ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/botlib.h File Reference
botlib.h File Reference
Classes
struct bot_input_s
struct bsp_surface_s
struct bsp_trace_s
struct bot_entitystate_s
struct botlib_import_s
struct aas_export_s
struct ea_export_s
struct ai_export_s
struct botlib_export_s
Macros
#define BOTLIB_API_VERSION 2
#define BOTFILESBASEFOLDER "botfiles"
#define LINECOLOR_NONE -1
#define LINECOLOR_RED 1
#define LINECOLOR_GREEN 2
#define LINECOLOR_BLUE 3
#define LINECOLOR_YELLOW 4
#define LINECOLOR_ORANGE 5
#define PRT_MESSAGE 1
#define PRT_WARNING 2
#define PRT_ERROR 3
#define PRT_FATAL 4
#define PRT_EXIT 5
#define CMS_NORMAL 0
#define CMS_CHAT 1
#define BLERR_NOERROR 0
#define BLERR_LIBRARYNOTSETUP 1
#define BLERR_INVALIDENTITYNUMBER 2
#define BLERR_NOAASFILE 3
#define BLERR_CANNOTOPENAASFILE 4
#define BLERR_WRONGAASFILEID 5
#define BLERR_WRONGAASFILEVERSION 6
#define BLERR_CANNOTREADAASLUMP 7
#define BLERR_CANNOTLOADICHAT 8
#define BLERR_CANNOTLOADITEMWEIGHTS 9
#define BLERR_CANNOTLOADITEMCONFIG 10
#define BLERR_CANNOTLOADWEAPONWEIGHTS 11
#define BLERR_CANNOTLOADWEAPONCONFIG 12
#define ACTION_ATTACK 0x00000001
#define ACTION_USE 0x00000002
#define ACTION_RESPAWN 0x00000008
#define ACTION_JUMP 0x00000010
#define ACTION_MOVEUP 0x00000020
#define ACTION_CROUCH 0x00000080
#define ACTION_MOVEDOWN 0x00000100
#define ACTION_MOVEFORWARD 0x00000200
#define ACTION_MOVEBACK 0x00000800
#define ACTION_MOVELEFT 0x00001000
#define ACTION_MOVERIGHT 0x00002000
#define ACTION_DELAYEDJUMP 0x00008000
#define ACTION_TALK 0x00010000
#define ACTION_GESTURE 0x00020000
#define ACTION_WALK 0x00080000
#define ACTION_AFFIRMATIVE 0x00100000
#define ACTION_NEGATIVE 0x00200000
#define ACTION_GETFLAG 0x00800000
#define ACTION_GUARDBASE 0x01000000
#define ACTION_PATROL 0x02000000
#define ACTION_FOLLOWME 0x08000000
#define ACTION_JUMPEDLASTFRAME 0x10000000
#define BSPTRACE
Typedefs
typedef struct bot_input_s bot_input_t
typedef struct bsp_surface_s bsp_surface_t
typedef struct bsp_trace_s bsp_trace_t
typedef struct bot_entitystate_s bot_entitystate_t
typedef struct botlib_import_s botlib_import_t
typedef struct aas_export_s aas_export_t
typedef struct ea_export_s ea_export_t
typedef struct ai_export_s ai_export_t
typedef struct botlib_export_s botlib_export_t
Functions
botlib_export_t * GetBotLibAPI (int apiVersion, botlib_import_t *import)
Macro Definition Documentation
ACTION_AFFIRMATIVE
#define ACTION_AFFIRMATIVE 0x00100000
Definition at line 97 of file botlib.h.
ACTION_ATTACK
#define ACTION_ATTACK 0x00000001
Definition at line 82 of file botlib.h.
ACTION_CROUCH
#define ACTION_CROUCH 0x00000080
Definition at line 87 of file botlib.h.
ACTION_DELAYEDJUMP
#define ACTION_DELAYEDJUMP 0x00008000
Definition at line 93 of file botlib.h.
ACTION_FOLLOWME
#define ACTION_FOLLOWME 0x08000000
Definition at line 102 of file botlib.h.
ACTION_GESTURE
#define ACTION_GESTURE 0x00020000
Definition at line 95 of file botlib.h.
ACTION_GETFLAG
#define ACTION_GETFLAG 0x00800000
Definition at line 99 of file botlib.h.
ACTION_GUARDBASE
#define ACTION_GUARDBASE 0x01000000
Definition at line 100 of file botlib.h.
ACTION_JUMP
#define ACTION_JUMP 0x00000010
Definition at line 85 of file botlib.h.
ACTION_JUMPEDLASTFRAME
#define ACTION_JUMPEDLASTFRAME 0x10000000
Definition at line 103 of file botlib.h.
ACTION_MOVEBACK
#define ACTION_MOVEBACK 0x00000800
Definition at line 90 of file botlib.h.
ACTION_MOVEDOWN
#define ACTION_MOVEDOWN 0x00000100
Definition at line 88 of file botlib.h.
ACTION_MOVEFORWARD
#define ACTION_MOVEFORWARD 0x00000200
Definition at line 89 of file botlib.h.
ACTION_MOVELEFT
#define ACTION_MOVELEFT 0x00001000
Definition at line 91 of file botlib.h.
ACTION_MOVERIGHT
#define ACTION_MOVERIGHT 0x00002000
Definition at line 92 of file botlib.h.
ACTION_MOVEUP
#define ACTION_MOVEUP 0x00000020
Definition at line 86 of file botlib.h.
ACTION_NEGATIVE
#define ACTION_NEGATIVE 0x00200000
Definition at line 98 of file botlib.h.
ACTION_PATROL
#define ACTION_PATROL 0x02000000
Definition at line 101 of file botlib.h.
ACTION_RESPAWN
#define ACTION_RESPAWN 0x00000008
Definition at line 84 of file botlib.h.
ACTION_TALK
#define ACTION_TALK 0x00010000
Definition at line 94 of file botlib.h.
ACTION_USE
#define ACTION_USE 0x00000002
Definition at line 83 of file botlib.h.
ACTION_WALK
#define ACTION_WALK 0x00080000
Definition at line 96 of file botlib.h.
BLERR_CANNOTLOADICHAT
#define BLERR_CANNOTLOADICHAT 8
Definition at line 75 of file botlib.h.
BLERR_CANNOTLOADITEMCONFIG
#define BLERR_CANNOTLOADITEMCONFIG 10
Definition at line 77 of file botlib.h.
BLERR_CANNOTLOADITEMWEIGHTS
#define BLERR_CANNOTLOADITEMWEIGHTS 9
Definition at line 76 of file botlib.h.
BLERR_CANNOTLOADWEAPONCONFIG
#define BLERR_CANNOTLOADWEAPONCONFIG 12
Definition at line 79 of file botlib.h.
BLERR_CANNOTLOADWEAPONWEIGHTS
#define BLERR_CANNOTLOADWEAPONWEIGHTS 11
Definition at line 78 of file botlib.h.
BLERR_CANNOTOPENAASFILE
#define BLERR_CANNOTOPENAASFILE 4
Definition at line 71 of file botlib.h.
BLERR_CANNOTREADAASLUMP
#define BLERR_CANNOTREADAASLUMP 7
Definition at line 74 of file botlib.h.
BLERR_INVALIDENTITYNUMBER
#define BLERR_INVALIDENTITYNUMBER 2
Definition at line 69 of file botlib.h.
BLERR_LIBRARYNOTSETUP
#define BLERR_LIBRARYNOTSETUP 1
Definition at line 68 of file botlib.h.
BLERR_NOAASFILE
#define BLERR_NOAASFILE 3
Definition at line 70 of file botlib.h.
BLERR_NOERROR
#define BLERR_NOERROR 0
Definition at line 67 of file botlib.h.
BLERR_WRONGAASFILEID
#define BLERR_WRONGAASFILEID 5
Definition at line 72 of file botlib.h.
BLERR_WRONGAASFILEVERSION
#define BLERR_WRONGAASFILEVERSION 6
Definition at line 73 of file botlib.h.
BOTFILESBASEFOLDER
#define BOTFILESBASEFOLDER "botfiles"
Definition at line 46 of file botlib.h.
BOTLIB_API_VERSION
#define BOTLIB_API_VERSION 2
Definition at line 32 of file botlib.h.
BSPTRACE
#define BSPTRACE
Definition at line 118 of file botlib.h.
CMS_CHAT
#define CMS_CHAT 1
Definition at line 64 of file botlib.h.
CMS_NORMAL
#define CMS_NORMAL 0
Definition at line 63 of file botlib.h.
LINECOLOR_BLUE
#define LINECOLOR_BLUE 3
Definition at line 51 of file botlib.h.
LINECOLOR_GREEN
#define LINECOLOR_GREEN 2
Definition at line 50 of file botlib.h.
LINECOLOR_NONE
#define LINECOLOR_NONE -1
Definition at line 48 of file botlib.h.
LINECOLOR_ORANGE
#define LINECOLOR_ORANGE 5
Definition at line 53 of file botlib.h.
LINECOLOR_RED
#define LINECOLOR_RED 1
Definition at line 49 of file botlib.h.
LINECOLOR_YELLOW
#define LINECOLOR_YELLOW 4
Definition at line 52 of file botlib.h.
PRT_ERROR
#define PRT_ERROR 3
Definition at line 58 of file botlib.h.
PRT_EXIT
#define PRT_EXIT 5
Definition at line 60 of file botlib.h.
PRT_FATAL
#define PRT_FATAL 4
Definition at line 59 of file botlib.h.
PRT_MESSAGE
#define PRT_MESSAGE 1
Definition at line 56 of file botlib.h.
PRT_WARNING
#define PRT_WARNING 2
Definition at line 57 of file botlib.h.
Typedef Documentation
aas_export_t
typedef struct aas_export_s aas_export_t
ai_export_t
typedef struct ai_export_s ai_export_t
bot_entitystate_t
typedef struct bot_entitystate_s bot_entitystate_t
bot_input_t
typedef struct bot_input_s bot_input_t
botlib_export_t
typedef struct botlib_export_s botlib_export_t
botlib_import_t
typedef struct botlib_import_s botlib_import_t
bsp_surface_t
typedef struct bsp_surface_s bsp_surface_t
bsp_trace_t
typedef struct bsp_trace_s bsp_trace_t
ea_export_t
typedef struct ea_export_s ea_export_t
Function Documentation
GetBotLibAPI()
botlib_export_t* GetBotLibAPI (int apiVersion, botlib_import_t * import)
Definition at line 852 of file be_interface.c.
{
     assert(import);
     botimport = *import;
     assert(botimport.Print);
     Com_Memset( &be_botlib_export, 0, sizeof( be_botlib_export ) );
     if ( apiVersion != BOTLIB_API_VERSION ) {
         botimport.Print( PRT_ERROR, "Mismatched BOTLIB_API_VERSION: expected %i, got %i\n", BOTLIB_API_VERSION, apiVersion );
         return NULL;
     }
     Init_AAS_Export(&be_botlib_export.aas);
     Init_EA_Export(&be_botlib_export.ea);
     Init_AI_Export(&be_botlib_export.ai);
     be_botlib_export.BotLibSetup = Export_BotLibSetup;
     be_botlib_export.BotLibShutdown = Export_BotLibShutdown;
     be_botlib_export.BotLibVarSet = Export_BotLibVarSet;
     be_botlib_export.BotLibVarGet = Export_BotLibVarGet;
     be_botlib_export.PC_AddGlobalDefine = PC_AddGlobalDefine;
     be_botlib_export.PC_LoadSourceHandle = PC_LoadSourceHandle;
     be_botlib_export.PC_FreeSourceHandle = PC_FreeSourceHandle;
     be_botlib_export.PC_ReadTokenHandle = PC_ReadTokenHandle;
     be_botlib_export.PC_SourceFileAndLine = PC_SourceFileAndLine;
     be_botlib_export.BotLibStartFrame = Export_BotLibStartFrame;
     be_botlib_export.BotLibLoadMap = Export_BotLibLoadMap;
     be_botlib_export.BotLibUpdateEntity = Export_BotLibUpdateEntity;
     be_botlib_export.Test = BotExportTest;
     return &be_botlib_export;
 }
References botlib_export_s::aas, botlib_export_s::ai, be_botlib_export, BotExportTest(), botimport, BOTLIB_API_VERSION, botlib_export_s::BotLibLoadMap, botlib_export_s::BotLibSetup, botlib_export_s::BotLibShutdown, botlib_export_s::BotLibStartFrame, botlib_export_s::BotLibUpdateEntity, botlib_export_s::BotLibVarGet, botlib_export_s::BotLibVarSet, Com_Memset, botlib_export_s::ea, Export_BotLibLoadMap(), Export_BotLibSetup(), Export_BotLibShutdown(), Export_BotLibStartFrame(), Export_BotLibUpdateEntity(), Export_BotLibVarGet(), Export_BotLibVarSet(), Init_AAS_Export(), Init_AI_Export(), Init_EA_Export(), NULL, botlib_export_s::PC_AddGlobalDefine, PC_AddGlobalDefine(), botlib_export_s::PC_FreeSourceHandle, PC_FreeSourceHandle(), botlib_export_s::PC_LoadSourceHandle, PC_LoadSourceHandle(), botlib_export_s::PC_ReadTokenHandle, PC_ReadTokenHandle(), botlib_export_s::PC_SourceFileAndLine, PC_SourceFileAndLine(), PRT_ERROR, and botlib_export_s::Test.
Referenced by SV_BotInitBotLib().