ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/ai_vcmd.h File Reference
ai_vcmd.h File Reference
Functions
int BotVoiceChatCommand (bot_state_t *bs, int mode, char *voicechat)
void BotVoiceChat_Defend (bot_state_t *bs, int client, int mode)
Function Documentation
BotVoiceChat_Defend()
void BotVoiceChat_Defend (bot_state_t * bs, int client, int mode)
Definition at line 172 of file ai_vcmd.c.
{
 #ifdef MISSIONPACK
     if ( gametype == GT_OBELISK || gametype == GT_HARVESTER) {
         //
         switch(BotTeam(bs)) {
             case TEAM_RED: memcpy(&bs->teamgoal, &redobelisk, sizeof(bot_goal_t)); break;
             case TEAM_BLUE: memcpy(&bs->teamgoal, &blueobelisk, sizeof(bot_goal_t)); break;
             default: return;
         }
     }
     else
 #endif
         if (gametype == GT_CTF
 #ifdef MISSIONPACK
             || gametype == GT_1FCTF
 #endif
             ) {
         //
         switch(BotTeam(bs)) {
             case TEAM_RED: memcpy(&bs->teamgoal, &ctf_redflag, sizeof(bot_goal_t)); break;
             case TEAM_BLUE: memcpy(&bs->teamgoal, &ctf_blueflag, sizeof(bot_goal_t)); break;
             default: return;
         }
     }
     else {
         return;
     }
     //
     bs->decisionmaker = client;
     bs->ordered = qtrue;
     bs->order_time = FloatTime();
     //set the time to send a message to the team mates
     bs->teammessage_time = FloatTime() + 2 * random();
     //set the ltg type
     bs->ltgtype = LTG_DEFENDKEYAREA;
     //get the team goal time
     bs->teamgoal_time = FloatTime() + TEAM_DEFENDKEYAREA_TIME;
     //away from defending
     bs->defendaway_time = 0;
     //
     BotSetTeamStatus(bs);
     // remember last ordered task
     BotRememberLastOrderedTask(bs);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
Referenced by BotVoiceChat_DefendFlag(), and FindHumanTeamLeader().
BotVoiceChatCommand()
int BotVoiceChatCommand (bot_state_t * bs, int mode, char * voicechat)
Definition at line 515 of file ai_vcmd.c.
{
     int i, clientNum;
     //int voiceOnly, color;
     char *ptr, buf[MAX_MESSAGE_SIZE], *cmd;
     if (!TeamPlayIsOn()) {
         return qfalse;
     }
     if ( mode == SAY_ALL ) {
         return qfalse;  // don't do anything with voice chats to everyone
     }
     Q_strncpyz(buf, voiceChat, sizeof(buf));
     cmd = buf;
     for (; *cmd && *cmd > ' '; cmd++);
     while (*cmd && *cmd <= ' ') *cmd++ = '\0';
     //voiceOnly = atoi(ptr);
     for (ptr = cmd; *cmd && *cmd > ' '; cmd++);
     while (*cmd && *cmd <= ' ') *cmd++ = '\0';
     clientNum = atoi(ptr);
     for (; *cmd && *cmd > ' '; cmd++);
     while (*cmd && *cmd <= ' ') *cmd++ = '\0';
     //color = atoi(ptr);
     if (!BotSameTeam(bs, clientNum)) {
         return qfalse;
     }
     for (i = 0; voiceCommands[i].cmd; i++) {
         if (!Q_stricmp(cmd, voiceCommands[i].cmd)) {
             voiceCommands[i].func(bs, clientNum, mode);
             return qtrue;
         }
     }
     return qfalse;
 }
Referenced by BotAI().