ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_memory.c File Reference
l_memory.c File Reference
#include "../qcommon/q_shared.h"
#include "botlib.h"
#include "l_log.h"
#include "l_memory.h"
#include "be_interface.h"
Macros
#define MEM_ID 0x12345678l
#define HUNK_ID 0x87654321l
Functions
void * GetMemory (unsigned long size)
void * GetClearedMemory (unsigned long size)
void * GetHunkMemory (unsigned long size)
void * GetClearedHunkMemory (unsigned long size)
void FreeMemory (void *ptr)
int AvailableMemory (void)
void PrintUsedMemorySize (void)
void PrintMemoryLabels (void)
Variables
int allocatedmemory
int totalmemorysize
int numblocks
Macro Definition Documentation
HUNK_ID
#define HUNK_ID 0x87654321l
Definition at line 42 of file l_memory.c.
MEM_ID
#define MEM_ID 0x12345678l
Definition at line 41 of file l_memory.c.
Function Documentation
AvailableMemory()
int AvailableMemory (void)
Definition at line 441 of file l_memory.c.
 {
     return botimport.AvailableMemory();
 } //end of the function AvailableMemory
Referenced by AAS_AreaRouteToGoalArea().
FreeMemory()
void FreeMemory (void * ptr)
Definition at line 424 of file l_memory.c.
 {
     unsigned long int *memid;
     memid = (unsigned long int *) ((char *) ptr - sizeof(unsigned long int));
     if (*memid == MEM_ID)
     {
         botimport.FreeMemory(memid);
     } //end if
 } //end of the function FreeMemory
Referenced by AAS_CalculateAreaTravelTimes(), AAS_ContinueInitReachability(), AAS_CreateReversedReachability(), AAS_DumpAASData(), AAS_DumpBSPData(), AAS_FloodAreas(), AAS_FreeAASLinkedEntities(), AAS_FreeAASLinkHeap(), AAS_FreeAllClusterAreaCache(), AAS_FreeAllPortalCache(), AAS_FreeBSPEntities(), AAS_FreeRoutingCache(), AAS_FreeRoutingCaches(), AAS_InitAASLinkedEntities(), AAS_InitAlternativeRouting(), AAS_InitAreaContentsTravelFlags(), AAS_InitClustering(), AAS_InitPortalMaxTravelTimes(), AAS_InitReachabilityAreas(), AAS_InitRoutingUpdate(), AAS_OptimizeStore(), AAS_Setup(), AAS_Shutdown(), AAS_ShutdownAlternativeRouting(), AAS_ShutDownReachabilityHeap(), AAS_StoreReachability(), BotCheckInitialChatIntegrety(), BotCheckReplyChatIntegrety(), BotFreeCharacter2(), BotFreeCharacterStrings(), BotFreeChatFile(), BotFreeChatState(), BotFreeGoalState(), BotFreeInfoEntities(), BotFreeItemWeights(), BotFreeMatchPieces(), BotFreeMatchTemplates(), BotFreeMoveState(), BotFreeReplyChat(), BotFreeWeaponState(), BotFreeWeaponWeights(), BotInitInfoEntities(), BotLoadCharacterFromFile(), BotShutdownChatAI(), BotShutdownGoalAI(), BotShutdownMoveAI(), BotShutdownWeaponAI(), EA_Shutdown(), FreeFuzzySeperators_r(), FreeScript(), FreeSource(), FreeWeightConfig2(), InitConsoleMessageHeap(), InitLevelItemHeap(), LibVarDeAlloc(), LibVarSet(), LoadItemConfig(), LoadScriptFile(), LoadWeaponConfig(), PC_DefineFromString(), PC_FreeDefine(), PC_FreeToken(), PC_PopIndent(), and ReadWeightConfig().
GetClearedHunkMemory()
void* GetClearedHunkMemory (unsigned long size)
Definition at line 406 of file l_memory.c.
 {
     void *ptr;
 #ifdef MEMDEBUG
     ptr = GetHunkMemoryDebug(size, label, file, line);
 #else
     ptr = GetHunkMemory(size);
 #endif //MEMDEBUG
     Com_Memset(ptr, 0, size);
     return ptr;
 } //end of the function GetClearedHunkMemory
Referenced by AAS_InitAASLinkedEntities(), AAS_LoadAASLump(), AAS_LoadBSPFile(), AAS_ParseBSPEntities(), AAS_Setup(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), EA_Setup(), InitConsoleMessageHeap(), LoadItemConfig(), and LoadWeaponConfig().
GetClearedMemory()
void* GetClearedMemory (unsigned long size)
Definition at line 364 of file l_memory.c.
 {
     void *ptr;
 #ifdef MEMDEBUG
     ptr = GetMemoryDebug(size, label, file, line);
 #else
     ptr = GetMemory(size);
 #endif //MEMDEBUG
     Com_Memset(ptr, 0, size);
     return ptr;
 } //end of the function GetClearedMemory
Referenced by AAS_AllocRoutingCache(), AAS_CalculateAreaTravelTimes(), AAS_CreateReversedReachability(), AAS_FloodAreas(), AAS_InitAreaContentsTravelFlags(), AAS_InitClusterAreaCache(), AAS_InitClustering(), AAS_InitPortalCache(), AAS_InitPortalMaxTravelTimes(), AAS_InitReachability(), AAS_InitReachabilityAreas(), AAS_InitRoutingUpdate(), AAS_NearestHideArea(), AAS_OptimizeAlloc(), AAS_SetupReachabilityHeap(), AAS_StoreReachability(), BotAllocChatState(), BotAllocGoalState(), BotAllocMoveState(), BotAllocWeaponState(), BotCheckChatMessageIntegrety(), BotInitInfoEntities(), BotInterpolateCharacters(), BotLoadCharacterFromFile(), BotLoadChatFile(), BotLoadInitialChat(), InitLevelItemHeap(), ItemWeightIndex(), LoadScriptFile(), LoadScriptMemory(), LoadSourceFile(), LoadSourceMemory(), PC_DefineFromString(), ReadFuzzySeperators_r(), ReadWeightConfig(), and WeaponWeightIndex().
GetHunkMemory()
void* GetHunkMemory (unsigned long size)
Definition at line 385 of file l_memory.c.
 {
     void *ptr;
     unsigned long int *memid;
     ptr = botimport.HunkAlloc(size + sizeof(unsigned long int));
     if (!ptr) return NULL;
     memid = (unsigned long int *) ptr;
     *memid = HUNK_ID;
     return (unsigned long int *) ((char *) ptr + sizeof(unsigned long int));
 } //end of the function GetHunkMemory
Referenced by AAS_InitAASLinkHeap(), AAS_ParseBSPEntities(), and GetClearedHunkMemory().
GetMemory()
void* GetMemory (unsigned long size)
Definition at line 343 of file l_memory.c.
 {
     void *ptr;
     unsigned long int *memid;
     ptr = botimport.GetMemory(size + sizeof(unsigned long int));
     if (!ptr) return NULL;
     memid = (unsigned long int *) ptr;
     *memid = MEM_ID;
     return (unsigned long int *) ((char *) ptr + sizeof(unsigned long int));
 } //end of the function GetMemory
Referenced by AAS_InitAlternativeRouting(), AAS_ReadCache(), BotDefaultCharacteristics(), BotInterpolateCharacters(), BotLoadCharacterFromFile(), GetClearedMemory(), LibVar(), LibVarAlloc(), LibVarSet(), LoadSourceFile(), LoadSourceMemory(), PC_AddBuiltinDefines(), PC_CopyDefine(), PC_CopyToken(), PC_Directive_define(), PC_PushIndent(), and PS_CreatePunctuationTable().
PrintMemoryLabels()
void PrintMemoryLabels (void)
Definition at line 460 of file l_memory.c.
 {
 } //end of the function PrintMemoryLabels
Referenced by AAS_StartFrame(), and Export_BotLibShutdown().
PrintUsedMemorySize()
void PrintUsedMemorySize (void)
Definition at line 451 of file l_memory.c.
 {
 } //end of the function PrintUsedMemorySize
Referenced by AAS_StartFrame().
Variable Documentation
allocatedmemory
int allocatedmemory
Definition at line 44 of file l_memory.c.
numblocks
int numblocks
Definition at line 46 of file l_memory.c.
totalmemorysize
int totalmemorysize
Definition at line 45 of file l_memory.c.