ioquake3 doxygen: C:/entry/dev/ioq3/code/sys/con_log.c File Reference
con_log.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "sys_local.h"
Macros
#define MAX_LOG 32768
Functions
unsigned int CON_LogSize (void)
static unsigned int CON_LogFree (void)
unsigned int CON_LogWrite (const char *in)
unsigned int CON_LogRead (char *out, unsigned int outSize)
Variables
static char consoleLog [MAX_LOG]
static unsigned int writePos = 0
static unsigned int readPos = 0
Macro Definition Documentation
MAX_LOG
#define MAX_LOG 32768
Definition at line 27 of file con_log.c.
Function Documentation
CON_LogFree()
static unsigned int CON_LogFree (void) static
Definition at line 51 of file con_log.c.
 {
     return MAX_LOG - CON_LogSize( ) - 1;
 }
References CON_LogSize(), and MAX_LOG.
Referenced by CON_LogWrite().
CON_LogRead()
unsigned int CON_LogRead (char * out, unsigned int outSize)
Definition at line 104 of file con_log.c.
 {
     unsigned int firstChunk;
     unsigned int secondChunk;
     if( CON_LogSize( ) < outSize )
         outSize = CON_LogSize( );
     if( readPos + outSize > MAX_LOG )
     {
         firstChunk  = MAX_LOG - readPos;
         secondChunk = outSize - firstChunk;
     }
     else
     {
         firstChunk  = outSize;
         secondChunk = 0;
     }
     Com_Memcpy( out, consoleLog + readPos, firstChunk );
     Com_Memcpy( out + firstChunk, consoleLog, secondChunk );
     readPos = ( readPos + outSize ) % MAX_LOG;
     return outSize;
 }
References Com_Memcpy, CON_LogSize(), consoleLog, MAX_LOG, and readPos.
Referenced by Sys_ErrorDialog().
CON_LogSize()
unsigned int CON_LogSize (void)
Definition at line 38 of file con_log.c.
 {
     if( readPos <= writePos )
         return writePos - readPos;
     else
         return writePos + MAX_LOG - readPos;
 }
References MAX_LOG, readPos, and writePos.
Referenced by CON_LogFree(), CON_LogRead(), CON_LogWrite(), and Sys_ErrorDialog().
CON_LogWrite()
unsigned int CON_LogWrite (const char * in)
Definition at line 61 of file con_log.c.
 {
     unsigned int length = strlen( in );
     unsigned int firstChunk;
     unsigned int secondChunk;
     while( CON_LogFree( ) < length && CON_LogSize( ) > 0 )
     {
         // Free enough space
         while( consoleLog[ readPos ] != '\n' && CON_LogSize( ) > 1 )
             readPos = ( readPos + 1 ) % MAX_LOG;
         // Skip past the '\n'
         readPos = ( readPos + 1 ) % MAX_LOG;
     }
     if( CON_LogFree( ) < length )
         return 0;
     if( writePos + length > MAX_LOG )
     {
         firstChunk  = MAX_LOG - writePos;
         secondChunk = length - firstChunk;
     }
     else
     {
         firstChunk  = length;
         secondChunk = 0;
     }
     Com_Memcpy( consoleLog + writePos, in, firstChunk );
     Com_Memcpy( consoleLog, in + firstChunk, secondChunk );
     writePos = ( writePos + length ) % MAX_LOG;
     return length;
 }
References Com_Memcpy, CON_LogFree(), CON_LogSize(), consoleLog, in, MAX_LOG, readPos, and writePos.
Referenced by Sys_Print().
Variable Documentation
consoleLog
char consoleLog[MAX_LOG] static
Definition at line 29 of file con_log.c.
Referenced by CON_LogRead(), and CON_LogWrite().
readPos
unsigned int readPos = 0 static
Definition at line 31 of file con_log.c.
Referenced by CON_LogRead(), CON_LogSize(), and CON_LogWrite().
writePos
unsigned int writePos = 0 static
Definition at line 30 of file con_log.c.
Referenced by CON_LogSize(), CON_LogWrite(), and CON_Show().