ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_local.h File Reference
ui_local.h File Reference
#include "../qcommon/q_shared.h"
#include "../renderercommon/tr_types.h"
#include "../ui/ui_public.h"
#include "../client/keycodes.h"
#include "../game/bg_public.h"
Classes
struct _tag_menuframework
struct menucommon_s
struct mfield_t
struct menufield_s
struct menuslider_s
struct menulist_s
struct menuaction_s
struct menuradiobutton_s
struct menubitmap_s
struct menutext_s
struct lerpFrame_t
struct playerInfo_t
struct uiStatic_t
Macros
#define UI_API_VERSION 4
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
#define SLIDER_RANGE 10
#define MAX_EDIT_LINE 256
#define MAX_MENUDEPTH 8
#define MAX_MENUITEMS 64
#define MTYPE_NULL 0
#define MTYPE_SLIDER 1
#define MTYPE_ACTION 2
#define MTYPE_SPINCONTROL 3
#define MTYPE_FIELD 4
#define MTYPE_RADIOBUTTON 5
#define MTYPE_BITMAP 6
#define MTYPE_TEXT 7
#define MTYPE_SCROLLLIST 8
#define MTYPE_PTEXT 9
#define MTYPE_BTEXT 10
#define QMF_BLINK ((unsigned int) 0x00000001)
#define QMF_SMALLFONT ((unsigned int) 0x00000002)
#define QMF_LEFT_JUSTIFY ((unsigned int) 0x00000004)
#define QMF_CENTER_JUSTIFY ((unsigned int) 0x00000008)
#define QMF_RIGHT_JUSTIFY ((unsigned int) 0x00000010)
#define QMF_NUMBERSONLY ((unsigned int) 0x00000020)
#define QMF_HIGHLIGHT ((unsigned int) 0x00000040)
#define QMF_HIGHLIGHT_IF_FOCUS ((unsigned int) 0x00000080)
#define QMF_PULSEIFFOCUS ((unsigned int) 0x00000100)
#define QMF_HASMOUSEFOCUS ((unsigned int) 0x00000200)
#define QMF_NOONOFFTEXT ((unsigned int) 0x00000400)
#define QMF_MOUSEONLY ((unsigned int) 0x00000800)
#define QMF_HIDDEN ((unsigned int) 0x00001000)
#define QMF_GRAYED ((unsigned int) 0x00002000)
#define QMF_INACTIVE ((unsigned int) 0x00004000)
#define QMF_NODEFAULTINIT ((unsigned int) 0x00008000)
#define QMF_OWNERDRAW ((unsigned int) 0x00010000)
#define QMF_PULSE ((unsigned int) 0x00020000)
#define QMF_LOWERCASE ((unsigned int) 0x00040000)
#define QMF_UPPERCASE ((unsigned int) 0x00080000)
#define QMF_SILENT ((unsigned int) 0x00100000)
#define QM_GOTFOCUS 1
#define QM_LOSTFOCUS 2
#define QM_ACTIVATED 3
#define MAX_FAVORITESERVERS 16
Typedefs
typedef void(* voidfunc_f) (void)
typedef struct _tag_menuframework menuframework_s
Enumerations
enum awardType_t {
AWARD_ACCURACY, AWARD_IMPRESSIVE, AWARD_EXCELLENT, AWARD_GAUNTLET,
AWARD_FRAGS, AWARD_PERFECT, AWARD_ACCURACY, AWARD_IMPRESSIVE,
AWARD_EXCELLENT, AWARD_GAUNTLET, AWARD_FRAGS, AWARD_PERFECT
}
Functions
void Menu_Cache (void)
void Menu_Focus (menucommon_s *m)
void Menu_AddItem (menuframework_s *menu, void *item)
void Menu_AdjustCursor (menuframework_s *menu, int dir)
void Menu_Draw (menuframework_s *menu)
void * Menu_ItemAtCursor (menuframework_s *m)
sfxHandle_t Menu_ActivateItem (menuframework_s *s, menucommon_s *item)
void Menu_SetCursor (menuframework_s *s, int cursor)
void Menu_SetCursorToItem (menuframework_s *m, void *ptr)
sfxHandle_t Menu_DefaultKey (menuframework_s *s, int key)
void Bitmap_Init (menubitmap_s *b)
void Bitmap_Draw (menubitmap_s *b)
void ScrollList_Draw (menulist_s *l)
sfxHandle_t ScrollList_Key (menulist_s *l, int key)
void MField_Clear (mfield_t *edit)
void MField_KeyDownEvent (mfield_t *edit, int key)
void MField_CharEvent (mfield_t *edit, int ch)
void MField_Draw (mfield_t *edit, int x, int y, int style, vec4_t color)
void MenuField_Init (menufield_s *m)
void MenuField_Draw (menufield_s *f)
sfxHandle_t MenuField_Key (menufield_s *m, int *key)
void MainMenu_Cache (void)
void UI_MainMenu (void)
void UI_RegisterCvars (void)
void UI_UpdateCvars (void)
void UI_CreditMenu (void)
void InGame_Cache (void)
void UI_InGameMenu (void)
void ConfirmMenu_Cache (void)
void UI_ConfirmMenu (const char *question, void(*draw)(void), void(*action)(qboolean result))
void UI_ConfirmMenu_Style (const char *question, int style, void(*draw)(void), void(*action)(qboolean result))
void UI_Message (const char **lines)
void UI_SetupMenu_Cache (void)
void UI_SetupMenu (void)
void UI_TeamMainMenu (void)
void TeamMain_Cache (void)
void UI_DrawConnectScreen (qboolean overlay)
void UI_ControlsMenu (void)
void Controls_Cache (void)
void UI_DemosMenu (void)
void Demos_Cache (void)
void UI_CinematicsMenu (void)
void UI_CinematicsMenu_f (void)
void UI_CinematicsMenu_Cache (void)
void UI_ModsMenu (void)
void UI_ModsMenu_Cache (void)
void UI_CDKeyMenu (void)
void UI_CDKeyMenu_Cache (void)
void UI_CDKeyMenu_f (void)
void UI_PlayerModelMenu (void)
void PlayerModel_Cache (void)
void UI_PlayerSettingsMenu (void)
void PlayerSettings_Cache (void)
void UI_PreferencesMenu (void)
void Preferences_Cache (void)
void UI_SpecifyLeagueMenu (void)
void SpecifyLeague_Cache (void)
void UI_SpecifyServerMenu (void)
void SpecifyServer_Cache (void)
void UI_ArenaServersMenu (void)
void ArenaServers_Cache (void)
void UI_StartServerMenu (qboolean multiplayer)
void StartServer_Cache (void)
void ServerOptions_Cache (void)
void UI_BotSelectMenu (char *bot)
void UI_BotSelectMenu_Cache (void)
void UI_ServerInfoMenu (void)
void ServerInfo_Cache (void)
void UI_GraphicsOptionsMenu (void)
void GraphicsOptions_Cache (void)
void DriverInfo_Cache (void)
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t *pi, int time)
void UI_PlayerInfo_SetModel (playerInfo_t *pi, const char *model)
void UI_PlayerInfo_SetInfo (playerInfo_t *pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNum, qboolean chat)
qboolean UI_RegisterClientModelname (playerInfo_t *pi, const char *modelSkinName)
void UI_Init (void)
void UI_Shutdown (void)
void UI_KeyEvent (int key, int down)
void UI_MouseEvent (int dx, int dy)
void UI_Refresh (int realtime)
qboolean UI_ConsoleCommand (int realTime)
float UI_ClampCvar (float min, float max, float value)
void UI_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_DrawRect (float x, float y, float width, float height, const float *color)
void UI_UpdateScreen (void)
void UI_SetColor (const float *rgba)
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
void UI_DrawBannerString (int x, int y, const char *str, int style, vec4_t color)
float UI_ProportionalSizeScale (int style)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
void UI_DrawProportionalString_AutoWrapped (int x, int ystart, int xmax, int ystep, const char *str, int style, vec4_t color)
int UI_ProportionalStringWidth (const char *str)
void UI_DrawString (int x, int y, const char *str, int style, vec4_t color)
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
qboolean UI_CursorInRect (int x, int y, int width, int height)
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
void UI_DrawTextBox (int x, int y, int width, int lines)
qboolean UI_IsFullscreen (void)
void UI_SetActiveMenu (uiMenuCommand_t menu)
void UI_PushMenu (menuframework_s *menu)
void UI_PopMenu (void)
void UI_ForceMenuOff (void)
char * UI_Argv (int arg)
char * UI_Cvar_VariableString (const char *var_name)
void UI_StartDemoLoop (void)
void UI_SPLevelMenu_Cache (void)
void UI_SPLevelMenu (void)
void UI_SPLevelMenu_f (void)
void UI_SPLevelMenu_ReInit (void)
void UI_SPArena_Start (const char *arenaInfo)
void UI_SPPostgameMenu_Cache (void)
void UI_SPPostgameMenu_f (void)
void UI_SPSkillMenu (const char *arenaInfo)
void UI_SPSkillMenu_Cache (void)
void trap_Print (const char *string)
trap_Print prints the string pointed to by fmt to the Q3 Console.
void trap_Error (const char *string) __attribute__((noreturn))
This is very similar to the trap_Print function with the exception that this will halt execution of the module it is called from.
int trap_Milliseconds (void)
Returns the number of milliseconds that have elapsed since Quake 3 was executed.
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
This function is used to create a new vmCvar.
void trap_Cvar_Update (vmCvar_t *vmCvar)
This function first parses out the name of the vmCvar and then searches for the corresponding database entry.
void trap_Cvar_Set (const char *var_name, const char *value)
This function searchs for the name of the vmCvar and stores the value into both the float and integer fields of the corresponding vmCvar entry.
float trap_Cvar_VariableValue (const char *var_name)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
void trap_Cvar_SetValue (const char *var_name, float value)
void trap_Cvar_Reset (const char *name)
void trap_Cvar_Create (const char *var_name, const char *var_value, int flags)
void trap_Cvar_InfoStringBuffer (int bit, char *buffer, int bufsize)
int trap_Argc (void)
Whenever a client issues a console command it can have arguments passed with it.
void trap_Argv (int n, char *buffer, int bufferLength)
This will fill the buffer pointed to by buffer with an argument to a client command where n is the argument to return.
void trap_Cmd_ExecuteText (int exec_when, const char *text)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
This opens a file specified by the string qpath and allocates a fileHandle_t (just a typedef int) to that file.
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
This reads len bytes of data from the file specified by f and fills buffer with it.
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
This writes len bytes of data from buffer to the file specified by f.
void trap_FS_FCloseFile (fileHandle_t f)
Closes the file specified by f.
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
This fills listbuf with a NULL delimited list of all the files in the directory specified by path ending in extension.
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
qhandle_t trap_R_RegisterModel (const char *name)
qhandle_t trap_R_RegisterSkin (const char *name)
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
void trap_R_ClearScene (void)
void trap_R_AddRefEntityToScene (const refEntity_t *re)
Physically added to the visuals in the game, after a new shader is set.
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
This function will add a light to the game at org, which has a radius of intensity units, and the colour data which is shown in the variables r, g, and b.
void trap_R_RenderScene (const refdef_t *fd)
void trap_R_SetColor (const float *rgba)
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void trap_UpdateScreen (void)
trap_UpdateScreen updates the screen.
int trap_CM_LerpTag (orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName)
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
void trap_Key_SetBinding (int keynum, const char *binding)
qboolean trap_Key_IsDown (int keynum)
Returns true is the indicated key is held down, returns false if not held down (released).
qboolean trap_Key_GetOverstrikeMode (void)
void trap_Key_SetOverstrikeMode (qboolean state)
void trap_Key_ClearStates (void)
int trap_Key_GetCatcher (void)
Returns a bitmask representing active key catchers.
void trap_Key_SetCatcher (int catcher)
Redirects key events to different module(s).
void trap_GetClipboardData (char *buf, int bufsize)
void trap_GetClientState (uiClientState_t *state)
void trap_GetGlconfig (glconfig_t *glconfig)
int trap_GetConfigString (int index, char *buff, int buffsize)
int trap_LAN_GetServerCount (int source)
void trap_LAN_GetServerAddressString (int source, int n, char *buf, int buflen)
void trap_LAN_GetServerInfo (int source, int n, char *buf, int buflen)
int trap_LAN_GetPingQueueCount (void)
int trap_LAN_ServerStatus (const char *serverAddress, char *serverStatus, int maxLen)
void trap_LAN_ClearPing (int n)
void trap_LAN_GetPing (int n, char *buf, int buflen, int *pingtime)
void trap_LAN_GetPingInfo (int n, char *buf, int buflen)
int trap_MemoryRemaining (void)
void trap_GetCDKey (char *buf, int buflen)
void trap_SetCDKey (char *buf)
qboolean trap_VerifyCDKey (const char *key, const char *chksum)
void trap_SetPbClStatus (int status)
void UI_AddBots_Cache (void)
void UI_AddBotsMenu (void)
void UI_RemoveBots_Cache (void)
void UI_RemoveBotsMenu (void)
void UI_TeamOrdersMenu (void)
void UI_TeamOrdersMenu_f (void)
void UI_TeamOrdersMenu_Cache (void)
void UI_LoadConfig_Cache (void)
void UI_LoadConfigMenu (void)
void UI_SaveConfigMenu_Cache (void)
void UI_SaveConfigMenu (void)
void UI_DisplayOptionsMenu_Cache (void)
void UI_DisplayOptionsMenu (void)
void UI_SoundOptionsMenu_Cache (void)
void UI_SoundOptionsMenu (void)
void UI_NetworkOptionsMenu_Cache (void)
void UI_NetworkOptionsMenu (void)
const char * UI_GetArenaInfoByNumber (int num)
const char * UI_GetArenaInfoByMap (const char *map)
const char * UI_GetSpecialArenaInfo (const char *tag)
int UI_GetNumArenas (void)
int UI_GetNumSPArenas (void)
int UI_GetNumSPTiers (void)
char * UI_GetBotInfoByNumber (int num)
char * UI_GetBotInfoByName (const char *name)
int UI_GetNumBots (void)
void UI_GetBestScore (int level, int *score, int *skill)
void UI_SetBestScore (int level, int score)
int UI_TierCompleted (int levelWon)
qboolean UI_ShowTierVideo (int tier)
qboolean UI_CanShowTierVideo (int tier)
int UI_GetCurrentGame (void)
void UI_NewGame (void)
void UI_LogAwardData (int award, int data)
int UI_GetAwardLevel (int award)
void UI_SPUnlock_f (void)
void UI_SPUnlockMedals_f (void)
void UI_InitGameinfo (void)
void Rankings_DrawText (void *self)
void Rankings_DrawName (void *self)
void Rankings_DrawPassword (void *self)
void Rankings_Cache (void)
void UI_RankingsMenu (void)
void Login_Cache (void)
void UI_LoginMenu (void)
void Signup_Cache (void)
void UI_SignupMenu (void)
void RankStatus_Cache (void)
void UI_RankStatusMenu (void)
Variables
vmCvar_t ui_ffa_fraglimit
vmCvar_t ui_ffa_timelimit
vmCvar_t ui_tourney_fraglimit
vmCvar_t ui_tourney_timelimit
vmCvar_t ui_team_fraglimit
vmCvar_t ui_team_timelimit
vmCvar_t ui_team_friendly
vmCvar_t ui_ctf_capturelimit
vmCvar_t ui_ctf_timelimit
vmCvar_t ui_ctf_friendly
vmCvar_t ui_arenasFile
vmCvar_t ui_botsFile
vmCvar_t ui_spScores1
vmCvar_t ui_spScores2
vmCvar_t ui_spScores3
vmCvar_t ui_spScores4
vmCvar_t ui_spScores5
vmCvar_t ui_spAwards
vmCvar_t ui_spVideos
vmCvar_t ui_spSkill
vmCvar_t ui_spSelection
vmCvar_t ui_browserMaster
vmCvar_t ui_browserGameType
vmCvar_t ui_browserSortKey
vmCvar_t ui_browserShowFull
vmCvar_t ui_browserShowEmpty
vmCvar_t ui_brassTime
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_marks
vmCvar_t ui_server1
vmCvar_t ui_server2
vmCvar_t ui_server3
vmCvar_t ui_server4
vmCvar_t ui_server5
vmCvar_t ui_server6
vmCvar_t ui_server7
vmCvar_t ui_server8
vmCvar_t ui_server9
vmCvar_t ui_server10
vmCvar_t ui_server11
vmCvar_t ui_server12
vmCvar_t ui_server13
vmCvar_t ui_server14
vmCvar_t ui_server15
vmCvar_t ui_server16
vmCvar_t ui_cdkey
vmCvar_t ui_cdkeychecked
vmCvar_t ui_ioq3
sfxHandle_t menu_in_sound
sfxHandle_t menu_move_sound
sfxHandle_t menu_out_sound
sfxHandle_t menu_buzz_sound
sfxHandle_t menu_null_sound
sfxHandle_t weaponChangeSound
vec4_t menu_text_color
vec4_t menu_grayed_color
vec4_t menu_dark_color
vec4_t menu_highlight_color
vec4_t menu_red_color
vec4_t menu_black_color
vec4_t menu_dim_color
vec4_t color_black
vec4_t color_white
vec4_t color_yellow
vec4_t color_blue
vec4_t color_orange
vec4_t color_red
vec4_t color_dim
vec4_t name_color
vec4_t list_color
vec4_t listbar_color
vec4_t text_color_disabled
vec4_t text_color_normal
vec4_t text_color_highlight
char * ui_medalNames []
char * ui_medalPicNames []
char * ui_medalSounds []
qboolean m_entersound
uiStatic_t uis
Macro Definition Documentation
LCOLUMN_OFFSET
#define LCOLUMN_OFFSET (-BIGCHAR_WIDTH)
Definition at line 103 of file ui_local.h.
MAX_EDIT_LINE
#define MAX_EDIT_LINE 256
Definition at line 106 of file ui_local.h.
MAX_FAVORITESERVERS
#define MAX_FAVORITESERVERS 16
Definition at line 423 of file ui_local.h.
MAX_MENUDEPTH
#define MAX_MENUDEPTH 8
Definition at line 108 of file ui_local.h.
MAX_MENUITEMS
#define MAX_MENUITEMS 64
Definition at line 109 of file ui_local.h.
MTYPE_ACTION
#define MTYPE_ACTION 2
Definition at line 113 of file ui_local.h.
MTYPE_BITMAP
#define MTYPE_BITMAP 6
Definition at line 117 of file ui_local.h.
MTYPE_BTEXT
#define MTYPE_BTEXT 10
Definition at line 121 of file ui_local.h.
MTYPE_FIELD
#define MTYPE_FIELD 4
Definition at line 115 of file ui_local.h.
MTYPE_NULL
#define MTYPE_NULL 0
Definition at line 111 of file ui_local.h.
MTYPE_PTEXT
#define MTYPE_PTEXT 9
Definition at line 120 of file ui_local.h.
MTYPE_RADIOBUTTON
#define MTYPE_RADIOBUTTON 5
Definition at line 116 of file ui_local.h.
MTYPE_SCROLLLIST
#define MTYPE_SCROLLLIST 8
Definition at line 119 of file ui_local.h.
MTYPE_SLIDER
#define MTYPE_SLIDER 1
Definition at line 112 of file ui_local.h.
MTYPE_SPINCONTROL
#define MTYPE_SPINCONTROL 3
Definition at line 114 of file ui_local.h.
MTYPE_TEXT
#define MTYPE_TEXT 7
Definition at line 118 of file ui_local.h.
QM_ACTIVATED
#define QM_ACTIVATED 3
Definition at line 148 of file ui_local.h.
QM_GOTFOCUS
#define QM_GOTFOCUS 1
Definition at line 146 of file ui_local.h.
QM_LOSTFOCUS
#define QM_LOSTFOCUS 2
Definition at line 147 of file ui_local.h.
QMF_BLINK
#define QMF_BLINK ((unsigned int) 0x00000001)
Definition at line 123 of file ui_local.h.
QMF_CENTER_JUSTIFY
#define QMF_CENTER_JUSTIFY ((unsigned int) 0x00000008)
Definition at line 126 of file ui_local.h.
QMF_GRAYED
#define QMF_GRAYED ((unsigned int) 0x00002000)
Definition at line 136 of file ui_local.h.
QMF_HASMOUSEFOCUS
#define QMF_HASMOUSEFOCUS ((unsigned int) 0x00000200)
Definition at line 132 of file ui_local.h.
QMF_HIDDEN
#define QMF_HIDDEN ((unsigned int) 0x00001000)
Definition at line 135 of file ui_local.h.
QMF_HIGHLIGHT
#define QMF_HIGHLIGHT ((unsigned int) 0x00000040)
Definition at line 129 of file ui_local.h.
QMF_HIGHLIGHT_IF_FOCUS
#define QMF_HIGHLIGHT_IF_FOCUS ((unsigned int) 0x00000080)
Definition at line 130 of file ui_local.h.
QMF_INACTIVE
#define QMF_INACTIVE ((unsigned int) 0x00004000)
Definition at line 137 of file ui_local.h.
QMF_LEFT_JUSTIFY
#define QMF_LEFT_JUSTIFY ((unsigned int) 0x00000004)
Definition at line 125 of file ui_local.h.
QMF_LOWERCASE
#define QMF_LOWERCASE ((unsigned int) 0x00040000)
Definition at line 141 of file ui_local.h.
QMF_MOUSEONLY
#define QMF_MOUSEONLY ((unsigned int) 0x00000800)
Definition at line 134 of file ui_local.h.
QMF_NODEFAULTINIT
#define QMF_NODEFAULTINIT ((unsigned int) 0x00008000)
Definition at line 138 of file ui_local.h.
QMF_NOONOFFTEXT
#define QMF_NOONOFFTEXT ((unsigned int) 0x00000400)
Definition at line 133 of file ui_local.h.
QMF_NUMBERSONLY
#define QMF_NUMBERSONLY ((unsigned int) 0x00000020)
Definition at line 128 of file ui_local.h.
QMF_OWNERDRAW
#define QMF_OWNERDRAW ((unsigned int) 0x00010000)
Definition at line 139 of file ui_local.h.
QMF_PULSE
#define QMF_PULSE ((unsigned int) 0x00020000)
Definition at line 140 of file ui_local.h.
QMF_PULSEIFFOCUS
#define QMF_PULSEIFFOCUS ((unsigned int) 0x00000100)
Definition at line 131 of file ui_local.h.
QMF_RIGHT_JUSTIFY
#define QMF_RIGHT_JUSTIFY ((unsigned int) 0x00000010)
Definition at line 127 of file ui_local.h.
QMF_SILENT
#define QMF_SILENT ((unsigned int) 0x00100000)
Definition at line 143 of file ui_local.h.
QMF_SMALLFONT
#define QMF_SMALLFONT ((unsigned int) 0x00000002)
Definition at line 124 of file ui_local.h.
QMF_UPPERCASE
#define QMF_UPPERCASE ((unsigned int) 0x00080000)
Definition at line 142 of file ui_local.h.
RCOLUMN_OFFSET
#define RCOLUMN_OFFSET (BIGCHAR_WIDTH)
Definition at line 102 of file ui_local.h.
SLIDER_RANGE
#define SLIDER_RANGE 10
Definition at line 105 of file ui_local.h.
UI_API_VERSION
#define UI_API_VERSION 4
Definition at line 32 of file ui_local.h.
Typedef Documentation
menuframework_s
typedef struct _tag_menuframework menuframework_s
voidfunc_f
typedef void(* voidfunc_f) (void)
Definition at line 36 of file ui_local.h.
Enumeration Type Documentation
awardType_t
enum awardType_t
Enumerator
AWARD_ACCURACY
AWARD_IMPRESSIVE
AWARD_EXCELLENT
AWARD_GAUNTLET
AWARD_FRAGS
AWARD_PERFECT
AWARD_ACCURACY
AWARD_IMPRESSIVE
AWARD_EXCELLENT
AWARD_GAUNTLET
AWARD_FRAGS
AWARD_PERFECT
Definition at line 744 of file ui_local.h.
              {
     AWARD_ACCURACY,
     AWARD_IMPRESSIVE,
     AWARD_EXCELLENT,
     AWARD_GAUNTLET,
     AWARD_FRAGS,
     AWARD_PERFECT
 } awardType_t;
Function Documentation
ArenaServers_Cache()
void ArenaServers_Cache (void)
Definition at line 1619 of file ui_servers2.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_CREATE0 );
     trap_R_RegisterShaderNoMip( ART_CREATE1 );
     trap_R_RegisterShaderNoMip( ART_SPECIFY0 );
     trap_R_RegisterShaderNoMip( ART_SPECIFY1 );
     trap_R_RegisterShaderNoMip( ART_REFRESH0 );
     trap_R_RegisterShaderNoMip( ART_REFRESH1 );
     trap_R_RegisterShaderNoMip( ART_CONNECT0 );
     trap_R_RegisterShaderNoMip( ART_CONNECT1 );
     trap_R_RegisterShaderNoMip( ART_ARROWS0  );
     trap_R_RegisterShaderNoMip( ART_ARROWS_UP );
     trap_R_RegisterShaderNoMip( ART_ARROWS_DOWN );
     trap_R_RegisterShaderNoMip( ART_UNKNOWNMAP );
     trap_R_RegisterShaderNoMip( ART_PUNKBUSTER );
 }
Referenced by UI_Cache_f().
Bitmap_Draw()
void Bitmap_Draw (menubitmap_s * b)
Definition at line 282 of file ui_qmenu.c.
 {
     float   x;
     float   y;
     float   w;
     float   h;
     vec4_t  tempcolor;
     float*  color;
     x = b->generic.x;
     y = b->generic.y;
     w = b->width;
     h = b->height;
     if (b->generic.flags & QMF_RIGHT_JUSTIFY)
     {
         x = x - w;
     }
     else if (b->generic.flags & QMF_CENTER_JUSTIFY)
     {
         x = x - w/2;
     }
     // used to refresh shader
     if (b->generic.name && !b->shader)
     {
         b->shader = trap_R_RegisterShaderNoMip( b->generic.name );
         if (!b->shader && b->errorpic)
             b->shader = trap_R_RegisterShaderNoMip( b->errorpic );
     }
     if (b->focuspic && !b->focusshader)
         b->focusshader = trap_R_RegisterShaderNoMip( b->focuspic );
     if (b->generic.flags & QMF_GRAYED)
     {
         if (b->shader)
         {
             trap_R_SetColor( colorMdGrey );
             UI_DrawHandlePic( x, y, w, h, b->shader );
             trap_R_SetColor( NULL );
         }
     }
     else
     {
         if (b->shader)
             UI_DrawHandlePic( x, y, w, h, b->shader );
         if (  ( (b->generic.flags & QMF_PULSE)
             || (b->generic.flags & QMF_PULSEIFFOCUS) )
               && (Menu_ItemAtCursor( b->generic.parent ) == b))
         {
             if (b->focuscolor)
             {
                 tempcolor[0] = b->focuscolor[0];
                 tempcolor[1] = b->focuscolor[1];
                 tempcolor[2] = b->focuscolor[2];
                 color        = tempcolor;
             }
             else
                 color = pulse_color;
             color[3] = 0.5+0.5*sin(uis.realtime/PULSE_DIVISOR);
             trap_R_SetColor( color );
             UI_DrawHandlePic( x, y, w, h, b->focusshader );
             trap_R_SetColor( NULL );
         }
         else if ((b->generic.flags & QMF_HIGHLIGHT) || ((b->generic.flags & QMF_HIGHLIGHT_IF_FOCUS) && (Menu_ItemAtCursor( b->generic.parent ) == b)))
         {
             if (b->focuscolor)
             {
                 trap_R_SetColor( b->focuscolor );
                 UI_DrawHandlePic( x, y, w, h, b->focusshader );
                 trap_R_SetColor( NULL );
             }
             else
                 UI_DrawHandlePic( x, y, w, h, b->focusshader );
         }
     }
 }
Referenced by ServerOptions_LevelshotDraw().
Bitmap_Init()
void Bitmap_Init (menubitmap_s * b)
Definition at line 241 of file ui_qmenu.c.
 {
     int x;
     int y;
     int w;
     int h;
     x = b->generic.x;
     y = b->generic.y;
     w = b->width;
     h = b->height;
     if( w < 0 ) {
         w = -w;
     }
     if( h < 0 ) {
         h = -h;
     }
     if (b->generic.flags & QMF_RIGHT_JUSTIFY)
     {
         x = x - w;
     }
     else if (b->generic.flags & QMF_CENTER_JUSTIFY)
     {
         x = x - w/2;
     }
     b->generic.left   = x;
     b->generic.right  = x + w;
     b->generic.top    = y;
     b->generic.bottom = y + h;
     b->shader      = 0;
     b->focusshader = 0;
 }
Referenced by UI_SPLevelMenu_SetMenuItems().
ConfirmMenu_Cache()
void ConfirmMenu_Cache (void)
Definition at line 163 of file ui_confirm.c.
{
     trap_R_RegisterShaderNoMip( ART_CONFIRM_FRAME );
 }
Controls_Cache()
void Controls_Cache (void)
Definition at line 1659 of file ui_controls2.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
Demos_Cache()
void Demos_Cache (void)
Definition at line 284 of file ui_demo2.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_GO0 );
     trap_R_RegisterShaderNoMip( ART_GO1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_ARROWS );
     trap_R_RegisterShaderNoMip( ART_ARROWLEFT );
     trap_R_RegisterShaderNoMip( ART_ARROWRIGHT );
 }
DriverInfo_Cache()
void DriverInfo_Cache (void)
Definition at line 122 of file ui_video.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!driverinfo_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(driverinfo_artlist[i]);
     }
 }
Referenced by UI_Cache_f().
GraphicsOptions_Cache()
void GraphicsOptions_Cache (void)
Definition at line 1295 of file ui_video.c.
{
     trap_R_RegisterShaderNoMip( GRAPHICSOPTIONS_FRAMEL );
     trap_R_RegisterShaderNoMip( GRAPHICSOPTIONS_FRAMER );
     trap_R_RegisterShaderNoMip( GRAPHICSOPTIONS_BACK0 );
     trap_R_RegisterShaderNoMip( GRAPHICSOPTIONS_BACK1 );
     trap_R_RegisterShaderNoMip( GRAPHICSOPTIONS_ACCEPT0 );
     trap_R_RegisterShaderNoMip( GRAPHICSOPTIONS_ACCEPT1 );
 }
Referenced by UI_Cache_f().
InGame_Cache()
void InGame_Cache (void)
Definition at line 329 of file ui_ingame.c.
{
     trap_R_RegisterShaderNoMip( INGAME_FRAME );
 }
Login_Cache()
void Login_Cache (void)
Definition at line 193 of file ui_login.c.
{
     trap_R_RegisterShaderNoMip( LOGIN_FRAME );
 }
MainMenu_Cache()
void MainMenu_Cache (void)
Definition at line 140 of file ui_menu.c.
{
     s_main.bannerModel = trap_R_RegisterModel( MAIN_BANNER_MODEL );
 }
Referenced by UI_Cache_f().
Menu_ActivateItem()
sfxHandle_t Menu_ActivateItem (menuframework_s * s, menucommon_s * item)
Definition at line 1598 of file ui_qmenu.c.
{
     if ( item->callback ) {
         item->callback( item, QM_ACTIVATED );
         if( !( item->flags & QMF_SILENT ) ) {
             return menu_move_sound;
         }
     }
     return 0;
 }
Menu_AddItem()
void Menu_AddItem (menuframework_s * menu, void * item)
Definition at line 1297 of file ui_qmenu.c.
 {
     menucommon_s    *itemptr;
     if (menu->nitems >= MAX_MENUITEMS)
         trap_Error ("Menu_AddItem: excessive items");
     menu->items[menu->nitems] = item;
     ((menucommon_s*)menu->items[menu->nitems])->parent        = menu;
     ((menucommon_s*)menu->items[menu->nitems])->menuPosition  = menu->nitems;
     ((menucommon_s*)menu->items[menu->nitems])->flags        &= ~QMF_HASMOUSEFOCUS;
     // perform any item specific initializations
     itemptr = (menucommon_s*)item;
     if (!(itemptr->flags & QMF_NODEFAULTINIT))
     {
         switch (itemptr->type)
         {
             case MTYPE_ACTION:
                 Action_Init((menuaction_s*)item);
                 break;
             case MTYPE_FIELD:
                 MenuField_Init((menufield_s*)item);
                 break;
             case MTYPE_SPINCONTROL:
                 SpinControl_Init((menulist_s*)item);
                 break;
             case MTYPE_RADIOBUTTON:
                 RadioButton_Init((menuradiobutton_s*)item);
                 break;
             case MTYPE_SLIDER:
                 Slider_Init((menuslider_s*)item);
                 break;
             case MTYPE_BITMAP:
                 Bitmap_Init((menubitmap_s*)item);
                 break;
             case MTYPE_TEXT:
                 Text_Init((menutext_s*)item);
                 break;
             case MTYPE_SCROLLLIST:
                 ScrollList_Init((menulist_s*)item);
                 break;
             case MTYPE_PTEXT:
                 PText_Init((menutext_s*)item);
                 break;
             case MTYPE_BTEXT:
                 BText_Init((menutext_s*)item);
                 break;
             default:
                 trap_Error( va("Menu_Init: unknown type %d", itemptr->type) );
         }
     }
     menu->nitems++;
 }
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), Demos_MenuInit(), GraphicsOptions_MenuInit(), InGame_MenuInit(), LoadConfig_MenuInit(), Login_MenuInit(), Options_MenuInit(), PlayerModel_MenuInit(), PlayerSettings_MenuInit(), Preferences_MenuInit(), Rankings_MenuInit(), RankStatus_MenuInit(), ServerOptions_MenuInit(), Signup_MenuInit(), SpecifyLeague_MenuInit(), SpecifyServer_MenuInit(), StartServer_MenuInit(), TeamMain_MenuInit(), UI_AddBotsMenu_Init(), UI_BotSelectMenu_Init(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Init(), UI_ConfirmMenu_Style(), UI_DisplayOptionsMenu_Init(), UI_DrawConnectScreen(), UI_DriverInfo_Menu(), UI_MainMenu(), UI_Message(), UI_Mods_MenuInit(), UI_NetworkOptionsMenu_Init(), UI_RemoveBotsMenu_Init(), UI_ResetMenu(), UI_SaveConfigMenu_Init(), UI_ServerInfoMenu(), UI_SetupMenu_Init(), UI_SoundOptionsMenu_Init(), UI_SPLevelMenu_Init(), UI_SPPostgameMenu_Init(), UI_SPSkillMenu_Init(), and UI_TeamOrdersMenu_Init().
Menu_AdjustCursor()
void Menu_AdjustCursor (menuframework_s * menu, int dir)
Definition at line 1435 of file ui_qmenu.c.
{
     menucommon_s    *item = NULL;
     qboolean        wrapped = qfalse;
 wrap:
     while ( m->cursor >= 0 && m->cursor < m->nitems ) {
         item = ( menucommon_s * ) m->items[m->cursor];
         if (( item->flags & (QMF_GRAYED|QMF_MOUSEONLY|QMF_INACTIVE) ) ) {
             m->cursor += dir;
         }
         else {
             break;
         }
     }
     if ( dir == 1 ) {
         if ( m->cursor >= m->nitems ) {
             if ( m->wrapAround ) {
                 if ( wrapped ) {
                     m->cursor = m->cursor_prev;
                     return;
                 }
                 m->cursor = 0;
                 wrapped = qtrue;
                 goto wrap;
             }
             m->cursor = m->cursor_prev;
         }
     }
     else {
         if ( m->cursor < 0 ) {
             if ( m->wrapAround ) {
                 if ( wrapped ) {
                     m->cursor = m->cursor_prev;
                     return;
                 }
                 m->cursor = m->nitems - 1;
                 wrapped = qtrue;
                 goto wrap;
             }
             m->cursor = m->cursor_prev;
         }
     }
 }
Menu_Cache()
void Menu_Cache (void)
Definition at line 1745 of file ui_qmenu.c.
 {
     uis.charset         = trap_R_RegisterShaderNoMip( "gfx/2d/bigchars" );
     uis.charsetProp     = trap_R_RegisterShaderNoMip( "menu/art/font1_prop.tga" );
     uis.charsetPropGlow = trap_R_RegisterShaderNoMip( "menu/art/font1_prop_glo.tga" );
     uis.charsetPropB    = trap_R_RegisterShaderNoMip( "menu/art/font2_prop.tga" );
     uis.cursor          = trap_R_RegisterShaderNoMip( "menu/art/3_cursor2" );
     uis.rb_on           = trap_R_RegisterShaderNoMip( "menu/art/switch_on" );
     uis.rb_off          = trap_R_RegisterShaderNoMip( "menu/art/switch_off" );
     uis.whiteShader = trap_R_RegisterShaderNoMip( "white" );
     if ( uis.glconfig.hardwareType == GLHW_RAGEPRO ) {
         // the blend effect turns to shit with the normal
         uis.menuBackShader  = trap_R_RegisterShaderNoMip( "menubackRagePro" );
     } else {
         uis.menuBackShader  = trap_R_RegisterShaderNoMip( "menuback" );
     }
     uis.menuBackNoLogoShader = trap_R_RegisterShaderNoMip( "menubacknologo" );
     menu_in_sound   = trap_S_RegisterSound( "sound/misc/menu1.wav", qfalse );
     menu_move_sound = trap_S_RegisterSound( "sound/misc/menu2.wav", qfalse );
     menu_out_sound  = trap_S_RegisterSound( "sound/misc/menu3.wav", qfalse );
     menu_buzz_sound = trap_S_RegisterSound( "sound/misc/menu4.wav", qfalse );
     weaponChangeSound   = trap_S_RegisterSound( "sound/weapons/change.wav", qfalse );
     // need a nonzero sound, make an empty sound for this
     menu_null_sound = -1;
     sliderBar = trap_R_RegisterShaderNoMip( "menu/art/slider2" );
     sliderButton_0 = trap_R_RegisterShaderNoMip( "menu/art/sliderbutt_0" );
     sliderButton_1 = trap_R_RegisterShaderNoMip( "menu/art/sliderbutt_1" );
 }
Referenced by UI_ConsoleCommand(), UI_DrawConnectScreen(), UI_Init(), and UI_SetActiveMenu().
Menu_DefaultKey()
sfxHandle_t Menu_DefaultKey (menuframework_s * s, int key)
Definition at line 1614 of file ui_qmenu.c.
 {
     sfxHandle_t     sound = 0;
     menucommon_s    *item;
     int             cursor_prev;
     // menu system keys
     switch ( key )
     {
         case K_MOUSE2:
         case K_ESCAPE:
             UI_PopMenu();
             return menu_out_sound;
     }
     if (!m || !m->nitems)
         return 0;
     // route key stimulus to widget
     item = Menu_ItemAtCursor( m );
     if (item && !(item->flags & (QMF_GRAYED|QMF_INACTIVE)))
     {
         switch (item->type)
         {
             case MTYPE_SPINCONTROL:
                 sound = SpinControl_Key( (menulist_s*)item, key );
                 break;
             case MTYPE_RADIOBUTTON:
                 sound = RadioButton_Key( (menuradiobutton_s*)item, key );
                 break;
             case MTYPE_SLIDER:
                 sound = Slider_Key( (menuslider_s*)item, key );
                 break;
             case MTYPE_SCROLLLIST:
                 sound = ScrollList_Key( (menulist_s*)item, key );
                 break;
             case MTYPE_FIELD:
                 sound = MenuField_Key( (menufield_s*)item, &key );
                 break;
         }
         if (sound) {
             // key was handled
             return sound;
         }
     }
     // default handling
     switch ( key )
     {
 #ifndef NDEBUG
         case K_F11:
             uis.debug ^= 1;
             break;
         case K_F12:
             trap_Cmd_ExecuteText(EXEC_APPEND, "screenshot\n");
             break;
 #endif
         case K_KP_UPARROW:
         case K_UPARROW:
             cursor_prev    = m->cursor;
             m->cursor_prev = m->cursor;
             m->cursor--;
             Menu_AdjustCursor( m, -1 );
             if ( cursor_prev != m->cursor ) {
                 Menu_CursorMoved( m );
                 sound = menu_move_sound;
             }
             break;
         case K_TAB:
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
             cursor_prev    = m->cursor;
             m->cursor_prev = m->cursor;
             m->cursor++;
             Menu_AdjustCursor( m, 1 );
             if ( cursor_prev != m->cursor ) {
                 Menu_CursorMoved( m );
                 sound = menu_move_sound;
             }
             break;
         case K_MOUSE1:
         case K_MOUSE3:
             if (item)
                 if ((item->flags & QMF_HASMOUSEFOCUS) && !(item->flags & (QMF_GRAYED|QMF_INACTIVE)))
                     return (Menu_ActivateItem( m, item ));
             break;
         case K_JOY1:
         case K_JOY2:
         case K_JOY3:
         case K_JOY4:
         case K_AUX1:
         case K_AUX2:
         case K_AUX3:
         case K_AUX4:
         case K_AUX5:
         case K_AUX6:
         case K_AUX7:
         case K_AUX8:
         case K_AUX9:
         case K_AUX10:
         case K_AUX11:
         case K_AUX12:
         case K_AUX13:
         case K_AUX14:
         case K_AUX15:
         case K_AUX16:
         case K_KP_ENTER:
         case K_ENTER:
             if (item)
                 if (!(item->flags & (QMF_MOUSEONLY|QMF_GRAYED|QMF_INACTIVE)))
                     return (Menu_ActivateItem( m, item ));
             break;
     }
     return sound;
 }
Referenced by ArenaServers_MenuKey(), ConfirmMenu_Key(), Controls_MenuKey(), PlayerModel_MenuKey(), PlayerSettings_MenuKey(), Reset_MenuKey(), ServerInfo_MenuKey(), UI_KeyEvent(), UI_SPPostgameMenu_MenuKey(), UI_SPSkillMenu_Key(), and UI_TeamOrdersMenu_Key().
Menu_Draw()
void Menu_Draw (menuframework_s * menu)
Definition at line 1485 of file ui_qmenu.c.
 {
     int             i;
     menucommon_s    *itemptr;
     // draw menu
     for (i=0; i<menu->nitems; i++)
     {
         itemptr = (menucommon_s*)menu->items[i];
         if (itemptr->flags & QMF_HIDDEN)
             continue;
         if (itemptr->ownerdraw)
         {
             // total subclassing, owner draws everything
             itemptr->ownerdraw( itemptr );
         }
         else
         {
             switch (itemptr->type)
             {
                 case MTYPE_RADIOBUTTON:
                     RadioButton_Draw( (menuradiobutton_s*)itemptr );
                     break;
                 case MTYPE_FIELD:
                     MenuField_Draw( (menufield_s*)itemptr );
                     break;
                 case MTYPE_SLIDER:
                     Slider_Draw( (menuslider_s*)itemptr );
                     break;
                 case MTYPE_SPINCONTROL:
                     SpinControl_Draw( (menulist_s*)itemptr );
                     break;
                 case MTYPE_ACTION:
                     Action_Draw( (menuaction_s*)itemptr );
                     break;
                 case MTYPE_BITMAP:
                     Bitmap_Draw( (menubitmap_s*)itemptr );
                     break;
                 case MTYPE_TEXT:
                     Text_Draw( (menutext_s*)itemptr );
                     break;
                 case MTYPE_SCROLLLIST:
                     ScrollList_Draw( (menulist_s*)itemptr );
                     break;
                 case MTYPE_PTEXT:
                     PText_Draw( (menutext_s*)itemptr );
                     break;
                 case MTYPE_BTEXT:
                     BText_Draw( (menutext_s*)itemptr );
                     break;
                 default:
                     trap_Error( va("Menu_Draw: unknown type %d", itemptr->type) );
             }
         }
 #ifndef NDEBUG
         if( uis.debug ) {
             int x;
             int y;
             int w;
             int h;
             if( !( itemptr->flags & QMF_INACTIVE ) ) {
                 x = itemptr->left;
                 y = itemptr->top;
                 w = itemptr->right - itemptr->left + 1;
                 h = itemptr->bottom - itemptr->top + 1;
                 if (itemptr->flags & QMF_HASMOUSEFOCUS) {
                     UI_DrawRect(x, y, w, h, colorYellow );
                 }
                 else {
                     UI_DrawRect(x, y, w, h, colorWhite );
                 }
             }
         }
 #endif
     }
     itemptr = Menu_ItemAtCursor( menu );
     if ( itemptr && itemptr->statusbar)
         itemptr->statusbar( ( void * ) itemptr );
 }
Referenced by ArenaServers_MenuDraw(), ConfirmMenu_Draw(), DriverInfo_MenuDraw(), GraphicsOptions_MenuDraw(), Main_MenuDraw(), MessageMenu_Draw(), Reset_MenuDraw(), ServerInfo_MenuDraw(), SoundOptions_MenuDraw(), UI_Refresh(), UI_SPLevelMenu_MenuDraw(), and UI_SPPostgameMenu_MenuDraw().
Menu_Focus()
void Menu_Focus (menucommon_s * m)
Menu_ItemAtCursor()
void* Menu_ItemAtCursor (menuframework_s * m)
Definition at line 1585 of file ui_qmenu.c.
 {
     if ( m->cursor < 0 || m->cursor >= m->nitems )
         return NULL;
     return m->items[m->cursor];
 }
Referenced by ArenaServers_MenuKey(), Controls_DrawKeyBinding(), MenuField_Draw(), PlayerModel_MenuKey(), UI_SaveConfigMenu_SavenameDraw(), UI_SPLevelMenu_MenuDraw(), and UI_TeamOrdersMenu_Key().
Menu_SetCursor()
void Menu_SetCursor (menuframework_s * s, int cursor)
Definition at line 1395 of file ui_qmenu.c.
 {
     if (((menucommon_s*)(m->items[cursor]))->flags & (QMF_GRAYED|QMF_INACTIVE))
     {
         // cursor can't go there
         return;
     }
     m->cursor_prev = m->cursor;
     m->cursor      = cursor;
     Menu_CursorMoved( m );
 }
Referenced by PlayerModel_MenuKey(), UI_MouseEvent(), and UI_PushMenu().
Menu_SetCursorToItem()
void Menu_SetCursorToItem (menuframework_s * m, void * ptr)
Definition at line 1414 of file ui_qmenu.c.
 {
     int i;
     for (i=0; i<m->nitems; i++)
     {
         if (m->items[i] == ptr)
         {
             Menu_SetCursor( m, i );
             return;
         }
     }
 }
Referenced by UI_CinematicsMenu_f(), UI_ConfirmMenu_Style(), UI_DisplayOptionsMenu(), UI_GraphicsOptionsMenu(), UI_Message(), UI_NetworkOptionsMenu(), UI_PlayerModelMenu(), UI_ResetMenu(), UI_SoundOptionsMenu(), UI_SPLevelMenu(), UI_SPPostgameMenu_f(), and UI_SPSkillMenu().
MenuField_Draw()
void MenuField_Draw (menufield_s * f)
Definition at line 332 of file ui_mfield.c.
 {
     int     x;
     int     y;
     int     w;
     int     style;
     qboolean focus;
     float   *color;
     x = f->generic.x;
     y = f->generic.y;
     if (f->generic.flags & QMF_SMALLFONT)
     {
         w = SMALLCHAR_WIDTH;
         style = UI_SMALLFONT;
     }
     else
     {
         w = BIGCHAR_WIDTH;
         style = UI_BIGFONT;
     }
     if (Menu_ItemAtCursor( f->generic.parent ) == f) {
         focus = qtrue;
         style |= UI_PULSE;
     }
     else {
         focus = qfalse;
     }
     if (f->generic.flags & QMF_GRAYED)
         color = text_color_disabled;
     else if (focus)
         color = text_color_highlight;
     else
         color = text_color_normal;
     if ( focus )
     {
         // draw cursor
         UI_FillRect( f->generic.left, f->generic.top, f->generic.right-f->generic.left+1, f->generic.bottom-f->generic.top+1, listbar_color );
         UI_DrawChar( x, y, 13, UI_CENTER|UI_BLINK|style, color);
     }
     if ( f->generic.name ) {
         UI_DrawString( x - w, y, f->generic.name, style|UI_RIGHT, color );
     }
     MField_Draw( &f->field, x + w, y, style, color );
 }
Referenced by Menu_Draw().
MenuField_Init()
void MenuField_Init (menufield_s * m)
Definition at line 296 of file ui_mfield.c.
{
     int l;
     int w;
     int h;
     MField_Clear( &m->field );
     if (m->generic.flags & QMF_SMALLFONT)
     {
         w = SMALLCHAR_WIDTH;
         h = SMALLCHAR_HEIGHT;
     }
     else
     {
         w = BIGCHAR_WIDTH;
         h = BIGCHAR_HEIGHT;
     }
     if (m->generic.name) {
         l = (strlen( m->generic.name )+1) * w;
     }
     else {
         l = 0;
     }
     m->generic.left   = m->generic.x - l;
     m->generic.top    = m->generic.y;
     m->generic.right  = m->generic.x + w + m->field.widthInChars*w;
     m->generic.bottom = m->generic.y + h;
 }
Referenced by Menu_AddItem().
MenuField_Key()
sfxHandle_t MenuField_Key (menufield_s * m, int * key)
Definition at line 389 of file ui_mfield.c.
 {
     int keycode;
     keycode = *key;
     switch ( keycode )
     {
         case K_KP_ENTER:
         case K_ENTER:
         case K_JOY1:
         case K_JOY2:
         case K_JOY3:
         case K_JOY4:
             // have enter go to next cursor point
             *key = K_TAB;
             break;
         case K_TAB:
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
         case K_KP_UPARROW:
         case K_UPARROW:
             break;
         default:
             if ( keycode & K_CHAR_FLAG )
             {
                 keycode &= ~K_CHAR_FLAG;
                 if ((m->generic.flags & QMF_UPPERCASE) && Q_islower( keycode ))
                     keycode -= 'a' - 'A';
                 else if ((m->generic.flags & QMF_LOWERCASE) && Q_isupper( keycode ))
                     keycode -= 'A' - 'a';
                 else if ((m->generic.flags & QMF_NUMBERSONLY) && Q_isalpha( keycode ))
                     return (menu_buzz_sound);
                 MField_CharEvent( &m->field, keycode);
             }
             else
                 MField_KeyDownEvent( &m->field, keycode );
             break;
     }
     return (0);
 }
Referenced by Menu_DefaultKey().
MField_CharEvent()
void MField_CharEvent (mfield_t * edit, int ch)
Definition at line 207 of file ui_mfield.c.
{
     int     len;
     if ( ch == 'v' - 'a' + 1 ) {    // ctrl-v is paste
         MField_Paste( edit );
         return;
     }
     if ( ch == 'c' - 'a' + 1 ) {    // ctrl-c clears the field
         MField_Clear( edit );
         return;
     }
     len = strlen( edit->buffer );
     if ( ch == 'h' - 'a' + 1 )  {   // ctrl-h is backspace
         if ( edit->cursor > 0 ) {
             memmove( edit->buffer + edit->cursor - 1,
                 edit->buffer + edit->cursor, len + 1 - edit->cursor );
             edit->cursor--;
             if ( edit->cursor < edit->scroll )
             {
                 edit->scroll--;
             }
         }
         return;
     }
     if ( ch == 'a' - 'a' + 1 ) {    // ctrl-a is home
         edit->cursor = 0;
         edit->scroll = 0;
         return;
     }
     if ( ch == 'e' - 'a' + 1 ) {    // ctrl-e is end
         edit->cursor = len;
         edit->scroll = edit->cursor - edit->widthInChars + 1;
         if (edit->scroll < 0)
             edit->scroll = 0;
         return;
     }
     //
     // ignore any other non printable chars
     //
     if ( ch < 32 ) {
         return;
     }
     if ( trap_Key_GetOverstrikeMode() ) {
         if ((edit->cursor == MAX_EDIT_LINE - 1) || (edit->maxchars && edit->cursor >= edit->maxchars))
             return;
     } else {
         // insert mode
         if (( len == MAX_EDIT_LINE - 1 ) || (edit->maxchars && len >= edit->maxchars))
             return;
         memmove( edit->buffer + edit->cursor + 1, edit->buffer + edit->cursor, len + 1 - edit->cursor );
     }
     edit->buffer[edit->cursor] = ch;
     if (!edit->maxchars || edit->cursor < edit->maxchars-1)
         edit->cursor++;
     if ( edit->cursor >= edit->widthInChars )
     {
         edit->scroll++;
     }
     if ( edit->cursor == len + 1) {
         edit->buffer[edit->cursor] = 0;
     }
 }
MField_Clear()
void MField_Clear (mfield_t * edit)
Definition at line 285 of file ui_mfield.c.
{
     edit->buffer[0] = 0;
     edit->cursor = 0;
     edit->scroll = 0;
 }
MField_Draw()
void MField_Draw (mfield_t * edit, int x, int y, int style, vec4_t color)
Definition at line 33 of file ui_mfield.c.
{
     int     len;
     int     charw;
     int     drawLen;
     int     prestep;
     int     cursorChar;
     char    str[MAX_STRING_CHARS];
     drawLen = edit->widthInChars;
     len     = strlen( edit->buffer ) + 1;
     // guarantee that cursor will be visible
     if ( len <= drawLen ) {
         prestep = 0;
     } else {
         if ( edit->scroll + drawLen > len ) {
             edit->scroll = len - drawLen;
             if ( edit->scroll < 0 ) {
                 edit->scroll = 0;
             }
         }
         prestep = edit->scroll;
     }
     if ( prestep + drawLen > len ) {
         drawLen = len - prestep;
     }
     // extract <drawLen> characters from the field at <prestep>
     if ( drawLen >= MAX_STRING_CHARS ) {
         trap_Error( "drawLen >= MAX_STRING_CHARS" );
     }
     memcpy( str, edit->buffer + prestep, drawLen );
     str[ drawLen ] = 0;
     UI_DrawString( x, y, str, style, color );
     // draw the cursor
     if (!(style & UI_PULSE)) {
         return;
     }
     if ( trap_Key_GetOverstrikeMode() ) {
         cursorChar = 11;
     } else {
         cursorChar = 10;
     }
     style &= ~UI_PULSE;
     style |= UI_BLINK;
     if (style & UI_SMALLFONT)
     {
         charw = SMALLCHAR_WIDTH;
     }
     else if (style & UI_GIANTFONT)
     {
         charw = GIANTCHAR_WIDTH;
     }
     else
     {
         charw = BIGCHAR_WIDTH;
     }
     if (style & UI_CENTER)
     {
         len = strlen(str);
         x = x - len*charw/2;
     }
     else if (style & UI_RIGHT)
     {
         len = strlen(str);
         x = x - len*charw;
     }
     UI_DrawChar( x + ( edit->cursor - prestep ) * charw, y, cursorChar, style & ~(UI_CENTER|UI_RIGHT), color );
 }
Referenced by UI_DrawConnectScreen(), and UI_SaveConfigMenu_SavenameDraw().
MField_KeyDownEvent()
void MField_KeyDownEvent (mfield_t * edit, int key)
Definition at line 139 of file ui_mfield.c.
{
     int     len;
     // shift-insert is paste
     if ( ( ( key == K_INS ) || ( key == K_KP_INS ) ) && trap_Key_IsDown( K_SHIFT ) ) {
         MField_Paste( edit );
         return;
     }
     len = strlen( edit->buffer );
     if ( key == K_DEL || key == K_KP_DEL ) {
         if ( edit->cursor < len ) {
             memmove( edit->buffer + edit->cursor,
                 edit->buffer + edit->cursor + 1, len - edit->cursor );
         }
         return;
     }
     if ( key == K_RIGHTARROW || key == K_KP_RIGHTARROW )
     {
         if ( edit->cursor < len ) {
             edit->cursor++;
         }
         if ( edit->cursor >= edit->scroll + edit->widthInChars && edit->cursor <= len )
         {
             edit->scroll++;
         }
         return;
     }
     if ( key == K_LEFTARROW || key == K_KP_LEFTARROW )
     {
         if ( edit->cursor > 0 ) {
             edit->cursor--;
         }
         if ( edit->cursor < edit->scroll )
         {
             edit->scroll--;
         }
         return;
     }
     if ( key == K_HOME || key == K_KP_HOME || ( tolower(key) == 'a' && trap_Key_IsDown( K_CTRL ) ) ) {
         edit->cursor = 0;
         edit->scroll = 0;
         return;
     }
     if ( key == K_END || key == K_KP_END || ( tolower(key) == 'e' && trap_Key_IsDown( K_CTRL ) ) ) {
         edit->cursor = len;
         edit->scroll = len - edit->widthInChars + 1;
         if (edit->scroll < 0)
             edit->scroll = 0;
         return;
     }
     if ( key == K_INS || key == K_KP_INS ) {
         trap_Key_SetOverstrikeMode( !trap_Key_GetOverstrikeMode() );
         return;
     }
 }
PlayerModel_Cache()
void PlayerModel_Cache (void)
Definition at line 713 of file ui_playermodel.c.
 {
     int i;
     for( i = 0; playermodel_artlist[i]; i++ ) {
         trap_R_RegisterShaderNoMip( playermodel_artlist[i] );
     }
     PlayerModel_BuildList();
     for( i = 0; i < s_playermodel.nummodels; i++ ) {
         trap_R_RegisterShaderNoMip( s_playermodel.modelnames[i] );
     }
 }
Referenced by UI_Cache_f().
PlayerSettings_Cache()
void PlayerSettings_Cache (void)
Definition at line 486 of file ui_playersettings.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_MODEL0 );
     trap_R_RegisterShaderNoMip( ART_MODEL1 );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     s_playersettings.fxBasePic = trap_R_RegisterShaderNoMip( ART_FX_BASE );
     s_playersettings.fxPic[0] = trap_R_RegisterShaderNoMip( ART_FX_RED );
     s_playersettings.fxPic[1] = trap_R_RegisterShaderNoMip( ART_FX_YELLOW );
     s_playersettings.fxPic[2] = trap_R_RegisterShaderNoMip( ART_FX_GREEN );
     s_playersettings.fxPic[3] = trap_R_RegisterShaderNoMip( ART_FX_TEAL );
     s_playersettings.fxPic[4] = trap_R_RegisterShaderNoMip( ART_FX_BLUE );
     s_playersettings.fxPic[5] = trap_R_RegisterShaderNoMip( ART_FX_CYAN );
     s_playersettings.fxPic[6] = trap_R_RegisterShaderNoMip( ART_FX_WHITE );
 }
Referenced by UI_Cache_f().
Preferences_Cache()
void Preferences_Cache (void)
Definition at line 394 of file ui_preferences.c.
{
     int     n;
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     for( n = 0; n < NUM_CROSSHAIRS; n++ ) {
         s_preferences.crosshairShader[n] = trap_R_RegisterShaderNoMip( va("gfx/2d/crosshair%c", 'a' + n ) );
     }
 }
Referenced by UI_Cache_f().
Rankings_Cache()
void Rankings_Cache (void)
Definition at line 405 of file ui_rankings.c.
{
     trap_R_RegisterShaderNoMip( RANKINGS_FRAME );
 }
References RANKINGS_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by Rankings_MenuInit().
Rankings_DrawName()
void Rankings_DrawName (void * self)
Definition at line 120 of file ui_rankings.c.
 {
     menufield_s     *f;
     int             length;
     char*           p;
     f = (menufield_s*)self;
     // GRANK_FIXME - enforce valid characters
     for( p = f->field.buffer; *p != '\0'; p++ )
     {
         //if( ispunct(*p) || isspace(*p) )
         if( !( ( (*p) >= '0' && (*p) <= '9') || Q_isalpha(*p)) )
         {
             *p = '\0';
         }
     }
     // strip color codes
     Q_CleanStr( f->field.buffer );
     length = strlen( f->field.buffer );
     if( f->field.cursor > length )
     {
         f->field.cursor = length;
     }
     Rankings_DrawText( f );
 }
References mfield_t::buffer, mfield_t::cursor, menufield_s::field, Q_CleanStr(), Q_isalpha(), and Rankings_DrawText().
Referenced by Login_MenuInit(), and Signup_MenuInit().
Rankings_DrawPassword()
void Rankings_DrawPassword (void * self)
Definition at line 191 of file ui_rankings.c.
 {
     menufield_s*    f;
     char            password[MAX_EDIT_LINE];
     int             length;
     int             i;
     char*           p;
     f = (menufield_s*)self;
     // GRANK_FIXME - enforce valid characters
     for( p = f->field.buffer; *p != '\0'; p++ )
     {
         //if( ispunct(*p) || isspace(*p) )
         if( !( ( (*p) >= '0' && (*p) <= '9') || Q_isalpha(*p)) )
         {
             *p = '\0';
         }
     }
     length = strlen( f->field.buffer );
     if( f->field.cursor > length )
     {
         f->field.cursor = length;
     }
     // save password
     Q_strncpyz( password, f->field.buffer, sizeof(password) );
     // mask password with *
     for( i = 0; i < length; i++ )
     {
         f->field.buffer[i] = '*';
     }
     // draw masked password
     Rankings_DrawText( f );
     //MenuField_Draw( f );
     // restore password
     Q_strncpyz( f->field.buffer, password, sizeof(f->field.buffer) );
 }
References mfield_t::buffer, mfield_t::cursor, menufield_s::field, MAX_EDIT_LINE, Q_isalpha(), Q_strncpyz(), and Rankings_DrawText().
Referenced by Login_MenuInit(), and Signup_MenuInit().
Rankings_DrawText()
void Rankings_DrawText (void * self)
Definition at line 68 of file ui_rankings.c.
 {
     menufield_s     *f;
     qboolean        focus;
     int             style;
     char            *txt;
     char            c;
     float           *color;
     int             basex, x, y;
     f = (menufield_s*)self;
     basex = f->generic.x;
     y = f->generic.y + 4;
     focus = (f->generic.parent->cursor == f->generic.menuPosition);
     style = UI_LEFT|UI_SMALLFONT;
     color = text_color_normal;
     if( focus ) {
         style |= UI_PULSE;
         color = text_color_highlight;
     }
     // draw the actual text
     txt = f->field.buffer;
     color = g_color_table[ColorIndex(COLOR_WHITE)];
     x = basex;
     while ( (c = *txt) != 0 ) {
         UI_DrawChar( x, y, c, style, color );
         txt++;
         x += SMALLCHAR_WIDTH;
     }
     // draw cursor if we have focus
     if( focus ) {
         if ( trap_Key_GetOverstrikeMode() ) {
             c = 11;
         } else {
             c = 10;
         }
         style &= ~UI_PULSE;
         style |= UI_BLINK;
         UI_DrawChar( basex + f->field.cursor * SMALLCHAR_WIDTH, y, c, style, color_white );
     }
 }
References mfield_t::buffer, color_white, COLOR_WHITE, ColorIndex, _tag_menuframework::cursor, mfield_t::cursor, menufield_s::field, g_color_table, menufield_s::generic, menucommon_s::menuPosition, menucommon_s::parent, SMALLCHAR_WIDTH, text_color_highlight, text_color_normal, trap_Key_GetOverstrikeMode(), UI_BLINK, UI_DrawChar(), UI_LEFT, UI_PULSE, UI_SMALLFONT, menucommon_s::x, and menucommon_s::y.
Referenced by Rankings_DrawName(), Rankings_DrawPassword(), and Signup_MenuInit().
RankStatus_Cache()
void RankStatus_Cache (void)
Definition at line 158 of file ui_rankstatus.c.
{
     trap_R_RegisterShaderNoMip( RANKSTATUS_FRAME );
 }
ScrollList_Draw()
void ScrollList_Draw (menulist_s * l)
Definition at line 1233 of file ui_qmenu.c.
 {
     int         x;
     int         u;
     int         y;
     int         i;
     int         base;
     int         column;
     float*      color;
     qboolean    hasfocus;
     int         style;
     hasfocus = (l->generic.parent->cursor == l->generic.menuPosition);
     x = l->generic.x;
     for( column = 0; column < l->columns; column++ ) {
         y = l->generic.y;
         base = l->top + column * l->height;
         for( i = base; i < base + l->height; i++) {
             if (i >= l->numitems)
                 break;
             if (i == l->curvalue)
             {
                 u = x - 2;
                 if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                     u -= (l->width * SMALLCHAR_WIDTH) / 2 + 1;
                 }
                 UI_FillRect(u,y,l->width*SMALLCHAR_WIDTH,SMALLCHAR_HEIGHT+2,listbar_color);
                 color = text_color_highlight;
                 if (hasfocus)
                     style = UI_PULSE|UI_LEFT|UI_SMALLFONT;
                 else
                     style = UI_LEFT|UI_SMALLFONT;
             }
             else
             {
                 color = text_color_normal;
                 style = UI_LEFT|UI_SMALLFONT;
             }
             if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                 style |= UI_CENTER;
             }
             UI_DrawString(
                 x,
                 y,
                 l->itemnames[i],
                 style,
                 color);
             y += SMALLCHAR_HEIGHT;
         }
         x += (l->width + l->separation) * SMALLCHAR_WIDTH;
     }
 }
ScrollList_Key()
sfxHandle_t ScrollList_Key (menulist_s * l, int key)
Definition at line 908 of file ui_qmenu.c.
 {
     int x;
     int y;
     int w;
     int i;
     int j;
     int c;
     int cursorx;
     int cursory;
     int column;
     int index;
     switch (key)
     {
         case K_MOUSE1:
             if (l->generic.flags & QMF_HASMOUSEFOCUS)
             {
                 // check scroll region
                 x = l->generic.x;
                 y = l->generic.y;
                 w = ( (l->width + l->separation) * l->columns - l->separation) * SMALLCHAR_WIDTH;
                 if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                     x -= w / 2;
                 }
                 if (UI_CursorInRect( x, y, w, l->height*SMALLCHAR_HEIGHT ))
                 {
                     cursorx = (uis.cursorx - x)/SMALLCHAR_WIDTH;
                     column = cursorx / (l->width + l->separation);
                     cursory = (uis.cursory - y)/SMALLCHAR_HEIGHT;
                     index = column * l->height + cursory;
                     if (l->top + index < l->numitems)
                     {
                         l->oldvalue = l->curvalue;
                         l->curvalue = l->top + index;
                         if (l->oldvalue != l->curvalue && l->generic.callback)
{
                             l->generic.callback( l, QM_GOTFOCUS );
                             return (menu_move_sound);
                         }
                     }
                 }
                 // absorbed, silent sound effect
                 return (menu_null_sound);
             }
             break;
         case K_KP_HOME:
         case K_HOME:
             l->oldvalue = l->curvalue;
             l->curvalue = 0;
             l->top      = 0;
             if (l->oldvalue != l->curvalue && l->generic.callback)
             {
                 l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_KP_END:
         case K_END:
             l->oldvalue = l->curvalue;
             l->curvalue = l->numitems-1;
             if( l->columns > 1 ) {
                 c = (l->curvalue / l->height + 1) * l->height;
                 l->top = c - (l->columns * l->height);
             }
             else {
                 l->top = l->curvalue - (l->height - 1);
             }
             if (l->top < 0)
                 l->top = 0;
             if (l->oldvalue != l->curvalue && l->generic.callback)
             {
                 l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_PGUP:
         case K_KP_PGUP:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->curvalue > 0)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue -= l->height-1;
                 if (l->curvalue < 0)
                     l->curvalue = 0;
                 l->top = l->curvalue;
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_PGDN:
         case K_KP_PGDN:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->curvalue < l->numitems-1)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue += l->height-1;
                 if (l->curvalue > l->numitems-1)
                     l->curvalue = l->numitems-1;
                 l->top = l->curvalue - (l->height-1);
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_MWHEELUP:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->top > 0)
             {
                 // if scrolling 3 lines would replace over half of the
                 // displayed items, only scroll 1 item at a time.
                 int scroll = l->height < 6 ? 1 : 3;
                 l->top -= scroll;
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 // make scrolling silent
                 return (menu_null_sound);
             }
             return (menu_buzz_sound);
         case K_MWHEELDOWN:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->top < l->numitems-l->height)
             {
                 // if scrolling 3 items would replace over half of the
                 // displayed items, only scroll 1 item at a time.
                 int scroll = l->height < 6 ? 1 : 3;
                 l->top += scroll;
                 if (l->top > l->numitems-l->height)
                     l->top = l->numitems-l->height;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 // make scrolling silent
                 return (menu_null_sound);
             }
             return (menu_buzz_sound);
         case K_KP_UPARROW:
         case K_UPARROW:
             if( l->curvalue == 0 ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue--;
             if( l->curvalue < l->top ) {
                 if( l->columns == 1 ) {
                     l->top--;
                 }
                 else {
                     l->top -= l->height;
                 }
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return (menu_move_sound);
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
             if( l->curvalue == l->numitems - 1 ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue++;
             if( l->curvalue >= l->top + l->columns * l->height ) {
                 if( l->columns == 1 ) {
                     l->top++;
                 }
                 else {
                     l->top += l->height;
                 }
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
         case K_KP_LEFTARROW:
         case K_LEFTARROW:
             if( l->columns == 1 ) {
                 return menu_null_sound;
             }
             if( l->curvalue < l->height ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue -= l->height;
             if( l->curvalue < l->top ) {
                 l->top -= l->height;
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
         case K_KP_RIGHTARROW:
         case K_RIGHTARROW:
             if( l->columns == 1 ) {
                 return menu_null_sound;
             }
             c = l->curvalue + l->height;
             if( c >= l->numitems ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue = c;
             if( l->curvalue > l->top + l->columns * l->height - 1 ) {
                 l->top += l->height;
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
     }
     // cycle look for ascii key inside list items
     if ( !Q_isprint( key ) )
         return (0);
     // force to lower for case insensitive compare
     if ( Q_isupper( key ) )
     {
         key -= 'A' - 'a';
     }
     // iterate list items
     for (i=1; i<=l->numitems; i++)
     {
         j = (l->curvalue + i) % l->numitems;
         c = l->itemnames[j][0];
         if ( Q_isupper( c ) )
         {
             c -= 'A' - 'a';
         }
         if (c == key)
         {
             // set current item, mimic windows listbox scroll behavior
             if (j < l->top)
             {
                 // behind top most item, set this as new top
                 l->top = j;
             }
             else if (j > l->top+l->height-1)
             {
                 // past end of list box, do page down
                 l->top = (j+1) - l->height;
             }
             if (l->curvalue != j)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue = j;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return ( menu_move_sound );
             }
             return (menu_buzz_sound);
         }
     }
     return (menu_buzz_sound);
 }
Referenced by ArenaServers_Event(), Demos_MenuEvent(), LoadConfig_MenuEvent(), and SpecifyLeague_Event().
ServerInfo_Cache()
void ServerInfo_Cache (void)
Definition at line 168 of file ui_serverinfo.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!serverinfo_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(serverinfo_artlist[i]);
     }
 }
Referenced by UI_Cache_f().
ServerOptions_Cache()
void ServerOptions_Cache (void)
Definition at line 1495 of file ui_startserver.c.
{
     trap_R_RegisterShaderNoMip( GAMESERVER_BACK0 );
     trap_R_RegisterShaderNoMip( GAMESERVER_BACK1 );
     trap_R_RegisterShaderNoMip( GAMESERVER_FIGHT0 );
     trap_R_RegisterShaderNoMip( GAMESERVER_FIGHT1 );
     trap_R_RegisterShaderNoMip( GAMESERVER_SELECT );
     trap_R_RegisterShaderNoMip( GAMESERVER_UNKNOWNMAP );
 }
Referenced by UI_Cache_f().
Signup_Cache()
void Signup_Cache (void)
Definition at line 271 of file ui_signup.c.
{
     trap_R_RegisterShaderNoMip( SIGNUP_FRAME );
 }
SpecifyLeague_Cache()
void SpecifyLeague_Cache (void)
Definition at line 310 of file ui_specifyleague.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!specifyleague_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(specifyleague_artlist[i]);
     }
 }
SpecifyServer_Cache()
void SpecifyServer_Cache (void)
Definition at line 190 of file ui_specifyserver.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!specifyserver_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(specifyserver_artlist[i]);
     }
 }
Referenced by UI_Cache_f().
StartServer_Cache()
void StartServer_Cache (void)
Definition at line 559 of file ui_startserver.c.
 {
     int             i;
     const char      *info;
     qboolean        precache;
     char            picname[64];
     char            mapname[ MAX_NAMELENGTH ];
     trap_R_RegisterShaderNoMip( GAMESERVER_BACK0 );
     trap_R_RegisterShaderNoMip( GAMESERVER_BACK1 );
     trap_R_RegisterShaderNoMip( GAMESERVER_NEXT0 );
     trap_R_RegisterShaderNoMip( GAMESERVER_NEXT1 );
     trap_R_RegisterShaderNoMip( GAMESERVER_FRAMEL );
     trap_R_RegisterShaderNoMip( GAMESERVER_FRAMER );
     trap_R_RegisterShaderNoMip( GAMESERVER_SELECT );
     trap_R_RegisterShaderNoMip( GAMESERVER_SELECTED );
     trap_R_RegisterShaderNoMip( GAMESERVER_UNKNOWNMAP );
     trap_R_RegisterShaderNoMip( GAMESERVER_ARROWS );
     trap_R_RegisterShaderNoMip( GAMESERVER_ARROWSL );
     trap_R_RegisterShaderNoMip( GAMESERVER_ARROWSR );
     precache = trap_Cvar_VariableValue("com_buildscript");
     if( precache ) {
         for( i = 0; i < UI_GetNumArenas(); i++ ) {
             info = UI_GetArenaInfoByNumber( i );
             Q_strncpyz( mapname, Info_ValueForKey( info, "map"), MAX_NAMELENGTH );
             Q_strupr( mapname );
             Com_sprintf( picname, sizeof(picname), "levelshots/%s", mapname );
             trap_R_RegisterShaderNoMip(picname);
         }
     }
 }
Referenced by UI_Cache_f().
TeamMain_Cache()
void TeamMain_Cache (void)
Definition at line 186 of file ui_team.c.
{
     trap_R_RegisterShaderNoMip( TEAMMAIN_FRAME );
 }
Referenced by UI_Cache_f().
trap_Argc()
int trap_Argc (void)
Whenever a client issues a console command it can have arguments passed with it.
Returns
The number of arguments identically to the argc found in C programs with this prototype for main: int main(int argc, char **argv).
Definition at line 101 of file cg_syscalls.c.
 {
     return syscall(CG_ARGC);
 }
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
This will fill the buffer pointed to by buffer with an argument to a client command where n is the argument to return.
0 is the command itself, 1 is the first argument and so on... Very similiar to char **argv in a C program.
Parameters
n The argument number to return.
buffer A point to a buffer to fill.
bufferLength The size of the buffer.
Definition at line 106 of file cg_syscalls.c.
 {
     syscall(CG_ARGV, n, buffer, bufferLength);
 }
trap_CM_LerpTag()
int trap_CM_LerpTag (orientation_t * tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char * tagName)
Definition at line 219 of file ui_syscalls.c.
 {
     return syscall(UI_CM_LERPTAG, tag, mod, startFrame, endFrame, PASSFLOAT(frac), tagName);
 }
Referenced by UI_PositionEntityOnTag(), and UI_PositionRotatedEntityOnTag().
trap_Cmd_ExecuteText()
void trap_Cmd_ExecuteText (int exec_when, const char * text)
Definition at line 119 of file ui_syscalls.c.
 {
     syscall(UI_CMD_EXECUTETEXT, exec_when, text);
 }
Referenced by _UI_Init(), ArenaServers_DoRefresh(), ArenaServers_Go(), ArenaServers_StartRefresh(), Controls_SetConfig(), Demos_MenuEvent(), GraphicsOptions_ApplyChanges(), InGame_Event(), InGame_RestartAction(), LoadConfig_MenuEvent(), Main_MenuEvent(), Menu_DefaultKey(), NeedCDAction(), NeedCDKeyAction(), Rankings_MenuEvent(), ServerOptions_Start(), Setup_ResetDefaults_Action(), SpecifyServer_Event(), TeamMain_MenuEvent(), UI_AddBotsMenu_FightEvent(), UI_CinematicsMenu_Event(), UI_CreditMenu_Key(), UI_DoServerRefresh(), UI_KeyConnect(), UI_Mods_MenuEvent(), UI_RemoveBotsMenu_DeleteEvent(), UI_RunMenuScript(), UI_SaveConfigMenu_SaveEvent(), UI_SoundOptionsMenu_Event(), UI_SPArena_Start(), UI_SPPostgameMenu_AgainEvent(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuEvent(), UI_SPPostgameMenu_MenuKey(), UI_StartDemoLoop(), UI_StartServerRefresh(), UI_StartSkirmish(), and UI_TeamOrdersMenu_ListEvent().
trap_Cvar_Create()
void trap_Cvar_Create (const char * var_name, const char * var_value, int flags)
Definition at line 99 of file ui_syscalls.c.
 {
     syscall(UI_CVAR_CREATE, var_name, var_value, flags);
 }
trap_Cvar_InfoStringBuffer()
void trap_Cvar_InfoStringBuffer (int bit, char * buffer, int bufsize)
Definition at line 104 of file ui_syscalls.c.
 {
     syscall(UI_CVAR_INFOSTRINGBUFFER, bit, buffer, bufsize);
 }
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * cvar, const char * var_name, const char * value, int flags)
This function is used to create a new vmCvar.
It sends all the information to the engine's main database and then it stores a local copy of the data into the vmCvar_t passed as the first argument.
Parameters
cvar A pointer the location in which to store the local data.
var_name A null-terminated string that will be used to set the vmCvar's name field.
value A null-terminated string that will be used to set both the floating point and integer value fields of the vmCvar.
flags ?.
Definition at line 62 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_REGISTER, vmCvar, varName, defaultValue, flags);
 }
trap_Cvar_Reset()
void trap_Cvar_Reset (const char * name)
Definition at line 94 of file ui_syscalls.c.
 {
     syscall(UI_CVAR_RESET, name);
 }
Referenced by Controls_InitCvars(), GraphicsOptions_ApplyChanges(), Preferences_Event(), and UI_Update().
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
This function searchs for the name of the vmCvar and stores the value into both the float and integer fields of the corresponding vmCvar entry.
The only way to effectly change the value of a vmCvar is to use this function, the ANSI storage operator only modifies the local buffer and not the "master copy".
Parameters
var_name A null-terminated string containing the name of the vmCvar to set.
value A null-terminated string containing the desired value.
Definition at line 72 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_SET, var_name, value);
 }
trap_Cvar_SetValue()
void trap_Cvar_SetValue (const char * var_name, float value)
Definition at line 89 of file ui_syscalls.c.
 {
     syscall(UI_CVAR_SETVALUE, var_name, PASSFLOAT(value));
 }
Referenced by ArenaServers_Event(), Controls_InitCvars(), Controls_SetConfig(), GraphicsOptions_ApplyChanges(), PlayerSettings_SaveChanges(), Preferences_Event(), Reset_MenuEvent(), ServerOptions_Start(), StartServer_MenuEvent(), UI_Crosshair_HandleKey(), UI_DisplayOptionsMenu_Event(), UI_Effects_HandleKey(), UI_GameType_HandleKey(), UI_Handicap_HandleKey(), UI_JoinGameType_HandleKey(), UI_NetGameType_HandleKey(), UI_NetSource_HandleKey(), UI_NetworkOptionsMenu_Event(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_Skill_HandleKey(), UI_SoundOptionsMenu_Event(), UI_SPArena_Start(), UI_SPLevelMenu_LevelEvent(), UI_SPLevelMenu_ResetAction(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_MenuDraw(), UI_SPSkillMenu_SkillEvent(), UI_StartSkirmish(), UI_TeamMember_HandleKey(), and UI_Update().
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * cvar)
This function first parses out the name of the vmCvar and then searches for the corresponding database entry.
Once it finds the vmCvar it will copy the "master copy" of the vmCvar into the local address provided.
Parameters
cvar A pointer to the vmCvar to update.
Definition at line 67 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_UPDATE, vmCvar);
 }
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
This is useful for obtaining cvar contents that are not bound, or cannot be bound, to a vmCvar_t variable in the mod code.
The terminating NULL is attached to the end of the copied string by this trap, guaranteeing buffer holds a null-terminated string. The total number of characters copied, including terminating NULL, fits within the size specified by bufsize, truncating the string if necessary.
A nonexistent cvar provides an empty string. An existing cvar with empty content also provides an empty string. Thus, this trap is not sufficient to determine if a cvar actually exists or not.
This trap does not create a new cvar; to create a new cvar during run-time, you can use trap_Cvar_Set or trap_SendConsoleCommand.
Parameters
var_name name of cvar (console variable).
buffer destination string buffer.
bufsize maximum limit of string buffer.
var_name
buffer
bufsize This is useful for obtaining cvar contents that are not bound, or cannot be bound, to a vmCvar_t variable in the mod code.
The terminating NULL is attached to the end of the copied string by this trap, guaranteeing buffer holds a null-terminated string. The total number of characters copied, including terminating NULL, fits within the size specified by bufsize, truncating the string if necessary.
A nonexistent cvar provides an empty string. An existing cvar with empty content also provides an empty string. Thus, this trap is not sufficient to determine if a cvar actually exists or not.
This trap does not create a new cvar; to create a new cvar during run-time, you can use trap_Cvar_Set or trap_SendConsoleCommand.
Parameters
var_name name of cvar (console variable).
buffer destination string buffer.
bufsize maximum limit of string buffer.
var_name
buffer
bufsize
Definition at line 96 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize);
 }
trap_Cvar_VariableValue()
float trap_Cvar_VariableValue (const char * var_name)
Definition at line 54 of file g_bot.c.
 {
     char buf[128];
     trap_Cvar_VariableStringBuffer(var_name, buf, sizeof(buf));
     return atof(buf);
 }
trap_Error()
void trap_Error (const char * string)
This is very similar to the trap_Print function with the exception that this will halt execution of the module it is called from.
Usually the user shouldn't call this directly, but using G_Error instead.
Parameters
text Text to be displayed.
Definition at line 50 of file cg_syscalls.c.
 {
     syscall(CG_ERROR, fmt);
     // shut up GCC warning about returning functions, because we know better
     exit(1);
 }
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Closes the file specified by f.
Parameters
f The file to be closed.
Definition at line 131 of file cg_syscalls.c.
 {
     syscall(CG_FS_FCLOSEFILE, f);
 }
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
This opens a file specified by the string qpath and allocates a fileHandle_t (just a typedef int) to that file.
This is then used in subsequent operations involving the file. The fsMode_t enumeration refers to the mode the file is opened in. FS_READ for reading the file. FS_WRITE will create the file qpath if it doesn't exist or 0 length it if it does. FS_APPEND allows writing to the end of an existing file. FS_APPEND_SYNC is similar to FS_APPEND except you can read from the file at the same time.
An int is returned representing the length of the file being opened.
Parameters
qpath The file to be opened.
f Reference to a local fileHandle_t.
mode Mode to open the file in.
Returns
Definition at line 116 of file cg_syscalls.c.
 {
     return syscall(CG_FS_FOPENFILE, qpath, f, mode);
 }
trap_FS_GetFileList()
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
This fills listbuf with a NULL delimited list of all the files in the directory specified by path ending in extension.
The number of files listed is returned.
Parameters
path String reflecting a directory.
extension File extension to list (incluing a leading period).
listbuf Pointer to a buffer to fill.
bufsize Length of the buffer.
Returns
Definition at line 174 of file g_syscalls.c.
 {
     return syscall(G_FS_GETFILELIST, path, extension, listbuf, bufsize);
 }
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
This reads len bytes of data from the file specified by f and fills buffer with it.
Parameters
buffer A buffer to fill.
len he amount to read from the file.
f A file handle provided by trap_FS_FOpenFile.
Definition at line 121 of file cg_syscalls.c.
 {
     syscall(CG_FS_READ, buffer, len, f);
 }
trap_FS_Seek()
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
Definition at line 136 of file cg_syscalls.c.
 {
     return syscall(CG_FS_SEEK, f, offset, origin);
 }
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
This writes len bytes of data from buffer to the file specified by f.
Parameters
buffer A buffer to read from.
len The amount to write to the file.
f A file handle provided by trap_FS_FOpenFile.
Definition at line 126 of file cg_syscalls.c.
 {
     syscall(CG_FS_WRITE, buffer, len, f);
 }
trap_GetCDKey()
void trap_GetCDKey (char * buf, int buflen)
Definition at line 394 of file ui_syscalls.c.
 {
     syscall(UI_GET_CDKEY, buf, buflen);
 }
Referenced by UI_CDKeyMenu_Init(), UI_MainMenu(), and UI_RunMenuScript().
trap_GetClientState()
void trap_GetClientState (uiClientState_t * state)
Definition at line 284 of file ui_syscalls.c.
 {
     syscall(UI_GETCLIENTSTATE, state);
 }
Referenced by InGame_MenuInit(), Options_MenuInit(), UI_BuildPlayerList(), UI_ConfirmMenu_Style(), UI_DrawConnectScreen(), UI_Message(), UI_ResetMenu(), UI_TeamOrdersMenu_BuildBotList(), and UI_TeamOrdersMenu_f().
trap_GetClipboardData()
void trap_GetClipboardData (char * buf, int bufsize)
Definition at line 279 of file ui_syscalls.c.
 {
     syscall(UI_GETCLIPBOARDDATA, buf, bufsize);
 }
Referenced by MField_Paste().
trap_GetConfigString()
int trap_GetConfigString (int index, char * buff, int buffsize)
Definition at line 294 of file ui_syscalls.c.
 {
     return syscall(UI_GETCONFIGSTRING, index, buff, buffsize);
 }
Referenced by InGame_MenuInit(), Prepname(), TeamMain_MenuInit(), UI_AddBotsMenu_Init(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_DrawConnectScreen(), UI_RemoveBotsMenu_GetBots(), UI_RemoveBotsMenu_SetBotNames(), UI_ServerInfoMenu(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_TeamOrdersMenu_BuildBotList(), and UI_TeamOrdersMenu_f().
trap_GetGlconfig()
void trap_GetGlconfig (glconfig_t * glconfig)
Definition at line 507 of file cg_syscalls.c.
 {
     syscall(CG_GETGLCONFIG, glconfig);
 }
trap_Key_ClearStates()
void trap_Key_ClearStates (void)
Definition at line 264 of file ui_syscalls.c.
 {
     syscall(UI_KEY_CLEARSTATES);
 }
Referenced by _UI_KeyEvent(), _UI_SetActiveMenu(), UI_ForceMenuOff(), UI_Pause(), and UI_RunMenuScript().
trap_Key_GetBindingBuf()
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
Definition at line 239 of file ui_syscalls.c.
 {
     syscall(UI_KEY_GETBINDINGBUF, keynum, buf, buflen);
 }
Referenced by _UI_Init(), and Controls_GetKeyAssignment().
trap_Key_GetCatcher()
int trap_Key_GetCatcher (void)
Returns a bitmask representing active key catchers.
Bitmask values are: KEYCATCH_CONSOLE KEYCATCH_UI KEYCATCH_MESSAGE KEYCATCH_CGAME
(see also trap_Key_SetCatcher())
To check if CGAME key-catching is active: if (trap_Key_GetCatcher() & KEYCATCH_UI) { //happy happy }
Returns
A bitmask representing active key catchers.
Definition at line 615 of file cg_syscalls.c.
 {
     return syscall(CG_KEY_GETCATCHER);
 }
trap_Key_GetOverstrikeMode()
qboolean trap_Key_GetOverstrikeMode (void)
Definition at line 254 of file ui_syscalls.c.
 {
     return syscall(UI_KEY_GETOVERSTRIKEMODE);
 }
Referenced by _UI_Init(), MField_CharEvent(), MField_Draw(), MField_KeyDownEvent(), PlayerSettings_DrawName(), Rankings_DrawText(), and UI_CDKeyMenu_DrawKey().
trap_Key_IsDown()
qboolean trap_Key_IsDown (int keynum)
Returns true is the indicated key is held down, returns false if not held down (released).
The values of keynum range from 0 to 255, inclusive. For the most part, a key's keynum corresponds to its character's ASCII value (e.g. the 'A' key is 65).
I have a list of keynames used by the bind command with their keynums which I may append at a later date. In the meantime, if you want to know them now, you can do this:
Create a keynums.cfg with a pattern like: bind 0x00 Key 0x00 bind 0x01 Key 0x01 ... bind 0xfe Key 0xfe bind 0xff Key 0xff (case matters for the hex values, and a scripting language to automate this really helps).
Back up your q3config.cfg, run Q3, "/exec keynums.cfg; bindlist; condump keynums.txt; quit".
In the file "keynums.txt" you should now have lines like: UPARROW "Key 0x84"
There's your keynum list.
(Generating keynums.cfg in GNU bash: for i in $(seq 0 255); do x=$(printf "%02x" $i); echo bind 0x$x Key 0x$x; done > keynums.cfg).
Parameters
keynum A key keynum.
Returns
Definition at line 592 of file cg_syscalls.c.
 {
     return syscall(CG_KEY_ISDOWN, keynum);
 }
trap_Key_KeynumToStringBuf()
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
Definition at line 234 of file ui_syscalls.c.
 {
     syscall(UI_KEY_KEYNUMTOSTRINGBUF, keynum, buf, buflen);
 }
Referenced by _UI_Init(), and Controls_DrawKeyBinding().
trap_Key_SetBinding()
void trap_Key_SetBinding (int keynum, const char * binding)
Definition at line 244 of file ui_syscalls.c.
 {
     syscall(UI_KEY_SETBINDING, keynum, binding);
 }
Referenced by _UI_Init(), Controls_MenuKey(), and Controls_SetConfig().
trap_Key_SetCatcher()
void trap_Key_SetCatcher (int catcher)
Redirects key events to different module(s).
Normally, key events are interpreted by the engine, affected by the key bindings. This trap allows you redirect key events to other components.
Valid catchers are: KEYCATCH_CONSOLE: the console KEYCATCH_UI: the ui module KEYCATCH_MESSAGE: the little message editor thingy KEYCATCH_CGAME: the cgame module
These are bitmasked values, meaning you can combine them with the OR operator (|), as in (KEYCATCH_UI|KEYCATCH_CGAME), but I recommend against trying multiple catchers (it may get confusing).
As a mods programmer, you may be most interested in KEYCATCH_CGAME, and on this I will concentrate this entry.
— The Keyboard —
When key-catching is enabled (trap_Key_SetCatcher(KEYCATCH_CGAME);), upon a change in key state (gets pressed or gets released), the engine calls the vmMain() function in cg_main.c with the following parameters: command = CG_KEY_EVENT arg0 = keynum arg1 = 1 if pressed, 0 if released.
In baseq3 game source, this event is already handled and delegated to CG_KeyEvent(), which is empty.
The values for keynum are the same as for trap_Key_IsDown().
Key catching is disabled by calling with a parameter of 0 (as in, no catchers). Key catching is also terminated if the user presses the ESC key, which means you won't receive events on the ESC key.
— The Mouse —
When key-catching is enabled, mouse movement is also redirected to the specified module. When the engine detects mouse movement, it calls vmMain() with the following parameters: command = CG_MOUSE_EVENT arg0 = relative X position arg1 = relative Y position
The game source for baseq3 delegates this event to CG_MouseEvent().
Pointer Device Movement - Reported Value: Left - Negative X Right - Positive X Up - Negative Y Down - Positive Y
The engine only reports mouse movement – if the mouse doesn't move, there is no mouse event. The engine reports mouse buttons and wheels (if any) as key events, for binding purposes.
Cvars do not influence the reported values.
Parameters
catcher Key catchers bitmask.
Definition at line 677 of file cg_syscalls.c.
 {
     syscall(CG_KEY_SETCATCHER, catcher);
 }
trap_Key_SetOverstrikeMode()
void trap_Key_SetOverstrikeMode (qboolean state)
Definition at line 259 of file ui_syscalls.c.
 {
     syscall(UI_KEY_SETOVERSTRIKEMODE, state);
 }
Referenced by _UI_Init(), and MField_KeyDownEvent().
trap_LAN_ClearPing()
void trap_LAN_ClearPing (int n)
Definition at line 344 of file ui_syscalls.c.
 {
     syscall(UI_LAN_CLEARPING, n);
 }
Referenced by ArenaServers_DoRefresh(), and ArenaServers_StartRefresh().
trap_LAN_GetPing()
void trap_LAN_GetPing (int n, char * buf, int buflen, int * pingtime)
Definition at line 349 of file ui_syscalls.c.
 {
     syscall(UI_LAN_GETPING, n, buf, buflen, pingtime);
 }
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetPingInfo()
void trap_LAN_GetPingInfo (int n, char * buf, int buflen)
Definition at line 354 of file ui_syscalls.c.
 {
     syscall(UI_LAN_GETPINGINFO, n, buf, buflen);
 }
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetPingQueueCount()
int trap_LAN_GetPingQueueCount (void)
Definition at line 319 of file ui_syscalls.c.
 {
     return syscall(UI_LAN_GETPINGQUEUECOUNT);
 }
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetServerAddressString()
void trap_LAN_GetServerAddressString (int source, int n, char * buf, int buflen)
Definition at line 304 of file ui_syscalls.c.
 {
     syscall(UI_LAN_GETSERVERADDRESSSTRING, source, n, buf, buflen);
 }
Referenced by ArenaServers_DoRefresh(), UI_BuildFindPlayerList(), and UI_RunMenuScript().
trap_LAN_GetServerCount()
int trap_LAN_GetServerCount (int source)
Definition at line 299 of file ui_syscalls.c.
 {
     return syscall(UI_LAN_GETSERVERCOUNT, source);
 }
Referenced by ArenaServers_DoRefresh(), UI_BuildServerDisplayList(), UI_DoServerRefresh(), UI_DrawServerRefreshDate(), UI_StartServerRefresh(), and UI_StopServerRefresh().
trap_LAN_GetServerInfo()
void trap_LAN_GetServerInfo (int source, int n, char * buf, int buflen)
Definition at line 309 of file ui_syscalls.c.
 {
     syscall(UI_LAN_GETSERVERINFO, source, n, buf, buflen);
 }
Referenced by UI_BuildFindPlayerList(), UI_BuildServerDisplayList(), UI_FeederItemText(), UI_FeederSelection(), and UI_RunMenuScript().
trap_LAN_ServerStatus()
int trap_LAN_ServerStatus (const char * serverAddress, char * serverStatus, int maxLen)
Definition at line 324 of file ui_syscalls.c.
 {
     return syscall(UI_LAN_SERVERSTATUS, serverAddress, serverStatus, maxLen);
 }
Referenced by UI_BuildFindPlayerList(), UI_BuildServerStatus(), and UI_GetServerStatusInfo().
trap_MemoryRemaining()
int trap_MemoryRemaining (void)
Definition at line 557 of file cg_syscalls.c.
 {
     return syscall(CG_MEMORY_REMAINING);
 }
trap_Milliseconds()
int trap_Milliseconds (void)
Returns the number of milliseconds that have elapsed since Quake 3 was executed.
A Quake 3, multi-platform version of the Win32 function timeGetTime, which also returns the number of milliseconds since the program was executed.
Returns
The number of milliseconds that have elapsed since Quake 3 was executed.
Definition at line 57 of file cg_syscalls.c.
 {
     return syscall(CG_MILLISECONDS);
 }
trap_Print()
void trap_Print (const char * string)
trap_Print prints the string pointed to by fmt to the Q3 Console.
This should not usually be used directly by the user; the G_Printf function provides its functionality and more.
Parameters
text Text to be displayed.
Definition at line 45 of file cg_syscalls.c.
 {
     syscall(CG_PRINT, fmt);
 }
trap_R_AddLightToScene()
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
This function will add a light to the game at org, which has a radius of intensity units, and the colour data which is shown in the variables r, g, and b.
The highest number for an RGB index is 255, but in Quake 3 the colour's index is divided by 255 to give a normalized value.
Say I want to make a purple light. The colour data for purple in RGB is 255,0,255. So the normalized values for this colour are:
255/255 = 1.0 0/255 = 0.0 255/255 = 1.0
o to add a purple light at the vector x, and radius 2.4 I would write:
trap_R_AddLightToScene(x, 2.4, 1.0, 0.0, 1.0);.
Parameters
org origin of the light - where the light will be.
intensity not the exact intensity of the light, but the radius of the light - the light is a sphere-like object and points within that object are lighted up, and the closer something is to the origin of the light (org) the closer the light will be to the actual colour data of the light.
r this is the colour data of the light (normalized, so the highest value, 255, is 1.0) - r is the amount of red light.
g green light.
b blue light.
Definition at line 465 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDLIGHTTOSCENE, org, PASSFLOAT(intensity), PASSFLOAT(r), PASSFLOAT(g), PASSFLOAT(b));
 }
trap_R_AddPolyToScene()
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
Definition at line 424 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDPOLYTOSCENE, hShader, numVerts, verts);
 }
trap_R_AddRefEntityToScene()
void trap_R_AddRefEntityToScene (const refEntity_t * re)
Physically added to the visuals in the game, after a new shader is set.
Parameters
[in] Updated entity.
Definition at line 419 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDREFENTITYTOSCENE, re);
 }
trap_R_ClearScene()
void trap_R_ClearScene (void)
Definition at line 409 of file cg_syscalls.c.
 {
     syscall(CG_R_CLEARSCENE);
 }
trap_R_DrawStretchPic()
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Definition at line 485 of file cg_syscalls.c.
 {
     syscall(CG_R_DRAWSTRETCHPIC, PASSFLOAT(x), PASSFLOAT(y), PASSFLOAT(w), PASSFLOAT(h), PASSFLOAT(s1), PASSFLOAT(t1), PASSFLOAT(s2), PASSFLOAT(t2), hShader);
 }
trap_R_RegisterModel()
qhandle_t trap_R_RegisterModel (const char * name)
Definition at line 378 of file cg_syscalls.c.
 {
     return syscall(CG_R_REGISTERMODEL, name);
 }
trap_R_RegisterShaderNoMip()
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
Definition at line 399 of file cg_syscalls.c.
 {
     return syscall(CG_R_REGISTERSHADERNOMIP, name);
 }
trap_R_RegisterSkin()
qhandle_t trap_R_RegisterSkin (const char * name)
Definition at line 383 of file cg_syscalls.c.
 {
     return syscall(CG_R_REGISTERSKIN, name);
 }
trap_R_RenderScene()
void trap_R_RenderScene (const refdef_t * fd)
Definition at line 475 of file cg_syscalls.c.
 {
     syscall(CG_R_RENDERSCENE, fd);
 }
trap_R_SetColor()
void trap_R_SetColor (const float * rgba)
Definition at line 480 of file cg_syscalls.c.
 {
     syscall(CG_R_SETCOLOR, rgba);
 }
trap_S_RegisterSound()
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
Definition at line 363 of file cg_syscalls.c.
 {
     return syscall(CG_S_REGISTERSOUND, sample, compressed);
 }
trap_S_StartLocalSound()
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
Definition at line 326 of file cg_syscalls.c.
 {
     syscall(CG_S_STARTLOCALSOUND, sfx, channelNum);
 }
trap_SetCDKey()
void trap_SetCDKey (char * buf)
Definition at line 399 of file ui_syscalls.c.
 {
     syscall(UI_SET_CDKEY, buf);
 }
Referenced by UI_CDKeyMenu_Event(), and UI_RunMenuScript().
trap_SetPbClStatus()
void trap_SetPbClStatus (int status)
Definition at line 489 of file ui_syscalls.c.
 {
     syscall(UI_SET_PBCLSTATUS, status);
 }
Referenced by Punkbuster_ConfirmDisable(), Punkbuster_ConfirmEnable(), and UI_RunMenuScript().
trap_UpdateScreen()
void trap_UpdateScreen (void)
trap_UpdateScreen updates the screen.
cg_local.h says: // force a screen update, only used during gamestate load void trap_UpdateScreen(void);
the Trap_UpdateScreen itself appears to be: cg_syscalls.c void trap_UpdateScreen(void) { syscall(CG_UPDATESCREEN); }
This is also called by: UI_Atoms.C
void UI_UpdateScreen(void) { trap_UpdateScreen(); }
it is also called by: ui_local.h void trap_R_DrawStretchPic(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader); void trap_UpdateScreen(void); int trap_CM_LerpTag(orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName);
The locations of the calls and the remarks placed around it imply that this trap is ONLY for updating the screen during connection to local or remote host.
(eg: Loading....shotgun ; Loading.... Gauntlet ect... during the load of a map.)
Definition at line 243 of file cg_syscalls.c.
 {
     syscall(CG_UPDATESCREEN);
 }
trap_VerifyCDKey()
qboolean trap_VerifyCDKey (const char * key, const char * chksum)
Definition at line 484 of file ui_syscalls.c.
 {
     return syscall(UI_VERIFY_CDKEY, key, chksum);
 }
Referenced by UI_CDKeyMenu_Init(), UI_MainMenu(), and UI_RunMenuScript().
UI_AddBots_Cache()
void UI_AddBots_Cache (void)
Definition at line 398 of file ui_addbots.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FIGHT0 );
     trap_R_RegisterShaderNoMip( ART_FIGHT1 );
     trap_R_RegisterShaderNoMip( ART_BACKGROUND );
     trap_R_RegisterShaderNoMip( ART_ARROWS );
     trap_R_RegisterShaderNoMip( ART_ARROWUP );
     trap_R_RegisterShaderNoMip( ART_ARROWDOWN );
 }
UI_AddBotsMenu()
void UI_AddBotsMenu (void)
Definition at line 415 of file ui_addbots.c.
{
     UI_AddBotsMenu_Init();
     UI_PushMenu( &addBotsMenuInfo.menu );
 }
UI_AdjustFrom640()
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 1105 of file ui_atoms.c.
{
     // expect valid pointers
     *x = *x * uis.xscale + uis.bias;
     *y *= uis.yscale;
     *w *= uis.xscale;
     *h *= uis.yscale;
 }
UI_ArenaServersMenu()
void UI_ArenaServersMenu (void)
Definition at line 1643 of file ui_servers2.c.
{
     ArenaServers_MenuInit();
     UI_PushMenu( &g_arenaservers.menu );
 }
Referenced by Main_MenuEvent().
UI_Argv()
char* UI_Argv (int arg)
Definition at line 939 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Argv( arg, buffer, sizeof( buffer ) );
     return buffer;
 }
UI_BotSelectMenu()
void UI_BotSelectMenu (char * bot)
Definition at line 1981 of file ui_startserver.c.
{
     UI_BotSelectMenu_Init( bot );
     UI_PushMenu( &botSelectInfo.menu );
 }
UI_BotSelectMenu_Cache()
void UI_BotSelectMenu_Cache (void)
Definition at line 1839 of file ui_startserver.c.
{
     trap_R_RegisterShaderNoMip( BOTSELECT_BACK0 );
     trap_R_RegisterShaderNoMip( BOTSELECT_BACK1 );
     trap_R_RegisterShaderNoMip( BOTSELECT_ACCEPT0 );
     trap_R_RegisterShaderNoMip( BOTSELECT_ACCEPT1 );
     trap_R_RegisterShaderNoMip( BOTSELECT_SELECT );
     trap_R_RegisterShaderNoMip( BOTSELECT_SELECTED );
     trap_R_RegisterShaderNoMip( BOTSELECT_ARROWS );
     trap_R_RegisterShaderNoMip( BOTSELECT_ARROWSL );
     trap_R_RegisterShaderNoMip( BOTSELECT_ARROWSR );
 }
Referenced by UI_Cache_f().
UI_CanShowTierVideo()
qboolean UI_CanShowTierVideo (int tier)
Definition at line 630 of file ui_gameinfo.c.
{
     char    key[16];
     char    videos[MAX_INFO_VALUE];
     if( !tier ) {
         return qfalse;
     }
     if( uis.demoversion && tier != 8 ) {
         return qfalse;
     }
     trap_Cvar_VariableStringBuffer( "g_spVideos", videos, sizeof(videos) );
     Com_sprintf( key, sizeof(key), "tier%i", tier );
     if( atoi( Info_ValueForKey( videos, key ) ) ) {
         return qtrue;
     }
     return qfalse;
 }
UI_CDKeyMenu()
void UI_CDKeyMenu (void)
Definition at line 278 of file ui_cdkey.c.
{
     UI_CDKeyMenu_Init();
     UI_PushMenu( &cdkeyMenuInfo.menu );
 }
UI_CDKeyMenu_Cache()
void UI_CDKeyMenu_Cache (void)
Definition at line 264 of file ui_cdkey.c.
{
     trap_R_RegisterShaderNoMip( ART_ACCEPT0 );
     trap_R_RegisterShaderNoMip( ART_ACCEPT1 );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FRAME );
 }
UI_CDKeyMenu_f()
void UI_CDKeyMenu_f (void)
Definition at line 289 of file ui_cdkey.c.
{
     UI_CDKeyMenu();
 }
UI_CinematicsMenu()
void UI_CinematicsMenu (void)
Definition at line 333 of file ui_cinematics.c.
{
     UI_CinematicsMenu_Init();
     UI_PushMenu( &cinematicsMenuInfo.menu );
 }
UI_CinematicsMenu_Cache()
void UI_CinematicsMenu_Cache (void)
Definition at line 320 of file ui_cinematics.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
UI_CinematicsMenu_f()
void UI_CinematicsMenu_f (void)
Definition at line 344 of file ui_cinematics.c.
{
     int     n;
     n = atoi( UI_Argv( 1 ) );
     UI_CinematicsMenu();
     Menu_SetCursorToItem( &cinematicsMenuInfo.menu, cinematicsMenuInfo.menu.items[n + 3] );
 }
UI_ClampCvar()
float UI_ClampCvar (float min, float max, float value)
Definition at line 60 of file ui_atoms.c.
 {
     if ( value < min ) return min;
     if ( value > max ) return max;
     return value;
 }
UI_ConfirmMenu()
void UI_ConfirmMenu (const char * question, void(*)(void) draw, void(*)(qboolean result) action)
Definition at line 241 of file ui_confirm.c.
{
     UI_ConfirmMenu_Style(question, UI_CENTER|UI_INVERSE, draw, action);
 }
UI_ConfirmMenu_Style()
void UI_ConfirmMenu_Style (const char * question, int style, void(*)(void) draw, void(*)(qboolean result) action)
Definition at line 173 of file ui_confirm.c.
{
     uiClientState_t cstate;
     int n1, n2, n3;
     int l1, l2, l3;
     // zero set all our globals
     memset( &s_confirm, 0, sizeof(s_confirm) );
     ConfirmMenu_Cache();
     n1 = UI_ProportionalStringWidth( "YES/NO" );
     n2 = UI_ProportionalStringWidth( "YES" ) + PROP_GAP_WIDTH;
     n3 = UI_ProportionalStringWidth( "/" )  + PROP_GAP_WIDTH;
     l1 = 320 - ( n1 / 2 );
     l2 = l1 + n2;
     l3 = l2 + n3;
     s_confirm.slashX = l2;
     s_confirm.question = question;
     s_confirm.draw = draw;
     s_confirm.action = action;
     s_confirm.style = style;
     s_confirm.menu.draw       = ConfirmMenu_Draw;
     s_confirm.menu.key        = ConfirmMenu_Key;
     s_confirm.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         s_confirm.menu.fullscreen = qfalse;
     }
     else {
         s_confirm.menu.fullscreen = qtrue;
     }
     s_confirm.yes.generic.type      = MTYPE_PTEXT;
     s_confirm.yes.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.yes.generic.callback  = ConfirmMenu_Event;
     s_confirm.yes.generic.id        = ID_CONFIRM_YES;
     s_confirm.yes.generic.x         = l1;
     s_confirm.yes.generic.y         = 264;
     s_confirm.yes.string            = "YES";
     s_confirm.yes.color             = color_red;
     s_confirm.yes.style             = UI_LEFT;
     s_confirm.no.generic.type       = MTYPE_PTEXT;
     s_confirm.no.generic.flags      = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.no.generic.callback   = ConfirmMenu_Event;
     s_confirm.no.generic.id         = ID_CONFIRM_NO;
     s_confirm.no.generic.x          = l3;
     s_confirm.no.generic.y          = 264;
     s_confirm.no.string             = "NO";
     s_confirm.no.color              = color_red;
     s_confirm.no.style              = UI_LEFT;
     Menu_AddItem( &s_confirm.menu,  &s_confirm.yes );
     Menu_AddItem( &s_confirm.menu,  &s_confirm.no );
     UI_PushMenu( &s_confirm.menu );
     Menu_SetCursorToItem( &s_confirm.menu, &s_confirm.no );
 }
References confirmMenu_t::action, CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_red, ConfirmMenu_Cache(), ConfirmMenu_Draw(), ConfirmMenu_Event(), ConfirmMenu_Key(), uiClientState_t::connState, confirmMenu_t::draw, _tag_menuframework::draw, menucommon_s::flags, _tag_menuframework::fullscreen, menutext_s::generic, menucommon_s::id, ID_CONFIRM_NO, ID_CONFIRM_YES, _tag_menuframework::key, confirmMenu_t::menu, Menu_AddItem(), Menu_SetCursorToItem(), MTYPE_PTEXT, confirmMenu_t::no, PROP_GAP_WIDTH, qfalse, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, confirmMenu_t::question, s_confirm, confirmMenu_t::slashX, menutext_s::string, confirmMenu_t::style, menutext_s::style, trap_GetClientState(), menucommon_s::type, UI_LEFT, UI_ProportionalStringWidth(), UI_PushMenu(), _tag_menuframework::wrapAround, menucommon_s::x, menucommon_s::y, and confirmMenu_t::yes.
Referenced by ArenaServers_Event(), and UI_ConfirmMenu().
UI_ConsoleCommand()
qboolean UI_ConsoleCommand (int realTime)
Definition at line 1003 of file ui_atoms.c.
{
     char    *cmd;
     uis.frametime = realTime - uis.realtime;
     uis.realtime = realTime;
     cmd = UI_Argv( 0 );
     // ensure minimum menu data is available
     Menu_Cache();
     if ( Q_stricmp (cmd, "levelselect") == 0 ) {
         UI_SPLevelMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "postgame") == 0 ) {
         UI_SPPostgameMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cache") == 0 ) {
         UI_Cache_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cinematics") == 0 ) {
         UI_CinematicsMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_teamOrders") == 0 ) {
         UI_TeamOrdersMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "iamacheater") == 0 ) {
         UI_SPUnlock_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "iamamonkey") == 0 ) {
         UI_SPUnlockMedals_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cdkey") == 0 ) {
         UI_CDKeyMenu_f();
         return qtrue;
     }
     return qfalse;
 }
UI_ControlsMenu()
void UI_ControlsMenu (void)
Definition at line 1672 of file ui_controls2.c.
{
     Controls_MenuInit();
     UI_PushMenu( &s_controls.menu );
 }
UI_CreditMenu()
void UI_CreditMenu (void)
Definition at line 172 of file ui_credits.c.
{
     memset( &s_credits, 0 ,sizeof(s_credits) );
     s_credits.menu.draw = UI_CreditMenu_Draw;
     s_credits.menu.key = UI_CreditMenu_Key;
     s_credits.menu.fullscreen = qtrue;
     UI_PushMenu ( &s_credits.menu );
 }
UI_CursorInRect()
qboolean UI_CursorInRect (int x, int y, int width, int height)
Definition at line 1263 of file ui_atoms.c.
 {
     if (uis.cursorx < x ||
         uis.cursory < y ||
         uis.cursorx > x+width ||
         uis.cursory > y+height)
         return qfalse;
     return qtrue;
 }
UI_Cvar_VariableString()
char* UI_Cvar_VariableString (const char * var_name)
Definition at line 948 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Cvar_VariableStringBuffer( var_name, buffer, sizeof( buffer ) );
     return buffer;
 }
UI_DemosMenu()
void UI_DemosMenu (void)
Definition at line 301 of file ui_demo2.c.
{
     Demos_MenuInit();
     UI_PushMenu( &s_demos.menu );
 }
UI_DisplayOptionsMenu()
void UI_DisplayOptionsMenu (void)
Definition at line 261 of file ui_display.c.
{
     UI_DisplayOptionsMenu_Init();
     UI_PushMenu( &displayOptionsInfo.menu );
     Menu_SetCursorToItem( &displayOptionsInfo.menu, &displayOptionsInfo.display );
 }
UI_DisplayOptionsMenu_Cache()
void UI_DisplayOptionsMenu_Cache (void)
Definition at line 248 of file ui_display.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
 }
UI_DrawBannerString()
void UI_DrawBannerString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 650 of file cg_drawtools.c.
 {
     const char* s;
     int                ch;
     int                width;
     vec4_t            drawcolor;
     // find the width of the drawn text
     s = str;
     width = 0;
     while (*s) {
         ch = *s;
         if (ch == ' ') {
             width += PROPB_SPACE_WIDTH;
         } else if (ch >= 'A' && ch <= 'Z') {
             width += propMapB[ch - 'A'][2] + PROPB_GAP_WIDTH;
         }
         s++;
     }
     width -= PROPB_GAP_WIDTH;
     switch (style & UI_FORMATMASK) {
     case UI_CENTER:
         x -= width / 2;
         break;
     case UI_RIGHT:
         x -= width;
         break;
     case UI_LEFT:
     default:
         break;
     }
     if (style & UI_DROPSHADOW) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawBannerString2(x + 2, y + 2, str, drawcolor);
     }
     UI_DrawBannerString2(x, y, str, color);
 }
UI_DrawChar()
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
Definition at line 778 of file ui_atoms.c.
 {
     char    buff[2];
     buff[0] = ch;
     buff[1] = '\0';
     UI_DrawString( x, y, buff, style, color );
 }
UI_DrawConnectScreen()
void UI_DrawConnectScreen (qboolean overlay)
Definition at line 162 of file ui_connect.c.
{
     char            *s;
     uiClientState_t cstate;
     char            info[MAX_INFO_VALUE];
     Menu_Cache();
     if ( !overlay ) {
         // draw the dialog background
         UI_SetColor( color_white );
         UI_DrawHandlePic( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, uis.menuBackShader );
     }
     // see what information we should display
     trap_GetClientState( &cstate );
     info[0] = '\0';
     if( trap_GetConfigString( CS_SERVERINFO, info, sizeof(info) ) ) {
         UI_DrawProportionalString( 320, 16, va( "Loading %s", Info_ValueForKey( info, "mapname" ) ), UI_BIGFONT|UI_CENTER|UI_DROPSHADOW, color_white );
     }
     UI_DrawProportionalString( 320, 64, va("Connecting to %s", cstate.servername), UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW, menu_text_color );
     //UI_DrawProportionalString( 320, 96, "Press Esc to abort", UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW, menu_text_color );
     // display global MOTD at bottom
     UI_DrawProportionalString( SCREEN_WIDTH/2, SCREEN_HEIGHT-32,
         Info_ValueForKey( cstate.updateInfoString, "motd" ), UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW, menu_text_color );
     // print any server info (server full, bad version, etc)
     if ( cstate.connState < CA_CONNECTED ) {
         UI_DrawProportionalString_AutoWrapped( 320, 192, 630, 20, cstate.messageString, UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW, menu_text_color );
     }
 #if 0
     // display password field
     if ( passwordNeeded ) {
         s_ingame_menu.x = SCREEN_WIDTH * 0.50 - 128;
         s_ingame_menu.nitems = 0;
         s_ingame_menu.wrapAround = qtrue;
         passwordField.generic.type = MTYPE_FIELD;
         passwordField.generic.name = "Password:";
         passwordField.generic.callback = 0;
         passwordField.generic.x     = 10;
         passwordField.generic.y     = 180;
         Field_Clear( &passwordField.field );
         passwordField.width = 256;
         passwordField.field.widthInChars = 16;
         Q_strncpyz( passwordField.field.buffer, Cvar_VariableString("password"),
             sizeof(passwordField.field.buffer) );
         Menu_AddItem( &s_ingame_menu, ( void * ) &s_customize_player_action );
         MField_Draw( &passwordField );
     }
 #endif
     if ( lastConnState > cstate.connState ) {
         lastLoadingText[0] = '\0';
     }
     lastConnState = cstate.connState;
     switch ( cstate.connState ) {
     case CA_CONNECTING:
         s = va("Awaiting challenge...%i", cstate.connectPacketCount);
         break;
     case CA_CHALLENGING:
         s = va("Awaiting connection...%i", cstate.connectPacketCount);
         break;
     case CA_CONNECTED: {
         char downloadName[MAX_INFO_VALUE];
             trap_Cvar_VariableStringBuffer( "cl_downloadName", downloadName, sizeof(downloadName) );
             if (*downloadName) {
                 UI_DisplayDownloadInfo( downloadName );
                 return;
             }
         }
         s = "Awaiting gamestate...";
         break;
     case CA_LOADING:
         return;
     case CA_PRIMED:
         return;
     default:
         return;
     }
     UI_DrawProportionalString( 320, 128, s, UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW, color_white );
     // password required / connection rejected information goes here
 }
UI_DrawHandlePic()
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
Definition at line 1121 of file ui_atoms.c.
{
     float   s0;
     float   s1;
     float   t0;
     float   t1;
     if( w < 0 ) {   // flip about vertical
         w  = -w;
         s0 = 1;
         s1 = 0;
     }
     else {
         s0 = 0;
         s1 = 1;
     }
     if( h < 0 ) {   // flip about horizontal
         h  = -h;
         t0 = 1;
         t1 = 0;
     }
     else {
         t0 = 0;
         t1 = 1;
     }
     UI_AdjustFrom640( &x, &y, &w, &h );
     trap_R_DrawStretchPic( x, y, w, h, s0, t0, s1, t1, hShader );
 }
UI_DrawNamedPic()
void UI_DrawNamedPic (float x, float y, float width, float height, const char * picname)
Definition at line 1113 of file ui_atoms.c.
{
     qhandle_t   hShader;
     hShader = trap_R_RegisterShaderNoMip( picname );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
UI_DrawPlayer()
void UI_DrawPlayer (float x, float y, float w, float h, playerInfo_t * pi, int time)
Definition at line 714 of file ui_players.c.
{
     refdef_t        refdef;
     refEntity_t     legs = {0};
     refEntity_t     torso = {0};
     refEntity_t     head = {0};
     refEntity_t     gun = {0};
     refEntity_t     barrel = {0};
     refEntity_t     flash = {0};
     vec3_t          origin;
     int             renderfx;
     vec3_t          mins = {-16, -16, -24};
     vec3_t          maxs = {16, 16, 32};
     float           len;
     float           xx;
     if ( !pi->legsModel || !pi->torsoModel || !pi->headModel || !pi->animations[0].numFrames ) {
         return;
     }
     dp_realtime = time;
     if ( pi->pendingWeapon != WP_NUM_WEAPONS && dp_realtime > pi->weaponTimer ) {
         pi->weapon = pi->pendingWeapon;
         pi->lastWeapon = pi->pendingWeapon;
         pi->pendingWeapon = WP_NUM_WEAPONS;
         pi->weaponTimer = 0;
         if( pi->currentWeapon != pi->weapon ) {
             trap_S_StartLocalSound( weaponChangeSound, CHAN_LOCAL );
         }
     }
     UI_AdjustFrom640( &x, &y, &w, &h );
     y -= jumpHeight;
     memset( &refdef, 0, sizeof( refdef ) );
     memset( &legs, 0, sizeof(legs) );
     memset( &torso, 0, sizeof(torso) );
     memset( &head, 0, sizeof(head) );
     refdef.rdflags = RDF_NOWORLDMODEL;
     AxisClear( refdef.viewaxis );
     refdef.x = x;
     refdef.y = y;
     refdef.width = w;
     refdef.height = h;
     refdef.fov_x = (int)((float)refdef.width / uis.xscale / 640.0f * 90.0f);
     xx = refdef.width / uis.xscale / tan( refdef.fov_x / 360 * M_PI );
     refdef.fov_y = atan2( refdef.height / uis.yscale, xx );
     refdef.fov_y *= ( 360 / M_PI );
     // calculate distance so the player nearly fills the box
     len = 0.7 * ( maxs[2] - mins[2] );
     origin[0] = len / tan( DEG2RAD(refdef.fov_x) * 0.5 );
     origin[1] = 0.5 * ( mins[1] + maxs[1] );
     origin[2] = -0.5 * ( mins[2] + maxs[2] );
     refdef.time = dp_realtime;
     trap_R_ClearScene();
     // get the rotation information
     UI_PlayerAngles( pi, legs.axis, torso.axis, head.axis );
     // get the animation state (after rotation, to allow feet shuffle)
     UI_PlayerAnimation( pi, &legs.oldframe, &legs.frame, &legs.backlerp,
          &torso.oldframe, &torso.frame, &torso.backlerp );
     renderfx = RF_LIGHTING_ORIGIN | RF_NOSHADOW;
     //
     // add the legs
     //
     legs.hModel = pi->legsModel;
     legs.customSkin = pi->legsSkin;
     VectorCopy( origin, legs.origin );
     VectorCopy( origin, legs.lightingOrigin );
     legs.renderfx = renderfx;
     VectorCopy (legs.origin, legs.oldorigin);
     trap_R_AddRefEntityToScene( &legs );
     if (!legs.hModel) {
         return;
     }
     //
     // add the torso
     //
     torso.hModel = pi->torsoModel;
     if (!torso.hModel) {
         return;
     }
     torso.customSkin = pi->torsoSkin;
     VectorCopy( origin, torso.lightingOrigin );
     UI_PositionRotatedEntityOnTag( &torso, &legs, pi->legsModel, "tag_torso");
     torso.renderfx = renderfx;
     trap_R_AddRefEntityToScene( &torso );
     //
     // add the head
     //
     head.hModel = pi->headModel;
     if (!head.hModel) {
         return;
     }
     head.customSkin = pi->headSkin;
     VectorCopy( origin, head.lightingOrigin );
     UI_PositionRotatedEntityOnTag( &head, &torso, pi->torsoModel, "tag_head");
     head.renderfx = renderfx;
     trap_R_AddRefEntityToScene( &head );
     //
     // add the gun
     //
     if ( pi->currentWeapon != WP_NONE ) {
         memset( &gun, 0, sizeof(gun) );
         gun.hModel = pi->weaponModel;
         if( pi->currentWeapon == WP_RAILGUN ) {
             Byte4Copy( pi->c1RGBA, gun.shaderRGBA );
         }
         else {
             Byte4Copy( colorWhite, gun.shaderRGBA );
         }
         VectorCopy( origin, gun.lightingOrigin );
         UI_PositionEntityOnTag( &gun, &torso, pi->torsoModel, "tag_weapon");
         gun.renderfx = renderfx;
         trap_R_AddRefEntityToScene( &gun );
     }
     //
     // add the spinning barrel
     //
     if ( pi->realWeapon == WP_MACHINEGUN || pi->realWeapon == WP_GAUNTLET || pi->realWeapon == WP_BFG ) {
         vec3_t  angles;
         memset( &barrel, 0, sizeof(barrel) );
         VectorCopy( origin, barrel.lightingOrigin );
         barrel.renderfx = renderfx;
         barrel.hModel = pi->barrelModel;
         angles[YAW] = 0;
         angles[PITCH] = 0;
         angles[ROLL] = UI_MachinegunSpinAngle( pi );
         AnglesToAxis( angles, barrel.axis );
         UI_PositionRotatedEntityOnTag( &barrel, &gun, pi->weaponModel, "tag_barrel");
         trap_R_AddRefEntityToScene( &barrel );
     }
     //
     // add muzzle flash
     //
     if ( dp_realtime <= pi->muzzleFlashTime ) {
         if ( pi->flashModel ) {
             memset( &flash, 0, sizeof(flash) );
             flash.hModel = pi->flashModel;
             if( pi->currentWeapon == WP_RAILGUN ) {
                 Byte4Copy( pi->c1RGBA, flash.shaderRGBA );
             }
             else {
                 Byte4Copy( colorWhite, flash.shaderRGBA );
             }
             VectorCopy( origin, flash.lightingOrigin );
             UI_PositionEntityOnTag( &flash, &gun, pi->weaponModel, "tag_flash");
             flash.renderfx = renderfx;
             trap_R_AddRefEntityToScene( &flash );
         }
         // make a dlight for the flash
         if ( pi->flashDlightColor[0] || pi->flashDlightColor[1] || pi->flashDlightColor[2] ) {
             trap_R_AddLightToScene( flash.origin, 200 + (rand()&31), pi->flashDlightColor[0],
                 pi->flashDlightColor[1], pi->flashDlightColor[2] );
         }
     }
     //
     // add the chat icon
     //
     if ( pi->chat ) {
         UI_PlayerFloatSprite( pi, origin, trap_R_RegisterShaderNoMip( "sprites/balloon3" ) );
     }
     //
     // add an accent light
     //
     origin[0] -= 100;   // + = behind, - = in front
     origin[1] += 100;   // + = left, - = right
     origin[2] += 100;   // + = above, - = below
     trap_R_AddLightToScene( origin, 500, 1.0, 1.0, 1.0 );
     origin[0] -= 100;
     origin[1] -= 100;
     origin[2] -= 100;
     trap_R_AddLightToScene( origin, 500, 1.0, 0.0, 0.0 );
     trap_R_RenderScene( &refdef );
 }
Referenced by Controls_DrawPlayer(), PlayerModel_DrawPlayer(), PlayerSettings_DrawPlayer(), UI_DrawOpponent(), and UI_DrawPlayerModel().
UI_DrawProportionalString()
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 781 of file cg_drawtools.c.
 {
     vec4_t    drawcolor;
     int        width;
     float    sizeScale;
     sizeScale = UI_ProportionalSizeScale(style);
     switch (style & UI_FORMATMASK) {
     case UI_CENTER:
         width = UI_ProportionalStringWidth(str) * sizeScale;
         x -= width / 2;
         break;
     case UI_RIGHT:
         width = UI_ProportionalStringWidth(str) * sizeScale;
         x -= width;
         break;
     case UI_LEFT:
     default:
         break;
     }
     if (style & UI_DROPSHADOW) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2(x + 2, y + 2, str, drawcolor, sizeScale, cgs.media.charsetProp);
     }
     if (style & UI_INVERSE) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2(x, y, str, drawcolor, sizeScale, cgs.media.charsetProp);
         return;
     }
     if (style & UI_PULSE) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2(x, y, str, color, sizeScale, cgs.media.charsetProp);
         drawcolor[0] = color[0];
         drawcolor[1] = color[1];
         drawcolor[2] = color[2];
         drawcolor[3] = 0.5 + 0.5 * sin(cg.time / PULSE_DIVISOR);
         UI_DrawProportionalString2(x, y, str, drawcolor, sizeScale, cgs.media.charsetPropGlow);
         return;
     }
     UI_DrawProportionalString2(x, y, str, color, sizeScale, cgs.media.charsetProp);
 }
UI_DrawProportionalString_AutoWrapped()
void UI_DrawProportionalString_AutoWrapped (int x, int ystart, int xmax, int ystep, const char * str, int style, vec4_t color)
Definition at line 575 of file ui_atoms.c.
{
     int width;
     char *s1,*s2,*s3;
     char c_bcp;
     char buf[1024];
     float   sizeScale;
     if (!str || str[0]=='\0')
         return;
     sizeScale = UI_ProportionalSizeScale( style );
     Q_strncpyz(buf, str, sizeof(buf));
     s1 = s2 = s3 = buf;
     while (1) {
         do {
             s3++;
         } while (*s3!=' ' && *s3!='\0');
         c_bcp = *s3;
         *s3 = '\0';
         width = UI_ProportionalStringWidth(s1) * sizeScale;
         *s3 = c_bcp;
         if (width > xmax) {
             if (s1==s2)
             {
                 // fuck, don't have a clean cut, we'll overflow
                 s2 = s3;
             }
             *s2 = '\0';
             UI_DrawProportionalString(x, y, s1, style, color);
             y += ystep;
             if (c_bcp == '\0')
       {
         // that was the last word
         // we could start a new loop, but that wouldn't be much use
         // even if the word is too long, we would overflow it (see above)
         // so just print it now if needed
         s2++;
         if (*s2 != '\0') // if we are printing an overflowing line we have s2 == s3
           UI_DrawProportionalString(x, y, s2, style, color);
                 break;
       }
             s2++;
             s1 = s2;
             s3 = s2;
         }
         else
         {
             s2 = s3;
             if (c_bcp == '\0') // we reached the end
             {
                 UI_DrawProportionalString(x, y, s1, style, color);
                 break;
             }
         }
     }
 }
References Q_strncpyz(), UI_DrawProportionalString(), UI_ProportionalSizeScale(), and UI_ProportionalStringWidth().
Referenced by Main_MenuDraw(), and UI_DrawConnectScreen().
UI_DrawRect()
void UI_DrawRect (float x, float y, float width, float height, const float * color)
Definition at line 1174 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y + height - 1, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x + width - 1, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
UI_DrawString()
void UI_DrawString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 699 of file ui_atoms.c.
 {
     int     len;
     int     charw;
     int     charh;
     vec4_t  newcolor;
     vec4_t  lowlight;
     float   *drawcolor;
     vec4_t  dropcolor;
     if( !str ) {
         return;
     }
     if ((style & UI_BLINK) && ((uis.realtime/BLINK_DIVISOR) & 1))
         return;
     if (style & UI_SMALLFONT)
     {
         charw = SMALLCHAR_WIDTH;
         charh = SMALLCHAR_HEIGHT;
     }
     else if (style & UI_GIANTFONT)
     {
         charw = GIANTCHAR_WIDTH;
         charh = GIANTCHAR_HEIGHT;
     }
     else
     {
         charw = BIGCHAR_WIDTH;
         charh = BIGCHAR_HEIGHT;
     }
     if (style & UI_PULSE)
     {
         lowlight[0] = 0.8*color[0];
         lowlight[1] = 0.8*color[1];
         lowlight[2] = 0.8*color[2];
         lowlight[3] = 0.8*color[3];
         UI_LerpColor(color,lowlight,newcolor,0.5+0.5*sin(uis.realtime/PULSE_DIVISOR));
         drawcolor = newcolor;
     }
     else
         drawcolor = color;
     switch (style & UI_FORMATMASK)
     {
         case UI_CENTER:
             // center justify at x
             len = strlen(str);
             x   = x - len*charw/2;
             break;
         case UI_RIGHT:
             // right justify at x
             len = strlen(str);
             x   = x - len*charw;
             break;
         default:
             // left justify at x
             break;
     }
     if ( style & UI_DROPSHADOW )
     {
         dropcolor[0] = dropcolor[1] = dropcolor[2] = 0;
         dropcolor[3] = drawcolor[3];
         UI_DrawString2(x+2,y+2,str,dropcolor,charw,charh);
     }
     UI_DrawString2(x,y,str,drawcolor,charw,charh);
 }
UI_DrawTextBox()
void UI_DrawTextBox (int x, int y, int width, int lines)
Definition at line 1257 of file ui_atoms.c.
 {
     UI_FillRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorBlack );
     UI_DrawRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorWhite );
 }
UI_FillRect()
void UI_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 1158 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
UI_ForceMenuOff()
void UI_ForceMenuOff (void)
Definition at line 152 of file ui_atoms.c.
 {
     uis.menusp     = 0;
     uis.activemenu = NULL;
     trap_Key_SetCatcher( trap_Key_GetCatcher() & ~KEYCATCH_UI );
     trap_Key_ClearStates();
     trap_Cvar_Set( "cl_paused", "0" );
 }
UI_GetArenaInfoByMap()
const char* UI_GetArenaInfoByMap (const char * map)
Definition at line 294 of file ui_gameinfo.c.
{
     int         n;
     for( n = 0; n < ui_numArenas; n++ ) {
         if( Q_stricmp( Info_ValueForKey( ui_arenaInfos[n], "map" ), map ) == 0 ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
UI_GetArenaInfoByNumber()
const char* UI_GetArenaInfoByNumber (int num)
Definition at line 269 of file ui_gameinfo.c.
{
     int     n;
     char    *value;
     if( num < 0 || num >= ui_numArenas ) {
         trap_Print( va( S_COLOR_RED "Invalid arena number: %i\n", num ) );
         return NULL;
     }
     for( n = 0; n < ui_numArenas; n++ ) {
         value = Info_ValueForKey( ui_arenaInfos[n], "num" );
         if( *value && atoi(value) == num ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
UI_GetAwardLevel()
int UI_GetAwardLevel (int award)
Definition at line 549 of file ui_gameinfo.c.
{
     char    key[16];
     char    awardData[MAX_INFO_VALUE];
     trap_Cvar_VariableStringBuffer( "g_spAwards", awardData, sizeof(awardData) );
     Com_sprintf( key, sizeof(key), "a%i", award );
     return atoi( Info_ValueForKey( awardData, key ) );
 }
UI_GetBestScore()
void UI_GetBestScore (int level, int * score, int * skill)
Definition at line 435 of file ui_gameinfo.c.
{
     int     n;
     int     skillScore;
     int     bestScore;
     int     bestScoreSkill;
     char    arenaKey[16];
     char    scores[MAX_INFO_VALUE];
     if( !score || !skill ) {
         return;
     }
     if( level < 0 || level > ui_numArenas ) {
         return;
     }
     bestScore = 0;
     bestScoreSkill = 0;
     for( n = 1; n <= 5; n++ ) {
         trap_Cvar_VariableStringBuffer( va( "g_spScores%i", n ), scores, MAX_INFO_VALUE );
         Com_sprintf( arenaKey, sizeof( arenaKey ), "l%i", level );
         skillScore = atoi( Info_ValueForKey( scores, arenaKey ) );
         if( skillScore < 1 || skillScore > 8 ) {
             continue;
         }
         if( !bestScore || skillScore <= bestScore ) {
             bestScore = skillScore;
             bestScoreSkill = n;
         }
     }
     *score = bestScore;
     *skill = bestScoreSkill;
 }
UI_GetBotInfoByName()
char* UI_GetBotInfoByName (const char * name)
Definition at line 409 of file ui_gameinfo.c.
{
     int     n;
     char    *value;
     for ( n = 0; n < ui_numBots ; n++ ) {
         value = Info_ValueForKey( ui_botInfos[n], "name" );
         if ( !Q_stricmp( value, name ) ) {
             return ui_botInfos[n];
         }
     }
     return NULL;
 }
UI_GetBotInfoByNumber()
char* UI_GetBotInfoByNumber (int num)
Definition at line 395 of file ui_gameinfo.c.
{
     if( num < 0 || num >= ui_numBots ) {
         trap_Print( va( S_COLOR_RED "Invalid bot number: %i\n", num ) );
         return NULL;
     }
     return ui_botInfos[num];
 }
UI_GetCurrentGame()
int UI_GetCurrentGame (void)
Definition at line 660 of file ui_gameinfo.c.
{
     int     level;
     int     rank = 0;
     int     skill;
     const char *info;
     info = UI_GetSpecialArenaInfo( "training" );
     if( info ) {
         level = atoi( Info_ValueForKey( info, "num" ) );
         UI_GetBestScore( level, &rank, &skill );
         if ( !rank || rank > 1 ) {
             return level;
         }
     }
     for( level = 0; level < ui_numSinglePlayerArenas; level++ ) {
         UI_GetBestScore( level, &rank, &skill );
         if ( !rank || rank > 1 ) {
             return level;
         }
     }
     info = UI_GetSpecialArenaInfo( "final" );
     if( !info ) {
         return -1;
     }
     return atoi( Info_ValueForKey( info, "num" ) );
 }
UI_GetNumArenas()
int UI_GetNumArenas (void)
Definition at line 713 of file ui_gameinfo.c.
{
     return ui_numArenas;
 }
UI_GetNumBots()
int UI_GetNumBots (void)
Definition at line 743 of file ui_gameinfo.c.
{
     return ui_numBots;
 }
UI_GetNumSPArenas()
int UI_GetNumSPArenas (void)
Definition at line 723 of file ui_gameinfo.c.
{
     return ui_numSinglePlayerArenas;
 }
UI_GetNumSPTiers()
int UI_GetNumSPTiers (void)
Definition at line 733 of file ui_gameinfo.c.
{
     return ui_numSinglePlayerArenas / ARENAS_PER_TIER;
 }
UI_GetSpecialArenaInfo()
const char* UI_GetSpecialArenaInfo (const char * tag)
Definition at line 312 of file ui_gameinfo.c.
{
     int         n;
     for( n = 0; n < ui_numArenas; n++ ) {
         if( Q_stricmp( Info_ValueForKey( ui_arenaInfos[n], "special" ), tag ) == 0 ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
UI_GraphicsOptionsMenu()
void UI_GraphicsOptionsMenu (void)
Definition at line 1310 of file ui_video.c.
{
     GraphicsOptions_MenuInit();
     UI_PushMenu( &s_graphicsoptions.menu );
     Menu_SetCursorToItem( &s_graphicsoptions.menu, &s_graphicsoptions.graphics );
 }
Referenced by Options_Event(), UI_DisplayOptionsMenu_Event(), UI_NetworkOptionsMenu_Event(), UI_SetupMenu_Event(), and UI_SoundOptionsMenu_Event().
UI_InGameMenu()
void UI_InGameMenu (void)
Definition at line 339 of file ui_ingame.c.
{
     // force as top level menu
     uis.menusp = 0;
     // set menu cursor to a nice location
     uis.cursorx = 319;
     uis.cursory = 80;
     InGame_MenuInit();
     UI_PushMenu( &s_ingame.menu );
 }
UI_Init()
void UI_Init (void)
Definition at line 1070 of file ui_atoms.c.
                      {
     UI_RegisterCvars();
     UI_InitGameinfo();
     // cache redundant calulations
     trap_GetGlconfig( &uis.glconfig );
     // for 640x480 virtualized screen
     uis.xscale = uis.glconfig.vidWidth * (1.0/640.0);
     uis.yscale = uis.glconfig.vidHeight * (1.0/480.0);
     if ( uis.glconfig.vidWidth * 480 > uis.glconfig.vidHeight * 640 ) {
         // wide screen
         uis.bias = 0.5 * ( uis.glconfig.vidWidth - ( uis.glconfig.vidHeight * (640.0/480.0) ) );
         uis.xscale = uis.yscale;
     }
     else {
         // no wide screen
         uis.bias = 0;
     }
     // initialize the menu system
     Menu_Cache();
     uis.activemenu = NULL;
     uis.menusp     = 0;
 }
UI_InitGameinfo()
void UI_InitGameinfo (void)
Definition at line 808 of file ui_gameinfo.c.
{
     UI_InitMemory();
     UI_LoadArenas();
     UI_LoadBots();
     uis.demoversion = qfalse;
 }
UI_IsFullscreen()
qboolean UI_IsFullscreen (void)
Definition at line 788 of file ui_atoms.c.
{
     if ( uis.activemenu && ( trap_Key_GetCatcher() & KEYCATCH_UI ) ) {
         return uis.activemenu->fullscreen;
     }
     return qfalse;
 }
UI_KeyEvent()
void UI_KeyEvent (int key, int down)
Definition at line 851 of file ui_atoms.c.
{
     sfxHandle_t     s;
     if (!uis.activemenu) {
         return;
     }
     if (!down) {
         return;
     }
     if (uis.activemenu->key)
         s = uis.activemenu->key( key );
     else
         s = Menu_DefaultKey( uis.activemenu, key );
     if ((s > 0) && (s != menu_null_sound))
         trap_S_StartLocalSound( s, CHAN_LOCAL_SOUND );
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, _tag_menuframework::key, Menu_DefaultKey(), menu_null_sound, s, trap_S_StartLocalSound(), and uis.
Referenced by vmMain().
UI_LerpColor()
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Definition at line 167 of file ui_atoms.c.
 {
     int i;
     // lerp and clamp each component
     for (i=0; i<4; i++)
     {
         c[i] = a[i] + t*(b[i]-a[i]);
         if (c[i] < 0)
             c[i] = 0;
         else if (c[i] > 1.0)
             c[i] = 1.0;
     }
 }
UI_LoadConfig_Cache()
void UI_LoadConfig_Cache (void)
Definition at line 252 of file ui_loadconfig.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FIGHT0 );
     trap_R_RegisterShaderNoMip( ART_FIGHT1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_ARROWS );
     trap_R_RegisterShaderNoMip( ART_ARROWLEFT );
     trap_R_RegisterShaderNoMip( ART_ARROWRIGHT );
 }
UI_LoadConfigMenu()
void UI_LoadConfigMenu (void)
Definition at line 270 of file ui_loadconfig.c.
{
     LoadConfig_MenuInit();
     UI_PushMenu( &s_configs.menu );
 }
UI_LogAwardData()
void UI_LogAwardData (int award, int data)
Definition at line 520 of file ui_gameinfo.c.
{
     char    key[16];
     char    awardData[MAX_INFO_VALUE];
     int     oldValue;
     if( data == 0 ) {
         return;
     }
     if( award > AWARD_PERFECT ) {
         trap_Print( va( S_COLOR_RED "Bad award %i in UI_LogAwardData\n", award ) );
         return;
     }
     trap_Cvar_VariableStringBuffer( "g_spAwards", awardData, sizeof(awardData) );
     Com_sprintf( key, sizeof(key), "a%i", award );
     oldValue = atoi( Info_ValueForKey( awardData, key ) );
     Info_SetValueForKey( awardData, key, va( "%i", oldValue + data ) );
     trap_Cvar_Set( "g_spAwards", awardData );
 }
UI_LoginMenu()
void UI_LoginMenu (void)
Definition at line 203 of file ui_login.c.
{
     Login_MenuInit();
     UI_PushMenu ( &s_login.menu );
 }
Referenced by Rankings_MenuEvent(), and RankStatus_MenuEvent().
UI_MainMenu()
void UI_MainMenu (void)
Definition at line 269 of file ui_menu.c.
{
     int     y;
     qboolean teamArena = qfalse;
     int     style = UI_CENTER | UI_DROPSHADOW;
     trap_Cvar_Set( "sv_killserver", "1" );
     if( !uis.demoversion && !ui_cdkeychecked.integer ) {
         char    key[17];
         trap_GetCDKey( key, sizeof(key) );
         if( trap_VerifyCDKey( key, NULL ) == qfalse ) {
             UI_CDKeyMenu();
             return;
         }
     }
     memset( &s_main, 0 ,sizeof(mainmenu_t) );
     memset( &s_errorMessage, 0 ,sizeof(errorMessage_t) );
     // com_errorMessage would need that too
     MainMenu_Cache();
     trap_Cvar_VariableStringBuffer( "com_errorMessage", s_errorMessage.errorMessage, sizeof(s_errorMessage.errorMessage) );
     if (strlen(s_errorMessage.errorMessage))
     {
         s_errorMessage.menu.draw = Main_MenuDraw;
         s_errorMessage.menu.key = ErrorMessage_Key;
         s_errorMessage.menu.fullscreen = qtrue;
         s_errorMessage.menu.wrapAround = qtrue;
         s_errorMessage.menu.showlogo = qtrue;
         trap_Key_SetCatcher( KEYCATCH_UI );
         uis.menusp = 0;
         UI_PushMenu ( &s_errorMessage.menu );
         return;
     }
     s_main.menu.draw = Main_MenuDraw;
     s_main.menu.fullscreen = qtrue;
     s_main.menu.wrapAround = qtrue;
     s_main.menu.showlogo = qtrue;
     y = 134;
     s_main.singleplayer.generic.type        = MTYPE_PTEXT;
     s_main.singleplayer.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.singleplayer.generic.x           = 320;
     s_main.singleplayer.generic.y           = y;
     s_main.singleplayer.generic.id          = ID_SINGLEPLAYER;
     s_main.singleplayer.generic.callback    = Main_MenuEvent;
     s_main.singleplayer.string              = "SINGLE PLAYER";
     s_main.singleplayer.color               = color_red;
     s_main.singleplayer.style               = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.multiplayer.generic.type         = MTYPE_PTEXT;
     s_main.multiplayer.generic.flags        = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.multiplayer.generic.x            = 320;
     s_main.multiplayer.generic.y            = y;
     s_main.multiplayer.generic.id           = ID_MULTIPLAYER;
     s_main.multiplayer.generic.callback     = Main_MenuEvent;
     s_main.multiplayer.string               = "MULTIPLAYER";
     s_main.multiplayer.color                = color_red;
     s_main.multiplayer.style                = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.setup.generic.type               = MTYPE_PTEXT;
     s_main.setup.generic.flags              = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.setup.generic.x                  = 320;
     s_main.setup.generic.y                  = y;
     s_main.setup.generic.id                 = ID_SETUP;
     s_main.setup.generic.callback           = Main_MenuEvent;
     s_main.setup.string                     = "SETUP";
     s_main.setup.color                      = color_red;
     s_main.setup.style                      = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.demos.generic.type               = MTYPE_PTEXT;
     s_main.demos.generic.flags              = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.demos.generic.x                  = 320;
     s_main.demos.generic.y                  = y;
     s_main.demos.generic.id                 = ID_DEMOS;
     s_main.demos.generic.callback           = Main_MenuEvent;
     s_main.demos.string                     = "DEMOS";
     s_main.demos.color                      = color_red;
     s_main.demos.style                      = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.cinematics.generic.type          = MTYPE_PTEXT;
     s_main.cinematics.generic.flags         = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.cinematics.generic.x             = 320;
     s_main.cinematics.generic.y             = y;
     s_main.cinematics.generic.id            = ID_CINEMATICS;
     s_main.cinematics.generic.callback      = Main_MenuEvent;
     s_main.cinematics.string                = "CINEMATICS";
     s_main.cinematics.color                 = color_red;
     s_main.cinematics.style                 = style;
     if ( !uis.demoversion && UI_TeamArenaExists() ) {
         teamArena = qtrue;
         y += MAIN_MENU_VERTICAL_SPACING;
         s_main.teamArena.generic.type           = MTYPE_PTEXT;
         s_main.teamArena.generic.flags          = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
         s_main.teamArena.generic.x              = 320;
         s_main.teamArena.generic.y              = y;
         s_main.teamArena.generic.id             = ID_TEAMARENA;
         s_main.teamArena.generic.callback       = Main_MenuEvent;
         s_main.teamArena.string                 = "TEAM ARENA";
         s_main.teamArena.color                  = color_red;
         s_main.teamArena.style                  = style;
     }
     if ( !uis.demoversion ) {
         y += MAIN_MENU_VERTICAL_SPACING;
         s_main.mods.generic.type            = MTYPE_PTEXT;
         s_main.mods.generic.flags           = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
         s_main.mods.generic.x               = 320;
         s_main.mods.generic.y               = y;
         s_main.mods.generic.id              = ID_MODS;
         s_main.mods.generic.callback        = Main_MenuEvent;
         s_main.mods.string                  = "MODS";
         s_main.mods.color                   = color_red;
         s_main.mods.style                   = style;
     }
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.exit.generic.type                = MTYPE_PTEXT;
     s_main.exit.generic.flags               = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.exit.generic.x                   = 320;
     s_main.exit.generic.y                   = y;
     s_main.exit.generic.id                  = ID_EXIT;
     s_main.exit.generic.callback            = Main_MenuEvent;
     s_main.exit.string                      = "EXIT";
     s_main.exit.color                       = color_red;
     s_main.exit.style                       = style;
     Menu_AddItem( &s_main.menu, &s_main.singleplayer );
     Menu_AddItem( &s_main.menu, &s_main.multiplayer );
     Menu_AddItem( &s_main.menu, &s_main.setup );
     Menu_AddItem( &s_main.menu, &s_main.demos );
     Menu_AddItem( &s_main.menu, &s_main.cinematics );
     if (teamArena) {
         Menu_AddItem( &s_main.menu, &s_main.teamArena );
     }
     if ( !uis.demoversion ) {
         Menu_AddItem( &s_main.menu, &s_main.mods );
     }
     Menu_AddItem( &s_main.menu, &s_main.exit );
     trap_Key_SetCatcher( KEYCATCH_UI );
     uis.menusp = 0;
     UI_PushMenu ( &s_main.menu );
 }
Referenced by UI_SetActiveMenu().
UI_Message()
void UI_Message (const char ** lines)
Definition at line 251 of file ui_confirm.c.
{
     uiClientState_t cstate;
     int n1, l1;
     // zero set all our globals
     memset( &s_confirm, 0, sizeof(s_confirm) );
     ConfirmMenu_Cache();
     n1 = UI_ProportionalStringWidth( "OK" );
     l1 = 320 - ( n1 / 2 );
     s_confirm.lines = lines;
     s_confirm.style = UI_CENTER|UI_INVERSE|UI_SMALLFONT;
     s_confirm.menu.draw       = MessageMenu_Draw;
     s_confirm.menu.key        = ConfirmMenu_Key;
     s_confirm.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         s_confirm.menu.fullscreen = qfalse;
     }
     else {
         s_confirm.menu.fullscreen = qtrue;
     }
     s_confirm.yes.generic.type      = MTYPE_PTEXT;
     s_confirm.yes.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.yes.generic.callback  = ConfirmMenu_Event;
     s_confirm.yes.generic.id        = ID_CONFIRM_YES;
     s_confirm.yes.generic.x         = l1;
     s_confirm.yes.generic.y         = 280;
     s_confirm.yes.string            = "OK";
     s_confirm.yes.color             = color_red;
     s_confirm.yes.style             = UI_LEFT;
     Menu_AddItem( &s_confirm.menu,  &s_confirm.yes );
     UI_PushMenu( &s_confirm.menu );
     Menu_SetCursorToItem( &s_confirm.menu, &s_confirm.yes );
 }
References CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_red, ConfirmMenu_Cache(), ConfirmMenu_Event(), ConfirmMenu_Key(), uiClientState_t::connState, _tag_menuframework::draw, menucommon_s::flags, _tag_menuframework::fullscreen, menutext_s::generic, menucommon_s::id, ID_CONFIRM_YES, _tag_menuframework::key, confirmMenu_t::lines, confirmMenu_t::menu, Menu_AddItem(), Menu_SetCursorToItem(), MessageMenu_Draw(), MTYPE_PTEXT, qfalse, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s_confirm, menutext_s::string, confirmMenu_t::style, menutext_s::style, trap_GetClientState(), menucommon_s::type, UI_CENTER, UI_INVERSE, UI_LEFT, UI_ProportionalStringWidth(), UI_PushMenu(), UI_SMALLFONT, _tag_menuframework::wrapAround, menucommon_s::x, menucommon_s::y, and confirmMenu_t::yes.
Referenced by Punkbuster_ConfirmDisable().
UI_ModsMenu()
void UI_ModsMenu (void)
Definition at line 244 of file ui_mods.c.
{
     UI_Mods_MenuInit();
     UI_PushMenu( &s_mods.menu );
 }
Referenced by Main_MenuEvent().
UI_ModsMenu_Cache()
void UI_ModsMenu_Cache (void)
Definition at line 229 of file ui_mods.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FIGHT0 );
     trap_R_RegisterShaderNoMip( ART_FIGHT1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
Referenced by UI_Cache_f().
UI_MouseEvent()
void UI_MouseEvent (int dx, int dy)
Definition at line 876 of file ui_atoms.c.
 {
     int             i;
     int             bias;
     menucommon_s*   m;
     if (!uis.activemenu)
         return;
     // convert X bias to 640 coords
     bias = uis.bias / uis.xscale;
     // update mouse screen position
     uis.cursorx += dx;
     if (uis.cursorx < -bias)
         uis.cursorx = -bias;
     else if (uis.cursorx > SCREEN_WIDTH+bias)
         uis.cursorx = SCREEN_WIDTH+bias;
     uis.cursory += dy;
     if (uis.cursory < 0)
         uis.cursory = 0;
     else if (uis.cursory > SCREEN_HEIGHT)
         uis.cursory = SCREEN_HEIGHT;
     // region test the active menu items
     for (i=0; i<uis.activemenu->nitems; i++)
     {
         m = (menucommon_s*)uis.activemenu->items[i];
         if (m->flags & (QMF_GRAYED|QMF_INACTIVE))
             continue;
         if ((uis.cursorx < m->left) ||
             (uis.cursorx > m->right) ||
             (uis.cursory < m->top) ||
             (uis.cursory > m->bottom))
         {
             // cursor out of item bounds
             continue;
         }
         // set focus to item at cursor
         if (uis.activemenu->cursor != i)
         {
             Menu_SetCursor( uis.activemenu, i );
             ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor_prev]))->flags &= ~QMF_HASMOUSEFOCUS;
             if ( !(((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags & QMF_SILENT ) ) {
                 trap_S_StartLocalSound( menu_move_sound, CHAN_LOCAL_SOUND );
             }
         }
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags |= QMF_HASMOUSEFOCUS;
         return;
     }
     if (uis.activemenu->nitems > 0) {
         // out of any region
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags &= ~QMF_HASMOUSEFOCUS;
     }
 }
UI_NetworkOptionsMenu()
void UI_NetworkOptionsMenu (void)
Definition at line 277 of file ui_network.c.
{
     UI_NetworkOptionsMenu_Init();
     UI_PushMenu( &networkOptionsInfo.menu );
     Menu_SetCursorToItem( &networkOptionsInfo.menu, &networkOptionsInfo.network );
 }
Referenced by GraphicsOptions_Event(), Options_Event(), UI_DisplayOptionsMenu_Event(), and UI_SoundOptionsMenu_Event().
UI_NetworkOptionsMenu_Cache()
void UI_NetworkOptionsMenu_Cache (void)
Definition at line 264 of file ui_network.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
 }
Referenced by UI_Cache_f().
UI_NewGame()
void UI_NewGame (void)
Definition at line 697 of file ui_gameinfo.c.
{
     trap_Cvar_Set( "g_spScores1", "" );
     trap_Cvar_Set( "g_spScores2", "" );
     trap_Cvar_Set( "g_spScores3", "" );
     trap_Cvar_Set( "g_spScores4", "" );
     trap_Cvar_Set( "g_spScores5", "" );
     trap_Cvar_Set( "g_spAwards", "" );
     trap_Cvar_Set( "g_spVideos", "" );
 }
UI_PlayerInfo_SetInfo()
void UI_PlayerInfo_SetInfo (playerInfo_t * pi, int legsAnim, int torsoAnim, vec3_t viewAngles, vec3_t moveAngles, weapon_t weaponNum, qboolean chat)
Definition at line 1202 of file ui_players.c.
{
     int         currentAnim;
     weapon_t    weaponNum;
     int         c;
     pi->chat = chat;
     c = (int)trap_Cvar_VariableValue( "color1" );
     VectorClear( pi->color1 );
     if( c < 1 || c > 7 ) {
         VectorSet( pi->color1, 1, 1, 1 );
     }
     else {
         if( c & 1 ) {
             pi->color1[2] = 1.0f;
         }
         if( c & 2 ) {
             pi->color1[1] = 1.0f;
         }
         if( c & 4 ) {
             pi->color1[0] = 1.0f;
         }
     }
     pi->c1RGBA[0] = 255 * pi->color1[0];
     pi->c1RGBA[1] = 255 * pi->color1[1];
     pi->c1RGBA[2] = 255 * pi->color1[2];
     pi->c1RGBA[3] = 255;
     // view angles
     VectorCopy( viewAngles, pi->viewAngles );
     // move angles
     VectorCopy( moveAngles, pi->moveAngles );
     if ( pi->newModel ) {
         pi->newModel = qfalse;
         jumpHeight = 0;
         pi->pendingLegsAnim = 0;
         UI_ForceLegsAnim( pi, legsAnim );
         pi->legs.yawAngle = viewAngles[YAW];
         pi->legs.yawing = qfalse;
         pi->pendingTorsoAnim = 0;
         UI_ForceTorsoAnim( pi, torsoAnim );
         pi->torso.yawAngle = viewAngles[YAW];
         pi->torso.yawing = qfalse;
         if ( weaponNumber != WP_NUM_WEAPONS ) {
             pi->weapon = weaponNumber;
             pi->currentWeapon = weaponNumber;
             pi->lastWeapon = weaponNumber;
             pi->pendingWeapon = WP_NUM_WEAPONS;
             pi->weaponTimer = 0;
             UI_PlayerInfo_SetWeapon( pi, pi->weapon );
         }
         return;
     }
     // weapon
     if ( weaponNumber == WP_NUM_WEAPONS ) {
         pi->pendingWeapon = WP_NUM_WEAPONS;
         pi->weaponTimer = 0;
     }
     else if ( weaponNumber != WP_NONE ) {
         pi->pendingWeapon = weaponNumber;
         pi->weaponTimer = dp_realtime + UI_TIMER_WEAPON_DELAY;
     }
     weaponNum = pi->lastWeapon;
     pi->weapon = weaponNum;
     if ( torsoAnim == BOTH_DEATH1 || legsAnim == BOTH_DEATH1 ) {
         torsoAnim = legsAnim = BOTH_DEATH1;
         pi->weapon = pi->currentWeapon = WP_NONE;
         UI_PlayerInfo_SetWeapon( pi, pi->weapon );
         jumpHeight = 0;
         pi->pendingLegsAnim = 0;
         UI_ForceLegsAnim( pi, legsAnim );
         pi->pendingTorsoAnim = 0;
         UI_ForceTorsoAnim( pi, torsoAnim );
         return;
     }
     // leg animation
     currentAnim = pi->legsAnim & ~ANIM_TOGGLEBIT;
     if ( legsAnim != LEGS_JUMP && ( currentAnim == LEGS_JUMP || currentAnim == LEGS_LAND ) ) {
         pi->pendingLegsAnim = legsAnim;
     }
     else if ( legsAnim != currentAnim ) {
         jumpHeight = 0;
         pi->pendingLegsAnim = 0;
         UI_ForceLegsAnim( pi, legsAnim );
     }
     // torso animation
     if ( torsoAnim == TORSO_STAND || torsoAnim == TORSO_STAND2 ) {
         if ( weaponNum == WP_NONE || weaponNum == WP_GAUNTLET ) {
             torsoAnim = TORSO_STAND2;
         }
         else {
             torsoAnim = TORSO_STAND;
         }
     }
     if ( torsoAnim == TORSO_ATTACK || torsoAnim == TORSO_ATTACK2 ) {
         if ( weaponNum == WP_NONE || weaponNum == WP_GAUNTLET ) {
             torsoAnim = TORSO_ATTACK2;
         }
         else {
             torsoAnim = TORSO_ATTACK;
         }
         pi->muzzleFlashTime = dp_realtime + UI_TIMER_MUZZLE_FLASH;
         //FIXME play firing sound here
     }
     currentAnim = pi->torsoAnim & ~ANIM_TOGGLEBIT;
     if ( weaponNum != pi->currentWeapon || currentAnim == TORSO_RAISE || currentAnim == TORSO_DROP ) {
         pi->pendingTorsoAnim = torsoAnim;
     }
     else if ( ( currentAnim == TORSO_GESTURE || currentAnim == TORSO_ATTACK ) && ( torsoAnim != currentAnim ) ) {
         pi->pendingTorsoAnim = torsoAnim;
     }
     else if ( torsoAnim != currentAnim ) {
         pi->pendingTorsoAnim = 0;
         UI_ForceTorsoAnim( pi, torsoAnim );
     }
 }
Referenced by Controls_UpdateModel(), PlayerModel_UpdateModel(), PlayerSettings_DrawPlayer(), PlayerSettings_SetMenuItems(), UI_DrawOpponent(), and UI_DrawPlayerModel().
UI_PlayerInfo_SetModel()
void UI_PlayerInfo_SetModel (playerInfo_t * pi, const char * model)
Definition at line 1183 of file ui_players.c.
{
     memset( pi, 0, sizeof(*pi) );
     UI_RegisterClientModelname( pi, model );
     pi->weapon = WP_MACHINEGUN;
     pi->currentWeapon = pi->weapon;
     pi->lastWeapon = pi->weapon;
     pi->pendingWeapon = WP_NUM_WEAPONS;
     pi->weaponTimer = 0;
     pi->chat = qfalse;
     pi->newModel = qtrue;
     UI_PlayerInfo_SetWeapon( pi, pi->weapon );
 }
References playerInfo_t::chat, playerInfo_t::currentWeapon, playerInfo_t::lastWeapon, playerInfo_t::newModel, playerInfo_t::pendingWeapon, qfalse, qtrue, UI_PlayerInfo_SetWeapon(), UI_RegisterClientModelname(), playerInfo_t::weapon, playerInfo_t::weaponTimer, WP_MACHINEGUN, and WP_NUM_WEAPONS.
Referenced by Controls_DrawPlayer(), Controls_InitModel(), PlayerModel_UpdateModel(), PlayerSettings_DrawPlayer(), PlayerSettings_SetMenuItems(), UI_DrawOpponent(), and UI_DrawPlayerModel().
UI_PlayerModelMenu()
void UI_PlayerModelMenu (void)
Definition at line 727 of file ui_playermodel.c.
 {
     PlayerModel_MenuInit();
     UI_PushMenu( &s_playermodel.menu );
     Menu_SetCursorToItem( &s_playermodel.menu, &s_playermodel.pics[s_playermodel.selectedmodel % MAX_MODELSPERPAGE] );
 }
Referenced by PlayerSettings_MenuEvent().
UI_PlayerSettingsMenu()
void UI_PlayerSettingsMenu (void)
Definition at line 510 of file ui_playersettings.c.
{
     PlayerSettings_MenuInit();
     UI_PushMenu( &s_playersettings.menu );
 }
Referenced by UI_SetupMenu_Event(), and UI_SPLevelMenu_PlayerEvent().
UI_PopMenu()
void UI_PopMenu (void)
Definition at line 134 of file ui_atoms.c.
 {
     trap_S_StartLocalSound( menu_out_sound, CHAN_LOCAL_SOUND );
     uis.menusp--;
     if (uis.menusp < 0)
         trap_Error ("UI_PopMenu: menu stack underflow");
     if (uis.menusp) {
         uis.activemenu = uis.stack[uis.menusp-1];
         uis.firstdraw = qtrue;
     }
     else {
         UI_ForceMenuOff ();
     }
 }
UI_PreferencesMenu()
void UI_PreferencesMenu (void)
Definition at line 412 of file ui_preferences.c.
{
     Preferences_MenuInit();
     UI_PushMenu( &s_preferences.menu );
 }
Referenced by UI_SetupMenu_Event().
UI_ProportionalSizeScale()
float UI_ProportionalSizeScale (int style)
Definition at line 766 of file cg_drawtools.c.
 {
     if (style & UI_SMALLFONT) {
         return 0.75;
     }
     return 1.00;
 }
UI_ProportionalStringWidth()
int UI_ProportionalStringWidth (const char * str)
Definition at line 695 of file cg_drawtools.c.
 {
     const char* s;
     int                ch;
     int                charWidth;
     int                width;
     s = str;
     width = 0;
     while (*s) {
         ch = *s & 127;
         charWidth = propMap[ch][2];
         if (charWidth != -1) {
             width += charWidth;
             width += PROP_GAP_WIDTH;
         }
         s++;
     }
     width -= PROP_GAP_WIDTH;
     return width;
 }
UI_PushMenu()
void UI_PushMenu (menuframework_s * menu)
Definition at line 81 of file ui_atoms.c.
 {
     int             i;
     menucommon_s*   item;
     // avoid stacking menus invoked by hotkeys
     for (i=0 ; i<uis.menusp ; i++)
     {
         if (uis.stack[i] == menu)
         {
             uis.menusp = i;
             break;
         }
     }
     if (i == uis.menusp)
     {
         if (uis.menusp >= MAX_MENUDEPTH)
             trap_Error("UI_PushMenu: menu stack overflow");
         uis.stack[uis.menusp++] = menu;
     }
     uis.activemenu = menu;
     // default cursor position
     menu->cursor      = 0;
     menu->cursor_prev = 0;
     m_entersound = qtrue;
     trap_Key_SetCatcher( KEYCATCH_UI );
     // force first available item to have focus
     for (i=0; i<menu->nitems; i++)
     {
         item = (menucommon_s *)menu->items[i];
         if (!(item->flags & (QMF_GRAYED|QMF_MOUSEONLY|QMF_INACTIVE)))
         {
             menu->cursor_prev = -1;
             Menu_SetCursor( menu, i );
             break;
         }
     }
     uis.firstdraw = qtrue;
 }
UI_RankingsMenu()
void UI_RankingsMenu (void)
Definition at line 415 of file ui_rankings.c.
{
     Rankings_MenuInit();
     UI_PushMenu ( &s_rankings.menu );
 }
References rankings_t::menu, Rankings_MenuInit(), s_rankings, and UI_PushMenu().
Referenced by RankStatus_MenuEvent().
UI_RankStatusMenu()
void UI_RankStatusMenu (void)
Definition at line 168 of file ui_rankstatus.c.
{
     s_status = (grank_status_t)trap_Cvar_VariableValue("client_status");
     switch( s_status )
     {
     case QGR_STATUS_NEW:
         return;
     case QGR_STATUS_PENDING:
         // GRANK_FIXME
         return;
     case QGR_STATUS_NO_USER:
         // GRANK_FIXME - get this when user exists
         s_rankstatus_message = "Username unavailable";
         break;
     case QGR_STATUS_BAD_PASSWORD:
         s_rankstatus_message = "Invalid password";
         break;
     case QGR_STATUS_TIMEOUT:
         s_rankstatus_message = "Timed out";
         break;
     case QGR_STATUS_NO_MEMBERSHIP:
         s_rankstatus_message = "No membership";
         break;
     case QGR_STATUS_INVALIDUSER:
         s_rankstatus_message = "Validation failed";
         break;
     case QGR_STATUS_ERROR:
         s_rankstatus_message = "Error";
         break;
     case QGR_STATUS_SPECTATOR:
     case QGR_STATUS_ACTIVE:
         UI_ForceMenuOff();
         return;
     default:
         return;
     }
     RankStatus_MenuInit();
     trap_CL_UI_RankUserReset();
     UI_PushMenu ( &s_rankstatus.menu );
 }
UI_Refresh()
void UI_Refresh (int realtime)
Definition at line 1200 of file ui_atoms.c.
 {
     uis.frametime = realtime - uis.realtime;
     uis.realtime  = realtime;
     if ( !( trap_Key_GetCatcher() & KEYCATCH_UI ) ) {
         return;
     }
     UI_UpdateCvars();
     if ( uis.activemenu )
     {
         if (uis.activemenu->fullscreen)
         {
             // draw the background
             if( uis.activemenu->showlogo ) {
                 UI_DrawHandlePic( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, uis.menuBackShader );
             }
             else {
                 UI_DrawHandlePic( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, uis.menuBackNoLogoShader );
             }
         }
         if (uis.activemenu->draw)
             uis.activemenu->draw();
         else
             Menu_Draw( uis.activemenu );
         if( uis.firstdraw ) {
             UI_MouseEvent( 0, 0 );
             uis.firstdraw = qfalse;
         }
     }
     // draw cursor
     UI_SetColor( NULL );
     UI_DrawHandlePic( uis.cursorx-16, uis.cursory-16, 32, 32, uis.cursor);
 #ifndef NDEBUG
     if (uis.debug)
     {
         // cursor coordinates
         UI_DrawString( 0, 0, va("(%d,%d)",uis.cursorx,uis.cursory), UI_LEFT|UI_SMALLFONT, colorRed );
     }
 #endif
     // delay playing the enter sound until after the
     // menu has been drawn, to avoid delay while
     // caching images
     if (m_entersound)
     {
         trap_S_StartLocalSound( menu_in_sound, CHAN_LOCAL_SOUND );
         m_entersound = qfalse;
     }
 }
UI_RegisterClientModelname()
qboolean UI_RegisterClientModelname (playerInfo_t * pi, const char * modelSkinName)
Definition at line 1111 of file ui_players.c.
{
     char        modelName[MAX_QPATH];
     char        skinName[MAX_QPATH];
     char        filename[MAX_QPATH];
     char        *slash;
     pi->torsoModel = 0;
     pi->headModel = 0;
     if ( !modelSkinName[0] ) {
         return qfalse;
     }
     Q_strncpyz( modelName, modelSkinName, sizeof( modelName ) );
     slash = strchr( modelName, '/' );
     if ( !slash ) {
         // modelName did not include a skin name
         Q_strncpyz( skinName, "default", sizeof( skinName ) );
     } else {
         Q_strncpyz( skinName, slash + 1, sizeof( skinName ) );
         // truncate modelName
         *slash = 0;
     }
     // load cmodels before models so filecache works
     Com_sprintf( filename, sizeof( filename ), "models/players/%s/lower.md3", modelName );
     pi->legsModel = trap_R_RegisterModel( filename );
     if ( !pi->legsModel ) {
         Com_Printf( "Failed to load model file %s\n", filename );
         return qfalse;
     }
     Com_sprintf( filename, sizeof( filename ), "models/players/%s/upper.md3", modelName );
     pi->torsoModel = trap_R_RegisterModel( filename );
     if ( !pi->torsoModel ) {
         Com_Printf( "Failed to load model file %s\n", filename );
         return qfalse;
     }
     Com_sprintf( filename, sizeof( filename ), "models/players/%s/head.md3", modelName );
     pi->headModel = trap_R_RegisterModel( filename );
     if ( !pi->headModel ) {
         Com_Printf( "Failed to load model file %s\n", filename );
         return qfalse;
     }
     // if any skins failed to load, fall back to default
     if ( !UI_RegisterClientSkin( pi, modelName, skinName ) ) {
         if ( !UI_RegisterClientSkin( pi, modelName, "default" ) ) {
             Com_Printf( "Failed to load skin file: %s : %s\n", modelName, skinName );
             return qfalse;
         }
     }
     // load the animations
     Com_sprintf( filename, sizeof( filename ), "models/players/%s/animation.cfg", modelName );
     if ( !UI_ParseAnimationFile( filename, pi ) ) {
         Com_Printf( "Failed to load animation file %s\n", filename );
         return qfalse;
     }
     return qtrue;
 }
References Com_Printf(), Com_sprintf(), playerInfo_t::headModel, playerInfo_t::legsModel, MAX_QPATH, Q_strncpyz(), qfalse, qtrue, playerInfo_t::torsoModel, trap_R_RegisterModel(), UI_ParseAnimationFile(), and UI_RegisterClientSkin().
Referenced by UI_DrawOpponent(), and UI_PlayerInfo_SetModel().
UI_RegisterCvars()
void UI_RegisterCvars (void)
Definition at line 229 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         trap_Cvar_Register( cv->vmCvar, cv->cvarName, cv->defaultString, cv->cvarFlags );
     }
 }
Referenced by UI_Init().
UI_RemoveBots_Cache()
void UI_RemoveBots_Cache (void)
Definition at line 211 of file ui_removebots.c.
{
     trap_R_RegisterShaderNoMip( ART_BACKGROUND );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_DELETE0 );
     trap_R_RegisterShaderNoMip( ART_DELETE1 );
 }
Referenced by UI_Cache_f().
UI_RemoveBotsMenu()
void UI_RemoveBotsMenu (void)
Definition at line 339 of file ui_removebots.c.
{
     UI_RemoveBotsMenu_Init();
     UI_PushMenu( &removeBotsMenuInfo.menu );
 }
Referenced by InGame_Event().
UI_SaveConfigMenu()
void UI_SaveConfigMenu (void)
Definition at line 209 of file ui_saveconfig.c.
{
     UI_SaveConfigMenu_Init();
     UI_PushMenu( &saveConfig.menu );
 }
UI_SaveConfigMenu_Cache()
void UI_SaveConfigMenu_Cache (void)
Definition at line 195 of file ui_saveconfig.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_SAVE0 );
     trap_R_RegisterShaderNoMip( ART_SAVE1 );
     trap_R_RegisterShaderNoMip( ART_BACKGROUND );
 }
UI_ServerInfoMenu()
void UI_ServerInfoMenu (void)
Definition at line 186 of file ui_serverinfo.c.
 {
     const char      *s;
     char            key[MAX_INFO_KEY];
     char            value[MAX_INFO_VALUE];
     // zero set all our globals
     memset( &s_serverinfo, 0 ,sizeof(serverinfo_t) );
     ServerInfo_Cache();
     s_serverinfo.menu.draw       = ServerInfo_MenuDraw;
     s_serverinfo.menu.key        = ServerInfo_MenuKey;
     s_serverinfo.menu.wrapAround = qtrue;
     s_serverinfo.menu.fullscreen = qtrue;
     s_serverinfo.banner.generic.type  = MTYPE_BTEXT;
     s_serverinfo.banner.generic.x     = 320;
     s_serverinfo.banner.generic.y     = 16;
     s_serverinfo.banner.string        = "SERVER INFO";
     s_serverinfo.banner.color         = color_white;
     s_serverinfo.banner.style         = UI_CENTER;
     s_serverinfo.framel.generic.type  = MTYPE_BITMAP;
     s_serverinfo.framel.generic.name  = SERVERINFO_FRAMEL;
     s_serverinfo.framel.generic.flags = QMF_INACTIVE;
     s_serverinfo.framel.generic.x     = 0;
     s_serverinfo.framel.generic.y     = 78;
     s_serverinfo.framel.width         = 256;
     s_serverinfo.framel.height        = 329;
     s_serverinfo.framer.generic.type  = MTYPE_BITMAP;
     s_serverinfo.framer.generic.name  = SERVERINFO_FRAMER;
     s_serverinfo.framer.generic.flags = QMF_INACTIVE;
     s_serverinfo.framer.generic.x     = 376;
     s_serverinfo.framer.generic.y     = 76;
     s_serverinfo.framer.width         = 256;
     s_serverinfo.framer.height        = 334;
     s_serverinfo.add.generic.type     = MTYPE_PTEXT;
     s_serverinfo.add.generic.flags    = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_serverinfo.add.generic.callback = ServerInfo_Event;
     s_serverinfo.add.generic.id       = ID_ADD;
     s_serverinfo.add.generic.x        = 320;
     s_serverinfo.add.generic.y        = 371;
     s_serverinfo.add.string           = "ADD TO FAVORITES";
     s_serverinfo.add.style            = UI_CENTER|UI_SMALLFONT;
     s_serverinfo.add.color            = color_red;
     if( trap_Cvar_VariableValue( "sv_running" ) ) {
         s_serverinfo.add.generic.flags |= QMF_GRAYED;
     }
     s_serverinfo.back.generic.type     = MTYPE_BITMAP;
     s_serverinfo.back.generic.name     = SERVERINFO_BACK0;
     s_serverinfo.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_serverinfo.back.generic.callback = ServerInfo_Event;
     s_serverinfo.back.generic.id       = ID_BACK;
     s_serverinfo.back.generic.x        = 0;
     s_serverinfo.back.generic.y        = 480-64;
     s_serverinfo.back.width            = 128;
     s_serverinfo.back.height           = 64;
     s_serverinfo.back.focuspic         = SERVERINFO_BACK1;
     trap_GetConfigString( CS_SERVERINFO, s_serverinfo.info, MAX_INFO_STRING );
     s_serverinfo.numlines = 0;
     s = s_serverinfo.info;
     while ( s ) {
         Info_NextPair( &s, key, value );
         if ( !key[0] ) {
             break;
         }
         s_serverinfo.numlines++;
     }
     if (s_serverinfo.numlines > 16)
         s_serverinfo.numlines = 16;
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.banner );
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.framel );
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.framer );
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.add );
     Menu_AddItem( &s_serverinfo.menu, (void*) &s_serverinfo.back );
     UI_PushMenu( &s_serverinfo.menu );
 }
Referenced by InGame_Event().
UI_SetActiveMenu()
void UI_SetActiveMenu (uiMenuCommand_t menu)
Definition at line 808 of file ui_atoms.c.
{
     // this should be the ONLY way the menu system is brought up
     // ensure minimum menu data is cached
     Menu_Cache();
     switch ( menu ) {
     case UIMENU_NONE:
         UI_ForceMenuOff();
         return;
     case UIMENU_MAIN:
         UI_MainMenu();
         return;
     case UIMENU_NEED_CD:
         UI_ConfirmMenu( "Insert the CD", 0, NeedCDAction );
         return;
     case UIMENU_BAD_CD_KEY:
         UI_ConfirmMenu( "Bad CD Key", 0, NeedCDKeyAction );
         return;
     case UIMENU_INGAME:
         /*
         //GRank
         UI_RankingsMenu();
         return;
         */
         trap_Cvar_Set( "cl_paused", "1" );
         UI_InGameMenu();
         return;
     case UIMENU_TEAM:
     case UIMENU_POSTGAME:
     default:
 #ifndef NDEBUG
       Com_Printf("UI_SetActiveMenu: bad enum %d\n", menu );
 #endif
       break;
     }
 }
UI_SetBestScore()
void UI_SetBestScore (int level, int score)
Definition at line 482 of file ui_gameinfo.c.
{
     int     skill;
     int     oldScore;
     char    arenaKey[16];
     char    scores[MAX_INFO_VALUE];
     // validate score
     if( score < 1 || score > 8 ) {
         return;
     }
     // validate skill
     skill = (int)trap_Cvar_VariableValue( "g_spSkill" );
     if( skill < 1 || skill > 5 ) {
         return;
     }
     // get scores
     trap_Cvar_VariableStringBuffer( va( "g_spScores%i", skill ), scores, MAX_INFO_VALUE );
     // see if this is better
     Com_sprintf( arenaKey, sizeof( arenaKey ), "l%i", level );
     oldScore = atoi( Info_ValueForKey( scores, arenaKey ) );
     if( oldScore && oldScore <= score ) {
         return;
     }
     // update scores
     Info_SetValueForKey( scores, arenaKey, va( "%i", score ) );
     trap_Cvar_Set( va( "g_spScores%i", skill ), scores );
 }
UI_SetColor()
void UI_SetColor (const float * rgba)
Definition at line 1187 of file ui_atoms.c.
{
     trap_R_SetColor( rgba );
 }
UI_SetupMenu()
void UI_SetupMenu (void)
Definition at line 324 of file ui_setup.c.
{
     UI_SetupMenu_Init();
     UI_PushMenu( &setupMenuInfo.menu );
 }
Referenced by InGame_Event(), Main_MenuEvent(), and Rankings_MenuEvent().
UI_SetupMenu_Cache()
void UI_SetupMenu_Cache (void)
Definition at line 311 of file ui_setup.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
Referenced by UI_Cache_f().
UI_ShowTierVideo()
qboolean UI_ShowTierVideo (int tier)
Definition at line 603 of file ui_gameinfo.c.
{
     char    key[16];
     char    videos[MAX_INFO_VALUE];
     if( tier <= 0 ) {
         return qfalse;
     }
     trap_Cvar_VariableStringBuffer( "g_spVideos", videos, sizeof(videos) );
     Com_sprintf( key, sizeof(key), "tier%i", tier );
     if( atoi( Info_ValueForKey( videos, key ) ) ) {
         return qfalse;
     }
     Info_SetValueForKey( videos, key, va( "%i", 1 ) );
     trap_Cvar_Set( "g_spVideos", videos );
     return qtrue;
 }
UI_Shutdown()
void UI_Shutdown (void)
Definition at line 1062 of file ui_atoms.c.
{
 }
UI_SignupMenu()
void UI_SignupMenu (void)
Definition at line 281 of file ui_signup.c.
{
     Signup_MenuInit();
     UI_PushMenu ( &s_signup.menu );
 }
Referenced by Rankings_MenuEvent(), and RankStatus_MenuEvent().
UI_SoundOptionsMenu()
void UI_SoundOptionsMenu (void)
Definition at line 446 of file ui_sound.c.
{
     UI_SoundOptionsMenu_Init();
     UI_PushMenu( &soundOptionsInfo.menu );
     Menu_SetCursorToItem( &soundOptionsInfo.menu, &soundOptionsInfo.sound );
 }
Referenced by GraphicsOptions_Event(), Options_Event(), UI_DisplayOptionsMenu_Event(), and UI_NetworkOptionsMenu_Event().
UI_SoundOptionsMenu_Cache()
void UI_SoundOptionsMenu_Cache (void)
Definition at line 431 of file ui_sound.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_ACCEPT0 );
     trap_R_RegisterShaderNoMip( ART_ACCEPT1 );
 }
Referenced by UI_Cache_f().
UI_SPArena_Start()
void UI_SPArena_Start (const char * arenaInfo)
Definition at line 25 of file ui_sparena.c.
{
     char    *map;
     int     level;
     int     n;
     char    *txt;
     n = (int)trap_Cvar_VariableValue( "sv_maxclients" );
     if ( n < 8 ) {
         trap_Cvar_SetValue( "sv_maxclients", 8 );
     }
     level = atoi( Info_ValueForKey( arenaInfo, "num" ) );
     txt = Info_ValueForKey( arenaInfo, "special" );
     if( txt[0] ) {
         if( Q_stricmp( txt, "training" ) == 0 ) {
             level = -4;
         }
         else if( Q_stricmp( txt, "final" ) == 0 ) {
             level = UI_GetNumSPTiers() * ARENAS_PER_TIER;
         }
     }
     trap_Cvar_SetValue( "ui_spSelection", level );
     map = Info_ValueForKey( arenaInfo, "map" );
     trap_Cmd_ExecuteText( EXEC_APPEND, va( "spmap %s\n", map ) );
 }
Referenced by UI_SPPostgameMenu_NextEvent(), and UI_SPSkillMenu_FightEvent().
UI_SpecifyLeagueMenu()
void UI_SpecifyLeagueMenu (void)
Definition at line 328 of file ui_specifyleague.c.
 {
     SpecifyLeague_MenuInit();
     UI_PushMenu( &s_specifyleague.menu );
 }
UI_SpecifyServerMenu()
void UI_SpecifyServerMenu (void)
Definition at line 208 of file ui_specifyserver.c.
 {
     SpecifyServer_MenuInit();
     UI_PushMenu( &s_specifyserver.menu );
 }
Referenced by ArenaServers_Event().
UI_SPLevelMenu()
void UI_SPLevelMenu (void)
Definition at line 946 of file ui_splevel.c.
{
     int         level;
     int         trainingLevel;
     const char  *arenaInfo;
     trainingTier = -1;
     arenaInfo = UI_GetSpecialArenaInfo( "training" );
     if( arenaInfo ) {
         minTier = trainingTier;
         trainingLevel = atoi( Info_ValueForKey( arenaInfo, "num" ) );
     }
     else {
         minTier = 0;
         trainingLevel = -2;
     }
     finalTier = UI_GetNumSPTiers();
     arenaInfo = UI_GetSpecialArenaInfo( "final" );
     if( arenaInfo ) {
         maxTier = finalTier;
     }
     else {
         maxTier = finalTier - 1;
         if( maxTier < minTier ) {
             maxTier = minTier;
         }
     }
     level = UI_GetCurrentGame();
     if ( level == -1 ) {
         level = UI_GetNumSPArenas() - 1;
         if( maxTier == finalTier ) {
             level++;
         }
     }
     if( level == trainingLevel ) {
         currentSet = -1;
         currentGame = 0;
     }
     else {
         currentSet = level / ARENAS_PER_TIER;
         currentGame = level % ARENAS_PER_TIER;
     }
     UI_SPLevelMenu_Init();
     UI_PushMenu( &levelMenuInfo.menu );
     Menu_SetCursorToItem( &levelMenuInfo.menu, &levelMenuInfo.item_next );
 }
Referenced by Main_MenuEvent(), and Reset_MenuEvent().
UI_SPLevelMenu_Cache()
void UI_SPLevelMenu_Cache (void)
Definition at line 680 of file ui_splevel.c.
{
     int             n;
     trap_R_RegisterShaderNoMip( ART_LEVELFRAME_FOCUS );
     trap_R_RegisterShaderNoMip( ART_LEVELFRAME_SELECTED );
     trap_R_RegisterShaderNoMip( ART_ARROW );
     trap_R_RegisterShaderNoMip( ART_ARROW_FOCUS );
     trap_R_RegisterShaderNoMip( ART_MAP_UNKNOWN );
     trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE1 );
     trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE2 );
     trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE3 );
     trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE4 );
     trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE5 );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FIGHT0 );
     trap_R_RegisterShaderNoMip( ART_FIGHT1 );
     trap_R_RegisterShaderNoMip( ART_RESET0 );
     trap_R_RegisterShaderNoMip( ART_RESET1 );
     trap_R_RegisterShaderNoMip( ART_CUSTOM0 );
     trap_R_RegisterShaderNoMip( ART_CUSTOM1 );
     for( n = 0; n < 6; n++ ) {
         trap_R_RegisterShaderNoMip( ui_medalPicNames[n] );
         levelMenuInfo.awardSounds[n] = trap_S_RegisterSound( ui_medalSounds[n], qfalse );
     }
     levelMenuInfo.levelSelectedPic = trap_R_RegisterShaderNoMip( ART_LEVELFRAME_SELECTED );
     levelMenuInfo.levelFocusPic = trap_R_RegisterShaderNoMip( ART_LEVELFRAME_FOCUS );
     levelMenuInfo.levelCompletePic[0] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE1 );
     levelMenuInfo.levelCompletePic[1] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE2 );
     levelMenuInfo.levelCompletePic[2] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE3 );
     levelMenuInfo.levelCompletePic[3] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE4 );
     levelMenuInfo.levelCompletePic[4] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE5 );
 }
Referenced by UI_Cache_f().
UI_SPLevelMenu_f()
void UI_SPLevelMenu_f (void)
Definition at line 1002 of file ui_splevel.c.
{
     trap_Key_SetCatcher( KEYCATCH_UI );
     uis.menusp = 0;
     UI_SPLevelMenu();
 }
Referenced by UI_ConsoleCommand().
UI_SPLevelMenu_ReInit()
void UI_SPLevelMenu_ReInit (void)
Definition at line 1014 of file ui_splevel.c.
{
     levelMenuInfo.reinit = qtrue;
 }
Referenced by UI_SPUnlock_f().
UI_SPPostgameMenu_Cache()
void UI_SPPostgameMenu_Cache (void)
Definition at line 402 of file ui_sppostgame.c.
{
     int         n;
     qboolean    buildscript;
     buildscript = trap_Cvar_VariableValue("com_buildscript");
     trap_R_RegisterShaderNoMip( ART_MENU0 );
     trap_R_RegisterShaderNoMip( ART_MENU1 );
     trap_R_RegisterShaderNoMip( ART_REPLAY0 );
     trap_R_RegisterShaderNoMip( ART_REPLAY1 );
     trap_R_RegisterShaderNoMip( ART_NEXT0 );
     trap_R_RegisterShaderNoMip( ART_NEXT1 );
     for( n = 0; n < 6; n++ ) {
         trap_R_RegisterShaderNoMip( ui_medalPicNames[n] );
         trap_S_RegisterSound( ui_medalSounds[n], qfalse );
     }
     if( buildscript ) {
         trap_S_RegisterSound( "music/loss.wav", qfalse );
         trap_S_RegisterSound( "music/win.wav", qfalse );
         trap_S_RegisterSound( "sound/player/announce/youwin.wav", qfalse );
     }
 }
Referenced by UI_Cache_f().
UI_SPPostgameMenu_f()
void UI_SPPostgameMenu_f (void)
Definition at line 503 of file ui_sppostgame.c.
{
     int         playerGameRank;
     int         playerClientNum;
     int         n;
     int         oldFrags, newFrags;
     const char  *arena;
     int         awardValues[6];
     char        map[MAX_QPATH];
     char        info[MAX_INFO_STRING];
     memset( &postgameMenuInfo, 0, sizeof(postgameMenuInfo) );
     trap_GetConfigString( CS_SYSTEMINFO, info, sizeof(info) );
     postgameMenuInfo.serverId = atoi( Info_ValueForKey( info, "sv_serverid" ) );
     trap_GetConfigString( CS_SERVERINFO, info, sizeof(info) );
     Q_strncpyz( map, Info_ValueForKey( info, "mapname" ), sizeof(map) );
     arena = UI_GetArenaInfoByMap( map );
     if ( !arena ) {
         return;
     }
     Q_strncpyz( arenainfo, arena, sizeof(arenainfo) );
     postgameMenuInfo.level = atoi( Info_ValueForKey( arenainfo, "num" ) );
     postgameMenuInfo.numClients = atoi( UI_Argv( 1 ) );
     playerClientNum = atoi( UI_Argv( 2 ) );
     playerGameRank = 8;     // in case they ended game as a spectator
     if( postgameMenuInfo.numClients > MAX_SCOREBOARD_CLIENTS ) {
         postgameMenuInfo.numClients = MAX_SCOREBOARD_CLIENTS;
     }
     for( n = 0; n < postgameMenuInfo.numClients; n++ ) {
         postgameMenuInfo.clientNums[n] = atoi( UI_Argv( 8 + n * 3 + 1 ) );
         postgameMenuInfo.ranks[n] = atoi( UI_Argv( 8 + n * 3 + 2 ) );
         postgameMenuInfo.scores[n] = atoi( UI_Argv( 8 + n * 3 + 3 ) );
         if( postgameMenuInfo.clientNums[n] == playerClientNum ) {
             playerGameRank = (postgameMenuInfo.ranks[n] & ~RANK_TIED_FLAG) + 1;
         }
     }
     UI_SetBestScore( postgameMenuInfo.level, playerGameRank );
     // process award stats and prepare presentation data
     awardValues[AWARD_ACCURACY] = atoi( UI_Argv( 3 ) );
     awardValues[AWARD_IMPRESSIVE] = atoi( UI_Argv( 4 ) );
     awardValues[AWARD_EXCELLENT] = atoi( UI_Argv( 5 ) );
     awardValues[AWARD_GAUNTLET] = atoi( UI_Argv( 6 ) );
     awardValues[AWARD_FRAGS] = atoi( UI_Argv( 7 ) );
     awardValues[AWARD_PERFECT] = atoi( UI_Argv( 8 ) );
     postgameMenuInfo.numAwards = 0;
     if( awardValues[AWARD_ACCURACY] >= 50 ) {
         UI_LogAwardData( AWARD_ACCURACY, 1 );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_ACCURACY;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_ACCURACY];
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_IMPRESSIVE] ) {
         UI_LogAwardData( AWARD_IMPRESSIVE, awardValues[AWARD_IMPRESSIVE] );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_IMPRESSIVE;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_IMPRESSIVE];
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_EXCELLENT] ) {
         UI_LogAwardData( AWARD_EXCELLENT, awardValues[AWARD_EXCELLENT] );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_EXCELLENT;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_EXCELLENT];
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_GAUNTLET] ) {
         UI_LogAwardData( AWARD_GAUNTLET, awardValues[AWARD_GAUNTLET] );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_GAUNTLET;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_GAUNTLET];
         postgameMenuInfo.numAwards++;
     }
     oldFrags = UI_GetAwardLevel( AWARD_FRAGS ) / 100;
     UI_LogAwardData( AWARD_FRAGS, awardValues[AWARD_FRAGS] );
     newFrags = UI_GetAwardLevel( AWARD_FRAGS ) / 100;
     if( newFrags > oldFrags ) {
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_FRAGS;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = newFrags * 100;
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_PERFECT] ) {
         UI_LogAwardData( AWARD_PERFECT, 1 );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_PERFECT;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = 1;
         postgameMenuInfo.numAwards++;
     }
     if ( playerGameRank == 1 ) {
         postgameMenuInfo.won = UI_TierCompleted( postgameMenuInfo.level );
     }
     else {
         postgameMenuInfo.won = -1;
     }
     postgameMenuInfo.starttime = uis.realtime;
     postgameMenuInfo.scoreboardtime = uis.realtime;
     trap_Key_SetCatcher( KEYCATCH_UI );
     uis.menusp = 0;
     UI_SPPostgameMenu_Init();
     UI_PushMenu( &postgameMenuInfo.menu );
     if ( playerGameRank == 1 ) {
         Menu_SetCursorToItem( &postgameMenuInfo.menu, &postgameMenuInfo.item_next );
     }
     else {
         Menu_SetCursorToItem( &postgameMenuInfo.menu, &postgameMenuInfo.item_again );
     }
     Prepname( 0 );
     Prepname( 1 );
     Prepname( 2 );
     if ( playerGameRank != 1 ) {
         postgameMenuInfo.winnerSound = trap_S_RegisterSound( va( "sound/player/announce/%s_wins.wav", postgameMenuInfo.placeNames[0] ), qfalse );
         trap_Cmd_ExecuteText( EXEC_APPEND, "music music/loss\n" );
     }
     else {
         postgameMenuInfo.winnerSound = trap_S_RegisterSound( "sound/player/announce/youwin.wav", qfalse );
         trap_Cmd_ExecuteText( EXEC_APPEND, "music music/win\n" );
     }
     postgameMenuInfo.phase = 1;
     postgameMenuInfo.lastTier = UI_GetNumSPTiers();
     if ( UI_GetSpecialArenaInfo( "final" ) ) {
         postgameMenuInfo.lastTier++;
     }
 }
Referenced by UI_ConsoleCommand().
UI_SPSkillMenu()
void UI_SPSkillMenu (const char * arenaInfo)
Definition at line 324 of file ui_spskill.c.
{
     UI_SPSkillMenu_Init();
     skillMenuInfo.arenaInfo = arenaInfo;
     UI_PushMenu( &skillMenuInfo.menu );
     Menu_SetCursorToItem( &skillMenuInfo.menu, &skillMenuInfo.item_fight );
 }
Referenced by UI_SPLevelMenu_NextEvent().
UI_SPSkillMenu_Cache()
void UI_SPSkillMenu_Cache (void)
Definition at line 178 of file ui_spskill.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAME );
     trap_R_RegisterShaderNoMip( ART_BACK );
     trap_R_RegisterShaderNoMip( ART_BACK_FOCUS );
     trap_R_RegisterShaderNoMip( ART_FIGHT );
     trap_R_RegisterShaderNoMip( ART_FIGHT_FOCUS );
     skillMenuInfo.skillpics[0] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE1 );
     skillMenuInfo.skillpics[1] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE2 );
     skillMenuInfo.skillpics[2] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE3 );
     skillMenuInfo.skillpics[3] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE4 );
     skillMenuInfo.skillpics[4] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE5 );
     skillMenuInfo.nightmareSound = trap_S_RegisterSound( "sound/misc/nightmare.wav", qfalse );
     skillMenuInfo.silenceSound = trap_S_RegisterSound( "sound/misc/silence.wav", qfalse );
 }
Referenced by UI_Cache_f().
UI_SPUnlock_f()
void UI_SPUnlock_f (void)
Definition at line 753 of file ui_gameinfo.c.
{
     char    arenaKey[16];
     char    scores[MAX_INFO_VALUE];
     int     level;
     int     tier;
     // get scores for skill 1
     trap_Cvar_VariableStringBuffer( "g_spScores1", scores, MAX_INFO_VALUE );
     // update scores
     for( level = 0; level < ui_numSinglePlayerArenas + ui_numSpecialSinglePlayerArenas; level++ ) {
         Com_sprintf( arenaKey, sizeof( arenaKey ), "l%i", level );
         Info_SetValueForKey( scores, arenaKey, "1" );
     }
     trap_Cvar_Set( "g_spScores1", scores );
     // unlock cinematics
     for( tier = 1; tier <= 8; tier++ ) {
         UI_ShowTierVideo( tier );
     }
     trap_Print( "All levels unlocked at skill level 1\n" );
     UI_SPLevelMenu_ReInit();
 }
UI_SPUnlockMedals_f()
void UI_SPUnlockMedals_f (void)
Definition at line 785 of file ui_gameinfo.c.
{
     int     n;
     char    key[16];
     char    awardData[MAX_INFO_VALUE];
     trap_Cvar_VariableStringBuffer( "g_spAwards", awardData, MAX_INFO_VALUE );
     for( n = 0; n < 6; n++ ) {
         Com_sprintf( key, sizeof(key), "a%i", n );
         Info_SetValueForKey( awardData, key, "100" );
     }
     trap_Cvar_Set( "g_spAwards", awardData );
     trap_Print( "All awards unlocked at 100\n" );
 }
UI_StartDemoLoop()
void UI_StartDemoLoop (void)
Definition at line 72 of file ui_atoms.c.
{
     trap_Cmd_ExecuteText( EXEC_APPEND, "d1\n" );
 }
UI_StartServerMenu()
void UI_StartServerMenu (qboolean multiplayer)
Definition at line 600 of file ui_startserver.c.
{
     StartServer_MenuInit();
     s_startserver.multiplayer = multiplayer;
     UI_PushMenu( &s_startserver.menu );
 }
Referenced by ArenaServers_Event(), and UI_SPLevelMenu_CustomEvent().
UI_TeamMainMenu()
void UI_TeamMainMenu (void)
Definition at line 196 of file ui_team.c.
{
     TeamMain_MenuInit();
     UI_PushMenu ( &s_teammain.menu );
 }
Referenced by InGame_Event().
UI_TeamOrdersMenu()
void UI_TeamOrdersMenu (void)
Definition at line 417 of file ui_teamorders.c.
{
     UI_TeamOrdersMenu_Init();
     UI_PushMenu( &teamOrdersMenuInfo.menu );
 }
Referenced by InGame_Event().
UI_TeamOrdersMenu_Cache()
void UI_TeamOrdersMenu_Cache (void)
Definition at line 405 of file ui_teamorders.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAME );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
 }
UI_TeamOrdersMenu_f()
void UI_TeamOrdersMenu_f (void)
Definition at line 428 of file ui_teamorders.c.
{
     uiClientState_t cs;
     char    info[MAX_INFO_STRING];
     int     team;
     // make sure it's a team game
     trap_GetConfigString( CS_SERVERINFO, info, sizeof(info) );
     teamOrdersMenuInfo.gametype = atoi( Info_ValueForKey( info, "g_gametype" ) );
     if( teamOrdersMenuInfo.gametype < GT_TEAM ) {
         return;
     }
     // not available to spectators
     trap_GetClientState( &cs );
     trap_GetConfigString( CS_PLAYERS + cs.clientNum, info, MAX_INFO_STRING );
     team = atoi( Info_ValueForKey( info, "t" ) );
     if( team == TEAM_SPECTATOR ) {
         return;
     }
     UI_TeamOrdersMenu();
 }
Referenced by UI_ConsoleCommand().
UI_TierCompleted()
int UI_TierCompleted (int levelWon)
Definition at line 565 of file ui_gameinfo.c.
{
     int         level;
     int         n;
     int         tier;
     int         score;
     int         skill;
     const char  *info;
     tier = levelWon / ARENAS_PER_TIER;
     level = tier * ARENAS_PER_TIER;
     if( tier == UI_GetNumSPTiers() ) {
         info = UI_GetSpecialArenaInfo( "training" );
         if( levelWon == atoi( Info_ValueForKey( info, "num" ) ) ) {
             return 0;
         }
         info = UI_GetSpecialArenaInfo( "final" );
         if( !info || levelWon == atoi( Info_ValueForKey( info, "num" ) ) ) {
             return tier + 1;
         }
         return -1;
     }
     for( n = 0; n < ARENAS_PER_TIER; n++, level++ ) {
         UI_GetBestScore( level, &score, &skill );
         if ( score != 1 ) {
             return -1;
         }
     }
     return tier + 1;
 }
UI_UpdateCvars()
void UI_UpdateCvars (void)
Definition at line 243 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         if ( !cv->vmCvar ) {
             continue;
         }
         trap_Cvar_Update( cv->vmCvar );
     }
 }
Referenced by UI_Refresh().
UI_UpdateScreen()
void UI_UpdateScreen (void)
Definition at line 1191 of file ui_atoms.c.
{
     trap_UpdateScreen();
 }
Variable Documentation
color_black
vec4_t color_black
Definition at line 43 of file ui_qmenu.c.
Referenced by UI_SPLevelMenu_MenuDraw().
color_blue
vec4_t color_blue
Definition at line 46 of file ui_qmenu.c.
color_dim
vec4_t color_dim
Definition at line 50 of file ui_qmenu.c.
color_orange
vec4_t color_orange
Definition at line 48 of file ui_qmenu.c.
Referenced by ServerOptions_LevelshotDraw(), ServerOptions_MenuInit(), StartServer_LevelshotDraw(), UI_AddBotsMenu_BotEvent(), UI_AddBotsMenu_Init(), UI_BotSelectMenu_Init(), UI_BotSelectMenu_UpdateGrid(), UI_CDKeyMenu_DrawKey(), UI_RemoveBotsMenu_BotEvent(), UI_RemoveBotsMenu_Init(), UI_SaveConfigMenu_SavenameDraw(), UI_SPLevelMenu_MenuDraw(), and UI_TeamOrdersMenu_ListDraw().
color_red
vec4_t color_red
Definition at line 49 of file ui_qmenu.c.
Referenced by ConfirmMenu_Draw(), Controls_MenuInit(), DriverInfo_MenuDraw(), GraphicsOptions_MenuInit(), InGame_MenuInit(), MessageMenu_Draw(), Options_MenuInit(), PlayerModel_DrawPlayer(), Reset_MenuDraw(), ServerInfo_MenuDraw(), UI_BotSelectMenu_UpdateGrid(), UI_CDKeyMenu_DrawKey(), UI_CinematicsMenu_Init(), UI_ConfirmMenu_Style(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DisplayOptionsMenu_Init(), UI_MainMenu(), UI_Message(), UI_NetworkOptionsMenu_Init(), UI_ResetMenu(), UI_ServerInfoMenu(), UI_SetupMenu_Init(), UI_SoundOptionsMenu_Init(), UI_SPLevelMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPSkillMenu_Init(), and UI_SPSkillMenu_SkillEvent().
color_white
vec4_t color_white
Definition at line 44 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), Demos_MenuInit(), GraphicsOptions_MenuInit(), LoadConfig_MenuInit(), Options_MenuInit(), PlayerModel_MenuInit(), PlayerSettings_DrawName(), PlayerSettings_MenuInit(), Preferences_MenuInit(), Rankings_DrawText(), ServerOptions_MenuInit(), SpecifyLeague_MenuInit(), SpecifyServer_MenuInit(), StartServer_MenuInit(), UI_AddBotsMenu_BotEvent(), UI_AddBotsMenu_Init(), UI_BotSelectMenu_Init(), UI_CDKeyMenu_DrawKey(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Init(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DisplayDownloadInfo(), UI_DisplayOptionsMenu_Init(), UI_DrawConnectScreen(), UI_DriverInfo_Menu(), UI_Mods_MenuInit(), UI_NetworkOptionsMenu_Init(), UI_RemoveBotsMenu_BotEvent(), UI_RemoveBotsMenu_Init(), UI_SaveConfigMenu_Init(), UI_ServerInfoMenu(), UI_SetupMenu_Init(), UI_SoundOptionsMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_SPSkillMenu_Init(), UI_SPSkillMenu_SkillEvent(), and UI_TeamOrdersMenu_Init().
color_yellow
vec4_t color_yellow
Definition at line 45 of file ui_qmenu.c.
Referenced by Controls_ResetDefaults_Draw(), Reset_MenuDraw(), Setup_ResetDefaults_Draw(), UI_CDKeyMenu_DrawKey(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_ResetDraw(), UI_SPPostgameMenu_DrawAwardsMedals(), and UI_TeamOrdersMenu_ListDraw().
list_color
vec4_t list_color
listbar_color
vec4_t listbar_color
Definition at line 57 of file ui_qmenu.c.
Referenced by Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PlayerName_Draw(), and UI_CDKeyMenu_DrawKey().
m_entersound
qboolean m_entersound
Definition at line 31 of file ui_atoms.c.
menu_black_color
vec4_t menu_black_color
menu_buzz_sound
sfxHandle_t menu_buzz_sound
Definition at line 33 of file ui_qmenu.c.
Referenced by MenuField_Key(), and PlayerModel_MenuKey().
menu_dark_color
vec4_t menu_dark_color
menu_dim_color
vec4_t menu_dim_color
Definition at line 42 of file ui_qmenu.c.
menu_grayed_color
vec4_t menu_grayed_color
menu_highlight_color
vec4_t menu_highlight_color
menu_in_sound
sfxHandle_t menu_in_sound
Definition at line 30 of file ui_qmenu.c.
Referenced by UI_Refresh().
menu_move_sound
sfxHandle_t menu_move_sound
Definition at line 31 of file ui_qmenu.c.
Referenced by ArenaServers_MenuKey(), PlayerModel_MenuKey(), UI_MouseEvent(), and UI_TeamOrdersMenu_Key().
menu_null_sound
sfxHandle_t menu_null_sound
Definition at line 34 of file ui_qmenu.c.
Referenced by ErrorMessage_Key(), UI_KeyEvent(), and UI_TeamOrdersMenu_Key().
menu_out_sound
sfxHandle_t menu_out_sound
Definition at line 32 of file ui_qmenu.c.
Referenced by Controls_MenuKey(), and UI_PopMenu().
menu_red_color
vec4_t menu_red_color
menu_text_color
vec4_t menu_text_color
Definition at line 41 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Main_MenuDraw(), and UI_DrawConnectScreen().
name_color
vec4_t name_color
text_color_disabled
vec4_t text_color_disabled
Definition at line 54 of file ui_qmenu.c.
Referenced by Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), and PlayerName_Draw().
text_color_highlight
vec4_t text_color_highlight
Definition at line 56 of file ui_qmenu.c.
Referenced by Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PlayerName_Draw(), PlayerSettings_DrawEffects(), PlayerSettings_DrawHandicap(), PlayerSettings_DrawName(), Rankings_DrawText(), and UI_SaveConfigMenu_SavenameDraw().
text_color_normal
vec4_t text_color_normal
Definition at line 55 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), Crosshair_Draw(), DriverInfo_MenuDraw(), MenuField_Draw(), PlayerModel_MenuInit(), PlayerName_Draw(), PlayerSettings_DrawEffects(), PlayerSettings_DrawHandicap(), PlayerSettings_DrawName(), Rankings_DrawText(), ServerInfo_MenuDraw(), and StartServer_MenuInit().
ui_arenasFile
vmCvar_t ui_arenasFile
Definition at line 116 of file ui_main.c.
ui_botsFile
vmCvar_t ui_botsFile
Definition at line 117 of file ui_main.c.
ui_brassTime
vmCvar_t ui_brassTime
Definition at line 135 of file ui_main.c.
ui_browserGameType
vmCvar_t ui_browserGameType
Definition at line 130 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserMaster
vmCvar_t ui_browserMaster
Definition at line 129 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserShowEmpty
vmCvar_t ui_browserShowEmpty
Definition at line 133 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserShowFull
vmCvar_t ui_browserShowFull
Definition at line 132 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_browserSortKey
vmCvar_t ui_browserSortKey
Definition at line 131 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_cdkey
vmCvar_t ui_cdkey
ui_cdkeychecked
vmCvar_t ui_cdkeychecked
Definition at line 157 of file ui_main.c.
Referenced by UI_MainMenu().
ui_ctf_capturelimit
vmCvar_t ui_ctf_capturelimit
Definition at line 112 of file ui_main.c.
ui_ctf_friendly
vmCvar_t ui_ctf_friendly
Definition at line 114 of file ui_main.c.
ui_ctf_timelimit
vmCvar_t ui_ctf_timelimit
Definition at line 113 of file ui_main.c.
ui_drawCrosshair
vmCvar_t ui_drawCrosshair
Definition at line 136 of file ui_main.c.
ui_drawCrosshairNames
vmCvar_t ui_drawCrosshairNames
Definition at line 137 of file ui_main.c.
ui_ffa_fraglimit
vmCvar_t ui_ffa_fraglimit
Definition at line 102 of file ui_main.c.
ui_ffa_timelimit
vmCvar_t ui_ffa_timelimit
Definition at line 103 of file ui_main.c.
ui_ioq3
vmCvar_t ui_ioq3
Definition at line 158 of file ui_main.c.
ui_marks
vmCvar_t ui_marks
Definition at line 138 of file ui_main.c.
ui_medalNames
char* ui_medalNames[]
Definition at line 80 of file ui_sppostgame.c.
ui_medalPicNames
char* ui_medalPicNames[]
Definition at line 81 of file ui_sppostgame.c.
Referenced by UI_SPLevelMenu_Cache(), and UI_SPLevelMenu_Init().
ui_medalSounds
char* ui_medalSounds[]
Definition at line 89 of file ui_sppostgame.c.
Referenced by UI_SPLevelMenu_Cache().
ui_server1
vmCvar_t ui_server1
Definition at line 140 of file ui_main.c.
ui_server10
vmCvar_t ui_server10
Definition at line 149 of file ui_main.c.
ui_server11
vmCvar_t ui_server11
Definition at line 150 of file ui_main.c.
ui_server12
vmCvar_t ui_server12
Definition at line 151 of file ui_main.c.
ui_server13
vmCvar_t ui_server13
Definition at line 152 of file ui_main.c.
ui_server14
vmCvar_t ui_server14
Definition at line 153 of file ui_main.c.
ui_server15
vmCvar_t ui_server15
Definition at line 154 of file ui_main.c.
ui_server16
vmCvar_t ui_server16
Definition at line 155 of file ui_main.c.
ui_server2
vmCvar_t ui_server2
Definition at line 141 of file ui_main.c.
ui_server3
vmCvar_t ui_server3
Definition at line 142 of file ui_main.c.
ui_server4
vmCvar_t ui_server4
Definition at line 143 of file ui_main.c.
ui_server5
vmCvar_t ui_server5
Definition at line 144 of file ui_main.c.
ui_server6
vmCvar_t ui_server6
Definition at line 145 of file ui_main.c.
ui_server7
vmCvar_t ui_server7
Definition at line 146 of file ui_main.c.
ui_server8
vmCvar_t ui_server8
Definition at line 147 of file ui_main.c.
ui_server9
vmCvar_t ui_server9
Definition at line 148 of file ui_main.c.
ui_spAwards
vmCvar_t ui_spAwards
Definition at line 123 of file ui_main.c.
ui_spScores1
vmCvar_t ui_spScores1
Definition at line 118 of file ui_main.c.
ui_spScores2
vmCvar_t ui_spScores2
Definition at line 119 of file ui_main.c.
ui_spScores3
vmCvar_t ui_spScores3
Definition at line 120 of file ui_main.c.
ui_spScores4
vmCvar_t ui_spScores4
Definition at line 121 of file ui_main.c.
ui_spScores5
vmCvar_t ui_spScores5
Definition at line 122 of file ui_main.c.
ui_spSelection
vmCvar_t ui_spSelection
Definition at line 127 of file ui_main.c.
ui_spSkill
vmCvar_t ui_spSkill
Definition at line 125 of file ui_main.c.
ui_spVideos
vmCvar_t ui_spVideos
Definition at line 124 of file ui_main.c.
ui_team_fraglimit
vmCvar_t ui_team_fraglimit
Definition at line 108 of file ui_main.c.
ui_team_friendly
vmCvar_t ui_team_friendly
Definition at line 110 of file ui_main.c.
ui_team_timelimit
vmCvar_t ui_team_timelimit
Definition at line 109 of file ui_main.c.
ui_tourney_fraglimit
vmCvar_t ui_tourney_fraglimit
Definition at line 105 of file ui_main.c.
ui_tourney_timelimit
vmCvar_t ui_tourney_timelimit
Definition at line 106 of file ui_main.c.
uis
uiStatic_t uis
Definition at line 30 of file ui_atoms.c.
weaponChangeSound
sfxHandle_t weaponChangeSound
Definition at line 35 of file ui_qmenu.c.