ioquake3 doxygen: C:/entry/dev/ioquake3/code/qcommon/json.h File Reference
json.h File Reference
#include <stdio.h>
Enumerations
enum {
JSONTYPE_STRING, JSONTYPE_OBJECT, JSONTYPE_ARRAY, JSONTYPE_VALUE,
JSONTYPE_ERROR
}
Functions
const char * JSON_ArrayGetFirstValue (const char *json, const char *jsonEnd)
const char * JSON_ArrayGetNextValue (const char *json, const char *jsonEnd)
unsigned int JSON_ArrayGetIndex (const char *json, const char *jsonEnd, const char **indexes, unsigned int numIndexes)
const char * JSON_ArrayGetValue (const char *json, const char *jsonEnd, unsigned int index)
const char * JSON_ObjectGetNamedValue (const char *json, const char *jsonEnd, const char *name)
unsigned int JSON_ValueGetType (const char *json, const char *jsonEnd)
unsigned int JSON_ValueGetString (const char *json, const char *jsonEnd, char *outString, unsigned int stringLen)
double JSON_ValueGetDouble (const char *json, const char *jsonEnd)
float JSON_ValueGetFloat (const char *json, const char *jsonEnd)
int JSON_ValueGetInt (const char *json, const char *jsonEnd)
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
JSONTYPE_STRING
JSONTYPE_OBJECT
JSONTYPE_ARRAY
JSONTYPE_VALUE
JSONTYPE_ERROR
Definition at line 24 of file json.h.
 {
     JSONTYPE_STRING, // string
     JSONTYPE_OBJECT, // object
     JSONTYPE_ARRAY,  // array
     JSONTYPE_VALUE,  // number, true, false, or null
     JSONTYPE_ERROR   // out of data
 };
Function Documentation
JSON_ArrayGetFirstValue()
const char* JSON_ArrayGetFirstValue (const char * json, const char * jsonEnd)
JSON_ArrayGetIndex()
unsigned int JSON_ArrayGetIndex (const char * json, const char * jsonEnd, const char ** indexes, unsigned int numIndexes)
Referenced by R_LoadEnvironmentJson().
JSON_ArrayGetNextValue()
const char* JSON_ArrayGetNextValue (const char * json, const char * jsonEnd)
JSON_ArrayGetValue()
const char* JSON_ArrayGetValue (const char * json, const char * jsonEnd, unsigned int index)
Referenced by R_LoadEnvironmentJson().
JSON_ObjectGetNamedValue()
const char* JSON_ObjectGetNamedValue (const char * json, const char * jsonEnd, const char * name)
Referenced by R_LoadEnvironmentJson().
JSON_ValueGetDouble()
double JSON_ValueGetDouble (const char * json, const char * jsonEnd)
JSON_ValueGetFloat()
float JSON_ValueGetFloat (const char * json, const char * jsonEnd)
Referenced by R_LoadEnvironmentJson().
JSON_ValueGetInt()
int JSON_ValueGetInt (const char * json, const char * jsonEnd)
JSON_ValueGetString()
unsigned int JSON_ValueGetString (const char * json, const char * jsonEnd, char * outString, unsigned int stringLen)
Referenced by R_LoadEnvironmentJson().
JSON_ValueGetType()
unsigned int JSON_ValueGetType (const char * json, const char * jsonEnd)
Referenced by R_LoadEnvironmentJson().