ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_team.c File Reference
g_team.c File Reference
#include "g_local.h"
Classes
struct teamgame_s
Team-based game.
Macros
#define MAX_TEAM_SPAWN_POINTS 32
Typedefs
typedef struct teamgame_s teamgame_t
Team-based game.
Functions
void Team_SetFlagStatus (int team, flagStatus_t status)
void Team_InitGame (void)
Initialize the team-based game.
int OtherTeam (int team)
const char * TeamName (int team)
const char * TeamColorString (int team)
static __attribute__ ((format(printf, 2, 3)))
void AddTeamScore (vec3_t origin, int team, int score)
qboolean OnSameTeam (gentity_t *ent1, gentity_t *ent2)
void Team_CheckDroppedItem (gentity_t *dropped)
void Team_ForceGesture (int team)
void Team_FragBonuses (gentity_t *targ, gentity_t *inflictor, gentity_t *attacker)
void Team_CheckHurtCarrier (gentity_t *targ, gentity_t *attacker)
gentity_t * Team_ResetFlag (int team)
void Team_ResetFlags (void)
void Team_ReturnFlagSound (gentity_t *ent, int team)
void Team_TakeFlagSound (gentity_t *ent, int team)
void Team_CaptureFlagSound (gentity_t *ent, int team)
void Team_ReturnFlag (int team)
void Team_FreeEntity (gentity_t *ent)
void Team_DroppedFlagThink (gentity_t *ent)
int Team_TouchOurFlag (gentity_t *ent, gentity_t *other, int team)
int Team_TouchEnemyFlag (gentity_t *ent, gentity_t *other, int team)
int Pickup_Team (gentity_t *ent, gentity_t *other)
gentity_t * Team_GetLocation (gentity_t *ent)
qboolean Team_GetLocationMsg (gentity_t *ent, char *loc, int loclen)
gentity_t * SelectRandomTeamSpawnPoint (int teamstate, team_t team)
gentity_t * SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, qboolean isbot)
static int QDECL SortClients (const void *a, const void *b)
void TeamplayInfoMessage (gentity_t *ent)
void CheckTeamStatus (void)
void SP_team_CTF_redplayer (gentity_t *ent)
void SP_team_CTF_blueplayer (gentity_t *ent)
void SP_team_CTF_redspawn (gentity_t *ent)
void SP_team_CTF_bluespawn (gentity_t *ent)
Variables
teamgame_t teamgame
gentity_t * neutralObelisk
static char ctfFlagStatusRemap [] = { '0', '1', '*', '*', '2' }
static char oneFlagStatusRemap [] = { '0', '1', '2', '3', '4' }
Macro Definition Documentation
MAX_TEAM_SPAWN_POINTS
#define MAX_TEAM_SPAWN_POINTS 32
Definition at line 972 of file g_team.c.
Typedef Documentation
teamgame_t
typedef struct teamgame_s teamgame_t
Team-based game.
Function Documentation
__attribute__()
static __attribute__ ((format(printf, 2, 3))) static
Definition at line 104 of file g_team.c.
 {
     char        msg[1024];
     va_list        argptr;
     char* p;
     va_start(argptr, fmt);
     if (Q_vsnprintf(msg, sizeof(msg), fmt, argptr) >= sizeof(msg)) {
         G_Error("PrintMsg overrun");
     }
     va_end(argptr);
     // double quotes are bad
     while ((p = strchr(msg, '"')) != NULL)
         *p = '\'';
     trap_SendServerCommand(((ent == NULL) ? -1 : ent - g_entities), va("print \"%s\"", msg));
 }
AddTeamScore()
void AddTeamScore (vec3_t origin, int team, int score)
Definition at line 131 of file g_team.c.
 {
     gentity_t* te;
     te = G_TempEntity(origin, EV_GLOBAL_TEAM_SOUND);
     te->r.svFlags |= SVF_BROADCAST;
     if (team == TEAM_RED) {
         if (level.teamScores[TEAM_RED] + score == level.teamScores[TEAM_BLUE]) {
             //teams are tied sound
             te->s.eventParm = GTS_TEAMS_ARE_TIED;
         } else if (level.teamScores[TEAM_RED] <= level.teamScores[TEAM_BLUE] &&
             level.teamScores[TEAM_RED] + score > level.teamScores[TEAM_BLUE]) {
             // red took the lead sound
             te->s.eventParm = GTS_REDTEAM_TOOK_LEAD;
         } else {
             // red scored sound
             te->s.eventParm = GTS_REDTEAM_SCORED;
         }
     } else {
         if (level.teamScores[TEAM_BLUE] + score == level.teamScores[TEAM_RED]) {
             //teams are tied sound
             te->s.eventParm = GTS_TEAMS_ARE_TIED;
         } else if (level.teamScores[TEAM_BLUE] <= level.teamScores[TEAM_RED] &&
             level.teamScores[TEAM_BLUE] + score > level.teamScores[TEAM_RED]) {
             // blue took the lead sound
             te->s.eventParm = GTS_BLUETEAM_TOOK_LEAD;
         } else {
             // blue scored sound
             te->s.eventParm = GTS_BLUETEAM_SCORED;
         }
     }
     level.teamScores[team] += score;
 }
Referenced by Team_TouchOurFlag().
CheckTeamStatus()
void CheckTeamStatus (void)
Definition at line 1131 of file g_team.c.
 {
     int i;
     gentity_t* loc, * ent;
     if (level.time - level.lastTeamLocationTime > TEAM_LOCATION_UPDATE_TIME) {
         level.lastTeamLocationTime = level.time;
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->client->pers.connected != CON_CONNECTED) {
                 continue;
             }
             if (ent->inuse && (ent->client->sess.sessionTeam == TEAM_RED || ent->client->sess.sessionTeam == TEAM_BLUE)) {
                 loc = Team_GetLocation(ent);
                 if (loc)
                     ent->client->pers.teamState.location = loc->health;
                 else
                     ent->client->pers.teamState.location = 0;
             }
         }
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->client->pers.connected != CON_CONNECTED) {
                 continue;
             }
             if (ent->inuse) {
                 TeamplayInfoMessage(ent);
             }
         }
     }
 }
Referenced by G_RunFrame().
OnSameTeam()
qboolean OnSameTeam (gentity_t * ent1, gentity_t * ent2)
Definition at line 171 of file g_team.c.
 {
     if (!ent1->client || !ent2->client) {
         return qfalse;
     }
     if (g_gametype.integer < GT_TEAM) {
         return qfalse;
     }
     if (ent1->client->sess.sessionTeam == ent2->client->sess.sessionTeam) {
         return qtrue;
     }
     return qfalse;
 }
Referenced by G_Damage(), G_RankDamage(), G_SayTo(), LogAccuracyHit(), player_die(), and Team_FragBonuses().
OtherTeam()
int OtherTeam (int team)
Definition at line 72 of file g_team.c.
 {
     if (team == TEAM_RED)
         return TEAM_BLUE;
     else if (team == TEAM_BLUE)
         return TEAM_RED;
     return team;
 }
Referenced by Team_FragBonuses(), and Team_TouchOurFlag().
Pickup_Team()
int Pickup_Team (gentity_t * ent, gentity_t * other)
Definition at line 841 of file g_team.c.
 {
     int team;
     gclient_t* cl = other->client;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_OBELISK) {
         // there are no team items that can be picked up in obelisk
         G_FreeEntity(ent);
         return 0;
     }
     if (g_gametype.integer == GT_HARVESTER) {
         // the only team items that can be picked up in harvester are the cubes
         if (ent->spawnflags != cl->sess.sessionTeam) {
             cl->ps.generic1 += 1;
         }
         G_FreeEntity(ent);
         return 0;
     }
 #endif
     // figure out what team this flag is
     if (strcmp(ent->classname, "team_CTF_redflag") == 0) {
         team = TEAM_RED;
     } else if (strcmp(ent->classname, "team_CTF_blueflag") == 0) {
         team = TEAM_BLUE;
     }
 #ifdef MISSIONPACK
     else if (strcmp(ent->classname, "team_CTF_neutralflag") == 0) {
         team = TEAM_FREE;
     }
 #endif
     else {
         PrintMsg(other, "Don't know what team the flag is on.\n");
         return 0;
     }
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         if (team == TEAM_FREE) {
             return Team_TouchEnemyFlag(ent, other, cl->sess.sessionTeam);
         }
         if (team != cl->sess.sessionTeam) {
             return Team_TouchOurFlag(ent, other, cl->sess.sessionTeam);
         }
         return 0;
     }
 #endif
     // GT_CTF
     if (team == cl->sess.sessionTeam) {
         return Team_TouchOurFlag(ent, other, team);
     }
     return Team_TouchEnemyFlag(ent, other, team);
 }
Referenced by Touch_Item().
SelectCTFSpawnPoint()
gentity_t* SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, qboolean isbot)
Definition at line 1024 of file g_team.c.
 {
     gentity_t* spot;
     spot = SelectRandomTeamSpawnPoint(teamstate, team);
     if (!spot) {
         return SelectSpawnPoint(vec3_origin, origin, angles, isbot);
     }
     VectorCopy(spot->s.origin, origin);
     origin[2] += 9;
     VectorCopy(spot->s.angles, angles);
     return spot;
 }
Referenced by ClientSpawn().
SelectRandomTeamSpawnPoint()
gentity_t* SelectRandomTeamSpawnPoint (int teamstate, team_t team)
Definition at line 973 of file g_team.c.
 {
     gentity_t* spot;
     int            count;
     int            selection;
     gentity_t* spots[MAX_TEAM_SPAWN_POINTS];
     char* classname;
     if (teamstate == TEAM_BEGIN) {
         if (team == TEAM_RED)
             classname = "team_CTF_redplayer";
         else if (team == TEAM_BLUE)
             classname = "team_CTF_blueplayer";
         else
             return NULL;
     } else {
         if (team == TEAM_RED)
             classname = "team_CTF_redspawn";
         else if (team == TEAM_BLUE)
             classname = "team_CTF_bluespawn";
         else
             return NULL;
     }
     count = 0;
     spot = NULL;
     while ((spot = G_Find(spot, FOFS(classname), classname)) != NULL) {
         if (SpotWouldTelefrag(spot)) {
             continue;
         }
         spots[count] = spot;
         if (++count == MAX_TEAM_SPAWN_POINTS)
             break;
     }
     if (!count) {    // no spots that won't telefrag
         return G_Find(NULL, FOFS(classname), classname);
     }
     selection = rand() % count;
     return spots[selection];
 }
Referenced by SelectCTFSpawnPoint().
SortClients()
static int QDECL SortClients (const void * a, const void * b) static
Definition at line 1043 of file g_team.c.
 {
     return *(int*)a - *(int*)b;
 }
Referenced by TeamplayInfoMessage().
SP_team_CTF_blueplayer()
void SP_team_CTF_blueplayer (gentity_t * ent)
Definition at line 1183 of file g_team.c.
 {
 }
SP_team_CTF_bluespawn()
void SP_team_CTF_bluespawn (gentity_t * ent)
Definition at line 1200 of file g_team.c.
 {
 }
SP_team_CTF_redplayer()
void SP_team_CTF_redplayer (gentity_t * ent)
Definition at line 1175 of file g_team.c.
 {
 }
SP_team_CTF_redspawn()
void SP_team_CTF_redspawn (gentity_t * ent)
Definition at line 1192 of file g_team.c.
 {
 }
Team_CaptureFlagSound()
void Team_CaptureFlagSound (gentity_t * ent, int team)
Definition at line 618 of file g_team.c.
 {
     gentity_t* te;
     if (ent == NULL) {
         G_Printf("Warning:  NULL passed to Team_CaptureFlagSound\n");
         return;
     }
     te = G_TempEntity(ent->s.pos.trBase, EV_GLOBAL_TEAM_SOUND);
     if (team == TEAM_BLUE) {
         te->s.eventParm = GTS_BLUE_CAPTURE;
     } else {
         te->s.eventParm = GTS_RED_CAPTURE;
     }
     te->r.svFlags |= SVF_BROADCAST;
 }
Referenced by Team_TouchOurFlag().
Team_CheckDroppedItem()
void Team_CheckDroppedItem (gentity_t * dropped)
Definition at line 235 of file g_team.c.
 {
     if (dropped->item->giTag == PW_REDFLAG) {
         Team_SetFlagStatus(TEAM_RED, FLAG_DROPPED);
     } else if (dropped->item->giTag == PW_BLUEFLAG) {
         Team_SetFlagStatus(TEAM_BLUE, FLAG_DROPPED);
     } else if (dropped->item->giTag == PW_NEUTRALFLAG) {
         Team_SetFlagStatus(TEAM_FREE, FLAG_DROPPED);
     }
 }
Referenced by LaunchItem().
Team_CheckHurtCarrier()
void Team_CheckHurtCarrier (gentity_t * targ, gentity_t * attacker)
Definition at line 485 of file g_team.c.
 {
     int flag_pw;
     if (!targ->client || !attacker->client)
         return;
     if (targ->client->sess.sessionTeam == TEAM_RED)
         flag_pw = PW_BLUEFLAG;
     else
         flag_pw = PW_REDFLAG;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         flag_pw = PW_NEUTRALFLAG;
     }
 #endif
     // flags
     if (targ->client->ps.powerups[flag_pw] &&
         targ->client->sess.sessionTeam != attacker->client->sess.sessionTeam)
         attacker->client->pers.teamState.lasthurtcarrier = level.time;
     // skulls
     if (targ->client->ps.generic1 &&
         targ->client->sess.sessionTeam != attacker->client->sess.sessionTeam)
         attacker->client->pers.teamState.lasthurtcarrier = level.time;
 }
Referenced by G_Damage().
Team_DroppedFlagThink()
void Team_DroppedFlagThink (gentity_t * ent)
Definition at line 666 of file g_team.c.
 {
     int        team = TEAM_FREE;
     if (ent->item->giTag == PW_REDFLAG) {
         team = TEAM_RED;
     } else if (ent->item->giTag == PW_BLUEFLAG) {
         team = TEAM_BLUE;
     } else if (ent->item->giTag == PW_NEUTRALFLAG) {
         team = TEAM_FREE;
     }
     Team_ReturnFlagSound(Team_ResetFlag(team), team);
     // Reset Flag will delete this entity
 }
Referenced by Blocked_Door(), and LaunchItem().
Team_ForceGesture()
void Team_ForceGesture (int team)
Definition at line 251 of file g_team.c.
 {
     int i;
     gentity_t* ent;
     for (i = 0; i < MAX_CLIENTS; i++) {
         ent = &g_entities[i];
         if (!ent->inuse)
             continue;
         if (!ent->client)
             continue;
         if (ent->client->sess.sessionTeam != team)
             continue;
         //
         ent->flags |= FL_FORCE_GESTURE;
     }
 }
Referenced by Team_TouchOurFlag().
Team_FragBonuses()
void Team_FragBonuses (gentity_t * targ, gentity_t * inflictor, gentity_t * attacker)
Definition at line 278 of file g_team.c.
 {
     int i;
     gentity_t* ent;
     int flag_pw, enemy_flag_pw;
     int otherteam;
     int tokens;
     gentity_t* flag, * carrier = NULL;
     char* c;
     vec3_t v1, v2;
     int team;
     // no bonus for fragging yourself or team mates
     if (!targ->client || !attacker->client || targ == attacker || OnSameTeam(targ, attacker))
         return;
     team = targ->client->sess.sessionTeam;
     otherteam = OtherTeam(targ->client->sess.sessionTeam);
     if (otherteam < 0)
         return; // whoever died isn't on a team
     // same team, if the flag at base, check to he has the enemy flag
     if (team == TEAM_RED) {
         flag_pw = PW_REDFLAG;
         enemy_flag_pw = PW_BLUEFLAG;
     } else {
         flag_pw = PW_BLUEFLAG;
         enemy_flag_pw = PW_REDFLAG;
     }
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         flag_pw = PW_NEUTRALFLAG;
         enemy_flag_pw = PW_NEUTRALFLAG;
     }
 #endif
     // did the attacker frag the flag carrier?
     tokens = 0;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_HARVESTER) {
         tokens = targ->client->ps.generic1;
     }
 #endif
     if (targ->client->ps.powerups[enemy_flag_pw]) {
         attacker->client->pers.teamState.lastfraggedcarrier = level.time;
         AddScore(attacker, targ->r.currentOrigin, CTF_FRAG_CARRIER_BONUS);
         attacker->client->pers.teamState.fragcarrier++;
         PrintMsg(NULL, "%s" S_COLOR_WHITE " fragged %s's flag carrier!\n",
             attacker->client->pers.netname, TeamName(team));
         // the target had the flag, clear the hurt carrier
         // field on the other team
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->inuse && ent->client->sess.sessionTeam == otherteam)
                 ent->client->pers.teamState.lasthurtcarrier = 0;
         }
         return;
     }
     // did the attacker frag a head carrier? other->client->ps.generic1
     if (tokens) {
         attacker->client->pers.teamState.lastfraggedcarrier = level.time;
         AddScore(attacker, targ->r.currentOrigin, CTF_FRAG_CARRIER_BONUS * tokens * tokens);
         attacker->client->pers.teamState.fragcarrier++;
         PrintMsg(NULL, "%s" S_COLOR_WHITE " fragged %s's skull carrier!\n",
             attacker->client->pers.netname, TeamName(team));
         // the target had the flag, clear the hurt carrier
         // field on the other team
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->inuse && ent->client->sess.sessionTeam == otherteam)
                 ent->client->pers.teamState.lasthurtcarrier = 0;
         }
         return;
     }
     if (targ->client->pers.teamState.lasthurtcarrier &&
         level.time - targ->client->pers.teamState.lasthurtcarrier < CTF_CARRIER_DANGER_PROTECT_TIMEOUT &&
         !attacker->client->ps.powerups[flag_pw]) {
         // attacker is on the same team as the flag carrier and
         // fragged a guy who hurt our flag carrier
         AddScore(attacker, targ->r.currentOrigin, CTF_CARRIER_DANGER_PROTECT_BONUS);
         attacker->client->pers.teamState.carrierdefense++;
         targ->client->pers.teamState.lasthurtcarrier = 0;
         attacker->client->ps.persistant[PERS_DEFEND_COUNT]++;
         // add the sprite over the player's head
         attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
         attacker->client->ps.eFlags |= EF_AWARD_DEFEND;
         attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
         return;
     }
     // flag and flag carrier area defense bonuses
     // we have to find the flag and carrier entities
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_OBELISK) {
         // find the team obelisk
         switch (attacker->client->sess.sessionTeam) {
         case TEAM_RED:
             c = "team_redobelisk";
             break;
         case TEAM_BLUE:
             c = "team_blueobelisk";
             break;
         default:
             return;
         }
     } else if (g_gametype.integer == GT_HARVESTER) {
         // find the center obelisk
         c = "team_neutralobelisk";
     } else {
 #endif
         // find the flag
         switch (attacker->client->sess.sessionTeam) {
         case TEAM_RED:
             c = "team_CTF_redflag";
             break;
         case TEAM_BLUE:
             c = "team_CTF_blueflag";
             break;
         default:
             return;
         }
         // find attacker's team's flag carrier
         for (i = 0; i < g_maxclients.integer; i++) {
             carrier = g_entities + i;
             if (carrier->inuse && carrier->client->ps.powerups[flag_pw])
                 break;
             carrier = NULL;
         }
 #ifdef MISSIONPACK
     }
 #endif
     flag = NULL;
     while ((flag = G_Find(flag, FOFS(classname), c)) != NULL) {
         if (!(flag->flags & FL_DROPPED_ITEM))
             break;
     }
     if (!flag)
         return; // can't find attacker's flag
     // ok we have the attackers flag and a pointer to the carrier
     // check to see if we are defending the base's flag
     VectorSubtract(targ->r.currentOrigin, flag->r.currentOrigin, v1);
     VectorSubtract(attacker->r.currentOrigin, flag->r.currentOrigin, v2);
     if (((VectorLength(v1) < CTF_TARGET_PROTECT_RADIUS &&
         trap_InPVS(flag->r.currentOrigin, targ->r.currentOrigin)) ||
         (VectorLength(v2) < CTF_TARGET_PROTECT_RADIUS &&
             trap_InPVS(flag->r.currentOrigin, attacker->r.currentOrigin))) &&
         attacker->client->sess.sessionTeam != targ->client->sess.sessionTeam) {
         // we defended the base flag
         AddScore(attacker, targ->r.currentOrigin, CTF_FLAG_DEFENSE_BONUS);
         attacker->client->pers.teamState.basedefense++;
         attacker->client->ps.persistant[PERS_DEFEND_COUNT]++;
         // add the sprite over the player's head
         attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
         attacker->client->ps.eFlags |= EF_AWARD_DEFEND;
         attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
         return;
     }
     if (carrier && carrier != attacker) {
         VectorSubtract(targ->r.currentOrigin, carrier->r.currentOrigin, v1);
         VectorSubtract(attacker->r.currentOrigin, carrier->r.currentOrigin, v2);
         if (((VectorLength(v1) < CTF_ATTACKER_PROTECT_RADIUS &&
             trap_InPVS(carrier->r.currentOrigin, targ->r.currentOrigin)) ||
             (VectorLength(v2) < CTF_ATTACKER_PROTECT_RADIUS &&
                 trap_InPVS(carrier->r.currentOrigin, attacker->r.currentOrigin))) &&
             attacker->client->sess.sessionTeam != targ->client->sess.sessionTeam) {
             AddScore(attacker, targ->r.currentOrigin, CTF_CARRIER_PROTECT_BONUS);
             attacker->client->pers.teamState.carrierdefense++;
             attacker->client->ps.persistant[PERS_DEFEND_COUNT]++;
             // add the sprite over the player's head
             attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
             attacker->client->ps.eFlags |= EF_AWARD_DEFEND;
             attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
             return;
         }
     }
 }
Referenced by player_die().
Team_FreeEntity()
void Team_FreeEntity (gentity_t * ent)
Definition at line 646 of file g_team.c.
 {
     if (ent->item->giTag == PW_REDFLAG) {
         Team_ReturnFlag(TEAM_RED);
     } else if (ent->item->giTag == PW_BLUEFLAG) {
         Team_ReturnFlag(TEAM_BLUE);
     } else if (ent->item->giTag == PW_NEUTRALFLAG) {
         Team_ReturnFlag(TEAM_FREE);
     }
 }
Referenced by G_RunItem().
Team_GetLocation()
gentity_t* Team_GetLocation (gentity_t * ent)
Definition at line 902 of file g_team.c.
 {
     gentity_t* eloc, * best;
     float            bestlen, len;
     vec3_t            origin;
     best = NULL;
     bestlen = 3 * 8192.0 * 8192.0;
     VectorCopy(ent->r.currentOrigin, origin);
     for (eloc = level.locationHead; eloc; eloc = eloc->nextTrain) {
         len = (origin[0] - eloc->r.currentOrigin[0]) * (origin[0] - eloc->r.currentOrigin[0])
             + (origin[1] - eloc->r.currentOrigin[1]) * (origin[1] - eloc->r.currentOrigin[1])
             + (origin[2] - eloc->r.currentOrigin[2]) * (origin[2] - eloc->r.currentOrigin[2]);
         if (len > bestlen) {
             continue;
         }
         if (!trap_InPVS(origin, eloc->r.currentOrigin)) {
             continue;
         }
         bestlen = len;
         best = eloc;
     }
     return best;
 }
Referenced by CheckTeamStatus(), and Team_GetLocationMsg().
Team_GetLocationMsg()
qboolean Team_GetLocationMsg (gentity_t * ent, char * loc, int loclen)
Definition at line 941 of file g_team.c.
 {
     gentity_t* best;
     best = Team_GetLocation(ent);
     if (!best)
         return qfalse;
     if (best->count) {
         if (best->count < 0)
             best->count = 0;
         if (best->count > 7)
             best->count = 7;
         Com_sprintf(loc, loclen, "%c%c%s" S_COLOR_WHITE, Q_COLOR_ESCAPE, best->count + '0', best->message);
     } else
         Com_sprintf(loc, loclen, "%s", best->message);
     return qtrue;
 }
Referenced by G_Say().
Team_InitGame()
void Team_InitGame (void)
Initialize the team-based game.
Definition at line 50 of file g_team.c.
 {
     memset(&teamgame, 0, sizeof teamgame);
     switch (g_gametype.integer) {
     case GT_CTF:
         teamgame.redStatus = -1; // Invalid to force update
         Team_SetFlagStatus(TEAM_RED, FLAG_ATBASE);
         teamgame.blueStatus = -1; // Invalid to force update
         Team_SetFlagStatus(TEAM_BLUE, FLAG_ATBASE);
         break;
 #ifdef MISSIONPACK
     case GT_1FCTF:
         teamgame.flagStatus = -1; // Invalid to force update
         Team_SetFlagStatus(TEAM_FREE, FLAG_ATBASE);
         break;
 #endif
     default:
         break;
     }
 }
Referenced by G_CheckTeamItems().
Team_ResetFlag()
gentity_t* Team_ResetFlag (int team)
Definition at line 515 of file g_team.c.
 {
     char* c;
     gentity_t* ent, * rent = NULL;
     switch (team) {
     case TEAM_RED:
         c = "team_CTF_redflag";
         break;
     case TEAM_BLUE:
         c = "team_CTF_blueflag";
         break;
     case TEAM_FREE:
         c = "team_CTF_neutralflag";
         break;
     default:
         return NULL;
     }
     ent = NULL;
     while ((ent = G_Find(ent, FOFS(classname), c)) != NULL) {
         if (ent->flags & FL_DROPPED_ITEM)
             G_FreeEntity(ent);
         else {
             rent = ent;
             RespawnItem(ent);
         }
     }
     Team_SetFlagStatus(team, FLAG_ATBASE);
     return rent;
 }
Referenced by Team_DroppedFlagThink(), Team_ResetFlags(), Team_ReturnFlag(), and Team_TouchOurFlag().
Team_ResetFlags()
void Team_ResetFlags (void)
Definition at line 549 of file g_team.c.
 {
     if (g_gametype.integer == GT_CTF) {
         Team_ResetFlag(TEAM_RED);
         Team_ResetFlag(TEAM_BLUE);
     }
 #ifdef MISSIONPACK
     else if (g_gametype.integer == GT_1FCTF) {
         Team_ResetFlag(TEAM_FREE);
     }
 #endif
 }
Referenced by Team_TouchOurFlag().
Team_ReturnFlag()
void Team_ReturnFlag (int team)
Definition at line 636 of file g_team.c.
 {
     Team_ReturnFlagSound(Team_ResetFlag(team), team);
     if (team == TEAM_FREE) {
         PrintMsg(NULL, "The flag has returned!\n");
     } else {
         PrintMsg(NULL, "The %s flag has returned!\n", TeamName(team));
     }
 }
Referenced by player_die(), Team_FreeEntity(), and Use_target_remove_powerups().
Team_ReturnFlagSound()
void Team_ReturnFlagSound (gentity_t * ent, int team)
Definition at line 562 of file g_team.c.
 {
     gentity_t* te;
     if (ent == NULL) {
         G_Printf("Warning:  NULL passed to Team_ReturnFlagSound\n");
         return;
     }
     te = G_TempEntity(ent->s.pos.trBase, EV_GLOBAL_TEAM_SOUND);
     if (team == TEAM_BLUE) {
         te->s.eventParm = GTS_RED_RETURN;
     } else {
         te->s.eventParm = GTS_BLUE_RETURN;
     }
     te->r.svFlags |= SVF_BROADCAST;
 }
Referenced by Team_DroppedFlagThink(), Team_ReturnFlag(), and Team_TouchOurFlag().
Team_SetFlagStatus()
void Team_SetFlagStatus (int team, flagStatus_t status)
Definition at line 192 of file g_team.c.
 {
     qboolean modified = qfalse;
     switch (team) {
     case TEAM_RED:    // CTF
         if (teamgame.redStatus != status) {
             teamgame.redStatus = status;
             modified = qtrue;
         }
         break;
     case TEAM_BLUE:    // CTF
         if (teamgame.blueStatus != status) {
             teamgame.blueStatus = status;
             modified = qtrue;
         }
         break;
     case TEAM_FREE:    // One Flag CTF
         if (teamgame.flagStatus != status) {
             teamgame.flagStatus = status;
             modified = qtrue;
         }
         break;
     }
     if (modified) {
         char st[4];
         if (g_gametype.integer == GT_CTF) {
             st[0] = ctfFlagStatusRemap[teamgame.redStatus];
             st[1] = ctfFlagStatusRemap[teamgame.blueStatus];
             st[2] = 0;
         } else {        // GT_1FCTF
             st[0] = oneFlagStatusRemap[teamgame.flagStatus];
             st[1] = 0;
         }
         trap_SetConfigstring(CS_FLAGSTATUS, st);
     }
 }
Referenced by Team_CheckDroppedItem(), Team_InitGame(), Team_ResetFlag(), and Team_TouchEnemyFlag().
Team_TakeFlagSound()
void Team_TakeFlagSound (gentity_t * ent, int team)
Definition at line 580 of file g_team.c.
 {
     gentity_t* te;
     if (ent == NULL) {
         G_Printf("Warning:  NULL passed to Team_TakeFlagSound\n");
         return;
     }
     // only play sound when the flag was at the base
     // or not picked up the last 10 seconds
     switch (team) {
     case TEAM_RED:
         if (teamgame.blueStatus != FLAG_ATBASE) {
             if (teamgame.blueTakenTime > level.time - 10000)
                 return;
         }
         teamgame.blueTakenTime = level.time;
         break;
     case TEAM_BLUE:    // CTF
         if (teamgame.redStatus != FLAG_ATBASE) {
             if (teamgame.redTakenTime > level.time - 10000)
                 return;
         }
         teamgame.redTakenTime = level.time;
         break;
     }
     te = G_TempEntity(ent->s.pos.trBase, EV_GLOBAL_TEAM_SOUND);
     if (team == TEAM_BLUE) {
         te->s.eventParm = GTS_RED_TAKEN;
     } else {
         te->s.eventParm = GTS_BLUE_TAKEN;
     }
     te->r.svFlags |= SVF_BROADCAST;
 }
Referenced by Team_TouchEnemyFlag().
Team_TouchEnemyFlag()
int Team_TouchEnemyFlag (gentity_t * ent, gentity_t * other, int team)
Definition at line 804 of file g_team.c.
 {
     gclient_t* cl = other->client;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         PrintMsg(NULL, "%s" S_COLOR_WHITE " got the flag!\n", other->client->pers.netname);
         cl->ps.powerups[PW_NEUTRALFLAG] = INT_MAX; // flags never expire
         if (team == TEAM_RED) {
             Team_SetFlagStatus(TEAM_FREE, FLAG_TAKEN_RED);
         } else {
             Team_SetFlagStatus(TEAM_FREE, FLAG_TAKEN_BLUE);
         }
     } else {
 #endif
         PrintMsg(NULL, "%s" S_COLOR_WHITE " got the %s flag!\n",
             other->client->pers.netname, TeamName(team));
         if (team == TEAM_RED)
             cl->ps.powerups[PW_REDFLAG] = INT_MAX; // flags never expire
         else
             cl->ps.powerups[PW_BLUEFLAG] = INT_MAX; // flags never expire
         Team_SetFlagStatus(team, FLAG_TAKEN);
 #ifdef MISSIONPACK
     }
     AddScore(other, ent->r.currentOrigin, CTF_FLAG_BONUS);
 #endif
     cl->pers.teamState.flagsince = level.time;
     Team_TakeFlagSound(ent, team);
     return -1; // Do not respawn this automatically, but do delete it if it was FL_DROPPED
 }
Referenced by Pickup_Team().
Team_TouchOurFlag()
int Team_TouchOurFlag (gentity_t * ent, gentity_t * other, int team)
Definition at line 688 of file g_team.c.
 {
     int            i;
     gentity_t* player;
     gclient_t* cl = other->client;
     int            enemy_flag;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         enemy_flag = PW_NEUTRALFLAG;
     } else {
 #endif
         if (cl->sess.sessionTeam == TEAM_RED) {
             enemy_flag = PW_BLUEFLAG;
         } else {
             enemy_flag = PW_REDFLAG;
         }
         if (ent->flags & FL_DROPPED_ITEM) {
             // hey, it's not home.  return it by teleporting it back
             PrintMsg(NULL, "%s" S_COLOR_WHITE " returned the %s flag!\n",
                 cl->pers.netname, TeamName(team));
             AddScore(other, ent->r.currentOrigin, CTF_RECOVERY_BONUS);
             other->client->pers.teamState.flagrecovery++;
             other->client->pers.teamState.lastreturnedflag = level.time;
             //ResetFlag will remove this entity!  We must return zero
             Team_ReturnFlagSound(Team_ResetFlag(team), team);
             return 0;
         }
 #ifdef MISSIONPACK
     }
 #endif
     // the flag is at home base.  if the player has the enemy
     // flag, he's just won!
     if (!cl->ps.powerups[enemy_flag])
         return 0; // We don't have the flag
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         PrintMsg(NULL, "%s" S_COLOR_WHITE " captured the flag!\n", cl->pers.netname);
     } else {
 #endif
         PrintMsg(NULL, "%s" S_COLOR_WHITE " captured the %s flag!\n", cl->pers.netname, TeamName(OtherTeam(team)));
 #ifdef MISSIONPACK
     }
 #endif
     cl->ps.powerups[enemy_flag] = 0;
     teamgame.last_flag_capture = level.time;
     teamgame.last_capture_team = team;
     // Increase the team's score
     AddTeamScore(ent->s.pos.trBase, other->client->sess.sessionTeam, 1);
     Team_ForceGesture(other->client->sess.sessionTeam);
     other->client->pers.teamState.captures++;
     // add the sprite over the player's head
     other->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
     other->client->ps.eFlags |= EF_AWARD_CAP;
     other->client->rewardTime = level.time + REWARD_SPRITE_TIME;
     other->client->ps.persistant[PERS_CAPTURES]++;
     // other gets another 10 frag bonus
     AddScore(other, ent->r.currentOrigin, CTF_CAPTURE_BONUS);
     Team_CaptureFlagSound(ent, team);
     // Ok, let's do the player loop, hand out the bonuses
     for (i = 0; i < g_maxclients.integer; i++) {
         player = &g_entities[i];
         // also make sure we don't award assist bonuses to the flag carrier himself.
         if (!player->inuse || player == other)
             continue;
         if (player->client->sess.sessionTeam !=
             cl->sess.sessionTeam) {
             player->client->pers.teamState.lasthurtcarrier = -5;
         } else if (player->client->sess.sessionTeam ==
             cl->sess.sessionTeam) {
 #ifdef MISSIONPACK
             AddScore(player, ent->r.currentOrigin, CTF_TEAM_BONUS);
 #endif
             // award extra points for capture assists
             if (player->client->pers.teamState.lastreturnedflag +
                 CTF_RETURN_FLAG_ASSIST_TIMEOUT > level.time) {
                 AddScore(player, ent->r.currentOrigin, CTF_RETURN_FLAG_ASSIST_BONUS);
                 other->client->pers.teamState.assists++;
                 player->client->ps.persistant[PERS_ASSIST_COUNT]++;
                 // add the sprite over the player's head
                 player->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
                 player->client->ps.eFlags |= EF_AWARD_ASSIST;
                 player->client->rewardTime = level.time + REWARD_SPRITE_TIME;
             }
             if (player->client->pers.teamState.lastfraggedcarrier +
                 CTF_FRAG_CARRIER_ASSIST_TIMEOUT > level.time) {
                 AddScore(player, ent->r.currentOrigin, CTF_FRAG_CARRIER_ASSIST_BONUS);
                 other->client->pers.teamState.assists++;
                 player->client->ps.persistant[PERS_ASSIST_COUNT]++;
                 // add the sprite over the player's head
                 player->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
                 player->client->ps.eFlags |= EF_AWARD_ASSIST;
                 player->client->rewardTime = level.time + REWARD_SPRITE_TIME;
             }
         }
     }
     Team_ResetFlags();
     CalculateRanks();
     return 0; // Do not respawn this automatically
 }
Referenced by Pickup_Team().
TeamColorString()
const char* TeamColorString (int team)
Definition at line 92 of file g_team.c.
 {
     if (team == TEAM_RED)
         return S_COLOR_RED;
     else if (team == TEAM_BLUE)
         return S_COLOR_BLUE;
     else if (team == TEAM_SPECTATOR)
         return S_COLOR_YELLOW;
     return S_COLOR_WHITE;
 }
TeamName()
const char* TeamName (int team)
Definition at line 81 of file g_team.c.
 {
     if (team == TEAM_RED)
         return "RED";
     else if (team == TEAM_BLUE)
         return "BLUE";
     else if (team == TEAM_SPECTATOR)
         return "SPECTATOR";
     return "FREE";
 }
Referenced by Team_FragBonuses(), Team_ReturnFlag(), Team_TouchEnemyFlag(), and Team_TouchOurFlag().
TeamplayInfoMessage()
void TeamplayInfoMessage (gentity_t * ent)
Definition at line 1058 of file g_team.c.
 {
     char        entry[1024];
     char        string[8192];
     int            stringlength;
     int            i, j;
     gentity_t* player;
     int            cnt;
     int            h, a;
     int            clients[TEAM_MAXOVERLAY];
     int            team;
     if (!ent->client->pers.teamInfo)
         return;
     // send team info to spectator for team of followed client
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         if (ent->client->sess.spectatorState != SPECTATOR_FOLLOW
             || ent->client->sess.spectatorClient < 0) {
             return;
         }
         team = g_entities[ent->client->sess.spectatorClient].client->sess.sessionTeam;
     } else {
         team = ent->client->sess.sessionTeam;
     }
     if (team != TEAM_RED && team != TEAM_BLUE) {
         return;
     }
     // figure out what client should be on the display
     // we are limited to 8, but we want to use the top eight players
     // but in client order (so they don't keep changing position on the overlay)
     for (i = 0, cnt = 0; i < g_maxclients.integer && cnt < TEAM_MAXOVERLAY; i++) {
         player = g_entities + level.sortedClients[i];
         if (player->inuse && player->client->sess.sessionTeam == team) {
             clients[cnt++] = level.sortedClients[i];
         }
     }
     // We have the top eight players, sort them by clientNum
     qsort(clients, cnt, sizeof(clients[0]), SortClients);
     // send the latest information on all clients
     string[0] = 0;
     stringlength = 0;
     for (i = 0, cnt = 0; i < g_maxclients.integer && cnt < TEAM_MAXOVERLAY; i++) {
         player = g_entities + i;
         if (player->inuse && player->client->sess.sessionTeam == team) {
             h = player->client->ps.stats[STAT_HEALTH];
             a = player->client->ps.stats[STAT_ARMOR];
             if (h < 0) h = 0;
             if (a < 0) a = 0;
             Com_sprintf(entry, sizeof(entry),
                 " %i %i %i %i %i %i",
                 //                level.sortedClients[i], player->client->pers.teamState.location, h, a,
                 i, player->client->pers.teamState.location, h, a,
                 player->client->ps.weapon, player->s.powerups);
             j = strlen(entry);
             if (stringlength + j >= sizeof(string))
                 break;
             strcpy(string + stringlength, entry);
             stringlength += j;
             cnt++;
         }
     }
     trap_SendServerCommand(ent - g_entities, va("tinfo %i %s", cnt, string));
 }
Referenced by CheckTeamStatus().
Variable Documentation
ctfFlagStatusRemap
char ctfFlagStatusRemap[] = { '0', '1', '*', '*', '2' } static
Definition at line 189 of file g_team.c.
Referenced by Team_SetFlagStatus().
neutralObelisk
gentity_t* neutralObelisk
Definition at line 43 of file g_team.c.
oneFlagStatusRemap
char oneFlagStatusRemap[] = { '0', '1', '2', '3', '4' } static
Definition at line 190 of file g_team.c.
Referenced by Team_SetFlagStatus().
teamgame
teamgame_t teamgame
Definition at line 41 of file g_team.c.
Referenced by Team_InitGame(), Team_SetFlagStatus(), Team_TakeFlagSound(), and Team_TouchOurFlag().