ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_combat.c File Reference
g_combat.c File Reference
#include "g_local.h"
Functions
void ScorePlum (gentity_t *ent, vec3_t origin, int score)
void AddScore (gentity_t *ent, vec3_t origin, int score)
void TossClientItems (gentity_t *self)
void LookAtKiller (gentity_t *self, gentity_t *inflictor, gentity_t *attacker)
void GibEntity (gentity_t *self, int killer)
void body_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int meansOfDeath)
void CheckAlmostCapture (gentity_t *self, gentity_t *attacker)
void CheckAlmostScored (gentity_t *self, gentity_t *attacker)
void player_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int meansOfDeath)
int CheckArmor (gentity_t *ent, int damage, int dflags)
int RaySphereIntersections (vec3_t origin, float radius, vec3_t point, vec3_t dir, vec3_t intersections[2])
void G_Damage (gentity_t *targ, gentity_t *inflictor, gentity_t *attacker, vec3_t dir, vec3_t point, int damage, int dflags, int mod)
The damage is dealt out, if all signs indicate that the bullet hit a surface that can be damaged.
qboolean CanDamage (gentity_t *targ, vec3_t origin)
qboolean G_RadiusDamage (vec3_t origin, gentity_t *attacker, float damage, float radius, gentity_t *ignore, int mod)
Variables
char * modNames []
Function Documentation
AddScore()
void AddScore (gentity_t * ent, vec3_t origin, int score)
Definition at line 53 of file g_combat.c.
 {
     if (!ent->client) {
         return;
     }
     // no scoring during pre-match warmup
     if (level.warmupTime) {
         return;
     }
     // show score plum
     ScorePlum(ent, origin, score);
     //
     ent->client->ps.persistant[PERS_SCORE] += score;
     if (g_gametype.integer == GT_TEAM)
         level.teamScores[ent->client->ps.persistant[PERS_TEAM]] += score;
     CalculateRanks();
 }
References CalculateRanks(), gentity_s::client, g_gametype, GT_TEAM, level, PERS_SCORE, PERS_TEAM, playerState_s::persistant, gclient_s::ps, ScorePlum(), level_locals_t::teamScores, and level_locals_t::warmupTime.
Referenced by player_die(), Team_FragBonuses(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), and Use_Target_Score().
body_die()
void body_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, int meansOfDeath)
Definition at line 273 of file g_combat.c.
 {
     if (self->health > GIB_HEALTH) {
         return;
     }
     if (!g_blood.integer) {
         self->health = GIB_HEALTH + 1;
         return;
     }
     GibEntity(self, 0);
 }
References g_blood, GIB_HEALTH, GibEntity(), and vmCvar_t::integer.
Referenced by CopyToBodyQue(), and player_die().
CanDamage()
qboolean CanDamage (gentity_t * targ, vec3_t origin)
Definition at line 1089 of file g_combat.c.
 {
     vec3_t    dest;
     trace_t    tr;
     vec3_t    midpoint;
     vec3_t    offsetmins = { -15, -15, -15 };
     vec3_t    offsetmaxs = { 15, 15, 15 };
     // use the midpoint of the bounds instead of the origin, because
     // bmodels may have their origin is 0,0,0
     VectorAdd(targ->r.absmin, targ->r.absmax, midpoint);
     VectorScale(midpoint, 0.5, midpoint);
     VectorCopy(midpoint, dest);
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0 || tr.entityNum == targ->s.number)
         return qtrue;
     // this should probably check in the plane of projection,
     // rather than in world coordinate
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     return qfalse;
 }
References entityShared_t::absmax, entityShared_t::absmin, ENTITYNUM_NONE, MASK_SOLID, entityState_s::number, qfalse, qtrue, gentity_s::r, gentity_s::s, tr, trap_Trace(), vec3_origin, VectorAdd, VectorCopy, and VectorScale.
Referenced by G_RadiusDamage().
CheckAlmostCapture()
void CheckAlmostCapture (gentity_t * self, gentity_t * attacker)
Definition at line 360 of file g_combat.c.
 {
     gentity_t* ent;
     vec3_t        dir;
     char* classname;
     // if this player was carrying a flag
     if (self->client->ps.powerups[PW_REDFLAG] ||
         self->client->ps.powerups[PW_BLUEFLAG] ||
         self->client->ps.powerups[PW_NEUTRALFLAG]) {
         // get the goal flag this player should have been going for
         if (g_gametype.integer == GT_CTF) {
             if (self->client->sess.sessionTeam == TEAM_BLUE) {
                 classname = "team_CTF_blueflag";
             } else {
                 classname = "team_CTF_redflag";
             }
         } else {
             if (self->client->sess.sessionTeam == TEAM_BLUE) {
                 classname = "team_CTF_redflag";
             } else {
                 classname = "team_CTF_blueflag";
             }
         }
         ent = NULL;
         do {
             ent = G_Find(ent, FOFS(classname), classname);
         } while (ent && (ent->flags & FL_DROPPED_ITEM));
         // if we found the destination flag and it's not picked up
         if (ent && !(ent->r.svFlags & SVF_NOCLIENT)) {
             // if the player was *very* close
             VectorSubtract(self->client->ps.origin, ent->s.origin, dir);
             if (VectorLength(dir) < 200) {
                 self->client->ps.persistant[PERS_PLAYEREVENTS] ^= PLAYEREVENT_HOLYSHIT;
                 if (attacker->client) {
                     attacker->client->ps.persistant[PERS_PLAYEREVENTS] ^= PLAYEREVENT_HOLYSHIT;
                 }
             }
         }
     }
 }
References gentity_s::client, FL_DROPPED_ITEM, gentity_s::flags, FOFS, G_Find(), g_gametype, GT_CTF, NULL, entityState_s::origin, PERS_PLAYEREVENTS, playerState_s::persistant, PLAYEREVENT_HOLYSHIT, gclient_s::ps, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, gentity_s::r, gentity_s::s, SVF_NOCLIENT, entityShared_t::svFlags, TEAM_BLUE, VectorLength(), and VectorSubtract.
Referenced by player_die().
CheckAlmostScored()
void CheckAlmostScored (gentity_t * self, gentity_t * attacker)
Definition at line 407 of file g_combat.c.
 {
     gentity_t* ent;
     vec3_t        dir;
     char* classname;
     // if the player was carrying cubes
     if (self->client->ps.generic1) {
         if (self->client->sess.sessionTeam == TEAM_BLUE) {
             classname = "team_redobelisk";
         } else {
             classname = "team_blueobelisk";
         }
         ent = G_Find(NULL, FOFS(classname), classname);
         // if we found the destination obelisk
         if (ent) {
             // if the player was *very* close
             VectorSubtract(self->client->ps.origin, ent->s.origin, dir);
             if (VectorLength(dir) < 200) {
                 self->client->ps.persistant[PERS_PLAYEREVENTS] ^= PLAYEREVENT_HOLYSHIT;
                 if (attacker->client) {
                     attacker->client->ps.persistant[PERS_PLAYEREVENTS] ^= PLAYEREVENT_HOLYSHIT;
                 }
             }
         }
     }
 }
References gentity_s::client, FOFS, G_Find(), NULL, entityState_s::origin, PERS_PLAYEREVENTS, playerState_s::persistant, PLAYEREVENT_HOLYSHIT, gclient_s::ps, gentity_s::s, TEAM_BLUE, VectorLength(), and VectorSubtract.
Referenced by player_die().
CheckArmor()
int CheckArmor (gentity_t * ent, int damage, int dflags)
Definition at line 677 of file g_combat.c.
 {
     gclient_t* client;
     int            save;
     int            count;
     if (!damage)
         return 0;
     client = ent->client;
     if (!client)
         return 0;
     if (dflags & DAMAGE_NO_ARMOR)
         return 0;
     // armor
     count = client->ps.stats[STAT_ARMOR];
     save = ceil(damage * ARMOR_PROTECTION);
     if (save >= count)
         save = count;
     if (!save)
         return 0;
     client->ps.stats[STAT_ARMOR] -= save;
     return save;
 }
References ARMOR_PROTECTION, gentity_s::client, count, DAMAGE_NO_ARMOR, gclient_s::ps, STAT_ARMOR, and playerState_s::stats.
Referenced by G_Damage().
G_Damage()
void G_Damage (gentity_t * targ, gentity_t * inflictor, gentity_t * attacker, vec3_t dir, vec3_t point, int damage, int dflags, int mod)
The damage is dealt out, if all signs indicate that the bullet hit a surface that can be damaged.
Parameters
targ The entity in the game that will receive the damage.
inflictor The entity that caused the damage, in a literal sense. This could be a bullet, a grenade, a rocket, and so on.
attacker The entity that caused the inflictor to do damage. An example is the player who fired the shotgun.
dir This is the direction of knock back for the target. Some items cause so much damage that the target may be thrown back from the blow.
point This is the point of actual contact where the damage is done. This is a good reference point in case you want to look for damage in specific areas on the target, such as a headshot.
damage The total amount of damage being dealt to the target.
dflags Some types of damage can be specialized or flagged to behave differently within Q3. This is where the damage flags are passed in. An example of available dflags is DAMAGE_NO_ARMOR: the damage ignores players armor.
mod These are flags that tell the function what will be considered the means of death in case it is to be determined at a later point. (For example, if you want to track a certain weapons usage and effectiveness).
Definition at line 832 of file g_combat.c.
 {
     gclient_t* client;
     int            take;
     int            asave;
     int            knockback;
     int            max;
 #ifdef MISSIONPACK
     vec3_t        bouncedir, impactpoint;
 #endif
     if (!targ->takedamage) {
         return;
     }
     // the intermission has already been qualified for, so don't
     // allow any extra scoring
     if (level.intermissionQueued) {
         return;
     }
 #ifdef MISSIONPACK
     if (targ->client && mod != MOD_JUICED) {
         if (targ->client->invulnerabilityTime > level.time) {
             if (dir && point) {
                 G_InvulnerabilityEffect(targ, dir, point, impactpoint, bouncedir);
             }
             return;
         }
     }
 #endif
     if (!inflictor) {
         inflictor = &g_entities[ENTITYNUM_WORLD];
     }
     if (!attacker) {
         attacker = &g_entities[ENTITYNUM_WORLD];
     }
     // shootable doors / buttons don't actually have any health
     if (targ->s.eType == ET_MOVER) {
         if (targ->use && targ->moverState == MOVER_POS1) {
             targ->use(targ, inflictor, attacker);
         }
         return;
     }
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_OBELISK && CheckObeliskAttack(targ, attacker)) {
         return;
     }
 #endif
     // reduce damage by the attacker's handicap value
     // unless they are rocket jumping
     if (attacker->client && attacker != targ) {
         max = attacker->client->ps.stats[STAT_MAX_HEALTH];
 #ifdef MISSIONPACK
         if (bg_itemlist[attacker->client->ps.stats[STAT_PERSISTANT_POWERUP]].giTag == PW_GUARD) {
             max /= 2;
         }
 #endif
         damage = damage * max / 100;
     }
     client = targ->client;
     if (client) {
         if (client->noclip) {
             return;
         }
     }
     if (!dir) {
         dflags |= DAMAGE_NO_KNOCKBACK;
     } else {
         VectorNormalize(dir);
     }
     knockback = damage;
     if (knockback > 200) {
         knockback = 200;
     }
     if (targ->flags & FL_NO_KNOCKBACK) {
         knockback = 0;
     }
     if (dflags & DAMAGE_NO_KNOCKBACK) {
         knockback = 0;
     }
     // figure momentum add, even if the damage won't be taken
     if (knockback && targ->client) {
         vec3_t    kvel;
         float    mass;
         mass = 200;
         VectorScale(dir, g_knockback.value * (float)knockback / mass, kvel);
         VectorAdd(targ->client->ps.velocity, kvel, targ->client->ps.velocity);
         // set the timer so that the other client can't cancel
         // out the movement immediately
         if (!targ->client->ps.pm_time) {
             int        t;
             t = knockback * 2;
             if (t < 50) {
                 t = 50;
             }
             if (t > 200) {
                 t = 200;
             }
             targ->client->ps.pm_time = t;
             targ->client->ps.pm_flags |= PMF_TIME_KNOCKBACK;
         }
     }
     // check for completely getting out of the damage
     if (!(dflags & DAMAGE_NO_PROTECTION)) {
         // if TF_NO_FRIENDLY_FIRE is set, don't do damage to the target
         // if the attacker was on the same team
 #ifdef MISSIONPACK
         if (mod != MOD_JUICED && targ != attacker && !(dflags & DAMAGE_NO_TEAM_PROTECTION) && OnSameTeam(targ, attacker)) {
 #else
         if (targ != attacker && OnSameTeam(targ, attacker)) {
 #endif
             if (!g_friendlyFire.integer) {
                 return;
             }
         }
 #ifdef MISSIONPACK
         if (mod == MOD_PROXIMITY_MINE) {
             if (inflictor && inflictor->parent && OnSameTeam(targ, inflictor->parent)) {
                 return;
             }
             if (targ == attacker) {
                 return;
             }
         }
 #endif
         // check for godmode
         if (targ->flags & FL_GODMODE) {
             return;
         }
     }
     // battlesuit protects from all radius damage (but takes knockback)
     // and protects 50% against all damage
     if (client && client->ps.powerups[PW_BATTLESUIT]) {
         G_AddEvent(targ, EV_POWERUP_BATTLESUIT, 0);
         if ((dflags & DAMAGE_RADIUS) || (mod == MOD_FALLING)) {
             return;
         }
         damage *= 0.5;
     }
     // add to the attacker's hit counter (if the target isn't a general entity like a prox mine)
     if (attacker->client && client
         && targ != attacker && targ->health > 0
         && targ->s.eType != ET_MISSILE
         && targ->s.eType != ET_GENERAL) {
         if (OnSameTeam(targ, attacker)) {
             attacker->client->ps.persistant[PERS_HITS]--;
         } else {
             attacker->client->ps.persistant[PERS_HITS]++;
         }
         attacker->client->ps.persistant[PERS_ATTACKEE_ARMOR] = (targ->health << 8) | (client->ps.stats[STAT_ARMOR]);
     }
     // always give half damage if hurting self
     // calculated after knockback, so rocket jumping works
     if (targ == attacker) {
         damage *= 0.5;
     }
     if (damage < 1) {
         damage = 1;
     }
     take = damage;
     // save some from armor
     asave = CheckArmor(targ, take, dflags);
     take -= asave;
     if (g_debugDamage.integer) {
         G_Printf("%i: client:%i health:%i damage:%i armor:%i\n", level.time, targ->s.number,
             targ->health, take, asave);
     }
     // add to the damage inflicted on a player this frame
     // the total will be turned into screen blends and view angle kicks
     // at the end of the frame
     if (client) {
         if (attacker) {
             client->ps.persistant[PERS_ATTACKER] = attacker->s.number;
         } else {
             client->ps.persistant[PERS_ATTACKER] = ENTITYNUM_WORLD;
         }
         client->damage_armor += asave;
         client->damage_blood += take;
         client->damage_knockback += knockback;
         if (dir) {
             VectorCopy(dir, client->damage_from);
             client->damage_fromWorld = qfalse;
         } else {
             VectorCopy(targ->r.currentOrigin, client->damage_from);
             client->damage_fromWorld = qtrue;
         }
     }
     // See if it's the player hurting the emeny flag carrier
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_CTF || g_gametype.integer == GT_1FCTF) {
 #else
     if (g_gametype.integer == GT_CTF) {
 #endif
         Team_CheckHurtCarrier(targ, attacker);
     }
     if (targ->client) {
         // set the last client who damaged the target
         targ->client->lasthurt_client = attacker->s.number;
         targ->client->lasthurt_mod = mod;
     }
     // do the damage
     if (take) {
         targ->health = targ->health - take;
         if (targ->client) {
             targ->client->ps.stats[STAT_HEALTH] = targ->health;
         }
         if (targ->health <= 0) {
             if (client)
                 targ->flags |= FL_NO_KNOCKBACK;
             if (targ->health < -999)
                 targ->health = -999;
             targ->enemy = attacker;
             targ->die(targ, inflictor, attacker, take, mod);
             return;
         } else if (targ->pain) {
             targ->pain(targ, attacker, take);
         }
     }
 }
References bg_itemlist, CheckArmor(), CheckObeliskAttack(), gentity_s::client, entityShared_t::currentOrigin, gclient_s::damage_armor, gclient_s::damage_blood, gclient_s::damage_from, gclient_s::damage_fromWorld, gclient_s::damage_knockback, DAMAGE_NO_KNOCKBACK, DAMAGE_NO_PROTECTION, DAMAGE_RADIUS, gentity_s::die, gentity_s::enemy, ENTITYNUM_WORLD, ET_GENERAL, ET_MISSILE, ET_MOVER, entityState_s::eType, EV_POWERUP_BATTLESUIT, FL_GODMODE, FL_NO_KNOCKBACK, gentity_s::flags, G_AddEvent(), g_debugDamage, g_entities, g_friendlyFire, g_gametype, G_InvulnerabilityEffect(), g_knockback, G_Printf(), gitem_s::giTag, GT_1FCTF, GT_CTF, GT_OBELISK, gentity_s::health, vmCvar_t::integer, level_locals_t::intermissionQueued, gclient_s::lasthurt_client, gclient_s::lasthurt_mod, level, MOD_FALLING, MOVER_POS1, gentity_s::moverState, gclient_s::noclip, entityState_s::number, OnSameTeam(), gentity_s::pain, gentity_s::parent, PERS_ATTACKEE_ARMOR, PERS_ATTACKER, PERS_HITS, playerState_s::persistant, playerState_s::pm_flags, playerState_s::pm_time, PMF_TIME_KNOCKBACK, playerState_s::powerups, gclient_s::ps, PW_BATTLESUIT, PW_GUARD, qfalse, qtrue, gentity_s::r, gentity_s::s, STAT_ARMOR, STAT_HEALTH, STAT_MAX_HEALTH, playerState_s::stats, t, gentity_s::takedamage, Team_CheckHurtCarrier(), level_locals_t::time, gentity_s::use, vmCvar_t::value, VectorAdd, VectorCopy, VectorNormalize(), VectorScale, and playerState_s::velocity.
Referenced by Blocked_Door(), Bullet_Fire(), CheckGauntletAttack(), ClientEvents(), G_KillBox(), G_MissileImpact(), G_MoverPush(), G_RadiusDamage(), hurt_touch(), P_WorldEffects(), ShotgunPellet(), target_kill_use(), target_laser_think(), Weapon_LightningFire(), and weapon_railgun_fire().
G_RadiusDamage()
qboolean G_RadiusDamage (vec3_t origin, gentity_t * attacker, float damage, float radius, gentity_t * ignore, int mod)
Definition at line 1191 of file g_combat.c.
 {
     float        points, dist;
     gentity_t* ent;
     int            entityList[MAX_GENTITIES];
     int            numListedEntities;
     vec3_t        mins, maxs;
     vec3_t        v;
     vec3_t        dir;
     int            i, e;
     qboolean    hitClient = qfalse;
     if (radius < 1) {
         radius = 1;
     }
     for (i = 0; i < 3; i++) {
         mins[i] = origin[i] - radius;
         maxs[i] = origin[i] + radius;
     }
     numListedEntities = trap_EntitiesInBox(mins, maxs, entityList, MAX_GENTITIES);
     for (e = 0; e < numListedEntities; e++) {
         ent = &g_entities[entityList[e]];
         if (ent == ignore)
             continue;
         if (!ent->takedamage)
             continue;
         // find the distance from the edge of the bounding box
         for (i = 0; i < 3; i++) {
             if (origin[i] < ent->r.absmin[i]) {
                 v[i] = ent->r.absmin[i] - origin[i];
             } else if (origin[i] > ent->r.absmax[i]) {
                 v[i] = origin[i] - ent->r.absmax[i];
             } else {
                 v[i] = 0;
             }
         }
         dist = VectorLength(v);
         if (dist >= radius) {
             continue;
         }
         points = damage * (1.0 - dist / radius);
         if (CanDamage(ent, origin)) {
             if (LogAccuracyHit(ent, attacker)) {
                 hitClient = qtrue;
             }
             VectorSubtract(ent->r.currentOrigin, origin, dir);
             // push the center of mass higher than the origin so players
             // get knocked into the air more
             dir[2] += 24;
             G_Damage(ent, NULL, attacker, dir, origin, (int)points, DAMAGE_RADIUS, mod);
         }
     }
     return hitClient;
 }
References entityShared_t::absmax, entityShared_t::absmin, CanDamage(), entityShared_t::currentOrigin, DAMAGE_RADIUS, G_Damage(), g_entities, LogAccuracyHit(), MAX_GENTITIES, NULL, qfalse, qtrue, gentity_s::r, gentity_s::takedamage, trap_EntitiesInBox(), VectorLength(), and VectorSubtract.
Referenced by G_ExplodeMissile(), and G_MissileImpact().
GibEntity()
void GibEntity (gentity_t * self, int killer)
Definition at line 242 of file g_combat.c.
 {
     gentity_t* ent;
     int i;
     //if this entity still has kamikaze
     if (self->s.eFlags & EF_KAMIKAZE) {
         // check if there is a kamikaze timer around for this owner
         for (i = 0; i < level.num_entities; i++) {
             ent = &g_entities[i];
             if (!ent->inuse)
                 continue;
             if (ent->activator != self)
                 continue;
             if (strcmp(ent->classname, "kamikaze timer"))
                 continue;
             G_FreeEntity(ent);
             break;
         }
     }
     G_AddEvent(self, EV_GIB_PLAYER, killer);
     self->takedamage = qfalse;
     self->s.eType = ET_INVISIBLE;
     self->r.contents = 0;
 }
References gentity_s::activator, gentity_s::classname, EF_KAMIKAZE, ET_INVISIBLE, EV_GIB_PLAYER, G_AddEvent(), g_entities, G_FreeEntity(), gentity_s::inuse, level, level_locals_t::num_entities, and qfalse.
Referenced by body_die(), and player_die().
LookAtKiller()
void LookAtKiller (gentity_t * self, gentity_t * inflictor, gentity_t * attacker)
Definition at line 221 of file g_combat.c.
 {
     vec3_t        dir;
     if (attacker && attacker != self) {
         VectorSubtract(attacker->s.pos.trBase, self->s.pos.trBase, dir);
     } else if (inflictor && inflictor != self) {
         VectorSubtract(inflictor->s.pos.trBase, self->s.pos.trBase, dir);
     } else {
         self->client->ps.stats[STAT_DEAD_YAW] = self->s.angles[YAW];
         return;
     }
     self->client->ps.stats[STAT_DEAD_YAW] = vectoyaw(dir);
 }
References entityState_s::pos, gentity_s::s, STAT_DEAD_YAW, trajectory_t::trBase, VectorSubtract, vectoyaw(), and YAW.
Referenced by player_die().
player_die()
void player_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, int meansOfDeath)
Definition at line 440 of file g_combat.c.
 {
     gentity_t* ent;
     int            anim;
     int            contents;
     int            killer;
     int            i;
     char* killerName, * obit;
     if (self->client->ps.pm_type == PM_DEAD) {
         return;
     }
     if (level.intermissiontime) {
         return;
     }
     // check for an almost capture
     CheckAlmostCapture(self, attacker);
     // check for a player that almost brought in cubes
     CheckAlmostScored(self, attacker);
     if (self->client && self->client->hook) {
         Weapon_HookFree(self->client->hook);
     }
 #ifdef MISSIONPACK
     if ((self->client->ps.eFlags & EF_TICKING) && self->activator) {
         self->client->ps.eFlags &= ~EF_TICKING;
         self->activator->think = G_FreeEntity;
         self->activator->nextthink = level.time;
     }
 #endif
     self->client->ps.pm_type = PM_DEAD;
     if (attacker) {
         killer = attacker->s.number;
         if (attacker->client) {
             killerName = attacker->client->pers.netname;
         } else {
             killerName = "<non-client>";
         }
     } else {
         killer = ENTITYNUM_WORLD;
         killerName = "<world>";
     }
     if (killer < 0 || killer >= MAX_CLIENTS) {
         killer = ENTITYNUM_WORLD;
         killerName = "<world>";
     }
     if (meansOfDeath < 0 || meansOfDeath >= ARRAY_LEN(modNames)) {
         obit = "<bad obituary>";
     } else {
         obit = modNames[meansOfDeath];
     }
     G_LogPrintf("Kill: %i %i %i: %s killed %s by %s\n",
         killer, self->s.number, meansOfDeath, killerName,
         self->client->pers.netname, obit);
     // broadcast the death event to everyone
     ent = G_TempEntity(self->r.currentOrigin, EV_OBITUARY);
     ent->s.eventParm = meansOfDeath;
     ent->s.otherEntityNum = self->s.number;
     ent->s.otherEntityNum2 = killer;
     ent->r.svFlags = SVF_BROADCAST;    // send to everyone
     self->enemy = attacker;
     self->client->ps.persistant[PERS_KILLED]++;
     if (attacker && attacker->client) {
         attacker->client->lastkilled_client = self->s.number;
         if (attacker == self || OnSameTeam(self, attacker)) {
             AddScore(attacker, self->r.currentOrigin, -1);
         } else {
             AddScore(attacker, self->r.currentOrigin, 1);
             if (meansOfDeath == MOD_GAUNTLET) {
                 // play humiliation on player
                 attacker->client->ps.persistant[PERS_GAUNTLET_FRAG_COUNT]++;
                 // add the sprite over the player's head
                 attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
                 attacker->client->ps.eFlags |= EF_AWARD_GAUNTLET;
                 attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
                 // also play humiliation on target
                 self->client->ps.persistant[PERS_PLAYEREVENTS] ^= PLAYEREVENT_GAUNTLETREWARD;
             }
             // check for two kills in a short amount of time
             // if this is close enough to the last kill, give a reward sound
             if (level.time - attacker->client->lastKillTime < CARNAGE_REWARD_TIME) {
                 // play excellent on player
                 attacker->client->ps.persistant[PERS_EXCELLENT_COUNT]++;
                 // add the sprite over the player's head
                 attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
                 attacker->client->ps.eFlags |= EF_AWARD_EXCELLENT;
                 attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
             }
             attacker->client->lastKillTime = level.time;
         }
     } else {
         AddScore(self, self->r.currentOrigin, -1);
     }
     // Add team bonuses
     Team_FragBonuses(self, inflictor, attacker);
     // if I committed suicide, the flag does not fall, it returns.
     if (meansOfDeath == MOD_SUICIDE) {
         if (self->client->ps.powerups[PW_NEUTRALFLAG]) {        // only happens in One Flag CTF
             Team_ReturnFlag(TEAM_FREE);
             self->client->ps.powerups[PW_NEUTRALFLAG] = 0;
         } else if (self->client->ps.powerups[PW_REDFLAG]) {        // only happens in standard CTF
             Team_ReturnFlag(TEAM_RED);
             self->client->ps.powerups[PW_REDFLAG] = 0;
         } else if (self->client->ps.powerups[PW_BLUEFLAG]) {    // only happens in standard CTF
             Team_ReturnFlag(TEAM_BLUE);
             self->client->ps.powerups[PW_BLUEFLAG] = 0;
         }
     }
     TossClientItems(self);
 #ifdef MISSIONPACK
     TossClientPersistantPowerups(self);
     if (g_gametype.integer == GT_HARVESTER) {
         TossClientCubes(self);
     }
 #endif
     Cmd_Score_f(self);        // show scores
     // send updated scores to any clients that are following this one,
     // or they would get stale scoreboards
     for (i = 0; i < level.maxclients; i++) {
         gclient_t* client;
         client = &level.clients[i];
         if (client->pers.connected != CON_CONNECTED) {
             continue;
         }
         if (client->sess.sessionTeam != TEAM_SPECTATOR) {
             continue;
         }
         if (client->sess.spectatorClient == self->s.number) {
             Cmd_Score_f(g_entities + i);
         }
     }
     self->takedamage = qtrue;    // can still be gibbed
     self->s.weapon = WP_NONE;
     self->s.powerups = 0;
     self->r.contents = CONTENTS_CORPSE;
     self->s.angles[0] = 0;
     self->s.angles[2] = 0;
     LookAtKiller(self, inflictor, attacker);
     VectorCopy(self->s.angles, self->client->ps.viewangles);
     self->s.loopSound = 0;
     self->r.maxs[2] = -8;
     // don't allow respawn until the death anim is done
     // g_forcerespawn may force spawning at some later time
     self->client->respawnTime = level.time + 1700;
     // remove powerups
     memset(self->client->ps.powerups, 0, sizeof(self->client->ps.powerups));
     // never gib in a nodrop
     contents = trap_PointContents(self->r.currentOrigin, -1);
     if ((self->health <= GIB_HEALTH && !(contents & CONTENTS_NODROP) && g_blood.integer) || meansOfDeath == MOD_SUICIDE) {
         // gib death
         GibEntity(self, killer);
     } else {
         // normal death
         static int i;
         switch (i) {
         case 0:
             anim = BOTH_DEATH1;
             break;
         case 1:
             anim = BOTH_DEATH2;
             break;
         case 2:
         default:
             anim = BOTH_DEATH3;
             break;
         }
         // for the no-blood option, we need to prevent the health
         // from going to gib level
         if (self->health <= GIB_HEALTH) {
             self->health = GIB_HEALTH + 1;
         }
         self->client->ps.legsAnim =
             ((self->client->ps.legsAnim & ANIM_TOGGLEBIT) ^ ANIM_TOGGLEBIT) | anim;
         self->client->ps.torsoAnim =
             ((self->client->ps.torsoAnim & ANIM_TOGGLEBIT) ^ ANIM_TOGGLEBIT) | anim;
         G_AddEvent(self, EV_DEATH1 + i, killer);
         // the body can still be gibbed
         self->die = body_die;
         // globally cycle through the different death animations
         i = (i + 1) % 3;
 #ifdef MISSIONPACK
         if (self->s.eFlags & EF_KAMIKAZE) {
             Kamikaze_DeathTimer(self);
         }
 #endif
     }
     trap_LinkEntity(self);
 }
References AddScore(), ANIM_TOGGLEBIT, ARRAY_LEN, body_die(), BOTH_DEATH1, BOTH_DEATH2, BOTH_DEATH3, CARNAGE_REWARD_TIME, CheckAlmostCapture(), CheckAlmostScored(), gentity_s::client, level_locals_t::clients, Cmd_Score_f(), CON_CONNECTED, clientPersistant_t::connected, CONTENTS_CORPSE, CONTENTS_NODROP, entityShared_t::currentOrigin, EF_AWARD_ASSIST, EF_AWARD_CAP, EF_AWARD_DEFEND, EF_AWARD_EXCELLENT, EF_AWARD_GAUNTLET, EF_AWARD_IMPRESSIVE, EF_KAMIKAZE, playerState_s::eFlags, ENTITYNUM_WORLD, EV_DEATH1, EV_OBITUARY, entityState_s::eventParm, G_AddEvent(), g_blood, g_entities, G_FreeEntity(), g_gametype, G_LogPrintf(), G_TempEntity(), GIB_HEALTH, GibEntity(), GT_HARVESTER, vmCvar_t::integer, level_locals_t::intermissiontime, gclient_s::lastkilled_client, gclient_s::lastKillTime, level, LookAtKiller(), MAX_CLIENTS, level_locals_t::maxclients, MOD_GAUNTLET, MOD_SUICIDE, modNames, clientPersistant_t::netname, entityState_s::number, OnSameTeam(), entityState_s::otherEntityNum, entityState_s::otherEntityNum2, gclient_s::pers, PERS_EXCELLENT_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_KILLED, PERS_PLAYEREVENTS, playerState_s::persistant, PLAYEREVENT_GAUNTLETREWARD, PM_DEAD, gclient_s::ps, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, qtrue, gentity_s::r, REWARD_SPRITE_TIME, gclient_s::rewardTime, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::spectatorClient, SVF_BROADCAST, entityShared_t::svFlags, TEAM_BLUE, Team_FragBonuses(), TEAM_FREE, TEAM_RED, Team_ReturnFlag(), TEAM_SPECTATOR, level_locals_t::time, TossClientCubes(), TossClientItems(), trap_LinkEntity(), trap_PointContents(), VectorCopy, Weapon_HookFree(), and WP_NONE.
Referenced by ClientSpawn(), Cmd_Kill_f(), and SetTeam().
RaySphereIntersections()
int RaySphereIntersections (vec3_t origin, float radius, vec3_t point, vec3_t dir, vec3_t intersections[2])
Definition at line 713 of file g_combat.c.
 {
     float b, c, d, t;
     //    | origin - (point + t * dir) | = radius
     //    a = dir[0]^2 + dir[1]^2 + dir[2]^2;
     //    b = 2 * (dir[0] * (point[0] - origin[0]) + dir[1] * (point[1] - origin[1]) + dir[2] * (point[2] - origin[2]));
     //    c = (point[0] - origin[0])^2 + (point[1] - origin[1])^2 + (point[2] - origin[2])^2 - radius^2;
     // normalize dir so a = 1
     VectorNormalize(dir);
     b = 2 * (dir[0] * (point[0] - origin[0]) + dir[1] * (point[1] - origin[1]) + dir[2] * (point[2] - origin[2]));
     c = (point[0] - origin[0]) * (point[0] - origin[0]) +
         (point[1] - origin[1]) * (point[1] - origin[1]) +
         (point[2] - origin[2]) * (point[2] - origin[2]) -
         radius * radius;
     d = b * b - 4 * c;
     if (d > 0) {
         t = (-b + sqrt(d)) / 2;
         VectorMA(point, t, dir, intersections[0]);
         t = (-b - sqrt(d)) / 2;
         VectorMA(point, t, dir, intersections[1]);
         return 2;
     } else if (d == 0) {
         t = (-b) / 2;
         VectorMA(point, t, dir, intersections[0]);
         return 1;
     }
     return 0;
 }
References t, VectorMA, and VectorNormalize().
ScorePlum()
void ScorePlum (gentity_t * ent, vec3_t origin, int score)
Definition at line 33 of file g_combat.c.
 {
     gentity_t* plum;
     plum = G_TempEntity(origin, EV_SCOREPLUM);
     // only send this temp entity to a single client
     plum->r.svFlags |= SVF_SINGLECLIENT;
     plum->r.singleClient = ent->s.number;
     //
     plum->s.otherEntityNum = ent->s.number;
     plum->s.time = score;
 }
References EV_SCOREPLUM, G_TempEntity(), entityState_s::number, entityState_s::otherEntityNum, gentity_s::r, gentity_s::s, entityShared_t::singleClient, SVF_SINGLECLIENT, entityShared_t::svFlags, and entityState_s::time.
Referenced by AddScore().
TossClientItems()
void TossClientItems (gentity_t * self)
Definition at line 78 of file g_combat.c.
 {
     gitem_t* item;
     int            weapon;
     float        angle;
     int            i;
     gentity_t* drop;
     // drop the weapon if not a gauntlet or machinegun
     weapon = self->s.weapon;
     // make a special check to see if they are changing to a new
     // weapon that isn't the mg or gauntlet.  Without this, a client
     // can pick up a weapon, be killed, and not drop the weapon because
     // their weapon change hasn't completed yet and they are still holding the MG.
     if (weapon == WP_MACHINEGUN || weapon == WP_GRAPPLING_HOOK) {
         if (self->client->ps.weaponstate == WEAPON_DROPPING) {
             weapon = self->client->pers.cmd.weapon;
         }
         if (!(self->client->ps.stats[STAT_WEAPONS] & (1 << weapon))) {
             weapon = WP_NONE;
         }
     }
     if (weapon > WP_MACHINEGUN&& weapon != WP_GRAPPLING_HOOK &&
         self->client->ps.ammo[weapon]) {
         // find the item type for this weapon
         item = BG_FindItemForWeapon(weapon);
         // spawn the item
         Drop_Item(self, item, 0);
     }
     // drop all the powerups if not in teamplay
     if (g_gametype.integer != GT_TEAM) {
         angle = 45;
         for (i = 1; i < PW_NUM_POWERUPS; i++) {
             if (self->client->ps.powerups[i] > level.time) {
                 item = BG_FindItemForPowerup(i);
                 if (!item) {
                     continue;
                 }
                 drop = Drop_Item(self, item, angle);
                 // decide how many seconds it has left
                 drop->count = (self->client->ps.powerups[i] - level.time) / 1000;
                 if (drop->count < 1) {
                     drop->count = 1;
                 }
                 angle += 45;
             }
         }
     }
 }
References BG_FindItemForPowerup(), BG_FindItemForWeapon(), gentity_s::count, Drop_Item(), g_gametype, GT_TEAM, level, PW_NUM_POWERUPS, gentity_s::s, STAT_WEAPONS, level_locals_t::time, entityState_s::weapon, WEAPON_DROPPING, WP_GRAPPLING_HOOK, WP_MACHINEGUN, and WP_NONE.
Referenced by ClientDisconnect(), and player_die().
Variable Documentation
modNames
char* modNames[]
Definition at line 288 of file g_combat.c.
Referenced by player_die().