ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/g_missile.c File Reference
g_missile.c File Reference
#include "g_local.h"
Macros
#define MISSILE_PRESTEP_TIME 50
Functions
void G_BounceMissile (gentity_t *ent, trace_t *trace)
void G_ExplodeMissile (gentity_t *ent)
void G_MissileImpact (gentity_t *ent, trace_t *trace)
void G_RunMissile (gentity_t *ent)
gentity_t * fire_plasma (gentity_t *self, vec3_t start, vec3_t dir)
gentity_t * fire_grenade (gentity_t *self, vec3_t start, vec3_t dir)
gentity_t * fire_bfg (gentity_t *self, vec3_t start, vec3_t dir)
gentity_t * fire_rocket (gentity_t *self, vec3_t start, vec3_t dir)
gentity_t * fire_grapple (gentity_t *self, vec3_t start, vec3_t dir)
Macro Definition Documentation
MISSILE_PRESTEP_TIME
#define MISSILE_PRESTEP_TIME 50
Definition at line 25 of file g_missile.c.
Function Documentation
fire_bfg()
gentity_t* fire_bfg (gentity_t * self, vec3_t start, vec3_t dir)
Definition at line 605 of file g_missile.c.
{
     gentity_t   *bolt;
     VectorNormalize (dir);
     bolt = G_Spawn();
     bolt->classname = "bfg";
     bolt->nextthink = level.time + 10000;
     bolt->think = G_ExplodeMissile;
     bolt->s.eType = ET_MISSILE;
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     bolt->s.weapon = WP_BFG;
     bolt->r.ownerNum = self->s.number;
     bolt->parent = self;
     bolt->damage = 100;
     bolt->splashDamage = 100;
     bolt->splashRadius = 120;
     bolt->methodOfDeath = MOD_BFG;
     bolt->splashMethodOfDeath = MOD_BFG_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_LINEAR;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;     // move a bit on the very first frame
     VectorCopy( start, bolt->s.pos.trBase );
     VectorScale( dir, 2000, bolt->s.pos.trDelta );
     SnapVector( bolt->s.pos.trDelta );          // save net bandwidth
     VectorCopy (start, bolt->r.currentOrigin);
     return bolt;
 }
Referenced by BFG_Fire().
fire_grapple()
gentity_t* fire_grapple (gentity_t * self, vec3_t start, vec3_t dir)
Definition at line 682 of file g_missile.c.
{
     gentity_t   *hook;
     VectorNormalize (dir);
     hook = G_Spawn();
     hook->classname = "hook";
     hook->nextthink = level.time + 10000;
     hook->think = Weapon_HookFree;
     hook->s.eType = ET_MISSILE;
     hook->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     hook->s.weapon = WP_GRAPPLING_HOOK;
     hook->r.ownerNum = self->s.number;
     hook->methodOfDeath = MOD_GRAPPLE;
     hook->clipmask = MASK_SHOT;
     hook->parent = self;
     hook->target_ent = NULL;
     hook->s.pos.trType = TR_LINEAR;
     hook->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;     // move a bit on the very first frame
     hook->s.otherEntityNum = self->s.number; // use to match beam in client
     VectorCopy( start, hook->s.pos.trBase );
     VectorScale( dir, 800, hook->s.pos.trDelta );
     SnapVector( hook->s.pos.trDelta );          // save net bandwidth
     VectorCopy (start, hook->r.currentOrigin);
     self->client->hook = hook;
     return hook;
 }
Referenced by Weapon_GrapplingHook_Fire().
fire_grenade()
gentity_t* fire_grenade (gentity_t * self, vec3_t start, vec3_t dir)
Definition at line 563 of file g_missile.c.
{
     gentity_t   *bolt;
     VectorNormalize (dir);
     bolt = G_Spawn();
     bolt->classname = "grenade";
     bolt->nextthink = level.time + 2500;
     bolt->think = G_ExplodeMissile;
     bolt->s.eType = ET_MISSILE;
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     bolt->s.weapon = WP_GRENADE_LAUNCHER;
     bolt->s.eFlags = EF_BOUNCE_HALF;
     bolt->r.ownerNum = self->s.number;
     bolt->parent = self;
     bolt->damage = 100;
     bolt->splashDamage = 100;
     bolt->splashRadius = 150;
     bolt->methodOfDeath = MOD_GRENADE;
     bolt->splashMethodOfDeath = MOD_GRENADE_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_GRAVITY;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;     // move a bit on the very first frame
     VectorCopy( start, bolt->s.pos.trBase );
     VectorScale( dir, 700, bolt->s.pos.trDelta );
     SnapVector( bolt->s.pos.trDelta );          // save net bandwidth
     VectorCopy (start, bolt->r.currentOrigin);
     return bolt;
 }
Referenced by Use_Shooter(), and weapon_grenadelauncher_fire().
fire_plasma()
gentity_t* fire_plasma (gentity_t * self, vec3_t start, vec3_t dir)
Definition at line 522 of file g_missile.c.
{
     gentity_t   *bolt;
     VectorNormalize (dir);
     bolt = G_Spawn();
     bolt->classname = "plasma";
     bolt->nextthink = level.time + 10000;
     bolt->think = G_ExplodeMissile;
     bolt->s.eType = ET_MISSILE;
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     bolt->s.weapon = WP_PLASMAGUN;
     bolt->r.ownerNum = self->s.number;
     bolt->parent = self;
     bolt->damage = 20;
     bolt->splashDamage = 15;
     bolt->splashRadius = 20;
     bolt->methodOfDeath = MOD_PLASMA;
     bolt->splashMethodOfDeath = MOD_PLASMA_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_LINEAR;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;     // move a bit on the very first frame
     VectorCopy( start, bolt->s.pos.trBase );
     VectorScale( dir, 2000, bolt->s.pos.trDelta );
     SnapVector( bolt->s.pos.trDelta );          // save net bandwidth
     VectorCopy (start, bolt->r.currentOrigin);
     return bolt;
 }
Referenced by Use_Shooter(), and Weapon_Plasmagun_Fire().
fire_rocket()
gentity_t* fire_rocket (gentity_t * self, vec3_t start, vec3_t dir)
Definition at line 645 of file g_missile.c.
{
     gentity_t   *bolt;
     VectorNormalize (dir);
     bolt = G_Spawn();
     bolt->classname = "rocket";
     bolt->nextthink = level.time + 15000;
     bolt->think = G_ExplodeMissile;
     bolt->s.eType = ET_MISSILE;
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     bolt->s.weapon = WP_ROCKET_LAUNCHER;
     bolt->r.ownerNum = self->s.number;
     bolt->parent = self;
     bolt->damage = 100;
     bolt->splashDamage = 100;
     bolt->splashRadius = 120;
     bolt->methodOfDeath = MOD_ROCKET;
     bolt->splashMethodOfDeath = MOD_ROCKET_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_LINEAR;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;     // move a bit on the very first frame
     VectorCopy( start, bolt->s.pos.trBase );
     VectorScale( dir, 900, bolt->s.pos.trDelta );
     SnapVector( bolt->s.pos.trDelta );          // save net bandwidth
     VectorCopy (start, bolt->r.currentOrigin);
     return bolt;
 }
Referenced by Use_Shooter(), and Weapon_RocketLauncher_Fire().
G_BounceMissile()
void G_BounceMissile (gentity_t * ent, trace_t * trace)
Definition at line 33 of file g_missile.c.
{
     vec3_t  velocity;
     float   dot;
     int     hitTime;
     // reflect the velocity on the trace plane
     hitTime = level.previousTime + ( level.time - level.previousTime ) * trace->fraction;
     BG_EvaluateTrajectoryDelta( &ent->s.pos, hitTime, velocity );
     dot = DotProduct( velocity, trace->plane.normal );
     VectorMA( velocity, -2*dot, trace->plane.normal, ent->s.pos.trDelta );
     if ( ent->s.eFlags & EF_BOUNCE_HALF ) {
         VectorScale( ent->s.pos.trDelta, 0.65, ent->s.pos.trDelta );
         // check for stop
         if ( trace->plane.normal[2] > 0.2 && VectorLength( ent->s.pos.trDelta ) < 40 ) {
             G_SetOrigin( ent, trace->endpos );
             ent->s.time = level.time / 4;
             return;
         }
     }
     VectorAdd( ent->r.currentOrigin, trace->plane.normal, ent->r.currentOrigin);
     VectorCopy( ent->r.currentOrigin, ent->s.pos.trBase );
     ent->s.pos.trTime = level.time;
 }
Referenced by G_MissileImpact().
G_ExplodeMissile()
void G_ExplodeMissile (gentity_t * ent)
Definition at line 67 of file g_missile.c.
{
     vec3_t      dir;
     vec3_t      origin;
     BG_EvaluateTrajectory( &ent->s.pos, level.time, origin );
     SnapVector( origin );
     G_SetOrigin( ent, origin );
     // we don't have a valid direction, so just point straight up
     dir[0] = dir[1] = 0;
     dir[2] = 1;
     ent->s.eType = ET_GENERAL;
     G_AddEvent( ent, EV_MISSILE_MISS, DirToByte( dir ) );
     ent->freeAfterEvent = qtrue;
     // splash damage
     if ( ent->splashDamage ) {
         if( G_RadiusDamage( ent->r.currentOrigin, ent->parent, ent->splashDamage, ent->splashRadius, ent
             , ent->splashMethodOfDeath ) ) {
             g_entities[ent->r.ownerNum].client->accuracy_hits++;
         }
     }
     trap_LinkEntity( ent );
 }
Referenced by fire_bfg(), fire_grenade(), fire_plasma(), fire_rocket(), and G_MoverPush().
G_MissileImpact()
void G_MissileImpact (gentity_t * ent, trace_t * trace)
Definition at line 270 of file g_missile.c.
{
     gentity_t       *other;
     qboolean        hitClient = qfalse;
 #ifdef MISSIONPACK
     vec3_t          forward, impactpoint, bouncedir;
     int             eFlags;
 #endif
     other = &g_entities[trace->entityNum];
     // check for bounce
     if ( !other->takedamage &&
         ( ent->s.eFlags & ( EF_BOUNCE | EF_BOUNCE_HALF ) ) ) {
         G_BounceMissile( ent, trace );
         G_AddEvent( ent, EV_GRENADE_BOUNCE, 0 );
         return;
     }
 #ifdef MISSIONPACK
     if ( other->takedamage ) {
         if ( ent->s.weapon != WP_PROX_LAUNCHER ) {
             if ( other->client && other->client->invulnerabilityTime > level.time ) {
                 //
                 VectorCopy( ent->s.pos.trDelta, forward );
                 VectorNormalize( forward );
                 if (G_InvulnerabilityEffect( other, forward, ent->s.pos.trBase, impactpoint, bouncedir )) {
                     VectorCopy( bouncedir, trace->plane.normal );
                     eFlags = ent->s.eFlags & EF_BOUNCE_HALF;
                     ent->s.eFlags &= ~EF_BOUNCE_HALF;
                     G_BounceMissile( ent, trace );
                     ent->s.eFlags |= eFlags;
                 }
                 ent->target_ent = other;
                 return;
             }
         }
     }
 #endif
     // impact damage
     if (other->takedamage) {
         // FIXME: wrong damage direction?
         if ( ent->damage ) {
             vec3_t  velocity;
             if( LogAccuracyHit( other, &g_entities[ent->r.ownerNum] ) ) {
                 g_entities[ent->r.ownerNum].client->accuracy_hits++;
                 hitClient = qtrue;
             }
             BG_EvaluateTrajectoryDelta( &ent->s.pos, level.time, velocity );
             if ( VectorLength( velocity ) == 0 ) {
                 velocity[2] = 1;    // stepped on a grenade
             }
             G_Damage (other, ent, &g_entities[ent->r.ownerNum], velocity,
                 ent->s.origin, ent->damage,
                 0, ent->methodOfDeath);
         }
     }
 #ifdef MISSIONPACK
     if( ent->s.weapon == WP_PROX_LAUNCHER ) {
         if( ent->s.pos.trType != TR_GRAVITY ) {
             return;
         }
         // if it's a player, stick it on to them (flag them and remove this entity)
         if( other->s.eType == ET_PLAYER && other->health > 0 ) {
             ProximityMine_Player( ent, other );
             return;
         }
         SnapVectorTowards( trace->endpos, ent->s.pos.trBase );
         G_SetOrigin( ent, trace->endpos );
         ent->s.pos.trType = TR_STATIONARY;
         VectorClear( ent->s.pos.trDelta );
         G_AddEvent( ent, EV_PROXIMITY_MINE_STICK, trace->surfaceFlags );
         ent->think = ProximityMine_Activate;
         ent->nextthink = level.time + 2000;
         vectoangles( trace->plane.normal, ent->s.angles );
         ent->s.angles[0] += 90;
         // link the prox mine to the other entity
         ent->enemy = other;
         ent->die = ProximityMine_Die;
         VectorCopy(trace->plane.normal, ent->movedir);
         VectorSet(ent->r.mins, -4, -4, -4);
         VectorSet(ent->r.maxs, 4, 4, 4);
         trap_LinkEntity(ent);
         return;
     }
 #endif
     if (!strcmp(ent->classname, "hook")) {
         gentity_t *nent;
         vec3_t v;
         nent = G_Spawn();
         if ( other->takedamage && other->client ) {
             G_AddEvent( nent, EV_MISSILE_HIT, DirToByte( trace->plane.normal ) );
             nent->s.otherEntityNum = other->s.number;
             ent->enemy = other;
             v[0] = other->r.currentOrigin[0] + (other->r.mins[0] + other->r.maxs[0]) * 0.5;
             v[1] = other->r.currentOrigin[1] + (other->r.mins[1] + other->r.maxs[1]) * 0.5;
             v[2] = other->r.currentOrigin[2] + (other->r.mins[2] + other->r.maxs[2]) * 0.5;
             SnapVectorTowards( v, ent->s.pos.trBase );  // save net bandwidth
         } else {
             VectorCopy(trace->endpos, v);
             G_AddEvent( nent, EV_MISSILE_MISS, DirToByte( trace->plane.normal ) );
             ent->enemy = NULL;
         }
         SnapVectorTowards( v, ent->s.pos.trBase );  // save net bandwidth
         nent->freeAfterEvent = qtrue;
         // change over to a normal entity right at the point of impact
         nent->s.eType = ET_GENERAL;
         ent->s.eType = ET_GRAPPLE;
         G_SetOrigin( ent, v );
         G_SetOrigin( nent, v );
         ent->think = Weapon_HookThink;
         ent->nextthink = level.time + FRAMETIME;
         ent->parent->client->ps.pm_flags |= PMF_GRAPPLE_PULL;
         VectorCopy( ent->r.currentOrigin, ent->parent->client->ps.grapplePoint);
         trap_LinkEntity( ent );
         trap_LinkEntity( nent );
         return;
     }
     // is it cheaper in bandwidth to just remove this ent and create a new
     // one, rather than changing the missile into the explosion?
     if ( other->takedamage && other->client ) {
         G_AddEvent( ent, EV_MISSILE_HIT, DirToByte( trace->plane.normal ) );
         ent->s.otherEntityNum = other->s.number;
     } else if( trace->surfaceFlags & SURF_METALSTEPS ) {
         G_AddEvent( ent, EV_MISSILE_MISS_METAL, DirToByte( trace->plane.normal ) );
     } else {
         G_AddEvent( ent, EV_MISSILE_MISS, DirToByte( trace->plane.normal ) );
     }
     ent->freeAfterEvent = qtrue;
     // change over to a normal entity right at the point of impact
     ent->s.eType = ET_GENERAL;
     SnapVectorTowards( trace->endpos, ent->s.pos.trBase );  // save net bandwidth
     G_SetOrigin( ent, trace->endpos );
     // splash damage (doesn't apply to person directly hit)
     if ( ent->splashDamage ) {
         if( G_RadiusDamage( trace->endpos, ent->parent, ent->splashDamage, ent->splashRadius,
             other, ent->splashMethodOfDeath ) ) {
             if( !hitClient ) {
                 g_entities[ent->r.ownerNum].client->accuracy_hits++;
             }
         }
     }
     trap_LinkEntity( ent );
 }
Referenced by G_RunMissile().
G_RunMissile()
void G_RunMissile (gentity_t * ent)
Definition at line 448 of file g_missile.c.
{
     vec3_t      origin;
     trace_t     tr;
     int         passent;
     // get current position
     BG_EvaluateTrajectory( &ent->s.pos, level.time, origin );
     // if this missile bounced off an invulnerability sphere
     if ( ent->target_ent ) {
         passent = ent->target_ent->s.number;
     }
 #ifdef MISSIONPACK
     // prox mines that left the owner bbox will attach to anything, even the owner
     else if (ent->s.weapon == WP_PROX_LAUNCHER && ent->count) {
         passent = ENTITYNUM_NONE;
     }
 #endif
     else {
         // ignore interactions with the missile owner
         passent = ent->r.ownerNum;
     }
     // trace a line from the previous position to the current position
     trap_Trace( &tr, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, origin, passent, ent->clipmask );
     if ( tr.startsolid || tr.allsolid ) {
         // make sure the tr.entityNum is set to the entity we're stuck in
         trap_Trace( &tr, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, ent->r.currentOrigin, passent, ent->clipmask );
         tr.fraction = 0;
     }
     else {
         VectorCopy( tr.endpos, ent->r.currentOrigin );
     }
     trap_LinkEntity( ent );
     if ( tr.fraction != 1 ) {
         // never explode or bounce on sky
         if ( tr.surfaceFlags & SURF_NOIMPACT ) {
             // If grapple, reset owner
             if (ent->parent && ent->parent->client && ent->parent->client->hook == ent) {
                 ent->parent->client->hook = NULL;
             }
             G_FreeEntity( ent );
             return;
         }
         G_MissileImpact( ent, &tr );
         if ( ent->s.eType != ET_MISSILE ) {
             return;     // exploded
         }
     }
 #ifdef MISSIONPACK
     // if the prox mine wasn't yet outside the player body
     if (ent->s.weapon == WP_PROX_LAUNCHER && !ent->count) {
         // check if the prox mine is outside the owner bbox
         trap_Trace( &tr, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, ent->r.currentOrigin, ENTITYNUM_NONE, ent->clipmask );
         if (!tr.startsolid || tr.entityNum != ent->r.ownerNum) {
             ent->count = 1;
         }
     }
 #endif
     // check think function after bouncing
     G_RunThink( ent );
 }
Referenced by G_RunFrame().