ioquake3 doxygen: C:/entry/dev/ioq3/code/sys/sys_win32.c File Reference
sys_win32.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "sys_local.h"
#include <windows.h>
#include <lmerr.h>
#include <lmcons.h>
#include <lmwksta.h>
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <direct.h>
#include <io.h>
#include <conio.h>
#include <wincrypt.h>
#include <shlobj.h>
#include <psapi.h>
#include <float.h>
Macros
#define KEY_WOW64_32KEY 0x0200
#define _MCW_EM 0x0008001fU
#define _MCW_RC 0x00000300U
#define _MCW_PC 0x00030000U
#define _RC_NEAR 0x00000000U
#define _PC_53 0x00010000U
#define FPUCWMASK1 (_MCW_RC | _MCW_EM)
#define FPUCW (_RC_NEAR | _MCW_EM | _PC_53)
#define FPUCWMASK (FPUCWMASK1 | _MCW_PC)
#define MEM_THRESHOLD 96*1024*1024
#define MAX_FOUND_FILES 0x1000
Functions
unsigned int _controlfp (unsigned int new, unsigned int mask)
void Sys_SetFloatEnv (void)
char * Sys_DefaultHomePath (void)
char * Sys_SteamPath (void)
char * Sys_GogPath (void)
int Sys_Milliseconds (void)
qboolean Sys_RandomBytes (byte *string, int len)
char * Sys_GetCurrentUser (void)
qboolean Sys_LowPhysicalMemory (void)
const char * Sys_Basename (char *path)
const char * Sys_Dirname (char *path)
FILE * Sys_FOpen (const char *ospath, const char *mode)
qboolean Sys_Mkdir (const char *path)
FILE * Sys_Mkfifo (const char *ospath)
char * Sys_Cwd (void)
void Sys_ListFilteredFiles (const char *basedir, char *subdirs, char *filter, char **list, int *numfiles)
static qboolean strgtr (const char *s0, const char *s1)
char ** Sys_ListFiles (const char *directory, const char *extension, char *filter, int *numfiles, qboolean wantsubs)
void Sys_FreeFileList (char **list)
void Sys_Sleep (int msec)
void Sys_ErrorDialog (const char *error)
dialogResult_t Sys_Dialog (dialogType_t type, const char *message, const char *title)
void Sys_GLimpSafeInit (void)
void Sys_GLimpInit (void)
void Sys_PlatformInit (void)
void Sys_PlatformExit (void)
void Sys_SetEnv (const char *name, const char *value)
int Sys_PID (void)
qboolean Sys_PIDIsRunning (int pid)
qboolean Sys_DllExtension (const char *name)
Variables
static char homePath [MAX_OSPATH] = { 0 }
static char steamPath [MAX_OSPATH] = { 0 }
static char gogPath [MAX_OSPATH] = { 0 }
static UINT timerResolution = 0
int sys_timeBase
Macro Definition Documentation
_MCW_EM
#define _MCW_EM 0x0008001fU
Definition at line 69 of file sys_win32.c.
_MCW_PC
#define _MCW_PC 0x00030000U
Definition at line 71 of file sys_win32.c.
_MCW_RC
#define _MCW_RC 0x00000300U
Definition at line 70 of file sys_win32.c.
_PC_53
#define _PC_53 0x00010000U
Definition at line 73 of file sys_win32.c.
_RC_NEAR
#define _RC_NEAR 0x00000000U
Definition at line 72 of file sys_win32.c.
FPUCW
#define FPUCW (_RC_NEAR | _MCW_EM | _PC_53)
Definition at line 79 of file sys_win32.c.
FPUCWMASK
#define FPUCWMASK (FPUCWMASK1 | _MCW_PC)
Definition at line 84 of file sys_win32.c.
FPUCWMASK1
#define FPUCWMASK1 (_MCW_RC | _MCW_EM)
Definition at line 78 of file sys_win32.c.
KEY_WOW64_32KEY
#define KEY_WOW64_32KEY 0x0200
Definition at line 43 of file sys_win32.c.
MAX_FOUND_FILES
#define MAX_FOUND_FILES 0x1000
Definition at line 420 of file sys_win32.c.
MEM_THRESHOLD
#define MEM_THRESHOLD 96*1024*1024
Definition at line 289 of file sys_win32.c.
Function Documentation
_controlfp()
unsigned int _controlfp (unsigned int new, unsigned int mask)
Referenced by Sys_SetFloatEnv().
strgtr()
static qboolean strgtr (const char * s0, const char * s1) static
Definition at line 480 of file sys_win32.c.
 {
     int l0, l1, i;
     l0 = strlen(s0);
     l1 = strlen(s1);
     if (l1<l0) {
         l0 = l1;
     }
     for(i=0;i<l0;i++) {
         if (s1[i] > s0[i]) {
             return qtrue;
         }
         if (s1[i] < s0[i]) {
             return qfalse;
         }
     }
     return qfalse;
 }
References qfalse, and qtrue.
Referenced by Sys_ListFiles().
Sys_Basename()
const char* Sys_Basename (char * path)
Definition at line 308 of file sys_win32.c.
 {
     static char base[ MAX_OSPATH ] = { 0 };
     int length;
     length = strlen( path ) - 1;
     // Skip trailing slashes
     while( length > 0 && path[ length ] == '\\' )
         length--;
     while( length > 0 && path[ length - 1 ] != '\\' )
         length--;
     Q_strncpyz( base, &path[ length ], sizeof( base ) );
     length = strlen( base ) - 1;
     // Strip trailing slashes
     while( length > 0 && base[ length ] == '\\' )
     base[ length-- ] = '\0';
     return base;
 }
References MAX_OSPATH, and Q_strncpyz().
Referenced by Sys_StripAppBundle().
Sys_Cwd()
char* Sys_Cwd (void)
Definition at line 403 of file sys_win32.c.
                       {
     static char cwd[MAX_OSPATH];
     _getcwd( cwd, sizeof( cwd ) - 1 );
     cwd[MAX_OSPATH-1] = 0;
     return cwd;
 }
References MAX_OSPATH.
Referenced by Sys_DefaultInstallPath().
Sys_DefaultHomePath()
char* Sys_DefaultHomePath (void)
Definition at line 97 of file sys_win32.c.
 {
     TCHAR szPath[MAX_PATH];
     FARPROC qSHGetFolderPath;
     HMODULE shfolder = LoadLibrary("shfolder.dll");
     if(shfolder == NULL)
     {
         Com_Printf("Unable to load SHFolder.dll\n");
         return NULL;
     }
     if(!*homePath && com_homepath)
     {
         qSHGetFolderPath = GetProcAddress(shfolder, "SHGetFolderPathA");
         if(qSHGetFolderPath == NULL)
         {
             Com_Printf("Unable to find SHGetFolderPath in SHFolder.dll\n");
             FreeLibrary(shfolder);
             return NULL;
         }
         if( !SUCCEEDED( qSHGetFolderPath( NULL, CSIDL_APPDATA,
                         NULL, 0, szPath ) ) )
         {
             Com_Printf("Unable to detect CSIDL_APPDATA\n");
             FreeLibrary(shfolder);
             return NULL;
         }
         Com_sprintf(homePath, sizeof(homePath), "%s%c", szPath, PATH_SEP);
         if(com_homepath->string[0])
             Q_strcat(homePath, sizeof(homePath), com_homepath->string);
         else
             Q_strcat(homePath, sizeof(homePath), HOMEPATH_NAME_WIN);
     }
     FreeLibrary(shfolder);
     return homePath;
 }
References com_homepath, Com_Printf(), Com_sprintf(), homePath, HOMEPATH_NAME_WIN, NULL, PATH_SEP, Q_strcat(), and cvar_s::string.
Referenced by FS_Startup().
Sys_Dialog()
dialogResult_t Sys_Dialog (dialogType_t type, const char * message, const char * title)
Definition at line 709 of file sys_win32.c.
 {
     UINT uType;
     switch( type )
     {
         default:
         case DT_INFO:      uType = MB_ICONINFORMATION|MB_OK; break;
         case DT_WARNING:   uType = MB_ICONWARNING|MB_OK; break;
         case DT_ERROR:     uType = MB_ICONERROR|MB_OK; break;
         case DT_YES_NO:    uType = MB_ICONQUESTION|MB_YESNO; break;
         case DT_OK_CANCEL: uType = MB_ICONWARNING|MB_OKCANCEL; break;
     }
     switch( MessageBox( NULL, message, title, uType ) )
     {
         default:
         case IDOK:      return DR_OK;
         case IDCANCEL:  return DR_CANCEL;
         case IDYES:     return DR_YES;
         case IDNO:      return DR_NO;
     }
 }
References DR_CANCEL, DR_NO, DR_OK, DR_YES, DT_ERROR, DT_INFO, DT_OK_CANCEL, DT_WARNING, DT_YES_NO, and NULL.
Referenced by main(), Sys_ErrorDialog(), and Sys_InitPIDFile().
Sys_Dirname()
const char* Sys_Dirname (char * path)
Definition at line 338 of file sys_win32.c.
 {
     static char dir[ MAX_OSPATH ] = { 0 };
     int length;
     Q_strncpyz( dir, path, sizeof( dir ) );
     length = strlen( dir ) - 1;
     while( length > 0 && dir[ length ] != '\\' )
         length--;
     dir[ length ] = '\0';
     return dir;
 }
References MAX_OSPATH, and Q_strncpyz().
Referenced by main(), and Sys_StripAppBundle().
Sys_DllExtension()
qboolean Sys_DllExtension (const char * name)
Definition at line 861 of file sys_win32.c.
{
     return COM_CompareExtension( name, DLL_EXT );
 }
References COM_CompareExtension(), and DLL_EXT.
Referenced by FS_CheckFilenameIsMutable(), Sys_LoadDll(), and Sys_LoadGameDll().
Sys_ErrorDialog()
void Sys_ErrorDialog (const char * error)
Definition at line 668 of file sys_win32.c.
 {
     if( Sys_Dialog( DT_YES_NO, va( "%s. Copy console log to clipboard?", error ),
             "Error" ) == DR_YES )
     {
         HGLOBAL memoryHandle;
         char *clipMemory;
         memoryHandle = GlobalAlloc( GMEM_MOVEABLE|GMEM_DDESHARE, CON_LogSize( ) + 1 );
         clipMemory = (char *)GlobalLock( memoryHandle );
         if( clipMemory )
         {
             char *p = clipMemory;
             char buffer[ 1024 ];
             unsigned int size;
             while( ( size = CON_LogRead( buffer, sizeof( buffer ) ) ) > 0 )
             {
                 Com_Memcpy( p, buffer, size );
                 p += size;
             }
             *p = '\0';
             if( OpenClipboard( NULL ) && EmptyClipboard( ) )
                 SetClipboardData( CF_TEXT, memoryHandle );
             GlobalUnlock( clipMemory );
             CloseClipboard( );
         }
     }
 }
References buffer, Com_Memcpy, CON_LogRead(), CON_LogSize(), DR_YES, DT_YES_NO, NULL, Sys_Dialog(), and va().
Referenced by Sys_Error().
Sys_FOpen()
FILE* Sys_FOpen (const char * ospath, const char * mode)
Definition at line 359 of file sys_win32.c.
{
     size_t length;
     // Windows API ignores all trailing spaces and periods which can get around Quake 3 file system restrictions.
     length = strlen( ospath );
     if ( length == 0 || ospath[length-1] == ' ' || ospath[length-1] == '.' ) {
         return NULL;
     }
     return fopen( ospath, mode );
 }
References NULL.
Referenced by FS_FileInPathExists(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_Startup(), FS_SV_FOpenFileRead(), and FS_SV_FOpenFileWrite().
Sys_FreeFileList()
void Sys_FreeFileList (char ** list)
Definition at line 619 of file sys_win32.c.
 {
     int i;
     if ( !list ) {
         return;
     }
     for ( i = 0 ; list[i] ; i++ ) {
         Z_Free( list[i] );
     }
     Z_Free( list );
 }
References Z_Free().
Referenced by FS_AddGameDirectory(), FS_GetModList(), and FS_ListFilteredFiles().
Sys_GetCurrentUser()
char* Sys_GetCurrentUser (void)
Definition at line 273 of file sys_win32.c.
 {
     static char s_userName[1024];
     unsigned long size = sizeof( s_userName );
     if( !GetUserName( s_userName, &size ) )
         strcpy( s_userName, "player" );
     if( !s_userName[0] )
     {
         strcpy( s_userName, "player" );
     }
     return s_userName;
 }
Referenced by Sys_Init().
Sys_GLimpInit()
void Sys_GLimpInit (void)
Definition at line 751 of file sys_win32.c.
 {
 }
Referenced by CL_InitRef().
Sys_GLimpSafeInit()
void Sys_GLimpSafeInit (void)
Definition at line 740 of file sys_win32.c.
 {
 }
Referenced by CL_InitRef().
Sys_GogPath()
char* Sys_GogPath (void)
Definition at line 198 of file sys_win32.c.
 {
 #ifdef GOGPATH_ID
     HKEY gogRegKey;
     DWORD pathLen = MAX_OSPATH;
     if (!gogPath[0] && !RegOpenKeyEx(HKEY_LOCAL_MACHINE, "SOFTWARE\\GOG.com\\Games\\" GOGPATH_ID, 0, KEY_QUERY_VALUE | KEY_WOW64_32KEY, &gogRegKey))
     {
         pathLen = MAX_OSPATH;
         if (RegQueryValueEx(gogRegKey, "PATH", NULL, NULL, (LPBYTE)gogPath, &pathLen))
             gogPath[0] = '\0';
         RegCloseKey(gogRegKey);
     }
     if (gogPath[0])
     {
         if (pathLen == MAX_OSPATH)
             pathLen--;
         gogPath[pathLen] = '\0';
     }
 #endif
     return gogPath;
 }
References gogPath, GOGPATH_ID, KEY_WOW64_32KEY, MAX_OSPATH, and NULL.
Referenced by FS_Startup().
Sys_ListFiles()
char** Sys_ListFiles (const char * directory, const char * extension, char * filter, int * numfiles, qboolean wantsubs)
Definition at line 507 of file sys_win32.c.
 {
     char        search[MAX_OSPATH];
     int         nfiles;
     char        **listCopy;
     char        *list[MAX_FOUND_FILES];
     struct _finddata_t findinfo;
     intptr_t        findhandle;
     int         flag;
     int         i;
     int         extLen;
     if (filter) {
         nfiles = 0;
         Sys_ListFilteredFiles( directory, "", filter, list, &nfiles );
         list[ nfiles ] = 0;
         *numfiles = nfiles;
         if (!nfiles)
             return NULL;
         listCopy = Z_Malloc( ( nfiles + 1 ) * sizeof( *listCopy ) );
         for ( i = 0 ; i < nfiles ; i++ ) {
             listCopy[i] = list[i];
         }
         listCopy[i] = NULL;
         return listCopy;
     }
     if ( !extension) {
         extension = "";
     }
     // passing a slash as extension will find directories
     if ( extension[0] == '/' && extension[1] == 0 ) {
         extension = "";
         flag = 0;
     } else {
         flag = _A_SUBDIR;
     }
     extLen = strlen( extension );
     Com_sprintf( search, sizeof(search), "%s\\*%s", directory, extension );
     // search
     nfiles = 0;
     findhandle = _findfirst (search, &findinfo);
     if (findhandle == -1) {
         *numfiles = 0;
         return NULL;
     }
     do {
         if ( (!wantsubs && flag ^ ( findinfo.attrib & _A_SUBDIR )) || (wantsubs && findinfo.attrib & _A_SUBDIR) ) {
             if (*extension) {
                 if ( strlen( findinfo.name ) < extLen ||
                     Q_stricmp(
                         findinfo.name + strlen( findinfo.name ) - extLen,
                         extension ) ) {
                     continue; // didn't match
                 }
             }
             if ( nfiles == MAX_FOUND_FILES - 1 ) {
                 break;
             }
             list[ nfiles ] = CopyString( findinfo.name );
             nfiles++;
         }
     } while ( _findnext (findhandle, &findinfo) != -1 );
     list[ nfiles ] = 0;
     _findclose (findhandle);
     // return a copy of the list
     *numfiles = nfiles;
     if ( !nfiles ) {
         return NULL;
     }
     listCopy = Z_Malloc( ( nfiles + 1 ) * sizeof( *listCopy ) );
     for ( i = 0 ; i < nfiles ; i++ ) {
         listCopy[i] = list[i];
     }
     listCopy[i] = NULL;
     do {
         flag = 0;
         for(i=1; i<nfiles; i++) {
             if (strgtr(listCopy[i-1], listCopy[i])) {
                 char *temp = listCopy[i];
                 listCopy[i] = listCopy[i-1];
                 listCopy[i-1] = temp;
                 flag = 1;
             }
         }
     } while(flag);
     return listCopy;
 }
References Com_sprintf(), CopyString(), intptr_t(), MAX_FOUND_FILES, MAX_OSPATH, NULL, Q_stricmp(), strgtr(), Sys_ListFilteredFiles(), and Z_Malloc.
Referenced by FS_AddGameDirectory(), FS_GetModList(), and FS_ListFilteredFiles().
Sys_ListFilteredFiles()
void Sys_ListFilteredFiles (const char * basedir, char * subdirs, char * filter, char ** list, int * numfiles)
Definition at line 427 of file sys_win32.c.
 {
     char        search[MAX_OSPATH], newsubdirs[MAX_OSPATH];
     char        filename[MAX_OSPATH];
     intptr_t    findhandle;
     struct _finddata_t findinfo;
     if ( *numfiles >= MAX_FOUND_FILES - 1 ) {
         return;
     }
     if (strlen(subdirs)) {
         Com_sprintf( search, sizeof(search), "%s\\%s\\*", basedir, subdirs );
     }
     else {
         Com_sprintf( search, sizeof(search), "%s\\*", basedir );
     }
     findhandle = _findfirst (search, &findinfo);
     if (findhandle == -1) {
         return;
     }
     do {
         if (findinfo.attrib & _A_SUBDIR) {
             if (Q_stricmp(findinfo.name, ".") && Q_stricmp(findinfo.name, "..")) {
                 if (strlen(subdirs)) {
                     Com_sprintf( newsubdirs, sizeof(newsubdirs), "%s\\%s", subdirs, findinfo.name);
                 }
                 else {
                     Com_sprintf( newsubdirs, sizeof(newsubdirs), "%s", findinfo.name);
                 }
                 Sys_ListFilteredFiles( basedir, newsubdirs, filter, list, numfiles );
             }
         }
         if ( *numfiles >= MAX_FOUND_FILES - 1 ) {
             break;
         }
         Com_sprintf( filename, sizeof(filename), "%s\\%s", subdirs, findinfo.name );
         if (!Com_FilterPath( filter, filename, qfalse ))
             continue;
         list[ *numfiles ] = CopyString( filename );
         (*numfiles)++;
     } while ( _findnext (findhandle, &findinfo) != -1 );
     _findclose (findhandle);
 }
References Com_FilterPath(), Com_sprintf(), CopyString(), intptr_t(), MAX_FOUND_FILES, MAX_OSPATH, Q_stricmp(), and qfalse.
Referenced by Sys_ListFiles().
Sys_LowPhysicalMemory()
qboolean Sys_LowPhysicalMemory (void)
Definition at line 296 of file sys_win32.c.
 {
     MEMORYSTATUS stat;
     GlobalMemoryStatus (&stat);
     return (stat.dwTotalPhys <= MEM_THRESHOLD) ? qtrue : qfalse;
 }
References MEM_THRESHOLD, qfalse, and qtrue.
Referenced by CL_InitCGame(), and CL_InitRef().
Sys_Milliseconds()
int Sys_Milliseconds (void)
Definition at line 231 of file sys_win32.c.
 {
     int             sys_curtime;
     static qboolean initialized = qfalse;
     if (!initialized) {
         sys_timeBase = timeGetTime();
         initialized = qtrue;
     }
     sys_curtime = timeGetTime() - sys_timeBase;
     return sys_curtime;
 }
References qfalse, qtrue, and sys_timeBase.
Referenced by CL_CgameSystemCalls(), CL_DemoCompleted(), CL_GetFreePing(), CL_GetPing(), CL_InitCGame(), CL_Ping_f(), CL_ScaledMilliseconds(), CL_ServerInfoPacket(), CL_SetCGameTime(), CL_UISystemCalls(), CL_UpdateVisiblePings_f(), Com_Error(), Com_Frame(), Com_GetSystemEvent(), Com_QueueEvent(), Com_RunAndTimeServerPacket(), Com_TimeVal(), Com_TouchMemory(), Con_ToggleMenu_f(), main(), NET_FlushPacketQueue(), NET_QueuePacket(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_Frame(), SV_GameSystemCalls(), SV_RateMsec(), SV_SendQueuedPackets(), SVC_BucketForAddress(), and SVC_RateLimit().
Sys_Mkdir()
qboolean Sys_Mkdir (const char * path)
Definition at line 376 of file sys_win32.c.
 {
     if( !CreateDirectory( path, NULL ) )
     {
         if( GetLastError( ) != ERROR_ALREADY_EXISTS )
             return qfalse;
     }
     return qtrue;
 }
References NULL, qfalse, and qtrue.
Referenced by FS_CreatePath().
Sys_Mkfifo()
FILE* Sys_Mkfifo (const char * ospath)
Definition at line 393 of file sys_win32.c.
 {
     return NULL;
 }
References NULL.
Referenced by FS_FCreateOpenPipeFile().
Sys_PID()
int Sys_PID (void)
Definition at line 823 of file sys_win32.c.
 {
     return GetCurrentProcessId( );
 }
Referenced by Sys_WritePIDFile().
Sys_PIDIsRunning()
qboolean Sys_PIDIsRunning (int pid)
Definition at line 833 of file sys_win32.c.
 {
     DWORD processes[ 1024 ];
     DWORD numBytes, numProcesses;
     int i;
     if( !EnumProcesses( processes, sizeof( processes ), &numBytes ) )
         return qfalse; // Assume it's not running
     numProcesses = numBytes / sizeof( DWORD );
     // Search for the pid
     for( i = 0; i < numProcesses; i++ )
     {
         if( processes[ i ] == pid )
             return qtrue;
     }
     return qfalse;
 }
References qfalse, and qtrue.
Referenced by Sys_WritePIDFile().
Sys_PlatformExit()
void Sys_PlatformExit (void)
Definition at line 795 of file sys_win32.c.
 {
 #ifndef DEDICATED
     if(timerResolution)
         timeEndPeriod(timerResolution);
 #endif
 }
References timerResolution.
Referenced by __attribute__().
Sys_PlatformInit()
void Sys_PlatformInit (void)
Definition at line 762 of file sys_win32.c.
 {
 #ifndef DEDICATED
     TIMECAPS ptc;
 #endif
     Sys_SetFloatEnv();
 #ifndef DEDICATED
     if(timeGetDevCaps(&ptc, sizeof(ptc)) == MMSYSERR_NOERROR)
     {
         timerResolution = ptc.wPeriodMin;
         if(timerResolution > 1)
         {
             Com_Printf("Warning: Minimum supported timer resolution is %ums "
                 "on this system, recommended resolution 1ms\n", timerResolution);
         }
         timeBeginPeriod(timerResolution);
     }
     else
         timerResolution = 0;
 #endif
 }
References Com_Printf(), Sys_SetFloatEnv(), and timerResolution.
Referenced by main().
Sys_RandomBytes()
qboolean Sys_RandomBytes (byte * string, int len)
Definition at line 250 of file sys_win32.c.
 {
     HCRYPTPROV  prov;
     if( !CryptAcquireContext( &prov, NULL, NULL,
         PROV_RSA_FULL, CRYPT_VERIFYCONTEXT ) )  {
         return qfalse;
     }
     if( !CryptGenRandom( prov, len, (BYTE *)string ) )  {
         CryptReleaseContext( prov, 0 );
         return qfalse;
     }
     CryptReleaseContext( prov, 0 );
     return qtrue;
 }
References NULL, qfalse, and qtrue.
Referenced by Com_InitRand(), and Com_RandomBytes().
Sys_SetEnv()
void Sys_SetEnv (const char * name, const char * value)
Definition at line 810 of file sys_win32.c.
 {
     if(value)
         _putenv(va("%s=%s", name, value));
     else
         _putenv(va("%s=", name));
 }
References va().
Referenced by CL_InitRef(), and Com_Setenv_f().
Sys_SetFloatEnv()
void Sys_SetFloatEnv (void)
Definition at line 87 of file sys_win32.c.
 {
     _controlfp(FPUCW, FPUCWMASK);
 }
References _controlfp(), FPUCW, and FPUCWMASK.
Referenced by Sys_PlatformInit().
Sys_Sleep()
void Sys_Sleep (int msec)
Definition at line 642 of file sys_win32.c.
 {
     if( msec == 0 )
         return;
 #ifdef DEDICATED
     if( msec < 0 )
         WaitForSingleObject( GetStdHandle( STD_INPUT_HANDLE ), INFINITE );
     else
         WaitForSingleObject( GetStdHandle( STD_INPUT_HANDLE ), msec );
 #else
     // Client Sys_Sleep doesn't support waiting on stdin
     if( msec < 0 )
         return;
     Sleep( msec );
 #endif
 }
References INFINITE.
Referenced by SV_Frame().
Sys_SteamPath()
char* Sys_SteamPath (void)
Definition at line 144 of file sys_win32.c.
 {
 #if defined(STEAMPATH_NAME) || defined(STEAMPATH_APPID)
     HKEY steamRegKey;
     DWORD pathLen = MAX_OSPATH;
     qboolean finishPath = qfalse;
 #ifdef STEAMPATH_APPID
     // Assuming Steam is a 32-bit app
     if (!steamPath[0] && !RegOpenKeyEx(HKEY_LOCAL_MACHINE, "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Steam App " STEAMPATH_APPID, 0, KEY_QUERY_VALUE | KEY_WOW64_32KEY, &steamRegKey))
     {
         pathLen = MAX_OSPATH;
         if (RegQueryValueEx(steamRegKey, "InstallLocation", NULL, NULL, (LPBYTE)steamPath, &pathLen))
             steamPath[0] = '\0';
         RegCloseKey(steamRegKey);
     }
 #endif
 #ifdef STEAMPATH_NAME
     if (!steamPath[0] && !RegOpenKeyEx(HKEY_CURRENT_USER, "Software\\Valve\\Steam", 0, KEY_QUERY_VALUE, &steamRegKey))
     {
         pathLen = MAX_OSPATH;
         if (RegQueryValueEx(steamRegKey, "SteamPath", NULL, NULL, (LPBYTE)steamPath, &pathLen))
             if (RegQueryValueEx(steamRegKey, "InstallPath", NULL, NULL, (LPBYTE)steamPath, &pathLen))
                 steamPath[0] = '\0';
         if (steamPath[0])
             finishPath = qtrue;
         RegCloseKey(steamRegKey);
     }
 #endif
     if (steamPath[0])
     {
         if (pathLen == MAX_OSPATH)
             pathLen--;
         steamPath[pathLen] = '\0';
         if (finishPath)
             Q_strcat(steamPath, MAX_OSPATH, "\\SteamApps\\common\\" STEAMPATH_NAME );
     }
 #endif
     return steamPath;
 }
References KEY_WOW64_32KEY, MAX_OSPATH, NULL, Q_strcat(), qfalse, qtrue, steamPath, STEAMPATH_APPID, and STEAMPATH_NAME.
Referenced by FS_Startup().
Variable Documentation
gogPath
char gogPath[MAX_OSPATH] = { 0 } static
Definition at line 53 of file sys_win32.c.
Referenced by Sys_GogPath().
homePath
char homePath[MAX_OSPATH] = { 0 } static
Definition at line 47 of file sys_win32.c.
Referenced by FS_HomeRemove(), FS_Startup(), Sys_DefaultHomePath(), and Sys_PIDFileName().
steamPath
char steamPath[MAX_OSPATH] = { 0 } static
Definition at line 50 of file sys_win32.c.
Referenced by Sys_SteamPath().
sys_timeBase
int sys_timeBase
Definition at line 230 of file sys_win32.c.
Referenced by Sys_Milliseconds().
timerResolution
UINT timerResolution = 0 static
Definition at line 56 of file sys_win32.c.
Referenced by Sys_PlatformExit(), and Sys_PlatformInit().