ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_mods.c File Reference
ui_mods.c File Reference
#include "ui_local.h"
Classes
struct mods_t
Macros
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_FIGHT0 "menu/art/load_0"
#define ART_FIGHT1 "menu/art/load_1"
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define MAX_MODS 64
#define NAMEBUFSIZE (MAX_MODS * 48)
#define GAMEBUFSIZE (MAX_MODS * 16)
#define ID_BACK 10
#define ID_GO 11
#define ID_LIST 12
Functions
static void UI_Mods_MenuEvent (void *ptr, int event)
static void UI_Mods_ParseInfos (char *modDir, char *modDesc)
static void UI_Mods_LoadMods (void)
static void UI_Mods_MenuInit (void)
void UI_ModsMenu_Cache (void)
void UI_ModsMenu (void)
Variables
static mods_t s_mods
Macro Definition Documentation
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 25 of file ui_mods.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 26 of file ui_mods.c.
ART_FIGHT0
#define ART_FIGHT0 "menu/art/load_0"
Definition at line 27 of file ui_mods.c.
ART_FIGHT1
#define ART_FIGHT1 "menu/art/load_1"
Definition at line 28 of file ui_mods.c.
ART_FRAMEL
#define ART_FRAMEL "menu/art/frame2_l"
Definition at line 29 of file ui_mods.c.
ART_FRAMER
#define ART_FRAMER "menu/art/frame1_r"
Definition at line 30 of file ui_mods.c.
GAMEBUFSIZE
#define GAMEBUFSIZE (MAX_MODS * 16)
Definition at line 34 of file ui_mods.c.
ID_BACK
#define ID_BACK 10
Definition at line 36 of file ui_mods.c.
ID_GO
#define ID_GO 11
Definition at line 37 of file ui_mods.c.
ID_LIST
#define ID_LIST 12
Definition at line 38 of file ui_mods.c.
MAX_MODS
#define MAX_MODS 64
Definition at line 32 of file ui_mods.c.
NAMEBUFSIZE
#define NAMEBUFSIZE (MAX_MODS * 48)
Definition at line 33 of file ui_mods.c.
Function Documentation
UI_Mods_LoadMods()
static void UI_Mods_LoadMods (void) static
Definition at line 114 of file ui_mods.c.
{
     int     numdirs;
     char    dirlist[2048];
     char    *dirptr;
   char  *descptr;
     int     i;
     int     dirlen;
     s_mods.list.itemnames = (const char **)s_mods.descriptionList;
     s_mods.descriptionPtr = s_mods.description;
     s_mods.fs_gamePtr = s_mods.fs_game;
     // always start off with baseq3
     s_mods.list.numitems = 1;
     s_mods.list.itemnames[0] = s_mods.descriptionList[0] = "Quake III Arena";
     s_mods.fs_gameList[0] = "";
     numdirs = trap_FS_GetFileList( "$modlist", "", dirlist, sizeof(dirlist) );
     dirptr  = dirlist;
     for( i = 0; i < numdirs; i++ ) {
         dirlen = strlen( dirptr ) + 1;
     descptr = dirptr + dirlen;
     UI_Mods_ParseInfos( dirptr, descptr);
     dirptr += dirlen + strlen(descptr) + 1;
     }
     trap_Print( va( "%i mods parsed\n", s_mods.list.numitems ) );
     if (s_mods.list.numitems > MAX_MODS) {
         s_mods.list.numitems = MAX_MODS;
     }
 }
References mods_t::description, mods_t::descriptionList, mods_t::descriptionPtr, mods_t::fs_game, mods_t::fs_gameList, mods_t::fs_gamePtr, menulist_s::itemnames, mods_t::list, MAX_MODS, menulist_s::numitems, s_mods, trap_FS_GetFileList(), trap_Print(), UI_Mods_ParseInfos(), and va().
Referenced by UI_Mods_MenuInit().
UI_Mods_MenuEvent()
static void UI_Mods_MenuEvent (void * ptr, int event) static
Definition at line 71 of file ui_mods.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch ( ((menucommon_s*)ptr)->id ) {
     case ID_GO:
         trap_Cvar_Set( "fs_game", s_mods.fs_gameList[s_mods.list.curvalue] );
         trap_Cmd_ExecuteText( EXEC_APPEND, "vid_restart;" );
         UI_PopMenu();
         break;
     case ID_BACK:
         UI_PopMenu();
         break;
     }
 }
References menulist_s::curvalue, EXEC_APPEND, mods_t::fs_gameList, ID_BACK, ID_GO, mods_t::list, QM_ACTIVATED, s_mods, trap_Cmd_ExecuteText(), trap_Cvar_Set(), and UI_PopMenu().
Referenced by UI_Mods_MenuInit().
UI_Mods_MenuInit()
static void UI_Mods_MenuInit (void) static
Definition at line 152 of file ui_mods.c.
{
     UI_ModsMenu_Cache();
     memset( &s_mods, 0 ,sizeof(mods_t) );
     s_mods.menu.wrapAround = qtrue;
     s_mods.menu.fullscreen = qtrue;
     s_mods.banner.generic.type      = MTYPE_BTEXT;
     s_mods.banner.generic.x         = 320;
     s_mods.banner.generic.y         = 16;
     s_mods.banner.string            = "MODS";
     s_mods.banner.color             = color_white;
     s_mods.banner.style             = UI_CENTER;
     s_mods.framel.generic.type      = MTYPE_BITMAP;
     s_mods.framel.generic.name      = ART_FRAMEL;
     s_mods.framel.generic.flags     = QMF_INACTIVE;
     s_mods.framel.generic.x         = 0;
     s_mods.framel.generic.y         = 78;
     s_mods.framel.width             = 256;
     s_mods.framel.height            = 329;
     s_mods.framer.generic.type      = MTYPE_BITMAP;
     s_mods.framer.generic.name      = ART_FRAMER;
     s_mods.framer.generic.flags     = QMF_INACTIVE;
     s_mods.framer.generic.x         = 376;
     s_mods.framer.generic.y         = 76;
     s_mods.framer.width             = 256;
     s_mods.framer.height            = 334;
     s_mods.back.generic.type        = MTYPE_BITMAP;
     s_mods.back.generic.name        = ART_BACK0;
     s_mods.back.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_mods.back.generic.id          = ID_BACK;
     s_mods.back.generic.callback    = UI_Mods_MenuEvent;
     s_mods.back.generic.x           = 0;
     s_mods.back.generic.y           = 480-64;
     s_mods.back.width               = 128;
     s_mods.back.height              = 64;
     s_mods.back.focuspic            = ART_BACK1;
     s_mods.go.generic.type          = MTYPE_BITMAP;
     s_mods.go.generic.name          = ART_FIGHT0;
     s_mods.go.generic.flags         = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_mods.go.generic.id            = ID_GO;
     s_mods.go.generic.callback      = UI_Mods_MenuEvent;
     s_mods.go.generic.x             = 640;
     s_mods.go.generic.y             = 480-64;
     s_mods.go.width                 = 128;
     s_mods.go.height                = 64;
     s_mods.go.focuspic              = ART_FIGHT1;
     // scan for mods
     s_mods.list.generic.type        = MTYPE_SCROLLLIST;
     s_mods.list.generic.flags       = QMF_PULSEIFFOCUS|QMF_CENTER_JUSTIFY;
     s_mods.list.generic.callback    = UI_Mods_MenuEvent;
     s_mods.list.generic.id          = ID_LIST;
     s_mods.list.generic.x           = 320;
     s_mods.list.generic.y           = 130;
     s_mods.list.width               = 48;
     s_mods.list.height              = 14;
     UI_Mods_LoadMods();
     Menu_AddItem( &s_mods.menu, &s_mods.banner );
     Menu_AddItem( &s_mods.menu, &s_mods.framel );
     Menu_AddItem( &s_mods.menu, &s_mods.framer );
     Menu_AddItem( &s_mods.menu, &s_mods.list );
     Menu_AddItem( &s_mods.menu, &s_mods.back );
     Menu_AddItem( &s_mods.menu, &s_mods.go );
 }
References ART_BACK0, ART_BACK1, ART_FIGHT0, ART_FIGHT1, ART_FRAMEL, ART_FRAMER, mods_t::back, mods_t::banner, menucommon_s::callback, menutext_s::color, color_white, menucommon_s::flags, menubitmap_s::focuspic, mods_t::framel, mods_t::framer, _tag_menuframework::fullscreen, menulist_s::generic, menubitmap_s::generic, menutext_s::generic, mods_t::go, menulist_s::height, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_GO, ID_LIST, mods_t::list, mods_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_SCROLLLIST, menucommon_s::name, QMF_CENTER_JUSTIFY, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, qtrue, s_mods, menutext_s::string, menutext_s::style, menucommon_s::type, UI_CENTER, UI_Mods_LoadMods(), UI_Mods_MenuEvent(), UI_ModsMenu_Cache(), menulist_s::width, menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_ModsMenu().
UI_Mods_ParseInfos()
static void UI_Mods_ParseInfos (char * modDir, char * modDesc) static
Definition at line 95 of file ui_mods.c.
{
     s_mods.fs_gameList[s_mods.list.numitems] = s_mods.fs_gamePtr;
     Q_strncpyz( s_mods.fs_gamePtr, modDir, 16 );
     s_mods.descriptionList[s_mods.list.numitems] = s_mods.descriptionPtr;
     Q_strncpyz( s_mods.descriptionPtr, modDesc, 48 );
     s_mods.list.itemnames[s_mods.list.numitems] = s_mods.descriptionPtr;
     s_mods.descriptionPtr += strlen( s_mods.descriptionPtr ) + 1;
     s_mods.fs_gamePtr += strlen( s_mods.fs_gamePtr ) + 1;
     s_mods.list.numitems++;
 }
References mods_t::descriptionList, mods_t::descriptionPtr, mods_t::fs_gameList, mods_t::fs_gamePtr, menulist_s::itemnames, mods_t::list, menulist_s::numitems, Q_strncpyz(), and s_mods.
Referenced by UI_Mods_LoadMods().
UI_ModsMenu()
void UI_ModsMenu (void)
Definition at line 244 of file ui_mods.c.
{
     UI_Mods_MenuInit();
     UI_PushMenu( &s_mods.menu );
 }
References mods_t::menu, s_mods, UI_Mods_MenuInit(), and UI_PushMenu().
Referenced by Main_MenuEvent().
UI_ModsMenu_Cache()
void UI_ModsMenu_Cache (void)
Definition at line 229 of file ui_mods.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FIGHT0 );
     trap_R_RegisterShaderNoMip( ART_FIGHT1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
References ART_BACK0, ART_BACK1, ART_FIGHT0, ART_FIGHT1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_Mods_MenuInit().
Variable Documentation
s_mods
mods_t s_mods static
Definition at line 63 of file ui_mods.c.
Referenced by UI_Mods_LoadMods(), UI_Mods_MenuEvent(), UI_Mods_MenuInit(), UI_Mods_ParseInfos(), and UI_ModsMenu().