ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/q_math.c File Reference
q_math.c File Reference
#include "q_shared.h"
Functions
int Q_rand (int *seed)
float Q_random (int *seed)
float Q_crandom (int *seed)
signed char ClampChar (int i)
signed short ClampShort (int i)
int DirToByte (vec3_t dir)
void ByteToDir (int b, vec3_t dir)
unsigned ColorBytes3 (float r, float g, float b)
unsigned ColorBytes4 (float r, float g, float b, float a)
float NormalizeColor (const vec3_t in, vec3_t out)
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
void RotateAroundDirection (vec3_t axis[3], float yaw)
void vectoangles (const vec3_t value1, vec3_t angles)
void AnglesToAxis (const vec3_t angles, vec3_t axis[3])
void AxisClear (vec3_t axis[3])
void AxisCopy (vec3_t in[3], vec3_t out[3])
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
void VectorRotate (vec3_t in, vec3_t matrix[3], vec3_t out)
float Q_rsqrt (float number)
float Q_fabs (float f)
float LerpAngle (float from, float to, float frac)
float AngleSubtract (float a1, float a2)
void AnglesSubtract (vec3_t v1, vec3_t v2, vec3_t v3)
float AngleMod (float a)
float AngleNormalize360 (float angle)
float AngleNormalize180 (float angle)
float AngleDelta (float angle1, float angle2)
void SetPlaneSignbits (cplane_t *out)
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s *p)
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
void ClearBounds (vec3_t mins, vec3_t maxs)
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
vec_t VectorNormalize (vec3_t v)
vec_t VectorNormalize2 (const vec3_t v, vec3_t out)
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
void _VectorCopy (const vec3_t in, vec3_t out)
void _VectorScale (const vec3_t in, vec_t scale, vec3_t out)
void Vector4Scale (const vec4_t in, vec_t scale, vec4_t out)
int Q_log2 (int val)
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
void PerpendicularVector (vec3_t dst, const vec3_t src)
int Q_isnan (float x)
float Q_acos (float c)
Variables
vec3_t vec3_origin = { 0,0,0 }
vec3_t axisDefault [3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } }
vec4_t colorBlack = { 0, 0, 0, 1 }
vec4_t colorRed = { 1, 0, 0, 1 }
vec4_t colorGreen = { 0, 1, 0, 1 }
vec4_t colorBlue = { 0, 0, 1, 1 }
vec4_t colorYellow = { 1, 1, 0, 1 }
vec4_t colorMagenta = { 1, 0, 1, 1 }
vec4_t colorCyan = { 0, 1, 1, 1 }
vec4_t colorWhite = { 1, 1, 1, 1 }
vec4_t colorLtGrey = { 0.75, 0.75, 0.75, 1 }
vec4_t colorMdGrey = { 0.5, 0.5, 0.5, 1 }
vec4_t colorDkGrey = { 0.25, 0.25, 0.25, 1 }
vec4_t g_color_table [8]
vec3_t bytedirs [NUMVERTEXNORMALS]
Function Documentation
_DotProduct()
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
Definition at line 854 of file q_math.c.
 {
     return v1[0] * v2[0] + v1[1] * v2[1] + v1[2] * v2[2];
 }
_VectorAdd()
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
Definition at line 866 of file q_math.c.
 {
     out[0] = veca[0] + vecb[0];
     out[1] = veca[1] + vecb[1];
     out[2] = veca[2] + vecb[2];
 }
References state::out.
_VectorCopy()
void _VectorCopy (const vec3_t in, vec3_t out)
Definition at line 873 of file q_math.c.
 {
     out[0] = in[0];
     out[1] = in[1];
     out[2] = in[2];
 }
References in, and state::out.
_VectorMA()
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
Definition at line 846 of file q_math.c.
 {
     vecc[0] = veca[0] + scale * vecb[0];
     vecc[1] = veca[1] + scale * vecb[1];
     vecc[2] = veca[2] + scale * vecb[2];
 }
_VectorScale()
void _VectorScale (const vec3_t in, vec_t scale, vec3_t out)
Definition at line 880 of file q_math.c.
 {
     out[0] = in[0] * scale;
     out[1] = in[1] * scale;
     out[2] = in[2] * scale;
 }
References in, and state::out.
_VectorSubtract()
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
Definition at line 859 of file q_math.c.
 {
     out[0] = veca[0] - vecb[0];
     out[1] = veca[1] - vecb[1];
     out[2] = veca[2] - vecb[2];
 }
References state::out.
AddPointToBounds()
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 735 of file q_math.c.
 {
     if (v[0] < mins[0]) {
         mins[0] = v[0];
     }
     if (v[0] > maxs[0]) {
         maxs[0] = v[0];
     }
     if (v[1] < mins[1]) {
         mins[1] = v[1];
     }
     if (v[1] > maxs[1]) {
         maxs[1] = v[1];
     }
     if (v[2] < mins[2]) {
         mins[2] = v[2];
     }
     if (v[2] > maxs[2]) {
         maxs[2] = v[2];
     }
 }
Referenced by CM_GeneratePatchCollide(), LoadDrawVertToSrfVert(), R_CreateSurfaceGridMesh(), R_CullLocalBox(), R_LoadIQM(), R_MarkFragments(), R_RenderSunShadowMaps(), RE_AddPolyToScene(), and Think_SpawnNewDoorTrigger().
AngleDelta()
float AngleDelta (float angle1, float angle2)
Definition at line 637 of file q_math.c.
 {
     return AngleNormalize180(angle1 - angle2);
 }
References AngleNormalize180().
AngleMod()
float AngleMod (float a)
Definition at line 593 of file q_math.c.
 {
     a = (360.0 / 65536) * ((int)(a * (65536 / 360.0)) & 65535);
     return a;
 }
References a.
Referenced by BotAI(), BotAimAtEnemy(), BotChangeViewAngle(), BotChangeViewAngles(), BotMapScripts(), BotUpdateInput(), CG_MachinegunSpinAngle(), CG_PlayerAngles(), CG_SwingAngles(), InFieldOfVision(), UI_MachinegunSpinAngle(), UI_PlayerAngles(), and UI_SwingAngles().
AngleNormalize180()
float AngleNormalize180 (float angle)
Definition at line 620 of file q_math.c.
 {
     angle = AngleNormalize360(angle);
     if (angle > 180.0) {
         angle -= 360.0;
     }
     return angle;
 }
References AngleNormalize360().
Referenced by AngleDelta(), and BG_TouchJumpPad().
AngleNormalize360()
float AngleNormalize360 (float angle)
Definition at line 607 of file q_math.c.
 {
     return (360.0 / 65536) * ((int)(angle * (65536 / 360.0)) & 65535);
 }
References int().
Referenced by AngleNormalize180().
AnglesSubtract()
void AnglesSubtract (vec3_t v1, vec3_t v2, vec3_t v3)
Definition at line 585 of file q_math.c.
 {
     v3[0] = AngleSubtract(v1[0], v2[0]);
     v3[1] = AngleSubtract(v1[1], v2[1]);
     v3[2] = AngleSubtract(v1[2], v2[2]);
 }
References AngleSubtract().
Referenced by CG_PlayerAngles(), and UI_PlayerAngles().
AnglesToAxis()
void AnglesToAxis (const vec3_t angles, vec3_t axis[3])
Definition at line 424 of file q_math.c.
 {
     vec3_t    right;
     // angle vectors returns "right" instead of "y axis"
     AngleVectors(angles, axis[0], right, axis[2]);
     VectorSubtract(vec3_origin, right, axis[1]);
 }
References AngleVectors(), right, vec3_origin, and VectorSubtract.
Referenced by CG_AddFragment(), CG_AddPacketEntities(), CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_CalcViewValues(), CG_Draw3DModel(), CG_General(), CG_Item(), CG_LightningBolt(), CG_MachineGunEjectBrass(), CG_Missile(), CG_Mover(), CG_PlasmaTrail(), CG_Player(), CG_PlayerAngles(), CG_PlayerFlag(), CG_ScorePlum(), CG_ShotgunEjectBrass(), CG_TeamBase(), CG_TestModel_f(), CG_TrailItem(), Item_Model_Paint(), Main_MenuDraw(), UI_DrawPlayer(), and UI_PlayerAngles().
AngleSubtract()
float AngleSubtract (float a1, float a2)
Definition at line 570 of file q_math.c.
 {
     float    a;
     a = a1 - a2;
     while (a > 180) {
         a -= 360;
     }
     while (a < -180) {
         a += 360;
     }
     return a;
 }
References a.
Referenced by AnglesSubtract(), CG_SwingAngles(), and UI_SwingAngles().
AngleVectors()
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
Definition at line 956 of file q_math.c.
 {
     float        angle;
     static float        sr, sp, sy, cr, cp, cy;
     // static to help MS compiler fp bugs
     angle = angles[YAW] * (M_PI * 2 / 360);
     sy = sin(angle);
     cy = cos(angle);
     angle = angles[PITCH] * (M_PI * 2 / 360);
     sp = sin(angle);
     cp = cos(angle);
     angle = angles[ROLL] * (M_PI * 2 / 360);
     sr = sin(angle);
     cr = cos(angle);
     if (forward) {
         forward[0] = cp * cy;
         forward[1] = cp * sy;
         forward[2] = -sp;
     }
     if (right) {
         right[0] = (-1 * sr * sp * cy + -1 * cr * -sy);
         right[1] = (-1 * sr * sp * sy + -1 * cr * cy);
         right[2] = -1 * sr * cp;
     }
     if (up) {
         up[0] = (cr * sp * cy + -sr * -sy);
         up[1] = (cr * sp * sy + -sr * cy);
         up[2] = cr * cp;
     }
 }
References forward, M_PI, PITCH, right, ROLL, up, and YAW.
Referenced by AAS_Reachability_Teleport(), AAS_SetMovedir(), AAS_WeaponJumpZVelocity(), AnglesToAxis(), BotAIBlocked(), BotCheckAttack(), BotExportTest(), BotGetLongTermGoal(), BotInputToUserCommand(), BotRandomMove(), BotSetMovedir(), CG_AddParticles(), CG_AddParticleToScene(), CG_CalcMuzzlePoint(), CG_CreateRotationMatrix(), CG_DamageFeedback(), CG_GrappleTrail(), CG_LightningBolt(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_ParticleBloodCloud(), CG_ParticleDust(), CheckGauntletAttack(), CM_TransformedPointContents(), CreateRotationMatrix(), Drop_Item(), FireWeapon(), G_CreateRotationMatrix(), G_SetMovedir(), G_TryPushingProxMine(), Pickup_Powerup(), PmoveSingle(), PodiumPlacementThink(), SpawnModelOnVictoryPad(), SpawnPodium(), SV_GameSystemCalls(), TeleportPlayer(), UI_MovedirAdjustment(), and ValidBloodPool().
AxisClear()
void AxisClear (vec3_t axis[3])
Definition at line 433 of file q_math.c.
 {
     axis[0][0] = 1;
     axis[0][1] = 0;
     axis[0][2] = 0;
     axis[1][0] = 0;
     axis[1][1] = 1;
     axis[1][2] = 0;
     axis[2][0] = 0;
     axis[2][1] = 0;
     axis[2][2] = 1;
 }
Referenced by CG_Beam(), CG_Draw3DModel(), CG_GrappleTrail(), CG_MakeExplosion(), CG_RailTrail(), CG_SpawnEffect(), Item_Model_Paint(), Main_MenuDraw(), R_IQMLerpTag(), R_LerpTag(), and UI_DrawPlayer().
AxisCopy()
void AxisCopy (vec3_t in[3], vec3_t out[3])
Definition at line 446 of file q_math.c.
 {
     VectorCopy(in[0], out[0]);
     VectorCopy(in[1], out[1]);
     VectorCopy(in[2], out[2]);
 }
References in, state::out, and VectorCopy.
Referenced by CG_Item(), CG_LaunchExplode(), CG_LaunchGib(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), CG_ShotgunEjectBrass(), and R_GetPortalOrientations().
BoundsIntersect()
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
Definition at line 759 of file q_math.c.
 {
     if (maxs[0] < mins2[0] ||
         maxs[1] < mins2[1] ||
         maxs[2] < mins2[2] ||
         mins[0] > maxs2[0] ||
         mins[1] > maxs2[1] ||
         mins[2] > maxs2[2]) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoundsIntersectPoint()
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
Definition at line 789 of file q_math.c.
 {
     if (origin[0] > maxs[0] ||
         origin[0] < mins[0] ||
         origin[1] > maxs[1] ||
         origin[1] < mins[1] ||
         origin[2] > maxs[2] ||
         origin[2] < mins[2]) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoundsIntersectSphere()
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
Definition at line 774 of file q_math.c.
 {
     if (origin[0] - radius > maxs[0] ||
         origin[0] + radius < mins[0] ||
         origin[1] - radius > maxs[1] ||
         origin[1] + radius < mins[1] ||
         origin[2] - radius > maxs[2] ||
         origin[2] + radius < mins[2]) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoxOnPlaneSide()
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s * p)
Definition at line 673 of file q_math.c.
 {
     float    dist[2];
     int        sides, b, i;
     // fast axial cases
     if (p->type < 3) {
         if (p->dist <= emins[p->type])
             return 1;
         if (p->dist >= emaxs[p->type])
             return 2;
         return 3;
     }
     // general case
     dist[0] = dist[1] = 0;
     if (p->signbits < 8) // >= 8: default case is original code (dist[0]=dist[1]=0)
     {
         for (i = 0; i < 3; i++) {
             b = (p->signbits >> i) & 1;
             dist[b] += p->normal[i] * emaxs[i];
             dist[!b] += p->normal[i] * emins[i];
         }
     }
     sides = 0;
     if (dist[0] >= p->dist)
         sides = 1;
     if (dist[1] < p->dist)
         sides |= 2;
     return sides;
 }
References cplane_s::dist, cplane_s::normal, cplane_s::signbits, and cplane_s::type.
Referenced by CM_BoxLeafnums_r(), R_BoxSurfaces_r(), R_CullBox(), R_PshadowSurface(), and R_RecursiveWorldNode().
ByteToDir()
void ByteToDir (int b, vec3_t dir)
Definition at line 214 of file q_math.c.
 {
     if (b < 0 || b >= NUMVERTEXNORMALS) {
         VectorCopy(vec3_origin, dir);
         return;
     }
     VectorCopy(bytedirs[b], dir);
 }
References bytedirs, NUMVERTEXNORMALS, vec3_origin, and VectorCopy.
Referenced by CG_EntityEvent(), and CG_Portal().
ClampChar()
signed char ClampChar (int i)
Definition at line 168 of file q_math.c.
 {
     if (i < -128) {
         return -128;
     }
     if (i > 127) {
         return 127;
     }
     return i;
 }
Referenced by CL_JoystickMove(), CL_KeyMove(), and CL_MouseMove().
ClampShort()
signed short ClampShort (int i)
Definition at line 179 of file q_math.c.
 {
     if (i < -32768) {
         return -32768;
     }
     if (i > 0x7fff) {
         return 0x7fff;
     }
     return i;
 }
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 729 of file q_math.c.
 {
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
Referenced by CM_GeneratePatchCollide(), ParseFace(), ParseTriSurf(), R_AddWorldSurfaces(), R_CreateSurfaceGridMesh(), R_CullLocalBox(), R_LoadIQM(), R_MarkFragments(), and R_RenderSunShadowMaps().
ColorBytes3()
unsigned ColorBytes3 (float r, float g, float b)
Definition at line 224 of file q_math.c.
 {
     unsigned    i;
     ((byte*)&i)[0] = r * 255;
     ((byte*)&i)[1] = g * 255;
     ((byte*)&i)[2] = b * 255;
     return i;
 }
ColorBytes4()
unsigned ColorBytes4 (float r, float g, float b, float a)
Definition at line 235 of file q_math.c.
 {
     unsigned    i;
     ((byte*)&i)[0] = r * 255;
     ((byte*)&i)[1] = g * 255;
     ((byte*)&i)[2] = b * 255;
     ((byte*)&i)[3] = a * 255;
     return i;
 }
References a.
Referenced by R_LoadFogs().
DirToByte()
int DirToByte (vec3_t dir)
Definition at line 192 of file q_math.c.
 {
     int        i, best;
     float    d, bestd;
     if (!dir) {
         return 0;
     }
     bestd = 0;
     best = 0;
     for (i = 0; i < NUMVERTEXNORMALS; i++) {
         d = DotProduct(dir, bytedirs[i]);
         if (d > bestd) {
             bestd = d;
             best = i;
         }
     }
     return best;
 }
References bytedirs, DotProduct, and NUMVERTEXNORMALS.
Referenced by Bullet_Fire(), CheckGauntletAttack(), G_ExplodeMissile(), G_MissileImpact(), locateCamera(), Weapon_LightningFire(), and weapon_railgun_fire().
LerpAngle()
float LerpAngle (float from, float to, float frac)
Definition at line 547 of file q_math.c.
 {
     float    a;
     if (to - from > 180) {
         to -= 360;
     }
     if (to - from < -180) {
         to += 360;
     }
     a = from + frac * (to - from);
     return a;
 }
References a.
Referenced by CG_InterpolateEntityPosition(), and CG_InterpolatePlayerState().
MakeNormalVectors()
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
Definition at line 484 of file q_math.c.
 {
     float        d;
     // this rotate and negate guarantees a vector
     // not colinear with the original
     right[1] = -forward[0];
     right[2] = forward[1];
     right[0] = forward[2];
     d = DotProduct(right, forward);
     VectorMA(right, -d, forward, right);
     VectorNormalize(right);
     CrossProduct(right, forward, up);
 }
References CrossProduct(), DotProduct, forward, right, up, VectorMA, and VectorNormalize().
Referenced by RB_SurfaceRailRings().
MatrixMultiply()
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
Definition at line 933 of file q_math.c.
 {
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
         in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
         in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
         in1[0][2] * in2[2][2];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
         in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
         in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
         in1[1][2] * in2[2][2];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
         in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
         in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
         in1[2][2] * in2[2][2];
 }
References state::out.
Referenced by CG_AddPlayerWeapon(), CG_PositionEntityOnTag(), CG_PositionRotatedEntityOnTag(), RotatePointAroundVector(), SV_GameSystemCalls(), UI_PositionEntityOnTag(), and UI_PositionRotatedEntityOnTag().
NormalizeColor()
float NormalizeColor (const vec3_t in, vec3_t out)
Definition at line 247 of file q_math.c.
 {
     float    max;
     max = in[0];
     if (in[1] > max) {
         max = in[1];
     }
     if (in[2] > max) {
         max = in[2];
     }
     if (!max) {
         VectorClear(out);
     } else {
         out[0] = in[0] / max;
         out[1] = in[1] / max;
         out[2] = in[2] / max;
     }
     return max;
 }
References in, state::out, and VectorClear.
PerpendicularVector()
void PerpendicularVector (vec3_t dst, const vec3_t src)
Definition at line 992 of file q_math.c.
 {
     int    pos;
     int i;
     float minelem = 1.0F;
     vec3_t tempvec;
     /*
     ** find the smallest magnitude axially aligned vector
     */
     for (pos = 0, i = 0; i < 3; i++) {
         if (fabs(src[i]) < minelem) {
             pos = i;
             minelem = fabs(src[i]);
         }
     }
     tempvec[0] = tempvec[1] = tempvec[2] = 0.0F;
     tempvec[pos] = 1.0F;
     /*
     ** project the point onto the plane defined by src
     */
     ProjectPointOnPlane(dst, tempvec, src);
     /*
     ** normalize the result
     */
     VectorNormalize(dst);
 }
References ProjectPointOnPlane(), and VectorNormalize().
Referenced by CG_ImpactMark(), CG_Portal(), CG_RailTrail(), CG_ShotgunPattern(), R_GetPortalOrientations(), RB_DrawSun(), RB_SurfaceBeam(), RotateAroundDirection(), RotatePointAroundVector(), ShotgunPattern(), SV_GameSystemCalls(), and Use_Shooter().
PlaneFromPoints()
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
Definition at line 278 of file q_math.c.
 {
     vec3_t    d1, d2;
     VectorSubtract(b, a, d1);
     VectorSubtract(c, a, d2);
     CrossProduct(d2, d1, plane);
     if (VectorNormalize(plane) == 0) {
         return qfalse;
     }
     plane[3] = DotProduct(a, plane);
     return qtrue;
 }
References a, CrossProduct(), DotProduct, qfalse, qtrue, VectorNormalize(), and VectorSubtract.
Referenced by R_PlaneForSurface().
ProjectPointOnPlane()
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
Definition at line 453 of file q_math.c.
 {
     float d;
     vec3_t n;
     float inv_denom;
     inv_denom = DotProduct(normal, normal);
 #ifndef Q3_VM
     assert(Q_fabs(inv_denom) != 0.0f); // zero vectors get here
 #endif
     inv_denom = 1.0f / inv_denom;
     d = DotProduct(normal, p) * inv_denom;
     n[0] = normal[0] * inv_denom;
     n[1] = normal[1] * inv_denom;
     n[2] = normal[2] * inv_denom;
     dst[0] = p[0] - d * n[0];
     dst[1] = p[1] - d * n[1];
     dst[2] = p[2] - d * n[2];
 }
References DotProduct, and Q_fabs().
Referenced by PerpendicularVector().
Q_acos()
float Q_acos (float c)
Definition at line 1054 of file q_math.c.
 {
     float angle;
     angle = acos(c);
     if (angle > M_PI) {
         return (float)M_PI;
     }
     if (angle < -M_PI) {
         return (float)M_PI;
     }
     return angle;
 }
References M_PI.
Referenced by CL_CgameSystemCalls(), and R_InitSkyTexCoords().
Q_crandom()
float Q_crandom (int * seed)
Definition at line 161 of file q_math.c.
 {
     return 2.0 * (Q_random(seed) - 0.5);
 }
References Q_random().
Referenced by CG_ShotgunPattern(), and ShotgunPattern().
Q_fabs()
float Q_fabs (float f)
Definition at line 530 of file q_math.c.
 {
     floatint_t fi;
     fi.f = f;
     fi.i &= 0x7FFFFFFF;
     return fi.f;
 }
References floatint_t::f, and floatint_t::i.
Referenced by ProjectPointOnPlane(), and UI_MovedirAdjustment().
Q_isnan()
int Q_isnan (float x)
Definition at line 1029 of file q_math.c.
 {
     floatint_t fi;
     fi.f = x;
     fi.ui &= 0x7FFFFFFF;
     fi.ui = 0x7F800000 - fi.ui;
     return (int)((unsigned int)fi.ui >> 31);
 }
References floatint_t::f, int(), and floatint_t::ui.
Referenced by RE_AddRefEntityToScene().
Q_log2()
int Q_log2 (int val)
Definition at line 896 of file q_math.c.
 {
     int answer;
     answer = 0;
     while ((val >>= 1) != 0) {
         answer++;
     }
     return answer;
 }
Q_rand()
int Q_rand (int * seed)
Definition at line 150 of file q_math.c.
 {
     *seed = (69069U * *seed + 1U);
     return *seed;
 }
Referenced by Q_random().
Q_random()
float Q_random (int * seed)
Definition at line 156 of file q_math.c.
 {
     return (Q_rand(seed) & 0xffff) / (float)0x10000;
 }
References Q_rand().
Referenced by CG_SmokePuff(), and Q_crandom().
Q_rsqrt()
float Q_rsqrt (float number)
Definition at line 514 of file q_math.c.
 {
     floatint_t t;
     float x2, y;
     const float threehalfs = 1.5F;
     x2 = number * 0.5F;
     t.f = number;
     t.i = 0x5f3759df - (t.i >> 1);               // what the fuck?
     y = t.f;
     y = y * (threehalfs - (x2 * y * y));   // 1st iteration
 //    y  = y * ( threehalfs - ( x2 * y * y ) );   // 2nd iteration, this can be removed
     return y;
 }
References t.
Referenced by VectorNormalizeFast().
RadiusFromBounds()
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
Definition at line 713 of file q_math.c.
 {
     int        i;
     vec3_t    corner;
     float    a, b;
     for (i = 0; i < 3; i++) {
         a = fabs(mins[i]);
         b = fabs(maxs[i]);
         corner[i] = a > b ? a : b;
     }
     return VectorLength(corner);
 }
References a, and VectorLength().
Referenced by BotImport_BSPModelMinsMaxsOrigin(), G_MoverPush(), R_ComputeLOD(), and SV_LinkEntity().
RotateAroundDirection()
void RotateAroundDirection (vec3_t axis[3], float yaw)
Definition at line 362 of file q_math.c.
 {
     // create an arbitrary axis[1]
     PerpendicularVector(axis[1], axis[0]);
     // rotate it around axis[0] by yaw
     if (yaw) {
         vec3_t    temp;
         VectorCopy(axis[1], temp);
         RotatePointAroundVector(axis[1], axis[0], temp, yaw);
     }
     // cross to get axis[2]
     CrossProduct(axis[0], axis[1], axis[2]);
 }
References CrossProduct(), PerpendicularVector(), RotatePointAroundVector(), and VectorCopy.
Referenced by CG_MakeExplosion(), and CG_Missile().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 300 of file q_math.c.
 {
     float    m[3][3];
     float    im[3][3];
     float    zrot[3][3];
     float    tmpmat[3][3];
     float    rot[3][3];
     int    i;
     vec3_t vr, vup, vf;
     float    rad;
     vf[0] = dir[0];
     vf[1] = dir[1];
     vf[2] = dir[2];
     PerpendicularVector(vr, dir);
     CrossProduct(vr, vf, vup);
     m[0][0] = vr[0];
     m[1][0] = vr[1];
     m[2][0] = vr[2];
     m[0][1] = vup[0];
     m[1][1] = vup[1];
     m[2][1] = vup[2];
     m[0][2] = vf[0];
     m[1][2] = vf[1];
     m[2][2] = vf[2];
     memcpy(im, m, sizeof(im));
     im[0][1] = m[1][0];
     im[0][2] = m[2][0];
     im[1][0] = m[0][1];
     im[1][2] = m[2][1];
     im[2][0] = m[0][2];
     im[2][1] = m[1][2];
     memset(zrot, 0, sizeof(zrot));
     zrot[0][0] = zrot[1][1] = zrot[2][2] = 1.0F;
     rad = DEG2RAD(degrees);
     zrot[0][0] = cos(rad);
     zrot[0][1] = sin(rad);
     zrot[1][0] = -sin(rad);
     zrot[1][1] = cos(rad);
     MatrixMultiply(m, zrot, tmpmat);
     MatrixMultiply(tmpmat, im, rot);
     for (i = 0; i < 3; i++) {
         dst[i] = rot[i][0] * point[0] + rot[i][1] * point[1] + rot[i][2] * point[2];
     }
 }
References CrossProduct(), DEG2RAD, m, MatrixMultiply(), PerpendicularVector(), and vup.
Referenced by CG_ImpactMark(), CG_RailTrail(), R_GetPortalOrientations(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), and RotateAroundDirection().
SetPlaneSignbits()
void SetPlaneSignbits (cplane_t * out)
Definition at line 651 of file q_math.c.
 {
     int    bits, j;
     // for fast box on planeside test
     bits = 0;
     for (j = 0; j < 3; j++) {
         if (out->normal[j] < 0) {
             bits |= 1 << j;
         }
     }
     out->signbits = bits;
 }
References bits(), and state::out.
Referenced by CM_InitBoxHull(), ParseFace(), R_RenderPshadowMaps(), R_SetupFrustum(), and R_SetupProjectionOrtho().
vectoangles()
void vectoangles (const vec3_t value1, vec3_t angles)
Definition at line 382 of file q_math.c.
 {
     float    forward;
     float    yaw, pitch;
     if (value1[1] == 0 && value1[0] == 0) {
         yaw = 0;
         if (value1[2] > 0) {
             pitch = 90;
         } else {
             pitch = 270;
         }
     } else {
         if (value1[0]) {
             yaw = (atan2(value1[1], value1[0]) * 180 / M_PI);
         } else if (value1[1] > 0) {
             yaw = 90;
         } else {
             yaw = 270;
         }
         if (yaw < 0) {
             yaw += 360;
         }
         forward = sqrt(value1[0] * value1[0] + value1[1] * value1[1]);
         pitch = (atan2(value1[2], forward) * 180 / M_PI);
         if (pitch < 0) {
             pitch += 360;
         }
     }
     angles[PITCH] = -pitch;
     angles[YAW] = yaw;
     angles[ROLL] = 0;
 }
References forward, M_PI, PITCH, ROLL, and YAW.
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), BG_TouchJumpPad(), BotAimAtEnemy(), BotCheckAttack(), BotClearPath(), BotEntityVisible(), BotFindEnemy(), BotGetLongTermGoal(), BotLongTermGoal(), BotMapScripts(), CG_AddParticles(), CG_AddParticleToScene(), CG_ParticleBloodCloud(), CG_ParticleDust(), FindIntermissionPoint(), G_MissileImpact(), P_DamageFeedback(), PodiumPlacementThink(), SpawnModelOnVictoryPad(), and ValidBloodPool().
Vector4Scale()
void Vector4Scale (const vec4_t in, vec_t scale, vec4_t out)
Definition at line 887 of file q_math.c.
 {
     out[0] = in[0] * scale;
     out[1] = in[1] * scale;
     out[2] = in[2] * scale;
     out[3] = in[3] * scale;
 }
References in, and state::out.
VectorNormalize()
vec_t VectorNormalize (vec3_t v)
Definition at line 804 of file q_math.c.
 {
     // NOTE: TTimo - Apple G4 altivec source uses double?
     float    length, ilength;
     length = v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
     if (length) {
         /* writing it this way allows gcc to recognize that rsqrt can be used */
         ilength = 1 / (float)sqrt(length);
         /* sqrt(length) = length * (1 / sqrt(length)) */
         length *= ilength;
         v[0] *= ilength;
         v[1] *= ilength;
         v[2] *= ilength;
     }
     return length;
 }
Referenced by AAS_ClientMovementPrediction(), AAS_DrawArrow(), AAS_GetJumpPadInfo(), AAS_JumpReachRunStart(), AAS_NearbySolidOrGap(), AAS_ProjectPointOntoVector(), AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_WalkOffLedge(), AAS_ShowReachability(), AAS_TestMovementPrediction(), AAS_TraceClientBBox(), AAS_WeaponJumpZVelocity(), AimAtTarget(), Autosprite2Deform(), BotAddToTarget(), BotAIBlocked(), BotAimAtEnemy(), BotAirControl(), BotAttackMove(), BotCheckBarrierJump(), BotFinishTravel_Elevator(), BotFinishTravel_FuncBobbing(), BotFinishTravel_Jump(), BotFinishTravel_JumpPad(), BotFinishTravel_Walk(), BotFinishTravel_WalkOffLedge(), BotFinishTravel_WeaponJump(), BotGetLongTermGoal(), BotImport_DebugLineShow(), BotMoveInGoalArea(), BotRoamGoal(), BotSwimInDirection(), BotTravel_BarrierJump(), BotTravel_BFGJump(), BotTravel_Crouch(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotTravel_Jump(), BotTravel_Ladder(), BotTravel_RocketJump(), BotTravel_Swim(), BotTravel_Teleport(), BotTravel_Walk(), BotTravel_WalkOffLedge(), BotTravel_WaterJump(), BotWalkInDirection(), CG_AddScorePlum(), CG_BubbleTrail(), CG_LightningBolt(), CG_Player(), CG_PlayerAngles(), CG_PlayerFlag(), CG_RailTrail(), CG_ShotgunFire(), CG_Tracer(), CM_AddFacetBevels(), CM_PlaneFromPoints(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), DebugLine(), fire_bfg(), fire_grapple(), fire_grenade(), fire_plasma(), fire_rocket(), G_BounceProjectile(), G_Damage(), G_MissileImpact(), locateCamera(), MakeNormalVectors(), ParseShader(), PerpendicularVector(), Pickup_Powerup(), PlaneFromPoints(), PM_Accelerate(), PM_AirMove(), PM_CheckWaterJump(), PM_DeadMove(), PM_FlyMove(), PM_GrappleMove(), PM_NoclipMove(), PM_SlideMove(), PM_WalkMove(), PM_WaterMove(), R_CalcTangentSpace(), R_CalcTangentVectors(), R_InitSkyTexCoords(), R_LerpTag(), R_LoadMD3(), R_RenderPshadowMaps(), R_RenderSunShadowMaps(), R_SetupEntityLighting(), R_SubdividePatchToGrid(), RaySphereIntersections(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RE_LoadWorldMap(), S_SpatializeOrigin(), target_laser_think(), Use_Shooter(), weapon_grenadelauncher_fire(), and Weapon_LightningFire().
VectorNormalize2()
vec_t VectorNormalize2 (const vec3_t v, vec3_t out)
Definition at line 824 of file q_math.c.
 {
     float    length, ilength;
     length = v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
     if (length) {
         /* writing it this way allows gcc to recognize that rsqrt can be used */
         ilength = 1 / (float)sqrt(length);
         /* sqrt(length) = length * (1 / sqrt(length)) */
         length *= ilength;
         out[0] = v[0] * ilength;
         out[1] = v[1] * ilength;
         out[2] = v[2] * ilength;
     } else {
         VectorClear(out);
     }
     return length;
 }
References state::out, and VectorClear.
Referenced by AddWindingToConvexHull(), BaseWindingForPlane(), BotWalkInDirection(), CG_Grapple(), CG_ImpactMark(), CG_Missile(), CG_ShotgunPattern(), CheckWinding(), MakeMeshNormals(), PM_SlideMove(), R_MarkFragments(), R_SetupEntityLightingGrid(), RemoveColinearPoints(), RGBAtoNormal(), ShotgunPattern(), and WindingPlane().
VectorRotate()
void VectorRotate (vec3_t in, vec3_t matrix[3], vec3_t out)
Definition at line 501 of file q_math.c.
 {
     out[0] = DotProduct(in, matrix[0]);
     out[1] = DotProduct(in, matrix[1]);
     out[2] = DotProduct(in, matrix[2]);
 }
References DotProduct, in, and state::out.
Referenced by S_SpatializeOrigin().
Variable Documentation
axisDefault
vec3_t axisDefault[3] = { { 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 } }
Definition at line 35 of file q_math.c.
Referenced by CG_LaunchExplode(), CG_LaunchGib(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), and CG_ShotgunEjectBrass().
bytedirs
vec3_t bytedirs[NUMVERTEXNORMALS]
Definition at line 63 of file q_math.c.
Referenced by ByteToDir(), and DirToByte().
colorBlack
vec4_t colorBlack = { 0, 0, 0, 1 }
Definition at line 38 of file q_math.c.
Referenced by ServerOptions_LevelshotDraw(), StartServer_LevelshotDraw(), Text_Paint(), Text_PaintWithCursor(), UI_DrawTextBox(), and UI_SaveConfigMenu_SavenameDraw().
colorBlue
vec4_t colorBlue = { 0, 0, 1, 1 }
Definition at line 41 of file q_math.c.
colorCyan
vec4_t colorCyan = { 0, 1, 1, 1 }
Definition at line 44 of file q_math.c.
colorDkGrey
vec4_t colorDkGrey = { 0.25, 0.25, 0.25, 1 }
Definition at line 48 of file q_math.c.
colorGreen
vec4_t colorGreen = { 0, 1, 0, 1 }
Definition at line 40 of file q_math.c.
colorLtGrey
vec4_t colorLtGrey = { 0.75, 0.75, 0.75, 1 }
Definition at line 46 of file q_math.c.
colorMagenta
vec4_t colorMagenta = { 1, 0, 1, 1 }
Definition at line 43 of file q_math.c.
colorMdGrey
vec4_t colorMdGrey = { 0.5, 0.5, 0.5, 1 }
Definition at line 47 of file q_math.c.
Referenced by Bitmap_Draw(), and Signup_MenuInit().
colorRed
vec4_t colorRed = { 1, 0, 0, 1 }
Definition at line 39 of file q_math.c.
Referenced by Login_MenuInit(), PlayerModel_MenuInit(), Rankings_MenuInit(), RankStatus_MenuInit(), RB_SurfaceBeam(), Signup_MenuInit(), TeamMain_MenuInit(), UI_BotSelectMenu_Init(), UI_Refresh(), and UI_SaveConfigMenu_SavenameDraw().
colorWhite
vec4_t colorWhite = { 1, 1, 1, 1 }
Definition at line 45 of file q_math.c.
Referenced by CG_DrawInformation(), CG_DrawOldScoreboard(), CG_DrawWarmup(), Controls_DrawKeyBinding(), Controls_StatusBar(), FBO_BlitFromTexture(), Menu_Draw(), RB_DrawSun(), RB_InstantQuad(), RE_SetColor(), RE_StretchRaw(), ServerOptions_StatusBar(), UI_DisplayDownloadInfo(), UI_DrawConnectScreen(), UI_DrawPlayer(), and UI_DrawTextBox().
colorYellow
vec4_t colorYellow = { 1, 1, 0, 1 }
Definition at line 42 of file q_math.c.
Referenced by Menu_Draw().
g_color_table
vec4_t g_color_table[8]
Initial value:
=
{
{0.0, 0.0, 0.0, 1.0},
{1.0, 0.0, 0.0, 1.0},
{0.0, 1.0, 0.0, 1.0},
{1.0, 1.0, 0.0, 1.0},
{0.0, 0.0, 1.0, 1.0},
{0.0, 1.0, 1.0, 1.0},
{1.0, 0.0, 1.0, 1.0},
{1.0, 1.0, 1.0, 1.0},
}
Definition at line 50 of file q_math.c.
Referenced by CG_DrawLagometer(), CG_DrawStringExt(), CG_Text_Paint_Limit(), CON_ColorCharToAttrib(), Con_DrawNotify(), Con_DrawSolidConsole(), PlayerSettings_DrawName(), Rankings_DrawText(), SCR_DrawDebugGraph(), SCR_DrawDemoRecording(), SCR_DrawScreenField(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), and UI_DrawString2().
vec3_origin
vec3_t vec3_origin = { 0,0,0 }
Definition at line 34 of file q_math.c.
Referenced by AAS_JumpReachRunStart(), AddSkyPolygon(), AnglesToAxis(), AutospriteDeform(), BaseWindingForPlane(), BotCheckSnapshot(), ByteToDir(), CanDamage(), CG_AddPlayerWeapon(), CG_BloodTrail(), CG_ClipMoveToEntities(), CG_DamageFeedback(), CG_EntityEffects(), CG_Grapple(), CG_HasteTrail(), CG_Item(), CG_LightningBolt(), CG_PlayerPowerups(), CG_Portal(), CG_ScanForCrosshairEntity(), CM_AddFacetBevels(), CM_BoxTrace(), CM_DrawDebugSurface(), CM_Trace(), CM_TransformedBoxTrace(), CM_ValidateFacet(), FindIntermissionPoint(), G_TryPushingProxMine(), InitTrigger(), PlayerSettings_DrawPlayer(), PlayerSettings_SetMenuItems(), PM_NoclipMove(), R_GetPortalOrientations(), R_LoadFogs(), R_MirrorViewBySurface(), RB_AddQuadStampExt(), RB_SurfaceSprite(), SelectCTFSpawnPoint(), SelectInitialSpawnPoint(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), SV_PointContents(), SV_Trace(), UI_DrawOpponent(), UI_DrawPlayerModel(), and WindingCenter().