ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/ai_chat.h File Reference
ai_chat.h File Reference
Functions
int BotChat_EnterGame (bot_state_t *bs)
int BotChat_ExitGame (bot_state_t *bs)
int BotChat_StartLevel (bot_state_t *bs)
int BotChat_EndLevel (bot_state_t *bs)
int BotChat_HitTalking (bot_state_t *bs)
int BotChat_HitNoDeath (bot_state_t *bs)
int BotChat_HitNoKill (bot_state_t *bs)
int BotChat_Death (bot_state_t *bs)
int BotChat_Kill (bot_state_t *bs)
int BotChat_EnemySuicide (bot_state_t *bs)
int BotChat_Random (bot_state_t *bs)
float BotChatTime (bot_state_t *bs)
int BotValidChatPosition (bot_state_t *bs)
void BotChatTest (bot_state_t *bs)
Function Documentation
BotChat_Death()
int BotChat_Death (bot_state_t * bs)
Definition at line 550 of file ai_chat.c.
{
     char name[32];
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_DEATH, 0, 1);
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     //if fast chatting is off
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
     }
     if (BotNumActivePlayers() <= 1) return qfalse;
     //
     if (bs->lastkilledby >= 0 && bs->lastkilledby < MAX_CLIENTS)
         EasyClientName(bs->lastkilledby, name, 32);
     else
         strcpy(name, "[world]");
     //
     if (TeamPlayIsOn() && BotSameTeam(bs, bs->lastkilledby)) {
         if (bs->lastkilledby == bs->client) return qfalse;
         BotAI_BotInitialChat(bs, "death_teammate", name, NULL);
         bs->chatto = CHAT_TEAM;
     }
     else
     {
         //teamplay
         if (TeamPlayIsOn()) {
 #ifdef MISSIONPACK
             trap_EA_Command(bs->client, "vtaunt");
 #endif
             return qtrue;
         }
         //
         if (bs->botdeathtype == MOD_WATER)
             BotAI_BotInitialChat(bs, "death_drown", BotRandomOpponentName(bs), NULL);
         else if (bs->botdeathtype == MOD_SLIME)
             BotAI_BotInitialChat(bs, "death_slime", BotRandomOpponentName(bs), NULL);
         else if (bs->botdeathtype == MOD_LAVA)
             BotAI_BotInitialChat(bs, "death_lava", BotRandomOpponentName(bs), NULL);
         else if (bs->botdeathtype == MOD_FALLING)
             BotAI_BotInitialChat(bs, "death_cratered", BotRandomOpponentName(bs), NULL);
         else if (bs->botsuicide || //all other suicides by own weapon
                 bs->botdeathtype == MOD_CRUSH ||
                 bs->botdeathtype == MOD_SUICIDE ||
                 bs->botdeathtype == MOD_TARGET_LASER ||
                 bs->botdeathtype == MOD_TRIGGER_HURT ||
                 bs->botdeathtype == MOD_UNKNOWN)
             BotAI_BotInitialChat(bs, "death_suicide", BotRandomOpponentName(bs), NULL);
         else if (bs->botdeathtype == MOD_TELEFRAG)
             BotAI_BotInitialChat(bs, "death_telefrag", name, NULL);
 #ifdef MISSIONPACK
         else if (bs->botdeathtype == MOD_KAMIKAZE && trap_BotNumInitialChats(bs->cs, "death_kamikaze"))
             BotAI_BotInitialChat(bs, "death_kamikaze", name, NULL);
 #endif
         else {
             if ((bs->botdeathtype == MOD_GAUNTLET ||
                 bs->botdeathtype == MOD_RAILGUN ||
                 bs->botdeathtype == MOD_BFG ||
                 bs->botdeathtype == MOD_BFG_SPLASH) && random() < 0.5) {
                 if (bs->botdeathtype == MOD_GAUNTLET)
                     BotAI_BotInitialChat(bs, "death_gauntlet",
                             name,                                               // 0
                             BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                             NULL);
                 else if (bs->botdeathtype == MOD_RAILGUN)
                     BotAI_BotInitialChat(bs, "death_rail",
                             name,                                               // 0
                             BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                             NULL);
                 else
                     BotAI_BotInitialChat(bs, "death_bfg",
                             name,                                               // 0
                             BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                             NULL);
             }
             //choose between insult and praise
             else if (random() < trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_INSULT, 0, 1)) {
                 BotAI_BotInitialChat(bs, "death_insult",
                             name,                                               // 0
                             BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                             NULL);
             }
             else {
                 BotAI_BotInitialChat(bs, "death_praise",
                             name,                                               // 0
                             BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                             NULL);
             }
         }
         bs->chatto = CHAT_ALL;
     }
     bs->lastchat_time = FloatTime();
     return qtrue;
 }
Referenced by AIEnter_Respawn().
BotChat_EndLevel()
int BotChat_EndLevel (bot_state_t * bs)
Definition at line 488 of file ai_chat.c.
{
     char name[32];
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (BotIsObserver(bs)) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     // teamplay
     if (TeamPlayIsOn())
     {
 #ifdef MISSIONPACK
         if (BotIsFirstInRankings(bs)) {
             trap_EA_Command(bs->client, "vtaunt");
         }
 #endif
         return qtrue;
     }
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_STARTENDLEVEL, 0, 1);
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
     }
     if (BotNumActivePlayers() <= 1) return qfalse;
     //
     if (BotIsFirstInRankings(bs)) {
         BotAI_BotInitialChat(bs, "level_end_victory",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 "[invalid var]",                        // 2
                 BotLastClientInRankings(),              // 3
                 BotMapTitle(),                          // 4
                 NULL);
     }
     else if (BotIsLastInRankings(bs)) {
         BotAI_BotInitialChat(bs, "level_end_lose",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 BotFirstClientInRankings(),             // 2
                 "[invalid var]",                        // 3
                 BotMapTitle(),                          // 4
                 NULL);
     }
     else {
         BotAI_BotInitialChat(bs, "level_end",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 BotFirstClientInRankings(),             // 2
                 BotLastClientInRankings(),              // 3
                 BotMapTitle(),                          // 4
                 NULL);
     }
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by AIEnter_Intermission().
BotChat_EnemySuicide()
int BotChat_EnemySuicide (bot_state_t * bs)
Definition at line 719 of file ai_chat.c.
{
     char name[32];
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     if (BotNumActivePlayers() <= 1) return qfalse;
     //
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_ENEMYSUICIDE, 0, 1);
     //don't chat in teamplay
     if (TeamPlayIsOn()) return qfalse;
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     //if fast chat is off
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
     }
     if (!BotValidChatPosition(bs)) return qfalse;
     //
     if (BotVisibleEnemies(bs)) return qfalse;
     //
     if (bs->enemy >= 0) EasyClientName(bs->enemy, name, 32);
     else strcpy(name, "");
     BotAI_BotInitialChat(bs, "enemy_suicide", name, NULL);
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by AINode_Battle_Fight().
BotChat_EnterGame()
int BotChat_EnterGame (bot_state_t * bs)
Definition at line 388 of file ai_chat.c.
{
     char name[32];
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     //don't chat in teamplay
     if (TeamPlayIsOn()) return qfalse;
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_ENTEREXITGAME, 0, 1);
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
     }
     if (BotNumActivePlayers() <= 1) return qfalse;
     if (!BotValidChatPosition(bs)) return qfalse;
     BotAI_BotInitialChat(bs, "game_enter",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 "[invalid var]",                        // 2
                 "[invalid var]",                        // 3
                 BotMapTitle(),                          // 4
                 NULL);
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by BotDeathmatchAI().
BotChat_ExitGame()
int BotChat_ExitGame (bot_state_t * bs)
Definition at line 421 of file ai_chat.c.
{
     char name[32];
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     //don't chat in teamplay
     if (TeamPlayIsOn()) return qfalse;
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_ENTEREXITGAME, 0, 1);
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
     }
     if (BotNumActivePlayers() <= 1) return qfalse;
     //
     BotAI_BotInitialChat(bs, "game_exit",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 "[invalid var]",                        // 2
                 "[invalid var]",                        // 3
                 BotMapTitle(),                          // 4
                 NULL);
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by BotAIShutdownClient().
BotChat_HitNoDeath()
int BotChat_HitNoDeath (bot_state_t * bs)
Definition at line 792 of file ai_chat.c.
{
     char name[32], *weap;
     float rnd;
     int lasthurt_client;
     aas_entityinfo_t entinfo;
     lasthurt_client = g_entities[bs->client].client->lasthurt_client;
     if (!lasthurt_client) return qfalse;
     if (lasthurt_client == bs->client) return qfalse;
     //
     if (lasthurt_client < 0 || lasthurt_client >= MAX_CLIENTS) return qfalse;
     //
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     if (BotNumActivePlayers() <= 1) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_HITNODEATH, 0, 1);
     //don't chat in teamplay
     if (TeamPlayIsOn()) return qfalse;
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     //if fast chat is off
     if (!bot_fastchat.integer) {
         if (random() > rnd * 0.5) return qfalse;
     }
     if (!BotValidChatPosition(bs)) return qfalse;
     //
     if (BotVisibleEnemies(bs)) return qfalse;
     //
     BotEntityInfo(bs->enemy, &entinfo);
     if (EntityIsShooting(&entinfo)) return qfalse;
     //
     ClientName(lasthurt_client, name, sizeof(name));
     weap = BotWeaponNameForMeansOfDeath(g_entities[bs->client].client->lasthurt_mod);
     //
     BotAI_BotInitialChat(bs, "hit_nodeath", name, weap, NULL);
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by AINode_Battle_Fight().
BotChat_HitNoKill()
int BotChat_HitNoKill (bot_state_t * bs)
Definition at line 837 of file ai_chat.c.
{
     char name[32], *weap;
     float rnd;
     aas_entityinfo_t entinfo;
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     if (BotNumActivePlayers() <= 1) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_HITNOKILL, 0, 1);
     //don't chat in teamplay
     if (TeamPlayIsOn()) return qfalse;
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     //if fast chat is off
     if (!bot_fastchat.integer) {
         if (random() > rnd * 0.5) return qfalse;
     }
     if (!BotValidChatPosition(bs)) return qfalse;
     //
     if (BotVisibleEnemies(bs)) return qfalse;
     //
     BotEntityInfo(bs->enemy, &entinfo);
     if (EntityIsShooting(&entinfo)) return qfalse;
     //
     ClientName(bs->enemy, name, sizeof(name));
     weap = BotWeaponNameForMeansOfDeath(g_entities[bs->enemy].client->lasthurt_mod);
     //
     BotAI_BotInitialChat(bs, "hit_nokill", name, weap, NULL);
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by AINode_Battle_Fight().
BotChat_HitTalking()
int BotChat_HitTalking (bot_state_t * bs)
Definition at line 753 of file ai_chat.c.
{
     char name[32], *weap;
     int lasthurt_client;
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     if (BotNumActivePlayers() <= 1) return qfalse;
     lasthurt_client = g_entities[bs->client].client->lasthurt_client;
     if (!lasthurt_client) return qfalse;
     if (lasthurt_client == bs->client) return qfalse;
     //
     if (lasthurt_client < 0 || lasthurt_client >= MAX_CLIENTS) return qfalse;
     //
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_HITTALKING, 0, 1);
     //don't chat in teamplay
     if (TeamPlayIsOn()) return qfalse;
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     //if fast chat is off
     if (!bot_fastchat.integer) {
         if (random() > rnd * 0.5) return qfalse;
     }
     if (!BotValidChatPosition(bs)) return qfalse;
     //
     ClientName(g_entities[bs->client].client->lasthurt_client, name, sizeof(name));
     weap = BotWeaponNameForMeansOfDeath(g_entities[bs->client].client->lasthurt_mod);
     //
     BotAI_BotInitialChat(bs, "hit_talking", name, weap, NULL);
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by AINode_Stand().
BotChat_Kill()
int BotChat_Kill (bot_state_t * bs)
Definition at line 653 of file ai_chat.c.
{
     char name[32];
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_KILL, 0, 1);
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     //if fast chat is off
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
     }
     if (bs->lastkilledplayer == bs->client) return qfalse;
     if (BotNumActivePlayers() <= 1) return qfalse;
     if (!BotValidChatPosition(bs)) return qfalse;
     //
     if (BotVisibleEnemies(bs)) return qfalse;
     //
     EasyClientName(bs->lastkilledplayer, name, 32);
     //
     bs->chatto = CHAT_ALL;
     if (TeamPlayIsOn() && BotSameTeam(bs, bs->lastkilledplayer)) {
         BotAI_BotInitialChat(bs, "kill_teammate", name, NULL);
         bs->chatto = CHAT_TEAM;
     }
     else
     {
         //don't chat in teamplay
         if (TeamPlayIsOn()) {
 #ifdef MISSIONPACK
             trap_EA_Command(bs->client, "vtaunt");
 #endif
             return qfalse;          // don't wait
         }
         //
         if (bs->enemydeathtype == MOD_GAUNTLET) {
             BotAI_BotInitialChat(bs, "kill_gauntlet", name, NULL);
         }
         else if (bs->enemydeathtype == MOD_RAILGUN) {
             BotAI_BotInitialChat(bs, "kill_rail", name, NULL);
         }
         else if (bs->enemydeathtype == MOD_TELEFRAG) {
             BotAI_BotInitialChat(bs, "kill_telefrag", name, NULL);
         }
 #ifdef MISSIONPACK
         else if (bs->botdeathtype == MOD_KAMIKAZE && trap_BotNumInitialChats(bs->cs, "kill_kamikaze"))
             BotAI_BotInitialChat(bs, "kill_kamikaze", name, NULL);
 #endif
         //choose between insult and praise
         else if (random() < trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_INSULT, 0, 1)) {
             BotAI_BotInitialChat(bs, "kill_insult", name, NULL);
         }
         else {
             BotAI_BotInitialChat(bs, "kill_praise", name, NULL);
         }
     }
     bs->lastchat_time = FloatTime();
     return qtrue;
 }
Referenced by AINode_Battle_Fight().
BotChat_Random()
int BotChat_Random (bot_state_t * bs)
Definition at line 875 of file ai_chat.c.
{
     float rnd;
     char name[32];
     if (bot_nochat.integer) return qfalse;
     if (BotIsObserver(bs)) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     //don't chat when doing something important :)
     if (bs->ltgtype == LTG_TEAMHELP ||
         bs->ltgtype == LTG_TEAMACCOMPANY ||
         bs->ltgtype == LTG_RUSHBASE) return qfalse;
     //
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_RANDOM, 0, 1);
     if (random() > bs->thinktime * 0.1) return qfalse;
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
         if (random() > 0.25) return qfalse;
     }
     if (BotNumActivePlayers() <= 1) return qfalse;
     //
     if (!BotValidChatPosition(bs)) return qfalse;
     //
     if (BotVisibleEnemies(bs)) return qfalse;
     //
     if (bs->lastkilledplayer == bs->client) {
         strcpy(name, BotRandomOpponentName(bs));
     }
     else {
         EasyClientName(bs->lastkilledplayer, name, sizeof(name));
     }
     if (TeamPlayIsOn()) {
 #ifdef MISSIONPACK
         trap_EA_Command(bs->client, "vtaunt");
 #endif
         return qfalse;          // don't wait
     }
     //
     if (random() < trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_MISC, 0, 1)) {
         BotAI_BotInitialChat(bs, "random_misc",
                     BotRandomOpponentName(bs),  // 0
                     name,                       // 1
                     "[invalid var]",            // 2
                     "[invalid var]",            // 3
                     BotMapTitle(),              // 4
                     BotRandomWeaponName(),      // 5
                     NULL);
     }
     else {
         BotAI_BotInitialChat(bs, "random_insult",
                     BotRandomOpponentName(bs),  // 0
                     name,                       // 1
                     "[invalid var]",            // 2
                     "[invalid var]",            // 3
                     BotMapTitle(),              // 4
                     BotRandomWeaponName(),      // 5
                     NULL);
     }
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by AINode_Seek_LTG().
BotChat_StartLevel()
int BotChat_StartLevel (bot_state_t * bs)
Definition at line 454 of file ai_chat.c.
{
     char name[32];
     float rnd;
     if (bot_nochat.integer) return qfalse;
     if (BotIsObserver(bs)) return qfalse;
     if (bs->lastchat_time > FloatTime() - TIME_BETWEENCHATTING) return qfalse;
     //don't chat in teamplay
     if (TeamPlayIsOn()) {
 #ifdef MISSIONPACK
         trap_EA_Command(bs->client, "vtaunt");
 #endif
         return qfalse;
     }
     // don't chat in tournament mode
     if (gametype == GT_TOURNAMENT) return qfalse;
     rnd = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_CHAT_STARTENDLEVEL, 0, 1);
     if (!bot_fastchat.integer) {
         if (random() > rnd) return qfalse;
     }
     if (BotNumActivePlayers() <= 1) return qfalse;
     BotAI_BotInitialChat(bs, "level_start",
                 EasyClientName(bs->client, name, 32),   // 0
                 NULL);
     bs->lastchat_time = FloatTime();
     bs->chatto = CHAT_ALL;
     return qtrue;
 }
Referenced by AINode_Intermission().
BotChatTest()
void BotChatTest (bot_state_t * bs)
Definition at line 957 of file ai_chat.c.
{
     char name[32];
     char *weap;
     int num, i;
     num = trap_BotNumInitialChats(bs->cs, "game_enter");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "game_enter",
                     EasyClientName(bs->client, name, 32),   // 0
                     BotRandomOpponentName(bs),              // 1
                     "[invalid var]",                        // 2
                     "[invalid var]",                        // 3
                     BotMapTitle(),                          // 4
                     NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "game_exit");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "game_exit",
                     EasyClientName(bs->client, name, 32),   // 0
                     BotRandomOpponentName(bs),              // 1
                     "[invalid var]",                        // 2
                     "[invalid var]",                        // 3
                     BotMapTitle(),                          // 4
                     NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "level_start");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "level_start",
                     EasyClientName(bs->client, name, 32),   // 0
                     NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "level_end_victory");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "level_end_victory",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 BotFirstClientInRankings(),             // 2
                 BotLastClientInRankings(),              // 3
                 BotMapTitle(),                          // 4
                 NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "level_end_lose");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "level_end_lose",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 BotFirstClientInRankings(),             // 2
                 BotLastClientInRankings(),              // 3
                 BotMapTitle(),                          // 4
                 NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "level_end");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "level_end",
                 EasyClientName(bs->client, name, 32),   // 0
                 BotRandomOpponentName(bs),              // 1
                 BotFirstClientInRankings(),             // 2
                 BotLastClientInRankings(),              // 3
                 BotMapTitle(),                          // 4
                 NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     EasyClientName(bs->lastkilledby, name, sizeof(name));
     num = trap_BotNumInitialChats(bs->cs, "death_drown");
     for (i = 0; i < num; i++)
     {
         //
         BotAI_BotInitialChat(bs, "death_drown", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_slime");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_slime", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_lava");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_lava", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_cratered");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_cratered", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_suicide");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_suicide", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_telefrag");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_telefrag", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_gauntlet");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_gauntlet",
                 name,                                               // 0
                 BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                 NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_rail");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_rail",
                 name,                                               // 0
                 BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                 NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_bfg");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_bfg",
                 name,                                               // 0
                 BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                 NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_insult");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_insult",
                     name,                                               // 0
                     BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                     NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "death_praise");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "death_praise",
                     name,                                               // 0
                     BotWeaponNameForMeansOfDeath(bs->botdeathtype),     // 1
                     NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     //
     EasyClientName(bs->lastkilledplayer, name, 32);
     //
     num = trap_BotNumInitialChats(bs->cs, "kill_gauntlet");
     for (i = 0; i < num; i++)
     {
         //
         BotAI_BotInitialChat(bs, "kill_gauntlet", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "kill_rail");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "kill_rail", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "kill_telefrag");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "kill_telefrag", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "kill_insult");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "kill_insult", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "kill_praise");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "kill_praise", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "enemy_suicide");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "enemy_suicide", name, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     ClientName(g_entities[bs->client].client->lasthurt_client, name, sizeof(name));
     weap = BotWeaponNameForMeansOfDeath(g_entities[bs->client].client->lasthurt_client);
     num = trap_BotNumInitialChats(bs->cs, "hit_talking");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "hit_talking", name, weap, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "hit_nodeath");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "hit_nodeath", name, weap, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "hit_nokill");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "hit_nokill", name, weap, NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     //
     if (bs->lastkilledplayer == bs->client) {
         strcpy(name, BotRandomOpponentName(bs));
     }
     else {
         EasyClientName(bs->lastkilledplayer, name, sizeof(name));
     }
     //
     num = trap_BotNumInitialChats(bs->cs, "random_misc");
     for (i = 0; i < num; i++)
     {
         //
         BotAI_BotInitialChat(bs, "random_misc",
                     BotRandomOpponentName(bs),  // 0
                     name,                       // 1
                     "[invalid var]",            // 2
                     "[invalid var]",            // 3
                     BotMapTitle(),              // 4
                     BotRandomWeaponName(),      // 5
                     NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
     num = trap_BotNumInitialChats(bs->cs, "random_insult");
     for (i = 0; i < num; i++)
     {
         BotAI_BotInitialChat(bs, "random_insult",
                     BotRandomOpponentName(bs),  // 0
                     name,                       // 1
                     "[invalid var]",            // 2
                     "[invalid var]",            // 3
                     BotMapTitle(),              // 4
                     BotRandomWeaponName(),      // 5
                     NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_ALL);
     }
 }
Referenced by BotAISetupClient().
BotChatTime()
float BotChatTime (bot_state_t * bs)
Definition at line 944 of file ai_chat.c.
{
     //int cpm;
     //cpm = trap_Characteristic_BInteger(bs->character, CHARACTERISTIC_CHAT_CPM, 1, 4000);
     return 2.0; //(float) trap_BotChatLength(bs->cs) * 30 / cpm;
 }
Referenced by AIEnter_Respawn(), AINode_Battle_Fight(), AINode_Intermission(), AINode_Seek_LTG(), AINode_Stand(), BotCheckConsoleMessages(), and BotDeathmatchAI().
BotValidChatPosition()
int BotValidChatPosition (bot_state_t * bs)
Definition at line 348 of file ai_chat.c.
{
     vec3_t point, start, end, mins, maxs;
     bsp_trace_t trace;
     //if the bot is dead all positions are valid
     if (BotIsDead(bs)) return qtrue;
     //never start chatting with a powerup
     if (bs->inventory[INVENTORY_QUAD] ||
         bs->inventory[INVENTORY_ENVIRONMENTSUIT] ||
         bs->inventory[INVENTORY_HASTE] ||
         bs->inventory[INVENTORY_INVISIBILITY] ||
         bs->inventory[INVENTORY_REGEN] ||
         bs->inventory[INVENTORY_FLIGHT]) return qfalse;
     //must be on the ground
     //if (bs->cur_ps.groundEntityNum != ENTITYNUM_NONE) return qfalse;
     //do not chat if in lava or slime
     VectorCopy(bs->origin, point);
     point[2] -= 24;
     if (trap_PointContents(point,bs->entitynum) & (CONTENTS_LAVA|CONTENTS_SLIME)) return qfalse;
     //do not chat if under water
     VectorCopy(bs->origin, point);
     point[2] += 32;
     if (trap_PointContents(point,bs->entitynum) & MASK_WATER) return qfalse;
     //must be standing on the world entity
     VectorCopy(bs->origin, start);
     VectorCopy(bs->origin, end);
     start[2] += 1;
     end[2] -= 10;
     trap_AAS_PresenceTypeBoundingBox(PRESENCE_CROUCH, mins, maxs);
     BotAI_Trace(&trace, start, mins, maxs, end, bs->client, MASK_SOLID);
     if (trace.ent != ENTITYNUM_WORLD) return qfalse;
     //the bot is in a position where it can chat
     return qtrue;
 }
Referenced by BotChat_EnemySuicide(), BotChat_EnterGame(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_HitTalking(), BotChat_Kill(), BotChat_Random(), and BotCheckConsoleMessages().