ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_bot.c File Reference
g_bot.c File Reference
#include "g_local.h"
Classes
struct botSpawnQueue_t
Macros
#define BOT_BEGIN_DELAY_BASE 2000
#define BOT_BEGIN_DELAY_INCREMENT 1500
#define BOT_SPAWN_QUEUE_DEPTH 16
Functions
float trap_Cvar_VariableValue (const char *var_name)
int G_ParseInfos (char *buf, int max, char *infos[])
static void G_LoadArenasFromFile (char *filename)
static void G_LoadArenas (void)
const char * G_GetArenaInfoByMap (const char *map)
static void PlayerIntroSound (const char *modelAndSkin)
int G_CountBotPlayersByName (const char *name, int team)
int G_SelectRandomBotInfo (int team)
void G_AddRandomBot (int team)
int G_RemoveRandomBot (int team)
int G_CountHumanPlayers (int team)
int G_CountBotPlayers (int team)
void G_CheckMinimumPlayers (void)
void G_CheckBotSpawn (void)
static void AddBotToSpawnQueue (int clientNum, int delay)
void G_RemoveQueuedBotBegin (int clientNum)
qboolean G_BotConnect (int clientNum, qboolean restart)
static void G_AddBot (const char *name, float skill, const char *team, int delay, char *altname)
void Svcmd_AddBot_f (void)
void Svcmd_BotList_f (void)
static void G_SpawnBots (char *botList, int baseDelay)
static void G_LoadBotsFromFile (char *filename)
static void G_LoadBots (void)
char * G_GetBotInfoByNumber (int num)
char * G_GetBotInfoByName (const char *name)
void G_InitBots (qboolean restart)
Variables
static int g_numBots
static char * g_botInfos [MAX_BOTS]
int g_numArenas
static char * g_arenaInfos [MAX_ARENAS]
static botSpawnQueue_t botSpawnQueue [BOT_SPAWN_QUEUE_DEPTH]
vmCvar_t bot_minplayers
gentity_t * podium1
gentity_t * podium2
gentity_t * podium3
Macro Definition Documentation
BOT_BEGIN_DELAY_BASE
#define BOT_BEGIN_DELAY_BASE 2000
Definition at line 36 of file g_bot.c.
BOT_BEGIN_DELAY_INCREMENT
#define BOT_BEGIN_DELAY_INCREMENT 1500
Definition at line 37 of file g_bot.c.
BOT_SPAWN_QUEUE_DEPTH
#define BOT_SPAWN_QUEUE_DEPTH 16
Definition at line 39 of file g_bot.c.
Function Documentation
AddBotToSpawnQueue()
static void AddBotToSpawnQueue (int clientNum, int delay) static
Definition at line 529 of file g_bot.c.
 {
     int        n;
     for (n = 0; n < BOT_SPAWN_QUEUE_DEPTH; n++) {
         if (!botSpawnQueue[n].spawnTime) {
             botSpawnQueue[n].spawnTime = level.time + delay;
             botSpawnQueue[n].clientNum = clientNum;
             return;
         }
     }
     G_Printf(S_COLOR_YELLOW "Unable to delay spawn\n");
     ClientBegin(clientNum);
 }
References BOT_SPAWN_QUEUE_DEPTH, botSpawnQueue, ClientBegin(), botSpawnQueue_t::clientNum, G_Printf(), level, S_COLOR_YELLOW, botSpawnQueue_t::spawnTime, and level_locals_t::time.
Referenced by G_AddBot().
G_AddBot()
static void G_AddBot (const char * name, float skill, const char * team, int delay, char * altname) static
Definition at line 596 of file g_bot.c.
 {
     int                clientNum;
     int                teamNum;
     int                botinfoNum;
     char* botinfo;
     char* key;
     char* s;
     char* botname;
     char* model;
     char* headmodel;
     char            userinfo[MAX_INFO_STRING];
     // have the server allocate a client slot
     clientNum = trap_BotAllocateClient();
     if (clientNum == -1) {
         G_Printf(S_COLOR_RED "Unable to add bot. All player slots are in use.\n");
         G_Printf(S_COLOR_RED "Start server with more 'open' slots (or check setting of sv_maxclients cvar).\n");
         return;
     }
     // set default team
     if (!team || !*team) {
         if (g_gametype.integer >= GT_TEAM) {
             if (PickTeam(clientNum) == TEAM_RED) {
                 team = "red";
             } else {
                 team = "blue";
             }
         } else {
             team = "free";
         }
     }
     // get the botinfo from bots.txt
     if (Q_stricmp(name, "random") == 0) {
         if (Q_stricmp(team, "red") == 0 || Q_stricmp(team, "r") == 0) {
             teamNum = TEAM_RED;
         } else if (Q_stricmp(team, "blue") == 0 || Q_stricmp(team, "b") == 0) {
             teamNum = TEAM_BLUE;
         } else if (!Q_stricmp(team, "spectator") || !Q_stricmp(team, "s")) {
             teamNum = TEAM_SPECTATOR;
         } else {
             teamNum = TEAM_FREE;
         }
         botinfoNum = G_SelectRandomBotInfo(teamNum);
         if (botinfoNum < 0) {
             G_Printf(S_COLOR_RED "Error: Cannot add random bot, no bot info available.\n");
             trap_BotFreeClient(clientNum);
             return;
         }
         botinfo = G_GetBotInfoByNumber(botinfoNum);
     } else {
         botinfo = G_GetBotInfoByName(name);
     }
     if (!botinfo) {
         G_Printf(S_COLOR_RED "Error: Bot '%s' not defined\n", name);
         trap_BotFreeClient(clientNum);
         return;
     }
     // create the bot's userinfo
     userinfo[0] = '\0';
     botname = Info_ValueForKey(botinfo, "funname");
     if (!botname[0]) {
         botname = Info_ValueForKey(botinfo, "name");
     }
     // check for an alternative name
     if (altname && altname[0]) {
         botname = altname;
     }
     Info_SetValueForKey(userinfo, "name", botname);
     Info_SetValueForKey(userinfo, "rate", "25000");
     Info_SetValueForKey(userinfo, "snaps", "20");
     Info_SetValueForKey(userinfo, "skill", va("%.2f", skill));
     Info_SetValueForKey(userinfo, "teampref", team);
     if (skill >= 1 && skill < 2) {
         Info_SetValueForKey(userinfo, "handicap", "50");
     } else if (skill >= 2 && skill < 3) {
         Info_SetValueForKey(userinfo, "handicap", "70");
     } else if (skill >= 3 && skill < 4) {
         Info_SetValueForKey(userinfo, "handicap", "90");
     }
     key = "model";
     model = Info_ValueForKey(botinfo, key);
     if (!*model) {
         model = "visor/default";
     }
     Info_SetValueForKey(userinfo, key, model);
     key = "team_model";
     Info_SetValueForKey(userinfo, key, model);
     key = "headmodel";
     headmodel = Info_ValueForKey(botinfo, key);
     if (!*headmodel) {
         headmodel = model;
     }
     Info_SetValueForKey(userinfo, key, headmodel);
     key = "team_headmodel";
     Info_SetValueForKey(userinfo, key, headmodel);
     key = "gender";
     s = Info_ValueForKey(botinfo, key);
     if (!*s) {
         s = "male";
     }
     Info_SetValueForKey(userinfo, "sex", s);
     key = "color1";
     s = Info_ValueForKey(botinfo, key);
     if (!*s) {
         s = "4";
     }
     Info_SetValueForKey(userinfo, key, s);
     key = "color2";
     s = Info_ValueForKey(botinfo, key);
     if (!*s) {
         s = "5";
     }
     Info_SetValueForKey(userinfo, key, s);
     s = Info_ValueForKey(botinfo, "aifile");
     if (!*s) {
         trap_Print(S_COLOR_RED "Error: bot has no aifile specified\n");
         trap_BotFreeClient(clientNum);
         return;
     }
     Info_SetValueForKey(userinfo, "characterfile", s);
     // don't send tinfo to bots, they don't parse it
     Info_SetValueForKey(userinfo, "teamoverlay", "0");
     // register the userinfo
     trap_SetUserinfo(clientNum, userinfo);
     // have it connect to the game as a normal client
     if (ClientConnect(clientNum, qtrue, qtrue)) {
         return;
     }
     if (delay == 0) {
         ClientBegin(clientNum);
         return;
     }
     AddBotToSpawnQueue(clientNum, delay);
 }
References AddBotToSpawnQueue(), ClientBegin(), ClientConnect(), g_gametype, G_GetBotInfoByName(), G_GetBotInfoByNumber(), G_Printf(), G_SelectRandomBotInfo(), GT_TEAM, Info_SetValueForKey(), Info_ValueForKey(), MAX_INFO_STRING, PickTeam(), Q_stricmp(), qtrue, s, S_COLOR_RED, TEAM_BLUE, TEAM_FREE, TEAM_RED, TEAM_SPECTATOR, trap_BotAllocateClient(), trap_BotFreeClient(), trap_Print(), trap_SetUserinfo(), and va().
Referenced by Svcmd_AddBot_f().
G_AddRandomBot()
void G_AddRandomBot (int team)
Definition at line 325 of file g_bot.c.
 {
     char* teamstr;
     float    skill;
     skill = trap_Cvar_VariableValue("g_spSkill");
     if (team == TEAM_RED) teamstr = "red";
     else if (team == TEAM_BLUE) teamstr = "blue";
     else teamstr = "free";
     trap_SendConsoleCommand(EXEC_INSERT, va("addbot random %f %s %i\n", skill, teamstr, 0));
 }
References EXEC_INSERT, TEAM_BLUE, TEAM_RED, trap_Cvar_VariableValue(), trap_SendConsoleCommand(), and va().
Referenced by G_CheckMinimumPlayers().
G_BotConnect()
qboolean G_BotConnect (int clientNum, qboolean restart)
Definition at line 572 of file g_bot.c.
 {
     bot_settings_t    settings;
     char            userinfo[MAX_INFO_STRING];
     trap_GetUserinfo(clientNum, userinfo, sizeof(userinfo));
     Q_strncpyz(settings.characterfile, Info_ValueForKey(userinfo, "characterfile"), sizeof(settings.characterfile));
     settings.skill = atof(Info_ValueForKey(userinfo, "skill"));
     if (!BotAISetupClient(clientNum, &settings, restart)) {
         trap_DropClient(clientNum, "BotAISetupClient failed");
         return qfalse;
     }
     return qtrue;
 }
References BotAISetupClient(), bot_settings_s::characterfile, Info_ValueForKey(), MAX_INFO_STRING, Q_strncpyz(), qfalse, qtrue, bot_settings_s::skill, trap_DropClient(), and trap_GetUserinfo().
Referenced by ClientConnect().
G_CheckBotSpawn()
void G_CheckBotSpawn (void)
Definition at line 499 of file g_bot.c.
 {
     int        n;
     char    userinfo[MAX_INFO_VALUE];
     G_CheckMinimumPlayers();
     for (n = 0; n < BOT_SPAWN_QUEUE_DEPTH; n++) {
         if (!botSpawnQueue[n].spawnTime) {
             continue;
         }
         if (botSpawnQueue[n].spawnTime > level.time) {
             continue;
         }
         ClientBegin(botSpawnQueue[n].clientNum);
         botSpawnQueue[n].spawnTime = 0;
         if (g_gametype.integer == GT_SINGLE_PLAYER) {
             trap_GetUserinfo(botSpawnQueue[n].clientNum, userinfo, sizeof(userinfo));
             PlayerIntroSound(Info_ValueForKey(userinfo, "model"));
         }
     }
 }
References BOT_SPAWN_QUEUE_DEPTH, botSpawnQueue, ClientBegin(), G_CheckMinimumPlayers(), g_gametype, GT_SINGLE_PLAYER, Info_ValueForKey(), level, MAX_INFO_VALUE, PlayerIntroSound(), botSpawnQueue_t::spawnTime, level_locals_t::time, and trap_GetUserinfo().
Referenced by BotAIStartFrame().
G_CheckMinimumPlayers()
void G_CheckMinimumPlayers (void)
Definition at line 425 of file g_bot.c.
 {
     int minplayers;
     int humanplayers, botplayers;
     static int checkminimumplayers_time;
     if (level.intermissiontime) return;
     //only check once each 10 seconds
     if (checkminimumplayers_time > level.time - 10000) {
         return;
     }
     checkminimumplayers_time = level.time;
     trap_Cvar_Update(&bot_minplayers);
     minplayers = bot_minplayers.integer;
     if (minplayers <= 0) return;
     if (g_gametype.integer >= GT_TEAM) {
         if (minplayers >= g_maxclients.integer / 2) {
             minplayers = (g_maxclients.integer / 2) - 1;
         }
         humanplayers = G_CountHumanPlayers(TEAM_RED);
         botplayers = G_CountBotPlayers(TEAM_RED);
         //
         if (humanplayers + botplayers < minplayers) {
             G_AddRandomBot(TEAM_RED);
         } else if (humanplayers + botplayers > minplayers&& botplayers) {
             G_RemoveRandomBot(TEAM_RED);
         }
         //
         humanplayers = G_CountHumanPlayers(TEAM_BLUE);
         botplayers = G_CountBotPlayers(TEAM_BLUE);
         //
         if (humanplayers + botplayers < minplayers) {
             G_AddRandomBot(TEAM_BLUE);
         } else if (humanplayers + botplayers > minplayers&& botplayers) {
             G_RemoveRandomBot(TEAM_BLUE);
         }
     } else if (g_gametype.integer == GT_TOURNAMENT) {
         if (minplayers >= g_maxclients.integer) {
             minplayers = g_maxclients.integer - 1;
         }
         humanplayers = G_CountHumanPlayers(-1);
         botplayers = G_CountBotPlayers(-1);
         //
         if (humanplayers + botplayers < minplayers) {
             G_AddRandomBot(TEAM_FREE);
         } else if (humanplayers + botplayers > minplayers&& botplayers) {
             // try to remove spectators first
             if (!G_RemoveRandomBot(TEAM_SPECTATOR)) {
                 // just remove the bot that is playing
                 G_RemoveRandomBot(-1);
             }
         }
     } else if (g_gametype.integer == GT_FFA) {
         if (minplayers >= g_maxclients.integer) {
             minplayers = g_maxclients.integer - 1;
         }
         humanplayers = G_CountHumanPlayers(TEAM_FREE);
         botplayers = G_CountBotPlayers(TEAM_FREE);
         //
         if (humanplayers + botplayers < minplayers) {
             G_AddRandomBot(TEAM_FREE);
         } else if (humanplayers + botplayers > minplayers&& botplayers) {
             G_RemoveRandomBot(TEAM_FREE);
         }
     }
 }
References bot_minplayers, G_AddRandomBot(), G_CountBotPlayers(), G_CountHumanPlayers(), g_gametype, g_maxclients, G_RemoveRandomBot(), GT_FFA, GT_TEAM, GT_TOURNAMENT, vmCvar_t::integer, level_locals_t::intermissiontime, level, TEAM_BLUE, TEAM_FREE, TEAM_RED, TEAM_SPECTATOR, level_locals_t::time, and trap_Cvar_Update().
Referenced by G_CheckBotSpawn().
G_CountBotPlayers()
int G_CountBotPlayers (int team)
Definition at line 398 of file g_bot.c.
 {
     int i, num;
     gclient_t* cl;
     num = 0;
     for (i = 0; i < g_maxclients.integer; i++) {
         cl = level.clients + i;
         if (cl->pers.connected == CON_DISCONNECTED) {
             continue;
         }
         if (!(g_entities[i].r.svFlags & SVF_BOT)) {
             continue;
         }
         if (team >= 0 && cl->sess.sessionTeam != team) {
             continue;
         }
         num++;
     }
     return num;
 }
References cl, level_locals_t::clients, CON_DISCONNECTED, g_entities, g_maxclients, vmCvar_t::integer, level, and SVF_BOT.
Referenced by G_CheckMinimumPlayers().
G_CountBotPlayersByName()
int G_CountBotPlayersByName (const char * name, int team)
Definition at line 244 of file g_bot.c.
 {
     int            i, num;
     gclient_t* cl;
     num = 0;
     for (i = 0; i < g_maxclients.integer; i++) {
         cl = level.clients + i;
         if (cl->pers.connected == CON_DISCONNECTED) {
             continue;
         }
         if (!(g_entities[i].r.svFlags & SVF_BOT)) {
             continue;
         }
         if (team >= 0 && cl->sess.sessionTeam != team) {
             continue;
         }
         if (name && Q_stricmp(name, cl->pers.netname)) {
             continue;
         }
         num++;
     }
     return num;
 }
References cl, level_locals_t::clients, CON_DISCONNECTED, g_entities, g_maxclients, vmCvar_t::integer, level, Q_stricmp(), and SVF_BOT.
Referenced by G_SelectRandomBotInfo().
G_CountHumanPlayers()
int G_CountHumanPlayers (int team)
Definition at line 369 of file g_bot.c.
 {
     int i, num;
     gclient_t* cl;
     num = 0;
     for (i = 0; i < g_maxclients.integer; i++) {
         cl = level.clients + i;
         if (cl->pers.connected != CON_CONNECTED) {
             continue;
         }
         if (g_entities[i].r.svFlags & SVF_BOT) {
             continue;
         }
         if (team >= 0 && cl->sess.sessionTeam != team) {
             continue;
         }
         num++;
     }
     return num;
 }
References cl, level_locals_t::clients, CON_CONNECTED, g_entities, g_maxclients, vmCvar_t::integer, level, and SVF_BOT.
Referenced by G_CheckMinimumPlayers().
G_GetArenaInfoByMap()
const char* G_GetArenaInfoByMap (const char * map)
Definition at line 196 of file g_bot.c.
 {
     int            n;
     for (n = 0; n < g_numArenas; n++) {
         if (Q_stricmp(Info_ValueForKey(g_arenaInfos[n], "map"), map) == 0) {
             return g_arenaInfos[n];
         }
     }
     return NULL;
 }
References g_arenaInfos, g_numArenas, Info_ValueForKey(), NULL, and Q_stricmp().
Referenced by G_InitBots().
G_GetBotInfoByName()
char* G_GetBotInfoByName (const char * name)
Definition at line 996 of file g_bot.c.
 {
     int        n;
     char* value;
     for (n = 0; n < g_numBots; n++) {
         value = Info_ValueForKey(g_botInfos[n], "name");
         if (!Q_stricmp(value, name)) {
             return g_botInfos[n];
         }
     }
     return NULL;
 }
References g_botInfos, g_numBots, Info_ValueForKey(), NULL, and Q_stricmp().
Referenced by G_AddBot().
G_GetBotInfoByNumber()
char* G_GetBotInfoByNumber (int num)
Definition at line 981 of file g_bot.c.
 {
     if (num < 0 || num >= g_numBots) {
         trap_Print(va(S_COLOR_RED "Invalid bot number: %i\n", num));
         return NULL;
     }
     return g_botInfos[num];
 }
References g_botInfos, g_numBots, NULL, S_COLOR_RED, trap_Print(), and va().
Referenced by G_AddBot().
G_InitBots()
void G_InitBots (qboolean restart)
Definition at line 1016 of file g_bot.c.
 {
     int            fragLimit;
     int            timeLimit;
     const char* arenainfo;
     char* strValue;
     int            basedelay;
     char        map[MAX_QPATH];
     char        serverinfo[MAX_INFO_STRING];
     G_LoadBots();
     G_LoadArenas();
     trap_Cvar_Register(&bot_minplayers, "bot_minplayers", "0", CVAR_SERVERINFO);
     if (g_gametype.integer == GT_SINGLE_PLAYER) {
         trap_GetServerinfo(serverinfo, sizeof(serverinfo));
         Q_strncpyz(map, Info_ValueForKey(serverinfo, "mapname"), sizeof(map));
         arenainfo = G_GetArenaInfoByMap(map);
         if (!arenainfo) {
             return;
         }
         strValue = Info_ValueForKey(arenainfo, "fraglimit");
         fragLimit = atoi(strValue);
         if (fragLimit) {
             trap_Cvar_Set("fraglimit", strValue);
         } else {
             trap_Cvar_Set("fraglimit", "0");
         }
         strValue = Info_ValueForKey(arenainfo, "timelimit");
         timeLimit = atoi(strValue);
         if (timeLimit) {
             trap_Cvar_Set("timelimit", strValue);
         } else {
             trap_Cvar_Set("timelimit", "0");
         }
         if (!fragLimit && !timeLimit) {
             trap_Cvar_Set("fraglimit", "10");
             trap_Cvar_Set("timelimit", "0");
         }
         basedelay = BOT_BEGIN_DELAY_BASE;
         strValue = Info_ValueForKey(arenainfo, "special");
         if (Q_stricmp(strValue, "training") == 0) {
             basedelay += 10000;
         }
         if (!restart) {
             G_SpawnBots(Info_ValueForKey(arenainfo, "bots"), basedelay);
         }
     }
 }
References arenainfo, BOT_BEGIN_DELAY_BASE, bot_minplayers, CVAR_SERVERINFO, g_gametype, G_GetArenaInfoByMap(), G_LoadArenas(), G_LoadBots(), G_SpawnBots(), GT_SINGLE_PLAYER, Info_ValueForKey(), MAX_INFO_STRING, MAX_QPATH, Q_stricmp(), Q_strncpyz(), trap_Cvar_Register(), trap_Cvar_Set(), and trap_GetServerinfo().
Referenced by G_InitGame().
G_LoadArenas()
static void G_LoadArenas (void) static
Definition at line 155 of file g_bot.c.
 {
     int            numdirs;
     vmCvar_t    arenasFile;
     char        filename[128];
     char        dirlist[1024];
     char* dirptr;
     int            i, n;
     int            dirlen;
     g_numArenas = 0;
     trap_Cvar_Register(&arenasFile, "g_arenasFile", "", CVAR_INIT | CVAR_ROM);
     if (*arenasFile.string) {
         G_LoadArenasFromFile(arenasFile.string);
     } else {
         G_LoadArenasFromFile("scripts/arenas.txt");
     }
     // get all arenas from .arena files
     numdirs = trap_FS_GetFileList("scripts", ".arena", dirlist, 1024);
     dirptr = dirlist;
     for (i = 0; i < numdirs; i++, dirptr += dirlen + 1) {
         dirlen = strlen(dirptr);
         strcpy(filename, "scripts/");
         strcat(filename, dirptr);
         G_LoadArenasFromFile(filename);
     }
     trap_Print(va("%i arenas parsed\n", g_numArenas));
     for (n = 0; n < g_numArenas; n++) {
         Info_SetValueForKey(g_arenaInfos[n], "num", va("%i", n));
     }
 }
References CVAR_INIT, CVAR_ROM, g_arenaInfos, G_LoadArenasFromFile(), g_numArenas, Info_SetValueForKey(), vmCvar_t::string, trap_Cvar_Register(), trap_FS_GetFileList(), trap_Print(), and va().
Referenced by G_InitBots().
G_LoadArenasFromFile()
static void G_LoadArenasFromFile (char * filename) static
Definition at line 126 of file g_bot.c.
 {
     int                len;
     fileHandle_t    f;
     char            buf[MAX_ARENAS_TEXT];
     len = trap_FS_FOpenFile(filename, &f, FS_READ);
     if (!f) {
         trap_Print(va(S_COLOR_RED "file not found: %s\n", filename));
         return;
     }
     if (len >= MAX_ARENAS_TEXT) {
         trap_FS_FCloseFile(f);
         trap_Print(va(S_COLOR_RED "file too large: %s is %i, max allowed is %i\n", filename, len, MAX_ARENAS_TEXT));
         return;
     }
     trap_FS_Read(buf, len, f);
     buf[len] = 0;
     trap_FS_FCloseFile(f);
     g_numArenas += G_ParseInfos(buf, MAX_ARENAS - g_numArenas, &g_arenaInfos[g_numArenas]);
 }
References FS_READ, g_arenaInfos, g_numArenas, G_ParseInfos(), MAX_ARENAS, MAX_ARENAS_TEXT, S_COLOR_RED, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), and va().
Referenced by G_LoadArenas().
G_LoadBots()
static void G_LoadBots (void) static
Definition at line 939 of file g_bot.c.
 {
     vmCvar_t    botsFile;
     int            numdirs;
     char        filename[128];
     char        dirlist[1024];
     char* dirptr;
     int            i;
     int            dirlen;
     if (!trap_Cvar_VariableIntegerValue("bot_enable")) {
         return;
     }
     g_numBots = 0;
     trap_Cvar_Register(&botsFile, "g_botsFile", "", CVAR_INIT | CVAR_ROM);
     if (*botsFile.string) {
         G_LoadBotsFromFile(botsFile.string);
     } else {
         G_LoadBotsFromFile("scripts/bots.txt");
     }
     // get all bots from .bot files
     numdirs = trap_FS_GetFileList("scripts", ".bot", dirlist, 1024);
     dirptr = dirlist;
     for (i = 0; i < numdirs; i++, dirptr += dirlen + 1) {
         dirlen = strlen(dirptr);
         strcpy(filename, "scripts/");
         strcat(filename, dirptr);
         G_LoadBotsFromFile(filename);
     }
     trap_Print(va("%i bots parsed\n", g_numBots));
 }
References CVAR_INIT, CVAR_ROM, G_LoadBotsFromFile(), g_numBots, vmCvar_t::string, trap_Cvar_Register(), trap_Cvar_VariableIntegerValue(), trap_FS_GetFileList(), trap_Print(), and va().
Referenced by G_InitBots().
G_LoadBotsFromFile()
static void G_LoadBotsFromFile (char * filename) static
Definition at line 910 of file g_bot.c.
 {
     int                len;
     fileHandle_t    f;
     char            buf[MAX_BOTS_TEXT];
     len = trap_FS_FOpenFile(filename, &f, FS_READ);
     if (!f) {
         trap_Print(va(S_COLOR_RED "file not found: %s\n", filename));
         return;
     }
     if (len >= MAX_BOTS_TEXT) {
         trap_Print(va(S_COLOR_RED "file too large: %s is %i, max allowed is %i\n", filename, len, MAX_BOTS_TEXT));
         trap_FS_FCloseFile(f);
         return;
     }
     trap_FS_Read(buf, len, f);
     buf[len] = 0;
     trap_FS_FCloseFile(f);
     g_numBots += G_ParseInfos(buf, MAX_BOTS - g_numBots, &g_botInfos[g_numBots]);
 }
References FS_READ, g_botInfos, g_numBots, G_ParseInfos(), MAX_BOTS, MAX_BOTS_TEXT, S_COLOR_RED, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), and va().
Referenced by G_LoadBots().
G_ParseInfos()
int G_ParseInfos (char * buf, int max, char * infos[])
Definition at line 69 of file g_bot.c.
 {
     char* token;
     int        count;
     char    key[MAX_TOKEN_CHARS];
     char    info[MAX_INFO_STRING];
     count = 0;
     while (1) {
         token = COM_Parse(&buf);
         if (!token[0]) {
             break;
         }
         if (strcmp(token, "{")) {
             Com_Printf("Missing { in info file\n");
             break;
         }
         if (count == max) {
             Com_Printf("Max infos exceeded\n");
             break;
         }
         info[0] = '\0';
         while (1) {
             token = COM_ParseExt(&buf, qtrue);
             if (!token[0]) {
                 Com_Printf("Unexpected end of info file\n");
                 break;
             }
             if (!strcmp(token, "}")) {
                 break;
             }
             Q_strncpyz(key, token, sizeof(key));
             token = COM_ParseExt(&buf, qfalse);
             if (!token[0]) {
                 strcpy(token, "<NULL>");
             }
             Info_SetValueForKey(info, key, token);
         }
         //NOTE: extra space for arena number
         infos[count] = G_Alloc(strlen(info) + strlen("\\num\\") + strlen(va("%d", MAX_ARENAS)) + 1);
         if (infos[count]) {
             strcpy(infos[count], info);
             count++;
         }
     }
     return count;
 }
References COM_Parse(), COM_ParseExt(), Com_Printf(), count, G_Alloc(), Info_SetValueForKey(), MAX_ARENAS, MAX_INFO_STRING, MAX_TOKEN_CHARS, Q_strncpyz(), qfalse, qtrue, and va().
Referenced by G_LoadArenasFromFile(), and G_LoadBotsFromFile().
G_RemoveQueuedBotBegin()
void G_RemoveQueuedBotBegin (int clientNum)
Definition at line 554 of file g_bot.c.
 {
     int        n;
     for (n = 0; n < BOT_SPAWN_QUEUE_DEPTH; n++) {
         if (botSpawnQueue[n].clientNum == clientNum) {
             botSpawnQueue[n].spawnTime = 0;
             return;
         }
     }
 }
References BOT_SPAWN_QUEUE_DEPTH, botSpawnQueue, and botSpawnQueue_t::spawnTime.
Referenced by ClientDisconnect().
G_RemoveRandomBot()
int G_RemoveRandomBot (int team)
Definition at line 342 of file g_bot.c.
 {
     int i;
     gclient_t* cl;
     for (i = 0; i < g_maxclients.integer; i++) {
         cl = level.clients + i;
         if (cl->pers.connected != CON_CONNECTED) {
             continue;
         }
         if (!(g_entities[i].r.svFlags & SVF_BOT)) {
             continue;
         }
         if (team >= 0 && cl->sess.sessionTeam != team) {
             continue;
         }
         trap_SendConsoleCommand(EXEC_INSERT, va("clientkick %d\n", i));
         return qtrue;
     }
     return qfalse;
 }
References cl, level_locals_t::clients, CON_CONNECTED, EXEC_INSERT, g_entities, g_maxclients, vmCvar_t::integer, level, qfalse, qtrue, SVF_BOT, trap_SendConsoleCommand(), and va().
Referenced by G_CheckMinimumPlayers().
G_SelectRandomBotInfo()
int G_SelectRandomBotInfo (int team)
Definition at line 276 of file g_bot.c.
 {
     int        selection[MAX_BOTS];
     int        n, num;
     int        count, bestCount;
     char* value;
     // don't add duplicate bots to the server if there are less bots than bot types
     if (team != -1 && G_CountBotPlayersByName(NULL, -1) < g_numBots) {
         team = -1;
     }
     num = 0;
     bestCount = MAX_CLIENTS;
     for (n = 0; n < g_numBots; n++) {
         value = Info_ValueForKey(g_botInfos[n], "funname");
         if (!value[0]) {
             value = Info_ValueForKey(g_botInfos[n], "name");
         }
         //
         count = G_CountBotPlayersByName(value, team);
         if (count < bestCount) {
             bestCount = count;
             num = 0;
         }
         if (count == bestCount) {
             selection[num++] = n;
             if (num == MAX_BOTS) {
                 break;
             }
         }
     }
     if (num > 0) {
         num = random() * (num - 1);
         return selection[num];
     }
     return -1;
 }
References count, g_botInfos, G_CountBotPlayersByName(), g_numBots, Info_ValueForKey(), MAX_BOTS, MAX_CLIENTS, NULL, and random.
Referenced by G_AddBot().
G_SpawnBots()
static void G_SpawnBots (char * botList, int baseDelay) static
Definition at line 852 of file g_bot.c.
 {
     char* bot;
     char* p;
     float        skill;
     int            delay;
     char        bots[MAX_INFO_VALUE];
     podium1 = NULL;
     podium2 = NULL;
     podium3 = NULL;
     skill = trap_Cvar_VariableValue("g_spSkill");
     if (skill < 1) {
         trap_Cvar_Set("g_spSkill", "1");
         skill = 1;
     } else if (skill > 5) {
         trap_Cvar_Set("g_spSkill", "5");
         skill = 5;
     }
     Q_strncpyz(bots, botList, sizeof(bots));
     p = &bots[0];
     delay = baseDelay;
     while (*p) {
         //skip spaces
         while (*p && *p == ' ') {
             p++;
         }
         if (!*p) {
             break;
         }
         // mark start of bot name
         bot = p;
         // skip until space of null
         while (*p && *p != ' ') {
             p++;
         }
         if (*p) {
             *p++ = 0;
         }
         // we must add the bot this way, calling G_AddBot directly at this stage
         // does "Bad Things"
         trap_SendConsoleCommand(EXEC_INSERT, va("addbot %s %f free %i\n", bot, skill, delay));
         delay += BOT_BEGIN_DELAY_INCREMENT;
     }
 }
References BOT_BEGIN_DELAY_INCREMENT, EXEC_INSERT, MAX_INFO_VALUE, NULL, podium1, podium2, podium3, Q_strncpyz(), trap_Cvar_Set(), trap_Cvar_VariableValue(), trap_SendConsoleCommand(), and va().
Referenced by G_InitBots().
PlayerIntroSound()
static void PlayerIntroSound (const char * modelAndSkin) static
Definition at line 215 of file g_bot.c.
 {
     char    model[MAX_QPATH];
     char* skin;
     Q_strncpyz(model, modelAndSkin, sizeof(model));
     skin = strrchr(model, '/');
     if (skin) {
         *skin++ = '\0';
     } else {
         skin = model;
     }
     if (Q_stricmp(skin, "default") == 0) {
         skin = model;
     }
     trap_SendConsoleCommand(EXEC_APPEND, va("play sound/player/announce/%s.wav\n", skin));
 }
References EXEC_APPEND, MAX_QPATH, Q_stricmp(), Q_strncpyz(), trap_SendConsoleCommand(), and va().
Referenced by G_CheckBotSpawn().
Svcmd_AddBot_f()
void Svcmd_AddBot_f (void)
Definition at line 758 of file g_bot.c.
 {
     float            skill;
     int                delay;
     char            name[MAX_TOKEN_CHARS];
     char            altname[MAX_TOKEN_CHARS];
     char            string[MAX_TOKEN_CHARS];
     char            team[MAX_TOKEN_CHARS];
     // are bots enabled?
     if (!trap_Cvar_VariableIntegerValue("bot_enable")) {
         return;
     }
     // name
     trap_Argv(1, name, sizeof(name));
     if (!name[0]) {
         trap_Print("Usage: Addbot <botname> [skill 1-5] [team] [msec delay] [altname]\n");
         return;
     }
     // skill
     trap_Argv(2, string, sizeof(string));
     if (!string[0]) {
         skill = 4;
     } else {
         skill = Com_Clamp(1, 5, atof(string));
     }
     // team
     trap_Argv(3, team, sizeof(team));
     // delay
     trap_Argv(4, string, sizeof(string));
     if (!string[0]) {
         delay = 0;
     } else {
         delay = atoi(string);
     }
     // alternative name
     trap_Argv(5, altname, sizeof(altname));
     G_AddBot(name, skill, team, delay, altname);
     // if this was issued during gameplay and we are playing locally,
     // go ahead and load the bot's media immediately
     if (level.time - level.startTime > 1000 &&
         trap_Cvar_VariableIntegerValue("cl_running")) {
         trap_SendServerCommand(-1, "loaddefered\n");    // FIXME: spelled wrong, but not changing for demo
     }
 }
References Com_Clamp(), G_AddBot(), level, MAX_TOKEN_CHARS, level_locals_t::startTime, level_locals_t::time, trap_Argv(), trap_Cvar_VariableIntegerValue(), trap_Print(), and trap_SendServerCommand().
Referenced by ConsoleCommand().
Svcmd_BotList_f()
void Svcmd_BotList_f (void)
Definition at line 816 of file g_bot.c.
 {
     int i;
     char name[MAX_TOKEN_CHARS];
     char funname[MAX_TOKEN_CHARS];
     char model[MAX_TOKEN_CHARS];
     char aifile[MAX_TOKEN_CHARS];
     trap_Print("^1name             model            aifile              funname\n");
     for (i = 0; i < g_numBots; i++) {
         Q_strncpyz(name, Info_ValueForKey(g_botInfos[i], "name"), sizeof(name));
         if (!*name) {
             strcpy(name, "UnnamedPlayer");
         }
         Q_strncpyz(funname, Info_ValueForKey(g_botInfos[i], "funname"), sizeof(funname));
         if (!*funname) {
             strcpy(funname, "");
         }
         Q_strncpyz(model, Info_ValueForKey(g_botInfos[i], "model"), sizeof(model));
         if (!*model) {
             strcpy(model, "visor/default");
         }
         Q_strncpyz(aifile, Info_ValueForKey(g_botInfos[i], "aifile"), sizeof(aifile));
         if (!*aifile) {
             strcpy(aifile, "bots/default_c.c");
         }
         trap_Print(va("%-16s %-16s %-20s %-20s\n", name, model, aifile, funname));
     }
 }
References g_botInfos, g_numBots, Info_ValueForKey(), MAX_TOKEN_CHARS, Q_strncpyz(), trap_Print(), and va().
Referenced by ConsoleCommand().
trap_Cvar_VariableValue()
float trap_Cvar_VariableValue (const char * var_name)
Definition at line 54 of file g_bot.c.
 {
     char buf[128];
     trap_Cvar_VariableStringBuffer(var_name, buf, sizeof(buf));
     return atof(buf);
 }
Referenced by _UI_Init(), ArenaServers_MaxPing(), ArenaServers_MenuInit(), ArenaServers_StartRefresh(), Controls_InitCvars(), Controls_SetConfig(), Demos_MenuInit(), G_AddRandomBot(), G_SpawnBots(), GraphicsOptions_SetMenuItems(), InGame_MenuInit(), PlayerModel_BuildList(), PlayerSettings_SetMenuItems(), Preferences_SetMenuItems(), Punkbuster_ConfirmDisable(), Punkbuster_ConfirmEnable(), Rankings_MenuInit(), ServerOptions_MenuInit(), ServerOptions_SetMenuItems(), Signup_MenuInit(), StartServer_Cache(), UI_AddBotsMenu_Init(), UI_BotName_HandleKey(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_DisplayDownloadInfo(), UI_DisplayOptionsMenu_Init(), UI_DrawBotName(), UI_DrawHandicap(), UI_DrawPlayerModel(), UI_DrawSkill(), UI_DrawTeamMember(), UI_DrawTier(), UI_DrawTierGameType(), UI_DrawTierMap(), UI_DrawTierMapName(), UI_Handicap_HandleKey(), UI_LoadBestScores(), UI_LoadDemos(), UI_NetworkOptionsMenu_Init(), UI_OwnerDrawVisible(), UI_OwnerDrawWidth(), UI_PlayerInfo_SetInfo(), UI_RankStatusMenu(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_ServerInfoMenu(), UI_SetBestScore(), UI_SetupMenu_Init(), UI_Skill_HandleKey(), UI_SoundOptionsMenu_Init(), UI_SPArena_Start(), UI_SPLevelMenu_Init(), UI_SPPostgameMenu_Cache(), UI_SPPostgameMenu_MenuDraw(), UI_SPSkillMenu_Init(), UI_SPSkillMenu_SkillEvent(), UI_StartServerRefresh(), UI_StartSkirmish(), UI_StopServerRefresh(), UI_TeamMember_HandleKey(), and UI_Update().
Variable Documentation
bot_minplayers
vmCvar_t bot_minplayers
Definition at line 48 of file g_bot.c.
Referenced by G_CheckMinimumPlayers(), and G_InitBots().
botSpawnQueue
botSpawnQueue_t botSpawnQueue[BOT_SPAWN_QUEUE_DEPTH] static
Definition at line 46 of file g_bot.c.
Referenced by AddBotToSpawnQueue(), G_CheckBotSpawn(), and G_RemoveQueuedBotBegin().
g_arenaInfos
char* g_arenaInfos[MAX_ARENAS] static
Definition at line 33 of file g_bot.c.
Referenced by G_GetArenaInfoByMap(), G_LoadArenas(), and G_LoadArenasFromFile().
g_botInfos
char* g_botInfos[MAX_BOTS] static
Definition at line 29 of file g_bot.c.
Referenced by G_GetBotInfoByName(), G_GetBotInfoByNumber(), G_LoadBotsFromFile(), G_SelectRandomBotInfo(), and Svcmd_BotList_f().
g_numArenas
int g_numArenas
Definition at line 32 of file g_bot.c.
Referenced by G_GetArenaInfoByMap(), G_LoadArenas(), and G_LoadArenasFromFile().
g_numBots
int g_numBots static
Definition at line 28 of file g_bot.c.
Referenced by G_GetBotInfoByName(), G_GetBotInfoByNumber(), G_LoadBots(), G_LoadBotsFromFile(), G_SelectRandomBotInfo(), and Svcmd_BotList_f().
podium1
gentity_t* podium1
Definition at line 30 of file g_arenas.c.
Referenced by G_SpawnBots(), PodiumPlacementThink(), SpawnModelsOnVictoryPads(), and Svcmd_AbortPodium_f().
podium2
gentity_t* podium2
Definition at line 31 of file g_arenas.c.
Referenced by G_SpawnBots(), PodiumPlacementThink(), and SpawnModelsOnVictoryPads().
podium3
gentity_t* podium3
Definition at line 32 of file g_arenas.c.
Referenced by G_SpawnBots(), PodiumPlacementThink(), and SpawnModelsOnVictoryPads().