ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_specifyleague.c File Reference
ui_specifyleague.c File Reference
#include "ui_local.h"
Classes
struct specifyleague_t
struct table_t
Macros
#define MAX_LISTBOXITEMS 128
#define MAX_LISTBOXWIDTH 40
#define MAX_LEAGUENAME 80
#define SPECIFYLEAGUE_FRAMEL "menu/art/frame2_l"
#define SPECIFYLEAGUE_FRAMER "menu/art/frame1_r"
#define SPECIFYLEAGUE_BACK0 "menu/art/back_0"
#define SPECIFYLEAGUE_BACK1 "menu/art/back_1"
#define SPECIFYLEAGUE_ARROWS0 "menu/art/arrows_vert_0"
#define SPECIFYLEAGUE_UP "menu/art/arrows_vert_top"
#define SPECIFYLEAGUE_DOWN "menu/art/arrows_vert_bot"
#define GLOBALRANKINGS_LOGO "menu/art/gr/grlogo"
#define GLOBALRANKINGS_LETTERS "menu/art/gr/grletters"
#define ID_SPECIFYLEAGUENAME 100
#define ID_SPECIFYLEAGUELIST 101
#define ID_SPECIFYLEAGUEUP 102
#define ID_SPECIFYLEAGUEDOWN 103
#define ID_SPECIFYLEAGUEBACK 104
Functions
static void SpecifyLeague_GetList ()
static void SpecifyLeague_Event (void *ptr, int event)
void SpecifyLeague_MenuInit (void)
void SpecifyLeague_Cache (void)
void UI_SpecifyLeagueMenu (void)
Variables
static char * specifyleague_artlist []
static char playername [80]
static specifyleague_t s_specifyleague
table_t league_table [MAX_LISTBOXITEMS]
char * leaguename_items [MAX_LISTBOXITEMS]
Macro Definition Documentation
GLOBALRANKINGS_LETTERS
#define GLOBALRANKINGS_LETTERS "menu/art/gr/grletters"
Definition at line 41 of file ui_specifyleague.c.
GLOBALRANKINGS_LOGO
#define GLOBALRANKINGS_LOGO "menu/art/gr/grlogo"
Definition at line 40 of file ui_specifyleague.c.
ID_SPECIFYLEAGUEBACK
#define ID_SPECIFYLEAGUEBACK 104
Definition at line 47 of file ui_specifyleague.c.
ID_SPECIFYLEAGUEDOWN
#define ID_SPECIFYLEAGUEDOWN 103
Definition at line 46 of file ui_specifyleague.c.
ID_SPECIFYLEAGUELIST
#define ID_SPECIFYLEAGUELIST 101
Definition at line 44 of file ui_specifyleague.c.
ID_SPECIFYLEAGUENAME
#define ID_SPECIFYLEAGUENAME 100
Definition at line 43 of file ui_specifyleague.c.
ID_SPECIFYLEAGUEUP
#define ID_SPECIFYLEAGUEUP 102
Definition at line 45 of file ui_specifyleague.c.
MAX_LEAGUENAME
#define MAX_LEAGUENAME 80
Definition at line 31 of file ui_specifyleague.c.
MAX_LISTBOXITEMS
#define MAX_LISTBOXITEMS 128
Definition at line 29 of file ui_specifyleague.c.
MAX_LISTBOXWIDTH
#define MAX_LISTBOXWIDTH 40
Definition at line 30 of file ui_specifyleague.c.
SPECIFYLEAGUE_ARROWS0
#define SPECIFYLEAGUE_ARROWS0 "menu/art/arrows_vert_0"
Definition at line 37 of file ui_specifyleague.c.
SPECIFYLEAGUE_BACK0
#define SPECIFYLEAGUE_BACK0 "menu/art/back_0"
Definition at line 35 of file ui_specifyleague.c.
SPECIFYLEAGUE_BACK1
#define SPECIFYLEAGUE_BACK1 "menu/art/back_1"
Definition at line 36 of file ui_specifyleague.c.
SPECIFYLEAGUE_DOWN
#define SPECIFYLEAGUE_DOWN "menu/art/arrows_vert_bot"
Definition at line 39 of file ui_specifyleague.c.
SPECIFYLEAGUE_FRAMEL
#define SPECIFYLEAGUE_FRAMEL "menu/art/frame2_l"
Definition at line 33 of file ui_specifyleague.c.
SPECIFYLEAGUE_FRAMER
#define SPECIFYLEAGUE_FRAMER "menu/art/frame1_r"
Definition at line 34 of file ui_specifyleague.c.
SPECIFYLEAGUE_UP
#define SPECIFYLEAGUE_UP "menu/art/arrows_vert_top"
Definition at line 38 of file ui_specifyleague.c.
Function Documentation
SpecifyLeague_Cache()
void SpecifyLeague_Cache (void)
Definition at line 310 of file ui_specifyleague.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!specifyleague_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(specifyleague_artlist[i]);
     }
 }
References specifyleague_artlist, and trap_R_RegisterShaderNoMip().
Referenced by SpecifyLeague_MenuInit().
SpecifyLeague_Event()
static void SpecifyLeague_Event (void * ptr, int event) static
Definition at line 122 of file ui_specifyleague.c.
 {
     int     id;
     id = ((menucommon_s*)ptr)->id;
     //if( event != QM_ACTIVATED && id != ID_SPECIFYLEAGUELIST ) {
     //  return;
     //}
     switch (id)
     {
         case ID_SPECIFYLEAGUELIST:
             if( event == QM_GOTFOCUS ) {
                 //ArenaServers_UpdatePicture();
             }
         break;
         case ID_SPECIFYLEAGUEUP:
             if( event == QM_ACTIVATED )
                 ScrollList_Key( &s_specifyleague.list, K_UPARROW );
         break;
         case ID_SPECIFYLEAGUEDOWN:
             if( event == QM_ACTIVATED )
                 ScrollList_Key( &s_specifyleague.list, K_DOWNARROW );
         break;
         case ID_SPECIFYLEAGUENAME:
             if( (event == QM_LOSTFOCUS) &&
                 (Q_strncmp(playername,
                     s_specifyleague.rankname.field.buffer,
                     strlen(s_specifyleague.rankname.field.buffer)) != 0))
             {
                 SpecifyLeague_GetList();
             }
         break;
         case ID_SPECIFYLEAGUEBACK:
             if( event == QM_ACTIVATED )
             {
                 trap_Cvar_Set( "sv_leagueName", league_table[s_specifyleague.list.curvalue].leaguename);
                 UI_PopMenu();
             }
         break;
     }
 }
References mfield_t::buffer, menulist_s::curvalue, menufield_s::field, ID_SPECIFYLEAGUEBACK, ID_SPECIFYLEAGUEDOWN, ID_SPECIFYLEAGUELIST, ID_SPECIFYLEAGUENAME, ID_SPECIFYLEAGUEUP, K_DOWNARROW, K_UPARROW, league_table, table_t::leaguename, specifyleague_t::list, playername, Q_strncmp(), QM_ACTIVATED, QM_GOTFOCUS, QM_LOSTFOCUS, specifyleague_t::rankname, s_specifyleague, ScrollList_Key(), SpecifyLeague_GetList(), trap_Cvar_Set(), and UI_PopMenu().
Referenced by SpecifyLeague_MenuInit().
SpecifyLeague_GetList()
static void SpecifyLeague_GetList () static
Definition at line 93 of file ui_specifyleague.c.
 {
     int count = 0;
     int i;
     /* The Player Name has changed. We need to perform another search */
     Q_strncpyz( playername,
         s_specifyleague.rankname.field.buffer,
         sizeof(playername) );
     count = trap_CL_UI_RankGetLeauges( playername );
     for(i = 0; i < count; i++)
     {
         char    s[MAX_LEAGUENAME];
         const char  *var;
         var = va( "leaguename%i", i+1 );
         trap_Cvar_VariableStringBuffer( var, s, sizeof(s) );
         Q_strncpyz(league_table[i].leaguename, s, sizeof(league_table[i].leaguename) );
         Q_strncpyz(league_table[i].buff, league_table[i].leaguename, sizeof(league_table[i].buff) );
     }
     s_specifyleague.list.numitems = count;
 }
References mfield_t::buffer, count, menufield_s::field, league_table, specifyleague_t::list, MAX_LEAGUENAME, menulist_s::numitems, playername, Q_strncpyz(), specifyleague_t::rankname, s, s_specifyleague, trap_Cvar_VariableStringBuffer(), and va().
Referenced by SpecifyLeague_Event(), and SpecifyLeague_MenuInit().
SpecifyLeague_MenuInit()
void SpecifyLeague_MenuInit (void)
Definition at line 173 of file ui_specifyleague.c.
 {
     int i;
     // zero set all our globals
     memset( &s_specifyleague, 0 ,sizeof(specifyleague_t) );
     SpecifyLeague_Cache();
     s_specifyleague.menu.wrapAround = qtrue;
     s_specifyleague.menu.fullscreen = qtrue;
     s_specifyleague.banner.generic.type  = MTYPE_BTEXT;
     s_specifyleague.banner.generic.x     = 320;
     s_specifyleague.banner.generic.y     = 16;
     s_specifyleague.banner.string        = "CHOOSE LEAGUE";
     s_specifyleague.banner.color         = color_white;
     s_specifyleague.banner.style         = UI_CENTER;
     s_specifyleague.framel.generic.type  = MTYPE_BITMAP;
     s_specifyleague.framel.generic.name  = SPECIFYLEAGUE_FRAMEL;
     s_specifyleague.framel.generic.flags = QMF_INACTIVE;
     s_specifyleague.framel.generic.x     = 0;
     s_specifyleague.framel.generic.y     = 78;
     s_specifyleague.framel.width         = 256;
     s_specifyleague.framel.height        = 334;
     s_specifyleague.framer.generic.type  = MTYPE_BITMAP;
     s_specifyleague.framer.generic.name  = SPECIFYLEAGUE_FRAMER;
     s_specifyleague.framer.generic.flags = QMF_INACTIVE;
     s_specifyleague.framer.generic.x     = 376;
     s_specifyleague.framer.generic.y     = 76;
     s_specifyleague.framer.width         = 256;
     s_specifyleague.framer.height        = 334;
     s_specifyleague.grlogo.generic.type  = MTYPE_BITMAP;
     s_specifyleague.grlogo.generic.name  = GLOBALRANKINGS_LOGO;
     s_specifyleague.grlogo.generic.flags = QMF_INACTIVE;
     s_specifyleague.grlogo.generic.x     = 0;
     s_specifyleague.grlogo.generic.y     = 0;
     s_specifyleague.grlogo.width         = 64;
     s_specifyleague.grlogo.height        = 128;
     s_specifyleague.rankname.generic.type       = MTYPE_FIELD;
     s_specifyleague.rankname.generic.name       = "Player Name:";
     s_specifyleague.rankname.generic.flags      = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     s_specifyleague.rankname.generic.callback   = SpecifyLeague_Event;
     s_specifyleague.rankname.generic.id         = ID_SPECIFYLEAGUENAME;
     s_specifyleague.rankname.generic.x          = 226;
     s_specifyleague.rankname.generic.y          = 128;
     s_specifyleague.rankname.field.widthInChars = 32;
     s_specifyleague.rankname.field.maxchars     = 80;
     s_specifyleague.list.generic.type           = MTYPE_SCROLLLIST;
     s_specifyleague.list.generic.flags          = QMF_HIGHLIGHT_IF_FOCUS;
     s_specifyleague.list.generic.id             = ID_SPECIFYLEAGUELIST;
     s_specifyleague.list.generic.callback       = SpecifyLeague_Event;
     s_specifyleague.list.generic.x              = 160;
     s_specifyleague.list.generic.y              = 200;
     s_specifyleague.list.width                  = MAX_LISTBOXWIDTH;
     s_specifyleague.list.height                 = 8;
     s_specifyleague.list.itemnames              = (const char **)leaguename_items;
     s_specifyleague.list.numitems               = 0;
     for( i = 0; i < MAX_LISTBOXITEMS; i++ ) {
         league_table[i].buff[0] = 0;
         league_table[i].leaguename[0] = 0;
         leaguename_items[i] = league_table[i].buff;
     }
     s_specifyleague.arrows.generic.type         = MTYPE_BITMAP;
     s_specifyleague.arrows.generic.name         = SPECIFYLEAGUE_ARROWS0;
     s_specifyleague.arrows.generic.flags        = QMF_LEFT_JUSTIFY|QMF_INACTIVE;
     s_specifyleague.arrows.generic.callback     = SpecifyLeague_Event;
     s_specifyleague.arrows.generic.x            = 512;
     s_specifyleague.arrows.generic.y            = 240-64+16;
     s_specifyleague.arrows.width                = 64;
     s_specifyleague.arrows.height               = 128;
     s_specifyleague.up.generic.type             = MTYPE_BITMAP;
     s_specifyleague.up.generic.flags            = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_specifyleague.up.generic.callback         = SpecifyLeague_Event;
     s_specifyleague.up.generic.id               = ID_SPECIFYLEAGUEUP;
     s_specifyleague.up.generic.x                = 512;
     s_specifyleague.up.generic.y                = 240-64+16;
     s_specifyleague.up.width                    = 64;
     s_specifyleague.up.height                   = 64;
     s_specifyleague.up.focuspic                 = SPECIFYLEAGUE_UP;
     s_specifyleague.down.generic.type           = MTYPE_BITMAP;
     s_specifyleague.down.generic.flags          = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_specifyleague.down.generic.callback       = SpecifyLeague_Event;
     s_specifyleague.down.generic.id             = ID_SPECIFYLEAGUEDOWN;
     s_specifyleague.down.generic.x              = 512;
     s_specifyleague.down.generic.y              = 240+16;
     s_specifyleague.down.width                  = 64;
     s_specifyleague.down.height                 = 64;
     s_specifyleague.down.focuspic               = SPECIFYLEAGUE_DOWN;
     s_specifyleague.back.generic.type     = MTYPE_BITMAP;
     s_specifyleague.back.generic.name     = SPECIFYLEAGUE_BACK0;
     s_specifyleague.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_specifyleague.back.generic.callback = SpecifyLeague_Event;
     s_specifyleague.back.generic.id       = ID_SPECIFYLEAGUEBACK;
     s_specifyleague.back.generic.x        = 0;
     s_specifyleague.back.generic.y        = 480-64;
     s_specifyleague.back.width            = 128;
     s_specifyleague.back.height           = 64;
     s_specifyleague.back.focuspic         = SPECIFYLEAGUE_BACK1;
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.banner );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.framel );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.framer );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.grlogo );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.rankname );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.list );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.arrows );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.up );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.down );
     Menu_AddItem( &s_specifyleague.menu, &s_specifyleague.back );
     // initialize any menu variables
     Q_strncpyz( s_specifyleague.rankname.field.buffer,
         UI_Cvar_VariableString("name"),
         sizeof(s_specifyleague.rankname.field.buffer) );
     Q_strncpyz( playername,
         UI_Cvar_VariableString("name"),
         sizeof(playername) );
     SpecifyLeague_GetList();
 }
References specifyleague_t::arrows, specifyleague_t::back, specifyleague_t::banner, table_t::buff, mfield_t::buffer, menucommon_s::callback, menutext_s::color, color_white, specifyleague_t::down, menufield_s::field, menucommon_s::flags, menubitmap_s::focuspic, specifyleague_t::framel, specifyleague_t::framer, _tag_menuframework::fullscreen, menufield_s::generic, menulist_s::generic, menubitmap_s::generic, menutext_s::generic, GLOBALRANKINGS_LOGO, specifyleague_t::grlogo, menulist_s::height, menubitmap_s::height, menucommon_s::id, ID_SPECIFYLEAGUEBACK, ID_SPECIFYLEAGUEDOWN, ID_SPECIFYLEAGUELIST, ID_SPECIFYLEAGUENAME, ID_SPECIFYLEAGUEUP, menulist_s::itemnames, league_table, table_t::leaguename, leaguename_items, specifyleague_t::list, MAX_LISTBOXITEMS, MAX_LISTBOXWIDTH, mfield_t::maxchars, specifyleague_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_SCROLLLIST, menucommon_s::name, menulist_s::numitems, playername, Q_strncpyz(), QMF_HIGHLIGHT_IF_FOCUS, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_MOUSEONLY, QMF_PULSEIFFOCUS, QMF_SMALLFONT, qtrue, specifyleague_t::rankname, s_specifyleague, SPECIFYLEAGUE_ARROWS0, SPECIFYLEAGUE_BACK0, SPECIFYLEAGUE_BACK1, SpecifyLeague_Cache(), SPECIFYLEAGUE_DOWN, SpecifyLeague_Event(), SPECIFYLEAGUE_FRAMEL, SPECIFYLEAGUE_FRAMER, SpecifyLeague_GetList(), SPECIFYLEAGUE_UP, menutext_s::string, menutext_s::style, menucommon_s::type, UI_CENTER, UI_Cvar_VariableString(), specifyleague_t::up, menulist_s::width, menubitmap_s::width, mfield_t::widthInChars, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_SpecifyLeagueMenu().
UI_SpecifyLeagueMenu()
void UI_SpecifyLeagueMenu (void)
Definition at line 328 of file ui_specifyleague.c.
 {
     SpecifyLeague_MenuInit();
     UI_PushMenu( &s_specifyleague.menu );
 }
References specifyleague_t::menu, s_specifyleague, SpecifyLeague_MenuInit(), and UI_PushMenu().
Variable Documentation
league_table
table_t league_table[MAX_LISTBOXITEMS]
Definition at line 89 of file ui_specifyleague.c.
Referenced by SpecifyLeague_Event(), SpecifyLeague_GetList(), and SpecifyLeague_MenuInit().
leaguename_items
char* leaguename_items[MAX_LISTBOXITEMS]
Definition at line 90 of file ui_specifyleague.c.
Referenced by SpecifyLeague_MenuInit().
playername
char playername[80] static
Definition at line 63 of file ui_specifyleague.c.
Referenced by Controls_MenuInit(), PlayerModel_MenuInit(), SpecifyLeague_Event(), SpecifyLeague_GetList(), and SpecifyLeague_MenuInit().
s_specifyleague
specifyleague_t s_specifyleague static
Definition at line 81 of file ui_specifyleague.c.
Referenced by SpecifyLeague_Event(), SpecifyLeague_GetList(), SpecifyLeague_MenuInit(), and UI_SpecifyLeagueMenu().
specifyleague_artlist
char* specifyleague_artlist[] static
Initial value:
=
{
    SPECIFYLEAGUE_FRAMEL,
    SPECIFYLEAGUE_FRAMER,
    SPECIFYLEAGUE_ARROWS0,
    SPECIFYLEAGUE_UP,
    SPECIFYLEAGUE_DOWN,
    SPECIFYLEAGUE_BACK0,
    SPECIFYLEAGUE_BACK1,
    GLOBALRANKINGS_LOGO,
    GLOBALRANKINGS_LETTERS,
    NULL
}
Definition at line 49 of file ui_specifyleague.c.
Referenced by SpecifyLeague_Cache().