ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_log.c File Reference
l_log.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "botlib.h"
#include "be_interface.h"
#include "l_libvar.h"
#include "l_log.h"
Classes
struct logfile_s
Macros
#define MAX_LOGFILENAMESIZE 1024
Typedefs
typedef struct logfile_s logfile_t
Functions
void Log_Open (char *filename)
void Log_Close (void)
void Log_Shutdown (void)
void QDECL Log_Write (char *fmt,...)
void QDECL Log_WriteTimeStamped (char *fmt,...)
FILE * Log_FilePointer (void)
void Log_Flush (void)
Variables
static logfile_t logfile
Macro Definition Documentation
MAX_LOGFILENAMESIZE
#define MAX_LOGFILENAMESIZE 1024
Definition at line 43 of file l_log.c.
Typedef Documentation
logfile_t
typedef struct logfile_s logfile_t
Function Documentation
Log_Close()
void Log_Close (void)
Definition at line 90 of file l_log.c.
 {
     if (!logfile.fp) return;
     if (fclose(logfile.fp))
     {
         botimport.Print(PRT_ERROR, "can't close log file %s\n", logfile.filename);
         return;
     } //end if
     logfile.fp = NULL;
     botimport.Print(PRT_MESSAGE, "Closed log %s\n", logfile.filename);
 } //end of the function Log_Close
References botimport, logfile_s::filename, logfile_s::fp, logfile, NULL, PRT_ERROR, and PRT_MESSAGE.
Referenced by Log_Shutdown().
Log_FilePointer()
FILE* Log_FilePointer (void)
Definition at line 159 of file l_log.c.
 {
     return logfile.fp;
 } //end of the function Log_FilePointer
References logfile_s::fp, and logfile.
Referenced by BotDumpMatchTemplates(), BotDumpRandomStringList(), BotDumpReplyChat(), and BotDumpSynonymList().
Log_Flush()
void Log_Flush (void)
Definition at line 169 of file l_log.c.
 {
     if (logfile.fp) fflush(logfile.fp);
 } //end of the function Log_Flush
References logfile_s::fp, and logfile.
Log_Open()
void Log_Open (char * filename)
Definition at line 60 of file l_log.c.
 {
     char *ospath;
     if (!LibVarValue("log", "0")) return;
     if (!filename || !strlen(filename))
     {
         botimport.Print(PRT_MESSAGE, "openlog <filename>\n");
         return;
     } //end if
     if (logfile.fp)
     {
         botimport.Print(PRT_ERROR, "log file %s is already opened\n", logfile.filename);
         return;
     } //end if
     ospath = FS_BuildOSPath(Cvar_VariableString("fs_homepath"), Cvar_VariableString("fs_game"), filename);
     logfile.fp = fopen(ospath, "wb");
     if (!logfile.fp)
     {
         botimport.Print(PRT_ERROR, "can't open the log file %s\n", filename);
         return;
     } //end if
     Q_strncpyz(logfile.filename, filename, MAX_LOGFILENAMESIZE);
     botimport.Print(PRT_MESSAGE, "Opened log %s\n", logfile.filename);
 } //end of the function Log_Create
References botimport, Cvar_VariableString(), logfile_s::filename, logfile_s::fp, FS_BuildOSPath(), LibVarValue(), logfile, MAX_LOGFILENAMESIZE, PRT_ERROR, PRT_MESSAGE, and Q_strncpyz().
Referenced by Export_BotLibSetup().
Log_Shutdown()
void Log_Shutdown (void)
Definition at line 107 of file l_log.c.
 {
     if (logfile.fp) Log_Close();
 } //end of the function Log_Shutdown
References logfile_s::fp, Log_Close(), and logfile.
Referenced by Export_BotLibShutdown().
Log_Write()
void QDECL Log_Write (char * fmt, ...)
Definition at line 117 of file l_log.c.
 {
     va_list ap;
     if (!logfile.fp) return;
     va_start(ap, fmt);
     vfprintf(logfile.fp, fmt, ap);
     va_end(ap);
     //fprintf(logfile.fp, "\r\n");
     fflush(logfile.fp);
 } //end of the function Log_Write
References logfile_s::fp, and logfile.
Referenced by AAS_AlternativeRouteGoals(), AAS_BestReachableArea(), AAS_CheckAreaForPossiblePortals(), AAS_CountForcedClusterPortals(), AAS_InitClustering(), AAS_RandomGoalArea(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Ladder(), AAS_Reachability_WeaponJump(), AAS_TestPortals(), AAS_UpdatePortal(), BotCheckChatMessageIntegrety(), BotDumpAvoidGoals(), BotDumpCharacter(), BotDumpGoalStack(), BotDumpInitialChat(), BotInitLevelItems(), BotUpdateEntityItems(), ItemWeightIndex(), PC_DollarEvaluate(), PC_Evaluate(), PC_EvaluateTokens(), PC_ExpandDefine(), and PC_PrintDefineHashTable().
Log_WriteTimeStamped()
void QDECL Log_WriteTimeStamped (char * fmt, ...)
Definition at line 134 of file l_log.c.
 {
     va_list ap;
     if (!logfile.fp) return;
     fprintf(logfile.fp, "%d   %02d:%02d:%02d:%02d   ",
                     logfile.numwrites,
                     (int) (botlibglobals.time / 60 / 60),
                     (int) (botlibglobals.time / 60),
                     (int) (botlibglobals.time),
                     (int) ((int) (botlibglobals.time * 100)) -
                             ((int) botlibglobals.time) * 100);
     va_start(ap, fmt);
     vfprintf(logfile.fp, fmt, ap);
     va_end(ap);
     fprintf(logfile.fp, "\r\n");
     logfile.numwrites++;
     fflush(logfile.fp);
 } //end of the function Log_Write
References botlibglobals, logfile_s::fp, logfile, logfile_s::numwrites, and botlib_globals_s::time.
Variable Documentation
logfile
logfile_t logfile static
Definition at line 52 of file l_log.c.
Referenced by Log_Close(), Log_FilePointer(), Log_Flush(), Log_Open(), Log_Shutdown(), Log_Write(), and Log_WriteTimeStamped().