ioquake3 doxygen: C:/entry/dev/ioquake3/code/q3_ui/ui_demo2.c File Reference
ui_demo2.c File Reference
#include "ui_local.h"
Classes
struct demos_t
Macros
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_GO0 "menu/art/play_0"
#define ART_GO1 "menu/art/play_1"
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define ART_ARROWS "menu/art/arrows_horz_0"
#define ART_ARROWLEFT "menu/art/arrows_horz_left"
#define ART_ARROWRIGHT "menu/art/arrows_horz_right"
#define MAX_DEMOS 1024
#define NAMEBUFSIZE (MAX_DEMOS * 32)
#define ID_BACK 10
#define ID_GO 11
#define ID_LIST 12
#define ID_RIGHT 13
#define ID_LEFT 14
#define ARROWS_WIDTH 128
#define ARROWS_HEIGHT 48
Functions
static void Demos_MenuEvent (void *ptr, int event)
static void Demos_MenuInit (void)
void Demos_Cache (void)
void UI_DemosMenu (void)
Variables
static demos_t s_demos
Macro Definition Documentation
ARROWS_HEIGHT
#define ARROWS_HEIGHT 48
Definition at line 55 of file ui_demo2.c.
ARROWS_WIDTH
#define ARROWS_WIDTH 128
Definition at line 54 of file ui_demo2.c.
ART_ARROWLEFT
#define ART_ARROWLEFT "menu/art/arrows_horz_left"
Definition at line 42 of file ui_demo2.c.
ART_ARROWRIGHT
#define ART_ARROWRIGHT "menu/art/arrows_horz_right"
Definition at line 43 of file ui_demo2.c.
ART_ARROWS
#define ART_ARROWS "menu/art/arrows_horz_0"
Definition at line 41 of file ui_demo2.c.
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 35 of file ui_demo2.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 36 of file ui_demo2.c.
ART_FRAMEL
#define ART_FRAMEL "menu/art/frame2_l"
Definition at line 39 of file ui_demo2.c.
ART_FRAMER
#define ART_FRAMER "menu/art/frame1_r"
Definition at line 40 of file ui_demo2.c.
ART_GO0
#define ART_GO0 "menu/art/play_0"
Definition at line 37 of file ui_demo2.c.
ART_GO1
#define ART_GO1 "menu/art/play_1"
Definition at line 38 of file ui_demo2.c.
ID_BACK
#define ID_BACK 10
Definition at line 48 of file ui_demo2.c.
ID_GO
#define ID_GO 11
Definition at line 49 of file ui_demo2.c.
ID_LEFT
#define ID_LEFT 14
Definition at line 52 of file ui_demo2.c.
ID_LIST
#define ID_LIST 12
Definition at line 50 of file ui_demo2.c.
ID_RIGHT
#define ID_RIGHT 13
Definition at line 51 of file ui_demo2.c.
MAX_DEMOS
#define MAX_DEMOS 1024
Definition at line 45 of file ui_demo2.c.
NAMEBUFSIZE
#define NAMEBUFSIZE (MAX_DEMOS * 32)
Definition at line 46 of file ui_demo2.c.
Function Documentation
Demos_Cache()
void Demos_Cache (void)
Definition at line 284 of file ui_demo2.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_GO0 );
     trap_R_RegisterShaderNoMip( ART_GO1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_ARROWS );
     trap_R_RegisterShaderNoMip( ART_ARROWLEFT );
     trap_R_RegisterShaderNoMip( ART_ARROWRIGHT );
 }
Referenced by Demos_MenuInit(), and UI_Cache_f().
Demos_MenuEvent()
static void Demos_MenuEvent (void * ptr, int event) static
Definition at line 87 of file ui_demo2.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch( ((menucommon_s*)ptr)->id ) {
     case ID_GO:
         UI_ForceMenuOff ();
         trap_Cmd_ExecuteText( EXEC_APPEND, va( "demo %s\n",
                                 s_demos.list.itemnames[s_demos.list.curvalue]) );
         break;
     case ID_BACK:
         UI_PopMenu();
         break;
     case ID_LEFT:
         ScrollList_Key( &s_demos.list, K_LEFTARROW );
         break;
     case ID_RIGHT:
         ScrollList_Key( &s_demos.list, K_RIGHTARROW );
         break;
     }
 }
Referenced by Demos_MenuInit().
Demos_MenuInit()
static void Demos_MenuInit (void) static
Definition at line 119 of file ui_demo2.c.
{
     int     i, j;
     int     len;
     char    *demoname, extension[32];
     int protocol, protocolLegacy;
     memset( &s_demos, 0 ,sizeof(demos_t) );
     Demos_Cache();
     s_demos.menu.fullscreen = qtrue;
     s_demos.menu.wrapAround = qtrue;
     s_demos.banner.generic.type     = MTYPE_BTEXT;
     s_demos.banner.generic.x        = 320;
     s_demos.banner.generic.y        = 16;
     s_demos.banner.string           = "DEMOS";
     s_demos.banner.color            = color_white;
     s_demos.banner.style            = UI_CENTER;
     s_demos.framel.generic.type     = MTYPE_BITMAP;
     s_demos.framel.generic.name     = ART_FRAMEL;
     s_demos.framel.generic.flags    = QMF_INACTIVE;
     s_demos.framel.generic.x        = 0;
     s_demos.framel.generic.y        = 78;
     s_demos.framel.width            = 256;
     s_demos.framel.height           = 329;
     s_demos.framer.generic.type     = MTYPE_BITMAP;
     s_demos.framer.generic.name     = ART_FRAMER;
     s_demos.framer.generic.flags    = QMF_INACTIVE;
     s_demos.framer.generic.x        = 376;
     s_demos.framer.generic.y        = 76;
     s_demos.framer.width            = 256;
     s_demos.framer.height           = 334;
     s_demos.arrows.generic.type     = MTYPE_BITMAP;
     s_demos.arrows.generic.name     = ART_ARROWS;
     s_demos.arrows.generic.flags    = QMF_INACTIVE;
     s_demos.arrows.generic.x        = 320-ARROWS_WIDTH/2;
     s_demos.arrows.generic.y        = 400;
     s_demos.arrows.width            = ARROWS_WIDTH;
     s_demos.arrows.height           = ARROWS_HEIGHT;
     s_demos.left.generic.type       = MTYPE_BITMAP;
     s_demos.left.generic.flags      = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_demos.left.generic.x          = 320-ARROWS_WIDTH/2;
     s_demos.left.generic.y          = 400;
     s_demos.left.generic.id         = ID_LEFT;
     s_demos.left.generic.callback   = Demos_MenuEvent;
     s_demos.left.width              = ARROWS_WIDTH/2;
     s_demos.left.height             = ARROWS_HEIGHT;
     s_demos.left.focuspic           = ART_ARROWLEFT;
     s_demos.right.generic.type      = MTYPE_BITMAP;
     s_demos.right.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_demos.right.generic.x         = 320;
     s_demos.right.generic.y         = 400;
     s_demos.right.generic.id        = ID_RIGHT;
     s_demos.right.generic.callback  = Demos_MenuEvent;
     s_demos.right.width             = ARROWS_WIDTH/2;
     s_demos.right.height            = ARROWS_HEIGHT;
     s_demos.right.focuspic          = ART_ARROWRIGHT;
     s_demos.back.generic.type       = MTYPE_BITMAP;
     s_demos.back.generic.name       = ART_BACK0;
     s_demos.back.generic.flags      = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_demos.back.generic.id         = ID_BACK;
     s_demos.back.generic.callback   = Demos_MenuEvent;
     s_demos.back.generic.x          = 0;
     s_demos.back.generic.y          = 480-64;
     s_demos.back.width              = 128;
     s_demos.back.height             = 64;
     s_demos.back.focuspic           = ART_BACK1;
     s_demos.go.generic.type         = MTYPE_BITMAP;
     s_demos.go.generic.name         = ART_GO0;
     s_demos.go.generic.flags        = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_demos.go.generic.id           = ID_GO;
     s_demos.go.generic.callback     = Demos_MenuEvent;
     s_demos.go.generic.x            = 640;
     s_demos.go.generic.y            = 480-64;
     s_demos.go.width                = 128;
     s_demos.go.height               = 64;
     s_demos.go.focuspic             = ART_GO1;
     s_demos.list.generic.type       = MTYPE_SCROLLLIST;
     s_demos.list.generic.flags      = QMF_PULSEIFFOCUS;
     s_demos.list.generic.callback   = Demos_MenuEvent;
     s_demos.list.generic.id         = ID_LIST;
     s_demos.list.generic.x          = 118;
     s_demos.list.generic.y          = 130;
     s_demos.list.width              = 16;
     s_demos.list.height             = 14;
     s_demos.list.itemnames          = (const char **)s_demos.demolist;
     s_demos.list.columns            = 3;
     protocolLegacy = trap_Cvar_VariableValue("com_legacyprotocol");
     protocol = trap_Cvar_VariableValue("com_protocol");
     if(!protocol)
         protocol = trap_Cvar_VariableValue("protocol");
     if(protocolLegacy == protocol)
         protocolLegacy = 0;
     Com_sprintf(extension, sizeof(extension), ".%s%d", DEMOEXT, protocol);
     s_demos.numDemos = trap_FS_GetFileList("demos", extension, s_demos.names, ARRAY_LEN(s_demos.names));
     demoname = s_demos.names;
     i = 0;
     for(j = 0; j < 2; j++)
     {
         if(s_demos.numDemos > MAX_DEMOS)
             s_demos.numDemos = MAX_DEMOS;
         for(; i < s_demos.numDemos; i++)
         {
             s_demos.list.itemnames[i] = demoname;
             len = strlen(demoname);
             demoname += len + 1;
         }
         if(!j)
         {
             if(protocolLegacy > 0 && s_demos.numDemos < MAX_DEMOS)
             {
                 Com_sprintf(extension, sizeof(extension), ".%s%d", DEMOEXT, protocolLegacy);
                 s_demos.numDemos += trap_FS_GetFileList("demos", extension, demoname,
                                     ARRAY_LEN(s_demos.names) - (demoname - s_demos.names));
             }
             else
                 break;
         }
     }
     s_demos.list.numitems = s_demos.numDemos;
     if(!s_demos.numDemos)
     {
         s_demos.list.itemnames[0] = "No Demos Found.";
         s_demos.list.numitems = 1;
         //degenerate case, not selectable
         s_demos.go.generic.flags |= (QMF_INACTIVE|QMF_HIDDEN);
     }
     Menu_AddItem( &s_demos.menu, &s_demos.banner );
     Menu_AddItem( &s_demos.menu, &s_demos.framel );
     Menu_AddItem( &s_demos.menu, &s_demos.framer );
     Menu_AddItem( &s_demos.menu, &s_demos.list );
     Menu_AddItem( &s_demos.menu, &s_demos.arrows );
     Menu_AddItem( &s_demos.menu, &s_demos.left );
     Menu_AddItem( &s_demos.menu, &s_demos.right );
     Menu_AddItem( &s_demos.menu, &s_demos.back );
     Menu_AddItem( &s_demos.menu, &s_demos.go );
 }
Referenced by UI_DemosMenu().
UI_DemosMenu()
void UI_DemosMenu (void)
Definition at line 301 of file ui_demo2.c.
{
     Demos_MenuInit();
     UI_PushMenu( &s_demos.menu );
 }
Referenced by Main_MenuEvent().
Variable Documentation
s_demos
demos_t s_demos static
Definition at line 79 of file ui_demo2.c.
Referenced by Demos_MenuEvent(), Demos_MenuInit(), and UI_DemosMenu().