ioquake3 doxygen: C:/entry/dev/ioq3/code/sys/sys_loadlib.h File Reference
sys_loadlib.h File Reference
#include <SDL.h>
#include <SDL_loadso.h>
Macros
#define Sys_LoadLibrary(f) SDL_LoadObject(f)
#define Sys_UnloadLibrary(h) SDL_UnloadObject(h)
#define Sys_LoadFunction(h, fn) SDL_LoadFunction(h,fn)
#define Sys_LibraryError() SDL_GetError()
Functions
void *QDECL Sys_LoadDll (const char *name, qboolean useSystemLib)
Macro Definition Documentation
Sys_LibraryError
#define Sys_LibraryError () SDL_GetError()
Definition at line 48 of file sys_loadlib.h.
Sys_LoadFunction
#define Sys_LoadFunction (h, fn) SDL_LoadFunction(h,fn)
Definition at line 47 of file sys_loadlib.h.
Sys_LoadLibrary
#define Sys_LoadLibrary (f) SDL_LoadObject(f)
Definition at line 45 of file sys_loadlib.h.
Sys_UnloadLibrary
#define Sys_UnloadLibrary (h) SDL_UnloadObject(h)
Definition at line 46 of file sys_loadlib.h.
Function Documentation
Sys_LoadDll()
void* QDECL Sys_LoadDll (const char * name, qboolean useSystemLib)
Definition at line 470 of file sys_main.c.
 {
     void* dllhandle = NULL;
     if (!Sys_DllExtension(name)) {
         Com_Printf("Refusing to attempt to load library \"%s\": Extension not allowed.\n", name);
         return NULL;
     }
     if (useSystemLib) {
         Com_Printf("Trying to load \"%s\"...\n", name);
         dllhandle = Sys_LoadLibrary(name);
     }
     if (!dllhandle) {
         const char* topDir;
         char libPath[MAX_OSPATH];
         int len;
         topDir = Sys_BinaryPath();
         if (!*topDir)
             topDir = ".";
         len = Com_sprintf(libPath, sizeof(libPath), "%s%c%s", topDir, PATH_SEP, name);
         if (len < sizeof(libPath)) {
             Com_Printf("Trying to load \"%s\" from \"%s\"...\n", name, topDir);
             dllhandle = Sys_LoadLibrary(libPath);
         }
         else {
             Com_Printf("Skipping trying to load \"%s\" from \"%s\", file name is too long.\n", name, topDir);
         }
         if (!dllhandle) {
             const char* basePath = Cvar_VariableString("fs_basepath");
             if (!basePath || !*basePath)
                 basePath = ".";
             if (FS_FilenameCompare(topDir, basePath)) {
                 len = Com_sprintf(libPath, sizeof(libPath), "%s%c%s", basePath, PATH_SEP, name);
                 if (len < sizeof(libPath)) {
                     Com_Printf("Trying to load \"%s\" from \"%s\"...\n", name, basePath);
                     dllhandle = Sys_LoadLibrary(libPath);
                 }
                 else {
                     Com_Printf("Skipping trying to load \"%s\" from \"%s\", file name is too long.\n", name, basePath);
                 }
             }
             if (!dllhandle)
                 Com_Printf("Loading \"%s\" failed\n", name);
         }
     }
     return dllhandle;
 }
References Com_Printf(), Com_sprintf(), Cvar_VariableString(), FS_FilenameCompare(), MAX_OSPATH, NULL, PATH_SEP, Sys_BinaryPath(), Sys_DllExtension(), and Sys_LoadLibrary.
Referenced by CL_InitRef().