ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_controls2.c File Reference
ui_controls2.c File Reference
#include "ui_local.h"
Classes
struct bind_t
struct configcvar_t
struct controls_t
Macros
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define SAVE_NOOP 0
#define SAVE_YES 1
#define SAVE_NO 2
#define SAVE_CANCEL 3
#define C_MOVEMENT 0
#define C_LOOKING 1
#define C_WEAPONS 2
#define C_MISC 3
#define C_MAX 4
#define ID_MOVEMENT 100
#define ID_LOOKING 101
#define ID_WEAPONS 102
#define ID_MISC 103
#define ID_DEFAULTS 104
#define ID_BACK 105
#define ID_SAVEANDEXIT 106
#define ID_EXIT 107
#define ID_SHOWSCORES 0
#define ID_USEITEM 1
#define ID_SPEED 2
#define ID_FORWARD 3
#define ID_BACKPEDAL 4
#define ID_MOVELEFT 5
#define ID_MOVERIGHT 6
#define ID_MOVEUP 7
#define ID_MOVEDOWN 8
#define ID_LEFT 9
#define ID_RIGHT 10
#define ID_STRAFE 11
#define ID_LOOKUP 12
#define ID_LOOKDOWN 13
#define ID_MOUSELOOK 14
#define ID_CENTERVIEW 15
#define ID_ZOOMVIEW 16
#define ID_WEAPON1 17
#define ID_WEAPON2 18
#define ID_WEAPON3 19
#define ID_WEAPON4 20
#define ID_WEAPON5 21
#define ID_WEAPON6 22
#define ID_WEAPON7 23
#define ID_WEAPON8 24
#define ID_WEAPON9 25
#define ID_ATTACK 26
#define ID_WEAPPREV 27
#define ID_WEAPNEXT 28
#define ID_GESTURE 29
#define ID_CHAT 30
#define ID_CHAT2 31
#define ID_CHAT3 32
#define ID_CHAT4 33
#define ID_TOGGLEMENU 34
#define ID_FREELOOK 35
#define ID_INVERTMOUSE 36
#define ID_ALWAYSRUN 37
#define ID_AUTOSWITCH 38
#define ID_MOUSESPEED 39
#define ID_JOYENABLE 40
#define ID_JOYTHRESHOLD 41
#define ID_SMOOTHMOUSE 42
#define ANIM_IDLE 0
#define ANIM_RUN 1
#define ANIM_WALK 2
#define ANIM_BACK 3
#define ANIM_JUMP 4
#define ANIM_CROUCH 5
#define ANIM_STEPLEFT 6
#define ANIM_STEPRIGHT 7
#define ANIM_TURNLEFT 8
#define ANIM_TURNRIGHT 9
#define ANIM_LOOKUP 10
#define ANIM_LOOKDOWN 11
#define ANIM_WEAPON1 12
#define ANIM_WEAPON2 13
#define ANIM_WEAPON3 14
#define ANIM_WEAPON4 15
#define ANIM_WEAPON5 16
#define ANIM_WEAPON6 17
#define ANIM_WEAPON7 18
#define ANIM_WEAPON8 19
#define ANIM_WEAPON9 20
#define ANIM_WEAPON10 21
#define ANIM_ATTACK 22
#define ANIM_GESTURE 23
#define ANIM_DIE 24
#define ANIM_CHAT 25
Functions
static void Controls_InitCvars (void)
static float Controls_GetCvarDefault (char *name)
static float Controls_GetCvarValue (char *name)
static void Controls_UpdateModel (int anim)
static void Controls_Update (void)
static void Controls_DrawKeyBinding (void *self)
static void Controls_StatusBar (void *self)
static void Controls_DrawPlayer (void *self)
static void Controls_GetKeyAssignment (char *command, int *twokeys)
static void Controls_GetConfig (void)
static void Controls_SetConfig (void)
static void Controls_SetDefaults (void)
static sfxHandle_t Controls_MenuKey (int key)
static void Controls_ResetDefaults_Action (qboolean result)
static void Controls_ResetDefaults_Draw (void)
static void Controls_MenuEvent (void *ptr, int event)
static void Controls_ActionEvent (void *ptr, int event)
static void Controls_InitModel (void)
static void Controls_InitWeapons (void)
static void Controls_MenuInit (void)
void Controls_Cache (void)
void UI_ControlsMenu (void)
Variables
static controls_t s_controls
static vec4_t controls_binding_color = {1.00f, 0.43f, 0.00f, 1.00f}
static bind_t g_bindings []
static configcvar_t g_configcvars []
static menucommon_s * g_movement_controls []
static menucommon_s * g_weapons_controls []
static menucommon_s * g_looking_controls []
static menucommon_s * g_misc_controls []
static menucommon_s ** g_controls []
Macro Definition Documentation
ANIM_ATTACK
#define ANIM_ATTACK 22
Definition at line 148 of file ui_controls2.c.
ANIM_BACK
#define ANIM_BACK 3
Definition at line 129 of file ui_controls2.c.
ANIM_CHAT
#define ANIM_CHAT 25
Definition at line 151 of file ui_controls2.c.
ANIM_CROUCH
#define ANIM_CROUCH 5
Definition at line 131 of file ui_controls2.c.
ANIM_DIE
#define ANIM_DIE 24
Definition at line 150 of file ui_controls2.c.
ANIM_GESTURE
#define ANIM_GESTURE 23
Definition at line 149 of file ui_controls2.c.
ANIM_IDLE
#define ANIM_IDLE 0
Definition at line 126 of file ui_controls2.c.
ANIM_JUMP
#define ANIM_JUMP 4
Definition at line 130 of file ui_controls2.c.
ANIM_LOOKDOWN
#define ANIM_LOOKDOWN 11
Definition at line 137 of file ui_controls2.c.
ANIM_LOOKUP
#define ANIM_LOOKUP 10
Definition at line 136 of file ui_controls2.c.
ANIM_RUN
#define ANIM_RUN 1
Definition at line 127 of file ui_controls2.c.
ANIM_STEPLEFT
#define ANIM_STEPLEFT 6
Definition at line 132 of file ui_controls2.c.
ANIM_STEPRIGHT
#define ANIM_STEPRIGHT 7
Definition at line 133 of file ui_controls2.c.
ANIM_TURNLEFT
#define ANIM_TURNLEFT 8
Definition at line 134 of file ui_controls2.c.
ANIM_TURNRIGHT
#define ANIM_TURNRIGHT 9
Definition at line 135 of file ui_controls2.c.
ANIM_WALK
#define ANIM_WALK 2
Definition at line 128 of file ui_controls2.c.
ANIM_WEAPON1
#define ANIM_WEAPON1 12
Definition at line 138 of file ui_controls2.c.
ANIM_WEAPON10
#define ANIM_WEAPON10 21
Definition at line 147 of file ui_controls2.c.
ANIM_WEAPON2
#define ANIM_WEAPON2 13
Definition at line 139 of file ui_controls2.c.
ANIM_WEAPON3
#define ANIM_WEAPON3 14
Definition at line 140 of file ui_controls2.c.
ANIM_WEAPON4
#define ANIM_WEAPON4 15
Definition at line 141 of file ui_controls2.c.
ANIM_WEAPON5
#define ANIM_WEAPON5 16
Definition at line 142 of file ui_controls2.c.
ANIM_WEAPON6
#define ANIM_WEAPON6 17
Definition at line 143 of file ui_controls2.c.
ANIM_WEAPON7
#define ANIM_WEAPON7 18
Definition at line 144 of file ui_controls2.c.
ANIM_WEAPON8
#define ANIM_WEAPON8 19
Definition at line 145 of file ui_controls2.c.
ANIM_WEAPON9
#define ANIM_WEAPON9 20
Definition at line 146 of file ui_controls2.c.
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 34 of file ui_controls2.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 35 of file ui_controls2.c.
ART_FRAMEL
#define ART_FRAMEL "menu/art/frame2_l"
Definition at line 36 of file ui_controls2.c.
ART_FRAMER
#define ART_FRAMER "menu/art/frame1_r"
Definition at line 37 of file ui_controls2.c.
C_LOOKING
#define C_LOOKING 1
Definition at line 65 of file ui_controls2.c.
C_MAX
#define C_MAX 4
Definition at line 68 of file ui_controls2.c.
C_MISC
#define C_MISC 3
Definition at line 67 of file ui_controls2.c.
C_MOVEMENT
#define C_MOVEMENT 0
Definition at line 64 of file ui_controls2.c.
C_WEAPONS
#define C_WEAPONS 2
Definition at line 66 of file ui_controls2.c.
ID_ALWAYSRUN
#define ID_ALWAYSRUN 37
Definition at line 119 of file ui_controls2.c.
ID_ATTACK
#define ID_ATTACK 26
Definition at line 106 of file ui_controls2.c.
ID_AUTOSWITCH
#define ID_AUTOSWITCH 38
Definition at line 120 of file ui_controls2.c.
ID_BACK
#define ID_BACK 105
Definition at line 75 of file ui_controls2.c.
ID_BACKPEDAL
#define ID_BACKPEDAL 4
Definition at line 84 of file ui_controls2.c.
ID_CENTERVIEW
#define ID_CENTERVIEW 15
Definition at line 95 of file ui_controls2.c.
ID_CHAT
#define ID_CHAT 30
Definition at line 110 of file ui_controls2.c.
ID_CHAT2
#define ID_CHAT2 31
Definition at line 111 of file ui_controls2.c.
ID_CHAT3
#define ID_CHAT3 32
Definition at line 112 of file ui_controls2.c.
ID_CHAT4
#define ID_CHAT4 33
Definition at line 113 of file ui_controls2.c.
ID_DEFAULTS
#define ID_DEFAULTS 104
Definition at line 74 of file ui_controls2.c.
ID_EXIT
#define ID_EXIT 107
Definition at line 77 of file ui_controls2.c.
ID_FORWARD
#define ID_FORWARD 3
Definition at line 83 of file ui_controls2.c.
ID_FREELOOK
#define ID_FREELOOK 35
Definition at line 117 of file ui_controls2.c.
ID_GESTURE
#define ID_GESTURE 29
Definition at line 109 of file ui_controls2.c.
ID_INVERTMOUSE
#define ID_INVERTMOUSE 36
Definition at line 118 of file ui_controls2.c.
ID_JOYENABLE
#define ID_JOYENABLE 40
Definition at line 122 of file ui_controls2.c.
ID_JOYTHRESHOLD
#define ID_JOYTHRESHOLD 41
Definition at line 123 of file ui_controls2.c.
ID_LEFT
#define ID_LEFT 9
Definition at line 89 of file ui_controls2.c.
ID_LOOKDOWN
#define ID_LOOKDOWN 13
Definition at line 93 of file ui_controls2.c.
ID_LOOKING
#define ID_LOOKING 101
Definition at line 71 of file ui_controls2.c.
ID_LOOKUP
#define ID_LOOKUP 12
Definition at line 92 of file ui_controls2.c.
ID_MISC
#define ID_MISC 103
Definition at line 73 of file ui_controls2.c.
ID_MOUSELOOK
#define ID_MOUSELOOK 14
Definition at line 94 of file ui_controls2.c.
ID_MOUSESPEED
#define ID_MOUSESPEED 39
Definition at line 121 of file ui_controls2.c.
ID_MOVEDOWN
#define ID_MOVEDOWN 8
Definition at line 88 of file ui_controls2.c.
ID_MOVELEFT
#define ID_MOVELEFT 5
Definition at line 85 of file ui_controls2.c.
ID_MOVEMENT
#define ID_MOVEMENT 100
Definition at line 70 of file ui_controls2.c.
ID_MOVERIGHT
#define ID_MOVERIGHT 6
Definition at line 86 of file ui_controls2.c.
ID_MOVEUP
#define ID_MOVEUP 7
Definition at line 87 of file ui_controls2.c.
ID_RIGHT
#define ID_RIGHT 10
Definition at line 90 of file ui_controls2.c.
ID_SAVEANDEXIT
#define ID_SAVEANDEXIT 106
Definition at line 76 of file ui_controls2.c.
ID_SHOWSCORES
#define ID_SHOWSCORES 0
Definition at line 80 of file ui_controls2.c.
ID_SMOOTHMOUSE
#define ID_SMOOTHMOUSE 42
Definition at line 124 of file ui_controls2.c.
ID_SPEED
#define ID_SPEED 2
Definition at line 82 of file ui_controls2.c.
ID_STRAFE
#define ID_STRAFE 11
Definition at line 91 of file ui_controls2.c.
ID_TOGGLEMENU
#define ID_TOGGLEMENU 34
Definition at line 114 of file ui_controls2.c.
ID_USEITEM
#define ID_USEITEM 1
Definition at line 81 of file ui_controls2.c.
ID_WEAPNEXT
#define ID_WEAPNEXT 28
Definition at line 108 of file ui_controls2.c.
ID_WEAPON1
#define ID_WEAPON1 17
Definition at line 97 of file ui_controls2.c.
ID_WEAPON2
#define ID_WEAPON2 18
Definition at line 98 of file ui_controls2.c.
ID_WEAPON3
#define ID_WEAPON3 19
Definition at line 99 of file ui_controls2.c.
ID_WEAPON4
#define ID_WEAPON4 20
Definition at line 100 of file ui_controls2.c.
ID_WEAPON5
#define ID_WEAPON5 21
Definition at line 101 of file ui_controls2.c.
ID_WEAPON6
#define ID_WEAPON6 22
Definition at line 102 of file ui_controls2.c.
ID_WEAPON7
#define ID_WEAPON7 23
Definition at line 103 of file ui_controls2.c.
ID_WEAPON8
#define ID_WEAPON8 24
Definition at line 104 of file ui_controls2.c.
ID_WEAPON9
#define ID_WEAPON9 25
Definition at line 105 of file ui_controls2.c.
ID_WEAPONS
#define ID_WEAPONS 102
Definition at line 72 of file ui_controls2.c.
ID_WEAPPREV
#define ID_WEAPPREV 27
Definition at line 107 of file ui_controls2.c.
ID_ZOOMVIEW
#define ID_ZOOMVIEW 16
Definition at line 96 of file ui_controls2.c.
SAVE_CANCEL
#define SAVE_CANCEL 3
Definition at line 61 of file ui_controls2.c.
SAVE_NO
#define SAVE_NO 2
Definition at line 60 of file ui_controls2.c.
SAVE_NOOP
#define SAVE_NOOP 0
Definition at line 58 of file ui_controls2.c.
SAVE_YES
#define SAVE_YES 1
Definition at line 59 of file ui_controls2.c.
Function Documentation
Controls_ActionEvent()
static void Controls_ActionEvent (void * ptr, int event) static
Definition at line 1137 of file ui_controls2.c.
 {
     if (event == QM_LOSTFOCUS)
     {
         Controls_UpdateModel( ANIM_IDLE );
     }
     else if (event == QM_GOTFOCUS)
     {
         Controls_UpdateModel( g_bindings[((menucommon_s*)ptr)->id].anim );
     }
     else if ((event == QM_ACTIVATED) && !s_controls.waitingforkey)
     {
         s_controls.waitingforkey = 1;
         Controls_Update();
     }
 }
Referenced by Controls_MenuInit().
Controls_Cache()
void Controls_Cache (void)
Definition at line 1659 of file ui_controls2.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
Referenced by Controls_MenuInit(), and UI_Cache_f().
Controls_DrawKeyBinding()
static void Controls_DrawKeyBinding (void * self) static
Definition at line 652 of file ui_controls2.c.
 {
     menuaction_s*   a;
     int             x;
     int             y;
     int             b1;
     int             b2;
     qboolean        c;
     char            name[32];
     char            name2[32];
     a = (menuaction_s*) self;
     x = a->generic.x;
     y = a->generic.y;
     c = (Menu_ItemAtCursor( a->generic.parent ) == a);
     b1 = g_bindings[a->generic.id].bind1;
     if (b1 == -1)
         strcpy(name,"???");
     else
     {
         trap_Key_KeynumToStringBuf( b1, name, 32 );
         Q_strupr(name);
         b2 = g_bindings[a->generic.id].bind2;
         if (b2 != -1)
         {
             trap_Key_KeynumToStringBuf( b2, name2, 32 );
             Q_strupr(name2);
             strcat( name, " or " );
             strcat( name, name2 );
         }
     }
     if (c)
     {
         UI_FillRect( a->generic.left, a->generic.top, a->generic.right-a->generic.left+1, a->generic.bottom-a->generic.top+1, listbar_color );
         UI_DrawString( x - SMALLCHAR_WIDTH, y, g_bindings[a->generic.id].label, UI_RIGHT|UI_SMALLFONT, text_color_highlight );
         UI_DrawString( x + SMALLCHAR_WIDTH, y, name, UI_LEFT|UI_SMALLFONT|UI_PULSE, text_color_highlight );
         if (s_controls.waitingforkey)
         {
             UI_DrawChar( x, y, '=', UI_CENTER|UI_BLINK|UI_SMALLFONT, text_color_highlight);
             UI_DrawString(SCREEN_WIDTH * 0.50, SCREEN_HEIGHT * 0.80, "Waiting for new key ... ESCAPE to cancel", UI_SMALLFONT|UI_CENTER|UI_PULSE, colorWhite );
         }
         else
         {
             UI_DrawChar( x, y, 13, UI_CENTER|UI_BLINK|UI_SMALLFONT, text_color_highlight);
             UI_DrawString(SCREEN_WIDTH * 0.50, SCREEN_HEIGHT * 0.78, "Press ENTER or CLICK to change", UI_SMALLFONT|UI_CENTER, colorWhite );
             UI_DrawString(SCREEN_WIDTH * 0.50, SCREEN_HEIGHT * 0.82, "Press BACKSPACE to clear", UI_SMALLFONT|UI_CENTER, colorWhite );
         }
     }
     else
     {
         if (a->generic.flags & QMF_GRAYED)
         {
             UI_DrawString( x - SMALLCHAR_WIDTH, y, g_bindings[a->generic.id].label, UI_RIGHT|UI_SMALLFONT, text_color_disabled );
             UI_DrawString( x + SMALLCHAR_WIDTH, y, name, UI_LEFT|UI_SMALLFONT, text_color_disabled );
         }
         else
         {
             UI_DrawString( x - SMALLCHAR_WIDTH, y, g_bindings[a->generic.id].label, UI_RIGHT|UI_SMALLFONT, controls_binding_color );
             UI_DrawString( x + SMALLCHAR_WIDTH, y, name, UI_LEFT|UI_SMALLFONT, controls_binding_color );
         }
     }
 }
Referenced by Controls_MenuInit().
Controls_DrawPlayer()
static void Controls_DrawPlayer (void * self) static
Definition at line 739 of file ui_controls2.c.
{
     menubitmap_s    *b;
     char            buf[MAX_QPATH];
     trap_Cvar_VariableStringBuffer( "model", buf, sizeof( buf ) );
     if ( strcmp( buf, s_controls.playerModel ) != 0 ) {
         UI_PlayerInfo_SetModel( &s_controls.playerinfo, buf );
         strcpy( s_controls.playerModel, buf );
         Controls_UpdateModel( ANIM_IDLE );
     }
     b = (menubitmap_s*) self;
     UI_DrawPlayer( b->generic.x, b->generic.y, b->width, b->height, &s_controls.playerinfo, uis.realtime/2 );
 }
Referenced by Controls_MenuInit().
Controls_GetConfig()
static void Controls_GetConfig (void) static
Definition at line 789 of file ui_controls2.c.
 {
     int     i;
     int     twokeys[2];
     bind_t* bindptr;
     // put the bindings into a local store
     bindptr = g_bindings;
     // iterate each command, get its numeric binding
     for (i=0; ;i++,bindptr++)
     {
         if (!bindptr->label)
             break;
         Controls_GetKeyAssignment(bindptr->command, twokeys);
         bindptr->bind1 = twokeys[0];
         bindptr->bind2 = twokeys[1];
     }
     s_controls.invertmouse.curvalue  = Controls_GetCvarValue( "m_pitch" ) < 0;
     s_controls.smoothmouse.curvalue  = UI_ClampCvar( 0, 1, Controls_GetCvarValue( "m_filter" ) );
     s_controls.alwaysrun.curvalue    = UI_ClampCvar( 0, 1, Controls_GetCvarValue( "cl_run" ) );
     s_controls.autoswitch.curvalue   = UI_ClampCvar( 0, 1, Controls_GetCvarValue( "cg_autoswitch" ) );
     s_controls.sensitivity.curvalue  = UI_ClampCvar( 2, 30, Controls_GetCvarValue( "sensitivity" ) );
     s_controls.joyenable.curvalue    = UI_ClampCvar( 0, 1, Controls_GetCvarValue( "in_joystick" ) );
     s_controls.joythreshold.curvalue = UI_ClampCvar( 0.05f, 0.75f, Controls_GetCvarValue( "joy_threshold" ) );
     s_controls.freelook.curvalue     = UI_ClampCvar( 0, 1, Controls_GetCvarValue( "cl_freelook" ) );
 }
Referenced by Controls_MenuInit(), and UI_RunMenuScript().
Controls_GetCvarDefault()
static float Controls_GetCvarDefault (char * name) static
Definition at line 383 of file ui_controls2.c.
 {
     configcvar_t*   cvarptr;
     int             i;
     cvarptr = g_configcvars;
     for (i=0; ;i++,cvarptr++)
     {
         if (!cvarptr->name)
             return (0);
         if (!strcmp(cvarptr->name,name))
             break;
     }
     return (cvarptr->defaultvalue);
 }
Referenced by Controls_SetDefaults().
Controls_GetCvarValue()
static float Controls_GetCvarValue (char * name) static
Definition at line 406 of file ui_controls2.c.
 {
     configcvar_t*   cvarptr;
     int             i;
     cvarptr = g_configcvars;
     for (i=0; ;i++,cvarptr++)
     {
         if (!cvarptr->name)
             return (0);
         if (!strcmp(cvarptr->name,name))
             break;
     }
     return (cvarptr->value);
 }
Referenced by Controls_GetConfig().
Controls_GetKeyAssignment()
static void Controls_GetKeyAssignment (char * command, int * twokeys) static
Definition at line 760 of file ui_controls2.c.
 {
     int     count;
     int     j;
     char    b[256];
     twokeys[0] = twokeys[1] = -1;
     count = 0;
     for ( j = 0; j < 256; j++ )
     {
         trap_Key_GetBindingBuf( j, b, 256 );
         if ( *b == 0 ) {
             continue;
         }
         if ( !Q_stricmp( b, command ) ) {
             twokeys[count] = j;
             count++;
             if (count == 2)
                 break;
         }
     }
 }
Referenced by Controls_GetConfig().
Controls_InitCvars()
static void Controls_InitCvars (void) static
Definition at line 355 of file ui_controls2.c.
 {
     int             i;
     configcvar_t*   cvarptr;
     cvarptr = g_configcvars;
     for (i=0; ;i++,cvarptr++)
     {
         if (!cvarptr->name)
             break;
         // get current value
         cvarptr->value = trap_Cvar_VariableValue( cvarptr->name );
         // get default value
         trap_Cvar_Reset( cvarptr->name );
         cvarptr->defaultvalue = trap_Cvar_VariableValue( cvarptr->name );
         // restore current value
         trap_Cvar_SetValue( cvarptr->name, cvarptr->value );
     }
 }
Referenced by Controls_MenuInit().
Controls_InitModel()
static void Controls_InitModel (void) static
Definition at line 1159 of file ui_controls2.c.
 {
     memset( &s_controls.playerinfo, 0, sizeof(playerInfo_t) );
     UI_PlayerInfo_SetModel( &s_controls.playerinfo, UI_Cvar_VariableString( "model" ) );
     Controls_UpdateModel( ANIM_IDLE );
 }
Referenced by Controls_MenuInit().
Controls_InitWeapons()
static void Controls_InitWeapons (void) static
Definition at line 1173 of file ui_controls2.c.
{
     gitem_t *   item;
     for ( item = bg_itemlist + 1 ; item->classname ; item++ ) {
         if ( item->giType != IT_WEAPON ) {
             continue;
         }
         trap_R_RegisterModel( item->world_model[0] );
     }
 }
Referenced by Controls_MenuInit().
Controls_MenuEvent()
static void Controls_MenuEvent (void * ptr, int event) static
Definition at line 1049 of file ui_controls2.c.
 {
     switch (((menucommon_s*)ptr)->id)
     {
         case ID_MOVEMENT:
             if (event == QM_ACTIVATED)
             {
                 s_controls.section = C_MOVEMENT;
                 Controls_Update();
             }
             break;
         case ID_LOOKING:
             if (event == QM_ACTIVATED)
             {
                 s_controls.section = C_LOOKING;
                 Controls_Update();
             }
             break;
         case ID_WEAPONS:
             if (event == QM_ACTIVATED)
             {
                 s_controls.section = C_WEAPONS;
                 Controls_Update();
             }
             break;
         case ID_MISC:
             if (event == QM_ACTIVATED)
             {
                 s_controls.section = C_MISC;
                 Controls_Update();
             }
             break;
         case ID_DEFAULTS:
             if (event == QM_ACTIVATED)
             {
                 UI_ConfirmMenu( "SET TO DEFAULTS?", Controls_ResetDefaults_Draw, Controls_ResetDefaults_Action );
             }
             break;
         case ID_BACK:
             if (event == QM_ACTIVATED)
             {
                 if (s_controls.changesmade)
                     Controls_SetConfig();
                 UI_PopMenu();
             }
             break;
         case ID_SAVEANDEXIT:
             if (event == QM_ACTIVATED)
             {
                 Controls_SetConfig();
                 UI_PopMenu();
             }
             break;
         case ID_EXIT:
             if (event == QM_ACTIVATED)
             {
                 UI_PopMenu();
             }
             break;
         case ID_FREELOOK:
         case ID_MOUSESPEED:
         case ID_INVERTMOUSE:
         case ID_SMOOTHMOUSE:
         case ID_ALWAYSRUN:
         case ID_AUTOSWITCH:
         case ID_JOYENABLE:
         case ID_JOYTHRESHOLD:
             if (event == QM_ACTIVATED)
             {
                 s_controls.changesmade = qtrue;
             }
             break;
     }
 }
Referenced by Controls_MenuInit().
Controls_MenuInit()
static void Controls_MenuInit (void) static
Definition at line 1189 of file ui_controls2.c.
 {
     static char playername[32];
     // zero set all our globals
     memset( &s_controls, 0 ,sizeof(controls_t) );
     Controls_Cache();
     s_controls.menu.key        = Controls_MenuKey;
     s_controls.menu.wrapAround = qtrue;
     s_controls.menu.fullscreen = qtrue;
     s_controls.banner.generic.type  = MTYPE_BTEXT;
     s_controls.banner.generic.flags = QMF_CENTER_JUSTIFY;
     s_controls.banner.generic.x     = 320;
     s_controls.banner.generic.y     = 16;
     s_controls.banner.string        = "CONTROLS";
     s_controls.banner.color         = color_white;
     s_controls.banner.style         = UI_CENTER;
     s_controls.framel.generic.type  = MTYPE_BITMAP;
     s_controls.framel.generic.name  = ART_FRAMEL;
     s_controls.framel.generic.flags = QMF_LEFT_JUSTIFY|QMF_INACTIVE;
     s_controls.framel.generic.x     = 0;
     s_controls.framel.generic.y     = 78;
     s_controls.framel.width         = 256;
     s_controls.framel.height        = 329;
     s_controls.framer.generic.type  = MTYPE_BITMAP;
     s_controls.framer.generic.name  = ART_FRAMER;
     s_controls.framer.generic.flags = QMF_LEFT_JUSTIFY|QMF_INACTIVE;
     s_controls.framer.generic.x     = 376;
     s_controls.framer.generic.y     = 76;
     s_controls.framer.width         = 256;
     s_controls.framer.height        = 334;
     s_controls.looking.generic.type     = MTYPE_PTEXT;
     s_controls.looking.generic.flags    = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_controls.looking.generic.id       = ID_LOOKING;
     s_controls.looking.generic.callback = Controls_MenuEvent;
     s_controls.looking.generic.x        = 152;
     s_controls.looking.generic.y        = 240 - 2 * PROP_HEIGHT;
     s_controls.looking.string           = "LOOK";
     s_controls.looking.style            = UI_RIGHT;
     s_controls.looking.color            = color_red;
     s_controls.movement.generic.type     = MTYPE_PTEXT;
     s_controls.movement.generic.flags    = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_controls.movement.generic.id       = ID_MOVEMENT;
     s_controls.movement.generic.callback = Controls_MenuEvent;
     s_controls.movement.generic.x        = 152;
     s_controls.movement.generic.y        = 240 - PROP_HEIGHT;
     s_controls.movement.string          = "MOVE";
     s_controls.movement.style           = UI_RIGHT;
     s_controls.movement.color           = color_red;
     s_controls.weapons.generic.type     = MTYPE_PTEXT;
     s_controls.weapons.generic.flags    = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_controls.weapons.generic.id       = ID_WEAPONS;
     s_controls.weapons.generic.callback = Controls_MenuEvent;
     s_controls.weapons.generic.x        = 152;
     s_controls.weapons.generic.y        = 240;
     s_controls.weapons.string           = "SHOOT";
     s_controls.weapons.style            = UI_RIGHT;
     s_controls.weapons.color            = color_red;
     s_controls.misc.generic.type     = MTYPE_PTEXT;
     s_controls.misc.generic.flags    = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_controls.misc.generic.id       = ID_MISC;
     s_controls.misc.generic.callback = Controls_MenuEvent;
     s_controls.misc.generic.x        = 152;
     s_controls.misc.generic.y        = 240 + PROP_HEIGHT;
     s_controls.misc.string          = "MISC";
     s_controls.misc.style           = UI_RIGHT;
     s_controls.misc.color           = color_red;
     s_controls.back.generic.type     = MTYPE_BITMAP;
     s_controls.back.generic.name     = ART_BACK0;
     s_controls.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_controls.back.generic.x        = 0;
     s_controls.back.generic.y        = 480-64;
     s_controls.back.generic.id       = ID_BACK;
     s_controls.back.generic.callback = Controls_MenuEvent;
     s_controls.back.width            = 128;
     s_controls.back.height           = 64;
     s_controls.back.focuspic         = ART_BACK1;
     s_controls.player.generic.type      = MTYPE_BITMAP;
     s_controls.player.generic.flags     = QMF_INACTIVE;
     s_controls.player.generic.ownerdraw = Controls_DrawPlayer;
     s_controls.player.generic.x         = 400;
     s_controls.player.generic.y         = -40;
     s_controls.player.width             = 32*10;
     s_controls.player.height            = 56*10;
     s_controls.walkforward.generic.type      = MTYPE_ACTION;
     s_controls.walkforward.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.walkforward.generic.callback  = Controls_ActionEvent;
     s_controls.walkforward.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.walkforward.generic.id        = ID_FORWARD;
     s_controls.backpedal.generic.type      = MTYPE_ACTION;
     s_controls.backpedal.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.backpedal.generic.callback  = Controls_ActionEvent;
     s_controls.backpedal.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.backpedal.generic.id        = ID_BACKPEDAL;
     s_controls.stepleft.generic.type      = MTYPE_ACTION;
     s_controls.stepleft.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.stepleft.generic.callback  = Controls_ActionEvent;
     s_controls.stepleft.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.stepleft.generic.id        = ID_MOVELEFT;
     s_controls.stepright.generic.type      = MTYPE_ACTION;
     s_controls.stepright.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.stepright.generic.callback  = Controls_ActionEvent;
     s_controls.stepright.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.stepright.generic.id        = ID_MOVERIGHT;
     s_controls.moveup.generic.type      = MTYPE_ACTION;
     s_controls.moveup.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.moveup.generic.callback  = Controls_ActionEvent;
     s_controls.moveup.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.moveup.generic.id        = ID_MOVEUP;
     s_controls.movedown.generic.type      = MTYPE_ACTION;
     s_controls.movedown.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.movedown.generic.callback  = Controls_ActionEvent;
     s_controls.movedown.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.movedown.generic.id        = ID_MOVEDOWN;
     s_controls.turnleft.generic.type      = MTYPE_ACTION;
     s_controls.turnleft.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.turnleft.generic.callback  = Controls_ActionEvent;
     s_controls.turnleft.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.turnleft.generic.id        = ID_LEFT;
     s_controls.turnright.generic.type      = MTYPE_ACTION;
     s_controls.turnright.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.turnright.generic.callback  = Controls_ActionEvent;
     s_controls.turnright.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.turnright.generic.id        = ID_RIGHT;
     s_controls.sidestep.generic.type      = MTYPE_ACTION;
     s_controls.sidestep.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.sidestep.generic.callback  = Controls_ActionEvent;
     s_controls.sidestep.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.sidestep.generic.id        = ID_STRAFE;
     s_controls.run.generic.type      = MTYPE_ACTION;
     s_controls.run.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.run.generic.callback  = Controls_ActionEvent;
     s_controls.run.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.run.generic.id        = ID_SPEED;
     s_controls.chainsaw.generic.type      = MTYPE_ACTION;
     s_controls.chainsaw.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.chainsaw.generic.callback  = Controls_ActionEvent;
     s_controls.chainsaw.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.chainsaw.generic.id        = ID_WEAPON1;
     s_controls.machinegun.generic.type      = MTYPE_ACTION;
     s_controls.machinegun.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.machinegun.generic.callback  = Controls_ActionEvent;
     s_controls.machinegun.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.machinegun.generic.id        = ID_WEAPON2;
     s_controls.shotgun.generic.type      = MTYPE_ACTION;
     s_controls.shotgun.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.shotgun.generic.callback  = Controls_ActionEvent;
     s_controls.shotgun.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.shotgun.generic.id        = ID_WEAPON3;
     s_controls.grenadelauncher.generic.type      = MTYPE_ACTION;
     s_controls.grenadelauncher.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.grenadelauncher.generic.callback  = Controls_ActionEvent;
     s_controls.grenadelauncher.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.grenadelauncher.generic.id        = ID_WEAPON4;
     s_controls.rocketlauncher.generic.type      = MTYPE_ACTION;
     s_controls.rocketlauncher.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.rocketlauncher.generic.callback  = Controls_ActionEvent;
     s_controls.rocketlauncher.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.rocketlauncher.generic.id        = ID_WEAPON5;
     s_controls.lightning.generic.type      = MTYPE_ACTION;
     s_controls.lightning.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.lightning.generic.callback  = Controls_ActionEvent;
     s_controls.lightning.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.lightning.generic.id        = ID_WEAPON6;
     s_controls.railgun.generic.type      = MTYPE_ACTION;
     s_controls.railgun.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.railgun.generic.callback  = Controls_ActionEvent;
     s_controls.railgun.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.railgun.generic.id        = ID_WEAPON7;
     s_controls.plasma.generic.type      = MTYPE_ACTION;
     s_controls.plasma.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.plasma.generic.callback  = Controls_ActionEvent;
     s_controls.plasma.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.plasma.generic.id        = ID_WEAPON8;
     s_controls.bfg.generic.type      = MTYPE_ACTION;
     s_controls.bfg.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.bfg.generic.callback  = Controls_ActionEvent;
     s_controls.bfg.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.bfg.generic.id        = ID_WEAPON9;
     s_controls.attack.generic.type      = MTYPE_ACTION;
     s_controls.attack.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.attack.generic.callback  = Controls_ActionEvent;
     s_controls.attack.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.attack.generic.id        = ID_ATTACK;
     s_controls.prevweapon.generic.type      = MTYPE_ACTION;
     s_controls.prevweapon.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.prevweapon.generic.callback  = Controls_ActionEvent;
     s_controls.prevweapon.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.prevweapon.generic.id        = ID_WEAPPREV;
     s_controls.nextweapon.generic.type      = MTYPE_ACTION;
     s_controls.nextweapon.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.nextweapon.generic.callback  = Controls_ActionEvent;
     s_controls.nextweapon.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.nextweapon.generic.id        = ID_WEAPNEXT;
     s_controls.lookup.generic.type      = MTYPE_ACTION;
     s_controls.lookup.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.lookup.generic.callback  = Controls_ActionEvent;
     s_controls.lookup.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.lookup.generic.id        = ID_LOOKUP;
     s_controls.lookdown.generic.type      = MTYPE_ACTION;
     s_controls.lookdown.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.lookdown.generic.callback  = Controls_ActionEvent;
     s_controls.lookdown.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.lookdown.generic.id        = ID_LOOKDOWN;
     s_controls.mouselook.generic.type      = MTYPE_ACTION;
     s_controls.mouselook.generic.flags     = QMF_LEFT_JUSTIFY|QMF_HIGHLIGHT_IF_FOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.mouselook.generic.callback  = Controls_ActionEvent;
     s_controls.mouselook.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.mouselook.generic.id        = ID_MOUSELOOK;
     s_controls.freelook.generic.type        = MTYPE_RADIOBUTTON;
     s_controls.freelook.generic.flags       = QMF_SMALLFONT;
     s_controls.freelook.generic.x           = SCREEN_WIDTH/2;
     s_controls.freelook.generic.name        = "free look";
     s_controls.freelook.generic.id          = ID_FREELOOK;
     s_controls.freelook.generic.callback    = Controls_MenuEvent;
     s_controls.freelook.generic.statusbar   = Controls_StatusBar;
     s_controls.centerview.generic.type      = MTYPE_ACTION;
     s_controls.centerview.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.centerview.generic.callback  = Controls_ActionEvent;
     s_controls.centerview.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.centerview.generic.id        = ID_CENTERVIEW;
     s_controls.zoomview.generic.type      = MTYPE_ACTION;
     s_controls.zoomview.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.zoomview.generic.callback  = Controls_ActionEvent;
     s_controls.zoomview.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.zoomview.generic.id        = ID_ZOOMVIEW;
     s_controls.useitem.generic.type      = MTYPE_ACTION;
     s_controls.useitem.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.useitem.generic.callback  = Controls_ActionEvent;
     s_controls.useitem.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.useitem.generic.id        = ID_USEITEM;
     s_controls.showscores.generic.type      = MTYPE_ACTION;
     s_controls.showscores.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.showscores.generic.callback  = Controls_ActionEvent;
     s_controls.showscores.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.showscores.generic.id        = ID_SHOWSCORES;
     s_controls.invertmouse.generic.type      = MTYPE_RADIOBUTTON;
     s_controls.invertmouse.generic.flags     = QMF_SMALLFONT;
     s_controls.invertmouse.generic.x         = SCREEN_WIDTH/2;
     s_controls.invertmouse.generic.name      = "invert mouse";
     s_controls.invertmouse.generic.id        = ID_INVERTMOUSE;
     s_controls.invertmouse.generic.callback  = Controls_MenuEvent;
     s_controls.invertmouse.generic.statusbar = Controls_StatusBar;
     s_controls.smoothmouse.generic.type      = MTYPE_RADIOBUTTON;
     s_controls.smoothmouse.generic.flags     = QMF_SMALLFONT;
     s_controls.smoothmouse.generic.x         = SCREEN_WIDTH/2;
     s_controls.smoothmouse.generic.name      = "smooth mouse";
     s_controls.smoothmouse.generic.id        = ID_SMOOTHMOUSE;
     s_controls.smoothmouse.generic.callback  = Controls_MenuEvent;
     s_controls.smoothmouse.generic.statusbar = Controls_StatusBar;
     s_controls.alwaysrun.generic.type      = MTYPE_RADIOBUTTON;
     s_controls.alwaysrun.generic.flags     = QMF_SMALLFONT;
     s_controls.alwaysrun.generic.x         = SCREEN_WIDTH/2;
     s_controls.alwaysrun.generic.name      = "always run";
     s_controls.alwaysrun.generic.id        = ID_ALWAYSRUN;
     s_controls.alwaysrun.generic.callback  = Controls_MenuEvent;
     s_controls.alwaysrun.generic.statusbar = Controls_StatusBar;
     s_controls.autoswitch.generic.type      = MTYPE_RADIOBUTTON;
     s_controls.autoswitch.generic.flags     = QMF_SMALLFONT;
     s_controls.autoswitch.generic.x         = SCREEN_WIDTH/2;
     s_controls.autoswitch.generic.name      = "autoswitch weapons";
     s_controls.autoswitch.generic.id        = ID_AUTOSWITCH;
     s_controls.autoswitch.generic.callback  = Controls_MenuEvent;
     s_controls.autoswitch.generic.statusbar = Controls_StatusBar;
     s_controls.sensitivity.generic.type      = MTYPE_SLIDER;
     s_controls.sensitivity.generic.x         = SCREEN_WIDTH/2;
     s_controls.sensitivity.generic.flags     = QMF_SMALLFONT;
     s_controls.sensitivity.generic.name      = "mouse speed";
     s_controls.sensitivity.generic.id        = ID_MOUSESPEED;
     s_controls.sensitivity.generic.callback  = Controls_MenuEvent;
     s_controls.sensitivity.minvalue          = 2;
     s_controls.sensitivity.maxvalue          = 30;
     s_controls.sensitivity.generic.statusbar = Controls_StatusBar;
     s_controls.gesture.generic.type      = MTYPE_ACTION;
     s_controls.gesture.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.gesture.generic.callback  = Controls_ActionEvent;
     s_controls.gesture.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.gesture.generic.id        = ID_GESTURE;
     s_controls.chat.generic.type      = MTYPE_ACTION;
     s_controls.chat.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.chat.generic.callback  = Controls_ActionEvent;
     s_controls.chat.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.chat.generic.id        = ID_CHAT;
     s_controls.chat2.generic.type      = MTYPE_ACTION;
     s_controls.chat2.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.chat2.generic.callback  = Controls_ActionEvent;
     s_controls.chat2.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.chat2.generic.id        = ID_CHAT2;
     s_controls.chat3.generic.type      = MTYPE_ACTION;
     s_controls.chat3.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.chat3.generic.callback  = Controls_ActionEvent;
     s_controls.chat3.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.chat3.generic.id        = ID_CHAT3;
     s_controls.chat4.generic.type      = MTYPE_ACTION;
     s_controls.chat4.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.chat4.generic.callback  = Controls_ActionEvent;
     s_controls.chat4.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.chat4.generic.id        = ID_CHAT4;
     s_controls.togglemenu.generic.type      = MTYPE_ACTION;
     s_controls.togglemenu.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_GRAYED|QMF_HIDDEN;
     s_controls.togglemenu.generic.callback  = Controls_ActionEvent;
     s_controls.togglemenu.generic.ownerdraw = Controls_DrawKeyBinding;
     s_controls.togglemenu.generic.id        = ID_TOGGLEMENU;
     s_controls.joyenable.generic.type      = MTYPE_RADIOBUTTON;
     s_controls.joyenable.generic.flags     = QMF_SMALLFONT;
     s_controls.joyenable.generic.x         = SCREEN_WIDTH/2;
     s_controls.joyenable.generic.name      = "joystick";
     s_controls.joyenable.generic.id        = ID_JOYENABLE;
     s_controls.joyenable.generic.callback  = Controls_MenuEvent;
     s_controls.joyenable.generic.statusbar = Controls_StatusBar;
     s_controls.joythreshold.generic.type      = MTYPE_SLIDER;
     s_controls.joythreshold.generic.x         = SCREEN_WIDTH/2;
     s_controls.joythreshold.generic.flags     = QMF_SMALLFONT;
     s_controls.joythreshold.generic.name      = "joystick threshold";
     s_controls.joythreshold.generic.id        = ID_JOYTHRESHOLD;
     s_controls.joythreshold.generic.callback  = Controls_MenuEvent;
     s_controls.joythreshold.minvalue          = 0.05f;
     s_controls.joythreshold.maxvalue          = 0.75f;
     s_controls.joythreshold.generic.statusbar = Controls_StatusBar;
     s_controls.name.generic.type    = MTYPE_PTEXT;
     s_controls.name.generic.flags   = QMF_CENTER_JUSTIFY|QMF_INACTIVE;
     s_controls.name.generic.x       = 320;
     s_controls.name.generic.y       = 440;
     s_controls.name.string          = playername;
     s_controls.name.style           = UI_CENTER;
     s_controls.name.color           = text_color_normal;
     Menu_AddItem( &s_controls.menu, &s_controls.banner );
     Menu_AddItem( &s_controls.menu, &s_controls.framel );
     Menu_AddItem( &s_controls.menu, &s_controls.framer );
     Menu_AddItem( &s_controls.menu, &s_controls.player );
     Menu_AddItem( &s_controls.menu, &s_controls.name );
     Menu_AddItem( &s_controls.menu, &s_controls.looking );
     Menu_AddItem( &s_controls.menu, &s_controls.movement );
     Menu_AddItem( &s_controls.menu, &s_controls.weapons );
     Menu_AddItem( &s_controls.menu, &s_controls.misc );
     Menu_AddItem( &s_controls.menu, &s_controls.sensitivity );
     Menu_AddItem( &s_controls.menu, &s_controls.smoothmouse );
     Menu_AddItem( &s_controls.menu, &s_controls.invertmouse );
     Menu_AddItem( &s_controls.menu, &s_controls.lookup );
     Menu_AddItem( &s_controls.menu, &s_controls.lookdown );
     Menu_AddItem( &s_controls.menu, &s_controls.mouselook );
     Menu_AddItem( &s_controls.menu, &s_controls.freelook );
     Menu_AddItem( &s_controls.menu, &s_controls.centerview );
     Menu_AddItem( &s_controls.menu, &s_controls.zoomview );
     Menu_AddItem( &s_controls.menu, &s_controls.joyenable );
     Menu_AddItem( &s_controls.menu, &s_controls.joythreshold );
     Menu_AddItem( &s_controls.menu, &s_controls.alwaysrun );
     Menu_AddItem( &s_controls.menu, &s_controls.run );
     Menu_AddItem( &s_controls.menu, &s_controls.walkforward );
     Menu_AddItem( &s_controls.menu, &s_controls.backpedal );
     Menu_AddItem( &s_controls.menu, &s_controls.stepleft );
     Menu_AddItem( &s_controls.menu, &s_controls.stepright );
     Menu_AddItem( &s_controls.menu, &s_controls.moveup );
     Menu_AddItem( &s_controls.menu, &s_controls.movedown );
     Menu_AddItem( &s_controls.menu, &s_controls.turnleft );
     Menu_AddItem( &s_controls.menu, &s_controls.turnright );
     Menu_AddItem( &s_controls.menu, &s_controls.sidestep );
     Menu_AddItem( &s_controls.menu, &s_controls.attack );
     Menu_AddItem( &s_controls.menu, &s_controls.nextweapon );
     Menu_AddItem( &s_controls.menu, &s_controls.prevweapon );
     Menu_AddItem( &s_controls.menu, &s_controls.autoswitch );
     Menu_AddItem( &s_controls.menu, &s_controls.chainsaw );
     Menu_AddItem( &s_controls.menu, &s_controls.machinegun );
     Menu_AddItem( &s_controls.menu, &s_controls.shotgun );
     Menu_AddItem( &s_controls.menu, &s_controls.grenadelauncher );
     Menu_AddItem( &s_controls.menu, &s_controls.rocketlauncher );
     Menu_AddItem( &s_controls.menu, &s_controls.lightning );
     Menu_AddItem( &s_controls.menu, &s_controls.railgun );
     Menu_AddItem( &s_controls.menu, &s_controls.plasma );
     Menu_AddItem( &s_controls.menu, &s_controls.bfg );
     Menu_AddItem( &s_controls.menu, &s_controls.showscores );
     Menu_AddItem( &s_controls.menu, &s_controls.useitem );
     Menu_AddItem( &s_controls.menu, &s_controls.gesture );
     Menu_AddItem( &s_controls.menu, &s_controls.chat );
     Menu_AddItem( &s_controls.menu, &s_controls.chat2 );
     Menu_AddItem( &s_controls.menu, &s_controls.chat3 );
     Menu_AddItem( &s_controls.menu, &s_controls.chat4 );
     Menu_AddItem( &s_controls.menu, &s_controls.togglemenu );
     Menu_AddItem( &s_controls.menu, &s_controls.back );
     trap_Cvar_VariableStringBuffer( "name", s_controls.name.string, 16 );
     Q_CleanStr( s_controls.name.string );
     // initialize the configurable cvars
     Controls_InitCvars();
     // initialize the current config
     Controls_GetConfig();
     // intialize the model
     Controls_InitModel();
     // intialize the weapons
     Controls_InitWeapons ();
     // initial default section
     s_controls.section = C_LOOKING;
     // update the ui
     Controls_Update();
 }
Referenced by UI_ControlsMenu().
Controls_MenuKey()
static sfxHandle_t Controls_MenuKey (int key) static
Definition at line 901 of file ui_controls2.c.
 {
     int         id;
     int         i;
     qboolean    found;
     bind_t*     bindptr;
     found = qfalse;
     if (!s_controls.waitingforkey)
     {
         switch (key)
         {
             case K_BACKSPACE:
             case K_DEL:
             case K_KP_DEL:
                 key = -1;
                 break;
             case K_MOUSE2:
             case K_ESCAPE:
                 if (s_controls.changesmade)
                     Controls_SetConfig();
                 goto ignorekey;
             default:
                 goto ignorekey;
         }
     }
     else
     {
         if (key & K_CHAR_FLAG)
             goto ignorekey;
         switch (key)
         {
             case K_ESCAPE:
                 s_controls.waitingforkey = qfalse;
                 Controls_Update();
                 return (menu_out_sound);
             case '`':
                 goto ignorekey;
         }
     }
     s_controls.changesmade = qtrue;
     if (key != -1)
     {
         // remove from any other bind
         bindptr = g_bindings;
         for (i=0; ;i++,bindptr++)
         {
             if (!bindptr->label)
                 break;
             if (bindptr->bind2 == key)
                 bindptr->bind2 = -1;
             if (bindptr->bind1 == key)
             {
                 bindptr->bind1 = bindptr->bind2;
                 bindptr->bind2 = -1;
             }
         }
     }
     // assign key to local store
     id      = ((menucommon_s*)(s_controls.menu.items[s_controls.menu.cursor]))->id;
     bindptr = g_bindings;
     for (i=0; ;i++,bindptr++)
     {
         if (!bindptr->label)
             break;
         if (bindptr->id == id)
         {
             found = qtrue;
             if (key == -1)
             {
                 if( bindptr->bind1 != -1 ) {
                     trap_Key_SetBinding( bindptr->bind1, "" );
                     bindptr->bind1 = -1;
                 }
                 if( bindptr->bind2 != -1 ) {
                     trap_Key_SetBinding( bindptr->bind2, "" );
                     bindptr->bind2 = -1;
                 }
             }
             else if (bindptr->bind1 == -1) {
                 bindptr->bind1 = key;
             }
             else if (bindptr->bind1 != key && bindptr->bind2 == -1) {
                 bindptr->bind2 = key;
             }
             else
             {
                 trap_Key_SetBinding( bindptr->bind1, "" );
                 trap_Key_SetBinding( bindptr->bind2, "" );
                 bindptr->bind1 = key;
                 bindptr->bind2 = -1;
             }
             break;
         }
     }
     s_controls.waitingforkey = qfalse;
     if (found)
     {
         Controls_Update();
         return (menu_out_sound);
     }
 ignorekey:
     return Menu_DefaultKey( &s_controls.menu, key );
 }
Referenced by Controls_MenuInit().
Controls_ResetDefaults_Action()
static void Controls_ResetDefaults_Action (qboolean result) static
Definition at line 1024 of file ui_controls2.c.
{
     if( !result ) {
         return;
     }
     s_controls.changesmade = qtrue;
     Controls_SetDefaults();
     Controls_Update();
 }
Referenced by Controls_MenuEvent().
Controls_ResetDefaults_Draw()
static void Controls_ResetDefaults_Draw (void) static
Definition at line 1039 of file ui_controls2.c.
{
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 0, "WARNING: This will reset all", UI_CENTER|UI_SMALLFONT, color_yellow );
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 1, "controls to their default values.", UI_CENTER|UI_SMALLFONT, color_yellow );
 }
Referenced by Controls_MenuEvent().
Controls_SetConfig()
static void Controls_SetConfig (void) static
Definition at line 825 of file ui_controls2.c.
 {
     int     i;
     bind_t* bindptr;
     // set the bindings from the local store
     bindptr = g_bindings;
     // iterate each command, get its numeric binding
     for (i=0; ;i++,bindptr++)
     {
         if (!bindptr->label)
             break;
         if (bindptr->bind1 != -1)
         {
             trap_Key_SetBinding( bindptr->bind1, bindptr->command );
             if (bindptr->bind2 != -1)
                 trap_Key_SetBinding( bindptr->bind2, bindptr->command );
         }
     }
     if ( s_controls.invertmouse.curvalue )
         trap_Cvar_SetValue( "m_pitch", -fabs( trap_Cvar_VariableValue( "m_pitch" ) ) );
     else
         trap_Cvar_SetValue( "m_pitch", fabs( trap_Cvar_VariableValue( "m_pitch" ) ) );
     trap_Cvar_SetValue( "m_filter", s_controls.smoothmouse.curvalue );
     trap_Cvar_SetValue( "cl_run", s_controls.alwaysrun.curvalue );
     trap_Cvar_SetValue( "cg_autoswitch", s_controls.autoswitch.curvalue );
     trap_Cvar_SetValue( "sensitivity", s_controls.sensitivity.curvalue );
     trap_Cvar_SetValue( "in_joystick", s_controls.joyenable.curvalue );
     trap_Cvar_SetValue( "joy_threshold", s_controls.joythreshold.curvalue );
     trap_Cvar_SetValue( "cl_freelook", s_controls.freelook.curvalue );
     trap_Cmd_ExecuteText( EXEC_APPEND, "in_restart\n" );
 }
Referenced by Controls_MenuEvent(), Controls_MenuKey(), and UI_RunMenuScript().
Controls_SetDefaults()
static void Controls_SetDefaults (void) static
Definition at line 868 of file ui_controls2.c.
 {
     int i;
     bind_t* bindptr;
     // set the bindings from the local store
     bindptr = g_bindings;
     // iterate each command, set its default binding
     for (i=0; ;i++,bindptr++)
     {
         if (!bindptr->label)
             break;
         bindptr->bind1 = bindptr->defaultbind1;
         bindptr->bind2 = bindptr->defaultbind2;
     }
     s_controls.invertmouse.curvalue  = Controls_GetCvarDefault( "m_pitch" ) < 0;
     s_controls.smoothmouse.curvalue  = Controls_GetCvarDefault( "m_filter" );
     s_controls.alwaysrun.curvalue    = Controls_GetCvarDefault( "cl_run" );
     s_controls.autoswitch.curvalue   = Controls_GetCvarDefault( "cg_autoswitch" );
     s_controls.sensitivity.curvalue  = Controls_GetCvarDefault( "sensitivity" );
     s_controls.joyenable.curvalue    = Controls_GetCvarDefault( "in_joystick" );
     s_controls.joythreshold.curvalue = Controls_GetCvarDefault( "joy_threshold" );
     s_controls.freelook.curvalue     = Controls_GetCvarDefault( "cl_freelook" );
 }
Referenced by Controls_ResetDefaults_Action(), and UI_RunMenuScript().
Controls_StatusBar()
static void Controls_StatusBar (void * self) static
Definition at line 728 of file ui_controls2.c.
 {
     UI_DrawString(SCREEN_WIDTH * 0.50, SCREEN_HEIGHT * 0.80, "Use Arrow Keys or CLICK to change", UI_SMALLFONT|UI_CENTER, colorWhite );
 }
Referenced by Controls_MenuInit().
Controls_Update()
static void Controls_Update (void) static
Definition at line 558 of file ui_controls2.c.
{
     int     i;
     int     j;
     int     y;
     menucommon_s    **controls;
     menucommon_s    *control;
     // disable all controls in all groups
     for( i = 0; i < C_MAX; i++ ) {
         controls = g_controls[i];
         for( j = 0;  (control = controls[j]) ; j++ ) {
             control->flags |= (QMF_HIDDEN|QMF_INACTIVE);
         }
     }
     controls = g_controls[s_controls.section];
     // enable controls in active group (and count number of items for vertical centering)
     for( j = 0;  (control = controls[j]) ; j++ ) {
         control->flags &= ~(QMF_GRAYED|QMF_HIDDEN|QMF_INACTIVE);
     }
     // position controls
     y = ( SCREEN_HEIGHT - j * SMALLCHAR_HEIGHT ) / 2;
     for( j = 0; (control = controls[j]) ; j++, y += SMALLCHAR_HEIGHT ) {
         control->x      = 320;
         control->y      = y;
         control->left   = 320 - 19*SMALLCHAR_WIDTH;
         control->right  = 320 + 21*SMALLCHAR_WIDTH;
         control->top    = y;
         control->bottom = y + SMALLCHAR_HEIGHT;
     }
     if( s_controls.waitingforkey ) {
         // disable everybody
         for( i = 0; i < s_controls.menu.nitems; i++ ) {
             ((menucommon_s*)(s_controls.menu.items[i]))->flags |= QMF_GRAYED;
         }
         // enable action item
         ((menucommon_s*)(s_controls.menu.items[s_controls.menu.cursor]))->flags &= ~QMF_GRAYED;
         // don't gray out player's name
         s_controls.name.generic.flags &= ~QMF_GRAYED;
         return;
     }
     // enable everybody
     for( i = 0; i < s_controls.menu.nitems; i++ ) {
         ((menucommon_s*)(s_controls.menu.items[i]))->flags &= ~QMF_GRAYED;
     }
     // makes sure flags are right on the group selection controls
     s_controls.looking.generic.flags  &= ~(QMF_GRAYED|QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
     s_controls.movement.generic.flags &= ~(QMF_GRAYED|QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
     s_controls.weapons.generic.flags  &= ~(QMF_GRAYED|QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
     s_controls.misc.generic.flags     &= ~(QMF_GRAYED|QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
     s_controls.looking.generic.flags  |= QMF_PULSEIFFOCUS;
     s_controls.movement.generic.flags |= QMF_PULSEIFFOCUS;
     s_controls.weapons.generic.flags  |= QMF_PULSEIFFOCUS;
     s_controls.misc.generic.flags     |= QMF_PULSEIFFOCUS;
     // set buttons
     switch( s_controls.section ) {
     case C_MOVEMENT:
         s_controls.movement.generic.flags &= ~QMF_PULSEIFFOCUS;
         s_controls.movement.generic.flags |= (QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
         break;
     case C_LOOKING:
         s_controls.looking.generic.flags &= ~QMF_PULSEIFFOCUS;
         s_controls.looking.generic.flags |= (QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
         break;
     case C_WEAPONS:
         s_controls.weapons.generic.flags &= ~QMF_PULSEIFFOCUS;
         s_controls.weapons.generic.flags |= (QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
         break;
     case C_MISC:
         s_controls.misc.generic.flags &= ~QMF_PULSEIFFOCUS;
         s_controls.misc.generic.flags |= (QMF_HIGHLIGHT|QMF_HIGHLIGHT_IF_FOCUS);
         break;
     }
 }
Referenced by Controls_ActionEvent(), Controls_MenuEvent(), Controls_MenuInit(), Controls_MenuKey(), and Controls_ResetDefaults_Action().
Controls_UpdateModel()
static void Controls_UpdateModel (int anim) static
Definition at line 430 of file ui_controls2.c.
{
     VectorClear( s_controls.playerViewangles );
     VectorClear( s_controls.playerMoveangles );
     s_controls.playerViewangles[YAW] = 180 - 30;
     s_controls.playerMoveangles[YAW] = s_controls.playerViewangles[YAW];
     s_controls.playerLegs            = LEGS_IDLE;
     s_controls.playerTorso           = TORSO_STAND;
     s_controls.playerWeapon          = WP_NUM_WEAPONS;
     s_controls.playerChat            = qfalse;
     switch( anim ) {
     case ANIM_RUN:
         s_controls.playerLegs = LEGS_RUN;
         break;
     case ANIM_WALK:
         s_controls.playerLegs = LEGS_WALK;
         break;
     case ANIM_BACK:
         s_controls.playerLegs = LEGS_BACK;
         break;
     case ANIM_JUMP:
         s_controls.playerLegs = LEGS_JUMP;
         break;
     case ANIM_CROUCH:
         s_controls.playerLegs = LEGS_IDLECR;
         break;
     case ANIM_TURNLEFT:
         s_controls.playerViewangles[YAW] += 90;
         break;
     case ANIM_TURNRIGHT:
         s_controls.playerViewangles[YAW] -= 90;
         break;
     case ANIM_STEPLEFT:
         s_controls.playerLegs = LEGS_WALK;
         s_controls.playerMoveangles[YAW] = s_controls.playerViewangles[YAW] + 90;
         break;
     case ANIM_STEPRIGHT:
         s_controls.playerLegs = LEGS_WALK;
         s_controls.playerMoveangles[YAW] = s_controls.playerViewangles[YAW] - 90;
         break;
     case ANIM_LOOKUP:
         s_controls.playerViewangles[PITCH] = -45;
         break;
     case ANIM_LOOKDOWN:
         s_controls.playerViewangles[PITCH] = 45;
         break;
     case ANIM_WEAPON1:
         s_controls.playerWeapon = WP_GAUNTLET;
         break;
     case ANIM_WEAPON2:
         s_controls.playerWeapon = WP_MACHINEGUN;
         break;
     case ANIM_WEAPON3:
         s_controls.playerWeapon = WP_SHOTGUN;
         break;
     case ANIM_WEAPON4:
         s_controls.playerWeapon = WP_GRENADE_LAUNCHER;
         break;
     case ANIM_WEAPON5:
         s_controls.playerWeapon = WP_ROCKET_LAUNCHER;
         break;
     case ANIM_WEAPON6:
         s_controls.playerWeapon = WP_LIGHTNING;
         break;
     case ANIM_WEAPON7:
         s_controls.playerWeapon = WP_RAILGUN;
         break;
     case ANIM_WEAPON8:
         s_controls.playerWeapon = WP_PLASMAGUN;
         break;
     case ANIM_WEAPON9:
         s_controls.playerWeapon = WP_BFG;
         break;
     case ANIM_WEAPON10:
         s_controls.playerWeapon = WP_GRAPPLING_HOOK;
         break;
     case ANIM_ATTACK:
         s_controls.playerTorso = TORSO_ATTACK;
         break;
     case ANIM_GESTURE:
         s_controls.playerTorso = TORSO_GESTURE;
         break;
     case ANIM_DIE:
         s_controls.playerLegs = BOTH_DEATH1;
         s_controls.playerTorso = BOTH_DEATH1;
         s_controls.playerWeapon = WP_NONE;
         break;
     case ANIM_CHAT:
         s_controls.playerChat = qtrue;
         break;
     default:
         break;
     }
     UI_PlayerInfo_SetInfo( &s_controls.playerinfo, s_controls.playerLegs, s_controls.playerTorso, s_controls.playerViewangles, s_controls.playerMoveangles, s_controls.playerWeapon, s_controls.playerChat );
 }
Referenced by Controls_ActionEvent(), Controls_DrawPlayer(), and Controls_InitModel().
UI_ControlsMenu()
void UI_ControlsMenu (void)
Definition at line 1672 of file ui_controls2.c.
{
     Controls_MenuInit();
     UI_PushMenu( &s_controls.menu );
 }
Referenced by UI_SetupMenu_Event().
Variable Documentation
controls_binding_color
vec4_t controls_binding_color = {1.00f, 0.43f, 0.00f, 1.00f} static
Definition at line 228 of file ui_controls2.c.
Referenced by Controls_DrawKeyBinding().
g_bindings
bind_t g_bindings[] static
Definition at line 230 of file ui_controls2.c.
Referenced by Controls_ActionEvent(), Controls_DrawKeyBinding(), Controls_GetConfig(), Controls_MenuKey(), Controls_SetConfig(), and Controls_SetDefaults().
g_configcvars
configcvar_t g_configcvars[] static
Initial value:
=
{
    {"cl_run",          0,                  0},
    {"m_pitch",         0,                  0},
    {"cg_autoswitch",   0,                  0},
    {"sensitivity",     0,                  0},
    {"in_joystick",     0,                  0},
    {"joy_threshold",   0,                  0},
    {"m_filter",        0,                  0},
    {"cl_freelook",     0,                  0},
    {NULL,              0,                  0}
}
Definition at line 270 of file ui_controls2.c.
Referenced by Controls_GetCvarDefault(), Controls_GetCvarValue(), and Controls_InitCvars().
g_controls
menucommon_s** g_controls[] static
Initial value:
= {
    g_movement_controls,
    g_looking_controls,
    g_weapons_controls,
    g_misc_controls,
}
Definition at line 343 of file ui_controls2.c.
Referenced by Controls_Update().
g_looking_controls
menucommon_s* g_looking_controls[] static
Initial value:
= {
    (menucommon_s *)&s_controls.sensitivity,
    (menucommon_s *)&s_controls.smoothmouse,
    (menucommon_s *)&s_controls.invertmouse,
    (menucommon_s *)&s_controls.lookup,
    (menucommon_s *)&s_controls.lookdown,
    (menucommon_s *)&s_controls.mouselook,
    (menucommon_s *)&s_controls.freelook,
    (menucommon_s *)&s_controls.centerview,
    (menucommon_s *)&s_controls.zoomview,
    (menucommon_s *)&s_controls.joyenable,
    (menucommon_s *)&s_controls.joythreshold,
    NULL,
}
Definition at line 316 of file ui_controls2.c.
g_misc_controls
menucommon_s* g_misc_controls[] static
Initial value:
= {
    (menucommon_s *)&s_controls.showscores,
    (menucommon_s *)&s_controls.useitem,
    (menucommon_s *)&s_controls.gesture,
    (menucommon_s *)&s_controls.chat,
    (menucommon_s *)&s_controls.chat2,
    (menucommon_s *)&s_controls.chat3,
    (menucommon_s *)&s_controls.chat4,
    (menucommon_s *)&s_controls.togglemenu,
    NULL,
}
Definition at line 331 of file ui_controls2.c.
g_movement_controls
menucommon_s* g_movement_controls[] static
Initial value:
=
{
    (menucommon_s *)&s_controls.alwaysrun,
    (menucommon_s *)&s_controls.run,
    (menucommon_s *)&s_controls.walkforward,
    (menucommon_s *)&s_controls.backpedal,
    (menucommon_s *)&s_controls.stepleft,
    (menucommon_s *)&s_controls.stepright,
    (menucommon_s *)&s_controls.moveup,
    (menucommon_s *)&s_controls.movedown,
    (menucommon_s *)&s_controls.turnleft,
    (menucommon_s *)&s_controls.turnright,
    (menucommon_s *)&s_controls.sidestep,
    NULL
}
Definition at line 283 of file ui_controls2.c.
g_weapons_controls
menucommon_s* g_weapons_controls[] static
Initial value:
= {
    (menucommon_s *)&s_controls.attack,
    (menucommon_s *)&s_controls.nextweapon,
    (menucommon_s *)&s_controls.prevweapon,
    (menucommon_s *)&s_controls.autoswitch,
    (menucommon_s *)&s_controls.chainsaw,
    (menucommon_s *)&s_controls.machinegun,
    (menucommon_s *)&s_controls.shotgun,
    (menucommon_s *)&s_controls.grenadelauncher,
    (menucommon_s *)&s_controls.rocketlauncher,
    (menucommon_s *)&s_controls.lightning,
    (menucommon_s *)&s_controls.railgun,
    (menucommon_s *)&s_controls.plasma,
    (menucommon_s *)&s_controls.bfg,
    NULL,
}
Definition at line 299 of file ui_controls2.c.
s_controls
controls_t s_controls static
Definition at line 226 of file ui_controls2.c.
Referenced by Controls_ActionEvent(), Controls_DrawKeyBinding(), Controls_DrawPlayer(), Controls_GetConfig(), Controls_InitModel(), Controls_MenuEvent(), Controls_MenuInit(), Controls_MenuKey(), Controls_ResetDefaults_Action(), Controls_SetConfig(), Controls_SetDefaults(), Controls_Update(), Controls_UpdateModel(), and UI_ControlsMenu().