ioquake3 doxygen: C:/entry/dev/ioq3/code/client/cl_keys.c File Reference
cl_keys.c File Reference
#include "client.h"
Classes
struct keyname_t
Macros
#define MAX_CONSOLE_SAVE_BUFFER 1024
#define CONSOLE_HISTORY_FILE "q3history"
Functions
void Field_VariableSizeDraw (field_t *edit, int x, int y, int width, int size, qboolean showCursor, qboolean noColorEscape)
void Field_Draw (field_t *edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
void Field_BigDraw (field_t *edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
void Field_Paste (field_t *edit)
void Field_KeyDownEvent (field_t *edit, int key)
void Field_CharEvent (field_t *edit, int ch)
void Console_Key (int key)
void Message_Key (int key)
qboolean Key_GetOverstrikeMode (void)
void Key_SetOverstrikeMode (qboolean state)
qboolean Key_IsDown (int keynum)
int Key_StringToKeynum (char *str)
char * Key_KeynumToString (int keynum)
void Key_SetBinding (int keynum, const char *binding)
char * Key_GetBinding (int keynum)
int Key_GetKey (const char *binding)
void Key_Unbind_f (void)
void Key_Unbindall_f (void)
void Key_Bind_f (void)
void Key_WriteBindings (fileHandle_t f)
void Key_Bindlist_f (void)
void Key_KeynameCompletion (void(*callback)(const char *s))
static void Key_CompleteUnbind (char *args, int argNum)
static void Key_CompleteBind (char *args, int argNum)
void CL_InitKeyCommands (void)
static qboolean CL_BindUICommand (const char *cmd)
void CL_ParseBinding (int key, qboolean down, unsigned time)
void CL_KeyDownEvent (int key, unsigned time)
void CL_KeyUpEvent (int key, unsigned time)
void CL_KeyEvent (int key, qboolean down, unsigned time)
void CL_CharEvent (int key)
void Key_ClearStates (void)
int Key_GetCatcher (void)
void Key_SetCatcher (int catcher)
void CL_LoadConsoleHistory (void)
void CL_SaveConsoleHistory (void)
Variables
field_t historyEditLines [COMMAND_HISTORY]
int nextHistoryLine
int historyLine
field_t g_consoleField
field_t chatField
qboolean chat_team
int chat_playerNum
qboolean key_overstrikeMode
int anykeydown
qkey_t keys [MAX_KEYS]
keyname_t keynames []
static int keyCatchers = 0
static char consoleSaveBuffer [MAX_CONSOLE_SAVE_BUFFER]
static int consoleSaveBufferSize = 0
Macro Definition Documentation
CONSOLE_HISTORY_FILE
#define CONSOLE_HISTORY_FILE "q3history"
Definition at line 1455 of file cl_keys.c.
MAX_CONSOLE_SAVE_BUFFER
#define MAX_CONSOLE_SAVE_BUFFER 1024
Definition at line 1454 of file cl_keys.c.
Function Documentation
CL_BindUICommand()
static qboolean CL_BindUICommand (const char * cmd) static
Definition at line 1158 of file cl_keys.c.
{
     if ( Key_GetCatcher( ) & KEYCATCH_CONSOLE )
         return qfalse;
     if ( !Q_stricmp( cmd, "toggleconsole" ) )
         return qtrue;
     if ( !Q_stricmp( cmd, "togglemenu" ) )
         return qtrue;
     return qfalse;
 }
Referenced by CL_ParseBinding().
CL_CharEvent()
void CL_CharEvent (int key)
Definition at line 1381 of file cl_keys.c.
{
     // delete is not a printable character and is
     // otherwise handled by Field_KeyDownEvent
     if ( key == 127 ) {
         return;
     }
     // distribute the key down event to the appropriate handler
     if ( Key_GetCatcher( ) & KEYCATCH_CONSOLE )
     {
         Field_CharEvent( &g_consoleField, key );
     }
     else if ( Key_GetCatcher( ) & KEYCATCH_UI )
     {
         VM_Call( uivm, UI_KEY_EVENT, key | K_CHAR_FLAG, qtrue );
     }
     else if ( Key_GetCatcher( ) & KEYCATCH_MESSAGE )
     {
         Field_CharEvent( &chatField, key );
     }
     else if ( clc.state == CA_DISCONNECTED )
     {
         Field_CharEvent( &g_consoleField, key );
     }
 }
Referenced by Com_EventLoop().
CL_InitKeyCommands()
void CL_InitKeyCommands (void)
Definition at line 1141 of file cl_keys.c.
{
     // register our functions
     Cmd_AddCommand ("bind",Key_Bind_f);
     Cmd_SetCommandCompletionFunc( "bind", Key_CompleteBind );
     Cmd_AddCommand ("unbind",Key_Unbind_f);
     Cmd_SetCommandCompletionFunc( "unbind", Key_CompleteUnbind );
     Cmd_AddCommand ("unbindall",Key_Unbindall_f);
     Cmd_AddCommand ("bindlist",Key_Bindlist_f);
 }
Referenced by Com_Init().
CL_KeyDownEvent()
void CL_KeyDownEvent (int key, unsigned time)
Definition at line 1234 of file cl_keys.c.
 {
     keys[key].down = qtrue;
     keys[key].repeats++;
     if( keys[key].repeats == 1 )
         anykeydown++;
     if( keys[K_ALT].down && key == K_ENTER )
     {
         // don't repeat fullscreen toggle when keys are held down
         if ( keys[K_ENTER].repeats > 1 ) {
             return;
         }
         Cvar_SetValue( "r_fullscreen",
             !Cvar_VariableIntegerValue( "r_fullscreen" ) );
         return;
     }
     // console key is hardcoded, so the user can never unbind it
     if( key == K_CONSOLE || ( keys[K_SHIFT].down && key == K_ESCAPE ) )
     {
         Con_ToggleConsole_f ();
         Key_ClearStates ();
         return;
     }
     // keys can still be used for bound actions
     if ( ( key < 128 || key == K_MOUSE1 ) &&
         ( clc.demoplaying || clc.state == CA_CINEMATIC ) && Key_GetCatcher( ) == 0 ) {
         if (Cvar_VariableValue ("com_cameraMode") == 0) {
             Cvar_Set ("nextdemo","");
             key = K_ESCAPE;
         }
     }
     // escape is always handled special
     if ( key == K_ESCAPE ) {
         if ( Key_GetCatcher( ) & KEYCATCH_MESSAGE ) {
             // clear message mode
             Message_Key( key );
             return;
         }
         // escape always gets out of CGAME stuff
         if (Key_GetCatcher( ) & KEYCATCH_CGAME) {
             Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_CGAME );
             VM_Call (cgvm, CG_EVENT_HANDLING, CGAME_EVENT_NONE);
             return;
         }
         if ( !( Key_GetCatcher( ) & KEYCATCH_UI ) ) {
             if ( clc.state == CA_ACTIVE && !clc.demoplaying ) {
                 VM_Call( uivm, UI_SET_ACTIVE_MENU, UIMENU_INGAME );
             }
             else if ( clc.state != CA_DISCONNECTED ) {
                 CL_Disconnect_f();
                 S_StopAllSounds();
                 VM_Call( uivm, UI_SET_ACTIVE_MENU, UIMENU_MAIN );
             }
             return;
         }
         VM_Call( uivm, UI_KEY_EVENT, key, qtrue );
         return;
     }
     // send the bound action
     CL_ParseBinding( key, qtrue, time );
     // distribute the key down event to the appropriate handler
     if ( Key_GetCatcher( ) & KEYCATCH_CONSOLE ) {
         Console_Key( key );
     } else if ( Key_GetCatcher( ) & KEYCATCH_UI ) {
         if ( uivm ) {
             VM_Call( uivm, UI_KEY_EVENT, key, qtrue );
         }
     } else if ( Key_GetCatcher( ) & KEYCATCH_CGAME ) {
         if ( cgvm ) {
             VM_Call( cgvm, CG_KEY_EVENT, key, qtrue );
         }
     } else if ( Key_GetCatcher( ) & KEYCATCH_MESSAGE ) {
         Message_Key( key );
     } else if ( clc.state == CA_DISCONNECTED ) {
         Console_Key( key );
     }
 }
Referenced by CL_KeyEvent().
CL_KeyEvent()
void CL_KeyEvent (int key, qboolean down, unsigned time)
Definition at line 1367 of file cl_keys.c.
{
     if( down )
         CL_KeyDownEvent( key, time );
     else
         CL_KeyUpEvent( key, time );
 }
Referenced by Com_EventLoop(), Con_ToggleMenu_f(), and Key_ClearStates().
CL_KeyUpEvent()
void CL_KeyUpEvent (int key, unsigned time)
Definition at line 1331 of file cl_keys.c.
 {
     keys[key].repeats = 0;
     keys[key].down = qfalse;
     anykeydown--;
     if (anykeydown < 0) {
         anykeydown = 0;
     }
     // don't process key-up events for the console key
     if ( key == K_CONSOLE || ( key == K_ESCAPE && keys[K_SHIFT].down ) )
         return;
     //
     // key up events only perform actions if the game key binding is
     // a button command (leading + sign).  These will be processed even in
     // console mode and menu mode, to keep the character from continuing
     // an action started before a mode switch.
     //
     CL_ParseBinding( key, qfalse, time );
     if ( Key_GetCatcher( ) & KEYCATCH_UI && uivm ) {
         VM_Call( uivm, UI_KEY_EVENT, key, qfalse );
     } else if ( Key_GetCatcher( ) & KEYCATCH_CGAME && cgvm ) {
         VM_Call( cgvm, CG_KEY_EVENT, key, qfalse );
     }
 }
Referenced by CL_KeyEvent().
CL_LoadConsoleHistory()
void CL_LoadConsoleHistory (void)
Definition at line 1466 of file cl_keys.c.
 {
     char                    *token, *text_p;
     int                     i, numChars, numLines = 0;
     fileHandle_t    f;
     consoleSaveBufferSize = FS_FOpenFileRead( CONSOLE_HISTORY_FILE, &f, qfalse );
     if( !f )
     {
         Com_Printf( "Couldn't read %s.\n", CONSOLE_HISTORY_FILE );
         return;
     }
     if( consoleSaveBufferSize < MAX_CONSOLE_SAVE_BUFFER &&
             FS_Read( consoleSaveBuffer, consoleSaveBufferSize, f ) == consoleSaveBufferSize )
     {
         consoleSaveBuffer[consoleSaveBufferSize] = '\0';
         text_p = consoleSaveBuffer;
         for( i = COMMAND_HISTORY - 1; i >= 0; i-- )
         {
             if( !*( token = COM_Parse( &text_p ) ) )
                 break;
             historyEditLines[ i ].cursor = atoi( token );
             if( !*( token = COM_Parse( &text_p ) ) )
                 break;
             historyEditLines[ i ].scroll = atoi( token );
             if( !*( token = COM_Parse( &text_p ) ) )
                 break;
             numChars = atoi( token );
             text_p++;
             if( numChars > ( strlen( consoleSaveBuffer ) -  ( text_p - consoleSaveBuffer ) ) )
             {
                 Com_DPrintf( S_COLOR_YELLOW "WARNING: probable corrupt history\n" );
                 break;
             }
             Com_Memcpy( historyEditLines[ i ].buffer,
                     text_p, numChars );
             historyEditLines[ i ].buffer[ numChars ] = '\0';
             text_p += numChars;
             numLines++;
         }
         memmove( &historyEditLines[ 0 ], &historyEditLines[ i + 1 ],
                 numLines * sizeof( field_t ) );
         for( i = numLines; i < COMMAND_HISTORY; i++ )
             Field_Clear( &historyEditLines[ i ] );
         historyLine = nextHistoryLine = numLines;
     }
     else
         Com_Printf( "Couldn't read %s.\n", CONSOLE_HISTORY_FILE );
     FS_FCloseFile( f );
 }
Referenced by Con_Init().
CL_ParseBinding()
void CL_ParseBinding (int key, qboolean down, unsigned time)
Definition at line 1177 of file cl_keys.c.
 {
     char buf[ MAX_STRING_CHARS ], *p = buf, *end;
     qboolean allCommands, allowUpCmds;
     if( clc.state == CA_DISCONNECTED && Key_GetCatcher( ) == 0 )
         return;
     if( !keys[key].binding || !keys[key].binding[0] )
         return;
     Q_strncpyz( buf, keys[key].binding, sizeof( buf ) );
     // run all bind commands if console, ui, etc aren't reading keys
     allCommands = ( Key_GetCatcher( ) == 0 );
     // allow button up commands if in game even if key catcher is set
     allowUpCmds = ( clc.state != CA_DISCONNECTED );
     while( 1 )
     {
         while( isspace( *p ) )
             p++;
         end = strchr( p, ';' );
         if( end )
             *end = '\0';
         if( *p == '+' )
         {
             // button commands add keynum and time as parameters
             // so that multiple sources can be discriminated and
             // subframe corrected
             if ( allCommands || ( allowUpCmds && !down ) ) {
                 char cmd[1024];
                 Com_sprintf( cmd, sizeof( cmd ), "%c%s %d %d\n",
                     ( down ) ? '+' : '-', p + 1, key, time );
                 Cbuf_AddText( cmd );
             }
         }
         else if( down )
         {
             // normal commands only execute on key press
             if ( allCommands || CL_BindUICommand( p ) ) {
                 Cbuf_AddText( p );
                 Cbuf_AddText( "\n" );
             }
         }
         if( !end )
             break;
         p = end + 1;
     }
 }
Referenced by CL_KeyDownEvent(), and CL_KeyUpEvent().
CL_SaveConsoleHistory()
void CL_SaveConsoleHistory (void)
Definition at line 1536 of file cl_keys.c.
 {
     int                     i;
     int                     lineLength, saveBufferLength, additionalLength;
     fileHandle_t    f;
     consoleSaveBuffer[ 0 ] = '\0';
     i = ( nextHistoryLine - 1 ) % COMMAND_HISTORY;
     do
     {
         if( historyEditLines[ i ].buffer[ 0 ] )
         {
             lineLength = strlen( historyEditLines[ i ].buffer );
             saveBufferLength = strlen( consoleSaveBuffer );
             //ICK
             additionalLength = lineLength + strlen( "999 999 999  " );
             if( saveBufferLength + additionalLength < MAX_CONSOLE_SAVE_BUFFER )
             {
                 Q_strcat( consoleSaveBuffer, MAX_CONSOLE_SAVE_BUFFER,
                         va( "%d %d %d %s ",
                         historyEditLines[ i ].cursor,
                         historyEditLines[ i ].scroll,
                         lineLength,
                         historyEditLines[ i ].buffer ) );
             }
             else
                 break;
         }
         i = ( i - 1 + COMMAND_HISTORY ) % COMMAND_HISTORY;
     }
     while( i != ( nextHistoryLine - 1 ) % COMMAND_HISTORY );
     consoleSaveBufferSize = strlen( consoleSaveBuffer );
     f = FS_FOpenFileWrite( CONSOLE_HISTORY_FILE );
     if( !f )
     {
         Com_Printf( "Couldn't write %s.\n", CONSOLE_HISTORY_FILE );
         return;
     }
     if( FS_Write( consoleSaveBuffer, consoleSaveBufferSize, f ) < consoleSaveBufferSize )
         Com_Printf( "Couldn't write %s.\n", CONSOLE_HISTORY_FILE );
     FS_FCloseFile( f );
 }
Referenced by Console_Key().
Console_Key()
void Console_Key (int key)
Definition at line 606 of file cl_keys.c.
{
     // ctrl-L clears screen
     if ( key == 'l' && keys[K_CTRL].down ) {
         Cbuf_AddText ("clear\n");
         return;
     }
     // enter finishes the line
     if ( key == K_ENTER || key == K_KP_ENTER ) {
         // if not in the game explicitly prepend a slash if needed
         if ( clc.state != CA_ACTIVE && con_autochat->integer &&
                 g_consoleField.buffer[0] &&
                 g_consoleField.buffer[0] != '\\' &&
                 g_consoleField.buffer[0] != '/' ) {
             char    temp[MAX_EDIT_LINE-1];
             Q_strncpyz( temp, g_consoleField.buffer, sizeof( temp ) );
             Com_sprintf( g_consoleField.buffer, sizeof( g_consoleField.buffer ), "\\%s", temp );
             g_consoleField.cursor++;
         }
         Com_Printf ( "]%s\n", g_consoleField.buffer );
         // leading slash is an explicit command
         if ( g_consoleField.buffer[0] == '\\' || g_consoleField.buffer[0] == '/' ) {
             Cbuf_AddText( g_consoleField.buffer+1 );    // valid command
             Cbuf_AddText ("\n");
         } else {
             // other text will be chat messages
             if ( !g_consoleField.buffer[0] ) {
                 return; // empty lines just scroll the console without adding to history
             } else {
                 if ( con_autochat->integer ) {
                     Cbuf_AddText ("cmd say ");
                 }
                 Cbuf_AddText( g_consoleField.buffer );
                 Cbuf_AddText ("\n");
             }
         }
         // copy line to history buffer
         historyEditLines[nextHistoryLine % COMMAND_HISTORY] = g_consoleField;
         nextHistoryLine++;
         historyLine = nextHistoryLine;
         Field_Clear( &g_consoleField );
         g_consoleField.widthInChars = g_console_field_width;
         CL_SaveConsoleHistory( );
         if ( clc.state == CA_DISCONNECTED ) {
             SCR_UpdateScreen ();    // force an update, because the command
         }                           // may take some time
         return;
     }
     // command completion
     if (key == K_TAB) {
         Field_AutoComplete(&g_consoleField);
         return;
     }
     // command history (ctrl-p ctrl-n for unix style)
     if ( (key == K_MWHEELUP && keys[K_SHIFT].down) || ( key == K_UPARROW ) || ( key == K_KP_UPARROW ) ||
          ( ( tolower(key) == 'p' ) && keys[K_CTRL].down ) ) {
         if ( nextHistoryLine - historyLine < COMMAND_HISTORY
             && historyLine > 0 ) {
             historyLine--;
         }
         g_consoleField = historyEditLines[ historyLine % COMMAND_HISTORY ];
         return;
     }
     if ( (key == K_MWHEELDOWN && keys[K_SHIFT].down) || ( key == K_DOWNARROW ) || ( key == K_KP_DOWNARROW ) ||
          ( ( tolower(key) == 'n' ) && keys[K_CTRL].down ) ) {
         historyLine++;
         if (historyLine >= nextHistoryLine) {
             historyLine = nextHistoryLine;
             Field_Clear( &g_consoleField );
             g_consoleField.widthInChars = g_console_field_width;
             return;
         }
         g_consoleField = historyEditLines[ historyLine % COMMAND_HISTORY ];
         return;
     }
     // console scrolling
     if ( key == K_PGUP ) {
         Con_PageUp();
         return;
     }
     if ( key == K_PGDN) {
         Con_PageDown();
         return;
     }
     if ( key == K_MWHEELUP) {   //----(SA)  added some mousewheel functionality to the console
         Con_PageUp();
         if(keys[K_CTRL].down) { // hold <ctrl> to accelerate scrolling
             Con_PageUp();
             Con_PageUp();
         }
         return;
     }
     if ( key == K_MWHEELDOWN) { //----(SA)  added some mousewheel functionality to the console
         Con_PageDown();
         if(keys[K_CTRL].down) { // hold <ctrl> to accelerate scrolling
             Con_PageDown();
             Con_PageDown();
         }
         return;
     }
     // ctrl-home = top of console
     if ( key == K_HOME && keys[K_CTRL].down ) {
         Con_Top();
         return;
     }
     // ctrl-end = bottom of console
     if ( key == K_END && keys[K_CTRL].down ) {
         Con_Bottom();
         return;
     }
     // pass to the normal editline routine
     Field_KeyDownEvent( &g_consoleField, key );
 }
Referenced by CL_KeyDownEvent().
Field_BigDraw()
void Field_BigDraw (field_t * edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
Definition at line 417 of file cl_keys.c.
 {
     Field_VariableSizeDraw( edit, x, y, width, BIGCHAR_WIDTH, showCursor, noColorEscape );
 }
Referenced by Con_DrawNotify().
Field_CharEvent()
void Field_CharEvent (field_t * edit, int ch)
Definition at line 517 of file cl_keys.c.
{
     int     len;
     if ( ch == 'v' - 'a' + 1 ) {    // ctrl-v is paste
         Field_Paste( edit );
         return;
     }
     if ( ch == 'c' - 'a' + 1 ) {    // ctrl-c clears the field
         Field_Clear( edit );
         return;
     }
     len = strlen( edit->buffer );
     if ( ch == 'h' - 'a' + 1 )  {   // ctrl-h is backspace
         if ( edit->cursor > 0 ) {
             memmove( edit->buffer + edit->cursor - 1,
                 edit->buffer + edit->cursor, len + 1 - edit->cursor );
             edit->cursor--;
             if ( edit->cursor < edit->scroll )
             {
                 edit->scroll--;
             }
         }
         return;
     }
     if ( ch == 'a' - 'a' + 1 ) {    // ctrl-a is home
         edit->cursor = 0;
         edit->scroll = 0;
         return;
     }
     if ( ch == 'e' - 'a' + 1 ) {    // ctrl-e is end
         edit->cursor = len;
         edit->scroll = edit->cursor - edit->widthInChars;
         return;
     }
     //
     // ignore any other non printable chars
     //
     if ( ch < 32 ) {
         return;
     }
     if ( key_overstrikeMode ) {
         // - 2 to leave room for the leading slash and trailing \0
         if ( edit->cursor == MAX_EDIT_LINE - 2 )
             return;
         edit->buffer[edit->cursor] = ch;
         edit->cursor++;
     } else {    // insert mode
         // - 2 to leave room for the leading slash and trailing \0
         if ( len == MAX_EDIT_LINE - 2 ) {
             return; // all full
         }
         memmove( edit->buffer + edit->cursor + 1,
             edit->buffer + edit->cursor, len + 1 - edit->cursor );
         edit->buffer[edit->cursor] = ch;
         edit->cursor++;
     }
     if ( edit->cursor >= edit->widthInChars ) {
         edit->scroll++;
     }
     if ( edit->cursor == len + 1) {
         edit->buffer[edit->cursor] = 0;
     }
 }
Referenced by CL_CharEvent(), and Field_Paste().
Field_Draw()
void Field_Draw (field_t * edit, int x, int y, int width, qboolean showCursor, qboolean noColorEscape)
Definition at line 412 of file cl_keys.c.
 {
     Field_VariableSizeDraw( edit, x, y, width, SMALLCHAR_WIDTH, showCursor, noColorEscape );
 }
Referenced by Con_DrawInput().
Field_KeyDownEvent()
void Field_KeyDownEvent (field_t * edit, int key)
Definition at line 456 of file cl_keys.c.
{
     int     len;
     // shift-insert is paste
     if ( ( ( key == K_INS ) || ( key == K_KP_INS ) ) && keys[K_SHIFT].down ) {
         Field_Paste( edit );
         return;
     }
     key = tolower( key );
     len = strlen( edit->buffer );
     switch ( key ) {
         case K_DEL:
             if ( edit->cursor < len ) {
                 memmove( edit->buffer + edit->cursor,
                     edit->buffer + edit->cursor + 1, len - edit->cursor );
             }
             break;
         case K_RIGHTARROW:
             if ( edit->cursor < len ) {
                 edit->cursor++;
             }
             break;
         case K_LEFTARROW:
             if ( edit->cursor > 0 ) {
                 edit->cursor--;
             }
             break;
         case K_HOME:
             edit->cursor = 0;
             break;
         case K_END:
             edit->cursor = len;
             break;
         case K_INS:
             key_overstrikeMode = !key_overstrikeMode;
             break;
         default:
             break;
     }
     // Change scroll if cursor is no longer visible
     if ( edit->cursor < edit->scroll ) {
         edit->scroll = edit->cursor;
     } else if ( edit->cursor >= edit->scroll + edit->widthInChars && edit->cursor <= len ) {
         edit->scroll = edit->cursor - edit->widthInChars + 1;
     }
 }
Referenced by Console_Key(), and Message_Key().
Field_Paste()
void Field_Paste (field_t * edit)
Definition at line 427 of file cl_keys.c.
{
     char    *cbd;
     int     pasteLen, i;
     cbd = Sys_GetClipboardData();
     if ( !cbd ) {
         return;
     }
     // send as if typed, so insert / overstrike works properly
     pasteLen = strlen( cbd );
     for ( i = 0 ; i < pasteLen ; i++ ) {
         Field_CharEvent( edit, cbd[i] );
     }
     Z_Free( cbd );
 }
Referenced by Field_CharEvent(), and Field_KeyDownEvent().
Field_VariableSizeDraw()
void Field_VariableSizeDraw (field_t * edit, int x, int y, int width, int size, qboolean showCursor, qboolean noColorEscape)
Definition at line 339 of file cl_keys.c.
{
     int     len;
     int     drawLen;
     int     prestep;
     int     cursorChar;
     char    str[MAX_STRING_CHARS];
     int     i;
     drawLen = edit->widthInChars - 1; // - 1 so there is always a space for the cursor
     len = strlen( edit->buffer );
     // guarantee that cursor will be visible
     if ( len <= drawLen ) {
         prestep = 0;
     } else {
         if ( edit->scroll + drawLen > len ) {
             edit->scroll = len - drawLen;
             if ( edit->scroll < 0 ) {
                 edit->scroll = 0;
             }
         }
         prestep = edit->scroll;
     }
     if ( prestep + drawLen > len ) {
         drawLen = len - prestep;
     }
     // extract <drawLen> characters from the field at <prestep>
     if ( drawLen >= MAX_STRING_CHARS ) {
         Com_Error( ERR_DROP, "drawLen >= MAX_STRING_CHARS" );
     }
     Com_Memcpy( str, edit->buffer + prestep, drawLen );
     str[ drawLen ] = 0;
     // draw it
     if ( size == SMALLCHAR_WIDTH ) {
         float   color[4];
         color[0] = color[1] = color[2] = color[3] = 1.0;
         SCR_DrawSmallStringExt( x, y, str, color, qfalse, noColorEscape );
     } else {
         // draw big string with drop shadow
         SCR_DrawBigString( x, y, str, 1.0, noColorEscape );
     }
     // draw the cursor
     if ( showCursor ) {
         if ( (int)( cls.realtime >> 8 ) & 1 ) {
             return;     // off blink
         }
         if ( key_overstrikeMode ) {
             cursorChar = 11;
         } else {
             cursorChar = 10;
         }
         i = drawLen - strlen( str );
         if ( size == SMALLCHAR_WIDTH ) {
             SCR_DrawSmallChar( x + ( edit->cursor - prestep - i ) * size, y, cursorChar );
         } else {
             str[0] = cursorChar;
             str[1] = 0;
             SCR_DrawBigString( x + ( edit->cursor - prestep - i ) * size, y, str, 1.0, qfalse );
         }
     }
 }
Referenced by Field_BigDraw(), and Field_Draw().
Key_Bind_f()
void Key_Bind_f (void)
Definition at line 1002 of file cl_keys.c.
 {
     int         i, c, b;
     char        cmd[1024];
     c = Cmd_Argc();
     if (c < 2)
     {
         Com_Printf ("bind <key> [command] : attach a command to a key\n");
         return;
     }
     b = Key_StringToKeynum (Cmd_Argv(1));
     if (b==-1)
     {
         Com_Printf ("\"%s\" isn't a valid key\n", Cmd_Argv(1));
         return;
     }
     if (c == 2)
     {
         if (keys[b].binding && keys[b].binding[0])
             Com_Printf ("\"%s\" = \"%s\"\n", Key_KeynumToString(b), keys[b].binding );
         else
             Com_Printf ("\"%s\" is not bound\n", Key_KeynumToString(b) );
         return;
     }
 // copy the rest of the command line
     cmd[0] = 0;     // start out with a null string
     for (i=2 ; i< c ; i++)
     {
         strcat (cmd, Cmd_Argv(i));
         if (i != (c-1))
             strcat (cmd, " ");
     }
     Key_SetBinding (b, cmd);
 }
Referenced by CL_InitKeyCommands().
Key_Bindlist_f()
void Key_Bindlist_f (void)
Definition at line 1070 of file cl_keys.c.
{
     int     i;
     for ( i = 0 ; i < MAX_KEYS ; i++ ) {
         if ( keys[i].binding && keys[i].binding[0] ) {
             Com_Printf( "%s \"%s\"\n", Key_KeynumToString(i), keys[i].binding );
         }
     }
 }
Referenced by CL_InitKeyCommands().
Key_ClearStates()
void Key_ClearStates (void)
Definition at line 1413 of file cl_keys.c.
 {
     int     i;
     anykeydown = 0;
     for ( i=0 ; i < MAX_KEYS ; i++ ) {
         if ( keys[i].down ) {
             CL_KeyEvent( i, qfalse, 0 );
         }
         keys[i].down = 0;
         keys[i].repeats = 0;
     }
 }
Referenced by CL_KeyDownEvent(), CL_UISystemCalls(), and Key_SetCatcher().
Key_CompleteBind()
static void Key_CompleteBind (char * args, int argNum) static
Definition at line 1114 of file cl_keys.c.
 {
     char *p;
     if( argNum == 2 )
     {
         // Skip "bind "
         p = Com_SkipTokens( args, 1, " " );
         if( p > args )
             Field_CompleteKeyname( );
     }
     else if( argNum >= 3 )
     {
         // Skip "bind <key> "
         p = Com_SkipTokens( args, 2, " " );
         if( p > args )
             Field_CompleteCommand( p, qtrue, qtrue );
     }
 }
Referenced by CL_InitKeyCommands().
Key_CompleteUnbind()
static void Key_CompleteUnbind (char * args, int argNum) static
Definition at line 1097 of file cl_keys.c.
 {
     if( argNum == 2 )
     {
         // Skip "unbind "
         char *p = Com_SkipTokens( args, 1, " " );
         if( p > args )
             Field_CompleteKeyname( );
     }
 }
Referenced by CL_InitKeyCommands().
Key_GetBinding()
char* Key_GetBinding (int keynum)
Definition at line 930 of file cl_keys.c.
{
     if ( keynum < 0 || keynum >= MAX_KEYS ) {
         return "";
     }
     return keys[ keynum ].binding;
 }
Referenced by Key_GetBindingBuf().
Key_GetCatcher()
int Key_GetCatcher (void)
Definition at line 1436 of file cl_keys.c.
{
     return keyCatchers;
 }
Referenced by CL_BindUICommand(), CL_CgameSystemCalls(), CL_CharEvent(), CL_CmdButtons(), CL_Frame(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), CL_ParseBinding(), CL_ShutdownCGame(), CL_ShutdownUI(), CL_UISystemCalls(), Con_Close(), Con_DrawConsole(), Con_DrawInput(), Con_DrawNotify(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), Con_RunConsole(), Con_ToggleConsole_f(), Message_Key(), and SCR_DrawScreenField().
Key_GetKey()
int Key_GetKey (const char * binding)
Definition at line 944 of file cl_keys.c.
{
   int i;
   if (binding) {
     for (i=0 ; i < MAX_KEYS ; i++) {
       if (keys[i].binding && Q_stricmp(binding, keys[i].binding) == 0) {
         return i;
       }
     }
   }
   return -1;
 }
Referenced by CL_CgameSystemCalls().
Key_GetOverstrikeMode()
qboolean Key_GetOverstrikeMode (void)
Definition at line 790 of file cl_keys.c.
{
     return key_overstrikeMode;
 }
Referenced by CL_UISystemCalls().
Key_IsDown()
qboolean Key_IsDown (int keynum)
Definition at line 805 of file cl_keys.c.
{
     if ( keynum < 0 || keynum >= MAX_KEYS ) {
         return qfalse;
     }
     return keys[keynum].down;
 }
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
Key_KeynameCompletion()
void Key_KeynameCompletion (void(*)(const char *s) callback)
Definition at line 1085 of file cl_keys.c.
{
     int     i;
     for( i = 0; keynames[ i ].name != NULL; i++ )
         callback( keynames[ i ].name );
 }
Referenced by Field_CompleteKeyname().
Key_KeynumToString()
char* Key_KeynumToString (int keynum)
Definition at line 860 of file cl_keys.c.
{
     keyname_t   *kn;
     static  char    tinystr[5];
     int         i, j;
     if ( keynum == -1 ) {
         return "<KEY NOT FOUND>";
     }
     if ( keynum < 0 || keynum >= MAX_KEYS ) {
         return "<OUT OF RANGE>";
     }
     // check for printable ascii (don't use quote)
     if ( keynum > 32 && keynum < 127 && keynum != '"' && keynum != ';' ) {
         tinystr[0] = keynum;
         tinystr[1] = 0;
         return tinystr;
     }
     // check for a key string
     for ( kn=keynames ; kn->name ; kn++ ) {
         if (keynum == kn->keynum) {
             return kn->name;
         }
     }
     // make a hex string
     i = keynum >> 4;
     j = keynum & 15;
     tinystr[0] = '0';
     tinystr[1] = 'x';
     tinystr[2] = i > 9 ? i - 10 + 'a' : i + '0';
     tinystr[3] = j > 9 ? j - 10 + 'a' : j + '0';
     tinystr[4] = 0;
     return tinystr;
 }
Referenced by Key_Bind_f(), Key_Bindlist_f(), Key_KeynumToStringBuf(), and Key_WriteBindings().
Key_SetBinding()
void Key_SetBinding (int keynum, const char * binding)
Definition at line 906 of file cl_keys.c.
{
     if ( keynum < 0 || keynum >= MAX_KEYS ) {
         return;
     }
     // free old bindings
     if ( keys[ keynum ].binding ) {
         Z_Free( keys[ keynum ].binding );
     }
     // allocate memory for new binding
     keys[keynum].binding = CopyString( binding );
     // consider this like modifying an archived cvar, so the
     // file write will be triggered at the next opportunity
     cvar_modifiedFlags |= CVAR_ARCHIVE;
 }
Referenced by CL_UISystemCalls(), Key_Bind_f(), Key_Unbind_f(), and Key_Unbindall_f().
Key_SetCatcher()
void Key_SetCatcher (int catcher)
Definition at line 1445 of file cl_keys.c.
{
     // If the catcher state is changing, clear all key states
     if( catcher != keyCatchers )
         Key_ClearStates( );
     keyCatchers = catcher;
 }
Referenced by CL_CgameSystemCalls(), CL_Connect_f(), CL_KeyDownEvent(), CL_MapLoading(), CL_Shutdown(), CL_ShutdownCGame(), CL_ShutdownUI(), CL_StartDemoLoop(), CL_UISystemCalls(), Con_Close(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), Con_ToggleConsole_f(), and Message_Key().
Key_SetOverstrikeMode()
void Key_SetOverstrikeMode (qboolean state)
Definition at line 795 of file cl_keys.c.
{
     key_overstrikeMode = state;
 }
Referenced by CL_UISystemCalls().
Key_StringToKeynum()
int Key_StringToKeynum (char * str)
Definition at line 826 of file cl_keys.c.
{
     keyname_t   *kn;
     int         n;
     if ( !str || !str[0] ) {
         return -1;
     }
     if ( !str[1] ) {
         return tolower( str[0] );
     }
     // check for hex code
     n = Com_HexStrToInt( str );
     if ( n >= 0 && n < MAX_KEYS ) {
         return n;
     }
     // scan for a text match
     for ( kn=keynames ; kn->name ; kn++ ) {
         if ( !Q_stricmp( str,kn->name ) )
             return kn->keynum;
     }
     return -1;
 }
Referenced by Key_Bind_f(), and Key_Unbind_f().
Key_Unbind_f()
void Key_Unbind_f (void)
Definition at line 962 of file cl_keys.c.
 {
     int     b;
     if (Cmd_Argc() != 2)
     {
         Com_Printf ("unbind <key> : remove commands from a key\n");
         return;
     }
     b = Key_StringToKeynum (Cmd_Argv(1));
     if (b==-1)
     {
         Com_Printf ("\"%s\" isn't a valid key\n", Cmd_Argv(1));
         return;
     }
     Key_SetBinding (b, "");
 }
Referenced by CL_InitKeyCommands().
Key_Unbindall_f()
void Key_Unbindall_f (void)
Definition at line 987 of file cl_keys.c.
 {
     int     i;
     for (i=0 ; i < MAX_KEYS; i++)
         if (keys[i].binding)
             Key_SetBinding (i, "");
 }
Referenced by CL_InitKeyCommands().
Key_WriteBindings()
void Key_WriteBindings (fileHandle_t f)
Definition at line 1049 of file cl_keys.c.
{
     int     i;
     FS_Printf (f, "unbindall\n" );
     for (i=0 ; i<MAX_KEYS ; i++) {
         if (keys[i].binding && keys[i].binding[0] ) {
             FS_Printf (f, "bind %s \"%s\"\n", Key_KeynumToString(i), keys[i].binding);
         }
     }
 }
Referenced by Com_WriteConfigToFile().
Message_Key()
void Message_Key (int key)
Definition at line 751 of file cl_keys.c.
{
     char    buffer[MAX_STRING_CHARS];
     if (key == K_ESCAPE) {
         Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_MESSAGE );
         Field_Clear( &chatField );
         return;
     }
     if ( key == K_ENTER || key == K_KP_ENTER )
     {
         if ( chatField.buffer[0] && clc.state == CA_ACTIVE ) {
             if (chat_playerNum != -1 )
                 Com_sprintf( buffer, sizeof( buffer ), "tell %i \"%s\"\n", chat_playerNum, chatField.buffer );
             else if (chat_team)
                 Com_sprintf( buffer, sizeof( buffer ), "say_team \"%s\"\n", chatField.buffer );
             else
                 Com_sprintf( buffer, sizeof( buffer ), "say \"%s\"\n", chatField.buffer );
             CL_AddReliableCommand(buffer, qfalse);
         }
         Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_MESSAGE );
         Field_Clear( &chatField );
         return;
     }
     Field_KeyDownEvent( &chatField, key );
 }
Referenced by CL_KeyDownEvent().
Variable Documentation
anykeydown
int anykeydown
Definition at line 45 of file cl_keys.c.
Referenced by CL_CmdButtons(), CL_KeyDownEvent(), CL_KeyUpEvent(), and Key_ClearStates().
chat_playerNum
int chat_playerNum
Definition at line 40 of file cl_keys.c.
Referenced by Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), and Message_Key().
chat_team
qboolean chat_team
Definition at line 38 of file cl_keys.c.
Referenced by Con_DrawNotify(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), and Message_Key().
chatField
field_t chatField
Definition at line 37 of file cl_keys.c.
Referenced by CL_CharEvent(), Con_DrawNotify(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), and Message_Key().
consoleSaveBuffer
char consoleSaveBuffer[MAX_CONSOLE_SAVE_BUFFER] static
Definition at line 1456 of file cl_keys.c.
Referenced by CL_LoadConsoleHistory(), and CL_SaveConsoleHistory().
consoleSaveBufferSize
int consoleSaveBufferSize = 0 static
Definition at line 1457 of file cl_keys.c.
Referenced by CL_LoadConsoleHistory(), and CL_SaveConsoleHistory().
g_consoleField
field_t g_consoleField
Definition at line 36 of file cl_keys.c.
Referenced by CL_CharEvent(), CL_InitRenderer(), Con_Close(), Con_DrawInput(), Con_Init(), Con_ToggleConsole_f(), and Console_Key().
historyEditLines
field_t historyEditLines[COMMAND_HISTORY]
Definition at line 30 of file cl_keys.c.
Referenced by CL_LoadConsoleHistory(), CL_SaveConsoleHistory(), Con_Init(), and Console_Key().
historyLine
int historyLine
Definition at line 33 of file cl_keys.c.
Referenced by CL_LoadConsoleHistory(), and Console_Key().
key_overstrikeMode
qboolean key_overstrikeMode
Definition at line 43 of file cl_keys.c.
Referenced by Field_CharEvent(), Field_KeyDownEvent(), Field_VariableSizeDraw(), Key_GetOverstrikeMode(), and Key_SetOverstrikeMode().
keyCatchers
int keyCatchers = 0 static
Definition at line 1429 of file cl_keys.c.
Referenced by Key_GetCatcher(), and Key_SetCatcher().
keynames
keyname_t keynames[]
Definition at line 56 of file cl_keys.c.
Referenced by Key_KeynameCompletion(), Key_KeynumToString(), and Key_StringToKeynum().
keys
qkey_t keys[MAX_KEYS]
Definition at line 46 of file cl_keys.c.
Referenced by BotCheckValidReplyChatKeySet(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_ParseBinding(), Console_Key(), Field_KeyDownEvent(), Key_Bind_f(), Key_Bindlist_f(), Key_ClearStates(), Key_GetBinding(), Key_GetKey(), Key_IsDown(), Key_SetBinding(), Key_Unbindall_f(), and Key_WriteBindings().
nextHistoryLine
int nextHistoryLine
Definition at line 32 of file cl_keys.c.
Referenced by CL_LoadConsoleHistory(), CL_SaveConsoleHistory(), and Console_Key().