ioquake3 doxygen: C:/entry/dev/ioquake3/code/ui/ui_syscalls.c File Reference
ui_syscalls.c File Reference
#include "ui_local.h"
Functions
static intptr_t (QDECL *syscall)(intptr_t arg
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
int PASSFLOAT (float x)
void trap_Print (const char *string)
void trap_Error (const char *string)
int trap_Milliseconds (void)
void trap_Cvar_Register (vmCvar_t *cvar, const char *var_name, const char *value, int flags)
void trap_Cvar_Update (vmCvar_t *cvar)
void trap_Cvar_Set (const char *var_name, const char *value)
float trap_Cvar_VariableValue (const char *var_name)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
void trap_Cvar_SetValue (const char *var_name, float value)
void trap_Cvar_Reset (const char *name)
void trap_Cvar_Create (const char *var_name, const char *var_value, int flags)
void trap_Cvar_InfoStringBuffer (int bit, char *buffer, int bufsize)
int trap_Argc (void)
void trap_Argv (int n, char *buffer, int bufferLength)
void trap_Cmd_ExecuteText (int exec_when, const char *text)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
void trap_FS_FCloseFile (fileHandle_t f)
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
qhandle_t trap_R_RegisterModel (const char *name)
qhandle_t trap_R_RegisterSkin (const char *name)
void trap_R_RegisterFont (const char *fontName, int pointSize, fontInfo_t *font)
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
void trap_R_ClearScene (void)
void trap_R_AddRefEntityToScene (const refEntity_t *re)
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
void trap_R_RenderScene (const refdef_t *fd)
void trap_R_SetColor (const float *rgba)
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
void trap_UpdateScreen (void)
int trap_CM_LerpTag (orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName)
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
void trap_Key_KeynumToStringBuf (int keynum, char *buf, int buflen)
void trap_Key_GetBindingBuf (int keynum, char *buf, int buflen)
void trap_Key_SetBinding (int keynum, const char *binding)
qboolean trap_Key_IsDown (int keynum)
qboolean trap_Key_GetOverstrikeMode (void)
void trap_Key_SetOverstrikeMode (qboolean state)
void trap_Key_ClearStates (void)
int trap_Key_GetCatcher (void)
void trap_Key_SetCatcher (int catcher)
void trap_GetClipboardData (char *buf, int bufsize)
void trap_GetClientState (uiClientState_t *state)
void trap_GetGlconfig (glconfig_t *glconfig)
int trap_GetConfigString (int index, char *buff, int buffsize)
int trap_LAN_GetServerCount (int source)
void trap_LAN_GetServerAddressString (int source, int n, char *buf, int buflen)
void trap_LAN_GetServerInfo (int source, int n, char *buf, int buflen)
int trap_LAN_GetServerPing (int source, int n)
int trap_LAN_GetPingQueueCount (void)
int trap_LAN_ServerStatus (const char *serverAddress, char *serverStatus, int maxLen)
void trap_LAN_SaveCachedServers (void)
void trap_LAN_LoadCachedServers (void)
void trap_LAN_ResetPings (int n)
void trap_LAN_ClearPing (int n)
void trap_LAN_GetPing (int n, char *buf, int buflen, int *pingtime)
void trap_LAN_GetPingInfo (int n, char *buf, int buflen)
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
int trap_LAN_ServerIsVisible (int source, int n)
qboolean trap_LAN_UpdateVisiblePings (int source)
int trap_LAN_AddServer (int source, const char *name, const char *addr)
void trap_LAN_RemoveServer (int source, const char *addr)
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
int trap_MemoryRemaining (void)
void trap_GetCDKey (char *buf, int buflen)
void trap_SetCDKey (char *buf)
int trap_PC_AddGlobalDefine (char *define)
int trap_PC_LoadSource (const char *filename)
int trap_PC_FreeSource (int handle)
int trap_PC_ReadToken (int handle, pc_token_t *pc_token)
int trap_PC_SourceFileAndLine (int handle, char *filename, int *line)
void trap_S_StopBackgroundTrack (void)
void trap_S_StartBackgroundTrack (const char *intro, const char *loop)
int trap_RealTime (qtime_t *qtime)
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
e_status trap_CIN_StopCinematic (int handle)
e_status trap_CIN_RunCinematic (int handle)
void trap_CIN_DrawCinematic (int handle)
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
qboolean trap_VerifyCDKey (const char *key, const char *chksum)
void trap_SetPbClStatus (int status)
Function Documentation
dllEntry()
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
Definition at line 33 of file ui_syscalls.c.
{
     syscall = syscallptr;
 }
intptr_t()
static intptr_t (QDECL * syscall) static
PASSFLOAT()
int PASSFLOAT (float x)
Definition at line 37 of file ui_syscalls.c.
{
     floatint_t fi;
     fi.f = x;
     return fi.i;
 }
Referenced by trap_CM_LerpTag(), trap_Cvar_SetValue(), trap_R_AddLightToScene(), and trap_R_DrawStretchPic().
trap_Argc()
int trap_Argc (void)
Definition at line 96 of file ui_syscalls.c.
                       {
     return syscall( UI_ARGC );
 }
Referenced by CG_ServerCommand(), CG_TestModel_f(), Cmd_CallTeamVote_f(), Cmd_Follow_f(), Cmd_GameCommand_f(), Cmd_Say_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_Tell_f(), ConcatArgs(), Svcmd_AddIP_f(), Svcmd_ForceTeam_f(), Svcmd_RemoveIP_f(), and UI_ConsoleCommand().
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
Definition at line 100 of file ui_syscalls.c.
{
     syscall( UI_ARGV, n, buffer, bufferLength );
 }
Referenced by CG_Argv(), CG_TargetCommand_f(), ClientCommand(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_Follow_f(), Cmd_GameCommand_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_Vote_f(), ConcatArgs(), ConsoleCommand(), Svcmd_AddBot_f(), Svcmd_AddIP_f(), Svcmd_ForceTeam_f(), Svcmd_RemoveIP_f(), and UI_Argv().
trap_CIN_DrawCinematic()
void trap_CIN_DrawCinematic (int handle)
Definition at line 383 of file ui_syscalls.c.
{
   syscall(UI_CIN_DRAWCINEMATIC, handle);
 }
Referenced by UI_DrawCinematic().
trap_CIN_PlayCinematic()
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
Definition at line 365 of file ui_syscalls.c.
{
   return syscall(UI_CIN_PLAYCINEMATIC, arg0, xpos, ypos, width, height, bits);
 }
Referenced by UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawPreviewCinematic(), UI_FeederSelection(), and UI_PlayCinematic().
trap_CIN_RunCinematic()
e_status trap_CIN_RunCinematic (int handle)
Definition at line 377 of file ui_syscalls.c.
{
   return syscall(UI_CIN_RUNCINEMATIC, handle);
 }
Referenced by UI_DrawClanCinematic(), UI_DrawMapCinematic(), UI_DrawNetMapCinematic(), UI_DrawPreviewCinematic(), and UI_RunCinematicFrame().
trap_CIN_SetExtents()
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Definition at line 389 of file ui_syscalls.c.
{
   syscall(UI_CIN_SETEXTENTS, handle, x, y, w, h);
 }
Referenced by UI_DrawCinematic().
trap_CIN_StopCinematic()
e_status trap_CIN_StopCinematic (int handle)
Definition at line 371 of file ui_syscalls.c.
{
   return syscall(UI_CIN_STOPCINEMATIC, handle);
 }
Referenced by UI_ClanName_HandleKey(), UI_FeederSelection(), UI_RunMenuScript(), and UI_StopCinematic().
trap_CM_LerpTag()
int trap_CM_LerpTag (orientation_t * tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char * tagName)
Definition at line 184 of file ui_syscalls.c.
{
     return syscall( UI_CM_LERPTAG, tag, mod, startFrame, endFrame, PASSFLOAT(frac), tagName );
 }
Referenced by UI_PositionEntityOnTag(), and UI_PositionRotatedEntityOnTag().
trap_Cmd_ExecuteText()
void trap_Cmd_ExecuteText (int exec_when, const char * text)
Definition at line 104 of file ui_syscalls.c.
{
     syscall( UI_CMD_EXECUTETEXT, exec_when, text );
 }
Referenced by _UI_Init(), ArenaServers_DoRefresh(), ArenaServers_Go(), ArenaServers_StartRefresh(), Controls_SetConfig(), Demos_MenuEvent(), GraphicsOptions_ApplyChanges(), InGame_Event(), InGame_RestartAction(), LoadConfig_MenuEvent(), Main_MenuEvent(), Menu_DefaultKey(), NeedCDAction(), NeedCDKeyAction(), Rankings_MenuEvent(), ServerOptions_Start(), Setup_ResetDefaults_Action(), SpecifyServer_Event(), TeamMain_MenuEvent(), UI_AddBotsMenu_FightEvent(), UI_CinematicsMenu_Event(), UI_CreditMenu_Key(), UI_DoServerRefresh(), UI_KeyConnect(), UI_Mods_MenuEvent(), UI_RemoveBotsMenu_DeleteEvent(), UI_RunMenuScript(), UI_SaveConfigMenu_SaveEvent(), UI_SoundOptionsMenu_Event(), UI_SPArena_Start(), UI_SPPostgameMenu_AgainEvent(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuEvent(), UI_SPPostgameMenu_MenuKey(), UI_StartDemoLoop(), UI_StartServerRefresh(), UI_StartSkirmish(), and UI_TeamOrdersMenu_ListEvent().
trap_Cvar_Create()
void trap_Cvar_Create (const char * var_name, const char * var_value, int flags)
Definition at line 88 of file ui_syscalls.c.
{
     syscall( UI_CVAR_CREATE, var_name, var_value, flags );
 }
trap_Cvar_InfoStringBuffer()
void trap_Cvar_InfoStringBuffer (int bit, char * buffer, int bufsize)
Definition at line 92 of file ui_syscalls.c.
{
     syscall( UI_CVAR_INFOSTRINGBUFFER, bit, buffer, bufsize );
 }
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * cvar, const char * var_name, const char * value, int flags)
Definition at line 58 of file ui_syscalls.c.
{
     syscall( UI_CVAR_REGISTER, cvar, var_name, value, flags );
 }
Referenced by _UI_Init(), ArenaServers_MenuInit(), BotAILoadMap(), BotAISetup(), BotSetupDeathmatchAI(), CG_RegisterCvars(), G_InitBots(), G_LoadArenas(), G_LoadBots(), G_RegisterCvars(), UI_LoadArenas(), UI_LoadBots(), and UI_RegisterCvars().
trap_Cvar_Reset()
void trap_Cvar_Reset (const char * name)
Definition at line 84 of file ui_syscalls.c.
{
     syscall( UI_CVAR_RESET, name );
 }
Referenced by Controls_InitCvars(), GraphicsOptions_ApplyChanges(), Preferences_Event(), and UI_Update().
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
Definition at line 66 of file ui_syscalls.c.
{
     syscall( UI_CVAR_SET, var_name, value );
 }
Referenced by _UI_Init(), _UI_KeyEvent(), _UI_SetActiveMenu(), ArenaServers_SaveChanges(), BeginIntermission(), BotAIStartFrame(), BotInterbreedEndMatch(), BotInterbreeding(), BotWriteSessionData(), CG_CalcVrect(), CG_DrawActiveFrame(), CG_MapRestart(), CG_ParseServerinfo(), CG_PredictPlayerState(), CG_SetSelectedPlayerName(), CG_ShowResponseHead(), CG_SizeDown_f(), CG_SizeUp_f(), CG_StartOrbit_f(), CG_UpdateCvars(), CheckCvars(), CheckExitRules(), CheckTournament(), ClientThink_real(), ErrorMessage_Key(), ExitLevel(), Favorites_Add(), G_InitBots(), G_InitSessionData(), G_RankRunFrame(), G_RegisterCvars(), G_RunFrame(), G_SpawnBots(), G_WriteClientSessionData(), G_WriteSessionData(), GraphicsOptions_ApplyChanges(), Main_MenuEvent(), PlayerModel_SaveChanges(), PlayerSettings_MenuEvent(), PlayerSettings_SaveChanges(), ServerOptions_Start(), SP_worldspawn(), SpecifyLeague_Event(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Event(), UI_ClanName_HandleKey(), UI_DrawJoinGameType(), UI_DrawMapCinematic(), UI_DrawMapPreview(), UI_DrawMapTimeToBeat(), UI_DrawNetGameType(), UI_DrawNetMapCinematic(), UI_FeederSelection(), UI_ForceMenuOff(), UI_LogAwardData(), UI_MainMenu(), UI_Mods_MenuEvent(), UI_NewGame(), UI_NextOpponent(), UI_Pause(), UI_PriorOpponent(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_SetActiveMenu(), UI_SetBestScore(), UI_SetBestScores(), UI_SetCapFragLimits(), UI_ShowPostGame(), UI_ShowTierVideo(), UI_SPLevelMenu_Init(), UI_SPPostgameMenu_MenuDraw(), UI_SPUnlock_f(), UI_SPUnlockMedals_f(), UI_StartServerRefresh(), UI_StartSkirmish(), UI_TeamName_HandleKey(), UI_Update(), and UpdateIPBans().
trap_Cvar_SetValue()
void trap_Cvar_SetValue (const char * var_name, float value)
Definition at line 80 of file ui_syscalls.c.
{
     syscall( UI_CVAR_SETVALUE, var_name, PASSFLOAT( value ) );
 }
Referenced by ArenaServers_Event(), Controls_InitCvars(), Controls_SetConfig(), GraphicsOptions_ApplyChanges(), PlayerSettings_SaveChanges(), Preferences_Event(), Reset_MenuEvent(), ServerOptions_Start(), StartServer_MenuEvent(), UI_Crosshair_HandleKey(), UI_DisplayOptionsMenu_Event(), UI_Effects_HandleKey(), UI_GameType_HandleKey(), UI_Handicap_HandleKey(), UI_JoinGameType_HandleKey(), UI_NetGameType_HandleKey(), UI_NetSource_HandleKey(), UI_NetworkOptionsMenu_Event(), UI_RunMenuScript(), UI_SelectedPlayer_HandleKey(), UI_Skill_HandleKey(), UI_SoundOptionsMenu_Event(), UI_SPArena_Start(), UI_SPLevelMenu_LevelEvent(), UI_SPLevelMenu_ResetAction(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_MenuDraw(), UI_SPSkillMenu_SkillEvent(), UI_StartSkirmish(), UI_TeamMember_HandleKey(), and UI_Update().
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * cvar)
Definition at line 62 of file ui_syscalls.c.
{
     syscall( UI_CVAR_UPDATE, cvar );
 }
Referenced by BotAIStartFrame(), BotCheckConsoleMessages(), BotInterbreedEndMatch(), BotInterbreeding(), BotTestAAS(), CG_PredictPlayerState(), CG_UpdateCvars(), CheckExitRules(), ClientThink_real(), G_CheckMinimumPlayers(), G_RegisterCvars(), G_UpdateCvars(), and UI_UpdateCvars().
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
Definition at line 76 of file ui_syscalls.c.
{
     syscall( UI_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize );
 }
Referenced by _UI_Init(), _UI_SetActiveMenu(), ArenaServers_LoadFavorites(), ArenaServers_SetType(), ArenaServers_StartRefresh(), BG_AddPredictableEventToPlayerstate(), BotInitLibrary(), BotReadSessionData(), CG_DrawCrosshair3D(), CG_DrawInformation(), CG_NewClientInfo(), CG_RegisterCvars(), CG_StartOrbit_f(), Cmd_CallVote_f(), Controls_DrawPlayer(), Controls_MenuInit(), ExitLevel(), Favorites_Add(), G_InitWorldSession(), G_RankGameOver(), G_ReadSessionData(), GraphicsOptions_GetResolutions(), GraphicsOptions_SetMenuItems(), PlayerModel_SetMenuItems(), PlayerSettings_DrawPlayer(), ServerOptions_InitPlayerItems(), SpecifyLeague_GetList(), trap_Cvar_VariableValue(), UI_BuildFindPlayerList(), UI_BuildServerDisplayList(), UI_CanShowTierVideo(), UI_Cvar_VariableString(), UI_DrawConnectScreen(), UI_GetAwardLevel(), UI_GetBestScore(), UI_LogAwardData(), UI_MainMenu(), UI_NetSource_HandleKey(), UI_SetBestScore(), UI_ShowTierVideo(), UI_SPLevelMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPUnlock_f(), and UI_SPUnlockMedals_f().
trap_Cvar_VariableValue()
float trap_Cvar_VariableValue (const char * var_name)
Definition at line 70 of file ui_syscalls.c.
{
     floatint_t fi;
     fi.i = syscall( UI_CVAR_VARIABLEVALUE, var_name );
     return fi.f;
 }
trap_Error()
void trap_Error (const char * string)
Definition at line 47 of file ui_syscalls.c.
 {
     syscall(UI_ERROR, string);
     // shut up GCC warning about returning functions, because we know better
     exit(1);
 }
Referenced by CG_Error(), Com_Error(), G_Error(), Menu_AddItem(), Menu_Draw(), MField_Draw(), UI_LoadMenus(), UI_PopMenu(), UI_PushMenu(), and UI_SetLerpFrameAnimation().
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Definition at line 120 of file ui_syscalls.c.
{
     syscall( UI_FS_FCLOSEFILE, f );
 }
Referenced by CG_ParseAnimationFile(), G_LoadArenasFromFile(), G_LoadBotsFromFile(), G_ShutdownGame(), GetMenuBuffer(), UI_CalcPostGameStats(), UI_ClearScores(), UI_LoadArenasFromFile(), UI_LoadBestScores(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
Definition at line 108 of file ui_syscalls.c.
{
     return syscall( UI_FS_FOPENFILE, qpath, f, mode );
 }
Referenced by CG_FileExists(), CG_ParseAnimationFile(), G_InitGame(), G_LoadArenasFromFile(), G_LoadBotsFromFile(), GetMenuBuffer(), UI_CalcPostGameStats(), UI_ClearScores(), UI_FileExists(), UI_hasSkinForBase(), UI_LoadArenasFromFile(), UI_LoadBestScores(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
trap_FS_GetFileList()
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
Definition at line 124 of file ui_syscalls.c.
{
     return syscall( UI_FS_GETFILELIST, path, extension, listbuf, bufsize );
 }
Referenced by Demos_MenuInit(), G_LoadArenas(), G_LoadBots(), LoadConfig_MenuInit(), PlayerModel_BuildList(), UI_BuildQ3Model_List(), UI_ClearScores(), UI_LoadArenas(), UI_LoadBots(), UI_LoadDemos(), UI_LoadMods(), UI_LoadMovies(), UI_LoadTeams(), UI_Mods_LoadMods(), and UI_TeamArenaExists().
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
Definition at line 112 of file ui_syscalls.c.
{
     syscall( UI_FS_READ, buffer, len, f );
 }
Referenced by CG_ParseAnimationFile(), G_LoadArenasFromFile(), G_LoadBotsFromFile(), GetMenuBuffer(), UI_CalcPostGameStats(), UI_LoadArenasFromFile(), UI_LoadBestScores(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
trap_FS_Seek()
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
Definition at line 128 of file ui_syscalls.c.
{
     return syscall( UI_FS_SEEK, f, offset, origin );
 }
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
Definition at line 116 of file ui_syscalls.c.
{
     syscall( UI_FS_WRITE, buffer, len, f );
 }
Referenced by G_LogPrintf(), UI_CalcPostGameStats(), and UI_ClearScores().
trap_GetCDKey()
void trap_GetCDKey (char * buf, int buflen)
Definition at line 324 of file ui_syscalls.c.
{
     syscall( UI_GET_CDKEY, buf, buflen );
 }
Referenced by UI_CDKeyMenu_Init(), UI_MainMenu(), and UI_RunMenuScript().
trap_GetClientState()
void trap_GetClientState (uiClientState_t * state)
Definition at line 236 of file ui_syscalls.c.
{
     syscall( UI_GETCLIENTSTATE, state );
 }
Referenced by InGame_MenuInit(), Options_MenuInit(), UI_BuildPlayerList(), UI_ConfirmMenu_Style(), UI_DrawConnectScreen(), UI_Message(), UI_ResetMenu(), UI_TeamOrdersMenu_BuildBotList(), and UI_TeamOrdersMenu_f().
trap_GetClipboardData()
void trap_GetClipboardData (char * buf, int bufsize)
Definition at line 232 of file ui_syscalls.c.
{
     syscall( UI_GETCLIPBOARDDATA, buf, bufsize );
 }
Referenced by MField_Paste().
trap_GetConfigString()
int trap_GetConfigString (int index, char * buff, int buffsize)
Definition at line 244 of file ui_syscalls.c.
{
     return syscall( UI_GETCONFIGSTRING, index, buff, buffsize );
 }
Referenced by InGame_MenuInit(), Prepname(), TeamMain_MenuInit(), UI_AddBotsMenu_Init(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_DrawConnectScreen(), UI_RemoveBotsMenu_GetBots(), UI_RemoveBotsMenu_SetBotNames(), UI_ServerInfoMenu(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_TeamOrdersMenu_BuildBotList(), and UI_TeamOrdersMenu_f().
trap_GetGlconfig()
void trap_GetGlconfig (glconfig_t * glconfig)
Definition at line 240 of file ui_syscalls.c.
{
     syscall( UI_GETGLCONFIG, glconfig );
 }
Referenced by _UI_Init(), CG_Init(), and UI_Init().
trap_Key_ClearStates()
void trap_Key_ClearStates (void)
Definition at line 220 of file ui_syscalls.c.
{
     syscall( UI_KEY_CLEARSTATES );
 }
Referenced by _UI_KeyEvent(), _UI_SetActiveMenu(), UI_ForceMenuOff(), UI_Pause(), and UI_RunMenuScript().
trap_Key_GetBindingBuf()
void trap_Key_GetBindingBuf (int keynum, char * buf, int buflen)
Definition at line 200 of file ui_syscalls.c.
{
     syscall( UI_KEY_GETBINDINGBUF, keynum, buf, buflen );
 }
Referenced by _UI_Init(), and Controls_GetKeyAssignment().
trap_Key_GetCatcher()
int trap_Key_GetCatcher (void)
Definition at line 224 of file ui_syscalls.c.
{
     return syscall( UI_KEY_GETCATCHER );
 }
Referenced by _UI_KeyEvent(), _UI_Refresh(), _UI_SetActiveMenu(), UI_ForceMenuOff(), UI_IsFullscreen(), UI_Pause(), UI_Refresh(), and UI_RunMenuScript().
trap_Key_GetOverstrikeMode()
qboolean trap_Key_GetOverstrikeMode (void)
Definition at line 212 of file ui_syscalls.c.
{
     return syscall( UI_KEY_GETOVERSTRIKEMODE );
 }
Referenced by _UI_Init(), MField_CharEvent(), MField_Draw(), MField_KeyDownEvent(), PlayerSettings_DrawName(), Rankings_DrawText(), and UI_CDKeyMenu_DrawKey().
trap_Key_IsDown()
qboolean trap_Key_IsDown (int keynum)
Definition at line 208 of file ui_syscalls.c.
{
     return syscall( UI_KEY_ISDOWN, keynum );
 }
Referenced by MField_KeyDownEvent().
trap_Key_KeynumToStringBuf()
void trap_Key_KeynumToStringBuf (int keynum, char * buf, int buflen)
Definition at line 196 of file ui_syscalls.c.
{
     syscall( UI_KEY_KEYNUMTOSTRINGBUF, keynum, buf, buflen );
 }
Referenced by _UI_Init(), and Controls_DrawKeyBinding().
trap_Key_SetBinding()
void trap_Key_SetBinding (int keynum, const char * binding)
Definition at line 204 of file ui_syscalls.c.
{
     syscall( UI_KEY_SETBINDING, keynum, binding );
 }
Referenced by _UI_Init(), Controls_MenuKey(), and Controls_SetConfig().
trap_Key_SetCatcher()
void trap_Key_SetCatcher (int catcher)
Definition at line 228 of file ui_syscalls.c.
{
     syscall( UI_KEY_SETCATCHER, catcher );
 }
Referenced by _UI_KeyEvent(), _UI_SetActiveMenu(), CG_KeyEvent(), CG_MouseEvent(), UI_ForceMenuOff(), UI_MainMenu(), UI_Pause(), UI_PushMenu(), UI_RunMenuScript(), UI_SPLevelMenu_f(), and UI_SPPostgameMenu_f().
trap_Key_SetOverstrikeMode()
void trap_Key_SetOverstrikeMode (qboolean state)
Definition at line 216 of file ui_syscalls.c.
{
     syscall( UI_KEY_SETOVERSTRIKEMODE, state );
 }
Referenced by _UI_Init(), and MField_KeyDownEvent().
trap_LAN_AddServer()
int trap_LAN_AddServer (int source, const char * name, const char * addr)
Definition at line 308 of file ui_syscalls.c.
{
     return syscall( UI_LAN_ADDSERVER, source, name, addr );
 }
Referenced by UI_RunMenuScript().
trap_LAN_ClearPing()
void trap_LAN_ClearPing (int n)
Definition at line 284 of file ui_syscalls.c.
{
     syscall( UI_LAN_CLEARPING, n );
 }
Referenced by ArenaServers_DoRefresh(), and ArenaServers_StartRefresh().
trap_LAN_CompareServers()
int trap_LAN_CompareServers (int source, int sortKey, int sortDir, int s1, int s2)
Definition at line 316 of file ui_syscalls.c.
{
     return syscall( UI_LAN_COMPARESERVERS, source, sortKey, sortDir, s1, s2 );
 }
Referenced by UI_BinaryServerInsertion(), and UI_ServersQsortCompare().
trap_LAN_GetPing()
void trap_LAN_GetPing (int n, char * buf, int buflen, int * pingtime)
Definition at line 288 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETPING, n, buf, buflen, pingtime );
 }
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetPingInfo()
void trap_LAN_GetPingInfo (int n, char * buf, int buflen)
Definition at line 292 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETPINGINFO, n, buf, buflen );
 }
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetPingQueueCount()
int trap_LAN_GetPingQueueCount (void)
Definition at line 264 of file ui_syscalls.c.
{
     return syscall( UI_LAN_GETPINGQUEUECOUNT );
 }
Referenced by ArenaServers_DoRefresh().
trap_LAN_GetServerAddressString()
void trap_LAN_GetServerAddressString (int source, int n, char * buf, int buflen)
Definition at line 252 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETSERVERADDRESSSTRING, source, n, buf, buflen );
 }
Referenced by ArenaServers_DoRefresh(), UI_BuildFindPlayerList(), and UI_RunMenuScript().
trap_LAN_GetServerCount()
int trap_LAN_GetServerCount (int source)
Definition at line 248 of file ui_syscalls.c.
{
     return syscall( UI_LAN_GETSERVERCOUNT, source );
 }
Referenced by ArenaServers_DoRefresh(), UI_BuildServerDisplayList(), UI_DoServerRefresh(), UI_DrawServerRefreshDate(), UI_StartServerRefresh(), and UI_StopServerRefresh().
trap_LAN_GetServerInfo()
void trap_LAN_GetServerInfo (int source, int n, char * buf, int buflen)
Definition at line 256 of file ui_syscalls.c.
{
     syscall( UI_LAN_GETSERVERINFO, source, n, buf, buflen );
 }
Referenced by UI_BuildFindPlayerList(), UI_BuildServerDisplayList(), UI_FeederItemText(), UI_FeederSelection(), and UI_RunMenuScript().
trap_LAN_GetServerPing()
int trap_LAN_GetServerPing (int source, int n)
Definition at line 260 of file ui_syscalls.c.
{
     return syscall( UI_LAN_GETSERVERPING, source, n );
 }
Referenced by UI_BuildServerDisplayList().
trap_LAN_LoadCachedServers()
void trap_LAN_LoadCachedServers (void)
Definition at line 276 of file ui_syscalls.c.
{
     syscall( UI_LAN_LOADCACHEDSERVERS );
 }
Referenced by _UI_Init().
trap_LAN_MarkServerVisible()
void trap_LAN_MarkServerVisible (int source, int n, qboolean visible)
Definition at line 296 of file ui_syscalls.c.
{
     syscall( UI_LAN_MARKSERVERVISIBLE, source, n, visible );
 }
Referenced by UI_BuildServerDisplayList(), and UI_StartServerRefresh().
trap_LAN_RemoveServer()
void trap_LAN_RemoveServer (int source, const char * addr)
Definition at line 312 of file ui_syscalls.c.
{
     syscall( UI_LAN_REMOVESERVER, source, addr );
 }
Referenced by UI_RunMenuScript().
trap_LAN_ResetPings()
void trap_LAN_ResetPings (int n)
Definition at line 280 of file ui_syscalls.c.
{
     syscall( UI_LAN_RESETPINGS, n );
 }
Referenced by UI_StartServerRefresh(), and UI_UpdatePendingPings().
trap_LAN_SaveCachedServers()
void trap_LAN_SaveCachedServers (void)
Definition at line 272 of file ui_syscalls.c.
{
     syscall( UI_LAN_SAVECACHEDSERVERS );
 }
Referenced by _UI_Shutdown().
trap_LAN_ServerIsVisible()
int trap_LAN_ServerIsVisible (int source, int n)
Definition at line 300 of file ui_syscalls.c.
{
     return syscall( UI_LAN_SERVERISVISIBLE, source, n );
 }
Referenced by UI_BuildServerDisplayList().
trap_LAN_ServerStatus()
int trap_LAN_ServerStatus (const char * serverAddress, char * serverStatus, int maxLen)
Definition at line 268 of file ui_syscalls.c.
{
     return syscall( UI_LAN_SERVERSTATUS, serverAddress, serverStatus, maxLen );
 }
Referenced by UI_BuildFindPlayerList(), UI_BuildServerStatus(), and UI_GetServerStatusInfo().
trap_LAN_UpdateVisiblePings()
qboolean trap_LAN_UpdateVisiblePings (int source)
Definition at line 304 of file ui_syscalls.c.
{
     return syscall( UI_LAN_UPDATEVISIBLEPINGS, source );
 }
Referenced by UI_DoServerRefresh().
trap_MemoryRemaining()
int trap_MemoryRemaining (void)
Definition at line 320 of file ui_syscalls.c.
{
     return syscall( UI_MEMORY_REMAINING );
 }
Referenced by CG_LoadDeferredPlayers(), CG_NewClientInfo(), PlayerModel_DrawPlayer(), and PlayerModel_PicEvent().
trap_Milliseconds()
int trap_Milliseconds (void)
Definition at line 54 of file ui_syscalls.c.
{
     return syscall( UI_MILLISECONDS );
 }
Referenced by CG_DrawFPS(), and UI_LoadMenus().
trap_PC_AddGlobalDefine()
int trap_PC_AddGlobalDefine (char * define)
Definition at line 332 of file ui_syscalls.c.
{
     return syscall( UI_PC_ADD_GLOBAL_DEFINE, define );
 }
trap_PC_FreeSource()
int trap_PC_FreeSource (int handle)
Definition at line 340 of file ui_syscalls.c.
{
     return syscall( UI_PC_FREE_SOURCE, handle );
 }
trap_PC_LoadSource()
int trap_PC_LoadSource (const char * filename)
Definition at line 336 of file ui_syscalls.c.
{
     return syscall( UI_PC_LOAD_SOURCE, filename );
 }
trap_PC_ReadToken()
int trap_PC_ReadToken (int handle, pc_token_t * pc_token)
Definition at line 344 of file ui_syscalls.c.
{
     return syscall( UI_PC_READ_TOKEN, handle, pc_token );
 }
trap_PC_SourceFileAndLine()
int trap_PC_SourceFileAndLine (int handle, char * filename, int * line)
Definition at line 348 of file ui_syscalls.c.
{
     return syscall( UI_PC_SOURCE_FILE_AND_LINE, handle, filename, line );
 }
trap_Print()
void trap_Print (const char * string)
Definition at line 43 of file ui_syscalls.c.
{
     syscall( UI_PRINT, string );
 }
Referenced by CG_Printf(), Com_Printf(), G_AddBot(), G_GetBotInfoByNumber(), G_LoadArenas(), G_LoadArenasFromFile(), G_LoadBots(), G_LoadBotsFromFile(), G_Printf(), GetMenuBuffer(), Svcmd_AddBot_f(), Svcmd_BotList_f(), UI_GetArenaInfoByNumber(), UI_GetBotInfoByNumber(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadBots(), UI_LoadBotsFromFile(), UI_LogAwardData(), UI_Mods_LoadMods(), UI_SPUnlock_f(), and UI_SPUnlockMedals_f().
trap_R_AddLightToScene()
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
Definition at line 160 of file ui_syscalls.c.
{
     syscall( UI_R_ADDLIGHTTOSCENE, org, PASSFLOAT(intensity), PASSFLOAT(r), PASSFLOAT(g), PASSFLOAT(b) );
 }
Referenced by CG_AddExplosion(), CG_AddPlayerWeapon(), CG_AddSpriteExplosion(), CG_EntityEffects(), CG_Missile(), CG_PlayerPowerups(), and UI_DrawPlayer().
trap_R_AddPolyToScene()
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
Definition at line 156 of file ui_syscalls.c.
{
     syscall( UI_R_ADDPOLYTOSCENE, hShader, numVerts, verts );
 }
Referenced by CG_AddMarks(), CG_AddParticleToScene(), CG_ImpactMark(), CG_PlayerSplash(), and CG_Tracer().
trap_R_AddRefEntityToScene()
void trap_R_AddRefEntityToScene (const refEntity_t * re)
Definition at line 152 of file ui_syscalls.c.
{
     syscall( UI_R_ADDREFENTITYTOSCENE, re );
 }
Referenced by _UI_Init(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddMoveScaleFade(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddScorePlum(), CG_AddSpriteExplosion(), CG_AddTestModel(), CG_AddWeaponWithPowerups(), CG_Beam(), CG_DamageBlendBlob(), CG_Draw3DModel(), CG_DrawCrosshair3D(), CG_General(), CG_Grapple(), CG_GrappleTrail(), CG_Item(), CG_LightningBolt(), CG_Missile(), CG_Mover(), CG_Player(), CG_PlayerFlag(), CG_PlayerFloatSprite(), CG_Portal(), CG_TeamBase(), CG_TrailItem(), Main_MenuDraw(), UI_DrawPlayer(), and UI_PlayerFloatSprite().
trap_R_ClearScene()
void trap_R_ClearScene (void)
Definition at line 148 of file ui_syscalls.c.
{
     syscall( UI_R_CLEARSCENE );
 }
Referenced by _UI_Init(), CG_Draw3DModel(), CG_DrawActiveFrame(), CG_RegisterGraphics(), Main_MenuDraw(), and UI_DrawPlayer().
trap_R_DrawStretchPic()
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Definition at line 172 of file ui_syscalls.c.
{
     syscall( UI_R_DRAWSTRETCHPIC, PASSFLOAT(x), PASSFLOAT(y), PASSFLOAT(w), PASSFLOAT(h), PASSFLOAT(s1), PASSFLOAT(t1), PASSFLOAT(s2), PASSFLOAT(t2), hShader );
 }
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), _UI_Init(), CG_DrawChar(), CG_DrawCrosshair(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawPic(), CG_DrawSides(), CG_DrawTopBottom(), CG_FillRect(), CG_TileClearBox(), Text_PaintChar(), UI_DrawBannerString2(), UI_DrawHandlePic(), UI_DrawNamedPic(), UI_DrawProportionalString2(), UI_DrawRect(), UI_DrawSides(), UI_DrawString2(), UI_DrawTopBottom(), and UI_FillRect().
trap_R_ModelBounds()
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
Definition at line 176 of file ui_syscalls.c.
{
     syscall( UI_R_MODELBOUNDS, model, mins, maxs );
 }
Referenced by _UI_Init(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawSelectedPlayerHead(), CG_RegisterGraphics(), and CG_RegisterWeapon().
trap_R_RegisterFont()
void trap_R_RegisterFont (const char * fontName, int pointSize, fontInfo_t * font)
Definition at line 140 of file ui_syscalls.c.
{
     syscall( UI_R_REGISTERFONT, fontName, pointSize, font );
 }
Referenced by _UI_Init(), and Asset_Parse().
trap_R_RegisterModel()
qhandle_t trap_R_RegisterModel (const char * name)
Definition at line 132 of file ui_syscalls.c.
{
     return syscall( UI_R_REGISTERMODEL, name );
 }
Referenced by _UI_Init(), CG_AddTestModel(), CG_ConfigStringModified(), CG_RegisterClientModelname(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RegisterWeapon(), CG_TestModel_f(), Controls_InitWeapons(), MainMenu_Cache(), UI_PlayerInfo_SetWeapon(), and UI_RegisterClientModelname().
trap_R_RegisterShaderNoMip()
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
Definition at line 144 of file ui_syscalls.c.
{
     return syscall( UI_R_REGISTERSHADERNOMIP, name );
 }
Referenced by _UI_Init(), ArenaServers_Cache(), Asset_Parse(), AssetCache(), Bitmap_Draw(), CG_DrawInformation(), CG_Init(), CG_LoadingClient(), CG_LoadingItem(), CG_RegisterClientModelname(), CG_RegisterGraphics(), ConfirmMenu_Cache(), Controls_Cache(), Demos_Cache(), DriverInfo_Cache(), GraphicsOptions_Cache(), InGame_Cache(), Login_Cache(), MapList_Parse(), Menu_Cache(), PlayerIcon(), PlayerIconHandle(), PlayerModel_Cache(), PlayerSettings_Cache(), Preferences_Cache(), Rankings_Cache(), RankStatus_Cache(), Reset_Cache(), ServerInfo_Cache(), ServerOptions_Cache(), ServerPlayerIcon(), Signup_Cache(), SpecifyLeague_Cache(), SpecifyServer_Cache(), StartServer_Cache(), StartServer_LevelshotDraw(), SystemConfig_Cache(), Team_Parse(), TeamMain_Cache(), UI_AddBots_Cache(), UI_BotSelectMenu_Cache(), UI_BuildQ3Model_List(), UI_CDKeyMenu_Cache(), UI_CinematicsMenu_Cache(), UI_DisplayOptionsMenu_Cache(), UI_DrawClanLogo(), UI_DrawMapPreview(), UI_DrawNamedPic(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayer(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawTierMap(), UI_FeederItemImage(), UI_FeederSelection(), UI_LoadConfig_Cache(), UI_ModsMenu_Cache(), UI_NetworkOptionsMenu_Cache(), UI_RemoveBots_Cache(), UI_SaveConfigMenu_Cache(), UI_SetupMenu_Cache(), UI_SoundOptionsMenu_Cache(), UI_SPLevelMenu_Cache(), UI_SPLevelMenu_SetMenuArena(), UI_SPPostgameMenu_Cache(), UI_SPSkillMenu_Cache(), and UI_TeamOrdersMenu_Cache().
trap_R_RegisterSkin()
qhandle_t trap_R_RegisterSkin (const char * name)
Definition at line 136 of file ui_syscalls.c.
{
     return syscall( UI_R_REGISTERSKIN, name );
 }
Referenced by CG_RegisterClientSkin(), CG_RegisterGraphics(), and UI_RegisterClientSkin().
trap_R_RemapShader()
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
Definition at line 394 of file ui_syscalls.c.
{
     syscall( UI_R_REMAP_SHADER, oldShader, newShader, timeOffset );
 }
Referenced by CG_ServerCommand(), CG_ShaderStateChanged(), and UI_ConsoleCommand().
trap_R_RenderScene()
void trap_R_RenderScene (const refdef_t * fd)
Definition at line 164 of file ui_syscalls.c.
{
     syscall( UI_R_RENDERSCENE, fd );
 }
Referenced by _UI_Init(), CG_Draw3DModel(), CG_DrawActive(), Main_MenuDraw(), and UI_DrawPlayer().
trap_R_SetColor()
void trap_R_SetColor (const float * rgba)
Definition at line 168 of file ui_syscalls.c.
{
     syscall( UI_R_SETCOLOR, rgba );
 }
Referenced by _UI_DrawRect(), Bitmap_Draw(), CG_DrawAreaPowerUp(), CG_DrawBlueFlagStatus(), CG_DrawCenterString(), CG_DrawCrosshair(), CG_DrawCrosshairNames(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawPickupItem(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerScore(), CG_DrawPowerups(), CG_DrawRect(), CG_DrawRedFlagStatus(), CG_DrawReward(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHealth(), CG_DrawStatusBar(), CG_DrawStringExt(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawWeaponSelect(), CG_FillRect(), CG_OneFlagStatus(), CG_Text_Paint_Limit(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), UI_DrawBannerString2(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawCrosshair(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawProportionalString2(), UI_DrawRect(), UI_DrawString2(), UI_FillRect(), UI_SetColor(), and UI_SPLevelMenu_MenuDraw().
trap_RealTime()
int trap_RealTime (qtime_t * qtime)
Definition at line 360 of file ui_syscalls.c.
{
     return syscall( UI_REAL_TIME, qtime );
 }
Referenced by UI_StartServerRefresh().
trap_S_RegisterSound()
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
Definition at line 192 of file ui_syscalls.c.
{
     return syscall( UI_S_REGISTERSOUND, sample, compressed );
 }
Referenced by _UI_Init(), Asset_Parse(), AssetCache(), CG_ConfigStringModified(), CG_CustomSound(), CG_EntityEvent(), CG_LoadClientInfo(), CG_LoadingClient(), CG_MachinegunSpinAngle(), CG_RegisterItemSounds(), CG_RegisterSounds(), CG_RegisterWeapon(), Menu_Cache(), PlayerModel_BuildList(), UI_SPLevelMenu_Cache(), UI_SPPostgameMenu_Cache(), UI_SPPostgameMenu_DrawAwardsPresentation(), UI_SPPostgameMenu_f(), and UI_SPSkillMenu_Cache().
trap_S_StartBackgroundTrack()
void trap_S_StartBackgroundTrack (const char * intro, const char * loop)
Definition at line 356 of file ui_syscalls.c.
{
     syscall( UI_S_STARTBACKGROUNDTRACK, intro, loop );
 }
Referenced by _UI_Init(), and CG_StartMusic().
trap_S_StartLocalSound()
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
Definition at line 188 of file ui_syscalls.c.
{
     syscall( UI_S_STARTLOCALSOUND, sfx, channelNum );
 }
Referenced by _UI_Init(), CG_CheckAmmo(), CG_CheckLocalSounds(), CG_ConfigStringModified(), CG_DrawReward(), CG_DrawTeamVote(), CG_DrawVote(), CG_DrawWarmup(), CG_EntityEvent(), CG_MapRestart(), CG_ParseWarmup(), CG_PlayBufferedSounds(), CG_ServerCommand(), UI_DrawPlayer(), UI_KeyEvent(), UI_MouseEvent(), UI_OwnerDrawVisible(), UI_PopMenu(), UI_Refresh(), UI_SPLevelMenu_AwardEvent(), UI_SPPostgameMenu_DrawAwardsPresentation(), UI_SPPostgameMenu_MenuDraw(), UI_SPSkillMenu_BackEvent(), UI_SPSkillMenu_Init(), UI_SPSkillMenu_Key(), and UI_SPSkillMenu_SkillEvent().
trap_S_StopBackgroundTrack()
void trap_S_StopBackgroundTrack (void)
Definition at line 352 of file ui_syscalls.c.
{
     syscall( UI_S_STOPBACKGROUNDTRACK );
 }
Referenced by _UI_Init().
trap_SetCDKey()
void trap_SetCDKey (char * buf)
Definition at line 328 of file ui_syscalls.c.
{
     syscall( UI_SET_CDKEY, buf );
 }
Referenced by UI_CDKeyMenu_Event(), and UI_RunMenuScript().
trap_SetPbClStatus()
void trap_SetPbClStatus (int status)
Definition at line 402 of file ui_syscalls.c.
{
     syscall( UI_SET_PBCLSTATUS, status );
 }
Referenced by Punkbuster_ConfirmDisable(), Punkbuster_ConfirmEnable(), and UI_RunMenuScript().
trap_UpdateScreen()
void trap_UpdateScreen (void)
Definition at line 180 of file ui_syscalls.c.
{
     syscall( UI_UPDATESCREEN );
 }
Referenced by CG_LoadingString(), and UI_UpdateScreen().
trap_VerifyCDKey()
qboolean trap_VerifyCDKey (const char * key, const char * chksum)
Definition at line 398 of file ui_syscalls.c.
{
     return syscall( UI_VERIFY_CDKEY, key, chksum);
 }
Referenced by UI_CDKeyMenu_Init(), UI_MainMenu(), and UI_RunMenuScript().