ioquake3 doxygen: C:/entry/dev/ioq3/code/renderergl2/tr_shade.c File Reference
tr_shade.c File Reference
#include "tr_local.h"
Functions
void R_DrawElements (int numIndexes, int firstIndex)
static void R_BindAnimatedImageToTMU (textureBundle_t *bundle, int tmu)
static void DrawTris (shaderCommands_t *input)
static void DrawNormals (shaderCommands_t *input)
void RB_BeginSurface (shader_t *shader, int fogNum, int cubemapIndex)
float EvalWaveForm (const waveForm_t *wf)
float EvalWaveFormClamped (const waveForm_t *wf)
static void ComputeTexMods (shaderStage_t *pStage, int bundleNum, float *outMatrix, float *outOffTurb)
static void ComputeDeformValues (int *deformGen, vec5_t deformParams)
static void ProjectDlightTexture (void)
static void ComputeShaderColors (shaderStage_t *pStage, vec4_t baseColor, vec4_t vertColor, int blend)
static void ComputeFogValues (vec4_t fogDistanceVector, vec4_t fogDepthVector, float *eyeT)
static void ComputeFogColorMask (shaderStage_t *pStage, vec4_t fogColorMask)
static void ForwardDlight (void)
static void ProjectPshadowVBOGLSL (void)
static void RB_FogPass (void)
static unsigned int RB_CalcShaderVertexAttribs (shaderCommands_t *input)
static void RB_IterateStagesGeneric (shaderCommands_t *input)
static void RB_RenderShadowmap (shaderCommands_t *input)
void RB_StageIteratorGeneric (void)
void RB_EndSurface (void)
Variables
shaderCommands_t tess
Function Documentation
ComputeDeformValues()
static void ComputeDeformValues (int * deformGen, vec5_t deformParams) static
Definition at line 281 of file tr_shade.c.
 {
     // u_DeformGen
     *deformGen = DGEN_NONE;
     if(!ShaderRequiresCPUDeforms(tess.shader))
     {
         deformStage_t  *ds;
         // only support the first one
         ds = &tess.shader->deforms[0];
         switch (ds->deformation)
         {
             case DEFORM_WAVE:
                 *deformGen = ds->deformationWave.func;
                 deformParams[0] = ds->deformationWave.base;
                 deformParams[1] = ds->deformationWave.amplitude;
                 deformParams[2] = ds->deformationWave.phase;
                 deformParams[3] = ds->deformationWave.frequency;
                 deformParams[4] = ds->deformationSpread;
                 break;
             case DEFORM_BULGE:
                 *deformGen = DGEN_BULGE;
                 deformParams[0] = 0;
                 deformParams[1] = ds->bulgeHeight; // amplitude
                 deformParams[2] = ds->bulgeWidth;  // phase
                 deformParams[3] = ds->bulgeSpeed;  // frequency
                 deformParams[4] = 0;
                 break;
             default:
                 break;
         }
     }
 }
References waveForm_t::amplitude, waveForm_t::base, deformStage_t::bulgeHeight, deformStage_t::bulgeSpeed, deformStage_t::bulgeWidth, DEFORM_BULGE, DEFORM_WAVE, deformStage_t::deformation, deformStage_t::deformationSpread, deformStage_t::deformationWave, shader_s::deforms, DGEN_BULGE, DGEN_NONE, waveForm_t::frequency, waveForm_t::func, waveForm_t::phase, shaderCommands_s::shader, ShaderRequiresCPUDeforms(), and tess.
Referenced by ForwardDlight(), ProjectDlightTexture(), ProjectPshadowVBOGLSL(), RB_FogPass(), RB_IterateStagesGeneric(), and RB_RenderShadowmap().
ComputeFogColorMask()
static void ComputeFogColorMask (shaderStage_t * pStage, vec4_t fogColorMask) static
Definition at line 609 of file tr_shade.c.
 {
     switch(pStage->adjustColorsForFog)
     {
         case ACFF_MODULATE_RGB:
             fogColorMask[0] =
             fogColorMask[1] =
             fogColorMask[2] = 1.0f;
             fogColorMask[3] = 0.0f;
             break;
         case ACFF_MODULATE_ALPHA:
             fogColorMask[0] =
             fogColorMask[1] =
             fogColorMask[2] = 0.0f;
             fogColorMask[3] = 1.0f;
             break;
         case ACFF_MODULATE_RGBA:
             fogColorMask[0] =
             fogColorMask[1] =
             fogColorMask[2] =
             fogColorMask[3] = 1.0f;
             break;
         default:
             fogColorMask[0] =
             fogColorMask[1] =
             fogColorMask[2] =
             fogColorMask[3] = 0.0f;
             break;
     }
 }
References ACFF_MODULATE_ALPHA, ACFF_MODULATE_RGB, ACFF_MODULATE_RGBA, and shaderStage_t::adjustColorsForFog.
Referenced by ForwardDlight(), and RB_IterateStagesGeneric().
ComputeFogValues()
static void ComputeFogValues (vec4_t fogDistanceVector, vec4_t fogDepthVector, float * eyeT) static
Definition at line 572 of file tr_shade.c.
 {
     // from RB_CalcFogTexCoords()
     fog_t  *fog;
     vec3_t  local;
     if (!tess.fogNum)
         return;
     fog = tr.world->fogs + tess.fogNum;
     VectorSubtract( backEnd.or.origin, backEnd.viewParms.or.origin, local );
     fogDistanceVector[0] = -backEnd.or.modelMatrix[2];
     fogDistanceVector[1] = -backEnd.or.modelMatrix[6];
     fogDistanceVector[2] = -backEnd.or.modelMatrix[10];
     fogDistanceVector[3] = DotProduct( local, backEnd.viewParms.or.axis[0] );
     // scale the fog vectors based on the fog's thickness
     VectorScale4(fogDistanceVector, fog->tcScale, fogDistanceVector);
     // rotate the gradient vector for this orientation
     if ( fog->hasSurface ) {
         fogDepthVector[0] = fog->surface[0] * backEnd.or.axis[0][0] +
             fog->surface[1] * backEnd.or.axis[0][1] + fog->surface[2] * backEnd.or.axis[0][2];
         fogDepthVector[1] = fog->surface[0] * backEnd.or.axis[1][0] +
             fog->surface[1] * backEnd.or.axis[1][1] + fog->surface[2] * backEnd.or.axis[1][2];
         fogDepthVector[2] = fog->surface[0] * backEnd.or.axis[2][0] +
             fog->surface[1] * backEnd.or.axis[2][1] + fog->surface[2] * backEnd.or.axis[2][2];
         fogDepthVector[3] = -fog->surface[3] + DotProduct( backEnd.or.origin, fog->surface );
         *eyeT = DotProduct( backEnd.or.viewOrigin, fogDepthVector ) + fogDepthVector[3];
     } else {
         *eyeT = 1;  // non-surface fog always has eye inside
     }
 }
References orientationr_t::axis, backEnd, DotProduct, shaderCommands_s::fogNum, world_t::fogs, fog_t::hasSurface, local, orientationr_t::modelMatrix, viewParms_t::or, backEndState_t::or, orientationr_t::origin, fog_t::surface, fog_t::tcScale, tess, tr, VectorScale4, VectorSubtract, orientationr_t::viewOrigin, backEndState_t::viewParms, and trGlobals_t::world.
Referenced by ForwardDlight(), RB_FogPass(), and RB_IterateStagesGeneric().
ComputeShaderColors()
static void ComputeShaderColors (shaderStage_t * pStage, vec4_t baseColor, vec4_t vertColor, int blend) static
Definition at line 400 of file tr_shade.c.
 {
     qboolean isBlend = ((blend & GLS_SRCBLEND_BITS) == GLS_SRCBLEND_DST_COLOR)
         || ((blend & GLS_SRCBLEND_BITS) == GLS_SRCBLEND_ONE_MINUS_DST_COLOR)
         || ((blend & GLS_DSTBLEND_BITS) == GLS_DSTBLEND_SRC_COLOR)
         || ((blend & GLS_DSTBLEND_BITS) == GLS_DSTBLEND_ONE_MINUS_SRC_COLOR);
     qboolean is2DDraw = backEnd.currentEntity == &backEnd.entity2D;
     float overbright = (isBlend || is2DDraw) ? 1.0f : (float)(1 << tr.overbrightBits);
     fog_t *fog;
     baseColor[0] =
     baseColor[1] =
     baseColor[2] =
     baseColor[3] = 1.0f;
     vertColor[0] =
     vertColor[1] =
     vertColor[2] =
     vertColor[3] = 0.0f;
     //
     // rgbGen
     //
     switch ( pStage->rgbGen )
     {
         case CGEN_EXACT_VERTEX:
         case CGEN_EXACT_VERTEX_LIT:
             baseColor[0] =
             baseColor[1] =
             baseColor[2] =
             baseColor[3] = 0.0f;
             vertColor[0] =
             vertColor[1] =
             vertColor[2] = overbright;
             vertColor[3] = 1.0f;
             break;
         case CGEN_CONST:
             baseColor[0] = pStage->constantColor[0] / 255.0f;
             baseColor[1] = pStage->constantColor[1] / 255.0f;
             baseColor[2] = pStage->constantColor[2] / 255.0f;
             baseColor[3] = pStage->constantColor[3] / 255.0f;
             break;
         case CGEN_VERTEX:
         case CGEN_VERTEX_LIT:
             baseColor[0] =
             baseColor[1] =
             baseColor[2] =
             baseColor[3] = 0.0f;
             vertColor[0] =
             vertColor[1] =
             vertColor[2] =
             vertColor[3] = 1.0f;
             break;
         case CGEN_ONE_MINUS_VERTEX:
             baseColor[0] =
             baseColor[1] =
             baseColor[2] = 1.0f;
             vertColor[0] =
             vertColor[1] =
             vertColor[2] = -1.0f;
             break;
         case CGEN_FOG:
             fog = tr.world->fogs + tess.fogNum;
             baseColor[0] = ((unsigned char *)(&fog->colorInt))[0] / 255.0f;
             baseColor[1] = ((unsigned char *)(&fog->colorInt))[1] / 255.0f;
             baseColor[2] = ((unsigned char *)(&fog->colorInt))[2] / 255.0f;
             baseColor[3] = ((unsigned char *)(&fog->colorInt))[3] / 255.0f;
             break;
         case CGEN_WAVEFORM:
             baseColor[0] =
             baseColor[1] =
             baseColor[2] = RB_CalcWaveColorSingle( &pStage->rgbWave );
             break;
         case CGEN_ENTITY:
             if (backEnd.currentEntity)
             {
                 baseColor[0] = ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[0] / 255.0f;
                 baseColor[1] = ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[1] / 255.0f;
                 baseColor[2] = ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[2] / 255.0f;
                 baseColor[3] = ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[3] / 255.0f;
             }
             break;
         case CGEN_ONE_MINUS_ENTITY:
             if (backEnd.currentEntity)
             {
                 baseColor[0] = 1.0f - ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[0] / 255.0f;
                 baseColor[1] = 1.0f - ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[1] / 255.0f;
                 baseColor[2] = 1.0f - ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[2] / 255.0f;
                 baseColor[3] = 1.0f - ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[3] / 255.0f;
             }
             break;
         case CGEN_IDENTITY:
         case CGEN_LIGHTING_DIFFUSE:
             baseColor[0] =
             baseColor[1] =
             baseColor[2] = overbright;
             break;
         case CGEN_IDENTITY_LIGHTING:
         case CGEN_BAD:
             break;
     }
     //
     // alphaGen
     //
     switch ( pStage->alphaGen )
     {
         case AGEN_SKIP:
             break;
         case AGEN_CONST:
             baseColor[3] = pStage->constantColor[3] / 255.0f;
             vertColor[3] = 0.0f;
             break;
         case AGEN_WAVEFORM:
             baseColor[3] = RB_CalcWaveAlphaSingle( &pStage->alphaWave );
             vertColor[3] = 0.0f;
             break;
         case AGEN_ENTITY:
             if (backEnd.currentEntity)
             {
                 baseColor[3] = ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[3] / 255.0f;
             }
             vertColor[3] = 0.0f;
             break;
         case AGEN_ONE_MINUS_ENTITY:
             if (backEnd.currentEntity)
             {
                 baseColor[3] = 1.0f - ((unsigned char *)backEnd.currentEntity->e.shaderRGBA)[3] / 255.0f;
             }
             vertColor[3] = 0.0f;
             break;
         case AGEN_VERTEX:
             baseColor[3] = 0.0f;
             vertColor[3] = 1.0f;
             break;
         case AGEN_ONE_MINUS_VERTEX:
             baseColor[3] = 1.0f;
             vertColor[3] = -1.0f;
             break;
         case AGEN_IDENTITY:
         case AGEN_LIGHTING_SPECULAR:
         case AGEN_PORTAL:
             // Done entirely in vertex program
             baseColor[3] = 1.0f;
             vertColor[3] = 0.0f;
             break;
     }
     // FIXME: find some way to implement this.
 #if 0
     // if in greyscale rendering mode turn all color values into greyscale.
     if(r_greyscale->integer)
     {
         int scale;
         for(i = 0; i < tess.numVertexes; i++)
         {
             scale = (tess.svars.colors[i][0] + tess.svars.colors[i][1] + tess.svars.colors[i][2]) / 3;
             tess.svars.colors[i][0] = tess.svars.colors[i][1] = tess.svars.colors[i][2] = scale;
         }
     }
 #endif
 }
References AGEN_CONST, AGEN_ENTITY, AGEN_IDENTITY, AGEN_LIGHTING_SPECULAR, AGEN_ONE_MINUS_ENTITY, AGEN_ONE_MINUS_VERTEX, AGEN_PORTAL, AGEN_SKIP, AGEN_VERTEX, AGEN_WAVEFORM, shaderStage_t::alphaGen, shaderStage_t::alphaWave, backEnd, CGEN_BAD, CGEN_CONST, CGEN_ENTITY, CGEN_EXACT_VERTEX, CGEN_EXACT_VERTEX_LIT, CGEN_FOG, CGEN_IDENTITY, CGEN_IDENTITY_LIGHTING, CGEN_LIGHTING_DIFFUSE, CGEN_ONE_MINUS_ENTITY, CGEN_ONE_MINUS_VERTEX, CGEN_VERTEX, CGEN_VERTEX_LIT, CGEN_WAVEFORM, fog_t::colorInt, shaderStage_t::constantColor, backEndState_t::currentEntity, trRefEntity_t::e, backEndState_t::entity2D, shaderCommands_s::fogNum, world_t::fogs, GLS_DSTBLEND_BITS, GLS_DSTBLEND_ONE_MINUS_SRC_COLOR, GLS_DSTBLEND_SRC_COLOR, GLS_SRCBLEND_BITS, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE_MINUS_DST_COLOR, cvar_s::integer, shaderCommands_s::numVertexes, trGlobals_t::overbrightBits, r_greyscale, RB_CalcWaveAlphaSingle(), RB_CalcWaveColorSingle(), shaderStage_t::rgbGen, shaderStage_t::rgbWave, refEntity_t::shaderRGBA, tess, tr, and trGlobals_t::world.
Referenced by ForwardDlight(), and RB_IterateStagesGeneric().
ComputeTexMods()
static void ComputeTexMods (shaderStage_t * pStage, int bundleNum, float * outMatrix, float * outOffTurb) static
Definition at line 184 of file tr_shade.c.
 {
     int tm;
     float matrix[6], currentmatrix[6];
     textureBundle_t *bundle = &pStage->bundle[bundleNum];
     matrix[0] = 1.0f; matrix[2] = 0.0f; matrix[4] = 0.0f;
     matrix[1] = 0.0f; matrix[3] = 1.0f; matrix[5] = 0.0f;
     currentmatrix[0] = 1.0f; currentmatrix[2] = 0.0f; currentmatrix[4] = 0.0f;
     currentmatrix[1] = 0.0f; currentmatrix[3] = 1.0f; currentmatrix[5] = 0.0f;
     outMatrix[0] = 1.0f; outMatrix[2] = 0.0f;
     outMatrix[1] = 0.0f; outMatrix[3] = 1.0f;
     outOffTurb[0] = 0.0f; outOffTurb[1] = 0.0f; outOffTurb[2] = 0.0f; outOffTurb[3] = 0.0f;
     for ( tm = 0; tm < bundle->numTexMods ; tm++ ) {
         switch ( bundle->texMods[tm].type )
         {
         case TMOD_NONE:
             tm = TR_MAX_TEXMODS;        // break out of for loop
             break;
         case TMOD_TURBULENT:
             RB_CalcTurbulentFactors(&bundle->texMods[tm].wave, &outOffTurb[2], &outOffTurb[3]);
             break;
         case TMOD_ENTITY_TRANSLATE:
             RB_CalcScrollTexMatrix( backEnd.currentEntity->e.shaderTexCoord, matrix );
             break;
         case TMOD_SCROLL:
             RB_CalcScrollTexMatrix( bundle->texMods[tm].scroll,
                                      matrix );
             break;
         case TMOD_SCALE:
             RB_CalcScaleTexMatrix( bundle->texMods[tm].scale,
                                   matrix );
             break;
         case TMOD_STRETCH:
             RB_CalcStretchTexMatrix( &bundle->texMods[tm].wave,
                                    matrix );
             break;
         case TMOD_TRANSFORM:
             RB_CalcTransformTexMatrix( &bundle->texMods[tm],
                                      matrix );
             break;
         case TMOD_ROTATE:
             RB_CalcRotateTexMatrix( bundle->texMods[tm].rotateSpeed,
                                     matrix );
             break;
         default:
             ri.Error( ERR_DROP, "ERROR: unknown texmod '%d' in shader '%s'", bundle->texMods[tm].type, tess.shader->name );
             break;
         }
         switch ( bundle->texMods[tm].type )
         {
         case TMOD_NONE:
         case TMOD_TURBULENT:
         default:
             break;
         case TMOD_ENTITY_TRANSLATE:
         case TMOD_SCROLL:
         case TMOD_SCALE:
         case TMOD_STRETCH:
         case TMOD_TRANSFORM:
         case TMOD_ROTATE:
             outMatrix[0] = matrix[0] * currentmatrix[0] + matrix[2] * currentmatrix[1];
             outMatrix[1] = matrix[1] * currentmatrix[0] + matrix[3] * currentmatrix[1];
             outMatrix[2] = matrix[0] * currentmatrix[2] + matrix[2] * currentmatrix[3];
             outMatrix[3] = matrix[1] * currentmatrix[2] + matrix[3] * currentmatrix[3];
             outOffTurb[0] = matrix[0] * currentmatrix[4] + matrix[2] * currentmatrix[5] + matrix[4];
             outOffTurb[1] = matrix[1] * currentmatrix[4] + matrix[3] * currentmatrix[5] + matrix[5];
             currentmatrix[0] = outMatrix[0];
             currentmatrix[1] = outMatrix[1];
             currentmatrix[2] = outMatrix[2];
             currentmatrix[3] = outMatrix[3];
             currentmatrix[4] = outOffTurb[0];
             currentmatrix[5] = outOffTurb[1];
             break;
         }
     }
 }
References backEnd, shaderStage_t::bundle, backEndState_t::currentEntity, trRefEntity_t::e, ERR_DROP, shader_s::name, textureBundle_t::numTexMods, RB_CalcRotateTexMatrix(), RB_CalcScaleTexMatrix(), RB_CalcScrollTexMatrix(), RB_CalcStretchTexMatrix(), RB_CalcTransformTexMatrix(), RB_CalcTurbulentFactors(), ri, texModInfo_t::rotateSpeed, texModInfo_t::scale, texModInfo_t::scroll, shaderCommands_s::shader, refEntity_t::shaderTexCoord, tess, textureBundle_t::texMods, TMOD_ENTITY_TRANSLATE, TMOD_NONE, TMOD_ROTATE, TMOD_SCALE, TMOD_SCROLL, TMOD_STRETCH, TMOD_TRANSFORM, TMOD_TURBULENT, TR_MAX_TEXMODS, texModInfo_t::type, and texModInfo_t::wave.
Referenced by ForwardDlight(), and RB_IterateStagesGeneric().
DrawNormals()
static void DrawNormals (shaderCommands_t * input) static
Definition at line 136 of file tr_shade.c.
{
     //FIXME: implement this
 }
Referenced by RB_EndSurface().
DrawTris()
static void DrawTris (shaderCommands_t * input) static
Definition at line 105 of file tr_shade.c.
{
     GL_BindToTMU( tr.whiteImage, TB_COLORMAP );
     GL_State( GLS_POLYMODE_LINE | GLS_DEPTHMASK_TRUE );
     qglDepthRange( 0, 0 );
     {
         shaderProgram_t *sp = &tr.textureColorShader;
         vec4_t color;
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         VectorSet4(color, 1, 1, 1, 1);
         GLSL_SetUniformVec4(sp, UNIFORM_COLOR, color);
         GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 0);
         R_DrawElements(input->numIndexes, input->firstIndex);
     }
     qglDepthRange( 0, 1 );
 }
References shaderCommands_s::firstIndex, GL_BindToTMU(), GL_State(), GLS_DEPTHMASK_TRUE, GLS_POLYMODE_LINE, GLSL_BindProgram(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformVec4(), glState, glstate_t::modelviewProjection, shaderCommands_s::numIndexes, R_DrawElements(), TB_COLORMAP, trGlobals_t::textureColorShader, tr, UNIFORM_ALPHATEST, UNIFORM_COLOR, UNIFORM_MODELVIEWPROJECTIONMATRIX, VectorSet4, and trGlobals_t::whiteImage.
Referenced by RB_EndSurface().
EvalWaveForm()
float EvalWaveForm (const waveForm_t * wf)
EvalWaveFormClamped()
float EvalWaveFormClamped (const waveForm_t * wf)
ForwardDlight()
static void ForwardDlight (void) static
Definition at line 641 of file tr_shade.c.
{
     int     l;
     //vec3_t    origin;
     //float scale;
     float   radius;
     int deformGen;
     vec5_t deformParams;
     vec4_t fogDistanceVector, fogDepthVector = {0, 0, 0, 0};
     float eyeT = 0;
     shaderCommands_t *input = &tess;
     shaderStage_t *pStage = tess.xstages[0];
     if ( !backEnd.refdef.num_dlights ) {
         return;
     }
     ComputeDeformValues(&deformGen, deformParams);
     ComputeFogValues(fogDistanceVector, fogDepthVector, &eyeT);
     for ( l = 0 ; l < backEnd.refdef.num_dlights ; l++ ) {
         dlight_t    *dl;
         shaderProgram_t *sp;
         vec4_t vector;
         vec4_t texMatrix;
         vec4_t texOffTurb;
         if ( !( tess.dlightBits & ( 1 << l ) ) ) {
             continue;   // this surface definitely doesn't have any of this light
         }
         dl = &backEnd.refdef.dlights[l];
         //VectorCopy( dl->transformed, origin );
         radius = dl->radius;
         //scale = 1.0f / radius;
         //if (pStage->glslShaderGroup == tr.lightallShader)
         {
             int index = pStage->glslShaderIndex;
             index &= ~LIGHTDEF_LIGHTTYPE_MASK;
             index |= LIGHTDEF_USE_LIGHT_VECTOR;
             sp = &tr.lightallShader[index];
         }
         backEnd.pc.c_lightallDraws++;
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         GLSL_SetUniformVec3(sp, UNIFORM_VIEWORIGIN, backEnd.viewParms.or.origin);
         GLSL_SetUniformVec3(sp, UNIFORM_LOCALVIEWORIGIN, backEnd.or.viewOrigin);
         GLSL_SetUniformFloat(sp, UNIFORM_VERTEXLERP, glState.vertexAttribsInterpolation);
         GLSL_SetUniformInt(sp, UNIFORM_DEFORMGEN, deformGen);
         if (deformGen != DGEN_NONE)
         {
             GLSL_SetUniformFloat5(sp, UNIFORM_DEFORMPARAMS, deformParams);
             GLSL_SetUniformFloat(sp, UNIFORM_TIME, tess.shaderTime);
         }
         if ( input->fogNum ) {
             vec4_t fogColorMask;
             GLSL_SetUniformVec4(sp, UNIFORM_FOGDISTANCE, fogDistanceVector);
             GLSL_SetUniformVec4(sp, UNIFORM_FOGDEPTH, fogDepthVector);
             GLSL_SetUniformFloat(sp, UNIFORM_FOGEYET, eyeT);
             ComputeFogColorMask(pStage, fogColorMask);
             GLSL_SetUniformVec4(sp, UNIFORM_FOGCOLORMASK, fogColorMask);
         }
         {
             vec4_t baseColor;
             vec4_t vertColor;
             ComputeShaderColors(pStage, baseColor, vertColor, GLS_SRCBLEND_ONE | GLS_DSTBLEND_ONE);
             GLSL_SetUniformVec4(sp, UNIFORM_BASECOLOR, baseColor);
             GLSL_SetUniformVec4(sp, UNIFORM_VERTCOLOR, vertColor);
         }
         if (pStage->alphaGen == AGEN_PORTAL)
         {
             GLSL_SetUniformFloat(sp, UNIFORM_PORTALRANGE, tess.shader->portalRange);
         }
         GLSL_SetUniformInt(sp, UNIFORM_COLORGEN, pStage->rgbGen);
         GLSL_SetUniformInt(sp, UNIFORM_ALPHAGEN, pStage->alphaGen);
         GLSL_SetUniformVec3(sp, UNIFORM_DIRECTEDLIGHT, dl->color);
         VectorSet(vector, 0, 0, 0);
         GLSL_SetUniformVec3(sp, UNIFORM_AMBIENTLIGHT, vector);
         VectorCopy(dl->origin, vector);
         vector[3] = 1.0f;
         GLSL_SetUniformVec4(sp, UNIFORM_LIGHTORIGIN, vector);
         GLSL_SetUniformFloat(sp, UNIFORM_LIGHTRADIUS, radius);
         GLSL_SetUniformVec4(sp, UNIFORM_NORMALSCALE, pStage->normalScale);
         GLSL_SetUniformVec4(sp, UNIFORM_SPECULARSCALE, pStage->specularScale);
         // include GLS_DEPTHFUNC_EQUAL so alpha tested surfaces don't add light
         // where they aren't rendered
         GL_State( GLS_SRCBLEND_ONE | GLS_DSTBLEND_ONE | GLS_DEPTHFUNC_EQUAL );
         GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 0);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELMATRIX, backEnd.or.transformMatrix);
         if (pStage->bundle[TB_DIFFUSEMAP].image[0])
             R_BindAnimatedImageToTMU( &pStage->bundle[TB_DIFFUSEMAP], TB_DIFFUSEMAP);
         // bind textures that are sampled and used in the glsl shader, and
         // bind whiteImage to textures that are sampled but zeroed in the glsl shader
         //
         // alternatives:
         //  - use the last bound texture
         //     -> costs more to sample a higher res texture then throw out the result
         //  - disable texture sampling in glsl shader with #ifdefs, as before
         //     -> increases the number of shaders that must be compiled
         //
         if (pStage->bundle[TB_NORMALMAP].image[0])
         {
             R_BindAnimatedImageToTMU( &pStage->bundle[TB_NORMALMAP], TB_NORMALMAP);
         }
         else if (r_normalMapping->integer)
             GL_BindToTMU( tr.whiteImage, TB_NORMALMAP );
         if (pStage->bundle[TB_SPECULARMAP].image[0])
         {
             R_BindAnimatedImageToTMU( &pStage->bundle[TB_SPECULARMAP], TB_SPECULARMAP);
         }
         else if (r_specularMapping->integer)
             GL_BindToTMU( tr.whiteImage, TB_SPECULARMAP );
         {
             vec4_t enableTextures;
             VectorSet4(enableTextures, 0.0f, 0.0f, 0.0f, 0.0f);
             GLSL_SetUniformVec4(sp, UNIFORM_ENABLETEXTURES, enableTextures);
         }
         if (r_dlightMode->integer >= 2)
             GL_BindToTMU(tr.shadowCubemaps[l], TB_SHADOWMAP);
         ComputeTexMods( pStage, TB_DIFFUSEMAP, texMatrix, texOffTurb );
         GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXMATRIX, texMatrix);
         GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXOFFTURB, texOffTurb);
         GLSL_SetUniformInt(sp, UNIFORM_TCGEN0, pStage->bundle[0].tcGen);
         //
         // draw
         //
         R_DrawElements(input->numIndexes, input->firstIndex);
         backEnd.pc.c_totalIndexes += tess.numIndexes;
         backEnd.pc.c_dlightIndexes += tess.numIndexes;
         backEnd.pc.c_dlightVertexes += tess.numVertexes;
     }
 }
References AGEN_PORTAL, shaderStage_t::alphaGen, backEnd, shaderStage_t::bundle, backEndCounters_t::c_dlightIndexes, backEndCounters_t::c_dlightVertexes, backEndCounters_t::c_lightallDraws, backEndCounters_t::c_totalIndexes, dlight_s::color, ComputeDeformValues(), ComputeFogColorMask(), ComputeFogValues(), ComputeShaderColors(), ComputeTexMods(), DGEN_NONE, shaderCommands_s::dlightBits, trRefdef_t::dlights, shaderCommands_s::firstIndex, shaderCommands_s::fogNum, GL_BindToTMU(), GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE, GLS_SRCBLEND_ONE, GLSL_BindProgram(), GLSL_SetUniformFloat(), GLSL_SetUniformFloat5(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformVec3(), GLSL_SetUniformVec4(), shaderStage_t::glslShaderIndex, glState, textureBundle_t::image, cvar_s::integer, trGlobals_t::lightallShader, LIGHTDEF_LIGHTTYPE_MASK, LIGHTDEF_USE_LIGHT_VECTOR, glstate_t::modelviewProjection, shaderStage_t::normalScale, trRefdef_t::num_dlights, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, viewParms_t::or, backEndState_t::or, dlight_s::origin, orientationr_t::origin, backEndState_t::pc, shader_s::portalRange, R_BindAnimatedImageToTMU(), r_dlightMode, R_DrawElements(), r_normalMapping, r_specularMapping, dlight_s::radius, backEndState_t::refdef, shaderStage_t::rgbGen, shaderCommands_s::shader, shaderCommands_s::shaderTime, trGlobals_t::shadowCubemaps, shaderStage_t::specularScale, TB_DIFFUSEMAP, TB_NORMALMAP, TB_SHADOWMAP, TB_SPECULARMAP, textureBundle_t::tcGen, tess, tr, orientationr_t::transformMatrix, UNIFORM_ALPHAGEN, UNIFORM_ALPHATEST, UNIFORM_AMBIENTLIGHT, UNIFORM_BASECOLOR, UNIFORM_COLORGEN, UNIFORM_DEFORMGEN, UNIFORM_DEFORMPARAMS, UNIFORM_DIFFUSETEXMATRIX, UNIFORM_DIFFUSETEXOFFTURB, UNIFORM_DIRECTEDLIGHT, UNIFORM_ENABLETEXTURES, UNIFORM_FOGCOLORMASK, UNIFORM_FOGDEPTH, UNIFORM_FOGDISTANCE, UNIFORM_FOGEYET, UNIFORM_LIGHTORIGIN, UNIFORM_LIGHTRADIUS, UNIFORM_LOCALVIEWORIGIN, UNIFORM_MODELMATRIX, UNIFORM_MODELVIEWPROJECTIONMATRIX, UNIFORM_NORMALSCALE, UNIFORM_PORTALRANGE, UNIFORM_SPECULARSCALE, UNIFORM_TCGEN0, UNIFORM_TIME, UNIFORM_VERTCOLOR, UNIFORM_VERTEXLERP, UNIFORM_VIEWORIGIN, VectorCopy, VectorSet, VectorSet4, glstate_t::vertexAttribsInterpolation, orientationr_t::viewOrigin, backEndState_t::viewParms, trGlobals_t::whiteImage, and shaderCommands_s::xstages.
Referenced by RB_StageIteratorGeneric().
ProjectDlightTexture()
static void ProjectDlightTexture (void) static
Definition at line 321 of file tr_shade.c.
{
     int     l;
     vec3_t  origin;
     float   scale;
     float   radius;
     int deformGen;
     vec5_t deformParams;
     if ( !backEnd.refdef.num_dlights ) {
         return;
     }
     ComputeDeformValues(&deformGen, deformParams);
     for ( l = 0 ; l < backEnd.refdef.num_dlights ; l++ ) {
         dlight_t    *dl;
         shaderProgram_t *sp;
         vec4_t vector;
         if ( !( tess.dlightBits & ( 1 << l ) ) ) {
             continue;   // this surface definitely doesn't have any of this light
         }
         dl = &backEnd.refdef.dlights[l];
         VectorCopy( dl->transformed, origin );
         radius = dl->radius;
         scale = 1.0f / radius;
         sp = &tr.dlightShader[deformGen == DGEN_NONE ? 0 : 1];
         backEnd.pc.c_dlightDraws++;
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         GLSL_SetUniformFloat(sp, UNIFORM_VERTEXLERP, glState.vertexAttribsInterpolation);
         GLSL_SetUniformInt(sp, UNIFORM_DEFORMGEN, deformGen);
         if (deformGen != DGEN_NONE)
         {
             GLSL_SetUniformFloat5(sp, UNIFORM_DEFORMPARAMS, deformParams);
             GLSL_SetUniformFloat(sp, UNIFORM_TIME, tess.shaderTime);
         }
         vector[0] = dl->color[0];
         vector[1] = dl->color[1];
         vector[2] = dl->color[2];
         vector[3] = 1.0f;
         GLSL_SetUniformVec4(sp, UNIFORM_COLOR, vector);
         vector[0] = origin[0];
         vector[1] = origin[1];
         vector[2] = origin[2];
         vector[3] = scale;
         GLSL_SetUniformVec4(sp, UNIFORM_DLIGHTINFO, vector);
         GL_BindToTMU( tr.dlightImage, TB_COLORMAP );
         // include GLS_DEPTHFUNC_EQUAL so alpha tested surfaces don't add light
         // where they aren't rendered
         if ( dl->additive ) {
             GL_State( GLS_ATEST_GT_0 | GLS_SRCBLEND_ONE | GLS_DSTBLEND_ONE | GLS_DEPTHFUNC_EQUAL );
         }
         else {
             GL_State( GLS_ATEST_GT_0 | GLS_SRCBLEND_DST_COLOR | GLS_DSTBLEND_ONE | GLS_DEPTHFUNC_EQUAL );
         }
         GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 1);
         R_DrawElements(tess.numIndexes, tess.firstIndex);
         backEnd.pc.c_totalIndexes += tess.numIndexes;
         backEnd.pc.c_dlightIndexes += tess.numIndexes;
         backEnd.pc.c_dlightVertexes += tess.numVertexes;
     }
 }
References dlight_s::additive, backEnd, backEndCounters_t::c_dlightDraws, backEndCounters_t::c_dlightIndexes, backEndCounters_t::c_dlightVertexes, backEndCounters_t::c_totalIndexes, dlight_s::color, ComputeDeformValues(), DGEN_NONE, shaderCommands_s::dlightBits, trGlobals_t::dlightImage, trRefdef_t::dlights, trGlobals_t::dlightShader, shaderCommands_s::firstIndex, GL_BindToTMU(), GL_State(), GLS_ATEST_GT_0, GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE, GLS_SRCBLEND_DST_COLOR, GLS_SRCBLEND_ONE, GLSL_BindProgram(), GLSL_SetUniformFloat(), GLSL_SetUniformFloat5(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformVec4(), glState, glstate_t::modelviewProjection, trRefdef_t::num_dlights, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, backEndState_t::pc, R_DrawElements(), dlight_s::radius, backEndState_t::refdef, shaderCommands_s::shaderTime, TB_COLORMAP, tess, tr, dlight_s::transformed, UNIFORM_ALPHATEST, UNIFORM_COLOR, UNIFORM_DEFORMGEN, UNIFORM_DEFORMPARAMS, UNIFORM_DLIGHTINFO, UNIFORM_MODELVIEWPROJECTIONMATRIX, UNIFORM_TIME, UNIFORM_VERTEXLERP, VectorCopy, and glstate_t::vertexAttribsInterpolation.
Referenced by RB_StageIteratorGeneric().
ProjectPshadowVBOGLSL()
static void ProjectPshadowVBOGLSL (void) static
Definition at line 814 of file tr_shade.c.
{
     int     l;
     vec3_t  origin;
     float   radius;
     int deformGen;
     vec5_t deformParams;
     shaderCommands_t *input = &tess;
     if ( !backEnd.refdef.num_pshadows ) {
         return;
     }
     ComputeDeformValues(&deformGen, deformParams);
     for ( l = 0 ; l < backEnd.refdef.num_pshadows ; l++ ) {
         pshadow_t   *ps;
         shaderProgram_t *sp;
         vec4_t vector;
         if ( !( tess.pshadowBits & ( 1 << l ) ) ) {
             continue;   // this surface definitely doesn't have any of this shadow
         }
         ps = &backEnd.refdef.pshadows[l];
         VectorCopy( ps->lightOrigin, origin );
         radius = ps->lightRadius;
         sp = &tr.pshadowShader;
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         VectorCopy(origin, vector);
         vector[3] = 1.0f;
         GLSL_SetUniformVec4(sp, UNIFORM_LIGHTORIGIN, vector);
         VectorScale(ps->lightViewAxis[0], 1.0f / ps->viewRadius, vector);
         GLSL_SetUniformVec3(sp, UNIFORM_LIGHTFORWARD, vector);
         VectorScale(ps->lightViewAxis[1], 1.0f / ps->viewRadius, vector);
         GLSL_SetUniformVec3(sp, UNIFORM_LIGHTRIGHT, vector);
         VectorScale(ps->lightViewAxis[2], 1.0f / ps->viewRadius, vector);
         GLSL_SetUniformVec3(sp, UNIFORM_LIGHTUP, vector);
         GLSL_SetUniformFloat(sp, UNIFORM_LIGHTRADIUS, radius);
         // include GLS_DEPTHFUNC_EQUAL so alpha tested surfaces don't add light
         // where they aren't rendered
         GL_State( GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA | GLS_DEPTHFUNC_EQUAL );
         GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 0);
         GL_BindToTMU( tr.pshadowMaps[l], TB_DIFFUSEMAP );
         //
         // draw
         //
         R_DrawElements(input->numIndexes, input->firstIndex);
         backEnd.pc.c_totalIndexes += tess.numIndexes;
         //backEnd.pc.c_dlightIndexes += tess.numIndexes;
     }
 }
References backEnd, backEndCounters_t::c_totalIndexes, ComputeDeformValues(), shaderCommands_s::firstIndex, GL_BindToTMU(), GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_SRCBLEND_SRC_ALPHA, GLSL_BindProgram(), GLSL_SetUniformFloat(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformVec3(), GLSL_SetUniformVec4(), glState, pshadow_s::lightOrigin, pshadow_s::lightRadius, pshadow_s::lightViewAxis, glstate_t::modelviewProjection, trRefdef_t::num_pshadows, shaderCommands_s::numIndexes, backEndState_t::pc, shaderCommands_s::pshadowBits, trGlobals_t::pshadowMaps, trRefdef_t::pshadows, trGlobals_t::pshadowShader, R_DrawElements(), backEndState_t::refdef, TB_DIFFUSEMAP, tess, tr, UNIFORM_ALPHATEST, UNIFORM_LIGHTFORWARD, UNIFORM_LIGHTORIGIN, UNIFORM_LIGHTRADIUS, UNIFORM_LIGHTRIGHT, UNIFORM_LIGHTUP, UNIFORM_MODELVIEWPROJECTIONMATRIX, VectorCopy, VectorScale, and pshadow_s::viewRadius.
Referenced by RB_StageIteratorGeneric().
R_BindAnimatedImageToTMU()
static void R_BindAnimatedImageToTMU (textureBundle_t * bundle, int tmu) static
Definition at line 64 of file tr_shade.c.
{
     int64_t index;
     if ( bundle->isVideoMap ) {
         ri.CIN_RunCinematic(bundle->videoMapHandle);
         ri.CIN_UploadCinematic(bundle->videoMapHandle);
         GL_BindToTMU(tr.scratchImage[bundle->videoMapHandle], tmu);
         return;
     }
     if ( bundle->numImageAnimations <= 1 ) {
         GL_BindToTMU( bundle->image[0], tmu);
         return;
     }
     // it is necessary to do this messy calc to make sure animations line up
     // exactly with waveforms of the same frequency
     index = tess.shaderTime * bundle->imageAnimationSpeed * FUNCTABLE_SIZE;
     index >>= FUNCTABLE_SIZE2;
     if ( index < 0 ) {
         index = 0;  // may happen with shader time offsets
     }
     // Windows x86 doesn't load renderer DLL with 64 bit modulus
     //index %= bundle->numImageAnimations;
     while ( index >= bundle->numImageAnimations ) {
         index -= bundle->numImageAnimations;
     }
     GL_BindToTMU( bundle->image[ index ], tmu );
 }
References refimport_t::CIN_RunCinematic, refimport_t::CIN_UploadCinematic, FUNCTABLE_SIZE, FUNCTABLE_SIZE2, GL_BindToTMU(), textureBundle_t::image, textureBundle_t::imageAnimationSpeed, textureBundle_t::isVideoMap, textureBundle_t::numImageAnimations, ri, trGlobals_t::scratchImage, shaderCommands_s::shaderTime, tess, tr, and textureBundle_t::videoMapHandle.
Referenced by ForwardDlight(), and RB_IterateStagesGeneric().
R_DrawElements()
void R_DrawElements (int numIndexes, int firstIndex)
Definition at line 41 of file tr_shade.c.
 {
     qglDrawElements(GL_TRIANGLES, numIndexes, GL_INDEX_TYPE, BUFFER_OFFSET(firstIndex * sizeof(glIndex_t)));
 }
References BUFFER_OFFSET, and GL_INDEX_TYPE.
Referenced by DrawSkySide(), DrawTris(), ForwardDlight(), ProjectDlightTexture(), ProjectPshadowVBOGLSL(), RB_FogPass(), RB_InstantQuad2(), RB_IterateStagesGeneric(), RB_RenderShadowmap(), and RB_SurfaceBeam().
RB_BeginSurface()
void RB_BeginSurface (shader_t * shader, int fogNum, int cubemapIndex)
Definition at line 149 of file tr_shade.c.
{
     shader_t *state = (shader->remappedShader) ? shader->remappedShader : shader;
     tess.numIndexes = 0;
     tess.firstIndex = 0;
     tess.numVertexes = 0;
     tess.shader = state;
     tess.fogNum = fogNum;
     tess.cubemapIndex = cubemapIndex;
     tess.dlightBits = 0;        // will be OR'd in by surface functions
     tess.pshadowBits = 0;       // will be OR'd in by surface functions
     tess.xstages = state->stages;
     tess.numPasses = state->numUnfoggedPasses;
     tess.currentStageIteratorFunc = state->optimalStageIteratorFunc;
     tess.useInternalVao = qtrue;
     tess.useCacheVao = qfalse;
     tess.shaderTime = backEnd.refdef.floatTime - tess.shader->timeOffset;
     if (tess.shader->clampTime && tess.shaderTime >= tess.shader->clampTime) {
         tess.shaderTime = tess.shader->clampTime;
     }
     if (backEnd.viewParms.flags & VPF_SHADOWMAP)
     {
         tess.currentStageIteratorFunc = RB_StageIteratorGeneric;
     }
 }
References backEnd, shader_s::clampTime, shaderCommands_s::cubemapIndex, shaderCommands_s::currentStageIteratorFunc, shaderCommands_s::dlightBits, shaderCommands_s::firstIndex, viewParms_t::flags, trRefdef_t::floatTime, shaderCommands_s::fogNum, shaderCommands_s::numIndexes, shaderCommands_s::numPasses, shaderCommands_s::numVertexes, shaderCommands_s::pshadowBits, qfalse, qtrue, RB_StageIteratorGeneric(), backEndState_t::refdef, shader_s::remappedShader, shader, shaderCommands_s::shader, shaderCommands_s::shaderTime, tess, shader_s::timeOffset, shaderCommands_s::useCacheVao, shaderCommands_s::useInternalVao, backEndState_t::viewParms, VPF_SHADOWMAP, and shaderCommands_s::xstages.
Referenced by RB_CheckOverflow(), RB_CheckVao(), RB_DrawSun(), RB_IQMSurfaceAnimVao(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), RB_SurfaceVaoCached(), RB_SurfaceVaoMdvMesh(), and SurfIsOffscreen().
RB_CalcShaderVertexAttribs()
static unsigned int RB_CalcShaderVertexAttribs (shaderCommands_t * input) static
Definition at line 962 of file tr_shade.c.
 {
     unsigned int vertexAttribs = input->shader->vertexAttribs;
     if(glState.vertexAnimation)
     {
         vertexAttribs |= ATTR_POSITION2;
         if (vertexAttribs & ATTR_NORMAL)
         {
             vertexAttribs |= ATTR_NORMAL2;
             vertexAttribs |= ATTR_TANGENT2;
         }
     }
     return vertexAttribs;
 }
References ATTR_NORMAL, ATTR_NORMAL2, ATTR_POSITION2, ATTR_TANGENT2, glState, shaderCommands_s::shader, glstate_t::vertexAnimation, and shader_s::vertexAttribs.
Referenced by RB_StageIteratorGeneric().
RB_EndSurface()
void RB_EndSurface (void)
Definition at line 1619 of file tr_shade.c.
{
     shaderCommands_t *input;
     input = &tess;
     if (input->numIndexes == 0 || input->numVertexes == 0) {
         return;
     }
     if (input->indexes[SHADER_MAX_INDEXES-1] != 0) {
         ri.Error (ERR_DROP, "RB_EndSurface() - SHADER_MAX_INDEXES hit");
     }
     if (input->xyz[SHADER_MAX_VERTEXES-1][0] != 0) {
         ri.Error (ERR_DROP, "RB_EndSurface() - SHADER_MAX_VERTEXES hit");
     }
     if ( tess.shader == tr.shadowShader ) {
         RB_ShadowTessEnd();
         return;
     }
     // for debugging of sort order issues, stop rendering after a given sort value
     if ( r_debugSort->integer && r_debugSort->integer < tess.shader->sort ) {
         return;
     }
     if (tess.useCacheVao)
     {
         // upload indexes now
         VaoCache_Commit();
     }
     //
     // update performance counters
     //
     backEnd.pc.c_shaders++;
     backEnd.pc.c_vertexes += tess.numVertexes;
     backEnd.pc.c_indexes += tess.numIndexes;
     backEnd.pc.c_totalIndexes += tess.numIndexes * tess.numPasses;
     //
     // call off to shader specific tess end function
     //
     tess.currentStageIteratorFunc();
     //
     // draw debugging stuff
     //
     if ( r_showtris->integer ) {
         DrawTris (input);
     }
     if ( r_shownormals->integer ) {
         DrawNormals (input);
     }
     // clear shader so we can tell we don't have any unclosed surfaces
     tess.numIndexes = 0;
     tess.numVertexes = 0;
     tess.firstIndex = 0;
     GLimp_LogComment( "----------\n" );
 }
References backEnd, backEndCounters_t::c_indexes, backEndCounters_t::c_shaders, backEndCounters_t::c_totalIndexes, backEndCounters_t::c_vertexes, shaderCommands_s::currentStageIteratorFunc, DrawNormals(), DrawTris(), ERR_DROP, shaderCommands_s::firstIndex, GLimp_LogComment(), cvar_s::integer, shaderCommands_s::numIndexes, shaderCommands_s::numPasses, shaderCommands_s::numVertexes, backEndState_t::pc, r_debugSort, r_shownormals, r_showtris, RB_ShadowTessEnd(), ri, shaderCommands_s::shader, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, trGlobals_t::shadowShader, shader_s::sort, tess, tr, shaderCommands_s::useCacheVao, and VaoCache_Commit().
Referenced by RB_CapShadowMap(), RB_CheckOverflow(), RB_CheckVao(), RB_ClearDepth(), RB_ColorMask(), RB_DrawBuffer(), RB_DrawSun(), RB_DrawSurfs(), RB_ExecuteRenderCommands(), RB_ExportCubemaps(), RB_IQMSurfaceAnimVao(), RB_PostProcess(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_StretchPic(), RB_SurfaceGrid(), RB_SurfaceVaoCached(), RB_SurfaceVaoMdvMesh(), RB_SwapBuffers(), RB_TakeScreenshotCmd(), RB_TakeVideoFrameCmd(), and RE_StretchRaw().
RB_FogPass()
static void RB_FogPass (void) static
Definition at line 891 of file tr_shade.c.
{
     fog_t       *fog;
     vec4_t  color;
     vec4_t  fogDistanceVector, fogDepthVector = {0, 0, 0, 0};
     float   eyeT = 0;
     shaderProgram_t *sp;
     int deformGen;
     vec5_t deformParams;
     ComputeDeformValues(&deformGen, deformParams);
     {
         int index = 0;
         if (deformGen != DGEN_NONE)
             index |= FOGDEF_USE_DEFORM_VERTEXES;
         if (glState.vertexAnimation)
             index |= FOGDEF_USE_VERTEX_ANIMATION;
         else if (glState.boneAnimation)
             index |= FOGDEF_USE_BONE_ANIMATION;
         sp = &tr.fogShader[index];
     }
     backEnd.pc.c_fogDraws++;
     GLSL_BindProgram(sp);
     fog = tr.world->fogs + tess.fogNum;
     GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
     GLSL_SetUniformFloat(sp, UNIFORM_VERTEXLERP, glState.vertexAttribsInterpolation);
     if (glState.boneAnimation)
     {
         GLSL_SetUniformMat4BoneMatrix(sp, UNIFORM_BONEMATRIX, glState.boneMatrix, glState.boneAnimation);
     }
     GLSL_SetUniformInt(sp, UNIFORM_DEFORMGEN, deformGen);
     if (deformGen != DGEN_NONE)
     {
         GLSL_SetUniformFloat5(sp, UNIFORM_DEFORMPARAMS, deformParams);
         GLSL_SetUniformFloat(sp, UNIFORM_TIME, tess.shaderTime);
     }
     color[0] = ((unsigned char *)(&fog->colorInt))[0] / 255.0f;
     color[1] = ((unsigned char *)(&fog->colorInt))[1] / 255.0f;
     color[2] = ((unsigned char *)(&fog->colorInt))[2] / 255.0f;
     color[3] = ((unsigned char *)(&fog->colorInt))[3] / 255.0f;
     GLSL_SetUniformVec4(sp, UNIFORM_COLOR, color);
     ComputeFogValues(fogDistanceVector, fogDepthVector, &eyeT);
     GLSL_SetUniformVec4(sp, UNIFORM_FOGDISTANCE, fogDistanceVector);
     GLSL_SetUniformVec4(sp, UNIFORM_FOGDEPTH, fogDepthVector);
     GLSL_SetUniformFloat(sp, UNIFORM_FOGEYET, eyeT);
     if ( tess.shader->fogPass == FP_EQUAL ) {
         GL_State( GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA | GLS_DEPTHFUNC_EQUAL );
     } else {
         GL_State( GLS_SRCBLEND_SRC_ALPHA | GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA );
     }
     GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 0);
     R_DrawElements(tess.numIndexes, tess.firstIndex);
 }
References backEnd, glstate_t::boneAnimation, glstate_t::boneMatrix, backEndCounters_t::c_fogDraws, fog_t::colorInt, ComputeDeformValues(), ComputeFogValues(), DGEN_NONE, shaderCommands_s::firstIndex, FOGDEF_USE_BONE_ANIMATION, FOGDEF_USE_DEFORM_VERTEXES, FOGDEF_USE_VERTEX_ANIMATION, shaderCommands_s::fogNum, shader_s::fogPass, world_t::fogs, trGlobals_t::fogShader, FP_EQUAL, GL_State(), GLS_DEPTHFUNC_EQUAL, GLS_DSTBLEND_ONE_MINUS_SRC_ALPHA, GLS_SRCBLEND_SRC_ALPHA, GLSL_BindProgram(), GLSL_SetUniformFloat(), GLSL_SetUniformFloat5(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformMat4BoneMatrix(), GLSL_SetUniformVec4(), glState, glstate_t::modelviewProjection, shaderCommands_s::numIndexes, backEndState_t::pc, R_DrawElements(), shaderCommands_s::shader, shaderCommands_s::shaderTime, tess, tr, UNIFORM_ALPHATEST, UNIFORM_BONEMATRIX, UNIFORM_COLOR, UNIFORM_DEFORMGEN, UNIFORM_DEFORMPARAMS, UNIFORM_FOGDEPTH, UNIFORM_FOGDISTANCE, UNIFORM_FOGEYET, UNIFORM_MODELVIEWPROJECTIONMATRIX, UNIFORM_TIME, UNIFORM_VERTEXLERP, glstate_t::vertexAnimation, glstate_t::vertexAttribsInterpolation, and trGlobals_t::world.
Referenced by RB_StageIteratorGeneric().
RB_IterateStagesGeneric()
static void RB_IterateStagesGeneric (shaderCommands_t * input) static
Definition at line 979 of file tr_shade.c.
 {
     int stage;
     vec4_t fogDistanceVector, fogDepthVector = {0, 0, 0, 0};
     float eyeT = 0;
     int deformGen;
     vec5_t deformParams;
     qboolean renderToCubemap = tr.renderCubeFbo && glState.currentFBO == tr.renderCubeFbo;
     ComputeDeformValues(&deformGen, deformParams);
     ComputeFogValues(fogDistanceVector, fogDepthVector, &eyeT);
     for ( stage = 0; stage < MAX_SHADER_STAGES; stage++ )
     {
         shaderStage_t *pStage = input->xstages[stage];
         shaderProgram_t *sp;
         vec4_t texMatrix;
         vec4_t texOffTurb;
         if ( !pStage )
         {
             break;
         }
         if (backEnd.depthFill)
         {
             if (pStage->glslShaderGroup == tr.lightallShader)
             {
                 int index = 0;
                 if (backEnd.currentEntity && backEnd.currentEntity != &tr.worldEntity)
                 {
                     if (glState.boneAnimation)
                     {
                         index |= LIGHTDEF_ENTITY_BONE_ANIMATION;
                     }
                     else
                     {
                         index |= LIGHTDEF_ENTITY_VERTEX_ANIMATION;
                     }
                 }
                 if (pStage->stateBits & GLS_ATEST_BITS)
                 {
                     index |= LIGHTDEF_USE_TCGEN_AND_TCMOD;
                 }
                 sp = &pStage->glslShaderGroup[index];
             }
             else
             {
                 int shaderAttribs = 0;
                 if (tess.shader->numDeforms && !ShaderRequiresCPUDeforms(tess.shader))
                 {
                     shaderAttribs |= GENERICDEF_USE_DEFORM_VERTEXES;
                 }
                 if (glState.vertexAnimation)
                 {
                     shaderAttribs |= GENERICDEF_USE_VERTEX_ANIMATION;
                 }
                 else if (glState.boneAnimation)
                 {
                     shaderAttribs |= GENERICDEF_USE_BONE_ANIMATION;
                 }
                 if (pStage->stateBits & GLS_ATEST_BITS)
                 {
                     shaderAttribs |= GENERICDEF_USE_TCGEN_AND_TCMOD;
                 }
                 sp = &tr.genericShader[shaderAttribs];
             }
         }
         else if (pStage->glslShaderGroup == tr.lightallShader)
         {
             int index = pStage->glslShaderIndex;
             if (backEnd.currentEntity && backEnd.currentEntity != &tr.worldEntity)
             {
                 if (glState.boneAnimation)
                 {
                     index |= LIGHTDEF_ENTITY_BONE_ANIMATION;
                 }
                 else
                 {
                     index |= LIGHTDEF_ENTITY_VERTEX_ANIMATION;
                 }
             }
             if (r_sunlightMode->integer && (backEnd.viewParms.flags & VPF_USESUNLIGHT) && (index & LIGHTDEF_LIGHTTYPE_MASK))
             {
                 index |= LIGHTDEF_USE_SHADOWMAP;
             }
             if (r_lightmap->integer && ((index & LIGHTDEF_LIGHTTYPE_MASK) == LIGHTDEF_USE_LIGHTMAP))
             {
                 index = LIGHTDEF_USE_TCGEN_AND_TCMOD;
             }
             sp = &pStage->glslShaderGroup[index];
             backEnd.pc.c_lightallDraws++;
         }
         else
         {
             sp = GLSL_GetGenericShaderProgram(stage);
             backEnd.pc.c_genericDraws++;
         }
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         GLSL_SetUniformVec3(sp, UNIFORM_VIEWORIGIN, backEnd.viewParms.or.origin);
         GLSL_SetUniformVec3(sp, UNIFORM_LOCALVIEWORIGIN, backEnd.or.viewOrigin);
         GLSL_SetUniformFloat(sp, UNIFORM_VERTEXLERP, glState.vertexAttribsInterpolation);
         if (glState.boneAnimation)
         {
             GLSL_SetUniformMat4BoneMatrix(sp, UNIFORM_BONEMATRIX, glState.boneMatrix, glState.boneAnimation);
         }
         GLSL_SetUniformInt(sp, UNIFORM_DEFORMGEN, deformGen);
         if (deformGen != DGEN_NONE)
         {
             GLSL_SetUniformFloat5(sp, UNIFORM_DEFORMPARAMS, deformParams);
             GLSL_SetUniformFloat(sp, UNIFORM_TIME, tess.shaderTime);
         }
         if ( input->fogNum ) {
             GLSL_SetUniformVec4(sp, UNIFORM_FOGDISTANCE, fogDistanceVector);
             GLSL_SetUniformVec4(sp, UNIFORM_FOGDEPTH, fogDepthVector);
             GLSL_SetUniformFloat(sp, UNIFORM_FOGEYET, eyeT);
         }
         GL_State( pStage->stateBits );
         if ((pStage->stateBits & GLS_ATEST_BITS) == GLS_ATEST_GT_0)
         {
             GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 1);
         }
         else if ((pStage->stateBits & GLS_ATEST_BITS) == GLS_ATEST_LT_80)
         {
             GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 2);
         }
         else if ((pStage->stateBits & GLS_ATEST_BITS) == GLS_ATEST_GE_80)
         {
             GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 3);
         }
         else
         {
             GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 0);
         }
         {
             vec4_t baseColor;
             vec4_t vertColor;
             ComputeShaderColors(pStage, baseColor, vertColor, pStage->stateBits);
             GLSL_SetUniformVec4(sp, UNIFORM_BASECOLOR, baseColor);
             GLSL_SetUniformVec4(sp, UNIFORM_VERTCOLOR, vertColor);
         }
         if (pStage->rgbGen == CGEN_LIGHTING_DIFFUSE)
         {
             vec4_t vec;
             VectorScale(backEnd.currentEntity->ambientLight, 1.0f / 255.0f, vec);
             GLSL_SetUniformVec3(sp, UNIFORM_AMBIENTLIGHT, vec);
             VectorScale(backEnd.currentEntity->directedLight, 1.0f / 255.0f, vec);
             GLSL_SetUniformVec3(sp, UNIFORM_DIRECTEDLIGHT, vec);
             VectorCopy(backEnd.currentEntity->lightDir, vec);
             vec[3] = 0.0f;
             GLSL_SetUniformVec4(sp, UNIFORM_LIGHTORIGIN, vec);
             GLSL_SetUniformVec3(sp, UNIFORM_MODELLIGHTDIR, backEnd.currentEntity->modelLightDir);
             GLSL_SetUniformFloat(sp, UNIFORM_LIGHTRADIUS, 0.0f);
         }
         if (pStage->alphaGen == AGEN_PORTAL)
         {
             GLSL_SetUniformFloat(sp, UNIFORM_PORTALRANGE, tess.shader->portalRange);
         }
         GLSL_SetUniformInt(sp, UNIFORM_COLORGEN, pStage->rgbGen);
         GLSL_SetUniformInt(sp, UNIFORM_ALPHAGEN, pStage->alphaGen);
         if ( input->fogNum )
         {
             vec4_t fogColorMask;
             ComputeFogColorMask(pStage, fogColorMask);
             GLSL_SetUniformVec4(sp, UNIFORM_FOGCOLORMASK, fogColorMask);
         }
         if (r_lightmap->integer)
         {
             vec4_t v;
             VectorSet4(v, 1.0f, 0.0f, 0.0f, 1.0f);
             GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXMATRIX, v);
             VectorSet4(v, 0.0f, 0.0f, 0.0f, 0.0f);
             GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXOFFTURB, v);
             GLSL_SetUniformInt(sp, UNIFORM_TCGEN0, TCGEN_LIGHTMAP);
         }
         else
         {
             ComputeTexMods(pStage, TB_DIFFUSEMAP, texMatrix, texOffTurb);
             GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXMATRIX, texMatrix);
             GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXOFFTURB, texOffTurb);
             GLSL_SetUniformInt(sp, UNIFORM_TCGEN0, pStage->bundle[0].tcGen);
             if (pStage->bundle[0].tcGen == TCGEN_VECTOR)
             {
                 vec3_t vec;
                 VectorCopy(pStage->bundle[0].tcGenVectors[0], vec);
                 GLSL_SetUniformVec3(sp, UNIFORM_TCGEN0VECTOR0, vec);
                 VectorCopy(pStage->bundle[0].tcGenVectors[1], vec);
                 GLSL_SetUniformVec3(sp, UNIFORM_TCGEN0VECTOR1, vec);
             }
         }
         GLSL_SetUniformMat4(sp, UNIFORM_MODELMATRIX, backEnd.or.transformMatrix);
         GLSL_SetUniformVec4(sp, UNIFORM_NORMALSCALE, pStage->normalScale);
         {
             vec4_t specularScale;
             Vector4Copy(pStage->specularScale, specularScale);
             if (renderToCubemap)
             {
                 // force specular to nonmetal if rendering cubemaps
                 if (r_pbr->integer)
                     specularScale[1] = 0.0f;
             }
             GLSL_SetUniformVec4(sp, UNIFORM_SPECULARSCALE, specularScale);
         }
         //GLSL_SetUniformFloat(sp, UNIFORM_MAPLIGHTSCALE, backEnd.refdef.mapLightScale);
         //
         // do multitexture
         //
         if ( backEnd.depthFill )
         {
             if (!(pStage->stateBits & GLS_ATEST_BITS))
                 GL_BindToTMU( tr.whiteImage, TB_COLORMAP );
             else if ( pStage->bundle[TB_COLORMAP].image[0] != 0 )
                 R_BindAnimatedImageToTMU( &pStage->bundle[TB_COLORMAP], TB_COLORMAP );
         }
         else if ( pStage->glslShaderGroup == tr.lightallShader )
         {
             int i;
             vec4_t enableTextures;
             if (r_sunlightMode->integer && (backEnd.viewParms.flags & VPF_USESUNLIGHT) && (pStage->glslShaderIndex & LIGHTDEF_LIGHTTYPE_MASK))
             {
                 // FIXME: screenShadowImage is NULL if no framebuffers
                 if (tr.screenShadowImage)
                     GL_BindToTMU(tr.screenShadowImage, TB_SHADOWMAP);
                 GLSL_SetUniformVec3(sp, UNIFORM_PRIMARYLIGHTAMBIENT, backEnd.refdef.sunAmbCol);
                 if (r_pbr->integer)
                 {
                     vec3_t color;
                     color[0] = backEnd.refdef.sunCol[0] * backEnd.refdef.sunCol[0];
                     color[1] = backEnd.refdef.sunCol[1] * backEnd.refdef.sunCol[1];
                     color[2] = backEnd.refdef.sunCol[2] * backEnd.refdef.sunCol[2];
                     GLSL_SetUniformVec3(sp, UNIFORM_PRIMARYLIGHTCOLOR, color);
                 }
                 else
                 {
                     GLSL_SetUniformVec3(sp, UNIFORM_PRIMARYLIGHTCOLOR, backEnd.refdef.sunCol);
                 }
                 GLSL_SetUniformVec4(sp, UNIFORM_PRIMARYLIGHTORIGIN,  backEnd.refdef.sunDir);
             }
             VectorSet4(enableTextures, 0, 0, 0, 0);
             if ((r_lightmap->integer == 1 || r_lightmap->integer == 2) && pStage->bundle[TB_LIGHTMAP].image[0])
             {
                 for (i = 0; i < NUM_TEXTURE_BUNDLES; i++)
                 {
                     if (i == TB_COLORMAP)
                         R_BindAnimatedImageToTMU( &pStage->bundle[TB_LIGHTMAP], i);
                     else
                         GL_BindToTMU( tr.whiteImage, i );
                 }
             }
             else if (r_lightmap->integer == 3 && pStage->bundle[TB_DELUXEMAP].image[0])
             {
                 for (i = 0; i < NUM_TEXTURE_BUNDLES; i++)
                 {
                     if (i == TB_COLORMAP)
                         R_BindAnimatedImageToTMU( &pStage->bundle[TB_DELUXEMAP], i);
                     else
                         GL_BindToTMU( tr.whiteImage, i );
                 }
             }
             else
             {
                 qboolean light = (pStage->glslShaderIndex & LIGHTDEF_LIGHTTYPE_MASK) != 0;
                 qboolean fastLight = !(r_normalMapping->integer || r_specularMapping->integer);
                 if (pStage->bundle[TB_DIFFUSEMAP].image[0])
                     R_BindAnimatedImageToTMU( &pStage->bundle[TB_DIFFUSEMAP], TB_DIFFUSEMAP);
                 if (pStage->bundle[TB_LIGHTMAP].image[0])
                     R_BindAnimatedImageToTMU( &pStage->bundle[TB_LIGHTMAP], TB_LIGHTMAP);
                 // bind textures that are sampled and used in the glsl shader, and
                 // bind whiteImage to textures that are sampled but zeroed in the glsl shader
                 //
                 // alternatives:
                 //  - use the last bound texture
                 //     -> costs more to sample a higher res texture then throw out the result
                 //  - disable texture sampling in glsl shader with #ifdefs, as before
                 //     -> increases the number of shaders that must be compiled
                 //
                 if (light && !fastLight)
                 {
                     if (pStage->bundle[TB_NORMALMAP].image[0])
                     {
                         R_BindAnimatedImageToTMU( &pStage->bundle[TB_NORMALMAP], TB_NORMALMAP);
                         enableTextures[0] = 1.0f;
                     }
                     else if (r_normalMapping->integer)
                         GL_BindToTMU( tr.whiteImage, TB_NORMALMAP );
                     if (pStage->bundle[TB_DELUXEMAP].image[0])
                     {
                         R_BindAnimatedImageToTMU( &pStage->bundle[TB_DELUXEMAP], TB_DELUXEMAP);
                         enableTextures[1] = 1.0f;
                     }
                     else if (r_deluxeMapping->integer)
                         GL_BindToTMU( tr.whiteImage, TB_DELUXEMAP );
                     if (pStage->bundle[TB_SPECULARMAP].image[0])
                     {
                         R_BindAnimatedImageToTMU( &pStage->bundle[TB_SPECULARMAP], TB_SPECULARMAP);
                         enableTextures[2] = 1.0f;
                     }
                     else if (r_specularMapping->integer)
                         GL_BindToTMU( tr.whiteImage, TB_SPECULARMAP );
                 }
                 enableTextures[3] = (r_cubeMapping->integer && !(tr.viewParms.flags & VPF_NOCUBEMAPS) && input->cubemapIndex) ? 1.0f : 0.0f;
             }
             GLSL_SetUniformVec4(sp, UNIFORM_ENABLETEXTURES, enableTextures);
         }
         else if ( pStage->bundle[1].image[0] != 0 )
         {
             R_BindAnimatedImageToTMU( &pStage->bundle[0], 0 );
             R_BindAnimatedImageToTMU( &pStage->bundle[1], 1 );
         }
         else
         {
             //
             // set state
             //
             R_BindAnimatedImageToTMU( &pStage->bundle[0], 0 );
         }
         //
         // testing cube map
         //
         if (!(tr.viewParms.flags & VPF_NOCUBEMAPS) && input->cubemapIndex && r_cubeMapping->integer)
         {
             vec4_t vec;
             cubemap_t *cubemap = &tr.cubemaps[input->cubemapIndex - 1];
             // FIXME: cubemap image could be NULL if cubemap isn't renderer or loaded
             if (cubemap->image)
                 GL_BindToTMU( cubemap->image, TB_CUBEMAP);
             VectorSubtract(cubemap->origin, backEnd.viewParms.or.origin, vec);
             vec[3] = 1.0f;
             VectorScale4(vec, 1.0f / cubemap->parallaxRadius, vec);
             GLSL_SetUniformVec4(sp, UNIFORM_CUBEMAPINFO, vec);
         }
         //
         // draw
         //
         R_DrawElements(input->numIndexes, input->firstIndex);
         // allow skipping out to show just lightmaps during development
         if ( r_lightmap->integer && ( pStage->bundle[0].isLightmap || pStage->bundle[1].isLightmap ) )
         {
             break;
         }
         if (backEnd.depthFill)
             break;
     }
 }
References AGEN_PORTAL, shaderStage_t::alphaGen, trRefEntity_t::ambientLight, backEnd, glstate_t::boneAnimation, glstate_t::boneMatrix, shaderStage_t::bundle, backEndCounters_t::c_genericDraws, backEndCounters_t::c_lightallDraws, CGEN_LIGHTING_DIFFUSE, ComputeDeformValues(), ComputeFogColorMask(), ComputeFogValues(), ComputeShaderColors(), ComputeTexMods(), shaderCommands_s::cubemapIndex, trGlobals_t::cubemaps, backEndState_t::currentEntity, glstate_t::currentFBO, backEndState_t::depthFill, DGEN_NONE, trRefEntity_t::directedLight, shaderCommands_s::firstIndex, viewParms_t::flags, shaderCommands_s::fogNum, GENERICDEF_USE_BONE_ANIMATION, GENERICDEF_USE_DEFORM_VERTEXES, GENERICDEF_USE_TCGEN_AND_TCMOD, GENERICDEF_USE_VERTEX_ANIMATION, trGlobals_t::genericShader, GL_BindToTMU(), GL_State(), GLS_ATEST_BITS, GLS_ATEST_GE_80, GLS_ATEST_GT_0, GLS_ATEST_LT_80, GLSL_BindProgram(), GLSL_GetGenericShaderProgram(), GLSL_SetUniformFloat(), GLSL_SetUniformFloat5(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformMat4BoneMatrix(), GLSL_SetUniformVec3(), GLSL_SetUniformVec4(), shaderStage_t::glslShaderGroup, shaderStage_t::glslShaderIndex, glState, cubemap_s::image, textureBundle_t::image, cvar_s::integer, textureBundle_t::isLightmap, trGlobals_t::lightallShader, LIGHTDEF_ENTITY_BONE_ANIMATION, LIGHTDEF_ENTITY_VERTEX_ANIMATION, LIGHTDEF_LIGHTTYPE_MASK, LIGHTDEF_USE_LIGHTMAP, LIGHTDEF_USE_SHADOWMAP, LIGHTDEF_USE_TCGEN_AND_TCMOD, trRefEntity_t::lightDir, MAX_SHADER_STAGES, trRefEntity_t::modelLightDir, glstate_t::modelviewProjection, shaderStage_t::normalScale, NUM_TEXTURE_BUNDLES, shader_s::numDeforms, shaderCommands_s::numIndexes, viewParms_t::or, backEndState_t::or, cubemap_s::origin, orientationr_t::origin, cubemap_s::parallaxRadius, backEndState_t::pc, shader_s::portalRange, R_BindAnimatedImageToTMU(), r_cubeMapping, r_deluxeMapping, R_DrawElements(), r_lightmap, r_normalMapping, r_pbr, r_specularMapping, r_sunlightMode, backEndState_t::refdef, trGlobals_t::renderCubeFbo, shaderStage_t::rgbGen, trGlobals_t::screenShadowImage, shaderCommands_s::shader, ShaderRequiresCPUDeforms(), shaderCommands_s::shaderTime, shaderStage_t::specularScale, shaderStage_t::stateBits, trRefdef_t::sunAmbCol, trRefdef_t::sunCol, trRefdef_t::sunDir, TB_COLORMAP, TB_CUBEMAP, TB_DELUXEMAP, TB_DIFFUSEMAP, TB_LIGHTMAP, TB_NORMALMAP, TB_SHADOWMAP, TB_SPECULARMAP, textureBundle_t::tcGen, TCGEN_LIGHTMAP, TCGEN_VECTOR, textureBundle_t::tcGenVectors, tess, tr, orientationr_t::transformMatrix, UNIFORM_ALPHAGEN, UNIFORM_ALPHATEST, UNIFORM_AMBIENTLIGHT, UNIFORM_BASECOLOR, UNIFORM_BONEMATRIX, UNIFORM_COLORGEN, UNIFORM_CUBEMAPINFO, UNIFORM_DEFORMGEN, UNIFORM_DEFORMPARAMS, UNIFORM_DIFFUSETEXMATRIX, UNIFORM_DIFFUSETEXOFFTURB, UNIFORM_DIRECTEDLIGHT, UNIFORM_ENABLETEXTURES, UNIFORM_FOGCOLORMASK, UNIFORM_FOGDEPTH, UNIFORM_FOGDISTANCE, UNIFORM_FOGEYET, UNIFORM_LIGHTORIGIN, UNIFORM_LIGHTRADIUS, UNIFORM_LOCALVIEWORIGIN, UNIFORM_MODELLIGHTDIR, UNIFORM_MODELMATRIX, UNIFORM_MODELVIEWPROJECTIONMATRIX, UNIFORM_NORMALSCALE, UNIFORM_PORTALRANGE, UNIFORM_PRIMARYLIGHTAMBIENT, UNIFORM_PRIMARYLIGHTCOLOR, UNIFORM_PRIMARYLIGHTORIGIN, UNIFORM_SPECULARSCALE, UNIFORM_TCGEN0, UNIFORM_TCGEN0VECTOR0, UNIFORM_TCGEN0VECTOR1, UNIFORM_TIME, UNIFORM_VERTCOLOR, UNIFORM_VERTEXLERP, UNIFORM_VIEWORIGIN, Vector4Copy, VectorCopy, VectorScale, VectorScale4, VectorSet4, VectorSubtract, glstate_t::vertexAnimation, glstate_t::vertexAttribsInterpolation, orientationr_t::viewOrigin, backEndState_t::viewParms, trGlobals_t::viewParms, VPF_NOCUBEMAPS, VPF_USESUNLIGHT, trGlobals_t::whiteImage, trGlobals_t::worldEntity, and shaderCommands_s::xstages.
Referenced by RB_StageIteratorGeneric().
RB_RenderShadowmap()
static void RB_RenderShadowmap (shaderCommands_t * input) static
Definition at line 1393 of file tr_shade.c.
 {
     int deformGen;
     vec5_t deformParams;
     ComputeDeformValues(&deformGen, deformParams);
     {
         shaderProgram_t *sp = &tr.shadowmapShader[0];
         if (glState.vertexAnimation)
         {
             sp = &tr.shadowmapShader[SHADOWMAPDEF_USE_VERTEX_ANIMATION];
         }
         else if (glState.boneAnimation)
         {
             sp = &tr.shadowmapShader[SHADOWMAPDEF_USE_BONE_ANIMATION];
         }
         vec4_t vector;
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELMATRIX, backEnd.or.transformMatrix);
         GLSL_SetUniformFloat(sp, UNIFORM_VERTEXLERP, glState.vertexAttribsInterpolation);
         if (glState.boneAnimation)
         {
             GLSL_SetUniformMat4BoneMatrix(sp, UNIFORM_BONEMATRIX, glState.boneMatrix, glState.boneAnimation);
         }
         GLSL_SetUniformInt(sp, UNIFORM_DEFORMGEN, deformGen);
         if (deformGen != DGEN_NONE)
         {
             GLSL_SetUniformFloat5(sp, UNIFORM_DEFORMPARAMS, deformParams);
             GLSL_SetUniformFloat(sp, UNIFORM_TIME, tess.shaderTime);
         }
         VectorCopy(backEnd.viewParms.or.origin, vector);
         vector[3] = 1.0f;
         GLSL_SetUniformVec4(sp, UNIFORM_LIGHTORIGIN, vector);
         GLSL_SetUniformFloat(sp, UNIFORM_LIGHTRADIUS, backEnd.viewParms.zFar);
         GL_State( 0 );
         GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 0);
         //
         // do multitexture
         //
         //if ( pStage->glslShaderGroup )
         {
             //
             // draw
             //
             R_DrawElements(input->numIndexes, input->firstIndex);
         }
     }
 }
References backEnd, glstate_t::boneAnimation, glstate_t::boneMatrix, ComputeDeformValues(), DGEN_NONE, shaderCommands_s::firstIndex, GL_State(), GLSL_BindProgram(), GLSL_SetUniformFloat(), GLSL_SetUniformFloat5(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformMat4BoneMatrix(), GLSL_SetUniformVec4(), glState, glstate_t::modelviewProjection, shaderCommands_s::numIndexes, viewParms_t::or, backEndState_t::or, orientationr_t::origin, R_DrawElements(), shaderCommands_s::shaderTime, SHADOWMAPDEF_USE_BONE_ANIMATION, SHADOWMAPDEF_USE_VERTEX_ANIMATION, trGlobals_t::shadowmapShader, tess, tr, orientationr_t::transformMatrix, UNIFORM_ALPHATEST, UNIFORM_BONEMATRIX, UNIFORM_DEFORMGEN, UNIFORM_DEFORMPARAMS, UNIFORM_LIGHTORIGIN, UNIFORM_LIGHTRADIUS, UNIFORM_MODELMATRIX, UNIFORM_MODELVIEWPROJECTIONMATRIX, UNIFORM_TIME, UNIFORM_VERTEXLERP, VectorCopy, glstate_t::vertexAnimation, glstate_t::vertexAttribsInterpolation, backEndState_t::viewParms, and viewParms_t::zFar.
Referenced by RB_StageIteratorGeneric().
RB_StageIteratorGeneric()
void RB_StageIteratorGeneric (void)
Definition at line 1461 of file tr_shade.c.
 {
     shaderCommands_t *input;
     unsigned int vertexAttribs = 0;
     input = &tess;
     if (!input->numVertexes || !input->numIndexes)
     {
         return;
     }
     if (tess.useInternalVao)
     {
         RB_DeformTessGeometry();
     }
     vertexAttribs = RB_CalcShaderVertexAttribs( input );
     if (tess.useInternalVao)
     {
         RB_UpdateTessVao(vertexAttribs);
     }
     else
     {
         backEnd.pc.c_staticVaoDraws++;
     }
     //
     // log this call
     //
     if ( r_logFile->integer )
     {
         // don't just call LogComment, or we will get
         // a call to va() every frame!
         GLimp_LogComment( va("--- RB_StageIteratorGeneric( %s ) ---\n", tess.shader->name) );
     }
     //
     // set face culling appropriately
     //
     if (input->shader->cullType == CT_TWO_SIDED)
     {
         GL_Cull( CT_TWO_SIDED );
     }
     else
     {
         qboolean cullFront = (input->shader->cullType == CT_FRONT_SIDED);
         if ( backEnd.viewParms.flags & VPF_DEPTHSHADOW )
             cullFront = !cullFront;
         if ( backEnd.viewParms.isMirror )
             cullFront = !cullFront;
         if ( backEnd.currentEntity && backEnd.currentEntity->mirrored )
             cullFront = !cullFront;
         if (cullFront)
             GL_Cull( CT_FRONT_SIDED );
         else
             GL_Cull( CT_BACK_SIDED );
     }
     // set polygon offset if necessary
     if ( input->shader->polygonOffset )
     {
         qglEnable( GL_POLYGON_OFFSET_FILL );
     }
     //
     // render depth if in depthfill mode
     //
     if (backEnd.depthFill)
     {
         RB_IterateStagesGeneric( input );
         //
         // reset polygon offset
         //
         if ( input->shader->polygonOffset )
         {
             qglDisable( GL_POLYGON_OFFSET_FILL );
         }
         return;
     }
     //
     // render shadowmap if in shadowmap mode
     //
     if (backEnd.viewParms.flags & VPF_SHADOWMAP)
     {
         if ( input->shader->sort == SS_OPAQUE )
         {
             RB_RenderShadowmap( input );
         }
         //
         // reset polygon offset
         //
         if ( input->shader->polygonOffset )
         {
             qglDisable( GL_POLYGON_OFFSET_FILL );
         }
         return;
     }
     //
     //
     // call shader function
     //
     RB_IterateStagesGeneric( input );
     //
     // pshadows!
     //
     if (glRefConfig.framebufferObject && r_shadows->integer == 4 && tess.pshadowBits
         && tess.shader->sort <= SS_OPAQUE && !(tess.shader->surfaceFlags & (SURF_NODLIGHT | SURF_SKY) ) ) {
         ProjectPshadowVBOGLSL();
     }
     //
     // now do any dynamic lighting needed
     //
     if ( tess.dlightBits && tess.shader->sort <= SS_OPAQUE && r_lightmap->integer == 0
         && !(tess.shader->surfaceFlags & (SURF_NODLIGHT | SURF_SKY) ) ) {
         if (tess.shader->numUnfoggedPasses == 1 && tess.xstages[0]->glslShaderGroup == tr.lightallShader
             && (tess.xstages[0]->glslShaderIndex & LIGHTDEF_LIGHTTYPE_MASK) && r_dlightMode->integer)
         {
             ForwardDlight();
         }
         else
         {
             ProjectDlightTexture();
         }
     }
     //
     // now do fog
     //
     if ( tess.fogNum && tess.shader->fogPass ) {
         RB_FogPass();
     }
     //
     // reset polygon offset
     //
     if ( input->shader->polygonOffset )
     {
         qglDisable( GL_POLYGON_OFFSET_FILL );
     }
 }
References backEnd, backEndCounters_t::c_staticVaoDraws, CT_BACK_SIDED, CT_FRONT_SIDED, CT_TWO_SIDED, shader_s::cullType, backEndState_t::currentEntity, backEndState_t::depthFill, shaderCommands_s::dlightBits, viewParms_t::flags, shaderCommands_s::fogNum, shader_s::fogPass, ForwardDlight(), glRefConfig_t::framebufferObject, GL_Cull(), GLimp_LogComment(), glRefConfig, shaderStage_t::glslShaderGroup, shaderStage_t::glslShaderIndex, cvar_s::integer, viewParms_t::isMirror, trGlobals_t::lightallShader, LIGHTDEF_LIGHTTYPE_MASK, trRefEntity_t::mirrored, shader_s::name, shaderCommands_s::numIndexes, shader_s::numUnfoggedPasses, shaderCommands_s::numVertexes, backEndState_t::pc, shader_s::polygonOffset, ProjectDlightTexture(), ProjectPshadowVBOGLSL(), shaderCommands_s::pshadowBits, r_dlightMode, r_lightmap, r_logFile, r_shadows, RB_CalcShaderVertexAttribs(), RB_DeformTessGeometry(), RB_FogPass(), RB_IterateStagesGeneric(), RB_RenderShadowmap(), RB_UpdateTessVao(), shaderCommands_s::shader, shader_s::sort, SS_OPAQUE, SURF_NODLIGHT, SURF_SKY, shader_s::surfaceFlags, tess, tr, shaderCommands_s::useInternalVao, va(), backEndState_t::viewParms, VPF_DEPTHSHADOW, VPF_SHADOWMAP, and shaderCommands_s::xstages.
Referenced by ComputeStageIteratorFunc(), R_ShaderList_f(), RB_BeginSurface(), and RB_StageIteratorSky().
Variable Documentation
tess
shaderCommands_t tess
Definition at line 55 of file tr_shade.c.
Referenced by Autosprite2Deform(), AutospriteDeform(), ComputeDeformValues(), ComputeFogValues(), ComputeShaderColors(), ComputeTexMods(), DeformText(), DoRailCore(), DoRailDiscs(), DrawSkySide(), FillCloudySkySide(), ForwardDlight(), GLSL_GetGenericShaderProgram(), LerpMeshVertexes(), ProjectDlightTexture(), ProjectPshadowVBOGLSL(), R_BindAnimatedImageToTMU(), R_BindVao(), R_BuildCloudData(), R_Init(), R_InitVaos(), R_RenderShadowEdges(), RB_AddQuadStampExt(), RB_BeginSurface(), RB_CalcBulgeVertexes(), RB_CalcDeformNormals(), RB_CalcDeformVertexes(), RB_CalcFogTexCoords(), RB_CalcModulateColorsByFog(), RB_CalcMoveVertexes(), RB_CalcRotateTexMatrix(), RB_CalcScrollTexMatrix(), RB_CalcTurbulentFactors(), RB_CalcWaveColorSingle(), RB_CapShadowMap(), RB_CheckOverflow(), RB_CheckVao(), RB_ClearDepth(), RB_ColorMask(), RB_DeformTessGeometry(), RB_DrawBuffer(), RB_DrawSurfs(), RB_EndSurface(), RB_ExecuteRenderCommands(), RB_ExportCubemaps(), RB_FogPass(), RB_InstantQuad2(), RB_IQMSurfaceAnim(), RB_IQMSurfaceAnimVao(), RB_IterateStagesGeneric(), RB_MDRSurfaceAnim(), RB_PostProcess(), RB_ProjectionShadowDeform(), RB_RenderDrawSurfList(), RB_RenderFlare(), RB_RenderShadowmap(), RB_ShadowTessEnd(), RB_StageIteratorGeneric(), RB_StageIteratorSky(), RB_StretchPic(), RB_SurfaceBeam(), RB_SurfaceFlare(), RB_SurfaceGrid(), RB_SurfaceMesh(), RB_SurfacePolychain(), RB_SurfaceVaoCached(), RB_SurfaceVaoMdvMesh(), RB_SurfaceVertsAndIndexes(), RB_SwapBuffers(), RB_TakeScreenshotCmd(), RB_TakeVideoFrameCmd(), RB_UpdateTessVao(), RE_StretchRaw(), SurfIsOffscreen(), TableForFunc(), Vao_SetVertexPointers(), and VaoCache_Commit().