ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/huffman.c File Reference
huffman.c File Reference
#include "q_shared.h"
#include "qcommon.h"
Functions
void Huff_putBit (int bit, byte *fout, int *offset)
int Huff_getBloc (void)
void Huff_setBloc (int _bloc)
int Huff_getBit (byte *fin, int *offset)
static void add_bit (char bit, byte *fout)
static int get_bit (byte *fin)
static node_t ** get_ppnode (huff_t *huff)
static void free_ppnode (huff_t *huff, node_t **ppnode)
static void swap (huff_t *huff, node_t *node1, node_t *node2)
static void swaplist (node_t *node1, node_t *node2)
static void increment (huff_t *huff, node_t *node)
void Huff_addRef (huff_t *huff, byte ch)
int Huff_Receive (node_t *node, int *ch, byte *fin)
void Huff_offsetReceive (node_t *node, int *ch, byte *fin, int *offset, int maxoffset)
static void send (node_t *node, node_t *child, byte *fout, int maxoffset)
void Huff_transmit (huff_t *huff, int ch, byte *fout, int maxoffset)
void Huff_offsetTransmit (huff_t *huff, int ch, byte *fout, int *offset, int maxoffset)
void Huff_Decompress (msg_t *mbuf, int offset)
void Huff_Compress (msg_t *mbuf, int offset)
void Huff_Init (huffman_t *huff)
Variables
static int bloc = 0
int oldsize
Function Documentation
add_bit()
static void add_bit (char bit, byte * fout) static
Definition at line 62 of file huffman.c.
{
     if ((bloc&7) == 0) {
         fout[(bloc>>3)] = 0;
     }
     fout[(bloc>>3)] |= bit << (bloc&7);
     bloc++;
 }
Referenced by Huff_transmit(), and send().
free_ppnode()
static void free_ppnode (huff_t * huff, node_t ** ppnode) static
Definition at line 89 of file huffman.c.
{
     *ppnode = (node_t *)huff->freelist;
     huff->freelist = ppnode;
 }
Referenced by increment().
get_bit()
static int get_bit (byte * fin) static
Definition at line 71 of file huffman.c.
{
     int t;
     t = (fin[(bloc>>3)] >> (bloc&7)) & 0x1;
     bloc++;
     return t;
 }
Referenced by Huff_Decompress(), Huff_offsetReceive(), and Huff_Receive().
get_ppnode()
static node_t** get_ppnode (huff_t * huff) static
Definition at line 78 of file huffman.c.
{
     node_t **tppnode;
     if (!huff->freelist) {
         return &(huff->nodePtrs[huff->blocPtrs++]);
     } else {
         tppnode = huff->freelist;
         huff->freelist = (node_t **)*tppnode;
         return tppnode;
     }
 }
Referenced by Huff_addRef(), and increment().
Huff_addRef()
void Huff_addRef (huff_t * huff, byte ch)
Definition at line 196 of file huffman.c.
{
     node_t *tnode, *tnode2;
     if (huff->loc[ch] == NULL) { /* if this is the first transmission of this node */
         tnode = &(huff->nodeList[huff->blocNode++]);
         tnode2 = &(huff->nodeList[huff->blocNode++]);
         tnode2->symbol = INTERNAL_NODE;
         tnode2->weight = 1;
         tnode2->next = huff->lhead->next;
         if (huff->lhead->next) {
             huff->lhead->next->prev = tnode2;
             if (huff->lhead->next->weight == 1) {
                 tnode2->head = huff->lhead->next->head;
             } else {
                 tnode2->head = get_ppnode(huff);
                 *tnode2->head = tnode2;
             }
         } else {
             tnode2->head = get_ppnode(huff);
             *tnode2->head = tnode2;
         }
         huff->lhead->next = tnode2;
         tnode2->prev = huff->lhead;
         tnode->symbol = ch;
         tnode->weight = 1;
         tnode->next = huff->lhead->next;
         if (huff->lhead->next) {
             huff->lhead->next->prev = tnode;
             if (huff->lhead->next->weight == 1) {
                 tnode->head = huff->lhead->next->head;
             } else {
                 /* this should never happen */
                 tnode->head = get_ppnode(huff);
                 *tnode->head = tnode2;
             }
         } else {
             /* this should never happen */
             tnode->head = get_ppnode(huff);
             *tnode->head = tnode;
         }
         huff->lhead->next = tnode;
         tnode->prev = huff->lhead;
         tnode->left = tnode->right = NULL;
         if (huff->lhead->parent) {
             if (huff->lhead->parent->left == huff->lhead) { /* lhead is guaranteed to by the NYT */
                 huff->lhead->parent->left = tnode2;
             } else {
                 huff->lhead->parent->right = tnode2;
             }
         } else {
             huff->tree = tnode2;
         }
         tnode2->right = tnode;
         tnode2->left = huff->lhead;
         tnode2->parent = huff->lhead->parent;
         huff->lhead->parent = tnode->parent = tnode2;
         huff->loc[ch] = tnode;
         increment(huff, tnode2->parent);
     } else {
         increment(huff, huff->loc[ch]);
     }
 }
Referenced by Huff_Compress(), Huff_Decompress(), and MSG_initHuffman().
Huff_Compress()
void Huff_Compress (msg_t * mbuf, int offset)
Definition at line 397 of file huffman.c.
{
     int         i, ch, size;
     byte        seq[65536];
     byte*       buffer;
     huff_t      huff;
     size = mbuf->cursize - offset;
     buffer = mbuf->data + offset;
     if (size<=0) {
         return;
     }
     Com_Memset(&huff, 0, sizeof(huff_t));
     // Add the NYT (not yet transmitted) node into the tree/list */
     huff.tree = huff.lhead = huff.loc[NYT] =  &(huff.nodeList[huff.blocNode++]);
     huff.tree->symbol = NYT;
     huff.tree->weight = 0;
     huff.lhead->next = huff.lhead->prev = NULL;
     huff.tree->parent = huff.tree->left = huff.tree->right = NULL;
     seq[0] = (size>>8);
     seq[1] = size&0xff;
     bloc = 16;
     for (i=0; i<size; i++ ) {
         ch = buffer[i];
         Huff_transmit(&huff, ch, seq, size<<3);                     /* Transmit symbol */
         Huff_addRef(&huff, (byte)ch);                               /* Do update */
     }
     bloc += 8;                                              // next byte
     mbuf->cursize = (bloc>>3) + offset;
     Com_Memcpy(mbuf->data+offset, seq, (bloc>>3));
 }
Referenced by NET_OutOfBandData().
Huff_Decompress()
void Huff_Decompress (msg_t * mbuf, int offset)
Definition at line 343 of file huffman.c.
{
     int         ch, cch, i, j, size;
     byte        seq[65536];
     byte*       buffer;
     huff_t      huff;
     size = mbuf->cursize - offset;
     buffer = mbuf->data + offset;
     if ( size <= 0 ) {
         return;
     }
     Com_Memset(&huff, 0, sizeof(huff_t));
     // Initialize the tree & list with the NYT node
     huff.tree = huff.lhead = huff.ltail = huff.loc[NYT] = &(huff.nodeList[huff.blocNode++]);
     huff.tree->symbol = NYT;
     huff.tree->weight = 0;
     huff.lhead->next = huff.lhead->prev = NULL;
     huff.tree->parent = huff.tree->left = huff.tree->right = NULL;
     cch = buffer[0]*256 + buffer[1];
     // don't overflow with bad messages
     if ( cch > mbuf->maxsize - offset ) {
         cch = mbuf->maxsize - offset;
     }
     bloc = 16;
     for ( j = 0; j < cch; j++ ) {
         ch = 0;
         // don't overflow reading from the messages
         // FIXME: would it be better to have an overflow check in get_bit ?
         if ( (bloc >> 3) > size ) {
             seq[j] = 0;
             break;
         }
         Huff_Receive(huff.tree, &ch, buffer);               /* Get a character */
         if ( ch == NYT ) {                              /* We got a NYT, get the symbol associated with it */
             ch = 0;
             for ( i = 0; i < 8; i++ ) {
                 ch = (ch<<1) + get_bit(buffer);
             }
         }
         seq[j] = ch;                                    /* Write symbol */
         Huff_addRef(&huff, (byte)ch);                               /* Increment node */
     }
     mbuf->cursize = cch + offset;
     Com_Memcpy(mbuf->data + offset, seq, cch);
 }
Referenced by SV_ConnectionlessPacket().
Huff_getBit()
int Huff_getBit (byte * fin, int * offset)
Definition at line 52 of file huffman.c.
{
     int t;
     bloc = *offset;
     t = (fin[(bloc>>3)] >> (bloc&7)) & 0x1;
     bloc++;
     *offset = bloc;
     return t;
 }
Referenced by MSG_ReadBits().
Huff_getBloc()
int Huff_getBloc (void)
Definition at line 42 of file huffman.c.
 {
     return bloc;
 }
Referenced by MSG_LookaheadByte().
Huff_Init()
void Huff_Init (huffman_t * huff)
Definition at line 435 of file huffman.c.
{
     Com_Memset(&huff->compressor, 0, sizeof(huff_t));
     Com_Memset(&huff->decompressor, 0, sizeof(huff_t));
     // Initialize the tree & list with the NYT node
     huff->decompressor.tree = huff->decompressor.lhead = huff->decompressor.ltail = huff->decompressor.loc[NYT] = &(huff->decompressor.nodeList[huff->decompressor.blocNode++]);
     huff->decompressor.tree->symbol = NYT;
     huff->decompressor.tree->weight = 0;
     huff->decompressor.lhead->next = huff->decompressor.lhead->prev = NULL;
     huff->decompressor.tree->parent = huff->decompressor.tree->left = huff->decompressor.tree->right = NULL;
     // Add the NYT (not yet transmitted) node into the tree/list */
     huff->compressor.tree = huff->compressor.lhead = huff->compressor.loc[NYT] =  &(huff->compressor.nodeList[huff->compressor.blocNode++]);
     huff->compressor.tree->symbol = NYT;
     huff->compressor.tree->weight = 0;
     huff->compressor.lhead->next = huff->compressor.lhead->prev = NULL;
     huff->compressor.tree->parent = huff->compressor.tree->left = huff->compressor.tree->right = NULL;
 }
Referenced by MSG_initHuffman().
Huff_offsetReceive()
void Huff_offsetReceive (node_t * node, int * ch, byte * fin, int * offset, int maxoffset)
Definition at line 282 of file huffman.c.
{
     bloc = *offset;
     while (node && node->symbol == INTERNAL_NODE) {
         if (bloc >= maxoffset) {
             *ch = 0;
             *offset = maxoffset + 1;
             return;
         }
         if (get_bit(fin)) {
             node = node->right;
         } else {
             node = node->left;
         }
     }
     if (!node) {
         *ch = 0;
         return;
 //      Com_Error(ERR_DROP, "Illegal tree!");
     }
     *ch = node->symbol;
     *offset = bloc;
 }
Referenced by MSG_ReadBits().
Huff_offsetTransmit()
void Huff_offsetTransmit (huff_t * huff, int ch, byte * fout, int * offset, int maxoffset)
Definition at line 337 of file huffman.c.
{
     bloc = *offset;
     send(huff->loc[ch], NULL, fout, maxoffset);
     *offset = bloc;
 }
Referenced by MSG_WriteBits().
Huff_putBit()
void Huff_putBit (int bit, byte * fout, int * offset)
Definition at line 32 of file huffman.c.
{
     bloc = *offset;
     if ((bloc&7) == 0) {
         fout[(bloc>>3)] = 0;
     }
     fout[(bloc>>3)] |= bit << (bloc&7);
     bloc++;
     *offset = bloc;
 }
Referenced by MSG_WriteBits().
Huff_Receive()
int Huff_Receive (node_t * node, int * ch, byte * fin)
Definition at line 266 of file huffman.c.
{
     while (node && node->symbol == INTERNAL_NODE) {
         if (get_bit(fin)) {
             node = node->right;
         } else {
             node = node->left;
         }
     }
     if (!node) {
         return 0;
 //      Com_Error(ERR_DROP, "Illegal tree!");
     }
     return (*ch = node->symbol);
 }
Referenced by Huff_Decompress().
Huff_setBloc()
void Huff_setBloc (int _bloc)
Definition at line 47 of file huffman.c.
 {
     bloc = _bloc;
 }
Referenced by MSG_LookaheadByte().
Huff_transmit()
void Huff_transmit (huff_t * huff, int ch, byte * fout, int maxoffset)
Definition at line 324 of file huffman.c.
{
     int i;
     if (huff->loc[ch] == NULL) {
         /* node_t hasn't been transmitted, send a NYT, then the symbol */
         Huff_transmit(huff, NYT, fout, maxoffset);
         for (i = 7; i >= 0; i--) {
             add_bit((char)((ch >> i) & 0x1), fout);
         }
     } else {
         send(huff->loc[ch], NULL, fout, maxoffset);
     }
 }
Referenced by Huff_Compress(), and Huff_transmit().
increment()
static void increment (huff_t * huff, node_t * node) static
Definition at line 158 of file huffman.c.
{
     node_t *lnode;
     if (!node) {
         return;
     }
     if (node->next != NULL && node->next->weight == node->weight) {
         lnode = *node->head;
         if (lnode != node->parent) {
             swap(huff, lnode, node);
         }
         swaplist(lnode, node);
     }
     if (node->prev && node->prev->weight == node->weight) {
         *node->head = node->prev;
     } else {
         *node->head = NULL;
         free_ppnode(huff, node->head);
     }
     node->weight++;
     if (node->next && node->next->weight == node->weight) {
         node->head = node->next->head;
     } else {
         node->head = get_ppnode(huff);
         *node->head = node;
     }
     if (node->parent) {
         increment(huff, node->parent);
         if (node->prev == node->parent) {
             swaplist(node, node->parent);
             if (*node->head == node) {
                 *node->head = node->parent;
             }
         }
     }
 }
Referenced by Huff_addRef().
send()
static void send (node_t * node, node_t * child, byte * fout, int maxoffset) static
Definition at line 306 of file huffman.c.
{
     if (node->parent) {
         send(node->parent, node, fout, maxoffset);
     }
     if (child) {
         if (bloc >= maxoffset) {
             bloc = maxoffset + 1;
             return;
         }
         if (node->right == child) {
             add_bit(1, fout);
         } else {
             add_bit(0, fout);
         }
     }
 }
Referenced by Huff_offsetTransmit(), Huff_transmit(), NET_OpenSocks(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
swap()
static void swap (huff_t * huff, node_t * node1, node_t * node2) static
Definition at line 95 of file huffman.c.
{
     node_t *par1, *par2;
     par1 = node1->parent;
     par2 = node2->parent;
     if (par1) {
         if (par1->left == node1) {
             par1->left = node2;
         } else {
           par1->right = node2;
         }
     } else {
         huff->tree = node2;
     }
     if (par2) {
         if (par2->left == node2) {
             par2->left = node1;
         } else {
             par2->right = node1;
         }
     } else {
         huff->tree = node1;
     }
     node1->parent = par2;
     node2->parent = par1;
 }
Referenced by Hunk_SwapBanks(), increment(), R_RenderPshadowMaps(), and RawImage_SwizzleRA().
swaplist()
static void swaplist (node_t * node1, node_t * node2) static
Definition at line 126 of file huffman.c.
{
     node_t *par1;
     par1 = node1->next;
     node1->next = node2->next;
     node2->next = par1;
     par1 = node1->prev;
     node1->prev = node2->prev;
     node2->prev = par1;
     if (node1->next == node1) {
         node1->next = node2;
     }
     if (node2->next == node2) {
         node2->next = node1;
     }
     if (node1->next) {
         node1->next->prev = node1;
     }
     if (node2->next) {
         node2->next->prev = node2;
     }
     if (node1->prev) {
         node1->prev->next = node1;
     }
     if (node2->prev) {
         node2->prev->next = node2;
     }
 }
Referenced by increment().
Variable Documentation
bloc
int bloc = 0 static
Definition at line 30 of file huffman.c.
Referenced by add_bit(), get_bit(), Huff_Compress(), Huff_Decompress(), Huff_getBit(), Huff_getBloc(), Huff_offsetReceive(), Huff_offsetTransmit(), Huff_putBit(), Huff_setBloc(), MSG_LookaheadByte(), and send().
oldsize
int oldsize
Definition at line 40 of file msg.c.
Referenced by MSG_WriteBits(), MSG_WriteDeltaEntity(), MSG_WriteDeltaPlayerstate(), and MSG_WriteDeltaUsercmdKey().