ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/ai_main.c File Reference
ai_main.c File Reference
#include "g_local.h"
#include "../qcommon/q_shared.h"
#include "../botlib/botlib.h"
#include "../botlib/be_aas.h"
#include "../botlib/be_ea.h"
#include "../botlib/be_ai_char.h"
#include "../botlib/be_ai_chat.h"
#include "../botlib/be_ai_gen.h"
#include "../botlib/be_ai_goal.h"
#include "../botlib/be_ai_move.h"
#include "../botlib/be_ai_weap.h"
#include "ai_main.h"
#include "ai_dmq3.h"
#include "ai_chat.h"
#include "ai_cmd.h"
#include "ai_dmnet.h"
#include "ai_vcmd.h"
#include "chars.h"
#include "inv.h"
#include "syn.h"
Functions
void ExitLevel (void)
void QDECL BotAI_Print (int type, char *fmt,...)
void BotAI_Trace (bsp_trace_t *bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
int BotAI_GetClientState (int clientNum, playerState_t *state)
int BotAI_GetEntityState (int entityNum, entityState_t *state)
int BotAI_GetSnapshotEntity (int clientNum, int sequence, entityState_t *state)
void QDECL BotAI_BotInitialChat (bot_state_t *bs, char *type,...)
void BotTestAAS (vec3_t origin)
void BotReportStatus (bot_state_t *bs)
void BotTeamplayReport (void)
void BotSetInfoConfigString (bot_state_t *bs)
void BotUpdateInfoConfigStrings (void)
void BotInterbreedBots (void)
void BotWriteInterbreeded (char *filename)
void BotInterbreedEndMatch (void)
void BotInterbreeding (void)
void BotEntityInfo (int entnum, aas_entityinfo_t *info)
int NumBots (void)
int BotTeamLeader (bot_state_t *bs)
float AngleDifference (float ang1, float ang2)
float BotChangeViewAngle (float angle, float ideal_angle, float speed)
void BotChangeViewAngles (bot_state_t *bs, float thinktime)
void BotInputToUserCommand (bot_input_t *bi, usercmd_t *ucmd, int delta_angles[3], int time)
void BotUpdateInput (bot_state_t *bs, int time, int elapsed_time)
void BotAIRegularUpdate (void)
void RemoveColorEscapeSequences (char *text)
int BotAI (int client, float thinktime)
void BotScheduleBotThink (void)
void BotWriteSessionData (bot_state_t *bs)
void BotReadSessionData (bot_state_t *bs)
int BotAISetupClient (int client, struct bot_settings_s *settings, qboolean restart)
int BotAIShutdownClient (int client, qboolean restart)
void BotResetState (bot_state_t *bs)
int BotAILoadMap (int restart)
int BotAIStartFrame (int time)
int BotInitLibrary (void)
int BotAISetup (int restart)
int BotAIShutdown (int restart)
Variables
bot_state_t * botstates [MAX_CLIENTS]
int numbots
float floattime
float regularupdate_time
int bot_interbreed
int bot_interbreedmatchcount
vmCvar_t bot_thinktime
vmCvar_t bot_memorydump
vmCvar_t bot_saveroutingcache
vmCvar_t bot_pause
vmCvar_t bot_report
vmCvar_t bot_testsolid
vmCvar_t bot_testclusters
vmCvar_t bot_developer
vmCvar_t bot_interbreedchar
vmCvar_t bot_interbreedbots
vmCvar_t bot_interbreedcycle
vmCvar_t bot_interbreedwrite
Function Documentation
AngleDifference()
float AngleDifference (float ang1, float ang2)
Definition at line 715 of file ai_main.c.
{
     float diff;
     diff = ang1 - ang2;
     if (ang1 > ang2) {
         if (diff > 180.0) diff -= 360.0;
     }
     else {
         if (diff < -180.0) diff += 360.0;
     }
     return diff;
 }
Referenced by BotChangeViewAngles().
BotAI()
int BotAI (int client, float thinktime)
Definition at line 975 of file ai_main.c.
{
     bot_state_t *bs;
     char buf[1024], *args;
     int j;
     trap_EA_ResetInput(client);
     //
     bs = botstates[client];
     if (!bs || !bs->inuse) {
         BotAI_Print(PRT_FATAL, "BotAI: client %d is not setup\n", client);
         return qfalse;
     }
     //retrieve the current client state
     if (!BotAI_GetClientState(client, &bs->cur_ps)) {
         BotAI_Print(PRT_FATAL, "BotAI: failed to get player state for player %d\n", client);
         return qfalse;
     }
     //retrieve any waiting server commands
     while( trap_BotGetServerCommand(client, buf, sizeof(buf)) ) {
         //have buf point to the command and args to the command arguments
         args = strchr( buf, ' ');
         if (!args) continue;
         *args++ = '\0';
         //remove color espace sequences from the arguments
         RemoveColorEscapeSequences( args );
         if (!Q_stricmp(buf, "cp "))
             { /*CenterPrintf*/ }
         else if (!Q_stricmp(buf, "cs"))
             { /*ConfigStringModified*/ }
         else if (!Q_stricmp(buf, "print")) {
             //remove first and last quote from the chat message
             memmove(args, args+1, strlen(args));
             args[strlen(args)-1] = '\0';
             trap_BotQueueConsoleMessage(bs->cs, CMS_NORMAL, args);
         }
         else if (!Q_stricmp(buf, "chat")) {
             //remove first and last quote from the chat message
             memmove(args, args+1, strlen(args));
             args[strlen(args)-1] = '\0';
             trap_BotQueueConsoleMessage(bs->cs, CMS_CHAT, args);
         }
         else if (!Q_stricmp(buf, "tchat")) {
             //remove first and last quote from the chat message
             memmove(args, args+1, strlen(args));
             args[strlen(args)-1] = '\0';
             trap_BotQueueConsoleMessage(bs->cs, CMS_CHAT, args);
         }
 #ifdef MISSIONPACK
         else if (!Q_stricmp(buf, "vchat")) {
             BotVoiceChatCommand(bs, SAY_ALL, args);
         }
         else if (!Q_stricmp(buf, "vtchat")) {
             BotVoiceChatCommand(bs, SAY_TEAM, args);
         }
         else if (!Q_stricmp(buf, "vtell")) {
             BotVoiceChatCommand(bs, SAY_TELL, args);
         }
 #endif
         else if (!Q_stricmp(buf, "scores"))
             { /*FIXME: parse scores?*/ }
         else if (!Q_stricmp(buf, "clientLevelShot"))
             { /*ignore*/ }
     }
     //add the delta angles to the bot's current view angles
     for (j = 0; j < 3; j++) {
         bs->viewangles[j] = AngleMod(bs->viewangles[j] + SHORT2ANGLE(bs->cur_ps.delta_angles[j]));
     }
     //increase the local time of the bot
     bs->ltime += thinktime;
     //
     bs->thinktime = thinktime;
     //origin of the bot
     VectorCopy(bs->cur_ps.origin, bs->origin);
     //eye coordinates of the bot
     VectorCopy(bs->cur_ps.origin, bs->eye);
     bs->eye[2] += bs->cur_ps.viewheight;
     //get the area the bot is in
     bs->areanum = BotPointAreaNum(bs->origin);
     //the real AI
     BotDeathmatchAI(bs, thinktime);
     //set the weapon selection every AI frame
     trap_EA_SelectWeapon(bs->client, bs->weaponnum);
     //subtract the delta angles
     for (j = 0; j < 3; j++) {
         bs->viewangles[j] = AngleMod(bs->viewangles[j] - SHORT2ANGLE(bs->cur_ps.delta_angles[j]));
     }
     //everything was ok
     return qtrue;
 }
Referenced by BotAIStartFrame().
BotAI_BotInitialChat()
void QDECL BotAI_BotInitialChat (bot_state_t * bs, char * type, ...)
Definition at line 217 of file ai_main.c.
{
     int     i, mcontext;
     va_list ap;
     char    *p;
     char    *vars[MAX_MATCHVARIABLES];
     memset(vars, 0, sizeof(vars));
     va_start(ap, type);
     p = va_arg(ap, char *);
     for (i = 0; i < MAX_MATCHVARIABLES; i++) {
         if( !p ) {
             break;
         }
         vars[i] = p;
         p = va_arg(ap, char *);
     }
     va_end(ap);
     mcontext = BotSynonymContext(bs);
     trap_BotInitialChat( bs->cs, type, mcontext, vars[0], vars[1], vars[2], vars[3], vars[4], vars[5], vars[6], vars[7] );
 }
Referenced by BotChat_Death(), BotChat_EndLevel(), BotChat_EnemySuicide(), BotChat_EnterGame(), BotChat_ExitGame(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_HitTalking(), BotChat_Kill(), BotChat_Random(), BotChat_StartLevel(), BotChatTest(), BotCreateGroup(), BotCTFOrders_BothFlagsAtBase(), BotCTFOrders_BothFlagsNotAtBase(), BotCTFOrders_EnemyFlagNotAtBase(), BotCTFOrders_FlagNotAtBase(), BotGetLongTermGoal(), BotLongTermGoal(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_Dismiss(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_TaskPreference(), BotMatch_WhatAreYouDoing(), BotMatch_WhereAreYou(), BotMatch_WhichTeam(), BotTeamAI(), BotVoiceChat_Camp(), BotVoiceChat_FollowMe(), BotVoiceChat_Patrol(), BotVoiceChat_WantOnDefense(), BotVoiceChat_WantOnOffense(), and BotVoiceChat_WhoIsLeader().
BotAI_GetClientState()
int BotAI_GetClientState (int clientNum, playerState_t * state)
Definition at line 161 of file ai_main.c.
{
     gentity_t   *ent;
     ent = &g_entities[clientNum];
     if ( !ent->inuse ) {
         return qfalse;
     }
     if ( !ent->client ) {
         return qfalse;
     }
     memcpy( state, &ent->client->ps, sizeof(playerState_t) );
     return qtrue;
 }
Referenced by BotAI(), BotClientTravelTimeToGoal(), BotFirstClientInRankings(), BotIsFirstInRankings(), BotIsLastInRankings(), BotLastClientInRankings(), and EntityIsDead().
BotAI_GetEntityState()
int BotAI_GetEntityState (int entityNum, entityState_t * state)
Definition at line 181 of file ai_main.c.
{
     gentity_t   *ent;
     ent = &g_entities[entityNum];
     memset( state, 0, sizeof(entityState_t) );
     if (!ent->inuse) return qfalse;
     if (!ent->r.linked) return qfalse;
     if (ent->r.svFlags & SVF_NOCLIENT) return qfalse;
     memcpy( state, &ent->s, sizeof(entityState_t) );
     return qtrue;
 }
Referenced by BotAI_GetSnapshotEntity(), BotCheckSnapshot(), and BotClearPath().
BotAI_GetSnapshotEntity()
int BotAI_GetSnapshotEntity (int clientNum, int sequence, entityState_t * state)
Definition at line 198 of file ai_main.c.
{
     int     entNum;
     entNum = trap_BotGetSnapshotEntity( clientNum, sequence );
     if ( entNum == -1 ) {
         memset(state, 0, sizeof(entityState_t));
         return -1;
     }
     BotAI_GetEntityState( entNum, state );
     return sequence + 1;
 }
Referenced by BotCheckSnapshot().
BotAI_Print()
void QDECL BotAI_Print (int type, char * fmt, ...)
Definition at line 93 of file ai_main.c.
{
     char str[2048];
     va_list ap;
     va_start(ap, fmt);
     Q_vsnprintf(str, sizeof(str), fmt, ap);
     va_end(ap);
     switch(type) {
         case PRT_MESSAGE: {
             G_Printf("%s", str);
             break;
         }
         case PRT_WARNING: {
             G_Printf( S_COLOR_YELLOW "Warning: %s", str );
             break;
         }
         case PRT_ERROR: {
             G_Printf( S_COLOR_RED "Error: %s", str );
             break;
         }
         case PRT_FATAL: {
             G_Printf( S_COLOR_RED "Fatal: %s", str );
             break;
         }
         case PRT_EXIT: {
             G_Error( S_COLOR_RED "Exit: %s", str );
             break;
         }
         default: {
             G_Printf( "unknown print type\n" );
             break;
         }
     }
 }
Referenced by AINode_Battle_Fight(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), BotAI(), BotAIBlocked(), BotAISetupClient(), BotCheckConsoleMessages(), BotCheckEvents(), BotCreateWayPoint(), BotDeathmatchAI(), BotDumpNodeSwitches(), BotGetActivateGoal(), BotGetItemLongTermGoal(), BotGPSToPosition(), BotMatchMessage(), BotRecordNodeSwitch(), BotReportStatus(), BotSetupAlternativeRouteGoals(), BotSetupDeathmatchAI(), BotTeamplayReport(), BotTestAAS(), ClientName(), and ClientSkin().
BotAI_Trace()
void BotAI_Trace (bsp_trace_t * bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
Definition at line 135 of file ai_main.c.
{
     trace_t trace;
     trap_Trace(&trace, start, mins, maxs, end, passent, contentmask);
     //copy the trace information
     bsptrace->allsolid = trace.allsolid;
     bsptrace->startsolid = trace.startsolid;
     bsptrace->fraction = trace.fraction;
     VectorCopy(trace.endpos, bsptrace->endpos);
     bsptrace->plane.dist = trace.plane.dist;
     VectorCopy(trace.plane.normal, bsptrace->plane.normal);
     bsptrace->plane.signbits = trace.plane.signbits;
     bsptrace->plane.type = trace.plane.type;
     bsptrace->surface.value = 0;
     bsptrace->surface.flags = trace.surfaceFlags;
     bsptrace->ent = trace.entityNum;
     bsptrace->exp_dist = 0;
     bsptrace->sidenum = 0;
     bsptrace->contents = 0;
 }
Referenced by AINode_Seek_ActivateEntity(), BotAimAtEnemy(), BotCheckAttack(), BotClearPath(), BotEntityVisible(), BotFindEnemy(), BotFuncButtonActivateGoal(), BotGetAirGoal(), BotNearestVisibleItem(), BotRoamGoal(), and BotValidChatPosition().
BotAILoadMap()
int BotAILoadMap (int restart)
Definition at line 1371 of file ai_main.c.
{
     int         i;
     vmCvar_t    mapname;
     if (!restart) {
         trap_Cvar_Register( &mapname, "mapname", "", CVAR_SERVERINFO | CVAR_ROM );
         trap_BotLibLoadMap( mapname.string );
     }
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (botstates[i] && botstates[i]->inuse) {
             BotResetState( botstates[i] );
             botstates[i]->setupcount = 4;
         }
     }
     BotSetupDeathmatchAI();
     return qtrue;
 }
Referenced by G_InitGame().
BotAIRegularUpdate()
void BotAIRegularUpdate (void)
Definition at line 942 of file ai_main.c.
{
     if (regularupdate_time < FloatTime()) {
         trap_BotUpdateEntityItems();
         regularupdate_time = FloatTime() + 0.3;
     }
 }
Referenced by BotAIStartFrame().
BotAISetup()
int BotAISetup (int restart)
Definition at line 1666 of file ai_main.c.
{
     int         errnum;
     trap_Cvar_Register(&bot_thinktime, "bot_thinktime", "100", CVAR_CHEAT);
     trap_Cvar_Register(&bot_memorydump, "bot_memorydump", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_saveroutingcache, "bot_saveroutingcache", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_pause, "bot_pause", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_report, "bot_report", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_testsolid, "bot_testsolid", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_testclusters, "bot_testclusters", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_developer, "bot_developer", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_interbreedchar, "bot_interbreedchar", "", 0);
     trap_Cvar_Register(&bot_interbreedbots, "bot_interbreedbots", "10", 0);
     trap_Cvar_Register(&bot_interbreedcycle, "bot_interbreedcycle", "20", 0);
     trap_Cvar_Register(&bot_interbreedwrite, "bot_interbreedwrite", "", 0);
     //if the game is restarted for a tournament
     if (restart) {
         return qtrue;
     }
     //initialize the bot states
     memset( botstates, 0, sizeof(botstates) );
     errnum = BotInitLibrary();
     if (errnum != BLERR_NOERROR) return qfalse;
     return qtrue;
 }
Referenced by G_InitGame().
BotAISetupClient()
int BotAISetupClient (int client, struct bot_settings_s * settings, qboolean restart)
Definition at line 1172 of file ai_main.c.
{
     char filename[144], name[144], gender[144];
     bot_state_t *bs;
     int errnum;
     if (!botstates[client]) botstates[client] = G_Alloc(sizeof(bot_state_t));
     bs = botstates[client];
     if (!bs) {
         return qfalse;
     }
     if (bs && bs->inuse) {
         BotAI_Print(PRT_FATAL, "BotAISetupClient: client %d already setup\n", client);
         return qfalse;
     }
     if (!trap_AAS_Initialized()) {
         BotAI_Print(PRT_FATAL, "AAS not initialized\n");
         return qfalse;
     }
     //load the bot character
     bs->character = trap_BotLoadCharacter(settings->characterfile, settings->skill);
     if (!bs->character) {
         BotAI_Print(PRT_FATAL, "couldn't load skill %f from %s\n", settings->skill, settings->characterfile);
         return qfalse;
     }
     //copy the settings
     memcpy(&bs->settings, settings, sizeof(bot_settings_t));
     //allocate a goal state
     bs->gs = trap_BotAllocGoalState(client);
     //load the item weights
     trap_Characteristic_String(bs->character, CHARACTERISTIC_ITEMWEIGHTS, filename, sizeof(filename));
     errnum = trap_BotLoadItemWeights(bs->gs, filename);
     if (errnum != BLERR_NOERROR) {
         trap_BotFreeGoalState(bs->gs);
         return qfalse;
     }
     //allocate a weapon state
     bs->ws = trap_BotAllocWeaponState();
     //load the weapon weights
     trap_Characteristic_String(bs->character, CHARACTERISTIC_WEAPONWEIGHTS, filename, sizeof(filename));
     errnum = trap_BotLoadWeaponWeights(bs->ws, filename);
     if (errnum != BLERR_NOERROR) {
         trap_BotFreeGoalState(bs->gs);
         trap_BotFreeWeaponState(bs->ws);
         return qfalse;
     }
     //allocate a chat state
     bs->cs = trap_BotAllocChatState();
     //load the chat file
     trap_Characteristic_String(bs->character, CHARACTERISTIC_CHAT_FILE, filename, sizeof(filename));
     trap_Characteristic_String(bs->character, CHARACTERISTIC_CHAT_NAME, name, sizeof(name));
     errnum = trap_BotLoadChatFile(bs->cs, filename, name);
     if (errnum != BLERR_NOERROR) {
         trap_BotFreeChatState(bs->cs);
         trap_BotFreeGoalState(bs->gs);
         trap_BotFreeWeaponState(bs->ws);
         return qfalse;
     }
     //get the gender characteristic
     trap_Characteristic_String(bs->character, CHARACTERISTIC_GENDER, gender, sizeof(gender));
     //set the chat gender
     if (*gender == 'f' || *gender == 'F') trap_BotSetChatGender(bs->cs, CHAT_GENDERFEMALE);
     else if (*gender == 'm' || *gender == 'M') trap_BotSetChatGender(bs->cs, CHAT_GENDERMALE);
     else trap_BotSetChatGender(bs->cs, CHAT_GENDERLESS);
     bs->inuse = qtrue;
     bs->client = client;
     bs->entitynum = client;
     bs->setupcount = 4;
     bs->entergame_time = FloatTime();
     bs->ms = trap_BotAllocMoveState();
     bs->walker = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_WALKER, 0, 1);
     numbots++;
     if (trap_Cvar_VariableIntegerValue("bot_testichat")) {
         trap_BotLibVarSet("bot_testichat", "1");
         BotChatTest(bs);
     }
     //NOTE: reschedule the bot thinking
     BotScheduleBotThink();
     //if interbreeding start with a mutation
     if (bot_interbreed) {
         trap_BotMutateGoalFuzzyLogic(bs->gs, 1);
     }
     // if we kept the bot client
     if (restart) {
         BotReadSessionData(bs);
     }
     //bot has been setup successfully
     return qtrue;
 }
Referenced by G_BotConnect().
BotAIShutdown()
int BotAIShutdown (int restart)
Definition at line 1700 of file ai_main.c.
{
     int i;
     //if the game is restarted for a tournament
     if ( restart ) {
         //shutdown all the bots in the botlib
         for (i = 0; i < MAX_CLIENTS; i++) {
             if (botstates[i] && botstates[i]->inuse) {
                 BotAIShutdownClient(botstates[i]->client, restart);
             }
         }
         //don't shutdown the bot library
     }
     else {
         trap_BotLibShutdown();
     }
     return qtrue;
 }
Referenced by G_ShutdownGame().
BotAIShutdownClient()
int BotAIShutdownClient (int client, qboolean restart)
Definition at line 1272 of file ai_main.c.
{
     bot_state_t *bs;
     bs = botstates[client];
     if (!bs || !bs->inuse) {
         //BotAI_Print(PRT_ERROR, "BotAIShutdownClient: client %d already shutdown\n", client);
         return qfalse;
     }
     if (restart) {
         BotWriteSessionData(bs);
     }
     if (BotChat_ExitGame(bs)) {
         trap_BotEnterChat(bs->cs, bs->client, CHAT_ALL);
     }
     trap_BotFreeMoveState(bs->ms);
     //free the goal state
     trap_BotFreeGoalState(bs->gs);
     //free the chat file
     trap_BotFreeChatState(bs->cs);
     //free the weapon weights
     trap_BotFreeWeaponState(bs->ws);
     //free the bot character
     trap_BotFreeCharacter(bs->character);
     //
     BotFreeWaypoints(bs->checkpoints);
     BotFreeWaypoints(bs->patrolpoints);
     //clear activate goal stack
     BotClearActivateGoalStack(bs);
     //clear the bot state
     memset(bs, 0, sizeof(bot_state_t));
     //set the inuse flag to qfalse
     bs->inuse = qfalse;
     //there's one bot less
     numbots--;
     //everything went ok
     return qtrue;
 }
Referenced by BotAIShutdown(), BotInterbreeding(), and ClientDisconnect().
BotAIStartFrame()
int BotAIStartFrame (int time)
Definition at line 1401 of file ai_main.c.
{
     int i;
     gentity_t   *ent;
     bot_entitystate_t state;
     int elapsed_time, thinktime;
     static int local_time;
     static int botlib_residual;
     static int lastbotthink_time;
     G_CheckBotSpawn();
     trap_Cvar_Update(&bot_rocketjump);
     trap_Cvar_Update(&bot_grapple);
     trap_Cvar_Update(&bot_fastchat);
     trap_Cvar_Update(&bot_nochat);
     trap_Cvar_Update(&bot_testrchat);
     trap_Cvar_Update(&bot_thinktime);
     trap_Cvar_Update(&bot_memorydump);
     trap_Cvar_Update(&bot_saveroutingcache);
     trap_Cvar_Update(&bot_pause);
     trap_Cvar_Update(&bot_report);
     if (bot_report.integer) {
 //      BotTeamplayReport();
 //      trap_Cvar_Set("bot_report", "0");
         BotUpdateInfoConfigStrings();
     }
     if (bot_pause.integer) {
         // execute bot user commands every frame
         for( i = 0; i < MAX_CLIENTS; i++ ) {
             if( !botstates[i] || !botstates[i]->inuse ) {
                 continue;
             }
             if( g_entities[i].client->pers.connected != CON_CONNECTED ) {
                 continue;
             }
             botstates[i]->lastucmd.forwardmove = 0;
             botstates[i]->lastucmd.rightmove = 0;
             botstates[i]->lastucmd.upmove = 0;
             botstates[i]->lastucmd.buttons = 0;
             botstates[i]->lastucmd.serverTime = time;
             trap_BotUserCommand(botstates[i]->client, &botstates[i]->lastucmd);
         }
         return qtrue;
     }
     if (bot_memorydump.integer) {
         trap_BotLibVarSet("memorydump", "1");
         trap_Cvar_Set("bot_memorydump", "0");
     }
     if (bot_saveroutingcache.integer) {
         trap_BotLibVarSet("saveroutingcache", "1");
         trap_Cvar_Set("bot_saveroutingcache", "0");
     }
     //check if bot interbreeding is activated
     BotInterbreeding();
     //cap the bot think time
     if (bot_thinktime.integer > 200) {
         trap_Cvar_Set("bot_thinktime", "200");
     }
     //if the bot think time changed we should reschedule the bots
     if (bot_thinktime.integer != lastbotthink_time) {
         lastbotthink_time = bot_thinktime.integer;
         BotScheduleBotThink();
     }
     elapsed_time = time - local_time;
     local_time = time;
     botlib_residual += elapsed_time;
     if (elapsed_time > bot_thinktime.integer) thinktime = elapsed_time;
     else thinktime = bot_thinktime.integer;
     // update the bot library
     if ( botlib_residual >= thinktime ) {
         botlib_residual -= thinktime;
         trap_BotLibStartFrame((float) time / 1000);
         if (!trap_AAS_Initialized()) return qfalse;
         //update entities in the botlib
         for (i = 0; i < MAX_GENTITIES; i++) {
             ent = &g_entities[i];
             if (!ent->inuse) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             if (!ent->r.linked) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             if (ent->r.svFlags & SVF_NOCLIENT) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             // do not update missiles
             if (ent->s.eType == ET_MISSILE && ent->s.weapon != WP_GRAPPLING_HOOK) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             // do not update event only entities
             if (ent->s.eType > ET_EVENTS) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
 #ifdef MISSIONPACK
             // never link prox mine triggers
             if (ent->r.contents == CONTENTS_TRIGGER) {
                 if (ent->touch == ProximityMine_Trigger) {
                     trap_BotLibUpdateEntity(i, NULL);
                     continue;
                 }
             }
 #endif
             //
             memset(&state, 0, sizeof(bot_entitystate_t));
             //
             VectorCopy(ent->r.currentOrigin, state.origin);
             if (i < MAX_CLIENTS) {
                 VectorCopy(ent->s.apos.trBase, state.angles);
             } else {
                 VectorCopy(ent->r.currentAngles, state.angles);
             }
             VectorCopy(ent->s.origin2, state.old_origin);
             VectorCopy(ent->r.mins, state.mins);
             VectorCopy(ent->r.maxs, state.maxs);
             state.type = ent->s.eType;
             state.flags = ent->s.eFlags;
             if (ent->r.bmodel) state.solid = SOLID_BSP;
             else state.solid = SOLID_BBOX;
             state.groundent = ent->s.groundEntityNum;
             state.modelindex = ent->s.modelindex;
             state.modelindex2 = ent->s.modelindex2;
             state.frame = ent->s.frame;
             state.event = ent->s.event;
             state.eventParm = ent->s.eventParm;
             state.powerups = ent->s.powerups;
             state.legsAnim = ent->s.legsAnim;
             state.torsoAnim = ent->s.torsoAnim;
             state.weapon = ent->s.weapon;
             //
             trap_BotLibUpdateEntity(i, &state);
         }
         BotAIRegularUpdate();
     }
     floattime = trap_AAS_Time();
     // execute scheduled bot AI
     for( i = 0; i < MAX_CLIENTS; i++ ) {
         if( !botstates[i] || !botstates[i]->inuse ) {
             continue;
         }
         //
         botstates[i]->botthink_residual += elapsed_time;
         //
         if ( botstates[i]->botthink_residual >= thinktime ) {
             botstates[i]->botthink_residual -= thinktime;
             if (!trap_AAS_Initialized()) return qfalse;
             if (g_entities[i].client->pers.connected == CON_CONNECTED) {
                 BotAI(i, (float) thinktime / 1000);
             }
         }
     }
     // execute bot user commands every frame
     for( i = 0; i < MAX_CLIENTS; i++ ) {
         if( !botstates[i] || !botstates[i]->inuse ) {
             continue;
         }
         if( g_entities[i].client->pers.connected != CON_CONNECTED ) {
             continue;
         }
         BotUpdateInput(botstates[i], time, elapsed_time);
         trap_BotUserCommand(botstates[i]->client, &botstates[i]->lastucmd);
     }
     return qtrue;
 }
Referenced by vmMain().
BotChangeViewAngle()
float BotChangeViewAngle (float angle, float ideal_angle, float speed)
Definition at line 733 of file ai_main.c.
{
     float move;
     angle = AngleMod(angle);
     ideal_angle = AngleMod(ideal_angle);
     if (angle == ideal_angle) return angle;
     move = ideal_angle - angle;
     if (ideal_angle > angle) {
         if (move > 180.0) move -= 360.0;
     }
     else {
         if (move < -180.0) move += 360.0;
     }
     if (move > 0) {
         if (move > speed) move = speed;
     }
     else {
         if (move < -speed) move = -speed;
     }
     return AngleMod(angle + move);
 }
Referenced by BotChangeViewAngles().
BotChangeViewAngles()
void BotChangeViewAngles (bot_state_t * bs, float thinktime)
Definition at line 760 of file ai_main.c.
{
     float diff, factor, maxchange, anglespeed, disired_speed;
     int i;
     if (bs->ideal_viewangles[PITCH] > 180) bs->ideal_viewangles[PITCH] -= 360;
     //
     if (bs->enemy >= 0) {
         factor = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_VIEW_FACTOR, 0.01f, 1);
         maxchange = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_VIEW_MAXCHANGE, 1, 1800);
     }
     else {
         factor = 0.05f;
         maxchange = 360;
     }
     if (maxchange < 240) maxchange = 240;
     maxchange *= thinktime;
     for (i = 0; i < 2; i++) {
         //
         if (bot_challenge.integer) {
             //smooth slowdown view model
             diff = fabs(AngleDifference(bs->viewangles[i], bs->ideal_viewangles[i]));
             anglespeed = diff * factor;
             if (anglespeed > maxchange) anglespeed = maxchange;
             bs->viewangles[i] = BotChangeViewAngle(bs->viewangles[i],
                                             bs->ideal_viewangles[i], anglespeed);
         }
         else {
             //over reaction view model
             bs->viewangles[i] = AngleMod(bs->viewangles[i]);
             bs->ideal_viewangles[i] = AngleMod(bs->ideal_viewangles[i]);
             diff = AngleDifference(bs->viewangles[i], bs->ideal_viewangles[i]);
             disired_speed = diff * factor;
             bs->viewanglespeed[i] += (bs->viewanglespeed[i] - disired_speed);
             if (bs->viewanglespeed[i] > 180) bs->viewanglespeed[i] = maxchange;
             if (bs->viewanglespeed[i] < -180) bs->viewanglespeed[i] = -maxchange;
             anglespeed = bs->viewanglespeed[i];
             if (anglespeed > maxchange) anglespeed = maxchange;
             if (anglespeed < -maxchange) anglespeed = -maxchange;
             bs->viewangles[i] += anglespeed;
             bs->viewangles[i] = AngleMod(bs->viewangles[i]);
             //demping
             bs->viewanglespeed[i] *= 0.45 * (1 - factor);
         }
         //BotAI_Print(PRT_MESSAGE, "ideal_angles %f %f\n", bs->ideal_viewangles[0], bs->ideal_viewangles[1], bs->ideal_viewangles[2]);`
         //bs->viewangles[i] = bs->ideal_viewangles[i];
     }
     //bs->viewangles[PITCH] = 0;
     if (bs->viewangles[PITCH] > 180) bs->viewangles[PITCH] -= 360;
     //elementary action: view
     trap_EA_View(bs->client, bs->viewangles);
 }
Referenced by BotUpdateInput().
BotEntityInfo()
void BotEntityInfo (int entnum, aas_entityinfo_t * info)
Definition at line 683 of file ai_main.c.
{
     trap_AAS_EntityInfo(entnum, info);
 }
Referenced by AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), BotAIBlocked(), BotAimAtEnemy(), BotAttackMove(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotCheckAttack(), BotCheckEvents(), BotCTFSeekGoals(), BotEnemyFlagCarrierVisible(), BotEntityVisible(), BotFindEnemy(), BotGetActivateGoal(), BotGetLongTermGoal(), BotGoForActivateGoal(), BotLongTermGoal(), BotMapScripts(), BotMatch_Camp(), BotMatch_HelpAccompany(), BotMatch_LeadTheWay(), BotSetTeamStatus(), BotTeamFlagCarrier(), BotTeamFlagCarrierVisible(), BotUpdateBattleInventory(), BotVisibleEnemies(), BotVisibleTeamMatesAndEnemies(), BotVoiceChat_Camp(), BotVoiceChat_FollowMe(), BotWantsToChase(), and BotWantsToRetreat().
BotInitLibrary()
int BotInitLibrary (void)
Definition at line 1594 of file ai_main.c.
{
     char buf[144];
     //set the maxclients and maxentities library variables before calling BotSetupLibrary
     Com_sprintf(buf, sizeof(buf), "%d", level.maxclients);
     trap_BotLibVarSet("maxclients", buf);
     Com_sprintf(buf, sizeof(buf), "%d", MAX_GENTITIES);
     trap_BotLibVarSet("maxentities", buf);
     //bsp checksum
     trap_Cvar_VariableStringBuffer("sv_mapChecksum", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("sv_mapChecksum", buf);
     //maximum number of aas links
     trap_Cvar_VariableStringBuffer("max_aaslinks", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("max_aaslinks", buf);
     //maximum number of items in a level
     trap_Cvar_VariableStringBuffer("max_levelitems", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("max_levelitems", buf);
     //game type
     trap_Cvar_VariableStringBuffer("g_gametype", buf, sizeof(buf));
     if (!strlen(buf)) strcpy(buf, "0");
     trap_BotLibVarSet("g_gametype", buf);
     //bot developer mode and log file
     trap_BotLibVarSet("bot_developer", bot_developer.string);
     trap_Cvar_VariableStringBuffer("logfile", buf, sizeof(buf));
     trap_BotLibVarSet("log", buf);
     //no chatting
     trap_Cvar_VariableStringBuffer("bot_nochat", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("nochat", buf);
     //visualize jump pads
     trap_Cvar_VariableStringBuffer("bot_visualizejumppads", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("bot_visualizejumppads", buf);
     //forced clustering calculations
     trap_Cvar_VariableStringBuffer("bot_forceclustering", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("forceclustering", buf);
     //forced reachability calculations
     trap_Cvar_VariableStringBuffer("bot_forcereachability", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("forcereachability", buf);
     //force writing of AAS to file
     trap_Cvar_VariableStringBuffer("bot_forcewrite", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("forcewrite", buf);
     //no AAS optimization
     trap_Cvar_VariableStringBuffer("bot_aasoptimize", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("aasoptimize", buf);
     //
     trap_Cvar_VariableStringBuffer("bot_saveroutingcache", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("saveroutingcache", buf);
     //reload instead of cache bot character files
     trap_Cvar_VariableStringBuffer("bot_reloadcharacters", buf, sizeof(buf));
     if (!strlen(buf)) strcpy(buf, "0");
     trap_BotLibVarSet("bot_reloadcharacters", buf);
     //base directory
     trap_Cvar_VariableStringBuffer("fs_basepath", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("basedir", buf);
     //game directory
     trap_Cvar_VariableStringBuffer("fs_game", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("gamedir", buf);
     //home directory
     trap_Cvar_VariableStringBuffer("fs_homepath", buf, sizeof(buf));
     if (strlen(buf)) trap_BotLibVarSet("homedir", buf);
     //
 #ifdef MISSIONPACK
     trap_BotLibDefine("MISSIONPACK");
 #endif
     //setup the bot library
     return trap_BotLibSetup();
 }
Referenced by BotAISetup().
BotInputToUserCommand()
void BotInputToUserCommand (bot_input_t * bi, usercmd_t * ucmd, int delta_angles[3], int time)
Definition at line 817 of file ai_main.c.
{
     vec3_t angles, forward, right;
     short temp;
     int j;
     float f, r, u, m;
     //clear the whole structure
     memset(ucmd, 0, sizeof(usercmd_t));
     //the duration for the user command in milli seconds
     ucmd->serverTime = time;
     //
     if (bi->actionflags & ACTION_DELAYEDJUMP) {
         bi->actionflags |= ACTION_JUMP;
         bi->actionflags &= ~ACTION_DELAYEDJUMP;
     }
     //set the buttons
     if (bi->actionflags & ACTION_RESPAWN) ucmd->buttons = BUTTON_ATTACK;
     if (bi->actionflags & ACTION_ATTACK) ucmd->buttons |= BUTTON_ATTACK;
     if (bi->actionflags & ACTION_TALK) ucmd->buttons |= BUTTON_TALK;
     if (bi->actionflags & ACTION_GESTURE) ucmd->buttons |= BUTTON_GESTURE;
     if (bi->actionflags & ACTION_USE) ucmd->buttons |= BUTTON_USE_HOLDABLE;
     if (bi->actionflags & ACTION_WALK) ucmd->buttons |= BUTTON_WALKING;
     if (bi->actionflags & ACTION_AFFIRMATIVE) ucmd->buttons |= BUTTON_AFFIRMATIVE;
     if (bi->actionflags & ACTION_NEGATIVE) ucmd->buttons |= BUTTON_NEGATIVE;
     if (bi->actionflags & ACTION_GETFLAG) ucmd->buttons |= BUTTON_GETFLAG;
     if (bi->actionflags & ACTION_GUARDBASE) ucmd->buttons |= BUTTON_GUARDBASE;
     if (bi->actionflags & ACTION_PATROL) ucmd->buttons |= BUTTON_PATROL;
     if (bi->actionflags & ACTION_FOLLOWME) ucmd->buttons |= BUTTON_FOLLOWME;
     //
     ucmd->weapon = bi->weapon;
     //set the view angles
     //NOTE: the ucmd->angles are the angles WITHOUT the delta angles
     ucmd->angles[PITCH] = ANGLE2SHORT(bi->viewangles[PITCH]);
     ucmd->angles[YAW] = ANGLE2SHORT(bi->viewangles[YAW]);
     ucmd->angles[ROLL] = ANGLE2SHORT(bi->viewangles[ROLL]);
     //subtract the delta angles
     for (j = 0; j < 3; j++) {
         temp = ucmd->angles[j] - delta_angles[j];
         /*NOTE: disabled because temp should be mod first
         if ( j == PITCH ) {
             // don't let the player look up or down more than 90 degrees
             if ( temp > 16000 ) temp = 16000;
             else if ( temp < -16000 ) temp = -16000;
         }
         */
         ucmd->angles[j] = temp;
     }
     //NOTE: movement is relative to the REAL view angles
     //get the horizontal forward and right vector
     //get the pitch in the range [-180, 180]
     if (bi->dir[2]) angles[PITCH] = bi->viewangles[PITCH];
     else angles[PITCH] = 0;
     angles[YAW] = bi->viewangles[YAW];
     angles[ROLL] = 0;
     AngleVectors(angles, forward, right, NULL);
     //bot input speed is in the range [0, 400]
     bi->speed = bi->speed * 127 / 400;
     //set the view independent movement
     f = DotProduct(forward, bi->dir);
     r = DotProduct(right, bi->dir);
     u = fabs(forward[2]) * bi->dir[2];
     m = fabs(f);
     if (fabs(r) > m) {
         m = fabs(r);
     }
     if (fabs(u) > m) {
         m = fabs(u);
     }
     if (m > 0) {
         f *= bi->speed / m;
         r *= bi->speed / m;
         u *= bi->speed / m;
     }
     ucmd->forwardmove = f;
     ucmd->rightmove = r;
     ucmd->upmove = u;
     if (bi->actionflags & ACTION_MOVEFORWARD) ucmd->forwardmove = 127;
     if (bi->actionflags & ACTION_MOVEBACK) ucmd->forwardmove = -127;
     if (bi->actionflags & ACTION_MOVELEFT) ucmd->rightmove = -127;
     if (bi->actionflags & ACTION_MOVERIGHT) ucmd->rightmove = 127;
     //jump/moveup
     if (bi->actionflags & ACTION_JUMP) ucmd->upmove = 127;
     //crouch/movedown
     if (bi->actionflags & ACTION_CROUCH) ucmd->upmove = -127;
 }
Referenced by BotUpdateInput().
BotInterbreedBots()
void BotInterbreedBots (void)
Definition at line 563 of file ai_main.c.
{
     float ranks[MAX_CLIENTS];
     int parent1, parent2, child;
     int i;
     // get rankings for all the bots
     for (i = 0; i < MAX_CLIENTS; i++) {
         if ( botstates[i] && botstates[i]->inuse ) {
             ranks[i] = botstates[i]->num_kills * 2 - botstates[i]->num_deaths;
         }
         else {
             ranks[i] = -1;
         }
     }
     if (trap_GeneticParentsAndChildSelection(MAX_CLIENTS, ranks, &parent1, &parent2, &child)) {
         trap_BotInterbreedGoalFuzzyLogic(botstates[parent1]->gs, botstates[parent2]->gs, botstates[child]->gs);
         trap_BotMutateGoalFuzzyLogic(botstates[child]->gs, 1);
     }
     // reset the kills and deaths
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (botstates[i] && botstates[i]->inuse) {
             botstates[i]->num_kills = 0;
             botstates[i]->num_deaths = 0;
         }
     }
 }
Referenced by BotInterbreedEndMatch().
BotInterbreedEndMatch()
void BotInterbreedEndMatch (void)
Definition at line 628 of file ai_main.c.
{
     if (!bot_interbreed) return;
     bot_interbreedmatchcount++;
     if (bot_interbreedmatchcount >= bot_interbreedcycle.integer) {
         bot_interbreedmatchcount = 0;
         //
         trap_Cvar_Update(&bot_interbreedwrite);
         if (strlen(bot_interbreedwrite.string)) {
             BotWriteInterbreeded(bot_interbreedwrite.string);
             trap_Cvar_Set("bot_interbreedwrite", "");
         }
         BotInterbreedBots();
     }
 }
Referenced by ExitLevel().
BotInterbreeding()
void BotInterbreeding (void)
Definition at line 649 of file ai_main.c.
{
     int i;
     trap_Cvar_Update(&bot_interbreedchar);
     if (!strlen(bot_interbreedchar.string)) return;
     //make sure we are in tournament mode
     if (gametype != GT_TOURNAMENT) {
         trap_Cvar_Set("g_gametype", va("%d", GT_TOURNAMENT));
         ExitLevel();
         return;
     }
     //shutdown all the bots
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (botstates[i] && botstates[i]->inuse) {
             BotAIShutdownClient(botstates[i]->client, qfalse);
         }
     }
     //make sure all item weight configs are reloaded and Not shared
     trap_BotLibVarSet("bot_reloadcharacters", "1");
     //add a number of bots using the desired bot character
     for (i = 0; i < bot_interbreedbots.integer; i++) {
         trap_SendConsoleCommand( EXEC_INSERT, va("addbot %s 4 free %i %s%d\n",
                         bot_interbreedchar.string, i * 50, bot_interbreedchar.string, i) );
     }
     //
     trap_Cvar_Set("bot_interbreedchar", "");
     bot_interbreed = qtrue;
 }
Referenced by BotAIStartFrame().
BotReadSessionData()
void BotReadSessionData (bot_state_t * bs)
Definition at line 1133 of file ai_main.c.
{
     char    s[MAX_STRING_CHARS];
     const char  *var;
     var = va( "botsession%i", bs->client );
     trap_Cvar_VariableStringBuffer( var, s, sizeof(s) );
     sscanf(s,
             "%i %i %i %i %i %i %i %i"
             " %f %f %f"
             " %f %f %f"
             " %f %f %f"
             " %f",
         &bs->lastgoal_decisionmaker,
         &bs->lastgoal_ltgtype,
         &bs->lastgoal_teammate,
         &bs->lastgoal_teamgoal.areanum,
         &bs->lastgoal_teamgoal.entitynum,
         &bs->lastgoal_teamgoal.flags,
         &bs->lastgoal_teamgoal.iteminfo,
         &bs->lastgoal_teamgoal.number,
         &bs->lastgoal_teamgoal.origin[0],
         &bs->lastgoal_teamgoal.origin[1],
         &bs->lastgoal_teamgoal.origin[2],
         &bs->lastgoal_teamgoal.mins[0],
         &bs->lastgoal_teamgoal.mins[1],
         &bs->lastgoal_teamgoal.mins[2],
         &bs->lastgoal_teamgoal.maxs[0],
         &bs->lastgoal_teamgoal.maxs[1],
         &bs->lastgoal_teamgoal.maxs[2],
         &bs->formation_dist
         );
 }
Referenced by BotAISetupClient().
BotReportStatus()
void BotReportStatus (bot_state_t * bs)
Definition at line 275 of file ai_main.c.
{
     char goalname[MAX_MESSAGE_SIZE];
     char netname[MAX_MESSAGE_SIZE];
     char *leader, flagstatus[32];
     //
     ClientName(bs->client, netname, sizeof(netname));
     if (Q_stricmp(netname, bs->teamleader) == 0) leader = "L";
     else leader = " ";
     strcpy(flagstatus, "  ");
     if (gametype == GT_CTF) {
         if (BotCTFCarryingFlag(bs)) {
             if (BotTeam(bs) == TEAM_RED) strcpy(flagstatus, S_COLOR_RED"F ");
             else strcpy(flagstatus, S_COLOR_BLUE"F ");
         }
     }
 #ifdef MISSIONPACK
     else if (gametype == GT_1FCTF) {
         if (Bot1FCTFCarryingFlag(bs)) {
             if (BotTeam(bs) == TEAM_RED) strcpy(flagstatus, S_COLOR_RED"F ");
             else strcpy(flagstatus, S_COLOR_BLUE"F ");
         }
     }
     else if (gametype == GT_HARVESTER) {
         if (BotHarvesterCarryingCubes(bs)) {
             if (BotTeam(bs) == TEAM_RED) Com_sprintf(flagstatus, sizeof(flagstatus), S_COLOR_RED"%2d", bs->inventory[INVENTORY_REDCUBE]);
             else Com_sprintf(flagstatus, sizeof(flagstatus), S_COLOR_BLUE"%2d", bs->inventory[INVENTORY_BLUECUBE]);
         }
     }
 #endif
     switch(bs->ltgtype) {
         case LTG_TEAMHELP:
         {
             EasyClientName(bs->teammate, goalname, sizeof(goalname));
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: helping %s\n", netname, leader, flagstatus, goalname);
             break;
         }
         case LTG_TEAMACCOMPANY:
         {
             EasyClientName(bs->teammate, goalname, sizeof(goalname));
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: accompanying %s\n", netname, leader, flagstatus, goalname);
             break;
         }
         case LTG_DEFENDKEYAREA:
         {
             trap_BotGoalName(bs->teamgoal.number, goalname, sizeof(goalname));
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: defending %s\n", netname, leader, flagstatus, goalname);
             break;
         }
         case LTG_GETITEM:
         {
             trap_BotGoalName(bs->teamgoal.number, goalname, sizeof(goalname));
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: getting item %s\n", netname, leader, flagstatus, goalname);
             break;
         }
         case LTG_KILL:
         {
             ClientName(bs->teamgoal.entitynum, goalname, sizeof(goalname));
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: killing %s\n", netname, leader, flagstatus, goalname);
             break;
         }
         case LTG_CAMP:
         case LTG_CAMPORDER:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: camping\n", netname, leader, flagstatus);
             break;
         }
         case LTG_PATROL:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: patrolling\n", netname, leader, flagstatus);
             break;
         }
         case LTG_GETFLAG:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: capturing flag\n", netname, leader, flagstatus);
             break;
         }
         case LTG_RUSHBASE:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: rushing base\n", netname, leader, flagstatus);
             break;
         }
         case LTG_RETURNFLAG:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: returning flag\n", netname, leader, flagstatus);
             break;
         }
         case LTG_ATTACKENEMYBASE:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: attacking the enemy base\n", netname, leader, flagstatus);
             break;
         }
         case LTG_HARVEST:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: harvesting\n", netname, leader, flagstatus);
             break;
         }
         default:
         {
             BotAI_Print(PRT_MESSAGE, "%-20s%s%s: roaming\n", netname, leader, flagstatus);
             break;
         }
     }
 }
Referenced by BotTeamplayReport().
BotResetState()
void BotResetState (bot_state_t * bs)
Definition at line 1321 of file ai_main.c.
{
     int client, entitynum, inuse;
     int movestate, goalstate, chatstate, weaponstate;
     bot_settings_t settings;
     int character;
     playerState_t ps;                           //current player state
     float entergame_time;
     //save some things that should not be reset here
     memcpy(&settings, &bs->settings, sizeof(bot_settings_t));
     memcpy(&ps, &bs->cur_ps, sizeof(playerState_t));
     inuse = bs->inuse;
     client = bs->client;
     entitynum = bs->entitynum;
     character = bs->character;
     movestate = bs->ms;
     goalstate = bs->gs;
     chatstate = bs->cs;
     weaponstate = bs->ws;
     entergame_time = bs->entergame_time;
     //free checkpoints and patrol points
     BotFreeWaypoints(bs->checkpoints);
     BotFreeWaypoints(bs->patrolpoints);
     //reset the whole state
     memset(bs, 0, sizeof(bot_state_t));
     //copy back some state stuff that should not be reset
     bs->ms = movestate;
     bs->gs = goalstate;
     bs->cs = chatstate;
     bs->ws = weaponstate;
     memcpy(&bs->cur_ps, &ps, sizeof(playerState_t));
     memcpy(&bs->settings, &settings, sizeof(bot_settings_t));
     bs->inuse = inuse;
     bs->client = client;
     bs->entitynum = entitynum;
     bs->character = character;
     bs->entergame_time = entergame_time;
     //reset several states
     if (bs->ms) trap_BotResetMoveState(bs->ms);
     if (bs->gs) trap_BotResetGoalState(bs->gs);
     if (bs->ws) trap_BotResetWeaponState(bs->ws);
     if (bs->gs) trap_BotResetAvoidGoals(bs->gs);
     if (bs->ms) trap_BotResetAvoidReach(bs->ms);
 }
Referenced by AIEnter_Intermission(), AIEnter_Observer(), and BotAILoadMap().
BotScheduleBotThink()
void BotScheduleBotThink (void)
Definition at line 1073 of file ai_main.c.
{
     int i, botnum;
     botnum = 0;
     for( i = 0; i < MAX_CLIENTS; i++ ) {
         if( !botstates[i] || !botstates[i]->inuse ) {
             continue;
         }
         //initialize the bot think residual time
         botstates[i]->botthink_residual = bot_thinktime.integer * botnum / numbots;
         botnum++;
     }
 }
Referenced by BotAISetupClient(), and BotAIStartFrame().
BotSetInfoConfigString()
void BotSetInfoConfigString (bot_state_t * bs)
Definition at line 423 of file ai_main.c.
{
     char goalname[MAX_MESSAGE_SIZE];
     char netname[MAX_MESSAGE_SIZE];
     char action[MAX_MESSAGE_SIZE];
     char *leader, carrying[32], *cs;
     bot_goal_t goal;
     //
     ClientName(bs->client, netname, sizeof(netname));
     if (Q_stricmp(netname, bs->teamleader) == 0) leader = "L";
     else leader = " ";
     strcpy(carrying, "  ");
     if (gametype == GT_CTF) {
         if (BotCTFCarryingFlag(bs)) {
             strcpy(carrying, "F ");
         }
     }
 #ifdef MISSIONPACK
     else if (gametype == GT_1FCTF) {
         if (Bot1FCTFCarryingFlag(bs)) {
             strcpy(carrying, "F ");
         }
     }
     else if (gametype == GT_HARVESTER) {
         if (BotHarvesterCarryingCubes(bs)) {
             if (BotTeam(bs) == TEAM_RED) Com_sprintf(carrying, sizeof(carrying), "%2d", bs->inventory[INVENTORY_REDCUBE]);
             else Com_sprintf(carrying, sizeof(carrying), "%2d", bs->inventory[INVENTORY_BLUECUBE]);
         }
     }
 #endif
     switch(bs->ltgtype) {
         case LTG_TEAMHELP:
         {
             EasyClientName(bs->teammate, goalname, sizeof(goalname));
             Com_sprintf(action, sizeof(action), "helping %s", goalname);
             break;
         }
         case LTG_TEAMACCOMPANY:
         {
             EasyClientName(bs->teammate, goalname, sizeof(goalname));
             Com_sprintf(action, sizeof(action), "accompanying %s", goalname);
             break;
         }
         case LTG_DEFENDKEYAREA:
         {
             trap_BotGoalName(bs->teamgoal.number, goalname, sizeof(goalname));
             Com_sprintf(action, sizeof(action), "defending %s", goalname);
             break;
         }
         case LTG_GETITEM:
         {
             trap_BotGoalName(bs->teamgoal.number, goalname, sizeof(goalname));
             Com_sprintf(action, sizeof(action), "getting item %s", goalname);
             break;
         }
         case LTG_KILL:
         {
             ClientName(bs->teamgoal.entitynum, goalname, sizeof(goalname));
             Com_sprintf(action, sizeof(action), "killing %s", goalname);
             break;
         }
         case LTG_CAMP:
         case LTG_CAMPORDER:
         {
             Com_sprintf(action, sizeof(action), "camping");
             break;
         }
         case LTG_PATROL:
         {
             Com_sprintf(action, sizeof(action), "patrolling");
             break;
         }
         case LTG_GETFLAG:
         {
             Com_sprintf(action, sizeof(action), "capturing flag");
             break;
         }
         case LTG_RUSHBASE:
         {
             Com_sprintf(action, sizeof(action), "rushing base");
             break;
         }
         case LTG_RETURNFLAG:
         {
             Com_sprintf(action, sizeof(action), "returning flag");
             break;
         }
         case LTG_ATTACKENEMYBASE:
         {
             Com_sprintf(action, sizeof(action), "attacking the enemy base");
             break;
         }
         case LTG_HARVEST:
         {
             Com_sprintf(action, sizeof(action), "harvesting");
             break;
         }
         default:
         {
             trap_BotGetTopGoal(bs->gs, &goal);
             trap_BotGoalName(goal.number, goalname, sizeof(goalname));
             Com_sprintf(action, sizeof(action), "roaming %s", goalname);
             break;
         }
     }
     cs = va("l\\%s\\c\\%s\\a\\%s",
                 leader,
                 carrying,
                 action);
     trap_SetConfigstring (CS_BOTINFO + bs->client, cs);
 }
Referenced by BotUpdateInfoConfigStrings().
BotTeamLeader()
int BotTeamLeader (bot_state_t * bs)
Definition at line 701 of file ai_main.c.
{
     int leader;
     leader = ClientFromName(bs->teamleader);
     if (leader < 0) return qfalse;
     if (!botstates[leader] || !botstates[leader]->inuse) return qfalse;
     return qtrue;
 }
Referenced by BotCheckItemPickup(), and BotCTFSeekGoals().
BotTeamplayReport()
void BotTeamplayReport (void)
Definition at line 386 of file ai_main.c.
{
     int i;
     char buf[MAX_INFO_STRING];
     BotAI_Print(PRT_MESSAGE, S_COLOR_RED"RED\n");
     for (i = 0; i < level.maxclients; i++) {
         //
         if ( !botstates[i] || !botstates[i]->inuse ) continue;
         //
         trap_GetConfigstring(CS_PLAYERS+i, buf, sizeof(buf));
         //if no config string or no name
         if (!strlen(buf) || !strlen(Info_ValueForKey(buf, "n"))) continue;
         //skip spectators
         if (atoi(Info_ValueForKey(buf, "t")) == TEAM_RED) {
             BotReportStatus(botstates[i]);
         }
     }
     BotAI_Print(PRT_MESSAGE, S_COLOR_BLUE"BLUE\n");
     for (i = 0; i < level.maxclients; i++) {
         //
         if ( !botstates[i] || !botstates[i]->inuse ) continue;
         //
         trap_GetConfigstring(CS_PLAYERS+i, buf, sizeof(buf));
         //if no config string or no name
         if (!strlen(buf) || !strlen(Info_ValueForKey(buf, "n"))) continue;
         //skip spectators
         if (atoi(Info_ValueForKey(buf, "t")) == TEAM_BLUE) {
             BotReportStatus(botstates[i]);
         }
     }
 }
BotTestAAS()
void BotTestAAS (vec3_t origin)
Definition at line 246 of file ai_main.c.
{
     int areanum;
     aas_areainfo_t info;
     trap_Cvar_Update(&bot_testsolid);
     trap_Cvar_Update(&bot_testclusters);
     if (bot_testsolid.integer) {
         if (!trap_AAS_Initialized()) return;
         areanum = BotPointAreaNum(origin);
         if (areanum) BotAI_Print(PRT_MESSAGE, "\rempty area");
         else BotAI_Print(PRT_MESSAGE, "\r^1SOLID area");
     }
     else if (bot_testclusters.integer) {
         if (!trap_AAS_Initialized()) return;
         areanum = BotPointAreaNum(origin);
         if (!areanum)
             BotAI_Print(PRT_MESSAGE, "\r^1Solid!                              ");
         else {
             trap_AAS_AreaInfo(areanum, &info);
             BotAI_Print(PRT_MESSAGE, "\rarea %d, cluster %d       ", areanum, info.cluster);
         }
     }
 }
Referenced by ClientThink_real().
BotUpdateInfoConfigStrings()
void BotUpdateInfoConfigStrings (void)
Definition at line 541 of file ai_main.c.
{
     int i;
     char buf[MAX_INFO_STRING];
     for (i = 0; i < level.maxclients; i++) {
         //
         if ( !botstates[i] || !botstates[i]->inuse )
             continue;
         //
         trap_GetConfigstring(CS_PLAYERS+i, buf, sizeof(buf));
         //if no config string or no name
         if (!strlen(buf) || !strlen(Info_ValueForKey(buf, "n")))
             continue;
         BotSetInfoConfigString(botstates[i]);
     }
 }
Referenced by BotAIStartFrame().
BotUpdateInput()
void BotUpdateInput (bot_state_t * bs, int time, int elapsed_time)
Definition at line 913 of file ai_main.c.
{
     bot_input_t bi;
     int j;
     //add the delta angles to the bot's current view angles
     for (j = 0; j < 3; j++) {
         bs->viewangles[j] = AngleMod(bs->viewangles[j] + SHORT2ANGLE(bs->cur_ps.delta_angles[j]));
     }
     //change the bot view angles
     BotChangeViewAngles(bs, (float) elapsed_time / 1000);
     //retrieve the bot input
     trap_EA_GetInput(bs->client, (float) time / 1000, &bi);
     //respawn hack
     if (bi.actionflags & ACTION_RESPAWN) {
         if (bs->lastucmd.buttons & BUTTON_ATTACK) bi.actionflags &= ~(ACTION_RESPAWN|ACTION_ATTACK);
     }
     //convert the bot input to a usercmd
     BotInputToUserCommand(&bi, &bs->lastucmd, bs->cur_ps.delta_angles, time);
     //subtract the delta angles
     for (j = 0; j < 3; j++) {
         bs->viewangles[j] = AngleMod(bs->viewangles[j] - SHORT2ANGLE(bs->cur_ps.delta_angles[j]));
     }
 }
Referenced by BotAIStartFrame().
BotWriteInterbreeded()
void BotWriteInterbreeded (char * filename)
Definition at line 596 of file ai_main.c.
{
     float rank, bestrank;
     int i, bestbot;
     bestrank = 0;
     bestbot = -1;
     // get the best bot
     for (i = 0; i < MAX_CLIENTS; i++) {
         if ( botstates[i] && botstates[i]->inuse ) {
             rank = botstates[i]->num_kills * 2 - botstates[i]->num_deaths;
         }
         else {
             rank = -1;
         }
         if (rank > bestrank) {
             bestrank = rank;
             bestbot = i;
         }
     }
     if (bestbot >= 0) {
         //write out the new goal fuzzy logic
         trap_BotSaveGoalFuzzyLogic(botstates[bestbot]->gs, filename);
     }
 }
Referenced by BotInterbreedEndMatch().
BotWriteSessionData()
void BotWriteSessionData (bot_state_t * bs)
Definition at line 1093 of file ai_main.c.
{
     const char  *s;
     const char  *var;
     s = va(
             "%i %i %i %i %i %i %i %i"
             " %f %f %f"
             " %f %f %f"
             " %f %f %f"
             " %f",
         bs->lastgoal_decisionmaker,
         bs->lastgoal_ltgtype,
         bs->lastgoal_teammate,
         bs->lastgoal_teamgoal.areanum,
         bs->lastgoal_teamgoal.entitynum,
         bs->lastgoal_teamgoal.flags,
         bs->lastgoal_teamgoal.iteminfo,
         bs->lastgoal_teamgoal.number,
         bs->lastgoal_teamgoal.origin[0],
         bs->lastgoal_teamgoal.origin[1],
         bs->lastgoal_teamgoal.origin[2],
         bs->lastgoal_teamgoal.mins[0],
         bs->lastgoal_teamgoal.mins[1],
         bs->lastgoal_teamgoal.mins[2],
         bs->lastgoal_teamgoal.maxs[0],
         bs->lastgoal_teamgoal.maxs[1],
         bs->lastgoal_teamgoal.maxs[2],
         bs->formation_dist
         );
     var = va( "botsession%i", bs->client );
     trap_Cvar_Set( var, s );
 }
Referenced by BotAIShutdownClient().
ExitLevel()
void ExitLevel (void)
Definition at line 1043 of file g_main.c.
                       {
     int     i;
     gclient_t *cl;
     char nextmap[MAX_STRING_CHARS];
     char d1[MAX_STRING_CHARS];
     //bot interbreeding
     BotInterbreedEndMatch();
     // if we are running a tournement map, kick the loser to spectator status,
     // which will automatically grab the next spectator and restart
     if ( g_gametype.integer == GT_TOURNAMENT  ) {
         if ( !level.restarted ) {
             RemoveTournamentLoser();
             trap_SendConsoleCommand( EXEC_APPEND, "map_restart 0\n" );
             level.restarted = qtrue;
             level.changemap = NULL;
             level.intermissiontime = 0;
         }
         return;
     }
     trap_Cvar_VariableStringBuffer( "nextmap", nextmap, sizeof(nextmap) );
     trap_Cvar_VariableStringBuffer( "d1", d1, sizeof(d1) );
     if( !Q_stricmp( nextmap, "map_restart 0" ) && Q_stricmp( d1, "" ) ) {
         trap_Cvar_Set( "nextmap", "vstr d2" );
         trap_SendConsoleCommand( EXEC_APPEND, "vstr d1\n" );
     } else {
         trap_SendConsoleCommand( EXEC_APPEND, "vstr nextmap\n" );
     }
     level.changemap = NULL;
     level.intermissiontime = 0;
     // reset all the scores so we don't enter the intermission again
     level.teamScores[TEAM_RED] = 0;
     level.teamScores[TEAM_BLUE] = 0;
     for ( i=0 ; i< g_maxclients.integer ; i++ ) {
         cl = level.clients + i;
         if ( cl->pers.connected != CON_CONNECTED ) {
             continue;
         }
         cl->ps.persistant[PERS_SCORE] = 0;
     }
     // we need to do this here before changing to CON_CONNECTING
     G_WriteSessionData();
     // change all client states to connecting, so the early players into the
     // next level will know the others aren't done reconnecting
     for (i=0 ; i< g_maxclients.integer ; i++) {
         if ( level.clients[i].pers.connected == CON_CONNECTED ) {
             level.clients[i].pers.connected = CON_CONNECTING;
         }
     }
 }
Referenced by BotInterbreeding(), and CheckIntermissionExit().
NumBots()
int NumBots (void)
Definition at line 692 of file ai_main.c.
                   {
     return numbots;
 }
Referenced by BotCheckConsoleMessages().
RemoveColorEscapeSequences()
void RemoveColorEscapeSequences (char * text)
Definition at line 954 of file ai_main.c.
{
     int i, l;
     l = 0;
     for ( i = 0; text[i]; i++ ) {
         if (Q_IsColorString(&text[i])) {
             i++;
             continue;
         }
         if (text[i] > 0x7E)
             continue;
         text[l++] = text[i];
     }
     text[l] = '\0';
 }
Referenced by BotAI().
Variable Documentation
bot_developer
vmCvar_t bot_developer
Definition at line 78 of file ai_main.c.
Referenced by BotAISetup(), BotGetActivateGoal(), and BotInitLibrary().
bot_interbreed
int bot_interbreed
Definition at line 68 of file ai_main.c.
Referenced by BotAISetupClient(), BotInterbreedEndMatch(), and BotInterbreeding().
bot_interbreedbots
vmCvar_t bot_interbreedbots
Definition at line 80 of file ai_main.c.
Referenced by BotAISetup(), and BotInterbreeding().
bot_interbreedchar
vmCvar_t bot_interbreedchar
Definition at line 79 of file ai_main.c.
Referenced by BotAISetup(), and BotInterbreeding().
bot_interbreedcycle
vmCvar_t bot_interbreedcycle
Definition at line 81 of file ai_main.c.
Referenced by BotAISetup(), and BotInterbreedEndMatch().
bot_interbreedmatchcount
int bot_interbreedmatchcount
Definition at line 69 of file ai_main.c.
Referenced by BotInterbreedEndMatch().
bot_interbreedwrite
vmCvar_t bot_interbreedwrite
Definition at line 82 of file ai_main.c.
Referenced by BotAISetup(), and BotInterbreedEndMatch().
bot_memorydump
vmCvar_t bot_memorydump
Definition at line 72 of file ai_main.c.
Referenced by BotAISetup(), and BotAIStartFrame().
bot_pause
vmCvar_t bot_pause
Definition at line 74 of file ai_main.c.
Referenced by BotAISetup(), and BotAIStartFrame().
bot_report
vmCvar_t bot_report
Definition at line 75 of file ai_main.c.
Referenced by BotAISetup(), and BotAIStartFrame().
bot_saveroutingcache
vmCvar_t bot_saveroutingcache
Definition at line 73 of file ai_main.c.
Referenced by BotAISetup(), and BotAIStartFrame().
bot_testclusters
vmCvar_t bot_testclusters
Definition at line 77 of file ai_main.c.
Referenced by BotAISetup(), and BotTestAAS().
bot_testsolid
vmCvar_t bot_testsolid
Definition at line 76 of file ai_main.c.
Referenced by BotAISetup(), and BotTestAAS().
bot_thinktime
vmCvar_t bot_thinktime
Definition at line 71 of file ai_main.c.
Referenced by BotAISetup(), BotAIStartFrame(), and BotScheduleBotThink().
botstates
bot_state_t* botstates[MAX_CLIENTS]
Definition at line 60 of file ai_main.c.
Referenced by BotAI(), BotAILoadMap(), BotAISetup(), BotAISetupClient(), BotAIShutdown(), BotAIShutdownClient(), BotAIStartFrame(), BotInterbreedBots(), BotInterbreeding(), BotScheduleBotThink(), BotTeamLeader(), BotTeamplayReport(), BotUpdateInfoConfigStrings(), and BotWriteInterbreeded().
floattime
float floattime
Definition at line 64 of file ai_main.c.
Referenced by BotAIStartFrame().
numbots
int numbots
Definition at line 62 of file ai_main.c.
Referenced by BotAISetupClient(), BotAIShutdownClient(), BotScheduleBotThink(), and NumBots().
regularupdate_time
float regularupdate_time
Definition at line 66 of file ai_main.c.
Referenced by BotAIRegularUpdate().