ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_main.c File Reference
ui_main.c File Reference
#include "ui_local.h"
Classes
struct cvarTable_t
Functions
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
void UI_RegisterCvars (void)
void UI_UpdateCvars (void)
Variables
vmCvar_t ui_ffa_fraglimit
vmCvar_t ui_ffa_timelimit
vmCvar_t ui_tourney_fraglimit
vmCvar_t ui_tourney_timelimit
vmCvar_t ui_team_fraglimit
vmCvar_t ui_team_timelimit
vmCvar_t ui_team_friendly
vmCvar_t ui_ctf_capturelimit
vmCvar_t ui_ctf_timelimit
vmCvar_t ui_ctf_friendly
vmCvar_t ui_arenasFile
vmCvar_t ui_botsFile
vmCvar_t ui_spScores1
vmCvar_t ui_spScores2
vmCvar_t ui_spScores3
vmCvar_t ui_spScores4
vmCvar_t ui_spScores5
vmCvar_t ui_spAwards
vmCvar_t ui_spVideos
vmCvar_t ui_spSkill
vmCvar_t ui_spSelection
vmCvar_t ui_browserMaster
vmCvar_t ui_browserGameType
vmCvar_t ui_browserSortKey
vmCvar_t ui_browserShowFull
vmCvar_t ui_browserShowEmpty
vmCvar_t ui_brassTime
vmCvar_t ui_drawCrosshair
vmCvar_t ui_drawCrosshairNames
vmCvar_t ui_marks
vmCvar_t ui_server1
vmCvar_t ui_server2
vmCvar_t ui_server3
vmCvar_t ui_server4
vmCvar_t ui_server5
vmCvar_t ui_server6
vmCvar_t ui_server7
vmCvar_t ui_server8
vmCvar_t ui_server9
vmCvar_t ui_server10
vmCvar_t ui_server11
vmCvar_t ui_server12
vmCvar_t ui_server13
vmCvar_t ui_server14
vmCvar_t ui_server15
vmCvar_t ui_server16
vmCvar_t ui_cdkeychecked
vmCvar_t ui_ioq3
static cvarTable_t cvarTable []
static int cvarTableSize = ARRAY_LEN(cvarTable)
Function Documentation
UI_RegisterCvars()
void UI_RegisterCvars (void)
Definition at line 229 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         trap_Cvar_Register( cv->vmCvar, cv->cvarName, cv->defaultString, cv->cvarFlags );
     }
 }
Referenced by _UI_Init().
UI_UpdateCvars()
void UI_UpdateCvars (void)
Definition at line 243 of file ui_main.c.
{
     int         i;
     cvarTable_t *cv;
     for ( i = 0, cv = cvarTable ; i < cvarTableSize ; i++, cv++ ) {
         if ( !cv->vmCvar ) {
             continue;
         }
         trap_Cvar_Update( cv->vmCvar );
     }
 }
Referenced by _UI_Refresh().
vmMain()
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
Definition at line 43 of file ui_main.c.
{
     switch ( command ) {
     case UI_GETAPIVERSION:
         return UI_API_VERSION;
     case UI_INIT:
         UI_Init();
         return 0;
     case UI_SHUTDOWN:
         UI_Shutdown();
         return 0;
     case UI_KEY_EVENT:
         UI_KeyEvent( arg0, arg1 );
         return 0;
     case UI_MOUSE_EVENT:
         UI_MouseEvent( arg0, arg1 );
         return 0;
     case UI_REFRESH:
         UI_Refresh( arg0 );
         return 0;
     case UI_IS_FULLSCREEN:
         return UI_IsFullscreen();
     case UI_SET_ACTIVE_MENU:
         UI_SetActiveMenu( arg0 );
         return 0;
     case UI_CONSOLE_COMMAND:
         return UI_ConsoleCommand(arg0);
     case UI_DRAW_CONNECT_SCREEN:
         UI_DrawConnectScreen( arg0 );
         return 0;
     case UI_HASUNIQUECDKEY:             // mod authors need to observe this
         return qtrue;  // change this to qfalse for mods!
     }
     return -1;
 }
References qtrue, UI_API_VERSION, UI_CONSOLE_COMMAND, UI_ConsoleCommand(), UI_DRAW_CONNECT_SCREEN, UI_DrawConnectScreen(), UI_GETAPIVERSION, UI_HASUNIQUECDKEY, UI_INIT, UI_Init(), UI_IS_FULLSCREEN, UI_IsFullscreen(), UI_KEY_EVENT, UI_KeyEvent(), UI_MOUSE_EVENT, UI_MouseEvent(), UI_REFRESH, UI_Refresh(), UI_SET_ACTIVE_MENU, UI_SetActiveMenu(), UI_SHUTDOWN, and UI_Shutdown().
Variable Documentation
cvarTable
cvarTable_t cvarTable[] static
Definition at line 160 of file ui_main.c.
Referenced by UI_RegisterCvars(), and UI_UpdateCvars().
cvarTableSize
int cvarTableSize = ARRAY_LEN(cvarTable) static
Definition at line 221 of file ui_main.c.
Referenced by UI_RegisterCvars(), and UI_UpdateCvars().
ui_arenasFile
vmCvar_t ui_arenasFile
Definition at line 116 of file ui_main.c.
ui_botsFile
vmCvar_t ui_botsFile
Definition at line 117 of file ui_main.c.
ui_brassTime
vmCvar_t ui_brassTime
Definition at line 135 of file ui_main.c.
ui_browserGameType
vmCvar_t ui_browserGameType
Definition at line 130 of file ui_main.c.
ui_browserMaster
vmCvar_t ui_browserMaster
Definition at line 129 of file ui_main.c.
ui_browserShowEmpty
vmCvar_t ui_browserShowEmpty
Definition at line 133 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
ui_browserShowFull
vmCvar_t ui_browserShowFull
Definition at line 132 of file ui_main.c.
Referenced by UI_BuildServerDisplayList().
ui_browserSortKey
vmCvar_t ui_browserSortKey
Definition at line 131 of file ui_main.c.
Referenced by ArenaServers_MenuInit().
ui_cdkeychecked
vmCvar_t ui_cdkeychecked
Definition at line 157 of file ui_main.c.
ui_ctf_capturelimit
vmCvar_t ui_ctf_capturelimit
Definition at line 112 of file ui_main.c.
ui_ctf_friendly
vmCvar_t ui_ctf_friendly
Definition at line 114 of file ui_main.c.
ui_ctf_timelimit
vmCvar_t ui_ctf_timelimit
Definition at line 113 of file ui_main.c.
ui_drawCrosshair
vmCvar_t ui_drawCrosshair
Definition at line 136 of file ui_main.c.
ui_drawCrosshairNames
vmCvar_t ui_drawCrosshairNames
Definition at line 137 of file ui_main.c.
ui_ffa_fraglimit
vmCvar_t ui_ffa_fraglimit
Definition at line 102 of file ui_main.c.
ui_ffa_timelimit
vmCvar_t ui_ffa_timelimit
Definition at line 103 of file ui_main.c.
ui_ioq3
vmCvar_t ui_ioq3
Definition at line 158 of file ui_main.c.
ui_marks
vmCvar_t ui_marks
Definition at line 138 of file ui_main.c.
ui_server1
vmCvar_t ui_server1
Definition at line 140 of file ui_main.c.
ui_server10
vmCvar_t ui_server10
Definition at line 149 of file ui_main.c.
ui_server11
vmCvar_t ui_server11
Definition at line 150 of file ui_main.c.
ui_server12
vmCvar_t ui_server12
Definition at line 151 of file ui_main.c.
ui_server13
vmCvar_t ui_server13
Definition at line 152 of file ui_main.c.
ui_server14
vmCvar_t ui_server14
Definition at line 153 of file ui_main.c.
ui_server15
vmCvar_t ui_server15
Definition at line 154 of file ui_main.c.
ui_server16
vmCvar_t ui_server16
Definition at line 155 of file ui_main.c.
ui_server2
vmCvar_t ui_server2
Definition at line 141 of file ui_main.c.
ui_server3
vmCvar_t ui_server3
Definition at line 142 of file ui_main.c.
ui_server4
vmCvar_t ui_server4
Definition at line 143 of file ui_main.c.
ui_server5
vmCvar_t ui_server5
Definition at line 144 of file ui_main.c.
ui_server6
vmCvar_t ui_server6
Definition at line 145 of file ui_main.c.
ui_server7
vmCvar_t ui_server7
Definition at line 146 of file ui_main.c.
ui_server8
vmCvar_t ui_server8
Definition at line 147 of file ui_main.c.
ui_server9
vmCvar_t ui_server9
Definition at line 148 of file ui_main.c.
ui_spAwards
vmCvar_t ui_spAwards
Definition at line 123 of file ui_main.c.
ui_spScores1
vmCvar_t ui_spScores1
Definition at line 118 of file ui_main.c.
ui_spScores2
vmCvar_t ui_spScores2
Definition at line 119 of file ui_main.c.
ui_spScores3
vmCvar_t ui_spScores3
Definition at line 120 of file ui_main.c.
ui_spScores4
vmCvar_t ui_spScores4
Definition at line 121 of file ui_main.c.
ui_spScores5
vmCvar_t ui_spScores5
Definition at line 122 of file ui_main.c.
ui_spSelection
vmCvar_t ui_spSelection
Definition at line 127 of file ui_main.c.
ui_spSkill
vmCvar_t ui_spSkill
Definition at line 125 of file ui_main.c.
ui_spVideos
vmCvar_t ui_spVideos
Definition at line 124 of file ui_main.c.
ui_team_fraglimit
vmCvar_t ui_team_fraglimit
Definition at line 108 of file ui_main.c.
ui_team_friendly
vmCvar_t ui_team_friendly
Definition at line 110 of file ui_main.c.
ui_team_timelimit
vmCvar_t ui_team_timelimit
Definition at line 109 of file ui_main.c.
ui_tourney_fraglimit
vmCvar_t ui_tourney_fraglimit
Definition at line 105 of file ui_main.c.
ui_tourney_timelimit
vmCvar_t ui_tourney_timelimit
Definition at line 106 of file ui_main.c.