ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ai_weap.c File Reference
be_ai_weap.c File Reference
#include "../qcommon/q_shared.h"
#include "l_libvar.h"
#include "l_log.h"
#include "l_memory.h"
#include "l_utils.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_ai_weight.h"
#include "be_ai_weap.h"
Classes
struct weaponconfig_s
struct bot_weaponstate_s
Macros
#define WEAPON_OFS(x) (size_t)&(((weaponinfo_t *)0)->x)
#define PROJECTILE_OFS(x) (size_t)&(((projectileinfo_t *)0)->x)
Typedefs
typedef struct weaponconfig_s weaponconfig_t
typedef struct bot_weaponstate_s bot_weaponstate_t
Functions
int BotValidWeaponNumber (int weaponnum)
bot_weaponstate_t * BotWeaponStateFromHandle (int handle)
weaponconfig_t * LoadWeaponConfig (char *filename)
int * WeaponWeightIndex (weightconfig_t *wwc, weaponconfig_t *wc)
void BotFreeWeaponWeights (int weaponstate)
int BotLoadWeaponWeights (int weaponstate, char *filename)
void BotGetWeaponInfo (int weaponstate, int weapon, weaponinfo_t *weaponinfo)
int BotChooseBestFightWeapon (int weaponstate, int *inventory)
void BotResetWeaponState (int weaponstate)
int BotAllocWeaponState (void)
void BotFreeWeaponState (int handle)
int BotSetupWeaponAI (void)
void BotShutdownWeaponAI (void)
Variables
static fielddef_t weaponinfo_fields []
static fielddef_t projectileinfo_fields []
static structdef_t weaponinfo_struct
static structdef_t projectileinfo_struct
static bot_weaponstate_t * botweaponstates [MAX_CLIENTS+1]
static weaponconfig_t * weaponconfig
Macro Definition Documentation
PROJECTILE_OFS
#define PROJECTILE_OFS (x) (size_t)&(((projectileinfo_t *)0)->x)
Definition at line 52 of file be_ai_weap.c.
WEAPON_OFS
#define WEAPON_OFS (x) (size_t)&(((weaponinfo_t *)0)->x)
Definition at line 51 of file be_ai_weap.c.
Typedef Documentation
bot_weaponstate_t
typedef struct bot_weaponstate_s bot_weaponstate_t
weaponconfig_t
typedef struct weaponconfig_s weaponconfig_t
Function Documentation
BotAllocWeaponState()
int BotAllocWeaponState (void)
Definition at line 450 of file be_ai_weap.c.
 {
     int i;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (!botweaponstates[i])
         {
             botweaponstates[i] = GetClearedMemory(sizeof(bot_weaponstate_t));
             return i;
         } //end if
     } //end for
     return 0;
 } //end of the function BotAllocWeaponState
References botweaponstates, GetClearedMemory(), and MAX_CLIENTS.
Referenced by Init_AI_Export().
BotChooseBestFightWeapon()
int BotChooseBestFightWeapon (int weaponstate, int * inventory)
Definition at line 404 of file be_ai_weap.c.
 {
     int i, index, bestweapon;
     float weight, bestweight;
     weaponconfig_t *wc;
     bot_weaponstate_t *ws;
     ws = BotWeaponStateFromHandle(weaponstate);
     if (!ws) return 0;
     wc = weaponconfig;
     if (!weaponconfig) return 0;
     //if the bot has no weapon weight configuration
     if (!ws->weaponweightconfig) return 0;
     bestweight = 0;
     bestweapon = 0;
     for (i = 0; i < wc->numweapons; i++)
     {
         if (!wc->weaponinfo[i].valid) continue;
         index = ws->weaponweightindex[i];
         if (index < 0) continue;
         weight = FuzzyWeight(inventory, ws->weaponweightconfig, index);
         if (weight > bestweight)
         {
             bestweight = weight;
             bestweapon = i;
         } //end if
     } //end for
     return bestweapon;
 } //end of the function BotChooseBestFightWeapon
References BotWeaponStateFromHandle(), FuzzyWeight(), weaponconfig_s::numweapons, weaponinfo_s::valid, weaponconfig, weaponconfig_s::weaponinfo, bot_weaponstate_s::weaponweightconfig, and bot_weaponstate_s::weaponweightindex.
Referenced by Init_AI_Export().
BotFreeWeaponState()
void BotFreeWeaponState (int handle)
Definition at line 470 of file be_ai_weap.c.
 {
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "weapon state handle %d out of range\n", handle);
         return;
     } //end if
     if (!botweaponstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid weapon state %d\n", handle);
         return;
     } //end if
     BotFreeWeaponWeights(handle);
     FreeMemory(botweaponstates[handle]);
     botweaponstates[handle] = NULL;
 } //end of the function BotFreeWeaponState
References BotFreeWeaponWeights(), botimport, botweaponstates, FreeMemory(), MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotShutdownWeaponAI(), and Init_AI_Export().
BotFreeWeaponWeights()
void BotFreeWeaponWeights (int weaponstate)
Definition at line 349 of file be_ai_weap.c.
 {
     bot_weaponstate_t *ws;
     ws = BotWeaponStateFromHandle(weaponstate);
     if (!ws) return;
     if (ws->weaponweightconfig) FreeWeightConfig(ws->weaponweightconfig);
     if (ws->weaponweightindex) FreeMemory(ws->weaponweightindex);
 } //end of the function BotFreeWeaponWeights
References BotWeaponStateFromHandle(), FreeMemory(), FreeWeightConfig(), bot_weaponstate_s::weaponweightconfig, and bot_weaponstate_s::weaponweightindex.
Referenced by BotFreeWeaponState(), and BotLoadWeaponWeights().
BotGetWeaponInfo()
void BotGetWeaponInfo (int weaponstate, int weapon, weaponinfo_t * weaponinfo)
Definition at line 388 of file be_ai_weap.c.
 {
     bot_weaponstate_t *ws;
     if (!BotValidWeaponNumber(weapon)) return;
     ws = BotWeaponStateFromHandle(weaponstate);
     if (!ws) return;
     if (!weaponconfig) return;
     Com_Memcpy(weaponinfo, &weaponconfig->weaponinfo[weapon], sizeof(weaponinfo_t));
 } //end of the function BotGetWeaponInfo
References BotValidWeaponNumber(), BotWeaponStateFromHandle(), Com_Memcpy, weaponconfig, and weaponconfig_s::weaponinfo.
Referenced by Init_AI_Export().
BotLoadWeaponWeights()
int BotLoadWeaponWeights (int weaponstate, char * filename)
Definition at line 364 of file be_ai_weap.c.
 {
     bot_weaponstate_t *ws;
     ws = BotWeaponStateFromHandle(weaponstate);
     if (!ws) return BLERR_CANNOTLOADWEAPONWEIGHTS;
     BotFreeWeaponWeights(weaponstate);
     //
     ws->weaponweightconfig = ReadWeightConfig(filename);
     if (!ws->weaponweightconfig)
     {
         botimport.Print(PRT_FATAL, "couldn't load weapon config %s\n", filename);
         return BLERR_CANNOTLOADWEAPONWEIGHTS;
     } //end if
     if (!weaponconfig) return BLERR_CANNOTLOADWEAPONCONFIG;
     ws->weaponweightindex = WeaponWeightIndex(ws->weaponweightconfig, weaponconfig);
     return BLERR_NOERROR;
 } //end of the function BotLoadWeaponWeights
References BLERR_CANNOTLOADWEAPONCONFIG, BLERR_CANNOTLOADWEAPONWEIGHTS, BLERR_NOERROR, BotFreeWeaponWeights(), botimport, BotWeaponStateFromHandle(), PRT_FATAL, ReadWeightConfig(), weaponconfig, bot_weaponstate_s::weaponweightconfig, bot_weaponstate_s::weaponweightindex, and WeaponWeightIndex().
Referenced by Init_AI_Export().
BotResetWeaponState()
void BotResetWeaponState (int weaponstate)
Definition at line 441 of file be_ai_weap.c.
 {
 } //end of the function BotResetWeaponState
Referenced by Init_AI_Export().
BotSetupWeaponAI()
int BotSetupWeaponAI (void)
Definition at line 492 of file be_ai_weap.c.
 {
     char *file;
     file = LibVarString("weaponconfig", "weapons.c");
     weaponconfig = LoadWeaponConfig(file);
     if (!weaponconfig)
     {
         botimport.Print(PRT_FATAL, "couldn't load the weapon config\n");
         return BLERR_CANNOTLOADWEAPONCONFIG;
     } //end if
 #ifdef DEBUG_AI_WEAP
     DumpWeaponConfig(weaponconfig);
 #endif //DEBUG_AI_WEAP
     //
     return BLERR_NOERROR;
 } //end of the function BotSetupWeaponAI
References BLERR_CANNOTLOADWEAPONCONFIG, BLERR_NOERROR, botimport, LibVarString(), LoadWeaponConfig(), PRT_FATAL, and weaponconfig.
Referenced by Export_BotLibSetup().
BotShutdownWeaponAI()
void BotShutdownWeaponAI (void)
Definition at line 516 of file be_ai_weap.c.
 {
     int i;
     if (weaponconfig) FreeMemory(weaponconfig);
     weaponconfig = NULL;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (botweaponstates[i])
         {
             BotFreeWeaponState(i);
         } //end if
     } //end for
 } //end of the function BotShutdownWeaponAI
References BotFreeWeaponState(), botweaponstates, FreeMemory(), MAX_CLIENTS, NULL, and weaponconfig.
Referenced by Export_BotLibShutdown().
BotValidWeaponNumber()
int BotValidWeaponNumber (int weaponnum)
Definition at line 137 of file be_ai_weap.c.
 {
     if (weaponnum <= 0 || weaponnum > weaponconfig->numweapons)
     {
         botimport.Print(PRT_ERROR, "weapon number out of range\n");
         return qfalse;
     } //end if
     return qtrue;
 } //end of the function BotValidWeaponNumber
References botimport, weaponconfig_s::numweapons, PRT_ERROR, qfalse, qtrue, and weaponconfig.
Referenced by BotGetWeaponInfo().
BotWeaponStateFromHandle()
bot_weaponstate_t* BotWeaponStateFromHandle (int handle)
Definition at line 152 of file be_ai_weap.c.
 {
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "weapon state handle %d out of range\n", handle);
         return NULL;
     } //end if
     if (!botweaponstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid weapon state %d\n", handle);
         return NULL;
     } //end if
     return botweaponstates[handle];
 } //end of the function BotWeaponStateFromHandle
References botimport, botweaponstates, MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotChooseBestFightWeapon(), BotFreeWeaponWeights(), BotGetWeaponInfo(), and BotLoadWeaponWeights().
LoadWeaponConfig()
weaponconfig_t* LoadWeaponConfig (char * filename)
Definition at line 198 of file be_ai_weap.c.
 {
     int max_weaponinfo, max_projectileinfo;
     token_t token;
     char path[MAX_QPATH];
     int i, j;
     source_t *source;
     weaponconfig_t *wc;
     weaponinfo_t weaponinfo;
     max_weaponinfo = (int) LibVarValue("max_weaponinfo", "32");
     if (max_weaponinfo < 0)
     {
         botimport.Print(PRT_ERROR, "max_weaponinfo = %d\n", max_weaponinfo);
         max_weaponinfo = 32;
         LibVarSet("max_weaponinfo", "32");
     } //end if
     max_projectileinfo = (int) LibVarValue("max_projectileinfo", "32");
     if (max_projectileinfo < 0)
     {
         botimport.Print(PRT_ERROR, "max_projectileinfo = %d\n", max_projectileinfo);
         max_projectileinfo = 32;
         LibVarSet("max_projectileinfo", "32");
     } //end if
     Q_strncpyz(path, filename, sizeof(path));
     PC_SetBaseFolder(BOTFILESBASEFOLDER);
     source = LoadSourceFile(path);
     if (!source)
     {
         botimport.Print(PRT_ERROR, "counldn't load %s\n", path);
         return NULL;
     } //end if
     //initialize weapon config
     wc = (weaponconfig_t *) GetClearedHunkMemory(sizeof(weaponconfig_t) +
                                         max_weaponinfo * sizeof(weaponinfo_t) +
                                         max_projectileinfo * sizeof(projectileinfo_t));
     wc->weaponinfo = (weaponinfo_t *) ((char *) wc + sizeof(weaponconfig_t));
     wc->projectileinfo = (projectileinfo_t *) ((char *) wc->weaponinfo +
                                         max_weaponinfo * sizeof(weaponinfo_t));
     wc->numweapons = max_weaponinfo;
     wc->numprojectiles = 0;
     //parse the source file
     while(PC_ReadToken(source, &token))
     {
         if (!strcmp(token.string, "weaponinfo"))
         {
             Com_Memset(&weaponinfo, 0, sizeof(weaponinfo_t));
             if (!ReadStructure(source, &weaponinfo_struct, (char *) &weaponinfo))
             {
                 FreeMemory(wc);
                 FreeSource(source);
                 return NULL;
             } //end if
             if (weaponinfo.number < 0 || weaponinfo.number >= max_weaponinfo)
             {
                 botimport.Print(PRT_ERROR, "weapon info number %d out of range in %s\n", weaponinfo.number, path);
                 FreeMemory(wc);
                 FreeSource(source);
                 return NULL;
             } //end if
             Com_Memcpy(&wc->weaponinfo[weaponinfo.number], &weaponinfo, sizeof(weaponinfo_t));
             wc->weaponinfo[weaponinfo.number].valid = qtrue;
         } //end if
         else if (!strcmp(token.string, "projectileinfo"))
         {
             if (wc->numprojectiles >= max_projectileinfo)
             {
                 botimport.Print(PRT_ERROR, "more than %d projectiles defined in %s\n", max_projectileinfo, path);
                 FreeMemory(wc);
                 FreeSource(source);
                 return NULL;
             } //end if
             Com_Memset(&wc->projectileinfo[wc->numprojectiles], 0, sizeof(projectileinfo_t));
             if (!ReadStructure(source, &projectileinfo_struct, (char *) &wc->projectileinfo[wc->numprojectiles]))
             {
                 FreeMemory(wc);
                 FreeSource(source);
                 return NULL;
             } //end if
             wc->numprojectiles++;
         } //end if
         else
         {
             botimport.Print(PRT_ERROR, "unknown definition %s in %s\n", token.string, path);
             FreeMemory(wc);
             FreeSource(source);
             return NULL;
         } //end else
     } //end while
     FreeSource(source);
     //fix up weapons
     for (i = 0; i < wc->numweapons; i++)
     {
         if (!wc->weaponinfo[i].valid) continue;
         if (!wc->weaponinfo[i].name[0])
         {
             botimport.Print(PRT_ERROR, "weapon %d has no name in %s\n", i, path);
             FreeMemory(wc);
             return NULL;
         } //end if
         if (!wc->weaponinfo[i].projectile[0])
         {
             botimport.Print(PRT_ERROR, "weapon %s has no projectile in %s\n", wc->weaponinfo[i].name, path);
             FreeMemory(wc);
             return NULL;
         } //end if
         //find the projectile info and copy it to the weapon info
         for (j = 0; j < wc->numprojectiles; j++)
         {
             if (!strcmp(wc->projectileinfo[j].name, wc->weaponinfo[i].projectile))
             {
                 Com_Memcpy(&wc->weaponinfo[i].proj, &wc->projectileinfo[j], sizeof(projectileinfo_t));
                 break;
             } //end if
         } //end for
         if (j == wc->numprojectiles)
         {
             botimport.Print(PRT_ERROR, "weapon %s uses undefined projectile in %s\n", wc->weaponinfo[i].name, path);
             FreeMemory(wc);
             return NULL;
         } //end if
     } //end for
     if (!wc->numweapons) botimport.Print(PRT_WARNING, "no weapon info loaded\n");
     botimport.Print(PRT_MESSAGE, "loaded %s\n", path);
     return wc;
 } //end of the function LoadWeaponConfig
References BOTFILESBASEFOLDER, botimport, Com_Memcpy, Com_Memset, FreeMemory(), FreeSource(), GetClearedHunkMemory(), int(), LibVarSet(), LibVarValue(), LoadSourceFile(), MAX_QPATH, projectileinfo_s::name, weaponinfo_s::name, NULL, weaponconfig_s::numprojectiles, weaponconfig_s::numweapons, PC_ReadToken(), PC_SetBaseFolder(), weaponinfo_s::proj, weaponinfo_s::projectile, weaponconfig_s::projectileinfo, projectileinfo_struct, PRT_ERROR, PRT_MESSAGE, PRT_WARNING, Q_strncpyz(), qtrue, ReadStructure(), token_s::string, weaponinfo_s::valid, weaponconfig_s::weaponinfo, and weaponinfo_struct.
Referenced by BotSetupWeaponAI().
WeaponWeightIndex()
int* WeaponWeightIndex (weightconfig_t * wwc, weaponconfig_t * wc)
Definition at line 330 of file be_ai_weap.c.
 {
     int *index, i;
     //initialize item weight index
     index = (int *) GetClearedMemory(sizeof(int) * wc->numweapons);
     for (i = 0; i < wc->numweapons; i++)
     {
         index[i] = FindFuzzyWeight(wwc, wc->weaponinfo[i].name);
     } //end for
     return index;
 } //end of the function WeaponWeightIndex
References FindFuzzyWeight(), GetClearedMemory(), weaponinfo_s::name, weaponconfig_s::numweapons, and weaponconfig_s::weaponinfo.
Referenced by BotLoadWeaponWeights().
Variable Documentation
botweaponstates
bot_weaponstate_t* botweaponstates[MAX_CLIENTS+1] static
Definition at line 128 of file be_ai_weap.c.
Referenced by BotAllocWeaponState(), BotFreeWeaponState(), BotShutdownWeaponAI(), and BotWeaponStateFromHandle().
projectileinfo_fields
fielddef_t projectileinfo_fields[] static
Initial value:
=
{
{"name", PROJECTILE_OFS(name), FT_STRING},
{"model", PROJECTILE_OFS(model), FT_STRING},
{"flags", PROJECTILE_OFS(flags), FT_INT},
{"gravity", PROJECTILE_OFS(gravity), FT_FLOAT},
{"damage", PROJECTILE_OFS(damage), FT_INT},
{"radius", PROJECTILE_OFS(radius), FT_FLOAT},
{"visdamage", PROJECTILE_OFS(visdamage), FT_INT},
{"damagetype", PROJECTILE_OFS(damagetype), FT_INT},
{"healthinc", PROJECTILE_OFS(healthinc), FT_INT},
{"push", PROJECTILE_OFS(push), FT_FLOAT},
{"detonation", PROJECTILE_OFS(detonation), FT_FLOAT},
{"bounce", PROJECTILE_OFS(bounce), FT_FLOAT},
{"bouncefric", PROJECTILE_OFS(bouncefric), FT_FLOAT},
{"bouncestop", PROJECTILE_OFS(bouncestop), FT_FLOAT},
{NULL, 0, 0, 0}
}
Definition at line 83 of file be_ai_weap.c.
projectileinfo_struct
structdef_t projectileinfo_struct static
Initial value:
=
{
    sizeof(projectileinfo_t), projectileinfo_fields
}
Definition at line 107 of file be_ai_weap.c.
Referenced by LoadWeaponConfig().
weaponconfig
weaponconfig_t* weaponconfig static
Definition at line 129 of file be_ai_weap.c.
Referenced by BotChooseBestFightWeapon(), BotGetWeaponInfo(), BotLoadWeaponWeights(), BotSetupWeaponAI(), BotShutdownWeaponAI(), and BotValidWeaponNumber().
weaponinfo_fields
fielddef_t weaponinfo_fields[] static
Initial value:
=
{
{"number", WEAPON_OFS(number), FT_INT},
{"name", WEAPON_OFS(name), FT_STRING},
{"level", WEAPON_OFS(level), FT_INT},
{"model", WEAPON_OFS(model), FT_STRING},
{"weaponindex", WEAPON_OFS(weaponindex), FT_INT},
{"flags", WEAPON_OFS(flags), FT_INT},
{"projectile", WEAPON_OFS(projectile), FT_STRING},
{"numprojectiles", WEAPON_OFS(numprojectiles), FT_INT},
{"hspread", WEAPON_OFS(hspread), FT_FLOAT},
{"vspread", WEAPON_OFS(vspread), FT_FLOAT},
{"speed", WEAPON_OFS(speed), FT_FLOAT},
{"acceleration", WEAPON_OFS(acceleration), FT_FLOAT},
{"recoil", WEAPON_OFS(recoil), FT_FLOAT|FT_ARRAY, 3},
{"offset", WEAPON_OFS(offset), FT_FLOAT|FT_ARRAY, 3},
{"angleoffset", WEAPON_OFS(angleoffset), FT_FLOAT|FT_ARRAY, 3},
{"extrazvelocity", WEAPON_OFS(extrazvelocity), FT_FLOAT},
{"ammoamount", WEAPON_OFS(ammoamount), FT_INT},
{"ammoindex", WEAPON_OFS(ammoindex), FT_INT},
{"activate", WEAPON_OFS(activate), FT_FLOAT},
{"reload", WEAPON_OFS(reload), FT_FLOAT},
{"spinup", WEAPON_OFS(spinup), FT_FLOAT},
{"spindown", WEAPON_OFS(spindown), FT_FLOAT},
{NULL, 0, 0, 0}
}
Definition at line 55 of file be_ai_weap.c.
weaponinfo_struct
structdef_t weaponinfo_struct static
Initial value:
=
{
    sizeof(weaponinfo_t), weaponinfo_fields
}
Definition at line 103 of file be_ai_weap.c.
Referenced by LoadWeaponConfig().