ioquake3 doxygen: C:/entry/dev/ioq3/code/ui/ui_atoms.c File Reference
ui_atoms.c File Reference
#include "ui_local.h"
Functions
void QDECL Com_Error (int level, const char *error,...)
void QDECL Com_Printf (const char *msg,...)
float UI_ClampCvar (float min, float max, float value)
void UI_StartDemoLoop (void)
static void NeedCDAction (qboolean result)
static void NeedCDKeyAction (qboolean result)
char * UI_Argv (int arg)
char * UI_Cvar_VariableString (const char *var_name)
void UI_SetBestScores (postGameInfo_t *newInfo, qboolean postGame)
void UI_LoadBestScores (const char *map, int game)
void UI_ClearScores (void)
static void UI_Cache_f (void)
static void UI_CalcPostGameStats (void)
qboolean UI_ConsoleCommand (int realTime)
void UI_Shutdown (void)
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
void UI_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_DrawSides (float x, float y, float w, float h)
void UI_DrawTopBottom (float x, float y, float w, float h)
void UI_DrawRect (float x, float y, float width, float height, const float *color)
void UI_SetColor (const float *rgba)
void UI_UpdateScreen (void)
void UI_DrawTextBox (int x, int y, int width, int lines)
qboolean UI_CursorInRect (int x, int y, int width, int height)
Variables
qboolean m_entersound
qboolean newUI = qfalse
Function Documentation
Com_Error()
void QDECL Com_Error (int level, const char * error, ...)
Definition at line 32 of file ui_atoms.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, error);
     Q_vsnprintf (text, sizeof(text), error, argptr);
     va_end (argptr);
     trap_Error( text );
 }
References Q_vsnprintf(), and trap_Error().
Com_Printf()
void QDECL Com_Printf (const char * msg, ...)
Definition at line 43 of file ui_atoms.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, msg);
     Q_vsnprintf (text, sizeof(text), msg, argptr);
     va_end (argptr);
     trap_Print( text );
 }
References Q_vsnprintf(), and trap_Print().
NeedCDAction()
static void NeedCDAction (qboolean result) static
Definition at line 80 of file ui_atoms.c.
{
     if ( !result ) {
         trap_Cmd_ExecuteText( EXEC_APPEND, "quit\n" );
     }
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
NeedCDKeyAction()
static void NeedCDKeyAction (qboolean result) static
Definition at line 88 of file ui_atoms.c.
{
     if ( !result ) {
         trap_Cmd_ExecuteText( EXEC_APPEND, "quit\n" );
     }
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
UI_AdjustFrom640()
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 421 of file ui_atoms.c.
{
     // expect valid pointers
     *x = *x * uiInfo.uiDC.xscale + uiInfo.uiDC.bias;
     *y *= uiInfo.uiDC.yscale;
     *w *= uiInfo.uiDC.xscale;
     *h *= uiInfo.uiDC.yscale;
 }
References displayContextDef_t::bias, uiStatic_t::bias, uiInfo_t::uiDC, uiInfo, uis, displayContextDef_t::xscale, uiStatic_t::xscale, displayContextDef_t::yscale, and uiStatic_t::yscale.
UI_Argv()
char* UI_Argv (int arg)
Definition at line 95 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Argv( arg, buffer, sizeof( buffer ) );
     return buffer;
 }
References buffer, MAX_STRING_CHARS, and trap_Argv().
UI_Cache_f()
static void UI_Cache_f (void) static
Definition at line 231 of file ui_atoms.c.
{
     Display_CacheAll();
 }
References Display_CacheAll().
UI_CalcPostGameStats()
static void UI_CalcPostGameStats (void) static
Definition at line 240 of file ui_atoms.c.
{
     char        map[MAX_QPATH];
     char        fileName[MAX_QPATH];
     char        info[MAX_INFO_STRING];
     fileHandle_t f;
     int size, game, time, adjustedTime;
     postGameInfo_t oldInfo;
     postGameInfo_t newInfo;
     qboolean newHigh = qfalse;
     trap_GetConfigString( CS_SERVERINFO, info, sizeof(info) );
     Q_strncpyz( map, Info_ValueForKey( info, "mapname" ), sizeof(map) );
     game = atoi(Info_ValueForKey(info, "g_gametype"));
     // compose file name
     Com_sprintf(fileName, MAX_QPATH, "games/%s_%i.game", map, game);
     // see if we have one already
     memset(&oldInfo, 0, sizeof(postGameInfo_t));
     if (trap_FS_FOpenFile(fileName, &f, FS_READ) >= 0) {
     // if so load it
         size = 0;
         trap_FS_Read(&size, sizeof(int), f);
         if (size == sizeof(postGameInfo_t)) {
             trap_FS_Read(&oldInfo, sizeof(postGameInfo_t), f);
         }
         trap_FS_FCloseFile(f);
     }
     newInfo.accuracy = atoi(UI_Argv(3));
     newInfo.impressives = atoi(UI_Argv(4));
     newInfo.excellents = atoi(UI_Argv(5));
     newInfo.defends = atoi(UI_Argv(6));
     newInfo.assists = atoi(UI_Argv(7));
     newInfo.gauntlets = atoi(UI_Argv(8));
     newInfo.baseScore = atoi(UI_Argv(9));
     newInfo.perfects = atoi(UI_Argv(10));
     newInfo.redScore = atoi(UI_Argv(11));
     newInfo.blueScore = atoi(UI_Argv(12));
     time = atoi(UI_Argv(13));
     newInfo.captures = atoi(UI_Argv(14));
     newInfo.time = (time - trap_Cvar_VariableValue("ui_matchStartTime")) / 1000;
     adjustedTime = uiInfo.mapList[ui_currentMap.integer].timeToBeat[game];
     if (newInfo.time < adjustedTime) {
         newInfo.timeBonus = (adjustedTime - newInfo.time) * 10;
     } else {
         newInfo.timeBonus = 0;
     }
     if (newInfo.redScore > newInfo.blueScore && newInfo.blueScore <= 0) {
         newInfo.shutoutBonus = 100;
     } else {
         newInfo.shutoutBonus = 0;
     }
     newInfo.skillBonus = trap_Cvar_VariableValue("g_spSkill");
     if (newInfo.skillBonus <= 0) {
         newInfo.skillBonus = 1;
     }
     newInfo.score = newInfo.baseScore + newInfo.shutoutBonus + newInfo.timeBonus;
     newInfo.score *= newInfo.skillBonus;
     // see if the score is higher for this one
     newHigh = (newInfo.redScore > newInfo.blueScore && newInfo.score > oldInfo.score);
     if  (newHigh) {
         // if so write out the new one
         uiInfo.newHighScoreTime = uiInfo.uiDC.realTime + 20000;
         if (trap_FS_FOpenFile(fileName, &f, FS_WRITE) >= 0) {
             size = sizeof(postGameInfo_t);
             trap_FS_Write(&size, sizeof(int), f);
             trap_FS_Write(&newInfo, sizeof(postGameInfo_t), f);
             trap_FS_FCloseFile(f);
         }
     }
     if (newInfo.time < oldInfo.time) {
         uiInfo.newBestTime = uiInfo.uiDC.realTime + 20000;
     }
     // put back all the ui overrides
     trap_Cvar_Set("capturelimit", UI_Cvar_VariableString("ui_saveCaptureLimit"));
     trap_Cvar_Set("fraglimit", UI_Cvar_VariableString("ui_saveFragLimit"));
     trap_Cvar_Set("cg_drawTimer", UI_Cvar_VariableString("ui_drawTimer"));
     trap_Cvar_Set("g_doWarmup", UI_Cvar_VariableString("ui_doWarmup"));
     trap_Cvar_Set("g_Warmup", UI_Cvar_VariableString("ui_Warmup"));
     trap_Cvar_Set("sv_pure", UI_Cvar_VariableString("ui_pure"));
     trap_Cvar_Set("g_friendlyFire", UI_Cvar_VariableString("ui_friendlyFire"));
     UI_SetBestScores(&newInfo, qtrue);
     UI_ShowPostGame(newHigh);
 }
References postGameInfo_s::accuracy, postGameInfo_s::assists, postGameInfo_s::baseScore, postGameInfo_s::blueScore, postGameInfo_s::captures, Com_sprintf(), CS_SERVERINFO, postGameInfo_s::defends, postGameInfo_s::excellents, FS_READ, FS_WRITE, postGameInfo_s::gauntlets, postGameInfo_s::impressives, Info_ValueForKey(), vmCvar_t::integer, uiInfo_t::mapList, MAX_INFO_STRING, MAX_QPATH, uiInfo_t::newBestTime, uiInfo_t::newHighScoreTime, postGameInfo_s::perfects, Q_strncpyz(), qfalse, qtrue, displayContextDef_t::realTime, postGameInfo_s::redScore, postGameInfo_s::score, postGameInfo_s::shutoutBonus, postGameInfo_s::skillBonus, postGameInfo_s::time, postGameInfo_s::timeBonus, mapInfo::timeToBeat, trap_Cvar_Set(), trap_Cvar_VariableValue(), trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_FS_Write(), trap_GetConfigString(), UI_Argv(), ui_currentMap, UI_Cvar_VariableString(), UI_SetBestScores(), UI_ShowPostGame(), uiInfo_t::uiDC, and uiInfo.
Referenced by UI_ConsoleCommand().
UI_ClampCvar()
float UI_ClampCvar (float min, float max, float value)
Definition at line 62 of file ui_atoms.c.
 {
     if ( value < min ) return min;
     if ( value > max ) return max;
     return value;
 }
UI_ClearScores()
void UI_ClearScores (void)
Definition at line 200 of file ui_atoms.c.
{
     char    gameList[4096];
     char *gameFile;
     int     i, len, count, size;
     fileHandle_t f;
     postGameInfo_t newInfo;
     count = trap_FS_GetFileList( "games", "game", gameList, sizeof(gameList) );
     size = sizeof(postGameInfo_t);
     memset(&newInfo, 0, size);
     if (count > 0) {
         gameFile = gameList;
         for ( i = 0; i < count; i++ ) {
             len = strlen(gameFile);
             if (trap_FS_FOpenFile(va("games/%s",gameFile), &f, FS_WRITE) >= 0) {
                 trap_FS_Write(&size, sizeof(int), f);
                 trap_FS_Write(&newInfo, size, f);
                 trap_FS_FCloseFile(f);
             }
             gameFile += len + 1;
         }
     }
     UI_SetBestScores(&newInfo, qfalse);
 }
References count, FS_WRITE, qfalse, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_GetFileList(), trap_FS_Write(), UI_SetBestScores(), and va().
Referenced by UI_RunMenuScript().
UI_ConsoleCommand()
qboolean UI_ConsoleCommand (int realTime)
Definition at line 341 of file ui_atoms.c.
{
     char    *cmd;
     uiInfo.uiDC.frameTime = realTime - uiInfo.uiDC.realTime;
     uiInfo.uiDC.realTime = realTime;
     cmd = UI_Argv( 0 );
     // ensure minimum menu data is available
     //Menu_Cache();
     if ( Q_stricmp (cmd, "ui_test") == 0 ) {
         UI_ShowPostGame(qtrue);
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_report") == 0 ) {
         UI_Report();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_load") == 0 ) {
         UI_Load();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "remapShader") == 0 ) {
         if (trap_Argc() == 4) {
             char shader1[MAX_QPATH];
             char shader2[MAX_QPATH];
             char shader3[MAX_QPATH];
             Q_strncpyz(shader1, UI_Argv(1), sizeof(shader1));
             Q_strncpyz(shader2, UI_Argv(2), sizeof(shader2));
             Q_strncpyz(shader3, UI_Argv(3), sizeof(shader3));
             trap_R_RemapShader(shader1, shader2, shader3);
             return qtrue;
         }
     }
     if ( Q_stricmp (cmd, "postgame") == 0 ) {
         UI_CalcPostGameStats();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cache") == 0 ) {
         UI_Cache_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_teamOrders") == 0 ) {
         //UI_TeamOrdersMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cdkey") == 0 ) {
         //UI_CDKeyMenu_f();
         return qtrue;
     }
     return qfalse;
 }
References displayContextDef_t::frameTime, uiStatic_t::frametime, MAX_QPATH, Menu_Cache(), Q_stricmp(), Q_strncpyz(), qfalse, qtrue, displayContextDef_t::realTime, uiStatic_t::realtime, trap_Argc(), trap_R_RemapShader(), UI_Argv(), UI_Cache_f(), UI_CalcPostGameStats(), UI_CDKeyMenu_f(), UI_CinematicsMenu_f(), UI_Load(), UI_Report(), UI_ShowPostGame(), UI_SPLevelMenu_f(), UI_SPPostgameMenu_f(), UI_SPUnlock_f(), UI_SPUnlockMedals_f(), UI_TeamOrdersMenu_f(), uiInfo_t::uiDC, uiInfo, and uis.
UI_CursorInRect()
qboolean UI_CursorInRect (int x, int y, int width, int height)
Definition at line 525 of file ui_atoms.c.
 {
     if (uiInfo.uiDC.cursorx < x ||
         uiInfo.uiDC.cursory < y ||
         uiInfo.uiDC.cursorx > x+width ||
         uiInfo.uiDC.cursory > y+height)
         return qfalse;
     return qtrue;
 }
References displayContextDef_t::cursorx, uiStatic_t::cursorx, displayContextDef_t::cursory, uiStatic_t::cursory, qfalse, qtrue, uiInfo_t::uiDC, uiInfo, and uis.
UI_Cvar_VariableString()
char* UI_Cvar_VariableString (const char * var_name)
Definition at line 104 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Cvar_VariableStringBuffer( var_name, buffer, sizeof( buffer ) );
     return buffer;
 }
References buffer, MAX_STRING_CHARS, and trap_Cvar_VariableStringBuffer().
UI_DrawHandlePic()
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
Definition at line 437 of file ui_atoms.c.
{
     float   s0;
     float   s1;
     float   t0;
     float   t1;
     if( w < 0 ) {   // flip about vertical
         w  = -w;
         s0 = 1;
         s1 = 0;
     }
     else {
         s0 = 0;
         s1 = 1;
     }
     if( h < 0 ) {   // flip about horizontal
         h  = -h;
         t0 = 1;
         t1 = 0;
     }
     else {
         t0 = 0;
         t1 = 1;
     }
     UI_AdjustFrom640( &x, &y, &w, &h );
     trap_R_DrawStretchPic( x, y, w, h, s0, t0, s1, t1, hShader );
 }
References trap_R_DrawStretchPic(), and UI_AdjustFrom640().
UI_DrawNamedPic()
void UI_DrawNamedPic (float x, float y, float width, float height, const char * picname)
Definition at line 429 of file ui_atoms.c.
{
     qhandle_t   hShader;
     hShader = trap_R_RegisterShaderNoMip( picname );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
References trap_R_DrawStretchPic(), trap_R_RegisterShaderNoMip(), and UI_AdjustFrom640().
UI_DrawRect()
void UI_DrawRect (float x, float y, float width, float height, const float * color)
Definition at line 501 of file ui_atoms.c.
{
     trap_R_SetColor( color );
   UI_DrawTopBottom(x, y, width, height);
   UI_DrawSides(x, y, width, height);
     trap_R_SetColor( NULL );
 }
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), UI_DrawSides(), UI_DrawTopBottom(), uis, and uiStatic_t::whiteShader.
UI_DrawSides()
void UI_DrawSides (float x, float y, float w, float h)
Definition at line 483 of file ui_atoms.c.
{
     UI_AdjustFrom640( &x, &y, &w, &h );
     trap_R_DrawStretchPic( x, y, 1, h, 0, 0, 0, 0, uiInfo.uiDC.whiteShader );
     trap_R_DrawStretchPic( x + w - 1, y, 1, h, 0, 0, 0, 0, uiInfo.uiDC.whiteShader );
 }
References trap_R_DrawStretchPic(), UI_AdjustFrom640(), uiInfo_t::uiDC, uiInfo, and displayContextDef_t::whiteShader.
Referenced by UI_DrawRect().
UI_DrawTextBox()
void UI_DrawTextBox (int x, int y, int width, int lines)
Definition at line 519 of file ui_atoms.c.
 {
     UI_FillRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorBlack );
     UI_DrawRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorWhite );
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, colorBlack, colorWhite, UI_DrawRect(), and UI_FillRect().
UI_DrawTopBottom()
void UI_DrawTopBottom (float x, float y, float w, float h)
Definition at line 489 of file ui_atoms.c.
{
     UI_AdjustFrom640( &x, &y, &w, &h );
     trap_R_DrawStretchPic( x, y, w, 1, 0, 0, 0, 0, uiInfo.uiDC.whiteShader );
     trap_R_DrawStretchPic( x, y + h - 1, w, 1, 0, 0, 0, 0, uiInfo.uiDC.whiteShader );
 }
References trap_R_DrawStretchPic(), UI_AdjustFrom640(), uiInfo_t::uiDC, uiInfo, and displayContextDef_t::whiteShader.
Referenced by UI_DrawRect().
UI_FillRect()
void UI_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 474 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 0, 0, uiInfo.uiDC.whiteShader );
     trap_R_SetColor( NULL );
 }
References NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), UI_AdjustFrom640(), uiInfo_t::uiDC, uiInfo, uis, displayContextDef_t::whiteShader, and uiStatic_t::whiteShader.
UI_LoadBestScores()
void UI_LoadBestScores (const char * map, int game)
Definition at line 149 of file ui_atoms.c.
 {
     char        fileName[MAX_QPATH];
     fileHandle_t f;
     postGameInfo_t newInfo;
     int protocol, protocolLegacy;
     memset(&newInfo, 0, sizeof(postGameInfo_t));
     Com_sprintf(fileName, MAX_QPATH, "games/%s_%i.game", map, game);
     if (trap_FS_FOpenFile(fileName, &f, FS_READ) >= 0) {
         int size = 0;
         trap_FS_Read(&size, sizeof(int), f);
         if (size == sizeof(postGameInfo_t)) {
             trap_FS_Read(&newInfo, sizeof(postGameInfo_t), f);
         }
         trap_FS_FCloseFile(f);
     }
     UI_SetBestScores(&newInfo, qfalse);
     uiInfo.demoAvailable = qfalse;
     protocolLegacy = trap_Cvar_VariableValue("com_legacyprotocol");
     protocol = trap_Cvar_VariableValue("com_protocol");
     if(!protocol)
         protocol = trap_Cvar_VariableValue("protocol");
     if(protocolLegacy == protocol)
         protocolLegacy = 0;
     Com_sprintf(fileName, MAX_QPATH, "demos/%s_%d.%s%d", map, game, DEMOEXT, protocol);
     if(trap_FS_FOpenFile(fileName, &f, FS_READ) >= 0)
     {
         uiInfo.demoAvailable = qtrue;
         trap_FS_FCloseFile(f);
     }
     else if(protocolLegacy > 0)
     {
         Com_sprintf(fileName, MAX_QPATH, "demos/%s_%d.%s%d", map, game, DEMOEXT, protocolLegacy);
         if (trap_FS_FOpenFile(fileName, &f, FS_READ) >= 0)
         {
             uiInfo.demoAvailable = qtrue;
             trap_FS_FCloseFile(f);
         }
     }
 }
References Com_sprintf(), uiInfo_t::demoAvailable, DEMOEXT, FS_READ, MAX_QPATH, qfalse, qtrue, trap_Cvar_VariableValue(), trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), UI_SetBestScores(), and uiInfo.
Referenced by _UI_Init(), UI_FeederSelection(), UI_GameType_HandleKey(), and UI_RunMenuScript().
UI_SetBestScores()
void UI_SetBestScores (postGameInfo_t * newInfo, qboolean postGame)
Definition at line 114 of file ui_atoms.c.
{
     trap_Cvar_Set("ui_scoreAccuracy",     va("%i%%", newInfo->accuracy));
     trap_Cvar_Set("ui_scoreImpressives",    va("%i", newInfo->impressives));
     trap_Cvar_Set("ui_scoreExcellents",     va("%i", newInfo->excellents));
     trap_Cvar_Set("ui_scoreDefends",            va("%i", newInfo->defends));
     trap_Cvar_Set("ui_scoreAssists",            va("%i", newInfo->assists));
     trap_Cvar_Set("ui_scoreGauntlets",      va("%i", newInfo->gauntlets));
     trap_Cvar_Set("ui_scoreScore",              va("%i", newInfo->score));
     trap_Cvar_Set("ui_scorePerfect",            va("%i", newInfo->perfects));
     trap_Cvar_Set("ui_scoreTeam",                   va("%i to %i", newInfo->redScore, newInfo->blueScore));
     trap_Cvar_Set("ui_scoreBase",                   va("%i", newInfo->baseScore));
     trap_Cvar_Set("ui_scoreTimeBonus",      va("%i", newInfo->timeBonus));
     trap_Cvar_Set("ui_scoreSkillBonus",     va("%i", newInfo->skillBonus));
     trap_Cvar_Set("ui_scoreShutoutBonus",   va("%i", newInfo->shutoutBonus));
     trap_Cvar_Set("ui_scoreTime",                   va("%02i:%02i", newInfo->time / 60, newInfo->time % 60));
     trap_Cvar_Set("ui_scoreCaptures",       va("%i", newInfo->captures));
   if (postGame) {
         trap_Cvar_Set("ui_scoreAccuracy2",     va("%i%%", newInfo->accuracy));
         trap_Cvar_Set("ui_scoreImpressives2",   va("%i", newInfo->impressives));
         trap_Cvar_Set("ui_scoreExcellents2",    va("%i", newInfo->excellents));
         trap_Cvar_Set("ui_scoreDefends2",           va("%i", newInfo->defends));
         trap_Cvar_Set("ui_scoreAssists2",           va("%i", newInfo->assists));
         trap_Cvar_Set("ui_scoreGauntlets2",         va("%i", newInfo->gauntlets));
         trap_Cvar_Set("ui_scoreScore2",                 va("%i", newInfo->score));
         trap_Cvar_Set("ui_scorePerfect2",           va("%i", newInfo->perfects));
         trap_Cvar_Set("ui_scoreTeam2",                  va("%i to %i", newInfo->redScore, newInfo->blueScore));
         trap_Cvar_Set("ui_scoreBase2",                  va("%i", newInfo->baseScore));
         trap_Cvar_Set("ui_scoreTimeBonus2",     va("%i", newInfo->timeBonus));
         trap_Cvar_Set("ui_scoreSkillBonus2",        va("%i", newInfo->skillBonus));
         trap_Cvar_Set("ui_scoreShutoutBonus2",  va("%i", newInfo->shutoutBonus));
         trap_Cvar_Set("ui_scoreTime2",                  va("%02i:%02i", newInfo->time / 60, newInfo->time % 60));
         trap_Cvar_Set("ui_scoreCaptures2",      va("%i", newInfo->captures));
     }
 }
References postGameInfo_s::accuracy, postGameInfo_s::assists, postGameInfo_s::baseScore, postGameInfo_s::blueScore, postGameInfo_s::captures, postGameInfo_s::defends, postGameInfo_s::excellents, postGameInfo_s::gauntlets, postGameInfo_s::impressives, postGameInfo_s::perfects, postGameInfo_s::redScore, postGameInfo_s::score, postGameInfo_s::shutoutBonus, postGameInfo_s::skillBonus, postGameInfo_s::time, postGameInfo_s::timeBonus, trap_Cvar_Set(), and va().
Referenced by UI_CalcPostGameStats(), UI_ClearScores(), and UI_LoadBestScores().
UI_SetColor()
void UI_SetColor (const float * rgba)
Definition at line 510 of file ui_atoms.c.
{
     trap_R_SetColor( rgba );
 }
References trap_R_SetColor().
UI_Shutdown()
void UI_Shutdown (void)
Definition at line 411 of file ui_atoms.c.
{
 }
UI_StartDemoLoop()
void UI_StartDemoLoop (void)
Definition at line 74 of file ui_atoms.c.
{
     trap_Cmd_ExecuteText( EXEC_APPEND, "d1\n" );
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
UI_UpdateScreen()
void UI_UpdateScreen (void)
Definition at line 514 of file ui_atoms.c.
{
     trap_UpdateScreen();
 }
References trap_UpdateScreen().
Variable Documentation
m_entersound
qboolean m_entersound
Definition at line 30 of file ui_atoms.c.
newUI
qboolean newUI = qfalse
Definition at line 54 of file ui_atoms.c.