ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_local.h File Reference
g_local.h File Reference
#include "../qcommon/q_shared.h"
#include "bg_public.h"
#include "g_public.h"
#include "g_team.h"
Classes
struct gentity_s
struct playerTeamState_t
struct clientSession_t
Client data that stays across multiple levels or tournament restarts.
struct clientPersistant_t
Client data that stays across multiple respawns, but is cleared on each level change or team change at ClientBegin().
struct gclient_s
The data structure for a client connection.
struct level_locals_t
struct bot_settings_s
Macros
#define GAMEVERSION BASEGAME
#define BODY_QUEUE_SIZE 8
#define INFINITE 1000000
#define FRAMETIME 100
#define CARNAGE_REWARD_TIME 3000
#define REWARD_SPRITE_TIME 2000
#define INTERMISSION_DELAY_TIME 1000
#define SP_INTERMISSION_DELAY_TIME 5000
#define FL_GODMODE 0x00000010
#define FL_NOTARGET 0x00000020
#define FL_TEAMSLAVE 0x00000400
#define FL_NO_KNOCKBACK 0x00000800
#define FL_DROPPED_ITEM 0x00001000
#define FL_NO_BOTS 0x00002000
#define FL_NO_HUMANS 0x00004000
#define FL_FORCE_GESTURE 0x00008000
#define SP_PODIUM_MODEL "models/mapobjects/podium/podium4.md3"
#define MAX_NETNAME 36
#define MAX_VOTE_COUNT 3
#define MAX_SPAWN_VARS 64
#define MAX_SPAWN_VARS_CHARS 4096
#define DAMAGE_RADIUS 0x00000001
#define DAMAGE_NO_ARMOR 0x00000002
#define DAMAGE_NO_KNOCKBACK 0x00000004
#define DAMAGE_NO_PROTECTION 0x00000008
#define MAX_FILEPATH 144
#define FOFS(x) ((size_t)&(((gentity_t *)0)->x))
Typedefs
typedef struct gentity_s gentity_t
typedef struct gclient_s gclient_t
typedef struct bot_settings_s bot_settings_t
Enumerations
enum moverState_t { MOVER_POS1, MOVER_POS2, MOVER_1TO2, MOVER_2TO1 }
enum clientConnected_t { CON_DISCONNECTED, CON_CONNECTING, CON_CONNECTED }
enum spectatorState_t { SPECTATOR_NOT, SPECTATOR_FREE, SPECTATOR_FOLLOW, SPECTATOR_SCOREBOARD }
enum playerTeamStateState_t { TEAM_BEGIN, TEAM_ACTIVE }
Functions
qboolean G_SpawnString (const char *key, const char *defaultString, char **out)
qboolean G_SpawnFloat (const char *key, const char *defaultString, float *out)
qboolean G_SpawnInt (const char *key, const char *defaultString, int *out)
qboolean G_SpawnVector (const char *key, const char *defaultString, float *out)
void G_SpawnEntitiesFromString (void)
char * G_NewString (const char *string)
void Cmd_Score_f (gentity_t *ent)
void StopFollowing (gentity_t *ent)
void BroadcastTeamChange (gclient_t *client, int oldTeam)
void SetTeam (gentity_t *ent, const char *s)
void Cmd_FollowCycle_f (gentity_t *ent, int dir)
void G_CheckTeamItems (void)
Check team items.
void G_RunItem (gentity_t *ent)
void RespawnItem (gentity_t *ent)
void UseHoldableItem (gentity_t *ent)
void PrecacheItem (gitem_t *it)
gentity_t * Drop_Item (gentity_t *ent, gitem_t *item, float angle)
gentity_t * LaunchItem (gitem_t *item, vec3_t origin, vec3_t velocity)
void SetRespawn (gentity_t *ent, float delay)
void G_SpawnItem (gentity_t *ent, gitem_t *item)
void FinishSpawningItem (gentity_t *ent)
void Think_Weapon (gentity_t *ent)
int ArmorIndex (gentity_t *ent)
void Add_Ammo (gentity_t *ent, int weapon, int count)
void Touch_Item (gentity_t *ent, gentity_t *other, trace_t *trace)
void ClearRegisteredItems (void)
void RegisterItem (gitem_t *item)
void SaveRegisteredItems (void)
int G_ModelIndex (char *name)
int G_SoundIndex (char *name)
void G_TeamCommand (team_t team, char *cmd)
void G_KillBox (gentity_t *ent)
gentity_t * G_Find (gentity_t *from, int fieldofs, const char *match)
gentity_t * G_PickTarget (char *targetname)
void G_UseTargets (gentity_t *ent, gentity_t *activator)
void G_SetMovedir (vec3_t angles, vec3_t movedir)
void G_InitGentity (gentity_t *e)
gentity_t * G_Spawn (void)
gentity_t * G_TempEntity (vec3_t origin, int event)
G_TempEntity spawns an event temporary entity that will be auto-removed.
void G_Sound (gentity_t *ent, int channel, int soundIndex)
void G_FreeEntity (gentity_t *e)
qboolean G_EntitiesFree (void)
void G_TouchTriggers (gentity_t *ent)
float * tv (float x, float y, float z)
char * vtos (const vec3_t v)
float vectoyaw (const vec3_t vec)
void G_AddPredictableEvent (gentity_t *ent, int event, int eventParm)
void G_AddEvent (gentity_t *ent, int event, int eventParm)
void G_SetOrigin (gentity_t *ent, vec3_t origin)
void AddRemap (const char *oldShader, const char *newShader, float timeOffset)
const char * BuildShaderStateConfig (void)
qboolean CanDamage (gentity_t *targ, vec3_t origin)
void G_Damage (gentity_t *targ, gentity_t *inflictor, gentity_t *attacker, vec3_t dir, vec3_t point, int damage, int dflags, int mod)
The damage is dealt out, if all signs indicate that the bullet hit a surface that can be damaged.
qboolean G_RadiusDamage (vec3_t origin, gentity_t *attacker, float damage, float radius, gentity_t *ignore, int mod)
int G_InvulnerabilityEffect (gentity_t *targ, vec3_t dir, vec3_t point, vec3_t impactpoint, vec3_t bouncedir)
void body_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int meansOfDeath)
void TossClientItems (gentity_t *self)
void TossClientCubes (gentity_t *self)
void G_RunMissile (gentity_t *ent)
gentity_t * fire_plasma (gentity_t *self, vec3_t start, vec3_t aimdir)
gentity_t * fire_grenade (gentity_t *self, vec3_t start, vec3_t aimdir)
gentity_t * fire_rocket (gentity_t *self, vec3_t start, vec3_t dir)
This function is responsible for creating an entity and defining it as a rocket (also called a missile).
gentity_t * fire_bfg (gentity_t *self, vec3_t start, vec3_t dir)
gentity_t * fire_grapple (gentity_t *self, vec3_t start, vec3_t dir)
void G_RunMover (gentity_t *ent)
void Touch_DoorTrigger (gentity_t *ent, gentity_t *other, trace_t *trace)
void trigger_teleporter_touch (gentity_t *self, gentity_t *other, trace_t *trace)
void TeleportPlayer (gentity_t *player, vec3_t origin, vec3_t angles)
qboolean LogAccuracyHit (gentity_t *target, gentity_t *attacker)
void CalcMuzzlePoint (gentity_t *ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
void SnapVectorTowards (vec3_t v, vec3_t to)
qboolean CheckGauntletAttack (gentity_t *ent)
void Weapon_HookFree (gentity_t *ent)
void Weapon_HookThink (gentity_t *ent)
int TeamCount (int ignoreClientNum, team_t team)
int TeamLeader (int team)
team_t PickTeam (int ignoreClientNum)
void SetClientViewAngle (gentity_t *ent, vec3_t angle)
gentity_t * SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles, qboolean isbot)
void CopyToBodyQue (gentity_t *ent)
void ClientRespawn (gentity_t *ent)
void BeginIntermission (void)
void InitBodyQue (void)
void ClientSpawn (gentity_t *ent)
void player_die (gentity_t *self, gentity_t *inflictor, gentity_t *attacker, int damage, int mod)
void AddScore (gentity_t *ent, vec3_t origin, int score)
void CalculateRanks (void)
qboolean SpotWouldTelefrag (gentity_t *spot)
qboolean ConsoleCommand (void)
void G_ProcessIPBans (void)
qboolean G_FilterPacket (char *from)
void FireWeapon (gentity_t *ent)
void DeathmatchScoreboardMessage (gentity_t *ent)
void MoveClientToIntermission (gentity_t *ent)
void FindIntermissionPoint (void)
void SetLeader (int team, int client)
void CheckTeamLeader (int team)
void G_RunThink (gentity_t *ent)
void AddTournamentQueue (gclient_t *client)
void QDECL G_LogPrintf (const char *fmt,...) __attribute__((format(printf
void QDECL void SendScoreboardMessageToAllClients (void)
void QDECL G_Printf (const char *fmt,...) __attribute__((format(printf
void QDECL void QDECL G_Error (const char *fmt,...) __attribute__((noreturn
void QDECL void QDECL format (printf, 1, 2)))
char * ClientConnect (int clientNum, qboolean firstTime, qboolean isBot)
void ClientUserinfoChanged (int clientNum)
void ClientDisconnect (int clientNum)
void ClientBegin (int clientNum)
ClientBegin is called when a client has finished connecting, and is ready to be placed into the level.
void ClientCommand (int clientNum)
void ClientThink (int clientNum)
void ClientEndFrame (gentity_t *ent)
void G_RunClient (gentity_t *ent)
qboolean OnSameTeam (gentity_t *ent1, gentity_t *ent2)
void Team_CheckDroppedItem (gentity_t *dropped)
qboolean CheckObeliskAttack (gentity_t *obelisk, gentity_t *attacker)
void * G_Alloc (int size)
void G_InitMemory (void)
void Svcmd_GameMem_f (void)
void G_ReadSessionData (gclient_t *client)
void G_InitSessionData (gclient_t *client, char *userinfo)
void G_InitWorldSession (void)
void G_WriteSessionData (void)
void UpdateTournamentInfo (void)
void SpawnModelsOnVictoryPads (void)
void Svcmd_AbortPodium_f (void)
void G_InitBots (qboolean restart)
char * G_GetBotInfoByNumber (int num)
char * G_GetBotInfoByName (const char *name)
void G_CheckBotSpawn (void)
void G_RemoveQueuedBotBegin (int clientNum)
qboolean G_BotConnect (int clientNum, qboolean restart)
void Svcmd_AddBot_f (void)
void Svcmd_BotList_f (void)
void BotInterbreedEndMatch (void)
int BotAISetup (int restart)
int BotAIShutdown (int restart)
int BotAILoadMap (int restart)
int BotAISetupClient (int client, struct bot_settings_s *settings, qboolean restart)
int BotAIShutdownClient (int client, qboolean restart)
int BotAIStartFrame (int time)
void BotTestAAS (vec3_t origin)
void trap_Print (const char *text)
trap_Print prints the string pointed to by fmt to the Q3 Console.
void trap_Error (const char *text) __attribute__((noreturn))
This is very similar to the trap_Print function with the exception that this will halt execution of the module it is called from.
int trap_Milliseconds (void)
Returns the number of milliseconds that have elapsed since Quake 3 was executed.
int trap_RealTime (qtime_t *qtime)
Returns current system time and date at server.
int trap_Argc (void)
Whenever a client issues a console command it can have arguments passed with it.
void trap_Argv (int n, char *buffer, int bufferLength)
This will fill the buffer pointed to by buffer with an argument to a client command where n is the argument to return.
void trap_Args (char *buffer, int bufferLength)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
This opens a file specified by the string qpath and allocates a fileHandle_t (just a typedef int) to that file.
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
This reads len bytes of data from the file specified by f and fills buffer with it.
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
This writes len bytes of data from buffer to the file specified by f.
void trap_FS_FCloseFile (fileHandle_t f)
Closes the file specified by f.
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
This fills listbuf with a NULL delimited list of all the files in the directory specified by path ending in extension.
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
void trap_SendConsoleCommand (int exec_when, const char *text)
This call adds a command to the command buffer i.e.
void trap_Cvar_Register (vmCvar_t *cvar, const char *var_name, const char *value, int flags)
This function is used to create a new vmCvar.
void trap_Cvar_Update (vmCvar_t *cvar)
This function first parses out the name of the vmCvar and then searches for the corresponding database entry.
void trap_Cvar_Set (const char *var_name, const char *value)
This function searchs for the name of the vmCvar and stores the value into both the float and integer fields of the corresponding vmCvar entry.
int trap_Cvar_VariableIntegerValue (const char *var_name)
This function returns the integer value of var_name that is currently stored in the "master copy".
float trap_Cvar_VariableValue (const char *var_name)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
void trap_LocateGameData (gentity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *gameClients, int sizeofGameClient)
It would be very unusual for a mod programmer to want to call this - especially with parameters other than those outlined above.
void trap_DropClient (int clientNum, const char *reason)
This provides a mechanism to unconditionally drop a client from a server via their clientNum (ent->client->ps.clientNum).
void trap_SendServerCommand (int clientNum, const char *text)
This has the same effect as typing a command in a clients console for evaluation by the server.
void trap_SetConfigstring (int num, const char *string)
The Q3 Engine provides a mechanism for communicating data from the server to the client via config strings.
void trap_GetConfigstring (int num, char *buffer, int bufferSize)
This is a server side callback used to get the value of a config string.
void trap_GetUserinfo (int num, char *buffer, int bufferSize)
Each client has a "user info" string which is a backslash delimited key/value pair for the various options the user can set.
void trap_SetUserinfo (int num, const char *buffer)
This does the opposite to trap_GetUserinfo and sets a userinfo string for a user.
void trap_GetServerinfo (char *buffer, int bufferSize)
The "server info" string is a backslash delimited list of server variables such as g_gametype and mapname.
void trap_SetBrushModel (gentity_t *ent, const char *name)
This function does several special things to an entity which should not be done any other way.
void trap_Trace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
This function is used to trace from one position to another in the BSP tree and store the results in a trace_t structure.
int trap_PointContents (const vec3_t point, int passEntityNum)
This trap call returns the CONTENTS_* of a specific point in space - it is commonly used to avoid spawning items in CONTENTS_NODROP areas.
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
void trap_AdjustAreaPortalState (gentity_t *ent, qboolean open)
Adjusts the state of a portal connecting two areas.
qboolean trap_AreasConnected (int area1, int area2)
This functions tests whether or not the areas (presumably leaf nodes of the bsp tree) are adjacent physically.
void trap_LinkEntity (gentity_t *ent)
When an entity is "linked" it is subject to all evaluations that the world performs on it.
void trap_UnlinkEntity (gentity_t *ent)
When an entity is "unlinked" from the world it remains in memory, but ceases to exist from the point of view of the world.
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int *entityList, int maxcount)
This fills an array of ints with the entity numbers (ent->s.number) of all the entities currently within the cuboid defined by mins and maxs.
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
int trap_BotAllocateClient (void)
Allocates a free client slot and returns the client number.
void trap_BotFreeClient (int clientNum)
void trap_GetUsercmd (int clientNum, usercmd_t *cmd)
This function will retrieve the usercmd_t generated by the client portion of the Q3 binary and place it in what it pointed to by cmd.
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
This call fills the buffer pointed to by buffer with all the key/value pairs of every map entity.
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
Creates a solid coloured permanent polygon in the renderer (and world) based on the given array of vertices/points.
void trap_DebugPolygonDelete (int id)
Removes a polygon that was previously created via trap_DebugPolygonCreate.
int trap_BotLibSetup (void)
int trap_BotLibShutdown (void)
int trap_BotLibVarSet (char *var_name, char *value)
int trap_BotLibVarGet (char *var_name, char *value, int size)
int trap_BotLibDefine (char *string)
int trap_BotLibStartFrame (float time)
int trap_BotLibLoadMap (const char *mapname)
int trap_BotLibUpdateEntity (int ent, void *bue)
int trap_BotLibTest (int parm0, char *parm1, vec3_t parm2, vec3_t parm3)
int trap_BotGetSnapshotEntity (int clientNum, int sequence)
int trap_BotGetServerCommand (int clientNum, char *message, int size)
void trap_BotUserCommand (int client, usercmd_t *ucmd)
int trap_AAS_BBoxAreas (vec3_t absmins, vec3_t absmaxs, int *areas, int maxareas)
int trap_AAS_AreaInfo (int areanum, void *info)
void trap_AAS_EntityInfo (int entnum, void *info)
int trap_AAS_Initialized (void)
void trap_AAS_PresenceTypeBoundingBox (int presencetype, vec3_t mins, vec3_t maxs)
float trap_AAS_Time (void)
int trap_AAS_PointAreaNum (vec3_t point)
int trap_AAS_PointReachabilityAreaIndex (vec3_t point)
int trap_AAS_TraceAreas (vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
int trap_AAS_PointContents (vec3_t point)
int trap_AAS_NextBSPEntity (int ent)
int trap_AAS_ValueForBSPEpairKey (int ent, char *key, char *value, int size)
int trap_AAS_VectorForBSPEpairKey (int ent, char *key, vec3_t v)
int trap_AAS_FloatForBSPEpairKey (int ent, char *key, float *value)
int trap_AAS_IntForBSPEpairKey (int ent, char *key, int *value)
int trap_AAS_AreaReachability (int areanum)
int trap_AAS_AreaTravelTimeToGoalArea (int areanum, vec3_t origin, int goalareanum, int travelflags)
int trap_AAS_EnableRoutingArea (int areanum, int enable)
int trap_AAS_PredictRoute (void *route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
int trap_AAS_AlternativeRouteGoals (vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, void *altroutegoals, int maxaltroutegoals, int type)
int trap_AAS_Swimming (vec3_t origin)
int trap_AAS_PredictClientMovement (void *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
void trap_EA_Say (int client, char *str)
void trap_EA_SayTeam (int client, char *str)
void trap_EA_Command (int client, char *command)
void trap_EA_Action (int client, int action)
void trap_EA_Gesture (int client)
void trap_EA_Talk (int client)
void trap_EA_Attack (int client)
void trap_EA_Use (int client)
void trap_EA_Respawn (int client)
void trap_EA_Crouch (int client)
void trap_EA_MoveUp (int client)
void trap_EA_MoveDown (int client)
void trap_EA_MoveForward (int client)
void trap_EA_MoveBack (int client)
void trap_EA_MoveLeft (int client)
void trap_EA_MoveRight (int client)
void trap_EA_SelectWeapon (int client, int weapon)
void trap_EA_Jump (int client)
void trap_EA_DelayedJump (int client)
void trap_EA_Move (int client, vec3_t dir, float speed)
void trap_EA_View (int client, vec3_t viewangles)
void trap_EA_EndRegular (int client, float thinktime)
void trap_EA_GetInput (int client, float thinktime, void *input)
void trap_EA_ResetInput (int client)
int trap_BotLoadCharacter (char *charfile, float skill)
void trap_BotFreeCharacter (int character)
float trap_Characteristic_Float (int character, int index)
float trap_Characteristic_BFloat (int character, int index, float min, float max)
int trap_Characteristic_Integer (int character, int index)
int trap_Characteristic_BInteger (int character, int index, int min, int max)
void trap_Characteristic_String (int character, int index, char *buf, int size)
int trap_BotAllocChatState (void)
void trap_BotFreeChatState (int handle)
void trap_BotQueueConsoleMessage (int chatstate, int type, char *message)
void trap_BotRemoveConsoleMessage (int chatstate, int handle)
int trap_BotNextConsoleMessage (int chatstate, void *cm)
int trap_BotNumConsoleMessages (int chatstate)
void trap_BotInitialChat (int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int trap_BotNumInitialChats (int chatstate, char *type)
int trap_BotReplyChat (int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int trap_BotChatLength (int chatstate)
void trap_BotEnterChat (int chatstate, int client, int sendto)
void trap_BotGetChatMessage (int chatstate, char *buf, int size)
int trap_StringContains (char *str1, char *str2, int casesensitive)
int trap_BotFindMatch (char *str, void *match, unsigned long int context)
void trap_BotMatchVariable (void *match, int variable, char *buf, int size)
void trap_UnifyWhiteSpaces (char *string)
void trap_BotReplaceSynonyms (char *string, unsigned long int context)
int trap_BotLoadChatFile (int chatstate, char *chatfile, char *chatname)
void trap_BotSetChatGender (int chatstate, int gender)
void trap_BotSetChatName (int chatstate, char *name, int client)
void trap_BotResetGoalState (int goalstate)
void trap_BotRemoveFromAvoidGoals (int goalstate, int number)
void trap_BotResetAvoidGoals (int goalstate)
void trap_BotPushGoal (int goalstate, void *goal)
void trap_BotPopGoal (int goalstate)
void trap_BotEmptyGoalStack (int goalstate)
void trap_BotDumpAvoidGoals (int goalstate)
void trap_BotDumpGoalStack (int goalstate)
void trap_BotGoalName (int number, char *name, int size)
int trap_BotGetTopGoal (int goalstate, void *goal)
int trap_BotGetSecondGoal (int goalstate, void *goal)
int trap_BotChooseLTGItem (int goalstate, vec3_t origin, int *inventory, int travelflags)
int trap_BotChooseNBGItem (int goalstate, vec3_t origin, int *inventory, int travelflags, void *ltg, float maxtime)
int trap_BotTouchingGoal (vec3_t origin, void *goal)
int trap_BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, void *goal)
int trap_BotGetNextCampSpotGoal (int num, void *goal)
int trap_BotGetMapLocationGoal (char *name, void *goal)
int trap_BotGetLevelItemGoal (int index, char *classname, void *goal)
float trap_BotAvoidGoalTime (int goalstate, int number)
void trap_BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
void trap_BotInitLevelItems (void)
void trap_BotUpdateEntityItems (void)
int trap_BotLoadItemWeights (int goalstate, char *filename)
void trap_BotFreeItemWeights (int goalstate)
void trap_BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
void trap_BotSaveGoalFuzzyLogic (int goalstate, char *filename)
void trap_BotMutateGoalFuzzyLogic (int goalstate, float range)
int trap_BotAllocGoalState (int state)
void trap_BotFreeGoalState (int handle)
void trap_BotResetMoveState (int movestate)
void trap_BotMoveToGoal (void *result, int movestate, void *goal, int travelflags)
int trap_BotMoveInDirection (int movestate, vec3_t dir, float speed, int type)
void trap_BotResetAvoidReach (int movestate)
void trap_BotResetLastAvoidReach (int movestate)
int trap_BotReachabilityArea (vec3_t origin, int testground)
int trap_BotMovementViewTarget (int movestate, void *goal, int travelflags, float lookahead, vec3_t target)
int trap_BotPredictVisiblePosition (vec3_t origin, int areanum, void *goal, int travelflags, vec3_t target)
int trap_BotAllocMoveState (void)
void trap_BotFreeMoveState (int handle)
void trap_BotInitMoveState (int handle, void *initmove)
void trap_BotAddAvoidSpot (int movestate, vec3_t origin, float radius, int type)
int trap_BotChooseBestFightWeapon (int weaponstate, int *inventory)
void trap_BotGetWeaponInfo (int weaponstate, int weapon, void *weaponinfo)
int trap_BotLoadWeaponWeights (int weaponstate, char *filename)
int trap_BotAllocWeaponState (void)
void trap_BotFreeWeaponState (int weaponstate)
void trap_BotResetWeaponState (int weaponstate)
int trap_GeneticParentsAndChildSelection (int numranks, float *ranks, int *parent1, int *parent2, int *child)
void trap_SnapVector (float *v)
This simply removes the fractional part of each axis of v - a form of "snap to grid".
Variables
level_locals_t level
gentity_t g_entities [MAX_GENTITIES]
The global entity list in game.
vmCvar_t g_gametype
vmCvar_t g_dedicated
vmCvar_t g_cheats
vmCvar_t g_maxclients
vmCvar_t g_maxGameClients
vmCvar_t g_restarted
vmCvar_t g_dmflags
vmCvar_t g_fraglimit
vmCvar_t g_timelimit
vmCvar_t g_capturelimit
vmCvar_t g_friendlyFire
vmCvar_t g_password
vmCvar_t g_needpass
vmCvar_t g_gravity
vmCvar_t g_speed
vmCvar_t g_knockback
vmCvar_t g_quadfactor
vmCvar_t g_forcerespawn
vmCvar_t g_inactivity
vmCvar_t g_debugMove
vmCvar_t g_debugAlloc
vmCvar_t g_debugDamage
vmCvar_t g_weaponRespawn
vmCvar_t g_weaponTeamRespawn
vmCvar_t g_synchronousClients
vmCvar_t g_motd
vmCvar_t g_warmup
vmCvar_t g_doWarmup
vmCvar_t g_blood
vmCvar_t g_allowVote
vmCvar_t g_teamAutoJoin
vmCvar_t g_teamForceBalance
vmCvar_t g_banIPs
vmCvar_t g_filterBan
vmCvar_t g_obeliskHealth
vmCvar_t g_obeliskRegenPeriod
vmCvar_t g_obeliskRegenAmount
vmCvar_t g_obeliskRespawnDelay
vmCvar_t g_cubeTimeout
vmCvar_t g_redteam
vmCvar_t g_blueteam
vmCvar_t g_smoothClients
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
vmCvar_t g_rankings
vmCvar_t g_enableDust
vmCvar_t g_enableBreath
vmCvar_t g_singlePlayer
vmCvar_t g_proxMineTimeout
vmCvar_t g_localTeamPref
Macro Definition Documentation
BODY_QUEUE_SIZE
#define BODY_QUEUE_SIZE 8
Definition at line 34 of file g_local.h.
CARNAGE_REWARD_TIME
#define CARNAGE_REWARD_TIME 3000
Definition at line 39 of file g_local.h.
DAMAGE_NO_ARMOR
#define DAMAGE_NO_ARMOR 0x00000002
Definition at line 515 of file g_local.h.
DAMAGE_NO_KNOCKBACK
#define DAMAGE_NO_KNOCKBACK 0x00000004
Definition at line 516 of file g_local.h.
DAMAGE_NO_PROTECTION
#define DAMAGE_NO_PROTECTION 0x00000008
Definition at line 517 of file g_local.h.
DAMAGE_RADIUS
#define DAMAGE_RADIUS 0x00000001
Definition at line 514 of file g_local.h.
FL_DROPPED_ITEM
#define FL_DROPPED_ITEM 0x00001000
Definition at line 50 of file g_local.h.
FL_FORCE_GESTURE
#define FL_FORCE_GESTURE 0x00008000
Definition at line 53 of file g_local.h.
FL_GODMODE
#define FL_GODMODE 0x00000010
Definition at line 46 of file g_local.h.
FL_NO_BOTS
#define FL_NO_BOTS 0x00002000
Definition at line 51 of file g_local.h.
FL_NO_HUMANS
#define FL_NO_HUMANS 0x00004000
Definition at line 52 of file g_local.h.
FL_NO_KNOCKBACK
#define FL_NO_KNOCKBACK 0x00000800
Definition at line 49 of file g_local.h.
FL_NOTARGET
#define FL_NOTARGET 0x00000020
Definition at line 47 of file g_local.h.
FL_TEAMSLAVE
#define FL_TEAMSLAVE 0x00000400
Definition at line 48 of file g_local.h.
FOFS
#define FOFS (x) ((size_t)&(((gentity_t *)0)->x))
Definition at line 705 of file g_local.h.
FRAMETIME
#define FRAMETIME 100
Definition at line 38 of file g_local.h.
GAMEVERSION
#define GAMEVERSION BASEGAME
Definition at line 32 of file g_local.h.
INFINITE
#define INFINITE 1000000
Definition at line 36 of file g_local.h.
INTERMISSION_DELAY_TIME
#define INTERMISSION_DELAY_TIME 1000
Definition at line 42 of file g_local.h.
MAX_FILEPATH
#define MAX_FILEPATH 144
Definition at line 683 of file g_local.h.
MAX_NETNAME
#define MAX_NETNAME 36
Definition at line 235 of file g_local.h.
MAX_SPAWN_VARS
#define MAX_SPAWN_VARS 64
Definition at line 337 of file g_local.h.
MAX_SPAWN_VARS_CHARS
#define MAX_SPAWN_VARS_CHARS 4096
Definition at line 338 of file g_local.h.
MAX_VOTE_COUNT
#define MAX_VOTE_COUNT 3
Definition at line 236 of file g_local.h.
REWARD_SPRITE_TIME
#define REWARD_SPRITE_TIME 2000
Definition at line 40 of file g_local.h.
SP_INTERMISSION_DELAY_TIME
#define SP_INTERMISSION_DELAY_TIME 5000
Definition at line 43 of file g_local.h.
SP_PODIUM_MODEL
#define SP_PODIUM_MODEL "models/mapobjects/podium/podium4.md3"
Definition at line 63 of file g_local.h.
Typedef Documentation
bot_settings_t
typedef struct bot_settings_s bot_settings_t
gclient_t
typedef struct gclient_s gclient_t
Definition at line 68 of file g_local.h.
gentity_t
typedef struct gentity_s gentity_t
Definition at line 67 of file g_local.h.
Enumeration Type Documentation
clientConnected_t
enum clientConnected_t
Enumerator
CON_DISCONNECTED
CON_CONNECTING
CON_CONNECTED
Definition at line 180 of file g_local.h.
              {
     CON_DISCONNECTED,
     CON_CONNECTING,
     CON_CONNECTED
 } clientConnected_t;
moverState_t
enum moverState_t
Enumerator
MOVER_POS1
MOVER_POS2
MOVER_1TO2
MOVER_2TO1
Definition at line 56 of file g_local.h.
              {
     MOVER_POS1,
     MOVER_POS2,
     MOVER_1TO2,
     MOVER_2TO1
 } moverState_t;
playerTeamStateState_t
enum playerTeamStateState_t
Enumerator
TEAM_BEGIN
TEAM_ACTIVE
Definition at line 193 of file g_local.h.
              {
     TEAM_BEGIN,        // Beginning a team game, spawn at base
     TEAM_ACTIVE        // Now actively playing
 } playerTeamStateState_t;
spectatorState_t
enum spectatorState_t
Enumerator
SPECTATOR_NOT
SPECTATOR_FREE
SPECTATOR_FOLLOW
SPECTATOR_SCOREBOARD
Definition at line 186 of file g_local.h.
              {
     SPECTATOR_NOT,
     SPECTATOR_FREE,
     SPECTATOR_FOLLOW,
     SPECTATOR_SCOREBOARD
 } spectatorState_t;
Function Documentation
Add_Ammo()
void Add_Ammo (gentity_t * ent, int weapon, int count)
Definition at line 212 of file g_items.c.
 {
     ent->client->ps.ammo[weapon] += count;
     if (ent->client->ps.ammo[weapon] > 200) {
         ent->client->ps.ammo[weapon] = 200;
     }
 }
References playerState_s::ammo, gentity_s::client, count, and gclient_s::ps.
Referenced by Pickup_Ammo(), and Pickup_Weapon().
AddRemap()
void AddRemap (const char * oldShader, const char * newShader, float timeOffset)
Definition at line 38 of file g_utils.c.
 {
     int i;
     for (i = 0; i < remapCount; i++) {
         if (Q_stricmp(oldShader, remappedShaders[i].oldShader) == 0) {
             // found it, just update this one
             strcpy(remappedShaders[i].newShader, newShader);
             remappedShaders[i].timeOffset = timeOffset;
             return;
         }
     }
     if (remapCount < MAX_SHADER_REMAPS) {
         strcpy(remappedShaders[remapCount].newShader, newShader);
         strcpy(remappedShaders[remapCount].oldShader, oldShader);
         remappedShaders[remapCount].timeOffset = timeOffset;
         remapCount++;
     }
 }
References MAX_SHADER_REMAPS, Q_stricmp(), remapCount, remappedShaders, and shaderRemap_t::timeOffset.
Referenced by G_RemapTeamShaders(), and G_UseTargets().
AddScore()
void AddScore (gentity_t * ent, vec3_t origin, int score)
Definition at line 53 of file g_combat.c.
 {
     if (!ent->client) {
         return;
     }
     // no scoring during pre-match warmup
     if (level.warmupTime) {
         return;
     }
     // show score plum
     ScorePlum(ent, origin, score);
     //
     ent->client->ps.persistant[PERS_SCORE] += score;
     if (g_gametype.integer == GT_TEAM)
         level.teamScores[ent->client->ps.persistant[PERS_TEAM]] += score;
     CalculateRanks();
 }
References CalculateRanks(), gentity_s::client, g_gametype, GT_TEAM, level, PERS_SCORE, PERS_TEAM, playerState_s::persistant, gclient_s::ps, ScorePlum(), level_locals_t::teamScores, and level_locals_t::warmupTime.
Referenced by player_die(), Team_FragBonuses(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), and Use_Target_Score().
AddTournamentQueue()
void AddTournamentQueue (gclient_t * client)
Definition at line 643 of file g_main.c.
 {
     int index;
     gclient_t* curclient;
     for (index = 0; index < level.maxclients; index++) {
         curclient = &level.clients[index];
         if (curclient->pers.connected != CON_DISCONNECTED) {
             if (curclient == client)
                 curclient->sess.spectatorNum = 0;
             else if (curclient->sess.sessionTeam == TEAM_SPECTATOR)
                 curclient->sess.spectatorNum++;
         }
     }
 }
References level_locals_t::clients, CON_DISCONNECTED, clientPersistant_t::connected, level, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::spectatorNum, and TEAM_SPECTATOR.
Referenced by G_InitSessionData(), and SetTeam().
ArmorIndex()
int ArmorIndex (gentity_t * ent)
BeginIntermission()
void BeginIntermission (void)
Definition at line 1007 of file g_main.c.
 {
     int            i;
     gentity_t* client;
     if (level.intermissiontime) {
         return;        // already active
     }
     // if in tournement mode, change the wins / losses
     if (g_gametype.integer == GT_TOURNAMENT) {
         AdjustTournamentScores();
     }
     level.intermissiontime = level.time;
     // move all clients to the intermission point
     for (i = 0; i < level.maxclients; i++) {
         client = g_entities + i;
         if (!client->inuse)
             continue;
         // respawn if dead
         if (client->health <= 0) {
             ClientRespawn(client);
         }
         MoveClientToIntermission(client);
     }
 #ifdef MISSIONPACK
     if (g_singlePlayer.integer) {
         trap_Cvar_Set("ui_singlePlayerActive", "0");
         UpdateTournamentInfo();
     }
 #else
     // if single player game
     if (g_gametype.integer == GT_SINGLE_PLAYER) {
         UpdateTournamentInfo();
         SpawnModelsOnVictoryPads();
     }
 #endif
     // send the current scoring to all clients
     SendScoreboardMessageToAllClients();
 }
References AdjustTournamentScores(), ClientRespawn(), g_entities, g_gametype, g_singlePlayer, GT_SINGLE_PLAYER, GT_TOURNAMENT, gentity_s::health, vmCvar_t::integer, level_locals_t::intermissiontime, gentity_s::inuse, level, level_locals_t::maxclients, MoveClientToIntermission(), SendScoreboardMessageToAllClients(), SpawnModelsOnVictoryPads(), level_locals_t::time, trap_Cvar_Set(), and UpdateTournamentInfo().
Referenced by CheckExitRules(), and Cmd_LevelShot_f().
body_die()
void body_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, int meansOfDeath)
Definition at line 273 of file g_combat.c.
 {
     if (self->health > GIB_HEALTH) {
         return;
     }
     if (!g_blood.integer) {
         self->health = GIB_HEALTH + 1;
         return;
     }
     GibEntity(self, 0);
 }
References g_blood, GIB_HEALTH, GibEntity(), and vmCvar_t::integer.
Referenced by CopyToBodyQue(), and player_die().
BotAILoadMap()
int BotAILoadMap (int restart)
Definition at line 1392 of file ai_main.c.
 {
     int            i;
     vmCvar_t    mapname;
     if (!restart) {
         trap_Cvar_Register(&mapname, "mapname", "", CVAR_SERVERINFO | CVAR_ROM);
         trap_BotLibLoadMap(mapname.string);
     }
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (botstates[i] && botstates[i]->inuse) {
             BotResetState(botstates[i]);
             botstates[i]->setupcount = 4;
         }
     }
     BotSetupDeathmatchAI();
     return qtrue;
 }
References BotResetState(), BotSetupDeathmatchAI(), botstates, CVAR_ROM, CVAR_SERVERINFO, MAX_CLIENTS, qtrue, bot_state_s::setupcount, vmCvar_t::string, trap_BotLibLoadMap(), and trap_Cvar_Register().
Referenced by G_InitGame().
BotAISetup()
int BotAISetup (int restart)
Definition at line 1690 of file ai_main.c.
 {
     int            errnum;
     trap_Cvar_Register(&bot_thinktime, "bot_thinktime", "100", CVAR_CHEAT);
     trap_Cvar_Register(&bot_memorydump, "bot_memorydump", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_saveroutingcache, "bot_saveroutingcache", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_pause, "bot_pause", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_report, "bot_report", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_testsolid, "bot_testsolid", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_testclusters, "bot_testclusters", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_developer, "bot_developer", "0", CVAR_CHEAT);
     trap_Cvar_Register(&bot_interbreedchar, "bot_interbreedchar", "", 0);
     trap_Cvar_Register(&bot_interbreedbots, "bot_interbreedbots", "10", 0);
     trap_Cvar_Register(&bot_interbreedcycle, "bot_interbreedcycle", "20", 0);
     trap_Cvar_Register(&bot_interbreedwrite, "bot_interbreedwrite", "", 0);
     //if the game is restarted for a tournament
     if (restart) {
         return qtrue;
     }
     //initialize the bot states
     memset(botstates, 0, sizeof(botstates));
     errnum = BotInitLibrary();
     if (errnum != BLERR_NOERROR) return qfalse;
     return qtrue;
 }
References BLERR_NOERROR, bot_developer, bot_interbreedbots, bot_interbreedchar, bot_interbreedcycle, bot_interbreedwrite, bot_memorydump, bot_pause, bot_report, bot_saveroutingcache, bot_testclusters, bot_testsolid, bot_thinktime, BotInitLibrary(), botstates, CVAR_CHEAT, qfalse, qtrue, and trap_Cvar_Register().
Referenced by G_InitGame().
BotAISetupClient()
int BotAISetupClient (int client, struct bot_settings_s * settings, qboolean restart)
Definition at line 1190 of file ai_main.c.
 {
     char filename[144], name[144], gender[144];
     bot_state_t* bs;
     int errnum;
     if (!botstates[client]) botstates[client] = G_Alloc(sizeof(bot_state_t));
     bs = botstates[client];
     if (!bs) {
         return qfalse;
     }
     if (bs && bs->inuse) {
         BotAI_Print(PRT_FATAL, "BotAISetupClient: client %d already setup\n", client);
         return qfalse;
     }
     if (!trap_AAS_Initialized()) {
         BotAI_Print(PRT_FATAL, "AAS not initialized\n");
         return qfalse;
     }
     //load the bot character
     bs->character = trap_BotLoadCharacter(settings->characterfile, settings->skill);
     if (!bs->character) {
         BotAI_Print(PRT_FATAL, "couldn't load skill %f from %s\n", settings->skill, settings->characterfile);
         return qfalse;
     }
     //copy the settings
     memcpy(&bs->settings, settings, sizeof(bot_settings_t));
     //allocate a goal state
     bs->gs = trap_BotAllocGoalState(client);
     //load the item weights
     trap_Characteristic_String(bs->character, CHARACTERISTIC_ITEMWEIGHTS, filename, sizeof(filename));
     errnum = trap_BotLoadItemWeights(bs->gs, filename);
     if (errnum != BLERR_NOERROR) {
         trap_BotFreeGoalState(bs->gs);
         return qfalse;
     }
     //allocate a weapon state
     bs->ws = trap_BotAllocWeaponState();
     //load the weapon weights
     trap_Characteristic_String(bs->character, CHARACTERISTIC_WEAPONWEIGHTS, filename, sizeof(filename));
     errnum = trap_BotLoadWeaponWeights(bs->ws, filename);
     if (errnum != BLERR_NOERROR) {
         trap_BotFreeGoalState(bs->gs);
         trap_BotFreeWeaponState(bs->ws);
         return qfalse;
     }
     //allocate a chat state
     bs->cs = trap_BotAllocChatState();
     //load the chat file
     trap_Characteristic_String(bs->character, CHARACTERISTIC_CHAT_FILE, filename, sizeof(filename));
     trap_Characteristic_String(bs->character, CHARACTERISTIC_CHAT_NAME, name, sizeof(name));
     errnum = trap_BotLoadChatFile(bs->cs, filename, name);
     if (errnum != BLERR_NOERROR) {
         trap_BotFreeChatState(bs->cs);
         trap_BotFreeGoalState(bs->gs);
         trap_BotFreeWeaponState(bs->ws);
         return qfalse;
     }
     //get the gender characteristic
     trap_Characteristic_String(bs->character, CHARACTERISTIC_GENDER, gender, sizeof(gender));
     //set the chat gender
     if (*gender == 'f' || *gender == 'F') trap_BotSetChatGender(bs->cs, CHAT_GENDERFEMALE);
     else if (*gender == 'm' || *gender == 'M') trap_BotSetChatGender(bs->cs, CHAT_GENDERMALE);
     else trap_BotSetChatGender(bs->cs, CHAT_GENDERLESS);
     bs->inuse = qtrue;
     bs->client = client;
     bs->entitynum = client;
     bs->setupcount = 4;
     bs->entergame_time = FloatTime();
     bs->ms = trap_BotAllocMoveState();
     bs->walker = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_WALKER, 0, 1);
     numbots++;
     if (trap_Cvar_VariableIntegerValue("bot_testichat")) {
         trap_BotLibVarSet("bot_testichat", "1");
         BotChatTest(bs);
     }
     //NOTE: reschedule the bot thinking
     BotScheduleBotThink();
     //if interbreeding start with a mutation
     if (bot_interbreed) {
         trap_BotMutateGoalFuzzyLogic(bs->gs, 1);
     }
     // if we kept the bot client
     if (restart) {
         BotReadSessionData(bs);
     }
     //bot has been setup successfully
     return qtrue;
 }
References BLERR_NOERROR, bot_interbreed, BotAI_Print(), BotChatTest(), BotReadSessionData(), BotScheduleBotThink(), botstates, bot_state_s::character, bot_settings_s::characterfile, CHARACTERISTIC_CHAT_FILE, CHARACTERISTIC_CHAT_NAME, CHARACTERISTIC_GENDER, CHARACTERISTIC_ITEMWEIGHTS, CHARACTERISTIC_WALKER, CHARACTERISTIC_WEAPONWEIGHTS, CHAT_GENDERFEMALE, CHAT_GENDERLESS, CHAT_GENDERMALE, bot_state_s::client, bot_state_s::cs, bot_state_s::entergame_time, bot_state_s::entitynum, FloatTime, G_Alloc(), bot_state_s::gs, bot_state_s::inuse, bot_state_s::ms, numbots, PRT_FATAL, qfalse, qtrue, bot_state_s::settings, bot_state_s::setupcount, bot_settings_s::skill, trap_AAS_Initialized(), trap_BotAllocChatState(), trap_BotAllocGoalState(), trap_BotAllocMoveState(), trap_BotAllocWeaponState(), trap_BotFreeChatState(), trap_BotFreeGoalState(), trap_BotFreeWeaponState(), trap_BotLibVarSet(), trap_BotLoadCharacter(), trap_BotLoadChatFile(), trap_BotLoadItemWeights(), trap_BotLoadWeaponWeights(), trap_BotMutateGoalFuzzyLogic(), trap_BotSetChatGender(), trap_Characteristic_BFloat(), trap_Characteristic_String(), trap_Cvar_VariableIntegerValue(), bot_state_s::walker, and bot_state_s::ws.
Referenced by G_BotConnect().
BotAIShutdown()
int BotAIShutdown (int restart)
Definition at line 1725 of file ai_main.c.
 {
     int i;
     //if the game is restarted for a tournament
     if (restart) {
         //shutdown all the bots in the botlib
         for (i = 0; i < MAX_CLIENTS; i++) {
             if (botstates[i] && botstates[i]->inuse) {
                 BotAIShutdownClient(botstates[i]->client, restart);
             }
         }
         //don't shutdown the bot library
     } else {
         trap_BotLibShutdown();
     }
     return qtrue;
 }
References BotAIShutdownClient(), botstates, MAX_CLIENTS, qtrue, and trap_BotLibShutdown().
Referenced by G_ShutdownGame().
BotAIShutdownClient()
int BotAIShutdownClient (int client, qboolean restart)
Definition at line 1291 of file ai_main.c.
 {
     bot_state_t* bs;
     bs = botstates[client];
     if (!bs || !bs->inuse) {
         //BotAI_Print(PRT_ERROR, "BotAIShutdownClient: client %d already shutdown\n", client);
         return qfalse;
     }
     if (restart) {
         BotWriteSessionData(bs);
     }
     if (BotChat_ExitGame(bs)) {
         trap_BotEnterChat(bs->cs, bs->client, CHAT_ALL);
     }
     trap_BotFreeMoveState(bs->ms);
     //free the goal state
     trap_BotFreeGoalState(bs->gs);
     //free the chat file
     trap_BotFreeChatState(bs->cs);
     //free the weapon weights
     trap_BotFreeWeaponState(bs->ws);
     //free the bot character
     trap_BotFreeCharacter(bs->character);
     //
     BotFreeWaypoints(bs->checkpoints);
     BotFreeWaypoints(bs->patrolpoints);
     //clear activate goal stack
     BotClearActivateGoalStack(bs);
     //clear the bot state
     memset(bs, 0, sizeof(bot_state_t));
     //set the inuse flag to qfalse
     bs->inuse = qfalse;
     //there's one bot less
     numbots--;
     //everything went ok
     return qtrue;
 }
References BotChat_ExitGame(), BotClearActivateGoalStack(), BotFreeWaypoints(), botstates, BotWriteSessionData(), bot_state_s::character, CHAT_ALL, bot_state_s::checkpoints, bot_state_s::client, bot_state_s::cs, bot_state_s::gs, bot_state_s::inuse, bot_state_s::ms, numbots, bot_state_s::patrolpoints, qfalse, qtrue, trap_BotEnterChat(), trap_BotFreeCharacter(), trap_BotFreeChatState(), trap_BotFreeGoalState(), trap_BotFreeMoveState(), trap_BotFreeWeaponState(), and bot_state_s::ws.
Referenced by BotAIShutdown(), BotInterbreeding(), and ClientDisconnect().
BotAIStartFrame()
int BotAIStartFrame (int time)
Definition at line 1423 of file ai_main.c.
 {
     int i;
     gentity_t* ent;
     bot_entitystate_t state;
     int elapsed_time, thinktime;
     static int local_time;
     static int botlib_residual;
     static int lastbotthink_time;
     G_CheckBotSpawn();
     trap_Cvar_Update(&bot_rocketjump);
     trap_Cvar_Update(&bot_grapple);
     trap_Cvar_Update(&bot_fastchat);
     trap_Cvar_Update(&bot_nochat);
     trap_Cvar_Update(&bot_testrchat);
     trap_Cvar_Update(&bot_thinktime);
     trap_Cvar_Update(&bot_memorydump);
     trap_Cvar_Update(&bot_saveroutingcache);
     trap_Cvar_Update(&bot_pause);
     trap_Cvar_Update(&bot_report);
     if (bot_report.integer) {
         //        BotTeamplayReport();
         //        trap_Cvar_Set("bot_report", "0");
         BotUpdateInfoConfigStrings();
     }
     if (bot_pause.integer) {
         // execute bot user commands every frame
         for (i = 0; i < MAX_CLIENTS; i++) {
             if (!botstates[i] || !botstates[i]->inuse) {
                 continue;
             }
             if (g_entities[i].client->pers.connected != CON_CONNECTED) {
                 continue;
             }
             botstates[i]->lastucmd.forwardmove = 0;
             botstates[i]->lastucmd.rightmove = 0;
             botstates[i]->lastucmd.upmove = 0;
             botstates[i]->lastucmd.buttons = 0;
             botstates[i]->lastucmd.serverTime = time;
             trap_BotUserCommand(botstates[i]->client, &botstates[i]->lastucmd);
         }
         return qtrue;
     }
     if (bot_memorydump.integer) {
         trap_BotLibVarSet("memorydump", "1");
         trap_Cvar_Set("bot_memorydump", "0");
     }
     if (bot_saveroutingcache.integer) {
         trap_BotLibVarSet("saveroutingcache", "1");
         trap_Cvar_Set("bot_saveroutingcache", "0");
     }
     //check if bot interbreeding is activated
     BotInterbreeding();
     //cap the bot think time
     if (bot_thinktime.integer > 200) {
         trap_Cvar_Set("bot_thinktime", "200");
     }
     //if the bot think time changed we should reschedule the bots
     if (bot_thinktime.integer != lastbotthink_time) {
         lastbotthink_time = bot_thinktime.integer;
         BotScheduleBotThink();
     }
     elapsed_time = time - local_time;
     local_time = time;
     botlib_residual += elapsed_time;
     if (elapsed_time > bot_thinktime.integer) thinktime = elapsed_time;
     else thinktime = bot_thinktime.integer;
     // update the bot library
     if (botlib_residual >= thinktime) {
         botlib_residual -= thinktime;
         trap_BotLibStartFrame((float)time / 1000);
         if (!trap_AAS_Initialized()) return qfalse;
         //update entities in the botlib
         for (i = 0; i < MAX_GENTITIES; i++) {
             ent = &g_entities[i];
             if (!ent->inuse) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             if (!ent->r.linked) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             if (ent->r.svFlags & SVF_NOCLIENT) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             // do not update missiles
             if (ent->s.eType == ET_MISSILE && ent->s.weapon != WP_GRAPPLING_HOOK) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
             // do not update event only entities
             if (ent->s.eType > ET_EVENTS) {
                 trap_BotLibUpdateEntity(i, NULL);
                 continue;
             }
 #ifdef MISSIONPACK
             // never link prox mine triggers
             if (ent->r.contents == CONTENTS_TRIGGER) {
                 if (ent->touch == ProximityMine_Trigger) {
                     trap_BotLibUpdateEntity(i, NULL);
                     continue;
                 }
             }
 #endif
             //
             memset(&state, 0, sizeof(bot_entitystate_t));
             //
             VectorCopy(ent->r.currentOrigin, state.origin);
             if (i < MAX_CLIENTS) {
                 VectorCopy(ent->s.apos.trBase, state.angles);
             } else {
                 VectorCopy(ent->r.currentAngles, state.angles);
             }
             VectorCopy(ent->s.origin2, state.old_origin);
             VectorCopy(ent->r.mins, state.mins);
             VectorCopy(ent->r.maxs, state.maxs);
             state.type = ent->s.eType;
             state.flags = ent->s.eFlags;
             if (ent->r.bmodel) state.solid = SOLID_BSP;
             else state.solid = SOLID_BBOX;
             state.groundent = ent->s.groundEntityNum;
             state.modelindex = ent->s.modelindex;
             state.modelindex2 = ent->s.modelindex2;
             state.frame = ent->s.frame;
             state.event = ent->s.event;
             state.eventParm = ent->s.eventParm;
             state.powerups = ent->s.powerups;
             state.legsAnim = ent->s.legsAnim;
             state.torsoAnim = ent->s.torsoAnim;
             state.weapon = ent->s.weapon;
             //
             trap_BotLibUpdateEntity(i, &state);
         }
         BotAIRegularUpdate();
     }
     floattime = trap_AAS_Time();
     // execute scheduled bot AI
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (!botstates[i] || !botstates[i]->inuse) {
             continue;
         }
         //
         botstates[i]->botthink_residual += elapsed_time;
         //
         if (botstates[i]->botthink_residual >= thinktime) {
             botstates[i]->botthink_residual -= thinktime;
             if (!trap_AAS_Initialized()) return qfalse;
             if (g_entities[i].client->pers.connected == CON_CONNECTED) {
                 BotAI(i, (float)thinktime / 1000);
             }
         }
     }
     // execute bot user commands every frame
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (!botstates[i] || !botstates[i]->inuse) {
             continue;
         }
         if (g_entities[i].client->pers.connected != CON_CONNECTED) {
             continue;
         }
         BotUpdateInput(botstates[i], time, elapsed_time);
         trap_BotUserCommand(botstates[i]->client, &botstates[i]->lastucmd);
     }
     return qtrue;
 }
References entityState_s::apos, entityShared_t::bmodel, bot_fastchat, bot_grapple, bot_memorydump, bot_nochat, bot_pause, bot_report, bot_rocketjump, bot_saveroutingcache, bot_testrchat, bot_thinktime, BotAI(), BotAIRegularUpdate(), BotInterbreeding(), BotScheduleBotThink(), botstates, bot_state_s::botthink_residual, BotUpdateInfoConfigStrings(), BotUpdateInput(), usercmd_s::buttons, CON_CONNECTED, entityShared_t::contents, CONTENTS_TRIGGER, entityShared_t::currentAngles, entityShared_t::currentOrigin, entityState_s::eFlags, ET_EVENTS, ET_MISSILE, entityState_s::eType, entityState_s::event, entityState_s::eventParm, floattime, usercmd_s::forwardmove, entityState_s::frame, G_CheckBotSpawn(), g_entities, entityState_s::groundEntityNum, vmCvar_t::integer, gentity_s::inuse, bot_state_s::lastucmd, entityState_s::legsAnim, entityShared_t::linked, MAX_CLIENTS, MAX_GENTITIES, entityShared_t::maxs, entityShared_t::mins, entityState_s::modelindex, entityState_s::modelindex2, NULL, entityState_s::origin2, entityState_s::powerups, qfalse, qtrue, gentity_s::r, usercmd_s::rightmove, gentity_s::s, usercmd_s::serverTime, SOLID_BBOX, SOLID_BSP, SVF_NOCLIENT, entityShared_t::svFlags, entityState_s::torsoAnim, gentity_s::touch, trap_AAS_Initialized(), trap_AAS_Time(), trap_BotLibStartFrame(), trap_BotLibUpdateEntity(), trap_BotLibVarSet(), trap_BotUserCommand(), trap_Cvar_Set(), trap_Cvar_Update(), trajectory_t::trBase, usercmd_s::upmove, VectorCopy, entityState_s::weapon, and WP_GRAPPLING_HOOK.
Referenced by vmMain().
BotInterbreedEndMatch()
void BotInterbreedEndMatch (void)
Definition at line 642 of file ai_main.c.
 {
     if (!bot_interbreed) return;
     bot_interbreedmatchcount++;
     if (bot_interbreedmatchcount >= bot_interbreedcycle.integer) {
         bot_interbreedmatchcount = 0;
         //
         trap_Cvar_Update(&bot_interbreedwrite);
         if (strlen(bot_interbreedwrite.string)) {
             BotWriteInterbreeded(bot_interbreedwrite.string);
             trap_Cvar_Set("bot_interbreedwrite", "");
         }
         BotInterbreedBots();
     }
 }
References bot_interbreed, bot_interbreedcycle, bot_interbreedmatchcount, bot_interbreedwrite, BotInterbreedBots(), BotWriteInterbreeded(), vmCvar_t::integer, vmCvar_t::string, trap_Cvar_Set(), and trap_Cvar_Update().
Referenced by ExitLevel().
BotTestAAS()
void BotTestAAS (vec3_t origin)
Definition at line 258 of file ai_main.c.
 {
     int areanum;
     aas_areainfo_t info;
     trap_Cvar_Update(&bot_testsolid);
     trap_Cvar_Update(&bot_testclusters);
     if (bot_testsolid.integer) {
         if (!trap_AAS_Initialized()) return;
         areanum = BotPointAreaNum(origin);
         if (areanum) BotAI_Print(PRT_MESSAGE, "\rempty area");
         else BotAI_Print(PRT_MESSAGE, "\r^1SOLID area");
     } else if (bot_testclusters.integer) {
         if (!trap_AAS_Initialized()) return;
         areanum = BotPointAreaNum(origin);
         if (!areanum)
             BotAI_Print(PRT_MESSAGE, "\r^1Solid!                              ");
         else {
             trap_AAS_AreaInfo(areanum, &info);
             BotAI_Print(PRT_MESSAGE, "\rarea %d, cluster %d       ", areanum, info.cluster);
         }
     }
 }
References bot_testclusters, bot_testsolid, BotAI_Print(), BotPointAreaNum(), aas_areainfo_s::cluster, vmCvar_t::integer, PRT_MESSAGE, trap_AAS_AreaInfo(), trap_AAS_Initialized(), and trap_Cvar_Update().
Referenced by ClientThink_real().
BroadcastTeamChange()
void BroadcastTeamChange (gclient_t * client, int oldTeam)
Definition at line 496 of file g_cmds.c.
 {
     if (client->sess.sessionTeam == TEAM_RED) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the red team.\n\"",
             client->pers.netname));
     } else if (client->sess.sessionTeam == TEAM_BLUE) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the blue team.\n\"",
             client->pers.netname));
     } else if (client->sess.sessionTeam == TEAM_SPECTATOR && oldTeam != TEAM_SPECTATOR) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the spectators.\n\"",
             client->pers.netname));
     } else if (client->sess.sessionTeam == TEAM_FREE) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the battle.\n\"",
             client->pers.netname));
     }
 }
References clientPersistant_t::netname, gclient_s::pers, S_COLOR_WHITE, gclient_s::sess, clientSession_t::sessionTeam, TEAM_BLUE, TEAM_FREE, TEAM_RED, TEAM_SPECTATOR, trap_SendServerCommand(), and va().
Referenced by ClientConnect(), and SetTeam().
BuildShaderStateConfig()
const char* BuildShaderStateConfig (void)
Definition at line 58 of file g_utils.c.
 {
     static char    buff[MAX_STRING_CHARS * 4];
     char out[(MAX_QPATH * 2) + 5];
     int i;
     memset(buff, 0, MAX_STRING_CHARS);
     for (i = 0; i < remapCount; i++) {
         Com_sprintf(out, (MAX_QPATH * 2) + 5, "%s=%s:%5.2f@", remappedShaders[i].oldShader, remappedShaders[i].newShader, remappedShaders[i].timeOffset);
         Q_strcat(buff, sizeof(buff), out);
     }
     return buff;
 }
References Com_sprintf(), MAX_QPATH, MAX_STRING_CHARS, Q_strcat(), remapCount, and remappedShaders.
Referenced by G_RemapTeamShaders(), and G_UseTargets().
CalcMuzzlePoint()
void CalcMuzzlePoint (gentity_t * ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
Definition at line 799 of file g_weapon.c.
 {
     VectorCopy(ent->s.pos.trBase, muzzlePoint);
     muzzlePoint[2] += ent->client->ps.viewheight;
     VectorMA(muzzlePoint, 14, forward, muzzlePoint);
     // snap to integer coordinates for more efficient network bandwidth usage
     SnapVector(muzzlePoint);
 }
References gentity_s::client, forward, entityState_s::pos, gclient_s::ps, gentity_s::s, SnapVector, trajectory_t::trBase, VectorCopy, VectorMA, and playerState_s::viewheight.
Referenced by CheckGauntletAttack().
CalculateRanks()
void CalculateRanks (void)
Definition at line 799 of file g_main.c.
 {
     int        i;
     int        rank;
     int        score;
     int        newScore;
     gclient_t* cl;
     level.follow1 = -1;
     level.follow2 = -1;
     level.numConnectedClients = 0;
     level.numNonSpectatorClients = 0;
     level.numPlayingClients = 0;
     level.numVotingClients = 0;        // don't count bots
     for (i = 0; i < ARRAY_LEN(level.numteamVotingClients); i++)
         level.numteamVotingClients[i] = 0;
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected != CON_DISCONNECTED) {
             level.sortedClients[level.numConnectedClients] = i;
             level.numConnectedClients++;
             if (level.clients[i].sess.sessionTeam != TEAM_SPECTATOR) {
                 level.numNonSpectatorClients++;
                 // decide if this should be auto-followed
                 if (level.clients[i].pers.connected == CON_CONNECTED) {
                     level.numPlayingClients++;
                     if (!(g_entities[i].r.svFlags & SVF_BOT)) {
                         level.numVotingClients++;
                         if (level.clients[i].sess.sessionTeam == TEAM_RED)
                             level.numteamVotingClients[0]++;
                         else if (level.clients[i].sess.sessionTeam == TEAM_BLUE)
                             level.numteamVotingClients[1]++;
                     }
                     if (level.follow1 == -1) {
                         level.follow1 = i;
                     } else if (level.follow2 == -1) {
                         level.follow2 = i;
                     }
                 }
             }
         }
     }
     qsort(level.sortedClients, level.numConnectedClients,
         sizeof(level.sortedClients[0]), SortRanks);
     // set the rank value for all clients that are connected and not spectators
     if (g_gametype.integer >= GT_TEAM) {
         // in team games, rank is just the order of the teams, 0=red, 1=blue, 2=tied
         for (i = 0; i < level.numConnectedClients; i++) {
             cl = &level.clients[level.sortedClients[i]];
             if (level.teamScores[TEAM_RED] == level.teamScores[TEAM_BLUE]) {
                 cl->ps.persistant[PERS_RANK] = 2;
             } else if (level.teamScores[TEAM_RED] > level.teamScores[TEAM_BLUE]) {
                 cl->ps.persistant[PERS_RANK] = 0;
             } else {
                 cl->ps.persistant[PERS_RANK] = 1;
             }
         }
     } else {
         rank = -1;
         score = 0;
         for (i = 0; i < level.numPlayingClients; i++) {
             cl = &level.clients[level.sortedClients[i]];
             newScore = cl->ps.persistant[PERS_SCORE];
             if (i == 0 || newScore != score) {
                 rank = i;
                 // assume we aren't tied until the next client is checked
                 level.clients[level.sortedClients[i]].ps.persistant[PERS_RANK] = rank;
             } else {
                 // we are tied with the previous client
                 level.clients[level.sortedClients[i - 1]].ps.persistant[PERS_RANK] = rank | RANK_TIED_FLAG;
                 level.clients[level.sortedClients[i]].ps.persistant[PERS_RANK] = rank | RANK_TIED_FLAG;
             }
             score = newScore;
             if (g_gametype.integer == GT_SINGLE_PLAYER && level.numPlayingClients == 1) {
                 level.clients[level.sortedClients[i]].ps.persistant[PERS_RANK] = rank | RANK_TIED_FLAG;
             }
         }
     }
     // set the CS_SCORES1/2 configstrings, which will be visible to everyone
     if (g_gametype.integer >= GT_TEAM) {
         trap_SetConfigstring(CS_SCORES1, va("%i", level.teamScores[TEAM_RED]));
         trap_SetConfigstring(CS_SCORES2, va("%i", level.teamScores[TEAM_BLUE]));
     } else {
         if (level.numConnectedClients == 0) {
             trap_SetConfigstring(CS_SCORES1, va("%i", SCORE_NOT_PRESENT));
             trap_SetConfigstring(CS_SCORES2, va("%i", SCORE_NOT_PRESENT));
         } else if (level.numConnectedClients == 1) {
             trap_SetConfigstring(CS_SCORES1, va("%i", level.clients[level.sortedClients[0]].ps.persistant[PERS_SCORE]));
             trap_SetConfigstring(CS_SCORES2, va("%i", SCORE_NOT_PRESENT));
         } else {
             trap_SetConfigstring(CS_SCORES1, va("%i", level.clients[level.sortedClients[0]].ps.persistant[PERS_SCORE]));
             trap_SetConfigstring(CS_SCORES2, va("%i", level.clients[level.sortedClients[1]].ps.persistant[PERS_SCORE]));
         }
     }
     // see if it is time to end the level
     CheckExitRules();
     // if we are at the intermission, send the new info to everyone
     if (level.intermissiontime) {
         SendScoreboardMessageToAllClients();
     }
 }
References ARRAY_LEN, CheckExitRules(), cl, level_locals_t::clients, CON_CONNECTED, CON_DISCONNECTED, clientPersistant_t::connected, CS_SCORES1, CS_SCORES2, level_locals_t::follow1, level_locals_t::follow2, g_entities, g_gametype, GT_SINGLE_PLAYER, GT_TEAM, vmCvar_t::integer, level_locals_t::intermissiontime, level, level_locals_t::maxclients, level_locals_t::numConnectedClients, level_locals_t::numNonSpectatorClients, level_locals_t::numPlayingClients, level_locals_t::numteamVotingClients, level_locals_t::numVotingClients, gclient_s::pers, PERS_RANK, PERS_SCORE, playerState_s::persistant, gclient_s::ps, RANK_TIED_FLAG, SCORE_NOT_PRESENT, SendScoreboardMessageToAllClients(), gclient_s::sess, clientSession_t::sessionTeam, level_locals_t::sortedClients, SortRanks(), SVF_BOT, TEAM_BLUE, TEAM_RED, TEAM_SPECTATOR, level_locals_t::teamScores, trap_SetConfigstring(), and va().
Referenced by AddScore(), ClientBegin(), ClientConnect(), ClientDisconnect(), Team_TouchOurFlag(), and UpdateTournamentInfo().
CanDamage()
qboolean CanDamage (gentity_t * targ, vec3_t origin)
Definition at line 1089 of file g_combat.c.
 {
     vec3_t    dest;
     trace_t    tr;
     vec3_t    midpoint;
     vec3_t    offsetmins = { -15, -15, -15 };
     vec3_t    offsetmaxs = { 15, 15, 15 };
     // use the midpoint of the bounds instead of the origin, because
     // bmodels may have their origin is 0,0,0
     VectorAdd(targ->r.absmin, targ->r.absmax, midpoint);
     VectorScale(midpoint, 0.5, midpoint);
     VectorCopy(midpoint, dest);
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0 || tr.entityNum == targ->s.number)
         return qtrue;
     // this should probably check in the plane of projection,
     // rather than in world coordinate
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmaxs[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmaxs[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmaxs[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     VectorCopy(midpoint, dest);
     dest[0] += offsetmins[0];
     dest[1] += offsetmins[1];
     dest[2] += offsetmins[2];
     trap_Trace(&tr, origin, vec3_origin, vec3_origin, dest, ENTITYNUM_NONE, MASK_SOLID);
     if (tr.fraction == 1.0)
         return qtrue;
     return qfalse;
 }
References entityShared_t::absmax, entityShared_t::absmin, ENTITYNUM_NONE, MASK_SOLID, entityState_s::number, qfalse, qtrue, gentity_s::r, gentity_s::s, tr, trap_Trace(), vec3_origin, VectorAdd, VectorCopy, and VectorScale.
Referenced by G_RadiusDamage().
CheckGauntletAttack()
qboolean CheckGauntletAttack (gentity_t * ent)
Definition at line 71 of file g_weapon.c.
 {
     trace_t        tr;
     vec3_t        end;
     gentity_t* tent;
     gentity_t* traceEnt;
     int            damage;
     // set aiming directions
     AngleVectors(ent->client->ps.viewangles, forward, right, up);
     CalcMuzzlePoint(ent, forward, right, up, muzzle);
     VectorMA(muzzle, 32, forward, end);
     trap_Trace(&tr, muzzle, NULL, NULL, end, ent->s.number, MASK_SHOT);
     if (tr.surfaceFlags & SURF_NOIMPACT) {
         return qfalse;
     }
     if (ent->client->noclip) {
         return qfalse;
     }
     traceEnt = &g_entities[tr.entityNum];
     // send blood impact
     if (traceEnt->takedamage && traceEnt->client) {
         tent = G_TempEntity(tr.endpos, EV_MISSILE_HIT);
         tent->s.otherEntityNum = traceEnt->s.number;
         tent->s.eventParm = DirToByte(tr.plane.normal);
         tent->s.weapon = ent->s.weapon;
     }
     if (!traceEnt->takedamage) {
         return qfalse;
     }
     if (ent->client->ps.powerups[PW_QUAD]) {
         G_AddEvent(ent, EV_POWERUP_QUAD, 0);
         s_quadFactor = g_quadfactor.value;
     } else {
         s_quadFactor = 1;
     }
 #ifdef MISSIONPACK
     if (ent->client->persistantPowerup && ent->client->persistantPowerup->item && ent->client->persistantPowerup->item->giTag == PW_DOUBLER) {
         s_quadFactor *= 2;
     }
 #endif
     damage = 50 * s_quadFactor;
     G_Damage(traceEnt, ent, ent, forward, tr.endpos,
         damage, 0, MOD_GAUNTLET);
     return qtrue;
 }
References AngleVectors(), CalcMuzzlePoint(), gentity_s::client, DirToByte(), EV_MISSILE_HIT, EV_POWERUP_QUAD, entityState_s::eventParm, forward, G_AddEvent(), G_Damage(), g_entities, g_quadfactor, G_TempEntity(), MASK_SHOT, MOD_GAUNTLET, muzzle, gclient_s::noclip, NULL, entityState_s::number, entityState_s::otherEntityNum, playerState_s::powerups, gclient_s::ps, PW_DOUBLER, PW_QUAD, qfalse, qtrue, right, gentity_s::s, s_quadFactor, SURF_NOIMPACT, gentity_s::takedamage, tr, trap_Trace(), up, vmCvar_t::value, VectorMA, playerState_s::viewangles, and entityState_s::weapon.
Referenced by ClientThink_real().
CheckObeliskAttack()
qboolean CheckObeliskAttack (gentity_t * obelisk, gentity_t * attacker)
Referenced by G_Damage().
CheckTeamLeader()
void CheckTeamLeader (int team)
Definition at line 1686 of file g_main.c.
 {
     int i;
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].sess.sessionTeam != team)
             continue;
         if (level.clients[i].sess.teamLeader)
             break;
     }
     if (i >= level.maxclients) {
         for (i = 0; i < level.maxclients; i++) {
             if (level.clients[i].sess.sessionTeam != team)
                 continue;
             if (!(g_entities[i].r.svFlags & SVF_BOT)) {
                 level.clients[i].sess.teamLeader = qtrue;
                 break;
             }
         }
         if (i >= level.maxclients) {
             for (i = 0; i < level.maxclients; i++) {
                 if (level.clients[i].sess.sessionTeam != team)
                     continue;
                 level.clients[i].sess.teamLeader = qtrue;
                 break;
             }
         }
     }
 }
References level_locals_t::clients, g_entities, level, level_locals_t::maxclients, qtrue, gclient_s::sess, clientSession_t::sessionTeam, SVF_BOT, and clientSession_t::teamLeader.
Referenced by SetTeam().
ClearRegisteredItems()
void ClearRegisteredItems (void)
Definition at line 807 of file g_items.c.
 {
     memset(itemRegistered, 0, sizeof(itemRegistered));
     // players always start with the base weapon
     RegisterItem(BG_FindItemForWeapon(WP_MACHINEGUN));
     RegisterItem(BG_FindItemForWeapon(WP_GAUNTLET));
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_HARVESTER) {
         RegisterItem(BG_FindItem("Red Cube"));
         RegisterItem(BG_FindItem("Blue Cube"));
     }
 #endif
 }
References BG_FindItem(), BG_FindItemForWeapon(), g_gametype, GT_HARVESTER, itemRegistered, RegisterItem(), WP_GAUNTLET, and WP_MACHINEGUN.
Referenced by G_InitGame().
ClientBegin()
void ClientBegin (int clientNum)
ClientBegin is called when a client has finished connecting, and is ready to be placed into the level.
This will happen every level load, and on transition between teams, but doesn't happen on respawns.
Definition at line 983 of file g_client.c.
 {
     gentity_t* ent;
     gclient_t* client;
     int         flags;
     ent = g_entities + clientNum;
     client = level.clients + clientNum;
     if (ent->r.linked)
         trap_UnlinkEntity(ent);
     G_InitGentity(ent);
     ent->touch = 0;
     ent->pain = 0;
     ent->client = client;
     client->pers.connected = CON_CONNECTED;
     client->pers.enterTime = level.time;
     client->pers.teamState.state = TEAM_BEGIN;
     // save eflags around this, because changing teams will
     // cause this to happen with a valid entity, and we
     // want to make sure the teleport bit is set right
     // so the viewpoint doesn't interpolate through the
     // world to the new position
     flags = client->ps.eFlags;
     memset(&client->ps, 0, sizeof(client->ps));
     client->ps.eFlags = flags;
     // locate ent at a spawn point
     ClientSpawn(ent);
     if (client->sess.sessionTeam != TEAM_SPECTATOR) {
         if (g_gametype.integer != GT_TOURNAMENT)
             trap_SendServerCommand(-1, va("print \"%s" S_COLOR_WHITE " entered the game\n\"", client->pers.netname));
     }
     G_LogPrintf("ClientBegin: %i\n", clientNum);
     // count current clients and rank for scoreboard
     CalculateRanks();
 }
References CalculateRanks(), gentity_s::client, level_locals_t::clients, ClientSpawn(), CON_CONNECTED, clientPersistant_t::connected, playerState_s::eFlags, clientPersistant_t::enterTime, g_entities, g_gametype, G_InitGentity(), G_LogPrintf(), GT_TOURNAMENT, level, entityShared_t::linked, clientPersistant_t::netname, gentity_s::pain, gclient_s::pers, gclient_s::ps, gentity_s::r, S_COLOR_WHITE, gclient_s::sess, clientSession_t::sessionTeam, playerTeamState_t::state, TEAM_BEGIN, TEAM_SPECTATOR, clientPersistant_t::teamState, level_locals_t::time, gentity_s::touch, trap_SendServerCommand(), trap_UnlinkEntity(), and va().
Referenced by AddBotToSpawnQueue(), G_AddBot(), G_CheckBotSpawn(), SetTeam(), SpectatorClientEndFrame(), and vmMain().
ClientCommand()
void ClientCommand (int clientNum)
Definition at line 1725 of file g_cmds.c.
 {
     gentity_t* ent;
     char       cmd[MAX_TOKEN_CHARS];
     ent = g_entities + clientNum;
     if (!ent->client || ent->client->pers.connected != CON_CONNECTED) {
         if (ent->client && ent->client->pers.localClient) {
             // Handle early team command sent by UI when starting a local
             // team play game.
             trap_Argv(0, cmd, sizeof(cmd));
             if (Q_stricmp(cmd, "team") == 0) {
                 Cmd_Team_f(ent);
             }
         }
         return; // not fully in game yet
     }
     trap_Argv(0, cmd, sizeof(cmd));
     if (Q_stricmp(cmd, "say") == 0) {
         Cmd_Say_f(ent, SAY_ALL, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "say_team") == 0) {
         Cmd_Say_f(ent, SAY_TEAM, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "tell") == 0) {
         Cmd_Tell_f(ent);
         return;
     }
 #ifdef MISSIONPACK
     if (Q_stricmp(cmd, "vsay") == 0) {
         Cmd_Voice_f(ent, SAY_ALL, qfalse, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "vsay_team") == 0) {
         Cmd_Voice_f(ent, SAY_TEAM, qfalse, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "vtell") == 0) {
         Cmd_VoiceTell_f(ent, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "vosay") == 0) {
         Cmd_Voice_f(ent, SAY_ALL, qfalse, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "vosay_team") == 0) {
         Cmd_Voice_f(ent, SAY_TEAM, qfalse, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "votell") == 0) {
         Cmd_VoiceTell_f(ent, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "vtaunt") == 0) {
         Cmd_VoiceTaunt_f(ent);
         return;
     }
 #endif
     if (Q_stricmp(cmd, "score") == 0) {
         Cmd_Score_f(ent);
         return;
     }
     // ignore all other commands when at intermission
     if (level.intermissiontime) {
         Cmd_Say_f(ent, qfalse, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "give") == 0)
         Cmd_Give_f(ent);
     else if (Q_stricmp(cmd, "god") == 0)
         Cmd_God_f(ent);
     else if (Q_stricmp(cmd, "notarget") == 0)
         Cmd_Notarget_f(ent);
     else if (Q_stricmp(cmd, "noclip") == 0)
         Cmd_Noclip_f(ent);
     else if (Q_stricmp(cmd, "kill") == 0)
         Cmd_Kill_f(ent);
     else if (Q_stricmp(cmd, "teamtask") == 0)
         Cmd_TeamTask_f(ent);
     else if (Q_stricmp(cmd, "levelshot") == 0)
         Cmd_LevelShot_f(ent);
     else if (Q_stricmp(cmd, "follow") == 0)
         Cmd_Follow_f(ent);
     else if (Q_stricmp(cmd, "follownext") == 0)
         Cmd_FollowCycle_f(ent, 1);
     else if (Q_stricmp(cmd, "followprev") == 0)
         Cmd_FollowCycle_f(ent, -1);
     else if (Q_stricmp(cmd, "team") == 0)
         Cmd_Team_f(ent);
     else if (Q_stricmp(cmd, "where") == 0)
         Cmd_Where_f(ent);
     else if (Q_stricmp(cmd, "callvote") == 0)
         Cmd_CallVote_f(ent);
     else if (Q_stricmp(cmd, "vote") == 0)
         Cmd_Vote_f(ent);
     else if (Q_stricmp(cmd, "callteamvote") == 0)
         Cmd_CallTeamVote_f(ent);
     else if (Q_stricmp(cmd, "teamvote") == 0)
         Cmd_TeamVote_f(ent);
     else if (Q_stricmp(cmd, "gc") == 0)
         Cmd_GameCommand_f(ent);
     else if (Q_stricmp(cmd, "setviewpos") == 0)
         Cmd_SetViewpos_f(ent);
     else if (Q_stricmp(cmd, "stats") == 0)
         Cmd_Stats_f(ent);
     else
         trap_SendServerCommand(clientNum, va("print \"unknown cmd %s\n\"", cmd));
 }
References gentity_s::client, Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_GameCommand_f(), Cmd_Give_f(), Cmd_God_f(), Cmd_Kill_f(), Cmd_LevelShot_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_Say_f(), Cmd_Score_f(), Cmd_SetViewpos_f(), Cmd_Stats_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_Vote_f(), Cmd_Where_f(), CON_CONNECTED, clientPersistant_t::connected, g_entities, level_locals_t::intermissiontime, level, clientPersistant_t::localClient, MAX_TOKEN_CHARS, gclient_s::pers, Q_stricmp(), qfalse, qtrue, SAY_ALL, SAY_TEAM, trap_Argv(), trap_SendServerCommand(), and va().
Referenced by vmMain().
ClientConnect()
char* ClientConnect (int clientNum, qboolean firstTime, qboolean isBot)
Definition at line 885 of file g_client.c.
 {
     char* value;
     //    char        *areabits;
     gclient_t* client;
     char        userinfo[MAX_INFO_STRING];
     gentity_t* ent;
     ent = &g_entities[clientNum];
     trap_GetUserinfo(clientNum, userinfo, sizeof(userinfo));
     // IP filtering
     // https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=500
     // recommanding PB based IP / GUID banning, the builtin system is pretty limited
     // check to see if they are on the banned IP list
     value = Info_ValueForKey(userinfo, "ip");
     if (G_FilterPacket(value)) {
         return "You are banned from this server.";
     }
     // we don't check password for bots and local client
     // NOTE: local client <-> "ip" "localhost"
     //   this means this client is not running in our current process
     if (!isBot && (strcmp(value, "localhost") != 0)) {
         // check for a password
         value = Info_ValueForKey(userinfo, "password");
         if (g_password.string[0] && Q_stricmp(g_password.string, "none") &&
             strcmp(g_password.string, value) != 0) {
             return "Invalid password";
         }
     }
     // if a player reconnects quickly after a disconnect, the client disconnect may never be called, thus flag can get lost in the ether
     if (ent->inuse) {
         G_LogPrintf("Forcing disconnect on active client: %i\n", clientNum);
         // so lets just fix up anything that should happen on a disconnect
         ClientDisconnect(clientNum);
     }
     // they can connect
     ent->client = level.clients + clientNum;
     client = ent->client;
     //    areabits = client->areabits;
     memset(client, 0, sizeof(*client));
     client->pers.connected = CON_CONNECTING;
     // check for local client
     value = Info_ValueForKey(userinfo, "ip");
     if (!strcmp(value, "localhost")) {
         client->pers.localClient = qtrue;
     }
     if (isBot) {
         ent->r.svFlags |= SVF_BOT;
         ent->inuse = qtrue;
         if (!G_BotConnect(clientNum, !firstTime)) {
             return "BotConnectfailed";
         }
     }
     // read or initialize the session data
     if (firstTime || level.newSession) {
         G_InitSessionData(client, userinfo);
     }
     G_ReadSessionData(client);
     // get and distribute relevant parameters
     G_LogPrintf("ClientConnect: %i\n", clientNum);
     ClientUserinfoChanged(clientNum);
     // don't do the "xxx connected" messages if they were caried over from previous level
     if (firstTime) {
         trap_SendServerCommand(-1, va("print \"%s" S_COLOR_WHITE " connected\n\"", client->pers.netname));
     }
     if (g_gametype.integer >= GT_TEAM &&
         client->sess.sessionTeam != TEAM_SPECTATOR) {
         BroadcastTeamChange(client, -1);
     }
     // count current clients and rank for scoreboard
     CalculateRanks();
     // for statistics
 //    client->areabits = areabits;
 //    if ( !client->areabits )
 //        client->areabits = G_Alloc( (trap_AAS_PointReachabilityAreaIndex( NULL ) + 7) / 8 );
     return NULL;
 }
References BroadcastTeamChange(), CalculateRanks(), gentity_s::client, ClientDisconnect(), level_locals_t::clients, ClientUserinfoChanged(), CON_CONNECTING, clientPersistant_t::connected, G_BotConnect(), g_entities, G_FilterPacket(), g_gametype, G_InitSessionData(), G_LogPrintf(), g_password, G_ReadSessionData(), GT_TEAM, Info_ValueForKey(), gentity_s::inuse, level, clientPersistant_t::localClient, MAX_INFO_STRING, clientPersistant_t::netname, level_locals_t::newSession, NULL, gclient_s::pers, Q_stricmp(), qtrue, gentity_s::r, S_COLOR_WHITE, gclient_s::sess, clientSession_t::sessionTeam, vmCvar_t::string, SVF_BOT, entityShared_t::svFlags, TEAM_SPECTATOR, trap_GetUserinfo(), trap_SendServerCommand(), and va().
Referenced by G_AddBot(), and vmMain().
ClientDisconnect()
void ClientDisconnect (int clientNum)
Definition at line 1246 of file g_client.c.
 {
     gentity_t* ent;
     gentity_t* tent;
     int            i;
     // cleanup if we are kicking a bot that
     // hasn't spawned yet
     G_RemoveQueuedBotBegin(clientNum);
     ent = g_entities + clientNum;
     if (!ent->client || ent->client->pers.connected == CON_DISCONNECTED) {
         return;
     }
     // stop any following clients
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].sess.sessionTeam == TEAM_SPECTATOR
             && level.clients[i].sess.spectatorState == SPECTATOR_FOLLOW
             && level.clients[i].sess.spectatorClient == clientNum) {
             StopFollowing(&g_entities[i]);
         }
     }
     // send effect if they were completely connected
     if (ent->client->pers.connected == CON_CONNECTED
         && ent->client->sess.sessionTeam != TEAM_SPECTATOR) {
         tent = G_TempEntity(ent->client->ps.origin, EV_PLAYER_TELEPORT_OUT);
         tent->s.clientNum = ent->s.clientNum;
         // They don't get to take powerups with them!
         // Especially important for stuff like CTF flags
         TossClientItems(ent);
 #ifdef MISSIONPACK
         TossClientPersistantPowerups(ent);
         if (g_gametype.integer == GT_HARVESTER) {
             TossClientCubes(ent);
         }
 #endif
     }
     G_LogPrintf("ClientDisconnect: %i\n", clientNum);
     // if we are playing in tourney mode and losing, give a win to the other player
     if ((g_gametype.integer == GT_TOURNAMENT)
         && !level.intermissiontime
         && !level.warmupTime && level.sortedClients[1] == clientNum) {
         level.clients[level.sortedClients[0]].sess.wins++;
         ClientUserinfoChanged(level.sortedClients[0]);
     }
     if (g_gametype.integer == GT_TOURNAMENT &&
         ent->client->sess.sessionTeam == TEAM_FREE &&
         level.intermissiontime) {
         trap_SendConsoleCommand(EXEC_APPEND, "map_restart 0\n");
         level.restarted = qtrue;
         level.changemap = NULL;
         level.intermissiontime = 0;
     }
     trap_UnlinkEntity(ent);
     ent->s.modelindex = 0;
     ent->inuse = qfalse;
     ent->classname = "disconnected";
     ent->client->pers.connected = CON_DISCONNECTED;
     ent->client->ps.persistant[PERS_TEAM] = TEAM_FREE;
     ent->client->sess.sessionTeam = TEAM_FREE;
     trap_SetConfigstring(CS_PLAYERS + clientNum, "");
     CalculateRanks();
     if (ent->r.svFlags & SVF_BOT) {
         BotAIShutdownClient(clientNum, qfalse);
     }
 }
References BotAIShutdownClient(), CalculateRanks(), level_locals_t::changemap, gentity_s::classname, gentity_s::client, entityState_s::clientNum, level_locals_t::clients, ClientUserinfoChanged(), CON_CONNECTED, CON_DISCONNECTED, clientPersistant_t::connected, CS_PLAYERS, EV_PLAYER_TELEPORT_OUT, EXEC_APPEND, g_entities, g_gametype, G_LogPrintf(), G_RemoveQueuedBotBegin(), G_TempEntity(), GT_HARVESTER, GT_TOURNAMENT, level_locals_t::intermissiontime, gentity_s::inuse, level, level_locals_t::maxclients, entityState_s::modelindex, NULL, playerState_s::origin, gclient_s::pers, PERS_TEAM, playerState_s::persistant, gclient_s::ps, qfalse, qtrue, gentity_s::r, level_locals_t::restarted, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, level_locals_t::sortedClients, SPECTATOR_FOLLOW, clientSession_t::spectatorClient, clientSession_t::spectatorState, StopFollowing(), SVF_BOT, entityShared_t::svFlags, TEAM_FREE, TEAM_SPECTATOR, TossClientCubes(), TossClientItems(), trap_SendConsoleCommand(), trap_SetConfigstring(), trap_UnlinkEntity(), level_locals_t::warmupTime, and clientSession_t::wins.
Referenced by ClientConnect(), and vmMain().
ClientEndFrame()
void ClientEndFrame (gentity_t * ent)
Definition at line 1106 of file g_active.c.
 {
     int            i;
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         SpectatorClientEndFrame(ent);
         return;
     }
     // turn off any expired powerups
     for (i = 0; i < MAX_POWERUPS; i++) {
         if (ent->client->ps.powerups[i] < level.time) {
             ent->client->ps.powerups[i] = 0;
         }
     }
 #ifdef MISSIONPACK
     // set powerup for player animation
     if (bg_itemlist[ent->client->ps.stats[STAT_PERSISTANT_POWERUP]].giTag == PW_GUARD) {
         ent->client->ps.powerups[PW_GUARD] = level.time;
     }
     if (bg_itemlist[ent->client->ps.stats[STAT_PERSISTANT_POWERUP]].giTag == PW_SCOUT) {
         ent->client->ps.powerups[PW_SCOUT] = level.time;
     }
     if (bg_itemlist[ent->client->ps.stats[STAT_PERSISTANT_POWERUP]].giTag == PW_DOUBLER) {
         ent->client->ps.powerups[PW_DOUBLER] = level.time;
     }
     if (bg_itemlist[ent->client->ps.stats[STAT_PERSISTANT_POWERUP]].giTag == PW_AMMOREGEN) {
         ent->client->ps.powerups[PW_AMMOREGEN] = level.time;
     }
     if (ent->client->invulnerabilityTime > level.time) {
         ent->client->ps.powerups[PW_INVULNERABILITY] = level.time;
     }
 #endif
     // save network bandwidth
 #if 0
     if (!g_synchronousClients->integer && ent->client->ps.pm_type == PM_NORMAL) {
         // FIXME: this must change eventually for non-sync demo recording
         VectorClear(ent->client->ps.viewangles);
     }
 #endif
     //
     // If the end of unit layout is displayed, don't give
     // the player any normal movement attributes
     //
     if (level.intermissiontime) {
         return;
     }
     // burn from lava, etc
     P_WorldEffects(ent);
     // apply all the damage taken this frame
     P_DamageFeedback(ent);
     // add the EF_CONNECTION flag if we haven't gotten commands recently
     if (level.time - ent->client->lastCmdTime > 1000) {
         ent->client->ps.eFlags |= EF_CONNECTION;
     } else {
         ent->client->ps.eFlags &= ~EF_CONNECTION;
     }
     ent->client->ps.stats[STAT_HEALTH] = ent->health;    // FIXME: get rid of ent->health...
     G_SetClientSound(ent);
     // set the latest infor
     if (g_smoothClients.integer) {
         BG_PlayerStateToEntityStateExtraPolate(&ent->client->ps, &ent->s, ent->client->ps.commandTime, qtrue);
     } else {
         BG_PlayerStateToEntityState(&ent->client->ps, &ent->s, qtrue);
     }
     SendPendingPredictableEvents(&ent->client->ps);
     // set the bit for the reachability area the client is currently in
 //    i = trap_AAS_PointReachabilityAreaIndex( ent->client->ps.origin );
 //    ent->client->areabits[i >> 3] |= 1 << (i & 7);
 }
References bg_itemlist, BG_PlayerStateToEntityState(), BG_PlayerStateToEntityStateExtraPolate(), gentity_s::client, playerState_s::commandTime, EF_CONNECTION, playerState_s::eFlags, G_SetClientSound(), g_smoothClients, g_synchronousClients, gitem_s::giTag, gentity_s::health, vmCvar_t::integer, level_locals_t::intermissiontime, gclient_s::lastCmdTime, level, MAX_POWERUPS, P_DamageFeedback(), P_WorldEffects(), PM_NORMAL, playerState_s::pm_type, playerState_s::powerups, gclient_s::ps, PW_AMMOREGEN, PW_DOUBLER, PW_GUARD, PW_INVULNERABILITY, PW_SCOUT, qtrue, gentity_s::s, SendPendingPredictableEvents(), gclient_s::sess, clientSession_t::sessionTeam, SpectatorClientEndFrame(), STAT_HEALTH, playerState_s::stats, TEAM_SPECTATOR, level_locals_t::time, VectorClear, and playerState_s::viewangles.
Referenced by ClientSpawn(), and G_RunFrame().
ClientRespawn()
void ClientRespawn (gentity_t * ent)
Definition at line 533 of file g_client.c.
 {
     CopyToBodyQue(ent);
     ClientSpawn(ent);
 }
References ClientSpawn(), and CopyToBodyQue().
Referenced by BeginIntermission(), and ClientThink_real().
ClientSpawn()
void ClientSpawn (gentity_t * ent)
Definition at line 1036 of file g_client.c.
 {
     int        index;
     vec3_t    spawn_origin, spawn_angles;
     gclient_t* client;
     int        i;
     clientPersistant_t    saved;
     clientSession_t        savedSess;
     int        persistant[MAX_PERSISTANT];
     gentity_t* spawnPoint;
     gentity_t* tent;
     int        flags;
     int        savedPing;
     //    char    *savedAreaBits;
     int        accuracy_hits, accuracy_shots;
     int        eventSequence;
     char    userinfo[MAX_INFO_STRING];
     index = ent - g_entities;
     client = ent->client;
     VectorClear(spawn_origin);
     // find a spawn point
     // do it before setting health back up, so farthest
     // ranging doesn't count this client
     if (client->sess.sessionTeam == TEAM_SPECTATOR) {
         spawnPoint = SelectSpectatorSpawnPoint(
             spawn_origin, spawn_angles);
     } else if (g_gametype.integer >= GT_CTF) {
         // all base oriented team games use the CTF spawn points
         spawnPoint = SelectCTFSpawnPoint(
             client->sess.sessionTeam,
             client->pers.teamState.state,
             spawn_origin, spawn_angles,
             !!(ent->r.svFlags & SVF_BOT));
     } else {
         // the first spawn should be at a good looking spot
         if (!client->pers.initialSpawn && client->pers.localClient) {
             client->pers.initialSpawn = qtrue;
             spawnPoint = SelectInitialSpawnPoint(spawn_origin, spawn_angles,
                 !!(ent->r.svFlags & SVF_BOT));
         } else {
             // don't spawn near existing origin if possible
             spawnPoint = SelectSpawnPoint(
                 client->ps.origin,
                 spawn_origin, spawn_angles, !!(ent->r.svFlags & SVF_BOT));
         }
     }
     client->pers.teamState.state = TEAM_ACTIVE;
     // always clear the kamikaze flag
     ent->s.eFlags &= ~EF_KAMIKAZE;
     // toggle the teleport bit so the client knows to not lerp
     // and never clear the voted flag
     flags = ent->client->ps.eFlags & (EF_TELEPORT_BIT | EF_VOTED | EF_TEAMVOTED);
     flags ^= EF_TELEPORT_BIT;
     // clear everything but the persistant data
     saved = client->pers;
     savedSess = client->sess;
     savedPing = client->ps.ping;
     //    savedAreaBits = client->areabits;
     accuracy_hits = client->accuracy_hits;
     accuracy_shots = client->accuracy_shots;
     for (i = 0; i < MAX_PERSISTANT; i++) {
         persistant[i] = client->ps.persistant[i];
     }
     eventSequence = client->ps.eventSequence;
     Com_Memset(client, 0, sizeof(*client));
     client->pers = saved;
     client->sess = savedSess;
     client->ps.ping = savedPing;
     //    client->areabits = savedAreaBits;
     client->accuracy_hits = accuracy_hits;
     client->accuracy_shots = accuracy_shots;
     client->lastkilled_client = -1;
     for (i = 0; i < MAX_PERSISTANT; i++) {
         client->ps.persistant[i] = persistant[i];
     }
     client->ps.eventSequence = eventSequence;
     // increment the spawncount so the client will detect the respawn
     client->ps.persistant[PERS_SPAWN_COUNT]++;
     client->ps.persistant[PERS_TEAM] = client->sess.sessionTeam;
     client->airOutTime = level.time + 12000;
     trap_GetUserinfo(index, userinfo, sizeof(userinfo));
     // set max health
     client->pers.maxHealth = atoi(Info_ValueForKey(userinfo, "handicap"));
     if (client->pers.maxHealth < 1 || client->pers.maxHealth > 100) {
         client->pers.maxHealth = 100;
     }
     // clear entity values
     client->ps.stats[STAT_MAX_HEALTH] = client->pers.maxHealth;
     client->ps.eFlags = flags;
     ent->s.groundEntityNum = ENTITYNUM_NONE;
     ent->client = &level.clients[index];
     ent->takedamage = qtrue;
     ent->inuse = qtrue;
     ent->classname = "player";
     ent->r.contents = CONTENTS_BODY;
     ent->clipmask = MASK_PLAYERSOLID;
     ent->die = player_die;
     ent->waterlevel = 0;
     ent->watertype = 0;
     ent->flags = 0;
     VectorCopy(playerMins, ent->r.mins);
     VectorCopy(playerMaxs, ent->r.maxs);
     client->ps.clientNum = index;
     client->ps.stats[STAT_WEAPONS] = (1 << WP_MACHINEGUN);
     if (g_gametype.integer == GT_TEAM) {
         client->ps.ammo[WP_MACHINEGUN] = 50;
     } else {
         client->ps.ammo[WP_MACHINEGUN] = 100;
     }
     client->ps.stats[STAT_WEAPONS] |= (1 << WP_GAUNTLET);
     client->ps.ammo[WP_GAUNTLET] = -1;
     client->ps.ammo[WP_GRAPPLING_HOOK] = -1;
     // health will count down towards max_health
     ent->health = client->ps.stats[STAT_HEALTH] = client->ps.stats[STAT_MAX_HEALTH] + 25;
     G_SetOrigin(ent, spawn_origin);
     VectorCopy(spawn_origin, client->ps.origin);
     // the respawned flag will be cleared after the attack and jump keys come up
     client->ps.pm_flags |= PMF_RESPAWNED;
     trap_GetUsercmd(client - level.clients, &ent->client->pers.cmd);
     SetClientViewAngle(ent, spawn_angles);
     // don't allow full run speed for a bit
     client->ps.pm_flags |= PMF_TIME_KNOCKBACK;
     client->ps.pm_time = 100;
     client->respawnTime = level.time;
     client->inactivityTime = level.time + g_inactivity.integer * 1000;
     client->latched_buttons = 0;
     // set default animations
     client->ps.torsoAnim = TORSO_STAND;
     client->ps.legsAnim = LEGS_IDLE;
     if (!level.intermissiontime) {
         if (ent->client->sess.sessionTeam != TEAM_SPECTATOR) {
             G_KillBox(ent);
             // force the base weapon up
             client->ps.weapon = WP_MACHINEGUN;
             client->ps.weaponstate = WEAPON_READY;
             // fire the targets of the spawn point
             G_UseTargets(spawnPoint, ent);
             // select the highest weapon number available, after any spawn given items have fired
             client->ps.weapon = 1;
             for (i = WP_NUM_WEAPONS - 1; i > 0; i--) {
                 if (client->ps.stats[STAT_WEAPONS] & (1 << i)) {
                     client->ps.weapon = i;
                     break;
                 }
             }
             // positively link the client, even if the command times are weird
             VectorCopy(ent->client->ps.origin, ent->r.currentOrigin);
             tent = G_TempEntity(ent->client->ps.origin, EV_PLAYER_TELEPORT_IN);
             tent->s.clientNum = ent->s.clientNum;
             trap_LinkEntity(ent);
         }
     } else {
         // move players to intermission
         MoveClientToIntermission(ent);
     }
     // run a client frame to drop exactly to the floor,
     // initialize animations and other things
     client->ps.commandTime = level.time - 100;
     ent->client->pers.cmd.serverTime = level.time;
     ClientThink(ent - g_entities);
     // run the presend to set anything else, follow spectators wait
     // until all clients have been reconnected after map_restart
     if (ent->client->sess.spectatorState != SPECTATOR_FOLLOW) {
         ClientEndFrame(ent);
     }
     // clear entity state values
     BG_PlayerStateToEntityState(&client->ps, &ent->s, qtrue);
 }
References gclient_s::accuracy_hits, gclient_s::accuracy_shots, gclient_s::airOutTime, playerState_s::ammo, BG_PlayerStateToEntityState(), gentity_s::classname, gentity_s::client, ClientEndFrame(), playerState_s::clientNum, entityState_s::clientNum, level_locals_t::clients, ClientThink(), gentity_s::clipmask, clientPersistant_t::cmd, Com_Memset, playerState_s::commandTime, entityShared_t::contents, CONTENTS_BODY, entityShared_t::currentOrigin, gentity_s::die, EF_KAMIKAZE, EF_TEAMVOTED, EF_TELEPORT_BIT, EF_VOTED, playerState_s::eFlags, entityState_s::eFlags, ENTITYNUM_NONE, EV_PLAYER_TELEPORT_IN, playerState_s::eventSequence, gentity_s::flags, g_entities, g_gametype, g_inactivity, G_KillBox(), G_SetOrigin(), G_TempEntity(), G_UseTargets(), entityState_s::groundEntityNum, GT_CTF, GT_TEAM, gentity_s::health, gclient_s::inactivityTime, Info_ValueForKey(), clientPersistant_t::initialSpawn, vmCvar_t::integer, level_locals_t::intermissiontime, gentity_s::inuse, gclient_s::lastkilled_client, gclient_s::latched_buttons, LEGS_IDLE, playerState_s::legsAnim, level, clientPersistant_t::localClient, MASK_PLAYERSOLID, MAX_INFO_STRING, MAX_PERSISTANT, clientPersistant_t::maxHealth, entityShared_t::maxs, entityShared_t::mins, MoveClientToIntermission(), playerState_s::origin, gclient_s::pers, PERS_SPAWN_COUNT, PERS_TEAM, playerState_s::persistant, playerState_s::ping, player_die(), playerMaxs, playerMins, playerState_s::pm_flags, playerState_s::pm_time, PMF_RESPAWNED, PMF_TIME_KNOCKBACK, gclient_s::ps, qtrue, gentity_s::r, gclient_s::respawnTime, gentity_s::s, SelectCTFSpawnPoint(), SelectInitialSpawnPoint(), SelectSpawnPoint(), SelectSpectatorSpawnPoint(), usercmd_s::serverTime, gclient_s::sess, clientSession_t::sessionTeam, SetClientViewAngle(), SPECTATOR_FOLLOW, clientSession_t::spectatorState, STAT_HEALTH, STAT_MAX_HEALTH, STAT_WEAPONS, playerTeamState_t::state, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, gentity_s::takedamage, TEAM_ACTIVE, TEAM_SPECTATOR, clientPersistant_t::teamState, level_locals_t::time, TORSO_STAND, playerState_s::torsoAnim, trap_GetUsercmd(), trap_GetUserinfo(), trap_LinkEntity(), VectorClear, VectorCopy, gentity_s::waterlevel, gentity_s::watertype, playerState_s::weapon, WEAPON_READY, playerState_s::weaponstate, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_MACHINEGUN, and WP_NUM_WEAPONS.
Referenced by ClientBegin(), ClientRespawn(), and G_RankRunFrame().
ClientThink()
void ClientThink (int clientNum)
Definition at line 1020 of file g_active.c.
 {
     gentity_t* ent;
     ent = g_entities + clientNum;
     trap_GetUsercmd(clientNum, &ent->client->pers.cmd);
     // mark the time we got info, so we can display the
     // phone jack if they don't get any for a while
     ent->client->lastCmdTime = level.time;
     if (!(ent->r.svFlags & SVF_BOT) && !g_synchronousClients.integer) {
         ClientThink_real(ent);
     }
 }
References gentity_s::client, ClientThink_real(), clientPersistant_t::cmd, g_entities, g_synchronousClients, vmCvar_t::integer, gclient_s::lastCmdTime, level, gclient_s::pers, gentity_s::r, SVF_BOT, entityShared_t::svFlags, level_locals_t::time, and trap_GetUsercmd().
Referenced by ClientSpawn(), and vmMain().
ClientUserinfoChanged()
void ClientUserinfoChanged (int clientNum)
Definition at line 700 of file g_client.c.
 {
     gentity_t* ent;
     int        teamTask, teamLeader, health;
     char* s;
     char    model[MAX_QPATH];
     char    headModel[MAX_QPATH];
     char    oldname[MAX_STRING_CHARS];
     gclient_t* client;
     char    c1[MAX_INFO_STRING];
     char    c2[MAX_INFO_STRING];
     char    redTeam[MAX_INFO_STRING];
     char    blueTeam[MAX_INFO_STRING];
     char    userinfo[MAX_INFO_STRING];
     ent = g_entities + clientNum;
     client = ent->client;
     trap_GetUserinfo(clientNum, userinfo, sizeof(userinfo));
     // check for malformed or illegal info strings
     if (!Info_Validate(userinfo)) {
         strcpy(userinfo, "\\name\\badinfo");
         // don't keep those clients and userinfo
         trap_DropClient(clientNum, "Invalid userinfo");
     }
     // check the item prediction
     s = Info_ValueForKey(userinfo, "cg_predictItems");
     if (!atoi(s)) {
         client->pers.predictItemPickup = qfalse;
     } else {
         client->pers.predictItemPickup = qtrue;
     }
     // set name
     Q_strncpyz(oldname, client->pers.netname, sizeof(oldname));
     s = Info_ValueForKey(userinfo, "name");
     ClientCleanName(s, client->pers.netname, sizeof(client->pers.netname));
     if (client->sess.sessionTeam == TEAM_SPECTATOR) {
         if (client->sess.spectatorState == SPECTATOR_SCOREBOARD) {
             Q_strncpyz(client->pers.netname, "scoreboard", sizeof(client->pers.netname));
         }
     }
     if (client->pers.connected == CON_CONNECTED) {
         if (strcmp(oldname, client->pers.netname)) {
             trap_SendServerCommand(-1, va("print \"%s" S_COLOR_WHITE " renamed to %s\n\"", oldname,
                 client->pers.netname));
         }
     }
     // set max health
 #ifdef MISSIONPACK
     if (client->ps.powerups[PW_GUARD]) {
         client->pers.maxHealth = 200;
     } else {
         health = atoi(Info_ValueForKey(userinfo, "handicap"));
         client->pers.maxHealth = health;
         if (client->pers.maxHealth < 1 || client->pers.maxHealth > 100) {
             client->pers.maxHealth = 100;
         }
     }
 #else
     health = atoi(Info_ValueForKey(userinfo, "handicap"));
     client->pers.maxHealth = health;
     if (client->pers.maxHealth < 1 || client->pers.maxHealth > 100) {
         client->pers.maxHealth = 100;
     }
 #endif
     client->ps.stats[STAT_MAX_HEALTH] = client->pers.maxHealth;
     // set model
     if (g_gametype.integer >= GT_TEAM) {
         Q_strncpyz(model, Info_ValueForKey(userinfo, "team_model"), sizeof(model));
         Q_strncpyz(headModel, Info_ValueForKey(userinfo, "team_headmodel"), sizeof(headModel));
     } else {
         Q_strncpyz(model, Info_ValueForKey(userinfo, "model"), sizeof(model));
         Q_strncpyz(headModel, Info_ValueForKey(userinfo, "headmodel"), sizeof(headModel));
     }
     /*    NOTE: all client side now
         // team
         switch( team ) {
         case TEAM_RED:
             ForceClientSkin(client, model, "red");
     //        ForceClientSkin(client, headModel, "red");
             break;
         case TEAM_BLUE:
             ForceClientSkin(client, model, "blue");
     //        ForceClientSkin(client, headModel, "blue");
             break;
         }
         // don't ever use a default skin in teamplay, it would just waste memory
         // however bots will always join a team but they spawn in as spectator
         if ( g_gametype.integer >= GT_TEAM && team == TEAM_SPECTATOR) {
             ForceClientSkin(client, model, "red");
     //        ForceClientSkin(client, headModel, "red");
         }
     */
 #ifdef MISSIONPACK
     if (g_gametype.integer >= GT_TEAM && !(ent->r.svFlags & SVF_BOT)) {
         client->pers.teamInfo = qtrue;
     } else {
         s = Info_ValueForKey(userinfo, "teamoverlay");
         if (!*s || atoi(s) != 0) {
             client->pers.teamInfo = qtrue;
         } else {
             client->pers.teamInfo = qfalse;
         }
     }
 #else
     // teamInfo
     s = Info_ValueForKey(userinfo, "teamoverlay");
     if (!*s || atoi(s) != 0) {
         client->pers.teamInfo = qtrue;
     } else {
         client->pers.teamInfo = qfalse;
     }
 #endif
     /*
     s = Info_ValueForKey( userinfo, "cg_pmove_fixed" );
     if ( !*s || atoi( s ) == 0 ) {
         client->pers.pmoveFixed = qfalse;
     }
     else {
         client->pers.pmoveFixed = qtrue;
     }
     */
     // team task (0 = none, 1 = offence, 2 = defence)
     teamTask = atoi(Info_ValueForKey(userinfo, "teamtask"));
     // team Leader (1 = leader, 0 is normal player)
     teamLeader = client->sess.teamLeader;
     // colors
     Q_strncpyz(c1, Info_ValueForKey(userinfo, "color1"), sizeof(c1));
     Q_strncpyz(c2, Info_ValueForKey(userinfo, "color2"), sizeof(c2));
     Q_strncpyz(redTeam, Info_ValueForKey(userinfo, "g_redteam"), sizeof(redTeam));
     Q_strncpyz(blueTeam, Info_ValueForKey(userinfo, "g_blueteam"), sizeof(blueTeam));
     // send over a subset of the userinfo keys so other clients can
     // print scoreboards, display models, and play custom sounds
     if (ent->r.svFlags & SVF_BOT) {
         s = va("n\\%s\\t\\%i\\model\\%s\\hmodel\\%s\\c1\\%s\\c2\\%s\\hc\\%i\\w\\%i\\l\\%i\\skill\\%s\\tt\\%d\\tl\\%d",
             client->pers.netname, client->sess.sessionTeam, model, headModel, c1, c2,
             client->pers.maxHealth, client->sess.wins, client->sess.losses,
             Info_ValueForKey(userinfo, "skill"), teamTask, teamLeader);
     } else {
         s = va("n\\%s\\t\\%i\\model\\%s\\hmodel\\%s\\g_redteam\\%s\\g_blueteam\\%s\\c1\\%s\\c2\\%s\\hc\\%i\\w\\%i\\l\\%i\\tt\\%d\\tl\\%d",
             client->pers.netname, client->sess.sessionTeam, model, headModel, redTeam, blueTeam, c1, c2,
             client->pers.maxHealth, client->sess.wins, client->sess.losses, teamTask, teamLeader);
     }
     trap_SetConfigstring(CS_PLAYERS + clientNum, s);
     // this is not the userinfo, more like the configstring actually
     G_LogPrintf("ClientUserinfoChanged: %i %s\n", clientNum, s);
 }
References gentity_s::client, ClientCleanName(), CON_CONNECTED, clientPersistant_t::connected, CS_PLAYERS, g_entities, g_gametype, G_LogPrintf(), GT_TEAM, Info_Validate(), Info_ValueForKey(), clientSession_t::losses, MAX_INFO_STRING, MAX_QPATH, MAX_STRING_CHARS, clientPersistant_t::maxHealth, clientPersistant_t::netname, gclient_s::pers, playerState_s::powerups, clientPersistant_t::predictItemPickup, gclient_s::ps, PW_GUARD, Q_strncpyz(), qfalse, qtrue, gentity_s::r, s, S_COLOR_WHITE, gclient_s::sess, clientSession_t::sessionTeam, SPECTATOR_SCOREBOARD, clientSession_t::spectatorState, STAT_MAX_HEALTH, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, TEAM_SPECTATOR, clientPersistant_t::teamInfo, clientSession_t::teamLeader, trap_DropClient(), trap_GetUserinfo(), trap_SendServerCommand(), trap_SetConfigstring(), va(), and clientSession_t::wins.
Referenced by AdjustTournamentScores(), BotSetUserInfo(), ClientConnect(), ClientDisconnect(), Cmd_TeamTask_f(), SetLeader(), SetTeam(), and vmMain().
Cmd_FollowCycle_f()
void Cmd_FollowCycle_f (gentity_t * ent, int dir)
Definition at line 783 of file g_cmds.c.
 {
     int        clientnum;
     int        original;
     // if they are playing a tournement game, count as a loss
     if ((g_gametype.integer == GT_TOURNAMENT)
         && ent->client->sess.sessionTeam == TEAM_FREE) {
         ent->client->sess.losses++;
     }
     // first set them to spectator
     if (ent->client->sess.spectatorState == SPECTATOR_NOT) {
         SetTeam(ent, "spectator");
     }
     if (dir != 1 && dir != -1) {
         G_Error("Cmd_FollowCycle_f: bad dir %i", dir);
     }
     // if dedicated follow client, just switch between the two auto clients
     if (ent->client->sess.spectatorClient < 0) {
         if (ent->client->sess.spectatorClient == -1) {
             ent->client->sess.spectatorClient = -2;
         } else if (ent->client->sess.spectatorClient == -2) {
             ent->client->sess.spectatorClient = -1;
         }
         return;
     }
     clientnum = ent->client->sess.spectatorClient;
     original = clientnum;
     do {
         clientnum += dir;
         if (clientnum >= level.maxclients) {
             clientnum = 0;
         }
         if (clientnum < 0) {
             clientnum = level.maxclients - 1;
         }
         // can only follow connected clients
         if (level.clients[clientnum].pers.connected != CON_CONNECTED) {
             continue;
         }
         // can't follow another spectator
         if (level.clients[clientnum].sess.sessionTeam == TEAM_SPECTATOR) {
             continue;
         }
         // this is good, we can use it
         ent->client->sess.spectatorClient = clientnum;
         ent->client->sess.spectatorState = SPECTATOR_FOLLOW;
         return;
     } while (clientnum != original);
     // leave it where it was
 }
References gentity_s::client, level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, G_Error(), g_gametype, GT_TOURNAMENT, level, clientSession_t::losses, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), SPECTATOR_FOLLOW, SPECTATOR_NOT, clientSession_t::spectatorClient, clientSession_t::spectatorState, TEAM_FREE, and TEAM_SPECTATOR.
Referenced by ClientCommand(), and SpectatorThink().
Cmd_Score_f()
void Cmd_Score_f (gentity_t * ent)
Definition at line 105 of file g_cmds.c.
 {
     DeathmatchScoreboardMessage(ent);
 }
References DeathmatchScoreboardMessage().
Referenced by ClientCommand(), and player_die().
ConsoleCommand()
qboolean ConsoleCommand (void)
Definition at line 442 of file g_svcmds.c.
 {
     char    cmd[MAX_TOKEN_CHARS];
     trap_Argv(0, cmd, sizeof(cmd));
     if (Q_stricmp(cmd, "entitylist") == 0) {
         Svcmd_EntityList_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "forceteam") == 0) {
         Svcmd_ForceTeam_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "game_memory") == 0) {
         Svcmd_GameMem_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "addbot") == 0) {
         Svcmd_AddBot_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "botlist") == 0) {
         Svcmd_BotList_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "abort_podium") == 0) {
         Svcmd_AbortPodium_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "addip") == 0) {
         Svcmd_AddIP_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "removeip") == 0) {
         Svcmd_RemoveIP_f();
         return qtrue;
     }
     if (Q_stricmp(cmd, "listip") == 0) {
         trap_SendConsoleCommand(EXEC_NOW, "g_banIPs\n");
         return qtrue;
     }
     if (g_dedicated.integer) {
         if (Q_stricmp(cmd, "say") == 0) {
             trap_SendServerCommand(-1, va("print \"server: %s\n\"", ConcatArgs(1)));
             return qtrue;
         }
         // everything else will also be printed as a say command
         trap_SendServerCommand(-1, va("print \"server: %s\n\"", ConcatArgs(0)));
         return qtrue;
     }
     return qfalse;
 }
References ConcatArgs(), EXEC_NOW, g_dedicated, vmCvar_t::integer, MAX_TOKEN_CHARS, Q_stricmp(), qfalse, qtrue, Svcmd_AbortPodium_f(), Svcmd_AddBot_f(), Svcmd_AddIP_f(), Svcmd_BotList_f(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), Svcmd_GameMem_f(), Svcmd_RemoveIP_f(), trap_Argv(), trap_SendConsoleCommand(), trap_SendServerCommand(), and va().
Referenced by vmMain().
CopyToBodyQue()
void CopyToBodyQue (gentity_t * ent)
Definition at line 403 of file g_client.c.
 {
 #ifdef MISSIONPACK
     gentity_t* e;
     int i;
 #endif
     gentity_t* body;
     int            contents;
     trap_UnlinkEntity(ent);
     // if client is in a nodrop area, don't leave the body
     contents = trap_PointContents(ent->s.origin, -1);
     if (contents & CONTENTS_NODROP) {
         return;
     }
     // grab a body que and cycle to the next one
     body = level.bodyQue[level.bodyQueIndex];
     level.bodyQueIndex = (level.bodyQueIndex + 1) % BODY_QUEUE_SIZE;
     body->s = ent->s;
     body->s.eFlags = EF_DEAD;        // clear EF_TALK, etc
 #ifdef MISSIONPACK
     if (ent->s.eFlags & EF_KAMIKAZE) {
         body->s.eFlags |= EF_KAMIKAZE;
         // check if there is a kamikaze timer around for this owner
         for (i = 0; i < level.num_entities; i++) {
             e = &g_entities[i];
             if (!e->inuse)
                 continue;
             if (e->activator != ent)
                 continue;
             if (strcmp(e->classname, "kamikaze timer"))
                 continue;
             e->activator = body;
             break;
         }
     }
 #endif
     body->s.powerups = 0;    // clear powerups
     body->s.loopSound = 0;    // clear lava burning
     body->s.number = body - g_entities;
     body->timestamp = level.time;
     body->physicsObject = qtrue;
     body->physicsBounce = 0;        // don't bounce
     if (body->s.groundEntityNum == ENTITYNUM_NONE) {
         body->s.pos.trType = TR_GRAVITY;
         body->s.pos.trTime = level.time;
         VectorCopy(ent->client->ps.velocity, body->s.pos.trDelta);
     } else {
         body->s.pos.trType = TR_STATIONARY;
     }
     body->s.event = 0;
     // change the animation to the last-frame only, so the sequence
     // doesn't repeat anew for the body
     switch (body->s.legsAnim & ~ANIM_TOGGLEBIT) {
     case BOTH_DEATH1:
     case BOTH_DEAD1:
         body->s.torsoAnim = body->s.legsAnim = BOTH_DEAD1;
         break;
     case BOTH_DEATH2:
     case BOTH_DEAD2:
         body->s.torsoAnim = body->s.legsAnim = BOTH_DEAD2;
         break;
     case BOTH_DEATH3:
     case BOTH_DEAD3:
     default:
         body->s.torsoAnim = body->s.legsAnim = BOTH_DEAD3;
         break;
     }
     body->r.svFlags = ent->r.svFlags;
     VectorCopy(ent->r.mins, body->r.mins);
     VectorCopy(ent->r.maxs, body->r.maxs);
     VectorCopy(ent->r.absmin, body->r.absmin);
     VectorCopy(ent->r.absmax, body->r.absmax);
     body->clipmask = CONTENTS_SOLID | CONTENTS_PLAYERCLIP;
     body->r.contents = CONTENTS_CORPSE;
     body->r.ownerNum = ent->s.number;
     body->nextthink = level.time + 5000;
     body->think = BodySink;
     body->die = body_die;
     // don't take more damage if already gibbed
     if (ent->health <= GIB_HEALTH) {
         body->takedamage = qfalse;
     } else {
         body->takedamage = qtrue;
     }
     VectorCopy(body->s.pos.trBase, body->r.currentOrigin);
     trap_LinkEntity(body);
 }
References entityShared_t::absmax, entityShared_t::absmin, gentity_s::activator, ANIM_TOGGLEBIT, body_die(), BODY_QUEUE_SIZE, level_locals_t::bodyQue, level_locals_t::bodyQueIndex, BodySink(), BOTH_DEAD1, BOTH_DEAD2, BOTH_DEAD3, BOTH_DEATH1, BOTH_DEATH2, BOTH_DEATH3, gentity_s::classname, gentity_s::client, gentity_s::clipmask, entityShared_t::contents, CONTENTS_CORPSE, CONTENTS_NODROP, CONTENTS_PLAYERCLIP, CONTENTS_SOLID, entityShared_t::currentOrigin, gentity_s::die, EF_DEAD, EF_KAMIKAZE, entityState_s::eFlags, ENTITYNUM_NONE, entityState_s::event, g_entities, GIB_HEALTH, entityState_s::groundEntityNum, gentity_s::health, gentity_s::inuse, entityState_s::legsAnim, level, entityState_s::loopSound, entityShared_t::maxs, entityShared_t::mins, gentity_s::nextthink, level_locals_t::num_entities, entityState_s::number, entityState_s::origin, entityShared_t::ownerNum, gentity_s::physicsBounce, gentity_s::physicsObject, entityState_s::pos, entityState_s::powerups, gclient_s::ps, qfalse, qtrue, gentity_s::r, gentity_s::s, entityShared_t::svFlags, gentity_s::takedamage, gentity_s::think, level_locals_t::time, gentity_s::timestamp, entityState_s::torsoAnim, TR_GRAVITY, TR_STATIONARY, trap_LinkEntity(), trap_PointContents(), trap_UnlinkEntity(), trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorCopy, and playerState_s::velocity.
Referenced by ClientRespawn(), and SetTeam().
DeathmatchScoreboardMessage()
void DeathmatchScoreboardMessage (gentity_t * ent)
Definition at line 35 of file g_cmds.c.
 {
     char        entry[1024];
     char        string[1000];
     int            stringlength;
     int            i, j;
     gclient_t* cl;
     int            numSorted, scoreFlags, accuracy, perfect;
     // don't send scores to bots, they don't parse it
     if (ent->r.svFlags & SVF_BOT) {
         return;
     }
     // send the latest information on all clients
     string[0] = 0;
     stringlength = 0;
     scoreFlags = 0;
     numSorted = level.numConnectedClients;
     for (i = 0; i < numSorted; i++) {
         int        ping;
         cl = &level.clients[level.sortedClients[i]];
         if (cl->pers.connected == CON_CONNECTING) {
             ping = -1;
         } else {
             ping = cl->ps.ping < 999 ? cl->ps.ping : 999;
         }
         if (cl->accuracy_shots) {
             accuracy = cl->accuracy_hits * 100 / cl->accuracy_shots;
         } else {
             accuracy = 0;
         }
         perfect = (cl->ps.persistant[PERS_RANK] == 0 && cl->ps.persistant[PERS_KILLED] == 0) ? 1 : 0;
         Com_sprintf(entry, sizeof(entry),
             " %i %i %i %i %i %i %i %i %i %i %i %i %i %i", level.sortedClients[i],
             cl->ps.persistant[PERS_SCORE], ping, (level.time - cl->pers.enterTime) / 60000,
             scoreFlags, g_entities[level.sortedClients[i]].s.powerups, accuracy,
             cl->ps.persistant[PERS_IMPRESSIVE_COUNT],
             cl->ps.persistant[PERS_EXCELLENT_COUNT],
             cl->ps.persistant[PERS_GAUNTLET_FRAG_COUNT],
             cl->ps.persistant[PERS_DEFEND_COUNT],
             cl->ps.persistant[PERS_ASSIST_COUNT],
             perfect,
             cl->ps.persistant[PERS_CAPTURES]);
         j = strlen(entry);
         if (stringlength + j >= sizeof(string))
             break;
         strcpy(string + stringlength, entry);
         stringlength += j;
     }
     trap_SendServerCommand(ent - g_entities, va("scores %i %i %i%s", i,
         level.teamScores[TEAM_RED], level.teamScores[TEAM_BLUE],
         string));
 }
References cl, level_locals_t::clients, Com_sprintf(), CON_CONNECTING, g_entities, level, level_locals_t::numConnectedClients, PERS_ASSIST_COUNT, PERS_CAPTURES, PERS_DEFEND_COUNT, PERS_EXCELLENT_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_IMPRESSIVE_COUNT, PERS_KILLED, PERS_RANK, PERS_SCORE, entityState_s::powerups, gentity_s::r, gentity_s::s, level_locals_t::sortedClients, SVF_BOT, entityShared_t::svFlags, TEAM_BLUE, TEAM_RED, level_locals_t::teamScores, level_locals_t::time, trap_SendServerCommand(), and va().
Referenced by Cmd_Score_f(), G_RankRunFrame(), and SendScoreboardMessageToAllClients().
Drop_Item()
gentity_t* Drop_Item (gentity_t * ent, gitem_t * item, float angle)
Definition at line 626 of file g_items.c.
 {
     vec3_t    velocity;
     vec3_t    angles;
     VectorCopy(ent->s.apos.trBase, angles);
     angles[YAW] += angle;
     angles[PITCH] = 0;    // always forward
     AngleVectors(angles, velocity, NULL, NULL);
     VectorScale(velocity, 150, velocity);
     velocity[2] += 200 + crandom() * 50;
     return LaunchItem(item, ent->s.pos.trBase, velocity);
 }
References AngleVectors(), entityState_s::apos, crandom, LaunchItem(), NULL, PITCH, entityState_s::pos, gentity_s::s, trajectory_t::trBase, VectorCopy, VectorScale, and YAW.
Referenced by ClientEvents(), and TossClientItems().
FindIntermissionPoint()
void FindIntermissionPoint (void)
Definition at line 978 of file g_main.c.
 {
     gentity_t* ent, * target;
     vec3_t        dir;
     // find the intermission spot
     ent = G_Find(NULL, FOFS(classname), "info_player_intermission");
     if (!ent) {    // the map creator forgot to put in an intermission point...
         SelectSpawnPoint(vec3_origin, level.intermission_origin, level.intermission_angle, qfalse);
     } else {
         VectorCopy(ent->s.origin, level.intermission_origin);
         VectorCopy(ent->s.angles, level.intermission_angle);
         // if it has a target, look towards it
         if (ent->target) {
             target = G_PickTarget(ent->target);
             if (target) {
                 VectorSubtract(target->s.origin, level.intermission_origin, dir);
                 vectoangles(dir, level.intermission_angle);
             }
         }
     }
 }
References entityState_s::angles, FOFS, G_Find(), G_PickTarget(), level_locals_t::intermission_angle, level_locals_t::intermission_origin, level, NULL, entityState_s::origin, qfalse, gentity_s::s, SelectSpawnPoint(), gentity_s::target, vec3_origin, vectoangles(), VectorCopy, and VectorSubtract.
Referenced by MoveClientToIntermission(), and SelectSpectatorSpawnPoint().
FinishSpawningItem()
void FinishSpawningItem (gentity_t * ent)
Definition at line 665 of file g_items.c.
 {
     trace_t        tr;
     vec3_t        dest;
     VectorSet(ent->r.mins, -ITEM_RADIUS, -ITEM_RADIUS, -ITEM_RADIUS);
     VectorSet(ent->r.maxs, ITEM_RADIUS, ITEM_RADIUS, ITEM_RADIUS);
     ent->s.eType = ET_ITEM;
     ent->s.modelindex = ent->item - bg_itemlist;        // store item number in modelindex
     ent->s.modelindex2 = 0; // zero indicates this isn't a dropped item
     ent->r.contents = CONTENTS_TRIGGER;
     ent->touch = Touch_Item;
     // using an item causes it to respawn
     ent->use = Use_Item;
     if (ent->spawnflags & 1) {
         // suspended
         G_SetOrigin(ent, ent->s.origin);
     } else {
         // drop to floor
         VectorSet(dest, ent->s.origin[0], ent->s.origin[1], ent->s.origin[2] - 4096);
         trap_Trace(&tr, ent->s.origin, ent->r.mins, ent->r.maxs, dest, ent->s.number, MASK_SOLID);
         if (tr.startsolid) {
             G_Printf("FinishSpawningItem: %s startsolid at %s\n", ent->classname, vtos(ent->s.origin));
             G_FreeEntity(ent);
             return;
         }
         // allow to ride movers
         ent->s.groundEntityNum = tr.entityNum;
         G_SetOrigin(ent, tr.endpos);
     }
     // team slaves and targeted items aren't present at start
     if ((ent->flags & FL_TEAMSLAVE) || ent->targetname) {
         ent->s.eFlags |= EF_NODRAW;
         ent->r.contents = 0;
         return;
     }
     // powerups don't spawn in for a while
     if (ent->item->giType == IT_POWERUP) {
         float    respawn;
         respawn = 45 + crandom() * 15;
         ent->s.eFlags |= EF_NODRAW;
         ent->r.contents = 0;
         ent->nextthink = level.time + respawn * 1000;
         ent->think = RespawnItem;
         return;
     }
     trap_LinkEntity(ent);
 }
References bg_itemlist, gentity_s::classname, entityShared_t::contents, CONTENTS_TRIGGER, crandom, EF_NODRAW, entityState_s::eFlags, ET_ITEM, entityState_s::eType, FL_TEAMSLAVE, gentity_s::flags, G_FreeEntity(), G_Printf(), G_SetOrigin(), gitem_s::giType, entityState_s::groundEntityNum, IT_POWERUP, gentity_s::item, ITEM_RADIUS, level, MASK_SOLID, entityShared_t::maxs, entityShared_t::mins, entityState_s::modelindex, entityState_s::modelindex2, gentity_s::nextthink, entityState_s::number, entityState_s::origin, gentity_s::r, RespawnItem(), gentity_s::s, gentity_s::spawnflags, gentity_s::targetname, gentity_s::think, level_locals_t::time, gentity_s::touch, Touch_Item(), tr, trap_LinkEntity(), trap_Trace(), gentity_s::use, Use_Item(), VectorSet, and vtos().
Referenced by Cmd_Give_f(), and G_SpawnItem().
fire_bfg()
gentity_t* fire_bfg (gentity_t * self, vec3_t start, vec3_t dir)
Definition at line 614 of file g_missile.c.
 {
     gentity_t* bolt;
     VectorNormalize(dir);
     bolt = G_Spawn();
     bolt->classname = "bfg";
     bolt->nextthink = level.time + 10000;
     bolt->think = G_ExplodeMissile;
     bolt->s.eType = ET_MISSILE;
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     bolt->s.weapon = WP_BFG;
     bolt->r.ownerNum = self->s.number;
     bolt->parent = self;
     bolt->damage = 100;
     bolt->splashDamage = 100;
     bolt->splashRadius = 120;
     bolt->methodOfDeath = MOD_BFG;
     bolt->splashMethodOfDeath = MOD_BFG_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_LINEAR;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;        // move a bit on the very first frame
     VectorCopy(start, bolt->s.pos.trBase);
     VectorScale(dir, 2000, bolt->s.pos.trDelta);
     SnapVector(bolt->s.pos.trDelta);            // save net bandwidth
     VectorCopy(start, bolt->r.currentOrigin);
     return bolt;
 }
References gentity_s::classname, gentity_s::clipmask, entityShared_t::currentOrigin, gentity_s::damage, ET_MISSILE, entityState_s::eType, G_ExplodeMissile(), G_Spawn(), level, MASK_SHOT, gentity_s::methodOfDeath, MISSILE_PRESTEP_TIME, MOD_BFG, MOD_BFG_SPLASH, gentity_s::nextthink, NULL, entityShared_t::ownerNum, gentity_s::parent, entityState_s::pos, gentity_s::r, gentity_s::s, SnapVector, gentity_s::splashDamage, gentity_s::splashMethodOfDeath, gentity_s::splashRadius, SVF_USE_CURRENT_ORIGIN, entityShared_t::svFlags, gentity_s::target_ent, gentity_s::think, level_locals_t::time, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorCopy, VectorNormalize(), VectorScale, entityState_s::weapon, and WP_BFG.
Referenced by BFG_Fire().
fire_grapple()
gentity_t* fire_grapple (gentity_t * self, vec3_t start, vec3_t dir)
Definition at line 702 of file g_missile.c.
 {
     gentity_t* hook;
     VectorNormalize(dir);
     hook = G_Spawn();
     hook->classname = "hook";
     hook->nextthink = level.time + 10000;
     hook->think = Weapon_HookFree;
     hook->s.eType = ET_MISSILE;
     hook->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     hook->s.weapon = WP_GRAPPLING_HOOK;
     hook->r.ownerNum = self->s.number;
     hook->methodOfDeath = MOD_GRAPPLE;
     hook->clipmask = MASK_SHOT;
     hook->parent = self;
     hook->target_ent = NULL;
     hook->s.pos.trType = TR_LINEAR;
     hook->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;        // move a bit on the very first frame
     hook->s.otherEntityNum = self->s.number; // use to match beam in client
     VectorCopy(start, hook->s.pos.trBase);
     VectorScale(dir, 800, hook->s.pos.trDelta);
     SnapVector(hook->s.pos.trDelta);            // save net bandwidth
     VectorCopy(start, hook->r.currentOrigin);
     self->client->hook = hook;
     return hook;
 }
References gentity_s::classname, gentity_s::clipmask, entityShared_t::currentOrigin, ET_MISSILE, entityState_s::eType, G_Spawn(), level, MASK_SHOT, gentity_s::methodOfDeath, MISSILE_PRESTEP_TIME, MOD_GRAPPLE, gentity_s::nextthink, NULL, entityState_s::otherEntityNum, entityShared_t::ownerNum, gentity_s::parent, entityState_s::pos, gentity_s::r, gentity_s::s, SnapVector, SVF_USE_CURRENT_ORIGIN, entityShared_t::svFlags, gentity_s::target_ent, gentity_s::think, level_locals_t::time, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorCopy, VectorNormalize(), VectorScale, entityState_s::weapon, Weapon_HookFree(), and WP_GRAPPLING_HOOK.
Referenced by Weapon_GrapplingHook_Fire().
fire_grenade()
gentity_t* fire_grenade (gentity_t * self, vec3_t start, vec3_t aimdir)
Definition at line 571 of file g_missile.c.
 {
     gentity_t* bolt;
     VectorNormalize(dir);
     bolt = G_Spawn();
     bolt->classname = "grenade";
     bolt->nextthink = level.time + 2500;
     bolt->think = G_ExplodeMissile;
     bolt->s.eType = ET_MISSILE;
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     bolt->s.weapon = WP_GRENADE_LAUNCHER;
     bolt->s.eFlags = EF_BOUNCE_HALF;
     bolt->r.ownerNum = self->s.number;
     bolt->parent = self;
     bolt->damage = 100;
     bolt->splashDamage = 100;
     bolt->splashRadius = 150;
     bolt->methodOfDeath = MOD_GRENADE;
     bolt->splashMethodOfDeath = MOD_GRENADE_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_GRAVITY;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;        // move a bit on the very first frame
     VectorCopy(start, bolt->s.pos.trBase);
     VectorScale(dir, 700, bolt->s.pos.trDelta);
     SnapVector(bolt->s.pos.trDelta);            // save net bandwidth
     VectorCopy(start, bolt->r.currentOrigin);
     return bolt;
 }
References gentity_s::classname, gentity_s::clipmask, entityShared_t::currentOrigin, gentity_s::damage, EF_BOUNCE_HALF, entityState_s::eFlags, ET_MISSILE, entityState_s::eType, G_ExplodeMissile(), G_Spawn(), level, MASK_SHOT, gentity_s::methodOfDeath, MISSILE_PRESTEP_TIME, MOD_GRENADE, MOD_GRENADE_SPLASH, gentity_s::nextthink, NULL, entityShared_t::ownerNum, gentity_s::parent, entityState_s::pos, gentity_s::r, gentity_s::s, SnapVector, gentity_s::splashDamage, gentity_s::splashMethodOfDeath, gentity_s::splashRadius, SVF_USE_CURRENT_ORIGIN, entityShared_t::svFlags, gentity_s::target_ent, gentity_s::think, level_locals_t::time, TR_GRAVITY, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorCopy, VectorNormalize(), VectorScale, entityState_s::weapon, and WP_GRENADE_LAUNCHER.
Referenced by Use_Shooter(), and weapon_grenadelauncher_fire().
fire_plasma()
gentity_t* fire_plasma (gentity_t * self, vec3_t start, vec3_t aimdir)
Definition at line 529 of file g_missile.c.
 {
     gentity_t* bolt;
     VectorNormalize(dir);
     bolt = G_Spawn();
     bolt->classname = "plasma";
     bolt->nextthink = level.time + 10000;
     bolt->think = G_ExplodeMissile;
     bolt->s.eType = ET_MISSILE;
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;
     bolt->s.weapon = WP_PLASMAGUN;
     bolt->r.ownerNum = self->s.number;
     bolt->parent = self;
     bolt->damage = 20;
     bolt->splashDamage = 15;
     bolt->splashRadius = 20;
     bolt->methodOfDeath = MOD_PLASMA;
     bolt->splashMethodOfDeath = MOD_PLASMA_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_LINEAR;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME;        // move a bit on the very first frame
     VectorCopy(start, bolt->s.pos.trBase);
     VectorScale(dir, 2000, bolt->s.pos.trDelta);
     SnapVector(bolt->s.pos.trDelta);            // save net bandwidth
     VectorCopy(start, bolt->r.currentOrigin);
     return bolt;
 }
References gentity_s::classname, gentity_s::clipmask, entityShared_t::currentOrigin, gentity_s::damage, ET_MISSILE, entityState_s::eType, G_ExplodeMissile(), G_Spawn(), level, MASK_SHOT, gentity_s::methodOfDeath, MISSILE_PRESTEP_TIME, MOD_PLASMA, MOD_PLASMA_SPLASH, gentity_s::nextthink, NULL, entityShared_t::ownerNum, gentity_s::parent, entityState_s::pos, gentity_s::r, gentity_s::s, SnapVector, gentity_s::splashDamage, gentity_s::splashMethodOfDeath, gentity_s::splashRadius, SVF_USE_CURRENT_ORIGIN, entityShared_t::svFlags, gentity_s::target_ent, gentity_s::think, level_locals_t::time, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorCopy, VectorNormalize(), VectorScale, entityState_s::weapon, and WP_PLASMAGUN.
Referenced by Use_Shooter(), and Weapon_Plasmagun_Fire().
fire_rocket()
gentity_t* fire_rocket (gentity_t * self, vec3_t start, vec3_t dir)
This function is responsible for creating an entity and defining it as a rocket (also called a missile).
Parameters
[in] self The parent entity (owner).
[in] start A starting location.
[in] dir A direction to face.
Returns
The spawned entity.
Definition at line 663 of file g_missile.c.
 {
     gentity_t* bolt;
     VectorNormalize(dir);
     bolt = G_Spawn();                        // Either finds a free entity or creates one.
     bolt->classname = "rocket";
     bolt->nextthink = level.time + 15000;    // Set the time until the next think period.
     bolt->think = G_ExplodeMissile;          // Specifies which think function will be called.
     bolt->s.eType = ET_MISSILE;              // Type of bolt.
     bolt->r.svFlags = SVF_USE_CURRENT_ORIGIN;// Link position.
     bolt->s.weapon = WP_ROCKET_LAUNCHER;     // The weapon it was fired from.
     bolt->r.ownerNum = self->s.number;       // Its owner.
     bolt->parent = self;
     bolt->damage = 100;
     bolt->splashDamage = 100;                       // Indirect damage.
     bolt->splashRadius = 120;
     bolt->methodOfDeath = MOD_ROCKET;
     bolt->splashMethodOfDeath = MOD_ROCKET_SPLASH;
     bolt->clipmask = MASK_SHOT;
     bolt->target_ent = NULL;
     bolt->s.pos.trType = TR_LINEAR;
     bolt->s.pos.trTime = level.time - MISSILE_PRESTEP_TIME; // move a bit on the very first frame
     VectorCopy(start, bolt->s.pos.trBase);
     VectorScale(dir, 900, bolt->s.pos.trDelta);           // Fired at 900 units/sec.
     SnapVector(bolt->s.pos.trDelta);                      // save net bandwidth
     VectorCopy(start, bolt->r.currentOrigin);
     return bolt;
 }
References gentity_s::classname, gentity_s::clipmask, entityShared_t::currentOrigin, gentity_s::damage, ET_MISSILE, entityState_s::eType, G_ExplodeMissile(), G_Spawn(), level, MASK_SHOT, gentity_s::methodOfDeath, MISSILE_PRESTEP_TIME, MOD_ROCKET, MOD_ROCKET_SPLASH, gentity_s::nextthink, NULL, entityShared_t::ownerNum, gentity_s::parent, entityState_s::pos, gentity_s::r, gentity_s::s, SnapVector, gentity_s::splashDamage, gentity_s::splashMethodOfDeath, gentity_s::splashRadius, SVF_USE_CURRENT_ORIGIN, entityShared_t::svFlags, gentity_s::target_ent, gentity_s::think, level_locals_t::time, TR_LINEAR, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorCopy, VectorNormalize(), VectorScale, entityState_s::weapon, and WP_ROCKET_LAUNCHER.
Referenced by Use_Shooter(), and Weapon_RocketLauncher_Fire().
FireWeapon()
void FireWeapon (gentity_t * ent)
Definition at line 831 of file g_weapon.c.
 {
     if (ent->client->ps.powerups[PW_QUAD]) {
         s_quadFactor = g_quadfactor.value;
     } else {
         s_quadFactor = 1;
     }
 #ifdef MISSIONPACK
     if (ent->client->persistantPowerup && ent->client->persistantPowerup->item && ent->client->persistantPowerup->item->giTag == PW_DOUBLER) {
         s_quadFactor *= 2;
     }
 #endif
     // track shots taken for accuracy tracking.  Grapple is not a weapon and gauntet is just not tracked
     if (ent->s.weapon != WP_GRAPPLING_HOOK && ent->s.weapon != WP_GAUNTLET) {
 #ifdef MISSIONPACK
         if (ent->s.weapon == WP_NAILGUN) {
             ent->client->accuracy_shots += NUM_NAILSHOTS;
         } else {
             ent->client->accuracy_shots++;
         }
 #else
         ent->client->accuracy_shots++;
 #endif
     }
     // set aiming directions
     AngleVectors(ent->client->ps.viewangles, forward, right, up);
     CalcMuzzlePointOrigin(ent, ent->client->oldOrigin, forward, right, up, muzzle);
     // fire the specific weapon
     switch (ent->s.weapon) {
     case WP_GAUNTLET:
         Weapon_Gauntlet(ent);
         break;
     case WP_LIGHTNING:
         Weapon_LightningFire(ent);
         break;
     case WP_SHOTGUN:
         weapon_supershotgun_fire(ent);
         break;
     case WP_MACHINEGUN:
         if (g_gametype.integer != GT_TEAM) {
             Bullet_Fire(ent, MACHINEGUN_SPREAD, MACHINEGUN_DAMAGE, MOD_MACHINEGUN);
         } else {
             Bullet_Fire(ent, MACHINEGUN_SPREAD, MACHINEGUN_TEAM_DAMAGE, MOD_MACHINEGUN);
         }
         break;
     case WP_GRENADE_LAUNCHER:
         weapon_grenadelauncher_fire(ent);
         break;
     case WP_ROCKET_LAUNCHER:
         Weapon_RocketLauncher_Fire(ent);
         break;
     case WP_PLASMAGUN:
         Weapon_Plasmagun_Fire(ent);
         break;
     case WP_RAILGUN:
         weapon_railgun_fire(ent);
         break;
     case WP_BFG:
         BFG_Fire(ent);
         break;
     case WP_GRAPPLING_HOOK:
         Weapon_GrapplingHook_Fire(ent);
         break;
 #ifdef MISSIONPACK
     case WP_NAILGUN:
         Weapon_Nailgun_Fire(ent);
         break;
     case WP_PROX_LAUNCHER:
         weapon_proxlauncher_fire(ent);
         break;
     case WP_CHAINGUN:
         Bullet_Fire(ent, CHAINGUN_SPREAD, CHAINGUN_DAMAGE, MOD_CHAINGUN);
         break;
 #endif
     default:
         // FIXME        G_Error( "Bad ent->s.weapon" );
         break;
     }
 }
References gclient_s::accuracy_shots, AngleVectors(), BFG_Fire(), Bullet_Fire(), CalcMuzzlePointOrigin(), gentity_s::client, forward, g_gametype, g_quadfactor, GT_TEAM, MACHINEGUN_DAMAGE, MACHINEGUN_SPREAD, MACHINEGUN_TEAM_DAMAGE, MOD_MACHINEGUN, muzzle, NUM_NAILSHOTS, gclient_s::oldOrigin, playerState_s::powerups, gclient_s::ps, PW_DOUBLER, PW_QUAD, right, gentity_s::s, s_quadFactor, up, vmCvar_t::value, playerState_s::viewangles, entityState_s::weapon, Weapon_Gauntlet(), Weapon_GrapplingHook_Fire(), weapon_grenadelauncher_fire(), Weapon_LightningFire(), Weapon_Plasmagun_Fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_supershotgun_fire(), WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by ClientEvents().
format()
void QDECL void QDECL format (printf , 1 , 2)
G_AddEvent()
void G_AddEvent (gentity_t * ent, int event, int eventParm)
Definition at line 593 of file g_utils.c.
 {
     int        bits;
     if (!event) {
         G_Printf("G_AddEvent: zero event added for entity %i\n", ent->s.number);
         return;
     }
     // clients need to add the event in playerState_t instead of entityState_t
     if (ent->client) {
         bits = ent->client->ps.externalEvent & EV_EVENT_BITS;
         bits = (bits + EV_EVENT_BIT1) & EV_EVENT_BITS;
         ent->client->ps.externalEvent = event | bits;
         ent->client->ps.externalEventParm = eventParm;
         ent->client->ps.externalEventTime = level.time;
     } else {
         bits = ent->s.event & EV_EVENT_BITS;
         bits = (bits + EV_EVENT_BIT1) & EV_EVENT_BITS;
         ent->s.event = event | bits;
         ent->s.eventParm = eventParm;
     }
     ent->eventTime = level.time;
 }
References bits(), gentity_s::client, EV_EVENT_BIT1, EV_EVENT_BITS, entityState_s::event, entityState_s::eventParm, gentity_s::eventTime, playerState_s::externalEvent, playerState_s::externalEventParm, playerState_s::externalEventTime, G_Printf(), level, entityState_s::number, gclient_s::ps, gentity_s::s, and level_locals_t::time.
Referenced by CelebrateStart(), CheckGauntletAttack(), ClientTimerActions(), G_Damage(), G_ExplodeMissile(), G_MissileImpact(), G_MoverPush(), GibEntity(), P_DamageFeedback(), P_WorldEffects(), player_die(), Reached_BinaryMover(), RespawnItem(), ReturnToPos1(), Touch_Item(), Use_BinaryMover(), Use_Shooter(), and Use_Target_Speaker().
G_AddPredictableEvent()
void G_AddPredictableEvent (gentity_t * ent, int event, int eventParm)
Definition at line 577 of file g_utils.c.
 {
     if (!ent->client) {
         return;
     }
     BG_AddPredictableEventToPlayerstate(event, eventParm, &ent->client->ps);
 }
References BG_AddPredictableEventToPlayerstate(), gentity_s::client, and gclient_s::ps.
Referenced by Touch_Item().
G_Alloc()
void* G_Alloc (int size)
Definition at line 36 of file g_mem.c.
 {
     char* p;
     if (g_debugAlloc.integer) {
         G_Printf("G_Alloc of %i bytes (%i left)\n", size, POOLSIZE - allocPoint - ((size + 31) & ~31));
     }
     if (allocPoint + size > POOLSIZE) {
         G_Error("G_Alloc: failed on allocation of %i bytes", size);
         return NULL;
     }
     p = &memoryPool[allocPoint];
     allocPoint += (size + 31) & ~31;
     return p;
 }
References allocPoint, g_debugAlloc, G_Error(), G_Printf(), vmCvar_t::integer, memoryPool, NULL, and POOLSIZE.
Referenced by BotAISetupClient(), G_NewString(), and G_ParseInfos().
G_BotConnect()
qboolean G_BotConnect (int clientNum, qboolean restart)
Definition at line 572 of file g_bot.c.
 {
     bot_settings_t    settings;
     char            userinfo[MAX_INFO_STRING];
     trap_GetUserinfo(clientNum, userinfo, sizeof(userinfo));
     Q_strncpyz(settings.characterfile, Info_ValueForKey(userinfo, "characterfile"), sizeof(settings.characterfile));
     settings.skill = atof(Info_ValueForKey(userinfo, "skill"));
     if (!BotAISetupClient(clientNum, &settings, restart)) {
         trap_DropClient(clientNum, "BotAISetupClient failed");
         return qfalse;
     }
     return qtrue;
 }
References BotAISetupClient(), bot_settings_s::characterfile, Info_ValueForKey(), MAX_INFO_STRING, Q_strncpyz(), qfalse, qtrue, bot_settings_s::skill, trap_DropClient(), and trap_GetUserinfo().
Referenced by ClientConnect().
G_CheckBotSpawn()
void G_CheckBotSpawn (void)
Definition at line 499 of file g_bot.c.
 {
     int        n;
     char    userinfo[MAX_INFO_VALUE];
     G_CheckMinimumPlayers();
     for (n = 0; n < BOT_SPAWN_QUEUE_DEPTH; n++) {
         if (!botSpawnQueue[n].spawnTime) {
             continue;
         }
         if (botSpawnQueue[n].spawnTime > level.time) {
             continue;
         }
         ClientBegin(botSpawnQueue[n].clientNum);
         botSpawnQueue[n].spawnTime = 0;
         if (g_gametype.integer == GT_SINGLE_PLAYER) {
             trap_GetUserinfo(botSpawnQueue[n].clientNum, userinfo, sizeof(userinfo));
             PlayerIntroSound(Info_ValueForKey(userinfo, "model"));
         }
     }
 }
References BOT_SPAWN_QUEUE_DEPTH, botSpawnQueue, ClientBegin(), G_CheckMinimumPlayers(), g_gametype, GT_SINGLE_PLAYER, Info_ValueForKey(), level, MAX_INFO_VALUE, PlayerIntroSound(), botSpawnQueue_t::spawnTime, level_locals_t::time, and trap_GetUserinfo().
Referenced by BotAIStartFrame().
G_CheckTeamItems()
void G_CheckTeamItems (void)
Check team items.
Definition at line 730 of file g_items.c.
 {
     // Set up team stuff
     Team_InitGame();
     if (g_gametype.integer == GT_CTF) {
         gitem_t* item;
         // check for the two flags
         item = BG_FindItem("Red Flag");
         if (!item || !itemRegistered[item - bg_itemlist])
             G_Printf(S_COLOR_YELLOW "WARNING: No team_CTF_redflag in map\n");
         item = BG_FindItem("Blue Flag");
         if (!item || !itemRegistered[item - bg_itemlist])
             G_Printf(S_COLOR_YELLOW "WARNING: No team_CTF_blueflag in map\n");
     }
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         gitem_t* item;
         // check for all three flags
         item = BG_FindItem("Red Flag");
         if (!item || !itemRegistered[item - bg_itemlist])
             G_Printf(S_COLOR_YELLOW "WARNING: No team_CTF_redflag in map\n");
         item = BG_FindItem("Blue Flag");
         if (!item || !itemRegistered[item - bg_itemlist])
             G_Printf(S_COLOR_YELLOW "WARNING: No team_CTF_blueflag in map\n");
         item = BG_FindItem("Neutral Flag");
         if (!item || !itemRegistered[item - bg_itemlist])
             G_Printf(S_COLOR_YELLOW "WARNING: No team_CTF_neutralflag in map\n");
     }
     if (g_gametype.integer == GT_OBELISK) {
         gentity_t* ent;
         // check for the two obelisks
         ent = NULL;
         ent = G_Find(ent, FOFS(classname), "team_redobelisk");
         if (!ent)
             G_Printf(S_COLOR_YELLOW "WARNING: No team_redobelisk in map\n");
         ent = NULL;
         ent = G_Find(ent, FOFS(classname), "team_blueobelisk");
         if (!ent)
             G_Printf(S_COLOR_YELLOW "WARNING: No team_blueobelisk in map\n");
     }
     if (g_gametype.integer == GT_HARVESTER) {
         gentity_t* ent;
         // check for all three obelisks
         ent = NULL;
         ent = G_Find(ent, FOFS(classname), "team_redobelisk");
         if (!ent)
             G_Printf(S_COLOR_YELLOW "WARNING: No team_redobelisk in map\n");
         ent = NULL;
         ent = G_Find(ent, FOFS(classname), "team_blueobelisk");
         if (!ent)
             G_Printf(S_COLOR_YELLOW "WARNING: No team_blueobelisk in map\n");
         ent = NULL;
         ent = G_Find(ent, FOFS(classname), "team_neutralobelisk");
         if (!ent)
             G_Printf(S_COLOR_YELLOW "WARNING: No team_neutralobelisk in map\n");
     }
 #endif
 }
References BG_FindItem(), bg_itemlist, FOFS, G_Find(), g_gametype, G_Printf(), GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, itemRegistered, NULL, S_COLOR_YELLOW, and Team_InitGame().
Referenced by G_InitGame().
G_Damage()
void G_Damage (gentity_t * targ, gentity_t * inflictor, gentity_t * attacker, vec3_t dir, vec3_t point, int damage, int dflags, int mod)
The damage is dealt out, if all signs indicate that the bullet hit a surface that can be damaged.
Parameters
targ The entity in the game that will receive the damage.
inflictor The entity that caused the damage, in a literal sense. This could be a bullet, a grenade, a rocket, and so on.
attacker The entity that caused the inflictor to do damage. An example is the player who fired the shotgun.
dir This is the direction of knock back for the target. Some items cause so much damage that the target may be thrown back from the blow.
point This is the point of actual contact where the damage is done. This is a good reference point in case you want to look for damage in specific areas on the target, such as a headshot.
damage The total amount of damage being dealt to the target.
dflags Some types of damage can be specialized or flagged to behave differently within Q3. This is where the damage flags are passed in. An example of available dflags is DAMAGE_NO_ARMOR: the damage ignores players armor.
mod These are flags that tell the function what will be considered the means of death in case it is to be determined at a later point. (For example, if you want to track a certain weapons usage and effectiveness).
Definition at line 832 of file g_combat.c.
 {
     gclient_t* client;
     int            take;
     int            asave;
     int            knockback;
     int            max;
 #ifdef MISSIONPACK
     vec3_t        bouncedir, impactpoint;
 #endif
     if (!targ->takedamage) {
         return;
     }
     // the intermission has already been qualified for, so don't
     // allow any extra scoring
     if (level.intermissionQueued) {
         return;
     }
 #ifdef MISSIONPACK
     if (targ->client && mod != MOD_JUICED) {
         if (targ->client->invulnerabilityTime > level.time) {
             if (dir && point) {
                 G_InvulnerabilityEffect(targ, dir, point, impactpoint, bouncedir);
             }
             return;
         }
     }
 #endif
     if (!inflictor) {
         inflictor = &g_entities[ENTITYNUM_WORLD];
     }
     if (!attacker) {
         attacker = &g_entities[ENTITYNUM_WORLD];
     }
     // shootable doors / buttons don't actually have any health
     if (targ->s.eType == ET_MOVER) {
         if (targ->use && targ->moverState == MOVER_POS1) {
             targ->use(targ, inflictor, attacker);
         }
         return;
     }
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_OBELISK && CheckObeliskAttack(targ, attacker)) {
         return;
     }
 #endif
     // reduce damage by the attacker's handicap value
     // unless they are rocket jumping
     if (attacker->client && attacker != targ) {
         max = attacker->client->ps.stats[STAT_MAX_HEALTH];
 #ifdef MISSIONPACK
         if (bg_itemlist[attacker->client->ps.stats[STAT_PERSISTANT_POWERUP]].giTag == PW_GUARD) {
             max /= 2;
         }
 #endif
         damage = damage * max / 100;
     }
     client = targ->client;
     if (client) {
         if (client->noclip) {
             return;
         }
     }
     if (!dir) {
         dflags |= DAMAGE_NO_KNOCKBACK;
     } else {
         VectorNormalize(dir);
     }
     knockback = damage;
     if (knockback > 200) {
         knockback = 200;
     }
     if (targ->flags & FL_NO_KNOCKBACK) {
         knockback = 0;
     }
     if (dflags & DAMAGE_NO_KNOCKBACK) {
         knockback = 0;
     }
     // figure momentum add, even if the damage won't be taken
     if (knockback && targ->client) {
         vec3_t    kvel;
         float    mass;
         mass = 200;
         VectorScale(dir, g_knockback.value * (float)knockback / mass, kvel);
         VectorAdd(targ->client->ps.velocity, kvel, targ->client->ps.velocity);
         // set the timer so that the other client can't cancel
         // out the movement immediately
         if (!targ->client->ps.pm_time) {
             int        t;
             t = knockback * 2;
             if (t < 50) {
                 t = 50;
             }
             if (t > 200) {
                 t = 200;
             }
             targ->client->ps.pm_time = t;
             targ->client->ps.pm_flags |= PMF_TIME_KNOCKBACK;
         }
     }
     // check for completely getting out of the damage
     if (!(dflags & DAMAGE_NO_PROTECTION)) {
         // if TF_NO_FRIENDLY_FIRE is set, don't do damage to the target
         // if the attacker was on the same team
 #ifdef MISSIONPACK
         if (mod != MOD_JUICED && targ != attacker && !(dflags & DAMAGE_NO_TEAM_PROTECTION) && OnSameTeam(targ, attacker)) {
 #else
         if (targ != attacker && OnSameTeam(targ, attacker)) {
 #endif
             if (!g_friendlyFire.integer) {
                 return;
             }
         }
 #ifdef MISSIONPACK
         if (mod == MOD_PROXIMITY_MINE) {
             if (inflictor && inflictor->parent && OnSameTeam(targ, inflictor->parent)) {
                 return;
             }
             if (targ == attacker) {
                 return;
             }
         }
 #endif
         // check for godmode
         if (targ->flags & FL_GODMODE) {
             return;
         }
     }
     // battlesuit protects from all radius damage (but takes knockback)
     // and protects 50% against all damage
     if (client && client->ps.powerups[PW_BATTLESUIT]) {
         G_AddEvent(targ, EV_POWERUP_BATTLESUIT, 0);
         if ((dflags & DAMAGE_RADIUS) || (mod == MOD_FALLING)) {
             return;
         }
         damage *= 0.5;
     }
     // add to the attacker's hit counter (if the target isn't a general entity like a prox mine)
     if (attacker->client && client
         && targ != attacker && targ->health > 0
         && targ->s.eType != ET_MISSILE
         && targ->s.eType != ET_GENERAL) {
         if (OnSameTeam(targ, attacker)) {
             attacker->client->ps.persistant[PERS_HITS]--;
         } else {
             attacker->client->ps.persistant[PERS_HITS]++;
         }
         attacker->client->ps.persistant[PERS_ATTACKEE_ARMOR] = (targ->health << 8) | (client->ps.stats[STAT_ARMOR]);
     }
     // always give half damage if hurting self
     // calculated after knockback, so rocket jumping works
     if (targ == attacker) {
         damage *= 0.5;
     }
     if (damage < 1) {
         damage = 1;
     }
     take = damage;
     // save some from armor
     asave = CheckArmor(targ, take, dflags);
     take -= asave;
     if (g_debugDamage.integer) {
         G_Printf("%i: client:%i health:%i damage:%i armor:%i\n", level.time, targ->s.number,
             targ->health, take, asave);
     }
     // add to the damage inflicted on a player this frame
     // the total will be turned into screen blends and view angle kicks
     // at the end of the frame
     if (client) {
         if (attacker) {
             client->ps.persistant[PERS_ATTACKER] = attacker->s.number;
         } else {
             client->ps.persistant[PERS_ATTACKER] = ENTITYNUM_WORLD;
         }
         client->damage_armor += asave;
         client->damage_blood += take;
         client->damage_knockback += knockback;
         if (dir) {
             VectorCopy(dir, client->damage_from);
             client->damage_fromWorld = qfalse;
         } else {
             VectorCopy(targ->r.currentOrigin, client->damage_from);
             client->damage_fromWorld = qtrue;
         }
     }
     // See if it's the player hurting the emeny flag carrier
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_CTF || g_gametype.integer == GT_1FCTF) {
 #else
     if (g_gametype.integer == GT_CTF) {
 #endif
         Team_CheckHurtCarrier(targ, attacker);
     }
     if (targ->client) {
         // set the last client who damaged the target
         targ->client->lasthurt_client = attacker->s.number;
         targ->client->lasthurt_mod = mod;
     }
     // do the damage
     if (take) {
         targ->health = targ->health - take;
         if (targ->client) {
             targ->client->ps.stats[STAT_HEALTH] = targ->health;
         }
         if (targ->health <= 0) {
             if (client)
                 targ->flags |= FL_NO_KNOCKBACK;
             if (targ->health < -999)
                 targ->health = -999;
             targ->enemy = attacker;
             targ->die(targ, inflictor, attacker, take, mod);
             return;
         } else if (targ->pain) {
             targ->pain(targ, attacker, take);
         }
     }
 }
References bg_itemlist, CheckArmor(), CheckObeliskAttack(), gentity_s::client, entityShared_t::currentOrigin, gclient_s::damage_armor, gclient_s::damage_blood, gclient_s::damage_from, gclient_s::damage_fromWorld, gclient_s::damage_knockback, DAMAGE_NO_KNOCKBACK, DAMAGE_NO_PROTECTION, DAMAGE_RADIUS, gentity_s::die, gentity_s::enemy, ENTITYNUM_WORLD, ET_GENERAL, ET_MISSILE, ET_MOVER, entityState_s::eType, EV_POWERUP_BATTLESUIT, FL_GODMODE, FL_NO_KNOCKBACK, gentity_s::flags, G_AddEvent(), g_debugDamage, g_entities, g_friendlyFire, g_gametype, G_InvulnerabilityEffect(), g_knockback, G_Printf(), gitem_s::giTag, GT_1FCTF, GT_CTF, GT_OBELISK, gentity_s::health, vmCvar_t::integer, level_locals_t::intermissionQueued, gclient_s::lasthurt_client, gclient_s::lasthurt_mod, level, MOD_FALLING, MOVER_POS1, gentity_s::moverState, gclient_s::noclip, entityState_s::number, OnSameTeam(), gentity_s::pain, gentity_s::parent, PERS_ATTACKEE_ARMOR, PERS_ATTACKER, PERS_HITS, playerState_s::persistant, playerState_s::pm_flags, playerState_s::pm_time, PMF_TIME_KNOCKBACK, playerState_s::powerups, gclient_s::ps, PW_BATTLESUIT, PW_GUARD, qfalse, qtrue, gentity_s::r, gentity_s::s, STAT_ARMOR, STAT_HEALTH, STAT_MAX_HEALTH, playerState_s::stats, t, gentity_s::takedamage, Team_CheckHurtCarrier(), level_locals_t::time, gentity_s::use, vmCvar_t::value, VectorAdd, VectorCopy, VectorNormalize(), VectorScale, and playerState_s::velocity.
Referenced by Blocked_Door(), Bullet_Fire(), CheckGauntletAttack(), ClientEvents(), G_KillBox(), G_MissileImpact(), G_MoverPush(), G_RadiusDamage(), hurt_touch(), P_WorldEffects(), ShotgunPellet(), target_kill_use(), target_laser_think(), Weapon_LightningFire(), and weapon_railgun_fire().
G_EntitiesFree()
qboolean G_EntitiesFree (void)
Definition at line 449 of file g_utils.c.
 {
     int            i;
     gentity_t* e;
     if (level.num_entities < ENTITYNUM_MAX_NORMAL) {
         // can open a new slot if needed
         return qtrue;
     }
     e = &g_entities[MAX_CLIENTS];
     for (i = MAX_CLIENTS; i < level.num_entities; i++, e++) {
         if (e->inuse) {
             continue;
         }
         // slot available
         return qtrue;
     }
     return qfalse;
 }
References ENTITYNUM_MAX_NORMAL, g_entities, gentity_s::inuse, level, MAX_CLIENTS, level_locals_t::num_entities, qfalse, and qtrue.
G_Error()
void QDECL void QDECL G_Error (const char * fmt, ...)
Referenced by __attribute__(), BotAI_Print(), Cmd_FollowCycle_f(), G_AddSpawnVarToken(), G_Alloc(), G_FindConfigstringIndex(), G_ParseSpawnVars(), G_Spawn(), G_SpawnEntitiesFromString(), G_TryPushingEntity(), Reached_BinaryMover(), RegisterItem(), RespawnItem(), SelectRandomFurthestSpawnPoint(), SP_target_speaker(), and SP_worldspawn().
G_FilterPacket()
qboolean G_FilterPacket (char * from)
Definition at line 167 of file g_svcmds.c.
 {
     int        i;
     unsigned    in;
     byte m[4] = { 0 };
     char* p;
     i = 0;
     p = from;
     while (*p && i < 4) {
         m[i] = 0;
         while (*p >= '0' && *p <= '9') {
             m[i] = m[i] * 10 + (*p - '0');
             p++;
         }
         if (!*p || *p == ':')
             break;
         i++, p++;
     }
     in = *(unsigned*)m;
     for (i = 0; i < numIPFilters; i++)
         if ((in & ipFilters[i].mask) == ipFilters[i].compare)
             return g_filterBan.integer != 0;
     return g_filterBan.integer == 0;
 }
References ipFilter_s::compare, g_filterBan, in, vmCvar_t::integer, ipFilters, m, and numIPFilters.
Referenced by ClientConnect().
G_Find()
gentity_t* G_Find (gentity_t * from, int fieldofs, const char * match)
Definition at line 165 of file g_utils.c.
 {
     char* s;
     if (!from)
         from = g_entities;
     else
         from++;
     for (; from < &g_entities[level.num_entities]; from++) {
         if (!from->inuse)
             continue;
         s = *(char**)((byte*)from + fieldofs);
         if (!s)
             continue;
         if (!Q_stricmp(s, match))
             return from;
     }
     return NULL;
 }
References g_entities, gentity_s::inuse, level, NULL, level_locals_t::num_entities, Q_stricmp(), and s.
Referenced by CheckAlmostCapture(), CheckAlmostScored(), FindIntermissionPoint(), G_CheckTeamItems(), G_PickTarget(), G_UseTargets(), SelectInitialSpawnPoint(), SelectNearestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), SelectRandomTeamSpawnPoint(), target_laser_start(), Team_FragBonuses(), Team_ResetFlag(), Think_SetupTrainTargets(), and Use_Target_Give().
G_FreeEntity()
void G_FreeEntity (gentity_t * e)
Definition at line 478 of file g_utils.c.
 {
     trap_UnlinkEntity(ed);        // unlink from world
     if (ed->neverFree) {
         return;
     }
     memset(ed, 0, sizeof(*ed));
     ed->classname = "freed";
     ed->freetime = level.time;
     ed->inuse = qfalse;
 }
References gentity_s::classname, gentity_s::freetime, gentity_s::inuse, level, gentity_s::neverFree, qfalse, level_locals_t::time, and trap_UnlinkEntity().
Referenced by AimAtTarget(), Blocked_Door(), Cmd_Give_f(), FinishSpawningItem(), G_MoverPush(), G_RunFrame(), G_RunItem(), G_RunMissile(), G_SpawnGEntityFromSpawnVars(), GibEntity(), LaunchItem(), locateCamera(), multi_trigger(), Pickup_Team(), player_die(), SP_func_train(), SP_info_null(), SP_light(), SP_misc_model(), SP_path_corner(), Team_ResetFlag(), trigger_always_think(), and Weapon_HookFree().
G_GetBotInfoByName()
char* G_GetBotInfoByName (const char * name)
Definition at line 996 of file g_bot.c.
 {
     int        n;
     char* value;
     for (n = 0; n < g_numBots; n++) {
         value = Info_ValueForKey(g_botInfos[n], "name");
         if (!Q_stricmp(value, name)) {
             return g_botInfos[n];
         }
     }
     return NULL;
 }
References g_botInfos, g_numBots, Info_ValueForKey(), NULL, and Q_stricmp().
Referenced by G_AddBot().
G_GetBotInfoByNumber()
char* G_GetBotInfoByNumber (int num)
Definition at line 981 of file g_bot.c.
 {
     if (num < 0 || num >= g_numBots) {
         trap_Print(va(S_COLOR_RED "Invalid bot number: %i\n", num));
         return NULL;
     }
     return g_botInfos[num];
 }
References g_botInfos, g_numBots, NULL, S_COLOR_RED, trap_Print(), and va().
Referenced by G_AddBot().
G_InitBots()
void G_InitBots (qboolean restart)
Definition at line 1016 of file g_bot.c.
 {
     int            fragLimit;
     int            timeLimit;
     const char* arenainfo;
     char* strValue;
     int            basedelay;
     char        map[MAX_QPATH];
     char        serverinfo[MAX_INFO_STRING];
     G_LoadBots();
     G_LoadArenas();
     trap_Cvar_Register(&bot_minplayers, "bot_minplayers", "0", CVAR_SERVERINFO);
     if (g_gametype.integer == GT_SINGLE_PLAYER) {
         trap_GetServerinfo(serverinfo, sizeof(serverinfo));
         Q_strncpyz(map, Info_ValueForKey(serverinfo, "mapname"), sizeof(map));
         arenainfo = G_GetArenaInfoByMap(map);
         if (!arenainfo) {
             return;
         }
         strValue = Info_ValueForKey(arenainfo, "fraglimit");
         fragLimit = atoi(strValue);
         if (fragLimit) {
             trap_Cvar_Set("fraglimit", strValue);
         } else {
             trap_Cvar_Set("fraglimit", "0");
         }
         strValue = Info_ValueForKey(arenainfo, "timelimit");
         timeLimit = atoi(strValue);
         if (timeLimit) {
             trap_Cvar_Set("timelimit", strValue);
         } else {
             trap_Cvar_Set("timelimit", "0");
         }
         if (!fragLimit && !timeLimit) {
             trap_Cvar_Set("fraglimit", "10");
             trap_Cvar_Set("timelimit", "0");
         }
         basedelay = BOT_BEGIN_DELAY_BASE;
         strValue = Info_ValueForKey(arenainfo, "special");
         if (Q_stricmp(strValue, "training") == 0) {
             basedelay += 10000;
         }
         if (!restart) {
             G_SpawnBots(Info_ValueForKey(arenainfo, "bots"), basedelay);
         }
     }
 }
References arenainfo, BOT_BEGIN_DELAY_BASE, bot_minplayers, CVAR_SERVERINFO, g_gametype, G_GetArenaInfoByMap(), G_LoadArenas(), G_LoadBots(), G_SpawnBots(), GT_SINGLE_PLAYER, Info_ValueForKey(), MAX_INFO_STRING, MAX_QPATH, Q_stricmp(), Q_strncpyz(), trap_Cvar_Register(), trap_Cvar_Set(), and trap_GetServerinfo().
Referenced by G_InitGame().
G_InitGentity()
void G_InitGentity (gentity_t * e)
Definition at line 374 of file g_utils.c.
 {
     e->inuse = qtrue;
     e->classname = "noclass";
     e->s.number = e - g_entities;
     e->r.ownerNum = ENTITYNUM_NONE;
 }
References gentity_s::classname, ENTITYNUM_NONE, g_entities, gentity_s::inuse, entityState_s::number, entityShared_t::ownerNum, qtrue, gentity_s::r, and gentity_s::s.
Referenced by ClientBegin(), and G_Spawn().
G_InitMemory()
void G_InitMemory (void)
Definition at line 56 of file g_mem.c.
 {
     allocPoint = 0;
 }
References allocPoint.
Referenced by G_InitGame().
G_InitSessionData()
void G_InitSessionData (gclient_t * client, char * userinfo)
Definition at line 104 of file g_session.c.
 {
     clientSession_t* sess;
     const char* value;
     sess = &client->sess;
     // check for team preference, mainly for bots
     value = Info_ValueForKey(userinfo, "teampref");
     // check for human's team preference set by start server menu
     if (!value[0] && g_localTeamPref.string[0] && client->pers.localClient) {
         value = g_localTeamPref.string;
         // clear team so it's only used once
         trap_Cvar_Set("g_localTeamPref", "");
     }
     // initial team determination
     if (g_gametype.integer >= GT_TEAM) {
         // always spawn as spectator in team games
         sess->sessionTeam = TEAM_SPECTATOR;
         sess->spectatorState = SPECTATOR_FREE;
         if (value[0] || g_teamAutoJoin.integer) {
             SetTeam(&g_entities[client - level.clients], value);
         }
     } else {
         if (value[0] == 's') {
             // a willing spectator, not a waiting-in-line
             sess->sessionTeam = TEAM_SPECTATOR;
         } else {
             switch (g_gametype.integer) {
             default:
             case GT_FFA:
             case GT_SINGLE_PLAYER:
                 if (g_maxGameClients.integer > 0 &&
                     level.numNonSpectatorClients >= g_maxGameClients.integer) {
                     sess->sessionTeam = TEAM_SPECTATOR;
                 } else {
                     sess->sessionTeam = TEAM_FREE;
                 }
                 break;
             case GT_TOURNAMENT:
                 // if the game is full, go into a waiting mode
                 if (level.numNonSpectatorClients >= 2) {
                     sess->sessionTeam = TEAM_SPECTATOR;
                 } else {
                     sess->sessionTeam = TEAM_FREE;
                 }
                 break;
             }
         }
         sess->spectatorState = SPECTATOR_FREE;
     }
     AddTournamentQueue(client);
     G_WriteClientSessionData(client);
 }
References AddTournamentQueue(), level_locals_t::clients, g_entities, g_gametype, g_localTeamPref, g_maxGameClients, g_teamAutoJoin, G_WriteClientSessionData(), GT_FFA, GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, Info_ValueForKey(), vmCvar_t::integer, level, clientPersistant_t::localClient, level_locals_t::numNonSpectatorClients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), SPECTATOR_FREE, clientSession_t::spectatorState, vmCvar_t::string, TEAM_FREE, TEAM_SPECTATOR, and trap_Cvar_Set().
Referenced by ClientConnect().
G_InitWorldSession()
void G_InitWorldSession (void)
Definition at line 173 of file g_session.c.
 {
     char    s[MAX_STRING_CHARS];
     int            gt;
     trap_Cvar_VariableStringBuffer("session", s, sizeof(s));
     gt = atoi(s);
     // if the gametype changed since the last session, don't use any
     // client sessions
     if (g_gametype.integer != gt) {
         level.newSession = qtrue;
         G_Printf("Gametype changed, clearing session data.\n");
     }
 }
References g_gametype, G_Printf(), gt, level, MAX_STRING_CHARS, level_locals_t::newSession, qtrue, s, and trap_Cvar_VariableStringBuffer().
Referenced by G_InitGame().
G_InvulnerabilityEffect()
int G_InvulnerabilityEffect (gentity_t * targ, vec3_t dir, vec3_t point, vec3_t impactpoint, vec3_t bouncedir)
Referenced by Bullet_Fire(), G_Damage(), G_MissileImpact(), ShotgunPellet(), Weapon_LightningFire(), and weapon_railgun_fire().
G_KillBox()
void G_KillBox (gentity_t * ent)
Definition at line 542 of file g_utils.c.
 {
     int            i, num;
     int            touch[MAX_GENTITIES];
     gentity_t* hit;
     vec3_t        mins, maxs;
     VectorAdd(ent->client->ps.origin, ent->r.mins, mins);
     VectorAdd(ent->client->ps.origin, ent->r.maxs, maxs);
     num = trap_EntitiesInBox(mins, maxs, touch, MAX_GENTITIES);
     for (i = 0; i < num; i++) {
         hit = &g_entities[touch[i]];
         if (!hit->client) {
             continue;
         }
         // nail it
         G_Damage(hit, ent, ent, NULL, NULL,
             100000, DAMAGE_NO_PROTECTION, MOD_TELEFRAG);
     }
 }
References gentity_s::client, DAMAGE_NO_PROTECTION, G_Damage(), g_entities, MAX_GENTITIES, entityShared_t::maxs, entityShared_t::mins, MOD_TELEFRAG, NULL, playerState_s::origin, gclient_s::ps, gentity_s::r, trap_EntitiesInBox(), and VectorAdd.
Referenced by ClientSpawn(), and TeleportPlayer().
G_LogPrintf()
void QDECL G_LogPrintf (const char * fmt, ...)
Referenced by ClientBegin(), ClientConnect(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_GameCommand_f(), Cmd_Tell_f(), G_Say(), player_die(), SP_worldspawn(), and Touch_Item().
G_ModelIndex()
int G_ModelIndex (char * name)
Definition at line 119 of file g_utils.c.
 {
     return G_FindConfigstringIndex(name, CS_MODELS, MAX_MODELS, qtrue);
 }
References CS_MODELS, G_FindConfigstringIndex(), MAX_MODELS, and qtrue.
Referenced by BotSetEntityNumForGoalWithModel(), G_InitGame(), InitMover(), SP_misc_model(), and SpawnPodium().
G_NewString()
char* G_NewString (const char * string)
Definition at line 309 of file g_spawn.c.
 {
     char* newb, * new_p;
     int        i, l;
     l = strlen(string) + 1;
     newb = G_Alloc(l);
     new_p = newb;
     // turn \n into a real linefeed
     for (i = 0; i < l; i++) {
         if (string[i] == '\\' && i < l - 1) {
             i++;
             if (string[i] == 'n') {
                 *new_p++ = '\n';
             } else {
                 *new_p++ = '\\';
             }
         } else {
             *new_p++ = string[i];
         }
     }
     return newb;
 }
References G_Alloc().
Referenced by G_ParseField().
G_PickTarget()
gentity_t* G_PickTarget (char * targetname)
Definition at line 197 of file g_utils.c.
 {
     gentity_t* ent = NULL;
     int        num_choices = 0;
     gentity_t* choice[MAXCHOICES];
     if (!targetname) {
         G_Printf("G_PickTarget called with NULL targetname\n");
         return NULL;
     }
     while (1) {
         ent = G_Find(ent, FOFS(targetname), targetname);
         if (!ent)
             break;
         choice[num_choices++] = ent;
         if (num_choices == MAXCHOICES)
             break;
     }
     if (!num_choices) {
         G_Printf("G_PickTarget: target %s not found\n", targetname);
         return NULL;
     }
     return choice[rand() % num_choices];
 }
References FOFS, G_Find(), G_Printf(), MAXCHOICES, and NULL.
Referenced by AimAtTarget(), FindIntermissionPoint(), InitShooter_Finish(), locateCamera(), target_relay_use(), target_teleporter_use(), and trigger_teleporter_touch().
G_Printf()
void QDECL G_Printf (const char * fmt, ...)
Referenced by AddBotToSpawnQueue(), AddIP(), BotAI_Print(), ClientForString(), FinishSpawningItem(), G_AddBot(), G_AddEvent(), G_Alloc(), G_CallSpawn(), G_CheckTeamItems(), G_Damage(), G_InitWorldSession(), G_PickTarget(), G_Say(), G_Spawn(), G_UseTargets(), locateCamera(), SaveRegisteredItems(), SP_func_timer(), SP_func_train(), SP_path_corner(), SP_target_teleporter(), SP_trigger_multiple(), SpawnModelOnVictoryPad(), StringToFilter(), Svcmd_AddIP_f(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), Svcmd_GameMem_f(), Svcmd_RemoveIP_f(), target_laser_start(), target_teleporter_use(), Team_CaptureFlagSound(), Team_ReturnFlagSound(), Team_TakeFlagSound(), Think_SetupTrainTargets(), and trigger_teleporter_touch().
G_ProcessIPBans()
void G_ProcessIPBans (void)
Definition at line 227 of file g_svcmds.c.
 {
     char* s, * t;
     char        str[MAX_CVAR_VALUE_STRING];
     Q_strncpyz(str, g_banIPs.string, sizeof(str));
     for (t = s = g_banIPs.string; *t; /* */) {
         s = strchr(s, ' ');
         if (!s)
             break;
         while (*s == ' ')
             *s++ = 0;
         if (*t)
             AddIP(t);
         t = s;
     }
 }
References AddIP(), g_banIPs, MAX_CVAR_VALUE_STRING, Q_strncpyz(), s, vmCvar_t::string, and t.
Referenced by G_InitGame().
G_RadiusDamage()
qboolean G_RadiusDamage (vec3_t origin, gentity_t * attacker, float damage, float radius, gentity_t * ignore, int mod)
Definition at line 1191 of file g_combat.c.
 {
     float        points, dist;
     gentity_t* ent;
     int            entityList[MAX_GENTITIES];
     int            numListedEntities;
     vec3_t        mins, maxs;
     vec3_t        v;
     vec3_t        dir;
     int            i, e;
     qboolean    hitClient = qfalse;
     if (radius < 1) {
         radius = 1;
     }
     for (i = 0; i < 3; i++) {
         mins[i] = origin[i] - radius;
         maxs[i] = origin[i] + radius;
     }
     numListedEntities = trap_EntitiesInBox(mins, maxs, entityList, MAX_GENTITIES);
     for (e = 0; e < numListedEntities; e++) {
         ent = &g_entities[entityList[e]];
         if (ent == ignore)
             continue;
         if (!ent->takedamage)
             continue;
         // find the distance from the edge of the bounding box
         for (i = 0; i < 3; i++) {
             if (origin[i] < ent->r.absmin[i]) {
                 v[i] = ent->r.absmin[i] - origin[i];
             } else if (origin[i] > ent->r.absmax[i]) {
                 v[i] = origin[i] - ent->r.absmax[i];
             } else {
                 v[i] = 0;
             }
         }
         dist = VectorLength(v);
         if (dist >= radius) {
             continue;
         }
         points = damage * (1.0 - dist / radius);
         if (CanDamage(ent, origin)) {
             if (LogAccuracyHit(ent, attacker)) {
                 hitClient = qtrue;
             }
             VectorSubtract(ent->r.currentOrigin, origin, dir);
             // push the center of mass higher than the origin so players
             // get knocked into the air more
             dir[2] += 24;
             G_Damage(ent, NULL, attacker, dir, origin, (int)points, DAMAGE_RADIUS, mod);
         }
     }
     return hitClient;
 }
References entityShared_t::absmax, entityShared_t::absmin, CanDamage(), entityShared_t::currentOrigin, DAMAGE_RADIUS, G_Damage(), g_entities, LogAccuracyHit(), MAX_GENTITIES, NULL, qfalse, qtrue, gentity_s::r, gentity_s::takedamage, trap_EntitiesInBox(), VectorLength(), and VectorSubtract.
Referenced by G_ExplodeMissile(), and G_MissileImpact().
G_ReadSessionData()
void G_ReadSessionData (gclient_t * client)
Definition at line 70 of file g_session.c.
 {
     char    s[MAX_STRING_CHARS];
     const char* var;
     int teamLeader;
     int spectatorState;
     int sessionTeam;
     var = va("session%i", (int)(client - level.clients));
     trap_Cvar_VariableStringBuffer(var, s, sizeof(s));
     sscanf(s, "%i %i %i %i %i %i %i",
         &sessionTeam,
         &client->sess.spectatorNum,
         &spectatorState,
         &client->sess.spectatorClient,
         &client->sess.wins,
         &client->sess.losses,
         &teamLeader
     );
     client->sess.sessionTeam = (team_t)sessionTeam;
     client->sess.spectatorState = (spectatorState_t)spectatorState;
     client->sess.teamLeader = (qboolean)teamLeader;
 }
References level_locals_t::clients, level, clientSession_t::losses, MAX_STRING_CHARS, s, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::spectatorClient, clientSession_t::spectatorNum, clientSession_t::spectatorState, clientSession_t::teamLeader, trap_Cvar_VariableStringBuffer(), va(), and clientSession_t::wins.
Referenced by ClientConnect().
G_RemoveQueuedBotBegin()
void G_RemoveQueuedBotBegin (int clientNum)
Definition at line 554 of file g_bot.c.
 {
     int        n;
     for (n = 0; n < BOT_SPAWN_QUEUE_DEPTH; n++) {
         if (botSpawnQueue[n].clientNum == clientNum) {
             botSpawnQueue[n].spawnTime = 0;
             return;
         }
     }
 }
References BOT_SPAWN_QUEUE_DEPTH, botSpawnQueue, and botSpawnQueue_t::spawnTime.
Referenced by ClientDisconnect().
G_RunClient()
void G_RunClient (gentity_t * ent)
Definition at line 1037 of file g_active.c.
 {
     if (!(ent->r.svFlags & SVF_BOT) && !g_synchronousClients.integer) {
         return;
     }
     ent->client->pers.cmd.serverTime = level.time;
     ClientThink_real(ent);
 }
References gentity_s::client, ClientThink_real(), clientPersistant_t::cmd, g_synchronousClients, vmCvar_t::integer, level, gclient_s::pers, gentity_s::r, usercmd_s::serverTime, SVF_BOT, entityShared_t::svFlags, and level_locals_t::time.
Referenced by G_RunFrame().
G_RunItem()
void G_RunItem (gentity_t * ent)
Definition at line 963 of file g_items.c.
 {
     vec3_t        origin;
     trace_t        tr;
     int            contents;
     int            mask;
     // if its groundentity has been set to none, it may have been pushed off an edge
     if (ent->s.groundEntityNum == ENTITYNUM_NONE) {
         if (ent->s.pos.trType != TR_GRAVITY) {
             ent->s.pos.trType = TR_GRAVITY;
             ent->s.pos.trTime = level.time;
         }
     }
     if (ent->s.pos.trType == TR_STATIONARY) {
         // check think function
         G_RunThink(ent);
         return;
     }
     // get current position
     BG_EvaluateTrajectory(&ent->s.pos, level.time, origin);
     // trace a line from the previous position to the current position
     if (ent->clipmask) {
         mask = ent->clipmask;
     } else {
         mask = MASK_PLAYERSOLID & ~CONTENTS_BODY;//MASK_SOLID;
     }
     trap_Trace(&tr, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, origin,
         ent->r.ownerNum, mask);
     VectorCopy(tr.endpos, ent->r.currentOrigin);
     if (tr.startsolid) {
         tr.fraction = 0;
     }
     trap_LinkEntity(ent);    // FIXME: avoid this for stationary?
     // check think function
     G_RunThink(ent);
     if (tr.fraction == 1) {
         return;
     }
     // if it is in a nodrop volume, remove it
     contents = trap_PointContents(ent->r.currentOrigin, -1);
     if (contents & CONTENTS_NODROP) {
         if (ent->item && ent->item->giType == IT_TEAM) {
             Team_FreeEntity(ent);
         } else {
             G_FreeEntity(ent);
         }
         return;
     }
     G_BounceItem(ent, &tr);
 }
References BG_EvaluateTrajectory(), gentity_s::clipmask, CONTENTS_BODY, CONTENTS_NODROP, entityShared_t::currentOrigin, ENTITYNUM_NONE, G_BounceItem(), G_FreeEntity(), G_RunThink(), gitem_s::giType, entityState_s::groundEntityNum, IT_TEAM, gentity_s::item, level, MASK_PLAYERSOLID, entityShared_t::maxs, entityShared_t::mins, entityShared_t::ownerNum, entityState_s::pos, gentity_s::r, gentity_s::s, Team_FreeEntity(), level_locals_t::time, tr, TR_GRAVITY, TR_STATIONARY, trap_LinkEntity(), trap_PointContents(), trap_Trace(), trajectory_t::trTime, trajectory_t::trType, and VectorCopy.
Referenced by G_RunFrame().
G_RunMissile()
void G_RunMissile (gentity_t * ent)
Definition at line 455 of file g_missile.c.
 {
     vec3_t        origin;
     trace_t        tr;
     int            passent;
     // get current position
     BG_EvaluateTrajectory(&ent->s.pos, level.time, origin);
     // if this missile bounced off an invulnerability sphere
     if (ent->target_ent) {
         passent = ent->target_ent->s.number;
     }
 #ifdef MISSIONPACK
     // prox mines that left the owner bbox will attach to anything, even the owner
     else if (ent->s.weapon == WP_PROX_LAUNCHER && ent->count) {
         passent = ENTITYNUM_NONE;
     }
 #endif
     else {
         // ignore interactions with the missile owner
         passent = ent->r.ownerNum;
     }
     // trace a line from the previous position to the current position
     trap_Trace(&tr, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, origin, passent, ent->clipmask);
     if (tr.startsolid || tr.allsolid) {
         // make sure the tr.entityNum is set to the entity we're stuck in
         trap_Trace(&tr, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, ent->r.currentOrigin, passent, ent->clipmask);
         tr.fraction = 0;
     } else {
         VectorCopy(tr.endpos, ent->r.currentOrigin);
     }
     trap_LinkEntity(ent);
     if (tr.fraction != 1) {
         // never explode or bounce on sky
         if (tr.surfaceFlags & SURF_NOIMPACT) {
             // If grapple, reset owner
             if (ent->parent && ent->parent->client && ent->parent->client->hook == ent) {
                 ent->parent->client->hook = NULL;
             }
             G_FreeEntity(ent);
             return;
         }
         G_MissileImpact(ent, &tr);
         if (ent->s.eType != ET_MISSILE) {
             return;        // exploded
         }
     }
 #ifdef MISSIONPACK
     // if the prox mine wasn't yet outside the player body
     if (ent->s.weapon == WP_PROX_LAUNCHER && !ent->count) {
         // check if the prox mine is outside the owner bbox
         trap_Trace(&tr, ent->r.currentOrigin, ent->r.mins, ent->r.maxs, ent->r.currentOrigin, ENTITYNUM_NONE, ent->clipmask);
         if (!tr.startsolid || tr.entityNum != ent->r.ownerNum) {
             ent->count = 1;
         }
     }
 #endif
     // check think function after bouncing
     G_RunThink(ent);
 }
References BG_EvaluateTrajectory(), gentity_s::client, gentity_s::clipmask, gentity_s::count, entityShared_t::currentOrigin, ENTITYNUM_NONE, ET_MISSILE, entityState_s::eType, G_FreeEntity(), G_MissileImpact(), G_RunThink(), gclient_s::hook, level, entityShared_t::maxs, entityShared_t::mins, NULL, entityState_s::number, entityShared_t::ownerNum, gentity_s::parent, entityState_s::pos, gentity_s::r, gentity_s::s, SURF_NOIMPACT, gentity_s::target_ent, level_locals_t::time, tr, trap_LinkEntity(), trap_Trace(), VectorCopy, and entityState_s::weapon.
Referenced by G_RunFrame().
G_RunMover()
void G_RunMover (gentity_t * ent)
Definition at line 475 of file g_mover.c.
 {
     // if not a team captain, don't do anything, because
     // the captain will handle everything
     if (ent->flags & FL_TEAMSLAVE) {
         return;
     }
     // if stationary at one of the positions, don't move anything
     if (ent->s.pos.trType != TR_STATIONARY || ent->s.apos.trType != TR_STATIONARY) {
         G_MoverTeam(ent);
     }
     // check think function
     G_RunThink(ent);
 }
References entityState_s::apos, FL_TEAMSLAVE, gentity_s::flags, G_MoverTeam(), G_RunThink(), entityState_s::pos, gentity_s::s, TR_STATIONARY, and trajectory_t::trType.
Referenced by G_RunFrame().
G_RunThink()
void G_RunThink (gentity_t * ent)
Definition at line 1789 of file g_main.c.
 {
     int    thinktime;
     thinktime = ent->nextthink;
     if (thinktime <= 0) {
         return;
     }
     if (thinktime > level.time) {
         return;
     }
     ent->nextthink = 0;
     if (!ent->think) {
         G_Error("NULL ent->think");
     }
     ent->think(ent);
 }
References G_Error(), level, gentity_s::nextthink, gentity_s::think, and level_locals_t::time.
Referenced by G_RunFrame(), G_RunItem(), G_RunMissile(), and G_RunMover().
G_SetMovedir()
void G_SetMovedir (vec3_t angles, vec3_t movedir)
Definition at line 333 of file g_utils.c.
 {
     static vec3_t VEC_UP = { 0, -1, 0 };
     static vec3_t MOVEDIR_UP = { 0, 0, 1 };
     static vec3_t VEC_DOWN = { 0, -2, 0 };
     static vec3_t MOVEDIR_DOWN = { 0, 0, -1 };
     if (VectorCompare(angles, VEC_UP)) {
         VectorCopy(MOVEDIR_UP, movedir);
     } else if (VectorCompare(angles, VEC_DOWN)) {
         VectorCopy(MOVEDIR_DOWN, movedir);
     } else {
         AngleVectors(angles, movedir, NULL, NULL);
     }
     VectorClear(angles);
 }
References AngleVectors(), MOVEDIR_DOWN, MOVEDIR_UP, NULL, VEC_DOWN, VEC_UP, VectorClear, VectorCompare(), and VectorCopy.
Referenced by InitShooter(), InitTrigger(), locateCamera(), SP_func_button(), SP_func_door(), SP_target_push(), and target_laser_start().
G_SetOrigin()
void G_SetOrigin (gentity_t * ent, vec3_t origin)
Definition at line 643 of file g_utils.c.
 {
     VectorCopy(origin, ent->s.pos.trBase);
     ent->s.pos.trType = TR_STATIONARY;
     ent->s.pos.trTime = 0;
     ent->s.pos.trDuration = 0;
     VectorClear(ent->s.pos.trDelta);
     VectorCopy(origin, ent->r.currentOrigin);
 }
References entityShared_t::currentOrigin, entityState_s::pos, gentity_s::r, gentity_s::s, TR_STATIONARY, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trDuration, trajectory_t::trTime, trajectory_t::trType, VectorClear, and VectorCopy.
Referenced by ClientSpawn(), FinishSpawningItem(), G_BounceItem(), G_BounceMissile(), G_ExplodeMissile(), G_MissileImpact(), G_TempEntity(), LaunchItem(), PodiumPlacementThink(), SP_info_camp(), SP_info_notnull(), SP_misc_model(), SP_target_location(), SP_target_position(), SpawnModelOnVictoryPad(), SpawnPodium(), and Weapon_HookThink().
G_Sound()
void G_Sound (gentity_t * ent, int channel, int soundIndex)
Definition at line 624 of file g_utils.c.
 {
     gentity_t* te;
     te = G_TempEntity(ent->r.currentOrigin, EV_GENERAL_SOUND);
     te->s.eventParm = soundIndex;
 }
References entityShared_t::currentOrigin, EV_GENERAL_SOUND, entityState_s::eventParm, G_TempEntity(), gentity_s::r, and gentity_s::s.
Referenced by hurt_touch(), and Use_target_push().
G_SoundIndex()
int G_SoundIndex (char * name)
Definition at line 124 of file g_utils.c.
 {
     return G_FindConfigstringIndex(name, CS_SOUNDS, MAX_SOUNDS, qtrue);
 }
References CS_SOUNDS, G_FindConfigstringIndex(), MAX_SOUNDS, and qtrue.
Referenced by G_InitGame(), G_SetClientSound(), G_SpawnItem(), InitMover(), RespawnItem(), SP_func_button(), SP_func_door(), SP_func_plat(), SP_target_push(), SP_target_speaker(), SP_trigger_hurt(), SP_trigger_push(), and SP_trigger_teleport().
G_Spawn()
gentity_t* G_Spawn (void)
Definition at line 397 of file g_utils.c.
 {
     int            i, force;
     gentity_t* e;
     e = NULL;    // shut up warning
     for (force = 0; force < 2; force++) {
         // if we go through all entities and can't find one to free,
         // override the normal minimum times before use
         e = &g_entities[MAX_CLIENTS];
         for (i = MAX_CLIENTS; i < level.num_entities; i++, e++) {
             if (e->inuse) {
                 continue;
             }
             // the first couple seconds of server time can involve a lot of
             // freeing and allocating, so relax the replacement policy
             if (!force && e->freetime > level.startTime + 2000 && level.time - e->freetime < 1000) {
                 continue;
             }
             // reuse this slot
             G_InitGentity(e);
             return e;
         }
         if (level.num_entities < ENTITYNUM_MAX_NORMAL) {
             break;
         }
     }
     if (level.num_entities == ENTITYNUM_MAX_NORMAL) {
         for (i = 0; i < MAX_GENTITIES; i++) {
             G_Printf("%4i: %s\n", i, g_entities[i].classname);
         }
         G_Error("G_Spawn: no free entities");
     }
     // open up a new slot
     level.num_entities++;
     // let the server system know that there are more entities
     trap_LocateGameData(level.gentities, level.num_entities, sizeof(gentity_t),
         &level.clients[0].ps, sizeof(level.clients[0]));
     G_InitGentity(e);
     return e;
 }
References level_locals_t::clients, ENTITYNUM_MAX_NORMAL, gentity_s::freetime, g_entities, G_Error(), G_InitGentity(), G_Printf(), level_locals_t::gentities, gentity_s::inuse, level, MAX_CLIENTS, MAX_GENTITIES, NULL, level_locals_t::num_entities, gclient_s::ps, level_locals_t::startTime, level_locals_t::time, and trap_LocateGameData().
Referenced by Cmd_Give_f(), fire_bfg(), fire_grapple(), fire_grenade(), fire_plasma(), fire_rocket(), G_MissileImpact(), G_SpawnGEntityFromSpawnVars(), G_TempEntity(), InitBodyQue(), LaunchItem(), SpawnModelOnVictoryPad(), SpawnPlatTrigger(), SpawnPodium(), and Think_SpawnNewDoorTrigger().
G_SpawnEntitiesFromString()
void G_SpawnEntitiesFromString (void)
Definition at line 633 of file g_spawn.c.
 {
     // allow calls to G_Spawn*()
     level.spawning = qtrue;
     level.numSpawnVars = 0;
     // the worldspawn is not an actual entity, but it still
     // has a "spawn" function to perform any global setup
     // needed by a level (setting configstrings or cvars, etc)
     if (!G_ParseSpawnVars()) {
         G_Error("SpawnEntities: no entities");
     }
     SP_worldspawn();
     // parse ents
     while (G_ParseSpawnVars()) {
         G_SpawnGEntityFromSpawnVars();
     }
     level.spawning = qfalse;            // any future calls to G_Spawn*() will be errors
 }
References G_Error(), G_ParseSpawnVars(), G_SpawnGEntityFromSpawnVars(), level, level_locals_t::numSpawnVars, qfalse, qtrue, SP_worldspawn(), and level_locals_t::spawning.
Referenced by G_InitGame().
G_SpawnFloat()
qboolean G_SpawnFloat (const char * key, const char * defaultString, float * out)
Definition at line 46 of file g_spawn.c.
 {
     char* s;
     qboolean    present;
     present = G_SpawnString(key, defaultString, &s);
     *out = atof(s);
     return present;
 }
References G_SpawnString(), and s.
Referenced by G_SpawnItem(), InitMover(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_timer(), SP_misc_portal_camera(), SP_target_delay(), SP_target_speaker(), and SP_trigger_multiple().
G_SpawnInt()
qboolean G_SpawnInt (const char * key, const char * defaultString, int * out)
Definition at line 56 of file g_spawn.c.
 {
     char* s;
     qboolean    present;
     present = G_SpawnString(key, defaultString, &s);
     *out = atoi(s);
     return present;
 }
References G_SpawnString(), and s.
Referenced by G_SpawnGEntityFromSpawnVars(), SP_func_bobbing(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), and SP_info_player_deathmatch().
G_SpawnItem()
void G_SpawnItem (gentity_t * ent, gitem_t * item)
Definition at line 891 of file g_items.c.
 {
     G_SpawnFloat("random", "0", &ent->random);
     G_SpawnFloat("wait", "0", &ent->wait);
     RegisterItem(item);
     if (G_ItemDisabled(item))
         return;
     ent->item = item;
     // some movers spawn on the second frame, so delay item
     // spawns until the third frame so they can ride trains
     ent->nextthink = level.time + FRAMETIME * 2;
     ent->think = FinishSpawningItem;
     ent->physicsBounce = 0.50;        // items are bouncy
     if (item->giType == IT_POWERUP) {
         G_SoundIndex("sound/items/poweruprespawn.wav");
         G_SpawnFloat("noglobalsound", "0", &ent->speed);
     }
 #ifdef MISSIONPACK
     if (item->giType == IT_PERSISTANT_POWERUP) {
         ent->s.generic1 = ent->spawnflags;
     }
 #endif
 }
References FinishSpawningItem(), FRAMETIME, G_ItemDisabled(), G_SoundIndex(), G_SpawnFloat(), entityState_s::generic1, gitem_s::giType, IT_PERSISTANT_POWERUP, IT_POWERUP, gentity_s::item, level, gentity_s::nextthink, gentity_s::physicsBounce, gentity_s::random, RegisterItem(), gentity_s::s, gentity_s::spawnflags, gentity_s::speed, gentity_s::think, level_locals_t::time, and gentity_s::wait.
Referenced by Cmd_Give_f(), and G_CallSpawn().
G_SpawnString()
qboolean G_SpawnString (const char * key, const char * defaultString, char ** out)
Definition at line 26 of file g_spawn.c.
 {
     int        i;
     if (!level.spawning) {
         *out = (char*)defaultString;
         //        G_Error( "G_SpawnString() called while not spawning" );
     }
     for (i = 0; i < level.numSpawnVars; i++) {
         if (!Q_stricmp(key, level.spawnVars[i][0])) {
             *out = level.spawnVars[i][1];
             return qtrue;
         }
     }
     *out = (char*)defaultString;
     return qfalse;
 }
References level, level_locals_t::numSpawnVars, Q_stricmp(), qfalse, qtrue, level_locals_t::spawning, and level_locals_t::spawnVars.
Referenced by G_SpawnFloat(), G_SpawnGEntityFromSpawnVars(), G_SpawnInt(), G_SpawnVector(), InitMover(), SP_target_speaker(), and SP_worldspawn().
G_SpawnVector()
qboolean G_SpawnVector (const char * key, const char * defaultString, float * out)
Definition at line 66 of file g_spawn.c.
 {
     char* s;
     qboolean    present;
     present = G_SpawnString(key, defaultString, &s);
     sscanf(s, "%f %f %f", &out[0], &out[1], &out[2]);
     return present;
 }
References G_SpawnString(), and s.
Referenced by InitMover().
G_TeamCommand()
void G_TeamCommand (team_t team, char * cmd)
Definition at line 139 of file g_utils.c.
 {
     int        i;
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected == CON_CONNECTED) {
             if (level.clients[i].sess.sessionTeam == team) {
                 trap_SendServerCommand(i, va("%s", cmd));
             }
         }
     }
 }
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, level, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, trap_SendServerCommand(), and va().
Referenced by Use_Target_Print().
G_TempEntity()
gentity_t* G_TempEntity (vec3_t origin, int event)
G_TempEntity spawns an event temporary entity that will be auto-removed.
The origin will be snapped to save net bandwidth, so care must be taken if the origin is right on a surface (snap towards start vector first).
Parameters
origin
event
Returns
The event temporary entity.
Definition at line 502 of file g_utils.c.
 {
     gentity_t* e;
     vec3_t      snapped;
     e = G_Spawn();
     e->s.eType = ET_EVENTS + event;
     e->classname = "tempEntity";
     e->eventTime = level.time;
     e->freeAfterEvent = qtrue;
     VectorCopy(origin, snapped);
     SnapVector(snapped);        // save network bandwidth
     G_SetOrigin(e, snapped);
     // find cluster for PVS
     trap_LinkEntity(e);
     return e;
 }
References gentity_s::classname, ET_EVENTS, entityState_s::eType, gentity_s::eventTime, gentity_s::freeAfterEvent, G_SetOrigin(), G_Spawn(), level, qtrue, gentity_s::s, SnapVector, level_locals_t::time, trap_LinkEntity(), and VectorCopy.
Referenced by AddTeamScore(), Blocked_Door(), Bullet_Fire(), CheckGauntletAttack(), ClientDisconnect(), ClientSpawn(), G_Sound(), player_die(), RespawnItem(), ScorePlum(), SendPendingPredictableEvents(), Team_CaptureFlagSound(), Team_ReturnFlagSound(), Team_TakeFlagSound(), TeleportPlayer(), Touch_Item(), Weapon_LightningFire(), weapon_railgun_fire(), and weapon_supershotgun_fire().
G_TouchTriggers()
void G_TouchTriggers (gentity_t * ent)
Definition at line 239 of file g_active.c.
 {
     int            i, num;
     int            touch[MAX_GENTITIES];
     gentity_t* hit;
     trace_t        trace;
     vec3_t        mins, maxs;
     static vec3_t    range = { 40, 40, 52 };
     if (!ent->client) {
         return;
     }
     // dead clients don't activate triggers!
     if (ent->client->ps.stats[STAT_HEALTH] <= 0) {
         return;
     }
     VectorSubtract(ent->client->ps.origin, range, mins);
     VectorAdd(ent->client->ps.origin, range, maxs);
     num = trap_EntitiesInBox(mins, maxs, touch, MAX_GENTITIES);
     // can't use ent->absmin, because that has a one unit pad
     VectorAdd(ent->client->ps.origin, ent->r.mins, mins);
     VectorAdd(ent->client->ps.origin, ent->r.maxs, maxs);
     for (i = 0; i < num; i++) {
         hit = &g_entities[touch[i]];
         if (!hit->touch && !ent->touch) {
             continue;
         }
         if (!(hit->r.contents & CONTENTS_TRIGGER)) {
             continue;
         }
         // ignore most entities if a spectator
         if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
             if (hit->s.eType != ET_TELEPORT_TRIGGER &&
                 // this is ugly but adding a new ET_? type will
                 // most likely cause network incompatibilities
                 hit->touch != Touch_DoorTrigger) {
                 continue;
             }
         }
         // use separate code for determining if an item is picked up
         // so you don't have to actually contact its bounding box
         if (hit->s.eType == ET_ITEM) {
             if (!BG_PlayerTouchesItem(&ent->client->ps, &hit->s, level.time)) {
                 continue;
             }
         } else {
             if (!trap_EntityContact(mins, maxs, hit)) {
                 continue;
             }
         }
         memset(&trace, 0, sizeof(trace));
         if (hit->touch) {
             hit->touch(hit, ent, &trace);
         }
         if ((ent->r.svFlags & SVF_BOT) && (ent->touch)) {
             ent->touch(ent, hit, &trace);
         }
     }
     // if we didn't touch a jump pad this pmove frame
     if (ent->client->ps.jumppad_frame != ent->client->ps.pmove_framecount) {
         ent->client->ps.jumppad_frame = 0;
         ent->client->ps.jumppad_ent = 0;
     }
 }
References BG_PlayerTouchesItem(), gentity_s::client, entityShared_t::contents, CONTENTS_TRIGGER, ET_ITEM, ET_TELEPORT_TRIGGER, entityState_s::eType, g_entities, playerState_s::jumppad_ent, playerState_s::jumppad_frame, level, MAX_GENTITIES, entityShared_t::maxs, entityShared_t::mins, playerState_s::origin, playerState_s::pmove_framecount, gclient_s::ps, gentity_s::r, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, STAT_HEALTH, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, TEAM_SPECTATOR, level_locals_t::time, gentity_s::touch, Touch_DoorTrigger(), trap_EntitiesInBox(), trap_EntityContact(), VectorAdd, and VectorSubtract.
Referenced by ClientThink_real(), and SpectatorThink().
G_UseTargets()
void G_UseTargets (gentity_t * ent, gentity_t * activator)
Definition at line 237 of file g_utils.c.
 {
     gentity_t* t;
     if (!ent) {
         return;
     }
     if (ent->targetShaderName && ent->targetShaderNewName) {
         float f = level.time * 0.001;
         AddRemap(ent->targetShaderName, ent->targetShaderNewName, f);
         trap_SetConfigstring(CS_SHADERSTATE, BuildShaderStateConfig());
     }
     if (!ent->target) {
         return;
     }
     t = NULL;
     while ((t = G_Find(t, FOFS(targetname), ent->target)) != NULL) {
         if (t == ent) {
             G_Printf("WARNING: Entity used itself.\n");
         } else {
             if (t->use) {
                 t->use(t, ent, activator);
             }
         }
         if (!ent->inuse) {
             G_Printf("entity was removed while using targets\n");
             return;
         }
     }
 }
References AddRemap(), BuildShaderStateConfig(), CS_SHADERSTATE, FOFS, G_Find(), G_Printf(), gentity_s::inuse, level, NULL, t, gentity_s::target, gentity_s::targetShaderName, gentity_s::targetShaderNewName, level_locals_t::time, and trap_SetConfigstring().
Referenced by ClientSpawn(), func_timer_think(), multi_trigger(), Reached_BinaryMover(), Reached_Train(), target_relay_use(), Think_Target_Delay(), Touch_Item(), and trigger_always_think().
G_WriteSessionData()
void G_WriteSessionData (void)
Definition at line 195 of file g_session.c.
 {
     int        i;
     trap_Cvar_Set("session", va("%i", g_gametype.integer));
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected == CON_CONNECTED) {
             G_WriteClientSessionData(&level.clients[i]);
         }
     }
 }
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, g_gametype, G_WriteClientSessionData(), level, level_locals_t::maxclients, gclient_s::pers, trap_Cvar_Set(), and va().
Referenced by ExitLevel(), and G_ShutdownGame().
InitBodyQue()
void InitBodyQue (void)
Definition at line 362 of file g_client.c.
 {
     int        i;
     gentity_t* ent;
     level.bodyQueIndex = 0;
     for (i = 0; i < BODY_QUEUE_SIZE; i++) {
         ent = G_Spawn();
         ent->classname = "bodyque";
         ent->neverFree = qtrue;
         level.bodyQue[i] = ent;
     }
 }
References BODY_QUEUE_SIZE, level_locals_t::bodyQue, level_locals_t::bodyQueIndex, gentity_s::classname, G_Spawn(), level, gentity_s::neverFree, and qtrue.
Referenced by G_InitGame().
LaunchItem()
gentity_t* LaunchItem (gitem_t * item, vec3_t origin, vec3_t velocity)
Definition at line 575 of file g_items.c.
 {
     gentity_t* dropped;
     dropped = G_Spawn();
     dropped->s.eType = ET_ITEM;
     dropped->s.modelindex = item - bg_itemlist;    // store item number in modelindex
     dropped->s.modelindex2 = 1; // This is non-zero is it's a dropped item
     dropped->classname = item->classname;
     dropped->item = item;
     VectorSet(dropped->r.mins, -ITEM_RADIUS, -ITEM_RADIUS, -ITEM_RADIUS);
     VectorSet(dropped->r.maxs, ITEM_RADIUS, ITEM_RADIUS, ITEM_RADIUS);
     dropped->r.contents = CONTENTS_TRIGGER;
     dropped->touch = Touch_Item;
     G_SetOrigin(dropped, origin);
     dropped->s.pos.trType = TR_GRAVITY;
     dropped->s.pos.trTime = level.time;
     VectorCopy(velocity, dropped->s.pos.trDelta);
     dropped->s.eFlags |= EF_BOUNCE_HALF;
 #ifdef MISSIONPACK
     if ((g_gametype.integer == GT_CTF || g_gametype.integer == GT_1FCTF) && item->giType == IT_TEAM) { // Special case for CTF flags
 #else
     if (g_gametype.integer == GT_CTF && item->giType == IT_TEAM) { // Special case for CTF flags
 #endif
         dropped->think = Team_DroppedFlagThink;
         dropped->nextthink = level.time + 30000;
         Team_CheckDroppedItem(dropped);
     } else { // auto-remove after 30 seconds
         dropped->think = G_FreeEntity;
         dropped->nextthink = level.time + 30000;
     }
     dropped->flags = FL_DROPPED_ITEM;
     trap_LinkEntity(dropped);
     return dropped;
 }
References bg_itemlist, gentity_s::classname, gitem_s::classname, entityShared_t::contents, CONTENTS_TRIGGER, EF_BOUNCE_HALF, entityState_s::eFlags, ET_ITEM, entityState_s::eType, FL_DROPPED_ITEM, gentity_s::flags, G_FreeEntity(), g_gametype, G_SetOrigin(), G_Spawn(), gitem_s::giType, GT_1FCTF, GT_CTF, IT_TEAM, gentity_s::item, ITEM_RADIUS, level, entityShared_t::maxs, entityShared_t::mins, entityState_s::modelindex, entityState_s::modelindex2, gentity_s::nextthink, entityState_s::pos, gentity_s::r, gentity_s::s, Team_CheckDroppedItem(), Team_DroppedFlagThink(), gentity_s::think, level_locals_t::time, gentity_s::touch, Touch_Item(), TR_GRAVITY, trap_LinkEntity(), trajectory_t::trDelta, trajectory_t::trTime, trajectory_t::trType, VectorCopy, and VectorSet.
Referenced by Drop_Item().
LogAccuracyHit()
qboolean LogAccuracyHit (gentity_t * target, gentity_t * attacker)
Definition at line 762 of file g_weapon.c.
 {
     if (!target->takedamage) {
         return qfalse;
     }
     if (target == attacker) {
         return qfalse;
     }
     if (!target->client) {
         return qfalse;
     }
     if (!attacker->client) {
         return qfalse;
     }
     if (target->client->ps.stats[STAT_HEALTH] <= 0) {
         return qfalse;
     }
     if (OnSameTeam(target, attacker)) {
         return qfalse;
     }
     return qtrue;
 }
References gentity_s::client, OnSameTeam(), gclient_s::ps, qfalse, qtrue, STAT_HEALTH, playerState_s::stats, and gentity_s::takedamage.
Referenced by Bullet_Fire(), G_MissileImpact(), G_RadiusDamage(), ShotgunPellet(), Weapon_LightningFire(), and weapon_railgun_fire().
MoveClientToIntermission()
void MoveClientToIntermission (gentity_t * ent)
Definition at line 945 of file g_main.c.
 {
     // take out of follow mode if needed
     if (ent->client->sess.spectatorState == SPECTATOR_FOLLOW) {
         StopFollowing(ent);
     }
     FindIntermissionPoint();
     // move to the spot
     VectorCopy(level.intermission_origin, ent->s.origin);
     VectorCopy(level.intermission_origin, ent->client->ps.origin);
     VectorCopy(level.intermission_angle, ent->client->ps.viewangles);
     ent->client->ps.pm_type = PM_INTERMISSION;
     // clean up powerup info
     memset(ent->client->ps.powerups, 0, sizeof(ent->client->ps.powerups));
     ent->client->ps.eFlags = 0;
     ent->s.eFlags = 0;
     ent->s.eType = ET_GENERAL;
     ent->s.modelindex = 0;
     ent->s.loopSound = 0;
     ent->s.event = 0;
     ent->r.contents = 0;
 }
References gentity_s::client, entityShared_t::contents, playerState_s::eFlags, entityState_s::eFlags, ET_GENERAL, entityState_s::eType, entityState_s::event, FindIntermissionPoint(), level_locals_t::intermission_angle, level_locals_t::intermission_origin, level, entityState_s::loopSound, entityState_s::modelindex, playerState_s::origin, entityState_s::origin, PM_INTERMISSION, playerState_s::pm_type, playerState_s::powerups, gclient_s::ps, gentity_s::r, gentity_s::s, gclient_s::sess, SPECTATOR_FOLLOW, clientSession_t::spectatorState, StopFollowing(), VectorCopy, and playerState_s::viewangles.
Referenced by BeginIntermission(), and ClientSpawn().
OnSameTeam()
qboolean OnSameTeam (gentity_t * ent1, gentity_t * ent2)
Definition at line 171 of file g_team.c.
 {
     if (!ent1->client || !ent2->client) {
         return qfalse;
     }
     if (g_gametype.integer < GT_TEAM) {
         return qfalse;
     }
     if (ent1->client->sess.sessionTeam == ent2->client->sess.sessionTeam) {
         return qtrue;
     }
     return qfalse;
 }
References gentity_s::client, g_gametype, GT_TEAM, qfalse, qtrue, gclient_s::sess, and clientSession_t::sessionTeam.
Referenced by G_Damage(), G_RankDamage(), G_SayTo(), LogAccuracyHit(), player_die(), and Team_FragBonuses().
PickTeam()
team_t PickTeam (int ignoreClientNum)
Definition at line 598 of file g_client.c.
 {
     int        counts[TEAM_NUM_TEAMS];
     counts[TEAM_BLUE] = TeamCount(ignoreClientNum, TEAM_BLUE);
     counts[TEAM_RED] = TeamCount(ignoreClientNum, TEAM_RED);
     if (counts[TEAM_BLUE] > counts[TEAM_RED]) {
         return TEAM_RED;
     }
     if (counts[TEAM_RED] > counts[TEAM_BLUE]) {
         return TEAM_BLUE;
     }
     // equal team count, so join the team with the lowest score
     if (level.teamScores[TEAM_BLUE] > level.teamScores[TEAM_RED]) {
         return TEAM_RED;
     }
     return TEAM_BLUE;
 }
References level, TEAM_BLUE, TEAM_NUM_TEAMS, TEAM_RED, TeamCount(), and level_locals_t::teamScores.
Referenced by G_AddBot(), and SetTeam().
player_die()
void player_die (gentity_t * self, gentity_t * inflictor, gentity_t * attacker, int damage, int mod)
Definition at line 440 of file g_combat.c.
 {
     gentity_t* ent;
     int            anim;
     int            contents;
     int            killer;
     int            i;
     char* killerName, * obit;
     if (self->client->ps.pm_type == PM_DEAD) {
         return;
     }
     if (level.intermissiontime) {
         return;
     }
     // check for an almost capture
     CheckAlmostCapture(self, attacker);
     // check for a player that almost brought in cubes
     CheckAlmostScored(self, attacker);
     if (self->client && self->client->hook) {
         Weapon_HookFree(self->client->hook);
     }
 #ifdef MISSIONPACK
     if ((self->client->ps.eFlags & EF_TICKING) && self->activator) {
         self->client->ps.eFlags &= ~EF_TICKING;
         self->activator->think = G_FreeEntity;
         self->activator->nextthink = level.time;
     }
 #endif
     self->client->ps.pm_type = PM_DEAD;
     if (attacker) {
         killer = attacker->s.number;
         if (attacker->client) {
             killerName = attacker->client->pers.netname;
         } else {
             killerName = "<non-client>";
         }
     } else {
         killer = ENTITYNUM_WORLD;
         killerName = "<world>";
     }
     if (killer < 0 || killer >= MAX_CLIENTS) {
         killer = ENTITYNUM_WORLD;
         killerName = "<world>";
     }
     if (meansOfDeath < 0 || meansOfDeath >= ARRAY_LEN(modNames)) {
         obit = "<bad obituary>";
     } else {
         obit = modNames[meansOfDeath];
     }
     G_LogPrintf("Kill: %i %i %i: %s killed %s by %s\n",
         killer, self->s.number, meansOfDeath, killerName,
         self->client->pers.netname, obit);
     // broadcast the death event to everyone
     ent = G_TempEntity(self->r.currentOrigin, EV_OBITUARY);
     ent->s.eventParm = meansOfDeath;
     ent->s.otherEntityNum = self->s.number;
     ent->s.otherEntityNum2 = killer;
     ent->r.svFlags = SVF_BROADCAST;    // send to everyone
     self->enemy = attacker;
     self->client->ps.persistant[PERS_KILLED]++;
     if (attacker && attacker->client) {
         attacker->client->lastkilled_client = self->s.number;
         if (attacker == self || OnSameTeam(self, attacker)) {
             AddScore(attacker, self->r.currentOrigin, -1);
         } else {
             AddScore(attacker, self->r.currentOrigin, 1);
             if (meansOfDeath == MOD_GAUNTLET) {
                 // play humiliation on player
                 attacker->client->ps.persistant[PERS_GAUNTLET_FRAG_COUNT]++;
                 // add the sprite over the player's head
                 attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
                 attacker->client->ps.eFlags |= EF_AWARD_GAUNTLET;
                 attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
                 // also play humiliation on target
                 self->client->ps.persistant[PERS_PLAYEREVENTS] ^= PLAYEREVENT_GAUNTLETREWARD;
             }
             // check for two kills in a short amount of time
             // if this is close enough to the last kill, give a reward sound
             if (level.time - attacker->client->lastKillTime < CARNAGE_REWARD_TIME) {
                 // play excellent on player
                 attacker->client->ps.persistant[PERS_EXCELLENT_COUNT]++;
                 // add the sprite over the player's head
                 attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
                 attacker->client->ps.eFlags |= EF_AWARD_EXCELLENT;
                 attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
             }
             attacker->client->lastKillTime = level.time;
         }
     } else {
         AddScore(self, self->r.currentOrigin, -1);
     }
     // Add team bonuses
     Team_FragBonuses(self, inflictor, attacker);
     // if I committed suicide, the flag does not fall, it returns.
     if (meansOfDeath == MOD_SUICIDE) {
         if (self->client->ps.powerups[PW_NEUTRALFLAG]) {        // only happens in One Flag CTF
             Team_ReturnFlag(TEAM_FREE);
             self->client->ps.powerups[PW_NEUTRALFLAG] = 0;
         } else if (self->client->ps.powerups[PW_REDFLAG]) {        // only happens in standard CTF
             Team_ReturnFlag(TEAM_RED);
             self->client->ps.powerups[PW_REDFLAG] = 0;
         } else if (self->client->ps.powerups[PW_BLUEFLAG]) {    // only happens in standard CTF
             Team_ReturnFlag(TEAM_BLUE);
             self->client->ps.powerups[PW_BLUEFLAG] = 0;
         }
     }
     TossClientItems(self);
 #ifdef MISSIONPACK
     TossClientPersistantPowerups(self);
     if (g_gametype.integer == GT_HARVESTER) {
         TossClientCubes(self);
     }
 #endif
     Cmd_Score_f(self);        // show scores
     // send updated scores to any clients that are following this one,
     // or they would get stale scoreboards
     for (i = 0; i < level.maxclients; i++) {
         gclient_t* client;
         client = &level.clients[i];
         if (client->pers.connected != CON_CONNECTED) {
             continue;
         }
         if (client->sess.sessionTeam != TEAM_SPECTATOR) {
             continue;
         }
         if (client->sess.spectatorClient == self->s.number) {
             Cmd_Score_f(g_entities + i);
         }
     }
     self->takedamage = qtrue;    // can still be gibbed
     self->s.weapon = WP_NONE;
     self->s.powerups = 0;
     self->r.contents = CONTENTS_CORPSE;
     self->s.angles[0] = 0;
     self->s.angles[2] = 0;
     LookAtKiller(self, inflictor, attacker);
     VectorCopy(self->s.angles, self->client->ps.viewangles);
     self->s.loopSound = 0;
     self->r.maxs[2] = -8;
     // don't allow respawn until the death anim is done
     // g_forcerespawn may force spawning at some later time
     self->client->respawnTime = level.time + 1700;
     // remove powerups
     memset(self->client->ps.powerups, 0, sizeof(self->client->ps.powerups));
     // never gib in a nodrop
     contents = trap_PointContents(self->r.currentOrigin, -1);
     if ((self->health <= GIB_HEALTH && !(contents & CONTENTS_NODROP) && g_blood.integer) || meansOfDeath == MOD_SUICIDE) {
         // gib death
         GibEntity(self, killer);
     } else {
         // normal death
         static int i;
         switch (i) {
         case 0:
             anim = BOTH_DEATH1;
             break;
         case 1:
             anim = BOTH_DEATH2;
             break;
         case 2:
         default:
             anim = BOTH_DEATH3;
             break;
         }
         // for the no-blood option, we need to prevent the health
         // from going to gib level
         if (self->health <= GIB_HEALTH) {
             self->health = GIB_HEALTH + 1;
         }
         self->client->ps.legsAnim =
             ((self->client->ps.legsAnim & ANIM_TOGGLEBIT) ^ ANIM_TOGGLEBIT) | anim;
         self->client->ps.torsoAnim =
             ((self->client->ps.torsoAnim & ANIM_TOGGLEBIT) ^ ANIM_TOGGLEBIT) | anim;
         G_AddEvent(self, EV_DEATH1 + i, killer);
         // the body can still be gibbed
         self->die = body_die;
         // globally cycle through the different death animations
         i = (i + 1) % 3;
 #ifdef MISSIONPACK
         if (self->s.eFlags & EF_KAMIKAZE) {
             Kamikaze_DeathTimer(self);
         }
 #endif
     }
     trap_LinkEntity(self);
 }
References AddScore(), ANIM_TOGGLEBIT, ARRAY_LEN, body_die(), BOTH_DEATH1, BOTH_DEATH2, BOTH_DEATH3, CARNAGE_REWARD_TIME, CheckAlmostCapture(), CheckAlmostScored(), gentity_s::client, level_locals_t::clients, Cmd_Score_f(), CON_CONNECTED, clientPersistant_t::connected, CONTENTS_CORPSE, CONTENTS_NODROP, entityShared_t::currentOrigin, EF_AWARD_ASSIST, EF_AWARD_CAP, EF_AWARD_DEFEND, EF_AWARD_EXCELLENT, EF_AWARD_GAUNTLET, EF_AWARD_IMPRESSIVE, EF_KAMIKAZE, playerState_s::eFlags, ENTITYNUM_WORLD, EV_DEATH1, EV_OBITUARY, entityState_s::eventParm, G_AddEvent(), g_blood, g_entities, G_FreeEntity(), g_gametype, G_LogPrintf(), G_TempEntity(), GIB_HEALTH, GibEntity(), GT_HARVESTER, vmCvar_t::integer, level_locals_t::intermissiontime, gclient_s::lastkilled_client, gclient_s::lastKillTime, level, LookAtKiller(), MAX_CLIENTS, level_locals_t::maxclients, MOD_GAUNTLET, MOD_SUICIDE, modNames, clientPersistant_t::netname, entityState_s::number, OnSameTeam(), entityState_s::otherEntityNum, entityState_s::otherEntityNum2, gclient_s::pers, PERS_EXCELLENT_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_KILLED, PERS_PLAYEREVENTS, playerState_s::persistant, PLAYEREVENT_GAUNTLETREWARD, PM_DEAD, gclient_s::ps, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, qtrue, gentity_s::r, REWARD_SPRITE_TIME, gclient_s::rewardTime, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::spectatorClient, SVF_BROADCAST, entityShared_t::svFlags, TEAM_BLUE, Team_FragBonuses(), TEAM_FREE, TEAM_RED, Team_ReturnFlag(), TEAM_SPECTATOR, level_locals_t::time, TossClientCubes(), TossClientItems(), trap_LinkEntity(), trap_PointContents(), VectorCopy, Weapon_HookFree(), and WP_NONE.
Referenced by ClientSpawn(), Cmd_Kill_f(), and SetTeam().
PrecacheItem()
void PrecacheItem (gitem_t * it)
RegisterItem()
void RegisterItem (gitem_t * item)
Definition at line 829 of file g_items.c.
 {
     if (!item) {
         G_Error("RegisterItem: NULL");
     }
     itemRegistered[item - bg_itemlist] = qtrue;
 }
References bg_itemlist, G_Error(), itemRegistered, and qtrue.
Referenced by ClearRegisteredItems(), G_SpawnItem(), and InitShooter().
RespawnItem()
void RespawnItem (gentity_t * ent)
Definition at line 354 of file g_items.c.
 {
     if (!ent) {
         return;
     }
     // randomly select from teamed entities
     if (ent->team) {
         gentity_t* master;
         int    count;
         int choice;
         if (!ent->teammaster) {
             G_Error("RespawnItem: bad teammaster");
         }
         master = ent->teammaster;
         for (count = 0, ent = master; ent; ent = ent->teamchain, count++)
             ;
         choice = rand() % count;
         for (count = 0, ent = master; ent && count < choice; ent = ent->teamchain, count++)
             ;
     }
     if (!ent) {
         return;
     }
     ent->r.contents = CONTENTS_TRIGGER;
     ent->s.eFlags &= ~EF_NODRAW;
     ent->r.svFlags &= ~SVF_NOCLIENT;
     trap_LinkEntity(ent);
     if (ent->item->giType == IT_POWERUP) {
         // play powerup spawn sound to all clients
         gentity_t* te;
         // if the powerup respawn sound should Not be global
         if (ent->speed) {
             te = G_TempEntity(ent->s.pos.trBase, EV_GENERAL_SOUND);
         } else {
             te = G_TempEntity(ent->s.pos.trBase, EV_GLOBAL_SOUND);
         }
         te->s.eventParm = G_SoundIndex("sound/items/poweruprespawn.wav");
         te->r.svFlags |= SVF_BROADCAST;
     }
     if (ent->item->giType == IT_HOLDABLE && ent->item->giTag == HI_KAMIKAZE) {
         // play powerup spawn sound to all clients
         gentity_t* te;
         // if the powerup respawn sound should Not be global
         if (ent->speed) {
             te = G_TempEntity(ent->s.pos.trBase, EV_GENERAL_SOUND);
         } else {
             te = G_TempEntity(ent->s.pos.trBase, EV_GLOBAL_SOUND);
         }
         te->s.eventParm = G_SoundIndex("sound/items/kamikazerespawn.wav");
         te->r.svFlags |= SVF_BROADCAST;
     }
     // play the normal respawn sound only to nearby clients
     G_AddEvent(ent, EV_ITEM_RESPAWN, 0);
     ent->nextthink = 0;
 }
References entityShared_t::contents, CONTENTS_TRIGGER, count, EF_NODRAW, entityState_s::eFlags, EV_GENERAL_SOUND, EV_GLOBAL_SOUND, EV_ITEM_RESPAWN, entityState_s::eventParm, G_AddEvent(), G_Error(), G_SoundIndex(), G_TempEntity(), gitem_s::giTag, gitem_s::giType, HI_KAMIKAZE, IT_HOLDABLE, IT_POWERUP, gentity_s::item, gentity_s::nextthink, entityState_s::pos, gentity_s::r, gentity_s::s, gentity_s::speed, SVF_BROADCAST, SVF_NOCLIENT, entityShared_t::svFlags, gentity_s::team, gentity_s::teamchain, gentity_s::teammaster, trap_LinkEntity(), and trajectory_t::trBase.
Referenced by FinishSpawningItem(), Team_ResetFlag(), Touch_Item(), and Use_Item().
SaveRegisteredItems()
void SaveRegisteredItems (void)
Definition at line 846 of file g_items.c.
 {
     char    string[MAX_ITEMS + 1];
     int        i;
     int        count;
     count = 0;
     for (i = 0; i < bg_numItems; i++) {
         if (itemRegistered[i]) {
             count++;
             string[i] = '1';
         } else {
             string[i] = '0';
         }
     }
     string[bg_numItems] = 0;
     G_Printf("%i items registered\n", count);
     trap_SetConfigstring(CS_ITEMS, string);
 }
References bg_numItems, count, CS_ITEMS, G_Printf(), itemRegistered, MAX_ITEMS, and trap_SetConfigstring().
Referenced by G_InitGame().
SelectSpawnPoint()
gentity_t* SelectSpawnPoint (vec3_t avoidPoint, vec3_t origin, vec3_t angles, qboolean isbot)
Definition at line 266 of file g_client.c.
 {
     return SelectRandomFurthestSpawnPoint(avoidPoint, origin, angles, isbot);
     /*
     gentity_t    *spot;
     gentity_t    *nearestSpot;
     nearestSpot = SelectNearestDeathmatchSpawnPoint( avoidPoint );
     spot = SelectRandomDeathmatchSpawnPoint ( );
     if ( spot == nearestSpot ) {
         // roll again if it would be real close to point of death
         spot = SelectRandomDeathmatchSpawnPoint ( );
         if ( spot == nearestSpot ) {
             // last try
             spot = SelectRandomDeathmatchSpawnPoint ( );
         }
     }
     // find a single player start spot
     if (!spot) {
         G_Error( "Couldn't find a spawn point" );
     }
     VectorCopy (spot->s.origin, origin);
     origin[2] += 9;
     VectorCopy (spot->s.angles, angles);
     return spot;
     */
 }
References SelectRandomFurthestSpawnPoint().
Referenced by ClientEvents(), ClientSpawn(), FindIntermissionPoint(), SelectCTFSpawnPoint(), and SelectInitialSpawnPoint().
SendScoreboardMessageToAllClients()
void QDECL void SendScoreboardMessageToAllClients (void)
Definition at line 926 of file g_main.c.
 {
     int        i;
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected == CON_CONNECTED) {
             DeathmatchScoreboardMessage(g_entities + i);
         }
     }
 }
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, DeathmatchScoreboardMessage(), g_entities, level, level_locals_t::maxclients, and gclient_s::pers.
Referenced by BeginIntermission(), and CalculateRanks().
SetClientViewAngle()
void SetClientViewAngle (gentity_t * ent, vec3_t angle)
Definition at line 513 of file g_client.c.
 {
     int            i;
     // set the delta angle
     for (i = 0; i < 3; i++) {
         int        cmdAngle;
         cmdAngle = ANGLE2SHORT(angle[i]);
         ent->client->ps.delta_angles[i] = cmdAngle - ent->client->pers.cmd.angles[i];
     }
     VectorCopy(angle, ent->s.angles);
     VectorCopy(ent->s.angles, ent->client->ps.viewangles);
 }
References ANGLE2SHORT, usercmd_s::angles, entityState_s::angles, gentity_s::client, clientPersistant_t::cmd, playerState_s::delta_angles, gclient_s::pers, gclient_s::ps, gentity_s::s, VectorCopy, and playerState_s::viewangles.
Referenced by ClientSpawn(), StopFollowing(), and TeleportPlayer().
SetLeader()
void SetLeader (int team, int client)
Definition at line 1656 of file g_main.c.
 {
     int i;
     if (level.clients[client].pers.connected == CON_DISCONNECTED) {
         PrintTeam(team, va("print \"%s is not connected\n\"", level.clients[client].pers.netname));
         return;
     }
     if (level.clients[client].sess.sessionTeam != team) {
         PrintTeam(team, va("print \"%s is not on the team anymore\n\"", level.clients[client].pers.netname));
         return;
     }
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].sess.sessionTeam != team)
             continue;
         if (level.clients[i].sess.teamLeader) {
             level.clients[i].sess.teamLeader = qfalse;
             ClientUserinfoChanged(i);
         }
     }
     level.clients[client].sess.teamLeader = qtrue;
     ClientUserinfoChanged(client);
     PrintTeam(team, va("print \"%s is the new team leader\n\"", level.clients[client].pers.netname));
 }
References level_locals_t::clients, ClientUserinfoChanged(), CON_DISCONNECTED, clientPersistant_t::connected, level, level_locals_t::maxclients, clientPersistant_t::netname, gclient_s::pers, PrintTeam(), qfalse, qtrue, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::teamLeader, and va().
Referenced by CheckTeamVote(), and SetTeam().
SetRespawn()
void SetRespawn (gentity_t * ent, float delay)
SetTeam()
void SetTeam (gentity_t * ent, const char * s)
Definition at line 518 of file g_cmds.c.
 {
     int                    team, oldTeam;
     gclient_t* client;
     int                    clientNum;
     spectatorState_t    specState;
     int                    specClient;
     int                    teamLeader;
     //
     // see what change is requested
     //
     client = ent->client;
     clientNum = client - level.clients;
     specClient = 0;
     specState = SPECTATOR_NOT;
     if (!Q_stricmp(s, "scoreboard") || !Q_stricmp(s, "score")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_SCOREBOARD;
     } else if (!Q_stricmp(s, "follow1")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FOLLOW;
         specClient = -1;
     } else if (!Q_stricmp(s, "follow2")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FOLLOW;
         specClient = -2;
     } else if (!Q_stricmp(s, "spectator") || !Q_stricmp(s, "s")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FREE;
     } else if (g_gametype.integer >= GT_TEAM) {
         // if running a team game, assign player to one of the teams
         specState = SPECTATOR_NOT;
         if (!Q_stricmp(s, "red") || !Q_stricmp(s, "r")) {
             team = TEAM_RED;
         } else if (!Q_stricmp(s, "blue") || !Q_stricmp(s, "b")) {
             team = TEAM_BLUE;
         } else {
             // pick the team with the least number of players
             team = PickTeam(clientNum);
         }
         if (g_teamForceBalance.integer && !client->pers.localClient && !(ent->r.svFlags & SVF_BOT)) {
             int        counts[TEAM_NUM_TEAMS];
             counts[TEAM_BLUE] = TeamCount(clientNum, TEAM_BLUE);
             counts[TEAM_RED] = TeamCount(clientNum, TEAM_RED);
             // We allow a spread of two
             if (team == TEAM_RED && counts[TEAM_RED] - counts[TEAM_BLUE] > 1) {
                 trap_SendServerCommand(clientNum,
                     "cp \"Red team has too many players.\n\"");
                 return; // ignore the request
             }
             if (team == TEAM_BLUE && counts[TEAM_BLUE] - counts[TEAM_RED] > 1) {
                 trap_SendServerCommand(clientNum,
                     "cp \"Blue team has too many players.\n\"");
                 return; // ignore the request
             }
             // It's ok, the team we are switching to has less or same number of players
         }
     } else {
         // force them to spectators if there aren't any spots free
         team = TEAM_FREE;
     }
     // override decision if limiting the players
     if ((g_gametype.integer == GT_TOURNAMENT)
         && level.numNonSpectatorClients >= 2) {
         team = TEAM_SPECTATOR;
     } else if (g_maxGameClients.integer > 0 &&
         level.numNonSpectatorClients >= g_maxGameClients.integer) {
         team = TEAM_SPECTATOR;
     }
     //
     // decide if we will allow the change
     //
     oldTeam = client->sess.sessionTeam;
     if (team == oldTeam && team != TEAM_SPECTATOR) {
         return;
     }
     //
     // execute the team change
     //
     // if the player was dead leave the body, but only if they're actually in game
     if (client->ps.stats[STAT_HEALTH] <= 0 && client->pers.connected == CON_CONNECTED) {
         CopyToBodyQue(ent);
     }
     // he starts at 'base'
     client->pers.teamState.state = TEAM_BEGIN;
     if (oldTeam != TEAM_SPECTATOR) {
         // Kill him (makes sure he loses flags, etc)
         ent->flags &= ~FL_GODMODE;
         ent->client->ps.stats[STAT_HEALTH] = ent->health = 0;
         player_die(ent, ent, ent, 100000, MOD_SUICIDE);
     }
     // they go to the end of the line for tournements
     if (team == TEAM_SPECTATOR && oldTeam != team)
         AddTournamentQueue(client);
     client->sess.sessionTeam = team;
     client->sess.spectatorState = specState;
     client->sess.spectatorClient = specClient;
     client->sess.teamLeader = qfalse;
     if (team == TEAM_RED || team == TEAM_BLUE) {
         teamLeader = TeamLeader(team);
         // if there is no team leader or the team leader is a bot and this client is not a bot
         if (teamLeader == -1 || (!(g_entities[clientNum].r.svFlags & SVF_BOT) && (g_entities[teamLeader].r.svFlags & SVF_BOT))) {
             SetLeader(team, clientNum);
         }
     }
     // make sure there is a team leader on the team the player came from
     if (oldTeam == TEAM_RED || oldTeam == TEAM_BLUE) {
         CheckTeamLeader(oldTeam);
     }
     // get and distribute relevant parameters
     ClientUserinfoChanged(clientNum);
     // client hasn't spawned yet, they sent an early team command, teampref userinfo, or g_teamAutoJoin is enabled
     if (client->pers.connected != CON_CONNECTED) {
         return;
     }
     BroadcastTeamChange(client, oldTeam);
     ClientBegin(clientNum);
 }
References AddTournamentQueue(), BroadcastTeamChange(), CheckTeamLeader(), gentity_s::client, ClientBegin(), level_locals_t::clients, ClientUserinfoChanged(), CON_CONNECTED, clientPersistant_t::connected, CopyToBodyQue(), FL_GODMODE, gentity_s::flags, g_entities, g_gametype, g_maxGameClients, g_teamForceBalance, GT_TEAM, GT_TOURNAMENT, gentity_s::health, vmCvar_t::integer, level, clientPersistant_t::localClient, MOD_SUICIDE, level_locals_t::numNonSpectatorClients, gclient_s::pers, PickTeam(), player_die(), gclient_s::ps, Q_stricmp(), qfalse, gentity_s::r, s, gclient_s::sess, clientSession_t::sessionTeam, SetLeader(), SPECTATOR_FOLLOW, SPECTATOR_FREE, SPECTATOR_NOT, SPECTATOR_SCOREBOARD, clientSession_t::spectatorClient, clientSession_t::spectatorState, STAT_HEALTH, playerTeamState_t::state, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, TEAM_BEGIN, TEAM_BLUE, TEAM_FREE, TEAM_NUM_TEAMS, TEAM_RED, TEAM_SPECTATOR, TeamCount(), clientSession_t::teamLeader, TeamLeader(), clientPersistant_t::teamState, and trap_SendServerCommand().
Referenced by AddTournamentPlayer(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_Team_f(), G_InitSessionData(), G_RankRunFrame(), RemoveTournamentLoser(), RemoveTournamentWinner(), and Svcmd_ForceTeam_f().
SnapVectorTowards()
void SnapVectorTowards (vec3_t v, vec3_t to)
Definition at line 147 of file g_weapon.c.
 {
     int        i;
     for (i = 0; i < 3; i++) {
         if (to[i] <= v[i]) {
             v[i] = floor(v[i]);
         } else {
             v[i] = ceil(v[i]);
         }
     }
 }
Referenced by Bullet_Fire(), G_MissileImpact(), Weapon_HookThink(), and weapon_railgun_fire().
SpawnModelsOnVictoryPads()
void SpawnModelsOnVictoryPads (void)
Definition at line 330 of file g_arenas.c.
 {
     gentity_t* player;
     gentity_t* podium;
     podium1 = NULL;
     podium2 = NULL;
     podium3 = NULL;
     podium = SpawnPodium();
     player = SpawnModelOnVictoryPad(podium, offsetFirst, &g_entities[level.sortedClients[0]],
         level.clients[level.sortedClients[0]].ps.persistant[PERS_RANK] & ~RANK_TIED_FLAG);
     if (player) {
         player->nextthink = level.time + 2000;
         player->think = CelebrateStart;
         podium1 = player;
     }
     player = SpawnModelOnVictoryPad(podium, offsetSecond, &g_entities[level.sortedClients[1]],
         level.clients[level.sortedClients[1]].ps.persistant[PERS_RANK] & ~RANK_TIED_FLAG);
     if (player) {
         podium2 = player;
     }
     if (level.numNonSpectatorClients > 2) {
         player = SpawnModelOnVictoryPad(podium, offsetThird, &g_entities[level.sortedClients[2]],
             level.clients[level.sortedClients[2]].ps.persistant[PERS_RANK] & ~RANK_TIED_FLAG);
         if (player) {
             podium3 = player;
         }
     }
 }
References CelebrateStart(), level_locals_t::clients, g_entities, level, gentity_s::nextthink, NULL, level_locals_t::numNonSpectatorClients, offsetFirst, offsetSecond, offsetThird, PERS_RANK, playerState_s::persistant, podium1, podium2, podium3, gclient_s::ps, RANK_TIED_FLAG, level_locals_t::sortedClients, SpawnModelOnVictoryPad(), SpawnPodium(), gentity_s::think, and level_locals_t::time.
Referenced by BeginIntermission().
SpotWouldTelefrag()
qboolean SpotWouldTelefrag (gentity_t * spot)
Definition at line 84 of file g_client.c.
 {
     int            i, num;
     int            touch[MAX_GENTITIES];
     gentity_t* hit;
     vec3_t        mins, maxs;
     VectorAdd(spot->s.origin, playerMins, mins);
     VectorAdd(spot->s.origin, playerMaxs, maxs);
     num = trap_EntitiesInBox(mins, maxs, touch, MAX_GENTITIES);
     for (i = 0; i < num; i++) {
         hit = &g_entities[touch[i]];
         //if ( hit->client && hit->client->ps.stats[STAT_HEALTH] > 0 ) {
         if (hit->client) {
             return qtrue;
         }
     }
     return qfalse;
 }
References gentity_s::client, g_entities, MAX_GENTITIES, entityState_s::origin, playerMaxs, playerMins, qfalse, qtrue, gentity_s::s, trap_EntitiesInBox(), and VectorAdd.
Referenced by SelectInitialSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), and SelectRandomTeamSpawnPoint().
StopFollowing()
void StopFollowing (gentity_t * ent)
Definition at line 665 of file g_cmds.c.
 {
     ent->client->ps.persistant[PERS_TEAM] = TEAM_SPECTATOR;
     ent->client->sess.sessionTeam = TEAM_SPECTATOR;
     ent->client->sess.spectatorState = SPECTATOR_FREE;
     ent->client->ps.pm_flags &= ~PMF_FOLLOW;
     ent->r.svFlags &= ~SVF_BOT;
     ent->client->ps.clientNum = ent - g_entities;
     SetClientViewAngle(ent, ent->client->ps.viewangles);
     // don't use dead view angles
     if (ent->client->ps.stats[STAT_HEALTH] <= 0) {
         ent->client->ps.stats[STAT_HEALTH] = 1;
     }
 }
References gentity_s::client, playerState_s::clientNum, g_entities, PERS_TEAM, playerState_s::persistant, playerState_s::pm_flags, PMF_FOLLOW, gclient_s::ps, gentity_s::r, gclient_s::sess, clientSession_t::sessionTeam, SetClientViewAngle(), SPECTATOR_FREE, clientSession_t::spectatorState, STAT_HEALTH, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, TEAM_SPECTATOR, and playerState_s::viewangles.
Referenced by ClientDisconnect(), Cmd_Follow_f(), and MoveClientToIntermission().
Svcmd_AbortPodium_f()
void Svcmd_AbortPodium_f (void)
Definition at line 370 of file g_arenas.c.
 {
     if (g_gametype.integer != GT_SINGLE_PLAYER) {
         return;
     }
     if (podium1) {
         podium1->nextthink = level.time;
         podium1->think = CelebrateStop;
     }
 }
References CelebrateStop(), g_gametype, GT_SINGLE_PLAYER, level, gentity_s::nextthink, podium1, gentity_s::think, and level_locals_t::time.
Referenced by ConsoleCommand().
Svcmd_AddBot_f()
void Svcmd_AddBot_f (void)
Definition at line 758 of file g_bot.c.
 {
     float            skill;
     int                delay;
     char            name[MAX_TOKEN_CHARS];
     char            altname[MAX_TOKEN_CHARS];
     char            string[MAX_TOKEN_CHARS];
     char            team[MAX_TOKEN_CHARS];
     // are bots enabled?
     if (!trap_Cvar_VariableIntegerValue("bot_enable")) {
         return;
     }
     // name
     trap_Argv(1, name, sizeof(name));
     if (!name[0]) {
         trap_Print("Usage: Addbot <botname> [skill 1-5] [team] [msec delay] [altname]\n");
         return;
     }
     // skill
     trap_Argv(2, string, sizeof(string));
     if (!string[0]) {
         skill = 4;
     } else {
         skill = Com_Clamp(1, 5, atof(string));
     }
     // team
     trap_Argv(3, team, sizeof(team));
     // delay
     trap_Argv(4, string, sizeof(string));
     if (!string[0]) {
         delay = 0;
     } else {
         delay = atoi(string);
     }
     // alternative name
     trap_Argv(5, altname, sizeof(altname));
     G_AddBot(name, skill, team, delay, altname);
     // if this was issued during gameplay and we are playing locally,
     // go ahead and load the bot's media immediately
     if (level.time - level.startTime > 1000 &&
         trap_Cvar_VariableIntegerValue("cl_running")) {
         trap_SendServerCommand(-1, "loaddefered\n");    // FIXME: spelled wrong, but not changing for demo
     }
 }
References Com_Clamp(), G_AddBot(), level, MAX_TOKEN_CHARS, level_locals_t::startTime, level_locals_t::time, trap_Argv(), trap_Cvar_VariableIntegerValue(), trap_Print(), and trap_SendServerCommand().
Referenced by ConsoleCommand().
Svcmd_BotList_f()
void Svcmd_BotList_f (void)
Definition at line 816 of file g_bot.c.
 {
     int i;
     char name[MAX_TOKEN_CHARS];
     char funname[MAX_TOKEN_CHARS];
     char model[MAX_TOKEN_CHARS];
     char aifile[MAX_TOKEN_CHARS];
     trap_Print("^1name             model            aifile              funname\n");
     for (i = 0; i < g_numBots; i++) {
         Q_strncpyz(name, Info_ValueForKey(g_botInfos[i], "name"), sizeof(name));
         if (!*name) {
             strcpy(name, "UnnamedPlayer");
         }
         Q_strncpyz(funname, Info_ValueForKey(g_botInfos[i], "funname"), sizeof(funname));
         if (!*funname) {
             strcpy(funname, "");
         }
         Q_strncpyz(model, Info_ValueForKey(g_botInfos[i], "model"), sizeof(model));
         if (!*model) {
             strcpy(model, "visor/default");
         }
         Q_strncpyz(aifile, Info_ValueForKey(g_botInfos[i], "aifile"), sizeof(aifile));
         if (!*aifile) {
             strcpy(aifile, "bots/default_c.c");
         }
         trap_Print(va("%-16s %-16s %-20s %-20s\n", name, model, aifile, funname));
     }
 }
References g_botInfos, g_numBots, Info_ValueForKey(), MAX_TOKEN_CHARS, Q_strncpyz(), trap_Print(), and va().
Referenced by ConsoleCommand().
Svcmd_GameMem_f()
void Svcmd_GameMem_f (void)
Definition at line 61 of file g_mem.c.
 {
     G_Printf("Game memory status: %i out of %i bytes allocated\n", allocPoint, POOLSIZE);
 }
References allocPoint, G_Printf(), and POOLSIZE.
Referenced by ConsoleCommand().
Team_CheckDroppedItem()
void Team_CheckDroppedItem (gentity_t * dropped)
Definition at line 235 of file g_team.c.
 {
     if (dropped->item->giTag == PW_REDFLAG) {
         Team_SetFlagStatus(TEAM_RED, FLAG_DROPPED);
     } else if (dropped->item->giTag == PW_BLUEFLAG) {
         Team_SetFlagStatus(TEAM_BLUE, FLAG_DROPPED);
     } else if (dropped->item->giTag == PW_NEUTRALFLAG) {
         Team_SetFlagStatus(TEAM_FREE, FLAG_DROPPED);
     }
 }
References FLAG_DROPPED, gitem_s::giTag, gentity_s::item, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, TEAM_BLUE, TEAM_FREE, TEAM_RED, and Team_SetFlagStatus().
Referenced by LaunchItem().
TeamCount()
int TeamCount (int ignoreClientNum, team_t team)
Definition at line 547 of file g_client.c.
 {
     int        i;
     int        count = 0;
     for (i = 0; i < level.maxclients; i++) {
         if (i == ignoreClientNum) {
             continue;
         }
         if (level.clients[i].pers.connected == CON_DISCONNECTED) {
             continue;
         }
         if (level.clients[i].sess.sessionTeam == team) {
             count++;
         }
     }
     return count;
 }
References level_locals_t::clients, CON_DISCONNECTED, clientPersistant_t::connected, count, level, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, and clientSession_t::sessionTeam.
Referenced by CheckTournament(), PickTeam(), and SetTeam().
TeamLeader()
int TeamLeader (int team)
Definition at line 574 of file g_client.c.
 {
     int        i;
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected == CON_DISCONNECTED) {
             continue;
         }
         if (level.clients[i].sess.sessionTeam == team) {
             if (level.clients[i].sess.teamLeader)
                 return i;
         }
     }
     return -1;
 }
References level_locals_t::clients, CON_DISCONNECTED, clientPersistant_t::connected, level, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, and clientSession_t::teamLeader.
Referenced by SetTeam().
TeleportPlayer()
void TeleportPlayer (gentity_t * player, vec3_t origin, vec3_t angles)
Definition at line 83 of file g_misc.c.
 {
     gentity_t* tent;
     qboolean noAngles;
     noAngles = (angles[0] > 999999.0);
     // use temp events at source and destination to prevent the effect
     // from getting dropped by a second player event
     if (player->client->sess.sessionTeam != TEAM_SPECTATOR) {
         tent = G_TempEntity(player->client->ps.origin, EV_PLAYER_TELEPORT_OUT);
         tent->s.clientNum = player->s.clientNum;
         tent = G_TempEntity(origin, EV_PLAYER_TELEPORT_IN);
         tent->s.clientNum = player->s.clientNum;
     }
     // unlink to make sure it can't possibly interfere with G_KillBox
     trap_UnlinkEntity(player);
     VectorCopy(origin, player->client->ps.origin);
     player->client->ps.origin[2] += 1;
     if (!noAngles) {
         // spit the player out
         AngleVectors(angles, player->client->ps.velocity, NULL, NULL);
         VectorScale(player->client->ps.velocity, 400, player->client->ps.velocity);
         player->client->ps.pm_time = 160;        // hold time
         player->client->ps.pm_flags |= PMF_TIME_KNOCKBACK;
         // set angles
         SetClientViewAngle(player, angles);
     }
     // toggle the teleport bit so the client knows to not lerp
     player->client->ps.eFlags ^= EF_TELEPORT_BIT;
     // kill anything at the destination
     if (player->client->sess.sessionTeam != TEAM_SPECTATOR) {
         G_KillBox(player);
     }
     // save results of pmove
     BG_PlayerStateToEntityState(&player->client->ps, &player->s, qtrue);
     // use the precise origin for linking
     VectorCopy(player->client->ps.origin, player->r.currentOrigin);
     if (player->client->sess.sessionTeam != TEAM_SPECTATOR) {
         trap_LinkEntity(player);
     }
 }
References AngleVectors(), BG_PlayerStateToEntityState(), gentity_s::client, entityState_s::clientNum, entityShared_t::currentOrigin, EF_TELEPORT_BIT, playerState_s::eFlags, EV_PLAYER_TELEPORT_IN, EV_PLAYER_TELEPORT_OUT, G_KillBox(), G_TempEntity(), NULL, playerState_s::origin, playerState_s::pm_flags, playerState_s::pm_time, PMF_TIME_KNOCKBACK, gclient_s::ps, qtrue, gentity_s::r, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, SetClientViewAngle(), TEAM_SPECTATOR, trap_LinkEntity(), trap_UnlinkEntity(), VectorCopy, VectorScale, and playerState_s::velocity.
Referenced by ClientEvents(), Cmd_SetViewpos_f(), target_teleporter_use(), Touch_DoorTriggerSpectator(), and trigger_teleporter_touch().
Think_Weapon()
void Think_Weapon (gentity_t * ent)
TossClientCubes()
void TossClientCubes (gentity_t * self)
Referenced by ClientDisconnect(), and player_die().
TossClientItems()
void TossClientItems (gentity_t * self)
Definition at line 78 of file g_combat.c.
 {
     gitem_t* item;
     int            weapon;
     float        angle;
     int            i;
     gentity_t* drop;
     // drop the weapon if not a gauntlet or machinegun
     weapon = self->s.weapon;
     // make a special check to see if they are changing to a new
     // weapon that isn't the mg or gauntlet.  Without this, a client
     // can pick up a weapon, be killed, and not drop the weapon because
     // their weapon change hasn't completed yet and they are still holding the MG.
     if (weapon == WP_MACHINEGUN || weapon == WP_GRAPPLING_HOOK) {
         if (self->client->ps.weaponstate == WEAPON_DROPPING) {
             weapon = self->client->pers.cmd.weapon;
         }
         if (!(self->client->ps.stats[STAT_WEAPONS] & (1 << weapon))) {
             weapon = WP_NONE;
         }
     }
     if (weapon > WP_MACHINEGUN&& weapon != WP_GRAPPLING_HOOK &&
         self->client->ps.ammo[weapon]) {
         // find the item type for this weapon
         item = BG_FindItemForWeapon(weapon);
         // spawn the item
         Drop_Item(self, item, 0);
     }
     // drop all the powerups if not in teamplay
     if (g_gametype.integer != GT_TEAM) {
         angle = 45;
         for (i = 1; i < PW_NUM_POWERUPS; i++) {
             if (self->client->ps.powerups[i] > level.time) {
                 item = BG_FindItemForPowerup(i);
                 if (!item) {
                     continue;
                 }
                 drop = Drop_Item(self, item, angle);
                 // decide how many seconds it has left
                 drop->count = (self->client->ps.powerups[i] - level.time) / 1000;
                 if (drop->count < 1) {
                     drop->count = 1;
                 }
                 angle += 45;
             }
         }
     }
 }
References BG_FindItemForPowerup(), BG_FindItemForWeapon(), gentity_s::count, Drop_Item(), g_gametype, GT_TEAM, level, PW_NUM_POWERUPS, gentity_s::s, STAT_WEAPONS, level_locals_t::time, entityState_s::weapon, WEAPON_DROPPING, WP_GRAPPLING_HOOK, WP_MACHINEGUN, and WP_NONE.
Referenced by ClientDisconnect(), and player_die().
Touch_DoorTrigger()
void Touch_DoorTrigger (gentity_t * ent, gentity_t * other, trace_t * trace)
Definition at line 863 of file g_mover.c.
 {
     if (other->client && other->client->sess.sessionTeam == TEAM_SPECTATOR) {
         // if the door is not open and not opening
         if (ent->parent->moverState != MOVER_1TO2 &&
             ent->parent->moverState != MOVER_POS2) {
             Touch_DoorTriggerSpectator(ent, other, trace);
         }
     } else if (ent->parent->moverState != MOVER_1TO2) {
         Use_BinaryMover(ent->parent, ent, other);
     }
 }
References gentity_s::client, MOVER_1TO2, MOVER_POS2, gentity_s::moverState, gentity_s::parent, gclient_s::sess, clientSession_t::sessionTeam, TEAM_SPECTATOR, Touch_DoorTriggerSpectator(), and Use_BinaryMover().
Referenced by G_TouchTriggers(), and Think_SpawnNewDoorTrigger().
Touch_Item()
void Touch_Item (gentity_t * ent, gentity_t * other, trace_t * trace)
Definition at line 429 of file g_items.c.
 {
     int            respawn;
     qboolean    predict;
     if (!other->client)
         return;
     if (other->health < 1)
         return;        // dead people can't pickup
     // the same pickup rules are used for client side and server side
     if (!BG_CanItemBeGrabbed(g_gametype.integer, &ent->s, &other->client->ps)) {
         return;
     }
     G_LogPrintf("Item: %i %s\n", other->s.number, ent->item->classname);
     predict = other->client->pers.predictItemPickup;
     // call the item-specific pickup function
     switch (ent->item->giType) {
     case IT_WEAPON:
         respawn = Pickup_Weapon(ent, other);
         //        predict = qfalse;
         break;
     case IT_AMMO:
         respawn = Pickup_Ammo(ent, other);
         //        predict = qfalse;
         break;
     case IT_ARMOR:
         respawn = Pickup_Armor(ent, other);
         break;
     case IT_HEALTH:
         respawn = Pickup_Health(ent, other);
         break;
     case IT_POWERUP:
         respawn = Pickup_Powerup(ent, other);
         predict = qfalse;
         break;
 #ifdef MISSIONPACK
     case IT_PERSISTANT_POWERUP:
         respawn = Pickup_PersistantPowerup(ent, other);
         break;
 #endif
     case IT_TEAM:
         respawn = Pickup_Team(ent, other);
         break;
     case IT_HOLDABLE:
         respawn = Pickup_Holdable(ent, other);
         break;
     default:
         return;
     }
     if (!respawn) {
         return;
     }
     // play the normal pickup sound
     if (predict) {
         G_AddPredictableEvent(other, EV_ITEM_PICKUP, ent->s.modelindex);
     } else {
         G_AddEvent(other, EV_ITEM_PICKUP, ent->s.modelindex);
     }
     // powerup pickups are global broadcasts
     if (ent->item->giType == IT_POWERUP || ent->item->giType == IT_TEAM) {
         // if we want the global sound to play
         if (!ent->speed) {
             gentity_t* te;
             te = G_TempEntity(ent->s.pos.trBase, EV_GLOBAL_ITEM_PICKUP);
             te->s.eventParm = ent->s.modelindex;
             te->r.svFlags |= SVF_BROADCAST;
         } else {
             gentity_t* te;
             te = G_TempEntity(ent->s.pos.trBase, EV_GLOBAL_ITEM_PICKUP);
             te->s.eventParm = ent->s.modelindex;
             // only send this temp entity to a single client
             te->r.svFlags |= SVF_SINGLECLIENT;
             te->r.singleClient = other->s.number;
         }
     }
     // fire item targets
     G_UseTargets(ent, other);
     // wait of -1 will not respawn
     if (ent->wait == -1) {
         ent->r.svFlags |= SVF_NOCLIENT;
         ent->s.eFlags |= EF_NODRAW;
         ent->r.contents = 0;
         ent->unlinkAfterEvent = qtrue;
         return;
     }
     // non zero wait overrides respawn time
     if (ent->wait) {
         respawn = ent->wait;
     }
     // random can be used to vary the respawn time
     if (ent->random) {
         respawn += crandom() * ent->random;
         if (respawn < 1) {
             respawn = 1;
         }
     }
     // dropped items will not respawn
     if (ent->flags & FL_DROPPED_ITEM) {
         ent->freeAfterEvent = qtrue;
     }
     // picked up items still stay around, they just don't
     // draw anything.  This allows respawnable items
     // to be placed on movers.
     ent->r.svFlags |= SVF_NOCLIENT;
     ent->s.eFlags |= EF_NODRAW;
     ent->r.contents = 0;
     // ZOID
     // A negative respawn times means to never respawn this item (but don't
     // delete it).  This is used by items that are respawned by third party
     // events such as ctf flags
     if (respawn <= 0) {
         ent->nextthink = 0;
         ent->think = 0;
     } else {
         ent->nextthink = level.time + respawn * 1000;
         ent->think = RespawnItem;
     }
     trap_LinkEntity(ent);
 }
References BG_CanItemBeGrabbed(), gitem_s::classname, gentity_s::client, entityShared_t::contents, crandom, EF_NODRAW, entityState_s::eFlags, EV_GLOBAL_ITEM_PICKUP, EV_ITEM_PICKUP, entityState_s::eventParm, FL_DROPPED_ITEM, gentity_s::flags, gentity_s::freeAfterEvent, G_AddEvent(), G_AddPredictableEvent(), g_gametype, G_LogPrintf(), G_TempEntity(), G_UseTargets(), gitem_s::giType, gentity_s::health, IT_AMMO, IT_ARMOR, IT_HEALTH, IT_HOLDABLE, IT_PERSISTANT_POWERUP, IT_POWERUP, IT_TEAM, IT_WEAPON, gentity_s::item, level, entityState_s::modelindex, gentity_s::nextthink, entityState_s::number, gclient_s::pers, Pickup_Ammo(), Pickup_Armor(), Pickup_Health(), Pickup_Holdable(), Pickup_Powerup(), Pickup_Team(), Pickup_Weapon(), entityState_s::pos, clientPersistant_t::predictItemPickup, gclient_s::ps, qfalse, qtrue, gentity_s::r, gentity_s::random, RespawnItem(), gentity_s::s, entityShared_t::singleClient, gentity_s::speed, SVF_BROADCAST, SVF_NOCLIENT, SVF_SINGLECLIENT, entityShared_t::svFlags, gentity_s::think, level_locals_t::time, trap_LinkEntity(), trajectory_t::trBase, gentity_s::unlinkAfterEvent, and gentity_s::wait.
Referenced by Cmd_Give_f(), FinishSpawningItem(), LaunchItem(), and Use_Target_Give().
trap_AAS_AlternativeRouteGoals()
int trap_AAS_AlternativeRouteGoals (vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, void * altroutegoals, int maxaltroutegoals, int type)
Definition at line 869 of file g_syscalls.c.
References BOTLIB_AAS_ALTERNATIVE_ROUTE_GOAL.
Referenced by BotSetupAlternativeRouteGoals().
trap_AAS_AreaInfo()
int trap_AAS_AreaInfo (int areanum, void * info)
Definition at line 811 of file g_syscalls.c.
References BOTLIB_AAS_AREA_INFO.
Referenced by BotGetActivateGoal(), and BotTestAAS().
trap_AAS_AreaReachability()
int trap_AAS_AreaReachability (int areanum)
Definition at line 846 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_AREA_REACHABILITY, areanum);
 }
References BOTLIB_AAS_AREA_REACHABILITY.
Referenced by AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), BotAIBlocked(), BotFuncButtonActivateGoal(), BotGetActivateGoal(), BotGetLongTermGoal(), BotLongTermGoal(), and BotTriggerMultipleActivateGoal().
trap_AAS_AreaTravelTimeToGoalArea()
int trap_AAS_AreaTravelTimeToGoalArea (int areanum, vec3_t origin, int goalareanum, int travelflags)
Definition at line 851 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_AREA_TRAVEL_TIME_TO_GOAL_AREA, areanum, origin, goalareanum, travelflags);
 }
References BOTLIB_AAS_AREA_TRAVEL_TIME_TO_GOAL_AREA.
Referenced by BotAlternateRoute(), BotClientTravelTimeToGoal(), BotGetActivateGoal(), BotGetLongTermGoal(), BotMatch_WhereAreYou(), BotNearbyGoal(), BotSetLastOrderedTask(), and BotWantsToCamp().
trap_AAS_BBoxAreas()
int trap_AAS_BBoxAreas (vec3_t absmins, vec3_t absmaxs, int * areas, int maxareas)
Definition at line 806 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_BBOX_AREAS, absmins, absmaxs, areas, maxareas);
 }
References BOTLIB_AAS_BBOX_AREAS.
Referenced by BotGetActivateGoal().
trap_AAS_EnableRoutingArea()
int trap_AAS_EnableRoutingArea (int areanum, int enable)
Definition at line 856 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_ENABLE_ROUTING_AREA, areanum, enable);
 }
References BOTLIB_AAS_ENABLE_ROUTING_AREA.
Referenced by BotEnableActivateGoalAreas().
trap_AAS_EntityInfo()
void trap_AAS_EntityInfo (int entnum, void * info)
Definition at line 769 of file g_syscalls.c.
References BOTLIB_AAS_ENTITY_INFO.
Referenced by BotEntityInfo().
trap_AAS_FloatForBSPEpairKey()
int trap_AAS_FloatForBSPEpairKey (int ent, char * key, float * value)
Definition at line 836 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_FLOAT_FOR_BSP_EPAIR_KEY, ent, key, value);
 }
References BOTLIB_AAS_FLOAT_FOR_BSP_EPAIR_KEY.
Referenced by BotFuncButtonActivateGoal(), and BotGetActivateGoal().
trap_AAS_Initialized()
int trap_AAS_Initialized (void)
Definition at line 774 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_INITIALIZED);
 }
References BOTLIB_AAS_INITIALIZED.
Referenced by BotAISetupClient(), BotAIStartFrame(), and BotTestAAS().
trap_AAS_IntForBSPEpairKey()
int trap_AAS_IntForBSPEpairKey (int ent, char * key, int * value)
Definition at line 841 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_INT_FOR_BSP_EPAIR_KEY, ent, key, value);
 }
References BOTLIB_AAS_INT_FOR_BSP_EPAIR_KEY.
Referenced by BotGetActivateGoal().
trap_AAS_NextBSPEntity()
int trap_AAS_NextBSPEntity (int ent)
Definition at line 821 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_NEXT_BSP_ENTITY, ent);
 }
References BOTLIB_AAS_NEXT_BSP_ENTITY.
Referenced by BotGetActivateGoal(), BotGoalForBSPEntity(), and BotSetupDeathmatchAI().
trap_AAS_PointAreaNum()
int trap_AAS_PointAreaNum (vec3_t point)
Definition at line 791 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_POINT_AREA_NUM, point);
 }
References BOTLIB_AAS_POINT_AREA_NUM.
Referenced by BotPointAreaNum().
trap_AAS_PointContents()
int trap_AAS_PointContents (vec3_t point)
Definition at line 816 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_POINT_CONTENTS, point);
 }
References BOTLIB_AAS_POINT_CONTENTS.
Referenced by BotCheckAir(), BotEntityVisible(), BotGoForAir(), and BotInLavaOrSlime().
trap_AAS_PointReachabilityAreaIndex()
int trap_AAS_PointReachabilityAreaIndex (vec3_t point)
Definition at line 796 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_POINT_REACHABILITY_AREA_INDEX, point);
 }
References BOTLIB_AAS_POINT_REACHABILITY_AREA_INDEX.
trap_AAS_PredictClientMovement()
int trap_AAS_PredictClientMovement (void * move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
Definition at line 881 of file g_syscalls.c.
References BOTLIB_AAS_PREDICT_CLIENT_MOVEMENT, and PASSFLOAT().
Referenced by BotAimAtEnemy().
trap_AAS_PredictRoute()
int trap_AAS_PredictRoute (void * route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
Definition at line 861 of file g_syscalls.c.
References BOTLIB_AAS_PREDICT_ROUTE.
Referenced by BotAIPredictObstacles().
trap_AAS_PresenceTypeBoundingBox()
void trap_AAS_PresenceTypeBoundingBox (int presencetype, vec3_t mins, vec3_t maxs)
Definition at line 779 of file g_syscalls.c.
 {
     syscall(BOTLIB_AAS_PRESENCE_TYPE_BOUNDING_BOX, presencetype, mins, maxs);
 }
References BOTLIB_AAS_PRESENCE_TYPE_BOUNDING_BOX.
Referenced by BotFuncButtonActivateGoal(), and BotValidChatPosition().
trap_AAS_Swimming()
int trap_AAS_Swimming (vec3_t origin)
Definition at line 876 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_SWIMMING, origin);
 }
References BOTLIB_AAS_SWIMMING.
Referenced by BotGetLongTermGoal(), and BotReachedGoal().
trap_AAS_Time()
float trap_AAS_Time (void)
Definition at line 784 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AAS_TIME);
     return fi.f;
 }
References BOTLIB_AAS_TIME, floatint_t::f, and floatint_t::i.
Referenced by BotAIStartFrame().
trap_AAS_TraceAreas()
int trap_AAS_TraceAreas (vec3_t start, vec3_t end, int * areas, vec3_t * points, int maxareas)
Definition at line 801 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_TRACE_AREAS, start, end, areas, points, maxareas);
 }
References BOTLIB_AAS_TRACE_AREAS.
Referenced by BotFuncButtonActivateGoal(), BotGoalForBSPEntity(), BotPointAreaNum(), and BotTriggerMultipleActivateGoal().
trap_AAS_ValueForBSPEpairKey()
int trap_AAS_ValueForBSPEpairKey (int ent, char * key, char * value, int size)
Definition at line 826 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_VALUE_FOR_BSP_EPAIR_KEY, ent, key, value, size);
 }
References BOTLIB_AAS_VALUE_FOR_BSP_EPAIR_KEY.
Referenced by BotFuncButtonActivateGoal(), BotFuncDoorActivateGoal(), BotGetActivateGoal(), BotGoalForBSPEntity(), BotPrintActivateGoalInfo(), BotSetupDeathmatchAI(), and BotTriggerMultipleActivateGoal().
trap_AAS_VectorForBSPEpairKey()
int trap_AAS_VectorForBSPEpairKey (int ent, char * key, vec3_t v)
Definition at line 831 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_VECTOR_FOR_BSP_EPAIR_KEY, ent, key, v);
 }
References BOTLIB_AAS_VECTOR_FOR_BSP_EPAIR_KEY.
Referenced by BotGetActivateGoal(), and BotGoalForBSPEntity().
trap_AdjustAreaPortalState()
void trap_AdjustAreaPortalState (gentity_t * ent, qboolean open)
Adjusts the state of a portal connecting two areas.
Set "open" to true to allow visibility through the portal and false to block visibility. This is normally used to adjust visibility when opening and closing doors. When the door is open; "open" is set true and entities are visible through the door, when the door is closed; "open" is set false and trap_InPVS will not see entities through the door. See Use_BinaryMover in the game source for an example.
Parameters
ent Entity to adjust.
open State to adjust to.
Definition at line 528 of file g_syscalls.c.
 {
     syscall(G_ADJUST_AREA_PORTAL_STATE, ent, open);
 }
References G_ADJUST_AREA_PORTAL_STATE.
Referenced by Reached_BinaryMover(), and Use_BinaryMover().
trap_AreasConnected()
qboolean trap_AreasConnected (int area1, int area2)
This functions tests whether or not the areas (presumably leaf nodes of the bsp tree) are adjacent physically.
FIXME: the values of area1 and area2 are unknown, however.
Parameters
area1 First area to test.
area2 Second area to test.
Returns
Definition at line 541 of file g_syscalls.c.
 {
     return syscall(G_AREAS_CONNECTED, area1, area2);
 }
References G_AREAS_CONNECTED.
trap_Argc()
int trap_Argc (void)
Whenever a client issues a console command it can have arguments passed with it.
Returns
The number of arguments identically to the argc found in C programs with this prototype for main: int main(int argc, char **argv).
Definition at line 101 of file cg_syscalls.c.
 {
     return syscall(CG_ARGC);
 }
trap_Args()
void trap_Args (char * buffer, int bufferLength)
Definition at line 111 of file cg_syscalls.c.
 {
     syscall(CG_ARGS, buffer, bufferLength);
 }
References buffer, and CG_ARGS.
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
This will fill the buffer pointed to by buffer with an argument to a client command where n is the argument to return.
0 is the command itself, 1 is the first argument and so on... Very similiar to char **argv in a C program.
Parameters
n The argument number to return.
buffer A point to a buffer to fill.
bufferLength The size of the buffer.
Definition at line 106 of file cg_syscalls.c.
 {
     syscall(CG_ARGV, n, buffer, bufferLength);
 }
trap_BotAddAvoidSpot()
void trap_BotAddAvoidSpot (int movestate, vec3_t origin, float radius, int type)
Definition at line 1302 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_ADD_AVOID_SPOT, movestate, origin, PASSFLOAT(radius), type);
 }
References BOTLIB_AI_ADD_AVOID_SPOT, and PASSFLOAT().
Referenced by BotCheckForGrenades(), and BotCheckSnapshot().
trap_BotAllocateClient()
int trap_BotAllocateClient (void)
Allocates a free client slot and returns the client number.
Also marks the client as bot in the engine (arg2 will be 1 when a GAME_CLIENT_CONNECT message is dispatched to vmMain for this client).
On failure, -1 is returned.
Definition at line 620 of file g_syscalls.c.
 {
     return syscall(G_BOT_ALLOCATE_CLIENT);
 }
References G_BOT_ALLOCATE_CLIENT.
Referenced by G_AddBot().
trap_BotAllocChatState()
int trap_BotAllocChatState (void)
Definition at line 1048 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_CHAT_STATE);
 }
References BOTLIB_AI_ALLOC_CHAT_STATE.
Referenced by BotAISetupClient().
trap_BotAllocGoalState()
int trap_BotAllocGoalState (int state)
Definition at line 1287 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_GOAL_STATE, state);
 }
References BOTLIB_AI_ALLOC_GOAL_STATE.
Referenced by BotAISetupClient().
trap_BotAllocMoveState()
int trap_BotAllocMoveState (void)
Definition at line 1343 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_MOVE_STATE);
 }
References BOTLIB_AI_ALLOC_MOVE_STATE.
Referenced by BotAISetupClient().
trap_BotAllocWeaponState()
int trap_BotAllocWeaponState (void)
Definition at line 1373 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_WEAPON_STATE);
 }
References BOTLIB_AI_ALLOC_WEAPON_STATE.
Referenced by BotAISetupClient().
trap_BotAvoidGoalTime()
float trap_BotAvoidGoalTime (int goalstate, int number)
Definition at line 1240 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AI_AVOID_GOAL_TIME, goalstate, number);
     return fi.f;
 }
References BOTLIB_AI_AVOID_GOAL_TIME, floatint_t::f, and floatint_t::i.
trap_BotChatLength()
int trap_BotChatLength (int chatstate)
Definition at line 1095 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHAT_LENGTH, chatstate);
 }
References BOTLIB_AI_CHAT_LENGTH.
trap_BotChooseBestFightWeapon()
int trap_BotChooseBestFightWeapon (int weaponstate, int * inventory)
Definition at line 1358 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHOOSE_BEST_FIGHT_WEAPON, weaponstate, inventory);
 }
References BOTLIB_AI_CHOOSE_BEST_FIGHT_WEAPON.
Referenced by BotChooseWeapon().
trap_BotChooseLTGItem()
int trap_BotChooseLTGItem (int goalstate, vec3_t origin, int * inventory, int travelflags)
Definition at line 1205 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHOOSE_LTG_ITEM, goalstate, origin, inventory, travelflags);
 }
References BOTLIB_AI_CHOOSE_LTG_ITEM.
Referenced by BotGetItemLongTermGoal().
trap_BotChooseNBGItem()
int trap_BotChooseNBGItem (int goalstate, vec3_t origin, int * inventory, int travelflags, void * ltg, float maxtime)
Definition at line 1210 of file g_syscalls.c.
References BOTLIB_AI_CHOOSE_NBG_ITEM, and PASSFLOAT().
Referenced by BotGoForAir(), and BotNearbyGoal().
trap_BotDumpAvoidGoals()
void trap_BotDumpAvoidGoals (int goalstate)
Definition at line 1180 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_DUMP_AVOID_GOALS, goalstate);
 }
References BOTLIB_AI_DUMP_AVOID_GOALS.
Referenced by BotDeathmatchAI().
trap_BotDumpGoalStack()
void trap_BotDumpGoalStack (int goalstate)
Definition at line 1185 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_DUMP_GOAL_STACK, goalstate);
 }
References BOTLIB_AI_DUMP_GOAL_STACK.
Referenced by BotDeathmatchAI().
trap_BotEmptyGoalStack()
void trap_BotEmptyGoalStack (int goalstate)
Definition at line 1175 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_EMPTY_GOAL_STACK, goalstate);
 }
References BOTLIB_AI_EMPTY_GOAL_STACK.
Referenced by AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
trap_BotEnterChat()
void trap_BotEnterChat (int chatstate, int client, int sendto)
Definition at line 1100 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_ENTER_CHAT, chatstate, client, sendto);
 }
References BOTLIB_AI_ENTER_CHAT.
Referenced by AIEnter_Intermission(), AINode_Respawn(), AINode_Stand(), BotAIShutdownClient(), BotChatTest(), BotGetLongTermGoal(), BotLongTermGoal(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_Dismiss(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_TaskPreference(), BotMatch_WhatAreYouDoing(), BotMatch_WhereAreYou(), BotMatch_WhichTeam(), BotSayTeamOrderAlways(), BotTeamAI(), BotVoiceChat_Camp(), BotVoiceChat_FollowMe(), BotVoiceChat_Patrol(), BotVoiceChat_WantOnDefense(), BotVoiceChat_WantOnOffense(), and BotVoiceChat_WhoIsLeader().
trap_BotFindMatch()
int trap_BotFindMatch (char * str, void * match, unsigned long int context)
Definition at line 1115 of file g_syscalls.c.
References BOTLIB_AI_FIND_MATCH.
Referenced by BotAddressedToBot(), BotCheckConsoleMessages(), BotGetPatrolWaypoints(), BotGetTime(), BotMatch_HelpAccompany(), and BotMatchMessage().
trap_BotFreeCharacter()
void trap_BotFreeCharacter (int character)
Definition at line 1014 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_CHARACTER, character);
 }
References BOTLIB_AI_FREE_CHARACTER.
Referenced by BotAIShutdownClient().
trap_BotFreeChatState()
void trap_BotFreeChatState (int handle)
Definition at line 1053 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_CHAT_STATE, handle);
 }
References BOTLIB_AI_FREE_CHAT_STATE.
Referenced by BotAISetupClient(), and BotAIShutdownClient().
trap_BotFreeClient()
void trap_BotFreeClient (int clientNum)
Definition at line 625 of file g_syscalls.c.
 {
     syscall(G_BOT_FREE_CLIENT, clientNum);
 }
References G_BOT_FREE_CLIENT.
Referenced by G_AddBot().
trap_BotFreeGoalState()
void trap_BotFreeGoalState (int handle)
Definition at line 1292 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_GOAL_STATE, handle);
 }
References BOTLIB_AI_FREE_GOAL_STATE.
Referenced by BotAISetupClient(), and BotAIShutdownClient().
trap_BotFreeItemWeights()
void trap_BotFreeItemWeights (int goalstate)
Definition at line 1267 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_ITEM_WEIGHTS, goalstate);
 }
References BOTLIB_AI_FREE_ITEM_WEIGHTS.
trap_BotFreeMoveState()
void trap_BotFreeMoveState (int handle)
Definition at line 1348 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_MOVE_STATE, handle);
 }
References BOTLIB_AI_FREE_MOVE_STATE.
Referenced by BotAIShutdownClient().
trap_BotFreeWeaponState()
void trap_BotFreeWeaponState (int weaponstate)
Definition at line 1378 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_WEAPON_STATE, weaponstate);
 }
References BOTLIB_AI_FREE_WEAPON_STATE.
Referenced by BotAISetupClient(), and BotAIShutdownClient().
trap_BotGetChatMessage()
void trap_BotGetChatMessage (int chatstate, char * buf, int size)
Definition at line 1105 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_GET_CHAT_MESSAGE, chatstate, buf, size);
 }
References BOTLIB_AI_GET_CHAT_MESSAGE.
Referenced by BotSayTeamOrder(), and BotSayTeamOrderAlways().
trap_BotGetLevelItemGoal()
int trap_BotGetLevelItemGoal (int index, char * classname, void * goal)
Definition at line 1225 of file g_syscalls.c.
References BOTLIB_AI_GET_LEVEL_ITEM_GOAL.
Referenced by BotDontAvoid(), BotGetItemTeamGoal(), BotNearestVisibleItem(), BotSetupAlternativeRouteGoals(), and BotSetupDeathmatchAI().
trap_BotGetMapLocationGoal()
int trap_BotGetMapLocationGoal (char * name, void * goal)
Definition at line 1235 of file g_syscalls.c.
References BOTLIB_AI_GET_MAP_LOCATION_GOAL.
trap_BotGetNextCampSpotGoal()
int trap_BotGetNextCampSpotGoal (int num, void * goal)
Definition at line 1230 of file g_syscalls.c.
References BOTLIB_AI_GET_NEXT_CAMP_SPOT_GOAL.
Referenced by BotWantsToCamp().
trap_BotGetSecondGoal()
int trap_BotGetSecondGoal (int goalstate, void * goal)
Definition at line 1200 of file g_syscalls.c.
References BOTLIB_AI_GET_SECOND_GOAL.
Referenced by AINode_Seek_NBG().
trap_BotGetServerCommand()
int trap_BotGetServerCommand (int clientNum, char * message, int size)
Definition at line 759 of file g_syscalls.c.
 {
     return syscall(BOTLIB_GET_CONSOLE_MESSAGE, clientNum, message, size);
 }
References BOTLIB_GET_CONSOLE_MESSAGE.
Referenced by BotAI().
trap_BotGetSnapshotEntity()
int trap_BotGetSnapshotEntity (int clientNum, int sequence)
Definition at line 754 of file g_syscalls.c.
 {
     return syscall(BOTLIB_GET_SNAPSHOT_ENTITY, clientNum, sequence);
 }
References BOTLIB_GET_SNAPSHOT_ENTITY.
Referenced by BotAI_GetSnapshotEntity().
trap_BotGetTopGoal()
int trap_BotGetTopGoal (int goalstate, void * goal)
Definition at line 1195 of file g_syscalls.c.
References BOTLIB_AI_GET_TOP_GOAL.
Referenced by AIEnter_Seek_LTG(), AIEnter_Seek_NBG(), AINode_Battle_NBG(), AINode_Seek_NBG(), BotGetItemLongTermGoal(), BotGoForAir(), and BotSetInfoConfigString().
trap_BotGetWeaponInfo()
void trap_BotGetWeaponInfo (int weaponstate, int weapon, void * weaponinfo)
Definition at line 1363 of file g_syscalls.c.
References BOTLIB_AI_GET_WEAPON_INFO.
Referenced by BotAimAtEnemy(), and BotCheckAttack().
trap_BotGoalName()
void trap_BotGoalName (int number, char * name, int size)
Definition at line 1190 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_GOAL_NAME, number, name, size);
 }
References BOTLIB_AI_GOAL_NAME.
Referenced by AIEnter_Seek_LTG(), AIEnter_Seek_NBG(), BotGetLongTermGoal(), BotMatch_WhatAreYouDoing(), BotNearestVisibleItem(), BotReportStatus(), and BotSetInfoConfigString().
trap_BotInitialChat()
void trap_BotInitialChat (int chatstate, char * type, int mcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 1078 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_INITIAL_CHAT, chatstate, type, mcontext, var0, var1, var2, var3, var4, var5, var6, var7);
 }
References BOTLIB_AI_INITIAL_CHAT.
Referenced by BotAI_BotInitialChat().
trap_BotInitLevelItems()
void trap_BotInitLevelItems (void)
Definition at line 1252 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_INIT_LEVEL_ITEMS);
 }
References BOTLIB_AI_INIT_LEVEL_ITEMS.
trap_BotInitMoveState()
void trap_BotInitMoveState (int handle, void * initmove)
Definition at line 1353 of file g_syscalls.c.
References BOTLIB_AI_INIT_MOVE_STATE.
Referenced by BotSetupForMovement().
trap_BotInterbreedGoalFuzzyLogic()
void trap_BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
Definition at line 1272 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_INTERBREED_GOAL_FUZZY_LOGIC, parent1, parent2, child);
 }
References BOTLIB_AI_INTERBREED_GOAL_FUZZY_LOGIC.
Referenced by BotInterbreedBots().
trap_BotItemGoalInVisButNotVisible()
int trap_BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, void * goal)
Definition at line 1220 of file g_syscalls.c.
References BOTLIB_AI_ITEM_GOAL_IN_VIS_BUT_NOT_VISIBLE.
Referenced by BotGetLongTermGoal(), and BotReachedGoal().
trap_BotLibDefine()
int trap_BotLibDefine (char * string)
Definition at line 729 of file g_syscalls.c.
 {
     return syscall(BOTLIB_PC_ADD_GLOBAL_DEFINE, string);
 }
References BOTLIB_PC_ADD_GLOBAL_DEFINE.
Referenced by BotInitLibrary().
trap_BotLibLoadMap()
int trap_BotLibLoadMap (const char * mapname)
Definition at line 739 of file g_syscalls.c.
 {
     return syscall(BOTLIB_LOAD_MAP, mapname);
 }
References BOTLIB_LOAD_MAP.
Referenced by BotAILoadMap().
trap_BotLibSetup()
int trap_BotLibSetup (void)
Definition at line 709 of file g_syscalls.c.
 {
     return syscall(BOTLIB_SETUP);
 }
References BOTLIB_SETUP.
Referenced by BotInitLibrary().
trap_BotLibShutdown()
int trap_BotLibShutdown (void)
Definition at line 714 of file g_syscalls.c.
 {
     return syscall(BOTLIB_SHUTDOWN);
 }
References BOTLIB_SHUTDOWN.
Referenced by BotAIShutdown().
trap_BotLibStartFrame()
int trap_BotLibStartFrame (float time)
Definition at line 734 of file g_syscalls.c.
 {
     return syscall(BOTLIB_START_FRAME, PASSFLOAT(time));
 }
References BOTLIB_START_FRAME, and PASSFLOAT().
Referenced by BotAIStartFrame().
trap_BotLibTest()
int trap_BotLibTest (int parm0, char * parm1, vec3_t parm2, vec3_t parm3)
Definition at line 749 of file g_syscalls.c.
 {
     return syscall(BOTLIB_TEST, parm0, parm1, parm2, parm3);
 }
References BOTLIB_TEST.
trap_BotLibUpdateEntity()
int trap_BotLibUpdateEntity (int ent, void * bue)
Definition at line 744 of file g_syscalls.c.
References BOTLIB_UPDATENTITY.
Referenced by BotAIStartFrame().
trap_BotLibVarGet()
int trap_BotLibVarGet (char * var_name, char * value, int size)
Definition at line 724 of file g_syscalls.c.
 {
     return syscall(BOTLIB_LIBVAR_GET, var_name, value, size);
 }
References BOTLIB_LIBVAR_GET.
trap_BotLibVarSet()
int trap_BotLibVarSet (char * var_name, char * value)
Definition at line 719 of file g_syscalls.c.
 {
     return syscall(BOTLIB_LIBVAR_SET, var_name, value);
 }
References BOTLIB_LIBVAR_SET.
Referenced by BotAISetupClient(), BotAIStartFrame(), BotCheckConsoleMessages(), BotInitLibrary(), and BotInterbreeding().
trap_BotLoadCharacter()
int trap_BotLoadCharacter (char * charfile, float skill)
Definition at line 1009 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_CHARACTER, charfile, PASSFLOAT(skill));
 }
References BOTLIB_AI_LOAD_CHARACTER, and PASSFLOAT().
Referenced by BotAISetupClient().
trap_BotLoadChatFile()
int trap_BotLoadChatFile (int chatstate, char * chatfile, char * chatname)
Definition at line 1135 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_CHAT_FILE, chatstate, chatfile, chatname);
 }
References BOTLIB_AI_LOAD_CHAT_FILE.
Referenced by BotAISetupClient().
trap_BotLoadItemWeights()
int trap_BotLoadItemWeights (int goalstate, char * filename)
Definition at line 1262 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_ITEM_WEIGHTS, goalstate, filename);
 }
References BOTLIB_AI_LOAD_ITEM_WEIGHTS.
Referenced by BotAISetupClient().
trap_BotLoadWeaponWeights()
int trap_BotLoadWeaponWeights (int weaponstate, char * filename)
Definition at line 1368 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_WEAPON_WEIGHTS, weaponstate, filename);
 }
References BOTLIB_AI_LOAD_WEAPON_WEIGHTS.
Referenced by BotAISetupClient().
trap_BotMatchVariable()
void trap_BotMatchVariable (void * match, int variable, char * buf, int size)
Definition at line 1120 of file g_syscalls.c.
References BOTLIB_AI_MATCH_VARIABLE.
Referenced by BotAddressedToBot(), BotCheckConsoleMessages(), BotGetPatrolWaypoints(), BotGetTime(), BotMatch_AttackEnemyBase(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_CTF(), BotMatch_DefendKeyArea(), BotMatch_Dismiss(), BotMatch_EnterGame(), BotMatch_FormationSpace(), BotMatch_GetFlag(), BotMatch_GetItem(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_NewLeader(), BotMatch_Patrol(), BotMatch_ReturnFlag(), BotMatch_RushBase(), BotMatch_StartTeamLeaderShip(), BotMatch_StopTeamLeaderShip(), BotMatch_Suicide(), BotMatch_TaskPreference(), BotMatch_WhatAreYouDoing(), and BotMatch_WhereAreYou().
trap_BotMoveInDirection()
int trap_BotMoveInDirection (int movestate, vec3_t dir, float speed, int type)
Definition at line 1313 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_MOVE_IN_DIRECTION, movestate, dir, PASSFLOAT(speed), type);
 }
References BOTLIB_AI_MOVE_IN_DIRECTION, and PASSFLOAT().
Referenced by BotAIBlocked(), BotAttackMove(), BotGetLongTermGoal(), and BotRandomMove().
trap_BotMovementViewTarget()
int trap_BotMovementViewTarget (int movestate, void * goal, int travelflags, float lookahead, vec3_t target)
Definition at line 1333 of file g_syscalls.c.
References BOTLIB_AI_MOVEMENT_VIEW_TARGET, and PASSFLOAT().
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
trap_BotMoveToGoal()
void trap_BotMoveToGoal (void * result, int movestate, void * goal, int travelflags)
Definition at line 1307 of file g_syscalls.c.
References BOTLIB_AI_MOVE_TO_GOAL.
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), and BotAttackMove().
trap_BotMutateGoalFuzzyLogic()
void trap_BotMutateGoalFuzzyLogic (int goalstate, float range)
Definition at line 1282 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_MUTATE_GOAL_FUZZY_LOGIC, goalstate, PASSFLOAT(range));
 }
References BOTLIB_AI_MUTATE_GOAL_FUZZY_LOGIC, and PASSFLOAT().
Referenced by BotAISetupClient(), and BotInterbreedBots().
trap_BotNextConsoleMessage()
int trap_BotNextConsoleMessage (int chatstate, void * cm)
Definition at line 1068 of file g_syscalls.c.
References BOTLIB_AI_NEXT_CONSOLE_MESSAGE, and cm.
Referenced by BotCheckConsoleMessages().
trap_BotNumConsoleMessages()
int trap_BotNumConsoleMessages (int chatstate)
Definition at line 1073 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_NUM_CONSOLE_MESSAGE, chatstate);
 }
References BOTLIB_AI_NUM_CONSOLE_MESSAGE.
Referenced by BotCheckConsoleMessages().
trap_BotNumInitialChats()
int trap_BotNumInitialChats (int chatstate, char * type)
Definition at line 1084 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_NUM_INITIAL_CHATS, chatstate, type);
 }
References BOTLIB_AI_NUM_INITIAL_CHATS.
Referenced by BotChat_Death(), BotChat_Kill(), and BotChatTest().
trap_BotPopGoal()
void trap_BotPopGoal (int goalstate)
Definition at line 1170 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_POP_GOAL, goalstate);
 }
References BOTLIB_AI_POP_GOAL.
Referenced by AINode_Battle_NBG(), AINode_Seek_NBG(), BotGetItemLongTermGoal(), and BotGoForAir().
trap_BotPredictVisiblePosition()
int trap_BotPredictVisiblePosition (vec3_t origin, int areanum, void * goal, int travelflags, vec3_t target)
Definition at line 1338 of file g_syscalls.c.
References BOTLIB_AI_PREDICT_VISIBLE_POSITION.
Referenced by BotAimAtEnemy().
trap_BotPushGoal()
void trap_BotPushGoal (int goalstate, void * goal)
Definition at line 1165 of file g_syscalls.c.
References BOTLIB_AI_PUSH_GOAL.
Referenced by BotGoForAir().
trap_BotQueueConsoleMessage()
void trap_BotQueueConsoleMessage (int chatstate, int type, char * message)
Definition at line 1058 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_QUEUE_CONSOLE_MESSAGE, chatstate, type, message);
 }
References BOTLIB_AI_QUEUE_CONSOLE_MESSAGE.
Referenced by BotAI(), and BotSayTeamOrderAlways().
trap_BotReachabilityArea()
int trap_BotReachabilityArea (vec3_t origin, int testground)
Definition at line 1328 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_REACHABILITY_AREA, origin, testground);
 }
References BOTLIB_AI_REACHABILITY_AREA.
trap_BotRemoveConsoleMessage()
void trap_BotRemoveConsoleMessage (int chatstate, int handle)
Definition at line 1063 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_REMOVE_CONSOLE_MESSAGE, chatstate, handle);
 }
References BOTLIB_AI_REMOVE_CONSOLE_MESSAGE.
Referenced by BotCheckConsoleMessages().
trap_BotRemoveFromAvoidGoals()
void trap_BotRemoveFromAvoidGoals (int goalstate, int number)
Definition at line 1160 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_REMOVE_FROM_AVOID_GOALS, goalstate, number);
 }
References BOTLIB_AI_REMOVE_FROM_AVOID_GOALS.
Referenced by BotDontAvoid().
trap_BotReplaceSynonyms()
void trap_BotReplaceSynonyms (char * string, unsigned long int context)
Definition at line 1130 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_REPLACE_SYNONYMS, string, context);
 }
References BOTLIB_AI_REPLACE_SYNONYMS.
Referenced by BotCheckConsoleMessages().
trap_BotReplyChat()
int trap_BotReplyChat (int chatstate, char * message, int mcontext, int vcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 1089 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_REPLY_CHAT, chatstate, message, mcontext, vcontext, var0, var1, var2, var3, var4, var5, var6, var7);
 }
References BOTLIB_AI_REPLY_CHAT.
Referenced by BotCheckConsoleMessages().
trap_BotResetAvoidGoals()
void trap_BotResetAvoidGoals (int goalstate)
Definition at line 1155 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_AVOID_GOALS, goalstate);
 }
References BOTLIB_AI_RESET_AVOID_GOALS.
Referenced by AIEnter_Respawn(), BotGetItemLongTermGoal(), BotGoForAir(), and BotResetState().
trap_BotResetAvoidReach()
void trap_BotResetAvoidReach (int movestate)
Definition at line 1318 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_AVOID_REACH, movestate);
 }
References BOTLIB_AI_RESET_AVOID_REACH.
Referenced by AIEnter_Respawn(), AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), BotGetItemLongTermGoal(), BotGetLongTermGoal(), and BotResetState().
trap_BotResetGoalState()
void trap_BotResetGoalState (int goalstate)
Definition at line 1150 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_GOAL_STATE, goalstate);
 }
References BOTLIB_AI_RESET_GOAL_STATE.
Referenced by AIEnter_Respawn(), and BotResetState().
trap_BotResetLastAvoidReach()
void trap_BotResetLastAvoidReach (int movestate)
Definition at line 1323 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_LAST_AVOID_REACH, movestate);
 }
References BOTLIB_AI_RESET_LAST_AVOID_REACH.
Referenced by AIEnter_Battle_Fight(), AIEnter_Battle_SuicidalFight(), AINode_Battle_Chase(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), and BotGetLongTermGoal().
trap_BotResetMoveState()
void trap_BotResetMoveState (int movestate)
Definition at line 1297 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_MOVE_STATE, movestate);
 }
References BOTLIB_AI_RESET_MOVE_STATE.
Referenced by AIEnter_Respawn(), and BotResetState().
trap_BotResetWeaponState()
void trap_BotResetWeaponState (int weaponstate)
Definition at line 1383 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_WEAPON_STATE, weaponstate);
 }
References BOTLIB_AI_RESET_WEAPON_STATE.
Referenced by BotResetState().
trap_BotSaveGoalFuzzyLogic()
void trap_BotSaveGoalFuzzyLogic (int goalstate, char * filename)
Definition at line 1277 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SAVE_GOAL_FUZZY_LOGIC, goalstate, filename);
 }
References BOTLIB_AI_SAVE_GOAL_FUZZY_LOGIC.
Referenced by BotWriteInterbreeded().
trap_BotSetAvoidGoalTime()
void trap_BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
Definition at line 1247 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SET_AVOID_GOAL_TIME, goalstate, number, PASSFLOAT(avoidtime));
 }
References BOTLIB_AI_SET_AVOID_GOAL_TIME, and PASSFLOAT().
Referenced by BotReachedGoal().
trap_BotSetChatGender()
void trap_BotSetChatGender (int chatstate, int gender)
Definition at line 1140 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SET_CHAT_GENDER, chatstate, gender);
 }
References BOTLIB_AI_SET_CHAT_GENDER.
Referenced by BotAISetupClient(), and BotDeathmatchAI().
trap_BotSetChatName()
void trap_BotSetChatName (int chatstate, char * name, int client)
Definition at line 1145 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SET_CHAT_NAME, chatstate, name, client);
 }
References BOTLIB_AI_SET_CHAT_NAME.
Referenced by BotDeathmatchAI().
trap_BotTouchingGoal()
int trap_BotTouchingGoal (vec3_t origin, void * goal)
Definition at line 1215 of file g_syscalls.c.
References BOTLIB_AI_TOUCHING_GOAL.
Referenced by AINode_Battle_Chase(), AINode_Seek_ActivateEntity(), BotGetLongTermGoal(), and BotReachedGoal().
trap_BotUpdateEntityItems()
void trap_BotUpdateEntityItems (void)
Definition at line 1257 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_UPDATE_ENTITY_ITEMS);
 }
References BOTLIB_AI_UPDATE_ENTITY_ITEMS.
Referenced by BotAIRegularUpdate().
trap_BotUserCommand()
void trap_BotUserCommand (int client, usercmd_t * ucmd)
Definition at line 764 of file g_syscalls.c.
 {
     syscall(BOTLIB_USER_COMMAND, clientNum, ucmd);
 }
References BOTLIB_USER_COMMAND.
Referenced by BotAIStartFrame().
trap_Characteristic_BFloat()
float trap_Characteristic_BFloat (int character, int index, float min, float max)
Definition at line 1026 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AI_CHARACTERISTIC_BFLOAT, character, index, PASSFLOAT(min), PASSFLOAT(max));
     return fi.f;
 }
References BOTLIB_AI_CHARACTERISTIC_BFLOAT, floatint_t::f, floatint_t::i, and PASSFLOAT().
Referenced by AINode_Battle_NBG(), AINode_Battle_Retreat(), BotAimAtEnemy(), BotAISetupClient(), BotAttackMove(), BotCanAndWantsToRocketJump(), BotChangeViewAngles(), BotChat_Death(), BotChat_EndLevel(), BotChat_EnemySuicide(), BotChat_EnterGame(), BotChat_ExitGame(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_HitTalking(), BotChat_Kill(), BotChat_Random(), BotChat_StartLevel(), BotCheckAttack(), BotCheckConsoleMessages(), BotFindEnemy(), BotGetLongTermGoal(), BotGoCamp(), BotMapScripts(), and BotWantsToCamp().
trap_Characteristic_BInteger()
int trap_Characteristic_BInteger (int character, int index, int min, int max)
Definition at line 1038 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHARACTERISTIC_BINTEGER, character, index, min, max);
 }
References BOTLIB_AI_CHARACTERISTIC_BINTEGER.
trap_Characteristic_Float()
float trap_Characteristic_Float (int character, int index)
Definition at line 1019 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AI_CHARACTERISTIC_FLOAT, character, index);
     return fi.f;
 }
References BOTLIB_AI_CHARACTERISTIC_FLOAT, floatint_t::f, and floatint_t::i.
trap_Characteristic_Integer()
int trap_Characteristic_Integer (int character, int index)
Definition at line 1033 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHARACTERISTIC_INTEGER, character, index);
 }
References BOTLIB_AI_CHARACTERISTIC_INTEGER.
trap_Characteristic_String()
void trap_Characteristic_String (int character, int index, char * buf, int size)
Definition at line 1043 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_CHARACTERISTIC_STRING, character, index, buf, size);
 }
References BOTLIB_AI_CHARACTERISTIC_STRING.
Referenced by BotAISetupClient(), and BotDeathmatchAI().
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * cvar, const char * var_name, const char * value, int flags)
This function is used to create a new vmCvar.
It sends all the information to the engine's main database and then it stores a local copy of the data into the vmCvar_t passed as the first argument.
Parameters
cvar A pointer the location in which to store the local data.
var_name A null-terminated string that will be used to set the vmCvar's name field.
value A null-terminated string that will be used to set both the floating point and integer value fields of the vmCvar.
flags ?.
Definition at line 62 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_REGISTER, vmCvar, varName, defaultValue, flags);
 }
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
This function searchs for the name of the vmCvar and stores the value into both the float and integer fields of the corresponding vmCvar entry.
The only way to effectly change the value of a vmCvar is to use this function, the ANSI storage operator only modifies the local buffer and not the "master copy".
Parameters
var_name A null-terminated string containing the name of the vmCvar to set.
value A null-terminated string containing the desired value.
Definition at line 72 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_SET, var_name, value);
 }
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * cvar)
This function first parses out the name of the vmCvar and then searches for the corresponding database entry.
Once it finds the vmCvar it will copy the "master copy" of the vmCvar into the local address provided.
Parameters
cvar A pointer to the vmCvar to update.
Definition at line 67 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_UPDATE, vmCvar);
 }
trap_Cvar_VariableIntegerValue()
int trap_Cvar_VariableIntegerValue (const char * var_name)
This function returns the integer value of var_name that is currently stored in the "master copy".
Parameters
var_name A null-terminated string containing the name of the vmCvar to retrieve a value from.
Returns
The integer value of var_name that is currently stored in the "master copy".
Definition at line 257 of file g_syscalls.c.
 {
     return syscall(G_CVAR_VARIABLE_INTEGER_VALUE, var_name);
 }
References G_CVAR_VARIABLE_INTEGER_VALUE.
Referenced by BotAISetupClient(), BotSetupDeathmatchAI(), G_InitGame(), G_ItemDisabled(), G_LoadBots(), G_RankGameOver(), G_ShutdownGame(), PodiumPlacementThink(), SpawnPodium(), and Svcmd_AddBot_f().
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
This is useful for obtaining cvar contents that are not bound, or cannot be bound, to a vmCvar_t variable in the mod code.
The terminating NULL is attached to the end of the copied string by this trap, guaranteeing buffer holds a null-terminated string. The total number of characters copied, including terminating NULL, fits within the size specified by bufsize, truncating the string if necessary.
A nonexistent cvar provides an empty string. An existing cvar with empty content also provides an empty string. Thus, this trap is not sufficient to determine if a cvar actually exists or not.
This trap does not create a new cvar; to create a new cvar during run-time, you can use trap_Cvar_Set or trap_SendConsoleCommand.
Parameters
var_name name of cvar (console variable).
buffer destination string buffer.
bufsize maximum limit of string buffer.
var_name
buffer
bufsize This is useful for obtaining cvar contents that are not bound, or cannot be bound, to a vmCvar_t variable in the mod code.
The terminating NULL is attached to the end of the copied string by this trap, guaranteeing buffer holds a null-terminated string. The total number of characters copied, including terminating NULL, fits within the size specified by bufsize, truncating the string if necessary.
A nonexistent cvar provides an empty string. An existing cvar with empty content also provides an empty string. Thus, this trap is not sufficient to determine if a cvar actually exists or not.
This trap does not create a new cvar; to create a new cvar during run-time, you can use trap_Cvar_Set or trap_SendConsoleCommand.
Parameters
var_name name of cvar (console variable).
buffer destination string buffer.
bufsize maximum limit of string buffer.
var_name
buffer
bufsize
Definition at line 96 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize);
 }
trap_Cvar_VariableValue()
float trap_Cvar_VariableValue (const char * var_name)
Definition at line 54 of file g_bot.c.
 {
     char buf[128];
     trap_Cvar_VariableStringBuffer(var_name, buf, sizeof(buf));
     return atof(buf);
 }
trap_DebugPolygonCreate()
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
Creates a solid coloured permanent polygon in the renderer (and world) based on the given array of vertices/points.
it returns a reference handle to the polygon as it appears in the renderlist. This function should be disabled, but it may still work.
In Q3 1.31, only a single debug polygon can be displayed at once. Calling trap_DebugPolygonCreate() to draw a second polygon causes none of them to be drawn on the screen. Delete the old polygon before trying to draw the new one.
Parameters
color
numPoints
points
Returns
Definition at line 669 of file g_syscalls.c.
 {
     return syscall(G_DEBUG_POLYGON_CREATE, color, numPoints, points);
 }
References G_DEBUG_POLYGON_CREATE.
Referenced by DebugLine().
trap_DebugPolygonDelete()
void trap_DebugPolygonDelete (int id)
Removes a polygon that was previously created via trap_DebugPolygonCreate.
Parameters
id a value previously returned by trap_DebugPolygonCreate.
Definition at line 679 of file g_syscalls.c.
 {
     syscall(G_DEBUG_POLYGON_DELETE, id);
 }
References G_DEBUG_POLYGON_DELETE.
trap_DropClient()
void trap_DropClient (int clientNum, const char * reason)
This provides a mechanism to unconditionally drop a client from a server via their clientNum (ent->client->ps.clientNum).
The reason is displayed to the client when they are dropped.
Parameters
clientNum The client to drop.
reason The reason for the drop.
Definition at line 299 of file g_syscalls.c.
 {
     syscall(G_DROP_CLIENT, clientNum, reason);
 }
References G_DROP_CLIENT.
Referenced by ClientInactivityTimer(), ClientUserinfoChanged(), and G_BotConnect().
trap_EA_Action()
void trap_EA_Action (int client, int action)
Definition at line 904 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_ACTION, client, action);
 }
References BOTLIB_EA_ACTION.
Referenced by BotGetLongTermGoal(), BotMatch_Suicide(), BotMatch_TaskPreference(), BotRefuseOrder(), BotVoiceChat_WantOnDefense(), and BotVoiceChat_WantOnOffense().
trap_EA_Attack()
void trap_EA_Attack (int client)
Definition at line 919 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_ATTACK, client);
 }
References BOTLIB_EA_ATTACK.
Referenced by AINode_Seek_ActivateEntity(), BotCheckAttack(), BotClearPath(), and BotMapScripts().
trap_EA_Command()
void trap_EA_Command (int client, char * command)
Definition at line 899 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_COMMAND, client, command);
 }
References BOTLIB_EA_COMMAND.
Referenced by BotChat_Death(), BotChat_EndLevel(), BotChat_Kill(), BotChat_Random(), BotChat_StartLevel(), BotMatch_Suicide(), BotVoiceChat(), and BotVoiceChatOnly().
trap_EA_Crouch()
void trap_EA_Crouch (int client)
Definition at line 934 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_CROUCH, client);
 }
References BOTLIB_EA_CROUCH.
Referenced by BotGetLongTermGoal().
trap_EA_DelayedJump()
void trap_EA_DelayedJump (int client)
Definition at line 979 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_DELAYED_JUMP, client);
 }
References BOTLIB_EA_DELAYED_JUMP.
trap_EA_EndRegular()
void trap_EA_EndRegular (int client, float thinktime)
Definition at line 994 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_END_REGULAR, client, PASSFLOAT(thinktime));
 }
References BOTLIB_EA_END_REGULAR, and PASSFLOAT().
trap_EA_Gesture()
void trap_EA_Gesture (int client)
Definition at line 909 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_GESTURE, client);
 }
References BOTLIB_EA_GESTURE.
Referenced by AINode_Seek_LTG(), and BotGetLongTermGoal().
trap_EA_GetInput()
void trap_EA_GetInput (int client, float thinktime, void * input)
Definition at line 999 of file g_syscalls.c.
References BOTLIB_EA_GET_INPUT, and PASSFLOAT().
Referenced by BotUpdateInput().
trap_EA_Jump()
void trap_EA_Jump (int client)
Definition at line 974 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_JUMP, client);
 }
References BOTLIB_EA_JUMP.
trap_EA_Move()
void trap_EA_Move (int client, vec3_t dir, float speed)
Definition at line 984 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE, client, dir, PASSFLOAT(speed));
 }
References BOTLIB_EA_MOVE, and PASSFLOAT().
trap_EA_MoveBack()
void trap_EA_MoveBack (int client)
Definition at line 954 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_BACK, client);
 }
References BOTLIB_EA_MOVE_BACK.
trap_EA_MoveDown()
void trap_EA_MoveDown (int client)
Definition at line 944 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_DOWN, client);
 }
References BOTLIB_EA_MOVE_DOWN.
trap_EA_MoveForward()
void trap_EA_MoveForward (int client)
Definition at line 949 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_FORWARD, client);
 }
References BOTLIB_EA_MOVE_FORWARD.
trap_EA_MoveLeft()
void trap_EA_MoveLeft (int client)
Definition at line 959 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_LEFT, client);
 }
References BOTLIB_EA_MOVE_LEFT.
trap_EA_MoveRight()
void trap_EA_MoveRight (int client)
Definition at line 964 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_RIGHT, client);
 }
References BOTLIB_EA_MOVE_RIGHT.
trap_EA_MoveUp()
void trap_EA_MoveUp (int client)
Definition at line 939 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_UP, client);
 }
References BOTLIB_EA_MOVE_UP.
trap_EA_ResetInput()
void trap_EA_ResetInput (int client)
Definition at line 1004 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_RESET_INPUT, client);
 }
References BOTLIB_EA_RESET_INPUT.
Referenced by BotAI().
trap_EA_Respawn()
void trap_EA_Respawn (int client)
Definition at line 929 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_RESPAWN, client);
 }
References BOTLIB_EA_RESPAWN.
Referenced by AINode_Respawn().
trap_EA_Say()
void trap_EA_Say (int client, char * str)
Definition at line 889 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_SAY, client, str);
 }
References BOTLIB_EA_SAY.
Referenced by BotPrintActivateGoalInfo().
trap_EA_SayTeam()
void trap_EA_SayTeam (int client, char * str)
Definition at line 894 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_SAY_TEAM, client, str);
 }
References BOTLIB_EA_SAY_TEAM.
Referenced by BotGetPatrolWaypoints(), BotMatch_WhoIsTeamLeader(), and BotMatchMessage().
trap_EA_SelectWeapon()
void trap_EA_SelectWeapon (int client, int weapon)
Definition at line 969 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_SELECT_WEAPON, client, weapon);
 }
References BOTLIB_EA_SELECT_WEAPON.
Referenced by BotAI(), and BotChooseWeapon().
trap_EA_Talk()
void trap_EA_Talk (int client)
Definition at line 914 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_TALK, client);
 }
References BOTLIB_EA_TALK.
Referenced by AINode_Respawn(), and AINode_Stand().
trap_EA_Use()
void trap_EA_Use (int client)
Definition at line 924 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_USE, client);
 }
References BOTLIB_EA_USE.
Referenced by BotBattleUseItems(), and BotCheckEvents().
trap_EA_View()
void trap_EA_View (int client, vec3_t viewangles)
Definition at line 989 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_VIEW, client, viewangles);
 }
References BOTLIB_EA_VIEW.
Referenced by BotAimAtEnemy(), and BotChangeViewAngles().
trap_EntitiesInBox()
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int * list, int maxcount)
This fills an array of ints with the entity numbers (ent->s.number) of all the entities currently within the cuboid defined by mins and maxs.
Two vectors - mins and maxs - to be passed in, representing the extents (or farthest points) of an invisible box in the world of Q3.
Parameters
[in] mins The position of the corner of a cuboid.
[in] maxs The position of the opposite corner of this cuboid.
[in,out] list A array of integers(entityNum's (entity indices)) to hold any entities that positively past the test for existence within the boxs boundaries.
[in] maxcount The maximum amount of entities that will be returned by the parameter, list.
Returns
The number of all entities that were successfully found in the box.
Definition at line 590 of file g_syscalls.c.
 {
     return syscall(G_ENTITIES_IN_BOX, mins, maxs, list, maxcount);
 }
References G_ENTITIES_IN_BOX.
Referenced by G_KillBox(), G_MoverPush(), G_RadiusDamage(), G_TouchTriggers(), and SpotWouldTelefrag().
trap_EntityContact()
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
Definition at line 595 of file g_syscalls.c.
 {
     return syscall(G_ENTITY_CONTACT, mins, maxs, ent);
 }
References G_ENTITY_CONTACT.
Referenced by G_TouchTriggers().
trap_Error()
void trap_Error (const char * string)
This is very similar to the trap_Print function with the exception that this will halt execution of the module it is called from.
Usually the user shouldn't call this directly, but using G_Error instead.
Parameters
text Text to be displayed.
Definition at line 50 of file cg_syscalls.c.
 {
     syscall(CG_ERROR, fmt);
     // shut up GCC warning about returning functions, because we know better
     exit(1);
 }
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Closes the file specified by f.
Parameters
f The file to be closed.
Definition at line 131 of file cg_syscalls.c.
 {
     syscall(CG_FS_FCLOSEFILE, f);
 }
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
This opens a file specified by the string qpath and allocates a fileHandle_t (just a typedef int) to that file.
This is then used in subsequent operations involving the file. The fsMode_t enumeration refers to the mode the file is opened in. FS_READ for reading the file. FS_WRITE will create the file qpath if it doesn't exist or 0 length it if it does. FS_APPEND allows writing to the end of an existing file. FS_APPEND_SYNC is similar to FS_APPEND except you can read from the file at the same time.
An int is returned representing the length of the file being opened.
Parameters
qpath The file to be opened.
f Reference to a local fileHandle_t.
mode Mode to open the file in.
Returns
Definition at line 116 of file cg_syscalls.c.
 {
     return syscall(CG_FS_FOPENFILE, qpath, f, mode);
 }
trap_FS_GetFileList()
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
This fills listbuf with a NULL delimited list of all the files in the directory specified by path ending in extension.
The number of files listed is returned.
Parameters
path String reflecting a directory.
extension File extension to list (incluing a leading period).
listbuf Pointer to a buffer to fill.
bufsize Length of the buffer.
Returns
Definition at line 174 of file g_syscalls.c.
 {
     return syscall(G_FS_GETFILELIST, path, extension, listbuf, bufsize);
 }
Referenced by Demos_MenuInit(), G_LoadArenas(), G_LoadBots(), LoadConfig_MenuInit(), PlayerModel_BuildList(), UI_BuildQ3Model_List(), UI_ClearScores(), UI_LoadArenas(), UI_LoadBots(), UI_LoadDemos(), UI_LoadMods(), UI_LoadMovies(), UI_LoadTeams(), UI_Mods_LoadMods(), and UI_TeamArenaExists().
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
This reads len bytes of data from the file specified by f and fills buffer with it.
Parameters
buffer A buffer to fill.
len he amount to read from the file.
f A file handle provided by trap_FS_FOpenFile.
Definition at line 121 of file cg_syscalls.c.
 {
     syscall(CG_FS_READ, buffer, len, f);
 }
trap_FS_Seek()
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
Definition at line 136 of file cg_syscalls.c.
 {
     return syscall(CG_FS_SEEK, f, offset, origin);
 }
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
This writes len bytes of data from buffer to the file specified by f.
Parameters
buffer A buffer to read from.
len The amount to write to the file.
f A file handle provided by trap_FS_FOpenFile.
Definition at line 126 of file cg_syscalls.c.
 {
     syscall(CG_FS_WRITE, buffer, len, f);
 }
trap_GeneticParentsAndChildSelection()
int trap_GeneticParentsAndChildSelection (int numranks, float * ranks, int * parent1, int * parent2, int * child)
Definition at line 1388 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_GENETIC_PARENTS_AND_CHILD_SELECTION, numranks, ranks, parent1, parent2, child);
 }
References BOTLIB_AI_GENETIC_PARENTS_AND_CHILD_SELECTION.
Referenced by BotInterbreedBots().
trap_GetConfigstring()
void trap_GetConfigstring (int num, char * buffer, int bufferSize)
This is a server side callback used to get the value of a config string.
It is only used once in the q3 source, by the G_FindConfigstringIndex function which in turn is used by the G_ModelIndex and G_SoundIndex functions.
Parameters
num The config string to be read.
buffer A pointer to a buffer to fill with the config string value.
bufferSize The size of the buffer.
Definition at line 341 of file g_syscalls.c.
 {
     syscall(G_GET_CONFIGSTRING, num, buffer, bufferSize);
 }
References buffer, and G_GET_CONFIGSTRING.
Referenced by BotCheckEvents(), BotFirstClientInRankings(), BotIsFirstInRankings(), BotIsLastInRankings(), BotIsObserver(), BotLastClientInRankings(), BotNumActivePlayers(), BotNumTeamMates(), BotRandomOpponentName(), BotSortTeamMatesByBaseTravelTime(), BotTeamOrders(), BotTeamplayReport(), BotUpdateInfoConfigStrings(), ClientFromName(), ClientName(), ClientOnSameTeamFromName(), ClientSkin(), G_FindConfigstringIndex(), and NumPlayersOnSameTeam().
trap_GetEntityToken()
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
This call fills the buffer pointed to by buffer with all the key/value pairs of every map entity.
The string returned has a very similar format to that of the tail end of a GTKRadiant .map file before it is compiled to a bsp. It is unlikely that a user would ever need to call this since it is handled already in g_spawn.c.
Parameters
buffer A buffer to fill.
bufferSize The size of the buffer.
Returns
Definition at line 821 of file cg_syscalls.c.
 {
     return syscall(CG_GET_ENTITY_TOKEN, buffer, bufferSize);
 }
References buffer, CG_GET_ENTITY_TOKEN, and G_GET_ENTITY_TOKEN.
trap_GetServerinfo()
void trap_GetServerinfo (char * buffer, int bufferSize)
The "server info" string is a backslash delimited list of server variables such as g_gametype and mapname.
Besides the bot code, its only other use in the Q3 source is to print to the value of serverinfo to the logfile.
Parameters
buffer A buffer to fill with the server info.
bufferSize The size of the buffer.
Definition at line 381 of file g_syscalls.c.
 {
     syscall(G_GET_SERVERINFO, buffer, bufferSize);
 }
References buffer, and G_GET_SERVERINFO.
Referenced by BotMapScripts(), BotMapTitle(), G_InitBots(), and G_InitGame().
trap_GetUsercmd()
void trap_GetUsercmd (int clientNum, usercmd_t * cmd)
This function will retrieve the usercmd_t generated by the client portion of the Q3 binary and place it in what it pointed to by cmd.
Parameters
clientNum The clientNum to retreive cmd from.
cmd Pointer to a usercmd_t to fill.
Definition at line 636 of file g_syscalls.c.
 {
     syscall(G_GET_USERCMD, clientNum, cmd);
 }
References G_GET_USERCMD.
Referenced by ClientSpawn(), and ClientThink().
trap_GetUserinfo()
void trap_GetUserinfo (int num, char * buffer, int bufferSize)
Each client has a "user info" string which is a backslash delimited key/value pair for the various options the user can set.
For example, model, skin and weapon colour. trap_GetUserinfo fills the buffer pointed to by *buffer with the userinfo of the client referenced by num. Key values are then retrieved using Info_ValueForKey(buffer, keyname).
Parameters
num clientNum of the userinfo to retrieve.
buffer Pointer to a buffer to fill.
bufferSize Size of the buffer.
Definition at line 356 of file g_syscalls.c.
 {
     syscall(G_GET_USERINFO, num, buffer, bufferSize);
 }
References buffer, and G_GET_USERINFO.
Referenced by BotDeathmatchAI(), BotSetUserInfo(), ClientConnect(), ClientSpawn(), ClientUserinfoChanged(), Cmd_TeamTask_f(), G_BotConnect(), and G_CheckBotSpawn().
trap_InPVS()
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
Two points can return true, but not be visible to each other due to detail brushes, curves, etc. A return value of false guarantees that the points can not see each other. Normally used to test if two entities can potentially see each other, point1 would be the currentOrigin of the first entitiy and point2 the currentOrigin of the second entity. This function relies on the Potentially Visible Set, and areaportal data generated during the BSP compiling of a map.
Parameters
p1 Absolute coordinates of point 1.
p2 Absolute coordinates of point 2.
Returns
Definition at line 498 of file g_syscalls.c.
 {
     return syscall(G_IN_PVS, p1, p2);
 }
References G_IN_PVS.
Referenced by Team_FragBonuses(), and Team_GetLocation().
trap_InPVSIgnorePortals()
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
This function does not check areaportals. Points hidden by closed doors (and other areaportals) will still return true.
Parameters
p1 Absolute coordinates of point 1.
p2 Absolute coordinates of point 2.
Returns
Definition at line 512 of file g_syscalls.c.
 {
     return syscall(G_IN_PVS_IGNORE_PORTALS, p1, p2);
 }
References G_IN_PVS_IGNORE_PORTALS.
trap_LinkEntity()
void trap_LinkEntity (gentity_t * ent)
When an entity is "linked" it is subject to all evaluations that the world performs on it.
For example, all linked entities are accounted for when performing a trace. Newly created entities are not linked into the world - they must be explcitly linked using this call. Linking an entity that is already linked into the world has no effect unless the following properties have changed:
Its origin or angles have changed which might cause a change in the entity's PVS (ent->r.currentOrigin is used to calculate the entity's PVS cluster)
Its bounds have changed (again, is used in PVS cluster calculations, and to set abs(min/max))
Its contents have changed (will set ent->s.solid)
Its brush model has changed (again, sets ent->s.solid)
Parameters
ent Entity to be linked.
Definition at line 558 of file g_syscalls.c.
 {
     syscall(G_LINKENTITY, ent);
 }
References G_LINKENTITY.
Referenced by ClientSpawn(), ClientThink_real(), CopyToBodyQue(), FinishSpawningItem(), G_ExplodeMissile(), G_MissileImpact(), G_MoverPush(), G_MoverTeam(), G_RunItem(), G_RunMissile(), G_TempEntity(), G_TryPushingEntity(), G_TryPushingProxMine(), hurt_use(), InitMover(), InitShooter(), LaunchItem(), player_die(), RespawnItem(), SetMoverState(), SP_func_rotating(), SP_misc_model(), SP_misc_portal_camera(), SP_misc_portal_surface(), SP_target_speaker(), SP_trigger_hurt(), SP_trigger_multiple(), SP_trigger_push(), SP_trigger_teleport(), SpawnModelOnVictoryPad(), SpawnPlatTrigger(), SpawnPodium(), target_laser_think(), TeleportPlayer(), Think_SpawnNewDoorTrigger(), Touch_Item(), and weapon_railgun_fire().
trap_LocateGameData()
void trap_LocateGameData (gentity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * clients, int sizeofGClient)
It would be very unusual for a mod programmer to want to call this - especially with parameters other than those outlined above.
Its purpose it to notify the Q3 binary when new entities are created. In the Q3 source it is used twice - once on level load and in G_Spawn where it is called whenever an entity is created.
Parameters
gEnts Usually level.gentities.
numGEntities Usually level.num_entities.
sizeofGEntity_t Usually sizeof(gentity_t).
clients Usually &level.clients;[0].ps.
sizeofGClient Usually sizeof(level.clients[0]).
Definition at line 286 of file g_syscalls.c.
 {
     syscall(G_LOCATE_GAME_DATA, gEnts, numGEntities, sizeofGEntity_t, clients, sizeofGClient);
 }
References G_LOCATE_GAME_DATA.
Referenced by G_InitGame(), and G_Spawn().
trap_Milliseconds()
int trap_Milliseconds (void)
Returns the number of milliseconds that have elapsed since Quake 3 was executed.
A Quake 3, multi-platform version of the Win32 function timeGetTime, which also returns the number of milliseconds since the program was executed.
Returns
The number of milliseconds that have elapsed since Quake 3 was executed.
Definition at line 57 of file cg_syscalls.c.
 {
     return syscall(CG_MILLISECONDS);
 }
trap_PointContents()
int trap_PointContents (const vec3_t point, int passEntityNum)
This trap call returns the CONTENTS_* of a specific point in space - it is commonly used to avoid spawning items in CONTENTS_NODROP areas.
The second parameter specifies an entityNum (ent->s.number) which is ignored when evaluating the contents for a point.
Parameters
point The point in space to be examined.
passEntityNum An entityNum to be ignored.
Returns
The CONTENTS_* of the specific point in space.
Definition at line 480 of file g_syscalls.c.
 {
     return syscall(G_POINT_CONTENTS, point, passEntityNum);
 }
References G_POINT_CONTENTS.
Referenced by BotGetLongTermGoal(), BotRoamGoal(), BotValidChatPosition(), ClientThink_real(), CopyToBodyQue(), G_RunItem(), player_die(), and SpectatorThink().
trap_Print()
void trap_Print (const char * string)
trap_Print prints the string pointed to by fmt to the Q3 Console.
This should not usually be used directly by the user; the G_Printf function provides its functionality and more.
Parameters
text Text to be displayed.
Definition at line 45 of file cg_syscalls.c.
 {
     syscall(CG_PRINT, fmt);
 }
trap_RealTime()
int trap_RealTime (qtime_t * qtime)
Returns current system time and date at server.
Parameters
qtime Point in time - look at q_shared.h qtime_t for details.
Returns
The current system time and date at server.
Definition at line 725 of file cg_syscalls.c.
 {
     return syscall(CG_REAL_TIME, qtime);
 }
trap_SendConsoleCommand()
void trap_SendConsoleCommand (int exec_when, const char * text)
This call adds a command to the command buffer i.e.
so that the programmer may issue server commands that would normally need to be entered into the console. exec_when takes an element of the cbufExec_t enumeration:
Description of the EXEC_* values are described in q_shared.h.
In general, EXEC_APPEND is the most common use, simulating the user typing in the command. The string is stored to a buffer (appended) until a game frame is completed, then the engine will examine the buffered strings to run.
EXEC_NOW is a bad idea, as it can lead to an infinite loop: EXEC_NOW causes an immediate jump into engine space, which then jumps back to QVM/mod space to execute commands, which could lead to an immediate jump right back to engine space, which would lead to... and so on.
Useless examples: trap_SendConsoleCommand(EXEC_APPEND, "team free"); trap_SendConsoleCommand(EXEC_APPEND, "say Vini vidi vici.; quit");.
Parameters
exec_when When to execute this command: EXEC_NOW, EXEC_INSERT, EXEC_APPEND.
text The command to be executed.
Definition at line 206 of file g_syscalls.c.
 {
     syscall(G_SEND_CONSOLE_COMMAND, exec_when, text);
 }
References G_SEND_CONSOLE_COMMAND.
trap_SendServerCommand()
void trap_SendServerCommand (int clientNum, const char * text)
This has the same effect as typing a command in a clients console for evaluation by the server.
This includes the commands evaluated in g_cmds.c. Its main use in the Q3 source is to print information to a specific client's console via the "print" command. Passing -1 as the clientNum sends the command to every client.
Parameters
clientNum The client that the command is being sent from.
text The command to be sent.
Definition at line 313 of file g_syscalls.c.
 {
     syscall(G_SEND_SERVER_COMMAND, clientNum, text);
 }
References G_SEND_SERVER_COMMAND.
Referenced by __attribute__(), BroadcastTeamChange(), CheatsOk(), CheckExitRules(), CheckTeamVote(), CheckVote(), ClientBegin(), ClientCommand(), ClientConnect(), ClientInactivityTimer(), ClientNumberFromString(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_God_f(), Cmd_LevelShot_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_Vote_f(), Cmd_Where_f(), ConsoleCommand(), DeathmatchScoreboardMessage(), G_RankRunFrame(), G_SayTo(), G_TeamCommand(), G_UpdateCvars(), PrintTeam(), SetTeam(), Svcmd_AddBot_f(), TeamplayInfoMessage(), and Use_Target_Print().
trap_SetBrushModel()
void trap_SetBrushModel (gentity_t * ent, const char * name)
This function does several special things to an entity which should not be done any other way.
It sets the clipping bounds of the entity to use the collision map contained in the brush model specified. Brush models have a complex collision map which is far more detailed than a regular bounding-box (doors, plats, movers etc). The mins and maxes of a brush-model entity may differ wildly from reality.
It sets the entity to have the SOLID_BMODEL type which serves to alert clients that the modelindex used to render this entity is not in the regular list, but instead is the index into the cgs.inlineDrawModel list which is built on start-up. This list is zero-indexed from *1 and therefore does not contain the map itself. Another method must be used to get the client to render the map a second time.
It sets the "bmodel" member of the entityShared_t structure to 1 (entityShared_t is the "r" member of the gentity_t structure). This allows a simple method of checking if an entity uses a brush model.
There is nothing to prevent an entity from using a brush model which is not built into the map (not inline). However this ability is not used anywhere in Q3A or Q3TA. The map compilers have special command-line switches to build BSPs which are externally lit and designed to be stand-alone models. If this is attempted the cgame QVM will require special code (a bit-flag or similar) to allow it to know the difference between a brush-model index that is inline and one that is external.
And thats' the last function in the game list!!.
Parameters
ent The entity to apply the collision map to.
name The name of the brush model. If the model is inline (built into the map) it will "*0", "*1", "*n". These names are generated by the map compiler and cannot be changed. "*0" is always the map itself. If the model is external to the map then it is the filename of the BSP (another map is technically valid as a stand-alone model though it is not externally lit and all external surfaces are backfaced culled).
Definition at line 418 of file g_syscalls.c.
 {
     syscall(G_SET_BRUSH_MODEL, ent, name);
 }
References G_SET_BRUSH_MODEL.
Referenced by InitTrigger(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_static(), and SP_func_train().
trap_SetConfigstring()
void trap_SetConfigstring (int num, const char * string)
The Q3 Engine provides a mechanism for communicating data from the server to the client via config strings.
This is (presumably) an array of strings within the engine that are indexed by the CS_* values in bg_public.c. This trap call sets one of these strings to a value. Config strings should usually be used to communicate complex data that changes relatively rarely.
Parameters
num The config string to set.
string The value to set it to.
Definition at line 327 of file g_syscalls.c.
 {
     syscall(G_SET_CONFIGSTRING, num, string);
 }
References G_SET_CONFIGSTRING.
Referenced by BotSetInfoConfigString(), CalculateRanks(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), G_FindConfigstringIndex(), G_InitGame(), G_RemapTeamShaders(), G_UseTargets(), LogExit(), SaveRegisteredItems(), SP_worldspawn(), target_location_linkup(), and Team_SetFlagStatus().
trap_SetUserinfo()
void trap_SetUserinfo (int num, const char * buffer)
This does the opposite to trap_GetUserinfo and sets a userinfo string for a user.
However, it is not used much in the Q3 source, where config strings seem to be the prefered method to transfer userinfo to the client.
Parameters
num clientNum of userinfo to change.
buffer Userinfo string to set.
Definition at line 369 of file g_syscalls.c.
 {
     syscall(G_SET_USERINFO, num, buffer);
 }
References buffer, and G_SET_USERINFO.
Referenced by BotDeathmatchAI(), BotSetUserInfo(), Cmd_TeamTask_f(), and G_AddBot().
trap_SnapVector()
void trap_SnapVector (float * v)
This simply removes the fractional part of each axis of v - a form of "snap to grid".
Its purpose is to save network bandwidth by exploiting the fact that delta compression will only transmit the changes in state of a struct. A changing vector will change less frequently if only the integral part is taken into account.
Parameters
v Vector to snap.
Definition at line 730 of file cg_syscalls.c.
 {
     syscall(CG_SNAPVECTOR, v);
 }
References CG_SNAPVECTOR, and G_SNAPVECTOR.
trap_StringContains()
int trap_StringContains (char * str1, char * str2, int casesensitive)
Definition at line 1110 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_STRING_CONTAINS, str1, str2, casesensitive);
 }
References BOTLIB_AI_STRING_CONTAINS.
trap_Trace()
void trap_Trace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
This function is used to trace from one position to another in the BSP tree and store the results in a trace_t structure.
The results consist of the following information (where tr is a variable of type trace_t):
tr.allsolid: If this is qtrue, then the area (or some part of it) between the mins and maxs is inside a solid (a brush).
tr.contents: The contents mask of the plane that the trace hit.
tr.endpos: Position where the trace ended.
tr.entityNum: Entity number of the entity that the trace hit. If it hit solid geometry then this will equal ENTITYNUM_WORLD.
tr.fraction: This is the fraction of the vector between start and end where the trace ended. Therefore if this is less than 1.0 the trace hit something.
tr.plane: Information about the plane that was hit (most notably the surface normal) stored in a cplane_t structure.
tr.startsolid: If this is qtrue, then the trace started in a solid (brush).
tr.surfaceFlags: surfaceflags of the surface that was hit (look in surfaceflags.h at the SURF_* constants to see the which ones there are).
If the mins and maxs are NULL then the trace is treated as purely linear from point to point.
If mins and maxs are defined however a bounding box trace is performed whereby rather than a point the entire bounding box is traced so that it is possible to detect the collision between solid entities. For example, tracing directly downwards onto a floor with mins and maxs set to { -15, -15, -15 } and { 15, 15, 15 } respectively starting at some point above the floor will result in a trace_t with an endpoint 15 units from the floor.
Parameters
results Pointer to a variable of type trace_t where the result of the trace will be stored.
start Vector representing the starting position of the trace.
mins Vector representing the mins of the bounding box the trace will have.
maxs Vector representing the maxs of the bounding box the trace will have.
end Vector representing the end position of the trace (it's destination).
passEntityNum The trace will not collide against the entity with this number (usually set to the entity number of the entity that initiated the trace so it won't collide against itself).
contentmask The content mask it should collide against. Use any of the MASK_ or CONTENTS_ constants. You can logical OR several of them together if needed.
Definition at line 456 of file g_syscalls.c.
 {
     syscall(G_TRACE, results, start, mins, maxs, end, passEntityNum, contentmask);
 }
References G_TRACE.
Referenced by BotAI_Trace(), Bullet_Fire(), CanDamage(), CheckGauntletAttack(), ClientThink_real(), FinishSpawningItem(), G_CheckProxMinePosition(), G_RunItem(), G_RunMissile(), G_TestEntityPosition(), Pickup_Powerup(), ShotgunPellet(), SpectatorThink(), target_laser_think(), Weapon_LightningFire(), and weapon_railgun_fire().
trap_UnifyWhiteSpaces()
void trap_UnifyWhiteSpaces (char * string)
Definition at line 1125 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_UNIFY_WHITE_SPACES, string);
 }
References BOTLIB_AI_UNIFY_WHITE_SPACES.
Referenced by BotCheckConsoleMessages().
trap_UnlinkEntity()
void trap_UnlinkEntity (gentity_t * ent)
When an entity is "unlinked" from the world it remains in memory, but ceases to exist from the point of view of the world.
This is useful for temporarily deleting an entity or when performing major alterations to an entity's fields. Unlinking an entity that is already unlinked has no effect.
Parameters
ent Entity to be unlinked.
Definition at line 571 of file g_syscalls.c.
 {
     syscall(G_UNLINKENTITY, ent);
 }
References G_UNLINKENTITY.
Referenced by BodySink(), ClientBegin(), ClientDisconnect(), CopyToBodyQue(), G_FreeEntity(), G_MoverPush(), G_RunFrame(), hurt_use(), SP_trigger_hurt(), SpectatorThink(), target_laser_off(), TeleportPlayer(), Use_Target_Give(), and weapon_railgun_fire().
trigger_teleporter_touch()
void trigger_teleporter_touch (gentity_t * self, gentity_t * other, trace_t * trace)
Definition at line 284 of file g_trigger.c.
 {
     gentity_t* dest;
     if (!other->client) {
         return;
     }
     if (other->client->ps.pm_type == PM_DEAD) {
         return;
     }
     // Spectators only?
     if ((self->spawnflags & 1) &&
         other->client->sess.sessionTeam != TEAM_SPECTATOR) {
         return;
     }
     dest = G_PickTarget(self->target);
     if (!dest) {
         G_Printf("Couldn't find teleporter destination\n");
         return;
     }
     TeleportPlayer(other, dest->s.origin, dest->s.angles);
 }
References entityState_s::angles, gentity_s::client, G_PickTarget(), G_Printf(), entityState_s::origin, PM_DEAD, playerState_s::pm_type, gclient_s::ps, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, TEAM_SPECTATOR, and TeleportPlayer().
Referenced by SP_trigger_teleport().
tv()
float* tv (float x, float y, float z)
Definition at line 280 of file g_utils.c.
 {
     static    int        index;
     static    vec3_t    vecs[8];
     float* v;
     // use an array so that multiple tempvectors won't collide
     // for a while
     v = vecs[index];
     index = (index + 1) & 7;
     v[0] = x;
     v[1] = y;
     v[2] = z;
     return v;
 }
Referenced by GetTickCount(), and Touch_DoorTriggerSpectator().
UpdateTournamentInfo()
void UpdateTournamentInfo (void)
Definition at line 40 of file g_arenas.c.
 {
     int             i;
     gentity_t*      player;
     int             playerClientNum;
     int             n, accuracy, perfect, msglen;
 #ifdef MISSIONPACK
     int score1, score2;
     qboolean won;
 #endif
     char        buf[32];
     char        msg[MAX_STRING_CHARS];
     // find the real player
     player = NULL;
     for (i = 0; i < level.maxclients; i++) {
         player = &g_entities[i];
         if (!player->inuse) {
             continue;
         }
         if (!(player->r.svFlags & SVF_BOT)) {
             break;
         }
     }
     // this should never happen!
     if (!player || i == level.maxclients) {
         return;
     }
     playerClientNum = i;
     CalculateRanks();
     if (level.clients[playerClientNum].sess.sessionTeam == TEAM_SPECTATOR) {
 #ifdef MISSIONPACK
         Com_sprintf(msg, sizeof(msg), "postgame %i %i 0 0 0 0 0 0 0 0 0 0 0", level.numNonSpectatorClients, playerClientNum);
 #else
         Com_sprintf(msg, sizeof(msg), "postgame %i %i 0 0 0 0 0 0", level.numNonSpectatorClients, playerClientNum);
 #endif
     } else {
         if (player->client->accuracy_shots) {
             accuracy = player->client->accuracy_hits * 100 / player->client->accuracy_shots;
         } else {
             accuracy = 0;
         }
 #ifdef MISSIONPACK
         won = qfalse;
         if (g_gametype.integer >= GT_CTF) {
             score1 = level.teamScores[TEAM_RED];
             score2 = level.teamScores[TEAM_BLUE];
             if (level.clients[playerClientNum].sess.sessionTeam == TEAM_RED) {
                 won = (level.teamScores[TEAM_RED] > level.teamScores[TEAM_BLUE]);
             } else {
                 won = (level.teamScores[TEAM_BLUE] > level.teamScores[TEAM_RED]);
             }
         } else {
             if (&level.clients[playerClientNum] == &level.clients[level.sortedClients[0]]) {
                 won = qtrue;
                 score1 = level.clients[level.sortedClients[0]].ps.persistant[PERS_SCORE];
                 score2 = level.clients[level.sortedClients[1]].ps.persistant[PERS_SCORE];
             } else {
                 score2 = level.clients[level.sortedClients[0]].ps.persistant[PERS_SCORE];
                 score1 = level.clients[level.sortedClients[1]].ps.persistant[PERS_SCORE];
             }
         }
         if (won && player->client->ps.persistant[PERS_KILLED] == 0) {
             perfect = 1;
         } else {
             perfect = 0;
         }
         Com_sprintf(msg, sizeof(msg), "postgame %i %i %i %i %i %i %i %i %i %i %i %i %i %i", level.numNonSpectatorClients, playerClientNum, accuracy,
             player->client->ps.persistant[PERS_IMPRESSIVE_COUNT], player->client->ps.persistant[PERS_EXCELLENT_COUNT], player->client->ps.persistant[PERS_DEFEND_COUNT],
             player->client->ps.persistant[PERS_ASSIST_COUNT], player->client->ps.persistant[PERS_GAUNTLET_FRAG_COUNT], player->client->ps.persistant[PERS_SCORE],
             perfect, score1, score2, level.time, player->client->ps.persistant[PERS_CAPTURES]);
 #else
         perfect = (level.clients[playerClientNum].ps.persistant[PERS_RANK] == 0 && player->client->ps.persistant[PERS_KILLED] == 0) ? 1 : 0;
         Com_sprintf(msg, sizeof(msg), "postgame %i %i %i %i %i %i %i %i", level.numNonSpectatorClients, playerClientNum, accuracy,
             player->client->ps.persistant[PERS_IMPRESSIVE_COUNT], player->client->ps.persistant[PERS_EXCELLENT_COUNT],
             player->client->ps.persistant[PERS_GAUNTLET_FRAG_COUNT], player->client->ps.persistant[PERS_SCORE],
             perfect);
 #endif
     }
     msglen = strlen(msg);
     for (i = 0; i < level.numNonSpectatorClients; i++) {
         n = level.sortedClients[i];
         Com_sprintf(buf, sizeof(buf), " %i %i %i", n, level.clients[n].ps.persistant[PERS_RANK], level.clients[n].ps.persistant[PERS_SCORE]);
         msglen += strlen(buf);
         if (msglen >= sizeof(msg)) {
             break;
         }
         strcat(msg, buf);
     }
     trap_SendConsoleCommand(EXEC_APPEND, msg);
 }
References gclient_s::accuracy_hits, gclient_s::accuracy_shots, CalculateRanks(), gentity_s::client, level_locals_t::clients, Com_sprintf(), EXEC_APPEND, g_entities, g_gametype, GT_CTF, gentity_s::inuse, level, MAX_STRING_CHARS, level_locals_t::maxclients, NULL, level_locals_t::numNonSpectatorClients, PERS_ASSIST_COUNT, PERS_CAPTURES, PERS_DEFEND_COUNT, PERS_EXCELLENT_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_IMPRESSIVE_COUNT, PERS_KILLED, PERS_RANK, PERS_SCORE, playerState_s::persistant, gclient_s::ps, qfalse, qtrue, gentity_s::r, gclient_s::sess, clientSession_t::sessionTeam, level_locals_t::sortedClients, SVF_BOT, entityShared_t::svFlags, TEAM_BLUE, TEAM_RED, TEAM_SPECTATOR, level_locals_t::teamScores, level_locals_t::time, and trap_SendConsoleCommand().
Referenced by BeginIntermission().
UseHoldableItem()
void UseHoldableItem (gentity_t * ent)
vectoyaw()
float vectoyaw (const vec3_t vec)
Definition at line 351 of file g_utils.c.
 {
     float    yaw;
     if (vec[YAW] == 0 && vec[PITCH] == 0) {
         yaw = 0;
     } else {
         if (vec[PITCH]) {
             yaw = (atan2(vec[YAW], vec[PITCH]) * 180 / M_PI);
         } else if (vec[YAW] > 0) {
             yaw = 90;
         } else {
             yaw = 270;
         }
         if (yaw < 0) {
             yaw += 360;
         }
     }
     return yaw;
 }
References M_PI, PITCH, and YAW.
Referenced by LookAtKiller(), and SpawnPodium().
vtos()
char* vtos (const vec3_t v)
Definition at line 307 of file g_utils.c.
 {
     static    int        index;
     static    char    str[8][32];
     char* s;
     // use an array so that multiple vtos won't collide
     s = str[index];
     index = (index + 1) & 7;
     Com_sprintf(s, 32, "(%i %i %i)", (int)v[0], (int)v[1], (int)v[2]);
     return s;
 }
References Com_sprintf(), and s.
Referenced by Cmd_Where_f(), FinishSpawningItem(), SP_func_timer(), SP_func_train(), SP_path_corner(), SP_target_speaker(), SP_target_teleporter(), target_laser_start(), and Think_SetupTrainTargets().
Weapon_HookFree()
void Weapon_HookFree (gentity_t * ent)
Definition at line 604 of file g_weapon.c.
 {
     ent->parent->client->hook = NULL;
     ent->parent->client->ps.pm_flags &= ~PMF_GRAPPLE_PULL;
     G_FreeEntity(ent);
 }
References gentity_s::client, G_FreeEntity(), gclient_s::hook, NULL, gentity_s::parent, playerState_s::pm_flags, PMF_GRAPPLE_PULL, and gclient_s::ps.
Referenced by ClientThink_real(), fire_grapple(), and player_die().
Weapon_HookThink()
void Weapon_HookThink (gentity_t * ent)
Definition at line 611 of file g_weapon.c.
 {
     if (ent->enemy) {
         vec3_t v, oldorigin;
         VectorCopy(ent->r.currentOrigin, oldorigin);
         v[0] = ent->enemy->r.currentOrigin[0] + (ent->enemy->r.mins[0] + ent->enemy->r.maxs[0]) * 0.5;
         v[1] = ent->enemy->r.currentOrigin[1] + (ent->enemy->r.mins[1] + ent->enemy->r.maxs[1]) * 0.5;
         v[2] = ent->enemy->r.currentOrigin[2] + (ent->enemy->r.mins[2] + ent->enemy->r.maxs[2]) * 0.5;
         SnapVectorTowards(v, oldorigin);    // save net bandwidth
         G_SetOrigin(ent, v);
     }
     VectorCopy(ent->r.currentOrigin, ent->parent->client->ps.grapplePoint);
 }
References gentity_s::client, entityShared_t::currentOrigin, gentity_s::enemy, G_SetOrigin(), playerState_s::grapplePoint, entityShared_t::maxs, entityShared_t::mins, gentity_s::parent, gclient_s::ps, gentity_s::r, SnapVectorTowards(), and VectorCopy.
Referenced by G_MissileImpact().
Variable Documentation
g_allowVote
vmCvar_t g_allowVote
Definition at line 74 of file g_main.c.
Referenced by Cmd_CallTeamVote_f(), and Cmd_CallVote_f().
g_banIPs
vmCvar_t g_banIPs
Definition at line 77 of file g_main.c.
Referenced by G_ProcessIPBans().
g_blood
vmCvar_t g_blood
Definition at line 71 of file g_main.c.
Referenced by body_die(), and player_die().
g_blueteam
vmCvar_t g_blueteam
Referenced by G_RemapTeamShaders().
g_capturelimit
vmCvar_t g_capturelimit
Definition at line 45 of file g_main.c.
Referenced by CheckExitRules().
g_cheats
vmCvar_t g_cheats
Definition at line 54 of file g_main.c.
Referenced by CheatsOk(), and Cmd_SetViewpos_f().
g_cubeTimeout
vmCvar_t g_cubeTimeout
g_debugAlloc
vmCvar_t g_debugAlloc
Definition at line 61 of file g_main.c.
Referenced by G_Alloc().
g_debugDamage
vmCvar_t g_debugDamage
Definition at line 60 of file g_main.c.
Referenced by G_Damage().
g_debugMove
vmCvar_t g_debugMove
Definition at line 59 of file g_main.c.
Referenced by ClientThink_real().
g_dedicated
vmCvar_t g_dedicated
Definition at line 51 of file g_main.c.
Referenced by ConsoleCommand(), G_LogPrintf(), and G_Say().
g_dmflags
vmCvar_t g_dmflags
Definition at line 42 of file g_main.c.
Referenced by ClientEvents(), and ClientThink_real().
g_doWarmup
vmCvar_t g_doWarmup
Definition at line 67 of file g_main.c.
Referenced by SP_worldspawn().
g_enableBreath
vmCvar_t g_enableBreath
g_enableDust
vmCvar_t g_enableDust
g_entities
gentity_t g_entities[MAX_GENTITIES]
The global entity list in game.
Definition at line 38 of file g_main.c.
Referenced by __attribute__(), AddTournamentPlayer(), BeginIntermission(), BotAI_GetClientState(), BotAI_GetEntityState(), BotAIStartFrame(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_HitTalking(), BotChatTest(), BotCheckAttack(), BotCheckEvents(), BotFindEnemy(), BotModelMinsMaxs(), BotSetEntityNumForGoal(), BotSetEntityNumForGoalWithActivator(), BotSetEntityNumForGoalWithModel(), Bullet_Fire(), CalculateRanks(), CheatsOk(), CheckGauntletAttack(), CheckIntermissionExit(), CheckTeamLeader(), CheckTeamStatus(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientImpacts(), ClientNumberFromString(), ClientSpawn(), ClientThink(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_God_f(), Cmd_LevelShot_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_Vote_f(), Cmd_Where_f(), CopyToBodyQue(), DeathmatchScoreboardMessage(), FindHumanTeamLeader(), G_CountBotPlayers(), G_CountBotPlayersByName(), G_CountHumanPlayers(), G_Damage(), G_EntitiesFree(), G_ExplodeMissile(), G_Find(), G_FindTeams(), G_InitGame(), G_InitGentity(), G_InitSessionData(), G_KillBox(), G_MissileImpact(), G_MoverPush(), G_RadiusDamage(), G_RankClientDisconnect(), G_RankDamage(), G_RankRunFrame(), G_RankWeaponTime(), G_RemoveRandomBot(), G_RunFrame(), G_Say(), G_SayTo(), G_Spawn(), G_TestEntityPosition(), G_TouchTriggers(), GibEntity(), LogExit(), player_die(), RemoveTournamentLoser(), RemoveTournamentWinner(), SendScoreboardMessageToAllClients(), SetTeam(), ShotgunPellet(), SP_worldspawn(), SpawnModelOnVictoryPad(), SpawnModelsOnVictoryPads(), SpawnPodium(), SpotWouldTelefrag(), StopFollowing(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), target_laser_think(), target_location_linkup(), Team_ForceGesture(), Team_FragBonuses(), Team_TouchOurFlag(), TeamplayInfoMessage(), UpdateTournamentInfo(), Use_Target_Print(), Weapon_LightningFire(), and weapon_railgun_fire().
g_filterBan
vmCvar_t g_filterBan
Definition at line 78 of file g_main.c.
Referenced by G_FilterPacket().
g_forcerespawn
vmCvar_t g_forcerespawn
Definition at line 57 of file g_main.c.
Referenced by ClientThink_real().
g_fraglimit
vmCvar_t g_fraglimit
Definition at line 43 of file g_main.c.
Referenced by CheckExitRules(), and G_RankRunFrame().
g_friendlyFire
vmCvar_t g_friendlyFire
Definition at line 46 of file g_main.c.
Referenced by G_Damage().
g_gametype
vmCvar_t g_gametype
Definition at line 196 of file be_ai_goal.c.
Referenced by AddScore(), BeginIntermission(), BotChooseLTGItem(), BotChooseNBGItem(), BotGetLevelItemGoal(), BotSetupGoalAI(), BotUpdateEntityItems(), CalculateRanks(), CheckAlmostCapture(), CheckExitRules(), CheckIntermissionExit(), CheckTournament(), ClearRegisteredItems(), ClientBegin(), ClientConnect(), ClientDisconnect(), ClientEvents(), ClientSpawn(), ClientUserinfoChanged(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_LevelShot_f(), Cmd_Team_f(), ExitLevel(), FireWeapon(), G_AddBot(), G_CheckBotSpawn(), G_CheckMinimumPlayers(), G_CheckTeamItems(), G_Damage(), G_InitBots(), G_InitGame(), G_InitSessionData(), G_InitWorldSession(), G_RankRunFrame(), G_RegisterCvars(), G_Say(), G_SayTo(), G_SpawnGEntityFromSpawnVars(), G_WriteSessionData(), LaunchItem(), LogExit(), OnSameTeam(), Pickup_Powerup(), Pickup_Team(), Pickup_Weapon(), player_die(), ScoreIsTied(), SetTeam(), Svcmd_AbortPodium_f(), Team_CheckHurtCarrier(), Team_FragBonuses(), Team_InitGame(), Team_ResetFlags(), Team_SetFlagStatus(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), TossClientItems(), Touch_Item(), and UpdateTournamentInfo().
g_gravity
vmCvar_t g_gravity
Definition at line 53 of file g_main.c.
Referenced by AimAtTarget(), ClientThink_real(), and SP_func_pendulum().
g_inactivity
vmCvar_t g_inactivity
Definition at line 58 of file g_main.c.
Referenced by ClientInactivityTimer(), and ClientSpawn().
g_knockback
vmCvar_t g_knockback
Definition at line 55 of file g_main.c.
Referenced by G_Damage().
g_localTeamPref
vmCvar_t g_localTeamPref
Definition at line 84 of file g_main.c.
Referenced by G_InitSessionData().
g_maxclients
vmCvar_t g_maxclients
Definition at line 49 of file g_main.c.
Referenced by CheckExitRules(), CheckIntermissionExit(), CheckTeamStatus(), ExitLevel(), G_CheckMinimumPlayers(), G_CountBotPlayers(), G_CountBotPlayersByName(), G_CountHumanPlayers(), G_InitGame(), G_RemoveRandomBot(), Team_FragBonuses(), Team_TouchOurFlag(), and TeamplayInfoMessage().
g_maxGameClients
vmCvar_t g_maxGameClients
Definition at line 50 of file g_main.c.
Referenced by G_InitSessionData(), and SetTeam().
g_motd
vmCvar_t g_motd
Definition at line 64 of file g_main.c.
Referenced by SP_worldspawn().
g_needpass
vmCvar_t g_needpass
Definition at line 48 of file g_main.c.
g_obeliskHealth
vmCvar_t g_obeliskHealth
g_obeliskRegenAmount
vmCvar_t g_obeliskRegenAmount
g_obeliskRegenPeriod
vmCvar_t g_obeliskRegenPeriod
g_obeliskRespawnDelay
vmCvar_t g_obeliskRespawnDelay
g_password
vmCvar_t g_password
Definition at line 47 of file g_main.c.
Referenced by CheckCvars(), and ClientConnect().
g_proxMineTimeout
vmCvar_t g_proxMineTimeout
g_quadfactor
vmCvar_t g_quadfactor
Definition at line 56 of file g_main.c.
Referenced by CheckGauntletAttack(), and FireWeapon().
g_rankings
vmCvar_t g_rankings
Definition at line 82 of file g_main.c.
g_redteam
vmCvar_t g_redteam
Referenced by G_RemapTeamShaders().
g_restarted
vmCvar_t g_restarted
Definition at line 68 of file g_main.c.
Referenced by SP_worldspawn().
g_singlePlayer
vmCvar_t g_singlePlayer
Referenced by BeginIntermission(), CheckExitRules(), ClientThink_real(), and LogExit().
g_smoothClients
vmCvar_t g_smoothClients
Definition at line 79 of file g_main.c.
Referenced by ClientEndFrame(), and ClientThink_real().
g_speed
vmCvar_t g_speed
Definition at line 52 of file g_main.c.
Referenced by ClientThink_real().
g_synchronousClients
vmCvar_t g_synchronousClients
Definition at line 65 of file g_main.c.
Referenced by ClientEndFrame(), ClientThink(), and G_RunClient().
g_teamAutoJoin
vmCvar_t g_teamAutoJoin
Definition at line 75 of file g_main.c.
Referenced by G_InitSessionData().
g_teamForceBalance
vmCvar_t g_teamForceBalance
Definition at line 76 of file g_main.c.
Referenced by SetTeam().
g_timelimit
vmCvar_t g_timelimit
Definition at line 44 of file g_main.c.
Referenced by CheckExitRules(), and G_RankRunFrame().
g_warmup
vmCvar_t g_warmup
Definition at line 66 of file g_main.c.
Referenced by CheckTournament(), and G_RegisterCvars().
g_weaponRespawn
vmCvar_t g_weaponRespawn
Definition at line 62 of file g_main.c.
Referenced by Pickup_Weapon().
g_weaponTeamRespawn
vmCvar_t g_weaponTeamRespawn
Definition at line 63 of file g_main.c.
Referenced by Pickup_Weapon().
level
level_locals_t level
Definition at line 26 of file g_main.c.
Referenced by AddBotToSpawnQueue(), AddScore(), AddTeamScore(), AddTournamentPlayer(), AddTournamentQueue(), AdjustTournamentScores(), BeginIntermission(), BodySink(), BotEnemyFlagCarrierVisible(), BotFindEnemy(), BotFirstClientInRankings(), BotInitLibrary(), BotIntermission(), BotIsFirstInRankings(), BotIsLastInRankings(), BotLastClientInRankings(), BotMapScripts(), BotModelMinsMaxs(), BotNumActivePlayers(), BotNumTeamMates(), BotRandomOpponentName(), BotSameTeam(), BotSetEntityNumForGoal(), BotSetEntityNumForGoalWithActivator(), BotSetEntityNumForGoalWithModel(), BotSortTeamMatesByBaseTravelTime(), BotTeam(), BotTeamFlagCarrier(), BotTeamFlagCarrierVisible(), BotTeamOrders(), BotTeamplayReport(), BotUpdateInfoConfigStrings(), BotVisibleTeamMatesAndEnemies(), Bullet_Fire(), CalculateRanks(), CelebrateStart(), CheckExitRules(), CheckIntermissionExit(), CheckTeamLeader(), CheckTeamStatus(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientBegin(), ClientCommand(), ClientConnect(), ClientDisconnect(), ClientEndFrame(), ClientEvents(), ClientForString(), ClientFromName(), ClientInactivityTimer(), ClientNumberFromString(), ClientOnSameTeamFromName(), ClientSpawn(), ClientThink(), ClientThink_real(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), Com_Error(), CopyToBodyQue(), DeathmatchScoreboardMessage(), ExitLevel(), FindClientByName(), FindEnemyByName(), FindIntermissionPoint(), FinishSpawningItem(), fire_bfg(), fire_grapple(), fire_grenade(), fire_plasma(), fire_rocket(), func_timer_think(), G_AddEvent(), G_AddSpawnVarToken(), G_BounceItem(), G_BounceMissile(), G_CheckBotSpawn(), G_CheckMinimumPlayers(), G_CountBotPlayers(), G_CountBotPlayersByName(), G_CountHumanPlayers(), G_Damage(), G_EntitiesFree(), G_ExplodeMissile(), G_Find(), G_FindTeams(), G_FreeEntity(), G_InitGame(), G_InitSessionData(), G_InitWorldSession(), G_LogPrintf(), G_MissileImpact(), G_MoverTeam(), G_ParseSpawnVars(), G_RankCapture(), G_RankClientDisconnect(), G_RankDamage(), G_RankFireWeapon(), G_RankGameOver(), G_RankPickupAmmo(), G_RankPickupArmor(), G_RankPickupHealth(), G_RankPickupHoldable(), G_RankPickupPowerup(), G_RankPickupWeapon(), G_RankPlayerDie(), G_RankReward(), G_RankRunFrame(), G_RankUseHoldable(), G_RankUserTeamName(), G_RankWeaponTime(), G_ReadSessionData(), G_RegisterCvars(), G_RemapTeamShaders(), G_RemoveRandomBot(), G_RunClient(), G_RunFrame(), G_RunItem(), G_RunMissile(), G_RunThink(), G_Say(), G_SetClientSound(), G_ShutdownGame(), G_Spawn(), G_SpawnEntitiesFromString(), G_SpawnGEntityFromSpawnVars(), G_SpawnItem(), G_SpawnString(), G_TeamCommand(), G_TempEntity(), G_TouchTriggers(), G_UseTargets(), G_WriteClientSessionData(), G_WriteSessionData(), GibEntity(), GLDSA_CompressedTextureImage2DEXT(), GLDSA_CompressedTextureSubImage2DEXT(), GLDSA_CopyTextureSubImage2DEXT(), GLDSA_NamedFramebufferTexture2DEXT(), GLDSA_TextureImage2DEXT(), GLDSA_TextureSubImage2DEXT(), hurt_touch(), InitBodyQue(), InitShooter(), LaunchItem(), LogExit(), MoveClientToIntermission(), multi_trigger(), NumPlayersOnSameTeam(), P_DamageFeedback(), P_WorldEffects(), PickTeam(), Pickup_Powerup(), player_die(), PodiumPlacementThink(), PrintTeam(), R_RenderSunShadowMaps(), Reached_BinaryMover(), Reached_Train(), RemoveTournamentLoser(), RemoveTournamentWinner(), ReturnToPos1(), ScoreIsTied(), SelectSpectatorSpawnPoint(), SendScoreboardMessageToAllClients(), SetLeader(), SetMoverState(), SetTeam(), ShotgunPellet(), SortRanks(), SP_func_door(), SP_func_timer(), SP_func_train(), SP_misc_portal_surface(), SP_target_laser(), SP_target_location(), SP_target_push(), SP_trigger_always(), SP_trigger_push(), SP_worldspawn(), SpawnModelOnVictoryPad(), SpawnModelsOnVictoryPads(), SpawnPodium(), SpectatorClientEndFrame(), Svcmd_AbortPodium_f(), Svcmd_AddBot_f(), Svcmd_EntityList_f(), Svcmd_ForceTeam_f(), target_laser_think(), target_location_linkup(), Team_CheckHurtCarrier(), Team_FragBonuses(), Team_GetLocation(), Team_TakeFlagSound(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), TeamCount(), TeamLeader(), TeamplayInfoMessage(), Think_BeginMoving(), Think_MatchTeam(), Think_SpawnNewDoorTrigger(), TossClientItems(), Touch_Item(), Touch_Plat(), UI_GetBestScore(), UI_GetCurrentGame(), UI_SetBestScore(), UI_SPArena_Start(), UI_SPLevelMenu(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetMenuArena(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_NextEvent(), UI_SPUnlock_f(), UI_TierCompleted(), unzOpenCurrentFile2(), unzOpenCurrentFile3(), UpdateTournamentInfo(), Use_BinaryMover(), Use_Target_Delay(), Use_target_push(), VM_Debug(), Weapon_LightningFire(), and weapon_railgun_fire().
pmove_fixed
vmCvar_t pmove_fixed
Definition at line 169 of file cg_main.c.
pmove_msec
vmCvar_t pmove_msec
Definition at line 171 of file cg_main.c.