ioquake3 doxygen: C:/entry/dev/ioq3/code/renderercommon/tr_font.c File Reference
tr_font.c File Reference
#include "tr_common.h"
#include "../qcommon/qcommon.h"
Classes
union poor
Macros
#define MAX_FONTS 6
Functions
int readInt (void)
float readFloat (void)
void RE_RegisterFont (const char *fontName, int pointSize, fontInfo_t *font)
void R_InitFreeType (void)
void R_DoneFreeType (void)
Variables
static int registeredFontCount = 0
static fontInfo_t registeredFont [MAX_FONTS]
static int fdOffset
static byte * fdFile
Macro Definition Documentation
MAX_FONTS
#define MAX_FONTS 6
Definition at line 89 of file tr_font.c.
Function Documentation
R_DoneFreeType()
void R_DoneFreeType (void)
Definition at line 552 of file tr_font.c.
{
 #ifdef BUILD_FREETYPE
     if (ftLibrary) {
         FT_Done_FreeType( ftLibrary );
         ftLibrary = NULL;
     }
 #endif
     registeredFontCount = 0;
 }
References NULL, and registeredFontCount.
Referenced by RE_Shutdown().
R_InitFreeType()
void R_InitFreeType (void)
Definition at line 542 of file tr_font.c.
{
 #ifdef BUILD_FREETYPE
     if (FT_Init_FreeType( &ftLibrary )) {
         ri.Printf(PRINT_WARNING, "R_InitFreeType: Unable to initialize FreeType.\n");
     }
 #endif
     registeredFontCount = 0;
 }
References PRINT_WARNING, registeredFontCount, and ri.
Referenced by R_Init().
RE_RegisterFont()
void RE_RegisterFont (const char * fontName, int pointSize, fontInfo_t * font)
Definition at line 333 of file tr_font.c.
{
 #ifdef BUILD_FREETYPE
     FT_Face face;
     int j, k, xOut, yOut, lastStart, imageNumber;
     int scaledSize, newSize, maxHeight, left;
     unsigned char *out, *imageBuff;
     glyphInfo_t *glyph;
     image_t *image;
     qhandle_t h;
     float max;
     float dpi = 72;
     float glyphScale;
 #endif
     void *faceData;
     int i, len;
     char name[1024];
     if (!fontName) {
         ri.Printf(PRINT_ALL, "RE_RegisterFont: called with empty name\n");
         return;
     }
     if (pointSize <= 0) {
         pointSize = 12;
     }
     R_IssuePendingRenderCommands();
     if (registeredFontCount >= MAX_FONTS) {
         ri.Printf(PRINT_WARNING, "RE_RegisterFont: Too many fonts registered already.\n");
         return;
     }
     Com_sprintf(name, sizeof(name), "fonts/fontImage_%i.dat",pointSize);
     for (i = 0; i < registeredFontCount; i++) {
         if (Q_stricmp(name, registeredFont[i].name) == 0) {
             Com_Memcpy(font, &registeredFont[i], sizeof(fontInfo_t));
             return;
         }
     }
     len = ri.FS_ReadFile(name, NULL);
     if (len == sizeof(fontInfo_t)) {
         ri.FS_ReadFile(name, &faceData);
         fdOffset = 0;
         fdFile = faceData;
         for(i=0; i<GLYPHS_PER_FONT; i++) {
             font->glyphs[i].height      = readInt();
             font->glyphs[i].top         = readInt();
             font->glyphs[i].bottom      = readInt();
             font->glyphs[i].pitch       = readInt();
             font->glyphs[i].xSkip       = readInt();
             font->glyphs[i].imageWidth  = readInt();
             font->glyphs[i].imageHeight = readInt();
             font->glyphs[i].s           = readFloat();
             font->glyphs[i].t           = readFloat();
             font->glyphs[i].s2          = readFloat();
             font->glyphs[i].t2          = readFloat();
             font->glyphs[i].glyph       = readInt();
             Q_strncpyz(font->glyphs[i].shaderName, (const char *)&fdFile[fdOffset], sizeof(font->glyphs[i].shaderName));
             fdOffset += sizeof(font->glyphs[i].shaderName);
         }
         font->glyphScale = readFloat();
         Com_Memcpy(font->name, &fdFile[fdOffset], MAX_QPATH);
 //      Com_Memcpy(font, faceData, sizeof(fontInfo_t));
         Q_strncpyz(font->name, name, sizeof(font->name));
         for (i = GLYPH_START; i <= GLYPH_END; i++) {
             font->glyphs[i].glyph = RE_RegisterShaderNoMip(font->glyphs[i].shaderName);
         }
         Com_Memcpy(&registeredFont[registeredFontCount++], font, sizeof(fontInfo_t));
         ri.FS_FreeFile(faceData);
         return;
     }
 #ifndef BUILD_FREETYPE
     ri.Printf(PRINT_WARNING, "RE_RegisterFont: FreeType code not available\n");
 #else
     if (ftLibrary == NULL) {
         ri.Printf(PRINT_WARNING, "RE_RegisterFont: FreeType not initialized.\n");
         return;
     }
     len = ri.FS_ReadFile(fontName, &faceData);
     if (len <= 0) {
         ri.Printf(PRINT_WARNING, "RE_RegisterFont: Unable to read font file '%s'\n", fontName);
         return;
     }
     // allocate on the stack first in case we fail
     if (FT_New_Memory_Face( ftLibrary, faceData, len, 0, &face )) {
         ri.Printf(PRINT_WARNING, "RE_RegisterFont: FreeType, unable to allocate new face.\n");
         return;
     }
     if (FT_Set_Char_Size( face, pointSize << 6, pointSize << 6, dpi, dpi)) {
         ri.Printf(PRINT_WARNING, "RE_RegisterFont: FreeType, unable to set face char size.\n");
         return;
     }
     //*font = &registeredFonts[registeredFontCount++];
     // make a 256x256 image buffer, once it is full, register it, clean it and keep going
     // until all glyphs are rendered
     out = ri.Malloc(256*256);
     if (out == NULL) {
         ri.Printf(PRINT_WARNING, "RE_RegisterFont: ri.Malloc failure during output image creation.\n");
         return;
     }
     Com_Memset(out, 0, 256*256);
     maxHeight = 0;
     for (i = GLYPH_START; i <= GLYPH_END; i++) {
         RE_ConstructGlyphInfo(out, &xOut, &yOut, &maxHeight, face, (unsigned char)i, qtrue);
     }
     xOut = 0;
     yOut = 0;
     i = GLYPH_START;
     lastStart = i;
     imageNumber = 0;
     while ( i <= GLYPH_END + 1 ) {
         if ( i == GLYPH_END + 1 ) {
             // upload/save current image buffer
             xOut = yOut = -1;
         } else {
             glyph = RE_ConstructGlyphInfo(out, &xOut, &yOut, &maxHeight, face, (unsigned char)i, qfalse);
         }
         if (xOut == -1 || yOut == -1)  {
             // ran out of room
             // we need to create an image from the bitmap, set all the handles in the glyphs to this point
             //
             scaledSize = 256*256;
             newSize = scaledSize * 4;
             imageBuff = ri.Malloc(newSize);
             left = 0;
             max = 0;
             for ( k = 0; k < (scaledSize) ; k++ ) {
                 if (max < out[k]) {
                     max = out[k];
                 }
             }
             if (max > 0) {
                 max = 255/max;
             }
             for ( k = 0; k < (scaledSize) ; k++ ) {
                 imageBuff[left++] = 255;
                 imageBuff[left++] = 255;
                 imageBuff[left++] = 255;
                 imageBuff[left++] = ((float)out[k] * max);
             }
             Com_sprintf (name, sizeof(name), "fonts/fontImage_%i_%i.tga", imageNumber++, pointSize);
             if (r_saveFontData->integer) {
                 WriteTGA(name, imageBuff, 256, 256);
             }
             //Com_sprintf (name, sizeof(name), "fonts/fontImage_%i_%i", imageNumber++, pointSize);
             image = R_CreateImage(name, imageBuff, 256, 256, IMGTYPE_COLORALPHA, IMGFLAG_CLAMPTOEDGE, 0 );
             h = RE_RegisterShaderFromImage(name, LIGHTMAP_2D, image, qfalse);
             for (j = lastStart; j < i; j++) {
                 font->glyphs[j].glyph = h;
                 Q_strncpyz(font->glyphs[j].shaderName, name, sizeof(font->glyphs[j].shaderName));
             }
             lastStart = i;
             Com_Memset(out, 0, 256*256);
             xOut = 0;
             yOut = 0;
             ri.Free(imageBuff);
             if ( i == GLYPH_END + 1 )
                 i++;
         } else {
             Com_Memcpy(&font->glyphs[i], glyph, sizeof(glyphInfo_t));
             i++;
         }
     }
     // change the scale to be relative to 1 based on 72 dpi ( so dpi of 144 means a scale of .5 )
     glyphScale = 72.0f / dpi;
     // we also need to adjust the scale based on point size relative to 48 points as the ui scaling is based on a 48 point font
     glyphScale *= 48.0f / pointSize;
     registeredFont[registeredFontCount].glyphScale = glyphScale;
     font->glyphScale = glyphScale;
     Com_Memcpy(&registeredFont[registeredFontCount++], font, sizeof(fontInfo_t));
     if (r_saveFontData->integer) {
         ri.FS_WriteFile(va("fonts/fontImage_%i.dat", pointSize), font, sizeof(fontInfo_t));
     }
     ri.Free(out);
     ri.FS_FreeFile(faceData);
 #endif
 }
References glyphInfo_t::bottom, Com_Memcpy, Com_Memset, Com_sprintf(), fdFile, fdOffset, refimport_t::Free, refimport_t::FS_FreeFile, refimport_t::FS_ReadFile, refimport_t::FS_WriteFile, glyphInfo_t::glyph, GLYPH_END, GLYPH_START, fontInfo_t::glyphs, GLYPHS_PER_FONT, fontInfo_t::glyphScale, glyphInfo_t::height, glyphInfo_t::imageHeight, glyphInfo_t::imageWidth, IMGFLAG_CLAMPTOEDGE, IMGTYPE_COLORALPHA, cvar_s::integer, LIGHTMAP_2D, refimport_t::Malloc, MAX_FONTS, MAX_QPATH, fontInfo_t::name, NULL, glyphInfo_t::pitch, PRINT_ALL, PRINT_WARNING, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, R_CreateImage(), R_IssuePendingRenderCommands(), r_saveFontData, RE_RegisterShaderFromImage(), RE_RegisterShaderNoMip(), readFloat(), readInt(), registeredFont, registeredFontCount, ri, glyphInfo_t::s, glyphInfo_t::s2, glyphInfo_t::shaderName, glyphInfo_t::t, glyphInfo_t::t2, glyphInfo_t::top, va(), and glyphInfo_t::xSkip.
Referenced by GetRefAPI().
readFloat()
float readFloat (void)
Definition at line 316 of file tr_font.c.
{
     poor    me;
 #if defined Q3_BIG_ENDIAN
     me.fred[0] = fdFile[fdOffset+3];
     me.fred[1] = fdFile[fdOffset+2];
     me.fred[2] = fdFile[fdOffset+1];
     me.fred[3] = fdFile[fdOffset+0];
 #elif defined Q3_LITTLE_ENDIAN
     me.fred[0] = fdFile[fdOffset+0];
     me.fred[1] = fdFile[fdOffset+1];
     me.fred[2] = fdFile[fdOffset+2];
     me.fred[3] = fdFile[fdOffset+3];
 #endif
     fdOffset += 4;
     return me.ffred;
 }
References fdFile, fdOffset, poor::ffred, and poor::fred.
Referenced by RE_RegisterFont().
readInt()
int readInt (void)
Definition at line 305 of file tr_font.c.
                     {
     int i = ((unsigned int)fdFile[fdOffset] | ((unsigned int)fdFile[fdOffset+1]<<8) | ((unsigned int)fdFile[fdOffset+2]<<16) | ((unsigned int)fdFile[fdOffset+3]<<24));
     fdOffset += 4;
     return i;
 }
References fdFile, fdOffset, and int().
Referenced by RE_RegisterFont().
Variable Documentation
fdFile
byte* fdFile static
Definition at line 303 of file tr_font.c.
Referenced by RE_RegisterFont(), readFloat(), and readInt().
fdOffset
int fdOffset static
Definition at line 302 of file tr_font.c.
Referenced by RE_RegisterFont(), readFloat(), and readInt().
registeredFont
fontInfo_t registeredFont[MAX_FONTS] static
Definition at line 91 of file tr_font.c.
Referenced by RE_RegisterFont().
registeredFontCount
int registeredFontCount = 0 static
Definition at line 90 of file tr_font.c.
Referenced by R_DoneFreeType(), R_InitFreeType(), and RE_RegisterFont().