ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_team.h File Reference
g_team.h File Reference
Macros
#define CTF_CAPTURE_BONUS 5
#define CTF_TEAM_BONUS 0
#define CTF_RECOVERY_BONUS 1
#define CTF_FLAG_BONUS 0
#define CTF_FRAG_CARRIER_BONUS 2
#define CTF_FLAG_RETURN_TIME 40000
#define CTF_CARRIER_DANGER_PROTECT_BONUS 2
#define CTF_CARRIER_PROTECT_BONUS 1
#define CTF_FLAG_DEFENSE_BONUS 1
#define CTF_RETURN_FLAG_ASSIST_BONUS 1
#define CTF_FRAG_CARRIER_ASSIST_BONUS 2
#define CTF_TARGET_PROTECT_RADIUS 1000
#define CTF_ATTACKER_PROTECT_RADIUS 1000
#define CTF_CARRIER_DANGER_PROTECT_TIMEOUT 8000
#define CTF_FRAG_CARRIER_ASSIST_TIMEOUT 10000
#define CTF_RETURN_FLAG_ASSIST_TIMEOUT 10000
#define CTF_GRAPPLE_SPEED 750
#define CTF_GRAPPLE_PULL_SPEED 750
#define OVERLOAD_ATTACK_BASE_SOUND_TIME 20000
Functions
int OtherTeam (int team)
const char * TeamName (int team)
const char * TeamColorString (int team)
void AddTeamScore (vec3_t origin, int team, int score)
void Team_DroppedFlagThink (gentity_t *ent)
void Team_FragBonuses (gentity_t *targ, gentity_t *inflictor, gentity_t *attacker)
void Team_CheckHurtCarrier (gentity_t *targ, gentity_t *attacker)
void Team_InitGame (void)
Initialize the team-based game.
void Team_ReturnFlag (int team)
void Team_FreeEntity (gentity_t *ent)
gentity_t * SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, qboolean isbot)
gentity_t * Team_GetLocation (gentity_t *ent)
qboolean Team_GetLocationMsg (gentity_t *ent, char *loc, int loclen)
void TeamplayInfoMessage (gentity_t *ent)
void CheckTeamStatus (void)
int Pickup_Team (gentity_t *ent, gentity_t *other)
Macro Definition Documentation
CTF_ATTACKER_PROTECT_RADIUS
#define CTF_ATTACKER_PROTECT_RADIUS 1000
Definition at line 57 of file g_team.h.
CTF_CAPTURE_BONUS
#define CTF_CAPTURE_BONUS 5
Definition at line 41 of file g_team.h.
CTF_CARRIER_DANGER_PROTECT_BONUS
#define CTF_CARRIER_DANGER_PROTECT_BONUS 2
Definition at line 48 of file g_team.h.
CTF_CARRIER_DANGER_PROTECT_TIMEOUT
#define CTF_CARRIER_DANGER_PROTECT_TIMEOUT 8000
Definition at line 59 of file g_team.h.
CTF_CARRIER_PROTECT_BONUS
#define CTF_CARRIER_PROTECT_BONUS 1
Definition at line 49 of file g_team.h.
CTF_FLAG_BONUS
#define CTF_FLAG_BONUS 0
Definition at line 44 of file g_team.h.
CTF_FLAG_DEFENSE_BONUS
#define CTF_FLAG_DEFENSE_BONUS 1
Definition at line 50 of file g_team.h.
CTF_FLAG_RETURN_TIME
#define CTF_FLAG_RETURN_TIME 40000
Definition at line 46 of file g_team.h.
CTF_FRAG_CARRIER_ASSIST_BONUS
#define CTF_FRAG_CARRIER_ASSIST_BONUS 2
Definition at line 52 of file g_team.h.
CTF_FRAG_CARRIER_ASSIST_TIMEOUT
#define CTF_FRAG_CARRIER_ASSIST_TIMEOUT 10000
Definition at line 60 of file g_team.h.
CTF_FRAG_CARRIER_BONUS
#define CTF_FRAG_CARRIER_BONUS 2
Definition at line 45 of file g_team.h.
CTF_GRAPPLE_PULL_SPEED
#define CTF_GRAPPLE_PULL_SPEED 750
Definition at line 64 of file g_team.h.
CTF_GRAPPLE_SPEED
#define CTF_GRAPPLE_SPEED 750
Definition at line 63 of file g_team.h.
CTF_RECOVERY_BONUS
#define CTF_RECOVERY_BONUS 1
Definition at line 43 of file g_team.h.
CTF_RETURN_FLAG_ASSIST_BONUS
#define CTF_RETURN_FLAG_ASSIST_BONUS 1
Definition at line 51 of file g_team.h.
CTF_RETURN_FLAG_ASSIST_TIMEOUT
#define CTF_RETURN_FLAG_ASSIST_TIMEOUT 10000
Definition at line 61 of file g_team.h.
CTF_TARGET_PROTECT_RADIUS
#define CTF_TARGET_PROTECT_RADIUS 1000
Definition at line 56 of file g_team.h.
CTF_TEAM_BONUS
#define CTF_TEAM_BONUS 0
Definition at line 42 of file g_team.h.
OVERLOAD_ATTACK_BASE_SOUND_TIME
#define OVERLOAD_ATTACK_BASE_SOUND_TIME 20000
Definition at line 66 of file g_team.h.
Function Documentation
AddTeamScore()
void AddTeamScore (vec3_t origin, int team, int score)
Definition at line 131 of file g_team.c.
 {
     gentity_t* te;
     te = G_TempEntity(origin, EV_GLOBAL_TEAM_SOUND);
     te->r.svFlags |= SVF_BROADCAST;
     if (team == TEAM_RED) {
         if (level.teamScores[TEAM_RED] + score == level.teamScores[TEAM_BLUE]) {
             //teams are tied sound
             te->s.eventParm = GTS_TEAMS_ARE_TIED;
         } else if (level.teamScores[TEAM_RED] <= level.teamScores[TEAM_BLUE] &&
             level.teamScores[TEAM_RED] + score > level.teamScores[TEAM_BLUE]) {
             // red took the lead sound
             te->s.eventParm = GTS_REDTEAM_TOOK_LEAD;
         } else {
             // red scored sound
             te->s.eventParm = GTS_REDTEAM_SCORED;
         }
     } else {
         if (level.teamScores[TEAM_BLUE] + score == level.teamScores[TEAM_RED]) {
             //teams are tied sound
             te->s.eventParm = GTS_TEAMS_ARE_TIED;
         } else if (level.teamScores[TEAM_BLUE] <= level.teamScores[TEAM_RED] &&
             level.teamScores[TEAM_BLUE] + score > level.teamScores[TEAM_RED]) {
             // blue took the lead sound
             te->s.eventParm = GTS_BLUETEAM_TOOK_LEAD;
         } else {
             // blue scored sound
             te->s.eventParm = GTS_BLUETEAM_SCORED;
         }
     }
     level.teamScores[team] += score;
 }
References EV_GLOBAL_TEAM_SOUND, entityState_s::eventParm, G_TempEntity(), GTS_BLUETEAM_SCORED, GTS_BLUETEAM_TOOK_LEAD, GTS_REDTEAM_SCORED, GTS_REDTEAM_TOOK_LEAD, GTS_TEAMS_ARE_TIED, level, gentity_s::r, gentity_s::s, SVF_BROADCAST, entityShared_t::svFlags, TEAM_BLUE, TEAM_RED, and level_locals_t::teamScores.
Referenced by Team_TouchOurFlag().
CheckTeamStatus()
void CheckTeamStatus (void)
Definition at line 1131 of file g_team.c.
 {
     int i;
     gentity_t* loc, * ent;
     if (level.time - level.lastTeamLocationTime > TEAM_LOCATION_UPDATE_TIME) {
         level.lastTeamLocationTime = level.time;
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->client->pers.connected != CON_CONNECTED) {
                 continue;
             }
             if (ent->inuse && (ent->client->sess.sessionTeam == TEAM_RED || ent->client->sess.sessionTeam == TEAM_BLUE)) {
                 loc = Team_GetLocation(ent);
                 if (loc)
                     ent->client->pers.teamState.location = loc->health;
                 else
                     ent->client->pers.teamState.location = 0;
             }
         }
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->client->pers.connected != CON_CONNECTED) {
                 continue;
             }
             if (ent->inuse) {
                 TeamplayInfoMessage(ent);
             }
         }
     }
 }
References gentity_s::client, CON_CONNECTED, clientPersistant_t::connected, g_entities, g_maxclients, gentity_s::health, vmCvar_t::integer, gentity_s::inuse, level_locals_t::lastTeamLocationTime, level, playerTeamState_t::location, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, TEAM_BLUE, Team_GetLocation(), TEAM_LOCATION_UPDATE_TIME, TEAM_RED, TeamplayInfoMessage(), clientPersistant_t::teamState, and level_locals_t::time.
Referenced by G_RunFrame().
OtherTeam()
int OtherTeam (int team)
Definition at line 72 of file g_team.c.
 {
     if (team == TEAM_RED)
         return TEAM_BLUE;
     else if (team == TEAM_BLUE)
         return TEAM_RED;
     return team;
 }
References TEAM_BLUE, and TEAM_RED.
Referenced by Team_FragBonuses(), and Team_TouchOurFlag().
Pickup_Team()
int Pickup_Team (gentity_t * ent, gentity_t * other)
Definition at line 841 of file g_team.c.
 {
     int team;
     gclient_t* cl = other->client;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_OBELISK) {
         // there are no team items that can be picked up in obelisk
         G_FreeEntity(ent);
         return 0;
     }
     if (g_gametype.integer == GT_HARVESTER) {
         // the only team items that can be picked up in harvester are the cubes
         if (ent->spawnflags != cl->sess.sessionTeam) {
             cl->ps.generic1 += 1;
         }
         G_FreeEntity(ent);
         return 0;
     }
 #endif
     // figure out what team this flag is
     if (strcmp(ent->classname, "team_CTF_redflag") == 0) {
         team = TEAM_RED;
     } else if (strcmp(ent->classname, "team_CTF_blueflag") == 0) {
         team = TEAM_BLUE;
     }
 #ifdef MISSIONPACK
     else if (strcmp(ent->classname, "team_CTF_neutralflag") == 0) {
         team = TEAM_FREE;
     }
 #endif
     else {
         PrintMsg(other, "Don't know what team the flag is on.\n");
         return 0;
     }
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         if (team == TEAM_FREE) {
             return Team_TouchEnemyFlag(ent, other, cl->sess.sessionTeam);
         }
         if (team != cl->sess.sessionTeam) {
             return Team_TouchOurFlag(ent, other, cl->sess.sessionTeam);
         }
         return 0;
     }
 #endif
     // GT_CTF
     if (team == cl->sess.sessionTeam) {
         return Team_TouchOurFlag(ent, other, team);
     }
     return Team_TouchEnemyFlag(ent, other, team);
 }
References cl, gentity_s::classname, gentity_s::client, G_FreeEntity(), g_gametype, GT_1FCTF, GT_HARVESTER, GT_OBELISK, gentity_s::spawnflags, TEAM_BLUE, TEAM_FREE, TEAM_RED, Team_TouchEnemyFlag(), and Team_TouchOurFlag().
Referenced by Touch_Item().
SelectCTFSpawnPoint()
gentity_t* SelectCTFSpawnPoint (team_t team, int teamstate, vec3_t origin, vec3_t angles, qboolean isbot)
Definition at line 1024 of file g_team.c.
 {
     gentity_t* spot;
     spot = SelectRandomTeamSpawnPoint(teamstate, team);
     if (!spot) {
         return SelectSpawnPoint(vec3_origin, origin, angles, isbot);
     }
     VectorCopy(spot->s.origin, origin);
     origin[2] += 9;
     VectorCopy(spot->s.angles, angles);
     return spot;
 }
References entityState_s::angles, entityState_s::origin, gentity_s::s, SelectRandomTeamSpawnPoint(), SelectSpawnPoint(), vec3_origin, and VectorCopy.
Referenced by ClientSpawn().
Team_CheckHurtCarrier()
void Team_CheckHurtCarrier (gentity_t * targ, gentity_t * attacker)
Definition at line 485 of file g_team.c.
 {
     int flag_pw;
     if (!targ->client || !attacker->client)
         return;
     if (targ->client->sess.sessionTeam == TEAM_RED)
         flag_pw = PW_BLUEFLAG;
     else
         flag_pw = PW_REDFLAG;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         flag_pw = PW_NEUTRALFLAG;
     }
 #endif
     // flags
     if (targ->client->ps.powerups[flag_pw] &&
         targ->client->sess.sessionTeam != attacker->client->sess.sessionTeam)
         attacker->client->pers.teamState.lasthurtcarrier = level.time;
     // skulls
     if (targ->client->ps.generic1 &&
         targ->client->sess.sessionTeam != attacker->client->sess.sessionTeam)
         attacker->client->pers.teamState.lasthurtcarrier = level.time;
 }
References gentity_s::client, g_gametype, playerState_s::generic1, GT_1FCTF, playerTeamState_t::lasthurtcarrier, level, gclient_s::pers, playerState_s::powerups, gclient_s::ps, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, gclient_s::sess, clientSession_t::sessionTeam, TEAM_RED, clientPersistant_t::teamState, and level_locals_t::time.
Referenced by G_Damage().
Team_DroppedFlagThink()
void Team_DroppedFlagThink (gentity_t * ent)
Definition at line 666 of file g_team.c.
 {
     int        team = TEAM_FREE;
     if (ent->item->giTag == PW_REDFLAG) {
         team = TEAM_RED;
     } else if (ent->item->giTag == PW_BLUEFLAG) {
         team = TEAM_BLUE;
     } else if (ent->item->giTag == PW_NEUTRALFLAG) {
         team = TEAM_FREE;
     }
     Team_ReturnFlagSound(Team_ResetFlag(team), team);
     // Reset Flag will delete this entity
 }
References gitem_s::giTag, gentity_s::item, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, TEAM_BLUE, TEAM_FREE, TEAM_RED, Team_ResetFlag(), and Team_ReturnFlagSound().
Referenced by Blocked_Door(), and LaunchItem().
Team_FragBonuses()
void Team_FragBonuses (gentity_t * targ, gentity_t * inflictor, gentity_t * attacker)
Definition at line 278 of file g_team.c.
 {
     int i;
     gentity_t* ent;
     int flag_pw, enemy_flag_pw;
     int otherteam;
     int tokens;
     gentity_t* flag, * carrier = NULL;
     char* c;
     vec3_t v1, v2;
     int team;
     // no bonus for fragging yourself or team mates
     if (!targ->client || !attacker->client || targ == attacker || OnSameTeam(targ, attacker))
         return;
     team = targ->client->sess.sessionTeam;
     otherteam = OtherTeam(targ->client->sess.sessionTeam);
     if (otherteam < 0)
         return; // whoever died isn't on a team
     // same team, if the flag at base, check to he has the enemy flag
     if (team == TEAM_RED) {
         flag_pw = PW_REDFLAG;
         enemy_flag_pw = PW_BLUEFLAG;
     } else {
         flag_pw = PW_BLUEFLAG;
         enemy_flag_pw = PW_REDFLAG;
     }
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_1FCTF) {
         flag_pw = PW_NEUTRALFLAG;
         enemy_flag_pw = PW_NEUTRALFLAG;
     }
 #endif
     // did the attacker frag the flag carrier?
     tokens = 0;
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_HARVESTER) {
         tokens = targ->client->ps.generic1;
     }
 #endif
     if (targ->client->ps.powerups[enemy_flag_pw]) {
         attacker->client->pers.teamState.lastfraggedcarrier = level.time;
         AddScore(attacker, targ->r.currentOrigin, CTF_FRAG_CARRIER_BONUS);
         attacker->client->pers.teamState.fragcarrier++;
         PrintMsg(NULL, "%s" S_COLOR_WHITE " fragged %s's flag carrier!\n",
             attacker->client->pers.netname, TeamName(team));
         // the target had the flag, clear the hurt carrier
         // field on the other team
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->inuse && ent->client->sess.sessionTeam == otherteam)
                 ent->client->pers.teamState.lasthurtcarrier = 0;
         }
         return;
     }
     // did the attacker frag a head carrier? other->client->ps.generic1
     if (tokens) {
         attacker->client->pers.teamState.lastfraggedcarrier = level.time;
         AddScore(attacker, targ->r.currentOrigin, CTF_FRAG_CARRIER_BONUS * tokens * tokens);
         attacker->client->pers.teamState.fragcarrier++;
         PrintMsg(NULL, "%s" S_COLOR_WHITE " fragged %s's skull carrier!\n",
             attacker->client->pers.netname, TeamName(team));
         // the target had the flag, clear the hurt carrier
         // field on the other team
         for (i = 0; i < g_maxclients.integer; i++) {
             ent = g_entities + i;
             if (ent->inuse && ent->client->sess.sessionTeam == otherteam)
                 ent->client->pers.teamState.lasthurtcarrier = 0;
         }
         return;
     }
     if (targ->client->pers.teamState.lasthurtcarrier &&
         level.time - targ->client->pers.teamState.lasthurtcarrier < CTF_CARRIER_DANGER_PROTECT_TIMEOUT &&
         !attacker->client->ps.powerups[flag_pw]) {
         // attacker is on the same team as the flag carrier and
         // fragged a guy who hurt our flag carrier
         AddScore(attacker, targ->r.currentOrigin, CTF_CARRIER_DANGER_PROTECT_BONUS);
         attacker->client->pers.teamState.carrierdefense++;
         targ->client->pers.teamState.lasthurtcarrier = 0;
         attacker->client->ps.persistant[PERS_DEFEND_COUNT]++;
         // add the sprite over the player's head
         attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
         attacker->client->ps.eFlags |= EF_AWARD_DEFEND;
         attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
         return;
     }
     // flag and flag carrier area defense bonuses
     // we have to find the flag and carrier entities
 #ifdef MISSIONPACK
     if (g_gametype.integer == GT_OBELISK) {
         // find the team obelisk
         switch (attacker->client->sess.sessionTeam) {
         case TEAM_RED:
             c = "team_redobelisk";
             break;
         case TEAM_BLUE:
             c = "team_blueobelisk";
             break;
         default:
             return;
         }
     } else if (g_gametype.integer == GT_HARVESTER) {
         // find the center obelisk
         c = "team_neutralobelisk";
     } else {
 #endif
         // find the flag
         switch (attacker->client->sess.sessionTeam) {
         case TEAM_RED:
             c = "team_CTF_redflag";
             break;
         case TEAM_BLUE:
             c = "team_CTF_blueflag";
             break;
         default:
             return;
         }
         // find attacker's team's flag carrier
         for (i = 0; i < g_maxclients.integer; i++) {
             carrier = g_entities + i;
             if (carrier->inuse && carrier->client->ps.powerups[flag_pw])
                 break;
             carrier = NULL;
         }
 #ifdef MISSIONPACK
     }
 #endif
     flag = NULL;
     while ((flag = G_Find(flag, FOFS(classname), c)) != NULL) {
         if (!(flag->flags & FL_DROPPED_ITEM))
             break;
     }
     if (!flag)
         return; // can't find attacker's flag
     // ok we have the attackers flag and a pointer to the carrier
     // check to see if we are defending the base's flag
     VectorSubtract(targ->r.currentOrigin, flag->r.currentOrigin, v1);
     VectorSubtract(attacker->r.currentOrigin, flag->r.currentOrigin, v2);
     if (((VectorLength(v1) < CTF_TARGET_PROTECT_RADIUS &&
         trap_InPVS(flag->r.currentOrigin, targ->r.currentOrigin)) ||
         (VectorLength(v2) < CTF_TARGET_PROTECT_RADIUS &&
             trap_InPVS(flag->r.currentOrigin, attacker->r.currentOrigin))) &&
         attacker->client->sess.sessionTeam != targ->client->sess.sessionTeam) {
         // we defended the base flag
         AddScore(attacker, targ->r.currentOrigin, CTF_FLAG_DEFENSE_BONUS);
         attacker->client->pers.teamState.basedefense++;
         attacker->client->ps.persistant[PERS_DEFEND_COUNT]++;
         // add the sprite over the player's head
         attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
         attacker->client->ps.eFlags |= EF_AWARD_DEFEND;
         attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
         return;
     }
     if (carrier && carrier != attacker) {
         VectorSubtract(targ->r.currentOrigin, carrier->r.currentOrigin, v1);
         VectorSubtract(attacker->r.currentOrigin, carrier->r.currentOrigin, v2);
         if (((VectorLength(v1) < CTF_ATTACKER_PROTECT_RADIUS &&
             trap_InPVS(carrier->r.currentOrigin, targ->r.currentOrigin)) ||
             (VectorLength(v2) < CTF_ATTACKER_PROTECT_RADIUS &&
                 trap_InPVS(carrier->r.currentOrigin, attacker->r.currentOrigin))) &&
             attacker->client->sess.sessionTeam != targ->client->sess.sessionTeam) {
             AddScore(attacker, targ->r.currentOrigin, CTF_CARRIER_PROTECT_BONUS);
             attacker->client->pers.teamState.carrierdefense++;
             attacker->client->ps.persistant[PERS_DEFEND_COUNT]++;
             // add the sprite over the player's head
             attacker->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
             attacker->client->ps.eFlags |= EF_AWARD_DEFEND;
             attacker->client->rewardTime = level.time + REWARD_SPRITE_TIME;
             return;
         }
     }
 }
References AddScore(), playerTeamState_t::basedefense, playerTeamState_t::carrierdefense, gentity_s::client, CTF_ATTACKER_PROTECT_RADIUS, CTF_CARRIER_DANGER_PROTECT_BONUS, CTF_CARRIER_DANGER_PROTECT_TIMEOUT, CTF_CARRIER_PROTECT_BONUS, CTF_FLAG_DEFENSE_BONUS, CTF_FRAG_CARRIER_BONUS, CTF_TARGET_PROTECT_RADIUS, entityShared_t::currentOrigin, EF_AWARD_ASSIST, EF_AWARD_CAP, EF_AWARD_DEFEND, EF_AWARD_EXCELLENT, EF_AWARD_GAUNTLET, EF_AWARD_IMPRESSIVE, playerState_s::eFlags, FL_DROPPED_ITEM, gentity_s::flags, FOFS, playerTeamState_t::fragcarrier, g_entities, G_Find(), g_gametype, g_maxclients, playerState_s::generic1, GT_1FCTF, GT_HARVESTER, GT_OBELISK, vmCvar_t::integer, gentity_s::inuse, playerTeamState_t::lastfraggedcarrier, playerTeamState_t::lasthurtcarrier, level, clientPersistant_t::netname, NULL, OnSameTeam(), OtherTeam(), gclient_s::pers, PERS_DEFEND_COUNT, playerState_s::persistant, playerState_s::powerups, gclient_s::ps, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, gentity_s::r, REWARD_SPRITE_TIME, gclient_s::rewardTime, S_COLOR_WHITE, gclient_s::sess, clientSession_t::sessionTeam, TEAM_BLUE, TEAM_RED, TeamName(), clientPersistant_t::teamState, level_locals_t::time, trap_InPVS(), VectorLength(), and VectorSubtract.
Referenced by player_die().
Team_FreeEntity()
void Team_FreeEntity (gentity_t * ent)
Definition at line 646 of file g_team.c.
 {
     if (ent->item->giTag == PW_REDFLAG) {
         Team_ReturnFlag(TEAM_RED);
     } else if (ent->item->giTag == PW_BLUEFLAG) {
         Team_ReturnFlag(TEAM_BLUE);
     } else if (ent->item->giTag == PW_NEUTRALFLAG) {
         Team_ReturnFlag(TEAM_FREE);
     }
 }
References gitem_s::giTag, gentity_s::item, PW_BLUEFLAG, PW_NEUTRALFLAG, PW_REDFLAG, TEAM_BLUE, TEAM_FREE, TEAM_RED, and Team_ReturnFlag().
Referenced by G_RunItem().
Team_GetLocation()
gentity_t* Team_GetLocation (gentity_t * ent)
Definition at line 902 of file g_team.c.
 {
     gentity_t* eloc, * best;
     float            bestlen, len;
     vec3_t            origin;
     best = NULL;
     bestlen = 3 * 8192.0 * 8192.0;
     VectorCopy(ent->r.currentOrigin, origin);
     for (eloc = level.locationHead; eloc; eloc = eloc->nextTrain) {
         len = (origin[0] - eloc->r.currentOrigin[0]) * (origin[0] - eloc->r.currentOrigin[0])
             + (origin[1] - eloc->r.currentOrigin[1]) * (origin[1] - eloc->r.currentOrigin[1])
             + (origin[2] - eloc->r.currentOrigin[2]) * (origin[2] - eloc->r.currentOrigin[2]);
         if (len > bestlen) {
             continue;
         }
         if (!trap_InPVS(origin, eloc->r.currentOrigin)) {
             continue;
         }
         bestlen = len;
         best = eloc;
     }
     return best;
 }
References entityShared_t::currentOrigin, level, level_locals_t::locationHead, gentity_s::nextTrain, NULL, gentity_s::r, trap_InPVS(), and VectorCopy.
Referenced by CheckTeamStatus(), and Team_GetLocationMsg().
Team_GetLocationMsg()
qboolean Team_GetLocationMsg (gentity_t * ent, char * loc, int loclen)
Definition at line 941 of file g_team.c.
 {
     gentity_t* best;
     best = Team_GetLocation(ent);
     if (!best)
         return qfalse;
     if (best->count) {
         if (best->count < 0)
             best->count = 0;
         if (best->count > 7)
             best->count = 7;
         Com_sprintf(loc, loclen, "%c%c%s" S_COLOR_WHITE, Q_COLOR_ESCAPE, best->count + '0', best->message);
     } else
         Com_sprintf(loc, loclen, "%s", best->message);
     return qtrue;
 }
References Com_sprintf(), gentity_s::count, gentity_s::message, Q_COLOR_ESCAPE, qfalse, qtrue, S_COLOR_WHITE, and Team_GetLocation().
Referenced by G_Say().
Team_InitGame()
void Team_InitGame (void)
Initialize the team-based game.
Definition at line 50 of file g_team.c.
 {
     memset(&teamgame, 0, sizeof teamgame);
     switch (g_gametype.integer) {
     case GT_CTF:
         teamgame.redStatus = -1; // Invalid to force update
         Team_SetFlagStatus(TEAM_RED, FLAG_ATBASE);
         teamgame.blueStatus = -1; // Invalid to force update
         Team_SetFlagStatus(TEAM_BLUE, FLAG_ATBASE);
         break;
 #ifdef MISSIONPACK
     case GT_1FCTF:
         teamgame.flagStatus = -1; // Invalid to force update
         Team_SetFlagStatus(TEAM_FREE, FLAG_ATBASE);
         break;
 #endif
     default:
         break;
     }
 }
References teamgame_s::blueStatus, FLAG_ATBASE, teamgame_s::flagStatus, g_gametype, GT_1FCTF, GT_CTF, teamgame_s::redStatus, TEAM_BLUE, TEAM_FREE, TEAM_RED, Team_SetFlagStatus(), and teamgame.
Referenced by G_CheckTeamItems().
Team_ReturnFlag()
void Team_ReturnFlag (int team)
Definition at line 636 of file g_team.c.
 {
     Team_ReturnFlagSound(Team_ResetFlag(team), team);
     if (team == TEAM_FREE) {
         PrintMsg(NULL, "The flag has returned!\n");
     } else {
         PrintMsg(NULL, "The %s flag has returned!\n", TeamName(team));
     }
 }
References NULL, TEAM_FREE, Team_ResetFlag(), Team_ReturnFlagSound(), and TeamName().
Referenced by player_die(), Team_FreeEntity(), and Use_target_remove_powerups().
TeamColorString()
const char* TeamColorString (int team)
Definition at line 92 of file g_team.c.
 {
     if (team == TEAM_RED)
         return S_COLOR_RED;
     else if (team == TEAM_BLUE)
         return S_COLOR_BLUE;
     else if (team == TEAM_SPECTATOR)
         return S_COLOR_YELLOW;
     return S_COLOR_WHITE;
 }
References S_COLOR_BLUE, S_COLOR_RED, S_COLOR_WHITE, S_COLOR_YELLOW, TEAM_BLUE, TEAM_RED, and TEAM_SPECTATOR.
TeamName()
const char* TeamName (int team)
Definition at line 81 of file g_team.c.
 {
     if (team == TEAM_RED)
         return "RED";
     else if (team == TEAM_BLUE)
         return "BLUE";
     else if (team == TEAM_SPECTATOR)
         return "SPECTATOR";
     return "FREE";
 }
References TEAM_BLUE, TEAM_RED, and TEAM_SPECTATOR.
Referenced by Team_FragBonuses(), Team_ReturnFlag(), Team_TouchEnemyFlag(), and Team_TouchOurFlag().
TeamplayInfoMessage()
void TeamplayInfoMessage (gentity_t * ent)
Definition at line 1058 of file g_team.c.
 {
     char        entry[1024];
     char        string[8192];
     int            stringlength;
     int            i, j;
     gentity_t* player;
     int            cnt;
     int            h, a;
     int            clients[TEAM_MAXOVERLAY];
     int            team;
     if (!ent->client->pers.teamInfo)
         return;
     // send team info to spectator for team of followed client
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         if (ent->client->sess.spectatorState != SPECTATOR_FOLLOW
             || ent->client->sess.spectatorClient < 0) {
             return;
         }
         team = g_entities[ent->client->sess.spectatorClient].client->sess.sessionTeam;
     } else {
         team = ent->client->sess.sessionTeam;
     }
     if (team != TEAM_RED && team != TEAM_BLUE) {
         return;
     }
     // figure out what client should be on the display
     // we are limited to 8, but we want to use the top eight players
     // but in client order (so they don't keep changing position on the overlay)
     for (i = 0, cnt = 0; i < g_maxclients.integer && cnt < TEAM_MAXOVERLAY; i++) {
         player = g_entities + level.sortedClients[i];
         if (player->inuse && player->client->sess.sessionTeam == team) {
             clients[cnt++] = level.sortedClients[i];
         }
     }
     // We have the top eight players, sort them by clientNum
     qsort(clients, cnt, sizeof(clients[0]), SortClients);
     // send the latest information on all clients
     string[0] = 0;
     stringlength = 0;
     for (i = 0, cnt = 0; i < g_maxclients.integer && cnt < TEAM_MAXOVERLAY; i++) {
         player = g_entities + i;
         if (player->inuse && player->client->sess.sessionTeam == team) {
             h = player->client->ps.stats[STAT_HEALTH];
             a = player->client->ps.stats[STAT_ARMOR];
             if (h < 0) h = 0;
             if (a < 0) a = 0;
             Com_sprintf(entry, sizeof(entry),
                 " %i %i %i %i %i %i",
                 //                level.sortedClients[i], player->client->pers.teamState.location, h, a,
                 i, player->client->pers.teamState.location, h, a,
                 player->client->ps.weapon, player->s.powerups);
             j = strlen(entry);
             if (stringlength + j >= sizeof(string))
                 break;
             strcpy(string + stringlength, entry);
             stringlength += j;
             cnt++;
         }
     }
     trap_SendServerCommand(ent - g_entities, va("tinfo %i %s", cnt, string));
 }
References a, gentity_s::client, Com_sprintf(), g_entities, g_maxclients, vmCvar_t::integer, gentity_s::inuse, level, playerTeamState_t::location, gclient_s::pers, entityState_s::powerups, gclient_s::ps, gentity_s::s, gclient_s::sess, clientSession_t::sessionTeam, SortClients(), level_locals_t::sortedClients, SPECTATOR_FOLLOW, clientSession_t::spectatorClient, clientSession_t::spectatorState, STAT_ARMOR, STAT_HEALTH, playerState_s::stats, TEAM_BLUE, TEAM_MAXOVERLAY, TEAM_RED, TEAM_SPECTATOR, clientPersistant_t::teamInfo, clientPersistant_t::teamState, trap_SendServerCommand(), va(), and playerState_s::weapon.
Referenced by CheckTeamStatus().