ioquake3 doxygen: C:/entry/dev/ioq3/code/game/ai_vcmd.c File Reference
ai_vcmd.c File Reference
#include "g_local.h"
#include "../botlib/botlib.h"
#include "../botlib/be_aas.h"
#include "../botlib/be_ea.h"
#include "../botlib/be_ai_char.h"
#include "../botlib/be_ai_chat.h"
#include "../botlib/be_ai_gen.h"
#include "../botlib/be_ai_goal.h"
#include "../botlib/be_ai_move.h"
#include "../botlib/be_ai_weap.h"
#include "ai_main.h"
#include "ai_dmq3.h"
#include "ai_chat.h"
#include "ai_cmd.h"
#include "ai_dmnet.h"
#include "ai_team.h"
#include "ai_vcmd.h"
#include "chars.h"
#include "inv.h"
#include "syn.h"
#include "match.h"
#include "../../ui/menudef.h"
Classes
struct voiceCommand_s
Typedefs
typedef struct voiceCommand_s voiceCommand_t
Functions
void BotVoiceChat_GetFlag (bot_state_t *bs, int client, int mode)
void BotVoiceChat_Offense (bot_state_t *bs, int client, int mode)
void BotVoiceChat_Defend (bot_state_t *bs, int client, int mode)
void BotVoiceChat_DefendFlag (bot_state_t *bs, int client, int mode)
void BotVoiceChat_Patrol (bot_state_t *bs, int client, int mode)
void BotVoiceChat_Camp (bot_state_t *bs, int client, int mode)
void BotVoiceChat_FollowMe (bot_state_t *bs, int client, int mode)
void BotVoiceChat_FollowFlagCarrier (bot_state_t *bs, int client, int mode)
void BotVoiceChat_ReturnFlag (bot_state_t *bs, int client, int mode)
void BotVoiceChat_StartLeader (bot_state_t *bs, int client, int mode)
void BotVoiceChat_StopLeader (bot_state_t *bs, int client, int mode)
void BotVoiceChat_WhoIsLeader (bot_state_t *bs, int client, int mode)
void BotVoiceChat_WantOnDefense (bot_state_t *bs, int client, int mode)
void BotVoiceChat_WantOnOffense (bot_state_t *bs, int client, int mode)
void BotVoiceChat_Dummy (bot_state_t *bs, int client, int mode)
int BotVoiceChatCommand (bot_state_t *bs, int mode, char *voiceChat)
Variables
voiceCommand_t voiceCommands []
Typedef Documentation
voiceCommand_t
typedef struct voiceCommand_s voiceCommand_t
Function Documentation
BotVoiceChat_Camp()
void BotVoiceChat_Camp (bot_state_t * bs, int client, int mode)
Definition at line 257 of file ai_vcmd.c.
{
     int areanum;
     aas_entityinfo_t entinfo;
     char netname[MAX_NETNAME];
     //
     bs->teamgoal.entitynum = -1;
     BotEntityInfo(client, &entinfo);
     //if info is valid (in PVS)
     if (entinfo.valid) {
         areanum = BotPointAreaNum(entinfo.origin);
         if (areanum) { // && trap_AAS_AreaReachability(areanum)) {
             //NOTE: just assume the bot knows where the person is
             //if (BotEntityVisible(bs->entitynum, bs->eye, bs->viewangles, 360, client)) {
                 bs->teamgoal.entitynum = client;
                 bs->teamgoal.areanum = areanum;
                 VectorCopy(entinfo.origin, bs->teamgoal.origin);
                 VectorSet(bs->teamgoal.mins, -8, -8, -8);
                 VectorSet(bs->teamgoal.maxs, 8, 8, 8);
             //}
         }
     }
     //if the other is not visible
     if (bs->teamgoal.entitynum < 0) {
         BotAI_BotInitialChat(bs, "whereareyou", EasyClientName(client, netname, sizeof(netname)), NULL);
         trap_BotEnterChat(bs->cs, client, CHAT_TELL);
         return;
     }
     //
     bs->decisionmaker = client;
     bs->ordered = qtrue;
     bs->order_time = FloatTime();
     //set the time to send a message to the team mates
     bs->teammessage_time = FloatTime() + 2 * random();
     //set the ltg type
     bs->ltgtype = LTG_CAMPORDER;
     //get the team goal time
     bs->teamgoal_time = FloatTime() + TEAM_CAMP_TIME;
     //the teammate that requested the camping
     bs->teammate = client;
     //not arrived yet
     bs->arrive_time = 0;
     //
     BotSetTeamStatus(bs);
     // remember last ordered task
     BotRememberLastOrderedTask(bs);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References bot_goal_s::areanum, bot_state_s::arrive_time, BotAI_BotInitialChat(), BotEntityInfo(), BotPointAreaNum(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), CHAT_TELL, bot_state_s::cs, bot_state_s::decisionmaker, EasyClientName(), bot_goal_s::entitynum, FloatTime, LTG_CAMPORDER, bot_state_s::ltgtype, MAX_NETNAME, bot_goal_s::maxs, bot_goal_s::mins, NULL, bot_state_s::order_time, bot_state_s::ordered, bot_goal_s::origin, aas_entityinfo_s::origin, qtrue, random, TEAM_CAMP_TIME, bot_state_s::teamgoal, bot_state_s::teamgoal_time, bot_state_s::teammate, bot_state_s::teammessage_time, trap_BotEnterChat(), aas_entityinfo_s::valid, VectorCopy, and VectorSet.
BotVoiceChat_Defend()
void BotVoiceChat_Defend (bot_state_t * bs, int client, int mode)
Definition at line 172 of file ai_vcmd.c.
{
 #ifdef MISSIONPACK
     if ( gametype == GT_OBELISK || gametype == GT_HARVESTER) {
         //
         switch(BotTeam(bs)) {
             case TEAM_RED: memcpy(&bs->teamgoal, &redobelisk, sizeof(bot_goal_t)); break;
             case TEAM_BLUE: memcpy(&bs->teamgoal, &blueobelisk, sizeof(bot_goal_t)); break;
             default: return;
         }
     }
     else
 #endif
         if (gametype == GT_CTF
 #ifdef MISSIONPACK
             || gametype == GT_1FCTF
 #endif
             ) {
         //
         switch(BotTeam(bs)) {
             case TEAM_RED: memcpy(&bs->teamgoal, &ctf_redflag, sizeof(bot_goal_t)); break;
             case TEAM_BLUE: memcpy(&bs->teamgoal, &ctf_blueflag, sizeof(bot_goal_t)); break;
             default: return;
         }
     }
     else {
         return;
     }
     //
     bs->decisionmaker = client;
     bs->ordered = qtrue;
     bs->order_time = FloatTime();
     //set the time to send a message to the team mates
     bs->teammessage_time = FloatTime() + 2 * random();
     //set the ltg type
     bs->ltgtype = LTG_DEFENDKEYAREA;
     //get the team goal time
     bs->teamgoal_time = FloatTime() + TEAM_DEFENDKEYAREA_TIME;
     //away from defending
     bs->defendaway_time = 0;
     //
     BotSetTeamStatus(bs);
     // remember last ordered task
     BotRememberLastOrderedTask(bs);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), BotTeam(), ctf_blueflag, ctf_redflag, bot_state_s::decisionmaker, bot_state_s::defendaway_time, FloatTime, gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, GT_OBELISK, LTG_DEFENDKEYAREA, bot_state_s::ltgtype, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, TEAM_BLUE, TEAM_DEFENDKEYAREA_TIME, TEAM_RED, bot_state_s::teamgoal, bot_state_s::teamgoal_time, and bot_state_s::teammessage_time.
Referenced by BotVoiceChat_DefendFlag(), and FindHumanTeamLeader().
BotVoiceChat_DefendFlag()
void BotVoiceChat_DefendFlag (bot_state_t * bs, int client, int mode)
Definition at line 225 of file ai_vcmd.c.
{
     BotVoiceChat_Defend(bs, client, mode);
 }
References BotVoiceChat_Defend().
BotVoiceChat_Dummy()
void BotVoiceChat_Dummy (bot_state_t * bs, int client, int mode)
Definition at line 494 of file ai_vcmd.c.
{
 }
BotVoiceChat_FollowFlagCarrier()
void BotVoiceChat_FollowFlagCarrier (bot_state_t * bs, int client, int mode)
Definition at line 367 of file ai_vcmd.c.
{
     int carrier;
     carrier = BotTeamFlagCarrier(bs);
     if (carrier >= 0)
         BotVoiceChat_FollowMe(bs, carrier, mode);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References BotPrintTeamGoal(), BotTeamFlagCarrier(), and BotVoiceChat_FollowMe().
BotVoiceChat_FollowMe()
void BotVoiceChat_FollowMe (bot_state_t * bs, int client, int mode)
Definition at line 313 of file ai_vcmd.c.
{
     int areanum;
     aas_entityinfo_t entinfo;
     char netname[MAX_NETNAME];
     bs->teamgoal.entitynum = -1;
     BotEntityInfo(client, &entinfo);
     //if info is valid (in PVS)
     if (entinfo.valid) {
         areanum = BotPointAreaNum(entinfo.origin);
         if (areanum) { // && trap_AAS_AreaReachability(areanum)) {
             bs->teamgoal.entitynum = client;
             bs->teamgoal.areanum = areanum;
             VectorCopy(entinfo.origin, bs->teamgoal.origin);
             VectorSet(bs->teamgoal.mins, -8, -8, -8);
             VectorSet(bs->teamgoal.maxs, 8, 8, 8);
         }
     }
     //if the other is not visible
     if (bs->teamgoal.entitynum < 0) {
         BotAI_BotInitialChat(bs, "whereareyou", EasyClientName(client, netname, sizeof(netname)), NULL);
         trap_BotEnterChat(bs->cs, client, CHAT_TELL);
         return;
     }
     //
     bs->decisionmaker = client;
     bs->ordered = qtrue;
     bs->order_time = FloatTime();
     //the team mate
     bs->teammate = client;
     //last time the team mate was assumed visible
     bs->teammatevisible_time = FloatTime();
     //set the time to send a message to the team mates
     bs->teammessage_time = FloatTime() + 2 * random();
     //get the team goal time
     bs->teamgoal_time = FloatTime() + TEAM_ACCOMPANY_TIME;
     //set the ltg type
     bs->ltgtype = LTG_TEAMACCOMPANY;
     bs->formation_dist = 3.5 * 32;        //3.5 meter
     bs->arrive_time = 0;
     //
     BotSetTeamStatus(bs);
     // remember last ordered task
     BotRememberLastOrderedTask(bs);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References bot_goal_s::areanum, bot_state_s::arrive_time, BotAI_BotInitialChat(), BotEntityInfo(), BotPointAreaNum(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), CHAT_TELL, bot_state_s::cs, bot_state_s::decisionmaker, EasyClientName(), bot_goal_s::entitynum, FloatTime, bot_state_s::formation_dist, LTG_TEAMACCOMPANY, bot_state_s::ltgtype, MAX_NETNAME, bot_goal_s::maxs, bot_goal_s::mins, NULL, bot_state_s::order_time, bot_state_s::ordered, bot_goal_s::origin, aas_entityinfo_s::origin, qtrue, random, TEAM_ACCOMPANY_TIME, bot_state_s::teamgoal, bot_state_s::teamgoal_time, bot_state_s::teammate, bot_state_s::teammatevisible_time, bot_state_s::teammessage_time, trap_BotEnterChat(), aas_entityinfo_s::valid, VectorCopy, and VectorSet.
Referenced by BotVoiceChat_FollowFlagCarrier().
BotVoiceChat_GetFlag()
void BotVoiceChat_GetFlag (bot_state_t * bs, int client, int mode)
Definition at line 72 of file ai_vcmd.c.
{
     //
     if (gametype == GT_CTF) {
         if (!ctf_redflag.areanum || !ctf_blueflag.areanum)
             return;
     }
 #ifdef MISSIONPACK
     else if (gametype == GT_1FCTF) {
         if (!ctf_neutralflag.areanum || !ctf_redflag.areanum || !ctf_blueflag.areanum)
             return;
     }
 #endif
     else {
         return;
     }
     //
     bs->decisionmaker = client;
     bs->ordered = qtrue;
     bs->order_time = FloatTime();
     //set the time to send a message to the team mates
     bs->teammessage_time = FloatTime() + 2 * random();
     //set the ltg type
     bs->ltgtype = LTG_GETFLAG;
     //set the team goal time
     bs->teamgoal_time = FloatTime() + CTF_GETFLAG_TIME;
     // get an alternate route in ctf
     if (gametype == GT_CTF) {
         //get an alternative route goal towards the enemy base
         BotGetAlternateRouteGoal(bs, BotOppositeTeam(bs));
     }
     //
     BotSetTeamStatus(bs);
     // remember last ordered task
     BotRememberLastOrderedTask(bs);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References bot_goal_s::areanum, BotGetAlternateRouteGoal(), BotOppositeTeam(), BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), ctf_blueflag, CTF_GETFLAG_TIME, ctf_redflag, bot_state_s::decisionmaker, FloatTime, gametype, GT_1FCTF, GT_CTF, LTG_GETFLAG, bot_state_s::ltgtype, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, bot_state_s::teamgoal_time, and bot_state_s::teammessage_time.
Referenced by BotVoiceChat_Offense().
BotVoiceChat_Offense()
void BotVoiceChat_Offense (bot_state_t * bs, int client, int mode)
Definition at line 116 of file ai_vcmd.c.
{
     if ( gametype == GT_CTF
 #ifdef MISSIONPACK
         || gametype == GT_1FCTF
 #endif
         ) {
         BotVoiceChat_GetFlag(bs, client, mode);
         return;
     }
 #ifdef MISSIONPACK
     if (gametype == GT_HARVESTER) {
         //
         bs->decisionmaker = client;
         bs->ordered = qtrue;
         bs->order_time = FloatTime();
         //set the time to send a message to the team mates
         bs->teammessage_time = FloatTime() + 2 * random();
         //set the ltg type
         bs->ltgtype = LTG_HARVEST;
         //set the team goal time
         bs->teamgoal_time = FloatTime() + TEAM_HARVEST_TIME;
         bs->harvestaway_time = 0;
         //
         BotSetTeamStatus(bs);
         // remember last ordered task
         BotRememberLastOrderedTask(bs);
     }
     else
 #endif
     {
         //
         bs->decisionmaker = client;
         bs->ordered = qtrue;
         bs->order_time = FloatTime();
         //set the time to send a message to the team mates
         bs->teammessage_time = FloatTime() + 2 * random();
         //set the ltg type
         bs->ltgtype = LTG_ATTACKENEMYBASE;
         //set the team goal time
         bs->teamgoal_time = FloatTime() + TEAM_ATTACKENEMYBASE_TIME;
         bs->attackaway_time = 0;
         //
         BotSetTeamStatus(bs);
         // remember last ordered task
         BotRememberLastOrderedTask(bs);
     }
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References bot_state_s::attackaway_time, BotPrintTeamGoal(), BotRememberLastOrderedTask(), BotSetTeamStatus(), BotVoiceChat_GetFlag(), bot_state_s::decisionmaker, FloatTime, gametype, GT_1FCTF, GT_CTF, GT_HARVESTER, bot_state_s::harvestaway_time, LTG_ATTACKENEMYBASE, LTG_HARVEST, bot_state_s::ltgtype, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, TEAM_ATTACKENEMYBASE_TIME, TEAM_HARVEST_TIME, bot_state_s::teamgoal_time, and bot_state_s::teammessage_time.
BotVoiceChat_Patrol()
void BotVoiceChat_Patrol (bot_state_t * bs, int client, int mode)
Definition at line 234 of file ai_vcmd.c.
{
     //
     bs->decisionmaker = client;
     //
     bs->ltgtype = 0;
     bs->lead_time = 0;
     bs->lastgoal_ltgtype = 0;
     //
     BotAI_BotInitialChat(bs, "dismissed", NULL);
     trap_BotEnterChat(bs->cs, client, CHAT_TELL);
     BotVoiceChatOnly(bs, -1, VOICECHAT_ONPATROL);
     //
     BotSetTeamStatus(bs);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References BotAI_BotInitialChat(), BotPrintTeamGoal(), BotSetTeamStatus(), BotVoiceChatOnly(), CHAT_TELL, bot_state_s::cs, bot_state_s::decisionmaker, bot_state_s::lastgoal_ltgtype, bot_state_s::lead_time, bot_state_s::ltgtype, NULL, and trap_BotEnterChat().
BotVoiceChat_ReturnFlag()
void BotVoiceChat_ReturnFlag (bot_state_t * bs, int client, int mode)
Definition at line 383 of file ai_vcmd.c.
{
     //if not in CTF mode
     if (
         gametype != GT_CTF
 #ifdef MISSIONPACK
         && gametype != GT_1FCTF
 #endif
         ) {
         return;
     }
     //
     bs->decisionmaker = client;
     bs->ordered = qtrue;
     bs->order_time = FloatTime();
     //set the time to send a message to the team mates
     bs->teammessage_time = FloatTime() + 2 * random();
     //set the ltg type
     bs->ltgtype = LTG_RETURNFLAG;
     //set the team goal time
     bs->teamgoal_time = FloatTime() + CTF_RETURNFLAG_TIME;
     bs->rushbaseaway_time = 0;
     BotSetTeamStatus(bs);
 #ifdef DEBUG
     BotPrintTeamGoal(bs);
 #endif //DEBUG
 }
References BotPrintTeamGoal(), BotSetTeamStatus(), CTF_RETURNFLAG_TIME, bot_state_s::decisionmaker, FloatTime, gametype, GT_1FCTF, GT_CTF, LTG_RETURNFLAG, bot_state_s::ltgtype, bot_state_s::order_time, bot_state_s::ordered, qtrue, random, bot_state_s::rushbaseaway_time, bot_state_s::teamgoal_time, and bot_state_s::teammessage_time.
BotVoiceChat_StartLeader()
void BotVoiceChat_StartLeader (bot_state_t * bs, int client, int mode)
Definition at line 415 of file ai_vcmd.c.
{
     ClientName(client, bs->teamleader, sizeof(bs->teamleader));
 }
References ClientName(), and bot_state_s::teamleader.
BotVoiceChat_StopLeader()
void BotVoiceChat_StopLeader (bot_state_t * bs, int client, int mode)
Definition at line 424 of file ai_vcmd.c.
{
     char netname[MAX_MESSAGE_SIZE];
     if (!Q_stricmp(bs->teamleader, ClientName(client, netname, sizeof(netname)))) {
         bs->teamleader[0] = '\0';
         notleader[client] = qtrue;
     }
 }
References ClientName(), MAX_MESSAGE_SIZE, notleader, Q_stricmp(), qtrue, and bot_state_s::teamleader.
BotVoiceChat_WantOnDefense()
void BotVoiceChat_WantOnDefense (bot_state_t * bs, int client, int mode)
Definition at line 457 of file ai_vcmd.c.
{
     char netname[MAX_NETNAME];
     int preference;
     preference = BotGetTeamMateTaskPreference(bs, client);
     preference &= ~TEAMTP_ATTACKER;
     preference |= TEAMTP_DEFENDER;
     BotSetTeamMateTaskPreference(bs, client, preference);
     //
     EasyClientName(client, netname, sizeof(netname));
     BotAI_BotInitialChat(bs, "keepinmind", netname, NULL);
     trap_BotEnterChat(bs->cs, client, CHAT_TELL);
     BotVoiceChatOnly(bs, client, VOICECHAT_YES);
     trap_EA_Action(bs->client, ACTION_AFFIRMATIVE);
 }
References ACTION_AFFIRMATIVE, BotAI_BotInitialChat(), BotGetTeamMateTaskPreference(), BotSetTeamMateTaskPreference(), BotVoiceChatOnly(), CHAT_TELL, bot_state_s::client, bot_state_s::cs, EasyClientName(), MAX_NETNAME, NULL, TEAMTP_ATTACKER, TEAMTP_DEFENDER, trap_BotEnterChat(), and trap_EA_Action().
BotVoiceChat_WantOnOffense()
void BotVoiceChat_WantOnOffense (bot_state_t * bs, int client, int mode)
Definition at line 478 of file ai_vcmd.c.
{
     char netname[MAX_NETNAME];
     int preference;
     preference = BotGetTeamMateTaskPreference(bs, client);
     preference &= ~TEAMTP_DEFENDER;
     preference |= TEAMTP_ATTACKER;
     BotSetTeamMateTaskPreference(bs, client, preference);
     //
     EasyClientName(client, netname, sizeof(netname));
     BotAI_BotInitialChat(bs, "keepinmind", netname, NULL);
     trap_BotEnterChat(bs->cs, client, CHAT_TELL);
     BotVoiceChatOnly(bs, client, VOICECHAT_YES);
     trap_EA_Action(bs->client, ACTION_AFFIRMATIVE);
 }
References ACTION_AFFIRMATIVE, BotAI_BotInitialChat(), BotGetTeamMateTaskPreference(), BotSetTeamMateTaskPreference(), BotVoiceChatOnly(), CHAT_TELL, bot_state_s::client, bot_state_s::cs, EasyClientName(), MAX_NETNAME, NULL, TEAMTP_ATTACKER, TEAMTP_DEFENDER, trap_BotEnterChat(), and trap_EA_Action().
BotVoiceChat_WhoIsLeader()
void BotVoiceChat_WhoIsLeader (bot_state_t * bs, int client, int mode)
Definition at line 438 of file ai_vcmd.c.
{
     char netname[MAX_MESSAGE_SIZE];
     if (!TeamPlayIsOn()) return;
     ClientName(bs->client, netname, sizeof(netname));
     //if this bot IS the team leader
     if (!Q_stricmp(netname, bs->teamleader)) {
         BotAI_BotInitialChat(bs, "iamteamleader", NULL);
         trap_BotEnterChat(bs->cs, 0, CHAT_TEAM);
         BotVoiceChatOnly(bs, -1, VOICECHAT_STARTLEADER);
     }
 }
References BotAI_BotInitialChat(), BotVoiceChatOnly(), CHAT_TEAM, bot_state_s::client, ClientName(), bot_state_s::cs, MAX_MESSAGE_SIZE, NULL, Q_stricmp(), bot_state_s::teamleader, TeamPlayIsOn(), and trap_BotEnterChat().
BotVoiceChatCommand()
int BotVoiceChatCommand (bot_state_t * bs, int mode, char * voiceChat)
Definition at line 515 of file ai_vcmd.c.
{
     int i, clientNum;
     //int voiceOnly, color;
     char *ptr, buf[MAX_MESSAGE_SIZE], *cmd;
     if (!TeamPlayIsOn()) {
         return qfalse;
     }
     if ( mode == SAY_ALL ) {
         return qfalse;    // don't do anything with voice chats to everyone
     }
     Q_strncpyz(buf, voiceChat, sizeof(buf));
     cmd = buf;
     for (; *cmd && *cmd > ' '; cmd++);
     while (*cmd && *cmd <= ' ') *cmd++ = '\0';
     //voiceOnly = atoi(ptr);
     for (ptr = cmd; *cmd && *cmd > ' '; cmd++);
     while (*cmd && *cmd <= ' ') *cmd++ = '\0';
     clientNum = atoi(ptr);
     for (; *cmd && *cmd > ' '; cmd++);
     while (*cmd && *cmd <= ' ') *cmd++ = '\0';
     //color = atoi(ptr);
     if (!BotSameTeam(bs, clientNum)) {
         return qfalse;
     }
     for (i = 0; voiceCommands[i].cmd; i++) {
         if (!Q_stricmp(cmd, voiceCommands[i].cmd)) {
             voiceCommands[i].func(bs, clientNum, mode);
             return qtrue;
         }
     }
     return qfalse;
 }
References BotSameTeam(), voiceCommand_s::cmd, voiceCommand_s::func, MAX_MESSAGE_SIZE, Q_stricmp(), Q_strncpyz(), qfalse, qtrue, SAY_ALL, TeamPlayIsOn(), and voiceCommands.
Referenced by BotAI().
Variable Documentation
voiceCommands
voiceCommand_t voiceCommands[]
Initial value:
= {
    {VOICECHAT_GETFLAG, BotVoiceChat_GetFlag},
    {VOICECHAT_OFFENSE, BotVoiceChat_Offense },
    {VOICECHAT_DEFEND, BotVoiceChat_Defend },
    {VOICECHAT_DEFENDFLAG, BotVoiceChat_DefendFlag },
    {VOICECHAT_PATROL, BotVoiceChat_Patrol },
    {VOICECHAT_CAMP, BotVoiceChat_Camp },
    {VOICECHAT_FOLLOWME, BotVoiceChat_FollowMe },
    {VOICECHAT_FOLLOWFLAGCARRIER, BotVoiceChat_FollowFlagCarrier },
    {VOICECHAT_RETURNFLAG, BotVoiceChat_ReturnFlag },
    {VOICECHAT_STARTLEADER, BotVoiceChat_StartLeader },
    {VOICECHAT_STOPLEADER, BotVoiceChat_StopLeader },
    {VOICECHAT_WHOISLEADER, BotVoiceChat_WhoIsLeader },
    {VOICECHAT_WANTONDEFENSE, BotVoiceChat_WantOnDefense },
    {VOICECHAT_WANTONOFFENSE, BotVoiceChat_WantOnOffense },
    {NULL, BotVoiceChat_Dummy}
}
Definition at line 497 of file ai_vcmd.c.
Referenced by BotVoiceChatCommand().