ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ai_chat.c File Reference
be_ai_chat.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_libvar.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_utils.h"
#include "l_log.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_ea.h"
#include "be_ai_chat.h"
Classes
struct bot_chatmessage_s
struct bot_chattype_s
struct bot_chat_s
struct bot_randomstring_s
struct bot_randomlist_s
struct bot_synonym_s
struct bot_synonymlist_s
struct bot_matchstring_s
struct bot_matchpiece_s
struct bot_matchtemplate_s
struct bot_replychatkey_s
struct bot_replychat_s
struct bot_stringlist_s
struct bot_chatstate_s
struct bot_ichatdata_t
Macros
#define ESCAPE_CHAR 0x01
#define MT_VARIABLE 1
#define MT_STRING 2
#define RCKFL_AND 1
#define RCKFL_NOT 2
#define RCKFL_NAME 4
#define RCKFL_STRING 8
#define RCKFL_VARIABLES 16
#define RCKFL_BOTNAMES 32
#define RCKFL_GENDERFEMALE 64
#define RCKFL_GENDERMALE 128
#define RCKFL_GENDERLESS 256
#define CHATMESSAGE_RECENTTIME 20
Typedefs
typedef struct bot_chatmessage_s bot_chatmessage_t
typedef struct bot_chattype_s bot_chattype_t
typedef struct bot_chat_s bot_chat_t
typedef struct bot_randomstring_s bot_randomstring_t
typedef struct bot_randomlist_s bot_randomlist_t
typedef struct bot_synonym_s bot_synonym_t
typedef struct bot_synonymlist_s bot_synonymlist_t
typedef struct bot_matchstring_s bot_matchstring_t
typedef struct bot_matchpiece_s bot_matchpiece_t
typedef struct bot_matchtemplate_s bot_matchtemplate_t
typedef struct bot_replychatkey_s bot_replychatkey_t
typedef struct bot_replychat_s bot_replychat_t
typedef struct bot_stringlist_s bot_stringlist_t
typedef struct bot_chatstate_s bot_chatstate_t
Functions
bot_chatstate_t * BotChatStateFromHandle (int handle)
void InitConsoleMessageHeap (void)
bot_consolemessage_t * AllocConsoleMessage (void)
void FreeConsoleMessage (bot_consolemessage_t *message)
void BotRemoveConsoleMessage (int chatstate, int handle)
void BotQueueConsoleMessage (int chatstate, int type, char *message)
int BotNextConsoleMessage (int chatstate, bot_consolemessage_t *cm)
int BotNumConsoleMessages (int chatstate)
int IsWhiteSpace (char c)
void BotRemoveTildes (char *message)
void UnifyWhiteSpaces (char *string)
int StringContains (char *str1, char *str2, int casesensitive)
char * StringContainsWord (char *str1, char *str2, int casesensitive)
void StringReplaceWords (char *string, char *synonym, char *replacement)
void BotDumpSynonymList (bot_synonymlist_t *synlist)
bot_synonymlist_t * BotLoadSynonyms (char *filename)
void BotReplaceSynonyms (char *string, unsigned long int context)
void BotReplaceWeightedSynonyms (char *string, unsigned long int context)
void BotReplaceReplySynonyms (char *string, unsigned long int context)
int BotLoadChatMessage (source_t *source, char *chatmessagestring)
void BotDumpRandomStringList (bot_randomlist_t *randomlist)
bot_randomlist_t * BotLoadRandomStrings (char *filename)
char * RandomString (char *name)
void BotDumpMatchTemplates (bot_matchtemplate_t *matches)
void BotFreeMatchPieces (bot_matchpiece_t *matchpieces)
bot_matchpiece_t * BotLoadMatchPieces (source_t *source, char *endtoken)
void BotFreeMatchTemplates (bot_matchtemplate_t *mt)
bot_matchtemplate_t * BotLoadMatchTemplates (char *matchfile)
int StringsMatch (bot_matchpiece_t *pieces, bot_match_t *match)
int BotFindMatch (char *str, bot_match_t *match, unsigned long int context)
void BotMatchVariable (bot_match_t *match, int variable, char *buf, int size)
bot_stringlist_t * BotFindStringInList (bot_stringlist_t *list, char *string)
bot_stringlist_t * BotCheckChatMessageIntegrety (char *message, bot_stringlist_t *stringlist)
void BotCheckInitialChatIntegrety (bot_chat_t *chat)
void BotCheckReplyChatIntegrety (bot_replychat_t *replychat)
void BotDumpReplyChat (bot_replychat_t *replychat)
void BotFreeReplyChat (bot_replychat_t *replychat)
void BotCheckValidReplyChatKeySet (source_t *source, bot_replychatkey_t *keys)
bot_replychat_t * BotLoadReplyChat (char *filename)
void BotDumpInitialChat (bot_chat_t *chat)
bot_chat_t * BotLoadInitialChat (char *chatfile, char *chatname)
void BotFreeChatFile (int chatstate)
int BotLoadChatFile (int chatstate, char *chatfile, char *chatname)
int BotExpandChatMessage (char *outmessage, char *message, unsigned long mcontext, bot_match_t *match, unsigned long vcontext, int reply)
void BotConstructChatMessage (bot_chatstate_t *chatstate, char *message, unsigned long mcontext, bot_match_t *match, unsigned long vcontext, int reply)
char * BotChooseInitialChatMessage (bot_chatstate_t *cs, char *type)
int BotNumInitialChats (int chatstate, char *type)
void BotInitialChat (int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
void BotPrintReplyChatKeys (bot_replychat_t *replychat)
int BotReplyChat (int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int BotChatLength (int chatstate)
void BotEnterChat (int chatstate, int clientto, int sendto)
void BotGetChatMessage (int chatstate, char *buf, int size)
void BotSetChatGender (int chatstate, int gender)
void BotSetChatName (int chatstate, char *name, int client)
void BotResetChatAI (void)
int BotAllocChatState (void)
void BotFreeChatState (int handle)
int BotSetupChatAI (void)
void BotShutdownChatAI (void)
Variables
bot_ichatdata_t * ichatdata [MAX_CLIENTS]
bot_chatstate_t * botchatstates [MAX_CLIENTS+1]
bot_consolemessage_t * consolemessageheap = NULL
bot_consolemessage_t * freeconsolemessages = NULL
bot_matchtemplate_t * matchtemplates = NULL
bot_synonymlist_t * synonyms = NULL
bot_randomlist_t * randomstrings = NULL
bot_replychat_t * replychats = NULL
Macro Definition Documentation
CHATMESSAGE_RECENTTIME
#define CHATMESSAGE_RECENTTIME 20
Definition at line 71 of file be_ai_chat.c.
ESCAPE_CHAR
#define ESCAPE_CHAR 0x01
Definition at line 50 of file be_ai_chat.c.
MT_STRING
#define MT_STRING 2
Definition at line 59 of file be_ai_chat.c.
MT_VARIABLE
#define MT_VARIABLE 1
Definition at line 58 of file be_ai_chat.c.
RCKFL_AND
#define RCKFL_AND 1
Definition at line 61 of file be_ai_chat.c.
RCKFL_BOTNAMES
#define RCKFL_BOTNAMES 32
Definition at line 66 of file be_ai_chat.c.
RCKFL_GENDERFEMALE
#define RCKFL_GENDERFEMALE 64
Definition at line 67 of file be_ai_chat.c.
RCKFL_GENDERLESS
#define RCKFL_GENDERLESS 256
Definition at line 69 of file be_ai_chat.c.
RCKFL_GENDERMALE
#define RCKFL_GENDERMALE 128
Definition at line 68 of file be_ai_chat.c.
RCKFL_NAME
#define RCKFL_NAME 4
Definition at line 63 of file be_ai_chat.c.
RCKFL_NOT
#define RCKFL_NOT 2
Definition at line 62 of file be_ai_chat.c.
RCKFL_STRING
#define RCKFL_STRING 8
Definition at line 64 of file be_ai_chat.c.
RCKFL_VARIABLES
#define RCKFL_VARIABLES 16
Definition at line 65 of file be_ai_chat.c.
Typedef Documentation
bot_chat_t
typedef struct bot_chat_s bot_chat_t
bot_chatmessage_t
typedef struct bot_chatmessage_s bot_chatmessage_t
bot_chatstate_t
typedef struct bot_chatstate_s bot_chatstate_t
bot_chattype_t
typedef struct bot_chattype_s bot_chattype_t
bot_matchpiece_t
typedef struct bot_matchpiece_s bot_matchpiece_t
bot_matchstring_t
typedef struct bot_matchstring_s bot_matchstring_t
bot_matchtemplate_t
typedef struct bot_matchtemplate_s bot_matchtemplate_t
bot_randomlist_t
typedef struct bot_randomlist_s bot_randomlist_t
bot_randomstring_t
typedef struct bot_randomstring_s bot_randomstring_t
bot_replychat_t
typedef struct bot_replychat_s bot_replychat_t
bot_replychatkey_t
typedef struct bot_replychatkey_s bot_replychatkey_t
bot_stringlist_t
typedef struct bot_stringlist_s bot_stringlist_t
bot_synonym_t
typedef struct bot_synonym_s bot_synonym_t
bot_synonymlist_t
typedef struct bot_synonymlist_s bot_synonymlist_t
Function Documentation
AllocConsoleMessage()
bot_consolemessage_t* AllocConsoleMessage (void)
Definition at line 268 of file be_ai_chat.c.
 {
     bot_consolemessage_t *message;
     message = freeconsolemessages;
     if (freeconsolemessages) freeconsolemessages = freeconsolemessages->next;
     if (freeconsolemessages) freeconsolemessages->prev = NULL;
     return message;
 } //end of the function AllocConsoleMessage
Referenced by BotQueueConsoleMessage().
BotAllocChatState()
int BotAllocChatState (void)
Definition at line 2915 of file be_ai_chat.c.
 {
     int i;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (!botchatstates[i])
         {
             botchatstates[i] = GetClearedMemory(sizeof(bot_chatstate_t));
             return i;
         } //end if
     } //end for
     return 0;
 } //end of the function BotAllocChatState
Referenced by Init_AI_Export().
BotChatLength()
int BotChatLength (int chatstate)
Definition at line 2791 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     return strlen(cs->chatmessage);
 } //end of the function BotChatLength
Referenced by Init_AI_Export().
BotChatStateFromHandle()
bot_chatstate_t* BotChatStateFromHandle (int handle)
Definition at line 219 of file be_ai_chat.c.
 {
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "chat state handle %d out of range\n", handle);
         return NULL;
     } //end if
     if (!botchatstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid chat state %d\n", handle);
         return NULL;
     } //end if
     return botchatstates[handle];
 } //end of the function BotChatStateFromHandle
Referenced by BotChatLength(), BotEnterChat(), BotFreeChatFile(), BotGetChatMessage(), BotInitialChat(), BotLoadChatFile(), BotNextConsoleMessage(), BotNumConsoleMessages(), BotNumInitialChats(), BotQueueConsoleMessage(), BotRemoveConsoleMessage(), BotReplyChat(), BotSetChatGender(), and BotSetChatName().
BotCheckChatMessageIntegrety()
bot_stringlist_t* BotCheckChatMessageIntegrety (char * message, bot_stringlist_t * stringlist)
Definition at line 1532 of file be_ai_chat.c.
 {
     int i;
     char *msgptr;
     char temp[MAX_MESSAGE_SIZE];
     bot_stringlist_t *s;
     msgptr = message;
     //
     while(*msgptr)
     {
         if (*msgptr == ESCAPE_CHAR)
         {
             msgptr++;
             switch(*msgptr)
             {
                 case 'v': //variable
                 {
                     //step over the 'v'
                     msgptr++;
                     while(*msgptr && *msgptr != ESCAPE_CHAR) msgptr++;
                     //step over the trailing escape char
                     if (*msgptr) msgptr++;
                     break;
                 } //end case
                 case 'r': //random
                 {
                     //step over the 'r'
                     msgptr++;
                     for (i = 0; (*msgptr && *msgptr != ESCAPE_CHAR); i++)
                     {
                         temp[i] = *msgptr++;
                     } //end while
                     temp[i] = '\0';
                     //step over the trailing escape char
                     if (*msgptr) msgptr++;
                     //find the random keyword
                     if (!RandomString(temp))
                     {
                         if (!BotFindStringInList(stringlist, temp))
{
                             Log_Write("%s = {\"%s\"} //MISSING RANDOM\r\n", temp, temp);
                             s = GetClearedMemory(sizeof(bot_stringlist_t) + strlen(temp) + 1);
                             s->string = (char *) s + sizeof(bot_stringlist_t);
                             strcpy(s->string, temp);
                             s->next = stringlist;
                             stringlist = s;
                         } //end if
                     } //end if
                     break;
                 } //end case
                 default:
                 {
                     botimport.Print(PRT_FATAL, "BotCheckChatMessageIntegrety: message \"%s\" invalid escape char\n", message);
                     break;
                 } //end default
             } //end switch
         } //end if
         else
         {
             msgptr++;
         } //end else
     } //end while
     return stringlist;
 } //end of the function BotCheckChatMessageIntegrety
Referenced by BotCheckInitialChatIntegrety(), and BotCheckReplyChatIntegrety().
BotCheckInitialChatIntegrety()
void BotCheckInitialChatIntegrety (bot_chat_t * chat)
Definition at line 1603 of file be_ai_chat.c.
 {
     bot_chattype_t *t;
     bot_chatmessage_t *cm;
     bot_stringlist_t *stringlist, *s, *nexts;
     stringlist = NULL;
     for (t = chat->types; t; t = t->next)
     {
         for (cm = t->firstchatmessage; cm; cm = cm->next)
         {
             stringlist = BotCheckChatMessageIntegrety(cm->chatmessage, stringlist);
         } //end for
     } //end for
     for (s = stringlist; s; s = nexts)
     {
         nexts = s->next;
         FreeMemory(s);
     } //end for
 } //end of the function BotCheckInitialChatIntegrety
Referenced by BotLoadInitialChat().
BotCheckReplyChatIntegrety()
void BotCheckReplyChatIntegrety (bot_replychat_t * replychat)
Definition at line 1629 of file be_ai_chat.c.
 {
     bot_replychat_t *rp;
     bot_chatmessage_t *cm;
     bot_stringlist_t *stringlist, *s, *nexts;
     stringlist = NULL;
     for (rp = replychat; rp; rp = rp->next)
     {
         for (cm = rp->firstchatmessage; cm; cm = cm->next)
         {
             stringlist = BotCheckChatMessageIntegrety(cm->chatmessage, stringlist);
         } //end for
     } //end for
     for (s = stringlist; s; s = nexts)
     {
         nexts = s->next;
         FreeMemory(s);
     } //end for
 } //end of the function BotCheckReplyChatIntegrety
Referenced by BotLoadReplyChat().
BotCheckValidReplyChatKeySet()
void BotCheckValidReplyChatKeySet (source_t * source, bot_replychatkey_t * keys)
Definition at line 1740 of file be_ai_chat.c.
 {
     int allprefixed, hasvariableskey, hasstringkey;
     bot_matchpiece_t *m;
     bot_matchstring_t *ms;
     bot_replychatkey_t *key, *key2;
     //
     allprefixed = qtrue;
     hasvariableskey = hasstringkey = qfalse;
     for (key = keys; key; key = key->next)
     {
         if (!(key->flags & (RCKFL_AND|RCKFL_NOT)))
         {
             allprefixed = qfalse;
             if (key->flags & RCKFL_VARIABLES)
             {
                 for (m = key->match; m; m = m->next)
                 {
                     if (m->type == MT_VARIABLE) hasvariableskey = qtrue;
                 } //end for
             } //end if
             else if (key->flags & RCKFL_STRING)
             {
                 hasstringkey = qtrue;
             } //end else if
         } //end if
         else if ((key->flags & RCKFL_AND) && (key->flags & RCKFL_STRING))
         {
             for (key2 = keys; key2; key2 = key2->next)
             {
                 if (key2 == key) continue;
                 if (key2->flags & RCKFL_NOT) continue;
                 if (key2->flags & RCKFL_VARIABLES)
                 {
                     for (m = key2->match; m; m = m->next)
                     {
                         if (m->type == MT_STRING)
{
                             for (ms = m->firststring; ms; ms = ms->next)
{
                                 if (StringContains(ms->string, key->string, qfalse) != -1)
{
                                     break;
                                 } //end if
                             } //end for
                             if (ms) break;
                         } //end if
                         else if (m->type == MT_VARIABLE)
{
                             break;
                         } //end if
                     } //end for
                     if (!m)
                     {
                         SourceWarning(source, "one of the match templates does not "
                                         "leave space for the key %s with the & prefix", key->string);
                     } //end if
                 } //end if
             } //end for
         } //end else
         if ((key->flags & RCKFL_NOT) && (key->flags & RCKFL_STRING))
         {
             for (key2 = keys; key2; key2 = key2->next)
             {
                 if (key2 == key) continue;
                 if (key2->flags & RCKFL_NOT) continue;
                 if (key2->flags & RCKFL_STRING)
                 {
                     if (StringContains(key2->string, key->string, qfalse) != -1)
                     {
                         SourceWarning(source, "the key %s with prefix ! is inside the key %s", key->string, key2->string);
                     } //end if
                 } //end if
                 else if (key2->flags & RCKFL_VARIABLES)
                 {
                     for (m = key2->match; m; m = m->next)
                     {
                         if (m->type == MT_STRING)
{
                             for (ms = m->firststring; ms; ms = ms->next)
{
                                 if (StringContains(ms->string, key->string, qfalse) != -1)
{
                                     SourceWarning(source, "the key %s with prefix ! is inside "
                                                 "the match template string %s", key->string, ms->string);
                                 } //end if
                             } //end for
                         } //end if
                     } //end for
                 } //end else if
             } //end for
         } //end if
     } //end for
     if (allprefixed) SourceWarning(source, "all keys have a & or ! prefix");
     if (hasvariableskey && hasstringkey)
     {
         SourceWarning(source, "variables from the match template(s) could be "
                                 "invalid when outputting one of the chat messages");
     } //end if
 } //end of the function BotCheckValidReplyChatKeySet
Referenced by BotLoadReplyChat().
BotChooseInitialChatMessage()
char* BotChooseInitialChatMessage (bot_chatstate_t * cs, char * type)
Definition at line 2429 of file be_ai_chat.c.
 {
     int n, numchatmessages;
     float besttime;
     bot_chattype_t *t;
     bot_chatmessage_t *m, *bestchatmessage;
     bot_chat_t *chat;
     chat = cs->chat;
     for (t = chat->types; t; t = t->next)
     {
         if (!Q_stricmp(t->name, type))
         {
             numchatmessages = 0;
             for (m = t->firstchatmessage; m; m = m->next)
             {
                 if (m->time > AAS_Time()) continue;
                 numchatmessages++;
             } //end if
             //if all chat messages have been used recently
             if (numchatmessages <= 0)
             {
                 besttime = 0;
                 bestchatmessage = NULL;
                 for (m = t->firstchatmessage; m; m = m->next)
                 {
                     if (!besttime || m->time < besttime)
                     {
                         bestchatmessage = m;
                         besttime = m->time;
                     } //end if
                 } //end for
                 if (bestchatmessage) return bestchatmessage->chatmessage;
             } //end if
             else //choose a chat message randomly
             {
                 n = random() * numchatmessages;
                 for (m = t->firstchatmessage; m; m = m->next)
                 {
                     if (m->time > AAS_Time()) continue;
                     if (--n < 0)
                     {
                         m->time = AAS_Time() + CHATMESSAGE_RECENTTIME;
                         return m->chatmessage;
                     } //end if
                 } //end for
             } //end else
             return NULL;
         } //end if
     } //end for
     return NULL;
 } //end of the function BotChooseInitialChatMessage
Referenced by BotInitialChat().
BotConstructChatMessage()
void BotConstructChatMessage (bot_chatstate_t * chatstate, char * message, unsigned long mcontext, bot_match_t * match, unsigned long vcontext, int reply)
Definition at line 2401 of file be_ai_chat.c.
 {
     int i;
     char srcmessage[MAX_MESSAGE_SIZE];
     strcpy(srcmessage, message);
     for (i = 0; i < 10; i++)
     {
         if (!BotExpandChatMessage(chatstate->chatmessage, srcmessage, mcontext, match, vcontext, reply))
         {
             break;
         } //end if
         strcpy(srcmessage, chatstate->chatmessage);
     } //end for
     if (i >= 10)
     {
         botimport.Print(PRT_WARNING, "too many expansions in chat message\n");
         botimport.Print(PRT_WARNING, "%s\n", chatstate->chatmessage);
     } //end if
 } //end of the function BotConstructChatMessage
Referenced by BotInitialChat(), and BotReplyChat().
BotDumpInitialChat()
void BotDumpInitialChat (bot_chat_t * chat)
Definition at line 2007 of file be_ai_chat.c.
 {
     bot_chattype_t *t;
     bot_chatmessage_t *m;
     Log_Write("{");
     for (t = chat->types; t; t = t->next)
     {
         Log_Write(" type \"%s\"", t->name);
         Log_Write(" {");
         Log_Write("  numchatmessages = %d", t->numchatmessages);
         for (m = t->firstchatmessage; m; m = m->next)
         {
             Log_Write("  \"%s\"", m->chatmessage);
         } //end for
         Log_Write(" }");
     } //end for
     Log_Write("}");
 } //end of the function BotDumpInitialChat
BotDumpMatchTemplates()
void BotDumpMatchTemplates (bot_matchtemplate_t * matches)
Definition at line 1097 of file be_ai_chat.c.
 {
     FILE *fp;
     bot_matchtemplate_t *mt;
     bot_matchpiece_t *mp;
     bot_matchstring_t *ms;
     fp = Log_FilePointer();
     if (!fp) return;
     for (mt = matches; mt; mt = mt->next)
     {
             fprintf(fp, "{ " );
         for (mp = mt->first; mp; mp = mp->next)
         {
             if (mp->type == MT_STRING)
             {
                 for (ms = mp->firststring; ms; ms = ms->next)
                 {
                     fprintf(fp, "\"%s\"", ms->string);
                     if (ms->next) fprintf(fp, "|");
                 } //end for
             } //end if
             else if (mp->type == MT_VARIABLE)
             {
                 fprintf(fp, "%d", mp->variable);
             } //end else if
             if (mp->next) fprintf(fp, ", ");
         } //end for
         fprintf(fp, " = (%d, %d);}\n", mt->type, mt->subtype);
     } //end for
 } //end of the function BotDumpMatchTemplates
BotDumpRandomStringList()
void BotDumpRandomStringList (bot_randomlist_t * randomlist)
Definition at line 936 of file be_ai_chat.c.
 {
     FILE *fp;
     bot_randomlist_t *random;
     bot_randomstring_t *rs;
     fp = Log_FilePointer();
     if (!fp) return;
     for (random = randomlist; random; random = random->next)
     {
         fprintf(fp, "%s = {", random->string);
         for (rs = random->firstrandomstring; rs; rs = rs->next)
         {
             fprintf(fp, "\"%s\"", rs->string);
             if (rs->next) fprintf(fp, ", ");
             else fprintf(fp, "}\n");
         } //end for
     } //end for
 } //end of the function BotDumpRandomStringList
BotDumpReplyChat()
void BotDumpReplyChat (bot_replychat_t * replychat)
Definition at line 1655 of file be_ai_chat.c.
 {
     FILE *fp;
     bot_replychat_t *rp;
     bot_replychatkey_t *key;
     bot_chatmessage_t *cm;
     bot_matchpiece_t *mp;
     fp = Log_FilePointer();
     if (!fp) return;
     fprintf(fp, "BotDumpReplyChat:\n");
     for (rp = replychat; rp; rp = rp->next)
     {
         fprintf(fp, "[");
         for (key = rp->keys; key; key = key->next)
         {
             if (key->flags & RCKFL_AND) fprintf(fp, "&");
             else if (key->flags & RCKFL_NOT) fprintf(fp, "!");
             //
             if (key->flags & RCKFL_NAME) fprintf(fp, "name");
             else if (key->flags & RCKFL_GENDERFEMALE) fprintf(fp, "female");
             else if (key->flags & RCKFL_GENDERMALE) fprintf(fp, "male");
             else if (key->flags & RCKFL_GENDERLESS) fprintf(fp, "it");
             else if (key->flags & RCKFL_VARIABLES)
             {
                 fprintf(fp, "(");
                 for (mp = key->match; mp; mp = mp->next)
                 {
                     if (mp->type == MT_STRING) fprintf(fp, "\"%s\"", mp->firststring->string);
                     else fprintf(fp, "%d", mp->variable);
                     if (mp->next) fprintf(fp, ", ");
                 } //end for
                 fprintf(fp, ")");
             } //end if
             else if (key->flags & RCKFL_STRING)
             {
                 fprintf(fp, "\"%s\"", key->string);
             } //end if
             if (key->next) fprintf(fp, ", ");
             else fprintf(fp, "] = %1.0f\n", rp->priority);
         } //end for
         fprintf(fp, "{\n");
         for (cm = rp->firstchatmessage; cm; cm = cm->next)
         {
             fprintf(fp, "\t\"%s\";\n", cm->chatmessage);
         } //end for
         fprintf(fp, "}\n");
     } //end for
 } //end of the function BotDumpReplyChat
BotDumpSynonymList()
void BotDumpSynonymList (bot_synonymlist_t * synlist)
Definition at line 583 of file be_ai_chat.c.
 {
     FILE *fp;
     bot_synonymlist_t *syn;
     bot_synonym_t *synonym;
     fp = Log_FilePointer();
     if (!fp) return;
     for (syn = synlist; syn; syn = syn->next)
     {
             fprintf(fp, "%ld : [", syn->context);
         for (synonym = syn->firstsynonym; synonym; synonym = synonym->next)
         {
             fprintf(fp, "(\"%s\", %1.2f)", synonym->string, synonym->weight);
             if (synonym->next) fprintf(fp, ", ");
         } //end for
         fprintf(fp, "]\n");
     } //end for
 } //end of the function BotDumpSynonymList
BotEnterChat()
void BotEnterChat (int chatstate, int clientto, int sendto)
Definition at line 2805 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     if (strlen(cs->chatmessage))
     {
         BotRemoveTildes(cs->chatmessage);
         if (LibVarGetValue("bot_testichat")) {
             botimport.Print(PRT_MESSAGE, "%s\n", cs->chatmessage);
         }
         else {
             switch(sendto) {
                 case CHAT_TEAM:
                     EA_Command(cs->client, va("say_team %s", cs->chatmessage));
                     break;
                 case CHAT_TELL:
                     EA_Command(cs->client, va("tell %d %s", clientto, cs->chatmessage));
                     break;
                 default: //CHAT_ALL
                     EA_Command(cs->client, va("say %s", cs->chatmessage));
                     break;
             }
         }
         //clear the chat message from the state
         strcpy(cs->chatmessage, "");
     } //end if
 } //end of the function BotEnterChat
Referenced by Init_AI_Export().
BotExpandChatMessage()
int BotExpandChatMessage (char * outmessage, char * message, unsigned long mcontext, bot_match_t * match, unsigned long vcontext, int reply)
Definition at line 2280 of file be_ai_chat.c.
 {
     int num, len, i, expansion;
     char *outputbuf, *ptr, *msgptr;
     char temp[MAX_MESSAGE_SIZE];
     expansion = qfalse;
     msgptr = message;
     outputbuf = outmessage;
     len = 0;
     //
     while(*msgptr)
     {
         if (*msgptr == ESCAPE_CHAR)
         {
             msgptr++;
             switch(*msgptr)
             {
                 case 'v': //variable
                 {
                     msgptr++;
                     num = 0;
                     while(*msgptr && *msgptr != ESCAPE_CHAR)
                     {
                         num = num * 10 + (*msgptr++) - '0';
                     } //end while
                     //step over the trailing escape char
                     if (*msgptr) msgptr++;
                     if (num > MAX_MATCHVARIABLES)
                     {
                         botimport.Print(PRT_ERROR, "BotConstructChat: message %s variable %d out of range\n", message, num);
                         return qfalse;
                     } //end if
                     if (match->variables[num].offset >= 0)
                     {
                             assert( match->variables[num].offset >= 0 );
                         ptr = &match->string[ (int) match->variables[num].offset];
                         for (i = 0; i < match->variables[num].length; i++)
{
                             temp[i] = ptr[i];
                         } //end for
                         temp[i] = 0;
                         //if it's a reply message
                         if (reply)
{
                             //replace the reply synonyms in the variables
                             BotReplaceReplySynonyms(temp, vcontext);
                         } //end if
                         else
{
                             //replace synonyms in the variable context
                             BotReplaceSynonyms(temp, vcontext);
                         } //end else
                         //
                         if (len + strlen(temp) >= MAX_MESSAGE_SIZE)
{
                             botimport.Print(PRT_ERROR, "BotConstructChat: message %s too long\n", message);
                             return qfalse;
                         } //end if
                         strcpy(&outputbuf[len], temp);
                         len += strlen(temp);
                     } //end if
                     break;
                 } //end case
                 case 'r': //random
                 {
                     msgptr++;
                     for (i = 0; (*msgptr && *msgptr != ESCAPE_CHAR); i++)
                     {
                         temp[i] = *msgptr++;
                     } //end while
                     temp[i] = '\0';
                     //step over the trailing escape char
                     if (*msgptr) msgptr++;
                     //find the random keyword
                     ptr = RandomString(temp);
                     if (!ptr)
                     {
                         botimport.Print(PRT_ERROR, "BotConstructChat: unknown random string %s\n", temp);
                         return qfalse;
                     } //end if
                     if (len + strlen(ptr) >= MAX_MESSAGE_SIZE)
                     {
                         botimport.Print(PRT_ERROR, "BotConstructChat: message \"%s\" too long\n", message);
                         return qfalse;
                     } //end if
                     strcpy(&outputbuf[len], ptr);
                     len += strlen(ptr);
                     expansion = qtrue;
                     break;
                 } //end case
                 default:
                 {
                     botimport.Print(PRT_FATAL, "BotConstructChat: message \"%s\" invalid escape char\n", message);
                     break;
                 } //end default
             } //end switch
         } //end if
         else
         {
             outputbuf[len++] = *msgptr++;
             if (len >= MAX_MESSAGE_SIZE)
             {
                 botimport.Print(PRT_ERROR, "BotConstructChat: message \"%s\" too long\n", message);
                 break;
             } //end if
         } //end else
     } //end while
     outputbuf[len] = '\0';
     //replace synonyms weighted in the message context
     BotReplaceWeightedSynonyms(outputbuf, mcontext);
     //return true if a random was expanded
     return expansion;
 } //end of the function BotExpandChatMessage
Referenced by BotConstructChatMessage().
BotFindMatch()
int BotFindMatch (char * str, bot_match_t * match, unsigned long int context)
Definition at line 1454 of file be_ai_chat.c.
 {
     int i;
     bot_matchtemplate_t *ms;
     Q_strncpyz(match->string, str, MAX_MESSAGE_SIZE);
     //remove any trailing enters
     while(strlen(match->string) &&
             match->string[strlen(match->string)-1] == '\n')
     {
         match->string[strlen(match->string)-1] = '\0';
     } //end while
     //compare the string with all the match strings
     for (ms = matchtemplates; ms; ms = ms->next)
     {
         if (!(ms->context & context)) continue;
         //reset the match variable offsets
         for (i = 0; i < MAX_MATCHVARIABLES; i++) match->variables[i].offset = -1;
         //
         if (StringsMatch(ms->first, match))
         {
             match->type = ms->type;
             match->subtype = ms->subtype;
             return qtrue;
         } //end if
     } //end for
     return qfalse;
 } //end of the function BotFindMatch
Referenced by Init_AI_Export().
BotFindStringInList()
bot_stringlist_t* BotFindStringInList (bot_stringlist_t * list, char * string)
Definition at line 1516 of file be_ai_chat.c.
 {
     bot_stringlist_t *s;
     for (s = list; s; s = s->next)
     {
         if (!strcmp(s->string, string)) return s;
     } //end for
     return NULL;
 } //end of the function BotFindStringInList
Referenced by BotCheckChatMessageIntegrety().
BotFreeChatFile()
void BotFreeChatFile (int chatstate)
Definition at line 2207 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     if (cs->chat) FreeMemory(cs->chat);
     cs->chat = NULL;
 } //end of the function BotFreeChatFile
Referenced by BotFreeChatState(), and BotLoadChatFile().
BotFreeChatState()
void BotFreeChatState (int handle)
Definition at line 2935 of file be_ai_chat.c.
 {
     bot_consolemessage_t m;
     int h;
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "chat state handle %d out of range\n", handle);
         return;
     } //end if
     if (!botchatstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid chat state %d\n", handle);
         return;
     } //end if
     if (LibVarGetValue("bot_reloadcharacters"))
     {
         BotFreeChatFile(handle);
     } //end if
     //free all the console messages left in the chat state
     for (h = BotNextConsoleMessage(handle, &m); h; h = BotNextConsoleMessage(handle, &m))
     {
         //remove the console message
         BotRemoveConsoleMessage(handle, h);
     } //end for
     FreeMemory(botchatstates[handle]);
     botchatstates[handle] = NULL;
 } //end of the function BotFreeChatState
Referenced by BotShutdownChatAI(), and Init_AI_Export().
BotFreeMatchPieces()
void BotFreeMatchPieces (bot_matchpiece_t * matchpieces)
Definition at line 1134 of file be_ai_chat.c.
 {
     bot_matchpiece_t *mp, *nextmp;
     bot_matchstring_t *ms, *nextms;
     for (mp = matchpieces; mp; mp = nextmp)
     {
         nextmp = mp->next;
         if (mp->type == MT_STRING)
         {
             for (ms = mp->firststring; ms; ms = nextms)
             {
                 nextms = ms->next;
                 FreeMemory(ms);
             } //end for
         } //end if
         FreeMemory(mp);
     } //end for
 } //end of the function BotFreeMatchPieces
Referenced by BotFreeMatchTemplates(), BotFreeReplyChat(), and BotLoadMatchPieces().
BotFreeMatchTemplates()
void BotFreeMatchTemplates (bot_matchtemplate_t * mt)
Definition at line 1261 of file be_ai_chat.c.
 {
     bot_matchtemplate_t *nextmt;
     for (; mt; mt = nextmt)
     {
         nextmt = mt->next;
         BotFreeMatchPieces(mt->first);
         FreeMemory(mt);
     } //end for
 } //end of the function BotFreeMatchTemplates
Referenced by BotLoadMatchTemplates(), and BotShutdownChatAI().
BotFreeReplyChat()
void BotFreeReplyChat (bot_replychat_t * replychat)
Definition at line 1710 of file be_ai_chat.c.
 {
     bot_replychat_t *rp, *nextrp;
     bot_replychatkey_t *key, *nextkey;
     bot_chatmessage_t *cm, *nextcm;
     for (rp = replychat; rp; rp = nextrp)
     {
         nextrp = rp->next;
         for (key = rp->keys; key; key = nextkey)
         {
             nextkey = key->next;
             if (key->match) BotFreeMatchPieces(key->match);
             if (key->string) FreeMemory(key->string);
             FreeMemory(key);
         } //end for
         for (cm = rp->firstchatmessage; cm; cm = nextcm)
         {
             nextcm = cm->next;
             FreeMemory(cm);
         } //end for
         FreeMemory(rp);
     } //end for
 } //end of the function BotFreeReplyChat
Referenced by BotLoadReplyChat(), and BotShutdownChatAI().
BotGetChatMessage()
void BotGetChatMessage (int chatstate, char * buf, int size)
Definition at line 2841 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     BotRemoveTildes(cs->chatmessage);
     strncpy(buf, cs->chatmessage, size-1);
     buf[size-1] = '\0';
     //clear the chat message from the state
     strcpy(cs->chatmessage, "");
 } //end of the function BotGetChatMessage
Referenced by Init_AI_Export().
BotInitialChat()
void BotInitialChat (int chatstate, char * type, int mcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 2514 of file be_ai_chat.c.
 {
     char *message;
     int index;
     bot_match_t match;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     //if no chat file is loaded
     if (!cs->chat) return;
     //choose a chat message randomly of the given type
     message = BotChooseInitialChatMessage(cs, type);
     //if there's no message of the given type
     if (!message)
     {
 #ifdef DEBUG
         botimport.Print(PRT_MESSAGE, "no chat messages of type %s\n", type);
 #endif //DEBUG
         return;
     } //end if
     //
     Com_Memset(&match, 0, sizeof(match));
     index = 0;
     if( var0 ) {
         strcat(match.string, var0);
         match.variables[0].offset = index;
         match.variables[0].length = strlen(var0);
         index += strlen(var0);
     }
     if( var1 ) {
         strcat(match.string, var1);
         match.variables[1].offset = index;
         match.variables[1].length = strlen(var1);
         index += strlen(var1);
     }
     if( var2 ) {
         strcat(match.string, var2);
         match.variables[2].offset = index;
         match.variables[2].length = strlen(var2);
         index += strlen(var2);
     }
     if( var3 ) {
         strcat(match.string, var3);
         match.variables[3].offset = index;
         match.variables[3].length = strlen(var3);
         index += strlen(var3);
     }
     if( var4 ) {
         strcat(match.string, var4);
         match.variables[4].offset = index;
         match.variables[4].length = strlen(var4);
         index += strlen(var4);
     }
     if( var5 ) {
         strcat(match.string, var5);
         match.variables[5].offset = index;
         match.variables[5].length = strlen(var5);
         index += strlen(var5);
     }
     if( var6 ) {
         strcat(match.string, var6);
         match.variables[6].offset = index;
         match.variables[6].length = strlen(var6);
         index += strlen(var6);
     }
     if( var7 ) {
         strcat(match.string, var7);
         match.variables[7].offset = index;
         match.variables[7].length = strlen(var7);
     }
     //
     BotConstructChatMessage(cs, message, mcontext, &match, 0, qfalse);
 } //end of the function BotInitialChat
Referenced by Init_AI_Export().
BotLoadChatFile()
int BotLoadChatFile (int chatstate, char * chatfile, char * chatname)
Definition at line 2222 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     int n, avail = 0;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return BLERR_CANNOTLOADICHAT;
     BotFreeChatFile(chatstate);
     if (!LibVarGetValue("bot_reloadcharacters"))
     {
         avail = -1;
         for( n = 0; n < MAX_CLIENTS; n++ ) {
             if( !ichatdata[n] ) {
                 if( avail == -1 ) {
                     avail = n;
                 }
                 continue;
             }
             if( strcmp( chatfile, ichatdata[n]->filename ) != 0 ) {
                 continue;
             }
             if( strcmp( chatname, ichatdata[n]->chatname ) != 0 ) {
                 continue;
             }
             cs->chat = ichatdata[n]->chat;
         //      botimport.Print( PRT_MESSAGE, "retained %s from %s\n", chatname, chatfile );
             return BLERR_NOERROR;
         }
         if( avail == -1 ) {
             botimport.Print(PRT_FATAL, "ichatdata table full; couldn't load chat %s from %s\n", chatname, chatfile);
             return BLERR_CANNOTLOADICHAT;
         }
     }
     cs->chat = BotLoadInitialChat(chatfile, chatname);
     if (!cs->chat)
     {
         botimport.Print(PRT_FATAL, "couldn't load chat %s from %s\n", chatname, chatfile);
         return BLERR_CANNOTLOADICHAT;
     } //end if
     if (!LibVarGetValue("bot_reloadcharacters"))
     {
         ichatdata[avail] = GetClearedMemory( sizeof(bot_ichatdata_t) );
         ichatdata[avail]->chat = cs->chat;
         Q_strncpyz( ichatdata[avail]->chatname, chatname, sizeof(ichatdata[avail]->chatname) );
         Q_strncpyz( ichatdata[avail]->filename, chatfile, sizeof(ichatdata[avail]->filename) );
     } //end if
     return BLERR_NOERROR;
 } //end of the function BotLoadChatFile
Referenced by Init_AI_Export().
BotLoadChatMessage()
int BotLoadChatMessage (source_t * source, char * chatmessagestring)
Definition at line 877 of file be_ai_chat.c.
 {
     char *ptr;
     token_t token;
     ptr = chatmessagestring;
     *ptr = 0;
     //
     while(1)
     {
         if (!PC_ExpectAnyToken(source, &token)) return qfalse;
         //fixed string
         if (token.type == TT_STRING)
         {
             StripDoubleQuotes(token.string);
             if (strlen(ptr) + strlen(token.string) + 1 > MAX_MESSAGE_SIZE)
             {
                 SourceError(source, "chat message too long");
                 return qfalse;
             } //end if
             strcat(ptr, token.string);
         } //end else if
         //variable string
         else if (token.type == TT_NUMBER && (token.subtype & TT_INTEGER))
         {
             if (strlen(ptr) + 7 > MAX_MESSAGE_SIZE)
             {
                 SourceError(source, "chat message too long");
                 return qfalse;
             } //end if
             sprintf(&ptr[strlen(ptr)], "%cv%ld%c", ESCAPE_CHAR, token.intvalue, ESCAPE_CHAR);
         } //end if
         //random string
         else if (token.type == TT_NAME)
         {
             if (strlen(ptr) + 7 > MAX_MESSAGE_SIZE)
             {
                 SourceError(source, "chat message too long");
                 return qfalse;
             } //end if
             sprintf(&ptr[strlen(ptr)], "%cr%s%c", ESCAPE_CHAR, token.string, ESCAPE_CHAR);
         } //end else if
         else
         {
             SourceError(source, "unknown message component %s", token.string);
             return qfalse;
         } //end else
         if (PC_CheckTokenString(source, ";")) break;
         if (!PC_ExpectTokenString(source, ",")) return qfalse;
     } //end while
     //
     return qtrue;
 } //end of the function BotLoadChatMessage
Referenced by BotLoadInitialChat(), BotLoadRandomStrings(), and BotLoadReplyChat().
BotLoadInitialChat()
bot_chat_t* BotLoadInitialChat (char * chatfile, char * chatname)
Definition at line 2032 of file be_ai_chat.c.
 {
     int pass, foundchat, indent, size;
     char *ptr = NULL;
     char chatmessagestring[MAX_MESSAGE_SIZE];
     source_t *source;
     token_t token;
     bot_chat_t *chat = NULL;
     bot_chattype_t *chattype = NULL;
     bot_chatmessage_t *chatmessage = NULL;
 #ifdef DEBUG
     int starttime;
     starttime = Sys_MilliSeconds();
 #endif //DEBUG
     //
     size = 0;
     foundchat = qfalse;
     //a bot chat is parsed in two phases
     for (pass = 0; pass < 2; pass++)
     {
         //allocate memory
         if (pass && size) ptr = (char *) GetClearedMemory(size);
         //load the source file
         PC_SetBaseFolder(BOTFILESBASEFOLDER);
         source = LoadSourceFile(chatfile);
         if (!source)
         {
             botimport.Print(PRT_ERROR, "counldn't load %s\n", chatfile);
             return NULL;
         } //end if
         //chat structure
         if (pass)
         {
             chat = (bot_chat_t *) ptr;
             ptr += sizeof(bot_chat_t);
         } //end if
         size = sizeof(bot_chat_t);
         //
         while(PC_ReadToken(source, &token))
         {
             if (!strcmp(token.string, "chat"))
             {
                 if (!PC_ExpectTokenType(source, TT_STRING, 0, &token))
                 {
                     FreeSource(source);
                     return NULL;
                 } //end if
                 StripDoubleQuotes(token.string);
                 //after the chat name we expect an opening brace
                 if (!PC_ExpectTokenString(source, "{"))
                 {
                     FreeSource(source);
                     return NULL;
                 } //end if
                 //if the chat name is found
                 if (!Q_stricmp(token.string, chatname))
                 {
                     foundchat = qtrue;
                     //read the chat types
                     while(1)
                     {
                         if (!PC_ExpectAnyToken(source, &token))
{
                             FreeSource(source);
                             return NULL;
                         } //end if
                         if (!strcmp(token.string, "}")) break;
                         if (strcmp(token.string, "type"))
{
                             SourceError(source, "expected type found %s", token.string);
                             FreeSource(source);
                             return NULL;
                         } //end if
                         //expect the chat type name
                         if (!PC_ExpectTokenType(source, TT_STRING, 0, &token) ||
                             !PC_ExpectTokenString(source, "{"))
{
                             FreeSource(source);
                             return NULL;
                         } //end if
                         StripDoubleQuotes(token.string);
                         if (pass && ptr)
{
                             chattype = (bot_chattype_t *) ptr;
                             Q_strncpyz(chattype->name, token.string, MAX_CHATTYPE_NAME);
                             chattype->firstchatmessage = NULL;
                             //add the chat type to the chat
                             chattype->next = chat->types;
                             chat->types = chattype;
                             //
                             ptr += sizeof(bot_chattype_t);
                         } //end if
                         size += sizeof(bot_chattype_t);
                         //read the chat messages
                         while(!PC_CheckTokenString(source, "}"))
{
                             size_t len;
                             if (!BotLoadChatMessage(source, chatmessagestring))
{
                                 FreeSource(source);
                                 return NULL;
                             } //end if
                             len = strlen(chatmessagestring) + 1;
                             len = PAD(len, sizeof(long));
                             if (pass && ptr)
{
                                 chatmessage = (bot_chatmessage_t *) ptr;
                                 chatmessage->time = -2*CHATMESSAGE_RECENTTIME;
                                 //put the chat message in the list
                                 chatmessage->next = chattype->firstchatmessage;
                                 chattype->firstchatmessage = chatmessage;
                                 //store the chat message
                                 ptr += sizeof(bot_chatmessage_t);
                                 chatmessage->chatmessage = ptr;
                                 strcpy(chatmessage->chatmessage, chatmessagestring);
                                 ptr += len;
                                 //the number of chat messages increased
                                 chattype->numchatmessages++;
                             } //end if
                             size += sizeof(bot_chatmessage_t) + len;
                         } //end if
                     } //end while
                 } //end if
                 else //skip the bot chat
                 {
                     indent = 1;
                     while(indent)
                     {
                         if (!PC_ExpectAnyToken(source, &token))
{
                             FreeSource(source);
                             return NULL;
                         } //end if
                         if (!strcmp(token.string, "{")) indent++;
                         else if (!strcmp(token.string, "}")) indent--;
                     } //end while
                 } //end else
             } //end if
             else
             {
                 SourceError(source, "unknown definition %s", token.string);
                 FreeSource(source);
                 return NULL;
             } //end else
         } //end while
         //free the source
         FreeSource(source);
         //if the requested character is not found
         if (!foundchat)
         {
             botimport.Print(PRT_ERROR, "couldn't find chat %s in %s\n", chatname, chatfile);
             return NULL;
         } //end if
     } //end for
     //
     botimport.Print(PRT_MESSAGE, "loaded %s from %s\n", chatname, chatfile);
     //
     //BotDumpInitialChat(chat);
     if (botDeveloper)
     {
         BotCheckInitialChatIntegrety(chat);
     } //end if
 #ifdef DEBUG
     botimport.Print(PRT_MESSAGE, "initial chats loaded in %d msec\n", Sys_MilliSeconds() - starttime);
 #endif //DEBUG
     //character was read successfully
     return chat;
 } //end of the function BotLoadInitialChat
Referenced by BotLoadChatFile().
BotLoadMatchPieces()
bot_matchpiece_t* BotLoadMatchPieces (source_t * source, char * endtoken)
Definition at line 1159 of file be_ai_chat.c.
 {
     int lastwasvariable, emptystring;
     token_t token;
     bot_matchpiece_t *matchpiece, *firstpiece, *lastpiece;
     bot_matchstring_t *matchstring, *lastmatchstring;
     firstpiece = NULL;
     lastpiece = NULL;
     //
     lastwasvariable = qfalse;
     //
     while(PC_ReadToken(source, &token))
     {
         if (token.type == TT_NUMBER && (token.subtype & TT_INTEGER))
         {
             if (token.intvalue >= MAX_MATCHVARIABLES)
             {
                 SourceError(source, "can't have more than %d match variables", MAX_MATCHVARIABLES);
                 FreeSource(source);
                 BotFreeMatchPieces(firstpiece);
                 return NULL;
             } //end if
             if (lastwasvariable)
             {
                 SourceError(source, "not allowed to have adjacent variables");
                 FreeSource(source);
                 BotFreeMatchPieces(firstpiece);
                 return NULL;
             } //end if
             lastwasvariable = qtrue;
             //
             matchpiece = (bot_matchpiece_t *) GetClearedHunkMemory(sizeof(bot_matchpiece_t));
             matchpiece->type = MT_VARIABLE;
             matchpiece->variable = token.intvalue;
             matchpiece->next = NULL;
             if (lastpiece) lastpiece->next = matchpiece;
             else firstpiece = matchpiece;
             lastpiece = matchpiece;
         } //end if
         else if (token.type == TT_STRING)
         {
             //
             matchpiece = (bot_matchpiece_t *) GetClearedHunkMemory(sizeof(bot_matchpiece_t));
             matchpiece->firststring = NULL;
             matchpiece->type = MT_STRING;
             matchpiece->variable = 0;
             matchpiece->next = NULL;
             if (lastpiece) lastpiece->next = matchpiece;
             else firstpiece = matchpiece;
             lastpiece = matchpiece;
             //
             lastmatchstring = NULL;
             emptystring = qfalse;
             //
             do
             {
                 if (matchpiece->firststring)
                 {
                     if (!PC_ExpectTokenType(source, TT_STRING, 0, &token))
                     {
                         FreeSource(source);
                         BotFreeMatchPieces(firstpiece);
                         return NULL;
                     } //end if
                 } //end if
                 StripDoubleQuotes(token.string);
                 matchstring = (bot_matchstring_t *) GetClearedHunkMemory(sizeof(bot_matchstring_t) + strlen(token.string) + 1);
                 matchstring->string = (char *) matchstring + sizeof(bot_matchstring_t);
                 strcpy(matchstring->string, token.string);
                 if (!strlen(token.string)) emptystring = qtrue;
                 matchstring->next = NULL;
                 if (lastmatchstring) lastmatchstring->next = matchstring;
                 else matchpiece->firststring = matchstring;
                 lastmatchstring = matchstring;
             } while(PC_CheckTokenString(source, "|"));
             //if there was no empty string found
             if (!emptystring) lastwasvariable = qfalse;
         } //end if
         else
         {
             SourceError(source, "invalid token %s", token.string);
             FreeSource(source);
             BotFreeMatchPieces(firstpiece);
             return NULL;
         } //end else
         if (PC_CheckTokenString(source, endtoken)) break;
         if (!PC_ExpectTokenString(source, ","))
         {
             FreeSource(source);
             BotFreeMatchPieces(firstpiece);
             return NULL;
         } //end if
     } //end while
     return firstpiece;
 } //end of the function BotLoadMatchPieces
Referenced by BotLoadMatchTemplates(), and BotLoadReplyChat().
BotLoadMatchTemplates()
bot_matchtemplate_t* BotLoadMatchTemplates (char * matchfile)
Definition at line 1278 of file be_ai_chat.c.
 {
     source_t *source;
     token_t token;
     bot_matchtemplate_t *matchtemplate, *matches, *lastmatch;
     unsigned long int context;
     PC_SetBaseFolder(BOTFILESBASEFOLDER);
     source = LoadSourceFile(matchfile);
     if (!source)
     {
         botimport.Print(PRT_ERROR, "counldn't load %s\n", matchfile);
         return NULL;
     } //end if
     //
     matches = NULL; //list with matches
     lastmatch = NULL; //last match in the list
     while(PC_ReadToken(source, &token))
     {
         if (token.type != TT_NUMBER || !(token.subtype & TT_INTEGER))
         {
             SourceError(source, "expected integer, found %s", token.string);
             BotFreeMatchTemplates(matches);
             FreeSource(source);
             return NULL;
         } //end if
         //the context
         context = token.intvalue;
         //
         if (!PC_ExpectTokenString(source, "{"))
         {
             BotFreeMatchTemplates(matches);
             FreeSource(source);
             return NULL;
         } //end if
         //
         while(PC_ReadToken(source, &token))
         {
             if (!strcmp(token.string, "}")) break;
             //
             PC_UnreadLastToken(source);
             //
             matchtemplate = (bot_matchtemplate_t *) GetClearedHunkMemory(sizeof(bot_matchtemplate_t));
             matchtemplate->context = context;
             matchtemplate->next = NULL;
             //add the match template to the list
             if (lastmatch) lastmatch->next = matchtemplate;
             else matches = matchtemplate;
             lastmatch = matchtemplate;
             //load the match template
             matchtemplate->first = BotLoadMatchPieces(source, "=");
             if (!matchtemplate->first)
             {
                 BotFreeMatchTemplates(matches);
                 return NULL;
             } //end if
             //read the match type
             if (!PC_ExpectTokenString(source, "(") ||
                 !PC_ExpectTokenType(source, TT_NUMBER, TT_INTEGER, &token))
             {
                 BotFreeMatchTemplates(matches);
                 FreeSource(source);
                 return NULL;
             } //end if
             matchtemplate->type = token.intvalue;
             //read the match subtype
             if (!PC_ExpectTokenString(source, ",") ||
                 !PC_ExpectTokenType(source, TT_NUMBER, TT_INTEGER, &token))
             {
                 BotFreeMatchTemplates(matches);
                 FreeSource(source);
                 return NULL;
             } //end if
             matchtemplate->subtype = token.intvalue;
             //read trailing punctuations
             if (!PC_ExpectTokenString(source, ")") ||
                 !PC_ExpectTokenString(source, ";"))
             {
                 BotFreeMatchTemplates(matches);
                 FreeSource(source);
                 return NULL;
             } //end if
         } //end while
     } //end while
     //free the source
     FreeSource(source);
     botimport.Print(PRT_MESSAGE, "loaded %s\n", matchfile);
     //
     //BotDumpMatchTemplates(matches);
     //
     return matches;
 } //end of the function BotLoadMatchTemplates
Referenced by BotSetupChatAI().
BotLoadRandomStrings()
bot_randomlist_t* BotLoadRandomStrings (char * filename)
Definition at line 961 of file be_ai_chat.c.
 {
     int pass, size;
     char *ptr = NULL, chatmessagestring[MAX_MESSAGE_SIZE];
     source_t *source;
     token_t token;
     bot_randomlist_t *randomlist, *lastrandom, *random;
     bot_randomstring_t *randomstring;
 #ifdef DEBUG
     int starttime = Sys_MilliSeconds();
 #endif //DEBUG
     size = 0;
     randomlist = NULL;
     random = NULL;
     //the synonyms are parsed in two phases
     for (pass = 0; pass < 2; pass++)
     {
         //
         if (pass && size) ptr = (char *) GetClearedHunkMemory(size);
         //
         PC_SetBaseFolder(BOTFILESBASEFOLDER);
         source = LoadSourceFile(filename);
         if (!source)
         {
             botimport.Print(PRT_ERROR, "counldn't load %s\n", filename);
             return NULL;
         } //end if
         //
         randomlist = NULL; //list
         lastrandom = NULL; //last
         //
         while(PC_ReadToken(source, &token))
         {
             size_t len;
             if (token.type != TT_NAME)
             {
                 SourceError(source, "unknown random %s", token.string);
                 FreeSource(source);
                 return NULL;
             } //end if
             len = strlen(token.string) + 1;
             len = PAD(len, sizeof(long));
             size += sizeof(bot_randomlist_t) + len;
             if (pass && ptr)
             {
                 random = (bot_randomlist_t *) ptr;
                 ptr += sizeof(bot_randomlist_t);
                 random->string = ptr;
                 ptr += len;
                 strcpy(random->string, token.string);
                 random->firstrandomstring = NULL;
                 random->numstrings = 0;
                 //
                 if (lastrandom) lastrandom->next = random;
                 else randomlist = random;
                 lastrandom = random;
             } //end if
             if (!PC_ExpectTokenString(source, "=") ||
                 !PC_ExpectTokenString(source, "{"))
             {
                 FreeSource(source);
                 return NULL;
             } //end if
             while(!PC_CheckTokenString(source, "}"))
             {
                 if (!BotLoadChatMessage(source, chatmessagestring))
                 {
                     FreeSource(source);
                     return NULL;
                 } //end if
                 len = strlen(chatmessagestring) + 1;
                 len = PAD(len, sizeof(long));
                 size += sizeof(bot_randomstring_t) + len;
                 if (pass && ptr)
                 {
                     randomstring = (bot_randomstring_t *) ptr;
                     ptr += sizeof(bot_randomstring_t);
                     randomstring->string = ptr;
                     ptr += len;
                     strcpy(randomstring->string, chatmessagestring);
                     //
                     random->numstrings++;
                     randomstring->next = random->firstrandomstring;
                     random->firstrandomstring = randomstring;
                 } //end if
             } //end while
         } //end while
         //free the source after one pass
         FreeSource(source);
     } //end for
     botimport.Print(PRT_MESSAGE, "loaded %s\n", filename);
     //
 #ifdef DEBUG
     botimport.Print(PRT_MESSAGE, "random strings %d msec\n", Sys_MilliSeconds() - starttime);
     //BotDumpRandomStringList(randomlist);
 #endif //DEBUG
     //
     return randomlist;
 } //end of the function BotLoadRandomStrings
Referenced by BotSetupChatAI().
BotLoadReplyChat()
bot_replychat_t* BotLoadReplyChat (char * filename)
Definition at line 1847 of file be_ai_chat.c.
 {
     char chatmessagestring[MAX_MESSAGE_SIZE];
     char namebuffer[MAX_MESSAGE_SIZE];
     source_t *source;
     token_t token;
     bot_chatmessage_t *chatmessage = NULL;
     bot_replychat_t *replychat, *replychatlist;
     bot_replychatkey_t *key;
     PC_SetBaseFolder(BOTFILESBASEFOLDER);
     source = LoadSourceFile(filename);
     if (!source)
     {
         botimport.Print(PRT_ERROR, "counldn't load %s\n", filename);
         return NULL;
     } //end if
     //
     replychatlist = NULL;
     //
     while(PC_ReadToken(source, &token))
     {
         if (strcmp(token.string, "["))
         {
             SourceError(source, "expected [, found %s", token.string);
             BotFreeReplyChat(replychatlist);
             FreeSource(source);
             return NULL;
         } //end if
         //
         replychat = GetClearedHunkMemory(sizeof(bot_replychat_t));
         replychat->keys = NULL;
         replychat->next = replychatlist;
         replychatlist = replychat;
         //read the keys, there must be at least one key
         do
         {
             //allocate a key
             key = (bot_replychatkey_t *) GetClearedHunkMemory(sizeof(bot_replychatkey_t));
             key->flags = 0;
             key->string = NULL;
             key->match = NULL;
             key->next = replychat->keys;
             replychat->keys = key;
             //check for MUST BE PRESENT and MUST BE ABSENT keys
             if (PC_CheckTokenString(source, "&")) key->flags |= RCKFL_AND;
             else if (PC_CheckTokenString(source, "!")) key->flags |= RCKFL_NOT;
             //special keys
             if (PC_CheckTokenString(source, "name")) key->flags |= RCKFL_NAME;
             else if (PC_CheckTokenString(source, "female")) key->flags |= RCKFL_GENDERFEMALE;
             else if (PC_CheckTokenString(source, "male")) key->flags |= RCKFL_GENDERMALE;
             else if (PC_CheckTokenString(source, "it")) key->flags |= RCKFL_GENDERLESS;
             else if (PC_CheckTokenString(source, "(")) //match key
             {
                 key->flags |= RCKFL_VARIABLES;
                 key->match = BotLoadMatchPieces(source, ")");
                 if (!key->match)
                 {
                     BotFreeReplyChat(replychatlist);
                     return NULL;
                 } //end if
             } //end else if
             else if (PC_CheckTokenString(source, "<")) //bot names
             {
                 key->flags |= RCKFL_BOTNAMES;
                 strcpy(namebuffer, "");
                 do
                 {
                     if (!PC_ExpectTokenType(source, TT_STRING, 0, &token))
                     {
                         BotFreeReplyChat(replychatlist);
                         FreeSource(source);
                         return NULL;
                     } //end if
                     StripDoubleQuotes(token.string);
                     if (strlen(namebuffer)) strcat(namebuffer, "\\");
                     strcat(namebuffer, token.string);
                 } while(PC_CheckTokenString(source, ","));
                 if (!PC_ExpectTokenString(source, ">"))
                 {
                     BotFreeReplyChat(replychatlist);
                     FreeSource(source);
                     return NULL;
                 } //end if
                 key->string = (char *) GetClearedHunkMemory(strlen(namebuffer) + 1);
                 strcpy(key->string, namebuffer);
             } //end else if
             else //normal string key
             {
                 key->flags |= RCKFL_STRING;
                 if (!PC_ExpectTokenType(source, TT_STRING, 0, &token))
                 {
                     BotFreeReplyChat(replychatlist);
                     FreeSource(source);
                     return NULL;
                 } //end if
                 StripDoubleQuotes(token.string);
                 key->string = (char *) GetClearedHunkMemory(strlen(token.string) + 1);
                 strcpy(key->string, token.string);
             } //end else
             //
             PC_CheckTokenString(source, ",");
         } while(!PC_CheckTokenString(source, "]"));
         //
         BotCheckValidReplyChatKeySet(source, replychat->keys);
         //read the = sign and the priority
         if (!PC_ExpectTokenString(source, "=") ||
             !PC_ExpectTokenType(source, TT_NUMBER, 0, &token))
         {
             BotFreeReplyChat(replychatlist);
             FreeSource(source);
             return NULL;
         } //end if
         replychat->priority = token.floatvalue;
         //read the leading {
         if (!PC_ExpectTokenString(source, "{"))
         {
             BotFreeReplyChat(replychatlist);
             FreeSource(source);
             return NULL;
         } //end if
         replychat->numchatmessages = 0;
         //while the trailing } is not found
         while(!PC_CheckTokenString(source, "}"))
         {
             if (!BotLoadChatMessage(source, chatmessagestring))
             {
                 BotFreeReplyChat(replychatlist);
                 FreeSource(source);
                 return NULL;
             } //end if
             chatmessage = (bot_chatmessage_t *) GetClearedHunkMemory(sizeof(bot_chatmessage_t) + strlen(chatmessagestring) + 1);
             chatmessage->chatmessage = (char *) chatmessage + sizeof(bot_chatmessage_t);
             strcpy(chatmessage->chatmessage, chatmessagestring);
             chatmessage->time = -2*CHATMESSAGE_RECENTTIME;
             chatmessage->next = replychat->firstchatmessage;
             //add the chat message to the reply chat
             replychat->firstchatmessage = chatmessage;
             replychat->numchatmessages++;
         } //end while
     } //end while
     FreeSource(source);
     botimport.Print(PRT_MESSAGE, "loaded %s\n", filename);
     //
     //BotDumpReplyChat(replychatlist);
     if (botDeveloper)
     {
         BotCheckReplyChatIntegrety(replychatlist);
     } //end if
     //
     if (!replychatlist) botimport.Print(PRT_MESSAGE, "no rchats\n");
     //
     return replychatlist;
 } //end of the function BotLoadReplyChat
Referenced by BotSetupChatAI().
BotLoadSynonyms()
bot_synonymlist_t* BotLoadSynonyms (char * filename)
Definition at line 608 of file be_ai_chat.c.
 {
     int pass, size, contextlevel, numsynonyms;
     unsigned long int context, contextstack[32];
     char *ptr = NULL;
     source_t *source;
     token_t token;
     bot_synonymlist_t *synlist, *lastsyn, *syn;
     bot_synonym_t *synonym, *lastsynonym;
     size = 0;
     synlist = NULL; //make compiler happy
     syn = NULL; //make compiler happy
     synonym = NULL; //make compiler happy
     //the synonyms are parsed in two phases
     for (pass = 0; pass < 2; pass++)
     {
         //
         if (pass && size) ptr = (char *) GetClearedHunkMemory(size);
         //
         PC_SetBaseFolder(BOTFILESBASEFOLDER);
         source = LoadSourceFile(filename);
         if (!source)
         {
             botimport.Print(PRT_ERROR, "counldn't load %s\n", filename);
             return NULL;
         } //end if
         //
         context = 0;
         contextlevel = 0;
         synlist = NULL; //list synonyms
         lastsyn = NULL; //last synonym in the list
         //
         while(PC_ReadToken(source, &token))
         {
             if (token.type == TT_NUMBER)
             {
                 context |= token.intvalue;
                 contextstack[contextlevel] = token.intvalue;
                 contextlevel++;
                 if (contextlevel >= 32)
                 {
                     SourceError(source, "more than 32 context levels");
                     FreeSource(source);
                     return NULL;
                 } //end if
                 if (!PC_ExpectTokenString(source, "{"))
                 {
                     FreeSource(source);
                     return NULL;
                 } //end if
             } //end if
             else if (token.type == TT_PUNCTUATION)
             {
                 if (!strcmp(token.string, "}"))
                 {
                     contextlevel--;
                     if (contextlevel < 0)
                     {
                         SourceError(source, "too many }");
                         FreeSource(source);
                         return NULL;
                     } //end if
                     context &= ~contextstack[contextlevel];
                 } //end if
                 else if (!strcmp(token.string, "["))
                 {
                     size += sizeof(bot_synonymlist_t);
                     if (pass && ptr)
                     {
                         syn = (bot_synonymlist_t *) ptr;
                         ptr += sizeof(bot_synonymlist_t);
                         syn->context = context;
                         syn->firstsynonym = NULL;
                         syn->next = NULL;
                         if (lastsyn) lastsyn->next = syn;
                         else synlist = syn;
                         lastsyn = syn;
                     } //end if
                     numsynonyms = 0;
                     lastsynonym = NULL;
                     while(1)
                     {
                         size_t len;
                         if (!PC_ExpectTokenString(source, "(") ||
                             !PC_ExpectTokenType(source, TT_STRING, 0, &token))
{
                             FreeSource(source);
                             return NULL;
                         } //end if
                         StripDoubleQuotes(token.string);
                         if (strlen(token.string) <= 0)
{
                             SourceError(source, "empty string");
                             FreeSource(source);
                             return NULL;
                         } //end if
                         len = strlen(token.string) + 1;
                         len = PAD(len, sizeof(long));
                         size += sizeof(bot_synonym_t) + len;
                         if (pass && ptr)
{
                             synonym = (bot_synonym_t *) ptr;
                             ptr += sizeof(bot_synonym_t);
                             synonym->string = ptr;
                             ptr += len;
                             strcpy(synonym->string, token.string);
                             //
                             if (lastsynonym) lastsynonym->next = synonym;
                             else syn->firstsynonym = synonym;
                             lastsynonym = synonym;
                         } //end if
                         numsynonyms++;
                         if (!PC_ExpectTokenString(source, ",") ||
                             !PC_ExpectTokenType(source, TT_NUMBER, 0, &token) ||
                             !PC_ExpectTokenString(source, ")"))
{
                             FreeSource(source);
                             return NULL;
                         } //end if
                         if (pass && ptr)
{
                             synonym->weight = token.floatvalue;
                             syn->totalweight += synonym->weight;
                         } //end if
                         if (PC_CheckTokenString(source, "]")) break;
                         if (!PC_ExpectTokenString(source, ","))
{
                             FreeSource(source);
                             return NULL;
                         } //end if
                     } //end while
                     if (numsynonyms < 2)
                     {
                         SourceError(source, "synonym must have at least two entries");
                         FreeSource(source);
                         return NULL;
                     } //end if
                 } //end else
                 else
                 {
                     SourceError(source, "unexpected %s", token.string);
                     FreeSource(source);
                     return NULL;
                 } //end if
             } //end else if
         } //end while
         //
         FreeSource(source);
         //
         if (contextlevel > 0)
         {
             SourceError(source, "missing }");
             return NULL;
         } //end if
     } //end for
     botimport.Print(PRT_MESSAGE, "loaded %s\n", filename);
     //
     //BotDumpSynonymList(synlist);
     //
     return synlist;
 } //end of the function BotLoadSynonyms
Referenced by BotSetupChatAI().
BotMatchVariable()
void BotMatchVariable (bot_match_t * match, int variable, char * buf, int size)
Definition at line 1488 of file be_ai_chat.c.
 {
     if (variable < 0 || variable >= MAX_MATCHVARIABLES)
     {
         botimport.Print(PRT_FATAL, "BotMatchVariable: variable out of range\n");
         strcpy(buf, "");
         return;
     } //end if
     if (match->variables[variable].offset >= 0)
     {
         if (match->variables[variable].length < size)
             size = match->variables[variable].length+1;
         assert( match->variables[variable].offset >= 0 );
         strncpy(buf, &match->string[ (int) match->variables[variable].offset], size-1);
         buf[size-1] = '\0';
     } //end if
     else
     {
         strcpy(buf, "");
     } //end else
 } //end of the function BotMatchVariable
Referenced by Init_AI_Export().
BotNextConsoleMessage()
int BotNextConsoleMessage (int chatstate, bot_consolemessage_t * cm)
Definition at line 367 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     bot_consolemessage_t *firstmsg;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     if ((firstmsg = cs->firstmessage))
     {
         cm->handle = firstmsg->handle;
         cm->time = firstmsg->time;
         cm->type = firstmsg->type;
         Q_strncpyz(cm->message, firstmsg->message,
                sizeof(cm->message));
         /* We omit setting the two pointers in cm because pointer
          * size in the VM differs between the size in the engine on
          * 64 bit machines, which would lead to a buffer overflow if
          * this functions is called from the VM. The pointers are
          * of no interest to functions calling
          * BotNextConsoleMessage anyways.
          */
         return cm->handle;
     } //end if
     return 0;
 } //end of the function BotConsoleMessage
Referenced by BotFreeChatState(), and Init_AI_Export().
BotNumConsoleMessages()
int BotNumConsoleMessages (int chatstate)
Definition at line 400 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     return cs->numconsolemessages;
 } //end of the function BotNumConsoleMessages
Referenced by Init_AI_Export().
BotNumInitialChats()
int BotNumInitialChats (int chatstate, char * type)
Definition at line 2487 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     bot_chattype_t *t;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     for (t = cs->chat->types; t; t = t->next)
     {
         if (!Q_stricmp(t->name, type))
         {
             if (LibVarGetValue("bot_testichat")) {
                 botimport.Print(PRT_MESSAGE, "%s has %d chat lines\n", type, t->numchatmessages);
                 botimport.Print(PRT_MESSAGE, "-------------------\n");
             }
             return t->numchatmessages;
         } //end if
     } //end for
     return 0;
 } //end of the function BotNumInitialChats
Referenced by Init_AI_Export().
BotPrintReplyChatKeys()
void BotPrintReplyChatKeys (bot_replychat_t * replychat)
Definition at line 2594 of file be_ai_chat.c.
 {
     bot_replychatkey_t *key;
     bot_matchpiece_t *mp;
     botimport.Print(PRT_MESSAGE, "[");
     for (key = replychat->keys; key; key = key->next)
     {
         if (key->flags & RCKFL_AND) botimport.Print(PRT_MESSAGE, "&");
         else if (key->flags & RCKFL_NOT) botimport.Print(PRT_MESSAGE, "!");
         //
         if (key->flags & RCKFL_NAME) botimport.Print(PRT_MESSAGE, "name");
         else if (key->flags & RCKFL_GENDERFEMALE) botimport.Print(PRT_MESSAGE, "female");
         else if (key->flags & RCKFL_GENDERMALE) botimport.Print(PRT_MESSAGE, "male");
         else if (key->flags & RCKFL_GENDERLESS) botimport.Print(PRT_MESSAGE, "it");
         else if (key->flags & RCKFL_VARIABLES)
         {
             botimport.Print(PRT_MESSAGE, "(");
             for (mp = key->match; mp; mp = mp->next)
             {
                 if (mp->type == MT_STRING) botimport.Print(PRT_MESSAGE, "\"%s\"", mp->firststring->string);
                 else botimport.Print(PRT_MESSAGE, "%d", mp->variable);
                 if (mp->next) botimport.Print(PRT_MESSAGE, ", ");
             } //end for
             botimport.Print(PRT_MESSAGE, ")");
         } //end if
         else if (key->flags & RCKFL_STRING)
         {
             botimport.Print(PRT_MESSAGE, "\"%s\"", key->string);
         } //end if
         if (key->next) botimport.Print(PRT_MESSAGE, ", ");
         else botimport.Print(PRT_MESSAGE, "] = %1.0f\n", replychat->priority);
     } //end for
     botimport.Print(PRT_MESSAGE, "{\n");
 } //end of the function BotPrintReplyChatKeys
BotQueueConsoleMessage()
void BotQueueConsoleMessage (int chatstate, int type, char * message)
Definition at line 326 of file be_ai_chat.c.
 {
     bot_consolemessage_t *m;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     m = AllocConsoleMessage();
     if (!m)
     {
         botimport.Print(PRT_ERROR, "empty console message heap\n");
         return;
     } //end if
     cs->handle++;
     if (cs->handle <= 0 || cs->handle > 8192) cs->handle = 1;
     m->handle = cs->handle;
     m->time = AAS_Time();
     m->type = type;
     Q_strncpyz(m->message, message, MAX_MESSAGE_SIZE);
     m->next = NULL;
     if (cs->lastmessage)
     {
         cs->lastmessage->next = m;
         m->prev = cs->lastmessage;
         cs->lastmessage = m;
     } //end if
     else
     {
         cs->lastmessage = m;
         cs->firstmessage = m;
         m->prev = NULL;
     } //end if
     cs->numconsolemessages++;
 } //end of the function BotQueueConsoleMessage
Referenced by Init_AI_Export().
BotRemoveConsoleMessage()
void BotRemoveConsoleMessage (int chatstate, int handle)
Definition at line 296 of file be_ai_chat.c.
 {
     bot_consolemessage_t *m, *nextm;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     for (m = cs->firstmessage; m; m = nextm)
     {
         nextm = m->next;
         if (m->handle == handle)
         {
             if (m->next) m->next->prev = m->prev;
             else cs->lastmessage = m->prev;
             if (m->prev) m->prev->next = m->next;
             else cs->firstmessage = m->next;
             FreeConsoleMessage(m);
             cs->numconsolemessages--;
             break;
         } //end if
     } //end for
 } //end of the function BotRemoveConsoleMessage
Referenced by BotFreeChatState(), and Init_AI_Export().
BotRemoveTildes()
void BotRemoveTildes (char * message)
Definition at line 434 of file be_ai_chat.c.
 {
     int i;
     //remove all tildes from the chat message
     for (i = 0; message[i]; i++)
     {
         if (message[i] == '~')
         {
             memmove(&message[i], &message[i+1], strlen(&message[i+1])+1);
         } //end if
     } //end for
 } //end of the function BotRemoveTildes
Referenced by BotEnterChat(), BotGetChatMessage(), and BotReplyChat().
BotReplaceReplySynonyms()
void BotReplaceReplySynonyms (char * string, unsigned long int context)
Definition at line 830 of file be_ai_chat.c.
 {
     char *str1, *str2, *replacement;
     bot_synonymlist_t *syn;
     bot_synonym_t *synonym;
     for (str1 = string; *str1; )
     {
         //go to the start of the next word
         while(*str1 && *str1 <= ' ') str1++;
         if (!*str1) break;
         //
         for (syn = synonyms; syn; syn = syn->next)
         {
             if (!(syn->context & context)) continue;
             for (synonym = syn->firstsynonym->next; synonym; synonym = synonym->next)
             {
                 //if the synonym is not at the front of the string continue
                 str2 = StringContainsWord(str1, synonym->string, qfalse);
                 if (!str2 || str2 != str1) continue;
                 //
                 replacement = syn->firstsynonym->string;
                 //if the replacement IS in front of the string continue
                 str2 = StringContainsWord(str1, replacement, qfalse);
                 if (str2 && str2 == str1) continue;
                 //
                 memmove(str1 + strlen(replacement), str1+strlen(synonym->string),
                             strlen(str1+strlen(synonym->string)) + 1);
                 //append the synonum replacement
                 Com_Memcpy(str1, replacement, strlen(replacement));
                 //
                 break;
             } //end for
             //if a synonym has been replaced
             if (synonym) break;
         } //end for
         //skip over this word
         while(*str1 && *str1 > ' ') str1++;
         if (!*str1) break;
     } //end while
 } //end of the function BotReplaceReplySynonyms
Referenced by BotExpandChatMessage().
BotReplaceSynonyms()
void BotReplaceSynonyms (char * string, unsigned long int context)
Definition at line 777 of file be_ai_chat.c.
 {
     bot_synonymlist_t *syn;
     bot_synonym_t *synonym;
     for (syn = synonyms; syn; syn = syn->next)
     {
         if (!(syn->context & context)) continue;
         for (synonym = syn->firstsynonym->next; synonym; synonym = synonym->next)
         {
             StringReplaceWords(string, synonym->string, syn->firstsynonym->string);
         } //end for
     } //end for
 } //end of the function BotReplaceSynonyms
Referenced by BotExpandChatMessage(), and Init_AI_Export().
BotReplaceWeightedSynonyms()
void BotReplaceWeightedSynonyms (char * string, unsigned long int context)
Definition at line 797 of file be_ai_chat.c.
 {
     bot_synonymlist_t *syn;
     bot_synonym_t *synonym, *replacement;
     float weight, curweight;
     for (syn = synonyms; syn; syn = syn->next)
     {
         if (!(syn->context & context)) continue;
         //choose a weighted random replacement synonym
         weight = random() * syn->totalweight;
         if (!weight) continue;
         curweight = 0;
         for (replacement = syn->firstsynonym; replacement; replacement = replacement->next)
         {
             curweight += replacement->weight;
             if (weight < curweight) break;
         } //end for
         if (!replacement) continue;
         //replace all synonyms with the replacement
         for (synonym = syn->firstsynonym; synonym; synonym = synonym->next)
         {
             if (synonym == replacement) continue;
             StringReplaceWords(string, synonym->string, replacement->string);
         } //end for
     } //end for
 } //end of the function BotReplaceWeightedSynonyms
Referenced by BotExpandChatMessage().
BotReplyChat()
int BotReplyChat (int chatstate, char * message, int mcontext, int vcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 2635 of file be_ai_chat.c.
 {
     bot_replychat_t *rchat, *bestrchat;
     bot_replychatkey_t *key;
     bot_chatmessage_t *m, *bestchatmessage;
     bot_match_t match, bestmatch;
     int bestpriority, num, found, res, numchatmessages, index;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return qfalse;
     Com_Memset(&match, 0, sizeof(bot_match_t));
     strcpy(match.string, message);
     bestpriority = -1;
     bestchatmessage = NULL;
     bestrchat = NULL;
     //go through all the reply chats
     for (rchat = replychats; rchat; rchat = rchat->next)
     {
         found = qfalse;
         for (key = rchat->keys; key; key = key->next)
         {
             res = qfalse;
             //get the match result
             if (key->flags & RCKFL_NAME) res = (StringContains(message, cs->name, qfalse) != -1);
             else if (key->flags & RCKFL_BOTNAMES) res = (StringContains(key->string, cs->name, qfalse) != -1);
             else if (key->flags & RCKFL_GENDERFEMALE) res = (cs->gender == CHAT_GENDERFEMALE);
             else if (key->flags & RCKFL_GENDERMALE) res = (cs->gender == CHAT_GENDERMALE);
             else if (key->flags & RCKFL_GENDERLESS) res = (cs->gender == CHAT_GENDERLESS);
             else if (key->flags & RCKFL_VARIABLES) res = StringsMatch(key->match, &match);
             else if (key->flags & RCKFL_STRING) res = (StringContainsWord(message, key->string, qfalse) != NULL);
             //if the key must be present
             if (key->flags & RCKFL_AND)
             {
                 if (!res)
                 {
                     found = qfalse;
                     break;
                 } //end if
             } //end else if
             //if the key must be absent
             else if (key->flags & RCKFL_NOT)
             {
                 if (res)
                 {
                     found = qfalse;
                     break;
                 } //end if
             } //end if
             else if (res)
             {
                 found = qtrue;
             } //end else
         } //end for
         //
         if (found)
         {
             if (rchat->priority > bestpriority)
             {
                 numchatmessages = 0;
                 for (m = rchat->firstchatmessage; m; m = m->next)
                 {
                     if (m->time > AAS_Time()) continue;
                     numchatmessages++;
                 } //end if
                 num = random() * numchatmessages;
                 for (m = rchat->firstchatmessage; m; m = m->next)
                 {
                     if (--num < 0) break;
                     if (m->time > AAS_Time()) continue;
                 } //end for
                 //if the reply chat has a message
                 if (m)
                 {
                     Com_Memcpy(&bestmatch, &match, sizeof(bot_match_t));
                     bestchatmessage = m;
                     bestrchat = rchat;
                     bestpriority = rchat->priority;
                 } //end if
             } //end if
         } //end if
     } //end for
     if (bestchatmessage)
     {
         index = strlen(bestmatch.string);
         if( var0 ) {
             strcat(bestmatch.string, var0);
             bestmatch.variables[0].offset = index;
             bestmatch.variables[0].length = strlen(var0);
             index += strlen(var0);
         }
         if( var1 ) {
             strcat(bestmatch.string, var1);
             bestmatch.variables[1].offset = index;
             bestmatch.variables[1].length = strlen(var1);
             index += strlen(var1);
         }
         if( var2 ) {
             strcat(bestmatch.string, var2);
             bestmatch.variables[2].offset = index;
             bestmatch.variables[2].length = strlen(var2);
             index += strlen(var2);
         }
         if( var3 ) {
             strcat(bestmatch.string, var3);
             bestmatch.variables[3].offset = index;
             bestmatch.variables[3].length = strlen(var3);
             index += strlen(var3);
         }
         if( var4 ) {
             strcat(bestmatch.string, var4);
             bestmatch.variables[4].offset = index;
             bestmatch.variables[4].length = strlen(var4);
             index += strlen(var4);
         }
         if( var5 ) {
             strcat(bestmatch.string, var5);
             bestmatch.variables[5].offset = index;
             bestmatch.variables[5].length = strlen(var5);
             index += strlen(var5);
         }
         if( var6 ) {
             strcat(bestmatch.string, var6);
             bestmatch.variables[6].offset = index;
             bestmatch.variables[6].length = strlen(var6);
             index += strlen(var6);
         }
         if( var7 ) {
             strcat(bestmatch.string, var7);
             bestmatch.variables[7].offset = index;
             bestmatch.variables[7].length = strlen(var7);
         }
         if (LibVarGetValue("bot_testrchat"))
         {
             for (m = bestrchat->firstchatmessage; m; m = m->next)
             {
                 BotConstructChatMessage(cs, m->chatmessage, mcontext, &bestmatch, vcontext, qtrue);
                 BotRemoveTildes(cs->chatmessage);
                 botimport.Print(PRT_MESSAGE, "%s\n", cs->chatmessage);
             } //end if
         } //end if
         else
         {
             bestchatmessage->time = AAS_Time() + CHATMESSAGE_RECENTTIME;
             BotConstructChatMessage(cs, bestchatmessage->chatmessage, mcontext, &bestmatch, vcontext, qtrue);
         } //end else
         return qtrue;
     } //end if
     return qfalse;
 } //end of the function BotReplyChat
Referenced by Init_AI_Export().
BotResetChatAI()
void BotResetChatAI (void)
Definition at line 2896 of file be_ai_chat.c.
 {
     bot_replychat_t *rchat;
     bot_chatmessage_t *m;
     for (rchat = replychats; rchat; rchat = rchat->next)
     {
         for (m = rchat->firstchatmessage; m; m = m->next)
         {
             m->time = 0;
         } //end for
     } //end for
 } //end of the function BotResetChatAI
BotSetChatGender()
void BotSetChatGender (int chatstate, int gender)
Definition at line 2860 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     switch(gender)
     {
         case CHAT_GENDERFEMALE: cs->gender = CHAT_GENDERFEMALE; break;
         case CHAT_GENDERMALE: cs->gender = CHAT_GENDERMALE; break;
         default: cs->gender = CHAT_GENDERLESS; break;
     } //end switch
 } //end of the function BotSetChatGender
Referenced by Init_AI_Export().
BotSetChatName()
void BotSetChatName (int chatstate, char * name, int client)
Definition at line 2879 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     cs->client = client;
     Com_Memset(cs->name, 0, sizeof(cs->name));
     strncpy(cs->name, name, sizeof(cs->name)-1);
     cs->name[sizeof(cs->name)-1] = '\0';
 } //end of the function BotSetChatName
Referenced by Init_AI_Export().
BotSetupChatAI()
int BotSetupChatAI (void)
Definition at line 2969 of file be_ai_chat.c.
 {
     char *file;
 #ifdef DEBUG
     int starttime = Sys_MilliSeconds();
 #endif //DEBUG
     file = LibVarString("synfile", "syn.c");
     synonyms = BotLoadSynonyms(file);
     file = LibVarString("rndfile", "rnd.c");
     randomstrings = BotLoadRandomStrings(file);
     file = LibVarString("matchfile", "match.c");
     matchtemplates = BotLoadMatchTemplates(file);
     //
     if (!LibVarValue("nochat", "0"))
     {
         file = LibVarString("rchatfile", "rchat.c");
         replychats = BotLoadReplyChat(file);
     } //end if
     InitConsoleMessageHeap();
 #ifdef DEBUG
     botimport.Print(PRT_MESSAGE, "setup chat AI %d msec\n", Sys_MilliSeconds() - starttime);
 #endif //DEBUG
     return BLERR_NOERROR;
 } //end of the function BotSetupChatAI
Referenced by Export_BotLibSetup().
BotShutdownChatAI()
void BotShutdownChatAI (void)
Definition at line 3003 of file be_ai_chat.c.
 {
     int i;
     //free all remaining chat states
     for(i = 0; i < MAX_CLIENTS; i++)
     {
         if (botchatstates[i])
         {
             BotFreeChatState(i);
         } //end if
     } //end for
     //free all cached chats
     for(i = 0; i < MAX_CLIENTS; i++)
     {
         if (ichatdata[i])
         {
             FreeMemory(ichatdata[i]->chat);
             FreeMemory(ichatdata[i]);
             ichatdata[i] = NULL;
         } //end if
     } //end for
     if (consolemessageheap) FreeMemory(consolemessageheap);
     consolemessageheap = NULL;
     if (matchtemplates) BotFreeMatchTemplates(matchtemplates);
     matchtemplates = NULL;
     if (randomstrings) FreeMemory(randomstrings);
     randomstrings = NULL;
     if (synonyms) FreeMemory(synonyms);
     synonyms = NULL;
     if (replychats) BotFreeReplyChat(replychats);
     replychats = NULL;
 } //end of the function BotShutdownChatAI
Referenced by Export_BotLibShutdown().
FreeConsoleMessage()
void FreeConsoleMessage (bot_consolemessage_t * message)
Definition at line 283 of file be_ai_chat.c.
 {
     if (freeconsolemessages) freeconsolemessages->prev = message;
     message->prev = NULL;
     message->next = freeconsolemessages;
     freeconsolemessages = message;
 } //end of the function FreeConsoleMessage
Referenced by BotRemoveConsoleMessage().
InitConsoleMessageHeap()
void InitConsoleMessageHeap (void)
Definition at line 240 of file be_ai_chat.c.
 {
     int i, max_messages;
     if (consolemessageheap) FreeMemory(consolemessageheap);
     //
     max_messages = (int) LibVarValue("max_messages", "1024");
     consolemessageheap = (bot_consolemessage_t *) GetClearedHunkMemory(max_messages *
                                                 sizeof(bot_consolemessage_t));
     consolemessageheap[0].prev = NULL;
     consolemessageheap[0].next = &consolemessageheap[1];
     for (i = 1; i < max_messages-1; i++)
     {
         consolemessageheap[i].prev = &consolemessageheap[i - 1];
         consolemessageheap[i].next = &consolemessageheap[i + 1];
     } //end for
     consolemessageheap[max_messages-1].prev = &consolemessageheap[max_messages-2];
     consolemessageheap[max_messages-1].next = NULL;
     //pointer to the free console messages
     freeconsolemessages = consolemessageheap;
 } //end of the function InitConsoleMessageHeap
Referenced by BotSetupChatAI().
IsWhiteSpace()
int IsWhiteSpace (char c)
Definition at line 414 of file be_ai_chat.c.
 {
     if ((c >= 'a' && c <= 'z')
         || (c >= 'A' && c <= 'Z')
         || (c >= '0' && c <= '9')
         || c == '(' || c == ')'
         || c == '?' || c == ':'
         || c == '\''|| c == '/'
         || c == ',' || c == '.'
         || c == '[' || c == ']'
         || c == '-' || c == '_'
         || c == '+' || c == '=') return qfalse;
     return qtrue;
 } //end of the function IsWhiteSpace
Referenced by UnifyWhiteSpaces().
RandomString()
char* RandomString (char * name)
Definition at line 1068 of file be_ai_chat.c.
 {
     bot_randomlist_t *random;
     bot_randomstring_t *rs;
     int i;
     for (random = randomstrings; random; random = random->next)
     {
         if (!strcmp(random->string, name))
         {
             i = random() * random->numstrings;
             for (rs = random->firstrandomstring; rs; rs = rs->next)
             {
                 if (--i < 0) break;
             } //end for
             if (rs)
             {
                 return rs->string;
             } //end if
         } //end for
     } //end for
     return NULL;
 } //end of the function RandomString
Referenced by BotCheckChatMessageIntegrety(), and BotExpandChatMessage().
StringContains()
int StringContains (char * str1, char * str2, int casesensitive)
Definition at line 477 of file be_ai_chat.c.
 {
     int len, i, j, index;
     if (str1 == NULL || str2 == NULL) return -1;
     len = strlen(str1) - strlen(str2);
     index = 0;
     for (i = 0; i <= len; i++, str1++, index++)
     {
         for (j = 0; str2[j]; j++)
         {
             if (casesensitive)
             {
                 if (str1[j] != str2[j]) break;
             } //end if
             else
             {
                 if (toupper(str1[j]) != toupper(str2[j])) break;
             } //end else
         } //end for
         if (!str2[j]) return index;
     } //end for
     return -1;
 } //end of the function StringContains
Referenced by BotCheckValidReplyChatKeySet(), BotReplyChat(), Init_AI_Export(), and StringsMatch().
StringContainsWord()
char* StringContainsWord (char * str1, char * str2, int casesensitive)
Definition at line 508 of file be_ai_chat.c.
 {
     int len, i, j;
     len = strlen(str1) - strlen(str2);
     for (i = 0; i <= len; i++, str1++)
     {
         //if not at the start of the string
         if (i)
         {
             //skip to the start of the next word
             while(*str1 && *str1 != ' ' && *str1 != '.' && *str1 != ',' && *str1 != '!') str1++;
             if (!*str1) break;
             str1++;
         } //end for
         //compare the word
         for (j = 0; str2[j]; j++)
         {
             if (casesensitive)
             {
                 if (str1[j] != str2[j]) break;
             } //end if
             else
             {
                 if (toupper(str1[j]) != toupper(str2[j])) break;
             } //end else
         } //end for
         //if there was a word match
         if (!str2[j])
         {
             //if the first string has an end of word
             if (!str1[j] || str1[j] == ' ' || str1[j] == '.' || str1[j] == ',' || str1[j] == '!') return str1;
         } //end if
     } //end for
     return NULL;
 } //end of the function StringContainsWord
Referenced by BotReplaceReplySynonyms(), BotReplyChat(), and StringReplaceWords().
StringReplaceWords()
void StringReplaceWords (char * string, char * synonym, char * replacement)
Definition at line 550 of file be_ai_chat.c.
 {
     char *str, *str2;
     //find the synonym in the string
     str = StringContainsWord(string, synonym, qfalse);
     //if the synonym occurred in the string
     while(str)
     {
         //if the synonym isn't part of the replacement which is already in the string
         //useful for abbreviations
         str2 = StringContainsWord(string, replacement, qfalse);
         while(str2)
         {
             if (str2 <= str && str < str2 + strlen(replacement)) break;
             str2 = StringContainsWord(str2+1, replacement, qfalse);
         } //end while
         if (!str2)
         {
             memmove(str + strlen(replacement), str+strlen(synonym), strlen(str+strlen(synonym))+1);
             //append the synonum replacement
             Com_Memcpy(str, replacement, strlen(replacement));
         } //end if
         //find the next synonym in the string
         str = StringContainsWord(str+strlen(replacement), synonym, qfalse);
     } //end if
 } //end of the function StringReplaceWords
Referenced by BotReplaceSynonyms(), and BotReplaceWeightedSynonyms().
StringsMatch()
int StringsMatch (bot_matchpiece_t * pieces, bot_match_t * match)
Definition at line 1377 of file be_ai_chat.c.
 {
     int lastvariable, index;
     char *strptr, *newstrptr;
     bot_matchpiece_t *mp;
     bot_matchstring_t *ms;
     //no last variable
     lastvariable = -1;
     //pointer to the string to compare the match string with
     strptr = match->string;
     //Log_Write("match: %s", strptr);
     //compare the string with the current match string
     for (mp = pieces; mp; mp = mp->next)
     {
         //if it is a piece of string
         if (mp->type == MT_STRING)
         {
             newstrptr = NULL;
             for (ms = mp->firststring; ms; ms = ms->next)
             {
                 if (!strlen(ms->string))
                 {
                     newstrptr = strptr;
                     break;
                 } //end if
                 //Log_Write("MT_STRING: %s", mp->string);
                 index = StringContains(strptr, ms->string, qfalse);
                 if (index >= 0)
                 {
                     newstrptr = strptr + index;
                     if (lastvariable >= 0)
                     {
                         match->variables[lastvariable].length =
                                 (newstrptr - match->string) - match->variables[lastvariable].offset;
                                 //newstrptr - match->variables[lastvariable].ptr;
                         lastvariable = -1;
                         break;
                     } //end if
                     else if (index == 0)
                     {
                         break;
                     } //end else
                     newstrptr = NULL;
                 } //end if
             } //end for
             if (!newstrptr) return qfalse;
             strptr = newstrptr + strlen(ms->string);
         } //end if
         //if it is a variable piece of string
         else if (mp->type == MT_VARIABLE)
         {
             //Log_Write("MT_VARIABLE");
             match->variables[mp->variable].offset = strptr - match->string;
             lastvariable = mp->variable;
         } //end else if
     } //end for
     //if a match was found
     if (!mp && (lastvariable >= 0 || !strlen(strptr)))
     {
         //if the last piece was a variable string
         if (lastvariable >= 0)
         {
                 assert( match->variables[lastvariable].offset >= 0 );
             match->variables[lastvariable].length =
                 strlen(&match->string[ (int) match->variables[lastvariable].offset]);
         } //end if
         return qtrue;
     } //end if
     return qfalse;
 } //end of the function StringsMatch
Referenced by BotFindMatch(), and BotReplyChat().
UnifyWhiteSpaces()
void UnifyWhiteSpaces (char * string)
Definition at line 453 of file be_ai_chat.c.
 {
     char *ptr, *oldptr;
     for (ptr = oldptr = string; *ptr; oldptr = ptr)
     {
         while(*ptr && IsWhiteSpace(*ptr)) ptr++;
         if (ptr > oldptr)
         {
             //if not at the start and not at the end of the string
             //write only one space
             if (oldptr > string && *ptr) *oldptr++ = ' ';
             //remove all other white spaces
             if (ptr > oldptr) memmove(oldptr, ptr, strlen(ptr)+1);
         } //end if
         while(*ptr && !IsWhiteSpace(*ptr)) ptr++;
     } //end while
 } //end of the function UnifyWhiteSpaces
Referenced by Init_AI_Export().
Variable Documentation
botchatstates
bot_chatstate_t* botchatstates[MAX_CLIENTS+1]
Definition at line 200 of file be_ai_chat.c.
Referenced by BotAllocChatState(), BotChatStateFromHandle(), BotFreeChatState(), and BotShutdownChatAI().
consolemessageheap
bot_consolemessage_t* consolemessageheap = NULL
Definition at line 202 of file be_ai_chat.c.
Referenced by BotShutdownChatAI(), and InitConsoleMessageHeap().
freeconsolemessages
bot_consolemessage_t* freeconsolemessages = NULL
Definition at line 203 of file be_ai_chat.c.
Referenced by AllocConsoleMessage(), FreeConsoleMessage(), and InitConsoleMessageHeap().
ichatdata
bot_ichatdata_t* ichatdata[MAX_CLIENTS]
Definition at line 198 of file be_ai_chat.c.
Referenced by BotLoadChatFile(), and BotShutdownChatAI().
matchtemplates
bot_matchtemplate_t* matchtemplates = NULL
Definition at line 205 of file be_ai_chat.c.
Referenced by BotFindMatch(), BotSetupChatAI(), and BotShutdownChatAI().
randomstrings
bot_randomlist_t* randomstrings = NULL
Definition at line 209 of file be_ai_chat.c.
Referenced by BotSetupChatAI(), BotShutdownChatAI(), and RandomString().
replychats
bot_replychat_t* replychats = NULL
Definition at line 211 of file be_ai_chat.c.
Referenced by BotReplyChat(), BotResetChatAI(), BotSetupChatAI(), and BotShutdownChatAI().
synonyms
bot_synonymlist_t* synonyms = NULL
Definition at line 207 of file be_ai_chat.c.
Referenced by BotReplaceReplySynonyms(), BotReplaceSynonyms(), BotReplaceWeightedSynonyms(), BotSetupChatAI(), and BotShutdownChatAI().