ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/net_ip.c File Reference
net_ip.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include <winsock2.h>
#include <ws2tcpip.h>
#include <wspiapi.h>
Classes
struct nip_localaddr_t
Macros
#define EAGAIN WSAEWOULDBLOCK
#define EADDRNOTAVAIL WSAEADDRNOTAVAIL
#define EAFNOSUPPORT WSAEAFNOSUPPORT
#define ECONNRESET WSAECONNRESET
#define socketError WSAGetLastError()
#define IF_NAMESIZE 16
#define NET_MULTICAST_IP6 "ff04::696f:7175:616b:6533"
#define MAX_IPS 32
Typedefs
typedef int socklen_t
typedef unsigned short sa_family_t
typedef u_long ioctlarg_t
Functions
char * NET_ErrorString (void)
static void NetadrToSockadr (netadr_t *a, struct sockaddr *s)
static void SockadrToNetadr (struct sockaddr *s, netadr_t *a)
static struct addrinfo * SearchAddrInfo (struct addrinfo *hints, sa_family_t family)
static qboolean Sys_StringToSockaddr (const char *s, struct sockaddr *sadr, int sadr_len, sa_family_t family)
static void Sys_SockaddrToString (char *dest, int destlen, struct sockaddr *input)
qboolean Sys_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
qboolean NET_CompareBaseAdrMask (netadr_t a, netadr_t b, int netmask)
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
const char * NET_AdrToString (netadr_t a)
const char * NET_AdrToStringwPort (netadr_t a)
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
qboolean NET_IsLocalAddress (netadr_t adr)
qboolean NET_GetPacket (netadr_t *net_from, msg_t *net_message, fd_set *fdr)
void Sys_SendPacket (int length, const void *data, netadr_t to)
qboolean Sys_IsLANAddress (netadr_t adr)
void Sys_ShowIP (void)
SOCKET NET_IPSocket (char *net_interface, int port, int *err)
SOCKET NET_IP6Socket (char *net_interface, int port, struct sockaddr_in6 *bindto, int *err)
void NET_SetMulticast6 (void)
void NET_JoinMulticast6 (void)
void NET_LeaveMulticast6 ()
void NET_OpenSocks (int port)
static void NET_AddLocalAddress (char *ifname, struct sockaddr *addr, struct sockaddr *netmask)
static void NET_GetLocalAddress (void)
void NET_OpenIP (void)
static qboolean NET_GetCvars (void)
void NET_Config (qboolean enableNetworking)
void NET_Init (void)
void NET_Shutdown (void)
void NET_Event (fd_set *fdr)
void NET_Sleep (int msec)
void NET_Restart_f (void)
Variables
static WSADATA winsockdata
static qboolean winsockInitialized = qfalse
static qboolean usingSocks = qfalse
static int networkingEnabled = 0
static cvar_t * net_enabled
static cvar_t * net_socksEnabled
static cvar_t * net_socksServer
static cvar_t * net_socksPort
static cvar_t * net_socksUsername
static cvar_t * net_socksPassword
static cvar_t * net_ip
static cvar_t * net_ip6
static cvar_t * net_port
static cvar_t * net_port6
static cvar_t * net_mcast6addr
static cvar_t * net_mcast6iface
static cvar_t * net_dropsim
static struct sockaddr socksRelayAddr
static SOCKET ip_socket = INVALID_SOCKET
static SOCKET ip6_socket = INVALID_SOCKET
static SOCKET socks_socket = INVALID_SOCKET
static SOCKET multicast6_socket = INVALID_SOCKET
static struct ipv6_mreq curgroup
static struct sockaddr_in6 boundto
static nip_localaddr_t localIP [MAX_IPS]
static int numIP
static char socksBuf [4096]
Macro Definition Documentation
EADDRNOTAVAIL
#define EADDRNOTAVAIL WSAEADDRNOTAVAIL
Definition at line 50 of file net_ip.c.
EAFNOSUPPORT
#define EAFNOSUPPORT WSAEAFNOSUPPORT
Definition at line 51 of file net_ip.c.
EAGAIN
#define EAGAIN WSAEWOULDBLOCK
Definition at line 49 of file net_ip.c.
ECONNRESET
#define ECONNRESET WSAECONNRESET
Definition at line 52 of file net_ip.c.
IF_NAMESIZE
#define IF_NAMESIZE 16
Definition at line 127 of file net_ip.c.
MAX_IPS
#define MAX_IPS 32
Definition at line 133 of file net_ip.c.
NET_MULTICAST_IP6
#define NET_MULTICAST_IP6 "ff04::696f:7175:616b:6533"
Definition at line 131 of file net_ip.c.
socketError
#define socketError WSAGetLastError()
Definition at line 54 of file net_ip.c.
Typedef Documentation
ioctlarg_t
typedef u_long ioctlarg_t
Definition at line 53 of file net_ip.c.
sa_family_t
typedef unsigned short sa_family_t
Definition at line 46 of file net_ip.c.
socklen_t
typedef int socklen_t
Definition at line 42 of file net_ip.c.
Function Documentation
NET_AddLocalAddress()
static void NET_AddLocalAddress (char * ifname, struct sockaddr * addr, struct sockaddr * netmask) static
Definition at line 1234 of file net_ip.c.
 {
     int addrlen;
     sa_family_t family;
     // only add addresses that have all required info.
     if(!addr || !netmask || !ifname)
         return;
     family = addr->sa_family;
     if(numIP < MAX_IPS)
     {
         if(family == AF_INET)
         {
             addrlen = sizeof(struct sockaddr_in);
             localIP[numIP].type = NA_IP;
         }
         else if(family == AF_INET6)
         {
             addrlen = sizeof(struct sockaddr_in6);
             localIP[numIP].type = NA_IP6;
         }
         else
             return;
         Q_strncpyz(localIP[numIP].ifname, ifname, sizeof(localIP[numIP].ifname));
         localIP[numIP].family = family;
         memcpy(&localIP[numIP].addr, addr, addrlen);
         memcpy(&localIP[numIP].netmask, netmask, addrlen);
         numIP++;
     }
 }
Referenced by NET_GetLocalAddress().
NET_AdrToString()
const char* NET_AdrToString (netadr_t a)
Definition at line 456 of file net_ip.c.
 {
     static  char    s[NET_ADDRSTRMAXLEN];
     if (a.type == NA_LOOPBACK)
         Com_sprintf (s, sizeof(s), "loopback");
     else if (a.type == NA_BOT)
         Com_sprintf (s, sizeof(s), "bot");
     else if (a.type == NA_IP || a.type == NA_IP6)
     {
         struct sockaddr_storage sadr;
         memset(&sadr, 0, sizeof(sadr));
         NetadrToSockadr(&a, (struct sockaddr *) &sadr);
         Sys_SockaddrToString(s, sizeof(s), (struct sockaddr *) &sadr);
     }
     return s;
 }
Referenced by CL_ServerInfoPacket(), NET_AdrToStringwPort(), NET_GetPacket(), Netchan_Process(), SV_AddBanToList(), SV_ConnectionlessPacket(), SV_DelBanFromList(), SV_DirectConnect(), SV_GetChallenge(), SV_ListBans_f(), SV_Status_f(), SV_UserinfoChanged(), SV_WriteBans(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
NET_AdrToStringwPort()
const char* NET_AdrToStringwPort (netadr_t a)
Definition at line 476 of file net_ip.c.
 {
     static  char    s[NET_ADDRSTRMAXLEN];
     if (a.type == NA_LOOPBACK)
         Com_sprintf (s, sizeof(s), "loopback");
     else if (a.type == NA_BOT)
         Com_sprintf (s, sizeof(s), "bot");
     else if(a.type == NA_IP)
         Com_sprintf(s, sizeof(s), "%s:%hu", NET_AdrToString(a), ntohs(a.port));
     else if(a.type == NA_IP6)
         Com_sprintf(s, sizeof(s), "[%s]:%hu", NET_AdrToString(a), ntohs(a.port));
     return s;
 }
Referenced by CL_Connect_f(), CL_ConnectionlessPacket(), CL_GetPing(), CL_GlobalServers_f(), CL_PacketEvent(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), LAN_GetServerAddressString(), LAN_GetServerInfo(), and SV_MasterHeartbeat().
NET_CompareAdr()
qboolean NET_CompareAdr (netadr_t a, netadr_t b)
Definition at line 493 of file net_ip.c.
 {
     if(!NET_CompareBaseAdr(a, b))
         return qfalse;
     if (a.type == NA_IP || a.type == NA_IP6)
     {
         if (a.port == b.port)
             return qtrue;
     }
     else
         return qtrue;
     return qfalse;
 }
Referenced by CL_ConnectionlessPacket(), CL_GetServerStatus(), CL_MotdPacket(), CL_PacketEvent(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatus(), CL_ServerStatusResponse(), CL_SetServerInfoByAddress(), CL_UpdateVisiblePings_f(), LAN_AddServer(), LAN_RemoveServer(), SV_DirectConnect(), SV_DropClient(), and SV_GetChallenge().
NET_CompareBaseAdr()
qboolean NET_CompareBaseAdr (netadr_t a, netadr_t b)
Definition at line 451 of file net_ip.c.
 {
     return NET_CompareBaseAdrMask(a, b, -1);
 }
Referenced by NET_CompareAdr(), SV_AuthorizeIpPacket(), SV_DirectConnect(), and SV_PacketEvent().
NET_CompareBaseAdrMask()
qboolean NET_CompareBaseAdrMask (netadr_t a, netadr_t b, int netmask)
Definition at line 390 of file net_ip.c.
 {
     byte cmpmask, *addra, *addrb;
     int curbyte;
     if (a.type != b.type)
         return qfalse;
     if (a.type == NA_LOOPBACK)
         return qtrue;
     if(a.type == NA_IP)
     {
         addra = (byte *) &a.ip;
         addrb = (byte *) &b.ip;
         if(netmask < 0 || netmask > 32)
             netmask = 32;
     }
     else if(a.type == NA_IP6)
     {
         addra = (byte *) &a.ip6;
         addrb = (byte *) &b.ip6;
         if(netmask < 0 || netmask > 128)
             netmask = 128;
     }
     else
     {
         Com_Printf ("NET_CompareBaseAdr: bad address type\n");
         return qfalse;
     }
     curbyte = netmask >> 3;
     if(curbyte && memcmp(addra, addrb, curbyte))
             return qfalse;
     netmask &= 0x07;
     if(netmask)
     {
         cmpmask = (1 << netmask) - 1;
         cmpmask <<= 8 - netmask;
         if((addra[curbyte] & cmpmask) == (addrb[curbyte] & cmpmask))
             return qtrue;
     }
     else
         return qtrue;
     return qfalse;
 }
Referenced by NET_CompareBaseAdr(), SV_AddBanToList(), SV_DelBanFromList(), and SV_IsBanned().
NET_Config()
void NET_Config (qboolean enableNetworking)
Definition at line 1492 of file net_ip.c.
{
     qboolean    modified;
     qboolean    stop;
     qboolean    start;
     // get any latched changes to cvars
     modified = NET_GetCvars();
     if( !net_enabled->integer ) {
         enableNetworking = 0;
     }
     // if enable state is the same and no cvars were modified, we have nothing to do
     if( enableNetworking == networkingEnabled && !modified ) {
         return;
     }
     if( enableNetworking == networkingEnabled ) {
         if( enableNetworking ) {
             stop = qtrue;
             start = qtrue;
         }
         else {
             stop = qfalse;
             start = qfalse;
         }
     }
     else {
         if( enableNetworking ) {
             stop = qfalse;
             start = qtrue;
         }
         else {
             stop = qtrue;
             start = qfalse;
         }
         networkingEnabled = enableNetworking;
     }
     if( stop ) {
         if ( ip_socket != INVALID_SOCKET ) {
             closesocket( ip_socket );
             ip_socket = INVALID_SOCKET;
         }
         if(multicast6_socket != INVALID_SOCKET)
         {
             if(multicast6_socket != ip6_socket)
                 closesocket(multicast6_socket);
             multicast6_socket = INVALID_SOCKET;
         }
         if ( ip6_socket != INVALID_SOCKET ) {
             closesocket( ip6_socket );
             ip6_socket = INVALID_SOCKET;
         }
         if ( socks_socket != INVALID_SOCKET ) {
             closesocket( socks_socket );
             socks_socket = INVALID_SOCKET;
         }
     }
     if( start )
     {
         if (net_enabled->integer)
         {
             NET_OpenIP();
             NET_SetMulticast6();
         }
     }
 }
Referenced by NET_Init(), NET_Restart_f(), and NET_Shutdown().
NET_ErrorString()
char* NET_ErrorString (void)
Definition at line 157 of file net_ip.c.
{
 #ifdef _WIN32
     //FIXME: replace with FormatMessage?
     switch( socketError ) {
         case WSAEINTR: return "WSAEINTR";
         case WSAEBADF: return "WSAEBADF";
         case WSAEACCES: return "WSAEACCES";
         case WSAEDISCON: return "WSAEDISCON";
         case WSAEFAULT: return "WSAEFAULT";
         case WSAEINVAL: return "WSAEINVAL";
         case WSAEMFILE: return "WSAEMFILE";
         case WSAEWOULDBLOCK: return "WSAEWOULDBLOCK";
         case WSAEINPROGRESS: return "WSAEINPROGRESS";
         case WSAEALREADY: return "WSAEALREADY";
         case WSAENOTSOCK: return "WSAENOTSOCK";
         case WSAEDESTADDRREQ: return "WSAEDESTADDRREQ";
         case WSAEMSGSIZE: return "WSAEMSGSIZE";
         case WSAEPROTOTYPE: return "WSAEPROTOTYPE";
         case WSAENOPROTOOPT: return "WSAENOPROTOOPT";
         case WSAEPROTONOSUPPORT: return "WSAEPROTONOSUPPORT";
         case WSAESOCKTNOSUPPORT: return "WSAESOCKTNOSUPPORT";
         case WSAEOPNOTSUPP: return "WSAEOPNOTSUPP";
         case WSAEPFNOSUPPORT: return "WSAEPFNOSUPPORT";
         case WSAEAFNOSUPPORT: return "WSAEAFNOSUPPORT";
         case WSAEADDRINUSE: return "WSAEADDRINUSE";
         case WSAEADDRNOTAVAIL: return "WSAEADDRNOTAVAIL";
         case WSAENETDOWN: return "WSAENETDOWN";
         case WSAENETUNREACH: return "WSAENETUNREACH";
         case WSAENETRESET: return "WSAENETRESET";
         case WSAECONNABORTED: return "WSWSAECONNABORTEDAEINTR";
         case WSAECONNRESET: return "WSAECONNRESET";
         case WSAENOBUFS: return "WSAENOBUFS";
         case WSAEISCONN: return "WSAEISCONN";
         case WSAENOTCONN: return "WSAENOTCONN";
         case WSAESHUTDOWN: return "WSAESHUTDOWN";
         case WSAETOOMANYREFS: return "WSAETOOMANYREFS";
         case WSAETIMEDOUT: return "WSAETIMEDOUT";
         case WSAECONNREFUSED: return "WSAECONNREFUSED";
         case WSAELOOP: return "WSAELOOP";
         case WSAENAMETOOLONG: return "WSAENAMETOOLONG";
         case WSAEHOSTDOWN: return "WSAEHOSTDOWN";
         case WSASYSNOTREADY: return "WSASYSNOTREADY";
         case WSAVERNOTSUPPORTED: return "WSAVERNOTSUPPORTED";
         case WSANOTINITIALISED: return "WSANOTINITIALISED";
         case WSAHOST_NOT_FOUND: return "WSAHOST_NOT_FOUND";
         case WSATRY_AGAIN: return "WSATRY_AGAIN";
         case WSANO_RECOVERY: return "WSANO_RECOVERY";
         case WSANO_DATA: return "WSANO_DATA";
         default: return "NO ERROR";
     }
 #else
     return strerror(socketError);
 #endif
 }
Referenced by NET_GetPacket(), NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), NET_OpenSocks(), NET_Sleep(), and Sys_SendPacket().
NET_Event()
void NET_Event (fd_set * fdr)
Definition at line 1619 of file net_ip.c.
 {
     byte bufData[MAX_MSGLEN + 1];
     netadr_t from = {0};
     msg_t netmsg;
     while(1)
     {
         MSG_Init(&netmsg, bufData, sizeof(bufData));
         if(NET_GetPacket(&from, &netmsg, fdr))
         {
             if(net_dropsim->value > 0.0f && net_dropsim->value <= 100.0f)
             {
                 // com_dropsim->value percent of incoming packets get dropped.
                 if(rand() < (int) (((double) RAND_MAX) / 100.0 * (double) net_dropsim->value))
                     continue;          // drop this packet
             }
             if(com_sv_running->integer)
                 Com_RunAndTimeServerPacket(&from, &netmsg);
             else
                 CL_PacketEvent(from, &netmsg);
         }
         else
             break;
     }
 }
Referenced by NET_Sleep().
NET_GetCvars()
static qboolean NET_GetCvars (void) static
Definition at line 1418 of file net_ip.c.
{
     int modified;
 #ifdef DEDICATED
     // I want server owners to explicitly turn on ipv6 support.
     net_enabled = Cvar_Get( "net_enabled", "1", CVAR_LATCH | CVAR_ARCHIVE );
 #else
     /* End users have it enabled so they can connect to ipv6-only hosts, but ipv4 will be
      * used if available due to ping */
     net_enabled = Cvar_Get( "net_enabled", "3", CVAR_LATCH | CVAR_ARCHIVE );
 #endif
     modified = net_enabled->modified;
     net_enabled->modified = qfalse;
     net_ip = Cvar_Get( "net_ip", "0.0.0.0", CVAR_LATCH );
     modified += net_ip->modified;
     net_ip->modified = qfalse;
     net_ip6 = Cvar_Get( "net_ip6", "::", CVAR_LATCH );
     modified += net_ip6->modified;
     net_ip6->modified = qfalse;
     net_port = Cvar_Get( "net_port", va( "%i", PORT_SERVER ), CVAR_LATCH );
     modified += net_port->modified;
     net_port->modified = qfalse;
     net_port6 = Cvar_Get( "net_port6", va( "%i", PORT_SERVER ), CVAR_LATCH );
     modified += net_port6->modified;
     net_port6->modified = qfalse;
     // Some cvars for configuring multicast options which facilitates scanning for servers on local subnets.
     net_mcast6addr = Cvar_Get( "net_mcast6addr", NET_MULTICAST_IP6, CVAR_LATCH | CVAR_ARCHIVE );
     modified += net_mcast6addr->modified;
     net_mcast6addr->modified = qfalse;
 #ifdef _WIN32
     net_mcast6iface = Cvar_Get( "net_mcast6iface", "0", CVAR_LATCH | CVAR_ARCHIVE );
 #else
     net_mcast6iface = Cvar_Get( "net_mcast6iface", "", CVAR_LATCH | CVAR_ARCHIVE );
 #endif
     modified += net_mcast6iface->modified;
     net_mcast6iface->modified = qfalse;
     net_socksEnabled = Cvar_Get( "net_socksEnabled", "0", CVAR_LATCH | CVAR_ARCHIVE );
     modified += net_socksEnabled->modified;
     net_socksEnabled->modified = qfalse;
     net_socksServer = Cvar_Get( "net_socksServer", "", CVAR_LATCH | CVAR_ARCHIVE );
     modified += net_socksServer->modified;
     net_socksServer->modified = qfalse;
     net_socksPort = Cvar_Get( "net_socksPort", "1080", CVAR_LATCH | CVAR_ARCHIVE );
     modified += net_socksPort->modified;
     net_socksPort->modified = qfalse;
     net_socksUsername = Cvar_Get( "net_socksUsername", "", CVAR_LATCH | CVAR_ARCHIVE );
     modified += net_socksUsername->modified;
     net_socksUsername->modified = qfalse;
     net_socksPassword = Cvar_Get( "net_socksPassword", "", CVAR_LATCH | CVAR_ARCHIVE );
     modified += net_socksPassword->modified;
     net_socksPassword->modified = qfalse;
     net_dropsim = Cvar_Get("net_dropsim", "", CVAR_TEMP);
     return modified ? qtrue : qfalse;
 }
Referenced by NET_Config().
NET_GetLocalAddress()
static void NET_GetLocalAddress (void) static
Definition at line 1295 of file net_ip.c.
{
     char                hostname[256];
     struct addrinfo hint;
     struct addrinfo *res = NULL;
     numIP = 0;
     if(gethostname( hostname, 256 ) == SOCKET_ERROR)
         return;
     Com_Printf( "Hostname: %s\n", hostname );
     memset(&hint, 0, sizeof(hint));
     hint.ai_family = AF_UNSPEC;
     hint.ai_socktype = SOCK_DGRAM;
     if(!getaddrinfo(hostname, NULL, &hint, &res))
     {
         struct sockaddr_in mask4;
         struct sockaddr_in6 mask6;
         struct addrinfo *search;
         /* On operating systems where it's more difficult to find out the configured interfaces, we'll just assume a
          * netmask with all bits set. */
         memset(&mask4, 0, sizeof(mask4));
         memset(&mask6, 0, sizeof(mask6));
         mask4.sin_family = AF_INET;
         memset(&mask4.sin_addr.s_addr, 0xFF, sizeof(mask4.sin_addr.s_addr));
         mask6.sin6_family = AF_INET6;
         memset(&mask6.sin6_addr, 0xFF, sizeof(mask6.sin6_addr));
         // add all IPs from returned list.
         for(search = res; search; search = search->ai_next)
         {
             if(search->ai_family == AF_INET)
                 NET_AddLocalAddress("", search->ai_addr, (struct sockaddr *) &mask4);
             else if(search->ai_family == AF_INET6)
                 NET_AddLocalAddress("", search->ai_addr, (struct sockaddr *) &mask6);
         }
         Sys_ShowIP();
     }
     if(res)
         freeaddrinfo(res);
 }
Referenced by NET_OpenIP().
NET_GetPacket()
qboolean NET_GetPacket (netadr_t * net_from, msg_t * net_message, fd_set * fdr)
Definition at line 523 of file net_ip.c.
 {
     int     ret;
     struct sockaddr_storage from;
     socklen_t   fromlen;
     int     err;
     if(ip_socket != INVALID_SOCKET && FD_ISSET(ip_socket, fdr))
     {
         fromlen = sizeof(from);
         ret = recvfrom( ip_socket, (void *)net_message->data, net_message->maxsize, 0, (struct sockaddr *) &from, &fromlen );
         if (ret == SOCKET_ERROR)
         {
             err = socketError;
             if( err != EAGAIN && err != ECONNRESET )
                 Com_Printf( "NET_GetPacket: %s\n", NET_ErrorString() );
         }
         else
         {
             memset( ((struct sockaddr_in *)&from)->sin_zero, 0, 8 );
             if ( usingSocks && memcmp( &from, &socksRelayAddr, fromlen ) == 0 ) {
                 if ( ret < 10 || net_message->data[0] != 0 || net_message->data[1] != 0 || net_message->data[2] != 0 || net_message->data[3] != 1 ) {
                     return qfalse;
                 }
                 net_from->type = NA_IP;
                 net_from->ip[0] = net_message->data[4];
                 net_from->ip[1] = net_message->data[5];
                 net_from->ip[2] = net_message->data[6];
                 net_from->ip[3] = net_message->data[7];
                 net_from->port = *(short *)&net_message->data[8];
                 net_message->readcount = 10;
             }
             else {
                 SockadrToNetadr( (struct sockaddr *) &from, net_from );
                 net_message->readcount = 0;
             }
             if( ret >= net_message->maxsize ) {
                 Com_Printf( "Oversize packet from %s\n", NET_AdrToString (*net_from) );
                 return qfalse;
             }
             net_message->cursize = ret;
             return qtrue;
         }
     }
     if(ip6_socket != INVALID_SOCKET && FD_ISSET(ip6_socket, fdr))
     {
         fromlen = sizeof(from);
         ret = recvfrom(ip6_socket, (void *)net_message->data, net_message->maxsize, 0, (struct sockaddr *) &from, &fromlen);
         if (ret == SOCKET_ERROR)
         {
             err = socketError;
             if( err != EAGAIN && err != ECONNRESET )
                 Com_Printf( "NET_GetPacket: %s\n", NET_ErrorString() );
         }
         else
         {
             SockadrToNetadr((struct sockaddr *) &from, net_from);
             net_message->readcount = 0;
             if(ret >= net_message->maxsize)
             {
                 Com_Printf( "Oversize packet from %s\n", NET_AdrToString (*net_from) );
                 return qfalse;
             }
             net_message->cursize = ret;
             return qtrue;
         }
     }
     if(multicast6_socket != INVALID_SOCKET && multicast6_socket != ip6_socket && FD_ISSET(multicast6_socket, fdr))
     {
         fromlen = sizeof(from);
         ret = recvfrom(multicast6_socket, (void *)net_message->data, net_message->maxsize, 0, (struct sockaddr *) &from, &fromlen);
         if (ret == SOCKET_ERROR)
         {
             err = socketError;
             if( err != EAGAIN && err != ECONNRESET )
                 Com_Printf( "NET_GetPacket: %s\n", NET_ErrorString() );
         }
         else
         {
             SockadrToNetadr((struct sockaddr *) &from, net_from);
             net_message->readcount = 0;
             if(ret >= net_message->maxsize)
             {
                 Com_Printf( "Oversize packet from %s\n", NET_AdrToString (*net_from) );
                 return qfalse;
             }
             net_message->cursize = ret;
             return qtrue;
         }
     }
     return qfalse;
 }
Referenced by NET_Event().
NET_Init()
void NET_Init (void)
Definition at line 1573 of file net_ip.c.
                       {
 #ifdef _WIN32
     int     r;
     r = WSAStartup( MAKEWORD( 1, 1 ), &winsockdata );
     if( r ) {
         Com_Printf( "WARNING: Winsock initialization failed, returned %d\n", r );
         return;
     }
     winsockInitialized = qtrue;
     Com_Printf( "Winsock Initialized\n" );
 #endif
     NET_Config( qtrue );
     Cmd_AddCommand ("net_restart", NET_Restart_f);
 }
Referenced by main().
NET_IP6Socket()
SOCKET NET_IP6Socket (char * net_interface, int port, struct sockaddr_in6 * bindto, int * err)
Definition at line 881 of file net_ip.c.
{
     SOCKET              newsocket;
     struct sockaddr_in6 address;
     ioctlarg_t          _true = 1;
     *err = 0;
     if( net_interface )
     {
         // Print the name in brackets if there is a colon:
         if(Q_CountChar(net_interface, ':'))
             Com_Printf( "Opening IP6 socket: [%s]:%i\n", net_interface, port );
         else
             Com_Printf( "Opening IP6 socket: %s:%i\n", net_interface, port );
     }
     else
         Com_Printf( "Opening IP6 socket: [::]:%i\n", port );
     if( ( newsocket = socket( PF_INET6, SOCK_DGRAM, IPPROTO_UDP ) ) == INVALID_SOCKET ) {
         *err = socketError;
         Com_Printf( "WARNING: NET_IP6Socket: socket: %s\n", NET_ErrorString() );
         return newsocket;
     }
     // make it non-blocking
     if( ioctlsocket( newsocket, FIONBIO, &_true ) == SOCKET_ERROR ) {
         Com_Printf( "WARNING: NET_IP6Socket: ioctl FIONBIO: %s\n", NET_ErrorString() );
         *err = socketError;
         closesocket(newsocket);
         return INVALID_SOCKET;
     }
 #ifdef IPV6_V6ONLY
     {
         int i = 1;
         // ipv4 addresses should not be allowed to connect via this socket.
         if(setsockopt(newsocket, IPPROTO_IPV6, IPV6_V6ONLY, (char *) &i, sizeof(i)) == SOCKET_ERROR)
         {
             // win32 systems don't seem to support this anyways.
             Com_DPrintf("WARNING: NET_IP6Socket: setsockopt IPV6_V6ONLY: %s\n", NET_ErrorString());
         }
     }
 #endif
     if( !net_interface || !net_interface[0]) {
         address.sin6_family = AF_INET6;
         address.sin6_addr = in6addr_any;
     }
     else
     {
         if(!Sys_StringToSockaddr( net_interface, (struct sockaddr *)&address, sizeof(address), AF_INET6))
         {
             closesocket(newsocket);
             return INVALID_SOCKET;
         }
     }
     if( port == PORT_ANY ) {
         address.sin6_port = 0;
     }
     else {
         address.sin6_port = htons( (short)port );
     }
     if( bind( newsocket, (void *)&address, sizeof(address) ) == SOCKET_ERROR ) {
         Com_Printf( "WARNING: NET_IP6Socket: bind: %s\n", NET_ErrorString() );
         *err = socketError;
         closesocket( newsocket );
         return INVALID_SOCKET;
     }
     if(bindto)
         *bindto = address;
     return newsocket;
 }
Referenced by NET_JoinMulticast6(), and NET_OpenIP().
NET_IPSocket()
SOCKET NET_IPSocket (char * net_interface, int port, int * err)
Definition at line 813 of file net_ip.c.
{
     SOCKET              newsocket;
     struct sockaddr_in  address;
     ioctlarg_t          _true = 1;
     int                 i = 1;
     *err = 0;
     if( net_interface ) {
         Com_Printf( "Opening IP socket: %s:%i\n", net_interface, port );
     }
     else {
         Com_Printf( "Opening IP socket: 0.0.0.0:%i\n", port );
     }
     if( ( newsocket = socket( PF_INET, SOCK_DGRAM, IPPROTO_UDP ) ) == INVALID_SOCKET ) {
         *err = socketError;
         Com_Printf( "WARNING: NET_IPSocket: socket: %s\n", NET_ErrorString() );
         return newsocket;
     }
     // make it non-blocking
     if( ioctlsocket( newsocket, FIONBIO, &_true ) == SOCKET_ERROR ) {
         Com_Printf( "WARNING: NET_IPSocket: ioctl FIONBIO: %s\n", NET_ErrorString() );
         *err = socketError;
         closesocket(newsocket);
         return INVALID_SOCKET;
     }
     // make it broadcast capable
     if( setsockopt( newsocket, SOL_SOCKET, SO_BROADCAST, (char *) &i, sizeof(i) ) == SOCKET_ERROR ) {
         Com_Printf( "WARNING: NET_IPSocket: setsockopt SO_BROADCAST: %s\n", NET_ErrorString() );
     }
     if( !net_interface || !net_interface[0]) {
         address.sin_family = AF_INET;
         address.sin_addr.s_addr = INADDR_ANY;
     }
     else
     {
         if(!Sys_StringToSockaddr( net_interface, (struct sockaddr *)&address, sizeof(address), AF_INET))
         {
             closesocket(newsocket);
             return INVALID_SOCKET;
         }
     }
     if( port == PORT_ANY ) {
         address.sin_port = 0;
     }
     else {
         address.sin_port = htons( (short)port );
     }
     if( bind( newsocket, (void *)&address, sizeof(address) ) == SOCKET_ERROR ) {
         Com_Printf( "WARNING: NET_IPSocket: bind: %s\n", NET_ErrorString() );
         *err = socketError;
         closesocket( newsocket );
         return INVALID_SOCKET;
     }
     return newsocket;
 }
Referenced by NET_OpenIP().
NET_IsLocalAddress()
qboolean NET_IsLocalAddress (netadr_t adr)
Definition at line 510 of file net_ip.c.
{
     return adr.type == NA_LOOPBACK;
 }
Referenced by CL_Connect_f(), CL_Record_f(), SV_DirectConnect(), and SV_UserinfoChanged().
NET_JoinMulticast6()
void NET_JoinMulticast6 (void)
Definition at line 999 of file net_ip.c.
 {
     int err;
     if(ip6_socket == INVALID_SOCKET || multicast6_socket != INVALID_SOCKET || (net_enabled->integer & NET_DISABLEMCAST))
         return;
     if(IN6_IS_ADDR_MULTICAST(&boundto.sin6_addr) || IN6_IS_ADDR_UNSPECIFIED(&boundto.sin6_addr))
     {
         // The way the socket was bound does not prohibit receiving multi-cast packets. So we don't need to open a new one.
         multicast6_socket = ip6_socket;
     }
     else
     {
         if((multicast6_socket = NET_IP6Socket(net_mcast6addr->string, ntohs(boundto.sin6_port), NULL, &err)) == INVALID_SOCKET)
         {
             // If the OS does not support binding to multicast addresses, like WinXP, at least try with the normal file descriptor.
             multicast6_socket = ip6_socket;
         }
     }
     if(curgroup.ipv6mr_interface)
     {
         if (setsockopt(multicast6_socket, IPPROTO_IPV6, IPV6_MULTICAST_IF,
                     (char *) &curgroup.ipv6mr_interface, sizeof(curgroup.ipv6mr_interface)) < 0)
         {
             Com_Printf("NET_JoinMulticast6: Couldn't set scope on multicast socket: %s\n", NET_ErrorString());
             if(multicast6_socket != ip6_socket)
             {
                 closesocket(multicast6_socket);
                 multicast6_socket = INVALID_SOCKET;
                 return;
             }
         }
     }
     if (setsockopt(multicast6_socket, IPPROTO_IPV6, IPV6_JOIN_GROUP, (char *) &curgroup, sizeof(curgroup)))
     {
         Com_Printf("NET_JoinMulticast6: Couldn't join multicast group: %s\n", NET_ErrorString());
         if(multicast6_socket != ip6_socket)
         {
             closesocket(multicast6_socket);
             multicast6_socket = INVALID_SOCKET;
             return;
         }
     }
 }
Referenced by SV_Startup().
NET_LeaveMulticast6()
void NET_LeaveMulticast6 ()
Definition at line 1049 of file net_ip.c.
 {
     if(multicast6_socket != INVALID_SOCKET)
     {
         if(multicast6_socket != ip6_socket)
             closesocket(multicast6_socket);
         else
             setsockopt(multicast6_socket, IPPROTO_IPV6, IPV6_LEAVE_GROUP, (char *) &curgroup, sizeof(curgroup));
         multicast6_socket = INVALID_SOCKET;
     }
 }
Referenced by SV_Shutdown().
NET_OpenIP()
void NET_OpenIP (void)
Definition at line 1350 of file net_ip.c.
{
     int     i;
     int     err;
     int     port;
     int     port6;
     port = net_port->integer;
     port6 = net_port6->integer;
     NET_GetLocalAddress();
     // automatically scan for a valid port, so multiple
     // dedicated servers can be started without requiring
     // a different net_port for each one
     if(net_enabled->integer & NET_ENABLEV6)
     {
         for( i = 0 ; i < 10 ; i++ )
         {
             ip6_socket = NET_IP6Socket(net_ip6->string, port6 + i, &boundto, &err);
             if (ip6_socket != INVALID_SOCKET)
             {
                 Cvar_SetValue( "net_port6", port6 + i );
                 break;
             }
             else
             {
                 if(err == EAFNOSUPPORT)
                     break;
             }
         }
         if(ip6_socket == INVALID_SOCKET)
             Com_Printf( "WARNING: Couldn't bind to a v6 ip address.\n");
     }
     if(net_enabled->integer & NET_ENABLEV4)
     {
         for( i = 0 ; i < 10 ; i++ ) {
             ip_socket = NET_IPSocket( net_ip->string, port + i, &err );
             if (ip_socket != INVALID_SOCKET) {
                 Cvar_SetValue( "net_port", port + i );
                 if (net_socksEnabled->integer)
                     NET_OpenSocks( port + i );
                 break;
             }
             else
             {
                 if(err == EAFNOSUPPORT)
                     break;
             }
         }
         if(ip_socket == INVALID_SOCKET)
             Com_Printf( "WARNING: Couldn't bind to a v4 ip address.\n");
     }
 }
Referenced by NET_Config().
NET_OpenSocks()
void NET_OpenSocks (int port)
Definition at line 1067 of file net_ip.c.
{
     struct sockaddr_in  address;
     struct hostent      *h;
     int                 len;
     qboolean            rfc1929;
     unsigned char       buf[64];
     usingSocks = qfalse;
     Com_Printf( "Opening connection to SOCKS server.\n" );
     if ( ( socks_socket = socket( AF_INET, SOCK_STREAM, IPPROTO_TCP ) ) == INVALID_SOCKET ) {
         Com_Printf( "WARNING: NET_OpenSocks: socket: %s\n", NET_ErrorString() );
         return;
     }
     h = gethostbyname( net_socksServer->string );
     if ( h == NULL ) {
         Com_Printf( "WARNING: NET_OpenSocks: gethostbyname: %s\n", NET_ErrorString() );
         return;
     }
     if ( h->h_addrtype != AF_INET ) {
         Com_Printf( "WARNING: NET_OpenSocks: gethostbyname: address type was not AF_INET\n" );
         return;
     }
     address.sin_family = AF_INET;
     address.sin_addr.s_addr = *(int *)h->h_addr_list[0];
     address.sin_port = htons( (short)net_socksPort->integer );
     if ( connect( socks_socket, (struct sockaddr *)&address, sizeof( address ) ) == SOCKET_ERROR ) {
         Com_Printf( "NET_OpenSocks: connect: %s\n", NET_ErrorString() );
         return;
     }
     // send socks authentication handshake
     if ( *net_socksUsername->string || *net_socksPassword->string ) {
         rfc1929 = qtrue;
     }
     else {
         rfc1929 = qfalse;
     }
     buf[0] = 5;     // SOCKS version
     // method count
     if ( rfc1929 ) {
         buf[1] = 2;
         len = 4;
     }
     else {
         buf[1] = 1;
         len = 3;
     }
     buf[2] = 0;     // method #1 - method id #00: no authentication
     if ( rfc1929 ) {
         buf[2] = 2;     // method #2 - method id #02: username/password
     }
     if ( send( socks_socket, (void *)buf, len, 0 ) == SOCKET_ERROR ) {
         Com_Printf( "NET_OpenSocks: send: %s\n", NET_ErrorString() );
         return;
     }
     // get the response
     len = recv( socks_socket, (void *)buf, 64, 0 );
     if ( len == SOCKET_ERROR ) {
         Com_Printf( "NET_OpenSocks: recv: %s\n", NET_ErrorString() );
         return;
     }
     if ( len != 2 || buf[0] != 5 ) {
         Com_Printf( "NET_OpenSocks: bad response\n" );
         return;
     }
     switch( buf[1] ) {
     case 0: // no authentication
         break;
     case 2: // username/password authentication
         break;
     default:
         Com_Printf( "NET_OpenSocks: request denied\n" );
         return;
     }
     // do username/password authentication if needed
     if ( buf[1] == 2 ) {
         int     ulen;
         int     plen;
         // build the request
         ulen = strlen( net_socksUsername->string );
         plen = strlen( net_socksPassword->string );
         buf[0] = 1;     // username/password authentication version
         buf[1] = ulen;
         if ( ulen ) {
             memcpy( &buf[2], net_socksUsername->string, ulen );
         }
         buf[2 + ulen] = plen;
         if ( plen ) {
             memcpy( &buf[3 + ulen], net_socksPassword->string, plen );
         }
         // send it
         if ( send( socks_socket, (void *)buf, 3 + ulen + plen, 0 ) == SOCKET_ERROR ) {
             Com_Printf( "NET_OpenSocks: send: %s\n", NET_ErrorString() );
             return;
         }
         // get the response
         len = recv( socks_socket, (void *)buf, 64, 0 );
         if ( len == SOCKET_ERROR ) {
             Com_Printf( "NET_OpenSocks: recv: %s\n", NET_ErrorString() );
             return;
         }
         if ( len != 2 || buf[0] != 1 ) {
             Com_Printf( "NET_OpenSocks: bad response\n" );
             return;
         }
         if ( buf[1] != 0 ) {
             Com_Printf( "NET_OpenSocks: authentication failed\n" );
             return;
         }
     }
     // send the UDP associate request
     buf[0] = 5;     // SOCKS version
     buf[1] = 3;     // command: UDP associate
     buf[2] = 0;     // reserved
     buf[3] = 1;     // address type: IPV4
     *(int *)&buf[4] = INADDR_ANY;
     *(short *)&buf[8] = htons( (short)port );       // port
     if ( send( socks_socket, (void *)buf, 10, 0 ) == SOCKET_ERROR ) {
         Com_Printf( "NET_OpenSocks: send: %s\n", NET_ErrorString() );
         return;
     }
     // get the response
     len = recv( socks_socket, (void *)buf, 64, 0 );
     if( len == SOCKET_ERROR ) {
         Com_Printf( "NET_OpenSocks: recv: %s\n", NET_ErrorString() );
         return;
     }
     if( len < 2 || buf[0] != 5 ) {
         Com_Printf( "NET_OpenSocks: bad response\n" );
         return;
     }
     // check completion code
     if( buf[1] != 0 ) {
         Com_Printf( "NET_OpenSocks: request denied: %i\n", buf[1] );
         return;
     }
     if( buf[3] != 1 ) {
         Com_Printf( "NET_OpenSocks: relay address is not IPV4: %i\n", buf[3] );
         return;
     }
     ((struct sockaddr_in *)&socksRelayAddr)->sin_family = AF_INET;
     ((struct sockaddr_in *)&socksRelayAddr)->sin_addr.s_addr = *(int *)&buf[4];
     ((struct sockaddr_in *)&socksRelayAddr)->sin_port = *(short *)&buf[8];
     memset( ((struct sockaddr_in *)&socksRelayAddr)->sin_zero, 0, 8 );
     usingSocks = qtrue;
 }
Referenced by NET_OpenIP().
NET_Restart_f()
void NET_Restart_f (void)
Definition at line 1706 of file net_ip.c.
 {
     NET_Config(qtrue);
 }
Referenced by Com_GameRestart(), and NET_Init().
NET_SetMulticast6()
void NET_SetMulticast6 (void)
Definition at line 965 of file net_ip.c.
 {
     struct sockaddr_in6 addr;
     if(!*net_mcast6addr->string || !Sys_StringToSockaddr(net_mcast6addr->string, (struct sockaddr *) &addr, sizeof(addr), AF_INET6))
     {
         Com_Printf("WARNING: NET_JoinMulticast6: Incorrect multicast address given, "
                "please set cvar %s to a sane value.\n", net_mcast6addr->name);
         Cvar_SetValue(net_enabled->name, net_enabled->integer | NET_DISABLEMCAST);
         return;
     }
     memcpy(&curgroup.ipv6mr_multiaddr, &addr.sin6_addr, sizeof(curgroup.ipv6mr_multiaddr));
     if(*net_mcast6iface->string)
     {
 #ifdef _WIN32
         curgroup.ipv6mr_interface = net_mcast6iface->integer;
 #else
         curgroup.ipv6mr_interface = if_nametoindex(net_mcast6iface->string);
 #endif
     }
     else
         curgroup.ipv6mr_interface = 0;
 }
Referenced by NET_Config().
NET_Shutdown()
void NET_Shutdown (void)
Definition at line 1598 of file net_ip.c.
{
     if ( !networkingEnabled ) {
         return;
     }
     NET_Config( qfalse );
 #ifdef _WIN32
     WSACleanup();
     winsockInitialized = qfalse;
 #endif
 }
Referenced by __attribute__().
NET_Sleep()
void NET_Sleep (int msec)
Definition at line 1655 of file net_ip.c.
 {
     struct timeval timeout;
     fd_set fdr;
     int retval;
     SOCKET highestfd = INVALID_SOCKET;
     if(msec < 0)
         msec = 0;
     FD_ZERO(&fdr);
     if(ip_socket != INVALID_SOCKET)
     {
         FD_SET(ip_socket, &fdr);
         highestfd = ip_socket;
     }
     if(ip6_socket != INVALID_SOCKET)
     {
         FD_SET(ip6_socket, &fdr);
         if(highestfd == INVALID_SOCKET || ip6_socket > highestfd)
             highestfd = ip6_socket;
     }
 #ifdef _WIN32
     if(highestfd == INVALID_SOCKET)
     {
         // windows ain't happy when select is called without valid FDs
         SleepEx(msec, 0);
         return;
     }
 #endif
     timeout.tv_sec = msec/1000;
     timeout.tv_usec = (msec%1000)*1000;
     retval = select(highestfd + 1, &fdr, NULL, NULL, &timeout);
     if(retval == SOCKET_ERROR)
         Com_Printf("Warning: select() syscall failed: %s\n", NET_ErrorString());
     else if(retval > 0)
         NET_Event(&fdr);
 }
Referenced by Com_Frame().
NetadrToSockadr()
static void NetadrToSockadr (netadr_t * a, struct sockaddr * s) static
Definition at line 212 of file net_ip.c.
{
     if( a->type == NA_BROADCAST ) {
         ((struct sockaddr_in *)s)->sin_family = AF_INET;
         ((struct sockaddr_in *)s)->sin_port = a->port;
         ((struct sockaddr_in *)s)->sin_addr.s_addr = INADDR_BROADCAST;
     }
     else if( a->type == NA_IP ) {
         ((struct sockaddr_in *)s)->sin_family = AF_INET;
         ((struct sockaddr_in *)s)->sin_addr.s_addr = *(int *)&a->ip;
         ((struct sockaddr_in *)s)->sin_port = a->port;
     }
     else if( a->type == NA_IP6 ) {
         ((struct sockaddr_in6 *)s)->sin6_family = AF_INET6;
         ((struct sockaddr_in6 *)s)->sin6_addr = * ((struct in6_addr *) &a->ip6);
         ((struct sockaddr_in6 *)s)->sin6_port = a->port;
         ((struct sockaddr_in6 *)s)->sin6_scope_id = a->scope_id;
     }
     else if(a->type == NA_MULTICAST6)
     {
         ((struct sockaddr_in6 *)s)->sin6_family = AF_INET6;
         ((struct sockaddr_in6 *)s)->sin6_addr = curgroup.ipv6mr_multiaddr;
         ((struct sockaddr_in6 *)s)->sin6_port = a->port;
     }
 }
Referenced by NET_AdrToString(), and Sys_SendPacket().
SearchAddrInfo()
static struct addrinfo* SearchAddrInfo (struct addrinfo * hints, sa_family_t family) static
Definition at line 254 of file net_ip.c.
 {
     while(hints)
     {
         if(hints->ai_family == family)
             return hints;
         hints = hints->ai_next;
     }
     return NULL;
 }
Referenced by Sys_StringToSockaddr().
SockadrToNetadr()
static void SockadrToNetadr (struct sockaddr * s, netadr_t * a) static
Definition at line 238 of file net_ip.c.
{
     if (s->sa_family == AF_INET) {
         a->type = NA_IP;
         *(int *)&a->ip = ((struct sockaddr_in *)s)->sin_addr.s_addr;
         a->port = ((struct sockaddr_in *)s)->sin_port;
     }
     else if(s->sa_family == AF_INET6)
     {
         a->type = NA_IP6;
         memcpy(a->ip6, &((struct sockaddr_in6 *)s)->sin6_addr, sizeof(a->ip6));
         a->port = ((struct sockaddr_in6 *)s)->sin6_port;
         a->scope_id = ((struct sockaddr_in6 *)s)->sin6_scope_id;
     }
 }
Referenced by NET_GetPacket(), and Sys_StringToAdr().
Sys_IsLANAddress()
qboolean Sys_IsLANAddress (netadr_t adr)
Definition at line 708 of file net_ip.c.
{
     int     index, run, addrsize;
     qboolean differed;
     byte *compareadr, *comparemask, *compareip;
     if( adr.type == NA_LOOPBACK ) {
         return qtrue;
     }
     if( adr.type == NA_IP )
     {
         // RFC1918:
         // 10.0.0.0        -   10.255.255.255  (10/8 prefix)
         // 172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
         // 192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
         if(adr.ip[0] == 10)
             return qtrue;
         if(adr.ip[0] == 172 && (adr.ip[1]&0xf0) == 16)
             return qtrue;
         if(adr.ip[0] == 192 && adr.ip[1] == 168)
             return qtrue;
         if(adr.ip[0] == 127)
             return qtrue;
     }
     else if(adr.type == NA_IP6)
     {
         if(adr.ip6[0] == 0xfe && (adr.ip6[1] & 0xc0) == 0x80)
             return qtrue;
         if((adr.ip6[0] & 0xfe) == 0xfc)
             return qtrue;
     }
     // Now compare against the networks this computer is member of.
     for(index = 0; index < numIP; index++)
     {
         if(localIP[index].type == adr.type)
         {
             if(adr.type == NA_IP)
             {
                 compareip = (byte *) &((struct sockaddr_in *) &localIP[index].addr)->sin_addr.s_addr;
                 comparemask = (byte *) &((struct sockaddr_in *) &localIP[index].netmask)->sin_addr.s_addr;
                 compareadr = adr.ip;
                 addrsize = sizeof(adr.ip);
             }
             else
             {
                 // TODO? should we check the scope_id here?
                 compareip = (byte *) &((struct sockaddr_in6 *) &localIP[index].addr)->sin6_addr;
                 comparemask = (byte *) &((struct sockaddr_in6 *) &localIP[index].netmask)->sin6_addr;
                 compareadr = adr.ip6;
                 addrsize = sizeof(adr.ip6);
             }
             differed = qfalse;
             for(run = 0; run < addrsize; run++)
             {
                 if((compareip[run] & comparemask[run]) != (compareadr[run] & comparemask[run]))
                 {
                     differed = qtrue;
                     break;
                 }
             }
             if(!differed)
                 return qtrue;
         }
     }
     return qfalse;
 }
Referenced by CL_CheckForResend(), CL_ReadyToSendPacket(), SV_DirectConnect(), SV_GetChallenge(), SV_SendClientMessages(), and SV_UserinfoChanged().
Sys_SendPacket()
void Sys_SendPacket (int length, const void * data, netadr_t to)
Definition at line 643 of file net_ip.c.
{
     int             ret = SOCKET_ERROR;
     struct sockaddr_storage addr;
     if( to.type != NA_BROADCAST && to.type != NA_IP && to.type != NA_IP6 && to.type != NA_MULTICAST6)
     {
         Com_Error( ERR_FATAL, "Sys_SendPacket: bad address type" );
         return;
     }
     if( (ip_socket == INVALID_SOCKET && to.type == NA_IP) ||
         (ip_socket == INVALID_SOCKET && to.type == NA_BROADCAST) ||
         (ip6_socket == INVALID_SOCKET && to.type == NA_IP6) ||
         (ip6_socket == INVALID_SOCKET && to.type == NA_MULTICAST6) )
         return;
     if(to.type == NA_MULTICAST6 && (net_enabled->integer & NET_DISABLEMCAST))
         return;
     memset(&addr, 0, sizeof(addr));
     NetadrToSockadr( &to, (struct sockaddr *) &addr );
     if( usingSocks && to.type == NA_IP ) {
         socksBuf[0] = 0;    // reserved
         socksBuf[1] = 0;
         socksBuf[2] = 0;    // fragment (not fragmented)
         socksBuf[3] = 1;    // address type: IPV4
         *(int *)&socksBuf[4] = ((struct sockaddr_in *)&addr)->sin_addr.s_addr;
         *(short *)&socksBuf[8] = ((struct sockaddr_in *)&addr)->sin_port;
         memcpy( &socksBuf[10], data, length );
         ret = sendto( ip_socket, socksBuf, length+10, 0, &socksRelayAddr, sizeof(socksRelayAddr) );
     }
     else {
         if(addr.ss_family == AF_INET)
             ret = sendto( ip_socket, data, length, 0, (struct sockaddr *) &addr, sizeof(struct sockaddr_in) );
         else if(addr.ss_family == AF_INET6)
             ret = sendto( ip6_socket, data, length, 0, (struct sockaddr *) &addr, sizeof(struct sockaddr_in6) );
     }
     if( ret == SOCKET_ERROR ) {
         int err = socketError;
         // wouldblock is silent
         if( err == EAGAIN ) {
             return;
         }
         // some PPP links do not allow broadcasts and return an error
         if( ( err == EADDRNOTAVAIL ) && ( ( to.type == NA_BROADCAST ) ) ) {
             return;
         }
         Com_Printf( "Sys_SendPacket: %s\n", NET_ErrorString() );
     }
 }
Referenced by NET_FlushPacketQueue(), and NET_SendPacket().
Sys_ShowIP()
void Sys_ShowIP (void)
Definition at line 789 of file net_ip.c.
                       {
     int i;
     char addrbuf[NET_ADDRSTRMAXLEN];
     for(i = 0; i < numIP; i++)
     {
         Sys_SockaddrToString(addrbuf, sizeof(addrbuf), (struct sockaddr *) &localIP[i].addr);
         if(localIP[i].type == NA_IP)
             Com_Printf( "IP: %s\n", addrbuf);
         else if(localIP[i].type == NA_IP6)
             Com_Printf( "IP6: %s\n", addrbuf);
     }
 }
Referenced by CL_ShowIP_f(), and NET_GetLocalAddress().
Sys_SockaddrToString()
static void Sys_SockaddrToString (char * dest, int destlen, struct sockaddr * input) static
Definition at line 341 of file net_ip.c.
 {
     socklen_t inputlen;
     if (input->sa_family == AF_INET6)
         inputlen = sizeof(struct sockaddr_in6);
     else
         inputlen = sizeof(struct sockaddr_in);
     if(getnameinfo(input, inputlen, dest, destlen, NULL, 0, NI_NUMERICHOST) && destlen > 0)
         *dest = '\0';
 }
Referenced by NET_AdrToString(), and Sys_ShowIP().
Sys_StringToAdr()
qboolean Sys_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
Definition at line 359 of file net_ip.c.
{
     struct sockaddr_storage sadr;
     sa_family_t fam;
     switch(family)
     {
         case NA_IP:
             fam = AF_INET;
         break;
         case NA_IP6:
             fam = AF_INET6;
         break;
         default:
             fam = AF_UNSPEC;
         break;
     }
     if( !Sys_StringToSockaddr(s, (struct sockaddr *) &sadr, sizeof(sadr), fam ) ) {
         return qfalse;
     }
     SockadrToNetadr( (struct sockaddr *) &sadr, a );
     return qtrue;
 }
Referenced by NET_StringToAdr().
Sys_StringToSockaddr()
static qboolean Sys_StringToSockaddr (const char * s, struct sockaddr * sadr, int sadr_len, sa_family_t family) static
Definition at line 272 of file net_ip.c.
 {
     struct addrinfo hints;
     struct addrinfo *res = NULL;
     struct addrinfo *search = NULL;
     struct addrinfo *hintsp;
     int retval;
     memset(sadr, '\0', sizeof(*sadr));
     memset(&hints, '\0', sizeof(hints));
     hintsp = &hints;
     hintsp->ai_family = family;
     hintsp->ai_socktype = SOCK_DGRAM;
     retval = getaddrinfo(s, NULL, hintsp, &res);
     if(!retval)
     {
         if(family == AF_UNSPEC)
         {
             // Decide here and now which protocol family to use
             if(net_enabled->integer & NET_PRIOV6)
             {
                 if(net_enabled->integer & NET_ENABLEV6)
                     search = SearchAddrInfo(res, AF_INET6);
                 if(!search && (net_enabled->integer & NET_ENABLEV4))
                     search = SearchAddrInfo(res, AF_INET);
             }
             else
             {
                 if(net_enabled->integer & NET_ENABLEV4)
                     search = SearchAddrInfo(res, AF_INET);
                 if(!search && (net_enabled->integer & NET_ENABLEV6))
                     search = SearchAddrInfo(res, AF_INET6);
             }
         }
         else
             search = SearchAddrInfo(res, family);
         if(search)
         {
             if(search->ai_addrlen > sadr_len)
                 search->ai_addrlen = sadr_len;
             memcpy(sadr, search->ai_addr, search->ai_addrlen);
             freeaddrinfo(res);
             return qtrue;
         }
         else
             Com_Printf("Sys_StringToSockaddr: Error resolving %s: No address of required type found.\n", s);
     }
     else
         Com_Printf("Sys_StringToSockaddr: Error resolving %s: %s\n", s, gai_strerror(retval));
     if(res)
         freeaddrinfo(res);
     return qfalse;
 }
Referenced by NET_IP6Socket(), NET_IPSocket(), NET_SetMulticast6(), and Sys_StringToAdr().
Variable Documentation
boundto
struct sockaddr_in6 boundto static
Definition at line 124 of file net_ip.c.
Referenced by NET_JoinMulticast6(), and NET_OpenIP().
curgroup
struct ipv6_mreq curgroup static
Definition at line 122 of file net_ip.c.
Referenced by NET_JoinMulticast6(), NET_LeaveMulticast6(), NET_SetMulticast6(), and NetadrToSockadr().
ip6_socket
SOCKET ip6_socket = INVALID_SOCKET static
Definition at line 117 of file net_ip.c.
Referenced by NET_Config(), NET_GetPacket(), NET_JoinMulticast6(), NET_LeaveMulticast6(), NET_OpenIP(), NET_Sleep(), and Sys_SendPacket().
ip_socket
SOCKET ip_socket = INVALID_SOCKET static
Definition at line 116 of file net_ip.c.
Referenced by NET_Config(), NET_GetPacket(), NET_OpenIP(), NET_Sleep(), and Sys_SendPacket().
localIP
nip_localaddr_t localIP[MAX_IPS] static
Definition at line 145 of file net_ip.c.
Referenced by NET_AddLocalAddress(), Sys_IsLANAddress(), and Sys_ShowIP().
multicast6_socket
SOCKET multicast6_socket = INVALID_SOCKET static
Definition at line 119 of file net_ip.c.
Referenced by NET_Config(), NET_GetPacket(), NET_JoinMulticast6(), and NET_LeaveMulticast6().
net_dropsim
cvar_t* net_dropsim static
Definition at line 112 of file net_ip.c.
Referenced by NET_Event(), and NET_GetCvars().
net_enabled
cvar_t* net_enabled static
Definition at line 97 of file net_ip.c.
Referenced by NET_Config(), NET_GetCvars(), NET_JoinMulticast6(), NET_OpenIP(), NET_SetMulticast6(), Sys_SendPacket(), and Sys_StringToSockaddr().
net_ip
cvar_t* net_ip static
Definition at line 105 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenIP().
net_ip6
cvar_t* net_ip6 static
Definition at line 106 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenIP().
net_mcast6addr
cvar_t* net_mcast6addr static
Definition at line 109 of file net_ip.c.
Referenced by NET_GetCvars(), NET_JoinMulticast6(), and NET_SetMulticast6().
net_mcast6iface
cvar_t* net_mcast6iface static
Definition at line 110 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_SetMulticast6().
net_port
cvar_t* net_port static
Definition at line 107 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenIP().
net_port6
cvar_t* net_port6 static
Definition at line 108 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenIP().
net_socksEnabled
cvar_t* net_socksEnabled static
Definition at line 99 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenIP().
net_socksPassword
cvar_t* net_socksPassword static
Definition at line 103 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenSocks().
net_socksPort
cvar_t* net_socksPort static
Definition at line 101 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenSocks().
net_socksServer
cvar_t* net_socksServer static
Definition at line 100 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenSocks().
net_socksUsername
cvar_t* net_socksUsername static
Definition at line 102 of file net_ip.c.
Referenced by NET_GetCvars(), and NET_OpenSocks().
networkingEnabled
int networkingEnabled = 0 static
Definition at line 95 of file net_ip.c.
Referenced by NET_Config(), and NET_Shutdown().
numIP
int numIP static
Definition at line 146 of file net_ip.c.
Referenced by NET_AddLocalAddress(), NET_GetLocalAddress(), Sys_IsLANAddress(), and Sys_ShowIP().
socks_socket
SOCKET socks_socket = INVALID_SOCKET static
Definition at line 118 of file net_ip.c.
Referenced by NET_Config(), and NET_OpenSocks().
socksBuf
char socksBuf[4096] static
Definition at line 636 of file net_ip.c.
Referenced by Sys_SendPacket().
socksRelayAddr
struct sockaddr socksRelayAddr static
Definition at line 114 of file net_ip.c.
Referenced by NET_GetPacket(), NET_OpenSocks(), and Sys_SendPacket().
usingSocks
qboolean usingSocks = qfalse static
Definition at line 94 of file net_ip.c.
Referenced by NET_GetPacket(), NET_OpenSocks(), and Sys_SendPacket().
winsockdata
WSADATA winsockdata static
Definition at line 56 of file net_ip.c.
Referenced by NET_Init().
winsockInitialized
qboolean winsockInitialized = qfalse static
Definition at line 57 of file net_ip.c.
Referenced by NET_Init(), and NET_Shutdown().