ioquake3 doxygen: C:/entry/dev/ioq3/code/game/bg_misc.c File Reference
bg_misc.c File Reference
Both games misc functions, all completely stateless.
#include "../qcommon/q_shared.h"
#include "bg_public.h"
Functions
gitem_t * BG_FindItemForPowerup (powerup_t pw)
gitem_t * BG_FindItemForHoldable (holdable_t pw)
gitem_t * BG_FindItemForWeapon (weapon_t weapon)
gitem_t * BG_FindItem (const char *pickupName)
qboolean BG_PlayerTouchesItem (playerState_t *ps, entityState_t *item, int atTime)
qboolean BG_CanItemBeGrabbed (int gametype, const entityState_t *ent, const playerState_t *ps)
void BG_EvaluateTrajectory (const trajectory_t *tr, int atTime, vec3_t result)
void BG_EvaluateTrajectoryDelta (const trajectory_t *tr, int atTime, vec3_t result)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t *ps)
void BG_TouchJumpPad (playerState_t *ps, entityState_t *jumppad)
void BG_PlayerStateToEntityState (playerState_t *ps, entityState_t *s, qboolean snap)
void BG_PlayerStateToEntityStateExtraPolate (playerState_t *ps, entityState_t *s, int time, qboolean snap)
Variables
gitem_t bg_itemlist []
int bg_numItems = ARRAY_LEN(bg_itemlist) - 1
char * eventnames []
Detailed Description
Both games misc functions, all completely stateless.
Definition in file bg_misc.c.
Function Documentation
BG_AddPredictableEventToPlayerstate()
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t * ps)
Definition at line 1414 of file bg_misc.c.
 {
 #ifdef _DEBUG
     {
         char buf[256];
         trap_Cvar_VariableStringBuffer("showevents", buf, sizeof(buf));
         if (atof(buf) != 0) {
 #ifdef QAGAME
             Com_Printf(" game event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #else
             Com_Printf("Cgame event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #endif
     }
 }
 #endif
     ps->events[ps->eventSequence & (MAX_PS_EVENTS - 1)] = newEvent;
     ps->eventParms[ps->eventSequence & (MAX_PS_EVENTS - 1)] = eventParm;
     ps->eventSequence++;
 }
References Com_Printf(), eventnames, playerState_s::eventParms, playerState_s::events, playerState_s::eventSequence, MAX_PS_EVENTS, playerState_s::pmove_framecount, and trap_Cvar_VariableStringBuffer().
Referenced by BG_TouchJumpPad(), CG_TouchItem(), G_AddPredictableEvent(), and PM_AddEvent().
BG_CanItemBeGrabbed()
qboolean BG_CanItemBeGrabbed (int gametype, const entityState_t * ent, const playerState_t * ps)
Definition at line 1056 of file bg_misc.c.
 {
     gitem_t* item;
 #ifdef MISSIONPACK
     int        upperBound;
 #endif
     if (ent->modelindex < 1 || ent->modelindex >= bg_numItems) {
         Com_Error(ERR_DROP, "BG_CanItemBeGrabbed: index out of range");
     }
     item = &bg_itemlist[ent->modelindex];
     switch (item->giType) {
     case IT_WEAPON:
         return qtrue;    // weapons are always picked up
     case IT_AMMO:
         if (ps->ammo[item->giTag] >= 200) {
             return qfalse;        // can't hold any more
         }
         return qtrue;
     case IT_ARMOR:
 #ifdef MISSIONPACK
         if (bg_itemlist[ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_SCOUT) {
             return qfalse;
         }
         // we also clamp armor to the maxhealth for handicapping
         if (bg_itemlist[ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_GUARD) {
             upperBound = ps->stats[STAT_MAX_HEALTH];
         } else {
             upperBound = ps->stats[STAT_MAX_HEALTH] * 2;
         }
         if (ps->stats[STAT_ARMOR] >= upperBound) {
             return qfalse;
     }
 #else
         if (ps->stats[STAT_ARMOR] >= ps->stats[STAT_MAX_HEALTH] * 2) {
             return qfalse;
         }
 #endif
         return qtrue;
     case IT_HEALTH:
         // small and mega healths will go over the max, otherwise
         // don't pick up if already at max
 #ifdef MISSIONPACK
         if (bg_itemlist[ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_GUARD) {
         } else
 #endif
             if (item->quantity == 5 || item->quantity == 100) {
                 if (ps->stats[STAT_HEALTH] >= ps->stats[STAT_MAX_HEALTH] * 2) {
                     return qfalse;
                 }
                 return qtrue;
             }
         if (ps->stats[STAT_HEALTH] >= ps->stats[STAT_MAX_HEALTH]) {
             return qfalse;
         }
         return qtrue;
     case IT_POWERUP:
         return qtrue;    // powerups are always picked up
 #ifdef MISSIONPACK
     case IT_PERSISTANT_POWERUP:
         // can only hold one item at a time
         if (ps->stats[STAT_PERSISTANT_POWERUP]) {
             return qfalse;
         }
         // check team only
         if ((ent->generic1 & 2) && (ps->persistant[PERS_TEAM] != TEAM_RED)) {
             return qfalse;
         }
         if ((ent->generic1 & 4) && (ps->persistant[PERS_TEAM] != TEAM_BLUE)) {
             return qfalse;
         }
         return qtrue;
 #endif
     case IT_TEAM: // team items, such as flags
 #ifdef MISSIONPACK
         if (gametype == GT_1FCTF) {
             // neutral flag can always be picked up
             if (item->giTag == PW_NEUTRALFLAG) {
                 return qtrue;
             }
             if (ps->persistant[PERS_TEAM] == TEAM_RED) {
                 if (item->giTag == PW_BLUEFLAG && ps->powerups[PW_NEUTRALFLAG]) {
                     return qtrue;
                 }
             } else if (ps->persistant[PERS_TEAM] == TEAM_BLUE) {
                 if (item->giTag == PW_REDFLAG && ps->powerups[PW_NEUTRALFLAG]) {
                     return qtrue;
                 }
             }
         }
 #endif
         if (gametype == GT_CTF) {
             // ent->modelindex2 is non-zero on items if they are dropped
             // we need to know this because we can pick up our dropped flag (and return it)
             // but we can't pick up our flag at base
             if (ps->persistant[PERS_TEAM] == TEAM_RED) {
                 if (item->giTag == PW_BLUEFLAG ||
                     (item->giTag == PW_REDFLAG && ent->modelindex2) ||
                     (item->giTag == PW_REDFLAG && ps->powerups[PW_BLUEFLAG]))
                     return qtrue;
             } else if (ps->persistant[PERS_TEAM] == TEAM_BLUE) {
                 if (item->giTag == PW_REDFLAG ||
                     (item->giTag == PW_BLUEFLAG && ent->modelindex2) ||
                     (item->giTag == PW_BLUEFLAG && ps->powerups[PW_REDFLAG]))
                     return qtrue;
             }
         }
 #ifdef MISSIONPACK
         if (gametype == GT_HARVESTER) {
             return qtrue;
         }
 #endif
         return qfalse;
     case IT_HOLDABLE:
         // can only hold one item at a time
         if (ps->stats[STAT_HOLDABLE_ITEM]) {
             return qfalse;
         }
         return qtrue;
     case IT_BAD:
         Com_Error(ERR_DROP, "BG_CanItemBeGrabbed: IT_BAD");
     default:
 #ifndef Q3_VM
 #ifndef NDEBUG
         Com_Printf("BG_CanItemBeGrabbed: unknown enum %d\n", item->giType);
 #endif
 #endif
         break;
     }
     return qfalse;
 }
References playerState_s::ammo, bg_itemlist, bg_numItems, Com_Error(), Com_Printf(), ERR_DROP, gametype, entityState_s::generic1, gitem_s::giTag, gitem_s::giType, GT_1FCTF, GT_CTF, GT_HARVESTER, IT_AMMO, IT_ARMOR, IT_BAD, IT_HEALTH, IT_HOLDABLE, IT_PERSISTANT_POWERUP, IT_POWERUP, IT_TEAM, IT_WEAPON, entityState_s::modelindex, entityState_s::modelindex2, PERS_TEAM, playerState_s::persistant, playerState_s::powerups, PW_BLUEFLAG, PW_GUARD, PW_NEUTRALFLAG, PW_REDFLAG, PW_SCOUT, qfalse, qtrue, gitem_s::quantity, STAT_ARMOR, STAT_HEALTH, STAT_HOLDABLE_ITEM, STAT_MAX_HEALTH, playerState_s::stats, TEAM_BLUE, and TEAM_RED.
Referenced by CG_TouchItem(), and Touch_Item().
BG_EvaluateTrajectory()
void BG_EvaluateTrajectory (const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 1213 of file bg_misc.c.
 {
     float        deltaTime;
     float        phase;
     switch (tr->trType) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorCopy(tr->trBase, result);
         break;
     case TR_LINEAR:
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         VectorMA(tr->trBase, deltaTime, tr->trDelta, result);
         break;
     case TR_SINE:
         deltaTime = (atTime - tr->trTime) / (float)tr->trDuration;
         phase = sin(deltaTime * M_PI * 2);
         VectorMA(tr->trBase, phase, tr->trDelta, result);
         break;
     case TR_LINEAR_STOP:
         if (atTime > tr->trTime + tr->trDuration) {
             atTime = tr->trTime + tr->trDuration;
         }
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         if (deltaTime < 0) {
             deltaTime = 0;
         }
         VectorMA(tr->trBase, deltaTime, tr->trDelta, result);
         break;
     case TR_GRAVITY:
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         VectorMA(tr->trBase, deltaTime, tr->trDelta, result);
         result[2] -= 0.5 * DEFAULT_GRAVITY * deltaTime * deltaTime;        // FIXME: local gravity...
         break;
     default:
         Com_Error(ERR_DROP, "BG_EvaluateTrajectory: unknown trType: %i", tr->trType);
         break;
     }
 }
References Com_Error(), DEFAULT_GRAVITY, ERR_DROP, M_PI, tr, TR_GRAVITY, TR_INTERPOLATE, TR_LINEAR, TR_LINEAR_STOP, TR_SINE, TR_STATIONARY, VectorCopy, and VectorMA.
Referenced by BG_PlayerTouchesItem(), CG_AddFragment(), CG_AddMoveScaleFade(), CG_AdjustPositionForMover(), CG_BloodTrail(), CG_CalcEntityLerpPositions(), CG_CheckEvents(), CG_ClipMoveToEntities(), CG_GrappleTrail(), CG_InterpolateEntityPosition(), CG_PlasmaTrail(), CG_ResetPlayerEntity(), CG_RocketTrail(), G_ExplodeMissile(), G_MoverTeam(), G_RunItem(), G_RunMissile(), and SetMoverState().
BG_EvaluateTrajectoryDelta()
void BG_EvaluateTrajectoryDelta (const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 1260 of file bg_misc.c.
 {
     float    deltaTime;
     float    phase;
     switch (tr->trType) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorClear(result);
         break;
     case TR_LINEAR:
         VectorCopy(tr->trDelta, result);
         break;
     case TR_SINE:
         deltaTime = (atTime - tr->trTime) / (float)tr->trDuration;
         phase = cos(deltaTime * M_PI * 2);    // derivative of sin = cos
         phase *= 0.5;
         VectorScale(tr->trDelta, phase, result);
         break;
     case TR_LINEAR_STOP:
         if (atTime > tr->trTime + tr->trDuration) {
             VectorClear(result);
             return;
         }
         VectorCopy(tr->trDelta, result);
         break;
     case TR_GRAVITY:
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         VectorCopy(tr->trDelta, result);
         result[2] -= DEFAULT_GRAVITY * deltaTime;        // FIXME: local gravity...
         break;
     default:
         Com_Error(ERR_DROP, "BG_EvaluateTrajectoryDelta: unknown trType: %i", tr->trType);
         break;
     }
 }
References Com_Error(), DEFAULT_GRAVITY, ERR_DROP, M_PI, tr, TR_GRAVITY, TR_INTERPOLATE, TR_LINEAR, TR_LINEAR_STOP, TR_SINE, TR_STATIONARY, VectorClear, VectorCopy, and VectorScale.
Referenced by CG_Missile(), CG_ReflectVelocity(), G_BounceItem(), G_BounceMissile(), and G_MissileImpact().
BG_FindItem()
gitem_t* BG_FindItem (const char * pickupName)
Definition at line 1007 of file bg_misc.c.
 {
     gitem_t* it;
     for (it = bg_itemlist + 1; it->classname; it++) {
         if (!Q_stricmp(it->pickup_name, pickupName))
             return it;
     }
     return NULL;
 }
References bg_itemlist, gitem_s::classname, NULL, gitem_s::pickup_name, and Q_stricmp().
Referenced by ClearRegisteredItems(), ClientEvents(), Cmd_Give_f(), and G_CheckTeamItems().
BG_FindItemForHoldable()
gitem_t* BG_FindItemForHoldable (holdable_t pw)
Definition at line 965 of file bg_misc.c.
 {
     int        i;
     for (i = 0; i < bg_numItems; i++) {
         if (bg_itemlist[i].giType == IT_HOLDABLE && bg_itemlist[i].giTag == pw) {
             return &bg_itemlist[i];
         }
     }
     Com_Error(ERR_DROP, "HoldableItem not found");
     return NULL;
 }
References bg_itemlist, bg_numItems, Com_Error(), ERR_DROP, IT_HOLDABLE, NULL, and pw().
Referenced by CG_UseItem().
BG_FindItemForPowerup()
gitem_t* BG_FindItemForPowerup (powerup_t pw)
Definition at line 943 of file bg_misc.c.
 {
     int        i;
     for (i = 0; i < bg_numItems; i++) {
         if ((bg_itemlist[i].giType == IT_POWERUP ||
             bg_itemlist[i].giType == IT_TEAM ||
             bg_itemlist[i].giType == IT_PERSISTANT_POWERUP) &&
             bg_itemlist[i].giTag == pw) {
             return &bg_itemlist[i];
         }
     }
     return NULL;
 }
References bg_itemlist, bg_numItems, IT_PERSISTANT_POWERUP, IT_POWERUP, IT_TEAM, NULL, and pw().
Referenced by CG_DrawAreaPowerUp(), CG_DrawBlueFlagStatus(), CG_DrawFlagModel(), CG_DrawNewTeamInfo(), CG_DrawPowerups(), CG_DrawRedFlagStatus(), CG_DrawScores(), CG_DrawSelectedPlayerPowerup(), CG_DrawTeamOverlay(), CG_OneFlagStatus(), ClientEvents(), and TossClientItems().
BG_FindItemForWeapon()
gitem_t* BG_FindItemForWeapon (weapon_t weapon)
Definition at line 987 of file bg_misc.c.
 {
     gitem_t* it;
     for (it = bg_itemlist + 1; it->classname; it++) {
         if (it->giType == IT_WEAPON && it->giTag == weapon) {
             return it;
         }
     }
     Com_Error(ERR_DROP, "Couldn't find item for weapon %i", weapon);
     return NULL;
 }
References bg_itemlist, gitem_s::classname, Com_Error(), ERR_DROP, gitem_s::giTag, gitem_s::giType, IT_WEAPON, and NULL.
Referenced by ClearRegisteredItems(), InitShooter(), and TossClientItems().
BG_PlayerStateToEntityState()
void BG_PlayerStateToEntityState (playerState_t * ps, entityState_t * s, qboolean snap)
Definition at line 1484 of file bg_misc.c.
 {
     int        i;
     if (ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPECTATOR) {
         s->eType = ET_INVISIBLE;
     } else if (ps->stats[STAT_HEALTH] <= GIB_HEALTH) {
         s->eType = ET_INVISIBLE;
     } else {
         s->eType = ET_PLAYER;
     }
     s->number = ps->clientNum;
     s->pos.trType = TR_INTERPOLATE;
     VectorCopy(ps->origin, s->pos.trBase);
     if (snap) {
         SnapVector(s->pos.trBase);
     }
     // set the trDelta for flag direction
     VectorCopy(ps->velocity, s->pos.trDelta);
     s->apos.trType = TR_INTERPOLATE;
     VectorCopy(ps->viewangles, s->apos.trBase);
     if (snap) {
         SnapVector(s->apos.trBase);
     }
     s->angles2[YAW] = ps->movementDir;
     s->legsAnim = ps->legsAnim;
     s->torsoAnim = ps->torsoAnim;
     s->clientNum = ps->clientNum;        // ET_PLAYER looks here instead of at number
                                         // so corpses can also reference the proper config
     s->eFlags = ps->eFlags;
     if (ps->stats[STAT_HEALTH] <= 0) {
         s->eFlags |= EF_DEAD;
     } else {
         s->eFlags &= ~EF_DEAD;
     }
     if (ps->externalEvent) {
         s->event = ps->externalEvent;
         s->eventParm = ps->externalEventParm;
     } else if (ps->entityEventSequence < ps->eventSequence) {
         int        seq;
         if (ps->entityEventSequence < ps->eventSequence - MAX_PS_EVENTS) {
             ps->entityEventSequence = ps->eventSequence - MAX_PS_EVENTS;
         }
         seq = ps->entityEventSequence & (MAX_PS_EVENTS - 1);
         s->event = ps->events[seq] | ((ps->entityEventSequence & 3) << 8);
         s->eventParm = ps->eventParms[seq];
         ps->entityEventSequence++;
     }
     s->weapon = ps->weapon;
     s->groundEntityNum = ps->groundEntityNum;
     s->powerups = 0;
     for (i = 0; i < MAX_POWERUPS; i++) {
         if (ps->powerups[i]) {
             s->powerups |= 1 << i;
         }
     }
     s->loopSound = ps->loopSound;
     s->generic1 = ps->generic1;
 }
References playerState_s::clientNum, EF_DEAD, playerState_s::eFlags, playerState_s::entityEventSequence, ET_INVISIBLE, ET_PLAYER, playerState_s::eventParms, playerState_s::events, playerState_s::eventSequence, playerState_s::externalEvent, playerState_s::externalEventParm, playerState_s::generic1, GIB_HEALTH, playerState_s::groundEntityNum, playerState_s::legsAnim, playerState_s::loopSound, MAX_POWERUPS, MAX_PS_EVENTS, playerState_s::movementDir, playerState_s::origin, PM_INTERMISSION, PM_SPECTATOR, playerState_s::pm_type, playerState_s::powerups, s, SnapVector, STAT_HEALTH, playerState_s::stats, playerState_s::torsoAnim, TR_INTERPOLATE, VectorCopy, playerState_s::velocity, playerState_s::viewangles, playerState_s::weapon, and YAW.
Referenced by CG_AddPacketEntities(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_TransitionSnapshot(), ClientEndFrame(), ClientSpawn(), ClientThink_real(), SendPendingPredictableEvents(), and TeleportPlayer().
BG_PlayerStateToEntityStateExtraPolate()
void BG_PlayerStateToEntityStateExtraPolate (playerState_t * ps, entityState_t * s, int time, qboolean snap)
Definition at line 1561 of file bg_misc.c.
 {
     int        i;
     if (ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPECTATOR) {
         s->eType = ET_INVISIBLE;
     } else if (ps->stats[STAT_HEALTH] <= GIB_HEALTH) {
         s->eType = ET_INVISIBLE;
     } else {
         s->eType = ET_PLAYER;
     }
     s->number = ps->clientNum;
     s->pos.trType = TR_LINEAR_STOP;
     VectorCopy(ps->origin, s->pos.trBase);
     if (snap) {
         SnapVector(s->pos.trBase);
     }
     // set the trDelta for flag direction and linear prediction
     VectorCopy(ps->velocity, s->pos.trDelta);
     // set the time for linear prediction
     s->pos.trTime = time;
     // set maximum extra polation time
     s->pos.trDuration = 50; // 1000 / sv_fps (default = 20)
     s->apos.trType = TR_INTERPOLATE;
     VectorCopy(ps->viewangles, s->apos.trBase);
     if (snap) {
         SnapVector(s->apos.trBase);
     }
     s->angles2[YAW] = ps->movementDir;
     s->legsAnim = ps->legsAnim;
     s->torsoAnim = ps->torsoAnim;
     s->clientNum = ps->clientNum;        // ET_PLAYER looks here instead of at number
                                         // so corpses can also reference the proper config
     s->eFlags = ps->eFlags;
     if (ps->stats[STAT_HEALTH] <= 0) {
         s->eFlags |= EF_DEAD;
     } else {
         s->eFlags &= ~EF_DEAD;
     }
     if (ps->externalEvent) {
         s->event = ps->externalEvent;
         s->eventParm = ps->externalEventParm;
     } else if (ps->entityEventSequence < ps->eventSequence) {
         int        seq;
         if (ps->entityEventSequence < ps->eventSequence - MAX_PS_EVENTS) {
             ps->entityEventSequence = ps->eventSequence - MAX_PS_EVENTS;
         }
         seq = ps->entityEventSequence & (MAX_PS_EVENTS - 1);
         s->event = ps->events[seq] | ((ps->entityEventSequence & 3) << 8);
         s->eventParm = ps->eventParms[seq];
         ps->entityEventSequence++;
     }
     s->weapon = ps->weapon;
     s->groundEntityNum = ps->groundEntityNum;
     s->powerups = 0;
     for (i = 0; i < MAX_POWERUPS; i++) {
         if (ps->powerups[i]) {
             s->powerups |= 1 << i;
         }
     }
     s->loopSound = ps->loopSound;
     s->generic1 = ps->generic1;
 }
References playerState_s::clientNum, EF_DEAD, playerState_s::eFlags, playerState_s::entityEventSequence, ET_INVISIBLE, ET_PLAYER, playerState_s::eventParms, playerState_s::events, playerState_s::eventSequence, playerState_s::externalEvent, playerState_s::externalEventParm, playerState_s::generic1, GIB_HEALTH, playerState_s::groundEntityNum, playerState_s::legsAnim, playerState_s::loopSound, MAX_POWERUPS, MAX_PS_EVENTS, playerState_s::movementDir, playerState_s::origin, PM_INTERMISSION, PM_SPECTATOR, playerState_s::pm_type, playerState_s::powerups, s, SnapVector, STAT_HEALTH, playerState_s::stats, playerState_s::torsoAnim, TR_INTERPOLATE, TR_LINEAR_STOP, VectorCopy, playerState_s::velocity, playerState_s::viewangles, playerState_s::weapon, and YAW.
Referenced by ClientEndFrame(), and ClientThink_real().
BG_PlayerTouchesItem()
qboolean BG_PlayerTouchesItem (playerState_t * ps, entityState_t * item, int atTime)
Definition at line 1027 of file bg_misc.c.
 {
     vec3_t        origin;
     BG_EvaluateTrajectory(&item->pos, atTime, origin);
     // we are ignoring ducked differences here
     if (ps->origin[0] - origin[0] > 44
         || ps->origin[0] - origin[0] < -50
         || ps->origin[1] - origin[1] > 36
         || ps->origin[1] - origin[1] < -36
         || ps->origin[2] - origin[2] > 36
         || ps->origin[2] - origin[2] < -36) {
         return qfalse;
     }
     return qtrue;
 }
References BG_EvaluateTrajectory(), playerState_s::origin, entityState_s::pos, qfalse, and qtrue.
Referenced by CG_TouchItem(), and G_TouchTriggers().
BG_TouchJumpPad()
void BG_TouchJumpPad (playerState_t * ps, entityState_t * jumppad)
Definition at line 1440 of file bg_misc.c.
 {
     vec3_t    angles;
     float p;
     int effectNum;
     // spectators don't use jump pads
     if (ps->pm_type != PM_NORMAL) {
         return;
     }
     // flying characters don't hit bounce pads
     if (ps->powerups[PW_FLIGHT]) {
         return;
     }
     // if we didn't hit this same jumppad the previous frame
     // then don't play the event sound again if we are in a fat trigger
     if (ps->jumppad_ent != jumppad->number) {
         vectoangles(jumppad->origin2, angles);
         p = fabs(AngleNormalize180(angles[PITCH]));
         if (p < 45) {
             effectNum = 0;
         } else {
             effectNum = 1;
         }
         BG_AddPredictableEventToPlayerstate(EV_JUMP_PAD, effectNum, ps);
     }
     // remember hitting this jumppad this frame
     ps->jumppad_ent = jumppad->number;
     ps->jumppad_frame = ps->pmove_framecount;
     // give the player the velocity from the jumppad
     VectorCopy(jumppad->origin2, ps->velocity);
 }
References AngleNormalize180(), BG_AddPredictableEventToPlayerstate(), EV_JUMP_PAD, playerState_s::jumppad_ent, playerState_s::jumppad_frame, entityState_s::number, entityState_s::origin2, PITCH, PM_NORMAL, playerState_s::pm_type, playerState_s::pmove_framecount, playerState_s::powerups, PW_FLIGHT, vectoangles(), VectorCopy, and playerState_s::velocity.
Referenced by CG_TouchTriggerPrediction(), and trigger_push_touch().
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
This is useful for obtaining cvar contents that are not bound, or cannot be bound, to a vmCvar_t variable in the mod code.
The terminating NULL is attached to the end of the copied string by this trap, guaranteeing buffer holds a null-terminated string. The total number of characters copied, including terminating NULL, fits within the size specified by bufsize, truncating the string if necessary.
A nonexistent cvar provides an empty string. An existing cvar with empty content also provides an empty string. Thus, this trap is not sufficient to determine if a cvar actually exists or not.
This trap does not create a new cvar; to create a new cvar during run-time, you can use trap_Cvar_Set or trap_SendConsoleCommand.
Parameters
var_name name of cvar (console variable).
buffer destination string buffer.
bufsize maximum limit of string buffer.
var_name
buffer
bufsize This is useful for obtaining cvar contents that are not bound, or cannot be bound, to a vmCvar_t variable in the mod code.
The terminating NULL is attached to the end of the copied string by this trap, guaranteeing buffer holds a null-terminated string. The total number of characters copied, including terminating NULL, fits within the size specified by bufsize, truncating the string if necessary.
A nonexistent cvar provides an empty string. An existing cvar with empty content also provides an empty string. Thus, this trap is not sufficient to determine if a cvar actually exists or not.
This trap does not create a new cvar; to create a new cvar during run-time, you can use trap_Cvar_Set or trap_SendConsoleCommand.
Parameters
var_name name of cvar (console variable).
buffer destination string buffer.
bufsize maximum limit of string buffer.
var_name
buffer
bufsize
Definition at line 96 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize);
 }
Referenced by BG_AddPredictableEventToPlayerstate().
Variable Documentation
bg_itemlist
gitem_t bg_itemlist[]
Definition at line 48 of file bg_misc.c.
Referenced by BG_CanItemBeGrabbed(), BG_FindItem(), BG_FindItemForHoldable(), BG_FindItemForPowerup(), BG_FindItemForWeapon(), CG_DrawPickupItem(), CG_EntityEvent(), CG_Item(), CG_ItemPickup(), CG_LoadingItem(), CG_RegisterItemSounds(), CG_RegisterItemVisuals(), CG_RegisterWeapon(), CG_TouchItem(), ClientEndFrame(), ClientThink_real(), ClientTimerActions(), Controls_InitWeapons(), FinishSpawningItem(), G_CallSpawn(), G_CheckTeamItems(), G_Damage(), LaunchItem(), Pickup_Armor(), Pickup_Health(), Pickup_Holdable(), PM_Weapon(), RegisterItem(), and UI_PlayerInfo_SetWeapon().
bg_numItems
int bg_numItems = ARRAY_LEN(bg_itemlist) - 1
Definition at line 935 of file bg_misc.c.
Referenced by BG_CanItemBeGrabbed(), BG_FindItemForHoldable(), BG_FindItemForPowerup(), CG_EntityEvent(), CG_Item(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RegisterSounds(), and SaveRegisteredItems().
eventnames
char* eventnames[]
Definition at line 1297 of file bg_misc.c.
Referenced by BG_AddPredictableEventToPlayerstate().