ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/bg_pmove.c File Reference
bg_pmove.c File Reference
#include "../qcommon/q_shared.h"
#include "bg_public.h"
#include "bg_local.h"
Functions
void PM_AddEvent (int newEvent)
void PM_AddTouchEnt (int entityNum)
static void PM_StartTorsoAnim (int anim)
static void PM_StartLegsAnim (int anim)
static void PM_ContinueLegsAnim (int anim)
static void PM_ContinueTorsoAnim (int anim)
static void PM_ForceLegsAnim (int anim)
void PM_ClipVelocity (vec3_t in, vec3_t normal, vec3_t out, float overbounce)
static void PM_Friction (void)
static void PM_Accelerate (vec3_t wishdir, float wishspeed, float accel)
static float PM_CmdScale (usercmd_t *cmd)
static void PM_SetMovementDir (void)
static qboolean PM_CheckJump (void)
static qboolean PM_CheckWaterJump (void)
static void PM_WaterJumpMove (void)
static void PM_WaterMove (void)
static void PM_FlyMove (void)
static void PM_AirMove (void)
static void PM_GrappleMove (void)
static void PM_WalkMove (void)
static void PM_DeadMove (void)
static void PM_NoclipMove (void)
static int PM_FootstepForSurface (void)
static void PM_CrashLand (void)
static int PM_CorrectAllSolid (trace_t *trace)
static void PM_GroundTraceMissed (void)
static void PM_GroundTrace (void)
static void PM_SetWaterLevel (void)
static void PM_CheckDuck (void)
static void PM_Footsteps (void)
static void PM_WaterEvents (void)
static void PM_BeginWeaponChange (int weapon)
static void PM_FinishWeaponChange (void)
static void PM_TorsoAnimation (void)
static void PM_Weapon (void)
static void PM_Animate (void)
static void PM_DropTimers (void)
void PM_UpdateViewAngles (playerState_t *ps, const usercmd_t *cmd)
void trap_SnapVector (float *v)
void PmoveSingle (pmove_t *pmove)
void Pmove (pmove_t *pmove)
Variables
pmove_t * pm
pml_t pml
float pm_stopspeed = 100.0f
float pm_duckScale = 0.25f
float pm_swimScale = 0.50f
float pm_accelerate = 10.0f
float pm_airaccelerate = 1.0f
float pm_wateraccelerate = 4.0f
float pm_flyaccelerate = 8.0f
float pm_friction = 6.0f
float pm_waterfriction = 1.0f
float pm_flightfriction = 3.0f
float pm_spectatorfriction = 5.0f
int c_pmove = 0
Function Documentation
PM_Accelerate()
static void PM_Accelerate (vec3_t wishdir, float wishspeed, float accel) static
Definition at line 239 of file bg_pmove.c.
{
 #if 1
     // q2 style
     int         i;
     float       addspeed, accelspeed, currentspeed;
     currentspeed = DotProduct (pm->ps->velocity, wishdir);
     addspeed = wishspeed - currentspeed;
     if (addspeed <= 0) {
         return;
     }
     accelspeed = accel*pml.frametime*wishspeed;
     if (accelspeed > addspeed) {
         accelspeed = addspeed;
     }
     for (i=0 ; i<3 ; i++) {
         pm->ps->velocity[i] += accelspeed*wishdir[i];
     }
 #else
     // proper way (avoids strafe jump maxspeed bug), but feels bad
     vec3_t      wishVelocity;
     vec3_t      pushDir;
     float       pushLen;
     float       canPush;
     VectorScale( wishdir, wishspeed, wishVelocity );
     VectorSubtract( wishVelocity, pm->ps->velocity, pushDir );
     pushLen = VectorNormalize( pushDir );
     canPush = accel*pml.frametime*wishspeed;
     if (canPush > pushLen) {
         canPush = pushLen;
     }
     VectorMA( pm->ps->velocity, canPush, pushDir, pm->ps->velocity );
 #endif
 }
Referenced by PM_AirMove(), PM_FlyMove(), PM_NoclipMove(), PM_WalkMove(), and PM_WaterMove().
PM_AddEvent()
void PM_AddEvent (int newEvent)
Definition at line 57 of file bg_pmove.c.
{
     BG_AddPredictableEventToPlayerstate( newEvent, 0, pm->ps );
 }
Referenced by PM_Animate(), PM_BeginWeaponChange(), PM_CheckJump(), PM_CrashLand(), PM_Footsteps(), PM_StepSlideMove(), PM_WaterEvents(), and PM_Weapon().
PM_AddTouchEnt()
void PM_AddTouchEnt (int entityNum)
Definition at line 66 of file bg_pmove.c.
{
     int     i;
     if ( entityNum == ENTITYNUM_WORLD ) {
         return;
     }
     if ( pm->numtouch == MAXTOUCH ) {
         return;
     }
     // see if it is already added
     for ( i = 0 ; i < pm->numtouch ; i++ ) {
         if ( pm->touchents[ i ] == entityNum ) {
             return;
         }
     }
     // add it
     pm->touchents[pm->numtouch] = entityNum;
     pm->numtouch++;
 }
Referenced by PM_GroundTrace(), and PM_SlideMove().
PM_AirMove()
static void PM_AirMove (void) static
Definition at line 600 of file bg_pmove.c.
{
     int         i;
     vec3_t      wishvel;
     float       fmove, smove;
     vec3_t      wishdir;
     float       wishspeed;
     float       scale;
     usercmd_t   cmd;
     PM_Friction();
     fmove = pm->cmd.forwardmove;
     smove = pm->cmd.rightmove;
     cmd = pm->cmd;
     scale = PM_CmdScale( &cmd );
     // set the movementDir so clients can rotate the legs for strafing
     PM_SetMovementDir();
     // project moves down to flat plane
     pml.forward[2] = 0;
     pml.right[2] = 0;
     VectorNormalize (pml.forward);
     VectorNormalize (pml.right);
     for ( i = 0 ; i < 2 ; i++ ) {
         wishvel[i] = pml.forward[i]*fmove + pml.right[i]*smove;
     }
     wishvel[2] = 0;
     VectorCopy (wishvel, wishdir);
     wishspeed = VectorNormalize(wishdir);
     wishspeed *= scale;
     // not on ground, so little effect on velocity
     PM_Accelerate (wishdir, wishspeed, pm_airaccelerate);
     // we may have a ground plane that is very steep, even
     // though we don't have a groundentity
     // slide along the steep plane
     if ( pml.groundPlane ) {
         PM_ClipVelocity (pm->ps->velocity, pml.groundTrace.plane.normal,
             pm->ps->velocity, OVERCLIP );
     }
 #if 0
     //ZOID:  If we are on the grapple, try stair-stepping
     //this allows a player to use the grapple to pull himself
     //over a ledge
     if (pm->ps->pm_flags & PMF_GRAPPLE_PULL)
         PM_StepSlideMove ( qtrue );
     else
         PM_SlideMove ( qtrue );
 #endif
     PM_StepSlideMove ( qtrue );
 }
Referenced by PM_WalkMove(), and PmoveSingle().
PM_Animate()
static void PM_Animate (void) static
Definition at line 1713 of file bg_pmove.c.
{
     if ( pm->cmd.buttons & BUTTON_GESTURE ) {
         if ( pm->ps->torsoTimer == 0 ) {
             PM_StartTorsoAnim( TORSO_GESTURE );
             pm->ps->torsoTimer = TIMER_GESTURE;
             PM_AddEvent( EV_TAUNT );
         }
 #ifdef MISSIONPACK
     } else if ( pm->cmd.buttons & BUTTON_GETFLAG ) {
         if ( pm->ps->torsoTimer == 0 ) {
             PM_StartTorsoAnim( TORSO_GETFLAG );
             pm->ps->torsoTimer = 600;   //TIMER_GESTURE;
         }
     } else if ( pm->cmd.buttons & BUTTON_GUARDBASE ) {
         if ( pm->ps->torsoTimer == 0 ) {
             PM_StartTorsoAnim( TORSO_GUARDBASE );
             pm->ps->torsoTimer = 600;   //TIMER_GESTURE;
         }
     } else if ( pm->cmd.buttons & BUTTON_PATROL ) {
         if ( pm->ps->torsoTimer == 0 ) {
             PM_StartTorsoAnim( TORSO_PATROL );
             pm->ps->torsoTimer = 600;   //TIMER_GESTURE;
         }
     } else if ( pm->cmd.buttons & BUTTON_FOLLOWME ) {
         if ( pm->ps->torsoTimer == 0 ) {
             PM_StartTorsoAnim( TORSO_FOLLOWME );
             pm->ps->torsoTimer = 600;   //TIMER_GESTURE;
         }
     } else if ( pm->cmd.buttons & BUTTON_AFFIRMATIVE ) {
         if ( pm->ps->torsoTimer == 0 ) {
             PM_StartTorsoAnim( TORSO_AFFIRMATIVE);
             pm->ps->torsoTimer = 600;   //TIMER_GESTURE;
         }
     } else if ( pm->cmd.buttons & BUTTON_NEGATIVE ) {
         if ( pm->ps->torsoTimer == 0 ) {
             PM_StartTorsoAnim( TORSO_NEGATIVE );
             pm->ps->torsoTimer = 600;   //TIMER_GESTURE;
         }
 #endif
     }
 }
Referenced by PmoveSingle().
PM_BeginWeaponChange()
static void PM_BeginWeaponChange (int weapon) static
Definition at line 1468 of file bg_pmove.c.
{
     if ( weapon <= WP_NONE || weapon >= WP_NUM_WEAPONS ) {
         return;
     }
     if ( !( pm->ps->stats[STAT_WEAPONS] & ( 1 << weapon ) ) ) {
         return;
     }
     if ( pm->ps->weaponstate == WEAPON_DROPPING ) {
         return;
     }
     PM_AddEvent( EV_CHANGE_WEAPON );
     pm->ps->weaponstate = WEAPON_DROPPING;
     pm->ps->weaponTime += 200;
     PM_StartTorsoAnim( TORSO_DROP );
 }
Referenced by PM_Weapon().
PM_CheckDuck()
static void PM_CheckDuck (void) static
Definition at line 1248 of file bg_pmove.c.
 {
     trace_t trace;
     if ( pm->ps->powerups[PW_INVULNERABILITY] ) {
         if ( pm->ps->pm_flags & PMF_INVULEXPAND ) {
             // invulnerability sphere has a 42 units radius
             VectorSet( pm->mins, -42, -42, -42 );
             VectorSet( pm->maxs, 42, 42, 42 );
         }
         else {
             VectorSet( pm->mins, -15, -15, MINS_Z );
             VectorSet( pm->maxs, 15, 15, 16 );
         }
         pm->ps->pm_flags |= PMF_DUCKED;
         pm->ps->viewheight = CROUCH_VIEWHEIGHT;
         return;
     }
     pm->ps->pm_flags &= ~PMF_INVULEXPAND;
     pm->mins[0] = -15;
     pm->mins[1] = -15;
     pm->maxs[0] = 15;
     pm->maxs[1] = 15;
     pm->mins[2] = MINS_Z;
     if (pm->ps->pm_type == PM_DEAD)
     {
         pm->maxs[2] = -8;
         pm->ps->viewheight = DEAD_VIEWHEIGHT;
         return;
     }
     if (pm->cmd.upmove < 0)
     {   // duck
         pm->ps->pm_flags |= PMF_DUCKED;
     }
     else
     {   // stand up if possible
         if (pm->ps->pm_flags & PMF_DUCKED)
         {
             // try to stand up
             pm->maxs[2] = 32;
             pm->trace (&trace, pm->ps->origin, pm->mins, pm->maxs, pm->ps->origin, pm->ps->clientNum, pm->tracemask );
             if (!trace.allsolid)
                 pm->ps->pm_flags &= ~PMF_DUCKED;
         }
     }
     if (pm->ps->pm_flags & PMF_DUCKED)
     {
         pm->maxs[2] = 16;
         pm->ps->viewheight = CROUCH_VIEWHEIGHT;
     }
     else
     {
         pm->maxs[2] = 32;
         pm->ps->viewheight = DEFAULT_VIEWHEIGHT;
     }
 }
Referenced by PmoveSingle().
PM_CheckJump()
static qboolean PM_CheckJump (void) static
Definition at line 358 of file bg_pmove.c.
{
     if ( pm->ps->pm_flags & PMF_RESPAWNED ) {
         return qfalse;      // don't allow jump until all buttons are up
     }
     if ( pm->cmd.upmove < 10 ) {
         // not holding jump
         return qfalse;
     }
     // must wait for jump to be released
     if ( pm->ps->pm_flags & PMF_JUMP_HELD ) {
         // clear upmove so cmdscale doesn't lower running speed
         pm->cmd.upmove = 0;
         return qfalse;
     }
     pml.groundPlane = qfalse;       // jumping away
     pml.walking = qfalse;
     pm->ps->pm_flags |= PMF_JUMP_HELD;
     pm->ps->groundEntityNum = ENTITYNUM_NONE;
     pm->ps->velocity[2] = JUMP_VELOCITY;
     PM_AddEvent( EV_JUMP );
     if ( pm->cmd.forwardmove >= 0 ) {
         PM_ForceLegsAnim( LEGS_JUMP );
         pm->ps->pm_flags &= ~PMF_BACKWARDS_JUMP;
     } else {
         PM_ForceLegsAnim( LEGS_JUMPB );
         pm->ps->pm_flags |= PMF_BACKWARDS_JUMP;
     }
     return qtrue;
 }
Referenced by PM_WalkMove().
PM_CheckWaterJump()
static qboolean PM_CheckWaterJump (void) static
Definition at line 399 of file bg_pmove.c.
{
     vec3_t  spot;
     int     cont;
     vec3_t  flatforward;
     if (pm->ps->pm_time) {
         return qfalse;
     }
     // check for water jump
     if ( pm->waterlevel != 2 ) {
         return qfalse;
     }
     flatforward[0] = pml.forward[0];
     flatforward[1] = pml.forward[1];
     flatforward[2] = 0;
     VectorNormalize (flatforward);
     VectorMA (pm->ps->origin, 30, flatforward, spot);
     spot[2] += 4;
     cont = pm->pointcontents (spot, pm->ps->clientNum );
     if ( !(cont & CONTENTS_SOLID) ) {
         return qfalse;
     }
     spot[2] += 16;
     cont = pm->pointcontents (spot, pm->ps->clientNum );
     if ( cont & (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_BODY) ) {
         return qfalse;
     }
     // jump out of water
     VectorScale (pml.forward, 200, pm->ps->velocity);
     pm->ps->velocity[2] = 350;
     pm->ps->pm_flags |= PMF_TIME_WATERJUMP;
     pm->ps->pm_time = 2000;
     return qtrue;
 }
Referenced by PM_WaterMove().
PM_ClipVelocity()
void PM_ClipVelocity (vec3_t in, vec3_t normal, vec3_t out, float overbounce)
Definition at line 144 of file bg_pmove.c.
{
     float   backoff;
     float   change;
     int     i;
     backoff = DotProduct (in, normal);
     if ( backoff < 0 ) {
         backoff *= overbounce;
     } else {
         backoff /= overbounce;
     }
     for ( i=0 ; i<3 ; i++ ) {
         change = normal[i]*backoff;
         out[i] = in[i] - change;
     }
 }
Referenced by PM_AirMove(), PM_SlideMove(), PM_StepSlideMove(), PM_WalkMove(), and PM_WaterMove().
PM_CmdScale()
static float PM_CmdScale (usercmd_t * cmd) static
Definition at line 289 of file bg_pmove.c.
{
     int     max;
     float   total;
     float   scale;
     max = abs( cmd->forwardmove );
     if ( abs( cmd->rightmove ) > max ) {
         max = abs( cmd->rightmove );
     }
     if ( abs( cmd->upmove ) > max ) {
         max = abs( cmd->upmove );
     }
     if ( !max ) {
         return 0;
     }
     total = sqrt( cmd->forwardmove * cmd->forwardmove
         + cmd->rightmove * cmd->rightmove + cmd->upmove * cmd->upmove );
     scale = (float)pm->ps->speed * max / ( 127.0 * total );
     return scale;
 }
Referenced by PM_AirMove(), PM_FlyMove(), PM_NoclipMove(), PM_WalkMove(), and PM_WaterMove().
PM_ContinueLegsAnim()
static void PM_ContinueLegsAnim (int anim) static
Definition at line 111 of file bg_pmove.c.
{
     if ( ( pm->ps->legsAnim & ~ANIM_TOGGLEBIT ) == anim ) {
         return;
     }
     if ( pm->ps->legsTimer > 0 ) {
         return;     // a high priority animation is running
     }
     PM_StartLegsAnim( anim );
 }
Referenced by PM_Footsteps().
PM_ContinueTorsoAnim()
static void PM_ContinueTorsoAnim (int anim) static
Definition at line 121 of file bg_pmove.c.
{
     if ( ( pm->ps->torsoAnim & ~ANIM_TOGGLEBIT ) == anim ) {
         return;
     }
     if ( pm->ps->torsoTimer > 0 ) {
         return;     // a high priority animation is running
     }
     PM_StartTorsoAnim( anim );
 }
Referenced by PM_TorsoAnimation().
PM_CorrectAllSolid()
static int PM_CorrectAllSolid (trace_t * trace) static
Definition at line 1023 of file bg_pmove.c.
{
     int         i, j, k;
     vec3_t      point;
     if ( pm->debugLevel ) {
         Com_Printf("%i:allsolid\n", c_pmove);
     }
     // jitter around
     for (i = -1; i <= 1; i++) {
         for (j = -1; j <= 1; j++) {
             for (k = -1; k <= 1; k++) {
                 VectorCopy(pm->ps->origin, point);
                 point[0] += (float) i;
                 point[1] += (float) j;
                 point[2] += (float) k;
                 pm->trace (trace, point, pm->mins, pm->maxs, point, pm->ps->clientNum, pm->tracemask);
                 if ( !trace->allsolid ) {
                     point[0] = pm->ps->origin[0];
                     point[1] = pm->ps->origin[1];
                     point[2] = pm->ps->origin[2] - 0.25;
                     pm->trace (trace, pm->ps->origin, pm->mins, pm->maxs, point, pm->ps->clientNum, pm->tracemask);
                     pml.groundTrace = *trace;
                     return qtrue;
                 }
             }
         }
     }
     pm->ps->groundEntityNum = ENTITYNUM_NONE;
     pml.groundPlane = qfalse;
     pml.walking = qfalse;
     return qfalse;
 }
Referenced by PM_GroundTrace().
PM_CrashLand()
static void PM_CrashLand (void) static
Definition at line 923 of file bg_pmove.c.
{
     float       delta;
     float       dist;
     float       vel, acc;
     float       t;
     float       a, b, c, den;
     // decide which landing animation to use
     if ( pm->ps->pm_flags & PMF_BACKWARDS_JUMP ) {
         PM_ForceLegsAnim( LEGS_LANDB );
     } else {
         PM_ForceLegsAnim( LEGS_LAND );
     }
     pm->ps->legsTimer = TIMER_LAND;
     // calculate the exact velocity on landing
     dist = pm->ps->origin[2] - pml.previous_origin[2];
     vel = pml.previous_velocity[2];
     acc = -pm->ps->gravity;
     a = acc / 2;
     b = vel;
     c = -dist;
     den =  b * b - 4 * a * c;
     if ( den < 0 ) {
         return;
     }
     t = (-b - sqrt( den ) ) / ( 2 * a );
     delta = vel + t * acc;
     delta = delta*delta * 0.0001;
     // ducking while falling doubles damage
     if ( pm->ps->pm_flags & PMF_DUCKED ) {
         delta *= 2;
     }
     // never take falling damage if completely underwater
     if ( pm->waterlevel == 3 ) {
         return;
     }
     // reduce falling damage if there is standing water
     if ( pm->waterlevel == 2 ) {
         delta *= 0.25;
     }
     if ( pm->waterlevel == 1 ) {
         delta *= 0.5;
     }
     if ( delta < 1 ) {
         return;
     }
     // create a local entity event to play the sound
     // SURF_NODAMAGE is used for bounce pads where you don't ever
     // want to take damage or play a crunch sound
     if ( !(pml.groundTrace.surfaceFlags & SURF_NODAMAGE) )  {
         if ( delta > 60 ) {
             PM_AddEvent( EV_FALL_FAR );
         } else if ( delta > 40 ) {
             // this is a pain grunt, so don't play it if dead
             if ( pm->ps->stats[STAT_HEALTH] > 0 ) {
                 PM_AddEvent( EV_FALL_MEDIUM );
             }
         } else if ( delta > 7 ) {
             PM_AddEvent( EV_FALL_SHORT );
         } else {
             PM_AddEvent( PM_FootstepForSurface() );
         }
     }
     // start footstep cycle over
     pm->ps->bobCycle = 0;
 }
Referenced by PM_GroundTrace().
PM_DeadMove()
static void PM_DeadMove (void) static
Definition at line 816 of file bg_pmove.c.
{
     float   forward;
     if ( !pml.walking ) {
         return;
     }
     // extra friction
     forward = VectorLength (pm->ps->velocity);
     forward -= 20;
     if ( forward <= 0 ) {
         VectorClear (pm->ps->velocity);
     } else {
         VectorNormalize (pm->ps->velocity);
         VectorScale (pm->ps->velocity, forward, pm->ps->velocity);
     }
 }
Referenced by PmoveSingle().
PM_DropTimers()
static void PM_DropTimers (void) static
Definition at line 1761 of file bg_pmove.c.
{
     // drop misc timing counter
     if ( pm->ps->pm_time ) {
         if ( pml.msec >= pm->ps->pm_time ) {
             pm->ps->pm_flags &= ~PMF_ALL_TIMES;
             pm->ps->pm_time = 0;
         } else {
             pm->ps->pm_time -= pml.msec;
         }
     }
     // drop animation counter
     if ( pm->ps->legsTimer > 0 ) {
         pm->ps->legsTimer -= pml.msec;
         if ( pm->ps->legsTimer < 0 ) {
             pm->ps->legsTimer = 0;
         }
     }
     if ( pm->ps->torsoTimer > 0 ) {
         pm->ps->torsoTimer -= pml.msec;
         if ( pm->ps->torsoTimer < 0 ) {
             pm->ps->torsoTimer = 0;
         }
     }
 }
Referenced by PmoveSingle().
PM_FinishWeaponChange()
static void PM_FinishWeaponChange (void) static
Definition at line 1493 of file bg_pmove.c.
{
     int     weapon;
     weapon = pm->cmd.weapon;
     if ( weapon < WP_NONE || weapon >= WP_NUM_WEAPONS ) {
         weapon = WP_NONE;
     }
     if ( !( pm->ps->stats[STAT_WEAPONS] & ( 1 << weapon ) ) ) {
         weapon = WP_NONE;
     }
     pm->ps->weapon = weapon;
     pm->ps->weaponstate = WEAPON_RAISING;
     pm->ps->weaponTime += 250;
     PM_StartTorsoAnim( TORSO_RAISE );
 }
Referenced by PM_Weapon().
PM_FlyMove()
static void PM_FlyMove (void) static
Definition at line 559 of file bg_pmove.c.
{
     int     i;
     vec3_t  wishvel;
     float   wishspeed;
     vec3_t  wishdir;
     float   scale;
     // normal slowdown
     PM_Friction ();
     scale = PM_CmdScale( &pm->cmd );
     //
     // user intentions
     //
     if ( !scale ) {
         wishvel[0] = 0;
         wishvel[1] = 0;
         wishvel[2] = 0;
     } else {
         for (i=0 ; i<3 ; i++) {
             wishvel[i] = scale * pml.forward[i]*pm->cmd.forwardmove + scale * pml.right[i]*pm->cmd.rightmove;
         }
         wishvel[2] += scale * pm->cmd.upmove;
     }
     VectorCopy (wishvel, wishdir);
     wishspeed = VectorNormalize(wishdir);
     PM_Accelerate (wishdir, wishspeed, pm_flyaccelerate);
     PM_StepSlideMove( qfalse );
 }
Referenced by PmoveSingle().
PM_FootstepForSurface()
static int PM_FootstepForSurface (void) static
Definition at line 905 of file bg_pmove.c.
{
     if ( pml.groundTrace.surfaceFlags & SURF_NOSTEPS ) {
         return 0;
     }
     if ( pml.groundTrace.surfaceFlags & SURF_METALSTEPS ) {
         return EV_FOOTSTEP_METAL;
     }
     return EV_FOOTSTEP;
 }
Referenced by PM_CrashLand(), and PM_Footsteps().
PM_Footsteps()
static void PM_Footsteps (void) static
Definition at line 1321 of file bg_pmove.c.
{
     float       bobmove;
     int         old;
     qboolean    footstep;
     //
     // calculate speed and cycle to be used for
     // all cyclic walking effects
     //
     pm->xyspeed = sqrt( pm->ps->velocity[0] * pm->ps->velocity[0]
         +  pm->ps->velocity[1] * pm->ps->velocity[1] );
     if ( pm->ps->groundEntityNum == ENTITYNUM_NONE ) {
         if ( pm->ps->powerups[PW_INVULNERABILITY] ) {
             PM_ContinueLegsAnim( LEGS_IDLECR );
         }
         // airborne leaves position in cycle intact, but doesn't advance
         if ( pm->waterlevel > 1 ) {
             PM_ContinueLegsAnim( LEGS_SWIM );
         }
         return;
     }
     // if not trying to move
     if ( !pm->cmd.forwardmove && !pm->cmd.rightmove ) {
         if (  pm->xyspeed < 5 ) {
             pm->ps->bobCycle = 0;   // start at beginning of cycle again
             if ( pm->ps->pm_flags & PMF_DUCKED ) {
                 PM_ContinueLegsAnim( LEGS_IDLECR );
             } else {
                 PM_ContinueLegsAnim( LEGS_IDLE );
             }
         }
         return;
     }
     footstep = qfalse;
     if ( pm->ps->pm_flags & PMF_DUCKED ) {
         bobmove = 0.5;  // ducked characters bob much faster
         if ( pm->ps->pm_flags & PMF_BACKWARDS_RUN ) {
             PM_ContinueLegsAnim( LEGS_BACKCR );
         }
         else {
             PM_ContinueLegsAnim( LEGS_WALKCR );
         }
         // ducked characters never play footsteps
     /*
     } else  if ( pm->ps->pm_flags & PMF_BACKWARDS_RUN ) {
         if ( !( pm->cmd.buttons & BUTTON_WALKING ) ) {
             bobmove = 0.4;  // faster speeds bob faster
             footstep = qtrue;
         } else {
             bobmove = 0.3;
         }
         PM_ContinueLegsAnim( LEGS_BACK );
     */
     } else {
         if ( !( pm->cmd.buttons & BUTTON_WALKING ) ) {
             bobmove = 0.4f; // faster speeds bob faster
             if ( pm->ps->pm_flags & PMF_BACKWARDS_RUN ) {
                 PM_ContinueLegsAnim( LEGS_BACK );
             }
             else {
                 PM_ContinueLegsAnim( LEGS_RUN );
             }
             footstep = qtrue;
         } else {
             bobmove = 0.3f; // walking bobs slow
             if ( pm->ps->pm_flags & PMF_BACKWARDS_RUN ) {
                 PM_ContinueLegsAnim( LEGS_BACKWALK );
             }
             else {
                 PM_ContinueLegsAnim( LEGS_WALK );
             }
         }
     }
     // check for footstep / splash sounds
     old = pm->ps->bobCycle;
     pm->ps->bobCycle = (int)( old + bobmove * pml.msec ) & 255;
     // if we just crossed a cycle boundary, play an appropriate footstep event
     if ( ( ( old + 64 ) ^ ( pm->ps->bobCycle + 64 ) ) & 128 ) {
         if ( pm->waterlevel == 0 ) {
             // on ground will only play sounds if running
             if ( footstep && !pm->noFootsteps ) {
                 PM_AddEvent( PM_FootstepForSurface() );
             }
         } else if ( pm->waterlevel == 1 ) {
             // splashing
             PM_AddEvent( EV_FOOTSPLASH );
         } else if ( pm->waterlevel == 2 ) {
             // wading / swimming at surface
             PM_AddEvent( EV_SWIM );
         } else if ( pm->waterlevel == 3 ) {
             // no sound when completely underwater
         }
     }
 }
Referenced by PmoveSingle().
PM_ForceLegsAnim()
static void PM_ForceLegsAnim (int anim) static
Definition at line 131 of file bg_pmove.c.
{
     pm->ps->legsTimer = 0;
     PM_StartLegsAnim( anim );
 }
Referenced by PM_CheckJump(), PM_CrashLand(), PM_GroundTrace(), and PM_GroundTraceMissed().
PM_Friction()
static void PM_Friction (void) static
Definition at line 171 of file bg_pmove.c.
{
     vec3_t  vec;
     float   *vel;
     float   speed, newspeed, control;
     float   drop;
     vel = pm->ps->velocity;
     VectorCopy( vel, vec );
     if ( pml.walking ) {
         vec[2] = 0; // ignore slope movement
     }
     speed = VectorLength(vec);
     if (speed < 1) {
         vel[0] = 0;
         vel[1] = 0;     // allow sinking underwater
         // FIXME: still have z friction underwater?
         return;
     }
     drop = 0;
     // apply ground friction
     if ( pm->waterlevel <= 1 ) {
         if ( pml.walking && !(pml.groundTrace.surfaceFlags & SURF_SLICK) ) {
             // if getting knocked back, no friction
             if ( ! (pm->ps->pm_flags & PMF_TIME_KNOCKBACK) ) {
                 control = speed < pm_stopspeed ? pm_stopspeed : speed;
                 drop += control*pm_friction*pml.frametime;
             }
         }
     }
     // apply water friction even if just wading
     if ( pm->waterlevel ) {
         drop += speed*pm_waterfriction*pm->waterlevel*pml.frametime;
     }
     // apply flying friction
     if ( pm->ps->powerups[PW_FLIGHT]) {
         drop += speed*pm_flightfriction*pml.frametime;
     }
     if ( pm->ps->pm_type == PM_SPECTATOR) {
         drop += speed*pm_spectatorfriction*pml.frametime;
     }
     // scale the velocity
     newspeed = speed - drop;
     if (newspeed < 0) {
         newspeed = 0;
     }
     newspeed /= speed;
     vel[0] = vel[0] * newspeed;
     vel[1] = vel[1] * newspeed;
     vel[2] = vel[2] * newspeed;
 }
Referenced by PM_AirMove(), PM_FlyMove(), PM_WalkMove(), and PM_WaterMove().
PM_GrappleMove()
static void PM_GrappleMove (void) static
Definition at line 665 of file bg_pmove.c.
{
     vec3_t vel, v;
     float vlen;
     VectorScale(pml.forward, -16, v);
     VectorAdd(pm->ps->grapplePoint, v, v);
     VectorSubtract(v, pm->ps->origin, vel);
     vlen = VectorLength(vel);
     VectorNormalize( vel );
     if (vlen <= 100)
         VectorScale(vel, 10 * vlen, vel);
     else
         VectorScale(vel, 800, vel);
     VectorCopy(vel, pm->ps->velocity);
     pml.groundPlane = qfalse;
 }
Referenced by PmoveSingle().
PM_GroundTrace()
static void PM_GroundTrace (void) static
Definition at line 1106 of file bg_pmove.c.
{
     vec3_t      point;
     trace_t     trace;
     point[0] = pm->ps->origin[0];
     point[1] = pm->ps->origin[1];
     point[2] = pm->ps->origin[2] - 0.25;
     pm->trace (&trace, pm->ps->origin, pm->mins, pm->maxs, point, pm->ps->clientNum, pm->tracemask);
     pml.groundTrace = trace;
     // do something corrective if the trace starts in a solid...
     if ( trace.allsolid ) {
         if ( !PM_CorrectAllSolid(&trace) )
             return;
     }
     // if the trace didn't hit anything, we are in free fall
     if ( trace.fraction == 1.0 ) {
         PM_GroundTraceMissed();
         pml.groundPlane = qfalse;
         pml.walking = qfalse;
         return;
     }
     // check if getting thrown off the ground
     if ( pm->ps->velocity[2] > 0 && DotProduct( pm->ps->velocity, trace.plane.normal ) > 10 ) {
         if ( pm->debugLevel ) {
             Com_Printf("%i:kickoff\n", c_pmove);
         }
         // go into jump animation
         if ( pm->cmd.forwardmove >= 0 ) {
             PM_ForceLegsAnim( LEGS_JUMP );
             pm->ps->pm_flags &= ~PMF_BACKWARDS_JUMP;
         } else {
             PM_ForceLegsAnim( LEGS_JUMPB );
             pm->ps->pm_flags |= PMF_BACKWARDS_JUMP;
         }
         pm->ps->groundEntityNum = ENTITYNUM_NONE;
         pml.groundPlane = qfalse;
         pml.walking = qfalse;
         return;
     }
     // slopes that are too steep will not be considered onground
     if ( trace.plane.normal[2] < MIN_WALK_NORMAL ) {
         if ( pm->debugLevel ) {
             Com_Printf("%i:steep\n", c_pmove);
         }
         // FIXME: if they can't slide down the slope, let them
         // walk (sharp crevices)
         pm->ps->groundEntityNum = ENTITYNUM_NONE;
         pml.groundPlane = qtrue;
         pml.walking = qfalse;
         return;
     }
     pml.groundPlane = qtrue;
     pml.walking = qtrue;
     // hitting solid ground will end a waterjump
     if (pm->ps->pm_flags & PMF_TIME_WATERJUMP)
     {
         pm->ps->pm_flags &= ~(PMF_TIME_WATERJUMP | PMF_TIME_LAND);
         pm->ps->pm_time = 0;
     }
     if ( pm->ps->groundEntityNum == ENTITYNUM_NONE ) {
         // just hit the ground
         if ( pm->debugLevel ) {
             Com_Printf("%i:Land\n", c_pmove);
         }
         PM_CrashLand();
         // don't do landing time if we were just going down a slope
         if ( pml.previous_velocity[2] < -200 ) {
             // don't allow another jump for a little while
             pm->ps->pm_flags |= PMF_TIME_LAND;
             pm->ps->pm_time = 250;
         }
     }
     pm->ps->groundEntityNum = trace.entityNum;
     // don't reset the z velocity for slopes
 //  pm->ps->velocity[2] = 0;
     PM_AddTouchEnt( trace.entityNum );
 }
Referenced by PmoveSingle().
PM_GroundTraceMissed()
static void PM_GroundTraceMissed (void) static
Definition at line 1068 of file bg_pmove.c.
{
     trace_t     trace;
     vec3_t      point;
     if ( pm->ps->groundEntityNum != ENTITYNUM_NONE ) {
         // we just transitioned into freefall
         if ( pm->debugLevel ) {
             Com_Printf("%i:lift\n", c_pmove);
         }
         // if they aren't in a jumping animation and the ground is a ways away, force into it
         // if we didn't do the trace, the player would be backflipping down staircases
         VectorCopy( pm->ps->origin, point );
         point[2] -= 64;
         pm->trace (&trace, pm->ps->origin, pm->mins, pm->maxs, point, pm->ps->clientNum, pm->tracemask);
         if ( trace.fraction == 1.0 ) {
             if ( pm->cmd.forwardmove >= 0 ) {
                 PM_ForceLegsAnim( LEGS_JUMP );
                 pm->ps->pm_flags &= ~PMF_BACKWARDS_JUMP;
             } else {
                 PM_ForceLegsAnim( LEGS_JUMPB );
                 pm->ps->pm_flags |= PMF_BACKWARDS_JUMP;
             }
         }
     }
     pm->ps->groundEntityNum = ENTITYNUM_NONE;
     pml.groundPlane = qfalse;
     pml.walking = qfalse;
 }
Referenced by PM_GroundTrace().
PM_NoclipMove()
static void PM_NoclipMove (void) static
Definition at line 841 of file bg_pmove.c.
{
     float   speed, drop, friction, control, newspeed;
     int         i;
     vec3_t      wishvel;
     float       fmove, smove;
     vec3_t      wishdir;
     float       wishspeed;
     float       scale;
     pm->ps->viewheight = DEFAULT_VIEWHEIGHT;
     // friction
     speed = VectorLength (pm->ps->velocity);
     if (speed < 1)
     {
         VectorCopy (vec3_origin, pm->ps->velocity);
     }
     else
     {
         drop = 0;
         friction = pm_friction*1.5; // extra friction
         control = speed < pm_stopspeed ? pm_stopspeed : speed;
         drop += control*friction*pml.frametime;
         // scale the velocity
         newspeed = speed - drop;
         if (newspeed < 0)
             newspeed = 0;
         newspeed /= speed;
         VectorScale (pm->ps->velocity, newspeed, pm->ps->velocity);
     }
     // accelerate
     scale = PM_CmdScale( &pm->cmd );
     fmove = pm->cmd.forwardmove;
     smove = pm->cmd.rightmove;
     for (i=0 ; i<3 ; i++)
         wishvel[i] = pml.forward[i]*fmove + pml.right[i]*smove;
     wishvel[2] += pm->cmd.upmove;
     VectorCopy (wishvel, wishdir);
     wishspeed = VectorNormalize(wishdir);
     wishspeed *= scale;
     PM_Accelerate( wishdir, wishspeed, pm_accelerate );
     // move
     VectorMA (pm->ps->origin, pml.frametime, pm->ps->velocity, pm->ps->origin);
 }
Referenced by PmoveSingle().
PM_SetMovementDir()
static void PM_SetMovementDir (void) static
Definition at line 321 of file bg_pmove.c.
{
     if ( pm->cmd.forwardmove || pm->cmd.rightmove ) {
         if ( pm->cmd.rightmove == 0 && pm->cmd.forwardmove > 0 ) {
             pm->ps->movementDir = 0;
         } else if ( pm->cmd.rightmove < 0 && pm->cmd.forwardmove > 0 ) {
             pm->ps->movementDir = 1;
         } else if ( pm->cmd.rightmove < 0 && pm->cmd.forwardmove == 0 ) {
             pm->ps->movementDir = 2;
         } else if ( pm->cmd.rightmove < 0 && pm->cmd.forwardmove < 0 ) {
             pm->ps->movementDir = 3;
         } else if ( pm->cmd.rightmove == 0 && pm->cmd.forwardmove < 0 ) {
             pm->ps->movementDir = 4;
         } else if ( pm->cmd.rightmove > 0 && pm->cmd.forwardmove < 0 ) {
             pm->ps->movementDir = 5;
         } else if ( pm->cmd.rightmove > 0 && pm->cmd.forwardmove == 0 ) {
             pm->ps->movementDir = 6;
         } else if ( pm->cmd.rightmove > 0 && pm->cmd.forwardmove > 0 ) {
             pm->ps->movementDir = 7;
         }
     } else {
         // if they aren't actively going directly sideways,
         // change the animation to the diagonal so they
         // don't stop too crooked
         if ( pm->ps->movementDir == 2 ) {
             pm->ps->movementDir = 1;
         } else if ( pm->ps->movementDir == 6 ) {
             pm->ps->movementDir = 7;
         }
     }
 }
Referenced by PM_AirMove(), and PM_WalkMove().
PM_SetWaterLevel()
static void PM_SetWaterLevel (void) static
Definition at line 1204 of file bg_pmove.c.
{
     vec3_t      point;
     int         cont;
     int         sample1;
     int         sample2;
     //
     // get waterlevel, accounting for ducking
     //
     pm->waterlevel = 0;
     pm->watertype = 0;
     point[0] = pm->ps->origin[0];
     point[1] = pm->ps->origin[1];
     point[2] = pm->ps->origin[2] + MINS_Z + 1;
     cont = pm->pointcontents( point, pm->ps->clientNum );
     if ( cont & MASK_WATER ) {
         sample2 = pm->ps->viewheight - MINS_Z;
         sample1 = sample2 / 2;
         pm->watertype = cont;
         pm->waterlevel = 1;
         point[2] = pm->ps->origin[2] + MINS_Z + sample1;
         cont = pm->pointcontents (point, pm->ps->clientNum );
         if ( cont & MASK_WATER ) {
             pm->waterlevel = 2;
             point[2] = pm->ps->origin[2] + MINS_Z + sample2;
             cont = pm->pointcontents (point, pm->ps->clientNum );
             if ( cont & MASK_WATER ){
                 pm->waterlevel = 3;
             }
         }
     }
 }
Referenced by PmoveSingle().
PM_StartLegsAnim()
static void PM_StartLegsAnim (int anim) static
Definition at line 100 of file bg_pmove.c.
{
     if ( pm->ps->pm_type >= PM_DEAD ) {
         return;
     }
     if ( pm->ps->legsTimer > 0 ) {
         return;     // a high priority animation is running
     }
     pm->ps->legsAnim = ( ( pm->ps->legsAnim & ANIM_TOGGLEBIT ) ^ ANIM_TOGGLEBIT )
         | anim;
 }
Referenced by PM_ContinueLegsAnim(), and PM_ForceLegsAnim().
PM_StartTorsoAnim()
static void PM_StartTorsoAnim (int anim) static
Definition at line 93 of file bg_pmove.c.
{
     if ( pm->ps->pm_type >= PM_DEAD ) {
         return;
     }
     pm->ps->torsoAnim = ( ( pm->ps->torsoAnim & ANIM_TOGGLEBIT ) ^ ANIM_TOGGLEBIT )
         | anim;
 }
Referenced by PM_Animate(), PM_BeginWeaponChange(), PM_ContinueTorsoAnim(), PM_FinishWeaponChange(), and PM_Weapon().
PM_TorsoAnimation()
static void PM_TorsoAnimation (void) static
Definition at line 1518 of file bg_pmove.c.
{
     if ( pm->ps->weaponstate == WEAPON_READY ) {
         if ( pm->ps->weapon == WP_GAUNTLET ) {
             PM_ContinueTorsoAnim( TORSO_STAND2 );
         } else {
             PM_ContinueTorsoAnim( TORSO_STAND );
         }
         return;
     }
 }
Referenced by PmoveSingle().
PM_UpdateViewAngles()
void PM_UpdateViewAngles (playerState_t * ps, const usercmd_t * cmd)
Definition at line 1796 of file bg_pmove.c.
{
     short       temp;
     int     i;
     if ( ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPINTERMISSION) {
         return;     // no view changes at all
     }
     if ( ps->pm_type != PM_SPECTATOR && ps->stats[STAT_HEALTH] <= 0 ) {
         return;     // no view changes at all
     }
     // circularly clamp the angles with deltas
     for (i=0 ; i<3 ; i++) {
         temp = cmd->angles[i] + ps->delta_angles[i];
         if ( i == PITCH ) {
             // don't let the player look up or down more than 90 degrees
             if ( temp > 16000 ) {
                 ps->delta_angles[i] = 16000 - cmd->angles[i];
                 temp = 16000;
             } else if ( temp < -16000 ) {
                 ps->delta_angles[i] = -16000 - cmd->angles[i];
                 temp = -16000;
             }
         }
         ps->viewangles[i] = SHORT2ANGLE(temp);
     }
 }
Referenced by CG_InterpolatePlayerState(), CG_PredictPlayerState(), and PmoveSingle().
PM_WalkMove()
static void PM_WalkMove (void) static
Definition at line 691 of file bg_pmove.c.
{
     int         i;
     vec3_t      wishvel;
     float       fmove, smove;
     vec3_t      wishdir;
     float       wishspeed;
     float       scale;
     usercmd_t   cmd;
     float       accelerate;
     float       vel;
     if ( pm->waterlevel > 2 && DotProduct( pml.forward, pml.groundTrace.plane.normal ) > 0 ) {
         // begin swimming
         PM_WaterMove();
         return;
     }
     if ( PM_CheckJump () ) {
         // jumped away
         if ( pm->waterlevel > 1 ) {
             PM_WaterMove();
         } else {
             PM_AirMove();
         }
         return;
     }
     PM_Friction ();
     fmove = pm->cmd.forwardmove;
     smove = pm->cmd.rightmove;
     cmd = pm->cmd;
     scale = PM_CmdScale( &cmd );
     // set the movementDir so clients can rotate the legs for strafing
     PM_SetMovementDir();
     // project moves down to flat plane
     pml.forward[2] = 0;
     pml.right[2] = 0;
     // project the forward and right directions onto the ground plane
     PM_ClipVelocity (pml.forward, pml.groundTrace.plane.normal, pml.forward, OVERCLIP );
     PM_ClipVelocity (pml.right, pml.groundTrace.plane.normal, pml.right, OVERCLIP );
     //
     VectorNormalize (pml.forward);
     VectorNormalize (pml.right);
     for ( i = 0 ; i < 3 ; i++ ) {
         wishvel[i] = pml.forward[i]*fmove + pml.right[i]*smove;
     }
     // when going up or down slopes the wish velocity should Not be zero
 //  wishvel[2] = 0;
     VectorCopy (wishvel, wishdir);
     wishspeed = VectorNormalize(wishdir);
     wishspeed *= scale;
     // clamp the speed lower if ducking
     if ( pm->ps->pm_flags & PMF_DUCKED ) {
         if ( wishspeed > pm->ps->speed * pm_duckScale ) {
             wishspeed = pm->ps->speed * pm_duckScale;
         }
     }
     // clamp the speed lower if wading or walking on the bottom
     if ( pm->waterlevel ) {
         float   waterScale;
         waterScale = pm->waterlevel / 3.0;
         waterScale = 1.0 - ( 1.0 - pm_swimScale ) * waterScale;
         if ( wishspeed > pm->ps->speed * waterScale ) {
             wishspeed = pm->ps->speed * waterScale;
         }
     }
     // when a player gets hit, they temporarily lose
     // full control, which allows them to be moved a bit
     if ( ( pml.groundTrace.surfaceFlags & SURF_SLICK ) || pm->ps->pm_flags & PMF_TIME_KNOCKBACK ) {
         accelerate = pm_airaccelerate;
     } else {
         accelerate = pm_accelerate;
     }
     PM_Accelerate (wishdir, wishspeed, accelerate);
     //Com_Printf("velocity = %1.1f %1.1f %1.1f\n", pm->ps->velocity[0], pm->ps->velocity[1], pm->ps->velocity[2]);
     //Com_Printf("velocity1 = %1.1f\n", VectorLength(pm->ps->velocity));
     if ( ( pml.groundTrace.surfaceFlags & SURF_SLICK ) || pm->ps->pm_flags & PMF_TIME_KNOCKBACK ) {
         pm->ps->velocity[2] -= pm->ps->gravity * pml.frametime;
     } else {
         // don't reset the z velocity for slopes
 //      pm->ps->velocity[2] = 0;
     }
     vel = VectorLength(pm->ps->velocity);
     // slide along the ground plane
     PM_ClipVelocity (pm->ps->velocity, pml.groundTrace.plane.normal,
         pm->ps->velocity, OVERCLIP );
     // don't decrease velocity when going up or down a slope
     VectorNormalize(pm->ps->velocity);
     VectorScale(pm->ps->velocity, vel, pm->ps->velocity);
     // don't do anything if standing still
     if (!pm->ps->velocity[0] && !pm->ps->velocity[1]) {
         return;
     }
     PM_StepSlideMove( qfalse );
     //Com_Printf("velocity2 = %1.1f\n", VectorLength(pm->ps->velocity));
 }
Referenced by PmoveSingle().
PM_WaterEvents()
static void PM_WaterEvents (void) static
Definition at line 1432 of file bg_pmove.c.
                                    {        // FIXME?
     //
     // if just entered a water volume, play a sound
     //
     if (!pml.previous_waterlevel && pm->waterlevel) {
         PM_AddEvent( EV_WATER_TOUCH );
     }
     //
     // if just completely exited a water volume, play a sound
     //
     if (pml.previous_waterlevel && !pm->waterlevel) {
         PM_AddEvent( EV_WATER_LEAVE );
     }
     //
     // check for head just going under water
     //
     if (pml.previous_waterlevel != 3 && pm->waterlevel == 3) {
         PM_AddEvent( EV_WATER_UNDER );
     }
     //
     // check for head just coming out of water
     //
     if (pml.previous_waterlevel == 3 && pm->waterlevel != 3) {
         PM_AddEvent( EV_WATER_CLEAR );
     }
 }
Referenced by PmoveSingle().
PM_WaterJumpMove()
static void PM_WaterJumpMove (void) static
Definition at line 451 of file bg_pmove.c.
{
     // waterjump has no control, but falls
     PM_StepSlideMove( qtrue );
     pm->ps->velocity[2] -= pm->ps->gravity * pml.frametime;
     if (pm->ps->velocity[2] < 0) {
         // cancel as soon as we are falling down again
         pm->ps->pm_flags &= ~PMF_ALL_TIMES;
         pm->ps->pm_time = 0;
     }
 }
Referenced by PM_WaterMove(), and PmoveSingle().
PM_WaterMove()
static void PM_WaterMove (void) static
Definition at line 470 of file bg_pmove.c.
{
     int     i;
     vec3_t  wishvel;
     float   wishspeed;
     vec3_t  wishdir;
     float   scale;
     float   vel;
     if ( PM_CheckWaterJump() ) {
         PM_WaterJumpMove();
         return;
     }
 #if 0
     // jump = head for surface
     if ( pm->cmd.upmove >= 10 ) {
         if (pm->ps->velocity[2] > -300) {
             if ( pm->watertype & CONTENTS_WATER ) {
                 pm->ps->velocity[2] = 100;
             } else if ( pm->watertype & CONTENTS_SLIME ) {
                 pm->ps->velocity[2] = 80;
             } else {
                 pm->ps->velocity[2] = 50;
             }
         }
     }
 #endif
     PM_Friction ();
     scale = PM_CmdScale( &pm->cmd );
     //
     // user intentions
     //
     if ( !scale ) {
         wishvel[0] = 0;
         wishvel[1] = 0;
         wishvel[2] = -60;       // sink towards bottom
     } else {
         for (i=0 ; i<3 ; i++)
             wishvel[i] = scale * pml.forward[i]*pm->cmd.forwardmove + scale * pml.right[i]*pm->cmd.rightmove;
         wishvel[2] += scale * pm->cmd.upmove;
     }
     VectorCopy (wishvel, wishdir);
     wishspeed = VectorNormalize(wishdir);
     if ( wishspeed > pm->ps->speed * pm_swimScale ) {
         wishspeed = pm->ps->speed * pm_swimScale;
     }
     PM_Accelerate (wishdir, wishspeed, pm_wateraccelerate);
     // make sure we can go up slopes easily under water
     if ( pml.groundPlane && DotProduct( pm->ps->velocity, pml.groundTrace.plane.normal ) < 0 ) {
         vel = VectorLength(pm->ps->velocity);
         // slide along the ground plane
         PM_ClipVelocity (pm->ps->velocity, pml.groundTrace.plane.normal,
             pm->ps->velocity, OVERCLIP );
         VectorNormalize(pm->ps->velocity);
         VectorScale(pm->ps->velocity, vel, pm->ps->velocity);
     }
     PM_SlideMove( qfalse );
 }
Referenced by PM_WalkMove(), and PmoveSingle().
PM_Weapon()
static void PM_Weapon (void) static
Definition at line 1537 of file bg_pmove.c.
{
     int     addTime;
     // don't allow attack until all buttons are up
     if ( pm->ps->pm_flags & PMF_RESPAWNED ) {
         return;
     }
     // ignore if spectator
     if ( pm->ps->persistant[PERS_TEAM] == TEAM_SPECTATOR ) {
         return;
     }
     // check for dead player
     if ( pm->ps->stats[STAT_HEALTH] <= 0 ) {
         pm->ps->weapon = WP_NONE;
         return;
     }
     // check for item using
     if ( pm->cmd.buttons & BUTTON_USE_HOLDABLE ) {
         if ( ! ( pm->ps->pm_flags & PMF_USE_ITEM_HELD ) ) {
             if ( bg_itemlist[pm->ps->stats[STAT_HOLDABLE_ITEM]].giTag == HI_MEDKIT
                 && pm->ps->stats[STAT_HEALTH] >= (pm->ps->stats[STAT_MAX_HEALTH] + 25) ) {
                 // don't use medkit if at max health
             } else {
                 pm->ps->pm_flags |= PMF_USE_ITEM_HELD;
                 PM_AddEvent( EV_USE_ITEM0 + bg_itemlist[pm->ps->stats[STAT_HOLDABLE_ITEM]].giTag );
                 pm->ps->stats[STAT_HOLDABLE_ITEM] = 0;
             }
             return;
         }
     } else {
         pm->ps->pm_flags &= ~PMF_USE_ITEM_HELD;
     }
     // make weapon function
     if ( pm->ps->weaponTime > 0 ) {
         pm->ps->weaponTime -= pml.msec;
     }
     // check for weapon change
     // can't change if weapon is firing, but can change
     // again if lowering or raising
     if ( pm->ps->weaponTime <= 0 || pm->ps->weaponstate != WEAPON_FIRING ) {
         if ( pm->ps->weapon != pm->cmd.weapon ) {
             PM_BeginWeaponChange( pm->cmd.weapon );
         }
     }
     if ( pm->ps->weaponTime > 0 ) {
         return;
     }
     // change weapon if time
     if ( pm->ps->weaponstate == WEAPON_DROPPING ) {
         PM_FinishWeaponChange();
         return;
     }
     if ( pm->ps->weaponstate == WEAPON_RAISING ) {
         pm->ps->weaponstate = WEAPON_READY;
         if ( pm->ps->weapon == WP_GAUNTLET ) {
             PM_StartTorsoAnim( TORSO_STAND2 );
         } else {
             PM_StartTorsoAnim( TORSO_STAND );
         }
         return;
     }
     // check for fire
     if ( ! (pm->cmd.buttons & BUTTON_ATTACK) ) {
         pm->ps->weaponTime = 0;
         pm->ps->weaponstate = WEAPON_READY;
         return;
     }
     // start the animation even if out of ammo
     if ( pm->ps->weapon == WP_GAUNTLET ) {
         // the guantlet only "fires" when it actually hits something
         if ( !pm->gauntletHit ) {
             pm->ps->weaponTime = 0;
             pm->ps->weaponstate = WEAPON_READY;
             return;
         }
         PM_StartTorsoAnim( TORSO_ATTACK2 );
     } else {
         PM_StartTorsoAnim( TORSO_ATTACK );
     }
     pm->ps->weaponstate = WEAPON_FIRING;
     // check for out of ammo
     if ( ! pm->ps->ammo[ pm->ps->weapon ] ) {
         PM_AddEvent( EV_NOAMMO );
         pm->ps->weaponTime += 500;
         return;
     }
     // take an ammo away if not infinite
     if ( pm->ps->ammo[ pm->ps->weapon ] != -1 ) {
         pm->ps->ammo[ pm->ps->weapon ]--;
     }
     // fire weapon
     PM_AddEvent( EV_FIRE_WEAPON );
     switch( pm->ps->weapon ) {
     default:
     case WP_GAUNTLET:
         addTime = 400;
         break;
     case WP_LIGHTNING:
         addTime = 50;
         break;
     case WP_SHOTGUN:
         addTime = 1000;
         break;
     case WP_MACHINEGUN:
         addTime = 100;
         break;
     case WP_GRENADE_LAUNCHER:
         addTime = 800;
         break;
     case WP_ROCKET_LAUNCHER:
         addTime = 800;
         break;
     case WP_PLASMAGUN:
         addTime = 100;
         break;
     case WP_RAILGUN:
         addTime = 1500;
         break;
     case WP_BFG:
         addTime = 200;
         break;
     case WP_GRAPPLING_HOOK:
         addTime = 400;
         break;
 #ifdef MISSIONPACK
     case WP_NAILGUN:
         addTime = 1000;
         break;
     case WP_PROX_LAUNCHER:
         addTime = 800;
         break;
     case WP_CHAINGUN:
         addTime = 30;
         break;
 #endif
     }
 #ifdef MISSIONPACK
     if( bg_itemlist[pm->ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_SCOUT ) {
         addTime /= 1.5;
     }
     else
     if( bg_itemlist[pm->ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_AMMOREGEN ) {
         addTime /= 1.3;
     }
     else
 #endif
     if ( pm->ps->powerups[PW_HASTE] ) {
         addTime /= 1.3;
     }
     pm->ps->weaponTime += addTime;
 }
Referenced by PmoveSingle().
Pmove()
void Pmove (pmove_t * pmove)
Definition at line 2025 of file bg_pmove.c.
{
     int         finalTime;
     finalTime = pmove->cmd.serverTime;
     if ( finalTime < pmove->ps->commandTime ) {
         return; // should not happen
     }
     if ( finalTime > pmove->ps->commandTime + 1000 ) {
         pmove->ps->commandTime = finalTime - 1000;
     }
     pmove->ps->pmove_framecount = (pmove->ps->pmove_framecount+1) & ((1<<PS_PMOVEFRAMECOUNTBITS)-1);
     // chop the move up if it is too long, to prevent framerate
     // dependent behavior
     while ( pmove->ps->commandTime != finalTime ) {
         int     msec;
         msec = finalTime - pmove->ps->commandTime;
         if ( pmove->pmove_fixed ) {
             if ( msec > pmove->pmove_msec ) {
                 msec = pmove->pmove_msec;
             }
         }
         else {
             if ( msec > 66 ) {
                 msec = 66;
             }
         }
         pmove->cmd.serverTime = pmove->ps->commandTime + msec;
         PmoveSingle( pmove );
         if ( pmove->ps->pm_flags & PMF_JUMP_HELD ) {
             pmove->cmd.upmove = 20;
         }
     }
     //PM_CheckStuck();
 }
Referenced by CG_PredictPlayerState(), ClientThink_real(), and SpectatorThink().
PmoveSingle()
void PmoveSingle (pmove_t * pmove)
Definition at line 1835 of file bg_pmove.c.
{
     pm = pmove;
     // this counter lets us debug movement problems with a journal
     // by setting a conditional breakpoint fot the previous frame
     c_pmove++;
     // clear results
     pm->numtouch = 0;
     pm->watertype = 0;
     pm->waterlevel = 0;
     if ( pm->ps->stats[STAT_HEALTH] <= 0 ) {
         pm->tracemask &= ~CONTENTS_BODY;    // corpses can fly through bodies
     }
     // make sure walking button is clear if they are running, to avoid
     // proxy no-footsteps cheats
     if ( abs( pm->cmd.forwardmove ) > 64 || abs( pm->cmd.rightmove ) > 64 ) {
         pm->cmd.buttons &= ~BUTTON_WALKING;
     }
     // set the talk balloon flag
     if ( pm->cmd.buttons & BUTTON_TALK ) {
         pm->ps->eFlags |= EF_TALK;
     } else {
         pm->ps->eFlags &= ~EF_TALK;
     }
     // set the firing flag for continuous beam weapons
     if ( !(pm->ps->pm_flags & PMF_RESPAWNED) && pm->ps->pm_type != PM_INTERMISSION && pm->ps->pm_type != PM_NOCLIP
         && ( pm->cmd.buttons & BUTTON_ATTACK ) && pm->ps->ammo[ pm->ps->weapon ] ) {
         pm->ps->eFlags |= EF_FIRING;
     } else {
         pm->ps->eFlags &= ~EF_FIRING;
     }
     // clear the respawned flag if attack and use are cleared
     if ( pm->ps->stats[STAT_HEALTH] > 0 &&
         !( pm->cmd.buttons & (BUTTON_ATTACK | BUTTON_USE_HOLDABLE) ) ) {
         pm->ps->pm_flags &= ~PMF_RESPAWNED;
     }
     // if talk button is down, dissallow all other input
     // this is to prevent any possible intercept proxy from
     // adding fake talk balloons
     if ( pmove->cmd.buttons & BUTTON_TALK ) {
         // keep the talk button set tho for when the cmd.serverTime > 66 msec
         // and the same cmd is used multiple times in Pmove
         pmove->cmd.buttons = BUTTON_TALK;
         pmove->cmd.forwardmove = 0;
         pmove->cmd.rightmove = 0;
         pmove->cmd.upmove = 0;
     }
     // clear all pmove local vars
     memset (&pml, 0, sizeof(pml));
     // determine the time
     pml.msec = pmove->cmd.serverTime - pm->ps->commandTime;
     if ( pml.msec < 1 ) {
         pml.msec = 1;
     } else if ( pml.msec > 200 ) {
         pml.msec = 200;
     }
     pm->ps->commandTime = pmove->cmd.serverTime;
     // save old org in case we get stuck
     VectorCopy (pm->ps->origin, pml.previous_origin);
     // save old velocity for crashlanding
     VectorCopy (pm->ps->velocity, pml.previous_velocity);
     pml.frametime = pml.msec * 0.001;
     // update the viewangles
     PM_UpdateViewAngles( pm->ps, &pm->cmd );
     AngleVectors (pm->ps->viewangles, pml.forward, pml.right, pml.up);
     if ( pm->cmd.upmove < 10 ) {
         // not holding jump
         pm->ps->pm_flags &= ~PMF_JUMP_HELD;
     }
     // decide if backpedaling animations should be used
     if ( pm->cmd.forwardmove < 0 ) {
         pm->ps->pm_flags |= PMF_BACKWARDS_RUN;
     } else if ( pm->cmd.forwardmove > 0 || ( pm->cmd.forwardmove == 0 && pm->cmd.rightmove ) ) {
         pm->ps->pm_flags &= ~PMF_BACKWARDS_RUN;
     }
     if ( pm->ps->pm_type >= PM_DEAD ) {
         pm->cmd.forwardmove = 0;
         pm->cmd.rightmove = 0;
         pm->cmd.upmove = 0;
     }
     if ( pm->ps->pm_type == PM_SPECTATOR ) {
         PM_CheckDuck ();
         PM_FlyMove ();
         PM_DropTimers ();
         return;
     }
     if ( pm->ps->pm_type == PM_NOCLIP ) {
         PM_NoclipMove ();
         PM_DropTimers ();
         return;
     }
     if (pm->ps->pm_type == PM_FREEZE) {
         return;     // no movement at all
     }
     if ( pm->ps->pm_type == PM_INTERMISSION || pm->ps->pm_type == PM_SPINTERMISSION) {
         return;     // no movement at all
     }
     // set watertype, and waterlevel
     PM_SetWaterLevel();
     pml.previous_waterlevel = pmove->waterlevel;
     // set mins, maxs, and viewheight
     PM_CheckDuck ();
     // set groundentity
     PM_GroundTrace();
     if ( pm->ps->pm_type == PM_DEAD ) {
         PM_DeadMove ();
     }
     PM_DropTimers();
 #ifdef MISSIONPACK
     if ( pm->ps->powerups[PW_INVULNERABILITY] ) {
         PM_InvulnerabilityMove();
     } else
 #endif
     if ( pm->ps->powerups[PW_FLIGHT] ) {
         // flight powerup doesn't allow jump and has different friction
         PM_FlyMove();
     } else if (pm->ps->pm_flags & PMF_GRAPPLE_PULL) {
         PM_GrappleMove();
         // We can wiggle a bit
         PM_AirMove();
     } else if (pm->ps->pm_flags & PMF_TIME_WATERJUMP) {
         PM_WaterJumpMove();
     } else if ( pm->waterlevel > 1 ) {
         // swimming
         PM_WaterMove();
     } else if ( pml.walking ) {
         // walking on ground
         PM_WalkMove();
     } else {
         // airborne
         PM_AirMove();
     }
     PM_Animate();
     // set groundentity, watertype, and waterlevel
     PM_GroundTrace();
     PM_SetWaterLevel();
     // weapons
     PM_Weapon();
     // torso animation
     PM_TorsoAnimation();
     // footstep events / legs animations
     PM_Footsteps();
     // entering / leaving water splashes
     PM_WaterEvents();
     // snap some parts of playerstate to save network bandwidth
     trap_SnapVector( pm->ps->velocity );
 }
Referenced by Pmove().
trap_SnapVector()
void trap_SnapVector (float * v)
Definition at line 395 of file cg_syscalls.c.
{
     syscall( CG_SNAPVECTOR, v );
 }
Referenced by PmoveSingle().
Variable Documentation
c_pmove
int c_pmove = 0
Definition at line 48 of file bg_pmove.c.
Referenced by PM_CorrectAllSolid(), PM_GroundTrace(), PM_GroundTraceMissed(), PM_StepSlideMove(), and PmoveSingle().
pm
pmove_t* pm
Definition at line 30 of file bg_pmove.c.
Referenced by ClientImpacts(), ClientThink_real(), PM_Accelerate(), PM_AddEvent(), PM_AddTouchEnt(), PM_AirMove(), PM_Animate(), PM_BeginWeaponChange(), PM_CheckDuck(), PM_CheckJump(), PM_CheckWaterJump(), PM_CmdScale(), PM_ContinueLegsAnim(), PM_ContinueTorsoAnim(), PM_CorrectAllSolid(), PM_CrashLand(), PM_DeadMove(), PM_DropTimers(), PM_FinishWeaponChange(), PM_FlyMove(), PM_Footsteps(), PM_ForceLegsAnim(), PM_Friction(), PM_GrappleMove(), PM_GroundTrace(), PM_GroundTraceMissed(), PM_NoclipMove(), PM_SetMovementDir(), PM_SetWaterLevel(), PM_SlideMove(), PM_StartLegsAnim(), PM_StartTorsoAnim(), PM_StepSlideMove(), PM_TorsoAnimation(), PM_WalkMove(), PM_WaterEvents(), PM_WaterJumpMove(), PM_WaterMove(), PM_Weapon(), PmoveSingle(), and SpectatorThink().
pm_accelerate
float pm_accelerate = 10.0f
Definition at line 38 of file bg_pmove.c.
Referenced by PM_NoclipMove(), and PM_WalkMove().
pm_airaccelerate
float pm_airaccelerate = 1.0f
Definition at line 39 of file bg_pmove.c.
Referenced by PM_AirMove(), and PM_WalkMove().
pm_duckScale
float pm_duckScale = 0.25f
Definition at line 35 of file bg_pmove.c.
Referenced by PM_WalkMove().
pm_flightfriction
float pm_flightfriction = 3.0f
Definition at line 45 of file bg_pmove.c.
Referenced by PM_Friction().
pm_flyaccelerate
float pm_flyaccelerate = 8.0f
Definition at line 41 of file bg_pmove.c.
Referenced by PM_FlyMove().
pm_friction
float pm_friction = 6.0f
Definition at line 43 of file bg_pmove.c.
Referenced by PM_Friction(), and PM_NoclipMove().
pm_spectatorfriction
float pm_spectatorfriction = 5.0f
Definition at line 46 of file bg_pmove.c.
Referenced by PM_Friction().
pm_stopspeed
float pm_stopspeed = 100.0f
Definition at line 34 of file bg_pmove.c.
Referenced by PM_Friction(), and PM_NoclipMove().
pm_swimScale
float pm_swimScale = 0.50f
Definition at line 36 of file bg_pmove.c.
Referenced by PM_WalkMove(), and PM_WaterMove().
pm_wateraccelerate
float pm_wateraccelerate = 4.0f
Definition at line 40 of file bg_pmove.c.
Referenced by PM_WaterMove().
pm_waterfriction
float pm_waterfriction = 1.0f
Definition at line 44 of file bg_pmove.c.
Referenced by PM_Friction().
pml
pml_t pml
Definition at line 31 of file bg_pmove.c.
Referenced by PM_Accelerate(), PM_AirMove(), PM_CheckJump(), PM_CheckWaterJump(), PM_CorrectAllSolid(), PM_CrashLand(), PM_DeadMove(), PM_DropTimers(), PM_FlyMove(), PM_FootstepForSurface(), PM_Footsteps(), PM_Friction(), PM_GrappleMove(), PM_GroundTrace(), PM_GroundTraceMissed(), PM_NoclipMove(), PM_SlideMove(), PM_WalkMove(), PM_WaterEvents(), PM_WaterJumpMove(), PM_WaterMove(), PM_Weapon(), and PmoveSingle().