ioquake3 doxygen: C:/entry/dev/ioq3/code/renderergl2/tr_sky.c File Reference
tr_sky.c File Reference
#include "tr_local.h"
Macros
#define SKY_SUBDIVISIONS 8
#define HALF_SKY_SUBDIVISIONS (SKY_SUBDIVISIONS/2)
#define ON_EPSILON 0.1f
#define MAX_CLIP_VERTS 64
#define SQR(a) ((a)*(a))
Functions
static void AddSkyPolygon (int nump, vec3_t vecs)
static void ClipSkyPolygon (int nump, vec3_t vecs, int stage)
static void ClearSkyBox (void)
void RB_ClipSkyPolygons (shaderCommands_t *input)
static void MakeSkyVec (float s, float t, int axis, float outSt[2], vec3_t outXYZ)
static void DrawSkySide (struct image_s *image, const int mins[2], const int maxs[2])
static void DrawSkyBox (shader_t *shader)
static void FillCloudySkySide (const int mins[2], const int maxs[2], qboolean addIndexes)
static void FillCloudBox (const shader_t *shader, int stage)
void R_BuildCloudData (shaderCommands_t *input)
void R_InitSkyTexCoords (float heightCloud)
void RB_DrawSun (float scale, shader_t *shader)
void RB_StageIteratorSky (void)
Variables
static float s_cloudTexCoords [6][SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1][2]
static float s_cloudTexP [6][SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1]
static vec3_t sky_clip [6]
static float sky_mins [2][6]
static float sky_maxs [2][6]
static float sky_min
static float sky_max
static int sky_texorder [6] = {0,2,1,3,4,5}
static vec3_t s_skyPoints [SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1]
static float s_skyTexCoords [SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1][2]
Macro Definition Documentation
HALF_SKY_SUBDIVISIONS
#define HALF_SKY_SUBDIVISIONS (SKY_SUBDIVISIONS/2)
Definition at line 26 of file tr_sky.c.
MAX_CLIP_VERTS
#define MAX_CLIP_VERTS 64
Definition at line 144 of file tr_sky.c.
ON_EPSILON
#define ON_EPSILON 0.1f
Definition at line 143 of file tr_sky.c.
SKY_SUBDIVISIONS
#define SKY_SUBDIVISIONS 8
Definition at line 25 of file tr_sky.c.
SQR
#define SQR (a) ((a)*(a))
Definition at line 728 of file tr_sky.c.
Function Documentation
AddSkyPolygon()
static void AddSkyPolygon (int nump, vec3_t vecs) static
Definition at line 57 of file tr_sky.c.
 {
     int     i,j;
     vec3_t  v, av;
     float   s, t, dv;
     int     axis;
     float   *vp;
     // s = [0]/[2], t = [1]/[2]
     static int  vec_to_st[6][3] =
     {
         {-2,3,1},
         {2,3,-1},
         {1,3,2},
         {-1,3,-2},
         {-2,-1,3},
         {-2,1,-3}
     //  {-1,2,3},
     //  {1,2,-3}
     };
     // decide which face it maps to
     VectorCopy (vec3_origin, v);
     for (i=0, vp=vecs ; i<nump ; i++, vp+=3)
     {
         VectorAdd (vp, v, v);
     }
     av[0] = fabs(v[0]);
     av[1] = fabs(v[1]);
     av[2] = fabs(v[2]);
     if (av[0] > av[1] && av[0] > av[2])
     {
         if (v[0] < 0)
             axis = 1;
         else
             axis = 0;
     }
     else if (av[1] > av[2] && av[1] > av[0])
     {
         if (v[1] < 0)
             axis = 3;
         else
             axis = 2;
     }
     else
     {
         if (v[2] < 0)
             axis = 5;
         else
             axis = 4;
     }
     // project new texture coords
     for (i=0 ; i<nump ; i++, vecs+=3)
     {
         j = vec_to_st[axis][2];
         if (j > 0)
             dv = vecs[j - 1];
         else
             dv = -vecs[-j - 1];
         if (dv < 0.001)
             continue;   // don't divide by zero
         j = vec_to_st[axis][0];
         if (j < 0)
             s = -vecs[-j -1] / dv;
         else
             s = vecs[j-1] / dv;
         j = vec_to_st[axis][1];
         if (j < 0)
             t = -vecs[-j -1] / dv;
         else
             t = vecs[j-1] / dv;
         if (s < sky_mins[0][axis])
             sky_mins[0][axis] = s;
         if (t < sky_mins[1][axis])
             sky_mins[1][axis] = t;
         if (s > sky_maxs[0][axis])
             sky_maxs[0][axis] = s;
         if (t > sky_maxs[1][axis])
             sky_maxs[1][axis] = t;
     }
 }
References s, sky_maxs, sky_mins, t, vec3_origin, VectorAdd, and VectorCopy.
Referenced by ClipSkyPolygon().
ClearSkyBox()
static void ClearSkyBox (void) static
Definition at line 246 of file tr_sky.c.
{
     int     i;
     for (i=0 ; i<6 ; i++) {
         sky_mins[0][i] = sky_mins[1][i] = 9999;
         sky_maxs[0][i] = sky_maxs[1][i] = -9999;
     }
 }
References sky_maxs, and sky_mins.
Referenced by RB_ClipSkyPolygons().
ClipSkyPolygon()
static void ClipSkyPolygon (int nump, vec3_t vecs, int stage) static
Definition at line 150 of file tr_sky.c.
 {
     float   *norm;
     float   *v;
     qboolean    front, back;
     float   d, e;
     float   dists[MAX_CLIP_VERTS];
     int     sides[MAX_CLIP_VERTS];
     vec3_t  newv[2][MAX_CLIP_VERTS];
     int     newc[2];
     int     i, j;
     if (nump > MAX_CLIP_VERTS-2)
         ri.Error (ERR_DROP, "ClipSkyPolygon: MAX_CLIP_VERTS");
     if (stage == 6)
     {   // fully clipped, so draw it
         AddSkyPolygon (nump, vecs);
         return;
     }
     front = back = qfalse;
     norm = sky_clip[stage];
     for (i=0, v = vecs ; i<nump ; i++, v+=3)
     {
         d = DotProduct (v, norm);
         if (d > ON_EPSILON)
         {
             front = qtrue;
             sides[i] = SIDE_FRONT;
         }
         else if (d < -ON_EPSILON)
         {
             back = qtrue;
             sides[i] = SIDE_BACK;
         }
         else
             sides[i] = SIDE_ON;
         dists[i] = d;
     }
     if (!front || !back)
     {   // not clipped
         ClipSkyPolygon (nump, vecs, stage+1);
         return;
     }
     // clip it
     sides[i] = sides[0];
     dists[i] = dists[0];
     VectorCopy (vecs, (vecs+(i*3)) );
     newc[0] = newc[1] = 0;
     for (i=0, v = vecs ; i<nump ; i++, v+=3)
     {
         switch (sides[i])
         {
         case SIDE_FRONT:
             VectorCopy (v, newv[0][newc[0]]);
             newc[0]++;
             break;
         case SIDE_BACK:
             VectorCopy (v, newv[1][newc[1]]);
             newc[1]++;
             break;
         case SIDE_ON:
             VectorCopy (v, newv[0][newc[0]]);
             newc[0]++;
             VectorCopy (v, newv[1][newc[1]]);
             newc[1]++;
             break;
         }
         if (sides[i] == SIDE_ON || sides[i+1] == SIDE_ON || sides[i+1] == sides[i])
             continue;
         d = dists[i] / (dists[i] - dists[i+1]);
         for (j=0 ; j<3 ; j++)
         {
             e = v[j] + d*(v[j+3] - v[j]);
             newv[0][newc[0]][j] = e;
             newv[1][newc[1]][j] = e;
         }
         newc[0]++;
         newc[1]++;
     }
     // continue
     ClipSkyPolygon (newc[0], newv[0][0], stage+1);
     ClipSkyPolygon (newc[1], newv[1][0], stage+1);
 }
References AddSkyPolygon(), DotProduct, ERR_DROP, MAX_CLIP_VERTS, ON_EPSILON, qfalse, qtrue, ri, SIDE_BACK, SIDE_FRONT, SIDE_ON, sky_clip, and VectorCopy.
Referenced by RB_ClipSkyPolygons().
DrawSkyBox()
static void DrawSkyBox (shader_t * shader) static
Definition at line 477 of file tr_sky.c.
 {
     int     i;
     sky_min = 0;
     sky_max = 1;
     Com_Memset( s_skyTexCoords, 0, sizeof( s_skyTexCoords ) );
     for (i=0 ; i<6 ; i++)
     {
         int sky_mins_subd[2], sky_maxs_subd[2];
         int s, t;
         sky_mins[0][i] = floor( sky_mins[0][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         sky_mins[1][i] = floor( sky_mins[1][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         sky_maxs[0][i] = ceil( sky_maxs[0][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         sky_maxs[1][i] = ceil( sky_maxs[1][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         if ( ( sky_mins[0][i] >= sky_maxs[0][i] ) ||
              ( sky_mins[1][i] >= sky_maxs[1][i] ) )
         {
             continue;
         }
         sky_mins_subd[0] = sky_mins[0][i] * HALF_SKY_SUBDIVISIONS;
         sky_mins_subd[1] = sky_mins[1][i] * HALF_SKY_SUBDIVISIONS;
         sky_maxs_subd[0] = sky_maxs[0][i] * HALF_SKY_SUBDIVISIONS;
         sky_maxs_subd[1] = sky_maxs[1][i] * HALF_SKY_SUBDIVISIONS;
         if ( sky_mins_subd[0] < -HALF_SKY_SUBDIVISIONS )
             sky_mins_subd[0] = -HALF_SKY_SUBDIVISIONS;
         else if ( sky_mins_subd[0] > HALF_SKY_SUBDIVISIONS )
             sky_mins_subd[0] = HALF_SKY_SUBDIVISIONS;
         if ( sky_mins_subd[1] < -HALF_SKY_SUBDIVISIONS )
             sky_mins_subd[1] = -HALF_SKY_SUBDIVISIONS;
         else if ( sky_mins_subd[1] > HALF_SKY_SUBDIVISIONS )
             sky_mins_subd[1] = HALF_SKY_SUBDIVISIONS;
         if ( sky_maxs_subd[0] < -HALF_SKY_SUBDIVISIONS )
             sky_maxs_subd[0] = -HALF_SKY_SUBDIVISIONS;
         else if ( sky_maxs_subd[0] > HALF_SKY_SUBDIVISIONS )
             sky_maxs_subd[0] = HALF_SKY_SUBDIVISIONS;
         if ( sky_maxs_subd[1] < -HALF_SKY_SUBDIVISIONS )
             sky_maxs_subd[1] = -HALF_SKY_SUBDIVISIONS;
         else if ( sky_maxs_subd[1] > HALF_SKY_SUBDIVISIONS )
             sky_maxs_subd[1] = HALF_SKY_SUBDIVISIONS;
         //
         // iterate through the subdivisions
         //
         for ( t = sky_mins_subd[1]+HALF_SKY_SUBDIVISIONS; t <= sky_maxs_subd[1]+HALF_SKY_SUBDIVISIONS; t++ )
         {
             for ( s = sky_mins_subd[0]+HALF_SKY_SUBDIVISIONS; s <= sky_maxs_subd[0]+HALF_SKY_SUBDIVISIONS; s++ )
             {
                 MakeSkyVec( ( s - HALF_SKY_SUBDIVISIONS ) / ( float ) HALF_SKY_SUBDIVISIONS,
                             ( t - HALF_SKY_SUBDIVISIONS ) / ( float ) HALF_SKY_SUBDIVISIONS,
                             i,
                             s_skyTexCoords[t][s],
                             s_skyPoints[t][s] );
             }
         }
         DrawSkySide( shader->sky.outerbox[sky_texorder[i]],
                      sky_mins_subd,
                      sky_maxs_subd );
     }
 }
References Com_Memset, DrawSkySide(), HALF_SKY_SUBDIVISIONS, MakeSkyVec(), skyParms_t::outerbox, s, s_skyPoints, s_skyTexCoords, shader, shader_s::sky, sky_max, sky_maxs, sky_min, sky_mins, sky_texorder, and t.
Referenced by RB_StageIteratorSky().
DrawSkySide()
static void DrawSkySide (struct image_s * image, const int mins[2], const int maxs[2]) static
Definition at line 364 of file tr_sky.c.
 {
     int s, t;
     int firstVertex = tess.numVertexes;
     //int firstIndex = tess.numIndexes;
     vec4_t color;
     //tess.numVertexes = 0;
     //tess.numIndexes = 0;
     tess.firstIndex = tess.numIndexes;
     GL_BindToTMU( image, TB_COLORMAP );
     GL_Cull( CT_TWO_SIDED );
     for ( t = mins[1]+HALF_SKY_SUBDIVISIONS; t <= maxs[1]+HALF_SKY_SUBDIVISIONS; t++ )
     {
         for ( s = mins[0]+HALF_SKY_SUBDIVISIONS; s <= maxs[0]+HALF_SKY_SUBDIVISIONS; s++ )
         {
             tess.xyz[tess.numVertexes][0] = s_skyPoints[t][s][0];
             tess.xyz[tess.numVertexes][1] = s_skyPoints[t][s][1];
             tess.xyz[tess.numVertexes][2] = s_skyPoints[t][s][2];
             tess.xyz[tess.numVertexes][3] = 1.0;
             tess.texCoords[tess.numVertexes][0] = s_skyTexCoords[t][s][0];
             tess.texCoords[tess.numVertexes][1] = s_skyTexCoords[t][s][1];
             tess.numVertexes++;
             if(tess.numVertexes >= SHADER_MAX_VERTEXES)
             {
                 ri.Error(ERR_DROP, "SHADER_MAX_VERTEXES hit in DrawSkySideVBO()");
             }
         }
     }
     for ( t = 0; t < maxs[1] - mins[1]; t++ )
     {
         for ( s = 0; s < maxs[0] - mins[0]; s++ )
         {
             if (tess.numIndexes + 6 >= SHADER_MAX_INDEXES)
             {
                 ri.Error(ERR_DROP, "SHADER_MAX_INDEXES hit in DrawSkySideVBO()");
             }
             tess.indexes[tess.numIndexes++] =  s +       t      * (maxs[0] - mins[0] + 1) + firstVertex;
             tess.indexes[tess.numIndexes++] =  s +      (t + 1) * (maxs[0] - mins[0] + 1) + firstVertex;
             tess.indexes[tess.numIndexes++] = (s + 1) +  t      * (maxs[0] - mins[0] + 1) + firstVertex;
             tess.indexes[tess.numIndexes++] = (s + 1) +  t      * (maxs[0] - mins[0] + 1) + firstVertex;
             tess.indexes[tess.numIndexes++] =  s +      (t + 1) * (maxs[0] - mins[0] + 1) + firstVertex;
             tess.indexes[tess.numIndexes++] = (s + 1) + (t + 1) * (maxs[0] - mins[0] + 1) + firstVertex;
         }
     }
     // FIXME: A lot of this can probably be removed for speed, and refactored into a more convenient function
     RB_UpdateTessVao(ATTR_POSITION | ATTR_TEXCOORD);
 /*
     {
         shaderProgram_t *sp = &tr.textureColorShader;
         GLSL_VertexAttribsState(ATTR_POSITION | ATTR_TEXCOORD);
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         color[0] =
         color[1] =
         color[2] = tr.identityLight;
         color[3] = 1.0f;
         GLSL_SetUniformVec4(sp, UNIFORM_COLOR, color);
     }
 */
     {
         shaderProgram_t *sp = &tr.lightallShader[0];
         vec4_t vector;
         GLSL_BindProgram(sp);
         GLSL_SetUniformMat4(sp, UNIFORM_MODELVIEWPROJECTIONMATRIX, glState.modelviewProjection);
         color[0] =
         color[1] =
         color[2] =
         color[3] = 1.0f;
         GLSL_SetUniformVec4(sp, UNIFORM_BASECOLOR, color);
         color[0] =
         color[1] =
         color[2] =
         color[3] = 0.0f;
         GLSL_SetUniformVec4(sp, UNIFORM_VERTCOLOR, color);
         VectorSet4(vector, 1.0, 0.0, 0.0, 1.0);
         GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXMATRIX, vector);
         VectorSet4(vector, 0.0, 0.0, 0.0, 0.0);
         GLSL_SetUniformVec4(sp, UNIFORM_DIFFUSETEXOFFTURB, vector);
         GLSL_SetUniformInt(sp, UNIFORM_ALPHATEST, 0);
     }
     R_DrawElements(tess.numIndexes - tess.firstIndex, tess.firstIndex);
     //qglDrawElements(GL_TRIANGLES, tess.numIndexes - tess.firstIndex, GL_INDEX_TYPE, BUFFER_OFFSET(tess.firstIndex * sizeof(glIndex_t)));
     //R_BindNullVBO();
     //R_BindNullIBO();
     tess.numIndexes = tess.firstIndex;
     tess.numVertexes = firstVertex;
     tess.firstIndex = 0;
 }
References ATTR_POSITION, ATTR_TEXCOORD, CT_TWO_SIDED, ERR_DROP, shaderCommands_s::firstIndex, GL_BindToTMU(), GL_Cull(), GLSL_BindProgram(), GLSL_SetUniformInt(), GLSL_SetUniformMat4(), GLSL_SetUniformVec4(), glState, HALF_SKY_SUBDIVISIONS, trGlobals_t::lightallShader, glstate_t::modelviewProjection, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, R_DrawElements(), RB_UpdateTessVao(), ri, s, s_skyPoints, s_skyTexCoords, SHADER_MAX_INDEXES, SHADER_MAX_VERTEXES, t, TB_COLORMAP, tess, tr, UNIFORM_ALPHATEST, UNIFORM_BASECOLOR, UNIFORM_DIFFUSETEXMATRIX, UNIFORM_DIFFUSETEXOFFTURB, UNIFORM_MODELVIEWPROJECTIONMATRIX, UNIFORM_VERTCOLOR, and VectorSet4.
Referenced by DrawSkyBox().
FillCloudBox()
static void FillCloudBox (const shader_t * shader, int stage) static
Definition at line 597 of file tr_sky.c.
 {
     int i;
     for ( i =0; i < 6; i++ )
     {
         int sky_mins_subd[2], sky_maxs_subd[2];
         int s, t;
         float MIN_T;
         if ( 1 ) // FIXME? shader->sky.fullClouds )
         {
             MIN_T = -HALF_SKY_SUBDIVISIONS;
             // still don't want to draw the bottom, even if fullClouds
             if ( i == 5 )
                 continue;
         }
         else
         {
             switch( i )
             {
             case 0:
             case 1:
             case 2:
             case 3:
                 MIN_T = -1;
                 break;
             case 5:
                 // don't draw clouds beneath you
                 continue;
             case 4:     // top
             default:
                 MIN_T = -HALF_SKY_SUBDIVISIONS;
                 break;
             }
         }
         sky_mins[0][i] = floor( sky_mins[0][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         sky_mins[1][i] = floor( sky_mins[1][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         sky_maxs[0][i] = ceil( sky_maxs[0][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         sky_maxs[1][i] = ceil( sky_maxs[1][i] * HALF_SKY_SUBDIVISIONS ) / HALF_SKY_SUBDIVISIONS;
         if ( ( sky_mins[0][i] >= sky_maxs[0][i] ) ||
              ( sky_mins[1][i] >= sky_maxs[1][i] ) )
         {
             continue;
         }
         sky_mins_subd[0] = ri.ftol(sky_mins[0][i] * HALF_SKY_SUBDIVISIONS);
         sky_mins_subd[1] = ri.ftol(sky_mins[1][i] * HALF_SKY_SUBDIVISIONS);
         sky_maxs_subd[0] = ri.ftol(sky_maxs[0][i] * HALF_SKY_SUBDIVISIONS);
         sky_maxs_subd[1] = ri.ftol(sky_maxs[1][i] * HALF_SKY_SUBDIVISIONS);
         if ( sky_mins_subd[0] < -HALF_SKY_SUBDIVISIONS )
             sky_mins_subd[0] = -HALF_SKY_SUBDIVISIONS;
         else if ( sky_mins_subd[0] > HALF_SKY_SUBDIVISIONS )
             sky_mins_subd[0] = HALF_SKY_SUBDIVISIONS;
         if ( sky_mins_subd[1] < MIN_T )
             sky_mins_subd[1] = MIN_T;
         else if ( sky_mins_subd[1] > HALF_SKY_SUBDIVISIONS )
             sky_mins_subd[1] = HALF_SKY_SUBDIVISIONS;
         if ( sky_maxs_subd[0] < -HALF_SKY_SUBDIVISIONS )
             sky_maxs_subd[0] = -HALF_SKY_SUBDIVISIONS;
         else if ( sky_maxs_subd[0] > HALF_SKY_SUBDIVISIONS )
             sky_maxs_subd[0] = HALF_SKY_SUBDIVISIONS;
         if ( sky_maxs_subd[1] < MIN_T )
             sky_maxs_subd[1] = MIN_T;
         else if ( sky_maxs_subd[1] > HALF_SKY_SUBDIVISIONS )
             sky_maxs_subd[1] = HALF_SKY_SUBDIVISIONS;
         //
         // iterate through the subdivisions
         //
         for ( t = sky_mins_subd[1]+HALF_SKY_SUBDIVISIONS; t <= sky_maxs_subd[1]+HALF_SKY_SUBDIVISIONS; t++ )
         {
             for ( s = sky_mins_subd[0]+HALF_SKY_SUBDIVISIONS; s <= sky_maxs_subd[0]+HALF_SKY_SUBDIVISIONS; s++ )
             {
                 MakeSkyVec( ( s - HALF_SKY_SUBDIVISIONS ) / ( float ) HALF_SKY_SUBDIVISIONS,
                             ( t - HALF_SKY_SUBDIVISIONS ) / ( float ) HALF_SKY_SUBDIVISIONS,
                             i,
                             NULL,
                             s_skyPoints[t][s] );
                 s_skyTexCoords[t][s][0] = s_cloudTexCoords[i][t][s][0];
                 s_skyTexCoords[t][s][1] = s_cloudTexCoords[i][t][s][1];
             }
         }
         // only add indexes for first stage
         FillCloudySkySide( sky_mins_subd, sky_maxs_subd, ( stage == 0 ) );
     }
 }
References FillCloudySkySide(), refimport_t::ftol, HALF_SKY_SUBDIVISIONS, MakeSkyVec(), NULL, ri, s, s_cloudTexCoords, s_skyPoints, s_skyTexCoords, sky_maxs, sky_mins, and t.
Referenced by R_BuildCloudData().
FillCloudySkySide()
static void FillCloudySkySide (const int mins[2], const int maxs[2], qboolean addIndexes) static
Definition at line 547 of file tr_sky.c.
 {
     int s, t;
     int vertexStart = tess.numVertexes;
     int tHeight, sWidth;
     tHeight = maxs[1] - mins[1] + 1;
     sWidth = maxs[0] - mins[0] + 1;
     for ( t = mins[1]+HALF_SKY_SUBDIVISIONS; t <= maxs[1]+HALF_SKY_SUBDIVISIONS; t++ )
     {
         for ( s = mins[0]+HALF_SKY_SUBDIVISIONS; s <= maxs[0]+HALF_SKY_SUBDIVISIONS; s++ )
         {
             VectorAdd( s_skyPoints[t][s], backEnd.viewParms.or.origin, tess.xyz[tess.numVertexes] );
             tess.texCoords[tess.numVertexes][0] = s_skyTexCoords[t][s][0];
             tess.texCoords[tess.numVertexes][1] = s_skyTexCoords[t][s][1];
             tess.numVertexes++;
             if ( tess.numVertexes >= SHADER_MAX_VERTEXES )
             {
                 ri.Error( ERR_DROP, "SHADER_MAX_VERTEXES hit in FillCloudySkySide()" );
             }
         }
     }
     // only add indexes for one pass, otherwise it would draw multiple times for each pass
     if ( addIndexes ) {
         for ( t = 0; t < tHeight-1; t++ )
         {
             for ( s = 0; s < sWidth-1; s++ )
             {
                 tess.indexes[tess.numIndexes] = vertexStart + s + t * ( sWidth );
                 tess.numIndexes++;
                 tess.indexes[tess.numIndexes] = vertexStart + s + ( t + 1 ) * ( sWidth );
                 tess.numIndexes++;
                 tess.indexes[tess.numIndexes] = vertexStart + s + 1 + t * ( sWidth );
                 tess.numIndexes++;
                 tess.indexes[tess.numIndexes] = vertexStart + s + ( t + 1 ) * ( sWidth );
                 tess.numIndexes++;
                 tess.indexes[tess.numIndexes] = vertexStart + s + 1 + ( t + 1 ) * ( sWidth );
                 tess.numIndexes++;
                 tess.indexes[tess.numIndexes] = vertexStart + s + 1 + t * ( sWidth );
                 tess.numIndexes++;
             }
         }
     }
 }
References backEnd, ERR_DROP, HALF_SKY_SUBDIVISIONS, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, viewParms_t::or, orientationr_t::origin, ri, s, s_skyPoints, s_skyTexCoords, SHADER_MAX_VERTEXES, t, tess, VectorAdd, and backEndState_t::viewParms.
Referenced by FillCloudBox().
MakeSkyVec()
static void MakeSkyVec (float s, float t, int axis, float outSt[2], vec3_t outXYZ) static
Definition at line 292 of file tr_sky.c.
 {
     // 1 = s, 2 = t, 3 = 2048
     static int  st_to_vec[6][3] =
     {
         {3,-1,2},
         {-3,1,2},
         {1,3,2},
         {-1,-3,2},
         {-2,-1,3},      // 0 degrees yaw, look straight up
         {2,-1,-3}       // look straight down
     };
     vec3_t      b;
     int         j, k;
     float   boxSize;
     boxSize = backEnd.viewParms.zFar / 1.75;        // div sqrt(3)
     b[0] = s*boxSize;
     b[1] = t*boxSize;
     b[2] = boxSize;
     for (j=0 ; j<3 ; j++)
     {
         k = st_to_vec[axis][j];
         if (k < 0)
         {
             outXYZ[j] = -b[-k - 1];
         }
         else
         {
             outXYZ[j] = b[k - 1];
         }
     }
     // avoid bilerp seam
     s = (s+1)*0.5;
     t = (t+1)*0.5;
     if (s < sky_min)
     {
         s = sky_min;
     }
     else if (s > sky_max)
     {
         s = sky_max;
     }
     if (t < sky_min)
     {
         t = sky_min;
     }
     else if (t > sky_max)
     {
         t = sky_max;
     }
     t = 1.0 - t;
     if ( outSt )
     {
         outSt[0] = s;
         outSt[1] = t;
     }
 }
References backEnd, s, sky_max, sky_min, t, backEndState_t::viewParms, and viewParms_t::zFar.
Referenced by DrawSkyBox(), FillCloudBox(), and R_InitSkyTexCoords().
R_BuildCloudData()
void R_BuildCloudData (shaderCommands_t * input)
Definition at line 695 of file tr_sky.c.
 {
     int         i;
     shader_t    *shader;
     shader = input->shader;
     assert( shader->isSky );
     sky_min = 1.0 / 256.0f;     // FIXME: not correct?
     sky_max = 255.0 / 256.0f;
     // set up for drawing
     tess.numIndexes = 0;
     tess.numVertexes = 0;
     tess.firstIndex = 0;
     if ( shader->sky.cloudHeight )
     {
         for ( i = 0; i < MAX_SHADER_STAGES; i++ )
         {
             if ( !tess.xstages[i] ) {
                 break;
             }
             FillCloudBox( shader, i );
         }
     }
 }
References skyParms_t::cloudHeight, FillCloudBox(), shaderCommands_s::firstIndex, shader_s::isSky, MAX_SHADER_STAGES, shaderCommands_s::numIndexes, shaderCommands_s::numVertexes, shader, shaderCommands_s::shader, shader_s::sky, sky_max, sky_min, tess, and shaderCommands_s::xstages.
Referenced by RB_StageIteratorSky().
R_InitSkyTexCoords()
void R_InitSkyTexCoords (float heightCloud)
Definition at line 729 of file tr_sky.c.
 {
     int i, s, t;
     float radiusWorld = 4096;
     float p;
     float sRad, tRad;
     vec3_t skyVec;
     vec3_t v;
     // init zfar so MakeSkyVec works even though
     // a world hasn't been bounded
     backEnd.viewParms.zFar = 1024;
     for ( i = 0; i < 6; i++ )
     {
         for ( t = 0; t <= SKY_SUBDIVISIONS; t++ )
         {
             for ( s = 0; s <= SKY_SUBDIVISIONS; s++ )
             {
                 // compute vector from view origin to sky side integral point
                 MakeSkyVec( ( s - HALF_SKY_SUBDIVISIONS ) / ( float ) HALF_SKY_SUBDIVISIONS,
                             ( t - HALF_SKY_SUBDIVISIONS ) / ( float ) HALF_SKY_SUBDIVISIONS,
                             i,
                             NULL,
                             skyVec );
                 // compute parametric value 'p' that intersects with cloud layer
                 p = ( 1.0f / ( 2 * DotProduct( skyVec, skyVec ) ) ) *
                     ( -2 * skyVec[2] * radiusWorld +
                        2 * sqrt( SQR( skyVec[2] ) * SQR( radiusWorld ) +
                                  2 * SQR( skyVec[0] ) * radiusWorld * heightCloud +
                                  SQR( skyVec[0] ) * SQR( heightCloud ) +
                                  2 * SQR( skyVec[1] ) * radiusWorld * heightCloud +
                                  SQR( skyVec[1] ) * SQR( heightCloud ) +
                                  2 * SQR( skyVec[2] ) * radiusWorld * heightCloud +
                                  SQR( skyVec[2] ) * SQR( heightCloud ) ) );
                 s_cloudTexP[i][t][s] = p;
                 // compute intersection point based on p
                 VectorScale( skyVec, p, v );
                 v[2] += radiusWorld;
                 // compute vector from world origin to intersection point 'v'
                 VectorNormalize( v );
                 sRad = Q_acos( v[0] );
                 tRad = Q_acos( v[1] );
                 s_cloudTexCoords[i][t][s][0] = sRad;
                 s_cloudTexCoords[i][t][s][1] = tRad;
             }
         }
     }
 }
References backEnd, DotProduct, HALF_SKY_SUBDIVISIONS, MakeSkyVec(), NULL, Q_acos(), s, s_cloudTexCoords, s_cloudTexP, SKY_SUBDIVISIONS, SQR, t, VectorNormalize(), VectorScale, backEndState_t::viewParms, and viewParms_t::zFar.
Referenced by ParseSkyParms().
RB_ClipSkyPolygons()
void RB_ClipSkyPolygons (shaderCommands_t * input)
Definition at line 260 of file tr_sky.c.
 {
     vec3_t      p[5];   // need one extra point for clipping
     int         i, j;
     ClearSkyBox();
     for ( i = 0; i < input->numIndexes; i += 3 )
     {
         for (j = 0 ; j < 3 ; j++)
         {
             VectorSubtract( input->xyz[input->indexes[i+j]],
                             backEnd.viewParms.or.origin,
                             p[j] );
         }
         ClipSkyPolygon( 3, p[0], 0 );
     }
 }
References backEnd, ClearSkyBox(), ClipSkyPolygon(), shaderCommands_s::numIndexes, viewParms_t::or, orientationr_t::origin, VectorSubtract, and backEndState_t::viewParms.
Referenced by RB_StageIteratorSky().
RB_DrawSun()
void RB_DrawSun (float scale, shader_t * shader)
Definition at line 790 of file tr_sky.c.
{
     float       size;
     float       dist;
     vec3_t      origin, vec1, vec2;
     if ( !backEnd.skyRenderedThisView ) {
         return;
     }
     //qglLoadMatrixf( backEnd.viewParms.world.modelMatrix );
     //qglTranslatef (backEnd.viewParms.or.origin[0], backEnd.viewParms.or.origin[1], backEnd.viewParms.or.origin[2]);
     {
         // FIXME: this could be a lot cleaner
         mat4_t translation, modelview;
         Mat4Translation( backEnd.viewParms.or.origin, translation );
         Mat4Multiply( backEnd.viewParms.world.modelMatrix, translation, modelview );
         GL_SetModelviewMatrix( modelview );
     }
     dist =  backEnd.viewParms.zFar / 1.75;      // div sqrt(3)
     size = dist * scale;
     VectorScale( tr.sunDirection, dist, origin );
     PerpendicularVector( vec1, tr.sunDirection );
     CrossProduct( tr.sunDirection, vec1, vec2 );
     VectorScale( vec1, size, vec1 );
     VectorScale( vec2, size, vec2 );
     // farthest depth range
     qglDepthRange( 1.0, 1.0 );
     RB_BeginSurface( shader, 0, 0 );
     RB_AddQuadStamp(origin, vec1, vec2, colorWhite);
     RB_EndSurface();
     // back to normal depth range
     qglDepthRange( 0.0, 1.0 );
 }
References backEnd, colorWhite, CrossProduct(), GL_SetModelviewMatrix(), Mat4Multiply(), Mat4Translation(), orientationr_t::modelMatrix, viewParms_t::or, orientationr_t::origin, PerpendicularVector(), RB_AddQuadStamp(), RB_BeginSurface(), RB_EndSurface(), shader, backEndState_t::skyRenderedThisView, trGlobals_t::sunDirection, tr, VectorScale, backEndState_t::viewParms, viewParms_t::world, and viewParms_t::zFar.
Referenced by RB_DrawSurfs().
RB_StageIteratorSky()
void RB_StageIteratorSky (void)
Definition at line 845 of file tr_sky.c.
{
     if ( r_fastsky->integer ) {
         return;
     }
     // go through all the polygons and project them onto
     // the sky box to see which blocks on each side need
     // to be drawn
     RB_ClipSkyPolygons( &tess );
     // r_showsky will let all the sky blocks be drawn in
     // front of everything to allow developers to see how
     // much sky is getting sucked in
     if ( r_showsky->integer ) {
         qglDepthRange( 0.0, 0.0 );
     } else {
         qglDepthRange( 1.0, 1.0 );
     }
     // draw the outer skybox
     if ( tess.shader->sky.outerbox[0] && tess.shader->sky.outerbox[0] != tr.defaultImage ) {
         mat4_t oldmodelview;
         GL_State( 0 );
         GL_Cull( CT_FRONT_SIDED );
         //qglTranslatef (backEnd.viewParms.or.origin[0], backEnd.viewParms.or.origin[1], backEnd.viewParms.or.origin[2]);
         {
             // FIXME: this could be a lot cleaner
             mat4_t trans, product;
             Mat4Copy( glState.modelview, oldmodelview );
             Mat4Translation( backEnd.viewParms.or.origin, trans );
             Mat4Multiply( glState.modelview, trans, product );
             GL_SetModelviewMatrix( product );
         }
         DrawSkyBox( tess.shader );
         GL_SetModelviewMatrix( oldmodelview );
     }
     // generate the vertexes for all the clouds, which will be drawn
     // by the generic shader routine
     R_BuildCloudData( &tess );
     RB_StageIteratorGeneric();
     // draw the inner skybox
     // back to normal depth range
     qglDepthRange( 0.0, 1.0 );
     // note that sky was drawn so we will draw a sun later
     backEnd.skyRenderedThisView = qtrue;
 }
References backEnd, CT_FRONT_SIDED, trGlobals_t::defaultImage, DrawSkyBox(), GL_Cull(), GL_SetModelviewMatrix(), GL_State(), glState, cvar_s::integer, Mat4Copy(), Mat4Multiply(), Mat4Translation(), glstate_t::modelview, viewParms_t::or, orientationr_t::origin, skyParms_t::outerbox, qtrue, R_BuildCloudData(), r_fastsky, r_showsky, RB_ClipSkyPolygons(), RB_StageIteratorGeneric(), shaderCommands_s::shader, shader_s::sky, backEndState_t::skyRenderedThisView, tess, tr, and backEndState_t::viewParms.
Referenced by ComputeStageIteratorFunc(), and R_ShaderList_f().
Variable Documentation
s_cloudTexCoords
float s_cloudTexCoords[6][SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1][2] static
Definition at line 28 of file tr_sky.c.
Referenced by FillCloudBox(), and R_InitSkyTexCoords().
s_cloudTexP
float s_cloudTexP[6][SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1] static
Definition at line 29 of file tr_sky.c.
Referenced by R_InitSkyTexCoords().
s_skyPoints
vec3_t s_skyPoints[SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1] static
Definition at line 361 of file tr_sky.c.
Referenced by DrawSkyBox(), DrawSkySide(), FillCloudBox(), and FillCloudySkySide().
s_skyTexCoords
float s_skyTexCoords[SKY_SUBDIVISIONS+1][SKY_SUBDIVISIONS+1][2] static
Definition at line 362 of file tr_sky.c.
Referenced by DrawSkyBox(), DrawSkySide(), FillCloudBox(), and FillCloudySkySide().
sky_clip
vec3_t sky_clip[6] static
Initial value:
=
{
    {1,1,0},
    {1,-1,0},
    {0,-1,1},
    {0,1,1},
    {1,0,1},
    {-1,0,1}
}
Definition at line 39 of file tr_sky.c.
Referenced by ClipSkyPolygon().
sky_max
float sky_max static
Definition at line 50 of file tr_sky.c.
Referenced by DrawSkyBox(), MakeSkyVec(), and R_BuildCloudData().
sky_maxs
float sky_maxs[2][6] static
Definition at line 49 of file tr_sky.c.
Referenced by AddSkyPolygon(), ClearSkyBox(), DrawSkyBox(), and FillCloudBox().
sky_min
float sky_min static
Definition at line 50 of file tr_sky.c.
Referenced by DrawSkyBox(), MakeSkyVec(), and R_BuildCloudData().
sky_mins
float sky_mins[2][6] static
Definition at line 49 of file tr_sky.c.
Referenced by AddSkyPolygon(), ClearSkyBox(), DrawSkyBox(), and FillCloudBox().
sky_texorder
int sky_texorder[6] = {0,2,1,3,4,5} static
Definition at line 360 of file tr_sky.c.
Referenced by DrawSkyBox().