ioquake3 doxygen: C:/entry/dev/ioq3/code/cgame/cg_servercmds.c File Reference
cg_servercmds.c File Reference
#include "cg_local.h"
Functions
static void CG_ParseScores (void)
static void CG_ParseTeamInfo (void)
void CG_ParseServerinfo (void)
static void CG_ParseWarmup (void)
void CG_SetConfigValues (void)
void CG_ShaderStateChanged (void)
static void CG_ConfigStringModified (void)
static void CG_AddToTeamChat (const char *str)
static void CG_MapRestart (void)
static void CG_RemoveChatEscapeChar (char *text)
static void CG_ServerCommand (void)
void CG_ExecuteNewServerCommands (int latestSequence)
Function Documentation
CG_AddToTeamChat()
static void CG_AddToTeamChat (const char * str) static
Definition at line 374 of file cg_servercmds.c.
 {
     int len;
     char* p, * ls;
     int lastcolor;
     int chatHeight;
     if (cg_teamChatHeight.integer < TEAMCHAT_HEIGHT) {
         chatHeight = cg_teamChatHeight.integer;
     } else {
         chatHeight = TEAMCHAT_HEIGHT;
     }
     if (chatHeight <= 0 || cg_teamChatTime.integer <= 0) {
         // team chat disabled, dump into normal chat
         cgs.teamChatPos = cgs.teamLastChatPos = 0;
         return;
     }
     len = 0;
     p = cgs.teamChatMsgs[cgs.teamChatPos % chatHeight];
     *p = 0;
     lastcolor = '7';
     ls = NULL;
     while (*str) {
         if (len > TEAMCHAT_WIDTH - 1) {
             if (ls) {
                 str -= (p - ls);
                 str++;
                 p -= (p - ls);
             }
             *p = 0;
             cgs.teamChatMsgTimes[cgs.teamChatPos % chatHeight] = cg.time;
             cgs.teamChatPos++;
             p = cgs.teamChatMsgs[cgs.teamChatPos % chatHeight];
             *p = 0;
             *p++ = Q_COLOR_ESCAPE;
             *p++ = lastcolor;
             len = 0;
             ls = NULL;
         }
         if (Q_IsColorString(str)) {
             *p++ = *str++;
             lastcolor = *str;
             *p++ = *str++;
             continue;
         }
         if (*str == ' ') {
             ls = p;
         }
         *p++ = *str++;
         len++;
     }
     *p = 0;
     cgs.teamChatMsgTimes[cgs.teamChatPos % chatHeight] = cg.time;
     cgs.teamChatPos++;
     if (cgs.teamChatPos - cgs.teamLastChatPos > chatHeight)
         cgs.teamLastChatPos = cgs.teamChatPos - chatHeight;
 }
References cg, cg_teamChatHeight, cg_teamChatTime, cgs, vmCvar_t::integer, NULL, Q_COLOR_ESCAPE, Q_IsColorString(), TEAMCHAT_HEIGHT, TEAMCHAT_WIDTH, cgs_t::teamChatMsgs, cgs_t::teamChatMsgTimes, cgs_t::teamChatPos, cgs_t::teamLastChatPos, and cg_t::time.
Referenced by CG_ServerCommand().
CG_ConfigStringModified()
static void CG_ConfigStringModified (void) static
Definition at line 284 of file cg_servercmds.c.
 {
     const char* str;
     int        num;
     num = atoi(CG_Argv(1));
     // get the gamestate from the client system, which will have the
     // new configstring already integrated
     trap_GetGameState(&cgs.gameState);
     // look up the individual string that was modified
     str = CG_ConfigString(num);
     // do something with it if necessary
     if (num == CS_MUSIC) {
         CG_StartMusic();
     } else if (num == CS_SERVERINFO) {
         CG_ParseServerinfo();
     } else if (num == CS_WARMUP) {
         CG_ParseWarmup();
     } else if (num == CS_SCORES1) {
         cgs.scores1 = atoi(str);
     } else if (num == CS_SCORES2) {
         cgs.scores2 = atoi(str);
     } else if (num == CS_LEVEL_START_TIME) {
         cgs.levelStartTime = atoi(str);
     } else if (num == CS_VOTE_TIME) {
         cgs.voteTime = atoi(str);
         cgs.voteModified = qtrue;
     } else if (num == CS_VOTE_YES) {
         cgs.voteYes = atoi(str);
         cgs.voteModified = qtrue;
     } else if (num == CS_VOTE_NO) {
         cgs.voteNo = atoi(str);
         cgs.voteModified = qtrue;
     } else if (num == CS_VOTE_STRING) {
         Q_strncpyz(cgs.voteString, str, sizeof(cgs.voteString));
 #ifdef MISSIONPACK
         trap_S_StartLocalSound(cgs.media.voteNow, CHAN_ANNOUNCER);
 #endif //MISSIONPACK
     } else if (num >= CS_TEAMVOTE_TIME && num <= CS_TEAMVOTE_TIME + 1) {
         cgs.teamVoteTime[num - CS_TEAMVOTE_TIME] = atoi(str);
         cgs.teamVoteModified[num - CS_TEAMVOTE_TIME] = qtrue;
     } else if (num >= CS_TEAMVOTE_YES && num <= CS_TEAMVOTE_YES + 1) {
         cgs.teamVoteYes[num - CS_TEAMVOTE_YES] = atoi(str);
         cgs.teamVoteModified[num - CS_TEAMVOTE_YES] = qtrue;
     } else if (num >= CS_TEAMVOTE_NO && num <= CS_TEAMVOTE_NO + 1) {
         cgs.teamVoteNo[num - CS_TEAMVOTE_NO] = atoi(str);
         cgs.teamVoteModified[num - CS_TEAMVOTE_NO] = qtrue;
     } else if (num >= CS_TEAMVOTE_STRING && num <= CS_TEAMVOTE_STRING + 1) {
         Q_strncpyz(cgs.teamVoteString[num - CS_TEAMVOTE_STRING], str, sizeof(cgs.teamVoteString[0]));
 #ifdef MISSIONPACK
         trap_S_StartLocalSound(cgs.media.voteNow, CHAN_ANNOUNCER);
 #endif
     } else if (num == CS_INTERMISSION) {
         cg.intermissionStarted = atoi(str);
     } else if (num >= CS_MODELS && num < CS_MODELS + MAX_MODELS) {
         cgs.gameModels[num - CS_MODELS] = trap_R_RegisterModel(str);
     } else if (num >= CS_SOUNDS && num < CS_SOUNDS + MAX_SOUNDS) {
         if (str[0] != '*') {    // player specific sounds don't register here
             cgs.gameSounds[num - CS_SOUNDS] = trap_S_RegisterSound(str, qfalse);
         }
     } else if (num >= CS_PLAYERS && num < CS_PLAYERS + MAX_CLIENTS) {
         CG_NewClientInfo(num - CS_PLAYERS);
         CG_BuildSpectatorString();
     } else if (num == CS_FLAGSTATUS) {
         if (cgs.gametype == GT_CTF) {
             // format is rb where its red/blue, 0 is at base, 1 is taken, 2 is dropped
             cgs.redflag = str[0] - '0';
             cgs.blueflag = str[1] - '0';
         }
 #ifdef MISSIONPACK
         else if (cgs.gametype == GT_1FCTF) {
             cgs.flagStatus = str[0] - '0';
         }
 #endif
     } else if (num == CS_SHADERSTATE) {
         CG_ShaderStateChanged();
     }
 }
References cgs_t::blueflag, cg, CG_Argv(), CG_BuildSpectatorString(), CG_ConfigString(), CG_NewClientInfo(), CG_ParseServerinfo(), CG_ParseWarmup(), CG_ShaderStateChanged(), CG_StartMusic(), cgs, CHAN_ANNOUNCER, CS_FLAGSTATUS, CS_INTERMISSION, CS_LEVEL_START_TIME, CS_MODELS, CS_MUSIC, CS_PLAYERS, CS_SCORES1, CS_SCORES2, CS_SERVERINFO, CS_SHADERSTATE, CS_SOUNDS, CS_TEAMVOTE_NO, CS_TEAMVOTE_STRING, CS_TEAMVOTE_TIME, CS_TEAMVOTE_YES, CS_VOTE_NO, CS_VOTE_STRING, CS_VOTE_TIME, CS_VOTE_YES, CS_WARMUP, cgs_t::flagStatus, cgs_t::gameModels, cgs_t::gameSounds, cgs_t::gameState, cgs_t::gametype, GT_1FCTF, GT_CTF, cg_t::intermissionStarted, cgs_t::levelStartTime, MAX_CLIENTS, MAX_MODELS, MAX_SOUNDS, cgs_t::media, Q_strncpyz(), qfalse, qtrue, cgs_t::redflag, cgs_t::scores1, cgs_t::scores2, cgs_t::teamVoteModified, cgs_t::teamVoteNo, cgs_t::teamVoteString, cgs_t::teamVoteTime, cgs_t::teamVoteYes, trap_GetGameState(), trap_R_RegisterModel(), trap_S_RegisterSound(), trap_S_StartLocalSound(), cgs_t::voteModified, cgs_t::voteNo, cgMedia_t::voteNow, cgs_t::voteString, cgs_t::voteTime, and cgs_t::voteYes.
Referenced by CG_ServerCommand().
CG_ExecuteNewServerCommands()
void CG_ExecuteNewServerCommands (int latestSequence)
Definition at line 1121 of file cg_servercmds.c.
 {
     while (cgs.serverCommandSequence < latestSequence) {
         if (trap_GetServerCommand(++cgs.serverCommandSequence)) {
             CG_ServerCommand();
         }
     }
 }
References CG_ServerCommand(), cgs, cgs_t::serverCommandSequence, and trap_GetServerCommand().
Referenced by CG_SetInitialSnapshot(), and CG_TransitionSnapshot().
CG_MapRestart()
static void CG_MapRestart (void) static
Definition at line 453 of file cg_servercmds.c.
 {
     if (cg_showmiss.integer) {
         CG_Printf("CG_MapRestart\n");
     }
     CG_InitLocalEntities();
     CG_InitMarkPolys();
     CG_ClearParticles();
     // make sure the "3 frags left" warnings play again
     cg.fraglimitWarnings = 0;
     cg.timelimitWarnings = 0;
     cg.rewardTime = 0;
     cg.rewardStack = 0;
     cg.intermissionStarted = qfalse;
     cg.levelShot = qfalse;
     cgs.voteTime = 0;
     cg.mapRestart = qtrue;
     CG_StartMusic();
     trap_S_ClearLoopingSounds(qtrue);
     // we really should clear more parts of cg here and stop sounds
     // play the "fight" sound if this is a restart without warmup
     if (cg.warmup == 0 /* && cgs.gametype == GT_TOURNAMENT */) {
         trap_S_StartLocalSound(cgs.media.countFightSound, CHAN_ANNOUNCER);
         CG_CenterPrint("FIGHT!", 120, GIANTCHAR_WIDTH * 2);
     }
 #ifdef MISSIONPACK
     if (cg_singlePlayerActive.integer) {
         trap_Cvar_Set("ui_matchStartTime", va("%i", cg.time));
         if (cg_recordSPDemo.integer && *cg_recordSPDemoName.string) {
             trap_SendConsoleCommand(va("set g_synchronousclients 1 ; record %s \n", cg_recordSPDemoName.string));
         }
     }
 #endif
     trap_Cvar_Set("cg_thirdPerson", "0");
 }
References cg, CG_CenterPrint(), CG_ClearParticles(), CG_InitLocalEntities(), CG_InitMarkPolys(), CG_Printf(), cg_showmiss, CG_StartMusic(), cgs, CHAN_ANNOUNCER, cgMedia_t::countFightSound, cg_t::fraglimitWarnings, GIANTCHAR_WIDTH, vmCvar_t::integer, cg_t::intermissionStarted, cg_t::levelShot, cg_t::mapRestart, cgs_t::media, qfalse, qtrue, cg_t::rewardStack, cg_t::rewardTime, cg_t::time, cg_t::timelimitWarnings, trap_Cvar_Set(), trap_S_ClearLoopingSounds(), trap_S_StartLocalSound(), trap_SendConsoleCommand(), va(), cgs_t::voteTime, and cg_t::warmup.
Referenced by CG_ServerCommand().
CG_ParseScores()
static void CG_ParseScores (void) static
Definition at line 68 of file cg_servercmds.c.
 {
     int        i, powerups;
     cg.numScores = atoi(CG_Argv(1));
     if (cg.numScores > MAX_CLIENTS) {
         cg.numScores = MAX_CLIENTS;
     }
     cg.teamScores[0] = atoi(CG_Argv(2));
     cg.teamScores[1] = atoi(CG_Argv(3));
     memset(cg.scores, 0, sizeof(cg.scores));
     for (i = 0; i < cg.numScores; i++) {
         //
         cg.scores[i].client = atoi(CG_Argv(i * 14 + 4));
         cg.scores[i].score = atoi(CG_Argv(i * 14 + 5));
         cg.scores[i].ping = atoi(CG_Argv(i * 14 + 6));
         cg.scores[i].time = atoi(CG_Argv(i * 14 + 7));
         cg.scores[i].scoreFlags = atoi(CG_Argv(i * 14 + 8));
         powerups = atoi(CG_Argv(i * 14 + 9));
         cg.scores[i].accuracy = atoi(CG_Argv(i * 14 + 10));
         cg.scores[i].impressiveCount = atoi(CG_Argv(i * 14 + 11));
         cg.scores[i].excellentCount = atoi(CG_Argv(i * 14 + 12));
         cg.scores[i].guantletCount = atoi(CG_Argv(i * 14 + 13));
         cg.scores[i].defendCount = atoi(CG_Argv(i * 14 + 14));
         cg.scores[i].assistCount = atoi(CG_Argv(i * 14 + 15));
         cg.scores[i].perfect = atoi(CG_Argv(i * 14 + 16));
         cg.scores[i].captures = atoi(CG_Argv(i * 14 + 17));
         if (cg.scores[i].client < 0 || cg.scores[i].client >= MAX_CLIENTS) {
             cg.scores[i].client = 0;
         }
         cgs.clientinfo[cg.scores[i].client].score = cg.scores[i].score;
         cgs.clientinfo[cg.scores[i].client].powerups = powerups;
         cg.scores[i].team = cgs.clientinfo[cg.scores[i].client].team;
     }
 #ifdef MISSIONPACK
     CG_SetScoreSelection(NULL);
 #endif
 }
References score_t::accuracy, score_t::assistCount, score_t::captures, cg, CG_Argv(), CG_SetScoreSelection(), cgs, score_t::client, cgs_t::clientinfo, score_t::defendCount, score_t::excellentCount, score_t::guantletCount, score_t::impressiveCount, MAX_CLIENTS, NULL, cg_t::numScores, score_t::perfect, score_t::ping, clientInfo_t::powerups, score_t::score, clientInfo_t::score, score_t::scoreFlags, cg_t::scores, score_t::team, clientInfo_t::team, cg_t::teamScores, and score_t::time.
Referenced by CG_ServerCommand().
CG_ParseServerinfo()
void CG_ParseServerinfo (void)
Definition at line 156 of file cg_servercmds.c.
 {
     const char* info;
     char* mapname;
     info = CG_ConfigString(CS_SERVERINFO);
     cgs.gametype = atoi(Info_ValueForKey(info, "g_gametype"));
     trap_Cvar_Set("g_gametype", va("%i", cgs.gametype));
     cgs.dmflags = atoi(Info_ValueForKey(info, "dmflags"));
     cgs.teamflags = atoi(Info_ValueForKey(info, "teamflags"));
     cgs.fraglimit = atoi(Info_ValueForKey(info, "fraglimit"));
     cgs.capturelimit = atoi(Info_ValueForKey(info, "capturelimit"));
     cgs.timelimit = atoi(Info_ValueForKey(info, "timelimit"));
     cgs.maxclients = atoi(Info_ValueForKey(info, "sv_maxclients"));
     mapname = Info_ValueForKey(info, "mapname");
     Com_sprintf(cgs.mapname, sizeof(cgs.mapname), "maps/%s.bsp", mapname);
     Q_strncpyz(cgs.redTeam, Info_ValueForKey(info, "g_redTeam"), sizeof(cgs.redTeam));
     trap_Cvar_Set("g_redTeam", cgs.redTeam);
     Q_strncpyz(cgs.blueTeam, Info_ValueForKey(info, "g_blueTeam"), sizeof(cgs.blueTeam));
     trap_Cvar_Set("g_blueTeam", cgs.blueTeam);
 }
References cgs_t::blueTeam, cgs_t::capturelimit, CG_ConfigString(), cgs, Com_sprintf(), CS_SERVERINFO, cgs_t::dmflags, cgs_t::fraglimit, cgs_t::gametype, Info_ValueForKey(), cgs_t::mapname, cgs_t::maxclients, Q_strncpyz(), cgs_t::redTeam, cgs_t::teamflags, cgs_t::timelimit, trap_Cvar_Set(), and va().
Referenced by CG_ConfigStringModified(), and CG_Init().
CG_ParseTeamInfo()
static void CG_ParseTeamInfo (void) static
Definition at line 118 of file cg_servercmds.c.
 {
     int        i;
     int        client;
     numSortedTeamPlayers = atoi(CG_Argv(1));
     if (numSortedTeamPlayers < 0 || numSortedTeamPlayers > TEAM_MAXOVERLAY) {
         CG_Error("CG_ParseTeamInfo: numSortedTeamPlayers out of range (%d)",
             numSortedTeamPlayers);
         return;
     }
     for (i = 0; i < numSortedTeamPlayers; i++) {
         client = atoi(CG_Argv(i * 6 + 2));
         if (client < 0 || client >= MAX_CLIENTS) {
             CG_Error("CG_ParseTeamInfo: bad client number: %d", client);
             return;
         }
         sortedTeamPlayers[i] = client;
         cgs.clientinfo[client].location = atoi(CG_Argv(i * 6 + 3));
         cgs.clientinfo[client].health = atoi(CG_Argv(i * 6 + 4));
         cgs.clientinfo[client].armor = atoi(CG_Argv(i * 6 + 5));
         cgs.clientinfo[client].curWeapon = atoi(CG_Argv(i * 6 + 6));
         cgs.clientinfo[client].powerups = atoi(CG_Argv(i * 6 + 7));
     }
 }
References clientInfo_t::armor, CG_Argv(), CG_Error(), cgs, cgs_t::clientinfo, clientInfo_t::curWeapon, clientInfo_t::health, clientInfo_t::location, MAX_CLIENTS, numSortedTeamPlayers, clientInfo_t::powerups, sortedTeamPlayers, and TEAM_MAXOVERLAY.
Referenced by CG_ServerCommand().
CG_ParseWarmup()
static void CG_ParseWarmup (void) static
Definition at line 183 of file cg_servercmds.c.
 {
     const char* info;
     int            warmup;
     info = CG_ConfigString(CS_WARMUP);
     warmup = atoi(info);
     cg.warmupCount = -1;
     if (warmup == 0 && cg.warmup) {
     } else if (warmup > 0 && cg.warmup <= 0) {
 #ifdef MISSIONPACK
         if (cgs.gametype >= GT_CTF && cgs.gametype <= GT_HARVESTER) {
             trap_S_StartLocalSound(cgs.media.countPrepareTeamSound, CHAN_ANNOUNCER);
         } else
 #endif
         {
             trap_S_StartLocalSound(cgs.media.countPrepareSound, CHAN_ANNOUNCER);
         }
     }
     cg.warmup = warmup;
 }
References cg, CG_ConfigString(), cgs, CHAN_ANNOUNCER, cgMedia_t::countPrepareSound, CS_WARMUP, cgs_t::gametype, GT_CTF, GT_HARVESTER, cgs_t::media, trap_S_StartLocalSound(), cg_t::warmup, and cg_t::warmupCount.
Referenced by CG_ConfigStringModified().
CG_RemoveChatEscapeChar()
static void CG_RemoveChatEscapeChar (char * text) static
Definition at line 970 of file cg_servercmds.c.
 {
     int i, l;
     l = 0;
     for (i = 0; text[i]; i++) {
         if (text[i] == '\x19')
             continue;
         text[l++] = text[i];
     }
     text[l] = '\0';
 }
Referenced by CG_ServerCommand().
CG_ServerCommand()
static void CG_ServerCommand (void) static
Definition at line 991 of file cg_servercmds.c.
 {
     const char* cmd;
     char        text[MAX_SAY_TEXT];
     cmd = CG_Argv(0);
     if (!cmd[0]) {
         // server claimed the command
         return;
     }
     if (!strcmp(cmd, "cp")) {
         CG_CenterPrint(CG_Argv(1), SCREEN_HEIGHT * 0.30, BIGCHAR_WIDTH);
         return;
     }
     if (!strcmp(cmd, "cs")) {
         CG_ConfigStringModified();
         return;
     }
     if (!strcmp(cmd, "print")) {
         CG_Printf("%s", CG_Argv(1));
 #ifdef MISSIONPACK
         cmd = CG_Argv(1);            // yes, this is obviously a hack, but so is the way we hear about
                                     // votes passing or failing
         if (!Q_stricmpn(cmd, "vote failed", 11) || !Q_stricmpn(cmd, "team vote failed", 16)) {
             trap_S_StartLocalSound(cgs.media.voteFailed, CHAN_ANNOUNCER);
         } else if (!Q_stricmpn(cmd, "vote passed", 11) || !Q_stricmpn(cmd, "team vote passed", 16)) {
             trap_S_StartLocalSound(cgs.media.votePassed, CHAN_ANNOUNCER);
         }
 #endif
         return;
     }
     if (!strcmp(cmd, "chat")) {
         if (cgs.gametype >= GT_TEAM && cg_teamChatsOnly.integer) {
             return;
         }
         trap_S_StartLocalSound(cgs.media.talkSound, CHAN_LOCAL_SOUND);
         Q_strncpyz(text, CG_Argv(1), MAX_SAY_TEXT);
         CG_RemoveChatEscapeChar(text);
         CG_Printf("%s\n", text);
         return;
     }
     if (!strcmp(cmd, "tchat")) {
         trap_S_StartLocalSound(cgs.media.talkSound, CHAN_LOCAL_SOUND);
         Q_strncpyz(text, CG_Argv(1), MAX_SAY_TEXT);
         CG_RemoveChatEscapeChar(text);
         CG_AddToTeamChat(text);
         CG_Printf("%s\n", text);
         return;
     }
 #ifdef MISSIONPACK
     if (!strcmp(cmd, "vchat")) {
         CG_VoiceChat(SAY_ALL);
         return;
     }
     if (!strcmp(cmd, "vtchat")) {
         CG_VoiceChat(SAY_TEAM);
         return;
     }
     if (!strcmp(cmd, "vtell")) {
         CG_VoiceChat(SAY_TELL);
         return;
     }
 #endif
     if (!strcmp(cmd, "scores")) {
         CG_ParseScores();
         return;
     }
     if (!strcmp(cmd, "tinfo")) {
         CG_ParseTeamInfo();
         return;
     }
     if (!strcmp(cmd, "map_restart")) {
         CG_MapRestart();
         return;
     }
     if (Q_stricmp(cmd, "remapShader") == 0) {
         if (trap_Argc() == 4) {
             char shader1[MAX_QPATH];
             char shader2[MAX_QPATH];
             char shader3[MAX_QPATH];
             Q_strncpyz(shader1, CG_Argv(1), sizeof(shader1));
             Q_strncpyz(shader2, CG_Argv(2), sizeof(shader2));
             Q_strncpyz(shader3, CG_Argv(3), sizeof(shader3));
             trap_R_RemapShader(shader1, shader2, shader3);
         }
         return;
     }
     // loaddeferred can be both a servercmd and a consolecmd
     if (!strcmp(cmd, "loaddefered")) {    // FIXME: spelled wrong, but not changing for demo
         CG_LoadDeferredPlayers();
         return;
     }
     // clientLevelShot is sent before taking a special screenshot for
     // the menu system during development
     if (!strcmp(cmd, "clientLevelShot")) {
         cg.levelShot = qtrue;
         return;
     }
     CG_Printf("Unknown client game command: %s\n", cmd);
 }
References BIGCHAR_WIDTH, cg, CG_AddToTeamChat(), CG_Argv(), CG_CenterPrint(), CG_ConfigStringModified(), CG_LoadDeferredPlayers(), CG_MapRestart(), CG_ParseScores(), CG_ParseTeamInfo(), CG_Printf(), CG_RemoveChatEscapeChar(), cg_teamChatsOnly, cgs, CHAN_ANNOUNCER, CHAN_LOCAL_SOUND, cgs_t::gametype, GT_TEAM, vmCvar_t::integer, cg_t::levelShot, MAX_QPATH, MAX_SAY_TEXT, cgs_t::media, Q_stricmp(), Q_stricmpn(), Q_strncpyz(), qtrue, SAY_ALL, SAY_TEAM, SAY_TELL, SCREEN_HEIGHT, cgMedia_t::talkSound, trap_Argc(), trap_R_RemapShader(), trap_S_StartLocalSound(), cgMedia_t::voteFailed, and cgMedia_t::votePassed.
Referenced by CG_ExecuteNewServerCommands().
CG_SetConfigValues()
void CG_SetConfigValues (void)
Definition at line 216 of file cg_servercmds.c.
 {
     const char* s;
     cgs.scores1 = atoi(CG_ConfigString(CS_SCORES1));
     cgs.scores2 = atoi(CG_ConfigString(CS_SCORES2));
     cgs.levelStartTime = atoi(CG_ConfigString(CS_LEVEL_START_TIME));
     if (cgs.gametype == GT_CTF) {
         s = CG_ConfigString(CS_FLAGSTATUS);
         cgs.redflag = s[0] - '0';
         cgs.blueflag = s[1] - '0';
     }
 #ifdef MISSIONPACK
     else if (cgs.gametype == GT_1FCTF) {
         s = CG_ConfigString(CS_FLAGSTATUS);
         cgs.flagStatus = s[0] - '0';
     }
 #endif
     cg.warmup = atoi(CG_ConfigString(CS_WARMUP));
 }
References cgs_t::blueflag, cg, CG_ConfigString(), cgs, CS_FLAGSTATUS, CS_LEVEL_START_TIME, CS_SCORES1, CS_SCORES2, CS_WARMUP, cgs_t::flagStatus, cgs_t::gametype, GT_1FCTF, GT_CTF, cgs_t::levelStartTime, cgs_t::redflag, s, cgs_t::scores1, cgs_t::scores2, and cg_t::warmup.
Referenced by CG_Init().
CG_ShaderStateChanged()
void CG_ShaderStateChanged (void)
Definition at line 242 of file cg_servercmds.c.
 {
     char originalShader[MAX_QPATH];
     char newShader[MAX_QPATH];
     char timeOffset[16];
     const char* o;
     char* n, * t;
     o = CG_ConfigString(CS_SHADERSTATE);
     while (o && *o) {
         n = strstr(o, "=");
         if (n && *n) {
             strncpy(originalShader, o, n - o);
             originalShader[n - o] = 0;
             n++;
             t = strstr(n, ":");
             if (t && *t) {
                 strncpy(newShader, n, t - n);
                 newShader[t - n] = 0;
             } else {
                 break;
             }
             t++;
             o = strstr(t, "@");
             if (o) {
                 strncpy(timeOffset, t, o - t);
                 timeOffset[o - t] = 0;
                 o++;
                 trap_R_RemapShader(originalShader, newShader, timeOffset);
             }
         } else {
             break;
         }
     }
 }
References CG_ConfigString(), CS_SHADERSTATE, MAX_QPATH, t, and trap_R_RemapShader().
Referenced by CG_ConfigStringModified(), and CG_Init().