ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_script.c File Reference
l_script.c File Reference
Macros
#define PUNCTABLE
Functions
void PS_CreatePunctuationTable (script_t *script, punctuation_t *punctuations)
char * PunctuationFromNum (script_t *script, int num)
void QDECL ScriptError (script_t *script, char *str,...)
void QDECL ScriptWarning (script_t *script, char *str,...)
void SetScriptPunctuations (script_t *script, punctuation_t *p)
int PS_ReadWhiteSpace (script_t *script)
int PS_ReadEscapeCharacter (script_t *script, char *ch)
int PS_ReadString (script_t *script, token_t *token, int quote)
int PS_ReadName (script_t *script, token_t *token)
void NumberValue (char *string, int subtype, unsigned long int *intvalue, float *floatvalue)
int PS_ReadNumber (script_t *script, token_t *token)
int PS_ReadLiteral (script_t *script, token_t *token)
int PS_ReadPunctuation (script_t *script, token_t *token)
int PS_ReadPrimitive (script_t *script, token_t *token)
int PS_ReadToken (script_t *script, token_t *token)
int PS_ExpectTokenString (script_t *script, char *string)
int PS_ExpectTokenType (script_t *script, int type, int subtype, token_t *token)
int PS_ExpectAnyToken (script_t *script, token_t *token)
int PS_CheckTokenString (script_t *script, char *string)
int PS_CheckTokenType (script_t *script, int type, int subtype, token_t *token)
int PS_SkipUntilString (script_t *script, char *string)
void PS_UnreadLastToken (script_t *script)
void PS_UnreadToken (script_t *script, token_t *token)
char PS_NextWhiteSpaceChar (script_t *script)
void StripDoubleQuotes (char *string)
void StripSingleQuotes (char *string)
float ReadSignedFloat (script_t *script)
signed long int ReadSignedInt (script_t *script)
void SetScriptFlags (script_t *script, int flags)
int GetScriptFlags (script_t *script)
void ResetScript (script_t *script)
int EndOfScript (script_t *script)
int NumLinesCrossed (script_t *script)
int ScriptSkipTo (script_t *script, char *value)
int FileLength (FILE *fp)
script_t * LoadScriptFile (const char *filename)
script_t * LoadScriptMemory (char *ptr, int length, char *name)
void FreeScript (script_t *script)
void PS_SetBaseFolder (char *path)
Variables
punctuation_t default_punctuations []
Macro Definition Documentation
PUNCTABLE
#define PUNCTABLE
Definition at line 83 of file l_script.c.
Function Documentation
EndOfScript()
int EndOfScript (script_t * script)
Definition at line 1258 of file l_script.c.
 {
     return script->script_p >= script->end_p;
 } //end of the function EndOfScript
References script_s::end_p, and script_s::script_p.
Referenced by PC_ReadSourceToken().
FileLength()
int FileLength (FILE * fp)
Definition at line 1305 of file l_script.c.
 {
     int pos;
     int end;
     pos = ftell(fp);
     fseek(fp, 0, SEEK_END);
     end = ftell(fp);
     fseek(fp, pos, SEEK_SET);
     return end;
 } //end of the function FileLength
References SEEK_END, and SEEK_SET.
Referenced by LoadScriptFile().
FreeScript()
void FreeScript (script_t * script)
Definition at line 1427 of file l_script.c.
 {
 #ifdef PUNCTABLE
     if (script->punctuationtable) FreeMemory(script->punctuationtable);
 #endif //PUNCTABLE
     FreeMemory(script);
 } //end of the function FreeScript
References FreeMemory(), and script_s::punctuationtable.
Referenced by AAS_ParseBSPEntities(), FreeSource(), PC_DefineFromString(), and PC_ReadSourceToken().
GetScriptFlags()
int GetScriptFlags (script_t * script)
Definition at line 1223 of file l_script.c.
 {
     return script->flags;
 } //end of the function GetScriptFlags
References script_s::flags.
LoadScriptFile()
script_t* LoadScriptFile (const char * filename)
Definition at line 1324 of file l_script.c.
 {
 #ifdef BOTLIB
     fileHandle_t fp;
     char pathname[MAX_QPATH];
 #else
     FILE *fp;
 #endif
     int length;
     void *buffer;
     script_t *script;
 #ifdef BOTLIB
     if (strlen(basefolder))
         Com_sprintf(pathname, sizeof(pathname), "%s/%s", basefolder, filename);
     else
         Com_sprintf(pathname, sizeof(pathname), "%s", filename);
     length = botimport.FS_FOpenFile( pathname, &fp, FS_READ );
     if (!fp) return NULL;
 #else
     fp = fopen(filename, "rb");
     if (!fp) return NULL;
     length = FileLength(fp);
 #endif
     buffer = GetClearedMemory(sizeof(script_t) + length + 1);
     script = (script_t *) buffer;
     Com_Memset(script, 0, sizeof(script_t));
     Q_strncpyz(script->filename, filename, sizeof(script->filename));
     script->buffer = (char *) buffer + sizeof(script_t);
     script->buffer[length] = 0;
     script->length = length;
     //pointer in script buffer
     script->script_p = script->buffer;
     //pointer in script buffer before reading token
     script->lastscript_p = script->buffer;
     //pointer to end of script buffer
     script->end_p = &script->buffer[length];
     //set if there's a token available in script->token
     script->tokenavailable = 0;
     //
     script->line = 1;
     script->lastline = 1;
     //
     SetScriptPunctuations(script, NULL);
     //
 #ifdef BOTLIB
     botimport.FS_Read(script->buffer, length, fp);
     botimport.FS_FCloseFile(fp);
 #else
     if (fread(script->buffer, length, 1, fp) != 1)
     {
         FreeMemory(buffer);
         script = NULL;
     } //end if
     fclose(fp);
 #endif
     return script;
 } //end of the function LoadScriptFile
References botimport, buffer, script_s::buffer, Com_Memset, Com_sprintf(), script_s::end_p, FileLength(), script_s::filename, FreeMemory(), botlib_import_s::FS_FCloseFile, botlib_import_s::FS_FOpenFile, botlib_import_s::FS_Read, FS_READ, GetClearedMemory(), script_s::lastline, script_s::lastscript_p, script_s::length, script_s::line, MAX_QPATH, NULL, Q_strncpyz(), script_s::script_p, SetScriptPunctuations(), and script_s::tokenavailable.
Referenced by LoadSourceFile(), and PC_Directive_include().
LoadScriptMemory()
script_t* LoadScriptMemory (char * ptr, int length, char * name)
Definition at line 1391 of file l_script.c.
 {
     void *buffer;
     script_t *script;
     buffer = GetClearedMemory(sizeof(script_t) + length + 1);
     script = (script_t *) buffer;
     Com_Memset(script, 0, sizeof(script_t));
     Q_strncpyz(script->filename, name, sizeof(script->filename));
     script->buffer = (char *) buffer + sizeof(script_t);
     script->buffer[length] = 0;
     script->length = length;
     //pointer in script buffer
     script->script_p = script->buffer;
     //pointer in script buffer before reading token
     script->lastscript_p = script->buffer;
     //pointer to end of script buffer
     script->end_p = &script->buffer[length];
     //set if there's a token available in script->token
     script->tokenavailable = 0;
     //
     script->line = 1;
     script->lastline = 1;
     //
     SetScriptPunctuations(script, NULL);
     //
     Com_Memcpy(script->buffer, ptr, length);
     //
     return script;
 } //end of the function LoadScriptMemory
References buffer, script_s::buffer, Com_Memcpy, Com_Memset, script_s::end_p, script_s::filename, GetClearedMemory(), script_s::lastline, script_s::lastscript_p, script_s::length, script_s::line, NULL, Q_strncpyz(), script_s::script_p, SetScriptPunctuations(), and script_s::tokenavailable.
Referenced by AAS_ParseBSPEntities(), LoadSourceMemory(), and PC_DefineFromString().
NumberValue()
void NumberValue (char * string, int subtype, unsigned long int * intvalue, float * floatvalue)
Definition at line 554 of file l_script.c.
 {
     unsigned long int dotfound = 0;
     *intvalue = 0;
     *floatvalue = 0;
     //floating point number
     if (subtype & TT_FLOAT)
     {
         while(*string)
         {
             if (*string == '.')
             {
                 if (dotfound) return;
                 dotfound = 10;
                 string++;
             } //end if
             if (dotfound)
             {
                 *floatvalue = *floatvalue + (float) (*string - '0') /
                                                                     (float) dotfound;
                 dotfound *= 10;
             } //end if
             else
             {
                 *floatvalue = *floatvalue * 10.0 + (float) (*string - '0');
             } //end else
             string++;
         } //end while
         *intvalue = (unsigned long) *floatvalue;
     } //end if
     else if (subtype & TT_DECIMAL)
     {
         while(*string) *intvalue = *intvalue * 10 + (*string++ - '0');
         *floatvalue = *intvalue;
     } //end else if
     else if (subtype & TT_HEX)
     {
         //step over the leading 0x or 0X
         string += 2;
         while(*string)
         {
             *intvalue <<= 4;
             if (*string >= 'a' && *string <= 'f') *intvalue += *string - 'a' + 10;
             else if (*string >= 'A' && *string <= 'F') *intvalue += *string - 'A' + 10;
             else *intvalue += *string - '0';
             string++;
         } //end while
         *floatvalue = *intvalue;
     } //end else if
     else if (subtype & TT_OCTAL)
     {
         //step over the first zero
         string += 1;
         while(*string) *intvalue = (*intvalue << 3) + (*string++ - '0');
         *floatvalue = *intvalue;
     } //end else if
     else if (subtype & TT_BINARY)
     {
         //step over the leading 0b or 0B
         string += 2;
         while(*string) *intvalue = (*intvalue << 1) + (*string++ - '0');
         *floatvalue = *intvalue;
     } //end else if
 } //end of the function NumberValue
References long(), TT_BINARY, TT_DECIMAL, TT_FLOAT, TT_HEX, and TT_OCTAL.
Referenced by PS_ReadNumber().
NumLinesCrossed()
int NumLinesCrossed (script_t * script)
Definition at line 1268 of file l_script.c.
 {
     return script->line - script->lastline;
 } //end of the function NumLinesCrossed
References script_s::lastline, and script_s::line.
PS_CheckTokenString()
int PS_CheckTokenString (script_t * script, char * string)
Definition at line 1023 of file l_script.c.
 {
     token_t tok;
     if (!PS_ReadToken(script, &tok)) return 0;
     //if the token is available
     if (!strcmp(tok.string, string)) return 1;
     //token not available
     script->script_p = script->lastscript_p;
     return 0;
 } //end of the function PS_CheckTokenString
References script_s::lastscript_p, PS_ReadToken(), script_s::script_p, and token_s::string.
PS_CheckTokenType()
int PS_CheckTokenType (script_t * script, int type, int subtype, token_t * token)
Definition at line 1040 of file l_script.c.
 {
     token_t tok;
     if (!PS_ReadToken(script, &tok)) return 0;
     //if the type matches
     if (tok.type == type &&
             (tok.subtype & subtype) == subtype)
     {
         Com_Memcpy(token, &tok, sizeof(token_t));
         return 1;
     } //end if
     //token is not available
     script->script_p = script->lastscript_p;
     return 0;
 } //end of the function PS_CheckTokenType
References Com_Memcpy, script_s::lastscript_p, PS_ReadToken(), script_s::script_p, token_s::subtype, and token_s::type.
PS_CreatePunctuationTable()
void PS_CreatePunctuationTable (script_t * script, punctuation_t * punctuations)
Definition at line 173 of file l_script.c.
 {
     int i;
     punctuation_t *p, *lastp, *newp;
     //get memory for the table
     if (!script->punctuationtable) script->punctuationtable = (punctuation_t **)
                                                 GetMemory(256 * sizeof(punctuation_t *));
     Com_Memset(script->punctuationtable, 0, 256 * sizeof(punctuation_t *));
     //add the punctuations in the list to the punctuation table
     for (i = 0; punctuations[i].p; i++)
     {
         newp = &punctuations[i];
         lastp = NULL;
         //sort the punctuations in this table entry on length (longer punctuations first)
         for (p = script->punctuationtable[(unsigned int) newp->p[0]]; p; p = p->next)
         {
             if (strlen(p->p) < strlen(newp->p))
             {
                 newp->next = p;
                 if (lastp) lastp->next = newp;
                 else script->punctuationtable[(unsigned int) newp->p[0]] = newp;
                 break;
             } //end if
             lastp = p;
         } //end for
         if (!p)
         {
             newp->next = NULL;
             if (lastp) lastp->next = newp;
             else script->punctuationtable[(unsigned int) newp->p[0]] = newp;
         } //end if
     } //end for
 } //end of the function PS_CreatePunctuationTable
References Com_Memset, GetMemory(), int(), punctuation_s::next, NULL, punctuation_s::p, and script_s::punctuationtable.
Referenced by SetScriptPunctuations().
PS_ExpectAnyToken()
int PS_ExpectAnyToken (script_t * script, token_t * token)
Definition at line 1005 of file l_script.c.
 {
     if (!PS_ReadToken(script, token))
     {
         ScriptError(script, "couldn't read expected token");
         return 0;
     } //end if
     else
     {
         return 1;
     } //end else
 } //end of the function PS_ExpectAnyToken
References PS_ReadToken(), and ScriptError().
Referenced by ReadSignedFloat(), and ReadSignedInt().
PS_ExpectTokenString()
int PS_ExpectTokenString (script_t * script, char * string)
Definition at line 922 of file l_script.c.
 {
     token_t token;
     if (!PS_ReadToken(script, &token))
     {
         ScriptError(script, "couldn't find expected %s", string);
         return 0;
     } //end if
     if (strcmp(token.string, string))
     {
         ScriptError(script, "expected %s, found %s", string, token.string);
         return 0;
     } //end if
     return 1;
 } //end of the function PS_ExpectToken
References PS_ReadToken(), ScriptError(), and token_s::string.
PS_ExpectTokenType()
int PS_ExpectTokenType (script_t * script, int type, int subtype, token_t * token)
Definition at line 945 of file l_script.c.
 {
     char str[MAX_TOKEN];
     if (!PS_ReadToken(script, token))
     {
         ScriptError(script, "couldn't read expected token");
         return 0;
     } //end if
     if (token->type != type)
     {
         strcpy(str, "");
         if (type == TT_STRING) strcpy(str, "string");
         if (type == TT_LITERAL) strcpy(str, "literal");
         if (type == TT_NUMBER) strcpy(str, "number");
         if (type == TT_NAME) strcpy(str, "name");
         if (type == TT_PUNCTUATION) strcpy(str, "punctuation");
         ScriptError(script, "expected a %s, found %s", str, token->string);
         return 0;
     } //end if
     if (token->type == TT_NUMBER)
     {
         if ((token->subtype & subtype) != subtype)
         {
             strcpy(str, "");
             if (subtype & TT_DECIMAL) strcpy(str, "decimal");
             if (subtype & TT_HEX) strcpy(str, "hex");
             if (subtype & TT_OCTAL) strcpy(str, "octal");
             if (subtype & TT_BINARY) strcpy(str, "binary");
             if (subtype & TT_LONG) strcat(str, " long");
             if (subtype & TT_UNSIGNED) strcat(str, " unsigned");
             if (subtype & TT_FLOAT) strcat(str, " float");
             if (subtype & TT_INTEGER) strcat(str, " integer");
             ScriptError(script, "expected %s, found %s", str, token->string);
             return 0;
         } //end if
     } //end if
     else if (token->type == TT_PUNCTUATION)
     {
         if (subtype < 0)
         {
             ScriptError(script, "BUG: wrong punctuation subtype");
             return 0;
         } //end if
         if (token->subtype != subtype)
         {
             ScriptError(script, "expected %s, found %s",
                             script->punctuations[subtype].p, token->string);
             return 0;
         } //end if
     } //end else if
     return 1;
 } //end of the function PS_ExpectTokenType
References MAX_TOKEN, punctuation_s::p, PS_ReadToken(), script_s::punctuations, ScriptError(), token_s::string, token_s::subtype, TT_BINARY, TT_DECIMAL, TT_FLOAT, TT_HEX, TT_INTEGER, TT_LITERAL, TT_LONG, TT_NAME, TT_NUMBER, TT_OCTAL, TT_PUNCTUATION, TT_STRING, TT_UNSIGNED, and token_s::type.
Referenced by AAS_ParseBSPEntities().
PS_NextWhiteSpaceChar()
char PS_NextWhiteSpaceChar (script_t * script)
Definition at line 1100 of file l_script.c.
 {
     if (script->whitespace_p != script->endwhitespace_p)
     {
         return *script->whitespace_p++;
     } //end if
     else
     {
         return 0;
     } //end else
 } //end of the function PS_NextWhiteSpaceChar
References script_s::endwhitespace_p, and script_s::whitespace_p.
PS_ReadEscapeCharacter()
int PS_ReadEscapeCharacter (script_t * script, char * ch)
Definition at line 357 of file l_script.c.
 {
     int c, val, i;
     //step over the leading '\\'
     script->script_p++;
     //determine the escape character
     switch(*script->script_p)
     {
         case '\\': c = '\\'; break;
         case 'n': c = '\n'; break;
         case 'r': c = '\r'; break;
         case 't': c = '\t'; break;
         case 'v': c = '\v'; break;
         case 'b': c = '\b'; break;
         case 'f': c = '\f'; break;
         case 'a': c = '\a'; break;
         case '\'': c = '\''; break;
         case '\"': c = '\"'; break;
         case '\?': c = '\?'; break;
         case 'x':
         {
             script->script_p++;
             for (i = 0, val = 0; ; i++, script->script_p++)
             {
                 c = *script->script_p;
                 if (c >= '0' && c <= '9') c = c - '0';
                 else if (c >= 'A' && c <= 'Z') c = c - 'A' + 10;
                 else if (c >= 'a' && c <= 'z') c = c - 'a' + 10;
                 else break;
                 val = (val << 4) + c;
             } //end for
             script->script_p--;
             if (val > 0xFF)
             {
                 ScriptWarning(script, "too large value in escape character");
                 val = 0xFF;
             } //end if
             c = val;
             break;
         } //end case
         default: //NOTE: decimal ASCII code, NOT octal
         {
             if (*script->script_p < '0' || *script->script_p > '9') ScriptError(script, "unknown escape char");
             for (i = 0, val = 0; ; i++, script->script_p++)
             {
                 c = *script->script_p;
                 if (c >= '0' && c <= '9') c = c - '0';
                 else break;
                 val = val * 10 + c;
             } //end for
             script->script_p--;
             if (val > 0xFF)
             {
                 ScriptWarning(script, "too large value in escape character");
                 val = 0xFF;
             } //end if
             c = val;
             break;
         } //end default
     } //end switch
     //step over the escape character or the last digit of the number
     script->script_p++;
     //store the escape character
     *ch = c;
     //successfully read escape character
     return 1;
 } //end of the function PS_ReadEscapeCharacter
References script_s::script_p, ScriptError(), and ScriptWarning().
Referenced by PS_ReadLiteral(), and PS_ReadString().
PS_ReadLiteral()
int PS_ReadLiteral (script_t * script, token_t * token)
Definition at line 734 of file l_script.c.
 {
     token->type = TT_LITERAL;
     //first quote
     token->string[0] = *script->script_p++;
     //check for end of file
     if (!*script->script_p)
     {
         ScriptError(script, "end of file before trailing \'");
         return 0;
     } //end if
     //if it is an escape character
     if (*script->script_p == '\\')
     {
         if (!PS_ReadEscapeCharacter(script, &token->string[1])) return 0;
     } //end if
     else
     {
         token->string[1] = *script->script_p++;
     } //end else
     //check for trailing quote
     if (*script->script_p != '\'')
     {
         ScriptWarning(script, "too many characters in literal, ignored");
         while(*script->script_p &&
                 *script->script_p != '\'' &&
                 *script->script_p != '\n')
         {
             script->script_p++;
         } //end while
         if (*script->script_p == '\'') script->script_p++;
     } //end if
     //store the trailing quote
     token->string[2] = *script->script_p++;
     //store trailing zero to end the string
     token->string[3] = '\0';
     //the sub type is the integer literal value
     token->subtype = token->string[1];
     //
     return 1;
 } //end of the function PS_ReadLiteral
References PS_ReadEscapeCharacter(), script_s::script_p, ScriptError(), ScriptWarning(), token_s::string, token_s::subtype, TT_LITERAL, and token_s::type.
PS_ReadName()
int PS_ReadName (script_t * script, token_t * token)
Definition at line 524 of file l_script.c.
 {
     int len = 0;
     char c;
     token->type = TT_NAME;
     do
     {
         token->string[len++] = *script->script_p++;
         if (len >= MAX_TOKEN)
         {
             ScriptError(script, "name longer than MAX_TOKEN = %d", MAX_TOKEN);
             return 0;
         } //end if
         c = *script->script_p;
    } while ((c >= 'a' && c <= 'z') ||
                 (c >= 'A' && c <= 'Z') ||
                 (c >= '0' && c <= '9') ||
                 c == '_');
     token->string[len] = '\0';
     //the sub type is the length of the name
     token->subtype = len;
     return 1;
 } //end of the function PS_ReadName
References MAX_TOKEN, script_s::script_p, ScriptError(), token_s::string, token_s::subtype, TT_NAME, and token_s::type.
Referenced by PS_ReadToken().
PS_ReadNumber()
int PS_ReadNumber (script_t * script, token_t * token)
Definition at line 626 of file l_script.c.
 {
     int len = 0, i;
     int octal, dot;
     char c;
 //  unsigned long int intvalue = 0;
 //  double floatvalue = 0;
     token->type = TT_NUMBER;
     //check for a hexadecimal number
     if (*script->script_p == '0' &&
         (*(script->script_p + 1) == 'x' ||
         *(script->script_p + 1) == 'X'))
     {
         token->string[len++] = *script->script_p++;
         token->string[len++] = *script->script_p++;
         c = *script->script_p;
         //hexadecimal
         while((c >= '0' && c <= '9') ||
                     (c >= 'a' && c <= 'f') ||
                     (c >= 'A' && c <= 'A'))
         {
             token->string[len++] = *script->script_p++;
             if (len >= MAX_TOKEN)
             {
                 ScriptError(script, "hexadecimal number longer than MAX_TOKEN = %d", MAX_TOKEN);
                 return 0;
             } //end if
             c = *script->script_p;
         } //end while
         token->subtype |= TT_HEX;
     } //end if
 #ifdef BINARYNUMBERS
     //check for a binary number
     else if (*script->script_p == '0' &&
         (*(script->script_p + 1) == 'b' ||
         *(script->script_p + 1) == 'B'))
     {
         token->string[len++] = *script->script_p++;
         token->string[len++] = *script->script_p++;
         c = *script->script_p;
         //binary
         while(c == '0' || c == '1')
         {
             token->string[len++] = *script->script_p++;
             if (len >= MAX_TOKEN)
             {
                 ScriptError(script, "binary number longer than MAX_TOKEN = %d", MAX_TOKEN);
                 return 0;
             } //end if
             c = *script->script_p;
         } //end while
         token->subtype |= TT_BINARY;
     } //end if
 #endif //BINARYNUMBERS
     else //decimal or octal integer or floating point number
     {
         octal = qfalse;
         dot = qfalse;
         if (*script->script_p == '0') octal = qtrue;
         while(1)
         {
             c = *script->script_p;
             if (c == '.') dot = qtrue;
             else if (c == '8' || c == '9') octal = qfalse;
             else if (c < '0' || c > '9') break;
             token->string[len++] = *script->script_p++;
             if (len >= MAX_TOKEN - 1)
             {
                 ScriptError(script, "number longer than MAX_TOKEN = %d", MAX_TOKEN);
                 return 0;
             } //end if
         } //end while
         if (octal) token->subtype |= TT_OCTAL;
         else token->subtype |= TT_DECIMAL;
         if (dot) token->subtype |= TT_FLOAT;
     } //end else
     for (i = 0; i < 2; i++)
     {
         c = *script->script_p;
         //check for a LONG number
         if ( (c == 'l' || c == 'L')
              && !(token->subtype & TT_LONG))
         {
             script->script_p++;
             token->subtype |= TT_LONG;
         } //end if
         //check for an UNSIGNED number
         else if ( (c == 'u' || c == 'U')
               && !(token->subtype & (TT_UNSIGNED | TT_FLOAT)))
         {
             script->script_p++;
             token->subtype |= TT_UNSIGNED;
         } //end if
     } //end for
     token->string[len] = '\0';
 #ifdef NUMBERVALUE
     NumberValue(token->string, token->subtype, &token->intvalue, &token->floatvalue);
 #endif //NUMBERVALUE
     if (!(token->subtype & TT_FLOAT)) token->subtype |= TT_INTEGER;
     return 1;
 } //end of the function PS_ReadNumber
References token_s::floatvalue, token_s::intvalue, MAX_TOKEN, NumberValue(), qfalse, qtrue, script_s::script_p, ScriptError(), token_s::string, token_s::subtype, TT_BINARY, TT_DECIMAL, TT_FLOAT, TT_HEX, TT_INTEGER, TT_LONG, TT_NUMBER, TT_OCTAL, TT_UNSIGNED, and token_s::type.
Referenced by PS_ReadToken().
PS_ReadPrimitive()
int PS_ReadPrimitive (script_t * script, token_t * token)
Definition at line 822 of file l_script.c.
 {
     int len;
     len = 0;
     while(*script->script_p > ' ' && *script->script_p != ';')
     {
         if (len >= MAX_TOKEN - 1)
         {
             ScriptError(script, "primitive token longer than MAX_TOKEN = %d", MAX_TOKEN);
             return 0;
         } //end if
         token->string[len++] = *script->script_p++;
     } //end while
     token->string[len] = 0;
     //copy the token into the script structure
     Com_Memcpy(&script->token, token, sizeof(token_t));
     //primitive reading successful
     return 1;
 } //end of the function PS_ReadPrimitive
References Com_Memcpy, MAX_TOKEN, script_s::script_p, ScriptError(), token_s::string, and script_s::token.
Referenced by PS_ReadToken().
PS_ReadPunctuation()
int PS_ReadPunctuation (script_t * script, token_t * token)
Definition at line 781 of file l_script.c.
 {
     int len;
     char *p;
     punctuation_t *punc;
 #ifdef PUNCTABLE
     for (punc = script->punctuationtable[(unsigned int)*script->script_p]; punc; punc = punc->next)
     {
 #else
     int i;
     for (i = 0; script->punctuations[i].p; i++)
     {
         punc = &script->punctuations[i];
 #endif //PUNCTABLE
         p = punc->p;
         len = strlen(p);
         //if the script contains at least as much characters as the punctuation
         if (script->script_p + len <= script->end_p)
         {
             //if the script contains the punctuation
             if (!strncmp(script->script_p, p, len))
             {
                 Q_strncpyz(token->string, p, MAX_TOKEN);
                 script->script_p += len;
                 token->type = TT_PUNCTUATION;
                 //sub type is the number of the punctuation
                 token->subtype = punc->n;
                 return 1;
             } //end if
         } //end if
     } //end for
     return 0;
 } //end of the function PS_ReadPunctuation
References MAX_TOKEN, punctuation_s::n, punctuation_s::next, punctuation_s::p, script_s::punctuations, script_s::punctuationtable, Q_strncpyz(), script_s::script_p, token_s::string, token_s::subtype, TT_PUNCTUATION, and token_s::type.
Referenced by PS_ReadToken().
PS_ReadString()
int PS_ReadString (script_t * script, token_t * token, int quote)
Definition at line 435 of file l_script.c.
 {
     int len, tmpline;
     char *tmpscript_p;
     if (quote == '\"') token->type = TT_STRING;
     else token->type = TT_LITERAL;
     len = 0;
     //leading quote
     token->string[len++] = *script->script_p++;
     //
     while(1)
     {
         //minus 2 because trailing double quote and zero have to be appended
         if (len >= MAX_TOKEN - 2)
         {
             ScriptError(script, "string longer than MAX_TOKEN = %d", MAX_TOKEN);
             return 0;
         } //end if
         //if there is an escape character and
         //if escape characters inside a string are allowed
         if (*script->script_p == '\\' && !(script->flags & SCFL_NOSTRINGESCAPECHARS))
         {
             if (!PS_ReadEscapeCharacter(script, &token->string[len]))
             {
                 token->string[len] = 0;
                 return 0;
             } //end if
             len++;
         } //end if
         //if a trailing quote
         else if (*script->script_p == quote)
         {
             //step over the double quote
             script->script_p++;
             //if white spaces in a string are not allowed
             if (script->flags & SCFL_NOSTRINGWHITESPACES) break;
             //
             tmpscript_p = script->script_p;
             tmpline = script->line;
             //read unusefull stuff between possible two following strings
             if (!PS_ReadWhiteSpace(script))
             {
                 script->script_p = tmpscript_p;
                 script->line = tmpline;
                 break;
             } //end if
             //if there's no leading double qoute
             if (*script->script_p != quote)
             {
                 script->script_p = tmpscript_p;
                 script->line = tmpline;
                 break;
             } //end if
             //step over the new leading double quote
             script->script_p++;
         } //end if
         else
         {
             if (*script->script_p == '\0')
             {
                 token->string[len] = 0;
                 ScriptError(script, "missing trailing quote");
                 return 0;
             } //end if
           if (*script->script_p == '\n')
             {
                 token->string[len] = 0;
                 ScriptError(script, "newline inside string %s", token->string);
                 return 0;
             } //end if
             token->string[len++] = *script->script_p++;
         } //end else
     } //end while
     //trailing quote
     token->string[len++] = quote;
     //end string with a zero
     token->string[len] = '\0';
     //the sub type is the length of the string
     token->subtype = len;
     return 1;
 } //end of the function PS_ReadString
References script_s::flags, script_s::line, MAX_TOKEN, PS_ReadEscapeCharacter(), PS_ReadWhiteSpace(), SCFL_NOSTRINGESCAPECHARS, SCFL_NOSTRINGWHITESPACES, script_s::script_p, ScriptError(), token_s::string, token_s::subtype, TT_LITERAL, TT_STRING, and token_s::type.
Referenced by PS_ReadToken().
PS_ReadToken()
int PS_ReadToken (script_t * script, token_t * token)
Definition at line 848 of file l_script.c.
 {
     //if there is a token available (from UnreadToken)
     if (script->tokenavailable)
     {
         script->tokenavailable = 0;
         Com_Memcpy(token, &script->token, sizeof(token_t));
         return 1;
     } //end if
     //save script pointer
     script->lastscript_p = script->script_p;
     //save line counter
     script->lastline = script->line;
     //clear the token stuff
     Com_Memset(token, 0, sizeof(token_t));
     //start of the white space
     script->whitespace_p = script->script_p;
     token->whitespace_p = script->script_p;
     //read unusefull stuff
     if (!PS_ReadWhiteSpace(script)) return 0;
     //end of the white space
     script->endwhitespace_p = script->script_p;
     token->endwhitespace_p = script->script_p;
     //line the token is on
     token->line = script->line;
     //number of lines crossed before token
     token->linescrossed = script->line - script->lastline;
     //if there is a leading double quote
     if (*script->script_p == '\"')
     {
         if (!PS_ReadString(script, token, '\"')) return 0;
     } //end if
     //if a literal
     else if (*script->script_p == '\'')
     {
         //if (!PS_ReadLiteral(script, token)) return 0;
         if (!PS_ReadString(script, token, '\'')) return 0;
     } //end if
     //if there is a number
     else if ((*script->script_p >= '0' && *script->script_p <= '9') ||
                 (*script->script_p == '.' &&
                 (*(script->script_p + 1) >= '0' && *(script->script_p + 1) <= '9')))
     {
         if (!PS_ReadNumber(script, token)) return 0;
     } //end if
     //if this is a primitive script
     else if (script->flags & SCFL_PRIMITIVE)
     {
         return PS_ReadPrimitive(script, token);
     } //end else if
     //if there is a name
     else if ((*script->script_p >= 'a' && *script->script_p <= 'z') ||
         (*script->script_p >= 'A' && *script->script_p <= 'Z') ||
         *script->script_p == '_')
     {
         if (!PS_ReadName(script, token)) return 0;
     } //end if
     //check for punctuations
     else if (!PS_ReadPunctuation(script, token))
     {
         ScriptError(script, "can't read token");
         return 0;
     } //end if
     //copy the token into the script structure
     Com_Memcpy(&script->token, token, sizeof(token_t));
     //successfully read a token
     return 1;
 } //end of the function PS_ReadToken
References Com_Memcpy, Com_Memset, token_s::endwhitespace_p, script_s::endwhitespace_p, script_s::flags, script_s::lastline, script_s::lastscript_p, token_s::line, script_s::line, token_s::linescrossed, PS_ReadName(), PS_ReadNumber(), PS_ReadPrimitive(), PS_ReadPunctuation(), PS_ReadString(), PS_ReadWhiteSpace(), SCFL_PRIMITIVE, script_s::script_p, ScriptError(), script_s::token, script_s::tokenavailable, token_s::whitespace_p, and script_s::whitespace_p.
Referenced by AAS_ParseBSPEntities(), PC_ReadSourceToken(), PS_CheckTokenString(), PS_CheckTokenType(), PS_ExpectAnyToken(), PS_ExpectTokenString(), PS_ExpectTokenType(), and PS_SkipUntilString().
PS_ReadWhiteSpace()
int PS_ReadWhiteSpace (script_t * script)
Definition at line 298 of file l_script.c.
 {
     while(1)
     {
         //skip white space
         while(*script->script_p <= ' ')
         {
             if (!*script->script_p) return 0;
             if (*script->script_p == '\n') script->line++;
             script->script_p++;
         } //end while
         //skip comments
         if (*script->script_p == '/')
         {
             //comments //
             if (*(script->script_p+1) == '/')
             {
                 script->script_p++;
                 do
                 {
                     script->script_p++;
                     if (!*script->script_p) return 0;
                 } //end do
                 while(*script->script_p != '\n');
                 script->line++;
                 script->script_p++;
                 if (!*script->script_p) return 0;
                 continue;
             } //end if
             //comments /* */
             else if (*(script->script_p+1) == '*')
             {
                 script->script_p++;
                 do
                 {
                     script->script_p++;
                     if (!*script->script_p) return 0;
                     if (*script->script_p == '\n') script->line++;
                 } //end do
                 while(!(*script->script_p == '*' && *(script->script_p+1) == '/'));
                 script->script_p++;
                 if (!*script->script_p) return 0;
                 script->script_p++;
                 if (!*script->script_p) return 0;
                 continue;
             } //end if
         } //end if
         break;
     } //end while
     return 1;
 } //end of the function PS_ReadWhiteSpace
References script_s::line, and script_s::script_p.
Referenced by PS_ReadString(), PS_ReadToken(), and ScriptSkipTo().
PS_SetBaseFolder()
void PS_SetBaseFolder (char * path)
Definition at line 1440 of file l_script.c.
 {
 #ifdef BOTLIB
     Com_sprintf(basefolder, sizeof(basefolder), "%s", path);
 #endif
 } //end of the function PS_SetBaseFolder
References Com_sprintf().
Referenced by PC_LoadSourceHandle(), and PC_SetBaseFolder().
PS_SkipUntilString()
int PS_SkipUntilString (script_t * script, char * string)
Definition at line 1062 of file l_script.c.
 {
     token_t token;
     while(PS_ReadToken(script, &token))
     {
         if (!strcmp(token.string, string)) return 1;
     } //end while
     return 0;
 } //end of the function PS_SkipUntilString
References PS_ReadToken(), and token_s::string.
PS_UnreadLastToken()
void PS_UnreadLastToken (script_t * script)
Definition at line 1078 of file l_script.c.
 {
     script->tokenavailable = 1;
 } //end of the function UnreadLastToken
References script_s::tokenavailable.
PS_UnreadToken()
void PS_UnreadToken (script_t * script, token_t * token)
Definition at line 1088 of file l_script.c.
 {
     Com_Memcpy(&script->token, token, sizeof(token_t));
     script->tokenavailable = 1;
 } //end of the function UnreadToken
References Com_Memcpy, script_s::token, and script_s::tokenavailable.
PunctuationFromNum()
char* PunctuationFromNum (script_t * script, int num)
Definition at line 213 of file l_script.c.
 {
     int i;
     for (i = 0; script->punctuations[i].p; i++)
     {
         if (script->punctuations[i].n == num) return script->punctuations[i].p;
     } //end for
     return "unknown punctuation";
 } //end of the function PunctuationFromNum
References punctuation_s::n, punctuation_s::p, and script_s::punctuations.
Referenced by PC_EvaluateTokens().
ReadSignedFloat()
float ReadSignedFloat (script_t * script)
Definition at line 1151 of file l_script.c.
 {
     token_t token;
     float sign = 1.0;
     PS_ExpectAnyToken(script, &token);
     if (!strcmp(token.string, "-"))
     {
         if(!PS_ExpectAnyToken(script, &token))
         {
             ScriptError(script, "Missing float value");
             return 0;
         }
         sign = -1.0;
     }
     if (token.type != TT_NUMBER)
     {
         ScriptError(script, "expected float value, found %s", token.string);
         return 0;
     }
     return sign * token.floatvalue;
 } //end of the function ReadSignedFloat
References token_s::floatvalue, PS_ExpectAnyToken(), ScriptError(), token_s::string, TT_NUMBER, and token_s::type.
ReadSignedInt()
signed long int ReadSignedInt (script_t * script)
Definition at line 1182 of file l_script.c.
 {
     token_t token;
     signed long int sign = 1;
     PS_ExpectAnyToken(script, &token);
     if (!strcmp(token.string, "-"))
     {
         if(!PS_ExpectAnyToken(script, &token))
         {
             ScriptError(script, "Missing integer value");
             return 0;
         }
         sign = -1;
     }
     if (token.type != TT_NUMBER || token.subtype == TT_FLOAT)
     {
         ScriptError(script, "expected integer value, found %s", token.string);
         return 0;
     }
     return sign * token.intvalue;
 } //end of the function ReadSignedInt
References token_s::intvalue, PS_ExpectAnyToken(), ScriptError(), token_s::string, token_s::subtype, TT_FLOAT, TT_NUMBER, and token_s::type.
ResetScript()
void ResetScript (script_t * script)
Definition at line 1233 of file l_script.c.
 {
     //pointer in script buffer
     script->script_p = script->buffer;
     //pointer in script buffer before reading token
     script->lastscript_p = script->buffer;
     //begin of white space
     script->whitespace_p = NULL;
     //end of white space
     script->endwhitespace_p = NULL;
     //set if there's a token available in script->token
     script->tokenavailable = 0;
     //
     script->line = 1;
     script->lastline = 1;
     //clear the saved token
     Com_Memset(&script->token, 0, sizeof(token_t));
 } //end of the function ResetScript
References script_s::buffer, Com_Memset, script_s::endwhitespace_p, script_s::lastline, script_s::lastscript_p, script_s::line, NULL, script_s::script_p, script_s::token, script_s::tokenavailable, and script_s::whitespace_p.
ScriptError()
void QDECL ScriptError (script_t * script, char * str, ...)
Definition at line 229 of file l_script.c.
 {
     char text[1024];
     va_list ap;
     if (script->flags & SCFL_NOERRORS) return;
     va_start(ap, str);
     Q_vsnprintf(text, sizeof(text), str, ap);
     va_end(ap);
 #ifdef BOTLIB
     botimport.Print(PRT_ERROR, "file %s, line %d: %s\n", script->filename, script->line, text);
 #endif //BOTLIB
 #ifdef MEQCC
     printf("error: file %s, line %d: %s\n", script->filename, script->line, text);
 #endif //MEQCC
 #ifdef BSPC
     Log_Print("error: file %s, line %d: %s\n", script->filename, script->line, text);
 #endif //BSPC
 } //end of the function ScriptError
References botimport, script_s::filename, script_s::flags, script_s::line, PRT_ERROR, Q_vsnprintf(), and SCFL_NOERRORS.
Referenced by AAS_ParseBSPEntities(), PS_ExpectAnyToken(), PS_ExpectTokenString(), PS_ExpectTokenType(), PS_ReadEscapeCharacter(), PS_ReadLiteral(), PS_ReadName(), PS_ReadNumber(), PS_ReadPrimitive(), PS_ReadString(), PS_ReadToken(), ReadSignedFloat(), and ReadSignedInt().
ScriptSkipTo()
int ScriptSkipTo (script_t * script, char * value)
Definition at line 1278 of file l_script.c.
 {
     int len;
     char firstchar;
     firstchar = *value;
     len = strlen(value);
     do
     {
         if (!PS_ReadWhiteSpace(script)) return 0;
         if (*script->script_p == firstchar)
         {
             if (!strncmp(script->script_p, value, len))
             {
                 return 1;
             } //end if
         } //end if
         script->script_p++;
     } while(1);
 } //end of the function ScriptSkipTo
References PS_ReadWhiteSpace(), and script_s::script_p.
ScriptWarning()
void QDECL ScriptWarning (script_t * script, char * str, ...)
Definition at line 255 of file l_script.c.
 {
     char text[1024];
     va_list ap;
     if (script->flags & SCFL_NOWARNINGS) return;
     va_start(ap, str);
     Q_vsnprintf(text, sizeof(text), str, ap);
     va_end(ap);
 #ifdef BOTLIB
     botimport.Print(PRT_WARNING, "file %s, line %d: %s\n", script->filename, script->line, text);
 #endif //BOTLIB
 #ifdef MEQCC
     printf("warning: file %s, line %d: %s\n", script->filename, script->line, text);
 #endif //MEQCC
 #ifdef BSPC
     Log_Print("warning: file %s, line %d: %s\n", script->filename, script->line, text);
 #endif //BSPC
 } //end of the function ScriptWarning
References botimport, script_s::filename, script_s::flags, script_s::line, PRT_WARNING, Q_vsnprintf(), and SCFL_NOWARNINGS.
Referenced by PS_ReadEscapeCharacter(), and PS_ReadLiteral().
SetScriptFlags()
void SetScriptFlags (script_t * script, int flags)
Definition at line 1213 of file l_script.c.
 {
     script->flags = flags;
 } //end of the function SetScriptFlags
References script_s::flags.
Referenced by AAS_ParseBSPEntities().
SetScriptPunctuations()
void SetScriptPunctuations (script_t * script, punctuation_t * p)
Definition at line 281 of file l_script.c.
 {
 #ifdef PUNCTABLE
     if (p) PS_CreatePunctuationTable(script, p);
     else  PS_CreatePunctuationTable(script, default_punctuations);
 #endif //PUNCTABLE
     if (p) script->punctuations = p;
     else script->punctuations = default_punctuations;
 } //end of the function SetScriptPunctuations
References default_punctuations, PS_CreatePunctuationTable(), and script_s::punctuations.
Referenced by LoadScriptFile(), and LoadScriptMemory().
StripDoubleQuotes()
void StripDoubleQuotes (char * string)
Definition at line 1117 of file l_script.c.
 {
     if (*string == '\"')
     {
         memmove(string, string+1, strlen(string));
     } //end if
     if (string[strlen(string)-1] == '\"')
     {
         string[strlen(string)-1] = '\0';
     } //end if
 } //end of the function StripDoubleQuotes
Referenced by AAS_ParseBSPEntities(), BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), PC_Directive_include(), PC_ReadTokenHandle(), ReadString(), and ReadWeightConfig().
StripSingleQuotes()
void StripSingleQuotes (char * string)
Definition at line 1134 of file l_script.c.
 {
     if (*string == '\'')
     {
         memmove(string, string+1, strlen(string));
     } //end if
     if (string[strlen(string)-1] == '\'')
     {
         string[strlen(string)-1] = '\0';
     } //end if
 } //end of the function StripSingleQuotes
Referenced by ReadChar().
Variable Documentation
default_punctuations
punctuation_t default_punctuations[]
Definition at line 86 of file l_script.c.
Referenced by SetScriptPunctuations().