ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_menu.c File Reference
ui_menu.c File Reference
#include "ui_local.h"
Classes
struct mainmenu_t
struct errorMessage_t
Macros
#define ID_SINGLEPLAYER 10
#define ID_MULTIPLAYER 11
#define ID_SETUP 12
#define ID_DEMOS 13
#define ID_CINEMATICS 14
#define ID_TEAMARENA 15
#define ID_MODS 16
#define ID_EXIT 17
#define MAIN_BANNER_MODEL "models/mapobjects/banner/banner5.md3"
#define MAIN_MENU_VERTICAL_SPACING 34
Functions
static void MainMenu_ExitAction (qboolean result)
void Main_MenuEvent (void *ptr, int event)
void MainMenu_Cache (void)
sfxHandle_t ErrorMessage_Key (int key)
static void Main_MenuDraw (void)
static qboolean UI_TeamArenaExists (void)
void UI_MainMenu (void)
Variables
static mainmenu_t s_main
static errorMessage_t s_errorMessage
Macro Definition Documentation
ID_CINEMATICS
#define ID_CINEMATICS 14
Definition at line 39 of file ui_menu.c.
ID_DEMOS
#define ID_DEMOS 13
Definition at line 38 of file ui_menu.c.
ID_EXIT
#define ID_EXIT 17
Definition at line 42 of file ui_menu.c.
ID_MODS
#define ID_MODS 16
Definition at line 41 of file ui_menu.c.
ID_MULTIPLAYER
#define ID_MULTIPLAYER 11
Definition at line 36 of file ui_menu.c.
ID_SETUP
#define ID_SETUP 12
Definition at line 37 of file ui_menu.c.
ID_SINGLEPLAYER
#define ID_SINGLEPLAYER 10
Definition at line 35 of file ui_menu.c.
ID_TEAMARENA
#define ID_TEAMARENA 15
Definition at line 40 of file ui_menu.c.
MAIN_BANNER_MODEL
#define MAIN_BANNER_MODEL "models/mapobjects/banner/banner5.md3"
Definition at line 44 of file ui_menu.c.
MAIN_MENU_VERTICAL_SPACING
#define MAIN_MENU_VERTICAL_SPACING 34
Definition at line 45 of file ui_menu.c.
Function Documentation
ErrorMessage_Key()
sfxHandle_t ErrorMessage_Key (int key)
Definition at line 144 of file ui_menu.c.
 {
     trap_Cvar_Set( "com_errorMessage", "" );
     UI_MainMenu();
     return (menu_null_sound);
 }
References menu_null_sound, trap_Cvar_Set(), and UI_MainMenu().
Referenced by UI_MainMenu().
Main_MenuDraw()
static void Main_MenuDraw (void) static
Definition at line 158 of file ui_menu.c.
{
     refdef_t        refdef;
     refEntity_t     ent;
     vec3_t          origin;
     vec3_t          angles;
     float           adjust;
     float           x, y, w, h;
     vec4_t          color = {0.5, 0, 0, 1};
     // setup the refdef
     memset( &refdef, 0, sizeof( refdef ) );
     refdef.rdflags = RDF_NOWORLDMODEL;
     AxisClear( refdef.viewaxis );
     x = 0;
     y = 0;
     w = 640;
     h = 120;
     UI_AdjustFrom640( &x, &y, &w, &h );
     refdef.x = x;
     refdef.y = y;
     refdef.width = w;
     refdef.height = h;
     adjust = 0; // JDC: Kenneth asked me to stop this 1.0 * sin( (float)uis.realtime / 1000 );
     refdef.fov_x = 60 + adjust;
     refdef.fov_y = 19.6875 + adjust;
     refdef.time = uis.realtime;
     origin[0] = 300;
     origin[1] = 0;
     origin[2] = -32;
     trap_R_ClearScene();
     // add the model
     memset( &ent, 0, sizeof(ent) );
     adjust = 5.0 * sin( (float)uis.realtime / 5000 );
     VectorSet( angles, 0, 180 + adjust, 0 );
     AnglesToAxis( angles, ent.axis );
     ent.hModel = s_main.bannerModel;
     VectorCopy( origin, ent.origin );
     VectorCopy( origin, ent.lightingOrigin );
     ent.renderfx = RF_LIGHTING_ORIGIN | RF_NOSHADOW;
     VectorCopy( ent.origin, ent.oldorigin );
     trap_R_AddRefEntityToScene( &ent );
     trap_R_RenderScene( &refdef );
     if (strlen(s_errorMessage.errorMessage))
     {
         UI_DrawProportionalString_AutoWrapped( 320, 192, 600, 20, s_errorMessage.errorMessage, UI_CENTER|UI_SMALLFONT|UI_DROPSHADOW, menu_text_color );
     }
     else
     {
         // standard menu drawing
         Menu_Draw( &s_main.menu );
     }
     if (uis.demoversion) {
         UI_DrawProportionalString( 320, 372, "DEMO      FOR MATURE AUDIENCES      DEMO", UI_CENTER|UI_SMALLFONT, color );
         UI_DrawString( 320, 400, "Quake III Arena(c) 1999-2000, Id Software, Inc.  All Rights Reserved", UI_CENTER|UI_SMALLFONT, color );
     } else {
         UI_DrawString( 320, 450, "Quake III Arena(c) 1999-2000, Id Software, Inc.  All Rights Reserved", UI_CENTER|UI_SMALLFONT, color );
     }
 }
References AnglesToAxis(), refEntity_t::axis, AxisClear(), mainmenu_t::bannerModel, uiStatic_t::demoversion, errorMessage_t::errorMessage, refdef_t::fov_x, refdef_t::fov_y, refdef_t::height, refEntity_t::hModel, refEntity_t::lightingOrigin, mainmenu_t::menu, Menu_Draw(), menu_text_color, refEntity_t::oldorigin, refEntity_t::origin, RDF_NOWORLDMODEL, refdef_t::rdflags, uiStatic_t::realtime, refEntity_t::renderfx, RF_LIGHTING_ORIGIN, RF_NOSHADOW, s_errorMessage, s_main, refdef_t::time, trap_R_AddRefEntityToScene(), trap_R_ClearScene(), trap_R_RenderScene(), UI_AdjustFrom640(), UI_CENTER, UI_DrawProportionalString(), UI_DrawProportionalString_AutoWrapped(), UI_DrawString(), UI_DROPSHADOW, UI_SMALLFONT, uis, VectorCopy, VectorSet, refdef_t::viewaxis, refdef_t::width, refdef_t::x, and refdef_t::y.
Referenced by UI_MainMenu().
Main_MenuEvent()
void Main_MenuEvent (void * ptr, int event)
Definition at line 93 of file ui_menu.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch( ((menucommon_s*)ptr)->id ) {
     case ID_SINGLEPLAYER:
         UI_SPLevelMenu();
         break;
     case ID_MULTIPLAYER:
         UI_ArenaServersMenu();
         break;
     case ID_SETUP:
         UI_SetupMenu();
         break;
     case ID_DEMOS:
         UI_DemosMenu();
         break;
     case ID_CINEMATICS:
         UI_CinematicsMenu();
         break;
     case ID_MODS:
         UI_ModsMenu();
         break;
     case ID_TEAMARENA:
         trap_Cvar_Set( "fs_game", BASETA);
         trap_Cmd_ExecuteText( EXEC_APPEND, "vid_restart;" );
         break;
     case ID_EXIT:
         UI_ConfirmMenu( "EXIT GAME?", 0, MainMenu_ExitAction );
         break;
     }
 }
References BASETA, EXEC_APPEND, ID_CINEMATICS, ID_DEMOS, ID_EXIT, ID_MODS, ID_MULTIPLAYER, ID_SETUP, ID_SINGLEPLAYER, ID_TEAMARENA, MainMenu_ExitAction(), QM_ACTIVATED, trap_Cmd_ExecuteText(), trap_Cvar_Set(), UI_ArenaServersMenu(), UI_CinematicsMenu(), UI_ConfirmMenu(), UI_DemosMenu(), UI_ModsMenu(), UI_SetupMenu(), and UI_SPLevelMenu().
Referenced by UI_MainMenu().
MainMenu_Cache()
void MainMenu_Cache (void)
Definition at line 140 of file ui_menu.c.
{
     s_main.bannerModel = trap_R_RegisterModel( MAIN_BANNER_MODEL );
 }
References mainmenu_t::bannerModel, MAIN_BANNER_MODEL, s_main, and trap_R_RegisterModel().
Referenced by UI_Cache_f(), and UI_MainMenu().
MainMenu_ExitAction()
static void MainMenu_ExitAction (qboolean result) static
Definition at line 78 of file ui_menu.c.
{
     if( !result ) {
         return;
     }
     UI_PopMenu();
     UI_CreditMenu();
 }
References UI_CreditMenu(), and UI_PopMenu().
Referenced by Main_MenuEvent().
UI_MainMenu()
void UI_MainMenu (void)
Definition at line 269 of file ui_menu.c.
{
     int     y;
     qboolean teamArena = qfalse;
     int     style = UI_CENTER | UI_DROPSHADOW;
     trap_Cvar_Set( "sv_killserver", "1" );
     if( !uis.demoversion && !ui_cdkeychecked.integer ) {
         char    key[17];
         trap_GetCDKey( key, sizeof(key) );
         if( trap_VerifyCDKey( key, NULL ) == qfalse ) {
             UI_CDKeyMenu();
             return;
         }
     }
     memset( &s_main, 0 ,sizeof(mainmenu_t) );
     memset( &s_errorMessage, 0 ,sizeof(errorMessage_t) );
     // com_errorMessage would need that too
     MainMenu_Cache();
     trap_Cvar_VariableStringBuffer( "com_errorMessage", s_errorMessage.errorMessage, sizeof(s_errorMessage.errorMessage) );
     if (strlen(s_errorMessage.errorMessage))
     {
         s_errorMessage.menu.draw = Main_MenuDraw;
         s_errorMessage.menu.key = ErrorMessage_Key;
         s_errorMessage.menu.fullscreen = qtrue;
         s_errorMessage.menu.wrapAround = qtrue;
         s_errorMessage.menu.showlogo = qtrue;
         trap_Key_SetCatcher( KEYCATCH_UI );
         uis.menusp = 0;
         UI_PushMenu ( &s_errorMessage.menu );
         return;
     }
     s_main.menu.draw = Main_MenuDraw;
     s_main.menu.fullscreen = qtrue;
     s_main.menu.wrapAround = qtrue;
     s_main.menu.showlogo = qtrue;
     y = 134;
     s_main.singleplayer.generic.type        = MTYPE_PTEXT;
     s_main.singleplayer.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.singleplayer.generic.x           = 320;
     s_main.singleplayer.generic.y           = y;
     s_main.singleplayer.generic.id          = ID_SINGLEPLAYER;
     s_main.singleplayer.generic.callback    = Main_MenuEvent;
     s_main.singleplayer.string              = "SINGLE PLAYER";
     s_main.singleplayer.color               = color_red;
     s_main.singleplayer.style               = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.multiplayer.generic.type         = MTYPE_PTEXT;
     s_main.multiplayer.generic.flags        = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.multiplayer.generic.x            = 320;
     s_main.multiplayer.generic.y            = y;
     s_main.multiplayer.generic.id           = ID_MULTIPLAYER;
     s_main.multiplayer.generic.callback     = Main_MenuEvent;
     s_main.multiplayer.string               = "MULTIPLAYER";
     s_main.multiplayer.color                = color_red;
     s_main.multiplayer.style                = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.setup.generic.type               = MTYPE_PTEXT;
     s_main.setup.generic.flags              = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.setup.generic.x                  = 320;
     s_main.setup.generic.y                  = y;
     s_main.setup.generic.id                 = ID_SETUP;
     s_main.setup.generic.callback           = Main_MenuEvent;
     s_main.setup.string                     = "SETUP";
     s_main.setup.color                      = color_red;
     s_main.setup.style                      = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.demos.generic.type               = MTYPE_PTEXT;
     s_main.demos.generic.flags              = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.demos.generic.x                  = 320;
     s_main.demos.generic.y                  = y;
     s_main.demos.generic.id                 = ID_DEMOS;
     s_main.demos.generic.callback           = Main_MenuEvent;
     s_main.demos.string                     = "DEMOS";
     s_main.demos.color                      = color_red;
     s_main.demos.style                      = style;
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.cinematics.generic.type          = MTYPE_PTEXT;
     s_main.cinematics.generic.flags         = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.cinematics.generic.x             = 320;
     s_main.cinematics.generic.y             = y;
     s_main.cinematics.generic.id            = ID_CINEMATICS;
     s_main.cinematics.generic.callback      = Main_MenuEvent;
     s_main.cinematics.string                = "CINEMATICS";
     s_main.cinematics.color                 = color_red;
     s_main.cinematics.style                 = style;
     if ( !uis.demoversion && UI_TeamArenaExists() ) {
         teamArena = qtrue;
         y += MAIN_MENU_VERTICAL_SPACING;
         s_main.teamArena.generic.type           = MTYPE_PTEXT;
         s_main.teamArena.generic.flags          = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
         s_main.teamArena.generic.x              = 320;
         s_main.teamArena.generic.y              = y;
         s_main.teamArena.generic.id             = ID_TEAMARENA;
         s_main.teamArena.generic.callback       = Main_MenuEvent;
         s_main.teamArena.string                 = "TEAM ARENA";
         s_main.teamArena.color                  = color_red;
         s_main.teamArena.style                  = style;
     }
     if ( !uis.demoversion ) {
         y += MAIN_MENU_VERTICAL_SPACING;
         s_main.mods.generic.type            = MTYPE_PTEXT;
         s_main.mods.generic.flags           = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
         s_main.mods.generic.x               = 320;
         s_main.mods.generic.y               = y;
         s_main.mods.generic.id              = ID_MODS;
         s_main.mods.generic.callback        = Main_MenuEvent;
         s_main.mods.string                  = "MODS";
         s_main.mods.color                   = color_red;
         s_main.mods.style                   = style;
     }
     y += MAIN_MENU_VERTICAL_SPACING;
     s_main.exit.generic.type                = MTYPE_PTEXT;
     s_main.exit.generic.flags               = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     s_main.exit.generic.x                   = 320;
     s_main.exit.generic.y                   = y;
     s_main.exit.generic.id                  = ID_EXIT;
     s_main.exit.generic.callback            = Main_MenuEvent;
     s_main.exit.string                      = "EXIT";
     s_main.exit.color                       = color_red;
     s_main.exit.style                       = style;
     Menu_AddItem( &s_main.menu, &s_main.singleplayer );
     Menu_AddItem( &s_main.menu, &s_main.multiplayer );
     Menu_AddItem( &s_main.menu, &s_main.setup );
     Menu_AddItem( &s_main.menu, &s_main.demos );
     Menu_AddItem( &s_main.menu, &s_main.cinematics );
     if (teamArena) {
         Menu_AddItem( &s_main.menu, &s_main.teamArena );
     }
     if ( !uis.demoversion ) {
         Menu_AddItem( &s_main.menu, &s_main.mods );
     }
     Menu_AddItem( &s_main.menu, &s_main.exit );
     trap_Key_SetCatcher( KEYCATCH_UI );
     uis.menusp = 0;
     UI_PushMenu ( &s_main.menu );
 }
References menucommon_s::callback, mainmenu_t::cinematics, menutext_s::color, color_red, mainmenu_t::demos, uiStatic_t::demoversion, _tag_menuframework::draw, errorMessage_t::errorMessage, ErrorMessage_Key(), mainmenu_t::exit, menucommon_s::flags, _tag_menuframework::fullscreen, menutext_s::generic, menucommon_s::id, ID_CINEMATICS, ID_DEMOS, ID_EXIT, ID_MODS, ID_MULTIPLAYER, ID_SETUP, ID_SINGLEPLAYER, ID_TEAMARENA, vmCvar_t::integer, _tag_menuframework::key, KEYCATCH_UI, MAIN_MENU_VERTICAL_SPACING, Main_MenuDraw(), Main_MenuEvent(), MainMenu_Cache(), mainmenu_t::menu, errorMessage_t::menu, Menu_AddItem(), uiStatic_t::menusp, mainmenu_t::mods, MTYPE_PTEXT, mainmenu_t::multiplayer, NULL, qfalse, QMF_CENTER_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s_errorMessage, s_main, mainmenu_t::setup, _tag_menuframework::showlogo, mainmenu_t::singleplayer, menutext_s::string, menutext_s::style, mainmenu_t::teamArena, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_GetCDKey(), trap_Key_SetCatcher(), trap_VerifyCDKey(), menucommon_s::type, ui_cdkeychecked, UI_CDKeyMenu(), UI_CENTER, UI_DROPSHADOW, UI_PushMenu(), UI_TeamArenaExists(), uis, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by ErrorMessage_Key(), and UI_SetActiveMenu().
UI_TeamArenaExists()
static qboolean UI_TeamArenaExists (void) static
Definition at line 238 of file ui_menu.c.
{
     int     numdirs;
     char    dirlist[2048];
     char    *dirptr;
   char  *descptr;
     int     i;
     int     dirlen;
     numdirs = trap_FS_GetFileList( "$modlist", "", dirlist, sizeof(dirlist) );
     dirptr  = dirlist;
     for( i = 0; i < numdirs; i++ ) {
         dirlen = strlen( dirptr ) + 1;
     descptr = dirptr + dirlen;
         if (Q_stricmp(dirptr, BASETA) == 0) {
             return qtrue;
         }
     dirptr += dirlen + strlen(descptr) + 1;
     }
     return qfalse;
 }
References BASETA, Q_stricmp(), qfalse, qtrue, and trap_FS_GetFileList().
Referenced by UI_MainMenu().
Variable Documentation
s_errorMessage
errorMessage_t s_errorMessage static
Definition at line 71 of file ui_menu.c.
Referenced by Main_MenuDraw(), and UI_MainMenu().
s_main
mainmenu_t s_main static
Definition at line 64 of file ui_menu.c.
Referenced by Main_MenuDraw(), MainMenu_Cache(), and UI_MainMenu().