ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/ai_cmd.h File Reference
ai_cmd.h File Reference
Functions
int BotMatchMessage (bot_state_t *bs, char *message)
void BotPrintTeamGoal (bot_state_t *bs)
Variables
int notleader [MAX_CLIENTS]
Function Documentation
BotMatchMessage()
int BotMatchMessage (bot_state_t * bs, char * message)
Definition at line 1789 of file ai_cmd.c.
{
     bot_match_t match;
     match.type = 0;
     //if it is an unknown message
     if (!trap_BotFindMatch(message, &match, MTCONTEXT_MISC
                                             |MTCONTEXT_INITIALTEAMCHAT
                                             |MTCONTEXT_CTF)) {
         return qfalse;
     }
     //react to the found message
     switch(match.type)
     {
         case MSG_HELP:                  //someone calling for help
         case MSG_ACCOMPANY:             //someone calling for company
         {
             BotMatch_HelpAccompany(bs, &match);
             break;
         }
         case MSG_DEFENDKEYAREA:         //teamplay defend a key area
         {
             BotMatch_DefendKeyArea(bs, &match);
             break;
         }
         case MSG_CAMP:                  //camp somewhere
         {
             BotMatch_Camp(bs, &match);
             break;
         }
         case MSG_PATROL:                //patrol between several key areas
         {
             BotMatch_Patrol(bs, &match);
             break;
         }
         //CTF & 1FCTF
         case MSG_GETFLAG:               //ctf get the enemy flag
         {
             BotMatch_GetFlag(bs, &match);
             break;
         }
 #ifdef MISSIONPACK
         //CTF & 1FCTF & Obelisk & Harvester
         case MSG_ATTACKENEMYBASE:
         {
             BotMatch_AttackEnemyBase(bs, &match);
             break;
         }
         //Harvester
         case MSG_HARVEST:
         {
             BotMatch_Harvest(bs, &match);
             break;
         }
 #endif
         //CTF & 1FCTF & Harvester
         case MSG_RUSHBASE:              //ctf rush to the base
         {
             BotMatch_RushBase(bs, &match);
             break;
         }
         //CTF & 1FCTF
         case MSG_RETURNFLAG:
         {
             BotMatch_ReturnFlag(bs, &match);
             break;
         }
         //CTF & 1FCTF & Obelisk & Harvester
         case MSG_TASKPREFERENCE:
         {
             BotMatch_TaskPreference(bs, &match);
             break;
         }
         //CTF & 1FCTF
         case MSG_CTF:
         {
             BotMatch_CTF(bs, &match);
             break;
         }
         case MSG_GETITEM:
         {
             BotMatch_GetItem(bs, &match);
             break;
         }
         case MSG_JOINSUBTEAM:           //join a sub team
         {
             BotMatch_JoinSubteam(bs, &match);
             break;
         }
         case MSG_LEAVESUBTEAM:          //leave a sub team
         {
             BotMatch_LeaveSubteam(bs, &match);
             break;
         }
         case MSG_WHICHTEAM:
         {
             BotMatch_WhichTeam(bs, &match);
             break;
         }
         case MSG_CHECKPOINT:            //remember a check point
         {
             BotMatch_CheckPoint(bs, &match);
             break;
         }
         case MSG_CREATENEWFORMATION:    //start the creation of a new formation
         {
             trap_EA_SayTeam(bs->client, "the part of my brain to create formations has been damaged");
             break;
         }
         case MSG_FORMATIONPOSITION:     //tell someone his/her position in the formation
         {
             trap_EA_SayTeam(bs->client, "the part of my brain to create formations has been damaged");
             break;
         }
         case MSG_FORMATIONSPACE:        //set the formation space
         {
             BotMatch_FormationSpace(bs, &match);
             break;
         }
         case MSG_DOFORMATION:           //form a certain formation
         {
             break;
         }
         case MSG_DISMISS:               //dismiss someone
         {
             BotMatch_Dismiss(bs, &match);
             break;
         }
         case MSG_STARTTEAMLEADERSHIP:   //someone will become the team leader
         {
             BotMatch_StartTeamLeaderShip(bs, &match);
             break;
         }
         case MSG_STOPTEAMLEADERSHIP:    //someone will stop being the team leader
         {
             BotMatch_StopTeamLeaderShip(bs, &match);
             break;
         }
         case MSG_WHOISTEAMLAEDER:
         {
             BotMatch_WhoIsTeamLeader(bs, &match);
             break;
         }
         case MSG_WHATAREYOUDOING:       //ask a bot what he/she is doing
         {
             BotMatch_WhatAreYouDoing(bs, &match);
             break;
         }
         case MSG_WHATISMYCOMMAND:
         {
             BotMatch_WhatIsMyCommand(bs, &match);
             break;
         }
         case MSG_WHEREAREYOU:
         {
             BotMatch_WhereAreYou(bs, &match);
             break;
         }
         case MSG_LEADTHEWAY:
         {
             BotMatch_LeadTheWay(bs, &match);
             break;
         }
         case MSG_KILL:
         {
             BotMatch_Kill(bs, &match);
             break;
         }
         case MSG_ENTERGAME:             //someone entered the game
         {
             BotMatch_EnterGame(bs, &match);
             break;
         }
         case MSG_NEWLEADER:
         {
             BotMatch_NewLeader(bs, &match);
             break;
         }
         case MSG_WAIT:
         {
             break;
         }
         case MSG_SUICIDE:
         {
             BotMatch_Suicide(bs, &match);
             break;
         }
         default:
         {
             BotAI_Print(PRT_MESSAGE, "unknown match type\n");
             break;
         }
     }
     return qtrue;
 }
Referenced by BotCheckConsoleMessages().
BotPrintTeamGoal()
void BotPrintTeamGoal (bot_state_t * bs)
Referenced by BotCTFSeekGoals(), BotMatch_AttackEnemyBase(), BotMatch_Camp(), BotMatch_DefendKeyArea(), BotMatch_GetFlag(), BotMatch_GetItem(), BotMatch_HelpAccompany(), BotMatch_Kill(), BotMatch_Patrol(), BotMatch_ReturnFlag(), BotMatch_RushBase(), BotVoiceChat_Camp(), BotVoiceChat_Defend(), BotVoiceChat_FollowFlagCarrier(), BotVoiceChat_FollowMe(), BotVoiceChat_GetFlag(), BotVoiceChat_Offense(), BotVoiceChat_Patrol(), and BotVoiceChat_ReturnFlag().
Variable Documentation
notleader
int notleader[MAX_CLIENTS]
Definition at line 59 of file ai_cmd.c.
Referenced by BotMatch_EnterGame(), BotMatch_StopTeamLeaderShip(), BotVoiceChat_StopLeader(), and FindHumanTeamLeader().