ioquake3 doxygen: C:/entry/dev/ioquake3/code/renderergl2/tr_dsa.h File Reference
tr_dsa.h File Reference
#include "../renderercommon/qgl.h"
Functions
void GL_BindNullTextures (void)
int GL_BindMultiTexture (GLenum texunit, GLenum target, GLuint texture)
GLvoid APIENTRY GLDSA_BindMultiTextureEXT (GLenum texunit, GLenum target, GLuint texture)
GLvoid APIENTRY GLDSA_TextureParameterfEXT (GLuint texture, GLenum target, GLenum pname, GLfloat param)
GLvoid APIENTRY GLDSA_TextureParameteriEXT (GLuint texture, GLenum target, GLenum pname, GLint param)
GLvoid APIENTRY GLDSA_TextureImage2DEXT (GLuint texture, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GLvoid APIENTRY GLDSA_TextureSubImage2DEXT (GLuint texture, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
GLvoid APIENTRY GLDSA_CopyTextureSubImage2DEXT (GLuint texture, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
GLvoid APIENTRY GLDSA_CompressedTextureImage2DEXT (GLuint texture, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
GLvoid APIENTRY GLDSA_CompressedTextureSubImage2DEXT (GLuint texture, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
GLvoid APIENTRY GLDSA_GenerateTextureMipmapEXT (GLuint texture, GLenum target)
void GL_BindNullProgram (void)
int GL_UseProgram (GLuint program)
GLvoid APIENTRY GLDSA_ProgramUniform1iEXT (GLuint program, GLint location, GLint v0)
GLvoid APIENTRY GLDSA_ProgramUniform1fEXT (GLuint program, GLint location, GLfloat v0)
GLvoid APIENTRY GLDSA_ProgramUniform2fEXT (GLuint program, GLint location, GLfloat v0, GLfloat v1)
GLvoid APIENTRY GLDSA_ProgramUniform3fEXT (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
GLvoid APIENTRY GLDSA_ProgramUniform4fEXT (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
GLvoid APIENTRY GLDSA_ProgramUniform1fvEXT (GLuint program, GLint location, GLsizei count, const GLfloat *value)
GLvoid APIENTRY GLDSA_ProgramUniformMatrix4fvEXT (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value)
void GL_BindNullFramebuffers (void)
void GL_BindFramebuffer (GLenum target, GLuint framebuffer)
void GL_BindRenderbuffer (GLuint renderbuffer)
GLvoid APIENTRY GLDSA_NamedRenderbufferStorageEXT (GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height)
GLvoid APIENTRY GLDSA_NamedRenderbufferStorageMultisampleEXT (GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
GLenum APIENTRY GLDSA_CheckNamedFramebufferStatusEXT (GLuint framebuffer, GLenum target)
GLvoid APIENTRY GLDSA_NamedFramebufferTexture2DEXT (GLuint framebuffer, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
GLvoid APIENTRY GLDSA_NamedFramebufferRenderbufferEXT (GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Function Documentation
GL_BindFramebuffer()
void GL_BindFramebuffer (GLenum target, GLuint framebuffer)
Definition at line 216 of file tr_dsa.c.
 {
     switch (target)
     {
         case GL_FRAMEBUFFER:
             if (framebuffer != glDsaState.drawFramebuffer || framebuffer != glDsaState.readFramebuffer)
             {
                 qglBindFramebuffer(target, framebuffer);
                 glDsaState.drawFramebuffer = glDsaState.readFramebuffer = framebuffer;
             }
             break;
         case GL_DRAW_FRAMEBUFFER:
             if (framebuffer != glDsaState.drawFramebuffer)
             {
                 qglBindFramebuffer(target, framebuffer);
                 glDsaState.drawFramebuffer = framebuffer;
             }
             break;
         case GL_READ_FRAMEBUFFER:
             if (framebuffer != glDsaState.readFramebuffer)
             {
                 qglBindFramebuffer(target, framebuffer);
                 glDsaState.readFramebuffer = framebuffer;
             }
             break;
     }
 }
Referenced by FBO_Bind(), FBO_FastBlit(), FBO_Init(), GLDSA_CheckNamedFramebufferStatusEXT(), GLDSA_NamedFramebufferRenderbufferEXT(), and GLDSA_NamedFramebufferTexture2DEXT().
GL_BindMultiTexture()
int GL_BindMultiTexture (GLenum texunit, GLenum target, GLuint texture)
Definition at line 64 of file tr_dsa.c.
 {
     GLuint tmu = texunit - GL_TEXTURE0;
     if (glDsaState.textures[tmu] == texture)
         return 0;
     if (target >= GL_TEXTURE_CUBE_MAP_POSITIVE_X && target <= GL_TEXTURE_CUBE_MAP_NEGATIVE_Z)
         target = GL_TEXTURE_CUBE_MAP;
     qglBindMultiTextureEXT(texunit, target, texture);
     glDsaState.textures[tmu] = texture;
     return 1;
 }
Referenced by GL_BindToTMU(), GLDSA_CompressedTextureImage2DEXT(), GLDSA_CompressedTextureSubImage2DEXT(), GLDSA_CopyTextureSubImage2DEXT(), GLDSA_GenerateTextureMipmapEXT(), GLDSA_TextureImage2DEXT(), GLDSA_TextureParameterfEXT(), GLDSA_TextureParameteriEXT(), and GLDSA_TextureSubImage2DEXT().
GL_BindNullFramebuffers()
void GL_BindNullFramebuffers (void)
Definition at line 208 of file tr_dsa.c.
 {
     qglBindFramebuffer(GL_FRAMEBUFFER, 0);
     glDsaState.drawFramebuffer = glDsaState.readFramebuffer = 0;
     qglBindRenderbuffer(GL_RENDERBUFFER, 0);
     glDsaState.renderbuffer = 0;
 }
Referenced by GL_SetDefaultState().
GL_BindNullProgram()
void GL_BindNullProgram (void)
Definition at line 144 of file tr_dsa.c.
 {
     qglUseProgram(0);
     glDsaState.program = 0;
 }
Referenced by GL_SetDefaultState(), and GLSL_ShutdownGPUShaders().
GL_BindNullTextures()
void GL_BindNullTextures (void)
Definition at line 38 of file tr_dsa.c.
 {
     int i;
     if (glRefConfig.directStateAccess)
     {
         for (i = 0; i < NUM_TEXTURE_BUNDLES; i++)
         {
             qglBindMultiTextureEXT(GL_TEXTURE0 + i, GL_TEXTURE_2D, 0);
             glDsaState.textures[i] = 0;
         }
     }
     else
     {
         for (i = 0; i < NUM_TEXTURE_BUNDLES; i++)
         {
             qglActiveTexture(GL_TEXTURE0 + i);
             qglBindTexture(GL_TEXTURE_2D, 0);
             glDsaState.textures[i] = 0;
         }
         qglActiveTexture(GL_TEXTURE0);
         glDsaState.texunit = GL_TEXTURE0;
     }
 }
Referenced by GL_SetDefaultState(), and R_DeleteTextures().
GL_BindRenderbuffer()
void GL_BindRenderbuffer (GLuint renderbuffer)
Definition at line 246 of file tr_dsa.c.
 {
     if (renderbuffer != glDsaState.renderbuffer)
     {
         qglBindRenderbuffer(GL_RENDERBUFFER, renderbuffer);
         glDsaState.renderbuffer = renderbuffer;
     }
 }
Referenced by GLDSA_NamedRenderbufferStorageEXT(), and GLDSA_NamedRenderbufferStorageMultisampleEXT().
GL_UseProgram()
int GL_UseProgram (GLuint program)
Definition at line 150 of file tr_dsa.c.
 {
     if (glDsaState.program == program)
         return 0;
     qglUseProgram(program);
     glDsaState.program = program;
     return 1;
 }
Referenced by GLDSA_ProgramUniform1fEXT(), GLDSA_ProgramUniform1fvEXT(), GLDSA_ProgramUniform1iEXT(), GLDSA_ProgramUniform2fEXT(), GLDSA_ProgramUniform3fEXT(), GLDSA_ProgramUniform4fEXT(), GLDSA_ProgramUniformMatrix4fvEXT(), and GLSL_BindProgram().
GLDSA_BindMultiTextureEXT()
GLvoid APIENTRY GLDSA_BindMultiTextureEXT (GLenum texunit, GLenum target, GLuint texture)
Definition at line 79 of file tr_dsa.c.
 {
     if (glDsaState.texunit != texunit)
     {
         qglActiveTexture(texunit);
         glDsaState.texunit = texunit;
     }
     qglBindTexture(target, texture);
 }
GLDSA_CheckNamedFramebufferStatusEXT()
GLenum APIENTRY GLDSA_CheckNamedFramebufferStatusEXT (GLuint framebuffer, GLenum target)
Definition at line 269 of file tr_dsa.c.
 {
     GL_BindFramebuffer(target, framebuffer);
     return qglCheckFramebufferStatus(target);
 }
GLDSA_CompressedTextureImage2DEXT()
GLvoid APIENTRY GLDSA_CompressedTextureImage2DEXT (GLuint texture, GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
Definition at line 123 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data);
 }
GLDSA_CompressedTextureSubImage2DEXT()
GLvoid APIENTRY GLDSA_CompressedTextureSubImage2DEXT (GLuint texture, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
Definition at line 130 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglCompressedTexSubImage2D(target, level, xoffset, yoffset, width, height, format, imageSize, data);
 }
GLDSA_CopyTextureSubImage2DEXT()
GLvoid APIENTRY GLDSA_CopyTextureSubImage2DEXT (GLuint texture, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
Definition at line 116 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height);
 }
GLDSA_GenerateTextureMipmapEXT()
GLvoid APIENTRY GLDSA_GenerateTextureMipmapEXT (GLuint texture, GLenum target)
Definition at line 138 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglGenerateMipmap(target);
 }
GLDSA_NamedFramebufferRenderbufferEXT()
GLvoid APIENTRY GLDSA_NamedFramebufferRenderbufferEXT (GLuint framebuffer, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer)
Definition at line 282 of file tr_dsa.c.
 {
     GL_BindFramebuffer(GL_FRAMEBUFFER, framebuffer);
     qglFramebufferRenderbuffer(GL_FRAMEBUFFER, attachment, renderbuffertarget, renderbuffer);
 }
GLDSA_NamedFramebufferTexture2DEXT()
GLvoid APIENTRY GLDSA_NamedFramebufferTexture2DEXT (GLuint framebuffer, GLenum attachment, GLenum textarget, GLuint texture, GLint level)
Definition at line 275 of file tr_dsa.c.
 {
     GL_BindFramebuffer(GL_FRAMEBUFFER, framebuffer);
     qglFramebufferTexture2D(GL_FRAMEBUFFER, attachment, textarget, texture, level);
 }
GLDSA_NamedRenderbufferStorageEXT()
GLvoid APIENTRY GLDSA_NamedRenderbufferStorageEXT (GLuint renderbuffer, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 255 of file tr_dsa.c.
 {
     GL_BindRenderbuffer(renderbuffer);
     qglRenderbufferStorage(GL_RENDERBUFFER, internalformat, width, height);
 }
GLDSA_NamedRenderbufferStorageMultisampleEXT()
GLvoid APIENTRY GLDSA_NamedRenderbufferStorageMultisampleEXT (GLuint renderbuffer, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height)
Definition at line 262 of file tr_dsa.c.
 {
     GL_BindRenderbuffer(renderbuffer);
     qglRenderbufferStorageMultisample(GL_RENDERBUFFER, samples, internalformat, width, height);
 }
GLDSA_ProgramUniform1fEXT()
GLvoid APIENTRY GLDSA_ProgramUniform1fEXT (GLuint program, GLint location, GLfloat v0)
Definition at line 166 of file tr_dsa.c.
 {
     GL_UseProgram(program);
     qglUniform1f(location, v0);
 }
GLDSA_ProgramUniform1fvEXT()
GLvoid APIENTRY GLDSA_ProgramUniform1fvEXT (GLuint program, GLint location, GLsizei count, const GLfloat * value)
Definition at line 193 of file tr_dsa.c.
 {
     GL_UseProgram(program);
     qglUniform1fv(location, count, value);
 }
GLDSA_ProgramUniform1iEXT()
GLvoid APIENTRY GLDSA_ProgramUniform1iEXT (GLuint program, GLint location, GLint v0)
Definition at line 160 of file tr_dsa.c.
 {
     GL_UseProgram(program);
     qglUniform1i(location, v0);
 }
GLDSA_ProgramUniform2fEXT()
GLvoid APIENTRY GLDSA_ProgramUniform2fEXT (GLuint program, GLint location, GLfloat v0, GLfloat v1)
Definition at line 172 of file tr_dsa.c.
 {
     GL_UseProgram(program);
     qglUniform2f(location, v0, v1);
 }
GLDSA_ProgramUniform3fEXT()
GLvoid APIENTRY GLDSA_ProgramUniform3fEXT (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2)
Definition at line 179 of file tr_dsa.c.
 {
     GL_UseProgram(program);
     qglUniform3f(location, v0, v1, v2);
 }
GLDSA_ProgramUniform4fEXT()
GLvoid APIENTRY GLDSA_ProgramUniform4fEXT (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3)
Definition at line 186 of file tr_dsa.c.
 {
     GL_UseProgram(program);
     qglUniform4f(location, v0, v1, v2, v3);
 }
GLDSA_ProgramUniformMatrix4fvEXT()
GLvoid APIENTRY GLDSA_ProgramUniformMatrix4fvEXT (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat * value)
Definition at line 200 of file tr_dsa.c.
 {
     GL_UseProgram(program);
     qglUniformMatrix4fv(location, count, transpose, value);
 }
GLDSA_TextureImage2DEXT()
GLvoid APIENTRY GLDSA_TextureImage2DEXT (GLuint texture, GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 102 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglTexImage2D(target, level, internalformat, width, height, border, format, type, pixels);
 }
GLDSA_TextureParameterfEXT()
GLvoid APIENTRY GLDSA_TextureParameterfEXT (GLuint texture, GLenum target, GLenum pname, GLfloat param)
Definition at line 90 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglTexParameterf(target, pname, param);
 }
GLDSA_TextureParameteriEXT()
GLvoid APIENTRY GLDSA_TextureParameteriEXT (GLuint texture, GLenum target, GLenum pname, GLint param)
Definition at line 96 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglTexParameteri(target, pname, param);
 }
GLDSA_TextureSubImage2DEXT()
GLvoid APIENTRY GLDSA_TextureSubImage2DEXT (GLuint texture, GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
Definition at line 109 of file tr_dsa.c.
 {
     GL_BindMultiTexture(glDsaState.texunit, target, texture);
     qglTexSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels);
 }