ioquake3 doxygen: C:/entry/dev/ioq3/code/renderergl2/tr_cmds.c File Reference
tr_cmds.c File Reference
#include "tr_local.h"
Macros
#define MODE_RED_CYAN 1
#define MODE_RED_BLUE 2
#define MODE_RED_GREEN 3
#define MODE_GREEN_MAGENTA 4
#define MODE_MAX MODE_GREEN_MAGENTA
Functions
void R_PerformanceCounters (void)
void R_IssueRenderCommands (qboolean runPerformanceCounters)
void R_IssuePendingRenderCommands (void)
void * R_GetCommandBufferReserved (int bytes, int reservedBytes)
void * R_GetCommandBuffer (int bytes)
void R_AddDrawSurfCmd (drawSurf_t *drawSurfs, int numDrawSurfs)
void R_AddCapShadowmapCmd (int map, int cubeSide)
void R_AddPostProcessCmd (void)
void RE_SetColor (const float *rgba)
void RE_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void R_SetColorMode (GLboolean *rgba, stereoFrame_t stereoFrame, int colormode)
void RE_BeginFrame (stereoFrame_t stereoFrame)
void RE_EndFrame (int *frontEndMsec, int *backEndMsec)
void RE_TakeVideoFrame (int width, int height, byte *captureBuffer, byte *encodeBuffer, qboolean motionJpeg)
Macro Definition Documentation
MODE_GREEN_MAGENTA
#define MODE_GREEN_MAGENTA 4
Definition at line 285 of file tr_cmds.c.
MODE_MAX
#define MODE_MAX MODE_GREEN_MAGENTA
Definition at line 286 of file tr_cmds.c.
MODE_RED_BLUE
#define MODE_RED_BLUE 2
Definition at line 283 of file tr_cmds.c.
MODE_RED_CYAN
#define MODE_RED_CYAN 1
Definition at line 282 of file tr_cmds.c.
MODE_RED_GREEN
#define MODE_RED_GREEN 3
Definition at line 284 of file tr_cmds.c.
Function Documentation
R_AddCapShadowmapCmd()
void R_AddCapShadowmapCmd (int map, int cubeSide)
Definition at line 190 of file tr_cmds.c.
{
     capShadowmapCommand_t   *cmd;
     cmd = R_GetCommandBuffer( sizeof( *cmd ) );
     if ( !cmd ) {
         return;
     }
     cmd->commandId = RC_CAPSHADOWMAP;
     cmd->map = map;
     cmd->cubeSide = cubeSide;
 }
References capShadowmapCommand_t::commandId, capShadowmapCommand_t::cubeSide, capShadowmapCommand_t::map, R_GetCommandBuffer(), and RC_CAPSHADOWMAP.
Referenced by R_RenderDlightCubemaps(), and R_RenderPshadowMaps().
R_AddDrawSurfCmd()
void R_AddDrawSurfCmd (drawSurf_t * drawSurfs, int numDrawSurfs)
Definition at line 167 of file tr_cmds.c.
{
     drawSurfsCommand_t  *cmd;
     cmd = R_GetCommandBuffer( sizeof( *cmd ) );
     if ( !cmd ) {
         return;
     }
     cmd->commandId = RC_DRAW_SURFS;
     cmd->drawSurfs = drawSurfs;
     cmd->numDrawSurfs = numDrawSurfs;
     cmd->refdef = tr.refdef;
     cmd->viewParms = tr.viewParms;
 }
References drawSurfsCommand_t::commandId, drawSurfsCommand_t::drawSurfs, drawSurfsCommand_t::numDrawSurfs, R_GetCommandBuffer(), RC_DRAW_SURFS, trGlobals_t::refdef, drawSurfsCommand_t::refdef, tr, trGlobals_t::viewParms, and drawSurfsCommand_t::viewParms.
Referenced by R_SortDrawSurfs().
R_AddPostProcessCmd()
void R_AddPostProcessCmd (void)
Definition at line 210 of file tr_cmds.c.
{
     postProcessCommand_t    *cmd;
     cmd = R_GetCommandBuffer( sizeof( *cmd ) );
     if ( !cmd ) {
         return;
     }
     cmd->commandId = RC_POSTPROCESS;
     cmd->refdef = tr.refdef;
     cmd->viewParms = tr.viewParms;
 }
References postProcessCommand_t::commandId, R_GetCommandBuffer(), RC_POSTPROCESS, trGlobals_t::refdef, postProcessCommand_t::refdef, tr, trGlobals_t::viewParms, and postProcessCommand_t::viewParms.
Referenced by RE_RenderScene().
R_GetCommandBuffer()
void* R_GetCommandBuffer (int bytes)
Definition at line 156 of file tr_cmds.c.
{
     return R_GetCommandBufferReserved( bytes, PAD( sizeof( swapBuffersCommand_t ), sizeof(void *) ) );
 }
References PAD, and R_GetCommandBufferReserved().
Referenced by R_AddCapShadowmapCmd(), R_AddDrawSurfCmd(), R_AddPostProcessCmd(), R_ExportCubemaps(), R_TakeScreenshot(), RE_BeginFrame(), RE_SetColor(), RE_StretchPic(), and RE_TakeVideoFrame().
R_GetCommandBufferReserved()
void* R_GetCommandBufferReserved (int bytes, int reservedBytes)
Definition at line 129 of file tr_cmds.c.
{
     renderCommandList_t *cmdList;
     cmdList = &backEndData->commands;
     bytes = PAD(bytes, sizeof(void *));
     // always leave room for the end of list command
     if ( cmdList->used + bytes + sizeof( int ) + reservedBytes > MAX_RENDER_COMMANDS ) {
         if ( bytes > MAX_RENDER_COMMANDS - sizeof( int ) ) {
             ri.Error( ERR_FATAL, "R_GetCommandBuffer: bad size %i", bytes );
         }
         // if we run out of room, just start dropping commands
         return NULL;
     }
     cmdList->used += bytes;
     return cmdList->cmds + cmdList->used - bytes;
 }
References backEndData, renderCommandList_t::cmds, backEndData_t::commands, ERR_FATAL, MAX_RENDER_COMMANDS, NULL, PAD, ri, and renderCommandList_t::used.
Referenced by R_GetCommandBuffer(), and RE_EndFrame().
R_IssuePendingRenderCommands()
void R_IssuePendingRenderCommands (void)
Definition at line 115 of file tr_cmds.c.
{
     if ( !tr.registered ) {
         return;
     }
     R_IssueRenderCommands( qfalse );
 }
References qfalse, R_IssueRenderCommands(), trGlobals_t::registered, and tr.
Referenced by FBO_Init(), GLSL_InitGPUShaders(), R_CreateVao(), R_CreateVao2(), R_DebugGraphics(), R_LoadLightmaps(), R_RenderMissingCubemaps(), RE_BeginFrame(), RE_BeginRegistration(), RE_EndRegistration(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterSkin(), RE_Shutdown(), and RE_StretchRaw().
R_IssueRenderCommands()
void R_IssueRenderCommands (qboolean runPerformanceCounters)
Definition at line 85 of file tr_cmds.c.
{
     renderCommandList_t *cmdList;
     cmdList = &backEndData->commands;
     assert(cmdList);
     // add an end-of-list command
     *(int *)(cmdList->cmds + cmdList->used) = RC_END_OF_LIST;
     // clear it out, in case this is a sync and not a buffer flip
     cmdList->used = 0;
     if ( runPerformanceCounters ) {
         R_PerformanceCounters();
     }
     // actually start the commands going
     if ( !r_skipBackEnd->integer ) {
         // let it start on the new batch
         RB_ExecuteRenderCommands( cmdList->cmds );
     }
 }
References backEndData, renderCommandList_t::cmds, backEndData_t::commands, cvar_s::integer, R_PerformanceCounters(), r_skipBackEnd, RB_ExecuteRenderCommands(), RC_END_OF_LIST, and renderCommandList_t::used.
Referenced by R_IssuePendingRenderCommands(), and RE_EndFrame().
R_PerformanceCounters()
void R_PerformanceCounters (void)
Definition at line 29 of file tr_cmds.c.
{
     if ( !r_speeds->integer ) {
         // clear the counters even if we aren't printing
         Com_Memset( &tr.pc, 0, sizeof( tr.pc ) );
         Com_Memset( &backEnd.pc, 0, sizeof( backEnd.pc ) );
         return;
     }
     if (r_speeds->integer == 1) {
         ri.Printf (PRINT_ALL, "%i/%i/%i shaders/batches/surfs %i leafs %i verts %i/%i tris %.2f mtex %.2f dc\n",
             backEnd.pc.c_shaders, backEnd.pc.c_surfBatches, backEnd.pc.c_surfaces, tr.pc.c_leafs, backEnd.pc.c_vertexes,
             backEnd.pc.c_indexes/3, backEnd.pc.c_totalIndexes/3,
             R_SumOfUsedImages()/(1000000.0f), backEnd.pc.c_overDraw / (float)(glConfig.vidWidth * glConfig.vidHeight) );
     } else if (r_speeds->integer == 2) {
         ri.Printf (PRINT_ALL, "(patch) %i sin %i sclip  %i sout %i bin %i bclip %i bout\n",
             tr.pc.c_sphere_cull_patch_in, tr.pc.c_sphere_cull_patch_clip, tr.pc.c_sphere_cull_patch_out,
             tr.pc.c_box_cull_patch_in, tr.pc.c_box_cull_patch_clip, tr.pc.c_box_cull_patch_out );
         ri.Printf (PRINT_ALL, "(md3) %i sin %i sclip  %i sout %i bin %i bclip %i bout\n",
             tr.pc.c_sphere_cull_md3_in, tr.pc.c_sphere_cull_md3_clip, tr.pc.c_sphere_cull_md3_out,
             tr.pc.c_box_cull_md3_in, tr.pc.c_box_cull_md3_clip, tr.pc.c_box_cull_md3_out );
     } else if (r_speeds->integer == 3) {
         ri.Printf (PRINT_ALL, "viewcluster: %i\n", tr.viewCluster );
     } else if (r_speeds->integer == 4) {
         if ( backEnd.pc.c_dlightVertexes ) {
             ri.Printf (PRINT_ALL, "dlight srf:%i  culled:%i  verts:%i  tris:%i\n",
                 tr.pc.c_dlightSurfaces, tr.pc.c_dlightSurfacesCulled,
                 backEnd.pc.c_dlightVertexes, backEnd.pc.c_dlightIndexes / 3 );
         }
     }
     else if (r_speeds->integer == 5 )
     {
         ri.Printf( PRINT_ALL, "zFar: %.0f\n", tr.viewParms.zFar );
     }
     else if (r_speeds->integer == 6 )
     {
         ri.Printf( PRINT_ALL, "flare adds:%i tests:%i renders:%i\n",
             backEnd.pc.c_flareAdds, backEnd.pc.c_flareTests, backEnd.pc.c_flareRenders );
     }
     else if (r_speeds->integer == 7 )
     {
         ri.Printf( PRINT_ALL, "VAO draws: static %i dynamic %i\n",
             backEnd.pc.c_staticVaoDraws, backEnd.pc.c_dynamicVaoDraws);
         ri.Printf( PRINT_ALL, "GLSL binds: %i  draws: gen %i light %i fog %i dlight %i\n",
             backEnd.pc.c_glslShaderBinds, backEnd.pc.c_genericDraws, backEnd.pc.c_lightallDraws, backEnd.pc.c_fogDraws, backEnd.pc.c_dlightDraws);
     }
     Com_Memset( &tr.pc, 0, sizeof( tr.pc ) );
     Com_Memset( &backEnd.pc, 0, sizeof( backEnd.pc ) );
 }
References backEnd, frontEndCounters_t::c_box_cull_md3_clip, frontEndCounters_t::c_box_cull_md3_in, frontEndCounters_t::c_box_cull_md3_out, frontEndCounters_t::c_box_cull_patch_clip, frontEndCounters_t::c_box_cull_patch_in, frontEndCounters_t::c_box_cull_patch_out, backEndCounters_t::c_dlightDraws, backEndCounters_t::c_dlightIndexes, frontEndCounters_t::c_dlightSurfaces, frontEndCounters_t::c_dlightSurfacesCulled, backEndCounters_t::c_dlightVertexes, backEndCounters_t::c_dynamicVaoDraws, backEndCounters_t::c_flareAdds, backEndCounters_t::c_flareRenders, backEndCounters_t::c_flareTests, backEndCounters_t::c_fogDraws, backEndCounters_t::c_genericDraws, backEndCounters_t::c_glslShaderBinds, backEndCounters_t::c_indexes, frontEndCounters_t::c_leafs, backEndCounters_t::c_lightallDraws, backEndCounters_t::c_overDraw, backEndCounters_t::c_shaders, frontEndCounters_t::c_sphere_cull_md3_clip, frontEndCounters_t::c_sphere_cull_md3_in, frontEndCounters_t::c_sphere_cull_md3_out, frontEndCounters_t::c_sphere_cull_patch_clip, frontEndCounters_t::c_sphere_cull_patch_in, frontEndCounters_t::c_sphere_cull_patch_out, backEndCounters_t::c_staticVaoDraws, backEndCounters_t::c_surfaces, backEndCounters_t::c_surfBatches, backEndCounters_t::c_totalIndexes, backEndCounters_t::c_vertexes, Com_Memset, glConfig, cvar_s::integer, backEndState_t::pc, trGlobals_t::pc, PRINT_ALL, r_speeds, R_SumOfUsedImages(), ri, tr, glconfig_t::vidHeight, glconfig_t::vidWidth, trGlobals_t::viewCluster, trGlobals_t::viewParms, and viewParms_t::zFar.
Referenced by R_IssueRenderCommands().
R_SetColorMode()
void R_SetColorMode (GLboolean * rgba, stereoFrame_t stereoFrame, int colormode)
Definition at line 288 of file tr_cmds.c.
 {
     rgba[0] = rgba[1] = rgba[2] = rgba[3] = GL_TRUE;
     if(colormode > MODE_MAX)
     {
         if(stereoFrame == STEREO_LEFT)
             stereoFrame = STEREO_RIGHT;
         else if(stereoFrame == STEREO_RIGHT)
             stereoFrame = STEREO_LEFT;
         colormode -= MODE_MAX;
     }
     if(colormode == MODE_GREEN_MAGENTA)
     {
         if(stereoFrame == STEREO_LEFT)
             rgba[0] = rgba[2] = GL_FALSE;
         else if(stereoFrame == STEREO_RIGHT)
             rgba[1] = GL_FALSE;
     }
     else
     {
         if(stereoFrame == STEREO_LEFT)
             rgba[1] = rgba[2] = GL_FALSE;
         else if(stereoFrame == STEREO_RIGHT)
         {
             rgba[0] = GL_FALSE;
             if(colormode == MODE_RED_BLUE)
                 rgba[1] = GL_FALSE;
             else if(colormode == MODE_RED_GREEN)
                 rgba[2] = GL_FALSE;
         }
     }
 }
References MODE_GREEN_MAGENTA, MODE_MAX, MODE_RED_BLUE, MODE_RED_GREEN, STEREO_LEFT, and STEREO_RIGHT.
Referenced by RE_BeginFrame().
RE_BeginFrame()
void RE_BeginFrame (stereoFrame_t stereoFrame)
Definition at line 334 of file tr_cmds.c.
{
     drawBufferCommand_t *cmd = NULL;
     colorMaskCommand_t *colcmd = NULL;
     if ( !tr.registered ) {
         return;
     }
     glState.finishCalled = qfalse;
     tr.frameCount++;
     tr.frameSceneNum = 0;
     //
     // do overdraw measurement
     //
     if ( r_measureOverdraw->integer )
     {
         if ( glConfig.stencilBits < 4 )
         {
             ri.Printf( PRINT_ALL, "Warning: not enough stencil bits to measure overdraw: %d\n", glConfig.stencilBits );
             ri.Cvar_Set( "r_measureOverdraw", "0" );
             r_measureOverdraw->modified = qfalse;
         }
         else if ( r_shadows->integer == 2 )
         {
             ri.Printf( PRINT_ALL, "Warning: stencil shadows and overdraw measurement are mutually exclusive\n" );
             ri.Cvar_Set( "r_measureOverdraw", "0" );
             r_measureOverdraw->modified = qfalse;
         }
         else
         {
             R_IssuePendingRenderCommands();
             qglEnable( GL_STENCIL_TEST );
             qglStencilMask( ~0U );
             qglClearStencil( 0U );
             qglStencilFunc( GL_ALWAYS, 0U, ~0U );
             qglStencilOp( GL_KEEP, GL_INCR, GL_INCR );
         }
         r_measureOverdraw->modified = qfalse;
     }
     else
     {
         // this is only reached if it was on and is now off
         if ( r_measureOverdraw->modified ) {
             R_IssuePendingRenderCommands();
             qglDisable( GL_STENCIL_TEST );
         }
         r_measureOverdraw->modified = qfalse;
     }
     //
     // texturemode stuff
     //
     if ( r_textureMode->modified ) {
         R_IssuePendingRenderCommands();
         GL_TextureMode( r_textureMode->string );
         r_textureMode->modified = qfalse;
     }
     //
     // gamma stuff
     //
     if ( r_gamma->modified ) {
         r_gamma->modified = qfalse;
         R_IssuePendingRenderCommands();
         R_SetColorMappings();
     }
     // check for errors
     if ( !r_ignoreGLErrors->integer )
     {
         int err;
         R_IssuePendingRenderCommands();
         if ((err = qglGetError()) != GL_NO_ERROR)
             ri.Error(ERR_FATAL, "RE_BeginFrame() - glGetError() failed (0x%x)!", err);
     }
     if (glConfig.stereoEnabled) {
         if( !(cmd = R_GetCommandBuffer(sizeof(*cmd))) )
             return;
         cmd->commandId = RC_DRAW_BUFFER;
         if ( stereoFrame == STEREO_LEFT ) {
             cmd->buffer = (int)GL_BACK_LEFT;
         } else if ( stereoFrame == STEREO_RIGHT ) {
             cmd->buffer = (int)GL_BACK_RIGHT;
         } else {
             ri.Error( ERR_FATAL, "RE_BeginFrame: Stereo is enabled, but stereoFrame was %i", stereoFrame );
         }
     }
     else
     {
         if(r_anaglyphMode->integer)
         {
             if(r_anaglyphMode->modified)
             {
                 // clear both, front and backbuffer.
                 qglColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);
                 backEnd.colorMask[0] = GL_FALSE;
                 backEnd.colorMask[1] = GL_FALSE;
                 backEnd.colorMask[2] = GL_FALSE;
                 backEnd.colorMask[3] = GL_FALSE;
                 if (glRefConfig.framebufferObject)
                 {
                     // clear all framebuffers
                     if (tr.msaaResolveFbo)
                     {
                         FBO_Bind(tr.msaaResolveFbo);
                         qglClear(GL_COLOR_BUFFER_BIT);
                     }
                     if (tr.renderFbo)
                     {
                         FBO_Bind(tr.renderFbo);
                         qglClear(GL_COLOR_BUFFER_BIT);
                     }
                     FBO_Bind(NULL);
                 }
                 qglDrawBuffer(GL_FRONT);
                 qglClear(GL_COLOR_BUFFER_BIT);
                 qglDrawBuffer(GL_BACK);
                 qglClear(GL_COLOR_BUFFER_BIT);
                 r_anaglyphMode->modified = qfalse;
             }
             if(stereoFrame == STEREO_LEFT)
             {
                 if( !(cmd = R_GetCommandBuffer(sizeof(*cmd))) )
                     return;
                 if( !(colcmd = R_GetCommandBuffer(sizeof(*colcmd))) )
                     return;
             }
             else if(stereoFrame == STEREO_RIGHT)
             {
                 clearDepthCommand_t *cldcmd;
                 if( !(cldcmd = R_GetCommandBuffer(sizeof(*cldcmd))) )
                     return;
                 cldcmd->commandId = RC_CLEARDEPTH;
                 if( !(colcmd = R_GetCommandBuffer(sizeof(*colcmd))) )
                     return;
             }
             else
                 ri.Error( ERR_FATAL, "RE_BeginFrame: Stereo is enabled, but stereoFrame was %i", stereoFrame );
             R_SetColorMode(colcmd->rgba, stereoFrame, r_anaglyphMode->integer);
             colcmd->commandId = RC_COLORMASK;
         }
         else
         {
             if(stereoFrame != STEREO_CENTER)
                 ri.Error( ERR_FATAL, "RE_BeginFrame: Stereo is disabled, but stereoFrame was %i", stereoFrame );
             if( !(cmd = R_GetCommandBuffer(sizeof(*cmd))) )
                 return;
         }
         if(cmd)
         {
             cmd->commandId = RC_DRAW_BUFFER;
             if(r_anaglyphMode->modified)
             {
                 qglColorMask(GL_TRUE, GL_TRUE, GL_TRUE, GL_TRUE);
                 backEnd.colorMask[0] = 0;
                 backEnd.colorMask[1] = 0;
                 backEnd.colorMask[2] = 0;
                 backEnd.colorMask[3] = 0;
                 r_anaglyphMode->modified = qfalse;
             }
             if (!Q_stricmp(r_drawBuffer->string, "GL_FRONT"))
                 cmd->buffer = (int)GL_FRONT;
             else
                 cmd->buffer = (int)GL_BACK;
         }
     }
     tr.refdef.stereoFrame = stereoFrame;
 }
References backEnd, drawBufferCommand_t::buffer, backEndState_t::colorMask, drawBufferCommand_t::commandId, colorMaskCommand_t::commandId, clearDepthCommand_t::commandId, refimport_t::Cvar_Set, ERR_FATAL, FBO_Bind(), glstate_t::finishCalled, glRefConfig_t::framebufferObject, trGlobals_t::frameCount, trGlobals_t::frameSceneNum, GL_TextureMode(), glConfig, glRefConfig, glState, int(), cvar_s::integer, cvar_s::modified, trGlobals_t::msaaResolveFbo, NULL, PRINT_ALL, Q_stricmp(), qfalse, r_anaglyphMode, r_drawBuffer, r_gamma, R_GetCommandBuffer(), r_ignoreGLErrors, R_IssuePendingRenderCommands(), r_measureOverdraw, R_SetColorMappings(), R_SetColorMode(), r_shadows, r_textureMode, RC_CLEARDEPTH, RC_COLORMASK, RC_DRAW_BUFFER, trGlobals_t::refdef, trGlobals_t::registered, trGlobals_t::renderFbo, colorMaskCommand_t::rgba, ri, glconfig_t::stencilBits, STEREO_CENTER, STEREO_LEFT, STEREO_RIGHT, glconfig_t::stereoEnabled, trRefdef_t::stereoFrame, cvar_s::string, and tr.
Referenced by GetRefAPI().
RE_EndFrame()
void RE_EndFrame (int * frontEndMsec, int * backEndMsec)
Definition at line 533 of file tr_cmds.c.
{
     swapBuffersCommand_t    *cmd;
     if ( !tr.registered ) {
         return;
     }
     cmd = R_GetCommandBufferReserved( sizeof( *cmd ), 0 );
     if ( !cmd ) {
         return;
     }
     cmd->commandId = RC_SWAP_BUFFERS;
     R_IssueRenderCommands( qtrue );
     R_InitNextFrame();
     if ( frontEndMsec ) {
         *frontEndMsec = tr.frontEndMsec;
     }
     tr.frontEndMsec = 0;
     if ( backEndMsec ) {
         *backEndMsec = backEnd.pc.msec;
     }
     backEnd.pc.msec = 0;
 }
References backEnd, swapBuffersCommand_t::commandId, trGlobals_t::frontEndMsec, backEndCounters_t::msec, backEndState_t::pc, qtrue, R_GetCommandBufferReserved(), R_InitNextFrame(), R_IssueRenderCommands(), RC_SWAP_BUFFERS, trGlobals_t::registered, and tr.
Referenced by GetRefAPI().
RE_SetColor()
void RE_SetColor (const float * rgba)
Definition at line 230 of file tr_cmds.c.
{
     setColorCommand_t   *cmd;
   if ( !tr.registered ) {
     return;
   }
     cmd = R_GetCommandBuffer( sizeof( *cmd ) );
     if ( !cmd ) {
         return;
     }
     cmd->commandId = RC_SET_COLOR;
     if ( !rgba ) {
         static float colorWhite[4] = { 1, 1, 1, 1 };
         rgba = colorWhite;
     }
     cmd->color[0] = rgba[0];
     cmd->color[1] = rgba[1];
     cmd->color[2] = rgba[2];
     cmd->color[3] = rgba[3];
 }
References setColorCommand_t::color, colorWhite, setColorCommand_t::commandId, R_GetCommandBuffer(), RC_SET_COLOR, trGlobals_t::registered, and tr.
Referenced by GetRefAPI().
RE_StretchPic()
void RE_StretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Definition at line 259 of file tr_cmds.c.
{
     stretchPicCommand_t *cmd;
   if (!tr.registered) {
     return;
   }
     cmd = R_GetCommandBuffer( sizeof( *cmd ) );
     if ( !cmd ) {
         return;
     }
     cmd->commandId = RC_STRETCH_PIC;
     cmd->shader = R_GetShaderByHandle( hShader );
     cmd->x = x;
     cmd->y = y;
     cmd->w = w;
     cmd->h = h;
     cmd->s1 = s1;
     cmd->t1 = t1;
     cmd->s2 = s2;
     cmd->t2 = t2;
 }
References stretchPicCommand_t::commandId, stretchPicCommand_t::h, R_GetCommandBuffer(), R_GetShaderByHandle(), RC_STRETCH_PIC, trGlobals_t::registered, stretchPicCommand_t::s1, stretchPicCommand_t::s2, stretchPicCommand_t::shader, stretchPicCommand_t::t1, stretchPicCommand_t::t2, tr, stretchPicCommand_t::w, stretchPicCommand_t::x, and stretchPicCommand_t::y.
Referenced by GetRefAPI().
RE_TakeVideoFrame()
void RE_TakeVideoFrame (int width, int height, byte * captureBuffer, byte * encodeBuffer, qboolean motionJpeg)
Definition at line 564 of file tr_cmds.c.
 {
     videoFrameCommand_t *cmd;
     if( !tr.registered ) {
         return;
     }
     cmd = R_GetCommandBuffer( sizeof( *cmd ) );
     if( !cmd ) {
         return;
     }
     cmd->commandId = RC_VIDEOFRAME;
     cmd->width = width;
     cmd->height = height;
     cmd->captureBuffer = captureBuffer;
     cmd->encodeBuffer = encodeBuffer;
     cmd->motionJpeg = motionJpeg;
 }
References videoFrameCommand_t::captureBuffer, videoFrameCommand_t::commandId, videoFrameCommand_t::encodeBuffer, videoFrameCommand_t::height, videoFrameCommand_t::motionJpeg, R_GetCommandBuffer(), RC_VIDEOFRAME, trGlobals_t::registered, tr, and videoFrameCommand_t::width.
Referenced by GetRefAPI().