ioquake3 doxygen: botlib_export_s Struct Reference
botlib_export_s Struct Reference
#include <botlib.h>
Public Attributes
aas_export_t aas
ea_export_t ea
ai_export_t ai
int(* BotLibSetup)(void)
int(* BotLibShutdown)(void)
int(* BotLibVarSet)(const char *var_name, const char *value)
int(* BotLibVarGet)(const char *var_name, char *value, int size)
int(* PC_AddGlobalDefine)(char *string)
int(* PC_LoadSourceHandle)(const char *filename)
int(* PC_FreeSourceHandle)(int handle)
int(* PC_ReadTokenHandle)(int handle, pc_token_t *pc_token)
int(* PC_SourceFileAndLine)(int handle, char *filename, int *line)
int(* BotLibStartFrame)(float time)
int(* BotLibLoadMap)(const char *mapname)
int(* BotLibUpdateEntity)(int ent, bot_entitystate_t *state)
int(* Test)(int parm0, char *parm1, vec3_t parm2, vec3_t parm3)
Detailed Description
Definition at line 399 of file botlib.h.
Member Data Documentation
aas
aas_export_t botlib_export_s::aas
Definition at line 402 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
ai
ai_export_t botlib_export_s::ai
Definition at line 406 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
BotLibLoadMap
int(* botlib_export_s::BotLibLoadMap) (const char *mapname)
Definition at line 426 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
BotLibSetup
int(* botlib_export_s::BotLibSetup) (void)
Definition at line 408 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_BotLibSetup().
BotLibShutdown
int(* botlib_export_s::BotLibShutdown) (void)
Definition at line 410 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_BotLibShutdown().
BotLibStartFrame
int(* botlib_export_s::BotLibStartFrame) (float time)
Definition at line 424 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
BotLibUpdateEntity
int(* botlib_export_s::BotLibUpdateEntity) (int ent, bot_entitystate_t *state)
Definition at line 428 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
BotLibVarGet
int(* botlib_export_s::BotLibVarGet) (const char *var_name, char *value, int size)
Definition at line 414 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
BotLibVarSet
int(* botlib_export_s::BotLibVarSet) (const char *var_name, const char *value)
Definition at line 412 of file botlib.h.
Referenced by BotDrawDebugPolygons(), GetBotLibAPI(), SV_BotLibSetup(), and SV_GameSystemCalls().
ea
ea_export_t botlib_export_s::ea
Definition at line 404 of file botlib.h.
Referenced by GetBotLibAPI(), and SV_GameSystemCalls().
PC_AddGlobalDefine
int(* botlib_export_s::PC_AddGlobalDefine) (char *string)
Definition at line 417 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
PC_FreeSourceHandle
int(* botlib_export_s::PC_FreeSourceHandle) (int handle)
Definition at line 419 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
PC_LoadSourceHandle
int(* botlib_export_s::PC_LoadSourceHandle) (const char *filename)
Definition at line 418 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
PC_ReadTokenHandle
int(* botlib_export_s::PC_ReadTokenHandle) (int handle, pc_token_t *pc_token)
Definition at line 420 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
PC_SourceFileAndLine
int(* botlib_export_s::PC_SourceFileAndLine) (int handle, char *filename, int *line)
Definition at line 421 of file botlib.h.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), GetBotLibAPI(), and SV_GameSystemCalls().
Test
int(* botlib_export_s::Test) (int parm0, char *parm1, vec3_t parm2, vec3_t parm3)
Definition at line 430 of file botlib.h.
Referenced by BotDrawDebugPolygons(), GetBotLibAPI(), and SV_GameSystemCalls().