ioquake3 doxygen: C:/entry/dev/ioquake3/code/client/snd_main.c File Reference
snd_main.c File Reference
#include "client.h"
#include "snd_codec.h"
#include "snd_local.h"
#include "snd_public.h"
Functions
static qboolean S_ValidSoundInterface (soundInterface_t *si)
void S_StartSound (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx)
void S_StartLocalSound (sfxHandle_t sfx, int channelNum)
void S_StartBackgroundTrack (const char *intro, const char *loop)
void S_StopBackgroundTrack (void)
void S_RawSamples (int stream, int samples, int rate, int width, int channels, const byte *data, float volume, int entityNum)
void S_StopAllSounds (void)
void S_ClearLoopingSounds (qboolean killall)
void S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void S_StopLoopingSound (int entityNum)
void S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
void S_UpdateEntityPosition (int entityNum, const vec3_t origin)
void S_Update (void)
void S_DisableSounds (void)
void S_BeginRegistration (void)
sfxHandle_t S_RegisterSound (const char *sample, qboolean compressed)
void S_ClearSoundBuffer (void)
void S_SoundInfo (void)
void S_SoundList (void)
void S_Play_f (void)
void S_Music_f (void)
void S_StopMusic_f (void)
void S_Init (void)
void S_Shutdown (void)
Variables
cvar_t * s_volume
cvar_t * s_muted
cvar_t * s_musicVolume
cvar_t * s_doppler
cvar_t * s_backend
cvar_t * s_muteWhenMinimized
cvar_t * s_muteWhenUnfocused
static soundInterface_t si
Function Documentation
S_AddLoopingSound()
void S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Definition at line 167 of file snd_main.c.
 {
     if( si.AddLoopingSound ) {
         si.AddLoopingSound( entityNum, origin, velocity, sfx );
     }
 }
Referenced by CL_CgameSystemCalls().
S_AddRealLoopingSound()
void S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Definition at line 180 of file snd_main.c.
 {
     if( si.AddRealLoopingSound ) {
         si.AddRealLoopingSound( entityNum, origin, velocity, sfx );
     }
 }
Referenced by CL_CgameSystemCalls().
S_BeginRegistration()
void S_BeginRegistration (void)
Definition at line 273 of file snd_main.c.
 {
     if( si.BeginRegistration ) {
         si.BeginRegistration( );
     }
 }
Referenced by CL_StartHunkUsers().
S_ClearLoopingSounds()
void S_ClearLoopingSounds (qboolean killall)
Definition at line 155 of file snd_main.c.
 {
     if( si.ClearLoopingSounds ) {
         si.ClearLoopingSounds( killall );
     }
 }
Referenced by CL_CgameSystemCalls().
S_ClearSoundBuffer()
void S_ClearSoundBuffer (void)
Definition at line 299 of file snd_main.c.
 {
     if( si.ClearSoundBuffer ) {
         si.ClearSoundBuffer( );
     }
 }
Referenced by CL_Disconnect(), FS_FCreateOpenPipeFile(), FS_FOpenFileAppend(), FS_Rename(), FS_SV_FOpenFileRead(), and FS_SV_Rename().
S_DisableSounds()
void S_DisableSounds (void)
Definition at line 261 of file snd_main.c.
 {
     if( si.DisableSounds ) {
         si.DisableSounds( );
     }
 }
Referenced by CL_ShutdownAll().
S_Init()
void S_Init (void)
Definition at line 472 of file snd_main.c.
 {
     cvar_t      *cv;
     qboolean    started = qfalse;
     Com_Printf( "------ Initializing Sound ------\n" );
     s_volume = Cvar_Get( "s_volume", "0.8", CVAR_ARCHIVE );
     s_musicVolume = Cvar_Get( "s_musicvolume", "0.25", CVAR_ARCHIVE );
     s_muted = Cvar_Get("s_muted", "0", CVAR_ROM);
     s_doppler = Cvar_Get( "s_doppler", "1", CVAR_ARCHIVE );
     s_backend = Cvar_Get( "s_backend", "", CVAR_ROM );
     s_muteWhenMinimized = Cvar_Get( "s_muteWhenMinimized", "0", CVAR_ARCHIVE );
     s_muteWhenUnfocused = Cvar_Get( "s_muteWhenUnfocused", "0", CVAR_ARCHIVE );
     cv = Cvar_Get( "s_initsound", "1", 0 );
     if( !cv->integer ) {
         Com_Printf( "Sound disabled.\n" );
     } else {
         S_CodecInit( );
         Cmd_AddCommand( "play", S_Play_f );
         Cmd_AddCommand( "music", S_Music_f );
         Cmd_AddCommand( "stopmusic", S_StopMusic_f );
         Cmd_AddCommand( "s_list", S_SoundList );
         Cmd_AddCommand( "s_stop", S_StopAllSounds );
         Cmd_AddCommand( "s_info", S_SoundInfo );
         cv = Cvar_Get( "s_useOpenAL", "1", CVAR_ARCHIVE | CVAR_LATCH );
         if( cv->integer ) {
             //OpenAL
             started = S_AL_Init( &si );
             Cvar_Set( "s_backend", "OpenAL" );
         }
         if( !started ) {
             started = S_Base_Init( &si );
             Cvar_Set( "s_backend", "base" );
         }
         if( started ) {
             if( !S_ValidSoundInterface( &si ) ) {
                 Com_Error( ERR_FATAL, "Sound interface invalid" );
             }
             S_SoundInfo( );
             Com_Printf( "Sound initialization successful.\n" );
         } else {
             Com_Printf( "Sound initialization failed.\n" );
         }
     }
     Com_Printf( "--------------------------------\n");
 }
Referenced by CL_StartHunkUsers().
S_Music_f()
void S_Music_f (void)
Definition at line 431 of file snd_main.c.
{
     int     c;
     if( !si.StartBackgroundTrack ) {
         return;
     }
     c = Cmd_Argc();
     if ( c == 2 ) {
         si.StartBackgroundTrack( Cmd_Argv(1), NULL );
     } else if ( c == 3 ) {
         si.StartBackgroundTrack( Cmd_Argv(1), Cmd_Argv(2) );
     } else {
         Com_Printf ("Usage: music <musicfile> [loopfile]\n");
         return;
     }
 }
Referenced by S_Init().
S_Play_f()
void S_Play_f (void)
Definition at line 401 of file snd_main.c.
                       {
     int         i;
     int         c;
     sfxHandle_t h;
     if( !si.RegisterSound || !si.StartLocalSound ) {
         return;
     }
     c = Cmd_Argc();
     if( c < 2 ) {
         Com_Printf ("Usage: play <sound filename> [sound filename] [sound filename] ...\n");
         return;
     }
     for( i = 1; i < c; i++ ) {
         h = si.RegisterSound( Cmd_Argv(i), qfalse );
         if( h ) {
             si.StartLocalSound( h, CHAN_LOCAL_SOUND );
         }
     }
 }
Referenced by S_Init().
S_RawSamples()
void S_RawSamples (int stream, int samples, int rate, int width, int channels, const byte * data, float volume, int entityNum)
Definition at line 131 of file snd_main.c.
 {
     if(si.RawSamples)
         si.RawSamples(stream, samples, rate, width, channels, data, volume, entityNum);
 }
Referenced by RoQInterrupt().
S_RegisterSound()
sfxHandle_t S_RegisterSound (const char * sample, qboolean compressed)
Definition at line 285 of file snd_main.c.
 {
     if( si.RegisterSound ) {
         return si.RegisterSound( sample, compressed );
     } else {
         return 0;
     }
 }
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_Respatialize()
void S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
Definition at line 205 of file snd_main.c.
 {
     if( si.Respatialize ) {
         si.Respatialize( entityNum, origin, axis, inwater );
     }
 }
Referenced by CL_CgameSystemCalls().
S_Shutdown()
void S_Shutdown (void)
Definition at line 533 of file snd_main.c.
 {
     if( si.Shutdown ) {
         si.Shutdown( );
     }
     Com_Memset( &si, 0, sizeof( soundInterface_t ) );
     Cmd_RemoveCommand( "play" );
     Cmd_RemoveCommand( "music");
     Cmd_RemoveCommand( "stopmusic");
     Cmd_RemoveCommand( "s_list" );
     Cmd_RemoveCommand( "s_stop" );
     Cmd_RemoveCommand( "s_info" );
     S_CodecShutdown( );
 }
Referenced by CL_Snd_Shutdown().
S_SoundInfo()
void S_SoundInfo (void)
Definition at line 311 of file snd_main.c.
 {
     if( si.SoundInfo ) {
         si.SoundInfo( );
     }
 }
Referenced by S_Init().
S_SoundList()
void S_SoundList (void)
Definition at line 323 of file snd_main.c.
 {
     if( si.SoundList ) {
         si.SoundList( );
     }
 }
Referenced by S_Init().
S_StartBackgroundTrack()
void S_StartBackgroundTrack (const char * intro, const char * loop)
Definition at line 107 of file snd_main.c.
 {
     if( si.StartBackgroundTrack ) {
         si.StartBackgroundTrack( intro, loop );
     }
 }
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_StartLocalSound()
void S_StartLocalSound (sfxHandle_t sfx, int channelNum)
Definition at line 95 of file snd_main.c.
 {
     if( si.StartLocalSound ) {
         si.StartLocalSound( sfx, channelNum );
     }
 }
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_StartSound()
void S_StartSound (vec3_t origin, int entnum, int entchannel, sfxHandle_t sfx)
Definition at line 83 of file snd_main.c.
 {
     if( si.StartSound ) {
         si.StartSound( origin, entnum, entchannel, sfx );
     }
 }
Referenced by CL_CgameSystemCalls().
S_StopAllSounds()
void S_StopAllSounds (void)
Definition at line 143 of file snd_main.c.
 {
     if( si.StopAllSounds ) {
         si.StopAllSounds( );
     }
 }
Referenced by CL_Frame(), CL_KeyDownEvent(), CL_PlayCinematic_f(), CL_Vid_Restart_f(), S_Init(), SCR_DrawScreenField(), and SCR_StopCinematic().
S_StopBackgroundTrack()
void S_StopBackgroundTrack (void)
Definition at line 119 of file snd_main.c.
 {
     if( si.StopBackgroundTrack ) {
         si.StopBackgroundTrack( );
     }
 }
Referenced by CL_CgameSystemCalls(), and CL_UISystemCalls().
S_StopLoopingSound()
void S_StopLoopingSound (int entityNum)
Definition at line 193 of file snd_main.c.
 {
     if( si.StopLoopingSound ) {
         si.StopLoopingSound( entityNum );
     }
 }
Referenced by CL_CgameSystemCalls().
S_StopMusic_f()
void S_StopMusic_f (void)
Definition at line 456 of file snd_main.c.
 {
     if(!si.StopBackgroundTrack)
         return;
     si.StopBackgroundTrack();
 }
Referenced by S_Init().
S_Update()
void S_Update (void)
Definition at line 230 of file snd_main.c.
 {
     if(s_muted->integer)
     {
         if(!(s_muteWhenMinimized->integer && com_minimized->integer) &&
            !(s_muteWhenUnfocused->integer && com_unfocused->integer))
         {
             s_muted->integer = qfalse;
             s_muted->modified = qtrue;
         }
     }
     else
     {
         if((s_muteWhenMinimized->integer && com_minimized->integer) ||
            (s_muteWhenUnfocused->integer && com_unfocused->integer))
         {
             s_muted->integer = qtrue;
             s_muted->modified = qtrue;
         }
     }
     if( si.Update ) {
         si.Update( );
     }
 }
Referenced by CL_Frame(), and RoQInterrupt().
S_UpdateEntityPosition()
void S_UpdateEntityPosition (int entityNum, const vec3_t origin)
Definition at line 218 of file snd_main.c.
 {
     if( si.UpdateEntityPosition ) {
         si.UpdateEntityPosition( entityNum, origin );
     }
 }
Referenced by CL_CgameSystemCalls().
S_ValidSoundInterface()
static qboolean S_ValidSoundInterface (soundInterface_t * si) static
Definition at line 44 of file snd_main.c.
 {
     if( !si->Shutdown ) return qfalse;
     if( !si->StartSound ) return qfalse;
     if( !si->StartLocalSound ) return qfalse;
     if( !si->StartBackgroundTrack ) return qfalse;
     if( !si->StopBackgroundTrack ) return qfalse;
     if( !si->RawSamples ) return qfalse;
     if( !si->StopAllSounds ) return qfalse;
     if( !si->ClearLoopingSounds ) return qfalse;
     if( !si->AddLoopingSound ) return qfalse;
     if( !si->AddRealLoopingSound ) return qfalse;
     if( !si->StopLoopingSound ) return qfalse;
     if( !si->Respatialize ) return qfalse;
     if( !si->UpdateEntityPosition ) return qfalse;
     if( !si->Update ) return qfalse;
     if( !si->DisableSounds ) return qfalse;
     if( !si->BeginRegistration ) return qfalse;
     if( !si->RegisterSound ) return qfalse;
     if( !si->ClearSoundBuffer ) return qfalse;
     if( !si->SoundInfo ) return qfalse;
     if( !si->SoundList ) return qfalse;
 #ifdef USE_VOIP
     if( !si->StartCapture ) return qfalse;
     if( !si->AvailableCaptureSamples ) return qfalse;
     if( !si->Capture ) return qfalse;
     if( !si->StopCapture ) return qfalse;
     if( !si->MasterGain ) return qfalse;
 #endif
     return qtrue;
 }
Referenced by S_Init().
Variable Documentation
s_backend
cvar_t* s_backend
Definition at line 33 of file snd_main.c.
Referenced by S_Init().
s_doppler
cvar_t* s_doppler
Definition at line 32 of file snd_main.c.
Referenced by S_Base_AddLoopingSound(), and S_Init().
s_musicVolume
cvar_t* s_musicVolume
Definition at line 31 of file snd_main.c.
Referenced by S_Init(), and S_UpdateBackgroundTrack().
s_muted
cvar_t* s_muted
Definition at line 30 of file snd_main.c.
Referenced by S_Base_RawSamples(), S_Init(), S_PaintChannels(), and S_Update().
s_muteWhenMinimized
cvar_t* s_muteWhenMinimized
Definition at line 34 of file snd_main.c.
Referenced by S_Init(), and S_Update().
s_muteWhenUnfocused
cvar_t* s_muteWhenUnfocused
Definition at line 35 of file snd_main.c.
Referenced by S_Init(), and S_Update().
s_volume
cvar_t* s_volume
Definition at line 29 of file snd_main.c.
Referenced by S_Base_RawSamples(), S_Init(), and S_PaintChannels().
si
soundInterface_t si static
Definition at line 37 of file snd_main.c.
Referenced by DoFCBI(), DoFCBIQuick(), DoLinear(), ParseSurfaceParm(), S_AddLoopingSound(), S_AddRealLoopingSound(), S_AL_Init(), S_Base_Init(), S_BeginRegistration(), S_ClearLoopingSounds(), S_ClearSoundBuffer(), S_DisableSounds(), S_Init(), S_Music_f(), S_Play_f(), S_RawSamples(), S_RegisterSound(), S_Respatialize(), S_Shutdown(), S_SoundInfo(), S_SoundList(), S_StartBackgroundTrack(), S_StartLocalSound(), S_StartSound(), S_StopAllSounds(), S_StopBackgroundTrack(), S_StopLoopingSound(), S_StopMusic_f(), S_Update(), S_UpdateEntityPosition(), S_ValidSoundInterface(), Scroll_ListBox_AutoFunc(), Scroll_ListBox_ThumbFunc(), and Scroll_Slider_ThumbFunc().