ioquake3 doxygen: C:/entry/dev/ioq3/code/server/server.h File Reference
server.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "../game/g_public.h"
#include "../game/bg_public.h"
Classes
struct svEntity_s
struct server_t
struct clientSnapshot_t
struct netchan_buffer_s
struct client_s
struct challenge_t
struct serverStatic_t
struct serverBan_t
struct leakyBucket_s
Macros
#define PERS_SCORE 0
#define MAX_ENT_CLUSTERS 16
#define MAX_CHALLENGES 2048
#define MAX_CHALLENGES_MULTI (MAX_CHALLENGES / 2)
#define AUTHORIZE_TIMEOUT 5000
#define SERVER_MAXBANS 1024
Typedefs
typedef struct svEntity_s svEntity_t
typedef struct netchan_buffer_s netchan_buffer_t
typedef struct client_s client_t
typedef struct leakyBucket_s leakyBucket_t
Enumerations
enum serverState_t { SS_DEAD, SS_LOADING, SS_GAME }
enum clientState_t {
CS_FREE, CS_ZOMBIE, CS_CONNECTED, CS_PRIMED,
CS_ACTIVE
}
Functions
qboolean SVC_RateLimit (leakyBucket_t *bucket, int burst, int period)
qboolean SVC_RateLimitAddress (netadr_t from, int burst, int period)
void SV_FinalMessage (char *message)
void QDECL SV_SendServerCommand (client_t *cl, const char *fmt,...) __attribute__((format(printf
void QDECL void SV_AddOperatorCommands (void)
void SV_RemoveOperatorCommands (void)
void SV_MasterShutdown (void)
int SV_RateMsec (client_t *client)
void SV_SetConfigstring (int index, const char *val)
void SV_GetConfigstring (int index, char *buffer, int bufferSize)
void SV_UpdateConfigstrings (client_t *client)
void SV_SetUserinfo (int index, const char *val)
void SV_GetUserinfo (int index, char *buffer, int bufferSize)
void SV_ChangeMaxClients (void)
void SV_SpawnServer (char *server, qboolean killBots)
void SV_GetChallenge (netadr_t from)
void SV_DirectConnect (netadr_t from)
void SV_AuthorizeIpPacket (netadr_t from)
void SV_ExecuteClientMessage (client_t *cl, msg_t *msg)
void SV_UserinfoChanged (client_t *cl)
void SV_ClientEnterWorld (client_t *client, usercmd_t *cmd)
void SV_FreeClient (client_t *client)
void SV_DropClient (client_t *drop, const char *reason)
void SV_ExecuteClientCommand (client_t *cl, const char *s, qboolean clientOK)
void SV_ClientThink (client_t *cl, usercmd_t *cmd)
int SV_WriteDownloadToClient (client_t *cl, msg_t *msg)
int SV_SendDownloadMessages (void)
int SV_SendQueuedMessages (void)
void SV_Heartbeat_f (void)
void SV_AddServerCommand (client_t *client, const char *cmd)
void SV_UpdateServerCommandsToClient (client_t *client, msg_t *msg)
void SV_WriteFrameToClient (client_t *client, msg_t *msg)
void SV_SendMessageToClient (msg_t *msg, client_t *client)
void SV_SendClientMessages (void)
void SV_SendClientSnapshot (client_t *client)
int SV_NumForGentity (sharedEntity_t *ent)
sharedEntity_t * SV_GentityNum (int num)
playerState_t * SV_GameClientNum (int num)
svEntity_t * SV_SvEntityForGentity (sharedEntity_t *gEnt)
sharedEntity_t * SV_GEntityForSvEntity (svEntity_t *svEnt)
void SV_InitGameProgs (void)
void SV_ShutdownGameProgs (void)
void SV_RestartGameProgs (void)
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
void SV_BotFrame (int time)
int SV_BotAllocateClient (void)
void SV_BotFreeClient (int clientNum)
void SV_BotInitCvars (void)
int SV_BotLibSetup (void)
int SV_BotLibShutdown (void)
int SV_BotGetSnapshotEntity (int client, int ent)
int SV_BotGetConsoleMessage (int client, char *buf, int size)
int BotImport_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
void BotImport_DebugPolygonDelete (int id)
void SV_BotInitBotLib (void)
void SV_ClearWorld (void)
void SV_UnlinkEntity (sharedEntity_t *ent)
void SV_LinkEntity (sharedEntity_t *ent)
clipHandle_t SV_ClipHandleForEntity (const sharedEntity_t *ent)
void SV_SectorList_f (void)
int SV_AreaEntities (const vec3_t mins, const vec3_t maxs, int *entityList, int maxcount)
int SV_PointContents (const vec3_t p, int passEntityNum)
void SV_Trace (trace_t *results, const vec3_t start, vec3_t mins, vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, int capsule)
void SV_ClipToEntity (trace_t *trace, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int entityNum, int contentmask, int capsule)
void SV_Netchan_Transmit (client_t *client, msg_t *msg)
int SV_Netchan_TransmitNextFragment (client_t *client)
qboolean SV_Netchan_Process (client_t *client, msg_t *msg)
void SV_Netchan_FreeQueue (client_t *client)
Variables
serverStatic_t svs
server_t sv
vm_t * gvm
cvar_t * sv_fps
cvar_t * sv_timeout
cvar_t * sv_zombietime
cvar_t * sv_rconPassword
cvar_t * sv_privatePassword
cvar_t * sv_allowDownload
cvar_t * sv_maxclients
cvar_t * sv_privateClients
cvar_t * sv_hostname
cvar_t * sv_master [MAX_MASTER_SERVERS]
cvar_t * sv_reconnectlimit
cvar_t * sv_showloss
cvar_t * sv_padPackets
cvar_t * sv_killserver
cvar_t * sv_mapname
cvar_t * sv_mapChecksum
cvar_t * sv_serverid
cvar_t * sv_minRate
cvar_t * sv_maxRate
cvar_t * sv_dlRate
cvar_t * sv_minPing
cvar_t * sv_maxPing
cvar_t * sv_gametype
cvar_t * sv_pure
cvar_t * sv_floodProtect
cvar_t * sv_lanForceRate
cvar_t * sv_strictAuth
cvar_t * sv_banFile
serverBan_t serverBans [SERVER_MAXBANS]
int serverBansCount
leakyBucket_t outboundLeakyBucket
Macro Definition Documentation
AUTHORIZE_TIMEOUT
#define AUTHORIZE_TIMEOUT 5000
Definition at line 216 of file server.h.
MAX_CHALLENGES
#define MAX_CHALLENGES 2048
Definition at line 210 of file server.h.
MAX_CHALLENGES_MULTI
#define MAX_CHALLENGES_MULTI (MAX_CHALLENGES / 2)
Definition at line 214 of file server.h.
MAX_ENT_CLUSTERS
#define MAX_ENT_CLUSTERS 16
Definition at line 34 of file server.h.
PERS_SCORE
#define PERS_SCORE 0
Definition at line 31 of file server.h.
SERVER_MAXBANS
#define SERVER_MAXBANS 1024
Definition at line 250 of file server.h.
Typedef Documentation
client_t
typedef struct client_s client_t
leakyBucket_t
typedef struct leakyBucket_s leakyBucket_t
Definition at line 313 of file server.h.
netchan_buffer_t
typedef struct netchan_buffer_s netchan_buffer_t
svEntity_t
typedef struct svEntity_s svEntity_t
Enumeration Type Documentation
clientState_t
enum clientState_t
Enumerator
CS_FREE
CS_ZOMBIE
CS_CONNECTED
CS_PRIMED
CS_ACTIVE
Definition at line 115 of file server.h.
              {
     CS_FREE,        // can be reused for a new connection
     CS_ZOMBIE,      // client has been disconnected, but don't reuse
                     // connection for a couple seconds
     CS_CONNECTED,   // has been assigned to a client_t, but no gamestate yet
     CS_PRIMED,      // gamestate has been sent, but client hasn't sent a usercmd
     CS_ACTIVE       // client is fully in game
 } clientState_t;
serverState_t
enum serverState_t
Enumerator
SS_DEAD
SS_LOADING
SS_GAME
Definition at line 63 of file server.h.
              {
     SS_DEAD,            // no map loaded
     SS_LOADING,         // spawning level entities
     SS_GAME             // actively running
 } serverState_t;
Function Documentation
BotImport_DebugPolygonCreate()
int BotImport_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
Definition at line 319 of file sv_bot.c.
{
     bot_debugpoly_t *poly;
     int i;
     if (!debugpolygons)
         return 0;
     for (i = 1; i < bot_maxdebugpolys; i++)     {
         if (!debugpolygons[i].inuse)
             break;
     }
     if (i >= bot_maxdebugpolys)
         return 0;
     poly = &debugpolygons[i];
     poly->inuse = qtrue;
     poly->color = color;
     poly->numPoints = numPoints;
     Com_Memcpy(poly->points, points, numPoints * sizeof(vec3_t));
     //
     return i;
 }
Referenced by BotImport_DebugLineCreate(), SV_BotInitBotLib(), and SV_GameSystemCalls().
BotImport_DebugPolygonDelete()
void BotImport_DebugPolygonDelete (int id)
Definition at line 362 of file sv_bot.c.
 {
     if (!debugpolygons) return;
     debugpolygons[id].inuse = qfalse;
 }
Referenced by BotImport_DebugLineDelete(), SV_BotInitBotLib(), and SV_GameSystemCalls().
SV_AddOperatorCommands()
void QDECL void SV_AddOperatorCommands (void)
Definition at line 1520 of file sv_ccmds.c.
{
     static qboolean initialized;
     if ( initialized ) {
         return;
     }
     initialized = qtrue;
     Cmd_AddCommand ("heartbeat", SV_Heartbeat_f);
     Cmd_AddCommand ("kick", SV_Kick_f);
 #ifndef STANDALONE
     if(!com_standalone->integer)
     {
         Cmd_AddCommand ("banUser", SV_Ban_f);
         Cmd_AddCommand ("banClient", SV_BanNum_f);
     }
 #endif
     Cmd_AddCommand ("kickbots", SV_KickBots_f);
     Cmd_AddCommand ("kickall", SV_KickAll_f);
     Cmd_AddCommand ("kicknum", SV_KickNum_f);
     Cmd_AddCommand ("clientkick", SV_KickNum_f); // Legacy command
     Cmd_AddCommand ("status", SV_Status_f);
     Cmd_AddCommand ("serverinfo", SV_Serverinfo_f);
     Cmd_AddCommand ("systeminfo", SV_Systeminfo_f);
     Cmd_AddCommand ("dumpuser", SV_DumpUser_f);
     Cmd_AddCommand ("map_restart", SV_MapRestart_f);
     Cmd_AddCommand ("sectorlist", SV_SectorList_f);
     Cmd_AddCommand ("map", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "map", SV_CompleteMapName );
 #ifndef PRE_RELEASE_DEMO
     Cmd_AddCommand ("devmap", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "devmap", SV_CompleteMapName );
     Cmd_AddCommand ("spmap", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "spmap", SV_CompleteMapName );
     Cmd_AddCommand ("spdevmap", SV_Map_f);
     Cmd_SetCommandCompletionFunc( "spdevmap", SV_CompleteMapName );
 #endif
     Cmd_AddCommand ("killserver", SV_KillServer_f);
     if( com_dedicated->integer ) {
         Cmd_AddCommand ("say", SV_ConSay_f);
         Cmd_AddCommand ("tell", SV_ConTell_f);
         Cmd_AddCommand ("sayto", SV_ConSayto_f);
         Cmd_SetCommandCompletionFunc( "sayto", SV_CompletePlayerName );
     }
     Cmd_AddCommand("rehashbans", SV_RehashBans_f);
     Cmd_AddCommand("listbans", SV_ListBans_f);
     Cmd_AddCommand("banaddr", SV_BanAddr_f);
     Cmd_AddCommand("exceptaddr", SV_ExceptAddr_f);
     Cmd_AddCommand("bandel", SV_BanDel_f);
     Cmd_AddCommand("exceptdel", SV_ExceptDel_f);
     Cmd_AddCommand("flushbans", SV_FlushBans_f);
 }
Referenced by SV_Init().
SV_AddServerCommand()
void SV_AddServerCommand (client_t * client, const char * cmd)
Definition at line 143 of file sv_main.c.
{
     int     index, i;
     // this is very ugly but it's also a waste to for instance send multiple config string updates
     // for the same config string index in one snapshot
 //  if ( SV_ReplacePendingServerCommands( client, cmd ) ) {
 //      return;
 //  }
     // do not send commands until the gamestate has been sent
     if( client->state < CS_PRIMED )
         return;
     client->reliableSequence++;
     // if we would be losing an old command that hasn't been acknowledged,
     // we must drop the connection
     // we check == instead of >= so a broadcast print added by SV_DropClient()
     // doesn't cause a recursive drop client
     if ( client->reliableSequence - client->reliableAcknowledge == MAX_RELIABLE_COMMANDS + 1 ) {
         Com_Printf( "===== pending server commands =====\n" );
         for ( i = client->reliableAcknowledge + 1 ; i <= client->reliableSequence ; i++ ) {
             Com_Printf( "cmd %5d: %s\n", i, client->reliableCommands[ i & (MAX_RELIABLE_COMMANDS-1) ] );
         }
         Com_Printf( "cmd %5d: %s\n", i, cmd );
         SV_DropClient( client, "Server command overflow" );
         return;
     }
     index = client->reliableSequence & ( MAX_RELIABLE_COMMANDS - 1 );
     Q_strncpyz( client->reliableCommands[ index ], cmd, sizeof( client->reliableCommands[ index ] ) );
 }
Referenced by SV_MapRestart_f(), and SV_SendServerCommand().
SV_AreaEntities()
int SV_AreaEntities (const vec3_t mins, const vec3_t maxs, int * entityList, int maxcount)
Definition at line 426 of file sv_world.c.
{
     areaParms_t     ap;
     ap.mins = mins;
     ap.maxs = maxs;
     ap.list = entityList;
     ap.count = 0;
     ap.maxcount = maxcount;
     SV_AreaEntities_r( sv_worldSectors, &ap );
     return ap.count;
 }
Referenced by SV_ClipMoveToEntities(), SV_GameSystemCalls(), and SV_PointContents().
SV_AuthorizeIpPacket()
void SV_AuthorizeIpPacket (netadr_t from)
Definition at line 214 of file sv_client.c.
{
     int     challenge;
     int     i;
     char    *s;
     char    *r;
     challenge_t *challengeptr;
     if ( !NET_CompareBaseAdr( from, svs.authorizeAddress ) ) {
         Com_Printf( "SV_AuthorizeIpPacket: not from authorize server\n" );
         return;
     }
     challenge = atoi( Cmd_Argv( 1 ) );
     for (i = 0 ; i < MAX_CHALLENGES ; i++) {
         if ( svs.challenges[i].challenge == challenge ) {
             break;
         }
     }
     if ( i == MAX_CHALLENGES ) {
         Com_Printf( "SV_AuthorizeIpPacket: challenge not found\n" );
         return;
     }
     challengeptr = &svs.challenges[i];
     // send a packet back to the original client
     challengeptr->pingTime = svs.time;
     s = Cmd_Argv( 2 );
     r = Cmd_Argv( 3 );          // reason
     if ( !Q_stricmp( s, "demo" ) ) {
         // they are a demo client trying to connect to a real server
         NET_OutOfBandPrint( NS_SERVER, challengeptr->adr, "print\nServer is not a demo server\n" );
         // clear the challenge record so it won't timeout and let them through
         Com_Memset( challengeptr, 0, sizeof( *challengeptr ) );
         return;
     }
     if ( !Q_stricmp( s, "accept" ) ) {
         NET_OutOfBandPrint(NS_SERVER, challengeptr->adr,
             "challengeResponse %d %d %d", challengeptr->challenge, challengeptr->clientChallenge, com_protocol->integer);
         return;
     }
     if ( !Q_stricmp( s, "unknown" ) ) {
         if (!r) {
             NET_OutOfBandPrint( NS_SERVER, challengeptr->adr, "print\nAwaiting CD key authorization\n" );
         } else {
             NET_OutOfBandPrint( NS_SERVER, challengeptr->adr, "print\n%s\n", r);
         }
         // clear the challenge record so it won't timeout and let them through
         Com_Memset( challengeptr, 0, sizeof( *challengeptr ) );
         return;
     }
     // authorization failed
     if (!r) {
         NET_OutOfBandPrint( NS_SERVER, challengeptr->adr, "print\nSomeone is using this CD Key\n" );
     } else {
         NET_OutOfBandPrint( NS_SERVER, challengeptr->adr, "print\n%s\n", r );
     }
     // clear the challenge record so it won't timeout and let them through
     Com_Memset( challengeptr, 0, sizeof(*challengeptr) );
 }
Referenced by SV_ConnectionlessPacket().
SV_BotAllocateClient()
int SV_BotAllocateClient (void)
Definition at line 47 of file sv_bot.c.
{
     int         i;
     client_t    *cl;
     // find a client slot
     for ( i = 0, cl = svs.clients; i < sv_maxclients->integer; i++, cl++ ) {
         if ( cl->state == CS_FREE ) {
             break;
         }
     }
     if ( i == sv_maxclients->integer ) {
         return -1;
     }
     cl->gentity = SV_GentityNum( i );
     cl->gentity->s.number = i;
     cl->state = CS_ACTIVE;
     cl->lastPacketTime = svs.time;
     cl->netchan.remoteAddress.type = NA_BOT;
     cl->rate = 16384;
     return i;
 }
Referenced by SV_GameSystemCalls().
SV_BotFrame()
void SV_BotFrame (int time)
Definition at line 434 of file sv_bot.c.
{
     if (!bot_enable) return;
     //NOTE: maybe the game is already shutdown
     if (!gvm) return;
     VM_Call( gvm, BOTAI_START_FRAME, time );
 }
SV_BotFreeClient()
void SV_BotFreeClient (int clientNum)
Definition at line 77 of file sv_bot.c.
{
     client_t    *cl;
     if ( clientNum < 0 || clientNum >= sv_maxclients->integer ) {
         Com_Error( ERR_DROP, "SV_BotFreeClient: bad clientNum: %i", clientNum );
     }
     cl = &svs.clients[clientNum];
     cl->state = CS_FREE;
     cl->name[0] = 0;
     if ( cl->gentity ) {
         cl->gentity->r.svFlags &= ~SVF_BOT;
     }
 }
Referenced by SV_DropClient(), and SV_GameSystemCalls().
SV_BotGetConsoleMessage()
int SV_BotGetConsoleMessage (int client, char * buf, int size)
Definition at line 574 of file sv_bot.c.
 {
     client_t    *cl;
     int         index;
     cl = &svs.clients[client];
     cl->lastPacketTime = svs.time;
     if ( cl->reliableAcknowledge == cl->reliableSequence ) {
         return qfalse;
     }
     cl->reliableAcknowledge++;
     index = cl->reliableAcknowledge & ( MAX_RELIABLE_COMMANDS - 1 );
     if ( !cl->reliableCommands[index][0] ) {
         return qfalse;
     }
     Q_strncpyz( buf, cl->reliableCommands[index], size );
     return qtrue;
 }
Referenced by SV_GameSystemCalls().
SV_BotGetSnapshotEntity()
int SV_BotGetSnapshotEntity (int client, int ent)
Definition at line 624 of file sv_bot.c.
{
     client_t            *cl;
     clientSnapshot_t    *frame;
     cl = &svs.clients[client];
     frame = &cl->frames[cl->netchan.outgoingSequence & PACKET_MASK];
     if (sequence < 0 || sequence >= frame->num_entities) {
         return -1;
     }
     return svs.snapshotEntities[(frame->first_entity + sequence) % svs.numSnapshotEntities].number;
 }
Referenced by SV_GameSystemCalls().
SV_BotInitBotLib()
void SV_BotInitBotLib (void)
Definition at line 522 of file sv_bot.c.
{
     botlib_import_t botlib_import;
     if (debugpolygons) Z_Free(debugpolygons);
     bot_maxdebugpolys = Cvar_VariableIntegerValue("bot_maxdebugpolys");
     debugpolygons = Z_Malloc(sizeof(bot_debugpoly_t) * bot_maxdebugpolys);
     botlib_import.Print = BotImport_Print;
     botlib_import.Trace = BotImport_Trace;
     botlib_import.EntityTrace = BotImport_EntityTrace;
     botlib_import.PointContents = BotImport_PointContents;
     botlib_import.inPVS = BotImport_inPVS;
     botlib_import.BSPEntityData = BotImport_BSPEntityData;
     botlib_import.BSPModelMinsMaxsOrigin = BotImport_BSPModelMinsMaxsOrigin;
     botlib_import.BotClientCommand = BotClientCommand;
     //memory management
     botlib_import.GetMemory = BotImport_GetMemory;
     botlib_import.FreeMemory = BotImport_FreeMemory;
     botlib_import.AvailableMemory = Z_AvailableMemory;
     botlib_import.HunkAlloc = BotImport_HunkAlloc;
     // file system access
     botlib_import.FS_FOpenFile = FS_FOpenFileByMode;
     botlib_import.FS_Read = FS_Read;
     botlib_import.FS_Write = FS_Write;
     botlib_import.FS_FCloseFile = FS_FCloseFile;
     botlib_import.FS_Seek = FS_Seek;
     //debug lines
     botlib_import.DebugLineCreate = BotImport_DebugLineCreate;
     botlib_import.DebugLineDelete = BotImport_DebugLineDelete;
     botlib_import.DebugLineShow = BotImport_DebugLineShow;
     //debug polygons
     botlib_import.DebugPolygonCreate = BotImport_DebugPolygonCreate;
     botlib_import.DebugPolygonDelete = BotImport_DebugPolygonDelete;
     botlib_export = (botlib_export_t *)GetBotLibAPI( BOTLIB_API_VERSION, &botlib_import );
     assert(botlib_export);  // somehow we end up with a zero import.
 }
Referenced by SV_Init().
SV_BotInitCvars()
void SV_BotInitCvars (void)
Definition at line 483 of file sv_bot.c.
{
     Cvar_Get("bot_enable", "1", 0);                     //enable the bot
     Cvar_Get("bot_developer", "0", CVAR_CHEAT);         //bot developer mode
     Cvar_Get("bot_debug", "0", CVAR_CHEAT);             //enable bot debugging
     Cvar_Get("bot_maxdebugpolys", "2", 0);              //maximum number of debug polys
     Cvar_Get("bot_groundonly", "1", 0);                 //only show ground faces of areas
     Cvar_Get("bot_reachability", "0", 0);               //show all reachabilities to other areas
     Cvar_Get("bot_visualizejumppads", "0", CVAR_CHEAT); //show jumppads
     Cvar_Get("bot_forceclustering", "0", 0);            //force cluster calculations
     Cvar_Get("bot_forcereachability", "0", 0);          //force reachability calculations
     Cvar_Get("bot_forcewrite", "0", 0);                 //force writing aas file
     Cvar_Get("bot_aasoptimize", "0", 0);                //no aas file optimisation
     Cvar_Get("bot_saveroutingcache", "0", 0);           //save routing cache
     Cvar_Get("bot_thinktime", "100", CVAR_CHEAT);       //msec the bots thinks
     Cvar_Get("bot_reloadcharacters", "0", 0);           //reload the bot characters each time
     Cvar_Get("bot_testichat", "0", 0);                  //test ichats
     Cvar_Get("bot_testrchat", "0", 0);                  //test rchats
     Cvar_Get("bot_testsolid", "0", CVAR_CHEAT);         //test for solid areas
     Cvar_Get("bot_testclusters", "0", CVAR_CHEAT);      //test the AAS clusters
     Cvar_Get("bot_fastchat", "0", 0);                   //fast chatting bots
     Cvar_Get("bot_nochat", "0", 0);                     //disable chats
     Cvar_Get("bot_pause", "0", CVAR_CHEAT);             //pause the bots thinking
     Cvar_Get("bot_report", "0", CVAR_CHEAT);            //get a full report in ctf
     Cvar_Get("bot_grapple", "0", 0);                    //enable grapple
     Cvar_Get("bot_rocketjump", "1", 0);                 //enable rocket jumping
     Cvar_Get("bot_challenge", "0", 0);                  //challenging bot
     Cvar_Get("bot_minplayers", "0", 0);                 //minimum players in a team or the game
     Cvar_Get("bot_interbreedchar", "", CVAR_CHEAT);     //bot character used for interbreeding
     Cvar_Get("bot_interbreedbots", "10", CVAR_CHEAT);   //number of bots used for interbreeding
     Cvar_Get("bot_interbreedcycle", "20", CVAR_CHEAT);  //bot interbreeding cycle
     Cvar_Get("bot_interbreedwrite", "", CVAR_CHEAT);    //write interbreeded bots to this file
 }
Referenced by SV_Init().
SV_BotLibSetup()
int SV_BotLibSetup (void)
Definition at line 446 of file sv_bot.c.
{
     if (!bot_enable) {
         return 0;
     }
     if ( !botlib_export ) {
         Com_Printf( S_COLOR_RED "Error: SV_BotLibSetup without SV_BotInitBotLib\n" );
         return -1;
     }
     botlib_export->BotLibVarSet( "basegame", com_basegame->string );
     return botlib_export->BotLibSetup();
 }
Referenced by SV_GameSystemCalls().
SV_BotLibShutdown()
int SV_BotLibShutdown (void)
Definition at line 469 of file sv_bot.c.
{
     if ( !botlib_export ) {
         return -1;
     }
     return botlib_export->BotLibShutdown();
 }
Referenced by SV_GameSystemCalls().
SV_ChangeMaxClients()
void SV_ChangeMaxClients (void)
Definition at line 298 of file sv_init.c.
{
     int     oldMaxClients;
     int     i;
     client_t    *oldClients;
     int     count;
     // get the highest client number in use
     count = 0;
     for ( i = 0 ; i < sv_maxclients->integer ; i++ ) {
         if ( svs.clients[i].state >= CS_CONNECTED ) {
             if (i > count)
                 count = i;
         }
     }
     count++;
     oldMaxClients = sv_maxclients->integer;
     // never go below the highest client number in use
     SV_BoundMaxClients( count );
     // if still the same
     if ( sv_maxclients->integer == oldMaxClients ) {
         return;
     }
     oldClients = Hunk_AllocateTempMemory( count * sizeof(client_t) );
     // copy the clients to hunk memory
     for ( i = 0 ; i < count ; i++ ) {
         if ( svs.clients[i].state >= CS_CONNECTED ) {
             oldClients[i] = svs.clients[i];
         }
         else {
             Com_Memset(&oldClients[i], 0, sizeof(client_t));
         }
     }
     // free old clients arrays
     Z_Free( svs.clients );
     // allocate new clients
     svs.clients = Z_Malloc ( sv_maxclients->integer * sizeof(client_t) );
     Com_Memset( svs.clients, 0, sv_maxclients->integer * sizeof(client_t) );
     // copy the clients over
     for ( i = 0 ; i < count ; i++ ) {
         if ( oldClients[i].state >= CS_CONNECTED ) {
             svs.clients[i] = oldClients[i];
         }
     }
     // free the old clients on the hunk
     Hunk_FreeTempMemory( oldClients );
     // allocate new snapshot entities
     if ( com_dedicated->integer ) {
         svs.numSnapshotEntities = sv_maxclients->integer * PACKET_BACKUP * MAX_SNAPSHOT_ENTITIES;
     } else {
         // we don't need nearly as many when playing locally
         svs.numSnapshotEntities = sv_maxclients->integer * 4 * MAX_SNAPSHOT_ENTITIES;
     }
 }
Referenced by SV_SpawnServer().
SV_ClearWorld()
void SV_ClearWorld (void)
Definition at line 147 of file sv_world.c.
{
     clipHandle_t    h;
     vec3_t          mins, maxs;
     Com_Memset( sv_worldSectors, 0, sizeof(sv_worldSectors) );
     sv_numworldSectors = 0;
     // get world map bounds
     h = CM_InlineModel( 0 );
     CM_ModelBounds( h, mins, maxs );
     SV_CreateworldSector( 0, mins, maxs );
 }
Referenced by SV_SpawnServer().
SV_ClientEnterWorld()
void SV_ClientEnterWorld (client_t * client, usercmd_t * cmd)
Definition at line 780 of file sv_client.c.
{
     int     clientNum;
     sharedEntity_t *ent;
     Com_DPrintf( "Going from CS_PRIMED to CS_ACTIVE for %s\n", client->name );
     client->state = CS_ACTIVE;
     // resend all configstrings using the cs commands since these are
     // no longer sent when the client is CS_PRIMED
     SV_UpdateConfigstrings( client );
     // set up the entity for the client
     clientNum = client - svs.clients;
     ent = SV_GentityNum( clientNum );
     ent->s.number = clientNum;
     client->gentity = ent;
     client->deltaMessage = -1;
     client->lastSnapshotTime = 0;   // generate a snapshot immediately
     if(cmd)
         memcpy(&client->lastUsercmd, cmd, sizeof(client->lastUsercmd));
     else
         memset(&client->lastUsercmd, '\0', sizeof(client->lastUsercmd));
     // call the game begin function
     VM_Call( gvm, GAME_CLIENT_BEGIN, client - svs.clients );
 }
Referenced by SV_MapRestart_f(), and SV_UserMove().
SV_ClientThink()
void SV_ClientThink (client_t * cl, usercmd_t * cmd)
Definition at line 1652 of file sv_client.c.
{
     cl->lastUsercmd = *cmd;
     if ( cl->state != CS_ACTIVE ) {
         return;     // may have been kicked during the last usercmd
     }
     VM_Call( gvm, GAME_CLIENT_THINK, cl - svs.clients );
 }
Referenced by SV_GameSystemCalls(), and SV_UserMove().
SV_ClipHandleForEntity()
clipHandle_t SV_ClipHandleForEntity (const sharedEntity_t * ent)
Definition at line 35 of file sv_world.c.
{
     if ( ent->r.bmodel ) {
         // explicit hulls in the BSP model
         return CM_InlineModel( ent->s.modelindex );
     }
     if ( ent->r.svFlags & SVF_CAPSULE ) {
         // create a temp capsule from bounding box sizes
         return CM_TempBoxModel( ent->r.mins, ent->r.maxs, qtrue );
     }
     // create a temp tree from bounding box sizes
     return CM_TempBoxModel( ent->r.mins, ent->r.maxs, qfalse );
 }
Referenced by SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), and SV_PointContents().
SV_ClipToEntity()
void SV_ClipToEntity (trace_t * trace, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int entityNum, int contentmask, int capsule)
Definition at line 464 of file sv_world.c.
{
     sharedEntity_t  *touch;
     clipHandle_t    clipHandle;
     float           *origin, *angles;
     touch = SV_GentityNum( entityNum );
     Com_Memset(trace, 0, sizeof(trace_t));
     // if it doesn't have any brushes of a type we
     // are looking for, ignore it
     if ( ! ( contentmask & touch->r.contents ) ) {
         trace->fraction = 1.0;
         return;
     }
     // might intersect, so do an exact clip
     clipHandle = SV_ClipHandleForEntity (touch);
     origin = touch->r.currentOrigin;
     angles = touch->r.currentAngles;
     if ( !touch->r.bmodel ) {
         angles = vec3_origin;   // boxes don't rotate
     }
     CM_TransformedBoxTrace ( trace, (float *)start, (float *)end,
         (float *)mins, (float *)maxs, clipHandle,  contentmask,
         origin, angles, capsule);
     if ( trace->fraction < 1 ) {
         trace->entityNum = touch->s.number;
     }
 }
Referenced by BotImport_EntityTrace().
SV_DirectConnect()
void SV_DirectConnect (netadr_t from)
Definition at line 322 of file sv_client.c.
{
     char        userinfo[MAX_INFO_STRING];
     int         i;
     client_t    *cl, *newcl;
     client_t    temp;
     sharedEntity_t *ent;
     int         clientNum;
     int         version;
     int         qport;
     int         challenge;
     char        *password;
     int         startIndex;
     intptr_t        denied;
     int         count;
     char        *ip;
 #ifdef LEGACY_PROTOCOL
     qboolean    compat = qfalse;
 #endif
     Com_DPrintf ("SVC_DirectConnect ()\n");
     // Check whether this client is banned.
     if(SV_IsBanned(&from, qfalse))
     {
         NET_OutOfBandPrint(NS_SERVER, from, "print\nYou are banned from this server.\n");
         return;
     }
     Q_strncpyz( userinfo, Cmd_Argv(1), sizeof(userinfo) );
     version = atoi(Info_ValueForKey(userinfo, "protocol"));
 #ifdef LEGACY_PROTOCOL
     if(version > 0 && com_legacyprotocol->integer == version)
         compat = qtrue;
     else
 #endif
     {
         if(version != com_protocol->integer)
         {
             NET_OutOfBandPrint(NS_SERVER, from, "print\nServer uses protocol version %i "
                        "(yours is %i).\n", com_protocol->integer, version);
             Com_DPrintf("    rejected connect from version %i\n", version);
             return;
         }
     }
     challenge = atoi( Info_ValueForKey( userinfo, "challenge" ) );
     qport = atoi( Info_ValueForKey( userinfo, "qport" ) );
     // quick reject
     for (i=0,cl=svs.clients ; i < sv_maxclients->integer ; i++,cl++) {
         if ( cl->state == CS_FREE ) {
             continue;
         }
         if ( NET_CompareBaseAdr( from, cl->netchan.remoteAddress )
             && ( cl->netchan.qport == qport
             || from.port == cl->netchan.remoteAddress.port ) ) {
             if (( svs.time - cl->lastConnectTime)
                 < (sv_reconnectlimit->integer * 1000)) {
                 Com_DPrintf ("%s:reconnect rejected : too soon\n", NET_AdrToString (from));
                 return;
             }
             break;
         }
     }
     // don't let "ip" overflow userinfo string
     if ( NET_IsLocalAddress (from) )
         ip = "localhost";
     else
         ip = (char *)NET_AdrToString( from );
     if( ( strlen( ip ) + strlen( userinfo ) + 4 ) >= MAX_INFO_STRING ) {
         NET_OutOfBandPrint( NS_SERVER, from,
             "print\nUserinfo string length exceeded.  "
             "Try removing setu cvars from your config.\n" );
         return;
     }
     Info_SetValueForKey( userinfo, "ip", ip );
     // see if the challenge is valid (LAN clients don't need to challenge)
     if (!NET_IsLocalAddress(from))
     {
         int ping;
         challenge_t *challengeptr;
         for (i=0; i<MAX_CHALLENGES; i++)
         {
             if (NET_CompareAdr(from, svs.challenges[i].adr))
             {
                 if(challenge == svs.challenges[i].challenge)
                     break;
             }
         }
         if (i == MAX_CHALLENGES)
         {
             NET_OutOfBandPrint( NS_SERVER, from, "print\nNo or bad challenge for your address.\n" );
             return;
         }
         challengeptr = &svs.challenges[i];
         if(challengeptr->wasrefused)
         {
             // Return silently, so that error messages written by the server keep being displayed.
             return;
         }
         ping = svs.time - challengeptr->pingTime;
         // never reject a LAN client based on ping
         if ( !Sys_IsLANAddress( from ) ) {
             if ( sv_minPing->value && ping < sv_minPing->value ) {
                 NET_OutOfBandPrint( NS_SERVER, from, "print\nServer is for high pings only\n" );
                 Com_DPrintf ("Client %i rejected on a too low ping\n", i);
                 challengeptr->wasrefused = qtrue;
                 return;
             }
             if ( sv_maxPing->value && ping > sv_maxPing->value ) {
                 NET_OutOfBandPrint( NS_SERVER, from, "print\nServer is for low pings only\n" );
                 Com_DPrintf ("Client %i rejected on a too high ping\n", i);
                 challengeptr->wasrefused = qtrue;
                 return;
             }
         }
         Com_Printf("Client %i connecting with %i challenge ping\n", i, ping);
         challengeptr->connected = qtrue;
     }
     newcl = &temp;
     Com_Memset (newcl, 0, sizeof(client_t));
     // if there is already a slot for this ip, reuse it
     for (i=0,cl=svs.clients ; i < sv_maxclients->integer ; i++,cl++) {
         if ( cl->state == CS_FREE ) {
             continue;
         }
         if ( NET_CompareBaseAdr( from, cl->netchan.remoteAddress )
             && ( cl->netchan.qport == qport
             || from.port == cl->netchan.remoteAddress.port ) ) {
             Com_Printf ("%s:reconnect\n", NET_AdrToString (from));
             newcl = cl;
             // this doesn't work because it nukes the players userinfo
 //          // disconnect the client from the game first so any flags the
 //          // player might have are dropped
 //          VM_Call( gvm, GAME_CLIENT_DISCONNECT, newcl - svs.clients );
             //
             goto gotnewcl;
         }
     }
     // find a client slot
     // if "sv_privateClients" is set > 0, then that number
     // of client slots will be reserved for connections that
     // have "password" set to the value of "sv_privatePassword"
     // Info requests will report the maxclients as if the private
     // slots didn't exist, to prevent people from trying to connect
     // to a full server.
     // This is to allow us to reserve a couple slots here on our
     // servers so we can play without having to kick people.
     // check for privateClient password
     password = Info_ValueForKey( userinfo, "password" );
     if ( *password && !strcmp( password, sv_privatePassword->string ) ) {
         startIndex = 0;
     } else {
         // skip past the reserved slots
         startIndex = sv_privateClients->integer;
     }
     newcl = NULL;
     for ( i = startIndex; i < sv_maxclients->integer ; i++ ) {
         cl = &svs.clients[i];
         if (cl->state == CS_FREE) {
             newcl = cl;
             break;
         }
     }
     if ( !newcl ) {
         if ( NET_IsLocalAddress( from ) ) {
             count = 0;
             for ( i = startIndex; i < sv_maxclients->integer ; i++ ) {
                 cl = &svs.clients[i];
                 if (cl->netchan.remoteAddress.type == NA_BOT) {
                     count++;
                 }
             }
             // if they're all bots
             if (count >= sv_maxclients->integer - startIndex) {
                 SV_DropClient(&svs.clients[sv_maxclients->integer - 1], "only bots on server");
                 newcl = &svs.clients[sv_maxclients->integer - 1];
             }
             else {
                 Com_Error( ERR_FATAL, "server is full on local connect" );
                 return;
             }
         }
         else {
             NET_OutOfBandPrint( NS_SERVER, from, "print\nServer is full.\n" );
             Com_DPrintf ("Rejected a connection.\n");
             return;
         }
     }
     // we got a newcl, so reset the reliableSequence and reliableAcknowledge
     cl->reliableAcknowledge = 0;
     cl->reliableSequence = 0;
 gotnewcl:
     // build a new connection
     // accept the new client
     // this is the only place a client_t is ever initialized
     *newcl = temp;
     clientNum = newcl - svs.clients;
     ent = SV_GentityNum( clientNum );
     newcl->gentity = ent;
     // save the challenge
     newcl->challenge = challenge;
     // save the address
 #ifdef LEGACY_PROTOCOL
     newcl->compat = compat;
     Netchan_Setup(NS_SERVER, &newcl->netchan, from, qport, challenge, compat);
 #else
     Netchan_Setup(NS_SERVER, &newcl->netchan, from, qport, challenge, qfalse);
 #endif
     // init the netchan queue
     newcl->netchan_end_queue = &newcl->netchan_start_queue;
     // save the userinfo
     Q_strncpyz( newcl->userinfo, userinfo, sizeof(newcl->userinfo) );
     // get the game a chance to reject this connection or modify the userinfo
     denied = VM_Call( gvm, GAME_CLIENT_CONNECT, clientNum, qtrue, qfalse ); // firstTime = qtrue
     if ( denied ) {
         // we can't just use VM_ArgPtr, because that is only valid inside a VM_Call
         char *str = VM_ExplicitArgPtr( gvm, denied );
         NET_OutOfBandPrint( NS_SERVER, from, "print\n%s\n", str );
         Com_DPrintf ("Game rejected a connection: %s.\n", str);
         return;
     }
     SV_UserinfoChanged( newcl );
     // send the connect packet to the client
     NET_OutOfBandPrint(NS_SERVER, from, "connectResponse %d", challenge);
     Com_DPrintf( "Going from CS_FREE to CS_CONNECTED for %s\n", newcl->name );
     newcl->state = CS_CONNECTED;
     newcl->lastSnapshotTime = 0;
     newcl->lastPacketTime = svs.time;
     newcl->lastConnectTime = svs.time;
     // when we receive the first packet from the client, we will
     // notice that it is from a different serverid and that the
     // gamestate message was not just sent, forcing a retransmit
     newcl->gamestateMessageNum = -1;
     // if this was the first client on the server, or the last client
     // the server can hold, send a heartbeat to the master.
     count = 0;
     for (i=0,cl=svs.clients ; i < sv_maxclients->integer ; i++,cl++) {
         if ( svs.clients[i].state >= CS_CONNECTED ) {
             count++;
         }
     }
     if ( count == 1 || count == sv_maxclients->integer ) {
         SV_Heartbeat_f();
     }
 }
Referenced by SV_ConnectionlessPacket().
SV_DropClient()
void SV_DropClient (client_t * drop, const char * reason)
Definition at line 636 of file sv_client.c.
{
     int     i;
     challenge_t *challenge;
     const qboolean isBot = drop->netchan.remoteAddress.type == NA_BOT;
     if ( drop->state == CS_ZOMBIE ) {
         return;     // already dropped
     }
     if ( !isBot ) {
         // see if we already have a challenge for this ip
         challenge = &svs.challenges[0];
         for (i = 0 ; i < MAX_CHALLENGES ; i++, challenge++)
         {
             if(NET_CompareAdr(drop->netchan.remoteAddress, challenge->adr))
             {
                 Com_Memset(challenge, 0, sizeof(*challenge));
                 break;
             }
         }
     }
     // Free all allocated data on the client structure
     SV_FreeClient(drop);
     // tell everyone why they got dropped
     SV_SendServerCommand( NULL, "print \"%s" S_COLOR_WHITE " %s\n\"", drop->name, reason );
     // call the prog function for removing a client
     // this will remove the body, among other things
     VM_Call( gvm, GAME_CLIENT_DISCONNECT, drop - svs.clients );
     // add the disconnect command
     SV_SendServerCommand( drop, "disconnect \"%s\"", reason);
     if ( isBot ) {
         SV_BotFreeClient( drop - svs.clients );
         // bots shouldn't go zombie, as there's no real net connection.
         drop->state = CS_FREE;
     } else {
         Com_DPrintf( "Going to CS_ZOMBIE for %s\n", drop->name );
         drop->state = CS_ZOMBIE;        // become free in a few seconds
     }
     // nuke user info
     SV_SetUserinfo( drop - svs.clients, "" );
     // if this was the last client on the server, send a heartbeat
     // to the master so it is known the server is empty
     // send a heartbeat now so the master will get up to date info
     // if there is already a slot for this ip, reuse it
     for (i=0 ; i < sv_maxclients->integer ; i++ ) {
         if ( svs.clients[i].state >= CS_CONNECTED ) {
             break;
         }
     }
     if ( i == sv_maxclients->integer ) {
         SV_Heartbeat_f();
     }
 }
Referenced by SV_AddServerCommand(), SV_CheckTimeouts(), SV_ClientCommand(), SV_DirectConnect(), SV_Disconnect_f(), SV_ExecuteClientMessage(), SV_GameDropClient(), SV_Kick_f(), SV_KickAll_f(), SV_KickBots_f(), SV_KickNum_f(), SV_MapRestart_f(), SV_NextDownload_f(), SV_SpawnServer(), SV_UserinfoChanged(), SV_UserMove(), and SV_VerifyPaks_f().
SV_ExecuteClientCommand()
void SV_ExecuteClientCommand (client_t * cl, const char * s, qboolean clientOK)
Definition at line 1560 of file sv_client.c.
{
     ucmd_t  *u;
     qboolean bProcessed = qfalse;
     Cmd_TokenizeString( s );
     // see if it is a server level command
     for (u=ucmds ; u->name ; u++) {
         if (!strcmp (Cmd_Argv(0), u->name) ) {
             u->func( cl );
             bProcessed = qtrue;
             break;
         }
     }
     if (clientOK) {
         // pass unknown strings to the game
         if (!u->name && sv.state == SS_GAME && (cl->state == CS_ACTIVE || cl->state == CS_PRIMED)) {
             Cmd_Args_Sanitize();
             VM_Call( gvm, GAME_CLIENT_COMMAND, cl - svs.clients );
         }
     }
     else if (!bProcessed)
         Com_DPrintf( "client text ignored for %s: %s\n", cl->name, Cmd_Argv(0) );
 }
Referenced by BotClientCommand(), and SV_ClientCommand().
SV_ExecuteClientMessage()
void SV_ExecuteClientMessage (client_t * cl, msg_t * msg)
Definition at line 1897 of file sv_client.c.
{
     int         c;
     int         serverId;
     MSG_Bitstream(msg);
     serverId = MSG_ReadLong( msg );
     cl->messageAcknowledge = MSG_ReadLong( msg );
     if (cl->messageAcknowledge < 0) {
         // usually only hackers create messages like this
         // it is more annoying for them to let them hanging
 #ifndef NDEBUG
         SV_DropClient( cl, "DEBUG: illegible client message" );
 #endif
         return;
     }
     cl->reliableAcknowledge = MSG_ReadLong( msg );
     // NOTE: when the client message is fux0red the acknowledgement numbers
     // can be out of range, this could cause the server to send thousands of server
     // commands which the server thinks are not yet acknowledged in SV_UpdateServerCommandsToClient
     if (cl->reliableAcknowledge < cl->reliableSequence - MAX_RELIABLE_COMMANDS) {
         // usually only hackers create messages like this
         // it is more annoying for them to let them hanging
 #ifndef NDEBUG
         SV_DropClient( cl, "DEBUG: illegible client message" );
 #endif
         cl->reliableAcknowledge = cl->reliableSequence;
         return;
     }
     // if this is a usercmd from a previous gamestate,
     // ignore it or retransmit the current gamestate
     //
     // if the client was downloading, let it stay at whatever serverId and
     // gamestate it was at.  This allows it to keep downloading even when
     // the gamestate changes.  After the download is finished, we'll
     // notice and send it a new game state
     //
     // https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=536
     // don't drop as long as previous command was a nextdl, after a dl is done, downloadName is set back to ""
     // but we still need to read the next message to move to next download or send gamestate
     // I don't like this hack though, it must have been working fine at some point, suspecting the fix is somewhere else
     if ( serverId != sv.serverId && !*cl->downloadName && !strstr(cl->lastClientCommandString, "nextdl") ) {
         if ( serverId >= sv.restartedServerId && serverId < sv.serverId ) { // TTimo - use a comparison here to catch multiple map_restart
             // they just haven't caught the map_restart yet
             Com_DPrintf("%s : ignoring pre map_restart / outdated client message\n", cl->name);
             return;
         }
         // if we can tell that the client has dropped the last
         // gamestate we sent them, resend it
         if ( cl->state != CS_ACTIVE && cl->messageAcknowledge > cl->gamestateMessageNum ) {
             Com_DPrintf( "%s : dropped gamestate, resending\n", cl->name );
             SV_SendClientGameState( cl );
         }
         return;
     }
     // this client has acknowledged the new gamestate so it's
     // safe to start sending it the real time again
     if( cl->oldServerTime && serverId == sv.serverId ){
         Com_DPrintf( "%s acknowledged gamestate\n", cl->name );
         cl->oldServerTime = 0;
     }
     // read optional clientCommand strings
     do {
         c = MSG_ReadByte( msg );
         if ( c == clc_EOF ) {
             break;
         }
         if ( c != clc_clientCommand ) {
             break;
         }
         if ( !SV_ClientCommand( cl, msg ) ) {
             return; // we couldn't execute it because of the flood protection
         }
         if (cl->state == CS_ZOMBIE) {
             return; // disconnect command
         }
     } while ( 1 );
     // skip legacy speex voip data
     if ( c == clc_voipSpeex ) {
 #ifdef USE_VOIP
         SV_UserVoip( cl, msg, qtrue );
         c = MSG_ReadByte( msg );
 #endif
     }
     // read optional voip data
     if ( c == clc_voipOpus ) {
 #ifdef USE_VOIP
         SV_UserVoip( cl, msg, qfalse );
         c = MSG_ReadByte( msg );
 #endif
     }
     // read the usercmd_t
     if ( c == clc_move ) {
         SV_UserMove( cl, msg, qtrue );
     } else if ( c == clc_moveNoDelta ) {
         SV_UserMove( cl, msg, qfalse );
     } else if ( c != clc_EOF ) {
         Com_Printf( "WARNING: bad command byte for client %i\n", (int) (cl - svs.clients) );
     }
 //  if ( msg->readcount != msg->cursize ) {
 //      Com_Printf( "WARNING: Junk at end of packet for client %i\n", cl - svs.clients );
 //  }
 }
Referenced by SV_PacketEvent().
SV_FinalMessage()
void SV_FinalMessage (char * message)
Definition at line 712 of file sv_init.c.
{
     int         i, j;
     client_t    *cl;
     // send it twice, ignoring rate
     for ( j = 0 ; j < 2 ; j++ ) {
         for (i=0, cl = svs.clients ; i < sv_maxclients->integer ; i++, cl++) {
             if (cl->state >= CS_CONNECTED) {
                 // don't send a disconnect to a local client
                 if ( cl->netchan.remoteAddress.type != NA_LOOPBACK ) {
                     SV_SendServerCommand( cl, "print \"%s\n\"\n", message );
                     SV_SendServerCommand( cl, "disconnect \"%s\"", message );
                 }
                 // force a snapshot to be sent
                 cl->lastSnapshotTime = 0;
                 SV_SendClientSnapshot( cl );
             }
         }
     }
 }
Referenced by SV_Shutdown().
SV_FreeClient()
void SV_FreeClient (client_t * client)
Definition at line 608 of file sv_client.c.
 {
 #ifdef USE_VOIP
     int index;
     for(index = client->queuedVoipIndex; index < client->queuedVoipPackets; index++)
     {
         index %= ARRAY_LEN(client->voipPacket);
         Z_Free(client->voipPacket[index]);
     }
     client->queuedVoipPackets = 0;
 #endif
     SV_Netchan_FreeQueue(client);
     SV_CloseDownload(client);
 }
Referenced by SV_DropClient(), and SV_Shutdown().
SV_GameClientNum()
playerState_t* SV_GameClientNum (int num)
Definition at line 50 of file sv_game.c.
 {
     playerState_t* ps;
     ps = (playerState_t*)((byte*)sv.gameClients + sv.gameClientSize * (num));
     return ps;
 }
Referenced by SV_BuildClientSnapshot(), SV_CalcPings(), SV_Status_f(), and SVC_Status().
SV_GEntityForSvEntity()
sharedEntity_t* SV_GEntityForSvEntity (svEntity_t * svEnt)
Definition at line 67 of file sv_game.c.
 {
     int     num;
     num = svEnt - sv.svEntities;
     return SV_GentityNum(num);
 }
Referenced by SV_AreaEntities_r().
SV_GentityNum()
sharedEntity_t* SV_GentityNum (int num)
Definition at line 41 of file sv_game.c.
 {
     sharedEntity_t* ent;
     ent = (sharedEntity_t*)((byte*)sv.gentities + sv.gentitySize * (num));
     return ent;
 }
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_BotAllocateClient(), SV_BuildClientSnapshot(), SV_ClientEnterWorld(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_CreateBaseline(), SV_DirectConnect(), SV_GEntityForSvEntity(), SV_PointContents(), and SV_SpawnServer().
SV_GetChallenge()
void SV_GetChallenge (netadr_t from)
Definition at line 53 of file sv_client.c.
 {
     int     i;
     int     oldest;
     int     oldestTime;
     int     oldestClientTime;
     int     clientChallenge;
     challenge_t *challenge;
     qboolean wasfound = qfalse;
     char *gameName;
     qboolean gameMismatch;
     // ignore if we are in single player
     if ( Cvar_VariableValue( "g_gametype" ) == GT_SINGLE_PLAYER || Cvar_VariableValue("ui_singlePlayerActive")) {
         return;
     }
     // Prevent using getchallenge as an amplifier
     if ( SVC_RateLimitAddress( from, 10, 1000 ) ) {
         Com_DPrintf( "SV_GetChallenge: rate limit from %s exceeded, dropping request\n",
             NET_AdrToString( from ) );
         return;
     }
     // Allow getchallenge to be DoSed relatively easily, but prevent
     // excess outbound bandwidth usage when being flooded inbound
     if ( SVC_RateLimit( &outboundLeakyBucket, 10, 100 ) ) {
         Com_DPrintf( "SV_GetChallenge: rate limit exceeded, dropping request\n" );
         return;
     }
     gameName = Cmd_Argv(2);
 #ifdef LEGACY_PROTOCOL
     // gamename is optional for legacy protocol
     if (com_legacyprotocol->integer && !*gameName)
         gameMismatch = qfalse;
     else
 #endif
         gameMismatch = !*gameName || strcmp(gameName, com_gamename->string) != 0;
     // reject client if the gamename string sent by the client doesn't match ours
     if (gameMismatch)
     {
         NET_OutOfBandPrint(NS_SERVER, from, "print\nGame mismatch: This is a %s server\n",
             com_gamename->string);
         return;
     }
     oldest = 0;
     oldestClientTime = oldestTime = 0x7fffffff;
     // see if we already have a challenge for this ip
     challenge = &svs.challenges[0];
     clientChallenge = atoi(Cmd_Argv(1));
     for(i = 0 ; i < MAX_CHALLENGES ; i++, challenge++)
     {
         if(!challenge->connected && NET_CompareAdr(from, challenge->adr))
         {
             wasfound = qtrue;
             if(challenge->time < oldestClientTime)
                 oldestClientTime = challenge->time;
         }
         if(wasfound && i >= MAX_CHALLENGES_MULTI)
         {
             i = MAX_CHALLENGES;
             break;
         }
         if(challenge->time < oldestTime)
         {
             oldestTime = challenge->time;
             oldest = i;
         }
     }
     if (i == MAX_CHALLENGES)
     {
         // this is the first time this client has asked for a challenge
         challenge = &svs.challenges[oldest];
         challenge->clientChallenge = clientChallenge;
         challenge->adr = from;
         challenge->firstTime = svs.time;
         challenge->connected = qfalse;
     }
     // always generate a new challenge number, so the client cannot circumvent sv_maxping
     challenge->challenge = ( ((unsigned int)rand() << 16) ^ (unsigned int)rand() ) ^ svs.time;
     challenge->wasrefused = qfalse;
     challenge->time = svs.time;
 #ifndef STANDALONE
     // Drop the authorize stuff if this client is coming in via v6 as the auth server does not support ipv6.
     // Drop also for addresses coming in on local LAN and for stand-alone games independent from id's assets.
     if(challenge->adr.type == NA_IP && !com_standalone->integer && !Sys_IsLANAddress(from))
     {
         // look up the authorize server's IP
         if (svs.authorizeAddress.type == NA_BAD)
         {
             Com_Printf( "Resolving %s\n", AUTHORIZE_SERVER_NAME );
             if (NET_StringToAdr(AUTHORIZE_SERVER_NAME, &svs.authorizeAddress, NA_IP))
             {
                 svs.authorizeAddress.port = BigShort( PORT_AUTHORIZE );
                 Com_Printf( "%s resolved to %i.%i.%i.%i:%i\n", AUTHORIZE_SERVER_NAME,
                     svs.authorizeAddress.ip[0], svs.authorizeAddress.ip[1],
                     svs.authorizeAddress.ip[2], svs.authorizeAddress.ip[3],
                     BigShort( svs.authorizeAddress.port ) );
             }
         }
         // we couldn't contact the auth server, let them in.
         if(svs.authorizeAddress.type == NA_BAD)
             Com_Printf("Couldn't resolve auth server address\n");
         // if they have been challenging for a long time and we
         // haven't heard anything from the authorize server, go ahead and
         // let them in, assuming the id server is down
         else if(svs.time - oldestClientTime > AUTHORIZE_TIMEOUT)
             Com_DPrintf( "authorize server timed out\n" );
         else
         {
             // otherwise send their ip to the authorize server
             const char *game;
             Com_DPrintf( "sending getIpAuthorize for %s\n", NET_AdrToString( from ));
             game = Cvar_VariableString( "fs_game" );
             if (game[0] == 0) {
                 game = BASEGAME;
             }
             // the 0 is for backwards compatibility with obsolete sv_allowanonymous flags
             // getIpAuthorize <challenge> <IP> <game> 0 <auth-flag>
             NET_OutOfBandPrint( NS_SERVER, svs.authorizeAddress,
                 "getIpAuthorize %i %i.%i.%i.%i %s 0 %s",  challenge->challenge,
                 from.ip[0], from.ip[1], from.ip[2], from.ip[3], game, sv_strictAuth->string );
             return;
         }
     }
 #endif
     challenge->pingTime = svs.time;
     NET_OutOfBandPrint(NS_SERVER, challenge->adr, "challengeResponse %d %d %d",
                challenge->challenge, clientChallenge, com_protocol->integer);
 }
Referenced by SV_ConnectionlessPacket().
SV_GetConfigstring()
void SV_GetConfigstring (int index, char * buffer, int bufferSize)
Definition at line 154 of file sv_init.c.
{
     if ( bufferSize < 1 ) {
         Com_Error( ERR_DROP, "SV_GetConfigstring: bufferSize == %i", bufferSize );
     }
     if ( index < 0 || index >= MAX_CONFIGSTRINGS ) {
         Com_Error (ERR_DROP, "SV_GetConfigstring: bad index %i", index);
     }
     if ( !sv.configstrings[index] ) {
         buffer[0] = 0;
         return;
     }
     Q_strncpyz( buffer, sv.configstrings[index], bufferSize );
 }
Referenced by SV_GameSystemCalls().
SV_GetUserinfo()
void SV_GetUserinfo (int index, char * buffer, int bufferSize)
Definition at line 197 of file sv_init.c.
{
     if ( bufferSize < 1 ) {
         Com_Error( ERR_DROP, "SV_GetUserinfo: bufferSize == %i", bufferSize );
     }
     if ( index < 0 || index >= sv_maxclients->integer ) {
         Com_Error (ERR_DROP, "SV_GetUserinfo: bad index %i", index);
     }
     Q_strncpyz( buffer, svs.clients[ index ].userinfo, bufferSize );
 }
Referenced by SV_GameSystemCalls().
SV_Heartbeat_f()
void SV_Heartbeat_f (void)
Definition at line 1381 of file sv_ccmds.c.
{
     svs.nextHeartbeatTime = -9999999;
 }
Referenced by SV_AddOperatorCommands(), SV_DirectConnect(), SV_DropClient(), and SV_SpawnServer().
SV_InitGameProgs()
void SV_InitGameProgs (void)
Definition at line 941 of file sv_game.c.
 {
     cvar_t* var;
     //FIXME these are temp while I make bots run in vm
     extern int  bot_enable;
     var = Cvar_Get("bot_enable", "1", CVAR_LATCH);
     if (var) {
         bot_enable = var->integer;
     } else {
         bot_enable = 0;
     }
     // load the dll or bytecode
     gvm = VM_Create("qagame", SV_GameSystemCalls, Cvar_VariableValue("vm_game"));
     if (!gvm) {
         Com_Error(ERR_FATAL, "VM_Create on game failed");
     }
     SV_InitGameVM(qfalse);
 }
Referenced by SV_SpawnServer().
SV_inPVS()
qboolean SV_inPVS (const vec3_t p1, const vec3_t p2)
Definition at line 152 of file sv_game.c.
 {
     int     leafnum;
     int     cluster;
     int     area1, area2;
     byte* mask;
     leafnum = CM_PointLeafnum(p1);
     cluster = CM_LeafCluster(leafnum);
     area1 = CM_LeafArea(leafnum);
     mask = CM_ClusterPVS(cluster);
     leafnum = CM_PointLeafnum(p2);
     cluster = CM_LeafCluster(leafnum);
     area2 = CM_LeafArea(leafnum);
     if (mask && (!(mask[cluster >> 3] & (1 << (cluster & 7)))))
         return qfalse;
     if (!CM_AreasConnected(area1, area2))
         return qfalse;      // a door blocks sight
     return qtrue;
 }
Referenced by BotImport_inPVS(), and SV_GameSystemCalls().
SV_LinkEntity()
void SV_LinkEntity (sharedEntity_t * ent)
Definition at line 205 of file sv_world.c.
{
     worldSector_t   *node;
     int         leafs[MAX_TOTAL_ENT_LEAFS];
     int         cluster;
     int         num_leafs;
     int         i, j, k;
     int         area;
     int         lastLeaf;
     float       *origin, *angles;
     svEntity_t  *ent;
     ent = SV_SvEntityForGentity( gEnt );
     if ( ent->worldSector ) {
         SV_UnlinkEntity( gEnt );    // unlink from old position
     }
     // encode the size into the entityState_t for client prediction
     if ( gEnt->r.bmodel ) {
         gEnt->s.solid = SOLID_BMODEL;       // a solid_box will never create this value
     } else if ( gEnt->r.contents & ( CONTENTS_SOLID | CONTENTS_BODY ) ) {
         // assume that x/y are equal and symetric
         i = gEnt->r.maxs[0];
         if (i<1)
             i = 1;
         if (i>255)
             i = 255;
         // z is not symetric
         j = (-gEnt->r.mins[2]);
         if (j<1)
             j = 1;
         if (j>255)
             j = 255;
         // and z maxs can be negative...
         k = (gEnt->r.maxs[2]+32);
         if (k<1)
             k = 1;
         if (k>255)
             k = 255;
         gEnt->s.solid = (k<<16) | (j<<8) | i;
     } else {
         gEnt->s.solid = 0;
     }
     // get the position
     origin = gEnt->r.currentOrigin;
     angles = gEnt->r.currentAngles;
     // set the abs box
     if ( gEnt->r.bmodel && (angles[0] || angles[1] || angles[2]) ) {
         // expand for rotation
         float       max;
         max = RadiusFromBounds( gEnt->r.mins, gEnt->r.maxs );
         for (i=0 ; i<3 ; i++) {
             gEnt->r.absmin[i] = origin[i] - max;
             gEnt->r.absmax[i] = origin[i] + max;
         }
     } else {
         // normal
         VectorAdd (origin, gEnt->r.mins, gEnt->r.absmin);
         VectorAdd (origin, gEnt->r.maxs, gEnt->r.absmax);
     }
     // because movement is clipped an epsilon away from an actual edge,
     // we must fully check even when bounding boxes don't quite touch
     gEnt->r.absmin[0] -= 1;
     gEnt->r.absmin[1] -= 1;
     gEnt->r.absmin[2] -= 1;
     gEnt->r.absmax[0] += 1;
     gEnt->r.absmax[1] += 1;
     gEnt->r.absmax[2] += 1;
     // link to PVS leafs
     ent->numClusters = 0;
     ent->lastCluster = 0;
     ent->areanum = -1;
     ent->areanum2 = -1;
     //get all leafs, including solids
     num_leafs = CM_BoxLeafnums( gEnt->r.absmin, gEnt->r.absmax,
         leafs, MAX_TOTAL_ENT_LEAFS, &lastLeaf );
     // if none of the leafs were inside the map, the
     // entity is outside the world and can be considered unlinked
     if ( !num_leafs ) {
         return;
     }
     // set areas, even from clusters that don't fit in the entity array
     for (i=0 ; i<num_leafs ; i++) {
         area = CM_LeafArea (leafs[i]);
         if (area != -1) {
             // doors may legally straggle two areas,
             // but nothing should evern need more than that
             if (ent->areanum != -1 && ent->areanum != area) {
                 if (ent->areanum2 != -1 && ent->areanum2 != area && sv.state == SS_LOADING) {
                     Com_DPrintf ("Object %i touching 3 areas at %f %f %f\n",
                     gEnt->s.number,
                     gEnt->r.absmin[0], gEnt->r.absmin[1], gEnt->r.absmin[2]);
                 }
                 ent->areanum2 = area;
             } else {
                 ent->areanum = area;
             }
         }
     }
     // store as many explicit clusters as we can
     ent->numClusters = 0;
     for (i=0 ; i < num_leafs ; i++) {
         cluster = CM_LeafCluster( leafs[i] );
         if ( cluster != -1 ) {
             ent->clusternums[ent->numClusters++] = cluster;
             if ( ent->numClusters == MAX_ENT_CLUSTERS ) {
                 break;
             }
         }
     }
     // store off a last cluster if we need to
     if ( i != num_leafs ) {
         ent->lastCluster = CM_LeafCluster( lastLeaf );
     }
     gEnt->r.linkcount++;
     // find the first world sector node that the ent's box crosses
     node = sv_worldSectors;
     while (1)
     {
         if (node->axis == -1)
             break;
         if ( gEnt->r.absmin[node->axis] > node->dist)
             node = node->children[0];
         else if ( gEnt->r.absmax[node->axis] < node->dist)
             node = node->children[1];
         else
             break;      // crosses the node
     }
     // link it in
     ent->worldSector = node;
     ent->nextEntityInWorldSector = node->entities;
     node->entities = ent;
     gEnt->r.linked = qtrue;
 }
Referenced by SV_GameSystemCalls(), and SV_SetBrushModel().
SV_MasterShutdown()
void SV_MasterShutdown (void)
Definition at line 335 of file sv_main.c.
{
     // send a heartbeat right now
     svs.nextHeartbeatTime = -9999;
     SV_MasterHeartbeat(HEARTBEAT_FOR_MASTER);
     // send it again to minimize chance of drops
     svs.nextHeartbeatTime = -9999;
     SV_MasterHeartbeat(HEARTBEAT_FOR_MASTER);
     // when the master tries to poll the server, it won't respond, so
     // it will be removed from the list
 }
Referenced by SV_Shutdown().
SV_Netchan_FreeQueue()
void SV_Netchan_FreeQueue (client_t * client)
Definition at line 141 of file sv_net_chan.c.
 {
     netchan_buffer_t *netbuf, *next;
     for(netbuf = client->netchan_start_queue; netbuf; netbuf = next)
     {
         next = netbuf->next;
         Z_Free(netbuf);
     }
     client->netchan_start_queue = NULL;
     client->netchan_end_queue = &client->netchan_start_queue;
 }
Referenced by SV_FreeClient().
SV_Netchan_Process()
qboolean SV_Netchan_Process (client_t * client, msg_t * msg)
Definition at line 262 of file sv_net_chan.c.
{
     int ret;
     ret = Netchan_Process( &client->netchan, msg );
     if (!ret)
         return qfalse;
 #ifdef LEGACY_PROTOCOL
     if(client->compat)
         SV_Netchan_Decode(client, msg);
 #endif
     return qtrue;
 }
Referenced by SV_PacketEvent().
SV_Netchan_Transmit()
void SV_Netchan_Transmit (client_t * client, msg_t * msg)
Definition at line 224 of file sv_net_chan.c.
 {
     MSG_WriteByte( msg, svc_EOF );
     if(client->netchan.unsentFragments || client->netchan_start_queue)
     {
         netchan_buffer_t *netbuf;
         Com_DPrintf("#462 SV_Netchan_Transmit: unsent fragments, stacked\n");
         netbuf = (netchan_buffer_t *) Z_Malloc(sizeof(netchan_buffer_t));
         // store the msg, we can't store it encoded, as the encoding depends on stuff we still have to finish sending
         MSG_Copy(&netbuf->msg, netbuf->msgBuffer, sizeof( netbuf->msgBuffer ), msg);
 #ifdef LEGACY_PROTOCOL
         if(client->compat)
         {
             Q_strncpyz(netbuf->clientCommandString, client->lastClientCommandString,
                    sizeof(netbuf->clientCommandString));
         }
 #endif
         netbuf->next = NULL;
         // insert it in the queue, the message will be encoded and sent later
         *client->netchan_end_queue = netbuf;
         client->netchan_end_queue = &(*client->netchan_end_queue)->next;
     }
     else
     {
 #ifdef LEGACY_PROTOCOL
         if(client->compat)
             SV_Netchan_Encode(client, msg, client->lastClientCommandString);
 #endif
         Netchan_Transmit( &client->netchan, msg->cursize, msg->data );
     }
 }
Referenced by SV_SendDownloadMessages(), and SV_SendMessageToClient().
SV_Netchan_TransmitNextFragment()
int SV_Netchan_TransmitNextFragment (client_t * client)
Definition at line 196 of file sv_net_chan.c.
 {
     if(client->netchan.unsentFragments)
     {
         Netchan_TransmitNextFragment(&client->netchan);
         return SV_RateMsec(client);
     }
     else if(client->netchan_start_queue)
     {
         SV_Netchan_TransmitNextInQueue(client);
         return SV_RateMsec(client);
     }
     return -1;
 }
Referenced by SV_SendQueuedMessages().
SV_NumForGentity()
int SV_NumForGentity (sharedEntity_t * ent)
Definition at line 32 of file sv_game.c.
 {
     int     num;
     num = ((byte*)ent - (byte*)sv.gentities) / sv.gentitySize;
     return num;
 }
SV_PointContents()
int SV_PointContents (const vec3_t p, int passEntityNum)
Definition at line 653 of file sv_world.c.
{
     int         touch[MAX_GENTITIES];
     sharedEntity_t *hit;
     int         i, num;
     int         contents, c2;
     clipHandle_t    clipHandle;
     float       *angles;
     // get base contents from world
     contents = CM_PointContents( p, 0 );
     // or in contents from all the other entities
     num = SV_AreaEntities( p, p, touch, MAX_GENTITIES );
     for ( i=0 ; i<num ; i++ ) {
         if ( touch[i] == passEntityNum ) {
             continue;
         }
         hit = SV_GentityNum( touch[i] );
         // might intersect, so do an exact clip
         clipHandle = SV_ClipHandleForEntity( hit );
         angles = hit->r.currentAngles;
         if ( !hit->r.bmodel ) {
             angles = vec3_origin;   // boxes don't rotate
         }
         c2 = CM_TransformedPointContents (p, clipHandle, hit->r.currentOrigin, angles);
         contents |= c2;
     }
     return contents;
 }
Referenced by BotImport_PointContents(), and SV_GameSystemCalls().
SV_RateMsec()
int SV_RateMsec (client_t * client)
Definition at line 1172 of file sv_main.c.
 {
     int rate, rateMsec;
     int messageSize;
     messageSize = client->netchan.lastSentSize;
     rate = client->rate;
     if(sv_maxRate->integer)
     {
         if(sv_maxRate->integer < 1000)
             Cvar_Set( "sv_MaxRate", "1000" );
         if(sv_maxRate->integer < rate)
             rate = sv_maxRate->integer;
     }
     if(sv_minRate->integer)
     {
         if(sv_minRate->integer < 1000)
             Cvar_Set("sv_minRate", "1000");
         if(sv_minRate->integer > rate)
             rate = sv_minRate->integer;
     }
     if(client->netchan.remoteAddress.type == NA_IP6)
         messageSize += UDPIP6_HEADER_SIZE;
     else
         messageSize += UDPIP_HEADER_SIZE;
     rateMsec = messageSize * 1000 / ((int) (rate * com_timescale->value));
     rate = Sys_Milliseconds() - client->netchan.lastSentTime;
     if(rate > rateMsec)
         return 0;
     else
         return rateMsec - rate;
 }
Referenced by SV_Netchan_TransmitNextFragment(), SV_SendClientMessages(), and SV_SendQueuedMessages().
SV_RemoveOperatorCommands()
void SV_RemoveOperatorCommands (void)
Definition at line 1579 of file sv_ccmds.c.
{
 #if 0
     // removing these won't let the server start again
     Cmd_RemoveCommand ("heartbeat");
     Cmd_RemoveCommand ("kick");
     Cmd_RemoveCommand ("kicknum");
     Cmd_RemoveCommand ("clientkick");
     Cmd_RemoveCommand ("kickall");
     Cmd_RemoveCommand ("kickbots");
     Cmd_RemoveCommand ("banUser");
     Cmd_RemoveCommand ("banClient");
     Cmd_RemoveCommand ("status");
     Cmd_RemoveCommand ("serverinfo");
     Cmd_RemoveCommand ("systeminfo");
     Cmd_RemoveCommand ("dumpuser");
     Cmd_RemoveCommand ("map_restart");
     Cmd_RemoveCommand ("sectorlist");
     Cmd_RemoveCommand ("say");
 #endif
 }
Referenced by SV_Shutdown().
SV_RestartGameProgs()
void SV_RestartGameProgs (void)
Definition at line 917 of file sv_game.c.
 {
     if (!gvm) {
         return;
     }
     VM_Call(gvm, GAME_SHUTDOWN, qtrue);
     // do a restart instead of a free
     gvm = VM_Restart(gvm, qtrue);
     if (!gvm) {
         Com_Error(ERR_FATAL, "VM_Restart on game failed");
     }
     SV_InitGameVM(qtrue);
 }
Referenced by SV_MapRestart_f().
SV_SectorList_f()
void SV_SectorList_f (void)
Definition at line 83 of file sv_world.c.
{
     int             i, c;
     worldSector_t   *sec;
     svEntity_t      *ent;
     for ( i = 0 ; i < AREA_NODES ; i++ ) {
         sec = &sv_worldSectors[i];
         c = 0;
         for ( ent = sec->entities ; ent ; ent = ent->nextEntityInWorldSector ) {
             c++;
         }
         Com_Printf( "sector %i: %i entities\n", i, c );
     }
 }
Referenced by SV_AddOperatorCommands().
SV_SendClientMessages()
void SV_SendClientMessages (void)
Definition at line 643 of file sv_snapshot.c.
 {
     int     i;
     client_t    *c;
     // send a message to each connected client
     for(i=0; i < sv_maxclients->integer; i++)
     {
         c = &svs.clients[i];
         if(!c->state)
             continue;       // not connected
         if(svs.time - c->lastSnapshotTime < c->snapshotMsec * com_timescale->value)
             continue;       // It's not time yet
         if(*c->downloadName)
             continue;       // Client is downloading, don't send snapshots
         if(c->netchan.unsentFragments || c->netchan_start_queue)
         {
             c->rateDelayed = qtrue;
             continue;       // Drop this snapshot if the packet queue is still full or delta compression will break
         }
         if(!(c->netchan.remoteAddress.type == NA_LOOPBACK ||
              (sv_lanForceRate->integer && Sys_IsLANAddress(c->netchan.remoteAddress))))
         {
             // rate control for clients not on LAN
             if(SV_RateMsec(c) > 0)
             {
                 // Not enough time since last packet passed through the line
                 c->rateDelayed = qtrue;
                 continue;
             }
         }
         // generate and send a new message
         SV_SendClientSnapshot(c);
         c->lastSnapshotTime = svs.time;
         c->rateDelayed = qfalse;
     }
 }
Referenced by SV_Frame().
SV_SendClientSnapshot()
void SV_SendClientSnapshot (client_t * client)
Definition at line 597 of file sv_snapshot.c.
{
     byte        msg_buf[MAX_MSGLEN];
     msg_t       msg;
     // build the snapshot
     SV_BuildClientSnapshot( client );
     // bots need to have their snapshots build, but
     // the query them directly without needing to be sent
     if ( client->gentity && client->gentity->r.svFlags & SVF_BOT ) {
         return;
     }
     MSG_Init (&msg, msg_buf, sizeof(msg_buf));
     msg.allowoverflow = qtrue;
     // NOTE, MRE: all server->client messages now acknowledge
     // let the client know which reliable clientCommands we have received
     MSG_WriteLong( &msg, client->lastClientCommand );
     // (re)send any reliable server commands
     SV_UpdateServerCommandsToClient( client, &msg );
     // send over all the relevant entityState_t
     // and the playerState_t
     SV_WriteSnapshotToClient( client, &msg );
 #ifdef USE_VOIP
     SV_WriteVoipToClient( client, &msg );
 #endif
     // check for overflow
     if ( msg.overflowed ) {
         Com_Printf ("WARNING: msg overflowed for %s\n", client->name);
         MSG_Clear (&msg);
     }
     SV_SendMessageToClient( &msg, client );
 }
Referenced by SV_FinalMessage(), SV_SendClientMessages(), and SV_VerifyPaks_f().
SV_SendDownloadMessages()
int SV_SendDownloadMessages (void)
Definition at line 1169 of file sv_client.c.
 {
     int i, numDLs = 0, retval;
     client_t *cl;
     msg_t msg;
     byte msgBuffer[MAX_MSGLEN];
     for(i=0; i < sv_maxclients->integer; i++)
     {
         cl = &svs.clients[i];
         if(cl->state && *cl->downloadName)
         {
             MSG_Init(&msg, msgBuffer, sizeof(msgBuffer));
             MSG_WriteLong(&msg, cl->lastClientCommand);
             retval = SV_WriteDownloadToClient(cl, &msg);
             if(retval)
             {
                 MSG_WriteByte(&msg, svc_EOF);
                 SV_Netchan_Transmit(cl, &msg);
                 numDLs += retval;
             }
         }
     }
     return numDLs;
 }
Referenced by SV_SendQueuedPackets().
SV_SendMessageToClient()
void SV_SendMessageToClient (msg_t * msg, client_t * client)
Definition at line 577 of file sv_snapshot.c.
 {
     // record information about the message
     client->frames[client->netchan.outgoingSequence & PACKET_MASK].messageSize = msg->cursize;
     client->frames[client->netchan.outgoingSequence & PACKET_MASK].messageSent = svs.time;
     client->frames[client->netchan.outgoingSequence & PACKET_MASK].messageAcked = -1;
     // send the datagram
     SV_Netchan_Transmit(client, msg);
 }
Referenced by SV_SendClientGameState(), and SV_SendClientSnapshot().
SV_SendQueuedMessages()
int SV_SendQueuedMessages (void)
Definition at line 1136 of file sv_client.c.
 {
     int i, retval = -1, nextFragT;
     client_t *cl;
     for(i=0; i < sv_maxclients->integer; i++)
     {
         cl = &svs.clients[i];
         if(cl->state)
         {
             nextFragT = SV_RateMsec(cl);
             if(!nextFragT)
                 nextFragT = SV_Netchan_TransmitNextFragment(cl);
             if(nextFragT >= 0 && (retval == -1 || retval > nextFragT))
                 retval = nextFragT;
         }
     }
     return retval;
 }
Referenced by SV_SendQueuedPackets().
SV_SendServerCommand()
void QDECL SV_SendServerCommand (client_t * cl, const char * fmt, ...)
Referenced by SV_ConSay_f(), SV_ConSayto_f(), SV_ConTell_f(), SV_DropClient(), SV_FinalMessage(), SV_GameSendServerCommand(), and SV_SendConfigstring().
SV_SetConfigstring()
void SV_SetConfigstring (int index, const char * val)
Definition at line 106 of file sv_init.c.
{
     int     i;
     client_t    *client;
     if ( index < 0 || index >= MAX_CONFIGSTRINGS ) {
         Com_Error (ERR_DROP, "SV_SetConfigstring: bad index %i", index);
     }
     if ( !val ) {
         val = "";
     }
     // don't bother broadcasting an update if no change
     if ( !strcmp( val, sv.configstrings[ index ] ) ) {
         return;
     }
     // change the string in sv
     Z_Free( sv.configstrings[index] );
     sv.configstrings[index] = CopyString( val );
     // send it to all the clients if we aren't
     // spawning a new server
     if ( sv.state == SS_GAME || sv.restarting ) {
         // send the data to all relevant clients
         for (i = 0, client = svs.clients; i < sv_maxclients->integer ; i++, client++) {
             if ( client->state < CS_ACTIVE ) {
                 if ( client->state == CS_PRIMED )
                     client->csUpdated[ index ] = qtrue;
                 continue;
             }
             // do not always send server info to all clients
             if ( index == CS_SERVERINFO && client->gentity && (client->gentity->r.svFlags & SVF_NOSERVERINFO) ) {
                 continue;
             }
             SV_SendConfigstring(client, index);
         }
     }
 }
Referenced by SV_Frame(), SV_GameSystemCalls(), SV_MapRestart_f(), SV_RankNewGameCBF(), and SV_SpawnServer().
SV_SetUserinfo()
void SV_SetUserinfo (int index, const char * val)
Definition at line 176 of file sv_init.c.
{
     if ( index < 0 || index >= sv_maxclients->integer ) {
         Com_Error (ERR_DROP, "SV_SetUserinfo: bad index %i", index);
     }
     if ( !val ) {
         val = "";
     }
     Q_strncpyz( svs.clients[index].userinfo, val, sizeof( svs.clients[ index ].userinfo ) );
     Q_strncpyz( svs.clients[index].name, Info_ValueForKey( val, "name" ), sizeof(svs.clients[index].name) );
 }
Referenced by SV_DropClient(), and SV_GameSystemCalls().
SV_ShutdownGameProgs()
void SV_ShutdownGameProgs (void)
Definition at line 871 of file sv_game.c.
 {
     if (!gvm) {
         return;
     }
     VM_Call(gvm, GAME_SHUTDOWN, qfalse);
     VM_Free(gvm);
     gvm = NULL;
 }
SV_SpawnServer()
void SV_SpawnServer (char * server, qboolean killBots)
Definition at line 398 of file sv_init.c.
{
     int         i;
     int         checksum;
     qboolean    isBot;
     char        systemInfo[16384];
     const char  *p;
     // shut down the existing game if it is running
     SV_ShutdownGameProgs();
     Com_Printf ("------ Server Initialization ------\n");
     Com_Printf ("Server: %s\n",server);
     // if not running a dedicated server CL_MapLoading will connect the client to the server
     // also print some status stuff
     CL_MapLoading();
     // make sure all the client stuff is unloaded
     CL_ShutdownAll(qfalse);
     // clear the whole hunk because we're (re)loading the server
     Hunk_Clear();
     // clear collision map data
     CM_ClearMap();
     // init client structures and svs.numSnapshotEntities
     if ( !Cvar_VariableValue("sv_running") ) {
         SV_Startup();
     } else {
         // check for maxclients change
         if ( sv_maxclients->modified ) {
             SV_ChangeMaxClients();
         }
     }
     // clear pak references
     FS_ClearPakReferences(0);
     // allocate the snapshot entities on the hunk
     svs.snapshotEntities = Hunk_Alloc( sizeof(entityState_t)*svs.numSnapshotEntities, h_high );
     svs.nextSnapshotEntities = 0;
     // toggle the server bit so clients can detect that a
     // server has changed
     svs.snapFlagServerBit ^= SNAPFLAG_SERVERCOUNT;
     // set nextmap to the same map, but it may be overriden
     // by the game startup or another console command
     Cvar_Set( "nextmap", "map_restart 0");
 //  Cvar_Set( "nextmap", va("map %s", server) );
     for (i=0 ; i<sv_maxclients->integer ; i++) {
         // save when the server started for each client already connected
         if (svs.clients[i].state >= CS_CONNECTED) {
             svs.clients[i].oldServerTime = sv.time;
         }
     }
     // wipe the entire per-level structure
     SV_ClearServer();
     for ( i = 0 ; i < MAX_CONFIGSTRINGS ; i++ ) {
         sv.configstrings[i] = CopyString("");
     }
     // make sure we are not paused
     Cvar_Set("cl_paused", "0");
     // get a new checksum feed and restart the file system
     sv.checksumFeed = ( ((unsigned int)rand() << 16) ^ (unsigned int)rand() ) ^ Com_Milliseconds();
     FS_Restart( sv.checksumFeed );
     CM_LoadMap( va("maps/%s.bsp", server), qfalse, &checksum );
     // set serverinfo visible name
     Cvar_Set( "mapname", server );
     Cvar_Set( "sv_mapChecksum", va("%i",checksum) );
     // serverid should be different each time
     sv.serverId = com_frameTime;
     sv.restartedServerId = sv.serverId; // I suppose the init here is just to be safe
     sv.checksumFeedServerId = sv.serverId;
     Cvar_Set( "sv_serverid", va("%i", sv.serverId ) );
     // clear physics interaction links
     SV_ClearWorld ();
     // media configstring setting should be done during
     // the loading stage, so connected clients don't have
     // to load during actual gameplay
     sv.state = SS_LOADING;
     // load and spawn all other entities
     SV_InitGameProgs();
     // don't allow a map_restart if game is modified
     sv_gametype->modified = qfalse;
     // run a few frames to allow everything to settle
     for (i = 0;i < 3; i++)
     {
         VM_Call (gvm, GAME_RUN_FRAME, sv.time);
         SV_BotFrame (sv.time);
         sv.time += 100;
         svs.time += 100;
     }
     // create a baseline for more efficient communications
     SV_CreateBaseline ();
     for (i=0 ; i<sv_maxclients->integer ; i++) {
         // send the new gamestate to all connected clients
         if (svs.clients[i].state >= CS_CONNECTED) {
             char    *denied;
             if ( svs.clients[i].netchan.remoteAddress.type == NA_BOT ) {
                 if ( killBots ) {
                     SV_DropClient( &svs.clients[i], "" );
                     continue;
                 }
                 isBot = qtrue;
             }
             else {
                 isBot = qfalse;
             }
             // connect the client again
             denied = VM_ExplicitArgPtr( gvm, VM_Call( gvm, GAME_CLIENT_CONNECT, i, qfalse, isBot ) );   // firstTime = qfalse
             if ( denied ) {
                 // this generally shouldn't happen, because the client
                 // was connected before the level change
                 SV_DropClient( &svs.clients[i], denied );
             } else {
                 if( !isBot ) {
                     // when we get the next packet from a connected client,
                     // the new gamestate will be sent
                     svs.clients[i].state = CS_CONNECTED;
                 }
                 else {
                     client_t        *client;
                     sharedEntity_t  *ent;
                     client = &svs.clients[i];
                     client->state = CS_ACTIVE;
                     ent = SV_GentityNum( i );
                     ent->s.number = i;
                     client->gentity = ent;
                     client->deltaMessage = -1;
                     client->lastSnapshotTime = 0;   // generate a snapshot immediately
                     VM_Call( gvm, GAME_CLIENT_BEGIN, i );
                 }
             }
         }
     }
     // run another frame to allow things to look at all the players
     VM_Call (gvm, GAME_RUN_FRAME, sv.time);
     SV_BotFrame (sv.time);
     sv.time += 100;
     svs.time += 100;
     if ( sv_pure->integer ) {
         // the server sends these to the clients so they will only
         // load pk3s also loaded at the server
         p = FS_LoadedPakChecksums();
         Cvar_Set( "sv_paks", p );
         if (strlen(p) == 0) {
             Com_Printf( "WARNING: sv_pure set but no PK3 files loaded\n" );
         }
         p = FS_LoadedPakNames();
         Cvar_Set( "sv_pakNames", p );
         // we need to touch the cgame and ui qvm because they could be in
         // separate pk3 files and the client will need to download the pk3
         // files with the latest cgame and ui qvm to pass the pure check
         SV_TouchFile( "vm/cgame.qvm" );
         SV_TouchFile( "vm/ui.qvm" );
     }
     else {
         Cvar_Set( "sv_paks", "" );
         Cvar_Set( "sv_pakNames", "" );
     }
     // the server sends these to the clients so they can figure
     // out which pk3s should be auto-downloaded
     p = FS_ReferencedPakChecksums();
     Cvar_Set( "sv_referencedPaks", p );
     p = FS_ReferencedPakNames();
     Cvar_Set( "sv_referencedPakNames", p );
     // save systeminfo and serverinfo strings
     Q_strncpyz( systemInfo, Cvar_InfoString_Big( CVAR_SYSTEMINFO ), sizeof( systemInfo ) );
     cvar_modifiedFlags &= ~CVAR_SYSTEMINFO;
     SV_SetConfigstring( CS_SYSTEMINFO, systemInfo );
     SV_SetConfigstring( CS_SERVERINFO, Cvar_InfoString( CVAR_SERVERINFO ) );
     cvar_modifiedFlags &= ~CVAR_SERVERINFO;
     // any media configstring setting now should issue a warning
     // and any configstring changes should be reliably transmitted
     // to all clients
     sv.state = SS_GAME;
     // send a heartbeat now so the master will get up to date info
     SV_Heartbeat_f();
     Hunk_SetMark();
 #ifndef DEDICATED
     if ( com_dedicated->integer ) {
         // restart renderer in order to show console for dedicated servers
         // launched through the regular binary
         CL_StartHunkUsers( qtrue );
     }
 #endif
     Com_Printf ("-----------------------------------\n");
 }
Referenced by SV_Map_f(), and SV_MapRestart_f().
SV_SvEntityForGentity()
svEntity_t* SV_SvEntityForGentity (sharedEntity_t * gEnt)
Definition at line 59 of file sv_game.c.
 {
     if (!gEnt || gEnt->s.number < 0 || gEnt->s.number >= MAX_GENTITIES) {
         Com_Error(ERR_DROP, "SV_SvEntityForGentity: bad gEnt");
     }
     return &sv.svEntities[gEnt->s.number];
 }
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_AdjustAreaPortalState(), SV_LinkEntity(), and SV_UnlinkEntity().
SV_Trace()
void SV_Trace (trace_t * results, const vec3_t start, vec3_t mins, vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask, int capsule)
Definition at line 596 of file sv_world.c.
{
     moveclip_t  clip;
     int         i;
     if ( !mins ) {
         mins = vec3_origin;
     }
     if ( !maxs ) {
         maxs = vec3_origin;
     }
     Com_Memset ( &clip, 0, sizeof ( moveclip_t ) );
     // clip to world
     CM_BoxTrace( &clip.trace, start, end, mins, maxs, 0, contentmask, capsule );
     clip.trace.entityNum = clip.trace.fraction != 1.0 ? ENTITYNUM_WORLD : ENTITYNUM_NONE;
     if ( clip.trace.fraction == 0 ) {
         *results = clip.trace;
         return;     // blocked immediately by the world
     }
     clip.contentmask = contentmask;
     clip.start = start;
 //  VectorCopy( clip.trace.endpos, clip.end );
     VectorCopy( end, clip.end );
     clip.mins = mins;
     clip.maxs = maxs;
     clip.passEntityNum = passEntityNum;
     clip.capsule = capsule;
     // create the bounding box of the entire move
     // we can limit it to the part of the move not
     // already clipped off by the world, which can be
     // a significant savings for line of sight and shot traces
     for ( i=0 ; i<3 ; i++ ) {
         if ( end[i] > start[i] ) {
             clip.boxmins[i] = clip.start[i] + clip.mins[i] - 1;
             clip.boxmaxs[i] = clip.end[i] + clip.maxs[i] + 1;
         } else {
             clip.boxmins[i] = clip.end[i] + clip.mins[i] - 1;
             clip.boxmaxs[i] = clip.start[i] + clip.maxs[i] + 1;
         }
     }
     // clip to other solid entities
     SV_ClipMoveToEntities ( &clip );
     *results = clip.trace;
 }
Referenced by BotImport_Trace(), and SV_GameSystemCalls().
SV_UnlinkEntity()
void SV_UnlinkEntity (sharedEntity_t * ent)
Definition at line 167 of file sv_world.c.
{
     svEntity_t      *ent;
     svEntity_t      *scan;
     worldSector_t   *ws;
     ent = SV_SvEntityForGentity( gEnt );
     gEnt->r.linked = qfalse;
     ws = ent->worldSector;
     if ( !ws ) {
         return;     // not linked in anywhere
     }
     ent->worldSector = NULL;
     if ( ws->entities == ent ) {
         ws->entities = ent->nextEntityInWorldSector;
         return;
     }
     for ( scan = ws->entities ; scan ; scan = scan->nextEntityInWorldSector ) {
         if ( scan->nextEntityInWorldSector == ent ) {
             scan->nextEntityInWorldSector = ent->nextEntityInWorldSector;
             return;
         }
     }
     Com_Printf( "WARNING: SV_UnlinkEntity: not found in worldSector\n" );
 }
Referenced by SV_GameSystemCalls(), and SV_LinkEntity().
SV_UpdateConfigstrings()
void SV_UpdateConfigstrings (client_t * client)
Definition at line 81 of file sv_init.c.
 {
     int index;
     for( index = 0; index < MAX_CONFIGSTRINGS; index++ ) {
         // if the CS hasn't changed since we went to CS_PRIMED, ignore
         if(!client->csUpdated[index])
             continue;
         // do not always send server info to all clients
         if ( index == CS_SERVERINFO && client->gentity &&
             (client->gentity->r.svFlags & SVF_NOSERVERINFO) ) {
             continue;
         }
         SV_SendConfigstring(client, index);
         client->csUpdated[index] = qfalse;
     }
 }
Referenced by SV_ClientEnterWorld().
SV_UpdateServerCommandsToClient()
void SV_UpdateServerCommandsToClient (client_t * client, msg_t * msg)
Definition at line 218 of file sv_snapshot.c.
{
     int     i;
     // write any unacknowledged serverCommands
     for ( i = client->reliableAcknowledge + 1 ; i <= client->reliableSequence ; i++ ) {
         MSG_WriteByte( msg, svc_serverCommand );
         MSG_WriteLong( msg, i );
         MSG_WriteString( msg, client->reliableCommands[ i & (MAX_RELIABLE_COMMANDS-1) ] );
     }
     client->reliableSent = client->reliableSequence;
 }
Referenced by SV_SendClientGameState(), and SV_SendClientSnapshot().
SV_UserinfoChanged()
void SV_UserinfoChanged (client_t * cl)
Definition at line 1390 of file sv_client.c.
{
     char    *val;
     char    *ip;
     int     i;
     int len;
     // name for C code
     Q_strncpyz( cl->name, Info_ValueForKey (cl->userinfo, "name"), sizeof(cl->name) );
     // rate command
     // if the client is on the same subnet as the server and we aren't running an
     // internet public server, assume they don't need a rate choke
     if ( Sys_IsLANAddress( cl->netchan.remoteAddress ) && com_dedicated->integer != 2 && sv_lanForceRate->integer == 1) {
         cl->rate = 99999;   // lans should not rate limit
     } else {
         val = Info_ValueForKey (cl->userinfo, "rate");
         if (strlen(val)) {
             i = atoi(val);
             cl->rate = i;
             if (cl->rate < 1000) {
                 cl->rate = 1000;
             } else if (cl->rate > 90000) {
                 cl->rate = 90000;
             }
         } else {
             cl->rate = 3000;
         }
     }
     val = Info_ValueForKey (cl->userinfo, "handicap");
     if (strlen(val)) {
         i = atoi(val);
         if (i<=0 || i>100 || strlen(val) > 4) {
             Info_SetValueForKey( cl->userinfo, "handicap", "100" );
         }
     }
     // snaps command
     val = Info_ValueForKey (cl->userinfo, "snaps");
     if(strlen(val))
     {
         i = atoi(val);
         if(i < 1)
             i = 1;
         else if(i > sv_fps->integer)
             i = sv_fps->integer;
         i = 1000 / i;
     }
     else
         i = 50;
     if(i != cl->snapshotMsec)
     {
         // Reset last sent snapshot so we avoid desync between server frame time and snapshot send time
         cl->lastSnapshotTime = 0;
         cl->snapshotMsec = i;
     }
 #ifdef USE_VOIP
 #ifdef LEGACY_PROTOCOL
     if(cl->compat)
         cl->hasVoip = qfalse;
     else
 #endif
     {
         val = Info_ValueForKey(cl->userinfo, "cl_voipProtocol");
         cl->hasVoip = !Q_stricmp( val, "opus" );
     }
 #endif
     // TTimo
     // maintain the IP information
     // the banning code relies on this being consistently present
     if( NET_IsLocalAddress(cl->netchan.remoteAddress) )
         ip = "localhost";
     else
         ip = (char*)NET_AdrToString( cl->netchan.remoteAddress );
     val = Info_ValueForKey( cl->userinfo, "ip" );
     if( val[0] )
         len = strlen( ip ) - strlen( val ) + strlen( cl->userinfo );
     else
         len = strlen( ip ) + 4 + strlen( cl->userinfo );
     if( len >= MAX_INFO_STRING )
         SV_DropClient( cl, "userinfo string length exceeded" );
     else
         Info_SetValueForKey( cl->userinfo, "ip", ip );
 }
Referenced by SV_DirectConnect(), and SV_UpdateUserinfo_f().
SV_WriteDownloadToClient()
int SV_WriteDownloadToClient (client_t * cl, msg_t * msg)
Definition at line 929 of file sv_client.c.
 {
     int curindex;
     int unreferenced = 1;
     char errorMessage[1024];
     char pakbuf[MAX_QPATH], *pakptr;
     int numRefPaks;
     if (!*cl->downloadName)
         return 0;   // Nothing being downloaded
     if(!cl->download)
     {
         qboolean idPack = qfalse;
         #ifndef STANDALONE
         qboolean missionPack = qfalse;
         #endif
         // Chop off filename extension.
         Com_sprintf(pakbuf, sizeof(pakbuf), "%s", cl->downloadName);
         pakptr = strrchr(pakbuf, '.');
         if(pakptr)
         {
             *pakptr = '\0';
             // Check for pk3 filename extension
             if(!Q_stricmp(pakptr + 1, "pk3"))
             {
                 const char *referencedPaks = FS_ReferencedPakNames();
                 // Check whether the file appears in the list of referenced
                 // paks to prevent downloading of arbitrary files.
                 Cmd_TokenizeStringIgnoreQuotes(referencedPaks);
                 numRefPaks = Cmd_Argc();
                 for(curindex = 0; curindex < numRefPaks; curindex++)
                 {
                     if(!FS_FilenameCompare(Cmd_Argv(curindex), pakbuf))
                     {
                         unreferenced = 0;
                         // now that we know the file is referenced,
                         // check whether it's legal to download it.
 #ifndef STANDALONE
                         missionPack = FS_idPak(pakbuf, BASETA, NUM_TA_PAKS);
                         idPack = missionPack;
 #endif
                         idPack = idPack || FS_idPak(pakbuf, BASEGAME, NUM_ID_PAKS);
                         break;
                     }
                 }
             }
         }
         cl->download = 0;
         // We open the file here
         if ( !(sv_allowDownload->integer & DLF_ENABLE) ||
             (sv_allowDownload->integer & DLF_NO_UDP) ||
             idPack || unreferenced ||
             ( cl->downloadSize = FS_SV_FOpenFileRead( cl->downloadName, &cl->download ) ) < 0 ) {
             // cannot auto-download file
             if(unreferenced)
             {
                 Com_Printf("clientDownload: %d : \"%s\" is not referenced and cannot be downloaded.\n", (int) (cl - svs.clients), cl->downloadName);
                 Com_sprintf(errorMessage, sizeof(errorMessage), "File \"%s\" is not referenced and cannot be downloaded.", cl->downloadName);
             }
             else if (idPack) {
                 Com_Printf("clientDownload: %d : \"%s\" cannot download id pk3 files\n", (int) (cl - svs.clients), cl->downloadName);
 #ifndef STANDALONE
                 if(missionPack)
                 {
                     Com_sprintf(errorMessage, sizeof(errorMessage), "Cannot autodownload Team Arena file \"%s\"\n"
                                     "The Team Arena mission pack can be found in your local game store.", cl->downloadName);
                 }
                 else
 #endif
                 {
                     Com_sprintf(errorMessage, sizeof(errorMessage), "Cannot autodownload id pk3 file \"%s\"", cl->downloadName);
                 }
             }
             else if ( !(sv_allowDownload->integer & DLF_ENABLE) ||
                 (sv_allowDownload->integer & DLF_NO_UDP) ) {
                 Com_Printf("clientDownload: %d : \"%s\" download disabled\n", (int) (cl - svs.clients), cl->downloadName);
                 if (sv_pure->integer) {
                     Com_sprintf(errorMessage, sizeof(errorMessage), "Could not download \"%s\" because autodownloading is disabled on the server.\n\n"
                                         "You will need to get this file elsewhere before you "
                                         "can connect to this pure server.\n", cl->downloadName);
                 } else {
                     Com_sprintf(errorMessage, sizeof(errorMessage), "Could not download \"%s\" because autodownloading is disabled on the server.\n\n"
                     "The server you are connecting to is not a pure server, "
                     "set autodownload to No in your settings and you might be "
                     "able to join the game anyway.\n", cl->downloadName);
                 }
             } else {
         // NOTE TTimo this is NOT supposed to happen unless bug in our filesystem scheme?
         //   if the pk3 is referenced, it must have been found somewhere in the filesystem
                 Com_Printf("clientDownload: %d : \"%s\" file not found on server\n", (int) (cl - svs.clients), cl->downloadName);
                 Com_sprintf(errorMessage, sizeof(errorMessage), "File \"%s\" not found on server for autodownloading.\n", cl->downloadName);
             }
             MSG_WriteByte( msg, svc_download );
             MSG_WriteShort( msg, 0 ); // client is expecting block zero
             MSG_WriteLong( msg, -1 ); // illegal file size
             MSG_WriteString( msg, errorMessage );
             *cl->downloadName = 0;
             if(cl->download)
                 FS_FCloseFile(cl->download);
             return 1;
         }
         Com_Printf( "clientDownload: %d : beginning \"%s\"\n", (int) (cl - svs.clients), cl->downloadName );
         // Init
         cl->downloadCurrentBlock = cl->downloadClientBlock = cl->downloadXmitBlock = 0;
         cl->downloadCount = 0;
         cl->downloadEOF = qfalse;
     }
     // Perform any reads that we need to
     while (cl->downloadCurrentBlock - cl->downloadClientBlock < MAX_DOWNLOAD_WINDOW &&
         cl->downloadSize != cl->downloadCount) {
         curindex = (cl->downloadCurrentBlock % MAX_DOWNLOAD_WINDOW);
         if (!cl->downloadBlocks[curindex])
             cl->downloadBlocks[curindex] = Z_Malloc(MAX_DOWNLOAD_BLKSIZE);
         cl->downloadBlockSize[curindex] = FS_Read( cl->downloadBlocks[curindex], MAX_DOWNLOAD_BLKSIZE, cl->download );
         if (cl->downloadBlockSize[curindex] < 0) {
             // EOF right now
             cl->downloadCount = cl->downloadSize;
             break;
         }
         cl->downloadCount += cl->downloadBlockSize[curindex];
         // Load in next block
         cl->downloadCurrentBlock++;
     }
     // Check to see if we have eof condition and add the EOF block
     if (cl->downloadCount == cl->downloadSize &&
         !cl->downloadEOF &&
         cl->downloadCurrentBlock - cl->downloadClientBlock < MAX_DOWNLOAD_WINDOW) {
         cl->downloadBlockSize[cl->downloadCurrentBlock % MAX_DOWNLOAD_WINDOW] = 0;
         cl->downloadCurrentBlock++;
         cl->downloadEOF = qtrue;  // We have added the EOF block
     }
     if (cl->downloadClientBlock == cl->downloadCurrentBlock)
         return 0; // Nothing to transmit
     // Write out the next section of the file, if we have already reached our window,
     // automatically start retransmitting
     if (cl->downloadXmitBlock == cl->downloadCurrentBlock)
     {
         // We have transmitted the complete window, should we start resending?
         if (svs.time - cl->downloadSendTime > 1000)
             cl->downloadXmitBlock = cl->downloadClientBlock;
         else
             return 0;
     }
     // Send current block
     curindex = (cl->downloadXmitBlock % MAX_DOWNLOAD_WINDOW);
     MSG_WriteByte( msg, svc_download );
     MSG_WriteShort( msg, cl->downloadXmitBlock );
     // block zero is special, contains file size
     if ( cl->downloadXmitBlock == 0 )
         MSG_WriteLong( msg, cl->downloadSize );
     MSG_WriteShort( msg, cl->downloadBlockSize[curindex] );
     // Write the block
     if(cl->downloadBlockSize[curindex])
         MSG_WriteData(msg, cl->downloadBlocks[curindex], cl->downloadBlockSize[curindex]);
     Com_DPrintf( "clientDownload: %d : writing block %d\n", (int) (cl - svs.clients), cl->downloadXmitBlock );
     // Move on to the next block
     // It will get sent with next snap shot.  The rate will keep us in line.
     cl->downloadXmitBlock++;
     cl->downloadSendTime = svs.time;
     return 1;
 }
Referenced by SV_SendDownloadMessages().
SV_WriteFrameToClient()
void SV_WriteFrameToClient (client_t * client, msg_t * msg)
SVC_RateLimit()
qboolean SVC_RateLimit (leakyBucket_t * bucket, int burst, int period)
Definition at line 480 of file sv_main.c.
{
     if ( bucket != NULL ) {
         int now = Sys_Milliseconds();
         int interval = now - bucket->lastTime;
         int expired = interval / period;
         int expiredRemainder = interval % period;
         if ( expired > bucket->burst || interval < 0 ) {
             bucket->burst = 0;
             bucket->lastTime = now;
         } else {
             bucket->burst -= expired;
             bucket->lastTime = now - expiredRemainder;
         }
         if ( bucket->burst < burst ) {
             bucket->burst++;
             return qfalse;
         }
     }
     return qtrue;
 }
Referenced by SV_GetChallenge(), SVC_Info(), SVC_RateLimitAddress(), SVC_RemoteCommand(), and SVC_Status().
SVC_RateLimitAddress()
qboolean SVC_RateLimitAddress (netadr_t from, int burst, int period)
Definition at line 512 of file sv_main.c.
{
     leakyBucket_t *bucket = SVC_BucketForAddress( from, burst, period );
     return SVC_RateLimit( bucket, burst, period );
 }
Referenced by SV_GetChallenge(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().
Variable Documentation
gvm
vm_t* gvm
Definition at line 32 of file sv_main.c.
Referenced by SV_BotFrame(), SV_ClientEnterWorld(), SV_ClientThink(), SV_DirectConnect(), SV_DropClient(), SV_ExecuteClientCommand(), SV_Frame(), SV_GameCommand(), SV_InitGameProgs(), SV_InitGameVM(), SV_MapRestart_f(), SV_RestartGameProgs(), SV_ShutdownGameProgs(), SV_SpawnServer(), and SV_UpdateUserinfo_f().
outboundLeakyBucket
leakyBucket_t outboundLeakyBucket
Definition at line 363 of file sv_main.c.
Referenced by SV_GetChallenge(), SVC_Info(), and SVC_Status().
serverBans
serverBan_t serverBans[SERVER_MAXBANS]
Definition at line 66 of file sv_main.c.
Referenced by SV_AddBanToList(), SV_DelBanEntryFromList(), SV_DelBanFromList(), SV_IsBanned(), SV_ListBans_f(), SV_RehashBans_f(), and SV_WriteBans().
serverBansCount
int serverBansCount
Definition at line 67 of file sv_main.c.
Referenced by SV_AddBanToList(), SV_DelBanEntryFromList(), SV_DelBanFromList(), SV_FlushBans_f(), SV_IsBanned(), SV_ListBans_f(), SV_RehashBans_f(), and SV_WriteBans().
sv
server_t sv
Definition at line 31 of file sv_main.c.
Referenced by Com_Frame(), SV_AddEntitiesVisibleFromPoint(), SV_AddEntToSnapshot(), SV_AreaEntities_r(), SV_BuildClientSnapshot(), SV_ClearServer(), SV_CreateBaseline(), SV_EmitPacketEntities(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_Frame(), SV_FrameMsec(), SV_GameClientNum(), SV_GameCommand(), SV_GameSystemCalls(), SV_GEntityForSvEntity(), SV_GentityNum(), SV_GetConfigstring(), SV_InitGameVM(), SV_LinkEntity(), SV_LocateGameData(), SV_MapRestart_f(), SV_NumForGentity(), SV_SendClientGameState(), SV_SendConfigstring(), SV_SetConfigstring(), SV_SpawnServer(), SV_SvEntityForGentity(), SV_UserMove(), SV_VerifyPaks_f(), and SV_WriteSnapshotToClient().
sv_allowDownload
cvar_t* sv_allowDownload
Definition at line 39 of file sv_main.c.
Referenced by SV_Init(), and SV_WriteDownloadToClient().
sv_banFile
cvar_t* sv_banFile
Definition at line 64 of file sv_main.c.
Referenced by SV_Init(), SV_RehashBans_f(), and SV_WriteBans().
sv_dlRate
cvar_t* sv_dlRate
Definition at line 54 of file sv_main.c.
Referenced by SV_Init(), and SV_SendQueuedPackets().
sv_floodProtect
cvar_t* sv_floodProtect
Definition at line 59 of file sv_main.c.
Referenced by SV_ClientCommand(), and SV_Init().
sv_fps
cvar_t* sv_fps
Definition at line 34 of file sv_main.c.
Referenced by SV_Frame(), SV_FrameMsec(), SV_Init(), and SV_UserinfoChanged().
sv_gametype
cvar_t* sv_gametype
Definition at line 57 of file sv_main.c.
Referenced by SV_Init(), SV_Map_f(), SV_MapRestart_f(), SV_SpawnServer(), and SVC_Info().
sv_hostname
cvar_t* sv_hostname
Definition at line 43 of file sv_main.c.
Referenced by SV_Init(), and SVC_Info().
sv_killserver
cvar_t* sv_killserver
Definition at line 48 of file sv_main.c.
Referenced by SV_Frame(), SV_Init(), SV_Shutdown(), and SV_Startup().
sv_lanForceRate
cvar_t* sv_lanForceRate
Definition at line 60 of file sv_main.c.
Referenced by SV_Init(), SV_SendClientMessages(), and SV_UserinfoChanged().
sv_mapChecksum
cvar_t* sv_mapChecksum
Definition at line 50 of file sv_main.c.
Referenced by SV_Init().
sv_mapname
cvar_t* sv_mapname
Definition at line 49 of file sv_main.c.
Referenced by SV_Init(), SV_Status_f(), and SVC_Info().
sv_master
cvar_t* sv_master[MAX_MASTER_SERVERS]
Definition at line 44 of file sv_main.c.
Referenced by SV_Init(), and SV_MasterHeartbeat().
sv_maxclients
cvar_t* sv_maxclients
Definition at line 40 of file sv_main.c.
Referenced by SV_BotAllocateClient(), SV_BotFreeClient(), SV_BoundMaxClients(), SV_CalcPings(), SV_ChangeMaxClients(), SV_CompletePlayerName(), SV_DirectConnect(), SV_DropClient(), SV_GameDropClient(), SV_GameSendServerCommand(), SV_GetPlayerByNum(), SV_GetUsercmd(), SV_GetUserinfo(), SV_Init(), SV_InitGameVM(), SV_MapRestart_f(), SV_RankBegin(), SV_RankEnd(), SV_RankJoinGameCBF(), SV_RankNewGameCBF(), SV_RankQuit(), SV_RankUserValidate(), SV_SendClientMessages(), SV_SendDownloadMessages(), SV_SendQueuedMessages(), SV_SetUserinfo(), SV_Shutdown(), SV_SpawnServer(), SV_Startup(), SVC_Info(), and SVC_Status().
sv_maxPing
cvar_t* sv_maxPing
Definition at line 56 of file sv_main.c.
Referenced by SV_DirectConnect(), SV_Init(), and SVC_Info().
sv_maxRate
cvar_t* sv_maxRate
Definition at line 53 of file sv_main.c.
Referenced by SV_Init(), and SV_RateMsec().
sv_minPing
cvar_t* sv_minPing
Definition at line 55 of file sv_main.c.
Referenced by SV_DirectConnect(), SV_Init(), and SVC_Info().
sv_minRate
cvar_t* sv_minRate
Definition at line 52 of file sv_main.c.
Referenced by SV_Init(), and SV_RateMsec().
sv_padPackets
cvar_t* sv_padPackets
Definition at line 47 of file sv_main.c.
Referenced by SV_Init(), and SV_WriteSnapshotToClient().
sv_privateClients
cvar_t* sv_privateClients
Definition at line 42 of file sv_main.c.
Referenced by SV_DirectConnect(), SV_Init(), and SVC_Info().
sv_privatePassword
cvar_t* sv_privatePassword
Definition at line 38 of file sv_main.c.
Referenced by SV_DirectConnect(), and SV_Init().
sv_pure
cvar_t* sv_pure
Definition at line 58 of file sv_main.c.
Referenced by SV_Init(), SV_SpawnServer(), SV_UserMove(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), and SVC_Info().
sv_rconPassword
cvar_t* sv_rconPassword
Definition at line 37 of file sv_main.c.
Referenced by SV_Init(), and SVC_RemoteCommand().
sv_reconnectlimit
cvar_t* sv_reconnectlimit
Definition at line 45 of file sv_main.c.
Referenced by SV_DirectConnect(), and SV_Init().
sv_serverid
cvar_t* sv_serverid
Definition at line 51 of file sv_main.c.
Referenced by SV_Init().
sv_showloss
cvar_t* sv_showloss
Definition at line 46 of file sv_main.c.
Referenced by SV_Init().
sv_strictAuth
cvar_t* sv_strictAuth
Definition at line 62 of file sv_main.c.
Referenced by SV_GetChallenge(), and SV_Init().
sv_timeout
cvar_t* sv_timeout
Definition at line 35 of file sv_main.c.
Referenced by SV_CheckTimeouts(), and SV_Init().
sv_zombietime
cvar_t* sv_zombietime
Definition at line 36 of file sv_main.c.
Referenced by SV_CheckTimeouts(), and SV_Init().
svs
serverStatic_t svs
Definition at line 30 of file sv_main.c.
Referenced by BotClientCommand(), BotDrawDebugPolygons(), SV_AuthorizeIpPacket(), SV_Ban_f(), SV_BanNum_f(), SV_BotAllocateClient(), SV_BotFreeClient(), SV_BotGetConsoleMessage(), SV_BotGetSnapshotEntity(), SV_BuildClientSnapshot(), SV_CalcPings(), SV_ChangeMaxClients(), SV_CheckPaused(), SV_CheckTimeouts(), SV_ClientCommand(), SV_ClientEnterWorld(), SV_ClientThink(), SV_CompletePlayerName(), SV_ConSayto_f(), SV_DirectConnect(), SV_DropClient(), SV_EmitPacketEntities(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_FinalMessage(), SV_FlushRedirect(), SV_Frame(), SV_GameDropClient(), SV_GameSendServerCommand(), SV_GameSystemCalls(), SV_GetChallenge(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_GetUsercmd(), SV_GetUserinfo(), SV_Heartbeat_f(), SV_InitGameVM(), SV_Kick_f(), SV_KickAll_f(), SV_KickBots_f(), SV_KickNum_f(), SV_MapRestart_f(), SV_MasterHeartbeat(), SV_MasterShutdown(), SV_NextDownload_f(), SV_PacketEvent(), SV_SendClientGameState(), SV_SendClientMessages(), SV_SendDownloadMessages(), SV_SendMessageToClient(), SV_SendQueuedMessages(), SV_SendServerCommand(), SV_SetConfigstring(), SV_SetUserinfo(), SV_Shutdown(), SV_SpawnServer(), SV_Startup(), SV_Status_f(), SV_StopDownload_f(), SV_UpdateUserinfo_f(), SV_UserMove(), SV_WriteDownloadToClient(), SV_WriteSnapshotToClient(), SVC_Info(), SVC_RemoteCommand(), and SVC_Status().