ioquake3 doxygen: C:/entry/dev/ioq3/code/server/sv_net_chan.c File Reference
sv_net_chan.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "server.h"
Functions
static void SV_Netchan_Encode (client_t *client, msg_t *msg, const char *clientCommandString)
static void SV_Netchan_Decode (client_t *client, msg_t *msg)
void SV_Netchan_FreeQueue (client_t *client)
void SV_Netchan_TransmitNextInQueue (client_t *client)
int SV_Netchan_TransmitNextFragment (client_t *client)
void SV_Netchan_Transmit (client_t *client, msg_t *msg)
qboolean SV_Netchan_Process (client_t *client, msg_t *msg)
Function Documentation
SV_Netchan_Decode()
static void SV_Netchan_Decode (client_t * client, msg_t * msg) static
Definition at line 93 of file sv_net_chan.c.
{
     int serverId, messageAcknowledge, reliableAcknowledge;
     int i, index, srdc, sbit;
     qboolean soob;
     byte key, *string;
     srdc = msg->readcount;
     sbit = msg->bit;
     soob = msg->oob;
     msg->oob = qfalse;
     serverId = MSG_ReadLong(msg);
     messageAcknowledge = MSG_ReadLong(msg);
     reliableAcknowledge = MSG_ReadLong(msg);
     msg->oob = soob;
     msg->bit = sbit;
     msg->readcount = srdc;
     string = (byte *)client->reliableCommands[ reliableAcknowledge & (MAX_RELIABLE_COMMANDS-1) ];
     index = 0;
     //
     key = client->challenge ^ serverId ^ messageAcknowledge;
     for (i = msg->readcount + SV_DECODE_START; i < msg->cursize; i++) {
         // modify the key with the last sent and acknowledged server command
         if (!string[index])
             index = 0;
         if (string[index] > 127 || string[index] == '%') {
             key ^= '.' << (i & 1);
         }
         else {
             key ^= string[index] << (i & 1);
         }
         index++;
         // decode the data with this key
         *(msg->data + i) = *(msg->data + i) ^ key;
     }
 }
Referenced by SV_Netchan_Process().
SV_Netchan_Encode()
static void SV_Netchan_Encode (client_t * client, msg_t * msg, const char * clientCommandString) static
Definition at line 37 of file sv_net_chan.c.
 {
     long i, index;
     byte key, *string;
     int srdc, sbit;
     qboolean soob;
     if ( msg->cursize < SV_ENCODE_START ) {
         return;
     }
     srdc = msg->readcount;
     sbit = msg->bit;
     soob = msg->oob;
     msg->bit = 0;
     msg->readcount = 0;
     msg->oob = qfalse;
     /* reliableAcknowledge = */ MSG_ReadLong(msg);
     msg->oob = soob;
     msg->bit = sbit;
     msg->readcount = srdc;
     string = (byte *) clientCommandString;
     index = 0;
     // xor the client challenge with the netchan sequence number
     key = client->challenge ^ client->netchan.outgoingSequence;
     for (i = SV_ENCODE_START; i < msg->cursize; i++) {
         // modify the key with the last received and with this message acknowledged client command
         if (!string[index])
             index = 0;
         if (string[index] > 127 || string[index] == '%') {
             key ^= '.' << (i & 1);
         }
         else {
             key ^= string[index] << (i & 1);
         }
         index++;
         // encode the data with this key
         *(msg->data + i) = *(msg->data + i) ^ key;
     }
 }
Referenced by SV_Netchan_Transmit(), and SV_Netchan_TransmitNextInQueue().
SV_Netchan_FreeQueue()
void SV_Netchan_FreeQueue (client_t * client)
Definition at line 141 of file sv_net_chan.c.
 {
     netchan_buffer_t *netbuf, *next;
     for(netbuf = client->netchan_start_queue; netbuf; netbuf = next)
     {
         next = netbuf->next;
         Z_Free(netbuf);
     }
     client->netchan_start_queue = NULL;
     client->netchan_end_queue = &client->netchan_start_queue;
 }
Referenced by SV_FreeClient().
SV_Netchan_Process()
qboolean SV_Netchan_Process (client_t * client, msg_t * msg)
Definition at line 262 of file sv_net_chan.c.
{
     int ret;
     ret = Netchan_Process( &client->netchan, msg );
     if (!ret)
         return qfalse;
 #ifdef LEGACY_PROTOCOL
     if(client->compat)
         SV_Netchan_Decode(client, msg);
 #endif
     return qtrue;
 }
Referenced by SV_PacketEvent().
SV_Netchan_Transmit()
void SV_Netchan_Transmit (client_t * client, msg_t * msg)
Definition at line 224 of file sv_net_chan.c.
 {
     MSG_WriteByte( msg, svc_EOF );
     if(client->netchan.unsentFragments || client->netchan_start_queue)
     {
         netchan_buffer_t *netbuf;
         Com_DPrintf("#462 SV_Netchan_Transmit: unsent fragments, stacked\n");
         netbuf = (netchan_buffer_t *) Z_Malloc(sizeof(netchan_buffer_t));
         // store the msg, we can't store it encoded, as the encoding depends on stuff we still have to finish sending
         MSG_Copy(&netbuf->msg, netbuf->msgBuffer, sizeof( netbuf->msgBuffer ), msg);
 #ifdef LEGACY_PROTOCOL
         if(client->compat)
         {
             Q_strncpyz(netbuf->clientCommandString, client->lastClientCommandString,
                    sizeof(netbuf->clientCommandString));
         }
 #endif
         netbuf->next = NULL;
         // insert it in the queue, the message will be encoded and sent later
         *client->netchan_end_queue = netbuf;
         client->netchan_end_queue = &(*client->netchan_end_queue)->next;
     }
     else
     {
 #ifdef LEGACY_PROTOCOL
         if(client->compat)
             SV_Netchan_Encode(client, msg, client->lastClientCommandString);
 #endif
         Netchan_Transmit( &client->netchan, msg->cursize, msg->data );
     }
 }
Referenced by SV_SendDownloadMessages(), and SV_SendMessageToClient().
SV_Netchan_TransmitNextFragment()
int SV_Netchan_TransmitNextFragment (client_t * client)
Definition at line 196 of file sv_net_chan.c.
 {
     if(client->netchan.unsentFragments)
     {
         Netchan_TransmitNextFragment(&client->netchan);
         return SV_RateMsec(client);
     }
     else if(client->netchan_start_queue)
     {
         SV_Netchan_TransmitNextInQueue(client);
         return SV_RateMsec(client);
     }
     return -1;
 }
Referenced by SV_SendQueuedMessages().
SV_Netchan_TransmitNextInQueue()
void SV_Netchan_TransmitNextInQueue (client_t * client)
Definition at line 160 of file sv_net_chan.c.
 {
     netchan_buffer_t *netbuf;
     Com_DPrintf("#462 Netchan_TransmitNextFragment: popping a queued message for transmit\n");
     netbuf = client->netchan_start_queue;
 #ifdef LEGACY_PROTOCOL
     if(client->compat)
         SV_Netchan_Encode(client, &netbuf->msg, netbuf->clientCommandString);
 #endif
     Netchan_Transmit(&client->netchan, netbuf->msg.cursize, netbuf->msg.data);
     // pop from queue
     client->netchan_start_queue = netbuf->next;
     if(!client->netchan_start_queue)
     {
         Com_DPrintf("#462 Netchan_TransmitNextFragment: emptied queue\n");
         client->netchan_end_queue = &client->netchan_start_queue;
     }
     else
         Com_DPrintf("#462 Netchan_TransmitNextFragment: remaining queued message\n");
     Z_Free(netbuf);
 }
Referenced by SV_Netchan_TransmitNextFragment().