ioquake3 doxygen: C:/entry/dev/ioq3/code/client/cl_curl.h File Reference
cl_curl.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include <curl/curl.h>
Macros
#define qcurl_version curl_version
#define qcurl_easy_init curl_easy_init
#define qcurl_easy_setopt curl_easy_setopt
#define qcurl_easy_perform curl_easy_perform
#define qcurl_easy_cleanup curl_easy_cleanup
#define qcurl_easy_getinfo curl_easy_getinfo
#define qcurl_easy_duphandle curl_easy_duphandle
#define qcurl_easy_reset curl_easy_reset
#define qcurl_easy_strerror curl_easy_strerror
#define qcurl_multi_init curl_multi_init
#define qcurl_multi_add_handle curl_multi_add_handle
#define qcurl_multi_remove_handle curl_multi_remove_handle
#define qcurl_multi_fdset curl_multi_fdset
#define qcurl_multi_perform curl_multi_perform
#define qcurl_multi_cleanup curl_multi_cleanup
#define qcurl_multi_info_read curl_multi_info_read
#define qcurl_multi_strerror curl_multi_strerror
Functions
qboolean CL_cURL_Init (void)
void CL_cURL_Shutdown (void)
void CL_cURL_BeginDownload (const char *localName, const char *remoteURL)
void CL_cURL_PerformDownload (void)
void CL_cURL_Cleanup (void)
Macro Definition Documentation
qcurl_easy_cleanup
#define qcurl_easy_cleanup curl_easy_cleanup
Definition at line 81 of file cl_curl.h.
qcurl_easy_duphandle
#define qcurl_easy_duphandle curl_easy_duphandle
Definition at line 83 of file cl_curl.h.
qcurl_easy_getinfo
#define qcurl_easy_getinfo curl_easy_getinfo
Definition at line 82 of file cl_curl.h.
qcurl_easy_init
#define qcurl_easy_init curl_easy_init
Definition at line 78 of file cl_curl.h.
qcurl_easy_perform
#define qcurl_easy_perform curl_easy_perform
Definition at line 80 of file cl_curl.h.
qcurl_easy_reset
#define qcurl_easy_reset curl_easy_reset
Definition at line 84 of file cl_curl.h.
qcurl_easy_setopt
#define qcurl_easy_setopt curl_easy_setopt
Definition at line 79 of file cl_curl.h.
qcurl_easy_strerror
#define qcurl_easy_strerror curl_easy_strerror
Definition at line 85 of file cl_curl.h.
qcurl_multi_add_handle
#define qcurl_multi_add_handle curl_multi_add_handle
Definition at line 88 of file cl_curl.h.
qcurl_multi_cleanup
#define qcurl_multi_cleanup curl_multi_cleanup
Definition at line 92 of file cl_curl.h.
qcurl_multi_fdset
#define qcurl_multi_fdset curl_multi_fdset
Definition at line 90 of file cl_curl.h.
qcurl_multi_info_read
#define qcurl_multi_info_read curl_multi_info_read
Definition at line 93 of file cl_curl.h.
qcurl_multi_init
#define qcurl_multi_init curl_multi_init
Definition at line 87 of file cl_curl.h.
qcurl_multi_perform
#define qcurl_multi_perform curl_multi_perform
Definition at line 91 of file cl_curl.h.
qcurl_multi_remove_handle
#define qcurl_multi_remove_handle curl_multi_remove_handle
Definition at line 89 of file cl_curl.h.
qcurl_multi_strerror
#define qcurl_multi_strerror curl_multi_strerror
Definition at line 94 of file cl_curl.h.
qcurl_version
#define qcurl_version curl_version
Definition at line 76 of file cl_curl.h.
Function Documentation
CL_cURL_BeginDownload()
void CL_cURL_BeginDownload (const char * localName, const char * remoteURL)
Referenced by CL_NextDownload().
CL_cURL_Cleanup()
void CL_cURL_Cleanup (void)
CL_cURL_Init()
qboolean CL_cURL_Init (void)
Referenced by CL_NextDownload().
CL_cURL_PerformDownload()
void CL_cURL_PerformDownload (void)
Referenced by CL_Frame().
CL_cURL_Shutdown()
void CL_cURL_Shutdown (void)
Referenced by CL_DownloadsComplete(), and CL_ShutdownAll().