ioquake3 doxygen: C:/entry/dev/ioq3/code/renderergl2/tr_shadows.c File Reference
tr_shadows.c File Reference
#include "tr_local.h"
Classes
struct edgeDef_t
Macros
#define MAX_EDGE_DEFS 32
Functions
void R_AddEdgeDef (int i1, int i2, int facing)
void R_RenderShadowEdges (void)
void RB_ShadowTessEnd (void)
void RB_ShadowFinish (void)
void RB_ProjectionShadowDeform (void)
Variables
static edgeDef_t edgeDefs [SHADER_MAX_VERTEXES][MAX_EDGE_DEFS]
static int numEdgeDefs [SHADER_MAX_VERTEXES]
Macro Definition Documentation
MAX_EDGE_DEFS
#define MAX_EDGE_DEFS 32
Definition at line 42 of file tr_shadows.c.
Function Documentation
R_AddEdgeDef()
void R_AddEdgeDef (int i1, int i2, int facing)
Definition at line 49 of file tr_shadows.c.
{
     int     c;
     c = numEdgeDefs[ i1 ];
     if ( c == MAX_EDGE_DEFS ) {
         return;     // overflow
     }
     edgeDefs[ i1 ][ c ].i2 = i2;
     edgeDefs[ i1 ][ c ].facing = facing;
     numEdgeDefs[ i1 ]++;
 }
Referenced by RB_ShadowTessEnd().
R_RenderShadowEdges()
void R_RenderShadowEdges (void)
Definition at line 62 of file tr_shadows.c.
{
     // FIXME: implement this
 #if 0
     int     i;
 #if 0
     int     numTris;
     // dumb way -- render every triangle's edges
     numTris = tess.numIndexes / 3;
     for ( i = 0 ; i < numTris ; i++ ) {
         int     i1, i2, i3;
         if ( !facing[i] ) {
             continue;
         }
         i1 = tess.indexes[ i*3 + 0 ];
         i2 = tess.indexes[ i*3 + 1 ];
         i3 = tess.indexes[ i*3 + 2 ];
         qglBegin( GL_TRIANGLE_STRIP );
         qglVertex3fv( tess.xyz[ i1 ] );
         qglVertex3fv( shadowXyz[ i1 ] );
         qglVertex3fv( tess.xyz[ i2 ] );
         qglVertex3fv( shadowXyz[ i2 ] );
         qglVertex3fv( tess.xyz[ i3 ] );
         qglVertex3fv( shadowXyz[ i3 ] );
         qglVertex3fv( tess.xyz[ i1 ] );
         qglVertex3fv( shadowXyz[ i1 ] );
         qglEnd();
     }
 #else
     int     c, c2;
     int     j, k;
     int     i2;
     int     c_edges, c_rejected;
     int     hit[2];
     // an edge is NOT a silhouette edge if its face doesn't face the light,
     // or if it has a reverse paired edge that also faces the light.
     // A well behaved polyhedron would have exactly two faces for each edge,
     // but lots of models have dangling edges or overfanned edges
     c_edges = 0;
     c_rejected = 0;
     for ( i = 0 ; i < tess.numVertexes ; i++ ) {
         c = numEdgeDefs[ i ];
         for ( j = 0 ; j < c ; j++ ) {
             if ( !edgeDefs[ i ][ j ].facing ) {
                 continue;
             }
             hit[0] = 0;
             hit[1] = 0;
             i2 = edgeDefs[ i ][ j ].i2;
             c2 = numEdgeDefs[ i2 ];
             for ( k = 0 ; k < c2 ; k++ ) {
                 if ( edgeDefs[ i2 ][ k ].i2 == i ) {
                     hit[ edgeDefs[ i2 ][ k ].facing ]++;
                 }
             }
             // if it doesn't share the edge with another front facing
             // triangle, it is a sil edge
             if ( hit[ 1 ] == 0 ) {
                 qglBegin( GL_TRIANGLE_STRIP );
                 qglVertex3fv( tess.xyz[ i ] );
                 qglVertex3fv( shadowXyz[ i ] );
                 qglVertex3fv( tess.xyz[ i2 ] );
                 qglVertex3fv( shadowXyz[ i2 ] );
                 qglEnd();
                 c_edges++;
             } else {
                 c_rejected++;
             }
         }
     }
 #endif
 #endif
 }
Referenced by RB_ShadowTessEnd().
RB_ProjectionShadowDeform()
void RB_ProjectionShadowDeform (void)
Definition at line 295 of file tr_shadows.c.
{
     float   *xyz;
     int     i;
     float   h;
     vec3_t  ground;
     vec3_t  light;
     float   groundDist;
     float   d;
     vec3_t  lightDir;
     xyz = ( float * ) tess.xyz;
     ground[0] = backEnd.or.axis[0][2];
     ground[1] = backEnd.or.axis[1][2];
     ground[2] = backEnd.or.axis[2][2];
     groundDist = backEnd.or.origin[2] - backEnd.currentEntity->e.shadowPlane;
     VectorCopy( backEnd.currentEntity->modelLightDir, lightDir );
     d = DotProduct( lightDir, ground );
     // don't let the shadows get too long or go negative
     if ( d < 0.5 ) {
         VectorMA( lightDir, (0.5 - d), ground, lightDir );
         d = DotProduct( lightDir, ground );
     }
     d = 1.0 / d;
     light[0] = lightDir[0] * d;
     light[1] = lightDir[1] * d;
     light[2] = lightDir[2] * d;
     for ( i = 0; i < tess.numVertexes; i++, xyz += 4 ) {
         h = DotProduct( xyz, ground ) + groundDist;
         xyz[0] -= light[0] * h;
         xyz[1] -= light[1] * h;
         xyz[2] -= light[2] * h;
     }
 }
Referenced by RB_DeformTessGeometry().
RB_ShadowFinish()
void RB_ShadowFinish (void)
Definition at line 252 of file tr_shadows.c.
{
     // FIXME: implement this
 #if 0
     if ( r_shadows->integer != 2 ) {
         return;
     }
     if ( glConfig.stencilBits < 4 ) {
         return;
     }
     qglEnable( GL_STENCIL_TEST );
     qglStencilFunc( GL_NOTEQUAL, 0, 255 );
     GL_Cull( CT_TWO_SIDED );
     GL_BindToTMU( tr.whiteImage, TB_COLORMAP );
     qglLoadIdentity ();
     qglColor3f( 0.6f, 0.6f, 0.6f );
     GL_State( GLS_DEPTHMASK_TRUE | GLS_SRCBLEND_DST_COLOR | GLS_DSTBLEND_ZERO );
 //  qglColor3f( 1, 0, 0 );
 //  GL_State( GLS_DEPTHMASK_TRUE | GLS_SRCBLEND_ONE | GLS_DSTBLEND_ZERO );
     qglBegin( GL_QUADS );
     qglVertex3f( -100, 100, -10 );
     qglVertex3f( 100, 100, -10 );
     qglVertex3f( 100, -100, -10 );
     qglVertex3f( -100, -100, -10 );
     qglEnd ();
     qglColor4f(1,1,1,1);
     qglDisable( GL_STENCIL_TEST );
 #endif
 }
Referenced by RB_DrawSurfs().
RB_ShadowTessEnd()
void RB_ShadowTessEnd (void)
Definition at line 158 of file tr_shadows.c.
{
     // FIXME: implement this
 #if 0
     int     i;
     int     numTris;
     vec3_t  lightDir;
     GLboolean rgba[4];
     if ( glConfig.stencilBits < 4 ) {
         return;
     }
     VectorCopy( backEnd.currentEntity->modelLightDir, lightDir );
     // project vertexes away from light direction
     for ( i = 0 ; i < tess.numVertexes ; i++ ) {
         VectorMA( tess.xyz[i], -512, lightDir, shadowXyz[i] );
     }
     // decide which triangles face the light
     Com_Memset( numEdgeDefs, 0, 4 * tess.numVertexes );
     numTris = tess.numIndexes / 3;
     for ( i = 0 ; i < numTris ; i++ ) {
         int     i1, i2, i3;
         vec3_t  d1, d2, normal;
         float   *v1, *v2, *v3;
         float   d;
         i1 = tess.indexes[ i*3 + 0 ];
         i2 = tess.indexes[ i*3 + 1 ];
         i3 = tess.indexes[ i*3 + 2 ];
         v1 = tess.xyz[ i1 ];
         v2 = tess.xyz[ i2 ];
         v3 = tess.xyz[ i3 ];
         VectorSubtract( v2, v1, d1 );
         VectorSubtract( v3, v1, d2 );
         CrossProduct( d1, d2, normal );
         d = DotProduct( normal, lightDir );
         if ( d > 0 ) {
             facing[ i ] = 1;
         } else {
             facing[ i ] = 0;
         }
         // create the edges
         R_AddEdgeDef( i1, i2, facing[ i ] );
         R_AddEdgeDef( i2, i3, facing[ i ] );
         R_AddEdgeDef( i3, i1, facing[ i ] );
     }
     // draw the silhouette edges
     GL_BindToTMU( tr.whiteImage, TB_COLORMAP );
     GL_State( GLS_SRCBLEND_ONE | GLS_DSTBLEND_ZERO );
     qglColor3f( 0.2f, 0.2f, 0.2f );
     // don't write to the color buffer
     qglGetBooleanv(GL_COLOR_WRITEMASK, rgba);
     qglColorMask( GL_FALSE, GL_FALSE, GL_FALSE, GL_FALSE );
     qglEnable( GL_STENCIL_TEST );
     qglStencilFunc( GL_ALWAYS, 1, 255 );
     GL_Cull( CT_BACK_SIDED );
     qglStencilOp( GL_KEEP, GL_KEEP, GL_INCR );
     R_RenderShadowEdges();
     GL_Cull( CT_FRONT_SIDED );
     qglStencilOp( GL_KEEP, GL_KEEP, GL_DECR );
     R_RenderShadowEdges();
     // reenable writing to the color buffer
     qglColorMask(rgba[0], rgba[1], rgba[2], rgba[3]);
 #endif
 }
Referenced by RB_EndSurface().
Variable Documentation
edgeDefs
edgeDef_t edgeDefs[SHADER_MAX_VERTEXES][MAX_EDGE_DEFS] static
Definition at line 44 of file tr_shadows.c.
Referenced by R_AddEdgeDef(), and R_RenderShadowEdges().
numEdgeDefs
int numEdgeDefs[SHADER_MAX_VERTEXES] static
Definition at line 45 of file tr_shadows.c.
Referenced by R_AddEdgeDef(), R_RenderShadowEdges(), and RB_ShadowTessEnd().