ioquake3 doxygen: C:/entry/dev/ioquake3/code/q3_ui/ui_loadconfig.c File Reference
ui_loadconfig.c File Reference
#include "ui_local.h"
Classes
struct configs_t
Macros
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_FIGHT0 "menu/art/load_0"
#define ART_FIGHT1 "menu/art/load_1"
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define ART_ARROWS "menu/art/arrows_horz_0"
#define ART_ARROWLEFT "menu/art/arrows_horz_left"
#define ART_ARROWRIGHT "menu/art/arrows_horz_right"
#define MAX_CONFIGS 128
#define NAMEBUFSIZE (MAX_CONFIGS * 16)
#define ID_BACK 10
#define ID_GO 11
#define ID_LIST 12
#define ID_LEFT 13
#define ID_RIGHT 14
#define ARROWS_WIDTH 128
#define ARROWS_HEIGHT 48
Functions
static void LoadConfig_MenuEvent (void *ptr, int event)
static void LoadConfig_MenuInit (void)
void UI_LoadConfig_Cache (void)
void UI_LoadConfigMenu (void)
Variables
static configs_t s_configs
Macro Definition Documentation
ARROWS_HEIGHT
#define ARROWS_HEIGHT 48
Definition at line 54 of file ui_loadconfig.c.
ARROWS_WIDTH
#define ARROWS_WIDTH 128
Definition at line 53 of file ui_loadconfig.c.
ART_ARROWLEFT
#define ART_ARROWLEFT "menu/art/arrows_horz_left"
Definition at line 41 of file ui_loadconfig.c.
ART_ARROWRIGHT
#define ART_ARROWRIGHT "menu/art/arrows_horz_right"
Definition at line 42 of file ui_loadconfig.c.
ART_ARROWS
#define ART_ARROWS "menu/art/arrows_horz_0"
Definition at line 40 of file ui_loadconfig.c.
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 34 of file ui_loadconfig.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 35 of file ui_loadconfig.c.
ART_FIGHT0
#define ART_FIGHT0 "menu/art/load_0"
Definition at line 36 of file ui_loadconfig.c.
ART_FIGHT1
#define ART_FIGHT1 "menu/art/load_1"
Definition at line 37 of file ui_loadconfig.c.
ART_FRAMEL
#define ART_FRAMEL "menu/art/frame2_l"
Definition at line 38 of file ui_loadconfig.c.
ART_FRAMER
#define ART_FRAMER "menu/art/frame1_r"
Definition at line 39 of file ui_loadconfig.c.
ID_BACK
#define ID_BACK 10
Definition at line 47 of file ui_loadconfig.c.
ID_GO
#define ID_GO 11
Definition at line 48 of file ui_loadconfig.c.
ID_LEFT
#define ID_LEFT 13
Definition at line 50 of file ui_loadconfig.c.
ID_LIST
#define ID_LIST 12
Definition at line 49 of file ui_loadconfig.c.
ID_RIGHT
#define ID_RIGHT 14
Definition at line 51 of file ui_loadconfig.c.
MAX_CONFIGS
#define MAX_CONFIGS 128
Definition at line 44 of file ui_loadconfig.c.
NAMEBUFSIZE
#define NAMEBUFSIZE (MAX_CONFIGS * 16)
Definition at line 45 of file ui_loadconfig.c.
Function Documentation
LoadConfig_MenuEvent()
static void LoadConfig_MenuEvent (void * ptr, int event) static
Definition at line 84 of file ui_loadconfig.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch ( ((menucommon_s*)ptr)->id ) {
     case ID_GO:
         trap_Cmd_ExecuteText( EXEC_APPEND, va( "exec %s\n", s_configs.list.itemnames[s_configs.list.curvalue] ) );
         UI_PopMenu();
         break;
     case ID_BACK:
         UI_PopMenu();
         break;
     case ID_LEFT:
         ScrollList_Key( &s_configs.list, K_LEFTARROW );
         break;
     case ID_RIGHT:
         ScrollList_Key( &s_configs.list, K_RIGHTARROW );
         break;
     }
 }
Referenced by LoadConfig_MenuInit().
LoadConfig_MenuInit()
static void LoadConfig_MenuInit (void) static
Definition at line 115 of file ui_loadconfig.c.
{
     int     i;
     int     len;
     char    *configname;
     UI_LoadConfig_Cache();
     memset( &s_configs, 0 ,sizeof(configs_t) );
     s_configs.menu.wrapAround = qtrue;
     s_configs.menu.fullscreen = qtrue;
     s_configs.banner.generic.type   = MTYPE_BTEXT;
     s_configs.banner.generic.x      = 320;
     s_configs.banner.generic.y      = 16;
     s_configs.banner.string         = "LOAD CONFIG";
     s_configs.banner.color          = color_white;
     s_configs.banner.style          = UI_CENTER;
     s_configs.framel.generic.type   = MTYPE_BITMAP;
     s_configs.framel.generic.name   = ART_FRAMEL;
     s_configs.framel.generic.flags  = QMF_INACTIVE;
     s_configs.framel.generic.x      = 0;
     s_configs.framel.generic.y      = 78;
     s_configs.framel.width          = 256;
     s_configs.framel.height         = 329;
     s_configs.framer.generic.type   = MTYPE_BITMAP;
     s_configs.framer.generic.name   = ART_FRAMER;
     s_configs.framer.generic.flags  = QMF_INACTIVE;
     s_configs.framer.generic.x      = 376;
     s_configs.framer.generic.y      = 76;
     s_configs.framer.width          = 256;
     s_configs.framer.height         = 334;
     s_configs.arrows.generic.type   = MTYPE_BITMAP;
     s_configs.arrows.generic.name   = ART_ARROWS;
     s_configs.arrows.generic.flags  = QMF_INACTIVE;
     s_configs.arrows.generic.x      = 320-ARROWS_WIDTH/2;
     s_configs.arrows.generic.y      = 400;
     s_configs.arrows.width          = ARROWS_WIDTH;
     s_configs.arrows.height         = ARROWS_HEIGHT;
     s_configs.left.generic.type     = MTYPE_BITMAP;
     s_configs.left.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_configs.left.generic.x        = 320-ARROWS_WIDTH/2;
     s_configs.left.generic.y        = 400;
     s_configs.left.generic.id       = ID_LEFT;
     s_configs.left.generic.callback = LoadConfig_MenuEvent;
     s_configs.left.width            = ARROWS_WIDTH/2;
     s_configs.left.height           = ARROWS_HEIGHT;
     s_configs.left.focuspic         = ART_ARROWLEFT;
     s_configs.right.generic.type    = MTYPE_BITMAP;
     s_configs.right.generic.flags   = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_MOUSEONLY;
     s_configs.right.generic.x       = 320;
     s_configs.right.generic.y       = 400;
     s_configs.right.generic.id      = ID_RIGHT;
     s_configs.right.generic.callback = LoadConfig_MenuEvent;
     s_configs.right.width           = ARROWS_WIDTH/2;
     s_configs.right.height          = ARROWS_HEIGHT;
     s_configs.right.focuspic        = ART_ARROWRIGHT;
     s_configs.back.generic.type     = MTYPE_BITMAP;
     s_configs.back.generic.name     = ART_BACK0;
     s_configs.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_configs.back.generic.id       = ID_BACK;
     s_configs.back.generic.callback = LoadConfig_MenuEvent;
     s_configs.back.generic.x        = 0;
     s_configs.back.generic.y        = 480-64;
     s_configs.back.width            = 128;
     s_configs.back.height           = 64;
     s_configs.back.focuspic         = ART_BACK1;
     s_configs.go.generic.type       = MTYPE_BITMAP;
     s_configs.go.generic.name       = ART_FIGHT0;
     s_configs.go.generic.flags      = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_configs.go.generic.id         = ID_GO;
     s_configs.go.generic.callback   = LoadConfig_MenuEvent;
     s_configs.go.generic.x          = 640;
     s_configs.go.generic.y          = 480-64;
     s_configs.go.width              = 128;
     s_configs.go.height             = 64;
     s_configs.go.focuspic           = ART_FIGHT1;
     // scan for configs
     s_configs.list.generic.type     = MTYPE_SCROLLLIST;
     s_configs.list.generic.flags    = QMF_PULSEIFFOCUS;
     s_configs.list.generic.callback = LoadConfig_MenuEvent;
     s_configs.list.generic.id       = ID_LIST;
     s_configs.list.generic.x        = 118;
     s_configs.list.generic.y        = 130;
     s_configs.list.width            = 16;
     s_configs.list.height           = 14;
     s_configs.list.numitems         = trap_FS_GetFileList( "", "cfg", s_configs.names, NAMEBUFSIZE );
     s_configs.list.itemnames        = (const char **)s_configs.configlist;
     s_configs.list.columns          = 3;
     if (!s_configs.list.numitems) {
         strcpy(s_configs.names,"No Files Found.");
         s_configs.list.numitems = 1;
         //degenerate case, not selectable
         s_configs.go.generic.flags |= (QMF_INACTIVE|QMF_HIDDEN);
     }
     else if (s_configs.list.numitems > MAX_CONFIGS)
         s_configs.list.numitems = MAX_CONFIGS;
     configname = s_configs.names;
     for ( i = 0; i < s_configs.list.numitems; i++ ) {
         s_configs.list.itemnames[i] = configname;
         // strip extension
         len = strlen( configname );
         if (!Q_stricmp(configname +  len - 4,".cfg"))
             configname[len-4] = '\0';
         Q_strupr(configname);
         configname += len + 1;
     }
     Menu_AddItem( &s_configs.menu, &s_configs.banner );
     Menu_AddItem( &s_configs.menu, &s_configs.framel );
     Menu_AddItem( &s_configs.menu, &s_configs.framer );
     Menu_AddItem( &s_configs.menu, &s_configs.list );
     Menu_AddItem( &s_configs.menu, &s_configs.arrows );
     Menu_AddItem( &s_configs.menu, &s_configs.left );
     Menu_AddItem( &s_configs.menu, &s_configs.right );
     Menu_AddItem( &s_configs.menu, &s_configs.back );
     Menu_AddItem( &s_configs.menu, &s_configs.go );
 }
Referenced by UI_LoadConfigMenu().
UI_LoadConfig_Cache()
void UI_LoadConfig_Cache (void)
Definition at line 252 of file ui_loadconfig.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FIGHT0 );
     trap_R_RegisterShaderNoMip( ART_FIGHT1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_ARROWS );
     trap_R_RegisterShaderNoMip( ART_ARROWLEFT );
     trap_R_RegisterShaderNoMip( ART_ARROWRIGHT );
 }
Referenced by LoadConfig_MenuInit().
UI_LoadConfigMenu()
void UI_LoadConfigMenu (void)
Definition at line 270 of file ui_loadconfig.c.
{
     LoadConfig_MenuInit();
     UI_PushMenu( &s_configs.menu );
 }
Variable Documentation
s_configs
configs_t s_configs static
Definition at line 76 of file ui_loadconfig.c.
Referenced by LoadConfig_MenuEvent(), LoadConfig_MenuInit(), and UI_LoadConfigMenu().