ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_removebots.c File Reference
ui_removebots.c File Reference
#include "ui_local.h"
Classes
struct removeBotsMenuInfo_t
Macros
#define ART_BACKGROUND "menu/art/addbotframe"
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_DELETE0 "menu/art/delete_0"
#define ART_DELETE1 "menu/art/delete_1"
#define ART_ARROWS "menu/art/arrows_vert_0"
#define ART_ARROWUP "menu/art/arrows_vert_top"
#define ART_ARROWDOWN "menu/art/arrows_vert_bot"
#define ID_UP 10
#define ID_DOWN 11
#define ID_DELETE 12
#define ID_BACK 13
#define ID_BOTNAME0 20
#define ID_BOTNAME1 21
#define ID_BOTNAME2 22
#define ID_BOTNAME3 23
#define ID_BOTNAME4 24
#define ID_BOTNAME5 25
#define ID_BOTNAME6 26
Functions
static void UI_RemoveBotsMenu_SetBotNames (void)
static void UI_RemoveBotsMenu_DeleteEvent (void *ptr, int event)
static void UI_RemoveBotsMenu_BotEvent (void *ptr, int event)
static void UI_RemoveBotsMenu_BackEvent (void *ptr, int event)
static void UI_RemoveBotsMenu_UpEvent (void *ptr, int event)
static void UI_RemoveBotsMenu_DownEvent (void *ptr, int event)
static void UI_RemoveBotsMenu_GetBots (void)
void UI_RemoveBots_Cache (void)
static void UI_RemoveBotsMenu_Init (void)
void UI_RemoveBotsMenu (void)
Variables
static removeBotsMenuInfo_t removeBotsMenuInfo
Macro Definition Documentation
ART_ARROWDOWN
#define ART_ARROWDOWN "menu/art/arrows_vert_bot"
Definition at line 42 of file ui_removebots.c.
ART_ARROWS
#define ART_ARROWS "menu/art/arrows_vert_0"
Definition at line 40 of file ui_removebots.c.
ART_ARROWUP
#define ART_ARROWUP "menu/art/arrows_vert_top"
Definition at line 41 of file ui_removebots.c.
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 36 of file ui_removebots.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 37 of file ui_removebots.c.
ART_BACKGROUND
#define ART_BACKGROUND "menu/art/addbotframe"
Definition at line 35 of file ui_removebots.c.
ART_DELETE0
#define ART_DELETE0 "menu/art/delete_0"
Definition at line 38 of file ui_removebots.c.
ART_DELETE1
#define ART_DELETE1 "menu/art/delete_1"
Definition at line 39 of file ui_removebots.c.
ID_BACK
#define ID_BACK 13
Definition at line 47 of file ui_removebots.c.
ID_BOTNAME0
#define ID_BOTNAME0 20
Definition at line 48 of file ui_removebots.c.
ID_BOTNAME1
#define ID_BOTNAME1 21
Definition at line 49 of file ui_removebots.c.
ID_BOTNAME2
#define ID_BOTNAME2 22
Definition at line 50 of file ui_removebots.c.
ID_BOTNAME3
#define ID_BOTNAME3 23
Definition at line 51 of file ui_removebots.c.
ID_BOTNAME4
#define ID_BOTNAME4 24
Definition at line 52 of file ui_removebots.c.
ID_BOTNAME5
#define ID_BOTNAME5 25
Definition at line 53 of file ui_removebots.c.
ID_BOTNAME6
#define ID_BOTNAME6 26
Definition at line 54 of file ui_removebots.c.
ID_DELETE
#define ID_DELETE 12
Definition at line 46 of file ui_removebots.c.
ID_DOWN
#define ID_DOWN 11
Definition at line 45 of file ui_removebots.c.
ID_UP
#define ID_UP 10
Definition at line 44 of file ui_removebots.c.
Function Documentation
UI_RemoveBots_Cache()
void UI_RemoveBots_Cache (void)
Definition at line 211 of file ui_removebots.c.
{
     trap_R_RegisterShaderNoMip( ART_BACKGROUND );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_DELETE0 );
     trap_R_RegisterShaderNoMip( ART_DELETE1 );
 }
References ART_BACK0, ART_BACK1, ART_BACKGROUND, ART_DELETE0, ART_DELETE1, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_RemoveBotsMenu_Init().
UI_RemoveBotsMenu()
void UI_RemoveBotsMenu (void)
Definition at line 339 of file ui_removebots.c.
{
     UI_RemoveBotsMenu_Init();
     UI_PushMenu( &removeBotsMenuInfo.menu );
 }
References removeBotsMenuInfo_t::menu, removeBotsMenuInfo, UI_PushMenu(), and UI_RemoveBotsMenu_Init().
Referenced by InGame_Event().
UI_RemoveBotsMenu_BackEvent()
static void UI_RemoveBotsMenu_BackEvent (void * ptr, int event) static
Definition at line 135 of file ui_removebots.c.
{
     if (event != QM_ACTIVATED) {
         return;
     }
     UI_PopMenu();
 }
References QM_ACTIVATED, and UI_PopMenu().
Referenced by UI_RemoveBotsMenu_Init().
UI_RemoveBotsMenu_BotEvent()
static void UI_RemoveBotsMenu_BotEvent (void * ptr, int event) static
Definition at line 119 of file ui_removebots.c.
{
     if (event != QM_ACTIVATED) {
         return;
     }
     removeBotsMenuInfo.bots[removeBotsMenuInfo.selectedBotNum].color = color_orange;
     removeBotsMenuInfo.selectedBotNum = ((menucommon_s*)ptr)->id - ID_BOTNAME0;
     removeBotsMenuInfo.bots[removeBotsMenuInfo.selectedBotNum].color = color_white;
 }
References removeBotsMenuInfo_t::bots, menutext_s::color, color_orange, color_white, ID_BOTNAME0, QM_ACTIVATED, removeBotsMenuInfo, and removeBotsMenuInfo_t::selectedBotNum.
Referenced by UI_RemoveBotsMenu_Init().
UI_RemoveBotsMenu_DeleteEvent()
static void UI_RemoveBotsMenu_DeleteEvent (void * ptr, int event) static
Definition at line 105 of file ui_removebots.c.
{
     if (event != QM_ACTIVATED) {
         return;
     }
     trap_Cmd_ExecuteText( EXEC_APPEND, va("clientkick %i\n", removeBotsMenuInfo.botClientNums[removeBotsMenuInfo.baseBotNum + removeBotsMenuInfo.selectedBotNum]) );
 }
References removeBotsMenuInfo_t::baseBotNum, removeBotsMenuInfo_t::botClientNums, EXEC_APPEND, QM_ACTIVATED, removeBotsMenuInfo, removeBotsMenuInfo_t::selectedBotNum, trap_Cmd_ExecuteText(), and va().
Referenced by UI_RemoveBotsMenu_Init().
UI_RemoveBotsMenu_DownEvent()
static void UI_RemoveBotsMenu_DownEvent (void * ptr, int event) static
Definition at line 165 of file ui_removebots.c.
{
     if (event != QM_ACTIVATED) {
         return;
     }
     if( removeBotsMenuInfo.baseBotNum + 7 < removeBotsMenuInfo.numBots ) {
         removeBotsMenuInfo.baseBotNum++;
         UI_RemoveBotsMenu_SetBotNames();
     }
 }
References removeBotsMenuInfo_t::baseBotNum, removeBotsMenuInfo_t::numBots, QM_ACTIVATED, removeBotsMenuInfo, and UI_RemoveBotsMenu_SetBotNames().
Referenced by UI_RemoveBotsMenu_Init().
UI_RemoveBotsMenu_GetBots()
static void UI_RemoveBotsMenu_GetBots (void) static
Definition at line 182 of file ui_removebots.c.
{
     int     numPlayers;
     int     isBot;
     int     n;
     char    info[MAX_INFO_STRING];
     trap_GetConfigString( CS_SERVERINFO, info, sizeof(info) );
     numPlayers = atoi( Info_ValueForKey( info, "sv_maxclients" ) );
     removeBotsMenuInfo.numBots = 0;
     for( n = 0; n < numPlayers; n++ ) {
         trap_GetConfigString( CS_PLAYERS + n, info, MAX_INFO_STRING );
         isBot = atoi( Info_ValueForKey( info, "skill" ) );
         if( !isBot ) {
             continue;
         }
         removeBotsMenuInfo.botClientNums[removeBotsMenuInfo.numBots] = n;
         removeBotsMenuInfo.numBots++;
     }
 }
References removeBotsMenuInfo_t::botClientNums, CS_PLAYERS, CS_SERVERINFO, Info_ValueForKey(), MAX_INFO_STRING, removeBotsMenuInfo_t::numBots, removeBotsMenuInfo, and trap_GetConfigString().
Referenced by UI_RemoveBotsMenu_Init().
UI_RemoveBotsMenu_Init()
static void UI_RemoveBotsMenu_Init (void) static
Definition at line 225 of file ui_removebots.c.
{
     int     n;
     int     count;
     int     y;
     memset( &removeBotsMenuInfo, 0 ,sizeof(removeBotsMenuInfo) );
     removeBotsMenuInfo.menu.fullscreen = qfalse;
     removeBotsMenuInfo.menu.wrapAround = qtrue;
     UI_RemoveBots_Cache();
     UI_RemoveBotsMenu_GetBots();
     UI_RemoveBotsMenu_SetBotNames();
     count = removeBotsMenuInfo.numBots < 7 ? removeBotsMenuInfo.numBots : 7;
     removeBotsMenuInfo.banner.generic.type      = MTYPE_BTEXT;
     removeBotsMenuInfo.banner.generic.x         = 320;
     removeBotsMenuInfo.banner.generic.y         = 16;
     removeBotsMenuInfo.banner.string            = "REMOVE BOTS";
     removeBotsMenuInfo.banner.color             = color_white;
     removeBotsMenuInfo.banner.style             = UI_CENTER;
     removeBotsMenuInfo.background.generic.type  = MTYPE_BITMAP;
     removeBotsMenuInfo.background.generic.name  = ART_BACKGROUND;
     removeBotsMenuInfo.background.generic.flags = QMF_INACTIVE;
     removeBotsMenuInfo.background.generic.x     = 320-233;
     removeBotsMenuInfo.background.generic.y     = 240-166;
     removeBotsMenuInfo.background.width         = 466;
     removeBotsMenuInfo.background.height        = 332;
     removeBotsMenuInfo.arrows.generic.type      = MTYPE_BITMAP;
     removeBotsMenuInfo.arrows.generic.name      = ART_ARROWS;
     removeBotsMenuInfo.arrows.generic.flags     = QMF_INACTIVE;
     removeBotsMenuInfo.arrows.generic.x         = 200;
     removeBotsMenuInfo.arrows.generic.y         = 128;
     removeBotsMenuInfo.arrows.width             = 64;
     removeBotsMenuInfo.arrows.height            = 128;
     removeBotsMenuInfo.up.generic.type          = MTYPE_BITMAP;
     removeBotsMenuInfo.up.generic.flags         = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     removeBotsMenuInfo.up.generic.x             = 200;
     removeBotsMenuInfo.up.generic.y             = 128;
     removeBotsMenuInfo.up.generic.id            = ID_UP;
     removeBotsMenuInfo.up.generic.callback      = UI_RemoveBotsMenu_UpEvent;
     removeBotsMenuInfo.up.width                 = 64;
     removeBotsMenuInfo.up.height                = 64;
     removeBotsMenuInfo.up.focuspic              = ART_ARROWUP;
     removeBotsMenuInfo.down.generic.type        = MTYPE_BITMAP;
     removeBotsMenuInfo.down.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     removeBotsMenuInfo.down.generic.x           = 200;
     removeBotsMenuInfo.down.generic.y           = 128+64;
     removeBotsMenuInfo.down.generic.id          = ID_DOWN;
     removeBotsMenuInfo.down.generic.callback    = UI_RemoveBotsMenu_DownEvent;
     removeBotsMenuInfo.down.width               = 64;
     removeBotsMenuInfo.down.height              = 64;
     removeBotsMenuInfo.down.focuspic            = ART_ARROWDOWN;
     for( n = 0, y = 120; n < count; n++, y += 20 ) {
         removeBotsMenuInfo.bots[n].generic.type     = MTYPE_PTEXT;
         removeBotsMenuInfo.bots[n].generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
         removeBotsMenuInfo.bots[n].generic.id       = ID_BOTNAME0 + n;
         removeBotsMenuInfo.bots[n].generic.x        = 320 - 56;
         removeBotsMenuInfo.bots[n].generic.y        = y;
         removeBotsMenuInfo.bots[n].generic.callback = UI_RemoveBotsMenu_BotEvent;
         removeBotsMenuInfo.bots[n].string           = removeBotsMenuInfo.botnames[n];
         removeBotsMenuInfo.bots[n].color            = color_orange;
         removeBotsMenuInfo.bots[n].style            = UI_LEFT|UI_SMALLFONT;
     }
     removeBotsMenuInfo.delete.generic.type      = MTYPE_BITMAP;
     removeBotsMenuInfo.delete.generic.name      = ART_DELETE0;
     removeBotsMenuInfo.delete.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     removeBotsMenuInfo.delete.generic.id        = ID_DELETE;
     removeBotsMenuInfo.delete.generic.callback  = UI_RemoveBotsMenu_DeleteEvent;
     removeBotsMenuInfo.delete.generic.x         = 320+128-128;
     removeBotsMenuInfo.delete.generic.y         = 256+128-64;
     removeBotsMenuInfo.delete.width             = 128;
     removeBotsMenuInfo.delete.height            = 64;
     removeBotsMenuInfo.delete.focuspic          = ART_DELETE1;
     removeBotsMenuInfo.back.generic.type        = MTYPE_BITMAP;
     removeBotsMenuInfo.back.generic.name        = ART_BACK0;
     removeBotsMenuInfo.back.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     removeBotsMenuInfo.back.generic.id          = ID_BACK;
     removeBotsMenuInfo.back.generic.callback    = UI_RemoveBotsMenu_BackEvent;
     removeBotsMenuInfo.back.generic.x           = 320-128;
     removeBotsMenuInfo.back.generic.y           = 256+128-64;
     removeBotsMenuInfo.back.width               = 128;
     removeBotsMenuInfo.back.height              = 64;
     removeBotsMenuInfo.back.focuspic            = ART_BACK1;
     Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.background );
     Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.banner );
     Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.arrows );
     Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.up );
     Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.down );
     for( n = 0; n < count; n++ ) {
         Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.bots[n] );
     }
     Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.delete );
     Menu_AddItem( &removeBotsMenuInfo.menu, &removeBotsMenuInfo.back );
     removeBotsMenuInfo.baseBotNum = 0;
     removeBotsMenuInfo.selectedBotNum = 0;
     removeBotsMenuInfo.bots[0].color = color_white;
 }
References removeBotsMenuInfo_t::arrows, ART_ARROWDOWN, ART_ARROWS, ART_ARROWUP, ART_BACK0, ART_BACK1, ART_BACKGROUND, ART_DELETE0, ART_DELETE1, removeBotsMenuInfo_t::back, removeBotsMenuInfo_t::background, removeBotsMenuInfo_t::banner, removeBotsMenuInfo_t::baseBotNum, removeBotsMenuInfo_t::botnames, removeBotsMenuInfo_t::bots, menucommon_s::callback, menutext_s::color, color_orange, color_white, count, removeBotsMenuInfo_t::delete, removeBotsMenuInfo_t::down, menucommon_s::flags, menubitmap_s::focuspic, _tag_menuframework::fullscreen, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_BOTNAME0, ID_DELETE, ID_DOWN, ID_UP, removeBotsMenuInfo_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, removeBotsMenuInfo_t::numBots, qfalse, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, removeBotsMenuInfo, removeBotsMenuInfo_t::selectedBotNum, menutext_s::string, menutext_s::style, menucommon_s::type, UI_CENTER, UI_LEFT, UI_RemoveBots_Cache(), UI_RemoveBotsMenu_BackEvent(), UI_RemoveBotsMenu_BotEvent(), UI_RemoveBotsMenu_DeleteEvent(), UI_RemoveBotsMenu_DownEvent(), UI_RemoveBotsMenu_GetBots(), UI_RemoveBotsMenu_SetBotNames(), UI_RemoveBotsMenu_UpEvent(), UI_SMALLFONT, removeBotsMenuInfo_t::up, menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_RemoveBotsMenu().
UI_RemoveBotsMenu_SetBotNames()
static void UI_RemoveBotsMenu_SetBotNames (void) static
Definition at line 87 of file ui_removebots.c.
{
     int     n;
     char    info[MAX_INFO_STRING];
     for ( n = 0; (n < 7) && (removeBotsMenuInfo.baseBotNum + n < removeBotsMenuInfo.numBots); n++ ) {
         trap_GetConfigString( CS_PLAYERS + removeBotsMenuInfo.botClientNums[removeBotsMenuInfo.baseBotNum + n], info, MAX_INFO_STRING );
         Q_strncpyz( removeBotsMenuInfo.botnames[n], Info_ValueForKey( info, "n" ), sizeof(removeBotsMenuInfo.botnames[n]) );
         Q_CleanStr( removeBotsMenuInfo.botnames[n] );
     }
 }
References removeBotsMenuInfo_t::baseBotNum, removeBotsMenuInfo_t::botClientNums, removeBotsMenuInfo_t::botnames, CS_PLAYERS, Info_ValueForKey(), MAX_INFO_STRING, removeBotsMenuInfo_t::numBots, Q_CleanStr(), Q_strncpyz(), removeBotsMenuInfo, and trap_GetConfigString().
Referenced by UI_RemoveBotsMenu_DownEvent(), UI_RemoveBotsMenu_Init(), and UI_RemoveBotsMenu_UpEvent().
UI_RemoveBotsMenu_UpEvent()
static void UI_RemoveBotsMenu_UpEvent (void * ptr, int event) static
Definition at line 148 of file ui_removebots.c.
{
     if (event != QM_ACTIVATED) {
         return;
     }
     if( removeBotsMenuInfo.baseBotNum > 0 ) {
         removeBotsMenuInfo.baseBotNum--;
         UI_RemoveBotsMenu_SetBotNames();
     }
 }
References removeBotsMenuInfo_t::baseBotNum, QM_ACTIVATED, removeBotsMenuInfo, and UI_RemoveBotsMenu_SetBotNames().
Referenced by UI_RemoveBotsMenu_Init().
Variable Documentation
removeBotsMenuInfo
removeBotsMenuInfo_t removeBotsMenuInfo static
Definition at line 79 of file ui_removebots.c.
Referenced by UI_RemoveBotsMenu(), UI_RemoveBotsMenu_BotEvent(), UI_RemoveBotsMenu_DeleteEvent(), UI_RemoveBotsMenu_DownEvent(), UI_RemoveBotsMenu_GetBots(), UI_RemoveBotsMenu_Init(), UI_RemoveBotsMenu_SetBotNames(), and UI_RemoveBotsMenu_UpEvent().