ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ea.h File Reference
be_ea.h File Reference
Functions
void EA_Say (int client, char *str)
void EA_SayTeam (int client, char *str)
void EA_Command (int client, char *command)
void EA_Action (int client, int action)
void EA_Crouch (int client)
void EA_Walk (int client)
void EA_MoveUp (int client)
void EA_MoveDown (int client)
void EA_MoveForward (int client)
void EA_MoveBack (int client)
void EA_MoveLeft (int client)
void EA_MoveRight (int client)
void EA_Attack (int client)
void EA_Respawn (int client)
void EA_Talk (int client)
void EA_Gesture (int client)
void EA_Use (int client)
void EA_SelectWeapon (int client, int weapon)
void EA_Jump (int client)
void EA_DelayedJump (int client)
void EA_Move (int client, vec3_t dir, float speed)
void EA_View (int client, vec3_t viewangles)
void EA_EndRegular (int client, float thinktime)
void EA_GetInput (int client, float thinktime, bot_input_t *input)
void EA_ResetInput (int client)
int EA_Setup (void)
void EA_Shutdown (void)
Function Documentation
EA_Action()
void EA_Action (int client, int action)
Definition at line 285 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= action;
 } //end of function EA_Action
References bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_Attack()
void EA_Attack (int client)
Definition at line 159 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_ATTACK;
 } //end of the function EA_Attack
References ACTION_ATTACK, bot_input_s::actionflags, and botinputs.
Referenced by BotTravel_BFGJump(), BotTravel_Grapple(), BotTravel_RocketJump(), and Init_EA_Export().
EA_Command()
void EA_Command (int client, char * command)
Definition at line 135 of file be_ea.c.
 {
     botimport.BotClientCommand(client, command);
 } //end of the function EA_Command
References botlib_import_s::BotClientCommand, and botimport.
Referenced by BotEnterChat(), BotResetGrapple(), BotTravel_Grapple(), and Init_EA_Export().
EA_Crouch()
void EA_Crouch (int client)
Definition at line 257 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_CROUCH;
 } //end of the function EA_Crouch
References ACTION_CROUCH, bot_input_s::actionflags, and botinputs.
Referenced by BotTravel_Crouch(), BotTravel_Walk(), BotWalkInDirection(), and Init_EA_Export().
EA_DelayedJump()
void EA_DelayedJump (int client)
Definition at line 236 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     if (bi->actionflags & ACTION_JUMPEDLASTFRAME)
     {
         bi->actionflags &= ~ACTION_DELAYEDJUMP;
     } //end if
     else
     {
         bi->actionflags |= ACTION_DELAYEDJUMP;
     } //end if
 } //end of the function EA_DelayedJump
References ACTION_DELAYEDJUMP, ACTION_JUMPEDLASTFRAME, bot_input_s::actionflags, and botinputs.
Referenced by BotTravel_Jump(), and Init_EA_Export().
EA_EndRegular()
void EA_EndRegular (int client, float thinktime)
Definition at line 415 of file be_ea.c.
 {
 } //end of the function EA_EndRegular
Referenced by Init_EA_Export().
EA_Gesture()
void EA_Gesture (int client)
Definition at line 121 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_GESTURE;
 } //end of the function EA_Gesture
References ACTION_GESTURE, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_GetInput()
void EA_GetInput (int client, float thinktime, bot_input_t * input)
Definition at line 424 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->thinktime = thinktime;
     Com_Memcpy(input, bi, sizeof(bot_input_t));
 } //end of the function EA_GetInput
References botinputs, Com_Memcpy, and bot_input_s::thinktime.
Referenced by Init_EA_Export().
EA_Jump()
void EA_Jump (int client)
Definition at line 215 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     if (bi->actionflags & ACTION_JUMPEDLASTFRAME)
     {
         bi->actionflags &= ~ACTION_JUMP;
     } //end if
     else
     {
         bi->actionflags |= ACTION_JUMP;
     } //end if
 } //end of the function EA_Jump
References ACTION_JUMP, ACTION_JUMPEDLASTFRAME, bot_input_s::actionflags, and botinputs.
Referenced by BotCheckBarrierJump(), BotTravel_BarrierJump(), BotTravel_BFGJump(), BotTravel_Jump(), BotTravel_RocketJump(), BotWalkInDirection(), and Init_EA_Export().
EA_Move()
void EA_Move (int client, vec3_t dir, float speed)
Definition at line 383 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     VectorCopy(dir, bi->dir);
     //cap speed
     if (speed > MAX_USERMOVE) speed = MAX_USERMOVE;
     else if (speed < -MAX_USERMOVE) speed = -MAX_USERMOVE;
     bi->speed = speed;
 } //end of the function EA_Move
References botinputs, bot_input_s::dir, MAX_USERMOVE, bot_input_s::speed, and VectorCopy.
Referenced by BotCheckBarrierJump(), BotFinishTravel_BarrierJump(), BotFinishTravel_Elevator(), BotFinishTravel_FuncBobbing(), BotFinishTravel_Jump(), BotFinishTravel_JumpPad(), BotFinishTravel_Walk(), BotFinishTravel_WalkOffLedge(), BotFinishTravel_WaterJump(), BotFinishTravel_WeaponJump(), BotMoveInGoalArea(), BotSwimInDirection(), BotTravel_BarrierJump(), BotTravel_BFGJump(), BotTravel_Crouch(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotTravel_Jump(), BotTravel_JumpPad(), BotTravel_Ladder(), BotTravel_RocketJump(), BotTravel_Swim(), BotTravel_Teleport(), BotTravel_Walk(), BotTravel_WalkOffLedge(), BotWalkInDirection(), and Init_EA_Export().
EA_MoveBack()
void EA_MoveBack (int client)
Definition at line 341 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_MOVEBACK;
 } //end of the function EA_MoveBack
References ACTION_MOVEBACK, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_MoveDown()
void EA_MoveDown (int client)
Definition at line 313 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_MOVEDOWN;
 } //end of the function EA_MoveDown
References ACTION_MOVEDOWN, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_MoveForward()
void EA_MoveForward (int client)
Definition at line 327 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_MOVEFORWARD;
 } //end of the function EA_MoveForward
References ACTION_MOVEFORWARD, bot_input_s::actionflags, and botinputs.
Referenced by BotTravel_Ladder(), BotTravel_WaterJump(), and Init_EA_Export().
EA_MoveLeft()
void EA_MoveLeft (int client)
Definition at line 355 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_MOVELEFT;
 } //end of the function EA_MoveLeft
References ACTION_MOVELEFT, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_MoveRight()
void EA_MoveRight (int client)
Definition at line 369 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_MOVERIGHT;
 } //end of the function EA_MoveRight
References ACTION_MOVERIGHT, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_MoveUp()
void EA_MoveUp (int client)
Definition at line 299 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_MOVEUP;
 } //end of the function EA_MoveUp
References ACTION_MOVEUP, bot_input_s::actionflags, and botinputs.
Referenced by BotTravel_WaterJump(), and Init_EA_Export().
EA_ResetInput()
void EA_ResetInput (int client)
Definition at line 438 of file be_ea.c.
 {
     bot_input_t *bi;
     int jumped = qfalse;
     bi = &botinputs[client];
     bi->thinktime = 0;
     VectorClear(bi->dir);
     bi->speed = 0;
     jumped = bi->actionflags & ACTION_JUMP;
     bi->actionflags = 0;
     if (jumped) bi->actionflags |= ACTION_JUMPEDLASTFRAME;
 } //end of the function EA_ResetInput
References ACTION_JUMP, ACTION_JUMPEDLASTFRAME, bot_input_s::actionflags, botinputs, bot_input_s::dir, qfalse, bot_input_s::speed, bot_input_s::thinktime, and VectorClear.
Referenced by Init_EA_Export().
EA_Respawn()
void EA_Respawn (int client)
Definition at line 201 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_RESPAWN;
 } //end of the function EA_Respawn
References ACTION_RESPAWN, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_Say()
void EA_Say (int client, char * str)
Definition at line 51 of file be_ea.c.
 {
     botimport.BotClientCommand(client, va("say %s", str) );
 } //end of the function EA_Say
References botlib_import_s::BotClientCommand, botimport, and va().
Referenced by Init_EA_Export().
EA_SayTeam()
void EA_SayTeam (int client, char * str)
Definition at line 61 of file be_ea.c.
 {
     botimport.BotClientCommand(client, va("say_team %s", str));
 } //end of the function EA_SayTeam
References botlib_import_s::BotClientCommand, botimport, and va().
Referenced by Init_EA_Export().
EA_SelectWeapon()
void EA_SelectWeapon (int client, int weapon)
Definition at line 145 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->weapon = weapon;
 } //end of the function EA_SelectWeapon
References botinputs, and bot_input_s::weapon.
Referenced by BotTravel_BFGJump(), BotTravel_RocketJump(), and Init_EA_Export().
EA_Setup()
int EA_Setup (void)
Definition at line 458 of file be_ea.c.
 {
     //initialize the bot inputs
     botinputs = (bot_input_t *) GetClearedHunkMemory(
                                     botlibglobals.maxclients * sizeof(bot_input_t));
     return BLERR_NOERROR;
 } //end of the function EA_Setup
References BLERR_NOERROR, botinputs, botlibglobals, GetClearedHunkMemory(), and botlib_globals_s::maxclients.
Referenced by Export_BotLibSetup().
EA_Shutdown()
void EA_Shutdown (void)
Definition at line 471 of file be_ea.c.
 {
     FreeMemory(botinputs);
     botinputs = NULL;
 } //end of the function EA_Shutdown
References botinputs, FreeMemory(), and NULL.
Referenced by Export_BotLibShutdown().
EA_Talk()
void EA_Talk (int client)
Definition at line 173 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_TALK;
 } //end of the function EA_Talk
References ACTION_TALK, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_Use()
void EA_Use (int client)
Definition at line 187 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_USE;
 } //end of the function EA_Use
References ACTION_USE, bot_input_s::actionflags, and botinputs.
Referenced by Init_EA_Export().
EA_View()
void EA_View (int client, vec3_t viewangles)
Definition at line 401 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     VectorCopy(viewangles, bi->viewangles);
 } //end of the function EA_View
References botinputs, VectorCopy, and bot_input_s::viewangles.
Referenced by BotTravel_BFGJump(), BotTravel_RocketJump(), and Init_EA_Export().
EA_Walk()
void EA_Walk (int client)
Definition at line 271 of file be_ea.c.
 {
     bot_input_t *bi;
     bi = &botinputs[client];
     bi->actionflags |= ACTION_WALK;
 } //end of the function EA_Walk
References ACTION_WALK, bot_input_s::actionflags, and botinputs.
Referenced by BotTravel_Walk().