ioquake3 doxygen: C:/entry/dev/ioquake3/code/botlib/be_aas_sample.h File Reference
be_aas_sample.h File Reference
Functions
void AAS_PresenceTypeBoundingBox (int presencetype, vec3_t mins, vec3_t maxs)
int AAS_AreaCluster (int areanum)
int AAS_AreaPresenceType (int areanum)
int AAS_PointPresenceType (vec3_t point)
aas_trace_t AAS_TraceClientBBox (vec3_t start, vec3_t end, int presencetype, int passent)
int AAS_TraceAreas (vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
int AAS_BBoxAreas (vec3_t absmins, vec3_t absmaxs, int *areas, int maxareas)
int AAS_AreaInfo (int areanum, aas_areainfo_t *info)
int AAS_PointAreaNum (vec3_t point)
int AAS_PointReachabilityAreaIndex (vec3_t point)
void AAS_FacePlane (int facenum, vec3_t normal, float *dist)
Function Documentation
AAS_AreaCluster()
int AAS_AreaCluster (int areanum)
Definition at line 307 of file be_aas_sample.c.
 {
     if (areanum <= 0 || areanum >= aasworld.numareas)
     {
         botimport.Print(PRT_ERROR, "AAS_AreaCluster: invalid area number\n");
         return 0;
     } //end if
     return aasworld.areasettings[areanum].cluster;
 } //end of the function AAS_AreaCluster
Referenced by AAS_FloodAreas(), AAS_FloodAreas_r(), and BotExportTest().
AAS_AreaInfo()
int AAS_AreaInfo (int areanum, aas_areainfo_t * info)
Definition at line 1362 of file be_aas_sample.c.
 {
     aas_areasettings_t *settings;
     if (!info)
         return 0;
     if (areanum <= 0 || areanum >= aasworld.numareas)
     {
         botimport.Print(PRT_ERROR, "AAS_AreaInfo: areanum %d out of range\n", areanum);
         return 0;
     } //end if
     settings = &aasworld.areasettings[areanum];
     info->cluster = settings->cluster;
     info->contents = settings->contents;
     info->flags = settings->areaflags;
     info->presencetype = settings->presencetype;
     VectorCopy(aasworld.areas[areanum].mins, info->mins);
     VectorCopy(aasworld.areas[areanum].maxs, info->maxs);
     VectorCopy(aasworld.areas[areanum].center, info->center);
     return sizeof(aas_areainfo_t);
 } //end of the function AAS_AreaInfo
Referenced by Init_AAS_Export().
AAS_AreaPresenceType()
int AAS_AreaPresenceType (int areanum)
Definition at line 323 of file be_aas_sample.c.
 {
     if (!aasworld.loaded) return 0;
     if (areanum <= 0 || areanum >= aasworld.numareas)
     {
         botimport.Print(PRT_ERROR, "AAS_AreaPresenceType: invalid area number\n");
         return 0;
     } //end if
     return aasworld.areasettings[areanum].presencetype;
 } //end of the function AAS_AreaPresenceType
Referenced by AAS_Reachability_Grapple(), and BotTravel_Walk().
AAS_BBoxAreas()
int AAS_BBoxAreas (vec3_t absmins, vec3_t absmaxs, int * areas, int maxareas)
Definition at line 1339 of file be_aas_sample.c.
 {
     aas_link_t *linkedareas, *link;
     int num;
     linkedareas = AAS_AASLinkEntity(absmins, absmaxs, -1);
     num = 0;
     for (link = linkedareas; link; link = link->next_area)
     {
         areas[num] = link->areanum;
         num++;
         if (num >= maxareas)
             break;
     } //end for
     AAS_UnlinkFromAreas(linkedareas);
     return num;
 } //end of the function AAS_BBoxAreas
Referenced by Init_AAS_Export().
AAS_FacePlane()
void AAS_FacePlane (int facenum, vec3_t normal, float * dist)
Definition at line 1051 of file be_aas_sample.c.
 {
     aas_plane_t *plane;
     plane = &aasworld.planes[aasworld.faces[facenum].planenum];
     VectorCopy(plane->normal, normal);
     *dist = plane->dist;
 } //end of the function AAS_FacePlane
AAS_PointAreaNum()
int AAS_PointAreaNum (vec3_t point)
Definition at line 212 of file be_aas_sample.c.
 {
     int nodenum;
     vec_t   dist;
     aas_node_t *node;
     aas_plane_t *plane;
     if (!aasworld.loaded)
     {
         botimport.Print(PRT_ERROR, "AAS_PointAreaNum: aas not loaded\n");
         return 0;
     } //end if
     //start with node 1 because node zero is a dummy used for solid leafs
     nodenum = 1;
     while (nodenum > 0)
     {
 //      botimport.Print(PRT_MESSAGE, "[%d]", nodenum);
 #ifdef AAS_SAMPLE_DEBUG
         if (nodenum >= aasworld.numnodes)
         {
             botimport.Print(PRT_ERROR, "nodenum = %d >= aasworld.numnodes = %d\n", nodenum, aasworld.numnodes);
             return 0;
         } //end if
 #endif //AAS_SAMPLE_DEBUG
         node = &aasworld.nodes[nodenum];
 #ifdef AAS_SAMPLE_DEBUG
         if (node->planenum < 0 || node->planenum >= aasworld.numplanes)
         {
             botimport.Print(PRT_ERROR, "node->planenum = %d >= aasworld.numplanes = %d\n", node->planenum, aasworld.numplanes);
             return 0;
         } //end if
 #endif //AAS_SAMPLE_DEBUG
         plane = &aasworld.planes[node->planenum];
         dist = DotProduct(point, plane->normal) - plane->dist;
         if (dist > 0) nodenum = node->children[0];
         else nodenum = node->children[1];
     } //end while
     if (!nodenum)
     {
 #ifdef AAS_SAMPLE_DEBUG
         botimport.Print(PRT_MESSAGE, "in solid\n");
 #endif //AAS_SAMPLE_DEBUG
         return 0;
     } //end if
     return -nodenum;
 } //end of the function AAS_PointAreaNum
Referenced by AAS_AgainstLadder(), AAS_BestReachableArea(), AAS_ClientMovementPrediction(), AAS_FloodAreas(), AAS_NearbySolidOrGap(), AAS_PointPresenceType(), AAS_PointReachabilityAreaIndex(), AAS_RandomGoalArea(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Teleport(), AAS_Reachability_WalkOffLedge(), AAS_Reachability_WeaponJump(), BotFuzzyPointReachabilityArea(), BotInitInfoEntities(), BotTravel_Grapple(), BotTravel_Jump(), and Init_AAS_Export().
AAS_PointPresenceType()
int AAS_PointPresenceType (vec3_t point)
Definition at line 340 of file be_aas_sample.c.
 {
     int areanum;
     if (!aasworld.loaded) return 0;
     areanum = AAS_PointAreaNum(point);
     if (!areanum) return PRESENCE_NONE;
     return aasworld.areasettings[areanum].presencetype;
 } //end of the function AAS_PointPresenceType
Referenced by AAS_ClientMovementPrediction(), and BotExportTest().
AAS_PointReachabilityAreaIndex()
int AAS_PointReachabilityAreaIndex (vec3_t point)
Definition at line 265 of file be_aas_sample.c.
 {
     int areanum, cluster, i, index;
     if (!aasworld.initialized)
         return 0;
     if ( !origin )
     {
         index = 0;
         for (i = 0; i < aasworld.numclusters; i++)
         {
             index += aasworld.clusters[i].numreachabilityareas;
         } //end for
         return index;
     } //end if
     areanum = AAS_PointAreaNum( origin );
     if ( !areanum || !AAS_AreaReachability(areanum) )
         return 0;
     cluster = aasworld.areasettings[areanum].cluster;
     areanum = aasworld.areasettings[areanum].clusterareanum;
     if (cluster < 0)
     {
         cluster = aasworld.portals[-cluster].frontcluster;
         areanum = aasworld.portals[-cluster].clusterareanum[0];
     } //end if
     index = 0;
     for (i = 0; i < cluster; i++)
     {
         index += aasworld.clusters[i].numreachabilityareas;
     } //end for
     index += areanum;
     return index;
 } //end of the function AAS_PointReachabilityAreaIndex
Referenced by Init_AAS_Export().
AAS_PresenceTypeBoundingBox()
void AAS_PresenceTypeBoundingBox (int presencetype, vec3_t mins, vec3_t maxs)
Definition at line 72 of file be_aas_sample.c.
 {
     int index;
     //bounding box size for each presence type
     vec3_t boxmins[3] = {{0, 0, 0}, {-15, -15, -24}, {-15, -15, -24}};
     vec3_t boxmaxs[3] = {{0, 0, 0}, { 15,  15,  32}, { 15,  15,   8}};
     if (presencetype == PRESENCE_NORMAL) index = 1;
     else if (presencetype == PRESENCE_CROUCH) index = 2;
     else
     {
         botimport.Print(PRT_FATAL, "AAS_PresenceTypeBoundingBox: unknown presence type\n");
         index = 2;
     } //end if
     VectorCopy(boxmins[index], mins);
     VectorCopy(boxmaxs[index], maxs);
 } //end of the function AAS_PresenceTypeBoundingBox
Referenced by AAS_AreaEntityCollision(), AAS_ClipToBBox(), AAS_LinkEntityClientBBox(), BotCheckBlocked(), BotOnTopOfEntity(), BotReachabilityArea(), BotTouchingGoal(), and Init_AAS_Export().
AAS_TraceAreas()
int AAS_TraceAreas (vec3_t start, vec3_t end, int * areas, vec3_t * points, int maxareas)
Definition at line 725 of file be_aas_sample.c.
 {
     int side, nodenum, tmpplanenum;
     int numareas;
     float front, back, frac;
     vec3_t cur_start, cur_end, cur_mid;
     aas_tracestack_t tracestack[127];
     aas_tracestack_t *tstack_p;
     aas_node_t *aasnode;
     aas_plane_t *plane;
     numareas = 0;
     areas[0] = 0;
     if (!aasworld.loaded) return numareas;
     tstack_p = tracestack;
     //we start with the whole line on the stack
     VectorCopy(start, tstack_p->start);
     VectorCopy(end, tstack_p->end);
     tstack_p->planenum = 0;
     //start with node 1 because node zero is a dummy for a solid leaf
     tstack_p->nodenum = 1;      //starting at the root of the tree
     tstack_p++;
     while (1)
     {
         //pop up the stack
         tstack_p--;
         //if the trace stack is empty (ended up with a piece of the
         //line to be traced in an area)
         if (tstack_p < tracestack)
         {
             return numareas;
         } //end if
         //number of the current node to test the line against
         nodenum = tstack_p->nodenum;
         //if it is an area
         if (nodenum < 0)
         {
 #ifdef AAS_SAMPLE_DEBUG
             if (-nodenum > aasworld.numareasettings)
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceAreas: -nodenum = %d out of range\n", -nodenum);
                 return numareas;
             } //end if
 #endif //AAS_SAMPLE_DEBUG
             //botimport.Print(PRT_MESSAGE, "areanum = %d, must be %d\n", -nodenum, AAS_PointAreaNum(start));
             areas[numareas] = -nodenum;
             if (points) VectorCopy(tstack_p->start, points[numareas]);
             numareas++;
             if (numareas >= maxareas) return numareas;
             continue;
         } //end if
         //if it is a solid leaf
         if (!nodenum)
         {
             continue;
         } //end if
 #ifdef AAS_SAMPLE_DEBUG
         if (nodenum > aasworld.numnodes)
         {
             botimport.Print(PRT_ERROR, "AAS_TraceAreas: nodenum out of range\n");
             return numareas;
         } //end if
 #endif //AAS_SAMPLE_DEBUG
         //the node to test against
         aasnode = &aasworld.nodes[nodenum];
         //start point of current line to test against node
         VectorCopy(tstack_p->start, cur_start);
         //end point of the current line to test against node
         VectorCopy(tstack_p->end, cur_end);
         //the current node plane
         plane = &aasworld.planes[aasnode->planenum];
         switch(plane->type)
         {/*FIXME: wtf doesn't this work? obviously the node planes aren't always facing positive!!!
             //check for axial planes
             case PLANE_X:
             {
                 front = cur_start[0] - plane->dist;
                 back = cur_end[0] - plane->dist;
                 break;
             } //end case
             case PLANE_Y:
             {
                 front = cur_start[1] - plane->dist;
                 back = cur_end[1] - plane->dist;
                 break;
             } //end case
             case PLANE_Z:
             {
                 front = cur_start[2] - plane->dist;
                 back = cur_end[2] - plane->dist;
                 break;
             } //end case*/
             default: //gee it's not an axial plane
             {
                 front = DotProduct(cur_start, plane->normal) - plane->dist;
                 back = DotProduct(cur_end, plane->normal) - plane->dist;
                 break;
             } //end default
         } //end switch
         //if the whole to be traced line is totally at the front of this node
         //only go down the tree with the front child
         if (front > 0 && back > 0)
         {
             //keep the current start and end point on the stack
             //and go down the tree with the front child
             tstack_p->nodenum = aasnode->children[0];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceAreas: stack overflow\n");
                 return numareas;
             } //end if
         } //end if
         //if the whole to be traced line is totally at the back of this node
         //only go down the tree with the back child
         else if (front <= 0 && back <= 0)
         {
             //keep the current start and end point on the stack
             //and go down the tree with the back child
             tstack_p->nodenum = aasnode->children[1];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceAreas: stack overflow\n");
                 return numareas;
             } //end if
         } //end if
         //go down the tree both at the front and back of the node
         else
         {
             tmpplanenum = tstack_p->planenum;
             //calculate the hitpoint with the node (split point of the line)
             //put the crosspoint TRACEPLANE_EPSILON pixels on the near side
             if (front < 0) frac = (front)/(front-back);
             else frac = (front)/(front-back);
             if (frac < 0) frac = 0;
             else if (frac > 1) frac = 1;
             //frac = front / (front-back);
             //
             cur_mid[0] = cur_start[0] + (cur_end[0] - cur_start[0]) * frac;
             cur_mid[1] = cur_start[1] + (cur_end[1] - cur_start[1]) * frac;
             cur_mid[2] = cur_start[2] + (cur_end[2] - cur_start[2]) * frac;
 //          AAS_DrawPlaneCross(cur_mid, plane->normal, plane->dist, plane->type, LINECOLOR_RED);
             //side the front part of the line is on
             side = front < 0;
             //first put the end part of the line on the stack (back side)
             VectorCopy(cur_mid, tstack_p->start);
             //not necessary to store because still on stack
             //VectorCopy(cur_end, tstack_p->end);
             tstack_p->planenum = aasnode->planenum;
             tstack_p->nodenum = aasnode->children[!side];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceAreas: stack overflow\n");
                 return numareas;
             } //end if
             //now put the part near the start of the line on the stack so we will
             //continue with thats part first. This way we'll find the first
             //hit of the bbox
             VectorCopy(cur_start, tstack_p->start);
             VectorCopy(cur_mid, tstack_p->end);
             tstack_p->planenum = tmpplanenum;
             tstack_p->nodenum = aasnode->children[side];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceAreas: stack overflow\n");
                 return numareas;
             } //end if
         } //end else
     } //end while
 //  return numareas;
 } //end of the function AAS_TraceAreas
AAS_TraceClientBBox()
aas_trace_t AAS_TraceClientBBox (vec3_t start, vec3_t end, int presencetype, int passent)
Definition at line 448 of file be_aas_sample.c.
 {
     int side, nodenum, tmpplanenum;
     float front, back, frac;
     vec3_t cur_start, cur_end, cur_mid, v1, v2;
     aas_tracestack_t tracestack[127];
     aas_tracestack_t *tstack_p;
     aas_node_t *aasnode;
     aas_plane_t *plane;
     aas_trace_t trace;
     //clear the trace structure
     Com_Memset(&trace, 0, sizeof(aas_trace_t));
     if (!aasworld.loaded) return trace;
     tstack_p = tracestack;
     //we start with the whole line on the stack
     VectorCopy(start, tstack_p->start);
     VectorCopy(end, tstack_p->end);
     tstack_p->planenum = 0;
     //start with node 1 because node zero is a dummy for a solid leaf
     tstack_p->nodenum = 1;      //starting at the root of the tree
     tstack_p++;
     while (1)
     {
         //pop up the stack
         tstack_p--;
         //if the trace stack is empty (ended up with a piece of the
         //line to be traced in an area)
         if (tstack_p < tracestack)
         {
             tstack_p++;
             //nothing was hit
             trace.startsolid = qfalse;
             trace.fraction = 1.0;
             //endpos is the end of the line
             VectorCopy(end, trace.endpos);
             //nothing hit
             trace.ent = 0;
             trace.area = 0;
             trace.planenum = 0;
             return trace;
         } //end if
         //number of the current node to test the line against
         nodenum = tstack_p->nodenum;
         //if it is an area
         if (nodenum < 0)
         {
 #ifdef AAS_SAMPLE_DEBUG
             if (-nodenum > aasworld.numareasettings)
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceBoundingBox: -nodenum out of range\n");
                 return trace;
             } //end if
 #endif //AAS_SAMPLE_DEBUG
             //botimport.Print(PRT_MESSAGE, "areanum = %d, must be %d\n", -nodenum, AAS_PointAreaNum(start));
             //if can't enter the area because it hasn't got the right presence type
             if (!(aasworld.areasettings[-nodenum].presencetype & presencetype))
             {
                 //if the start point is still the initial start point
                 //NOTE: no need for epsilons because the points will be
                 //exactly the same when they're both the start point
                 if (tstack_p->start[0] == start[0] &&
                         tstack_p->start[1] == start[1] &&
                         tstack_p->start[2] == start[2])
                 {
                     trace.startsolid = qtrue;
                     trace.fraction = 0.0;
                     VectorClear(v1);
                 } //end if
                 else
                 {
                     trace.startsolid = qfalse;
                     VectorSubtract(end, start, v1);
                     VectorSubtract(tstack_p->start, start, v2);
                     trace.fraction = VectorLength(v2) / VectorNormalize(v1);
                     VectorMA(tstack_p->start, -0.125, v1, tstack_p->start);
                 } //end else
                 VectorCopy(tstack_p->start, trace.endpos);
                 trace.ent = 0;
                 trace.area = -nodenum;
 //              VectorSubtract(end, start, v1);
                 trace.planenum = tstack_p->planenum;
                 //always take the plane with normal facing towards the trace start
                 plane = &aasworld.planes[trace.planenum];
                 if (DotProduct(v1, plane->normal) > 0) trace.planenum ^= 1;
                 return trace;
             } //end if
             else
             {
                 if (passent >= 0)
                 {
                     if (AAS_AreaEntityCollision(-nodenum, tstack_p->start,
                                                     tstack_p->end, presencetype, passent,
                                                     &trace))
                     {
                         if (!trace.startsolid)
{
                             VectorSubtract(end, start, v1);
                             VectorSubtract(trace.endpos, start, v2);
                             trace.fraction = VectorLength(v2) / VectorLength(v1);
                         } //end if
                         return trace;
                     } //end if
                 } //end if
             } //end else
             trace.lastarea = -nodenum;
             continue;
         } //end if
         //if it is a solid leaf
         if (!nodenum)
         {
             //if the start point is still the initial start point
             //NOTE: no need for epsilons because the points will be
             //exactly the same when they're both the start point
             if (tstack_p->start[0] == start[0] &&
                     tstack_p->start[1] == start[1] &&
                     tstack_p->start[2] == start[2])
             {
                 trace.startsolid = qtrue;
                 trace.fraction = 0.0;
                 VectorClear(v1);
             } //end if
             else
             {
                 trace.startsolid = qfalse;
                 VectorSubtract(end, start, v1);
                 VectorSubtract(tstack_p->start, start, v2);
                 trace.fraction = VectorLength(v2) / VectorNormalize(v1);
                 VectorMA(tstack_p->start, -0.125, v1, tstack_p->start);
             } //end else
             VectorCopy(tstack_p->start, trace.endpos);
             trace.ent = 0;
             trace.area = 0; //hit solid leaf
 //          VectorSubtract(end, start, v1);
             trace.planenum = tstack_p->planenum;
             //always take the plane with normal facing towards the trace start
             plane = &aasworld.planes[trace.planenum];
             if (DotProduct(v1, plane->normal) > 0) trace.planenum ^= 1;
             return trace;
         } //end if
 #ifdef AAS_SAMPLE_DEBUG
         if (nodenum > aasworld.numnodes)
         {
             botimport.Print(PRT_ERROR, "AAS_TraceBoundingBox: nodenum out of range\n");
             return trace;
         } //end if
 #endif //AAS_SAMPLE_DEBUG
         //the node to test against
         aasnode = &aasworld.nodes[nodenum];
         //start point of current line to test against node
         VectorCopy(tstack_p->start, cur_start);
         //end point of the current line to test against node
         VectorCopy(tstack_p->end, cur_end);
         //the current node plane
         plane = &aasworld.planes[aasnode->planenum];
         switch(plane->type)
         {/*FIXME: wtf doesn't this work? obviously the axial node planes aren't always facing positive!!!
             //check for axial planes
             case PLANE_X:
             {
                 front = cur_start[0] - plane->dist;
                 back = cur_end[0] - plane->dist;
                 break;
             } //end case
             case PLANE_Y:
             {
                 front = cur_start[1] - plane->dist;
                 back = cur_end[1] - plane->dist;
                 break;
             } //end case
             case PLANE_Z:
             {
                 front = cur_start[2] - plane->dist;
                 back = cur_end[2] - plane->dist;
                 break;
             } //end case*/
             default: //gee it's not an axial plane
             {
                 front = DotProduct(cur_start, plane->normal) - plane->dist;
                 back = DotProduct(cur_end, plane->normal) - plane->dist;
                 break;
             } //end default
         } //end switch
         // bk010221 - old location of FPE hack and divide by zero expression
         //if the whole to be traced line is totally at the front of this node
         //only go down the tree with the front child
         if ((front >= -ON_EPSILON && back >= -ON_EPSILON))
         {
             //keep the current start and end point on the stack
             //and go down the tree with the front child
             tstack_p->nodenum = aasnode->children[0];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceBoundingBox: stack overflow\n");
                 return trace;
             } //end if
         } //end if
         //if the whole to be traced line is totally at the back of this node
         //only go down the tree with the back child
         else if ((front < ON_EPSILON && back < ON_EPSILON))
         {
             //keep the current start and end point on the stack
             //and go down the tree with the back child
             tstack_p->nodenum = aasnode->children[1];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceBoundingBox: stack overflow\n");
                 return trace;
             } //end if
         } //end if
         //go down the tree both at the front and back of the node
         else
         {
             tmpplanenum = tstack_p->planenum;
             // bk010221 - new location of divide by zero (see above)
             if ( front == back ) front -= 0.001f; // bk0101022 - hack/FPE
                     //calculate the hitpoint with the node (split point of the line)
             //put the crosspoint TRACEPLANE_EPSILON pixels on the near side
             if (front < 0) frac = (front + TRACEPLANE_EPSILON)/(front-back);
             else frac = (front - TRACEPLANE_EPSILON)/(front-back); // bk010221
             //
             if (frac < 0)
                 frac = 0.001f; //0
             else if (frac > 1)
                 frac = 0.999f; //1
             //frac = front / (front-back);
             //
             cur_mid[0] = cur_start[0] + (cur_end[0] - cur_start[0]) * frac;
             cur_mid[1] = cur_start[1] + (cur_end[1] - cur_start[1]) * frac;
             cur_mid[2] = cur_start[2] + (cur_end[2] - cur_start[2]) * frac;
 //          AAS_DrawPlaneCross(cur_mid, plane->normal, plane->dist, plane->type, LINECOLOR_RED);
             //side the front part of the line is on
             side = front < 0;
             //first put the end part of the line on the stack (back side)
             VectorCopy(cur_mid, tstack_p->start);
             //not necessary to store because still on stack
             //VectorCopy(cur_end, tstack_p->end);
             tstack_p->planenum = aasnode->planenum;
             tstack_p->nodenum = aasnode->children[!side];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceBoundingBox: stack overflow\n");
                 return trace;
             } //end if
             //now put the part near the start of the line on the stack so we will
             //continue with thats part first. This way we'll find the first
             //hit of the bbox
             VectorCopy(cur_start, tstack_p->start);
             VectorCopy(cur_mid, tstack_p->end);
             tstack_p->planenum = tmpplanenum;
             tstack_p->nodenum = aasnode->children[side];
             tstack_p++;
             if (tstack_p >= &tracestack[127])
             {
                 botimport.Print(PRT_ERROR, "AAS_TraceBoundingBox: stack overflow\n");
                 return trace;
             } //end if
         } //end else
     } //end while
 //  return trace;
 } //end of the function AAS_TraceClientBBox
Referenced by AAS_BestReachableArea(), AAS_ClientMovementPrediction(), AAS_GetJumpPadInfo(), AAS_OnGround(), AAS_RandomGoalArea(), AAS_Reachability_Elevator(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Teleport(), AAS_Reachability_WalkOffLedge(), AAS_Reachability_WeaponJump(), BotCheckBarrierJump(), BotGapDistance(), and BotReachabilityArea().