ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_entity.h File Reference
be_aas_entity.h File Reference
Functions
void AAS_EntitySize (int entnum, vec3_t mins, vec3_t maxs)
int AAS_EntityModelNum (int entnum)
int AAS_OriginOfMoverWithModelNum (int modelnum, vec3_t origin)
int AAS_BestReachableEntityArea (int entnum)
void AAS_EntityInfo (int entnum, aas_entityinfo_t *info)
int AAS_NextEntity (int entnum)
void AAS_EntityOrigin (int entnum, vec3_t origin)
int AAS_EntityType (int entnum)
int AAS_EntityModelindex (int entnum)
Function Documentation
AAS_BestReachableEntityArea()
int AAS_BestReachableEntityArea (int entnum)
Definition at line 414 of file be_aas_entity.c.
 {
     aas_entity_t *ent;
     ent = &aasworld.entities[entnum];
     return AAS_BestReachableLinkArea(ent->areas);
 } //end of the function AAS_BestReachableEntityArea
References AAS_BestReachableLinkArea(), aasworld, aas_entity_s::areas, and aas_s::entities.
AAS_EntityInfo()
void AAS_EntityInfo (int entnum, aas_entityinfo_t * info)
Definition at line 171 of file be_aas_entity.c.
 {
     if (!aasworld.initialized)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityInfo: aasworld not initialized\n");
         Com_Memset(info, 0, sizeof(aas_entityinfo_t));
         return;
     } //end if
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityInfo: entnum %d out of range\n", entnum);
         Com_Memset(info, 0, sizeof(aas_entityinfo_t));
         return;
     } //end if
     Com_Memcpy(info, &aasworld.entities[entnum].i, sizeof(aas_entityinfo_t));
 } //end of the function AAS_EntityInfo
References aasworld, botimport, Com_Memcpy, Com_Memset, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, and PRT_FATAL.
Referenced by BotFindEntityForLevelItem(), BotItemGoalInVisButNotVisible(), BotUpdateEntityItems(), GrappleState(), and Init_AAS_Export().
AAS_EntityModelindex()
int AAS_EntityModelindex (int entnum)
Definition at line 212 of file be_aas_entity.c.
 {
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityModelindex: entnum %d out of range\n", entnum);
         return 0;
     } //end if
     return aasworld.entities[entnum].i.modelindex;
 } //end of the function AAS_EntityModelindex
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::modelindex, and PRT_FATAL.
Referenced by BotFindEntityForLevelItem(), BotMoveToGoal(), BotReachabilityArea(), and BotUpdateEntityItems().
AAS_EntityModelNum()
int AAS_EntityModelNum (int entnum)
Definition at line 244 of file be_aas_entity.c.
 {
     if (!aasworld.initialized) return 0;
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityModelNum: entnum %d out of range\n", entnum);
         return 0;
     } //end if
     return aasworld.entities[entnum].i.modelindex;
 } //end of the function AAS_EntityModelNum
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, aas_entityinfo_s::modelindex, and PRT_FATAL.
Referenced by BotOnMover().
AAS_EntityOrigin()
void AAS_EntityOrigin (int entnum, vec3_t origin)
Definition at line 195 of file be_aas_entity.c.
 {
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityOrigin: entnum %d out of range\n", entnum);
         VectorClear(origin);
         return;
     } //end if
     VectorCopy(aasworld.entities[entnum].i.origin, origin);
 } //end of the function AAS_EntityOrigin
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::origin, PRT_FATAL, VectorClear, and VectorCopy.
AAS_EntitySize()
void AAS_EntitySize (int entnum, vec3_t mins, vec3_t maxs)
Definition at line 286 of file be_aas_entity.c.
 {
     aas_entity_t *ent;
     if (!aasworld.initialized) return;
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntitySize: entnum %d out of range\n", entnum);
         return;
     } //end if
     ent = &aasworld.entities[entnum];
     VectorCopy(ent->i.mins, mins);
     VectorCopy(ent->i.maxs, maxs);
 } //end of the function AAS_EntitySize
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, aas_entityinfo_s::maxs, aas_entityinfo_s::mins, PRT_FATAL, and VectorCopy.
AAS_EntityType()
int AAS_EntityType (int entnum)
Definition at line 227 of file be_aas_entity.c.
 {
     if (!aasworld.initialized) return 0;
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityType: entnum %d out of range\n", entnum);
         return 0;
     } //end if
     return aasworld.entities[entnum].i.type;
 } //end of the AAS_EntityType
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, PRT_FATAL, and aas_entityinfo_s::type.
Referenced by BotUpdateEntityItems(), and GrappleState().
AAS_NextEntity()
int AAS_NextEntity (int entnum)
Definition at line 427 of file be_aas_entity.c.
 {
     if (!aasworld.loaded) return 0;
     if (entnum < 0) entnum = -1;
     while(++entnum < aasworld.maxentities)
     {
         if (aasworld.entities[entnum].i.valid) return entnum;
     } //end while
     return 0;
 } //end of the function AAS_NextEntity
References aasworld, aas_s::entities, aas_entity_s::i, aas_s::loaded, aas_s::maxentities, and aas_entityinfo_s::valid.
Referenced by BotFindEntityForLevelItem(), BotUpdateEntityItems(), and GrappleState().
AAS_OriginOfMoverWithModelNum()
int AAS_OriginOfMoverWithModelNum (int modelnum, vec3_t origin)
Definition at line 261 of file be_aas_entity.c.
 {
     int i;
     aas_entity_t *ent;
     for (i = 0; i < aasworld.maxentities; i++)
     {
         ent = &aasworld.entities[i];
         if (ent->i.type == ET_MOVER)
         {
             if (ent->i.modelindex == modelnum)
             {
                 VectorCopy(ent->i.origin, origin);
                 return qtrue;
             } //end if
         } //end if
     } //end for
     return qfalse;
 } //end of the function AAS_OriginOfMoverWithModelNum
References aasworld, aas_s::entities, ET_MOVER, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::modelindex, aas_entityinfo_s::origin, qfalse, qtrue, aas_entityinfo_s::type, and VectorCopy.
Referenced by BotFuncBobStartEnd(), BotOnMover(), MoverBottomCenter(), and MoverDown().