ioquake3 doxygen: C:/entry/dev/ioq3/code/client/libmumblelink.c File Reference
libmumblelink.c File Reference
#include <unistd.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "libmumblelink.h"
Classes
struct LinkedMem
Macros
#define MIN(a, b) ((a)<(b)?(a):(b))
Functions
static int32_t GetTickCount (void)
int mumble_link (const char *name)
void mumble_update_coordinates (float fPosition[3], float fFront[3], float fTop[3])
void mumble_update_coordinates2 (float fAvatarPosition[3], float fAvatarFront[3], float fAvatarTop[3], float fCameraPosition[3], float fCameraFront[3], float fCameraTop[3])
void mumble_set_identity (const char *identity)
void mumble_set_context (const unsigned char *context, size_t len)
void mumble_set_description (const char *description)
void mumble_unlink ()
int mumble_islinked (void)
Variables
static LinkedMem * lm = NULL
Macro Definition Documentation
MIN
#define MIN (a, b) ((a)<(b)?(a):(b))
Definition at line 46 of file libmumblelink.c.
Function Documentation
GetTickCount()
static int32_t GetTickCount (void) static
Definition at line 72 of file libmumblelink.c.
 {
     struct timeval tv;
     gettimeofday(&tv,NULL);
     return tv.tv_usec / 1000 + tv.tv_sec * 1000;
 }
References NULL, and tv().
Referenced by mumble_update_coordinates2().
mumble_islinked()
int mumble_islinked (void)
Definition at line 185 of file libmumblelink.c.
 {
     return lm != NULL;
 }
References lm, and NULL.
Referenced by CL_Disconnect(), and CL_FirstSnapshot().
mumble_link()
int mumble_link (const char * name)
Definition at line 81 of file libmumblelink.c.
 {
 #ifdef WIN32
     if(lm)
         return 0;
     hMapObject = OpenFileMappingW(FILE_MAP_ALL_ACCESS, FALSE, L"MumbleLink");
     if (hMapObject == NULL)
         return -1;
     lm = (LinkedMem *) MapViewOfFile(hMapObject, FILE_MAP_ALL_ACCESS, 0, 0, sizeof(LinkedMem));
     if (lm == NULL) {
         CloseHandle(hMapObject);
         hMapObject = NULL;
         return -1;
     }
 #else
     char file[256];
     int shmfd;
     if(lm)
         return 0;
     snprintf(file, sizeof (file), "/MumbleLink.%d", getuid());
     shmfd = shm_open(file, O_RDWR, S_IRUSR | S_IWUSR);
     if(shmfd < 0) {
         return -1;
     }
     lm = (LinkedMem *) (mmap(NULL, sizeof(LinkedMem), PROT_READ | PROT_WRITE, MAP_SHARED, shmfd,0));
     if (lm == (void *) (-1)) {
         lm = NULL;
         close(shmfd);
         return -1;
     }
     close(shmfd);
 #endif
     memset(lm, 0, sizeof(LinkedMem));
     mbstowcs(lm->name, name, sizeof(lm->name) / sizeof(wchar_t));
     return 0;
 }
References lm, LinkedMem::name, and NULL.
Referenced by CL_FirstSnapshot().
mumble_set_context()
void mumble_set_context (const unsigned char * context, size_t len)
Definition at line 153 of file libmumblelink.c.
 {
     if (!lm)
         return;
     len = MIN(sizeof(lm->context), len);
     lm->context_len = len;
     memcpy(lm->context, context, len);
 }
References LinkedMem::context, LinkedMem::context_len, lm, and MIN.
mumble_set_description()
void mumble_set_description (const char * description)
Definition at line 162 of file libmumblelink.c.
 {
     size_t len;
     if (!lm)
         return;
     len = MIN(sizeof(lm->description)/sizeof(wchar_t), strlen(description)+1);
     mbstowcs(lm->description, description, len);
 }
References LinkedMem::description, lm, and MIN.
mumble_set_identity()
void mumble_set_identity (const char * identity)
Definition at line 144 of file libmumblelink.c.
 {
     size_t len;
     if (!lm)
         return;
     len = MIN(sizeof(lm->identity)/sizeof(wchar_t), strlen(identity)+1);
     mbstowcs(lm->identity, identity, len);
 }
References LinkedMem::identity, lm, and MIN.
mumble_unlink()
void mumble_unlink ()
Definition at line 171 of file libmumblelink.c.
 {
     if(!lm)
         return;
 #ifdef WIN32
     UnmapViewOfFile(lm);
     CloseHandle(hMapObject);
     hMapObject = NULL;
 #else
     munmap(lm, sizeof(LinkedMem));
 #endif
     lm = NULL;
 }
References lm, and NULL.
Referenced by CL_Disconnect().
mumble_update_coordinates()
void mumble_update_coordinates (float fPosition[3], float fFront[3], float fTop[3])
Definition at line 123 of file libmumblelink.c.
 {
     mumble_update_coordinates2(fPosition, fFront, fTop, fPosition, fFront, fTop);
 }
References mumble_update_coordinates2().
mumble_update_coordinates2()
void mumble_update_coordinates2 (float fAvatarPosition[3], float fAvatarFront[3], float fAvatarTop[3], float fCameraPosition[3], float fCameraFront[3], float fCameraTop[3])
Definition at line 128 of file libmumblelink.c.
 {
     if (!lm)
         return;
     memcpy(lm->fAvatarPosition, fAvatarPosition, sizeof(lm->fAvatarPosition));
     memcpy(lm->fAvatarFront, fAvatarFront, sizeof(lm->fAvatarFront));
     memcpy(lm->fAvatarTop, fAvatarTop, sizeof(lm->fAvatarTop));
     memcpy(lm->fCameraPosition, fCameraPosition, sizeof(lm->fCameraPosition));
     memcpy(lm->fCameraFront, fCameraFront, sizeof(lm->fCameraFront));
     memcpy(lm->fCameraTop, fCameraTop, sizeof(lm->fCameraTop));
     lm->uiVersion = 2;
     lm->uiTick = GetTickCount();
 }
References LinkedMem::fAvatarFront, LinkedMem::fAvatarPosition, LinkedMem::fAvatarTop, LinkedMem::fCameraFront, LinkedMem::fCameraPosition, LinkedMem::fCameraTop, GetTickCount(), lm, LinkedMem::uiTick, and LinkedMem::uiVersion.
Referenced by mumble_update_coordinates().
Variable Documentation
lm
LinkedMem* lm = NULL static
Definition at line 67 of file libmumblelink.c.
Referenced by mumble_islinked(), mumble_link(), mumble_set_context(), mumble_set_description(), mumble_set_identity(), mumble_unlink(), and mumble_update_coordinates2().