ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_specifyserver.c File Reference
ui_specifyserver.c File Reference
#include "ui_local.h"
Classes
struct specifyserver_t
Macros
#define SPECIFYSERVER_FRAMEL "menu/art/frame2_l"
#define SPECIFYSERVER_FRAMER "menu/art/frame1_r"
#define SPECIFYSERVER_BACK0 "menu/art/back_0"
#define SPECIFYSERVER_BACK1 "menu/art/back_1"
#define SPECIFYSERVER_FIGHT0 "menu/art/fight_0"
#define SPECIFYSERVER_FIGHT1 "menu/art/fight_1"
#define ID_SPECIFYSERVERBACK 102
#define ID_SPECIFYSERVERGO 103
Functions
static void SpecifyServer_Event (void *ptr, int event)
void SpecifyServer_MenuInit (void)
void SpecifyServer_Cache (void)
void UI_SpecifyServerMenu (void)
Variables
static char * specifyserver_artlist []
static specifyserver_t s_specifyserver
Macro Definition Documentation
ID_SPECIFYSERVERBACK
#define ID_SPECIFYSERVERBACK 102
Definition at line 36 of file ui_specifyserver.c.
ID_SPECIFYSERVERGO
#define ID_SPECIFYSERVERGO 103
Definition at line 37 of file ui_specifyserver.c.
SPECIFYSERVER_BACK0
#define SPECIFYSERVER_BACK0 "menu/art/back_0"
Definition at line 31 of file ui_specifyserver.c.
SPECIFYSERVER_BACK1
#define SPECIFYSERVER_BACK1 "menu/art/back_1"
Definition at line 32 of file ui_specifyserver.c.
SPECIFYSERVER_FIGHT0
#define SPECIFYSERVER_FIGHT0 "menu/art/fight_0"
Definition at line 33 of file ui_specifyserver.c.
SPECIFYSERVER_FIGHT1
#define SPECIFYSERVER_FIGHT1 "menu/art/fight_1"
Definition at line 34 of file ui_specifyserver.c.
SPECIFYSERVER_FRAMEL
#define SPECIFYSERVER_FRAMEL "menu/art/frame2_l"
Definition at line 29 of file ui_specifyserver.c.
SPECIFYSERVER_FRAMER
#define SPECIFYSERVER_FRAMER "menu/art/frame1_r"
Definition at line 30 of file ui_specifyserver.c.
Function Documentation
SpecifyServer_Cache()
void SpecifyServer_Cache (void)
Definition at line 190 of file ui_specifyserver.c.
 {
     int i;
     // touch all our pics
     for (i=0; ;i++)
     {
         if (!specifyserver_artlist[i])
             break;
         trap_R_RegisterShaderNoMip(specifyserver_artlist[i]);
     }
 }
References specifyserver_artlist, and trap_R_RegisterShaderNoMip().
Referenced by SpecifyServer_MenuInit(), and UI_Cache_f().
SpecifyServer_Event()
static void SpecifyServer_Event (void * ptr, int event) static
Definition at line 69 of file ui_specifyserver.c.
 {
     char    buff[256];
     switch (((menucommon_s*)ptr)->id)
     {
         case ID_SPECIFYSERVERGO:
             if (event != QM_ACTIVATED)
                 break;
             if (s_specifyserver.domain.field.buffer[0])
             {
                 strcpy(buff,s_specifyserver.domain.field.buffer);
                 if (s_specifyserver.port.field.buffer[0])
                     Com_sprintf( buff+strlen(buff), 128, ":%s", s_specifyserver.port.field.buffer );
                 trap_Cmd_ExecuteText( EXEC_APPEND, va( "connect %s\n", buff ) );
             }
             break;
         case ID_SPECIFYSERVERBACK:
             if (event != QM_ACTIVATED)
                 break;
             UI_PopMenu();
             break;
     }
 }
References mfield_t::buffer, Com_sprintf(), specifyserver_t::domain, EXEC_APPEND, menufield_s::field, ID_SPECIFYSERVERBACK, ID_SPECIFYSERVERGO, specifyserver_t::port, QM_ACTIVATED, s_specifyserver, trap_Cmd_ExecuteText(), UI_PopMenu(), and va().
Referenced by SpecifyServer_MenuInit().
SpecifyServer_MenuInit()
void SpecifyServer_MenuInit (void)
Definition at line 103 of file ui_specifyserver.c.
 {
     // zero set all our globals
     memset( &s_specifyserver, 0 ,sizeof(specifyserver_t) );
     SpecifyServer_Cache();
     s_specifyserver.menu.wrapAround = qtrue;
     s_specifyserver.menu.fullscreen = qtrue;
     s_specifyserver.banner.generic.type  = MTYPE_BTEXT;
     s_specifyserver.banner.generic.x     = 320;
     s_specifyserver.banner.generic.y     = 16;
     s_specifyserver.banner.string        = "SPECIFY SERVER";
     s_specifyserver.banner.color         = color_white;
     s_specifyserver.banner.style         = UI_CENTER;
     s_specifyserver.framel.generic.type  = MTYPE_BITMAP;
     s_specifyserver.framel.generic.name  = SPECIFYSERVER_FRAMEL;
     s_specifyserver.framel.generic.flags = QMF_INACTIVE;
     s_specifyserver.framel.generic.x     = 0;
     s_specifyserver.framel.generic.y     = 78;
     s_specifyserver.framel.width         = 256;
     s_specifyserver.framel.height        = 329;
     s_specifyserver.framer.generic.type  = MTYPE_BITMAP;
     s_specifyserver.framer.generic.name  = SPECIFYSERVER_FRAMER;
     s_specifyserver.framer.generic.flags = QMF_INACTIVE;
     s_specifyserver.framer.generic.x     = 376;
     s_specifyserver.framer.generic.y     = 76;
     s_specifyserver.framer.width         = 256;
     s_specifyserver.framer.height        = 334;
     s_specifyserver.domain.generic.type       = MTYPE_FIELD;
     s_specifyserver.domain.generic.name       = "Address:";
     s_specifyserver.domain.generic.flags      = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     s_specifyserver.domain.generic.x          = 206;
     s_specifyserver.domain.generic.y          = 220;
     s_specifyserver.domain.field.widthInChars = 38;
     s_specifyserver.domain.field.maxchars     = 80;
     s_specifyserver.port.generic.type       = MTYPE_FIELD;
     s_specifyserver.port.generic.name       = "Port:";
     s_specifyserver.port.generic.flags      = QMF_PULSEIFFOCUS|QMF_SMALLFONT|QMF_NUMBERSONLY;
     s_specifyserver.port.generic.x          = 206;
     s_specifyserver.port.generic.y          = 250;
     s_specifyserver.port.field.widthInChars = 6;
     s_specifyserver.port.field.maxchars     = 5;
     s_specifyserver.go.generic.type     = MTYPE_BITMAP;
     s_specifyserver.go.generic.name     = SPECIFYSERVER_FIGHT0;
     s_specifyserver.go.generic.flags    = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_specifyserver.go.generic.callback = SpecifyServer_Event;
     s_specifyserver.go.generic.id       = ID_SPECIFYSERVERGO;
     s_specifyserver.go.generic.x        = 640;
     s_specifyserver.go.generic.y        = 480-64;
     s_specifyserver.go.width            = 128;
     s_specifyserver.go.height           = 64;
     s_specifyserver.go.focuspic         = SPECIFYSERVER_FIGHT1;
     s_specifyserver.back.generic.type     = MTYPE_BITMAP;
     s_specifyserver.back.generic.name     = SPECIFYSERVER_BACK0;
     s_specifyserver.back.generic.flags    = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_specifyserver.back.generic.callback = SpecifyServer_Event;
     s_specifyserver.back.generic.id       = ID_SPECIFYSERVERBACK;
     s_specifyserver.back.generic.x        = 0;
     s_specifyserver.back.generic.y        = 480-64;
     s_specifyserver.back.width            = 128;
     s_specifyserver.back.height           = 64;
     s_specifyserver.back.focuspic         = SPECIFYSERVER_BACK1;
     Menu_AddItem( &s_specifyserver.menu, &s_specifyserver.banner );
     Menu_AddItem( &s_specifyserver.menu, &s_specifyserver.framel );
     Menu_AddItem( &s_specifyserver.menu, &s_specifyserver.framer );
     Menu_AddItem( &s_specifyserver.menu, &s_specifyserver.domain );
     Menu_AddItem( &s_specifyserver.menu, &s_specifyserver.port );
     Menu_AddItem( &s_specifyserver.menu, &s_specifyserver.go );
     Menu_AddItem( &s_specifyserver.menu, &s_specifyserver.back );
     Com_sprintf( s_specifyserver.port.field.buffer, 6, "%i", 27960 );
 }
References specifyserver_t::back, specifyserver_t::banner, mfield_t::buffer, menucommon_s::callback, menutext_s::color, color_white, Com_sprintf(), specifyserver_t::domain, menufield_s::field, menucommon_s::flags, menubitmap_s::focuspic, specifyserver_t::framel, specifyserver_t::framer, _tag_menuframework::fullscreen, menufield_s::generic, menubitmap_s::generic, menutext_s::generic, specifyserver_t::go, menubitmap_s::height, menucommon_s::id, ID_SPECIFYSERVERBACK, ID_SPECIFYSERVERGO, mfield_t::maxchars, specifyserver_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, menucommon_s::name, specifyserver_t::port, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_NUMBERSONLY, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, QMF_SMALLFONT, qtrue, s_specifyserver, SPECIFYSERVER_BACK0, SPECIFYSERVER_BACK1, SpecifyServer_Cache(), SpecifyServer_Event(), SPECIFYSERVER_FIGHT0, SPECIFYSERVER_FIGHT1, SPECIFYSERVER_FRAMEL, SPECIFYSERVER_FRAMER, menutext_s::string, menutext_s::style, menucommon_s::type, UI_CENTER, menubitmap_s::width, mfield_t::widthInChars, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_SpecifyServerMenu().
UI_SpecifyServerMenu()
void UI_SpecifyServerMenu (void)
Definition at line 208 of file ui_specifyserver.c.
 {
     SpecifyServer_MenuInit();
     UI_PushMenu( &s_specifyserver.menu );
 }
References specifyserver_t::menu, s_specifyserver, SpecifyServer_MenuInit(), and UI_PushMenu().
Referenced by ArenaServers_Event().
Variable Documentation
s_specifyserver
specifyserver_t s_specifyserver static
Definition at line 62 of file ui_specifyserver.c.
Referenced by SpecifyServer_Event(), SpecifyServer_MenuInit(), and UI_SpecifyServerMenu().
specifyserver_artlist
char* specifyserver_artlist[] static
Initial value:
=
{
    SPECIFYSERVER_FRAMEL,
    SPECIFYSERVER_FRAMER,
    SPECIFYSERVER_BACK0,
    SPECIFYSERVER_BACK1,
    SPECIFYSERVER_FIGHT0,
    SPECIFYSERVER_FIGHT1,
    NULL
}
Definition at line 39 of file ui_specifyserver.c.
Referenced by SpecifyServer_Cache().