ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_utils.c File Reference
g_utils.c File Reference
#include "g_local.h"
Classes
struct shaderRemap_t
Macros
#define MAX_SHADER_REMAPS 128
#define MAXCHOICES 32
Functions
void AddRemap (const char *oldShader, const char *newShader, float timeOffset)
const char * BuildShaderStateConfig (void)
int G_FindConfigstringIndex (char *name, int start, int max, qboolean create)
int G_ModelIndex (char *name)
int G_SoundIndex (char *name)
void G_TeamCommand (team_t team, char *cmd)
gentity_t * G_Find (gentity_t *from, int fieldofs, const char *match)
gentity_t * G_PickTarget (char *targetname)
void G_UseTargets (gentity_t *ent, gentity_t *activator)
float * tv (float x, float y, float z)
char * vtos (const vec3_t v)
void G_SetMovedir (vec3_t angles, vec3_t movedir)
float vectoyaw (const vec3_t vec)
void G_InitGentity (gentity_t *e)
gentity_t * G_Spawn (void)
qboolean G_EntitiesFree (void)
void G_FreeEntity (gentity_t *ed)
gentity_t * G_TempEntity (vec3_t origin, int event)
G_TempEntity spawns an event temporary entity that will be auto-removed.
void G_KillBox (gentity_t *ent)
void G_AddPredictableEvent (gentity_t *ent, int event, int eventParm)
void G_AddEvent (gentity_t *ent, int event, int eventParm)
void G_Sound (gentity_t *ent, int channel, int soundIndex)
void G_SetOrigin (gentity_t *ent, vec3_t origin)
int DebugLine (vec3_t start, vec3_t end, int color)
Variables
int remapCount = 0
shaderRemap_t remappedShaders [MAX_SHADER_REMAPS]
Macro Definition Documentation
MAX_SHADER_REMAPS
#define MAX_SHADER_REMAPS 128
Definition at line 33 of file g_utils.c.
MAXCHOICES
#define MAXCHOICES 32
Definition at line 195 of file g_utils.c.
Function Documentation
AddRemap()
void AddRemap (const char * oldShader, const char * newShader, float timeOffset)
Definition at line 38 of file g_utils.c.
 {
     int i;
     for (i = 0; i < remapCount; i++) {
         if (Q_stricmp(oldShader, remappedShaders[i].oldShader) == 0) {
             // found it, just update this one
             strcpy(remappedShaders[i].newShader, newShader);
             remappedShaders[i].timeOffset = timeOffset;
             return;
         }
     }
     if (remapCount < MAX_SHADER_REMAPS) {
         strcpy(remappedShaders[remapCount].newShader, newShader);
         strcpy(remappedShaders[remapCount].oldShader, oldShader);
         remappedShaders[remapCount].timeOffset = timeOffset;
         remapCount++;
     }
 }
References MAX_SHADER_REMAPS, Q_stricmp(), remapCount, remappedShaders, and shaderRemap_t::timeOffset.
Referenced by G_RemapTeamShaders(), and G_UseTargets().
BuildShaderStateConfig()
const char* BuildShaderStateConfig (void)
Definition at line 58 of file g_utils.c.
 {
     static char    buff[MAX_STRING_CHARS * 4];
     char out[(MAX_QPATH * 2) + 5];
     int i;
     memset(buff, 0, MAX_STRING_CHARS);
     for (i = 0; i < remapCount; i++) {
         Com_sprintf(out, (MAX_QPATH * 2) + 5, "%s=%s:%5.2f@", remappedShaders[i].oldShader, remappedShaders[i].newShader, remappedShaders[i].timeOffset);
         Q_strcat(buff, sizeof(buff), out);
     }
     return buff;
 }
References Com_sprintf(), MAX_QPATH, MAX_STRING_CHARS, Q_strcat(), remapCount, and remappedShaders.
Referenced by G_RemapTeamShaders(), and G_UseTargets().
DebugLine()
int DebugLine (vec3_t start, vec3_t end, int color)
Definition at line 662 of file g_utils.c.
 {
     vec3_t points[4], dir, cross, up = { 0, 0, 1 };
     float dot;
     VectorCopy(start, points[0]);
     VectorCopy(start, points[1]);
     //points[1][2] -= 2;
     VectorCopy(end, points[2]);
     //points[2][2] -= 2;
     VectorCopy(end, points[3]);
     VectorSubtract(end, start, dir);
     VectorNormalize(dir);
     dot = DotProduct(dir, up);
     if (dot > 0.99 || dot < -0.99) VectorSet(cross, 1, 0, 0);
     else CrossProduct(dir, up, cross);
     VectorNormalize(cross);
     VectorMA(points[0], 2, cross, points[0]);
     VectorMA(points[1], -2, cross, points[1]);
     VectorMA(points[2], -2, cross, points[2]);
     VectorMA(points[3], 2, cross, points[3]);
     return trap_DebugPolygonCreate(color, 4, points);
 }
References CrossProduct(), DotProduct, trap_DebugPolygonCreate(), up, VectorCopy, VectorMA, VectorNormalize(), VectorSet, and VectorSubtract.
G_AddEvent()
void G_AddEvent (gentity_t * ent, int event, int eventParm)
Definition at line 593 of file g_utils.c.
 {
     int        bits;
     if (!event) {
         G_Printf("G_AddEvent: zero event added for entity %i\n", ent->s.number);
         return;
     }
     // clients need to add the event in playerState_t instead of entityState_t
     if (ent->client) {
         bits = ent->client->ps.externalEvent & EV_EVENT_BITS;
         bits = (bits + EV_EVENT_BIT1) & EV_EVENT_BITS;
         ent->client->ps.externalEvent = event | bits;
         ent->client->ps.externalEventParm = eventParm;
         ent->client->ps.externalEventTime = level.time;
     } else {
         bits = ent->s.event & EV_EVENT_BITS;
         bits = (bits + EV_EVENT_BIT1) & EV_EVENT_BITS;
         ent->s.event = event | bits;
         ent->s.eventParm = eventParm;
     }
     ent->eventTime = level.time;
 }
References bits(), gentity_s::client, EV_EVENT_BIT1, EV_EVENT_BITS, entityState_s::event, entityState_s::eventParm, gentity_s::eventTime, playerState_s::externalEvent, playerState_s::externalEventParm, playerState_s::externalEventTime, G_Printf(), level, entityState_s::number, gclient_s::ps, gentity_s::s, and level_locals_t::time.
Referenced by CelebrateStart(), CheckGauntletAttack(), ClientTimerActions(), G_Damage(), G_ExplodeMissile(), G_MissileImpact(), G_MoverPush(), GibEntity(), P_DamageFeedback(), P_WorldEffects(), player_die(), Reached_BinaryMover(), RespawnItem(), ReturnToPos1(), Touch_Item(), Use_BinaryMover(), Use_Shooter(), and Use_Target_Speaker().
G_AddPredictableEvent()
void G_AddPredictableEvent (gentity_t * ent, int event, int eventParm)
Definition at line 577 of file g_utils.c.
 {
     if (!ent->client) {
         return;
     }
     BG_AddPredictableEventToPlayerstate(event, eventParm, &ent->client->ps);
 }
References BG_AddPredictableEventToPlayerstate(), gentity_s::client, and gclient_s::ps.
Referenced by Touch_Item().
G_EntitiesFree()
qboolean G_EntitiesFree (void)
Definition at line 449 of file g_utils.c.
 {
     int            i;
     gentity_t* e;
     if (level.num_entities < ENTITYNUM_MAX_NORMAL) {
         // can open a new slot if needed
         return qtrue;
     }
     e = &g_entities[MAX_CLIENTS];
     for (i = MAX_CLIENTS; i < level.num_entities; i++, e++) {
         if (e->inuse) {
             continue;
         }
         // slot available
         return qtrue;
     }
     return qfalse;
 }
References ENTITYNUM_MAX_NORMAL, g_entities, gentity_s::inuse, level, MAX_CLIENTS, level_locals_t::num_entities, qfalse, and qtrue.
G_Find()
gentity_t* G_Find (gentity_t * from, int fieldofs, const char * match)
Definition at line 165 of file g_utils.c.
 {
     char* s;
     if (!from)
         from = g_entities;
     else
         from++;
     for (; from < &g_entities[level.num_entities]; from++) {
         if (!from->inuse)
             continue;
         s = *(char**)((byte*)from + fieldofs);
         if (!s)
             continue;
         if (!Q_stricmp(s, match))
             return from;
     }
     return NULL;
 }
References g_entities, gentity_s::inuse, level, NULL, level_locals_t::num_entities, Q_stricmp(), and s.
Referenced by CheckAlmostCapture(), CheckAlmostScored(), FindIntermissionPoint(), G_CheckTeamItems(), G_PickTarget(), G_UseTargets(), SelectInitialSpawnPoint(), SelectNearestDeathmatchSpawnPoint(), SelectRandomDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), SelectRandomTeamSpawnPoint(), target_laser_start(), Team_FragBonuses(), Team_ResetFlag(), Think_SetupTrainTargets(), and Use_Target_Give().
G_FindConfigstringIndex()
int G_FindConfigstringIndex (char * name, int start, int max, qboolean create)
Definition at line 86 of file g_utils.c.
 {
     int        i;
     char    s[MAX_STRING_CHARS];
     if (!name || !name[0]) {
         return 0;
     }
     for (i = 1; i < max; i++) {
         trap_GetConfigstring(start + i, s, sizeof(s));
         if (!s[0]) {
             break;
         }
         if (!strcmp(s, name)) {
             return i;
         }
     }
     if (!create) {
         return 0;
     }
     if (i == max) {
         G_Error("G_FindConfigstringIndex: overflow");
     }
     trap_SetConfigstring(start + i, name);
     return i;
 }
References G_Error(), MAX_STRING_CHARS, s, trap_GetConfigstring(), and trap_SetConfigstring().
Referenced by G_ModelIndex(), and G_SoundIndex().
G_FreeEntity()
void G_FreeEntity (gentity_t * ed)
Definition at line 478 of file g_utils.c.
 {
     trap_UnlinkEntity(ed);        // unlink from world
     if (ed->neverFree) {
         return;
     }
     memset(ed, 0, sizeof(*ed));
     ed->classname = "freed";
     ed->freetime = level.time;
     ed->inuse = qfalse;
 }
References gentity_s::classname, gentity_s::freetime, gentity_s::inuse, level, gentity_s::neverFree, qfalse, level_locals_t::time, and trap_UnlinkEntity().
Referenced by AimAtTarget(), Blocked_Door(), Cmd_Give_f(), FinishSpawningItem(), G_MoverPush(), G_RunFrame(), G_RunItem(), G_RunMissile(), G_SpawnGEntityFromSpawnVars(), GibEntity(), LaunchItem(), locateCamera(), multi_trigger(), Pickup_Team(), player_die(), SP_func_train(), SP_info_null(), SP_light(), SP_misc_model(), SP_path_corner(), Team_ResetFlag(), trigger_always_think(), and Weapon_HookFree().
G_InitGentity()
void G_InitGentity (gentity_t * e)
Definition at line 374 of file g_utils.c.
 {
     e->inuse = qtrue;
     e->classname = "noclass";
     e->s.number = e - g_entities;
     e->r.ownerNum = ENTITYNUM_NONE;
 }
References gentity_s::classname, ENTITYNUM_NONE, g_entities, gentity_s::inuse, entityState_s::number, entityShared_t::ownerNum, qtrue, gentity_s::r, and gentity_s::s.
Referenced by ClientBegin(), and G_Spawn().
G_KillBox()
void G_KillBox (gentity_t * ent)
Definition at line 542 of file g_utils.c.
 {
     int            i, num;
     int            touch[MAX_GENTITIES];
     gentity_t* hit;
     vec3_t        mins, maxs;
     VectorAdd(ent->client->ps.origin, ent->r.mins, mins);
     VectorAdd(ent->client->ps.origin, ent->r.maxs, maxs);
     num = trap_EntitiesInBox(mins, maxs, touch, MAX_GENTITIES);
     for (i = 0; i < num; i++) {
         hit = &g_entities[touch[i]];
         if (!hit->client) {
             continue;
         }
         // nail it
         G_Damage(hit, ent, ent, NULL, NULL,
             100000, DAMAGE_NO_PROTECTION, MOD_TELEFRAG);
     }
 }
References gentity_s::client, DAMAGE_NO_PROTECTION, G_Damage(), g_entities, MAX_GENTITIES, entityShared_t::maxs, entityShared_t::mins, MOD_TELEFRAG, NULL, playerState_s::origin, gclient_s::ps, gentity_s::r, trap_EntitiesInBox(), and VectorAdd.
Referenced by ClientSpawn(), and TeleportPlayer().
G_ModelIndex()
int G_ModelIndex (char * name)
Definition at line 119 of file g_utils.c.
 {
     return G_FindConfigstringIndex(name, CS_MODELS, MAX_MODELS, qtrue);
 }
References CS_MODELS, G_FindConfigstringIndex(), MAX_MODELS, and qtrue.
Referenced by BotSetEntityNumForGoalWithModel(), G_InitGame(), InitMover(), SP_misc_model(), and SpawnPodium().
G_PickTarget()
gentity_t* G_PickTarget (char * targetname)
Definition at line 197 of file g_utils.c.
 {
     gentity_t* ent = NULL;
     int        num_choices = 0;
     gentity_t* choice[MAXCHOICES];
     if (!targetname) {
         G_Printf("G_PickTarget called with NULL targetname\n");
         return NULL;
     }
     while (1) {
         ent = G_Find(ent, FOFS(targetname), targetname);
         if (!ent)
             break;
         choice[num_choices++] = ent;
         if (num_choices == MAXCHOICES)
             break;
     }
     if (!num_choices) {
         G_Printf("G_PickTarget: target %s not found\n", targetname);
         return NULL;
     }
     return choice[rand() % num_choices];
 }
References FOFS, G_Find(), G_Printf(), MAXCHOICES, and NULL.
Referenced by AimAtTarget(), FindIntermissionPoint(), InitShooter_Finish(), locateCamera(), target_relay_use(), target_teleporter_use(), and trigger_teleporter_touch().
G_SetMovedir()
void G_SetMovedir (vec3_t angles, vec3_t movedir)
Definition at line 333 of file g_utils.c.
 {
     static vec3_t VEC_UP = { 0, -1, 0 };
     static vec3_t MOVEDIR_UP = { 0, 0, 1 };
     static vec3_t VEC_DOWN = { 0, -2, 0 };
     static vec3_t MOVEDIR_DOWN = { 0, 0, -1 };
     if (VectorCompare(angles, VEC_UP)) {
         VectorCopy(MOVEDIR_UP, movedir);
     } else if (VectorCompare(angles, VEC_DOWN)) {
         VectorCopy(MOVEDIR_DOWN, movedir);
     } else {
         AngleVectors(angles, movedir, NULL, NULL);
     }
     VectorClear(angles);
 }
References AngleVectors(), MOVEDIR_DOWN, MOVEDIR_UP, NULL, VEC_DOWN, VEC_UP, VectorClear, VectorCompare(), and VectorCopy.
Referenced by InitShooter(), InitTrigger(), locateCamera(), SP_func_button(), SP_func_door(), SP_target_push(), and target_laser_start().
G_SetOrigin()
void G_SetOrigin (gentity_t * ent, vec3_t origin)
Definition at line 643 of file g_utils.c.
 {
     VectorCopy(origin, ent->s.pos.trBase);
     ent->s.pos.trType = TR_STATIONARY;
     ent->s.pos.trTime = 0;
     ent->s.pos.trDuration = 0;
     VectorClear(ent->s.pos.trDelta);
     VectorCopy(origin, ent->r.currentOrigin);
 }
References entityShared_t::currentOrigin, entityState_s::pos, gentity_s::r, gentity_s::s, TR_STATIONARY, trajectory_t::trBase, trajectory_t::trDelta, trajectory_t::trDuration, trajectory_t::trTime, trajectory_t::trType, VectorClear, and VectorCopy.
Referenced by ClientSpawn(), FinishSpawningItem(), G_BounceItem(), G_BounceMissile(), G_ExplodeMissile(), G_MissileImpact(), G_TempEntity(), LaunchItem(), PodiumPlacementThink(), SP_info_camp(), SP_info_notnull(), SP_misc_model(), SP_target_location(), SP_target_position(), SpawnModelOnVictoryPad(), SpawnPodium(), and Weapon_HookThink().
G_Sound()
void G_Sound (gentity_t * ent, int channel, int soundIndex)
Definition at line 624 of file g_utils.c.
 {
     gentity_t* te;
     te = G_TempEntity(ent->r.currentOrigin, EV_GENERAL_SOUND);
     te->s.eventParm = soundIndex;
 }
References entityShared_t::currentOrigin, EV_GENERAL_SOUND, entityState_s::eventParm, G_TempEntity(), gentity_s::r, and gentity_s::s.
Referenced by hurt_touch(), and Use_target_push().
G_SoundIndex()
int G_SoundIndex (char * name)
Definition at line 124 of file g_utils.c.
 {
     return G_FindConfigstringIndex(name, CS_SOUNDS, MAX_SOUNDS, qtrue);
 }
References CS_SOUNDS, G_FindConfigstringIndex(), MAX_SOUNDS, and qtrue.
Referenced by G_InitGame(), G_SetClientSound(), G_SpawnItem(), InitMover(), RespawnItem(), SP_func_button(), SP_func_door(), SP_func_plat(), SP_target_push(), SP_target_speaker(), SP_trigger_hurt(), SP_trigger_push(), and SP_trigger_teleport().
G_Spawn()
gentity_t* G_Spawn (void)
Definition at line 397 of file g_utils.c.
 {
     int            i, force;
     gentity_t* e;
     e = NULL;    // shut up warning
     for (force = 0; force < 2; force++) {
         // if we go through all entities and can't find one to free,
         // override the normal minimum times before use
         e = &g_entities[MAX_CLIENTS];
         for (i = MAX_CLIENTS; i < level.num_entities; i++, e++) {
             if (e->inuse) {
                 continue;
             }
             // the first couple seconds of server time can involve a lot of
             // freeing and allocating, so relax the replacement policy
             if (!force && e->freetime > level.startTime + 2000 && level.time - e->freetime < 1000) {
                 continue;
             }
             // reuse this slot
             G_InitGentity(e);
             return e;
         }
         if (level.num_entities < ENTITYNUM_MAX_NORMAL) {
             break;
         }
     }
     if (level.num_entities == ENTITYNUM_MAX_NORMAL) {
         for (i = 0; i < MAX_GENTITIES; i++) {
             G_Printf("%4i: %s\n", i, g_entities[i].classname);
         }
         G_Error("G_Spawn: no free entities");
     }
     // open up a new slot
     level.num_entities++;
     // let the server system know that there are more entities
     trap_LocateGameData(level.gentities, level.num_entities, sizeof(gentity_t),
         &level.clients[0].ps, sizeof(level.clients[0]));
     G_InitGentity(e);
     return e;
 }
References level_locals_t::clients, ENTITYNUM_MAX_NORMAL, gentity_s::freetime, g_entities, G_Error(), G_InitGentity(), G_Printf(), level_locals_t::gentities, gentity_s::inuse, level, MAX_CLIENTS, MAX_GENTITIES, NULL, level_locals_t::num_entities, gclient_s::ps, level_locals_t::startTime, level_locals_t::time, and trap_LocateGameData().
Referenced by Cmd_Give_f(), fire_bfg(), fire_grapple(), fire_grenade(), fire_plasma(), fire_rocket(), G_MissileImpact(), G_SpawnGEntityFromSpawnVars(), G_TempEntity(), InitBodyQue(), LaunchItem(), SpawnModelOnVictoryPad(), SpawnPlatTrigger(), SpawnPodium(), and Think_SpawnNewDoorTrigger().
G_TeamCommand()
void G_TeamCommand (team_t team, char * cmd)
Definition at line 139 of file g_utils.c.
 {
     int        i;
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected == CON_CONNECTED) {
             if (level.clients[i].sess.sessionTeam == team) {
                 trap_SendServerCommand(i, va("%s", cmd));
             }
         }
     }
 }
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, level, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, trap_SendServerCommand(), and va().
Referenced by Use_Target_Print().
G_TempEntity()
gentity_t* G_TempEntity (vec3_t origin, int event)
G_TempEntity spawns an event temporary entity that will be auto-removed.
The origin will be snapped to save net bandwidth, so care must be taken if the origin is right on a surface (snap towards start vector first).
Parameters
origin
event
Returns
The event temporary entity.
Definition at line 502 of file g_utils.c.
 {
     gentity_t* e;
     vec3_t      snapped;
     e = G_Spawn();
     e->s.eType = ET_EVENTS + event;
     e->classname = "tempEntity";
     e->eventTime = level.time;
     e->freeAfterEvent = qtrue;
     VectorCopy(origin, snapped);
     SnapVector(snapped);        // save network bandwidth
     G_SetOrigin(e, snapped);
     // find cluster for PVS
     trap_LinkEntity(e);
     return e;
 }
References gentity_s::classname, ET_EVENTS, entityState_s::eType, gentity_s::eventTime, gentity_s::freeAfterEvent, G_SetOrigin(), G_Spawn(), level, qtrue, gentity_s::s, SnapVector, level_locals_t::time, trap_LinkEntity(), and VectorCopy.
Referenced by AddTeamScore(), Blocked_Door(), Bullet_Fire(), CheckGauntletAttack(), ClientDisconnect(), ClientSpawn(), G_Sound(), player_die(), RespawnItem(), ScorePlum(), SendPendingPredictableEvents(), Team_CaptureFlagSound(), Team_ReturnFlagSound(), Team_TakeFlagSound(), TeleportPlayer(), Touch_Item(), Weapon_LightningFire(), weapon_railgun_fire(), and weapon_supershotgun_fire().
G_UseTargets()
void G_UseTargets (gentity_t * ent, gentity_t * activator)
Definition at line 237 of file g_utils.c.
 {
     gentity_t* t;
     if (!ent) {
         return;
     }
     if (ent->targetShaderName && ent->targetShaderNewName) {
         float f = level.time * 0.001;
         AddRemap(ent->targetShaderName, ent->targetShaderNewName, f);
         trap_SetConfigstring(CS_SHADERSTATE, BuildShaderStateConfig());
     }
     if (!ent->target) {
         return;
     }
     t = NULL;
     while ((t = G_Find(t, FOFS(targetname), ent->target)) != NULL) {
         if (t == ent) {
             G_Printf("WARNING: Entity used itself.\n");
         } else {
             if (t->use) {
                 t->use(t, ent, activator);
             }
         }
         if (!ent->inuse) {
             G_Printf("entity was removed while using targets\n");
             return;
         }
     }
 }
References AddRemap(), BuildShaderStateConfig(), CS_SHADERSTATE, FOFS, G_Find(), G_Printf(), gentity_s::inuse, level, NULL, t, gentity_s::target, gentity_s::targetShaderName, gentity_s::targetShaderNewName, level_locals_t::time, and trap_SetConfigstring().
Referenced by ClientSpawn(), func_timer_think(), multi_trigger(), Reached_BinaryMover(), Reached_Train(), target_relay_use(), Think_Target_Delay(), Touch_Item(), and trigger_always_think().
tv()
float* tv (float x, float y, float z)
Definition at line 280 of file g_utils.c.
 {
     static    int        index;
     static    vec3_t    vecs[8];
     float* v;
     // use an array so that multiple tempvectors won't collide
     // for a while
     v = vecs[index];
     index = (index + 1) & 7;
     v[0] = x;
     v[1] = y;
     v[2] = z;
     return v;
 }
Referenced by GetTickCount(), and Touch_DoorTriggerSpectator().
vectoyaw()
float vectoyaw (const vec3_t vec)
Definition at line 351 of file g_utils.c.
 {
     float    yaw;
     if (vec[YAW] == 0 && vec[PITCH] == 0) {
         yaw = 0;
     } else {
         if (vec[PITCH]) {
             yaw = (atan2(vec[YAW], vec[PITCH]) * 180 / M_PI);
         } else if (vec[YAW] > 0) {
             yaw = 90;
         } else {
             yaw = 270;
         }
         if (yaw < 0) {
             yaw += 360;
         }
     }
     return yaw;
 }
References M_PI, PITCH, and YAW.
Referenced by LookAtKiller(), and SpawnPodium().
vtos()
char* vtos (const vec3_t v)
Definition at line 307 of file g_utils.c.
 {
     static    int        index;
     static    char    str[8][32];
     char* s;
     // use an array so that multiple vtos won't collide
     s = str[index];
     index = (index + 1) & 7;
     Com_sprintf(s, 32, "(%i %i %i)", (int)v[0], (int)v[1], (int)v[2]);
     return s;
 }
References Com_sprintf(), and s.
Referenced by Cmd_Where_f(), FinishSpawningItem(), SP_func_timer(), SP_func_train(), SP_path_corner(), SP_target_speaker(), SP_target_teleporter(), target_laser_start(), and Think_SetupTrainTargets().
Variable Documentation
remapCount
int remapCount = 0
Definition at line 35 of file g_utils.c.
Referenced by AddRemap(), and BuildShaderStateConfig().
remappedShaders
shaderRemap_t remappedShaders[MAX_SHADER_REMAPS]
Definition at line 36 of file g_utils.c.
Referenced by AddRemap(), and BuildShaderStateConfig().