ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_display.c File Reference
ui_display.c File Reference
#include "ui_local.h"
Classes
struct displayOptionsInfo_t
Macros
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ID_GRAPHICS 10
#define ID_DISPLAY 11
#define ID_SOUND 12
#define ID_NETWORK 13
#define ID_BRIGHTNESS 14
#define ID_SCREENSIZE 15
#define ID_BACK 16
Functions
static void UI_DisplayOptionsMenu_Event (void *ptr, int event)
static void UI_DisplayOptionsMenu_Init (void)
void UI_DisplayOptionsMenu_Cache (void)
void UI_DisplayOptionsMenu (void)
Variables
static displayOptionsInfo_t displayOptionsInfo
Macro Definition Documentation
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 36 of file ui_display.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 37 of file ui_display.c.
ART_FRAMEL
#define ART_FRAMEL "menu/art/frame2_l"
Definition at line 34 of file ui_display.c.
ART_FRAMER
#define ART_FRAMER "menu/art/frame1_r"
Definition at line 35 of file ui_display.c.
ID_BACK
#define ID_BACK 16
Definition at line 45 of file ui_display.c.
ID_BRIGHTNESS
#define ID_BRIGHTNESS 14
Definition at line 43 of file ui_display.c.
ID_DISPLAY
#define ID_DISPLAY 11
Definition at line 40 of file ui_display.c.
ID_GRAPHICS
#define ID_GRAPHICS 10
Definition at line 39 of file ui_display.c.
ID_NETWORK
#define ID_NETWORK 13
Definition at line 42 of file ui_display.c.
ID_SCREENSIZE
#define ID_SCREENSIZE 15
Definition at line 44 of file ui_display.c.
ID_SOUND
#define ID_SOUND 12
Definition at line 41 of file ui_display.c.
Function Documentation
UI_DisplayOptionsMenu()
void UI_DisplayOptionsMenu (void)
Definition at line 261 of file ui_display.c.
{
     UI_DisplayOptionsMenu_Init();
     UI_PushMenu( &displayOptionsInfo.menu );
     Menu_SetCursorToItem( &displayOptionsInfo.menu, &displayOptionsInfo.display );
 }
Referenced by GraphicsOptions_Event(), Options_Event(), UI_NetworkOptionsMenu_Event(), and UI_SoundOptionsMenu_Event().
UI_DisplayOptionsMenu_Cache()
void UI_DisplayOptionsMenu_Cache (void)
Definition at line 248 of file ui_display.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
 }
Referenced by UI_Cache_f(), and UI_DisplayOptionsMenu_Init().
UI_DisplayOptionsMenu_Event()
static void UI_DisplayOptionsMenu_Event (void * ptr, int event) static
Definition at line 74 of file ui_display.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch( ((menucommon_s*)ptr)->id ) {
     case ID_GRAPHICS:
         UI_PopMenu();
         UI_GraphicsOptionsMenu();
         break;
     case ID_DISPLAY:
         break;
     case ID_SOUND:
         UI_PopMenu();
         UI_SoundOptionsMenu();
         break;
     case ID_NETWORK:
         UI_PopMenu();
         UI_NetworkOptionsMenu();
         break;
     case ID_BRIGHTNESS:
         trap_Cvar_SetValue( "r_gamma", displayOptionsInfo.brightness.curvalue / 10.0f );
         break;
     case ID_SCREENSIZE:
         trap_Cvar_SetValue( "cg_viewsize", displayOptionsInfo.screensize.curvalue * 10 );
         break;
     case ID_BACK:
         UI_PopMenu();
         break;
     }
 }
Referenced by UI_DisplayOptionsMenu_Init().
UI_DisplayOptionsMenu_Init()
static void UI_DisplayOptionsMenu_Init (void) static
Definition at line 118 of file ui_display.c.
{
     int     y;
     memset( &displayOptionsInfo, 0, sizeof(displayOptionsInfo) );
     UI_DisplayOptionsMenu_Cache();
     displayOptionsInfo.menu.wrapAround = qtrue;
     displayOptionsInfo.menu.fullscreen = qtrue;
     displayOptionsInfo.banner.generic.type      = MTYPE_BTEXT;
     displayOptionsInfo.banner.generic.flags     = QMF_CENTER_JUSTIFY;
     displayOptionsInfo.banner.generic.x         = 320;
     displayOptionsInfo.banner.generic.y         = 16;
     displayOptionsInfo.banner.string            = "SYSTEM SETUP";
     displayOptionsInfo.banner.color             = color_white;
     displayOptionsInfo.banner.style             = UI_CENTER;
     displayOptionsInfo.framel.generic.type      = MTYPE_BITMAP;
     displayOptionsInfo.framel.generic.name      = ART_FRAMEL;
     displayOptionsInfo.framel.generic.flags     = QMF_INACTIVE;
     displayOptionsInfo.framel.generic.x         = 0;
     displayOptionsInfo.framel.generic.y         = 78;
     displayOptionsInfo.framel.width             = 256;
     displayOptionsInfo.framel.height            = 329;
     displayOptionsInfo.framer.generic.type      = MTYPE_BITMAP;
     displayOptionsInfo.framer.generic.name      = ART_FRAMER;
     displayOptionsInfo.framer.generic.flags     = QMF_INACTIVE;
     displayOptionsInfo.framer.generic.x         = 376;
     displayOptionsInfo.framer.generic.y         = 76;
     displayOptionsInfo.framer.width             = 256;
     displayOptionsInfo.framer.height            = 334;
     displayOptionsInfo.graphics.generic.type        = MTYPE_PTEXT;
     displayOptionsInfo.graphics.generic.flags       = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     displayOptionsInfo.graphics.generic.id          = ID_GRAPHICS;
     displayOptionsInfo.graphics.generic.callback    = UI_DisplayOptionsMenu_Event;
     displayOptionsInfo.graphics.generic.x           = 216;
     displayOptionsInfo.graphics.generic.y           = 240 - 2 * PROP_HEIGHT;
     displayOptionsInfo.graphics.string              = "GRAPHICS";
     displayOptionsInfo.graphics.style               = UI_RIGHT;
     displayOptionsInfo.graphics.color               = color_red;
     displayOptionsInfo.display.generic.type         = MTYPE_PTEXT;
     displayOptionsInfo.display.generic.flags        = QMF_RIGHT_JUSTIFY;
     displayOptionsInfo.display.generic.id           = ID_DISPLAY;
     displayOptionsInfo.display.generic.callback     = UI_DisplayOptionsMenu_Event;
     displayOptionsInfo.display.generic.x            = 216;
     displayOptionsInfo.display.generic.y            = 240 - PROP_HEIGHT;
     displayOptionsInfo.display.string               = "DISPLAY";
     displayOptionsInfo.display.style                = UI_RIGHT;
     displayOptionsInfo.display.color                = color_red;
     displayOptionsInfo.sound.generic.type           = MTYPE_PTEXT;
     displayOptionsInfo.sound.generic.flags          = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     displayOptionsInfo.sound.generic.id             = ID_SOUND;
     displayOptionsInfo.sound.generic.callback       = UI_DisplayOptionsMenu_Event;
     displayOptionsInfo.sound.generic.x              = 216;
     displayOptionsInfo.sound.generic.y              = 240;
     displayOptionsInfo.sound.string                 = "SOUND";
     displayOptionsInfo.sound.style                  = UI_RIGHT;
     displayOptionsInfo.sound.color                  = color_red;
     displayOptionsInfo.network.generic.type         = MTYPE_PTEXT;
     displayOptionsInfo.network.generic.flags        = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     displayOptionsInfo.network.generic.id           = ID_NETWORK;
     displayOptionsInfo.network.generic.callback     = UI_DisplayOptionsMenu_Event;
     displayOptionsInfo.network.generic.x            = 216;
     displayOptionsInfo.network.generic.y            = 240 + PROP_HEIGHT;
     displayOptionsInfo.network.string               = "NETWORK";
     displayOptionsInfo.network.style                = UI_RIGHT;
     displayOptionsInfo.network.color                = color_red;
     y = 240 - 1 * (BIGCHAR_HEIGHT+2);
     displayOptionsInfo.brightness.generic.type      = MTYPE_SLIDER;
     displayOptionsInfo.brightness.generic.name      = "Brightness:";
     displayOptionsInfo.brightness.generic.flags     = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     displayOptionsInfo.brightness.generic.callback  = UI_DisplayOptionsMenu_Event;
     displayOptionsInfo.brightness.generic.id        = ID_BRIGHTNESS;
     displayOptionsInfo.brightness.generic.x         = 400;
     displayOptionsInfo.brightness.generic.y         = y;
     displayOptionsInfo.brightness.minvalue          = 5;
     displayOptionsInfo.brightness.maxvalue          = 20;
     if( !uis.glconfig.deviceSupportsGamma ) {
         displayOptionsInfo.brightness.generic.flags |= QMF_GRAYED;
     }
     y += BIGCHAR_HEIGHT+2;
     displayOptionsInfo.screensize.generic.type      = MTYPE_SLIDER;
     displayOptionsInfo.screensize.generic.name      = "Screen Size:";
     displayOptionsInfo.screensize.generic.flags     = QMF_PULSEIFFOCUS|QMF_SMALLFONT;
     displayOptionsInfo.screensize.generic.callback  = UI_DisplayOptionsMenu_Event;
     displayOptionsInfo.screensize.generic.id        = ID_SCREENSIZE;
     displayOptionsInfo.screensize.generic.x         = 400;
     displayOptionsInfo.screensize.generic.y         = y;
     displayOptionsInfo.screensize.minvalue          = 3;
     displayOptionsInfo.screensize.maxvalue          = 10;
     displayOptionsInfo.back.generic.type        = MTYPE_BITMAP;
     displayOptionsInfo.back.generic.name        = ART_BACK0;
     displayOptionsInfo.back.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     displayOptionsInfo.back.generic.callback    = UI_DisplayOptionsMenu_Event;
     displayOptionsInfo.back.generic.id          = ID_BACK;
     displayOptionsInfo.back.generic.x           = 0;
     displayOptionsInfo.back.generic.y           = 480-64;
     displayOptionsInfo.back.width               = 128;
     displayOptionsInfo.back.height              = 64;
     displayOptionsInfo.back.focuspic            = ART_BACK1;
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.banner );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.framel );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.framer );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.graphics );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.display );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.sound );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.network );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.brightness );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.screensize );
     Menu_AddItem( &displayOptionsInfo.menu, ( void * ) &displayOptionsInfo.back );
     displayOptionsInfo.brightness.curvalue  = trap_Cvar_VariableValue("r_gamma") * 10;
     displayOptionsInfo.screensize.curvalue  = trap_Cvar_VariableValue( "cg_viewsize")/10;
 }
Referenced by UI_DisplayOptionsMenu().
Variable Documentation
displayOptionsInfo
displayOptionsInfo_t displayOptionsInfo static
Definition at line 66 of file ui_display.c.
Referenced by UI_DisplayOptionsMenu(), UI_DisplayOptionsMenu_Event(), and UI_DisplayOptionsMenu_Init().