ioquake3 doxygen: ai_export_s Struct Reference
ai_export_s Struct Reference
#include <botlib.h>
Public Attributes
int(* BotLoadCharacter)(char *charfile, float skill)
void(* BotFreeCharacter)(int character)
float(* Characteristic_Float)(int character, int index)
float(* Characteristic_BFloat)(int character, int index, float min, float max)
int(* Characteristic_Integer)(int character, int index)
int(* Characteristic_BInteger)(int character, int index, int min, int max)
void(* Characteristic_String)(int character, int index, char *buf, int size)
int(* BotAllocChatState)(void)
void(* BotFreeChatState)(int handle)
void(* BotQueueConsoleMessage)(int chatstate, int type, char *message)
void(* BotRemoveConsoleMessage)(int chatstate, int handle)
int(* BotNextConsoleMessage)(int chatstate, struct bot_consolemessage_s *cm)
int(* BotNumConsoleMessages)(int chatstate)
void(* BotInitialChat)(int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int(* BotNumInitialChats)(int chatstate, char *type)
int(* BotReplyChat)(int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int(* BotChatLength)(int chatstate)
void(* BotEnterChat)(int chatstate, int client, int sendto)
void(* BotGetChatMessage)(int chatstate, char *buf, int size)
int(* StringContains)(char *str1, char *str2, int casesensitive)
int(* BotFindMatch)(char *str, struct bot_match_s *match, unsigned long int context)
void(* BotMatchVariable)(struct bot_match_s *match, int variable, char *buf, int size)
void(* UnifyWhiteSpaces)(char *string)
void(* BotReplaceSynonyms)(char *string, unsigned long int context)
int(* BotLoadChatFile)(int chatstate, char *chatfile, char *chatname)
void(* BotSetChatGender)(int chatstate, int gender)
void(* BotSetChatName)(int chatstate, char *name, int client)
void(* BotResetGoalState)(int goalstate)
void(* BotResetAvoidGoals)(int goalstate)
void(* BotRemoveFromAvoidGoals)(int goalstate, int number)
void(* BotPushGoal)(int goalstate, struct bot_goal_s *goal)
void(* BotPopGoal)(int goalstate)
void(* BotEmptyGoalStack)(int goalstate)
void(* BotDumpAvoidGoals)(int goalstate)
void(* BotDumpGoalStack)(int goalstate)
void(* BotGoalName)(int number, char *name, int size)
int(* BotGetTopGoal)(int goalstate, struct bot_goal_s *goal)
int(* BotGetSecondGoal)(int goalstate, struct bot_goal_s *goal)
int(* BotChooseLTGItem)(int goalstate, vec3_t origin, int *inventory, int travelflags)
int(* BotChooseNBGItem)(int goalstate, vec3_t origin, int *inventory, int travelflags, struct bot_goal_s *ltg, float maxtime)
int(* BotTouchingGoal)(vec3_t origin, struct bot_goal_s *goal)
int(* BotItemGoalInVisButNotVisible)(int viewer, vec3_t eye, vec3_t viewangles, struct bot_goal_s *goal)
int(* BotGetLevelItemGoal)(int index, char *classname, struct bot_goal_s *goal)
int(* BotGetNextCampSpotGoal)(int num, struct bot_goal_s *goal)
int(* BotGetMapLocationGoal)(char *name, struct bot_goal_s *goal)
float(* BotAvoidGoalTime)(int goalstate, int number)
void(* BotSetAvoidGoalTime)(int goalstate, int number, float avoidtime)
void(* BotInitLevelItems)(void)
void(* BotUpdateEntityItems)(void)
int(* BotLoadItemWeights)(int goalstate, char *filename)
void(* BotFreeItemWeights)(int goalstate)
void(* BotInterbreedGoalFuzzyLogic)(int parent1, int parent2, int child)
void(* BotSaveGoalFuzzyLogic)(int goalstate, char *filename)
void(* BotMutateGoalFuzzyLogic)(int goalstate, float range)
int(* BotAllocGoalState)(int client)
void(* BotFreeGoalState)(int handle)
void(* BotResetMoveState)(int movestate)
void(* BotMoveToGoal)(struct bot_moveresult_s *result, int movestate, struct bot_goal_s *goal, int travelflags)
int(* BotMoveInDirection)(int movestate, vec3_t dir, float speed, int type)
void(* BotResetAvoidReach)(int movestate)
void(* BotResetLastAvoidReach)(int movestate)
int(* BotReachabilityArea)(vec3_t origin, int testground)
int(* BotMovementViewTarget)(int movestate, struct bot_goal_s *goal, int travelflags, float lookahead, vec3_t target)
int(* BotPredictVisiblePosition)(vec3_t origin, int areanum, struct bot_goal_s *goal, int travelflags, vec3_t target)
int(* BotAllocMoveState)(void)
void(* BotFreeMoveState)(int handle)
void(* BotInitMoveState)(int handle, struct bot_initmove_s *initmove)
void(* BotAddAvoidSpot)(int movestate, vec3_t origin, float radius, int type)
int(* BotChooseBestFightWeapon)(int weaponstate, int *inventory)
void(* BotGetWeaponInfo)(int weaponstate, int weapon, struct weaponinfo_s *weaponinfo)
int(* BotLoadWeaponWeights)(int weaponstate, char *filename)
int(* BotAllocWeaponState)(void)
void(* BotFreeWeaponState)(int weaponstate)
void(* BotResetWeaponState)(int weaponstate)
int(* GeneticParentsAndChildSelection)(int numranks, float *ranks, int *parent1, int *parent2, int *child)
Detailed Description
Definition at line 300 of file botlib.h.
Member Data Documentation
BotAddAvoidSpot
void(* ai_export_s::BotAddAvoidSpot) (int movestate, vec3_t origin, float radius, int type)
Definition at line 382 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotAllocChatState
int(* ai_export_s::BotAllocChatState) (void)
Definition at line 315 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotAllocGoalState
int(* ai_export_s::BotAllocGoalState) (int client)
Definition at line 366 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotAllocMoveState
int(* ai_export_s::BotAllocMoveState) (void)
Definition at line 379 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotAllocWeaponState
int(* ai_export_s::BotAllocWeaponState) (void)
Definition at line 389 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotAvoidGoalTime
float(* ai_export_s::BotAvoidGoalTime) (int goalstate, int number)
Definition at line 357 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotChatLength
int(* ai_export_s::BotChatLength) (int chatstate)
Definition at line 324 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotChooseBestFightWeapon
int(* ai_export_s::BotChooseBestFightWeapon) (int weaponstate, int *inventory)
Definition at line 386 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotChooseLTGItem
int(* ai_export_s::BotChooseLTGItem) (int goalstate, vec3_t origin, int *inventory, int travelflags)
Definition at line 349 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotChooseNBGItem
int(* ai_export_s::BotChooseNBGItem) (int goalstate, vec3_t origin, int *inventory, int travelflags, struct bot_goal_s *ltg, float maxtime)
Definition at line 350 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotDumpAvoidGoals
void(* ai_export_s::BotDumpAvoidGoals) (int goalstate)
Definition at line 344 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotDumpGoalStack
void(* ai_export_s::BotDumpGoalStack) (int goalstate)
Definition at line 345 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotEmptyGoalStack
void(* ai_export_s::BotEmptyGoalStack) (int goalstate)
Definition at line 343 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotEnterChat
void(* ai_export_s::BotEnterChat) (int chatstate, int client, int sendto)
Definition at line 325 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotFindMatch
int(* ai_export_s::BotFindMatch) (char *str, struct bot_match_s *match, unsigned long int context)
Definition at line 328 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotFreeCharacter
void(* ai_export_s::BotFreeCharacter) (int character)
Definition at line 306 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotFreeChatState
void(* ai_export_s::BotFreeChatState) (int handle)
Definition at line 316 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotFreeGoalState
void(* ai_export_s::BotFreeGoalState) (int handle)
Definition at line 367 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotFreeItemWeights
void(* ai_export_s::BotFreeItemWeights) (int goalstate)
Definition at line 362 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotFreeMoveState
void(* ai_export_s::BotFreeMoveState) (int handle)
Definition at line 380 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotFreeWeaponState
void(* ai_export_s::BotFreeWeaponState) (int weaponstate)
Definition at line 390 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGetChatMessage
void(* ai_export_s::BotGetChatMessage) (int chatstate, char *buf, int size)
Definition at line 326 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGetLevelItemGoal
int(* ai_export_s::BotGetLevelItemGoal) (int index, char *classname, struct bot_goal_s *goal)
Definition at line 354 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGetMapLocationGoal
int(* ai_export_s::BotGetMapLocationGoal) (char *name, struct bot_goal_s *goal)
Definition at line 356 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGetNextCampSpotGoal
int(* ai_export_s::BotGetNextCampSpotGoal) (int num, struct bot_goal_s *goal)
Definition at line 355 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGetSecondGoal
int(* ai_export_s::BotGetSecondGoal) (int goalstate, struct bot_goal_s *goal)
Definition at line 348 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGetTopGoal
int(* ai_export_s::BotGetTopGoal) (int goalstate, struct bot_goal_s *goal)
Definition at line 347 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGetWeaponInfo
void(* ai_export_s::BotGetWeaponInfo) (int weaponstate, int weapon, struct weaponinfo_s *weaponinfo)
Definition at line 387 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotGoalName
void(* ai_export_s::BotGoalName) (int number, char *name, int size)
Definition at line 346 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotInitialChat
void(* ai_export_s::BotInitialChat) (int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
Definition at line 321 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotInitLevelItems
void(* ai_export_s::BotInitLevelItems) (void)
Definition at line 359 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotInitMoveState
void(* ai_export_s::BotInitMoveState) (int handle, struct bot_initmove_s *initmove)
Definition at line 381 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotInterbreedGoalFuzzyLogic
void(* ai_export_s::BotInterbreedGoalFuzzyLogic) (int parent1, int parent2, int child)
Definition at line 363 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotItemGoalInVisButNotVisible
int(* ai_export_s::BotItemGoalInVisButNotVisible) (int viewer, vec3_t eye, vec3_t viewangles, struct bot_goal_s *goal)
Definition at line 353 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotLoadCharacter
int(* ai_export_s::BotLoadCharacter) (char *charfile, float skill)
Definition at line 305 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotLoadChatFile
int(* ai_export_s::BotLoadChatFile) (int chatstate, char *chatfile, char *chatname)
Definition at line 332 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotLoadItemWeights
int(* ai_export_s::BotLoadItemWeights) (int goalstate, char *filename)
Definition at line 361 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotLoadWeaponWeights
int(* ai_export_s::BotLoadWeaponWeights) (int weaponstate, char *filename)
Definition at line 388 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotMatchVariable
void(* ai_export_s::BotMatchVariable) (struct bot_match_s *match, int variable, char *buf, int size)
Definition at line 329 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotMoveInDirection
int(* ai_export_s::BotMoveInDirection) (int movestate, vec3_t dir, float speed, int type)
Definition at line 373 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotMovementViewTarget
int(* ai_export_s::BotMovementViewTarget) (int movestate, struct bot_goal_s *goal, int travelflags, float lookahead, vec3_t target)
Definition at line 377 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotMoveToGoal
void(* ai_export_s::BotMoveToGoal) (struct bot_moveresult_s *result, int movestate, struct bot_goal_s *goal, int travelflags)
Definition at line 372 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotMutateGoalFuzzyLogic
void(* ai_export_s::BotMutateGoalFuzzyLogic) (int goalstate, float range)
Definition at line 365 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotNextConsoleMessage
int(* ai_export_s::BotNextConsoleMessage) (int chatstate, struct bot_consolemessage_s *cm)
Definition at line 319 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotNumConsoleMessages
int(* ai_export_s::BotNumConsoleMessages) (int chatstate)
Definition at line 320 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotNumInitialChats
int(* ai_export_s::BotNumInitialChats) (int chatstate, char *type)
Definition at line 322 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotPopGoal
void(* ai_export_s::BotPopGoal) (int goalstate)
Definition at line 342 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotPredictVisiblePosition
int(* ai_export_s::BotPredictVisiblePosition) (vec3_t origin, int areanum, struct bot_goal_s *goal, int travelflags, vec3_t target)
Definition at line 378 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotPushGoal
void(* ai_export_s::BotPushGoal) (int goalstate, struct bot_goal_s *goal)
Definition at line 341 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotQueueConsoleMessage
void(* ai_export_s::BotQueueConsoleMessage) (int chatstate, int type, char *message)
Definition at line 317 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotReachabilityArea
int(* ai_export_s::BotReachabilityArea) (vec3_t origin, int testground)
Definition at line 376 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotRemoveConsoleMessage
void(* ai_export_s::BotRemoveConsoleMessage) (int chatstate, int handle)
Definition at line 318 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotRemoveFromAvoidGoals
void(* ai_export_s::BotRemoveFromAvoidGoals) (int goalstate, int number)
Definition at line 340 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotReplaceSynonyms
void(* ai_export_s::BotReplaceSynonyms) (char *string, unsigned long int context)
Definition at line 331 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotReplyChat
int(* ai_export_s::BotReplyChat) (int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
Definition at line 323 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotResetAvoidGoals
void(* ai_export_s::BotResetAvoidGoals) (int goalstate)
Definition at line 339 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotResetAvoidReach
void(* ai_export_s::BotResetAvoidReach) (int movestate)
Definition at line 374 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotResetGoalState
void(* ai_export_s::BotResetGoalState) (int goalstate)
Definition at line 338 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotResetLastAvoidReach
void(* ai_export_s::BotResetLastAvoidReach) (int movestate)
Definition at line 375 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotResetMoveState
void(* ai_export_s::BotResetMoveState) (int movestate)
Definition at line 371 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotResetWeaponState
void(* ai_export_s::BotResetWeaponState) (int weaponstate)
Definition at line 391 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotSaveGoalFuzzyLogic
void(* ai_export_s::BotSaveGoalFuzzyLogic) (int goalstate, char *filename)
Definition at line 364 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotSetAvoidGoalTime
void(* ai_export_s::BotSetAvoidGoalTime) (int goalstate, int number, float avoidtime)
Definition at line 358 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotSetChatGender
void(* ai_export_s::BotSetChatGender) (int chatstate, int gender)
Definition at line 333 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotSetChatName
void(* ai_export_s::BotSetChatName) (int chatstate, char *name, int client)
Definition at line 334 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotTouchingGoal
int(* ai_export_s::BotTouchingGoal) (vec3_t origin, struct bot_goal_s *goal)
Definition at line 352 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
BotUpdateEntityItems
void(* ai_export_s::BotUpdateEntityItems) (void)
Definition at line 360 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
Characteristic_BFloat
float(* ai_export_s::Characteristic_BFloat) (int character, int index, float min, float max)
Definition at line 308 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
Characteristic_BInteger
int(* ai_export_s::Characteristic_BInteger) (int character, int index, int min, int max)
Definition at line 310 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
Characteristic_Float
float(* ai_export_s::Characteristic_Float) (int character, int index)
Definition at line 307 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
Characteristic_Integer
int(* ai_export_s::Characteristic_Integer) (int character, int index)
Definition at line 309 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
Characteristic_String
void(* ai_export_s::Characteristic_String) (int character, int index, char *buf, int size)
Definition at line 311 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
GeneticParentsAndChildSelection
int(* ai_export_s::GeneticParentsAndChildSelection) (int numranks, float *ranks, int *parent1, int *parent2, int *child)
Definition at line 395 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
StringContains
int(* ai_export_s::StringContains) (char *str1, char *str2, int casesensitive)
Definition at line 327 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().
UnifyWhiteSpaces
void(* ai_export_s::UnifyWhiteSpaces) (char *string)
Definition at line 330 of file botlib.h.
Referenced by Init_AI_Export(), and SV_GameSystemCalls().