ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/net_chan.c File Reference
net_chan.c File Reference
#include "q_shared.h"
#include "qcommon.h"
Classes
struct loopmsg_t
struct loopback_t
struct packetQueue_s
Macros
#define MAX_PACKETLEN 1400
#define FRAGMENT_SIZE (MAX_PACKETLEN - 100)
#define PACKET_HEADER 10
#define FRAGMENT_BIT (1U<<31)
#define MAX_LOOPBACK 16
Typedefs
typedef struct packetQueue_s packetQueue_t
Functions
void Netchan_Init (int port)
void Netchan_Setup (netsrc_t sock, netchan_t *chan, netadr_t adr, int qport, int challenge, qboolean compat)
void Netchan_TransmitNextFragment (netchan_t *chan)
void Netchan_Transmit (netchan_t *chan, int length, const byte *data)
qboolean Netchan_Process (netchan_t *chan, msg_t *msg)
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t *net_from, msg_t *net_message)
void NET_SendLoopPacket (netsrc_t sock, int length, const void *data, netadr_t to)
static void NET_QueuePacket (int length, const void *data, netadr_t to, int offset)
void NET_FlushPacketQueue (void)
void NET_SendPacket (netsrc_t sock, int length, const void *data, netadr_t to)
void QDECL NET_OutOfBandPrint (netsrc_t sock, netadr_t adr, const char *format,...)
void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, byte *format, int len)
int NET_StringToAdr (const char *s, netadr_t *a, netadrtype_t family)
Variables
cvar_t * showpackets
cvar_t * showdrop
cvar_t * qport
static char * netsrcString [2]
loopback_t loopbacks [2]
packetQueue_t * packetQueue = NULL
Macro Definition Documentation
FRAGMENT_BIT
#define FRAGMENT_BIT (1U<<31)
Definition at line 55 of file net_chan.c.
FRAGMENT_SIZE
#define FRAGMENT_SIZE (MAX_PACKETLEN - 100)
Definition at line 52 of file net_chan.c.
MAX_LOOPBACK
#define MAX_LOOPBACK 16
Definition at line 424 of file net_chan.c.
MAX_PACKETLEN
#define MAX_PACKETLEN 1400
Definition at line 50 of file net_chan.c.
PACKET_HEADER
#define PACKET_HEADER 10
Definition at line 53 of file net_chan.c.
Typedef Documentation
packetQueue_t
typedef struct packetQueue_s packetQueue_t
Function Documentation
NET_FlushPacketQueue()
void NET_FlushPacketQueue (void)
Definition at line 519 of file net_chan.c.
 {
     packetQueue_t *last;
     int now;
     while(packetQueue) {
         now = Sys_Milliseconds();
         if(packetQueue->release >= now)
             break;
         Sys_SendPacket(packetQueue->length, packetQueue->data,
             packetQueue->to);
         last = packetQueue;
         packetQueue = packetQueue->next;
         Z_Free(last->data);
         Z_Free(last);
     }
 }
Referenced by Com_Frame().
NET_GetLoopPacket()
qboolean NET_GetLoopPacket (netsrc_t sock, netadr_t * net_from, msg_t * net_message)
Definition at line 439 of file net_chan.c.
 {
     int     i;
     loopback_t  *loop;
     loop = &loopbacks[sock];
     if (loop->send - loop->get > MAX_LOOPBACK)
         loop->get = loop->send - MAX_LOOPBACK;
     if (loop->get >= loop->send)
         return qfalse;
     i = loop->get & (MAX_LOOPBACK-1);
     loop->get++;
     Com_Memcpy (net_message->data, loop->msgs[i].data, loop->msgs[i].datalen);
     net_message->cursize = loop->msgs[i].datalen;
     Com_Memset (net_from, 0, sizeof(*net_from));
     net_from->type = NA_LOOPBACK;
     return qtrue;
 }
Referenced by Com_EventLoop().
NET_OutOfBandData()
void QDECL NET_OutOfBandData (netsrc_t sock, netadr_t adr, byte * format, int len)
Definition at line 599 of file net_chan.c.
{
     byte        string[MAX_MSGLEN*2];
     int         i;
     msg_t       mbuf;
     // set the header
     string[0] = 0xff;
     string[1] = 0xff;
     string[2] = 0xff;
     string[3] = 0xff;
     for(i=0;i<len;i++) {
         string[i+4] = format[i];
     }
     mbuf.data = string;
     mbuf.cursize = len+4;
     Huff_Compress( &mbuf, 12);
     // send the datagram
     NET_SendPacket( sock, mbuf.cursize, mbuf.data, adr );
 }
Referenced by CL_CheckForResend().
NET_OutOfBandPrint()
void QDECL NET_OutOfBandPrint (netsrc_t sock, netadr_t adr, const char * format, ...)
Definition at line 573 of file net_chan.c.
{
     va_list     argptr;
     char        string[MAX_MSGLEN];
     // set the header
     string[0] = -1;
     string[1] = -1;
     string[2] = -1;
     string[3] = -1;
     va_start( argptr, format );
     Q_vsnprintf( string+4, sizeof(string)-4, format, argptr );
     va_end( argptr );
     // send the datagram
     NET_SendPacket( sock, strlen( string ), string, adr );
 }
Referenced by CL_CheckForResend(), CL_ConnectionlessPacket(), CL_GlobalServers_f(), CL_Ping_f(), CL_RequestAuthorization(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatus_f(), CL_UpdateVisiblePings_f(), SV_AuthorizeIpPacket(), SV_Ban_f(), SV_BanNum_f(), SV_DirectConnect(), SV_FlushRedirect(), SV_GetChallenge(), SV_MasterHeartbeat(), SVC_Info(), and SVC_Status().
NET_QueuePacket()
static void NET_QueuePacket (int length, const void * data, netadr_t to, int offset) static
Definition at line 490 of file net_chan.c.
 {
     packetQueue_t *new, *next = packetQueue;
     if(offset > 999)
         offset = 999;
     new = S_Malloc(sizeof(packetQueue_t));
     new->data = S_Malloc(length);
     Com_Memcpy(new->data, data, length);
     new->length = length;
     new->to = to;
     new->release = Sys_Milliseconds() + (int)((float)offset / com_timescale->value);
     new->next = NULL;
     if(!packetQueue) {
         packetQueue = new;
         return;
     }
     while(next) {
         if(!next->next) {
             next->next = new;
             return;
         }
         next = next->next;
     }
 }
Referenced by NET_SendPacket().
NET_SendLoopPacket()
void NET_SendLoopPacket (netsrc_t sock, int length, const void * data, netadr_t to)
Definition at line 464 of file net_chan.c.
 {
     int     i;
     loopback_t  *loop;
     loop = &loopbacks[sock^1];
     i = loop->send & (MAX_LOOPBACK-1);
     loop->send++;
     Com_Memcpy (loop->msgs[i].data, data, length);
     loop->msgs[i].datalen = length;
 }
Referenced by NET_SendPacket().
NET_SendPacket()
void NET_SendPacket (netsrc_t sock, int length, const void * data, netadr_t to)
Definition at line 537 of file net_chan.c.
{
     // sequenced packets are shown in netchan, so just show oob
     if ( showpackets->integer && *(int *)data == -1 )   {
         Com_Printf ("send packet %4i\n", length);
     }
     if ( to.type == NA_LOOPBACK ) {
         NET_SendLoopPacket (sock, length, data, to);
         return;
     }
     if ( to.type == NA_BOT ) {
         return;
     }
     if ( to.type == NA_BAD ) {
         return;
     }
     if ( sock == NS_CLIENT && cl_packetdelay->integer > 0 ) {
         NET_QueuePacket( length, data, to, cl_packetdelay->integer );
     }
     else if ( sock == NS_SERVER && sv_packetdelay->integer > 0 ) {
         NET_QueuePacket( length, data, to, sv_packetdelay->integer );
     }
     else {
         Sys_SendPacket( length, data, to );
     }
 }
Referenced by CL_LocalServers_f(), CL_Rcon_f(), NET_OutOfBandData(), NET_OutOfBandPrint(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
NET_StringToAdr()
int NET_StringToAdr (const char * s, netadr_t * a, netadrtype_t family)
Definition at line 629 of file net_chan.c.
 {
     char    base[MAX_STRING_CHARS], *search;
     char    *port = NULL;
     if (!strcmp (s, "localhost")) {
         Com_Memset (a, 0, sizeof(*a));
         a->type = NA_LOOPBACK;
 // as NA_LOOPBACK doesn't require ports report port was given.
         return 1;
     }
     Q_strncpyz( base, s, sizeof( base ) );
     if(*base == '[' || Q_CountChar(base, ':') > 1)
     {
         // This is an ipv6 address, handle it specially.
         search = strchr(base, ']');
         if(search)
         {
             *search = '\0';
             search++;
             if(*search == ':')
                 port = search + 1;
         }
         if(*base == '[')
             search = base + 1;
         else
             search = base;
     }
     else
     {
         // look for a port number
         port = strchr( base, ':' );
         if ( port ) {
             *port = '\0';
             port++;
         }
         search = base;
     }
     if(!Sys_StringToAdr(search, a, family))
     {
         a->type = NA_BAD;
         return 0;
     }
     if(port)
     {
         a->port = BigShort((short) atoi(port));
         return 1;
     }
     else
     {
         a->port = BigShort(PORT_SERVER);
         return 2;
     }
 }
Referenced by CL_Connect_f(), CL_GlobalServers_f(), CL_MapLoading(), CL_Ping_f(), CL_Rcon_f(), CL_RequestAuthorization(), CL_RequestMotd(), CL_ServerStatus(), CL_ServerStatus_f(), LAN_AddServer(), LAN_RemoveServer(), SV_Ban_f(), SV_BanNum_f(), SV_GetChallenge(), SV_MasterHeartbeat(), SV_ParseCIDRNotation(), and SV_RehashBans_f().
Netchan_Init()
void Netchan_Init (int port)
Definition at line 72 of file net_chan.c.
{
     port &= 0xffff;
     showpackets = Cvar_Get ("showpackets", "0", CVAR_TEMP );
     showdrop = Cvar_Get ("showdrop", "0", CVAR_TEMP );
     qport = Cvar_Get ("net_qport", va("%i", port), CVAR_INIT );
 }
Referenced by Com_Init().
Netchan_Process()
qboolean Netchan_Process (netchan_t * chan, msg_t * msg)
Definition at line 244 of file net_chan.c.
{
     int         sequence;
     int         fragmentStart, fragmentLength;
     qboolean    fragmented;
     // XOR unscramble all data in the packet after the header
 //  Netchan_UnScramblePacket( msg );
     // get sequence numbers
     MSG_BeginReadingOOB( msg );
     sequence = MSG_ReadLong( msg );
     // check for fragment information
     if ( sequence & FRAGMENT_BIT ) {
         sequence &= ~FRAGMENT_BIT;
         fragmented = qtrue;
     } else {
         fragmented = qfalse;
     }
     // read the qport if we are a server
     if ( chan->sock == NS_SERVER ) {
         MSG_ReadShort( msg );
     }
 #ifdef LEGACY_PROTOCOL
     if(!chan->compat)
 #endif
     {
         int checksum = MSG_ReadLong(msg);
         // UDP spoofing protection
         if(NETCHAN_GENCHECKSUM(chan->challenge, sequence) != checksum)
             return qfalse;
     }
     // read the fragment information
     if ( fragmented ) {
         fragmentStart = MSG_ReadShort( msg );
         fragmentLength = MSG_ReadShort( msg );
     } else {
         fragmentStart = 0;      // stop warning message
         fragmentLength = 0;
     }
     if ( showpackets->integer ) {
         if ( fragmented ) {
             Com_Printf( "%s recv %4i : s=%i fragment=%i,%i\n"
                 , netsrcString[ chan->sock ]
                 , msg->cursize
                 , sequence
                 , fragmentStart, fragmentLength );
         } else {
             Com_Printf( "%s recv %4i : s=%i\n"
                 , netsrcString[ chan->sock ]
                 , msg->cursize
                 , sequence );
         }
     }
     //
     // discard out of order or duplicated packets
     //
     if ( sequence <= chan->incomingSequence ) {
         if ( showdrop->integer || showpackets->integer ) {
             Com_Printf( "%s:Out of order packet %i at %i\n"
                 , NET_AdrToString( chan->remoteAddress )
                 ,  sequence
                 , chan->incomingSequence );
         }
         return qfalse;
     }
     //
     // dropped packets don't keep the message from being used
     //
     chan->dropped = sequence - (chan->incomingSequence+1);
     if ( chan->dropped > 0 ) {
         if ( showdrop->integer || showpackets->integer ) {
             Com_Printf( "%s:Dropped %i packets at %i\n"
             , NET_AdrToString( chan->remoteAddress )
             , chan->dropped
             , sequence );
         }
     }
     //
     // if this is the final framgent of a reliable message,
     // bump incoming_reliable_sequence
     //
     if ( fragmented ) {
         // TTimo
         // make sure we add the fragments in correct order
         // either a packet was dropped, or we received this one too soon
         // we don't reconstruct the fragments. we will wait till this fragment gets to us again
         // (NOTE: we could probably try to rebuild by out of order chunks if needed)
         if ( sequence != chan->fragmentSequence ) {
             chan->fragmentSequence = sequence;
             chan->fragmentLength = 0;
         }
         // if we missed a fragment, dump the message
         if ( fragmentStart != chan->fragmentLength ) {
             if ( showdrop->integer || showpackets->integer ) {
                 Com_Printf( "%s:Dropped a message fragment\n"
                 , NET_AdrToString( chan->remoteAddress ));
             }
             // we can still keep the part that we have so far,
             // so we don't need to clear chan->fragmentLength
             return qfalse;
         }
         // copy the fragment to the fragment buffer
         if ( fragmentLength < 0 || msg->readcount + fragmentLength > msg->cursize ||
             chan->fragmentLength + fragmentLength > sizeof( chan->fragmentBuffer ) ) {
             if ( showdrop->integer || showpackets->integer ) {
                 Com_Printf ("%s:illegal fragment length\n"
                 , NET_AdrToString (chan->remoteAddress ) );
             }
             return qfalse;
         }
         Com_Memcpy( chan->fragmentBuffer + chan->fragmentLength,
             msg->data + msg->readcount, fragmentLength );
         chan->fragmentLength += fragmentLength;
         // if this wasn't the last fragment, don't process anything
         if ( fragmentLength == FRAGMENT_SIZE ) {
             return qfalse;
         }
         if ( chan->fragmentLength > msg->maxsize ) {
             Com_Printf( "%s:fragmentLength %i > msg->maxsize\n"
                 , NET_AdrToString (chan->remoteAddress ),
                 chan->fragmentLength );
             return qfalse;
         }
         // copy the full message over the partial fragment
         // make sure the sequence number is still there
         *(int *)msg->data = LittleLong( sequence );
         Com_Memcpy( msg->data + 4, chan->fragmentBuffer, chan->fragmentLength );
         msg->cursize = chan->fragmentLength + 4;
         chan->fragmentLength = 0;
         msg->readcount = 4; // past the sequence number
         msg->bit = 32;  // past the sequence number
         // TTimo
         // clients were not acking fragmented messages
         chan->incomingSequence = sequence;
         return qtrue;
     }
     //
     // the message can now be read from the current message pointer
     //
     chan->incomingSequence = sequence;
     return qtrue;
 }
Referenced by CL_Netchan_Process(), and SV_Netchan_Process().
Netchan_Setup()
void Netchan_Setup (netsrc_t sock, netchan_t * chan, netadr_t adr, int qport, int challenge, qboolean compat)
Definition at line 86 of file net_chan.c.
 {
     Com_Memset (chan, 0, sizeof(*chan));
     chan->sock = sock;
     chan->remoteAddress = adr;
     chan->qport = qport;
     chan->incomingSequence = 0;
     chan->outgoingSequence = 1;
     chan->challenge = challenge;
 #ifdef LEGACY_PROTOCOL
     chan->compat = compat;
 #endif
 }
Referenced by CL_ConnectionlessPacket(), and SV_DirectConnect().
Netchan_Transmit()
void Netchan_Transmit (netchan_t * chan, int length, const byte * data)
Definition at line 177 of file net_chan.c.
{
     msg_t       send;
     byte        send_buf[MAX_PACKETLEN];
     if ( length > MAX_MSGLEN ) {
         Com_Error( ERR_DROP, "Netchan_Transmit: length = %i", length );
     }
     chan->unsentFragmentStart = 0;
     // fragment large reliable messages
     if ( length >= FRAGMENT_SIZE ) {
         chan->unsentFragments = qtrue;
         chan->unsentLength = length;
         Com_Memcpy( chan->unsentBuffer, data, length );
         // only send the first fragment now
         Netchan_TransmitNextFragment( chan );
         return;
     }
     // write the packet header
     MSG_InitOOB (&send, send_buf, sizeof(send_buf));
     MSG_WriteLong( &send, chan->outgoingSequence );
     // send the qport if we are a client
     if(chan->sock == NS_CLIENT)
         MSG_WriteShort(&send, qport->integer);
 #ifdef LEGACY_PROTOCOL
     if(!chan->compat)
 #endif
         MSG_WriteLong(&send, NETCHAN_GENCHECKSUM(chan->challenge, chan->outgoingSequence));
     chan->outgoingSequence++;
     MSG_WriteData( &send, data, length );
     // send the datagram
     NET_SendPacket( chan->sock, send.cursize, send.data, chan->remoteAddress );
     // Store send time and size of this packet for rate control
     chan->lastSentTime = Sys_Milliseconds();
     chan->lastSentSize = send.cursize;
     if ( showpackets->integer ) {
         Com_Printf( "%s send %4i : s=%i ack=%i\n"
             , netsrcString[ chan->sock ]
             , send.cursize
             , chan->outgoingSequence - 1
             , chan->incomingSequence );
     }
 }
Referenced by CL_Netchan_Transmit(), SV_Netchan_Transmit(), and SV_Netchan_TransmitNextInQueue().
Netchan_TransmitNextFragment()
void Netchan_TransmitNextFragment (netchan_t * chan)
Definition at line 109 of file net_chan.c.
{
     msg_t       send;
     byte        send_buf[MAX_PACKETLEN];
     int         fragmentLength;
     int         outgoingSequence;
     // write the packet header
     MSG_InitOOB (&send, send_buf, sizeof(send_buf));                // <-- only do the oob here
     outgoingSequence = chan->outgoingSequence | FRAGMENT_BIT;
     MSG_WriteLong(&send, outgoingSequence);
     // send the qport if we are a client
     if ( chan->sock == NS_CLIENT ) {
         MSG_WriteShort( &send, qport->integer );
     }
 #ifdef LEGACY_PROTOCOL
     if(!chan->compat)
 #endif
         MSG_WriteLong(&send, NETCHAN_GENCHECKSUM(chan->challenge, chan->outgoingSequence));
     // copy the reliable message to the packet first
     fragmentLength = FRAGMENT_SIZE;
     if ( chan->unsentFragmentStart  + fragmentLength > chan->unsentLength ) {
         fragmentLength = chan->unsentLength - chan->unsentFragmentStart;
     }
     MSG_WriteShort( &send, chan->unsentFragmentStart );
     MSG_WriteShort( &send, fragmentLength );
     MSG_WriteData( &send, chan->unsentBuffer + chan->unsentFragmentStart, fragmentLength );
     // send the datagram
     NET_SendPacket(chan->sock, send.cursize, send.data, chan->remoteAddress);
     // Store send time and size of this packet for rate control
     chan->lastSentTime = Sys_Milliseconds();
     chan->lastSentSize = send.cursize;
     if ( showpackets->integer ) {
         Com_Printf ("%s send %4i : s=%i fragment=%i,%i\n"
             , netsrcString[ chan->sock ]
             , send.cursize
             , chan->outgoingSequence
             , chan->unsentFragmentStart, fragmentLength);
     }
     chan->unsentFragmentStart += fragmentLength;
     // this exit condition is a little tricky, because a packet
     // that is exactly the fragment length still needs to send
     // a second packet of zero length so that the other side
     // can tell there aren't more to follow
     if ( chan->unsentFragmentStart == chan->unsentLength && fragmentLength != FRAGMENT_SIZE ) {
         chan->outgoingSequence++;
         chan->unsentFragments = qfalse;
     }
 }
Referenced by CL_Netchan_TransmitNextFragment(), Netchan_Transmit(), and SV_Netchan_TransmitNextFragment().
Variable Documentation
loopbacks
loopback_t loopbacks[2]
Definition at line 436 of file net_chan.c.
Referenced by NET_GetLoopPacket(), and NET_SendLoopPacket().
netsrcString
char* netsrcString[2] static
Initial value:
= {
    "client",
    "server"
}
Definition at line 61 of file net_chan.c.
Referenced by Netchan_Process(), Netchan_Transmit(), and Netchan_TransmitNextFragment().
packetQueue
packetQueue_t* packetQueue = NULL
Definition at line 488 of file net_chan.c.
Referenced by NET_FlushPacketQueue(), and NET_QueuePacket().
qport
cvar_t* qport
Definition at line 59 of file net_chan.c.
Referenced by Com_Init(), Netchan_Init(), Netchan_Setup(), Netchan_Transmit(), Netchan_TransmitNextFragment(), SV_DirectConnect(), and SV_PacketEvent().
showdrop
cvar_t* showdrop
Definition at line 58 of file net_chan.c.
Referenced by Netchan_Init(), and Netchan_Process().
showpackets
cvar_t* showpackets
Definition at line 57 of file net_chan.c.
Referenced by NET_SendPacket(), Netchan_Init(), Netchan_Process(), Netchan_Transmit(), and Netchan_TransmitNextFragment().