ioquake3 doxygen: C:/entry/dev/ioq3/code/client/cl_net_chan.c File Reference
cl_net_chan.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "client.h"
Functions
static void CL_Netchan_Encode (msg_t *msg)
static void CL_Netchan_Decode (msg_t *msg)
qboolean CL_Netchan_TransmitNextFragment (netchan_t *chan)
void CL_Netchan_Transmit (netchan_t *chan, msg_t *msg)
qboolean CL_Netchan_Process (netchan_t *chan, msg_t *msg)
Function Documentation
CL_Netchan_Decode()
static void CL_Netchan_Decode (msg_t * msg) static
Definition at line 93 of file cl_net_chan.c.
{
     long reliableAcknowledge, i, index;
     byte key, *string;
         int srdc, sbit, soob;
         srdc = msg->readcount;
         sbit = msg->bit;
         soob = msg->oob;
         msg->oob = 0;
     reliableAcknowledge = MSG_ReadLong(msg);
         msg->oob = soob;
         msg->bit = sbit;
         msg->readcount = srdc;
     string = (byte *) clc.reliableCommands[ reliableAcknowledge & (MAX_RELIABLE_COMMANDS-1) ];
     index = 0;
     // xor the client challenge with the netchan sequence number (need something that changes every message)
     key = clc.challenge ^ LittleLong( *(unsigned *)msg->data );
     for (i = msg->readcount + CL_DECODE_START; i < msg->cursize; i++) {
         // modify the key with the last sent and with this message acknowledged client command
         if (!string[index])
             index = 0;
         if (string[index] > 127 || string[index] == '%') {
             key ^= '.' << (i & 1);
         }
         else {
             key ^= string[index] << (i & 1);
         }
         index++;
         // decode the data with this key
         *(msg->data + i) = *(msg->data + i) ^ key;
     }
 }
References msg_t::bit, clientConnection_t::challenge, CL_DECODE_START, clc, msg_t::data, LittleLong, MAX_RELIABLE_COMMANDS, MSG_ReadLong(), msg_t::oob, msg_t::readcount, and clientConnection_t::reliableCommands.
Referenced by CL_Netchan_Process().
CL_Netchan_Encode()
static void CL_Netchan_Encode (msg_t * msg) static
Definition at line 39 of file cl_net_chan.c.
{
     int serverId, messageAcknowledge, reliableAcknowledge;
     int i, index, srdc, sbit, soob;
     byte key, *string;
     if ( msg->cursize <= CL_ENCODE_START ) {
         return;
     }
         srdc = msg->readcount;
         sbit = msg->bit;
         soob = msg->oob;
         msg->bit = 0;
         msg->readcount = 0;
         msg->oob = 0;
         serverId = MSG_ReadLong(msg);
     messageAcknowledge = MSG_ReadLong(msg);
     reliableAcknowledge = MSG_ReadLong(msg);
         msg->oob = soob;
         msg->bit = sbit;
         msg->readcount = srdc;
     string = (byte *)clc.serverCommands[ reliableAcknowledge & (MAX_RELIABLE_COMMANDS-1) ];
     index = 0;
     //
     key = clc.challenge ^ serverId ^ messageAcknowledge;
     for (i = CL_ENCODE_START; i < msg->cursize; i++) {
         // modify the key with the last received now acknowledged server command
         if (!string[index])
             index = 0;
         if (string[index] > 127 || string[index] == '%') {
             key ^= '.' << (i & 1);
         }
         else {
             key ^= string[index] << (i & 1);
         }
         index++;
         // encode the data with this key
         *(msg->data + i) = (*(msg->data + i)) ^ key;
     }
 }
References msg_t::bit, clientConnection_t::challenge, CL_ENCODE_START, clc, msg_t::cursize, msg_t::data, MAX_RELIABLE_COMMANDS, MSG_ReadLong(), msg_t::oob, msg_t::readcount, and clientConnection_t::serverCommands.
Referenced by CL_Netchan_Transmit().
CL_Netchan_Process()
qboolean CL_Netchan_Process (netchan_t * chan, msg_t * msg)
Definition at line 174 of file cl_net_chan.c.
{
     int ret;
     ret = Netchan_Process( chan, msg );
     if (!ret)
         return qfalse;
 #ifdef LEGACY_PROTOCOL
     if(chan->compat)
         CL_Netchan_Decode(msg);
 #endif
     return qtrue;
 }
References CL_Netchan_Decode(), Netchan_Process(), qfalse, and qtrue.
Referenced by CL_PacketEvent().
CL_Netchan_Transmit()
void CL_Netchan_Transmit (netchan_t * chan, msg_t * msg)
Definition at line 152 of file cl_net_chan.c.
{
     MSG_WriteByte( msg, clc_EOF );
 #ifdef LEGACY_PROTOCOL
     if(chan->compat)
         CL_Netchan_Encode(msg);
 #endif
     Netchan_Transmit(chan, msg->cursize, msg->data);
     // Transmit all fragments without delay
     while(CL_Netchan_TransmitNextFragment(chan))
     {
         Com_DPrintf("WARNING: #462 unsent fragments (not supposed to happen!)\n");
     }
 }
References CL_Netchan_Encode(), CL_Netchan_TransmitNextFragment(), clc_EOF, Com_DPrintf(), msg_t::cursize, msg_t::data, MSG_WriteByte(), and Netchan_Transmit().
Referenced by CL_WritePacket().
CL_Netchan_TransmitNextFragment()
qboolean CL_Netchan_TransmitNextFragment (netchan_t * chan)
Definition at line 136 of file cl_net_chan.c.
 {
     if(chan->unsentFragments)
     {
         Netchan_TransmitNextFragment(chan);
         return qtrue;
     }
     return qfalse;
 }
References Netchan_TransmitNextFragment(), qfalse, qtrue, and netchan_t::unsentFragments.
Referenced by CL_Netchan_Transmit().