ioquake3 doxygen: C:/entry/dev/ioq3/code/game/ai_team.h File Reference
ai_team.h File Reference
Functions
void BotTeamAI (bot_state_t *bs)
int BotGetTeamMateTaskPreference (bot_state_t *bs, int teammate)
void BotSetTeamMateTaskPreference (bot_state_t *bs, int teammate, int preference)
void BotVoiceChat (bot_state_t *bs, int toclient, char *voicechat)
void BotVoiceChatOnly (bot_state_t *bs, int toclient, char *voicechat)
Function Documentation
BotGetTeamMateTaskPreference()
int BotGetTeamMateTaskPreference (bot_state_t * bs, int teammate)
Definition at line 200 of file ai_team.c.
{
     char teammatename[MAX_NETNAME];
     if (!ctftaskpreferences[teammate].preference) return 0;
     ClientName(teammate, teammatename, sizeof(teammatename));
     if (Q_stricmp(teammatename, ctftaskpreferences[teammate].name)) return 0;
     return ctftaskpreferences[teammate].preference;
 }
Referenced by BotMatch_TaskPreference(), BotSortTeamMatesByTaskPreference(), BotVoiceChat_WantOnDefense(), and BotVoiceChat_WantOnOffense().
BotSetTeamMateTaskPreference()
void BotSetTeamMateTaskPreference (bot_state_t * bs, int teammate, int preference)
Definition at line 187 of file ai_team.c.
{
     char teammatename[MAX_NETNAME];
     ctftaskpreferences[teammate].preference = preference;
     ClientName(teammate, teammatename, sizeof(teammatename));
     strcpy(ctftaskpreferences[teammate].name, teammatename);
 }
Referenced by BotMatch_TaskPreference(), BotVoiceChat_WantOnDefense(), and BotVoiceChat_WantOnOffense().
BotTeamAI()
void BotTeamAI (bot_state_t * bs)
Definition at line 1927 of file ai_team.c.
{
     int numteammates;
     char netname[MAX_NETNAME];
     //
     if ( gametype < GT_TEAM  )
         return;
     // make sure we've got a valid team leader
     if (!BotValidTeamLeader(bs)) {
         //
         if (!FindHumanTeamLeader(bs)) {
             //
             if (!bs->askteamleader_time && !bs->becometeamleader_time) {
                 if (bs->entergame_time + 10 > FloatTime()) {
                     bs->askteamleader_time = FloatTime() + 5 + random() * 10;
                 }
                 else {
                     bs->becometeamleader_time = FloatTime() + 5 + random() * 10;
                 }
             }
             if (bs->askteamleader_time && bs->askteamleader_time < FloatTime()) {
                 // if asked for a team leader and no response
                 BotAI_BotInitialChat(bs, "whoisteamleader", NULL);
                 trap_BotEnterChat(bs->cs, 0, CHAT_TEAM);
                 bs->askteamleader_time = 0;
                 bs->becometeamleader_time = FloatTime() + 8 + random() * 10;
             }
             if (bs->becometeamleader_time && bs->becometeamleader_time < FloatTime()) {
                 BotAI_BotInitialChat(bs, "iamteamleader", NULL);
                 trap_BotEnterChat(bs->cs, 0, CHAT_TEAM);
                 BotSayVoiceTeamOrder(bs, -1, VOICECHAT_STARTLEADER);
                 ClientName(bs->client, netname, sizeof(netname));
                 strncpy(bs->teamleader, netname, sizeof(bs->teamleader));
                 bs->teamleader[sizeof(bs->teamleader)-1] = '\0';
                 bs->becometeamleader_time = 0;
             }
             return;
         }
     }
     bs->askteamleader_time = 0;
     bs->becometeamleader_time = 0;
     //return if this bot is NOT the team leader
     ClientName(bs->client, netname, sizeof(netname));
     if (Q_stricmp(netname, bs->teamleader) != 0) return;
     //
     numteammates = BotNumTeamMates(bs);
     //give orders
     switch(gametype) {
         case GT_TEAM:
         {
             if (bs->numteammates != numteammates || bs->forceorders) {
                 bs->teamgiveorders_time = FloatTime();
                 bs->numteammates = numteammates;
                 bs->forceorders = qfalse;
             }
             //if it's time to give orders
             if (bs->teamgiveorders_time && bs->teamgiveorders_time < FloatTime() - 5) {
                 BotTeamOrders(bs);
                 //give orders again after 120 seconds
                 bs->teamgiveorders_time = FloatTime() + 120;
             }
             break;
         }
         case GT_CTF:
         {
             //if the number of team mates changed or the flag status changed
             //or someone wants to know what to do
             if (bs->numteammates != numteammates || bs->flagstatuschanged || bs->forceorders) {
                 bs->teamgiveorders_time = FloatTime();
                 bs->numteammates = numteammates;
                 bs->flagstatuschanged = qfalse;
                 bs->forceorders = qfalse;
             }
             //if there were no flag captures the last 3 minutes
             if (bs->lastflagcapture_time < FloatTime() - 240) {
                 bs->lastflagcapture_time = FloatTime();
                 //randomly change the CTF strategy
                 if (random() < 0.4) {
                     bs->ctfstrategy ^= CTFS_AGRESSIVE;
                     bs->teamgiveorders_time = FloatTime();
                 }
             }
             //if it's time to give orders
             if (bs->teamgiveorders_time && bs->teamgiveorders_time < FloatTime() - 3) {
                 BotCTFOrders(bs);
                 //
                 bs->teamgiveorders_time = 0;
             }
             break;
         }
 #ifdef MISSIONPACK
         case GT_1FCTF:
         {
             if (bs->numteammates != numteammates || bs->flagstatuschanged || bs->forceorders) {
                 bs->teamgiveorders_time = FloatTime();
                 bs->numteammates = numteammates;
                 bs->flagstatuschanged = qfalse;
                 bs->forceorders = qfalse;
             }
             //if there were no flag captures the last 4 minutes
             if (bs->lastflagcapture_time < FloatTime() - 240) {
                 bs->lastflagcapture_time = FloatTime();
                 //randomly change the CTF strategy
                 if (random() < 0.4) {
                     bs->ctfstrategy ^= CTFS_AGRESSIVE;
                     bs->teamgiveorders_time = FloatTime();
                 }
             }
             //if it's time to give orders
             if (bs->teamgiveorders_time && bs->teamgiveorders_time < FloatTime() - 2) {
                 Bot1FCTFOrders(bs);
                 //
                 bs->teamgiveorders_time = 0;
             }
             break;
         }
         case GT_OBELISK:
         {
             if (bs->numteammates != numteammates || bs->forceorders) {
                 bs->teamgiveorders_time = FloatTime();
                 bs->numteammates = numteammates;
                 bs->forceorders = qfalse;
             }
             //if it's time to give orders
             if (bs->teamgiveorders_time && bs->teamgiveorders_time < FloatTime() - 5) {
                 BotObeliskOrders(bs);
                 //give orders again after 30 seconds
                 bs->teamgiveorders_time = FloatTime() + 30;
             }
             break;
         }
         case GT_HARVESTER:
         {
             if (bs->numteammates != numteammates || bs->forceorders) {
                 bs->teamgiveorders_time = FloatTime();
                 bs->numteammates = numteammates;
                 bs->forceorders = qfalse;
             }
             //if it's time to give orders
             if (bs->teamgiveorders_time && bs->teamgiveorders_time < FloatTime() - 5) {
                 BotHarvesterOrders(bs);
                 //give orders again after 30 seconds
                 bs->teamgiveorders_time = FloatTime() + 30;
             }
             break;
         }
 #endif
     }
 }
Referenced by BotDeathmatchAI().
BotVoiceChat()
void BotVoiceChat (bot_state_t * bs, int toclient, char * voicechat)
Definition at line 291 of file ai_team.c.
{
 #ifdef MISSIONPACK
     if (toclient == -1)
         // voice only say team
         trap_EA_Command(bs->client, va("vsay_team %s", voicechat));
     else
         // voice only tell single player
         trap_EA_Command(bs->client, va("vtell %d %s", toclient, voicechat));
 #endif
 }
Referenced by BotCheckItemPickup(), BotCTFSeekGoals(), BotMatch_Suicide(), BotRefuseOrder(), and BotSayVoiceTeamOrder().
BotVoiceChatOnly()
void BotVoiceChatOnly (bot_state_t * bs, int toclient, char * voicechat)
Definition at line 307 of file ai_team.c.
{
 #ifdef MISSIONPACK
     if (toclient == -1)
         // voice only say team
         trap_EA_Command(bs->client, va("vosay_team %s", voicechat));
     else
         // voice only tell single player
         trap_EA_Command(bs->client, va("votell %d %s", toclient, voicechat));
 #endif
 }
Referenced by BotGetLongTermGoal(), BotMatch_TaskPreference(), BotVoiceChat_Patrol(), BotVoiceChat_WantOnDefense(), BotVoiceChat_WantOnOffense(), and BotVoiceChat_WhoIsLeader().