ioquake3 doxygen: C:/entry/dev/ioq3/code/cgame/cg_consolecmds.c File Reference
cg_consolecmds.c File Reference
#include "cg_local.h"
Classes
struct consoleCommand_t
Functions
void CG_TargetCommand_f (void)
static void CG_SizeUp_f (void)
static void CG_SizeDown_f (void)
static void CG_Viewpos_f (void)
static void CG_ScoresDown_f (void)
static void CG_ScoresUp_f (void)
static void CG_TellTarget_f (void)
static void CG_TellAttacker_f (void)
static void CG_StartOrbit_f (void)
qboolean CG_ConsoleCommand (void)
void CG_InitConsoleCommands (void)
Variables
static consoleCommand_t commands []
Function Documentation
CG_ConsoleCommand()
qboolean CG_ConsoleCommand (void)
Definition at line 543 of file cg_consolecmds.c.
 {
     const char* cmd;
     int        i;
     cmd = CG_Argv(0);
     for (i = 0; i < ARRAY_LEN(commands); i++) {
         if (!Q_stricmp(cmd, commands[i].cmd)) {
             commands[i].function();
             return qtrue;
         }
     }
     return qfalse;
 }
References ARRAY_LEN, CG_Argv(), commands, consoleCommand_t::function, Q_stricmp(), qfalse, and qtrue.
Referenced by vmMain().
CG_InitConsoleCommands()
void CG_InitConsoleCommands (void)
Definition at line 569 of file cg_consolecmds.c.
 {
     int        i;
     for (i = 0; i < ARRAY_LEN(commands); i++) {
         trap_AddCommand(commands[i].cmd);
     }
     //
     // the game server will interpret these commands, which will be automatically
     // forwarded to the server after they are not recognized locally
     //
     trap_AddCommand("kill");
     trap_AddCommand("say");
     trap_AddCommand("say_team");
     trap_AddCommand("tell");
 #ifdef MISSIONPACK
     trap_AddCommand("vsay");
     trap_AddCommand("vsay_team");
     trap_AddCommand("vtell");
     trap_AddCommand("vtaunt");
     trap_AddCommand("vosay");
     trap_AddCommand("vosay_team");
     trap_AddCommand("votell");
 #endif
     trap_AddCommand("give");
     trap_AddCommand("god");
     trap_AddCommand("notarget");
     trap_AddCommand("noclip");
     trap_AddCommand("where");
     trap_AddCommand("team");
     trap_AddCommand("follow");
     trap_AddCommand("follownext");
     trap_AddCommand("followprev");
     trap_AddCommand("levelshot");
     trap_AddCommand("addbot");
     trap_AddCommand("setviewpos");
     trap_AddCommand("callvote");
     trap_AddCommand("vote");
     trap_AddCommand("callteamvote");
     trap_AddCommand("teamvote");
     trap_AddCommand("stats");
     trap_AddCommand("teamtask");
     trap_AddCommand("loaddefered");    // spelled wrong, but not changing for demo
 }
References ARRAY_LEN, commands, and trap_AddCommand().
Referenced by CG_Init().
CG_ScoresDown_f()
static void CG_ScoresDown_f (void) static
Definition at line 84 of file cg_consolecmds.c.
 {
 #ifdef MISSIONPACK
     CG_BuildSpectatorString();
 #endif
     if (cg.scoresRequestTime + 2000 < cg.time) {
         // the scores are more than two seconds out of data,
         // so request new ones
         cg.scoresRequestTime = cg.time;
         trap_SendClientCommand("score");
         // leave the current scores up if they were already
         // displayed, but if this is the first hit, clear them out
         if (!cg.showScores) {
             cg.showScores = qtrue;
             cg.numScores = 0;
         }
     } else {
         // show the cached contents even if they just pressed if it
         // is within two seconds
         cg.showScores = qtrue;
     }
 }
References cg, CG_BuildSpectatorString(), cg_t::numScores, qtrue, cg_t::scoresRequestTime, cg_t::showScores, cg_t::time, and trap_SendClientCommand().
CG_ScoresUp_f()
static void CG_ScoresUp_f (void) static
Definition at line 109 of file cg_consolecmds.c.
 {
     if (cg.showScores) {
         cg.showScores = qfalse;
         cg.scoreFadeTime = cg.time;
     }
 }
References cg, qfalse, cg_t::scoreFadeTime, cg_t::showScores, and cg_t::time.
CG_SizeDown_f()
static void CG_SizeDown_f (void) static
Definition at line 64 of file cg_consolecmds.c.
 {
     trap_Cvar_Set("cg_viewsize", va("%i", (int)(cg_viewsize.integer - 10)));
 }
References cg_viewsize, vmCvar_t::integer, trap_Cvar_Set(), and va().
CG_SizeUp_f()
static void CG_SizeUp_f (void) static
Definition at line 52 of file cg_consolecmds.c.
 {
     trap_Cvar_Set("cg_viewsize", va("%i", (int)(cg_viewsize.integer + 10)));
 }
References cg_viewsize, vmCvar_t::integer, trap_Cvar_Set(), and va().
CG_StartOrbit_f()
static void CG_StartOrbit_f (void) static
Definition at line 443 of file cg_consolecmds.c.
 {
     char var[MAX_TOKEN_CHARS];
     trap_Cvar_VariableStringBuffer("developer", var, sizeof(var));
     if (!atoi(var)) {
         return;
     }
     if (cg_cameraOrbit.value != 0) {
         trap_Cvar_Set("cg_cameraOrbit", "0");
         trap_Cvar_Set("cg_thirdPerson", "0");
     } else {
         trap_Cvar_Set("cg_cameraOrbit", "5");
         trap_Cvar_Set("cg_thirdPerson", "1");
         trap_Cvar_Set("cg_thirdPersonAngle", "0");
         trap_Cvar_Set("cg_thirdPersonRange", "100");
     }
 }
References cg_cameraOrbit, MAX_TOKEN_CHARS, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and vmCvar_t::value.
CG_TargetCommand_f()
void CG_TargetCommand_f (void)
Definition at line 32 of file cg_consolecmds.c.
 {
     int        targetNum;
     char    test[4];
     targetNum = CG_CrosshairPlayer();
     if (targetNum == -1)
         return;
     trap_Argv(1, test, 4);
     trap_SendClientCommand(va("gc %i %i", targetNum, atoi(test)));
 }
References CG_CrosshairPlayer(), trap_Argv(), trap_SendClientCommand(), and va().
CG_TellAttacker_f()
static void CG_TellAttacker_f (void) static
Definition at line 203 of file cg_consolecmds.c.
 {
     int        clientNum;
     char    command[128];
     char    message[128];
     clientNum = CG_LastAttacker();
     if (clientNum == -1) {
         return;
     }
     trap_Args(message, 128);
     Com_sprintf(command, 128, "tell %i %s", clientNum, message);
     trap_SendClientCommand(command);
 }
References CG_LastAttacker(), Com_sprintf(), trap_Args(), and trap_SendClientCommand().
CG_TellTarget_f()
static void CG_TellTarget_f (void) static
Definition at line 187 of file cg_consolecmds.c.
 {
     int        clientNum;
     char    command[128];
     char    message[128];
     clientNum = CG_CrosshairPlayer();
     if (clientNum == -1) {
         return;
     }
     trap_Args(message, 128);
     Com_sprintf(command, 128, "tell %i %s", clientNum, message);
     trap_SendClientCommand(command);
 }
References CG_CrosshairPlayer(), Com_sprintf(), trap_Args(), and trap_SendClientCommand().
CG_Viewpos_f()
static void CG_Viewpos_f (void) static
Definition at line 76 of file cg_consolecmds.c.
 {
     CG_Printf("(%i %i %i) : %i\n", (int)cg.refdef.vieworg[0],
         (int)cg.refdef.vieworg[1], (int)cg.refdef.vieworg[2],
         (int)cg.refdefViewAngles[YAW]);
 }
References cg, CG_Printf(), cg_t::refdef, cg_t::refdefViewAngles, refdef_t::vieworg, and YAW.
Variable Documentation
commands
consoleCommand_t commands[] static
Definition at line 481 of file cg_consolecmds.c.
Referenced by CG_ConsoleCommand(), and CG_InitConsoleCommands().