ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/vm_sparc.c File Reference
vm_sparc.c File Reference
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <time.h>
#include <stddef.h>
#include "vm_local.h"
#include "vm_sparc.h"
Classes
struct sparc_opcode
struct VM_Data
struct src_insn
struct jump_insn
struct dst_insn
struct data_hunk
struct func_info
Macros
#define DIE(reason)
#define SL(a, b) (a)
#define rTMP G1
#define rVMDATA G2
#define rPSTACK G3
#define rDATABASE G4
#define rDATAMASK G5
#define ARG_NONE 0
#define ARG_RS1 1
#define ARG_RS2 2
#define ARG_RD 3
#define ARG_SIMM13 4
#define ARG_DISP30 5
#define ARG_IMM22 6
#define ARG_DISP22 7
#define ARG_SWTRAP 8
#define ARG_RS1_RS2_RD { ARG_RS1, ARG_RS2, ARG_RD }
#define ARG_RS1_SIMM13_RD { ARG_RS1, ARG_SIMM13, ARG_RD }
#define ARG_RS1_RS2 { ARG_RS1, ARG_RS2 }
#define ARG_RS2_RD { ARG_RS2, ARG_RD }
#define OP_MASK 0xc0000000
#define OP2_MASK 0x01c00000
#define OP3_MASK 0x01f80000
#define OPF_MASK 0x00003fe0
#define IMM 0x00002000
#define FMT1(op) ((op) << 30), OP_MASK
#define FMT2(op, op2) ((op) << 30)|((op2)<<22), (OP_MASK | OP2_MASK)
#define FMT3(op, op3) ((op) << 30)|((op3)<<19), (OP_MASK | OP3_MASK | IMM)
#define FMT3I(op, op3) ((op) << 30)|((op3)<<19)|IMM, (OP_MASK | OP3_MASK | IMM)
#define FMT3F(op, op3, opf)
#define BICC(A, COND) FMT2(0,((A<<7)|(COND<<3)|0x2))
#define BFCC(A, COND) FMT2(0,((A<<7)|(COND<<3)|0x6))
#define TICC(COND) FMT3I(0,((COND<<6)|0x3a))
#define LDLI SL(LDUWI, LDXI)
#define LDL SL(LDUW, LDX)
#define STLI SL(STWI, STXI)
#define STL SL(STW, STX)
#define SPARC_NOP 0x01000000
#define SPARC_NUM_OPCODES (ARRAY_LEN(sparc_opcodes))
#define RS1(X) (((X) & 0x1f) << 14)
#define RS2(X) (((X) & 0x1f) << 0)
#define RD(X) (((X) & 0x1f) << 25)
#define SIMM13(X) (((X) & 0x1fff) << 0)
#define IMM22(X) (((X) & 0x3fffff) << 0)
#define DISP30(X) ((((X) >> 2) & 0x3fffffff) << 0)
#define DISP22(X) ((((X) >> 2) & 0x3fffff) << 0)
#define SWTRAP(X) (((X) & 0x7f) << 0)
#define SIMM13_P(X) ((unsigned int) (X) + 0x1000 < 0x2000)
#define IN(inst, args...)
#define opImm0 0x0000 /* no immediate */
#define opImm1 0x0001 /* 1 byte immadiate value after opcode */
#define opImm4 0x0002 /* 4 bytes immediate value after opcode */
#define opRet0 0x0000 /* returns nothing */
#define opRetI 0x0004 /* returns integer */
#define opRetF 0x0008 /* returns float */
#define opRetIF (opRetI | opRetF) /* returns integer or float */
#define opArg0 0x0000 /* requires nothing */
#define opArgI 0x0010 /* requires integer(s) */
#define opArgF 0x0020 /* requires float(s) */
#define opArgIF (opArgI | opArgF) /* requires integer or float */
#define opArg2I 0x0040 /* requires second argument, integer */
#define opArg2F 0x0080 /* requires second argument, float */
#define opArg2IF (opArg2I | opArg2F) /* requires second argument, integer or float */
#define OFFSET(structName, field) ((void *)&(((structName *)NULL)->field) - NULL)
#define VM_Data_Offset(field) OFFSET(vm_data_t, field)
#define REG_FLAGS_FLOAT 0x1
#define HUNK_SIZE 29
#define rFIRST(fp) ((fp)->gpr_pos - 1)
#define rSECOND(fp) ((fp)->gpr_pos - 2)
#define POP_GPR(fp) ((fp)->gpr_pos--)
#define PUSH_GPR(fp) ((fp)->gpr_pos++)
#define fFIRST(fp) ((fp)->fpr_pos - 1)
#define fSECOND(fp) ((fp)->fpr_pos - 2)
#define POP_FPR(fp) ((fp)->fpr_pos--)
#define PUSH_FPR(fp) ((fp)->fpr_pos++)
#define INSN_BUF_SIZE 50
#define THUNK_ICOUNT -1
#define in(inst, args...) __do_emit_one(fp, IN(inst, args))
#define MAYBE_EMIT_CONST(fp)
#define EMIT_FALSE_CONST(fp)
#define CALL_THUNK_INSN_OFFSET 5
Typedefs
typedef struct VM_Data vm_data_t
Enumerations
enum sparc_iname {
CALL, NOP, SETHI, BA,
BN, BNE, BE, BG,
BLE, BGE, BL, BGU,
BLEU, BCC, BCS, BPOS,
BNEG, BVC, BVS, ADDI,
ADD, ANDI, AND, ORI,
OR, XORI, XOR, SUBI,
SUB, ANDNI, ANDN, ORNI,
ORN, XNORI, XNOR, UMULI,
UMUL, SMULI, SMUL, UDIVI,
UDIV, SDIVI, SDIV, SUBCCI,
SUBCC, SLLI, SLL, SRLI,
SRL, SRAI, SRA, WRI,
WR, SAVEI, SAVE, RESTOREI,
RESTORE, TA, JMPLI, JMPL,
LDXI, LDX, LDUWI, LDUW,
LDUHI, LDUH, LDUBI, LDUB,
STXI, STX, STWI, STW,
STHI, STH, STBI, STB,
LDFI, LDF, STFI, STF,
FADD, FSUB, FCMP, FSTOI,
FITOS, FNEG, FDIV, FMUL,
FBE, FBNE, FBL, FBGE,
FBG, FBLE
}
Functions
static void vimm (unsigned int val, int bits, int shift, int sgned, int arg_index)
static unsigned int sparc_assemble (enum sparc_iname iname, const int argc, const int *argv)
static void VM_Destroy_Compiled (vm_t *vm)
static unsigned int sparc_push_data (struct func_info *const fp, unsigned int val)
static void dst_insn_insert_tail (struct func_info *const fp, struct dst_insn *dp)
static void jump_insn_insert_tail (struct func_info *const fp, struct jump_insn *jp)
static struct dst_insn * dst_new (struct func_info *const fp, unsigned int length, struct jump_insn *jp, int insns_size)
static void dst_insn_append (struct func_info *const fp)
static void ErrJump (void)
static void jump_insn_append (vm_t *vm, struct func_info *const fp, enum sparc_iname iname, int dest)
static void start_emit (struct func_info *const fp, int i_count)
static void __do_emit_one (struct func_info *const fp, unsigned int insn)
static void end_emit (struct func_info *const fp)
static void emit_jump (vm_t *vm, struct func_info *const fp, enum sparc_iname iname, int dest)
static void analyze_function (struct func_info *const fp)
static int asmcall (int call, int pstack)
static void blockcopy (unsigned int dest, unsigned int src, unsigned int count)
static void do_emit_const (struct func_info *const fp, struct src_insn *sp)
static void compile_one_insn (vm_t *vm, struct func_info *const fp, struct src_insn *sp)
static void free_source_insns (struct func_info *const fp)
static void compile_function (vm_t *vm, struct func_info *const fp)
static void emit_vm_thunk (struct func_info *const fp)
static void sparc_compute_code (vm_t *vm, struct func_info *const fp)
void VM_Compile (vm_t *vm, vmHeader_t *header)
int VM_CallCompiled (vm_t *vm, int *args)
Variables
static const struct sparc_opcode sparc_opcodes []
static const unsigned char vm_opInfo [256]
static const char * opnames [256]
Macro Definition Documentation
ARG_DISP22
#define ARG_DISP22 7
Definition at line 68 of file vm_sparc.c.
ARG_DISP30
#define ARG_DISP30 5
Definition at line 66 of file vm_sparc.c.
ARG_IMM22
#define ARG_IMM22 6
Definition at line 67 of file vm_sparc.c.
ARG_NONE
#define ARG_NONE 0
Definition at line 61 of file vm_sparc.c.
ARG_RD
#define ARG_RD 3
Definition at line 64 of file vm_sparc.c.
ARG_RS1
#define ARG_RS1 1
Definition at line 62 of file vm_sparc.c.
ARG_RS1_RS2
#define ARG_RS1_RS2 { ARG_RS1, ARG_RS2 }
Definition at line 74 of file vm_sparc.c.
ARG_RS1_RS2_RD
#define ARG_RS1_RS2_RD { ARG_RS1, ARG_RS2, ARG_RD }
Definition at line 72 of file vm_sparc.c.
ARG_RS1_SIMM13_RD
#define ARG_RS1_SIMM13_RD { ARG_RS1, ARG_SIMM13, ARG_RD }
Definition at line 73 of file vm_sparc.c.
ARG_RS2
#define ARG_RS2 2
Definition at line 63 of file vm_sparc.c.
ARG_RS2_RD
#define ARG_RS2_RD { ARG_RS2, ARG_RD }
Definition at line 75 of file vm_sparc.c.
ARG_SIMM13
#define ARG_SIMM13 4
Definition at line 65 of file vm_sparc.c.
ARG_SWTRAP
#define ARG_SWTRAP 8
Definition at line 69 of file vm_sparc.c.
BFCC
#define BFCC (A, COND) FMT2(0,((A<<7)|(COND<<3)|0x6))
Definition at line 92 of file vm_sparc.c.
BICC
#define BICC (A, COND) FMT2(0,((A<<7)|(COND<<3)|0x2))
Definition at line 91 of file vm_sparc.c.
CALL_THUNK_INSN_OFFSET
#define CALL_THUNK_INSN_OFFSET 5
DIE
#define DIE (reason)
Value:
    do { \
        Com_Error(ERR_DROP, "vm_sparc compiler error: " reason); \
        exit(1); \
    } while(0)
Definition at line 37 of file vm_sparc.c.
DISP22
#define DISP22 (X) ((((X) >> 2) & 0x3fffff) << 0)
Definition at line 270 of file vm_sparc.c.
DISP30
#define DISP30 (X) ((((X) >> 2) & 0x3fffffff) << 0)
Definition at line 269 of file vm_sparc.c.
EMIT_FALSE_CONST
#define EMIT_FALSE_CONST (fp)
Value:
do {    int saved_i_count = (fp)->saved_icount;         \
    (fp)->saved_icount = (fp)->cached_const->i_count;   \
    dst_insn_append(fp);                    \
    (fp)->saved_icount = saved_i_count;         \
} while (0)
Definition at line 866 of file vm_sparc.c.
fFIRST
#define fFIRST (fp) ((fp)->fpr_pos - 1)
Definition at line 588 of file vm_sparc.c.
FMT1
#define FMT1 (op) ((op) << 30), OP_MASK
Definition at line 84 of file vm_sparc.c.
FMT2
#define FMT2 (op, op2) ((op) << 30)|((op2)<<22), (OP_MASK | OP2_MASK)
Definition at line 85 of file vm_sparc.c.
FMT3
#define FMT3 (op, op3) ((op) << 30)|((op3)<<19), (OP_MASK | OP3_MASK | IMM)
Definition at line 86 of file vm_sparc.c.
FMT3F
#define FMT3F (op, op3, opf)
Value:
                ((op) << 30)|((op3)<<19)|((opf)<<5), \
                (OP_MASK | OP3_MASK | OPF_MASK)
Definition at line 88 of file vm_sparc.c.
FMT3I
#define FMT3I (op, op3) ((op) << 30)|((op3)<<19)|IMM, (OP_MASK | OP3_MASK | IMM)
Definition at line 87 of file vm_sparc.c.
fSECOND
#define fSECOND (fp) ((fp)->fpr_pos - 2)
Definition at line 589 of file vm_sparc.c.
HUNK_SIZE
#define HUNK_SIZE 29
Definition at line 565 of file vm_sparc.c.
IMM
#define IMM 0x00002000
Definition at line 82 of file vm_sparc.c.
IMM22
#define IMM22 (X) (((X) & 0x3fffff) << 0)
Definition at line 268 of file vm_sparc.c.
IN
#define IN (inst, args...)
Value:
({  const int argv[] = { args }; \
    const int argc = ARRAY_LEN(argv); \
    sparc_assemble(inst, argc, argv); \
})
Definition at line 321 of file vm_sparc.c.
in
#define in (inst, args...) __do_emit_one(fp, IN(inst, args))
Definition at line 739 of file vm_sparc.c.
INSN_BUF_SIZE
#define INSN_BUF_SIZE 50
Definition at line 593 of file vm_sparc.c.
LDL
#define LDL SL(LDUW, LDX)
Definition at line 148 of file vm_sparc.c.
LDLI
#define LDLI SL(LDUWI, LDXI)
Definition at line 147 of file vm_sparc.c.
MAYBE_EMIT_CONST
#define MAYBE_EMIT_CONST (fp)
Value:
do {    if ((fp)->cached_const) {          \
        int saved_i_count = (fp)->saved_icount; \
        do_emit_const(fp, (fp)->cached_const); \
        (fp)->saved_icount = saved_i_count; \
    } \
} while (0)
Definition at line 858 of file vm_sparc.c.
OFFSET
#define OFFSET (structName, field) ((void *)&(((structName *)NULL)->field) - NULL)
Definition at line 521 of file vm_sparc.c.
OP2_MASK
#define OP2_MASK 0x01c00000
Definition at line 78 of file vm_sparc.c.
OP3_MASK
#define OP3_MASK 0x01f80000
Definition at line 79 of file vm_sparc.c.
OP_MASK
#define OP_MASK 0xc0000000
Definition at line 77 of file vm_sparc.c.
opArg0
#define opArg0 0x0000 /* requires nothing */
Definition at line 403 of file vm_sparc.c.
opArg2F
#define opArg2F 0x0080 /* requires second argument, float */
Definition at line 409 of file vm_sparc.c.
opArg2I
#define opArg2I 0x0040 /* requires second argument, integer */
Definition at line 408 of file vm_sparc.c.
opArg2IF
#define opArg2IF (opArg2I | opArg2F) /* requires second argument, integer or float */
Definition at line 410 of file vm_sparc.c.
opArgF
#define opArgF 0x0020 /* requires float(s) */
Definition at line 405 of file vm_sparc.c.
opArgI
#define opArgI 0x0010 /* requires integer(s) */
Definition at line 404 of file vm_sparc.c.
opArgIF
#define opArgIF (opArgI | opArgF) /* requires integer or float */
Definition at line 406 of file vm_sparc.c.
OPF_MASK
#define OPF_MASK 0x00003fe0
Definition at line 80 of file vm_sparc.c.
opImm0
#define opImm0 0x0000 /* no immediate */
Definition at line 394 of file vm_sparc.c.
opImm1
#define opImm1 0x0001 /* 1 byte immadiate value after opcode */
Definition at line 395 of file vm_sparc.c.
opImm4
#define opImm4 0x0002 /* 4 bytes immediate value after opcode */
Definition at line 396 of file vm_sparc.c.
opRet0
#define opRet0 0x0000 /* returns nothing */
Definition at line 398 of file vm_sparc.c.
opRetF
#define opRetF 0x0008 /* returns float */
Definition at line 400 of file vm_sparc.c.
opRetI
#define opRetI 0x0004 /* returns integer */
Definition at line 399 of file vm_sparc.c.
opRetIF
#define opRetIF (opRetI | opRetF) /* returns integer or float */
Definition at line 401 of file vm_sparc.c.
POP_FPR
#define POP_FPR (fp) ((fp)->fpr_pos--)
Definition at line 590 of file vm_sparc.c.
POP_GPR
#define POP_GPR (fp) ((fp)->gpr_pos--)
Definition at line 584 of file vm_sparc.c.
PUSH_FPR
#define PUSH_FPR (fp) ((fp)->fpr_pos++)
Definition at line 591 of file vm_sparc.c.
PUSH_GPR
#define PUSH_GPR (fp) ((fp)->gpr_pos++)
Definition at line 585 of file vm_sparc.c.
RD
#define RD (X) (((X) & 0x1f) << 25)
Definition at line 266 of file vm_sparc.c.
rDATABASE
#define rDATABASE G4
Definition at line 53 of file vm_sparc.c.
rDATAMASK
#define rDATAMASK G5
Definition at line 54 of file vm_sparc.c.
REG_FLAGS_FLOAT
#define REG_FLAGS_FLOAT 0x1
Definition at line 541 of file vm_sparc.c.
rFIRST
#define rFIRST (fp) ((fp)->gpr_pos - 1)
Definition at line 582 of file vm_sparc.c.
rPSTACK
#define rPSTACK G3
Definition at line 52 of file vm_sparc.c.
RS1
#define RS1 (X) (((X) & 0x1f) << 14)
Definition at line 264 of file vm_sparc.c.
RS2
#define RS2 (X) (((X) & 0x1f) << 0)
Definition at line 265 of file vm_sparc.c.
rSECOND
#define rSECOND (fp) ((fp)->gpr_pos - 2)
Definition at line 583 of file vm_sparc.c.
rTMP
#define rTMP G1
Definition at line 50 of file vm_sparc.c.
rVMDATA
#define rVMDATA G2
Definition at line 51 of file vm_sparc.c.
SIMM13
#define SIMM13 (X) (((X) & 0x1fff) << 0)
Definition at line 267 of file vm_sparc.c.
SIMM13_P
#define SIMM13_P (X) ((unsigned int) (X) + 0x1000 < 0x2000)
Definition at line 273 of file vm_sparc.c.
SL
#define SL (a, b) (a)
Definition at line 47 of file vm_sparc.c.
SPARC_NOP
#define SPARC_NOP 0x01000000
Definition at line 152 of file vm_sparc.c.
SPARC_NUM_OPCODES
#define SPARC_NUM_OPCODES (ARRAY_LEN(sparc_opcodes))
Definition at line 262 of file vm_sparc.c.
STL
#define STL SL(STW, STX)
Definition at line 150 of file vm_sparc.c.
STLI
#define STLI SL(STWI, STXI)
Definition at line 149 of file vm_sparc.c.
SWTRAP
#define SWTRAP (X) (((X) & 0x7f) << 0)
Definition at line 271 of file vm_sparc.c.
THUNK_ICOUNT
#define THUNK_ICOUNT -1
Definition at line 613 of file vm_sparc.c.
TICC
#define TICC (COND) FMT3I(0,((COND<<6)|0x3a))
Definition at line 93 of file vm_sparc.c.
VM_Data_Offset
#define VM_Data_Offset (field) OFFSET(vm_data_t, field)
Definition at line 523 of file vm_sparc.c.
Typedef Documentation
vm_data_t
typedef struct VM_Data vm_data_t
Enumeration Type Documentation
sparc_iname
enum sparc_iname
Enumerator
CALL
NOP
SETHI
BA
BN
BNE
BE
BG
BLE
BGE
BL
BGU
BLEU
BCC
BCS
BPOS
BNEG
BVC
BVS
ADDI
ADD
ANDI
AND
ORI
OR
XORI
XOR
SUBI
SUB
ANDNI
ANDN
ORNI
ORN
XNORI
XNOR
UMULI
UMUL
SMULI
SMUL
UDIVI
UDIV
SDIVI
SDIV
SUBCCI
SUBCC
SLLI
SLL
SRLI
SRL
SRAI
SRA
WRI
WR
SAVEI
SAVE
RESTOREI
RESTORE
TA
JMPLI
JMPL
LDXI
LDX
LDUWI
LDUW
LDUHI
LDUH
LDUBI
LDUB
STXI
STX
STWI
STW
STHI
STH
STBI
STB
LDFI
LDF
STFI
STF
FADD
FSUB
FCMP
FSTOI
FITOS
FNEG
FDIV
FMUL
FBE
FBNE
FBL
FBGE
FBG
FBLE
Definition at line 95 of file vm_sparc.c.
                  {
     CALL, NOP, SETHI,
     BA, BN, BNE, BE, BG, BLE, BGE, BL, BGU, BLEU, BCC, BCS,
     BPOS, BNEG, BVC, BVS,
     ADDI, ADD,
     ANDI, AND,
     ORI, OR,
     XORI, XOR,
     SUBI, SUB,
     ANDNI, ANDN,
     ORNI, ORN,
     XNORI, XNOR,
     UMULI, UMUL,
     SMULI, SMUL,
     UDIVI, UDIV,
     SDIVI, SDIV,
     SUBCCI, SUBCC,
     SLLI, SLL,
     SRLI, SRL,
     SRAI, SRA,
     WRI, WR,
     SAVEI, SAVE,
     RESTOREI, RESTORE,
     TA,
     JMPLI, JMPL,
     LDXI, LDX,
     LDUWI, LDUW,
     LDUHI, LDUH,
     LDUBI, LDUB,
     STXI, STX,
     STWI, STW,
     STHI, STH,
     STBI, STB,
     LDFI, LDF,
     STFI, STF,
     FADD, FSUB, FCMP, FSTOI, FITOS, FNEG, FDIV, FMUL,
     FBE, FBNE, FBL, FBGE, FBG, FBLE,
 };
Function Documentation
__do_emit_one()
static void __do_emit_one (struct func_info *const fp, unsigned int insn) static
Definition at line 734 of file vm_sparc.c.
 {
     fp->insn_buf[fp->insn_index++] = insn;
 }
References func_info::insn_buf, and func_info::insn_index.
analyze_function()
static void analyze_function (struct func_info *const fp) static
Definition at line 753 of file vm_sparc.c.
 {
     struct src_insn *value_provider[20] = { NULL };
     struct src_insn *sp = fp->first;
     int opstack_depth = 0;
     while ((sp = sp->next) != NULL) {
         unsigned char opi, op = sp->op;
         opi = vm_opInfo[op];
         if (opi & opArgIF) {
             struct src_insn *vp = value_provider[--opstack_depth];
             unsigned char vpopi = vm_opInfo[vp->op];
             if ((opi & opArgI) && (vpopi & opRetI)) {
                 /* src1 and dst are integers */
             } else if ((opi & opArgF) && (vpopi & opRetF)) {
                 /* src1 and dst are floats */
                 vp->dst_reg_flags |= REG_FLAGS_FLOAT;
                 sp->src1_reg_flags = REG_FLAGS_FLOAT;
             } else {
                 /* illegal combination */
                 DIE("unrecognized instruction combination");
             }
         }
         if (opi & opArg2IF) {
             struct src_insn *vp = value_provider[--opstack_depth];
             unsigned char vpopi = vm_opInfo[vp->op];
             if ((opi & opArg2I) && (vpopi & opRetI)) {
                 /* src2 and dst are integers */
             } else if ( (opi & opArg2F) && (vpopi & opRetF) ) {
                 /* src2 and dst are floats */
                 vp->dst_reg_flags |= REG_FLAGS_FLOAT;
                 sp->src2_reg_flags = REG_FLAGS_FLOAT;
             } else {
                 /* illegal combination */
                 DIE("unrecognized instruction combination");
             }
         }
         if (opi & opRetIF) {
             value_provider[opstack_depth] = sp;
             opstack_depth++;
         }
     }
 }
References DIE, src_insn::dst_reg_flags, func_info::first, src_insn::next, NULL, src_insn::op, opArg2F, opArg2I, opArg2IF, opArgF, opArgI, opArgIF, opRetF, opRetI, opRetIF, REG_FLAGS_FLOAT, src_insn::src1_reg_flags, src_insn::src2_reg_flags, and vm_opInfo.
Referenced by compile_function().
asmcall()
static int asmcall (int call, int pstack) static
Definition at line 800 of file vm_sparc.c.
 {
     vm_t *savedVM = currentVM;
     int i, ret;
     currentVM->programStack = pstack - 4;
     if (sizeof(intptr_t) == sizeof(int)) {
         intptr_t *argPosition = (intptr_t *)((byte *)currentVM->dataBase + pstack + 4);
         argPosition[0] = -1 - call;
         ret = currentVM->systemCall(argPosition);
     } else {
         intptr_t args[MAX_VMSYSCALL_ARGS];
         args[0] = -1 - call;
         int *argPosition = (int *)((byte *)currentVM->dataBase + pstack + 4);
         for( i = 1; i < ARRAY_LEN(args); i++ )
             args[i] = argPosition[i];
         ret = currentVM->systemCall(args);
     }
     currentVM = savedVM;
     return ret;
 }
References ARRAY_LEN, currentVM, vm_s::dataBase, src_insn::i, intptr_t(), MAX_VMSYSCALL_ARGS, vm_s::programStack, and vm_s::systemCall.
Referenced by sparc_compute_code().
blockcopy()
static void blockcopy (unsigned int dest, unsigned int src, unsigned int count) static
Definition at line 826 of file vm_sparc.c.
 {
     unsigned int dataMask = currentVM->dataMask;
     if ((dest & dataMask) != dest ||
         (src & dataMask) != src ||
         ((dest+count) & dataMask) != dest + count ||
         ((src+count) & dataMask) != src + count) {
         DIE("OP_BLOCK_COPY out of range!");
     }
     memcpy(currentVM->dataBase+dest, currentVM->dataBase+src, count);
 }
References count, currentVM, vm_s::dataBase, vm_s::dataMask, and DIE.
Referenced by sparc_compute_code().
compile_function()
static void compile_function (vm_t * vm, struct func_info *const fp) static
Definition at line 1368 of file vm_sparc.c.
 {
     struct src_insn *sp;
     analyze_function(fp);
     fp->gpr_pos = L0;
     fp->fpr_pos = F0;
     fp->insn_index = 0;
     fp->stack_space = SL(64, 128);
     fp->cached_const = NULL;
     sp = fp->first;
     while ((sp = sp->next) != NULL)
         compile_one_insn(vm, fp, sp);
     free_source_insns(fp);
 }
References analyze_function(), func_info::cached_const, compile_one_insn(), F0, func_info::first, func_info::fpr_pos, free_source_insns(), func_info::gpr_pos, func_info::insn_index, L0, src_insn::next, NULL, SL, and func_info::stack_space.
Referenced by VM_Compile().
compile_one_insn()
static void compile_one_insn (vm_t * vm, struct func_info *const fp, struct src_insn * sp) static
Definition at line 873 of file vm_sparc.c.
 {
     start_emit(fp, sp->i_count);
     switch (sp->op) {
     default:
         Com_Printf("VM: Unhandled opcode 0x%02x[%s]\n",
                sp->op,
                opnames[sp->op] ? opnames[sp->op] : "UNKNOWN");
         DIE("Unsupported opcode");
         break;
     case OP_ENTER: {
         int stack = SL(64, 128);
         if (fp->need_float_tmp)
             stack += 16;
         in(SAVEI, O6, -stack, O6);
         if (!SIMM13_P(sp->arg.si)) {
             in(SETHI, sp->arg.i >> 10, rTMP);
             in(ORI, rTMP, sp->arg.i & 0x3ff, rTMP);
             in(SUB, rPSTACK, rTMP, rPSTACK);
         } else
             in(SUBI, rPSTACK, sp->arg.si, rPSTACK);
         break;
     }
     case OP_LEAVE:
         if (fp->cached_const && SIMM13_P(fp->cached_const->arg.si)) {
             EMIT_FALSE_CONST(fp);
             if (fp->cached_const->src1_reg_flags & REG_FLAGS_FLOAT)
                 DIE("constant float in OP_LEAVE");
             if (!SIMM13_P(sp->arg.si)) {
                 in(SETHI, sp->arg.i >> 10, rTMP);
                 in(ORI, rTMP, sp->arg.i & 0x3ff, rTMP);
                 in(ADD, rPSTACK, rTMP, rPSTACK);
             } else
                 in(ADDI, rPSTACK, sp->arg.si, rPSTACK);
             in(JMPLI, I7, 8, G0);
             in(RESTOREI, G0, fp->cached_const->arg.si, O0);
             POP_GPR(fp);
         } else {
             MAYBE_EMIT_CONST(fp);
             if (!SIMM13_P(sp->arg.si)) {
                 in(SETHI, sp->arg.i >> 10, rTMP);
                 in(ORI, rTMP, sp->arg.i & 0x3ff, rTMP);
                 in(ADD, rPSTACK, rTMP, rPSTACK);
             } else
                 in(ADDI, rPSTACK, sp->arg.si, rPSTACK);
             if (sp->src1_reg_flags & REG_FLAGS_FLOAT) {
                 in(STFI, O6, SL(64, 128), fFIRST(fp));
                 in(LDUWI, O6, SL(64, 128), O0);
                 in(JMPLI, I7, 8, G0);
                 in(RESTORE, O0, G0, O0);
                 POP_FPR(fp);
             } else {
                 in(JMPLI, I7, 8, G0);
                 in(RESTORE, rFIRST(fp), G0, O0);
                 POP_GPR(fp);
             }
         }
         assert(fp->gpr_pos == L0);
         assert(fp->fpr_pos == F0);
         break;
     case OP_JUMP:
         if (fp->cached_const) {
             EMIT_FALSE_CONST(fp);
             emit_jump(vm, fp, BA, fp->cached_const->arg.i);
         } else {
             MAYBE_EMIT_CONST(fp);
             in(SETHI, vm->instructionCount >> 10, rTMP);
             in(ORI, rTMP, vm->instructionCount & 0x3ff, rTMP);
             in(SUBCC, rTMP, rFIRST(fp), G0);
             in(BLEU, +4*5);
             in(LDLI, rVMDATA, VM_Data_Offset(ErrJump), rTMP);
             in(SLLI, rFIRST(fp), 2, rFIRST(fp));
             in(LDLI, rVMDATA, VM_Data_Offset(iPointers), rTMP);
             in(LDL, rTMP, rFIRST(fp), rTMP);
             in(JMPL, rTMP, G0, G0);
             in(NOP);
         }
         POP_GPR(fp);
         break;
     case OP_CALL:
         if (fp->cached_const) {
             EMIT_FALSE_CONST(fp);
             if (fp->cached_const->arg.si >= 0) {
                 emit_jump(vm, fp, CALL, fp->cached_const->arg.i);
             } else {
                 in(LDLI, rVMDATA, VM_Data_Offset(CallThunk), rTMP);
                 in(LDLI, rVMDATA, VM_Data_Offset(AsmCall), O3);
                 in(ORI, G0, fp->cached_const->arg.si, O0);
                 in(JMPL, rTMP, G0, O7);
                 in(OR, G0, rPSTACK, O1);
             }
             in(OR, G0, O0, rFIRST(fp));
         } else {
             MAYBE_EMIT_CONST(fp);
             in(SUBCCI, rFIRST(fp), 0, G0);
             in(BL, +4*7);
             in(NOP);
             /* normal call */
             in(SETHI, vm->instructionCount >> 10, rTMP);
             in(ORI, rTMP, vm->instructionCount & 0x3ff, rTMP);
             in(SUBCC, rTMP, rFIRST(fp), G0);
             in(BLEU, +4*9);
             in(LDLI, rVMDATA, VM_Data_Offset(ErrJump), rTMP);
             in(LDLI, rVMDATA, VM_Data_Offset(iPointers), O5);
             in(SLLI, rFIRST(fp), 2, rFIRST(fp));
             in(LDL, O5, rFIRST(fp), rTMP);
             in(BA, +4*4);
             in(NOP);
             /* syscall */
             in(LDLI, rVMDATA, VM_Data_Offset(CallThunk), rTMP);
             in(LDLI, rVMDATA, VM_Data_Offset(AsmCall), O3);
             in(OR, G0, rFIRST(fp), O0);
             in(JMPL, rTMP, G0, O7);
             in(OR, G0, rPSTACK, O1);
             /* return value */
             in(OR, G0, O0, rFIRST(fp));
         }
         break;
     case OP_BLOCK_COPY:
         MAYBE_EMIT_CONST(fp);
         in(LDLI, rVMDATA, VM_Data_Offset(CallThunk), rTMP);
         in(LDLI, rVMDATA, VM_Data_Offset(BlockCopy), O3);
         in(OR, G0, rSECOND(fp), O0);
         in(OR, G0, rFIRST(fp), O1);
         if ((sp->arg.i & ~0x3ff) == 0) {
             in(ORI, G0, sp->arg.i & 0x3ff, O2);
         } else if ((sp->arg.i & 0x3ff) == 0) {
             in(SETHI, sp->arg.i >> 10, O2);
         } else {
             in(SETHI, sp->arg.i >> 10, O2);
             in(ORI, O2, sp->arg.i & 0x3ff, O2);
         }
         in(JMPL, rTMP, G0, O7);
         in(NOP);
         POP_GPR(fp);
         POP_GPR(fp);
         break;
     case OP_PUSH:
         MAYBE_EMIT_CONST(fp);
         if (sp->dst_reg_flags & REG_FLAGS_FLOAT)
             PUSH_FPR(fp);
         else
             PUSH_GPR(fp);
         fp->force_emit = 1;
         break;
     case OP_POP:
         MAYBE_EMIT_CONST(fp);
         if (sp->src1_reg_flags & REG_FLAGS_FLOAT)
             POP_FPR(fp);
         else
             POP_GPR(fp);
         fp->force_emit = 1;
         break;
     case OP_ARG:
         MAYBE_EMIT_CONST(fp);
         in(ADDI, rPSTACK, sp->arg.b, rTMP);
         if (sp->src1_reg_flags & REG_FLAGS_FLOAT) {
             in(STF, rDATABASE, rTMP, fFIRST(fp));
             POP_FPR(fp);
         } else {
             in(STW, rDATABASE, rTMP, rFIRST(fp));
             POP_GPR(fp);
         }
         break;
     case OP_IGNORE:
         MAYBE_EMIT_CONST(fp);
         in(NOP);
         break;
     case OP_BREAK:
         MAYBE_EMIT_CONST(fp);
         in(TA, 0x5);
         break;
     case OP_LOCAL:
         MAYBE_EMIT_CONST(fp);
         PUSH_GPR(fp);
         if (!SIMM13_P(sp->arg.i)) {
             in(SETHI, sp->arg.i >> 10, rTMP);
             in(ORI, rTMP, sp->arg.i & 0x3ff, rTMP);
             in(ADD, rPSTACK, rTMP, rFIRST(fp));
         } else
             in(ADDI, rPSTACK, sp->arg.i, rFIRST(fp));
         break;
     case OP_CONST:
         MAYBE_EMIT_CONST(fp);
         break;
     case OP_LOAD4:
         MAYBE_EMIT_CONST(fp);
         in(AND, rFIRST(fp), rDATAMASK, rFIRST(fp));
         if (sp->dst_reg_flags & REG_FLAGS_FLOAT) {
             PUSH_FPR(fp);
             in(LDF, rFIRST(fp), rDATABASE, fFIRST(fp));
             POP_GPR(fp);
         } else {
             in(LDUW, rFIRST(fp), rDATABASE, rFIRST(fp));
         }
         break;
     case OP_LOAD2:
         MAYBE_EMIT_CONST(fp);
         in(AND, rFIRST(fp), rDATAMASK, rFIRST(fp));
         in(LDUH, rFIRST(fp), rDATABASE, rFIRST(fp));
         break;
     case OP_LOAD1:
         MAYBE_EMIT_CONST(fp);
         in(AND, rFIRST(fp), rDATAMASK, rFIRST(fp));
         in(LDUB, rFIRST(fp), rDATABASE, rFIRST(fp));
         break;
     case OP_STORE4:
         MAYBE_EMIT_CONST(fp);
         if (sp->src1_reg_flags & REG_FLAGS_FLOAT) {
             in(AND, rFIRST(fp), rDATAMASK, rFIRST(fp));
             in(STF, rFIRST(fp), rDATABASE, fFIRST(fp));
             POP_FPR(fp);
         } else {
             in(AND, rSECOND(fp), rDATAMASK, rSECOND(fp));
             in(STW, rSECOND(fp), rDATABASE, rFIRST(fp));
             POP_GPR(fp);
         }
         POP_GPR(fp);
         break;
     case OP_STORE2:
         MAYBE_EMIT_CONST(fp);
         in(AND, rSECOND(fp), rDATAMASK, rSECOND(fp));
         in(STH, rSECOND(fp), rDATABASE, rFIRST(fp));
         POP_GPR(fp);
         POP_GPR(fp);
         break;
     case OP_STORE1:
         MAYBE_EMIT_CONST(fp);
         in(AND, rSECOND(fp), rDATAMASK, rSECOND(fp));
         in(STB, rSECOND(fp), rDATABASE, rFIRST(fp));
         POP_GPR(fp);
         POP_GPR(fp);
         break;
     case OP_EQ:
     case OP_NE:
     case OP_LTI:
     case OP_GEI:
     case OP_GTI:
     case OP_LEI:
     case OP_LTU:
     case OP_GEU:
     case OP_GTU:
     case OP_LEU: {
         enum sparc_iname iname = BA;
         if (fp->cached_const && SIMM13_P(fp->cached_const->arg.si)) {
             EMIT_FALSE_CONST(fp);
             in(SUBCCI, rSECOND(fp), fp->cached_const->arg.si, G0);
         } else {
             MAYBE_EMIT_CONST(fp);
             in(SUBCC, rSECOND(fp), rFIRST(fp), G0);
         }
         switch(sp->op) {
         case OP_EQ: iname = BE; break;
         case OP_NE: iname = BNE; break;
         case OP_LTI: iname = BL; break;
         case OP_GEI: iname = BGE; break;
         case OP_GTI: iname = BG; break;
         case OP_LEI: iname = BLE; break;
         case OP_LTU: iname = BCS; break;
         case OP_GEU: iname = BCC; break;
         case OP_GTU: iname = BGU; break;
         case OP_LEU: iname = BLEU; break;
         }
         emit_jump(vm, fp, iname, sp->arg.i);
         POP_GPR(fp);
         POP_GPR(fp);
         break;
     }
     case OP_SEX8:
         MAYBE_EMIT_CONST(fp);
         in(SLLI, rFIRST(fp), 24, rFIRST(fp));
         in(SRAI, rFIRST(fp), 24, rFIRST(fp));
         break;
     case OP_SEX16:
         MAYBE_EMIT_CONST(fp);
         in(SLLI, rFIRST(fp), 16, rFIRST(fp));
         in(SRAI, rFIRST(fp), 16, rFIRST(fp));
         break;
     case OP_NEGI:
         MAYBE_EMIT_CONST(fp);
         in(SUB, G0, rFIRST(fp), rFIRST(fp));
         break;
     case OP_ADD:
         if (fp->cached_const && SIMM13_P(fp->cached_const->arg.si)) {
             EMIT_FALSE_CONST(fp);
             in(ADDI, rSECOND(fp), fp->cached_const->arg.si, rSECOND(fp));
         } else {
             MAYBE_EMIT_CONST(fp);
             in(ADD, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         }
         POP_GPR(fp);
         break;
     case OP_SUB:
         if (fp->cached_const && SIMM13_P(fp->cached_const->arg.si)) {
             EMIT_FALSE_CONST(fp);
             in(SUBI, rSECOND(fp), fp->cached_const->arg.si, rSECOND(fp));
         } else {
             MAYBE_EMIT_CONST(fp);
             in(SUB, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         }
         POP_GPR(fp);
         break;
     case OP_DIVI:
         MAYBE_EMIT_CONST(fp);
         in(SRAI, rSECOND(fp), 31, rTMP);
         in(WRI, rTMP, 0, Y_REG);
         in(SDIV, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_DIVU:
         MAYBE_EMIT_CONST(fp);
         in(WRI, G0, 0, Y_REG);
         in(UDIV, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_MODI:
         MAYBE_EMIT_CONST(fp);
         in(SRAI, rSECOND(fp), 31, rTMP);
         in(WRI, rTMP, 0, Y_REG);
         in(SDIV, rSECOND(fp), rFIRST(fp), rTMP);
         in(SMUL, rTMP, rFIRST(fp), rTMP);
         in(SUB, rSECOND(fp), rTMP, rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_MODU:
         MAYBE_EMIT_CONST(fp);
         in(WRI, G0, 0, Y_REG);
         in(UDIV, rSECOND(fp), rFIRST(fp), rTMP);
         in(SMUL, rTMP, rFIRST(fp), rTMP);
         in(SUB, rSECOND(fp), rTMP, rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_MULI:
         MAYBE_EMIT_CONST(fp);
         in(SMUL, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_MULU:
         MAYBE_EMIT_CONST(fp);
         in(UMUL, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_BAND:
         MAYBE_EMIT_CONST(fp);
         in(AND, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_BOR:
         MAYBE_EMIT_CONST(fp);
         in(OR, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_BXOR:
         MAYBE_EMIT_CONST(fp);
         in(XOR, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         POP_GPR(fp);
         break;
     case OP_BCOM:
         MAYBE_EMIT_CONST(fp);
         in(XNOR, rFIRST(fp), G0, rFIRST(fp));
         break;
     case OP_LSH:
         if (fp->cached_const) {
             EMIT_FALSE_CONST(fp);
             in(SLLI, rSECOND(fp), fp->cached_const->arg.si, rSECOND(fp));
         } else {
             MAYBE_EMIT_CONST(fp);
             in(SLL, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         }
         POP_GPR(fp);
         break;
     case OP_RSHI:
         if (fp->cached_const) {
             EMIT_FALSE_CONST(fp);
             in(SRAI, rSECOND(fp), fp->cached_const->arg.si, rSECOND(fp));
         } else {
             MAYBE_EMIT_CONST(fp);
             in(SRA, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         }
         POP_GPR(fp);
         break;
     case OP_RSHU:
         if (fp->cached_const) {
             EMIT_FALSE_CONST(fp);
             in(SRLI, rSECOND(fp), fp->cached_const->arg.si, rSECOND(fp));
         } else {
             MAYBE_EMIT_CONST(fp);
             in(SRL, rSECOND(fp), rFIRST(fp), rSECOND(fp));
         }
         POP_GPR(fp);
         break;
     case OP_NEGF:
         MAYBE_EMIT_CONST(fp);
         in(FNEG, fFIRST(fp), fFIRST(fp));
         break;
     case OP_ADDF:
         MAYBE_EMIT_CONST(fp);
         in(FADD, fSECOND(fp), fFIRST(fp), fSECOND(fp));
         POP_FPR(fp);
         break;
     case OP_SUBF:
         MAYBE_EMIT_CONST(fp);
         in(FSUB, fSECOND(fp), fFIRST(fp), fSECOND(fp));
         POP_FPR(fp);
         break;
     case OP_DIVF:
         MAYBE_EMIT_CONST(fp);
         in(FDIV, fSECOND(fp), fFIRST(fp), fSECOND(fp));
         POP_FPR(fp);
         break;
     case OP_MULF:
         MAYBE_EMIT_CONST(fp);
         in(FMUL, fSECOND(fp), fFIRST(fp), fSECOND(fp));
         POP_FPR(fp);
         break;
     case OP_EQF:
     case OP_NEF:
     case OP_LTF:
     case OP_GEF:
     case OP_GTF:
     case OP_LEF: {
         enum sparc_iname iname = FBE;
         MAYBE_EMIT_CONST(fp);
         in(FCMP, fSECOND(fp), fFIRST(fp));
         switch(sp->op) {
         case OP_EQF: iname = FBE; break;
         case OP_NEF: iname = FBNE; break;
         case OP_LTF: iname = FBL; break;
         case OP_GEF: iname = FBGE; break;
         case OP_GTF: iname = FBG; break;
         case OP_LEF: iname = FBLE; break;
         }
         emit_jump(vm, fp, iname, sp->arg.i);
         POP_FPR(fp);
         POP_FPR(fp);
         break;
     }
     case OP_CVIF:
         MAYBE_EMIT_CONST(fp);
         PUSH_FPR(fp);
         in(STWI, O6, SL(64, 128), rFIRST(fp));
         in(LDFI, O6, SL(64, 128), fFIRST(fp));
         in(FITOS, fFIRST(fp), fFIRST(fp));
         POP_GPR(fp);
         break;
     case OP_CVFI:
         MAYBE_EMIT_CONST(fp);
         PUSH_GPR(fp);
         in(FSTOI, fFIRST(fp), fFIRST(fp));
         in(STFI, O6, SL(64, 128), fFIRST(fp));
         in(LDUWI, O6, SL(64, 128), rFIRST(fp));
         POP_FPR(fp);
         break;
     }
     if (sp->op != OP_CONST) {
         fp->cached_const = NULL;
         end_emit(fp);
     } else {
         fp->cached_const = sp;
         if (sp->dst_reg_flags & REG_FLAGS_FLOAT) {
             PUSH_FPR(fp);
         } else {
             PUSH_GPR(fp);
         }
     }
     end_emit(fp);
 }
References ADD, ADDI, AND, src_insn::arg, src_insn::b, BA, BCC, BCS, BE, BG, BGE, BGU, BL, BLE, BLEU, BNE, func_info::cached_const, CALL, Com_Printf(), DIE, src_insn::dst_reg_flags, EMIT_FALSE_CONST, emit_jump(), end_emit(), ErrJump(), F0, FADD, FBE, FBG, FBGE, FBL, FBLE, FBNE, FCMP, FDIV, fFIRST, FITOS, FMUL, FNEG, func_info::force_emit, func_info::fpr_pos, fSECOND, FSTOI, FSUB, G0, func_info::gpr_pos, src_insn::i, I7, src_insn::i_count, in, vm_s::instructionCount, JMPL, JMPLI, L0, LDF, LDFI, LDL, LDLI, LDUB, LDUH, LDUW, LDUWI, MAYBE_EMIT_CONST, func_info::need_float_tmp, NOP, NULL, O0, O1, O2, O3, O5, O6, O7, src_insn::op, OP_ADD, OP_ADDF, OP_ARG, OP_BAND, OP_BCOM, OP_BLOCK_COPY, OP_BOR, OP_BREAK, OP_BXOR, OP_CALL, OP_CONST, OP_CVFI, OP_CVIF, OP_DIVF, OP_DIVI, OP_DIVU, OP_ENTER, OP_EQ, OP_EQF, OP_GEF, OP_GEI, OP_GEU, OP_GTF, OP_GTI, OP_GTU, OP_IGNORE, OP_JUMP, OP_LEAVE, OP_LEF, OP_LEI, OP_LEU, OP_LOAD1, OP_LOAD2, OP_LOAD4, OP_LOCAL, OP_LSH, OP_LTF, OP_LTI, OP_LTU, OP_MODI, OP_MODU, OP_MULF, OP_MULI, OP_MULU, OP_NE, OP_NEF, OP_NEGF, OP_NEGI, OP_POP, OP_PUSH, OP_RSHI, OP_RSHU, OP_SEX16, OP_SEX8, OP_STORE1, OP_STORE2, OP_STORE4, OP_SUB, OP_SUBF, opnames, OR, ORI, POP_FPR, POP_GPR, PUSH_FPR, PUSH_GPR, rDATABASE, rDATAMASK, REG_FLAGS_FLOAT, RESTORE, RESTOREI, rFIRST, rPSTACK, rSECOND, rTMP, rVMDATA, SAVEI, SDIV, SETHI, src_insn::si, SIMM13_P, SL, SLL, SLLI, SMUL, SRA, SRAI, src_insn::src1_reg_flags, SRL, SRLI, start_emit(), STB, STF, STFI, STH, STW, STWI, SUB, SUBCC, SUBCCI, SUBI, TA, UDIV, UMUL, VM_Data_Offset, WRI, XNOR, XOR, and Y_REG.
Referenced by compile_function().
do_emit_const()
static void do_emit_const (struct func_info *const fp, struct src_insn * sp) static
Definition at line 840 of file vm_sparc.c.
 {
     start_emit(fp, sp->i_count);
     if (sp->dst_reg_flags & REG_FLAGS_FLOAT) {
         in(LDFI, rVMDATA, sparc_push_data(fp, sp->arg.i), fFIRST(fp));
     } else {
         if ((sp->arg.i & ~0x3ff) == 0) {
             in(ORI, G0, sp->arg.i & 0x3ff, rFIRST(fp));
         } else if ((sp->arg.i & 0x3ff) == 0) {
             in(SETHI, sp->arg.i >> 10, rFIRST(fp));
         } else {
             in(SETHI, sp->arg.i >> 10, rFIRST(fp));
             in(ORI, rFIRST(fp), sp->arg.i & 0x3ff, rFIRST(fp));
         }
     }
     end_emit(fp);
 }
References src_insn::arg, src_insn::dst_reg_flags, end_emit(), fFIRST, G0, src_insn::i, src_insn::i_count, in, LDFI, ORI, REG_FLAGS_FLOAT, rFIRST, rVMDATA, SETHI, sparc_push_data(), and start_emit().
dst_insn_append()
static void dst_insn_append (struct func_info *const fp) static
Definition at line 689 of file vm_sparc.c.
 {
     int insns_size = (sizeof(unsigned int) * fp->insn_index);
     struct dst_insn *dp;
     dp = dst_new(fp, fp->insn_index, NULL, insns_size);
     if (insns_size)
         memcpy(&dp->code[0], fp->insn_buf, insns_size);
     dst_insn_insert_tail(fp, dp);
     fp->insn_index = 0;
 }
References dst_insn::code, dst_insn_insert_tail(), dst_new(), func_info::insn_buf, func_info::insn_index, int(), and NULL.
Referenced by end_emit().
dst_insn_insert_tail()
static void dst_insn_insert_tail (struct func_info *const fp, struct dst_insn * dp) static
Definition at line 651 of file vm_sparc.c.
 {
     if (!fp->dst_first) {
         fp->dst_first = fp->dst_last = dp;
     } else {
         fp->dst_last->next = dp;
         fp->dst_last = dp;
     }
 }
References func_info::dst_first, func_info::dst_last, and dst_insn::next.
Referenced by dst_insn_append(), and jump_insn_append().
dst_new()
static struct dst_insn* dst_new (struct func_info *const fp, unsigned int length, struct jump_insn * jp, int insns_size) static
Definition at line 673 of file vm_sparc.c.
 {
     struct dst_insn *dp = Z_Malloc(sizeof(struct dst_insn) + insns_size);
     dp->length = length;
     dp->jump = jp;
     dp->count = fp->dst_count++;
     dp->i_count = fp->saved_icount;
     dp->next = NULL;
     if (fp->saved_icount != THUNK_ICOUNT)
         fp->dst_by_i_count[fp->saved_icount] = dp;
     return dp;
 }
References dst_insn::count, func_info::dst_by_i_count, func_info::dst_count, dst_insn::i_count, dst_insn::jump, dst_insn::length, dst_insn::next, NULL, func_info::saved_icount, THUNK_ICOUNT, and Z_Malloc.
Referenced by dst_insn_append(), and jump_insn_append().
emit_jump()
static void emit_jump (vm_t * vm, struct func_info *const fp, enum sparc_iname iname, int dest) static
Definition at line 747 of file vm_sparc.c.
 {
     end_emit(fp);
     jump_insn_append(vm, fp, iname, dest);
 }
References end_emit(), and jump_insn_append().
Referenced by compile_one_insn().
emit_vm_thunk()
static void emit_vm_thunk (struct func_info *const fp) static
Definition at line 1393 of file vm_sparc.c.
 {
     /* int vm_thunk(void *vmdata, int programstack, void *database, int datamask) */
     start_emit(fp, THUNK_ICOUNT);
     in(OR, G0, O0, rVMDATA);
     in(OR, G0, O1, rPSTACK);
     in(OR, G0, O2, rDATABASE);
     in(BA, +4*17);
     in(OR, G0, O3, rDATAMASK);
     /* int call_thunk(int arg0, int arg1, int arg2, int (*func)(int int int)) */
 #define CALL_THUNK_INSN_OFFSET      5
     in(SAVEI, O6, -SL(64, 128), O6);
     in(OR, G0, rVMDATA, L0);
     in(OR, G0, rPSTACK, L1);
     in(OR, G0, rDATABASE, L2);
     in(OR, G0, rDATAMASK, L3);
     in(OR, G0, I0, O0);
     in(OR, G0, I1, O1);
     in(JMPL, I3, G0, O7);
     in(OR, G0, I2, O2);
     in(OR, G0, L0, rVMDATA);
     in(OR, G0, L1, rPSTACK);
     in(OR, G0, L2, rDATABASE);
     in(OR, G0, L3, rDATAMASK);
     in(JMPLI, I7, 8, G0);
     in(RESTORE, O0, G0, O0);
     end_emit(fp);
 }
References BA, end_emit(), G0, I0, I1, I2, I3, I7, in, JMPL, JMPLI, L0, L1, L2, L3, O0, O1, O2, O3, O6, O7, OR, rDATABASE, rDATAMASK, RESTORE, rPSTACK, rVMDATA, SAVEI, SL, start_emit(), and THUNK_ICOUNT.
Referenced by VM_Compile().
end_emit()
static void end_emit (struct func_info *const fp) static
Definition at line 741 of file vm_sparc.c.
 {
     if (fp->insn_index || fp->force_emit)
         dst_insn_append(fp);
 }
References dst_insn_append(), func_info::force_emit, and func_info::insn_index.
Referenced by compile_one_insn(), do_emit_const(), emit_jump(), and emit_vm_thunk().
ErrJump()
static void ErrJump (void) static
Definition at line 702 of file vm_sparc.c.
 {
     Com_Error(ERR_DROP, "program tried to execute code outside VM");
     exit(1);
 }
References Com_Error(), and ERR_DROP.
Referenced by compile_one_insn(), DoSyscall(), jump_insn_append(), and sparc_compute_code().
free_source_insns()
static void free_source_insns (struct func_info *const fp) static
Definition at line 1357 of file vm_sparc.c.
 {
     struct src_insn *sp = fp->first->next;
     while (sp) {
         struct src_insn *next = sp->next;
         Z_Free(sp);
         sp = next;
     }
 }
References func_info::first, src_insn::next, and Z_Free().
Referenced by compile_function().
jump_insn_append()
static void jump_insn_append (vm_t * vm, struct func_info *const fp, enum sparc_iname iname, int dest) static
Definition at line 708 of file vm_sparc.c.
 {
     struct jump_insn *jp = Z_Malloc(sizeof(*jp));
     struct dst_insn *dp;
     if (dest < 0 || dest >= vm->instructionCount)
         ErrJump();
     dp = dst_new(fp, 2, jp, 0);
     jp->jump_iname = iname;
     jp->jump_dest_insn = dest;
     jp->parent = dp;
     jp->next = NULL;
     jump_insn_insert_tail(fp, jp);
     dst_insn_insert_tail(fp, dp);
 }
References dst_insn_insert_tail(), dst_new(), ErrJump(), vm_s::instructionCount, jump_insn::jump_dest_insn, jump_insn::jump_iname, jump_insn_insert_tail(), jump_insn::next, NULL, jump_insn::parent, and Z_Malloc.
Referenced by emit_jump().
jump_insn_insert_tail()
static void jump_insn_insert_tail (struct func_info *const fp, struct jump_insn * jp) static
Definition at line 662 of file vm_sparc.c.
 {
     if (!fp->jump_first) {
         fp->jump_first = fp->jump_last = jp;
     } else {
         fp->jump_last->next = jp;
         fp->jump_last = jp;
     }
 }
References func_info::jump_first, func_info::jump_last, and jump_insn::next.
Referenced by jump_insn_append().
sparc_assemble()
static unsigned int sparc_assemble (enum sparc_iname iname, const int argc, const int * argv) static
Definition at line 294 of file vm_sparc.c.
 {
     const struct sparc_opcode *op = &sparc_opcodes[iname];
     unsigned int insn = op->opcode;
     int i, flt, rd_flt;
     flt = (op->name[0] == 'f');
     rd_flt = flt || (op->name[2] == 'f');
     for (i = 0; op->args[i] != ARG_NONE; i++) {
         int val = argv[i];
         switch (op->args[i]) {
         case ARG_RS1: insn |= RS1(val); break;
         case ARG_RS2: insn |= RS2(val); break;
         case ARG_RD:  insn |= RD(val); break;
         case ARG_SIMM13: insn |= SIMM13(val); vimm(val,13,0,1,i); break;
         case ARG_DISP30: insn |= DISP30(val); vimm(val,30,0,1,i); break;
         case ARG_IMM22: insn |= IMM22(val); vimm(val,22,0,0,i); break;
         case ARG_DISP22: insn |= DISP22(val); vimm(val,22,0,1,i); break;
         case ARG_SWTRAP: insn |= SWTRAP(val); vimm(val,7,0,0,i); break;
         }
     }
     return insn;
 }
References ARG_DISP22, ARG_DISP30, ARG_IMM22, ARG_NONE, ARG_RD, ARG_RS1, ARG_RS2, ARG_SIMM13, ARG_SWTRAP, sparc_opcode::args, DISP22, DISP30, IMM22, sparc_opcode::name, sparc_opcode::opcode, RD, RS1, RS2, SIMM13, sparc_opcodes, SWTRAP, and vimm().
sparc_compute_code()
static void sparc_compute_code (vm_t * vm, struct func_info *const fp) static
Definition at line 1429 of file vm_sparc.c.
 {
     struct dst_insn *dp = fp->dst_first;
     unsigned int *code_now, *code_begin;
     unsigned char *data_and_code;
     unsigned int code_length;
     int code_insns = 0, off;
     struct data_hunk *dhp;
     struct jump_insn *jp;
     vm_data_t *data;
     while (dp) {
         code_insns += dp->length;
         dp = dp->next;
     }
     code_length = (sizeof(vm_data_t) +
                (fp->data_num * sizeof(unsigned int)) +
                (code_insns * sizeof(unsigned int)));
     data_and_code = mmap(NULL, code_length, PROT_READ | PROT_WRITE,
                  MAP_SHARED | MAP_ANONYMOUS, -1, 0);
     if (data_and_code == MAP_FAILED)
         DIE("Not enough memory");
     code_now = code_begin = (unsigned int *)
         (data_and_code + VM_Data_Offset(data[fp->data_num]));
     dp = fp->dst_first;
     while (dp) {
         int i_count = dp->i_count;
         if (i_count != THUNK_ICOUNT) {
             if (!fp->dst_by_i_count[i_count])
                 fp->dst_by_i_count[i_count] = (void *) code_now;
         }
         if (!dp->jump) {
             memcpy(code_now, &dp->code[0], dp->length * sizeof(unsigned int));
             code_now += dp->length;
         } else {
             int i;
             dp->jump->parent = (void *) code_now;
             for (i = 0; i < dp->length; i++)
                 code_now[i] = SPARC_NOP;
             code_now += dp->length;
         }
         dp = dp->next;
     }
     jp = fp->jump_first;
     while (jp) {
         unsigned int *from = (void *) jp->parent;
         unsigned int *to = (void *) fp->dst_by_i_count[jp->jump_dest_insn];
         signed int disp = (to - from);
         *from = IN(jp->jump_iname, disp << 2);
         jp = jp->next;
     }
     vm->codeBase = data_and_code;
     vm->codeLength = code_length;
     data = (vm_data_t *) data_and_code;
     data->CallThunk = code_begin + CALL_THUNK_INSN_OFFSET;
     data->AsmCall = asmcall;
     data->BlockCopy = blockcopy;
     data->iPointers = (unsigned int *) vm->instructionPointers;
     data->dataLength = VM_Data_Offset(data[fp->data_num]);
     data->codeLength = (code_now - code_begin) * sizeof(unsigned int);
     data->ErrJump = ErrJump;
 #if 0
     {
         unsigned int *insn = code_begin;
         int i;
         Com_Printf("INSN DUMP\n");
         for (i = 0; i < data->codeLength / 4; i+= 8) {
             Com_Printf("\t.word\t0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x, 0x%08x\n",
                    insn[i + 0], insn[i + 1],
                    insn[i + 2], insn[i + 3],
                    insn[i + 4], insn[i + 5],
                    insn[i + 6], insn[i + 7]);
         }
     }
 #endif
     dhp = fp->data_first;
     off = 0;
     while (dhp) {
         struct data_hunk *next = dhp->next;
         int i;
         for (i = 0; i < dhp->count; i++)
             data->data[off + i] = dhp->data[i];
         off += dhp->count;
         Z_Free(dhp);
         dhp = next;
     }
     fp->data_first = NULL;
     fp->data_num = 0;
     dp = fp->dst_first;
     while (dp) {
         struct dst_insn *next = dp->next;
         if (dp->jump)
             Z_Free(dp->jump);
         Z_Free(dp);
         dp = next;
     }
     fp->dst_first = fp->dst_last = NULL;
 }
References VM_Data::AsmCall, asmcall(), VM_Data::BlockCopy, blockcopy(), CALL_THUNK_INSN_OFFSET, VM_Data::CallThunk, dst_insn::code, vm_s::codeBase, vm_s::codeLength, VM_Data::codeLength, Com_Printf(), data_hunk::count, data_hunk::data, func_info::data_first, func_info::data_num, VM_Data::dataLength, DIE, func_info::dst_by_i_count, func_info::dst_first, func_info::dst_last, VM_Data::ErrJump, ErrJump(), dst_insn::i_count, IN, vm_s::instructionPointers, VM_Data::iPointers, dst_insn::jump, jump_insn::jump_dest_insn, func_info::jump_first, jump_insn::jump_iname, dst_insn::length, MAP_ANONYMOUS, jump_insn::next, dst_insn::next, data_hunk::next, NULL, jump_insn::parent, SPARC_NOP, THUNK_ICOUNT, VM_Data_Offset, and Z_Free().
Referenced by VM_Compile().
sparc_push_data()
static unsigned int sparc_push_data (struct func_info *const fp, unsigned int val) static
Definition at line 615 of file vm_sparc.c.
 {
     struct data_hunk *last, *dp = fp->data_first;
     int off = 0;
     last = NULL;
     while (dp) {
         int i;
         for (i = 0; i < dp->count; i++) {
             if (dp->data[i] == val) {
                 off += i;
                 return VM_Data_Offset(data[off]);
             }
         }
         off += dp->count;
         last = dp;
         dp = dp->next;
     }
     dp = last;
     if (!dp || dp->count >= HUNK_SIZE) {
         struct data_hunk *new = Z_Malloc(sizeof(*new));
         if (!dp)
             fp->data_first = new;
         else
             dp->next = new;
         dp = new;
         dp->count = 0;
         dp->next = NULL;
     }
     dp->data[dp->count++] = val;
     fp->data_num = off + 1;
     return VM_Data_Offset(data[off]);
 }
References data_hunk::count, data_hunk::data, func_info::data_first, func_info::data_num, HUNK_SIZE, data_hunk::next, NULL, VM_Data_Offset, and Z_Malloc.
Referenced by do_emit_const().
start_emit()
static void start_emit (struct func_info *const fp, int i_count) static
Definition at line 727 of file vm_sparc.c.
 {
     fp->saved_icount = i_count;
     fp->insn_index = 0;
     fp->force_emit = 0;
 }
References func_info::force_emit, dst_insn::i_count, func_info::insn_index, and func_info::saved_icount.
Referenced by compile_one_insn(), do_emit_const(), and emit_vm_thunk().
vimm()
static void vimm (unsigned int val, int bits, int shift, int sgned, int arg_index) static
Definition at line 275 of file vm_sparc.c.
 {
     unsigned int orig_val = val;
     int orig_bits = bits;
     if (sgned) {
         int x = (int) val;
         if (x < 0)
             x = -x;
         val = (unsigned int) x;
         bits--;
     }
     if (val & ~((1U << bits) - 1U)) {
         Com_Printf("VM ERROR: immediate value 0x%08x out of %d bit range\n",
                orig_val, orig_bits);
         DIE("sparc VM bug");
     }
 }
References bits(), Com_Printf(), DIE, and int().
Referenced by sparc_assemble().
VM_CallCompiled()
int VM_CallCompiled (vm_t * vm, int * args)
Definition at line 1640 of file vm_sparc.c.
 {
     vm_data_t *vm_dataAndCode = (void *) vm->codeBase;
     int programStack = vm->programStack;
     int stackOnEntry = programStack;
     byte *image = vm->dataBase;
     int *argPointer;
     int retVal;
     currentVM = vm;
     vm->currentlyInterpreting = qtrue;
     programStack -= ( 8 + 4 * MAX_VMMAIN_ARGS );
     argPointer = (int *)&image[ programStack + 8 ];
     memcpy( argPointer, args, 4 * MAX_VMMAIN_ARGS );
     argPointer[-1] = 0;
     argPointer[-2] = -1;
     /* call generated code */
     {
         int (*entry)(void *, int, void *, int);
         entry = (void *)(vm->codeBase + vm_dataAndCode->dataLength);
         retVal = entry(vm->codeBase, programStack, vm->dataBase, vm->dataMask);
     }
     vm->programStack = stackOnEntry;
     vm->currentlyInterpreting = qfalse;
     return retVal;
 }
References vm_s::codeBase, vm_s::currentlyInterpreting, currentVM, vm_s::dataBase, VM_Data::dataLength, vm_s::dataMask, int(), MAX_VMMAIN_ARGS, vm_s::programStack, qfalse, and qtrue.
VM_Compile()
void VM_Compile (vm_t * vm, vmHeader_t * header)
Definition at line 1549 of file vm_sparc.c.
 {
     struct func_info fi;
     unsigned char *code;
     int i_count, pc, i;
     memset(&fi, 0, sizeof(fi));
     fi.first = Z_Malloc(sizeof(struct src_insn));
     fi.first->next = NULL;
 #ifdef __arch64__
     Z_Free(vm->instructionPointers);
     vm->instructionPointers = Z_Malloc(header->instructionCount *
                        sizeof(void *));
 #endif
     fi.dst_by_i_count = (struct dst_insn **) vm->instructionPointers;
     memset(fi.dst_by_i_count, 0, header->instructionCount * sizeof(void *));
     vm->compiled = qfalse;
     emit_vm_thunk(&fi);
     code = (unsigned char *) header + header->codeOffset;
     pc = 0;
     for (i_count = 0; i_count < header->instructionCount; i_count++) {
         unsigned char opi, op = code[pc++];
         struct src_insn *sp;
         if (op == OP_CALL || op == OP_BLOCK_COPY)
             fi.has_call = 1;
         opi = vm_opInfo[op];
         if (op == OP_CVIF || op == OP_CVFI ||
             (op == OP_LEAVE && (opi & opArgF)))
             fi.need_float_tmp = 1;
         if (op == OP_ENTER) {
             if (fi.first->next)
                 compile_function(vm, &fi);
             fi.first->next = NULL;
             fi.last = fi.first;
             fi.has_call = fi.need_float_tmp = 0;
         }
         sp = Z_Malloc(sizeof(*sp));
         sp->op = op;
         sp->i_count = i_count;
         sp->arg.i = 0;
         sp->next = NULL;
         if (vm_opInfo[op] & opImm4) {
             union {
                 unsigned char b[4];
                 unsigned int i;
             } c = { { code[ pc + 3 ], code[ pc + 2 ],
                   code[ pc + 1 ], code[ pc + 0 ] }, };
             sp->arg.i = c.i;
             pc += 4;
         } else if (vm_opInfo[op] & opImm1) {
             sp->arg.b = code[pc++];
         }
         fi.last->next = sp;
         fi.last = sp;
     }
     compile_function(vm, &fi);
     Z_Free(fi.first);
     memset(fi.dst_by_i_count, 0, header->instructionCount * sizeof(void *));
     sparc_compute_code(vm, &fi);
     for (i = 0; i < header->instructionCount; i++) {
         if (!fi.dst_by_i_count[i]) {
             Com_Printf(S_COLOR_RED "Pointer %d not initialized !\n", i);
             DIE("sparc JIT bug");
         }
     }
     if (mprotect(vm->codeBase, vm->codeLength, PROT_READ|PROT_EXEC)) {
         VM_Destroy_Compiled(vm);
         DIE("mprotect failed");
     }
     vm->destroy = VM_Destroy_Compiled;
     vm->compiled = qtrue;
 }
References src_insn::arg, src_insn::b, code, vm_s::codeBase, vm_s::codeLength, vmHeader_t::codeOffset, Com_Printf(), compile_function(), vm_s::compiled, vm_s::destroy, DIE, func_info::dst_by_i_count, emit_vm_thunk(), func_info::first, func_info::has_call, src_insn::i, src_insn::i_count, dst_insn::i_count, vmHeader_t::instructionCount, vm_s::instructionPointers, func_info::last, func_info::need_float_tmp, src_insn::next, NULL, src_insn::op, OP_BLOCK_COPY, OP_CALL, OP_CVFI, OP_CVIF, OP_ENTER, OP_LEAVE, opArgF, opImm1, opImm4, pc, qfalse, qtrue, S_COLOR_RED, sparc_compute_code(), VM_Destroy_Compiled(), vm_opInfo, Z_Free(), and Z_Malloc.
VM_Destroy_Compiled()
static void VM_Destroy_Compiled (vm_t * vm) static
Definition at line 498 of file vm_sparc.c.
 {
     if (vm->codeBase) {
         if (munmap(vm->codeBase, vm->codeLength))
             Com_Printf(S_COLOR_RED "Memory unmap failed, possible memory leak\n");
     }
     vm->codeBase = NULL;
 }
References vm_s::codeBase, vm_s::codeLength, Com_Printf(), NULL, and S_COLOR_RED.
Referenced by VM_Compile().
Variable Documentation
opnames
const char* opnames[256] static
Initial value:
= {
    "OP_UNDEF", "OP_IGNORE", "OP_BREAK", "OP_ENTER", "OP_LEAVE", "OP_CALL",
    "OP_PUSH", "OP_POP", "OP_CONST", "OP_LOCAL", "OP_JUMP",
    "OP_EQ", "OP_NE", "OP_LTI", "OP_LEI", "OP_GTI", "OP_GEI",
    "OP_LTU", "OP_LEU", "OP_GTU", "OP_GEU", "OP_EQF", "OP_NEF",
    "OP_LTF", "OP_LEF", "OP_GTF", "OP_GEF",
    "OP_LOAD1", "OP_LOAD2", "OP_LOAD4", "OP_STORE1", "OP_STORE2",
    "OP_STORE4", "OP_ARG", "OP_BLOCK_COPY",
    "OP_SEX8", "OP_SEX16",
    "OP_NEGI", "OP_ADD", "OP_SUB", "OP_DIVI", "OP_DIVU",
    "OP_MODI", "OP_MODU", "OP_MULI", "OP_MULU", "OP_BAND",
    "OP_BOR", "OP_BXOR", "OP_BCOM", "OP_LSH", "OP_RSHI", "OP_RSHU",
    "OP_NEGF", "OP_ADDF", "OP_SUBF", "OP_DIVF", "OP_MULF",
    "OP_CVIF", "OP_CVFI",
}
Definition at line 482 of file vm_sparc.c.
Referenced by compile_one_insn(), VM_CallInterpreted(), and VM_Compile().
sparc_opcodes
const struct sparc_opcode sparc_opcodes[] static
Definition at line 154 of file vm_sparc.c.
Referenced by sparc_assemble().
vm_opInfo
const unsigned char vm_opInfo[256] static
Definition at line 412 of file vm_sparc.c.
Referenced by analyze_function(), and VM_Compile().