ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_qmenu.c File Reference
ui_qmenu.c File Reference
#include "ui_local.h"
Functions
static void Action_Init (menuaction_s *a)
static void Action_Draw (menuaction_s *a)
static void RadioButton_Init (menuradiobutton_s *rb)
static void RadioButton_Draw (menuradiobutton_s *rb)
static sfxHandle_t RadioButton_Key (menuradiobutton_s *rb, int key)
static void Slider_Init (menuslider_s *s)
static sfxHandle_t Slider_Key (menuslider_s *s, int key)
static void Slider_Draw (menuslider_s *s)
static void SpinControl_Init (menulist_s *s)
static void SpinControl_Draw (menulist_s *s)
static sfxHandle_t SpinControl_Key (menulist_s *l, int key)
static void Text_Init (menutext_s *b)
static void Text_Draw (menutext_s *b)
static void ScrollList_Init (menulist_s *l)
sfxHandle_t ScrollList_Key (menulist_s *l, int key)
static void PText_Init (menutext_s *b)
static void PText_Draw (menutext_s *b)
static void BText_Init (menutext_s *b)
static void BText_Draw (menutext_s *b)
void Bitmap_Init (menubitmap_s *b)
void Bitmap_Draw (menubitmap_s *b)
void ScrollList_Draw (menulist_s *l)
void Menu_AddItem (menuframework_s *menu, void *item)
void Menu_CursorMoved (menuframework_s *m)
void Menu_SetCursor (menuframework_s *m, int cursor)
void Menu_SetCursorToItem (menuframework_s *m, void *ptr)
void Menu_AdjustCursor (menuframework_s *m, int dir)
void Menu_Draw (menuframework_s *menu)
void * Menu_ItemAtCursor (menuframework_s *m)
sfxHandle_t Menu_ActivateItem (menuframework_s *s, menucommon_s *item)
sfxHandle_t Menu_DefaultKey (menuframework_s *m, int key)
void Menu_Cache (void)
Variables
sfxHandle_t menu_in_sound
sfxHandle_t menu_move_sound
sfxHandle_t menu_out_sound
sfxHandle_t menu_buzz_sound
sfxHandle_t menu_null_sound
sfxHandle_t weaponChangeSound
static qhandle_t sliderBar
static qhandle_t sliderButton_0
static qhandle_t sliderButton_1
vec4_t menu_text_color = {1.0f, 1.0f, 1.0f, 1.0f}
vec4_t menu_dim_color = {0.0f, 0.0f, 0.0f, 0.75f}
vec4_t color_black = {0.00f, 0.00f, 0.00f, 1.00f}
vec4_t color_white = {1.00f, 1.00f, 1.00f, 1.00f}
vec4_t color_yellow = {1.00f, 1.00f, 0.00f, 1.00f}
vec4_t color_blue = {0.00f, 0.00f, 1.00f, 1.00f}
vec4_t color_lightOrange = {1.00f, 0.68f, 0.00f, 1.00f }
vec4_t color_orange = {1.00f, 0.43f, 0.00f, 1.00f}
vec4_t color_red = {1.00f, 0.00f, 0.00f, 1.00f}
vec4_t color_dim = {0.00f, 0.00f, 0.00f, 0.25f}
vec4_t pulse_color = {1.00f, 1.00f, 1.00f, 1.00f}
vec4_t text_color_disabled = {0.50f, 0.50f, 0.50f, 1.00f}
vec4_t text_color_normal = {1.00f, 0.43f, 0.00f, 1.00f}
vec4_t text_color_highlight = {1.00f, 1.00f, 0.00f, 1.00f}
vec4_t listbar_color = {1.00f, 0.43f, 0.00f, 0.30f}
vec4_t text_color_status = {1.00f, 1.00f, 1.00f, 1.00f}
Function Documentation
Action_Draw()
static void Action_Draw (menuaction_s * a) static
Definition at line 390 of file ui_qmenu.c.
 {
     int     x, y;
     int     style;
     float*  color;
     style = 0;
     color = menu_text_color;
     if ( a->generic.flags & QMF_GRAYED )
     {
         color = text_color_disabled;
     }
     else if (( a->generic.flags & QMF_PULSEIFFOCUS ) && ( a->generic.parent->cursor == a->generic.menuPosition ))
     {
         color = text_color_highlight;
         style = UI_PULSE;
     }
     else if (( a->generic.flags & QMF_HIGHLIGHT_IF_FOCUS ) && ( a->generic.parent->cursor == a->generic.menuPosition ))
     {
         color = text_color_highlight;
     }
     else if ( a->generic.flags & QMF_BLINK )
     {
         style = UI_BLINK;
         color = text_color_highlight;
     }
     x = a->generic.x;
     y = a->generic.y;
     UI_DrawString( x, y, a->generic.name, UI_LEFT|style, color );
     if ( a->generic.parent->cursor == a->generic.menuPosition )
     {
         // draw cursor
         UI_DrawChar( x - BIGCHAR_WIDTH, y, 13, UI_LEFT|UI_BLINK, color);
     }
 }
References a, BIGCHAR_WIDTH, menu_text_color, QMF_BLINK, QMF_GRAYED, QMF_HIGHLIGHT_IF_FOCUS, QMF_PULSEIFFOCUS, text_color_disabled, text_color_highlight, UI_BLINK, UI_DrawChar(), UI_DrawString(), UI_LEFT, and UI_PULSE.
Referenced by Menu_Draw().
Action_Init()
static void Action_Init (menuaction_s * a) static
Definition at line 368 of file ui_qmenu.c.
 {
     int len;
     // calculate bounds
     if (a->generic.name)
         len = strlen(a->generic.name);
     else
         len = 0;
     // left justify text
     a->generic.left   = a->generic.x;
     a->generic.right  = a->generic.x + len*BIGCHAR_WIDTH;
     a->generic.top    = a->generic.y;
     a->generic.bottom = a->generic.y + BIGCHAR_HEIGHT;
 }
References a, BIGCHAR_HEIGHT, and BIGCHAR_WIDTH.
Referenced by Menu_AddItem().
Bitmap_Draw()
void Bitmap_Draw (menubitmap_s * b)
Definition at line 282 of file ui_qmenu.c.
 {
     float   x;
     float   y;
     float   w;
     float   h;
     vec4_t  tempcolor;
     float*  color;
     x = b->generic.x;
     y = b->generic.y;
     w = b->width;
     h = b->height;
     if (b->generic.flags & QMF_RIGHT_JUSTIFY)
     {
         x = x - w;
     }
     else if (b->generic.flags & QMF_CENTER_JUSTIFY)
     {
         x = x - w/2;
     }
     // used to refresh shader
     if (b->generic.name && !b->shader)
     {
         b->shader = trap_R_RegisterShaderNoMip( b->generic.name );
         if (!b->shader && b->errorpic)
             b->shader = trap_R_RegisterShaderNoMip( b->errorpic );
     }
     if (b->focuspic && !b->focusshader)
         b->focusshader = trap_R_RegisterShaderNoMip( b->focuspic );
     if (b->generic.flags & QMF_GRAYED)
     {
         if (b->shader)
         {
             trap_R_SetColor( colorMdGrey );
             UI_DrawHandlePic( x, y, w, h, b->shader );
             trap_R_SetColor( NULL );
         }
     }
     else
     {
         if (b->shader)
             UI_DrawHandlePic( x, y, w, h, b->shader );
         if (  ( (b->generic.flags & QMF_PULSE)
             || (b->generic.flags & QMF_PULSEIFFOCUS) )
               && (Menu_ItemAtCursor( b->generic.parent ) == b))
         {
             if (b->focuscolor)
             {
                 tempcolor[0] = b->focuscolor[0];
                 tempcolor[1] = b->focuscolor[1];
                 tempcolor[2] = b->focuscolor[2];
                 color        = tempcolor;
             }
             else
                 color = pulse_color;
             color[3] = 0.5+0.5*sin(uis.realtime/PULSE_DIVISOR);
             trap_R_SetColor( color );
             UI_DrawHandlePic( x, y, w, h, b->focusshader );
             trap_R_SetColor( NULL );
         }
         else if ((b->generic.flags & QMF_HIGHLIGHT) || ((b->generic.flags & QMF_HIGHLIGHT_IF_FOCUS) && (Menu_ItemAtCursor( b->generic.parent ) == b)))
         {
             if (b->focuscolor)
             {
                 trap_R_SetColor( b->focuscolor );
                 UI_DrawHandlePic( x, y, w, h, b->focusshader );
                 trap_R_SetColor( NULL );
             }
             else
                 UI_DrawHandlePic( x, y, w, h, b->focusshader );
         }
     }
 }
References colorMdGrey, menubitmap_s::errorpic, menucommon_s::flags, menubitmap_s::focuscolor, menubitmap_s::focuspic, menubitmap_s::focusshader, menubitmap_s::generic, menubitmap_s::height, Menu_ItemAtCursor(), menucommon_s::name, NULL, menucommon_s::parent, pulse_color, PULSE_DIVISOR, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_HIGHLIGHT, QMF_HIGHLIGHT_IF_FOCUS, QMF_PULSE, QMF_PULSEIFFOCUS, QMF_RIGHT_JUSTIFY, uiStatic_t::realtime, menubitmap_s::shader, trap_R_RegisterShaderNoMip(), trap_R_SetColor(), UI_DrawHandlePic(), uis, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_Draw(), and ServerOptions_LevelshotDraw().
Bitmap_Init()
void Bitmap_Init (menubitmap_s * b)
Definition at line 241 of file ui_qmenu.c.
 {
     int x;
     int y;
     int w;
     int h;
     x = b->generic.x;
     y = b->generic.y;
     w = b->width;
     h = b->height;
     if( w < 0 ) {
         w = -w;
     }
     if( h < 0 ) {
         h = -h;
     }
     if (b->generic.flags & QMF_RIGHT_JUSTIFY)
     {
         x = x - w;
     }
     else if (b->generic.flags & QMF_CENTER_JUSTIFY)
     {
         x = x - w/2;
     }
     b->generic.left   = x;
     b->generic.right  = x + w;
     b->generic.top    = y;
     b->generic.bottom = y + h;
     b->shader      = 0;
     b->focusshader = 0;
 }
References menucommon_s::bottom, menucommon_s::flags, menubitmap_s::focusshader, menubitmap_s::generic, menubitmap_s::height, menucommon_s::left, QMF_CENTER_JUSTIFY, QMF_RIGHT_JUSTIFY, menucommon_s::right, menubitmap_s::shader, menucommon_s::top, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_AddItem(), and UI_SPLevelMenu_SetMenuItems().
BText_Draw()
static void BText_Draw (menutext_s * b) static
Definition at line 153 of file ui_qmenu.c.
 {
     int     x;
     int     y;
     float*  color;
     x = t->generic.x;
     y = t->generic.y;
     if (t->generic.flags & QMF_GRAYED)
         color = text_color_disabled;
     else
         color = t->color;
     UI_DrawBannerString( x, y, t->string, t->style, color );
 }
References QMF_GRAYED, t, text_color_disabled, and UI_DrawBannerString().
Referenced by Menu_Draw().
BText_Init()
static void BText_Init (menutext_s * b) static
Definition at line 143 of file ui_qmenu.c.
 {
     t->generic.flags |= QMF_INACTIVE;
 }
References QMF_INACTIVE, and t.
Referenced by Menu_AddItem().
Menu_ActivateItem()
sfxHandle_t Menu_ActivateItem (menuframework_s * s, menucommon_s * item)
Definition at line 1598 of file ui_qmenu.c.
{
     if ( item->callback ) {
         item->callback( item, QM_ACTIVATED );
         if( !( item->flags & QMF_SILENT ) ) {
             return menu_move_sound;
         }
     }
     return 0;
 }
References menucommon_s::callback, menucommon_s::flags, menu_move_sound, QM_ACTIVATED, and QMF_SILENT.
Referenced by Menu_DefaultKey().
Menu_AddItem()
void Menu_AddItem (menuframework_s * menu, void * item)
Definition at line 1297 of file ui_qmenu.c.
 {
     menucommon_s    *itemptr;
     if (menu->nitems >= MAX_MENUITEMS)
         trap_Error ("Menu_AddItem: excessive items");
     menu->items[menu->nitems] = item;
     ((menucommon_s*)menu->items[menu->nitems])->parent        = menu;
     ((menucommon_s*)menu->items[menu->nitems])->menuPosition  = menu->nitems;
     ((menucommon_s*)menu->items[menu->nitems])->flags        &= ~QMF_HASMOUSEFOCUS;
     // perform any item specific initializations
     itemptr = (menucommon_s*)item;
     if (!(itemptr->flags & QMF_NODEFAULTINIT))
     {
         switch (itemptr->type)
         {
             case MTYPE_ACTION:
                 Action_Init((menuaction_s*)item);
                 break;
             case MTYPE_FIELD:
                 MenuField_Init((menufield_s*)item);
                 break;
             case MTYPE_SPINCONTROL:
                 SpinControl_Init((menulist_s*)item);
                 break;
             case MTYPE_RADIOBUTTON:
                 RadioButton_Init((menuradiobutton_s*)item);
                 break;
             case MTYPE_SLIDER:
                 Slider_Init((menuslider_s*)item);
                 break;
             case MTYPE_BITMAP:
                 Bitmap_Init((menubitmap_s*)item);
                 break;
             case MTYPE_TEXT:
                 Text_Init((menutext_s*)item);
                 break;
             case MTYPE_SCROLLLIST:
                 ScrollList_Init((menulist_s*)item);
                 break;
             case MTYPE_PTEXT:
                 PText_Init((menutext_s*)item);
                 break;
             case MTYPE_BTEXT:
                 BText_Init((menutext_s*)item);
                 break;
             default:
                 trap_Error( va("Menu_Init: unknown type %d", itemptr->type) );
         }
     }
     menu->nitems++;
 }
References Action_Init(), Bitmap_Init(), BText_Init(), menucommon_s::flags, _tag_menuframework::items, MAX_MENUITEMS, MenuField_Init(), MTYPE_ACTION, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_PTEXT, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, MTYPE_TEXT, _tag_menuframework::nitems, PText_Init(), QMF_HASMOUSEFOCUS, QMF_NODEFAULTINIT, RadioButton_Init(), ScrollList_Init(), Slider_Init(), SpinControl_Init(), Text_Init(), trap_Error(), menucommon_s::type, and va().
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), Demos_MenuInit(), GraphicsOptions_MenuInit(), InGame_MenuInit(), LoadConfig_MenuInit(), Login_MenuInit(), Options_MenuInit(), PlayerModel_MenuInit(), PlayerSettings_MenuInit(), Preferences_MenuInit(), Rankings_MenuInit(), RankStatus_MenuInit(), ServerOptions_MenuInit(), Signup_MenuInit(), SpecifyLeague_MenuInit(), SpecifyServer_MenuInit(), StartServer_MenuInit(), TeamMain_MenuInit(), UI_AddBotsMenu_Init(), UI_BotSelectMenu_Init(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Init(), UI_ConfirmMenu_Style(), UI_DisplayOptionsMenu_Init(), UI_DrawConnectScreen(), UI_DriverInfo_Menu(), UI_MainMenu(), UI_Message(), UI_Mods_MenuInit(), UI_NetworkOptionsMenu_Init(), UI_RemoveBotsMenu_Init(), UI_ResetMenu(), UI_SaveConfigMenu_Init(), UI_ServerInfoMenu(), UI_SetupMenu_Init(), UI_SoundOptionsMenu_Init(), UI_SPLevelMenu_Init(), UI_SPPostgameMenu_Init(), UI_SPSkillMenu_Init(), and UI_TeamOrdersMenu_Init().
Menu_AdjustCursor()
void Menu_AdjustCursor (menuframework_s * m, int dir)
Definition at line 1435 of file ui_qmenu.c.
{
     menucommon_s    *item = NULL;
     qboolean        wrapped = qfalse;
 wrap:
     while ( m->cursor >= 0 && m->cursor < m->nitems ) {
         item = ( menucommon_s * ) m->items[m->cursor];
         if (( item->flags & (QMF_GRAYED|QMF_MOUSEONLY|QMF_INACTIVE) ) ) {
             m->cursor += dir;
         }
         else {
             break;
         }
     }
     if ( dir == 1 ) {
         if ( m->cursor >= m->nitems ) {
             if ( m->wrapAround ) {
                 if ( wrapped ) {
                     m->cursor = m->cursor_prev;
                     return;
                 }
                 m->cursor = 0;
                 wrapped = qtrue;
                 goto wrap;
             }
             m->cursor = m->cursor_prev;
         }
     }
     else {
         if ( m->cursor < 0 ) {
             if ( m->wrapAround ) {
                 if ( wrapped ) {
                     m->cursor = m->cursor_prev;
                     return;
                 }
                 m->cursor = m->nitems - 1;
                 wrapped = qtrue;
                 goto wrap;
             }
             m->cursor = m->cursor_prev;
         }
     }
 }
References menucommon_s::flags, m, NULL, qfalse, QMF_GRAYED, QMF_INACTIVE, QMF_MOUSEONLY, and qtrue.
Referenced by Menu_DefaultKey().
Menu_Cache()
void Menu_Cache (void)
Definition at line 1745 of file ui_qmenu.c.
 {
     uis.charset         = trap_R_RegisterShaderNoMip( "gfx/2d/bigchars" );
     uis.charsetProp     = trap_R_RegisterShaderNoMip( "menu/art/font1_prop.tga" );
     uis.charsetPropGlow = trap_R_RegisterShaderNoMip( "menu/art/font1_prop_glo.tga" );
     uis.charsetPropB    = trap_R_RegisterShaderNoMip( "menu/art/font2_prop.tga" );
     uis.cursor          = trap_R_RegisterShaderNoMip( "menu/art/3_cursor2" );
     uis.rb_on           = trap_R_RegisterShaderNoMip( "menu/art/switch_on" );
     uis.rb_off          = trap_R_RegisterShaderNoMip( "menu/art/switch_off" );
     uis.whiteShader = trap_R_RegisterShaderNoMip( "white" );
     if ( uis.glconfig.hardwareType == GLHW_RAGEPRO ) {
         // the blend effect turns to shit with the normal
         uis.menuBackShader  = trap_R_RegisterShaderNoMip( "menubackRagePro" );
     } else {
         uis.menuBackShader  = trap_R_RegisterShaderNoMip( "menuback" );
     }
     uis.menuBackNoLogoShader = trap_R_RegisterShaderNoMip( "menubacknologo" );
     menu_in_sound   = trap_S_RegisterSound( "sound/misc/menu1.wav", qfalse );
     menu_move_sound = trap_S_RegisterSound( "sound/misc/menu2.wav", qfalse );
     menu_out_sound  = trap_S_RegisterSound( "sound/misc/menu3.wav", qfalse );
     menu_buzz_sound = trap_S_RegisterSound( "sound/misc/menu4.wav", qfalse );
     weaponChangeSound   = trap_S_RegisterSound( "sound/weapons/change.wav", qfalse );
     // need a nonzero sound, make an empty sound for this
     menu_null_sound = -1;
     sliderBar = trap_R_RegisterShaderNoMip( "menu/art/slider2" );
     sliderButton_0 = trap_R_RegisterShaderNoMip( "menu/art/sliderbutt_0" );
     sliderButton_1 = trap_R_RegisterShaderNoMip( "menu/art/sliderbutt_1" );
 }
References uiStatic_t::charset, uiStatic_t::charsetProp, uiStatic_t::charsetPropB, uiStatic_t::charsetPropGlow, uiStatic_t::cursor, uiStatic_t::glconfig, GLHW_RAGEPRO, glconfig_t::hardwareType, menu_buzz_sound, menu_in_sound, menu_move_sound, menu_null_sound, menu_out_sound, uiStatic_t::menuBackNoLogoShader, uiStatic_t::menuBackShader, qfalse, uiStatic_t::rb_off, uiStatic_t::rb_on, sliderBar, sliderButton_0, sliderButton_1, trap_R_RegisterShaderNoMip(), trap_S_RegisterSound(), uis, weaponChangeSound, and uiStatic_t::whiteShader.
Referenced by UI_ConsoleCommand(), UI_DrawConnectScreen(), UI_Init(), and UI_SetActiveMenu().
Menu_CursorMoved()
void Menu_CursorMoved (menuframework_s * m)
Definition at line 1368 of file ui_qmenu.c.
 {
     void (*callback)( void *self, int notification );
     if (m->cursor_prev == m->cursor)
         return;
     if (m->cursor_prev >= 0 && m->cursor_prev < m->nitems)
     {
         callback = ((menucommon_s*)(m->items[m->cursor_prev]))->callback;
         if (callback)
             callback(m->items[m->cursor_prev],QM_LOSTFOCUS);
     }
     if (m->cursor >= 0 && m->cursor < m->nitems)
     {
         callback = ((menucommon_s*)(m->items[m->cursor]))->callback;
         if (callback)
             callback(m->items[m->cursor],QM_GOTFOCUS);
     }
 }
References m, QM_GOTFOCUS, QM_LOSTFOCUS, and void().
Referenced by Menu_DefaultKey(), and Menu_SetCursor().
Menu_DefaultKey()
sfxHandle_t Menu_DefaultKey (menuframework_s * m, int key)
Definition at line 1614 of file ui_qmenu.c.
 {
     sfxHandle_t     sound = 0;
     menucommon_s    *item;
     int             cursor_prev;
     // menu system keys
     switch ( key )
     {
         case K_MOUSE2:
         case K_ESCAPE:
             UI_PopMenu();
             return menu_out_sound;
     }
     if (!m || !m->nitems)
         return 0;
     // route key stimulus to widget
     item = Menu_ItemAtCursor( m );
     if (item && !(item->flags & (QMF_GRAYED|QMF_INACTIVE)))
     {
         switch (item->type)
         {
             case MTYPE_SPINCONTROL:
                 sound = SpinControl_Key( (menulist_s*)item, key );
                 break;
             case MTYPE_RADIOBUTTON:
                 sound = RadioButton_Key( (menuradiobutton_s*)item, key );
                 break;
             case MTYPE_SLIDER:
                 sound = Slider_Key( (menuslider_s*)item, key );
                 break;
             case MTYPE_SCROLLLIST:
                 sound = ScrollList_Key( (menulist_s*)item, key );
                 break;
             case MTYPE_FIELD:
                 sound = MenuField_Key( (menufield_s*)item, &key );
                 break;
         }
         if (sound) {
             // key was handled
             return sound;
         }
     }
     // default handling
     switch ( key )
     {
 #ifndef NDEBUG
         case K_F11:
             uis.debug ^= 1;
             break;
         case K_F12:
             trap_Cmd_ExecuteText(EXEC_APPEND, "screenshot\n");
             break;
 #endif
         case K_KP_UPARROW:
         case K_UPARROW:
             cursor_prev    = m->cursor;
             m->cursor_prev = m->cursor;
             m->cursor--;
             Menu_AdjustCursor( m, -1 );
             if ( cursor_prev != m->cursor ) {
                 Menu_CursorMoved( m );
                 sound = menu_move_sound;
             }
             break;
         case K_TAB:
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
             cursor_prev    = m->cursor;
             m->cursor_prev = m->cursor;
             m->cursor++;
             Menu_AdjustCursor( m, 1 );
             if ( cursor_prev != m->cursor ) {
                 Menu_CursorMoved( m );
                 sound = menu_move_sound;
             }
             break;
         case K_MOUSE1:
         case K_MOUSE3:
             if (item)
                 if ((item->flags & QMF_HASMOUSEFOCUS) && !(item->flags & (QMF_GRAYED|QMF_INACTIVE)))
                     return (Menu_ActivateItem( m, item ));
             break;
         case K_JOY1:
         case K_JOY2:
         case K_JOY3:
         case K_JOY4:
         case K_AUX1:
         case K_AUX2:
         case K_AUX3:
         case K_AUX4:
         case K_AUX5:
         case K_AUX6:
         case K_AUX7:
         case K_AUX8:
         case K_AUX9:
         case K_AUX10:
         case K_AUX11:
         case K_AUX12:
         case K_AUX13:
         case K_AUX14:
         case K_AUX15:
         case K_AUX16:
         case K_KP_ENTER:
         case K_ENTER:
             if (item)
                 if (!(item->flags & (QMF_MOUSEONLY|QMF_GRAYED|QMF_INACTIVE)))
                     return (Menu_ActivateItem( m, item ));
             break;
     }
     return sound;
 }
References uiStatic_t::debug, EXEC_APPEND, menucommon_s::flags, K_AUX1, K_AUX10, K_AUX11, K_AUX12, K_AUX13, K_AUX14, K_AUX15, K_AUX16, K_AUX2, K_AUX3, K_AUX4, K_AUX5, K_AUX6, K_AUX7, K_AUX8, K_AUX9, K_DOWNARROW, K_ENTER, K_ESCAPE, K_F11, K_F12, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_DOWNARROW, K_KP_ENTER, K_KP_UPARROW, K_MOUSE1, K_MOUSE2, K_MOUSE3, K_TAB, K_UPARROW, m, Menu_ActivateItem(), Menu_AdjustCursor(), Menu_CursorMoved(), Menu_ItemAtCursor(), menu_move_sound, menu_out_sound, MenuField_Key(), MTYPE_FIELD, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, QMF_GRAYED, QMF_HASMOUSEFOCUS, QMF_INACTIVE, QMF_MOUSEONLY, RadioButton_Key(), ScrollList_Key(), Slider_Key(), SpinControl_Key(), trap_Cmd_ExecuteText(), menucommon_s::type, UI_PopMenu(), and uis.
Referenced by ArenaServers_MenuKey(), ConfirmMenu_Key(), Controls_MenuKey(), PlayerModel_MenuKey(), PlayerSettings_MenuKey(), Reset_MenuKey(), ServerInfo_MenuKey(), UI_KeyEvent(), UI_SPPostgameMenu_MenuKey(), UI_SPSkillMenu_Key(), and UI_TeamOrdersMenu_Key().
Menu_Draw()
void Menu_Draw (menuframework_s * menu)
Definition at line 1485 of file ui_qmenu.c.
 {
     int             i;
     menucommon_s    *itemptr;
     // draw menu
     for (i=0; i<menu->nitems; i++)
     {
         itemptr = (menucommon_s*)menu->items[i];
         if (itemptr->flags & QMF_HIDDEN)
             continue;
         if (itemptr->ownerdraw)
         {
             // total subclassing, owner draws everything
             itemptr->ownerdraw( itemptr );
         }
         else
         {
             switch (itemptr->type)
             {
                 case MTYPE_RADIOBUTTON:
                     RadioButton_Draw( (menuradiobutton_s*)itemptr );
                     break;
                 case MTYPE_FIELD:
                     MenuField_Draw( (menufield_s*)itemptr );
                     break;
                 case MTYPE_SLIDER:
                     Slider_Draw( (menuslider_s*)itemptr );
                     break;
                 case MTYPE_SPINCONTROL:
                     SpinControl_Draw( (menulist_s*)itemptr );
                     break;
                 case MTYPE_ACTION:
                     Action_Draw( (menuaction_s*)itemptr );
                     break;
                 case MTYPE_BITMAP:
                     Bitmap_Draw( (menubitmap_s*)itemptr );
                     break;
                 case MTYPE_TEXT:
                     Text_Draw( (menutext_s*)itemptr );
                     break;
                 case MTYPE_SCROLLLIST:
                     ScrollList_Draw( (menulist_s*)itemptr );
                     break;
                 case MTYPE_PTEXT:
                     PText_Draw( (menutext_s*)itemptr );
                     break;
                 case MTYPE_BTEXT:
                     BText_Draw( (menutext_s*)itemptr );
                     break;
                 default:
                     trap_Error( va("Menu_Draw: unknown type %d", itemptr->type) );
             }
         }
 #ifndef NDEBUG
         if( uis.debug ) {
             int x;
             int y;
             int w;
             int h;
             if( !( itemptr->flags & QMF_INACTIVE ) ) {
                 x = itemptr->left;
                 y = itemptr->top;
                 w = itemptr->right - itemptr->left + 1;
                 h = itemptr->bottom - itemptr->top + 1;
                 if (itemptr->flags & QMF_HASMOUSEFOCUS) {
                     UI_DrawRect(x, y, w, h, colorYellow );
                 }
                 else {
                     UI_DrawRect(x, y, w, h, colorWhite );
                 }
             }
         }
 #endif
     }
     itemptr = Menu_ItemAtCursor( menu );
     if ( itemptr && itemptr->statusbar)
         itemptr->statusbar( ( void * ) itemptr );
 }
References Action_Draw(), Bitmap_Draw(), menucommon_s::bottom, BText_Draw(), colorWhite, colorYellow, uiStatic_t::debug, menucommon_s::flags, _tag_menuframework::items, menucommon_s::left, Menu_ItemAtCursor(), MenuField_Draw(), MTYPE_ACTION, MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_FIELD, MTYPE_PTEXT, MTYPE_RADIOBUTTON, MTYPE_SCROLLLIST, MTYPE_SLIDER, MTYPE_SPINCONTROL, MTYPE_TEXT, _tag_menuframework::nitems, menucommon_s::ownerdraw, PText_Draw(), QMF_HASMOUSEFOCUS, QMF_HIDDEN, QMF_INACTIVE, RadioButton_Draw(), menucommon_s::right, ScrollList_Draw(), Slider_Draw(), SpinControl_Draw(), menucommon_s::statusbar, Text_Draw(), menucommon_s::top, trap_Error(), menucommon_s::type, UI_DrawRect(), uis, and va().
Referenced by ArenaServers_MenuDraw(), ConfirmMenu_Draw(), DriverInfo_MenuDraw(), GraphicsOptions_MenuDraw(), Main_MenuDraw(), MessageMenu_Draw(), Reset_MenuDraw(), ServerInfo_MenuDraw(), SoundOptions_MenuDraw(), UI_Refresh(), UI_SPLevelMenu_MenuDraw(), and UI_SPPostgameMenu_MenuDraw().
Menu_ItemAtCursor()
void* Menu_ItemAtCursor (menuframework_s * m)
Definition at line 1585 of file ui_qmenu.c.
 {
     if ( m->cursor < 0 || m->cursor >= m->nitems )
         return NULL;
     return m->items[m->cursor];
 }
References m, and NULL.
Referenced by ArenaServers_MenuKey(), Bitmap_Draw(), Controls_DrawKeyBinding(), Menu_DefaultKey(), Menu_Draw(), MenuField_Draw(), PlayerModel_MenuKey(), PText_Draw(), UI_SaveConfigMenu_SavenameDraw(), UI_SPLevelMenu_MenuDraw(), and UI_TeamOrdersMenu_Key().
Menu_SetCursor()
void Menu_SetCursor (menuframework_s * m, int cursor)
Definition at line 1395 of file ui_qmenu.c.
 {
     if (((menucommon_s*)(m->items[cursor]))->flags & (QMF_GRAYED|QMF_INACTIVE))
     {
         // cursor can't go there
         return;
     }
     m->cursor_prev = m->cursor;
     m->cursor      = cursor;
     Menu_CursorMoved( m );
 }
References m, Menu_CursorMoved(), QMF_GRAYED, and QMF_INACTIVE.
Referenced by Menu_SetCursorToItem(), PlayerModel_MenuKey(), UI_MouseEvent(), and UI_PushMenu().
Menu_SetCursorToItem()
void Menu_SetCursorToItem (menuframework_s * m, void * ptr)
Definition at line 1414 of file ui_qmenu.c.
 {
     int i;
     for (i=0; i<m->nitems; i++)
     {
         if (m->items[i] == ptr)
         {
             Menu_SetCursor( m, i );
             return;
         }
     }
 }
References m, and Menu_SetCursor().
Referenced by UI_CinematicsMenu_f(), UI_ConfirmMenu_Style(), UI_DisplayOptionsMenu(), UI_GraphicsOptionsMenu(), UI_Message(), UI_NetworkOptionsMenu(), UI_PlayerModelMenu(), UI_ResetMenu(), UI_SoundOptionsMenu(), UI_SPLevelMenu(), UI_SPPostgameMenu_f(), and UI_SPSkillMenu().
PText_Draw()
static void PText_Draw (menutext_s * b) static
Definition at line 208 of file ui_qmenu.c.
 {
     int     x;
     int     y;
     float * color;
     int     style;
     x = t->generic.x;
     y = t->generic.y;
     if (t->generic.flags & QMF_GRAYED)
         color = text_color_disabled;
     else
         color = t->color;
     style = t->style;
     if( t->generic.flags & QMF_PULSEIFFOCUS ) {
         if( Menu_ItemAtCursor( t->generic.parent ) == t ) {
             style |= UI_PULSE;
         }
         else {
             style |= UI_INVERSE;
         }
     }
     UI_DrawProportionalString( x, y, t->string, style, color );
 }
References Menu_ItemAtCursor(), QMF_GRAYED, QMF_PULSEIFFOCUS, t, text_color_disabled, UI_DrawProportionalString(), UI_INVERSE, and UI_PULSE.
Referenced by Menu_Draw().
PText_Init()
static void PText_Init (menutext_s * b) static
Definition at line 175 of file ui_qmenu.c.
 {
     int x;
     int y;
     int w;
     int h;
     float   sizeScale;
     sizeScale = UI_ProportionalSizeScale( t->style );
     x = t->generic.x;
     y = t->generic.y;
     w = UI_ProportionalStringWidth( t->string ) * sizeScale;
     h = PROP_HEIGHT * sizeScale;
     if( t->generic.flags & QMF_RIGHT_JUSTIFY ) {
         x -= w;
     }
     else if( t->generic.flags & QMF_CENTER_JUSTIFY ) {
         x -= w / 2;
     }
     t->generic.left   = x - PROP_GAP_WIDTH * sizeScale;
     t->generic.right  = x + w + PROP_GAP_WIDTH * sizeScale;
     t->generic.top    = y;
     t->generic.bottom = y + h;
 }
References PROP_GAP_WIDTH, PROP_HEIGHT, QMF_CENTER_JUSTIFY, QMF_RIGHT_JUSTIFY, t, UI_ProportionalSizeScale(), and UI_ProportionalStringWidth().
Referenced by Menu_AddItem().
RadioButton_Draw()
static void RadioButton_Draw (menuradiobutton_s * rb) static
Definition at line 489 of file ui_qmenu.c.
 {
     int x;
     int y;
     float *color;
     int style;
     qboolean focus;
     x = rb->generic.x;
     y = rb->generic.y;
     focus = (rb->generic.parent->cursor == rb->generic.menuPosition);
     if ( rb->generic.flags & QMF_GRAYED )
     {
         color = text_color_disabled;
         style = UI_LEFT|UI_SMALLFONT;
     }
     else if ( focus )
     {
         color = text_color_highlight;
         style = UI_LEFT|UI_PULSE|UI_SMALLFONT;
     }
     else
     {
         color = text_color_normal;
         style = UI_LEFT|UI_SMALLFONT;
     }
     if ( focus )
     {
         // draw cursor
         UI_FillRect( rb->generic.left, rb->generic.top, rb->generic.right-rb->generic.left+1, rb->generic.bottom-rb->generic.top+1, listbar_color );
         UI_DrawChar( x, y, 13, UI_CENTER|UI_BLINK|UI_SMALLFONT, color);
     }
     if ( rb->generic.name )
         UI_DrawString( x - SMALLCHAR_WIDTH, y, rb->generic.name, UI_RIGHT|UI_SMALLFONT, color );
     if ( !rb->curvalue )
     {
         UI_DrawHandlePic( x + SMALLCHAR_WIDTH, y + 2, 16, 16, uis.rb_off);
         UI_DrawString( x + SMALLCHAR_WIDTH + 16, y, "off", style, color );
     }
     else
     {
         UI_DrawHandlePic( x + SMALLCHAR_WIDTH, y + 2, 16, 16, uis.rb_on );
         UI_DrawString( x + SMALLCHAR_WIDTH + 16, y, "on", style, color );
     }
 }
References menucommon_s::bottom, _tag_menuframework::cursor, menuradiobutton_s::curvalue, menucommon_s::flags, menuradiobutton_s::generic, menucommon_s::left, listbar_color, menucommon_s::menuPosition, menucommon_s::name, menucommon_s::parent, QMF_GRAYED, uiStatic_t::rb_off, uiStatic_t::rb_on, menucommon_s::right, SMALLCHAR_WIDTH, text_color_disabled, text_color_highlight, text_color_normal, menucommon_s::top, UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawHandlePic(), UI_DrawString(), UI_FillRect(), UI_LEFT, UI_PULSE, UI_RIGHT, UI_SMALLFONT, uis, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_Draw().
RadioButton_Init()
static void RadioButton_Init (menuradiobutton_s * rb) static
Definition at line 434 of file ui_qmenu.c.
 {
     int len;
     // calculate bounds
     if (rb->generic.name)
         len = strlen(rb->generic.name);
     else
         len = 0;
     rb->generic.left   = rb->generic.x - (len+1)*SMALLCHAR_WIDTH;
     rb->generic.right  = rb->generic.x + 6*SMALLCHAR_WIDTH;
     rb->generic.top    = rb->generic.y;
     rb->generic.bottom = rb->generic.y + SMALLCHAR_HEIGHT;
 }
References menucommon_s::bottom, menuradiobutton_s::generic, menucommon_s::left, menucommon_s::name, menucommon_s::right, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, menucommon_s::top, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_AddItem().
RadioButton_Key()
static sfxHandle_t RadioButton_Key (menuradiobutton_s * rb, int key) static
Definition at line 455 of file ui_qmenu.c.
 {
     switch (key)
     {
         case K_MOUSE1:
             if (!(rb->generic.flags & QMF_HASMOUSEFOCUS))
                 break;
         case K_JOY1:
         case K_JOY2:
         case K_JOY3:
         case K_JOY4:
         case K_ENTER:
         case K_KP_ENTER:
         case K_KP_LEFTARROW:
         case K_LEFTARROW:
         case K_KP_RIGHTARROW:
         case K_RIGHTARROW:
             rb->curvalue = !rb->curvalue;
             if ( rb->generic.callback )
                 rb->generic.callback( rb, QM_ACTIVATED );
             return (menu_move_sound);
     }
     // key not handled
     return 0;
 }
References menucommon_s::callback, menuradiobutton_s::curvalue, menucommon_s::flags, menuradiobutton_s::generic, K_ENTER, K_JOY1, K_JOY2, K_JOY3, K_JOY4, K_KP_ENTER, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, menu_move_sound, QM_ACTIVATED, and QMF_HASMOUSEFOCUS.
Referenced by Menu_DefaultKey().
ScrollList_Draw()
void ScrollList_Draw (menulist_s * l)
Definition at line 1233 of file ui_qmenu.c.
 {
     int         x;
     int         u;
     int         y;
     int         i;
     int         base;
     int         column;
     float*      color;
     qboolean    hasfocus;
     int         style;
     hasfocus = (l->generic.parent->cursor == l->generic.menuPosition);
     x = l->generic.x;
     for( column = 0; column < l->columns; column++ ) {
         y = l->generic.y;
         base = l->top + column * l->height;
         for( i = base; i < base + l->height; i++) {
             if (i >= l->numitems)
                 break;
             if (i == l->curvalue)
             {
                 u = x - 2;
                 if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                     u -= (l->width * SMALLCHAR_WIDTH) / 2 + 1;
                 }
                 UI_FillRect(u,y,l->width*SMALLCHAR_WIDTH,SMALLCHAR_HEIGHT+2,listbar_color);
                 color = text_color_highlight;
                 if (hasfocus)
                     style = UI_PULSE|UI_LEFT|UI_SMALLFONT;
                 else
                     style = UI_LEFT|UI_SMALLFONT;
             }
             else
             {
                 color = text_color_normal;
                 style = UI_LEFT|UI_SMALLFONT;
             }
             if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                 style |= UI_CENTER;
             }
             UI_DrawString(
                 x,
                 y,
                 l->itemnames[i],
                 style,
                 color);
             y += SMALLCHAR_HEIGHT;
         }
         x += (l->width + l->separation) * SMALLCHAR_WIDTH;
     }
 }
References menulist_s::columns, _tag_menuframework::cursor, menulist_s::curvalue, menucommon_s::flags, menulist_s::generic, menulist_s::height, menulist_s::itemnames, listbar_color, menucommon_s::menuPosition, menulist_s::numitems, menucommon_s::parent, QMF_CENTER_JUSTIFY, menulist_s::separation, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, text_color_highlight, text_color_normal, menulist_s::top, UI_CENTER, UI_DrawString(), UI_FillRect(), UI_LEFT, UI_PULSE, UI_SMALLFONT, menulist_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_Draw().
ScrollList_Init()
static void ScrollList_Init (menulist_s * l) static
Definition at line 874 of file ui_qmenu.c.
 {
     int     w;
     l->oldvalue = 0;
     l->curvalue = 0;
     l->top      = 0;
     if( !l->columns ) {
         l->columns = 1;
         l->separation = 0;
     }
     else if( !l->separation ) {
         l->separation = 3;
     }
     w = ( (l->width + l->separation) * l->columns - l->separation) * SMALLCHAR_WIDTH;
     l->generic.left   = l->generic.x;
     l->generic.top    = l->generic.y;
     l->generic.right  = l->generic.x + w;
     l->generic.bottom = l->generic.y + l->height * SMALLCHAR_HEIGHT;
     if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
         l->generic.left -= w / 2;
         l->generic.right -= w / 2;
     }
 }
References menucommon_s::bottom, menulist_s::columns, menulist_s::curvalue, menucommon_s::flags, menulist_s::generic, menulist_s::height, menucommon_s::left, menulist_s::oldvalue, QMF_CENTER_JUSTIFY, menucommon_s::right, menulist_s::separation, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, menucommon_s::top, menulist_s::top, menulist_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by Menu_AddItem().
ScrollList_Key()
sfxHandle_t ScrollList_Key (menulist_s * l, int key)
Definition at line 908 of file ui_qmenu.c.
 {
     int x;
     int y;
     int w;
     int i;
     int j;
     int c;
     int cursorx;
     int cursory;
     int column;
     int index;
     switch (key)
     {
         case K_MOUSE1:
             if (l->generic.flags & QMF_HASMOUSEFOCUS)
             {
                 // check scroll region
                 x = l->generic.x;
                 y = l->generic.y;
                 w = ( (l->width + l->separation) * l->columns - l->separation) * SMALLCHAR_WIDTH;
                 if( l->generic.flags & QMF_CENTER_JUSTIFY ) {
                     x -= w / 2;
                 }
                 if (UI_CursorInRect( x, y, w, l->height*SMALLCHAR_HEIGHT ))
                 {
                     cursorx = (uis.cursorx - x)/SMALLCHAR_WIDTH;
                     column = cursorx / (l->width + l->separation);
                     cursory = (uis.cursory - y)/SMALLCHAR_HEIGHT;
                     index = column * l->height + cursory;
                     if (l->top + index < l->numitems)
                     {
                         l->oldvalue = l->curvalue;
                         l->curvalue = l->top + index;
                         if (l->oldvalue != l->curvalue && l->generic.callback)
{
                             l->generic.callback( l, QM_GOTFOCUS );
                             return (menu_move_sound);
                         }
                     }
                 }
                 // absorbed, silent sound effect
                 return (menu_null_sound);
             }
             break;
         case K_KP_HOME:
         case K_HOME:
             l->oldvalue = l->curvalue;
             l->curvalue = 0;
             l->top      = 0;
             if (l->oldvalue != l->curvalue && l->generic.callback)
             {
                 l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_KP_END:
         case K_END:
             l->oldvalue = l->curvalue;
             l->curvalue = l->numitems-1;
             if( l->columns > 1 ) {
                 c = (l->curvalue / l->height + 1) * l->height;
                 l->top = c - (l->columns * l->height);
             }
             else {
                 l->top = l->curvalue - (l->height - 1);
             }
             if (l->top < 0)
                 l->top = 0;
             if (l->oldvalue != l->curvalue && l->generic.callback)
             {
                 l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_PGUP:
         case K_KP_PGUP:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->curvalue > 0)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue -= l->height-1;
                 if (l->curvalue < 0)
                     l->curvalue = 0;
                 l->top = l->curvalue;
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_PGDN:
         case K_KP_PGDN:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->curvalue < l->numitems-1)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue += l->height-1;
                 if (l->curvalue > l->numitems-1)
                     l->curvalue = l->numitems-1;
                 l->top = l->curvalue - (l->height-1);
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return (menu_move_sound);
             }
             return (menu_buzz_sound);
         case K_MWHEELUP:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->top > 0)
             {
                 // if scrolling 3 lines would replace over half of the
                 // displayed items, only scroll 1 item at a time.
                 int scroll = l->height < 6 ? 1 : 3;
                 l->top -= scroll;
                 if (l->top < 0)
                     l->top = 0;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 // make scrolling silent
                 return (menu_null_sound);
             }
             return (menu_buzz_sound);
         case K_MWHEELDOWN:
             if( l->columns > 1 ) {
                 return menu_null_sound;
             }
             if (l->top < l->numitems-l->height)
             {
                 // if scrolling 3 items would replace over half of the
                 // displayed items, only scroll 1 item at a time.
                 int scroll = l->height < 6 ? 1 : 3;
                 l->top += scroll;
                 if (l->top > l->numitems-l->height)
                     l->top = l->numitems-l->height;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 // make scrolling silent
                 return (menu_null_sound);
             }
             return (menu_buzz_sound);
         case K_KP_UPARROW:
         case K_UPARROW:
             if( l->curvalue == 0 ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue--;
             if( l->curvalue < l->top ) {
                 if( l->columns == 1 ) {
                     l->top--;
                 }
                 else {
                     l->top -= l->height;
                 }
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return (menu_move_sound);
         case K_KP_DOWNARROW:
         case K_DOWNARROW:
             if( l->curvalue == l->numitems - 1 ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue++;
             if( l->curvalue >= l->top + l->columns * l->height ) {
                 if( l->columns == 1 ) {
                     l->top++;
                 }
                 else {
                     l->top += l->height;
                 }
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
         case K_KP_LEFTARROW:
         case K_LEFTARROW:
             if( l->columns == 1 ) {
                 return menu_null_sound;
             }
             if( l->curvalue < l->height ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue -= l->height;
             if( l->curvalue < l->top ) {
                 l->top -= l->height;
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
         case K_KP_RIGHTARROW:
         case K_RIGHTARROW:
             if( l->columns == 1 ) {
                 return menu_null_sound;
             }
             c = l->curvalue + l->height;
             if( c >= l->numitems ) {
                 return menu_buzz_sound;
             }
             l->oldvalue = l->curvalue;
             l->curvalue = c;
             if( l->curvalue > l->top + l->columns * l->height - 1 ) {
                 l->top += l->height;
             }
             if( l->generic.callback ) {
                 l->generic.callback( l, QM_GOTFOCUS );
             }
             return menu_move_sound;
     }
     // cycle look for ascii key inside list items
     if ( !Q_isprint( key ) )
         return (0);
     // force to lower for case insensitive compare
     if ( Q_isupper( key ) )
     {
         key -= 'A' - 'a';
     }
     // iterate list items
     for (i=1; i<=l->numitems; i++)
     {
         j = (l->curvalue + i) % l->numitems;
         c = l->itemnames[j][0];
         if ( Q_isupper( c ) )
         {
             c -= 'A' - 'a';
         }
         if (c == key)
         {
             // set current item, mimic windows listbox scroll behavior
             if (j < l->top)
             {
                 // behind top most item, set this as new top
                 l->top = j;
             }
             else if (j > l->top+l->height-1)
             {
                 // past end of list box, do page down
                 l->top = (j+1) - l->height;
             }
             if (l->curvalue != j)
             {
                 l->oldvalue = l->curvalue;
                 l->curvalue = j;
                 if (l->generic.callback)
                     l->generic.callback( l, QM_GOTFOCUS );
                 return ( menu_move_sound );
             }
             return (menu_buzz_sound);
         }
     }
     return (menu_buzz_sound);
 }
References menucommon_s::callback, menulist_s::columns, uiStatic_t::cursorx, uiStatic_t::cursory, menulist_s::curvalue, menucommon_s::flags, menulist_s::generic, menulist_s::height, menulist_s::itemnames, K_DOWNARROW, K_END, K_HOME, K_KP_DOWNARROW, K_KP_END, K_KP_HOME, K_KP_LEFTARROW, K_KP_PGDN, K_KP_PGUP, K_KP_RIGHTARROW, K_KP_UPARROW, K_LEFTARROW, K_MOUSE1, K_MWHEELDOWN, K_MWHEELUP, K_PGDN, K_PGUP, K_RIGHTARROW, K_UPARROW, menu_buzz_sound, menu_move_sound, menu_null_sound, menulist_s::numitems, menulist_s::oldvalue, Q_isprint(), Q_isupper(), QM_GOTFOCUS, QMF_CENTER_JUSTIFY, QMF_HASMOUSEFOCUS, menulist_s::separation, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, menulist_s::top, UI_CursorInRect(), uis, menulist_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by ArenaServers_Event(), Demos_MenuEvent(), LoadConfig_MenuEvent(), Menu_DefaultKey(), and SpecifyLeague_Event().
Slider_Draw()
static void Slider_Draw (menuslider_s * s) static
Definition at line 629 of file ui_qmenu.c.
{
     int         x;
     int         y;
     int         style;
     float       *color;
     int         button;
     qboolean    focus;
     x = s->generic.x;
     y = s->generic.y;
     focus = (s->generic.parent->cursor == s->generic.menuPosition);
     if( s->generic.flags & QMF_GRAYED ) {
         color = text_color_disabled;
         style = UI_SMALLFONT;
     }
     else if( focus ) {
         color  = text_color_highlight;
         style = UI_SMALLFONT | UI_PULSE;
     }
     else {
         color = text_color_normal;
         style = UI_SMALLFONT;
     }
     // draw label
     UI_DrawString( x - SMALLCHAR_WIDTH, y, s->generic.name, UI_RIGHT|style, color );
     // draw slider
     UI_SetColor( color );
     UI_DrawHandlePic( x + SMALLCHAR_WIDTH, y, 96, 16, sliderBar );
     UI_SetColor( NULL );
     // clamp thumb
     if( s->maxvalue > s->minvalue ) {
         s->range = ( s->curvalue - s->minvalue ) / ( float ) ( s->maxvalue - s->minvalue );
         if( s->range < 0 ) {
             s->range = 0;
         }
         else if( s->range > 1) {
             s->range = 1;
         }
     }
     else {
         s->range = 0;
     }
     // draw thumb
     if( style & UI_PULSE) {
         button = sliderButton_1;
     }
     else {
         button = sliderButton_0;
     }
     UI_DrawHandlePic( (int)( x + 2*SMALLCHAR_WIDTH + (SLIDER_RANGE-1)*SMALLCHAR_WIDTH* s->range ) - 2, y - 2, 12, 20, button );
 }
References NULL, QMF_GRAYED, s, SLIDER_RANGE, sliderBar, sliderButton_0, sliderButton_1, SMALLCHAR_WIDTH, text_color_disabled, text_color_highlight, text_color_normal, UI_DrawHandlePic(), UI_DrawString(), UI_PULSE, UI_RIGHT, UI_SetColor(), and UI_SMALLFONT.
Referenced by Menu_Draw().
Slider_Init()
static void Slider_Init (menuslider_s * s) static
Definition at line 545 of file ui_qmenu.c.
 {
     int len;
     // calculate bounds
     if (s->generic.name)
         len = strlen(s->generic.name);
     else
         len = 0;
     s->generic.left   = s->generic.x - (len+1)*SMALLCHAR_WIDTH;
     s->generic.right  = s->generic.x + (SLIDER_RANGE+2+1)*SMALLCHAR_WIDTH;
     s->generic.top    = s->generic.y;
     s->generic.bottom = s->generic.y + SMALLCHAR_HEIGHT;
 }
References s, SLIDER_RANGE, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by Menu_AddItem().
Slider_Key()
static sfxHandle_t Slider_Key (menuslider_s * s, int key) static
Definition at line 566 of file ui_qmenu.c.
 {
     sfxHandle_t sound;
     int         x;
     int         oldvalue;
     switch (key)
     {
         case K_MOUSE1:
             x           = uis.cursorx - s->generic.x - 2*SMALLCHAR_WIDTH;
             oldvalue    = s->curvalue;
             s->curvalue = (x/(float)(SLIDER_RANGE*SMALLCHAR_WIDTH)) * (s->maxvalue-s->minvalue) + s->minvalue;
             if (s->curvalue < s->minvalue)
                 s->curvalue = s->minvalue;
             else if (s->curvalue > s->maxvalue)
                 s->curvalue = s->maxvalue;
             if (s->curvalue != oldvalue)
                 sound = menu_move_sound;
             else
                 sound = 0;
             break;
         case K_KP_LEFTARROW:
         case K_LEFTARROW:
             if (s->curvalue > s->minvalue)
             {
                 s->curvalue--;
                 sound = menu_move_sound;
             }
             else
                 sound = menu_buzz_sound;
             break;
         case K_KP_RIGHTARROW:
         case K_RIGHTARROW:
             if (s->curvalue < s->maxvalue)
             {
                 s->curvalue++;
                 sound = menu_move_sound;
             }
             else
                 sound = menu_buzz_sound;
             break;
         default:
             // key not handled
             sound = 0;
             break;
     }
     if ( sound && s->generic.callback )
         s->generic.callback( s, QM_ACTIVATED );
     return (sound);
 }
References uiStatic_t::cursorx, K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, menu_buzz_sound, menu_move_sound, QM_ACTIVATED, s, SLIDER_RANGE, SMALLCHAR_WIDTH, and uis.
Referenced by Menu_DefaultKey().
SpinControl_Draw()
static void SpinControl_Draw (menulist_s * s) static
Definition at line 830 of file ui_qmenu.c.
 {
     float *color;
     int x,y;
     int style;
     qboolean focus;
     x = s->generic.x;
     y = s->generic.y;
     style = UI_SMALLFONT;
     focus = (s->generic.parent->cursor == s->generic.menuPosition);
     if ( s->generic.flags & QMF_GRAYED )
         color = text_color_disabled;
     else if ( focus )
     {
         color = text_color_highlight;
         style |= UI_PULSE;
     }
     else if ( s->generic.flags & QMF_BLINK )
     {
         color = text_color_highlight;
         style |= UI_BLINK;
     }
     else
         color = text_color_normal;
     if ( focus )
     {
         // draw cursor
         UI_FillRect( s->generic.left, s->generic.top, s->generic.right-s->generic.left+1, s->generic.bottom-s->generic.top+1, listbar_color );
         UI_DrawChar( x, y, 13, UI_CENTER|UI_BLINK|UI_SMALLFONT, color);
     }
     UI_DrawString( x - SMALLCHAR_WIDTH, y, s->generic.name, style|UI_RIGHT, color );
     UI_DrawString( x + SMALLCHAR_WIDTH, y, s->itemnames[s->curvalue], style|UI_LEFT, color );
 }
References listbar_color, QMF_BLINK, QMF_GRAYED, s, SMALLCHAR_WIDTH, text_color_disabled, text_color_highlight, text_color_normal, UI_BLINK, UI_CENTER, UI_DrawChar(), UI_DrawString(), UI_FillRect(), UI_LEFT, UI_PULSE, UI_RIGHT, and UI_SMALLFONT.
Referenced by Menu_Draw().
SpinControl_Init()
static void SpinControl_Init (menulist_s * s) static
Definition at line 762 of file ui_qmenu.c.
{
     int len;
     int l;
     const char* str;
     if (s->generic.name)
         len = strlen(s->generic.name) * SMALLCHAR_WIDTH;
     else
         len = 0;
     s->generic.left = s->generic.x - SMALLCHAR_WIDTH - len;
     len = s->numitems = 0;
     while ( (str = s->itemnames[s->numitems]) != 0 )
     {
         l = strlen(str);
         if (l > len)
             len = l;
         s->numitems++;
     }
     s->generic.top    = s->generic.y;
     s->generic.right  = s->generic.x + (len+1)*SMALLCHAR_WIDTH;
     s->generic.bottom = s->generic.y + SMALLCHAR_HEIGHT;
 }
References s, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by Menu_AddItem().
SpinControl_Key()
static sfxHandle_t SpinControl_Key (menulist_s * l, int key) static
Definition at line 794 of file ui_qmenu.c.
 {
     sfxHandle_t sound;
     sound = 0;
     switch (key)
     {
         case K_KP_RIGHTARROW:
         case K_RIGHTARROW:
         case K_MOUSE1:
             s->curvalue++;
             if (s->curvalue >= s->numitems)
                 s->curvalue = 0;
             sound = menu_move_sound;
             break;
         case K_KP_LEFTARROW:
         case K_LEFTARROW:
             s->curvalue--;
             if (s->curvalue < 0)
                 s->curvalue = s->numitems-1;
             sound = menu_move_sound;
             break;
     }
     if ( sound && s->generic.callback )
         s->generic.callback( s, QM_ACTIVATED );
     return (sound);
 }
References K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_MOUSE1, K_RIGHTARROW, menu_move_sound, QM_ACTIVATED, and s.
Referenced by Menu_DefaultKey().
Text_Draw()
static void Text_Draw (menutext_s * b) static
Definition at line 110 of file ui_qmenu.c.
 {
     int     x;
     int     y;
     char    buff[512];
     float*  color;
     x = t->generic.x;
     y = t->generic.y;
     buff[0] = '\0';
     // possible label
     if (t->generic.name)
         strcpy(buff,t->generic.name);
     // possible value
     if (t->string)
         strcat(buff,t->string);
     if (t->generic.flags & QMF_GRAYED)
         color = text_color_disabled;
     else
         color = t->color;
     UI_DrawString( x, y, buff, t->style, color );
 }
References QMF_GRAYED, t, text_color_disabled, and UI_DrawString().
Referenced by Menu_Draw().
Text_Init()
static void Text_Init (menutext_s * b) static
Definition at line 100 of file ui_qmenu.c.
 {
     t->generic.flags |= QMF_INACTIVE;
 }
References QMF_INACTIVE, and t.
Referenced by Menu_AddItem().
Variable Documentation
color_black
vec4_t color_black = {0.00f, 0.00f, 0.00f, 1.00f}
Definition at line 43 of file ui_qmenu.c.
Referenced by UI_SPLevelMenu_MenuDraw().
color_blue
vec4_t color_blue = {0.00f, 0.00f, 1.00f, 1.00f}
Definition at line 46 of file ui_qmenu.c.
color_dim
vec4_t color_dim = {0.00f, 0.00f, 0.00f, 0.25f}
Definition at line 50 of file ui_qmenu.c.
color_lightOrange
vec4_t color_lightOrange = {1.00f, 0.68f, 0.00f, 1.00f }
Definition at line 47 of file ui_qmenu.c.
color_orange
vec4_t color_orange = {1.00f, 0.43f, 0.00f, 1.00f}
Definition at line 48 of file ui_qmenu.c.
Referenced by ServerOptions_LevelshotDraw(), ServerOptions_MenuInit(), StartServer_LevelshotDraw(), UI_AddBotsMenu_BotEvent(), UI_AddBotsMenu_Init(), UI_BotSelectMenu_Init(), UI_BotSelectMenu_UpdateGrid(), UI_CDKeyMenu_DrawKey(), UI_RemoveBotsMenu_BotEvent(), UI_RemoveBotsMenu_Init(), UI_SaveConfigMenu_SavenameDraw(), UI_SPLevelMenu_MenuDraw(), and UI_TeamOrdersMenu_ListDraw().
color_red
vec4_t color_red = {1.00f, 0.00f, 0.00f, 1.00f}
Definition at line 49 of file ui_qmenu.c.
Referenced by ConfirmMenu_Draw(), Controls_MenuInit(), DriverInfo_MenuDraw(), GraphicsOptions_MenuInit(), InGame_MenuInit(), MessageMenu_Draw(), Options_MenuInit(), PlayerModel_DrawPlayer(), Reset_MenuDraw(), ServerInfo_MenuDraw(), UI_BotSelectMenu_UpdateGrid(), UI_CDKeyMenu_DrawKey(), UI_CinematicsMenu_Init(), UI_ConfirmMenu_Style(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DisplayOptionsMenu_Init(), UI_MainMenu(), UI_Message(), UI_NetworkOptionsMenu_Init(), UI_ResetMenu(), UI_ServerInfoMenu(), UI_SetupMenu_Init(), UI_SoundOptionsMenu_Init(), UI_SPLevelMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPSkillMenu_Init(), and UI_SPSkillMenu_SkillEvent().
color_white
vec4_t color_white = {1.00f, 1.00f, 1.00f, 1.00f}
Definition at line 44 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), Demos_MenuInit(), GraphicsOptions_MenuInit(), LoadConfig_MenuInit(), Options_MenuInit(), PlayerModel_MenuInit(), PlayerSettings_DrawName(), PlayerSettings_MenuInit(), Preferences_MenuInit(), Rankings_DrawText(), ServerOptions_MenuInit(), SpecifyLeague_MenuInit(), SpecifyServer_MenuInit(), StartServer_MenuInit(), UI_AddBotsMenu_BotEvent(), UI_AddBotsMenu_Init(), UI_BotSelectMenu_Init(), UI_CDKeyMenu_DrawKey(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Init(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DisplayDownloadInfo(), UI_DisplayOptionsMenu_Init(), UI_DrawConnectScreen(), UI_DriverInfo_Menu(), UI_Mods_MenuInit(), UI_NetworkOptionsMenu_Init(), UI_RemoveBotsMenu_BotEvent(), UI_RemoveBotsMenu_Init(), UI_SaveConfigMenu_Init(), UI_ServerInfoMenu(), UI_SetupMenu_Init(), UI_SoundOptionsMenu_Init(), UI_SPLevelMenu_MenuDraw(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_SPSkillMenu_Init(), UI_SPSkillMenu_SkillEvent(), and UI_TeamOrdersMenu_Init().
color_yellow
vec4_t color_yellow = {1.00f, 1.00f, 0.00f, 1.00f}
Definition at line 45 of file ui_qmenu.c.
Referenced by Controls_ResetDefaults_Draw(), Reset_MenuDraw(), Setup_ResetDefaults_Draw(), UI_CDKeyMenu_DrawKey(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_ResetDraw(), UI_SPPostgameMenu_DrawAwardsMedals(), and UI_TeamOrdersMenu_ListDraw().
listbar_color
vec4_t listbar_color = {1.00f, 0.43f, 0.00f, 0.30f}
Definition at line 57 of file ui_qmenu.c.
Referenced by Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PlayerName_Draw(), RadioButton_Draw(), ScrollList_Draw(), SpinControl_Draw(), and UI_CDKeyMenu_DrawKey().
menu_buzz_sound
sfxHandle_t menu_buzz_sound
Definition at line 33 of file ui_qmenu.c.
Referenced by Menu_Cache(), MenuField_Key(), PlayerModel_MenuKey(), ScrollList_Key(), and Slider_Key().
menu_dim_color
vec4_t menu_dim_color = {0.0f, 0.0f, 0.0f, 0.75f}
Definition at line 42 of file ui_qmenu.c.
menu_in_sound
sfxHandle_t menu_in_sound
Definition at line 30 of file ui_qmenu.c.
Referenced by Menu_Cache(), and UI_Refresh().
menu_move_sound
sfxHandle_t menu_move_sound
Definition at line 31 of file ui_qmenu.c.
Referenced by ArenaServers_MenuKey(), Menu_ActivateItem(), Menu_Cache(), Menu_DefaultKey(), PlayerModel_MenuKey(), RadioButton_Key(), ScrollList_Key(), Slider_Key(), SpinControl_Key(), UI_MouseEvent(), and UI_TeamOrdersMenu_Key().
menu_null_sound
sfxHandle_t menu_null_sound
Definition at line 34 of file ui_qmenu.c.
Referenced by ErrorMessage_Key(), Menu_Cache(), ScrollList_Key(), UI_KeyEvent(), and UI_TeamOrdersMenu_Key().
menu_out_sound
sfxHandle_t menu_out_sound
Definition at line 32 of file ui_qmenu.c.
Referenced by Controls_MenuKey(), Menu_Cache(), Menu_DefaultKey(), and UI_PopMenu().
menu_text_color
vec4_t menu_text_color = {1.0f, 1.0f, 1.0f, 1.0f}
Definition at line 41 of file ui_qmenu.c.
Referenced by Action_Draw(), ArenaServers_MenuInit(), Main_MenuDraw(), and UI_DrawConnectScreen().
pulse_color
vec4_t pulse_color = {1.00f, 1.00f, 1.00f, 1.00f}
Definition at line 53 of file ui_qmenu.c.
Referenced by Bitmap_Draw().
sliderBar
qhandle_t sliderBar static
Definition at line 37 of file ui_qmenu.c.
Referenced by Menu_Cache(), and Slider_Draw().
sliderButton_0
qhandle_t sliderButton_0 static
Definition at line 38 of file ui_qmenu.c.
Referenced by Menu_Cache(), and Slider_Draw().
sliderButton_1
qhandle_t sliderButton_1 static
Definition at line 39 of file ui_qmenu.c.
Referenced by Menu_Cache(), and Slider_Draw().
text_color_disabled
vec4_t text_color_disabled = {0.50f, 0.50f, 0.50f, 1.00f}
Definition at line 54 of file ui_qmenu.c.
Referenced by Action_Draw(), BText_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PlayerName_Draw(), PText_Draw(), RadioButton_Draw(), Slider_Draw(), SpinControl_Draw(), and Text_Draw().
text_color_highlight
vec4_t text_color_highlight = {1.00f, 1.00f, 0.00f, 1.00f}
Definition at line 56 of file ui_qmenu.c.
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PlayerName_Draw(), PlayerSettings_DrawEffects(), PlayerSettings_DrawHandicap(), PlayerSettings_DrawName(), RadioButton_Draw(), Rankings_DrawText(), ScrollList_Draw(), Slider_Draw(), SpinControl_Draw(), and UI_SaveConfigMenu_SavenameDraw().
text_color_normal
vec4_t text_color_normal = {1.00f, 0.43f, 0.00f, 1.00f}
Definition at line 55 of file ui_qmenu.c.
Referenced by ArenaServers_MenuInit(), Controls_MenuInit(), Crosshair_Draw(), DriverInfo_MenuDraw(), MenuField_Draw(), PlayerModel_MenuInit(), PlayerName_Draw(), PlayerSettings_DrawEffects(), PlayerSettings_DrawHandicap(), PlayerSettings_DrawName(), RadioButton_Draw(), Rankings_DrawText(), ScrollList_Draw(), ServerInfo_MenuDraw(), Slider_Draw(), SpinControl_Draw(), and StartServer_MenuInit().
text_color_status
vec4_t text_color_status = {1.00f, 1.00f, 1.00f, 1.00f}
Definition at line 58 of file ui_qmenu.c.
weaponChangeSound
sfxHandle_t weaponChangeSound
Definition at line 35 of file ui_qmenu.c.
Referenced by Menu_Cache().