ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_spreset.c File Reference
ui_spreset.c File Reference
#include "ui_local.h"
Classes
struct resetMenu_t
Macros
#define ART_FRAME "menu/art/cut_frame"
#define ID_NO 100
#define ID_YES 101
Functions
void Reset_MenuEvent (void *ptr, int event)
static sfxHandle_t Reset_MenuKey (int key)
static void Reset_MenuDraw (void)
void Reset_Cache (void)
void UI_ResetMenu (void)
Variables
static resetMenu_t s_reset
Macro Definition Documentation
ART_FRAME
#define ART_FRAME "menu/art/cut_frame"
Definition at line 33 of file ui_spreset.c.
ID_NO
#define ID_NO 100
Definition at line 35 of file ui_spreset.c.
ID_YES
#define ID_YES 101
Definition at line 36 of file ui_spreset.c.
Function Documentation
Reset_Cache()
void Reset_Cache (void)
Definition at line 125 of file ui_spreset.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAME );
 }
References ART_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by UI_ResetMenu().
Reset_MenuDraw()
static void Reset_MenuDraw (void) static
Definition at line 107 of file ui_spreset.c.
{
     UI_DrawNamedPic( 142, 118, 359, 256, ART_FRAME );
     UI_DrawProportionalString( 320, 194 + 10, "RESET GAME?", UI_CENTER|UI_INVERSE, color_red );
     UI_DrawProportionalString( s_reset.slashX, 265, "/", UI_LEFT|UI_INVERSE, color_red );
     Menu_Draw( &s_reset.menu );
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 0, "WARNING: This resets all of the", UI_CENTER|UI_SMALLFONT, color_yellow );
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 1, "single player game variables.", UI_CENTER|UI_SMALLFONT, color_yellow );
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 2, "Do this only if you want to", UI_CENTER|UI_SMALLFONT, color_yellow );
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 3, "start over from the beginning.", UI_CENTER|UI_SMALLFONT, color_yellow );
 }
References ART_FRAME, color_red, color_yellow, resetMenu_t::menu, Menu_Draw(), PROP_HEIGHT, s_reset, SCREEN_WIDTH, resetMenu_t::slashX, UI_CENTER, UI_DrawNamedPic(), UI_DrawProportionalString(), UI_INVERSE, UI_LEFT, and UI_SMALLFONT.
Referenced by UI_ResetMenu().
Reset_MenuEvent()
void Reset_MenuEvent (void * ptr, int event)
Definition at line 54 of file ui_spreset.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     UI_PopMenu();
     if( ((menucommon_s*)ptr)->id == ID_NO ) {
         return;
     }
     // reset the game, pop the level menu and restart it so it updates
     UI_NewGame();
     trap_Cvar_SetValue( "ui_spSelection", 0 );
     UI_PopMenu();
     UI_SPLevelMenu();
 }
References ID_NO, QM_ACTIVATED, trap_Cvar_SetValue(), UI_NewGame(), UI_PopMenu(), and UI_SPLevelMenu().
Referenced by Reset_MenuKey(), and UI_ResetMenu().
Reset_MenuKey()
static sfxHandle_t Reset_MenuKey (int key) static
Definition at line 78 of file ui_spreset.c.
{
     switch ( key ) {
     case K_KP_LEFTARROW:
     case K_LEFTARROW:
     case K_KP_RIGHTARROW:
     case K_RIGHTARROW:
         key = K_TAB;
         break;
     case 'n':
     case 'N':
         Reset_MenuEvent( &s_reset.no, QM_ACTIVATED );
         break;
     case 'y':
     case 'Y':
         Reset_MenuEvent( &s_reset.yes, QM_ACTIVATED );
         break;
     }
     return Menu_DefaultKey( &s_reset.menu, key );
 }
References K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_RIGHTARROW, K_TAB, resetMenu_t::menu, Menu_DefaultKey(), resetMenu_t::no, QM_ACTIVATED, Reset_MenuEvent(), s_reset, and resetMenu_t::yes.
Referenced by UI_ResetMenu().
UI_ResetMenu()
void UI_ResetMenu (void)
Definition at line 135 of file ui_spreset.c.
{
     uiClientState_t cstate;
     int n1, n2, n3;
     int l1, l2, l3;
     // zero set all our globals
     memset( &s_reset, 0, sizeof(s_reset) );
     Reset_Cache();
     n1 = UI_ProportionalStringWidth( "YES/NO" );
     n2 = UI_ProportionalStringWidth( "YES" ) + PROP_GAP_WIDTH;
     n3 = UI_ProportionalStringWidth( "/" )  + PROP_GAP_WIDTH;
     l1 = 320 - ( n1 / 2 );
     l2 = l1 + n2;
     l3 = l2 + n3;
     s_reset.slashX = l2;
     s_reset.menu.draw       = Reset_MenuDraw;
     s_reset.menu.key        = Reset_MenuKey;
     s_reset.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         // float on top of running game
         s_reset.menu.fullscreen = qfalse;
     }
     else {
         // game not running
         s_reset.menu.fullscreen = qtrue;
     }
     s_reset.yes.generic.type        = MTYPE_PTEXT;
     s_reset.yes.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_reset.yes.generic.callback    = Reset_MenuEvent;
     s_reset.yes.generic.id          = ID_YES;
     s_reset.yes.generic.x           = l1;
     s_reset.yes.generic.y           = 264;
     s_reset.yes.string              = "YES";
     s_reset.yes.color               = color_red;
     s_reset.yes.style               = UI_LEFT;
     s_reset.no.generic.type         = MTYPE_PTEXT;
     s_reset.no.generic.flags        = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_reset.no.generic.callback     = Reset_MenuEvent;
     s_reset.no.generic.id           = ID_NO;
     s_reset.no.generic.x            = l3;
     s_reset.no.generic.y            = 264;
     s_reset.no.string               = "NO";
     s_reset.no.color                = color_red;
     s_reset.no.style                = UI_LEFT;
     Menu_AddItem( &s_reset.menu,    &s_reset.yes );
     Menu_AddItem( &s_reset.menu,    &s_reset.no );
     UI_PushMenu( &s_reset.menu );
     Menu_SetCursorToItem( &s_reset.menu, &s_reset.no );
 }
References CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_red, uiClientState_t::connState, _tag_menuframework::draw, menucommon_s::flags, _tag_menuframework::fullscreen, menutext_s::generic, menucommon_s::id, ID_NO, ID_YES, _tag_menuframework::key, resetMenu_t::menu, Menu_AddItem(), Menu_SetCursorToItem(), MTYPE_PTEXT, resetMenu_t::no, PROP_GAP_WIDTH, qfalse, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, Reset_Cache(), Reset_MenuDraw(), Reset_MenuEvent(), Reset_MenuKey(), s_reset, resetMenu_t::slashX, menutext_s::string, menutext_s::style, trap_GetClientState(), menucommon_s::type, UI_LEFT, UI_ProportionalStringWidth(), UI_PushMenu(), _tag_menuframework::wrapAround, menucommon_s::x, menucommon_s::y, and resetMenu_t::yes.
Variable Documentation
s_reset
resetMenu_t s_reset static
Definition at line 46 of file ui_spreset.c.
Referenced by Reset_MenuDraw(), Reset_MenuKey(), and UI_ResetMenu().