ioquake3 doxygen: C:/entry/dev/ioquake3/code/client/client.h File Reference
client.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "../renderercommon/tr_public.h"
#include "../ui/ui_public.h"
#include "keys.h"
#include "snd_public.h"
#include "../cgame/cg_public.h"
#include "../game/bg_public.h"
Classes
struct clSnapshot_t
struct outPacket_t
struct clientActive_t
struct clientConnection_t
struct ping_t
struct serverInfo_t
struct clientStatic_t
struct kbutton_t
Macros
#define QKEY_FILE "qkey"
#define QKEY_SIZE 2048
#define RETRANSMIT_TIMEOUT 3000
#define MAX_PARSE_ENTITIES (PACKET_BACKUP * MAX_SNAPSHOT_ENTITIES)
#define MAX_TIMEDEMO_DURATIONS 4096
Functions
void CL_Init (void)
void CL_AddReliableCommand (const char *cmd, qboolean isDisconnectCmd)
void CL_StartHunkUsers (qboolean rendererOnly)
void CL_Disconnect_f (void)
void CL_GetChallengePacket (void)
void CL_Vid_Restart_f (void)
void CL_Snd_Restart_f (void)
void CL_StartDemoLoop (void)
void CL_NextDemo (void)
void CL_ReadDemoMessage (void)
void CL_StopRecord_f (void)
void CL_InitDownloads (void)
void CL_NextDownload (void)
void CL_GetPing (int n, char *buf, int buflen, int *pingtime)
void CL_GetPingInfo (int n, char *buf, int buflen)
void CL_ClearPing (int n)
int CL_GetPingQueueCount (void)
void CL_ShutdownRef (void)
void CL_InitRef (void)
qboolean CL_CDKeyValidate (const char *key, const char *checksum)
int CL_ServerStatus (char *serverAddress, char *serverStatusString, int maxLen)
qboolean CL_CheckPaused (void)
void CL_InitInput (void)
void CL_ShutdownInput (void)
void CL_SendCmd (void)
void CL_ClearState (void)
void CL_ReadPackets (void)
void CL_WritePacket (void)
void IN_CenterView (void)
void CL_VerifyCode (void)
float CL_KeyState (kbutton_t *key)
int Key_StringToKeynum (char *str)
char * Key_KeynumToString (int keynum)
void CL_SystemInfoChanged (void)
void CL_ParseServerMessage (msg_t *msg)
void CL_ServerInfoPacket (netadr_t from, msg_t *msg)
void CL_LocalServers_f (void)
void CL_GlobalServers_f (void)
void CL_FavoriteServers_f (void)
void CL_Ping_f (void)
qboolean CL_UpdateVisiblePings_f (int source)
void Con_DrawCharacter (int cx, int line, int num)
void Con_CheckResize (void)
void Con_Init (void)
void Con_Shutdown (void)
void Con_Clear_f (void)
void Con_ToggleConsole_f (void)
void Con_DrawNotify (void)
void Con_ClearNotify (void)
void Con_RunConsole (void)
void Con_DrawConsole (void)
void Con_PageUp (void)
void Con_PageDown (void)
void Con_Top (void)
void Con_Bottom (void)
void Con_Close (void)
void CL_LoadConsoleHistory (void)
void CL_SaveConsoleHistory (void)
void SCR_Init (void)
void SCR_UpdateScreen (void)
void SCR_DebugGraph (float value)
int SCR_GetBigStringWidth (const char *str)
void SCR_AdjustFrom640 (float *x, float *y, float *w, float *h)
void SCR_FillRect (float x, float y, float width, float height, const float *color)
void SCR_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
void SCR_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void SCR_DrawBigString (int x, int y, const char *s, float alpha, qboolean noColorEscape)
void SCR_DrawBigStringColor (int x, int y, const char *s, vec4_t color, qboolean noColorEscape)
void SCR_DrawSmallStringExt (int x, int y, const char *string, float *setColor, qboolean forceColor, qboolean noColorEscape)
void SCR_DrawSmallChar (int x, int y, int ch)
void CL_PlayCinematic_f (void)
void SCR_DrawCinematic (void)
void SCR_RunCinematic (void)
void SCR_StopCinematic (void)
int CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
e_status CIN_StopCinematic (int handle)
e_status CIN_RunCinematic (int handle)
void CIN_DrawCinematic (int handle)
void CIN_SetExtents (int handle, int x, int y, int w, int h)
void CIN_SetLooping (int handle, qboolean loop)
void CIN_UploadCinematic (int handle)
void CIN_CloseAllVideos (void)
void CL_InitCGame (void)
void CL_ShutdownCGame (void)
qboolean CL_GameCommand (void)
void CL_CGameRendering (stereoFrame_t stereo)
void CL_SetCGameTime (void)
void CL_FirstSnapshot (void)
void CL_ShaderStateChanged (void)
void CL_InitUI (void)
void CL_ShutdownUI (void)
int Key_GetCatcher (void)
void Key_SetCatcher (int catcher)
void LAN_LoadCachedServers (void)
void LAN_SaveServersToCache (void)
void CL_Netchan_Transmit (netchan_t *chan, msg_t *msg)
qboolean CL_Netchan_Process (netchan_t *chan, msg_t *msg)
qboolean CL_OpenAVIForWriting (const char *filename)
void CL_TakeVideoFrame (void)
void CL_WriteAVIVideoFrame (const byte *imageBuffer, int size)
void CL_WriteAVIAudioFrame (const byte *pcmBuffer, int size)
qboolean CL_CloseAVI (void)
qboolean CL_VideoRecording (void)
void CL_WriteDemoMessage (msg_t *msg, int headerBytes)
Variables
int g_console_field_width
clientActive_t cl
clientConnection_t clc
clientStatic_t cls
char cl_oldGame [MAX_QPATH]
qboolean cl_oldGameSet
vm_t * cgvm
vm_t * uivm
refexport_t re
cvar_t * cl_nodelta
cvar_t * cl_debugMove
cvar_t * cl_noprint
cvar_t * cl_timegraph
cvar_t * cl_maxpackets
cvar_t * cl_packetdup
cvar_t * cl_shownet
cvar_t * cl_showSend
cvar_t * cl_timeNudge
cvar_t * cl_showTimeDelta
cvar_t * cl_freezeDemo
cvar_t * cl_yawspeed
cvar_t * cl_pitchspeed
cvar_t * cl_run
cvar_t * cl_anglespeedkey
cvar_t * cl_sensitivity
cvar_t * cl_freelook
cvar_t * cl_mouseAccel
cvar_t * cl_mouseAccelOffset
cvar_t * cl_mouseAccelStyle
cvar_t * cl_showMouseRate
cvar_t * m_pitch
cvar_t * m_yaw
cvar_t * m_forward
cvar_t * m_side
cvar_t * m_filter
cvar_t * j_pitch
cvar_t * j_yaw
cvar_t * j_forward
cvar_t * j_side
cvar_t * j_up
cvar_t * j_pitch_axis
cvar_t * j_yaw_axis
cvar_t * j_forward_axis
cvar_t * j_side_axis
cvar_t * j_up_axis
cvar_t * cl_timedemo
cvar_t * cl_aviFrameRate
cvar_t * cl_aviMotionJpeg
cvar_t * cl_activeAction
cvar_t * cl_allowDownload
cvar_t * cl_downloadMethod
cvar_t * cl_conXOffset
cvar_t * cl_inGameVideo
cvar_t * cl_lanForcePackets
cvar_t * cl_autoRecordDemo
cvar_t * cl_consoleKeys
int cl_connectedToPureServer
int cl_connectedToCheatServer
Macro Definition Documentation
MAX_PARSE_ENTITIES
#define MAX_PARSE_ENTITIES (PACKET_BACKUP * MAX_SNAPSHOT_ENTITIES)
Definition at line 89 of file client.h.
MAX_TIMEDEMO_DURATIONS
#define MAX_TIMEDEMO_DURATIONS 4096
Definition at line 160 of file client.h.
QKEY_FILE
#define QKEY_FILE "qkey"
Definition at line 42 of file client.h.
QKEY_SIZE
#define QKEY_SIZE 2048
Definition at line 43 of file client.h.
RETRANSMIT_TIMEOUT
#define RETRANSMIT_TIMEOUT 3000
Definition at line 45 of file client.h.
Function Documentation
CIN_CloseAllVideos()
void CIN_CloseAllVideos (void)
Definition at line 138 of file cl_cin.c.
{
     int     i;
     for ( i = 0 ; i < MAX_VIDEO_HANDLES ; i++ ) {
         if (cinTable[i].fileName[0] != 0 ) {
             CIN_StopCinematic(i);
         }
     }
 }
CIN_DrawCinematic()
void CIN_DrawCinematic (int handle)
Definition at line 1574 of file cl_cin.c.
{
     float   x, y, w, h;
     byte    *buf;
     if (handle < 0 || handle>= MAX_VIDEO_HANDLES || cinTable[handle].status == FMV_EOF) return;
     if (!cinTable[handle].buf) {
         return;
     }
     x = cinTable[handle].xpos;
     y = cinTable[handle].ypos;
     w = cinTable[handle].width;
     h = cinTable[handle].height;
     buf = cinTable[handle].buf;
     SCR_AdjustFrom640( &x, &y, &w, &h );
     if (cinTable[handle].dirty && (cinTable[handle].CIN_WIDTH != cinTable[handle].drawX || cinTable[handle].CIN_HEIGHT != cinTable[handle].drawY)) {
         int *buf2;
         buf2 = Hunk_AllocateTempMemory( 256*256*4 );
         CIN_ResampleCinematic(handle, buf2);
         re.DrawStretchRaw( x, y, w, h, 256, 256, (byte *)buf2, handle, qtrue);
         cinTable[handle].dirty = qfalse;
         Hunk_FreeTempMemory(buf2);
         return;
     }
     re.DrawStretchRaw( x, y, w, h, cinTable[handle].drawX, cinTable[handle].drawY, buf, handle, cinTable[handle].dirty);
     cinTable[handle].dirty = qfalse;
 }
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SCR_DrawCinematic().
CIN_PlayCinematic()
int CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
Definition at line 1407 of file cl_cin.c.
{
     unsigned short RoQID;
     char    name[MAX_OSPATH];
     int     i;
     if (strstr(arg, "/") == NULL && strstr(arg, "\\") == NULL) {
         Com_sprintf (name, sizeof(name), "video/%s", arg);
     } else {
         Com_sprintf (name, sizeof(name), "%s", arg);
     }
     if (!(systemBits & CIN_system)) {
         for ( i = 0 ; i < MAX_VIDEO_HANDLES ; i++ ) {
             if (!strcmp(cinTable[i].fileName, name) ) {
                 return i;
             }
         }
     }
     Com_DPrintf("CIN_PlayCinematic( %s )\n", arg);
     Com_Memset(&cin, 0, sizeof(cinematics_t) );
     currentHandle = CIN_HandleForVideo();
     cin.currentHandle = currentHandle;
     strcpy(cinTable[currentHandle].fileName, name);
     cinTable[currentHandle].ROQSize = 0;
     cinTable[currentHandle].ROQSize = FS_FOpenFileRead (cinTable[currentHandle].fileName, &cinTable[currentHandle].iFile, qtrue);
     if (cinTable[currentHandle].ROQSize<=0) {
         Com_DPrintf("play(%s), ROQSize<=0\n", arg);
         cinTable[currentHandle].fileName[0] = 0;
         return -1;
     }
     CIN_SetExtents(currentHandle, x, y, w, h);
     CIN_SetLooping(currentHandle, (systemBits & CIN_loop)!=0);
     cinTable[currentHandle].CIN_HEIGHT = DEFAULT_CIN_HEIGHT;
     cinTable[currentHandle].CIN_WIDTH  =  DEFAULT_CIN_WIDTH;
     cinTable[currentHandle].holdAtEnd = (systemBits & CIN_hold) != 0;
     cinTable[currentHandle].alterGameState = (systemBits & CIN_system) != 0;
     cinTable[currentHandle].playonwalls = 1;
     cinTable[currentHandle].silent = (systemBits & CIN_silent) != 0;
     cinTable[currentHandle].shader = (systemBits & CIN_shader) != 0;
     if (cinTable[currentHandle].alterGameState) {
         // close the menu
         if ( uivm ) {
             VM_Call( uivm, UI_SET_ACTIVE_MENU, UIMENU_NONE );
         }
     } else {
         cinTable[currentHandle].playonwalls = cl_inGameVideo->integer;
     }
     initRoQ();
     FS_Read (cin.file, 16, cinTable[currentHandle].iFile);
     RoQID = (unsigned short)(cin.file[0]) + (unsigned short)(cin.file[1])*256;
     if (RoQID == 0x1084)
     {
         RoQ_init();
 //      FS_Read (cin.file, cinTable[currentHandle].RoQFrameSize+8, cinTable[currentHandle].iFile);
         cinTable[currentHandle].status = FMV_PLAY;
         Com_DPrintf("trFMV::play(), playing %s\n", arg);
         if (cinTable[currentHandle].alterGameState) {
             clc.state = CA_CINEMATIC;
         }
         Con_Close();
         if (!cinTable[currentHandle].silent) {
             s_rawend[0] = s_soundtime;
         }
         return currentHandle;
     }
     Com_DPrintf("trFMV::play(), invalid RoQ ID\n");
     RoQShutdown();
     return -1;
 }
Referenced by CL_CgameSystemCalls(), CL_InitRef(), CL_PlayCinematic_f(), and CL_UISystemCalls().
CIN_RunCinematic()
e_status CIN_RunCinematic (int handle)
Definition at line 1336 of file cl_cin.c.
 {
     int start = 0;
     int     thisTime = 0;
     if (handle < 0 || handle>= MAX_VIDEO_HANDLES || cinTable[handle].status == FMV_EOF) return FMV_EOF;
     if (cin.currentHandle != handle) {
         currentHandle = handle;
         cin.currentHandle = currentHandle;
         cinTable[currentHandle].status = FMV_EOF;
         RoQReset();
     }
     if (cinTable[handle].playonwalls < -1)
     {
         return cinTable[handle].status;
     }
     currentHandle = handle;
     if (cinTable[currentHandle].alterGameState) {
         if ( clc.state != CA_CINEMATIC ) {
             return cinTable[currentHandle].status;
         }
     }
     if (cinTable[currentHandle].status == FMV_IDLE) {
         return cinTable[currentHandle].status;
     }
     thisTime = CL_ScaledMilliseconds();
     if (cinTable[currentHandle].shader && (abs(thisTime - cinTable[currentHandle].lastTime))>100) {
         cinTable[currentHandle].startTime += thisTime - cinTable[currentHandle].lastTime;
     }
     cinTable[currentHandle].tfps = (((CL_ScaledMilliseconds() - cinTable[currentHandle].startTime)*3)/100);
     start = cinTable[currentHandle].startTime;
     while(  (cinTable[currentHandle].tfps != cinTable[currentHandle].numQuads)
         && (cinTable[currentHandle].status == FMV_PLAY) )
     {
         RoQInterrupt();
         if (start != cinTable[currentHandle].startTime) {
             cinTable[currentHandle].tfps = (((CL_ScaledMilliseconds() - cinTable[currentHandle].startTime)*3)/100);
             start = cinTable[currentHandle].startTime;
         }
     }
     cinTable[currentHandle].lastTime = thisTime;
     if (cinTable[currentHandle].status == FMV_LOOPED) {
         cinTable[currentHandle].status = FMV_PLAY;
     }
     if (cinTable[currentHandle].status == FMV_EOF) {
       if (cinTable[currentHandle].looping) {
         RoQReset();
       } else {
         RoQShutdown();
         return FMV_EOF;
       }
     }
     return cinTable[currentHandle].status;
 }
Referenced by CL_CgameSystemCalls(), CL_InitRef(), CL_UISystemCalls(), and SCR_RunCinematic().
CIN_SetExtents()
void CIN_SetExtents (int handle, int x, int y, int w, int h)
Definition at line 1495 of file cl_cin.c.
{
     if (handle < 0 || handle>= MAX_VIDEO_HANDLES || cinTable[handle].status == FMV_EOF) return;
     cinTable[handle].xpos = x;
     cinTable[handle].ypos = y;
     cinTable[handle].width = w;
     cinTable[handle].height = h;
     cinTable[handle].dirty = qtrue;
 }
Referenced by CIN_PlayCinematic(), CL_CgameSystemCalls(), and CL_UISystemCalls().
CIN_SetLooping()
void CIN_SetLooping (int handle, qboolean loop)
Definition at line 1504 of file cl_cin.c.
{
     if (handle < 0 || handle>= MAX_VIDEO_HANDLES || cinTable[handle].status == FMV_EOF) return;
     cinTable[handle].looping = loop;
 }
Referenced by CIN_PlayCinematic().
CIN_StopCinematic()
e_status CIN_StopCinematic (int handle)
Definition at line 1305 of file cl_cin.c.
{
     if (handle < 0 || handle>= MAX_VIDEO_HANDLES || cinTable[handle].status == FMV_EOF) return FMV_EOF;
     currentHandle = handle;
     Com_DPrintf("trFMV::stop(), closing %s\n", cinTable[currentHandle].fileName);
     if (!cinTable[currentHandle].buf) {
         return FMV_EOF;
     }
     if (cinTable[currentHandle].alterGameState) {
         if ( clc.state != CA_CINEMATIC ) {
             return cinTable[currentHandle].status;
         }
     }
     cinTable[currentHandle].status = FMV_EOF;
     RoQShutdown();
     return FMV_EOF;
 }
Referenced by CIN_CloseAllVideos(), CL_CgameSystemCalls(), CL_UISystemCalls(), and SCR_StopCinematic().
CIN_UploadCinematic()
void CIN_UploadCinematic (int handle)
Definition at line 1659 of file cl_cin.c.
{
     if (handle >= 0 && handle < MAX_VIDEO_HANDLES) {
         if (!cinTable[handle].buf) {
             return;
         }
         if (cinTable[handle].playonwalls <= 0 && cinTable[handle].dirty) {
             if (cinTable[handle].playonwalls == 0) {
                 cinTable[handle].playonwalls = -1;
             } else {
                 if (cinTable[handle].playonwalls == -1) {
                     cinTable[handle].playonwalls = -2;
                 } else {
                     cinTable[handle].dirty = qfalse;
                 }
             }
         }
         // Resample the video if needed
         if (cinTable[handle].dirty && (cinTable[handle].CIN_WIDTH != cinTable[handle].drawX || cinTable[handle].CIN_HEIGHT != cinTable[handle].drawY))  {
             int *buf2;
             buf2 = Hunk_AllocateTempMemory( 256*256*4 );
             CIN_ResampleCinematic(handle, buf2);
             re.UploadCinematic( cinTable[handle].CIN_WIDTH, cinTable[handle].CIN_HEIGHT, 256, 256, (byte *)buf2, handle, qtrue);
             cinTable[handle].dirty = qfalse;
             Hunk_FreeTempMemory(buf2);
         } else {
             // Upload video at normal resolution
             re.UploadCinematic( cinTable[handle].CIN_WIDTH, cinTable[handle].CIN_HEIGHT, cinTable[handle].drawX, cinTable[handle].drawY,
                     cinTable[handle].buf, handle, cinTable[handle].dirty);
             cinTable[handle].dirty = qfalse;
         }
         if (cl_inGameVideo->integer == 0 && cinTable[handle].playonwalls == 1) {
             cinTable[handle].playonwalls--;
         }
         else if (cl_inGameVideo->integer != 0 && cinTable[handle].playonwalls != 1) {
             cinTable[handle].playonwalls = 1;
         }
     }
 }
Referenced by CL_InitRef().
CL_AddReliableCommand()
void CL_AddReliableCommand (const char * cmd, qboolean isDisconnectCmd)
Definition at line 580 of file cl_main.c.
 {
     int unacknowledged = clc.reliableSequence - clc.reliableAcknowledge;
     // if we would be losing an old command that hasn't been acknowledged,
     // we must drop the connection
     // also leave one slot open for the disconnect command in this case.
     if ((isDisconnectCmd && unacknowledged > MAX_RELIABLE_COMMANDS) ||
         (!isDisconnectCmd && unacknowledged >= MAX_RELIABLE_COMMANDS))
     {
         if(com_errorEntered)
             return;
         else
             Com_Error(ERR_DROP, "Client command overflow");
     }
     Q_strncpyz(clc.reliableCommands[++clc.reliableSequence & (MAX_RELIABLE_COMMANDS - 1)],
            cmd, sizeof(*clc.reliableCommands));
 }
Referenced by CL_BeginDownload(), CL_CgameSystemCalls(), CL_CheckUserinfo(), CL_Disconnect(), CL_DownloadsComplete(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_ParseDownload(), CL_ResetPureClientAtServer(), CL_Sayto_f(), CL_SendPureChecksums(), and Message_Key().
CL_CDKeyValidate()
qboolean CL_CDKeyValidate (const char * key, const char * checksum)
Definition at line 4649 of file cl_main.c.
{
 #ifdef STANDALONE
     return qtrue;
 #else
     char    ch;
     byte    sum;
     char    chs[3];
     int i, len;
     len = strlen(key);
     if( len != CDKEY_LEN ) {
         return qfalse;
     }
     if( checksum && strlen( checksum ) != CDCHKSUM_LEN ) {
         return qfalse;
     }
     sum = 0;
     // for loop gets rid of conditional assignment warning
     for (i = 0; i < len; i++) {
         ch = *key++;
         if (ch>='a' && ch<='z') {
             ch -= 32;
         }
         switch( ch ) {
         case '2':
         case '3':
         case '7':
         case 'A':
         case 'B':
         case 'C':
         case 'D':
         case 'G':
         case 'H':
         case 'J':
         case 'L':
         case 'P':
         case 'R':
         case 'S':
         case 'T':
         case 'W':
             sum += ch;
             continue;
         default:
             return qfalse;
         }
     }
     sprintf(chs, "%02x", sum);
     if (checksum && !Q_stricmp(chs, checksum)) {
         return qtrue;
     }
     if (!checksum) {
         return qtrue;
     }
     return qfalse;
 #endif
 }
CL_CGameRendering()
void CL_CGameRendering (stereoFrame_t stereo)
Definition at line 795 of file cl_cgame.c.
{
     VM_Call( cgvm, CG_DRAW_ACTIVE_FRAME, cl.serverTime, stereo, clc.demoplaying );
     VM_Debug( 0 );
 }
Referenced by SCR_DrawScreenField().
CL_CheckPaused()
qboolean CL_CheckPaused (void)
Definition at line 2889 of file cl_main.c.
 {
     // if cl_paused->modified is set, the cvar has only been changed in
     // this frame. Keep paused in this frame to ensure the server doesn't
     // lag behind.
     if(cl_paused->integer || cl_paused->modified)
         return qtrue;
     return qfalse;
 }
Referenced by CL_CheckTimeout(), CL_CheckUserinfo(), and CL_SetCGameTime().
CL_ClearPing()
void CL_ClearPing (int n)
Definition at line 4336 of file cl_main.c.
 {
     if (n < 0 || n >= MAX_PINGREQUESTS)
         return;
     cl_pinglist[n].adr.port = 0;
 }
Referenced by CL_UpdateVisiblePings_f(), and LAN_ClearPing().
CL_ClearState()
void CL_ClearState (void)
Definition at line 1329 of file cl_main.c.
{
 //  S_StopAllSounds();
     Com_Memset( &cl, 0, sizeof( cl ) );
 }
Referenced by CL_Disconnect(), CL_Init(), and CL_ParseGamestate().
CL_CloseAVI()
qboolean CL_CloseAVI (void)
Definition at line 593 of file cl_avi.c.
 {
   int indexRemainder;
   int indexSize = afd.numIndices * 16;
   const char *idxFileName = va( "%s" INDEX_FILE_EXTENSION, afd.fileName );
   // AVI file isn't open
   if( !afd.fileOpen )
     return qfalse;
   afd.fileOpen = qfalse;
   FS_Seek( afd.idxF, 4, FS_SEEK_SET );
   bufIndex = 0;
   WRITE_4BYTES( indexSize );
   SafeFS_Write( buffer, bufIndex, afd.idxF );
   FS_FCloseFile( afd.idxF );
   // Write index
   // Open the temp index file
   if( ( indexSize = FS_FOpenFileRead( idxFileName,
           &afd.idxF, qtrue ) ) <= 0 )
   {
     FS_FCloseFile( afd.f );
     return qfalse;
   }
   indexRemainder = indexSize;
   // Append index to end of avi file
   while( indexRemainder > MAX_AVI_BUFFER )
   {
     FS_Read( buffer, MAX_AVI_BUFFER, afd.idxF );
     SafeFS_Write( buffer, MAX_AVI_BUFFER, afd.f );
     afd.fileSize += MAX_AVI_BUFFER;
     indexRemainder -= MAX_AVI_BUFFER;
   }
   FS_Read( buffer, indexRemainder, afd.idxF );
   SafeFS_Write( buffer, indexRemainder, afd.f );
   afd.fileSize += indexRemainder;
   FS_FCloseFile( afd.idxF );
   // Remove temp index file
   FS_HomeRemove( idxFileName );
   // Write the real header
   FS_Seek( afd.f, 0, FS_SEEK_SET );
   CL_WriteAVIHeader( );
   bufIndex = 4;
   WRITE_4BYTES( afd.fileSize - 8 ); // "RIFF" size
   bufIndex = afd.moviOffset + 4;    // Skip "LIST"
   WRITE_4BYTES( afd.moviSize );
   SafeFS_Write( buffer, bufIndex, afd.f );
   Z_Free( afd.cBuffer );
   Z_Free( afd.eBuffer );
   FS_FCloseFile( afd.f );
   Com_Printf( "Wrote %d:%d frames to %s\n", afd.numVideoFrames, afd.numAudioFrames, afd.fileName );
   return qtrue;
 }
Referenced by CL_CheckFileSize(), CL_Disconnect(), CL_ShutdownAll(), CL_StopVideo_f(), and CL_Vid_Restart_f().
CL_Disconnect_f()
void CL_Disconnect_f (void)
Definition at line 1665 of file cl_main.c.
{
     SCR_StopCinematic();
     Cvar_Set("ui_singlePlayerActive", "0");
     if ( clc.state != CA_DISCONNECTED && clc.state != CA_CINEMATIC ) {
         Com_Error (ERR_DISCONNECT, "Disconnected from server");
     }
 }
Referenced by CL_Init(), and CL_KeyDownEvent().
CL_FavoriteServers_f()
void CL_FavoriteServers_f (void)
CL_FirstSnapshot()
void CL_FirstSnapshot (void)
Definition at line 878 of file cl_cgame.c.
{
     // ignore snapshots that don't have entities
     if ( cl.snap.snapFlags & SNAPFLAG_NOT_ACTIVE ) {
         return;
     }
     clc.state = CA_ACTIVE;
     // set the timedelta so we are exactly on this first frame
     cl.serverTimeDelta = cl.snap.serverTime - cls.realtime;
     cl.oldServerTime = cl.snap.serverTime;
     clc.timeDemoBaseTime = cl.snap.serverTime;
     // if this is the first frame of active play,
     // execute the contents of activeAction now
     // this is to allow scripting a timedemo to start right
     // after loading
     if ( cl_activeAction->string[0] ) {
         Cbuf_AddText( cl_activeAction->string );
         Cvar_Set( "activeAction", "" );
     }
 #ifdef USE_MUMBLE
     if ((cl_useMumble->integer) && !mumble_islinked()) {
         int ret = mumble_link(CLIENT_WINDOW_TITLE);
         Com_Printf("Mumble: Linking to Mumble application %s\n", ret==0?"ok":"failed");
     }
 #endif
 #ifdef USE_VOIP
     if (!clc.voipCodecInitialized) {
         int i;
         int error;
         clc.opusEncoder = opus_encoder_create(48000, 1, OPUS_APPLICATION_VOIP, &error);
         if ( error ) {
             Com_DPrintf("VoIP: Error opus_encoder_create %d\n", error);
             return;
         }
         for (i = 0; i < MAX_CLIENTS; i++) {
             clc.opusDecoder[i] = opus_decoder_create(48000, 1, &error);
             if ( error ) {
                 Com_DPrintf("VoIP: Error opus_decoder_create(%d) %d\n", i, error);
                 return;
             }
             clc.voipIgnore[i] = qfalse;
             clc.voipGain[i] = 1.0f;
         }
         clc.voipCodecInitialized = qtrue;
         clc.voipMuteAll = qfalse;
         Cmd_AddCommand ("voip", CL_Voip_f);
         Cvar_Set("cl_voipSendTarget", "spatial");
         Com_Memset(clc.voipTargets, ~0, sizeof(clc.voipTargets));
     }
 #endif
 }
Referenced by CL_SetCGameTime().
CL_GameCommand()
qboolean CL_GameCommand (void)
Definition at line 780 of file cl_cgame.c.
{
     if ( !cgvm ) {
         return qfalse;
     }
     return VM_Call( cgvm, CG_CONSOLE_COMMAND );
 }
CL_GetChallengePacket()
void CL_GetChallengePacket (void)
CL_GetPing()
void CL_GetPing (int n, char * buf, int buflen, int * pingtime)
Definition at line 4275 of file cl_main.c.
 {
     const char  *str;
     int     time;
     int     maxPing;
     if (n < 0 || n >= MAX_PINGREQUESTS || !cl_pinglist[n].adr.port)
     {
         // empty or invalid slot
         buf[0]    = '\0';
         *pingtime = 0;
         return;
     }
     str = NET_AdrToStringwPort( cl_pinglist[n].adr );
     Q_strncpyz( buf, str, buflen );
     time = cl_pinglist[n].time;
     if (!time)
     {
         // check for timeout
         time = Sys_Milliseconds() - cl_pinglist[n].start;
         maxPing = Cvar_VariableIntegerValue( "cl_maxPing" );
         if( maxPing < 100 ) {
             maxPing = 100;
         }
         if (time < maxPing)
         {
             // not timed out yet
             time = 0;
         }
     }
     CL_SetServerInfoByAddress(cl_pinglist[n].adr, cl_pinglist[n].info, cl_pinglist[n].time);
     *pingtime = time;
 }
Referenced by CL_UpdateVisiblePings_f(), and LAN_GetPing().
CL_GetPingInfo()
void CL_GetPingInfo (int n, char * buf, int buflen)
Definition at line 4318 of file cl_main.c.
 {
     if (n < 0 || n >= MAX_PINGREQUESTS || !cl_pinglist[n].adr.port)
     {
         // empty or invalid slot
         if (buflen)
             buf[0] = '\0';
         return;
     }
     Q_strncpyz( buf, cl_pinglist[n].info, buflen );
 }
Referenced by LAN_GetPingInfo().
CL_GetPingQueueCount()
int CL_GetPingQueueCount (void)
Definition at line 4349 of file cl_main.c.
 {
     int     i;
     int     count;
     ping_t* pingptr;
     count   = 0;
     pingptr = cl_pinglist;
     for (i=0; i<MAX_PINGREQUESTS; i++, pingptr++ ) {
         if (pingptr->adr.port) {
             count++;
         }
     }
     return (count);
 }
Referenced by CL_UpdateVisiblePings_f(), and LAN_GetPingQueueCount().
CL_GlobalServers_f()
void CL_GlobalServers_f (void)
Definition at line 4176 of file cl_main.c.
{
     netadr_t    to;
     int         count, i, masterNum;
     char        command[1024], *masteraddress;
     if ((count = Cmd_Argc()) < 3 || (masterNum = atoi(Cmd_Argv(1))) < 0 || masterNum > MAX_MASTER_SERVERS)
     {
         Com_Printf("usage: globalservers <master# 0-%d> <protocol> [keywords]\n", MAX_MASTER_SERVERS);
         return;
     }
     // request from all master servers
     if ( masterNum == 0 ) {
         int numAddress = 0;
         for ( i = 1; i <= MAX_MASTER_SERVERS; i++ ) {
             sprintf(command, "sv_master%d", i);
             masteraddress = Cvar_VariableString(command);
             if(!*masteraddress)
                 continue;
             numAddress++;
             Com_sprintf(command, sizeof(command), "globalservers %d %s %s\n", i, Cmd_Argv(2), Cmd_ArgsFrom(3));
             Cbuf_AddText(command);
         }
         if ( !numAddress ) {
             Com_Printf( "CL_GlobalServers_f: Error: No master server addresses.\n");
         }
         return;
     }
     sprintf(command, "sv_master%d", masterNum);
     masteraddress = Cvar_VariableString(command);
     if(!*masteraddress)
     {
         Com_Printf( "CL_GlobalServers_f: Error: No master server address given.\n");
         return;
     }
     // reset the list, waiting for response
     // -1 is used to distinguish a "no response"
     i = NET_StringToAdr(masteraddress, &to, NA_UNSPEC);
     if(!i)
     {
         Com_Printf( "CL_GlobalServers_f: Error: could not resolve address of master %s\n", masteraddress);
         return;
     }
     else if(i == 2)
         to.port = BigShort(PORT_MASTER);
     Com_Printf("Requesting servers from %s (%s)...\n", masteraddress, NET_AdrToStringwPort(to));
     cls.numglobalservers = -1;
     cls.pingUpdateSource = AS_GLOBAL;
     // Use the extended query for IPv6 masters
     if (to.type == NA_IP6 || to.type == NA_MULTICAST6)
     {
         int v4enabled = Cvar_VariableIntegerValue("net_enabled") & NET_ENABLEV4;
         if(v4enabled)
         {
             Com_sprintf(command, sizeof(command), "getserversExt %s %s",
                 com_gamename->string, Cmd_Argv(2));
         }
         else
         {
             Com_sprintf(command, sizeof(command), "getserversExt %s %s ipv6",
                 com_gamename->string, Cmd_Argv(2));
         }
     }
     else if ( !Q_stricmp( com_gamename->string, LEGACY_MASTER_GAMENAME ) )
         Com_sprintf(command, sizeof(command), "getservers %s",
             Cmd_Argv(2));
     else
         Com_sprintf(command, sizeof(command), "getservers %s %s",
             com_gamename->string, Cmd_Argv(2));
     for (i=3; i < count; i++)
     {
         Q_strcat(command, sizeof(command), " ");
         Q_strcat(command, sizeof(command), Cmd_Argv(i));
     }
     NET_OutOfBandPrint( NS_SERVER, to, "%s", command );
 }
Referenced by CL_Init().
CL_Init()
void CL_Init (void)
Definition at line 3496 of file cl_main.c.
                      {
     Com_Printf( "----- Client Initialization -----\n" );
     Con_Init ();
     if(!com_fullyInitialized)
     {
         CL_ClearState();
         clc.state = CA_DISCONNECTED;    // no longer CA_UNINITIALIZED
         cl_oldGameSet = qfalse;
     }
     cls.realtime = 0;
     CL_InitInput ();
     //
     // register our variables
     //
     cl_noprint = Cvar_Get( "cl_noprint", "0", 0 );
 #ifdef UPDATE_SERVER_NAME
     cl_motd = Cvar_Get ("cl_motd", "1", 0);
 #endif
     cl_timeout = Cvar_Get ("cl_timeout", "200", 0);
     cl_timeNudge = Cvar_Get ("cl_timeNudge", "0", CVAR_TEMP );
     cl_shownet = Cvar_Get ("cl_shownet", "0", CVAR_TEMP );
     cl_showSend = Cvar_Get ("cl_showSend", "0", CVAR_TEMP );
     cl_showTimeDelta = Cvar_Get ("cl_showTimeDelta", "0", CVAR_TEMP );
     cl_freezeDemo = Cvar_Get ("cl_freezeDemo", "0", CVAR_TEMP );
     rcon_client_password = Cvar_Get ("rconPassword", "", CVAR_TEMP );
     cl_activeAction = Cvar_Get( "activeAction", "", CVAR_TEMP );
     cl_timedemo = Cvar_Get ("timedemo", "0", 0);
     cl_timedemoLog = Cvar_Get ("cl_timedemoLog", "", CVAR_ARCHIVE);
     cl_autoRecordDemo = Cvar_Get ("cl_autoRecordDemo", "0", CVAR_ARCHIVE);
     cl_aviFrameRate = Cvar_Get ("cl_aviFrameRate", "25", CVAR_ARCHIVE);
     cl_aviMotionJpeg = Cvar_Get ("cl_aviMotionJpeg", "1", CVAR_ARCHIVE);
     cl_forceavidemo = Cvar_Get ("cl_forceavidemo", "0", 0);
     rconAddress = Cvar_Get ("rconAddress", "", 0);
     cl_yawspeed = Cvar_Get ("cl_yawspeed", "140", CVAR_ARCHIVE);
     cl_pitchspeed = Cvar_Get ("cl_pitchspeed", "140", CVAR_ARCHIVE);
     cl_anglespeedkey = Cvar_Get ("cl_anglespeedkey", "1.5", 0);
     cl_maxpackets = Cvar_Get ("cl_maxpackets", "30", CVAR_ARCHIVE );
     cl_packetdup = Cvar_Get ("cl_packetdup", "1", CVAR_ARCHIVE );
     cl_run = Cvar_Get ("cl_run", "1", CVAR_ARCHIVE);
     cl_sensitivity = Cvar_Get ("sensitivity", "5", CVAR_ARCHIVE);
     cl_mouseAccel = Cvar_Get ("cl_mouseAccel", "0", CVAR_ARCHIVE);
     cl_freelook = Cvar_Get( "cl_freelook", "1", CVAR_ARCHIVE );
     // 0: legacy mouse acceleration
     // 1: new implementation
     cl_mouseAccelStyle = Cvar_Get( "cl_mouseAccelStyle", "0", CVAR_ARCHIVE );
     // offset for the power function (for style 1, ignored otherwise)
     // this should be set to the max rate value
     cl_mouseAccelOffset = Cvar_Get( "cl_mouseAccelOffset", "5", CVAR_ARCHIVE );
     Cvar_CheckRange(cl_mouseAccelOffset, 0.001f, 50000.0f, qfalse);
     cl_showMouseRate = Cvar_Get ("cl_showmouserate", "0", 0);
     cl_allowDownload = Cvar_Get ("cl_allowDownload", "0", CVAR_ARCHIVE);
 #ifdef USE_CURL_DLOPEN
     cl_cURLLib = Cvar_Get("cl_cURLLib", DEFAULT_CURL_LIB, CVAR_ARCHIVE | CVAR_PROTECTED);
 #endif
     cl_conXOffset = Cvar_Get ("cl_conXOffset", "0", 0);
 #ifdef __APPLE__
     // In game video is REALLY slow in Mac OS X right now due to driver slowness
     cl_inGameVideo = Cvar_Get ("r_inGameVideo", "0", CVAR_ARCHIVE);
 #else
     cl_inGameVideo = Cvar_Get ("r_inGameVideo", "1", CVAR_ARCHIVE);
 #endif
     cl_serverStatusResendTime = Cvar_Get ("cl_serverStatusResendTime", "750", 0);
     // init autoswitch so the ui will have it correctly even
     // if the cgame hasn't been started
     Cvar_Get ("cg_autoswitch", "1", CVAR_ARCHIVE);
     m_pitch = Cvar_Get ("m_pitch", "0.022", CVAR_ARCHIVE);
     m_yaw = Cvar_Get ("m_yaw", "0.022", CVAR_ARCHIVE);
     m_forward = Cvar_Get ("m_forward", "0.25", CVAR_ARCHIVE);
     m_side = Cvar_Get ("m_side", "0.25", CVAR_ARCHIVE);
 #ifdef __APPLE__
     // Input is jittery on OS X w/o this
     m_filter = Cvar_Get ("m_filter", "1", CVAR_ARCHIVE);
 #else
     m_filter = Cvar_Get ("m_filter", "0", CVAR_ARCHIVE);
 #endif
     j_pitch =        Cvar_Get ("j_pitch",        "0.022", CVAR_ARCHIVE);
     j_yaw =          Cvar_Get ("j_yaw",          "-0.022", CVAR_ARCHIVE);
     j_forward =      Cvar_Get ("j_forward",      "-0.25", CVAR_ARCHIVE);
     j_side =         Cvar_Get ("j_side",         "0.25", CVAR_ARCHIVE);
     j_up =           Cvar_Get ("j_up",           "0", CVAR_ARCHIVE);
     j_pitch_axis =   Cvar_Get ("j_pitch_axis",   "3", CVAR_ARCHIVE);
     j_yaw_axis =     Cvar_Get ("j_yaw_axis",     "2", CVAR_ARCHIVE);
     j_forward_axis = Cvar_Get ("j_forward_axis", "1", CVAR_ARCHIVE);
     j_side_axis =    Cvar_Get ("j_side_axis",    "0", CVAR_ARCHIVE);
     j_up_axis =      Cvar_Get ("j_up_axis",      "4", CVAR_ARCHIVE);
     Cvar_CheckRange(j_pitch_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_yaw_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_forward_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_side_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     Cvar_CheckRange(j_up_axis, 0, MAX_JOYSTICK_AXIS-1, qtrue);
     cl_motdString = Cvar_Get( "cl_motdString", "", CVAR_ROM );
     Cvar_Get( "cl_maxPing", "800", CVAR_ARCHIVE );
     cl_lanForcePackets = Cvar_Get ("cl_lanForcePackets", "1", CVAR_ARCHIVE);
     cl_guidServerUniq = Cvar_Get ("cl_guidServerUniq", "1", CVAR_ARCHIVE);
     // ~ and `, as keys and characters
     cl_consoleKeys = Cvar_Get( "cl_consoleKeys", "~ ` 0x7e 0x60", CVAR_ARCHIVE);
     // userinfo
     Cvar_Get ("name", "UnnamedPlayer", CVAR_USERINFO | CVAR_ARCHIVE );
     cl_rate = Cvar_Get ("rate", "25000", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("snaps", "20", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("model", "sarge", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("headmodel", "sarge", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("team_model", "james", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("team_headmodel", "*james", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("g_redTeam", "Stroggs", CVAR_SERVERINFO | CVAR_ARCHIVE);
     Cvar_Get ("g_blueTeam", "Pagans", CVAR_SERVERINFO | CVAR_ARCHIVE);
     Cvar_Get ("color1",  "4", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("color2", "5", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("handicap", "100", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("teamtask", "0", CVAR_USERINFO );
     Cvar_Get ("sex", "male", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("cl_anonymous", "0", CVAR_USERINFO | CVAR_ARCHIVE );
     Cvar_Get ("password", "", CVAR_USERINFO);
     Cvar_Get ("cg_predictItems", "1", CVAR_USERINFO | CVAR_ARCHIVE );
 #ifdef USE_MUMBLE
     cl_useMumble = Cvar_Get ("cl_useMumble", "0", CVAR_ARCHIVE | CVAR_LATCH);
     cl_mumbleScale = Cvar_Get ("cl_mumbleScale", "0.0254", CVAR_ARCHIVE);
 #endif
 #ifdef USE_VOIP
     cl_voipSend = Cvar_Get ("cl_voipSend", "0", 0);
     cl_voipSendTarget = Cvar_Get ("cl_voipSendTarget", "spatial", 0);
     cl_voipGainDuringCapture = Cvar_Get ("cl_voipGainDuringCapture", "0.2", CVAR_ARCHIVE);
     cl_voipCaptureMult = Cvar_Get ("cl_voipCaptureMult", "2.0", CVAR_ARCHIVE);
     cl_voipUseVAD = Cvar_Get ("cl_voipUseVAD", "0", CVAR_ARCHIVE);
     cl_voipVADThreshold = Cvar_Get ("cl_voipVADThreshold", "0.25", CVAR_ARCHIVE);
     cl_voipShowMeter = Cvar_Get ("cl_voipShowMeter", "1", CVAR_ARCHIVE);
     cl_voip = Cvar_Get ("cl_voip", "1", CVAR_ARCHIVE);
     Cvar_CheckRange( cl_voip, 0, 1, qtrue );
     cl_voipProtocol = Cvar_Get ("cl_voipProtocol", cl_voip->integer ? "opus" : "", CVAR_USERINFO | CVAR_ROM);
 #endif
     // cgame might not be initialized before menu is used
     Cvar_Get ("cg_viewsize", "100", CVAR_ARCHIVE );
     // Make sure cg_stereoSeparation is zero as that variable is deprecated and should not be used anymore.
     Cvar_Get ("cg_stereoSeparation", "0", CVAR_ROM);
     //
     // register our commands
     //
     Cmd_AddCommand ("cmd", CL_ForwardToServer_f);
     Cmd_AddCommand ("configstrings", CL_Configstrings_f);
     Cmd_AddCommand ("clientinfo", CL_Clientinfo_f);
     Cmd_AddCommand ("snd_restart", CL_Snd_Restart_f);
     Cmd_AddCommand ("vid_restart", CL_Vid_Restart_f);
     Cmd_AddCommand ("disconnect", CL_Disconnect_f);
     Cmd_AddCommand ("record", CL_Record_f);
     Cmd_AddCommand ("demo", CL_PlayDemo_f);
     Cmd_SetCommandCompletionFunc( "demo", CL_CompleteDemoName );
     Cmd_AddCommand ("cinematic", CL_PlayCinematic_f);
     Cmd_AddCommand ("stoprecord", CL_StopRecord_f);
     Cmd_AddCommand ("connect", CL_Connect_f);
     Cmd_AddCommand ("reconnect", CL_Reconnect_f);
     Cmd_AddCommand ("localservers", CL_LocalServers_f);
     Cmd_AddCommand ("globalservers", CL_GlobalServers_f);
     Cmd_AddCommand ("rcon", CL_Rcon_f);
     Cmd_SetCommandCompletionFunc( "rcon", CL_CompleteRcon );
     Cmd_AddCommand ("ping", CL_Ping_f );
     Cmd_AddCommand ("serverstatus", CL_ServerStatus_f );
     Cmd_AddCommand ("showip", CL_ShowIP_f );
     Cmd_AddCommand ("fs_openedList", CL_OpenedPK3List_f );
     Cmd_AddCommand ("fs_referencedList", CL_ReferencedPK3List_f );
     Cmd_AddCommand ("model", CL_SetModel_f );
     Cmd_AddCommand ("video", CL_Video_f );
     Cmd_AddCommand ("stopvideo", CL_StopVideo_f );
     if( !com_dedicated->integer ) {
         Cmd_AddCommand ("sayto", CL_Sayto_f );
         Cmd_SetCommandCompletionFunc( "sayto", CL_CompletePlayerName );
     }
     CL_InitRef();
     SCR_Init ();
 //  Cbuf_Execute ();
     Cvar_Set( "cl_running", "1" );
     CL_GenerateQKey();
     Cvar_Get( "cl_guid", "", CVAR_USERINFO | CVAR_ROM );
     CL_UpdateGUID( NULL, 0 );
     Com_Printf( "----- Client Initialization Complete -----\n" );
 }
CL_InitCGame()
void CL_InitCGame (void)
Definition at line 711 of file cl_cgame.c.
{
     const char          *info;
     const char          *mapname;
     int                 t1, t2;
     vmInterpret_t       interpret;
     t1 = Sys_Milliseconds();
     // put away the console
     Con_Close();
     // find the current mapname
     info = cl.gameState.stringData + cl.gameState.stringOffsets[ CS_SERVERINFO ];
     mapname = Info_ValueForKey( info, "mapname" );
     Com_sprintf( cl.mapname, sizeof( cl.mapname ), "maps/%s.bsp", mapname );
     // load the dll or bytecode
     interpret = Cvar_VariableValue("vm_cgame");
     if(cl_connectedToPureServer)
     {
         // if sv_pure is set we only allow qvms to be loaded
         if(interpret != VMI_COMPILED && interpret != VMI_BYTECODE)
             interpret = VMI_COMPILED;
     }
     cgvm = VM_Create( "cgame", CL_CgameSystemCalls, interpret );
     if ( !cgvm ) {
         Com_Error( ERR_DROP, "VM_Create on cgame failed" );
     }
     clc.state = CA_LOADING;
     // init for this gamestate
     // use the lastExecutedServerCommand instead of the serverCommandSequence
     // otherwise server commands sent just before a gamestate are dropped
     VM_Call( cgvm, CG_INIT, clc.serverMessageSequence, clc.lastExecutedServerCommand, clc.clientNum );
     // reset any CVAR_CHEAT cvars registered by cgame
     if ( !clc.demoplaying && !cl_connectedToCheatServer )
         Cvar_SetCheatState();
     // we will send a usercmd this frame, which
     // will cause the server to send us the first snapshot
     clc.state = CA_PRIMED;
     t2 = Sys_Milliseconds();
     Com_Printf( "CL_InitCGame: %5.2f seconds\n", (t2-t1)/1000.0 );
     // have the renderer touch all its images, so they are present
     // on the card even if the driver does deferred loading
     re.EndRegistration();
     // make sure everything is paged in
     if (!Sys_LowPhysicalMemory()) {
         Com_TouchMemory();
     }
     // clear anything that got printed
     Con_ClearNotify ();
 }
Referenced by CL_DownloadsComplete(), and CL_Vid_Restart_f().
CL_InitDownloads()
void CL_InitDownloads (void)
Definition at line 2294 of file cl_main.c.
{
   char missingfiles[1024];
   if ( !(cl_allowDownload->integer & DLF_ENABLE) )
   {
     // autodownload is disabled on the client
     // but it's possible that some referenced files on the server are missing
     if (FS_ComparePaks( missingfiles, sizeof( missingfiles ), qfalse ) )
     {
       // NOTE TTimo I would rather have that printed as a modal message box
       //   but at this point while joining the game we don't know wether we will successfully join or not
       Com_Printf( "\nWARNING: You are missing some files referenced by the server:\n%s"
                   "You might not be able to join the game\n"
                   "Go to the setting menu to turn on autodownload, or get the file elsewhere\n\n", missingfiles );
     }
   }
   else if ( FS_ComparePaks( clc.downloadList, sizeof( clc.downloadList ) , qtrue ) ) {
     Com_Printf("Need paks: %s\n", clc.downloadList );
         if ( *clc.downloadList ) {
             // if autodownloading is not enabled on the server
             clc.state = CA_CONNECTED;
             *clc.downloadTempName = *clc.downloadName = 0;
             Cvar_Set( "cl_downloadName", "" );
             CL_NextDownload();
             return;
         }
     }
     CL_DownloadsComplete();
 }
Referenced by CL_ParseGamestate().
CL_InitInput()
void CL_InitInput (void)
Definition at line 934 of file cl_input.c.
{
     Cmd_AddCommand ("centerview",IN_CenterView);
     Cmd_AddCommand ("+moveup",IN_UpDown);
     Cmd_AddCommand ("-moveup",IN_UpUp);
     Cmd_AddCommand ("+movedown",IN_DownDown);
     Cmd_AddCommand ("-movedown",IN_DownUp);
     Cmd_AddCommand ("+left",IN_LeftDown);
     Cmd_AddCommand ("-left",IN_LeftUp);
     Cmd_AddCommand ("+right",IN_RightDown);
     Cmd_AddCommand ("-right",IN_RightUp);
     Cmd_AddCommand ("+forward",IN_ForwardDown);
     Cmd_AddCommand ("-forward",IN_ForwardUp);
     Cmd_AddCommand ("+back",IN_BackDown);
     Cmd_AddCommand ("-back",IN_BackUp);
     Cmd_AddCommand ("+lookup", IN_LookupDown);
     Cmd_AddCommand ("-lookup", IN_LookupUp);
     Cmd_AddCommand ("+lookdown", IN_LookdownDown);
     Cmd_AddCommand ("-lookdown", IN_LookdownUp);
     Cmd_AddCommand ("+strafe", IN_StrafeDown);
     Cmd_AddCommand ("-strafe", IN_StrafeUp);
     Cmd_AddCommand ("+moveleft", IN_MoveleftDown);
     Cmd_AddCommand ("-moveleft", IN_MoveleftUp);
     Cmd_AddCommand ("+moveright", IN_MoverightDown);
     Cmd_AddCommand ("-moveright", IN_MoverightUp);
     Cmd_AddCommand ("+speed", IN_SpeedDown);
     Cmd_AddCommand ("-speed", IN_SpeedUp);
     Cmd_AddCommand ("+attack", IN_Button0Down);
     Cmd_AddCommand ("-attack", IN_Button0Up);
     Cmd_AddCommand ("+button0", IN_Button0Down);
     Cmd_AddCommand ("-button0", IN_Button0Up);
     Cmd_AddCommand ("+button1", IN_Button1Down);
     Cmd_AddCommand ("-button1", IN_Button1Up);
     Cmd_AddCommand ("+button2", IN_Button2Down);
     Cmd_AddCommand ("-button2", IN_Button2Up);
     Cmd_AddCommand ("+button3", IN_Button3Down);
     Cmd_AddCommand ("-button3", IN_Button3Up);
     Cmd_AddCommand ("+button4", IN_Button4Down);
     Cmd_AddCommand ("-button4", IN_Button4Up);
     Cmd_AddCommand ("+button5", IN_Button5Down);
     Cmd_AddCommand ("-button5", IN_Button5Up);
     Cmd_AddCommand ("+button6", IN_Button6Down);
     Cmd_AddCommand ("-button6", IN_Button6Up);
     Cmd_AddCommand ("+button7", IN_Button7Down);
     Cmd_AddCommand ("-button7", IN_Button7Up);
     Cmd_AddCommand ("+button8", IN_Button8Down);
     Cmd_AddCommand ("-button8", IN_Button8Up);
     Cmd_AddCommand ("+button9", IN_Button9Down);
     Cmd_AddCommand ("-button9", IN_Button9Up);
     Cmd_AddCommand ("+button10", IN_Button10Down);
     Cmd_AddCommand ("-button10", IN_Button10Up);
     Cmd_AddCommand ("+button11", IN_Button11Down);
     Cmd_AddCommand ("-button11", IN_Button11Up);
     Cmd_AddCommand ("+button12", IN_Button12Down);
     Cmd_AddCommand ("-button12", IN_Button12Up);
     Cmd_AddCommand ("+button13", IN_Button13Down);
     Cmd_AddCommand ("-button13", IN_Button13Up);
     Cmd_AddCommand ("+button14", IN_Button14Down);
     Cmd_AddCommand ("-button14", IN_Button14Up);
     Cmd_AddCommand ("+mlook", IN_MLookDown);
     Cmd_AddCommand ("-mlook", IN_MLookUp);
 #ifdef USE_VOIP
     Cmd_AddCommand ("+voiprecord", IN_VoipRecordDown);
     Cmd_AddCommand ("-voiprecord", IN_VoipRecordUp);
 #endif
     cl_nodelta = Cvar_Get ("cl_nodelta", "0", 0);
     cl_debugMove = Cvar_Get ("cl_debugMove", "0", 0);
 }
Referenced by CL_Init().
CL_InitRef()
void CL_InitRef (void)
Definition at line 3201 of file cl_main.c.
{
     refimport_t ri;
     refexport_t *ret;
 #ifdef USE_RENDERER_DLOPEN
     GetRefAPI_t     GetRefAPI;
     char            dllName[MAX_OSPATH];
 #endif
     Com_Printf( "----- Initializing Renderer ----\n" );
 #ifdef USE_RENDERER_DLOPEN
     cl_renderer = Cvar_Get("cl_renderer", "opengl2", CVAR_ARCHIVE | CVAR_LATCH);
     Com_sprintf(dllName, sizeof(dllName), "renderer_%s_" ARCH_STRING DLL_EXT, cl_renderer->string);
     if(!(rendererLib = Sys_LoadDll(dllName, qfalse)) && strcmp(cl_renderer->string, cl_renderer->resetString))
     {
         Com_Printf("failed:\n\"%s\"\n", Sys_LibraryError());
         Cvar_ForceReset("cl_renderer");
         Com_sprintf(dllName, sizeof(dllName), "renderer_opengl2_" ARCH_STRING DLL_EXT);
         rendererLib = Sys_LoadDll(dllName, qfalse);
     }
     if(!rendererLib)
     {
         Com_Printf("failed:\n\"%s\"\n", Sys_LibraryError());
         Com_Error(ERR_FATAL, "Failed to load renderer");
     }
     GetRefAPI = Sys_LoadFunction(rendererLib, "GetRefAPI");
     if(!GetRefAPI)
     {
         Com_Error(ERR_FATAL, "Can't load symbol GetRefAPI: '%s'",  Sys_LibraryError());
     }
 #endif
     ri.Cmd_AddCommand = Cmd_AddCommand;
     ri.Cmd_RemoveCommand = Cmd_RemoveCommand;
     ri.Cmd_Argc = Cmd_Argc;
     ri.Cmd_Argv = Cmd_Argv;
     ri.Cmd_ExecuteText = Cbuf_ExecuteText;
     ri.Printf = CL_RefPrintf;
     ri.Error = Com_Error;
     ri.Milliseconds = CL_ScaledMilliseconds;
     ri.Malloc = CL_RefMalloc;
     ri.Free = Z_Free;
 #ifdef HUNK_DEBUG
     ri.Hunk_AllocDebug = Hunk_AllocDebug;
 #else
     ri.Hunk_Alloc = Hunk_Alloc;
 #endif
     ri.Hunk_AllocateTempMemory = Hunk_AllocateTempMemory;
     ri.Hunk_FreeTempMemory = Hunk_FreeTempMemory;
     ri.CM_ClusterPVS = CM_ClusterPVS;
     ri.CM_DrawDebugSurface = CM_DrawDebugSurface;
     ri.FS_ReadFile = FS_ReadFile;
     ri.FS_FreeFile = FS_FreeFile;
     ri.FS_WriteFile = FS_WriteFile;
     ri.FS_FreeFileList = FS_FreeFileList;
     ri.FS_ListFiles = FS_ListFiles;
     ri.FS_FileIsInPAK = FS_FileIsInPAK;
     ri.FS_FileExists = FS_FileExists;
     ri.Cvar_Get = Cvar_Get;
     ri.Cvar_Set = Cvar_Set;
     ri.Cvar_SetValue = Cvar_SetValue;
     ri.Cvar_CheckRange = Cvar_CheckRange;
     ri.Cvar_SetDescription = Cvar_SetDescription;
     ri.Cvar_VariableIntegerValue = Cvar_VariableIntegerValue;
     // cinematic stuff
     ri.CIN_UploadCinematic = CIN_UploadCinematic;
     ri.CIN_PlayCinematic = CIN_PlayCinematic;
     ri.CIN_RunCinematic = CIN_RunCinematic;
     ri.CL_WriteAVIVideoFrame = CL_WriteAVIVideoFrame;
     ri.IN_Init = IN_Init;
     ri.IN_Shutdown = IN_Shutdown;
     ri.IN_Restart = IN_Restart;
     ri.ftol = Q_ftol;
     ri.Sys_SetEnv = Sys_SetEnv;
     ri.Sys_GLimpSafeInit = Sys_GLimpSafeInit;
     ri.Sys_GLimpInit = Sys_GLimpInit;
     ri.Sys_LowPhysicalMemory = Sys_LowPhysicalMemory;
     ret = GetRefAPI( REF_API_VERSION, &ri );
 #if defined __USEA3D && defined __A3D_GEOM
     hA3Dg_ExportRenderGeom (ret);
 #endif
     Com_Printf( "-------------------------------\n");
     if ( !ret ) {
         Com_Error (ERR_FATAL, "Couldn't initialize refresh" );
     }
     re = *ret;
     // unpause so the cgame definitely gets a snapshot and renders a frame
     Cvar_Set( "cl_paused", "0" );
 }
CL_InitUI()
void CL_InitUI (void)
Definition at line 1106 of file cl_ui.c.
{
     int     v;
     vmInterpret_t       interpret;
     // load the dll or bytecode
     interpret = Cvar_VariableValue("vm_ui");
     if(cl_connectedToPureServer)
     {
         // if sv_pure is set we only allow qvms to be loaded
         if(interpret != VMI_COMPILED && interpret != VMI_BYTECODE)
             interpret = VMI_COMPILED;
     }
     uivm = VM_Create( "ui", CL_UISystemCalls, interpret );
     if ( !uivm ) {
         Com_Error( ERR_FATAL, "VM_Create on UI failed" );
     }
     // sanity check
     v = VM_Call( uivm, UI_GETAPIVERSION );
     if (v == UI_OLD_API_VERSION) {
 //      Com_Printf(S_COLOR_YELLOW "WARNING: loading old Quake III Arena User Interface version %d\n", v );
         // init for this gamestate
         VM_Call( uivm, UI_INIT, (clc.state >= CA_AUTHORIZING && clc.state < CA_ACTIVE));
     }
     else if (v != UI_API_VERSION) {
         // Free uivm now, so UI_SHUTDOWN doesn't get called later.
         VM_Free( uivm );
         uivm = NULL;
         Com_Error( ERR_DROP, "User Interface is version %d, expected %d", v, UI_API_VERSION );
         cls.uiStarted = qfalse;
     }
     else {
         // init for this gamestate
         VM_Call( uivm, UI_INIT, (clc.state >= CA_AUTHORIZING && clc.state < CA_ACTIVE) );
     }
 }
Referenced by CL_StartHunkUsers().
CL_KeyState()
float CL_KeyState (kbutton_t * key)
Definition at line 161 of file cl_input.c.
{
     float       val;
     int         msec;
     msec = key->msec;
     key->msec = 0;
     if ( key->active ) {
         // still down
         if ( !key->downtime ) {
             msec = com_frameTime;
         } else {
             msec += com_frameTime - key->downtime;
         }
         key->downtime = com_frameTime;
     }
 #if 0
     if (msec) {
         Com_Printf ("%i ", msec);
     }
 #endif
     val = (float)msec / frame_msec;
     if ( val < 0 ) {
         val = 0;
     }
     if ( val > 1 ) {
         val = 1;
     }
     return val;
 }
Referenced by CL_AdjustAngles(), and CL_KeyMove().
CL_LoadConsoleHistory()
void CL_LoadConsoleHistory (void)
Definition at line 1466 of file cl_keys.c.
 {
     char                    *token, *text_p;
     int                     i, numChars, numLines = 0;
     fileHandle_t    f;
     consoleSaveBufferSize = FS_FOpenFileRead( CONSOLE_HISTORY_FILE, &f, qfalse );
     if( !f )
     {
         Com_Printf( "Couldn't read %s.\n", CONSOLE_HISTORY_FILE );
         return;
     }
     if( consoleSaveBufferSize < MAX_CONSOLE_SAVE_BUFFER &&
             FS_Read( consoleSaveBuffer, consoleSaveBufferSize, f ) == consoleSaveBufferSize )
     {
         consoleSaveBuffer[consoleSaveBufferSize] = '\0';
         text_p = consoleSaveBuffer;
         for( i = COMMAND_HISTORY - 1; i >= 0; i-- )
         {
             if( !*( token = COM_Parse( &text_p ) ) )
                 break;
             historyEditLines[ i ].cursor = atoi( token );
             if( !*( token = COM_Parse( &text_p ) ) )
                 break;
             historyEditLines[ i ].scroll = atoi( token );
             if( !*( token = COM_Parse( &text_p ) ) )
                 break;
             numChars = atoi( token );
             text_p++;
             if( numChars > ( strlen( consoleSaveBuffer ) -  ( text_p - consoleSaveBuffer ) ) )
             {
                 Com_DPrintf( S_COLOR_YELLOW "WARNING: probable corrupt history\n" );
                 break;
             }
             Com_Memcpy( historyEditLines[ i ].buffer,
                     text_p, numChars );
             historyEditLines[ i ].buffer[ numChars ] = '\0';
             text_p += numChars;
             numLines++;
         }
         memmove( &historyEditLines[ 0 ], &historyEditLines[ i + 1 ],
                 numLines * sizeof( field_t ) );
         for( i = numLines; i < COMMAND_HISTORY; i++ )
             Field_Clear( &historyEditLines[ i ] );
         historyLine = nextHistoryLine = numLines;
     }
     else
         Com_Printf( "Couldn't read %s.\n", CONSOLE_HISTORY_FILE );
     FS_FCloseFile( f );
 }
Referenced by Con_Init().
CL_LocalServers_f()
void CL_LocalServers_f (void)
Definition at line 4128 of file cl_main.c.
{
     char        *message;
     int         i, j;
     netadr_t    to;
     Com_Printf( "Scanning for servers on the local network...\n");
     // reset the list, waiting for response
     cls.numlocalservers = 0;
     cls.pingUpdateSource = AS_LOCAL;
     for (i = 0; i < MAX_OTHER_SERVERS; i++) {
         qboolean b = cls.localServers[i].visible;
         Com_Memset(&cls.localServers[i], 0, sizeof(cls.localServers[i]));
         cls.localServers[i].visible = b;
     }
     Com_Memset( &to, 0, sizeof( to ) );
     // The 'xxx' in the message is a challenge that will be echoed back
     // by the server.  We don't care about that here, but master servers
     // can use that to prevent spoofed server responses from invalid ip
     message = "\377\377\377\377getinfo xxx";
     // send each message twice in case one is dropped
     for ( i = 0 ; i < 2 ; i++ ) {
         // send a broadcast packet on each server port
         // we support multiple server ports so a single machine
         // can nicely run multiple servers
         for ( j = 0 ; j < NUM_SERVER_PORTS ; j++ ) {
             to.port = BigShort( (short)(PORT_SERVER + j) );
             to.type = NA_BROADCAST;
             NET_SendPacket( NS_CLIENT, strlen( message ), message, to );
             to.type = NA_MULTICAST6;
             NET_SendPacket( NS_CLIENT, strlen( message ), message, to );
         }
     }
 }
Referenced by CL_Init().
CL_Netchan_Process()
qboolean CL_Netchan_Process (netchan_t * chan, msg_t * msg)
Definition at line 174 of file cl_net_chan.c.
{
     int ret;
     ret = Netchan_Process( chan, msg );
     if (!ret)
         return qfalse;
 #ifdef LEGACY_PROTOCOL
     if(chan->compat)
         CL_Netchan_Decode(msg);
 #endif
     return qtrue;
 }
Referenced by CL_PacketEvent().
CL_Netchan_Transmit()
void CL_Netchan_Transmit (netchan_t * chan, msg_t * msg)
Definition at line 152 of file cl_net_chan.c.
{
     MSG_WriteByte( msg, clc_EOF );
 #ifdef LEGACY_PROTOCOL
     if(chan->compat)
         CL_Netchan_Encode(msg);
 #endif
     Netchan_Transmit(chan, msg->cursize, msg->data);
     // Transmit all fragments without delay
     while(CL_Netchan_TransmitNextFragment(chan))
     {
         Com_DPrintf("WARNING: #462 unsent fragments (not supposed to happen!)\n");
     }
 }
Referenced by CL_WritePacket().
CL_NextDemo()
void CL_NextDemo (void)
Definition at line 1181 of file cl_main.c.
{
     char    v[MAX_STRING_CHARS];
     Q_strncpyz( v, Cvar_VariableString ("nextdemo"), sizeof(v) );
     v[MAX_STRING_CHARS-1] = 0;
     Com_DPrintf("CL_NextDemo: %s\n", v );
     if (!v[0]) {
         return;
     }
     Cvar_Set ("nextdemo","");
     Cbuf_AddText (v);
     Cbuf_AddText ("\n");
     Cbuf_Execute();
 }
Referenced by CL_DemoCompleted().
CL_NextDownload()
void CL_NextDownload (void)
Definition at line 2192 of file cl_main.c.
 {
     char *s;
     char *remoteName, *localName;
     qboolean useCURL = qfalse;
     // A download has finished, check whether this matches a referenced checksum
     if(*clc.downloadName)
     {
         char *zippath = FS_BuildOSPath(Cvar_VariableString("fs_homepath"), clc.downloadName, "");
         zippath[strlen(zippath)-1] = '\0';
         if(!FS_CompareZipChecksum(zippath))
             Com_Error(ERR_DROP, "Incorrect checksum for file: %s", clc.downloadName);
     }
     *clc.downloadTempName = *clc.downloadName = 0;
     Cvar_Set("cl_downloadName", "");
     // We are looking to start a download here
     if (*clc.downloadList) {
         s = clc.downloadList;
         // format is:
         //  @remotename@localname@remotename@localname, etc.
         if (*s == '@')
             s++;
         remoteName = s;
         if ( (s = strchr(s, '@')) == NULL ) {
             CL_DownloadsComplete();
             return;
         }
         *s++ = 0;
         localName = s;
         if ( (s = strchr(s, '@')) != NULL )
             *s++ = 0;
         else
             s = localName + strlen(localName); // point at the nul byte
 #ifdef USE_CURL
         if(!(cl_allowDownload->integer & DLF_NO_REDIRECT)) {
             if(clc.sv_allowDownload & DLF_NO_REDIRECT) {
                 Com_Printf("WARNING: server does not "
                     "allow download redirection "
                     "(sv_allowDownload is %d)\n",
                     clc.sv_allowDownload);
             }
             else if(!*clc.sv_dlURL) {
                 Com_Printf("WARNING: server allows "
                     "download redirection, but does not "
                     "have sv_dlURL set\n");
             }
             else if(!CL_cURL_Init()) {
                 Com_Printf("WARNING: could not load "
                     "cURL library\n");
             }
             else {
                 CL_cURL_BeginDownload(localName, va("%s/%s",
                     clc.sv_dlURL, remoteName));
                 useCURL = qtrue;
             }
         }
         else if(!(clc.sv_allowDownload & DLF_NO_REDIRECT)) {
             Com_Printf("WARNING: server allows download "
                 "redirection, but it disabled by client "
                 "configuration (cl_allowDownload is %d)\n",
                 cl_allowDownload->integer);
         }
 #endif /* USE_CURL */
         if(!useCURL) {
             if((cl_allowDownload->integer & DLF_NO_UDP)) {
                 Com_Error(ERR_DROP, "UDP Downloads are "
                     "disabled on your client. "
                     "(cl_allowDownload is %d)",
                     cl_allowDownload->integer);
                 return;
             }
             else {
                 CL_BeginDownload( localName, remoteName );
             }
         }
         clc.downloadRestart = qtrue;
         // move over the rest
         memmove( clc.downloadList, s, strlen(s) + 1);
         return;
     }
     CL_DownloadsComplete();
 }
Referenced by CL_InitDownloads(), and CL_ParseDownload().
CL_OpenAVIForWriting()
qboolean CL_OpenAVIForWriting (const char * filename)
Definition at line 324 of file cl_avi.c.
 {
   if( afd.fileOpen )
     return qfalse;
   Com_Memset( &afd, 0, sizeof( aviFileData_t ) );
   // Don't start if a framerate has not been chosen
   if( cl_aviFrameRate->integer <= 0 )
   {
     Com_Printf( S_COLOR_RED "cl_aviFrameRate must be >= 1\n" );
     return qfalse;
   }
   if( ( afd.f = FS_FOpenFileWrite( fileName ) ) <= 0 )
     return qfalse;
   if( ( afd.idxF = FS_FOpenFileWrite(
           va( "%s" INDEX_FILE_EXTENSION, fileName ) ) ) <= 0 )
   {
     FS_FCloseFile( afd.f );
     return qfalse;
   }
   Q_strncpyz( afd.fileName, fileName, MAX_QPATH );
   afd.frameRate = cl_aviFrameRate->integer;
   afd.framePeriod = (int)( 1000000.0f / afd.frameRate );
   afd.width = cls.glconfig.vidWidth;
   afd.height = cls.glconfig.vidHeight;
   if( cl_aviMotionJpeg->integer )
     afd.motionJpeg = qtrue;
   else
     afd.motionJpeg = qfalse;
   // Buffers only need to store RGB pixels.
   // Allocate a bit more space for the capture buffer to account for possible
   // padding at the end of pixel lines, and padding for alignment
   #define MAX_PACK_LEN 16
   afd.cBuffer = Z_Malloc((afd.width * 3 + MAX_PACK_LEN - 1) * afd.height + MAX_PACK_LEN - 1);
   // raw avi files have pixel lines start on 4-byte boundaries
   afd.eBuffer = Z_Malloc(PAD(afd.width * 3, AVI_LINE_PADDING) * afd.height);
   afd.a.rate = dma.speed;
   afd.a.format = WAV_FORMAT_PCM;
   afd.a.channels = dma.channels;
   /* !!! FIXME: if CL_WriteAVIAudioFrame() is ever called from somewhere other
      !!! FIXME:  than S_TransferStereo16(), we will need to handle/convert
      !!! FIXME:  float32 samples for AVI writing. */
   afd.a.bits = dma.samplebits;
   afd.a.sampleSize = ( afd.a.bits / 8 ) * afd.a.channels;
   if( afd.a.rate % afd.frameRate )
   {
     int suggestRate = afd.frameRate;
     while( ( afd.a.rate % suggestRate ) && suggestRate >= 1 )
       suggestRate--;
     Com_Printf( S_COLOR_YELLOW "WARNING: cl_aviFrameRate is not a divisor "
         "of the audio rate, suggest %d\n", suggestRate );
   }
   if( !Cvar_VariableIntegerValue( "s_initsound" ) )
   {
     afd.audio = qfalse;
   }
   else if( Q_stricmp( Cvar_VariableString( "s_backend" ), "OpenAL" ) )
   {
     if( afd.a.bits != 16 || afd.a.channels != 2 )
     {
       Com_Printf( S_COLOR_YELLOW "WARNING: Audio format of %d bit/%d channels not supported",
           afd.a.bits, afd.a.channels );
       afd.audio = qfalse;
     }
     else
       afd.audio = qtrue;
   }
   else
   {
     afd.audio = qfalse;
     Com_Printf( S_COLOR_YELLOW "WARNING: Audio capture is not supported "
         "with OpenAL. Set s_useOpenAL to 0 for audio capture\n" );
   }
   // This doesn't write a real header, but allocates the
   // correct amount of space at the beginning of the file
   CL_WriteAVIHeader( );
   SafeFS_Write( buffer, bufIndex, afd.f );
   afd.fileSize = bufIndex;
   bufIndex = 0;
   START_CHUNK( "idx1" );
   SafeFS_Write( buffer, bufIndex, afd.idxF );
   afd.moviSize = 4; // For the "movi"
   afd.fileOpen = qtrue;
   return qtrue;
 }
Referenced by CL_CheckFileSize(), and CL_Video_f().
CL_ParseServerMessage()
void CL_ParseServerMessage (msg_t * msg)
Definition at line 858 of file cl_parse.c.
{
     int         cmd;
     if ( cl_shownet->integer == 1 ) {
         Com_Printf ("%i ",msg->cursize);
     } else if ( cl_shownet->integer >= 2 ) {
         Com_Printf ("------------------\n");
     }
     MSG_Bitstream(msg);
     // get the reliable sequence acknowledge number
     clc.reliableAcknowledge = MSG_ReadLong( msg );
     //
     if ( clc.reliableAcknowledge < clc.reliableSequence - MAX_RELIABLE_COMMANDS ) {
         clc.reliableAcknowledge = clc.reliableSequence;
     }
     //
     // parse the message
     //
     while ( 1 ) {
         if ( msg->readcount > msg->cursize ) {
             Com_Error (ERR_DROP,"CL_ParseServerMessage: read past end of server message");
             break;
         }
         cmd = MSG_ReadByte( msg );
         if (cmd == svc_EOF) {
             SHOWNET( msg, "END OF MESSAGE" );
             break;
         }
         if ( cl_shownet->integer >= 2 ) {
             if ( (cmd < 0) || (!svc_strings[cmd]) ) {
                 Com_Printf( "%3i:BAD CMD %i\n", msg->readcount-1, cmd );
             } else {
                 SHOWNET( msg, svc_strings[cmd] );
             }
         }
     // other commands
         switch ( cmd ) {
         default:
             Com_Error (ERR_DROP,"CL_ParseServerMessage: Illegible server message");
             break;
         case svc_nop:
             break;
         case svc_serverCommand:
             CL_ParseCommandString( msg );
             break;
         case svc_gamestate:
             CL_ParseGamestate( msg );
             break;
         case svc_snapshot:
             CL_ParseSnapshot( msg );
             break;
         case svc_download:
             CL_ParseDownload( msg );
             break;
         case svc_voipSpeex:
 #ifdef USE_VOIP
             CL_ParseVoip( msg, qtrue );
 #endif
             break;
         case svc_voipOpus:
 #ifdef USE_VOIP
             CL_ParseVoip( msg, !clc.voipEnabled );
 #endif
             break;
         }
     }
 }
Referenced by CL_PacketEvent(), and CL_ReadDemoMessage().
CL_Ping_f()
void CL_Ping_f (void)
Definition at line 4429 of file cl_main.c.
{
     netadr_t    to;
     ping_t*     pingptr;
     char*       server;
     int         argc;
     netadrtype_t    family = NA_UNSPEC;
     argc = Cmd_Argc();
     if ( argc != 2 && argc != 3 ) {
         Com_Printf( "usage: ping [-4|-6] server\n");
         return;
     }
     if(argc == 2)
         server = Cmd_Argv(1);
     else
     {
         if(!strcmp(Cmd_Argv(1), "-4"))
             family = NA_IP;
         else if(!strcmp(Cmd_Argv(1), "-6"))
             family = NA_IP6;
         else
             Com_Printf( "warning: only -4 or -6 as address type understood.\n");
         server = Cmd_Argv(2);
     }
     Com_Memset( &to, 0, sizeof(netadr_t) );
     if ( !NET_StringToAdr( server, &to, family ) ) {
         return;
     }
     pingptr = CL_GetFreePing();
     memcpy( &pingptr->adr, &to, sizeof (netadr_t) );
     pingptr->start = Sys_Milliseconds();
     pingptr->time  = 0;
     CL_SetServerInfoByAddress(pingptr->adr, NULL, 0);
     NET_OutOfBandPrint( NS_CLIENT, to, "getinfo xxx" );
 }
Referenced by CL_Init().
CL_PlayCinematic_f()
void CL_PlayCinematic_f (void)
Definition at line 1608 of file cl_cin.c.
{
     char    *arg, *s;
     int bits = CIN_system;
     Com_DPrintf("CL_PlayCinematic_f\n");
     if (clc.state == CA_CINEMATIC) {
         SCR_StopCinematic();
     }
     arg = Cmd_Argv( 1 );
     s = Cmd_Argv(2);
     if ((s && s[0] == '1') || Q_stricmp(arg,"demoend.roq")==0 || Q_stricmp(arg,"end.roq")==0) {
         bits |= CIN_hold;
     }
     if (s && s[0] == '2') {
         bits |= CIN_loop;
     }
     S_StopAllSounds ();
     CL_handle = CIN_PlayCinematic( arg, 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, bits );
     if (CL_handle >= 0) {
         do {
             SCR_RunCinematic();
         } while (cinTable[currentHandle].buf == NULL && cinTable[currentHandle].status == FMV_PLAY);        // wait for first frame (load codebook and sound)
     }
 }
Referenced by CL_Init().
CL_ReadDemoMessage()
void CL_ReadDemoMessage (void)
Definition at line 935 of file cl_main.c.
{
     int         r;
     msg_t       buf;
     byte        bufData[ MAX_MSGLEN ];
     int         s;
     if ( !clc.demofile ) {
         CL_DemoCompleted ();
         return;
     }
     // get the sequence number
     r = FS_Read( &s, 4, clc.demofile);
     if ( r != 4 ) {
         CL_DemoCompleted ();
         return;
     }
     clc.serverMessageSequence = LittleLong( s );
     // init the message
     MSG_Init( &buf, bufData, sizeof( bufData ) );
     // get the length
     r = FS_Read (&buf.cursize, 4, clc.demofile);
     if ( r != 4 ) {
         CL_DemoCompleted ();
         return;
     }
     buf.cursize = LittleLong( buf.cursize );
     if ( buf.cursize == -1 ) {
         CL_DemoCompleted ();
         return;
     }
     if ( buf.cursize > buf.maxsize ) {
         Com_Error (ERR_DROP, "CL_ReadDemoMessage: demoMsglen > MAX_MSGLEN");
     }
     r = FS_Read( buf.data, buf.cursize, clc.demofile );
     if ( r != buf.cursize ) {
         Com_Printf( "Demo file was truncated.\n");
         CL_DemoCompleted ();
         return;
     }
     clc.lastPacketTime = cls.realtime;
     buf.readcount = 0;
     CL_ParseServerMessage( &buf );
 }
Referenced by CL_PlayDemo_f(), and CL_SetCGameTime().
CL_ReadPackets()
void CL_ReadPackets (void)
CL_SaveConsoleHistory()
void CL_SaveConsoleHistory (void)
Definition at line 1536 of file cl_keys.c.
 {
     int                     i;
     int                     lineLength, saveBufferLength, additionalLength;
     fileHandle_t    f;
     consoleSaveBuffer[ 0 ] = '\0';
     i = ( nextHistoryLine - 1 ) % COMMAND_HISTORY;
     do
     {
         if( historyEditLines[ i ].buffer[ 0 ] )
         {
             lineLength = strlen( historyEditLines[ i ].buffer );
             saveBufferLength = strlen( consoleSaveBuffer );
             //ICK
             additionalLength = lineLength + strlen( "999 999 999  " );
             if( saveBufferLength + additionalLength < MAX_CONSOLE_SAVE_BUFFER )
             {
                 Q_strcat( consoleSaveBuffer, MAX_CONSOLE_SAVE_BUFFER,
                         va( "%d %d %d %s ",
                         historyEditLines[ i ].cursor,
                         historyEditLines[ i ].scroll,
                         lineLength,
                         historyEditLines[ i ].buffer ) );
             }
             else
                 break;
         }
         i = ( i - 1 + COMMAND_HISTORY ) % COMMAND_HISTORY;
     }
     while( i != ( nextHistoryLine - 1 ) % COMMAND_HISTORY );
     consoleSaveBufferSize = strlen( consoleSaveBuffer );
     f = FS_FOpenFileWrite( CONSOLE_HISTORY_FILE );
     if( !f )
     {
         Com_Printf( "Couldn't write %s.\n", CONSOLE_HISTORY_FILE );
         return;
     }
     if( FS_Write( consoleSaveBuffer, consoleSaveBufferSize, f ) < consoleSaveBufferSize )
         Com_Printf( "Couldn't write %s.\n", CONSOLE_HISTORY_FILE );
     FS_FCloseFile( f );
 }
Referenced by Console_Key().
CL_SendCmd()
void CL_SendCmd (void)
Definition at line 904 of file cl_input.c.
{
     // don't send any message if not connected
     if ( clc.state < CA_CONNECTED ) {
         return;
     }
     // don't send commands if paused
     if ( com_sv_running->integer && sv_paused->integer && cl_paused->integer ) {
         return;
     }
     // we create commands even if a demo is playing,
     CL_CreateNewCommands();
     // don't send a packet if the last packet was sent too recently
     if ( !CL_ReadyToSendPacket() ) {
         if ( cl_showSend->integer ) {
             Com_Printf( ". " );
         }
         return;
     }
     CL_WritePacket();
 }
Referenced by CL_Frame().
CL_ServerInfoPacket()
void CL_ServerInfoPacket (netadr_t from, msg_t * msg)
Definition at line 3829 of file cl_main.c.
{
     int     i, type;
     char    info[MAX_INFO_STRING];
     char    *infoString;
     int     prot;
     char    *gamename;
     qboolean gameMismatch;
     infoString = MSG_ReadString( msg );
     // if this isn't the correct gamename, ignore it
     gamename = Info_ValueForKey( infoString, "gamename" );
 #ifdef LEGACY_PROTOCOL
     // gamename is optional for legacy protocol
     if (com_legacyprotocol->integer && !*gamename)
         gameMismatch = qfalse;
     else
 #endif
         gameMismatch = !*gamename || strcmp(gamename, com_gamename->string) != 0;
     if (gameMismatch)
     {
         Com_DPrintf( "Game mismatch in info packet: %s\n", infoString );
         return;
     }
     // if this isn't the correct protocol version, ignore it
     prot = atoi( Info_ValueForKey( infoString, "protocol" ) );
     if(prot != com_protocol->integer
 #ifdef LEGACY_PROTOCOL
        && prot != com_legacyprotocol->integer
 #endif
       )
     {
         Com_DPrintf( "Different protocol info packet: %s\n", infoString );
         return;
     }
     // iterate servers waiting for ping response
     for (i=0; i<MAX_PINGREQUESTS; i++)
     {
         if ( cl_pinglist[i].adr.port && !cl_pinglist[i].time && NET_CompareAdr( from, cl_pinglist[i].adr ) )
         {
             // calc ping time
             cl_pinglist[i].time = Sys_Milliseconds() - cl_pinglist[i].start;
             Com_DPrintf( "ping time %dms from %s\n", cl_pinglist[i].time, NET_AdrToString( from ) );
             // save of info
             Q_strncpyz( cl_pinglist[i].info, infoString, sizeof( cl_pinglist[i].info ) );
             // tack on the net type
             // NOTE: make sure these types are in sync with the netnames strings in the UI
             switch (from.type)
             {
                 case NA_BROADCAST:
                 case NA_IP:
                     type = 1;
                     break;
                 case NA_IP6:
                     type = 2;
                     break;
                 default:
                     type = 0;
                     break;
             }
             Info_SetValueForKey( cl_pinglist[i].info, "nettype", va("%d", type) );
             CL_SetServerInfoByAddress(from, infoString, cl_pinglist[i].time);
             return;
         }
     }
     // if not just sent a local broadcast or pinging local servers
     if (cls.pingUpdateSource != AS_LOCAL) {
         return;
     }
     for ( i = 0 ; i < MAX_OTHER_SERVERS ; i++ ) {
         // empty slot
         if ( cls.localServers[i].adr.port == 0 ) {
             break;
         }
         // avoid duplicate
         if ( NET_CompareAdr( from, cls.localServers[i].adr ) ) {
             return;
         }
     }
     if ( i == MAX_OTHER_SERVERS ) {
         Com_DPrintf( "MAX_OTHER_SERVERS hit, dropping infoResponse\n" );
         return;
     }
     // add this to the list
     cls.numlocalservers = i+1;
     CL_InitServerInfo( &cls.localServers[i], &from );
     Q_strncpyz( info, MSG_ReadString( msg ), MAX_INFO_STRING );
     if (strlen(info)) {
         if (info[strlen(info)-1] != '\n') {
             Q_strcat(info, sizeof(info), "\n");
         }
         Com_Printf( "%s: %s", NET_AdrToStringwPort( from ), info );
     }
 }
Referenced by CL_ConnectionlessPacket().
CL_ServerStatus()
int CL_ServerStatus (char * serverAddress, char * serverStatusString, int maxLen)
Definition at line 3972 of file cl_main.c.
{
     int i;
     netadr_t    to;
     serverStatus_t *serverStatus;
     // if no server address then reset all server status requests
     if ( !serverAddress ) {
         for (i = 0; i < MAX_SERVERSTATUSREQUESTS; i++) {
             cl_serverStatusList[i].address.port = 0;
             cl_serverStatusList[i].retrieved = qtrue;
         }
         return qfalse;
     }
     // get the address
     if ( !NET_StringToAdr( serverAddress, &to, NA_UNSPEC) ) {
         return qfalse;
     }
     serverStatus = CL_GetServerStatus( to );
     // if no server status string then reset the server status request for this address
     if ( !serverStatusString ) {
         serverStatus->retrieved = qtrue;
         return qfalse;
     }
     // if this server status request has the same address
     if ( NET_CompareAdr( to, serverStatus->address) ) {
         // if we received a response for this server status request
         if (!serverStatus->pending) {
             Q_strncpyz(serverStatusString, serverStatus->string, maxLen);
             serverStatus->retrieved = qtrue;
             serverStatus->startTime = 0;
             return qtrue;
         }
         // resend the request regularly
         else if ( serverStatus->startTime < Com_Milliseconds() - cl_serverStatusResendTime->integer ) {
             serverStatus->print = qfalse;
             serverStatus->pending = qtrue;
             serverStatus->retrieved = qfalse;
             serverStatus->time = 0;
             serverStatus->startTime = Com_Milliseconds();
             NET_OutOfBandPrint( NS_CLIENT, to, "getstatus" );
             return qfalse;
         }
     }
     // if retrieved
     else if ( serverStatus->retrieved ) {
         serverStatus->address = to;
         serverStatus->print = qfalse;
         serverStatus->pending = qtrue;
         serverStatus->retrieved = qfalse;
         serverStatus->startTime = Com_Milliseconds();
         serverStatus->time = 0;
         NET_OutOfBandPrint( NS_CLIENT, to, "getstatus" );
         return qfalse;
     }
     return qfalse;
 }
Referenced by LAN_GetServerStatus().
CL_SetCGameTime()
void CL_SetCGameTime (void)
Definition at line 942 of file cl_cgame.c.
{
     // getting a valid frame message ends the connection process
     if ( clc.state != CA_ACTIVE ) {
         if ( clc.state != CA_PRIMED ) {
             return;
         }
         if ( clc.demoplaying ) {
             // we shouldn't get the first snapshot on the same frame
             // as the gamestate, because it causes a bad time skip
             if ( !clc.firstDemoFrameSkipped ) {
                 clc.firstDemoFrameSkipped = qtrue;
                 return;
             }
             CL_ReadDemoMessage();
         }
         if ( cl.newSnapshots ) {
             cl.newSnapshots = qfalse;
             CL_FirstSnapshot();
         }
         if ( clc.state != CA_ACTIVE ) {
             return;
         }
     }
     // if we have gotten to this point, cl.snap is guaranteed to be valid
     if ( !cl.snap.valid ) {
         Com_Error( ERR_DROP, "CL_SetCGameTime: !cl.snap.valid" );
     }
     // allow pause in single player
     if ( sv_paused->integer && CL_CheckPaused() && com_sv_running->integer ) {
         // paused
         return;
     }
     if ( cl.snap.serverTime < cl.oldFrameServerTime ) {
         Com_Error( ERR_DROP, "cl.snap.serverTime < cl.oldFrameServerTime" );
     }
     cl.oldFrameServerTime = cl.snap.serverTime;
     // get our current view of time
     if ( clc.demoplaying && cl_freezeDemo->integer ) {
         // cl_freezeDemo is used to lock a demo in place for single frame advances
     } else {
         // cl_timeNudge is a user adjustable cvar that allows more
         // or less latency to be added in the interest of better
         // smoothness or better responsiveness.
         int tn;
         tn = cl_timeNudge->integer;
         if (tn<-30) {
             tn = -30;
         } else if (tn>30) {
             tn = 30;
         }
         cl.serverTime = cls.realtime + cl.serverTimeDelta - tn;
         // guarantee that time will never flow backwards, even if
         // serverTimeDelta made an adjustment or cl_timeNudge was changed
         if ( cl.serverTime < cl.oldServerTime ) {
             cl.serverTime = cl.oldServerTime;
         }
         cl.oldServerTime = cl.serverTime;
         // note if we are almost past the latest frame (without timeNudge),
         // so we will try and adjust back a bit when the next snapshot arrives
         if ( cls.realtime + cl.serverTimeDelta >= cl.snap.serverTime - 5 ) {
             cl.extrapolatedSnapshot = qtrue;
         }
     }
     // if we have gotten new snapshots, drift serverTimeDelta
     // don't do this every frame, or a period of packet loss would
     // make a huge adjustment
     if ( cl.newSnapshots ) {
         CL_AdjustTimeDelta();
     }
     if ( !clc.demoplaying ) {
         return;
     }
     // if we are playing a demo back, we can just keep reading
     // messages from the demo file until the cgame definitely
     // has valid snapshots to interpolate between
     // a timedemo will always use a deterministic set of time samples
     // no matter what speed machine it is run on,
     // while a normal demo may have different time samples
     // each time it is played back
     if ( cl_timedemo->integer ) {
         int now = Sys_Milliseconds( );
         int frameDuration;
         if (!clc.timeDemoStart) {
             clc.timeDemoStart = clc.timeDemoLastFrame = now;
             clc.timeDemoMinDuration = INT_MAX;
             clc.timeDemoMaxDuration = 0;
         }
         frameDuration = now - clc.timeDemoLastFrame;
         clc.timeDemoLastFrame = now;
         // Ignore the first measurement as it'll always be 0
         if( clc.timeDemoFrames > 0 )
         {
             if( frameDuration > clc.timeDemoMaxDuration )
                 clc.timeDemoMaxDuration = frameDuration;
             if( frameDuration < clc.timeDemoMinDuration )
                 clc.timeDemoMinDuration = frameDuration;
             // 255 ms = about 4fps
             if( frameDuration > UCHAR_MAX )
                 frameDuration = UCHAR_MAX;
             clc.timeDemoDurations[ ( clc.timeDemoFrames - 1 ) %
                 MAX_TIMEDEMO_DURATIONS ] = frameDuration;
         }
         clc.timeDemoFrames++;
         cl.serverTime = clc.timeDemoBaseTime + clc.timeDemoFrames * 50;
     }
     while ( cl.serverTime >= cl.snap.serverTime ) {
         // feed another messag, which should change
         // the contents of cl.snap
         CL_ReadDemoMessage();
         if ( clc.state != CA_ACTIVE ) {
             return;     // end of demo
         }
     }
 }
Referenced by CL_Frame().
CL_ShaderStateChanged()
void CL_ShaderStateChanged (void)
CL_ShutdownCGame()
void CL_ShutdownCGame (void)
Definition at line 386 of file cl_cgame.c.
{
     Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_CGAME );
     cls.cgameStarted = qfalse;
     if ( !cgvm ) {
         return;
     }
     VM_Call( cgvm, CG_SHUTDOWN );
     VM_Free( cgvm );
     cgvm = NULL;
 }
CL_ShutdownInput()
void CL_ShutdownInput (void)
Definition at line 1010 of file cl_input.c.
 {
     Cmd_RemoveCommand("centerview");
     Cmd_RemoveCommand("+moveup");
     Cmd_RemoveCommand("-moveup");
     Cmd_RemoveCommand("+movedown");
     Cmd_RemoveCommand("-movedown");
     Cmd_RemoveCommand("+left");
     Cmd_RemoveCommand("-left");
     Cmd_RemoveCommand("+right");
     Cmd_RemoveCommand("-right");
     Cmd_RemoveCommand("+forward");
     Cmd_RemoveCommand("-forward");
     Cmd_RemoveCommand("+back");
     Cmd_RemoveCommand("-back");
     Cmd_RemoveCommand("+lookup");
     Cmd_RemoveCommand("-lookup");
     Cmd_RemoveCommand("+lookdown");
     Cmd_RemoveCommand("-lookdown");
     Cmd_RemoveCommand("+strafe");
     Cmd_RemoveCommand("-strafe");
     Cmd_RemoveCommand("+moveleft");
     Cmd_RemoveCommand("-moveleft");
     Cmd_RemoveCommand("+moveright");
     Cmd_RemoveCommand("-moveright");
     Cmd_RemoveCommand("+speed");
     Cmd_RemoveCommand("-speed");
     Cmd_RemoveCommand("+attack");
     Cmd_RemoveCommand("-attack");
     Cmd_RemoveCommand("+button0");
     Cmd_RemoveCommand("-button0");
     Cmd_RemoveCommand("+button1");
     Cmd_RemoveCommand("-button1");
     Cmd_RemoveCommand("+button2");
     Cmd_RemoveCommand("-button2");
     Cmd_RemoveCommand("+button3");
     Cmd_RemoveCommand("-button3");
     Cmd_RemoveCommand("+button4");
     Cmd_RemoveCommand("-button4");
     Cmd_RemoveCommand("+button5");
     Cmd_RemoveCommand("-button5");
     Cmd_RemoveCommand("+button6");
     Cmd_RemoveCommand("-button6");
     Cmd_RemoveCommand("+button7");
     Cmd_RemoveCommand("-button7");
     Cmd_RemoveCommand("+button8");
     Cmd_RemoveCommand("-button8");
     Cmd_RemoveCommand("+button9");
     Cmd_RemoveCommand("-button9");
     Cmd_RemoveCommand("+button10");
     Cmd_RemoveCommand("-button10");
     Cmd_RemoveCommand("+button11");
     Cmd_RemoveCommand("-button11");
     Cmd_RemoveCommand("+button12");
     Cmd_RemoveCommand("-button12");
     Cmd_RemoveCommand("+button13");
     Cmd_RemoveCommand("-button13");
     Cmd_RemoveCommand("+button14");
     Cmd_RemoveCommand("-button14");
     Cmd_RemoveCommand("+mlook");
     Cmd_RemoveCommand("-mlook");
 #ifdef USE_VOIP
     Cmd_RemoveCommand("+voiprecord");
     Cmd_RemoveCommand("-voiprecord");
 #endif
 }
Referenced by CL_Shutdown().
CL_ShutdownRef()
void CL_ShutdownRef (void)
Definition at line 3105 of file cl_main.c.
{
     if ( re.Shutdown ) {
         re.Shutdown( qtrue );
     }
     Com_Memset( &re, 0, sizeof( re ) );
 #ifdef USE_RENDERER_DLOPEN
     if ( rendererLib ) {
         Sys_UnloadLibrary( rendererLib );
         rendererLib = NULL;
     }
 #endif
 }
Referenced by CL_ShutdownAll(), and CL_Vid_Restart_f().
CL_ShutdownUI()
void CL_ShutdownUI (void)
Definition at line 1088 of file cl_ui.c.
{
     Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_UI );
     cls.uiStarted = qfalse;
     if ( !uivm ) {
         return;
     }
     VM_Call( uivm, UI_SHUTDOWN );
     VM_Free( uivm );
     uivm = NULL;
 }
CL_Snd_Restart_f()
void CL_Snd_Restart_f (void)
Definition at line 2016 of file cl_main.c.
 {
     CL_Snd_Shutdown();
     // sound will be reinitialized by vid_restart
     CL_Vid_Restart_f();
 }
Referenced by CL_Init().
CL_StartDemoLoop()
void CL_StartDemoLoop (void)
Definition at line 1167 of file cl_main.c.
{
     // start the demo loop again
     Cbuf_AddText ("d1\n");
     Key_SetCatcher( 0 );
 }
CL_StartHunkUsers()
void CL_StartHunkUsers (qboolean rendererOnly)
Definition at line 3145 of file cl_main.c.
{
     if (!com_cl_running) {
         return;
     }
     if ( !com_cl_running->integer ) {
         return;
     }
     if ( !cls.rendererStarted ) {
         cls.rendererStarted = qtrue;
         CL_InitRenderer();
     }
     if ( rendererOnly ) {
         return;
     }
     if ( !cls.soundStarted ) {
         cls.soundStarted = qtrue;
         S_Init();
     }
     if ( !cls.soundRegistered ) {
         cls.soundRegistered = qtrue;
         S_BeginRegistration();
     }
     if( com_dedicated->integer ) {
         return;
     }
     if ( !cls.uiStarted ) {
         cls.uiStarted = qtrue;
         CL_InitUI();
     }
 }
CL_StopRecord_f()
void CL_StopRecord_f (void)
Definition at line 639 of file cl_main.c.
{
     int     len;
     if ( !clc.demorecording ) {
         Com_Printf ("Not recording a demo.\n");
         return;
     }
     // finish up
     len = -1;
     FS_Write (&len, 4, clc.demofile);
     FS_Write (&len, 4, clc.demofile);
     FS_FCloseFile (clc.demofile);
     clc.demofile = 0;
     clc.demorecording = qfalse;
     clc.spDemoRecording = qfalse;
     Com_Printf ("Stopped demo.\n");
 }
Referenced by CL_Disconnect(), CL_Frame(), CL_Init(), CL_ParseGamestate(), CL_ShutdownAll(), and CL_Vid_Restart_f().
CL_SystemInfoChanged()
void CL_SystemInfoChanged (void)
Definition at line 342 of file cl_parse.c.
{
     char            *systemInfo;
     const char      *s, *t;
     char            key[BIG_INFO_KEY];
     char            value[BIG_INFO_VALUE];
     qboolean        gameSet;
     systemInfo = cl.gameState.stringData + cl.gameState.stringOffsets[ CS_SYSTEMINFO ];
     // NOTE TTimo:
     // when the serverId changes, any further messages we send to the server will use this new serverId
     // https://zerowing.idsoftware.com/bugzilla/show_bug.cgi?id=475
     // in some cases, outdated cp commands might get sent with this news serverId
     cl.serverId = atoi( Info_ValueForKey( systemInfo, "sv_serverid" ) );
 #ifdef USE_VOIP
 #ifdef LEGACY_PROTOCOL
     if(clc.compat)
         clc.voipEnabled = qfalse;
     else
 #endif
     {
         s = Info_ValueForKey( systemInfo, "sv_voipProtocol" );
         clc.voipEnabled = !Q_stricmp(s, "opus");
     }
 #endif
     // don't set any vars when playing a demo
     if ( clc.demoplaying ) {
         return;
     }
     s = Info_ValueForKey( systemInfo, "sv_cheats" );
     cl_connectedToCheatServer = atoi( s );
     if ( !cl_connectedToCheatServer ) {
         Cvar_SetCheatState();
     }
     // check pure server string
     s = Info_ValueForKey( systemInfo, "sv_paks" );
     t = Info_ValueForKey( systemInfo, "sv_pakNames" );
     FS_PureServerSetLoadedPaks( s, t );
     s = Info_ValueForKey( systemInfo, "sv_referencedPaks" );
     t = Info_ValueForKey( systemInfo, "sv_referencedPakNames" );
     FS_PureServerSetReferencedPaks( s, t );
     gameSet = qfalse;
     // scan through all the variables in the systeminfo and locally set cvars to match
     s = systemInfo;
     while ( s ) {
         int cvar_flags;
         Info_NextPair( &s, key, value );
         if ( !key[0] ) {
             break;
         }
         // ehw!
         if (!Q_stricmp(key, "fs_game"))
         {
             if(FS_InvalidGameDir(value))
             {
                 Com_Printf(S_COLOR_YELLOW "WARNING: Server sent invalid fs_game value %s\n", value);
                 continue;
             }
             gameSet = qtrue;
         }
         if((cvar_flags = Cvar_Flags(key)) == CVAR_NONEXISTENT)
             Cvar_Get(key, value, CVAR_SERVER_CREATED | CVAR_ROM);
         else
         {
             // If this cvar may not be modified by a server discard the value.
             if(!(cvar_flags & (CVAR_SYSTEMINFO | CVAR_SERVER_CREATED | CVAR_USER_CREATED)))
             {
 #ifndef STANDALONE
                 if(Q_stricmp(key, "g_synchronousClients") && Q_stricmp(key, "pmove_fixed") &&
                    Q_stricmp(key, "pmove_msec"))
 #endif
                 {
                     Com_Printf(S_COLOR_YELLOW "WARNING: server is not allowed to set %s=%s\n", key, value);
                     continue;
                 }
             }
             Cvar_SetSafe(key, value);
         }
     }
     // if game folder should not be set and it is set at the client side
     if ( !gameSet && *Cvar_VariableString("fs_game") ) {
         Cvar_Set( "fs_game", "" );
     }
     cl_connectedToPureServer = Cvar_VariableValue( "sv_pure" );
 }
Referenced by CL_ConfigstringModified(), and CL_ParseGamestate().
CL_TakeVideoFrame()
void CL_TakeVideoFrame (void)
Definition at line 576 of file cl_avi.c.
 {
   // AVI file isn't open
   if( !afd.fileOpen )
     return;
   re.TakeVideoFrame( afd.width, afd.height,
       afd.cBuffer, afd.eBuffer, afd.motionJpeg );
 }
Referenced by CL_Frame().
CL_UpdateVisiblePings_f()
qboolean CL_UpdateVisiblePings_f (int source)
Definition at line 4479 of file cl_main.c.
{
     int         slots, i;
     char        buff[MAX_STRING_CHARS];
     int         pingTime;
     int         max;
     qboolean status = qfalse;
     if (source < 0 || source > AS_FAVORITES) {
         return qfalse;
     }
     cls.pingUpdateSource = source;
     slots = CL_GetPingQueueCount();
     if (slots < MAX_PINGREQUESTS) {
         serverInfo_t *server = NULL;
         switch (source) {
             case AS_LOCAL :
                 server = &cls.localServers[0];
                 max = cls.numlocalservers;
             break;
             case AS_GLOBAL :
                 server = &cls.globalServers[0];
                 max = cls.numglobalservers;
             break;
             case AS_FAVORITES :
                 server = &cls.favoriteServers[0];
                 max = cls.numfavoriteservers;
             break;
             default:
                 return qfalse;
         }
         for (i = 0; i < max; i++) {
             if (server[i].visible) {
                 if (server[i].ping == -1) {
                     int j;
                     if (slots >= MAX_PINGREQUESTS) {
                         break;
                     }
                     for (j = 0; j < MAX_PINGREQUESTS; j++) {
                         if (!cl_pinglist[j].adr.port) {
                             continue;
                         }
                         if (NET_CompareAdr( cl_pinglist[j].adr, server[i].adr)) {
                             // already on the list
                             break;
                         }
                     }
                     if (j >= MAX_PINGREQUESTS) {
                         status = qtrue;
                         for (j = 0; j < MAX_PINGREQUESTS; j++) {
                             if (!cl_pinglist[j].adr.port) {
                                 break;
                             }
                         }
                         memcpy(&cl_pinglist[j].adr, &server[i].adr, sizeof(netadr_t));
                         cl_pinglist[j].start = Sys_Milliseconds();
                         cl_pinglist[j].time = 0;
                         NET_OutOfBandPrint( NS_CLIENT, cl_pinglist[j].adr, "getinfo xxx" );
                         slots++;
                     }
                 }
                 // if the server has a ping higher than cl_maxPing or
                 // the ping packet got lost
                 else if (server[i].ping == 0) {
                     // if we are updating global servers
                     if (source == AS_GLOBAL) {
                         //
                         if ( cls.numGlobalServerAddresses > 0 ) {
                             // overwrite this server with one from the additional global servers
                             cls.numGlobalServerAddresses--;
                             CL_InitServerInfo(&server[i], &cls.globalServerAddresses[cls.numGlobalServerAddresses]);
                             // NOTE: the server[i].visible flag stays untouched
                         }
                     }
                 }
             }
         }
     }
     if (slots) {
         status = qtrue;
     }
     for (i = 0; i < MAX_PINGREQUESTS; i++) {
         if (!cl_pinglist[i].adr.port) {
             continue;
         }
         CL_GetPing( i, buff, MAX_STRING_CHARS, &pingTime );
         if (pingTime != 0) {
             CL_ClearPing(i);
             status = qtrue;
         }
     }
     return status;
 }
Referenced by LAN_UpdateVisiblePings().
CL_VerifyCode()
void CL_VerifyCode (void)
CL_Vid_Restart_f()
void CL_Vid_Restart_f (void)
Definition at line 1930 of file cl_main.c.
{
     // Settings may have changed so stop recording now
     if( CL_VideoRecording( ) ) {
         CL_CloseAVI( );
     }
     if(clc.demorecording)
         CL_StopRecord_f();
     // don't let them loop during the restart
     S_StopAllSounds();
     if(!FS_ConditionalRestart(clc.checksumFeed, qtrue))
     {
         // if not running a server clear the whole hunk
         if(com_sv_running->integer)
         {
             // clear all the client data on the hunk
             Hunk_ClearToMark();
         }
         else
         {
             // clear the whole hunk
             Hunk_Clear();
         }
         // shutdown the UI
         CL_ShutdownUI();
         // shutdown the CGame
         CL_ShutdownCGame();
         // shutdown the renderer and clear the renderer interface
         CL_ShutdownRef();
         // client is no longer pure until new checksums are sent
         CL_ResetPureClientAtServer();
         // clear pak references
         FS_ClearPakReferences( FS_UI_REF | FS_CGAME_REF );
         // reinitialize the filesystem if the game directory or checksum has changed
         cls.rendererStarted = qfalse;
         cls.uiStarted = qfalse;
         cls.cgameStarted = qfalse;
         cls.soundRegistered = qfalse;
         // unpause so the cgame definitely gets a snapshot and renders a frame
         Cvar_Set("cl_paused", "0");
         // initialize the renderer interface
         CL_InitRef();
         // startup all the client stuff
         CL_StartHunkUsers(qfalse);
         // start the cgame if connected
         if(clc.state > CA_CONNECTED && clc.state != CA_CINEMATIC)
         {
             cls.cgameStarted = qtrue;
             CL_InitCGame();
             // send pure checksums
             CL_SendPureChecksums();
         }
     }
 }
Referenced by CL_Init(), and CL_Snd_Restart_f().
CL_VideoRecording()
qboolean CL_VideoRecording (void)
Definition at line 665 of file cl_avi.c.
 {
   return afd.fileOpen;
 }
Referenced by CL_Disconnect(), CL_Frame(), CL_ShutdownAll(), CL_Vid_Restart_f(), S_GetSoundtime(), and S_TransferStereo16().
CL_WriteAVIAudioFrame()
void CL_WriteAVIAudioFrame (const byte * pcmBuffer, int size)
Definition at line 510 of file cl_avi.c.
 {
   static byte pcmCaptureBuffer[ PCM_BUFFER_SIZE ] = { 0 };
   static int  bytesInBuffer = 0;
   if( !afd.audio )
     return;
   if( !afd.fileOpen )
     return;
   // Chunk header + contents + padding
   if( CL_CheckFileSize( 8 + bytesInBuffer + size + 2 ) )
     return;
   if( bytesInBuffer + size > PCM_BUFFER_SIZE )
   {
     Com_Printf( S_COLOR_YELLOW
         "WARNING: Audio capture buffer overflow -- truncating\n" );
     size = PCM_BUFFER_SIZE - bytesInBuffer;
   }
   Com_Memcpy( &pcmCaptureBuffer[ bytesInBuffer ], pcmBuffer, size );
   bytesInBuffer += size;
   // Only write if we have a frame's worth of audio
   if( bytesInBuffer >= (int)ceil( (float)afd.a.rate / (float)afd.frameRate ) *
         afd.a.sampleSize )
   {
     int   chunkOffset = afd.fileSize - afd.moviOffset - 8;
     int   chunkSize = 8 + bytesInBuffer;
     int   paddingSize = PADLEN(bytesInBuffer, 2);
     byte  padding[ 4 ] = { 0 };
     bufIndex = 0;
     WRITE_STRING( "01wb" );
     WRITE_4BYTES( bytesInBuffer );
     SafeFS_Write( buffer, 8, afd.f );
     SafeFS_Write( pcmCaptureBuffer, bytesInBuffer, afd.f );
     SafeFS_Write( padding, paddingSize, afd.f );
     afd.fileSize += ( chunkSize + paddingSize );
     afd.numAudioFrames++;
     afd.moviSize += ( chunkSize + paddingSize );
     afd.a.totalBytes += bytesInBuffer;
     // Index
     bufIndex = 0;
     WRITE_STRING( "01wb" );           //dwIdentifier
     WRITE_4BYTES( 0 );                //dwFlags
     WRITE_4BYTES( chunkOffset );      //dwOffset
     WRITE_4BYTES( bytesInBuffer );    //dwLength
     SafeFS_Write( buffer, 16, afd.idxF );
     afd.numIndices++;
     bytesInBuffer = 0;
   }
 }
Referenced by S_TransferStereo16().
CL_WriteAVIVideoFrame()
void CL_WriteAVIVideoFrame (const byte * imageBuffer, int size)
Definition at line 463 of file cl_avi.c.
 {
   int   chunkOffset = afd.fileSize - afd.moviOffset - 8;
   int   chunkSize = 8 + size;
   int   paddingSize = PADLEN(size, 2);
   byte  padding[ 4 ] = { 0 };
   if( !afd.fileOpen )
     return;
   // Chunk header + contents + padding
   if( CL_CheckFileSize( 8 + size + 2 ) )
     return;
   bufIndex = 0;
   WRITE_STRING( "00dc" );
   WRITE_4BYTES( size );
   SafeFS_Write( buffer, 8, afd.f );
   SafeFS_Write( imageBuffer, size, afd.f );
   SafeFS_Write( padding, paddingSize, afd.f );
   afd.fileSize += ( chunkSize + paddingSize );
   afd.numVideoFrames++;
   afd.moviSize += ( chunkSize + paddingSize );
   if( size > afd.maxRecordSize )
     afd.maxRecordSize = size;
   // Index
   bufIndex = 0;
   WRITE_STRING( "00dc" );           //dwIdentifier
   WRITE_4BYTES( 0x00000010 );       //dwFlags (all frames are KeyFrames)
   WRITE_4BYTES( chunkOffset );      //dwOffset
   WRITE_4BYTES( size );             //dwLength
   SafeFS_Write( buffer, 16, afd.idxF );
   afd.numIndices++;
 }
Referenced by CL_InitRef().
CL_WriteDemoMessage()
void CL_WriteDemoMessage (msg_t * msg, int headerBytes)
Definition at line 617 of file cl_main.c.
{
     int     len, swlen;
     // write the packet sequence
     len = clc.serverMessageSequence;
     swlen = LittleLong( len );
     FS_Write (&swlen, 4, clc.demofile);
     // skip the packet sequencing information
     len = msg->cursize - headerBytes;
     swlen = LittleLong(len);
     FS_Write (&swlen, 4, clc.demofile);
     FS_Write ( msg->data + headerBytes, len, clc.demofile );
 }
Referenced by CL_PacketEvent(), and CL_WritePacket().
CL_WritePacket()
void CL_WritePacket (void)
Definition at line 743 of file cl_input.c.
{
     msg_t       buf;
     byte        data[MAX_MSGLEN];
     int         i, j;
     usercmd_t   *cmd, *oldcmd;
     usercmd_t   nullcmd;
     int         packetNum;
     int         oldPacketNum;
     int         count, key;
     // don't send anything if playing back a demo
     if ( clc.demoplaying || clc.state == CA_CINEMATIC ) {
         return;
     }
     Com_Memset( &nullcmd, 0, sizeof(nullcmd) );
     oldcmd = &nullcmd;
     MSG_Init( &buf, data, sizeof(data) );
     MSG_Bitstream( &buf );
     // write the current serverId so the server
     // can tell if this is from the current gameState
     MSG_WriteLong( &buf, cl.serverId );
     // write the last message we received, which can
     // be used for delta compression, and is also used
     // to tell if we dropped a gamestate
     MSG_WriteLong( &buf, clc.serverMessageSequence );
     // write the last reliable message we received
     MSG_WriteLong( &buf, clc.serverCommandSequence );
     // write any unacknowledged clientCommands
     for ( i = clc.reliableAcknowledge + 1 ; i <= clc.reliableSequence ; i++ ) {
         MSG_WriteByte( &buf, clc_clientCommand );
         MSG_WriteLong( &buf, i );
         MSG_WriteString( &buf, clc.reliableCommands[ i & (MAX_RELIABLE_COMMANDS-1) ] );
     }
     // we want to send all the usercmds that were generated in the last
     // few packet, so even if a couple packets are dropped in a row,
     // all the cmds will make it to the server
     if ( cl_packetdup->integer < 0 ) {
         Cvar_Set( "cl_packetdup", "0" );
     } else if ( cl_packetdup->integer > 5 ) {
         Cvar_Set( "cl_packetdup", "5" );
     }
     oldPacketNum = (clc.netchan.outgoingSequence - 1 - cl_packetdup->integer) & PACKET_MASK;
     count = cl.cmdNumber - cl.outPackets[ oldPacketNum ].p_cmdNumber;
     if ( count > MAX_PACKET_USERCMDS ) {
         count = MAX_PACKET_USERCMDS;
         Com_Printf("MAX_PACKET_USERCMDS\n");
     }
 #ifdef USE_VOIP
     if (clc.voipOutgoingDataSize > 0)
     {
         if((clc.voipFlags & VOIP_SPATIAL) || Com_IsVoipTarget(clc.voipTargets, sizeof(clc.voipTargets), -1))
         {
             MSG_WriteByte (&buf, clc_voipOpus);
             MSG_WriteByte (&buf, clc.voipOutgoingGeneration);
             MSG_WriteLong (&buf, clc.voipOutgoingSequence);
             MSG_WriteByte (&buf, clc.voipOutgoingDataFrames);
             MSG_WriteData (&buf, clc.voipTargets, sizeof(clc.voipTargets));
             MSG_WriteByte(&buf, clc.voipFlags);
             MSG_WriteShort (&buf, clc.voipOutgoingDataSize);
             MSG_WriteData (&buf, clc.voipOutgoingData, clc.voipOutgoingDataSize);
             // If we're recording a demo, we have to fake a server packet with
             //  this VoIP data so it gets to disk; the server doesn't send it
             //  back to us, and we might as well eliminate concerns about dropped
             //  and misordered packets here.
             if(clc.demorecording && !clc.demowaiting)
             {
                 const int voipSize = clc.voipOutgoingDataSize;
                 msg_t fakemsg;
                 byte fakedata[MAX_MSGLEN];
                 MSG_Init (&fakemsg, fakedata, sizeof (fakedata));
                 MSG_Bitstream (&fakemsg);
                 MSG_WriteLong (&fakemsg, clc.reliableAcknowledge);
                 MSG_WriteByte (&fakemsg, svc_voipOpus);
                 MSG_WriteShort (&fakemsg, clc.clientNum);
                 MSG_WriteByte (&fakemsg, clc.voipOutgoingGeneration);
                 MSG_WriteLong (&fakemsg, clc.voipOutgoingSequence);
                 MSG_WriteByte (&fakemsg, clc.voipOutgoingDataFrames);
                 MSG_WriteShort (&fakemsg, clc.voipOutgoingDataSize );
                 MSG_WriteBits (&fakemsg, clc.voipFlags, VOIP_FLAGCNT);
                 MSG_WriteData (&fakemsg, clc.voipOutgoingData, voipSize);
                 MSG_WriteByte (&fakemsg, svc_EOF);
                 CL_WriteDemoMessage (&fakemsg, 0);
             }
             clc.voipOutgoingSequence += clc.voipOutgoingDataFrames;
             clc.voipOutgoingDataSize = 0;
             clc.voipOutgoingDataFrames = 0;
         }
         else
         {
             // We have data, but no targets. Silently discard all data
             clc.voipOutgoingDataSize = 0;
             clc.voipOutgoingDataFrames = 0;
         }
     }
 #endif
     if ( count >= 1 ) {
         if ( cl_showSend->integer ) {
             Com_Printf( "(%i)", count );
         }
         // begin a client move command
         if ( cl_nodelta->integer || !cl.snap.valid || clc.demowaiting
             || clc.serverMessageSequence != cl.snap.messageNum ) {
             MSG_WriteByte (&buf, clc_moveNoDelta);
         } else {
             MSG_WriteByte (&buf, clc_move);
         }
         // write the command count
         MSG_WriteByte( &buf, count );
         // use the checksum feed in the key
         key = clc.checksumFeed;
         // also use the message acknowledge
         key ^= clc.serverMessageSequence;
         // also use the last acknowledged server command in the key
         key ^= MSG_HashKey(clc.serverCommands[ clc.serverCommandSequence & (MAX_RELIABLE_COMMANDS-1) ], 32);
         // write all the commands, including the predicted command
         for ( i = 0 ; i < count ; i++ ) {
             j = (cl.cmdNumber - count + i + 1) & CMD_MASK;
             cmd = &cl.cmds[j];
             MSG_WriteDeltaUsercmdKey (&buf, key, oldcmd, cmd);
             oldcmd = cmd;
         }
     }
     //
     // deliver the message
     //
     packetNum = clc.netchan.outgoingSequence & PACKET_MASK;
     cl.outPackets[ packetNum ].p_realtime = cls.realtime;
     cl.outPackets[ packetNum ].p_serverTime = oldcmd->serverTime;
     cl.outPackets[ packetNum ].p_cmdNumber = cl.cmdNumber;
     clc.lastPacketSentTime = cls.realtime;
     if ( cl_showSend->integer ) {
         Com_Printf( "%i ", buf.cursize );
     }
     CL_Netchan_Transmit (&clc.netchan, &buf);
 }
Referenced by CL_Disconnect(), CL_DownloadsComplete(), CL_ParseDownload(), and CL_SendCmd().
Con_Bottom()
void Con_Bottom (void)
Definition at line 829 of file cl_console.c.
{
     con.display = con.current;
 }
Referenced by Con_Clear_f(), and Console_Key().
Con_CheckResize()
void Con_CheckResize (void)
Definition at line 281 of file cl_console.c.
 {
     int     i, j, width, oldwidth, oldtotallines, numlines, numchars;
     short   tbuf[CON_TEXTSIZE];
     width = (SCREEN_WIDTH / SMALLCHAR_WIDTH) - 2;
     if (width == con.linewidth)
         return;
     if (width < 1)          // video hasn't been initialized yet
     {
         width = DEFAULT_CONSOLE_WIDTH;
         con.linewidth = width;
         con.totallines = CON_TEXTSIZE / con.linewidth;
         for(i=0; i<CON_TEXTSIZE; i++)
             con.text[i] = (ColorIndex(COLOR_WHITE)<<8) | ' ';
     }
     else
     {
         oldwidth = con.linewidth;
         con.linewidth = width;
         oldtotallines = con.totallines;
         con.totallines = CON_TEXTSIZE / con.linewidth;
         numlines = oldtotallines;
         if (con.totallines < numlines)
             numlines = con.totallines;
         numchars = oldwidth;
         if (con.linewidth < numchars)
             numchars = con.linewidth;
         Com_Memcpy (tbuf, con.text, CON_TEXTSIZE * sizeof(short));
         for(i=0; i<CON_TEXTSIZE; i++)
             con.text[i] = (ColorIndex(COLOR_WHITE)<<8) | ' ';
         for (i=0 ; i<numlines ; i++)
         {
             for (j=0 ; j<numchars ; j++)
             {
                 con.text[(con.totallines - 1 - i) * con.linewidth + j] =
                         tbuf[((con.current - i + oldtotallines) %
                               oldtotallines) * oldwidth + j];
             }
         }
         Con_ClearNotify ();
     }
     con.current = con.totallines - 1;
     con.display = con.current;
 }
Referenced by CL_ConsolePrint(), and Con_DrawConsole().
Con_Clear_f()
void Con_Clear_f (void)
Definition at line 162 of file cl_console.c.
{
     int     i;
     for ( i = 0 ; i < CON_TEXTSIZE ; i++ ) {
         con.text[i] = (ColorIndex(COLOR_WHITE)<<8) | ' ';
     }
     Con_Bottom();       // go to end
 }
Referenced by Con_Init().
Con_ClearNotify()
void Con_ClearNotify (void)
Definition at line 264 of file cl_console.c.
{
     int     i;
     for ( i = 0 ; i < NUM_CON_TIMES ; i++ ) {
         con.times[i] = 0;
     }
 }
Referenced by CL_GetServerCommand(), CL_InitCGame(), Con_CheckResize(), Con_Close(), and Con_ToggleConsole_f().
Con_Close()
void Con_Close (void)
Definition at line 834 of file cl_console.c.
{
     if ( !com_cl_running->integer ) {
         return;
     }
     Field_Clear( &g_consoleField );
     Con_ClearNotify ();
     Key_SetCatcher( Key_GetCatcher( ) & ~KEYCATCH_CONSOLE );
     con.finalFrac = 0;              // none visible
     con.displayFrac = 0;
 }
Referenced by CIN_PlayCinematic(), CL_Connect_f(), CL_GetServerCommand(), CL_InitCGame(), CL_MapLoading(), CL_ParseGamestate(), and CL_PlayDemo_f().
Con_DrawCharacter()
void Con_DrawCharacter (int cx, int line, int num)
Con_DrawConsole()
void Con_DrawConsole (void)
Definition at line 752 of file cl_console.c.
{
     // check for console width changes from a vid mode change
     Con_CheckResize ();
     // if disconnected, render console full screen
     if ( clc.state == CA_DISCONNECTED ) {
         if ( !( Key_GetCatcher( ) & (KEYCATCH_UI | KEYCATCH_CGAME)) ) {
             Con_DrawSolidConsole( 1.0 );
             return;
         }
     }
     if ( con.displayFrac ) {
         Con_DrawSolidConsole( con.displayFrac );
     } else {
         // draw notify lines
         if ( clc.state == CA_ACTIVE ) {
             Con_DrawNotify ();
         }
     }
 }
Referenced by SCR_DrawScreenField().
Con_DrawNotify()
void Con_DrawNotify (void)
Definition at line 564 of file cl_console.c.
 {
     int     x, v;
     short   *text;
     int     i;
     int     time;
     int     skip;
     int     currentColor;
     currentColor = 7;
     re.SetColor( g_color_table[currentColor] );
     v = 0;
     for (i= con.current-NUM_CON_TIMES+1 ; i<=con.current ; i++)
     {
         if (i < 0)
             continue;
         time = con.times[i % NUM_CON_TIMES];
         if (time == 0)
             continue;
         time = cls.realtime - time;
         if (time > con_notifytime->value*1000)
             continue;
         text = con.text + (i % con.totallines)*con.linewidth;
         if (cl.snap.ps.pm_type != PM_INTERMISSION && Key_GetCatcher( ) & (KEYCATCH_UI | KEYCATCH_CGAME) ) {
             continue;
         }
         for (x = 0 ; x < con.linewidth ; x++) {
             if ( ( text[x] & 0xff ) == ' ' ) {
                 continue;
             }
             if ( ColorIndexForNumber( text[x]>>8 ) != currentColor ) {
                 currentColor = ColorIndexForNumber( text[x]>>8 );
                 re.SetColor( g_color_table[currentColor] );
             }
             SCR_DrawSmallChar( cl_conXOffset->integer + con.xadjust + (x+1)*SMALLCHAR_WIDTH, v, text[x] & 0xff );
         }
         v += SMALLCHAR_HEIGHT;
     }
     re.SetColor( NULL );
     if (Key_GetCatcher( ) & (KEYCATCH_UI | KEYCATCH_CGAME) ) {
         return;
     }
     // draw the chat line
     if ( Key_GetCatcher( ) & KEYCATCH_MESSAGE )
     {
         if (chat_team)
         {
             SCR_DrawBigString (8, v, "say_team:", 1.0f, qfalse );
             skip = 10;
         }
         else
         {
             SCR_DrawBigString (8, v, "say:", 1.0f, qfalse );
             skip = 5;
         }
         Field_BigDraw( &chatField, skip * BIGCHAR_WIDTH, v,
             SCREEN_WIDTH - ( skip + 1 ) * BIGCHAR_WIDTH, qtrue, qtrue );
     }
 }
Referenced by Con_DrawConsole().
Con_Init()
void Con_Init (void)
Definition at line 356 of file cl_console.c.
                      {
     int     i;
     con_notifytime = Cvar_Get ("con_notifytime", "3", 0);
     con_conspeed = Cvar_Get ("scr_conspeed", "3", 0);
     con_autoclear = Cvar_Get("con_autoclear", "1", CVAR_ARCHIVE);
     Field_Clear( &g_consoleField );
     g_consoleField.widthInChars = g_console_field_width;
     for ( i = 0 ; i < COMMAND_HISTORY ; i++ ) {
         Field_Clear( &historyEditLines[i] );
         historyEditLines[i].widthInChars = g_console_field_width;
     }
     CL_LoadConsoleHistory( );
     Cmd_AddCommand ("toggleconsole", Con_ToggleConsole_f);
     Cmd_AddCommand ("togglemenu", Con_ToggleMenu_f);
     Cmd_AddCommand ("messagemode", Con_MessageMode_f);
     Cmd_AddCommand ("messagemode2", Con_MessageMode2_f);
     Cmd_AddCommand ("messagemode3", Con_MessageMode3_f);
     Cmd_AddCommand ("messagemode4", Con_MessageMode4_f);
     Cmd_AddCommand ("clear", Con_Clear_f);
     Cmd_AddCommand ("condump", Con_Dump_f);
     Cmd_SetCommandCompletionFunc( "condump", Cmd_CompleteTxtName );
 }
Referenced by CL_Init().
Con_PageDown()
void Con_PageDown (void)
Definition at line 815 of file cl_console.c.
{
     con.display += 2;
     if (con.display > con.current) {
         con.display = con.current;
     }
 }
Referenced by Console_Key().
Con_PageUp()
void Con_PageUp (void)
Definition at line 808 of file cl_console.c.
{
     con.display -= 2;
     if ( con.current - con.display >= con.totallines ) {
         con.display = con.current - con.totallines + 1;
     }
 }
Referenced by Console_Key().
Con_RunConsole()
void Con_RunConsole (void)
Definition at line 783 of file cl_console.c.
{
     // decide on the destination height of the console
     if ( Key_GetCatcher( ) & KEYCATCH_CONSOLE )
         con.finalFrac = 0.5;        // half screen
     else
         con.finalFrac = 0;              // none visible
     // scroll towards the destination height
     if (con.finalFrac < con.displayFrac)
     {
         con.displayFrac -= con_conspeed->value*cls.realFrametime*0.001;
         if (con.finalFrac > con.displayFrac)
             con.displayFrac = con.finalFrac;
     }
     else if (con.finalFrac > con.displayFrac)
     {
         con.displayFrac += con_conspeed->value*cls.realFrametime*0.001;
         if (con.finalFrac < con.displayFrac)
             con.displayFrac = con.finalFrac;
     }
 }
Referenced by CL_Frame().
Con_Shutdown()
void Con_Shutdown (void)
Definition at line 387 of file cl_console.c.
 {
     Cmd_RemoveCommand("toggleconsole");
     Cmd_RemoveCommand("togglemenu");
     Cmd_RemoveCommand("messagemode");
     Cmd_RemoveCommand("messagemode2");
     Cmd_RemoveCommand("messagemode3");
     Cmd_RemoveCommand("messagemode4");
     Cmd_RemoveCommand("clear");
     Cmd_RemoveCommand("condump");
 }
Referenced by CL_Shutdown().
Con_ToggleConsole_f()
void Con_ToggleConsole_f (void)
Definition at line 70 of file cl_console.c.
{
     // Can't toggle the console when it's the only thing available
     if ( clc.state == CA_DISCONNECTED && Key_GetCatcher( ) == KEYCATCH_CONSOLE ) {
         return;
     }
     if ( con_autoclear->integer ) {
         Field_Clear( &g_consoleField );
     }
     g_consoleField.widthInChars = g_console_field_width;
     Con_ClearNotify ();
     Key_SetCatcher( Key_GetCatcher( ) ^ KEYCATCH_CONSOLE );
 }
Referenced by CL_KeyDownEvent(), and Con_Init().
Con_Top()
void Con_Top (void)
Definition at line 822 of file cl_console.c.
                      {
     con.display = con.totallines;
     if ( con.current - con.display >= con.totallines ) {
         con.display = con.current - con.totallines + 1;
     }
 }
Referenced by Console_Key().
IN_CenterView()
void IN_CenterView (void)
Definition at line 270 of file cl_input.c.
{
     cl.viewangles[PITCH] = -SHORT2ANGLE(cl.snap.ps.delta_angles[PITCH]);
 }
Referenced by CL_InitInput(), and IN_MLookUp().
Key_GetCatcher()
int Key_GetCatcher (void)
Definition at line 1436 of file cl_keys.c.
{
     return keyCatchers;
 }
Referenced by CL_BindUICommand(), CL_CgameSystemCalls(), CL_CharEvent(), CL_CmdButtons(), CL_Frame(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), CL_ParseBinding(), CL_ShutdownCGame(), CL_ShutdownUI(), CL_UISystemCalls(), Con_Close(), Con_DrawConsole(), Con_DrawInput(), Con_DrawNotify(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), Con_RunConsole(), Con_ToggleConsole_f(), Message_Key(), and SCR_DrawScreenField().
Key_KeynumToString()
char* Key_KeynumToString (int keynum)
Definition at line 860 of file cl_keys.c.
{
     keyname_t   *kn;
     static  char    tinystr[5];
     int         i, j;
     if ( keynum == -1 ) {
         return "<KEY NOT FOUND>";
     }
     if ( keynum < 0 || keynum >= MAX_KEYS ) {
         return "<OUT OF RANGE>";
     }
     // check for printable ascii (don't use quote)
     if ( keynum > 32 && keynum < 127 && keynum != '"' && keynum != ';' ) {
         tinystr[0] = keynum;
         tinystr[1] = 0;
         return tinystr;
     }
     // check for a key string
     for ( kn=keynames ; kn->name ; kn++ ) {
         if (keynum == kn->keynum) {
             return kn->name;
         }
     }
     // make a hex string
     i = keynum >> 4;
     j = keynum & 15;
     tinystr[0] = '0';
     tinystr[1] = 'x';
     tinystr[2] = i > 9 ? i - 10 + 'a' : i + '0';
     tinystr[3] = j > 9 ? j - 10 + 'a' : j + '0';
     tinystr[4] = 0;
     return tinystr;
 }
Referenced by Key_Bind_f(), Key_Bindlist_f(), Key_KeynumToStringBuf(), and Key_WriteBindings().
Key_SetCatcher()
void Key_SetCatcher (int catcher)
Definition at line 1445 of file cl_keys.c.
{
     // If the catcher state is changing, clear all key states
     if( catcher != keyCatchers )
         Key_ClearStates( );
     keyCatchers = catcher;
 }
Referenced by CL_CgameSystemCalls(), CL_Connect_f(), CL_KeyDownEvent(), CL_MapLoading(), CL_Shutdown(), CL_ShutdownCGame(), CL_ShutdownUI(), CL_StartDemoLoop(), CL_UISystemCalls(), Con_Close(), Con_MessageMode2_f(), Con_MessageMode3_f(), Con_MessageMode4_f(), Con_MessageMode_f(), Con_ToggleConsole_f(), and Message_Key().
Key_StringToKeynum()
int Key_StringToKeynum (char * str)
Definition at line 826 of file cl_keys.c.
{
     keyname_t   *kn;
     int         n;
     if ( !str || !str[0] ) {
         return -1;
     }
     if ( !str[1] ) {
         return tolower( str[0] );
     }
     // check for hex code
     n = Com_HexStrToInt( str );
     if ( n >= 0 && n < MAX_KEYS ) {
         return n;
     }
     // scan for a text match
     for ( kn=keynames ; kn->name ; kn++ ) {
         if ( !Q_stricmp( str,kn->name ) )
             return kn->keynum;
     }
     return -1;
 }
Referenced by Key_Bind_f(), and Key_Unbind_f().
LAN_LoadCachedServers()
void LAN_LoadCachedServers (void)
Definition at line 50 of file cl_ui.c.
{
     int size;
     fileHandle_t fileIn;
     cls.numglobalservers = cls.numfavoriteservers = 0;
     cls.numGlobalServerAddresses = 0;
     if (FS_SV_FOpenFileRead("servercache.dat", &fileIn)) {
         FS_Read(&cls.numglobalservers, sizeof(int), fileIn);
         FS_Read(&cls.numfavoriteservers, sizeof(int), fileIn);
         FS_Read(&size, sizeof(int), fileIn);
         if (size == sizeof(cls.globalServers) + sizeof(cls.favoriteServers)) {
             FS_Read(&cls.globalServers, sizeof(cls.globalServers), fileIn);
             FS_Read(&cls.favoriteServers, sizeof(cls.favoriteServers), fileIn);
         } else {
             cls.numglobalservers = cls.numfavoriteservers = 0;
             cls.numGlobalServerAddresses = 0;
         }
         FS_FCloseFile(fileIn);
     }
 }
Referenced by CL_UISystemCalls().
LAN_SaveServersToCache()
void LAN_SaveServersToCache (void)
Definition at line 75 of file cl_ui.c.
{
     int size;
     fileHandle_t fileOut = FS_SV_FOpenFileWrite("servercache.dat");
     FS_Write(&cls.numglobalservers, sizeof(int), fileOut);
     FS_Write(&cls.numfavoriteservers, sizeof(int), fileOut);
     size = sizeof(cls.globalServers) + sizeof(cls.favoriteServers);
     FS_Write(&size, sizeof(int), fileOut);
     FS_Write(&cls.globalServers, sizeof(cls.globalServers), fileOut);
     FS_Write(&cls.favoriteServers, sizeof(cls.favoriteServers), fileOut);
     FS_FCloseFile(fileOut);
 }
Referenced by CL_UISystemCalls().
SCR_AdjustFrom640()
void SCR_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 59 of file cl_scrn.c.
{
     float   xscale;
     float   yscale;
 #if 0
         // adjust for wide screens
         if ( cls.glconfig.vidWidth * 480 > cls.glconfig.vidHeight * 640 ) {
             *x += 0.5 * ( cls.glconfig.vidWidth - ( cls.glconfig.vidHeight * 640 / 480 ) );
         }
 #endif
     // scale for screen sizes
     xscale = cls.glconfig.vidWidth / 640.0;
     yscale = cls.glconfig.vidHeight / 480.0;
     if ( x ) {
         *x *= xscale;
     }
     if ( y ) {
         *y *= yscale;
     }
     if ( w ) {
         *w *= xscale;
     }
     if ( h ) {
         *h *= yscale;
     }
 }
Referenced by CIN_DrawCinematic(), Con_DrawSolidConsole(), SCR_DrawChar(), SCR_DrawNamedPic(), SCR_DrawPic(), and SCR_FillRect().
SCR_DebugGraph()
void SCR_DebugGraph (float value)
Definition at line 408 of file cl_scrn.c.
 {
     values[current] = value;
     current = (current + 1) % ARRAY_LEN(values);
 }
SCR_DrawBigString()
void SCR_DrawBigString (int x, int y, const char * s, float alpha, qboolean noColorEscape)
Definition at line 246 of file cl_scrn.c.
{
     float   color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     SCR_DrawStringExt( x, y, BIGCHAR_WIDTH, s, color, qfalse, noColorEscape );
 }
Referenced by Con_DrawNotify(), and Field_VariableSizeDraw().
SCR_DrawBigStringColor()
void SCR_DrawBigStringColor (int x, int y, const char * s, vec4_t color, qboolean noColorEscape)
Definition at line 254 of file cl_scrn.c.
{
     SCR_DrawStringExt( x, y, BIGCHAR_WIDTH, s, color, qtrue, noColorEscape );
 }
SCR_DrawCinematic()
void SCR_DrawCinematic (void)
Definition at line 1638 of file cl_cin.c.
{
     if (CL_handle >= 0 && CL_handle < MAX_VIDEO_HANDLES) {
         CIN_DrawCinematic(CL_handle);
     }
 }
Referenced by SCR_DrawScreenField().
SCR_DrawNamedPic()
void SCR_DrawNamedPic (float x, float y, float width, float height, const char * picname)
Definition at line 41 of file cl_scrn.c.
{
     qhandle_t   hShader;
     assert( width != 0 );
     hShader = re.RegisterShader( picname );
     SCR_AdjustFrom640( &x, &y, &width, &height );
     re.DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
SCR_DrawPic()
void SCR_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
Definition at line 111 of file cl_scrn.c.
{
     SCR_AdjustFrom640( &x, &y, &width, &height );
     re.DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
Referenced by Con_DrawSolidConsole().
SCR_DrawSmallChar()
void SCR_DrawSmallChar (int x, int y, int ch)
Definition at line 160 of file cl_scrn.c.
{
     int row, col;
     float frow, fcol;
     float size;
     ch &= 255;
     if ( ch == ' ' ) {
         return;
     }
     if ( y < -SMALLCHAR_HEIGHT ) {
         return;
     }
     row = ch>>4;
     col = ch&15;
     frow = row*0.0625;
     fcol = col*0.0625;
     size = 0.0625;
     re.DrawStretchPic( x, y, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT,
                        fcol, frow,
                        fcol + size, frow + size,
                        cls.charSetShader );
 }
Referenced by Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), Field_VariableSizeDraw(), and SCR_DrawSmallStringExt().
SCR_DrawSmallStringExt()
void SCR_DrawSmallStringExt (int x, int y, const char * string, float * setColor, qboolean forceColor, qboolean noColorEscape)
Definition at line 267 of file cl_scrn.c.
{
     vec4_t      color;
     const char  *s;
     int         xx;
     // draw the colored text
     s = string;
     xx = x;
     re.SetColor( setColor );
     while ( *s ) {
         if ( Q_IsColorString( s ) ) {
             if ( !forceColor ) {
                 Com_Memcpy( color, g_color_table[ColorIndex(*(s+1))], sizeof( color ) );
                 color[3] = setColor[3];
                 re.SetColor( color );
             }
             if ( !noColorEscape ) {
                 s += 2;
                 continue;
             }
         }
         SCR_DrawSmallChar( xx, y, *s );
         xx += SMALLCHAR_WIDTH;
         s++;
     }
     re.SetColor( NULL );
 }
Referenced by Field_VariableSizeDraw().
SCR_FillRect()
void SCR_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 94 of file cl_scrn.c.
{
     re.SetColor( color );
     SCR_AdjustFrom640( &x, &y, &width, &height );
     re.DrawStretchPic( x, y, width, height, 0, 0, 0, 0, cls.whiteShader );
     re.SetColor( NULL );
 }
Referenced by Con_DrawSolidConsole().
SCR_GetBigStringWidth()
int SCR_GetBigStringWidth (const char * str)
Definition at line 320 of file cl_scrn.c.
{
     return SCR_Strlen( str ) * BIGCHAR_WIDTH;
 }
SCR_Init()
void SCR_Init (void)
Definition at line 455 of file cl_scrn.c.
                       {
     cl_timegraph = Cvar_Get ("timegraph", "0", CVAR_CHEAT);
     cl_debuggraph = Cvar_Get ("debuggraph", "0", CVAR_CHEAT);
     cl_graphheight = Cvar_Get ("graphheight", "32", CVAR_CHEAT);
     cl_graphscale = Cvar_Get ("graphscale", "1", CVAR_CHEAT);
     cl_graphshift = Cvar_Get ("graphshift", "0", CVAR_CHEAT);
     scr_initialized = qtrue;
 }
Referenced by CL_Init().
SCR_RunCinematic()
void SCR_RunCinematic (void)
Definition at line 1644 of file cl_cin.c.
 {
     if (CL_handle >= 0 && CL_handle < MAX_VIDEO_HANDLES) {
         CIN_RunCinematic(CL_handle);
     }
 }
Referenced by CL_Frame(), and CL_PlayCinematic_f().
SCR_StopCinematic()
void SCR_StopCinematic (void)
Definition at line 1651 of file cl_cin.c.
{
     if (CL_handle >= 0 && CL_handle < MAX_VIDEO_HANDLES) {
         CIN_StopCinematic(CL_handle);
         S_StopAllSounds ();
         CL_handle = -1;
     }
 }
Referenced by CL_Disconnect(), CL_Disconnect_f(), and CL_PlayCinematic_f().
SCR_UpdateScreen()
void SCR_UpdateScreen (void)
Definition at line 559 of file cl_scrn.c.
{
     static int  recursive;
     if ( !scr_initialized ) {
         return;             // not initialized yet
     }
     if ( ++recursive > 2 ) {
         Com_Error( ERR_FATAL, "SCR_UpdateScreen: recursively called" );
     }
     recursive = 1;
     // If there is no VM, there are also no rendering commands issued. Stop the renderer in
     // that case.
     if( uivm || com_dedicated->integer )
     {
         // XXX
         int in_anaglyphMode = Cvar_VariableIntegerValue("r_anaglyphMode");
         // if running in stereo, we need to draw the frame twice
         if ( cls.glconfig.stereoEnabled || in_anaglyphMode) {
             SCR_DrawScreenField( STEREO_LEFT );
             SCR_DrawScreenField( STEREO_RIGHT );
         } else {
             SCR_DrawScreenField( STEREO_CENTER );
         }
         if ( com_speeds->integer ) {
             re.EndFrame( &time_frontend, &time_backend );
         } else {
             re.EndFrame( NULL, NULL );
         }
     }
     recursive = 0;
 }
Referenced by CL_CgameSystemCalls(), CL_Disconnect(), CL_Frame(), CL_MapLoading(), CL_UISystemCalls(), and Console_Key().
Variable Documentation
cgvm
vm_t* cgvm
Definition at line 128 of file cl_main.c.
Referenced by CL_CGameRendering(), CL_GameCommand(), CL_InitCGame(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), CL_ShutdownCGame(), Con_MessageMode3_f(), and Con_MessageMode4_f().
cl
clientActive_t cl
Definition at line 125 of file cl_main.c.
Referenced by CalculateRanks(), CG_EntityEffects(), CheckExitRules(), CheckIntermissionExit(), CL_AdjustAngles(), CL_AdjustTimeDelta(), CL_CGameRendering(), CL_CheckTimeout(), CL_ClearState(), CL_CompletePlayerName(), CL_ConfigstringModified(), CL_Configstrings_f(), CL_CreateCmd(), CL_CreateNewCommands(), CL_DeltaEntity(), CL_FinishMove(), CL_FirstSnapshot(), CL_Frame(), CL_GetCurrentCmdNumber(), CL_GetCurrentSnapshotNumber(), CL_GetGameState(), CL_GetParseEntityState(), CL_GetServerCommand(), CL_GetSnapshot(), CL_GetUserCmd(), CL_InitCGame(), CL_JoystickEvent(), CL_JoystickMove(), CL_MapLoading(), CL_MouseEvent(), CL_MouseMove(), CL_ParseGamestate(), CL_ParsePacketEntities(), CL_ParseServerInfo(), CL_ParseSnapshot(), CL_ReadyToSendPacket(), CL_Record_f(), CL_Sayto_f(), CL_SendPureChecksums(), CL_SetCGameTime(), CL_SetUserCmdValue(), CL_SystemInfoChanged(), CL_WritePacket(), ClientForString(), ClientNumberFromString(), Com_Frame(), Con_DrawNotify(), DeathmatchScoreboardMessage(), ExitLevel(), G_CountBotPlayers(), G_CountBotPlayersByName(), G_CountHumanPlayers(), G_RemoveRandomBot(), GetClientState(), GetConfigString(), IN_CenterView(), LogExit(), Pickup_Team(), SpectatorClientEndFrame(), SV_AddBanToList(), SV_Ban_f(), SV_BanNum_f(), SV_BeginDownload_f(), SV_BotAllocateClient(), SV_BotFreeClient(), SV_BotGetConsoleMessage(), SV_BotGetSnapshotEntity(), SV_CalcPings(), SV_CheckPaused(), SV_CheckTimeouts(), SV_ClientCommand(), SV_ClientThink(), SV_CloseDownload(), SV_CompletePlayerName(), SV_ConSayto_f(), SV_ConTell_f(), SV_DirectConnect(), SV_Disconnect_f(), SV_DoneDownload_f(), SV_DumpUser_f(), SV_ExecuteClientCommand(), SV_ExecuteClientMessage(), SV_FinalMessage(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_KickAll_f(), SV_KickBots_f(), SV_KickNum_f(), SV_NextDownload_f(), SV_PacketEvent(), SV_ResetPureClient_f(), SV_SendDownloadMessages(), SV_SendQueuedMessages(), SV_SendServerCommand(), SV_Status_f(), SV_StopDownload_f(), SV_UpdateUserinfo_f(), SV_UserinfoChanged(), SV_UserMove(), SV_VerifyPaks_f(), SV_WriteDownloadToClient(), SVC_Status(), Svcmd_ForceTeam_f(), Team_TouchEnemyFlag(), and Team_TouchOurFlag().
cl_activeAction
cvar_t* cl_activeAction
Definition at line 107 of file cl_main.c.
Referenced by CL_FirstSnapshot(), and CL_Init().
cl_allowDownload
cvar_t* cl_allowDownload
Definition at line 111 of file cl_main.c.
Referenced by CL_Init(), CL_InitDownloads(), and CL_NextDownload().
cl_anglespeedkey
cvar_t* cl_anglespeedkey
Definition at line 282 of file cl_input.c.
Referenced by CL_AdjustAngles(), CL_Init(), and CL_JoystickMove().
cl_autoRecordDemo
cvar_t* cl_autoRecordDemo
Definition at line 77 of file cl_main.c.
Referenced by CL_Frame(), CL_Init(), and CL_ParseGamestate().
cl_aviFrameRate
cvar_t* cl_aviFrameRate
Definition at line 78 of file cl_main.c.
Referenced by CL_Frame(), CL_Init(), CL_OpenAVIForWriting(), and S_GetSoundtime().
cl_aviMotionJpeg
cvar_t* cl_aviMotionJpeg
Definition at line 79 of file cl_main.c.
Referenced by CL_Init(), and CL_OpenAVIForWriting().
cl_connectedToCheatServer
int cl_connectedToCheatServer
Definition at line 331 of file cl_parse.c.
Referenced by CL_InitCGame(), and CL_SystemInfoChanged().
cl_connectedToPureServer
int cl_connectedToPureServer
Definition at line 330 of file cl_parse.c.
Referenced by CL_Disconnect(), CL_InitCGame(), CL_InitUI(), and CL_SystemInfoChanged().
cl_consoleKeys
cvar_t* cl_consoleKeys
Definition at line 121 of file cl_main.c.
Referenced by CL_Init().
cl_conXOffset
cvar_t* cl_conXOffset
Definition at line 112 of file cl_main.c.
Referenced by CL_Init(), and Con_DrawNotify().
cl_debugMove
cvar_t* cl_debugMove
Definition at line 56 of file cl_main.c.
Referenced by CL_CreateCmd(), CL_InitInput(), and SCR_DrawScreenField().
cl_downloadMethod
cvar_t* cl_downloadMethod
cl_freelook
cvar_t* cl_freelook
Definition at line 82 of file cl_main.c.
Referenced by CL_Init(), CL_MouseMove(), and IN_MLookUp().
cl_freezeDemo
cvar_t* cl_freezeDemo
Definition at line 71 of file cl_main.c.
Referenced by CL_Init(), and CL_SetCGameTime().
cl_inGameVideo
cvar_t* cl_inGameVideo
Definition at line 113 of file cl_main.c.
Referenced by CIN_PlayCinematic(), CIN_UploadCinematic(), and CL_Init().
cl_lanForcePackets
cvar_t* cl_lanForcePackets
Definition at line 117 of file cl_main.c.
Referenced by CL_Init(), and CL_ReadyToSendPacket().
cl_maxpackets
cvar_t* cl_maxpackets
Definition at line 67 of file cl_main.c.
Referenced by CL_Init(), and CL_ReadyToSendPacket().
cl_mouseAccel
cvar_t* cl_mouseAccel
Definition at line 85 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_mouseAccelOffset
cvar_t* cl_mouseAccelOffset
Definition at line 86 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_mouseAccelStyle
cvar_t* cl_mouseAccelStyle
Definition at line 87 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_nodelta
cvar_t* cl_nodelta
Definition at line 55 of file cl_main.c.
Referenced by CL_InitInput(), and CL_WritePacket().
cl_noprint
cvar_t* cl_noprint
Definition at line 58 of file cl_main.c.
Referenced by CL_ConsolePrint(), and CL_Init().
cl_oldGame
char cl_oldGame[MAX_QPATH]
Definition at line 131 of file cl_main.c.
Referenced by CL_OldGame(), and CL_ParseGamestate().
cl_oldGameSet
qboolean cl_oldGameSet
Definition at line 132 of file cl_main.c.
Referenced by CL_Init(), CL_OldGame(), and CL_ParseGamestate().
cl_packetdup
cvar_t* cl_packetdup
Definition at line 68 of file cl_main.c.
Referenced by CL_Init(), and CL_WritePacket().
cl_pitchspeed
cvar_t* cl_pitchspeed
Definition at line 278 of file cl_input.c.
Referenced by CL_AdjustAngles(), and CL_Init().
cl_run
cvar_t* cl_run
Definition at line 280 of file cl_input.c.
Referenced by CL_Init(), CL_JoystickMove(), and CL_KeyMove().
cl_sensitivity
cvar_t* cl_sensitivity
Definition at line 83 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_showMouseRate
cvar_t* cl_showMouseRate
Definition at line 88 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
cl_shownet
cvar_t* cl_shownet
Definition at line 73 of file cl_main.c.
cl_showSend
cvar_t* cl_showSend
Definition at line 74 of file cl_main.c.
Referenced by CL_Init(), CL_SendCmd(), and CL_WritePacket().
cl_showTimeDelta
cvar_t* cl_showTimeDelta
Definition at line 70 of file cl_main.c.
Referenced by CL_AdjustTimeDelta(), and CL_Init().
cl_timedemo
cvar_t* cl_timedemo
Definition at line 75 of file cl_main.c.
Referenced by CL_DemoCompleted(), CL_Init(), and CL_SetCGameTime().
cl_timegraph
cvar_t* cl_timegraph
Definition at line 28 of file cl_scrn.c.
Referenced by CL_Frame(), SCR_DrawScreenField(), and SCR_Init().
cl_timeNudge
cvar_t* cl_timeNudge
Definition at line 69 of file cl_main.c.
Referenced by CL_Init(), and CL_SetCGameTime().
cl_yawspeed
cvar_t* cl_yawspeed
Definition at line 277 of file cl_input.c.
Referenced by CL_AdjustAngles(), and CL_Init().
clc
clientConnection_t clc
Definition at line 126 of file cl_main.c.
Referenced by CIN_PlayCinematic(), CIN_RunCinematic(), CIN_StopCinematic(), CL_AddReliableCommand(), CL_AdjustTimeDelta(), CL_BeginDownload(), CL_CGameRendering(), CL_CharEvent(), CL_CheckForResend(), CL_CheckTimeout(), CL_CheckUserinfo(), CL_Clientinfo_f(), CL_CompletePlayerName(), CL_Configstrings_f(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_CreateNewCommands(), CL_DemoCompleted(), CL_DemoFrameDurationSDev(), CL_Disconnect(), CL_Disconnect_f(), CL_DownloadsComplete(), CL_FirstSnapshot(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_Frame(), CL_GetServerCommand(), CL_Init(), CL_InitCGame(), CL_InitDownloads(), CL_InitUI(), CL_KeyDownEvent(), CL_MapLoading(), CL_Netchan_Decode(), CL_Netchan_Encode(), CL_NextDownload(), CL_OldGame(), CL_PacketEvent(), CL_ParseBinding(), CL_ParseCommandString(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParseServerInfo(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PlayCinematic_f(), CL_PlayDemo_f(), CL_Rcon_f(), CL_ReadDemoMessage(), CL_ReadyToSendPacket(), CL_Record_f(), CL_SendCmd(), CL_ServerStatus_f(), CL_SetCGameTime(), CL_ShutdownAll(), CL_StopRecord_f(), CL_SystemInfoChanged(), CL_Vid_Restart_f(), CL_Video_f(), CL_WriteDemoMessage(), CL_WritePacket(), Con_DrawConsole(), Con_DrawInput(), CON_Input(), Con_ToggleConsole_f(), Console_Key(), GetClientState(), Message_Key(), RoQShutdown(), S_GetSoundtime(), SCR_DrawDemoRecording(), and SCR_DrawScreenField().
cls
clientStatic_t cls
Definition at line 127 of file cl_main.c.
Referenced by CL_AdjustAngles(), CL_AdjustTimeDelta(), CL_BeginDownload(), CL_CDDialog(), CL_CheckForResend(), CL_CheckTimeout(), CL_ConnectionlessPacket(), CL_ConsolePrint(), CL_DownloadsComplete(), CL_FirstSnapshot(), CL_Frame(), CL_GetGlconfig(), CL_GlobalServers_f(), CL_Init(), CL_InitRenderer(), CL_InitUI(), CL_JoystickMove(), CL_LocalServers_f(), CL_MapLoading(), CL_MotdPacket(), CL_OpenAVIForWriting(), CL_PacketEvent(), CL_ParseSnapshot(), CL_Rcon_f(), CL_ReadDemoMessage(), CL_ReadyToSendPacket(), CL_RequestAuthorization(), CL_RequestMotd(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_SetCGameTime(), CL_SetServerInfoByAddress(), CL_Shutdown(), CL_ShutdownAll(), CL_ShutdownCGame(), CL_ShutdownUI(), CL_Snd_Shutdown(), CL_StartHunkUsers(), CL_UpdateVisiblePings_f(), CL_Vid_Restart_f(), CL_WritePacket(), Con_DrawNotify(), Con_DrawSolidConsole(), Con_Linefeed(), Con_RunConsole(), Field_VariableSizeDraw(), GetClientState(), LAN_AddServer(), LAN_GetServerAddressString(), LAN_GetServerCount(), LAN_GetServerInfo(), LAN_GetServerPing(), LAN_GetServerPtr(), LAN_LoadCachedServers(), LAN_MarkServerVisible(), LAN_RemoveServer(), LAN_ResetPings(), LAN_SaveServersToCache(), LAN_ServerIsVisible(), readQuadInfo(), S_Base_AddLoopingSound(), SCR_AdjustFrom640(), SCR_DrawChar(), SCR_DrawDebugGraph(), SCR_DrawScreenField(), SCR_DrawSmallChar(), SCR_FillRect(), SCR_UpdateScreen(), and UI_GameCommand().
g_console_field_width
int g_console_field_width
Definition at line 27 of file cl_console.c.
Referenced by CL_InitRenderer(), Con_Init(), Con_ToggleConsole_f(), and Console_Key().
j_forward
cvar_t* j_forward
Definition at line 98 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_forward_axis
cvar_t* j_forward_axis
Definition at line 103 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_pitch
cvar_t* j_pitch
Definition at line 96 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_pitch_axis
cvar_t* j_pitch_axis
Definition at line 101 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_side
cvar_t* j_side
Definition at line 99 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_side_axis
cvar_t* j_side_axis
Definition at line 104 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_up
cvar_t* j_up
Definition at line 100 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_up_axis
cvar_t* j_up_axis
Definition at line 105 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_yaw
cvar_t* j_yaw
Definition at line 97 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
j_yaw_axis
cvar_t* j_yaw_axis
Definition at line 102 of file cl_main.c.
Referenced by CL_Init(), and CL_JoystickMove().
m_filter
cvar_t* m_filter
Definition at line 94 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_forward
cvar_t* m_forward
Definition at line 92 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_pitch
cvar_t* m_pitch
Definition at line 90 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_side
cvar_t* m_side
Definition at line 93 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
m_yaw
cvar_t* m_yaw
Definition at line 91 of file cl_main.c.
Referenced by CL_Init(), and CL_MouseMove().
re
refexport_t re
Definition at line 135 of file cl_main.c.
Referenced by CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddMoveScaleFade(), CG_AddScaleFade(), CG_AddScorePlum(), CG_AddSpriteExplosion(), CG_BubbleTrail(), CG_LaunchExplode(), CG_LaunchGib(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), CG_RailTrail(), CG_ScorePlum(), CG_ShotgunEjectBrass(), CG_SmokePuff(), CG_SpawnEffect(), CIN_DrawCinematic(), CIN_UploadCinematic(), CL_CgameSystemCalls(), CL_InitCGame(), CL_InitRef(), CL_InitRenderer(), CL_ShutdownAll(), CL_ShutdownRef(), CL_TakeVideoFrame(), CL_UISystemCalls(), Con_DrawInput(), Con_DrawNotify(), Con_DrawSolidConsole(), GetRefAPI(), SCR_DrawChar(), SCR_DrawDebugGraph(), SCR_DrawNamedPic(), SCR_DrawPic(), SCR_DrawScreenField(), SCR_DrawSmallChar(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), SCR_FillRect(), SCR_UpdateScreen(), and trap_R_AddRefEntityToScene().
uivm
vm_t* uivm
Definition at line 29 of file cl_ui.c.
Referenced by CIN_PlayCinematic(), CL_CharEvent(), CL_Disconnect(), CL_Frame(), CL_InitUI(), CL_KeyDownEvent(), CL_KeyUpEvent(), CL_MouseEvent(), CL_ShutdownUI(), SCR_DrawScreenField(), SCR_UpdateScreen(), UI_GameCommand(), and UI_usesUniqueCDKey().