ioquake3 doxygen: aas_export_s Struct Reference
aas_export_s Struct Reference
#include <botlib.h>
Public Attributes
void(* AAS_EntityInfo)(int entnum, struct aas_entityinfo_s *info)
int(* AAS_Initialized)(void)
void(* AAS_PresenceTypeBoundingBox)(int presencetype, vec3_t mins, vec3_t maxs)
float(* AAS_Time)(void)
int(* AAS_PointAreaNum)(vec3_t point)
int(* AAS_PointReachabilityAreaIndex)(vec3_t point)
int(* AAS_TraceAreas)(vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
int(* AAS_BBoxAreas)(vec3_t absmins, vec3_t absmaxs, int *areas, int maxareas)
int(* AAS_AreaInfo)(int areanum, struct aas_areainfo_s *info)
int(* AAS_PointContents)(vec3_t point)
int(* AAS_NextBSPEntity)(int ent)
int(* AAS_ValueForBSPEpairKey)(int ent, char *key, char *value, int size)
int(* AAS_VectorForBSPEpairKey)(int ent, char *key, vec3_t v)
int(* AAS_FloatForBSPEpairKey)(int ent, char *key, float *value)
int(* AAS_IntForBSPEpairKey)(int ent, char *key, int *value)
int(* AAS_AreaReachability)(int areanum)
int(* AAS_AreaTravelTimeToGoalArea)(int areanum, vec3_t origin, int goalareanum, int travelflags)
int(* AAS_EnableRoutingArea)(int areanum, int enable)
int(* AAS_PredictRoute)(struct aas_predictroute_s *route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
int(* AAS_AlternativeRouteGoals)(vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, struct aas_altroutegoal_s *altroutegoals, int maxaltroutegoals, int type)
int(* AAS_Swimming)(vec3_t origin)
int(* AAS_PredictClientMovement)(struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
Detailed Description
Definition at line 208 of file botlib.h.
Member Data Documentation
AAS_AlternativeRouteGoals
int(* aas_export_s::AAS_AlternativeRouteGoals) (vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, struct aas_altroutegoal_s *altroutegoals, int maxaltroutegoals, int type)
Definition at line 252 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_AreaInfo
int(* aas_export_s::AAS_AreaInfo) (int areanum, struct aas_areainfo_s *info)
Definition at line 227 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_AreaReachability
int(* aas_export_s::AAS_AreaReachability) (int areanum)
Definition at line 240 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_AreaTravelTimeToGoalArea
int(* aas_export_s::AAS_AreaTravelTimeToGoalArea) (int areanum, vec3_t origin, int goalareanum, int travelflags)
Definition at line 244 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_BBoxAreas
int(* aas_export_s::AAS_BBoxAreas) (vec3_t absmins, vec3_t absmaxs, int *areas, int maxareas)
Definition at line 226 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_EnableRoutingArea
int(* aas_export_s::AAS_EnableRoutingArea) (int areanum, int enable)
Definition at line 245 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_EntityInfo
void(* aas_export_s::AAS_EntityInfo) (int entnum, struct aas_entityinfo_s *info)
Definition at line 213 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_FloatForBSPEpairKey
int(* aas_export_s::AAS_FloatForBSPEpairKey) (int ent, char *key, float *value)
Definition at line 235 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_Initialized
int(* aas_export_s::AAS_Initialized) (void)
Definition at line 217 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_IntForBSPEpairKey
int(* aas_export_s::AAS_IntForBSPEpairKey) (int ent, char *key, int *value)
Definition at line 236 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_NextBSPEntity
int(* aas_export_s::AAS_NextBSPEntity) (int ent)
Definition at line 232 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_PointAreaNum
int(* aas_export_s::AAS_PointAreaNum) (vec3_t point)
Definition at line 223 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_PointContents
int(* aas_export_s::AAS_PointContents) (vec3_t point)
Definition at line 231 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_PointReachabilityAreaIndex
int(* aas_export_s::AAS_PointReachabilityAreaIndex) (vec3_t point)
Definition at line 224 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_PredictClientMovement
int(* aas_export_s::AAS_PredictClientMovement) (struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
Definition at line 259 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_PredictRoute
int(* aas_export_s::AAS_PredictRoute) (struct aas_predictroute_s *route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
Definition at line 246 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_PresenceTypeBoundingBox
void(* aas_export_s::AAS_PresenceTypeBoundingBox) (int presencetype, vec3_t mins, vec3_t maxs)
Definition at line 218 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_Swimming
int(* aas_export_s::AAS_Swimming) (vec3_t origin)
Definition at line 258 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_Time
float(* aas_export_s::AAS_Time) (void)
Definition at line 219 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_TraceAreas
int(* aas_export_s::AAS_TraceAreas) (vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
Definition at line 225 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_ValueForBSPEpairKey
int(* aas_export_s::AAS_ValueForBSPEpairKey) (int ent, char *key, char *value, int size)
Definition at line 233 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().
AAS_VectorForBSPEpairKey
int(* aas_export_s::AAS_VectorForBSPEpairKey) (int ent, char *key, vec3_t v)
Definition at line 234 of file botlib.h.
Referenced by Init_AAS_Export(), and SV_GameSystemCalls().