ioquake3 doxygen: C:/entry/dev/ioquake3/code/sys/sys_unix.c File Reference
sys_unix.c File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
#include "sys_local.h"
#include <signal.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <stdio.h>
#include <dirent.h>
#include <unistd.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <pwd.h>
#include <libgen.h>
#include <fcntl.h>
#include <fenv.h>
#include <sys/wait.h>
Macros
#define MEM_THRESHOLD 96*1024*1024
#define MAX_FOUND_FILES 0x1000
Functions
char * Sys_DefaultHomePath (void)
char * Sys_SteamPath (void)
char * Sys_GogPath (void)
int Sys_Milliseconds (void)
qboolean Sys_RandomBytes (byte *string, int len)
char * Sys_GetCurrentUser (void)
qboolean Sys_LowPhysicalMemory (void)
const char * Sys_Basename (char *path)
const char * Sys_Dirname (char *path)
FILE * Sys_FOpen (const char *ospath, const char *mode)
qboolean Sys_Mkdir (const char *path)
FILE * Sys_Mkfifo (const char *ospath)
char * Sys_Cwd (void)
void Sys_ListFilteredFiles (const char *basedir, char *subdirs, char *filter, char **list, int *numfiles)
char ** Sys_ListFiles (const char *directory, const char *extension, char *filter, int *numfiles, qboolean wantsubs)
void Sys_FreeFileList (char **list)
void Sys_Sleep (int msec)
void Sys_ErrorDialog (const char *error)
static void Sys_ClearExecBuffer (void)
static void Sys_AppendToExecBuffer (const char *text)
static int Sys_Exec (void)
static void Sys_ZenityCommand (dialogType_t type, const char *message, const char *title)
static void Sys_KdialogCommand (dialogType_t type, const char *message, const char *title)
static void Sys_XmessageCommand (dialogType_t type, const char *message, const char *title)
dialogResult_t Sys_Dialog (dialogType_t type, const char *message, const char *title)
void Sys_GLimpSafeInit (void)
void Sys_GLimpInit (void)
void Sys_SetFloatEnv (void)
void Sys_PlatformInit (void)
void Sys_PlatformExit (void)
void Sys_SetEnv (const char *name, const char *value)
int Sys_PID (void)
qboolean Sys_PIDIsRunning (int pid)
qboolean Sys_DllExtension (const char *name)
Variables
qboolean stdinIsATTY
static char homePath [MAX_OSPATH] = { 0 }
static char steamPath [MAX_OSPATH] = { 0 }
static char gogPath [MAX_OSPATH] = { 0 }
unsigned long sys_timeBase = 0
int curtime
static char execBuffer [1024]
static char * execBufferPointer
static char * execArgv [16]
static int execArgc
Macro Definition Documentation
MAX_FOUND_FILES
#define MAX_FOUND_FILES 0x1000
Definition at line 315 of file sys_unix.c.
MEM_THRESHOLD
#define MEM_THRESHOLD 96*1024*1024
Definition at line 195 of file sys_unix.c.
Function Documentation
Sys_AppendToExecBuffer()
static void Sys_AppendToExecBuffer (const char * text) static
Definition at line 617 of file sys_unix.c.
 {
     size_t size = sizeof( execBuffer ) - ( execBufferPointer - execBuffer );
     int length = strlen( text ) + 1;
     if( length > size || execArgc >= ARRAY_LEN( execArgv ) )
         return;
     Q_strncpyz( execBufferPointer, text, size );
     execArgv[ execArgc++ ] = execBufferPointer;
     execBufferPointer += length;
 }
Referenced by Sys_KdialogCommand(), Sys_XmessageCommand(), and Sys_ZenityCommand().
Sys_Basename()
const char* Sys_Basename (char * path)
Definition at line 214 of file sys_unix.c.
 {
     return basename( path );
 }
Sys_ClearExecBuffer()
static void Sys_ClearExecBuffer (void) static
Definition at line 605 of file sys_unix.c.
 {
     execBufferPointer = execBuffer;
     Com_Memset( execArgv, 0, sizeof( execArgv ) );
     execArgc = 0;
 }
Referenced by Sys_KdialogCommand(), Sys_XmessageCommand(), and Sys_ZenityCommand().
Sys_Cwd()
char* Sys_Cwd (void)
Definition at line 294 of file sys_unix.c.
 {
     static char cwd[MAX_OSPATH];
     char *result = getcwd( cwd, sizeof( cwd ) - 1 );
     if( result != cwd )
         return NULL;
     cwd[MAX_OSPATH-1] = 0;
     return cwd;
 }
Sys_DefaultHomePath()
char* Sys_DefaultHomePath (void)
Definition at line 58 of file sys_unix.c.
 {
     char *p;
     if( !*homePath && com_homepath != NULL )
     {
         if( ( p = getenv( "HOME" ) ) != NULL )
         {
             Com_sprintf(homePath, sizeof(homePath), "%s%c", p, PATH_SEP);
 #ifdef __APPLE__
             Q_strcat(homePath, sizeof(homePath),
                 "Library/Application Support/");
             if(com_homepath->string[0])
                 Q_strcat(homePath, sizeof(homePath), com_homepath->string);
             else
                 Q_strcat(homePath, sizeof(homePath), HOMEPATH_NAME_MACOSX);
 #else
             if(com_homepath->string[0])
                 Q_strcat(homePath, sizeof(homePath), com_homepath->string);
             else
                 Q_strcat(homePath, sizeof(homePath), HOMEPATH_NAME_UNIX);
 #endif
         }
     }
     return homePath;
 }
Sys_Dialog()
dialogResult_t Sys_Dialog (dialogType_t type, const char * message, const char * title)
Definition at line 750 of file sys_unix.c.
 {
     typedef enum
     {
         NONE = 0,
         ZENITY,
         KDIALOG,
         XMESSAGE,
         NUM_DIALOG_PROGRAMS
     } dialogCommandType_t;
     typedef void (*dialogCommandBuilder_t)( dialogType_t, const char *, const char * );
     const char              *session = getenv( "DESKTOP_SESSION" );
     qboolean                tried[ NUM_DIALOG_PROGRAMS ] = { qfalse };
     dialogCommandBuilder_t  commands[ NUM_DIALOG_PROGRAMS ] = { NULL };
     dialogCommandType_t     preferredCommandType = NONE;
     int                     i;
     commands[ ZENITY ] = &Sys_ZenityCommand;
     commands[ KDIALOG ] = &Sys_KdialogCommand;
     commands[ XMESSAGE ] = &Sys_XmessageCommand;
     // This may not be the best way
     if( !Q_stricmp( session, "gnome" ) )
         preferredCommandType = ZENITY;
     else if( !Q_stricmp( session, "kde" ) )
         preferredCommandType = KDIALOG;
     for( i = NONE + 1; i < NUM_DIALOG_PROGRAMS; i++ )
     {
         if( preferredCommandType != NONE && preferredCommandType != i )
             continue;
         if( !tried[ i ] )
         {
             int exitCode;
             commands[ i ]( type, message, title );
             exitCode = Sys_Exec( );
             if( exitCode >= 0 )
             {
                 switch( type )
                 {
                     case DT_YES_NO:    return exitCode ? DR_NO : DR_YES;
                     case DT_OK_CANCEL: return exitCode ? DR_CANCEL : DR_OK;
                     default:           return DR_OK;
                 }
             }
             tried[ i ] = qtrue;
             // The preference failed, so start again in order
             if( preferredCommandType != NONE )
             {
                 preferredCommandType = NONE;
                 i = NONE + 1;
             }
         }
     }
     Com_DPrintf( S_COLOR_YELLOW "WARNING: failed to show a dialog\n" );
     return DR_OK;
 }
Referenced by Sys_ErrorDialog().
Sys_Dirname()
const char* Sys_Dirname (char * path)
Definition at line 224 of file sys_unix.c.
 {
     return dirname( path );
 }
Sys_DllExtension()
qboolean Sys_DllExtension (const char * name)
Definition at line 923 of file sys_unix.c.
{
     const char *p;
     char c = 0;
     if ( COM_CompareExtension( name, DLL_EXT ) ) {
         return qtrue;
     }
 #ifdef __APPLE__
     // Allow system frameworks without dylib extensions
     // i.e., /System/Library/Frameworks/OpenAL.framework/OpenAL
     if ( strncmp( name, "/System/Library/Frameworks/", 27 ) == 0 ) {
         return qtrue;
     }
 #endif
     // Check for format of filename.so.1.2.3
     p = strstr( name, DLL_EXT "." );
     if ( p ) {
         p += strlen( DLL_EXT );
         // Check if .so is only followed for periods and numbers.
         while ( *p ) {
             c = *p;
             if ( !isdigit( c ) && c != '.' ) {
                 return qfalse;
             }
             p++;
         }
         // Don't allow filename to end in a period. file.so., file.so.0., etc
         if ( c != '.' ) {
             return qtrue;
         }
     }
     return qfalse;
 }
Sys_ErrorDialog()
void Sys_ErrorDialog (const char * error)
Definition at line 542 of file sys_unix.c.
 {
     char buffer[ 1024 ];
     unsigned int size;
     int f = -1;
     const char *homepath = Cvar_VariableString( "fs_homepath" );
     const char *gamedir = Cvar_VariableString( "fs_game" );
     const char *fileName = "crashlog.txt";
     char *dirpath = FS_BuildOSPath( homepath, gamedir, "");
     char *ospath = FS_BuildOSPath( homepath, gamedir, fileName );
     Sys_Print( va( "%s\n", error ) );
 #ifndef DEDICATED
     Sys_Dialog( DT_ERROR, va( "%s. See \"%s\" for details.", error, ospath ), "Error" );
 #endif
     // Make sure the write path for the crashlog exists...
     if(!Sys_Mkdir(homepath))
     {
         Com_Printf("ERROR: couldn't create path '%s' for crash log.\n", homepath);
         return;
     }
     if(!Sys_Mkdir(dirpath))
     {
         Com_Printf("ERROR: couldn't create path '%s' for crash log.\n", dirpath);
         return;
     }
     // We might be crashing because we maxed out the Quake MAX_FILE_HANDLES,
     // which will come through here, so we don't want to recurse forever by
     // calling FS_FOpenFileWrite()...use the Unix system APIs instead.
     f = open( ospath, O_CREAT | O_TRUNC | O_WRONLY, 0640 );
     if( f == -1 )
     {
         Com_Printf( "ERROR: couldn't open %s\n", fileName );
         return;
     }
     // We're crashing, so we don't care much if write() or close() fails.
     while( ( size = CON_LogRead( buffer, sizeof( buffer ) ) ) > 0 ) {
         if( write( f, buffer, size ) != size ) {
             Com_Printf( "ERROR: couldn't fully write to %s\n", fileName );
             break;
         }
     }
     close( f );
 }
Sys_Exec()
static int Sys_Exec (void) static
Definition at line 636 of file sys_unix.c.
 {
     pid_t pid = fork( );
     if( pid < 0 )
         return -1;
     if( pid )
     {
         // Parent
         int exitCode;
         wait( &exitCode );
         return WEXITSTATUS( exitCode );
     }
     else
     {
         // Child
         execvp( execArgv[ 0 ], execArgv );
         // Failed to execute
         exit( -1 );
         return -1;
     }
 }
Referenced by Sys_Dialog().
Sys_FOpen()
FILE* Sys_FOpen (const char * ospath, const char * mode)
Definition at line 234 of file sys_unix.c.
{
     struct stat buf;
     // check if path exists and is a directory
     if ( !stat( ospath, &buf ) && S_ISDIR( buf.st_mode ) )
         return NULL;
     return fopen( ospath, mode );
 }
Sys_FreeFileList()
void Sys_FreeFileList (char ** list)
Definition at line 479 of file sys_unix.c.
 {
     int i;
     if ( !list ) {
         return;
     }
     for ( i = 0 ; list[i] ; i++ ) {
         Z_Free( list[i] );
     }
     Z_Free( list );
 }
Sys_GetCurrentUser()
char* Sys_GetCurrentUser (void)
Definition at line 185 of file sys_unix.c.
 {
     struct passwd *p;
     if ( (p = getpwuid( getuid() )) == NULL ) {
         return "player";
     }
     return p->pw_name;
 }
Sys_GLimpInit()
void Sys_GLimpInit (void)
Definition at line 835 of file sys_unix.c.
 {
     // NOP
 }
Sys_GLimpSafeInit()
void Sys_GLimpSafeInit (void)
Definition at line 823 of file sys_unix.c.
 {
     // NOP
 }
Sys_GogPath()
char* Sys_GogPath (void)
Definition at line 117 of file sys_unix.c.
 {
     // GOG also doesn't let you install Quake 3 on Mac/Linux
     return gogPath;
 }
Sys_KdialogCommand()
static void Sys_KdialogCommand (dialogType_t type, const char * message, const char * title) static
Definition at line 702 of file sys_unix.c.
 {
     Sys_ClearExecBuffer( );
     Sys_AppendToExecBuffer( "kdialog" );
     switch( type )
     {
         default:
         case DT_INFO:      Sys_AppendToExecBuffer( "--msgbox" ); break;
         case DT_WARNING:   Sys_AppendToExecBuffer( "--sorry" ); break;
         case DT_ERROR:     Sys_AppendToExecBuffer( "--error" ); break;
         case DT_YES_NO:    Sys_AppendToExecBuffer( "--warningyesno" ); break;
         case DT_OK_CANCEL: Sys_AppendToExecBuffer( "--warningcontinuecancel" ); break;
     }
     Sys_AppendToExecBuffer( message );
     Sys_AppendToExecBuffer( va( "--title=%s", title ) );
 }
Referenced by Sys_Dialog().
Sys_ListFiles()
char** Sys_ListFiles (const char * directory, const char * extension, char * filter, int * numfiles, qboolean wantsubs)
Definition at line 379 of file sys_unix.c.
 {
     struct dirent *d;
     DIR           *fdir;
     qboolean      dironly = wantsubs;
     char          search[MAX_OSPATH];
     int           nfiles;
     char          **listCopy;
     char          *list[MAX_FOUND_FILES];
     int           i;
     struct stat   st;
     int           extLen;
     if (filter) {
         nfiles = 0;
         Sys_ListFilteredFiles( directory, "", filter, list, &nfiles );
         list[ nfiles ] = NULL;
         *numfiles = nfiles;
         if (!nfiles)
             return NULL;
         listCopy = Z_Malloc( ( nfiles + 1 ) * sizeof( *listCopy ) );
         for ( i = 0 ; i < nfiles ; i++ ) {
             listCopy[i] = list[i];
         }
         listCopy[i] = NULL;
         return listCopy;
     }
     if ( !extension)
         extension = "";
     if ( extension[0] == '/' && extension[1] == 0 ) {
         extension = "";
         dironly = qtrue;
     }
     extLen = strlen( extension );
     // search
     nfiles = 0;
     if ((fdir = opendir(directory)) == NULL) {
         *numfiles = 0;
         return NULL;
     }
     while ((d = readdir(fdir)) != NULL) {
         Com_sprintf(search, sizeof(search), "%s/%s", directory, d->d_name);
         if (stat(search, &st) == -1)
             continue;
         if ((dironly && !(st.st_mode & S_IFDIR)) ||
             (!dironly && (st.st_mode & S_IFDIR)))
             continue;
         if (*extension) {
             if ( strlen( d->d_name ) < extLen ||
                 Q_stricmp(
                     d->d_name + strlen( d->d_name ) - extLen,
                     extension ) ) {
                 continue; // didn't match
             }
         }
         if ( nfiles == MAX_FOUND_FILES - 1 )
             break;
         list[ nfiles ] = CopyString( d->d_name );
         nfiles++;
     }
     list[ nfiles ] = NULL;
     closedir(fdir);
     // return a copy of the list
     *numfiles = nfiles;
     if ( !nfiles ) {
         return NULL;
     }
     listCopy = Z_Malloc( ( nfiles + 1 ) * sizeof( *listCopy ) );
     for ( i = 0 ; i < nfiles ; i++ ) {
         listCopy[i] = list[i];
     }
     listCopy[i] = NULL;
     return listCopy;
 }
Sys_ListFilteredFiles()
void Sys_ListFilteredFiles (const char * basedir, char * subdirs, char * filter, char ** list, int * numfiles)
Definition at line 322 of file sys_unix.c.
 {
     char          search[MAX_OSPATH], newsubdirs[MAX_OSPATH];
     char          filename[MAX_OSPATH];
     DIR           *fdir;
     struct dirent *d;
     struct stat   st;
     if ( *numfiles >= MAX_FOUND_FILES - 1 ) {
         return;
     }
     if (strlen(subdirs)) {
         Com_sprintf( search, sizeof(search), "%s/%s", basedir, subdirs );
     }
     else {
         Com_sprintf( search, sizeof(search), "%s", basedir );
     }
     if ((fdir = opendir(search)) == NULL) {
         return;
     }
     while ((d = readdir(fdir)) != NULL) {
         Com_sprintf(filename, sizeof(filename), "%s/%s", search, d->d_name);
         if (stat(filename, &st) == -1)
             continue;
         if (st.st_mode & S_IFDIR) {
             if (Q_stricmp(d->d_name, ".") && Q_stricmp(d->d_name, "..")) {
                 if (strlen(subdirs)) {
                     Com_sprintf( newsubdirs, sizeof(newsubdirs), "%s/%s", subdirs, d->d_name);
                 }
                 else {
                     Com_sprintf( newsubdirs, sizeof(newsubdirs), "%s", d->d_name);
                 }
                 Sys_ListFilteredFiles( basedir, newsubdirs, filter, list, numfiles );
             }
         }
         if ( *numfiles >= MAX_FOUND_FILES - 1 ) {
             break;
         }
         Com_sprintf( filename, sizeof(filename), "%s/%s", subdirs, d->d_name );
         if (!Com_FilterPath( filter, filename, qfalse ))
             continue;
         list[ *numfiles ] = CopyString( filename );
         (*numfiles)++;
     }
     closedir(fdir);
 }
Referenced by Sys_ListFiles().
Sys_LowPhysicalMemory()
qboolean Sys_LowPhysicalMemory (void)
Definition at line 204 of file sys_unix.c.
 {
     return qfalse;
 }
Sys_Milliseconds()
int Sys_Milliseconds (void)
Definition at line 138 of file sys_unix.c.
 {
     struct timeval tp;
     gettimeofday(&tp, NULL);
     if (!sys_timeBase)
     {
         sys_timeBase = tp.tv_sec;
         return tp.tv_usec/1000;
     }
     curtime = (tp.tv_sec - sys_timeBase)*1000 + tp.tv_usec/1000;
     return curtime;
 }
Sys_Mkdir()
qboolean Sys_Mkdir (const char * path)
Definition at line 249 of file sys_unix.c.
 {
     int result = mkdir( path, 0750 );
     if( result != 0 )
         return errno == EEXIST;
     return qtrue;
 }
Referenced by Sys_ErrorDialog().
Sys_Mkfifo()
FILE* Sys_Mkfifo (const char * ospath)
Definition at line 264 of file sys_unix.c.
 {
     FILE    *fifo;
     int result;
     int fn;
     struct  stat buf;
     // if file already exists AND is a pipefile, remove it
     if( !stat( ospath, &buf ) && S_ISFIFO( buf.st_mode ) )
         FS_Remove( ospath );
     result = mkfifo( ospath, 0600 );
     if( result != 0 )
         return NULL;
     fifo = fopen( ospath, "w+" );
     if( fifo )
     {
         fn = fileno( fifo );
         fcntl( fn, F_SETFL, O_NONBLOCK );
     }
     return fifo;
 }
Sys_PID()
int Sys_PID (void)
Definition at line 901 of file sys_unix.c.
 {
     return getpid( );
 }
Sys_PIDIsRunning()
qboolean Sys_PIDIsRunning (int pid)
Definition at line 911 of file sys_unix.c.
 {
     return kill( pid, 0 ) == 0;
 }
Sys_PlatformExit()
void Sys_PlatformExit (void)
Definition at line 876 of file sys_unix.c.
 {
 }
Sys_PlatformInit()
void Sys_PlatformInit (void)
Definition at line 853 of file sys_unix.c.
 {
     const char* term = getenv( "TERM" );
     signal( SIGHUP, Sys_SigHandler );
     signal( SIGQUIT, Sys_SigHandler );
     signal( SIGTRAP, Sys_SigHandler );
     signal( SIGABRT, Sys_SigHandler );
     signal( SIGBUS, Sys_SigHandler );
     Sys_SetFloatEnv();
     stdinIsATTY = isatty( STDIN_FILENO ) &&
         !( term && ( !strcmp( term, "raw" ) || !strcmp( term, "dumb" ) ) );
 }
Sys_RandomBytes()
qboolean Sys_RandomBytes (byte * string, int len)
Definition at line 160 of file sys_unix.c.
 {
     FILE *fp;
     fp = fopen( "/dev/urandom", "r" );
     if( !fp )
         return qfalse;
     setvbuf( fp, NULL, _IONBF, 0 ); // don't buffer reads from /dev/urandom
     if( fread( string, sizeof( byte ), len, fp ) != len )
     {
         fclose( fp );
         return qfalse;
     }
     fclose( fp );
     return qtrue;
 }
Sys_SetEnv()
void Sys_SetEnv (const char * name, const char * value)
Definition at line 888 of file sys_unix.c.
 {
     if(value && *value)
         setenv(name, value, 1);
     else
         unsetenv(name);
 }
Sys_SetFloatEnv()
void Sys_SetFloatEnv (void)
Definition at line 840 of file sys_unix.c.
 {
     // rounding toward nearest
     fesetround(FE_TONEAREST);
 }
Referenced by Sys_PlatformInit().
Sys_Sleep()
void Sys_Sleep (int msec)
Definition at line 501 of file sys_unix.c.
 {
     if( msec == 0 )
         return;
     if( stdinIsATTY )
     {
         fd_set fdset;
         FD_ZERO(&fdset);
         FD_SET(STDIN_FILENO, &fdset);
         if( msec < 0 )
         {
             select(STDIN_FILENO + 1, &fdset, NULL, NULL, NULL);
         }
         else
         {
             struct timeval timeout;
             timeout.tv_sec = msec/1000;
             timeout.tv_usec = (msec%1000)*1000;
             select(STDIN_FILENO + 1, &fdset, NULL, NULL, &timeout);
         }
     }
     else
     {
         // With nothing to select() on, we can't wait indefinitely
         if( msec < 0 )
             msec = 10;
         usleep( msec * 1000 );
     }
 }
Sys_SteamPath()
char* Sys_SteamPath (void)
Definition at line 92 of file sys_unix.c.
 {
     // Disabled since Steam doesn't let you install Quake 3 on Mac/Linux
 #if 0 //#ifdef STEAMPATH_NAME
     char *p;
     if( ( p = getenv( "HOME" ) ) != NULL )
     {
 #ifdef __APPLE__
         char *steamPathEnd = "/Library/Application Support/Steam/SteamApps/common/" STEAMPATH_NAME;
 #else
         char *steamPathEnd = "/.steam/steam/SteamApps/common/" STEAMPATH_NAME;
 #endif
         Com_sprintf(steamPath, sizeof(steamPath), "%s%s", p, steamPathEnd);
     }
 #endif
     return steamPath;
 }
Sys_XmessageCommand()
static void Sys_XmessageCommand (dialogType_t type, const char * message, const char * title) static
Definition at line 726 of file sys_unix.c.
 {
     Sys_ClearExecBuffer( );
     Sys_AppendToExecBuffer( "xmessage" );
     Sys_AppendToExecBuffer( "-buttons" );
     switch( type )
     {
         default:           Sys_AppendToExecBuffer( "OK:0" ); break;
         case DT_YES_NO:    Sys_AppendToExecBuffer( "Yes:0,No:1" ); break;
         case DT_OK_CANCEL: Sys_AppendToExecBuffer( "OK:0,Cancel:1" ); break;
     }
     Sys_AppendToExecBuffer( "-center" );
     Sys_AppendToExecBuffer( message );
 }
Referenced by Sys_Dialog().
Sys_ZenityCommand()
static void Sys_ZenityCommand (dialogType_t type, const char * message, const char * title) static
Definition at line 669 of file sys_unix.c.
 {
     Sys_ClearExecBuffer( );
     Sys_AppendToExecBuffer( "zenity" );
     switch( type )
     {
         default:
         case DT_INFO:      Sys_AppendToExecBuffer( "--info" ); break;
         case DT_WARNING:   Sys_AppendToExecBuffer( "--warning" ); break;
         case DT_ERROR:     Sys_AppendToExecBuffer( "--error" ); break;
         case DT_YES_NO:
             Sys_AppendToExecBuffer( "--question" );
             Sys_AppendToExecBuffer( "--ok-label=Yes" );
             Sys_AppendToExecBuffer( "--cancel-label=No" );
             break;
         case DT_OK_CANCEL:
             Sys_AppendToExecBuffer( "--question" );
             Sys_AppendToExecBuffer( "--ok-label=OK" );
             Sys_AppendToExecBuffer( "--cancel-label=Cancel" );
             break;
     }
     Sys_AppendToExecBuffer( va( "--text=%s", message ) );
     Sys_AppendToExecBuffer( va( "--title=%s", title ) );
 }
Referenced by Sys_Dialog().
Variable Documentation
curtime
int curtime
Definition at line 137 of file sys_unix.c.
Referenced by PC_ExpandBuiltinDefine(), and Sys_Milliseconds().
execArgc
int execArgc static
Definition at line 598 of file sys_unix.c.
Referenced by Sys_AppendToExecBuffer(), and Sys_ClearExecBuffer().
execArgv
char* execArgv[16] static
Definition at line 597 of file sys_unix.c.
Referenced by Sys_AppendToExecBuffer(), Sys_ClearExecBuffer(), and Sys_Exec().
execBuffer
char execBuffer[1024] static
Definition at line 595 of file sys_unix.c.
Referenced by Sys_AppendToExecBuffer(), and Sys_ClearExecBuffer().
execBufferPointer
char* execBufferPointer static
Definition at line 596 of file sys_unix.c.
Referenced by Sys_AppendToExecBuffer(), and Sys_ClearExecBuffer().
gogPath
char gogPath[MAX_OSPATH] = { 0 } static
Definition at line 51 of file sys_unix.c.
Referenced by Sys_GogPath().
homePath
char homePath[MAX_OSPATH] = { 0 } static
Definition at line 45 of file sys_unix.c.
Referenced by FS_HomeRemove(), FS_Startup(), Sys_DefaultHomePath(), and Sys_PIDFileName().
stdinIsATTY
qboolean stdinIsATTY
Definition at line 42 of file sys_unix.c.
Referenced by CON_Init(), Sys_PlatformInit(), and Sys_Sleep().
steamPath
char steamPath[MAX_OSPATH] = { 0 } static
Definition at line 48 of file sys_unix.c.
Referenced by Sys_SteamPath().
sys_timeBase
unsigned long sys_timeBase = 0
Definition at line 131 of file sys_unix.c.
Referenced by Sys_Milliseconds().