ioquake3 doxygen: C:/entry/dev/ioq3/code/client/snd_mem.c File Reference
snd_mem.c File Reference
#include "snd_local.h"
#include "snd_codec.h"
Macros
#define DEF_COMSOUNDMEGS "8"
Functions
void SND_free (sndBuffer *v)
sndBuffer * SND_malloc (void)
void SND_setup (void)
void SND_shutdown (void)
static int ResampleSfx (sfx_t *sfx, int channels, int inrate, int inwidth, int samples, byte *data, qboolean compressed)
static int ResampleSfxRaw (short *sfx, int channels, int inrate, int inwidth, int samples, byte *data)
qboolean S_LoadSound (sfx_t *sfx)
void S_DisplayFreeMemory (void)
Variables
static sndBuffer * buffer = NULL
static sndBuffer * freelist = NULL
static int inUse = 0
static int totalInUse = 0
short * sfxScratchBuffer = NULL
sfx_t * sfxScratchPointer = NULL
int sfxScratchIndex = 0
Macro Definition Documentation
DEF_COMSOUNDMEGS
#define DEF_COMSOUNDMEGS "8"
Definition at line 35 of file snd_mem.c.
Function Documentation
ResampleSfx()
static int ResampleSfx (sfx_t * sfx, int channels, int inrate, int inwidth, int samples, byte * data, qboolean compressed) static
Definition at line 116 of file snd_mem.c.
{
     int     outcount;
     int     srcsample;
     float   stepscale;
     int     i, j;
     int     sample, samplefrac, fracstep;
     int         part;
     sndBuffer   *chunk;
     stepscale = (float)inrate / dma.speed;  // this is usually 0.5, 1, or 2
     outcount = samples / stepscale;
     srcsample = 0;
     samplefrac = 0;
     fracstep = stepscale * 256 * channels;
     chunk = sfx->soundData;
     for (i=0 ; i<outcount ; i++)
     {
         srcsample += samplefrac >> 8;
         samplefrac &= 255;
         samplefrac += fracstep;
         for (j=0 ; j<channels ; j++)
         {
             if( inwidth == 2 ) {
                 sample = ( ((short *)data)[srcsample+j] );
             } else {
                 sample = (unsigned int)( (unsigned char)(data[srcsample+j]) - 128) << 8;
             }
             part = (i*channels+j)&(SND_CHUNK_SIZE-1);
             if (part == 0) {
                 sndBuffer   *newchunk;
                 newchunk = SND_malloc();
                 if (chunk == NULL) {
                     sfx->soundData = newchunk;
                 } else {
                     chunk->next = newchunk;
                 }
                 chunk = newchunk;
             }
             chunk->sndChunk[part] = sample;
         }
     }
     return outcount;
 }
Referenced by S_LoadSound().
ResampleSfxRaw()
static int ResampleSfxRaw (short * sfx, int channels, int inrate, int inwidth, int samples, byte * data) static
Definition at line 172 of file snd_mem.c.
{
     int         outcount;
     int         srcsample;
     float       stepscale;
     int         i, j;
     int         sample, samplefrac, fracstep;
     stepscale = (float)inrate / dma.speed;  // this is usually 0.5, 1, or 2
     outcount = samples / stepscale;
     srcsample = 0;
     samplefrac = 0;
     fracstep = stepscale * 256 * channels;
     for (i=0 ; i<outcount ; i++)
     {
         srcsample += samplefrac >> 8;
         samplefrac &= 255;
         samplefrac += fracstep;
         for (j=0 ; j<channels ; j++)
         {
             if( inwidth == 2 ) {
                 sample = LittleShort ( ((short *)data)[srcsample+j] );
             } else {
                 sample = (int)( (unsigned char)(data[srcsample+j]) - 128) << 8;
             }
             sfx[i*channels+j] = sample;
         }
     }
     return outcount;
 }
Referenced by S_LoadSound().
S_DisplayFreeMemory()
void S_DisplayFreeMemory (void)
Definition at line 276 of file snd_mem.c.
{
     Com_Printf("%d bytes free sound buffer memory, %d total used\n", inUse, totalInUse);
 }
Referenced by S_Base_SoundList().
S_LoadSound()
qboolean S_LoadSound (sfx_t * sfx)
Definition at line 215 of file snd_mem.c.
 {
     byte    *data;
     short   *samples;
     snd_info_t  info;
 //  int     size;
     // load it in
     data = S_CodecLoad(sfx->soundName, &info);
     if(!data)
         return qfalse;
     if ( info.width == 1 ) {
         Com_DPrintf(S_COLOR_YELLOW "WARNING: %s is a 8 bit audio file\n", sfx->soundName);
     }
     if ( info.rate != 22050 ) {
         Com_DPrintf(S_COLOR_YELLOW "WARNING: %s is not a 22kHz audio file\n", sfx->soundName);
     }
     samples = Hunk_AllocateTempMemory(info.channels * info.samples * sizeof(short) * 2);
     sfx->lastTimeUsed = Com_Milliseconds()+1;
     // each of these compression schemes works just fine
     // but the 16bit quality is much nicer and with a local
     // install assured we can rely upon the sound memory
     // manager to do the right thing for us and page
     // sound in as needed
     if( info.channels == 1 && sfx->soundCompressed == qtrue) {
         sfx->soundCompressionMethod = 1;
         sfx->soundData = NULL;
         sfx->soundLength = ResampleSfxRaw( samples, info.channels, info.rate, info.width, info.samples, data + info.dataofs );
         S_AdpcmEncodeSound(sfx, samples);
 #if 0
     } else if (info.channels == 1 && info.samples>(SND_CHUNK_SIZE*16) && info.width >1) {
         sfx->soundCompressionMethod = 3;
         sfx->soundData = NULL;
         sfx->soundLength = ResampleSfxRaw( samples, info.channels, info.rate, info.width, info.samples, (data + info.dataofs) );
         encodeMuLaw( sfx, samples);
     } else if (info.channels == 1 && info.samples>(SND_CHUNK_SIZE*6400) && info.width >1) {
         sfx->soundCompressionMethod = 2;
         sfx->soundData = NULL;
         sfx->soundLength = ResampleSfxRaw( samples, info.channels, info.rate, info.width, info.samples, (data + info.dataofs) );
         encodeWavelet( sfx, samples);
 #endif
     } else {
         sfx->soundCompressionMethod = 0;
         sfx->soundData = NULL;
         sfx->soundLength = ResampleSfx( sfx, info.channels, info.rate, info.width, info.samples, data + info.dataofs, qfalse );
     }
     sfx->soundChannels = info.channels;
     Hunk_FreeTempMemory(samples);
     Hunk_FreeTempMemory(data);
     return qtrue;
 }
Referenced by S_memoryLoad().
SND_free()
void SND_free (sndBuffer * v)
Definition at line 54 of file snd_mem.c.
{
     *(sndBuffer **)v = freelist;
     freelist = (sndBuffer*)v;
     inUse += sizeof(sndBuffer);
 }
Referenced by S_FreeOldestSound().
SND_malloc()
sndBuffer* SND_malloc (void)
Definition at line 60 of file snd_mem.c.
{
     sndBuffer *v;
 redo:
     if (freelist == NULL) {
         S_FreeOldestSound();
         goto redo;
     }
     inUse -= sizeof(sndBuffer);
     totalInUse += sizeof(sndBuffer);
     v = freelist;
     freelist = *(sndBuffer **)freelist;
     v->next = NULL;
     return v;
 }
Referenced by encodeMuLaw(), encodeWavelet(), ResampleSfx(), S_AdpcmEncodeSound(), and S_DefaultSound().
SND_setup()
void SND_setup (void)
Definition at line 77 of file snd_mem.c.
                      {
     sndBuffer *p, *q;
     cvar_t  *cv;
     int scs;
     cv = Cvar_Get( "com_soundMegs", DEF_COMSOUNDMEGS, CVAR_LATCH | CVAR_ARCHIVE );
     scs = (cv->integer*1536);
     buffer = malloc(scs*sizeof(sndBuffer) );
     // allocate the stack based hunk allocator
     sfxScratchBuffer = malloc(SND_CHUNK_SIZE * sizeof(short) * 4);  //Hunk_Alloc(SND_CHUNK_SIZE * sizeof(short) * 4);
     sfxScratchPointer = NULL;
     inUse = scs*sizeof(sndBuffer);
     p = buffer;;
     q = p + scs;
     while (--q > p)
         *(sndBuffer **)q = q-1;
     *(sndBuffer **)q = NULL;
     freelist = p + scs - 1;
     Com_Printf("Sound memory manager started\n");
 }
Referenced by S_Base_BeginRegistration().
SND_shutdown()
void SND_shutdown (void)
Definition at line 103 of file snd_mem.c.
 {
         free(sfxScratchBuffer);
         free(buffer);
 }
Referenced by S_Base_Shutdown().
Variable Documentation
buffer
sndBuffer* buffer = NULL static
Definition at line 45 of file snd_mem.c.
Referenced by SND_setup(), and SND_shutdown().
freelist
sndBuffer* freelist = NULL static
Definition at line 46 of file snd_mem.c.
Referenced by SND_free(), SND_malloc(), and SND_setup().
inUse
int inUse = 0 static
Definition at line 47 of file snd_mem.c.
Referenced by S_DisplayFreeMemory(), SND_free(), SND_malloc(), and SND_setup().
sfxScratchBuffer
short* sfxScratchBuffer = NULL
Definition at line 50 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), S_PaintChannelFromWavelet(), SND_setup(), and SND_shutdown().
sfxScratchIndex
int sfxScratchIndex = 0
Definition at line 52 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), and S_PaintChannelFromWavelet().
sfxScratchPointer
sfx_t* sfxScratchPointer = NULL
Definition at line 51 of file snd_mem.c.
Referenced by S_PaintChannelFromADPCM(), S_PaintChannelFromWavelet(), and SND_setup().
totalInUse
int totalInUse = 0 static
Definition at line 48 of file snd_mem.c.
Referenced by S_DisplayFreeMemory(), and SND_malloc().