ioquake3 doxygen: ea_export_s Struct Reference
ea_export_s Struct Reference
#include <botlib.h>
Public Attributes
void(* EA_Command)(int client, char *command)
void(* EA_Say)(int client, char *str)
void(* EA_SayTeam)(int client, char *str)
void(* EA_Action)(int client, int action)
void(* EA_Gesture)(int client)
void(* EA_Talk)(int client)
void(* EA_Attack)(int client)
void(* EA_Use)(int client)
void(* EA_Respawn)(int client)
void(* EA_MoveUp)(int client)
void(* EA_MoveDown)(int client)
void(* EA_MoveForward)(int client)
void(* EA_MoveBack)(int client)
void(* EA_MoveLeft)(int client)
void(* EA_MoveRight)(int client)
void(* EA_Crouch)(int client)
void(* EA_SelectWeapon)(int client, int weapon)
void(* EA_Jump)(int client)
void(* EA_DelayedJump)(int client)
void(* EA_Move)(int client, vec3_t dir, float speed)
void(* EA_View)(int client, vec3_t viewangles)
void(* EA_EndRegular)(int client, float thinktime)
void(* EA_GetInput)(int client, float thinktime, bot_input_t *input)
void(* EA_ResetInput)(int client)
Detailed Description
Definition at line 268 of file botlib.h.
Member Data Documentation
EA_Action
void(* ea_export_s::EA_Action) (int client, int action)
Definition at line 275 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Attack
void(* ea_export_s::EA_Attack) (int client)
Definition at line 278 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Command
void(* ea_export_s::EA_Command) (int client, char *command)
Definition at line 271 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Crouch
void(* ea_export_s::EA_Crouch) (int client)
Definition at line 287 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_DelayedJump
void(* ea_export_s::EA_DelayedJump) (int client)
Definition at line 291 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_EndRegular
void(* ea_export_s::EA_EndRegular) (int client, float thinktime)
Definition at line 295 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Gesture
void(* ea_export_s::EA_Gesture) (int client)
Definition at line 276 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_GetInput
void(* ea_export_s::EA_GetInput) (int client, float thinktime, bot_input_t *input)
Definition at line 296 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Jump
void(* ea_export_s::EA_Jump) (int client)
Definition at line 290 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Move
void(* ea_export_s::EA_Move) (int client, vec3_t dir, float speed)
Definition at line 292 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_MoveBack
void(* ea_export_s::EA_MoveBack) (int client)
Definition at line 284 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_MoveDown
void(* ea_export_s::EA_MoveDown) (int client)
Definition at line 282 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_MoveForward
void(* ea_export_s::EA_MoveForward) (int client)
Definition at line 283 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_MoveLeft
void(* ea_export_s::EA_MoveLeft) (int client)
Definition at line 285 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_MoveRight
void(* ea_export_s::EA_MoveRight) (int client)
Definition at line 286 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_MoveUp
void(* ea_export_s::EA_MoveUp) (int client)
Definition at line 281 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_ResetInput
void(* ea_export_s::EA_ResetInput) (int client)
Definition at line 297 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Respawn
void(* ea_export_s::EA_Respawn) (int client)
Definition at line 280 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Say
void(* ea_export_s::EA_Say) (int client, char *str)
Definition at line 272 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_SayTeam
void(* ea_export_s::EA_SayTeam) (int client, char *str)
Definition at line 273 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_SelectWeapon
void(* ea_export_s::EA_SelectWeapon) (int client, int weapon)
Definition at line 289 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Talk
void(* ea_export_s::EA_Talk) (int client)
Definition at line 277 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_Use
void(* ea_export_s::EA_Use) (int client)
Definition at line 279 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().
EA_View
void(* ea_export_s::EA_View) (int client, vec3_t viewangles)
Definition at line 293 of file botlib.h.
Referenced by Init_EA_Export(), and SV_GameSystemCalls().