ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/ai_main.h File Reference
ai_main.h File Reference
Classes
struct bot_waypoint_s
struct bot_activategoal_s
struct bot_state_s
Macros
#define CTF
#define MAX_ITEMS 256
#define BFL_STRAFERIGHT 1
#define BFL_ATTACKED 2
#define BFL_ATTACKJUMPED 4
#define BFL_AIMATENEMY 8
#define BFL_AVOIDRIGHT 16
#define BFL_IDEALVIEWSET 32
#define BFL_FIGHTSUICIDAL 64
#define LTG_TEAMHELP 1
#define LTG_TEAMACCOMPANY 2
#define LTG_DEFENDKEYAREA 3
#define LTG_GETFLAG 4
#define LTG_RUSHBASE 5
#define LTG_RETURNFLAG 6
#define LTG_CAMP 7
#define LTG_CAMPORDER 8
#define LTG_PATROL 9
#define LTG_GETITEM 10
#define LTG_KILL 11
#define LTG_HARVEST 12
#define LTG_ATTACKENEMYBASE 13
#define LTG_MAKELOVE_UNDER 14
#define LTG_MAKELOVE_ONTOP 15
#define TEAM_HELP_TIME 60
#define TEAM_ACCOMPANY_TIME 600
#define TEAM_DEFENDKEYAREA_TIME 600
#define TEAM_CAMP_TIME 600
#define TEAM_PATROL_TIME 600
#define TEAM_LEAD_TIME 600
#define TEAM_GETITEM_TIME 60
#define TEAM_KILL_SOMEONE 180
#define TEAM_ATTACKENEMYBASE_TIME 600
#define TEAM_HARVEST_TIME 120
#define CTF_GETFLAG_TIME 600
#define CTF_RUSHBASE_TIME 120
#define CTF_RETURNFLAG_TIME 180
#define CTF_ROAM_TIME 60
#define PATROL_LOOP 1
#define PATROL_REVERSE 2
#define PATROL_BACK 4
#define TEAMTP_DEFENDER 1
#define TEAMTP_ATTACKER 2
#define CTFS_AGRESSIVE 1
#define PRESENCE_NONE 1
#define PRESENCE_NORMAL 2
#define PRESENCE_CROUCH 4
#define MAX_PROXMINES 64
#define MAX_ACTIVATESTACK 8
#define MAX_ACTIVATEAREAS 32
#define FloatTime() floattime
Typedefs
typedef struct bot_waypoint_s bot_waypoint_t
typedef struct bot_activategoal_s bot_activategoal_t
typedef struct bot_state_s bot_state_t
Functions
void BotResetState (bot_state_t *bs)
int NumBots (void)
void BotEntityInfo (int entnum, aas_entityinfo_t *info)
void QDECL BotAI_Print (int type, char *fmt,...) __attribute__((format(printf
void QDECL void QDECL QDECL BotAI_BotInitialChat (bot_state_t *bs, char *type,...)
void BotAI_Trace (bsp_trace_t *bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
int BotAI_GetClientState (int clientNum, playerState_t *state)
int BotAI_GetEntityState (int entityNum, entityState_t *state)
int BotAI_GetSnapshotEntity (int clientNum, int sequence, entityState_t *state)
int BotTeamLeader (bot_state_t *bs)
Variables
float floattime
Macro Definition Documentation
BFL_AIMATENEMY
#define BFL_AIMATENEMY 8
Definition at line 41 of file ai_main.h.
BFL_ATTACKED
#define BFL_ATTACKED 2
Definition at line 39 of file ai_main.h.
BFL_ATTACKJUMPED
#define BFL_ATTACKJUMPED 4
Definition at line 40 of file ai_main.h.
BFL_AVOIDRIGHT
#define BFL_AVOIDRIGHT 16
Definition at line 42 of file ai_main.h.
BFL_FIGHTSUICIDAL
#define BFL_FIGHTSUICIDAL 64
Definition at line 44 of file ai_main.h.
BFL_IDEALVIEWSET
#define BFL_IDEALVIEWSET 32
Definition at line 43 of file ai_main.h.
BFL_STRAFERIGHT
#define BFL_STRAFERIGHT 1
Definition at line 38 of file ai_main.h.
CTF
#define CTF
Definition at line 34 of file ai_main.h.
CTF_GETFLAG_TIME
#define CTF_GETFLAG_TIME 600
Definition at line 72 of file ai_main.h.
CTF_RETURNFLAG_TIME
#define CTF_RETURNFLAG_TIME 180
Definition at line 74 of file ai_main.h.
CTF_ROAM_TIME
#define CTF_ROAM_TIME 60
Definition at line 75 of file ai_main.h.
CTF_RUSHBASE_TIME
#define CTF_RUSHBASE_TIME 120
Definition at line 73 of file ai_main.h.
CTFS_AGRESSIVE
#define CTFS_AGRESSIVE 1
Definition at line 84 of file ai_main.h.
FloatTime
#define FloatTime () floattime
Definition at line 284 of file ai_main.h.
LTG_ATTACKENEMYBASE
#define LTG_ATTACKENEMYBASE 13
Definition at line 58 of file ai_main.h.
LTG_CAMP
#define LTG_CAMP 7
Definition at line 52 of file ai_main.h.
LTG_CAMPORDER
#define LTG_CAMPORDER 8
Definition at line 53 of file ai_main.h.
LTG_DEFENDKEYAREA
#define LTG_DEFENDKEYAREA 3
Definition at line 48 of file ai_main.h.
LTG_GETFLAG
#define LTG_GETFLAG 4
Definition at line 49 of file ai_main.h.
LTG_GETITEM
#define LTG_GETITEM 10
Definition at line 55 of file ai_main.h.
LTG_HARVEST
#define LTG_HARVEST 12
Definition at line 57 of file ai_main.h.
LTG_KILL
#define LTG_KILL 11
Definition at line 56 of file ai_main.h.
LTG_MAKELOVE_ONTOP
#define LTG_MAKELOVE_ONTOP 15
Definition at line 60 of file ai_main.h.
LTG_MAKELOVE_UNDER
#define LTG_MAKELOVE_UNDER 14
Definition at line 59 of file ai_main.h.
LTG_PATROL
#define LTG_PATROL 9
Definition at line 54 of file ai_main.h.
LTG_RETURNFLAG
#define LTG_RETURNFLAG 6
Definition at line 51 of file ai_main.h.
LTG_RUSHBASE
#define LTG_RUSHBASE 5
Definition at line 50 of file ai_main.h.
LTG_TEAMACCOMPANY
#define LTG_TEAMACCOMPANY 2
Definition at line 47 of file ai_main.h.
LTG_TEAMHELP
#define LTG_TEAMHELP 1
Definition at line 46 of file ai_main.h.
MAX_ACTIVATEAREAS
#define MAX_ACTIVATEAREAS 32
Definition at line 102 of file ai_main.h.
MAX_ACTIVATESTACK
#define MAX_ACTIVATESTACK 8
Definition at line 101 of file ai_main.h.
MAX_ITEMS
#define MAX_ITEMS 256
Definition at line 36 of file ai_main.h.
MAX_PROXMINES
#define MAX_PROXMINES 64
Definition at line 90 of file ai_main.h.
PATROL_BACK
#define PATROL_BACK 4
Definition at line 79 of file ai_main.h.
PATROL_LOOP
#define PATROL_LOOP 1
Definition at line 77 of file ai_main.h.
PATROL_REVERSE
#define PATROL_REVERSE 2
Definition at line 78 of file ai_main.h.
PRESENCE_CROUCH
#define PRESENCE_CROUCH 4
Definition at line 88 of file ai_main.h.
PRESENCE_NONE
#define PRESENCE_NONE 1
Definition at line 86 of file ai_main.h.
PRESENCE_NORMAL
#define PRESENCE_NORMAL 2
Definition at line 87 of file ai_main.h.
TEAM_ACCOMPANY_TIME
#define TEAM_ACCOMPANY_TIME 600
Definition at line 63 of file ai_main.h.
TEAM_ATTACKENEMYBASE_TIME
#define TEAM_ATTACKENEMYBASE_TIME 600
Definition at line 70 of file ai_main.h.
TEAM_CAMP_TIME
#define TEAM_CAMP_TIME 600
Definition at line 65 of file ai_main.h.
TEAM_DEFENDKEYAREA_TIME
#define TEAM_DEFENDKEYAREA_TIME 600
Definition at line 64 of file ai_main.h.
TEAM_GETITEM_TIME
#define TEAM_GETITEM_TIME 60
Definition at line 68 of file ai_main.h.
TEAM_HARVEST_TIME
#define TEAM_HARVEST_TIME 120
Definition at line 71 of file ai_main.h.
TEAM_HELP_TIME
#define TEAM_HELP_TIME 60
Definition at line 62 of file ai_main.h.
TEAM_KILL_SOMEONE
#define TEAM_KILL_SOMEONE 180
Definition at line 69 of file ai_main.h.
TEAM_LEAD_TIME
#define TEAM_LEAD_TIME 600
Definition at line 67 of file ai_main.h.
TEAM_PATROL_TIME
#define TEAM_PATROL_TIME 600
Definition at line 66 of file ai_main.h.
TEAMTP_ATTACKER
#define TEAMTP_ATTACKER 2
Definition at line 82 of file ai_main.h.
TEAMTP_DEFENDER
#define TEAMTP_DEFENDER 1
Definition at line 81 of file ai_main.h.
Typedef Documentation
bot_activategoal_t
typedef struct bot_activategoal_s bot_activategoal_t
bot_state_t
typedef struct bot_state_s bot_state_t
bot_waypoint_t
typedef struct bot_waypoint_s bot_waypoint_t
Function Documentation
BotAI_BotInitialChat()
void QDECL void QDECL QDECL BotAI_BotInitialChat (bot_state_t * bs, char * type, ...)
Definition at line 217 of file ai_main.c.
{
     int     i, mcontext;
     va_list ap;
     char    *p;
     char    *vars[MAX_MATCHVARIABLES];
     memset(vars, 0, sizeof(vars));
     va_start(ap, type);
     p = va_arg(ap, char *);
     for (i = 0; i < MAX_MATCHVARIABLES; i++) {
         if( !p ) {
             break;
         }
         vars[i] = p;
         p = va_arg(ap, char *);
     }
     va_end(ap);
     mcontext = BotSynonymContext(bs);
     trap_BotInitialChat( bs->cs, type, mcontext, vars[0], vars[1], vars[2], vars[3], vars[4], vars[5], vars[6], vars[7] );
 }
Referenced by BotChat_Death(), BotChat_EndLevel(), BotChat_EnemySuicide(), BotChat_EnterGame(), BotChat_ExitGame(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_HitTalking(), BotChat_Kill(), BotChat_Random(), BotChat_StartLevel(), BotChatTest(), BotCreateGroup(), BotCTFOrders_BothFlagsAtBase(), BotCTFOrders_BothFlagsNotAtBase(), BotCTFOrders_EnemyFlagNotAtBase(), BotCTFOrders_FlagNotAtBase(), BotGetLongTermGoal(), BotLongTermGoal(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_Dismiss(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_TaskPreference(), BotMatch_WhatAreYouDoing(), BotMatch_WhereAreYou(), BotMatch_WhichTeam(), BotTeamAI(), BotVoiceChat_Camp(), BotVoiceChat_FollowMe(), BotVoiceChat_Patrol(), BotVoiceChat_WantOnDefense(), BotVoiceChat_WantOnOffense(), and BotVoiceChat_WhoIsLeader().
BotAI_GetClientState()
int BotAI_GetClientState (int clientNum, playerState_t * state)
Definition at line 161 of file ai_main.c.
{
     gentity_t   *ent;
     ent = &g_entities[clientNum];
     if ( !ent->inuse ) {
         return qfalse;
     }
     if ( !ent->client ) {
         return qfalse;
     }
     memcpy( state, &ent->client->ps, sizeof(playerState_t) );
     return qtrue;
 }
Referenced by BotAI(), BotClientTravelTimeToGoal(), BotFirstClientInRankings(), BotIsFirstInRankings(), BotIsLastInRankings(), BotLastClientInRankings(), and EntityIsDead().
BotAI_GetEntityState()
int BotAI_GetEntityState (int entityNum, entityState_t * state)
Definition at line 181 of file ai_main.c.
{
     gentity_t   *ent;
     ent = &g_entities[entityNum];
     memset( state, 0, sizeof(entityState_t) );
     if (!ent->inuse) return qfalse;
     if (!ent->r.linked) return qfalse;
     if (ent->r.svFlags & SVF_NOCLIENT) return qfalse;
     memcpy( state, &ent->s, sizeof(entityState_t) );
     return qtrue;
 }
Referenced by BotAI_GetSnapshotEntity(), BotCheckSnapshot(), and BotClearPath().
BotAI_GetSnapshotEntity()
int BotAI_GetSnapshotEntity (int clientNum, int sequence, entityState_t * state)
Definition at line 198 of file ai_main.c.
{
     int     entNum;
     entNum = trap_BotGetSnapshotEntity( clientNum, sequence );
     if ( entNum == -1 ) {
         memset(state, 0, sizeof(entityState_t));
         return -1;
     }
     BotAI_GetEntityState( entNum, state );
     return sequence + 1;
 }
Referenced by BotCheckSnapshot().
BotAI_Print()
void QDECL BotAI_Print (int type, char * fmt, ...)
BotAI_Trace()
void BotAI_Trace (bsp_trace_t * bsptrace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
Definition at line 135 of file ai_main.c.
{
     trace_t trace;
     trap_Trace(&trace, start, mins, maxs, end, passent, contentmask);
     //copy the trace information
     bsptrace->allsolid = trace.allsolid;
     bsptrace->startsolid = trace.startsolid;
     bsptrace->fraction = trace.fraction;
     VectorCopy(trace.endpos, bsptrace->endpos);
     bsptrace->plane.dist = trace.plane.dist;
     VectorCopy(trace.plane.normal, bsptrace->plane.normal);
     bsptrace->plane.signbits = trace.plane.signbits;
     bsptrace->plane.type = trace.plane.type;
     bsptrace->surface.value = 0;
     bsptrace->surface.flags = trace.surfaceFlags;
     bsptrace->ent = trace.entityNum;
     bsptrace->exp_dist = 0;
     bsptrace->sidenum = 0;
     bsptrace->contents = 0;
 }
Referenced by AINode_Seek_ActivateEntity(), BotAimAtEnemy(), BotCheckAttack(), BotClearPath(), BotEntityVisible(), BotFindEnemy(), BotFuncButtonActivateGoal(), BotGetAirGoal(), BotNearestVisibleItem(), BotRoamGoal(), and BotValidChatPosition().
BotEntityInfo()
void BotEntityInfo (int entnum, aas_entityinfo_t * info)
Definition at line 683 of file ai_main.c.
{
     trap_AAS_EntityInfo(entnum, info);
 }
Referenced by AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), BotAIBlocked(), BotAimAtEnemy(), BotAttackMove(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotCheckAttack(), BotCheckEvents(), BotCTFSeekGoals(), BotEnemyFlagCarrierVisible(), BotEntityVisible(), BotFindEnemy(), BotGetActivateGoal(), BotGetLongTermGoal(), BotGoForActivateGoal(), BotLongTermGoal(), BotMapScripts(), BotMatch_Camp(), BotMatch_HelpAccompany(), BotMatch_LeadTheWay(), BotSetTeamStatus(), BotTeamFlagCarrier(), BotTeamFlagCarrierVisible(), BotUpdateBattleInventory(), BotVisibleEnemies(), BotVisibleTeamMatesAndEnemies(), BotVoiceChat_Camp(), BotVoiceChat_FollowMe(), BotWantsToChase(), and BotWantsToRetreat().
BotResetState()
void BotResetState (bot_state_t * bs)
Definition at line 1321 of file ai_main.c.
{
     int client, entitynum, inuse;
     int movestate, goalstate, chatstate, weaponstate;
     bot_settings_t settings;
     int character;
     playerState_t ps;                           //current player state
     float entergame_time;
     //save some things that should not be reset here
     memcpy(&settings, &bs->settings, sizeof(bot_settings_t));
     memcpy(&ps, &bs->cur_ps, sizeof(playerState_t));
     inuse = bs->inuse;
     client = bs->client;
     entitynum = bs->entitynum;
     character = bs->character;
     movestate = bs->ms;
     goalstate = bs->gs;
     chatstate = bs->cs;
     weaponstate = bs->ws;
     entergame_time = bs->entergame_time;
     //free checkpoints and patrol points
     BotFreeWaypoints(bs->checkpoints);
     BotFreeWaypoints(bs->patrolpoints);
     //reset the whole state
     memset(bs, 0, sizeof(bot_state_t));
     //copy back some state stuff that should not be reset
     bs->ms = movestate;
     bs->gs = goalstate;
     bs->cs = chatstate;
     bs->ws = weaponstate;
     memcpy(&bs->cur_ps, &ps, sizeof(playerState_t));
     memcpy(&bs->settings, &settings, sizeof(bot_settings_t));
     bs->inuse = inuse;
     bs->client = client;
     bs->entitynum = entitynum;
     bs->character = character;
     bs->entergame_time = entergame_time;
     //reset several states
     if (bs->ms) trap_BotResetMoveState(bs->ms);
     if (bs->gs) trap_BotResetGoalState(bs->gs);
     if (bs->ws) trap_BotResetWeaponState(bs->ws);
     if (bs->gs) trap_BotResetAvoidGoals(bs->gs);
     if (bs->ms) trap_BotResetAvoidReach(bs->ms);
 }
Referenced by AIEnter_Intermission(), AIEnter_Observer(), and BotAILoadMap().
BotTeamLeader()
int BotTeamLeader (bot_state_t * bs)
Definition at line 701 of file ai_main.c.
{
     int leader;
     leader = ClientFromName(bs->teamleader);
     if (leader < 0) return qfalse;
     if (!botstates[leader] || !botstates[leader]->inuse) return qfalse;
     return qtrue;
 }
Referenced by BotCheckItemPickup(), and BotCTFSeekGoals().
NumBots()
int NumBots (void)
Definition at line 692 of file ai_main.c.
                   {
     return numbots;
 }
Referenced by BotCheckConsoleMessages().
Variable Documentation
floattime
float floattime
Definition at line 64 of file ai_main.c.
Referenced by BotAIStartFrame().