ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_gameinfo.c File Reference
ui_gameinfo.c File Reference
#include "ui_local.h"
Macros
#define POOLSIZE 128 * 1024
Functions
void * UI_Alloc (int size)
void UI_InitMemory (void)
int UI_ParseInfos (char *buf, int max, char *infos[])
static void UI_LoadArenasFromFile (char *filename)
static void UI_LoadArenas (void)
const char * UI_GetArenaInfoByNumber (int num)
const char * UI_GetArenaInfoByMap (const char *map)
const char * UI_GetSpecialArenaInfo (const char *tag)
static void UI_LoadBotsFromFile (char *filename)
static void UI_LoadBots (void)
char * UI_GetBotInfoByNumber (int num)
char * UI_GetBotInfoByName (const char *name)
void UI_GetBestScore (int level, int *score, int *skill)
void UI_SetBestScore (int level, int score)
void UI_LogAwardData (int award, int data)
int UI_GetAwardLevel (int award)
int UI_TierCompleted (int levelWon)
qboolean UI_ShowTierVideo (int tier)
qboolean UI_CanShowTierVideo (int tier)
int UI_GetCurrentGame (void)
void UI_NewGame (void)
int UI_GetNumArenas (void)
int UI_GetNumSPArenas (void)
int UI_GetNumSPTiers (void)
int UI_GetNumBots (void)
void UI_SPUnlock_f (void)
void UI_SPUnlockMedals_f (void)
void UI_InitGameinfo (void)
Variables
int ui_numBots
static char * ui_botInfos [MAX_BOTS]
static int ui_numArenas
static char * ui_arenaInfos [MAX_ARENAS]
static int ui_numSinglePlayerArenas
static int ui_numSpecialSinglePlayerArenas
static char memoryPool [POOLSIZE]
static int allocPoint
static int outOfMemory
Macro Definition Documentation
POOLSIZE
#define POOLSIZE 128 * 1024
Definition at line 34 of file ui_gameinfo.c.
Function Documentation
UI_Alloc()
void* UI_Alloc (int size)
Definition at line 54 of file ui_gameinfo.c.
{
     char    *p;
     if ( allocPoint + size > POOLSIZE ) {
         outOfMemory = qtrue;
         return NULL;
     }
     p = &memoryPool[allocPoint];
     allocPoint += ( size + 31 ) & ~31;
     return p;
 }
Referenced by UI_ParseInfos().
UI_CanShowTierVideo()
qboolean UI_CanShowTierVideo (int tier)
Definition at line 630 of file ui_gameinfo.c.
{
     char    key[16];
     char    videos[MAX_INFO_VALUE];
     if( !tier ) {
         return qfalse;
     }
     if( uis.demoversion && tier != 8 ) {
         return qfalse;
     }
     trap_Cvar_VariableStringBuffer( "g_spVideos", videos, sizeof(videos) );
     Com_sprintf( key, sizeof(key), "tier%i", tier );
     if( atoi( Info_ValueForKey( videos, key ) ) ) {
         return qtrue;
     }
     return qfalse;
 }
References Com_sprintf(), uiStatic_t::demoversion, Info_ValueForKey(), MAX_INFO_VALUE, qfalse, qtrue, trap_Cvar_VariableStringBuffer(), and uis.
Referenced by UI_CinematicsMenu_Init().
UI_GetArenaInfoByMap()
const char* UI_GetArenaInfoByMap (const char * map)
Definition at line 294 of file ui_gameinfo.c.
{
     int         n;
     for( n = 0; n < ui_numArenas; n++ ) {
         if( Q_stricmp( Info_ValueForKey( ui_arenaInfos[n], "map" ), map ) == 0 ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
References Info_ValueForKey(), NULL, Q_stricmp(), ui_arenaInfos, and ui_numArenas.
Referenced by ServerOptions_InitBotNames(), and UI_SPPostgameMenu_f().
UI_GetArenaInfoByNumber()
const char* UI_GetArenaInfoByNumber (int num)
Definition at line 269 of file ui_gameinfo.c.
{
     int     n;
     char    *value;
     if( num < 0 || num >= ui_numArenas ) {
         trap_Print( va( S_COLOR_RED "Invalid arena number: %i\n", num ) );
         return NULL;
     }
     for( n = 0; n < ui_numArenas; n++ ) {
         value = Info_ValueForKey( ui_arenaInfos[n], "num" );
         if( *value && atoi(value) == num ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
References Info_ValueForKey(), NULL, S_COLOR_RED, trap_Print(), ui_arenaInfos, ui_numArenas, and va().
Referenced by ServerOptions_SetMenuItems(), ServerOptions_Start(), StartServer_Cache(), StartServer_GametypeEvent(), StartServer_LevelshotDraw(), StartServer_Update(), UI_SPLevelMenu_LevelEvent(), UI_SPLevelMenu_SetMenuItems(), and UI_SPPostgameMenu_NextEvent().
UI_GetAwardLevel()
int UI_GetAwardLevel (int award)
Definition at line 549 of file ui_gameinfo.c.
{
     char    key[16];
     char    awardData[MAX_INFO_VALUE];
     trap_Cvar_VariableStringBuffer( "g_spAwards", awardData, sizeof(awardData) );
     Com_sprintf( key, sizeof(key), "a%i", award );
     return atoi( Info_ValueForKey( awardData, key ) );
 }
References Com_sprintf(), Info_ValueForKey(), MAX_INFO_VALUE, and trap_Cvar_VariableStringBuffer().
Referenced by UI_SPLevelMenu_Init(), and UI_SPPostgameMenu_f().
UI_GetBestScore()
void UI_GetBestScore (int level, int * score, int * skill)
Definition at line 435 of file ui_gameinfo.c.
{
     int     n;
     int     skillScore;
     int     bestScore;
     int     bestScoreSkill;
     char    arenaKey[16];
     char    scores[MAX_INFO_VALUE];
     if( !score || !skill ) {
         return;
     }
     if( level < 0 || level > ui_numArenas ) {
         return;
     }
     bestScore = 0;
     bestScoreSkill = 0;
     for( n = 1; n <= 5; n++ ) {
         trap_Cvar_VariableStringBuffer( va( "g_spScores%i", n ), scores, MAX_INFO_VALUE );
         Com_sprintf( arenaKey, sizeof( arenaKey ), "l%i", level );
         skillScore = atoi( Info_ValueForKey( scores, arenaKey ) );
         if( skillScore < 1 || skillScore > 8 ) {
             continue;
         }
         if( !bestScore || skillScore <= bestScore ) {
             bestScore = skillScore;
             bestScoreSkill = n;
         }
     }
     *score = bestScore;
     *skill = bestScoreSkill;
 }
References Com_sprintf(), Info_ValueForKey(), level, MAX_INFO_VALUE, trap_Cvar_VariableStringBuffer(), ui_numArenas, and va().
Referenced by UI_GetCurrentGame(), UI_SPLevelMenu_SetMenuArena(), and UI_TierCompleted().
UI_GetBotInfoByName()
char* UI_GetBotInfoByName (const char * name)
Definition at line 409 of file ui_gameinfo.c.
{
     int     n;
     char    *value;
     for ( n = 0; n < ui_numBots ; n++ ) {
         value = Info_ValueForKey( ui_botInfos[n], "name" );
         if ( !Q_stricmp( value, name ) ) {
             return ui_botInfos[n];
         }
     }
     return NULL;
 }
Referenced by ServerOptions_InitBotNames(), and UI_SPLevelMenu_SetBots().
UI_GetBotInfoByNumber()
char* UI_GetBotInfoByNumber (int num)
Definition at line 395 of file ui_gameinfo.c.
{
     if( num < 0 || num >= ui_numBots ) {
         trap_Print( va( S_COLOR_RED "Invalid bot number: %i\n", num ) );
         return NULL;
     }
     return ui_botInfos[num];
 }
Referenced by ServerOptions_InitBotNames(), UI_AddBotsMenu_SetBotNames(), UI_AddBotsMenu_SortCompare(), UI_BotSelectMenu_Default(), UI_BotSelectMenu_SortCompare(), UI_BotSelectMenu_UpdateGrid(), UI_GetBotNameByNumber(), and UI_SPLevelMenu_SetBots().
UI_GetCurrentGame()
int UI_GetCurrentGame (void)
Definition at line 660 of file ui_gameinfo.c.
{
     int     level;
     int     rank = 0;
     int     skill;
     const char *info;
     info = UI_GetSpecialArenaInfo( "training" );
     if( info ) {
         level = atoi( Info_ValueForKey( info, "num" ) );
         UI_GetBestScore( level, &rank, &skill );
         if ( !rank || rank > 1 ) {
             return level;
         }
     }
     for( level = 0; level < ui_numSinglePlayerArenas; level++ ) {
         UI_GetBestScore( level, &rank, &skill );
         if ( !rank || rank > 1 ) {
             return level;
         }
     }
     info = UI_GetSpecialArenaInfo( "final" );
     if( !info ) {
         return -1;
     }
     return atoi( Info_ValueForKey( info, "num" ) );
 }
References Info_ValueForKey(), level, UI_GetBestScore(), UI_GetSpecialArenaInfo(), and ui_numSinglePlayerArenas.
Referenced by UI_SPLevelMenu(), and UI_SPPostgameMenu_NextEvent().
UI_GetNumArenas()
int UI_GetNumArenas (void)
Definition at line 713 of file ui_gameinfo.c.
{
     return ui_numArenas;
 }
References ui_numArenas.
Referenced by StartServer_Cache(), and StartServer_GametypeEvent().
UI_GetNumBots()
int UI_GetNumBots (void)
Definition at line 743 of file ui_gameinfo.c.
{
     return ui_numBots;
 }
Referenced by UI_AddBotsMenu_Init(), UI_BotName_HandleKey(), UI_BotSelectMenu_BuildList(), UI_DrawTeamMember(), and UI_TeamMember_HandleKey().
UI_GetNumSPArenas()
int UI_GetNumSPArenas (void)
Definition at line 723 of file ui_gameinfo.c.
{
     return ui_numSinglePlayerArenas;
 }
References ui_numSinglePlayerArenas.
Referenced by UI_SPLevelMenu().
UI_GetNumSPTiers()
int UI_GetNumSPTiers (void)
Definition at line 733 of file ui_gameinfo.c.
{
     return ui_numSinglePlayerArenas / ARENAS_PER_TIER;
 }
References ARENAS_PER_TIER, and ui_numSinglePlayerArenas.
Referenced by UI_SPArena_Start(), UI_SPLevelMenu(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_NextEvent(), and UI_TierCompleted().
UI_GetSpecialArenaInfo()
const char* UI_GetSpecialArenaInfo (const char * tag)
Definition at line 312 of file ui_gameinfo.c.
{
     int         n;
     for( n = 0; n < ui_numArenas; n++ ) {
         if( Q_stricmp( Info_ValueForKey( ui_arenaInfos[n], "special" ), tag ) == 0 ) {
             return ui_arenaInfos[n];
         }
     }
     return NULL;
 }
References Info_ValueForKey(), NULL, Q_stricmp(), ui_arenaInfos, and ui_numArenas.
Referenced by UI_GetCurrentGame(), UI_SPLevelMenu(), UI_SPLevelMenu_ResetAction(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_f(), and UI_TierCompleted().
UI_InitGameinfo()
void UI_InitGameinfo (void)
Definition at line 808 of file ui_gameinfo.c.
{
     UI_InitMemory();
     UI_LoadArenas();
     UI_LoadBots();
     uis.demoversion = qfalse;
 }
References uiStatic_t::demoversion, qfalse, UI_InitMemory(), UI_LoadArenas(), UI_LoadBots(), and uis.
Referenced by UI_Init().
UI_InitMemory()
void UI_InitMemory (void)
Definition at line 74 of file ui_gameinfo.c.
{
     allocPoint = 0;
     outOfMemory = qfalse;
 }
Referenced by _UI_Init(), and UI_InitGameinfo().
UI_LoadArenas()
static void UI_LoadArenas (void) static
Definition at line 168 of file ui_gameinfo.c.
{
     int         numdirs;
     vmCvar_t    arenasFile;
     char        filename[128];
     char        dirlist[4096];
     char*       dirptr;
     int         i, n;
     int         dirlen;
     char        *type;
     char        *tag;
     int         singlePlayerNum, specialNum, otherNum;
     ui_numArenas = 0;
     trap_Cvar_Register( &arenasFile, "g_arenasFile", "", CVAR_INIT|CVAR_ROM );
     if( *arenasFile.string ) {
         UI_LoadArenasFromFile(arenasFile.string);
     }
     else {
         UI_LoadArenasFromFile("scripts/arenas.txt");
     }
     // get all arenas from .arena files
     numdirs = trap_FS_GetFileList("scripts", ".arena", dirlist, 4096 );
     dirptr  = dirlist;
     for (i = 0; i < numdirs; i++, dirptr += dirlen+1) {
         dirlen = strlen(dirptr);
         strcpy(filename, "scripts/");
         strcat(filename, dirptr);
         UI_LoadArenasFromFile(filename);
     }
     trap_Print( va( "%i arenas parsed\n", ui_numArenas ) );
     if (outOfMemory) trap_Print(S_COLOR_YELLOW"WARNING: not enough memory in pool to load all arenas\n");
     // set initial numbers
     for( n = 0; n < ui_numArenas; n++ ) {
         Info_SetValueForKey( ui_arenaInfos[n], "num", va( "%i", n ) );
     }
     // go through and count single players levels
     ui_numSinglePlayerArenas = 0;
     ui_numSpecialSinglePlayerArenas = 0;
     for( n = 0; n < ui_numArenas; n++ ) {
         // determine type
         type = Info_ValueForKey( ui_arenaInfos[n], "type" );
         // if no type specified, it will be treated as "ffa"
         if( !*type ) {
             continue;
         }
         if( strstr( type, "single" ) ) {
             // check for special single player arenas (training, final)
             tag = Info_ValueForKey( ui_arenaInfos[n], "special" );
             if( *tag ) {
                 ui_numSpecialSinglePlayerArenas++;
                 continue;
             }
             ui_numSinglePlayerArenas++;
         }
     }
     n = ui_numSinglePlayerArenas % ARENAS_PER_TIER;
     if( n != 0 ) {
         ui_numSinglePlayerArenas -= n;
         trap_Print( va( "%i arenas ignored to make count divisible by %i\n", n, ARENAS_PER_TIER ) );
     }
     // go through once more and assign number to the levels
     singlePlayerNum = 0;
     specialNum = singlePlayerNum + ui_numSinglePlayerArenas;
     otherNum = specialNum + ui_numSpecialSinglePlayerArenas;
     for( n = 0; n < ui_numArenas; n++ ) {
         // determine type
         type = Info_ValueForKey( ui_arenaInfos[n], "type" );
         // if no type specified, it will be treated as "ffa"
         if( *type ) {
             if( strstr( type, "single" ) ) {
                 // check for special single player arenas (training, final)
                 tag = Info_ValueForKey( ui_arenaInfos[n], "special" );
                 if( *tag ) {
                     Info_SetValueForKey( ui_arenaInfos[n], "num", va( "%i", specialNum++ ) );
                     continue;
                 }
                 Info_SetValueForKey( ui_arenaInfos[n], "num", va( "%i", singlePlayerNum++ ) );
                 continue;
             }
         }
         Info_SetValueForKey( ui_arenaInfos[n], "num", va( "%i", otherNum++ ) );
     }
 }
References ARENAS_PER_TIER, CVAR_INIT, CVAR_ROM, Info_SetValueForKey(), Info_ValueForKey(), outOfMemory, S_COLOR_YELLOW, vmCvar_t::string, trap_Cvar_Register(), trap_FS_GetFileList(), trap_Print(), ui_arenaInfos, UI_LoadArenasFromFile(), ui_numArenas, ui_numSinglePlayerArenas, ui_numSpecialSinglePlayerArenas, and va().
Referenced by _UI_Init(), UI_InitGameinfo(), and UI_Load().
UI_LoadArenasFromFile()
static void UI_LoadArenasFromFile (char * filename) static
Definition at line 140 of file ui_gameinfo.c.
{
     int             len;
     fileHandle_t    f;
     char            buf[MAX_ARENAS_TEXT];
     len = trap_FS_FOpenFile( filename, &f, FS_READ );
     if ( !f ) {
         trap_Print( va( S_COLOR_RED "file not found: %s\n", filename ) );
         return;
     }
     if ( len >= MAX_ARENAS_TEXT ) {
         trap_Print( va( S_COLOR_RED "file too large: %s is %i, max allowed is %i\n", filename, len, MAX_ARENAS_TEXT ) );
         trap_FS_FCloseFile( f );
         return;
     }
     trap_FS_Read( buf, len, f );
     buf[len] = 0;
     trap_FS_FCloseFile( f );
     ui_numArenas += UI_ParseInfos( buf, MAX_ARENAS - ui_numArenas, &ui_arenaInfos[ui_numArenas] );
 }
References FS_READ, MAX_ARENAS, MAX_ARENAS_TEXT, S_COLOR_RED, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), ui_arenaInfos, ui_numArenas, UI_ParseInfos(), and va().
Referenced by UI_LoadArenas().
UI_LoadBots()
static void UI_LoadBots (void) static
Definition at line 358 of file ui_gameinfo.c.
{
     vmCvar_t    botsFile;
     int         numdirs;
     char        filename[128];
     char        dirlist[1024];
     char*       dirptr;
     int         i;
     int         dirlen;
     ui_numBots = 0;
     trap_Cvar_Register( &botsFile, "g_botsFile", "", CVAR_INIT|CVAR_ROM );
     if( *botsFile.string ) {
         UI_LoadBotsFromFile(botsFile.string);
     }
     else {
         UI_LoadBotsFromFile("scripts/bots.txt");
     }
     // get all bots from .bot files
     numdirs = trap_FS_GetFileList("scripts", ".bot", dirlist, 1024 );
     dirptr  = dirlist;
     for (i = 0; i < numdirs; i++, dirptr += dirlen+1) {
         dirlen = strlen(dirptr);
         strcpy(filename, "scripts/");
         strcat(filename, dirptr);
         UI_LoadBotsFromFile(filename);
     }
     trap_Print( va( "%i bots parsed\n", ui_numBots ) );
 }
References CVAR_INIT, CVAR_ROM, vmCvar_t::string, trap_Cvar_Register(), trap_FS_GetFileList(), trap_Print(), UI_LoadBotsFromFile(), ui_numBots, and va().
Referenced by _UI_Init(), and UI_InitGameinfo().
UI_LoadBotsFromFile()
static void UI_LoadBotsFromFile (char * filename) static
Definition at line 329 of file ui_gameinfo.c.
{
     int             len;
     fileHandle_t    f;
     char            buf[MAX_BOTS_TEXT];
     len = trap_FS_FOpenFile( filename, &f, FS_READ );
     if ( !f ) {
         trap_Print( va( S_COLOR_RED "file not found: %s\n", filename ) );
         return;
     }
     if ( len >= MAX_BOTS_TEXT ) {
         trap_Print( va( S_COLOR_RED "file too large: %s is %i, max allowed is %i\n", filename, len, MAX_BOTS_TEXT ) );
         trap_FS_FCloseFile( f );
         return;
     }
     trap_FS_Read( buf, len, f );
     buf[len] = 0;
     trap_FS_FCloseFile( f );
     ui_numBots += UI_ParseInfos( buf, MAX_BOTS - ui_numBots, &ui_botInfos[ui_numBots] );
     if (outOfMemory) trap_Print(S_COLOR_YELLOW"WARNING: not enough memory in pool to load all bots\n");
 }
References FS_READ, MAX_BOTS, MAX_BOTS_TEXT, outOfMemory, S_COLOR_RED, S_COLOR_YELLOW, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), ui_botInfos, ui_numBots, UI_ParseInfos(), and va().
Referenced by UI_LoadBots().
UI_LogAwardData()
void UI_LogAwardData (int award, int data)
Definition at line 520 of file ui_gameinfo.c.
{
     char    key[16];
     char    awardData[MAX_INFO_VALUE];
     int     oldValue;
     if( data == 0 ) {
         return;
     }
     if( award > AWARD_PERFECT ) {
         trap_Print( va( S_COLOR_RED "Bad award %i in UI_LogAwardData\n", award ) );
         return;
     }
     trap_Cvar_VariableStringBuffer( "g_spAwards", awardData, sizeof(awardData) );
     Com_sprintf( key, sizeof(key), "a%i", award );
     oldValue = atoi( Info_ValueForKey( awardData, key ) );
     Info_SetValueForKey( awardData, key, va( "%i", oldValue + data ) );
     trap_Cvar_Set( "g_spAwards", awardData );
 }
References AWARD_PERFECT, Com_sprintf(), Info_SetValueForKey(), Info_ValueForKey(), MAX_INFO_VALUE, S_COLOR_RED, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Print(), and va().
Referenced by UI_SPPostgameMenu_f().
UI_NewGame()
void UI_NewGame (void)
Definition at line 697 of file ui_gameinfo.c.
{
     trap_Cvar_Set( "g_spScores1", "" );
     trap_Cvar_Set( "g_spScores2", "" );
     trap_Cvar_Set( "g_spScores3", "" );
     trap_Cvar_Set( "g_spScores4", "" );
     trap_Cvar_Set( "g_spScores5", "" );
     trap_Cvar_Set( "g_spAwards", "" );
     trap_Cvar_Set( "g_spVideos", "" );
 }
References trap_Cvar_Set().
Referenced by Reset_MenuEvent(), and UI_SPLevelMenu_ResetAction().
UI_ParseInfos()
int UI_ParseInfos (char * buf, int max, char * infos[])
Definition at line 84 of file ui_gameinfo.c.
{
     char    *token;
     int     count;
     char    key[MAX_TOKEN_CHARS];
     char    info[MAX_INFO_STRING];
     count = 0;
     while ( 1 ) {
         token = COM_Parse( &buf );
         if ( !token[0] ) {
             break;
         }
         if ( strcmp( token, "{" ) ) {
             Com_Printf( "Missing { in info file\n" );
             break;
         }
         if ( count == max ) {
             Com_Printf( "Max infos exceeded\n" );
             break;
         }
         info[0] = '\0';
         while ( 1 ) {
             token = COM_ParseExt( &buf, qtrue );
             if ( !token[0] ) {
                 Com_Printf( "Unexpected end of info file\n" );
                 break;
             }
             if ( !strcmp( token, "}" ) ) {
                 break;
             }
             Q_strncpyz( key, token, sizeof( key ) );
             token = COM_ParseExt( &buf, qfalse );
             if ( !token[0] ) {
                 strcpy( token, "<NULL>" );
             }
             Info_SetValueForKey( info, key, token );
         }
         //NOTE: extra space for arena number
         infos[count] = UI_Alloc(strlen(info) + strlen("\\num\\") + strlen(va("%d", MAX_ARENAS)) + 1);
         if (infos[count]) {
             strcpy(infos[count], info);
             count++;
         }
     }
     return count;
 }
References COM_Parse(), COM_ParseExt(), Com_Printf(), count, Info_SetValueForKey(), MAX_ARENAS, MAX_INFO_STRING, MAX_TOKEN_CHARS, Q_strncpyz(), qfalse, qtrue, UI_Alloc(), and va().
Referenced by UI_LoadArenasFromFile(), and UI_LoadBotsFromFile().
UI_SetBestScore()
void UI_SetBestScore (int level, int score)
Definition at line 482 of file ui_gameinfo.c.
{
     int     skill;
     int     oldScore;
     char    arenaKey[16];
     char    scores[MAX_INFO_VALUE];
     // validate score
     if( score < 1 || score > 8 ) {
         return;
     }
     // validate skill
     skill = (int)trap_Cvar_VariableValue( "g_spSkill" );
     if( skill < 1 || skill > 5 ) {
         return;
     }
     // get scores
     trap_Cvar_VariableStringBuffer( va( "g_spScores%i", skill ), scores, MAX_INFO_VALUE );
     // see if this is better
     Com_sprintf( arenaKey, sizeof( arenaKey ), "l%i", level );
     oldScore = atoi( Info_ValueForKey( scores, arenaKey ) );
     if( oldScore && oldScore <= score ) {
         return;
     }
     // update scores
     Info_SetValueForKey( scores, arenaKey, va( "%i", score ) );
     trap_Cvar_Set( va( "g_spScores%i", skill ), scores );
 }
References Com_sprintf(), Info_SetValueForKey(), Info_ValueForKey(), int(), level, MAX_INFO_VALUE, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Cvar_VariableValue(), and va().
Referenced by UI_SPPostgameMenu_f().
UI_ShowTierVideo()
qboolean UI_ShowTierVideo (int tier)
Definition at line 603 of file ui_gameinfo.c.
{
     char    key[16];
     char    videos[MAX_INFO_VALUE];
     if( tier <= 0 ) {
         return qfalse;
     }
     trap_Cvar_VariableStringBuffer( "g_spVideos", videos, sizeof(videos) );
     Com_sprintf( key, sizeof(key), "tier%i", tier );
     if( atoi( Info_ValueForKey( videos, key ) ) ) {
         return qfalse;
     }
     Info_SetValueForKey( videos, key, va( "%i", 1 ) );
     trap_Cvar_Set( "g_spVideos", videos );
     return qtrue;
 }
References Com_sprintf(), Info_SetValueForKey(), Info_ValueForKey(), MAX_INFO_VALUE, qfalse, qtrue, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and va().
Referenced by UI_SPPostgameMenu_MenuDraw(), and UI_SPUnlock_f().
UI_SPUnlock_f()
void UI_SPUnlock_f (void)
Definition at line 753 of file ui_gameinfo.c.
{
     char    arenaKey[16];
     char    scores[MAX_INFO_VALUE];
     int     level;
     int     tier;
     // get scores for skill 1
     trap_Cvar_VariableStringBuffer( "g_spScores1", scores, MAX_INFO_VALUE );
     // update scores
     for( level = 0; level < ui_numSinglePlayerArenas + ui_numSpecialSinglePlayerArenas; level++ ) {
         Com_sprintf( arenaKey, sizeof( arenaKey ), "l%i", level );
         Info_SetValueForKey( scores, arenaKey, "1" );
     }
     trap_Cvar_Set( "g_spScores1", scores );
     // unlock cinematics
     for( tier = 1; tier <= 8; tier++ ) {
         UI_ShowTierVideo( tier );
     }
     trap_Print( "All levels unlocked at skill level 1\n" );
     UI_SPLevelMenu_ReInit();
 }
References Com_sprintf(), Info_SetValueForKey(), level, MAX_INFO_VALUE, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), trap_Print(), ui_numSinglePlayerArenas, ui_numSpecialSinglePlayerArenas, UI_ShowTierVideo(), and UI_SPLevelMenu_ReInit().
Referenced by UI_ConsoleCommand().
UI_SPUnlockMedals_f()
void UI_SPUnlockMedals_f (void)
Definition at line 785 of file ui_gameinfo.c.
{
     int     n;
     char    key[16];
     char    awardData[MAX_INFO_VALUE];
     trap_Cvar_VariableStringBuffer( "g_spAwards", awardData, MAX_INFO_VALUE );
     for( n = 0; n < 6; n++ ) {
         Com_sprintf( key, sizeof(key), "a%i", n );
         Info_SetValueForKey( awardData, key, "100" );
     }
     trap_Cvar_Set( "g_spAwards", awardData );
     trap_Print( "All awards unlocked at 100\n" );
 }
References Com_sprintf(), Info_SetValueForKey(), MAX_INFO_VALUE, trap_Cvar_Set(), trap_Cvar_VariableStringBuffer(), and trap_Print().
Referenced by UI_ConsoleCommand().
UI_TierCompleted()
int UI_TierCompleted (int levelWon)
Definition at line 565 of file ui_gameinfo.c.
{
     int         level;
     int         n;
     int         tier;
     int         score;
     int         skill;
     const char  *info;
     tier = levelWon / ARENAS_PER_TIER;
     level = tier * ARENAS_PER_TIER;
     if( tier == UI_GetNumSPTiers() ) {
         info = UI_GetSpecialArenaInfo( "training" );
         if( levelWon == atoi( Info_ValueForKey( info, "num" ) ) ) {
             return 0;
         }
         info = UI_GetSpecialArenaInfo( "final" );
         if( !info || levelWon == atoi( Info_ValueForKey( info, "num" ) ) ) {
             return tier + 1;
         }
         return -1;
     }
     for( n = 0; n < ARENAS_PER_TIER; n++, level++ ) {
         UI_GetBestScore( level, &score, &skill );
         if ( score != 1 ) {
             return -1;
         }
     }
     return tier + 1;
 }
References ARENAS_PER_TIER, Info_ValueForKey(), level, UI_GetBestScore(), UI_GetNumSPTiers(), and UI_GetSpecialArenaInfo().
Referenced by UI_SPPostgameMenu_f().
Variable Documentation
allocPoint
int allocPoint static
Definition at line 46 of file ui_gameinfo.c.
Referenced by UI_Alloc(), and UI_InitMemory().
memoryPool
char memoryPool[POOLSIZE] static
Definition at line 45 of file ui_gameinfo.c.
Referenced by UI_Alloc().
outOfMemory
int outOfMemory static
Definition at line 46 of file ui_gameinfo.c.
Referenced by UI_Alloc(), UI_InitMemory(), UI_LoadArenas(), and UI_LoadBotsFromFile().
ui_arenaInfos
char* ui_arenaInfos[MAX_ARENAS] static
Definition at line 40 of file ui_gameinfo.c.
Referenced by UI_GetArenaInfoByMap(), UI_GetArenaInfoByNumber(), UI_GetSpecialArenaInfo(), UI_LoadArenas(), and UI_LoadArenasFromFile().
ui_botInfos
char* ui_botInfos[MAX_BOTS] static
Definition at line 37 of file ui_gameinfo.c.
Referenced by UI_GetBotInfoByName(), UI_GetBotInfoByNumber(), and UI_LoadBotsFromFile().
ui_numArenas
int ui_numArenas static
Definition at line 39 of file ui_gameinfo.c.
Referenced by UI_GetArenaInfoByMap(), UI_GetArenaInfoByNumber(), UI_GetBestScore(), UI_GetNumArenas(), UI_GetSpecialArenaInfo(), UI_LoadArenas(), and UI_LoadArenasFromFile().
ui_numBots
int ui_numBots
Definition at line 36 of file ui_gameinfo.c.
Referenced by UI_GetBotInfoByName(), UI_GetBotInfoByNumber(), UI_GetNumBots(), UI_LoadBots(), and UI_LoadBotsFromFile().
ui_numSinglePlayerArenas
int ui_numSinglePlayerArenas static
Definition at line 42 of file ui_gameinfo.c.
Referenced by UI_GetCurrentGame(), UI_GetNumSPArenas(), UI_GetNumSPTiers(), UI_LoadArenas(), and UI_SPUnlock_f().
ui_numSpecialSinglePlayerArenas
int ui_numSpecialSinglePlayerArenas static
Definition at line 43 of file ui_gameinfo.c.
Referenced by UI_LoadArenas(), and UI_SPUnlock_f().