ioquake3 doxygen: C:/entry/dev/ioq3/code/renderercommon/tr_noise.c File Reference
tr_noise.c File Reference
#include "tr_common.h"
Macros
#define NOISE_SIZE 256
#define NOISE_MASK (NOISE_SIZE - 1)
#define VAL(a) s_noise_perm[ (a) & (NOISE_MASK)]
#define INDEX(x, y, z, t) VAL(x + VAL(y + VAL(z + VAL(t))))
Functions
static float GetNoiseValue (int x, int y, int z, int t)
void R_NoiseInit (void)
float R_NoiseGet4f (float x, float y, float z, double t)
Variables
static float s_noise_table [NOISE_SIZE]
static int s_noise_perm [NOISE_SIZE]
Macro Definition Documentation
INDEX
#define INDEX (x, y, z, t) VAL(x + VAL(y + VAL(z + VAL(t))))
Definition at line 29 of file tr_noise.c.
NOISE_MASK
#define NOISE_MASK (NOISE_SIZE - 1)
Definition at line 26 of file tr_noise.c.
NOISE_SIZE
#define NOISE_SIZE 256
Definition at line 25 of file tr_noise.c.
VAL
#define VAL (a) s_noise_perm[ (a) & (NOISE_MASK)]
Definition at line 28 of file tr_noise.c.
Function Documentation
GetNoiseValue()
static float GetNoiseValue (int x, int y, int z, int t) static
Definition at line 34 of file tr_noise.c.
 {
     int index = INDEX( ( int ) x, ( int ) y, ( int ) z, ( int ) t );
     return s_noise_table[index];
 }
References INDEX, s_noise_table, and t.
Referenced by R_NoiseGet4f().
R_NoiseGet4f()
float R_NoiseGet4f (float x, float y, float z, double t)
Definition at line 52 of file tr_noise.c.
 {
     int i;
     int ix, iy, iz, it;
     float fx, fy, fz, ft;
     float front[4];
     float back[4];
     float fvalue, bvalue, value[2], finalvalue;
     ix = ( int ) floor( x );
     fx = x - ix;
     iy = ( int ) floor( y );
     fy = y - iy;
     iz = ( int ) floor( z );
     fz = z - iz;
     it = ( int ) floor( t );
     ft = t - it;
     for ( i = 0; i < 2; i++ )
     {
         front[0] = GetNoiseValue( ix, iy, iz, it + i );
         front[1] = GetNoiseValue( ix+1, iy, iz, it + i );
         front[2] = GetNoiseValue( ix, iy+1, iz, it + i );
         front[3] = GetNoiseValue( ix+1, iy+1, iz, it + i );
         back[0] = GetNoiseValue( ix, iy, iz + 1, it + i );
         back[1] = GetNoiseValue( ix+1, iy, iz + 1, it + i );
         back[2] = GetNoiseValue( ix, iy+1, iz + 1, it + i );
         back[3] = GetNoiseValue( ix+1, iy+1, iz + 1, it + i );
         fvalue = LERP( LERP( front[0], front[1], fx ), LERP( front[2], front[3], fx ), fy );
         bvalue = LERP( LERP( back[0], back[1], fx ), LERP( back[2], back[3], fx ), fy );
         value[i] = LERP( fvalue, bvalue, fz );
     }
     finalvalue = LERP( value[0], value[1], ft );
     return finalvalue;
 }
References GetNoiseValue(), int(), LERP, and t.
Referenced by RB_CalcDeformNormals(), and RB_CalcWaveColorSingle().
R_NoiseInit()
void R_NoiseInit (void)
Definition at line 41 of file tr_noise.c.
 {
     int i;
     for ( i = 0; i < NOISE_SIZE; i++ )
     {
         s_noise_table[i] = ( float ) ( ( ( rand() / ( float ) RAND_MAX ) * 2.0 - 1.0 ) );
         s_noise_perm[i] = ( unsigned char ) ( rand() / ( float ) RAND_MAX * 255 );
     }
 }
References NOISE_SIZE, s_noise_perm, and s_noise_table.
Referenced by R_Init().
Variable Documentation
s_noise_perm
int s_noise_perm[NOISE_SIZE] static
Definition at line 32 of file tr_noise.c.
Referenced by R_NoiseInit().
s_noise_table
float s_noise_table[NOISE_SIZE] static
Definition at line 31 of file tr_noise.c.
Referenced by GetNoiseValue(), and R_NoiseInit().