ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_credits.c File Reference
ui_credits.c File Reference
#include "ui_local.h"
Classes
struct creditsmenu_t
Functions
static void UI_CreditMenu_Draw_ioq3 (void)
static sfxHandle_t UI_CreditMenu_Key (int key)
static void UI_CreditMenu_Draw (void)
void UI_CreditMenu (void)
Variables
static creditsmenu_t s_credits
Function Documentation
UI_CreditMenu()
void UI_CreditMenu (void)
Definition at line 172 of file ui_credits.c.
{
     memset( &s_credits, 0 ,sizeof(s_credits) );
     s_credits.menu.draw = UI_CreditMenu_Draw;
     s_credits.menu.key = UI_CreditMenu_Key;
     s_credits.menu.fullscreen = qtrue;
     UI_PushMenu ( &s_credits.menu );
 }
References _tag_menuframework::draw, _tag_menuframework::fullscreen, _tag_menuframework::key, creditsmenu_t::menu, qtrue, s_credits, UI_CreditMenu_Draw(), UI_CreditMenu_Key(), and UI_PushMenu().
Referenced by InGame_QuitAction(), and MainMenu_ExitAction().
UI_CreditMenu_Draw()
static void UI_CreditMenu_Draw (void) static
Definition at line 112 of file ui_credits.c.
{
     int     y;
     y = 12;
     UI_DrawProportionalString( 320, y, "id Software is:", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Programming", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "John Carmack, Robert A. Duffy, Jim Dose'", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Art", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Adrian Carmack, Kevin Cloud,", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Kenneth Scott, Seneca Menard, Fred Nilsson", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Game Designer", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Graeme Devine", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Level Design", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Tim Willits, Christian Antkow, Paul Jaquays", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "CEO", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Todd Hollenshead", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Director of Business Development", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Marty Stratton", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Biz Assist and id Mom", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Donna Jackson", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Development Assistance", UI_CENTER|UI_SMALLFONT, color_white );
     y += PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawProportionalString( 320, y, "Eric Webb", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.35 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     UI_DrawString( 320, y, "To order: 1-800-idgames     www.quake3arena.com     www.idsoftware.com", UI_CENTER|UI_SMALLFONT, color_red );
     y += SMALLCHAR_HEIGHT;
     UI_DrawString( 320, y, "Quake III Arena(c) 1999-2000, Id Software, Inc.  All Rights Reserved", UI_CENTER|UI_SMALLFONT, color_red );
 }
References color_red, color_white, PROP_HEIGHT, PROP_SMALL_SIZE_SCALE, SMALLCHAR_HEIGHT, UI_CENTER, UI_DrawProportionalString(), UI_DrawString(), and UI_SMALLFONT.
Referenced by UI_CreditMenu().
UI_CreditMenu_Draw_ioq3()
static void UI_CreditMenu_Draw_ioq3 (void) static
Definition at line 48 of file ui_credits.c.
{
     int     y;
     int     i;
     // These are all people that have made commits to Subversion, and thus
     //  probably incomplete.
     // (These are in alphabetical order, for the defense of everyone's egos.)
     static const char *names[] = {
         "Tim Angus",
         "James Canete",
         "Vincent Cojot",
         "Ryan C. Gordon",
         "Aaron Gyes",
         "Zack Middleton",
         "Ludwig Nussel",
         "Julian Priestley",
         "Scirocco Six",
         "Thilo Schulz",
         "Zachary J. Slater",
         "Tony J. White",
         "...and many, many others!",  // keep this one last.
         NULL
     };
     // Center text vertically on the screen
     y = (SCREEN_HEIGHT - ARRAY_LEN(names) * (1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE)) / 2;
     UI_DrawProportionalString( 320, y, "ioquake3 contributors:", UI_CENTER|UI_SMALLFONT, color_white );
     y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     for (i = 0; names[i]; i++) {
         UI_DrawProportionalString( 320, y, names[i], UI_CENTER|UI_SMALLFONT, color_white );
         y += 1.42 * PROP_HEIGHT * PROP_SMALL_SIZE_SCALE;
     }
     UI_DrawString( 320, 459, "http://www.ioquake3.org/", UI_CENTER|UI_SMALLFONT, color_red );
 }
References ARRAY_LEN, color_red, color_white, NULL, PROP_HEIGHT, PROP_SMALL_SIZE_SCALE, SCREEN_HEIGHT, UI_CENTER, UI_DrawProportionalString(), UI_DrawString(), and UI_SMALLFONT.
Referenced by UI_CreditMenu_Key().
UI_CreditMenu_Key()
static sfxHandle_t UI_CreditMenu_Key (int key) static
Definition at line 92 of file ui_credits.c.
{
     if( key & K_CHAR_FLAG ) {
         return 0;
     }
     s_credits.frame++;
     if (s_credits.frame == 1) {
         s_credits.menu.draw = UI_CreditMenu_Draw_ioq3;
     } else {
         trap_Cmd_ExecuteText( EXEC_APPEND, "quit\n" );
     }
     return 0;
 }
References _tag_menuframework::draw, EXEC_APPEND, creditsmenu_t::frame, K_CHAR_FLAG, creditsmenu_t::menu, s_credits, trap_Cmd_ExecuteText(), and UI_CreditMenu_Draw_ioq3().
Referenced by UI_CreditMenu().
Variable Documentation
s_credits
creditsmenu_t s_credits static
Definition at line 40 of file ui_credits.c.
Referenced by UI_CreditMenu(), and UI_CreditMenu_Key().