ioquake3 doxygen: C:/entry/dev/ioquake3/code/client/snd_codec_wav.c File Reference
snd_codec_wav.c File Reference
#include "client.h"
#include "snd_codec.h"
Functions
static int FGetLittleLong (fileHandle_t f)
static short FGetLittleShort (fileHandle_t f)
static int S_ReadChunkInfo (fileHandle_t f, char *name)
static int S_FindRIFFChunk (fileHandle_t f, char *chunk)
static void S_ByteSwapRawSamples (int samples, int width, int s_channels, const byte *data)
static qboolean S_ReadRIFFHeader (fileHandle_t file, snd_info_t *info)
void * S_WAV_CodecLoad (const char *filename, snd_info_t *info)
snd_stream_t * S_WAV_CodecOpenStream (const char *filename)
void S_WAV_CodecCloseStream (snd_stream_t *stream)
int S_WAV_CodecReadStream (snd_stream_t *stream, int bytes, void *buffer)
Variables
snd_codec_t wav_codec
Function Documentation
FGetLittleLong()
static int FGetLittleLong (fileHandle_t f) static
Definition at line 32 of file snd_codec_wav.c.
{
     int     v;
     FS_Read( &v, sizeof(v), f );
     return LittleLong( v);
 }
Referenced by S_ReadChunkInfo(), and S_ReadRIFFHeader().
FGetLittleShort()
static short FGetLittleShort (fileHandle_t f) static
Definition at line 45 of file snd_codec_wav.c.
{
     short   v;
     FS_Read( &v, sizeof(v), f );
     return LittleShort( v);
 }
Referenced by S_ReadRIFFHeader().
S_ByteSwapRawSamples()
static void S_ByteSwapRawSamples (int samples, int width, int s_channels, const byte * data) static
Definition at line 108 of file snd_codec_wav.c.
{
     int     i;
     if ( width != 2 ) {
         return;
     }
     if ( LittleShort( 256 ) == 256 ) {
         return;
     }
     if ( s_channels == 2 ) {
         samples <<= 1;
     }
     for ( i = 0 ; i < samples ; i++ ) {
         ((short *)data)[i] = LittleShort( ((short *)data)[i] );
     }
 }
Referenced by S_WAV_CodecLoad(), and S_WAV_CodecReadStream().
S_FindRIFFChunk()
static int S_FindRIFFChunk (fileHandle_t f, char * chunk) static
Definition at line 84 of file snd_codec_wav.c.
{
     char    name[5];
     int     len;
     while( ( len = S_ReadChunkInfo(f, name) ) >= 0 )
     {
         // If this is the right chunk, return
         if( !Q_strncmp( name, chunk, 4 ) )
             return len;
         len = PAD( len, 2 );
         // Not the right chunk - skip it
         FS_Seek( f, len, FS_SEEK_CUR );
     }
     return -1;
 }
Referenced by S_ReadRIFFHeader().
S_ReadChunkInfo()
static int S_ReadChunkInfo (fileHandle_t f, char * name) static
Definition at line 58 of file snd_codec_wav.c.
 {
     int len, r;
     name[4] = 0;
     r = FS_Read(name, 4, f);
     if(r != 4)
         return -1;
     len = FGetLittleLong(f);
     if( len < 0 ) {
         Com_Printf( S_COLOR_YELLOW "WARNING: Negative chunk length\n" );
         return -1;
     }
     return len;
 }
Referenced by S_FindRIFFChunk().
S_ReadRIFFHeader()
static qboolean S_ReadRIFFHeader (fileHandle_t file, snd_info_t * info) static
Definition at line 131 of file snd_codec_wav.c.
 {
     char dump[16];
     int bits;
     int fmtlen = 0;
     // skip the riff wav header
     FS_Read(dump, 12, file);
     // Scan for the format chunk
     if((fmtlen = S_FindRIFFChunk(file, "fmt ")) < 0)
     {
         Com_Printf( S_COLOR_RED "ERROR: Couldn't find \"fmt\" chunk\n");
         return qfalse;
     }
     // Save the parameters
     FGetLittleShort(file); // wav_format
     info->channels = FGetLittleShort(file);
     info->rate = FGetLittleLong(file);
     FGetLittleLong(file);
     FGetLittleShort(file);
     bits = FGetLittleShort(file);
     if( bits < 8 )
     {
       Com_Printf( S_COLOR_RED "ERROR: Less than 8 bit sound is not supported\n");
       return qfalse;
     }
     info->width = bits / 8;
     info->dataofs = 0;
     // Skip the rest of the format chunk if required
     if(fmtlen > 16)
     {
         fmtlen -= 16;
         FS_Seek( file, fmtlen, FS_SEEK_CUR );
     }
     // Scan for the data chunk
     if( (info->size = S_FindRIFFChunk(file, "data")) < 0)
     {
         Com_Printf( S_COLOR_RED "ERROR: Couldn't find \"data\" chunk\n");
         return qfalse;
     }
     info->samples = (info->size / info->width) / info->channels;
     return qtrue;
 }
Referenced by S_WAV_CodecLoad(), and S_WAV_CodecOpenStream().
S_WAV_CodecCloseStream()
void S_WAV_CodecCloseStream (snd_stream_t * stream)
Definition at line 267 of file snd_codec_wav.c.
 {
     S_CodecUtilClose(&stream);
 }
S_WAV_CodecLoad()
void* S_WAV_CodecLoad (const char * filename, snd_info_t * info)
Definition at line 198 of file snd_codec_wav.c.
 {
     fileHandle_t file;
     void *buffer;
     // Try to open the file
     FS_FOpenFileRead(filename, &file, qtrue);
     if(!file)
     {
         return NULL;
     }
     // Read the RIFF header
     if(!S_ReadRIFFHeader(file, info))
     {
         FS_FCloseFile(file);
         Com_Printf( S_COLOR_RED "ERROR: Incorrect/unsupported format in \"%s\"\n",
                 filename);
         return NULL;
     }
     // Allocate some memory
     buffer = Hunk_AllocateTempMemory(info->size);
     if(!buffer)
     {
         FS_FCloseFile(file);
         Com_Printf( S_COLOR_RED "ERROR: Out of memory reading \"%s\"\n",
                 filename);
         return NULL;
     }
     // Read, byteswap
     FS_Read(buffer, info->size, file);
     S_ByteSwapRawSamples(info->samples, info->width, info->channels, (byte *)buffer);
     // Close and return
     FS_FCloseFile(file);
     return buffer;
 }
S_WAV_CodecOpenStream()
snd_stream_t* S_WAV_CodecOpenStream (const char * filename)
Definition at line 243 of file snd_codec_wav.c.
 {
     snd_stream_t *rv;
     // Open
     rv = S_CodecUtilOpen(filename, &wav_codec);
     if(!rv)
         return NULL;
     // Read the RIFF header
     if(!S_ReadRIFFHeader(rv->file, &rv->info))
     {
         S_CodecUtilClose(&rv);
         return NULL;
     }
     return rv;
 }
S_WAV_CodecReadStream()
int S_WAV_CodecReadStream (snd_stream_t * stream, int bytes, void * buffer)
Definition at line 277 of file snd_codec_wav.c.
 {
     int remaining = stream->info.size - stream->pos;
     int samples;
     if(remaining <= 0)
         return 0;
     if(bytes > remaining)
         bytes = remaining;
     stream->pos += bytes;
     samples = (bytes / stream->info.width) / stream->info.channels;
     FS_Read(buffer, bytes, stream->file);
     S_ByteSwapRawSamples(samples, stream->info.width, stream->info.channels, buffer);
     return bytes;
 }
Variable Documentation
wav_codec
snd_codec_t wav_codec
Initial value:
=
{
    "wav",
    S_WAV_CodecLoad,
    S_WAV_CodecOpenStream,
    S_WAV_CodecReadStream,
    S_WAV_CodecCloseStream,
    NULL
}
Definition at line 183 of file snd_codec_wav.c.
Referenced by S_CodecInit(), and S_WAV_CodecOpenStream().