ioquake3 doxygen: C:/entry/dev/ioq3/code/cgame/cg_main.c File Reference
cg_main.c File Reference
#include "cg_local.h"
Classes
struct cvarTable_t
Functions
void CG_Init (int serverMessageNum, int serverCommandSequence, int clientNum)
void CG_Shutdown (void)
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
void CG_RegisterCvars (void)
static void CG_ForceModelChange (void)
void CG_UpdateCvars (void)
int CG_CrosshairPlayer (void)
int CG_LastAttacker (void)
void QDECL CG_Printf (const char *msg,...)
void QDECL CG_Error (const char *msg,...)
void QDECL Com_Error (int level, const char *error,...)
void QDECL Com_Printf (const char *msg,...)
const char * CG_Argv (int arg)
static void CG_RegisterItemSounds (int itemNum)
static void CG_RegisterSounds (void)
static void CG_RegisterGraphics (void)
CG_RegisterGraphics() may execute for a couple of minutes with a slow disk.
void CG_BuildSpectatorString (void)
static void CG_RegisterClients (void)
const char * CG_ConfigString (int index)
void CG_StartMusic (void)
void CG_EventHandling (int type)
void CG_KeyEvent (int key, qboolean down)
void CG_MouseEvent (int x, int y)
Variables
int forceModelModificationCount = -1
cg_t cg
cgs_t cgs
centity_t cg_entities [MAX_GENTITIES]
weaponInfo_t cg_weapons [MAX_WEAPONS]
itemInfo_t cg_items [MAX_ITEMS]
vmCvar_t cg_railTrailTime
vmCvar_t cg_centertime
vmCvar_t cg_runpitch
vmCvar_t cg_runroll
vmCvar_t cg_bobup
vmCvar_t cg_bobpitch
vmCvar_t cg_bobroll
vmCvar_t cg_swingSpeed
vmCvar_t cg_shadows
vmCvar_t cg_gibs
vmCvar_t cg_drawTimer
vmCvar_t cg_drawFPS
vmCvar_t cg_drawSnapshot
vmCvar_t cg_draw3dIcons
vmCvar_t cg_drawIcons
vmCvar_t cg_drawAmmoWarning
vmCvar_t cg_drawCrosshair
vmCvar_t cg_drawCrosshairNames
vmCvar_t cg_drawRewards
vmCvar_t cg_crosshairSize
vmCvar_t cg_crosshairX
vmCvar_t cg_crosshairY
vmCvar_t cg_crosshairHealth
vmCvar_t cg_draw2D
vmCvar_t cg_drawStatus
vmCvar_t cg_animSpeed
vmCvar_t cg_debugAnim
vmCvar_t cg_debugPosition
vmCvar_t cg_debugEvents
vmCvar_t cg_errorDecay
vmCvar_t cg_nopredict
vmCvar_t cg_noPlayerAnims
vmCvar_t cg_showmiss
vmCvar_t cg_footsteps
vmCvar_t cg_addMarks
vmCvar_t cg_brassTime
vmCvar_t cg_viewsize
vmCvar_t cg_drawGun
vmCvar_t cg_gun_frame
vmCvar_t cg_gun_x
vmCvar_t cg_gun_y
vmCvar_t cg_gun_z
vmCvar_t cg_tracerChance
vmCvar_t cg_tracerWidth
vmCvar_t cg_tracerLength
vmCvar_t cg_autoswitch
vmCvar_t cg_ignore
vmCvar_t cg_simpleItems
vmCvar_t cg_fov
vmCvar_t cg_zoomFov
vmCvar_t cg_thirdPerson
vmCvar_t cg_thirdPersonRange
vmCvar_t cg_thirdPersonAngle
vmCvar_t cg_lagometer
vmCvar_t cg_drawAttacker
vmCvar_t cg_synchronousClients
vmCvar_t cg_teamChatTime
vmCvar_t cg_teamChatHeight
vmCvar_t cg_stats
vmCvar_t cg_buildScript
vmCvar_t cg_forceModel
vmCvar_t cg_paused
vmCvar_t cg_blood
vmCvar_t cg_predictItems
vmCvar_t cg_deferPlayers
vmCvar_t cg_drawTeamOverlay
vmCvar_t cg_teamOverlayUserinfo
vmCvar_t cg_drawFriend
vmCvar_t cg_teamChatsOnly
vmCvar_t cg_hudFiles
vmCvar_t cg_scorePlum
vmCvar_t cg_smoothClients
vmCvar_t pmove_fixed
vmCvar_t pmove_msec
vmCvar_t cg_pmove_msec
vmCvar_t cg_cameraMode
vmCvar_t cg_cameraOrbit
vmCvar_t cg_cameraOrbitDelay
vmCvar_t cg_timescaleFadeEnd
vmCvar_t cg_timescaleFadeSpeed
vmCvar_t cg_timescale
vmCvar_t cg_noProjectileTrail
vmCvar_t cg_oldRail
vmCvar_t cg_oldRocket
vmCvar_t cg_oldPlasma
vmCvar_t cg_trueLightning
static cvarTable_t cvarTable []
static int cvarTableSize = ARRAY_LEN(cvarTable)
Function Documentation
CG_Argv()
const char* CG_Argv (int arg)
Definition at line 482 of file cg_main.c.
 {
     static char    buffer[MAX_STRING_CHARS];
     trap_Argv(arg, buffer, sizeof(buffer));
     return buffer;
 }
Referenced by CG_ConfigStringModified(), CG_ConsoleCommand(), CG_ParseScores(), CG_ParseTeamInfo(), CG_ServerCommand(), CG_TestModel_f(), and CG_Weapon_f().
CG_BuildSpectatorString()
void CG_BuildSpectatorString (void)
Definition at line 1115 of file cg_main.c.
 {
     int i;
     cg.spectatorList[0] = 0;
     for (i = 0; i < MAX_CLIENTS; i++) {
         if (cgs.clientinfo[i].infoValid && cgs.clientinfo[i].team == TEAM_SPECTATOR) {
             Q_strcat(cg.spectatorList, sizeof(cg.spectatorList), va("%s     ", cgs.clientinfo[i].name));
         }
     }
     i = strlen(cg.spectatorList);
     if (i != cg.spectatorLen) {
         cg.spectatorLen = i;
         cg.spectatorWidth = -1;
     }
 }
Referenced by CG_ConfigStringModified(), CG_RegisterClients(), and CG_ScoresDown_f().
CG_ConfigString()
const char* CG_ConfigString (int index)
Definition at line 1168 of file cg_main.c.
 {
     if (index < 0 || index >= MAX_CONFIGSTRINGS) {
         CG_Error("CG_ConfigString: bad index: %i", index);
     }
     return cgs.gameState.stringData + cgs.gameState.stringOffsets[index];
 }
Referenced by CG_ConfigStringModified(), CG_DrawAttacker(), CG_DrawInformation(), CG_DrawNewTeamInfo(), CG_DrawPlayerLocation(), CG_DrawSelectedPlayerLocation(), CG_DrawTeamOverlay(), CG_DrawTourneyScoreboard(), CG_EntityEvent(), CG_ForceModelChange(), CG_Init(), CG_LoadingClient(), CG_NewClientInfo(), CG_NewParticleArea(), CG_Obituary(), CG_ParseServerinfo(), CG_ParseWarmup(), CG_RegisterClients(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_SetConfigValues(), CG_ShaderStateChanged(), and CG_StartMusic().
CG_CrosshairPlayer()
int CG_CrosshairPlayer (void)
Definition at line 413 of file cg_main.c.
 {
     if (cg.time > (cg.crosshairClientTime + 1000)) {
         return -1;
     }
     return cg.crosshairClientNum;
 }
Referenced by CG_TargetCommand_f(), CG_TellTarget_f(), and vmMain().
CG_Error()
void QDECL CG_Error (const char * msg, ...)
Definition at line 441 of file cg_main.c.
 {
     va_list        argptr;
     char        text[1024];
     va_start(argptr, msg);
     Q_vsnprintf(text, sizeof(text), msg, argptr);
     va_end(argptr);
     trap_Error(text);
 }
Referenced by CG_ConfigString(), CG_Init(), CG_RegisterItemSounds(), and vmMain().
CG_EventHandling()
void CG_EventHandling (int type)
Definition at line 2007 of file cg_main.c.
 {
 }
Referenced by vmMain().
CG_ForceModelChange()
static void CG_ForceModelChange (void) static
Definition at line 363 of file cg_main.c.
 {
     int        i;
     for (i = 0; i < MAX_CLIENTS; i++) {
         const char* clientInfo;
         clientInfo = CG_ConfigString(CS_PLAYERS + i);
         if (!clientInfo[0]) {
             continue;
         }
         CG_NewClientInfo(i);
     }
 }
Referenced by CG_UpdateCvars().
CG_Init()
void CG_Init (int serverMessageNum, int serverCommandSequence, int clientNum)
Definition at line 1878 of file cg_main.c.
 {
     const char* s;
     // clear everything
     memset(&cgs, 0, sizeof(cgs));
     memset(&cg, 0, sizeof(cg));
     memset(cg_entities, 0, sizeof(cg_entities));
     memset(cg_weapons, 0, sizeof(cg_weapons));
     memset(cg_items, 0, sizeof(cg_items));
     cg.clientNum = clientNum;
     cgs.processedSnapshotNum = serverMessageNum;
     cgs.serverCommandSequence = serverCommandSequence;
     // load a few needed things before we do any screen updates
     cgs.media.charsetShader = trap_R_RegisterShader("gfx/2d/bigchars");
     cgs.media.whiteShader = trap_R_RegisterShader("white");
     cgs.media.charsetProp = trap_R_RegisterShaderNoMip("menu/art/font1_prop.tga");
     cgs.media.charsetPropGlow = trap_R_RegisterShaderNoMip("menu/art/font1_prop_glo.tga");
     cgs.media.charsetPropB = trap_R_RegisterShaderNoMip("menu/art/font2_prop.tga");
     CG_RegisterCvars();
     CG_InitConsoleCommands();
     cg.weaponSelect = WP_MACHINEGUN;
     cgs.redflag = cgs.blueflag = -1; // For compatibily, default to unset for
     cgs.flagStatus = -1;
     // old servers
     // get the rendering configuration from the client system
     trap_GetGlconfig(&cgs.glconfig);
     cgs.screenXScale = cgs.glconfig.vidWidth / 640.0;
     cgs.screenYScale = cgs.glconfig.vidHeight / 480.0;
     // get the gamestate from the client system
     trap_GetGameState(&cgs.gameState);
     // check version
     s = CG_ConfigString(CS_GAME_VERSION);
     if (strcmp(s, GAME_VERSION)) {
         CG_Error("Client/Server game mismatch: %s/%s", GAME_VERSION, s);
     }
     s = CG_ConfigString(CS_LEVEL_START_TIME);
     cgs.levelStartTime = atoi(s);
     CG_ParseServerinfo();
     // load the new map
     CG_LoadingString("collision map");
     trap_CM_LoadMap(cgs.mapname);
 #ifdef MISSIONPACK
     String_Init();
 #endif
     cg.loading = qtrue;        // force players to load instead of defer
     CG_LoadingString("sounds");
     CG_RegisterSounds();
     CG_LoadingString("graphics");
     CG_RegisterGraphics();
     CG_LoadingString("clients");
     CG_RegisterClients();        // if low on memory, some clients will be deferred
 #ifdef MISSIONPACK
     CG_AssetCache();
     CG_LoadHudMenu();      // load new hud stuff
 #endif
     cg.loading = qfalse;    // future players will be deferred
     CG_InitLocalEntities();
     CG_InitMarkPolys();
     // remove the last loading update
     cg.infoScreenText[0] = 0;
     // Make sure we have update values (scores)
     CG_SetConfigValues();
     CG_StartMusic();
     CG_LoadingString("");
 #ifdef MISSIONPACK
     CG_InitTeamChat();
 #endif
     CG_ShaderStateChanged();
     trap_S_ClearLoopingSounds(qtrue);
 }
Referenced by vmMain().
CG_KeyEvent()
void CG_KeyEvent (int key, qboolean down)
Definition at line 2013 of file cg_main.c.
 {
 }
Referenced by vmMain().
CG_LastAttacker()
int CG_LastAttacker (void)
Definition at line 421 of file cg_main.c.
 {
     if (!cg.attackerTime) {
         return -1;
     }
     return cg.snap->ps.persistant[PERS_ATTACKER];
 }
Referenced by CG_TellAttacker_f(), and vmMain().
CG_MouseEvent()
void CG_MouseEvent (int x, int y)
Definition at line 2017 of file cg_main.c.
 {
 }
Referenced by vmMain().
CG_Printf()
void QDECL CG_Printf (const char * msg, ...)
Definition at line 429 of file cg_main.c.
 {
     va_list        argptr;
     char        text[1024];
     va_start(argptr, msg);
     Q_vsnprintf(text, sizeof(text), msg, argptr);
     va_end(argptr);
     trap_Print(text);
 }
CG_RegisterClients()
static void CG_RegisterClients (void) static
Definition at line 1137 of file cg_main.c.
 {
     int        i;
     CG_LoadingClient(cg.clientNum);
     CG_NewClientInfo(cg.clientNum);
     for (i = 0; i < MAX_CLIENTS; i++) {
         const char* clientInfo;
         if (cg.clientNum == i) {
             continue;
         }
         clientInfo = CG_ConfigString(CS_PLAYERS + i);
         if (!clientInfo[0]) {
             continue;
         }
         CG_LoadingClient(i);
         CG_NewClientInfo(i);
     }
     CG_BuildSpectatorString();
 }
Referenced by CG_Init().
CG_RegisterCvars()
void CG_RegisterCvars (void)
Definition at line 335 of file cg_main.c.
 {
     int            i;
     cvarTable_t* cv;
     char        var[MAX_TOKEN_CHARS];
     for (i = 0, cv = cvarTable; i < cvarTableSize; i++, cv++) {
         trap_Cvar_Register(cv->vmCvar, cv->cvarName,
             cv->defaultString, cv->cvarFlags);
     }
     // see if we are also running the server on this machine
     trap_Cvar_VariableStringBuffer("sv_running", var, sizeof(var));
     cgs.localServer = atoi(var);
     forceModelModificationCount = cg_forceModel.modificationCount;
     trap_Cvar_Register(NULL, "model", DEFAULT_MODEL, CVAR_USERINFO | CVAR_ARCHIVE);
     trap_Cvar_Register(NULL, "headmodel", DEFAULT_MODEL, CVAR_USERINFO | CVAR_ARCHIVE);
     trap_Cvar_Register(NULL, "team_model", DEFAULT_TEAM_MODEL, CVAR_USERINFO | CVAR_ARCHIVE);
     trap_Cvar_Register(NULL, "team_headmodel", DEFAULT_TEAM_HEAD, CVAR_USERINFO | CVAR_ARCHIVE);
 }
Referenced by CG_Init().
CG_RegisterGraphics()
static void CG_RegisterGraphics (void) static
CG_RegisterGraphics() may execute for a couple of minutes with a slow disk.
Definition at line 812 of file cg_main.c.
 {
     int         i;
     char        items[MAX_ITEMS + 1];
     static char* sb_nums[11] = {
         "gfx/2d/numbers/zero_32b",
         "gfx/2d/numbers/one_32b",
         "gfx/2d/numbers/two_32b",
         "gfx/2d/numbers/three_32b",
         "gfx/2d/numbers/four_32b",
         "gfx/2d/numbers/five_32b",
         "gfx/2d/numbers/six_32b",
         "gfx/2d/numbers/seven_32b",
         "gfx/2d/numbers/eight_32b",
         "gfx/2d/numbers/nine_32b",
         "gfx/2d/numbers/minus_32b",
     };
     // clear any references to old media
     memset(&cg.refdef, 0, sizeof(cg.refdef));
     trap_R_ClearScene();
     CG_LoadingString(cgs.mapname);
     trap_R_LoadWorldMap(cgs.mapname);
     // precache status bar pics
     CG_LoadingString("game media");
     for (i = 0; i < 11; i++)
         cgs.media.numberShaders[i] = trap_R_RegisterShader(sb_nums[i]);
     cgs.media.botSkillShaders[0] = trap_R_RegisterShader("menu/art/skill1.tga");
     cgs.media.botSkillShaders[1] = trap_R_RegisterShader("menu/art/skill2.tga");
     cgs.media.botSkillShaders[2] = trap_R_RegisterShader("menu/art/skill3.tga");
     cgs.media.botSkillShaders[3] = trap_R_RegisterShader("menu/art/skill4.tga");
     cgs.media.botSkillShaders[4] = trap_R_RegisterShader("menu/art/skill5.tga");
     cgs.media.viewBloodShader = trap_R_RegisterShader("viewBloodBlend");
     cgs.media.deferShader = trap_R_RegisterShaderNoMip("gfx/2d/defer.tga");
     cgs.media.scoreboardName = trap_R_RegisterShaderNoMip("menu/tab/name.tga");
     cgs.media.scoreboardPing = trap_R_RegisterShaderNoMip("menu/tab/ping.tga");
     cgs.media.scoreboardScore = trap_R_RegisterShaderNoMip("menu/tab/score.tga");
     cgs.media.scoreboardTime = trap_R_RegisterShaderNoMip("menu/tab/time.tga");
     cgs.media.smokePuffShader = trap_R_RegisterShader("smokePuff");
     cgs.media.smokePuffRageProShader = trap_R_RegisterShader("smokePuffRagePro");
     cgs.media.shotgunSmokePuffShader = trap_R_RegisterShader("shotgunSmokePuff");
 #ifdef MISSIONPACK
     cgs.media.nailPuffShader = trap_R_RegisterShader("nailtrail");
     cgs.media.blueProxMine = trap_R_RegisterModel("models/weaphits/proxmineb.md3");
 #endif
     cgs.media.plasmaBallShader = trap_R_RegisterShader("sprites/plasma1");
     cgs.media.bloodTrailShader = trap_R_RegisterShader("bloodTrail");
     cgs.media.lagometerShader = trap_R_RegisterShader("lagometer");
     cgs.media.connectionShader = trap_R_RegisterShader("disconnected");
     cgs.media.waterBubbleShader = trap_R_RegisterShader("waterBubble");
     cgs.media.tracerShader = trap_R_RegisterShader("gfx/misc/tracer");
     cgs.media.selectShader = trap_R_RegisterShader("gfx/2d/select");
     for (i = 0; i < NUM_CROSSHAIRS; i++)
         cgs.media.crosshairShader[i] = trap_R_RegisterShader(va("gfx/2d/crosshair%c", 'a' + i));
     cgs.media.backTileShader = trap_R_RegisterShader("gfx/2d/backtile");
     cgs.media.noammoShader = trap_R_RegisterShader("icons/noammo");
     // powerup shaders
     cgs.media.quadShader = trap_R_RegisterShader("powerups/quad");
     cgs.media.quadWeaponShader = trap_R_RegisterShader("powerups/quadWeapon");
     cgs.media.battleSuitShader = trap_R_RegisterShader("powerups/battleSuit");
     cgs.media.battleWeaponShader = trap_R_RegisterShader("powerups/battleWeapon");
     cgs.media.invisShader = trap_R_RegisterShader("powerups/invisibility");
     cgs.media.regenShader = trap_R_RegisterShader("powerups/regen");
     cgs.media.hastePuffShader = trap_R_RegisterShader("hasteSmokePuff");
 #ifdef MISSIONPACK
     if (cgs.gametype == GT_HARVESTER || cg_buildScript.integer) {
         cgs.media.redCubeModel = trap_R_RegisterModel("models/powerups/orb/r_orb.md3");
         cgs.media.blueCubeModel = trap_R_RegisterModel("models/powerups/orb/b_orb.md3");
         cgs.media.redCubeIcon = trap_R_RegisterShader("icons/skull_red");
         cgs.media.blueCubeIcon = trap_R_RegisterShader("icons/skull_blue");
     }
     if (cgs.gametype == GT_CTF || cgs.gametype == GT_1FCTF || cgs.gametype == GT_HARVESTER || cg_buildScript.integer) {
 #else
     if (cgs.gametype == GT_CTF || cg_buildScript.integer) {
 #endif
         cgs.media.redFlagModel = trap_R_RegisterModel("models/flags/r_flag.md3");
         cgs.media.blueFlagModel = trap_R_RegisterModel("models/flags/b_flag.md3");
         cgs.media.redFlagShader[0] = trap_R_RegisterShaderNoMip("icons/iconf_red1");
         cgs.media.redFlagShader[1] = trap_R_RegisterShaderNoMip("icons/iconf_red2");
         cgs.media.redFlagShader[2] = trap_R_RegisterShaderNoMip("icons/iconf_red3");
         cgs.media.blueFlagShader[0] = trap_R_RegisterShaderNoMip("icons/iconf_blu1");
         cgs.media.blueFlagShader[1] = trap_R_RegisterShaderNoMip("icons/iconf_blu2");
         cgs.media.blueFlagShader[2] = trap_R_RegisterShaderNoMip("icons/iconf_blu3");
 #ifdef MISSIONPACK
         cgs.media.flagPoleModel = trap_R_RegisterModel("models/flag2/flagpole.md3");
         cgs.media.flagFlapModel = trap_R_RegisterModel("models/flag2/flagflap3.md3");
         cgs.media.redFlagFlapSkin = trap_R_RegisterSkin("models/flag2/red.skin");
         cgs.media.blueFlagFlapSkin = trap_R_RegisterSkin("models/flag2/blue.skin");
         cgs.media.neutralFlagFlapSkin = trap_R_RegisterSkin("models/flag2/white.skin");
         cgs.media.redFlagBaseModel = trap_R_RegisterModel("models/mapobjects/flagbase/red_base.md3");
         cgs.media.blueFlagBaseModel = trap_R_RegisterModel("models/mapobjects/flagbase/blue_base.md3");
         cgs.media.neutralFlagBaseModel = trap_R_RegisterModel("models/mapobjects/flagbase/ntrl_base.md3");
 #endif
     }
 #ifdef MISSIONPACK
     if (cgs.gametype == GT_1FCTF || cg_buildScript.integer) {
         cgs.media.neutralFlagModel = trap_R_RegisterModel("models/flags/n_flag.md3");
         cgs.media.flagShader[0] = trap_R_RegisterShaderNoMip("icons/iconf_neutral1");
         cgs.media.flagShader[1] = trap_R_RegisterShaderNoMip("icons/iconf_red2");
         cgs.media.flagShader[2] = trap_R_RegisterShaderNoMip("icons/iconf_blu2");
         cgs.media.flagShader[3] = trap_R_RegisterShaderNoMip("icons/iconf_neutral3");
     }
     if (cgs.gametype == GT_OBELISK || cg_buildScript.integer) {
         cgs.media.rocketExplosionShader = trap_R_RegisterShader("rocketExplosion");
         cgs.media.overloadBaseModel = trap_R_RegisterModel("models/powerups/overload_base.md3");
         cgs.media.overloadTargetModel = trap_R_RegisterModel("models/powerups/overload_target.md3");
         cgs.media.overloadLightsModel = trap_R_RegisterModel("models/powerups/overload_lights.md3");
         cgs.media.overloadEnergyModel = trap_R_RegisterModel("models/powerups/overload_energy.md3");
     }
     if (cgs.gametype == GT_HARVESTER || cg_buildScript.integer) {
         cgs.media.harvesterModel = trap_R_RegisterModel("models/powerups/harvester/harvester.md3");
         cgs.media.harvesterRedSkin = trap_R_RegisterSkin("models/powerups/harvester/red.skin");
         cgs.media.harvesterBlueSkin = trap_R_RegisterSkin("models/powerups/harvester/blue.skin");
         cgs.media.harvesterNeutralModel = trap_R_RegisterModel("models/powerups/obelisk/obelisk.md3");
     }
     cgs.media.redKamikazeShader = trap_R_RegisterShader("models/weaphits/kamikred");
     cgs.media.dustPuffShader = trap_R_RegisterShader("hasteSmokePuff");
 #endif
     if (cgs.gametype >= GT_TEAM || cg_buildScript.integer) {
         cgs.media.friendShader = trap_R_RegisterShader("sprites/foe");
         cgs.media.redQuadShader = trap_R_RegisterShader("powerups/blueflag");
         cgs.media.teamStatusBar = trap_R_RegisterShader("gfx/2d/colorbar.tga");
 #ifdef MISSIONPACK
         cgs.media.blueKamikazeShader = trap_R_RegisterShader("models/weaphits/kamikblu");
 #endif
     }
     cgs.media.armorModel = trap_R_RegisterModel("models/powerups/armor/armor_yel.md3");
     cgs.media.armorIcon = trap_R_RegisterShaderNoMip("icons/iconr_yellow");
     cgs.media.machinegunBrassModel = trap_R_RegisterModel("models/weapons2/shells/m_shell.md3");
     cgs.media.shotgunBrassModel = trap_R_RegisterModel("models/weapons2/shells/s_shell.md3");
     cgs.media.gibAbdomen = trap_R_RegisterModel("models/gibs/abdomen.md3");
     cgs.media.gibArm = trap_R_RegisterModel("models/gibs/arm.md3");
     cgs.media.gibChest = trap_R_RegisterModel("models/gibs/chest.md3");
     cgs.media.gibFist = trap_R_RegisterModel("models/gibs/fist.md3");
     cgs.media.gibFoot = trap_R_RegisterModel("models/gibs/foot.md3");
     cgs.media.gibForearm = trap_R_RegisterModel("models/gibs/forearm.md3");
     cgs.media.gibIntestine = trap_R_RegisterModel("models/gibs/intestine.md3");
     cgs.media.gibLeg = trap_R_RegisterModel("models/gibs/leg.md3");
     cgs.media.gibSkull = trap_R_RegisterModel("models/gibs/skull.md3");
     cgs.media.gibBrain = trap_R_RegisterModel("models/gibs/brain.md3");
     cgs.media.smoke2 = trap_R_RegisterModel("models/weapons2/shells/s_shell.md3");
     cgs.media.balloonShader = trap_R_RegisterShader("sprites/balloon3");
     cgs.media.bloodExplosionShader = trap_R_RegisterShader("bloodExplosion");
     cgs.media.bulletFlashModel = trap_R_RegisterModel("models/weaphits/bullet.md3");
     cgs.media.ringFlashModel = trap_R_RegisterModel("models/weaphits/ring02.md3");
     cgs.media.dishFlashModel = trap_R_RegisterModel("models/weaphits/boom01.md3");
 #ifdef MISSIONPACK
     cgs.media.teleportEffectModel = trap_R_RegisterModel("models/powerups/pop.md3");
 #else
     cgs.media.teleportEffectModel = trap_R_RegisterModel("models/misc/telep.md3");
     cgs.media.teleportEffectShader = trap_R_RegisterShader("teleportEffect");
 #endif
 #ifdef MISSIONPACK
     cgs.media.kamikazeEffectModel = trap_R_RegisterModel("models/weaphits/kamboom2.md3");
     cgs.media.kamikazeShockWave = trap_R_RegisterModel("models/weaphits/kamwave.md3");
     cgs.media.kamikazeHeadModel = trap_R_RegisterModel("models/powerups/kamikazi.md3");
     cgs.media.kamikazeHeadTrail = trap_R_RegisterModel("models/powerups/trailtest.md3");
     cgs.media.guardPowerupModel = trap_R_RegisterModel("models/powerups/guard_player.md3");
     cgs.media.scoutPowerupModel = trap_R_RegisterModel("models/powerups/scout_player.md3");
     cgs.media.doublerPowerupModel = trap_R_RegisterModel("models/powerups/doubler_player.md3");
     cgs.media.ammoRegenPowerupModel = trap_R_RegisterModel("models/powerups/ammo_player.md3");
     cgs.media.invulnerabilityImpactModel = trap_R_RegisterModel("models/powerups/shield/impact.md3");
     cgs.media.invulnerabilityJuicedModel = trap_R_RegisterModel("models/powerups/shield/juicer.md3");
     cgs.media.medkitUsageModel = trap_R_RegisterModel("models/powerups/regen.md3");
     cgs.media.heartShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/selectedhealth.tga");
     cgs.media.invulnerabilityPowerupModel = trap_R_RegisterModel("models/powerups/shield/shield.md3");
 #endif
     cgs.media.medalImpressive = trap_R_RegisterShaderNoMip("medal_impressive");
     cgs.media.medalExcellent = trap_R_RegisterShaderNoMip("medal_excellent");
     cgs.media.medalGauntlet = trap_R_RegisterShaderNoMip("medal_gauntlet");
     cgs.media.medalDefend = trap_R_RegisterShaderNoMip("medal_defend");
     cgs.media.medalAssist = trap_R_RegisterShaderNoMip("medal_assist");
     cgs.media.medalCapture = trap_R_RegisterShaderNoMip("medal_capture");
     memset(cg_items, 0, sizeof(cg_items));
     memset(cg_weapons, 0, sizeof(cg_weapons));
     // only register the items that the server says we need
     Q_strncpyz(items, CG_ConfigString(CS_ITEMS), sizeof(items));
     for (i = 1; i < bg_numItems; i++) {
         if (items[i] == '1' || cg_buildScript.integer) {
             CG_LoadingItem(i);
             CG_RegisterItemVisuals(i);
         }
     }
     // wall marks
     cgs.media.bulletMarkShader = trap_R_RegisterShader("gfx/damage/bullet_mrk");
     cgs.media.burnMarkShader = trap_R_RegisterShader("gfx/damage/burn_med_mrk");
     cgs.media.holeMarkShader = trap_R_RegisterShader("gfx/damage/hole_lg_mrk");
     cgs.media.energyMarkShader = trap_R_RegisterShader("gfx/damage/plasma_mrk");
     cgs.media.shadowMarkShader = trap_R_RegisterShader("markShadow");
     cgs.media.wakeMarkShader = trap_R_RegisterShader("wake");
     cgs.media.bloodMarkShader = trap_R_RegisterShader("bloodMark");
     // register the inline models
     cgs.numInlineModels = trap_CM_NumInlineModels();
     for (i = 1; i < cgs.numInlineModels; i++) {
         char    name[10];
         vec3_t  mins, maxs;
         int     j;
         Com_sprintf(name, sizeof(name), "*%i", i);
         cgs.inlineDrawModel[i] = trap_R_RegisterModel(name);
         trap_R_ModelBounds(cgs.inlineDrawModel[i], mins, maxs);
         for (j = 0; j < 3; j++) {
             cgs.inlineModelMidpoints[i][j] = mins[j] + 0.5 * (maxs[j] - mins[j]);
         }
     }
     // register all the server specified models
     for (i = 1; i < MAX_MODELS; i++) {
         const char* modelName;
         modelName = CG_ConfigString(CS_MODELS + i);
         if (!modelName[0]) {
             break;
         }
         cgs.gameModels[i] = trap_R_RegisterModel(modelName);
     }
 #ifdef MISSIONPACK
     // new stuff
     cgs.media.patrolShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/patrol.tga");
     cgs.media.assaultShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/assault.tga");
     cgs.media.campShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/camp.tga");
     cgs.media.followShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/follow.tga");
     cgs.media.defendShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/defend.tga");
     cgs.media.teamLeaderShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/team_leader.tga");
     cgs.media.retrieveShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/retrieve.tga");
     cgs.media.escortShader = trap_R_RegisterShaderNoMip("ui/assets/statusbar/escort.tga");
     cgs.media.cursor = trap_R_RegisterShaderNoMip("menu/art/3_cursor2");
     cgs.media.sizeCursor = trap_R_RegisterShaderNoMip("ui/assets/sizecursor.tga");
     cgs.media.selectCursor = trap_R_RegisterShaderNoMip("ui/assets/selectcursor.tga");
     cgs.media.flagShaders[0] = trap_R_RegisterShaderNoMip("ui/assets/statusbar/flag_in_base.tga");
     cgs.media.flagShaders[1] = trap_R_RegisterShaderNoMip("ui/assets/statusbar/flag_capture.tga");
     cgs.media.flagShaders[2] = trap_R_RegisterShaderNoMip("ui/assets/statusbar/flag_missing.tga");
     trap_R_RegisterModel("models/players/james/lower.md3");
     trap_R_RegisterModel("models/players/james/upper.md3");
     trap_R_RegisterModel("models/players/heads/james/james.md3");
     trap_R_RegisterModel("models/players/janet/lower.md3");
     trap_R_RegisterModel("models/players/janet/upper.md3");
     trap_R_RegisterModel("models/players/heads/janet/janet.md3");
 #endif
     CG_ClearParticles();
     /*
         for (i=1; i<MAX_PARTICLES_AREAS; i++)
         {
             {
                 int rval;
                 rval = CG_NewParticleArea ( CS_PARTICLES + i);
                 if (!rval)
                     break;
             }
         }
     */
 }
Referenced by CG_Init().
CG_RegisterItemSounds()
static void CG_RegisterItemSounds (int itemNum) static
Definition at line 501 of file cg_main.c.
 {
     gitem_t* item;
     char            data[MAX_QPATH];
     char* s, * start;
     int                len;
     item = &bg_itemlist[itemNum];
     if (item->pickup_sound) {
         trap_S_RegisterSound(item->pickup_sound, qfalse);
     }
     // parse the space separated precache string for other media
     s = item->sounds;
     if (!s || !s[0])
         return;
     while (*s) {
         start = s;
         while (*s && *s != ' ') {
             s++;
         }
         len = s - start;
         if (len >= MAX_QPATH || len < 5) {
             CG_Error("PrecacheItem: %s has bad precache string",
                 item->classname);
             return;
         }
         memcpy(data, start, len);
         data[len] = 0;
         if (*s) {
             s++;
         }
         if (!strcmp(data + len - 3, "wav")) {
             trap_S_RegisterSound(data, qfalse);
         }
     }
 }
Referenced by CG_RegisterSounds().
CG_RegisterSounds()
static void CG_RegisterSounds (void) static
Definition at line 551 of file cg_main.c.
 {
     int        i;
     char    items[MAX_ITEMS + 1];
     char    name[MAX_QPATH];
     const char* soundName;
     // voice commands
 #ifdef MISSIONPACK
     CG_LoadVoiceChats();
 #endif
     cgs.media.oneMinuteSound = trap_S_RegisterSound("sound/feedback/1_minute.wav", qtrue);
     cgs.media.fiveMinuteSound = trap_S_RegisterSound("sound/feedback/5_minute.wav", qtrue);
     cgs.media.suddenDeathSound = trap_S_RegisterSound("sound/feedback/sudden_death.wav", qtrue);
     cgs.media.oneFragSound = trap_S_RegisterSound("sound/feedback/1_frag.wav", qtrue);
     cgs.media.twoFragSound = trap_S_RegisterSound("sound/feedback/2_frags.wav", qtrue);
     cgs.media.threeFragSound = trap_S_RegisterSound("sound/feedback/3_frags.wav", qtrue);
     cgs.media.count3Sound = trap_S_RegisterSound("sound/feedback/three.wav", qtrue);
     cgs.media.count2Sound = trap_S_RegisterSound("sound/feedback/two.wav", qtrue);
     cgs.media.count1Sound = trap_S_RegisterSound("sound/feedback/one.wav", qtrue);
     cgs.media.countFightSound = trap_S_RegisterSound("sound/feedback/fight.wav", qtrue);
     cgs.media.countPrepareSound = trap_S_RegisterSound("sound/feedback/prepare.wav", qtrue);
 #ifdef MISSIONPACK
     cgs.media.countPrepareTeamSound = trap_S_RegisterSound("sound/feedback/prepare_team.wav", qtrue);
 #endif
     if (cgs.gametype >= GT_TEAM || cg_buildScript.integer) {
         cgs.media.captureAwardSound = trap_S_RegisterSound("sound/teamplay/flagcapture_yourteam.wav", qtrue);
         cgs.media.redLeadsSound = trap_S_RegisterSound("sound/feedback/redleads.wav", qtrue);
         cgs.media.blueLeadsSound = trap_S_RegisterSound("sound/feedback/blueleads.wav", qtrue);
         cgs.media.teamsTiedSound = trap_S_RegisterSound("sound/feedback/teamstied.wav", qtrue);
         cgs.media.hitTeamSound = trap_S_RegisterSound("sound/feedback/hit_teammate.wav", qtrue);
         cgs.media.redScoredSound = trap_S_RegisterSound("sound/teamplay/voc_red_scores.wav", qtrue);
         cgs.media.blueScoredSound = trap_S_RegisterSound("sound/teamplay/voc_blue_scores.wav", qtrue);
         cgs.media.captureYourTeamSound = trap_S_RegisterSound("sound/teamplay/flagcapture_yourteam.wav", qtrue);
         cgs.media.captureOpponentSound = trap_S_RegisterSound("sound/teamplay/flagcapture_opponent.wav", qtrue);
         cgs.media.returnYourTeamSound = trap_S_RegisterSound("sound/teamplay/flagreturn_yourteam.wav", qtrue);
         cgs.media.returnOpponentSound = trap_S_RegisterSound("sound/teamplay/flagreturn_opponent.wav", qtrue);
         cgs.media.takenYourTeamSound = trap_S_RegisterSound("sound/teamplay/flagtaken_yourteam.wav", qtrue);
         cgs.media.takenOpponentSound = trap_S_RegisterSound("sound/teamplay/flagtaken_opponent.wav", qtrue);
         if (cgs.gametype == GT_CTF || cg_buildScript.integer) {
             cgs.media.redFlagReturnedSound = trap_S_RegisterSound("sound/teamplay/voc_red_returned.wav", qtrue);
             cgs.media.blueFlagReturnedSound = trap_S_RegisterSound("sound/teamplay/voc_blue_returned.wav", qtrue);
             cgs.media.enemyTookYourFlagSound = trap_S_RegisterSound("sound/teamplay/voc_enemy_flag.wav", qtrue);
             cgs.media.yourTeamTookEnemyFlagSound = trap_S_RegisterSound("sound/teamplay/voc_team_flag.wav", qtrue);
         }
 #ifdef MISSIONPACK
         if (cgs.gametype == GT_1FCTF || cg_buildScript.integer) {
             // FIXME: get a replacement for this sound ?
             cgs.media.neutralFlagReturnedSound = trap_S_RegisterSound("sound/teamplay/flagreturn_opponent.wav", qtrue);
             cgs.media.yourTeamTookTheFlagSound = trap_S_RegisterSound("sound/teamplay/voc_team_1flag.wav", qtrue);
             cgs.media.enemyTookTheFlagSound = trap_S_RegisterSound("sound/teamplay/voc_enemy_1flag.wav", qtrue);
         }
         if (cgs.gametype == GT_1FCTF || cgs.gametype == GT_CTF || cg_buildScript.integer) {
             cgs.media.youHaveFlagSound = trap_S_RegisterSound("sound/teamplay/voc_you_flag.wav", qtrue);
             cgs.media.holyShitSound = trap_S_RegisterSound("sound/feedback/voc_holyshit.wav", qtrue);
         }
         if (cgs.gametype == GT_OBELISK || cg_buildScript.integer) {
             cgs.media.yourBaseIsUnderAttackSound = trap_S_RegisterSound("sound/teamplay/voc_base_attack.wav", qtrue);
         }
 #else
         cgs.media.youHaveFlagSound = trap_S_RegisterSound("sound/teamplay/voc_you_flag.wav", qtrue);
         cgs.media.holyShitSound = trap_S_RegisterSound("sound/feedback/voc_holyshit.wav", qtrue);
 #endif
     }
     cgs.media.tracerSound = trap_S_RegisterSound("sound/weapons/machinegun/buletby1.wav", qfalse);
     cgs.media.selectSound = trap_S_RegisterSound("sound/weapons/change.wav", qfalse);
     cgs.media.wearOffSound = trap_S_RegisterSound("sound/items/wearoff.wav", qfalse);
     cgs.media.useNothingSound = trap_S_RegisterSound("sound/items/use_nothing.wav", qfalse);
     cgs.media.gibSound = trap_S_RegisterSound("sound/player/gibsplt1.wav", qfalse);
     cgs.media.gibBounce1Sound = trap_S_RegisterSound("sound/player/gibimp1.wav", qfalse);
     cgs.media.gibBounce2Sound = trap_S_RegisterSound("sound/player/gibimp2.wav", qfalse);
     cgs.media.gibBounce3Sound = trap_S_RegisterSound("sound/player/gibimp3.wav", qfalse);
 #ifdef MISSIONPACK
     cgs.media.useInvulnerabilitySound = trap_S_RegisterSound("sound/items/invul_activate.wav", qfalse);
     cgs.media.invulnerabilityImpactSound1 = trap_S_RegisterSound("sound/items/invul_impact_01.wav", qfalse);
     cgs.media.invulnerabilityImpactSound2 = trap_S_RegisterSound("sound/items/invul_impact_02.wav", qfalse);
     cgs.media.invulnerabilityImpactSound3 = trap_S_RegisterSound("sound/items/invul_impact_03.wav", qfalse);
     cgs.media.invulnerabilityJuicedSound = trap_S_RegisterSound("sound/items/invul_juiced.wav", qfalse);
     cgs.media.obeliskHitSound1 = trap_S_RegisterSound("sound/items/obelisk_hit_01.wav", qfalse);
     cgs.media.obeliskHitSound2 = trap_S_RegisterSound("sound/items/obelisk_hit_02.wav", qfalse);
     cgs.media.obeliskHitSound3 = trap_S_RegisterSound("sound/items/obelisk_hit_03.wav", qfalse);
     cgs.media.obeliskRespawnSound = trap_S_RegisterSound("sound/items/obelisk_respawn.wav", qfalse);
     cgs.media.ammoregenSound = trap_S_RegisterSound("sound/items/cl_ammoregen.wav", qfalse);
     cgs.media.doublerSound = trap_S_RegisterSound("sound/items/cl_doubler.wav", qfalse);
     cgs.media.guardSound = trap_S_RegisterSound("sound/items/cl_guard.wav", qfalse);
     cgs.media.scoutSound = trap_S_RegisterSound("sound/items/cl_scout.wav", qfalse);
 #endif
     cgs.media.teleInSound = trap_S_RegisterSound("sound/world/telein.wav", qfalse);
     cgs.media.teleOutSound = trap_S_RegisterSound("sound/world/teleout.wav", qfalse);
     cgs.media.respawnSound = trap_S_RegisterSound("sound/items/respawn1.wav", qfalse);
     cgs.media.noAmmoSound = trap_S_RegisterSound("sound/weapons/noammo.wav", qfalse);
     cgs.media.talkSound = trap_S_RegisterSound("sound/player/talk.wav", qfalse);
     cgs.media.landSound = trap_S_RegisterSound("sound/player/land1.wav", qfalse);
     cgs.media.hitSound = trap_S_RegisterSound("sound/feedback/hit.wav", qfalse);
 #ifdef MISSIONPACK
     cgs.media.hitSoundHighArmor = trap_S_RegisterSound("sound/feedback/hithi.wav", qfalse);
     cgs.media.hitSoundLowArmor = trap_S_RegisterSound("sound/feedback/hitlo.wav", qfalse);
 #endif
     cgs.media.impressiveSound = trap_S_RegisterSound("sound/feedback/impressive.wav", qtrue);
     cgs.media.excellentSound = trap_S_RegisterSound("sound/feedback/excellent.wav", qtrue);
     cgs.media.deniedSound = trap_S_RegisterSound("sound/feedback/denied.wav", qtrue);
     cgs.media.humiliationSound = trap_S_RegisterSound("sound/feedback/humiliation.wav", qtrue);
     cgs.media.assistSound = trap_S_RegisterSound("sound/feedback/assist.wav", qtrue);
     cgs.media.defendSound = trap_S_RegisterSound("sound/feedback/defense.wav", qtrue);
 #ifdef MISSIONPACK
     cgs.media.firstImpressiveSound = trap_S_RegisterSound("sound/feedback/first_impressive.wav", qtrue);
     cgs.media.firstExcellentSound = trap_S_RegisterSound("sound/feedback/first_excellent.wav", qtrue);
     cgs.media.firstHumiliationSound = trap_S_RegisterSound("sound/feedback/first_gauntlet.wav", qtrue);
 #endif
     cgs.media.takenLeadSound = trap_S_RegisterSound("sound/feedback/takenlead.wav", qtrue);
     cgs.media.tiedLeadSound = trap_S_RegisterSound("sound/feedback/tiedlead.wav", qtrue);
     cgs.media.lostLeadSound = trap_S_RegisterSound("sound/feedback/lostlead.wav", qtrue);
 #ifdef MISSIONPACK
     cgs.media.voteNow = trap_S_RegisterSound("sound/feedback/vote_now.wav", qtrue);
     cgs.media.votePassed = trap_S_RegisterSound("sound/feedback/vote_passed.wav", qtrue);
     cgs.media.voteFailed = trap_S_RegisterSound("sound/feedback/vote_failed.wav", qtrue);
 #endif
     cgs.media.watrInSound = trap_S_RegisterSound("sound/player/watr_in.wav", qfalse);
     cgs.media.watrOutSound = trap_S_RegisterSound("sound/player/watr_out.wav", qfalse);
     cgs.media.watrUnSound = trap_S_RegisterSound("sound/player/watr_un.wav", qfalse);
     cgs.media.jumpPadSound = trap_S_RegisterSound("sound/world/jumppad.wav", qfalse);
     for (i = 0; i < 4; i++) {
         Com_sprintf(name, sizeof(name), "sound/player/footsteps/step%i.wav", i + 1);
         cgs.media.footsteps[FOOTSTEP_NORMAL][i] = trap_S_RegisterSound(name, qfalse);
         Com_sprintf(name, sizeof(name), "sound/player/footsteps/boot%i.wav", i + 1);
         cgs.media.footsteps[FOOTSTEP_BOOT][i] = trap_S_RegisterSound(name, qfalse);
         Com_sprintf(name, sizeof(name), "sound/player/footsteps/flesh%i.wav", i + 1);
         cgs.media.footsteps[FOOTSTEP_FLESH][i] = trap_S_RegisterSound(name, qfalse);
         Com_sprintf(name, sizeof(name), "sound/player/footsteps/mech%i.wav", i + 1);
         cgs.media.footsteps[FOOTSTEP_MECH][i] = trap_S_RegisterSound(name, qfalse);
         Com_sprintf(name, sizeof(name), "sound/player/footsteps/energy%i.wav", i + 1);
         cgs.media.footsteps[FOOTSTEP_ENERGY][i] = trap_S_RegisterSound(name, qfalse);
         Com_sprintf(name, sizeof(name), "sound/player/footsteps/splash%i.wav", i + 1);
         cgs.media.footsteps[FOOTSTEP_SPLASH][i] = trap_S_RegisterSound(name, qfalse);
         Com_sprintf(name, sizeof(name), "sound/player/footsteps/clank%i.wav", i + 1);
         cgs.media.footsteps[FOOTSTEP_METAL][i] = trap_S_RegisterSound(name, qfalse);
     }
     // only register the items that the server says we need
     Q_strncpyz(items, CG_ConfigString(CS_ITEMS), sizeof(items));
     for (i = 1; i < bg_numItems; i++) {
         //        if ( items[ i ] == '1' || cg_buildScript.integer ) {
         CG_RegisterItemSounds(i);
         //        }
     }
     for (i = 1; i < MAX_SOUNDS; i++) {
         soundName = CG_ConfigString(CS_SOUNDS + i);
         if (!soundName[0]) {
             break;
         }
         if (soundName[0] == '*') {
             continue;    // custom sound
         }
         cgs.gameSounds[i] = trap_S_RegisterSound(soundName, qfalse);
     }
     // FIXME: only needed with item
     cgs.media.flightSound = trap_S_RegisterSound("sound/items/flight.wav", qfalse);
     cgs.media.medkitSound = trap_S_RegisterSound("sound/items/use_medkit.wav", qfalse);
     cgs.media.quadSound = trap_S_RegisterSound("sound/items/damage3.wav", qfalse);
     cgs.media.sfx_ric1 = trap_S_RegisterSound("sound/weapons/machinegun/ric1.wav", qfalse);
     cgs.media.sfx_ric2 = trap_S_RegisterSound("sound/weapons/machinegun/ric2.wav", qfalse);
     cgs.media.sfx_ric3 = trap_S_RegisterSound("sound/weapons/machinegun/ric3.wav", qfalse);
     //cgs.media.sfx_railg = trap_S_RegisterSound ("sound/weapons/railgun/railgf1a.wav", qfalse);
     cgs.media.sfx_rockexp = trap_S_RegisterSound("sound/weapons/rocket/rocklx1a.wav", qfalse);
     cgs.media.sfx_plasmaexp = trap_S_RegisterSound("sound/weapons/plasma/plasmx1a.wav", qfalse);
 #ifdef MISSIONPACK
     cgs.media.sfx_proxexp = trap_S_RegisterSound("sound/weapons/proxmine/wstbexpl.wav", qfalse);
     cgs.media.sfx_nghit = trap_S_RegisterSound("sound/weapons/nailgun/wnalimpd.wav", qfalse);
     cgs.media.sfx_nghitflesh = trap_S_RegisterSound("sound/weapons/nailgun/wnalimpl.wav", qfalse);
     cgs.media.sfx_nghitmetal = trap_S_RegisterSound("sound/weapons/nailgun/wnalimpm.wav", qfalse);
     cgs.media.sfx_chghit = trap_S_RegisterSound("sound/weapons/vulcan/wvulimpd.wav", qfalse);
     cgs.media.sfx_chghitflesh = trap_S_RegisterSound("sound/weapons/vulcan/wvulimpl.wav", qfalse);
     cgs.media.sfx_chghitmetal = trap_S_RegisterSound("sound/weapons/vulcan/wvulimpm.wav", qfalse);
     cgs.media.weaponHoverSound = trap_S_RegisterSound("sound/weapons/weapon_hover.wav", qfalse);
     cgs.media.kamikazeExplodeSound = trap_S_RegisterSound("sound/items/kam_explode.wav", qfalse);
     cgs.media.kamikazeImplodeSound = trap_S_RegisterSound("sound/items/kam_implode.wav", qfalse);
     cgs.media.kamikazeFarSound = trap_S_RegisterSound("sound/items/kam_explode_far.wav", qfalse);
     cgs.media.winnerSound = trap_S_RegisterSound("sound/feedback/voc_youwin.wav", qfalse);
     cgs.media.loserSound = trap_S_RegisterSound("sound/feedback/voc_youlose.wav", qfalse);
     cgs.media.wstbimplSound = trap_S_RegisterSound("sound/weapons/proxmine/wstbimpl.wav", qfalse);
     cgs.media.wstbimpmSound = trap_S_RegisterSound("sound/weapons/proxmine/wstbimpm.wav", qfalse);
     cgs.media.wstbimpdSound = trap_S_RegisterSound("sound/weapons/proxmine/wstbimpd.wav", qfalse);
     cgs.media.wstbactvSound = trap_S_RegisterSound("sound/weapons/proxmine/wstbactv.wav", qfalse);
 #endif
     cgs.media.regenSound = trap_S_RegisterSound("sound/items/regen.wav", qfalse);
     cgs.media.protectSound = trap_S_RegisterSound("sound/items/protect3.wav", qfalse);
     cgs.media.n_healthSound = trap_S_RegisterSound("sound/items/n_health.wav", qfalse);
     cgs.media.hgrenb1aSound = trap_S_RegisterSound("sound/weapons/grenade/hgrenb1a.wav", qfalse);
     cgs.media.hgrenb2aSound = trap_S_RegisterSound("sound/weapons/grenade/hgrenb2a.wav", qfalse);
 #ifdef MISSIONPACK
     trap_S_RegisterSound("sound/player/james/death1.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/death2.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/death3.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/jump1.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/pain25_1.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/pain75_1.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/pain100_1.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/falling1.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/gasp.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/drown.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/fall1.wav", qfalse);
     trap_S_RegisterSound("sound/player/james/taunt.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/death1.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/death2.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/death3.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/jump1.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/pain25_1.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/pain75_1.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/pain100_1.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/falling1.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/gasp.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/drown.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/fall1.wav", qfalse);
     trap_S_RegisterSound("sound/player/janet/taunt.wav", qfalse);
 #endif
 }
Referenced by CG_Init().
CG_Shutdown()
void CG_Shutdown (void)
Definition at line 1990 of file cg_main.c.
 {
     // some mods may need to do cleanup work here,
     // like closing files or archiving session data
 }
Referenced by vmMain().
CG_StartMusic()
void CG_StartMusic (void)
Definition at line 1184 of file cg_main.c.
 {
     char* s;
     char    parm1[MAX_QPATH], parm2[MAX_QPATH];
     // start the background music
     s = (char*)CG_ConfigString(CS_MUSIC);
     Q_strncpyz(parm1, COM_Parse(&s), sizeof(parm1));
     Q_strncpyz(parm2, COM_Parse(&s), sizeof(parm2));
     trap_S_StartBackgroundTrack(parm1, parm2);
 }
Referenced by CG_ConfigStringModified(), CG_Init(), and CG_MapRestart().
CG_UpdateCvars()
void CG_UpdateCvars (void)
Definition at line 383 of file cg_main.c.
 {
     int            i;
     cvarTable_t* cv;
     for (i = 0, cv = cvarTable; i < cvarTableSize; i++, cv++) {
         trap_Cvar_Update(cv->vmCvar);
     }
     // check for modications here
     // If team overlay is on, ask for updates from the server.  If it's off,
     // let the server know so we don't receive it
     if (drawTeamOverlayModificationCount != cg_drawTeamOverlay.modificationCount) {
         drawTeamOverlayModificationCount = cg_drawTeamOverlay.modificationCount;
         if (cg_drawTeamOverlay.integer > 0) {
             trap_Cvar_Set("teamoverlay", "1");
         } else {
             trap_Cvar_Set("teamoverlay", "0");
         }
     }
     // if force model changed
     if (forceModelModificationCount != cg_forceModel.modificationCount) {
         forceModelModificationCount = cg_forceModel.modificationCount;
         CG_ForceModelChange();
     }
 }
Referenced by CG_DrawActiveFrame().
Com_Error()
void QDECL Com_Error (int level, const char * error, ...)
Definition at line 453 of file cg_main.c.
 {
     va_list        argptr;
     char        text[1024];
     va_start(argptr, error);
     Q_vsnprintf(text, sizeof(text), error, argptr);
     va_end(argptr);
     trap_Error(text);
 }
Referenced by __attribute__(), _UI_Init(), BaseWindingForPlane(), BG_CanItemBeGrabbed(), BG_EvaluateTrajectory(), BG_EvaluateTrajectoryDelta(), BG_FindItemForHoldable(), BG_FindItemForWeapon(), BotImport_HunkAlloc(), Cbuf_ExecuteText(), CheckWinding(), ChopWindingInPlace(), CIN_HandleForVideo(), CL_AddReliableCommand(), CL_CgameSystemCalls(), CL_CheckForResend(), CL_ConfigstringModified(), CL_Disconnect_f(), CL_GetParseEntityState(), CL_GetServerCommand(), CL_GetSnapshot(), CL_GetUserCmd(), CL_InitCGame(), CL_InitRef(), CL_InitUI(), CL_JoystickEvent(), CL_NextDownload(), CL_ParseDownload(), CL_ParseGamestate(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_PlayDemo_f(), CL_ReadDemoMessage(), CL_SetCGameTime(), CL_UISystemCalls(), ClipWindingEpsilon(), CM_AdjustAreaPortalState(), CM_AreasConnected(), CM_ClipHandleToModel(), CM_EdgePlaneNum(), CM_FindPlane(), CM_FindPlane2(), CM_FloodArea_r(), CM_GeneratePatchCollide(), CM_InlineModel(), CM_LeafArea(), CM_LeafCluster(), CM_LoadMap(), CM_PatchCollideFromGrid(), CM_SetBorderInward(), Cmd_RemoveCommandSafe(), CMod_LoadBrushes(), CMod_LoadBrushSides(), CMod_LoadLeafBrushes(), CMod_LoadLeafs(), CMod_LoadLeafSurfaces(), CMod_LoadNodes(), CMod_LoadPatches(), CMod_LoadPlanes(), CMod_LoadShaders(), CMod_LoadSubmodels(), COM_MatchToken(), Cvar_Get(), Cvar_SetSafe(), Cvar_Update(), DoSyscall(), END_CHUNK(), ErrJump(), Field_VariableSizeDraw(), FreeWinding(), FS_CheckFilenameIsMutable(), FS_CheckPak0(), FS_CreatePath(), FS_FCloseFile(), FS_FCreateOpenPipeFile(), FS_FileForHandle(), FS_FileIsInPAK(), FS_FindVM(), FS_FOpenFileAppend(), FS_FOpenFileByMode(), FS_FOpenFileRead(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_FreeFile(), FS_FreeFileList(), FS_HandleForFile(), FS_InitFilesystem(), FS_ListFilteredFiles(), FS_Read(), FS_ReadFileDir(), FS_Rename(), FS_Restart(), FS_Seek(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), FS_Write(), FS_WriteFile(), Hex(), Info_RemoveKey(), Info_RemoveKey_Big(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Info_ValueForKey(), MSG_Copy(), MSG_ReadBits(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_WriteBits(), MSG_WriteByte(), MSG_WriteChar(), MSG_WriteDeltaEntity(), MSG_WriteShort(), Netchan_Transmit(), PC_CopyToken(), Q_strcat(), Q_strncpyz(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_StartSoundEx(), S_Base_UpdateEntityPosition(), S_FindName(), S_Init(), SafeFS_Write(), SCR_DrawScreenField(), SCR_UpdateScreen(), START_CHUNK(), SV_AddEntitiesVisibleFromPoint(), SV_BotFreeClient(), SV_BuildClientSnapshot(), SV_DirectConnect(), SV_GameSystemCalls(), SV_GetConfigstring(), SV_GetServerinfo(), SV_GetUsercmd(), SV_GetUserinfo(), SV_InitGameProgs(), SV_QsortEntityNumbers(), SV_RestartGameProgs(), SV_SetBrushModel(), SV_SetConfigstring(), SV_SetUserinfo(), SV_Startup(), SV_SvEntityForGentity(), Sys_SendPacket(), VM_BlockCopy(), VM_Call(), VM_CallCompiled(), VM_CallInterpreted(), VM_Compile(), VM_Create(), VM_Free(), VM_PrepareInterpreter(), and VM_Restart().
Com_Printf()
void QDECL Com_Printf (const char * msg, ...)
Definition at line 465 of file cg_main.c.
 {
     va_list        argptr;
     char        text[1024];
     va_start(argptr, msg);
     Q_vsnprintf(text, sizeof(text), msg, argptr);
     va_end(argptr);
     trap_Print(text);
 }
Referenced by __attribute__(), _UI_Init(), Alias_Parse(), BG_AddPredictableEventToPlayerstate(), BG_CanItemBeGrabbed(), Cbuf_AddText(), Cbuf_InsertText(), CG_DrawClientScore(), CG_ParseAnimationFile(), CG_RegisterClientModelname(), CG_RegisterClientSkin(), Character_Parse(), CL_AdjustTimeDelta(), CL_CgameSystemCalls(), CL_CheckTimeout(), CL_Clientinfo_f(), CL_CloseAVI(), CL_Configstrings_f(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_DemoCompleted(), CL_Disconnect(), CL_FirstSnapshot(), CL_ForwardCommandToServer(), CL_ForwardToServer_f(), CL_GenerateQKey(), CL_GlobalServers_f(), CL_Init(), CL_InitCGame(), CL_InitDownloads(), CL_InitRef(), CL_KeyState(), CL_LoadConsoleHistory(), CL_LocalServers_f(), CL_MouseMove(), CL_NextDownload(), CL_OpenAVIForWriting(), CL_OpenedPK3List_f(), CL_PacketEvent(), CL_ParseDownload(), CL_ParsePacketEntities(), CL_ParseServerMessage(), CL_ParseSnapshot(), CL_Ping_f(), CL_PlayDemo_f(), CL_Rcon_f(), CL_ReadDemoMessage(), CL_Record_f(), CL_ReferencedPK3List_f(), CL_RequestAuthorization(), CL_RequestMotd(), CL_SaveConsoleHistory(), CL_Sayto_f(), CL_SendCmd(), CL_ServerInfoPacket(), CL_ServersResponsePacket(), CL_ServerStatus_f(), CL_ServerStatusResponse(), CL_SetModel_f(), CL_Shutdown(), CL_StopRecord_f(), CL_SystemInfoChanged(), CL_UISystemCalls(), CL_Video_f(), CL_WalkDemoExt(), CL_WriteAVIAudioFrame(), CL_WritePacket(), ClientForString(), CM_AddFacetBevels(), CM_DrawDebugSurface(), CM_GridPlane(), Cmd_AddCommand(), Cmd_Echo_f(), Cmd_Exec_f(), Cmd_List_f(), Cmd_Vstr_f(), COM_ParseError(), COM_ParseWarning(), Com_sprintf(), compile_one_insn(), Con_Dump_f(), CON_Init(), CON_Input(), Console_Key(), Cvar_Get(), Cvar_List_f(), Cvar_ListModified_f(), Cvar_Print(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Set2(), Cvar_Set_f(), Cvar_Toggle_f(), Cvar_Unset_f(), Cvar_Validate(), Cvar_WriteVariables(), Font_Report(), FS_CheckPak0(), FS_ComparePaks(), FS_CreatePath(), FS_Dir_f(), FS_FCreateOpenPipeFile(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_NewDir_f(), FS_Path_f(), FS_Rename(), FS_Startup(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), FS_SV_Rename(), FS_TouchFile_f(), FS_Which(), FS_Which_f(), FS_Write(), FS_WriteFile(), G_ParseInfos(), GameType_Parse(), IN_KeyDown(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Item_ApplyHacks(), Key_Bind_f(), Key_Bindlist_f(), Key_Unbind_f(), MapList_Parse(), MSG_ReadDeltaEntity(), MSG_ReadDeltaPlayerstate(), MSG_ReportChangeVectors_f(), MSG_WriteBigString(), MSG_WriteString(), NET_CompareBaseAdrMask(), NET_GetLocalAddress(), NET_GetPacket(), NET_Init(), NET_IP6Socket(), NET_IPSocket(), NET_JoinMulticast6(), NET_OpenIP(), NET_OpenSocks(), NET_SendPacket(), NET_SetMulticast6(), NET_Sleep(), Netchan_Process(), Netchan_Transmit(), Netchan_TransmitNextFragment(), PM_CorrectAllSolid(), PM_GroundTrace(), PM_GroundTraceMissed(), PM_StepSlideMove(), readQuadInfo(), S_AL_Init(), S_Base_AddLoopingSound(), S_Base_AddRealLoopingSound(), S_Base_RegisterSound(), S_Base_SoundInfo(), S_Base_SoundList(), S_Base_StartLocalSound(), S_Base_StartSoundEx(), S_Base_Update(), S_CodecGetSound(), S_DisplayFreeMemory(), S_FindName(), S_Init(), S_Music_f(), S_OpenBackgroundStream(), S_Play_f(), S_ReadChunkInfo(), S_ReadRIFFHeader(), S_WAV_CodecLoad(), SHOWNET(), SND_setup(), sparc_compute_code(), String_Report(), SV_AddBanToList(), SV_AddServerCommand(), SV_AreaEntities_r(), SV_AuthorizeIpPacket(), SV_Ban_f(), SV_BanNum_f(), SV_BotLibSetup(), SV_ClientCommand(), SV_ConSay_f(), SV_ConSayto_f(), SV_ConTell_f(), SV_DelBanFromList(), SV_DirectConnect(), SV_DumpUser_f(), SV_ExecuteClientMessage(), SV_FlushBans_f(), SV_GameSystemCalls(), SV_GetChallenge(), SV_GetPlayerByHandle(), SV_GetPlayerByNum(), SV_Kick_f(), SV_KickAll_f(), SV_KickBots_f(), SV_KickNum_f(), SV_ListBans_f(), SV_Map_f(), SV_MapRestart_f(), SV_MasterHeartbeat(), SV_NextDownload_f(), SV_PacketEvent(), SV_SectorList_f(), SV_SendClientSnapshot(), SV_SendServerCommand(), SV_Serverinfo_f(), SV_Shutdown(), SV_SpawnServer(), SV_Status_f(), SV_Systeminfo_f(), SV_UnlinkEntity(), SV_UserMove(), SV_WriteDownloadToClient(), SVC_RemoteCommand(), Sys_DefaultHomePath(), Sys_In_Restart_f(), Sys_LoadDll(), Sys_LoadGameDll(), Sys_PlatformInit(), Sys_SendPacket(), Sys_ShowIP(), Sys_StringToSockaddr(), Sys_UnloadDll(), Sys_WritePIDFile(), Team_Parse(), UI_LoadMenus(), UI_ParseAnimationFile(), UI_ParseInfos(), UI_ParseMenu(), UI_RegisterClientModelname(), UI_RunMenuScript(), UI_StopServerRefresh(), UpdateIPBans(), vimm(), VM_Call(), VM_CallCompiled(), VM_CallInterpreted(), VM_Compile(), VM_Create(), VM_Destroy_Compiled(), VM_Free(), VM_LoadQVM(), VM_LoadSymbols(), VM_Restart(), VM_StackTrace(), VM_VmInfo_f(), and VM_VmProfile_f().
vmMain()
Q_EXPORT intptr_t vmMain (int command, int arg0, int arg1, int arg2, int arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9, int arg10, int arg11)
Definition at line 46 of file cg_main.c.
 {
     switch (command) {
     case CG_INIT:
         CG_Init(arg0, arg1, arg2);
         return 0;
     case CG_SHUTDOWN:
         CG_Shutdown();
         return 0;
     case CG_CONSOLE_COMMAND:
         return CG_ConsoleCommand();
     case CG_DRAW_ACTIVE_FRAME:
         CG_DrawActiveFrame(arg0, arg1, arg2);
         return 0;
     case CG_CROSSHAIR_PLAYER:
         return CG_CrosshairPlayer();
     case CG_LAST_ATTACKER:
         return CG_LastAttacker();
     case CG_KEY_EVENT:
         CG_KeyEvent(arg0, arg1);
         return 0;
     case CG_MOUSE_EVENT:
 #ifdef MISSIONPACK
         cgDC.cursorx = cgs.cursorX;
         cgDC.cursory = cgs.cursorY;
 #endif
         CG_MouseEvent(arg0, arg1);
         return 0;
     case CG_EVENT_HANDLING:
         CG_EventHandling(arg0);
         return 0;
     default:
         CG_Error("vmMain: unknown command %i", command);
         break;
     }
     return -1;
 }
Variable Documentation
cg
cg_t cg
Definition at line 86 of file cg_main.c.
Referenced by CG_AddBufferedSound(), CG_AddExplosion(), CG_AddFadeRGB(), CG_AddFallScaleFade(), CG_AddFragment(), CG_AddLagometerFrameInfo(), CG_AddLocalEntities(), CG_AddMarks(), CG_AddMoveScaleFade(), CG_AddPacketEntities(), CG_AddPainTwitch(), CG_AddParticles(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScaleFade(), CG_AddScorePlum(), CG_AddSpriteExplosion(), CG_AddTestModel(), CG_AddToTeamChat(), CG_AddViewWeapon(), CG_Bleed(), CG_BloodPool(), CG_BloodTrail(), CG_BubbleTrail(), CG_BuildSolidList(), CG_BuildSpectatorString(), CG_CalcEntityLerpPositions(), CG_CalcFov(), CG_CalcMuzzlePoint(), CG_CalculateWeaponPosition(), CG_CalcViewValues(), CG_CalcVrect(), CG_CenterPrint(), CG_CheckAmmo(), CG_CheckChangedPredictableEvents(), CG_CheckEvents(), CG_CheckLocalSounds(), CG_CheckOrderPending(), CG_CheckPlayerstateEvents(), CG_ClearLerpFrame(), CG_ClearParticles(), CG_ClipMoveToEntities(), CG_ColorForHealth(), CG_ConfigStringModified(), CG_CrosshairPlayer(), CG_DamageBlendBlob(), CG_DamageFeedback(), CG_Draw2D(), CG_Draw3DModel(), CG_DrawActive(), CG_DrawActiveFrame(), CG_DrawAmmoWarning(), CG_DrawAreaPowerUp(), CG_DrawAttacker(), CG_DrawBlueFlagHead(), CG_DrawCenterString(), CG_DrawClientScore(), CG_DrawCrosshair(), CG_DrawCrosshair3D(), CG_DrawCrosshairNames(), CG_DrawCTFPowerUp(), CG_DrawDisconnect(), CG_DrawFlagModel(), CG_DrawFollow(), CG_DrawHoldableItem(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawKiller(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawOldScoreboard(), CG_DrawPickupItem(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHasFlag(), CG_DrawPlayerHead(), CG_DrawPlayerHealth(), CG_DrawPlayerItem(), CG_DrawPlayerLocation(), CG_DrawPlayerScore(), CG_DrawPlayerStatus(), CG_DrawPowerups(), CG_DrawRedFlagHead(), CG_DrawReward(), CG_DrawScoreboard(), CG_DrawScores(), CG_DrawSelectedPlayerStatus(), CG_DrawSnapshot(), CG_DrawStatusBar(), CG_DrawStatusBarHead(), CG_DrawTeamColor(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawTeamSpectators(), CG_DrawTeamVote(), CG_DrawTimer(), CG_DrawTourneyScoreboard(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeaponSelect(), CG_EntityEvent(), CG_FadeColor(), CG_FireWeapon(), CG_General(), CG_GetGameStatusText(), CG_GetKillerText(), CG_GetTeamColor(), CG_GetValue(), CG_Grapple(), CG_GrappleTrail(), CG_HarvesterSkulls(), CG_HasteTrail(), CG_ImpactMark(), CG_Init(), CG_InterpolateEntityPosition(), CG_InterpolatePlayerState(), CG_Item(), CG_ItemPickup(), CG_KeyEvent(), CG_LastAttacker(), CG_LaunchExplode(), CG_LaunchGib(), CG_LightningBolt(), CG_LoadingString(), CG_MachineGunEjectBrass(), CG_MachinegunSpinAngle(), CG_MakeExplosion(), CG_MapRestart(), CG_Missile(), CG_MouseEvent(), CG_Mover(), CG_NewClientInfo(), CG_NextWeapon_f(), CG_Obituary(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_OilSlickRemove(), CG_OtherTeamHasFlag(), CG_OutOfAmmoChange(), CG_OwnerDrawVisible(), CG_PainEvent(), CG_ParseScores(), CG_ParseWarmup(), CG_Particle_Bleed(), CG_Particle_OilParticle(), CG_Particle_OilSlick(), CG_ParticleBloodCloud(), CG_ParticleBubble(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleExplosion(), CG_ParticleImpactSmokePuff(), CG_ParticleMisc(), CG_ParticleSmoke(), CG_ParticleSnow(), CG_ParticleSnowFlurry(), CG_ParticleSparks(), CG_PlasmaTrail(), CG_PlayBufferedSounds(), CG_Player(), CG_PlayerFloatSprite(), CG_PlayerSprites(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_PrevWeapon_f(), CG_ProcessSnapshots(), CG_RailTrail(), CG_ReadNextSnapshot(), CG_ReflectVelocity(), CG_RegisterClients(), CG_RegisterGraphics(), CG_ResetEntity(), CG_ResetPlayerEntity(), CG_Respawn(), CG_RocketTrail(), CG_RunLerpFrame(), CG_ScanForCrosshairEntity(), CG_ScorePlum(), CG_ScoresDown_f(), CG_ScoresUp_f(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_ShotgunEjectBrass(), CG_ShotgunFire(), CG_ShowResponseHead(), CG_SpawnEffect(), CG_Speaker(), CG_StepOffset(), CG_SwingAngles(), CG_TeamBase(), CG_TeamScoreboard(), CG_TestGun_f(), CG_TestModel_f(), CG_TestModelNextFrame_f(), CG_TestModelNextSkin_f(), CG_TestModelPrevFrame_f(), CG_TestModelPrevSkin_f(), CG_TileClear(), CG_TouchItem(), CG_TouchTriggerPrediction(), CG_Tracer(), CG_TransitionPlayerState(), CG_TransitionSnapshot(), CG_UseItem(), CG_Viewpos_f(), CG_Weapon_f(), CG_WeaponSelectable(), CG_YourTeamHasFlag(), CG_ZoomDown_f(), CG_ZoomUp_f(), pushReward(), and UI_DrawProportionalString().
cg_addMarks
vmCvar_t cg_addMarks
Definition at line 127 of file cg_main.c.
Referenced by CG_AddMarks(), and CG_ImpactMark().
cg_animSpeed
vmCvar_t cg_animSpeed
Definition at line 118 of file cg_main.c.
Referenced by CG_RunLerpFrame().
cg_autoswitch
vmCvar_t cg_autoswitch
Definition at line 138 of file cg_main.c.
Referenced by CG_ItemPickup().
cg_blood
vmCvar_t cg_blood
Definition at line 155 of file cg_main.c.
Referenced by CG_BigExplode(), CG_Bleed(), CG_DamageBlendBlob(), and CG_GibPlayer().
cg_bobpitch
vmCvar_t cg_bobpitch
Definition at line 98 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
cg_bobroll
vmCvar_t cg_bobroll
Definition at line 99 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
cg_bobup
vmCvar_t cg_bobup
Definition at line 97 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
cg_brassTime
vmCvar_t cg_brassTime
Definition at line 128 of file cg_main.c.
Referenced by CG_FireWeapon(), CG_MachineGunEjectBrass(), and CG_ShotgunEjectBrass().
cg_buildScript
vmCvar_t cg_buildScript
Definition at line 152 of file cg_main.c.
Referenced by CG_LoadClientInfo(), CG_NewClientInfo(), CG_RegisterGraphics(), and CG_RegisterSounds().
cg_cameraMode
vmCvar_t cg_cameraMode
Definition at line 173 of file cg_main.c.
Referenced by CG_OffsetThirdPersonView(), and CG_Player().
cg_cameraOrbit
vmCvar_t cg_cameraOrbit
Definition at line 174 of file cg_main.c.
Referenced by CG_CalcViewValues(), CG_Obituary(), and CG_StartOrbit_f().
cg_cameraOrbitDelay
vmCvar_t cg_cameraOrbitDelay
Definition at line 175 of file cg_main.c.
Referenced by CG_CalcViewValues().
cg_centertime
vmCvar_t cg_centertime
Definition at line 94 of file cg_main.c.
Referenced by CG_DrawCenterString().
cg_crosshairHealth
vmCvar_t cg_crosshairHealth
Definition at line 115 of file cg_main.c.
Referenced by CG_DrawCrosshair().
cg_crosshairSize
vmCvar_t cg_crosshairSize
Definition at line 112 of file cg_main.c.
Referenced by CG_DrawCrosshair(), and CG_DrawCrosshair3D().
cg_crosshairX
vmCvar_t cg_crosshairX
Definition at line 113 of file cg_main.c.
Referenced by CG_DrawCrosshair().
cg_crosshairY
vmCvar_t cg_crosshairY
Definition at line 114 of file cg_main.c.
Referenced by CG_DrawCrosshair().
cg_debugAnim
vmCvar_t cg_debugAnim
Definition at line 119 of file cg_main.c.
Referenced by CG_RunLerpFrame(), and CG_SetLerpFrameAnimation().
cg_debugEvents
vmCvar_t cg_debugEvents
Definition at line 121 of file cg_main.c.
Referenced by CG_EntityEvent().
cg_debugPosition
vmCvar_t cg_debugPosition
Definition at line 120 of file cg_main.c.
Referenced by CG_ResetPlayerEntity().
cg_deferPlayers
vmCvar_t cg_deferPlayers
Definition at line 157 of file cg_main.c.
Referenced by CG_NewClientInfo().
cg_draw2D
vmCvar_t cg_draw2D
Definition at line 116 of file cg_main.c.
Referenced by CG_Draw2D().
cg_draw3dIcons
vmCvar_t cg_draw3dIcons
Definition at line 106 of file cg_main.c.
Referenced by CG_Draw3DModel(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerArmorIcon(), CG_DrawSelectedPlayerHead(), CG_DrawStatusBar(), and CG_HarvesterSkulls().
cg_drawAmmoWarning
vmCvar_t cg_drawAmmoWarning
Definition at line 108 of file cg_main.c.
Referenced by CG_DrawAmmoWarning().
cg_drawAttacker
vmCvar_t cg_drawAttacker
Definition at line 147 of file cg_main.c.
Referenced by CG_DrawUpperRight().
cg_drawCrosshair
vmCvar_t cg_drawCrosshair
Definition at line 109 of file cg_main.c.
Referenced by CG_DrawCrosshair(), CG_DrawCrosshair3D(), and CG_DrawCrosshairNames().
cg_drawCrosshairNames
vmCvar_t cg_drawCrosshairNames
Definition at line 110 of file cg_main.c.
Referenced by CG_DrawCrosshairNames().
cg_drawFPS
vmCvar_t cg_drawFPS
Definition at line 104 of file cg_main.c.
Referenced by CG_DrawUpperRight().
cg_drawFriend
vmCvar_t cg_drawFriend
Definition at line 160 of file cg_main.c.
Referenced by CG_PlayerSprites().
cg_drawGun
vmCvar_t cg_drawGun
Definition at line 130 of file cg_main.c.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), and CG_EntityEvent().
cg_drawIcons
vmCvar_t cg_drawIcons
Definition at line 107 of file cg_main.c.
Referenced by CG_Draw3DModel(), CG_DrawClientScore(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerArmorIcon(), CG_DrawSelectedPlayerHead(), CG_DrawStatusBar(), and CG_HarvesterSkulls().
cg_drawRewards
vmCvar_t cg_drawRewards
Definition at line 111 of file cg_main.c.
Referenced by CG_DrawReward().
cg_drawSnapshot
vmCvar_t cg_drawSnapshot
Definition at line 105 of file cg_main.c.
Referenced by CG_DrawUpperRight().
cg_drawStatus
vmCvar_t cg_drawStatus
Definition at line 117 of file cg_main.c.
Referenced by CG_Draw2D(), CG_DrawPlayerArmorIcon(), CG_DrawStatusBar(), and CG_OwnerDraw().
cg_drawTeamOverlay
vmCvar_t cg_drawTeamOverlay
Definition at line 158 of file cg_main.c.
Referenced by CG_DrawLowerLeft(), CG_DrawLowerRight(), CG_DrawTeamOverlay(), CG_DrawUpperRight(), and CG_UpdateCvars().
cg_drawTimer
vmCvar_t cg_drawTimer
Definition at line 103 of file cg_main.c.
Referenced by CG_DrawUpperRight().
cg_entities
centity_t cg_entities[MAX_GENTITIES]
Definition at line 88 of file cg_main.c.
Referenced by CG_AddPacketEntities(), CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_AdjustPositionForMover(), CG_BuildSolidList(), CG_CalcMuzzlePoint(), CG_CheckPlayerstateEvents(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawStatusBar(), CG_GetValue(), CG_GrappleTrail(), CG_Init(), CG_LoadClientInfo(), CG_ScanForCrosshairEntity(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_ShotgunPellet(), and CG_TransitionSnapshot().
cg_errorDecay
vmCvar_t cg_errorDecay
Definition at line 122 of file cg_main.c.
Referenced by CG_CalcViewValues(), and CG_PredictPlayerState().
cg_footsteps
vmCvar_t cg_footsteps
Definition at line 126 of file cg_main.c.
Referenced by CG_EntityEvent().
cg_forceModel
vmCvar_t cg_forceModel
Definition at line 153 of file cg_main.c.
Referenced by CG_NewClientInfo(), CG_RegisterCvars(), and CG_UpdateCvars().
cg_fov
vmCvar_t cg_fov
Definition at line 141 of file cg_main.c.
Referenced by CG_AddViewWeapon(), and CG_CalcFov().
cg_gibs
vmCvar_t cg_gibs
Definition at line 102 of file cg_main.c.
Referenced by CG_GibPlayer().
cg_gun_frame
vmCvar_t cg_gun_frame
Definition at line 131 of file cg_main.c.
Referenced by CG_AddViewWeapon().
cg_gun_x
vmCvar_t cg_gun_x
Definition at line 132 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
cg_gun_y
vmCvar_t cg_gun_y
Definition at line 133 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
cg_gun_z
vmCvar_t cg_gun_z
Definition at line 134 of file cg_main.c.
Referenced by CG_AddTestModel(), and CG_AddViewWeapon().
cg_hudFiles
vmCvar_t cg_hudFiles
Definition at line 166 of file cg_main.c.
cg_ignore
vmCvar_t cg_ignore
Definition at line 139 of file cg_main.c.
cg_items
itemInfo_t cg_items[MAX_ITEMS]
Definition at line 90 of file cg_main.c.
Referenced by CG_DrawCTFPowerUp(), CG_DrawFlagModel(), CG_DrawHoldableItem(), CG_DrawPickupItem(), CG_DrawPlayerItem(), CG_Init(), CG_Item(), CG_RegisterGraphics(), and CG_RegisterItemVisuals().
cg_lagometer
vmCvar_t cg_lagometer
Definition at line 146 of file cg_main.c.
Referenced by CG_DrawLagometer().
cg_noPlayerAnims
vmCvar_t cg_noPlayerAnims
Definition at line 124 of file cg_main.c.
Referenced by CG_PlayerAnimation().
cg_nopredict
vmCvar_t cg_nopredict
Definition at line 123 of file cg_main.c.
Referenced by CG_DrawLagometer(), CG_EntityEvent(), CG_PredictPlayerState(), and CG_TransitionSnapshot().
cg_noProjectileTrail
vmCvar_t cg_noProjectileTrail
Definition at line 184 of file cg_main.c.
Referenced by CG_BubbleTrail(), CG_PlasmaTrail(), and CG_RocketTrail().
cg_oldPlasma
vmCvar_t cg_oldPlasma
Definition at line 187 of file cg_main.c.
Referenced by CG_PlasmaTrail().
cg_oldRail
vmCvar_t cg_oldRail
Definition at line 185 of file cg_main.c.
Referenced by CG_RailTrail().
cg_oldRocket
vmCvar_t cg_oldRocket
Definition at line 186 of file cg_main.c.
Referenced by CG_MissileHitWall().
cg_paused
vmCvar_t cg_paused
Definition at line 154 of file cg_main.c.
Referenced by CG_Draw2D(), CG_DrawOldScoreboard(), and CG_DrawScoreboard().
cg_pmove_msec
vmCvar_t cg_pmove_msec
Definition at line 172 of file cg_main.c.
cg_predictItems
vmCvar_t cg_predictItems
Definition at line 156 of file cg_main.c.
Referenced by CG_TouchItem().
cg_railTrailTime
vmCvar_t cg_railTrailTime
Definition at line 93 of file cg_main.c.
Referenced by CG_RailTrail().
cg_runpitch
vmCvar_t cg_runpitch
Definition at line 95 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
cg_runroll
vmCvar_t cg_runroll
Definition at line 96 of file cg_main.c.
Referenced by CG_OffsetFirstPersonView().
cg_scorePlum
vmCvar_t cg_scorePlum
Definition at line 167 of file cg_main.c.
Referenced by CG_ScorePlum().
cg_shadows
vmCvar_t cg_shadows
Definition at line 101 of file cg_main.c.
Referenced by CG_Player(), CG_PlayerShadow(), and CG_PlayerSplash().
cg_showmiss
vmCvar_t cg_showmiss
Definition at line 125 of file cg_main.c.
Referenced by CG_CheckChangedPredictableEvents(), CG_MapRestart(), and CG_PredictPlayerState().
cg_simpleItems
vmCvar_t cg_simpleItems
Definition at line 140 of file cg_main.c.
Referenced by CG_Item().
cg_smoothClients
vmCvar_t cg_smoothClients
Definition at line 168 of file cg_main.c.
Referenced by CG_CalcEntityLerpPositions().
cg_stats
vmCvar_t cg_stats
Definition at line 151 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
cg_swingSpeed
vmCvar_t cg_swingSpeed
Definition at line 100 of file cg_main.c.
Referenced by CG_PlayerAngles().
cg_synchronousClients
vmCvar_t cg_synchronousClients
Definition at line 148 of file cg_main.c.
Referenced by CG_DrawLagometer(), CG_EntityEvent(), CG_PredictPlayerState(), and CG_TransitionSnapshot().
cg_teamChatHeight
vmCvar_t cg_teamChatHeight
Definition at line 150 of file cg_main.c.
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
cg_teamChatsOnly
vmCvar_t cg_teamChatsOnly
Definition at line 161 of file cg_main.c.
Referenced by CG_ServerCommand().
cg_teamChatTime
vmCvar_t cg_teamChatTime
Definition at line 149 of file cg_main.c.
Referenced by CG_AddToTeamChat(), and CG_DrawTeamInfo().
cg_teamOverlayUserinfo
vmCvar_t cg_teamOverlayUserinfo
Definition at line 159 of file cg_main.c.
cg_thirdPerson
vmCvar_t cg_thirdPerson
Definition at line 143 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
cg_thirdPersonAngle
vmCvar_t cg_thirdPersonAngle
Definition at line 145 of file cg_main.c.
Referenced by CG_CalcViewValues(), and CG_OffsetThirdPersonView().
cg_thirdPersonRange
vmCvar_t cg_thirdPersonRange
Definition at line 144 of file cg_main.c.
Referenced by CG_OffsetThirdPersonView().
cg_timescale
vmCvar_t cg_timescale
Definition at line 178 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
cg_timescaleFadeEnd
vmCvar_t cg_timescaleFadeEnd
Definition at line 176 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
cg_timescaleFadeSpeed
vmCvar_t cg_timescaleFadeSpeed
Definition at line 177 of file cg_main.c.
Referenced by CG_DrawActiveFrame().
cg_tracerChance
vmCvar_t cg_tracerChance
Definition at line 135 of file cg_main.c.
Referenced by CG_Bullet().
cg_tracerLength
vmCvar_t cg_tracerLength
Definition at line 137 of file cg_main.c.
Referenced by CG_Tracer().
cg_tracerWidth
vmCvar_t cg_tracerWidth
Definition at line 136 of file cg_main.c.
Referenced by CG_Tracer().
cg_trueLightning
vmCvar_t cg_trueLightning
Definition at line 188 of file cg_main.c.
Referenced by CG_LightningBolt().
cg_viewsize
vmCvar_t cg_viewsize
Definition at line 129 of file cg_main.c.
Referenced by CG_CalcVrect(), CG_SizeDown_f(), and CG_SizeUp_f().
cg_weapons
weaponInfo_t cg_weapons[MAX_WEAPONS]
Definition at line 89 of file cg_main.c.
Referenced by CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_DrawNewTeamInfo(), CG_DrawPlayerAmmoIcon(), CG_DrawSelectedPlayerWeapon(), CG_DrawStatusBar(), CG_DrawTeamOverlay(), CG_DrawWeaponSelect(), CG_FireWeapon(), CG_Grapple(), CG_Init(), CG_Item(), CG_Missile(), CG_RegisterGraphics(), and CG_RegisterWeapon().
cg_zoomFov
vmCvar_t cg_zoomFov
Definition at line 142 of file cg_main.c.
Referenced by CG_CalcFov().
cgs
cgs_t cgs
Definition at line 87 of file cg_main.c.
Referenced by CG_AddMarks(), CG_AddParticleToScene(), CG_AddPlayerWeapon(), CG_AddRefEntityWithPowerups(), CG_AddScorePlum(), CG_AddToTeamChat(), CG_AddViewWeapon(), CG_AddWeaponWithPowerups(), CG_AdjustFrom640(), CG_BigExplode(), CG_Bleed(), CG_BloodTrail(), CG_BubbleTrail(), CG_BuildSpectatorString(), CG_CalcFov(), CG_CalcVrect(), CG_CheckAmmo(), CG_CheckLocalSounds(), CG_CheckOrderPending(), CG_ClientNumFromName(), CG_ConfigString(), CG_ConfigStringModified(), CG_CustomSound(), CG_DamageBlendBlob(), CG_Draw1stPlace(), CG_Draw2D(), CG_Draw2ndPlace(), CG_DrawAttacker(), CG_DrawBlueFlagHead(), CG_DrawBlueFlagName(), CG_DrawBlueFlagStatus(), CG_DrawBlueScore(), CG_DrawCapFragLimit(), CG_DrawChar(), CG_DrawClientScore(), CG_DrawCrosshair(), CG_DrawCrosshair3D(), CG_DrawCrosshairNames(), CG_DrawCTFPowerUp(), CG_DrawField(), CG_DrawFlagModel(), CG_DrawFollow(), CG_DrawHead(), CG_DrawInformation(), CG_DrawIntermission(), CG_DrawLagometer(), CG_DrawLowerLeft(), CG_DrawLowerRight(), CG_DrawNewTeamInfo(), CG_DrawOldScoreboard(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerLocation(), CG_DrawPlayerStatus(), CG_DrawRedFlagHead(), CG_DrawRedFlagName(), CG_DrawRedFlagStatus(), CG_DrawRedScore(), CG_DrawScoreboard(), CG_DrawScores(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerLocation(), CG_DrawSelectedPlayerName(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), CG_DrawSides(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawStatusBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawTeamVote(), CG_DrawTimer(), CG_DrawTopBottom(), CG_DrawTourneyScoreboard(), CG_DrawUpperRight(), CG_DrawVote(), CG_DrawWarmup(), CG_DrawWeaponSelect(), CG_EntityEffects(), CG_EntityEvent(), CG_EventHandling(), CG_ExecuteNewServerCommands(), CG_FillRect(), CG_FindClientHeadFile(), CG_FindClientModelFile(), CG_FireWeapon(), CG_FragmentBounceMark(), CG_FragmentBounceSound(), CG_GameTypeString(), CG_General(), CG_GetGameStatusText(), CG_GetValue(), CG_GibPlayer(), CG_GrappleTrail(), CG_HarvesterSkulls(), CG_HasteTrail(), CG_Init(), CG_Item(), CG_KeyEvent(), CG_LightningBolt(), CG_LoadClientInfo(), CG_LoadDeferredPlayers(), CG_LoadingClient(), CG_MachineGunEjectBrass(), CG_MapRestart(), CG_Missile(), CG_MissileHitWall(), CG_MouseEvent(), CG_Mover(), CG_NewClientInfo(), CG_NewParticleArea(), CG_Obituary(), CG_OneFlagStatus(), CG_OtherTeamHasFlag(), CG_OwnerDrawVisible(), CG_ParseScores(), CG_ParseServerinfo(), CG_ParseTeamInfo(), CG_ParseWarmup(), CG_ParticleBloodCloud(), CG_ParticleBulletDebris(), CG_ParticleDust(), CG_ParticleSparks(), CG_PlasmaTrail(), CG_Player(), CG_PlayerAngles(), CG_PlayerAnimation(), CG_PlayerFlag(), CG_PlayerPowerups(), CG_PlayerShadow(), CG_PlayerSplash(), CG_PlayerSprites(), CG_PowerupTimerSounds(), CG_PredictPlayerState(), CG_RailTrail(), CG_ReadNextSnapshot(), CG_RegisterCvars(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_RegisterWeapon(), CG_ResetPlayerEntity(), CG_RocketTrail(), CG_ScanForExistingClientInfo(), CG_ServerCommand(), CG_SetConfigValues(), CG_SetDeferredClientInfo(), CG_SetEntitySoundPosition(), CG_SetSelectedPlayerName(), CG_ShotgunEjectBrass(), CG_ShotgunFire(), CG_SmokePuff(), CG_SpawnEffect(), CG_Speaker(), CG_StatusHandle(), CG_TeamBase(), CG_TeamScoreboard(), CG_TileClear(), CG_TouchItem(), CG_Tracer(), CG_UseItem(), CG_YourTeamHasFlag(), UI_DrawBannerString2(), UI_DrawProportionalString(), UI_DrawProportionalString2(), and vmMain().
cvarTable
cvarTable_t cvarTable[] static
Definition at line 211 of file cg_main.c.
Referenced by CG_RegisterCvars(), and CG_UpdateCvars().
cvarTableSize
int cvarTableSize = ARRAY_LEN(cvarTable) static
Definition at line 328 of file cg_main.c.
Referenced by CG_RegisterCvars(), and CG_UpdateCvars().
forceModelModificationCount
int forceModelModificationCount = -1
Definition at line 32 of file cg_main.c.
Referenced by CG_RegisterCvars(), and CG_UpdateCvars().
pmove_fixed
vmCvar_t pmove_fixed
Definition at line 169 of file cg_main.c.
pmove_msec
vmCvar_t pmove_msec
Definition at line 171 of file cg_main.c.