ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_precomp.h File Reference
l_precomp.h File Reference
Classes
struct define_s
struct indent_s
struct source_s
Macros
#define PATHSEPERATOR_STR "\\"
#define PATHSEPERATOR_CHAR '\\'
#define DEFINE_FIXED 0x0001
#define BUILTIN_LINE 1
#define BUILTIN_FILE 2
#define BUILTIN_DATE 3
#define BUILTIN_TIME 4
#define BUILTIN_STDC 5
#define INDENT_IF 0x0001
#define INDENT_ELSE 0x0002
#define INDENT_ELIF 0x0004
#define INDENT_IFDEF 0x0008
#define INDENT_IFNDEF 0x0010
Typedefs
typedef struct define_s define_t
typedef struct indent_s indent_t
typedef struct source_s source_t
Functions
int PC_ReadToken (source_t *source, token_t *token)
int PC_ExpectTokenString (source_t *source, char *string)
int PC_ExpectTokenType (source_t *source, int type, int subtype, token_t *token)
int PC_ExpectAnyToken (source_t *source, token_t *token)
int PC_CheckTokenString (source_t *source, char *string)
int PC_CheckTokenType (source_t *source, int type, int subtype, token_t *token)
int PC_SkipUntilString (source_t *source, char *string)
void PC_UnreadLastToken (source_t *source)
void PC_UnreadToken (source_t *source, token_t *token)
int PC_ReadLine (source_t *source, token_t *token)
int PC_WhiteSpaceBeforeToken (token_t *token)
int PC_AddDefine (source_t *source, char *string)
int PC_AddGlobalDefine (char *string)
int PC_RemoveGlobalDefine (char *name)
void PC_RemoveAllGlobalDefines (void)
void PC_AddBuiltinDefines (source_t *source)
void PC_SetIncludePath (source_t *source, char *path)
void PC_SetPunctuations (source_t *source, punctuation_t *p)
void PC_SetBaseFolder (char *path)
source_t * LoadSourceFile (const char *filename)
source_t * LoadSourceMemory (char *ptr, int length, char *name)
void FreeSource (source_t *source)
void QDECL SourceError (source_t *source, char *str,...) __attribute__((format(printf
void QDECL void QDECL SourceWarning (source_t *source, char *str,...) __attribute__((format(printf
void QDECL void QDECL int PC_LoadSourceHandle (const char *filename)
int PC_FreeSourceHandle (int handle)
int PC_ReadTokenHandle (int handle, pc_token_t *pc_token)
int PC_SourceFileAndLine (int handle, char *filename, int *line)
void PC_CheckOpenSourceHandles (void)
Macro Definition Documentation
BUILTIN_DATE
#define BUILTIN_DATE 3
Definition at line 56 of file l_precomp.h.
BUILTIN_FILE
#define BUILTIN_FILE 2
Definition at line 55 of file l_precomp.h.
BUILTIN_LINE
#define BUILTIN_LINE 1
Definition at line 54 of file l_precomp.h.
BUILTIN_STDC
#define BUILTIN_STDC 5
Definition at line 58 of file l_precomp.h.
BUILTIN_TIME
#define BUILTIN_TIME 4
Definition at line 57 of file l_precomp.h.
DEFINE_FIXED
#define DEFINE_FIXED 0x0001
Definition at line 52 of file l_precomp.h.
INDENT_ELIF
#define INDENT_ELIF 0x0004
Definition at line 62 of file l_precomp.h.
INDENT_ELSE
#define INDENT_ELSE 0x0002
Definition at line 61 of file l_precomp.h.
INDENT_IF
#define INDENT_IF 0x0001
Definition at line 60 of file l_precomp.h.
INDENT_IFDEF
#define INDENT_IFDEF 0x0008
Definition at line 63 of file l_precomp.h.
INDENT_IFNDEF
#define INDENT_IFNDEF 0x0010
Definition at line 64 of file l_precomp.h.
PATHSEPERATOR_CHAR
#define PATHSEPERATOR_CHAR '\\'
Definition at line 41 of file l_precomp.h.
PATHSEPERATOR_STR
#define PATHSEPERATOR_STR "\\"
Definition at line 34 of file l_precomp.h.
Typedef Documentation
define_t
typedef struct define_s define_t
indent_t
typedef struct indent_s indent_t
source_t
typedef struct source_s source_t
Function Documentation
FreeSource()
void FreeSource (source_t * source)
Definition at line 3056 of file l_precomp.c.
 {
     script_t *script;
     token_t *token;
     define_t *define;
     indent_t *indent;
     int i;
     //PC_PrintDefineHashTable(source->definehash);
     //free all the scripts
     while(source->scriptstack)
     {
         script = source->scriptstack;
         source->scriptstack = source->scriptstack->next;
         FreeScript(script);
     } //end for
     //free all the tokens
     while(source->tokens)
     {
         token = source->tokens;
         source->tokens = source->tokens->next;
         PC_FreeToken(token);
     } //end for
 #if DEFINEHASHING
     for (i = 0; i < DEFINEHASHSIZE; i++)
     {
         while(source->definehash[i])
         {
             define = source->definehash[i];
             source->definehash[i] = source->definehash[i]->hashnext;
             PC_FreeDefine(define);
         } //end while
     } //end for
 #else //DEFINEHASHING
     //free all defines
     while(source->defines)
     {
         define = source->defines;
         source->defines = source->defines->next;
         PC_FreeDefine(define);
     } //end for
 #endif //DEFINEHASHING
     //free all indents
     while(source->indentstack)
     {
         indent = source->indentstack;
         source->indentstack = source->indentstack->next;
         FreeMemory(indent);
     } //end for
 #if DEFINEHASHING
     //
     if (source->definehash) FreeMemory(source->definehash);
 #endif //DEFINEHASHING
     //free the source itself
     FreeMemory(source);
 } //end of the function FreeSource
References source_s::definehash, DEFINEHASHSIZE, source_s::defines, FreeMemory(), FreeScript(), define_s::hashnext, source_s::indentstack, define_s::next, indent_s::next, token_s::next, script_s::next, PC_FreeDefine(), PC_FreeToken(), source_s::scriptstack, and source_s::tokens.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), PC_FreeSourceHandle(), and ReadWeightConfig().
LoadSourceFile()
source_t* LoadSourceFile (const char * filename)
Definition at line 2989 of file l_precomp.c.
 {
     source_t *source;
     script_t *script;
     PC_InitTokenHeap();
     script = LoadScriptFile(filename);
     if (!script) return NULL;
     script->next = NULL;
     source = (source_t *) GetMemory(sizeof(source_t));
     Com_Memset(source, 0, sizeof(source_t));
     Q_strncpyz(source->filename, filename, sizeof(source->filename));
     source->scriptstack = script;
     source->tokens = NULL;
     source->defines = NULL;
     source->indentstack = NULL;
     source->skip = 0;
 #if DEFINEHASHING
     source->definehash = GetClearedMemory(DEFINEHASHSIZE * sizeof(define_t *));
 #endif //DEFINEHASHING
     PC_AddGlobalDefinesToSource(source);
     return source;
 } //end of the function LoadSourceFile
References Com_Memset, source_s::definehash, DEFINEHASHSIZE, source_s::defines, source_s::filename, GetClearedMemory(), GetMemory(), source_s::indentstack, LoadScriptFile(), script_s::next, NULL, PC_AddGlobalDefinesToSource(), PC_InitTokenHeap(), Q_strncpyz(), source_s::scriptstack, source_s::skip, and source_s::tokens.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), PC_LoadSourceHandle(), and ReadWeightConfig().
LoadSourceMemory()
source_t* LoadSourceMemory (char * ptr, int length, char * name)
Definition at line 3023 of file l_precomp.c.
 {
     source_t *source;
     script_t *script;
     PC_InitTokenHeap();
     script = LoadScriptMemory(ptr, length, name);
     if (!script) return NULL;
     script->next = NULL;
     source = (source_t *) GetMemory(sizeof(source_t));
     Com_Memset(source, 0, sizeof(source_t));
     Q_strncpyz(source->filename, name, sizeof(source->filename));
     source->scriptstack = script;
     source->tokens = NULL;
     source->defines = NULL;
     source->indentstack = NULL;
     source->skip = 0;
 #if DEFINEHASHING
     source->definehash = GetClearedMemory(DEFINEHASHSIZE * sizeof(define_t *));
 #endif //DEFINEHASHING
     PC_AddGlobalDefinesToSource(source);
     return source;
 } //end of the function LoadSourceMemory
References Com_Memset, source_s::definehash, DEFINEHASHSIZE, source_s::defines, source_s::filename, GetClearedMemory(), GetMemory(), source_s::indentstack, LoadScriptMemory(), script_s::next, NULL, PC_AddGlobalDefinesToSource(), PC_InitTokenHeap(), Q_strncpyz(), source_s::scriptstack, source_s::skip, and source_s::tokens.
PC_AddBuiltinDefines()
void PC_AddBuiltinDefines (source_t * source)
Definition at line 664 of file l_precomp.c.
 {
     int i;
     define_t *define;
     struct builtin
     {
         char *string;
         int builtin;
     } builtin[] = {
         { "__LINE__",   BUILTIN_LINE },
         { "__FILE__",   BUILTIN_FILE },
         { "__DATE__",   BUILTIN_DATE },
         { "__TIME__",   BUILTIN_TIME },
 //      { "__STDC__", BUILTIN_STDC },
         { NULL, 0 }
     };
     for (i = 0; builtin[i].string; i++)
     {
         define = (define_t *) GetMemory(sizeof(define_t));
         Com_Memset(define, 0, sizeof(define_t));
         define->name = (char *) GetMemory(strlen(builtin[i].string) + 1);
         strcpy(define->name, builtin[i].string);
         define->flags |= DEFINE_FIXED;
         define->builtin = builtin[i].builtin;
         //add the define to the source
 #if DEFINEHASHING
         PC_AddDefineToHash(define, source->definehash);
 #else
         define->next = source->defines;
         source->defines = define;
 #endif //DEFINEHASHING
     } //end for
 } //end of the function PC_AddBuiltinDefines
References define_s::builtin, BUILTIN_DATE, BUILTIN_FILE, BUILTIN_LINE, BUILTIN_TIME, Com_Memset, DEFINE_FIXED, source_s::definehash, source_s::defines, define_s::flags, GetMemory(), define_s::name, define_s::next, NULL, and PC_AddDefineToHash().
PC_AddDefine()
int PC_AddDefine (source_t * source, char * string)
Definition at line 1371 of file l_precomp.c.
 {
     define_t *define;
     define = PC_DefineFromString(string);
     if (!define) return qfalse;
 #if DEFINEHASHING
     PC_AddDefineToHash(define, source->definehash);
 #else //DEFINEHASHING
     define->next = source->defines;
     source->defines = define;
 #endif //DEFINEHASHING
     return qtrue;
 } //end of the function PC_AddDefine
References source_s::definehash, source_s::defines, define_s::next, PC_AddDefineToHash(), PC_DefineFromString(), qfalse, and qtrue.
PC_AddGlobalDefine()
int PC_AddGlobalDefine (char * string)
Definition at line 1392 of file l_precomp.c.
 {
     define_t *define;
     define = PC_DefineFromString(string);
     if (!define) return qfalse;
     define->next = globaldefines;
     globaldefines = define;
     return qtrue;
 } //end of the function PC_AddGlobalDefine
References globaldefines, define_s::next, PC_DefineFromString(), qfalse, and qtrue.
Referenced by GetBotLibAPI().
PC_CheckOpenSourceHandles()
void PC_CheckOpenSourceHandles (void)
Definition at line 3221 of file l_precomp.c.
 {
     int i;
     for (i = 1; i < MAX_SOURCEFILES; i++)
     {
         if (sourceFiles[i])
         {
 #ifdef BOTLIB
             botimport.Print(PRT_ERROR, "file %s still open in precompiler\n", sourceFiles[i]->scriptstack->filename);
 #endif  //BOTLIB
         } //end if
     } //end for
 } //end of the function PC_CheckOpenSourceHandles
References botimport, source_s::filename, MAX_SOURCEFILES, PRT_ERROR, and sourceFiles.
Referenced by Export_BotLibShutdown().
PC_CheckTokenString()
int PC_CheckTokenString (source_t * source, char * string)
Definition at line 2884 of file l_precomp.c.
 {
     token_t tok;
     if (!PC_ReadToken(source, &tok)) return qfalse;
     //if the token is available
     if (!strcmp(tok.string, string)) return qtrue;
     //
     PC_UnreadSourceToken(source, &tok);
     return qfalse;
 } //end of the function PC_CheckTokenString
References PC_ReadToken(), PC_UnreadSourceToken(), qfalse, qtrue, and token_s::string.
Referenced by BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), PC_Directive_define(), ReadFuzzyWeight(), and ReadStructure().
PC_CheckTokenType()
int PC_CheckTokenType (source_t * source, int type, int subtype, token_t * token)
Definition at line 2901 of file l_precomp.c.
 {
     token_t tok;
     if (!PC_ReadToken(source, &tok)) return qfalse;
     //if the type matches
     if (tok.type == type &&
             (tok.subtype & subtype) == subtype)
     {
         Com_Memcpy(token, &tok, sizeof(token_t));
         return qtrue;
     } //end if
     //
     PC_UnreadSourceToken(source, &tok);
     return qfalse;
 } //end of the function PC_CheckTokenType
References Com_Memcpy, PC_ReadToken(), PC_UnreadSourceToken(), qfalse, qtrue, token_s::subtype, and token_s::type.
PC_ExpectAnyToken()
int PC_ExpectAnyToken (source_t * source, token_t * token)
Definition at line 2866 of file l_precomp.c.
 {
     if (!PC_ReadToken(source, token))
     {
         SourceError(source, "couldn't read expected token");
         return qfalse;
     } //end if
     else
     {
         return qtrue;
     } //end else
 } //end of the function PC_ExpectAnyToken
References PC_ReadToken(), qfalse, qtrue, and SourceError().
Referenced by BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), ReadChar(), ReadFuzzySeperators_r(), ReadNumber(), ReadStructure(), ReadValue(), and ReadWeightConfig().
PC_ExpectTokenString()
int PC_ExpectTokenString (source_t * source, char * string)
Definition at line 2789 of file l_precomp.c.
 {
     token_t token;
     if (!PC_ReadToken(source, &token))
     {
         SourceError(source, "couldn't find expected %s", string);
         return qfalse;
     } //end if
     if (strcmp(token.string, string))
     {
         SourceError(source, "expected %s, found %s", string, token.string);
         return qfalse;
     } //end if
     return qtrue;
 } //end of the function PC_ExpectTokenString
References PC_ReadToken(), qfalse, qtrue, SourceError(), and token_s::string.
Referenced by BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), ReadFuzzySeperators_r(), ReadFuzzyWeight(), ReadStructure(), and ReadWeightConfig().
PC_ExpectTokenType()
int PC_ExpectTokenType (source_t * source, int type, int subtype, token_t * token)
Definition at line 2812 of file l_precomp.c.
 {
     char str[MAX_TOKEN];
     if (!PC_ReadToken(source, token))
     {
         SourceError(source, "couldn't read expected token");
         return qfalse;
     } //end if
     if (token->type != type)
     {
         strcpy(str, "");
         if (type == TT_STRING) strcpy(str, "string");
         if (type == TT_LITERAL) strcpy(str, "literal");
         if (type == TT_NUMBER) strcpy(str, "number");
         if (type == TT_NAME) strcpy(str, "name");
         if (type == TT_PUNCTUATION) strcpy(str, "punctuation");
         SourceError(source, "expected a %s, found %s", str, token->string);
         return qfalse;
     } //end if
     if (token->type == TT_NUMBER)
     {
         if ((token->subtype & subtype) != subtype)
         {
             strcpy(str, "");
             if (subtype & TT_DECIMAL) strcpy(str, "decimal");
             if (subtype & TT_HEX) strcpy(str, "hex");
             if (subtype & TT_OCTAL) strcpy(str, "octal");
             if (subtype & TT_BINARY) strcpy(str, "binary");
             if (subtype & TT_LONG) strcat(str, " long");
             if (subtype & TT_UNSIGNED) strcat(str, " unsigned");
             if (subtype & TT_FLOAT) strcat(str, " float");
             if (subtype & TT_INTEGER) strcat(str, " integer");
             SourceError(source, "expected %s, found %s", str, token->string);
             return qfalse;
         } //end if
     } //end if
     else if (token->type == TT_PUNCTUATION)
     {
         if (token->subtype != subtype)
         {
             SourceError(source, "found %s", token->string);
             return qfalse;
         } //end if
     } //end else if
     return qtrue;
 } //end of the function PC_ExpectTokenType
References MAX_TOKEN, PC_ReadToken(), qfalse, qtrue, SourceError(), token_s::string, token_s::subtype, TT_BINARY, TT_DECIMAL, TT_FLOAT, TT_HEX, TT_INTEGER, TT_LITERAL, TT_LONG, TT_NAME, TT_NUMBER, TT_OCTAL, TT_PUNCTUATION, TT_STRING, TT_UNSIGNED, and token_s::type.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), ReadFuzzySeperators_r(), ReadString(), and ReadWeightConfig().
PC_FreeSourceHandle()
int PC_FreeSourceHandle (int handle)
Definition at line 3148 of file l_precomp.c.
 {
     if (handle < 1 || handle >= MAX_SOURCEFILES)
         return qfalse;
     if (!sourceFiles[handle])
         return qfalse;
     FreeSource(sourceFiles[handle]);
     sourceFiles[handle] = NULL;
     return qtrue;
 } //end of the function PC_FreeSourceHandle
References FreeSource(), MAX_SOURCEFILES, NULL, qfalse, qtrue, and sourceFiles.
Referenced by GetBotLibAPI().
PC_LoadSourceHandle()
void QDECL void QDECL int PC_LoadSourceHandle (const char * filename)
Definition at line 3123 of file l_precomp.c.
 {
     source_t *source;
     int i;
     for (i = 1; i < MAX_SOURCEFILES; i++)
     {
         if (!sourceFiles[i])
             break;
     } //end for
     if (i >= MAX_SOURCEFILES)
         return 0;
     PS_SetBaseFolder("");
     source = LoadSourceFile(filename);
     if (!source)
         return 0;
     sourceFiles[i] = source;
     return i;
 } //end of the function PC_LoadSourceHandle
References LoadSourceFile(), MAX_SOURCEFILES, PS_SetBaseFolder(), and sourceFiles.
Referenced by GetBotLibAPI().
PC_ReadLine()
int PC_ReadLine (source_t * source, token_t * token)
Definition at line 1062 of file l_precomp.c.
 {
     int crossline;
     crossline = 0;
     do
     {
         if (!PC_ReadSourceToken(source, token)) return qfalse;
         if (token->linescrossed > crossline)
         {
             PC_UnreadSourceToken(source, token);
             return qfalse;
         } //end if
         crossline = 1;
     } while(!strcmp(token->string, "\\"));
     return qtrue;
 } //end of the function PC_ReadLine
References token_s::linescrossed, PC_ReadSourceToken(), PC_UnreadSourceToken(), qfalse, qtrue, and token_s::string.
Referenced by PC_Directive_define(), PC_Directive_if_def(), PC_Directive_pragma(), PC_Directive_undef(), and PC_Evaluate().
PC_ReadToken()
int PC_ReadToken (source_t * source, token_t * token)
Definition at line 2706 of file l_precomp.c.
 {
     define_t *define;
     while(1)
     {
         if (!PC_ReadSourceToken(source, token)) return qfalse;
         //check for precompiler directives
         if (token->type == TT_PUNCTUATION && *token->string == '#')
         {
 #ifdef QUAKEC
             if (!BuiltinFunction(source))
 #endif //QUAKC
             {
                 //read the precompiler directive
                 if (!PC_ReadDirective(source)) return qfalse;
                 continue;
             } //end if
         } //end if
         if (token->type == TT_PUNCTUATION && *token->string == '$')
         {
 #ifdef QUAKEC
             if (!QuakeCMacro(source))
 #endif //QUAKEC
             {
                 //read the precompiler directive
                 if (!PC_ReadDollarDirective(source)) return qfalse;
                 continue;
             } //end if
         } //end if
         // recursively concatenate strings that are behind each other still resolving defines
         if (token->type == TT_STRING)
         {
             token_t newtoken;
             if (PC_ReadToken(source, &newtoken))
             {
                 if (newtoken.type == TT_STRING)
                 {
                     token->string[strlen(token->string)-1] = '\0';
                     if (strlen(token->string) + strlen(newtoken.string+1) + 1 >= MAX_TOKEN)
                     {
                         SourceError(source, "string longer than MAX_TOKEN %d", MAX_TOKEN);
                         return qfalse;
                     }
                     strcat(token->string, newtoken.string+1);
                 }
                 else
                 {
                     PC_UnreadToken(source, &newtoken);
                 }
             }
         } //end if
         //if skipping source because of conditional compilation
         if (source->skip) continue;
         //if the token is a name
         if (token->type == TT_NAME)
         {
             //check if the name is a define macro
 #if DEFINEHASHING
             define = PC_FindHashedDefine(source->definehash, token->string);
 #else
             define = PC_FindDefine(source->defines, token->string);
 #endif //DEFINEHASHING
             //if it is a define macro
             if (define)
             {
                 //expand the defined macro
                 if (!PC_ExpandDefineIntoSource(source, token, define)) return qfalse;
                 continue;
             } //end if
         } //end if
         //copy token for unreading
         Com_Memcpy(&source->token, token, sizeof(token_t));
         //found a token
         return qtrue;
     } //end while
 } //end of the function PC_ReadToken
References Com_Memcpy, source_s::definehash, source_s::defines, MAX_TOKEN, PC_ExpandDefineIntoSource(), PC_FindDefine(), PC_FindHashedDefine(), PC_ReadDirective(), PC_ReadDollarDirective(), PC_ReadSourceToken(), PC_ReadToken(), PC_UnreadToken(), qfalse, qtrue, source_s::skip, SourceError(), token_s::string, source_s::token, TT_NAME, TT_PUNCTUATION, TT_STRING, and token_s::type.
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), PC_CheckTokenString(), PC_CheckTokenType(), PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_ReadTokenHandle(), PC_SkipUntilString(), and ReadWeightConfig().
PC_ReadTokenHandle()
int PC_ReadTokenHandle (int handle, pc_token_t * pc_token)
Definition at line 3165 of file l_precomp.c.
 {
     token_t token;
     int ret;
     if (handle < 1 || handle >= MAX_SOURCEFILES)
         return 0;
     if (!sourceFiles[handle])
         return 0;
     ret = PC_ReadToken(sourceFiles[handle], &token);
     strcpy(pc_token->string, token.string);
     pc_token->type = token.type;
     pc_token->subtype = token.subtype;
     pc_token->intvalue = token.intvalue;
     pc_token->floatvalue = token.floatvalue;
     if (pc_token->type == TT_STRING)
         StripDoubleQuotes(pc_token->string);
     return ret;
 } //end of the function PC_ReadTokenHandle
References token_s::floatvalue, pc_token_s::floatvalue, token_s::intvalue, pc_token_s::intvalue, MAX_SOURCEFILES, PC_ReadToken(), sourceFiles, token_s::string, pc_token_s::string, StripDoubleQuotes(), token_s::subtype, pc_token_s::subtype, TT_STRING, token_s::type, and pc_token_s::type.
Referenced by GetBotLibAPI().
PC_RemoveAllGlobalDefines()
void PC_RemoveAllGlobalDefines (void)
Definition at line 1428 of file l_precomp.c.
 {
     define_t *define;
     for (define = globaldefines; define; define = globaldefines)
     {
         globaldefines = globaldefines->next;
         PC_FreeDefine(define);
     } //end for
 } //end of the function PC_RemoveAllGlobalDefines
References globaldefines, define_s::next, and PC_FreeDefine().
Referenced by Export_BotLibShutdown().
PC_RemoveGlobalDefine()
int PC_RemoveGlobalDefine (char * name)
Definition at line 1409 of file l_precomp.c.
 {
     define_t *define;
     define = PC_FindDefine(globaldefines, name);
     if (define)
     {
         PC_FreeDefine(define);
         return qtrue;
     } //end if
     return qfalse;
 } //end of the function PC_RemoveGlobalDefine
References globaldefines, PC_FindDefine(), PC_FreeDefine(), qfalse, and qtrue.
PC_SetBaseFolder()
void PC_SetBaseFolder (char * path)
Definition at line 3211 of file l_precomp.c.
 {
     PS_SetBaseFolder(path);
 } //end of the function PC_SetBaseFolder
References PS_SetBaseFolder().
Referenced by BotLoadCharacterFromFile(), BotLoadInitialChat(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), LoadWeaponConfig(), and ReadWeightConfig().
PC_SetIncludePath()
void PC_SetIncludePath (source_t * source, char * path)
Definition at line 2959 of file l_precomp.c.
 {
     size_t len;
     Q_strncpyz(source->includepath, path, sizeof(source->includepath)-1);
     len = strlen(source->includepath);
     //add trailing path seperator
     if (len > 0 && source->includepath[len-1] != '\\' &&
         source->includepath[len-1] != '/')
     {
         strcat(source->includepath, PATHSEPERATOR_STR);
     } //end if
 } //end of the function PC_SetIncludePath
References source_s::includepath, PATHSEPERATOR_STR, and Q_strncpyz().
PC_SetPunctuations()
void PC_SetPunctuations (source_t * source, punctuation_t * p)
Definition at line 2979 of file l_precomp.c.
 {
     source->punctuations = p;
 } //end of the function PC_SetPunctuations
References source_s::punctuations.
PC_SkipUntilString()
int PC_SkipUntilString (source_t * source, char * string)
Definition at line 2923 of file l_precomp.c.
 {
     token_t token;
     while(PC_ReadToken(source, &token))
     {
         if (!strcmp(token.string, string)) return qtrue;
     } //end while
     return qfalse;
 } //end of the function PC_SkipUntilString
References PC_ReadToken(), qfalse, qtrue, and token_s::string.
PC_SourceFileAndLine()
int PC_SourceFileAndLine (int handle, char * filename, int * line)
Definition at line 3191 of file l_precomp.c.
 {
     if (handle < 1 || handle >= MAX_SOURCEFILES)
         return qfalse;
     if (!sourceFiles[handle])
         return qfalse;
     strcpy(filename, sourceFiles[handle]->filename);
     if (sourceFiles[handle]->scriptstack)
         *line = sourceFiles[handle]->scriptstack->line;
     else
         *line = 0;
     return qtrue;
 } //end of the function PC_SourceFileAndLine
References script_s::line, MAX_SOURCEFILES, qfalse, qtrue, source_s::scriptstack, and sourceFiles.
Referenced by GetBotLibAPI().
PC_UnreadLastToken()
void PC_UnreadLastToken (source_t * source)
Definition at line 2939 of file l_precomp.c.
 {
     PC_UnreadSourceToken(source, &source->token);
 } //end of the function PC_UnreadLastToken
References PC_UnreadSourceToken(), and source_s::token.
Referenced by BotLoadMatchTemplates(), and ReadChar().
PC_UnreadToken()
void PC_UnreadToken (source_t * source, token_t * token)
Definition at line 2949 of file l_precomp.c.
 {
     PC_UnreadSourceToken(source, token);
 } //end of the function PC_UnreadToken
References PC_UnreadSourceToken().
Referenced by PC_ReadToken().
PC_WhiteSpaceBeforeToken()
int PC_WhiteSpaceBeforeToken (token_t * token)
Definition at line 1086 of file l_precomp.c.
 {
     return token->endwhitespace_p - token->whitespace_p > 0;
 } //end of the function PC_WhiteSpaceBeforeToken
References token_s::endwhitespace_p, and token_s::whitespace_p.
Referenced by PC_Directive_define().
SourceError()
void QDECL SourceError (source_t * source, char * str, ...)
SourceWarning()
void QDECL void QDECL SourceWarning (source_t * source, char * str, ...)