ioquake3 doxygen: C:/entry/dev/ioq3/code/cgame/cg_drawtools.c File Reference
cg_drawtools.c File Reference
#include "cg_local.h"
Macros
#define PROPB_GAP_WIDTH 4
#define PROPB_SPACE_WIDTH 12
#define PROPB_HEIGHT 36
Functions
void CG_AdjustFrom640 (float *x, float *y, float *w, float *h)
void CG_FillRect (float x, float y, float width, float height, const float *color)
void CG_DrawSides (float x, float y, float w, float h, float size)
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
void CG_DrawRect (float x, float y, float width, float height, float size, const float *color)
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
void CG_DrawChar (int x, int y, int width, int height, int ch)
void CG_DrawStringExt (int x, int y, const char *string, const float *setColor, qboolean forceColor, qboolean shadow, int charWidth, int charHeight, int maxChars)
void CG_DrawBigString (int x, int y, const char *s, float alpha)
void CG_DrawBigStringColor (int x, int y, const char *s, vec4_t color)
void CG_DrawSmallString (int x, int y, const char *s, float alpha)
void CG_DrawSmallStringColor (int x, int y, const char *s, vec4_t color)
int CG_DrawStrlen (const char *str)
static void CG_TileClearBox (int x, int y, int w, int h, qhandle_t hShader)
void CG_TileClear (void)
float * CG_FadeColor (int startMsec, int totalMsec)
float * CG_TeamColor (int team)
void CG_GetColorForHealth (int health, int armor, vec4_t hcolor)
void CG_ColorForHealth (vec4_t hcolor)
static void UI_DrawBannerString2 (int x, int y, const char *str, vec4_t color)
void UI_DrawBannerString (int x, int y, const char *str, int style, vec4_t color)
int UI_ProportionalStringWidth (const char *str)
static void UI_DrawProportionalString2 (int x, int y, const char *str, vec4_t color, float sizeScale, qhandle_t charset)
float UI_ProportionalSizeScale (int style)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
Variables
static int propMap [128][3]
static int propMapB [26][3]
Macro Definition Documentation
PROPB_GAP_WIDTH
#define PROPB_GAP_WIDTH 4
Definition at line 600 of file cg_drawtools.c.
PROPB_HEIGHT
#define PROPB_HEIGHT 36
Definition at line 602 of file cg_drawtools.c.
PROPB_SPACE_WIDTH
#define PROPB_SPACE_WIDTH 12
Definition at line 601 of file cg_drawtools.c.
Function Documentation
CG_AdjustFrom640()
void CG_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 33 of file cg_drawtools.c.
 {
 #if 0
     // adjust for wide screens
     if (cgs.glconfig.vidWidth * 480 > cgs.glconfig.vidHeight * 640) {
         *x += 0.5 * (cgs.glconfig.vidWidth - (cgs.glconfig.vidHeight * 640 / 480));
     }
 #endif
     // scale for screen sizes
     * x *= cgs.screenXScale;
     *y *= cgs.screenYScale;
     *w *= cgs.screenXScale;
     *h *= cgs.screenYScale;
 }
References cgs, cgs_t::glconfig, cgs_t::screenXScale, cgs_t::screenYScale, glconfig_t::vidHeight, and glconfig_t::vidWidth.
Referenced by CG_Draw3DModel(), CG_DrawChar(), CG_DrawCrosshair(), CG_DrawLagometer(), CG_DrawPic(), CG_DrawSides(), CG_DrawTopBottom(), CG_FillRect(), and CG_ShowResponseHead().
CG_ColorForHealth()
void CG_ColorForHealth (vec4_t hcolor)
Definition at line 445 of file cg_drawtools.c.
 {
     CG_GetColorForHealth(cg.snap->ps.stats[STAT_HEALTH],
         cg.snap->ps.stats[STAT_ARMOR], hcolor);
 }
References cg, CG_GetColorForHealth(), snapshot_t::ps, cg_t::snap, STAT_ARMOR, STAT_HEALTH, and playerState_s::stats.
Referenced by CG_DrawCrosshair(), and CG_DrawStatusBar().
CG_DrawBigString()
void CG_DrawBigString (int x, int y, const char * s, float alpha)
Definition at line 225 of file cg_drawtools.c.
 {
     float    color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     CG_DrawStringExt(x, y, s, color, qfalse, qtrue, BIGCHAR_WIDTH, BIGCHAR_HEIGHT, 0);
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, CG_DrawStringExt(), qfalse, qtrue, and s.
Referenced by CG_DrawAmmoWarning(), CG_DrawAttacker(), CG_DrawClientScore(), CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawLagometer(), CG_DrawOldScoreboard(), CG_DrawPickupItem(), CG_DrawScores(), CG_DrawSnapshot(), CG_DrawSpectator(), CG_DrawTimer(), and CG_DrawWarmup().
CG_DrawBigStringColor()
void CG_DrawBigStringColor (int x, int y, const char * s, vec4_t color)
Definition at line 234 of file cg_drawtools.c.
 {
     CG_DrawStringExt(x, y, s, color, qtrue, qtrue, BIGCHAR_WIDTH, BIGCHAR_HEIGHT, 0);
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, CG_DrawStringExt(), qtrue, and s.
Referenced by CG_DrawClientScore(), and CG_DrawWeaponSelect().
CG_DrawChar()
void CG_DrawChar (int x, int y, int width, int height, int ch)
Definition at line 128 of file cg_drawtools.c.
 {
     int row, col;
     float frow, fcol;
     float size;
     float    ax, ay, aw, ah;
     ch &= 255;
     if (ch == ' ') {
         return;
     }
     ax = x;
     ay = y;
     aw = width;
     ah = height;
     CG_AdjustFrom640(&ax, &ay, &aw, &ah);
     row = ch >> 4;
     col = ch & 15;
     frow = row * 0.0625;
     fcol = col * 0.0625;
     size = 0.0625;
     trap_R_DrawStretchPic(ax, ay, aw, ah,
         fcol, frow,
         fcol + size, frow + size,
         cgs.media.charsetShader);
 }
References CG_AdjustFrom640(), cgs, cgMedia_t::charsetShader, cgs_t::media, and trap_R_DrawStretchPic().
Referenced by CG_DrawStringExt().
CG_DrawPic()
void CG_DrawPic (float x, float y, float width, float height, qhandle_t hShader)
Definition at line 113 of file cg_drawtools.c.
 {
     CG_AdjustFrom640(&x, &y, &width, &height);
     trap_R_DrawStretchPic(x, y, width, height, 0, 0, 1, 1, hShader);
 }
References CG_AdjustFrom640(), and trap_R_DrawStretchPic().
Referenced by CG_DrawAreaPowerUp(), CG_DrawBlueFlagStatus(), CG_DrawClientScore(), CG_DrawCTFPowerUp(), CG_DrawDisconnect(), CG_DrawField(), CG_DrawFlagModel(), CG_DrawHead(), CG_DrawHoldableItem(), CG_DrawInformation(), CG_DrawLagometer(), CG_DrawLoadingIcons(), CG_DrawMedal(), CG_DrawNewTeamInfo(), CG_DrawOldScoreboard(), CG_DrawPickupItem(), CG_DrawPlayerAmmoIcon(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorIcon(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerItem(), CG_DrawPlayerScore(), CG_DrawPlayerStatus(), CG_DrawPowerups(), CG_DrawRedFlagStatus(), CG_DrawReward(), CG_DrawScores(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHead(), CG_DrawSelectedPlayerHealth(), CG_DrawSelectedPlayerPowerup(), CG_DrawSelectedPlayerStatus(), CG_DrawSelectedPlayerWeapon(), CG_DrawStatusBar(), CG_DrawTeamBackground(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawWeaponSelect(), CG_HarvesterSkulls(), and CG_OneFlagStatus().
CG_DrawRect()
void CG_DrawRect (float x, float y, float width, float height, float size, const float * color)
Definition at line 94 of file cg_drawtools.c.
 {
     trap_R_SetColor(color);
     CG_DrawTopBottom(x, y, width, height, size);
     CG_DrawSides(x, y + size, width, height - size * 2, size);
     trap_R_SetColor(NULL);
 }
References CG_DrawSides(), CG_DrawTopBottom(), NULL, and trap_R_SetColor().
CG_DrawSides()
void CG_DrawSides (float x, float y, float w, float h, float size)
Definition at line 72 of file cg_drawtools.c.
 {
     CG_AdjustFrom640(&x, &y, &w, &h);
     size *= cgs.screenXScale;
     trap_R_DrawStretchPic(x, y, size, h, 0, 0, 0, 0, cgs.media.whiteShader);
     trap_R_DrawStretchPic(x + w - size, y, size, h, 0, 0, 0, 0, cgs.media.whiteShader);
 }
References CG_AdjustFrom640(), cgs, cgs_t::media, cgs_t::screenXScale, trap_R_DrawStretchPic(), and cgMedia_t::whiteShader.
Referenced by CG_DrawRect().
CG_DrawSmallString()
void CG_DrawSmallString (int x, int y, const char * s, float alpha)
Definition at line 239 of file cg_drawtools.c.
 {
     float    color[4];
     color[0] = color[1] = color[2] = 1.0;
     color[3] = alpha;
     CG_DrawStringExt(x, y, s, color, qfalse, qfalse, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT, 0);
 }
References CG_DrawStringExt(), qfalse, s, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by CG_DrawTeamVote(), and CG_DrawVote().
CG_DrawSmallStringColor()
void CG_DrawSmallStringColor (int x, int y, const char * s, vec4_t color)
Definition at line 248 of file cg_drawtools.c.
 {
     CG_DrawStringExt(x, y, s, color, qtrue, qfalse, SMALLCHAR_WIDTH, SMALLCHAR_HEIGHT, 0);
 }
References CG_DrawStringExt(), qfalse, qtrue, s, SMALLCHAR_HEIGHT, and SMALLCHAR_WIDTH.
Referenced by CG_DrawClientScore().
CG_DrawStringExt()
void CG_DrawStringExt (int x, int y, const char * string, const float * setColor, qboolean forceColor, qboolean shadow, int charWidth, int charHeight, int maxChars)
Definition at line 171 of file cg_drawtools.c.
 {
     vec4_t        color;
     const char* s;
     int            xx;
     int            cnt;
     if (maxChars <= 0)
         maxChars = 32767; // do them all!
     // draw the drop shadow
     if (shadow) {
         color[0] = color[1] = color[2] = 0;
         color[3] = setColor[3];
         trap_R_SetColor(color);
         s = string;
         xx = x;
         cnt = 0;
         while (*s && cnt < maxChars) {
             if (Q_IsColorString(s)) {
                 s += 2;
                 continue;
             }
             CG_DrawChar(xx + 2, y + 2, charWidth, charHeight, *s);
             cnt++;
             xx += charWidth;
             s++;
         }
     }
     // draw the colored text
     s = string;
     xx = x;
     cnt = 0;
     trap_R_SetColor(setColor);
     while (*s && cnt < maxChars) {
         if (Q_IsColorString(s)) {
             if (!forceColor) {
                 memcpy(color, g_color_table[ColorIndex(*(s + 1))], sizeof(color));
                 color[3] = setColor[3];
                 trap_R_SetColor(color);
             }
             s += 2;
             continue;
         }
         CG_DrawChar(xx, y, charWidth, charHeight, *s);
         xx += charWidth;
         cnt++;
         s++;
     }
     trap_R_SetColor(NULL);
 }
References CG_DrawChar(), ColorIndex, g_color_table, NULL, Q_IsColorString(), s, and trap_R_SetColor().
Referenced by CG_CenterGiantLine(), CG_DrawBigString(), CG_DrawBigStringColor(), CG_DrawCenterString(), CG_DrawFollow(), CG_DrawReward(), CG_DrawSmallString(), CG_DrawSmallStringColor(), CG_DrawTeamInfo(), CG_DrawTeamOverlay(), CG_DrawTourneyScoreboard(), and CG_DrawWarmup().
CG_DrawStrlen()
int CG_DrawStrlen (const char * str)
Definition at line 260 of file cg_drawtools.c.
 {
     const char* s = str;
     int count = 0;
     while (*s) {
         if (Q_IsColorString(s)) {
             s += 2;
         } else {
             count++;
             s++;
         }
     }
     return count;
 }
References count, Q_IsColorString(), and s.
Referenced by CG_CenterGiantLine(), CG_DrawAmmoWarning(), CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawDisconnect(), CG_DrawFollow(), CG_DrawFPS(), CG_DrawOldScoreboard(), CG_DrawReward(), CG_DrawScores(), CG_DrawSnapshot(), CG_DrawTeamOverlay(), CG_DrawTimer(), CG_DrawWarmup(), and CG_DrawWeaponSelect().
CG_DrawTopBottom()
void CG_DrawTopBottom (float x, float y, float w, float h, float size)
Definition at line 80 of file cg_drawtools.c.
 {
     CG_AdjustFrom640(&x, &y, &w, &h);
     size *= cgs.screenYScale;
     trap_R_DrawStretchPic(x, y, w, size, 0, 0, 0, 0, cgs.media.whiteShader);
     trap_R_DrawStretchPic(x, y + h - size, w, size, 0, 0, 0, 0, cgs.media.whiteShader);
 }
References CG_AdjustFrom640(), cgs, cgs_t::media, cgs_t::screenYScale, trap_R_DrawStretchPic(), and cgMedia_t::whiteShader.
Referenced by CG_DrawRect().
CG_FadeColor()
float* CG_FadeColor (int startMsec, int totalMsec)
Definition at line 343 of file cg_drawtools.c.
 {
     static vec4_t        color;
     int            t;
     if (startMsec == 0) {
         return NULL;
     }
     t = cg.time - startMsec;
     if (t >= totalMsec) {
         return NULL;
     }
     // fade out
     if (totalMsec - t < FADE_TIME) {
         color[3] = (totalMsec - t) * 1.0 / FADE_TIME;
     } else {
         color[3] = 1.0;
     }
     color[0] = color[1] = color[2] = 1;
     return color;
 }
References cg, FADE_TIME, NULL, t, and cg_t::time.
Referenced by CG_DrawCenterString(), CG_DrawCrosshairNames(), CG_DrawOldScoreboard(), CG_DrawPickupItem(), CG_DrawReward(), CG_DrawScoreboard(), and CG_DrawWeaponSelect().
CG_FillRect()
void CG_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 55 of file cg_drawtools.c.
 {
     trap_R_SetColor(color);
     CG_AdjustFrom640(&x, &y, &width, &height);
     trap_R_DrawStretchPic(x, y, width, height, 0, 0, 0, 0, cgs.media.whiteShader);
     trap_R_SetColor(NULL);
 }
References CG_AdjustFrom640(), cgs, cgs_t::media, NULL, trap_R_DrawStretchPic(), trap_R_SetColor(), and cgMedia_t::whiteShader.
Referenced by CG_DrawClientScore(), CG_DrawScores(), and CG_DrawTourneyScoreboard().
CG_GetColorForHealth()
void CG_GetColorForHealth (int health, int armor, vec4_t hcolor)
Definition at line 401 of file cg_drawtools.c.
 {
     int        count;
     int        max;
     // calculate the total points of damage that can
     // be sustained at the current health / armor level
     if (health <= 0) {
         VectorClear(hcolor);    // black
         hcolor[3] = 1;
         return;
     }
     count = armor;
     max = health * ARMOR_PROTECTION / (1.0 - ARMOR_PROTECTION);
     if (max < count) {
         count = max;
     }
     health += count;
     // set the color based on health
     hcolor[0] = 1.0;
     hcolor[3] = 1.0;
     if (health >= 100) {
         hcolor[2] = 1.0;
     } else if (health < 66) {
         hcolor[2] = 0;
     } else {
         hcolor[2] = (health - 66) / 33.0;
     }
     if (health > 60) {
         hcolor[1] = 1.0;
     } else if (health < 30) {
         hcolor[1] = 0;
     } else {
         hcolor[1] = (health - 30) / 30.0;
     }
 }
References ARMOR_PROTECTION, count, and VectorClear.
Referenced by CG_ColorForHealth(), CG_DrawNewTeamInfo(), and CG_DrawTeamOverlay().
CG_TeamColor()
float* CG_TeamColor (int team)
Definition at line 375 of file cg_drawtools.c.
 {
     static vec4_t    red = { 1, 0.2f, 0.2f, 1 };
     static vec4_t    blue = { 0.2f, 0.2f, 1, 1 };
     static vec4_t    other = { 1, 1, 1, 1 };
     static vec4_t    spectator = { 0.7f, 0.7f, 0.7f, 1 };
     switch (team) {
     case TEAM_RED:
         return red;
     case TEAM_BLUE:
         return blue;
     case TEAM_SPECTATOR:
         return spectator;
     default:
         return other;
     }
 }
References TEAM_BLUE, TEAM_RED, and TEAM_SPECTATOR.
CG_TileClear()
void CG_TileClear (void)
Definition at line 305 of file cg_drawtools.c.
 {
     int        top, bottom, left, right;
     int        w, h;
     w = cgs.glconfig.vidWidth;
     h = cgs.glconfig.vidHeight;
     if (cg.refdef.x == 0 && cg.refdef.y == 0 &&
         cg.refdef.width == w && cg.refdef.height == h) {
         return;        // full screen rendering
     }
     top = cg.refdef.y;
     bottom = top + cg.refdef.height - 1;
     left = cg.refdef.x;
     right = left + cg.refdef.width - 1;
     // clear above view screen
     CG_TileClearBox(0, 0, w, top, cgs.media.backTileShader);
     // clear below view screen
     CG_TileClearBox(0, bottom, w, h - bottom, cgs.media.backTileShader);
     // clear left of view screen
     CG_TileClearBox(0, top, left, bottom - top + 1, cgs.media.backTileShader);
     // clear right of view screen
     CG_TileClearBox(right, top, w - right, bottom - top + 1, cgs.media.backTileShader);
 }
References cgMedia_t::backTileShader, cg, CG_TileClearBox(), cgs, cgs_t::glconfig, refdef_t::height, cgs_t::media, cg_t::refdef, right, glconfig_t::vidHeight, glconfig_t::vidWidth, refdef_t::width, refdef_t::x, and refdef_t::y.
Referenced by CG_DrawActive().
CG_TileClearBox()
static void CG_TileClearBox (int x, int y, int w, int h, qhandle_t hShader) static
Definition at line 285 of file cg_drawtools.c.
 {
     float    s1, t1, s2, t2;
     s1 = x / 64.0;
     t1 = y / 64.0;
     s2 = (x + w) / 64.0;
     t2 = (y + h) / 64.0;
     trap_R_DrawStretchPic(x, y, w, h, s1, t1, s2, t2, hShader);
 }
References trap_R_DrawStretchPic().
Referenced by CG_TileClear().
UI_DrawBannerString()
void UI_DrawBannerString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 650 of file cg_drawtools.c.
 {
     const char* s;
     int                ch;
     int                width;
     vec4_t            drawcolor;
     // find the width of the drawn text
     s = str;
     width = 0;
     while (*s) {
         ch = *s;
         if (ch == ' ') {
             width += PROPB_SPACE_WIDTH;
         } else if (ch >= 'A' && ch <= 'Z') {
             width += propMapB[ch - 'A'][2] + PROPB_GAP_WIDTH;
         }
         s++;
     }
     width -= PROPB_GAP_WIDTH;
     switch (style & UI_FORMATMASK) {
     case UI_CENTER:
         x -= width / 2;
         break;
     case UI_RIGHT:
         x -= width;
         break;
     case UI_LEFT:
     default:
         break;
     }
     if (style & UI_DROPSHADOW) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawBannerString2(x + 2, y + 2, str, drawcolor);
     }
     UI_DrawBannerString2(x, y, str, color);
 }
Referenced by BText_Draw().
UI_DrawBannerString2()
static void UI_DrawBannerString2 (int x, int y, const char * str, vec4_t color) static
Definition at line 609 of file cg_drawtools.c.
 {
     const char* s;
     unsigned char    ch;
     float    ax;
     float    ay;
     float    aw;
     float    ah;
     float    frow;
     float    fcol;
     float    fwidth;
     float    fheight;
     // draw the colored text
     trap_R_SetColor(color);
     ax = x * cgs.screenXScale + cgs.screenXBias;
     ay = y * cgs.screenYScale;
     s = str;
     while (*s) {
         ch = *s & 127;
         if (ch == ' ') {
             ax += ((float)PROPB_SPACE_WIDTH + (float)PROPB_GAP_WIDTH) * cgs.screenXScale;
         } else if (ch >= 'A' && ch <= 'Z') {
             ch -= 'A';
             fcol = (float)propMapB[ch][0] / 256.0f;
             frow = (float)propMapB[ch][1] / 256.0f;
             fwidth = (float)propMapB[ch][2] / 256.0f;
             fheight = (float)PROPB_HEIGHT / 256.0f;
             aw = (float)propMapB[ch][2] * cgs.screenXScale;
             ah = (float)PROPB_HEIGHT * cgs.screenYScale;
             trap_R_DrawStretchPic(ax, ay, aw, ah, fcol, frow, fcol + fwidth, frow + fheight, cgs.media.charsetPropB);
             ax += (aw + (float)PROPB_GAP_WIDTH * cgs.screenXScale);
         }
         s++;
     }
     trap_R_SetColor(NULL);
 }
References cgs, cgMedia_t::charsetPropB, cgs_t::media, NULL, PROPB_GAP_WIDTH, PROPB_HEIGHT, PROPB_SPACE_WIDTH, propMapB, s, cgs_t::screenXBias, cgs_t::screenXScale, cgs_t::screenYScale, trap_R_DrawStretchPic(), and trap_R_SetColor().
Referenced by UI_DrawBannerString().
UI_DrawProportionalString()
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 781 of file cg_drawtools.c.
 {
     vec4_t    drawcolor;
     int        width;
     float    sizeScale;
     sizeScale = UI_ProportionalSizeScale(style);
     switch (style & UI_FORMATMASK) {
     case UI_CENTER:
         width = UI_ProportionalStringWidth(str) * sizeScale;
         x -= width / 2;
         break;
     case UI_RIGHT:
         width = UI_ProportionalStringWidth(str) * sizeScale;
         x -= width;
         break;
     case UI_LEFT:
     default:
         break;
     }
     if (style & UI_DROPSHADOW) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2(x + 2, y + 2, str, drawcolor, sizeScale, cgs.media.charsetProp);
     }
     if (style & UI_INVERSE) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2(x, y, str, drawcolor, sizeScale, cgs.media.charsetProp);
         return;
     }
     if (style & UI_PULSE) {
         drawcolor[0] = color[0] * 0.8;
         drawcolor[1] = color[1] * 0.8;
         drawcolor[2] = color[2] * 0.8;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2(x, y, str, color, sizeScale, cgs.media.charsetProp);
         drawcolor[0] = color[0];
         drawcolor[1] = color[1];
         drawcolor[2] = color[2];
         drawcolor[3] = 0.5 + 0.5 * sin(cg.time / PULSE_DIVISOR);
         UI_DrawProportionalString2(x, y, str, drawcolor, sizeScale, cgs.media.charsetPropGlow);
         return;
     }
     UI_DrawProportionalString2(x, y, str, color, sizeScale, cgs.media.charsetProp);
 }
Referenced by CG_DrawInformation(), ConfirmMenu_Draw(), Controls_ResetDefaults_Draw(), Main_MenuDraw(), MessageMenu_Draw(), PlayerModel_DrawPlayer(), PlayerSettings_DrawEffects(), PlayerSettings_DrawHandicap(), PlayerSettings_DrawName(), PText_Draw(), Reset_MenuDraw(), Setup_ResetDefaults_Draw(), UI_CDKeyMenu_DrawKey(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DisplayDownloadInfo(), UI_DrawConnectScreen(), UI_SaveConfigMenu_SavenameDraw(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_ResetDraw(), UI_SPPostgameMenu_DrawAwardsPresentation(), UI_SPPostgameMenu_MenuDraw(), and UI_TeamOrdersMenu_ListDraw().
UI_DrawProportionalString2()
static void UI_DrawProportionalString2 (int x, int y, const char * str, vec4_t color, float sizeScale, qhandle_t charset) static
Definition at line 718 of file cg_drawtools.c.
 {
     const char* s;
     unsigned char    ch;
     float    ax;
     float    ay;
     float    aw;
     float    ah;
     float    frow;
     float    fcol;
     float    fwidth;
     float    fheight;
     // draw the colored text
     trap_R_SetColor(color);
     ax = x * cgs.screenXScale + cgs.screenXBias;
     ay = y * cgs.screenYScale;
     s = str;
     while (*s) {
         ch = *s & 127;
         if (ch == ' ') {
             aw = (float)PROP_SPACE_WIDTH * cgs.screenXScale * sizeScale;
         } else if (propMap[ch][2] != -1) {
             fcol = (float)propMap[ch][0] / 256.0f;
             frow = (float)propMap[ch][1] / 256.0f;
             fwidth = (float)propMap[ch][2] / 256.0f;
             fheight = (float)PROP_HEIGHT / 256.0f;
             aw = (float)propMap[ch][2] * cgs.screenXScale * sizeScale;
             ah = (float)PROP_HEIGHT * cgs.screenYScale * sizeScale;
             trap_R_DrawStretchPic(ax, ay, aw, ah, fcol, frow, fcol + fwidth, frow + fheight, charset);
         } else {
             aw = 0;
         }
         ax += (aw + (float)PROP_GAP_WIDTH * cgs.screenXScale * sizeScale);
         s++;
     }
     trap_R_SetColor(NULL);
 }
References cgs, NULL, PROP_GAP_WIDTH, PROP_HEIGHT, PROP_SPACE_WIDTH, propMap, s, cgs_t::screenXBias, cgs_t::screenXScale, cgs_t::screenYScale, trap_R_DrawStretchPic(), and trap_R_SetColor().
Referenced by UI_DrawProportionalString().
UI_ProportionalSizeScale()
float UI_ProportionalSizeScale (int style)
Definition at line 766 of file cg_drawtools.c.
 {
     if (style & UI_SMALLFONT) {
         return 0.75;
     }
     return 1.00;
 }
Referenced by PText_Init(), UI_DisplayDownloadInfo(), and UI_DrawProportionalString().
UI_ProportionalStringWidth()
int UI_ProportionalStringWidth (const char * str)
Definition at line 695 of file cg_drawtools.c.
 {
     const char* s;
     int                ch;
     int                charWidth;
     int                width;
     s = str;
     width = 0;
     while (*s) {
         ch = *s & 127;
         charWidth = propMap[ch][2];
         if (charWidth != -1) {
             width += charWidth;
             width += PROP_GAP_WIDTH;
         }
         s++;
     }
     width -= PROP_GAP_WIDTH;
     return width;
 }
Referenced by Prepname(), PText_Init(), UI_ConfirmMenu_Style(), UI_DisplayDownloadInfo(), UI_DrawProportionalString(), UI_Message(), and UI_ResetMenu().
Variable Documentation
propMap
int propMap[128][3] static
Definition at line 458 of file cg_drawtools.c.
Referenced by UI_DrawProportionalString2(), and UI_ProportionalStringWidth().
propMapB
int propMapB[26][3] static
Definition at line 568 of file cg_drawtools.c.
Referenced by UI_DrawBannerString(), and UI_DrawBannerString2().