ioquake3 doxygen: C:/entry/dev/ioq3/code/client/snd_codec.h File Reference
snd_codec.h File Reference
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
Classes
struct snd_info_s
struct snd_stream_s
struct snd_codec_s
Typedefs
typedef struct snd_info_s snd_info_t
typedef struct snd_codec_s snd_codec_t
typedef struct snd_stream_s snd_stream_t
typedef void *(* CODEC_LOAD) (const char *filename, snd_info_t *info)
typedef snd_stream_t *(* CODEC_OPEN) (const char *filename)
typedef int(* CODEC_READ) (snd_stream_t *stream, int bytes, void *buffer)
typedef void(* CODEC_CLOSE) (snd_stream_t *stream)
Functions
void S_CodecInit (void)
void S_CodecShutdown (void)
void S_CodecRegister (snd_codec_t *codec)
void * S_CodecLoad (const char *filename, snd_info_t *info)
snd_stream_t * S_CodecOpenStream (const char *filename)
void S_CodecCloseStream (snd_stream_t *stream)
int S_CodecReadStream (snd_stream_t *stream, int bytes, void *buffer)
snd_stream_t * S_CodecUtilOpen (const char *filename, snd_codec_t *codec)
void S_CodecUtilClose (snd_stream_t **stream)
void * S_WAV_CodecLoad (const char *filename, snd_info_t *info)
snd_stream_t * S_WAV_CodecOpenStream (const char *filename)
void S_WAV_CodecCloseStream (snd_stream_t *stream)
int S_WAV_CodecReadStream (snd_stream_t *stream, int bytes, void *buffer)
Variables
snd_codec_t wav_codec
Typedef Documentation
CODEC_CLOSE
typedef void(* CODEC_CLOSE) (snd_stream_t *stream)
Definition at line 56 of file snd_codec.h.
CODEC_LOAD
typedef void*(* CODEC_LOAD) (const char *filename, snd_info_t *info)
Definition at line 53 of file snd_codec.h.
CODEC_OPEN
typedef snd_stream_t*(* CODEC_OPEN) (const char *filename)
Definition at line 54 of file snd_codec.h.
CODEC_READ
typedef int(* CODEC_READ) (snd_stream_t *stream, int bytes, void *buffer)
Definition at line 55 of file snd_codec.h.
snd_codec_t
typedef struct snd_codec_s snd_codec_t
Definition at line 40 of file snd_codec.h.
snd_info_t
typedef struct snd_info_s snd_info_t
snd_stream_t
typedef struct snd_stream_s snd_stream_t
Function Documentation
S_CodecCloseStream()
void S_CodecCloseStream (snd_stream_t * stream)
Definition at line 180 of file snd_codec.c.
 {
     stream->codec->close(stream);
 }
Referenced by S_Base_StopBackgroundTrack(), and S_OpenBackgroundStream().
S_CodecInit()
void S_CodecInit (void)
Definition at line 123 of file snd_codec.c.
 {
     codecs = NULL;
 #ifdef USE_CODEC_OPUS
     S_CodecRegister(&opus_codec);
 #endif
 #ifdef USE_CODEC_VORBIS
     S_CodecRegister(&ogg_codec);
 #endif
 // Register wav codec last so that it is always tried first when a file extension was not found
     S_CodecRegister(&wav_codec);
 }
References codecs, NULL, S_CodecRegister(), and wav_codec.
Referenced by S_Init().
S_CodecLoad()
void* S_CodecLoad (const char * filename, snd_info_t * info)
Definition at line 165 of file snd_codec.c.
 {
     return S_CodecGetSound(filename, info);
 }
References S_CodecGetSound().
Referenced by S_LoadSound().
S_CodecOpenStream()
snd_stream_t* S_CodecOpenStream (const char * filename)
Definition at line 175 of file snd_codec.c.
 {
     return S_CodecGetSound(filename, NULL);
 }
References NULL, and S_CodecGetSound().
Referenced by S_OpenBackgroundStream().
S_CodecReadStream()
int S_CodecReadStream (snd_stream_t * stream, int bytes, void * buffer)
Definition at line 185 of file snd_codec.c.
 {
     return stream->codec->read(stream, bytes, buffer);
 }
References buffer.
Referenced by S_UpdateBackgroundTrack().
S_CodecRegister()
void S_CodecRegister (snd_codec_t * codec)
Definition at line 154 of file snd_codec.c.
 {
     codec->next = codecs;
     codecs = codec;
 }
References codecs, and snd_codec_s::next.
Referenced by S_CodecInit().
S_CodecShutdown()
void S_CodecShutdown (void)
Definition at line 144 of file snd_codec.c.
 {
     codecs = NULL;
 }
References codecs, and NULL.
Referenced by S_Shutdown().
S_CodecUtilClose()
void S_CodecUtilClose (snd_stream_t ** stream)
Definition at line 232 of file snd_codec.c.
 {
     FS_FCloseFile((*stream)->file);
     Z_Free(*stream);
     *stream = NULL;
 }
References FS_FCloseFile(), NULL, and Z_Free().
Referenced by S_WAV_CodecCloseStream(), and S_WAV_CodecOpenStream().
S_CodecUtilOpen()
snd_stream_t* S_CodecUtilOpen (const char * filename, snd_codec_t * codec)
Definition at line 198 of file snd_codec.c.
 {
     snd_stream_t *stream;
     fileHandle_t hnd;
     int length;
     // Try to open the file
     length = FS_FOpenFileRead(filename, &hnd, qtrue);
     if(!hnd)
     {
         Com_DPrintf("Can't read sound file %s\n", filename);
         return NULL;
     }
     // Allocate a stream
     stream = Z_Malloc(sizeof(snd_stream_t));
     if(!stream)
     {
         FS_FCloseFile(hnd);
         return NULL;
     }
     // Copy over, return
     stream->codec = codec;
     stream->file = hnd;
     stream->length = length;
     return stream;
 }
References Com_DPrintf(), FS_FCloseFile(), FS_FOpenFileRead(), NULL, qtrue, and Z_Malloc.
Referenced by S_WAV_CodecOpenStream().
S_WAV_CodecCloseStream()
void S_WAV_CodecCloseStream (snd_stream_t * stream)
Definition at line 267 of file snd_codec_wav.c.
 {
     S_CodecUtilClose(&stream);
 }
References S_CodecUtilClose().
S_WAV_CodecLoad()
void* S_WAV_CodecLoad (const char * filename, snd_info_t * info)
Definition at line 198 of file snd_codec_wav.c.
 {
     fileHandle_t file;
     void *buffer;
     // Try to open the file
     FS_FOpenFileRead(filename, &file, qtrue);
     if(!file)
     {
         return NULL;
     }
     // Read the RIFF header
     if(!S_ReadRIFFHeader(file, info))
     {
         FS_FCloseFile(file);
         Com_Printf( S_COLOR_RED "ERROR: Incorrect/unsupported format in \"%s\"\n",
                 filename);
         return NULL;
     }
     // Allocate some memory
     buffer = Hunk_AllocateTempMemory(info->size);
     if(!buffer)
     {
         FS_FCloseFile(file);
         Com_Printf( S_COLOR_RED "ERROR: Out of memory reading \"%s\"\n",
                 filename);
         return NULL;
     }
     // Read, byteswap
     FS_Read(buffer, info->size, file);
     S_ByteSwapRawSamples(info->samples, info->width, info->channels, (byte *)buffer);
     // Close and return
     FS_FCloseFile(file);
     return buffer;
 }
References buffer, snd_info_s::channels, Com_Printf(), FS_FCloseFile(), FS_FOpenFileRead(), FS_Read(), Hunk_AllocateTempMemory(), NULL, qtrue, S_ByteSwapRawSamples(), S_COLOR_RED, S_ReadRIFFHeader(), snd_info_s::samples, snd_info_s::size, and snd_info_s::width.
S_WAV_CodecOpenStream()
snd_stream_t* S_WAV_CodecOpenStream (const char * filename)
Definition at line 243 of file snd_codec_wav.c.
 {
     snd_stream_t *rv;
     // Open
     rv = S_CodecUtilOpen(filename, &wav_codec);
     if(!rv)
         return NULL;
     // Read the RIFF header
     if(!S_ReadRIFFHeader(rv->file, &rv->info))
     {
         S_CodecUtilClose(&rv);
         return NULL;
     }
     return rv;
 }
References snd_stream_s::file, snd_stream_s::info, NULL, S_CodecUtilClose(), S_CodecUtilOpen(), S_ReadRIFFHeader(), and wav_codec.
S_WAV_CodecReadStream()
int S_WAV_CodecReadStream (snd_stream_t * stream, int bytes, void * buffer)
Definition at line 277 of file snd_codec_wav.c.
 {
     int remaining = stream->info.size - stream->pos;
     int samples;
     if(remaining <= 0)
         return 0;
     if(bytes > remaining)
         bytes = remaining;
     stream->pos += bytes;
     samples = (bytes / stream->info.width) / stream->info.channels;
     FS_Read(buffer, bytes, stream->file);
     S_ByteSwapRawSamples(samples, stream->info.width, stream->info.channels, buffer);
     return bytes;
 }
References buffer, FS_Read(), and S_ByteSwapRawSamples().
Variable Documentation
wav_codec
snd_codec_t wav_codec
Definition at line 183 of file snd_codec_wav.c.
Referenced by S_CodecInit(), and S_WAV_CodecOpenStream().