ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_spskill.c File Reference
ui_spskill.c File Reference
#include "ui_local.h"
Classes
struct skillMenuInfo_t
Macros
#define ART_FRAME "menu/art/cut_frame"
#define ART_BACK "menu/art/back_0.tga"
#define ART_BACK_FOCUS "menu/art/back_1.tga"
#define ART_FIGHT "menu/art/fight_0"
#define ART_FIGHT_FOCUS "menu/art/fight_1"
#define ART_MAP_COMPLETE1 "menu/art/level_complete1"
#define ART_MAP_COMPLETE2 "menu/art/level_complete2"
#define ART_MAP_COMPLETE3 "menu/art/level_complete3"
#define ART_MAP_COMPLETE4 "menu/art/level_complete4"
#define ART_MAP_COMPLETE5 "menu/art/level_complete5"
#define ID_BABY 10
#define ID_EASY 11
#define ID_MEDIUM 12
#define ID_HARD 13
#define ID_NIGHTMARE 14
#define ID_BACK 15
#define ID_FIGHT 16
Functions
static void SetSkillColor (int skill, vec4_t color)
static void UI_SPSkillMenu_SkillEvent (void *ptr, int notification)
static void UI_SPSkillMenu_FightEvent (void *ptr, int notification)
static void UI_SPSkillMenu_BackEvent (void *ptr, int notification)
static sfxHandle_t UI_SPSkillMenu_Key (int key)
void UI_SPSkillMenu_Cache (void)
static void UI_SPSkillMenu_Init (void)
void UI_SPSkillMenu (const char *arenaInfo)
Variables
static skillMenuInfo_t skillMenuInfo
Macro Definition Documentation
ART_BACK
#define ART_BACK "menu/art/back_0.tga"
Definition at line 35 of file ui_spskill.c.
ART_BACK_FOCUS
#define ART_BACK_FOCUS "menu/art/back_1.tga"
Definition at line 36 of file ui_spskill.c.
ART_FIGHT
#define ART_FIGHT "menu/art/fight_0"
Definition at line 37 of file ui_spskill.c.
ART_FIGHT_FOCUS
#define ART_FIGHT_FOCUS "menu/art/fight_1"
Definition at line 38 of file ui_spskill.c.
ART_FRAME
#define ART_FRAME "menu/art/cut_frame"
Definition at line 34 of file ui_spskill.c.
ART_MAP_COMPLETE1
#define ART_MAP_COMPLETE1 "menu/art/level_complete1"
Definition at line 39 of file ui_spskill.c.
ART_MAP_COMPLETE2
#define ART_MAP_COMPLETE2 "menu/art/level_complete2"
Definition at line 40 of file ui_spskill.c.
ART_MAP_COMPLETE3
#define ART_MAP_COMPLETE3 "menu/art/level_complete3"
Definition at line 41 of file ui_spskill.c.
ART_MAP_COMPLETE4
#define ART_MAP_COMPLETE4 "menu/art/level_complete4"
Definition at line 42 of file ui_spskill.c.
ART_MAP_COMPLETE5
#define ART_MAP_COMPLETE5 "menu/art/level_complete5"
Definition at line 43 of file ui_spskill.c.
ID_BABY
#define ID_BABY 10
Definition at line 45 of file ui_spskill.c.
ID_BACK
#define ID_BACK 15
Definition at line 50 of file ui_spskill.c.
ID_EASY
#define ID_EASY 11
Definition at line 46 of file ui_spskill.c.
ID_FIGHT
#define ID_FIGHT 16
Definition at line 51 of file ui_spskill.c.
ID_HARD
#define ID_HARD 13
Definition at line 48 of file ui_spskill.c.
ID_MEDIUM
#define ID_MEDIUM 12
Definition at line 47 of file ui_spskill.c.
ID_NIGHTMARE
#define ID_NIGHTMARE 14
Definition at line 49 of file ui_spskill.c.
Function Documentation
SetSkillColor()
static void SetSkillColor (int skill, vec4_t color) static
Definition at line 79 of file ui_spskill.c.
{
     switch( skill ) {
     case 1:
         skillMenuInfo.item_baby.color = color;
         break;
     case 2:
         skillMenuInfo.item_easy.color = color;
         break;
     case 3:
         skillMenuInfo.item_medium.color = color;
         break;
     case 4:
         skillMenuInfo.item_hard.color = color;
         break;
     case 5:
         skillMenuInfo.item_nightmare.color = color;
         break;
     default:
         break;
     }
 }
Referenced by UI_SPSkillMenu_Init(), and UI_SPSkillMenu_SkillEvent().
UI_SPSkillMenu()
void UI_SPSkillMenu (const char * arenaInfo)
Definition at line 324 of file ui_spskill.c.
{
     UI_SPSkillMenu_Init();
     skillMenuInfo.arenaInfo = arenaInfo;
     UI_PushMenu( &skillMenuInfo.menu );
     Menu_SetCursorToItem( &skillMenuInfo.menu, &skillMenuInfo.item_fight );
 }
Referenced by UI_SPLevelMenu_NextEvent().
UI_SPSkillMenu_BackEvent()
static void UI_SPSkillMenu_BackEvent (void * ptr, int notification) static
Definition at line 150 of file ui_spskill.c.
{
     if (notification != QM_ACTIVATED) {
         return;
     }
     trap_S_StartLocalSound( skillMenuInfo.silenceSound, CHAN_ANNOUNCER );
     UI_PopMenu();
 }
Referenced by UI_SPSkillMenu_Init().
UI_SPSkillMenu_Cache()
void UI_SPSkillMenu_Cache (void)
Definition at line 178 of file ui_spskill.c.
{
     trap_R_RegisterShaderNoMip( ART_FRAME );
     trap_R_RegisterShaderNoMip( ART_BACK );
     trap_R_RegisterShaderNoMip( ART_BACK_FOCUS );
     trap_R_RegisterShaderNoMip( ART_FIGHT );
     trap_R_RegisterShaderNoMip( ART_FIGHT_FOCUS );
     skillMenuInfo.skillpics[0] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE1 );
     skillMenuInfo.skillpics[1] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE2 );
     skillMenuInfo.skillpics[2] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE3 );
     skillMenuInfo.skillpics[3] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE4 );
     skillMenuInfo.skillpics[4] = trap_R_RegisterShaderNoMip( ART_MAP_COMPLETE5 );
     skillMenuInfo.nightmareSound = trap_S_RegisterSound( "sound/misc/nightmare.wav", qfalse );
     skillMenuInfo.silenceSound = trap_S_RegisterSound( "sound/misc/silence.wav", qfalse );
 }
Referenced by UI_Cache_f(), and UI_SPSkillMenu_Init().
UI_SPSkillMenu_FightEvent()
static void UI_SPSkillMenu_FightEvent (void * ptr, int notification) static
Definition at line 137 of file ui_spskill.c.
{
     if (notification != QM_ACTIVATED)
         return;
     UI_SPArena_Start( skillMenuInfo.arenaInfo );
 }
Referenced by UI_SPSkillMenu_Init().
UI_SPSkillMenu_Init()
static void UI_SPSkillMenu_Init (void) static
Definition at line 200 of file ui_spskill.c.
{
     int     skill;
     memset( &skillMenuInfo, 0, sizeof(skillMenuInfo) );
     skillMenuInfo.menu.fullscreen = qtrue;
     skillMenuInfo.menu.key = UI_SPSkillMenu_Key;
     UI_SPSkillMenu_Cache();
     skillMenuInfo.art_frame.generic.type        = MTYPE_BITMAP;
     skillMenuInfo.art_frame.generic.name        = ART_FRAME;
     skillMenuInfo.art_frame.generic.flags       = QMF_LEFT_JUSTIFY|QMF_INACTIVE;
     skillMenuInfo.art_frame.generic.x           = 142;
     skillMenuInfo.art_frame.generic.y           = 118;
     skillMenuInfo.art_frame.width               = 359;
     skillMenuInfo.art_frame.height              = 256;
     skillMenuInfo.art_banner.generic.type       = MTYPE_BTEXT;
     skillMenuInfo.art_banner.generic.flags      = QMF_CENTER_JUSTIFY;
     skillMenuInfo.art_banner.generic.x          = 320;
     skillMenuInfo.art_banner.generic.y          = 16;
     skillMenuInfo.art_banner.string             = "DIFFICULTY";
     skillMenuInfo.art_banner.color              = color_white;
     skillMenuInfo.art_banner.style              = UI_CENTER;
     skillMenuInfo.item_baby.generic.type        = MTYPE_PTEXT;
     skillMenuInfo.item_baby.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     skillMenuInfo.item_baby.generic.x           = 320;
     skillMenuInfo.item_baby.generic.y           = 170;
     skillMenuInfo.item_baby.generic.callback    = UI_SPSkillMenu_SkillEvent;
     skillMenuInfo.item_baby.generic.id          = ID_BABY;
     skillMenuInfo.item_baby.string              = "I Can Win";
     skillMenuInfo.item_baby.color               = color_red;
     skillMenuInfo.item_baby.style               = UI_CENTER;
     skillMenuInfo.item_easy.generic.type        = MTYPE_PTEXT;
     skillMenuInfo.item_easy.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     skillMenuInfo.item_easy.generic.x           = 320;
     skillMenuInfo.item_easy.generic.y           = 198;
     skillMenuInfo.item_easy.generic.callback    = UI_SPSkillMenu_SkillEvent;
     skillMenuInfo.item_easy.generic.id          = ID_EASY;
     skillMenuInfo.item_easy.string              = "Bring It On";
     skillMenuInfo.item_easy.color               = color_red;
     skillMenuInfo.item_easy.style               = UI_CENTER;
     skillMenuInfo.item_medium.generic.type      = MTYPE_PTEXT;
     skillMenuInfo.item_medium.generic.flags     = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     skillMenuInfo.item_medium.generic.x         = 320;
     skillMenuInfo.item_medium.generic.y         = 227;
     skillMenuInfo.item_medium.generic.callback  = UI_SPSkillMenu_SkillEvent;
     skillMenuInfo.item_medium.generic.id        = ID_MEDIUM;
     skillMenuInfo.item_medium.string            = "Hurt Me Plenty";
     skillMenuInfo.item_medium.color             = color_red;
     skillMenuInfo.item_medium.style             = UI_CENTER;
     skillMenuInfo.item_hard.generic.type        = MTYPE_PTEXT;
     skillMenuInfo.item_hard.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     skillMenuInfo.item_hard.generic.x           = 320;
     skillMenuInfo.item_hard.generic.y           = 255;
     skillMenuInfo.item_hard.generic.callback    = UI_SPSkillMenu_SkillEvent;
     skillMenuInfo.item_hard.generic.id          = ID_HARD;
     skillMenuInfo.item_hard.string              = "Hardcore";
     skillMenuInfo.item_hard.color               = color_red;
     skillMenuInfo.item_hard.style               = UI_CENTER;
     skillMenuInfo.item_nightmare.generic.type       = MTYPE_PTEXT;
     skillMenuInfo.item_nightmare.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     skillMenuInfo.item_nightmare.generic.x          = 320;
     skillMenuInfo.item_nightmare.generic.y          = 283;
     skillMenuInfo.item_nightmare.generic.callback   = UI_SPSkillMenu_SkillEvent;
     skillMenuInfo.item_nightmare.generic.id         = ID_NIGHTMARE;
     skillMenuInfo.item_nightmare.string             = "NIGHTMARE!";
     skillMenuInfo.item_nightmare.color              = color_red;
     skillMenuInfo.item_nightmare.style              = UI_CENTER;
     skillMenuInfo.item_back.generic.type        = MTYPE_BITMAP;
     skillMenuInfo.item_back.generic.name        = ART_BACK;
     skillMenuInfo.item_back.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     skillMenuInfo.item_back.generic.x           = 0;
     skillMenuInfo.item_back.generic.y           = 480-64;
     skillMenuInfo.item_back.generic.callback    = UI_SPSkillMenu_BackEvent;
     skillMenuInfo.item_back.generic.id          = ID_BACK;
     skillMenuInfo.item_back.width               = 128;
     skillMenuInfo.item_back.height              = 64;
     skillMenuInfo.item_back.focuspic            = ART_BACK_FOCUS;
     skillMenuInfo.art_skillPic.generic.type     = MTYPE_BITMAP;
     skillMenuInfo.art_skillPic.generic.flags    = QMF_LEFT_JUSTIFY|QMF_INACTIVE;
     skillMenuInfo.art_skillPic.generic.x        = 320-64;
     skillMenuInfo.art_skillPic.generic.y        = 368;
     skillMenuInfo.art_skillPic.width            = 128;
     skillMenuInfo.art_skillPic.height           = 96;
     skillMenuInfo.item_fight.generic.type       = MTYPE_BITMAP;
     skillMenuInfo.item_fight.generic.name       = ART_FIGHT;
     skillMenuInfo.item_fight.generic.flags      = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS;
     skillMenuInfo.item_fight.generic.callback   = UI_SPSkillMenu_FightEvent;
     skillMenuInfo.item_fight.generic.id         = ID_FIGHT;
     skillMenuInfo.item_fight.generic.x          = 640;
     skillMenuInfo.item_fight.generic.y          = 480-64;
     skillMenuInfo.item_fight.width              = 128;
     skillMenuInfo.item_fight.height             = 64;
     skillMenuInfo.item_fight.focuspic           = ART_FIGHT_FOCUS;
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.art_frame );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.art_banner );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.item_baby );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.item_easy );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.item_medium );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.item_hard );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.item_nightmare );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.art_skillPic );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.item_back );
     Menu_AddItem( &skillMenuInfo.menu, ( void * )&skillMenuInfo.item_fight );
     skill = (int)Com_Clamp( 1, 5, trap_Cvar_VariableValue( "g_spSkill" ) );
     SetSkillColor( skill, color_white );
     skillMenuInfo.art_skillPic.shader = skillMenuInfo.skillpics[skill - 1];
     if( skill == 5 ) {
         trap_S_StartLocalSound( skillMenuInfo.nightmareSound, CHAN_ANNOUNCER );
     }
 }
Referenced by UI_SPSkillMenu().
UI_SPSkillMenu_Key()
static sfxHandle_t UI_SPSkillMenu_Key (int key) static
Definition at line 165 of file ui_spskill.c.
{
     if( key == K_MOUSE2 || key == K_ESCAPE ) {
         trap_S_StartLocalSound( skillMenuInfo.silenceSound, CHAN_ANNOUNCER );
     }
     return Menu_DefaultKey( &skillMenuInfo.menu, key );
 }
Referenced by UI_SPSkillMenu_Init().
UI_SPSkillMenu_SkillEvent()
static void UI_SPSkillMenu_SkillEvent (void * ptr, int notification) static
Definition at line 107 of file ui_spskill.c.
{
     int     id;
     int     skill;
     if (notification != QM_ACTIVATED)
         return;
     SetSkillColor( (int)trap_Cvar_VariableValue( "g_spSkill" ), color_red );
     id = ((menucommon_s*)ptr)->id;
     skill = id - ID_BABY + 1;
     trap_Cvar_SetValue( "g_spSkill", skill );
     SetSkillColor( skill, color_white );
     skillMenuInfo.art_skillPic.shader = skillMenuInfo.skillpics[skill - 1];
     if( id == ID_NIGHTMARE ) {
         trap_S_StartLocalSound( skillMenuInfo.nightmareSound, CHAN_ANNOUNCER );
     }
     else {
         trap_S_StartLocalSound( skillMenuInfo.silenceSound, CHAN_ANNOUNCER );
     }
 }
Referenced by UI_SPSkillMenu_Init().
Variable Documentation
skillMenuInfo
skillMenuInfo_t skillMenuInfo static
Definition at line 76 of file ui_spskill.c.
Referenced by SetSkillColor(), UI_SPSkillMenu(), UI_SPSkillMenu_BackEvent(), UI_SPSkillMenu_Cache(), UI_SPSkillMenu_FightEvent(), UI_SPSkillMenu_Init(), UI_SPSkillMenu_Key(), and UI_SPSkillMenu_SkillEvent().