ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_move.h File Reference
be_aas_move.h File Reference
Functions
int AAS_PredictClientMovement (struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
int AAS_ClientMovementHitBBox (struct aas_clientmove_s *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, vec3_t mins, vec3_t maxs, int visualize)
int AAS_OnGround (vec3_t origin, int presencetype, int passent)
int AAS_Swimming (vec3_t origin)
void AAS_JumpReachRunStart (struct aas_reachability_s *reach, vec3_t runstart)
int AAS_AgainstLadder (vec3_t origin)
float AAS_RocketJumpZVelocity (vec3_t origin)
float AAS_BFGJumpZVelocity (vec3_t origin)
int AAS_HorizontalVelocityForJump (float zvel, vec3_t start, vec3_t end, float *velocity)
void AAS_SetMovedir (vec3_t angles, vec3_t movedir)
int AAS_DropToFloor (vec3_t origin, vec3_t mins, vec3_t maxs)
void AAS_InitSettings (void)
Function Documentation
AAS_AgainstLadder()
int AAS_AgainstLadder (vec3_t origin)
Definition at line 123 of file be_aas_move.c.
 {
     int areanum, i, facenum, side;
     vec3_t org;
     aas_plane_t *plane;
     aas_face_t *face;
     aas_area_t *area;
     VectorCopy(origin, org);
     areanum = AAS_PointAreaNum(org);
     if (!areanum)
     {
         org[0] += 1;
         areanum = AAS_PointAreaNum(org);
         if (!areanum)
         {
             org[1] += 1;
             areanum = AAS_PointAreaNum(org);
             if (!areanum)
             {
                 org[0] -= 2;
                 areanum = AAS_PointAreaNum(org);
                 if (!areanum)
                 {
                     org[1] -= 2;
                     areanum = AAS_PointAreaNum(org);
                 } //end if
             } //end if
         } //end if
     } //end if
     //if in solid... wrrr shouldn't happen
     if (!areanum) return qfalse;
     //if not in a ladder area
     if (!(aasworld.areasettings[areanum].areaflags & AREA_LADDER)) return qfalse;
     //if a crouch only area
     if (!(aasworld.areasettings[areanum].presencetype & PRESENCE_NORMAL)) return qfalse;
     //
     area = &aasworld.areas[areanum];
     for (i = 0; i < area->numfaces; i++)
     {
         facenum = aasworld.faceindex[area->firstface + i];
         side = facenum < 0;
         face = &aasworld.faces[abs(facenum)];
         //if the face isn't a ladder face
         if (!(face->faceflags & FACE_LADDER)) continue;
         //get the plane the face is in
         plane = &aasworld.planes[face->planenum ^ side];
         //if the origin is pretty close to the plane
         if (fabsf(DotProduct(plane->normal, origin) - plane->dist) < 3)
         {
             if (AAS_PointInsideFace(abs(facenum), origin, 0.1f)) return qtrue;
         } //end if
     } //end for
     return qfalse;
 } //end of the function AAS_AgainstLadder
Referenced by BotMoveToGoal().
AAS_BFGJumpZVelocity()
float AAS_BFGJumpZVelocity (vec3_t origin)
Definition at line 352 of file be_aas_move.c.
 {
     //bfg radius damage is 1000 (p_weapon.c: weapon_bfg_fire)
     return AAS_WeaponJumpZVelocity(origin, 120);
 } //end of the function AAS_BFGJumpZVelocity
Referenced by AAS_Reachability_WeaponJump().
AAS_ClientMovementHitBBox()
int AAS_ClientMovementHitBBox (struct aas_clientmove_s * move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, vec3_t mins, vec3_t maxs, int visualize)
Definition at line 1003 of file be_aas_move.c.
 {
     return AAS_ClientMovementPrediction(move, entnum, origin, presencetype, onground,
                                         velocity, cmdmove, cmdframes, maxframes,
                                         frametime, SE_HITBOUNDINGBOX, 0,
                                         mins, maxs, visualize);
 } //end of the function AAS_ClientMovementHitBBox
Referenced by AAS_BestReachableFromJumpPadArea().
AAS_DropToFloor()
int AAS_DropToFloor (vec3_t origin, vec3_t mins, vec3_t maxs)
Definition at line 56 of file be_aas_move.c.
 {
     vec3_t end;
     bsp_trace_t trace;
     VectorCopy(origin, end);
     end[2] -= 100;
     trace = AAS_Trace(origin, mins, maxs, end, 0, CONTENTS_SOLID);
     if (trace.startsolid) return qfalse;
     VectorCopy(trace.endpos, origin);
     return qtrue;
 } //end of the function AAS_DropToFloor
Referenced by AAS_SetWeaponJumpAreaFlags(), and BotInitLevelItems().
AAS_HorizontalVelocityForJump()
int AAS_HorizontalVelocityForJump (float zvel, vec3_t start, vec3_t end, float * velocity)
Definition at line 1051 of file be_aas_move.c.
 {
     float phys_gravity, phys_maxvelocity;
     float maxjump, height2fall, t, top;
     vec3_t dir;
     phys_gravity = aassettings.phys_gravity;
     phys_maxvelocity = aassettings.phys_maxvelocity;
     //maximum height a player can jump with the given initial z velocity
     maxjump = 0.5 * phys_gravity * (zvel / phys_gravity) * (zvel / phys_gravity);
     //top of the parabolic jump
     top = start[2] + maxjump;
     //height the bot will fall from the top
     height2fall = top - end[2];
     //if the goal is to high to jump to
     if (height2fall < 0)
     {
         *velocity = phys_maxvelocity;
         return 0;
     } //end if
     //time a player takes to fall the height
     t = sqrt(height2fall / (0.5 * phys_gravity));
     //direction from start to end
     VectorSubtract(end, start, dir);
     //
     if ( (t + zvel / phys_gravity) == 0.0f ) {
         *velocity = phys_maxvelocity;
         return 0;
     }
     //calculate horizontal speed
     *velocity = sqrt(dir[0]*dir[0] + dir[1]*dir[1]) / (t + zvel / phys_gravity);
     //the horizontal speed must be lower than the max speed
     if (*velocity > phys_maxvelocity)
     {
         *velocity = phys_maxvelocity;
         return 0;
     } //end if
     return 1;
 } //end of the function AAS_HorizontalVelocityForJump
Referenced by AAS_FindFaceReachabilities(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_WeaponJump(), AAS_ShowReachability(), and BotTravel_WalkOffLedge().
AAS_InitSettings()
void AAS_InitSettings (void)
Definition at line 74 of file be_aas_move.c.
 {
     aassettings.phys_gravitydirection[0]    = 0;
     aassettings.phys_gravitydirection[1]    = 0;
     aassettings.phys_gravitydirection[2]    = -1;
     aassettings.phys_friction               = LibVarValue("phys_friction", "6");
     aassettings.phys_stopspeed              = LibVarValue("phys_stopspeed", "100");
     aassettings.phys_gravity                = LibVarValue("phys_gravity", "800");
     aassettings.phys_waterfriction          = LibVarValue("phys_waterfriction", "1");
     aassettings.phys_watergravity           = LibVarValue("phys_watergravity", "400");
     aassettings.phys_maxvelocity            = LibVarValue("phys_maxvelocity", "320");
     aassettings.phys_maxwalkvelocity        = LibVarValue("phys_maxwalkvelocity", "320");
     aassettings.phys_maxcrouchvelocity      = LibVarValue("phys_maxcrouchvelocity", "100");
     aassettings.phys_maxswimvelocity        = LibVarValue("phys_maxswimvelocity", "150");
     aassettings.phys_walkaccelerate         = LibVarValue("phys_walkaccelerate", "10");
     aassettings.phys_airaccelerate          = LibVarValue("phys_airaccelerate", "1");
     aassettings.phys_swimaccelerate         = LibVarValue("phys_swimaccelerate", "4");
     aassettings.phys_maxstep                = LibVarValue("phys_maxstep", "19");
     aassettings.phys_maxsteepness           = LibVarValue("phys_maxsteepness", "0.7");
     aassettings.phys_maxwaterjump           = LibVarValue("phys_maxwaterjump", "18");
     aassettings.phys_maxbarrier             = LibVarValue("phys_maxbarrier", "33");
     aassettings.phys_jumpvel                = LibVarValue("phys_jumpvel", "270");
     aassettings.phys_falldelta5             = LibVarValue("phys_falldelta5", "40");
     aassettings.phys_falldelta10            = LibVarValue("phys_falldelta10", "60");
     aassettings.rs_waterjump                = LibVarValue("rs_waterjump", "400");
     aassettings.rs_teleport                 = LibVarValue("rs_teleport", "50");
     aassettings.rs_barrierjump              = LibVarValue("rs_barrierjump", "100");
     aassettings.rs_startcrouch              = LibVarValue("rs_startcrouch", "300");
     aassettings.rs_startgrapple             = LibVarValue("rs_startgrapple", "500");
     aassettings.rs_startwalkoffledge        = LibVarValue("rs_startwalkoffledge", "70");
     aassettings.rs_startjump                = LibVarValue("rs_startjump", "300");
     aassettings.rs_rocketjump               = LibVarValue("rs_rocketjump", "500");
     aassettings.rs_bfgjump                  = LibVarValue("rs_bfgjump", "500");
     aassettings.rs_jumppad                  = LibVarValue("rs_jumppad", "250");
     aassettings.rs_aircontrolledjumppad     = LibVarValue("rs_aircontrolledjumppad", "300");
     aassettings.rs_funcbob                  = LibVarValue("rs_funcbob", "300");
     aassettings.rs_startelevator            = LibVarValue("rs_startelevator", "50");
     aassettings.rs_falldamage5              = LibVarValue("rs_falldamage5", "300");
     aassettings.rs_falldamage10             = LibVarValue("rs_falldamage10", "500");
     aassettings.rs_maxfallheight            = LibVarValue("rs_maxfallheight", "0");
     aassettings.rs_maxjumpfallheight        = LibVarValue("rs_maxjumpfallheight", "450");
 } //end of the function AAS_InitSettings
Referenced by AAS_LoadMap().
AAS_JumpReachRunStart()
void AAS_JumpReachRunStart (struct aas_reachability_s * reach, vec3_t runstart)
Definition at line 256 of file be_aas_move.c.
 {
     vec3_t hordir, start, cmdmove;
     aas_clientmove_t move;
     //
     hordir[0] = reach->start[0] - reach->end[0];
     hordir[1] = reach->start[1] - reach->end[1];
     hordir[2] = 0;
     VectorNormalize(hordir);
     //start point
     VectorCopy(reach->start, start);
     start[2] += 1;
     //get command movement
     VectorScale(hordir, 400, cmdmove);
     //
     AAS_PredictClientMovement(&move, -1, start, PRESENCE_NORMAL, qtrue,
                                 vec3_origin, cmdmove, 1, 2, 0.1f,
                                 SE_ENTERWATER|SE_ENTERSLIME|SE_ENTERLAVA|
                                 SE_HITGROUNDDAMAGE|SE_GAP, 0, qfalse);
     VectorCopy(move.endpos, runstart);
     //don't enter slime or lava and don't fall from too high
     if (move.stopevent & (SE_ENTERSLIME|SE_ENTERLAVA|SE_HITGROUNDDAMAGE))
     {
         VectorCopy(start, runstart);
     } //end if
 } //end of the function AAS_JumpReachRunStart
Referenced by AAS_ShowReachability(), and BotTravel_Jump().
AAS_OnGround()
int AAS_OnGround (vec3_t origin, int presencetype, int passent)
Definition at line 185 of file be_aas_move.c.
 {
     aas_trace_t trace;
     vec3_t end, up = {0, 0, 1};
     aas_plane_t *plane;
     VectorCopy(origin, end);
     end[2] -= 10;
     trace = AAS_TraceClientBBox(origin, end, presencetype, passent);
     //if in solid
     if (trace.startsolid) return qfalse;
     //if nothing hit at all
     if (trace.fraction >= 1.0) return qfalse;
     //if too far from the hit plane
     if (origin[2] - trace.endpos[2] > 10) return qfalse;
     //check if the plane isn't too steep
     plane = AAS_PlaneFromNum(trace.planenum);
     if (DotProduct(plane->normal, up) < aassettings.phys_maxsteepness) return qfalse;
     //the bot is on the ground
     return qtrue;
 } //end of the function AAS_OnGround
Referenced by AAS_ClientMovementPrediction(), BotMoveToGoal(), and BotWalkInDirection().
AAS_PredictClientMovement()
int AAS_PredictClientMovement (struct aas_clientmove_s * move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
Definition at line 983 of file be_aas_move.c.
 {
     vec3_t mins, maxs;
     return AAS_ClientMovementPrediction(move, entnum, origin, presencetype, onground,
                                         velocity, cmdmove, cmdframes, maxframes,
                                         frametime, stopevent, stopareanum,
                                         mins, maxs, visualize);
 } //end of the function AAS_PredictClientMovement
Referenced by AAS_JumpReachRunStart(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Teleport(), AAS_Reachability_WeaponJump(), AAS_ShowReachability(), AAS_TestMovementPrediction(), BotWalkInDirection(), and Init_AAS_Export().
AAS_RocketJumpZVelocity()
float AAS_RocketJumpZVelocity (vec3_t origin)
Definition at line 341 of file be_aas_move.c.
 {
     //rocket radius damage is 120 (p_weapon.c: Weapon_RocketLauncher_Fire)
     return AAS_WeaponJumpZVelocity(origin, 120);
 } //end of the function AAS_RocketJumpZVelocity
Referenced by AAS_Reachability_WeaponJump(), and AAS_ShowReachability().
AAS_SetMovedir()
void AAS_SetMovedir (vec3_t angles, vec3_t movedir)
Definition at line 235 of file be_aas_move.c.
 {
     if (VectorCompare(angles, VEC_UP))
     {
         VectorCopy(MOVEDIR_UP, movedir);
     } //end if
     else if (VectorCompare(angles, VEC_DOWN))
     {
         VectorCopy(MOVEDIR_DOWN, movedir);
     } //end else if
     else
     {
         AngleVectors(angles, movedir, NULL, NULL);
     } //end else
 } //end of the function AAS_SetMovedir
AAS_Swimming()
int AAS_Swimming (vec3_t origin)
Definition at line 215 of file be_aas_move.c.
 {
     vec3_t testorg;
     VectorCopy(origin, testorg);
     testorg[2] -= 2;
     if (AAS_PointContents(testorg) & (CONTENTS_LAVA|CONTENTS_SLIME|CONTENTS_WATER)) return qtrue;
     return qfalse;
 } //end of the function AAS_Swimming
Referenced by AAS_ClientMovementPrediction(), AAS_TestMovementPrediction(), BotMoveInDirection(), BotMoveToGoal(), BotReachabilityArea(), and Init_AAS_Export().