ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/cvar.c File Reference
cvar.c File Reference
#include "q_shared.h"
#include "qcommon.h"
Macros
#define MAX_CVARS 2048
#define FILE_HASH_SIZE 256
Functions
static long generateHashValue (const char *fname)
static qboolean Cvar_ValidateString (const char *s)
static cvar_t * Cvar_FindVar (const char *var_name)
float Cvar_VariableValue (const char *var_name)
int Cvar_VariableIntegerValue (const char *var_name)
char * Cvar_VariableString (const char *var_name)
void Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
int Cvar_Flags (const char *var_name)
void Cvar_CommandCompletion (void(*callback)(const char *s))
static const char * Cvar_Validate (cvar_t *var, const char *value, qboolean warn)
cvar_t * Cvar_Get (const char *var_name, const char *var_value, int flags)
void Cvar_Print (cvar_t *v)
cvar_t * Cvar_Set2 (const char *var_name, const char *value, qboolean force)
void Cvar_Set (const char *var_name, const char *value)
void Cvar_SetSafe (const char *var_name, const char *value)
void Cvar_SetLatched (const char *var_name, const char *value)
void Cvar_SetValue (const char *var_name, float value)
void Cvar_SetValueSafe (const char *var_name, float value)
void Cvar_Reset (const char *var_name)
void Cvar_ForceReset (const char *var_name)
void Cvar_SetCheatState (void)
qboolean Cvar_Command (void)
void Cvar_Print_f (void)
void Cvar_Toggle_f (void)
void Cvar_Set_f (void)
void Cvar_Reset_f (void)
void Cvar_WriteVariables (fileHandle_t f)
void Cvar_List_f (void)
void Cvar_ListModified_f (void)
cvar_t * Cvar_Unset (cvar_t *cv)
void Cvar_Unset_f (void)
void Cvar_Restart (qboolean unsetVM)
void Cvar_Restart_f (void)
char * Cvar_InfoString (int bit)
char * Cvar_InfoString_Big (int bit)
void Cvar_InfoStringBuffer (int bit, char *buff, int buffsize)
void Cvar_CheckRange (cvar_t *var, float min, float max, qboolean integral)
void Cvar_SetDescription (cvar_t *var, const char *var_description)
void Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
void Cvar_Update (vmCvar_t *vmCvar)
void Cvar_CompleteCvarName (char *args, int argNum)
void Cvar_Init (void)
Variables
cvar_t * cvar_vars = NULL
cvar_t * cvar_cheats
int cvar_modifiedFlags
cvar_t cvar_indexes [MAX_CVARS]
int cvar_numIndexes
static cvar_t * hashTable [FILE_HASH_SIZE]
Macro Definition Documentation
FILE_HASH_SIZE
#define FILE_HASH_SIZE 256
Definition at line 35 of file cvar.c.
MAX_CVARS
#define MAX_CVARS 2048
Definition at line 31 of file cvar.c.
Function Documentation
Cvar_CheckRange()
void Cvar_CheckRange (cvar_t * var, float min, float max, qboolean integral)
Definition at line 1290 of file cvar.c.
 {
     var->validate = qtrue;
     var->min = min;
     var->max = max;
     var->integral = integral;
     // Force an initial range check
     Cvar_Set( var->name, var->string );
 }
References Cvar_Set(), cvar_s::integral, cvar_s::max, cvar_s::min, cvar_s::name, qtrue, cvar_s::string, and cvar_s::validate.
Referenced by CL_Init(), CL_InitRef(), Com_Init(), and SV_Init().
Cvar_Command()
qboolean Cvar_Command (void)
Definition at line 750 of file cvar.c.
{
     cvar_t  *v;
     // check variables
     v = Cvar_FindVar (Cmd_Argv(0));
     if (!v) {
         return qfalse;
     }
     // perform a variable print or set
     if ( Cmd_Argc() == 1 ) {
         Cvar_Print( v );
         return qtrue;
     }
     // set the value if forcing isn't required
     Cvar_Set2 (v->name, Cmd_Args(), qfalse);
     return qtrue;
 }
References Cmd_Argc(), Cmd_Args(), Cmd_Argv(), Cvar_FindVar(), Cvar_Print(), Cvar_Set2(), cvar_s::name, qfalse, and qtrue.
Referenced by Cmd_ExecuteString().
Cvar_CommandCompletion()
void Cvar_CommandCompletion (void(*)(const char *s) callback)
Definition at line 187 of file cvar.c.
 {
     cvar_t      *cvar;
     for(cvar = cvar_vars; cvar; cvar = cvar->next)
     {
         if(cvar->name)
             callback(cvar->name);
     }
 }
References cvar_vars, cvar_s::name, and cvar_s::next.
Referenced by Field_CompleteCommand().
Cvar_CompleteCvarName()
void Cvar_CompleteCvarName (char * args, int argNum)
Definition at line 1419 of file cvar.c.
 {
     if( argNum == 2 )
     {
         // Skip "<cmd> "
         char *p = Com_SkipTokens( args, 1, " " );
         if( p > args )
             Field_CompleteCommand( p, qfalse, qtrue );
     }
 }
References Com_SkipTokens(), Field_CompleteCommand(), qfalse, and qtrue.
Referenced by Cmd_Init(), and Cvar_Init().
Cvar_FindVar()
static cvar_t* Cvar_FindVar (const char * var_name) static
Definition at line 85 of file cvar.c.
{
     cvar_t  *var;
     long hash;
     hash = generateHashValue(var_name);
     for (var=hashTable[hash] ; var ; var=var->hashNext) {
         if (!Q_stricmp(var_name, var->name)) {
             return var;
         }
     }
     return NULL;
 }
References generateHashValue(), cvar_s::hashNext, hashTable, cvar_s::name, NULL, and Q_stricmp().
Referenced by Cvar_Command(), Cvar_Flags(), Cvar_Get(), Cvar_Print_f(), Cvar_Register(), Cvar_Set2(), Cvar_Unset_f(), Cvar_VariableIntegerValue(), Cvar_VariableString(), Cvar_VariableStringBuffer(), and Cvar_VariableValue().
Cvar_Flags()
int Cvar_Flags (const char * var_name)
Definition at line 167 of file cvar.c.
 {
     cvar_t *var;
     if(!(var = Cvar_FindVar(var_name)))
         return CVAR_NONEXISTENT;
     else
     {
         if(var->modified)
             return var->flags | CVAR_MODIFIED;
         else
             return var->flags;
     }
 }
References Cvar_FindVar(), CVAR_MODIFIED, CVAR_NONEXISTENT, cvar_s::flags, and cvar_s::modified.
Referenced by CL_ParseGamestate(), CL_SystemInfoChanged(), Com_StartupVariable(), and Cvar_SetSafe().
Cvar_ForceReset()
void Cvar_ForceReset (const char * var_name)
Definition at line 709 of file cvar.c.
 {
     Cvar_Set2(var_name, NULL, qtrue);
 }
References Cvar_Set2(), NULL, and qtrue.
Referenced by CL_InitRef(), and FS_Startup().
Cvar_Get()
cvar_t* Cvar_Get (const char * var_name, const char * var_value, int flags)
Definition at line 310 of file cvar.c.
{
     cvar_t  *var;
     long    hash;
     int index;
     if ( !var_name || ! var_value ) {
         Com_Error( ERR_FATAL, "Cvar_Get: NULL parameter" );
     }
     if ( !Cvar_ValidateString( var_name ) ) {
         Com_Printf("invalid cvar name string: %s\n", var_name );
         var_name = "BADNAME";
     }
 #if 0       // FIXME: values with backslash happen
     if ( !Cvar_ValidateString( var_value ) ) {
         Com_Printf("invalid cvar value string: %s\n", var_value );
         var_value = "BADVALUE";
     }
 #endif
     var = Cvar_FindVar (var_name);
     if(var)
     {
         var_value = Cvar_Validate(var, var_value, qfalse);
         // Make sure the game code cannot mark engine-added variables as gamecode vars
         if(var->flags & CVAR_VM_CREATED)
         {
             if(!(flags & CVAR_VM_CREATED))
                 var->flags &= ~CVAR_VM_CREATED;
         }
         else if (!(var->flags & CVAR_USER_CREATED))
         {
             if(flags & CVAR_VM_CREATED)
                 flags &= ~CVAR_VM_CREATED;
         }
         // if the C code is now specifying a variable that the user already
         // set a value for, take the new value as the reset value
         if(var->flags & CVAR_USER_CREATED)
         {
             var->flags &= ~CVAR_USER_CREATED;
             Z_Free( var->resetString );
             var->resetString = CopyString( var_value );
             if(flags & CVAR_ROM)
             {
                 // this variable was set by the user,
                 // so force it to value given by the engine.
                 if(var->latchedString)
                     Z_Free(var->latchedString);
                 var->latchedString = CopyString(var_value);
             }
         }
         // Make sure servers cannot mark engine-added variables as SERVER_CREATED
         if(var->flags & CVAR_SERVER_CREATED)
         {
             if(!(flags & CVAR_SERVER_CREATED))
                 var->flags &= ~CVAR_SERVER_CREATED;
         }
         else
         {
             if(flags & CVAR_SERVER_CREATED)
                 flags &= ~CVAR_SERVER_CREATED;
         }
         var->flags |= flags;
         // only allow one non-empty reset string without a warning
         if ( !var->resetString[0] ) {
             // we don't have a reset string yet
             Z_Free( var->resetString );
             var->resetString = CopyString( var_value );
         } else if ( var_value[0] && strcmp( var->resetString, var_value ) ) {
             Com_DPrintf( "Warning: cvar \"%s\" given initial values: \"%s\" and \"%s\"\n",
                 var_name, var->resetString, var_value );
         }
         // if we have a latched string, take that value now
         if ( var->latchedString ) {
             char *s;
             s = var->latchedString;
             var->latchedString = NULL;  // otherwise cvar_set2 would free it
             Cvar_Set2( var_name, s, qtrue );
             Z_Free( s );
         }
         // ZOID--needs to be set so that cvars the game sets as
         // SERVERINFO get sent to clients
         cvar_modifiedFlags |= flags;
         return var;
     }
     //
     // allocate a new cvar
     //
     // find a free cvar
     for(index = 0; index < MAX_CVARS; index++)
     {
         if(!cvar_indexes[index].name)
             break;
     }
     if(index >= MAX_CVARS)
     {
         if(!com_errorEntered)
             Com_Error(ERR_FATAL, "Error: Too many cvars, cannot create a new one!");
         return NULL;
     }
     var = &cvar_indexes[index];
     if(index >= cvar_numIndexes)
         cvar_numIndexes = index + 1;
     var->name = CopyString (var_name);
     var->string = CopyString (var_value);
     var->modified = qtrue;
     var->modificationCount = 1;
     var->value = atof (var->string);
     var->integer = atoi(var->string);
     var->resetString = CopyString( var_value );
     var->validate = qfalse;
     var->description = NULL;
     // link the variable in
     var->next = cvar_vars;
     if(cvar_vars)
         cvar_vars->prev = var;
     var->prev = NULL;
     cvar_vars = var;
     var->flags = flags;
     // note what types of cvars have been modified (userinfo, archive, serverinfo, systeminfo)
     cvar_modifiedFlags |= var->flags;
     hash = generateHashValue(var_name);
     var->hashIndex = hash;
     var->hashNext = hashTable[hash];
     if(hashTable[hash])
         hashTable[hash]->hashPrev = var;
     var->hashPrev = NULL;
     hashTable[hash] = var;
     return var;
 }
References Com_DPrintf(), Com_Error(), com_errorEntered, Com_Printf(), CopyString(), Cvar_FindVar(), cvar_indexes, cvar_modifiedFlags, cvar_numIndexes, CVAR_ROM, CVAR_SERVER_CREATED, Cvar_Set2(), CVAR_USER_CREATED, Cvar_Validate(), Cvar_ValidateString(), cvar_vars, CVAR_VM_CREATED, cvar_s::description, ERR_FATAL, cvar_s::flags, generateHashValue(), cvar_s::hashIndex, cvar_s::hashNext, cvar_s::hashPrev, hashTable, cvar_s::integer, cvar_s::latchedString, MAX_CVARS, cvar_s::modificationCount, cvar_s::modified, cvar_s::name, cvar_s::next, NULL, cvar_s::prev, qfalse, qtrue, cvar_s::resetString, s, cvar_s::string, cvar_s::validate, cvar_s::value, and Z_Free().
Referenced by BotDrawDebugPolygons(), CL_Init(), CL_InitInput(), CL_InitRef(), CL_RequestAuthorization(), CL_SystemInfoChanged(), CM_DrawDebugSurface(), CM_LoadMap(), CM_TracePointThroughPatchCollide(), CM_TraceThroughPatchCollide(), Com_Frame(), Com_Init(), Com_InitHunkMemory(), Com_InitJournaling(), Com_InitZoneMemory(), Com_StartupVariable(), Con_Init(), Cvar_Init(), Cvar_Register(), Cvar_Set2(), FS_Startup(), NET_GetCvars(), Netchan_Init(), S_AL_Init(), S_Base_Init(), S_Init(), SCR_Init(), SND_setup(), SV_BotInitCvars(), SV_BoundMaxClients(), SV_Init(), SV_InitGameProgs(), SV_Map_f(), and VM_Init().
Cvar_InfoString()
char* Cvar_InfoString (int bit)
Definition at line 1236 of file cvar.c.
 {
     static char info[MAX_INFO_STRING];
     cvar_t  *var;
     info[0] = 0;
     for(var = cvar_vars; var; var = var->next)
     {
         if(var->name && (var->flags & bit))
             Info_SetValueForKey (info, var->name, var->string);
     }
     return info;
 }
References bit, cvar_vars, cvar_s::flags, Info_SetValueForKey(), MAX_INFO_STRING, cvar_s::name, cvar_s::next, and cvar_s::string.
Referenced by CL_CheckForResend(), CL_CheckUserinfo(), CL_Clientinfo_f(), Cvar_InfoStringBuffer(), SV_Frame(), SV_GetServerinfo(), SV_Serverinfo_f(), SV_SpawnServer(), and SVC_Status().
Cvar_InfoString_Big()
char* Cvar_InfoString_Big (int bit)
Definition at line 1259 of file cvar.c.
 {
     static char info[BIG_INFO_STRING];
     cvar_t  *var;
     info[0] = 0;
     for (var = cvar_vars; var; var = var->next)
     {
         if(var->name && (var->flags & bit))
             Info_SetValueForKey_Big (info, var->name, var->string);
     }
     return info;
 }
References BIG_INFO_STRING, bit, cvar_vars, cvar_s::flags, Info_SetValueForKey_Big(), cvar_s::name, cvar_s::next, and cvar_s::string.
Referenced by SV_Frame(), SV_SpawnServer(), and SV_Systeminfo_f().
Cvar_InfoStringBuffer()
void Cvar_InfoStringBuffer (int bit, char * buff, int buffsize)
Definition at line 1281 of file cvar.c.
{
     Q_strncpyz(buff,Cvar_InfoString(bit),buffsize);
 }
References bit, Cvar_InfoString(), and Q_strncpyz().
Referenced by CL_UISystemCalls().
Cvar_Init()
void Cvar_Init (void)
Definition at line 1438 of file cvar.c.
 {
     Com_Memset(cvar_indexes, '\0', sizeof(cvar_indexes));
     Com_Memset(hashTable, '\0', sizeof(hashTable));
     cvar_cheats = Cvar_Get("sv_cheats", "1", CVAR_ROM | CVAR_SYSTEMINFO );
     Cmd_AddCommand ("print", Cvar_Print_f);
     Cmd_AddCommand ("toggle", Cvar_Toggle_f);
     Cmd_SetCommandCompletionFunc( "toggle", Cvar_CompleteCvarName );
     Cmd_AddCommand ("set", Cvar_Set_f);
     Cmd_SetCommandCompletionFunc( "set", Cvar_CompleteCvarName );
     Cmd_AddCommand ("sets", Cvar_Set_f);
     Cmd_SetCommandCompletionFunc( "sets", Cvar_CompleteCvarName );
     Cmd_AddCommand ("setu", Cvar_Set_f);
     Cmd_SetCommandCompletionFunc( "setu", Cvar_CompleteCvarName );
     Cmd_AddCommand ("seta", Cvar_Set_f);
     Cmd_SetCommandCompletionFunc( "seta", Cvar_CompleteCvarName );
     Cmd_AddCommand ("reset", Cvar_Reset_f);
     Cmd_SetCommandCompletionFunc( "reset", Cvar_CompleteCvarName );
     Cmd_AddCommand ("unset", Cvar_Unset_f);
     Cmd_SetCommandCompletionFunc("unset", Cvar_CompleteCvarName);
     Cmd_AddCommand ("cvarlist", Cvar_List_f);
     Cmd_AddCommand ("cvar_modified", Cvar_ListModified_f);
     Cmd_AddCommand ("cvar_restart", Cvar_Restart_f);
 }
References Cmd_AddCommand(), Cmd_SetCommandCompletionFunc(), Com_Memset, cvar_cheats, Cvar_CompleteCvarName(), Cvar_Get(), cvar_indexes, Cvar_List_f(), Cvar_ListModified_f(), Cvar_Print_f(), Cvar_Reset_f(), Cvar_Restart_f(), CVAR_ROM, Cvar_Set_f(), CVAR_SYSTEMINFO, Cvar_Toggle_f(), Cvar_Unset_f(), and hashTable.
Referenced by Com_Init().
Cvar_List_f()
void Cvar_List_f (void)
Definition at line 953 of file cvar.c.
{
     cvar_t  *var;
     int     i;
     char    *match;
     if ( Cmd_Argc() > 1 ) {
         match = Cmd_Argv( 1 );
     } else {
         match = NULL;
     }
     i = 0;
     for (var = cvar_vars ; var ; var = var->next, i++)
     {
         if(!var->name || (match && !Com_Filter(match, var->name, qfalse)))
             continue;
         if (var->flags & CVAR_SERVERINFO) {
             Com_Printf("S");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_SYSTEMINFO) {
             Com_Printf("s");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_USERINFO) {
             Com_Printf("U");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_ROM) {
             Com_Printf("R");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_INIT) {
             Com_Printf("I");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_ARCHIVE) {
             Com_Printf("A");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_LATCH) {
             Com_Printf("L");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_CHEAT) {
             Com_Printf("C");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_USER_CREATED) {
             Com_Printf("?");
         } else {
             Com_Printf(" ");
         }
         Com_Printf (" %s \"%s\"\n", var->name, var->string);
     }
     Com_Printf ("\n%i total cvars\n", i);
     Com_Printf ("%i cvar indexes\n", cvar_numIndexes);
 }
References Cmd_Argc(), Cmd_Argv(), Com_Filter(), Com_Printf(), CVAR_ARCHIVE, CVAR_CHEAT, CVAR_INIT, CVAR_LATCH, cvar_numIndexes, CVAR_ROM, CVAR_SERVERINFO, CVAR_SYSTEMINFO, CVAR_USER_CREATED, CVAR_USERINFO, cvar_vars, cvar_s::flags, cvar_s::name, cvar_s::next, NULL, qfalse, and cvar_s::string.
Referenced by Cvar_Init().
Cvar_ListModified_f()
void Cvar_ListModified_f (void)
Definition at line 1028 of file cvar.c.
{
     cvar_t  *var;
     int     totalModified;
     char    *value;
     char    *match;
     if ( Cmd_Argc() > 1 ) {
         match = Cmd_Argv( 1 );
     } else {
         match = NULL;
     }
     totalModified = 0;
     for (var = cvar_vars ; var ; var = var->next)
     {
         if ( !var->name || !var->modificationCount )
             continue;
         value = var->latchedString ? var->latchedString : var->string;
         if ( !strcmp( value, var->resetString ) )
             continue;
         totalModified++;
         if (match && !Com_Filter(match, var->name, qfalse))
             continue;
         if (var->flags & CVAR_SERVERINFO) {
             Com_Printf("S");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_SYSTEMINFO) {
             Com_Printf("s");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_USERINFO) {
             Com_Printf("U");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_ROM) {
             Com_Printf("R");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_INIT) {
             Com_Printf("I");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_ARCHIVE) {
             Com_Printf("A");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_LATCH) {
             Com_Printf("L");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_CHEAT) {
             Com_Printf("C");
         } else {
             Com_Printf(" ");
         }
         if (var->flags & CVAR_USER_CREATED) {
             Com_Printf("?");
         } else {
             Com_Printf(" ");
         }
         Com_Printf (" %s \"%s\", default \"%s\"\n", var->name, value, var->resetString);
     }
     Com_Printf ("\n%i total modified cvars\n", totalModified);
 }
References Cmd_Argc(), Cmd_Argv(), Com_Filter(), Com_Printf(), CVAR_ARCHIVE, CVAR_CHEAT, CVAR_INIT, CVAR_LATCH, CVAR_ROM, CVAR_SERVERINFO, CVAR_SYSTEMINFO, CVAR_USER_CREATED, CVAR_USERINFO, cvar_vars, cvar_s::flags, cvar_s::latchedString, cvar_s::modificationCount, cvar_s::name, cvar_s::next, NULL, qfalse, cvar_s::resetString, and cvar_s::string.
Referenced by Cvar_Init().
Cvar_Print()
void Cvar_Print (cvar_t * v)
Definition at line 475 of file cvar.c.
{
     Com_Printf ("\"%s\" is:\"%s" S_COLOR_WHITE "\"",
             v->name, v->string );
     if ( !( v->flags & CVAR_ROM ) ) {
         if ( !Q_stricmp( v->string, v->resetString ) ) {
             Com_Printf (", the default" );
         } else {
             Com_Printf (" default:\"%s" S_COLOR_WHITE "\"",
                     v->resetString );
         }
     }
     Com_Printf ("\n");
     if ( v->latchedString ) {
         Com_Printf( "latched: \"%s\"\n", v->latchedString );
     }
     if ( v->description ) {
         Com_Printf( "%s\n", v->description );
     }
 }
References Com_Printf(), CVAR_ROM, cvar_s::description, cvar_s::flags, cvar_s::latchedString, cvar_s::name, Q_stricmp(), cvar_s::resetString, S_COLOR_WHITE, and cvar_s::string.
Referenced by Cvar_Command(), and Cvar_Print_f().
Cvar_Print_f()
void Cvar_Print_f (void)
Definition at line 779 of file cvar.c.
 {
     char *name;
     cvar_t *cv;
     if(Cmd_Argc() != 2)
     {
         Com_Printf ("usage: print <variable>\n");
         return;
     }
     name = Cmd_Argv(1);
     cv = Cvar_FindVar(name);
     if(cv)
         Cvar_Print(cv);
     else
         Com_Printf ("Cvar %s does not exist.\n", name);
 }
References Cmd_Argc(), Cmd_Argv(), Com_Printf(), Cvar_FindVar(), and Cvar_Print().
Referenced by Cvar_Init(), and Cvar_Set_f().
Cvar_Register()
void Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
Definition at line 1325 of file cvar.c.
 {
     cvar_t  *cv;
     // There is code in Cvar_Get to prevent CVAR_ROM cvars being changed by the
     // user. In other words CVAR_ARCHIVE and CVAR_ROM are mutually exclusive
     // flags. Unfortunately some historical game code (including single player
     // baseq3) sets both flags. We unset CVAR_ROM for such cvars.
     if ((flags & (CVAR_ARCHIVE | CVAR_ROM)) == (CVAR_ARCHIVE | CVAR_ROM)) {
         Com_DPrintf( S_COLOR_YELLOW "WARNING: Unsetting CVAR_ROM from cvar '%s', "
             "since it is also CVAR_ARCHIVE\n", varName );
         flags &= ~CVAR_ROM;
     }
     // Don't allow VM to specific a different creator or other internal flags.
     if ( flags & CVAR_USER_CREATED ) {
         Com_DPrintf( S_COLOR_YELLOW "WARNING: VM tried to set CVAR_USER_CREATED on cvar '%s'\n", varName );
         flags &= ~CVAR_USER_CREATED;
     }
     if ( flags & CVAR_SERVER_CREATED ) {
         Com_DPrintf( S_COLOR_YELLOW "WARNING: VM tried to set CVAR_SERVER_CREATED on cvar '%s'\n", varName );
         flags &= ~CVAR_SERVER_CREATED;
     }
     if ( flags & CVAR_PROTECTED ) {
         Com_DPrintf( S_COLOR_YELLOW "WARNING: VM tried to set CVAR_PROTECTED on cvar '%s'\n", varName );
         flags &= ~CVAR_PROTECTED;
     }
     if ( flags & CVAR_MODIFIED ) {
         Com_DPrintf( S_COLOR_YELLOW "WARNING: VM tried to set CVAR_MODIFIED on cvar '%s'\n", varName );
         flags &= ~CVAR_MODIFIED;
     }
     if ( flags & CVAR_NONEXISTENT ) {
         Com_DPrintf( S_COLOR_YELLOW "WARNING: VM tried to set CVAR_NONEXISTENT on cvar '%s'\n", varName );
         flags &= ~CVAR_NONEXISTENT;
     }
     cv = Cvar_FindVar(varName);
     // Don't modify cvar if it's protected.
     if ( cv && ( cv->flags & CVAR_PROTECTED ) ) {
         Com_DPrintf( S_COLOR_YELLOW "WARNING: VM tried to register protected cvar '%s' with value '%s'%s\n",
             varName, defaultValue, ( flags & ~cv->flags ) != 0 ? " and new flags" : "" );
     } else {
         cv = Cvar_Get(varName, defaultValue, flags | CVAR_VM_CREATED);
     }
     if (!vmCvar)
         return;
     vmCvar->handle = cv - cvar_indexes;
     vmCvar->modificationCount = -1;
     Cvar_Update( vmCvar );
 }
References Com_DPrintf(), CVAR_ARCHIVE, Cvar_FindVar(), Cvar_Get(), cvar_indexes, CVAR_MODIFIED, CVAR_NONEXISTENT, CVAR_PROTECTED, CVAR_ROM, CVAR_SERVER_CREATED, Cvar_Update(), CVAR_USER_CREATED, CVAR_VM_CREATED, cvar_s::flags, vmCvar_t::handle, vmCvar_t::modificationCount, and S_COLOR_YELLOW.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), and SV_GameSystemCalls().
Cvar_Reset()
void Cvar_Reset (const char * var_name)
Definition at line 700 of file cvar.c.
{
     Cvar_Set2( var_name, NULL, qfalse );
 }
References Cvar_Set2(), NULL, and qfalse.
Referenced by CL_UISystemCalls(), and Cvar_Reset_f().
Cvar_Reset_f()
void Cvar_Reset_f (void)
Definition at line 900 of file cvar.c.
{
     if ( Cmd_Argc() != 2 ) {
         Com_Printf ("usage: reset <variable>\n");
         return;
     }
     Cvar_Reset( Cmd_Argv( 1 ) );
 }
References Cmd_Argc(), Cmd_Argv(), Com_Printf(), and Cvar_Reset().
Referenced by Cvar_Init().
Cvar_Restart()
void Cvar_Restart (qboolean unsetVM)
Definition at line 1192 of file cvar.c.
 {
     cvar_t  *curvar;
     curvar = cvar_vars;
     while(curvar)
     {
         if((curvar->flags & CVAR_USER_CREATED) ||
             (unsetVM && (curvar->flags & CVAR_VM_CREATED)))
         {
             // throw out any variables the user/vm created
             curvar = Cvar_Unset(curvar);
             continue;
         }
         if(!(curvar->flags & (CVAR_ROM | CVAR_INIT | CVAR_NORESTART)))
         {
             // Just reset the rest to their default values.
             Cvar_Set2(curvar->name, curvar->resetString, qfalse);
         }
         curvar = curvar->next;
     }
 }
References CVAR_INIT, CVAR_NORESTART, CVAR_ROM, Cvar_Set2(), Cvar_Unset(), CVAR_USER_CREATED, cvar_vars, CVAR_VM_CREATED, cvar_s::flags, cvar_s::name, cvar_s::next, qfalse, and cvar_s::resetString.
Referenced by Com_GameRestart(), and Cvar_Restart_f().
Cvar_Restart_f()
void Cvar_Restart_f (void)
Definition at line 1226 of file cvar.c.
 {
     Cvar_Restart(qfalse);
 }
References Cvar_Restart(), and qfalse.
Referenced by Cvar_Init().
Cvar_Set()
void Cvar_Set (const char * var_name, const char * value)
Definition at line 628 of file cvar.c.
{
     Cvar_Set2 (var_name, value, qtrue);
 }
References Cvar_Set2(), and qtrue.
Referenced by CL_BeginDownload(), CL_Connect_f(), CL_Disconnect(), CL_Disconnect_f(), CL_DownloadsComplete(), CL_FirstSnapshot(), CL_Init(), CL_InitDownloads(), CL_InitRef(), CL_KeyDownEvent(), CL_MapLoading(), CL_MotdPacket(), CL_NextDemo(), CL_NextDownload(), CL_ParseGamestate(), CL_PlayDemo_f(), CL_ReadyToSendPacket(), CL_Reconnect_f(), CL_SetModel_f(), CL_Shutdown(), CL_SystemInfoChanged(), CL_UpdateGUID(), CL_Vid_Restart_f(), CL_WritePacket(), Com_DetectAltivec(), Com_Error(), Com_GameRestart_f(), Com_Init(), Com_InitJournaling(), Cvar_CheckRange(), Cvar_SetCheatState(), Cvar_SetSafe(), Cvar_SetValue(), FS_CheckPak0(), FS_InitFilesystem(), FS_Restart(), RoQShutdown(), S_Init(), SV_BoundMaxClients(), SV_CheckPaused(), SV_Frame(), SV_Map_f(), SV_MapRestart_f(), SV_RankBegin(), SV_RankCloseContext(), SV_RankEnd(), SV_RankError(), SV_RankNewGameCBF(), SV_RateMsec(), SV_Shutdown(), SV_SpawnServer(), SV_Startup(), Sys_Init(), and Sys_InitPIDFile().
Cvar_Set2()
cvar_t* Cvar_Set2 (const char * var_name, const char * value, qboolean force)
Definition at line 504 of file cvar.c.
{
     cvar_t  *var;
 //  Com_DPrintf( "Cvar_Set2: %s %s\n", var_name, value );
     if ( !Cvar_ValidateString( var_name ) ) {
         Com_Printf("invalid cvar name string: %s\n", var_name );
         var_name = "BADNAME";
     }
 #if 0   // FIXME
     if ( value && !Cvar_ValidateString( value ) ) {
         Com_Printf("invalid cvar value string: %s\n", value );
         var_value = "BADVALUE";
     }
 #endif
     var = Cvar_FindVar (var_name);
     if (!var) {
         if ( !value ) {
             return NULL;
         }
         // create it
         if ( !force ) {
             return Cvar_Get( var_name, value, CVAR_USER_CREATED );
         } else {
             return Cvar_Get (var_name, value, 0);
         }
     }
     if (!value ) {
         value = var->resetString;
     }
     value = Cvar_Validate(var, value, qtrue);
     if((var->flags & CVAR_LATCH) && var->latchedString)
     {
         if(!strcmp(value, var->string))
         {
             Z_Free(var->latchedString);
             var->latchedString = NULL;
             return var;
         }
         if(!strcmp(value, var->latchedString))
             return var;
     }
     else if(!strcmp(value, var->string))
         return var;
     // note what types of cvars have been modified (userinfo, archive, serverinfo, systeminfo)
     cvar_modifiedFlags |= var->flags;
     if (!force)
     {
         if (var->flags & CVAR_ROM)
         {
             Com_Printf ("%s is read only.\n", var_name);
             return var;
         }
         if (var->flags & CVAR_INIT)
         {
             Com_Printf ("%s is write protected.\n", var_name);
             return var;
         }
         if ((var->flags & CVAR_CHEAT) && !cvar_cheats->integer)
         {
             Com_Printf ("%s is cheat protected.\n", var_name);
             return var;
         }
         if (var->flags & CVAR_LATCH)
         {
             if (var->latchedString)
             {
                 if (strcmp(value, var->latchedString) == 0)
                     return var;
                 Z_Free (var->latchedString);
             }
             else
             {
                 if (strcmp(value, var->string) == 0)
                     return var;
             }
             Com_Printf ("%s will be changed upon restarting.\n", var_name);
             var->latchedString = CopyString(value);
             var->modified = qtrue;
             var->modificationCount++;
             return var;
         }
     }
     else
     {
         if (var->latchedString)
         {
             Z_Free (var->latchedString);
             var->latchedString = NULL;
         }
     }
     if (!strcmp(value, var->string))
         return var;     // not changed
     var->modified = qtrue;
     var->modificationCount++;
     Z_Free (var->string);   // free the old value string
     var->string = CopyString(value);
     var->value = atof (var->string);
     var->integer = atoi (var->string);
     return var;
 }
References Com_Printf(), CopyString(), CVAR_CHEAT, cvar_cheats, Cvar_FindVar(), Cvar_Get(), CVAR_INIT, CVAR_LATCH, cvar_modifiedFlags, CVAR_ROM, CVAR_USER_CREATED, Cvar_Validate(), Cvar_ValidateString(), cvar_s::flags, cvar_s::integer, cvar_s::latchedString, cvar_s::modificationCount, cvar_s::modified, NULL, qtrue, cvar_s::resetString, cvar_s::string, cvar_s::value, and Z_Free().
Referenced by CL_OldGame(), Com_StartupVariable(), Cvar_Command(), Cvar_ForceReset(), Cvar_Get(), Cvar_Reset(), Cvar_Restart(), Cvar_Set(), Cvar_Set_f(), Cvar_SetLatched(), and Cvar_Toggle_f().
Cvar_Set_f()
void Cvar_Set_f (void)
Definition at line 852 of file cvar.c.
{
     int     c;
     char    *cmd;
     cvar_t  *v;
     c = Cmd_Argc();
     cmd = Cmd_Argv(0);
     if ( c < 2 ) {
         Com_Printf ("usage: %s <variable> <value>\n", cmd);
         return;
     }
     if ( c == 2 ) {
         Cvar_Print_f();
         return;
     }
     v = Cvar_Set2 (Cmd_Argv(1), Cmd_ArgsFrom(2), qfalse);
     if( !v ) {
         return;
     }
     switch( cmd[3] ) {
         case 'a':
             if( !( v->flags & CVAR_ARCHIVE ) ) {
                 v->flags |= CVAR_ARCHIVE;
                 cvar_modifiedFlags |= CVAR_ARCHIVE;
             }
             break;
         case 'u':
             if( !( v->flags & CVAR_USERINFO ) ) {
                 v->flags |= CVAR_USERINFO;
                 cvar_modifiedFlags |= CVAR_USERINFO;
             }
             break;
         case 's':
             if( !( v->flags & CVAR_SERVERINFO ) ) {
                 v->flags |= CVAR_SERVERINFO;
                 cvar_modifiedFlags |= CVAR_SERVERINFO;
             }
             break;
     }
 }
References Cmd_Argc(), Cmd_ArgsFrom(), Cmd_Argv(), Com_Printf(), CVAR_ARCHIVE, cvar_modifiedFlags, Cvar_Print_f(), CVAR_SERVERINFO, Cvar_Set2(), CVAR_USERINFO, cvar_s::flags, and qfalse.
Referenced by Cvar_Init().
Cvar_SetCheatState()
void Cvar_SetCheatState (void)
Definition at line 721 of file cvar.c.
 {
     cvar_t  *var;
     // set all default vars to the safe value
     for(var = cvar_vars; var ; var = var->next)
     {
         if(var->flags & CVAR_CHEAT)
         {
             // the CVAR_LATCHED|CVAR_CHEAT vars might escape the reset here
             // because of a different var->latchedString
             if (var->latchedString)
             {
                 Z_Free(var->latchedString);
                 var->latchedString = NULL;
             }
             if (strcmp(var->resetString,var->string))
                 Cvar_Set(var->name, var->resetString);
         }
     }
 }
References CVAR_CHEAT, Cvar_Set(), cvar_vars, cvar_s::flags, cvar_s::latchedString, cvar_s::name, cvar_s::next, NULL, cvar_s::resetString, cvar_s::string, and Z_Free().
Referenced by CL_InitCGame(), and CL_SystemInfoChanged().
Cvar_SetDescription()
void Cvar_SetDescription (cvar_t * var, const char * var_description)
Definition at line 1306 of file cvar.c.
 {
     if( var_description && var_description[0] != '\0' )
     {
         if( var->description != NULL )
         {
             Z_Free( var->description );
         }
         var->description = CopyString( var_description );
     }
 }
References CopyString(), cvar_s::description, NULL, and Z_Free().
Referenced by CL_InitRef(), and Com_InitHunkMemory().
Cvar_SetLatched()
void Cvar_SetLatched (const char * var_name, const char * value)
Definition at line 659 of file cvar.c.
{
     Cvar_Set2 (var_name, value, qfalse);
 }
References Cvar_Set2(), and qfalse.
Referenced by SV_Map_f().
Cvar_SetSafe()
void Cvar_SetSafe (const char * var_name, const char * value)
Definition at line 637 of file cvar.c.
 {
     int flags = Cvar_Flags( var_name );
     if((flags != CVAR_NONEXISTENT) && (flags & CVAR_PROTECTED))
     {
         if( value )
             Com_Error( ERR_DROP, "Restricted source tried to set "
                 "\"%s\" to \"%s\"", var_name, value );
         else
             Com_Error( ERR_DROP, "Restricted source tried to "
                 "modify \"%s\"", var_name );
         return;
     }
     Cvar_Set( var_name, value );
 }
References Com_Error(), Cvar_Flags(), CVAR_NONEXISTENT, CVAR_PROTECTED, Cvar_Set(), and ERR_DROP.
Referenced by CL_CgameSystemCalls(), CL_SystemInfoChanged(), CL_UISystemCalls(), Cvar_SetValueSafe(), and SV_GameSystemCalls().
Cvar_SetValue()
void Cvar_SetValue (const char * var_name, float value)
Definition at line 668 of file cvar.c.
{
     char    val[32];
     if ( value == (int)value ) {
         Com_sprintf (val, sizeof(val), "%i",(int)value);
     } else {
         Com_sprintf (val, sizeof(val), "%f",value);
     }
     Cvar_Set (var_name, val);
 }
References Com_sprintf(), and Cvar_Set().
Referenced by CL_BeginDownload(), CL_InitRef(), CL_KeyDownEvent(), CL_ParseDownload(), Com_Printf(), NET_OpenIP(), NET_SetMulticast6(), and SV_Map_f().
Cvar_SetValueSafe()
void Cvar_SetValueSafe (const char * var_name, float value)
Definition at line 684 of file cvar.c.
 {
     char val[32];
     if( Q_isintegral( value ) )
         Com_sprintf( val, sizeof(val), "%i", (int)value );
     else
         Com_sprintf( val, sizeof(val), "%f", value );
     Cvar_SetSafe( var_name, val );
 }
References Com_sprintf(), Cvar_SetSafe(), and Q_isintegral().
Referenced by CL_UISystemCalls().
Cvar_Toggle_f()
void Cvar_Toggle_f (void)
Definition at line 808 of file cvar.c.
{
     int     i, c = Cmd_Argc();
     char        *curval;
     if(c < 2) {
         Com_Printf("usage: toggle <variable> [value1, value2, ...]\n");
         return;
     }
     if(c == 2) {
         Cvar_Set2(Cmd_Argv(1), va("%d",
             !Cvar_VariableValue(Cmd_Argv(1))),
             qfalse);
         return;
     }
     if(c == 3) {
         Com_Printf("toggle: nothing to toggle to\n");
         return;
     }
     curval = Cvar_VariableString(Cmd_Argv(1));
     // don't bother checking the last arg for a match since the desired
     // behaviour is the same as no match (set to the first argument)
     for(i = 2; i + 1 < c; i++) {
         if(strcmp(curval, Cmd_Argv(i)) == 0) {
             Cvar_Set2(Cmd_Argv(1), Cmd_Argv(i + 1), qfalse);
             return;
         }
     }
     // fallback
     Cvar_Set2(Cmd_Argv(1), Cmd_Argv(2), qfalse);
 }
References Cmd_Argc(), Cmd_Argv(), Com_Printf(), Cvar_Set2(), Cvar_VariableString(), Cvar_VariableValue(), qfalse, and va().
Referenced by Cvar_Init().
Cvar_Unset()
cvar_t* Cvar_Unset (cvar_t * cv)
Definition at line 1115 of file cvar.c.
 {
     cvar_t *next = cv->next;
     // note what types of cvars have been modified (userinfo, archive, serverinfo, systeminfo)
     cvar_modifiedFlags |= cv->flags;
     if(cv->name)
         Z_Free(cv->name);
     if(cv->string)
         Z_Free(cv->string);
     if(cv->latchedString)
         Z_Free(cv->latchedString);
     if(cv->resetString)
         Z_Free(cv->resetString);
     if(cv->description)
         Z_Free(cv->description);
     if(cv->prev)
         cv->prev->next = cv->next;
     else
         cvar_vars = cv->next;
     if(cv->next)
         cv->next->prev = cv->prev;
     if(cv->hashPrev)
         cv->hashPrev->hashNext = cv->hashNext;
     else
         hashTable[cv->hashIndex] = cv->hashNext;
     if(cv->hashNext)
         cv->hashNext->hashPrev = cv->hashPrev;
     Com_Memset(cv, '\0', sizeof(*cv));
     return next;
 }
References Com_Memset, cvar_modifiedFlags, cvar_vars, cvar_s::description, cvar_s::flags, cvar_s::hashIndex, cvar_s::hashNext, cvar_s::hashPrev, hashTable, cvar_s::latchedString, cvar_s::name, cvar_s::next, hunkblock_s::next, cvar_s::prev, cvar_s::resetString, cvar_s::string, and Z_Free().
Referenced by Cvar_Restart(), and Cvar_Unset_f().
Cvar_Unset_f()
void Cvar_Unset_f (void)
Definition at line 1160 of file cvar.c.
 {
     cvar_t *cv;
     if(Cmd_Argc() != 2)
     {
         Com_Printf("Usage: %s <varname>\n", Cmd_Argv(0));
         return;
     }
     cv = Cvar_FindVar(Cmd_Argv(1));
     if(!cv)
         return;
     if(cv->flags & CVAR_USER_CREATED)
         Cvar_Unset(cv);
     else
         Com_Printf("Error: %s: Variable %s is not user created.\n", Cmd_Argv(0), cv->name);
 }
References Cmd_Argc(), Cmd_Argv(), Com_Printf(), Cvar_FindVar(), Cvar_Unset(), CVAR_USER_CREATED, cvar_s::flags, and cvar_s::name.
Referenced by Cvar_Init().
Cvar_Update()
void Cvar_Update (vmCvar_t * vmCvar)
Definition at line 1387 of file cvar.c.
{
     cvar_t  *cv = NULL;
     assert(vmCvar);
     if ( (unsigned)vmCvar->handle >= cvar_numIndexes ) {
         Com_Error( ERR_DROP, "Cvar_Update: handle out of range" );
     }
     cv = cvar_indexes + vmCvar->handle;
     if ( cv->modificationCount == vmCvar->modificationCount ) {
         return;
     }
     if ( !cv->string ) {
         return;     // variable might have been cleared by a cvar_restart
     }
     vmCvar->modificationCount = cv->modificationCount;
     if ( strlen(cv->string)+1 > MAX_CVAR_VALUE_STRING )
       Com_Error( ERR_DROP, "Cvar_Update: src %s length %u exceeds MAX_CVAR_VALUE_STRING",
              cv->string,
              (unsigned int) strlen(cv->string));
     Q_strncpyz( vmCvar->string, cv->string,  MAX_CVAR_VALUE_STRING );
     vmCvar->value = cv->value;
     vmCvar->integer = cv->integer;
 }
References Com_Error(), cvar_indexes, cvar_numIndexes, ERR_DROP, vmCvar_t::handle, cvar_s::integer, vmCvar_t::integer, MAX_CVAR_VALUE_STRING, cvar_s::modificationCount, vmCvar_t::modificationCount, NULL, Q_strncpyz(), cvar_s::string, vmCvar_t::string, cvar_s::value, and vmCvar_t::value.
Referenced by CL_CgameSystemCalls(), CL_UISystemCalls(), Cvar_Register(), and SV_GameSystemCalls().
Cvar_Validate()
static const char* Cvar_Validate (cvar_t * var, const char * value, qboolean warn) static
Definition at line 203 of file cvar.c.
 {
     static char s[ MAX_CVAR_VALUE_STRING ];
     float valuef;
     qboolean changed = qfalse;
     if( !var->validate )
         return value;
     if( !value )
         return value;
     if( Q_isanumber( value ) )
     {
         valuef = atof( value );
         if( var->integral )
         {
             if( !Q_isintegral( valuef ) )
             {
                 if( warn )
                     Com_Printf( "WARNING: cvar '%s' must be integral", var->name );
                 valuef = (int)valuef;
                 changed = qtrue;
             }
         }
     }
     else
     {
         if( warn )
             Com_Printf( "WARNING: cvar '%s' must be numeric", var->name );
         valuef = atof( var->resetString );
         changed = qtrue;
     }
     if( valuef < var->min )
     {
         if( warn )
         {
             if( changed )
                 Com_Printf( " and is" );
             else
                 Com_Printf( "WARNING: cvar '%s'", var->name );
             if( Q_isintegral( var->min ) )
                 Com_Printf( " out of range (min %d)", (int)var->min );
             else
                 Com_Printf( " out of range (min %f)", var->min );
         }
         valuef = var->min;
         changed = qtrue;
     }
     else if( valuef > var->max )
     {
         if( warn )
         {
             if( changed )
                 Com_Printf( " and is" );
             else
                 Com_Printf( "WARNING: cvar '%s'", var->name );
             if( Q_isintegral( var->max ) )
                 Com_Printf( " out of range (max %d)", (int)var->max );
             else
                 Com_Printf( " out of range (max %f)", var->max );
         }
         valuef = var->max;
         changed = qtrue;
     }
     if( changed )
     {
         if( Q_isintegral( valuef ) )
         {
             Com_sprintf( s, sizeof( s ), "%d", (int)valuef );
             if( warn )
                 Com_Printf( ", setting to %d\n", (int)valuef );
         }
         else
         {
             Com_sprintf( s, sizeof( s ), "%f", valuef );
             if( warn )
                 Com_Printf( ", setting to %f\n", valuef );
         }
         return s;
     }
     else
         return value;
 }
References Com_Printf(), Com_sprintf(), int(), cvar_s::integral, cvar_s::max, MAX_CVAR_VALUE_STRING, cvar_s::min, cvar_s::name, Q_isanumber(), Q_isintegral(), qfalse, qtrue, cvar_s::resetString, s, and cvar_s::validate.
Referenced by Cvar_Get(), and Cvar_Set2().
Cvar_ValidateString()
static qboolean Cvar_ValidateString (const char * s) static
Definition at line 64 of file cvar.c.
{
     if ( !s ) {
         return qfalse;
     }
     if ( strchr( s, '\\' ) ) {
         return qfalse;
     }
     if ( strchr( s, '\"' ) ) {
         return qfalse;
     }
     if ( strchr( s, ';' ) ) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, qtrue, and s.
Referenced by Cvar_Get(), and Cvar_Set2().
Cvar_VariableIntegerValue()
int Cvar_VariableIntegerValue (const char * var_name)
Definition at line 120 of file cvar.c.
{
     cvar_t  *var;
     var = Cvar_FindVar (var_name);
     if (!var)
         return 0;
     return var->integer;
 }
References Cvar_FindVar(), and cvar_s::integer.
Referenced by CL_GetPing(), CL_GlobalServers_f(), CL_InitRef(), CL_KeyDownEvent(), CL_OpenAVIForWriting(), SCR_UpdateScreen(), SV_BotInitBotLib(), SV_GameSystemCalls(), SV_MasterHeartbeat(), and SVC_Info().
Cvar_VariableString()
char* Cvar_VariableString (const char * var_name)
Definition at line 135 of file cvar.c.
{
     cvar_t *var;
     var = Cvar_FindVar (var_name);
     if (!var)
         return "";
     return var->string;
 }
References Cvar_FindVar(), and cvar_s::string.
Referenced by CL_GlobalServers_f(), CL_NextDemo(), CL_NextDownload(), CL_OpenAVIForWriting(), CL_SystemInfoChanged(), CLUI_GetCDKey(), CLUI_SetCDKey(), Cmd_Vstr_f(), Com_WriteConfiguration(), Cvar_Toggle_f(), FS_InitFilesystem(), Log_Open(), PrintCvarMatches(), RoQShutdown(), SV_Frame(), SV_GetChallenge(), SV_MapRestart_f(), SV_RankBegin(), SVC_Info(), Sys_LoadDll(), Sys_PIDFileName(), and UI_DrawConnectScreen().
Cvar_VariableStringBuffer()
void Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
Definition at line 150 of file cvar.c.
{
     cvar_t *var;
     var = Cvar_FindVar (var_name);
     if (!var) {
         *buffer = 0;
     }
     else {
         Q_strncpyz( buffer, var->string, bufsize );
     }
 }
References buffer, Cvar_FindVar(), Q_strncpyz(), and cvar_s::string.
Referenced by CL_CgameSystemCalls(), CL_ParseGamestate(), CL_SetModel_f(), CL_UISystemCalls(), and SV_GameSystemCalls().
Cvar_VariableValue()
float Cvar_VariableValue (const char * var_name)
Definition at line 105 of file cvar.c.
{
     cvar_t  *var;
     var = Cvar_FindVar (var_name);
     if (!var)
         return 0;
     return var->value;
 }
References Cvar_FindVar(), and cvar_s::value.
Referenced by CL_CheckForResend(), CL_ConnectionlessPacket(), CL_InitCGame(), CL_InitUI(), CL_KeyDownEvent(), CL_Record_f(), CL_SystemInfoChanged(), CL_UISystemCalls(), Cvar_Toggle_f(), SV_GetChallenge(), SV_InitGameProgs(), SV_MapRestart_f(), SV_RankBegin(), SV_SpawnServer(), SVC_Info(), and SVC_Status().
Cvar_WriteVariables()
void Cvar_WriteVariables (fileHandle_t f)
Definition at line 916 of file cvar.c.
 {
     cvar_t  *var;
     char    buffer[1024];
     for (var = cvar_vars; var; var = var->next)
     {
         if(!var->name || Q_stricmp( var->name, "cl_cdkey" ) == 0)
             continue;
         if( var->flags & CVAR_ARCHIVE ) {
             // write the latched value, even if it hasn't taken effect yet
             if ( var->latchedString ) {
                 if( strlen( var->name ) + strlen( var->latchedString ) + 10 > sizeof( buffer ) ) {
                     Com_Printf( S_COLOR_YELLOW "WARNING: value of variable "
                             "\"%s\" too long to write to file\n", var->name );
                     continue;
                 }
                 Com_sprintf (buffer, sizeof(buffer), "seta %s \"%s\"\n", var->name, var->latchedString);
             } else {
                 if( strlen( var->name ) + strlen( var->string ) + 10 > sizeof( buffer ) ) {
                     Com_Printf( S_COLOR_YELLOW "WARNING: value of variable "
                             "\"%s\" too long to write to file\n", var->name );
                     continue;
                 }
                 Com_sprintf (buffer, sizeof(buffer), "seta %s \"%s\"\n", var->name, var->string);
             }
             FS_Write( buffer, strlen( buffer ), f );
         }
     }
 }
References buffer, Com_Printf(), Com_sprintf(), CVAR_ARCHIVE, cvar_vars, cvar_s::flags, FS_Write(), cvar_s::latchedString, cvar_s::name, cvar_s::next, Q_stricmp(), S_COLOR_YELLOW, and cvar_s::string.
Referenced by Com_WriteConfigToFile().
generateHashValue()
static long generateHashValue (const char * fname) static
Definition at line 43 of file cvar.c.
{
     int     i;
     long    hash;
     char    letter;
     hash = 0;
     i = 0;
     while (fname[i] != '\0') {
         letter = tolower(fname[i]);
         hash+=(long)(letter)*(i+119);
         i++;
     }
     hash &= (FILE_HASH_SIZE-1);
     return hash;
 }
References FILE_HASH_SIZE, and long().
Referenced by Cvar_FindVar(), and Cvar_Get().
Variable Documentation
cvar_cheats
cvar_t* cvar_cheats
Definition at line 28 of file cvar.c.
Referenced by Cvar_Init(), and Cvar_Set2().
cvar_indexes
cvar_t cvar_indexes[MAX_CVARS]
Definition at line 32 of file cvar.c.
Referenced by Cvar_Get(), Cvar_Init(), Cvar_Register(), and Cvar_Update().
cvar_modifiedFlags
int cvar_modifiedFlags
Definition at line 29 of file cvar.c.
Referenced by CL_CheckForResend(), CL_CheckUserinfo(), CLUI_SetCDKey(), Com_Init(), Com_WriteConfiguration(), Cvar_Get(), Cvar_Set2(), Cvar_Set_f(), Cvar_Unset(), Key_SetBinding(), SV_Frame(), and SV_SpawnServer().
cvar_numIndexes
int cvar_numIndexes
Definition at line 33 of file cvar.c.
Referenced by Cvar_Get(), Cvar_List_f(), and Cvar_Update().
cvar_vars
cvar_t* cvar_vars = NULL
Definition at line 27 of file cvar.c.
Referenced by Cvar_CommandCompletion(), Cvar_Get(), Cvar_InfoString(), Cvar_InfoString_Big(), Cvar_List_f(), Cvar_ListModified_f(), Cvar_Restart(), Cvar_SetCheatState(), Cvar_Unset(), and Cvar_WriteVariables().
hashTable
cvar_t* hashTable[FILE_HASH_SIZE] static
Definition at line 36 of file cvar.c.
Referenced by Cvar_FindVar(), Cvar_Get(), Cvar_Init(), and Cvar_Unset().