ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_main.h File Reference
be_aas_main.h File Reference
Functions
int AAS_Initialized (void)
int AAS_Loaded (void)
float AAS_Time (void)
void AAS_ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
Function Documentation
AAS_Initialized()
int AAS_Initialized (void)
Definition at line 83 of file be_aas_main.c.
 {
     return aasworld.initialized;
 } //end of the function AAS_Initialized
Referenced by Init_AAS_Export().
AAS_Loaded()
int AAS_Loaded (void)
Definition at line 73 of file be_aas_main.c.
 {
     return aasworld.loaded;
 } //end of the function AAS_Loaded
Referenced by BotInitLevelItems().
AAS_ProjectPointOntoVector()
void AAS_ProjectPointOntoVector (vec3_t point, vec3_t vStart, vec3_t vEnd, vec3_t vProj)
Definition at line 204 of file be_aas_main.c.
 {
     vec3_t pVec, vec;
     VectorSubtract( point, vStart, pVec );
     VectorSubtract( vEnd, vStart, vec );
     VectorNormalize( vec );
     // project onto the directional vector for this segment
     VectorMA( vStart, DotProduct( pVec, vec ), vec, vProj );
 } //end of the function AAS_ProjectPointOntoVector
Referenced by AAS_NearestHideArea(), DistanceFromLineSquared(), and DistancePointToLine().
AAS_Time()
float AAS_Time (void)
Definition at line 194 of file be_aas_main.c.
 {
     return aasworld.time;
 } //end of the function AAS_Time
Referenced by AAS_RoutingTime(), AAS_ShowReachableAreas(), AAS_UpdateEntity(), BotAddToAvoidGoals(), BotAddToAvoidReach(), BotAvoidGoalTime(), BotChooseInitialChatMessage(), BotDumpAvoidGoals(), BotGetReachabilityToGoal(), BotItemGoalInVisButNotVisible(), BotMoveToGoal(), BotQueueConsoleMessage(), BotRemoveFromAvoidGoals(), BotReplyChat(), BotTravel_Grapple(), BotUpdateEntityItems(), and Init_AAS_Export().