ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ai_weight.h File Reference
be_ai_weight.h File Reference
Classes
struct fuzzyseperator_s
struct weight_s
struct weightconfig_s
Macros
#define WT_BALANCE 1
#define MAX_WEIGHTS 128
Typedefs
typedef struct fuzzyseperator_s fuzzyseperator_t
typedef struct weight_s weight_t
typedef struct weightconfig_s weightconfig_t
Functions
weightconfig_t * ReadWeightConfig (char *filename)
void FreeWeightConfig (weightconfig_t *config)
qboolean WriteWeightConfig (char *filename, weightconfig_t *config)
int FindFuzzyWeight (weightconfig_t *wc, char *name)
float FuzzyWeight (int *inventory, weightconfig_t *wc, int weightnum)
float FuzzyWeightUndecided (int *inventory, weightconfig_t *wc, int weightnum)
void ScaleWeight (weightconfig_t *config, char *name, float scale)
void ScaleBalanceRange (weightconfig_t *config, float scale)
void EvolveWeightConfig (weightconfig_t *config)
void InterbreedWeightConfigs (weightconfig_t *config1, weightconfig_t *config2, weightconfig_t *configout)
void BotShutdownWeights (void)
Macro Definition Documentation
MAX_WEIGHTS
#define MAX_WEIGHTS 128
Definition at line 33 of file be_ai_weight.h.
WT_BALANCE
#define WT_BALANCE 1
Definition at line 32 of file be_ai_weight.h.
Typedef Documentation
fuzzyseperator_t
typedef struct fuzzyseperator_s fuzzyseperator_t
weight_t
typedef struct weight_s weight_t
weightconfig_t
typedef struct weightconfig_s weightconfig_t
Function Documentation
BotShutdownWeights()
void BotShutdownWeights (void)
Definition at line 912 of file be_ai_weight.c.
 {
     int i;
     for( i = 0; i < MAX_WEIGHT_FILES; i++ )
     {
         if (weightFileList[i])
         {
             FreeWeightConfig2(weightFileList[i]);
             weightFileList[i] = NULL;
         } //end if
     } //end for
 } //end of the function BotShutdownWeights
References FreeWeightConfig2(), MAX_WEIGHT_FILES, NULL, and weightFileList.
Referenced by Export_BotLibShutdown().
EvolveWeightConfig()
void EvolveWeightConfig (weightconfig_t * config)
Definition at line 741 of file be_ai_weight.c.
 {
     int i;
     for (i = 0; i < config->numweights; i++)
     {
         EvolveFuzzySeperator_r(config->weights[i].firstseperator);
     } //end for
 } //end of the function EvolveWeightConfig
References EvolveFuzzySeperator_r(), weight_s::firstseperator, weightconfig_s::numweights, and weightconfig_s::weights.
Referenced by BotMutateGoalFuzzyLogic().
FindFuzzyWeight()
int FindFuzzyWeight (weightconfig_t * wc, char * name)
Definition at line 563 of file be_ai_weight.c.
 {
     int i;
     for (i = 0; i < wc->numweights; i++)
     {
         if (!strcmp(wc->weights[i].name, name))
         {
             return i;
         } //end if
     } //end if
     return -1;
 } //end of the function FindFuzzyWeight
References weight_s::name, weightconfig_s::numweights, and weightconfig_s::weights.
Referenced by ItemWeightIndex(), and WeaponWeightIndex().
FreeWeightConfig()
void FreeWeightConfig (weightconfig_t * config)
Definition at line 149 of file be_ai_weight.c.
 {
     if (!LibVarGetValue("bot_reloadcharacters")) return;
     FreeWeightConfig2(config);
 } //end of the function FreeWeightConfig
References FreeWeightConfig2(), and LibVarGetValue().
Referenced by BotFreeItemWeights(), BotFreeWeaponWeights(), and ReadWeightConfig().
FuzzyWeight()
float FuzzyWeight (int * inventory, weightconfig_t * wc, int weightnum)
Definition at line 656 of file be_ai_weight.c.
 {
 #ifdef EVALUATERECURSIVELY
     return FuzzyWeight_r(inventory, wc->weights[weightnum].firstseperator);
 #else
     fuzzyseperator_t *s;
     s = wc->weights[weightnum].firstseperator;
     if (!s) return 0;
     while(1)
     {
         if (inventory[s->index] < s->value)
         {
             if (s->child) s = s->child;
             else return s->weight;
         } //end if
         else
         {
             if (s->next) s = s->next;
             else return s->weight;
         } //end else
     } //end if
     return 0;
 #endif
 } //end of the function FuzzyWeight
References weight_s::firstseperator, FuzzyWeight_r(), s, and weightconfig_s::weights.
Referenced by BotChooseBestFightWeapon(), BotChooseLTGItem(), and BotChooseNBGItem().
FuzzyWeightUndecided()
float FuzzyWeightUndecided (int * inventory, weightconfig_t * wc, int weightnum)
Definition at line 687 of file be_ai_weight.c.
 {
 #ifdef EVALUATERECURSIVELY
     return FuzzyWeightUndecided_r(inventory, wc->weights[weightnum].firstseperator);
 #else
     fuzzyseperator_t *s;
     s = wc->weights[weightnum].firstseperator;
     if (!s) return 0;
     while(1)
     {
         if (inventory[s->index] < s->value)
         {
             if (s->child) s = s->child;
             else return s->minweight + random() * (s->maxweight - s->minweight);
         } //end if
         else
         {
             if (s->next) s = s->next;
             else return s->minweight + random() * (s->maxweight - s->minweight);
         } //end else
     } //end if
     return 0;
 #endif
 } //end of the function FuzzyWeightUndecided
References weight_s::firstseperator, FuzzyWeightUndecided_r(), random, s, and weightconfig_s::weights.
Referenced by BotChooseLTGItem(), and BotChooseNBGItem().
InterbreedWeightConfigs()
void InterbreedWeightConfigs (weightconfig_t * config1, weightconfig_t * config2, weightconfig_t * configout)
Definition at line 888 of file be_ai_weight.c.
 {
     int i;
     if (config1->numweights != config2->numweights ||
         config1->numweights != configout->numweights)
     {
         botimport.Print(PRT_ERROR, "cannot interbreed weight configs, unequal numweights\n");
         return;
     } //end if
     for (i = 0; i < config1->numweights; i++)
     {
         InterbreedFuzzySeperator_r(config1->weights[i].firstseperator,
                                     config2->weights[i].firstseperator,
                                     configout->weights[i].firstseperator);
     } //end for
 } //end of the function InterbreedWeightConfigs
References botimport, weight_s::firstseperator, InterbreedFuzzySeperator_r(), weightconfig_s::numweights, PRT_ERROR, and weightconfig_s::weights.
Referenced by BotInterbreedGoalFuzzyLogic().
ReadWeightConfig()
weightconfig_t* ReadWeightConfig (char * filename)
Definition at line 285 of file be_ai_weight.c.
 {
     int newindent, avail = 0, n;
     token_t token;
     source_t *source;
     fuzzyseperator_t *fs;
     weightconfig_t *config = NULL;
 #ifdef DEBUG
     int starttime;
     starttime = Sys_MilliSeconds();
 #endif //DEBUG
     if (!LibVarGetValue("bot_reloadcharacters"))
     {
         avail = -1;
         for( n = 0; n < MAX_WEIGHT_FILES; n++ )
         {
             config = weightFileList[n];
             if( !config )
             {
                 if( avail == -1 )
                 {
                     avail = n;
                 } //end if
                 continue;
             } //end if
             if( strcmp( filename, config->filename ) == 0 )
             {
                 //botimport.Print( PRT_MESSAGE, "retained %s\n", filename );
                 return config;
             } //end if
         } //end for
         if( avail == -1 )
         {
             botimport.Print( PRT_ERROR, "weightFileList was full trying to load %s\n", filename );
             return NULL;
         } //end if
     } //end if
     PC_SetBaseFolder(BOTFILESBASEFOLDER);
     source = LoadSourceFile(filename);
     if (!source)
     {
         botimport.Print(PRT_ERROR, "counldn't load %s\n", filename);
         return NULL;
     } //end if
     //
     config = (weightconfig_t *) GetClearedMemory(sizeof(weightconfig_t));
     config->numweights = 0;
     Q_strncpyz( config->filename, filename, sizeof(config->filename) );
     //parse the item config file
     while(PC_ReadToken(source, &token))
     {
         if (!strcmp(token.string, "weight"))
         {
             if (config->numweights >= MAX_WEIGHTS)
             {
                 SourceWarning(source, "too many fuzzy weights");
                 break;
             } //end if
             if (!PC_ExpectTokenType(source, TT_STRING, 0, &token))
             {
                 FreeWeightConfig(config);
                 FreeSource(source);
                 return NULL;
             } //end if
             StripDoubleQuotes(token.string);
             config->weights[config->numweights].name = (char *) GetClearedMemory(strlen(token.string) + 1);
             strcpy(config->weights[config->numweights].name, token.string);
             if (!PC_ExpectAnyToken(source, &token))
             {
                 FreeWeightConfig(config);
                 FreeSource(source);
                 return NULL;
             } //end if
             newindent = qfalse;
             if (!strcmp(token.string, "{"))
             {
                 newindent = qtrue;
                 if (!PC_ExpectAnyToken(source, &token))
                 {
                     FreeWeightConfig(config);
                     FreeSource(source);
                     return NULL;
                 } //end if
             } //end if
             if (!strcmp(token.string, "switch"))
             {
                 fs = ReadFuzzySeperators_r(source);
                 if (!fs)
                 {
                     FreeWeightConfig(config);
                     FreeSource(source);
                     return NULL;
                 } //end if
                 config->weights[config->numweights].firstseperator = fs;
             } //end if
             else if (!strcmp(token.string, "return"))
             {
                 fs = (fuzzyseperator_t *) GetClearedMemory(sizeof(fuzzyseperator_t));
                 fs->index = 0;
                 fs->value = MAX_INVENTORYVALUE;
                 fs->next = NULL;
                 fs->child = NULL;
                 if (!ReadFuzzyWeight(source, fs))
                 {
                     FreeMemory(fs);
                     FreeWeightConfig(config);
                     FreeSource(source);
                     return NULL;
                 } //end if
                 config->weights[config->numweights].firstseperator = fs;
             } //end else if
             else
             {
                 SourceError(source, "invalid name %s", token.string);
                 FreeWeightConfig(config);
                 FreeSource(source);
                 return NULL;
             } //end else
             if (newindent)
             {
                 if (!PC_ExpectTokenString(source, "}"))
                 {
                     FreeWeightConfig(config);
                     FreeSource(source);
                     return NULL;
                 } //end if
             } //end if
             config->numweights++;
         } //end if
         else
         {
             SourceError(source, "invalid name %s", token.string);
             FreeWeightConfig(config);
             FreeSource(source);
             return NULL;
         } //end else
     } //end while
     //free the source at the end of a pass
     FreeSource(source);
     //if the file was located in a pak file
     botimport.Print(PRT_MESSAGE, "loaded %s\n", filename);
 #ifdef DEBUG
     if (botDeveloper)
     {
         botimport.Print(PRT_MESSAGE, "weights loaded in %d msec\n", Sys_MilliSeconds() - starttime);
     } //end if
 #endif //DEBUG
     //
     if (!LibVarGetValue("bot_reloadcharacters"))
     {
         weightFileList[avail] = config;
     } //end if
     //
     return config;
 } //end of the function ReadWeightConfig
References botDeveloper, BOTFILESBASEFOLDER, botimport, fuzzyseperator_s::child, weightconfig_s::filename, weight_s::firstseperator, FreeMemory(), FreeSource(), FreeWeightConfig(), GetClearedMemory(), fuzzyseperator_s::index, LibVarGetValue(), LoadSourceFile(), MAX_INVENTORYVALUE, MAX_WEIGHT_FILES, MAX_WEIGHTS, weight_s::name, fuzzyseperator_s::next, NULL, weightconfig_s::numweights, PC_ExpectAnyToken(), PC_ExpectTokenString(), PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, PRT_MESSAGE, Q_strncpyz(), qfalse, qtrue, ReadFuzzySeperators_r(), ReadFuzzyWeight(), SourceError(), SourceWarning(), token_s::string, StripDoubleQuotes(), Sys_MilliSeconds(), TT_STRING, fuzzyseperator_s::value, weightFileList, and weightconfig_s::weights.
Referenced by BotLoadItemWeights(), and BotLoadWeaponWeights().
ScaleBalanceRange()
void ScaleBalanceRange (weightconfig_t * config, float scale)
ScaleWeight()
void ScaleWeight (weightconfig_t * config, char * name, float scale)
Definition at line 778 of file be_ai_weight.c.
 {
     int i;
     if (scale < 0) scale = 0;
     else if (scale > 1) scale = 1;
     for (i = 0; i < config->numweights; i++)
     {
         if (!strcmp(name, config->weights[i].name))
         {
             ScaleFuzzySeperator_r(config->weights[i].firstseperator, scale);
             break;
         } //end if
     } //end for
 } //end of the function ScaleWeight
References weight_s::firstseperator, weight_s::name, weightconfig_s::numweights, ScaleFuzzySeperator_r(), and weightconfig_s::weights.
WriteWeightConfig()
qboolean WriteWeightConfig (char * filename, weightconfig_t * config)