ioquake3 doxygen: C:/entry/dev/ioquake3/code/q3_ui/ui_sppostgame.c File Reference
ui_sppostgame.c File Reference
#include "ui_local.h"
Classes
struct postgameMenuInfo_t
Macros
#define MAX_SCOREBOARD_CLIENTS 8
#define AWARD_PRESENTATION_TIME 2000
#define ART_MENU0 "menu/art/menu_0"
#define ART_MENU1 "menu/art/menu_1"
#define ART_REPLAY0 "menu/art/replay_0"
#define ART_REPLAY1 "menu/art/replay_1"
#define ART_NEXT0 "menu/art/next_0"
#define ART_NEXT1 "menu/art/next_1"
#define ID_AGAIN 10
#define ID_NEXT 11
#define ID_MENU 12
Functions
static void UI_SPPostgameMenu_AgainEvent (void *ptr, int event)
static void UI_SPPostgameMenu_NextEvent (void *ptr, int event)
static void UI_SPPostgameMenu_MenuEvent (void *ptr, int event)
static sfxHandle_t UI_SPPostgameMenu_MenuKey (int key)
static void UI_SPPostgameMenu_DrawAwardsMedals (int max)
static void UI_SPPostgameMenu_DrawAwardsPresentation (int timer)
static void UI_SPPostgameMenu_MenuDrawScoreLine (int n, int y)
static void UI_SPPostgameMenu_MenuDraw (void)
void UI_SPPostgameMenu_Cache (void)
static void UI_SPPostgameMenu_Init (void)
static void Prepname (int index)
void UI_SPPostgameMenu_f (void)
Variables
static postgameMenuInfo_t postgameMenuInfo
static char arenainfo [MAX_INFO_VALUE]
char * ui_medalNames [] = {"Accuracy", "Impressive", "Excellent", "Gauntlet", "Frags", "Perfect"}
char * ui_medalPicNames []
char * ui_medalSounds []
static int medalLocations [6] = {144, 448, 88, 504, 32, 560}
Macro Definition Documentation
ART_MENU0
#define ART_MENU0 "menu/art/menu_0"
Definition at line 37 of file ui_sppostgame.c.
ART_MENU1
#define ART_MENU1 "menu/art/menu_1"
Definition at line 38 of file ui_sppostgame.c.
ART_NEXT0
#define ART_NEXT0 "menu/art/next_0"
Definition at line 41 of file ui_sppostgame.c.
ART_NEXT1
#define ART_NEXT1 "menu/art/next_1"
Definition at line 42 of file ui_sppostgame.c.
ART_REPLAY0
#define ART_REPLAY0 "menu/art/replay_0"
Definition at line 39 of file ui_sppostgame.c.
ART_REPLAY1
#define ART_REPLAY1 "menu/art/replay_1"
Definition at line 40 of file ui_sppostgame.c.
AWARD_PRESENTATION_TIME
#define AWARD_PRESENTATION_TIME 2000
Definition at line 35 of file ui_sppostgame.c.
ID_AGAIN
#define ID_AGAIN 10
Definition at line 44 of file ui_sppostgame.c.
ID_MENU
#define ID_MENU 12
Definition at line 46 of file ui_sppostgame.c.
ID_NEXT
#define ID_NEXT 11
Definition at line 45 of file ui_sppostgame.c.
MAX_SCOREBOARD_CLIENTS
#define MAX_SCOREBOARD_CLIENTS 8
Definition at line 33 of file ui_sppostgame.c.
Function Documentation
Prepname()
static void Prepname (int index) static
Definition at line 479 of file ui_sppostgame.c.
{
     int     len;
     char    name[64];
     char    info[MAX_INFO_STRING];
     trap_GetConfigString( CS_PLAYERS + postgameMenuInfo.clientNums[index], info, MAX_INFO_STRING );
     Q_strncpyz( name, Info_ValueForKey( info, "n" ), sizeof(name) );
     Q_CleanStr( name );
     len = strlen( name );
     while( len && UI_ProportionalStringWidth( name ) > 256 ) {
         len--;
         name[len] = 0;
     }
     Q_strncpyz( postgameMenuInfo.placeNames[index], name, sizeof(postgameMenuInfo.placeNames[index]) );
 }
Referenced by UI_SPPostgameMenu_f().
UI_SPPostgameMenu_AgainEvent()
static void UI_SPPostgameMenu_AgainEvent (void * ptr, int event) static
Definition at line 104 of file ui_sppostgame.c.
 {
     if (event != QM_ACTIVATED) {
         return;
     }
     UI_PopMenu();
     trap_Cmd_ExecuteText( EXEC_APPEND, "map_restart 0\n" );
 }
Referenced by UI_SPPostgameMenu_Init().
UI_SPPostgameMenu_Cache()
void UI_SPPostgameMenu_Cache (void)
Definition at line 402 of file ui_sppostgame.c.
{
     int         n;
     qboolean    buildscript;
     buildscript = trap_Cvar_VariableValue("com_buildscript");
     trap_R_RegisterShaderNoMip( ART_MENU0 );
     trap_R_RegisterShaderNoMip( ART_MENU1 );
     trap_R_RegisterShaderNoMip( ART_REPLAY0 );
     trap_R_RegisterShaderNoMip( ART_REPLAY1 );
     trap_R_RegisterShaderNoMip( ART_NEXT0 );
     trap_R_RegisterShaderNoMip( ART_NEXT1 );
     for( n = 0; n < 6; n++ ) {
         trap_R_RegisterShaderNoMip( ui_medalPicNames[n] );
         trap_S_RegisterSound( ui_medalSounds[n], qfalse );
     }
     if( buildscript ) {
         trap_S_RegisterSound( "music/loss.wav", qfalse );
         trap_S_RegisterSound( "music/win.wav", qfalse );
         trap_S_RegisterSound( "sound/player/announce/youwin.wav", qfalse );
     }
 }
Referenced by UI_Cache_f(), and UI_SPPostgameMenu_Init().
UI_SPPostgameMenu_DrawAwardsMedals()
static void UI_SPPostgameMenu_DrawAwardsMedals (int max) static
Definition at line 209 of file ui_sppostgame.c.
{
     int     n;
     int     medal;
     int     amount;
     int     x, y;
     char    buf[16];
     for( n = 0; n < max; n++ ) {
         x = medalLocations[n];
         y = 64;
         medal = postgameMenuInfo.awardsEarned[n];
         amount = postgameMenuInfo.awardsLevels[n];
         UI_DrawNamedPic( x, y, 48, 48, ui_medalPicNames[medal] );
         if( medal == AWARD_ACCURACY ) {
             Com_sprintf( buf, sizeof(buf), "%i%%", amount );
         }
         else {
             if( amount == 1 ) {
                 continue;
             }
             Com_sprintf( buf, sizeof(buf), "%i", amount );
         }
         UI_DrawString( x + 24, y + 52, buf, UI_CENTER, color_yellow );
     }
 }
Referenced by UI_SPPostgameMenu_DrawAwardsPresentation(), and UI_SPPostgameMenu_MenuDraw().
UI_SPPostgameMenu_DrawAwardsPresentation()
static void UI_SPPostgameMenu_DrawAwardsPresentation (int timer) static
Definition at line 239 of file ui_sppostgame.c.
{
     int     awardNum;
     int     atimer;
     vec4_t  color;
     awardNum = timer / AWARD_PRESENTATION_TIME;
     atimer = timer % AWARD_PRESENTATION_TIME;
     color[0] = color[1] = color[2] = 1.0f;
     color[3] = (float)( AWARD_PRESENTATION_TIME - atimer ) / (float)AWARD_PRESENTATION_TIME;
     UI_DrawProportionalString( 320, 64, ui_medalNames[postgameMenuInfo.awardsEarned[awardNum]], UI_CENTER, color );
     UI_SPPostgameMenu_DrawAwardsMedals( awardNum + 1 );
     if( !postgameMenuInfo.playedSound[awardNum] ) {
         postgameMenuInfo.playedSound[awardNum] = qtrue;
         trap_S_StartLocalSound( trap_S_RegisterSound( ui_medalSounds[postgameMenuInfo.awardsEarned[awardNum]], qfalse ), CHAN_ANNOUNCER );
     }
 }
Referenced by UI_SPPostgameMenu_MenuDraw().
UI_SPPostgameMenu_f()
void UI_SPPostgameMenu_f (void)
Definition at line 503 of file ui_sppostgame.c.
{
     int         playerGameRank;
     int         playerClientNum;
     int         n;
     int         oldFrags, newFrags;
     const char  *arena;
     int         awardValues[6];
     char        map[MAX_QPATH];
     char        info[MAX_INFO_STRING];
     memset( &postgameMenuInfo, 0, sizeof(postgameMenuInfo) );
     trap_GetConfigString( CS_SYSTEMINFO, info, sizeof(info) );
     postgameMenuInfo.serverId = atoi( Info_ValueForKey( info, "sv_serverid" ) );
     trap_GetConfigString( CS_SERVERINFO, info, sizeof(info) );
     Q_strncpyz( map, Info_ValueForKey( info, "mapname" ), sizeof(map) );
     arena = UI_GetArenaInfoByMap( map );
     if ( !arena ) {
         return;
     }
     Q_strncpyz( arenainfo, arena, sizeof(arenainfo) );
     postgameMenuInfo.level = atoi( Info_ValueForKey( arenainfo, "num" ) );
     postgameMenuInfo.numClients = atoi( UI_Argv( 1 ) );
     playerClientNum = atoi( UI_Argv( 2 ) );
     playerGameRank = 8;     // in case they ended game as a spectator
     if( postgameMenuInfo.numClients > MAX_SCOREBOARD_CLIENTS ) {
         postgameMenuInfo.numClients = MAX_SCOREBOARD_CLIENTS;
     }
     for( n = 0; n < postgameMenuInfo.numClients; n++ ) {
         postgameMenuInfo.clientNums[n] = atoi( UI_Argv( 8 + n * 3 + 1 ) );
         postgameMenuInfo.ranks[n] = atoi( UI_Argv( 8 + n * 3 + 2 ) );
         postgameMenuInfo.scores[n] = atoi( UI_Argv( 8 + n * 3 + 3 ) );
         if( postgameMenuInfo.clientNums[n] == playerClientNum ) {
             playerGameRank = (postgameMenuInfo.ranks[n] & ~RANK_TIED_FLAG) + 1;
         }
     }
     UI_SetBestScore( postgameMenuInfo.level, playerGameRank );
     // process award stats and prepare presentation data
     awardValues[AWARD_ACCURACY] = atoi( UI_Argv( 3 ) );
     awardValues[AWARD_IMPRESSIVE] = atoi( UI_Argv( 4 ) );
     awardValues[AWARD_EXCELLENT] = atoi( UI_Argv( 5 ) );
     awardValues[AWARD_GAUNTLET] = atoi( UI_Argv( 6 ) );
     awardValues[AWARD_FRAGS] = atoi( UI_Argv( 7 ) );
     awardValues[AWARD_PERFECT] = atoi( UI_Argv( 8 ) );
     postgameMenuInfo.numAwards = 0;
     if( awardValues[AWARD_ACCURACY] >= 50 ) {
         UI_LogAwardData( AWARD_ACCURACY, 1 );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_ACCURACY;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_ACCURACY];
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_IMPRESSIVE] ) {
         UI_LogAwardData( AWARD_IMPRESSIVE, awardValues[AWARD_IMPRESSIVE] );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_IMPRESSIVE;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_IMPRESSIVE];
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_EXCELLENT] ) {
         UI_LogAwardData( AWARD_EXCELLENT, awardValues[AWARD_EXCELLENT] );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_EXCELLENT;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_EXCELLENT];
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_GAUNTLET] ) {
         UI_LogAwardData( AWARD_GAUNTLET, awardValues[AWARD_GAUNTLET] );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_GAUNTLET;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = awardValues[AWARD_GAUNTLET];
         postgameMenuInfo.numAwards++;
     }
     oldFrags = UI_GetAwardLevel( AWARD_FRAGS ) / 100;
     UI_LogAwardData( AWARD_FRAGS, awardValues[AWARD_FRAGS] );
     newFrags = UI_GetAwardLevel( AWARD_FRAGS ) / 100;
     if( newFrags > oldFrags ) {
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_FRAGS;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = newFrags * 100;
         postgameMenuInfo.numAwards++;
     }
     if( awardValues[AWARD_PERFECT] ) {
         UI_LogAwardData( AWARD_PERFECT, 1 );
         postgameMenuInfo.awardsEarned[postgameMenuInfo.numAwards] = AWARD_PERFECT;
         postgameMenuInfo.awardsLevels[postgameMenuInfo.numAwards] = 1;
         postgameMenuInfo.numAwards++;
     }
     if ( playerGameRank == 1 ) {
         postgameMenuInfo.won = UI_TierCompleted( postgameMenuInfo.level );
     }
     else {
         postgameMenuInfo.won = -1;
     }
     postgameMenuInfo.starttime = uis.realtime;
     postgameMenuInfo.scoreboardtime = uis.realtime;
     trap_Key_SetCatcher( KEYCATCH_UI );
     uis.menusp = 0;
     UI_SPPostgameMenu_Init();
     UI_PushMenu( &postgameMenuInfo.menu );
     if ( playerGameRank == 1 ) {
         Menu_SetCursorToItem( &postgameMenuInfo.menu, &postgameMenuInfo.item_next );
     }
     else {
         Menu_SetCursorToItem( &postgameMenuInfo.menu, &postgameMenuInfo.item_again );
     }
     Prepname( 0 );
     Prepname( 1 );
     Prepname( 2 );
     if ( playerGameRank != 1 ) {
         postgameMenuInfo.winnerSound = trap_S_RegisterSound( va( "sound/player/announce/%s_wins.wav", postgameMenuInfo.placeNames[0] ), qfalse );
         trap_Cmd_ExecuteText( EXEC_APPEND, "music music/loss\n" );
     }
     else {
         postgameMenuInfo.winnerSound = trap_S_RegisterSound( "sound/player/announce/youwin.wav", qfalse );
         trap_Cmd_ExecuteText( EXEC_APPEND, "music music/win\n" );
     }
     postgameMenuInfo.phase = 1;
     postgameMenuInfo.lastTier = UI_GetNumSPTiers();
     if ( UI_GetSpecialArenaInfo( "final" ) ) {
         postgameMenuInfo.lastTier++;
     }
 }
Referenced by UI_ConsoleCommand().
UI_SPPostgameMenu_Init()
static void UI_SPPostgameMenu_Init (void) static
Definition at line 432 of file ui_sppostgame.c.
{
     postgameMenuInfo.menu.wrapAround    = qtrue;
     postgameMenuInfo.menu.key           = UI_SPPostgameMenu_MenuKey;
     postgameMenuInfo.menu.draw          = UI_SPPostgameMenu_MenuDraw;
     postgameMenuInfo.ignoreKeysTime     = uis.realtime + 1500;
     UI_SPPostgameMenu_Cache();
     postgameMenuInfo.item_menu.generic.type         = MTYPE_BITMAP;
     postgameMenuInfo.item_menu.generic.name         = ART_MENU0;
     postgameMenuInfo.item_menu.generic.flags        = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_INACTIVE;
     postgameMenuInfo.item_menu.generic.x            = 0;
     postgameMenuInfo.item_menu.generic.y            = 480-64;
     postgameMenuInfo.item_menu.generic.callback     = UI_SPPostgameMenu_MenuEvent;
     postgameMenuInfo.item_menu.generic.id           = ID_MENU;
     postgameMenuInfo.item_menu.width                = 128;
     postgameMenuInfo.item_menu.height               = 64;
     postgameMenuInfo.item_menu.focuspic             = ART_MENU1;
     postgameMenuInfo.item_again.generic.type        = MTYPE_BITMAP;
     postgameMenuInfo.item_again.generic.name        = ART_REPLAY0;
     postgameMenuInfo.item_again.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS|QMF_INACTIVE;
     postgameMenuInfo.item_again.generic.x           = 320;
     postgameMenuInfo.item_again.generic.y           = 480-64;
     postgameMenuInfo.item_again.generic.callback    = UI_SPPostgameMenu_AgainEvent;
     postgameMenuInfo.item_again.generic.id          = ID_AGAIN;
     postgameMenuInfo.item_again.width               = 128;
     postgameMenuInfo.item_again.height              = 64;
     postgameMenuInfo.item_again.focuspic            = ART_REPLAY1;
     postgameMenuInfo.item_next.generic.type         = MTYPE_BITMAP;
     postgameMenuInfo.item_next.generic.name         = ART_NEXT0;
     postgameMenuInfo.item_next.generic.flags        = QMF_RIGHT_JUSTIFY|QMF_PULSEIFFOCUS|QMF_INACTIVE;
     postgameMenuInfo.item_next.generic.x            = 640;
     postgameMenuInfo.item_next.generic.y            = 480-64;
     postgameMenuInfo.item_next.generic.callback     = UI_SPPostgameMenu_NextEvent;
     postgameMenuInfo.item_next.generic.id           = ID_NEXT;
     postgameMenuInfo.item_next.width                = 128;
     postgameMenuInfo.item_next.height               = 64;
     postgameMenuInfo.item_next.focuspic             = ART_NEXT1;
     Menu_AddItem( &postgameMenuInfo.menu, ( void * )&postgameMenuInfo.item_menu );
     Menu_AddItem( &postgameMenuInfo.menu, ( void * )&postgameMenuInfo.item_again );
     Menu_AddItem( &postgameMenuInfo.menu, ( void * )&postgameMenuInfo.item_next );
 }
Referenced by UI_SPPostgameMenu_f().
UI_SPPostgameMenu_MenuDraw()
static void UI_SPPostgameMenu_MenuDraw (void) static
Definition at line 296 of file ui_sppostgame.c.
{
     int     timer;
     int     serverId;
     int     n;
     char    info[MAX_INFO_STRING];
     trap_GetConfigString( CS_SYSTEMINFO, info, sizeof(info) );
     serverId = atoi( Info_ValueForKey( info, "sv_serverid" ) );
     if( serverId != postgameMenuInfo.serverId ) {
         UI_PopMenu();
         return;
     }
     // phase 1
     if ( postgameMenuInfo.numClients > 2 ) {
         UI_DrawProportionalString( 510, 480 - 64 - PROP_HEIGHT, postgameMenuInfo.placeNames[2], UI_CENTER, color_white );
     }
     UI_DrawProportionalString( 130, 480 - 64 - PROP_HEIGHT, postgameMenuInfo.placeNames[1], UI_CENTER, color_white );
     UI_DrawProportionalString( 320, 480 - 64 - 2 * PROP_HEIGHT, postgameMenuInfo.placeNames[0], UI_CENTER, color_white );
     if( postgameMenuInfo.phase == 1 ) {
         timer = uis.realtime - postgameMenuInfo.starttime;
         if( timer >= 1000 && postgameMenuInfo.winnerSound ) {
             trap_S_StartLocalSound( postgameMenuInfo.winnerSound, CHAN_ANNOUNCER );
             postgameMenuInfo.winnerSound = 0;
         }
         if( timer < 5000 ) {
             return;
         }
         postgameMenuInfo.phase = 2;
         postgameMenuInfo.starttime = uis.realtime;
     }
     // phase 2
     if( postgameMenuInfo.phase == 2 ) {
         timer = uis.realtime - postgameMenuInfo.starttime;
         if( timer >= ( postgameMenuInfo.numAwards * AWARD_PRESENTATION_TIME ) ) {
             if( timer < 5000 ) {
                 return;
             }
             postgameMenuInfo.phase = 3;
             postgameMenuInfo.starttime = uis.realtime;
         }
         else {
             UI_SPPostgameMenu_DrawAwardsPresentation( timer );
         }
     }
     // phase 3
     if( postgameMenuInfo.phase == 3 ) {
         if( uis.demoversion ) {
             if( postgameMenuInfo.won == 1 && UI_ShowTierVideo( 8 )) {
                 trap_Cvar_Set( "nextmap", "" );
                 trap_Cmd_ExecuteText( EXEC_APPEND, "disconnect; cinematic demoEnd.RoQ\n" );
                 return;
             }
         }
         else if( postgameMenuInfo.won > -1 && UI_ShowTierVideo( postgameMenuInfo.won + 1 )) {
             if( postgameMenuInfo.won == postgameMenuInfo.lastTier ) {
                 trap_Cvar_Set( "nextmap", "" );
                 trap_Cmd_ExecuteText( EXEC_APPEND, "disconnect; cinematic end.RoQ\n" );
                 return;
             }
             trap_Cvar_SetValue( "ui_spSelection", postgameMenuInfo.won * ARENAS_PER_TIER );
             trap_Cvar_Set( "nextmap", "levelselect" );
             trap_Cmd_ExecuteText( EXEC_APPEND, va( "disconnect; cinematic tier%i.RoQ\n", postgameMenuInfo.won + 1 ) );
             return;
         }
         postgameMenuInfo.item_again.generic.flags &= ~QMF_INACTIVE;
         postgameMenuInfo.item_next.generic.flags &= ~QMF_INACTIVE;
         postgameMenuInfo.item_menu.generic.flags &= ~QMF_INACTIVE;
         UI_SPPostgameMenu_DrawAwardsMedals( postgameMenuInfo.numAwards );
         Menu_Draw( &postgameMenuInfo.menu );
     }
     // draw the scoreboard
     if( !trap_Cvar_VariableValue( "ui_spScoreboard" ) ) {
         return;
     }
     timer = uis.realtime - postgameMenuInfo.scoreboardtime;
     if( postgameMenuInfo.numClients <= 3 ) {
         n = 0;
     }
     else {
         n = timer / 1500 % (postgameMenuInfo.numClients + 2);
     }
     UI_SPPostgameMenu_MenuDrawScoreLine( n, 0 );
     UI_SPPostgameMenu_MenuDrawScoreLine( n + 1, 0 + SMALLCHAR_HEIGHT );
     UI_SPPostgameMenu_MenuDrawScoreLine( n + 2, 0 + 2 * SMALLCHAR_HEIGHT );
 }
Referenced by UI_SPPostgameMenu_Init().
UI_SPPostgameMenu_MenuDrawScoreLine()
static void UI_SPPostgameMenu_MenuDrawScoreLine (int n, int y) static
Definition at line 265 of file ui_sppostgame.c.
{
     int     rank;
     char    name[64];
     char    info[MAX_INFO_STRING];
     if( n > (postgameMenuInfo.numClients + 1) ) {
         n -= (postgameMenuInfo.numClients + 2);
     }
     if( n >= postgameMenuInfo.numClients ) {
         return;
     }
     rank = postgameMenuInfo.ranks[n];
     if( rank & RANK_TIED_FLAG ) {
         UI_DrawString( 640 - 31 * SMALLCHAR_WIDTH, y, "(tie)", UI_LEFT|UI_SMALLFONT, color_white );
         rank &= ~RANK_TIED_FLAG;
     }
     trap_GetConfigString( CS_PLAYERS + postgameMenuInfo.clientNums[n], info, MAX_INFO_STRING );
     Q_strncpyz( name, Info_ValueForKey( info, "n" ), sizeof(name) );
     Q_CleanStr( name );
     UI_DrawString( 640 - 25 * SMALLCHAR_WIDTH, y, va( "#%i: %-16s %2i", rank + 1, name, postgameMenuInfo.scores[n] ), UI_LEFT|UI_SMALLFONT, color_white );
 }
Referenced by UI_SPPostgameMenu_MenuDraw().
UI_SPPostgameMenu_MenuEvent()
static void UI_SPPostgameMenu_MenuEvent (void * ptr, int event) static
Definition at line 164 of file ui_sppostgame.c.
 {
     if (event != QM_ACTIVATED) {
         return;
     }
     UI_PopMenu();
     trap_Cmd_ExecuteText( EXEC_APPEND, "disconnect; levelselect\n" );
 }
Referenced by UI_SPPostgameMenu_Init().
UI_SPPostgameMenu_MenuKey()
static sfxHandle_t UI_SPPostgameMenu_MenuKey (int key) static
Definition at line 179 of file ui_sppostgame.c.
{
     if ( uis.realtime < postgameMenuInfo.ignoreKeysTime ) {
         return 0;
     }
     if( postgameMenuInfo.phase == 1 ) {
         trap_Cmd_ExecuteText( EXEC_APPEND, "abort_podium\n" );
         postgameMenuInfo.phase = 2;
         postgameMenuInfo.starttime = uis.realtime;
         postgameMenuInfo.ignoreKeysTime = uis.realtime + 250;
         return 0;
     }
     if( postgameMenuInfo.phase == 2 ) {
         postgameMenuInfo.phase = 3;
         postgameMenuInfo.starttime = uis.realtime;
         postgameMenuInfo.ignoreKeysTime = uis.realtime + 250;
         return 0;
     }
     if( key == K_ESCAPE || key == K_MOUSE2 ) {
         return 0;
     }
     return Menu_DefaultKey( &postgameMenuInfo.menu, key );
 }
Referenced by UI_SPPostgameMenu_Init().
UI_SPPostgameMenu_NextEvent()
static void UI_SPPostgameMenu_NextEvent (void * ptr, int event) static
Definition at line 119 of file ui_sppostgame.c.
{
     int         currentSet;
     int         levelSet;
     int         level;
     int         currentLevel;
     const char  *arenaInfo;
     if (event != QM_ACTIVATED) {
         return;
     }
     UI_PopMenu();
     // handle specially if we just won the training map
     if( postgameMenuInfo.won == 0 ) {
         level = 0;
     }
     else {
         level = postgameMenuInfo.level + 1;
     }
     levelSet = level / ARENAS_PER_TIER;
     currentLevel = UI_GetCurrentGame();
     if( currentLevel == -1 ) {
         currentLevel = postgameMenuInfo.level;
     }
     currentSet = currentLevel / ARENAS_PER_TIER;
     if( levelSet > currentSet || levelSet == UI_GetNumSPTiers() ) {
         level = currentLevel;
     }
     arenaInfo = UI_GetArenaInfoByNumber( level );
     if ( !arenaInfo ) {
         return;
     }
     UI_SPArena_Start( arenaInfo );
 }
Referenced by UI_SPPostgameMenu_Init().
Variable Documentation
arenainfo
char arenainfo[MAX_INFO_VALUE] static
Definition at line 78 of file ui_sppostgame.c.
Referenced by G_InitBots(), and UI_SPPostgameMenu_f().
medalLocations
int medalLocations[6] = {144, 448, 88, 504, 32, 560} static
Definition at line 207 of file ui_sppostgame.c.
Referenced by UI_SPPostgameMenu_DrawAwardsMedals().
postgameMenuInfo
postgameMenuInfo_t postgameMenuInfo static
Definition at line 77 of file ui_sppostgame.c.
Referenced by Prepname(), UI_SPPostgameMenu_DrawAwardsMedals(), UI_SPPostgameMenu_DrawAwardsPresentation(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_Init(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_SPPostgameMenu_MenuKey(), and UI_SPPostgameMenu_NextEvent().
ui_medalNames
char* ui_medalNames[] = {"Accuracy", "Impressive", "Excellent", "Gauntlet", "Frags", "Perfect"}
Definition at line 80 of file ui_sppostgame.c.
Referenced by UI_SPPostgameMenu_DrawAwardsPresentation().
ui_medalPicNames
char* ui_medalPicNames[]
Initial value:
= {
    "menu/medals/medal_accuracy",
    "menu/medals/medal_impressive",
    "menu/medals/medal_excellent",
    "menu/medals/medal_gauntlet",
    "menu/medals/medal_frags",
    "menu/medals/medal_victory"
}
Definition at line 81 of file ui_sppostgame.c.
Referenced by UI_SPLevelMenu_Cache(), UI_SPLevelMenu_Init(), UI_SPPostgameMenu_Cache(), and UI_SPPostgameMenu_DrawAwardsMedals().
ui_medalSounds
char* ui_medalSounds[]
Initial value:
= {
    "sound/feedback/accuracy.wav",
    "sound/feedback/impressive_a.wav",
    "sound/feedback/excellent_a.wav",
    "sound/feedback/gauntlet.wav",
    "sound/feedback/frags.wav",
    "sound/feedback/perfect.wav"
}
Definition at line 89 of file ui_sppostgame.c.
Referenced by UI_SPLevelMenu_Cache(), UI_SPPostgameMenu_Cache(), and UI_SPPostgameMenu_DrawAwardsPresentation().