ioquake3 doxygen: C:/entry/dev/ioquake3/code/botlib/be_aas_bsp.h File Reference
be_aas_bsp.h File Reference
Macros
#define MAX_EPAIRKEY 128
Functions
bsp_trace_t AAS_Trace (vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
int AAS_PointContents (vec3_t point)
qboolean AAS_inPVS (vec3_t p1, vec3_t p2)
qboolean AAS_inPHS (vec3_t p1, vec3_t p2)
qboolean AAS_AreasConnected (int area1, int area2)
int AAS_BoxEntities (vec3_t absmins, vec3_t absmaxs, int *list, int maxcount)
void AAS_BSPModelMinsMaxsOrigin (int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
int AAS_NextBSPEntity (int ent)
int AAS_ValueForBSPEpairKey (int ent, char *key, char *value, int size)
int AAS_VectorForBSPEpairKey (int ent, char *key, vec3_t v)
int AAS_FloatForBSPEpairKey (int ent, char *key, float *value)
int AAS_IntForBSPEpairKey (int ent, char *key, int *value)
Macro Definition Documentation
MAX_EPAIRKEY
#define MAX_EPAIRKEY 128
Definition at line 58 of file be_aas_bsp.h.
Function Documentation
AAS_AreasConnected()
qboolean AAS_AreasConnected (int area1, int area2)
AAS_BoxEntities()
int AAS_BoxEntities (vec3_t absmins, vec3_t absmaxs, int * list, int maxcount)
Definition at line 242 of file be_aas_bspq3.c.
 {
     return 0;
 } //end of the function AAS_BoxEntities
AAS_BSPModelMinsMaxsOrigin()
void AAS_BSPModelMinsMaxsOrigin (int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
Definition at line 212 of file be_aas_bspq3.c.
 {
     botimport.BSPModelMinsMaxsOrigin(modelnum, angles, mins, maxs, origin);
 } //end of the function AAS_BSPModelMinsMaxs
Referenced by AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Teleport(), AAS_UpdateEntity(), BotFuncBobStartEnd(), BotOnMover(), MoverBottomCenter(), and MoverDown().
AAS_FloatForBSPEpairKey()
int AAS_FloatForBSPEpairKey (int ent, char * key, float * value)
Definition at line 323 of file be_aas_bspq3.c.
 {
     char buf[MAX_EPAIRKEY];
     *value = 0;
     if (!AAS_ValueForBSPEpairKey(ent, key, buf, MAX_EPAIRKEY)) return qfalse;
     *value = atof(buf);
     return qtrue;
 } //end of the function AAS_FloatForBSPEpairKey
Referenced by AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Teleport(), BotInitInfoEntities(), BotInitLevelItems(), and Init_AAS_Export().
AAS_inPHS()
qboolean AAS_inPHS (vec3_t p1, vec3_t p2)
Definition at line 202 of file be_aas_bspq3.c.
 {
     return qtrue;
 } //end of the function AAS_inPHS
AAS_inPVS()
qboolean AAS_inPVS (vec3_t p1, vec3_t p2)
Definition at line 191 of file be_aas_bspq3.c.
 {
     return botimport.inPVS(p1, p2);
 } //end of the function AAS_InPVS
AAS_IntForBSPEpairKey()
int AAS_IntForBSPEpairKey (int ent, char * key, int * value)
Definition at line 338 of file be_aas_bspq3.c.
 {
     char buf[MAX_EPAIRKEY];
     *value = 0;
     if (!AAS_ValueForBSPEpairKey(ent, key, buf, MAX_EPAIRKEY)) return qfalse;
     *value = atoi(buf);
     return qtrue;
 } //end of the function AAS_IntForBSPEpairKey
Referenced by AAS_Reachability_FuncBobbing(), AAS_SetWeaponJumpAreaFlags(), AAS_TravelFlagsForTeam(), BotInitLevelItems(), and Init_AAS_Export().
AAS_NextBSPEntity()
int AAS_NextBSPEntity (int ent)
Definition at line 252 of file be_aas_bspq3.c.
 {
     ent++;
     if (ent >= 1 && ent < bspworld.numentities) return ent;
     return 0;
 } //end of the function AAS_NextBSPEntity
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_JumpPad(), AAS_Reachability_Teleport(), AAS_SetWeaponJumpAreaFlags(), BotInitInfoEntities(), BotInitLevelItems(), BotSetBrushModelTypes(), and Init_AAS_Export().
AAS_PointContents()
int AAS_PointContents (vec3_t point)
Definition at line 160 of file be_aas_bspq3.c.
 {
     return botimport.PointContents(point);
 } //end of the function AAS_PointContents
Referenced by AAS_ClientMovementPrediction(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Swim(), AAS_Swimming(), BotFinishTravel_WaterJump(), BotGapDistance(), BotInitLevelItems(), and Init_AAS_Export().
AAS_Trace()
bsp_trace_t AAS_Trace (vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
Definition at line 147 of file be_aas_bspq3.c.
 {
     bsp_trace_t bsptrace;
     botimport.Trace(&bsptrace, start, mins, maxs, end, passent, contentmask);
     return bsptrace;
 } //end of the function AAS_Trace
Referenced by AAS_DropToFloor(), AAS_Reachability_Grapple(), AAS_WeaponJumpZVelocity(), BotCheckBlocked(), BotExportTest(), BotInitLevelItems(), BotItemGoalInVisButNotVisible(), BotOnMover(), BotOnTopOfEntity(), BotReachabilityArea(), BotTravel_Grapple(), and BotVisible().
AAS_ValueForBSPEpairKey()
int AAS_ValueForBSPEpairKey (int ent, char * key, char * value, int size)
Definition at line 279 of file be_aas_bspq3.c.
 {
     bsp_epair_t *epair;
     value[0] = '\0';
     if (!AAS_BSPEntityInRange(ent)) return qfalse;
     for (epair = bspworld.entities[ent].epairs; epair; epair = epair->next)
     {
         if (!strcmp(epair->key, key))
         {
             strncpy(value, epair->value, size-1);
             value[size-1] = '\0';
             return qtrue;
         } //end if
     } //end for
     return qfalse;
 } //end of the function AAS_FindBSPEpair
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_FloatForBSPEpairKey(), AAS_GetJumpPadInfo(), AAS_IntForBSPEpairKey(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_JumpPad(), AAS_Reachability_Teleport(), AAS_SetWeaponJumpAreaFlags(), AAS_VectorForBSPEpairKey(), BotInitInfoEntities(), BotInitLevelItems(), BotSetBrushModelTypes(), and Init_AAS_Export().
AAS_VectorForBSPEpairKey()
int AAS_VectorForBSPEpairKey (int ent, char * key, vec3_t v)
Definition at line 302 of file be_aas_bspq3.c.
 {
     char buf[MAX_EPAIRKEY];
     double v1, v2, v3;
     VectorClear(v);
     if (!AAS_ValueForBSPEpairKey(ent, key, buf, MAX_EPAIRKEY)) return qfalse;
     //scanf into doubles, then assign, so it is vec_t size independent
     v1 = v2 = v3 = 0;
     sscanf(buf, "%lf %lf %lf", &v1, &v2, &v3);
     v[0] = v1;
     v[1] = v2;
     v[2] = v3;
     return qtrue;
 } //end of the function AAS_VectorForBSPEpairKey
Referenced by AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Teleport(), AAS_SetWeaponJumpAreaFlags(), BotInitInfoEntities(), BotInitLevelItems(), and Init_AAS_Export().