ioquake3 doxygen: C:/entry/dev/ioquake3/code/qcommon/vm_local.h File Reference
vm_local.h File Reference
#include "q_shared.h"
#include "qcommon.h"
Classes
struct vmSymbol_s
struct vm_s
Macros
#define MAX_VMMAIN_ARGS 13
#define MAX_VMSYSCALL_ARGS 16
#define OPSTACK_SIZE 1024
#define OPSTACK_MASK (OPSTACK_SIZE-1)
#define PROGRAM_STACK_SIZE 0x10000
#define PROGRAM_STACK_MASK (PROGRAM_STACK_SIZE-1)
#define VM_OFFSET_PROGRAM_STACK 0
#define VM_OFFSET_SYSTEM_CALL 4
Typedefs
typedef int vmptr_t
typedef struct vmSymbol_s vmSymbol_t
Enumerations
enum opcode_t {
OP_UNDEF, OP_IGNORE, OP_BREAK, OP_ENTER,
OP_LEAVE, OP_CALL, OP_PUSH, OP_POP,
OP_CONST, OP_LOCAL, OP_JUMP, OP_EQ,
OP_NE, OP_LTI, OP_LEI, OP_GTI,
OP_GEI, OP_LTU, OP_LEU, OP_GTU,
OP_GEU, OP_EQF, OP_NEF, OP_LTF,
OP_LEF, OP_GTF, OP_GEF, OP_LOAD1,
OP_LOAD2, OP_LOAD4, OP_STORE1, OP_STORE2,
OP_STORE4, OP_ARG, OP_BLOCK_COPY, OP_SEX8,
OP_SEX16, OP_NEGI, OP_ADD, OP_SUB,
OP_DIVI, OP_DIVU, OP_MODI, OP_MODU,
OP_MULI, OP_MULU, OP_BAND, OP_BOR,
OP_BXOR, OP_BCOM, OP_LSH, OP_RSHI,
OP_RSHU, OP_NEGF, OP_ADDF, OP_SUBF,
OP_DIVF, OP_MULF, OP_CVIF, OP_CVFI
}
Functions
void VM_Compile (vm_t *vm, vmHeader_t *header)
int VM_CallCompiled (vm_t *vm, int *args)
void VM_PrepareInterpreter (vm_t *vm, vmHeader_t *header)
int VM_CallInterpreted (vm_t *vm, int *args)
vmSymbol_t * VM_ValueToFunctionSymbol (vm_t *vm, int value)
int VM_SymbolToValue (vm_t *vm, const char *symbol)
const char * VM_ValueToSymbol (vm_t *vm, int value)
void VM_LogSyscalls (int *args)
void VM_BlockCopy (unsigned int dest, unsigned int src, size_t n)
Variables
vm_t * currentVM
int vm_debugLevel
Macro Definition Documentation
MAX_VMMAIN_ARGS
#define MAX_VMMAIN_ARGS 13
Definition at line 27 of file vm_local.h.
MAX_VMSYSCALL_ARGS
#define MAX_VMSYSCALL_ARGS 16
Definition at line 31 of file vm_local.h.
OPSTACK_MASK
#define OPSTACK_MASK (OPSTACK_SIZE-1)
Definition at line 36 of file vm_local.h.
OPSTACK_SIZE
#define OPSTACK_SIZE 1024
Definition at line 35 of file vm_local.h.
PROGRAM_STACK_MASK
#define PROGRAM_STACK_MASK (PROGRAM_STACK_SIZE-1)
Definition at line 41 of file vm_local.h.
PROGRAM_STACK_SIZE
#define PROGRAM_STACK_SIZE 0x10000
Definition at line 40 of file vm_local.h.
VM_OFFSET_PROGRAM_STACK
#define VM_OFFSET_PROGRAM_STACK 0
Definition at line 141 of file vm_local.h.
VM_OFFSET_SYSTEM_CALL
#define VM_OFFSET_SYSTEM_CALL 4
Definition at line 142 of file vm_local.h.
Typedef Documentation
vmptr_t
typedef int vmptr_t
Definition at line 132 of file vm_local.h.
vmSymbol_t
typedef struct vmSymbol_s vmSymbol_t
Enumeration Type Documentation
opcode_t
enum opcode_t
Enumerator
OP_UNDEF
OP_IGNORE
OP_BREAK
OP_ENTER
OP_LEAVE
OP_CALL
OP_PUSH
OP_POP
OP_CONST
OP_LOCAL
OP_JUMP
OP_EQ
OP_NE
OP_LTI
OP_LEI
OP_GTI
OP_GEI
OP_LTU
OP_LEU
OP_GTU
OP_GEU
OP_EQF
OP_NEF
OP_LTF
OP_LEF
OP_GTF
OP_GEF
OP_LOAD1
OP_LOAD2
OP_LOAD4
OP_STORE1
OP_STORE2
OP_STORE4
OP_ARG
OP_BLOCK_COPY
OP_SEX8
OP_SEX16
OP_NEGI
OP_ADD
OP_SUB
OP_DIVI
OP_DIVU
OP_MODI
OP_MODU
OP_MULI
OP_MULU
OP_BAND
OP_BOR
OP_BXOR
OP_BCOM
OP_LSH
OP_RSHI
OP_RSHU
OP_NEGF
OP_ADDF
OP_SUBF
OP_DIVF
OP_MULF
OP_CVIF
OP_CVFI
Definition at line 43 of file vm_local.h.
              {
     OP_UNDEF,
     OP_IGNORE,
     OP_BREAK,
     OP_ENTER,
     OP_LEAVE,
     OP_CALL,
     OP_PUSH,
     OP_POP,
     OP_CONST,
     OP_LOCAL,
     OP_JUMP,
     //-------------------
     OP_EQ,
     OP_NE,
     OP_LTI,
     OP_LEI,
     OP_GTI,
     OP_GEI,
     OP_LTU,
     OP_LEU,
     OP_GTU,
     OP_GEU,
     OP_EQF,
     OP_NEF,
     OP_LTF,
     OP_LEF,
     OP_GTF,
     OP_GEF,
     //-------------------
     OP_LOAD1,
     OP_LOAD2,
     OP_LOAD4,
     OP_STORE1,
     OP_STORE2,
     OP_STORE4,              // *(stack[top-1]) = stack[top]
     OP_ARG,
     OP_BLOCK_COPY,
     //-------------------
     OP_SEX8,
     OP_SEX16,
     OP_NEGI,
     OP_ADD,
     OP_SUB,
     OP_DIVI,
     OP_DIVU,
     OP_MODI,
     OP_MODU,
     OP_MULI,
     OP_MULU,
     OP_BAND,
     OP_BOR,
     OP_BXOR,
     OP_BCOM,
     OP_LSH,
     OP_RSHI,
     OP_RSHU,
     OP_NEGF,
     OP_ADDF,
     OP_SUBF,
     OP_DIVF,
     OP_MULF,
     OP_CVIF,
     OP_CVFI
 } opcode_t;
Function Documentation
VM_BlockCopy()
void VM_BlockCopy (unsigned int dest, unsigned int src, size_t n)
Definition at line 997 of file vm.c.
 {
     unsigned int dataMask = currentVM->dataMask;
     if ((dest & dataMask) != dest
     || (src & dataMask) != src
     || ((dest + n) & dataMask) != dest + n
     || ((src + n) & dataMask) != src + n)
     {
         Com_Error(ERR_DROP, "OP_BLOCK_COPY out of range!");
     }
     Com_Memcpy(currentVM->dataBase + dest, currentVM->dataBase + src, n);
 }
Referenced by DoSyscall(), PPC_ComputeCode(), VM_CallInterpreted(), and VM_Compile().
VM_CallCompiled()
int VM_CallCompiled (vm_t * vm, int * args)
Definition at line 1168 of file vm_armv7l.c.
 {
     byte    stack[OPSTACK_SIZE + 15];
     int *opStack;
     int programStack = vm->programStack;
     int stackOnEntry = programStack;
     byte    *image = vm->dataBase;
     int *argPointer;
     int retVal;
     currentVM = vm;
     vm->currentlyInterpreting = qtrue;
     programStack -= ( 8 + 4 * MAX_VMMAIN_ARGS );
     argPointer = (int *)&image[ programStack + 8 ];
     memcpy( argPointer, args, 4 * MAX_VMMAIN_ARGS );
     argPointer[-1] = 0;
     argPointer[-2] = -1;
     opStack = PADP(stack, 16);
     *opStack = 0xDEADBEEF;
 #if 0
     Com_Printf("r5 opStack:\t\t%p\n", opStack);
     Com_Printf("r7 codeBase:\t\t%p\n", vm->codeBase);
     Com_Printf("r8 programStack:\t0x%x\n", programStack);
     Com_Printf("r9 dataBase:\t\t%p\n", vm->dataBase);
 #endif
     /* call generated code */
     {
         //int (*entry)(void *, int, void *, int);
         int (*entry)(vm_t*, int*, int*);
         entry = (void *)(vm->codeBase);
         //__asm__ volatile("bkpt");
         //retVal = entry(vm->codeBase, programStack, vm->dataBase, vm->dataMask);
         retVal = entry(vm, &programStack, opStack);
     }
     if(*opStack != 0xDEADBEEF)
     {
         Com_Error(ERR_DROP, "opStack corrupted in compiled code");
     }
     if(programStack != stackOnEntry - (8 + 4 * MAX_VMMAIN_ARGS))
         Com_Error(ERR_DROP, "programStack corrupted in compiled code");
     vm->programStack = stackOnEntry;
     vm->currentlyInterpreting = qfalse;
     return retVal;
 }
Referenced by VM_Call().
VM_CallInterpreted()
int VM_CallInterpreted (vm_t * vm, int * args)
Definition at line 318 of file vm_interpreted.c.
{
     byte        stack[OPSTACK_SIZE + 15];
     int     *opStack;
     uint8_t     opStackOfs;
     int     programCounter;
     int     programStack;
     int     stackOnEntry;
     byte    *image;
     int     *codeImage;
     int     v1;
     int     dataMask;
     int     arg;
 #ifdef DEBUG_VM
     vmSymbol_t  *profileSymbol;
 #endif
     // interpret the code
     vm->currentlyInterpreting = qtrue;
     // we might be called recursively, so this might not be the very top
     programStack = stackOnEntry = vm->programStack;
 #ifdef DEBUG_VM
     profileSymbol = VM_ValueToFunctionSymbol( vm, 0 );
     // uncomment this for debugging breakpoints
     vm->breakFunction = 0;
 #endif
     // set up the stack frame
     image = vm->dataBase;
     codeImage = (int *)vm->codeBase;
     dataMask = vm->dataMask;
     programCounter = 0;
     programStack -= ( 8 + 4 * MAX_VMMAIN_ARGS );
     for ( arg = 0; arg < MAX_VMMAIN_ARGS; arg++ )
         *(int *)&image[ programStack + 8 + arg * 4 ] = args[ arg ];
     *(int *)&image[ programStack + 4 ] = 0; // return stack
     *(int *)&image[ programStack ] = -1;    // will terminate the loop on return
     VM_Debug(0);
     // leave a free spot at start of stack so
     // that as long as opStack is valid, opStack-1 will
     // not corrupt anything
     opStack = PADP(stack, 16);
     *opStack = 0xDEADBEEF;
     opStackOfs = 0;
 //  vm_debugLevel=2;
     // main interpreter loop, will exit when a LEAVE instruction
     // grabs the -1 program counter
 #define r2 codeImage[programCounter]
     while ( 1 ) {
         int     opcode, r0, r1;
 //      unsigned int    r2;
 nextInstruction:
         r0 = opStack[opStackOfs];
         r1 = opStack[(uint8_t) (opStackOfs - 1)];
 nextInstruction2:
 #ifdef DEBUG_VM
         if ( (unsigned)programCounter >= vm->codeLength ) {
             Com_Error( ERR_DROP, "VM pc out of range" );
             return 0;
         }
         if ( programStack <= vm->stackBottom ) {
             Com_Error( ERR_DROP, "VM stack overflow" );
             return 0;
         }
         if ( programStack & 3 ) {
             Com_Error( ERR_DROP, "VM program stack misaligned" );
             return 0;
         }
         if ( vm_debugLevel > 1 ) {
             Com_Printf( "%s %s\n", DEBUGSTR, opnames[opcode] );
         }
         profileSymbol->profileCount++;
 #endif
         opcode = codeImage[ programCounter++ ];
         switch ( opcode ) {
 #ifdef DEBUG_VM
         default:
             Com_Error( ERR_DROP, "Bad VM instruction" );  // this should be scanned on load!
             return 0;
 #endif
         case OP_BREAK:
             vm->breakCount++;
             goto nextInstruction2;
         case OP_CONST:
             opStackOfs++;
             r1 = r0;
             r0 = opStack[opStackOfs] = r2;
             programCounter += 1;
             goto nextInstruction2;
         case OP_LOCAL:
             opStackOfs++;
             r1 = r0;
             r0 = opStack[opStackOfs] = r2+programStack;
             programCounter += 1;
             goto nextInstruction2;
         case OP_LOAD4:
 #ifdef DEBUG_VM
             if(opStack[opStackOfs] & 3)
             {
                 Com_Error( ERR_DROP, "OP_LOAD4 misaligned" );
                 return 0;
             }
 #endif
             r0 = opStack[opStackOfs] = *(int *) &image[ r0 & dataMask ];
             goto nextInstruction2;
         case OP_LOAD2:
             r0 = opStack[opStackOfs] = *(unsigned short *)&image[ r0 & dataMask ];
             goto nextInstruction2;
         case OP_LOAD1:
             r0 = opStack[opStackOfs] = image[ r0 & dataMask ];
             goto nextInstruction2;
         case OP_STORE4:
             *(int *)&image[ r1 & dataMask ] = r0;
             opStackOfs -= 2;
             goto nextInstruction;
         case OP_STORE2:
             *(short *)&image[ r1 & dataMask ] = r0;
             opStackOfs -= 2;
             goto nextInstruction;
         case OP_STORE1:
             image[ r1 & dataMask ] = r0;
             opStackOfs -= 2;
             goto nextInstruction;
         case OP_ARG:
             // single byte offset from programStack
             *(int *)&image[ (codeImage[programCounter] + programStack) & dataMask ] = r0;
             opStackOfs--;
             programCounter += 1;
             goto nextInstruction;
         case OP_BLOCK_COPY:
             VM_BlockCopy(r1, r0, r2);
             programCounter += 1;
             opStackOfs -= 2;
             goto nextInstruction;
         case OP_CALL:
             // save current program counter
             *(int *)&image[ programStack ] = programCounter;
             // jump to the location on the stack
             programCounter = r0;
             opStackOfs--;
             if ( programCounter < 0 ) {
                 // system call
                 int     r;
 //              int     temp;
 #ifdef DEBUG_VM
                 int     stomped;
                 if ( vm_debugLevel ) {
                     Com_Printf( "%s---> systemcall(%i)\n", DEBUGSTR, -1 - programCounter );
                 }
 #endif
                 // save the stack to allow recursive VM entry
 //              temp = vm->callLevel;
                 vm->programStack = programStack - 4;
 #ifdef DEBUG_VM
                 stomped = *(int *)&image[ programStack + 4 ];
 #endif
                 *(int *)&image[ programStack + 4 ] = -1 - programCounter;
 //VM_LogSyscalls( (int *)&image[ programStack + 4 ] );
                 {
                     // the vm has ints on the stack, we expect
                     // pointers so we might have to convert it
                     if (sizeof(intptr_t) != sizeof(int)) {
                         intptr_t argarr[ MAX_VMSYSCALL_ARGS ];
                         int *imagePtr = (int *)&image[ programStack ];
                         int i;
                         for (i = 0; i < ARRAY_LEN(argarr); ++i) {
                             argarr[i] = *(++imagePtr);
                         }
                         r = vm->systemCall( argarr );
                     } else {
                         intptr_t* argptr = (intptr_t *)&image[ programStack + 4 ];
                         r = vm->systemCall( argptr );
                     }
                 }
 #ifdef DEBUG_VM
                 // this is just our stack frame pointer, only needed
                 // for debugging
                 *(int *)&image[ programStack + 4 ] = stomped;
 #endif
                 // save return value
                 opStackOfs++;
                 opStack[opStackOfs] = r;
                 programCounter = *(int *)&image[ programStack ];
 //              vm->callLevel = temp;
 #ifdef DEBUG_VM
                 if ( vm_debugLevel ) {
                     Com_Printf( "%s<--- %s\n", DEBUGSTR, VM_ValueToSymbol( vm, programCounter ) );
                 }
 #endif
             } else if ( (unsigned)programCounter >= vm->instructionCount ) {
                 Com_Error( ERR_DROP, "VM program counter out of range in OP_CALL" );
                 return 0;
             } else {
                 programCounter = vm->instructionPointers[ programCounter ];
             }
             goto nextInstruction;
         // push and pop are only needed for discarded or bad function return values
         case OP_PUSH:
             opStackOfs++;
             goto nextInstruction;
         case OP_POP:
             opStackOfs--;
             goto nextInstruction;
         case OP_ENTER:
 #ifdef DEBUG_VM
             profileSymbol = VM_ValueToFunctionSymbol( vm, programCounter );
 #endif
             // get size of stack frame
             v1 = r2;
             programCounter += 1;
             programStack -= v1;
 #ifdef DEBUG_VM
             // save old stack frame for debugging traces
             *(int *)&image[programStack+4] = programStack + v1;
             if ( vm_debugLevel ) {
                 Com_Printf( "%s---> %s\n", DEBUGSTR, VM_ValueToSymbol( vm, programCounter - 5 ) );
                 if ( vm->breakFunction && programCounter - 5 == vm->breakFunction ) {
                     // this is to allow setting breakpoints here in the debugger
                     vm->breakCount++;
 //                  vm_debugLevel = 2;
 //                  VM_StackTrace( vm, programCounter, programStack );
                 }
 //              vm->callLevel++;
             }
 #endif
             goto nextInstruction;
         case OP_LEAVE:
             // remove our stack frame
             v1 = r2;
             programStack += v1;
             // grab the saved program counter
             programCounter = *(int *)&image[ programStack ];
 #ifdef DEBUG_VM
             profileSymbol = VM_ValueToFunctionSymbol( vm, programCounter );
             if ( vm_debugLevel ) {
 //              vm->callLevel--;
                 Com_Printf( "%s<--- %s\n", DEBUGSTR, VM_ValueToSymbol( vm, programCounter ) );
             }
 #endif
             // check for leaving the VM
             if ( programCounter == -1 ) {
                 goto done;
             } else if ( (unsigned)programCounter >= vm->codeLength ) {
                 Com_Error( ERR_DROP, "VM program counter out of range in OP_LEAVE" );
                 return 0;
             }
             goto nextInstruction;
         /*
         ===================================================================
         BRANCHES
         ===================================================================
         */
         case OP_JUMP:
             if ( (unsigned)r0 >= vm->instructionCount )
             {
                 Com_Error( ERR_DROP, "VM program counter out of range in OP_JUMP" );
                 return 0;
             }
             programCounter = vm->instructionPointers[ r0 ];
             opStackOfs--;
             goto nextInstruction;
         case OP_EQ:
             opStackOfs -= 2;
             if ( r1 == r0 ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_NE:
             opStackOfs -= 2;
             if ( r1 != r0 ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_LTI:
             opStackOfs -= 2;
             if ( r1 < r0 ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_LEI:
             opStackOfs -= 2;
             if ( r1 <= r0 ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_GTI:
             opStackOfs -= 2;
             if ( r1 > r0 ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_GEI:
             opStackOfs -= 2;
             if ( r1 >= r0 ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_LTU:
             opStackOfs -= 2;
             if ( ((unsigned)r1) < ((unsigned)r0) ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_LEU:
             opStackOfs -= 2;
             if ( ((unsigned)r1) <= ((unsigned)r0) ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_GTU:
             opStackOfs -= 2;
             if ( ((unsigned)r1) > ((unsigned)r0) ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_GEU:
             opStackOfs -= 2;
             if ( ((unsigned)r1) >= ((unsigned)r0) ) {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_EQF:
             opStackOfs -= 2;
             if(((float *) opStack)[(uint8_t) (opStackOfs + 1)] == ((float *) opStack)[(uint8_t) (opStackOfs + 2)])
             {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_NEF:
             opStackOfs -= 2;
             if(((float *) opStack)[(uint8_t) (opStackOfs + 1)] != ((float *) opStack)[(uint8_t) (opStackOfs + 2)])
             {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_LTF:
             opStackOfs -= 2;
             if(((float *) opStack)[(uint8_t) (opStackOfs + 1)] < ((float *) opStack)[(uint8_t) (opStackOfs + 2)])
             {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_LEF:
             opStackOfs -= 2;
             if(((float *) opStack)[(uint8_t) ((uint8_t) (opStackOfs + 1))] <= ((float *) opStack)[(uint8_t) ((uint8_t) (opStackOfs + 2))])
             {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_GTF:
             opStackOfs -= 2;
             if(((float *) opStack)[(uint8_t) (opStackOfs + 1)] > ((float *) opStack)[(uint8_t) (opStackOfs + 2)])
             {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         case OP_GEF:
             opStackOfs -= 2;
             if(((float *) opStack)[(uint8_t) (opStackOfs + 1)] >= ((float *) opStack)[(uint8_t) (opStackOfs + 2)])
             {
                 programCounter = r2;    //vm->instructionPointers[r2];
                 goto nextInstruction;
             } else {
                 programCounter += 1;
                 goto nextInstruction;
             }
         //===================================================================
         case OP_NEGI:
             opStack[opStackOfs] = -r0;
             goto nextInstruction;
         case OP_ADD:
             opStackOfs--;
             opStack[opStackOfs] = r1 + r0;
             goto nextInstruction;
         case OP_SUB:
             opStackOfs--;
             opStack[opStackOfs] = r1 - r0;
             goto nextInstruction;
         case OP_DIVI:
             opStackOfs--;
             opStack[opStackOfs] = r1 / r0;
             goto nextInstruction;
         case OP_DIVU:
             opStackOfs--;
             opStack[opStackOfs] = ((unsigned) r1) / ((unsigned) r0);
             goto nextInstruction;
         case OP_MODI:
             opStackOfs--;
             opStack[opStackOfs] = r1 % r0;
             goto nextInstruction;
         case OP_MODU:
             opStackOfs--;
             opStack[opStackOfs] = ((unsigned) r1) % ((unsigned) r0);
             goto nextInstruction;
         case OP_MULI:
             opStackOfs--;
             opStack[opStackOfs] = r1 * r0;
             goto nextInstruction;
         case OP_MULU:
             opStackOfs--;
             opStack[opStackOfs] = ((unsigned) r1) * ((unsigned) r0);
             goto nextInstruction;
         case OP_BAND:
             opStackOfs--;
             opStack[opStackOfs] = ((unsigned) r1) & ((unsigned) r0);
             goto nextInstruction;
         case OP_BOR:
             opStackOfs--;
             opStack[opStackOfs] = ((unsigned) r1) | ((unsigned) r0);
             goto nextInstruction;
         case OP_BXOR:
             opStackOfs--;
             opStack[opStackOfs] = ((unsigned) r1) ^ ((unsigned) r0);
             goto nextInstruction;
         case OP_BCOM:
             opStack[opStackOfs] = ~((unsigned) r0);
             goto nextInstruction;
         case OP_LSH:
             opStackOfs--;
             opStack[opStackOfs] = r1 << r0;
             goto nextInstruction;
         case OP_RSHI:
             opStackOfs--;
             opStack[opStackOfs] = r1 >> r0;
             goto nextInstruction;
         case OP_RSHU:
             opStackOfs--;
             opStack[opStackOfs] = ((unsigned) r1) >> r0;
             goto nextInstruction;
         case OP_NEGF:
             ((float *) opStack)[opStackOfs] =  -((float *) opStack)[opStackOfs];
             goto nextInstruction;
         case OP_ADDF:
             opStackOfs--;
             ((float *) opStack)[opStackOfs] = ((float *) opStack)[opStackOfs] + ((float *) opStack)[(uint8_t) (opStackOfs + 1)];
             goto nextInstruction;
         case OP_SUBF:
             opStackOfs--;
             ((float *) opStack)[opStackOfs] = ((float *) opStack)[opStackOfs] - ((float *) opStack)[(uint8_t) (opStackOfs + 1)];
             goto nextInstruction;
         case OP_DIVF:
             opStackOfs--;
             ((float *) opStack)[opStackOfs] = ((float *) opStack)[opStackOfs] / ((float *) opStack)[(uint8_t) (opStackOfs + 1)];
             goto nextInstruction;
         case OP_MULF:
             opStackOfs--;
             ((float *) opStack)[opStackOfs] = ((float *) opStack)[opStackOfs] * ((float *) opStack)[(uint8_t) (opStackOfs + 1)];
             goto nextInstruction;
         case OP_CVIF:
             ((float *) opStack)[opStackOfs] = (float) opStack[opStackOfs];
             goto nextInstruction;
         case OP_CVFI:
             opStack[opStackOfs] = Q_ftol(((float *) opStack)[opStackOfs]);
             goto nextInstruction;
         case OP_SEX8:
             opStack[opStackOfs] = (signed char) opStack[opStackOfs];
             goto nextInstruction;
         case OP_SEX16:
             opStack[opStackOfs] = (short) opStack[opStackOfs];
             goto nextInstruction;
         }
     }
 done:
     vm->currentlyInterpreting = qfalse;
     if (opStackOfs != 1 || *opStack != 0xDEADBEEF)
         Com_Error(ERR_DROP, "Interpreter error: opStack[0] = %X, opStackOfs = %d", opStack[0], opStackOfs);
     vm->programStack = stackOnEntry;
     // return the result
     return opStack[opStackOfs];
 }
Referenced by VM_Call().
VM_Compile()
void VM_Compile (vm_t * vm, vmHeader_t * header)
Definition at line 597 of file vm_armv7l.c.
 {
     unsigned char *code;
     int i_count, pc = 0;
     int pass;
     int codeoffsets[2]; // was 1024 but it's only used for OFF_CODE and OFF_IMMEDIATES
 #define j_rel(x) (pass?_j_rel(x, pc):0xBAD)
 #define OFFSET(i) (pass?(j_rel(codeoffsets[i]-vm->codeLength)):(0xF000000F))
 //#define new_offset() (offsidx++)
 #define get_offset(i) (codeoffsets[i])
 #define save_offset(i) (codeoffsets[i] = vm->codeLength)
 #define OFF_CODE 0
 #define OFF_IMMEDIATES 1
     vm->compiled = qfalse;
     vm->codeBase = NULL;
     vm->codeLength = 0;
     for (pass = 0; pass < 2; ++pass) {
 //  int offsidx = 0;
 #ifdef CONST_OPTIMIZE
     // const optimization
     unsigned got_const = 0, const_value = 0;
 #endif
     if(pass)
     {
         vm->codeBase = mmap(NULL, vm->codeLength, PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0);
         if(vm->codeBase == MAP_FAILED)
             Com_Error(ERR_FATAL, "VM_CompileARM: can't mmap memory");
         vm->codeLength = 0;
     }
     //int (*entry)(vm_t*, int*, int*);
     emit(PUSH((((1<<8)-1)<<4)|(1<<14))); // push R4-R11, LR
     emit(SUBi(SP, SP, 12)); // align stack!
     emit(LDRai(rCODEBASE, R0, offsetof(vm_t, codeBase)));
     emit(LDRai(rDATABASE, R0, offsetof(vm_t, dataBase)));
     emit(LDRai(rDATAMASK, R0, offsetof(vm_t, dataMask)));
     emit(LDRai(rPSTACK, R1, 0));
     emit(MOV(rOPSTACK, R2)); // TODO: reverse opstack to avoid writing to return address
     emit(MOV(rOPSTACKBASE, rOPSTACK));
     emit(BLi(OFFSET(OFF_CODE)));
     // save return value in r0
     emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
     emit(ADDi(SP, SP, 12)); // align stack!
     emit(POP((((1<<8)-1)<<4)|(1<<15))); // pop R4-R11, LR -> PC
     /* save some immediates here */
     emit(BKPT(0));
     emit(BKPT(0));
     save_offset(OFF_IMMEDIATES);
 //  emit((unsigned)whatever);
     emit(BKPT(0));
     emit(BKPT(0));
     save_offset(OFF_CODE);
 //  offsidx = OFF_IMMEDIATES+1;
     code = (unsigned char *) header + header->codeOffset;
     pc = 0;
     for (i_count = 0; i_count < header->instructionCount; i_count++) {
         union {
             unsigned char b[4];
             unsigned int i;
         } arg;
         unsigned char op = code[pc++];
         vm->instructionPointers[i_count] = vm->codeLength;
         if (vm_opInfo[op] & opImm4)
         {
             memcpy(arg.b, &code[pc], 4);
             pc += 4;
 #ifdef EXCESSIVE_DEBUG
             Com_Printf("%d: instruction %d (%s %d), offset %d\n", pass, i_count, opnames[op], arg.i, vm->codeLength);
 #endif
         }
         else if (vm_opInfo[op] & opImm1)
         {
             arg.b[0] = code[pc];
             ++pc;
 #ifdef EXCESSIVE_DEBUG
             Com_Printf("%d: instruction %d (%s %hhd), offset %d\n", pass, i_count, opnames[op], arg.i, vm->codeLength);
 #endif
         }
         else
         {
 #ifdef EXCESSIVE_DEBUG
             Com_Printf("%d: instruction %d (%s), offset %d\n", pass, i_count, opnames[op], vm->codeLength);
 #endif
         }
         // TODO: for debug only
         //emit_MOVRxi(R4, i_count);
         switch ( op )
         {
             case OP_UNDEF:
                 break;
             case OP_IGNORE:
                 NOTIMPL(op);
                 break;
             case OP_BREAK:
                 emit(BKPT(0));
                 break;
             case OP_ENTER:
                 MAYBE_EMIT_CONST();
                 emit(PUSH1(LR));
                 emit(SUBi(SP, SP, 12)); // align stack
                 if (arg.i == 0 || can_encode(arg.i))
                 {
                     emit(SUBi(rPSTACK, rPSTACK, arg.i)); // pstack -= arg
                 }
                 else
                 {
                     emit_MOVR0i(arg.i);
                     emit(SUB(rPSTACK, rPSTACK, R0)); // pstack -= arg
                 }
                 break;
             case OP_LEAVE:
                 if (arg.i == 0 || can_encode(arg.i))
                 {
                     emit(ADDi(rPSTACK, rPSTACK, arg.i)); // pstack += arg
                 }
                 else
                 {
                     emit_MOVR0i(arg.i);
                     emit(ADD(rPSTACK, rPSTACK, R0)); // pstack += arg
                 }
                 emit(ADDi(SP, SP, 12));
                 emit(0xe49df004); // pop pc
                 break;
             case OP_CALL:
 #if 0
                 // save next instruction
                 emit_MOVR0i(i_count);
                 emit(STRa(R0, rDATABASE, rPSTACK));      // dataBase[pstack] = r0
 #endif
 #ifdef CONST_OPTIMIZE
                 if (got_const)
                 {
                     NOTIMPL(op);
                 }
                 else
 #endif
                 {
                     static int bytes_to_skip = -1;
                     static unsigned start_block = -1;
                     MAYBE_EMIT_CONST();
                     // get instruction nr from stack
                     emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                     emit(CMPi(R0, 0)); // check if syscall
                     if (start_block == -1)
                         start_block = vm->codeLength;
                     emit(cond(LT, Bi(j_rel(bytes_to_skip))));
                         CHECK_JUMP;
                         emit_MOVRxi_or_NOP(R1, (unsigned)vm->instructionPointers);
                         emit(LDRa(R0, R1, rLSL(2, R0))); // r0 = ((int*)r1)[r0]
                         emit(ADD(R0, rCODEBASE, R0)); // r0 = codeBase+r0
                         emit(BLX(R0));
                         emit(Bi(j_rel(vm->instructionPointers[i_count+1]-vm->codeLength)));
                     if (bytes_to_skip == -1)
                         bytes_to_skip = vm->codeLength - start_block;
                     emit(MOV(R1, rPSTACK));
                     emit_MOVRxi(R12, (unsigned)asmcall);
                     emit(BLX(R12));
                     // store return value
                     emit(STRaiw(R0, rOPSTACK, 4));      // opstack+=4; *opstack = r0
                 }
                 break;
             case OP_PUSH:
                 MAYBE_EMIT_CONST();
                 emit(ADDi(rOPSTACK, rOPSTACK, 4));
                 break;
             case OP_POP:
                 MAYBE_EMIT_CONST();
                 emit(SUBi(rOPSTACK, rOPSTACK, 4));
                 break;
             case OP_CONST:
                 MAYBE_EMIT_CONST();
                 emit_MOVR0i(arg.i);
                 emit(STRaiw(R0, rOPSTACK, 4));      // opstack+=4; *opstack = r0
                 break;
             case OP_LOCAL:
                 MAYBE_EMIT_CONST();
                 if (arg.i == 0 || can_encode(arg.i))
                 {
                     emit(ADDi(R0, rPSTACK, arg.i));     // r0 = pstack+arg
                 }
                 else
                 {
                     emit_MOVR0i(arg.i);
                     emit(ADD(R0, rPSTACK, R0));     // r0 = pstack+arg
                 }
                 emit(STRaiw(R0, rOPSTACK, 4));      // opstack+=4; *opstack = r0
                 break;
             case OP_JUMP:
 #ifdef CONST_OPTIMIZE
                 if (got_const)
                 {
                     NOTIMPL(op);
                 }
                 else
 #endif
                 {
                     emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                     CHECK_JUMP;
                     emit_MOVRxi(R1, (unsigned)vm->instructionPointers);
                     emit(LDRa(R0, R1, rLSL(2, R0))); // r0 = ((int*)r1)[r0]
                     emit(ADD(R0, rCODEBASE, R0)); // r0 = codeBase+r0
                     emit(BLX(R0));
                 }
                 break;
             case OP_EQ:
                 IJ(EQ);
                 break;
             case OP_NE:
                 IJ(NE);
                 break;
             case OP_LTI:
                 IJ(LT);
                 break;
             case OP_LEI:
                 IJ(LE);
                 break;
             case OP_GTI:
                 IJ(GT);
                 break;
             case OP_GEI:
                 IJ(GE);
                 break;
             case OP_LTU:
                 IJ(LO);
                 break;
             case OP_LEU:
                 IJ(LS);
                 break;
             case OP_GTU:
                 IJ(HI);
                 break;
             case OP_GEU:
                 IJ(HS);
                 break;
             case OP_EQF:
                 FJ(EQ);
                 break;
             case OP_NEF:
                 FJ(NE);
                 break;
             case OP_LTF:
                 FJ(LT);
                 break;
             case OP_LEF:
                 FJ(LE);
                 break;
             case OP_GTF:
                 FJ(GT);
                 break;
             case OP_GEF:
                 FJ(GE);
                 break;
             case OP_LOAD1:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));   // r0 = *opstack
                 emit(AND(R0, rDATAMASK, R0));    // r0 = r0 & rDATAMASK
                 emit(LDRBa(R0, rDATABASE, R0));  // r0 = (unsigned char)dataBase[r0]
                 emit(STRai(R0, rOPSTACK, 0));   // *opstack = r0
                 break;
             case OP_LOAD2:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));   // r0 = *opstack
                 emit(AND(R0, rDATAMASK, R0));    // r0 = r0 & rDATAMASK
                 emit(LDRHa(R0, rDATABASE, R0));  // r0 = (unsigned short)dataBase[r0]
                 emit(STRai(R0, rOPSTACK, 0));   // *opstack = r0
                 break;
             case OP_LOAD4:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));   // r0 = *opstack
                 emit(AND(R0, rDATAMASK, R0));    // r0 = r0 & rDATAMASK
                 emit(LDRa(R0, rDATABASE, R0));  // r0 = dataBase[r0]
                 emit(STRai(R0, rOPSTACK, 0));   // *opstack = r0
                 break;
             case OP_STORE1:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r1 = *opstack; rOPSTACK -= 4
                 emit(AND(R1, rDATAMASK, R1));    // r1 = r1 & rDATAMASK
                 emit(STRBa(R0, rDATABASE, R1)); // database[r1] = r0
                 break;
             case OP_STORE2:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r1 = *opstack; rOPSTACK -= 4
                 emit(AND(R1, rDATAMASK, R1));    // r1 = r1 & rDATAMASK
                 emit(STRHa(R0, rDATABASE, R1)); // database[r1] = r0
                 break;
             case OP_STORE4:
                 MAYBE_EMIT_CONST();
                 // optimize: use load multiple
                 // value
                 emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 // pointer
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r1 = *opstack; rOPSTACK -= 4
                 emit(AND(R1, rDATAMASK, R1));    // r1 = r1 & rDATAMASK
                 // store value at pointer
                 emit(STRa(R0, rDATABASE, R1)); // database[r1] = r0
                 break;
             case OP_ARG:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R0, rOPSTACK, 4));      // r0 = *opstack; rOPSTACK -= 4
                 emit(ADDi(R1, rPSTACK, arg.b[0]));  // r1 = programStack+arg
                 emit(AND(R1, rDATAMASK, R1));       // r1 = r1 & rDATAMASK
                 emit(STRa(R0, rDATABASE, R1));      // dataBase[r1] = r0
                 break;
             case OP_BLOCK_COPY:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 emit(LDRTxi(R0, rOPSTACK, 4));
                 emit_MOVRxi(R2, arg.i);
                 emit_MOVRxi(R12, (unsigned)VM_BlockCopy);
                 emit(BLX(R12));
                 break;
             case OP_SEX8:
                 MAYBE_EMIT_CONST();
                 emit(LDRSBai(R0, rOPSTACK, 0));      // sign extend *opstack
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_SEX16:
                 MAYBE_EMIT_CONST();
                 emit(LDRSHai(R0, rOPSTACK, 0));      // sign extend *opstack
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_NEGI:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(RSBi(R0, R0, 0));         // r0 = -r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_ADD:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(ADD(R0, R1, R0));         // r0 = r1 + r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_SUB:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(SUB(R0, R1, R0));         // r0 = r1 - r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_DIVI:
             case OP_DIVU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R1, rOPSTACK, 0));  // r1 = *opstack
                 emit(LDRxiw(R0, rOPSTACK, 4)); // opstack-=4; r0 = *opstack
                 if ( op == OP_DIVI )
                     emit_MOVRxi(R12, (unsigned)__aeabi_idiv);
                 else
                     emit_MOVRxi(R12, (unsigned)__aeabi_uidiv);
                 emit(BLX(R12));
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_MODI:
             case OP_MODU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R1, rOPSTACK, 0));  // r1 = *opstack
                 emit(LDRxiw(R0, rOPSTACK, 4)); // opstack-=4; r0 = *opstack
                 if ( op == OP_MODI )
                     emit_MOVRxi(R12, (unsigned)__aeabi_idivmod);
                 else
                     emit_MOVRxi(R12, (unsigned)__aeabi_uidivmod);
                 emit(BLX(R12));
                 emit(STRai(R1, rOPSTACK, 0));  // *opstack = r1
                 break;
             case OP_MULI:
             case OP_MULU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(MUL(R0, R1, R0));         // r0 = r1 * r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BAND:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(AND(R0, R1, R0));         // r0 = r1 & r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BOR:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(ORR(R0, R1, R0));         // r0 = r1 | r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BXOR:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(EOR(R0, R1, R0));         // r0 = r1 ^ r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BCOM:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(MVN(R0, R0));             // r0 = ~r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_LSH:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(LSL(R0, R1, R0));         // r0 = r1 << r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_RSHI:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(ASR(R0, R1, R0));         // r0 = r1 >> r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_RSHU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(LSR(R0, R1, R0));         // r0 = (unsigned)r1 >> r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_NEGF:
                 MAYBE_EMIT_CONST();
                 emit(VLDRa(S14, rOPSTACK, 0)); // s14 = *((float*)opstack)
                 emit(VNEG_F32(S14, S14));      // s15 = -s14
                 emit(VSTRa(S14, rOPSTACK, 0)); // *((float*)opstack) = s15
                 break;
             case OP_ADDF:
                 MAYBE_EMIT_CONST();
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // vldr can't modify rOPSTACK so
                 // we'd either need to change it
                 // with sub or use regular ldr+vmov
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VADD_F32(S14, S15, S14));   // s14 = s14 + s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_SUBF:
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // see OP_ADDF
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VSUB_F32(S14, S15, S14));   // s14 = s14 - s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_DIVF:
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // see OP_ADDF
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VDIV_F32(S14, S15, S14));   // s14 = s14 / s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_MULF:
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // see OP_ADDF
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VMUL_F32(S14, S15, S14));   // s14 = s14 * s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_CVIF:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(VMOVass(S14,R0));         // s14 = r0
                 emit(VCVT_F32_S32(S14, S14));  // s15 = (float)s14
                 emit(VSTRa(S14, rOPSTACK, 0)); // *((float*)opstack) = s15
                 break;
             case OP_CVFI:
                 MAYBE_EMIT_CONST();
                 emit(VLDRa(S14, rOPSTACK, 0)); // s14 = *((float*)opstack)
                 emit(VCVT_S32_F32(S14, S14));  // s15 = (int)s14
                 emit(VMOVssa(R0,S14));         // s14 = r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
         }
     }
     // never reached
     emit(BKPT(0));
     } // pass
     if (mprotect(vm->codeBase, vm->codeLength, PROT_READ|PROT_EXEC/* |PROT_WRITE */)) {
         VM_Destroy_Compiled(vm);
         DIE("mprotect failed");
     }
     // clear icache, http://blogs.arm.com/software-enablement/141-caches-and-self-modifying-code/
     __clear_cache(vm->codeBase, vm->codeBase+vm->codeLength);
     vm->destroy = VM_Destroy_Compiled;
     vm->compiled = qtrue;
 }
Referenced by VM_Create().
VM_LogSyscalls()
void VM_LogSyscalls (int * args)
Definition at line 978 of file vm.c.
{
     static  int     callnum;
     static  FILE    *f;
     if ( !f ) {
         f = fopen("syscalls.log", "w" );
     }
     callnum++;
     fprintf(f, "%i: %p (%i) = %i %i %i %i\n", callnum, (void*)(args - (int *)currentVM->dataBase),
         args[0], args[1], args[2], args[3], args[4] );
 }
VM_PrepareInterpreter()
void VM_PrepareInterpreter (vm_t * vm, vmHeader_t * header)
Definition at line 170 of file vm_interpreted.c.
{
     int     op;
     int     byte_pc;
     int     int_pc;
     byte    *code;
     int     instruction;
     int     *codeBase;
     vm->codeBase = Hunk_Alloc( vm->codeLength*4, h_high );          // we're now int aligned
 //  memcpy( vm->codeBase, (byte *)header + header->codeOffset, vm->codeLength );
     // we don't need to translate the instructions, but we still need
     // to find each instructions starting point for jumps
     int_pc = byte_pc = 0;
     instruction = 0;
     code = (byte *)header + header->codeOffset;
     codeBase = (int *)vm->codeBase;
     // Copy and expand instructions to words while building instruction table
     while ( instruction < header->instructionCount ) {
         vm->instructionPointers[ instruction ] = int_pc;
         instruction++;
         op = (int)code[ byte_pc ];
         codeBase[int_pc] = op;
         if(byte_pc > header->codeLength)
             Com_Error(ERR_DROP, "VM_PrepareInterpreter: pc > header->codeLength");
         byte_pc++;
         int_pc++;
         // these are the only opcodes that aren't a single byte
         switch ( op ) {
         case OP_ENTER:
         case OP_CONST:
         case OP_LOCAL:
         case OP_LEAVE:
         case OP_EQ:
         case OP_NE:
         case OP_LTI:
         case OP_LEI:
         case OP_GTI:
         case OP_GEI:
         case OP_LTU:
         case OP_LEU:
         case OP_GTU:
         case OP_GEU:
         case OP_EQF:
         case OP_NEF:
         case OP_LTF:
         case OP_LEF:
         case OP_GTF:
         case OP_GEF:
         case OP_BLOCK_COPY:
             codeBase[int_pc] = loadWord(&code[byte_pc]);
             byte_pc += 4;
             int_pc++;
             break;
         case OP_ARG:
             codeBase[int_pc] = (int)code[byte_pc];
             byte_pc++;
             int_pc++;
             break;
         default:
             break;
         }
     }
     int_pc = 0;
     instruction = 0;
     // Now that the code has been expanded to int-sized opcodes, we'll translate instruction index
     //into an index into codeBase[], which contains opcodes and operands.
     while ( instruction < header->instructionCount ) {
         op = codeBase[ int_pc ];
         instruction++;
         int_pc++;
         switch ( op ) {
         // These ops need to translate addresses in jumps from instruction index to int index
         case OP_EQ:
         case OP_NE:
         case OP_LTI:
         case OP_LEI:
         case OP_GTI:
         case OP_GEI:
         case OP_LTU:
         case OP_LEU:
         case OP_GTU:
         case OP_GEU:
         case OP_EQF:
         case OP_NEF:
         case OP_LTF:
         case OP_LEF:
         case OP_GTF:
         case OP_GEF:
             if(codeBase[int_pc] < 0 || codeBase[int_pc] > vm->instructionCount)
                 Com_Error(ERR_DROP, "VM_PrepareInterpreter: Jump to invalid instruction number");
             // codeBase[pc] is the instruction index. Convert that into an offset into
             //the int-aligned codeBase[] by the lookup table.
             codeBase[int_pc] = vm->instructionPointers[codeBase[int_pc]];
             int_pc++;
             break;
         // These opcodes have an operand that isn't an instruction index
         case OP_ENTER:
         case OP_CONST:
         case OP_LOCAL:
         case OP_LEAVE:
         case OP_BLOCK_COPY:
         case OP_ARG:
             int_pc++;
             break;
         default:
             break;
         }
     }
 }
Referenced by VM_Create().
VM_SymbolToValue()
int VM_SymbolToValue (vm_t * vm, const char * symbol)
Definition at line 143 of file vm.c.
{
     vmSymbol_t  *sym;
     for ( sym = vm->symbols ; sym ; sym = sym->next ) {
         if ( !strcmp( symbol, sym->symName ) ) {
             return sym->symValue;
         }
     }
     return 0;
 }
VM_ValueToFunctionSymbol()
vmSymbol_t* VM_ValueToFunctionSymbol (vm_t * vm, int value)
Definition at line 121 of file vm.c.
{
     vmSymbol_t  *sym;
     static vmSymbol_t   nullSym;
     sym = vm->symbols;
     if ( !sym ) {
         return &nullSym;
     }
     while ( sym->next && sym->next->symValue <= value ) {
         sym = sym->next;
     }
     return sym;
 }
Referenced by VM_CallInterpreted().
VM_ValueToSymbol()
const char* VM_ValueToSymbol (vm_t * vm, int value)
Definition at line 91 of file vm.c.
{
     vmSymbol_t  *sym;
     static char     text[MAX_TOKEN_CHARS];
     sym = vm->symbols;
     if ( !sym ) {
         return "NO SYMBOLS";
     }
     // find the symbol
     while ( sym->next && sym->next->symValue <= value ) {
         sym = sym->next;
     }
     if ( value == sym->symValue ) {
         return sym->symName;
     }
     Com_sprintf( text, sizeof( text ), "%s+%i", sym->symName, value - sym->symValue );
     return text;
 }
Referenced by VM_CallInterpreted(), and VM_StackTrace().
Variable Documentation
currentVM
vm_t* currentVM
Definition at line 39 of file vm.c.
Referenced by asmcall(), blockcopy(), DoSyscall(), VM_ArgPtr(), VM_AsmCall(), VM_BlockCopy(), VM_Call(), VM_CallCompiled(), VM_DllSyscall(), VM_ExplicitArgPtr(), VM_Free(), and VM_LogSyscalls().
vm_debugLevel
int vm_debugLevel
Definition at line 41 of file vm.c.
Referenced by VM_Call(), VM_CallInterpreted(), and VM_Debug().