ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_setup.c File Reference
ui_setup.c File Reference
#include "ui_local.h"
Classes
struct setupMenuInfo_t
Macros
#define SETUP_MENU_VERTICAL_SPACING 34
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define ID_CUSTOMIZEPLAYER 10
#define ID_CUSTOMIZECONTROLS 11
#define ID_SYSTEMCONFIG 12
#define ID_GAME 13
#define ID_CDKEY 14
#define ID_LOAD 15
#define ID_SAVE 16
#define ID_DEFAULTS 17
#define ID_BACK 18
Functions
static void Setup_ResetDefaults_Action (qboolean result)
static void Setup_ResetDefaults_Draw (void)
static void UI_SetupMenu_Event (void *ptr, int event)
static void UI_SetupMenu_Init (void)
void UI_SetupMenu_Cache (void)
void UI_SetupMenu (void)
Variables
static setupMenuInfo_t setupMenuInfo
Macro Definition Documentation
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 37 of file ui_setup.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 38 of file ui_setup.c.
ART_FRAMEL
#define ART_FRAMEL "menu/art/frame2_l"
Definition at line 39 of file ui_setup.c.
ART_FRAMER
#define ART_FRAMER "menu/art/frame1_r"
Definition at line 40 of file ui_setup.c.
ID_BACK
#define ID_BACK 18
Definition at line 50 of file ui_setup.c.
ID_CDKEY
#define ID_CDKEY 14
Definition at line 46 of file ui_setup.c.
ID_CUSTOMIZECONTROLS
#define ID_CUSTOMIZECONTROLS 11
Definition at line 43 of file ui_setup.c.
ID_CUSTOMIZEPLAYER
#define ID_CUSTOMIZEPLAYER 10
Definition at line 42 of file ui_setup.c.
ID_DEFAULTS
#define ID_DEFAULTS 17
Definition at line 49 of file ui_setup.c.
ID_GAME
#define ID_GAME 13
Definition at line 45 of file ui_setup.c.
ID_LOAD
#define ID_LOAD 15
Definition at line 47 of file ui_setup.c.
ID_SAVE
#define ID_SAVE 16
Definition at line 48 of file ui_setup.c.
ID_SYSTEMCONFIG
#define ID_SYSTEMCONFIG 12
Definition at line 44 of file ui_setup.c.
SETUP_MENU_VERTICAL_SPACING
#define SETUP_MENU_VERTICAL_SPACING 34
Definition at line 35 of file ui_setup.c.
Function Documentation
Setup_ResetDefaults_Action()
static void Setup_ResetDefaults_Action (qboolean result) static
Definition at line 78 of file ui_setup.c.
{
     if( !result ) {
         return;
     }
     trap_Cmd_ExecuteText( EXEC_APPEND, "exec default.cfg\n");
     trap_Cmd_ExecuteText( EXEC_APPEND, "cvar_restart\n");
     trap_Cmd_ExecuteText( EXEC_APPEND, "vid_restart\n" );
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
Referenced by UI_SetupMenu_Event().
Setup_ResetDefaults_Draw()
static void Setup_ResetDefaults_Draw (void) static
Definition at line 93 of file ui_setup.c.
{
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 0, "WARNING: This will reset *ALL*", UI_CENTER|UI_SMALLFONT, color_yellow );
     UI_DrawProportionalString( SCREEN_WIDTH/2, 356 + PROP_HEIGHT * 1, "options to their default values.", UI_CENTER|UI_SMALLFONT, color_yellow );
 }
References color_yellow, PROP_HEIGHT, SCREEN_WIDTH, UI_CENTER, UI_DrawProportionalString(), and UI_SMALLFONT.
Referenced by UI_SetupMenu_Event().
UI_SetupMenu()
void UI_SetupMenu (void)
Definition at line 324 of file ui_setup.c.
{
     UI_SetupMenu_Init();
     UI_PushMenu( &setupMenuInfo.menu );
 }
References setupMenuInfo_t::menu, setupMenuInfo, UI_PushMenu(), and UI_SetupMenu_Init().
Referenced by InGame_Event(), Main_MenuEvent(), and Rankings_MenuEvent().
UI_SetupMenu_Cache()
void UI_SetupMenu_Cache (void)
Definition at line 311 of file ui_setup.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_SetupMenu_Init().
UI_SetupMenu_Event()
static void UI_SetupMenu_Event (void * ptr, int event) static
Definition at line 104 of file ui_setup.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     switch( ((menucommon_s*)ptr)->id ) {
     case ID_CUSTOMIZEPLAYER:
         UI_PlayerSettingsMenu();
         break;
     case ID_CUSTOMIZECONTROLS:
         UI_ControlsMenu();
         break;
     case ID_SYSTEMCONFIG:
         UI_GraphicsOptionsMenu();
         break;
     case ID_GAME:
         UI_PreferencesMenu();
         break;
     case ID_CDKEY:
         UI_CDKeyMenu();
         break;
 //  case ID_LOAD:
 //      UI_LoadConfigMenu();
 //      break;
 //  case ID_SAVE:
 //      UI_SaveConfigMenu();
 //      break;
     case ID_DEFAULTS:
         UI_ConfirmMenu( "SET TO DEFAULTS?", Setup_ResetDefaults_Draw, Setup_ResetDefaults_Action );
         break;
     case ID_BACK:
         UI_PopMenu();
         break;
     }
 }
References ID_BACK, ID_CDKEY, ID_CUSTOMIZECONTROLS, ID_CUSTOMIZEPLAYER, ID_DEFAULTS, ID_GAME, ID_SYSTEMCONFIG, QM_ACTIVATED, Setup_ResetDefaults_Action(), Setup_ResetDefaults_Draw(), UI_CDKeyMenu(), UI_ConfirmMenu(), UI_ControlsMenu(), UI_GraphicsOptionsMenu(), UI_PlayerSettingsMenu(), UI_PopMenu(), and UI_PreferencesMenu().
Referenced by UI_SetupMenu_Init().
UI_SetupMenu_Init()
static void UI_SetupMenu_Init (void) static
Definition at line 154 of file ui_setup.c.
{
     int             y;
     UI_SetupMenu_Cache();
     memset( &setupMenuInfo, 0, sizeof(setupMenuInfo) );
     setupMenuInfo.menu.wrapAround = qtrue;
     setupMenuInfo.menu.fullscreen = qtrue;
     setupMenuInfo.banner.generic.type               = MTYPE_BTEXT;
     setupMenuInfo.banner.generic.x                  = 320;
     setupMenuInfo.banner.generic.y                  = 16;
     setupMenuInfo.banner.string                     = "SETUP";
     setupMenuInfo.banner.color                      = color_white;
     setupMenuInfo.banner.style                      = UI_CENTER;
     setupMenuInfo.framel.generic.type               = MTYPE_BITMAP;
     setupMenuInfo.framel.generic.name               = ART_FRAMEL;
     setupMenuInfo.framel.generic.flags              = QMF_INACTIVE;
     setupMenuInfo.framel.generic.x                  = 0;
     setupMenuInfo.framel.generic.y                  = 78;
     setupMenuInfo.framel.width                      = 256;
     setupMenuInfo.framel.height                     = 329;
     setupMenuInfo.framer.generic.type               = MTYPE_BITMAP;
     setupMenuInfo.framer.generic.name               = ART_FRAMER;
     setupMenuInfo.framer.generic.flags              = QMF_INACTIVE;
     setupMenuInfo.framer.generic.x                  = 376;
     setupMenuInfo.framer.generic.y                  = 76;
     setupMenuInfo.framer.width                      = 256;
     setupMenuInfo.framer.height                     = 334;
     y = 134;
     setupMenuInfo.setupplayer.generic.type          = MTYPE_PTEXT;
     setupMenuInfo.setupplayer.generic.flags         = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     setupMenuInfo.setupplayer.generic.x             = 320;
     setupMenuInfo.setupplayer.generic.y             = y;
     setupMenuInfo.setupplayer.generic.id            = ID_CUSTOMIZEPLAYER;
     setupMenuInfo.setupplayer.generic.callback      = UI_SetupMenu_Event;
     setupMenuInfo.setupplayer.string                = "PLAYER";
     setupMenuInfo.setupplayer.color                 = color_red;
     setupMenuInfo.setupplayer.style                 = UI_CENTER;
     y += SETUP_MENU_VERTICAL_SPACING;
     setupMenuInfo.setupcontrols.generic.type        = MTYPE_PTEXT;
     setupMenuInfo.setupcontrols.generic.flags       = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     setupMenuInfo.setupcontrols.generic.x           = 320;
     setupMenuInfo.setupcontrols.generic.y           = y;
     setupMenuInfo.setupcontrols.generic.id          = ID_CUSTOMIZECONTROLS;
     setupMenuInfo.setupcontrols.generic.callback    = UI_SetupMenu_Event;
     setupMenuInfo.setupcontrols.string              = "CONTROLS";
     setupMenuInfo.setupcontrols.color               = color_red;
     setupMenuInfo.setupcontrols.style               = UI_CENTER;
     y += SETUP_MENU_VERTICAL_SPACING;
     setupMenuInfo.setupsystem.generic.type          = MTYPE_PTEXT;
     setupMenuInfo.setupsystem.generic.flags         = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     setupMenuInfo.setupsystem.generic.x             = 320;
     setupMenuInfo.setupsystem.generic.y             = y;
     setupMenuInfo.setupsystem.generic.id            = ID_SYSTEMCONFIG;
     setupMenuInfo.setupsystem.generic.callback      = UI_SetupMenu_Event;
     setupMenuInfo.setupsystem.string                = "SYSTEM";
     setupMenuInfo.setupsystem.color                 = color_red;
     setupMenuInfo.setupsystem.style                 = UI_CENTER;
     y += SETUP_MENU_VERTICAL_SPACING;
     setupMenuInfo.game.generic.type                 = MTYPE_PTEXT;
     setupMenuInfo.game.generic.flags                = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     setupMenuInfo.game.generic.x                    = 320;
     setupMenuInfo.game.generic.y                    = y;
     setupMenuInfo.game.generic.id                   = ID_GAME;
     setupMenuInfo.game.generic.callback             = UI_SetupMenu_Event;
     setupMenuInfo.game.string                       = "GAME OPTIONS";
     setupMenuInfo.game.color                        = color_red;
     setupMenuInfo.game.style                        = UI_CENTER;
     y += SETUP_MENU_VERTICAL_SPACING;
     setupMenuInfo.cdkey.generic.type                = MTYPE_PTEXT;
     setupMenuInfo.cdkey.generic.flags               = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     setupMenuInfo.cdkey.generic.x                   = 320;
     setupMenuInfo.cdkey.generic.y                   = y;
     setupMenuInfo.cdkey.generic.id                  = ID_CDKEY;
     setupMenuInfo.cdkey.generic.callback            = UI_SetupMenu_Event;
     setupMenuInfo.cdkey.string                      = "CD Key";
     setupMenuInfo.cdkey.color                       = color_red;
     setupMenuInfo.cdkey.style                       = UI_CENTER;
     if( !trap_Cvar_VariableValue( "cl_paused" ) ) {
 #if 0
         y += SETUP_MENU_VERTICAL_SPACING;
         setupMenuInfo.load.generic.type                 = MTYPE_PTEXT;
         setupMenuInfo.load.generic.flags                = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
         setupMenuInfo.load.generic.x                    = 320;
         setupMenuInfo.load.generic.y                    = y;
         setupMenuInfo.load.generic.id                   = ID_LOAD;
         setupMenuInfo.load.generic.callback             = UI_SetupMenu_Event;
         setupMenuInfo.load.string                       = "LOAD";
         setupMenuInfo.load.color                        = color_red;
         setupMenuInfo.load.style                        = UI_CENTER;
         y += SETUP_MENU_VERTICAL_SPACING;
         setupMenuInfo.save.generic.type                 = MTYPE_PTEXT;
         setupMenuInfo.save.generic.flags                = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
         setupMenuInfo.save.generic.x                    = 320;
         setupMenuInfo.save.generic.y                    = y;
         setupMenuInfo.save.generic.id                   = ID_SAVE;
         setupMenuInfo.save.generic.callback             = UI_SetupMenu_Event;
         setupMenuInfo.save.string                       = "SAVE";
         setupMenuInfo.save.color                        = color_red;
         setupMenuInfo.save.style                        = UI_CENTER;
 #endif
         y += SETUP_MENU_VERTICAL_SPACING;
         setupMenuInfo.defaults.generic.type             = MTYPE_PTEXT;
         setupMenuInfo.defaults.generic.flags            = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
         setupMenuInfo.defaults.generic.x                = 320;
         setupMenuInfo.defaults.generic.y                = y;
         setupMenuInfo.defaults.generic.id               = ID_DEFAULTS;
         setupMenuInfo.defaults.generic.callback         = UI_SetupMenu_Event;
         setupMenuInfo.defaults.string                   = "DEFAULTS";
         setupMenuInfo.defaults.color                    = color_red;
         setupMenuInfo.defaults.style                    = UI_CENTER;
     }
     setupMenuInfo.back.generic.type                 = MTYPE_BITMAP;
     setupMenuInfo.back.generic.name                 = ART_BACK0;
     setupMenuInfo.back.generic.flags                = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     setupMenuInfo.back.generic.id                   = ID_BACK;
     setupMenuInfo.back.generic.callback             = UI_SetupMenu_Event;
     setupMenuInfo.back.generic.x                    = 0;
     setupMenuInfo.back.generic.y                    = 480-64;
     setupMenuInfo.back.width                        = 128;
     setupMenuInfo.back.height                       = 64;
     setupMenuInfo.back.focuspic                     = ART_BACK1;
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.banner );
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.framel );
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.framer );
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.setupplayer );
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.setupcontrols );
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.setupsystem );
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.game );
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.cdkey );
 //  Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.load );
 //  Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.save );
     if( !trap_Cvar_VariableValue( "cl_paused" ) ) {
         Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.defaults );
     }
     Menu_AddItem( &setupMenuInfo.menu, &setupMenuInfo.back );
 }
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, setupMenuInfo_t::back, setupMenuInfo_t::banner, menucommon_s::callback, setupMenuInfo_t::cdkey, menutext_s::color, color_red, color_white, setupMenuInfo_t::defaults, menucommon_s::flags, menubitmap_s::focuspic, setupMenuInfo_t::framel, setupMenuInfo_t::framer, _tag_menuframework::fullscreen, setupMenuInfo_t::game, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_CDKEY, ID_CUSTOMIZECONTROLS, ID_CUSTOMIZEPLAYER, ID_DEFAULTS, ID_GAME, ID_LOAD, ID_SAVE, ID_SYSTEMCONFIG, setupMenuInfo_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, QMF_CENTER_JUSTIFY, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, SETUP_MENU_VERTICAL_SPACING, setupMenuInfo_t::setupcontrols, setupMenuInfo, setupMenuInfo_t::setupplayer, setupMenuInfo_t::setupsystem, menutext_s::string, menutext_s::style, trap_Cvar_VariableValue(), menucommon_s::type, UI_CENTER, UI_SetupMenu_Cache(), UI_SetupMenu_Event(), menubitmap_s::width, _tag_menuframework::wrapAround, menucommon_s::x, and menucommon_s::y.
Referenced by UI_SetupMenu().
Variable Documentation
setupMenuInfo
setupMenuInfo_t setupMenuInfo static
Definition at line 70 of file ui_setup.c.
Referenced by UI_SetupMenu(), and UI_SetupMenu_Init().