ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_libvar.c File Reference
l_libvar.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_libvar.h"
Functions
float LibVarStringValue (const char *string)
libvar_t * LibVarAlloc (const char *var_name)
void LibVarDeAlloc (libvar_t *v)
void LibVarDeAllocAll (void)
libvar_t * LibVarGet (const char *var_name)
char * LibVarGetString (const char *var_name)
float LibVarGetValue (const char *var_name)
libvar_t * LibVar (const char *var_name, const char *value)
char * LibVarString (const char *var_name, const char *value)
float LibVarValue (const char *var_name, const char *value)
void LibVarSet (const char *var_name, const char *value)
qboolean LibVarChanged (const char *var_name)
void LibVarSetNotModified (const char *var_name)
Variables
libvar_t * libvarlist = NULL
Function Documentation
LibVar()
libvar_t* LibVar (const char * var_name, const char * value)
Definition at line 190 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVarGet(var_name);
     if (v) return v;
     //create new variable
     v = LibVarAlloc(var_name);
     //variable string
     v->string = (char *) GetMemory(strlen(value) + 1);
     strcpy(v->string, value);
     //the value
     v->value = LibVarStringValue(v->string);
     //variable is modified
     v->modified = qtrue;
     //
     return v;
 } //end of the function LibVar
References GetMemory(), LibVarAlloc(), LibVarGet(), LibVarStringValue(), libvar_s::modified, qtrue, libvar_s::string, and libvar_s::value.
Referenced by AAS_Setup(), BotSetupGoalAI(), BotSetupMoveAI(), LibVarString(), and LibVarValue().
LibVarAlloc()
libvar_t* LibVarAlloc (const char * var_name)
Definition at line 83 of file l_libvar.c.
 {
     libvar_t *v;
     v = (libvar_t *) GetMemory(sizeof(libvar_t));
     Com_Memset(v, 0, sizeof(libvar_t));
     v->name = (char *) GetMemory(strlen(var_name)+1);
     strcpy(v->name, var_name);
     //add the variable in the list
     v->next = libvarlist;
     libvarlist = v;
     return v;
 } //end of the function LibVarAlloc
References Com_Memset, GetMemory(), libvarlist, libvar_s::name, and libvar_s::next.
Referenced by LibVar(), and LibVarSet().
LibVarChanged()
qboolean LibVarChanged (const char * var_name)
Definition at line 266 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVarGet(var_name);
     if (v)
     {
         return v->modified;
     } //end if
     else
     {
         return qfalse;
     } //end else
 } //end of the function LibVarChanged
References LibVarGet(), libvar_s::modified, and qfalse.
LibVarDeAlloc()
void LibVarDeAlloc (libvar_t * v)
Definition at line 102 of file l_libvar.c.
 {
     if (v->string) FreeMemory(v->string);
     FreeMemory(v->name);
     FreeMemory(v);
 } //end of the function LibVarDeAlloc
References FreeMemory(), libvar_s::name, and libvar_s::string.
Referenced by LibVarDeAllocAll().
LibVarDeAllocAll()
void LibVarDeAllocAll (void)
Definition at line 114 of file l_libvar.c.
 {
     libvar_t *v;
     for (v = libvarlist; v; v = libvarlist)
     {
         libvarlist = libvarlist->next;
         LibVarDeAlloc(v);
     } //end for
     libvarlist = NULL;
 } //end of the function LibVarDeAllocAll
References LibVarDeAlloc(), libvarlist, libvar_s::next, and NULL.
Referenced by Export_BotLibShutdown().
LibVarGet()
libvar_t* LibVarGet (const char * var_name)
Definition at line 131 of file l_libvar.c.
 {
     libvar_t *v;
     for (v = libvarlist; v; v = v->next)
     {
         if (!Q_stricmp(v->name, var_name))
         {
             return v;
         } //end if
     } //end for
     return NULL;
 } //end of the function LibVarGet
References libvarlist, libvar_s::name, libvar_s::next, NULL, and Q_stricmp().
Referenced by LibVar(), LibVarChanged(), LibVarGetString(), LibVarGetValue(), LibVarSet(), and LibVarSetNotModified().
LibVarGetString()
char* LibVarGetString (const char * var_name)
Definition at line 150 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVarGet(var_name);
     if (v)
     {
         return v->string;
     } //end if
     else
     {
         return "";
     } //end else
 } //end of the function LibVarGetString
References LibVarGet(), and libvar_s::string.
Referenced by AAS_LoadAASFile(), and Export_BotLibVarGet().
LibVarGetValue()
float LibVarGetValue (const char * var_name)
Definition at line 170 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVarGet(var_name);
     if (v)
     {
         return v->value;
     } //end if
     else
     {
         return 0;
     } //end else
 } //end of the function LibVarGetValue
References LibVarGet(), and libvar_s::value.
Referenced by AAS_ContinueInit(), AAS_InitClustering(), AAS_InitReachability(), AAS_StartFrame(), BotEnterChat(), BotExportTest(), BotFreeCharacter(), BotFreeChatState(), BotLoadCharacterSkill(), BotLoadChatFile(), BotNumInitialChats(), BotReplyChat(), Export_BotLibSetup(), FreeWeightConfig(), and ReadWeightConfig().
LibVarSet()
void LibVarSet (const char * var_name, const char * value)
Definition at line 239 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVarGet(var_name);
     if (v)
     {
         FreeMemory(v->string);
     } //end if
     else
     {
         v = LibVarAlloc(var_name);
     } //end else
     //variable string
     v->string = (char *) GetMemory(strlen(value) + 1);
     strcpy(v->string, value);
     //the value
     v->value = LibVarStringValue(v->string);
     //variable is modified
     v->modified = qtrue;
 } //end of the function LibVarSet
References FreeMemory(), GetMemory(), LibVarAlloc(), LibVarGet(), LibVarStringValue(), libvar_s::modified, qtrue, libvar_s::string, and libvar_s::value.
Referenced by AAS_StartFrame(), Export_BotLibVarSet(), LoadItemConfig(), and LoadWeaponConfig().
LibVarSetNotModified()
void LibVarSetNotModified (const char * var_name)
Definition at line 286 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVarGet(var_name);
     if (v)
     {
         v->modified = qfalse;
     } //end if
 } //end of the function LibVarSetNotModified
References LibVarGet(), libvar_s::modified, and qfalse.
LibVarString()
char* LibVarString (const char * var_name, const char * value)
Definition at line 213 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVar(var_name, value);
     return v->string;
 } //end of the function LibVarString
References LibVar(), and libvar_s::string.
Referenced by BotSetupChatAI(), BotSetupGoalAI(), and BotSetupWeaponAI().
LibVarStringValue()
float LibVarStringValue (const char * string)
Definition at line 45 of file l_libvar.c.
 {
     int dotfound = 0;
     float value = 0;
     while(*string)
     {
         if (*string < '0' || *string > '9')
         {
             if (dotfound || *string != '.')
             {
                 return 0;
             } //end if
             else
             {
                 dotfound = 10;
                 string++;
             } //end if
         } //end if
         if (dotfound)
         {
             value = value + (float) (*string - '0') / (float) dotfound;
             dotfound *= 10;
         } //end if
         else
         {
             value = value * 10.0 + (float) (*string - '0');
         } //end else
         string++;
     } //end while
     return value;
 } //end of the function LibVarStringValue
Referenced by LibVar(), and LibVarSet().
LibVarValue()
float LibVarValue (const char * var_name, const char * value)
Definition at line 226 of file l_libvar.c.
 {
     libvar_t *v;
     v = LibVar(var_name, value);
     return v->value;
 } //end of the function LibVarValue
References LibVar(), and libvar_s::value.
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_ContinueInit(), AAS_InitAASLinkHeap(), AAS_InitRouting(), AAS_InitSettings(), AAS_Reachability_JumpPad(), AAS_Setup(), BotSetupChatAI(), BotSetupGoalAI(), Export_BotLibSetup(), InitConsoleMessageHeap(), InitLevelItemHeap(), LoadItemConfig(), LoadWeaponConfig(), and Log_Open().
Variable Documentation
libvarlist
libvar_t* libvarlist = NULL
Definition at line 37 of file l_libvar.c.
Referenced by LibVarAlloc(), LibVarDeAllocAll(), and LibVarGet().