ioquake3 doxygen: C:/entry/dev/ioq3/code/sys/sys_main.c File Reference
sys_main.c File Reference
#include <signal.h>
#include <stdlib.h>
#include <limits.h>
#include <sys/types.h>
#include <stdarg.h>
#include <stdio.h>
#include <sys/stat.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <SDL.h>
#include <SDL_cpuinfo.h>
#include "sys_local.h"
#include "sys_loadlib.h"
#include "../qcommon/q_shared.h"
#include "../qcommon/qcommon.h"
Macros
#define PID_FILENAME PRODUCT_NAME ".pid"
#define DEFAULT_BASEDIR Sys_BinaryPath()
#define MINSDL_VERSION
Functions
void Sys_SetBinaryPath (const char *path)
char * Sys_BinaryPath (void)
void Sys_SetDefaultInstallPath (const char *path)
char * Sys_DefaultInstallPath (void)
char * Sys_DefaultAppPath (void)
void Sys_In_Restart_f (void)
Restart the input subsystem.
char * Sys_ConsoleInput (void)
Handle new console input.
char * Sys_GetClipboardData (void)
static char * Sys_PIDFileName (const char *gamedir)
void Sys_RemovePIDFile (const char *gamedir)
static qboolean Sys_WritePIDFile (const char *gamedir)
Return qtrue if there is an existing stale PID file.
void Sys_InitPIDFile (const char *gamedir)
static __attribute__ ((noreturn))
Single exit point (regular exit or in case of error).
void Sys_Quit (void)
cpuFeatures_t Sys_GetProcessorFeatures (void)
void Sys_Init (void)
void Sys_AnsiColorPrint (const char *msg)
Transform Q3 colour codes to ANSI escape sequences.
void Sys_Print (const char *msg)
void Sys_Error (const char *error,...)
int Sys_FileTime (char *path)
void Sys_UnloadDll (void *dllHandle)
void * Sys_LoadDll (const char *name, qboolean useSystemLib)
void * Sys_LoadGameDll (const char *name, intptr_t(QDECL **entryPoint)(int,...), intptr_t(*systemcalls)(intptr_t,...))
void Sys_ParseArgs (int argc, char **argv)
void Sys_SigHandler (int signal)
int main (int argc, char **argv)
Variables
static char binaryPath [MAX_OSPATH] = { 0 }
static char installPath [MAX_OSPATH] = { 0 }
Macro Definition Documentation
DEFAULT_BASEDIR
#define DEFAULT_BASEDIR Sys_BinaryPath()
Definition at line 598 of file sys_main.c.
MINSDL_VERSION
#define MINSDL_VERSION
Value:
    XSTRING(MINSDL_MAJOR) "." \
    XSTRING(MINSDL_MINOR) "." \
    XSTRING(MINSDL_PATCH)
PID_FILENAME
#define PID_FILENAME PRODUCT_NAME ".pid"
Definition at line 155 of file sys_main.c.
Function Documentation
__attribute__()
static __attribute__ ((noreturn)) static
Single exit point (regular exit or in case of error).
Parameters
exitCode
Definition at line 262 of file sys_main.c.
 {
     CON_Shutdown();
 #ifndef DEDICATED
     SDL_Quit();
 #endif
     if (exitCode < 2 && com_fullyInitialized) {
         // Normal exit
         Sys_RemovePIDFile(FS_GetCurrentGameDir());
     }
     NET_Shutdown();
     Sys_PlatformExit();
     exit(exitCode);
 }
main()
int main (int argc, char ** argv)
Definition at line 636 of file sys_main.c.
 {
     int   i;
     char  commandLine[MAX_STRING_CHARS] = { 0 };
     extern void Sys_LaunchAutoupdater(int argc, char** argv);
     Sys_LaunchAutoupdater(argc, argv);
 #ifndef DEDICATED
     // SDL version check
     // Compile time
 #   if !SDL_VERSION_ATLEAST(MINSDL_MAJOR,MINSDL_MINOR,MINSDL_PATCH)
 #       error A more recent version of SDL is required
 #   endif
     // Run time
     SDL_version ver;
     SDL_GetVersion(&ver);
 #define MINSDL_VERSION \
     XSTRING(MINSDL_MAJOR) "." \
     XSTRING(MINSDL_MINOR) "." \
     XSTRING(MINSDL_PATCH)
     if (SDL_VERSIONNUM(ver.major, ver.minor, ver.patch) <
         SDL_VERSIONNUM(MINSDL_MAJOR, MINSDL_MINOR, MINSDL_PATCH)) {
         Sys_Dialog(DT_ERROR, va("SDL version " MINSDL_VERSION " or greater is required, "
             "but only version %d.%d.%d was found. You may be able to obtain a more recent copy "
             "from http://www.libsdl.org/.", ver.major, ver.minor, ver.patch), "SDL Library Too Old");
         Sys_Exit(1);
     }
 #endif
     Sys_PlatformInit();
     // Set the initial time base
     Sys_Milliseconds();
 #ifdef __APPLE__
     // This is passed if we are launched by double-clicking
     if (argc >= 2 && Q_strncmp(argv[1], "-psn", 4) == 0)
         argc = 1;
 #endif
     Sys_ParseArgs(argc, argv);
     Sys_SetBinaryPath(Sys_Dirname(argv[0]));
     Sys_SetDefaultInstallPath(DEFAULT_BASEDIR);
     // Concatenate the command line for passing to Com_Init
     for (i = 1; i < argc; i++) {
         const qboolean containsSpaces = strchr(argv[i], ' ') != NULL;
         if (containsSpaces)
             Q_strcat(commandLine, sizeof(commandLine), "\"");
         Q_strcat(commandLine, sizeof(commandLine), argv[i]);
         if (containsSpaces)
             Q_strcat(commandLine, sizeof(commandLine), "\"");
         Q_strcat(commandLine, sizeof(commandLine), " ");
     }
     CON_Init();
     Com_Init(commandLine);
     NET_Init();
     signal(SIGILL, Sys_SigHandler);
     signal(SIGFPE, Sys_SigHandler);
     signal(SIGSEGV, Sys_SigHandler);
     signal(SIGTERM, Sys_SigHandler);
     signal(SIGINT, Sys_SigHandler);
     while (1) {
         Com_Frame();
     }
     return 0;
 }
Sys_AnsiColorPrint()
void Sys_AnsiColorPrint (const char * msg)
Transform Q3 colour codes to ANSI escape sequences.
Parameters
msg
Definition at line 325 of file sys_main.c.
 {
     static char buffer[MAXPRINTMSG];
     int         length = 0;
     static int  q3ToAnsi[8] =
     {
         30, // COLOR_BLACK
         31, // COLOR_RED
         32, // COLOR_GREEN
         33, // COLOR_YELLOW
         34, // COLOR_BLUE
         36, // COLOR_CYAN
         35, // COLOR_MAGENTA
         0   // COLOR_WHITE
     };
     while (*msg) {
         if (Q_IsColorString(msg) || *msg == '\n') {
             // First empty the buffer
             if (length > 0) {
                 buffer[length] = '\0';
                 fputs(buffer, stderr);
                 length = 0;
             }
             if (*msg == '\n') {
                 // Issue a reset and then the newline
                 fputs("\033[0m\n", stderr);
                 msg++;
             }
             else {
                 // Print the color code
                 Com_sprintf(buffer, sizeof(buffer), "\033[%dm",
                     q3ToAnsi[ColorIndex(*(msg + 1))]);
                 fputs(buffer, stderr);
                 msg += 2;
             }
         }
         else {
             if (length >= MAXPRINTMSG - 1)
                 break;
             buffer[length] = *msg;
             length++;
             msg++;
         }
     }
     // Empty anything still left in the buffer
     if (length > 0) {
         buffer[length] = '\0';
         fputs(buffer, stderr);
     }
 }
Referenced by CON_Print().
Sys_BinaryPath()
char* Sys_BinaryPath (void)
Returns
Definition at line 66 of file sys_main.c.
 {
     return binaryPath;
 }
Referenced by Sys_DefaultAppPath(), and Sys_LoadDll().
Sys_ConsoleInput()
char* Sys_ConsoleInput (void)
Handle new console input.
Returns
Definition at line 119 of file sys_main.c.
 {
     return CON_Input();
 }
Referenced by Com_GetSystemEvent().
Sys_DefaultAppPath()
char* Sys_DefaultAppPath (void)
Definition at line 95 of file sys_main.c.
 {
     return Sys_BinaryPath();
 }
Referenced by FS_Startup().
Sys_DefaultInstallPath()
char* Sys_DefaultInstallPath (void)
Returns
Definition at line 84 of file sys_main.c.
 {
     if (*installPath)
         return installPath;
     else
         return Sys_Cwd();
 }
Referenced by FS_Startup().
Sys_Error()
void Sys_Error (const char * error, ...)
Definition at line 396 of file sys_main.c.
 {
     va_list argptr;
     char    string[1024];
     va_start(argptr, error);
     Q_vsnprintf(string, sizeof(string), error, argptr);
     va_end(argptr);
     Sys_ErrorDialog(string);
     Sys_Exit(3);
 }
Sys_FileTime()
int Sys_FileTime (char * path)
Definition at line 436 of file sys_main.c.
 {
     struct stat buf;
     if (stat(path, &buf) == -1)
         return -1;
     return buf.st_mtime;
 }
Sys_GetClipboardData()
char* Sys_GetClipboardData (void)
Returns
Definition at line 128 of file sys_main.c.
 {
 #ifdef DEDICATED
     return NULL;
 #else
     char* data = NULL;
     char* cliptext;
     if ((cliptext = SDL_GetClipboardText()) != NULL) {
         if (cliptext[0] != '\0') {
             size_t bufsize = strlen(cliptext) + 1;
             data = Z_Malloc(bufsize);
             Q_strncpyz(data, cliptext, bufsize);
             // find first listed char and set to '\0'
             strtok(data, "\n\r\b");
         }
         SDL_free(cliptext);
     }
     return data;
 #endif
 }
Referenced by CL_GetClipboardData(), and Field_Paste().
Sys_GetProcessorFeatures()
cpuFeatures_t Sys_GetProcessorFeatures (void)
Returns
Definition at line 294 of file sys_main.c.
 {
     cpuFeatures_t features = 0;
 #ifndef DEDICATED
     if (SDL_HasRDTSC())      features |= CF_RDTSC;
     if (SDL_Has3DNow())      features |= CF_3DNOW;
     if (SDL_HasMMX())        features |= CF_MMX;
     if (SDL_HasSSE())        features |= CF_SSE;
     if (SDL_HasSSE2())       features |= CF_SSE2;
     if (SDL_HasAltiVec())    features |= CF_ALTIVEC;
 #endif
     return features;
 }
Referenced by Com_DetectAltivec().
Sys_In_Restart_f()
void Sys_In_Restart_f (void)
Restart the input subsystem.
Definition at line 103 of file sys_main.c.
 {
 #ifndef DEDICATED
     if (!SDL_WasInit(SDL_INIT_VIDEO)) {
         Com_Printf("in_restart: Cannot restart input while video is shutdown\n");
         return;
     }
 #endif
     IN_Restart();
 }
Referenced by Sys_Init().
Sys_Init()
void Sys_Init (void)
Definition at line 313 of file sys_main.c.
 {
     Cmd_AddCommand("in_restart", Sys_In_Restart_f);
     Cvar_Set("arch", OS_STRING " " ARCH_STRING);
     Cvar_Set("username", Sys_GetCurrentUser());
 }
Referenced by Com_Init().
Sys_InitPIDFile()
void Sys_InitPIDFile (const char * gamedir)
Parameters
gamedir
Definition at line 236 of file sys_main.c.
 {
     if (Sys_WritePIDFile(gamedir)) {
 #ifndef DEDICATED
         char message[1024];
         char modName[MAX_OSPATH];
         FS_GetModDescription(gamedir, modName, sizeof(modName));
         Q_CleanStr(modName);
         Com_sprintf(message, sizeof(message), "The last time %s ran, "
             "it didn't exit properly. This may be due to inappropriate video "
             "settings. Would you like to start with \"safe\" video settings?", modName);
         if (Sys_Dialog(DT_YES_NO, message, "Abnormal Exit") == DR_YES) {
             Cvar_Set("com_abnormalExit", "1");
         }
 #endif
     }
 }
Referenced by Com_Init(), and FS_Restart().
Sys_LoadDll()
void* Sys_LoadDll (const char * name, qboolean useSystemLib)
Definition at line 470 of file sys_main.c.
 {
     void* dllhandle = NULL;
     if (!Sys_DllExtension(name)) {
         Com_Printf("Refusing to attempt to load library \"%s\": Extension not allowed.\n", name);
         return NULL;
     }
     if (useSystemLib) {
         Com_Printf("Trying to load \"%s\"...\n", name);
         dllhandle = Sys_LoadLibrary(name);
     }
     if (!dllhandle) {
         const char* topDir;
         char libPath[MAX_OSPATH];
         int len;
         topDir = Sys_BinaryPath();
         if (!*topDir)
             topDir = ".";
         len = Com_sprintf(libPath, sizeof(libPath), "%s%c%s", topDir, PATH_SEP, name);
         if (len < sizeof(libPath)) {
             Com_Printf("Trying to load \"%s\" from \"%s\"...\n", name, topDir);
             dllhandle = Sys_LoadLibrary(libPath);
         }
         else {
             Com_Printf("Skipping trying to load \"%s\" from \"%s\", file name is too long.\n", name, topDir);
         }
         if (!dllhandle) {
             const char* basePath = Cvar_VariableString("fs_basepath");
             if (!basePath || !*basePath)
                 basePath = ".";
             if (FS_FilenameCompare(topDir, basePath)) {
                 len = Com_sprintf(libPath, sizeof(libPath), "%s%c%s", basePath, PATH_SEP, name);
                 if (len < sizeof(libPath)) {
                     Com_Printf("Trying to load \"%s\" from \"%s\"...\n", name, basePath);
                     dllhandle = Sys_LoadLibrary(libPath);
                 }
                 else {
                     Com_Printf("Skipping trying to load \"%s\" from \"%s\", file name is too long.\n", name, basePath);
                 }
             }
             if (!dllhandle)
                 Com_Printf("Loading \"%s\" failed\n", name);
         }
     }
     return dllhandle;
 }
Referenced by CL_InitRef().
Sys_LoadGameDll()
void* Sys_LoadGameDll (const char * name, intptr_t(QDECL **entryPoint)(int,...) , intptr_t(*)(intptr_t,...) systemcalls)
Definition at line 535 of file sys_main.c.
 {
     void* libHandle;
     void (*dllEntry)(intptr_t(*syscallptr)(intptr_t, ...));
     assert(name);
     if (!Sys_DllExtension(name)) {
         Com_Printf("Refusing to attempt to load library \"%s\": Extension not allowed.\n", name);
         return NULL;
     }
     Com_Printf("Loading DLL file: %s\n", name);
     libHandle = Sys_LoadLibrary(name);
     if (!libHandle) {
         Com_Printf("Sys_LoadGameDll(%s) failed:\n\"%s\"\n", name, Sys_LibraryError());
         return NULL;
     }
     dllEntry = Sys_LoadFunction(libHandle, "dllEntry");
     *entryPoint = Sys_LoadFunction(libHandle, "vmMain");
     if (!*entryPoint || !dllEntry) {
         Com_Printf("Sys_LoadGameDll(%s) failed to find vmMain function:\n\"%s\" !\n", name, Sys_LibraryError());
         Sys_UnloadLibrary(libHandle);
         return NULL;
     }
     Com_Printf("Sys_LoadGameDll(%s) found vmMain function at %p\n", name, *entryPoint);
     dllEntry(systemcalls);
     return libHandle;
 }
Sys_ParseArgs()
void Sys_ParseArgs (int argc, char ** argv)
Definition at line 578 of file sys_main.c.
 {
     if (argc == 2) {
         if (!strcmp(argv[1], "--version") ||
             !strcmp(argv[1], "-v")) {
             const char* date = PRODUCT_DATE;
 #ifdef DEDICATED
             fprintf(stdout, Q3_VERSION " dedicated server (%s)\n", date);
 #else
             fprintf(stdout, Q3_VERSION " client (%s)\n", date);
 #endif
             Sys_Exit(0);
         }
     }
 }
Referenced by main().
Sys_PIDFileName()
static char* Sys_PIDFileName (const char * gamedir) static
Definition at line 163 of file sys_main.c.
 {
     const char* homePath = Cvar_VariableString("fs_homepath");
     if (*homePath != '\0')
         return va("%s/%s/%s", homePath, gamedir, PID_FILENAME);
     return NULL;
 }
Referenced by Sys_RemovePIDFile(), and Sys_WritePIDFile().
Sys_Print()
void Sys_Print (const char * msg)
Definition at line 385 of file sys_main.c.
 {
     CON_LogWrite(msg);
     CON_Print(msg);
 }
Referenced by Com_Printf().
Sys_Quit()
void Sys_Quit (void)
Definition at line 285 of file sys_main.c.
 {
     Sys_Exit(0);
 }
Referenced by Com_Quit_f().
Sys_RemovePIDFile()
void Sys_RemovePIDFile (const char * gamedir)
Definition at line 178 of file sys_main.c.
 {
     char* pidFile = Sys_PIDFileName(gamedir);
     if (pidFile != NULL)
         remove(pidFile);
 }
Referenced by __attribute__(), and FS_Restart().
Sys_SetBinaryPath()
void Sys_SetBinaryPath (const char * path)
Parameters
path
Definition at line 57 of file sys_main.c.
 {
     Q_strncpyz(binaryPath, path, sizeof(binaryPath));
 }
Referenced by main().
Sys_SetDefaultInstallPath()
void Sys_SetDefaultInstallPath (const char * path)
Parameters
path
Definition at line 75 of file sys_main.c.
 {
     Q_strncpyz(installPath, path, sizeof(installPath));
 }
Referenced by main().
Sys_SigHandler()
void Sys_SigHandler (int signal)
Definition at line 607 of file sys_main.c.
 {
     static qboolean signalcaught = qfalse;
     if (signalcaught) {
         fprintf(stderr, "DOUBLE SIGNAL FAULT: Received signal %d, exiting...\n",
             signal);
     }
     else {
         signalcaught = qtrue;
         VM_Forced_Unload_Start();
 #ifndef DEDICATED
         CL_Shutdown(va("Received signal %d", signal), qtrue, qtrue);
 #endif
         SV_Shutdown(va("Received signal %d", signal));
         VM_Forced_Unload_Done();
     }
     if (signal == SIGTERM || signal == SIGINT)
         Sys_Exit(1);
     else
         Sys_Exit(2);
 }
Referenced by CON_CtrlHandler(), and main().
Sys_UnloadDll()
void Sys_UnloadDll (void * dllHandle)
Definition at line 451 of file sys_main.c.
 {
     if (!dllHandle) {
         Com_Printf("Sys_UnloadDll(NULL)\n");
         return;
     }
     Sys_UnloadLibrary(dllHandle);
 }
Referenced by VM_Free().
Sys_WritePIDFile()
static qboolean Sys_WritePIDFile (const char * gamedir) static
Return qtrue if there is an existing stale PID file.
Parameters
gamedir
Returns
Definition at line 192 of file sys_main.c.
 {
     char* pidFile = Sys_PIDFileName(gamedir);
     FILE* f;
     qboolean  stale = qfalse;
     if (pidFile == NULL)
         return qfalse;
     // First, check if the pid file is already there
     if ((f = fopen(pidFile, "r")) != NULL) {
         char  pidBuffer[64] = { 0 };
         int   pid;
         pid = fread(pidBuffer, sizeof(char), sizeof(pidBuffer) - 1, f);
         fclose(f);
         if (pid > 0) {
             pid = atoi(pidBuffer);
             if (!Sys_PIDIsRunning(pid))
                 stale = qtrue;
         }
         else
             stale = qtrue;
     }
     if (FS_CreatePath(pidFile)) {
         return 0;
     }
     if ((f = fopen(pidFile, "w")) != NULL) {
         fprintf(f, "%d", Sys_PID());
         fclose(f);
     }
     else
         Com_Printf(S_COLOR_YELLOW "Couldn't write %s.\n", pidFile);
     return stale;
 }
Referenced by Sys_InitPIDFile().
Variable Documentation
binaryPath
char binaryPath[MAX_OSPATH] = { 0 } static
Definition at line 50 of file sys_main.c.
Referenced by Sys_BinaryPath(), and Sys_SetBinaryPath().
installPath
char installPath[MAX_OSPATH] = { 0 } static
Definition at line 51 of file sys_main.c.
Referenced by Sys_DefaultInstallPath(), and Sys_SetDefaultInstallPath().