ioquake3 doxygen: C:/entry/dev/ioq3/code/cgame/cg_syscalls.c File Reference
cg_syscalls.c File Reference
#include "cg_local.h"
Functions
static intptr_t (QDECL *syscall)(intptr_t arg
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
int PASSFLOAT (float x)
void trap_Print (const char *fmt)
void trap_Error (const char *fmt)
int trap_Milliseconds (void)
void trap_Cvar_Register (vmCvar_t *vmCvar, const char *varName, const char *defaultValue, int flags)
void trap_Cvar_Update (vmCvar_t *vmCvar)
void trap_Cvar_Set (const char *var_name, const char *value)
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
int trap_Argc (void)
void trap_Argv (int n, char *buffer, int bufferLength)
void trap_Args (char *buffer, int bufferLength)
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
void trap_FS_FCloseFile (fileHandle_t f)
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
void trap_SendConsoleCommand (const char *text)
The string provided by text is run as if typed as a command into the console.
void trap_AddCommand (const char *cmdName)
The string cmdName is added to a tab-completion list for the console.
void trap_RemoveCommand (const char *cmdName)
Although this trap is not actually used anywhere in baseq3 game source, a reasonable assumption, based on function name and parameters, is that this trap removes a command name from the list of command completions.
void trap_SendClientCommand (const char *s)
Sends command string as a client command directly to server.
void trap_UpdateScreen (void)
trap_UpdateScreen updates the screen.
void trap_CM_LoadMap (const char *mapname)
int trap_CM_NumInlineModels (void)
clipHandle_t trap_CM_InlineModel (int index)
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
clipHandle_t trap_CM_TempCapsuleModel (const vec3_t mins, const vec3_t maxs)
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
void trap_CM_BoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
void trap_CM_CapsuleTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
void trap_CM_TransformedBoxTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
void trap_CM_TransformedCapsuleTrace (trace_t *results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
int trap_CM_MarkFragments (int numPoints, const vec3_t *points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t *fragmentBuffer)
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
void trap_S_ClearLoopingSounds (qboolean killall)
void trap_S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void trap_S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
void trap_S_StopLoopingSound (int entityNum)
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
sfxHandle_t trap_S_RegisterSound (const char *sample, qboolean compressed)
void trap_S_StartBackgroundTrack (const char *intro, const char *loop)
void trap_R_LoadWorldMap (const char *mapname)
qhandle_t trap_R_RegisterModel (const char *name)
qhandle_t trap_R_RegisterSkin (const char *name)
qhandle_t trap_R_RegisterShader (const char *name)
This function registers the name shader and gives it a unique qhandle_t.
qhandle_t trap_R_RegisterShaderNoMip (const char *name)
void trap_R_RegisterFont (const char *fontName, int pointSize, fontInfo_t *font)
void trap_R_ClearScene (void)
void trap_R_AddRefEntityToScene (const refEntity_t *re)
Physically added to the visuals in the game, after a new shader is set.
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts)
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t *verts, int num)
int trap_R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
This function will add a light to the game at org, which has a radius of intensity units, and the colour data which is shown in the variables r, g, and b.
void trap_R_AddAdditiveLightToScene (const vec3_t org, float intensity, float r, float g, float b)
void trap_R_RenderScene (const refdef_t *fd)
void trap_R_SetColor (const float *rgba)
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
int trap_R_LerpTag (orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName)
void trap_R_RemapShader (const char *oldShader, const char *newShader, const char *timeOffset)
void trap_GetGlconfig (glconfig_t *glconfig)
void trap_GetGameState (gameState_t *gamestate)
void trap_GetCurrentSnapshotNumber (int *snapshotNumber, int *serverTime)
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t *snapshot)
qboolean trap_GetServerCommand (int serverCommandNumber)
int trap_GetCurrentCmdNumber (void)
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t *ucmd)
void trap_SetUserCmdValue (int stateValue, float sensitivityScale)
void testPrintInt (char *string, int i)
void testPrintFloat (char *string, float f)
int trap_MemoryRemaining (void)
qboolean trap_Key_IsDown (int keynum)
Returns true is the indicated key is held down, returns false if not held down (released).
int trap_Key_GetCatcher (void)
Returns a bitmask representing active key catchers.
void trap_Key_SetCatcher (int catcher)
Redirects key events to different module(s).
int trap_Key_GetKey (const char *binding)
Returns keynum of the key that has the binding specified by binding.
int trap_PC_AddGlobalDefine (char *define)
int trap_PC_LoadSource (const char *filename)
int trap_PC_FreeSource (int handle)
int trap_PC_ReadToken (int handle, pc_token_t *pc_token)
int trap_PC_SourceFileAndLine (int handle, char *filename, int *line)
void trap_S_StopBackgroundTrack (void)
int trap_RealTime (qtime_t *qtime)
void trap_SnapVector (float *v)
int trap_CIN_PlayCinematic (const char *arg0, int xpos, int ypos, int width, int height, int bits)
This function loads up and begins playing an ROQ file at the coordinates given.
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it.
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it.
void trap_CIN_DrawCinematic (int handle)
This function renders the current frame of the cinematic to the screen with the current position coordinates.
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
qboolean trap_R_inPVS (const vec3_t p1, const vec3_t p2)
Function Documentation
dllEntry()
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
Definition at line 33 of file cg_syscalls.c.
 {
     syscall = syscallptr;
 }
Referenced by Sys_LoadGameDll().
intptr_t()
static intptr_t (QDECL * syscall) static
Referenced by asmcall(), Com_InitHunkMemory(), ConstOptimize(), CopyWinding(), DoSyscall(), EmitCallProcedure(), EmitPtr(), Hunk_AllocateTempMemory(), R_GetAnimTag(), R_Init(), RB_ReadPixels(), SV_DirectConnect(), Sys_ListFiles(), Sys_ListFilteredFiles(), Sys_LoadGameDll(), VM_AsmCall(), VM_Call(), VM_CallInterpreted(), VM_Compile(), VM_DllSyscall(), VM_Restart(), vmMain(), and Z_TagMallocDebug().
PASSFLOAT()
int PASSFLOAT (float x)
Definition at line 38 of file cg_syscalls.c.
 {
     floatint_t fi;
     fi.f = x;
     return fi.i;
 }
References floatint_t::f, and floatint_t::i.
Referenced by testPrintFloat(), trap_R_AddAdditiveLightToScene(), trap_R_AddLightToScene(), trap_R_DrawStretchPic(), trap_R_LerpTag(), and trap_SetUserCmdValue().
testPrintFloat()
void testPrintFloat (char * string, float f)
Definition at line 552 of file cg_syscalls.c.
 {
     syscall(CG_TESTPRINTFLOAT, string, PASSFLOAT(f));
 }
References CG_TESTPRINTFLOAT, and PASSFLOAT().
testPrintInt()
void testPrintInt (char * string, int i)
Definition at line 547 of file cg_syscalls.c.
 {
     syscall(CG_TESTPRINTINT, string, i);
 }
References CG_TESTPRINTINT.
trap_AddCommand()
void trap_AddCommand (const char * cmdName)
The string cmdName is added to a tab-completion list for the console.
Tab completion is case-insensitive, but the completed string is rewritten with the stored capitalization.
Commands added to the commands[] array are automatically addded for tab-completion by the function CG_InitConsoleCommands(), and, in fact, this is the only function that calls this trap in the baseq3 game source.
Parameters
cmdName Command name.
Definition at line 161 of file cg_syscalls.c.
 {
     syscall(CG_ADDCOMMAND, cmdName);
 }
References CG_ADDCOMMAND.
Referenced by CG_InitConsoleCommands().
trap_Argc()
int trap_Argc (void)
Definition at line 101 of file cg_syscalls.c.
 {
     return syscall(CG_ARGC);
 }
trap_Args()
void trap_Args (char * buffer, int bufferLength)
Definition at line 111 of file cg_syscalls.c.
 {
     syscall(CG_ARGS, buffer, bufferLength);
 }
References buffer, and CG_ARGS.
Referenced by CG_TellAttacker_f(), and CG_TellTarget_f().
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
Definition at line 106 of file cg_syscalls.c.
 {
     syscall(CG_ARGV, n, buffer, bufferLength);
 }
trap_CIN_DrawCinematic()
void trap_CIN_DrawCinematic (int handle)
This function renders the current frame of the cinematic to the screen with the current position coordinates.
Draws the current frame.
Parameters
handle A handle returned by a previous call to trap_CIN_PlayCinematic.
Definition at line 785 of file cg_syscalls.c.
 {
     syscall(CG_CIN_DRAWCINEMATIC, handle);
 }
trap_CIN_PlayCinematic()
int trap_CIN_PlayCinematic (const char * arg0, int xpos, int ypos, int width, int height, int bits)
This function loads up and begins playing an ROQ file at the coordinates given.
if the CIN_hold flag is specified, the ROQ is loaded in a paused state. The function returns a handle to the cinematic instance or zero on failure.
This returns a handle. arg0 is the name in the format "idlogo.roq", set arg1 to NULL, alteredstates to qfalse (do not alter gamestate)
Parameters
arg0 The name of the .RoQ file to load.
xpos The X coordinate on-screen for the left edge of the cinematic display.
ypos The Y coordinate on-screen for the top edge of the cinematic display.
width The screen width of the cinematic display.
height The screen height of the cinematic display.
bits Combinations of the following flags: CIN_system, CIN_loop, CIN_hold, CIN_silent, CIN_shader.
Returns
Definition at line 750 of file cg_syscalls.c.
 {
     return syscall(CG_CIN_PLAYCINEMATIC, arg0, xpos, ypos, width, height, bits);
 }
trap_CIN_RunCinematic()
e_status trap_CIN_RunCinematic (int handle)
Will run a frame of the cinematic but will not draw it.
Will return FMV_EOF if the end of the cinematic has been reached.
Parameters
handle A handle returned by a previous call to trap_CIN_PlayCinematic.
Returns
Definition at line 774 of file cg_syscalls.c.
 {
     return syscall(CG_CIN_RUNCINEMATIC, handle);
 }
trap_CIN_SetExtents()
void trap_CIN_SetExtents (int handle, int x, int y, int w, int h)
Allows you to resize the animation dynamically.
Parameters
handle A handle returned by a previous call to trap_CIN_PlayCinematic
x the new X coordinate on-screen of the left edge of the cinematic.
y the new Y coordinate on-screen of the top edge of the cinematic.
w the new width on-screen of the cinematic.
h the new height on-screen of the cinematic.
Definition at line 799 of file cg_syscalls.c.
 {
     syscall(CG_CIN_SETEXTENTS, handle, x, y, w, h);
 }
trap_CIN_StopCinematic()
e_status trap_CIN_StopCinematic (int handle)
Stops playing the cinematic and ends it.
Should always return FMV_EOF. cinematics must be stopped in reverse order of when they are started.
Parameters
handle The handle returned by a previous call to trap_CIN_PlayCinematic.
Returns
Definition at line 763 of file cg_syscalls.c.
 {
     return syscall(CG_CIN_STOPCINEMATIC, handle);
 }
trap_CM_BoxTrace()
void trap_CM_BoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
Definition at line 283 of file cg_syscalls.c.
 {
     syscall(CG_CM_BOXTRACE, results, start, end, mins, maxs, model, brushmask);
 }
References CG_CM_BOXTRACE.
Referenced by CG_Bullet(), CG_PlayerShadow(), CG_PlayerSplash(), CG_ShotgunPellet(), CG_TouchTriggerPrediction(), and CG_Trace().
trap_CM_CapsuleTrace()
void trap_CM_CapsuleTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask)
Definition at line 290 of file cg_syscalls.c.
 {
     syscall(CG_CM_CAPSULETRACE, results, start, end, mins, maxs, model, brushmask);
 }
References CG_CM_CAPSULETRACE.
trap_CM_InlineModel()
clipHandle_t trap_CM_InlineModel (int index)
Definition at line 258 of file cg_syscalls.c.
 {
     return syscall(CG_CM_INLINEMODEL, index);
 }
References CG_CM_INLINEMODEL.
Referenced by CG_ClipMoveToEntities(), CG_PointContents(), and CG_TouchTriggerPrediction().
trap_CM_LoadMap()
void trap_CM_LoadMap (const char * mapname)
Definition at line 248 of file cg_syscalls.c.
 {
     syscall(CG_CM_LOADMAP, mapname);
 }
References CG_CM_LOADMAP.
Referenced by CG_Init().
trap_CM_MarkFragments()
int trap_CM_MarkFragments (int numPoints, const vec3_t * points, const vec3_t projection, int maxPoints, vec3_t pointBuffer, int maxFragments, markFragment_t * fragmentBuffer)
Definition at line 313 of file cg_syscalls.c.
 {
     return syscall(CG_CM_MARKFRAGMENTS, numPoints, points, projection, maxPoints, pointBuffer, maxFragments, fragmentBuffer);
 }
References CG_CM_MARKFRAGMENTS.
Referenced by CG_ImpactMark().
trap_CM_NumInlineModels()
int trap_CM_NumInlineModels (void)
Definition at line 253 of file cg_syscalls.c.
 {
     return syscall(CG_CM_NUMINLINEMODELS);
 }
References CG_CM_NUMINLINEMODELS.
Referenced by CG_RegisterGraphics().
trap_CM_PointContents()
int trap_CM_PointContents (const vec3_t p, clipHandle_t model)
Definition at line 273 of file cg_syscalls.c.
 {
     return syscall(CG_CM_POINTCONTENTS, p, model);
 }
References CG_CM_POINTCONTENTS.
Referenced by CG_PointContents().
trap_CM_TempBoxModel()
clipHandle_t trap_CM_TempBoxModel (const vec3_t mins, const vec3_t maxs)
Definition at line 263 of file cg_syscalls.c.
 {
     return syscall(CG_CM_TEMPBOXMODEL, mins, maxs);
 }
References CG_CM_TEMPBOXMODEL.
Referenced by CG_ClipMoveToEntities().
trap_CM_TempCapsuleModel()
clipHandle_t trap_CM_TempCapsuleModel (const vec3_t mins, const vec3_t maxs)
Definition at line 268 of file cg_syscalls.c.
 {
     return syscall(CG_CM_TEMPCAPSULEMODEL, mins, maxs);
 }
References CG_CM_TEMPCAPSULEMODEL.
trap_CM_TransformedBoxTrace()
void trap_CM_TransformedBoxTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
Definition at line 297 of file cg_syscalls.c.
 {
     syscall(CG_CM_TRANSFORMEDBOXTRACE, results, start, end, mins, maxs, model, brushmask, origin, angles);
 }
References CG_CM_TRANSFORMEDBOXTRACE.
Referenced by CG_ClipMoveToEntities().
trap_CM_TransformedCapsuleTrace()
void trap_CM_TransformedCapsuleTrace (trace_t * results, const vec3_t start, const vec3_t end, const vec3_t mins, const vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles)
Definition at line 305 of file cg_syscalls.c.
 {
     syscall(CG_CM_TRANSFORMEDCAPSULETRACE, results, start, end, mins, maxs, model, brushmask, origin, angles);
 }
References CG_CM_TRANSFORMEDCAPSULETRACE.
trap_CM_TransformedPointContents()
int trap_CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
Definition at line 278 of file cg_syscalls.c.
 {
     return syscall(CG_CM_TRANSFORMEDPOINTCONTENTS, p, model, origin, angles);
 }
References CG_CM_TRANSFORMEDPOINTCONTENTS.
Referenced by CG_PointContents().
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * vmCvar, const char * varName, const char * defaultValue, int flags)
Definition at line 62 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_REGISTER, vmCvar, varName, defaultValue, flags);
 }
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
Definition at line 72 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_SET, var_name, value);
 }
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * vmCvar)
Definition at line 67 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_UPDATE, vmCvar);
 }
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
This is useful for obtaining cvar contents that are not bound, or cannot be bound, to a vmCvar_t variable in the mod code.
The terminating NULL is attached to the end of the copied string by this trap, guaranteeing buffer holds a null-terminated string. The total number of characters copied, including terminating NULL, fits within the size specified by bufsize, truncating the string if necessary.
A nonexistent cvar provides an empty string. An existing cvar with empty content also provides an empty string. Thus, this trap is not sufficient to determine if a cvar actually exists or not.
This trap does not create a new cvar; to create a new cvar during run-time, you can use trap_Cvar_Set or trap_SendConsoleCommand.
Parameters
var_name name of cvar (console variable).
buffer destination string buffer.
bufsize maximum limit of string buffer.
Definition at line 96 of file cg_syscalls.c.
 {
     syscall(CG_CVAR_VARIABLESTRINGBUFFER, var_name, buffer, bufsize);
 }
trap_Error()
void trap_Error (const char * fmt)
Definition at line 50 of file cg_syscalls.c.
 {
     syscall(CG_ERROR, fmt);
     // shut up GCC warning about returning functions, because we know better
     exit(1);
 }
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Definition at line 131 of file cg_syscalls.c.
 {
     syscall(CG_FS_FCLOSEFILE, f);
 }
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
Definition at line 116 of file cg_syscalls.c.
 {
     return syscall(CG_FS_FOPENFILE, qpath, f, mode);
 }
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
Definition at line 121 of file cg_syscalls.c.
 {
     syscall(CG_FS_READ, buffer, len, f);
 }
trap_FS_Seek()
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
Definition at line 136 of file cg_syscalls.c.
 {
     return syscall(CG_FS_SEEK, f, offset, origin);
 }
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
Definition at line 126 of file cg_syscalls.c.
 {
     syscall(CG_FS_WRITE, buffer, len, f);
 }
trap_GetCurrentCmdNumber()
int trap_GetCurrentCmdNumber (void)
Definition at line 532 of file cg_syscalls.c.
 {
     return syscall(CG_GETCURRENTCMDNUMBER);
 }
References CG_GETCURRENTCMDNUMBER.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
trap_GetCurrentSnapshotNumber()
void trap_GetCurrentSnapshotNumber (int * snapshotNumber, int * serverTime)
Definition at line 517 of file cg_syscalls.c.
 {
     syscall(CG_GETCURRENTSNAPSHOTNUMBER, snapshotNumber, serverTime);
 }
References CG_GETCURRENTSNAPSHOTNUMBER.
Referenced by CG_ProcessSnapshots().
trap_GetEntityToken()
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
Definition at line 821 of file cg_syscalls.c.
 {
     return syscall(CG_GET_ENTITY_TOKEN, buffer, bufferSize);
 }
trap_GetGameState()
void trap_GetGameState (gameState_t * gamestate)
Definition at line 512 of file cg_syscalls.c.
 {
     syscall(CG_GETGAMESTATE, gamestate);
 }
References CG_GETGAMESTATE.
Referenced by CG_ConfigStringModified(), and CG_Init().
trap_GetGlconfig()
void trap_GetGlconfig (glconfig_t * glconfig)
Definition at line 507 of file cg_syscalls.c.
 {
     syscall(CG_GETGLCONFIG, glconfig);
 }
trap_GetServerCommand()
qboolean trap_GetServerCommand (int serverCommandNumber)
Definition at line 527 of file cg_syscalls.c.
 {
     return syscall(CG_GETSERVERCOMMAND, serverCommandNumber);
 }
References CG_GETSERVERCOMMAND.
Referenced by CG_ExecuteNewServerCommands().
trap_GetSnapshot()
qboolean trap_GetSnapshot (int snapshotNumber, snapshot_t * snapshot)
Definition at line 522 of file cg_syscalls.c.
 {
     return syscall(CG_GETSNAPSHOT, snapshotNumber, snapshot);
 }
References CG_GETSNAPSHOT.
Referenced by CG_ReadNextSnapshot().
trap_GetUserCmd()
qboolean trap_GetUserCmd (int cmdNumber, usercmd_t * ucmd)
Definition at line 537 of file cg_syscalls.c.
 {
     return syscall(CG_GETUSERCMD, cmdNumber, ucmd);
 }
References CG_GETUSERCMD.
Referenced by CG_DrawDisconnect(), CG_InterpolatePlayerState(), and CG_PredictPlayerState().
trap_Key_GetCatcher()
int trap_Key_GetCatcher (void)
Returns a bitmask representing active key catchers.
Bitmask values are: KEYCATCH_CONSOLE KEYCATCH_UI KEYCATCH_MESSAGE KEYCATCH_CGAME
(see also trap_Key_SetCatcher())
To check if CGAME key-catching is active: if (trap_Key_GetCatcher() & KEYCATCH_UI) { //happy happy }
Returns
A bitmask representing active key catchers.
Definition at line 615 of file cg_syscalls.c.
 {
     return syscall(CG_KEY_GETCATCHER);
 }
trap_Key_GetKey()
int trap_Key_GetKey (const char * binding)
Returns keynum of the key that has the binding specified by binding.
Case-sensitive.
Unknown: what happens when many keys have this binding.
Parameters
binding command string presumably bound to a key.
Returns
keynum of the key that has the binding specified by binding. Case-sensitive.
Definition at line 690 of file cg_syscalls.c.
 {
     return syscall(CG_KEY_GETKEY, binding);
 }
References CG_KEY_GETKEY.
trap_Key_IsDown()
qboolean trap_Key_IsDown (int keynum)
Returns true is the indicated key is held down, returns false if not held down (released).
The values of keynum range from 0 to 255, inclusive. For the most part, a key's keynum corresponds to its character's ASCII value (e.g. the 'A' key is 65).
I have a list of keynames used by the bind command with their keynums which I may append at a later date. In the meantime, if you want to know them now, you can do this:
Create a keynums.cfg with a pattern like: bind 0x00 Key 0x00 bind 0x01 Key 0x01 ... bind 0xfe Key 0xfe bind 0xff Key 0xff (case matters for the hex values, and a scripting language to automate this really helps).
Back up your q3config.cfg, run Q3, "/exec keynums.cfg; bindlist; condump keynums.txt; quit".
In the file "keynums.txt" you should now have lines like: UPARROW "Key 0x84"
There's your keynum list.
(Generating keynums.cfg in GNU bash: for i in $(seq 0 255); do x=$(printf "%02x" $i); echo bind 0x$x Key 0x$x; done > keynums.cfg).
Parameters
keynum A key keynum.
Returns
Definition at line 592 of file cg_syscalls.c.
 {
     return syscall(CG_KEY_ISDOWN, keynum);
 }
trap_Key_SetCatcher()
void trap_Key_SetCatcher (int catcher)
Redirects key events to different module(s).
Normally, key events are interpreted by the engine, affected by the key bindings. This trap allows you redirect key events to other components.
Valid catchers are: KEYCATCH_CONSOLE: the console KEYCATCH_UI: the ui module KEYCATCH_MESSAGE: the little message editor thingy KEYCATCH_CGAME: the cgame module
These are bitmasked values, meaning you can combine them with the OR operator (|), as in (KEYCATCH_UI|KEYCATCH_CGAME), but I recommend against trying multiple catchers (it may get confusing).
As a mods programmer, you may be most interested in KEYCATCH_CGAME, and on this I will concentrate this entry.
— The Keyboard —
When key-catching is enabled (trap_Key_SetCatcher(KEYCATCH_CGAME);), upon a change in key state (gets pressed or gets released), the engine calls the vmMain() function in cg_main.c with the following parameters: command = CG_KEY_EVENT arg0 = keynum arg1 = 1 if pressed, 0 if released.
In baseq3 game source, this event is already handled and delegated to CG_KeyEvent(), which is empty.
The values for keynum are the same as for trap_Key_IsDown().
Key catching is disabled by calling with a parameter of 0 (as in, no catchers). Key catching is also terminated if the user presses the ESC key, which means you won't receive events on the ESC key.
— The Mouse —
When key-catching is enabled, mouse movement is also redirected to the specified module. When the engine detects mouse movement, it calls vmMain() with the following parameters: command = CG_MOUSE_EVENT arg0 = relative X position arg1 = relative Y position
The game source for baseq3 delegates this event to CG_MouseEvent().
Pointer Device Movement - Reported Value: Left - Negative X Right - Positive X Up - Negative Y Down - Positive Y
The engine only reports mouse movement – if the mouse doesn't move, there is no mouse event. The engine reports mouse buttons and wheels (if any) as key events, for binding purposes.
Cvars do not influence the reported values.
Parameters
catcher Key catchers bitmask.
Definition at line 677 of file cg_syscalls.c.
 {
     syscall(CG_KEY_SETCATCHER, catcher);
 }
trap_MemoryRemaining()
int trap_MemoryRemaining (void)
Definition at line 557 of file cg_syscalls.c.
 {
     return syscall(CG_MEMORY_REMAINING);
 }
trap_Milliseconds()
int trap_Milliseconds (void)
Definition at line 57 of file cg_syscalls.c.
 {
     return syscall(CG_MILLISECONDS);
 }
trap_PC_AddGlobalDefine()
int trap_PC_AddGlobalDefine (char * define)
Definition at line 695 of file cg_syscalls.c.
 {
     return syscall(CG_PC_ADD_GLOBAL_DEFINE, define);
 }
trap_PC_FreeSource()
int trap_PC_FreeSource (int handle)
Definition at line 705 of file cg_syscalls.c.
 {
     return syscall(CG_PC_FREE_SOURCE, handle);
 }
Referenced by UI_LoadMenus(), and UI_ParseMenu().
trap_PC_LoadSource()
int trap_PC_LoadSource (const char * filename)
Definition at line 700 of file cg_syscalls.c.
 {
     return syscall(CG_PC_LOAD_SOURCE, filename);
 }
Referenced by UI_LoadMenus(), and UI_ParseMenu().
trap_PC_ReadToken()
int trap_PC_ReadToken (int handle, pc_token_t * pc_token)
Definition at line 710 of file cg_syscalls.c.
 {
     return syscall(CG_PC_READ_TOKEN, handle, pc_token);
 }
Referenced by Asset_Parse(), Item_Parse(), ItemParse_cvarFloatList(), ItemParse_cvarStrList(), Load_Menu(), Menu_Parse(), PC_Float_Parse(), PC_Int_Parse(), PC_Script_Parse(), PC_String_Parse(), UI_LoadMenus(), and UI_ParseMenu().
trap_PC_SourceFileAndLine()
int trap_PC_SourceFileAndLine (int handle, char * filename, int * line)
Definition at line 715 of file cg_syscalls.c.
 {
     return syscall(CG_PC_SOURCE_FILE_AND_LINE, handle, filename, line);
 }
Referenced by __attribute__().
trap_Print()
void trap_Print (const char * fmt)
Definition at line 45 of file cg_syscalls.c.
 {
     syscall(CG_PRINT, fmt);
 }
trap_R_AddAdditiveLightToScene()
void trap_R_AddAdditiveLightToScene (const vec3_t org, float intensity, float r, float g, float b)
Definition at line 470 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDADDITIVELIGHTTOSCENE, org, PASSFLOAT(intensity), PASSFLOAT(r), PASSFLOAT(g), PASSFLOAT(b));
 }
References CG_R_ADDADDITIVELIGHTTOSCENE, and PASSFLOAT().
trap_R_AddLightToScene()
void trap_R_AddLightToScene (const vec3_t org, float intensity, float r, float g, float b)
This function will add a light to the game at org, which has a radius of intensity units, and the colour data which is shown in the variables r, g, and b.
The highest number for an RGB index is 255, but in Quake 3 the colour's index is divided by 255 to give a normalized value.
Say I want to make a purple light. The colour data for purple in RGB is 255,0,255. So the normalized values for this colour are:
255/255 = 1.0 0/255 = 0.0 255/255 = 1.0
o to add a purple light at the vector x, and radius 2.4 I would write:
trap_R_AddLightToScene(x, 2.4, 1.0, 0.0, 1.0);.
Parameters
org origin of the light - where the light will be.
intensity not the exact intensity of the light, but the radius of the light - the light is a sphere-like object and points within that object are lighted up, and the closer something is to the origin of the light (org) the closer the light will be to the actual colour data of the light.
r this is the colour data of the light (normalized, so the highest value, 255, is 1.0) - r is the amount of red light.
g green light.
b blue light.
Definition at line 465 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDLIGHTTOSCENE, org, PASSFLOAT(intensity), PASSFLOAT(r), PASSFLOAT(g), PASSFLOAT(b));
 }
trap_R_AddPolysToScene()
void trap_R_AddPolysToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts, int num)
Definition at line 429 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDPOLYSTOSCENE, hShader, numVerts, verts, num);
 }
References CG_R_ADDPOLYSTOSCENE.
trap_R_AddPolyToScene()
void trap_R_AddPolyToScene (qhandle_t hShader, int numVerts, const polyVert_t * verts)
Definition at line 424 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDPOLYTOSCENE, hShader, numVerts, verts);
 }
trap_R_AddRefEntityToScene()
void trap_R_AddRefEntityToScene (const refEntity_t * re)
Physically added to the visuals in the game, after a new shader is set.
Parameters
[in] Updated entity.
Definition at line 419 of file cg_syscalls.c.
 {
     syscall(CG_R_ADDREFENTITYTOSCENE, re);
 }
trap_R_ClearScene()
void trap_R_ClearScene (void)
Definition at line 409 of file cg_syscalls.c.
 {
     syscall(CG_R_CLEARSCENE);
 }
trap_R_DrawStretchPic()
void trap_R_DrawStretchPic (float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader)
Definition at line 485 of file cg_syscalls.c.
 {
     syscall(CG_R_DRAWSTRETCHPIC, PASSFLOAT(x), PASSFLOAT(y), PASSFLOAT(w), PASSFLOAT(h), PASSFLOAT(s1), PASSFLOAT(t1), PASSFLOAT(s2), PASSFLOAT(t2), hShader);
 }
trap_R_inPVS()
qboolean trap_R_inPVS (const vec3_t p1, const vec3_t p2)
Definition at line 826 of file cg_syscalls.c.
 {
     return syscall(CG_R_INPVS, p1, p2);
 }
References CG_R_INPVS.
trap_R_LerpTag()
int trap_R_LerpTag (orientation_t * tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char * tagName)
Definition at line 496 of file cg_syscalls.c.
 {
     return syscall(CG_R_LERPTAG, tag, mod, startFrame, endFrame, PASSFLOAT(frac), tagName);
 }
References CG_R_LERPTAG, and PASSFLOAT().
Referenced by CG_AddPlayerWeapon(), CG_LoadClientInfo(), CG_PositionEntityOnTag(), and CG_PositionRotatedEntityOnTag().
trap_R_LightForPoint()
int trap_R_LightForPoint (vec3_t point, vec3_t ambientLight, vec3_t directedLight, vec3_t lightDir)
Definition at line 434 of file cg_syscalls.c.
 {
     return syscall(CG_R_LIGHTFORPOINT, point, ambientLight, directedLight, lightDir);
 }
References CG_R_LIGHTFORPOINT.
Referenced by CG_LightVerts().
trap_R_LoadWorldMap()
void trap_R_LoadWorldMap (const char * mapname)
Definition at line 373 of file cg_syscalls.c.
 {
     syscall(CG_R_LOADWORLDMAP, mapname);
 }
References CG_R_LOADWORLDMAP.
Referenced by CG_RegisterGraphics().
trap_R_ModelBounds()
void trap_R_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
Definition at line 491 of file cg_syscalls.c.
 {
     syscall(CG_R_MODELBOUNDS, model, mins, maxs);
 }
trap_R_RegisterFont()
void trap_R_RegisterFont (const char * fontName, int pointSize, fontInfo_t * font)
Definition at line 404 of file cg_syscalls.c.
 {
     syscall(CG_R_REGISTERFONT, fontName, pointSize, font);
 }
trap_R_RegisterModel()
qhandle_t trap_R_RegisterModel (const char * name)
Definition at line 378 of file cg_syscalls.c.
 {
     return syscall(CG_R_REGISTERMODEL, name);
 }
trap_R_RegisterShader()
qhandle_t trap_R_RegisterShader (const char * name)
This function registers the name shader and gives it a unique qhandle_t.
Parameters
name pointer to the name of the shader (?).
Returns
Definition at line 394 of file cg_syscalls.c.
 {
     return syscall(CG_R_REGISTERSHADER, name);
 }
References CG_R_REGISTERSHADER.
Referenced by CG_ClearParticles(), CG_DrawAreaPowerUp(), CG_DrawDisconnect(), CG_DrawInformation(), CG_DrawNewTeamInfo(), CG_DrawPowerups(), CG_DrawSelectedPlayerPowerup(), CG_DrawTeamOverlay(), CG_Init(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), and CG_RegisterWeapon().
trap_R_RegisterShaderNoMip()
qhandle_t trap_R_RegisterShaderNoMip (const char * name)
Definition at line 399 of file cg_syscalls.c.
 {
     return syscall(CG_R_REGISTERSHADERNOMIP, name);
 }
trap_R_RegisterSkin()
qhandle_t trap_R_RegisterSkin (const char * name)
Definition at line 383 of file cg_syscalls.c.
 {
     return syscall(CG_R_REGISTERSKIN, name);
 }
trap_R_RemapShader()
void trap_R_RemapShader (const char * oldShader, const char * newShader, const char * timeOffset)
Definition at line 502 of file cg_syscalls.c.
 {
     syscall(CG_R_REMAP_SHADER, oldShader, newShader, timeOffset);
 }
trap_R_RenderScene()
void trap_R_RenderScene (const refdef_t * fd)
Definition at line 475 of file cg_syscalls.c.
 {
     syscall(CG_R_RENDERSCENE, fd);
 }
trap_R_SetColor()
void trap_R_SetColor (const float * rgba)
Definition at line 480 of file cg_syscalls.c.
 {
     syscall(CG_R_SETCOLOR, rgba);
 }
trap_RealTime()
int trap_RealTime (qtime_t * qtime)
Definition at line 725 of file cg_syscalls.c.
 {
     return syscall(CG_REAL_TIME, qtime);
 }
trap_RemoveCommand()
void trap_RemoveCommand (const char * cmdName)
Although this trap is not actually used anywhere in baseq3 game source, a reasonable assumption, based on function name and parameters, is that this trap removes a command name from the list of command completions.
That is, the inverse of trap_AddCommand().
Unknown: case sensitivity (i.e. if capitalization matters for string matching).
Parameters
cmdName command name.
Definition at line 176 of file cg_syscalls.c.
 {
     syscall(CG_REMOVECOMMAND, cmdName);
 }
References CG_REMOVECOMMAND.
trap_S_AddLoopingSound()
void trap_S_AddLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Definition at line 336 of file cg_syscalls.c.
 {
     syscall(CG_S_ADDLOOPINGSOUND, entityNum, origin, velocity, sfx);
 }
References CG_S_ADDLOOPINGSOUND.
Referenced by CG_AddPlayerWeapon(), CG_EntityEffects(), CG_Grapple(), CG_Item(), CG_Missile(), and CG_PlayerPowerups().
trap_S_AddRealLoopingSound()
void trap_S_AddRealLoopingSound (int entityNum, const vec3_t origin, const vec3_t velocity, sfxHandle_t sfx)
Definition at line 342 of file cg_syscalls.c.
 {
     syscall(CG_S_ADDREALLOOPINGSOUND, entityNum, origin, velocity, sfx);
 }
References CG_S_ADDREALLOOPINGSOUND.
Referenced by CG_EntityEffects().
trap_S_ClearLoopingSounds()
void trap_S_ClearLoopingSounds (qboolean killall)
Definition at line 331 of file cg_syscalls.c.
 {
     syscall(CG_S_CLEARLOOPINGSOUNDS, killall);
 }
References CG_S_CLEARLOOPINGSOUNDS.
Referenced by CG_DrawActiveFrame(), CG_Init(), and CG_MapRestart().
trap_S_RegisterSound()
sfxHandle_t trap_S_RegisterSound (const char * sample, qboolean compressed)
Definition at line 363 of file cg_syscalls.c.
 {
     return syscall(CG_S_REGISTERSOUND, sample, compressed);
 }
trap_S_Respatialize()
void trap_S_Respatialize (int entityNum, const vec3_t origin, vec3_t axis[3], int inwater)
Definition at line 358 of file cg_syscalls.c.
 {
     syscall(CG_S_RESPATIALIZE, entityNum, origin, axis, inwater);
 }
References CG_S_RESPATIALIZE.
Referenced by CG_DrawActiveFrame().
trap_S_StartBackgroundTrack()
void trap_S_StartBackgroundTrack (const char * intro, const char * loop)
Definition at line 368 of file cg_syscalls.c.
 {
     syscall(CG_S_STARTBACKGROUNDTRACK, intro, loop);
 }
trap_S_StartLocalSound()
void trap_S_StartLocalSound (sfxHandle_t sfx, int channelNum)
Definition at line 326 of file cg_syscalls.c.
 {
     syscall(CG_S_STARTLOCALSOUND, sfx, channelNum);
 }
trap_S_StartSound()
void trap_S_StartSound (vec3_t origin, int entityNum, int entchannel, sfxHandle_t sfx)
Definition at line 321 of file cg_syscalls.c.
 {
     syscall(CG_S_STARTSOUND, origin, entityNum, entchannel, sfx);
 }
References CG_S_STARTSOUND.
Referenced by CG_EntityEvent(), CG_FireWeapon(), CG_FragmentBounceSound(), CG_MachinegunSpinAngle(), CG_MissileHitWall(), CG_PainEvent(), CG_PowerupTimerSounds(), CG_Speaker(), CG_TeamBase(), CG_Tracer(), and CG_UseItem().
trap_S_StopBackgroundTrack()
void trap_S_StopBackgroundTrack (void)
Definition at line 720 of file cg_syscalls.c.
 {
     syscall(CG_S_STOPBACKGROUNDTRACK);
 }
trap_S_StopLoopingSound()
void trap_S_StopLoopingSound (int entityNum)
Definition at line 348 of file cg_syscalls.c.
 {
     syscall(CG_S_STOPLOOPINGSOUND, entityNum);
 }
References CG_S_STOPLOOPINGSOUND.
Referenced by CG_EntityEvent().
trap_S_UpdateEntityPosition()
void trap_S_UpdateEntityPosition (int entityNum, const vec3_t origin)
Definition at line 353 of file cg_syscalls.c.
 {
     syscall(CG_S_UPDATEENTITYPOSITION, entityNum, origin);
 }
References CG_S_UPDATEENTITYPOSITION.
Referenced by CG_SetEntitySoundPosition().
trap_SendClientCommand()
void trap_SendClientCommand (const char * s)
Sends command string as a client command directly to server.
In contrast, trap_SendConsoleCommand() sends the string to the local console first, and, if not recognized there, sends to the server as a client command.
This trap makes no distinction among EXEC_NOW, EXEC_INSERT, or EXEC_APPEND as with trap_SendConsoleCommand(), since the command is sent "somewhere else".
The set of "client commands" is separate from "console commands", so that a misbehaving client cannot kill a server by attempting to send "quit" as a command.
In baseq3, the common SendClientCommand commands are "score" (to obtain information for scoreboard), "tell" (chat, commands), and "vtell" (Q3TA chat with WAV playback).
Beware of the server cvar sv_floodProtect. With it set to 1 (the default), commands sent to the server using SendClientCommand in rapid succession will be silently dropped by the server. In the case where some critical client->server communication is implemented using SendClientCommand, it is important that sv_floodProtect is off.
Note that chat flood protection can be fairly trivially implemented in the game module.
Parameters
s Command string.
Definition at line 205 of file cg_syscalls.c.
 {
     syscall(CG_SENDCLIENTCOMMAND, s);
 }
References CG_SENDCLIENTCOMMAND, and s.
Referenced by CG_DrawTourneyScoreboard(), CG_ScoresDown_f(), CG_TargetCommand_f(), CG_TellAttacker_f(), and CG_TellTarget_f().
trap_SendConsoleCommand()
void trap_SendConsoleCommand (const char * text)
The string provided by text is run as if typed as a command into the console.
A leading slash (/) is not required.
Parameters
text The command to be executed.
Definition at line 146 of file cg_syscalls.c.
 {
     syscall(CG_SENDCONSOLECOMMAND, text);
 }
References CG_SENDCONSOLECOMMAND.
Referenced by BotInterbreeding(), CG_CheckOrderPending(), CG_MapRestart(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientDisconnect(), ClientThink_real(), Cmd_CallVote_f(), ConsoleCommand(), ExitLevel(), G_AddRandomBot(), G_RankRunFrame(), G_RemoveRandomBot(), G_SpawnBots(), LogExit(), PlayerIntroSound(), and UpdateTournamentInfo().
trap_SetUserCmdValue()
void trap_SetUserCmdValue (int stateValue, float sensitivityScale)
Definition at line 542 of file cg_syscalls.c.
 {
     syscall(CG_SETUSERCMDVALUE, stateValue, PASSFLOAT(sensitivityScale));
 }
References CG_SETUSERCMDVALUE, and PASSFLOAT().
Referenced by CG_DrawActiveFrame().
trap_SnapVector()
void trap_SnapVector (float * v)
Definition at line 730 of file cg_syscalls.c.
 {
     syscall(CG_SNAPVECTOR, v);
 }
trap_UpdateScreen()
void trap_UpdateScreen (void)
trap_UpdateScreen updates the screen.
cg_local.h says: // force a screen update, only used during gamestate load void trap_UpdateScreen(void);
the Trap_UpdateScreen itself appears to be: cg_syscalls.c void trap_UpdateScreen(void) { syscall(CG_UPDATESCREEN); }
This is also called by: UI_Atoms.C
void UI_UpdateScreen(void) { trap_UpdateScreen(); }
it is also called by: ui_local.h void trap_R_DrawStretchPic(float x, float y, float w, float h, float s1, float t1, float s2, float t2, qhandle_t hShader); void trap_UpdateScreen(void); int trap_CM_LerpTag(orientation_t *tag, clipHandle_t mod, int startFrame, int endFrame, float frac, const char *tagName);
The locations of the calls and the remarks placed around it imply that this trap is ONLY for updating the screen during connection to local or remote host.
(eg: Loading....shotgun ; Loading.... Gauntlet ect... during the load of a map.)
Definition at line 243 of file cg_syscalls.c.
 {
     syscall(CG_UPDATESCREEN);
 }