ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_cluster.c File Reference
be_aas_cluster.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_log.h"
#include "l_libvar.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_aas_def.h"
#include "be_aas_cluster.h"
Macros
#define AAS_MAX_PORTALS 65536
#define AAS_MAX_PORTALINDEXSIZE 65536
#define AAS_MAX_CLUSTERS 65536
#define MAX_PORTALAREAS 1024
Functions
void AAS_RemoveClusterAreas (void)
void AAS_ClearCluster (int clusternum)
void AAS_RemovePortalsClusterReference (int clusternum)
int AAS_UpdatePortal (int areanum, int clusternum)
int AAS_FloodClusterAreas_r (int areanum, int clusternum)
int AAS_FloodClusterAreasUsingReachabilities (int clusternum)
void AAS_NumberClusterPortals (int clusternum)
void AAS_NumberClusterAreas (int clusternum)
int AAS_FindClusters (void)
void AAS_CreatePortals (void)
void AAS_ConnectedAreas_r (int *areanums, int numareas, int *connectedareas, int curarea)
qboolean AAS_ConnectedAreas (int *areanums, int numareas)
int AAS_GetAdjacentAreasWithLessPresenceTypes_r (int *areanums, int numareas, int curareanum)
int AAS_CheckAreaForPossiblePortals (int areanum)
void AAS_FindPossiblePortals (void)
void AAS_RemoveAllPortals (void)
int AAS_TestPortals (void)
void AAS_CountForcedClusterPortals (void)
void AAS_CreateViewPortals (void)
void AAS_SetViewPortalsAsClusterPortals (void)
void AAS_InitClustering (void)
Variables
botlib_import_t botimport
int nofaceflood = qtrue
Macro Definition Documentation
AAS_MAX_CLUSTERS
#define AAS_MAX_CLUSTERS 65536
Definition at line 51 of file be_aas_cluster.c.
AAS_MAX_PORTALINDEXSIZE
#define AAS_MAX_PORTALINDEXSIZE 65536
Definition at line 50 of file be_aas_cluster.c.
AAS_MAX_PORTALS
#define AAS_MAX_PORTALS 65536
Definition at line 49 of file be_aas_cluster.c.
MAX_PORTALAREAS
#define MAX_PORTALAREAS 1024
Definition at line 53 of file be_aas_cluster.c.
Function Documentation
AAS_CheckAreaForPossiblePortals()
int AAS_CheckAreaForPossiblePortals (int areanum)
Definition at line 794 of file be_aas_cluster.c.
 {
     int i, j, k, fen, ben, frontedgenum, backedgenum, facenum;
     int areanums[MAX_PORTALAREAS], numareas, otherareanum;
     int numareafrontfaces[MAX_PORTALAREAS], numareabackfaces[MAX_PORTALAREAS];
     int frontfacenums[MAX_PORTALAREAS], backfacenums[MAX_PORTALAREAS];
     int numfrontfaces, numbackfaces;
     int frontareanums[MAX_PORTALAREAS], backareanums[MAX_PORTALAREAS];
     int numfrontareas, numbackareas;
     int frontplanenum, backplanenum, faceplanenum;
     aas_area_t *area;
     aas_face_t *frontface, *backface, *face;
     //if it isn't already a portal
     if (aasworld.areasettings[areanum].contents & AREACONTENTS_CLUSTERPORTAL) return 0;
     //it must be a grounded area
     if (!(aasworld.areasettings[areanum].areaflags & AREA_GROUNDED)) return 0;
     //
     Com_Memset(numareafrontfaces, 0, sizeof(numareafrontfaces));
     Com_Memset(numareabackfaces, 0, sizeof(numareabackfaces));
     numfrontfaces = numbackfaces = 0;
     numfrontareas = numbackareas = 0;
     frontplanenum = backplanenum = -1;
     //add any adjacent areas with less presence types
     numareas = AAS_GetAdjacentAreasWithLessPresenceTypes_r(areanums, 0, areanum);
     //
     for (i = 0; i < numareas; i++)
     {
         area = &aasworld.areas[areanums[i]];
         for (j = 0; j < area->numfaces; j++)
         {
             facenum = abs(aasworld.faceindex[area->firstface + j]);
             face = &aasworld.faces[facenum];
             //if the face is solid
             if (face->faceflags & FACE_SOLID) continue;
             //check if the face is shared with one of the other areas
             for (k = 0; k < numareas; k++)
             {
                 if (k == i) continue;
                 if (face->frontarea == areanums[k] || face->backarea == areanums[k]) break;
             } //end for
             //if the face is shared
             if (k != numareas) continue;
             //the number of the area at the other side of the face
             if (face->frontarea == areanums[i]) otherareanum = face->backarea;
             else otherareanum = face->frontarea;
             //if the other area already is a cluter portal
             if (aasworld.areasettings[otherareanum].contents & AREACONTENTS_CLUSTERPORTAL) return 0;
             //number of the plane of the area
             faceplanenum = face->planenum & ~1;
             //
             if (frontplanenum < 0 || faceplanenum == frontplanenum)
             {
                 frontplanenum = faceplanenum;
                 frontfacenums[numfrontfaces++] = facenum;
                 for (k = 0; k < numfrontareas; k++)
                 {
                     if (frontareanums[k] == otherareanum) break;
                 } //end for
                 if (k == numfrontareas) frontareanums[numfrontareas++] = otherareanum;
                 numareafrontfaces[i]++;
             } //end if
             else if (backplanenum < 0 || faceplanenum == backplanenum)
             {
                 backplanenum = faceplanenum;
                 backfacenums[numbackfaces++] = facenum;
                 for (k = 0; k < numbackareas; k++)
                 {
                     if (backareanums[k] == otherareanum) break;
                 } //end for
                 if (k == numbackareas) backareanums[numbackareas++] = otherareanum;
                 numareabackfaces[i]++;
             } //end else
             else
             {
                 return 0;
             } //end else
         } //end for
     } //end for
     //every area should have at least one front face and one back face
     for (i = 0; i < numareas; i++)
     {
         if (!numareafrontfaces[i] || !numareabackfaces[i]) return 0;
     } //end for
     //the front areas should all be connected
     if (!AAS_ConnectedAreas(frontareanums, numfrontareas)) return 0;
     //the back areas should all be connected
     if (!AAS_ConnectedAreas(backareanums, numbackareas)) return 0;
     //none of the front faces should have a shared edge with a back face
     for (i = 0; i < numfrontfaces; i++)
     {
         frontface = &aasworld.faces[frontfacenums[i]];
         for (fen = 0; fen < frontface->numedges; fen++)
         {
             frontedgenum = abs(aasworld.edgeindex[frontface->firstedge + fen]);
             for (j = 0; j < numbackfaces; j++)
             {
                 backface = &aasworld.faces[backfacenums[j]];
                 for (ben = 0; ben < backface->numedges; ben++)
                 {
                     backedgenum = abs(aasworld.edgeindex[backface->firstedge + ben]);
                     if (frontedgenum == backedgenum) break;
                 } //end for
                 if (ben != backface->numedges) break;
             } //end for
             if (j != numbackfaces) break;
         } //end for
         if (fen != frontface->numedges) break;
     } //end for
     if (i != numfrontfaces) return 0;
     //set the cluster portal contents
     for (i = 0; i < numareas; i++)
     {
         aasworld.areasettings[areanums[i]].contents |= AREACONTENTS_CLUSTERPORTAL;
         //this area can be used as a route portal
         aasworld.areasettings[areanums[i]].contents |= AREACONTENTS_ROUTEPORTAL;
         Log_Write("possible portal: %d\r\n", areanums[i]);
     } //end for
     //
     return numareas;
 } //end of the function AAS_CheckAreaForPossiblePortals
References AAS_ConnectedAreas(), AAS_GetAdjacentAreasWithLessPresenceTypes_r(), aasworld, AREA_GROUNDED, AREACONTENTS_CLUSTERPORTAL, AREACONTENTS_ROUTEPORTAL, aas_areasettings_s::areaflags, aas_s::areas, aas_s::areasettings, aas_face_s::backarea, Com_Memset, aas_areasettings_s::contents, aas_s::edgeindex, FACE_SOLID, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_face_s::firstedge, aas_area_s::firstface, aas_face_s::frontarea, Log_Write(), MAX_PORTALAREAS, aas_face_s::numedges, aas_area_s::numfaces, and aas_face_s::planenum.
Referenced by AAS_FindPossiblePortals().
AAS_ClearCluster()
void AAS_ClearCluster (int clusternum)
Definition at line 79 of file be_aas_cluster.c.
 {
     int i;
     for (i = 1; i < aasworld.numareas; i++)
     {
         if (aasworld.areasettings[i].cluster == clusternum)
         {
             aasworld.areasettings[i].cluster = 0;
         } //end if
     } //end for
 } //end of the function AAS_ClearCluster
References aasworld, aas_s::areasettings, aas_areasettings_s::cluster, and aas_s::numareas.
AAS_ConnectedAreas()
qboolean AAS_ConnectedAreas (int * areanums, int numareas)
Definition at line 724 of file be_aas_cluster.c.
 {
     int connectedareas[MAX_PORTALAREAS], i;
     Com_Memset(connectedareas, 0, sizeof(connectedareas));
     if (numareas < 1) return qfalse;
     if (numareas == 1) return qtrue;
     AAS_ConnectedAreas_r(areanums, numareas, connectedareas, 0);
     for (i = 0; i < numareas; i++)
     {
         if (!connectedareas[i]) return qfalse;
     } //end for
     return qtrue;
 } //end of the function AAS_ConnectedAreas
References AAS_ConnectedAreas_r(), Com_Memset, MAX_PORTALAREAS, qfalse, and qtrue.
Referenced by AAS_CheckAreaForPossiblePortals().
AAS_ConnectedAreas_r()
void AAS_ConnectedAreas_r (int * areanums, int numareas, int * connectedareas, int curarea)
Definition at line 688 of file be_aas_cluster.c.
 {
     int i, j, otherareanum, facenum;
     aas_area_t *area;
     aas_face_t *face;
     connectedareas[curarea] = qtrue;
     area = &aasworld.areas[areanums[curarea]];
     for (i = 0; i < area->numfaces; i++)
     {
         facenum = abs(aasworld.faceindex[area->firstface + i]);
         face = &aasworld.faces[facenum];
         //if the face is solid
         if (face->faceflags & FACE_SOLID) continue;
         //get the area at the other side of the face
         if (face->frontarea != areanums[curarea]) otherareanum = face->frontarea;
         else otherareanum = face->backarea;
         //check if the face is leading to one of the other areas
         for (j = 0; j < numareas; j++)
         {
             if (areanums[j] == otherareanum) break;
         } //end for
         //if the face isn't leading to one of the other areas
         if (j == numareas) continue;
         //if the other area is already connected
         if (connectedareas[j]) continue;
         //recursively proceed with the other area
         AAS_ConnectedAreas_r(areanums, numareas, connectedareas, j);
     } //end for
 } //end of the function AAS_ConnectedAreas_r
References aasworld, aas_s::areas, aas_face_s::backarea, FACE_SOLID, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, aas_face_s::frontarea, aas_area_s::numfaces, and qtrue.
Referenced by AAS_ConnectedAreas().
AAS_CountForcedClusterPortals()
void AAS_CountForcedClusterPortals (void)
Definition at line 1402 of file be_aas_cluster.c.
 {
     int num, i;
     num = 0;
     for (i = 1; i < aasworld.numareas; i++)
     {
         if (aasworld.areasettings[i].contents & AREACONTENTS_CLUSTERPORTAL)
         {
             Log_Write("area %d is a forced portal area\r\n", i);
             num++;
         } //end if
     } //end for
     botimport.Print(PRT_MESSAGE, "%6d forced portal areas\n", num);
 } //end of the function AAS_CountForcedClusterPortals
References aasworld, AREACONTENTS_CLUSTERPORTAL, aas_s::areasettings, botimport, aas_areasettings_s::contents, Log_Write(), aas_s::numareas, and PRT_MESSAGE.
Referenced by AAS_InitClustering().
AAS_CreatePortals()
void AAS_CreatePortals (void)
Definition at line 440 of file be_aas_cluster.c.
 {
     int i;
     aas_portal_t *portal;
     for (i = 1; i < aasworld.numareas; i++)
     {
         //if the area is a cluster portal
         if (aasworld.areasettings[i].contents & AREACONTENTS_CLUSTERPORTAL)
         {
             if (aasworld.numportals >= AAS_MAX_PORTALS)
             {
                 AAS_Error("AAS_MAX_PORTALS\n");
                 return;
             } //end if
             portal = &aasworld.portals[aasworld.numportals];
             portal->areanum = i;
             portal->frontcluster = 0;
             portal->backcluster = 0;
             aasworld.numportals++;
         } //end if
     } //end for
 } //end of the function AAS_CreatePortals
References AAS_Error(), AAS_MAX_PORTALS, aasworld, AREACONTENTS_CLUSTERPORTAL, aas_portal_s::areanum, aas_s::areasettings, aas_portal_s::backcluster, aas_areasettings_s::contents, aas_portal_s::frontcluster, aas_s::numareas, aas_s::numportals, and aas_s::portals.
Referenced by AAS_InitClustering().
AAS_CreateViewPortals()
void AAS_CreateViewPortals (void)
Definition at line 1423 of file be_aas_cluster.c.
 {
     int i;
     for (i = 1; i < aasworld.numareas; i++)
     {
         if (aasworld.areasettings[i].contents & AREACONTENTS_CLUSTERPORTAL)
         {
             aasworld.areasettings[i].contents |= AREACONTENTS_VIEWPORTAL;
         } //end if
     } //end for
 } //end of the function AAS_CreateViewPortals
References aasworld, AREACONTENTS_CLUSTERPORTAL, AREACONTENTS_VIEWPORTAL, aas_s::areasettings, aas_areasettings_s::contents, and aas_s::numareas.
Referenced by AAS_InitClustering().
AAS_FindClusters()
int AAS_FindClusters (void)
Definition at line 390 of file be_aas_cluster.c.
 {
     int i;
     aas_cluster_t *cluster;
     AAS_RemoveClusterAreas();
     //
     for (i = 1; i < aasworld.numareas; i++)
     {
         //if the area is already part of a cluster
         if (aasworld.areasettings[i].cluster)
             continue;
         // if not flooding through faces only use areas that have reachabilities
         if (nofaceflood)
         {
             if (!aasworld.areasettings[i].numreachableareas)
                 continue;
         } //end if
         //if the area is a cluster portal
         if (aasworld.areasettings[i].contents & AREACONTENTS_CLUSTERPORTAL)
             continue;
         if (aasworld.numclusters >= AAS_MAX_CLUSTERS)
         {
             AAS_Error("AAS_MAX_CLUSTERS\n");
             return qfalse;
         } //end if
         cluster = &aasworld.clusters[aasworld.numclusters];
         cluster->numareas = 0;
         cluster->numreachabilityareas = 0;
         cluster->firstportal = aasworld.portalindexsize;
         cluster->numportals = 0;
         //flood the areas in this cluster
         if (!AAS_FloodClusterAreas_r(i, aasworld.numclusters))
             return qfalse;
         if (!AAS_FloodClusterAreasUsingReachabilities(aasworld.numclusters))
             return qfalse;
         //number the cluster areas
         //AAS_NumberClusterPortals(aasworld.numclusters);
         AAS_NumberClusterAreas(aasworld.numclusters);
         //Log_Write("cluster %d has %d areas\r\n", aasworld.numclusters, cluster->numareas);
         aasworld.numclusters++;
     } //end for
     return qtrue;
 } //end of the function AAS_FindClusters
References AAS_Error(), AAS_FloodClusterAreas_r(), AAS_FloodClusterAreasUsingReachabilities(), AAS_MAX_CLUSTERS, AAS_NumberClusterAreas(), AAS_RemoveClusterAreas(), aasworld, AREACONTENTS_CLUSTERPORTAL, aas_s::areasettings, aas_areasettings_s::cluster, aas_s::clusters, aas_areasettings_s::contents, aas_cluster_s::firstportal, nofaceflood, aas_cluster_s::numareas, aas_s::numareas, aas_s::numclusters, aas_cluster_s::numportals, aas_cluster_s::numreachabilityareas, aas_areasettings_s::numreachableareas, aas_s::portalindexsize, qfalse, and qtrue.
Referenced by AAS_InitClustering().
AAS_FindPossiblePortals()
void AAS_FindPossiblePortals (void)
Definition at line 921 of file be_aas_cluster.c.
 {
     int i, numpossibleportals;
     numpossibleportals = 0;
     for (i = 1; i < aasworld.numareas; i++)
     {
         numpossibleportals += AAS_CheckAreaForPossiblePortals(i);
     } //end for
     botimport.Print(PRT_MESSAGE, "\r%6d possible portal areas\n", numpossibleportals);
 } //end of the function AAS_FindPossiblePortals
References AAS_CheckAreaForPossiblePortals(), aasworld, botimport, aas_s::numareas, and PRT_MESSAGE.
Referenced by AAS_InitClustering().
AAS_FloodClusterAreas_r()
int AAS_FloodClusterAreas_r (int areanum, int clusternum)
Definition at line 178 of file be_aas_cluster.c.
 {
     aas_area_t *area;
     aas_face_t *face;
     int facenum, i;
     //
     if (areanum <= 0 || areanum >= aasworld.numareas)
     {
         AAS_Error("AAS_FloodClusterAreas_r: areanum out of range\n");
         return qfalse;
     } //end if
     //if the area is already part of a cluster
     if (aasworld.areasettings[areanum].cluster > 0)
     {
         if (aasworld.areasettings[areanum].cluster == clusternum) return qtrue;
         //
         //there's a reachability going from one cluster to another only in one direction
         //
         AAS_Error("cluster %d touched cluster %d at area %d\n",
                 clusternum, aasworld.areasettings[areanum].cluster, areanum);
         return qfalse;
     } //end if
     //don't add the cluster portal areas to the clusters
     if (aasworld.areasettings[areanum].contents & AREACONTENTS_CLUSTERPORTAL)
     {
         return AAS_UpdatePortal(areanum, clusternum);
     } //end if
     //set the area cluster number
     aasworld.areasettings[areanum].cluster = clusternum;
     aasworld.areasettings[areanum].clusterareanum =
                 aasworld.clusters[clusternum].numareas;
     //the cluster has an extra area
     aasworld.clusters[clusternum].numareas++;
     area = &aasworld.areas[areanum];
     //use area faces to flood into adjacent areas
     if (!nofaceflood)
     {
         for (i = 0; i < area->numfaces; i++)
         {
             facenum = abs(aasworld.faceindex[area->firstface + i]);
             face = &aasworld.faces[facenum];
             if (face->frontarea == areanum)
             {
                 if (face->backarea) if (!AAS_FloodClusterAreas_r(face->backarea, clusternum)) return qfalse;
             } //end if
             else
             {
                 if (face->frontarea) if (!AAS_FloodClusterAreas_r(face->frontarea, clusternum)) return qfalse;
             } //end else
         } //end for
     } //end if
     //use the reachabilities to flood into other areas
     for (i = 0; i < aasworld.areasettings[areanum].numreachableareas; i++)
     {
         if (!aasworld.reachability[
                     aasworld.areasettings[areanum].firstreachablearea + i].areanum)
         {
             continue;
         } //end if
         if (!AAS_FloodClusterAreas_r(aasworld.reachability[
                 aasworld.areasettings[areanum].firstreachablearea + i].areanum, clusternum)) return qfalse;
     } //end for
     return qtrue;
 } //end of the function AAS_FloodClusterAreas_r
References AAS_Error(), AAS_UpdatePortal(), aasworld, AREACONTENTS_CLUSTERPORTAL, aas_reachability_s::areanum, aas_s::areas, aas_s::areasettings, aas_face_s::backarea, aas_areasettings_s::cluster, aas_areasettings_s::clusterareanum, aas_s::clusters, aas_areasettings_s::contents, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, aas_areasettings_s::firstreachablearea, aas_face_s::frontarea, nofaceflood, aas_cluster_s::numareas, aas_s::numareas, aas_area_s::numfaces, aas_areasettings_s::numreachableareas, qfalse, qtrue, and aas_s::reachability.
Referenced by AAS_FindClusters(), and AAS_FloodClusterAreasUsingReachabilities().
AAS_FloodClusterAreasUsingReachabilities()
int AAS_FloodClusterAreasUsingReachabilities (int clusternum)
Definition at line 251 of file be_aas_cluster.c.
 {
     int i, j, areanum;
     for (i = 1; i < aasworld.numareas; i++)
     {
         //if this area already has a cluster set
         if (aasworld.areasettings[i].cluster)
             continue;
         //if this area is a cluster portal
         if (aasworld.areasettings[i].contents & AREACONTENTS_CLUSTERPORTAL)
             continue;
         //loop over the reachable areas from this area
         for (j = 0; j < aasworld.areasettings[i].numreachableareas; j++)
         {
             //the reachable area
             areanum = aasworld.reachability[aasworld.areasettings[i].firstreachablearea + j].areanum;
             //if this area is a cluster portal
             if (aasworld.areasettings[areanum].contents & AREACONTENTS_CLUSTERPORTAL)
                 continue;
             //if this area has a cluster set
             if (aasworld.areasettings[areanum].cluster)
             {
                 if (!AAS_FloodClusterAreas_r(i, clusternum))
                     return qfalse;
                 i = 0;
                 break;
             } //end if
         } //end for
     } //end for
     return qtrue;
 } //end of the function AAS_FloodClusterAreasUsingReachabilities
References AAS_FloodClusterAreas_r(), aasworld, AREACONTENTS_CLUSTERPORTAL, aas_reachability_s::areanum, aas_s::areasettings, aas_areasettings_s::cluster, aas_areasettings_s::contents, aas_areasettings_s::firstreachablearea, aas_s::numareas, aas_areasettings_s::numreachableareas, qfalse, qtrue, and aas_s::reachability.
Referenced by AAS_FindClusters().
AAS_GetAdjacentAreasWithLessPresenceTypes_r()
int AAS_GetAdjacentAreasWithLessPresenceTypes_r (int * areanums, int numareas, int curareanum)
Definition at line 745 of file be_aas_cluster.c.
 {
     int i, j, presencetype, otherpresencetype, otherareanum, facenum;
     aas_area_t *area;
     aas_face_t *face;
     areanums[numareas++] = curareanum;
     area = &aasworld.areas[curareanum];
     presencetype = aasworld.areasettings[curareanum].presencetype;
     for (i = 0; i < area->numfaces; i++)
     {
         facenum = abs(aasworld.faceindex[area->firstface + i]);
         face = &aasworld.faces[facenum];
         //if the face is solid
         if (face->faceflags & FACE_SOLID) continue;
         //the area at the other side of the face
         if (face->frontarea != curareanum) otherareanum = face->frontarea;
         else otherareanum = face->backarea;
         //
         otherpresencetype = aasworld.areasettings[otherareanum].presencetype;
         //if the other area has less presence types
         if ((presencetype & ~otherpresencetype) &&
                 !(otherpresencetype & ~presencetype))
         {
             //check if the other area isn't already in the list
             for (j = 0; j < numareas; j++)
             {
                 if (otherareanum == areanums[j]) break;
             } //end for
             //if the other area isn't already in the list
             if (j == numareas)
             {
                 if (numareas >= MAX_PORTALAREAS)
                 {
                     AAS_Error("MAX_PORTALAREAS\n");
                     return numareas;
                 } //end if
                 numareas = AAS_GetAdjacentAreasWithLessPresenceTypes_r(areanums, numareas, otherareanum);
             } //end if
         } //end if
     } //end for
     return numareas;
 } //end of the function AAS_GetAdjacentAreasWithLessPresenceTypes_r
References AAS_Error(), aasworld, aas_s::areas, aas_s::areasettings, aas_face_s::backarea, FACE_SOLID, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, aas_face_s::frontarea, MAX_PORTALAREAS, aas_area_s::numfaces, and aas_areasettings_s::presencetype.
Referenced by AAS_CheckAreaForPossiblePortals().
AAS_InitClustering()
void AAS_InitClustering (void)
Definition at line 1459 of file be_aas_cluster.c.
 {
     int i, removedPortalAreas;
     int n, total, numreachabilityareas;
     if (!aasworld.loaded) return;
     //if there are clusters
     if (aasworld.numclusters >= 1)
     {
 #ifndef BSPC
         //if clustering isn't forced
         if (!((int)LibVarGetValue("forceclustering")) &&
             !((int)LibVarGetValue("forcereachability"))) return;
 #endif
     } //end if
     //set all view portals as cluster portals in case we re-calculate the reachabilities and clusters (with -reach)
     AAS_SetViewPortalsAsClusterPortals();
     //count the number of forced cluster portals
     AAS_CountForcedClusterPortals();
     //remove all area cluster marks
     AAS_RemoveClusterAreas();
     //find possible cluster portals
     AAS_FindPossiblePortals();
     //craete portals to for the bot view
     AAS_CreateViewPortals();
     //remove all portals that are not closing a cluster
     //AAS_RemoveNotClusterClosingPortals();
     //initialize portal memory
     if (aasworld.portals) FreeMemory(aasworld.portals);
     aasworld.portals = (aas_portal_t *) GetClearedMemory(AAS_MAX_PORTALS * sizeof(aas_portal_t));
     //initialize portal index memory
     if (aasworld.portalindex) FreeMemory(aasworld.portalindex);
     aasworld.portalindex = (aas_portalindex_t *) GetClearedMemory(AAS_MAX_PORTALINDEXSIZE * sizeof(aas_portalindex_t));
     //initialize cluster memory
     if (aasworld.clusters) FreeMemory(aasworld.clusters);
     aasworld.clusters = (aas_cluster_t *) GetClearedMemory(AAS_MAX_CLUSTERS * sizeof(aas_cluster_t));
     //
     removedPortalAreas = 0;
     botimport.Print(PRT_MESSAGE, "\r%6d removed portal areas", removedPortalAreas);
     while(1)
     {
         botimport.Print(PRT_MESSAGE, "\r%6d", removedPortalAreas);
         //initialize the number of portals and clusters
         aasworld.numportals = 1;        //portal 0 is a dummy
         aasworld.portalindexsize = 0;
         aasworld.numclusters = 1;       //cluster 0 is a dummy
         //create the portals from the portal areas
         AAS_CreatePortals();
         //
         removedPortalAreas++;
         //find the clusters
         if (!AAS_FindClusters())
             continue;
         //test the portals
         if (!AAS_TestPortals())
             continue;
         //
         break;
     } //end while
     botimport.Print(PRT_MESSAGE, "\n");
     //the AAS file should be saved
     aasworld.savefile = qtrue;
     //write the portal areas to the log file
     for (i = 1; i < aasworld.numportals; i++)
     {
         Log_Write("portal %d: area %d\r\n", i, aasworld.portals[i].areanum);
     } //end for
     // report cluster info
     botimport.Print(PRT_MESSAGE, "%6d portals created\n", aasworld.numportals);
     botimport.Print(PRT_MESSAGE, "%6d clusters created\n", aasworld.numclusters);
     for (i = 1; i < aasworld.numclusters; i++)
     {
         botimport.Print(PRT_MESSAGE, "cluster %d has %d reachability areas\n", i,
                 aasworld.clusters[i].numreachabilityareas);
     } //end for
     // report AAS file efficiency
     numreachabilityareas = 0;
     total = 0;
     for (i = 0; i < aasworld.numclusters; i++) {
         n = aasworld.clusters[i].numreachabilityareas;
         numreachabilityareas += n;
         total += n * n;
     }
     total += numreachabilityareas * aasworld.numportals;
     //
     botimport.Print(PRT_MESSAGE, "%6i total reachability areas\n", numreachabilityareas);
     botimport.Print(PRT_MESSAGE, "%6i AAS memory/CPU usage (the lower the better)\n", total * 3);
 } //end of the function AAS_InitClustering
References AAS_CountForcedClusterPortals(), AAS_CreatePortals(), AAS_CreateViewPortals(), AAS_FindClusters(), AAS_FindPossiblePortals(), AAS_MAX_CLUSTERS, AAS_MAX_PORTALINDEXSIZE, AAS_MAX_PORTALS, AAS_RemoveClusterAreas(), AAS_SetViewPortalsAsClusterPortals(), AAS_TestPortals(), aasworld, aas_portal_s::areanum, botimport, aas_s::clusters, FreeMemory(), GetClearedMemory(), LibVarGetValue(), aas_s::loaded, Log_Write(), aas_s::numclusters, aas_s::numportals, aas_cluster_s::numreachabilityareas, aas_s::portalindex, aas_s::portalindexsize, aas_s::portals, PRT_MESSAGE, qtrue, and aas_s::savefile.
Referenced by AAS_ContinueInit().
AAS_NumberClusterAreas()
void AAS_NumberClusterAreas (int clusternum)
Definition at line 316 of file be_aas_cluster.c.
 {
     int i, portalnum;
     aas_cluster_t *cluster;
     aas_portal_t *portal;
     aasworld.clusters[clusternum].numareas = 0;
     aasworld.clusters[clusternum].numreachabilityareas = 0;
     //number all areas in this cluster WITH reachabilities
     for (i = 1; i < aasworld.numareas; i++)
     {
         //
         if (aasworld.areasettings[i].cluster != clusternum) continue;
         //
         if (!AAS_AreaReachability(i)) continue;
         //
         aasworld.areasettings[i].clusterareanum = aasworld.clusters[clusternum].numareas;
         //the cluster has an extra area
         aasworld.clusters[clusternum].numareas++;
         aasworld.clusters[clusternum].numreachabilityareas++;
     } //end for
     //number all portals in this cluster WITH reachabilities
     cluster = &aasworld.clusters[clusternum];
     for (i = 0; i < cluster->numportals; i++)
     {
         portalnum = aasworld.portalindex[cluster->firstportal + i];
         portal = &aasworld.portals[portalnum];
         if (!AAS_AreaReachability(portal->areanum)) continue;
         if (portal->frontcluster == clusternum)
         {
             portal->clusterareanum[0] = cluster->numareas++;
             aasworld.clusters[clusternum].numreachabilityareas++;
         } //end if
         else
         {
             portal->clusterareanum[1] = cluster->numareas++;
             aasworld.clusters[clusternum].numreachabilityareas++;
         } //end else
     } //end for
     //number all areas in this cluster WITHOUT reachabilities
     for (i = 1; i < aasworld.numareas; i++)
     {
         //
         if (aasworld.areasettings[i].cluster != clusternum) continue;
         //
         if (AAS_AreaReachability(i)) continue;
         //
         aasworld.areasettings[i].clusterareanum = aasworld.clusters[clusternum].numareas;
         //the cluster has an extra area
         aasworld.clusters[clusternum].numareas++;
     } //end for
     //number all portals in this cluster WITHOUT reachabilities
     cluster = &aasworld.clusters[clusternum];
     for (i = 0; i < cluster->numportals; i++)
     {
         portalnum = aasworld.portalindex[cluster->firstportal + i];
         portal = &aasworld.portals[portalnum];
         if (AAS_AreaReachability(portal->areanum)) continue;
         if (portal->frontcluster == clusternum)
         {
             portal->clusterareanum[0] = cluster->numareas++;
         } //end if
         else
         {
             portal->clusterareanum[1] = cluster->numareas++;
         } //end else
     } //end for
 } //end of the function AAS_NumberClusterAreas
References AAS_AreaReachability(), aasworld, aas_portal_s::areanum, aas_s::areasettings, aas_areasettings_s::cluster, aas_areasettings_s::clusterareanum, aas_portal_s::clusterareanum, aas_s::clusters, aas_cluster_s::firstportal, aas_portal_s::frontcluster, aas_cluster_s::numareas, aas_s::numareas, aas_cluster_s::numportals, aas_cluster_s::numreachabilityareas, aas_s::portalindex, and aas_s::portals.
Referenced by AAS_FindClusters().
AAS_NumberClusterPortals()
void AAS_NumberClusterPortals (int clusternum)
Definition at line 289 of file be_aas_cluster.c.
 {
     int i, portalnum;
     aas_cluster_t *cluster;
     aas_portal_t *portal;
     cluster = &aasworld.clusters[clusternum];
     for (i = 0; i < cluster->numportals; i++)
     {
         portalnum = aasworld.portalindex[cluster->firstportal + i];
         portal = &aasworld.portals[portalnum];
         if (portal->frontcluster == clusternum)
         {
             portal->clusterareanum[0] = cluster->numareas++;
         } //end if
         else
         {
             portal->clusterareanum[1] = cluster->numareas++;
         } //end else
     } //end for
 } //end of the function AAS_NumberClusterPortals
References aasworld, aas_portal_s::clusterareanum, aas_s::clusters, aas_cluster_s::firstportal, aas_portal_s::frontcluster, aas_cluster_s::numareas, aas_cluster_s::numportals, aas_s::portalindex, and aas_s::portals.
AAS_RemoveAllPortals()
void AAS_RemoveAllPortals (void)
Definition at line 938 of file be_aas_cluster.c.
 {
     int i;
     for (i = 1; i < aasworld.numareas; i++)
     {
         aasworld.areasettings[i].contents &= ~AREACONTENTS_CLUSTERPORTAL;
     } //end for
 } //end of the function AAS_RemoveAllPortals
References aasworld, AREACONTENTS_CLUSTERPORTAL, aas_s::areasettings, aas_areasettings_s::contents, and aas_s::numareas.
AAS_RemoveClusterAreas()
void AAS_RemoveClusterAreas (void)
Definition at line 64 of file be_aas_cluster.c.
 {
     int i;
     for (i = 1; i < aasworld.numareas; i++)
     {
         aasworld.areasettings[i].cluster = 0;
     } //end for
 } //end of the function AAS_RemoveClusterAreas
References aasworld, aas_s::areasettings, aas_areasettings_s::cluster, and aas_s::numareas.
Referenced by AAS_FindClusters(), and AAS_InitClustering().
AAS_RemovePortalsClusterReference()
void AAS_RemovePortalsClusterReference (int clusternum)
Definition at line 97 of file be_aas_cluster.c.
 {
     int portalnum;
     for (portalnum = 1; portalnum < aasworld.numportals; portalnum++)
     {
         if (aasworld.portals[portalnum].frontcluster == clusternum)
         {
             aasworld.portals[portalnum].frontcluster = 0;
         } //end if
         if (aasworld.portals[portalnum].backcluster == clusternum)
         {
             aasworld.portals[portalnum].backcluster = 0;
         } //end if
     } //end for
 } //end of the function AAS_RemovePortalsClusterReference
References aasworld, aas_portal_s::backcluster, aas_portal_s::frontcluster, aas_s::numportals, and aas_s::portals.
AAS_SetViewPortalsAsClusterPortals()
void AAS_SetViewPortalsAsClusterPortals (void)
Definition at line 1441 of file be_aas_cluster.c.
 {
     int i;
     for (i = 1; i < aasworld.numareas; i++)
     {
         if (aasworld.areasettings[i].contents & AREACONTENTS_VIEWPORTAL)
         {
             aasworld.areasettings[i].contents |= AREACONTENTS_CLUSTERPORTAL;
         } //end if
     } //end for
 } //end of the function AAS_SetViewPortalsAsClusterPortals
References aasworld, AREACONTENTS_CLUSTERPORTAL, AREACONTENTS_VIEWPORTAL, aas_s::areasettings, aas_areasettings_s::contents, and aas_s::numareas.
Referenced by AAS_InitClustering().
AAS_TestPortals()
int AAS_TestPortals (void)
Definition at line 1373 of file be_aas_cluster.c.
 {
     int i;
     aas_portal_t *portal;
     for (i = 1; i < aasworld.numportals; i++)
     {
         portal = &aasworld.portals[i];
         if (!portal->frontcluster)
         {
             aasworld.areasettings[portal->areanum].contents &= ~AREACONTENTS_CLUSTERPORTAL;
             Log_Write("portal area %d has no front cluster\r\n", portal->areanum);
             return qfalse;
         } //end if
         if (!portal->backcluster)
         {
             aasworld.areasettings[portal->areanum].contents &= ~AREACONTENTS_CLUSTERPORTAL;
             Log_Write("portal area %d has no back cluster\r\n", portal->areanum);
             return qfalse;
         } //end if
     } //end for
     return qtrue;
 } //end of the function
References aasworld, AREACONTENTS_CLUSTERPORTAL, aas_portal_s::areanum, aas_s::areasettings, aas_portal_s::backcluster, aas_areasettings_s::contents, aas_portal_s::frontcluster, Log_Write(), aas_s::numportals, aas_s::portals, qfalse, and qtrue.
Referenced by AAS_InitClustering().
AAS_UpdatePortal()
int AAS_UpdatePortal (int areanum, int clusternum)
Definition at line 119 of file be_aas_cluster.c.
 {
     int portalnum;
     aas_portal_t *portal;
     aas_cluster_t *cluster;
     //find the portal of the area
     for (portalnum = 1; portalnum < aasworld.numportals; portalnum++)
     {
         if (aasworld.portals[portalnum].areanum == areanum) break;
     } //end for
     //
     if (portalnum == aasworld.numportals)
     {
         AAS_Error("no portal of area %d\n", areanum);
         return qtrue;
     } //end if
     //
     portal = &aasworld.portals[portalnum];
     //if the portal is already fully updated
     if (portal->frontcluster == clusternum) return qtrue;
     if (portal->backcluster == clusternum) return qtrue;
     //if the portal has no front cluster yet
     if (!portal->frontcluster)
     {
         portal->frontcluster = clusternum;
     } //end if
     //if the portal has no back cluster yet
     else if (!portal->backcluster)
     {
         portal->backcluster = clusternum;
     } //end else if
     else
     {
         //remove the cluster portal flag contents
         aasworld.areasettings[areanum].contents &= ~AREACONTENTS_CLUSTERPORTAL;
         Log_Write("portal area %d is separating more than two clusters\r\n", areanum);
         return qfalse;
     } //end else
     if (aasworld.portalindexsize >= AAS_MAX_PORTALINDEXSIZE)
     {
         AAS_Error("AAS_MAX_PORTALINDEXSIZE\n");
         return qtrue;
     } //end if
     //set the area cluster number to the negative portal number
     aasworld.areasettings[areanum].cluster = -portalnum;
     //add the portal to the cluster using the portal index
     cluster = &aasworld.clusters[clusternum];
     aasworld.portalindex[cluster->firstportal + cluster->numportals] = portalnum;
     aasworld.portalindexsize++;
     cluster->numportals++;
     return qtrue;
 } //end of the function AAS_UpdatePortal
References AAS_Error(), AAS_MAX_PORTALINDEXSIZE, aasworld, AREACONTENTS_CLUSTERPORTAL, aas_portal_s::areanum, aas_s::areasettings, aas_portal_s::backcluster, aas_areasettings_s::cluster, aas_s::clusters, aas_areasettings_s::contents, aas_cluster_s::firstportal, aas_portal_s::frontcluster, Log_Write(), aas_cluster_s::numportals, aas_s::numportals, aas_s::portalindex, aas_s::portalindexsize, aas_s::portals, qfalse, and qtrue.
Referenced by AAS_FloodClusterAreas_r().
Variable Documentation
botimport
botlib_import_t botimport
Definition at line 59 of file be_interface.c.
Referenced by AAS_CountForcedClusterPortals(), AAS_FindPossiblePortals(), and AAS_InitClustering().
nofaceflood
int nofaceflood = qtrue
Definition at line 56 of file be_aas_cluster.c.
Referenced by AAS_FindClusters(), and AAS_FloodClusterAreas_r().