ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_crc.h File Reference
l_crc.h File Reference
Typedefs
typedef unsigned short crc_t
Functions
void CRC_Init (unsigned short *crcvalue)
void CRC_ProcessByte (unsigned short *crcvalue, byte data)
unsigned short CRC_Value (unsigned short crcvalue)
unsigned short CRC_ProcessString (unsigned char *data, int length)
void CRC_ContinueProcessString (unsigned short *crc, char *data, int length)
Typedef Documentation
crc_t
typedef unsigned short crc_t
Definition at line 23 of file l_crc.h.
Function Documentation
CRC_ContinueProcessString()
void CRC_ContinueProcessString (unsigned short * crc, char * data, int length)
Definition at line 144 of file l_crc.c.
 {
     int i;
     for (i = 0; i < length; i++)
     {
         *crc = (*crc << 8) ^ crctable[(*crc >> 8) ^ data[i]];
     } //end for
 } //end of the function CRC_ProcessString
References crctable.
CRC_Init()
void CRC_Init (unsigned short * crcvalue)
Definition at line 93 of file l_crc.c.
 {
     *crcvalue = CRC_INIT_VALUE;
 } //end of the function CRC_Init
References CRC_INIT_VALUE.
Referenced by CRC_ProcessString().
CRC_ProcessByte()
void CRC_ProcessByte (unsigned short * crcvalue, byte data)
Definition at line 103 of file l_crc.c.
 {
     *crcvalue = (*crcvalue << 8) ^ crctable[(*crcvalue >> 8) ^ data];
 } //end of the function CRC_ProcessByte
References crctable.
CRC_ProcessString()
unsigned short CRC_ProcessString (unsigned char * data, int length)
Definition at line 123 of file l_crc.c.
 {
     unsigned short crcvalue;
     int i, ind;
     CRC_Init(&crcvalue);
     for (i = 0; i < length; i++)
     {
         ind = (crcvalue >> 8) ^ data[i];
         if (ind < 0 || ind > 256) ind = 0;
         crcvalue = (crcvalue << 8) ^ crctable[ind];
     } //end for
     return CRC_Value(crcvalue);
 } //end of the function CRC_ProcessString
References CRC_Init(), CRC_Value(), and crctable.
Referenced by AAS_ReadRouteCache(), and AAS_WriteRouteCache().
CRC_Value()
unsigned short CRC_Value (unsigned short crcvalue)
Definition at line 113 of file l_crc.c.
 {
     return crcvalue ^ CRC_XOR_VALUE;
 } //end of the function CRC_Value
References CRC_XOR_VALUE.
Referenced by CRC_ProcessString().