ioquake3 doxygen: C:/entry/dev/ioquake3/code/game/ai_dmnet.h File Reference
ai_dmnet.h File Reference
Macros
#define MAX_NODESWITCHES 50
Functions
void AIEnter_Intermission (bot_state_t *bs, char *s)
void AIEnter_Observer (bot_state_t *bs, char *s)
void AIEnter_Respawn (bot_state_t *bs, char *s)
void AIEnter_Stand (bot_state_t *bs, char *s)
void AIEnter_Seek_ActivateEntity (bot_state_t *bs, char *s)
void AIEnter_Seek_NBG (bot_state_t *bs, char *s)
void AIEnter_Seek_LTG (bot_state_t *bs, char *s)
void AIEnter_Seek_Camp (bot_state_t *bs, char *s)
void AIEnter_Battle_Fight (bot_state_t *bs, char *s)
void AIEnter_Battle_Chase (bot_state_t *bs, char *s)
void AIEnter_Battle_Retreat (bot_state_t *bs, char *s)
void AIEnter_Battle_NBG (bot_state_t *bs, char *s)
int AINode_Intermission (bot_state_t *bs)
int AINode_Observer (bot_state_t *bs)
int AINode_Respawn (bot_state_t *bs)
int AINode_Stand (bot_state_t *bs)
int AINode_Seek_ActivateEntity (bot_state_t *bs)
int AINode_Seek_NBG (bot_state_t *bs)
int AINode_Seek_LTG (bot_state_t *bs)
int AINode_Battle_Fight (bot_state_t *bs)
int AINode_Battle_Chase (bot_state_t *bs)
int AINode_Battle_Retreat (bot_state_t *bs)
int AINode_Battle_NBG (bot_state_t *bs)
void BotResetNodeSwitches (void)
void BotDumpNodeSwitches (bot_state_t *bs)
Macro Definition Documentation
MAX_NODESWITCHES
#define MAX_NODESWITCHES 50
Definition at line 33 of file ai_dmnet.h.
Function Documentation
AIEnter_Battle_Chase()
void AIEnter_Battle_Chase (bot_state_t * bs, char * s)
Definition at line 2152 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "battle chase", "", s);
     bs->chase_time = FloatTime();
     bs->ainode = AINode_Battle_Chase;
 }
Referenced by AINode_Battle_Fight(), and AINode_Battle_Retreat().
AIEnter_Battle_Fight()
void AIEnter_Battle_Fight (bot_state_t * bs, char * s)
Definition at line 1968 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "battle fight", "", s);
     trap_BotResetLastAvoidReach(bs->ms);
     bs->ainode = AINode_Battle_Fight;
     bs->flags &= ~BFL_FIGHTSUICIDAL;
 }
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), and AINode_Stand().
AIEnter_Battle_NBG()
void AIEnter_Battle_NBG (bot_state_t * bs, char * s)
Definition at line 2481 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "battle NBG", "", s);
     bs->ainode = AINode_Battle_NBG;
 }
Referenced by AINode_Battle_Chase(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), and AINode_Seek_NBG().
AIEnter_Battle_Retreat()
void AIEnter_Battle_Retreat (bot_state_t * bs, char * s)
Definition at line 2292 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "battle retreat", "", s);
     bs->ainode = AINode_Battle_Retreat;
 }
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), and AINode_Seek_LTG().
AIEnter_Intermission()
void AIEnter_Intermission (bot_state_t * bs, char * s)
Definition at line 1131 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "intermission", "", s);
     //reset the bot state
     BotResetState(bs);
     //check for end level chat
     if (BotChat_EndLevel(bs)) {
         trap_BotEnterChat(bs->cs, 0, bs->chatto);
     }
     bs->ainode = AINode_Intermission;
 }
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
AIEnter_Observer()
void AIEnter_Observer (bot_state_t * bs, char * s)
Definition at line 1166 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "observer", "", s);
     //reset the bot state
     BotResetState(bs);
     bs->ainode = AINode_Observer;
 }
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
AIEnter_Respawn()
void AIEnter_Respawn (bot_state_t * bs, char * s)
Definition at line 1235 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "respawn", "", s);
     //reset some states
     trap_BotResetMoveState(bs->ms);
     trap_BotResetGoalState(bs->gs);
     trap_BotResetAvoidGoals(bs->gs);
     trap_BotResetAvoidReach(bs->ms);
     //if the bot wants to chat
     if (BotChat_Death(bs)) {
         bs->respawn_time = FloatTime() + BotChatTime(bs);
         bs->respawnchat_time = FloatTime();
     }
     else {
         bs->respawn_time = FloatTime() + 1 + random();
         bs->respawnchat_time = 0;
     }
     //set respawn state
     bs->respawn_wait = qfalse;
     bs->ainode = AINode_Respawn;
 }
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
AIEnter_Seek_ActivateEntity()
void AIEnter_Seek_ActivateEntity (bot_state_t * bs, char * s)
Definition at line 1438 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "activate entity", "", s);
     bs->ainode = AINode_Seek_ActivateEntity;
 }
Referenced by BotGoForActivateGoal().
AIEnter_Seek_Camp()
void AIEnter_Seek_Camp (bot_state_t * bs, char * s)
AIEnter_Seek_LTG()
void AIEnter_Seek_LTG (bot_state_t * bs, char * s)
Definition at line 1781 of file ai_dmnet.c.
{
     bot_goal_t goal;
     char buf[144];
     if (trap_BotGetTopGoal(bs->gs, &goal)) {
         trap_BotGoalName(goal.number, buf, 144);
         BotRecordNodeSwitch(bs, "seek LTG", buf, s);
     }
     else {
         BotRecordNodeSwitch(bs, "seek LTG", "no goal", s);
     }
     bs->ainode = AINode_Seek_LTG;
 }
Referenced by AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_Retreat(), AINode_Respawn(), AINode_Seek_NBG(), AINode_Stand(), and BotDeathmatchAI().
AIEnter_Seek_NBG()
void AIEnter_Seek_NBG (bot_state_t * bs, char * s)
Definition at line 1648 of file ai_dmnet.c.
{
     bot_goal_t goal;
     char buf[144];
     if (trap_BotGetTopGoal(bs->gs, &goal)) {
         trap_BotGoalName(goal.number, buf, 144);
         BotRecordNodeSwitch(bs, "seek NBG", buf, s);
     }
     else {
         BotRecordNodeSwitch(bs, "seek NBG", "no goal", s);
     }
     bs->ainode = AINode_Seek_NBG;
 }
Referenced by AINode_Battle_NBG(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and BotGetLongTermGoal().
AIEnter_Stand()
void AIEnter_Stand (bot_state_t * bs, char * s)
Definition at line 1191 of file ai_dmnet.c.
{
     BotRecordNodeSwitch(bs, "stand", "", s);
     bs->standfindenemy_time = FloatTime() + 1;
     bs->ainode = AINode_Stand;
 }
Referenced by AINode_Battle_Fight(), AINode_Intermission(), AINode_Observer(), AINode_Seek_LTG(), BotCheckConsoleMessages(), and BotDeathmatchAI().
AINode_Battle_Chase()
int AINode_Battle_Chase (bot_state_t * bs)
Definition at line 2163 of file ai_dmnet.c.
 {
     bot_goal_t goal;
     vec3_t target, dir;
     bot_moveresult_t moveresult;
     float range;
     if (BotIsObserver(bs)) {
         AIEnter_Observer(bs, "battle chase: observer");
         return qfalse;
     }
     //if in the intermission
     if (BotIntermission(bs)) {
         AIEnter_Intermission(bs, "battle chase: intermission");
         return qfalse;
     }
     //respawn if dead
     if (BotIsDead(bs)) {
         AIEnter_Respawn(bs, "battle chase: bot dead");
         return qfalse;
     }
     //if no enemy
     if (bs->enemy < 0) {
         AIEnter_Seek_LTG(bs, "battle chase: no enemy");
         return qfalse;
     }
     //if the enemy is visible
     if (BotEntityVisible(bs->entitynum, bs->eye, bs->viewangles, 360, bs->enemy)) {
         AIEnter_Battle_Fight(bs, "battle chase");
         return qfalse;
     }
     //if there is another enemy
     if (BotFindEnemy(bs, -1)) {
         AIEnter_Battle_Fight(bs, "battle chase: better enemy");
         return qfalse;
     }
     //there is no last enemy area
     if (!bs->lastenemyareanum) {
         AIEnter_Seek_LTG(bs, "battle chase: no enemy area");
         return qfalse;
     }
     //
     bs->tfl = TFL_DEFAULT;
     if (bot_grapple.integer) bs->tfl |= TFL_GRAPPLEHOOK;
     //if in lava or slime the bot should be able to get out
     if (BotInLavaOrSlime(bs)) bs->tfl |= TFL_LAVA|TFL_SLIME;
     //
     if (BotCanAndWantsToRocketJump(bs)) {
         bs->tfl |= TFL_ROCKETJUMP;
     }
     //map specific code
     BotMapScripts(bs);
     //create the chase goal
     goal.entitynum = bs->enemy;
     goal.areanum = bs->lastenemyareanum;
     VectorCopy(bs->lastenemyorigin, goal.origin);
     VectorSet(goal.mins, -8, -8, -8);
     VectorSet(goal.maxs, 8, 8, 8);
     //if the last seen enemy spot is reached the enemy could not be found
     if (trap_BotTouchingGoal(bs->origin, &goal)) bs->chase_time = 0;
     //if there's no chase time left
     if (!bs->chase_time || bs->chase_time < FloatTime() - 10) {
         AIEnter_Seek_LTG(bs, "battle chase: time out");
         return qfalse;
     }
     //check for nearby goals periodicly
     if (bs->check_time < FloatTime()) {
         bs->check_time = FloatTime() + 1;
         range = 150;
         //
         if (BotNearbyGoal(bs, bs->tfl, &goal, range)) {
             //the bot gets 5 seconds to pick up the nearby goal item
             bs->nbg_time = FloatTime() + 0.1 * range + 1;
             trap_BotResetLastAvoidReach(bs->ms);
             AIEnter_Battle_NBG(bs, "battle chase: nbg");
             return qfalse;
         }
     }
     //
     BotUpdateBattleInventory(bs, bs->enemy);
     //initialize the movement state
     BotSetupForMovement(bs);
     //move towards the goal
     trap_BotMoveToGoal(&moveresult, bs->ms, &goal, bs->tfl);
     //if the movement failed
     if (moveresult.failure) {
         //reset the avoid reach, otherwise bot is stuck in current area
         trap_BotResetAvoidReach(bs->ms);
         //BotAI_Print(PRT_MESSAGE, "movement failure %d\n", moveresult.traveltype);
         bs->ltg_time = 0;
     }
     //
     BotAIBlocked(bs, &moveresult, qfalse);
     //
     if (moveresult.flags & (MOVERESULT_MOVEMENTVIEWSET|MOVERESULT_MOVEMENTVIEW|MOVERESULT_SWIMVIEW)) {
         VectorCopy(moveresult.ideal_viewangles, bs->ideal_viewangles);
     }
     else if (!(bs->flags & BFL_IDEALVIEWSET)) {
         if (bs->chase_time > FloatTime() - 2) {
             BotAimAtEnemy(bs);
         }
         else {
             if (trap_BotMovementViewTarget(bs->ms, &goal, bs->tfl, 300, target)) {
                 VectorSubtract(target, bs->origin, dir);
                 vectoangles(dir, bs->ideal_viewangles);
             }
             else {
                 vectoangles(moveresult.movedir, bs->ideal_viewangles);
             }
         }
         bs->ideal_viewangles[2] *= 0.5;
     }
     //if the weapon is used for the bot movement
     if (moveresult.flags & MOVERESULT_MOVEMENTWEAPON) bs->weaponnum = moveresult.weapon;
     //if the bot is in the area the enemy was last seen in
     if (bs->areanum == bs->lastenemyareanum) bs->chase_time = 0;
     //if the bot wants to retreat (the bot could have been damage during the chase)
     if (BotWantsToRetreat(bs)) {
         AIEnter_Battle_Retreat(bs, "battle chase: wants to retreat");
         return qtrue;
     }
     return qtrue;
 }
Referenced by AIEnter_Battle_Chase().
AINode_Battle_Fight()
int AINode_Battle_Fight (bot_state_t * bs)
Definition at line 1992 of file ai_dmnet.c.
{
     int areanum;
     vec3_t target;
     aas_entityinfo_t entinfo;
     bot_moveresult_t moveresult;
     if (BotIsObserver(bs)) {
         AIEnter_Observer(bs, "battle fight: observer");
         return qfalse;
     }
     //if in the intermission
     if (BotIntermission(bs)) {
         AIEnter_Intermission(bs, "battle fight: intermission");
         return qfalse;
     }
     //respawn if dead
     if (BotIsDead(bs)) {
         AIEnter_Respawn(bs, "battle fight: bot dead");
         return qfalse;
     }
     //if there is another better enemy
     if (BotFindEnemy(bs, bs->enemy)) {
 #ifdef DEBUG
         BotAI_Print(PRT_MESSAGE, "found new better enemy\n");
 #endif
     }
     //if no enemy
     if (bs->enemy < 0) {
         AIEnter_Seek_LTG(bs, "battle fight: no enemy");
         return qfalse;
     }
     //
     BotEntityInfo(bs->enemy, &entinfo);
     //if the enemy is dead
     if (bs->enemydeath_time) {
         if (bs->enemydeath_time < FloatTime() - 1.0) {
             bs->enemydeath_time = 0;
             if (bs->enemysuicide) {
                 BotChat_EnemySuicide(bs);
             }
             if (bs->lastkilledplayer == bs->enemy && BotChat_Kill(bs)) {
                 bs->stand_time = FloatTime() + BotChatTime(bs);
                 AIEnter_Stand(bs, "battle fight: enemy dead");
             }
             else {
                 bs->ltg_time = 0;
                 AIEnter_Seek_LTG(bs, "battle fight: enemy dead");
             }
             return qfalse;
         }
     }
     else {
         if (EntityIsDead(&entinfo)) {
             bs->enemydeath_time = FloatTime();
         }
     }
     //if the enemy is invisible and not shooting the bot looses track easily
     if (EntityIsInvisible(&entinfo) && !EntityIsShooting(&entinfo)) {
         if (random() < 0.2) {
             AIEnter_Seek_LTG(bs, "battle fight: invisible");
             return qfalse;
         }
     }
     //
     VectorCopy(entinfo.origin, target);
     // if not a player enemy
     if (bs->enemy >= MAX_CLIENTS) {
 #ifdef MISSIONPACK
         // if attacking an obelisk
         if ( bs->enemy == redobelisk.entitynum ||
             bs->enemy == blueobelisk.entitynum ) {
             target[2] += 16;
         }
 #endif
     }
     //update the reachability area and origin if possible
     areanum = BotPointAreaNum(target);
     if (areanum && trap_AAS_AreaReachability(areanum)) {
         VectorCopy(target, bs->lastenemyorigin);
         bs->lastenemyareanum = areanum;
     }
     //update the attack inventory values
     BotUpdateBattleInventory(bs, bs->enemy);
     //if the bot's health decreased
     if (bs->lastframe_health > bs->inventory[INVENTORY_HEALTH]) {
         if (BotChat_HitNoDeath(bs)) {
             bs->stand_time = FloatTime() + BotChatTime(bs);
             AIEnter_Stand(bs, "battle fight: chat health decreased");
             return qfalse;
         }
     }
     //if the bot hit someone
     if (bs->cur_ps.persistant[PERS_HITS] > bs->lasthitcount) {
         if (BotChat_HitNoKill(bs)) {
             bs->stand_time = FloatTime() + BotChatTime(bs);
             AIEnter_Stand(bs, "battle fight: chat hit someone");
             return qfalse;
         }
     }
     //if the enemy is not visible
     if (!BotEntityVisible(bs->entitynum, bs->eye, bs->viewangles, 360, bs->enemy)) {
 #ifdef MISSIONPACK
         if (bs->enemy == redobelisk.entitynum || bs->enemy == blueobelisk.entitynum) {
             AIEnter_Battle_Chase(bs, "battle fight: obelisk out of sight");
             return qfalse;
         }
 #endif
         if (BotWantsToChase(bs)) {
             AIEnter_Battle_Chase(bs, "battle fight: enemy out of sight");
             return qfalse;
         }
         else {
             AIEnter_Seek_LTG(bs, "battle fight: enemy out of sight");
             return qfalse;
         }
     }
     //use holdable items
     BotBattleUseItems(bs);
     //
     bs->tfl = TFL_DEFAULT;
     if (bot_grapple.integer) bs->tfl |= TFL_GRAPPLEHOOK;
     //if in lava or slime the bot should be able to get out
     if (BotInLavaOrSlime(bs)) bs->tfl |= TFL_LAVA|TFL_SLIME;
     //
     if (BotCanAndWantsToRocketJump(bs)) {
         bs->tfl |= TFL_ROCKETJUMP;
     }
     //choose the best weapon to fight with
     BotChooseWeapon(bs);
     //do attack movements
     moveresult = BotAttackMove(bs, bs->tfl);
     //if the movement failed
     if (moveresult.failure) {
         //reset the avoid reach, otherwise bot is stuck in current area
         trap_BotResetAvoidReach(bs->ms);
         //BotAI_Print(PRT_MESSAGE, "movement failure %d\n", moveresult.traveltype);
         bs->ltg_time = 0;
     }
     //
     BotAIBlocked(bs, &moveresult, qfalse);
     //aim at the enemy
     BotAimAtEnemy(bs);
     //attack the enemy if possible
     BotCheckAttack(bs);
     //if the bot wants to retreat
     if (!(bs->flags & BFL_FIGHTSUICIDAL)) {
         if (BotWantsToRetreat(bs)) {
             AIEnter_Battle_Retreat(bs, "battle fight: wants to retreat");
             return qtrue;
         }
     }
     return qtrue;
 }
Referenced by AIEnter_Battle_Fight(), and AIEnter_Battle_SuicidalFight().
AINode_Battle_NBG()
int AINode_Battle_NBG (bot_state_t * bs)
Definition at line 2491 of file ai_dmnet.c.
{
     int areanum;
     bot_goal_t goal;
     aas_entityinfo_t entinfo;
     bot_moveresult_t moveresult;
     float attack_skill;
     vec3_t target, dir;
     if (BotIsObserver(bs)) {
         AIEnter_Observer(bs, "battle nbg: observer");
         return qfalse;
     }
     //if in the intermission
     if (BotIntermission(bs)) {
         AIEnter_Intermission(bs, "battle nbg: intermission");
         return qfalse;
     }
     //respawn if dead
     if (BotIsDead(bs)) {
         AIEnter_Respawn(bs, "battle nbg: bot dead");
         return qfalse;
     }
     //if no enemy
     if (bs->enemy < 0) {
         AIEnter_Seek_NBG(bs, "battle nbg: no enemy");
         return qfalse;
     }
     //
     BotEntityInfo(bs->enemy, &entinfo);
     if (EntityIsDead(&entinfo)) {
         AIEnter_Seek_NBG(bs, "battle nbg: enemy dead");
         return qfalse;
     }
     //
     bs->tfl = TFL_DEFAULT;
     if (bot_grapple.integer) bs->tfl |= TFL_GRAPPLEHOOK;
     //if in lava or slime the bot should be able to get out
     if (BotInLavaOrSlime(bs)) bs->tfl |= TFL_LAVA|TFL_SLIME;
     //
     if (BotCanAndWantsToRocketJump(bs)) {
         bs->tfl |= TFL_ROCKETJUMP;
     }
     //map specific code
     BotMapScripts(bs);
     //update the last time the enemy was visible
     if (BotEntityVisible(bs->entitynum, bs->eye, bs->viewangles, 360, bs->enemy)) {
         bs->enemyvisible_time = FloatTime();
         VectorCopy(entinfo.origin, target);
         // if not a player enemy
         if (bs->enemy >= MAX_CLIENTS) {
 #ifdef MISSIONPACK
             // if attacking an obelisk
             if ( bs->enemy == redobelisk.entitynum ||
                 bs->enemy == blueobelisk.entitynum ) {
                 target[2] += 16;
             }
 #endif
         }
         //update the reachability area and origin if possible
         areanum = BotPointAreaNum(target);
         if (areanum && trap_AAS_AreaReachability(areanum)) {
             VectorCopy(target, bs->lastenemyorigin);
             bs->lastenemyareanum = areanum;
         }
     }
     //if the bot has no goal or touches the current goal
     if (!trap_BotGetTopGoal(bs->gs, &goal)) {
         bs->nbg_time = 0;
     }
     else if (BotReachedGoal(bs, &goal)) {
         bs->nbg_time = 0;
     }
     //
     if (bs->nbg_time < FloatTime()) {
         //pop the current goal from the stack
         trap_BotPopGoal(bs->gs);
         //if the bot still has a goal
         if (trap_BotGetTopGoal(bs->gs, &goal))
             AIEnter_Battle_Retreat(bs, "battle nbg: time out");
         else
             AIEnter_Battle_Fight(bs, "battle nbg: time out");
         //
         return qfalse;
     }
     //initialize the movement state
     BotSetupForMovement(bs);
     //move towards the goal
     trap_BotMoveToGoal(&moveresult, bs->ms, &goal, bs->tfl);
     //if the movement failed
     if (moveresult.failure) {
         //reset the avoid reach, otherwise bot is stuck in current area
         trap_BotResetAvoidReach(bs->ms);
         //BotAI_Print(PRT_MESSAGE, "movement failure %d\n", moveresult.traveltype);
         bs->nbg_time = 0;
     }
     //
     BotAIBlocked(bs, &moveresult, qfalse);
     //update the attack inventory values
     BotUpdateBattleInventory(bs, bs->enemy);
     //choose the best weapon to fight with
     BotChooseWeapon(bs);
     //if the view is fixed for the movement
     if (moveresult.flags & (MOVERESULT_MOVEMENTVIEW|MOVERESULT_SWIMVIEW)) {
         VectorCopy(moveresult.ideal_viewangles, bs->ideal_viewangles);
     }
     else if (!(moveresult.flags & MOVERESULT_MOVEMENTVIEWSET)
                 && !(bs->flags & BFL_IDEALVIEWSET)) {
         attack_skill = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_ATTACK_SKILL, 0, 1);
         //if the bot is skilled enough and the enemy is visible
         if (attack_skill > 0.3) {
             //&& BotEntityVisible(bs->entitynum, bs->eye, bs->viewangles, 360, bs->enemy)
             BotAimAtEnemy(bs);
         }
         else {
             if (trap_BotMovementViewTarget(bs->ms, &goal, bs->tfl, 300, target)) {
                 VectorSubtract(target, bs->origin, dir);
                 vectoangles(dir, bs->ideal_viewangles);
             }
             else {
                 vectoangles(moveresult.movedir, bs->ideal_viewangles);
             }
             bs->ideal_viewangles[2] *= 0.5;
         }
     }
     //if the weapon is used for the bot movement
     if (moveresult.flags & MOVERESULT_MOVEMENTWEAPON) bs->weaponnum = moveresult.weapon;
     //attack the enemy if possible
     BotCheckAttack(bs);
     //
     return qtrue;
 }
Referenced by AIEnter_Battle_NBG().
AINode_Battle_Retreat()
int AINode_Battle_Retreat (bot_state_t * bs)
Definition at line 2302 of file ai_dmnet.c.
{
     bot_goal_t goal;
     aas_entityinfo_t entinfo;
     bot_moveresult_t moveresult;
     vec3_t target, dir;
     float attack_skill, range;
     int areanum;
     if (BotIsObserver(bs)) {
         AIEnter_Observer(bs, "battle retreat: observer");
         return qfalse;
     }
     //if in the intermission
     if (BotIntermission(bs)) {
         AIEnter_Intermission(bs, "battle retreat: intermission");
         return qfalse;
     }
     //respawn if dead
     if (BotIsDead(bs)) {
         AIEnter_Respawn(bs, "battle retreat: bot dead");
         return qfalse;
     }
     //if no enemy
     if (bs->enemy < 0) {
         AIEnter_Seek_LTG(bs, "battle retreat: no enemy");
         return qfalse;
     }
     //
     BotEntityInfo(bs->enemy, &entinfo);
     if (EntityIsDead(&entinfo)) {
         AIEnter_Seek_LTG(bs, "battle retreat: enemy dead");
         return qfalse;
     }
     //if there is another better enemy
     if (BotFindEnemy(bs, bs->enemy)) {
 #ifdef DEBUG
         BotAI_Print(PRT_MESSAGE, "found new better enemy\n");
 #endif
     }
     //
     bs->tfl = TFL_DEFAULT;
     if (bot_grapple.integer) bs->tfl |= TFL_GRAPPLEHOOK;
     //if in lava or slime the bot should be able to get out
     if (BotInLavaOrSlime(bs)) bs->tfl |= TFL_LAVA|TFL_SLIME;
     //map specific code
     BotMapScripts(bs);
     //update the attack inventory values
     BotUpdateBattleInventory(bs, bs->enemy);
     //if the bot doesn't want to retreat anymore... probably picked up some nice items
     if (BotWantsToChase(bs)) {
         //empty the goal stack, when chasing, only the enemy is the goal
         trap_BotEmptyGoalStack(bs->gs);
         //go chase the enemy
         AIEnter_Battle_Chase(bs, "battle retreat: wants to chase");
         return qfalse;
     }
     //update the last time the enemy was visible
     if (BotEntityVisible(bs->entitynum, bs->eye, bs->viewangles, 360, bs->enemy)) {
         bs->enemyvisible_time = FloatTime();
         VectorCopy(entinfo.origin, target);
         // if not a player enemy
         if (bs->enemy >= MAX_CLIENTS) {
 #ifdef MISSIONPACK
             // if attacking an obelisk
             if ( bs->enemy == redobelisk.entitynum ||
                 bs->enemy == blueobelisk.entitynum ) {
                 target[2] += 16;
             }
 #endif
         }
         //update the reachability area and origin if possible
         areanum = BotPointAreaNum(target);
         if (areanum && trap_AAS_AreaReachability(areanum)) {
             VectorCopy(target, bs->lastenemyorigin);
             bs->lastenemyareanum = areanum;
         }
     }
     //if the enemy is NOT visible for 4 seconds
     if (bs->enemyvisible_time < FloatTime() - 4) {
         AIEnter_Seek_LTG(bs, "battle retreat: lost enemy");
         return qfalse;
     }
     //else if the enemy is NOT visible
     else if (bs->enemyvisible_time < FloatTime()) {
         //if there is another enemy
         if (BotFindEnemy(bs, -1)) {
             AIEnter_Battle_Fight(bs, "battle retreat: another enemy");
             return qfalse;
         }
     }
     //
     BotTeamGoals(bs, qtrue);
     //use holdable items
     BotBattleUseItems(bs);
     //get the current long term goal while retreating
     if (!BotLongTermGoal(bs, bs->tfl, qtrue, &goal)) {
         AIEnter_Battle_SuicidalFight(bs, "battle retreat: no way out");
         return qfalse;
     }
     //check for nearby goals periodicly
     if (bs->check_time < FloatTime()) {
         bs->check_time = FloatTime() + 1;
         range = 150;
 #ifdef CTF
         if (gametype == GT_CTF) {
             //if carrying a flag the bot shouldn't be distracted too much
             if (BotCTFCarryingFlag(bs))
                 range = 50;
         }
 #endif //CTF
 #ifdef MISSIONPACK
         else if (gametype == GT_1FCTF) {
             if (Bot1FCTFCarryingFlag(bs))
                 range = 50;
         }
         else if (gametype == GT_HARVESTER) {
             if (BotHarvesterCarryingCubes(bs))
                 range = 80;
         }
 #endif
         //
         if (BotNearbyGoal(bs, bs->tfl, &goal, range)) {
             trap_BotResetLastAvoidReach(bs->ms);
             //time the bot gets to pick up the nearby goal item
             bs->nbg_time = FloatTime() + range / 100 + 1;
             AIEnter_Battle_NBG(bs, "battle retreat: nbg");
             return qfalse;
         }
     }
     //initialize the movement state
     BotSetupForMovement(bs);
     //move towards the goal
     trap_BotMoveToGoal(&moveresult, bs->ms, &goal, bs->tfl);
     //if the movement failed
     if (moveresult.failure) {
         //reset the avoid reach, otherwise bot is stuck in current area
         trap_BotResetAvoidReach(bs->ms);
         //BotAI_Print(PRT_MESSAGE, "movement failure %d\n", moveresult.traveltype);
         bs->ltg_time = 0;
     }
     //
     BotAIBlocked(bs, &moveresult, qfalse);
     //choose the best weapon to fight with
     BotChooseWeapon(bs);
     //if the view is fixed for the movement
     if (moveresult.flags & (MOVERESULT_MOVEMENTVIEW|MOVERESULT_SWIMVIEW)) {
         VectorCopy(moveresult.ideal_viewangles, bs->ideal_viewangles);
     }
     else if (!(moveresult.flags & MOVERESULT_MOVEMENTVIEWSET)
                 && !(bs->flags & BFL_IDEALVIEWSET) ) {
         attack_skill = trap_Characteristic_BFloat(bs->character, CHARACTERISTIC_ATTACK_SKILL, 0, 1);
         //if the bot is skilled enough
         if (attack_skill > 0.3) {
             BotAimAtEnemy(bs);
         }
         else {
             if (trap_BotMovementViewTarget(bs->ms, &goal, bs->tfl, 300, target)) {
                 VectorSubtract(target, bs->origin, dir);
                 vectoangles(dir, bs->ideal_viewangles);
             }
             else {
                 vectoangles(moveresult.movedir, bs->ideal_viewangles);
             }
             bs->ideal_viewangles[2] *= 0.5;
         }
     }
     //if the weapon is used for the bot movement
     if (moveresult.flags & MOVERESULT_MOVEMENTWEAPON) bs->weaponnum = moveresult.weapon;
     //attack the enemy if possible
     BotCheckAttack(bs);
     //
     return qtrue;
 }
Referenced by AIEnter_Battle_Retreat().
AINode_Intermission()
int AINode_Intermission (bot_state_t * bs)
Definition at line 1147 of file ai_dmnet.c.
{
     //if the intermission ended
     if (!BotIntermission(bs)) {
         if (BotChat_StartLevel(bs)) {
             bs->stand_time = FloatTime() + BotChatTime(bs);
         }
         else {
             bs->stand_time = FloatTime() + 2;
         }
         AIEnter_Stand(bs, "intermission: chat");
     }
     return qtrue;
 }
Referenced by AIEnter_Intermission().
AINode_Observer()
int AINode_Observer (bot_state_t * bs)
Definition at line 1178 of file ai_dmnet.c.
{
     //if the bot left observer mode
     if (!BotIsObserver(bs)) {
         AIEnter_Stand(bs, "observer: left observer");
     }
     return qtrue;
 }
Referenced by AIEnter_Observer().
AINode_Respawn()
int AINode_Respawn (bot_state_t * bs)
Definition at line 1261 of file ai_dmnet.c.
{
     // if waiting for the actual respawn
     if (bs->respawn_wait) {
         if (!BotIsDead(bs)) {
             AIEnter_Seek_LTG(bs, "respawn: respawned");
         }
         else {
             trap_EA_Respawn(bs->client);
         }
     }
     else if (bs->respawn_time < FloatTime()) {
         // wait until respawned
         bs->respawn_wait = qtrue;
         // elementary action respawn
         trap_EA_Respawn(bs->client);
         //
         if (bs->respawnchat_time) {
             trap_BotEnterChat(bs->cs, 0, bs->chatto);
             bs->enemy = -1;
         }
     }
     if (bs->respawnchat_time && bs->respawnchat_time < FloatTime() - 0.5) {
         trap_EA_Talk(bs->client);
     }
     //
     return qtrue;
 }
Referenced by AIEnter_Respawn().
AINode_Seek_ActivateEntity()
int AINode_Seek_ActivateEntity (bot_state_t * bs)
Definition at line 1448 of file ai_dmnet.c.
{
     bot_goal_t *goal;
     vec3_t target, dir, ideal_viewangles;
     bot_moveresult_t moveresult;
     int targetvisible;
     bsp_trace_t bsptrace;
     aas_entityinfo_t entinfo;
     if (BotIsObserver(bs)) {
         BotClearActivateGoalStack(bs);
         AIEnter_Observer(bs, "active entity: observer");
         return qfalse;
     }
     //if in the intermission
     if (BotIntermission(bs)) {
         BotClearActivateGoalStack(bs);
         AIEnter_Intermission(bs, "activate entity: intermission");
         return qfalse;
     }
     //respawn if dead
     if (BotIsDead(bs)) {
         BotClearActivateGoalStack(bs);
         AIEnter_Respawn(bs, "activate entity: bot dead");
         return qfalse;
     }
     //
     bs->tfl = TFL_DEFAULT;
     if (bot_grapple.integer) bs->tfl |= TFL_GRAPPLEHOOK;
     // if in lava or slime the bot should be able to get out
     if (BotInLavaOrSlime(bs)) bs->tfl |= TFL_LAVA|TFL_SLIME;
     // map specific code
     BotMapScripts(bs);
     // no enemy
     bs->enemy = -1;
     // if the bot has no activate goal
     if (!bs->activatestack) {
         BotClearActivateGoalStack(bs);
         AIEnter_Seek_NBG(bs, "activate entity: no goal");
         return qfalse;
     }
     //
     goal = &bs->activatestack->goal;
     // initialize target being visible to false
     targetvisible = qfalse;
     // if the bot has to shoot at a target to activate something
     if (bs->activatestack->shoot) {
         //
         BotAI_Trace(&bsptrace, bs->eye, NULL, NULL, bs->activatestack->target, bs->entitynum, MASK_SHOT);
         // if the shootable entity is visible from the current position
         if (bsptrace.fraction >= 1.0 || bsptrace.ent == goal->entitynum) {
             targetvisible = qtrue;
             // if holding the right weapon
             if (bs->cur_ps.weapon == bs->activatestack->weapon) {
                 VectorSubtract(bs->activatestack->target, bs->eye, dir);
                 vectoangles(dir, ideal_viewangles);
                 // if the bot is pretty close with its aim
                 if (InFieldOfVision(bs->viewangles, 20, ideal_viewangles)) {
                     trap_EA_Attack(bs->client);
                 }
             }
         }
     }
     // if the shoot target is visible
     if (targetvisible) {
         // get the entity info of the entity the bot is shooting at
         BotEntityInfo(goal->entitynum, &entinfo);
         // if the entity the bot shoots at moved
         if (!VectorCompare(bs->activatestack->origin, entinfo.origin)) {
 #ifdef DEBUG
             BotAI_Print(PRT_MESSAGE, "hit shootable button or trigger\n");
 #endif //DEBUG
             bs->activatestack->time = 0;
         }
         // if the activate goal has been activated or the bot takes too long
         if (bs->activatestack->time < FloatTime()) {
             BotPopFromActivateGoalStack(bs);
             // if there are more activate goals on the stack
             if (bs->activatestack) {
                 bs->activatestack->time = FloatTime() + 10;
                 return qfalse;
             }
             AIEnter_Seek_NBG(bs, "activate entity: time out");
             return qfalse;
         }
         memset(&moveresult, 0, sizeof(bot_moveresult_t));
     }
     else {
         // if the bot has no goal
         if (!goal) {
             bs->activatestack->time = 0;
         }
         // if the bot does not have a shoot goal
         else if (!bs->activatestack->shoot) {
             //if the bot touches the current goal
             if (trap_BotTouchingGoal(bs->origin, goal)) {
 #ifdef DEBUG
                 BotAI_Print(PRT_MESSAGE, "touched button or trigger\n");
 #endif //DEBUG
                 bs->activatestack->time = 0;
             }
         }
         // if the activate goal has been activated or the bot takes too long
         if (bs->activatestack->time < FloatTime()) {
             BotPopFromActivateGoalStack(bs);
             // if there are more activate goals on the stack
             if (bs->activatestack) {
                 bs->activatestack->time = FloatTime() + 10;
                 return qfalse;
             }
             AIEnter_Seek_NBG(bs, "activate entity: activated");
             return qfalse;
         }
         //predict obstacles
         if (BotAIPredictObstacles(bs, goal))
             return qfalse;
         //initialize the movement state
         BotSetupForMovement(bs);
         //move towards the goal
         trap_BotMoveToGoal(&moveresult, bs->ms, goal, bs->tfl);
         //if the movement failed
         if (moveresult.failure) {
             //reset the avoid reach, otherwise bot is stuck in current area
             trap_BotResetAvoidReach(bs->ms);
             //
             bs->activatestack->time = 0;
         }
         //check if the bot is blocked
         BotAIBlocked(bs, &moveresult, qtrue);
     }
     //
     BotClearPath(bs, &moveresult);
     // if the bot has to shoot to activate
     if (bs->activatestack->shoot) {
         // if the view angles aren't yet used for the movement
         if (!(moveresult.flags & MOVERESULT_MOVEMENTVIEW)) {
             VectorSubtract(bs->activatestack->target, bs->eye, dir);
             vectoangles(dir, moveresult.ideal_viewangles);
             moveresult.flags |= MOVERESULT_MOVEMENTVIEW;
         }
         // if there's no weapon yet used for the movement
         if (!(moveresult.flags & MOVERESULT_MOVEMENTWEAPON)) {
             moveresult.flags |= MOVERESULT_MOVEMENTWEAPON;
             //
             bs->activatestack->weapon = BotSelectActivateWeapon(bs);
             if (bs->activatestack->weapon == -1) {
                 //FIXME: find a decent weapon first
                 bs->activatestack->weapon = 0;
             }
             moveresult.weapon = bs->activatestack->weapon;
         }
     }
     // if the ideal view angles are set for movement
     if (moveresult.flags & (MOVERESULT_MOVEMENTVIEWSET|MOVERESULT_MOVEMENTVIEW|MOVERESULT_SWIMVIEW)) {
         VectorCopy(moveresult.ideal_viewangles, bs->ideal_viewangles);
     }
     // if waiting for something
     else if (moveresult.flags & MOVERESULT_WAITING) {
         if (random() < bs->thinktime * 0.8) {
             BotRoamGoal(bs, target);
             VectorSubtract(target, bs->origin, dir);
             vectoangles(dir, bs->ideal_viewangles);
             bs->ideal_viewangles[2] *= 0.5;
         }
     }
     else if (!(bs->flags & BFL_IDEALVIEWSET)) {
         if (trap_BotMovementViewTarget(bs->ms, goal, bs->tfl, 300, target)) {
             VectorSubtract(target, bs->origin, dir);
             vectoangles(dir, bs->ideal_viewangles);
         }
         else {
             vectoangles(moveresult.movedir, bs->ideal_viewangles);
         }
         bs->ideal_viewangles[2] *= 0.5;
     }
     // if the weapon is used for the bot movement
     if (moveresult.flags & MOVERESULT_MOVEMENTWEAPON)
         bs->weaponnum = moveresult.weapon;
     // if there is an enemy
     if (BotFindEnemy(bs, -1)) {
         if (BotWantsToRetreat(bs)) {
             //keep the current long term goal and retreat
             AIEnter_Battle_NBG(bs, "activate entity: found enemy");
         }
         else {
             trap_BotResetLastAvoidReach(bs->ms);
             //empty the goal stack
             trap_BotEmptyGoalStack(bs->gs);
             //go fight
             AIEnter_Battle_Fight(bs, "activate entity: found enemy");
         }
         BotClearActivateGoalStack(bs);
     }
     return qtrue;
 }
Referenced by AIEnter_Seek_ActivateEntity().
AINode_Seek_LTG()
int AINode_Seek_LTG (bot_state_t * bs)
Definition at line 1800 of file ai_dmnet.c.
 {
     bot_goal_t goal;
     vec3_t target, dir;
     bot_moveresult_t moveresult;
     int range;
     //char buf[128];
     //bot_goal_t tmpgoal;
     if (BotIsObserver(bs)) {
         AIEnter_Observer(bs, "seek ltg: observer");
         return qfalse;
     }
     //if in the intermission
     if (BotIntermission(bs)) {
         AIEnter_Intermission(bs, "seek ltg: intermission");
         return qfalse;
     }
     //respawn if dead
     if (BotIsDead(bs)) {
         AIEnter_Respawn(bs, "seek ltg: bot dead");
         return qfalse;
     }
     //
     if (BotChat_Random(bs)) {
         bs->stand_time = FloatTime() + BotChatTime(bs);
         AIEnter_Stand(bs, "seek ltg: random chat");
         return qfalse;
     }
     //
     bs->tfl = TFL_DEFAULT;
     if (bot_grapple.integer) bs->tfl |= TFL_GRAPPLEHOOK;
     //if in lava or slime the bot should be able to get out
     if (BotInLavaOrSlime(bs)) bs->tfl |= TFL_LAVA|TFL_SLIME;
     //
     if (BotCanAndWantsToRocketJump(bs)) {
         bs->tfl |= TFL_ROCKETJUMP;
     }
     //map specific code
     BotMapScripts(bs);
     //no enemy
     bs->enemy = -1;
     //
     if (bs->killedenemy_time > FloatTime() - 2) {
         if (random() < bs->thinktime * 1) {
             trap_EA_Gesture(bs->client);
         }
     }
     //if there is an enemy
     if (BotFindEnemy(bs, -1)) {
         if (BotWantsToRetreat(bs)) {
             //keep the current long term goal and retreat
             AIEnter_Battle_Retreat(bs, "seek ltg: found enemy");
             return qfalse;
         }
         else {
             trap_BotResetLastAvoidReach(bs->ms);
             //empty the goal stack
             trap_BotEmptyGoalStack(bs->gs);
             //go fight
             AIEnter_Battle_Fight(bs, "seek ltg: found enemy");
             return qfalse;
         }
     }
     //
     BotTeamGoals(bs, qfalse);
     //get the current long term goal
     if (!BotLongTermGoal(bs, bs->tfl, qfalse, &goal)) {
         return qtrue;
     }
     //check for nearby goals periodicly
     if (bs->check_time < FloatTime()) {
         bs->check_time = FloatTime() + 0.5;
         //check if the bot wants to camp
         BotWantsToCamp(bs);
         //
         if (bs->ltgtype == LTG_DEFENDKEYAREA) range = 400;
         else range = 150;
         //
 #ifdef CTF
         if (gametype == GT_CTF) {
             //if carrying a flag the bot shouldn't be distracted too much
             if (BotCTFCarryingFlag(bs))
                 range = 50;
         }
 #endif //CTF
 #ifdef MISSIONPACK
         else if (gametype == GT_1FCTF) {
             if (Bot1FCTFCarryingFlag(bs))
                 range = 50;
         }
         else if (gametype == GT_HARVESTER) {
             if (BotHarvesterCarryingCubes(bs))
                 range = 80;
         }
 #endif
         //
         if (BotNearbyGoal(bs, bs->tfl, &goal, range)) {
             trap_BotResetLastAvoidReach(bs->ms);
             //get the goal at the top of the stack
             //trap_BotGetTopGoal(bs->gs, &tmpgoal);
             //trap_BotGoalName(tmpgoal.number, buf, 144);
             //BotAI_Print(PRT_MESSAGE, "new nearby goal %s\n", buf);
             //time the bot gets to pick up the nearby goal item
             bs->nbg_time = FloatTime() + 4 + range * 0.01;
             AIEnter_Seek_NBG(bs, "ltg seek: nbg");
             return qfalse;
         }
     }
     //predict obstacles
     if (BotAIPredictObstacles(bs, &goal))
         return qfalse;
     //initialize the movement state
     BotSetupForMovement(bs);
     //move towards the goal
     trap_BotMoveToGoal(&moveresult, bs->ms, &goal, bs->tfl);
     //if the movement failed
     if (moveresult.failure) {
         //reset the avoid reach, otherwise bot is stuck in current area
         trap_BotResetAvoidReach(bs->ms);
         //BotAI_Print(PRT_MESSAGE, "movement failure %d\n", moveresult.traveltype);
         bs->ltg_time = 0;
     }
     //
     BotAIBlocked(bs, &moveresult, qtrue);
     //
     BotClearPath(bs, &moveresult);
     //if the viewangles are used for the movement
     if (moveresult.flags & (MOVERESULT_MOVEMENTVIEWSET|MOVERESULT_MOVEMENTVIEW|MOVERESULT_SWIMVIEW)) {
         VectorCopy(moveresult.ideal_viewangles, bs->ideal_viewangles);
     }
     //if waiting for something
     else if (moveresult.flags & MOVERESULT_WAITING) {
         if (random() < bs->thinktime * 0.8) {
             BotRoamGoal(bs, target);
             VectorSubtract(target, bs->origin, dir);
             vectoangles(dir, bs->ideal_viewangles);
             bs->ideal_viewangles[2] *= 0.5;
         }
     }
     else if (!(bs->flags & BFL_IDEALVIEWSET)) {
         if (trap_BotMovementViewTarget(bs->ms, &goal, bs->tfl, 300, target)) {
             VectorSubtract(target, bs->origin, dir);
             vectoangles(dir, bs->ideal_viewangles);
         }
         //FIXME: look at cluster portals?
         else if (VectorLengthSquared(moveresult.movedir)) {
             vectoangles(moveresult.movedir, bs->ideal_viewangles);
         }
         else if (random() < bs->thinktime * 0.8) {
             BotRoamGoal(bs, target);
             VectorSubtract(target, bs->origin, dir);
             vectoangles(dir, bs->ideal_viewangles);
             bs->ideal_viewangles[2] *= 0.5;
         }
         bs->ideal_viewangles[2] *= 0.5;
     }
     //if the weapon is used for the bot movement
     if (moveresult.flags & MOVERESULT_MOVEMENTWEAPON) bs->weaponnum = moveresult.weapon;
     //
     return qtrue;
 }
Referenced by AIEnter_Seek_LTG(), and BotAIBlocked().
AINode_Seek_NBG()
int AINode_Seek_NBG (bot_state_t * bs)
Definition at line 1667 of file ai_dmnet.c.
{
     bot_goal_t goal;
     vec3_t target, dir;
     bot_moveresult_t moveresult;
     if (BotIsObserver(bs)) {
         AIEnter_Observer(bs, "seek nbg: observer");
         return qfalse;
     }
     //if in the intermission
     if (BotIntermission(bs)) {
         AIEnter_Intermission(bs, "seek nbg: intermision");
         return qfalse;
     }
     //respawn if dead
     if (BotIsDead(bs)) {
         AIEnter_Respawn(bs, "seek nbg: bot dead");
         return qfalse;
     }
     //
     bs->tfl = TFL_DEFAULT;
     if (bot_grapple.integer) bs->tfl |= TFL_GRAPPLEHOOK;
     //if in lava or slime the bot should be able to get out
     if (BotInLavaOrSlime(bs)) bs->tfl |= TFL_LAVA|TFL_SLIME;
     //
     if (BotCanAndWantsToRocketJump(bs)) {
         bs->tfl |= TFL_ROCKETJUMP;
     }
     //map specific code
     BotMapScripts(bs);
     //no enemy
     bs->enemy = -1;
     //if the bot has no goal
     if (!trap_BotGetTopGoal(bs->gs, &goal)) bs->nbg_time = 0;
     //if the bot touches the current goal
     else if (BotReachedGoal(bs, &goal)) {
         BotChooseWeapon(bs);
         bs->nbg_time = 0;
     }
     //
     if (bs->nbg_time < FloatTime()) {
         //pop the current goal from the stack
         trap_BotPopGoal(bs->gs);
         //check for new nearby items right away
         //NOTE: we canNOT reset the check_time to zero because it would create an endless loop of node switches
         bs->check_time = FloatTime() + 0.05;
         //go back to seek ltg
         AIEnter_Seek_LTG(bs, "seek nbg: time out");
         return qfalse;
     }
     //predict obstacles
     if (BotAIPredictObstacles(bs, &goal))
         return qfalse;
     //initialize the movement state
     BotSetupForMovement(bs);
     //move towards the goal
     trap_BotMoveToGoal(&moveresult, bs->ms, &goal, bs->tfl);
     //if the movement failed
     if (moveresult.failure) {
         //reset the avoid reach, otherwise bot is stuck in current area
         trap_BotResetAvoidReach(bs->ms);
         bs->nbg_time = 0;
     }
     //check if the bot is blocked
     BotAIBlocked(bs, &moveresult, qtrue);
     //
     BotClearPath(bs, &moveresult);
     //if the viewangles are used for the movement
     if (moveresult.flags & (MOVERESULT_MOVEMENTVIEWSET|MOVERESULT_MOVEMENTVIEW|MOVERESULT_SWIMVIEW)) {
         VectorCopy(moveresult.ideal_viewangles, bs->ideal_viewangles);
     }
     //if waiting for something
     else if (moveresult.flags & MOVERESULT_WAITING) {
         if (random() < bs->thinktime * 0.8) {
             BotRoamGoal(bs, target);
             VectorSubtract(target, bs->origin, dir);
             vectoangles(dir, bs->ideal_viewangles);
             bs->ideal_viewangles[2] *= 0.5;
         }
     }
     else if (!(bs->flags & BFL_IDEALVIEWSET)) {
         if (!trap_BotGetSecondGoal(bs->gs, &goal)) trap_BotGetTopGoal(bs->gs, &goal);
         if (trap_BotMovementViewTarget(bs->ms, &goal, bs->tfl, 300, target)) {
             VectorSubtract(target, bs->origin, dir);
             vectoangles(dir, bs->ideal_viewangles);
         }
         //FIXME: look at cluster portals?
         else vectoangles(moveresult.movedir, bs->ideal_viewangles);
         bs->ideal_viewangles[2] *= 0.5;
     }
     //if the weapon is used for the bot movement
     if (moveresult.flags & MOVERESULT_MOVEMENTWEAPON) bs->weaponnum = moveresult.weapon;
     //if there is an enemy
     if (BotFindEnemy(bs, -1)) {
         if (BotWantsToRetreat(bs)) {
             //keep the current long term goal and retreat
             AIEnter_Battle_NBG(bs, "seek nbg: found enemy");
         }
         else {
             trap_BotResetLastAvoidReach(bs->ms);
             //empty the goal stack
             trap_BotEmptyGoalStack(bs->gs);
             //go fight
             AIEnter_Battle_Fight(bs, "seek nbg: found enemy");
         }
     }
     return qtrue;
 }
Referenced by AIEnter_Seek_NBG(), and BotAIBlocked().
AINode_Stand()
int AINode_Stand (bot_state_t * bs)
Definition at line 1202 of file ai_dmnet.c.
{
     //if the bot's health decreased
     if (bs->lastframe_health > bs->inventory[INVENTORY_HEALTH]) {
         if (BotChat_HitTalking(bs)) {
             bs->standfindenemy_time = FloatTime() + BotChatTime(bs) + 0.1;
             bs->stand_time = FloatTime() + BotChatTime(bs) + 0.1;
         }
     }
     if (bs->standfindenemy_time < FloatTime()) {
         if (BotFindEnemy(bs, -1)) {
             AIEnter_Battle_Fight(bs, "stand: found enemy");
             return qfalse;
         }
         bs->standfindenemy_time = FloatTime() + 1;
     }
     // put up chat icon
     trap_EA_Talk(bs->client);
     // when done standing
     if (bs->stand_time < FloatTime()) {
         trap_BotEnterChat(bs->cs, 0, bs->chatto);
         AIEnter_Seek_LTG(bs, "stand: time out");
         return qfalse;
     }
     //
     return qtrue;
 }
Referenced by AIEnter_Stand(), and BotCheckConsoleMessages().
BotDumpNodeSwitches()
void BotDumpNodeSwitches (bot_state_t * bs)
Definition at line 81 of file ai_dmnet.c.
{
     int i;
     char netname[MAX_NETNAME];
     ClientName(bs->client, netname, sizeof(netname));
     BotAI_Print(PRT_MESSAGE, "%s at %1.1f switched more than %d AI nodes\n", netname, FloatTime(), MAX_NODESWITCHES);
     for (i = 0; i < numnodeswitches; i++) {
         BotAI_Print(PRT_MESSAGE, "%s", nodeswitch[i]);
     }
     BotAI_Print(PRT_FATAL, "");
 }
Referenced by BotDeathmatchAI().
BotResetNodeSwitches()
void BotResetNodeSwitches (void)
Definition at line 72 of file ai_dmnet.c.
{
     numnodeswitches = 0;
 }
Referenced by BotDeathmatchAI().