ioquake3 doxygen: C:/entry/dev/ioquake3/code/qcommon/vm_armv7l.c File Reference
vm_armv7l.c File Reference
#include <sys/types.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <time.h>
#include <stddef.h>
#include <sys/stat.h>
#include <fcntl.h>
#include "vm_local.h"
Macros
#define R0 0
#define R1 1
#define R2 2
#define R3 3
#define R4 4
#define R12 12
#define FP 11
#define SP 13
#define LR 14
#define PC 15
#define APSR_nzcv 15
#define S14 14
#define S15 15
#define rOPSTACK 5
#define rOPSTACKBASE 6
#define rCODEBASE 7
#define rPSTACK 8
#define rDATABASE 9
#define rDATAMASK 10
#define bit(x) (1<<x)
#define DIE(reason, args...)
#define opImm0 0x0000 /* no immediate */
#define opImm1 0x0001 /* 1 byte immadiate value after opcode */
#define opImm4 0x0002 /* 4 bytes immediate value after opcode */
#define opRet0 0x0000 /* returns nothing */
#define opRetI 0x0004 /* returns integer */
#define opRetF 0x0008 /* returns float */
#define opRetIF (opRetI | opRetF) /* returns integer or float */
#define opArg0 0x0000 /* requires nothing */
#define opArgI 0x0010 /* requires integer(s) */
#define opArgF 0x0020 /* requires float(s) */
#define opArgIF (opArgI | opArgF) /* requires integer or float */
#define opArg2I 0x0040 /* requires second argument, integer */
#define opArg2F 0x0080 /* requires second argument, float */
#define opArg2IF (opArg2I | opArg2F) /* requires second argument, integer or float */
#define NOTIMPL(x) do { Com_Printf(S_COLOR_RED "instruction not implemented: %x\n", x); vm->compiled = qfalse; return; } while(0)
#define emit(isn) _emit(vm, isn, pass)
#define PREINDEX (1<<24)
#define rASR(i, reg) (0b10<<5 | ((i&31)<<7) | reg)
#define rLSL(i, reg) (0b00<<5 | ((i&31)<<7) | reg)
#define rLSR(i, reg) (0b01<<5 | ((i&31)<<7) | reg)
#define rROR(i, reg) (0b11<<5 | ((i&31)<<7) | reg)
#define EQ (0b0000<<28)
#define NE (0b0001<<28)
#define CS (0b0010<<28)
#define HS CS
#define CC (0b0011<<28)
#define LO CC
#define MI (0b0100<<28)
#define PL (0b0101<<28)
#define VS (0b0110<<28)
#define VC (0b0111<<28)
#define HI (0b1000<<28)
#define LS (0b1001<<28)
#define GE (0b1010<<28)
#define LT (0b1011<<28)
#define GT (0b1100<<28)
#define LE (0b1101<<28)
#define AL (0b1110<<28)
#define cond(what, op) (what | (op&~AL))
#define BKPT(v) (AL | 0b10010<<20 | ((v&~0xF)<<4) | 0b0111<<4 | (v&0xF))
#define YIELD (0b110010<<20 | 0b1111<<12 | 1)
#define NOP cond(AL, YIELD)
#define ANDi(dst, src, i) (AL | (0b001<<25) | (0b00000<<20) | (src<<16) | (dst<<12) | rimm(i))
#define EORi(dst, src, i) (AL | (0b001<<25) | (0b00010<<20) | (src<<16) | (dst<<12) | rimm(i))
#define SUBi(dst, src, i) (AL | (0b001<<25) | (0b00100<<20) | (src<<16) | (dst<<12) | rimm(i))
#define RSBi(dst, src, i) (AL | (0b001<<25) | (0b00110<<20) | (src<<16) | (dst<<12) | rimm(i))
#define ADDi(dst, src, i) (AL | (0b001<<25) | (0b01000<<20) | (src<<16) | (dst<<12) | rimm(i))
#define ADCi(dst, src, i) (AL | (0b001<<25) | (0b01010<<20) | (src<<16) | (dst<<12) | rimm(i))
#define SBCi(dst, src, i) (AL | (0b001<<25) | (0b01100<<20) | (src<<16) | (dst<<12) | rimm(i))
#define RSCi(dst, src, i) (AL | (0b001<<25) | (0b01110<<20) | (src<<16) | (dst<<12) | rimm(i))
#define ORRi(dst, src, i) (AL | (0b001<<25) | (0b11000<<20) | (src<<16) | (dst<<12) | rimm(i))
#define MOVi(dst, i) (AL | (0b001<<25) | (0b11010<<20) | (dst<<12) | rimm(i))
#define BICi(dst, src, i) (AL | (0b001<<25) | (0b11100<<20) | (src<<16) | (dst<<12) | rimm(i))
#define MVNi(dst, i) (AL | (0b001<<25) | (0b11110<<20) | (dst<<12) | rimm(i))
#define MOVW(dst, i) (AL | (0b11<<24) | ((((i)>>12)&0xF)<<16) | (dst<<12) | ((i)&((1<<12)-1)))
#define MOVT(dst, i) (AL | (0b11<<24) | (0b0100<<20) | ((((i)>>12)&0xF)<<16) | (dst<<12) | ((i)&((1<<12)-1)))
#define TSTi(src, i) (AL | (0b001<<25) | (0b10001<<20) | (src<<16) | rimm(i))
#define TEQi(src, i) (AL | (0b001<<25) | (0b10011<<20) | (src<<16) | rimm(i))
#define CMPi(src, i) (AL | (0b001<<25) | (0b10101<<20) | (src<<16) | rimm(i))
#define CMNi(src, i) (AL | (0b001<<25) | (0b10111<<20) | (src<<16) | rimm(i))
#define ANDSi(dst, src, i) (ANDi(dst, src, i) | (1<<20))
#define EORSi(dst, src, i) (EORi(dst, src, i) | (1<<20))
#define SUBSi(dst, src, i) (SUBi(dst, src, i) | (1<<20))
#define RSBSi(dst, src, i) (RSBi(dst, src, i) | (1<<20))
#define ADDSi(dst, src, i) (ADDi(dst, src, i) | (1<<20))
#define ADCSi(dst, src, i) (ADCi(dst, src, i) | (1<<20))
#define SBCSi(dst, src, i) (SBCi(dst, src, i) | (1<<20))
#define RSCSi(dst, src, i) (RSCi(dst, src, i) | (1<<20))
#define ORRSi(dst, src, i) (ORRi(dst, src, i) | (1<<20))
#define MOVSi(dst, i) (MOVi(dst, i) | (1<<20))
#define BICSi(dst, src, i) (BICi(dst, src, i) | (1<<20))
#define MVNSi(dst, i) (MVNi(dst, src, i) | (1<<20))
#define AND(dst, src, reg) (AL | (0b000<<25) | (0b00000<<20) | (src<<16) | (dst<<12) | reg)
#define EOR(dst, src, reg) (AL | (0b000<<25) | (0b00010<<20) | (src<<16) | (dst<<12) | reg)
#define SUB(dst, src, reg) (AL | (0b000<<25) | (0b00100<<20) | (src<<16) | (dst<<12) | reg)
#define RSB(dst, src, reg) (AL | (0b000<<25) | (0b00110<<20) | (src<<16) | (dst<<12) | reg)
#define ADD(dst, src, reg) (AL | (0b000<<25) | (0b01000<<20) | (src<<16) | (dst<<12) | reg)
#define ADC(dst, src, reg) (AL | (0b000<<25) | (0b01010<<20) | (src<<16) | (dst<<12) | reg)
#define SBC(dst, src, reg) (AL | (0b000<<25) | (0b01100<<20) | (src<<16) | (dst<<12) | reg)
#define RSC(dst, src, reg) (AL | (0b000<<25) | (0b01110<<20) | (src<<16) | (dst<<12) | reg)
#define ORR(dst, src, reg) (AL | (0b000<<25) | (0b11000<<20) | (src<<16) | (dst<<12) | reg)
#define MOV(dst, src) (AL | (0b000<<25) | (0b11010<<20) | (dst<<12) | src)
#define LSL(dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0001<<4) | src)
#define LSR(dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0011<<4) | src)
#define ASR(dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0101<<4) | src)
#define ROR(dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0111<<4) | src)
#define LSLi(dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b000<<4) | src)
#define LSRi(dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b010<<4) | src)
#define ASRi(dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b100<<4) | src)
#define RORi(dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b110<<4) | src)
#define RRX(dst, src) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (0b110<<4) | src)
#define BIC(dst, src, reg) (AL | (0b000<<25) | (0b11100<<20) | (src<<16) | (dst<<12) | reg)
#define MVN(dst, reg) (AL | (0b000<<25) | (0b11110<<20) | (dst<<12) | reg)
#define TST(src, reg) (AL | (0b000<<25) | (0b10001<<20) | (src<<16) | reg)
#define TEQ(src, reg) (AL | (0b000<<25) | (0b10011<<20) | (src<<16) | reg)
#define CMP(src, reg) (AL | (0b000<<25) | (0b10101<<20) | (src<<16) | reg)
#define CMN(src, reg) (AL | (0b000<<25) | (0b10111<<20) | (src<<16) | reg)
#define LDRa(dst, base, off) (AL | (0b011<<25) | (0b1100<<21) | (1<<20) | base<<16 | dst<<12 | off)
#define LDRx(dst, base, off) (AL | (0b011<<25) | (0b1000<<21) | (1<<20) | base<<16 | dst<<12 | off)
#define LDRai(dst, base, off) (AL | (0b010<<25) | (0b1100<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
#define LDRxi(dst, base, off) (AL | (0b010<<25) | (0b1000<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
#define LDRxiw(dst, base, off) (AL | (0b010<<25) | (0b1001<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
#define LDRTa(dst, base, off) (AL | (0b011<<25) | (0b0101<<21) | (1<<20) | base<<16 | dst<<12 | off)
#define LDRTx(dst, base, off) (AL | (0b011<<25) | (0b0001<<21) | (1<<20) | base<<16 | dst<<12 | off)
#define LDRTai(dst, base, off) (AL | (0b010<<25) | (0b0101<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
#define LDRTxi(dst, base, off) (AL | (0b010<<25) | (0b0001<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
#define LDRBa(dst, base, off) (AL | (0b011<<25) | (0b1110<<21) | (1<<20) | base<<16 | dst<<12 | off)
#define LDRSBai(dst, base, off) (AL | (0b000<<25) | (0b0110<<21) | (1<<20) | base<<16 | dst<<12 | ((off&0xF0)<<4)|0b1101<<4|(off&0x0F))
#define STRBa(dst, base, off) (AL | (0b011<<25) | (0b1110<<21) | (0<<20) | base<<16 | dst<<12 | off)
#define LDRHa(dst, base, off) (AL | (0b000<<25) | (0b1100<<21) | (1<<20) | base<<16 | dst<<12 | (0b1011<<4) | off)
#define LDRSHai(dst, base, off) (AL | (0b000<<25) | (0b1110<<21) | (1<<20) | base<<16 | dst<<12 | ((off&0xF0)<<4)|0b1111<<4|(off&0x0F))
#define STRHa(dst, base, off) (AL | (0b000<<25) | (0b1100<<21) | (0<<20) | base<<16 | dst<<12 | (0b1011<<4) | off)
#define STRa(dst, base, off) (AL | (0b011<<25) | (0b1100<<21) | (0<<20) | base<<16 | dst<<12 | off)
#define STRx(dst, base, off) (AL | (0b011<<25) | (0b1000<<21) | (0<<20) | base<<16 | dst<<12 | off)
#define STRai(dst, base, off) (AL | (0b010<<25) | (0b1100<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
#define STRxi(dst, base, off) (AL | (0b010<<25) | (0b1000<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
#define STRaiw(dst, base, off) (AL | (0b010<<25) | (0b1101<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
#define STRxiw(dst, base, off) (AL | (0b010<<25) | (0b1001<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
#define POP1(reg) (AL | (0b010<<25) | (0b0100<<21) | (1<<20) | SP<<16 | reg<<12 | reg)
#define PUSH1(reg) (AL | (0b010<<25) | (0b1001<<21) | (0<<20) | SP<<16 | reg<<12 | 4)
#define Bi(i) (AL | (0b10)<<26 | (1<<25) /*I*/ | (0<<24) /*L*/ | (i))
#define BLi(i) (AL | (0b10)<<26 | (1<<25) /*I*/ | (1<<24) /*L*/ | (i))
#define BX(reg) (AL | 0b00010010<<20 | 0b1111<<16 | 0b1111<<12 | 0b1111<<8| 0b0001<<4 | reg)
#define BLX(reg) (AL | 0b00010010<<20 | 0b1111<<16 | 0b1111<<12 | 0b1111<<8| 0b0011<<4 | reg)
#define PUSH(mask) (AL | (0b100100<<22) | (0b10<<20) | (0b1101<<16) | mask)
#define PUSH2(r1, r2) (AL | (0b100100<<22) | (0b10<<20) | (0b1101<<16) | 1<<r1 | 1<<r2)
#define POP(mask) (0xe8bd0000|mask)
#define STM(base, regs) (AL | 0b100<<25 | 0<<24/*P*/| 0<<24/*U*/| 0<<24/*S*/| 0<<24/*W*/ | (base<<16) | (regs&~(1<<16)))
#define MUL(op1, op2, op3) (AL | 0b0000000<<21 | (1<<20) /*S*/ | (op1<<16) | (op3<<8) | 0b1001<<4 | (op2))
#define emit_MOVR0i(arg) emit_MOVRxi(R0, arg)
#define emit_MOVRxi(reg, arg)
#define emit_MOVRxi_or_NOP(reg, arg)
#define VMOVass(Vn, Rt) (AL|(0b1110<<24)|(0b000<<21)|(0<<20)| ((Vn>>1)<<16) | (Rt<<12) | (0b1010<<8) | ((Vn&1)<<7) | (1<<4))
#define VMOVssa(Rt, Vn) (AL|(0b1110<<24)|(0b000<<21)|(1<<20)| ((Vn>>1)<<16) | (Rt<<12) | (0b1010<<8) | ((Vn&1)<<7) | (1<<4))
#define _VCVT_F(Vd, Vm, opc2, op) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b111<<19)|(opc2<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|(op<<7)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
#define VCVT_F32_U32(Sd, Sm) _VCVT_F(Sd, Sm, 0b000, 0 /* unsigned */)
#define VCVT_U32_F32(Sd, Sm) _VCVT_F(Sd, Sm, 0b100, 1 /* round zero */)
#define VCVT_F32_S32(Sd, Sm) _VCVT_F(Sd, Sm, 0b000, 1 /* unsigned */)
#define VCVT_S32_F32(Sd, Sm) _VCVT_F(Sd, Sm, 0b101, 1 /* round zero */)
#define VLDRa(Vd, Rn, i) (AL|(0b1101<<24)|1<<23|((Vd&1)<<22)|1<<20|(Rn<<16)|((Vd>>1)<<12)|(0b1010<<8)|off8(i))
#define VSTRa(Vd, Rn, i) (AL|(0b1101<<24)|1<<23|((Vd&1)<<22)|0<<20|(Rn<<16)|((Vd>>1)<<12)|(0b1010<<8)|off8(i))
#define VNEG_F32(Vd, Vm) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b11<<20)|(1<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
#define VADD_F32(Vd, Vn, Vm) (AL|(0b11100<<23)|((Vd&1)<<22)|(0b11<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|((Vn&1)<<7)|(0<<6)|((Vm&1)<<5)|(Vm>>1))
#define VSUB_F32(Vd, Vn, Vm) (AL|(0b11100<<23)|((Vd&1)<<22)|(0b11<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|((Vn&1)<<7)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
#define VMUL_F32(Vd, Vn, Vm) (AL|(0b11100<<23)|((Vd&1)<<22)|(0b10<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101)<<9|(0<<8)|((Vn&1)<<7)|(0<<6)|((Vm&1)<<5)|(Vm>>1))
#define VDIV_F32(Vd, Vn, Vm) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b00<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|((Vn&1)<<7)|(0<<6)|((Vm&1)<<5)|(Vm>>1))
#define _VCMP_F32(Vd, Vm, E) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b11<<20)|((0b0100)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|(E<<7)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
#define VCMP_F32(Vd, Vm) _VCMP_F32(Vd, Vm, 0)
#define VMRS(Rt) (AL|(0b11101111<<20)|(0b0001<<16)|(Rt<<12)|(0b1010<<8)|(1<<4))
#define CHECK_JUMP
#define MAYBE_EMIT_CONST()
#define IJ(comparator)
#define FJ(comparator)
#define printreg(reg) emit(PUSH1(R3)); emit(BLX(reg)); emit(POP1(R3));
#define j_rel(x) (pass?_j_rel(x, pc):0xBAD)
#define OFFSET(i) (pass?(j_rel(codeoffsets[i]-vm->codeLength)):(0xF000000F))
#define get_offset(i) (codeoffsets[i])
#define save_offset(i) (codeoffsets[i] = vm->codeLength)
#define OFF_CODE 0
#define OFF_IMMEDIATES 1
Functions
int __aeabi_idiv (int, int)
unsigned __aeabi_uidiv (unsigned, unsigned)
void __aeabi_idivmod (void)
void __aeabi_uidivmod (void)
static void VM_Destroy_Compiled (vm_t *vm)
static void __attribute__ ((__noreturn__))
static int asmcall (int call, int pstack)
void _emit (vm_t *vm, unsigned isn, int pass)
static unsigned char off8 (unsigned val)
static unsigned short rimm (unsigned val)
static unsigned short can_encode (unsigned val)
static unsigned _j_rel (int x, int pc)
void VM_Compile (vm_t *vm, vmHeader_t *header)
int VM_CallCompiled (vm_t *vm, int *args)
Variables
static const unsigned char vm_opInfo [256]
Macro Definition Documentation
_VCMP_F32
#define _VCMP_F32 (Vd, Vm, E) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b11<<20)|((0b0100)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|(E<<7)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
Definition at line 520 of file vm_armv7l.c.
_VCVT_F
#define _VCVT_F (Vd, Vm, opc2, op) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b111<<19)|(opc2<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|(op<<7)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
Definition at line 498 of file vm_armv7l.c.
ADC
#define ADC (dst, src, reg) (AL | (0b000<<25) | (0b01010<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 389 of file vm_armv7l.c.
ADCi
#define ADCi (dst, src, i) (AL | (0b001<<25) | (0b01010<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 353 of file vm_armv7l.c.
ADCSi
#define ADCSi (dst, src, i) (ADCi(dst, src, i) | (1<<20))
Definition at line 375 of file vm_armv7l.c.
ADD
#define ADD (dst, src, reg) (AL | (0b000<<25) | (0b01000<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 388 of file vm_armv7l.c.
ADDi
#define ADDi (dst, src, i) (AL | (0b001<<25) | (0b01000<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 352 of file vm_armv7l.c.
ADDSi
#define ADDSi (dst, src, i) (ADDi(dst, src, i) | (1<<20))
Definition at line 374 of file vm_armv7l.c.
AL
#define AL (0b1110<<28)
Definition at line 338 of file vm_armv7l.c.
AND
#define AND (dst, src, reg) (AL | (0b000<<25) | (0b00000<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 384 of file vm_armv7l.c.
ANDi
#define ANDi (dst, src, i) (AL | (0b001<<25) | (0b00000<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 348 of file vm_armv7l.c.
ANDSi
#define ANDSi (dst, src, i) (ANDi(dst, src, i) | (1<<20))
Definition at line 370 of file vm_armv7l.c.
APSR_nzcv
#define APSR_nzcv 15
Definition at line 57 of file vm_armv7l.c.
ASR
#define ASR (dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0101<<4) | src)
Definition at line 398 of file vm_armv7l.c.
ASRi
#define ASRi (dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b100<<4) | src)
Definition at line 403 of file vm_armv7l.c.
Bi
#define Bi (i) (AL | (0b10)<<26 | (1<<25) /*I*/ | (0<<24) /*L*/ | (i))
Definition at line 448 of file vm_armv7l.c.
BIC
#define BIC (dst, src, reg) (AL | (0b000<<25) | (0b11100<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 407 of file vm_armv7l.c.
BICi
#define BICi (dst, src, i) (AL | (0b001<<25) | (0b11100<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 359 of file vm_armv7l.c.
BICSi
#define BICSi (dst, src, i) (BICi(dst, src, i) | (1<<20))
Definition at line 381 of file vm_armv7l.c.
bit
#define bit (x) (1<<x)
Definition at line 69 of file vm_armv7l.c.
BKPT
#define BKPT (v) (AL | 0b10010<<20 | ((v&~0xF)<<4) | 0b0111<<4 | (v&0xF))
Definition at line 342 of file vm_armv7l.c.
BLi
#define BLi (i) (AL | (0b10)<<26 | (1<<25) /*I*/ | (1<<24) /*L*/ | (i))
Definition at line 451 of file vm_armv7l.c.
BLX
#define BLX (reg) (AL | 0b00010010<<20 | 0b1111<<16 | 0b1111<<12 | 0b1111<<8| 0b0011<<4 | reg)
Definition at line 457 of file vm_armv7l.c.
BX
#define BX (reg) (AL | 0b00010010<<20 | 0b1111<<16 | 0b1111<<12 | 0b1111<<8| 0b0001<<4 | reg)
Definition at line 454 of file vm_armv7l.c.
CC
#define CC (0b0011<<28)
Definition at line 326 of file vm_armv7l.c.
CHECK_JUMP
#define CHECK_JUMP
Value:
    do { \
    static int bytes_to_skip = -1; \
    static unsigned branch = -1; \
    emit_MOVRxi(R1, (unsigned)vm->instructionCount); \
    emit(CMP(R0, R1)); \
    if (branch == -1) \
        branch = vm->codeLength; \
    emit(cond(LT, Bi(j_rel(bytes_to_skip)))); \
    emit_MOVRxi_or_NOP(R12, (unsigned)ErrJump); \
    emit(BLX(R12)); \
    if (bytes_to_skip == -1) \
        bytes_to_skip = vm->codeLength - branch; \
} while(0)
Definition at line 528 of file vm_armv7l.c.
CMN
#define CMN (src, reg) (AL | (0b000<<25) | (0b10111<<20) | (src<<16) | reg)
Definition at line 413 of file vm_armv7l.c.
CMNi
#define CMNi (src, i) (AL | (0b001<<25) | (0b10111<<20) | (src<<16) | rimm(i))
Definition at line 368 of file vm_armv7l.c.
CMP
#define CMP (src, reg) (AL | (0b000<<25) | (0b10101<<20) | (src<<16) | reg)
Definition at line 412 of file vm_armv7l.c.
CMPi
#define CMPi (src, i) (AL | (0b001<<25) | (0b10101<<20) | (src<<16) | rimm(i))
Definition at line 367 of file vm_armv7l.c.
cond
#define cond (what, op) (what | (op&~AL))
Definition at line 339 of file vm_armv7l.c.
CS
#define CS (0b0010<<28)
Definition at line 324 of file vm_armv7l.c.
DIE
#define DIE (reason, args...)
Value:
    do { \
        Com_Error(ERR_DROP, "vm_arm compiler error: " reason, ##args); \
        exit(1); \
    } while(0)
Definition at line 78 of file vm_armv7l.c.
emit
#define emit (isn) _emit(vm, isn, pass)
Definition at line 267 of file vm_armv7l.c.
emit_MOVR0i
#define emit_MOVR0i (arg) emit_MOVRxi(R0, arg)
Definition at line 474 of file vm_armv7l.c.
emit_MOVRxi
#define emit_MOVRxi (reg, arg)
Value:
    do { \
    emit(MOVW(reg, (arg&0xFFFF))); \
    if (arg > 0xFFFF) \
        emit(MOVT(reg, (((arg>>16)&0xFFFF)))); \
    } while(0)
Definition at line 477 of file vm_armv7l.c.
emit_MOVRxi_or_NOP
#define emit_MOVRxi_or_NOP (reg, arg)
Value:
    do { \
    emit(MOVW(reg, (arg&0xFFFF))); \
    if (arg > 0xFFFF) \
        emit(MOVT(reg, (((arg>>16)&0xFFFF)))); \
    else \
        emit(NOP); \
    } while(0)
Definition at line 485 of file vm_armv7l.c.
EOR
#define EOR (dst, src, reg) (AL | (0b000<<25) | (0b00010<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 385 of file vm_armv7l.c.
EORi
#define EORi (dst, src, i) (AL | (0b001<<25) | (0b00010<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 349 of file vm_armv7l.c.
EORSi
#define EORSi (dst, src, i) (EORi(dst, src, i) | (1<<20))
Definition at line 371 of file vm_armv7l.c.
EQ
#define EQ (0b0000<<28)
Definition at line 322 of file vm_armv7l.c.
FJ
#define FJ (comparator)
Value:
    do { \
    emit_MOVRxi(R0, arg.i); \
    CHECK_JUMP; \
    emit(SUBi(rOPSTACK, rOPSTACK, 8)); \
    emit(VLDRa(S15, rOPSTACK, 4)); \
    emit(VLDRa(S14, rOPSTACK, 8)); \
    emit(VCMP_F32(S15, S14)); \
    emit(VMRS(APSR_nzcv)); \
    emit(cond(comparator, Bi(j_rel(vm->instructionPointers[arg.i]-vm->codeLength)))); \
} while (0)
Definition at line 567 of file vm_armv7l.c.
FP
#define FP 11
Definition at line 52 of file vm_armv7l.c.
GE
#define GE (0b1010<<28)
Definition at line 334 of file vm_armv7l.c.
get_offset
#define get_offset (i) (codeoffsets[i])
GT
#define GT (0b1100<<28)
Definition at line 336 of file vm_armv7l.c.
HI
#define HI (0b1000<<28)
Definition at line 332 of file vm_armv7l.c.
HS
#define HS CS
Definition at line 325 of file vm_armv7l.c.
IJ
#define IJ (comparator)
Value:
    do { \
    MAYBE_EMIT_CONST(); \
    emit_MOVRxi(R0, arg.i); \
    CHECK_JUMP; \
    emit(LDRTxi(R0, rOPSTACK, 4)); \
    emit(LDRTxi(R1, rOPSTACK, 4));  \
    emit(CMP(R1, R0)); \
    emit(cond(comparator, Bi(j_rel(vm->instructionPointers[arg.i]-vm->codeLength)))); \
} while (0)
Definition at line 557 of file vm_armv7l.c.
j_rel
#define j_rel (x) (pass?_j_rel(x, pc):0xBAD)
LDRa
#define LDRa (dst, base, off) (AL | (0b011<<25) | (0b1100<<21) | (1<<20) | base<<16 | dst<<12 | off)
Definition at line 415 of file vm_armv7l.c.
LDRai
#define LDRai (dst, base, off) (AL | (0b010<<25) | (0b1100<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 418 of file vm_armv7l.c.
LDRBa
#define LDRBa (dst, base, off) (AL | (0b011<<25) | (0b1110<<21) | (1<<20) | base<<16 | dst<<12 | off)
Definition at line 427 of file vm_armv7l.c.
LDRHa
#define LDRHa (dst, base, off) (AL | (0b000<<25) | (0b1100<<21) | (1<<20) | base<<16 | dst<<12 | (0b1011<<4) | off)
Definition at line 431 of file vm_armv7l.c.
LDRSBai
#define LDRSBai (dst, base, off) (AL | (0b000<<25) | (0b0110<<21) | (1<<20) | base<<16 | dst<<12 | ((off&0xF0)<<4)|0b1101<<4|(off&0x0F))
Definition at line 428 of file vm_armv7l.c.
LDRSHai
#define LDRSHai (dst, base, off) (AL | (0b000<<25) | (0b1110<<21) | (1<<20) | base<<16 | dst<<12 | ((off&0xF0)<<4)|0b1111<<4|(off&0x0F))
Definition at line 432 of file vm_armv7l.c.
LDRTa
#define LDRTa (dst, base, off) (AL | (0b011<<25) | (0b0101<<21) | (1<<20) | base<<16 | dst<<12 | off)
Definition at line 422 of file vm_armv7l.c.
LDRTai
#define LDRTai (dst, base, off) (AL | (0b010<<25) | (0b0101<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 424 of file vm_armv7l.c.
LDRTx
#define LDRTx (dst, base, off) (AL | (0b011<<25) | (0b0001<<21) | (1<<20) | base<<16 | dst<<12 | off)
Definition at line 423 of file vm_armv7l.c.
LDRTxi
#define LDRTxi (dst, base, off) (AL | (0b010<<25) | (0b0001<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 425 of file vm_armv7l.c.
LDRx
#define LDRx (dst, base, off) (AL | (0b011<<25) | (0b1000<<21) | (1<<20) | base<<16 | dst<<12 | off)
Definition at line 416 of file vm_armv7l.c.
LDRxi
#define LDRxi (dst, base, off) (AL | (0b010<<25) | (0b1000<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 419 of file vm_armv7l.c.
LDRxiw
#define LDRxiw (dst, base, off) (AL | (0b010<<25) | (0b1001<<21) | (1<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 420 of file vm_armv7l.c.
LE
#define LE (0b1101<<28)
Definition at line 337 of file vm_armv7l.c.
LO
#define LO CC
Definition at line 327 of file vm_armv7l.c.
LR
#define LR 14
Definition at line 54 of file vm_armv7l.c.
LS
#define LS (0b1001<<28)
Definition at line 333 of file vm_armv7l.c.
LSL
#define LSL (dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0001<<4) | src)
Definition at line 396 of file vm_armv7l.c.
LSLi
#define LSLi (dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b000<<4) | src)
Definition at line 401 of file vm_armv7l.c.
LSR
#define LSR (dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0011<<4) | src)
Definition at line 397 of file vm_armv7l.c.
LSRi
#define LSRi (dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b010<<4) | src)
Definition at line 402 of file vm_armv7l.c.
LT
#define LT (0b1011<<28)
Definition at line 335 of file vm_armv7l.c.
MAYBE_EMIT_CONST
#define MAYBE_EMIT_CONST ()
Definition at line 553 of file vm_armv7l.c.
MI
#define MI (0b0100<<28)
Definition at line 328 of file vm_armv7l.c.
MOV
#define MOV (dst, src) (AL | (0b000<<25) | (0b11010<<20) | (dst<<12) | src)
Definition at line 394 of file vm_armv7l.c.
MOVi
#define MOVi (dst, i) (AL | (0b001<<25) | (0b11010<<20) | (dst<<12) | rimm(i))
Definition at line 358 of file vm_armv7l.c.
MOVSi
#define MOVSi (dst, i) (MOVi(dst, i) | (1<<20))
Definition at line 380 of file vm_armv7l.c.
MOVT
#define MOVT (dst, i) (AL | (0b11<<24) | (0b0100<<20) | ((((i)>>12)&0xF)<<16) | (dst<<12) | ((i)&((1<<12)-1)))
Definition at line 363 of file vm_armv7l.c.
MOVW
#define MOVW (dst, i) (AL | (0b11<<24) | ((((i)>>12)&0xF)<<16) | (dst<<12) | ((i)&((1<<12)-1)))
Definition at line 362 of file vm_armv7l.c.
MUL
#define MUL (op1, op2, op3) (AL | 0b0000000<<21 | (1<<20) /*S*/ | (op1<<16) | (op3<<8) | 0b1001<<4 | (op2))
Definition at line 470 of file vm_armv7l.c.
MVN
#define MVN (dst, reg) (AL | (0b000<<25) | (0b11110<<20) | (dst<<12) | reg)
Definition at line 408 of file vm_armv7l.c.
MVNi
#define MVNi (dst, i) (AL | (0b001<<25) | (0b11110<<20) | (dst<<12) | rimm(i))
Definition at line 360 of file vm_armv7l.c.
MVNSi
#define MVNSi (dst, i) (MVNi(dst, src, i) | (1<<20))
Definition at line 382 of file vm_armv7l.c.
NE
#define NE (0b0001<<28)
Definition at line 323 of file vm_armv7l.c.
NOP
#define NOP cond(AL, YIELD)
Definition at line 345 of file vm_armv7l.c.
NOTIMPL
#define NOTIMPL (x) do { Com_Printf(S_COLOR_RED "instruction not implemented: %x\n", x); vm->compiled = qfalse; return; } while(0)
Definition at line 198 of file vm_armv7l.c.
OFF_CODE
#define OFF_CODE 0
OFF_IMMEDIATES
#define OFF_IMMEDIATES 1
OFFSET
#define OFFSET (i) (pass?(j_rel(codeoffsets[i]-vm->codeLength)):(0xF000000F))
opArg0
#define opArg0 0x0000 /* requires nothing */
Definition at line 99 of file vm_armv7l.c.
opArg2F
#define opArg2F 0x0080 /* requires second argument, float */
Definition at line 105 of file vm_armv7l.c.
opArg2I
#define opArg2I 0x0040 /* requires second argument, integer */
Definition at line 104 of file vm_armv7l.c.
opArg2IF
#define opArg2IF (opArg2I | opArg2F) /* requires second argument, integer or float */
Definition at line 106 of file vm_armv7l.c.
opArgF
#define opArgF 0x0020 /* requires float(s) */
Definition at line 101 of file vm_armv7l.c.
opArgI
#define opArgI 0x0010 /* requires integer(s) */
Definition at line 100 of file vm_armv7l.c.
opArgIF
#define opArgIF (opArgI | opArgF) /* requires integer or float */
Definition at line 102 of file vm_armv7l.c.
opImm0
#define opImm0 0x0000 /* no immediate */
Definition at line 90 of file vm_armv7l.c.
opImm1
#define opImm1 0x0001 /* 1 byte immadiate value after opcode */
Definition at line 91 of file vm_armv7l.c.
opImm4
#define opImm4 0x0002 /* 4 bytes immediate value after opcode */
Definition at line 92 of file vm_armv7l.c.
opRet0
#define opRet0 0x0000 /* returns nothing */
Definition at line 94 of file vm_armv7l.c.
opRetF
#define opRetF 0x0008 /* returns float */
Definition at line 96 of file vm_armv7l.c.
opRetI
#define opRetI 0x0004 /* returns integer */
Definition at line 95 of file vm_armv7l.c.
opRetIF
#define opRetIF (opRetI | opRetF) /* returns integer or float */
Definition at line 97 of file vm_armv7l.c.
ORR
#define ORR (dst, src, reg) (AL | (0b000<<25) | (0b11000<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 393 of file vm_armv7l.c.
ORRi
#define ORRi (dst, src, i) (AL | (0b001<<25) | (0b11000<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 357 of file vm_armv7l.c.
ORRSi
#define ORRSi (dst, src, i) (ORRi(dst, src, i) | (1<<20))
Definition at line 379 of file vm_armv7l.c.
PC
#define PC 15
Definition at line 55 of file vm_armv7l.c.
PL
#define PL (0b0101<<28)
Definition at line 329 of file vm_armv7l.c.
POP
#define POP (mask) (0xe8bd0000|mask)
Definition at line 464 of file vm_armv7l.c.
POP1
#define POP1 (reg) (AL | (0b010<<25) | (0b0100<<21) | (1<<20) | SP<<16 | reg<<12 | reg)
Definition at line 443 of file vm_armv7l.c.
PREINDEX
#define PREINDEX (1<<24)
Definition at line 314 of file vm_armv7l.c.
printreg
#define printreg (reg) emit(PUSH1(R3)); emit(BLX(reg)); emit(POP1(R3));
Definition at line 578 of file vm_armv7l.c.
PUSH
#define PUSH (mask) (AL | (0b100100<<22) | (0b10<<20) | (0b1101<<16) | mask)
Definition at line 460 of file vm_armv7l.c.
PUSH1
#define PUSH1 (reg) (AL | (0b010<<25) | (0b1001<<21) | (0<<20) | SP<<16 | reg<<12 | 4)
Definition at line 445 of file vm_armv7l.c.
PUSH2
#define PUSH2 (r1, r2) (AL | (0b100100<<22) | (0b10<<20) | (0b1101<<16) | 1<<r1 | 1<<r2)
Definition at line 461 of file vm_armv7l.c.
R0
#define R0 0
Definition at line 44 of file vm_armv7l.c.
R1
#define R1 1
Definition at line 45 of file vm_armv7l.c.
R12
#define R12 12
Definition at line 50 of file vm_armv7l.c.
R2
#define R2 2
Definition at line 46 of file vm_armv7l.c.
R3
#define R3 3
Definition at line 47 of file vm_armv7l.c.
R4
#define R4 4
Definition at line 48 of file vm_armv7l.c.
rASR
#define rASR (i, reg) (0b10<<5 | ((i&31)<<7) | reg)
Definition at line 316 of file vm_armv7l.c.
rCODEBASE
#define rCODEBASE 7
Definition at line 64 of file vm_armv7l.c.
rDATABASE
#define rDATABASE 9
Definition at line 66 of file vm_armv7l.c.
rDATAMASK
#define rDATAMASK 10
Definition at line 67 of file vm_armv7l.c.
rLSL
#define rLSL (i, reg) (0b00<<5 | ((i&31)<<7) | reg)
Definition at line 317 of file vm_armv7l.c.
rLSR
#define rLSR (i, reg) (0b01<<5 | ((i&31)<<7) | reg)
Definition at line 318 of file vm_armv7l.c.
rOPSTACK
#define rOPSTACK 5
Definition at line 62 of file vm_armv7l.c.
rOPSTACKBASE
#define rOPSTACKBASE 6
Definition at line 63 of file vm_armv7l.c.
ROR
#define ROR (dst, src, reg) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (reg<<8) | (0b0111<<4) | src)
Definition at line 399 of file vm_armv7l.c.
RORi
#define RORi (dst, src, i) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | ((i&0x1F)<<7) | (0b110<<4) | src)
Definition at line 404 of file vm_armv7l.c.
rPSTACK
#define rPSTACK 8
Definition at line 65 of file vm_armv7l.c.
rROR
#define rROR (i, reg) (0b11<<5 | ((i&31)<<7) | reg)
Definition at line 319 of file vm_armv7l.c.
RRX
#define RRX (dst, src) (AL | (0b000<<25) | (0b1101<<21) | (0<<20) | (dst<<12) | (0b110<<4) | src)
Definition at line 405 of file vm_armv7l.c.
RSB
#define RSB (dst, src, reg) (AL | (0b000<<25) | (0b00110<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 387 of file vm_armv7l.c.
RSBi
#define RSBi (dst, src, i) (AL | (0b001<<25) | (0b00110<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 351 of file vm_armv7l.c.
RSBSi
#define RSBSi (dst, src, i) (RSBi(dst, src, i) | (1<<20))
Definition at line 373 of file vm_armv7l.c.
RSC
#define RSC (dst, src, reg) (AL | (0b000<<25) | (0b01110<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 391 of file vm_armv7l.c.
RSCi
#define RSCi (dst, src, i) (AL | (0b001<<25) | (0b01110<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 355 of file vm_armv7l.c.
RSCSi
#define RSCSi (dst, src, i) (RSCi(dst, src, i) | (1<<20))
Definition at line 377 of file vm_armv7l.c.
S14
#define S14 14
Definition at line 59 of file vm_armv7l.c.
S15
#define S15 15
Definition at line 60 of file vm_armv7l.c.
save_offset
#define save_offset (i) (codeoffsets[i] = vm->codeLength)
SBC
#define SBC (dst, src, reg) (AL | (0b000<<25) | (0b01100<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 390 of file vm_armv7l.c.
SBCi
#define SBCi (dst, src, i) (AL | (0b001<<25) | (0b01100<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 354 of file vm_armv7l.c.
SBCSi
#define SBCSi (dst, src, i) (SBCi(dst, src, i) | (1<<20))
Definition at line 376 of file vm_armv7l.c.
SP
#define SP 13
Definition at line 53 of file vm_armv7l.c.
STM
#define STM (base, regs) (AL | 0b100<<25 | 0<<24/*P*/| 0<<24/*U*/| 0<<24/*S*/| 0<<24/*W*/ | (base<<16) | (regs&~(1<<16)))
Definition at line 466 of file vm_armv7l.c.
STRa
#define STRa (dst, base, off) (AL | (0b011<<25) | (0b1100<<21) | (0<<20) | base<<16 | dst<<12 | off)
Definition at line 435 of file vm_armv7l.c.
STRai
#define STRai (dst, base, off) (AL | (0b010<<25) | (0b1100<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 437 of file vm_armv7l.c.
STRaiw
#define STRaiw (dst, base, off) (AL | (0b010<<25) | (0b1101<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 439 of file vm_armv7l.c.
STRBa
#define STRBa (dst, base, off) (AL | (0b011<<25) | (0b1110<<21) | (0<<20) | base<<16 | dst<<12 | off)
Definition at line 429 of file vm_armv7l.c.
STRHa
#define STRHa (dst, base, off) (AL | (0b000<<25) | (0b1100<<21) | (0<<20) | base<<16 | dst<<12 | (0b1011<<4) | off)
Definition at line 433 of file vm_armv7l.c.
STRx
#define STRx (dst, base, off) (AL | (0b011<<25) | (0b1000<<21) | (0<<20) | base<<16 | dst<<12 | off)
Definition at line 436 of file vm_armv7l.c.
STRxi
#define STRxi (dst, base, off) (AL | (0b010<<25) | (0b1000<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 438 of file vm_armv7l.c.
STRxiw
#define STRxiw (dst, base, off) (AL | (0b010<<25) | (0b1001<<21) | (0<<20) | base<<16 | dst<<12 | rimm(off))
Definition at line 440 of file vm_armv7l.c.
SUB
#define SUB (dst, src, reg) (AL | (0b000<<25) | (0b00100<<20) | (src<<16) | (dst<<12) | reg)
Definition at line 386 of file vm_armv7l.c.
SUBi
#define SUBi (dst, src, i) (AL | (0b001<<25) | (0b00100<<20) | (src<<16) | (dst<<12) | rimm(i))
Definition at line 350 of file vm_armv7l.c.
SUBSi
#define SUBSi (dst, src, i) (SUBi(dst, src, i) | (1<<20))
Definition at line 372 of file vm_armv7l.c.
TEQ
#define TEQ (src, reg) (AL | (0b000<<25) | (0b10011<<20) | (src<<16) | reg)
Definition at line 411 of file vm_armv7l.c.
TEQi
#define TEQi (src, i) (AL | (0b001<<25) | (0b10011<<20) | (src<<16) | rimm(i))
Definition at line 366 of file vm_armv7l.c.
TST
#define TST (src, reg) (AL | (0b000<<25) | (0b10001<<20) | (src<<16) | reg)
Definition at line 410 of file vm_armv7l.c.
TSTi
#define TSTi (src, i) (AL | (0b001<<25) | (0b10001<<20) | (src<<16) | rimm(i))
Definition at line 365 of file vm_armv7l.c.
VADD_F32
#define VADD_F32 (Vd, Vn, Vm) (AL|(0b11100<<23)|((Vd&1)<<22)|(0b11<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|((Vn&1)<<7)|(0<<6)|((Vm&1)<<5)|(Vm>>1))
Definition at line 511 of file vm_armv7l.c.
VC
#define VC (0b0111<<28)
Definition at line 331 of file vm_armv7l.c.
VCMP_F32
#define VCMP_F32 (Vd, Vm) _VCMP_F32(Vd, Vm, 0)
Definition at line 522 of file vm_armv7l.c.
VCVT_F32_S32
#define VCVT_F32_S32 (Sd, Sm) _VCVT_F(Sd, Sm, 0b000, 1 /* unsigned */)
Definition at line 502 of file vm_armv7l.c.
VCVT_F32_U32
#define VCVT_F32_U32 (Sd, Sm) _VCVT_F(Sd, Sm, 0b000, 0 /* unsigned */)
Definition at line 500 of file vm_armv7l.c.
VCVT_S32_F32
#define VCVT_S32_F32 (Sd, Sm) _VCVT_F(Sd, Sm, 0b101, 1 /* round zero */)
Definition at line 503 of file vm_armv7l.c.
VCVT_U32_F32
#define VCVT_U32_F32 (Sd, Sm) _VCVT_F(Sd, Sm, 0b100, 1 /* round zero */)
Definition at line 501 of file vm_armv7l.c.
VDIV_F32
#define VDIV_F32 (Vd, Vn, Vm) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b00<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|((Vn&1)<<7)|(0<<6)|((Vm&1)<<5)|(Vm>>1))
Definition at line 517 of file vm_armv7l.c.
VLDRa
#define VLDRa (Vd, Rn, i) (AL|(0b1101<<24)|1<<23|((Vd&1)<<22)|1<<20|(Rn<<16)|((Vd>>1)<<12)|(0b1010<<8)|off8(i))
Definition at line 505 of file vm_armv7l.c.
VMOVass
#define VMOVass (Vn, Rt) (AL|(0b1110<<24)|(0b000<<21)|(0<<20)| ((Vn>>1)<<16) | (Rt<<12) | (0b1010<<8) | ((Vn&1)<<7) | (1<<4))
Definition at line 494 of file vm_armv7l.c.
VMOVssa
#define VMOVssa (Rt, Vn) (AL|(0b1110<<24)|(0b000<<21)|(1<<20)| ((Vn>>1)<<16) | (Rt<<12) | (0b1010<<8) | ((Vn&1)<<7) | (1<<4))
Definition at line 496 of file vm_armv7l.c.
VMRS
#define VMRS (Rt) (AL|(0b11101111<<20)|(0b0001<<16)|(Rt<<12)|(0b1010<<8)|(1<<4))
Definition at line 524 of file vm_armv7l.c.
VMUL_F32
#define VMUL_F32 (Vd, Vn, Vm) (AL|(0b11100<<23)|((Vd&1)<<22)|(0b10<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101)<<9|(0<<8)|((Vn&1)<<7)|(0<<6)|((Vm&1)<<5)|(Vm>>1))
Definition at line 515 of file vm_armv7l.c.
VNEG_F32
#define VNEG_F32 (Vd, Vm) (AL|(0b11101<<23)|((Vd&1)<<22)|(0b11<<20)|(1<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
Definition at line 508 of file vm_armv7l.c.
VS
#define VS (0b0110<<28)
Definition at line 330 of file vm_armv7l.c.
VSTRa
#define VSTRa (Vd, Rn, i) (AL|(0b1101<<24)|1<<23|((Vd&1)<<22)|0<<20|(Rn<<16)|((Vd>>1)<<12)|(0b1010<<8)|off8(i))
Definition at line 506 of file vm_armv7l.c.
VSUB_F32
#define VSUB_F32 (Vd, Vn, Vm) (AL|(0b11100<<23)|((Vd&1)<<22)|(0b11<<20)|((Vn>>1)<<16)|((Vd>>1)<<12)|(0b101<<9)|(0<<8)|((Vn&1)<<7)|(1<<6)|((Vm&1)<<5)|(Vm>>1))
Definition at line 513 of file vm_armv7l.c.
YIELD
#define YIELD (0b110010<<20 | 0b1111<<12 | 1)
Definition at line 344 of file vm_armv7l.c.
Function Documentation
__aeabi_idiv()
int __aeabi_idiv (int , int)
Referenced by VM_Compile().
__aeabi_idivmod()
void __aeabi_idivmod (void)
Referenced by VM_Compile().
__aeabi_uidiv()
unsigned __aeabi_uidiv (unsigned , unsigned)
Referenced by VM_Compile().
__aeabi_uidivmod()
void __aeabi_uidivmod (void)
Referenced by VM_Compile().
__attribute__()
static void __attribute__ ((__noreturn__)) static
Definition at line 218 of file vm_armv7l.c.
 {
     Com_Error(ERR_DROP, "program tried to execute code outside VM (%x)", num);
 }
_emit()
void _emit (vm_t * vm, unsigned isn, int pass)
Definition at line 252 of file vm_armv7l.c.
 {
 #if 0
     static int fd = -2;
     if (fd == -2)
         fd = open("code.bin", O_TRUNC|O_WRONLY|O_CREAT, 0644);
     if (fd > 0)
         write(fd, &isn, 4);
 #endif
     if (pass)
         memcpy(vm->codeBase+vm->codeLength, &isn, 4);
     vm->codeLength+=4;
 }
_j_rel()
static unsigned _j_rel (int x, int pc) inline static
Definition at line 580 of file vm_armv7l.c.
 {
     if (x&3) goto err;
     x = (x>>2)-2;
     if (x < 0)
     {
         if ((x&(0xFF<<24)) != 0xFF<<24)
             goto err;
         x &= ~(0xFF<<24);
     }
     else if (x&(0xFF<<24))
         goto err;
     return x;
 err:
     DIE("jump %d out of range at %d", x, pc);
 }
asmcall()
static int asmcall (int call, int pstack) static
Definition at line 223 of file vm_armv7l.c.
 {
     // save currentVM so as to allow for recursive VM entry
     vm_t *savedVM = currentVM;
     int i, ret;
     // modify VM stack pointer for recursive VM entry
     currentVM->programStack = pstack - 4;
     if (sizeof(intptr_t) == sizeof(int)) {
         intptr_t *argPosition = (intptr_t *)((byte *)currentVM->dataBase + pstack + 4);
         argPosition[0] = -1 - call;
         ret = currentVM->systemCall(argPosition);
     } else {
         intptr_t args[MAX_VMSYSCALL_ARGS];
         args[0] = -1 - call;
         int *argPosition = (int *)((byte *)currentVM->dataBase + pstack + 4);
         for( i = 1; i < ARRAY_LEN(args); i++ )
             args[i] = argPosition[i];
         ret = currentVM->systemCall(args);
     }
     currentVM = savedVM;
     return ret;
 }
Referenced by VM_Compile().
can_encode()
static unsigned short can_encode (unsigned val) static
Definition at line 296 of file vm_armv7l.c.
 {
     unsigned shift = 0;
     if (!val)
         DIE("can_encode: invalid argument");
     if (val < 256)
         return val;
     // rotate the value until it fits
     while (shift < 16 && (val>255 || !(val&3))) {
         val =  (val&3)<<30 | val>>2;
         ++shift;
     }
     if (shift > 15 || val > 255) {
         return 0;
     }
     return (16-shift)<<8 | val;
 }
Referenced by VM_Compile().
off8()
static unsigned char off8 (unsigned val) static
Definition at line 269 of file vm_armv7l.c.
 {
     if (val&3)
         DIE("offset must be multiple of four");
     if (val > 1020)
         DIE("offset too large");
     return val>>2;
 }
rimm()
static unsigned short rimm (unsigned val) static
Definition at line 279 of file vm_armv7l.c.
 {
     unsigned shift = 0;
     if (val < 256)
         return val;
     // rotate the value until it fits
     while (shift < 16 && (val>255 || !(val&3))) {
         val =  (val&3)<<30 | val>>2;
         ++shift;
     }
     if (shift > 15 || val > 255) {
         DIE("immediate cannot be encoded (%d, %d)\n", shift, val);
     }
     return (16-shift)<<8 | val;
 }
VM_CallCompiled()
int VM_CallCompiled (vm_t * vm, int * args)
Definition at line 1168 of file vm_armv7l.c.
 {
     byte    stack[OPSTACK_SIZE + 15];
     int *opStack;
     int programStack = vm->programStack;
     int stackOnEntry = programStack;
     byte    *image = vm->dataBase;
     int *argPointer;
     int retVal;
     currentVM = vm;
     vm->currentlyInterpreting = qtrue;
     programStack -= ( 8 + 4 * MAX_VMMAIN_ARGS );
     argPointer = (int *)&image[ programStack + 8 ];
     memcpy( argPointer, args, 4 * MAX_VMMAIN_ARGS );
     argPointer[-1] = 0;
     argPointer[-2] = -1;
     opStack = PADP(stack, 16);
     *opStack = 0xDEADBEEF;
 #if 0
     Com_Printf("r5 opStack:\t\t%p\n", opStack);
     Com_Printf("r7 codeBase:\t\t%p\n", vm->codeBase);
     Com_Printf("r8 programStack:\t0x%x\n", programStack);
     Com_Printf("r9 dataBase:\t\t%p\n", vm->dataBase);
 #endif
     /* call generated code */
     {
         //int (*entry)(void *, int, void *, int);
         int (*entry)(vm_t*, int*, int*);
         entry = (void *)(vm->codeBase);
         //__asm__ volatile("bkpt");
         //retVal = entry(vm->codeBase, programStack, vm->dataBase, vm->dataMask);
         retVal = entry(vm, &programStack, opStack);
     }
     if(*opStack != 0xDEADBEEF)
     {
         Com_Error(ERR_DROP, "opStack corrupted in compiled code");
     }
     if(programStack != stackOnEntry - (8 + 4 * MAX_VMMAIN_ARGS))
         Com_Error(ERR_DROP, "programStack corrupted in compiled code");
     vm->programStack = stackOnEntry;
     vm->currentlyInterpreting = qfalse;
     return retVal;
 }
Referenced by VM_Call().
VM_Compile()
void VM_Compile (vm_t * vm, vmHeader_t * header)
Definition at line 597 of file vm_armv7l.c.
 {
     unsigned char *code;
     int i_count, pc = 0;
     int pass;
     int codeoffsets[2]; // was 1024 but it's only used for OFF_CODE and OFF_IMMEDIATES
 #define j_rel(x) (pass?_j_rel(x, pc):0xBAD)
 #define OFFSET(i) (pass?(j_rel(codeoffsets[i]-vm->codeLength)):(0xF000000F))
 //#define new_offset() (offsidx++)
 #define get_offset(i) (codeoffsets[i])
 #define save_offset(i) (codeoffsets[i] = vm->codeLength)
 #define OFF_CODE 0
 #define OFF_IMMEDIATES 1
     vm->compiled = qfalse;
     vm->codeBase = NULL;
     vm->codeLength = 0;
     for (pass = 0; pass < 2; ++pass) {
 //  int offsidx = 0;
 #ifdef CONST_OPTIMIZE
     // const optimization
     unsigned got_const = 0, const_value = 0;
 #endif
     if(pass)
     {
         vm->codeBase = mmap(NULL, vm->codeLength, PROT_WRITE, MAP_SHARED|MAP_ANONYMOUS, -1, 0);
         if(vm->codeBase == MAP_FAILED)
             Com_Error(ERR_FATAL, "VM_CompileARM: can't mmap memory");
         vm->codeLength = 0;
     }
     //int (*entry)(vm_t*, int*, int*);
     emit(PUSH((((1<<8)-1)<<4)|(1<<14))); // push R4-R11, LR
     emit(SUBi(SP, SP, 12)); // align stack!
     emit(LDRai(rCODEBASE, R0, offsetof(vm_t, codeBase)));
     emit(LDRai(rDATABASE, R0, offsetof(vm_t, dataBase)));
     emit(LDRai(rDATAMASK, R0, offsetof(vm_t, dataMask)));
     emit(LDRai(rPSTACK, R1, 0));
     emit(MOV(rOPSTACK, R2)); // TODO: reverse opstack to avoid writing to return address
     emit(MOV(rOPSTACKBASE, rOPSTACK));
     emit(BLi(OFFSET(OFF_CODE)));
     // save return value in r0
     emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
     emit(ADDi(SP, SP, 12)); // align stack!
     emit(POP((((1<<8)-1)<<4)|(1<<15))); // pop R4-R11, LR -> PC
     /* save some immediates here */
     emit(BKPT(0));
     emit(BKPT(0));
     save_offset(OFF_IMMEDIATES);
 //  emit((unsigned)whatever);
     emit(BKPT(0));
     emit(BKPT(0));
     save_offset(OFF_CODE);
 //  offsidx = OFF_IMMEDIATES+1;
     code = (unsigned char *) header + header->codeOffset;
     pc = 0;
     for (i_count = 0; i_count < header->instructionCount; i_count++) {
         union {
             unsigned char b[4];
             unsigned int i;
         } arg;
         unsigned char op = code[pc++];
         vm->instructionPointers[i_count] = vm->codeLength;
         if (vm_opInfo[op] & opImm4)
         {
             memcpy(arg.b, &code[pc], 4);
             pc += 4;
 #ifdef EXCESSIVE_DEBUG
             Com_Printf("%d: instruction %d (%s %d), offset %d\n", pass, i_count, opnames[op], arg.i, vm->codeLength);
 #endif
         }
         else if (vm_opInfo[op] & opImm1)
         {
             arg.b[0] = code[pc];
             ++pc;
 #ifdef EXCESSIVE_DEBUG
             Com_Printf("%d: instruction %d (%s %hhd), offset %d\n", pass, i_count, opnames[op], arg.i, vm->codeLength);
 #endif
         }
         else
         {
 #ifdef EXCESSIVE_DEBUG
             Com_Printf("%d: instruction %d (%s), offset %d\n", pass, i_count, opnames[op], vm->codeLength);
 #endif
         }
         // TODO: for debug only
         //emit_MOVRxi(R4, i_count);
         switch ( op )
         {
             case OP_UNDEF:
                 break;
             case OP_IGNORE:
                 NOTIMPL(op);
                 break;
             case OP_BREAK:
                 emit(BKPT(0));
                 break;
             case OP_ENTER:
                 MAYBE_EMIT_CONST();
                 emit(PUSH1(LR));
                 emit(SUBi(SP, SP, 12)); // align stack
                 if (arg.i == 0 || can_encode(arg.i))
                 {
                     emit(SUBi(rPSTACK, rPSTACK, arg.i)); // pstack -= arg
                 }
                 else
                 {
                     emit_MOVR0i(arg.i);
                     emit(SUB(rPSTACK, rPSTACK, R0)); // pstack -= arg
                 }
                 break;
             case OP_LEAVE:
                 if (arg.i == 0 || can_encode(arg.i))
                 {
                     emit(ADDi(rPSTACK, rPSTACK, arg.i)); // pstack += arg
                 }
                 else
                 {
                     emit_MOVR0i(arg.i);
                     emit(ADD(rPSTACK, rPSTACK, R0)); // pstack += arg
                 }
                 emit(ADDi(SP, SP, 12));
                 emit(0xe49df004); // pop pc
                 break;
             case OP_CALL:
 #if 0
                 // save next instruction
                 emit_MOVR0i(i_count);
                 emit(STRa(R0, rDATABASE, rPSTACK));      // dataBase[pstack] = r0
 #endif
 #ifdef CONST_OPTIMIZE
                 if (got_const)
                 {
                     NOTIMPL(op);
                 }
                 else
 #endif
                 {
                     static int bytes_to_skip = -1;
                     static unsigned start_block = -1;
                     MAYBE_EMIT_CONST();
                     // get instruction nr from stack
                     emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                     emit(CMPi(R0, 0)); // check if syscall
                     if (start_block == -1)
                         start_block = vm->codeLength;
                     emit(cond(LT, Bi(j_rel(bytes_to_skip))));
                         CHECK_JUMP;
                         emit_MOVRxi_or_NOP(R1, (unsigned)vm->instructionPointers);
                         emit(LDRa(R0, R1, rLSL(2, R0))); // r0 = ((int*)r1)[r0]
                         emit(ADD(R0, rCODEBASE, R0)); // r0 = codeBase+r0
                         emit(BLX(R0));
                         emit(Bi(j_rel(vm->instructionPointers[i_count+1]-vm->codeLength)));
                     if (bytes_to_skip == -1)
                         bytes_to_skip = vm->codeLength - start_block;
                     emit(MOV(R1, rPSTACK));
                     emit_MOVRxi(R12, (unsigned)asmcall);
                     emit(BLX(R12));
                     // store return value
                     emit(STRaiw(R0, rOPSTACK, 4));      // opstack+=4; *opstack = r0
                 }
                 break;
             case OP_PUSH:
                 MAYBE_EMIT_CONST();
                 emit(ADDi(rOPSTACK, rOPSTACK, 4));
                 break;
             case OP_POP:
                 MAYBE_EMIT_CONST();
                 emit(SUBi(rOPSTACK, rOPSTACK, 4));
                 break;
             case OP_CONST:
                 MAYBE_EMIT_CONST();
                 emit_MOVR0i(arg.i);
                 emit(STRaiw(R0, rOPSTACK, 4));      // opstack+=4; *opstack = r0
                 break;
             case OP_LOCAL:
                 MAYBE_EMIT_CONST();
                 if (arg.i == 0 || can_encode(arg.i))
                 {
                     emit(ADDi(R0, rPSTACK, arg.i));     // r0 = pstack+arg
                 }
                 else
                 {
                     emit_MOVR0i(arg.i);
                     emit(ADD(R0, rPSTACK, R0));     // r0 = pstack+arg
                 }
                 emit(STRaiw(R0, rOPSTACK, 4));      // opstack+=4; *opstack = r0
                 break;
             case OP_JUMP:
 #ifdef CONST_OPTIMIZE
                 if (got_const)
                 {
                     NOTIMPL(op);
                 }
                 else
 #endif
                 {
                     emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                     CHECK_JUMP;
                     emit_MOVRxi(R1, (unsigned)vm->instructionPointers);
                     emit(LDRa(R0, R1, rLSL(2, R0))); // r0 = ((int*)r1)[r0]
                     emit(ADD(R0, rCODEBASE, R0)); // r0 = codeBase+r0
                     emit(BLX(R0));
                 }
                 break;
             case OP_EQ:
                 IJ(EQ);
                 break;
             case OP_NE:
                 IJ(NE);
                 break;
             case OP_LTI:
                 IJ(LT);
                 break;
             case OP_LEI:
                 IJ(LE);
                 break;
             case OP_GTI:
                 IJ(GT);
                 break;
             case OP_GEI:
                 IJ(GE);
                 break;
             case OP_LTU:
                 IJ(LO);
                 break;
             case OP_LEU:
                 IJ(LS);
                 break;
             case OP_GTU:
                 IJ(HI);
                 break;
             case OP_GEU:
                 IJ(HS);
                 break;
             case OP_EQF:
                 FJ(EQ);
                 break;
             case OP_NEF:
                 FJ(NE);
                 break;
             case OP_LTF:
                 FJ(LT);
                 break;
             case OP_LEF:
                 FJ(LE);
                 break;
             case OP_GTF:
                 FJ(GT);
                 break;
             case OP_GEF:
                 FJ(GE);
                 break;
             case OP_LOAD1:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));   // r0 = *opstack
                 emit(AND(R0, rDATAMASK, R0));    // r0 = r0 & rDATAMASK
                 emit(LDRBa(R0, rDATABASE, R0));  // r0 = (unsigned char)dataBase[r0]
                 emit(STRai(R0, rOPSTACK, 0));   // *opstack = r0
                 break;
             case OP_LOAD2:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));   // r0 = *opstack
                 emit(AND(R0, rDATAMASK, R0));    // r0 = r0 & rDATAMASK
                 emit(LDRHa(R0, rDATABASE, R0));  // r0 = (unsigned short)dataBase[r0]
                 emit(STRai(R0, rOPSTACK, 0));   // *opstack = r0
                 break;
             case OP_LOAD4:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));   // r0 = *opstack
                 emit(AND(R0, rDATAMASK, R0));    // r0 = r0 & rDATAMASK
                 emit(LDRa(R0, rDATABASE, R0));  // r0 = dataBase[r0]
                 emit(STRai(R0, rOPSTACK, 0));   // *opstack = r0
                 break;
             case OP_STORE1:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r1 = *opstack; rOPSTACK -= 4
                 emit(AND(R1, rDATAMASK, R1));    // r1 = r1 & rDATAMASK
                 emit(STRBa(R0, rDATABASE, R1)); // database[r1] = r0
                 break;
             case OP_STORE2:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r1 = *opstack; rOPSTACK -= 4
                 emit(AND(R1, rDATAMASK, R1));    // r1 = r1 & rDATAMASK
                 emit(STRHa(R0, rDATABASE, R1)); // database[r1] = r0
                 break;
             case OP_STORE4:
                 MAYBE_EMIT_CONST();
                 // optimize: use load multiple
                 // value
                 emit(LDRTxi(R0, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 // pointer
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r1 = *opstack; rOPSTACK -= 4
                 emit(AND(R1, rDATAMASK, R1));    // r1 = r1 & rDATAMASK
                 // store value at pointer
                 emit(STRa(R0, rDATABASE, R1)); // database[r1] = r0
                 break;
             case OP_ARG:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R0, rOPSTACK, 4));      // r0 = *opstack; rOPSTACK -= 4
                 emit(ADDi(R1, rPSTACK, arg.b[0]));  // r1 = programStack+arg
                 emit(AND(R1, rDATAMASK, R1));       // r1 = r1 & rDATAMASK
                 emit(STRa(R0, rDATABASE, R1));      // dataBase[r1] = r0
                 break;
             case OP_BLOCK_COPY:
                 MAYBE_EMIT_CONST();
                 emit(LDRTxi(R1, rOPSTACK, 4));  // r0 = *opstack; rOPSTACK -= 4
                 emit(LDRTxi(R0, rOPSTACK, 4));
                 emit_MOVRxi(R2, arg.i);
                 emit_MOVRxi(R12, (unsigned)VM_BlockCopy);
                 emit(BLX(R12));
                 break;
             case OP_SEX8:
                 MAYBE_EMIT_CONST();
                 emit(LDRSBai(R0, rOPSTACK, 0));      // sign extend *opstack
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_SEX16:
                 MAYBE_EMIT_CONST();
                 emit(LDRSHai(R0, rOPSTACK, 0));      // sign extend *opstack
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_NEGI:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(RSBi(R0, R0, 0));         // r0 = -r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_ADD:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(ADD(R0, R1, R0));         // r0 = r1 + r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_SUB:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(SUB(R0, R1, R0));         // r0 = r1 - r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_DIVI:
             case OP_DIVU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R1, rOPSTACK, 0));  // r1 = *opstack
                 emit(LDRxiw(R0, rOPSTACK, 4)); // opstack-=4; r0 = *opstack
                 if ( op == OP_DIVI )
                     emit_MOVRxi(R12, (unsigned)__aeabi_idiv);
                 else
                     emit_MOVRxi(R12, (unsigned)__aeabi_uidiv);
                 emit(BLX(R12));
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_MODI:
             case OP_MODU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R1, rOPSTACK, 0));  // r1 = *opstack
                 emit(LDRxiw(R0, rOPSTACK, 4)); // opstack-=4; r0 = *opstack
                 if ( op == OP_MODI )
                     emit_MOVRxi(R12, (unsigned)__aeabi_idivmod);
                 else
                     emit_MOVRxi(R12, (unsigned)__aeabi_uidivmod);
                 emit(BLX(R12));
                 emit(STRai(R1, rOPSTACK, 0));  // *opstack = r1
                 break;
             case OP_MULI:
             case OP_MULU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(MUL(R0, R1, R0));         // r0 = r1 * r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BAND:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(AND(R0, R1, R0));         // r0 = r1 & r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BOR:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(ORR(R0, R1, R0));         // r0 = r1 | r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BXOR:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(EOR(R0, R1, R0));         // r0 = r1 ^ r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_BCOM:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(MVN(R0, R0));             // r0 = ~r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_LSH:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(LSL(R0, R1, R0));         // r0 = r1 << r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_RSHI:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(ASR(R0, R1, R0));         // r0 = r1 >> r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_RSHU:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(LDRxiw(R1, rOPSTACK, 4)); // opstack-=4; r1 = *opstack
                 emit(LSR(R0, R1, R0));         // r0 = (unsigned)r1 >> r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
             case OP_NEGF:
                 MAYBE_EMIT_CONST();
                 emit(VLDRa(S14, rOPSTACK, 0)); // s14 = *((float*)opstack)
                 emit(VNEG_F32(S14, S14));      // s15 = -s14
                 emit(VSTRa(S14, rOPSTACK, 0)); // *((float*)opstack) = s15
                 break;
             case OP_ADDF:
                 MAYBE_EMIT_CONST();
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // vldr can't modify rOPSTACK so
                 // we'd either need to change it
                 // with sub or use regular ldr+vmov
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VADD_F32(S14, S15, S14));   // s14 = s14 + s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_SUBF:
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // see OP_ADDF
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VSUB_F32(S14, S15, S14));   // s14 = s14 - s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_DIVF:
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // see OP_ADDF
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VDIV_F32(S14, S15, S14));   // s14 = s14 / s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_MULF:
                 emit(VLDRa(S14, rOPSTACK, 0));   // s14 = *((float*)opstack)
                 // see OP_ADDF
                 emit(LDRxiw(R0, rOPSTACK, 4));   // opstack-=4; r1 = *opstack
                 emit(VMOVass(S15,R0));           // s15 = r0
                 emit(VMUL_F32(S14, S15, S14));   // s14 = s14 * s15
                 emit(VSTRa(S14, rOPSTACK, 0));   // *((float*)opstack) = s15
                 break;
             case OP_CVIF:
                 MAYBE_EMIT_CONST();
                 emit(LDRai(R0, rOPSTACK, 0));  // r0 = *opstack
                 emit(VMOVass(S14,R0));         // s14 = r0
                 emit(VCVT_F32_S32(S14, S14));  // s15 = (float)s14
                 emit(VSTRa(S14, rOPSTACK, 0)); // *((float*)opstack) = s15
                 break;
             case OP_CVFI:
                 MAYBE_EMIT_CONST();
                 emit(VLDRa(S14, rOPSTACK, 0)); // s14 = *((float*)opstack)
                 emit(VCVT_S32_F32(S14, S14));  // s15 = (int)s14
                 emit(VMOVssa(R0,S14));         // s14 = r0
                 emit(STRai(R0, rOPSTACK, 0));  // *opstack = r0
                 break;
         }
     }
     // never reached
     emit(BKPT(0));
     } // pass
     if (mprotect(vm->codeBase, vm->codeLength, PROT_READ|PROT_EXEC/* |PROT_WRITE */)) {
         VM_Destroy_Compiled(vm);
         DIE("mprotect failed");
     }
     // clear icache, http://blogs.arm.com/software-enablement/141-caches-and-self-modifying-code/
     __clear_cache(vm->codeBase, vm->codeBase+vm->codeLength);
     vm->destroy = VM_Destroy_Compiled;
     vm->compiled = qtrue;
 }
Referenced by VM_Create().
VM_Destroy_Compiled()
static void VM_Destroy_Compiled (vm_t * vm) static
Definition at line 202 of file vm_armv7l.c.
 {
     if (vm->codeBase) {
         if (munmap(vm->codeBase, vm->codeLength))
             Com_Printf(S_COLOR_RED "Memory unmap failed, possible memory leak\n");
     }
     vm->codeBase = NULL;
 }
Referenced by VM_Compile().
Variable Documentation
vm_opInfo
const unsigned char vm_opInfo[256] static
Definition at line 108 of file vm_armv7l.c.
Referenced by VM_Compile().