ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_session.c File Reference
g_session.c File Reference
#include "g_local.h"
Functions
void G_WriteClientSessionData (gclient_t *client)
void G_ReadSessionData (gclient_t *client)
void G_InitSessionData (gclient_t *client, char *userinfo)
void G_InitWorldSession (void)
void G_WriteSessionData (void)
Function Documentation
G_InitSessionData()
void G_InitSessionData (gclient_t * client, char * userinfo)
Definition at line 104 of file g_session.c.
 {
     clientSession_t* sess;
     const char* value;
     sess = &client->sess;
     // check for team preference, mainly for bots
     value = Info_ValueForKey(userinfo, "teampref");
     // check for human's team preference set by start server menu
     if (!value[0] && g_localTeamPref.string[0] && client->pers.localClient) {
         value = g_localTeamPref.string;
         // clear team so it's only used once
         trap_Cvar_Set("g_localTeamPref", "");
     }
     // initial team determination
     if (g_gametype.integer >= GT_TEAM) {
         // always spawn as spectator in team games
         sess->sessionTeam = TEAM_SPECTATOR;
         sess->spectatorState = SPECTATOR_FREE;
         if (value[0] || g_teamAutoJoin.integer) {
             SetTeam(&g_entities[client - level.clients], value);
         }
     } else {
         if (value[0] == 's') {
             // a willing spectator, not a waiting-in-line
             sess->sessionTeam = TEAM_SPECTATOR;
         } else {
             switch (g_gametype.integer) {
             default:
             case GT_FFA:
             case GT_SINGLE_PLAYER:
                 if (g_maxGameClients.integer > 0 &&
                     level.numNonSpectatorClients >= g_maxGameClients.integer) {
                     sess->sessionTeam = TEAM_SPECTATOR;
                 } else {
                     sess->sessionTeam = TEAM_FREE;
                 }
                 break;
             case GT_TOURNAMENT:
                 // if the game is full, go into a waiting mode
                 if (level.numNonSpectatorClients >= 2) {
                     sess->sessionTeam = TEAM_SPECTATOR;
                 } else {
                     sess->sessionTeam = TEAM_FREE;
                 }
                 break;
             }
         }
         sess->spectatorState = SPECTATOR_FREE;
     }
     AddTournamentQueue(client);
     G_WriteClientSessionData(client);
 }
References AddTournamentQueue(), level_locals_t::clients, g_entities, g_gametype, g_localTeamPref, g_maxGameClients, g_teamAutoJoin, G_WriteClientSessionData(), GT_FFA, GT_SINGLE_PLAYER, GT_TEAM, GT_TOURNAMENT, Info_ValueForKey(), vmCvar_t::integer, level, clientPersistant_t::localClient, level_locals_t::numNonSpectatorClients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), SPECTATOR_FREE, clientSession_t::spectatorState, vmCvar_t::string, TEAM_FREE, TEAM_SPECTATOR, and trap_Cvar_Set().
Referenced by ClientConnect().
G_InitWorldSession()
void G_InitWorldSession (void)
Definition at line 173 of file g_session.c.
 {
     char    s[MAX_STRING_CHARS];
     int            gt;
     trap_Cvar_VariableStringBuffer("session", s, sizeof(s));
     gt = atoi(s);
     // if the gametype changed since the last session, don't use any
     // client sessions
     if (g_gametype.integer != gt) {
         level.newSession = qtrue;
         G_Printf("Gametype changed, clearing session data.\n");
     }
 }
References g_gametype, G_Printf(), gt, level, MAX_STRING_CHARS, level_locals_t::newSession, qtrue, s, and trap_Cvar_VariableStringBuffer().
Referenced by G_InitGame().
G_ReadSessionData()
void G_ReadSessionData (gclient_t * client)
Definition at line 70 of file g_session.c.
 {
     char    s[MAX_STRING_CHARS];
     const char* var;
     int teamLeader;
     int spectatorState;
     int sessionTeam;
     var = va("session%i", (int)(client - level.clients));
     trap_Cvar_VariableStringBuffer(var, s, sizeof(s));
     sscanf(s, "%i %i %i %i %i %i %i",
         &sessionTeam,
         &client->sess.spectatorNum,
         &spectatorState,
         &client->sess.spectatorClient,
         &client->sess.wins,
         &client->sess.losses,
         &teamLeader
     );
     client->sess.sessionTeam = (team_t)sessionTeam;
     client->sess.spectatorState = (spectatorState_t)spectatorState;
     client->sess.teamLeader = (qboolean)teamLeader;
 }
References level_locals_t::clients, level, clientSession_t::losses, MAX_STRING_CHARS, s, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::spectatorClient, clientSession_t::spectatorNum, clientSession_t::spectatorState, clientSession_t::teamLeader, trap_Cvar_VariableStringBuffer(), va(), and clientSession_t::wins.
Referenced by ClientConnect().
G_WriteClientSessionData()
void G_WriteClientSessionData (gclient_t * client)
Definition at line 43 of file g_session.c.
 {
     const char* s;
     const char* var;
     s = va("%i %i %i %i %i %i %i",
         client->sess.sessionTeam,
         client->sess.spectatorNum,
         client->sess.spectatorState,
         client->sess.spectatorClient,
         client->sess.wins,
         client->sess.losses,
         client->sess.teamLeader
     );
     var = va("session%i", (int)(client - level.clients));
     trap_Cvar_Set(var, s);
 }
References level_locals_t::clients, level, clientSession_t::losses, s, gclient_s::sess, clientSession_t::sessionTeam, clientSession_t::spectatorClient, clientSession_t::spectatorNum, clientSession_t::spectatorState, clientSession_t::teamLeader, trap_Cvar_Set(), va(), and clientSession_t::wins.
Referenced by G_InitSessionData(), and G_WriteSessionData().
G_WriteSessionData()
void G_WriteSessionData (void)
Definition at line 195 of file g_session.c.
 {
     int        i;
     trap_Cvar_Set("session", va("%i", g_gametype.integer));
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected == CON_CONNECTED) {
             G_WriteClientSessionData(&level.clients[i]);
         }
     }
 }
References level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, g_gametype, G_WriteClientSessionData(), level, level_locals_t::maxclients, gclient_s::pers, trap_Cvar_Set(), and va().
Referenced by ExitLevel(), and G_ShutdownGame().