ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_log.h File Reference
l_log.h File Reference
Functions
void Log_Open (char *filename)
void Log_Close (void)
void Log_Shutdown (void)
void QDECL Log_Write (char *fmt,...) __attribute__((format(printf
void QDECL void QDECL Log_WriteTimeStamped (char *fmt,...) __attribute__((format(printf
void QDECL void QDECL FILE * Log_FilePointer (void)
void Log_Flush (void)
Function Documentation
Log_Close()
void Log_Close (void)
Definition at line 90 of file l_log.c.
 {
     if (!logfile.fp) return;
     if (fclose(logfile.fp))
     {
         botimport.Print(PRT_ERROR, "can't close log file %s\n", logfile.filename);
         return;
     } //end if
     logfile.fp = NULL;
     botimport.Print(PRT_MESSAGE, "Closed log %s\n", logfile.filename);
 } //end of the function Log_Close
Referenced by Log_Shutdown().
Log_FilePointer()
void QDECL void QDECL FILE* Log_FilePointer (void)
Definition at line 159 of file l_log.c.
 {
     return logfile.fp;
 } //end of the function Log_FilePointer
Referenced by BotDumpMatchTemplates(), BotDumpRandomStringList(), BotDumpReplyChat(), and BotDumpSynonymList().
Log_Flush()
void Log_Flush (void)
Definition at line 169 of file l_log.c.
 {
     if (logfile.fp) fflush(logfile.fp);
 } //end of the function Log_Flush
Log_Open()
void Log_Open (char * filename)
Definition at line 60 of file l_log.c.
 {
     char *ospath;
     if (!LibVarValue("log", "0")) return;
     if (!filename || !strlen(filename))
     {
         botimport.Print(PRT_MESSAGE, "openlog <filename>\n");
         return;
     } //end if
     if (logfile.fp)
     {
         botimport.Print(PRT_ERROR, "log file %s is already opened\n", logfile.filename);
         return;
     } //end if
     ospath = FS_BuildOSPath(Cvar_VariableString("fs_homepath"), Cvar_VariableString("fs_game"), filename);
     logfile.fp = fopen(ospath, "wb");
     if (!logfile.fp)
     {
         botimport.Print(PRT_ERROR, "can't open the log file %s\n", filename);
         return;
     } //end if
     Q_strncpyz(logfile.filename, filename, MAX_LOGFILENAMESIZE);
     botimport.Print(PRT_MESSAGE, "Opened log %s\n", logfile.filename);
 } //end of the function Log_Create
Referenced by Export_BotLibSetup().
Log_Shutdown()
void Log_Shutdown (void)
Definition at line 107 of file l_log.c.
 {
     if (logfile.fp) Log_Close();
 } //end of the function Log_Shutdown
Referenced by Export_BotLibShutdown().
Log_Write()
void QDECL Log_Write (char * fmt, ...)
Log_WriteTimeStamped()
void QDECL void QDECL Log_WriteTimeStamped (char * fmt, ...)