ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/q_shared.h File Reference
q_shared.h File Reference
included first by ALL program modules.
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdarg.h>
#include <string.h>
#include <stddef.h>
#include <stdlib.h>
#include <time.h>
#include <ctype.h>
#include <limits.h>
#include <stdint.h>
#include "q_platform.h"
#include "surfaceflags.h"
Classes
union floatint_t
struct pc_token_s
struct qint64
struct cvar_s
CVARS (console variables).
struct vmCvar_t
The modules that run in the virtual machine can't access the cvar_t directly, so they must ask for structured updates.
struct cplane_s
struct trace_t
A trace is returned when a box is swept through the world.
struct markFragment_t
struct orientation_t
struct gameState_t
struct playerState_s
playerState_t is a full superset of entityState_t as it is used by players, so if a playerState_t is transmitted, the entityState_t can be fully derived from it.
struct usercmd_s
usercmd_t is sent to the server each client frame.
struct trajectory_t
struct entityState_s
entityState_t is the information conveyed from the server in an update message about entities that the client will need to render in some way.
struct glyphInfo_t
struct fontInfo_t
struct qtime_s
Macros
#define PRODUCT_NAME "ioq3"
#define BASEGAME "baseq3"
#define CLIENT_WINDOW_TITLE "ioquake3"
#define CLIENT_WINDOW_MIN_TITLE "ioq3"
#define HOMEPATH_NAME_UNIX ".q3a"
#define HOMEPATH_NAME_WIN "Quake3"
#define HOMEPATH_NAME_MACOSX HOMEPATH_NAME_WIN
#define STEAMPATH_NAME "Quake 3 Arena"
#define STEAMPATH_APPID "2200"
#define GOGPATH_ID "1441704920"
#define GAMENAME_FOR_MASTER "Quake3Arena"
#define CINEMATICS_LOGO "idlogo.RoQ"
#define CINEMATICS_INTRO "intro.RoQ"
#define LEGACY_PROTOCOL
#define HEARTBEAT_FOR_MASTER "DarkPlaces"
Heartbeat for dpmaster protocol. You shouldn't change this unless you know what you're doing.
#define LEGACY_MASTER_GAMENAME "Quake3Arena"
When com_gamename is LEGACY_MASTER_GAMENAME, use quake3 master protocol.
#define LEGACY_HEARTBEAT_FOR_MASTER "QuakeArena-1"
#define BASETA "missionpack"
#define PRODUCT_VERSION "1.36"
#define PRODUCT_DATE __DATE__
#define Q3_VERSION PRODUCT_NAME " " PRODUCT_VERSION
#define MAX_TEAMNAME 32
#define MAX_MASTER_SERVERS 5
number of supported master servers.
#define DEMOEXT "dm_"
standard demo extension.
#define __attribute__(x)
#define UNUSED_VAR
#define Q_EXPORT
#define PAD(base, alignment) (((base)+(alignment)-1) & ~((alignment)-1))
#define PADLEN(base, alignment) (PAD((base), (alignment)) - (base))
#define PADP(base, alignment) ((void *) PAD((intptr_t) (base), (alignment)))
#define QALIGN(x)
#define NULL ((void *)0)
#define STRING(s) #s
#define XSTRING(s) STRING(s)
#define MAX_QINT 0x7fffffff
#define MIN_QINT (-MAX_QINT-1)
#define ARRAY_LEN(x) (sizeof(x) / sizeof(*(x)))
#define STRARRAY_LEN(x) (ARRAY_LEN(x) - 1)
#define PITCH 0
#define YAW 1
#define ROLL 2
#define MAX_STRING_CHARS 1024
#define MAX_STRING_TOKENS 1024
#define MAX_TOKEN_CHARS 1024
#define MAX_INFO_STRING 1024
#define MAX_INFO_KEY 1024
#define MAX_INFO_VALUE 1024
#define BIG_INFO_STRING 8192
#define BIG_INFO_KEY 8192
#define BIG_INFO_VALUE 8192
#define MAX_QPATH 64
#define MAX_OSPATH 256
#define MAX_NAME_LENGTH 32
#define MAX_SAY_TEXT 150
#define MAX_MAP_AREA_BYTES 32
#define PROP_GAP_WIDTH 3
#define PROP_SPACE_WIDTH 8
#define PROP_HEIGHT 27
#define PROP_SMALL_SIZE_SCALE 0.75
#define BLINK_DIVISOR 200
#define PULSE_DIVISOR 75
#define UI_LEFT 0x00000000
#define UI_CENTER 0x00000001
#define UI_RIGHT 0x00000002
#define UI_FORMATMASK 0x00000007
#define UI_SMALLFONT 0x00000010
#define UI_BIGFONT 0x00000020
#define UI_GIANTFONT 0x00000040
#define UI_DROPSHADOW 0x00000800
#define UI_BLINK 0x00001000
#define UI_INVERSE 0x00002000
#define UI_PULSE 0x00004000
#define HUNK_DEBUG
#define Hunk_Alloc(size, preference) Hunk_AllocDebug(size, preference, #size, __FILE__, __LINE__)
#define Com_Memset memset
#define Com_Memcpy memcpy
#define CIN_system 1
#define CIN_loop 2
#define CIN_hold 4
#define CIN_silent 8
#define CIN_shader 16
#define M_PI 3.14159265358979323846f
#define NUMVERTEXNORMALS 162
#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define TINYCHAR_WIDTH (SMALLCHAR_WIDTH)
#define TINYCHAR_HEIGHT (SMALLCHAR_HEIGHT/2)
#define SMALLCHAR_WIDTH 8
#define SMALLCHAR_HEIGHT 16
#define BIGCHAR_WIDTH 16
#define BIGCHAR_HEIGHT 16
#define GIANTCHAR_WIDTH 32
#define GIANTCHAR_HEIGHT 48
#define Q_COLOR_ESCAPE '^'
#define COLOR_BLACK '0'
#define COLOR_RED '1'
#define COLOR_GREEN '2'
#define COLOR_YELLOW '3'
#define COLOR_BLUE '4'
#define COLOR_CYAN '5'
#define COLOR_MAGENTA '6'
#define COLOR_WHITE '7'
#define ColorIndexForNumber(c) ((c) & 0x07)
#define ColorIndex(c) (ColorIndexForNumber((c) - '0'))
#define S_COLOR_BLACK "^0"
#define S_COLOR_RED "^1"
#define S_COLOR_GREEN "^2"
#define S_COLOR_YELLOW "^3"
#define S_COLOR_BLUE "^4"
#define S_COLOR_CYAN "^5"
#define S_COLOR_MAGENTA "^6"
#define S_COLOR_WHITE "^7"
#define MAKERGB(v, r, g, b) v[0]=r;v[1]=g;v[2]=b
#define MAKERGBA(v, r, g, b, a) v[0]=r;v[1]=g;v[2]=b;v[3]=a
#define DEG2RAD(a) (((a) * M_PI) / 180.0F)
#define RAD2DEG(a) (((a) * 180.0f) / M_PI)
#define nanmask (255<<23)
#define IS_NAN(x) (((*(int *)&x)&nanmask)==nanmask)
#define Q_ftol lrintf
#define Q_SnapVector(vec)
#define SQRTFAST(x) ((x) * Q_rsqrt(x))
#define DotProduct(x, y) ((x)[0]*(y)[0]+(x)[1]*(y)[1]+(x)[2]*(y)[2])
#define VectorSubtract(a, b, c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
#define VectorAdd(a, b, c) ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
#define VectorCopy(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2])
#define VectorScale(v, s, o) ((o)[0]=(v)[0]*(s),(o)[1]=(v)[1]*(s),(o)[2]=(v)[2]*(s))
#define VectorMA(v, s, b, o) ((o)[0]=(v)[0]+(b)[0]*(s),(o)[1]=(v)[1]+(b)[1]*(s),(o)[2]=(v)[2]+(b)[2]*(s))
#define VectorClear(a) ((a)[0]=(a)[1]=(a)[2]=0)
#define VectorNegate(a, b) ((b)[0]=-(a)[0],(b)[1]=-(a)[1],(b)[2]=-(a)[2])
#define VectorSet(v, x, y, z) ((v)[0]=(x), (v)[1]=(y), (v)[2]=(z))
#define Vector4Copy(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
#define Byte4Copy(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
#define QuatCopy(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
#define SnapVector(v) {v[0]=((int)(v[0]));v[1]=((int)(v[1]));v[2]=((int)(v[2]));}
#define random() ((rand () & 0x7fff) / ((float)0x7fff))
#define crandom() (2.0 * (random() - 0.5))
#define MAX(x, y) ((x)>(y)?(x):(y))
#define MIN(x, y) ((x)<(y)?(x):(y))
#define MAX_TOKENLENGTH 1024
#define TT_STRING 1
#define TT_LITERAL 2
#define TT_NUMBER 3
#define TT_NAME 4
#define TT_PUNCTUATION 5
#define TRUNCATE_LENGTH 64
#define CVAR_ARCHIVE 0x0001
Set to cause it to be saved to vars.rc.
#define CVAR_USERINFO 0x0002
sent to server on connect or change.
#define CVAR_SERVERINFO 0x0004
sent in response to front end requests.
#define CVAR_SYSTEMINFO 0x0008
these cvars will be duplicated on all clients.
#define CVAR_INIT 0x0010
Don't allow change from console at all, but can be set from the command line.
#define CVAR_LATCH 0x0020
Will only change when C code next does a Cvar_Get(), so it can't be changed without proper initialization.
#define CVAR_ROM 0x0040
#define CVAR_USER_CREATED 0x0080
#define CVAR_TEMP 0x0100
#define CVAR_CHEAT 0x0200
#define CVAR_NORESTART 0x0400
#define CVAR_SERVER_CREATED 0x0800
#define CVAR_VM_CREATED 0x1000
#define CVAR_PROTECTED 0x2000
#define CVAR_MODIFIED 0x40000000
#define CVAR_NONEXISTENT 0x80000000
#define MAX_CVAR_VALUE_STRING 256
#define VOIP_SPATIAL 0x01
#define VOIP_DIRECT 0x02
#define VOIP_FLAGCNT 2
#define PLANE_X 0
#define PLANE_Y 1
#define PLANE_Z 2
#define PLANE_NON_AXIAL 3
#define PlaneTypeForNormal(x) (x[0] == 1.0 ? PLANE_X : (x[1] == 1.0 ? PLANE_Y : (x[2] == 1.0 ? PLANE_Z : PLANE_NON_AXIAL)))
#define KEYCATCH_CONSOLE 0x0001
#define KEYCATCH_UI 0x0002
#define KEYCATCH_MESSAGE 0x0004
#define KEYCATCH_CGAME 0x0008
#define ANGLE2SHORT(x) ((int)((x)*65536/360) & 65535)
#define SHORT2ANGLE(x) ((x)*(360.0/65536))
#define SNAPFLAG_RATE_DELAYED 1
#define SNAPFLAG_NOT_ACTIVE 2
#define SNAPFLAG_SERVERCOUNT 4
#define MAX_CLIENTS 64
#define MAX_LOCATIONS 64
#define GENTITYNUM_BITS 10
#define MAX_GENTITIES (1<<GENTITYNUM_BITS)
#define ENTITYNUM_NONE (MAX_GENTITIES-1)
#define ENTITYNUM_WORLD (MAX_GENTITIES-2)
#define ENTITYNUM_MAX_NORMAL (MAX_GENTITIES-2)
#define MAX_MODELS 256
#define MAX_SOUNDS 256
#define MAX_CONFIGSTRINGS 1024
#define CS_SERVERINFO 0
#define CS_SYSTEMINFO 1
#define RESERVED_CONFIGSTRINGS 2
#define MAX_GAMESTATE_CHARS 16000
#define MAX_STATS 16
#define MAX_PERSISTANT 16
#define MAX_POWERUPS 16
#define MAX_WEAPONS 16
#define MAX_PS_EVENTS 2
#define PS_PMOVEFRAMECOUNTBITS 6
#define BUTTON_ATTACK 1
#define BUTTON_TALK 2
#define BUTTON_USE_HOLDABLE 4
#define BUTTON_GESTURE 8
#define BUTTON_WALKING 16
#define BUTTON_AFFIRMATIVE 32
#define BUTTON_NEGATIVE 64
#define BUTTON_GETFLAG 128
#define BUTTON_GUARDBASE 256
#define BUTTON_PATROL 512
#define BUTTON_FOLLOWME 1024
#define BUTTON_ANY 2048
#define MOVE_RUN 120
#define SOLID_BMODEL 0xffffff
#define GLYPH_START 0
#define GLYPH_END 255
#define GLYPH_CHARSTART 32
#define GLYPH_CHAREND 127
#define GLYPHS_PER_FONT GLYPH_END - GLYPH_START + 1
#define Square(x) ((x)*(x))
#define AS_LOCAL 0
#define AS_MPLAYER 1
#define AS_GLOBAL 2
#define AS_FAVORITES 3
#define MAX_GLOBAL_SERVERS 4096
#define MAX_OTHER_SERVERS 128
#define MAX_PINGREQUESTS 32
#define MAX_SERVERSTATUSREQUESTS 16
#define SAY_ALL 0
#define SAY_TEAM 1
#define SAY_TELL 2
#define CDKEY_LEN 16
#define CDCHKSUM_LEN 2
#define LERP(a, b, w) ((a) * (1.0f - (w)) + (b) * (w))
#define LUMA(red, green, blue) (0.2126f * (red) + 0.7152f * (green) + 0.0722f * (blue))
Typedefs
typedef unsigned char byte
typedef int qhandle_t
typedef int sfxHandle_t
typedef int fileHandle_t
typedef int clipHandle_t
typedef float vec_t
typedef vec_t vec2_t[2]
typedef vec_t vec3_t[3]
typedef vec_t vec4_t[4]
typedef vec_t vec5_t[5]
typedef vec_t quat_t[4]
typedef int fixed4_t
typedef int fixed8_t
typedef int fixed16_t
typedef struct pc_token_s pc_token_t
typedef struct cvar_s cvar_t
Nothing outside the Cvar_*() functions should modify these fields.
typedef int cvarHandle_t
typedef struct cplane_s cplane_t
typedef struct playerState_s playerState_t
playerState_t is a full superset of entityState_t as it is used by players, so if a playerState_t is transmitted, the entityState_t can be fully derived from it.
typedef struct usercmd_s usercmd_t
usercmd_t is sent to the server each client frame.
typedef struct entityState_s entityState_t
entityState_t is the information conveyed from the server in an update message about entities that the client will need to render in some way.
typedef struct qtime_s qtime_t
typedef enum _flag_status flagStatus_t
State of flag.
Enumerations
enum qboolean { qfalse, qtrue }
enum cbufExec_t { EXEC_NOW, EXEC_INSERT, EXEC_APPEND }
enum printParm_t { PRINT_ALL, PRINT_DEVELOPER, PRINT_WARNING, PRINT_ERROR }
enum errorParm_t {
ERR_FATAL, ERR_DROP, ERR_SERVERDISCONNECT, ERR_DISCONNECT,
ERR_NEED_CD
}
enum ha_pref { h_high, h_low, h_dontcare }
enum fsMode_t { FS_READ, FS_WRITE, FS_APPEND, FS_APPEND_SYNC }
enum fsOrigin_t { FS_SEEK_CUR, FS_SEEK_END, FS_SEEK_SET }
enum soundChannel_t {
CHAN_AUTO, CHAN_LOCAL, CHAN_WEAPON, CHAN_VOICE,
CHAN_ITEM, CHAN_BODY, CHAN_LOCAL_SOUND, CHAN_ANNOUNCER
}
enum trType_t {
TR_STATIONARY, TR_INTERPOLATE, TR_LINEAR, TR_LINEAR_STOP,
TR_SINE, TR_GRAVITY
}
enum connstate_t {
CA_UNINITIALIZED, CA_DISCONNECTED, CA_AUTHORIZING, CA_CONNECTING,
CA_CHALLENGING, CA_CONNECTED, CA_LOADING, CA_PRIMED,
CA_ACTIVE, CA_CINEMATIC
}
Connection state.
enum e_status {
FMV_IDLE, FMV_PLAY, FMV_EOF, FMV_ID_BLT,
FMV_ID_IDLE, FMV_LOOPED, FMV_ID_WAIT
}
cinematic states.
enum _flag_status {
FLAG_ATBASE = 0, FLAG_TAKEN, FLAG_TAKEN_RED, FLAG_TAKEN_BLUE,
FLAG_DROPPED
}
State of flag.
Functions
int Q_vsnprintf (char *str, size_t size, const char *format, va_list ap)
void * Hunk_AllocDebug (int size, ha_pref preference, char *label, char *file, int line)
qboolean Q_IsColorString (const char *p)
int Q_isnan (float x)
float Q_fabs (float f)
float Q_rsqrt (float f)
signed char ClampChar (int i)
signed short ClampShort (int i)
int DirToByte (vec3_t dir)
void ByteToDir (int b, vec3_t dir)
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
void _VectorCopy (const vec3_t in, vec3_t out)
void _VectorScale (const vec3_t in, float scale, vec3_t out)
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
unsigned ColorBytes3 (float r, float g, float b)
unsigned ColorBytes4 (float r, float g, float b, float a)
float NormalizeColor (const vec3_t in, vec3_t out)
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
void ClearBounds (vec3_t mins, vec3_t maxs)
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
static ID_INLINE int VectorCompare (const vec3_t v1, const vec3_t v2)
static ID_INLINE vec_t VectorLength (const vec3_t v)
static ID_INLINE vec_t VectorLengthSquared (const vec3_t v)
static ID_INLINE vec_t Distance (const vec3_t p1, const vec3_t p2)
static ID_INLINE vec_t DistanceSquared (const vec3_t p1, const vec3_t p2)
static ID_INLINE void VectorNormalizeFast (vec3_t v)
static ID_INLINE void VectorInverse (vec3_t v)
static ID_INLINE void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross)
vec_t VectorNormalize (vec3_t v)
vec_t VectorNormalize2 (const vec3_t v, vec3_t out)
void Vector4Scale (const vec4_t in, vec_t scale, vec4_t out)
void VectorRotate (vec3_t in, vec3_t matrix[3], vec3_t out)
int Q_log2 (int val)
float Q_acos (float c)
int Q_rand (int *seed)
float Q_random (int *seed)
float Q_crandom (int *seed)
void vectoangles (const vec3_t value1, vec3_t angles)
void AnglesToAxis (const vec3_t angles, vec3_t axis[3])
void AxisClear (vec3_t axis[3])
void AxisCopy (vec3_t in[3], vec3_t out[3])
void SetPlaneSignbits (struct cplane_s *out)
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s *plane)
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
float AngleMod (float a)
float LerpAngle (float from, float to, float frac)
float AngleSubtract (float a1, float a2)
void AnglesSubtract (vec3_t v1, vec3_t v2, vec3_t v3)
float AngleNormalize360 (float angle)
float AngleNormalize180 (float angle)
float AngleDelta (float angle1, float angle2)
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
void RotateAroundDirection (vec3_t axis[3], float yaw)
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
void PerpendicularVector (vec3_t dst, const vec3_t src)
float Com_Clamp (float min, float max, float value)
char * COM_SkipPath (char *pathname)
const char * COM_GetExtension (const char *name)
void COM_StripExtension (const char *in, char *out, int destsize)
qboolean COM_CompareExtension (const char *in, const char *ext)
void COM_DefaultExtension (char *path, int maxSize, const char *extension)
void COM_BeginParseSession (const char *name)
int COM_GetCurrentParseLine (void)
char * COM_Parse (char **data_p)
char * COM_ParseExt (char **data_p, qboolean allowLineBreak)
int COM_Compress (char *data_p)
void COM_ParseError (char *format,...) __attribute__((format(printf
void void COM_ParseWarning (char *format,...) __attribute__((format(printf
void COM_MatchToken (char **buf_p, char *match)
qboolean SkipBracedSection (char **program, int depth)
void SkipRestOfLine (char **data)
void Parse1DMatrix (char **buf_p, int x, float *m)
void Parse2DMatrix (char **buf_p, int y, int x, float *m)
void Parse3DMatrix (char **buf_p, int z, int y, int x, float *m)
int Com_HexStrToInt (const char *str)
int QDECL Com_sprintf (char *dest, int size, const char *fmt,...) __attribute__((format(printf
int QDECL char * Com_SkipTokens (char *s, int numTokens, char *sep)
char * Com_SkipCharset (char *s, char *sep)
void Com_RandomBytes (byte *string, int len)
int Q_isprint (int c)
int Q_islower (int c)
int Q_isupper (int c)
int Q_isalpha (int c)
qboolean Q_isanumber (const char *s)
qboolean Q_isintegral (float f)
int Q_stricmp (const char *s1, const char *s2)
int Q_strncmp (const char *s1, const char *s2, int n)
int Q_stricmpn (const char *s1, const char *s2, int n)
char * Q_strlwr (char *s1)
char * Q_strupr (char *s1)
const char * Q_stristr (const char *s, const char *find)
void Q_strncpyz (char *dest, const char *src, int destsize)
void Q_strcat (char *dest, int size, const char *src)
int Q_PrintStrlen (const char *string)
char * Q_CleanStr (char *string)
int Q_CountChar (const char *string, char tocount)
char *QDECL va (char *format,...) __attribute__((format(printf
void Com_TruncateLongString (char *buffer, const char *s)
char * Info_ValueForKey (const char *s, const char *key)
void Info_RemoveKey (char *s, const char *key)
void Info_RemoveKey_Big (char *s, const char *key)
void Info_SetValueForKey (char *s, const char *key, const char *value)
void Info_SetValueForKey_Big (char *s, const char *key, const char *value)
qboolean Info_Validate (const char *s)
void Info_NextPair (const char **s, char *key, char *value)
void QDECL Com_Error (int level, const char *error,...) __attribute__((noreturn
void QDECL format (printf, 2, 3)))
void QDECL Com_Printf (const char *msg,...) __attribute__((format(printf
Variables
vec3_t bytedirs [NUMVERTEXNORMALS]
vec4_t colorBlack
vec4_t colorRed
vec4_t colorGreen
vec4_t colorBlue
vec4_t colorYellow
vec4_t colorMagenta
vec4_t colorCyan
vec4_t colorWhite
vec4_t colorLtGrey
vec4_t colorMdGrey
vec4_t colorDkGrey
vec4_t g_color_table [8]
vec3_t vec3_origin
vec3_t axisDefault [3]
Detailed Description
included first by ALL program modules.
A user mod should never modify this file.
Definition in file q_shared.h.
Macro Definition Documentation
__attribute__
#define __attribute__ (x)
Definition at line 117 of file q_shared.h.
ANGLE2SHORT
#define ANGLE2SHORT (x) ((int)((x)*65536/360) & 65535)
Definition at line 1107 of file q_shared.h.
ARRAY_LEN
#define ARRAY_LEN (x) (sizeof(x) / sizeof(*(x)))
Definition at line 239 of file q_shared.h.
AS_FAVORITES
#define AS_FAVORITES 3
Definition at line 1436 of file q_shared.h.
AS_GLOBAL
#define AS_GLOBAL 2
Definition at line 1435 of file q_shared.h.
AS_LOCAL
#define AS_LOCAL 0
Definition at line 1433 of file q_shared.h.
AS_MPLAYER
#define AS_MPLAYER 1
Definition at line 1434 of file q_shared.h.
BASEGAME
#define BASEGAME "baseq3"
Definition at line 48 of file q_shared.h.
BASETA
#define BASETA "missionpack"
Definition at line 71 of file q_shared.h.
BIG_INFO_KEY
#define BIG_INFO_KEY 8192
Definition at line 258 of file q_shared.h.
BIG_INFO_STRING
#define BIG_INFO_STRING 8192
Definition at line 257 of file q_shared.h.
BIG_INFO_VALUE
#define BIG_INFO_VALUE 8192
Definition at line 259 of file q_shared.h.
BIGCHAR_HEIGHT
#define BIGCHAR_HEIGHT 16
Definition at line 399 of file q_shared.h.
BIGCHAR_WIDTH
#define BIGCHAR_WIDTH 16
Definition at line 398 of file q_shared.h.
BLINK_DIVISOR
#define BLINK_DIVISOR 200
Definition at line 318 of file q_shared.h.
BUTTON_AFFIRMATIVE
#define BUTTON_AFFIRMATIVE 32
Definition at line 1265 of file q_shared.h.
BUTTON_ANY
#define BUTTON_ANY 2048
Definition at line 1273 of file q_shared.h.
BUTTON_ATTACK
#define BUTTON_ATTACK 1
Definition at line 1256 of file q_shared.h.
BUTTON_FOLLOWME
#define BUTTON_FOLLOWME 1024
Definition at line 1271 of file q_shared.h.
BUTTON_GESTURE
#define BUTTON_GESTURE 8
Definition at line 1259 of file q_shared.h.
BUTTON_GETFLAG
#define BUTTON_GETFLAG 128
Definition at line 1268 of file q_shared.h.
BUTTON_GUARDBASE
#define BUTTON_GUARDBASE 256
Definition at line 1269 of file q_shared.h.
BUTTON_NEGATIVE
#define BUTTON_NEGATIVE 64
Definition at line 1266 of file q_shared.h.
BUTTON_PATROL
#define BUTTON_PATROL 512
Definition at line 1270 of file q_shared.h.
BUTTON_TALK
#define BUTTON_TALK 2
Definition at line 1257 of file q_shared.h.
BUTTON_USE_HOLDABLE
#define BUTTON_USE_HOLDABLE 4
Definition at line 1258 of file q_shared.h.
BUTTON_WALKING
#define BUTTON_WALKING 16
Definition at line 1260 of file q_shared.h.
Byte4Copy
#define Byte4Copy (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
Definition at line 586 of file q_shared.h.
CDCHKSUM_LEN
#define CDCHKSUM_LEN 2
Definition at line 1472 of file q_shared.h.
CDKEY_LEN
#define CDKEY_LEN 16
Definition at line 1471 of file q_shared.h.
CIN_hold
#define CIN_hold 4
Definition at line 355 of file q_shared.h.
CIN_loop
#define CIN_loop 2
Definition at line 354 of file q_shared.h.
CIN_shader
#define CIN_shader 16
Definition at line 357 of file q_shared.h.
CIN_silent
#define CIN_silent 8
Definition at line 356 of file q_shared.h.
CIN_system
#define CIN_system 1
Definition at line 353 of file q_shared.h.
CINEMATICS_INTRO
#define CINEMATICS_INTRO "intro.RoQ"
Definition at line 59 of file q_shared.h.
CINEMATICS_LOGO
#define CINEMATICS_LOGO "idlogo.RoQ"
Definition at line 58 of file q_shared.h.
CLIENT_WINDOW_MIN_TITLE
#define CLIENT_WINDOW_MIN_TITLE "ioq3"
Definition at line 50 of file q_shared.h.
CLIENT_WINDOW_TITLE
#define CLIENT_WINDOW_TITLE "ioquake3"
Definition at line 49 of file q_shared.h.
COLOR_BLACK
#define COLOR_BLACK '0'
Definition at line 419 of file q_shared.h.
COLOR_BLUE
#define COLOR_BLUE '4'
Definition at line 423 of file q_shared.h.
COLOR_CYAN
#define COLOR_CYAN '5'
Definition at line 424 of file q_shared.h.
COLOR_GREEN
#define COLOR_GREEN '2'
Definition at line 421 of file q_shared.h.
COLOR_MAGENTA
#define COLOR_MAGENTA '6'
Definition at line 425 of file q_shared.h.
COLOR_RED
#define COLOR_RED '1'
Definition at line 420 of file q_shared.h.
COLOR_WHITE
#define COLOR_WHITE '7'
Definition at line 426 of file q_shared.h.
COLOR_YELLOW
#define COLOR_YELLOW '3'
Definition at line 422 of file q_shared.h.
ColorIndex
#define ColorIndex (c) (ColorIndexForNumber((c) - '0'))
Definition at line 428 of file q_shared.h.
ColorIndexForNumber
#define ColorIndexForNumber (c) ((c) & 0x07)
Definition at line 427 of file q_shared.h.
Com_Memcpy
#define Com_Memcpy memcpy
Definition at line 351 of file q_shared.h.
Com_Memset
#define Com_Memset memset
Definition at line 350 of file q_shared.h.
crandom
#define crandom () (2.0 * (random() - 0.5))
Definition at line 702 of file q_shared.h.
CS_SERVERINFO
#define CS_SERVERINFO 0
Definition at line 1139 of file q_shared.h.
CS_SYSTEMINFO
#define CS_SYSTEMINFO 1
Definition at line 1140 of file q_shared.h.
CVAR_ARCHIVE
#define CVAR_ARCHIVE 0x0001
Set to cause it to be saved to vars.rc.
Used for system variables, not for player specific configurations.
Definition at line 914 of file q_shared.h.
CVAR_CHEAT
#define CVAR_CHEAT 0x0200
Definition at line 931 of file q_shared.h.
CVAR_INIT
#define CVAR_INIT 0x0010
Don't allow change from console at all, but can be set from the command line.
Definition at line 921 of file q_shared.h.
CVAR_LATCH
#define CVAR_LATCH 0x0020
Will only change when C code next does a Cvar_Get(), so it can't be changed without proper initialization.
Modified will be set, even though the value hasn't changed yet.
Definition at line 926 of file q_shared.h.
CVAR_MODIFIED
#define CVAR_MODIFIED 0x40000000
Definition at line 939 of file q_shared.h.
CVAR_NONEXISTENT
#define CVAR_NONEXISTENT 0x80000000
Definition at line 940 of file q_shared.h.
CVAR_NORESTART
#define CVAR_NORESTART 0x0400
Definition at line 932 of file q_shared.h.
CVAR_PROTECTED
#define CVAR_PROTECTED 0x2000
Definition at line 936 of file q_shared.h.
CVAR_ROM
#define CVAR_ROM 0x0040
Definition at line 928 of file q_shared.h.
CVAR_SERVER_CREATED
#define CVAR_SERVER_CREATED 0x0800
Definition at line 934 of file q_shared.h.
CVAR_SERVERINFO
#define CVAR_SERVERINFO 0x0004
sent in response to front end requests.
Definition at line 917 of file q_shared.h.
CVAR_SYSTEMINFO
#define CVAR_SYSTEMINFO 0x0008
these cvars will be duplicated on all clients.
Definition at line 918 of file q_shared.h.
CVAR_TEMP
#define CVAR_TEMP 0x0100
Definition at line 930 of file q_shared.h.
CVAR_USER_CREATED
#define CVAR_USER_CREATED 0x0080
Definition at line 929 of file q_shared.h.
CVAR_USERINFO
#define CVAR_USERINFO 0x0002
sent to server on connect or change.
Definition at line 916 of file q_shared.h.
CVAR_VM_CREATED
#define CVAR_VM_CREATED 0x1000
Definition at line 935 of file q_shared.h.
DEG2RAD
#define DEG2RAD (a) (((a) * M_PI) / 180.0F)
Definition at line 444 of file q_shared.h.
DEMOEXT
#define DEMOEXT "dm_"
standard demo extension.
Definition at line 86 of file q_shared.h.
DotProduct
#define DotProduct (x, y) ((x)[0]*(y)[0]+(x)[1]*(y)[1]+(x)[2]*(y)[2])
Definition at line 552 of file q_shared.h.
ENTITYNUM_MAX_NORMAL
#define ENTITYNUM_MAX_NORMAL (MAX_GENTITIES-2)
Definition at line 1128 of file q_shared.h.
ENTITYNUM_NONE
#define ENTITYNUM_NONE (MAX_GENTITIES-1)
Definition at line 1126 of file q_shared.h.
ENTITYNUM_WORLD
#define ENTITYNUM_WORLD (MAX_GENTITIES-2)
Definition at line 1127 of file q_shared.h.
GAMENAME_FOR_MASTER
#define GAMENAME_FOR_MASTER "Quake3Arena"
Definition at line 57 of file q_shared.h.
GENTITYNUM_BITS
#define GENTITYNUM_BITS 10
Definition at line 1120 of file q_shared.h.
GIANTCHAR_HEIGHT
#define GIANTCHAR_HEIGHT 48
Definition at line 402 of file q_shared.h.
GIANTCHAR_WIDTH
#define GIANTCHAR_WIDTH 32
Definition at line 401 of file q_shared.h.
GLYPH_CHAREND
#define GLYPH_CHAREND 127
Definition at line 1388 of file q_shared.h.
GLYPH_CHARSTART
#define GLYPH_CHARSTART 32
Definition at line 1387 of file q_shared.h.
GLYPH_END
#define GLYPH_END 255
Definition at line 1386 of file q_shared.h.
GLYPH_START
#define GLYPH_START 0
Definition at line 1385 of file q_shared.h.
GLYPHS_PER_FONT
#define GLYPHS_PER_FONT GLYPH_END - GLYPH_START + 1
Definition at line 1389 of file q_shared.h.
GOGPATH_ID
#define GOGPATH_ID "1441704920"
Definition at line 56 of file q_shared.h.
HEARTBEAT_FOR_MASTER
#define HEARTBEAT_FOR_MASTER "DarkPlaces"
Heartbeat for dpmaster protocol. You shouldn't change this unless you know what you're doing.
Definition at line 64 of file q_shared.h.
HOMEPATH_NAME_MACOSX
#define HOMEPATH_NAME_MACOSX HOMEPATH_NAME_WIN
Definition at line 53 of file q_shared.h.
HOMEPATH_NAME_UNIX
#define HOMEPATH_NAME_UNIX ".q3a"
Definition at line 51 of file q_shared.h.
HOMEPATH_NAME_WIN
#define HOMEPATH_NAME_WIN "Quake3"
Definition at line 52 of file q_shared.h.
Hunk_Alloc
#define Hunk_Alloc (size, preference) Hunk_AllocDebug(size, preference, #size, __FILE__, __LINE__)
Definition at line 344 of file q_shared.h.
HUNK_DEBUG
#define HUNK_DEBUG
Definition at line 334 of file q_shared.h.
IS_NAN
#define IS_NAN (x) (((*(int *)&x)&nanmask)==nanmask)
Definition at line 454 of file q_shared.h.
KEYCATCH_CGAME
#define KEYCATCH_CGAME 0x0008
Definition at line 1081 of file q_shared.h.
KEYCATCH_CONSOLE
#define KEYCATCH_CONSOLE 0x0001
Definition at line 1078 of file q_shared.h.
KEYCATCH_MESSAGE
#define KEYCATCH_MESSAGE 0x0004
Definition at line 1080 of file q_shared.h.
KEYCATCH_UI
#define KEYCATCH_UI 0x0002
Definition at line 1079 of file q_shared.h.
LEGACY_HEARTBEAT_FOR_MASTER
#define LEGACY_HEARTBEAT_FOR_MASTER "QuakeArena-1"
Definition at line 69 of file q_shared.h.
LEGACY_MASTER_GAMENAME
#define LEGACY_MASTER_GAMENAME "Quake3Arena"
When com_gamename is LEGACY_MASTER_GAMENAME, use quake3 master protocol.
You shouldn't change this unless you know what you're doing.
Definition at line 68 of file q_shared.h.
LEGACY_PROTOCOL
#define LEGACY_PROTOCOL
Definition at line 60 of file q_shared.h.
LERP
#define LERP (a, b, w) ((a) * (1.0f - (w)) + (b) * (w))
Definition at line 1475 of file q_shared.h.
LUMA
#define LUMA (red, green, blue) (0.2126f * (red) + 0.7152f * (green) + 0.0722f * (blue))
Definition at line 1476 of file q_shared.h.
M_PI
#define M_PI 3.14159265358979323846f
Definition at line 381 of file q_shared.h.
MAKERGB
#define MAKERGB (v, r, g, b) v[0]=r;v[1]=g;v[2]=b
Definition at line 441 of file q_shared.h.
MAKERGBA
#define MAKERGBA (v, r, g, b, a) v[0]=r;v[1]=g;v[2]=b;v[3]=a
Definition at line 442 of file q_shared.h.
MAX
#define MAX (x, y) ((x)>(y)?(x):(y))
Definition at line 743 of file q_shared.h.
MAX_CLIENTS
#define MAX_CLIENTS 64
Definition at line 1117 of file q_shared.h.
MAX_CONFIGSTRINGS
#define MAX_CONFIGSTRINGS 1024
Definition at line 1135 of file q_shared.h.
MAX_CVAR_VALUE_STRING
#define MAX_CVAR_VALUE_STRING 256
Definition at line 974 of file q_shared.h.
MAX_GAMESTATE_CHARS
#define MAX_GAMESTATE_CHARS 16000
Definition at line 1144 of file q_shared.h.
MAX_GENTITIES
#define MAX_GENTITIES (1<<GENTITYNUM_BITS)
Definition at line 1121 of file q_shared.h.
MAX_GLOBAL_SERVERS
#define MAX_GLOBAL_SERVERS 4096
Definition at line 1462 of file q_shared.h.
MAX_INFO_KEY
#define MAX_INFO_KEY 1024
Definition at line 254 of file q_shared.h.
MAX_INFO_STRING
#define MAX_INFO_STRING 1024
Definition at line 253 of file q_shared.h.
MAX_INFO_VALUE
#define MAX_INFO_VALUE 1024
Definition at line 255 of file q_shared.h.
MAX_LOCATIONS
#define MAX_LOCATIONS 64
Definition at line 1118 of file q_shared.h.
MAX_MAP_AREA_BYTES
#define MAX_MAP_AREA_BYTES 32
Definition at line 285 of file q_shared.h.
MAX_MASTER_SERVERS
#define MAX_MASTER_SERVERS 5
number of supported master servers.
Definition at line 84 of file q_shared.h.
MAX_MODELS
#define MAX_MODELS 256
Definition at line 1131 of file q_shared.h.
MAX_NAME_LENGTH
#define MAX_NAME_LENGTH 32
Definition at line 269 of file q_shared.h.
MAX_OSPATH
#define MAX_OSPATH 256
Definition at line 266 of file q_shared.h.
MAX_OTHER_SERVERS
#define MAX_OTHER_SERVERS 128
Definition at line 1463 of file q_shared.h.
MAX_PERSISTANT
#define MAX_PERSISTANT 16
Definition at line 1155 of file q_shared.h.
MAX_PINGREQUESTS
#define MAX_PINGREQUESTS 32
Definition at line 1464 of file q_shared.h.
MAX_POWERUPS
#define MAX_POWERUPS 16
Definition at line 1156 of file q_shared.h.
MAX_PS_EVENTS
#define MAX_PS_EVENTS 2
Definition at line 1159 of file q_shared.h.
MAX_QINT
#define MAX_QINT 0x7fffffff
Definition at line 236 of file q_shared.h.
MAX_QPATH
#define MAX_QPATH 64
Definition at line 262 of file q_shared.h.
MAX_SAY_TEXT
#define MAX_SAY_TEXT 150
Definition at line 271 of file q_shared.h.
MAX_SERVERSTATUSREQUESTS
#define MAX_SERVERSTATUSREQUESTS 16
Definition at line 1465 of file q_shared.h.
MAX_SOUNDS
#define MAX_SOUNDS 256
Definition at line 1132 of file q_shared.h.
MAX_STATS
#define MAX_STATS 16
Definition at line 1154 of file q_shared.h.
MAX_STRING_CHARS
#define MAX_STRING_CHARS 1024
Definition at line 249 of file q_shared.h.
MAX_STRING_TOKENS
#define MAX_STRING_TOKENS 1024
Definition at line 250 of file q_shared.h.
MAX_TEAMNAME
#define MAX_TEAMNAME 32
Definition at line 83 of file q_shared.h.
MAX_TOKEN_CHARS
#define MAX_TOKEN_CHARS 1024
Definition at line 251 of file q_shared.h.
MAX_TOKENLENGTH
#define MAX_TOKENLENGTH 1024
Definition at line 769 of file q_shared.h.
MAX_WEAPONS
#define MAX_WEAPONS 16
Definition at line 1157 of file q_shared.h.
MIN
#define MIN (x, y) ((x)<(y)?(x):(y))
Definition at line 747 of file q_shared.h.
MIN_QINT
#define MIN_QINT (-MAX_QINT-1)
Definition at line 237 of file q_shared.h.
MOVE_RUN
#define MOVE_RUN 120
Definition at line 1275 of file q_shared.h.
nanmask
#define nanmask (255<<23)
Definition at line 452 of file q_shared.h.
NULL
#define NULL ((void *)0)
Definition at line 229 of file q_shared.h.
NUMVERTEXNORMALS
#define NUMVERTEXNORMALS 162
Definition at line 384 of file q_shared.h.
PAD
#define PAD (base, alignment) (((base)+(alignment)-1) & ~((alignment)-1))
Definition at line 217 of file q_shared.h.
PADLEN
#define PADLEN (base, alignment) (PAD((base), (alignment)) - (base))
Definition at line 218 of file q_shared.h.
PADP
#define PADP (base, alignment) ((void *) PAD((intptr_t) (base), (alignment)))
Definition at line 220 of file q_shared.h.
PITCH
#define PITCH 0
Definition at line 243 of file q_shared.h.
PLANE_NON_AXIAL
#define PLANE_NON_AXIAL 3
Definition at line 1021 of file q_shared.h.
PLANE_X
#define PLANE_X 0
Definition at line 1018 of file q_shared.h.
PLANE_Y
#define PLANE_Y 1
Definition at line 1019 of file q_shared.h.
PLANE_Z
#define PLANE_Z 2
Definition at line 1020 of file q_shared.h.
PlaneTypeForNormal
#define PlaneTypeForNormal (x) (x[0] == 1.0 ? PLANE_X : (x[1] == 1.0 ? PLANE_Y : (x[2] == 1.0 ? PLANE_Z : PLANE_NON_AXIAL)))
Definition at line 1030 of file q_shared.h.
PRODUCT_DATE
#define PRODUCT_DATE __DATE__
Definition at line 78 of file q_shared.h.
PRODUCT_NAME
#define PRODUCT_NAME "ioq3"
Definition at line 47 of file q_shared.h.
PRODUCT_VERSION
#define PRODUCT_VERSION "1.36"
Definition at line 74 of file q_shared.h.
PROP_GAP_WIDTH
#define PROP_GAP_WIDTH 3
Definition at line 313 of file q_shared.h.
PROP_HEIGHT
#define PROP_HEIGHT 27
Definition at line 315 of file q_shared.h.
PROP_SMALL_SIZE_SCALE
#define PROP_SMALL_SIZE_SCALE 0.75
Definition at line 316 of file q_shared.h.
PROP_SPACE_WIDTH
#define PROP_SPACE_WIDTH 8
Definition at line 314 of file q_shared.h.
PS_PMOVEFRAMECOUNTBITS
#define PS_PMOVEFRAMECOUNTBITS 6
Definition at line 1161 of file q_shared.h.
PULSE_DIVISOR
#define PULSE_DIVISOR 75
Definition at line 319 of file q_shared.h.
Q3_VERSION
#define Q3_VERSION PRODUCT_NAME " " PRODUCT_VERSION
Definition at line 81 of file q_shared.h.
Q_COLOR_ESCAPE
#define Q_COLOR_ESCAPE '^'
Definition at line 416 of file q_shared.h.
Q_EXPORT
#define Q_EXPORT
Definition at line 134 of file q_shared.h.
Q_ftol
#define Q_ftol lrintf
Definition at line 481 of file q_shared.h.
Q_SnapVector
#define Q_SnapVector (vec)
Value:
    do\
    {\
        vec3_t *temp = (vec);\
        \
        (*temp)[0] = round((*temp)[0]);\
        (*temp)[1] = round((*temp)[1]);\
        (*temp)[2] = round((*temp)[2]);\
    } while(0)
Definition at line 482 of file q_shared.h.
QALIGN
#define QALIGN (x)
Definition at line 225 of file q_shared.h.
QuatCopy
#define QuatCopy (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
Definition at line 588 of file q_shared.h.
RAD2DEG
#define RAD2DEG (a) (((a) * 180.0f) / M_PI)
Definition at line 445 of file q_shared.h.
random
#define random () ((rand () & 0x7fff) / ((float)0x7fff))
Definition at line 701 of file q_shared.h.
RESERVED_CONFIGSTRINGS
#define RESERVED_CONFIGSTRINGS 2
Definition at line 1142 of file q_shared.h.
ROLL
#define ROLL 2
Definition at line 245 of file q_shared.h.
S_COLOR_BLACK
#define S_COLOR_BLACK "^0"
Definition at line 430 of file q_shared.h.
S_COLOR_BLUE
#define S_COLOR_BLUE "^4"
Definition at line 434 of file q_shared.h.
S_COLOR_CYAN
#define S_COLOR_CYAN "^5"
Definition at line 435 of file q_shared.h.
S_COLOR_GREEN
#define S_COLOR_GREEN "^2"
Definition at line 432 of file q_shared.h.
S_COLOR_MAGENTA
#define S_COLOR_MAGENTA "^6"
Definition at line 436 of file q_shared.h.
S_COLOR_RED
#define S_COLOR_RED "^1"
Definition at line 431 of file q_shared.h.
S_COLOR_WHITE
#define S_COLOR_WHITE "^7"
Definition at line 437 of file q_shared.h.
S_COLOR_YELLOW
#define S_COLOR_YELLOW "^3"
Definition at line 433 of file q_shared.h.
SAY_ALL
#define SAY_ALL 0
Definition at line 1467 of file q_shared.h.
SAY_TEAM
#define SAY_TEAM 1
Definition at line 1468 of file q_shared.h.
SAY_TELL
#define SAY_TELL 2
Definition at line 1469 of file q_shared.h.
SCREEN_HEIGHT
#define SCREEN_HEIGHT 480
Definition at line 390 of file q_shared.h.
SCREEN_WIDTH
#define SCREEN_WIDTH 640
Definition at line 389 of file q_shared.h.
SHORT2ANGLE
#define SHORT2ANGLE (x) ((x)*(360.0/65536))
Definition at line 1108 of file q_shared.h.
SMALLCHAR_HEIGHT
#define SMALLCHAR_HEIGHT 16
Definition at line 396 of file q_shared.h.
SMALLCHAR_WIDTH
#define SMALLCHAR_WIDTH 8
Definition at line 395 of file q_shared.h.
SNAPFLAG_NOT_ACTIVE
#define SNAPFLAG_NOT_ACTIVE 2
Definition at line 1111 of file q_shared.h.
SNAPFLAG_RATE_DELAYED
#define SNAPFLAG_RATE_DELAYED 1
Definition at line 1110 of file q_shared.h.
SNAPFLAG_SERVERCOUNT
#define SNAPFLAG_SERVERCOUNT 4
Definition at line 1112 of file q_shared.h.
SnapVector
#define SnapVector (v) {v[0]=((int)(v[0]));v[1]=((int)(v[1]));v[2]=((int)(v[2]));}
Definition at line 590 of file q_shared.h.
SOLID_BMODEL
#define SOLID_BMODEL 0xffffff
Definition at line 1292 of file q_shared.h.
SQRTFAST
#define SQRTFAST (x) ((x) * Q_rsqrt(x))
Definition at line 541 of file q_shared.h.
Square
#define Square (x) ((x)*(x))
Definition at line 1412 of file q_shared.h.
STEAMPATH_APPID
#define STEAMPATH_APPID "2200"
Definition at line 55 of file q_shared.h.
STEAMPATH_NAME
#define STEAMPATH_NAME "Quake 3 Arena"
Definition at line 54 of file q_shared.h.
STRARRAY_LEN
#define STRARRAY_LEN (x) (ARRAY_LEN(x) - 1)
Definition at line 240 of file q_shared.h.
STRING
#define STRING (s) #s
Definition at line 232 of file q_shared.h.
TINYCHAR_HEIGHT
#define TINYCHAR_HEIGHT (SMALLCHAR_HEIGHT/2)
Definition at line 393 of file q_shared.h.
TINYCHAR_WIDTH
#define TINYCHAR_WIDTH (SMALLCHAR_WIDTH)
Definition at line 392 of file q_shared.h.
TRUNCATE_LENGTH
#define TRUNCATE_LENGTH 64
Definition at line 879 of file q_shared.h.
TT_LITERAL
#define TT_LITERAL 2
Definition at line 774 of file q_shared.h.
TT_NAME
#define TT_NAME 4
Definition at line 776 of file q_shared.h.
TT_NUMBER
#define TT_NUMBER 3
Definition at line 775 of file q_shared.h.
TT_PUNCTUATION
#define TT_PUNCTUATION 5
Definition at line 777 of file q_shared.h.
TT_STRING
#define TT_STRING 1
Definition at line 773 of file q_shared.h.
UI_BIGFONT
#define UI_BIGFONT 0x00000020
Definition at line 326 of file q_shared.h.
UI_BLINK
#define UI_BLINK 0x00001000
Definition at line 329 of file q_shared.h.
UI_CENTER
#define UI_CENTER 0x00000001
Definition at line 322 of file q_shared.h.
UI_DROPSHADOW
#define UI_DROPSHADOW 0x00000800
Definition at line 328 of file q_shared.h.
UI_FORMATMASK
#define UI_FORMATMASK 0x00000007
Definition at line 324 of file q_shared.h.
UI_GIANTFONT
#define UI_GIANTFONT 0x00000040
Definition at line 327 of file q_shared.h.
UI_INVERSE
#define UI_INVERSE 0x00002000
Definition at line 330 of file q_shared.h.
UI_LEFT
#define UI_LEFT 0x00000000
Definition at line 321 of file q_shared.h.
UI_PULSE
#define UI_PULSE 0x00004000
Definition at line 331 of file q_shared.h.
UI_RIGHT
#define UI_RIGHT 0x00000002
Definition at line 323 of file q_shared.h.
UI_SMALLFONT
#define UI_SMALLFONT 0x00000010
Definition at line 325 of file q_shared.h.
UNUSED_VAR
#define UNUSED_VAR
Definition at line 124 of file q_shared.h.
Vector4Copy
#define Vector4Copy (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
Definition at line 584 of file q_shared.h.
VectorAdd
#define VectorAdd (a, b, c) ((c)[0]=(a)[0]+(b)[0],(c)[1]=(a)[1]+(b)[1],(c)[2]=(a)[2]+(b)[2])
Definition at line 554 of file q_shared.h.
VectorClear
#define VectorClear (a) ((a)[0]=(a)[1]=(a)[2]=0)
Definition at line 581 of file q_shared.h.
VectorCopy
#define VectorCopy (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2])
Definition at line 555 of file q_shared.h.
VectorMA
#define VectorMA (v, s, b, o) ((o)[0]=(v)[0]+(b)[0]*(s),(o)[1]=(v)[1]+(b)[1]*(s),(o)[2]=(v)[2]+(b)[2]*(s))
Definition at line 557 of file q_shared.h.
VectorNegate
#define VectorNegate (a, b) ((b)[0]=-(a)[0],(b)[1]=-(a)[1],(b)[2]=-(a)[2])
Definition at line 582 of file q_shared.h.
VectorScale
#define VectorScale (v, s, o) ((o)[0]=(v)[0]*(s),(o)[1]=(v)[1]*(s),(o)[2]=(v)[2]*(s))
Definition at line 556 of file q_shared.h.
VectorSet
#define VectorSet (v, x, y, z) ((v)[0]=(x), (v)[1]=(y), (v)[2]=(z))
Definition at line 583 of file q_shared.h.
VectorSubtract
#define VectorSubtract (a, b, c) ((c)[0]=(a)[0]-(b)[0],(c)[1]=(a)[1]-(b)[1],(c)[2]=(a)[2]-(b)[2])
Definition at line 553 of file q_shared.h.
VOIP_DIRECT
#define VOIP_DIRECT 0x02
Definition at line 1000 of file q_shared.h.
VOIP_FLAGCNT
#define VOIP_FLAGCNT 2
Definition at line 1004 of file q_shared.h.
VOIP_SPATIAL
#define VOIP_SPATIAL 0x01
Definition at line 999 of file q_shared.h.
XSTRING
#define XSTRING (s) STRING(s)
Definition at line 234 of file q_shared.h.
YAW
#define YAW 1
Definition at line 244 of file q_shared.h.
Typedef Documentation
byte
typedef unsigned char byte
Definition at line 202 of file q_shared.h.
clipHandle_t
typedef int clipHandle_t
Definition at line 215 of file q_shared.h.
cplane_t
typedef struct cplane_s cplane_t
cvar_t
typedef struct cvar_s cvar_t
Nothing outside the Cvar_*() functions should modify these fields.
Definition at line 943 of file q_shared.h.
cvarHandle_t
typedef int cvarHandle_t
Definition at line 976 of file q_shared.h.
entityState_t
typedef struct entityState_s entityState_t
entityState_t is the information conveyed from the server in an update message about entities that the client will need to render in some way.
Different eTypes may use the information in different ways.
The messages are delta compressed, so it doesn't really matter if the structure size is fairly large.
fileHandle_t
typedef int fileHandle_t
Definition at line 214 of file q_shared.h.
fixed16_t
typedef int fixed16_t
Definition at line 378 of file q_shared.h.
fixed4_t
typedef int fixed4_t
Definition at line 376 of file q_shared.h.
fixed8_t
typedef int fixed8_t
Definition at line 377 of file q_shared.h.
flagStatus_t
typedef enum _flag_status flagStatus_t
State of flag.
pc_token_t
typedef struct pc_token_s pc_token_t
playerState_t
typedef struct playerState_s playerState_t
playerState_t is a full superset of entityState_t as it is used by players, so if a playerState_t is transmitted, the entityState_t can be fully derived from it.
qhandle_t
typedef int qhandle_t
Definition at line 212 of file q_shared.h.
qtime_t
typedef struct qtime_s qtime_t
quat_t
typedef vec_t quat_t[4]
Definition at line 374 of file q_shared.h.
sfxHandle_t
typedef int sfxHandle_t
Definition at line 213 of file q_shared.h.
usercmd_t
typedef struct usercmd_s usercmd_t
usercmd_t is sent to the server each client frame.
vec2_t
typedef vec_t vec2_t[2]
Definition at line 369 of file q_shared.h.
vec3_t
typedef vec_t vec3_t[3]
Definition at line 370 of file q_shared.h.
vec4_t
typedef vec_t vec4_t[4]
Definition at line 371 of file q_shared.h.
vec5_t
typedef vec_t vec5_t[5]
Definition at line 372 of file q_shared.h.
vec_t
typedef float vec_t
Definition at line 368 of file q_shared.h.
Enumeration Type Documentation
_flag_status
enum _flag_status
State of flag.
Enumerator
FLAG_ATBASE
FLAG_TAKEN
CTF.
FLAG_TAKEN_RED
One Flag CTF.
FLAG_TAKEN_BLUE
One Flag CTF.
FLAG_DROPPED
Definition at line 1454 of file q_shared.h.
{
     FLAG_ATBASE = 0,
     FLAG_TAKEN,
     FLAG_TAKEN_RED,
     FLAG_TAKEN_BLUE,
     FLAG_DROPPED
 } flagStatus_t;
cbufExec_t
enum cbufExec_t
Enumerator
EXEC_NOW
EXEC_INSERT
EXEC_APPEND
Definition at line 274 of file q_shared.h.
              {
     EXEC_NOW,            // don't return until completed, a VM should NEVER use this,
                         // because some commands might cause the VM to be unloaded...
                         EXEC_INSERT,        // insert at current position, but don't run yet
                         EXEC_APPEND            // add to end of the command buffer (normal case)
 } cbufExec_t;
connstate_t
enum connstate_t
Connection state.
Enumerator
CA_UNINITIALIZED
CA_DISCONNECTED
not talking to a server.
CA_AUTHORIZING
not used any more, was checking cd key.
CA_CONNECTING
sending request packets to the server.
CA_CHALLENGING
sending challenge packets to the server.
CA_CONNECTED
netchan_t established, getting gamestate.
CA_LOADING
only during cgame initialization, never during main loop.
CA_PRIMED
got gamestate, waiting for first frame.
CA_ACTIVE
game views should be displayed
CA_CINEMATIC
playing a cinematic or a static pic, not connected to a server.
Definition at line 1370 of file q_shared.h.
              {
     CA_UNINITIALIZED,
     CA_DISCONNECTED,
     CA_AUTHORIZING,
     CA_CONNECTING,
     CA_CHALLENGING,
     CA_CONNECTED,
     CA_LOADING,
     CA_PRIMED,
     CA_ACTIVE,
     CA_CINEMATIC
 } connstate_t;
e_status
enum e_status
cinematic states.
Enumerator
FMV_IDLE
FMV_PLAY
play.
FMV_EOF
all other conditions, i.e. stop/EOF/abort.
FMV_ID_BLT
FMV_ID_IDLE
FMV_LOOPED
FMV_ID_WAIT
Definition at line 1441 of file q_shared.h.
              {
     FMV_IDLE,
     FMV_PLAY,
     FMV_EOF,
     FMV_ID_BLT,
     FMV_ID_IDLE,
     FMV_LOOPED,
     FMV_ID_WAIT
 } e_status;
errorParm_t
enum errorParm_t
Enumerator
ERR_FATAL
ERR_DROP
ERR_SERVERDISCONNECT
ERR_DISCONNECT
ERR_NEED_CD
Definition at line 302 of file q_shared.h.
              {
     ERR_FATAL,                    // exit the entire game with a popup window
     ERR_DROP,                    // print to console and disconnect from game
     ERR_SERVERDISCONNECT,        // don't kill server
     ERR_DISCONNECT,                // client disconnected from the server
     ERR_NEED_CD                    // pop up the need-cd dialog
 } errorParm_t;
fsMode_t
enum fsMode_t
Enumerator
FS_READ
FS_WRITE
FS_APPEND
FS_APPEND_SYNC
Definition at line 808 of file q_shared.h.
              {
     FS_READ,
     FS_WRITE,
     FS_APPEND,
     FS_APPEND_SYNC
 } fsMode_t;
fsOrigin_t
enum fsOrigin_t
Enumerator
FS_SEEK_CUR
FS_SEEK_END
FS_SEEK_SET
Definition at line 815 of file q_shared.h.
              {
     FS_SEEK_CUR,
     FS_SEEK_END,
     FS_SEEK_SET
 } fsOrigin_t;
ha_pref
enum ha_pref
Enumerator
h_high
h_low
h_dontcare
Definition at line 337 of file q_shared.h.
              {
     h_high,
     h_low,
     h_dontcare
 } ha_pref;
printParm_t
enum printParm_t
Enumerator
PRINT_ALL
PRINT_DEVELOPER
PRINT_WARNING
PRINT_ERROR
Definition at line 289 of file q_shared.h.
              {
     PRINT_ALL,
     PRINT_DEVELOPER,        // only print when "developer 1"
     PRINT_WARNING,
     PRINT_ERROR
 } printParm_t;
qboolean
enum qboolean
Enumerator
qfalse
qtrue
Definition at line 204 of file q_shared.h.
 { qfalse, qtrue }    qboolean;
soundChannel_t
enum soundChannel_t
Enumerator
CHAN_AUTO
CHAN_LOCAL
CHAN_WEAPON
CHAN_VOICE
CHAN_ITEM
CHAN_BODY
CHAN_LOCAL_SOUND
CHAN_ANNOUNCER
Definition at line 1087 of file q_shared.h.
              {
     CHAN_AUTO,
     CHAN_LOCAL,        // menu sounds, etc
     CHAN_WEAPON,
     CHAN_VOICE,
     CHAN_ITEM,
     CHAN_BODY,
     CHAN_LOCAL_SOUND,    // chat messages, etc
     CHAN_ANNOUNCER        // announcer voices, etc
 } soundChannel_t;
trType_t
enum trType_t
Enumerator
TR_STATIONARY
TR_INTERPOLATE
TR_LINEAR
TR_LINEAR_STOP
TR_SINE
TR_GRAVITY
Definition at line 1294 of file q_shared.h.
              {
     TR_STATIONARY,
     TR_INTERPOLATE,                // non-parametric, but interpolate between snapshots
     TR_LINEAR,
     TR_LINEAR_STOP,
     TR_SINE,                    // value = base + sin( time / duration ) * delta
     TR_GRAVITY
 } trType_t;
Function Documentation
_DotProduct()
vec_t _DotProduct (const vec3_t v1, const vec3_t v2)
Definition at line 854 of file q_math.c.
 {
     return v1[0] * v2[0] + v1[1] * v2[1] + v1[2] * v2[2];
 }
_VectorAdd()
void _VectorAdd (const vec3_t veca, const vec3_t vecb, vec3_t out)
Definition at line 866 of file q_math.c.
 {
     out[0] = veca[0] + vecb[0];
     out[1] = veca[1] + vecb[1];
     out[2] = veca[2] + vecb[2];
 }
References state::out.
_VectorCopy()
void _VectorCopy (const vec3_t in, vec3_t out)
Definition at line 873 of file q_math.c.
 {
     out[0] = in[0];
     out[1] = in[1];
     out[2] = in[2];
 }
References in, and state::out.
_VectorMA()
void _VectorMA (const vec3_t veca, float scale, const vec3_t vecb, vec3_t vecc)
Definition at line 846 of file q_math.c.
 {
     vecc[0] = veca[0] + scale * vecb[0];
     vecc[1] = veca[1] + scale * vecb[1];
     vecc[2] = veca[2] + scale * vecb[2];
 }
_VectorScale()
void _VectorScale (const vec3_t in, float scale, vec3_t out)
Definition at line 880 of file q_math.c.
 {
     out[0] = in[0] * scale;
     out[1] = in[1] * scale;
     out[2] = in[2] * scale;
 }
References in, and state::out.
_VectorSubtract()
void _VectorSubtract (const vec3_t veca, const vec3_t vecb, vec3_t out)
Definition at line 859 of file q_math.c.
 {
     out[0] = veca[0] - vecb[0];
     out[1] = veca[1] - vecb[1];
     out[2] = veca[2] - vecb[2];
 }
References state::out.
AddPointToBounds()
void AddPointToBounds (const vec3_t v, vec3_t mins, vec3_t maxs)
Definition at line 735 of file q_math.c.
 {
     if (v[0] < mins[0]) {
         mins[0] = v[0];
     }
     if (v[0] > maxs[0]) {
         maxs[0] = v[0];
     }
     if (v[1] < mins[1]) {
         mins[1] = v[1];
     }
     if (v[1] > maxs[1]) {
         maxs[1] = v[1];
     }
     if (v[2] < mins[2]) {
         mins[2] = v[2];
     }
     if (v[2] > maxs[2]) {
         maxs[2] = v[2];
     }
 }
Referenced by CM_GeneratePatchCollide(), LoadDrawVertToSrfVert(), R_CreateSurfaceGridMesh(), R_CullLocalBox(), R_LoadIQM(), R_MarkFragments(), R_RenderSunShadowMaps(), RE_AddPolyToScene(), and Think_SpawnNewDoorTrigger().
AngleDelta()
float AngleDelta (float angle1, float angle2)
Definition at line 637 of file q_math.c.
 {
     return AngleNormalize180(angle1 - angle2);
 }
References AngleNormalize180().
AngleMod()
float AngleMod (float a)
Definition at line 593 of file q_math.c.
 {
     a = (360.0 / 65536) * ((int)(a * (65536 / 360.0)) & 65535);
     return a;
 }
References a.
Referenced by BotAI(), BotAimAtEnemy(), BotChangeViewAngle(), BotChangeViewAngles(), BotMapScripts(), BotUpdateInput(), CG_MachinegunSpinAngle(), CG_PlayerAngles(), CG_SwingAngles(), InFieldOfVision(), UI_MachinegunSpinAngle(), UI_PlayerAngles(), and UI_SwingAngles().
AngleNormalize180()
float AngleNormalize180 (float angle)
Definition at line 620 of file q_math.c.
 {
     angle = AngleNormalize360(angle);
     if (angle > 180.0) {
         angle -= 360.0;
     }
     return angle;
 }
References AngleNormalize360().
Referenced by AngleDelta(), and BG_TouchJumpPad().
AngleNormalize360()
float AngleNormalize360 (float angle)
Definition at line 607 of file q_math.c.
 {
     return (360.0 / 65536) * ((int)(angle * (65536 / 360.0)) & 65535);
 }
References int().
Referenced by AngleNormalize180().
AnglesSubtract()
void AnglesSubtract (vec3_t v1, vec3_t v2, vec3_t v3)
Definition at line 585 of file q_math.c.
 {
     v3[0] = AngleSubtract(v1[0], v2[0]);
     v3[1] = AngleSubtract(v1[1], v2[1]);
     v3[2] = AngleSubtract(v1[2], v2[2]);
 }
References AngleSubtract().
Referenced by CG_PlayerAngles(), and UI_PlayerAngles().
AnglesToAxis()
void AnglesToAxis (const vec3_t angles, vec3_t axis[3])
Definition at line 424 of file q_math.c.
 {
     vec3_t    right;
     // angle vectors returns "right" instead of "y axis"
     AngleVectors(angles, axis[0], right, axis[2]);
     VectorSubtract(vec3_origin, right, axis[1]);
 }
References AngleVectors(), right, vec3_origin, and VectorSubtract.
Referenced by CG_AddFragment(), CG_AddPacketEntities(), CG_AddPlayerWeapon(), CG_AddViewWeapon(), CG_CalcViewValues(), CG_Draw3DModel(), CG_General(), CG_Item(), CG_LightningBolt(), CG_MachineGunEjectBrass(), CG_Missile(), CG_Mover(), CG_PlasmaTrail(), CG_Player(), CG_PlayerAngles(), CG_PlayerFlag(), CG_ScorePlum(), CG_ShotgunEjectBrass(), CG_TeamBase(), CG_TestModel_f(), CG_TrailItem(), Item_Model_Paint(), Main_MenuDraw(), UI_DrawPlayer(), and UI_PlayerAngles().
AngleSubtract()
float AngleSubtract (float a1, float a2)
Definition at line 570 of file q_math.c.
 {
     float    a;
     a = a1 - a2;
     while (a > 180) {
         a -= 360;
     }
     while (a < -180) {
         a += 360;
     }
     return a;
 }
References a.
Referenced by AnglesSubtract(), CG_SwingAngles(), and UI_SwingAngles().
AngleVectors()
void AngleVectors (const vec3_t angles, vec3_t forward, vec3_t right, vec3_t up)
Definition at line 956 of file q_math.c.
 {
     float        angle;
     static float        sr, sp, sy, cr, cp, cy;
     // static to help MS compiler fp bugs
     angle = angles[YAW] * (M_PI * 2 / 360);
     sy = sin(angle);
     cy = cos(angle);
     angle = angles[PITCH] * (M_PI * 2 / 360);
     sp = sin(angle);
     cp = cos(angle);
     angle = angles[ROLL] * (M_PI * 2 / 360);
     sr = sin(angle);
     cr = cos(angle);
     if (forward) {
         forward[0] = cp * cy;
         forward[1] = cp * sy;
         forward[2] = -sp;
     }
     if (right) {
         right[0] = (-1 * sr * sp * cy + -1 * cr * -sy);
         right[1] = (-1 * sr * sp * sy + -1 * cr * cy);
         right[2] = -1 * sr * cp;
     }
     if (up) {
         up[0] = (cr * sp * cy + -sr * -sy);
         up[1] = (cr * sp * sy + -sr * cy);
         up[2] = cr * cp;
     }
 }
References forward, M_PI, PITCH, right, ROLL, up, and YAW.
Referenced by AAS_Reachability_Teleport(), AAS_SetMovedir(), AAS_WeaponJumpZVelocity(), AnglesToAxis(), BotAIBlocked(), BotCheckAttack(), BotExportTest(), BotGetLongTermGoal(), BotInputToUserCommand(), BotRandomMove(), BotSetMovedir(), CG_AddParticles(), CG_AddParticleToScene(), CG_CalcMuzzlePoint(), CG_CreateRotationMatrix(), CG_DamageFeedback(), CG_GrappleTrail(), CG_LightningBolt(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_ParticleBloodCloud(), CG_ParticleDust(), CheckGauntletAttack(), CM_TransformedPointContents(), CreateRotationMatrix(), Drop_Item(), FireWeapon(), G_CreateRotationMatrix(), G_SetMovedir(), G_TryPushingProxMine(), Pickup_Powerup(), PmoveSingle(), PodiumPlacementThink(), SpawnModelOnVictoryPad(), SpawnPodium(), SV_GameSystemCalls(), TeleportPlayer(), UI_MovedirAdjustment(), and ValidBloodPool().
AxisClear()
void AxisClear (vec3_t axis[3])
Definition at line 433 of file q_math.c.
 {
     axis[0][0] = 1;
     axis[0][1] = 0;
     axis[0][2] = 0;
     axis[1][0] = 0;
     axis[1][1] = 1;
     axis[1][2] = 0;
     axis[2][0] = 0;
     axis[2][1] = 0;
     axis[2][2] = 1;
 }
Referenced by CG_Beam(), CG_Draw3DModel(), CG_GrappleTrail(), CG_MakeExplosion(), CG_RailTrail(), CG_SpawnEffect(), Item_Model_Paint(), Main_MenuDraw(), R_IQMLerpTag(), R_LerpTag(), and UI_DrawPlayer().
AxisCopy()
void AxisCopy (vec3_t in[3], vec3_t out[3])
Definition at line 446 of file q_math.c.
 {
     VectorCopy(in[0], out[0]);
     VectorCopy(in[1], out[1]);
     VectorCopy(in[2], out[2]);
 }
References in, state::out, and VectorCopy.
Referenced by CG_Item(), CG_LaunchExplode(), CG_LaunchGib(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), CG_ShotgunEjectBrass(), and R_GetPortalOrientations().
BoundsIntersect()
qboolean BoundsIntersect (const vec3_t mins, const vec3_t maxs, const vec3_t mins2, const vec3_t maxs2)
Definition at line 759 of file q_math.c.
 {
     if (maxs[0] < mins2[0] ||
         maxs[1] < mins2[1] ||
         maxs[2] < mins2[2] ||
         mins[0] > maxs2[0] ||
         mins[1] > maxs2[1] ||
         mins[2] > maxs2[2]) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoundsIntersectPoint()
qboolean BoundsIntersectPoint (const vec3_t mins, const vec3_t maxs, const vec3_t origin)
Definition at line 789 of file q_math.c.
 {
     if (origin[0] > maxs[0] ||
         origin[0] < mins[0] ||
         origin[1] > maxs[1] ||
         origin[1] < mins[1] ||
         origin[2] > maxs[2] ||
         origin[2] < mins[2]) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoundsIntersectSphere()
qboolean BoundsIntersectSphere (const vec3_t mins, const vec3_t maxs, const vec3_t origin, vec_t radius)
Definition at line 774 of file q_math.c.
 {
     if (origin[0] - radius > maxs[0] ||
         origin[0] + radius < mins[0] ||
         origin[1] - radius > maxs[1] ||
         origin[1] + radius < mins[1] ||
         origin[2] - radius > maxs[2] ||
         origin[2] + radius < mins[2]) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, and qtrue.
BoxOnPlaneSide()
int BoxOnPlaneSide (vec3_t emins, vec3_t emaxs, struct cplane_s * plane)
Definition at line 673 of file q_math.c.
 {
     float    dist[2];
     int        sides, b, i;
     // fast axial cases
     if (p->type < 3) {
         if (p->dist <= emins[p->type])
             return 1;
         if (p->dist >= emaxs[p->type])
             return 2;
         return 3;
     }
     // general case
     dist[0] = dist[1] = 0;
     if (p->signbits < 8) // >= 8: default case is original code (dist[0]=dist[1]=0)
     {
         for (i = 0; i < 3; i++) {
             b = (p->signbits >> i) & 1;
             dist[b] += p->normal[i] * emaxs[i];
             dist[!b] += p->normal[i] * emins[i];
         }
     }
     sides = 0;
     if (dist[0] >= p->dist)
         sides = 1;
     if (dist[1] < p->dist)
         sides |= 2;
     return sides;
 }
References cplane_s::dist, cplane_s::normal, cplane_s::signbits, and cplane_s::type.
Referenced by CM_BoxLeafnums_r(), R_BoxSurfaces_r(), R_CullBox(), R_PshadowSurface(), and R_RecursiveWorldNode().
ByteToDir()
void ByteToDir (int b, vec3_t dir)
Definition at line 214 of file q_math.c.
 {
     if (b < 0 || b >= NUMVERTEXNORMALS) {
         VectorCopy(vec3_origin, dir);
         return;
     }
     VectorCopy(bytedirs[b], dir);
 }
References bytedirs, NUMVERTEXNORMALS, vec3_origin, and VectorCopy.
Referenced by CG_EntityEvent(), and CG_Portal().
ClampChar()
signed char ClampChar (int i)
Definition at line 168 of file q_math.c.
 {
     if (i < -128) {
         return -128;
     }
     if (i > 127) {
         return 127;
     }
     return i;
 }
Referenced by CL_JoystickMove(), CL_KeyMove(), and CL_MouseMove().
ClampShort()
signed short ClampShort (int i)
Definition at line 179 of file q_math.c.
 {
     if (i < -32768) {
         return -32768;
     }
     if (i > 0x7fff) {
         return 0x7fff;
     }
     return i;
 }
ClearBounds()
void ClearBounds (vec3_t mins, vec3_t maxs)
Definition at line 729 of file q_math.c.
 {
     mins[0] = mins[1] = mins[2] = 99999;
     maxs[0] = maxs[1] = maxs[2] = -99999;
 }
Referenced by CM_GeneratePatchCollide(), ParseFace(), ParseTriSurf(), R_AddWorldSurfaces(), R_CreateSurfaceGridMesh(), R_CullLocalBox(), R_LoadIQM(), R_MarkFragments(), and R_RenderSunShadowMaps().
ColorBytes3()
unsigned ColorBytes3 (float r, float g, float b)
Definition at line 224 of file q_math.c.
 {
     unsigned    i;
     ((byte*)&i)[0] = r * 255;
     ((byte*)&i)[1] = g * 255;
     ((byte*)&i)[2] = b * 255;
     return i;
 }
ColorBytes4()
unsigned ColorBytes4 (float r, float g, float b, float a)
Definition at line 235 of file q_math.c.
 {
     unsigned    i;
     ((byte*)&i)[0] = r * 255;
     ((byte*)&i)[1] = g * 255;
     ((byte*)&i)[2] = b * 255;
     ((byte*)&i)[3] = a * 255;
     return i;
 }
References a.
Referenced by R_LoadFogs().
COM_BeginParseSession()
void COM_BeginParseSession (const char * name)
Definition at line 318 of file q_shared.c.
 {
     com_lines = 1;
     com_tokenline = 0;
     Com_sprintf(com_parsename, sizeof(com_parsename), "%s", name);
 }
References com_lines, com_parsename, Com_sprintf(), and com_tokenline.
Referenced by ScanAndLoadShaderFiles().
Com_Clamp()
float Com_Clamp (float min, float max, float value)
Definition at line 49 of file q_shared.c.
 {
     if (value < min) {
         return min;
     }
     if (value > max) {
         return max;
     }
     return value;
 }
Referenced by ArenaServers_MenuInit(), InitOpenGL(), PlayerSettings_SetMenuItems(), Preferences_SetMenuItems(), Punkbuster_ConfirmDisable(), Punkbuster_ConfirmEnable(), R_CreateImage2(), RB_GaussianBlur(), ServerOptions_MenuInit(), ServerOptions_SetMenuItems(), ServerOptions_Start(), Svcmd_AddBot_f(), UI_AddBotsMenu_Init(), UI_DrawHandicap(), UI_Handicap_HandleKey(), UI_OwnerDrawWidth(), UI_RunMenuScript(), and UI_SPSkillMenu_Init().
COM_CompareExtension()
qboolean COM_CompareExtension (const char * in, const char * ext)
Definition at line 119 of file q_shared.c.
 {
     int inlen, extlen;
     inlen = strlen(in);
     extlen = strlen(ext);
     if (extlen <= inlen) {
         in += inlen - extlen;
         if (!Q_stricmp(in, ext))
             return qtrue;
     }
     return qfalse;
 }
References in, state::inlen, Q_stricmp(), qfalse, and qtrue.
Referenced by Com_WriteConfig_f(), Con_Dump_f(), FS_CheckFilenameIsMutable(), and Sys_DllExtension().
COM_Compress()
int COM_Compress (char * data_p)
Definition at line 393 of file q_shared.c.
 {
     char* in, * out;
     int c;
     qboolean newline = qfalse, whitespace = qfalse;
     in = out = data_p;
     if (in) {
         while ((c = *in) != 0) {
             // skip double slash comments
             if (c == '/' && in[1] == '/') {
                 while (*in && *in != '\n') {
                     in++;
                 }
                 // skip /* */ comments
             } else if (c == '/' && in[1] == '*') {
                 while (*in && (*in != '*' || in[1] != '/'))
                     in++;
                 if (*in)
                     in += 2;
                 // record when we hit a newline
             } else if (c == '\n' || c == '\r') {
                 newline = qtrue;
                 in++;
                 // record when we hit whitespace
             } else if (c == ' ' || c == '\t') {
                 whitespace = qtrue;
                 in++;
                 // an actual token
             } else {
                 // if we have a pending newline, emit it (and it counts as whitespace)
                 if (newline) {
                     *out++ = '\n';
                     newline = qfalse;
                     whitespace = qfalse;
                 } if (whitespace) {
                     *out++ = ' ';
                     whitespace = qfalse;
                 }
                 // copy quoted strings unmolested
                 if (c == '"') {
                     *out++ = c;
                     in++;
                     while (1) {
                         c = *in;
                         if (c && c != '"') {
                             *out++ = c;
                             in++;
                         } else {
                             break;
                         }
                     }
                     if (c == '"') {
                         *out++ = c;
                         in++;
                     }
                 } else {
                     *out = c;
                     out++;
                     in++;
                 }
             }
         }
         *out = 0;
     }
     return out - data_p;
 }
References in, state::out, qfalse, and qtrue.
Referenced by ScanAndLoadShaderFiles(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
COM_DefaultExtension()
void COM_DefaultExtension (char * path, int maxSize, const char * extension)
Definition at line 144 of file q_shared.c.
 {
     const char* dot = strrchr(path, '.'), * slash;
     if (dot && (!(slash = strrchr(path, '/')) || slash < dot))
         return;
     else
         Q_strcat(path, maxSize, extension);
 }
References Q_strcat().
Referenced by Cmd_Exec_f(), Com_WriteConfig_f(), and Con_Dump_f().
Com_Error()
void QDECL Com_Error (int level, const char * error, ...)
COM_GetCurrentParseLine()
int COM_GetCurrentParseLine (void)
Definition at line 325 of file q_shared.c.
 {
     if (com_tokenline) {
         return com_tokenline;
     }
     return com_lines;
 }
References com_lines, and com_tokenline.
Referenced by COM_ParseError(), COM_ParseWarning(), and ScanAndLoadShaderFiles().
COM_GetExtension()
const char* COM_GetExtension (const char * name)
Definition at line 84 of file q_shared.c.
 {
     const char* dot = strrchr(name, '.'), * slash;
     if (dot && (!(slash = strrchr(name, '/')) || slash < dot))
         return dot + 1;
     else
         return "";
 }
Referenced by FS_CheckFilenameIsMutable(), R_LoadImage(), RE_RegisterModel(), and S_CodecGetSound().
Com_HexStrToInt()
int Com_HexStrToInt (const char * str)
Definition at line 672 of file q_shared.c.
 {
     if (!str)
         return -1;
     // check for hex code
     if (str[0] == '0' && str[1] == 'x' && str[2] != '\0') {
         int i, n = 0, len = strlen(str);
         for (i = 2; i < len; i++) {
             char digit;
             n *= 16;
             digit = tolower(str[i]);
             if (digit >= '0' && digit <= '9')
                 digit -= '0';
             else if (digit >= 'a' && digit <= 'f')
                 digit = digit - 'a' + 10;
             else
                 return -1;
             n += digit;
         }
         return n;
     }
     return -1;
 }
Referenced by Com_FieldStringToPlayerName(), and Key_StringToKeynum().
COM_MatchToken()
void COM_MatchToken (char ** buf_p, char * match)
Definition at line 562 of file q_shared.c.
 {
     char* token;
     token = COM_Parse(buf_p);
     if (strcmp(token, match)) {
         Com_Error(ERR_DROP, "MatchToken: %s != %s", token, match);
     }
 }
References Com_Error(), COM_Parse(), and ERR_DROP.
Referenced by Parse1DMatrix(), Parse2DMatrix(), and Parse3DMatrix().
COM_Parse()
char* COM_Parse (char ** data_p)
Definition at line 334 of file q_shared.c.
 {
     return COM_ParseExt(data_p, qtrue);
 }
References COM_ParseExt(), and qtrue.
Referenced by CG_NewParticleArea(), CG_ParseAnimationFile(), CG_StartMusic(), CL_LoadConsoleHistory(), COM_MatchToken(), G_ParseInfos(), Parse1DMatrix(), R_GetEntityToken(), SV_GameSystemCalls(), UI_ParseAnimationFile(), UI_ParseInfos(), and VM_LoadSymbols().
COM_ParseError()
void COM_ParseError (char * format, ...)
COM_ParseExt()
char* COM_ParseExt (char ** data_p, qboolean allowLineBreak)
Definition at line 463 of file q_shared.c.
 {
     int c = 0, len;
     qboolean hasNewLines = qfalse;
     char* data;
     data = *data_p;
     len = 0;
     com_token[0] = 0;
     com_tokenline = 0;
     // make sure incoming data is valid
     if (!data) {
         *data_p = NULL;
         return com_token;
     }
     while (1) {
         // skip whitespace
         data = SkipWhitespace(data, &hasNewLines);
         if (!data) {
             *data_p = NULL;
             return com_token;
         }
         if (hasNewLines && !allowLineBreaks) {
             *data_p = data;
             return com_token;
         }
         c = *data;
         // skip double slash comments
         if (c == '/' && data[1] == '/') {
             data += 2;
             while (*data && *data != '\n') {
                 data++;
             }
         }
         // skip /* */ comments
         else if (c == '/' && data[1] == '*') {
             data += 2;
             while (*data && (*data != '*' || data[1] != '/')) {
                 if (*data == '\n') {
                     com_lines++;
                 }
                 data++;
             }
             if (*data) {
                 data += 2;
             }
         } else {
             break;
         }
     }
     // token starts on this line
     com_tokenline = com_lines;
     // handle quoted strings
     if (c == '\"') {
         data++;
         while (1) {
             c = *data++;
             if (c == '\"' || !c) {
                 com_token[len] = 0;
                 *data_p = (char*)data;
                 return com_token;
             }
             if (c == '\n') {
                 com_lines++;
             }
             if (len < MAX_TOKEN_CHARS - 1) {
                 com_token[len] = c;
                 len++;
             }
         }
     }
     // parse a regular word
     do {
         if (len < MAX_TOKEN_CHARS - 1) {
             com_token[len] = c;
             len++;
         }
         data++;
         c = *data;
     } while (c > 32);
     com_token[len] = 0;
     *data_p = (char*)data;
     return com_token;
 }
References com_lines, com_token, com_tokenline, MAX_TOKEN_CHARS, NULL, qfalse, and SkipWhitespace().
Referenced by Alias_Parse(), Character_Parse(), COM_Parse(), FindShaderInShaderText(), Float_Parse(), G_ParseInfos(), GameType_Parse(), GametypeBits(), Int_Parse(), MapList_Parse(), ParseDeform(), ParseShader(), ParseSkyParms(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseTexMod(), ParseVector(), ParseWaveForm(), R_LoadEntities(), ScanAndLoadShaderFiles(), SkipBracedSection(), String_Parse(), Team_Parse(), UI_ParseGameInfo(), UI_ParseInfos(), and UI_ParseTeamInfo().
COM_ParseWarning()
void void COM_ParseWarning (char * format, ...)
Com_Printf()
void QDECL Com_Printf (const char * msg, ...)
Com_RandomBytes()
void Com_RandomBytes (byte * string, int len)
Definition at line 3592 of file common.c.
 {
     int i;
     if (Sys_RandomBytes(string, len))
         return;
     Com_Printf("Com_RandomBytes: using weak randomization\n");
     for (i = 0; i < len; i++)
         string[i] = (unsigned char)(rand() % 256);
 }
References Com_Printf(), and Sys_RandomBytes().
Referenced by CL_GenerateQKey(), and Com_Init().
Com_SkipCharset()
char* Com_SkipCharset (char * s, char * sep)
Definition at line 1397 of file q_shared.c.
 {
     char* p = s;
     while (p) {
         if (Com_CharIsOneOfCharset(*p, sep))
             p++;
         else
             break;
     }
     return p;
 }
References Com_CharIsOneOfCharset(), and s.
Referenced by Field_CompleteCommand().
COM_SkipPath()
char* COM_SkipPath (char * pathname)
Definition at line 66 of file q_shared.c.
 {
     char* last;
     last = pathname;
     while (*pathname) {
         if (*pathname == '/')
             last = pathname + 1;
         pathname++;
     }
     return last;
 }
Referenced by CL_Frame(), and RE_LoadWorldMap().
Com_SkipTokens()
int QDECL char* Com_SkipTokens (char * s, int numTokens, char * sep)
Definition at line 1416 of file q_shared.c.
 {
     int        sepCount = 0;
     char* p = s;
     while (sepCount < numTokens) {
         if (Com_CharIsOneOfCharset(*p++, sep)) {
             sepCount++;
             while (Com_CharIsOneOfCharset(*p, sep))
                 p++;
         } else if (*p == '\0')
             break;
     }
     if (sepCount == numTokens)
         return p;
     else
         return s;
 }
References Com_CharIsOneOfCharset(), and s.
Referenced by CL_CompleteRcon(), Cvar_CompleteCvarName(), Key_CompleteBind(), and Key_CompleteUnbind().
Com_sprintf()
int QDECL Com_sprintf (char * dest, int size, const char * fmt, ...)
COM_StripExtension()
void COM_StripExtension (const char * in, char * out, int destsize)
Definition at line 99 of file q_shared.c.
 {
     const char* dot = strrchr(in, '.'), * slash;
     if (dot && (!(slash = strrchr(in, '/')) || slash < dot))
         destsize = (destsize < dot - in + 1 ? destsize : dot - in + 1);
     if (in == out && destsize > 1)
         out[destsize - 1] = '\0';
     else
         Q_strncpyz(out, in, destsize);
 }
References in, state::out, and Q_strncpyz().
Referenced by CG_RegisterWeapon(), CL_Frame(), CollapseStagesToLightall(), FS_FilenameCompletion(), PlayerModel_BuildList(), R_FindImageFile(), R_FindShader(), R_FindShaderByName(), R_LoadImage(), R_RemapShader(), RB_ExportCubemaps(), RE_LoadWorldMap(), RE_RegisterModel(), S_CodecGetSound(), UI_BuildQ3Model_List(), UI_PlayerInfo_SetWeapon(), UI_SaveConfigMenu_SaveEvent(), and VM_LoadSymbols().
Com_TruncateLongString()
void Com_TruncateLongString (char * buffer, const char * s)
Definition at line 1047 of file q_shared.c.
 {
     int length = strlen(s);
     if (length <= TRUNCATE_LENGTH)
         Q_strncpyz(buffer, s, TRUNCATE_LENGTH);
     else {
         Q_strncpyz(buffer, s, (TRUNCATE_LENGTH / 2) - 3);
         Q_strcat(buffer, TRUNCATE_LENGTH, " ... ");
         Q_strcat(buffer, TRUNCATE_LENGTH, s + length - (TRUNCATE_LENGTH / 2) + 3);
     }
 }
References buffer, Q_strcat(), Q_strncpyz(), s, and TRUNCATE_LENGTH.
Referenced by PrintCvarMatches().
CrossProduct()
static ID_INLINE void CrossProduct (const vec3_t v1, const vec3_t v2, vec3_t cross) static
Definition at line 663 of file q_shared.h.
 {
     cross[0] = v1[1] * v2[2] - v1[2] * v2[1];
     cross[1] = v1[2] * v2[0] - v1[0] * v2[2];
     cross[2] = v1[0] * v2[1] - v1[1] * v2[0];
 }
Referenced by AAS_DrawArrow(), AAS_FaceArea(), AAS_PointInsideFace(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Jump(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_WalkOffLedge(), AddWindingToConvexHull(), Autosprite2Deform(), BaseWindingForPlane(), BotAIBlocked(), BotAttackMove(), BotImport_DebugLineShow(), CG_AddScorePlum(), CG_ImpactMark(), CG_Player(), CG_Portal(), CG_ShotgunPattern(), CheckWinding(), CM_AddFacetBevels(), CM_PlaneFromPoints(), DebugLine(), DeformText(), MakeMeshNormals(), MakeNormalVectors(), PlaneFromPoints(), PM_SlideMove(), R_CalcTangentSpace(), R_CalcTangentVectors(), R_GetPortalOrientations(), R_MarkFragments(), R_RenderPshadowMaps(), R_RenderSunShadowMaps(), RB_DrawSun(), RB_ShadowTessEnd(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RE_AddRefEntityToScene(), RotateAroundDirection(), RotatePointAroundVector(), ShotgunPattern(), Use_Shooter(), WindingArea(), and WindingPlane().
DirToByte()
int DirToByte (vec3_t dir)
Definition at line 192 of file q_math.c.
 {
     int        i, best;
     float    d, bestd;
     if (!dir) {
         return 0;
     }
     bestd = 0;
     best = 0;
     for (i = 0; i < NUMVERTEXNORMALS; i++) {
         d = DotProduct(dir, bytedirs[i]);
         if (d > bestd) {
             bestd = d;
             best = i;
         }
     }
     return best;
 }
References bytedirs, DotProduct, and NUMVERTEXNORMALS.
Referenced by Bullet_Fire(), CheckGauntletAttack(), G_ExplodeMissile(), G_MissileImpact(), locateCamera(), Weapon_LightningFire(), and weapon_railgun_fire().
Distance()
static ID_INLINE vec_t Distance (const vec3_t p1, const vec3_t p2) static
Definition at line 627 of file q_shared.h.
 {
     vec3_t    v;
     VectorSubtract(p2, p1, v);
     return VectorLength(v);
 }
References VectorLength(), and VectorSubtract.
Referenced by CG_AddParticleToScene(), and CG_GrappleTrail().
DistanceSquared()
static ID_INLINE vec_t DistanceSquared (const vec3_t p1, const vec3_t p2) static
Definition at line 635 of file q_shared.h.
 {
     vec3_t    v;
     VectorSubtract(p2, p1, v);
     return v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
 }
References VectorSubtract.
Referenced by S_Base_AddLoopingSound(), and S_Base_HearingThroughEntity().
format()
void QDECL format (printf , 2 , 3)
Hunk_AllocDebug()
void* Hunk_AllocDebug (int size, ha_pref preference, char * label, char * file, int line)
Definition at line 1752 of file common.c.
 {
 #else
 void* Hunk_Alloc(int size, ha_pref preference)
 {
 #endif
     void* buf;
     if (s_hunkData == NULL) {
         Com_Error(ERR_FATAL, "Hunk_Alloc: Hunk memory system not initialized");
     }
     // can't do preference if there is any temp allocated
     if (preference == h_dontcare || hunk_temp->temp != hunk_temp->permanent) {
         Hunk_SwapBanks();
     } else {
         if (preference == h_low && hunk_permanent != &hunk_low) {
             Hunk_SwapBanks();
         } else if (preference == h_high && hunk_permanent != &hunk_high) {
             Hunk_SwapBanks();
         }
     }
 #ifdef HUNK_DEBUG
     size += sizeof(hunkblock_t);
 #endif
     // round to cacheline
     size = (size + 31) & ~31;
     if (hunk_low.temp + hunk_high.temp + size > s_hunkTotal) {
 #ifdef HUNK_DEBUG
         Hunk_Log();
         Hunk_SmallLog();
         Com_Error(ERR_DROP, "Hunk_Alloc failed on %i: %s, line: %d (%s)", size, file, line, label);
 #else
         Com_Error(ERR_DROP, "Hunk_Alloc failed on %i", size);
 #endif
     }
     if (hunk_permanent == &hunk_low) {
         buf = (void*)(s_hunkData + hunk_permanent->permanent);
         hunk_permanent->permanent += size;
     } else {
         hunk_permanent->permanent += size;
         buf = (void*)(s_hunkData + s_hunkTotal - hunk_permanent->permanent);
     }
     hunk_permanent->temp = hunk_permanent->permanent;
     Com_Memset(buf, 0, size);
 #ifdef HUNK_DEBUG
     {
         hunkblock_t* block;
         block = (hunkblock_t*)buf;
         block->size = size - sizeof(hunkblock_t);
         block->file = file;
         block->label = label;
         block->line = line;
         block->next = hunkblocks;
         hunkblocks = block;
         buf = ((byte*)buf) + sizeof(hunkblock_t);
     }
 #endif
     return buf;
 }
References Com_Error(), Com_Memset, ERR_DROP, ERR_FATAL, hunkblock_s::file, h_dontcare, h_high, h_low, Hunk_Alloc, hunk_high, Hunk_Log(), hunk_low, hunk_permanent, Hunk_SmallLog(), Hunk_SwapBanks(), hunk_temp, hunkblocks, hunkblock_s::label, hunkblock_s::line, hunkblock_s::next, NULL, hunkUsed_t::permanent, s_hunkData, s_hunkTotal, hunkblock_s::size, and hunkUsed_t::temp.
Referenced by CL_InitRef().
Info_NextPair()
void Info_NextPair (const char ** s, char * key, char * value)
Definition at line 1132 of file q_shared.c.
 {
     char* o;
     const char* s;
     s = *head;
     if (*s == '\\') {
         s++;
     }
     key[0] = 0;
     value[0] = 0;
     o = key;
     while (*s != '\\') {
         if (!*s) {
             *o = 0;
             *head = s;
             return;
         }
         *o++ = *s++;
     }
     *o = 0;
     s++;
     o = value;
     while (*s != '\\' && *s) {
         *o++ = *s++;
     }
     *o = 0;
     *head = s;
 }
References s.
Referenced by CL_SystemInfoChanged(), ServerInfo_MenuDraw(), and UI_ServerInfoMenu().
Info_RemoveKey()
void Info_RemoveKey (char * s, const char * key)
Definition at line 1172 of file q_shared.c.
 {
     char* start;
     char    pkey[MAX_INFO_KEY];
     char    value[MAX_INFO_VALUE];
     char* o;
     if (strlen(s) >= MAX_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_RemoveKey: oversize infostring");
     }
     if (strchr(key, '\\')) {
         return;
     }
     while (1) {
         start = s;
         if (*s == '\\')
             s++;
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value;
         while (*s != '\\' && *s) {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp(key, pkey)) {
             memmove(start, s, strlen(s) + 1); // remove this part
             return;
         }
         if (!*s)
             return;
     }
 }
References Com_Error(), ERR_DROP, MAX_INFO_KEY, MAX_INFO_STRING, MAX_INFO_VALUE, and s.
Referenced by Info_SetValueForKey().
Info_RemoveKey_Big()
void Info_RemoveKey_Big (char * s, const char * key)
Definition at line 1225 of file q_shared.c.
 {
     char* start;
     char    pkey[BIG_INFO_KEY];
     char    value[BIG_INFO_VALUE];
     char* o;
     if (strlen(s) >= BIG_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_RemoveKey_Big: oversize infostring");
     }
     if (strchr(key, '\\')) {
         return;
     }
     while (1) {
         start = s;
         if (*s == '\\')
             s++;
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value;
         while (*s != '\\' && *s) {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp(key, pkey)) {
             memmove(start, s, strlen(s) + 1); // remove this part
             return;
         }
         if (!*s)
             return;
     }
 }
References BIG_INFO_KEY, BIG_INFO_STRING, BIG_INFO_VALUE, Com_Error(), ERR_DROP, and s.
Referenced by Info_SetValueForKey_Big().
Info_SetValueForKey()
void Info_SetValueForKey (char * s, const char * key, const char * value)
Definition at line 1301 of file q_shared.c.
 {
     char    newi[MAX_INFO_STRING];
     const char* blacklist = "\\;\"";
     if (strlen(s) >= MAX_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_SetValueForKey: oversize infostring");
     }
     for (; *blacklist; ++blacklist) {
         if (strchr(key, *blacklist) || strchr(value, *blacklist)) {
             Com_Printf(S_COLOR_YELLOW "Can't use keys or values with a '%c': %s = %s\n", *blacklist, key, value);
             return;
         }
     }
     Info_RemoveKey(s, key);
     if (!value || !strlen(value))
         return;
     Com_sprintf(newi, sizeof(newi), "\\%s\\%s", key, value);
     if (strlen(newi) + strlen(s) >= MAX_INFO_STRING) {
         Com_Printf("Info string length exceeded\n");
         return;
     }
     strcat(newi, s);
     strcpy(s, newi);
 }
References Com_Error(), Com_Printf(), Com_sprintf(), ERR_DROP, Info_RemoveKey(), MAX_INFO_STRING, s, and S_COLOR_YELLOW.
Referenced by ArenaServers_DoRefresh(), BotDeathmatchAI(), BotSetUserInfo(), CL_CheckForResend(), CL_RequestMotd(), CL_ServerInfoPacket(), Cmd_TeamTask_f(), Cvar_InfoString(), G_AddBot(), G_LoadArenas(), G_ParseInfos(), LAN_GetServerInfo(), SV_DirectConnect(), SV_RankNewGameCBF(), SV_UserinfoChanged(), SVC_Info(), SVC_Status(), UI_LoadArenas(), UI_LogAwardData(), UI_ParseInfos(), UI_SetBestScore(), UI_ShowTierVideo(), UI_SPUnlock_f(), and UI_SPUnlockMedals_f().
Info_SetValueForKey_Big()
void Info_SetValueForKey_Big (char * s, const char * key, const char * value)
Definition at line 1340 of file q_shared.c.
 {
     char    newi[BIG_INFO_STRING];
     const char* blacklist = "\\;\"";
     if (strlen(s) >= BIG_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_SetValueForKey: oversize infostring");
     }
     for (; *blacklist; ++blacklist) {
         if (strchr(key, *blacklist) || strchr(value, *blacklist)) {
             Com_Printf(S_COLOR_YELLOW "Can't use keys or values with a '%c': %s = %s\n", *blacklist, key, value);
             return;
         }
     }
     Info_RemoveKey_Big(s, key);
     if (!value)
         return;
     Com_sprintf(newi, sizeof(newi), "\\%s\\%s", key, value);
     if (strlen(newi) + strlen(s) >= BIG_INFO_STRING) {
         Com_Printf("BIG Info string length exceeded\n");
         return;
     }
     strcat(s, newi);
 }
References BIG_INFO_STRING, Com_Error(), Com_Printf(), Com_sprintf(), ERR_DROP, Info_RemoveKey_Big(), s, and S_COLOR_YELLOW.
Referenced by Cvar_InfoString_Big().
Info_Validate()
qboolean Info_Validate (const char * s)
Definition at line 1283 of file q_shared.c.
 {
     if (strchr(s, '\"')) {
         return qfalse;
     }
     if (strchr(s, ';')) {
         return qfalse;
     }
     return qtrue;
 }
References qfalse, qtrue, and s.
Referenced by ClientUserinfoChanged().
Info_ValueForKey()
char* Info_ValueForKey (const char * s, const char * key)
Definition at line 1077 of file q_shared.c.
 {
     char    pkey[BIG_INFO_KEY];
     static    char value[2][BIG_INFO_VALUE];    // use two buffers so compares
                                             // work without stomping on each other
     static    int    valueindex = 0;
     char* o;
     if (!s || !key) {
         return "";
     }
     if (strlen(s) >= BIG_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_ValueForKey: oversize infostring");
     }
     valueindex ^= 1;
     if (*s == '\\')
         s++;
     while (1) {
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 return "";
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value[valueindex];
         while (*s != '\\' && *s) {
             *o++ = *s++;
         }
         *o = 0;
         if (!Q_stricmp(key, pkey))
             return value[valueindex];
         if (!*s)
             break;
         s++;
     }
     return "";
 }
References BIG_INFO_KEY, BIG_INFO_STRING, BIG_INFO_VALUE, Com_Error(), ERR_DROP, Q_stricmp(), and s.
Referenced by ArenaServers_Insert(), BotFirstClientInRankings(), BotIsFirstInRankings(), BotIsLastInRankings(), BotIsObserver(), BotLastClientInRankings(), BotMapScripts(), BotMapTitle(), BotNumActivePlayers(), BotNumTeamMates(), BotRandomOpponentName(), BotSortTeamMatesByBaseTravelTime(), BotTeamOrders(), BotTeamplayReport(), BotUpdateInfoConfigStrings(), CG_DrawAttacker(), CG_DrawInformation(), CG_LoadingClient(), CG_NewClientInfo(), CG_Obituary(), CG_ParseServerinfo(), CL_CompletePlayerName(), CL_InitCGame(), CL_MotdPacket(), CL_ParseServerInfo(), CL_Sayto_f(), CL_ServerInfoPacket(), CL_SetServerInfo(), CL_SystemInfoChanged(), ClientConnect(), ClientFromName(), ClientName(), ClientOnSameTeamFromName(), ClientSkin(), ClientSpawn(), ClientUserinfoChanged(), G_AddBot(), G_BotConnect(), G_CheckBotSpawn(), G_GetArenaInfoByMap(), G_GetBotInfoByName(), G_InitBots(), G_InitSessionData(), G_SelectRandomBotInfo(), InGame_MenuInit(), Prepname(), ServerOptions_InitBotNames(), ServerOptions_SetMenuItems(), ServerOptions_Start(), StartServer_Cache(), StartServer_GametypeEvent(), StartServer_LevelshotDraw(), StartServer_Update(), SV_DirectConnect(), SV_SetUserinfo(), SV_UserinfoChanged(), Svcmd_BotList_f(), TeamMain_MenuInit(), UI_AddBotsMenu_Init(), UI_AddBotsMenu_SetBotNames(), UI_AddBotsMenu_SortCompare(), UI_BotSelectMenu_Default(), UI_BotSelectMenu_SortCompare(), UI_BotSelectMenu_UpdateGrid(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_BuildServerDisplayList(), UI_CalcPostGameStats(), UI_CanShowTierVideo(), UI_DrawConnectScreen(), UI_FeederItemText(), UI_FeederSelection(), UI_GetArenaInfoByMap(), UI_GetArenaInfoByNumber(), UI_GetAwardLevel(), UI_GetBestScore(), UI_GetBotInfoByName(), UI_GetBotNameByNumber(), UI_GetCurrentGame(), UI_GetSpecialArenaInfo(), UI_LoadArenas(), UI_LoadArenasIntoMapList(), UI_LogAwardData(), UI_RemoveBotsMenu_GetBots(), UI_RemoveBotsMenu_SetBotNames(), UI_RunMenuScript(), UI_SetBestScore(), UI_ShowTierVideo(), UI_SPArena_Start(), UI_SPLevelMenu(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetBots(), UI_SPLevelMenu_SetMenuArena(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_TeamOrdersMenu_BuildBotList(), UI_TeamOrdersMenu_f(), and UI_TierCompleted().
LerpAngle()
float LerpAngle (float from, float to, float frac)
Definition at line 547 of file q_math.c.
 {
     float    a;
     if (to - from > 180) {
         to -= 360;
     }
     if (to - from < -180) {
         to += 360;
     }
     a = from + frac * (to - from);
     return a;
 }
References a.
Referenced by CG_InterpolateEntityPosition(), and CG_InterpolatePlayerState().
MakeNormalVectors()
void MakeNormalVectors (const vec3_t forward, vec3_t right, vec3_t up)
Definition at line 484 of file q_math.c.
 {
     float        d;
     // this rotate and negate guarantees a vector
     // not colinear with the original
     right[1] = -forward[0];
     right[2] = forward[1];
     right[0] = forward[2];
     d = DotProduct(right, forward);
     VectorMA(right, -d, forward, right);
     VectorNormalize(right);
     CrossProduct(right, forward, up);
 }
References CrossProduct(), DotProduct, forward, right, up, VectorMA, and VectorNormalize().
Referenced by RB_SurfaceRailRings().
MatrixMultiply()
void MatrixMultiply (float in1[3][3], float in2[3][3], float out[3][3])
Definition at line 933 of file q_math.c.
 {
     out[0][0] = in1[0][0] * in2[0][0] + in1[0][1] * in2[1][0] +
         in1[0][2] * in2[2][0];
     out[0][1] = in1[0][0] * in2[0][1] + in1[0][1] * in2[1][1] +
         in1[0][2] * in2[2][1];
     out[0][2] = in1[0][0] * in2[0][2] + in1[0][1] * in2[1][2] +
         in1[0][2] * in2[2][2];
     out[1][0] = in1[1][0] * in2[0][0] + in1[1][1] * in2[1][0] +
         in1[1][2] * in2[2][0];
     out[1][1] = in1[1][0] * in2[0][1] + in1[1][1] * in2[1][1] +
         in1[1][2] * in2[2][1];
     out[1][2] = in1[1][0] * in2[0][2] + in1[1][1] * in2[1][2] +
         in1[1][2] * in2[2][2];
     out[2][0] = in1[2][0] * in2[0][0] + in1[2][1] * in2[1][0] +
         in1[2][2] * in2[2][0];
     out[2][1] = in1[2][0] * in2[0][1] + in1[2][1] * in2[1][1] +
         in1[2][2] * in2[2][1];
     out[2][2] = in1[2][0] * in2[0][2] + in1[2][1] * in2[1][2] +
         in1[2][2] * in2[2][2];
 }
References state::out.
Referenced by CG_AddPlayerWeapon(), CG_PositionEntityOnTag(), CG_PositionRotatedEntityOnTag(), RotatePointAroundVector(), SV_GameSystemCalls(), UI_PositionEntityOnTag(), and UI_PositionRotatedEntityOnTag().
NormalizeColor()
float NormalizeColor (const vec3_t in, vec3_t out)
Definition at line 247 of file q_math.c.
 {
     float    max;
     max = in[0];
     if (in[1] > max) {
         max = in[1];
     }
     if (in[2] > max) {
         max = in[2];
     }
     if (!max) {
         VectorClear(out);
     } else {
         out[0] = in[0] / max;
         out[1] = in[1] / max;
         out[2] = in[2] / max;
     }
     return max;
 }
References in, state::out, and VectorClear.
Parse1DMatrix()
void Parse1DMatrix (char ** buf_p, int x, float * m)
Definition at line 626 of file q_shared.c.
 {
     char* token;
     int        i;
     COM_MatchToken(buf_p, "(");
     for (i = 0; i < x; i++) {
         token = COM_Parse(buf_p);
         m[i] = atof(token);
     }
     COM_MatchToken(buf_p, ")");
 }
References COM_MatchToken(), COM_Parse(), and m.
Referenced by Parse2DMatrix().
Parse2DMatrix()
void Parse2DMatrix (char ** buf_p, int y, int x, float * m)
Definition at line 641 of file q_shared.c.
 {
     int        i;
     COM_MatchToken(buf_p, "(");
     for (i = 0; i < y; i++) {
         Parse1DMatrix(buf_p, x, m + i * x);
     }
     COM_MatchToken(buf_p, ")");
 }
References COM_MatchToken(), m, and Parse1DMatrix().
Referenced by Parse3DMatrix().
Parse3DMatrix()
void Parse3DMatrix (char ** buf_p, int z, int y, int x, float * m)
Definition at line 654 of file q_shared.c.
 {
     int        i;
     COM_MatchToken(buf_p, "(");
     for (i = 0; i < z; i++) {
         Parse2DMatrix(buf_p, y, x, m + i * x * y);
     }
     COM_MatchToken(buf_p, ")");
 }
References COM_MatchToken(), m, and Parse2DMatrix().
PerpendicularVector()
void PerpendicularVector (vec3_t dst, const vec3_t src)
Definition at line 992 of file q_math.c.
 {
     int    pos;
     int i;
     float minelem = 1.0F;
     vec3_t tempvec;
     /*
     ** find the smallest magnitude axially aligned vector
     */
     for (pos = 0, i = 0; i < 3; i++) {
         if (fabs(src[i]) < minelem) {
             pos = i;
             minelem = fabs(src[i]);
         }
     }
     tempvec[0] = tempvec[1] = tempvec[2] = 0.0F;
     tempvec[pos] = 1.0F;
     /*
     ** project the point onto the plane defined by src
     */
     ProjectPointOnPlane(dst, tempvec, src);
     /*
     ** normalize the result
     */
     VectorNormalize(dst);
 }
References ProjectPointOnPlane(), and VectorNormalize().
Referenced by CG_ImpactMark(), CG_Portal(), CG_RailTrail(), CG_ShotgunPattern(), R_GetPortalOrientations(), RB_DrawSun(), RB_SurfaceBeam(), RotateAroundDirection(), RotatePointAroundVector(), ShotgunPattern(), SV_GameSystemCalls(), and Use_Shooter().
PlaneFromPoints()
qboolean PlaneFromPoints (vec4_t plane, const vec3_t a, const vec3_t b, const vec3_t c)
Definition at line 278 of file q_math.c.
 {
     vec3_t    d1, d2;
     VectorSubtract(b, a, d1);
     VectorSubtract(c, a, d2);
     CrossProduct(d2, d1, plane);
     if (VectorNormalize(plane) == 0) {
         return qfalse;
     }
     plane[3] = DotProduct(a, plane);
     return qtrue;
 }
References a, CrossProduct(), DotProduct, qfalse, qtrue, VectorNormalize(), and VectorSubtract.
Referenced by R_PlaneForSurface().
ProjectPointOnPlane()
void ProjectPointOnPlane (vec3_t dst, const vec3_t p, const vec3_t normal)
Definition at line 453 of file q_math.c.
 {
     float d;
     vec3_t n;
     float inv_denom;
     inv_denom = DotProduct(normal, normal);
 #ifndef Q3_VM
     assert(Q_fabs(inv_denom) != 0.0f); // zero vectors get here
 #endif
     inv_denom = 1.0f / inv_denom;
     d = DotProduct(normal, p) * inv_denom;
     n[0] = normal[0] * inv_denom;
     n[1] = normal[1] * inv_denom;
     n[2] = normal[2] * inv_denom;
     dst[0] = p[0] - d * n[0];
     dst[1] = p[1] - d * n[1];
     dst[2] = p[2] - d * n[2];
 }
References DotProduct, and Q_fabs().
Referenced by PerpendicularVector().
Q_acos()
float Q_acos (float c)
Definition at line 1054 of file q_math.c.
 {
     float angle;
     angle = acos(c);
     if (angle > M_PI) {
         return (float)M_PI;
     }
     if (angle < -M_PI) {
         return (float)M_PI;
     }
     return angle;
 }
References M_PI.
Referenced by CL_CgameSystemCalls(), and R_InitSkyTexCoords().
Q_CleanStr()
char* Q_CleanStr (char * string)
Definition at line 967 of file q_shared.c.
 {
     char* d;
     char* s;
     int        c;
     s = string;
     d = string;
     while ((c = *s) != 0) {
         if (Q_IsColorString(s)) {
             s++;
         } else if (c >= 0x20 && c <= 0x7E) {
             *d++ = c;
         }
         s++;
     }
     *d = '\0';
     return string;
 }
References Q_IsColorString(), and s.
Referenced by ArenaServers_Insert(), CG_DrawInformation(), CG_LoadingClient(), CL_CompletePlayerName(), CL_Sayto_f(), ClientFromName(), ClientName(), ClientNumberFromString(), ClientOnSameTeamFromName(), Cmd_CallTeamVote_f(), Controls_MenuInit(), PlayerModel_SetMenuItems(), PlayerSettings_DrawName(), Prepname(), Rankings_DrawName(), ServerOptions_InitPlayerItems(), SV_CompletePlayerName(), SV_ConSayto_f(), SV_GetPlayerByHandle(), Sys_InitPIDFile(), UI_BotSelectMenu_UpdateGrid(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_RemoveBotsMenu_SetBotNames(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetBots(), UI_SPPostgameMenu_MenuDrawScoreLine(), and UI_TeamOrdersMenu_BuildBotList().
Q_CountChar()
int Q_CountChar (const char * string, char tocount)
Definition at line 988 of file q_shared.c.
 {
     int count;
     for (count = 0; *string; string++) {
         if (*string == tocount)
             count++;
     }
     return count;
 }
References count.
Referenced by NET_IP6Socket(), and NET_StringToAdr().
Q_crandom()
float Q_crandom (int * seed)
Definition at line 161 of file q_math.c.
 {
     return 2.0 * (Q_random(seed) - 0.5);
 }
References Q_random().
Referenced by CG_ShotgunPattern(), and ShotgunPattern().
Q_fabs()
float Q_fabs (float f)
Definition at line 530 of file q_math.c.
 {
     floatint_t fi;
     fi.f = f;
     fi.i &= 0x7FFFFFFF;
     return fi.f;
 }
References floatint_t::f, and floatint_t::i.
Referenced by ProjectPointOnPlane(), and UI_MovedirAdjustment().
Q_isalpha()
int Q_isalpha (int c)
Definition at line 733 of file q_shared.c.
 {
     if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))
         return (1);
     return (0);
 }
Referenced by MenuField_Key(), Rankings_DrawName(), and Rankings_DrawPassword().
Q_isanumber()
qboolean Q_isanumber (const char * s)
Definition at line 740 of file q_shared.c.
 {
     char* p;
     double UNUSED_VAR d;
     if (*s == '\0')
         return qfalse;
     d = strtod(s, &p);
     return *p == '\0';
 }
References qfalse, s, and UNUSED_VAR.
Referenced by Cvar_Validate().
Q_IsColorString()
qboolean Q_IsColorString (const char * p)
Definition at line 27 of file q_shared.c.
 {
     if (!p)
         return qfalse;
     if (p[0] != Q_COLOR_ESCAPE)
         return qfalse;
     if (p[1] == 0)
         return qfalse;
     // isalnum expects a signed integer in the range -1 (EOF) to 255, or it might assert on undefined behaviour
     // a dereferenced char pointer has the range -128 to 127, so we just need to rangecheck the negative part
     if (p[1] < 0)
         return qfalse;
     if (isalnum(p[1]) == 0)
         return qfalse;
     return qtrue;
 }
References Q_COLOR_ESCAPE, qfalse, and qtrue.
Referenced by CG_AddToTeamChat(), CG_DrawStringExt(), CG_DrawStrlen(), CG_Text_Paint_Limit(), CL_ConsolePrint(), ClientCleanName(), CON_Show(), CON_WindowsColorPrint(), PlayerSettings_DrawName(), Q_CleanStr(), Q_PrintStrlen(), RemoveColorEscapeSequences(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), SCR_Strlen(), SV_Strlen(), Sys_AnsiColorPrint(), Text_Height(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), Text_Width(), and UI_DrawString2().
Q_isintegral()
qboolean Q_isintegral (float f)
Definition at line 753 of file q_shared.c.
 {
     return (int)f == f;
 }
Referenced by Cvar_SetValueSafe(), and Cvar_Validate().
Q_islower()
int Q_islower (int c)
Definition at line 719 of file q_shared.c.
 {
     if (c >= 'a' && c <= 'z')
         return (1);
     return (0);
 }
Referenced by MenuField_Key().
Q_isnan()
int Q_isnan (float x)
Definition at line 1029 of file q_math.c.
 {
     floatint_t fi;
     fi.f = x;
     fi.ui &= 0x7FFFFFFF;
     fi.ui = 0x7F800000 - fi.ui;
     return (int)((unsigned int)fi.ui >> 31);
 }
References floatint_t::f, int(), and floatint_t::ui.
Referenced by RE_AddRefEntityToScene().
Q_isprint()
int Q_isprint (int c)
Definition at line 712 of file q_shared.c.
 {
     if (c >= 0x20 && c <= 0x7E)
         return (1);
     return (0);
 }
Referenced by ScrollList_Key().
Q_isupper()
int Q_isupper (int c)
Definition at line 726 of file q_shared.c.
 {
     if (c >= 'A' && c <= 'Z')
         return (1);
     return (0);
 }
Referenced by MenuField_Key(), and ScrollList_Key().
Q_log2()
int Q_log2 (int val)
Definition at line 896 of file q_math.c.
 {
     int answer;
     answer = 0;
     while ((val >>= 1) != 0) {
         answer++;
     }
     return answer;
 }
Q_PrintStrlen()
int Q_PrintStrlen (const char * string)
Definition at line 943 of file q_shared.c.
 {
     int            len;
     const char* p;
     if (!string) {
         return 0;
     }
     len = 0;
     p = string;
     while (*p) {
         if (Q_IsColorString(p)) {
             p += 2;
             continue;
         }
         p++;
         len++;
     }
     return len;
 }
References Q_IsColorString().
Referenced by CG_DrawAttacker().
Q_rand()
int Q_rand (int * seed)
Definition at line 150 of file q_math.c.
 {
     *seed = (69069U * *seed + 1U);
     return *seed;
 }
Referenced by Q_random().
Q_random()
float Q_random (int * seed)
Definition at line 156 of file q_math.c.
 {
     return (Q_rand(seed) & 0xffff) / (float)0x10000;
 }
References Q_rand().
Referenced by CG_SmokePuff(), and Q_crandom().
Q_rsqrt()
float Q_rsqrt (float f)
Definition at line 514 of file q_math.c.
 {
     floatint_t t;
     float x2, y;
     const float threehalfs = 1.5F;
     x2 = number * 0.5F;
     t.f = number;
     t.i = 0x5f3759df - (t.i >> 1);               // what the fuck?
     y = t.f;
     y = y * (threehalfs - (x2 * y * y));   // 1st iteration
 //    y  = y * ( threehalfs - ( x2 * y * y ) );   // 2nd iteration, this can be removed
     return y;
 }
References t.
Referenced by VectorNormalizeFast().
Q_strcat()
void Q_strcat (char * dest, int size, const char * src)
Definition at line 904 of file q_shared.c.
 {
     int        l1;
     l1 = strlen(dest);
     if (l1 >= size) {
         Com_Error(ERR_FATAL, "Q_strcat: already overflowed");
     }
     Q_strncpyz(dest + l1, src, size - l1);
 }
References Com_Error(), ERR_FATAL, and Q_strncpyz().
Referenced by BuildShaderStateConfig(), CG_BuildSpectatorString(), CG_RegisterWeapon(), CL_GlobalServers_f(), CL_Rcon_f(), CL_SaveConsoleHistory(), CL_ServerInfoPacket(), CollapseStagesToLightall(), COM_DefaultExtension(), Com_MD5File(), Com_Printf(), Com_TruncateLongString(), Con_Dump_f(), Field_Complete(), Field_CompletePlayerNameFinal(), FS_CheckPak0(), FS_ComparePaks(), FS_LoadedPakChecksums(), FS_LoadedPakNames(), FS_LoadedPakPureChecksums(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), FS_ReferencedPakPureChecksums(), GLSL_GetShaderHeader(), GLSL_InitGPUShaders(), Item_EnableShowViaCvar(), Item_RunScript(), main(), ParseStage(), PC_Directive_include(), PC_Script_Parse(), PlayerModel_SetMenuItems(), R_FindImageFile(), R_LoadImage(), RB_ExportCubemaps(), S_AL_Init(), ServerInfo_MenuDraw(), SVC_RemoteCommand(), Sys_DefaultHomePath(), Sys_SteamPath(), UI_PlayerInfo_SetWeapon(), UI_RunMenuScript(), and UpdateIPBans().
Q_stricmp()
int Q_stricmp (const char * s1, const char * s2)
Definition at line 872 of file q_shared.c.
 {
     return (s1 && s2) ? Q_stricmpn(s1, s2, 99999) : -1;
 }
References Q_stricmpn().
Referenced by AddRemap(), Alias_Parse(), ArenaServers_Compare(), ArenaServers_DoRefresh(), ArenaServers_LoadFavorites(), ArenaServers_Remove(), Asset_Parse(), BG_FindItem(), BindingFromName(), BindingIDFromName(), BotAI(), BotAlreadySelected(), BotChooseInitialChatMessage(), BotFindWayPoint(), BotGetLevelItemGoal(), BotGetMapLocationGoal(), BotGetTeamMateTaskPreference(), BotLoadInitialChat(), BotMapScripts(), BotMatch_CTF(), BotMatch_StopTeamLeaderShip(), BotMatch_TaskPreference(), BotMatch_WhatIsMyCommand(), BotMatch_WhoIsTeamLeader(), BotNearestVisibleItem(), BotNumInitialChats(), BotReportStatus(), BotSetBrushModelTypes(), BotSetEntityNumForGoal(), BotSetEntityNumForGoalWithActivator(), BotSetInfoConfigString(), BotTeamAI(), BotVoiceChat_StopLeader(), BotVoiceChat_WhoIsLeader(), BotVoiceChatCommand(), CG_ClientNumFromName(), CG_ConsoleCommand(), CG_ParseAnimationFile(), CG_ParticleExplosion(), CG_ScanForExistingClientInfo(), CG_ServerCommand(), CG_SetDeferredClientInfo(), Character_Parse(), CheckCvars(), CL_BindUICommand(), CL_CDKeyValidate(), CL_ConnectionlessPacket(), CL_GlobalServers_f(), CL_MapLoading(), CL_OpenAVIForWriting(), CL_PlayCinematic_f(), CL_Sayto_f(), CL_SystemInfoChanged(), ClientCommand(), ClientConnect(), ClientForString(), ClientFromName(), ClientNumberFromString(), ClientOnSameTeamFromName(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_CompleteArgument(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_FindCommand(), Cmd_Give_f(), Cmd_SetCommandCompletionFunc(), COM_CompareExtension(), Com_SafeMode(), ConsoleCommand(), Controls_GetKeyAssignment(), Cvar_FindVar(), Cvar_Print(), Cvar_WriteVariables(), ExitLevel(), Favorites_Add(), Field_CompletePlayerName(), FindClientByName(), FindEnemyByName(), FindShaderInShaderText(), FS_AddFileToList(), FS_AddGameDirectory(), FS_CheckPak0(), FS_FOpenFileReadDir(), FS_GetFileList(), FS_GetModList(), FS_IsExt(), FS_ListFilteredFiles(), FS_LoadZipFile(), FS_Restart(), FS_Startup(), FS_SV_FOpenFileRead(), G_AddBot(), G_CountBotPlayersByName(), G_Find(), G_GetArenaInfoByMap(), G_GetBotInfoByName(), G_InitBots(), G_ParseField(), G_SpawnString(), GameType_Parse(), GametypeBits(), GL_TextureMode(), GraphicsOptions_FindBuiltinResolution(), GraphicsOptions_FindDetectedResolution(), GraphicsOptions_GetAspectRatios(), GraphicsOptions_SetMenuItems(), Hunk_SmallLog(), Info_ValueForKey(), Item_ApplyHacks(), Item_EnableShowViaCvar(), Item_Multi_FindCvarByValue(), Item_Multi_Setting(), Item_RunScript(), Key_GetKey(), Key_StringToKeynum(), KeywordHash_Find(), LAN_CompareServers(), LibVarGet(), LoadConfig_MenuInit(), MapList_Parse(), Menu_FindItemByName(), Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), MenuParse_name(), Menus_ActivateByName(), Menus_FindByName(), NameToAFunc(), NameToDstBlendMode(), NameToGenFunc(), NameToSrcBlendMode(), ParseDeform(), ParseShader(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseTexMod(), PC_PushScript(), PC_Script_Parse(), PlayerIcon(), PlayerIntroSound(), PlayerModel_SetMenuItems(), R_FindShader(), R_FindShaderByName(), R_LoadCubemapEntities(), R_LoadEntities(), R_LoadImage(), R_RemapShader(), RE_BeginFrame(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterShaderFromImage(), RE_RegisterSkin(), S_AL_Init(), S_CodecGetSound(), S_FindName(), Script_SetColor(), Script_SetItemColor(), ServerPlayerIcon(), SetTeam(), SP_worldspawn(), SV_AuthorizeIpPacket(), SV_ConnectionlessPacket(), SV_ConSayto_f(), SV_GetPlayerByHandle(), SV_Kick_f(), SV_Map_f(), SV_MasterHeartbeat(), SV_UserinfoChanged(), SV_WriteDownloadToClient(), Sys_ListFiles(), Sys_ListFilteredFiles(), target_location_linkup(), Team_Parse(), UI_AddBotsMenu_SortCompare(), UI_AIFromName(), UI_AIIndex(), UI_AIIndexFromName(), UI_BotSelectMenu_Default(), UI_BotSelectMenu_SortCompare(), UI_BuildQ3Model_List(), UI_BuildServerDisplayList(), UI_ConsoleCommand(), UI_DrawConnectScreen(), UI_EnglishMapName(), UI_GetArenaInfoByMap(), UI_GetBotInfoByName(), UI_GetSpecialArenaInfo(), UI_HeadCountByTeam(), UI_LoadMenus(), UI_LoadMovies(), UI_OpponentLeaderModel(), UI_ParseAnimationFile(), UI_ParseGameInfo(), UI_ParseMenu(), UI_ParseTeamInfo(), UI_ResolutionToAspect(), UI_RunMenuScript(), UI_SortServerStatusInfo(), UI_SPArena_Start(), UI_SPLevelMenu_MenuDraw(), UI_TeamArenaExists(), UI_TeamIndexFromName(), UI_Update(), and VM_Create().
Q_stricmpn()
int Q_stricmpn (const char * s1, const char * s2, int n)
Definition at line 814 of file q_shared.c.
 {
     int        c1, c2;
     if (s1 == NULL) {
         if (s2 == NULL)
             return 0;
         else
             return -1;
     } else if (s2 == NULL)
         return 1;
     do {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--) {
             return 0;        // strings are equal until end point
         }
         if (c1 != c2) {
             if (c1 >= 'a' && c1 <= 'z') {
                 c1 -= ('a' - 'A');
             }
             if (c2 >= 'a' && c2 <= 'z') {
                 c2 -= ('a' - 'A');
             }
             if (c1 != c2) {
                 return c1 < c2 ? -1 : 1;
             }
         }
     } while (c1);
     return 0;        // strings are equal
 }
References NULL.
Referenced by CG_ServerCommand(), CL_PlayDemo_f(), Cmd_CallVote_f(), Com_AddStartupCommands(), FindMatches(), FS_CheckPak0(), FS_GetModList(), FS_IsDemoExt(), FS_ListFilteredFiles(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), ParseDeform(), ParseShader(), PlayerModel_BuildList(), PrintCvarMatches(), PrintMatches(), Q_stricmp(), Q_stristr(), SV_Map_f(), and UI_BuildQ3Model_List().
Q_stristr()
const char* Q_stristr (const char * s, const char * find)
Definition at line 918 of file q_shared.c.
 {
     char c, sc;
     size_t len;
     if ((c = *find++) != 0) {
         if (c >= 'a' && c <= 'z') {
             c -= ('a' - 'A');
         }
         len = strlen(find);
         do {
             do {
                 if ((sc = *s++) == 0)
                     return NULL;
                 if (sc >= 'a' && sc <= 'z') {
                     sc -= ('a' - 'A');
                 }
             } while (sc != c);
         } while (Q_stricmpn(s, find, len) != 0);
         s--;
     }
     return s;
 }
References NULL, Q_stricmpn(), and s.
Q_strlwr()
char* Q_strlwr (char * s1)
Definition at line 878 of file q_shared.c.
 {
     char* s;
     s = s1;
     while (*s) {
         *s = tolower(*s);
         s++;
     }
     return s1;
 }
References s.
Referenced by FS_LoadZipFile(), R_LoadIQM(), R_LoadMD3(), R_LoadMDR(), and RE_RegisterSkin().
Q_strncmp()
int Q_strncmp (const char * s1, const char * s2, int n)
Definition at line 852 of file q_shared.c.
 {
     int        c1, c2;
     do {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--) {
             return 0;        // strings are equal until end point
         }
         if (c1 != c2) {
             return c1 < c2 ? -1 : 1;
         }
     } while (c1);
     return 0;        // strings are equal
 }
Referenced by CheckTeamVote(), CL_ConnectionlessPacket(), CL_ConsolePrint(), main(), R_LoadEntities(), R_LoadIQM(), S_FindRIFFChunk(), SpecifyLeague_Event(), and SV_ConnectionlessPacket().
Q_strncpyz()
void Q_strncpyz (char * dest, const char * src, int destsize)
Definition at line 798 of file q_shared.c.
 {
     if (!dest) {
         Com_Error(ERR_FATAL, "Q_strncpyz: NULL dest");
     }
     if (!src) {
         Com_Error(ERR_FATAL, "Q_strncpyz: NULL src");
     }
     if (destsize < 1) {
         Com_Error(ERR_FATAL, "Q_strncpyz: destsize < 1");
     }
     strncpy(dest, src, destsize - 1);
     dest[destsize - 1] = 0;
 }
References Com_Error(), and ERR_FATAL.
Referenced by AAS_LoadFiles(), ArenaServers_Insert(), ArenaServers_LoadFavorites(), BotCreateWayPoint(), BotFindMatch(), BotGoalName(), BotLoadChatFile(), BotLoadInitialChat(), BotMatch_NewLeader(), BotNextConsoleMessage(), BotQueueConsoleMessage(), BotVoiceChatCommand(), CG_CenterPrint(), CG_ConfigStringModified(), CG_DrawInformation(), CG_LoadClientInfo(), CG_LoadingClient(), CG_LoadingString(), CG_NewClientInfo(), CG_Obituary(), CG_ParseServerinfo(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_ServerCommand(), CG_StartMusic(), CG_TestModel_f(), CL_AddReliableCommand(), CL_BeginDownload(), CL_CheckForResend(), CL_CompletePlayerName(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_Frame(), CL_GetClipboardData(), CL_GetPing(), CL_GetPingInfo(), CL_MapLoading(), CL_MotdPacket(), CL_NextDemo(), CL_OpenAVIForWriting(), CL_ParseBinding(), CL_ParseCommandString(), CL_ParseGamestate(), CL_ParseServerInfo(), CL_PlayDemo_f(), CL_Record_f(), CL_Sayto_f(), CL_ServerInfoPacket(), CL_ServerStatus(), CL_SetServerInfo(), ClientCleanName(), ClientNumberFromString(), ClientUserinfoChanged(), CM_LoadMap(), Cmd_ArgsBuffer(), Cmd_ArgvBuffer(), Cmd_CallTeamVote_f(), Cmd_Exec_f(), Cmd_TokenizeString2(), Com_AppendCDKey(), Com_FieldStringToPlayerName(), Com_MD5File(), Com_ReadCDKey(), COM_StripExtension(), Com_TruncateLongString(), Com_WriteCDKey(), Com_WriteConfig_f(), Con_Dump_f(), CON_HistAdd(), CON_HistNext(), CON_HistPrev(), CON_Input(), Console_Key(), CreateInternalShaders(), Cvar_InfoStringBuffer(), Cvar_Update(), Cvar_VariableStringBuffer(), FBO_Create(), Field_Complete(), Field_CompletePlayerNameFinal(), FindMatches(), FS_AddGameDirectory(), FS_CreatePath(), FS_FCreateOpenPipeFile(), FS_FilenameCompletion(), FS_FindVM(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_GetModDescription(), FS_InitFilesystem(), FS_LoadZipFile(), FS_Restart(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), G_BotConnect(), G_InitBots(), G_ParseInfos(), G_ProcessIPBans(), G_Say(), G_SpawnBots(), GetClientState(), GetConfigString(), GLimp_InitExtraExtensions(), GLSL_InitGPUShader2(), GLSL_LoadGPUShaderText(), GLSL_PrintLog(), GraphicsOptions_ApplyChanges(), GraphicsOptions_GetAspectRatios(), InitShader(), Item_Multi_HandleKey(), Key_GetBindingBuf(), Key_KeynumToStringBuf(), LAN_AddServer(), LAN_GetServerAddressString(), LAN_GetServerInfo(), LoadItemConfig(), LoadScriptFile(), LoadScriptMemory(), LoadSourceFile(), LoadSourceMemory(), LoadWeaponConfig(), Log_Open(), MSG_WriteBigString(), MSG_WriteString(), NET_AddLocalAddress(), NET_StringToAdr(), PC_DefineFromString(), PC_Directive_include(), PC_SetIncludePath(), PlayerIcon(), PlayerIntroSound(), PlayerModel_PicEvent(), PlayerModel_SetMenuItems(), PlayerSettings_DrawName(), PlayerSettings_SetMenuItems(), Prepname(), PS_ReadPunctuation(), Q_strcat(), R_CreateVao(), R_CreateVao2(), R_GetEntityToken(), R_InitSkins(), R_LoadCubemapEntities(), R_LoadEntities(), R_LoadImage(), R_LoadIQM(), R_LoadMD3(), R_LoadMDR(), R_PrintLongString(), R_TakeScreenshot(), Rankings_DrawPassword(), RE_LoadWorldMap(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterSkin(), ReadWeightConfig(), S_Base_StartBackgroundTrack(), S_CodecGetSound(), ScanAndLoadShaderFiles(), ServerOptions_InitBotNames(), ServerOptions_LevelshotDraw(), ServerOptions_SetMenuItems(), ServerPlayerIcon(), SP_target_speaker(), SpecifyLeague_GetList(), SpecifyLeague_MenuInit(), StartServer_Cache(), StartServer_LevelshotDraw(), StartServer_Update(), SV_AddBanToList(), SV_AddServerCommand(), SV_BeginDownload_f(), SV_BotGetConsoleMessage(), SV_CompletePlayerName(), SV_ConSayto_f(), SV_DirectConnect(), SV_GameSystemCalls(), SV_GetConfigstring(), SV_GetPlayerByHandle(), SV_GetServerinfo(), SV_GetUserinfo(), SV_Map_f(), SV_MapRestart_f(), SV_Netchan_Transmit(), SV_RankUserValidate(), SV_SendConfigstring(), SV_SetUserinfo(), SV_SpawnServer(), SV_UpdateUserinfo_f(), SV_UserinfoChanged(), Svcmd_BotList_f(), Sys_Basename(), Sys_Dirname(), Sys_GetClipboardData(), Sys_SetBinaryPath(), Sys_SetDefaultInstallPath(), Sys_StripAppBundle(), Text_PaintCenter_AutoWrapped(), UI_AddBotsMenu_SetBotNames(), UI_BotSelectMenu_SelectEvent(), UI_BotSelectMenu_UpdateGrid(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_ConsoleCommand(), UI_DrawConnectScreen(), UI_DrawGLInfo(), UI_DrawOpponent(), UI_DrawPlayerModel(), UI_DrawProportionalString_AutoWrapped(), UI_DrawServerRefreshDate(), UI_DriverInfo_Menu(), UI_FeederSelection(), UI_GetServerStatusInfo(), UI_Load(), UI_Mods_ParseInfos(), UI_ParseInfos(), UI_RegisterClientModelname(), UI_RemoveBotsMenu_SetBotNames(), UI_ResolutionToAspect(), UI_RunMenuScript(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetBots(), UI_SPLevelMenu_SetMenuArena(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_TeamOrdersMenu_BuildBotList(), VM_Create(), VM_LoadSymbols(), and VM_Restart().
Q_strupr()
char* Q_strupr (char * s1)
Definition at line 890 of file q_shared.c.
 {
     char* s;
     s = s1;
     while (*s) {
         *s = toupper(*s);
         s++;
     }
     return s1;
 }
References s.
Referenced by ArenaServers_Insert(), BindingFromName(), Controls_DrawKeyBinding(), LoadConfig_MenuInit(), PlayerModel_PicEvent(), PlayerModel_SetMenuItems(), ServerOptions_SetMenuItems(), StartServer_Cache(), StartServer_LevelshotDraw(), StartServer_Update(), UI_LoadMovies(), UI_SPLevelMenu_MenuDraw(), and UI_SPLevelMenu_SetMenuArena().
Q_vsnprintf()
int Q_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 769 of file q_shared.c.
 {
     int retval;
     retval = _vsnprintf(str, size, format, ap);
     if (retval < 0 || retval == size) {
         // Microsoft doesn't adhere to the C99 standard of vsnprintf,
         // which states that the return value must be the number of
         // bytes written if the output string had sufficient length.
         //
         // Obviously we cannot determine that value from Microsoft's
         // implementation, so we have no choice but to return size.
         str[size - 1] = '\0';
         return size;
     }
     return retval;
 }
References format().
Referenced by __attribute__(), AAS_Error(), BotAI_Print(), CG_Error(), CG_Printf(), Com_DPrintf(), Com_Error(), COM_ParseError(), COM_ParseWarning(), Com_Printf(), Com_sprintf(), FS_Printf(), G_Error(), G_LogPrintf(), G_Printf(), NET_OutOfBandPrint(), ScriptError(), ScriptWarning(), SourceError(), SourceWarning(), SV_RankError(), SV_SendServerCommand(), Sys_Error(), and va().
RadiusFromBounds()
float RadiusFromBounds (const vec3_t mins, const vec3_t maxs)
Definition at line 713 of file q_math.c.
 {
     int        i;
     vec3_t    corner;
     float    a, b;
     for (i = 0; i < 3; i++) {
         a = fabs(mins[i]);
         b = fabs(maxs[i]);
         corner[i] = a > b ? a : b;
     }
     return VectorLength(corner);
 }
References a, and VectorLength().
Referenced by BotImport_BSPModelMinsMaxsOrigin(), G_MoverPush(), R_ComputeLOD(), and SV_LinkEntity().
RotateAroundDirection()
void RotateAroundDirection (vec3_t axis[3], float yaw)
Definition at line 362 of file q_math.c.
 {
     // create an arbitrary axis[1]
     PerpendicularVector(axis[1], axis[0]);
     // rotate it around axis[0] by yaw
     if (yaw) {
         vec3_t    temp;
         VectorCopy(axis[1], temp);
         RotatePointAroundVector(axis[1], axis[0], temp, yaw);
     }
     // cross to get axis[2]
     CrossProduct(axis[0], axis[1], axis[2]);
 }
References CrossProduct(), PerpendicularVector(), RotatePointAroundVector(), and VectorCopy.
Referenced by CG_MakeExplosion(), and CG_Missile().
RotatePointAroundVector()
void RotatePointAroundVector (vec3_t dst, const vec3_t dir, const vec3_t point, float degrees)
Definition at line 300 of file q_math.c.
 {
     float    m[3][3];
     float    im[3][3];
     float    zrot[3][3];
     float    tmpmat[3][3];
     float    rot[3][3];
     int    i;
     vec3_t vr, vup, vf;
     float    rad;
     vf[0] = dir[0];
     vf[1] = dir[1];
     vf[2] = dir[2];
     PerpendicularVector(vr, dir);
     CrossProduct(vr, vf, vup);
     m[0][0] = vr[0];
     m[1][0] = vr[1];
     m[2][0] = vr[2];
     m[0][1] = vup[0];
     m[1][1] = vup[1];
     m[2][1] = vup[2];
     m[0][2] = vf[0];
     m[1][2] = vf[1];
     m[2][2] = vf[2];
     memcpy(im, m, sizeof(im));
     im[0][1] = m[1][0];
     im[0][2] = m[2][0];
     im[1][0] = m[0][1];
     im[1][2] = m[2][1];
     im[2][0] = m[0][2];
     im[2][1] = m[1][2];
     memset(zrot, 0, sizeof(zrot));
     zrot[0][0] = zrot[1][1] = zrot[2][2] = 1.0F;
     rad = DEG2RAD(degrees);
     zrot[0][0] = cos(rad);
     zrot[0][1] = sin(rad);
     zrot[1][0] = -sin(rad);
     zrot[1][1] = cos(rad);
     MatrixMultiply(m, zrot, tmpmat);
     MatrixMultiply(tmpmat, im, rot);
     for (i = 0; i < 3; i++) {
         dst[i] = rot[i][0] * point[0] + rot[i][1] * point[1] + rot[i][2] * point[2];
     }
 }
References CrossProduct(), DEG2RAD, m, MatrixMultiply(), PerpendicularVector(), and vup.
Referenced by CG_ImpactMark(), CG_RailTrail(), R_GetPortalOrientations(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), and RotateAroundDirection().
SetPlaneSignbits()
void SetPlaneSignbits (struct cplane_s * out)
Definition at line 651 of file q_math.c.
 {
     int    bits, j;
     // for fast box on planeside test
     bits = 0;
     for (j = 0; j < 3; j++) {
         if (out->normal[j] < 0) {
             bits |= 1 << j;
         }
     }
     out->signbits = bits;
 }
References bits(), and state::out.
Referenced by CM_InitBoxHull(), ParseFace(), R_RenderPshadowMaps(), R_SetupFrustum(), and R_SetupProjectionOrtho().
SkipBracedSection()
qboolean SkipBracedSection (char ** program, int depth)
Definition at line 582 of file q_shared.c.
 {
     char* token;
     do {
         token = COM_ParseExt(program, qtrue);
         if (token[1] == 0) {
             if (token[0] == '{') {
                 depth++;
             } else if (token[0] == '}') {
                 depth--;
             }
         }
     } while (depth && *program);
     return (depth == 0);
 }
References COM_ParseExt(), program, and qtrue.
Referenced by FindShaderInShaderText(), and ScanAndLoadShaderFiles().
SkipRestOfLine()
void SkipRestOfLine (char ** data)
Definition at line 605 of file q_shared.c.
 {
     char* p;
     int        c;
     p = *data;
     if (!*p)
         return;
     while ((c = *p++) != 0) {
         if (c == '\n') {
             com_lines++;
             break;
         }
     }
     *data = p;
 }
References com_lines.
Referenced by ParseShader().
va()
char* QDECL va (char * format, ...)
vectoangles()
void vectoangles (const vec3_t value1, vec3_t angles)
Definition at line 382 of file q_math.c.
 {
     float    forward;
     float    yaw, pitch;
     if (value1[1] == 0 && value1[0] == 0) {
         yaw = 0;
         if (value1[2] > 0) {
             pitch = 90;
         } else {
             pitch = 270;
         }
     } else {
         if (value1[0]) {
             yaw = (atan2(value1[1], value1[0]) * 180 / M_PI);
         } else if (value1[1] > 0) {
             yaw = 90;
         } else {
             yaw = 270;
         }
         if (yaw < 0) {
             yaw += 360;
         }
         forward = sqrt(value1[0] * value1[0] + value1[1] * value1[1]);
         pitch = (atan2(value1[2], forward) * 180 / M_PI);
         if (pitch < 0) {
             pitch += 360;
         }
     }
     angles[PITCH] = -pitch;
     angles[YAW] = yaw;
     angles[ROLL] = 0;
 }
References forward, M_PI, PITCH, ROLL, and YAW.
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), BG_TouchJumpPad(), BotAimAtEnemy(), BotCheckAttack(), BotClearPath(), BotEntityVisible(), BotFindEnemy(), BotGetLongTermGoal(), BotLongTermGoal(), BotMapScripts(), CG_AddParticles(), CG_AddParticleToScene(), CG_ParticleBloodCloud(), CG_ParticleDust(), FindIntermissionPoint(), G_MissileImpact(), P_DamageFeedback(), PodiumPlacementThink(), SpawnModelOnVictoryPad(), and ValidBloodPool().
Vector4Scale()
void Vector4Scale (const vec4_t in, vec_t scale, vec4_t out)
Definition at line 887 of file q_math.c.
 {
     out[0] = in[0] * scale;
     out[1] = in[1] * scale;
     out[2] = in[2] * scale;
     out[3] = in[3] * scale;
 }
References in, and state::out.
VectorCompare()
static ID_INLINE int VectorCompare (const vec3_t v1, const vec3_t v2) static
Definition at line 609 of file q_shared.h.
 {
     if (v1[0] != v2[0] || v1[1] != v2[1] || v1[2] != v2[2]) {
         return 0;
     }
     return 1;
 }
Referenced by AAS_SetMovedir(), AAS_UpdateEntity(), AINode_Seek_ActivateEntity(), BotGetActivateGoal(), BotSetMovedir(), CG_PredictPlayerState(), G_SetMovedir(), GLSL_SetUniformVec3(), InitTrigger(), and RE_RenderScene().
VectorInverse()
static ID_INLINE void VectorInverse (vec3_t v) static
Definition at line 656 of file q_shared.h.
 {
     v[0] = -v[0];
     v[1] = -v[1];
     v[2] = -v[2];
 }
Referenced by AAS_BoxOriginDistanceFromPlane(), AAS_Reachability_EqualFloorHeight(), CG_CreateRotationMatrix(), CG_Player(), CreateRotationMatrix(), G_CreateRotationMatrix(), and R_MarkFragments().
VectorLength()
static ID_INLINE vec_t VectorLength (const vec3_t v) static
Definition at line 617 of file q_shared.h.
 {
     return (vec_t)sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
 }
Referenced by AAS_AlternativeRouteGoals(), AAS_AreaTravelTime(), AAS_FaceArea(), AAS_FindFaceReachabilities(), AAS_NearestEntity(), AAS_NearestHideArea(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_TraceClientBBox(), AAS_WeaponJumpZVelocity(), AutospriteDeform(), BotAimAtEnemy(), BotClearPath(), BotCTFSeekGoals(), BotFindEntityForLevelItem(), BotFinishTravel_FuncBobbing(), BotFuzzyPointReachabilityArea(), BotNearestVisibleItem(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotTravel_WalkOffLedge(), BotUpdateBattleInventory(), BotUpdateEntityItems(), BotWalkInDirection(), BoundingSphereOfSpheres(), CG_AddFallScaleFade(), CG_AddMoveScaleFade(), CG_AddScaleFade(), CG_AddScorePlum(), CG_DamageFeedback(), CG_ParticleBloodCloud(), CG_ParticleDust(), CG_PredictPlayerState(), CheckAlmostCapture(), CheckAlmostScored(), CheckWinding(), CM_NeedsSubdivision(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), Distance(), DistancePointToLine(), G_BounceMissile(), G_MissileImpact(), G_RadiusDamage(), InitMover(), ParseMesh(), PM_DeadMove(), PM_Friction(), PM_GrappleMove(), PM_NoclipMove(), PM_WalkMove(), PM_WaterMove(), R_ComputeIQMFogNum(), R_CreateSurfaceGridMesh(), R_RenderPshadowMaps(), R_RotateForEntity(), R_SetupEntityLighting(), RadiusFromBounds(), Reached_Train(), SelectNearestDeathmatchSpawnPoint(), SelectRandomFurthestSpawnPoint(), Team_FragBonuses(), VectorDistance(), and WindingArea().
VectorLengthSquared()
static ID_INLINE vec_t VectorLengthSquared (const vec3_t v) static
Definition at line 622 of file q_shared.h.
 {
     return (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
 }
Referenced by AINode_Seek_LTG(), BotAimAtEnemy(), BotCheckAttack(), BotEntityVisible(), BotFindEnemy(), BotGetLongTermGoal(), BotLongTermGoal(), BotSetEntityNumForGoal(), BotSetEntityNumForGoalWithActivator(), BotSetEntityNumForGoalWithModel(), BotVisibleTeamMatesAndEnemies(), CM_DistanceFromLineSquared(), CM_TestCapsuleInCapsule(), CM_Trace(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), CM_VectorDistanceSquared(), DistanceFromLineSquared(), MakeMeshNormals(), R_SubdividePatchToGrid(), S_Base_AddLoopingSound(), SurfIsOffscreen(), SV_AddEntitiesVisibleFromPoint(), and VectorDistanceSquared().
VectorNormalize()
vec_t VectorNormalize (vec3_t v)
Definition at line 804 of file q_math.c.
 {
     // NOTE: TTimo - Apple G4 altivec source uses double?
     float    length, ilength;
     length = v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
     if (length) {
         /* writing it this way allows gcc to recognize that rsqrt can be used */
         ilength = 1 / (float)sqrt(length);
         /* sqrt(length) = length * (1 / sqrt(length)) */
         length *= ilength;
         v[0] *= ilength;
         v[1] *= ilength;
         v[2] *= ilength;
     }
     return length;
 }
Referenced by AAS_ClientMovementPrediction(), AAS_DrawArrow(), AAS_GetJumpPadInfo(), AAS_JumpReachRunStart(), AAS_NearbySolidOrGap(), AAS_ProjectPointOntoVector(), AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Ladder(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_WalkOffLedge(), AAS_ShowReachability(), AAS_TestMovementPrediction(), AAS_TraceClientBBox(), AAS_WeaponJumpZVelocity(), AimAtTarget(), Autosprite2Deform(), BotAddToTarget(), BotAIBlocked(), BotAimAtEnemy(), BotAirControl(), BotAttackMove(), BotCheckBarrierJump(), BotFinishTravel_Elevator(), BotFinishTravel_FuncBobbing(), BotFinishTravel_Jump(), BotFinishTravel_JumpPad(), BotFinishTravel_Walk(), BotFinishTravel_WalkOffLedge(), BotFinishTravel_WeaponJump(), BotGetLongTermGoal(), BotImport_DebugLineShow(), BotMoveInGoalArea(), BotRoamGoal(), BotSwimInDirection(), BotTravel_BarrierJump(), BotTravel_BFGJump(), BotTravel_Crouch(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotTravel_Jump(), BotTravel_Ladder(), BotTravel_RocketJump(), BotTravel_Swim(), BotTravel_Teleport(), BotTravel_Walk(), BotTravel_WalkOffLedge(), BotTravel_WaterJump(), BotWalkInDirection(), CG_AddScorePlum(), CG_BubbleTrail(), CG_LightningBolt(), CG_Player(), CG_PlayerAngles(), CG_PlayerFlag(), CG_RailTrail(), CG_ShotgunFire(), CG_Tracer(), CM_AddFacetBevels(), CM_PlaneFromPoints(), CM_TraceThroughSphere(), CM_TraceThroughVerticalCylinder(), DebugLine(), fire_bfg(), fire_grapple(), fire_grenade(), fire_plasma(), fire_rocket(), G_BounceProjectile(), G_Damage(), G_MissileImpact(), locateCamera(), MakeNormalVectors(), ParseShader(), PerpendicularVector(), Pickup_Powerup(), PlaneFromPoints(), PM_Accelerate(), PM_AirMove(), PM_CheckWaterJump(), PM_DeadMove(), PM_FlyMove(), PM_GrappleMove(), PM_NoclipMove(), PM_SlideMove(), PM_WalkMove(), PM_WaterMove(), R_CalcTangentSpace(), R_CalcTangentVectors(), R_InitSkyTexCoords(), R_LerpTag(), R_LoadMD3(), R_RenderPshadowMaps(), R_RenderSunShadowMaps(), R_SetupEntityLighting(), R_SubdividePatchToGrid(), RaySphereIntersections(), RB_SurfaceBeam(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), RE_LoadWorldMap(), S_SpatializeOrigin(), target_laser_think(), Use_Shooter(), weapon_grenadelauncher_fire(), and Weapon_LightningFire().
VectorNormalize2()
vec_t VectorNormalize2 (const vec3_t v, vec3_t out)
Definition at line 824 of file q_math.c.
 {
     float    length, ilength;
     length = v[0] * v[0] + v[1] * v[1] + v[2] * v[2];
     if (length) {
         /* writing it this way allows gcc to recognize that rsqrt can be used */
         ilength = 1 / (float)sqrt(length);
         /* sqrt(length) = length * (1 / sqrt(length)) */
         length *= ilength;
         out[0] = v[0] * ilength;
         out[1] = v[1] * ilength;
         out[2] = v[2] * ilength;
     } else {
         VectorClear(out);
     }
     return length;
 }
References state::out, and VectorClear.
Referenced by AddWindingToConvexHull(), BaseWindingForPlane(), BotWalkInDirection(), CG_Grapple(), CG_ImpactMark(), CG_Missile(), CG_ShotgunPattern(), CheckWinding(), MakeMeshNormals(), PM_SlideMove(), R_MarkFragments(), R_SetupEntityLightingGrid(), RemoveColinearPoints(), RGBAtoNormal(), ShotgunPattern(), and WindingPlane().
VectorNormalizeFast()
static ID_INLINE void VectorNormalizeFast (vec3_t v) static
Definition at line 645 of file q_shared.h.
 {
     float ilength;
     ilength = Q_rsqrt(DotProduct(v, v));
     v[0] *= ilength;
     v[1] *= ilength;
     v[2] *= ilength;
 }
References DotProduct, and Q_rsqrt().
Referenced by R_MarkFragments(), R_MipMapNormalHeight(), RB_AddFlare(), and RB_CalcDeformNormals().
VectorRotate()
void VectorRotate (vec3_t in, vec3_t matrix[3], vec3_t out)
Definition at line 501 of file q_math.c.
 {
     out[0] = DotProduct(in, matrix[0]);
     out[1] = DotProduct(in, matrix[1]);
     out[2] = DotProduct(in, matrix[2]);
 }
References DotProduct, in, and state::out.
Referenced by S_SpatializeOrigin().
Variable Documentation
axisDefault
vec3_t axisDefault[3]
Definition at line 35 of file q_math.c.
Referenced by CG_LaunchExplode(), CG_LaunchGib(), CG_MachineGunEjectBrass(), CG_PlasmaTrail(), and CG_ShotgunEjectBrass().
bytedirs
vec3_t bytedirs[NUMVERTEXNORMALS]
Definition at line 63 of file q_math.c.
Referenced by ByteToDir(), and DirToByte().
colorBlack
vec4_t colorBlack
Definition at line 38 of file q_math.c.
Referenced by ServerOptions_LevelshotDraw(), StartServer_LevelshotDraw(), Text_Paint(), Text_PaintWithCursor(), UI_DrawTextBox(), and UI_SaveConfigMenu_SavenameDraw().
colorBlue
vec4_t colorBlue
Definition at line 41 of file q_math.c.
colorCyan
vec4_t colorCyan
Definition at line 44 of file q_math.c.
colorDkGrey
vec4_t colorDkGrey
Definition at line 48 of file q_math.c.
colorGreen
vec4_t colorGreen
Definition at line 40 of file q_math.c.
colorLtGrey
vec4_t colorLtGrey
Definition at line 46 of file q_math.c.
colorMagenta
vec4_t colorMagenta
Definition at line 43 of file q_math.c.
colorMdGrey
vec4_t colorMdGrey
Definition at line 47 of file q_math.c.
Referenced by Bitmap_Draw(), and Signup_MenuInit().
colorRed
vec4_t colorRed
Definition at line 39 of file q_math.c.
Referenced by Login_MenuInit(), PlayerModel_MenuInit(), Rankings_MenuInit(), RankStatus_MenuInit(), RB_SurfaceBeam(), Signup_MenuInit(), TeamMain_MenuInit(), UI_BotSelectMenu_Init(), UI_Refresh(), and UI_SaveConfigMenu_SavenameDraw().
colorWhite
vec4_t colorWhite
Definition at line 45 of file q_math.c.
Referenced by CG_DrawInformation(), CG_DrawOldScoreboard(), CG_DrawWarmup(), Controls_DrawKeyBinding(), Controls_StatusBar(), FBO_BlitFromTexture(), Menu_Draw(), RB_DrawSun(), RB_InstantQuad(), RE_SetColor(), RE_StretchRaw(), ServerOptions_StatusBar(), UI_DisplayDownloadInfo(), UI_DrawConnectScreen(), UI_DrawPlayer(), and UI_DrawTextBox().
colorYellow
vec4_t colorYellow
Definition at line 42 of file q_math.c.
Referenced by Menu_Draw().
g_color_table
vec4_t g_color_table[8]
Definition at line 50 of file q_math.c.
Referenced by CG_DrawLagometer(), CG_DrawStringExt(), CG_Text_Paint_Limit(), CON_ColorCharToAttrib(), Con_DrawNotify(), Con_DrawSolidConsole(), PlayerSettings_DrawName(), Rankings_DrawText(), SCR_DrawDebugGraph(), SCR_DrawDemoRecording(), SCR_DrawScreenField(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), and UI_DrawString2().
vec3_origin
vec3_t vec3_origin
Definition at line 34 of file q_math.c.
Referenced by AAS_JumpReachRunStart(), AddSkyPolygon(), AnglesToAxis(), AutospriteDeform(), BaseWindingForPlane(), BotCheckSnapshot(), ByteToDir(), CanDamage(), CG_AddPlayerWeapon(), CG_BloodTrail(), CG_ClipMoveToEntities(), CG_DamageFeedback(), CG_EntityEffects(), CG_Grapple(), CG_HasteTrail(), CG_Item(), CG_LightningBolt(), CG_PlayerPowerups(), CG_Portal(), CG_ScanForCrosshairEntity(), CM_AddFacetBevels(), CM_BoxTrace(), CM_DrawDebugSurface(), CM_Trace(), CM_TransformedBoxTrace(), CM_ValidateFacet(), FindIntermissionPoint(), G_TryPushingProxMine(), InitTrigger(), PlayerSettings_DrawPlayer(), PlayerSettings_SetMenuItems(), PM_NoclipMove(), R_GetPortalOrientations(), R_LoadFogs(), R_MirrorViewBySurface(), RB_AddQuadStampExt(), RB_SurfaceSprite(), SelectCTFSpawnPoint(), SelectInitialSpawnPoint(), SV_ClipMoveToEntities(), SV_ClipToEntity(), SV_EntityContact(), SV_PointContents(), SV_Trace(), UI_DrawOpponent(), UI_DrawPlayerModel(), and WindingCenter().