ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/cm_public.h File Reference
cm_public.h File Reference
#include "qfiles.h"
Functions
void CM_LoadMap (const char *name, qboolean clientload, int *checksum)
void CM_ClearMap (void)
clipHandle_t CM_InlineModel (int index)
clipHandle_t CM_TempBoxModel (const vec3_t mins, const vec3_t maxs, int capsule)
void CM_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
int CM_NumClusters (void)
int CM_NumInlineModels (void)
char * CM_EntityString (void)
int CM_PointContents (const vec3_t p, clipHandle_t model)
int CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
void CM_BoxTrace (trace_t *results, const vec3_t start, const vec3_t end, vec3_t mins, vec3_t maxs, clipHandle_t model, int brushmask, int capsule)
void CM_TransformedBoxTrace (trace_t *results, const vec3_t start, const vec3_t end, vec3_t mins, vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles, int capsule)
byte * CM_ClusterPVS (int cluster)
int CM_PointLeafnum (const vec3_t p)
int CM_BoxLeafnums (const vec3_t mins, const vec3_t maxs, int *list, int listsize, int *lastLeaf)
int CM_LeafCluster (int leafnum)
int CM_LeafArea (int leafnum)
void CM_AdjustAreaPortalState (int area1, int area2, qboolean open)
qboolean CM_AreasConnected (int area1, int area2)
int CM_WriteAreaBits (byte *buffer, int area)
void CM_DrawDebugSurface (void(*drawPoly)(int color, int numPoints, float *points))
Function Documentation
CM_AdjustAreaPortalState()
void CM_AdjustAreaPortalState (int area1, int area2, qboolean open)
Definition at line 389 of file cm_test.c.
{
     if ( area1 < 0 || area2 < 0 ) {
         return;
     }
     if ( area1 >= cm.numAreas || area2 >= cm.numAreas ) {
         Com_Error (ERR_DROP, "CM_ChangeAreaPortalState: bad area number");
     }
     if ( open ) {
         cm.areaPortals[ area1 * cm.numAreas + area2 ]++;
         cm.areaPortals[ area2 * cm.numAreas + area1 ]++;
     } else {
         cm.areaPortals[ area1 * cm.numAreas + area2 ]--;
         cm.areaPortals[ area2 * cm.numAreas + area1 ]--;
         if ( cm.areaPortals[ area2 * cm.numAreas + area1 ] < 0 ) {
             Com_Error (ERR_DROP, "CM_AdjustAreaPortalState: negative reference count");
         }
     }
     CM_FloodAreaConnections ();
 }
Referenced by SV_AdjustAreaPortalState().
CM_AreasConnected()
qboolean CM_AreasConnected (int area1, int area2)
Definition at line 418 of file cm_test.c.
{
 #ifndef BSPC
     if ( cm_noAreas->integer ) {
         return qtrue;
     }
 #endif
     if ( area1 < 0 || area2 < 0 ) {
         return qfalse;
     }
     if (area1 >= cm.numAreas || area2 >= cm.numAreas) {
         Com_Error (ERR_DROP, "area >= cm.numAreas");
     }
     if (cm.areas[area1].floodnum == cm.areas[area2].floodnum) {
         return qtrue;
     }
     return qfalse;
 }
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_GameSystemCalls(), and SV_inPVS().
CM_BoxLeafnums()
int CM_BoxLeafnums (const vec3_t mins, const vec3_t maxs, int * list, int listsize, int * lastLeaf)
Definition at line 172 of file cm_test.c.
{
     leafList_t  ll;
     cm.checkcount++;
     VectorCopy( mins, ll.bounds[0] );
     VectorCopy( maxs, ll.bounds[1] );
     ll.count = 0;
     ll.maxcount = listsize;
     ll.list = list;
     ll.storeLeafs = CM_StoreLeafs;
     ll.lastLeaf = 0;
     ll.overflowed = qfalse;
     CM_BoxLeafnums_r( &ll, 0 );
     *lastLeaf = ll.lastLeaf;
     return ll.count;
 }
Referenced by SV_LinkEntity().
CM_BoxTrace()
void CM_BoxTrace (trace_t * results, const vec3_t start, const vec3_t end, vec3_t mins, vec3_t maxs, clipHandle_t model, int brushmask, int capsule)
Definition at line 1366 of file cm_trace.c.
{
     CM_Trace( results, start, end, mins, maxs, model, vec3_origin, brushmask, capsule, NULL );
 }
Referenced by CL_CgameSystemCalls(), and SV_Trace().
CM_ClearMap()
void CM_ClearMap (void)
Definition at line 668 of file cm_load.c.
{
     Com_Memset( &cm, 0, sizeof( cm ) );
     CM_ClearLevelPatches();
 }
Referenced by CL_ClearMemory(), and SV_SpawnServer().
CM_ClusterPVS()
byte* CM_ClusterPVS (int cluster)
Definition at line 316 of file cm_test.c.
{
     if (cluster < 0 || cluster >= cm.numClusters || !cm.vised ) {
         return cm.visibility;
     }
     return cm.visibility + cluster * cm.clusterBytes;
 }
Referenced by CL_InitRef(), SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), and SV_inPVSIgnorePortals().
CM_DrawDebugSurface()
void CM_DrawDebugSurface (void(*)(int color, int numPoints, float *points) drawPoly)
Definition at line 1649 of file cm_patch.c.
{
     static cvar_t   *cv;
 #ifndef BSPC
     static cvar_t   *cv2;
 #endif
     const patchCollide_t    *pc;
     facet_t         *facet;
     winding_t       *w;
     int             i, j, k, n;
     int             curplanenum, planenum, curinward, inward;
     float           plane[4];
     vec3_t mins = {-15, -15, -28}, maxs = {15, 15, 28};
     //vec3_t mins = {0, 0, 0}, maxs = {0, 0, 0};
     vec3_t v1, v2;
 #ifndef BSPC
     if ( !cv2 )
     {
         cv2 = Cvar_Get( "r_debugSurface", "0", 0 );
     }
     if (cv2->integer != 1)
     {
         BotDrawDebugPolygons(drawPoly, cv2->integer);
         return;
     }
 #endif
     if ( !debugPatchCollide ) {
         return;
     }
 #ifndef BSPC
     if ( !cv ) {
         cv = Cvar_Get( "cm_debugSize", "2", 0 );
     }
 #endif
     pc = debugPatchCollide;
     for ( i = 0, facet = pc->facets ; i < pc->numFacets ; i++, facet++ ) {
         for ( k = 0 ; k < facet->numBorders + 1; k++ ) {
             //
             if (k < facet->numBorders) {
                 planenum = facet->borderPlanes[k];
                 inward = facet->borderInward[k];
             }
             else {
                 planenum = facet->surfacePlane;
                 inward = qfalse;
                 //continue;
             }
             Vector4Copy( pc->planes[ planenum ].plane, plane );
             //planenum = facet->surfacePlane;
             if ( inward ) {
                 VectorSubtract( vec3_origin, plane, plane );
                 plane[3] = -plane[3];
             }
             plane[3] += cv->value;
             //*
             for (n = 0; n < 3; n++)
             {
                 if (plane[n] > 0) v1[n] = maxs[n];
                 else v1[n] = mins[n];
             } //end for
             VectorNegate(plane, v2);
             plane[3] += fabs(DotProduct(v1, v2));
             //*/
             w = BaseWindingForPlane( plane,  plane[3] );
             for ( j = 0 ; j < facet->numBorders + 1 && w; j++ ) {
                 //
                 if (j < facet->numBorders) {
                     curplanenum = facet->borderPlanes[j];
                     curinward = facet->borderInward[j];
                 }
                 else {
                     curplanenum = facet->surfacePlane;
                     curinward = qfalse;
                     //continue;
                 }
                 //
                 if (curplanenum == planenum) continue;
                 Vector4Copy( pc->planes[ curplanenum ].plane, plane );
                 if ( !curinward ) {
                     VectorSubtract( vec3_origin, plane, plane );
                     plane[3] = -plane[3];
                 }
         //          if ( !facet->borderNoAdjust[j] ) {
                     plane[3] -= cv->value;
         //          }
                 for (n = 0; n < 3; n++)
                 {
                     if (plane[n] > 0) v1[n] = maxs[n];
                     else v1[n] = mins[n];
                 } //end for
                 VectorNegate(plane, v2);
                 plane[3] -= fabs(DotProduct(v1, v2));
                 ChopWindingInPlace( &w, plane, plane[3], 0.1f );
             }
             if ( w ) {
                 if ( facet == debugFacet ) {
                     drawPoly( 4, w->numpoints, w->p[0] );
                     //Com_Printf("blue facet has %d border planes\n", facet->numBorders);
                 } else {
                     drawPoly( 1, w->numpoints, w->p[0] );
                 }
                 FreeWinding( w );
             }
             else
                 Com_Printf("winding chopped away by border planes\n");
         }
     }
     // draw the debug block
     {
         vec3_t          v[3];
         VectorCopy( debugBlockPoints[0], v[0] );
         VectorCopy( debugBlockPoints[1], v[1] );
         VectorCopy( debugBlockPoints[2], v[2] );
         drawPoly( 2, 3, v[0] );
         VectorCopy( debugBlockPoints[2], v[0] );
         VectorCopy( debugBlockPoints[3], v[1] );
         VectorCopy( debugBlockPoints[0], v[2] );
         drawPoly( 2, 3, v[0] );
     }
 #if 0
     vec3_t          v[4];
     v[0][0] = pc->bounds[1][0];
     v[0][1] = pc->bounds[1][1];
     v[0][2] = pc->bounds[1][2];
     v[1][0] = pc->bounds[1][0];
     v[1][1] = pc->bounds[0][1];
     v[1][2] = pc->bounds[1][2];
     v[2][0] = pc->bounds[0][0];
     v[2][1] = pc->bounds[0][1];
     v[2][2] = pc->bounds[1][2];
     v[3][0] = pc->bounds[0][0];
     v[3][1] = pc->bounds[1][1];
     v[3][2] = pc->bounds[1][2];
     drawPoly( 4, v[0] );
 #endif
 }
Referenced by CL_InitRef().
CM_EntityString()
char* CM_EntityString (void)
Definition at line 718 of file cm_load.c.
{
     return cm.entityString;
 }
Referenced by BotImport_BSPEntityData(), and SV_InitGameVM().
CM_InlineModel()
clipHandle_t CM_InlineModel (int index)
Definition at line 703 of file cm_load.c.
{
     if ( index < 0 || index >= cm.numSubModels ) {
         Com_Error (ERR_DROP, "CM_InlineModel: bad number");
     }
     return index;
 }
Referenced by BotImport_BSPModelMinsMaxsOrigin(), CL_CgameSystemCalls(), SV_ClearWorld(), SV_ClipHandleForEntity(), and SV_SetBrushModel().
CM_LeafArea()
int CM_LeafArea (int leafnum)
Definition at line 729 of file cm_load.c.
{
     if ( leafnum < 0 || leafnum >= cm.numLeafs ) {
         Com_Error (ERR_DROP, "CM_LeafArea: bad number");
     }
     return cm.leafs[leafnum].area;
 }
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), and SV_LinkEntity().
CM_LeafCluster()
int CM_LeafCluster (int leafnum)
Definition at line 722 of file cm_load.c.
{
     if (leafnum < 0 || leafnum >= cm.numLeafs) {
         Com_Error (ERR_DROP, "CM_LeafCluster: bad number");
     }
     return cm.leafs[leafnum].cluster;
 }
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), SV_inPVSIgnorePortals(), and SV_LinkEntity().
CM_LoadMap()
void CM_LoadMap (const char * name, qboolean clientload, int * checksum)
Definition at line 569 of file cm_load.c.
{
     union {
         int             *i;
         void            *v;
     } buf;
     int             i;
     dheader_t       header;
     int             length;
     static unsigned last_checksum;
     if ( !name || !name[0] ) {
         Com_Error( ERR_DROP, "CM_LoadMap: NULL name" );
     }
 #ifndef BSPC
     cm_noAreas = Cvar_Get ("cm_noAreas", "0", CVAR_CHEAT);
     cm_noCurves = Cvar_Get ("cm_noCurves", "0", CVAR_CHEAT);
     cm_playerCurveClip = Cvar_Get ("cm_playerCurveClip", "1", CVAR_ARCHIVE|CVAR_CHEAT );
 #endif
     Com_DPrintf( "CM_LoadMap( %s, %i )\n", name, clientload );
     if ( !strcmp( cm.name, name ) && clientload ) {
         *checksum = last_checksum;
         return;
     }
     // free old stuff
     Com_Memset( &cm, 0, sizeof( cm ) );
     CM_ClearLevelPatches();
     if ( !name[0] ) {
         cm.numLeafs = 1;
         cm.numClusters = 1;
         cm.numAreas = 1;
         cm.cmodels = Hunk_Alloc( sizeof( *cm.cmodels ), h_high );
         *checksum = 0;
         return;
     }
     //
     // load the file
     //
 #ifndef BSPC
     length = FS_ReadFile( name, &buf.v );
 #else
     length = LoadQuakeFile((quakefile_t *) name, &buf.v);
 #endif
     if ( !buf.i ) {
         Com_Error (ERR_DROP, "Couldn't load %s", name);
     }
     last_checksum = LittleLong (Com_BlockChecksum (buf.i, length));
     *checksum = last_checksum;
     header = *(dheader_t *)buf.i;
     for (i=0 ; i<sizeof(dheader_t)/4 ; i++) {
         ((int *)&header)[i] = LittleLong ( ((int *)&header)[i]);
     }
     if ( header.version != BSP_VERSION ) {
         Com_Error (ERR_DROP, "CM_LoadMap: %s has wrong version number (%i should be %i)"
         , name, header.version, BSP_VERSION );
     }
     cmod_base = (byte *)buf.i;
     // load into heap
     CMod_LoadShaders( &header.lumps[LUMP_SHADERS] );
     CMod_LoadLeafs (&header.lumps[LUMP_LEAFS]);
     CMod_LoadLeafBrushes (&header.lumps[LUMP_LEAFBRUSHES]);
     CMod_LoadLeafSurfaces (&header.lumps[LUMP_LEAFSURFACES]);
     CMod_LoadPlanes (&header.lumps[LUMP_PLANES]);
     CMod_LoadBrushSides (&header.lumps[LUMP_BRUSHSIDES]);
     CMod_LoadBrushes (&header.lumps[LUMP_BRUSHES]);
     CMod_LoadSubmodels (&header.lumps[LUMP_MODELS]);
     CMod_LoadNodes (&header.lumps[LUMP_NODES]);
     CMod_LoadEntityString (&header.lumps[LUMP_ENTITIES]);
     CMod_LoadVisibility( &header.lumps[LUMP_VISIBILITY] );
     CMod_LoadPatches( &header.lumps[LUMP_SURFACES], &header.lumps[LUMP_DRAWVERTS] );
     // we are NOT freeing the file, because it is cached for the ref
     FS_FreeFile (buf.v);
     CM_InitBoxHull ();
     CM_FloodAreaConnections ();
     // allow this to be cached if it is loaded by the server
     if ( !clientload ) {
         Q_strncpyz( cm.name, name, sizeof( cm.name ) );
     }
 }
Referenced by CL_CM_LoadMap(), and SV_SpawnServer().
CM_ModelBounds()
void CM_ModelBounds (clipHandle_t model, vec3_t mins, vec3_t maxs)
Definition at line 834 of file cm_load.c.
{
     cmodel_t    *cmod;
     cmod = CM_ClipHandleToModel( model );
     VectorCopy( cmod->mins, mins );
     VectorCopy( cmod->maxs, maxs );
 }
Referenced by BotImport_BSPModelMinsMaxsOrigin(), CM_TestBoundingBoxInCapsule(), CM_TestCapsuleInCapsule(), CM_TraceBoundingBoxThroughCapsule(), CM_TraceCapsuleThroughCapsule(), SV_ClearWorld(), and SV_SetBrushModel().
CM_NumClusters()
int CM_NumClusters (void)
Definition at line 710 of file cm_load.c.
{
     return cm.numClusters;
 }
CM_NumInlineModels()
int CM_NumInlineModels (void)
Definition at line 714 of file cm_load.c.
{
     return cm.numSubModels;
 }
Referenced by CL_CgameSystemCalls().
CM_PointContents()
int CM_PointContents (const vec3_t p, clipHandle_t model)
Definition at line 226 of file cm_test.c.
{
     int         leafnum;
     int         i, k;
     int         brushnum;
     cLeaf_t     *leaf;
     cbrush_t    *b;
     int         contents;
     float       d;
     cmodel_t    *clipm;
     if (!cm.numNodes) { // map not loaded
         return 0;
     }
     if ( model ) {
         clipm = CM_ClipHandleToModel( model );
         leaf = &clipm->leaf;
     } else {
         leafnum = CM_PointLeafnum_r (p, 0);
         leaf = &cm.leafs[leafnum];
     }
     contents = 0;
     for (k=0 ; k<leaf->numLeafBrushes ; k++) {
         brushnum = cm.leafbrushes[leaf->firstLeafBrush+k];
         b = &cm.brushes[brushnum];
         if ( !CM_BoundsIntersectPoint( b->bounds[0], b->bounds[1], p ) ) {
             continue;
         }
         // see if the point is in the brush
         for ( i = 0 ; i < b->numsides ; i++ ) {
             d = DotProduct( p, b->sides[i].plane->normal );
 // FIXME test for Cash
 //          if ( d >= b->sides[i].plane->dist ) {
             if ( d > b->sides[i].plane->dist ) {
                 break;
             }
         }
         if ( i == b->numsides ) {
             contents |= b->contents;
         }
     }
     return contents;
 }
Referenced by CL_CgameSystemCalls(), CM_TransformedPointContents(), and SV_PointContents().
CM_PointLeafnum()
int CM_PointLeafnum (const vec3_t p)
Definition at line 56 of file cm_test.c.
{
     if ( !cm.numNodes ) {   // map not loaded
         return 0;
     }
     return CM_PointLeafnum_r (p, 0);
 }
Referenced by SV_AddEntitiesVisibleFromPoint(), SV_inPVS(), and SV_inPVSIgnorePortals().
CM_TempBoxModel()
clipHandle_t CM_TempBoxModel (const vec3_t mins, const vec3_t maxs, int capsule)
Definition at line 801 of file cm_load.c.
{
     VectorCopy( mins, box_model.mins );
     VectorCopy( maxs, box_model.maxs );
     if ( capsule ) {
         return CAPSULE_MODEL_HANDLE;
     }
     box_planes[0].dist = maxs[0];
     box_planes[1].dist = -maxs[0];
     box_planes[2].dist = mins[0];
     box_planes[3].dist = -mins[0];
     box_planes[4].dist = maxs[1];
     box_planes[5].dist = -maxs[1];
     box_planes[6].dist = mins[1];
     box_planes[7].dist = -mins[1];
     box_planes[8].dist = maxs[2];
     box_planes[9].dist = -maxs[2];
     box_planes[10].dist = mins[2];
     box_planes[11].dist = -mins[2];
     VectorCopy( mins, box_brush->bounds[0] );
     VectorCopy( maxs, box_brush->bounds[1] );
     return BOX_MODEL_HANDLE;
 }
Referenced by CL_CgameSystemCalls(), CM_TestBoundingBoxInCapsule(), CM_TraceBoundingBoxThroughCapsule(), and SV_ClipHandleForEntity().
CM_TransformedBoxTrace()
void CM_TransformedBoxTrace (trace_t * results, const vec3_t start, const vec3_t end, vec3_t mins, vec3_t maxs, clipHandle_t model, int brushmask, const vec3_t origin, const vec3_t angles, int capsule)
Definition at line 1380 of file cm_trace.c.
{
     trace_t     trace;
     vec3_t      start_l, end_l;
     qboolean    rotated;
     vec3_t      offset;
     vec3_t      symetricSize[2];
     vec3_t      matrix[3], transpose[3];
     int         i;
     float       halfwidth;
     float       halfheight;
     float       t;
     sphere_t    sphere;
     if ( !mins ) {
         mins = vec3_origin;
     }
     if ( !maxs ) {
         maxs = vec3_origin;
     }
     // adjust so that mins and maxs are always symetric, which
     // avoids some complications with plane expanding of rotated
     // bmodels
     for ( i = 0 ; i < 3 ; i++ ) {
         offset[i] = ( mins[i] + maxs[i] ) * 0.5;
         symetricSize[0][i] = mins[i] - offset[i];
         symetricSize[1][i] = maxs[i] - offset[i];
         start_l[i] = start[i] + offset[i];
         end_l[i] = end[i] + offset[i];
     }
     // subtract origin offset
     VectorSubtract( start_l, origin, start_l );
     VectorSubtract( end_l, origin, end_l );
     // rotate start and end into the models frame of reference
     if ( model != BOX_MODEL_HANDLE &&
         (angles[0] || angles[1] || angles[2]) ) {
         rotated = qtrue;
     } else {
         rotated = qfalse;
     }
     halfwidth = symetricSize[ 1 ][ 0 ];
     halfheight = symetricSize[ 1 ][ 2 ];
     sphere.use = capsule;
     sphere.radius = ( halfwidth > halfheight ) ? halfheight : halfwidth;
     sphere.halfheight = halfheight;
     t = halfheight - sphere.radius;
     if (rotated) {
         // rotation on trace line (start-end) instead of rotating the bmodel
         // NOTE: This is still incorrect for bounding boxes because the actual bounding
         //       box that is swept through the model is not rotated. We cannot rotate
         //       the bounding box or the bmodel because that would make all the brush
         //       bevels invalid.
         //       However this is correct for capsules since a capsule itself is rotated too.
         CreateRotationMatrix(angles, matrix);
         RotatePoint(start_l, matrix);
         RotatePoint(end_l, matrix);
         // rotated sphere offset for capsule
         sphere.offset[0] = matrix[0][ 2 ] * t;
         sphere.offset[1] = -matrix[1][ 2 ] * t;
         sphere.offset[2] = matrix[2][ 2 ] * t;
     }
     else {
         VectorSet( sphere.offset, 0, 0, t );
     }
     // sweep the box through the model
     CM_Trace( &trace, start_l, end_l, symetricSize[0], symetricSize[1], model, origin, brushmask, capsule, &sphere );
     // if the bmodel was rotated and there was a collision
     if ( rotated && trace.fraction != 1.0 ) {
         // rotation of bmodel collision plane
         TransposeMatrix(matrix, transpose);
         RotatePoint(trace.plane.normal, transpose);
     }
     // re-calculate the end position of the trace because the trace.endpos
     // calculated by CM_Trace could be rotated and have an offset
     trace.endpos[0] = start[0] + trace.fraction * (end[0] - start[0]);
     trace.endpos[1] = start[1] + trace.fraction * (end[1] - start[1]);
     trace.endpos[2] = start[2] + trace.fraction * (end[2] - start[2]);
     *results = trace;
 }
Referenced by CL_CgameSystemCalls(), SV_ClipMoveToEntities(), SV_ClipToEntity(), and SV_EntityContact().
CM_TransformedPointContents()
int CM_TransformedPointContents (const vec3_t p, clipHandle_t model, const vec3_t origin, const vec3_t angles)
Definition at line 283 of file cm_test.c.
{
     vec3_t      p_l;
     vec3_t      temp;
     vec3_t      forward, right, up;
     // subtract origin offset
     VectorSubtract (p, origin, p_l);
     // rotate start and end into the models frame of reference
     if ( model != BOX_MODEL_HANDLE &&
     (angles[0] || angles[1] || angles[2]) )
     {
         AngleVectors (angles, forward, right, up);
         VectorCopy (p_l, temp);
         p_l[0] = DotProduct (temp, forward);
         p_l[1] = -DotProduct (temp, right);
         p_l[2] = DotProduct (temp, up);
     }
     return CM_PointContents( p_l, model );
 }
Referenced by CL_CgameSystemCalls(), and SV_PointContents().
CM_WriteAreaBits()
int CM_WriteAreaBits (byte * buffer, int area)
Definition at line 454 of file cm_test.c.
 {
     int     i;
     int     floodnum;
     int     bytes;
     bytes = (cm.numAreas+7)>>3;
 #ifndef BSPC
     if (cm_noAreas->integer || area == -1)
 #else
     if ( area == -1)
 #endif
     {   // for debugging, send everything
         Com_Memset (buffer, 255, bytes);
     }
     else
     {
         floodnum = cm.areas[area].floodnum;
         for (i=0 ; i<cm.numAreas ; i++)
         {
             if (cm.areas[i].floodnum == floodnum || area == -1)
                 buffer[i>>3] |= 1<<(i&7);
         }
     }
     return bytes;
 }
Referenced by SV_AddEntitiesVisibleFromPoint().