ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_syscalls.c File Reference
g_syscalls.c File Reference
#include "g_local.h"
Functions
static intptr_t (QDECL *syscall)(intptr_t arg
Traps's function point whose value is assigned at run time by dllEntry().
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
int PASSFLOAT (float x)
void trap_Print (const char *text)
trap_Print prints the string pointed to by fmt to the Q3 Console.
void trap_Error (const char *text)
This is very similar to the trap_Print function with the exception that this will halt execution of the module it is called from.
int trap_Milliseconds (void)
Returns the number of milliseconds that have elapsed since Quake 3 was executed.
int trap_Argc (void)
Whenever a client issues a console command it can have arguments passed with it.
void trap_Argv (int n, char *buffer, int bufferLength)
This will fill the buffer pointed to by buffer with an argument to a client command where n is the argument to return.
int trap_FS_FOpenFile (const char *qpath, fileHandle_t *f, fsMode_t mode)
This opens a file specified by the string qpath and allocates a fileHandle_t (just a typedef int) to that file.
void trap_FS_Read (void *buffer, int len, fileHandle_t f)
This reads len bytes of data from the file specified by f and fills buffer with it.
void trap_FS_Write (const void *buffer, int len, fileHandle_t f)
This writes len bytes of data from buffer to the file specified by f.
void trap_FS_FCloseFile (fileHandle_t f)
Closes the file specified by f.
int trap_FS_GetFileList (const char *path, const char *extension, char *listbuf, int bufsize)
This fills listbuf with a NULL delimited list of all the files in the directory specified by path ending in extension.
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
void trap_SendConsoleCommand (int exec_when, const char *text)
This call adds a command to the command buffer i.e.
void trap_Cvar_Register (vmCvar_t *cvar, const char *var_name, const char *value, int flags)
This function is used to create a new vmCvar.
void trap_Cvar_Update (vmCvar_t *cvar)
This function first parses out the name of the vmCvar and then searches for the corresponding database entry.
void trap_Cvar_Set (const char *var_name, const char *value)
This function searchs for the name of the vmCvar and stores the value into both the float and integer fields of the corresponding vmCvar entry.
int trap_Cvar_VariableIntegerValue (const char *var_name)
This function returns the integer value of var_name that is currently stored in the "master copy".
void trap_Cvar_VariableStringBuffer (const char *var_name, char *buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
void trap_LocateGameData (gentity_t *gEnts, int numGEntities, int sizeofGEntity_t, playerState_t *clients, int sizeofGClient)
It would be very unusual for a mod programmer to want to call this - especially with parameters other than those outlined above.
void trap_DropClient (int clientNum, const char *reason)
This provides a mechanism to unconditionally drop a client from a server via their clientNum (ent->client->ps.clientNum).
void trap_SendServerCommand (int clientNum, const char *text)
This has the same effect as typing a command in a clients console for evaluation by the server.
void trap_SetConfigstring (int num, const char *string)
The Q3 Engine provides a mechanism for communicating data from the server to the client via config strings.
void trap_GetConfigstring (int num, char *buffer, int bufferSize)
This is a server side callback used to get the value of a config string.
void trap_GetUserinfo (int num, char *buffer, int bufferSize)
Each client has a "user info" string which is a backslash delimited key/value pair for the various options the user can set.
void trap_SetUserinfo (int num, const char *buffer)
This does the opposite to trap_GetUserinfo and sets a userinfo string for a user.
void trap_GetServerinfo (char *buffer, int bufferSize)
The "server info" string is a backslash delimited list of server variables such as g_gametype and mapname.
void trap_SetBrushModel (gentity_t *ent, const char *name)
This function does several special things to an entity which should not be done any other way.
void trap_Trace (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
This function is used to trace from one position to another in the BSP tree and store the results in a trace_t structure.
void trap_TraceCapsule (trace_t *results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
int trap_PointContents (const vec3_t point, int passEntityNum)
This trap call returns the CONTENTS_* of a specific point in space - it is commonly used to avoid spawning items in CONTENTS_NODROP areas.
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
void trap_AdjustAreaPortalState (gentity_t *ent, qboolean open)
Adjusts the state of a portal connecting two areas.
qboolean trap_AreasConnected (int area1, int area2)
This functions tests whether or not the areas (presumably leaf nodes of the bsp tree) are adjacent physically.
void trap_LinkEntity (gentity_t *ent)
When an entity is "linked" it is subject to all evaluations that the world performs on it.
void trap_UnlinkEntity (gentity_t *ent)
When an entity is "unlinked" from the world it remains in memory, but ceases to exist from the point of view of the world.
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int *list, int maxcount)
This fills an array of ints with the entity numbers (ent->s.number) of all the entities currently within the cuboid defined by mins and maxs.
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t *ent)
If the entity pointed to by ent is physically within the bounds specified by mins and maxs then this function returns qtrue.
int trap_BotAllocateClient (void)
Allocates a free client slot and returns the client number.
void trap_BotFreeClient (int clientNum)
void trap_GetUsercmd (int clientNum, usercmd_t *cmd)
This function will retrieve the usercmd_t generated by the client portion of the Q3 binary and place it in what it pointed to by cmd.
qboolean trap_GetEntityToken (char *buffer, int bufferSize)
This call fills the buffer pointed to by buffer with all the key/value pairs of every map entity.
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t *points)
Creates a solid coloured permanent polygon in the renderer (and world) based on the given array of vertices/points.
void trap_DebugPolygonDelete (int id)
Removes a polygon that was previously created via trap_DebugPolygonCreate.
int trap_RealTime (qtime_t *qtime)
Returns current system time and date at server.
void trap_SnapVector (float *v)
This simply removes the fractional part of each axis of v - a form of "snap to grid".
int trap_BotLibSetup (void)
int trap_BotLibShutdown (void)
int trap_BotLibVarSet (char *var_name, char *value)
int trap_BotLibVarGet (char *var_name, char *value, int size)
int trap_BotLibDefine (char *string)
int trap_BotLibStartFrame (float time)
int trap_BotLibLoadMap (const char *mapname)
int trap_BotLibUpdateEntity (int ent, void *bue)
int trap_BotLibTest (int parm0, char *parm1, vec3_t parm2, vec3_t parm3)
int trap_BotGetSnapshotEntity (int clientNum, int sequence)
int trap_BotGetServerCommand (int clientNum, char *message, int size)
void trap_BotUserCommand (int clientNum, usercmd_t *ucmd)
void trap_AAS_EntityInfo (int entnum, void *info)
int trap_AAS_Initialized (void)
void trap_AAS_PresenceTypeBoundingBox (int presencetype, vec3_t mins, vec3_t maxs)
float trap_AAS_Time (void)
int trap_AAS_PointAreaNum (vec3_t point)
int trap_AAS_PointReachabilityAreaIndex (vec3_t point)
int trap_AAS_TraceAreas (vec3_t start, vec3_t end, int *areas, vec3_t *points, int maxareas)
int trap_AAS_BBoxAreas (vec3_t absmins, vec3_t absmaxs, int *areas, int maxareas)
int trap_AAS_AreaInfo (int areanum, void *info)
int trap_AAS_PointContents (vec3_t point)
int trap_AAS_NextBSPEntity (int ent)
int trap_AAS_ValueForBSPEpairKey (int ent, char *key, char *value, int size)
int trap_AAS_VectorForBSPEpairKey (int ent, char *key, vec3_t v)
int trap_AAS_FloatForBSPEpairKey (int ent, char *key, float *value)
int trap_AAS_IntForBSPEpairKey (int ent, char *key, int *value)
int trap_AAS_AreaReachability (int areanum)
int trap_AAS_AreaTravelTimeToGoalArea (int areanum, vec3_t origin, int goalareanum, int travelflags)
int trap_AAS_EnableRoutingArea (int areanum, int enable)
int trap_AAS_PredictRoute (void *route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
int trap_AAS_AlternativeRouteGoals (vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, void *altroutegoals, int maxaltroutegoals, int type)
int trap_AAS_Swimming (vec3_t origin)
int trap_AAS_PredictClientMovement (void *move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
void trap_EA_Say (int client, char *str)
void trap_EA_SayTeam (int client, char *str)
void trap_EA_Command (int client, char *command)
void trap_EA_Action (int client, int action)
void trap_EA_Gesture (int client)
void trap_EA_Talk (int client)
void trap_EA_Attack (int client)
void trap_EA_Use (int client)
void trap_EA_Respawn (int client)
void trap_EA_Crouch (int client)
void trap_EA_MoveUp (int client)
void trap_EA_MoveDown (int client)
void trap_EA_MoveForward (int client)
void trap_EA_MoveBack (int client)
void trap_EA_MoveLeft (int client)
void trap_EA_MoveRight (int client)
void trap_EA_SelectWeapon (int client, int weapon)
void trap_EA_Jump (int client)
void trap_EA_DelayedJump (int client)
void trap_EA_Move (int client, vec3_t dir, float speed)
void trap_EA_View (int client, vec3_t viewangles)
void trap_EA_EndRegular (int client, float thinktime)
void trap_EA_GetInput (int client, float thinktime, void *input)
void trap_EA_ResetInput (int client)
int trap_BotLoadCharacter (char *charfile, float skill)
void trap_BotFreeCharacter (int character)
float trap_Characteristic_Float (int character, int index)
float trap_Characteristic_BFloat (int character, int index, float min, float max)
int trap_Characteristic_Integer (int character, int index)
int trap_Characteristic_BInteger (int character, int index, int min, int max)
void trap_Characteristic_String (int character, int index, char *buf, int size)
int trap_BotAllocChatState (void)
void trap_BotFreeChatState (int handle)
void trap_BotQueueConsoleMessage (int chatstate, int type, char *message)
void trap_BotRemoveConsoleMessage (int chatstate, int handle)
int trap_BotNextConsoleMessage (int chatstate, void *cm)
int trap_BotNumConsoleMessages (int chatstate)
void trap_BotInitialChat (int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int trap_BotNumInitialChats (int chatstate, char *type)
int trap_BotReplyChat (int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int trap_BotChatLength (int chatstate)
void trap_BotEnterChat (int chatstate, int client, int sendto)
void trap_BotGetChatMessage (int chatstate, char *buf, int size)
int trap_StringContains (char *str1, char *str2, int casesensitive)
int trap_BotFindMatch (char *str, void *match, unsigned long int context)
void trap_BotMatchVariable (void *match, int variable, char *buf, int size)
void trap_UnifyWhiteSpaces (char *string)
void trap_BotReplaceSynonyms (char *string, unsigned long int context)
int trap_BotLoadChatFile (int chatstate, char *chatfile, char *chatname)
void trap_BotSetChatGender (int chatstate, int gender)
void trap_BotSetChatName (int chatstate, char *name, int client)
void trap_BotResetGoalState (int goalstate)
void trap_BotResetAvoidGoals (int goalstate)
void trap_BotRemoveFromAvoidGoals (int goalstate, int number)
void trap_BotPushGoal (int goalstate, void *goal)
void trap_BotPopGoal (int goalstate)
void trap_BotEmptyGoalStack (int goalstate)
void trap_BotDumpAvoidGoals (int goalstate)
void trap_BotDumpGoalStack (int goalstate)
void trap_BotGoalName (int number, char *name, int size)
int trap_BotGetTopGoal (int goalstate, void *goal)
int trap_BotGetSecondGoal (int goalstate, void *goal)
int trap_BotChooseLTGItem (int goalstate, vec3_t origin, int *inventory, int travelflags)
int trap_BotChooseNBGItem (int goalstate, vec3_t origin, int *inventory, int travelflags, void *ltg, float maxtime)
int trap_BotTouchingGoal (vec3_t origin, void *goal)
int trap_BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, void *goal)
int trap_BotGetLevelItemGoal (int index, char *classname, void *goal)
int trap_BotGetNextCampSpotGoal (int num, void *goal)
int trap_BotGetMapLocationGoal (char *name, void *goal)
float trap_BotAvoidGoalTime (int goalstate, int number)
void trap_BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
void trap_BotInitLevelItems (void)
void trap_BotUpdateEntityItems (void)
int trap_BotLoadItemWeights (int goalstate, char *filename)
void trap_BotFreeItemWeights (int goalstate)
void trap_BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
void trap_BotSaveGoalFuzzyLogic (int goalstate, char *filename)
void trap_BotMutateGoalFuzzyLogic (int goalstate, float range)
int trap_BotAllocGoalState (int state)
void trap_BotFreeGoalState (int handle)
void trap_BotResetMoveState (int movestate)
void trap_BotAddAvoidSpot (int movestate, vec3_t origin, float radius, int type)
void trap_BotMoveToGoal (void *result, int movestate, void *goal, int travelflags)
int trap_BotMoveInDirection (int movestate, vec3_t dir, float speed, int type)
void trap_BotResetAvoidReach (int movestate)
void trap_BotResetLastAvoidReach (int movestate)
int trap_BotReachabilityArea (vec3_t origin, int testground)
int trap_BotMovementViewTarget (int movestate, void *goal, int travelflags, float lookahead, vec3_t target)
int trap_BotPredictVisiblePosition (vec3_t origin, int areanum, void *goal, int travelflags, vec3_t target)
int trap_BotAllocMoveState (void)
void trap_BotFreeMoveState (int handle)
void trap_BotInitMoveState (int handle, void *initmove)
int trap_BotChooseBestFightWeapon (int weaponstate, int *inventory)
void trap_BotGetWeaponInfo (int weaponstate, int weapon, void *weaponinfo)
int trap_BotLoadWeaponWeights (int weaponstate, char *filename)
int trap_BotAllocWeaponState (void)
void trap_BotFreeWeaponState (int weaponstate)
void trap_BotResetWeaponState (int weaponstate)
int trap_GeneticParentsAndChildSelection (int numranks, float *ranks, int *parent1, int *parent2, int *child)
int trap_PC_LoadSource (const char *filename)
int trap_PC_FreeSource (int handle)
int trap_PC_ReadToken (int handle, pc_token_t *pc_token)
int trap_PC_SourceFileAndLine (int handle, char *filename, int *line)
Function Documentation
dllEntry()
static Q_EXPORT void dllEntry (intptr_t(QDECL *syscallptr)(intptr_t arg,...))
Definition at line 34 of file g_syscalls.c.
 {
     syscall = syscallptr;
 }
intptr_t()
static intptr_t (QDECL * syscall) static
Traps's function point whose value is assigned at run time by dllEntry().
PASSFLOAT()
int PASSFLOAT (float x)
Definition at line 39 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.f = x;
     return fi.i;
 }
References floatint_t::f, and floatint_t::i.
Referenced by trap_AAS_PredictClientMovement(), trap_BotAddAvoidSpot(), trap_BotChooseNBGItem(), trap_BotLibStartFrame(), trap_BotLoadCharacter(), trap_BotMoveInDirection(), trap_BotMovementViewTarget(), trap_BotMutateGoalFuzzyLogic(), trap_BotSetAvoidGoalTime(), trap_Characteristic_BFloat(), trap_EA_EndRegular(), trap_EA_GetInput(), and trap_EA_Move().
trap_AAS_AlternativeRouteGoals()
int trap_AAS_AlternativeRouteGoals (vec3_t start, int startareanum, vec3_t goal, int goalareanum, int travelflags, void * altroutegoals, int maxaltroutegoals, int type)
Definition at line 869 of file g_syscalls.c.
References BOTLIB_AAS_ALTERNATIVE_ROUTE_GOAL.
Referenced by BotSetupAlternativeRouteGoals().
trap_AAS_AreaInfo()
int trap_AAS_AreaInfo (int areanum, void * info)
Definition at line 811 of file g_syscalls.c.
References BOTLIB_AAS_AREA_INFO.
Referenced by BotGetActivateGoal(), and BotTestAAS().
trap_AAS_AreaReachability()
int trap_AAS_AreaReachability (int areanum)
Definition at line 846 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_AREA_REACHABILITY, areanum);
 }
References BOTLIB_AAS_AREA_REACHABILITY.
Referenced by AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), BotAIBlocked(), BotFuncButtonActivateGoal(), BotGetActivateGoal(), BotGetLongTermGoal(), BotLongTermGoal(), and BotTriggerMultipleActivateGoal().
trap_AAS_AreaTravelTimeToGoalArea()
int trap_AAS_AreaTravelTimeToGoalArea (int areanum, vec3_t origin, int goalareanum, int travelflags)
Definition at line 851 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_AREA_TRAVEL_TIME_TO_GOAL_AREA, areanum, origin, goalareanum, travelflags);
 }
References BOTLIB_AAS_AREA_TRAVEL_TIME_TO_GOAL_AREA.
Referenced by BotAlternateRoute(), BotClientTravelTimeToGoal(), BotGetActivateGoal(), BotGetLongTermGoal(), BotMatch_WhereAreYou(), BotNearbyGoal(), BotSetLastOrderedTask(), and BotWantsToCamp().
trap_AAS_BBoxAreas()
int trap_AAS_BBoxAreas (vec3_t absmins, vec3_t absmaxs, int * areas, int maxareas)
Definition at line 806 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_BBOX_AREAS, absmins, absmaxs, areas, maxareas);
 }
References BOTLIB_AAS_BBOX_AREAS.
Referenced by BotGetActivateGoal().
trap_AAS_EnableRoutingArea()
int trap_AAS_EnableRoutingArea (int areanum, int enable)
Definition at line 856 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_ENABLE_ROUTING_AREA, areanum, enable);
 }
References BOTLIB_AAS_ENABLE_ROUTING_AREA.
Referenced by BotEnableActivateGoalAreas().
trap_AAS_EntityInfo()
void trap_AAS_EntityInfo (int entnum, void * info)
Definition at line 769 of file g_syscalls.c.
References BOTLIB_AAS_ENTITY_INFO.
Referenced by BotEntityInfo().
trap_AAS_FloatForBSPEpairKey()
int trap_AAS_FloatForBSPEpairKey (int ent, char * key, float * value)
Definition at line 836 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_FLOAT_FOR_BSP_EPAIR_KEY, ent, key, value);
 }
References BOTLIB_AAS_FLOAT_FOR_BSP_EPAIR_KEY.
Referenced by BotFuncButtonActivateGoal(), and BotGetActivateGoal().
trap_AAS_Initialized()
int trap_AAS_Initialized (void)
Definition at line 774 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_INITIALIZED);
 }
References BOTLIB_AAS_INITIALIZED.
Referenced by BotAISetupClient(), BotAIStartFrame(), and BotTestAAS().
trap_AAS_IntForBSPEpairKey()
int trap_AAS_IntForBSPEpairKey (int ent, char * key, int * value)
Definition at line 841 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_INT_FOR_BSP_EPAIR_KEY, ent, key, value);
 }
References BOTLIB_AAS_INT_FOR_BSP_EPAIR_KEY.
Referenced by BotGetActivateGoal().
trap_AAS_NextBSPEntity()
int trap_AAS_NextBSPEntity (int ent)
Definition at line 821 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_NEXT_BSP_ENTITY, ent);
 }
References BOTLIB_AAS_NEXT_BSP_ENTITY.
Referenced by BotGetActivateGoal(), BotGoalForBSPEntity(), and BotSetupDeathmatchAI().
trap_AAS_PointAreaNum()
int trap_AAS_PointAreaNum (vec3_t point)
Definition at line 791 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_POINT_AREA_NUM, point);
 }
References BOTLIB_AAS_POINT_AREA_NUM.
Referenced by BotPointAreaNum().
trap_AAS_PointContents()
int trap_AAS_PointContents (vec3_t point)
Definition at line 816 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_POINT_CONTENTS, point);
 }
References BOTLIB_AAS_POINT_CONTENTS.
Referenced by BotCheckAir(), BotEntityVisible(), BotGoForAir(), and BotInLavaOrSlime().
trap_AAS_PointReachabilityAreaIndex()
int trap_AAS_PointReachabilityAreaIndex (vec3_t point)
Definition at line 796 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_POINT_REACHABILITY_AREA_INDEX, point);
 }
References BOTLIB_AAS_POINT_REACHABILITY_AREA_INDEX.
trap_AAS_PredictClientMovement()
int trap_AAS_PredictClientMovement (void * move, int entnum, vec3_t origin, int presencetype, int onground, vec3_t velocity, vec3_t cmdmove, int cmdframes, int maxframes, float frametime, int stopevent, int stopareanum, int visualize)
Definition at line 881 of file g_syscalls.c.
References BOTLIB_AAS_PREDICT_CLIENT_MOVEMENT, and PASSFLOAT().
Referenced by BotAimAtEnemy().
trap_AAS_PredictRoute()
int trap_AAS_PredictRoute (void * route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
Definition at line 861 of file g_syscalls.c.
References BOTLIB_AAS_PREDICT_ROUTE.
Referenced by BotAIPredictObstacles().
trap_AAS_PresenceTypeBoundingBox()
void trap_AAS_PresenceTypeBoundingBox (int presencetype, vec3_t mins, vec3_t maxs)
Definition at line 779 of file g_syscalls.c.
 {
     syscall(BOTLIB_AAS_PRESENCE_TYPE_BOUNDING_BOX, presencetype, mins, maxs);
 }
References BOTLIB_AAS_PRESENCE_TYPE_BOUNDING_BOX.
Referenced by BotFuncButtonActivateGoal(), and BotValidChatPosition().
trap_AAS_Swimming()
int trap_AAS_Swimming (vec3_t origin)
Definition at line 876 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_SWIMMING, origin);
 }
References BOTLIB_AAS_SWIMMING.
Referenced by BotGetLongTermGoal(), and BotReachedGoal().
trap_AAS_Time()
float trap_AAS_Time (void)
Definition at line 784 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AAS_TIME);
     return fi.f;
 }
References BOTLIB_AAS_TIME, floatint_t::f, and floatint_t::i.
Referenced by BotAIStartFrame().
trap_AAS_TraceAreas()
int trap_AAS_TraceAreas (vec3_t start, vec3_t end, int * areas, vec3_t * points, int maxareas)
Definition at line 801 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_TRACE_AREAS, start, end, areas, points, maxareas);
 }
References BOTLIB_AAS_TRACE_AREAS.
Referenced by BotFuncButtonActivateGoal(), BotGoalForBSPEntity(), BotPointAreaNum(), and BotTriggerMultipleActivateGoal().
trap_AAS_ValueForBSPEpairKey()
int trap_AAS_ValueForBSPEpairKey (int ent, char * key, char * value, int size)
Definition at line 826 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_VALUE_FOR_BSP_EPAIR_KEY, ent, key, value, size);
 }
References BOTLIB_AAS_VALUE_FOR_BSP_EPAIR_KEY.
Referenced by BotFuncButtonActivateGoal(), BotFuncDoorActivateGoal(), BotGetActivateGoal(), BotGoalForBSPEntity(), BotPrintActivateGoalInfo(), BotSetupDeathmatchAI(), and BotTriggerMultipleActivateGoal().
trap_AAS_VectorForBSPEpairKey()
int trap_AAS_VectorForBSPEpairKey (int ent, char * key, vec3_t v)
Definition at line 831 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AAS_VECTOR_FOR_BSP_EPAIR_KEY, ent, key, v);
 }
References BOTLIB_AAS_VECTOR_FOR_BSP_EPAIR_KEY.
Referenced by BotGetActivateGoal(), and BotGoalForBSPEntity().
trap_AdjustAreaPortalState()
void trap_AdjustAreaPortalState (gentity_t * ent, qboolean open)
Adjusts the state of a portal connecting two areas.
Set "open" to true to allow visibility through the portal and false to block visibility. This is normally used to adjust visibility when opening and closing doors. When the door is open; "open" is set true and entities are visible through the door, when the door is closed; "open" is set false and trap_InPVS will not see entities through the door. See Use_BinaryMover in the game source for an example.
Parameters
ent Entity to adjust.
open State to adjust to.
Definition at line 528 of file g_syscalls.c.
 {
     syscall(G_ADJUST_AREA_PORTAL_STATE, ent, open);
 }
References G_ADJUST_AREA_PORTAL_STATE.
Referenced by Reached_BinaryMover(), and Use_BinaryMover().
trap_AreasConnected()
qboolean trap_AreasConnected (int area1, int area2)
This functions tests whether or not the areas (presumably leaf nodes of the bsp tree) are adjacent physically.
FIXME: the values of area1 and area2 are unknown, however.
Parameters
area1 First area to test.
area2 Second area to test.
Returns
Definition at line 541 of file g_syscalls.c.
 {
     return syscall(G_AREAS_CONNECTED, area1, area2);
 }
References G_AREAS_CONNECTED.
trap_Argc()
int trap_Argc (void)
Whenever a client issues a console command it can have arguments passed with it.
Returns
The number of arguments identically to the argc found in C programs with this prototype for main: int main(int argc, char **argv).
Definition at line 92 of file g_syscalls.c.
 {
     return syscall(G_ARGC);
 }
References G_ARGC.
trap_Argv()
void trap_Argv (int n, char * buffer, int bufferLength)
This will fill the buffer pointed to by buffer with an argument to a client command where n is the argument to return.
0 is the command itself, 1 is the first argument and so on... Very similiar to char **argv in a C program.
Parameters
n The argument number to return.
buffer A point to a buffer to fill.
bufferLength The size of the buffer.
Definition at line 105 of file g_syscalls.c.
 {
     syscall(G_ARGV, n, buffer, bufferLength);
 }
References buffer, and G_ARGV.
trap_BotAddAvoidSpot()
void trap_BotAddAvoidSpot (int movestate, vec3_t origin, float radius, int type)
Definition at line 1302 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_ADD_AVOID_SPOT, movestate, origin, PASSFLOAT(radius), type);
 }
References BOTLIB_AI_ADD_AVOID_SPOT, and PASSFLOAT().
Referenced by BotCheckForGrenades(), and BotCheckSnapshot().
trap_BotAllocateClient()
int trap_BotAllocateClient (void)
Allocates a free client slot and returns the client number.
Also marks the client as bot in the engine (arg2 will be 1 when a GAME_CLIENT_CONNECT message is dispatched to vmMain for this client).
On failure, -1 is returned.
Definition at line 620 of file g_syscalls.c.
 {
     return syscall(G_BOT_ALLOCATE_CLIENT);
 }
References G_BOT_ALLOCATE_CLIENT.
Referenced by G_AddBot().
trap_BotAllocChatState()
int trap_BotAllocChatState (void)
Definition at line 1048 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_CHAT_STATE);
 }
References BOTLIB_AI_ALLOC_CHAT_STATE.
Referenced by BotAISetupClient().
trap_BotAllocGoalState()
int trap_BotAllocGoalState (int state)
Definition at line 1287 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_GOAL_STATE, state);
 }
References BOTLIB_AI_ALLOC_GOAL_STATE.
Referenced by BotAISetupClient().
trap_BotAllocMoveState()
int trap_BotAllocMoveState (void)
Definition at line 1343 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_MOVE_STATE);
 }
References BOTLIB_AI_ALLOC_MOVE_STATE.
Referenced by BotAISetupClient().
trap_BotAllocWeaponState()
int trap_BotAllocWeaponState (void)
Definition at line 1373 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_ALLOC_WEAPON_STATE);
 }
References BOTLIB_AI_ALLOC_WEAPON_STATE.
Referenced by BotAISetupClient().
trap_BotAvoidGoalTime()
float trap_BotAvoidGoalTime (int goalstate, int number)
Definition at line 1240 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AI_AVOID_GOAL_TIME, goalstate, number);
     return fi.f;
 }
References BOTLIB_AI_AVOID_GOAL_TIME, floatint_t::f, and floatint_t::i.
trap_BotChatLength()
int trap_BotChatLength (int chatstate)
Definition at line 1095 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHAT_LENGTH, chatstate);
 }
References BOTLIB_AI_CHAT_LENGTH.
trap_BotChooseBestFightWeapon()
int trap_BotChooseBestFightWeapon (int weaponstate, int * inventory)
Definition at line 1358 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHOOSE_BEST_FIGHT_WEAPON, weaponstate, inventory);
 }
References BOTLIB_AI_CHOOSE_BEST_FIGHT_WEAPON.
Referenced by BotChooseWeapon().
trap_BotChooseLTGItem()
int trap_BotChooseLTGItem (int goalstate, vec3_t origin, int * inventory, int travelflags)
Definition at line 1205 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHOOSE_LTG_ITEM, goalstate, origin, inventory, travelflags);
 }
References BOTLIB_AI_CHOOSE_LTG_ITEM.
Referenced by BotGetItemLongTermGoal().
trap_BotChooseNBGItem()
int trap_BotChooseNBGItem (int goalstate, vec3_t origin, int * inventory, int travelflags, void * ltg, float maxtime)
Definition at line 1210 of file g_syscalls.c.
References BOTLIB_AI_CHOOSE_NBG_ITEM, and PASSFLOAT().
Referenced by BotGoForAir(), and BotNearbyGoal().
trap_BotDumpAvoidGoals()
void trap_BotDumpAvoidGoals (int goalstate)
Definition at line 1180 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_DUMP_AVOID_GOALS, goalstate);
 }
References BOTLIB_AI_DUMP_AVOID_GOALS.
Referenced by BotDeathmatchAI().
trap_BotDumpGoalStack()
void trap_BotDumpGoalStack (int goalstate)
Definition at line 1185 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_DUMP_GOAL_STACK, goalstate);
 }
References BOTLIB_AI_DUMP_GOAL_STACK.
Referenced by BotDeathmatchAI().
trap_BotEmptyGoalStack()
void trap_BotEmptyGoalStack (int goalstate)
Definition at line 1175 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_EMPTY_GOAL_STACK, goalstate);
 }
References BOTLIB_AI_EMPTY_GOAL_STACK.
Referenced by AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
trap_BotEnterChat()
void trap_BotEnterChat (int chatstate, int client, int sendto)
Definition at line 1100 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_ENTER_CHAT, chatstate, client, sendto);
 }
References BOTLIB_AI_ENTER_CHAT.
Referenced by AIEnter_Intermission(), AINode_Respawn(), AINode_Stand(), BotAIShutdownClient(), BotChatTest(), BotGetLongTermGoal(), BotLongTermGoal(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_Dismiss(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_TaskPreference(), BotMatch_WhatAreYouDoing(), BotMatch_WhereAreYou(), BotMatch_WhichTeam(), BotSayTeamOrderAlways(), BotTeamAI(), BotVoiceChat_Camp(), BotVoiceChat_FollowMe(), BotVoiceChat_Patrol(), BotVoiceChat_WantOnDefense(), BotVoiceChat_WantOnOffense(), and BotVoiceChat_WhoIsLeader().
trap_BotFindMatch()
int trap_BotFindMatch (char * str, void * match, unsigned long int context)
Definition at line 1115 of file g_syscalls.c.
References BOTLIB_AI_FIND_MATCH.
Referenced by BotAddressedToBot(), BotCheckConsoleMessages(), BotGetPatrolWaypoints(), BotGetTime(), BotMatch_HelpAccompany(), and BotMatchMessage().
trap_BotFreeCharacter()
void trap_BotFreeCharacter (int character)
Definition at line 1014 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_CHARACTER, character);
 }
References BOTLIB_AI_FREE_CHARACTER.
Referenced by BotAIShutdownClient().
trap_BotFreeChatState()
void trap_BotFreeChatState (int handle)
Definition at line 1053 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_CHAT_STATE, handle);
 }
References BOTLIB_AI_FREE_CHAT_STATE.
Referenced by BotAISetupClient(), and BotAIShutdownClient().
trap_BotFreeClient()
void trap_BotFreeClient (int clientNum)
Definition at line 625 of file g_syscalls.c.
 {
     syscall(G_BOT_FREE_CLIENT, clientNum);
 }
References G_BOT_FREE_CLIENT.
Referenced by G_AddBot().
trap_BotFreeGoalState()
void trap_BotFreeGoalState (int handle)
Definition at line 1292 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_GOAL_STATE, handle);
 }
References BOTLIB_AI_FREE_GOAL_STATE.
Referenced by BotAISetupClient(), and BotAIShutdownClient().
trap_BotFreeItemWeights()
void trap_BotFreeItemWeights (int goalstate)
Definition at line 1267 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_ITEM_WEIGHTS, goalstate);
 }
References BOTLIB_AI_FREE_ITEM_WEIGHTS.
trap_BotFreeMoveState()
void trap_BotFreeMoveState (int handle)
Definition at line 1348 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_MOVE_STATE, handle);
 }
References BOTLIB_AI_FREE_MOVE_STATE.
Referenced by BotAIShutdownClient().
trap_BotFreeWeaponState()
void trap_BotFreeWeaponState (int weaponstate)
Definition at line 1378 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_FREE_WEAPON_STATE, weaponstate);
 }
References BOTLIB_AI_FREE_WEAPON_STATE.
Referenced by BotAISetupClient(), and BotAIShutdownClient().
trap_BotGetChatMessage()
void trap_BotGetChatMessage (int chatstate, char * buf, int size)
Definition at line 1105 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_GET_CHAT_MESSAGE, chatstate, buf, size);
 }
References BOTLIB_AI_GET_CHAT_MESSAGE.
Referenced by BotSayTeamOrder(), and BotSayTeamOrderAlways().
trap_BotGetLevelItemGoal()
int trap_BotGetLevelItemGoal (int index, char * classname, void * goal)
Definition at line 1225 of file g_syscalls.c.
References BOTLIB_AI_GET_LEVEL_ITEM_GOAL.
Referenced by BotDontAvoid(), BotGetItemTeamGoal(), BotNearestVisibleItem(), BotSetupAlternativeRouteGoals(), and BotSetupDeathmatchAI().
trap_BotGetMapLocationGoal()
int trap_BotGetMapLocationGoal (char * name, void * goal)
Definition at line 1235 of file g_syscalls.c.
References BOTLIB_AI_GET_MAP_LOCATION_GOAL.
trap_BotGetNextCampSpotGoal()
int trap_BotGetNextCampSpotGoal (int num, void * goal)
Definition at line 1230 of file g_syscalls.c.
References BOTLIB_AI_GET_NEXT_CAMP_SPOT_GOAL.
Referenced by BotWantsToCamp().
trap_BotGetSecondGoal()
int trap_BotGetSecondGoal (int goalstate, void * goal)
Definition at line 1200 of file g_syscalls.c.
References BOTLIB_AI_GET_SECOND_GOAL.
Referenced by AINode_Seek_NBG().
trap_BotGetServerCommand()
int trap_BotGetServerCommand (int clientNum, char * message, int size)
Definition at line 759 of file g_syscalls.c.
 {
     return syscall(BOTLIB_GET_CONSOLE_MESSAGE, clientNum, message, size);
 }
References BOTLIB_GET_CONSOLE_MESSAGE.
Referenced by BotAI().
trap_BotGetSnapshotEntity()
int trap_BotGetSnapshotEntity (int clientNum, int sequence)
Definition at line 754 of file g_syscalls.c.
 {
     return syscall(BOTLIB_GET_SNAPSHOT_ENTITY, clientNum, sequence);
 }
References BOTLIB_GET_SNAPSHOT_ENTITY.
Referenced by BotAI_GetSnapshotEntity().
trap_BotGetTopGoal()
int trap_BotGetTopGoal (int goalstate, void * goal)
Definition at line 1195 of file g_syscalls.c.
References BOTLIB_AI_GET_TOP_GOAL.
Referenced by AIEnter_Seek_LTG(), AIEnter_Seek_NBG(), AINode_Battle_NBG(), AINode_Seek_NBG(), BotGetItemLongTermGoal(), BotGoForAir(), and BotSetInfoConfigString().
trap_BotGetWeaponInfo()
void trap_BotGetWeaponInfo (int weaponstate, int weapon, void * weaponinfo)
Definition at line 1363 of file g_syscalls.c.
References BOTLIB_AI_GET_WEAPON_INFO.
Referenced by BotAimAtEnemy(), and BotCheckAttack().
trap_BotGoalName()
void trap_BotGoalName (int number, char * name, int size)
Definition at line 1190 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_GOAL_NAME, number, name, size);
 }
References BOTLIB_AI_GOAL_NAME.
Referenced by AIEnter_Seek_LTG(), AIEnter_Seek_NBG(), BotGetLongTermGoal(), BotMatch_WhatAreYouDoing(), BotNearestVisibleItem(), BotReportStatus(), and BotSetInfoConfigString().
trap_BotInitialChat()
void trap_BotInitialChat (int chatstate, char * type, int mcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 1078 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_INITIAL_CHAT, chatstate, type, mcontext, var0, var1, var2, var3, var4, var5, var6, var7);
 }
References BOTLIB_AI_INITIAL_CHAT.
Referenced by BotAI_BotInitialChat().
trap_BotInitLevelItems()
void trap_BotInitLevelItems (void)
Definition at line 1252 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_INIT_LEVEL_ITEMS);
 }
References BOTLIB_AI_INIT_LEVEL_ITEMS.
trap_BotInitMoveState()
void trap_BotInitMoveState (int handle, void * initmove)
Definition at line 1353 of file g_syscalls.c.
References BOTLIB_AI_INIT_MOVE_STATE.
Referenced by BotSetupForMovement().
trap_BotInterbreedGoalFuzzyLogic()
void trap_BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
Definition at line 1272 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_INTERBREED_GOAL_FUZZY_LOGIC, parent1, parent2, child);
 }
References BOTLIB_AI_INTERBREED_GOAL_FUZZY_LOGIC.
Referenced by BotInterbreedBots().
trap_BotItemGoalInVisButNotVisible()
int trap_BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, void * goal)
Definition at line 1220 of file g_syscalls.c.
References BOTLIB_AI_ITEM_GOAL_IN_VIS_BUT_NOT_VISIBLE.
Referenced by BotGetLongTermGoal(), and BotReachedGoal().
trap_BotLibDefine()
int trap_BotLibDefine (char * string)
Definition at line 729 of file g_syscalls.c.
 {
     return syscall(BOTLIB_PC_ADD_GLOBAL_DEFINE, string);
 }
References BOTLIB_PC_ADD_GLOBAL_DEFINE.
Referenced by BotInitLibrary().
trap_BotLibLoadMap()
int trap_BotLibLoadMap (const char * mapname)
Definition at line 739 of file g_syscalls.c.
 {
     return syscall(BOTLIB_LOAD_MAP, mapname);
 }
References BOTLIB_LOAD_MAP.
Referenced by BotAILoadMap().
trap_BotLibSetup()
int trap_BotLibSetup (void)
Definition at line 709 of file g_syscalls.c.
 {
     return syscall(BOTLIB_SETUP);
 }
References BOTLIB_SETUP.
Referenced by BotInitLibrary().
trap_BotLibShutdown()
int trap_BotLibShutdown (void)
Definition at line 714 of file g_syscalls.c.
 {
     return syscall(BOTLIB_SHUTDOWN);
 }
References BOTLIB_SHUTDOWN.
Referenced by BotAIShutdown().
trap_BotLibStartFrame()
int trap_BotLibStartFrame (float time)
Definition at line 734 of file g_syscalls.c.
 {
     return syscall(BOTLIB_START_FRAME, PASSFLOAT(time));
 }
References BOTLIB_START_FRAME, and PASSFLOAT().
Referenced by BotAIStartFrame().
trap_BotLibTest()
int trap_BotLibTest (int parm0, char * parm1, vec3_t parm2, vec3_t parm3)
Definition at line 749 of file g_syscalls.c.
 {
     return syscall(BOTLIB_TEST, parm0, parm1, parm2, parm3);
 }
References BOTLIB_TEST.
trap_BotLibUpdateEntity()
int trap_BotLibUpdateEntity (int ent, void * bue)
Definition at line 744 of file g_syscalls.c.
References BOTLIB_UPDATENTITY.
Referenced by BotAIStartFrame().
trap_BotLibVarGet()
int trap_BotLibVarGet (char * var_name, char * value, int size)
Definition at line 724 of file g_syscalls.c.
 {
     return syscall(BOTLIB_LIBVAR_GET, var_name, value, size);
 }
References BOTLIB_LIBVAR_GET.
trap_BotLibVarSet()
int trap_BotLibVarSet (char * var_name, char * value)
Definition at line 719 of file g_syscalls.c.
 {
     return syscall(BOTLIB_LIBVAR_SET, var_name, value);
 }
References BOTLIB_LIBVAR_SET.
Referenced by BotAISetupClient(), BotAIStartFrame(), BotCheckConsoleMessages(), BotInitLibrary(), and BotInterbreeding().
trap_BotLoadCharacter()
int trap_BotLoadCharacter (char * charfile, float skill)
Definition at line 1009 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_CHARACTER, charfile, PASSFLOAT(skill));
 }
References BOTLIB_AI_LOAD_CHARACTER, and PASSFLOAT().
Referenced by BotAISetupClient().
trap_BotLoadChatFile()
int trap_BotLoadChatFile (int chatstate, char * chatfile, char * chatname)
Definition at line 1135 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_CHAT_FILE, chatstate, chatfile, chatname);
 }
References BOTLIB_AI_LOAD_CHAT_FILE.
Referenced by BotAISetupClient().
trap_BotLoadItemWeights()
int trap_BotLoadItemWeights (int goalstate, char * filename)
Definition at line 1262 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_ITEM_WEIGHTS, goalstate, filename);
 }
References BOTLIB_AI_LOAD_ITEM_WEIGHTS.
Referenced by BotAISetupClient().
trap_BotLoadWeaponWeights()
int trap_BotLoadWeaponWeights (int weaponstate, char * filename)
Definition at line 1368 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_LOAD_WEAPON_WEIGHTS, weaponstate, filename);
 }
References BOTLIB_AI_LOAD_WEAPON_WEIGHTS.
Referenced by BotAISetupClient().
trap_BotMatchVariable()
void trap_BotMatchVariable (void * match, int variable, char * buf, int size)
Definition at line 1120 of file g_syscalls.c.
References BOTLIB_AI_MATCH_VARIABLE.
Referenced by BotAddressedToBot(), BotCheckConsoleMessages(), BotGetPatrolWaypoints(), BotGetTime(), BotMatch_AttackEnemyBase(), BotMatch_Camp(), BotMatch_CheckPoint(), BotMatch_CTF(), BotMatch_DefendKeyArea(), BotMatch_Dismiss(), BotMatch_EnterGame(), BotMatch_FormationSpace(), BotMatch_GetFlag(), BotMatch_GetItem(), BotMatch_HelpAccompany(), BotMatch_JoinSubteam(), BotMatch_Kill(), BotMatch_LeadTheWay(), BotMatch_LeaveSubteam(), BotMatch_NewLeader(), BotMatch_Patrol(), BotMatch_ReturnFlag(), BotMatch_RushBase(), BotMatch_StartTeamLeaderShip(), BotMatch_StopTeamLeaderShip(), BotMatch_Suicide(), BotMatch_TaskPreference(), BotMatch_WhatAreYouDoing(), and BotMatch_WhereAreYou().
trap_BotMoveInDirection()
int trap_BotMoveInDirection (int movestate, vec3_t dir, float speed, int type)
Definition at line 1313 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_MOVE_IN_DIRECTION, movestate, dir, PASSFLOAT(speed), type);
 }
References BOTLIB_AI_MOVE_IN_DIRECTION, and PASSFLOAT().
Referenced by BotAIBlocked(), BotAttackMove(), BotGetLongTermGoal(), and BotRandomMove().
trap_BotMovementViewTarget()
int trap_BotMovementViewTarget (int movestate, void * goal, int travelflags, float lookahead, vec3_t target)
Definition at line 1333 of file g_syscalls.c.
References BOTLIB_AI_MOVEMENT_VIEW_TARGET, and PASSFLOAT().
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), and AINode_Seek_NBG().
trap_BotMoveToGoal()
void trap_BotMoveToGoal (void * result, int movestate, void * goal, int travelflags)
Definition at line 1307 of file g_syscalls.c.
References BOTLIB_AI_MOVE_TO_GOAL.
Referenced by AINode_Battle_Chase(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), and BotAttackMove().
trap_BotMutateGoalFuzzyLogic()
void trap_BotMutateGoalFuzzyLogic (int goalstate, float range)
Definition at line 1282 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_MUTATE_GOAL_FUZZY_LOGIC, goalstate, PASSFLOAT(range));
 }
References BOTLIB_AI_MUTATE_GOAL_FUZZY_LOGIC, and PASSFLOAT().
Referenced by BotAISetupClient(), and BotInterbreedBots().
trap_BotNextConsoleMessage()
int trap_BotNextConsoleMessage (int chatstate, void * cm)
Definition at line 1068 of file g_syscalls.c.
References BOTLIB_AI_NEXT_CONSOLE_MESSAGE, and cm.
Referenced by BotCheckConsoleMessages().
trap_BotNumConsoleMessages()
int trap_BotNumConsoleMessages (int chatstate)
Definition at line 1073 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_NUM_CONSOLE_MESSAGE, chatstate);
 }
References BOTLIB_AI_NUM_CONSOLE_MESSAGE.
Referenced by BotCheckConsoleMessages().
trap_BotNumInitialChats()
int trap_BotNumInitialChats (int chatstate, char * type)
Definition at line 1084 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_NUM_INITIAL_CHATS, chatstate, type);
 }
References BOTLIB_AI_NUM_INITIAL_CHATS.
Referenced by BotChat_Death(), BotChat_Kill(), and BotChatTest().
trap_BotPopGoal()
void trap_BotPopGoal (int goalstate)
Definition at line 1170 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_POP_GOAL, goalstate);
 }
References BOTLIB_AI_POP_GOAL.
Referenced by AINode_Battle_NBG(), AINode_Seek_NBG(), BotGetItemLongTermGoal(), and BotGoForAir().
trap_BotPredictVisiblePosition()
int trap_BotPredictVisiblePosition (vec3_t origin, int areanum, void * goal, int travelflags, vec3_t target)
Definition at line 1338 of file g_syscalls.c.
References BOTLIB_AI_PREDICT_VISIBLE_POSITION.
Referenced by BotAimAtEnemy().
trap_BotPushGoal()
void trap_BotPushGoal (int goalstate, void * goal)
Definition at line 1165 of file g_syscalls.c.
References BOTLIB_AI_PUSH_GOAL.
Referenced by BotGoForAir().
trap_BotQueueConsoleMessage()
void trap_BotQueueConsoleMessage (int chatstate, int type, char * message)
Definition at line 1058 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_QUEUE_CONSOLE_MESSAGE, chatstate, type, message);
 }
References BOTLIB_AI_QUEUE_CONSOLE_MESSAGE.
Referenced by BotAI(), and BotSayTeamOrderAlways().
trap_BotReachabilityArea()
int trap_BotReachabilityArea (vec3_t origin, int testground)
Definition at line 1328 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_REACHABILITY_AREA, origin, testground);
 }
References BOTLIB_AI_REACHABILITY_AREA.
trap_BotRemoveConsoleMessage()
void trap_BotRemoveConsoleMessage (int chatstate, int handle)
Definition at line 1063 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_REMOVE_CONSOLE_MESSAGE, chatstate, handle);
 }
References BOTLIB_AI_REMOVE_CONSOLE_MESSAGE.
Referenced by BotCheckConsoleMessages().
trap_BotRemoveFromAvoidGoals()
void trap_BotRemoveFromAvoidGoals (int goalstate, int number)
Definition at line 1160 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_REMOVE_FROM_AVOID_GOALS, goalstate, number);
 }
References BOTLIB_AI_REMOVE_FROM_AVOID_GOALS.
Referenced by BotDontAvoid().
trap_BotReplaceSynonyms()
void trap_BotReplaceSynonyms (char * string, unsigned long int context)
Definition at line 1130 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_REPLACE_SYNONYMS, string, context);
 }
References BOTLIB_AI_REPLACE_SYNONYMS.
Referenced by BotCheckConsoleMessages().
trap_BotReplyChat()
int trap_BotReplyChat (int chatstate, char * message, int mcontext, int vcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 1089 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_REPLY_CHAT, chatstate, message, mcontext, vcontext, var0, var1, var2, var3, var4, var5, var6, var7);
 }
References BOTLIB_AI_REPLY_CHAT.
Referenced by BotCheckConsoleMessages().
trap_BotResetAvoidGoals()
void trap_BotResetAvoidGoals (int goalstate)
Definition at line 1155 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_AVOID_GOALS, goalstate);
 }
References BOTLIB_AI_RESET_AVOID_GOALS.
Referenced by AIEnter_Respawn(), BotGetItemLongTermGoal(), BotGoForAir(), and BotResetState().
trap_BotResetAvoidReach()
void trap_BotResetAvoidReach (int movestate)
Definition at line 1318 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_AVOID_REACH, movestate);
 }
References BOTLIB_AI_RESET_AVOID_REACH.
Referenced by AIEnter_Respawn(), AINode_Battle_Chase(), AINode_Battle_Fight(), AINode_Battle_NBG(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), BotGetItemLongTermGoal(), BotGetLongTermGoal(), and BotResetState().
trap_BotResetGoalState()
void trap_BotResetGoalState (int goalstate)
Definition at line 1150 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_GOAL_STATE, goalstate);
 }
References BOTLIB_AI_RESET_GOAL_STATE.
Referenced by AIEnter_Respawn(), and BotResetState().
trap_BotResetLastAvoidReach()
void trap_BotResetLastAvoidReach (int movestate)
Definition at line 1323 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_LAST_AVOID_REACH, movestate);
 }
References BOTLIB_AI_RESET_LAST_AVOID_REACH.
Referenced by AIEnter_Battle_Fight(), AIEnter_Battle_SuicidalFight(), AINode_Battle_Chase(), AINode_Battle_Retreat(), AINode_Seek_ActivateEntity(), AINode_Seek_LTG(), AINode_Seek_NBG(), and BotGetLongTermGoal().
trap_BotResetMoveState()
void trap_BotResetMoveState (int movestate)
Definition at line 1297 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_MOVE_STATE, movestate);
 }
References BOTLIB_AI_RESET_MOVE_STATE.
Referenced by AIEnter_Respawn(), and BotResetState().
trap_BotResetWeaponState()
void trap_BotResetWeaponState (int weaponstate)
Definition at line 1383 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_RESET_WEAPON_STATE, weaponstate);
 }
References BOTLIB_AI_RESET_WEAPON_STATE.
Referenced by BotResetState().
trap_BotSaveGoalFuzzyLogic()
void trap_BotSaveGoalFuzzyLogic (int goalstate, char * filename)
Definition at line 1277 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SAVE_GOAL_FUZZY_LOGIC, goalstate, filename);
 }
References BOTLIB_AI_SAVE_GOAL_FUZZY_LOGIC.
Referenced by BotWriteInterbreeded().
trap_BotSetAvoidGoalTime()
void trap_BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
Definition at line 1247 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SET_AVOID_GOAL_TIME, goalstate, number, PASSFLOAT(avoidtime));
 }
References BOTLIB_AI_SET_AVOID_GOAL_TIME, and PASSFLOAT().
Referenced by BotReachedGoal().
trap_BotSetChatGender()
void trap_BotSetChatGender (int chatstate, int gender)
Definition at line 1140 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SET_CHAT_GENDER, chatstate, gender);
 }
References BOTLIB_AI_SET_CHAT_GENDER.
Referenced by BotAISetupClient(), and BotDeathmatchAI().
trap_BotSetChatName()
void trap_BotSetChatName (int chatstate, char * name, int client)
Definition at line 1145 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_SET_CHAT_NAME, chatstate, name, client);
 }
References BOTLIB_AI_SET_CHAT_NAME.
Referenced by BotDeathmatchAI().
trap_BotTouchingGoal()
int trap_BotTouchingGoal (vec3_t origin, void * goal)
Definition at line 1215 of file g_syscalls.c.
References BOTLIB_AI_TOUCHING_GOAL.
Referenced by AINode_Battle_Chase(), AINode_Seek_ActivateEntity(), BotGetLongTermGoal(), and BotReachedGoal().
trap_BotUpdateEntityItems()
void trap_BotUpdateEntityItems (void)
Definition at line 1257 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_UPDATE_ENTITY_ITEMS);
 }
References BOTLIB_AI_UPDATE_ENTITY_ITEMS.
Referenced by BotAIRegularUpdate().
trap_BotUserCommand()
void trap_BotUserCommand (int clientNum, usercmd_t * ucmd)
Definition at line 764 of file g_syscalls.c.
 {
     syscall(BOTLIB_USER_COMMAND, clientNum, ucmd);
 }
References BOTLIB_USER_COMMAND.
Referenced by BotAIStartFrame().
trap_Characteristic_BFloat()
float trap_Characteristic_BFloat (int character, int index, float min, float max)
Definition at line 1026 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AI_CHARACTERISTIC_BFLOAT, character, index, PASSFLOAT(min), PASSFLOAT(max));
     return fi.f;
 }
References BOTLIB_AI_CHARACTERISTIC_BFLOAT, floatint_t::f, floatint_t::i, and PASSFLOAT().
Referenced by AINode_Battle_NBG(), AINode_Battle_Retreat(), BotAimAtEnemy(), BotAISetupClient(), BotAttackMove(), BotCanAndWantsToRocketJump(), BotChangeViewAngles(), BotChat_Death(), BotChat_EndLevel(), BotChat_EnemySuicide(), BotChat_EnterGame(), BotChat_ExitGame(), BotChat_HitNoDeath(), BotChat_HitNoKill(), BotChat_HitTalking(), BotChat_Kill(), BotChat_Random(), BotChat_StartLevel(), BotCheckAttack(), BotCheckConsoleMessages(), BotFindEnemy(), BotGetLongTermGoal(), BotGoCamp(), BotMapScripts(), and BotWantsToCamp().
trap_Characteristic_BInteger()
int trap_Characteristic_BInteger (int character, int index, int min, int max)
Definition at line 1038 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHARACTERISTIC_BINTEGER, character, index, min, max);
 }
References BOTLIB_AI_CHARACTERISTIC_BINTEGER.
trap_Characteristic_Float()
float trap_Characteristic_Float (int character, int index)
Definition at line 1019 of file g_syscalls.c.
 {
     floatint_t fi;
     fi.i = syscall(BOTLIB_AI_CHARACTERISTIC_FLOAT, character, index);
     return fi.f;
 }
References BOTLIB_AI_CHARACTERISTIC_FLOAT, floatint_t::f, and floatint_t::i.
trap_Characteristic_Integer()
int trap_Characteristic_Integer (int character, int index)
Definition at line 1033 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_CHARACTERISTIC_INTEGER, character, index);
 }
References BOTLIB_AI_CHARACTERISTIC_INTEGER.
trap_Characteristic_String()
void trap_Characteristic_String (int character, int index, char * buf, int size)
Definition at line 1043 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_CHARACTERISTIC_STRING, character, index, buf, size);
 }
References BOTLIB_AI_CHARACTERISTIC_STRING.
Referenced by BotAISetupClient(), and BotDeathmatchAI().
trap_Cvar_Register()
void trap_Cvar_Register (vmCvar_t * cvar, const char * var_name, const char * value, int flags)
This function is used to create a new vmCvar.
It sends all the information to the engine's main database and then it stores a local copy of the data into the vmCvar_t passed as the first argument.
Parameters
cvar A pointer the location in which to store the local data.
var_name A null-terminated string that will be used to set the vmCvar's name field.
value A null-terminated string that will be used to set both the floating point and integer value fields of the vmCvar.
flags ?.
Definition at line 221 of file g_syscalls.c.
 {
     syscall(G_CVAR_REGISTER, cvar, var_name, value, flags);
 }
References G_CVAR_REGISTER.
trap_Cvar_Set()
void trap_Cvar_Set (const char * var_name, const char * value)
This function searchs for the name of the vmCvar and stores the value into both the float and integer fields of the corresponding vmCvar entry.
The only way to effectly change the value of a vmCvar is to use this function, the ANSI storage operator only modifies the local buffer and not the "master copy".
Parameters
var_name A null-terminated string containing the name of the vmCvar to set.
value A null-terminated string containing the desired value.
Definition at line 246 of file g_syscalls.c.
 {
     syscall(G_CVAR_SET, var_name, value);
 }
References G_CVAR_SET.
trap_Cvar_Update()
void trap_Cvar_Update (vmCvar_t * cvar)
This function first parses out the name of the vmCvar and then searches for the corresponding database entry.
Once it finds the vmCvar it will copy the "master copy" of the vmCvar into the local address provided.
Parameters
cvar A pointer to the vmCvar to update.
Definition at line 232 of file g_syscalls.c.
 {
     syscall(G_CVAR_UPDATE, cvar);
 }
References G_CVAR_UPDATE.
trap_Cvar_VariableIntegerValue()
int trap_Cvar_VariableIntegerValue (const char * var_name)
This function returns the integer value of var_name that is currently stored in the "master copy".
Parameters
var_name A null-terminated string containing the name of the vmCvar to retrieve a value from.
Returns
The integer value of var_name that is currently stored in the "master copy".
Definition at line 257 of file g_syscalls.c.
 {
     return syscall(G_CVAR_VARIABLE_INTEGER_VALUE, var_name);
 }
References G_CVAR_VARIABLE_INTEGER_VALUE.
Referenced by BotAISetupClient(), BotSetupDeathmatchAI(), G_InitGame(), G_ItemDisabled(), G_LoadBots(), G_RankGameOver(), G_ShutdownGame(), PodiumPlacementThink(), SpawnPodium(), and Svcmd_AddBot_f().
trap_Cvar_VariableStringBuffer()
void trap_Cvar_VariableStringBuffer (const char * var_name, char * buffer, int bufsize)
This trap copies the content of a cvar named by var_name into a mod-space string.
Parameters
var_name
buffer
bufsize
Definition at line 268 of file g_syscalls.c.
 {
     syscall(G_CVAR_VARIABLE_STRING_BUFFER, var_name, buffer, bufsize);
 }
References buffer, and G_CVAR_VARIABLE_STRING_BUFFER.
trap_DebugPolygonCreate()
int trap_DebugPolygonCreate (int color, int numPoints, vec3_t * points)
Creates a solid coloured permanent polygon in the renderer (and world) based on the given array of vertices/points.
it returns a reference handle to the polygon as it appears in the renderlist. This function should be disabled, but it may still work.
In Q3 1.31, only a single debug polygon can be displayed at once. Calling trap_DebugPolygonCreate() to draw a second polygon causes none of them to be drawn on the screen. Delete the old polygon before trying to draw the new one.
Parameters
color
numPoints
points
Returns
Definition at line 669 of file g_syscalls.c.
 {
     return syscall(G_DEBUG_POLYGON_CREATE, color, numPoints, points);
 }
References G_DEBUG_POLYGON_CREATE.
Referenced by DebugLine().
trap_DebugPolygonDelete()
void trap_DebugPolygonDelete (int id)
Removes a polygon that was previously created via trap_DebugPolygonCreate.
Parameters
id a value previously returned by trap_DebugPolygonCreate.
Definition at line 679 of file g_syscalls.c.
 {
     syscall(G_DEBUG_POLYGON_DELETE, id);
 }
References G_DEBUG_POLYGON_DELETE.
trap_DropClient()
void trap_DropClient (int clientNum, const char * reason)
This provides a mechanism to unconditionally drop a client from a server via their clientNum (ent->client->ps.clientNum).
The reason is displayed to the client when they are dropped.
Parameters
clientNum The client to drop.
reason The reason for the drop.
Definition at line 299 of file g_syscalls.c.
 {
     syscall(G_DROP_CLIENT, clientNum, reason);
 }
References G_DROP_CLIENT.
Referenced by ClientInactivityTimer(), ClientUserinfoChanged(), and G_BotConnect().
trap_EA_Action()
void trap_EA_Action (int client, int action)
Definition at line 904 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_ACTION, client, action);
 }
References BOTLIB_EA_ACTION.
Referenced by BotGetLongTermGoal(), BotMatch_Suicide(), BotMatch_TaskPreference(), BotRefuseOrder(), BotVoiceChat_WantOnDefense(), and BotVoiceChat_WantOnOffense().
trap_EA_Attack()
void trap_EA_Attack (int client)
Definition at line 919 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_ATTACK, client);
 }
References BOTLIB_EA_ATTACK.
Referenced by AINode_Seek_ActivateEntity(), BotCheckAttack(), BotClearPath(), and BotMapScripts().
trap_EA_Command()
void trap_EA_Command (int client, char * command)
Definition at line 899 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_COMMAND, client, command);
 }
References BOTLIB_EA_COMMAND.
Referenced by BotChat_Death(), BotChat_EndLevel(), BotChat_Kill(), BotChat_Random(), BotChat_StartLevel(), BotMatch_Suicide(), BotVoiceChat(), and BotVoiceChatOnly().
trap_EA_Crouch()
void trap_EA_Crouch (int client)
Definition at line 934 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_CROUCH, client);
 }
References BOTLIB_EA_CROUCH.
Referenced by BotGetLongTermGoal().
trap_EA_DelayedJump()
void trap_EA_DelayedJump (int client)
Definition at line 979 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_DELAYED_JUMP, client);
 }
References BOTLIB_EA_DELAYED_JUMP.
trap_EA_EndRegular()
void trap_EA_EndRegular (int client, float thinktime)
Definition at line 994 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_END_REGULAR, client, PASSFLOAT(thinktime));
 }
References BOTLIB_EA_END_REGULAR, and PASSFLOAT().
trap_EA_Gesture()
void trap_EA_Gesture (int client)
Definition at line 909 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_GESTURE, client);
 }
References BOTLIB_EA_GESTURE.
Referenced by AINode_Seek_LTG(), and BotGetLongTermGoal().
trap_EA_GetInput()
void trap_EA_GetInput (int client, float thinktime, void * input)
Definition at line 999 of file g_syscalls.c.
References BOTLIB_EA_GET_INPUT, and PASSFLOAT().
Referenced by BotUpdateInput().
trap_EA_Jump()
void trap_EA_Jump (int client)
Definition at line 974 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_JUMP, client);
 }
References BOTLIB_EA_JUMP.
trap_EA_Move()
void trap_EA_Move (int client, vec3_t dir, float speed)
Definition at line 984 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE, client, dir, PASSFLOAT(speed));
 }
References BOTLIB_EA_MOVE, and PASSFLOAT().
trap_EA_MoveBack()
void trap_EA_MoveBack (int client)
Definition at line 954 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_BACK, client);
 }
References BOTLIB_EA_MOVE_BACK.
trap_EA_MoveDown()
void trap_EA_MoveDown (int client)
Definition at line 944 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_DOWN, client);
 }
References BOTLIB_EA_MOVE_DOWN.
trap_EA_MoveForward()
void trap_EA_MoveForward (int client)
Definition at line 949 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_FORWARD, client);
 }
References BOTLIB_EA_MOVE_FORWARD.
trap_EA_MoveLeft()
void trap_EA_MoveLeft (int client)
Definition at line 959 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_LEFT, client);
 }
References BOTLIB_EA_MOVE_LEFT.
trap_EA_MoveRight()
void trap_EA_MoveRight (int client)
Definition at line 964 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_RIGHT, client);
 }
References BOTLIB_EA_MOVE_RIGHT.
trap_EA_MoveUp()
void trap_EA_MoveUp (int client)
Definition at line 939 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_MOVE_UP, client);
 }
References BOTLIB_EA_MOVE_UP.
trap_EA_ResetInput()
void trap_EA_ResetInput (int client)
Definition at line 1004 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_RESET_INPUT, client);
 }
References BOTLIB_EA_RESET_INPUT.
Referenced by BotAI().
trap_EA_Respawn()
void trap_EA_Respawn (int client)
Definition at line 929 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_RESPAWN, client);
 }
References BOTLIB_EA_RESPAWN.
Referenced by AINode_Respawn().
trap_EA_Say()
void trap_EA_Say (int client, char * str)
Definition at line 889 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_SAY, client, str);
 }
References BOTLIB_EA_SAY.
Referenced by BotPrintActivateGoalInfo().
trap_EA_SayTeam()
void trap_EA_SayTeam (int client, char * str)
Definition at line 894 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_SAY_TEAM, client, str);
 }
References BOTLIB_EA_SAY_TEAM.
Referenced by BotGetPatrolWaypoints(), BotMatch_WhoIsTeamLeader(), and BotMatchMessage().
trap_EA_SelectWeapon()
void trap_EA_SelectWeapon (int client, int weapon)
Definition at line 969 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_SELECT_WEAPON, client, weapon);
 }
References BOTLIB_EA_SELECT_WEAPON.
Referenced by BotAI(), and BotChooseWeapon().
trap_EA_Talk()
void trap_EA_Talk (int client)
Definition at line 914 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_TALK, client);
 }
References BOTLIB_EA_TALK.
Referenced by AINode_Respawn(), and AINode_Stand().
trap_EA_Use()
void trap_EA_Use (int client)
Definition at line 924 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_USE, client);
 }
References BOTLIB_EA_USE.
Referenced by BotBattleUseItems(), and BotCheckEvents().
trap_EA_View()
void trap_EA_View (int client, vec3_t viewangles)
Definition at line 989 of file g_syscalls.c.
 {
     syscall(BOTLIB_EA_VIEW, client, viewangles);
 }
References BOTLIB_EA_VIEW.
Referenced by BotAimAtEnemy(), and BotChangeViewAngles().
trap_EntitiesInBox()
int trap_EntitiesInBox (const vec3_t mins, const vec3_t maxs, int * list, int maxcount)
This fills an array of ints with the entity numbers (ent->s.number) of all the entities currently within the cuboid defined by mins and maxs.
Two vectors - mins and maxs - to be passed in, representing the extents (or farthest points) of an invisible box in the world of Q3.
Parameters
[in] mins The position of the corner of a cuboid.
[in] maxs The position of the opposite corner of this cuboid.
[in,out] list A array of integers(entityNum's (entity indices)) to hold any entities that positively past the test for existence within the boxs boundaries.
[in] maxcount The maximum amount of entities that will be returned by the parameter, list.
Returns
The number of all entities that were successfully found in the box.
Definition at line 590 of file g_syscalls.c.
 {
     return syscall(G_ENTITIES_IN_BOX, mins, maxs, list, maxcount);
 }
References G_ENTITIES_IN_BOX.
Referenced by G_KillBox(), G_MoverPush(), G_RadiusDamage(), G_TouchTriggers(), and SpotWouldTelefrag().
trap_EntityContact()
qboolean trap_EntityContact (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
Definition at line 595 of file g_syscalls.c.
 {
     return syscall(G_ENTITY_CONTACT, mins, maxs, ent);
 }
References G_ENTITY_CONTACT.
Referenced by G_TouchTriggers().
trap_EntityContactCapsule()
qboolean trap_EntityContactCapsule (const vec3_t mins, const vec3_t maxs, const gentity_t * ent)
If the entity pointed to by ent is physically within the bounds specified by mins and maxs then this function returns qtrue.
Parameters
mins Lower bounds.
maxs Upper bounds.
ent The entity to test.
Returns
Definition at line 608 of file g_syscalls.c.
 {
     return syscall(G_ENTITY_CONTACTCAPSULE, mins, maxs, ent);
 }
References G_ENTITY_CONTACTCAPSULE.
trap_Error()
void trap_Error (const char * text)
This is very similar to the trap_Print function with the exception that this will halt execution of the module it is called from.
Usually the user shouldn't call this directly, but using G_Error instead.
Parameters
text Text to be displayed.
Definition at line 67 of file g_syscalls.c.
 {
     syscall(G_ERROR, text);
     // shut up GCC warning about returning functions, because we know better
     exit(1);
 }
References G_ERROR.
trap_FS_FCloseFile()
void trap_FS_FCloseFile (fileHandle_t f)
Closes the file specified by f.
Parameters
f The file to be closed.
Definition at line 159 of file g_syscalls.c.
 {
     syscall(G_FS_FCLOSE_FILE, f);
 }
References G_FS_FCLOSE_FILE.
trap_FS_FOpenFile()
int trap_FS_FOpenFile (const char * qpath, fileHandle_t * f, fsMode_t mode)
This opens a file specified by the string qpath and allocates a fileHandle_t (just a typedef int) to that file.
This is then used in subsequent operations involving the file. The fsMode_t enumeration refers to the mode the file is opened in. FS_READ for reading the file. FS_WRITE will create the file qpath if it doesn't exist or 0 length it if it does. FS_APPEND allows writing to the end of an existing file. FS_APPEND_SYNC is similar to FS_APPEND except you can read from the file at the same time.
An int is returned representing the length of the file being opened.
Parameters
qpath The file to be opened.
f Reference to a local fileHandle_t.
mode Mode to open the file in.
Returns
Definition at line 125 of file g_syscalls.c.
 {
     return syscall(G_FS_FOPEN_FILE, qpath, f, mode);
 }
References G_FS_FOPEN_FILE.
trap_FS_GetFileList()
int trap_FS_GetFileList (const char * path, const char * extension, char * listbuf, int bufsize)
This fills listbuf with a NULL delimited list of all the files in the directory specified by path ending in extension.
The number of files listed is returned.
Parameters
path String reflecting a directory.
extension File extension to list (incluing a leading period).
listbuf Pointer to a buffer to fill.
bufsize Length of the buffer.
Returns
Definition at line 174 of file g_syscalls.c.
 {
     return syscall(G_FS_GETFILELIST, path, extension, listbuf, bufsize);
 }
trap_FS_Read()
void trap_FS_Read (void * buffer, int len, fileHandle_t f)
This reads len bytes of data from the file specified by f and fills buffer with it.
Parameters
buffer A buffer to fill.
len he amount to read from the file.
f A file handle provided by trap_FS_FOpenFile.
Definition at line 137 of file g_syscalls.c.
 {
     syscall(G_FS_READ, buffer, len, f);
 }
References buffer, and G_FS_READ.
trap_FS_Seek()
int trap_FS_Seek (fileHandle_t f, long offset, int origin)
Definition at line 179 of file g_syscalls.c.
 {
     return syscall(G_FS_SEEK, f, offset, origin);
 }
References G_FS_SEEK.
trap_FS_Write()
void trap_FS_Write (const void * buffer, int len, fileHandle_t f)
This writes len bytes of data from buffer to the file specified by f.
Parameters
buffer A buffer to read from.
len The amount to write to the file.
f A file handle provided by trap_FS_FOpenFile.
Definition at line 149 of file g_syscalls.c.
 {
     syscall(G_FS_WRITE, buffer, len, f);
 }
References buffer, and G_FS_WRITE.
trap_GeneticParentsAndChildSelection()
int trap_GeneticParentsAndChildSelection (int numranks, float * ranks, int * parent1, int * parent2, int * child)
Definition at line 1388 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_GENETIC_PARENTS_AND_CHILD_SELECTION, numranks, ranks, parent1, parent2, child);
 }
References BOTLIB_AI_GENETIC_PARENTS_AND_CHILD_SELECTION.
Referenced by BotInterbreedBots().
trap_GetConfigstring()
void trap_GetConfigstring (int num, char * buffer, int bufferSize)
This is a server side callback used to get the value of a config string.
It is only used once in the q3 source, by the G_FindConfigstringIndex function which in turn is used by the G_ModelIndex and G_SoundIndex functions.
Parameters
num The config string to be read.
buffer A pointer to a buffer to fill with the config string value.
bufferSize The size of the buffer.
Definition at line 341 of file g_syscalls.c.
 {
     syscall(G_GET_CONFIGSTRING, num, buffer, bufferSize);
 }
References buffer, and G_GET_CONFIGSTRING.
Referenced by BotCheckEvents(), BotFirstClientInRankings(), BotIsFirstInRankings(), BotIsLastInRankings(), BotIsObserver(), BotLastClientInRankings(), BotNumActivePlayers(), BotNumTeamMates(), BotRandomOpponentName(), BotSortTeamMatesByBaseTravelTime(), BotTeamOrders(), BotTeamplayReport(), BotUpdateInfoConfigStrings(), ClientFromName(), ClientName(), ClientOnSameTeamFromName(), ClientSkin(), G_FindConfigstringIndex(), and NumPlayersOnSameTeam().
trap_GetEntityToken()
qboolean trap_GetEntityToken (char * buffer, int bufferSize)
This call fills the buffer pointed to by buffer with all the key/value pairs of every map entity.
The string returned has a very similar format to that of the tail end of a GTKRadiant .map file before it is compiled to a bsp. It is unlikely that a user would ever need to call this since it is handled already in g_spawn.c.
Parameters
buffer A buffer to fill.
bufferSize The size of the buffer.
Returns
Definition at line 650 of file g_syscalls.c.
 {
     return syscall(G_GET_ENTITY_TOKEN, buffer, bufferSize);
 }
References buffer, CG_GET_ENTITY_TOKEN, and G_GET_ENTITY_TOKEN.
Referenced by G_ParseSpawnVars().
trap_GetServerinfo()
void trap_GetServerinfo (char * buffer, int bufferSize)
The "server info" string is a backslash delimited list of server variables such as g_gametype and mapname.
Besides the bot code, its only other use in the Q3 source is to print to the value of serverinfo to the logfile.
Parameters
buffer A buffer to fill with the server info.
bufferSize The size of the buffer.
Definition at line 381 of file g_syscalls.c.
 {
     syscall(G_GET_SERVERINFO, buffer, bufferSize);
 }
References buffer, and G_GET_SERVERINFO.
Referenced by BotMapScripts(), BotMapTitle(), G_InitBots(), and G_InitGame().
trap_GetUsercmd()
void trap_GetUsercmd (int clientNum, usercmd_t * cmd)
This function will retrieve the usercmd_t generated by the client portion of the Q3 binary and place it in what it pointed to by cmd.
Parameters
clientNum The clientNum to retreive cmd from.
cmd Pointer to a usercmd_t to fill.
Definition at line 636 of file g_syscalls.c.
 {
     syscall(G_GET_USERCMD, clientNum, cmd);
 }
References G_GET_USERCMD.
Referenced by ClientSpawn(), and ClientThink().
trap_GetUserinfo()
void trap_GetUserinfo (int num, char * buffer, int bufferSize)
Each client has a "user info" string which is a backslash delimited key/value pair for the various options the user can set.
For example, model, skin and weapon colour. trap_GetUserinfo fills the buffer pointed to by *buffer with the userinfo of the client referenced by num. Key values are then retrieved using Info_ValueForKey(buffer, keyname).
Parameters
num clientNum of the userinfo to retrieve.
buffer Pointer to a buffer to fill.
bufferSize Size of the buffer.
Definition at line 356 of file g_syscalls.c.
 {
     syscall(G_GET_USERINFO, num, buffer, bufferSize);
 }
References buffer, and G_GET_USERINFO.
Referenced by BotDeathmatchAI(), BotSetUserInfo(), ClientConnect(), ClientSpawn(), ClientUserinfoChanged(), Cmd_TeamTask_f(), G_BotConnect(), and G_CheckBotSpawn().
trap_InPVS()
qboolean trap_InPVS (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
Two points can return true, but not be visible to each other due to detail brushes, curves, etc. A return value of false guarantees that the points can not see each other. Normally used to test if two entities can potentially see each other, point1 would be the currentOrigin of the first entitiy and point2 the currentOrigin of the second entity. This function relies on the Potentially Visible Set, and areaportal data generated during the BSP compiling of a map.
Parameters
p1 Absolute coordinates of point 1.
p2 Absolute coordinates of point 2.
Returns
Definition at line 498 of file g_syscalls.c.
 {
     return syscall(G_IN_PVS, p1, p2);
 }
References G_IN_PVS.
Referenced by Team_FragBonuses(), and Team_GetLocation().
trap_InPVSIgnorePortals()
qboolean trap_InPVSIgnorePortals (const vec3_t p1, const vec3_t p2)
Returns true if point1 can potentially see point2.
This function does not check areaportals. Points hidden by closed doors (and other areaportals) will still return true.
Parameters
p1 Absolute coordinates of point 1.
p2 Absolute coordinates of point 2.
Returns
Definition at line 512 of file g_syscalls.c.
 {
     return syscall(G_IN_PVS_IGNORE_PORTALS, p1, p2);
 }
References G_IN_PVS_IGNORE_PORTALS.
trap_LinkEntity()
void trap_LinkEntity (gentity_t * ent)
When an entity is "linked" it is subject to all evaluations that the world performs on it.
For example, all linked entities are accounted for when performing a trace. Newly created entities are not linked into the world - they must be explcitly linked using this call. Linking an entity that is already linked into the world has no effect unless the following properties have changed:
Its origin or angles have changed which might cause a change in the entity's PVS (ent->r.currentOrigin is used to calculate the entity's PVS cluster)
Its bounds have changed (again, is used in PVS cluster calculations, and to set abs(min/max))
Its contents have changed (will set ent->s.solid)
Its brush model has changed (again, sets ent->s.solid)
Parameters
ent Entity to be linked.
Definition at line 558 of file g_syscalls.c.
 {
     syscall(G_LINKENTITY, ent);
 }
References G_LINKENTITY.
Referenced by ClientSpawn(), ClientThink_real(), CopyToBodyQue(), FinishSpawningItem(), G_ExplodeMissile(), G_MissileImpact(), G_MoverPush(), G_MoverTeam(), G_RunItem(), G_RunMissile(), G_TempEntity(), G_TryPushingEntity(), G_TryPushingProxMine(), hurt_use(), InitMover(), InitShooter(), LaunchItem(), player_die(), RespawnItem(), SetMoverState(), SP_func_rotating(), SP_misc_model(), SP_misc_portal_camera(), SP_misc_portal_surface(), SP_target_speaker(), SP_trigger_hurt(), SP_trigger_multiple(), SP_trigger_push(), SP_trigger_teleport(), SpawnModelOnVictoryPad(), SpawnPlatTrigger(), SpawnPodium(), target_laser_think(), TeleportPlayer(), Think_SpawnNewDoorTrigger(), Touch_Item(), and weapon_railgun_fire().
trap_LocateGameData()
void trap_LocateGameData (gentity_t * gEnts, int numGEntities, int sizeofGEntity_t, playerState_t * clients, int sizeofGClient)
It would be very unusual for a mod programmer to want to call this - especially with parameters other than those outlined above.
Its purpose it to notify the Q3 binary when new entities are created. In the Q3 source it is used twice - once on level load and in G_Spawn where it is called whenever an entity is created.
Parameters
gEnts Usually level.gentities.
numGEntities Usually level.num_entities.
sizeofGEntity_t Usually sizeof(gentity_t).
clients Usually &level.clients;[0].ps.
sizeofGClient Usually sizeof(level.clients[0]).
Definition at line 286 of file g_syscalls.c.
 {
     syscall(G_LOCATE_GAME_DATA, gEnts, numGEntities, sizeofGEntity_t, clients, sizeofGClient);
 }
References G_LOCATE_GAME_DATA.
Referenced by G_InitGame(), and G_Spawn().
trap_Milliseconds()
int trap_Milliseconds (void)
Returns the number of milliseconds that have elapsed since Quake 3 was executed.
A Quake 3, multi-platform version of the Win32 function timeGetTime, which also returns the number of milliseconds since the program was executed.
Returns
The number of milliseconds that have elapsed since Quake 3 was executed.
Definition at line 81 of file g_syscalls.c.
 {
     return syscall(G_MILLISECONDS);
 }
References G_MILLISECONDS.
trap_PC_FreeSource()
int trap_PC_FreeSource (int handle)
Definition at line 1398 of file g_syscalls.c.
 {
     return syscall(BOTLIB_PC_FREE_SOURCE, handle);
 }
References BOTLIB_PC_FREE_SOURCE.
trap_PC_LoadSource()
int trap_PC_LoadSource (const char * filename)
Definition at line 1393 of file g_syscalls.c.
 {
     return syscall(BOTLIB_PC_LOAD_SOURCE, filename);
 }
References BOTLIB_PC_LOAD_SOURCE.
trap_PC_ReadToken()
int trap_PC_ReadToken (int handle, pc_token_t * pc_token)
Definition at line 1403 of file g_syscalls.c.
 {
     return syscall(BOTLIB_PC_READ_TOKEN, handle, pc_token);
 }
References BOTLIB_PC_READ_TOKEN.
trap_PC_SourceFileAndLine()
int trap_PC_SourceFileAndLine (int handle, char * filename, int * line)
Definition at line 1408 of file g_syscalls.c.
 {
     return syscall(BOTLIB_PC_SOURCE_FILE_AND_LINE, handle, filename, line);
 }
References BOTLIB_PC_SOURCE_FILE_AND_LINE.
trap_PointContents()
int trap_PointContents (const vec3_t point, int passEntityNum)
This trap call returns the CONTENTS_* of a specific point in space - it is commonly used to avoid spawning items in CONTENTS_NODROP areas.
The second parameter specifies an entityNum (ent->s.number) which is ignored when evaluating the contents for a point.
Parameters
point The point in space to be examined.
passEntityNum An entityNum to be ignored.
Returns
The CONTENTS_* of the specific point in space.
Definition at line 480 of file g_syscalls.c.
 {
     return syscall(G_POINT_CONTENTS, point, passEntityNum);
 }
References G_POINT_CONTENTS.
Referenced by BotGetLongTermGoal(), BotRoamGoal(), BotValidChatPosition(), ClientThink_real(), CopyToBodyQue(), G_RunItem(), player_die(), and SpectatorThink().
trap_Print()
void trap_Print (const char * text)
trap_Print prints the string pointed to by fmt to the Q3 Console.
This should not usually be used directly by the user; the G_Printf function provides its functionality and more.
Parameters
text Text to be displayed.
Definition at line 54 of file g_syscalls.c.
 {
     syscall(G_PRINT, text);
 }
References G_PRINT.
trap_RealTime()
int trap_RealTime (qtime_t * qtime)
Returns current system time and date at server.
Parameters
qtime Point in time - look at q_shared.h qtime_t for details.
Returns
The current system time and date at server.
Definition at line 690 of file g_syscalls.c.
 {
     return syscall(G_REAL_TIME, qtime);
 }
References G_REAL_TIME.
trap_SendConsoleCommand()
void trap_SendConsoleCommand (int exec_when, const char * text)
This call adds a command to the command buffer i.e.
so that the programmer may issue server commands that would normally need to be entered into the console. exec_when takes an element of the cbufExec_t enumeration:
Description of the EXEC_* values are described in q_shared.h.
In general, EXEC_APPEND is the most common use, simulating the user typing in the command. The string is stored to a buffer (appended) until a game frame is completed, then the engine will examine the buffered strings to run.
EXEC_NOW is a bad idea, as it can lead to an infinite loop: EXEC_NOW causes an immediate jump into engine space, which then jumps back to QVM/mod space to execute commands, which could lead to an immediate jump right back to engine space, which would lead to... and so on.
Useless examples: trap_SendConsoleCommand(EXEC_APPEND, "team free"); trap_SendConsoleCommand(EXEC_APPEND, "say Vini vidi vici.; quit");.
Parameters
exec_when When to execute this command: EXEC_NOW, EXEC_INSERT, EXEC_APPEND.
text The command to be executed.
Definition at line 206 of file g_syscalls.c.
 {
     syscall(G_SEND_CONSOLE_COMMAND, exec_when, text);
 }
References G_SEND_CONSOLE_COMMAND.
trap_SendServerCommand()
void trap_SendServerCommand (int clientNum, const char * text)
This has the same effect as typing a command in a clients console for evaluation by the server.
This includes the commands evaluated in g_cmds.c. Its main use in the Q3 source is to print information to a specific client's console via the "print" command. Passing -1 as the clientNum sends the command to every client.
Parameters
clientNum The client that the command is being sent from.
text The command to be sent.
Definition at line 313 of file g_syscalls.c.
 {
     syscall(G_SEND_SERVER_COMMAND, clientNum, text);
 }
References G_SEND_SERVER_COMMAND.
Referenced by __attribute__(), BroadcastTeamChange(), CheatsOk(), CheckExitRules(), CheckTeamVote(), CheckVote(), ClientBegin(), ClientCommand(), ClientConnect(), ClientInactivityTimer(), ClientNumberFromString(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_God_f(), Cmd_LevelShot_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_SetViewpos_f(), Cmd_Team_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_Vote_f(), Cmd_Where_f(), ConsoleCommand(), DeathmatchScoreboardMessage(), G_RankRunFrame(), G_SayTo(), G_TeamCommand(), G_UpdateCvars(), PrintTeam(), SetTeam(), Svcmd_AddBot_f(), TeamplayInfoMessage(), and Use_Target_Print().
trap_SetBrushModel()
void trap_SetBrushModel (gentity_t * ent, const char * name)
This function does several special things to an entity which should not be done any other way.
It sets the clipping bounds of the entity to use the collision map contained in the brush model specified. Brush models have a complex collision map which is far more detailed than a regular bounding-box (doors, plats, movers etc). The mins and maxes of a brush-model entity may differ wildly from reality.
It sets the entity to have the SOLID_BMODEL type which serves to alert clients that the modelindex used to render this entity is not in the regular list, but instead is the index into the cgs.inlineDrawModel list which is built on start-up. This list is zero-indexed from *1 and therefore does not contain the map itself. Another method must be used to get the client to render the map a second time.
It sets the "bmodel" member of the entityShared_t structure to 1 (entityShared_t is the "r" member of the gentity_t structure). This allows a simple method of checking if an entity uses a brush model.
There is nothing to prevent an entity from using a brush model which is not built into the map (not inline). However this ability is not used anywhere in Q3A or Q3TA. The map compilers have special command-line switches to build BSPs which are externally lit and designed to be stand-alone models. If this is attempted the cgame QVM will require special code (a bit-flag or similar) to allow it to know the difference between a brush-model index that is inline and one that is external.
And thats' the last function in the game list!!.
Parameters
ent The entity to apply the collision map to.
name The name of the brush model. If the model is inline (built into the map) it will "*0", "*1", "*n". These names are generated by the map compiler and cannot be changed. "*0" is always the map itself. If the model is external to the map then it is the filename of the BSP (another map is technically valid as a stand-alone model though it is not externally lit and all external surfaces are backfaced culled).
Definition at line 418 of file g_syscalls.c.
 {
     syscall(G_SET_BRUSH_MODEL, ent, name);
 }
References G_SET_BRUSH_MODEL.
Referenced by InitTrigger(), SP_func_bobbing(), SP_func_button(), SP_func_door(), SP_func_pendulum(), SP_func_plat(), SP_func_rotating(), SP_func_static(), and SP_func_train().
trap_SetConfigstring()
void trap_SetConfigstring (int num, const char * string)
The Q3 Engine provides a mechanism for communicating data from the server to the client via config strings.
This is (presumably) an array of strings within the engine that are indexed by the CS_* values in bg_public.c. This trap call sets one of these strings to a value. Config strings should usually be used to communicate complex data that changes relatively rarely.
Parameters
num The config string to set.
string The value to set it to.
Definition at line 327 of file g_syscalls.c.
 {
     syscall(G_SET_CONFIGSTRING, num, string);
 }
References G_SET_CONFIGSTRING.
Referenced by BotSetInfoConfigString(), CalculateRanks(), CheckTeamVote(), CheckTournament(), CheckVote(), ClientDisconnect(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), G_FindConfigstringIndex(), G_InitGame(), G_RemapTeamShaders(), G_UseTargets(), LogExit(), SaveRegisteredItems(), SP_worldspawn(), target_location_linkup(), and Team_SetFlagStatus().
trap_SetUserinfo()
void trap_SetUserinfo (int num, const char * buffer)
This does the opposite to trap_GetUserinfo and sets a userinfo string for a user.
However, it is not used much in the Q3 source, where config strings seem to be the prefered method to transfer userinfo to the client.
Parameters
num clientNum of userinfo to change.
buffer Userinfo string to set.
Definition at line 369 of file g_syscalls.c.
 {
     syscall(G_SET_USERINFO, num, buffer);
 }
References buffer, and G_SET_USERINFO.
Referenced by BotDeathmatchAI(), BotSetUserInfo(), Cmd_TeamTask_f(), and G_AddBot().
trap_SnapVector()
void trap_SnapVector (float * v)
This simply removes the fractional part of each axis of v - a form of "snap to grid".
Its purpose is to save network bandwidth by exploiting the fact that delta compression will only transmit the changes in state of a struct. A changing vector will change less frequently if only the integral part is taken into account.
Parameters
v Vector to snap.
Definition at line 703 of file g_syscalls.c.
 {
     syscall(G_SNAPVECTOR, v);
 }
References CG_SNAPVECTOR, and G_SNAPVECTOR.
Referenced by PmoveSingle().
trap_StringContains()
int trap_StringContains (char * str1, char * str2, int casesensitive)
Definition at line 1110 of file g_syscalls.c.
 {
     return syscall(BOTLIB_AI_STRING_CONTAINS, str1, str2, casesensitive);
 }
References BOTLIB_AI_STRING_CONTAINS.
trap_Trace()
void trap_Trace (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
This function is used to trace from one position to another in the BSP tree and store the results in a trace_t structure.
The results consist of the following information (where tr is a variable of type trace_t):
tr.allsolid: If this is qtrue, then the area (or some part of it) between the mins and maxs is inside a solid (a brush).
tr.contents: The contents mask of the plane that the trace hit.
tr.endpos: Position where the trace ended.
tr.entityNum: Entity number of the entity that the trace hit. If it hit solid geometry then this will equal ENTITYNUM_WORLD.
tr.fraction: This is the fraction of the vector between start and end where the trace ended. Therefore if this is less than 1.0 the trace hit something.
tr.plane: Information about the plane that was hit (most notably the surface normal) stored in a cplane_t structure.
tr.startsolid: If this is qtrue, then the trace started in a solid (brush).
tr.surfaceFlags: surfaceflags of the surface that was hit (look in surfaceflags.h at the SURF_* constants to see the which ones there are).
If the mins and maxs are NULL then the trace is treated as purely linear from point to point.
If mins and maxs are defined however a bounding box trace is performed whereby rather than a point the entire bounding box is traced so that it is possible to detect the collision between solid entities. For example, tracing directly downwards onto a floor with mins and maxs set to { -15, -15, -15 } and { 15, 15, 15 } respectively starting at some point above the floor will result in a trace_t with an endpoint 15 units from the floor.
Parameters
results Pointer to a variable of type trace_t where the result of the trace will be stored.
start Vector representing the starting position of the trace.
mins Vector representing the mins of the bounding box the trace will have.
maxs Vector representing the maxs of the bounding box the trace will have.
end Vector representing the end position of the trace (it's destination).
passEntityNum The trace will not collide against the entity with this number (usually set to the entity number of the entity that initiated the trace so it won't collide against itself).
contentmask The content mask it should collide against. Use any of the MASK_ or CONTENTS_ constants. You can logical OR several of them together if needed.
Definition at line 456 of file g_syscalls.c.
 {
     syscall(G_TRACE, results, start, mins, maxs, end, passEntityNum, contentmask);
 }
References G_TRACE.
Referenced by BotAI_Trace(), Bullet_Fire(), CanDamage(), CheckGauntletAttack(), ClientThink_real(), FinishSpawningItem(), G_CheckProxMinePosition(), G_RunItem(), G_RunMissile(), G_TestEntityPosition(), Pickup_Powerup(), ShotgunPellet(), SpectatorThink(), target_laser_think(), Weapon_LightningFire(), and weapon_railgun_fire().
trap_TraceCapsule()
void trap_TraceCapsule (trace_t * results, const vec3_t start, const vec3_t mins, const vec3_t maxs, const vec3_t end, int passEntityNum, int contentmask)
Definition at line 464 of file g_syscalls.c.
 {
     syscall(G_TRACECAPSULE, results, start, mins, maxs, end, passEntityNum, contentmask);
 }
References G_TRACECAPSULE.
trap_UnifyWhiteSpaces()
void trap_UnifyWhiteSpaces (char * string)
Definition at line 1125 of file g_syscalls.c.
 {
     syscall(BOTLIB_AI_UNIFY_WHITE_SPACES, string);
 }
References BOTLIB_AI_UNIFY_WHITE_SPACES.
Referenced by BotCheckConsoleMessages().
trap_UnlinkEntity()
void trap_UnlinkEntity (gentity_t * ent)
When an entity is "unlinked" from the world it remains in memory, but ceases to exist from the point of view of the world.
This is useful for temporarily deleting an entity or when performing major alterations to an entity's fields. Unlinking an entity that is already unlinked has no effect.
Parameters
ent Entity to be unlinked.
Definition at line 571 of file g_syscalls.c.
 {
     syscall(G_UNLINKENTITY, ent);
 }
References G_UNLINKENTITY.
Referenced by BodySink(), ClientBegin(), ClientDisconnect(), CopyToBodyQue(), G_FreeEntity(), G_MoverPush(), G_RunFrame(), hurt_use(), SP_trigger_hurt(), SpectatorThink(), target_laser_off(), TeleportPlayer(), Use_Target_Give(), and weapon_railgun_fire().