ioquake3 doxygen: C:/entry/dev/ioquake3/code/botlib/l_script.h File Reference
l_script.h File Reference
Classes
struct punctuation_s
struct token_s
struct script_s
Macros
#define BINARYNUMBERS
#define NUMBERVALUE
#define DOLLAR
#define MAX_TOKEN 1024
#define SCFL_NOERRORS 0x0001
#define SCFL_NOWARNINGS 0x0002
#define SCFL_NOSTRINGWHITESPACES 0x0004
#define SCFL_NOSTRINGESCAPECHARS 0x0008
#define SCFL_PRIMITIVE 0x0010
#define SCFL_NOBINARYNUMBERS 0x0020
#define SCFL_NONUMBERVALUES 0x0040
#define TT_STRING 1
#define TT_LITERAL 2
#define TT_NUMBER 3
#define TT_NAME 4
#define TT_PUNCTUATION 5
#define TT_DECIMAL 0x0008
#define TT_HEX 0x0100
#define TT_OCTAL 0x0200
#define TT_BINARY 0x0400
#define TT_FLOAT 0x0800
#define TT_INTEGER 0x1000
#define TT_LONG 0x2000
#define TT_UNSIGNED 0x4000
#define P_RSHIFT_ASSIGN 1
#define P_LSHIFT_ASSIGN 2
#define P_PARMS 3
#define P_PRECOMPMERGE 4
#define P_LOGIC_AND 5
#define P_LOGIC_OR 6
#define P_LOGIC_GEQ 7
#define P_LOGIC_LEQ 8
#define P_LOGIC_EQ 9
#define P_LOGIC_UNEQ 10
#define P_MUL_ASSIGN 11
#define P_DIV_ASSIGN 12
#define P_MOD_ASSIGN 13
#define P_ADD_ASSIGN 14
#define P_SUB_ASSIGN 15
#define P_INC 16
#define P_DEC 17
#define P_BIN_AND_ASSIGN 18
#define P_BIN_OR_ASSIGN 19
#define P_BIN_XOR_ASSIGN 20
#define P_RSHIFT 21
#define P_LSHIFT 22
#define P_POINTERREF 23
#define P_CPP1 24
#define P_CPP2 25
#define P_MUL 26
#define P_DIV 27
#define P_MOD 28
#define P_ADD 29
#define P_SUB 30
#define P_ASSIGN 31
#define P_BIN_AND 32
#define P_BIN_OR 33
#define P_BIN_XOR 34
#define P_BIN_NOT 35
#define P_LOGIC_NOT 36
#define P_LOGIC_GREATER 37
#define P_LOGIC_LESS 38
#define P_REF 39
#define P_COMMA 40
#define P_SEMICOLON 41
#define P_COLON 42
#define P_QUESTIONMARK 43
#define P_PARENTHESESOPEN 44
#define P_PARENTHESESCLOSE 45
#define P_BRACEOPEN 46
#define P_BRACECLOSE 47
#define P_SQBRACKETOPEN 48
#define P_SQBRACKETCLOSE 49
#define P_BACKSLASH 50
#define P_PRECOMP 51
#define P_DOLLAR 52
Typedefs
typedef struct punctuation_s punctuation_t
typedef struct token_s token_t
typedef struct script_s script_t
Functions
int PS_ReadToken (script_t *script, token_t *token)
int PS_ExpectTokenString (script_t *script, char *string)
int PS_ExpectTokenType (script_t *script, int type, int subtype, token_t *token)
int PS_ExpectAnyToken (script_t *script, token_t *token)
int PS_CheckTokenString (script_t *script, char *string)
int PS_CheckTokenType (script_t *script, int type, int subtype, token_t *token)
int PS_SkipUntilString (script_t *script, char *string)
void PS_UnreadLastToken (script_t *script)
void PS_UnreadToken (script_t *script, token_t *token)
char PS_NextWhiteSpaceChar (script_t *script)
void StripDoubleQuotes (char *string)
void StripSingleQuotes (char *string)
signed long int ReadSignedInt (script_t *script)
float ReadSignedFloat (script_t *script)
void SetScriptPunctuations (script_t *script, punctuation_t *p)
void SetScriptFlags (script_t *script, int flags)
int GetScriptFlags (script_t *script)
void ResetScript (script_t *script)
int EndOfScript (script_t *script)
char * PunctuationFromNum (script_t *script, int num)
script_t * LoadScriptFile (const char *filename)
script_t * LoadScriptMemory (char *ptr, int length, char *name)
void FreeScript (script_t *script)
void PS_SetBaseFolder (char *path)
void QDECL ScriptError (script_t *script, char *str,...) __attribute__((format(printf
void QDECL void QDECL ScriptWarning (script_t *script, char *str,...) __attribute__((format(printf
Macro Definition Documentation
BINARYNUMBERS
#define BINARYNUMBERS
Definition at line 33 of file l_script.h.
DOLLAR
#define DOLLAR
Definition at line 37 of file l_script.h.
MAX_TOKEN
#define MAX_TOKEN 1024
Definition at line 40 of file l_script.h.
NUMBERVALUE
#define NUMBERVALUE
Definition at line 35 of file l_script.h.
P_ADD
#define P_ADD 29
Definition at line 115 of file l_script.h.
P_ADD_ASSIGN
#define P_ADD_ASSIGN 14
Definition at line 98 of file l_script.h.
P_ASSIGN
#define P_ASSIGN 31
Definition at line 117 of file l_script.h.
P_BACKSLASH
#define P_BACKSLASH 50
Definition at line 140 of file l_script.h.
P_BIN_AND
#define P_BIN_AND 32
Definition at line 119 of file l_script.h.
P_BIN_AND_ASSIGN
#define P_BIN_AND_ASSIGN 18
Definition at line 103 of file l_script.h.
P_BIN_NOT
#define P_BIN_NOT 35
Definition at line 122 of file l_script.h.
P_BIN_OR
#define P_BIN_OR 33
Definition at line 120 of file l_script.h.
P_BIN_OR_ASSIGN
#define P_BIN_OR_ASSIGN 19
Definition at line 104 of file l_script.h.
P_BIN_XOR
#define P_BIN_XOR 34
Definition at line 121 of file l_script.h.
P_BIN_XOR_ASSIGN
#define P_BIN_XOR_ASSIGN 20
Definition at line 105 of file l_script.h.
P_BRACECLOSE
#define P_BRACECLOSE 47
Definition at line 137 of file l_script.h.
P_BRACEOPEN
#define P_BRACEOPEN 46
Definition at line 136 of file l_script.h.
P_COLON
#define P_COLON 42
Definition at line 131 of file l_script.h.
P_COMMA
#define P_COMMA 40
Definition at line 129 of file l_script.h.
P_CPP1
#define P_CPP1 24
Definition at line 110 of file l_script.h.
P_CPP2
#define P_CPP2 25
Definition at line 111 of file l_script.h.
P_DEC
#define P_DEC 17
Definition at line 101 of file l_script.h.
P_DIV
#define P_DIV 27
Definition at line 113 of file l_script.h.
P_DIV_ASSIGN
#define P_DIV_ASSIGN 12
Definition at line 96 of file l_script.h.
P_DOLLAR
#define P_DOLLAR 52
Definition at line 143 of file l_script.h.
P_INC
#define P_INC 16
Definition at line 100 of file l_script.h.
P_LOGIC_AND
#define P_LOGIC_AND 5
Definition at line 88 of file l_script.h.
P_LOGIC_EQ
#define P_LOGIC_EQ 9
Definition at line 92 of file l_script.h.
P_LOGIC_GEQ
#define P_LOGIC_GEQ 7
Definition at line 90 of file l_script.h.
P_LOGIC_GREATER
#define P_LOGIC_GREATER 37
Definition at line 125 of file l_script.h.
P_LOGIC_LEQ
#define P_LOGIC_LEQ 8
Definition at line 91 of file l_script.h.
P_LOGIC_LESS
#define P_LOGIC_LESS 38
Definition at line 126 of file l_script.h.
P_LOGIC_NOT
#define P_LOGIC_NOT 36
Definition at line 124 of file l_script.h.
P_LOGIC_OR
#define P_LOGIC_OR 6
Definition at line 89 of file l_script.h.
P_LOGIC_UNEQ
#define P_LOGIC_UNEQ 10
Definition at line 93 of file l_script.h.
P_LSHIFT
#define P_LSHIFT 22
Definition at line 107 of file l_script.h.
P_LSHIFT_ASSIGN
#define P_LSHIFT_ASSIGN 2
Definition at line 84 of file l_script.h.
P_MOD
#define P_MOD 28
Definition at line 114 of file l_script.h.
P_MOD_ASSIGN
#define P_MOD_ASSIGN 13
Definition at line 97 of file l_script.h.
P_MUL
#define P_MUL 26
Definition at line 112 of file l_script.h.
P_MUL_ASSIGN
#define P_MUL_ASSIGN 11
Definition at line 95 of file l_script.h.
P_PARENTHESESCLOSE
#define P_PARENTHESESCLOSE 45
Definition at line 135 of file l_script.h.
P_PARENTHESESOPEN
#define P_PARENTHESESOPEN 44
Definition at line 134 of file l_script.h.
P_PARMS
#define P_PARMS 3
Definition at line 85 of file l_script.h.
P_POINTERREF
#define P_POINTERREF 23
Definition at line 109 of file l_script.h.
P_PRECOMP
#define P_PRECOMP 51
Definition at line 142 of file l_script.h.
P_PRECOMPMERGE
#define P_PRECOMPMERGE 4
Definition at line 86 of file l_script.h.
P_QUESTIONMARK
#define P_QUESTIONMARK 43
Definition at line 132 of file l_script.h.
P_REF
#define P_REF 39
Definition at line 128 of file l_script.h.
P_RSHIFT
#define P_RSHIFT 21
Definition at line 106 of file l_script.h.
P_RSHIFT_ASSIGN
#define P_RSHIFT_ASSIGN 1
Definition at line 83 of file l_script.h.
P_SEMICOLON
#define P_SEMICOLON 41
Definition at line 130 of file l_script.h.
P_SQBRACKETCLOSE
#define P_SQBRACKETCLOSE 49
Definition at line 139 of file l_script.h.
P_SQBRACKETOPEN
#define P_SQBRACKETOPEN 48
Definition at line 138 of file l_script.h.
P_SUB
#define P_SUB 30
Definition at line 116 of file l_script.h.
P_SUB_ASSIGN
#define P_SUB_ASSIGN 15
Definition at line 99 of file l_script.h.
SCFL_NOBINARYNUMBERS
#define SCFL_NOBINARYNUMBERS 0x0020
Definition at line 53 of file l_script.h.
SCFL_NOERRORS
#define SCFL_NOERRORS 0x0001
Definition at line 48 of file l_script.h.
SCFL_NONUMBERVALUES
#define SCFL_NONUMBERVALUES 0x0040
Definition at line 54 of file l_script.h.
SCFL_NOSTRINGESCAPECHARS
#define SCFL_NOSTRINGESCAPECHARS 0x0008
Definition at line 51 of file l_script.h.
SCFL_NOSTRINGWHITESPACES
#define SCFL_NOSTRINGWHITESPACES 0x0004
Definition at line 50 of file l_script.h.
SCFL_NOWARNINGS
#define SCFL_NOWARNINGS 0x0002
Definition at line 49 of file l_script.h.
SCFL_PRIMITIVE
#define SCFL_PRIMITIVE 0x0010
Definition at line 52 of file l_script.h.
TT_BINARY
#define TT_BINARY 0x0400
Definition at line 75 of file l_script.h.
TT_DECIMAL
#define TT_DECIMAL 0x0008
Definition at line 71 of file l_script.h.
TT_FLOAT
#define TT_FLOAT 0x0800
Definition at line 77 of file l_script.h.
TT_HEX
#define TT_HEX 0x0100
Definition at line 72 of file l_script.h.
TT_INTEGER
#define TT_INTEGER 0x1000
Definition at line 78 of file l_script.h.
TT_LITERAL
#define TT_LITERAL 2
Definition at line 58 of file l_script.h.
TT_LONG
#define TT_LONG 0x2000
Definition at line 79 of file l_script.h.
TT_NAME
#define TT_NAME 4
Definition at line 60 of file l_script.h.
TT_NUMBER
#define TT_NUMBER 3
Definition at line 59 of file l_script.h.
TT_OCTAL
#define TT_OCTAL 0x0200
Definition at line 73 of file l_script.h.
TT_PUNCTUATION
#define TT_PUNCTUATION 5
Definition at line 61 of file l_script.h.
TT_STRING
#define TT_STRING 1
Definition at line 57 of file l_script.h.
TT_UNSIGNED
#define TT_UNSIGNED 0x4000
Definition at line 80 of file l_script.h.
Typedef Documentation
punctuation_t
typedef struct punctuation_s punctuation_t
script_t
typedef struct script_s script_t
token_t
typedef struct token_s token_t
Function Documentation
EndOfScript()
int EndOfScript (script_t * script)
Definition at line 1258 of file l_script.c.
 {
     return script->script_p >= script->end_p;
 } //end of the function EndOfScript
Referenced by PC_ReadSourceToken().
FreeScript()
void FreeScript (script_t * script)
Definition at line 1427 of file l_script.c.
 {
 #ifdef PUNCTABLE
     if (script->punctuationtable) FreeMemory(script->punctuationtable);
 #endif //PUNCTABLE
     FreeMemory(script);
 } //end of the function FreeScript
Referenced by AAS_ParseBSPEntities(), FreeSource(), PC_DefineFromString(), and PC_ReadSourceToken().
GetScriptFlags()
int GetScriptFlags (script_t * script)
Definition at line 1223 of file l_script.c.
 {
     return script->flags;
 } //end of the function GetScriptFlags
LoadScriptFile()
script_t* LoadScriptFile (const char * filename)
Definition at line 1324 of file l_script.c.
 {
 #ifdef BOTLIB
     fileHandle_t fp;
     char pathname[MAX_QPATH];
 #else
     FILE *fp;
 #endif
     int length;
     void *buffer;
     script_t *script;
 #ifdef BOTLIB
     if (strlen(basefolder))
         Com_sprintf(pathname, sizeof(pathname), "%s/%s", basefolder, filename);
     else
         Com_sprintf(pathname, sizeof(pathname), "%s", filename);
     length = botimport.FS_FOpenFile( pathname, &fp, FS_READ );
     if (!fp) return NULL;
 #else
     fp = fopen(filename, "rb");
     if (!fp) return NULL;
     length = FileLength(fp);
 #endif
     buffer = GetClearedMemory(sizeof(script_t) + length + 1);
     script = (script_t *) buffer;
     Com_Memset(script, 0, sizeof(script_t));
     Q_strncpyz(script->filename, filename, sizeof(script->filename));
     script->buffer = (char *) buffer + sizeof(script_t);
     script->buffer[length] = 0;
     script->length = length;
     //pointer in script buffer
     script->script_p = script->buffer;
     //pointer in script buffer before reading token
     script->lastscript_p = script->buffer;
     //pointer to end of script buffer
     script->end_p = &script->buffer[length];
     //set if there's a token available in script->token
     script->tokenavailable = 0;
     //
     script->line = 1;
     script->lastline = 1;
     //
     SetScriptPunctuations(script, NULL);
     //
 #ifdef BOTLIB
     botimport.FS_Read(script->buffer, length, fp);
     botimport.FS_FCloseFile(fp);
 #else
     if (fread(script->buffer, length, 1, fp) != 1)
     {
         FreeMemory(buffer);
         script = NULL;
     } //end if
     fclose(fp);
 #endif
     return script;
 } //end of the function LoadScriptFile
Referenced by LoadSourceFile(), and PC_Directive_include().
LoadScriptMemory()
script_t* LoadScriptMemory (char * ptr, int length, char * name)
Definition at line 1391 of file l_script.c.
 {
     void *buffer;
     script_t *script;
     buffer = GetClearedMemory(sizeof(script_t) + length + 1);
     script = (script_t *) buffer;
     Com_Memset(script, 0, sizeof(script_t));
     Q_strncpyz(script->filename, name, sizeof(script->filename));
     script->buffer = (char *) buffer + sizeof(script_t);
     script->buffer[length] = 0;
     script->length = length;
     //pointer in script buffer
     script->script_p = script->buffer;
     //pointer in script buffer before reading token
     script->lastscript_p = script->buffer;
     //pointer to end of script buffer
     script->end_p = &script->buffer[length];
     //set if there's a token available in script->token
     script->tokenavailable = 0;
     //
     script->line = 1;
     script->lastline = 1;
     //
     SetScriptPunctuations(script, NULL);
     //
     Com_Memcpy(script->buffer, ptr, length);
     //
     return script;
 } //end of the function LoadScriptMemory
Referenced by AAS_ParseBSPEntities(), LoadSourceMemory(), and PC_DefineFromString().
PS_CheckTokenString()
int PS_CheckTokenString (script_t * script, char * string)
Definition at line 1023 of file l_script.c.
 {
     token_t tok;
     if (!PS_ReadToken(script, &tok)) return 0;
     //if the token is available
     if (!strcmp(tok.string, string)) return 1;
     //token not available
     script->script_p = script->lastscript_p;
     return 0;
 } //end of the function PS_CheckTokenString
PS_CheckTokenType()
int PS_CheckTokenType (script_t * script, int type, int subtype, token_t * token)
Definition at line 1040 of file l_script.c.
 {
     token_t tok;
     if (!PS_ReadToken(script, &tok)) return 0;
     //if the type matches
     if (tok.type == type &&
             (tok.subtype & subtype) == subtype)
     {
         Com_Memcpy(token, &tok, sizeof(token_t));
         return 1;
     } //end if
     //token is not available
     script->script_p = script->lastscript_p;
     return 0;
 } //end of the function PS_CheckTokenType
PS_ExpectAnyToken()
int PS_ExpectAnyToken (script_t * script, token_t * token)
Definition at line 1005 of file l_script.c.
 {
     if (!PS_ReadToken(script, token))
     {
         ScriptError(script, "couldn't read expected token");
         return 0;
     } //end if
     else
     {
         return 1;
     } //end else
 } //end of the function PS_ExpectAnyToken
Referenced by ReadSignedFloat(), and ReadSignedInt().
PS_ExpectTokenString()
int PS_ExpectTokenString (script_t * script, char * string)
Definition at line 922 of file l_script.c.
 {
     token_t token;
     if (!PS_ReadToken(script, &token))
     {
         ScriptError(script, "couldn't find expected %s", string);
         return 0;
     } //end if
     if (strcmp(token.string, string))
     {
         ScriptError(script, "expected %s, found %s", string, token.string);
         return 0;
     } //end if
     return 1;
 } //end of the function PS_ExpectToken
PS_ExpectTokenType()
int PS_ExpectTokenType (script_t * script, int type, int subtype, token_t * token)
Definition at line 945 of file l_script.c.
 {
     char str[MAX_TOKEN];
     if (!PS_ReadToken(script, token))
     {
         ScriptError(script, "couldn't read expected token");
         return 0;
     } //end if
     if (token->type != type)
     {
         strcpy(str, "");
         if (type == TT_STRING) strcpy(str, "string");
         if (type == TT_LITERAL) strcpy(str, "literal");
         if (type == TT_NUMBER) strcpy(str, "number");
         if (type == TT_NAME) strcpy(str, "name");
         if (type == TT_PUNCTUATION) strcpy(str, "punctuation");
         ScriptError(script, "expected a %s, found %s", str, token->string);
         return 0;
     } //end if
     if (token->type == TT_NUMBER)
     {
         if ((token->subtype & subtype) != subtype)
         {
             strcpy(str, "");
             if (subtype & TT_DECIMAL) strcpy(str, "decimal");
             if (subtype & TT_HEX) strcpy(str, "hex");
             if (subtype & TT_OCTAL) strcpy(str, "octal");
             if (subtype & TT_BINARY) strcpy(str, "binary");
             if (subtype & TT_LONG) strcat(str, " long");
             if (subtype & TT_UNSIGNED) strcat(str, " unsigned");
             if (subtype & TT_FLOAT) strcat(str, " float");
             if (subtype & TT_INTEGER) strcat(str, " integer");
             ScriptError(script, "expected %s, found %s", str, token->string);
             return 0;
         } //end if
     } //end if
     else if (token->type == TT_PUNCTUATION)
     {
         if (subtype < 0)
         {
             ScriptError(script, "BUG: wrong punctuation subtype");
             return 0;
         } //end if
         if (token->subtype != subtype)
         {
             ScriptError(script, "expected %s, found %s",
                             script->punctuations[subtype].p, token->string);
             return 0;
         } //end if
     } //end else if
     return 1;
 } //end of the function PS_ExpectTokenType
Referenced by AAS_ParseBSPEntities().
PS_NextWhiteSpaceChar()
char PS_NextWhiteSpaceChar (script_t * script)
Definition at line 1100 of file l_script.c.
 {
     if (script->whitespace_p != script->endwhitespace_p)
     {
         return *script->whitespace_p++;
     } //end if
     else
     {
         return 0;
     } //end else
 } //end of the function PS_NextWhiteSpaceChar
PS_ReadToken()
int PS_ReadToken (script_t * script, token_t * token)
Definition at line 848 of file l_script.c.
 {
     //if there is a token available (from UnreadToken)
     if (script->tokenavailable)
     {
         script->tokenavailable = 0;
         Com_Memcpy(token, &script->token, sizeof(token_t));
         return 1;
     } //end if
     //save script pointer
     script->lastscript_p = script->script_p;
     //save line counter
     script->lastline = script->line;
     //clear the token stuff
     Com_Memset(token, 0, sizeof(token_t));
     //start of the white space
     script->whitespace_p = script->script_p;
     token->whitespace_p = script->script_p;
     //read unusefull stuff
     if (!PS_ReadWhiteSpace(script)) return 0;
     //end of the white space
     script->endwhitespace_p = script->script_p;
     token->endwhitespace_p = script->script_p;
     //line the token is on
     token->line = script->line;
     //number of lines crossed before token
     token->linescrossed = script->line - script->lastline;
     //if there is a leading double quote
     if (*script->script_p == '\"')
     {
         if (!PS_ReadString(script, token, '\"')) return 0;
     } //end if
     //if a literal
     else if (*script->script_p == '\'')
     {
         //if (!PS_ReadLiteral(script, token)) return 0;
         if (!PS_ReadString(script, token, '\'')) return 0;
     } //end if
     //if there is a number
     else if ((*script->script_p >= '0' && *script->script_p <= '9') ||
                 (*script->script_p == '.' &&
                 (*(script->script_p + 1) >= '0' && *(script->script_p + 1) <= '9')))
     {
         if (!PS_ReadNumber(script, token)) return 0;
     } //end if
     //if this is a primitive script
     else if (script->flags & SCFL_PRIMITIVE)
     {
         return PS_ReadPrimitive(script, token);
     } //end else if
     //if there is a name
     else if ((*script->script_p >= 'a' && *script->script_p <= 'z') ||
         (*script->script_p >= 'A' && *script->script_p <= 'Z') ||
         *script->script_p == '_')
     {
         if (!PS_ReadName(script, token)) return 0;
     } //end if
     //check for punctuations
     else if (!PS_ReadPunctuation(script, token))
     {
         ScriptError(script, "can't read token");
         return 0;
     } //end if
     //copy the token into the script structure
     Com_Memcpy(&script->token, token, sizeof(token_t));
     //successfully read a token
     return 1;
 } //end of the function PS_ReadToken
Referenced by AAS_ParseBSPEntities(), PC_ReadSourceToken(), PS_CheckTokenString(), PS_CheckTokenType(), PS_ExpectAnyToken(), PS_ExpectTokenString(), PS_ExpectTokenType(), and PS_SkipUntilString().
PS_SetBaseFolder()
void PS_SetBaseFolder (char * path)
Definition at line 1440 of file l_script.c.
 {
 #ifdef BOTLIB
     Com_sprintf(basefolder, sizeof(basefolder), "%s", path);
 #endif
 } //end of the function PS_SetBaseFolder
Referenced by PC_LoadSourceHandle(), and PC_SetBaseFolder().
PS_SkipUntilString()
int PS_SkipUntilString (script_t * script, char * string)
Definition at line 1062 of file l_script.c.
 {
     token_t token;
     while(PS_ReadToken(script, &token))
     {
         if (!strcmp(token.string, string)) return 1;
     } //end while
     return 0;
 } //end of the function PS_SkipUntilString
PS_UnreadLastToken()
void PS_UnreadLastToken (script_t * script)
Definition at line 1078 of file l_script.c.
 {
     script->tokenavailable = 1;
 } //end of the function UnreadLastToken
PS_UnreadToken()
void PS_UnreadToken (script_t * script, token_t * token)
Definition at line 1088 of file l_script.c.
 {
     Com_Memcpy(&script->token, token, sizeof(token_t));
     script->tokenavailable = 1;
 } //end of the function UnreadToken
PunctuationFromNum()
char* PunctuationFromNum (script_t * script, int num)
Definition at line 213 of file l_script.c.
 {
     int i;
     for (i = 0; script->punctuations[i].p; i++)
     {
         if (script->punctuations[i].n == num) return script->punctuations[i].p;
     } //end for
     return "unknown punctuation";
 } //end of the function PunctuationFromNum
Referenced by PC_EvaluateTokens().
ReadSignedFloat()
float ReadSignedFloat (script_t * script)
Definition at line 1151 of file l_script.c.
 {
     token_t token;
     float sign = 1.0;
     PS_ExpectAnyToken(script, &token);
     if (!strcmp(token.string, "-"))
     {
         if(!PS_ExpectAnyToken(script, &token))
         {
             ScriptError(script, "Missing float value");
             return 0;
         }
         sign = -1.0;
     }
     if (token.type != TT_NUMBER)
     {
         ScriptError(script, "expected float value, found %s", token.string);
         return 0;
     }
     return sign * token.floatvalue;
 } //end of the function ReadSignedFloat
ReadSignedInt()
signed long int ReadSignedInt (script_t * script)
Definition at line 1182 of file l_script.c.
 {
     token_t token;
     signed long int sign = 1;
     PS_ExpectAnyToken(script, &token);
     if (!strcmp(token.string, "-"))
     {
         if(!PS_ExpectAnyToken(script, &token))
         {
             ScriptError(script, "Missing integer value");
             return 0;
         }
         sign = -1;
     }
     if (token.type != TT_NUMBER || token.subtype == TT_FLOAT)
     {
         ScriptError(script, "expected integer value, found %s", token.string);
         return 0;
     }
     return sign * token.intvalue;
 } //end of the function ReadSignedInt
ResetScript()
void ResetScript (script_t * script)
Definition at line 1233 of file l_script.c.
 {
     //pointer in script buffer
     script->script_p = script->buffer;
     //pointer in script buffer before reading token
     script->lastscript_p = script->buffer;
     //begin of white space
     script->whitespace_p = NULL;
     //end of white space
     script->endwhitespace_p = NULL;
     //set if there's a token available in script->token
     script->tokenavailable = 0;
     //
     script->line = 1;
     script->lastline = 1;
     //clear the saved token
     Com_Memset(&script->token, 0, sizeof(token_t));
 } //end of the function ResetScript
ScriptError()
void QDECL ScriptError (script_t * script, char * str, ...)
ScriptWarning()
void QDECL void QDECL ScriptWarning (script_t * script, char * str, ...)
SetScriptFlags()
void SetScriptFlags (script_t * script, int flags)
Definition at line 1213 of file l_script.c.
 {
     script->flags = flags;
 } //end of the function SetScriptFlags
Referenced by AAS_ParseBSPEntities().
SetScriptPunctuations()
void SetScriptPunctuations (script_t * script, punctuation_t * p)
Definition at line 281 of file l_script.c.
 {
 #ifdef PUNCTABLE
     if (p) PS_CreatePunctuationTable(script, p);
     else  PS_CreatePunctuationTable(script, default_punctuations);
 #endif //PUNCTABLE
     if (p) script->punctuations = p;
     else script->punctuations = default_punctuations;
 } //end of the function SetScriptPunctuations
Referenced by LoadScriptFile(), and LoadScriptMemory().
StripDoubleQuotes()
void StripDoubleQuotes (char * string)
Definition at line 1117 of file l_script.c.
 {
     if (*string == '\"')
     {
         memmove(string, string+1, strlen(string));
     } //end if
     if (string[strlen(string)-1] == '\"')
     {
         string[strlen(string)-1] = '\0';
     } //end if
 } //end of the function StripDoubleQuotes
Referenced by AAS_ParseBSPEntities(), BotLoadCharacterFromFile(), BotLoadChatMessage(), BotLoadInitialChat(), BotLoadMatchPieces(), BotLoadReplyChat(), BotLoadSynonyms(), LoadItemConfig(), PC_Directive_include(), PC_ReadTokenHandle(), ReadString(), and ReadWeightConfig().
StripSingleQuotes()
void StripSingleQuotes (char * string)
Definition at line 1134 of file l_script.c.
 {
     if (*string == '\'')
     {
         memmove(string, string+1, strlen(string));
     } //end if
     if (string[strlen(string)-1] == '\'')
     {
         string[strlen(string)-1] = '\0';
     } //end if
 } //end of the function StripSingleQuotes
Referenced by ReadChar().