ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ai_move.h File Reference
be_ai_move.h File Reference
Classes
struct bot_initmove_s
struct bot_moveresult_s
struct bot_avoidspot_s
Macros
#define MOVE_WALK 1
#define MOVE_CROUCH 2
#define MOVE_JUMP 4
#define MOVE_GRAPPLE 8
#define MOVE_ROCKETJUMP 16
#define MOVE_BFGJUMP 32
#define MFL_BARRIERJUMP 1
#define MFL_ONGROUND 2
#define MFL_SWIMMING 4
#define MFL_AGAINSTLADDER 8
#define MFL_WATERJUMP 16
#define MFL_TELEPORTED 32
#define MFL_GRAPPLEPULL 64
#define MFL_ACTIVEGRAPPLE 128
#define MFL_GRAPPLERESET 256
#define MFL_WALK 512
#define MOVERESULT_MOVEMENTVIEW 1
#define MOVERESULT_SWIMVIEW 2
#define MOVERESULT_WAITING 4
#define MOVERESULT_MOVEMENTVIEWSET 8
#define MOVERESULT_MOVEMENTWEAPON 16
#define MOVERESULT_ONTOPOFOBSTACLE 32
#define MOVERESULT_ONTOPOF_FUNCBOB 64
#define MOVERESULT_ONTOPOF_ELEVATOR 128
#define MOVERESULT_BLOCKEDBYAVOIDSPOT 256
#define MAX_AVOIDREACH 1
#define MAX_AVOIDSPOTS 32
#define AVOID_CLEAR 0
#define AVOID_ALWAYS 1
#define AVOID_DONTBLOCK 2
#define RESULTTYPE_ELEVATORUP 1
#define RESULTTYPE_WAITFORFUNCBOBBING 2
#define RESULTTYPE_BADGRAPPLEPATH 4
#define RESULTTYPE_INSOLIDAREA 8
#define bot_moveresult_t_cleared(x) bot_moveresult_t (x) = {0, 0, 0, 0, 0, 0, 0, {0, 0, 0}, {0, 0, 0}}
Typedefs
typedef struct bot_initmove_s bot_initmove_t
typedef struct bot_moveresult_s bot_moveresult_t
typedef struct bot_avoidspot_s bot_avoidspot_t
Functions
void BotResetMoveState (int movestate)
void BotMoveToGoal (bot_moveresult_t *result, int movestate, bot_goal_t *goal, int travelflags)
int BotMoveInDirection (int movestate, vec3_t dir, float speed, int type)
void BotResetAvoidReach (int movestate)
void BotResetLastAvoidReach (int movestate)
int BotReachabilityArea (vec3_t origin, int client)
int BotMovementViewTarget (int movestate, bot_goal_t *goal, int travelflags, float lookahead, vec3_t target)
int BotPredictVisiblePosition (vec3_t origin, int areanum, bot_goal_t *goal, int travelflags, vec3_t target)
int BotAllocMoveState (void)
void BotFreeMoveState (int handle)
void BotInitMoveState (int handle, bot_initmove_t *initmove)
void BotAddAvoidSpot (int movestate, vec3_t origin, float radius, int type)
void BotSetBrushModelTypes (void)
int BotSetupMoveAI (void)
void BotShutdownMoveAI (void)
Macro Definition Documentation
AVOID_ALWAYS
#define AVOID_ALWAYS 1
Definition at line 66 of file be_ai_move.h.
AVOID_CLEAR
#define AVOID_CLEAR 0
Definition at line 65 of file be_ai_move.h.
AVOID_DONTBLOCK
#define AVOID_DONTBLOCK 2
Definition at line 67 of file be_ai_move.h.
bot_moveresult_t_cleared
#define bot_moveresult_t_cleared (x) bot_moveresult_t (x) = {0, 0, 0, 0, 0, 0, 0, {0, 0, 0}, {0, 0, 0}}
Definition at line 103 of file be_ai_move.h.
MAX_AVOIDREACH
#define MAX_AVOIDREACH 1
Definition at line 62 of file be_ai_move.h.
MAX_AVOIDSPOTS
#define MAX_AVOIDSPOTS 32
Definition at line 63 of file be_ai_move.h.
MFL_ACTIVEGRAPPLE
#define MFL_ACTIVEGRAPPLE 128
Definition at line 48 of file be_ai_move.h.
MFL_AGAINSTLADDER
#define MFL_AGAINSTLADDER 8
Definition at line 44 of file be_ai_move.h.
MFL_BARRIERJUMP
#define MFL_BARRIERJUMP 1
Definition at line 41 of file be_ai_move.h.
MFL_GRAPPLEPULL
#define MFL_GRAPPLEPULL 64
Definition at line 47 of file be_ai_move.h.
MFL_GRAPPLERESET
#define MFL_GRAPPLERESET 256
Definition at line 49 of file be_ai_move.h.
MFL_ONGROUND
#define MFL_ONGROUND 2
Definition at line 42 of file be_ai_move.h.
MFL_SWIMMING
#define MFL_SWIMMING 4
Definition at line 43 of file be_ai_move.h.
MFL_TELEPORTED
#define MFL_TELEPORTED 32
Definition at line 46 of file be_ai_move.h.
MFL_WALK
#define MFL_WALK 512
Definition at line 50 of file be_ai_move.h.
MFL_WATERJUMP
#define MFL_WATERJUMP 16
Definition at line 45 of file be_ai_move.h.
MOVE_BFGJUMP
#define MOVE_BFGJUMP 32
Definition at line 39 of file be_ai_move.h.
MOVE_CROUCH
#define MOVE_CROUCH 2
Definition at line 35 of file be_ai_move.h.
MOVE_GRAPPLE
#define MOVE_GRAPPLE 8
Definition at line 37 of file be_ai_move.h.
MOVE_JUMP
#define MOVE_JUMP 4
Definition at line 36 of file be_ai_move.h.
MOVE_ROCKETJUMP
#define MOVE_ROCKETJUMP 16
Definition at line 38 of file be_ai_move.h.
MOVE_WALK
#define MOVE_WALK 1
Definition at line 34 of file be_ai_move.h.
MOVERESULT_BLOCKEDBYAVOIDSPOT
#define MOVERESULT_BLOCKEDBYAVOIDSPOT 256
Definition at line 60 of file be_ai_move.h.
MOVERESULT_MOVEMENTVIEW
#define MOVERESULT_MOVEMENTVIEW 1
Definition at line 52 of file be_ai_move.h.
MOVERESULT_MOVEMENTVIEWSET
#define MOVERESULT_MOVEMENTVIEWSET 8
Definition at line 55 of file be_ai_move.h.
MOVERESULT_MOVEMENTWEAPON
#define MOVERESULT_MOVEMENTWEAPON 16
Definition at line 56 of file be_ai_move.h.
MOVERESULT_ONTOPOF_ELEVATOR
#define MOVERESULT_ONTOPOF_ELEVATOR 128
Definition at line 59 of file be_ai_move.h.
MOVERESULT_ONTOPOF_FUNCBOB
#define MOVERESULT_ONTOPOF_FUNCBOB 64
Definition at line 58 of file be_ai_move.h.
MOVERESULT_ONTOPOFOBSTACLE
#define MOVERESULT_ONTOPOFOBSTACLE 32
Definition at line 57 of file be_ai_move.h.
MOVERESULT_SWIMVIEW
#define MOVERESULT_SWIMVIEW 2
Definition at line 53 of file be_ai_move.h.
MOVERESULT_WAITING
#define MOVERESULT_WAITING 4
Definition at line 54 of file be_ai_move.h.
RESULTTYPE_BADGRAPPLEPATH
#define RESULTTYPE_BADGRAPPLEPATH 4
Definition at line 71 of file be_ai_move.h.
RESULTTYPE_ELEVATORUP
#define RESULTTYPE_ELEVATORUP 1
Definition at line 69 of file be_ai_move.h.
RESULTTYPE_INSOLIDAREA
#define RESULTTYPE_INSOLIDAREA 8
Definition at line 72 of file be_ai_move.h.
RESULTTYPE_WAITFORFUNCBOBBING
#define RESULTTYPE_WAITFORFUNCBOBBING 2
Definition at line 70 of file be_ai_move.h.
Typedef Documentation
bot_avoidspot_t
typedef struct bot_avoidspot_s bot_avoidspot_t
bot_initmove_t
typedef struct bot_initmove_s bot_initmove_t
bot_moveresult_t
typedef struct bot_moveresult_s bot_moveresult_t
Function Documentation
BotAddAvoidSpot()
void BotAddAvoidSpot (int movestate, vec3_t origin, float radius, int type)
Definition at line 717 of file be_ai_move.c.
 {
     bot_movestate_t *ms;
     ms = BotMoveStateFromHandle(movestate);
     if (!ms) return;
     if (type == AVOID_CLEAR)
     {
         ms->numavoidspots = 0;
         return;
     } //end if
     if (ms->numavoidspots >= MAX_AVOIDSPOTS)
         return;
     VectorCopy(origin, ms->avoidspots[ms->numavoidspots].origin);
     ms->avoidspots[ms->numavoidspots].radius = radius;
     ms->avoidspots[ms->numavoidspots].type = type;
     ms->numavoidspots++;
 } //end of the function BotAddAvoidSpot
References AVOID_CLEAR, bot_movestate_s::avoidspots, BotMoveStateFromHandle(), MAX_AVOIDSPOTS, bot_movestate_s::numavoidspots, bot_avoidspot_s::origin, bot_avoidspot_s::radius, bot_avoidspot_s::type, and VectorCopy.
Referenced by Init_AI_Export().
BotAllocMoveState()
int BotAllocMoveState (void)
Definition at line 125 of file be_ai_move.c.
 {
     int i;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (!botmovestates[i])
         {
             botmovestates[i] = GetClearedMemory(sizeof(bot_movestate_t));
             return i;
         } //end if
     } //end for
     return 0;
 } //end of the function BotAllocMoveState
References botmovestates, GetClearedMemory(), and MAX_CLIENTS.
Referenced by Init_AI_Export().
BotFreeMoveState()
void BotFreeMoveState (int handle)
Definition at line 145 of file be_ai_move.c.
 {
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "move state handle %d out of range\n", handle);
         return;
     } //end if
     if (!botmovestates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid move state %d\n", handle);
         return;
     } //end if
     FreeMemory(botmovestates[handle]);
     botmovestates[handle] = NULL;
 } //end of the function BotFreeMoveState
References botimport, botmovestates, FreeMemory(), MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by Init_AI_Export().
BotInitMoveState()
void BotInitMoveState (int handle, bot_initmove_t * initmove)
Definition at line 186 of file be_ai_move.c.
 {
     bot_movestate_t *ms;
     ms = BotMoveStateFromHandle(handle);
     if (!ms) return;
     VectorCopy(initmove->origin, ms->origin);
     VectorCopy(initmove->velocity, ms->velocity);
     VectorCopy(initmove->viewoffset, ms->viewoffset);
     ms->entitynum = initmove->entitynum;
     ms->client = initmove->client;
     ms->thinktime = initmove->thinktime;
     ms->presencetype = initmove->presencetype;
     VectorCopy(initmove->viewangles, ms->viewangles);
     //
     ms->moveflags &= ~MFL_ONGROUND;
     if (initmove->or_moveflags & MFL_ONGROUND) ms->moveflags |= MFL_ONGROUND;
     ms->moveflags &= ~MFL_TELEPORTED;
     if (initmove->or_moveflags & MFL_TELEPORTED) ms->moveflags |= MFL_TELEPORTED;
     ms->moveflags &= ~MFL_WATERJUMP;
     if (initmove->or_moveflags & MFL_WATERJUMP) ms->moveflags |= MFL_WATERJUMP;
     ms->moveflags &= ~MFL_WALK;
     if (initmove->or_moveflags & MFL_WALK) ms->moveflags |= MFL_WALK;
     ms->moveflags &= ~MFL_GRAPPLEPULL;
     if (initmove->or_moveflags & MFL_GRAPPLEPULL) ms->moveflags |= MFL_GRAPPLEPULL;
 } //end of the function BotInitMoveState
References BotMoveStateFromHandle(), bot_movestate_s::client, bot_initmove_s::client, bot_movestate_s::entitynum, bot_initmove_s::entitynum, MFL_GRAPPLEPULL, MFL_ONGROUND, MFL_TELEPORTED, MFL_WALK, MFL_WATERJUMP, bot_movestate_s::moveflags, bot_initmove_s::or_moveflags, bot_movestate_s::origin, bot_initmove_s::origin, bot_movestate_s::presencetype, bot_initmove_s::presencetype, bot_movestate_s::thinktime, bot_initmove_s::thinktime, VectorCopy, bot_movestate_s::velocity, bot_initmove_s::velocity, bot_movestate_s::viewangles, bot_initmove_s::viewangles, bot_movestate_s::viewoffset, and bot_initmove_s::viewoffset.
Referenced by Init_AI_Export().
BotMoveInDirection()
int BotMoveInDirection (int movestate, vec3_t dir, float speed, int type)
Definition at line 1228 of file be_ai_move.c.
 {
     bot_movestate_t *ms;
     ms = BotMoveStateFromHandle(movestate);
     if (!ms) return qfalse;
     //if swimming
     if (AAS_Swimming(ms->origin))
     {
         return BotSwimInDirection(ms, dir, speed, type);
     } //end if
     else
     {
         return BotWalkInDirection(ms, dir, speed, type);
     } //end else
 } //end of the function BotMoveInDirection
References AAS_Swimming(), BotMoveStateFromHandle(), BotSwimInDirection(), BotWalkInDirection(), bot_movestate_s::origin, and qfalse.
Referenced by Init_AI_Export().
BotMovementViewTarget()
int BotMovementViewTarget (int movestate, bot_goal_t * goal, int travelflags, float lookahead, vec3_t target)
Definition at line 840 of file be_ai_move.c.
 {
     aas_reachability_t reach;
     int reachnum, lastareanum;
     bot_movestate_t *ms;
     vec3_t end;
     float dist;
     ms = BotMoveStateFromHandle(movestate);
     if (!ms) return qfalse;
     //if the bot has no goal or no last reachability
     if (!ms->lastreachnum || !goal) return qfalse;
     reachnum = ms->lastreachnum;
     VectorCopy(ms->origin, end);
     lastareanum = ms->lastareanum;
     dist = 0;
     while(reachnum && dist < lookahead)
     {
         AAS_ReachabilityFromNum(reachnum, &reach);
         if (BotAddToTarget(end, reach.start, lookahead, &dist, target)) return qtrue;
         //never look beyond teleporters
         if ((reach.traveltype & TRAVELTYPE_MASK) == TRAVEL_TELEPORT) return qtrue;
         //never look beyond the weapon jump point
         if ((reach.traveltype & TRAVELTYPE_MASK) == TRAVEL_ROCKETJUMP) return qtrue;
         if ((reach.traveltype & TRAVELTYPE_MASK) == TRAVEL_BFGJUMP) return qtrue;
         //don't add jump pad distances
         if ((reach.traveltype & TRAVELTYPE_MASK) != TRAVEL_JUMPPAD &&
             (reach.traveltype & TRAVELTYPE_MASK) != TRAVEL_ELEVATOR &&
             (reach.traveltype & TRAVELTYPE_MASK) != TRAVEL_FUNCBOB)
         {
             if (BotAddToTarget(reach.start, reach.end, lookahead, &dist, target)) return qtrue;
         } //end if
         reachnum = BotGetReachabilityToGoal(reach.end, reach.areanum,
                         ms->lastgoalareanum, lastareanum,
                             ms->avoidreach, ms->avoidreachtimes, ms->avoidreachtries,
                                     goal, travelflags, NULL, 0, NULL);
         VectorCopy(reach.end, end);
         lastareanum = reach.areanum;
         if (lastareanum == goal->areanum)
         {
             BotAddToTarget(reach.end, goal->origin, lookahead, &dist, target);
             return qtrue;
         } //end if
     } //end while
     //
     return qfalse;
 } //end of the function BotMovementViewTarget
References AAS_ReachabilityFromNum(), bot_goal_s::areanum, aas_reachability_s::areanum, bot_movestate_s::avoidreach, bot_movestate_s::avoidreachtimes, bot_movestate_s::avoidreachtries, BotAddToTarget(), BotGetReachabilityToGoal(), BotMoveStateFromHandle(), aas_reachability_s::end, bot_movestate_s::lastareanum, bot_movestate_s::lastgoalareanum, bot_movestate_s::lastreachnum, NULL, bot_goal_s::origin, bot_movestate_s::origin, qfalse, qtrue, aas_reachability_s::start, TRAVEL_BFGJUMP, TRAVEL_ELEVATOR, TRAVEL_FUNCBOB, TRAVEL_JUMPPAD, TRAVEL_ROCKETJUMP, TRAVEL_TELEPORT, aas_reachability_s::traveltype, TRAVELTYPE_MASK, and VectorCopy.
Referenced by Init_AI_Export().
BotMoveToGoal()
void BotMoveToGoal (bot_moveresult_t * result, int movestate, bot_goal_t * goal, int travelflags)
Definition at line 3003 of file be_ai_move.c.
 {
     int reachnum, lastreachnum, foundjumppad, ent, resultflags;
     aas_reachability_t reach, lastreach;
     bot_movestate_t *ms;
     //vec3_t mins, maxs, up = {0, 0, 1};
     //bsp_trace_t trace;
     //static int debugline;
     result->failure = qfalse;
     result->type = 0;
     result->blocked = qfalse;
     result->blockentity = 0;
     result->traveltype = 0;
     result->flags = 0;
     //
     ms = BotMoveStateFromHandle(movestate);
     if (!ms) return;
     //reset the grapple before testing if the bot has a valid goal
     //because the bot could lose all its goals when stuck to a wall
     BotResetGrapple(ms);
     //
     if (!goal)
     {
 #ifdef DEBUG
         botimport.Print(PRT_MESSAGE, "client %d: movetogoal -> no goal\n", ms->client);
 #endif //DEBUG
         result->failure = qtrue;
         return;
     } //end if
     //botimport.Print(PRT_MESSAGE, "numavoidreach = %d\n", ms->numavoidreach);
     //remove some of the move flags
     ms->moveflags &= ~(MFL_SWIMMING|MFL_AGAINSTLADDER);
     //set some of the move flags
     //NOTE: the MFL_ONGROUND flag is also set in the higher AI
     if (AAS_OnGround(ms->origin, ms->presencetype, ms->entitynum)) ms->moveflags |= MFL_ONGROUND;
     //
     if (ms->moveflags & MFL_ONGROUND)
     {
         int modeltype, modelnum;
         ent = BotOnTopOfEntity(ms);
         if (ent != -1)
         {
             modelnum = AAS_EntityModelindex(ent);
             if (modelnum >= 0 && modelnum < MAX_MODELS)
             {
                 modeltype = modeltypes[modelnum];
                 if (modeltype == MODELTYPE_FUNC_PLAT)
                 {
                     AAS_ReachabilityFromNum(ms->lastreachnum, &reach);
                     //if the bot is Not using the elevator
                     if ((reach.traveltype & TRAVELTYPE_MASK) != TRAVEL_ELEVATOR ||
                         //NOTE: the face number is the plat model number
                         (reach.facenum & 0x0000FFFF) != modelnum)
                     {
                         reachnum = AAS_NextModelReachability(0, modelnum);
                         if (reachnum)
{
                             //botimport.Print(PRT_MESSAGE, "client %d: accidentally ended up on func_plat\n", ms->client);
                             AAS_ReachabilityFromNum(reachnum, &reach);
                             ms->lastreachnum = reachnum;
                             ms->reachability_time = AAS_Time() + BotReachabilityTime(&reach);
                         } //end if
                         else
{
                             if (botDeveloper)
{
                                 botimport.Print(PRT_MESSAGE, "client %d: on func_plat without reachability\n", ms->client);
                             } //end if
                             result->blocked = qtrue;
                             result->blockentity = ent;
                             result->flags |= MOVERESULT_ONTOPOFOBSTACLE;
                             return;
                         } //end else
                     } //end if
                     result->flags |= MOVERESULT_ONTOPOF_ELEVATOR;
                 } //end if
                 else if (modeltype == MODELTYPE_FUNC_BOB)
                 {
                     AAS_ReachabilityFromNum(ms->lastreachnum, &reach);
                     //if the bot is Not using the func bobbing
                     if ((reach.traveltype & TRAVELTYPE_MASK) != TRAVEL_FUNCBOB ||
                         //NOTE: the face number is the func_bobbing model number
                         (reach.facenum & 0x0000FFFF) != modelnum)
                     {
                         reachnum = AAS_NextModelReachability(0, modelnum);
                         if (reachnum)
{
                             //botimport.Print(PRT_MESSAGE, "client %d: accidentally ended up on func_bobbing\n", ms->client);
                             AAS_ReachabilityFromNum(reachnum, &reach);
                             ms->lastreachnum = reachnum;
                             ms->reachability_time = AAS_Time() + BotReachabilityTime(&reach);
                         } //end if
                         else
{
                             if (botDeveloper)
{
                                 botimport.Print(PRT_MESSAGE, "client %d: on func_bobbing without reachability\n", ms->client);
                             } //end if
                             result->blocked = qtrue;
                             result->blockentity = ent;
                             result->flags |= MOVERESULT_ONTOPOFOBSTACLE;
                             return;
                         } //end else
                     } //end if
                     result->flags |= MOVERESULT_ONTOPOF_FUNCBOB;
                 } //end if
                 else if (modeltype == MODELTYPE_FUNC_STATIC || modeltype == MODELTYPE_FUNC_DOOR)
                 {
                     // check if ontop of a door bridge ?
                     ms->areanum = BotFuzzyPointReachabilityArea(ms->origin);
                     // if not in a reachability area
                     if (!AAS_AreaReachability(ms->areanum))
                     {
                         result->blocked = qtrue;
                         result->blockentity = ent;
                         result->flags |= MOVERESULT_ONTOPOFOBSTACLE;
                         return;
                     } //end if
                 } //end else if
                 else
                 {
                     result->blocked = qtrue;
                     result->blockentity = ent;
                     result->flags |= MOVERESULT_ONTOPOFOBSTACLE;
                     return;
                 } //end else
             } //end if
         } //end if
     } //end if
     //if swimming
     if (AAS_Swimming(ms->origin)) ms->moveflags |= MFL_SWIMMING;
     //if against a ladder
     if (AAS_AgainstLadder(ms->origin)) ms->moveflags |= MFL_AGAINSTLADDER;
     //if the bot is on the ground, swimming or against a ladder
     if (ms->moveflags & (MFL_ONGROUND|MFL_SWIMMING|MFL_AGAINSTLADDER))
     {
         //botimport.Print(PRT_MESSAGE, "%s: onground, swimming or against ladder\n", ClientName(ms->entitynum-1));
         //
         AAS_ReachabilityFromNum(ms->lastreachnum, &lastreach);
         //reachability area the bot is in
         //ms->areanum = BotReachabilityArea(ms->origin, ((lastreach.traveltype & TRAVELTYPE_MASK) != TRAVEL_ELEVATOR));
         ms->areanum = BotFuzzyPointReachabilityArea(ms->origin);
         //
         if ( !ms->areanum )
         {
             result->failure = qtrue;
             result->blocked = qtrue;
             result->blockentity = 0;
             result->type = RESULTTYPE_INSOLIDAREA;
             return;
         } //end if
         //if the bot is in the goal area
         if (ms->areanum == goal->areanum)
         {
             *result = BotMoveInGoalArea(ms, goal);
             return;
         } //end if
         //assume we can use the reachability from the last frame
         reachnum = ms->lastreachnum;
         //if there is a last reachability
         if (reachnum)
         {
             AAS_ReachabilityFromNum(reachnum, &reach);
             //check if the reachability is still valid
             if (!(AAS_TravelFlagForType(reach.traveltype) & travelflags))
             {
                 reachnum = 0;
             } //end if
             //special grapple hook case
             else if ((reach.traveltype & TRAVELTYPE_MASK) == TRAVEL_GRAPPLEHOOK)
             {
                 if (ms->reachability_time < AAS_Time() ||
                     (ms->moveflags & MFL_GRAPPLERESET))
                 {
                     reachnum = 0;
                 } //end if
             } //end if
             //special elevator case
             else if ((reach.traveltype & TRAVELTYPE_MASK) == TRAVEL_ELEVATOR ||
                 (reach.traveltype & TRAVELTYPE_MASK) == TRAVEL_FUNCBOB)
             {
                 if ((result->flags & MOVERESULT_ONTOPOF_ELEVATOR) ||
                     (result->flags & MOVERESULT_ONTOPOF_FUNCBOB))
                 {
                     ms->reachability_time = AAS_Time() + 5;
                 } //end if
                 //if the bot was going for an elevator and reached the reachability area
                 if (ms->areanum == reach.areanum ||
                     ms->reachability_time < AAS_Time())
                 {
                     reachnum = 0;
                 } //end if
             } //end if
             else
             {
 #ifdef DEBUG
                 if (botDeveloper)
                 {
                     if (ms->reachability_time < AAS_Time())
                     {
                         botimport.Print(PRT_MESSAGE, "client %d: reachability timeout in ", ms->client);
                         AAS_PrintTravelType(reach.traveltype & TRAVELTYPE_MASK);
                         botimport.Print(PRT_MESSAGE, "\n");
                     } //end if
                     /*
                     if (ms->lastareanum != ms->areanum)
                     {
                         botimport.Print(PRT_MESSAGE, "changed from area %d to %d\n", ms->lastareanum, ms->areanum);
                     } //end if*/
                 } //end if
 #endif //DEBUG
                 //if the goal area changed or the reachability timed out
                 //or the area changed
                 if (ms->lastgoalareanum != goal->areanum ||
                         ms->reachability_time < AAS_Time() ||
                         ms->lastareanum != ms->areanum)
                 {
                     reachnum = 0;
                     //botimport.Print(PRT_MESSAGE, "area change or timeout\n");
                 } //end else if
             } //end else
         } //end if
         resultflags = 0;
         //if the bot needs a new reachability
         if (!reachnum)
         {
             //if the area has no reachability links
             if (!AAS_AreaReachability(ms->areanum))
             {
 #ifdef DEBUG
                 if (botDeveloper)
                 {
                     botimport.Print(PRT_MESSAGE, "area %d no reachability\n", ms->areanum);
                 } //end if
 #endif //DEBUG
             } //end if
             //get a new reachability leading towards the goal
             reachnum = BotGetReachabilityToGoal(ms->origin, ms->areanum,
                                 ms->lastgoalareanum, ms->lastareanum,
                                             ms->avoidreach, ms->avoidreachtimes, ms->avoidreachtries,
                                                         goal, travelflags,
                                                                 ms->avoidspots, ms->numavoidspots, &resultflags);
             //the area number the reachability starts in
             ms->reachareanum = ms->areanum;
             //reset some state variables
             ms->jumpreach = 0;                      //for TRAVEL_JUMP
             ms->moveflags &= ~MFL_GRAPPLERESET; //for TRAVEL_GRAPPLEHOOK
             //if there is a reachability to the goal
             if (reachnum)
             {
                 AAS_ReachabilityFromNum(reachnum, &reach);
                 //set a timeout for this reachability
                 ms->reachability_time = AAS_Time() + BotReachabilityTime(&reach);
                 //
 #ifdef AVOIDREACH
                 //add the reachability to the reachabilities to avoid for a while
                 BotAddToAvoidReach(ms, reachnum, AVOIDREACH_TIME);
 #endif //AVOIDREACH
             } //end if
 #ifdef DEBUG
             else if (botDeveloper)
             {
                 botimport.Print(PRT_MESSAGE, "goal not reachable\n");
                 Com_Memset(&reach, 0, sizeof(aas_reachability_t)); //make compiler happy
             } //end else
             if (botDeveloper)
             {
                 //if still going for the same goal
                 if (ms->lastgoalareanum == goal->areanum)
                 {
                     if (ms->lastareanum == reach.areanum)
                     {
                         botimport.Print(PRT_MESSAGE, "same goal, going back to previous area\n");
                     } //end if
                 } //end if
             } //end if
 #endif //DEBUG
         } //end else
         //
         ms->lastreachnum = reachnum;
         ms->lastgoalareanum = goal->areanum;
         ms->lastareanum = ms->areanum;
         //if the bot has a reachability
         if (reachnum)
         {
             //get the reachability from the number
             AAS_ReachabilityFromNum(reachnum, &reach);
             result->traveltype = reach.traveltype;
             //
 #ifdef DEBUG_AI_MOVE
             AAS_ClearShownDebugLines();
             AAS_PrintTravelType(reach.traveltype & TRAVELTYPE_MASK);
             AAS_ShowReachability(&reach);
 #endif //DEBUG_AI_MOVE
             //
 #ifdef DEBUG
             //botimport.Print(PRT_MESSAGE, "client %d: ", ms->client);
             //AAS_PrintTravelType(reach.traveltype);
             //botimport.Print(PRT_MESSAGE, "\n");
 #endif //DEBUG
             switch(reach.traveltype & TRAVELTYPE_MASK)
             {
                 case TRAVEL_WALK: *result = BotTravel_Walk(ms, &reach); break;
                 case TRAVEL_CROUCH: *result = BotTravel_Crouch(ms, &reach); break;
                 case TRAVEL_BARRIERJUMP: *result = BotTravel_BarrierJump(ms, &reach); break;
                 case TRAVEL_LADDER: *result = BotTravel_Ladder(ms, &reach); break;
                 case TRAVEL_WALKOFFLEDGE: *result = BotTravel_WalkOffLedge(ms, &reach); break;
                 case TRAVEL_JUMP: *result = BotTravel_Jump(ms, &reach); break;
                 case TRAVEL_SWIM: *result = BotTravel_Swim(ms, &reach); break;
                 case TRAVEL_WATERJUMP: *result = BotTravel_WaterJump(ms, &reach); break;
                 case TRAVEL_TELEPORT: *result = BotTravel_Teleport(ms, &reach); break;
                 case TRAVEL_ELEVATOR: *result = BotTravel_Elevator(ms, &reach); break;
                 case TRAVEL_GRAPPLEHOOK: *result = BotTravel_Grapple(ms, &reach); break;
                 case TRAVEL_ROCKETJUMP: *result = BotTravel_RocketJump(ms, &reach); break;
                 case TRAVEL_BFGJUMP: *result = BotTravel_BFGJump(ms, &reach); break;
                 case TRAVEL_JUMPPAD: *result = BotTravel_JumpPad(ms, &reach); break;
                 case TRAVEL_FUNCBOB: *result = BotTravel_FuncBobbing(ms, &reach); break;
                 default:
                 {
                     botimport.Print(PRT_FATAL, "travel type %d not implemented yet\n", (reach.traveltype & TRAVELTYPE_MASK));
                     break;
                 } //end case
             } //end switch
             result->traveltype = reach.traveltype;
             result->flags |= resultflags;
         } //end if
         else
         {
             result->failure = qtrue;
             result->flags |= resultflags;
             Com_Memset(&reach, 0, sizeof(aas_reachability_t));
         } //end else
 #ifdef DEBUG
         if (botDeveloper)
         {
             if (result->failure)
             {
                 botimport.Print(PRT_MESSAGE, "client %d: movement failure in ", ms->client);
                 AAS_PrintTravelType(reach.traveltype & TRAVELTYPE_MASK);
                 botimport.Print(PRT_MESSAGE, "\n");
             } //end if
         } //end if
 #endif //DEBUG
     } //end if
     else
     {
         int i, numareas, areas[16];
         vec3_t end;
         //special handling of jump pads when the bot uses a jump pad without knowing it
         foundjumppad = qfalse;
         VectorMA(ms->origin, -2 * ms->thinktime, ms->velocity, end);
         numareas = AAS_TraceAreas(ms->origin, end, areas, NULL, 16);
         for (i = numareas-1; i >= 0; i--)
         {
             if (AAS_AreaJumpPad(areas[i]))
             {
                 //botimport.Print(PRT_MESSAGE, "client %d used a jumppad without knowing, area %d\n", ms->client, areas[i]);
                 foundjumppad = qtrue;
                 lastreachnum = BotGetReachabilityToGoal(end, areas[i],
                             ms->lastgoalareanum, ms->lastareanum,
                             ms->avoidreach, ms->avoidreachtimes, ms->avoidreachtries,
                             goal, TFL_JUMPPAD, ms->avoidspots, ms->numavoidspots, NULL);
                 if (lastreachnum)
                 {
                     ms->lastreachnum = lastreachnum;
                     ms->lastareanum = areas[i];
                     //botimport.Print(PRT_MESSAGE, "found jumppad reachability\n");
                     break;
                 } //end if
                 else
                 {
                     for (lastreachnum = AAS_NextAreaReachability(areas[i], 0); lastreachnum;
                         lastreachnum = AAS_NextAreaReachability(areas[i], lastreachnum))
                     {
                         //get the reachability from the number
                         AAS_ReachabilityFromNum(lastreachnum, &reach);
                         if ((reach.traveltype & TRAVELTYPE_MASK) == TRAVEL_JUMPPAD)
{
                             ms->lastreachnum = lastreachnum;
                             ms->lastareanum = areas[i];
                             //botimport.Print(PRT_MESSAGE, "found jumppad reachability hard!!\n");
                         } //end if
                     } //end for
                     if (lastreachnum) break;
                 } //end else
             } //end if
         } //end for
         if (botDeveloper)
         {
             //if a jumppad is found with the trace but no reachability is found
             if (foundjumppad && !ms->lastreachnum)
             {
                 botimport.Print(PRT_MESSAGE, "client %d didn't find jumppad reachability\n", ms->client);
             } //end if
         } //end if
         //
         if (ms->lastreachnum)
         {
             //botimport.Print(PRT_MESSAGE, "%s: NOT onground, swimming or against ladder\n", ClientName(ms->entitynum-1));
             AAS_ReachabilityFromNum(ms->lastreachnum, &reach);
             result->traveltype = reach.traveltype;
 #ifdef DEBUG
             //botimport.Print(PRT_MESSAGE, "client %d finish: ", ms->client);
             //AAS_PrintTravelType(reach.traveltype & TRAVELTYPE_MASK);
             //botimport.Print(PRT_MESSAGE, "\n");
 #endif //DEBUG
             //
             switch(reach.traveltype & TRAVELTYPE_MASK)
             {
                 case TRAVEL_WALK: *result = BotTravel_Walk(ms, &reach); break;//BotFinishTravel_Walk(ms, &reach); break;
                 case TRAVEL_CROUCH: /*do nothing*/ break;
                 case TRAVEL_BARRIERJUMP: *result = BotFinishTravel_BarrierJump(ms, &reach); break;
                 case TRAVEL_LADDER: *result = BotTravel_Ladder(ms, &reach); break;
                 case TRAVEL_WALKOFFLEDGE: *result = BotFinishTravel_WalkOffLedge(ms, &reach); break;
                 case TRAVEL_JUMP: *result = BotFinishTravel_Jump(ms, &reach); break;
                 case TRAVEL_SWIM: *result = BotTravel_Swim(ms, &reach); break;
                 case TRAVEL_WATERJUMP: *result = BotFinishTravel_WaterJump(ms, &reach); break;
                 case TRAVEL_TELEPORT: /*do nothing*/ break;
                 case TRAVEL_ELEVATOR: *result = BotFinishTravel_Elevator(ms, &reach); break;
                 case TRAVEL_GRAPPLEHOOK: *result = BotTravel_Grapple(ms, &reach); break;
                 case TRAVEL_ROCKETJUMP:
                 case TRAVEL_BFGJUMP: *result = BotFinishTravel_WeaponJump(ms, &reach); break;
                 case TRAVEL_JUMPPAD: *result = BotFinishTravel_JumpPad(ms, &reach); break;
                 case TRAVEL_FUNCBOB: *result = BotFinishTravel_FuncBobbing(ms, &reach); break;
                 default:
                 {
                     botimport.Print(PRT_FATAL, "(last) travel type %d not implemented yet\n", (reach.traveltype & TRAVELTYPE_MASK));
                     break;
                 } //end case
             } //end switch
             result->traveltype = reach.traveltype;
 #ifdef DEBUG
             if (botDeveloper)
             {
                 if (result->failure)
                 {
                     botimport.Print(PRT_MESSAGE, "client %d: movement failure in finish ", ms->client);
                     AAS_PrintTravelType(reach.traveltype & TRAVELTYPE_MASK);
                     botimport.Print(PRT_MESSAGE, "\n");
                 } //end if
             } //end if
 #endif //DEBUG
         } //end if
     } //end else
     //FIXME: is it right to do this here?
     if (result->blocked) ms->reachability_time -= 10 * ms->thinktime;
     //copy the last origin
     VectorCopy(ms->origin, ms->lastorigin);
 } //end of the function BotMoveToGoal
References AAS_AgainstLadder(), AAS_AreaJumpPad(), AAS_AreaReachability(), AAS_ClearShownDebugLines(), AAS_EntityModelindex(), AAS_NextAreaReachability(), AAS_NextModelReachability(), AAS_OnGround(), AAS_PrintTravelType(), AAS_ReachabilityFromNum(), AAS_ShowReachability(), AAS_Swimming(), AAS_Time(), AAS_TraceAreas(), AAS_TravelFlagForType(), bot_goal_s::areanum, bot_movestate_s::areanum, aas_reachability_s::areanum, bot_movestate_s::avoidreach, AVOIDREACH_TIME, bot_movestate_s::avoidreachtimes, bot_movestate_s::avoidreachtries, bot_movestate_s::avoidspots, bot_moveresult_s::blocked, bot_moveresult_s::blockentity, BotAddToAvoidReach(), botDeveloper, BotFinishTravel_BarrierJump(), BotFinishTravel_Elevator(), BotFinishTravel_FuncBobbing(), BotFinishTravel_Jump(), BotFinishTravel_JumpPad(), BotFinishTravel_WalkOffLedge(), BotFinishTravel_WaterJump(), BotFinishTravel_WeaponJump(), BotFuzzyPointReachabilityArea(), BotGetReachabilityToGoal(), botimport, BotMoveInGoalArea(), BotMoveStateFromHandle(), BotOnTopOfEntity(), BotReachabilityTime(), BotResetGrapple(), BotTravel_BarrierJump(), BotTravel_BFGJump(), BotTravel_Crouch(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotTravel_Jump(), BotTravel_JumpPad(), BotTravel_Ladder(), BotTravel_RocketJump(), BotTravel_Swim(), BotTravel_Teleport(), BotTravel_Walk(), BotTravel_WalkOffLedge(), BotTravel_WaterJump(), bot_movestate_s::client, Com_Memset, bot_movestate_s::entitynum, aas_reachability_s::facenum, bot_moveresult_s::failure, bot_moveresult_s::flags, bot_movestate_s::jumpreach, bot_movestate_s::lastareanum, bot_movestate_s::lastgoalareanum, bot_movestate_s::lastorigin, bot_movestate_s::lastreachnum, MAX_MODELS, MFL_AGAINSTLADDER, MFL_GRAPPLERESET, MFL_ONGROUND, MFL_SWIMMING, MODELTYPE_FUNC_BOB, MODELTYPE_FUNC_DOOR, MODELTYPE_FUNC_PLAT, MODELTYPE_FUNC_STATIC, modeltypes, bot_movestate_s::moveflags, MOVERESULT_ONTOPOF_ELEVATOR, MOVERESULT_ONTOPOF_FUNCBOB, MOVERESULT_ONTOPOFOBSTACLE, NULL, bot_movestate_s::numavoidspots, bot_movestate_s::origin, bot_movestate_s::presencetype, PRT_FATAL, PRT_MESSAGE, qfalse, qtrue, bot_movestate_s::reachability_time, bot_movestate_s::reachareanum, RESULTTYPE_INSOLIDAREA, TFL_JUMPPAD, bot_movestate_s::thinktime, TRAVEL_BARRIERJUMP, TRAVEL_BFGJUMP, TRAVEL_CROUCH, TRAVEL_ELEVATOR, TRAVEL_FUNCBOB, TRAVEL_GRAPPLEHOOK, TRAVEL_JUMP, TRAVEL_JUMPPAD, TRAVEL_LADDER, TRAVEL_ROCKETJUMP, TRAVEL_SWIM, TRAVEL_TELEPORT, TRAVEL_WALK, TRAVEL_WALKOFFLEDGE, TRAVEL_WATERJUMP, bot_moveresult_s::traveltype, aas_reachability_s::traveltype, TRAVELTYPE_MASK, bot_moveresult_s::type, VectorCopy, VectorMA, and bot_movestate_s::velocity.
Referenced by Init_AI_Export().
BotPredictVisiblePosition()
int BotPredictVisiblePosition (vec3_t origin, int areanum, bot_goal_t * goal, int travelflags, vec3_t target)
Definition at line 908 of file be_ai_move.c.
 {
     aas_reachability_t reach;
     int reachnum, lastgoalareanum, lastareanum, i;
     int avoidreach[MAX_AVOIDREACH];
     float avoidreachtimes[MAX_AVOIDREACH];
     int avoidreachtries[MAX_AVOIDREACH];
     vec3_t end;
     //if the bot has no goal or no last reachability
     if (!goal) return qfalse;
     //if the areanum is not valid
     if (!areanum) return qfalse;
     //if the goal areanum is not valid
     if (!goal->areanum) return qfalse;
     Com_Memset(avoidreach, 0, MAX_AVOIDREACH * sizeof(int));
     lastgoalareanum = goal->areanum;
     lastareanum = areanum;
     VectorCopy(origin, end);
     //only do 20 hops
     for (i = 0; i < 20 && (areanum != goal->areanum); i++)
     {
         //
         reachnum = BotGetReachabilityToGoal(end, areanum,
                         lastgoalareanum, lastareanum,
                             avoidreach, avoidreachtimes, avoidreachtries,
                                     goal, travelflags, NULL, 0, NULL);
         if (!reachnum) return qfalse;
         AAS_ReachabilityFromNum(reachnum, &reach);
         //
         if (BotVisible(goal->entitynum, goal->origin, reach.start))
         {
             VectorCopy(reach.start, target);
             return qtrue;
         } //end if
         //
         if (BotVisible(goal->entitynum, goal->origin, reach.end))
         {
             VectorCopy(reach.end, target);
             return qtrue;
         } //end if
         //
         if (reach.areanum == goal->areanum)
         {
             VectorCopy(reach.end, target);
             return qtrue;
         } //end if
         //
         lastareanum = areanum;
         areanum = reach.areanum;
         VectorCopy(reach.end, end);
         //
     } //end while
     //
     return qfalse;
 } //end of the function BotPredictVisiblePosition
References AAS_ReachabilityFromNum(), bot_goal_s::areanum, aas_reachability_s::areanum, BotGetReachabilityToGoal(), BotVisible(), Com_Memset, aas_reachability_s::end, bot_goal_s::entitynum, MAX_AVOIDREACH, NULL, bot_goal_s::origin, qfalse, qtrue, aas_reachability_s::start, and VectorCopy.
Referenced by Init_AI_Export().
BotReachabilityArea()
int BotReachabilityArea (vec3_t origin, int client)
Definition at line 299 of file be_ai_move.c.
 {
     int modelnum, modeltype, reachnum, areanum;
     aas_reachability_t reach;
     vec3_t org, end, mins, maxs, up = {0, 0, 1};
     bsp_trace_t bsptrace;
     aas_trace_t trace;
     //check if the bot is standing on something
     AAS_PresenceTypeBoundingBox(PRESENCE_CROUCH, mins, maxs);
     VectorMA(origin, -3, up, end);
     bsptrace = AAS_Trace(origin, mins, maxs, end, client, CONTENTS_SOLID|CONTENTS_PLAYERCLIP);
     if (!bsptrace.startsolid && bsptrace.fraction < 1 && bsptrace.ent != ENTITYNUM_NONE)
     {
         //if standing on the world the bot should be in a valid area
         if (bsptrace.ent == ENTITYNUM_WORLD)
         {
             return BotFuzzyPointReachabilityArea(origin);
         } //end if
         modelnum = AAS_EntityModelindex(bsptrace.ent);
         modeltype = modeltypes[modelnum];
         //if standing on a func_plat or func_bobbing then the bot is assumed to be
         //in the area the reachability points to
         if (modeltype == MODELTYPE_FUNC_PLAT || modeltype == MODELTYPE_FUNC_BOB)
         {
             reachnum = AAS_NextModelReachability(0, modelnum);
             if (reachnum)
             {
                 AAS_ReachabilityFromNum(reachnum, &reach);
                 return reach.areanum;
             } //end if
         } //end else if
         //if the bot is swimming the bot should be in a valid area
         if (AAS_Swimming(origin))
         {
             return BotFuzzyPointReachabilityArea(origin);
         } //end if
         //
         areanum = BotFuzzyPointReachabilityArea(origin);
         //if the bot is in an area with reachabilities
         if (areanum && AAS_AreaReachability(areanum)) return areanum;
         //trace down till the ground is hit because the bot is standing on some other entity
         VectorCopy(origin, org);
         VectorCopy(org, end);
         end[2] -= 800;
         trace = AAS_TraceClientBBox(org, end, PRESENCE_CROUCH, -1);
         if (!trace.startsolid)
         {
             VectorCopy(trace.endpos, org);
         } //end if
         //
         return BotFuzzyPointReachabilityArea(org);
     } //end if
     //
     return BotFuzzyPointReachabilityArea(origin);
 } //end of the function BotReachabilityArea
References AAS_AreaReachability(), AAS_EntityModelindex(), AAS_NextModelReachability(), AAS_PresenceTypeBoundingBox(), AAS_ReachabilityFromNum(), AAS_Swimming(), AAS_Trace(), AAS_TraceClientBBox(), aas_reachability_s::areanum, BotFuzzyPointReachabilityArea(), CONTENTS_PLAYERCLIP, CONTENTS_SOLID, aas_trace_s::endpos, bsp_trace_s::ent, ENTITYNUM_NONE, ENTITYNUM_WORLD, bsp_trace_s::fraction, MODELTYPE_FUNC_BOB, MODELTYPE_FUNC_PLAT, modeltypes, PRESENCE_CROUCH, aas_trace_s::startsolid, bsp_trace_s::startsolid, up, VectorCopy, and VectorMA.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), and Init_AI_Export().
BotResetAvoidReach()
void BotResetAvoidReach (int movestate)
Definition at line 3465 of file be_ai_move.c.
 {
     bot_movestate_t *ms;
     ms = BotMoveStateFromHandle(movestate);
     if (!ms) return;
     Com_Memset(ms->avoidreach, 0, MAX_AVOIDREACH * sizeof(int));
     Com_Memset(ms->avoidreachtimes, 0, MAX_AVOIDREACH * sizeof(float));
     Com_Memset(ms->avoidreachtries, 0, MAX_AVOIDREACH * sizeof(int));
 } //end of the function BotResetAvoidReach
References bot_movestate_s::avoidreach, bot_movestate_s::avoidreachtimes, bot_movestate_s::avoidreachtries, BotMoveStateFromHandle(), Com_Memset, and MAX_AVOIDREACH.
Referenced by Init_AI_Export().
BotResetLastAvoidReach()
void BotResetLastAvoidReach (int movestate)
Definition at line 3481 of file be_ai_move.c.
 {
     int i, latest;
     float latesttime;
     bot_movestate_t *ms;
     ms = BotMoveStateFromHandle(movestate);
     if (!ms) return;
     latesttime = 0;
     latest = 0;
     for (i = 0; i < MAX_AVOIDREACH; i++)
     {
         if (ms->avoidreachtimes[i] > latesttime)
         {
             latesttime = ms->avoidreachtimes[i];
             latest = i;
         } //end if
     } //end for
     if (latesttime)
     {
         ms->avoidreachtimes[latest] = 0;
         if (ms->avoidreachtries[latest] > 0) ms->avoidreachtries[latest]--;
     } //end if
 } //end of the function BotResetLastAvoidReach
References bot_movestate_s::avoidreachtimes, bot_movestate_s::avoidreachtries, BotMoveStateFromHandle(), and MAX_AVOIDREACH.
Referenced by Init_AI_Export().
BotResetMoveState()
void BotResetMoveState (int movestate)
Definition at line 3511 of file be_ai_move.c.
 {
     bot_movestate_t *ms;
     ms = BotMoveStateFromHandle(movestate);
     if (!ms) return;
     Com_Memset(ms, 0, sizeof(bot_movestate_t));
 } //end of the function BotResetMoveState
References BotMoveStateFromHandle(), and Com_Memset.
Referenced by Init_AI_Export().
BotSetBrushModelTypes()
void BotSetBrushModelTypes (void)
Definition at line 511 of file be_ai_move.c.
 {
     int ent, modelnum;
     char classname[MAX_EPAIRKEY], model[MAX_EPAIRKEY];
     Com_Memset(modeltypes, 0, MAX_MODELS * sizeof(int));
     //
     for (ent = AAS_NextBSPEntity(0); ent; ent = AAS_NextBSPEntity(ent))
     {
         if (!AAS_ValueForBSPEpairKey(ent, "classname", classname, MAX_EPAIRKEY)) continue;
         if (!AAS_ValueForBSPEpairKey(ent, "model", model, MAX_EPAIRKEY)) continue;
         if (model[0]) modelnum = atoi(model+1);
         else modelnum = 0;
         if (modelnum < 0 || modelnum >= MAX_MODELS)
         {
             botimport.Print(PRT_MESSAGE, "entity %s model number out of range\n", classname);
             continue;
         } //end if
         if (!Q_stricmp(classname, "func_bobbing"))
             modeltypes[modelnum] = MODELTYPE_FUNC_BOB;
         else if (!Q_stricmp(classname, "func_plat"))
             modeltypes[modelnum] = MODELTYPE_FUNC_PLAT;
         else if (!Q_stricmp(classname, "func_door"))
             modeltypes[modelnum] = MODELTYPE_FUNC_DOOR;
         else if (!Q_stricmp(classname, "func_static"))
             modeltypes[modelnum] = MODELTYPE_FUNC_STATIC;
     } //end for
 } //end of the function BotSetBrushModelTypes
References AAS_NextBSPEntity(), AAS_ValueForBSPEpairKey(), botimport, Com_Memset, MAX_EPAIRKEY, MAX_MODELS, MODELTYPE_FUNC_BOB, MODELTYPE_FUNC_DOOR, MODELTYPE_FUNC_PLAT, MODELTYPE_FUNC_STATIC, modeltypes, PRT_MESSAGE, and Q_stricmp().
Referenced by BotSetupMoveAI(), and Export_BotLibLoadMap().
BotSetupMoveAI()
int BotSetupMoveAI (void)
Definition at line 3525 of file be_ai_move.c.
 {
     BotSetBrushModelTypes();
     sv_maxstep = LibVar("sv_step", "18");
     sv_maxbarrier = LibVar("sv_maxbarrier", "32");
     sv_gravity = LibVar("sv_gravity", "800");
     weapindex_rocketlauncher = LibVar("weapindex_rocketlauncher", "5");
     weapindex_bfg10k = LibVar("weapindex_bfg10k", "9");
     weapindex_grapple = LibVar("weapindex_grapple", "10");
     entitytypemissile = LibVar("entitytypemissile", "3");
     offhandgrapple = LibVar("offhandgrapple", "0");
     cmd_grappleon = LibVar("cmd_grappleon", "grappleon");
     cmd_grappleoff = LibVar("cmd_grappleoff", "grappleoff");
     return BLERR_NOERROR;
 } //end of the function BotSetupMoveAI
References BLERR_NOERROR, BotSetBrushModelTypes(), cmd_grappleoff, cmd_grappleon, entitytypemissile, LibVar(), offhandgrapple, sv_gravity, sv_maxbarrier, sv_maxstep, weapindex_bfg10k, weapindex_grapple, and weapindex_rocketlauncher.
Referenced by Export_BotLibSetup().
BotShutdownMoveAI()
void BotShutdownMoveAI (void)
Definition at line 3546 of file be_ai_move.c.
 {
     int i;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (botmovestates[i])
         {
             FreeMemory(botmovestates[i]);
             botmovestates[i] = NULL;
         } //end if
     } //end for
 } //end of the function BotShutdownMoveAI
References botmovestates, FreeMemory(), MAX_CLIENTS, and NULL.
Referenced by Export_BotLibShutdown().