ioquake3 doxygen: C:/entry/dev/ioquake3/code/botlib/be_ai_chat.h File Reference
be_ai_chat.h File Reference
Classes
struct bot_consolemessage_s
struct bot_matchvariable_s
struct bot_match_s
Macros
#define MAX_MESSAGE_SIZE 256
#define MAX_CHATTYPE_NAME 32
#define MAX_MATCHVARIABLES 8
#define CHAT_GENDERLESS 0
#define CHAT_GENDERFEMALE 1
#define CHAT_GENDERMALE 2
#define CHAT_ALL 0
#define CHAT_TEAM 1
#define CHAT_TELL 2
Typedefs
typedef struct bot_consolemessage_s bot_consolemessage_t
typedef struct bot_matchvariable_s bot_matchvariable_t
typedef struct bot_match_s bot_match_t
Functions
int BotSetupChatAI (void)
void BotShutdownChatAI (void)
int BotAllocChatState (void)
void BotFreeChatState (int handle)
void BotQueueConsoleMessage (int chatstate, int type, char *message)
void BotRemoveConsoleMessage (int chatstate, int handle)
int BotNextConsoleMessage (int chatstate, bot_consolemessage_t *cm)
int BotNumConsoleMessages (int chatstate)
void BotInitialChat (int chatstate, char *type, int mcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int BotNumInitialChats (int chatstate, char *type)
int BotReplyChat (int chatstate, char *message, int mcontext, int vcontext, char *var0, char *var1, char *var2, char *var3, char *var4, char *var5, char *var6, char *var7)
int BotChatLength (int chatstate)
void BotEnterChat (int chatstate, int clientto, int sendto)
void BotGetChatMessage (int chatstate, char *buf, int size)
int StringContains (char *str1, char *str2, int casesensitive)
int BotFindMatch (char *str, bot_match_t *match, unsigned long int context)
void BotMatchVariable (bot_match_t *match, int variable, char *buf, int size)
void UnifyWhiteSpaces (char *string)
void BotReplaceSynonyms (char *string, unsigned long int context)
int BotLoadChatFile (int chatstate, char *chatfile, char *chatname)
void BotSetChatGender (int chatstate, int gender)
void BotSetChatName (int chatstate, char *name, int client)
Macro Definition Documentation
CHAT_ALL
#define CHAT_ALL 0
Definition at line 40 of file be_ai_chat.h.
CHAT_GENDERFEMALE
#define CHAT_GENDERFEMALE 1
Definition at line 37 of file be_ai_chat.h.
CHAT_GENDERLESS
#define CHAT_GENDERLESS 0
Definition at line 36 of file be_ai_chat.h.
CHAT_GENDERMALE
#define CHAT_GENDERMALE 2
Definition at line 38 of file be_ai_chat.h.
CHAT_TEAM
#define CHAT_TEAM 1
Definition at line 41 of file be_ai_chat.h.
CHAT_TELL
#define CHAT_TELL 2
Definition at line 42 of file be_ai_chat.h.
MAX_CHATTYPE_NAME
#define MAX_CHATTYPE_NAME 32
Definition at line 33 of file be_ai_chat.h.
MAX_MATCHVARIABLES
#define MAX_MATCHVARIABLES 8
Definition at line 34 of file be_ai_chat.h.
MAX_MESSAGE_SIZE
#define MAX_MESSAGE_SIZE 256
Definition at line 32 of file be_ai_chat.h.
Typedef Documentation
bot_consolemessage_t
typedef struct bot_consolemessage_s bot_consolemessage_t
bot_match_t
typedef struct bot_match_s bot_match_t
bot_matchvariable_t
typedef struct bot_matchvariable_s bot_matchvariable_t
Function Documentation
BotAllocChatState()
int BotAllocChatState (void)
Definition at line 2915 of file be_ai_chat.c.
 {
     int i;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (!botchatstates[i])
         {
             botchatstates[i] = GetClearedMemory(sizeof(bot_chatstate_t));
             return i;
         } //end if
     } //end for
     return 0;
 } //end of the function BotAllocChatState
Referenced by Init_AI_Export().
BotChatLength()
int BotChatLength (int chatstate)
Definition at line 2791 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     return strlen(cs->chatmessage);
 } //end of the function BotChatLength
Referenced by Init_AI_Export().
BotEnterChat()
void BotEnterChat (int chatstate, int clientto, int sendto)
Definition at line 2805 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     if (strlen(cs->chatmessage))
     {
         BotRemoveTildes(cs->chatmessage);
         if (LibVarGetValue("bot_testichat")) {
             botimport.Print(PRT_MESSAGE, "%s\n", cs->chatmessage);
         }
         else {
             switch(sendto) {
                 case CHAT_TEAM:
                     EA_Command(cs->client, va("say_team %s", cs->chatmessage));
                     break;
                 case CHAT_TELL:
                     EA_Command(cs->client, va("tell %d %s", clientto, cs->chatmessage));
                     break;
                 default: //CHAT_ALL
                     EA_Command(cs->client, va("say %s", cs->chatmessage));
                     break;
             }
         }
         //clear the chat message from the state
         strcpy(cs->chatmessage, "");
     } //end if
 } //end of the function BotEnterChat
Referenced by Init_AI_Export().
BotFindMatch()
int BotFindMatch (char * str, bot_match_t * match, unsigned long int context)
Definition at line 1454 of file be_ai_chat.c.
 {
     int i;
     bot_matchtemplate_t *ms;
     Q_strncpyz(match->string, str, MAX_MESSAGE_SIZE);
     //remove any trailing enters
     while(strlen(match->string) &&
             match->string[strlen(match->string)-1] == '\n')
     {
         match->string[strlen(match->string)-1] = '\0';
     } //end while
     //compare the string with all the match strings
     for (ms = matchtemplates; ms; ms = ms->next)
     {
         if (!(ms->context & context)) continue;
         //reset the match variable offsets
         for (i = 0; i < MAX_MATCHVARIABLES; i++) match->variables[i].offset = -1;
         //
         if (StringsMatch(ms->first, match))
         {
             match->type = ms->type;
             match->subtype = ms->subtype;
             return qtrue;
         } //end if
     } //end for
     return qfalse;
 } //end of the function BotFindMatch
Referenced by Init_AI_Export().
BotFreeChatState()
void BotFreeChatState (int handle)
Definition at line 2935 of file be_ai_chat.c.
 {
     bot_consolemessage_t m;
     int h;
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "chat state handle %d out of range\n", handle);
         return;
     } //end if
     if (!botchatstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid chat state %d\n", handle);
         return;
     } //end if
     if (LibVarGetValue("bot_reloadcharacters"))
     {
         BotFreeChatFile(handle);
     } //end if
     //free all the console messages left in the chat state
     for (h = BotNextConsoleMessage(handle, &m); h; h = BotNextConsoleMessage(handle, &m))
     {
         //remove the console message
         BotRemoveConsoleMessage(handle, h);
     } //end for
     FreeMemory(botchatstates[handle]);
     botchatstates[handle] = NULL;
 } //end of the function BotFreeChatState
Referenced by BotShutdownChatAI(), and Init_AI_Export().
BotGetChatMessage()
void BotGetChatMessage (int chatstate, char * buf, int size)
Definition at line 2841 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     BotRemoveTildes(cs->chatmessage);
     strncpy(buf, cs->chatmessage, size-1);
     buf[size-1] = '\0';
     //clear the chat message from the state
     strcpy(cs->chatmessage, "");
 } //end of the function BotGetChatMessage
Referenced by Init_AI_Export().
BotInitialChat()
void BotInitialChat (int chatstate, char * type, int mcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 2514 of file be_ai_chat.c.
 {
     char *message;
     int index;
     bot_match_t match;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     //if no chat file is loaded
     if (!cs->chat) return;
     //choose a chat message randomly of the given type
     message = BotChooseInitialChatMessage(cs, type);
     //if there's no message of the given type
     if (!message)
     {
 #ifdef DEBUG
         botimport.Print(PRT_MESSAGE, "no chat messages of type %s\n", type);
 #endif //DEBUG
         return;
     } //end if
     //
     Com_Memset(&match, 0, sizeof(match));
     index = 0;
     if( var0 ) {
         strcat(match.string, var0);
         match.variables[0].offset = index;
         match.variables[0].length = strlen(var0);
         index += strlen(var0);
     }
     if( var1 ) {
         strcat(match.string, var1);
         match.variables[1].offset = index;
         match.variables[1].length = strlen(var1);
         index += strlen(var1);
     }
     if( var2 ) {
         strcat(match.string, var2);
         match.variables[2].offset = index;
         match.variables[2].length = strlen(var2);
         index += strlen(var2);
     }
     if( var3 ) {
         strcat(match.string, var3);
         match.variables[3].offset = index;
         match.variables[3].length = strlen(var3);
         index += strlen(var3);
     }
     if( var4 ) {
         strcat(match.string, var4);
         match.variables[4].offset = index;
         match.variables[4].length = strlen(var4);
         index += strlen(var4);
     }
     if( var5 ) {
         strcat(match.string, var5);
         match.variables[5].offset = index;
         match.variables[5].length = strlen(var5);
         index += strlen(var5);
     }
     if( var6 ) {
         strcat(match.string, var6);
         match.variables[6].offset = index;
         match.variables[6].length = strlen(var6);
         index += strlen(var6);
     }
     if( var7 ) {
         strcat(match.string, var7);
         match.variables[7].offset = index;
         match.variables[7].length = strlen(var7);
     }
     //
     BotConstructChatMessage(cs, message, mcontext, &match, 0, qfalse);
 } //end of the function BotInitialChat
Referenced by Init_AI_Export().
BotLoadChatFile()
int BotLoadChatFile (int chatstate, char * chatfile, char * chatname)
Definition at line 2222 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     int n, avail = 0;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return BLERR_CANNOTLOADICHAT;
     BotFreeChatFile(chatstate);
     if (!LibVarGetValue("bot_reloadcharacters"))
     {
         avail = -1;
         for( n = 0; n < MAX_CLIENTS; n++ ) {
             if( !ichatdata[n] ) {
                 if( avail == -1 ) {
                     avail = n;
                 }
                 continue;
             }
             if( strcmp( chatfile, ichatdata[n]->filename ) != 0 ) {
                 continue;
             }
             if( strcmp( chatname, ichatdata[n]->chatname ) != 0 ) {
                 continue;
             }
             cs->chat = ichatdata[n]->chat;
         //      botimport.Print( PRT_MESSAGE, "retained %s from %s\n", chatname, chatfile );
             return BLERR_NOERROR;
         }
         if( avail == -1 ) {
             botimport.Print(PRT_FATAL, "ichatdata table full; couldn't load chat %s from %s\n", chatname, chatfile);
             return BLERR_CANNOTLOADICHAT;
         }
     }
     cs->chat = BotLoadInitialChat(chatfile, chatname);
     if (!cs->chat)
     {
         botimport.Print(PRT_FATAL, "couldn't load chat %s from %s\n", chatname, chatfile);
         return BLERR_CANNOTLOADICHAT;
     } //end if
     if (!LibVarGetValue("bot_reloadcharacters"))
     {
         ichatdata[avail] = GetClearedMemory( sizeof(bot_ichatdata_t) );
         ichatdata[avail]->chat = cs->chat;
         Q_strncpyz( ichatdata[avail]->chatname, chatname, sizeof(ichatdata[avail]->chatname) );
         Q_strncpyz( ichatdata[avail]->filename, chatfile, sizeof(ichatdata[avail]->filename) );
     } //end if
     return BLERR_NOERROR;
 } //end of the function BotLoadChatFile
Referenced by Init_AI_Export().
BotMatchVariable()
void BotMatchVariable (bot_match_t * match, int variable, char * buf, int size)
Definition at line 1488 of file be_ai_chat.c.
 {
     if (variable < 0 || variable >= MAX_MATCHVARIABLES)
     {
         botimport.Print(PRT_FATAL, "BotMatchVariable: variable out of range\n");
         strcpy(buf, "");
         return;
     } //end if
     if (match->variables[variable].offset >= 0)
     {
         if (match->variables[variable].length < size)
             size = match->variables[variable].length+1;
         assert( match->variables[variable].offset >= 0 );
         strncpy(buf, &match->string[ (int) match->variables[variable].offset], size-1);
         buf[size-1] = '\0';
     } //end if
     else
     {
         strcpy(buf, "");
     } //end else
 } //end of the function BotMatchVariable
Referenced by Init_AI_Export().
BotNextConsoleMessage()
int BotNextConsoleMessage (int chatstate, bot_consolemessage_t * cm)
Definition at line 367 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     bot_consolemessage_t *firstmsg;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     if ((firstmsg = cs->firstmessage))
     {
         cm->handle = firstmsg->handle;
         cm->time = firstmsg->time;
         cm->type = firstmsg->type;
         Q_strncpyz(cm->message, firstmsg->message,
                sizeof(cm->message));
         /* We omit setting the two pointers in cm because pointer
          * size in the VM differs between the size in the engine on
          * 64 bit machines, which would lead to a buffer overflow if
          * this functions is called from the VM. The pointers are
          * of no interest to functions calling
          * BotNextConsoleMessage anyways.
          */
         return cm->handle;
     } //end if
     return 0;
 } //end of the function BotConsoleMessage
Referenced by BotFreeChatState(), and Init_AI_Export().
BotNumConsoleMessages()
int BotNumConsoleMessages (int chatstate)
Definition at line 400 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     return cs->numconsolemessages;
 } //end of the function BotNumConsoleMessages
Referenced by Init_AI_Export().
BotNumInitialChats()
int BotNumInitialChats (int chatstate, char * type)
Definition at line 2487 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     bot_chattype_t *t;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return 0;
     for (t = cs->chat->types; t; t = t->next)
     {
         if (!Q_stricmp(t->name, type))
         {
             if (LibVarGetValue("bot_testichat")) {
                 botimport.Print(PRT_MESSAGE, "%s has %d chat lines\n", type, t->numchatmessages);
                 botimport.Print(PRT_MESSAGE, "-------------------\n");
             }
             return t->numchatmessages;
         } //end if
     } //end for
     return 0;
 } //end of the function BotNumInitialChats
Referenced by Init_AI_Export().
BotQueueConsoleMessage()
void BotQueueConsoleMessage (int chatstate, int type, char * message)
Definition at line 326 of file be_ai_chat.c.
 {
     bot_consolemessage_t *m;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     m = AllocConsoleMessage();
     if (!m)
     {
         botimport.Print(PRT_ERROR, "empty console message heap\n");
         return;
     } //end if
     cs->handle++;
     if (cs->handle <= 0 || cs->handle > 8192) cs->handle = 1;
     m->handle = cs->handle;
     m->time = AAS_Time();
     m->type = type;
     Q_strncpyz(m->message, message, MAX_MESSAGE_SIZE);
     m->next = NULL;
     if (cs->lastmessage)
     {
         cs->lastmessage->next = m;
         m->prev = cs->lastmessage;
         cs->lastmessage = m;
     } //end if
     else
     {
         cs->lastmessage = m;
         cs->firstmessage = m;
         m->prev = NULL;
     } //end if
     cs->numconsolemessages++;
 } //end of the function BotQueueConsoleMessage
Referenced by Init_AI_Export().
BotRemoveConsoleMessage()
void BotRemoveConsoleMessage (int chatstate, int handle)
Definition at line 296 of file be_ai_chat.c.
 {
     bot_consolemessage_t *m, *nextm;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     for (m = cs->firstmessage; m; m = nextm)
     {
         nextm = m->next;
         if (m->handle == handle)
         {
             if (m->next) m->next->prev = m->prev;
             else cs->lastmessage = m->prev;
             if (m->prev) m->prev->next = m->next;
             else cs->firstmessage = m->next;
             FreeConsoleMessage(m);
             cs->numconsolemessages--;
             break;
         } //end if
     } //end for
 } //end of the function BotRemoveConsoleMessage
Referenced by BotFreeChatState(), and Init_AI_Export().
BotReplaceSynonyms()
void BotReplaceSynonyms (char * string, unsigned long int context)
Definition at line 777 of file be_ai_chat.c.
 {
     bot_synonymlist_t *syn;
     bot_synonym_t *synonym;
     for (syn = synonyms; syn; syn = syn->next)
     {
         if (!(syn->context & context)) continue;
         for (synonym = syn->firstsynonym->next; synonym; synonym = synonym->next)
         {
             StringReplaceWords(string, synonym->string, syn->firstsynonym->string);
         } //end for
     } //end for
 } //end of the function BotReplaceSynonyms
Referenced by BotExpandChatMessage(), and Init_AI_Export().
BotReplyChat()
int BotReplyChat (int chatstate, char * message, int mcontext, int vcontext, char * var0, char * var1, char * var2, char * var3, char * var4, char * var5, char * var6, char * var7)
Definition at line 2635 of file be_ai_chat.c.
 {
     bot_replychat_t *rchat, *bestrchat;
     bot_replychatkey_t *key;
     bot_chatmessage_t *m, *bestchatmessage;
     bot_match_t match, bestmatch;
     int bestpriority, num, found, res, numchatmessages, index;
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return qfalse;
     Com_Memset(&match, 0, sizeof(bot_match_t));
     strcpy(match.string, message);
     bestpriority = -1;
     bestchatmessage = NULL;
     bestrchat = NULL;
     //go through all the reply chats
     for (rchat = replychats; rchat; rchat = rchat->next)
     {
         found = qfalse;
         for (key = rchat->keys; key; key = key->next)
         {
             res = qfalse;
             //get the match result
             if (key->flags & RCKFL_NAME) res = (StringContains(message, cs->name, qfalse) != -1);
             else if (key->flags & RCKFL_BOTNAMES) res = (StringContains(key->string, cs->name, qfalse) != -1);
             else if (key->flags & RCKFL_GENDERFEMALE) res = (cs->gender == CHAT_GENDERFEMALE);
             else if (key->flags & RCKFL_GENDERMALE) res = (cs->gender == CHAT_GENDERMALE);
             else if (key->flags & RCKFL_GENDERLESS) res = (cs->gender == CHAT_GENDERLESS);
             else if (key->flags & RCKFL_VARIABLES) res = StringsMatch(key->match, &match);
             else if (key->flags & RCKFL_STRING) res = (StringContainsWord(message, key->string, qfalse) != NULL);
             //if the key must be present
             if (key->flags & RCKFL_AND)
             {
                 if (!res)
                 {
                     found = qfalse;
                     break;
                 } //end if
             } //end else if
             //if the key must be absent
             else if (key->flags & RCKFL_NOT)
             {
                 if (res)
                 {
                     found = qfalse;
                     break;
                 } //end if
             } //end if
             else if (res)
             {
                 found = qtrue;
             } //end else
         } //end for
         //
         if (found)
         {
             if (rchat->priority > bestpriority)
             {
                 numchatmessages = 0;
                 for (m = rchat->firstchatmessage; m; m = m->next)
                 {
                     if (m->time > AAS_Time()) continue;
                     numchatmessages++;
                 } //end if
                 num = random() * numchatmessages;
                 for (m = rchat->firstchatmessage; m; m = m->next)
                 {
                     if (--num < 0) break;
                     if (m->time > AAS_Time()) continue;
                 } //end for
                 //if the reply chat has a message
                 if (m)
                 {
                     Com_Memcpy(&bestmatch, &match, sizeof(bot_match_t));
                     bestchatmessage = m;
                     bestrchat = rchat;
                     bestpriority = rchat->priority;
                 } //end if
             } //end if
         } //end if
     } //end for
     if (bestchatmessage)
     {
         index = strlen(bestmatch.string);
         if( var0 ) {
             strcat(bestmatch.string, var0);
             bestmatch.variables[0].offset = index;
             bestmatch.variables[0].length = strlen(var0);
             index += strlen(var0);
         }
         if( var1 ) {
             strcat(bestmatch.string, var1);
             bestmatch.variables[1].offset = index;
             bestmatch.variables[1].length = strlen(var1);
             index += strlen(var1);
         }
         if( var2 ) {
             strcat(bestmatch.string, var2);
             bestmatch.variables[2].offset = index;
             bestmatch.variables[2].length = strlen(var2);
             index += strlen(var2);
         }
         if( var3 ) {
             strcat(bestmatch.string, var3);
             bestmatch.variables[3].offset = index;
             bestmatch.variables[3].length = strlen(var3);
             index += strlen(var3);
         }
         if( var4 ) {
             strcat(bestmatch.string, var4);
             bestmatch.variables[4].offset = index;
             bestmatch.variables[4].length = strlen(var4);
             index += strlen(var4);
         }
         if( var5 ) {
             strcat(bestmatch.string, var5);
             bestmatch.variables[5].offset = index;
             bestmatch.variables[5].length = strlen(var5);
             index += strlen(var5);
         }
         if( var6 ) {
             strcat(bestmatch.string, var6);
             bestmatch.variables[6].offset = index;
             bestmatch.variables[6].length = strlen(var6);
             index += strlen(var6);
         }
         if( var7 ) {
             strcat(bestmatch.string, var7);
             bestmatch.variables[7].offset = index;
             bestmatch.variables[7].length = strlen(var7);
         }
         if (LibVarGetValue("bot_testrchat"))
         {
             for (m = bestrchat->firstchatmessage; m; m = m->next)
             {
                 BotConstructChatMessage(cs, m->chatmessage, mcontext, &bestmatch, vcontext, qtrue);
                 BotRemoveTildes(cs->chatmessage);
                 botimport.Print(PRT_MESSAGE, "%s\n", cs->chatmessage);
             } //end if
         } //end if
         else
         {
             bestchatmessage->time = AAS_Time() + CHATMESSAGE_RECENTTIME;
             BotConstructChatMessage(cs, bestchatmessage->chatmessage, mcontext, &bestmatch, vcontext, qtrue);
         } //end else
         return qtrue;
     } //end if
     return qfalse;
 } //end of the function BotReplyChat
Referenced by Init_AI_Export().
BotSetChatGender()
void BotSetChatGender (int chatstate, int gender)
Definition at line 2860 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     switch(gender)
     {
         case CHAT_GENDERFEMALE: cs->gender = CHAT_GENDERFEMALE; break;
         case CHAT_GENDERMALE: cs->gender = CHAT_GENDERMALE; break;
         default: cs->gender = CHAT_GENDERLESS; break;
     } //end switch
 } //end of the function BotSetChatGender
Referenced by Init_AI_Export().
BotSetChatName()
void BotSetChatName (int chatstate, char * name, int client)
Definition at line 2879 of file be_ai_chat.c.
 {
     bot_chatstate_t *cs;
     cs = BotChatStateFromHandle(chatstate);
     if (!cs) return;
     cs->client = client;
     Com_Memset(cs->name, 0, sizeof(cs->name));
     strncpy(cs->name, name, sizeof(cs->name)-1);
     cs->name[sizeof(cs->name)-1] = '\0';
 } //end of the function BotSetChatName
Referenced by Init_AI_Export().
BotSetupChatAI()
int BotSetupChatAI (void)
Definition at line 2969 of file be_ai_chat.c.
 {
     char *file;
 #ifdef DEBUG
     int starttime = Sys_MilliSeconds();
 #endif //DEBUG
     file = LibVarString("synfile", "syn.c");
     synonyms = BotLoadSynonyms(file);
     file = LibVarString("rndfile", "rnd.c");
     randomstrings = BotLoadRandomStrings(file);
     file = LibVarString("matchfile", "match.c");
     matchtemplates = BotLoadMatchTemplates(file);
     //
     if (!LibVarValue("nochat", "0"))
     {
         file = LibVarString("rchatfile", "rchat.c");
         replychats = BotLoadReplyChat(file);
     } //end if
     InitConsoleMessageHeap();
 #ifdef DEBUG
     botimport.Print(PRT_MESSAGE, "setup chat AI %d msec\n", Sys_MilliSeconds() - starttime);
 #endif //DEBUG
     return BLERR_NOERROR;
 } //end of the function BotSetupChatAI
Referenced by Export_BotLibSetup().
BotShutdownChatAI()
void BotShutdownChatAI (void)
Definition at line 3003 of file be_ai_chat.c.
 {
     int i;
     //free all remaining chat states
     for(i = 0; i < MAX_CLIENTS; i++)
     {
         if (botchatstates[i])
         {
             BotFreeChatState(i);
         } //end if
     } //end for
     //free all cached chats
     for(i = 0; i < MAX_CLIENTS; i++)
     {
         if (ichatdata[i])
         {
             FreeMemory(ichatdata[i]->chat);
             FreeMemory(ichatdata[i]);
             ichatdata[i] = NULL;
         } //end if
     } //end for
     if (consolemessageheap) FreeMemory(consolemessageheap);
     consolemessageheap = NULL;
     if (matchtemplates) BotFreeMatchTemplates(matchtemplates);
     matchtemplates = NULL;
     if (randomstrings) FreeMemory(randomstrings);
     randomstrings = NULL;
     if (synonyms) FreeMemory(synonyms);
     synonyms = NULL;
     if (replychats) BotFreeReplyChat(replychats);
     replychats = NULL;
 } //end of the function BotShutdownChatAI
Referenced by Export_BotLibShutdown().
StringContains()
int StringContains (char * str1, char * str2, int casesensitive)
Definition at line 477 of file be_ai_chat.c.
 {
     int len, i, j, index;
     if (str1 == NULL || str2 == NULL) return -1;
     len = strlen(str1) - strlen(str2);
     index = 0;
     for (i = 0; i <= len; i++, str1++, index++)
     {
         for (j = 0; str2[j]; j++)
         {
             if (casesensitive)
             {
                 if (str1[j] != str2[j]) break;
             } //end if
             else
             {
                 if (toupper(str1[j]) != toupper(str2[j])) break;
             } //end else
         } //end for
         if (!str2[j]) return index;
     } //end for
     return -1;
 } //end of the function StringContains
Referenced by BotCheckValidReplyChatKeySet(), BotReplyChat(), Init_AI_Export(), and StringsMatch().
UnifyWhiteSpaces()
void UnifyWhiteSpaces (char * string)
Definition at line 453 of file be_ai_chat.c.
 {
     char *ptr, *oldptr;
     for (ptr = oldptr = string; *ptr; oldptr = ptr)
     {
         while(*ptr && IsWhiteSpace(*ptr)) ptr++;
         if (ptr > oldptr)
         {
             //if not at the start and not at the end of the string
             //write only one space
             if (oldptr > string && *ptr) *oldptr++ = ' ';
             //remove all other white spaces
             if (ptr > oldptr) memmove(oldptr, ptr, strlen(ptr)+1);
         } //end if
         while(*ptr && !IsWhiteSpace(*ptr)) ptr++;
     } //end while
 } //end of the function UnifyWhiteSpaces
Referenced by Init_AI_Export().