ioquake3 doxygen: C:/entry/dev/ioquake3/code/cgame/cg_effects.c File Reference
cg_effects.c File Reference
#include "cg_local.h"
Macros
#define GIB_VELOCITY 250
#define GIB_JUMP 250
#define EXP_VELOCITY 100
#define EXP_JUMP 150
Functions
void CG_BubbleTrail (vec3_t start, vec3_t end, float spacing)
localEntity_t * CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
void CG_SpawnEffect (vec3_t org)
void CG_ScorePlum (int client, vec3_t org, int score)
localEntity_t * CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
void CG_Bleed (vec3_t origin, int entityNum)
void CG_LaunchGib (vec3_t origin, vec3_t velocity, qhandle_t hModel)
void CG_GibPlayer (vec3_t playerOrigin)
void CG_LaunchExplode (vec3_t origin, vec3_t velocity, qhandle_t hModel)
void CG_BigExplode (vec3_t playerOrigin)
Macro Definition Documentation
EXP_JUMP
#define EXP_JUMP 150
Definition at line 673 of file cg_effects.c.
EXP_VELOCITY
#define EXP_VELOCITY 100
Definition at line 672 of file cg_effects.c.
GIB_JUMP
#define GIB_JUMP 250
Definition at line 563 of file cg_effects.c.
GIB_VELOCITY
#define GIB_VELOCITY 250
Definition at line 562 of file cg_effects.c.
Function Documentation
CG_BigExplode()
void CG_BigExplode (vec3_t playerOrigin)
Definition at line 681 of file cg_effects.c.
{
     vec3_t  origin, velocity;
     if ( !cg_blood.integer ) {
         return;
     }
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*EXP_VELOCITY;
     velocity[1] = crandom()*EXP_VELOCITY;
     velocity[2] = EXP_JUMP + crandom()*EXP_VELOCITY;
     CG_LaunchExplode( origin, velocity, cgs.media.smoke2 );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*EXP_VELOCITY;
     velocity[1] = crandom()*EXP_VELOCITY;
     velocity[2] = EXP_JUMP + crandom()*EXP_VELOCITY;
     CG_LaunchExplode( origin, velocity, cgs.media.smoke2 );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*EXP_VELOCITY*1.5;
     velocity[1] = crandom()*EXP_VELOCITY*1.5;
     velocity[2] = EXP_JUMP + crandom()*EXP_VELOCITY;
     CG_LaunchExplode( origin, velocity, cgs.media.smoke2 );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*EXP_VELOCITY*2.0;
     velocity[1] = crandom()*EXP_VELOCITY*2.0;
     velocity[2] = EXP_JUMP + crandom()*EXP_VELOCITY;
     CG_LaunchExplode( origin, velocity, cgs.media.smoke2 );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*EXP_VELOCITY*2.5;
     velocity[1] = crandom()*EXP_VELOCITY*2.5;
     velocity[2] = EXP_JUMP + crandom()*EXP_VELOCITY;
     CG_LaunchExplode( origin, velocity, cgs.media.smoke2 );
 }
CG_Bleed()
void CG_Bleed (vec3_t origin, int entityNum)
Definition at line 496 of file cg_effects.c.
{
     localEntity_t   *ex;
     if ( !cg_blood.integer ) {
         return;
     }
     ex = CG_AllocLocalEntity();
     ex->leType = LE_EXPLOSION;
     ex->startTime = cg.time;
     ex->endTime = ex->startTime + 500;
     VectorCopy ( origin, ex->refEntity.origin);
     ex->refEntity.reType = RT_SPRITE;
     ex->refEntity.rotation = rand() % 360;
     ex->refEntity.radius = 24;
     ex->refEntity.customShader = cgs.media.bloodExplosionShader;
     // don't show player's own blood in view
     if ( entityNum == cg.snap->ps.clientNum ) {
         ex->refEntity.renderfx |= RF_THIRD_PERSON;
     }
 }
Referenced by CG_Bullet(), and CG_MissileHitPlayer().
CG_BubbleTrail()
void CG_BubbleTrail (vec3_t start, vec3_t end, float spacing)
Definition at line 36 of file cg_effects.c.
{
     vec3_t      move;
     vec3_t      vec;
     float       len;
     int         i;
     if ( cg_noProjectileTrail.integer ) {
         return;
     }
     VectorCopy (start, move);
     VectorSubtract (end, start, vec);
     len = VectorNormalize (vec);
     // advance a random amount first
     i = rand() % (int)spacing;
     VectorMA( move, i, vec, move );
     VectorScale (vec, spacing, vec);
     for ( ; i < len; i += spacing ) {
         localEntity_t   *le;
         refEntity_t     *re;
         le = CG_AllocLocalEntity();
         le->leFlags = LEF_PUFF_DONT_SCALE;
         le->leType = LE_MOVE_SCALE_FADE;
         le->startTime = cg.time;
         le->endTime = cg.time + 1000 + random() * 250;
         le->lifeRate = 1.0 / ( le->endTime - le->startTime );
         re = &le->refEntity;
         re->shaderTime = cg.time / 1000.0f;
         re->reType = RT_SPRITE;
         re->rotation = 0;
         re->radius = 3;
         re->customShader = cgs.media.waterBubbleShader;
         re->shaderRGBA[0] = 0xff;
         re->shaderRGBA[1] = 0xff;
         re->shaderRGBA[2] = 0xff;
         re->shaderRGBA[3] = 0xff;
         le->color[3] = 1.0;
         le->pos.trType = TR_LINEAR;
         le->pos.trTime = cg.time;
         VectorCopy( move, le->pos.trBase );
         le->pos.trDelta[0] = crandom()*5;
         le->pos.trDelta[1] = crandom()*5;
         le->pos.trDelta[2] = crandom()*5 + 6;
         VectorAdd (move, vec, move);
     }
 }
Referenced by CG_Bullet(), CG_RocketTrail(), and CG_ShotgunPellet().
CG_GibPlayer()
void CG_GibPlayer (vec3_t playerOrigin)
Definition at line 564 of file cg_effects.c.
{
     vec3_t  origin, velocity;
     if ( !cg_blood.integer ) {
         return;
     }
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     if ( rand() & 1 ) {
         CG_LaunchGib( origin, velocity, cgs.media.gibSkull );
     } else {
         CG_LaunchGib( origin, velocity, cgs.media.gibBrain );
     }
     // allow gibs to be turned off for speed
     if ( !cg_gibs.integer ) {
         return;
     }
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibAbdomen );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibArm );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibChest );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibFist );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibFoot );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibForearm );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibIntestine );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibLeg );
     VectorCopy( playerOrigin, origin );
     velocity[0] = crandom()*GIB_VELOCITY;
     velocity[1] = crandom()*GIB_VELOCITY;
     velocity[2] = GIB_JUMP + crandom()*GIB_VELOCITY;
     CG_LaunchGib( origin, velocity, cgs.media.gibLeg );
 }
Referenced by CG_EntityEvent().
CG_LaunchExplode()
void CG_LaunchExplode (vec3_t origin, vec3_t velocity, qhandle_t hModel)
Definition at line 646 of file cg_effects.c.
{
     localEntity_t   *le;
     refEntity_t     *re;
     le = CG_AllocLocalEntity();
     re = &le->refEntity;
     le->leType = LE_FRAGMENT;
     le->startTime = cg.time;
     le->endTime = le->startTime + 10000 + random() * 6000;
     VectorCopy( origin, re->origin );
     AxisCopy( axisDefault, re->axis );
     re->hModel = hModel;
     le->pos.trType = TR_GRAVITY;
     VectorCopy( origin, le->pos.trBase );
     VectorCopy( velocity, le->pos.trDelta );
     le->pos.trTime = cg.time;
     le->bounceFactor = 0.1f;
     le->leBounceSoundType = LEBS_BRASS;
     le->leMarkType = LEMT_NONE;
 }
Referenced by CG_BigExplode().
CG_LaunchGib()
void CG_LaunchGib (vec3_t origin, vec3_t velocity, qhandle_t hModel)
Definition at line 529 of file cg_effects.c.
{
     localEntity_t   *le;
     refEntity_t     *re;
     le = CG_AllocLocalEntity();
     re = &le->refEntity;
     le->leType = LE_FRAGMENT;
     le->startTime = cg.time;
     le->endTime = le->startTime + 5000 + random() * 3000;
     VectorCopy( origin, re->origin );
     AxisCopy( axisDefault, re->axis );
     re->hModel = hModel;
     le->pos.trType = TR_GRAVITY;
     VectorCopy( origin, le->pos.trBase );
     VectorCopy( velocity, le->pos.trDelta );
     le->pos.trTime = cg.time;
     le->bounceFactor = 0.6f;
     le->leBounceSoundType = LEBS_BLOOD;
     le->leMarkType = LEMT_BLOOD;
 }
Referenced by CG_GibPlayer().
CG_MakeExplosion()
localEntity_t* CG_MakeExplosion (vec3_t origin, vec3_t dir, qhandle_t hModel, qhandle_t shader, int msec, qboolean isSprite)
Definition at line 433 of file cg_effects.c.
{
     float           ang;
     localEntity_t   *ex;
     int             offset;
     vec3_t          tmpVec, newOrigin;
     if ( msec <= 0 ) {
         CG_Error( "CG_MakeExplosion: msec = %i", msec );
     }
     // skew the time a bit so they aren't all in sync
     offset = rand() & 63;
     ex = CG_AllocLocalEntity();
     if ( isSprite ) {
         ex->leType = LE_SPRITE_EXPLOSION;
         // randomly rotate sprite orientation
         ex->refEntity.rotation = rand() % 360;
         VectorScale( dir, 16, tmpVec );
         VectorAdd( tmpVec, origin, newOrigin );
     } else {
         ex->leType = LE_EXPLOSION;
         VectorCopy( origin, newOrigin );
         // set axis with random rotate
         if ( !dir ) {
             AxisClear( ex->refEntity.axis );
         } else {
             ang = rand() % 360;
             VectorCopy( dir, ex->refEntity.axis[0] );
             RotateAroundDirection( ex->refEntity.axis, ang );
         }
     }
     ex->startTime = cg.time - offset;
     ex->endTime = ex->startTime + msec;
     // bias the time so all shader effects start correctly
     ex->refEntity.shaderTime = ex->startTime / 1000.0f;
     ex->refEntity.hModel = hModel;
     ex->refEntity.customShader = shader;
     // set origin
     VectorCopy( newOrigin, ex->refEntity.origin );
     VectorCopy( newOrigin, ex->refEntity.oldorigin );
     ex->color[0] = ex->color[1] = ex->color[2] = 1.0;
     return ex;
 }
Referenced by CG_MissileHitWall().
CG_ScorePlum()
void CG_ScorePlum (int client, vec3_t org, int score)
Definition at line 387 of file cg_effects.c.
{
     localEntity_t   *le;
     refEntity_t     *re;
     vec3_t          angles;
     static vec3_t lastPos;
     // only visualize for the client that scored
     if (client != cg.predictedPlayerState.clientNum || cg_scorePlum.integer == 0) {
         return;
     }
     le = CG_AllocLocalEntity();
     le->leFlags = 0;
     le->leType = LE_SCOREPLUM;
     le->startTime = cg.time;
     le->endTime = cg.time + 4000;
     le->lifeRate = 1.0 / ( le->endTime - le->startTime );
     le->color[0] = le->color[1] = le->color[2] = le->color[3] = 1.0;
     le->radius = score;
     VectorCopy( org, le->pos.trBase );
     if (org[2] >= lastPos[2] - 20 && org[2] <= lastPos[2] + 20) {
         le->pos.trBase[2] -= 20;
     }
     //CG_Printf( "Plum origin %i %i %i -- %i\n", (int)org[0], (int)org[1], (int)org[2], (int)Distance(org, lastPos));
     VectorCopy(org, lastPos);
     re = &le->refEntity;
     re->reType = RT_SPRITE;
     re->radius = 16;
     VectorClear(angles);
     AnglesToAxis( angles, re->axis );
 }
Referenced by CG_EntityEvent().
CG_SmokePuff()
localEntity_t* CG_SmokePuff (const vec3_t p, const vec3_t vel, float radius, float r, float g, float b, float a, float duration, int startTime, int fadeInTime, int leFlags, qhandle_t hShader)
Definition at line 99 of file cg_effects.c.
{
     static int  seed = 0x92;
     localEntity_t   *le;
     refEntity_t     *re;
 //  int fadeInTime = startTime + duration / 2;
     le = CG_AllocLocalEntity();
     le->leFlags = leFlags;
     le->radius = radius;
     re = &le->refEntity;
     re->rotation = Q_random( &seed ) * 360;
     re->radius = radius;
     re->shaderTime = startTime / 1000.0f;
     le->leType = LE_MOVE_SCALE_FADE;
     le->startTime = startTime;
     le->fadeInTime = fadeInTime;
     le->endTime = startTime + duration;
     if ( fadeInTime > startTime ) {
         le->lifeRate = 1.0 / ( le->endTime - le->fadeInTime );
     }
     else {
         le->lifeRate = 1.0 / ( le->endTime - le->startTime );
     }
     le->color[0] = r;
     le->color[1] = g;
     le->color[2] = b;
     le->color[3] = a;
     le->pos.trType = TR_LINEAR;
     le->pos.trTime = startTime;
     VectorCopy( vel, le->pos.trDelta );
     VectorCopy( p, le->pos.trBase );
     VectorCopy( p, re->origin );
     re->customShader = hShader;
     // rage pro can't alpha fade, so use a different shader
     if ( cgs.glconfig.hardwareType == GLHW_RAGEPRO ) {
         re->customShader = cgs.media.smokePuffRageProShader;
         re->shaderRGBA[0] = 0xff;
         re->shaderRGBA[1] = 0xff;
         re->shaderRGBA[2] = 0xff;
         re->shaderRGBA[3] = 0xff;
     } else {
         re->shaderRGBA[0] = le->color[0] * 0xff;
         re->shaderRGBA[1] = le->color[1] * 0xff;
         re->shaderRGBA[2] = le->color[2] * 0xff;
         re->shaderRGBA[3] = 0xff;
     }
     re->reType = RT_SPRITE;
     re->radius = le->radius;
     return le;
 }
Referenced by CG_BloodTrail(), CG_EntityEvent(), CG_HasteTrail(), CG_RocketTrail(), and CG_ShotgunFire().
CG_SpawnEffect()
void CG_SpawnEffect (vec3_t org)
Definition at line 172 of file cg_effects.c.
{
     localEntity_t   *le;
     refEntity_t     *re;
     le = CG_AllocLocalEntity();
     le->leFlags = 0;
     le->leType = LE_FADE_RGB;
     le->startTime = cg.time;
     le->endTime = cg.time + 500;
     le->lifeRate = 1.0 / ( le->endTime - le->startTime );
     le->color[0] = le->color[1] = le->color[2] = le->color[3] = 1.0;
     re = &le->refEntity;
     re->reType = RT_MODEL;
     re->shaderTime = cg.time / 1000.0f;
 #ifndef MISSIONPACK
     re->customShader = cgs.media.teleportEffectShader;
 #endif
     re->hModel = cgs.media.teleportEffectModel;
     AxisClear( re->axis );
     VectorCopy( org, re->origin );
 #ifdef MISSIONPACK
     re->origin[2] += 16;
 #else
     re->origin[2] -= 24;
 #endif
 }
Referenced by CG_EntityEvent().