ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_route.h File Reference
be_aas_route.h File Reference
Functions
int AAS_TravelFlagForType (int traveltype)
int AAS_AreaContentsTravelFlags (int areanum)
int AAS_NextAreaReachability (int areanum, int reachnum)
void AAS_ReachabilityFromNum (int num, struct aas_reachability_s *reach)
int AAS_RandomGoalArea (int areanum, int travelflags, int *goalareanum, vec3_t goalorigin)
int AAS_EnableRoutingArea (int areanum, int enable)
unsigned short int AAS_AreaTravelTime (int areanum, vec3_t start, vec3_t end)
int AAS_AreaTravelTimeToGoalArea (int areanum, vec3_t origin, int goalareanum, int travelflags)
int AAS_PredictRoute (struct aas_predictroute_s *route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
Function Documentation
AAS_AreaContentsTravelFlags()
int AAS_AreaContentsTravelFlags (int areanum)
Definition at line 391 of file be_aas_route.c.
 {
     return aasworld.areacontentstravelflags[areanum];
 } //end of the function AAS_AreaContentsTravelFlags
Referenced by BotValidTravel().
AAS_AreaTravelTime()
unsigned short int AAS_AreaTravelTime (int areanum, vec3_t start, vec3_t end)
Definition at line 473 of file be_aas_route.c.
 {
     int intdist;
     float dist;
     vec3_t dir;
     VectorSubtract(start, end, dir);
     dist = VectorLength(dir);
     //if crouch only area
     if (AAS_AreaCrouch(areanum)) dist *= DISTANCEFACTOR_CROUCH;
     //if swim area
     else if (AAS_AreaSwim(areanum)) dist *= DISTANCEFACTOR_SWIM;
     //normal walk area
     else dist *= DISTANCEFACTOR_WALK;
     //
     intdist = (int) dist;
     //make sure the distance isn't zero
     if (intdist <= 0) intdist = 1;
     return intdist;
 } //end of the function AAS_AreaTravelTime
Referenced by AAS_AreaRouteToGoalArea(), AAS_CalculateAreaTravelTimes(), AAS_NearestHideArea(), and AAS_PredictRoute().
AAS_AreaTravelTimeToGoalArea()
int AAS_AreaTravelTimeToGoalArea (int areanum, vec3_t origin, int goalareanum, int travelflags)
Definition at line 1775 of file be_aas_route.c.
 {
     int traveltime, reachnum = 0;
     if (AAS_AreaRouteToGoalArea(areanum, origin, goalareanum, travelflags, &traveltime, &reachnum))
     {
         return traveltime;
     }
     return 0;
 } //end of the function AAS_AreaTravelTimeToGoalArea
Referenced by AAS_AlternativeRouteGoals(), AAS_CreateAllRoutingCache(), AAS_RandomGoalArea(), BotChooseLTGItem(), BotChooseNBGItem(), BotExportTest(), BotGetReachabilityToGoal(), and Init_AAS_Export().
AAS_EnableRoutingArea()
int AAS_EnableRoutingArea (int areanum, int enable)
Definition at line 307 of file be_aas_route.c.
 {
     int flags;
     if (areanum <= 0 || areanum >= aasworld.numareas)
     {
         if (botDeveloper)
         {
             botimport.Print(PRT_ERROR, "AAS_EnableRoutingArea: areanum %d out of range\n", areanum);
         } //end if
         return 0;
     } //end if
     flags = aasworld.areasettings[areanum].areaflags & AREA_DISABLED;
     if (enable < 0)
         return !flags;
     if (enable)
         aasworld.areasettings[areanum].areaflags &= ~AREA_DISABLED;
     else
         aasworld.areasettings[areanum].areaflags |= AREA_DISABLED;
     // if the status of the area changed
     if ( (flags & AREA_DISABLED) != (aasworld.areasettings[areanum].areaflags & AREA_DISABLED) )
     {
         //remove all routing cache involving this area
         AAS_RemoveRoutingCacheUsingArea( areanum );
     } //end if
     return !flags;
 } //end of the function AAS_EnableRoutingArea
Referenced by Init_AAS_Export().
AAS_NextAreaReachability()
int AAS_NextAreaReachability (int areanum, int reachnum)
Definition at line 1947 of file be_aas_route.c.
 {
     aas_areasettings_t *settings;
     if (!aasworld.initialized) return 0;
     if (areanum <= 0 || areanum >= aasworld.numareas)
     {
         botimport.Print(PRT_ERROR, "AAS_NextAreaReachability: areanum %d out of range\n", areanum);
         return 0;
     } //end if
     settings = &aasworld.areasettings[areanum];
     if (!reachnum)
     {
         return settings->firstreachablearea;
     } //end if
     if (reachnum < settings->firstreachablearea)
     {
         botimport.Print(PRT_FATAL, "AAS_NextAreaReachability: reachnum < settings->firstreachableara");
         return 0;
     } //end if
     reachnum++;
     if (reachnum >= settings->firstreachablearea + settings->numreachableareas)
     {
         return 0;
     } //end if
     return reachnum;
 } //end of the function AAS_NextAreaReachability
Referenced by BotGetReachabilityToGoal(), and BotMoveToGoal().
AAS_PredictRoute()
int AAS_PredictRoute (struct aas_predictroute_s * route, int areanum, vec3_t origin, int goalareanum, int travelflags, int maxareas, int maxtime, int stopevent, int stopcontents, int stoptfl, int stopareanum)
Definition at line 1808 of file be_aas_route.c.
 {
     int curareanum, reachnum, i, j, testareanum;
     vec3_t curorigin;
     aas_reachability_t *reach;
     aas_reachabilityareas_t *reachareas;
     //init output
     route->stopevent = RSE_NONE;
     route->endarea = goalareanum;
     route->endcontents = 0;
     route->endtravelflags = 0;
     VectorCopy(origin, route->endpos);
     route->time = 0;
     curareanum = areanum;
     VectorCopy(origin, curorigin);
     for (i = 0; curareanum != goalareanum && (!maxareas || i < maxareas) && i < aasworld.numareas; i++)
     {
         reachnum = AAS_AreaReachabilityToGoalArea(curareanum, curorigin, goalareanum, travelflags);
         if (!reachnum)
         {
             route->stopevent = RSE_NOROUTE;
             return qfalse;
         } //end if
         reach = &aasworld.reachability[reachnum];
         //
         if (stopevent & RSE_USETRAVELTYPE)
         {
             if (AAS_TravelFlagForType_inline(reach->traveltype) & stoptfl)
             {
                 route->stopevent = RSE_USETRAVELTYPE;
                 route->endarea = curareanum;
                 route->endcontents = aasworld.areasettings[curareanum].contents;
                 route->endtravelflags = AAS_TravelFlagForType_inline(reach->traveltype);
                 VectorCopy(reach->start, route->endpos);
                 return qtrue;
             } //end if
             if (AAS_AreaContentsTravelFlags_inline(reach->areanum) & stoptfl)
             {
                 route->stopevent = RSE_USETRAVELTYPE;
                 route->endarea = reach->areanum;
                 route->endcontents = aasworld.areasettings[reach->areanum].contents;
                 route->endtravelflags = AAS_AreaContentsTravelFlags_inline(reach->areanum);
                 VectorCopy(reach->end, route->endpos);
                 route->time += AAS_AreaTravelTime(areanum, origin, reach->start);
                 route->time += reach->traveltime;
                 return qtrue;
             } //end if
         } //end if
         reachareas = &aasworld.reachabilityareas[reachnum];
         for (j = 0; j < reachareas->numareas + 1; j++)
         {
             if (j >= reachareas->numareas)
                 testareanum = reach->areanum;
             else
                 testareanum = aasworld.reachabilityareaindex[reachareas->firstarea + j];
             if (stopevent & RSE_ENTERCONTENTS)
             {
                 if (aasworld.areasettings[testareanum].contents & stopcontents)
                 {
                     route->stopevent = RSE_ENTERCONTENTS;
                     route->endarea = testareanum;
                     route->endcontents = aasworld.areasettings[testareanum].contents;
                     VectorCopy(reach->end, route->endpos);
                     route->time += AAS_AreaTravelTime(areanum, origin, reach->start);
                     route->time += reach->traveltime;
                     return qtrue;
                 } //end if
             } //end if
             if (stopevent & RSE_ENTERAREA)
             {
                 if (testareanum == stopareanum)
                 {
                     route->stopevent = RSE_ENTERAREA;
                     route->endarea = testareanum;
                     route->endcontents = aasworld.areasettings[testareanum].contents;
                     VectorCopy(reach->start, route->endpos);
                     return qtrue;
                 } //end if
             } //end if
         } //end for
         route->time += AAS_AreaTravelTime(areanum, origin, reach->start);
         route->time += reach->traveltime;
         route->endarea = reach->areanum;
         route->endcontents = aasworld.areasettings[reach->areanum].contents;
         route->endtravelflags = AAS_TravelFlagForType_inline(reach->traveltype);
         VectorCopy(reach->end, route->endpos);
         //
         curareanum = reach->areanum;
         VectorCopy(reach->end, curorigin);
         //
         if (maxtime && route->time > maxtime)
             break;
     } //end while
     if (curareanum != goalareanum)
         return qfalse;
     return qtrue;
 } //end of the function AAS_PredictRoute
Referenced by Init_AAS_Export().
AAS_RandomGoalArea()
int AAS_RandomGoalArea (int areanum, int travelflags, int * goalareanum, vec3_t goalorigin)
Definition at line 2009 of file be_aas_route.c.
 {
     int i, n, t;
     vec3_t start, end;
     aas_trace_t trace;
     //if the area has no reachabilities
     if (!AAS_AreaReachability(areanum)) return qfalse;
     //
     n = aasworld.numareas * random();
     for (i = 0; i < aasworld.numareas; i++)
     {
         if (n <= 0) n = 1;
         if (n >= aasworld.numareas) n = 1;
         if (AAS_AreaReachability(n))
         {
             t = AAS_AreaTravelTimeToGoalArea(areanum, aasworld.areas[areanum].center, n, travelflags);
             //if the goal is reachable
             if (t > 0)
             {
                 if (AAS_AreaSwim(n))
                 {
                     *goalareanum = n;
                     VectorCopy(aasworld.areas[n].center, goalorigin);
                     //botimport.Print(PRT_MESSAGE, "found random goal area %d\n", *goalareanum);
                     return qtrue;
                 } //end if
                 VectorCopy(aasworld.areas[n].center, start);
                 if (!AAS_PointAreaNum(start))
                     Log_Write("area %d center %f %f %f in solid?", n, start[0], start[1], start[2]);
                 VectorCopy(start, end);
                 end[2] -= 300;
                 trace = AAS_TraceClientBBox(start, end, PRESENCE_CROUCH, -1);
                 if (!trace.startsolid && trace.fraction < 1 && AAS_PointAreaNum(trace.endpos) == n)
                 {
                     if (AAS_AreaGroundFaceArea(n) > 300)
                     {
                         *goalareanum = n;
                         VectorCopy(trace.endpos, goalorigin);
                         //botimport.Print(PRT_MESSAGE, "found random goal area %d\n", *goalareanum);
                         return qtrue;
                     } //end if
                 } //end if
             } //end if
         } //end if
         n++;
     } //end for
     return qfalse;
 } //end of the function AAS_RandomGoalArea
AAS_ReachabilityFromNum()
void AAS_ReachabilityFromNum (int num, struct aas_reachability_s * reach)
Definition at line 1927 of file be_aas_route.c.
 {
     if (!aasworld.initialized)
     {
         Com_Memset(reach, 0, sizeof(aas_reachability_t));
         return;
     } //end if
     if (num < 0 || num >= aasworld.reachabilitysize)
     {
         Com_Memset(reach, 0, sizeof(aas_reachability_t));
         return;
     } //end if
     Com_Memcpy(reach, &aasworld.reachability[num], sizeof(aas_reachability_t));;
 } //end of the function AAS_ReachabilityFromNum
Referenced by BotExportTest(), BotGetReachabilityToGoal(), BotMovementViewTarget(), BotMoveToGoal(), BotPredictVisiblePosition(), BotReachabilityArea(), and BotResetGrapple().
AAS_TravelFlagForType()
int AAS_TravelFlagForType (int traveltype)
Definition at line 189 of file be_aas_route.c.
 {
     return AAS_TravelFlagForType_inline(traveltype);
 } //end of the function AAS_TravelFlagForType_inline
Referenced by BotMoveToGoal(), and BotValidTravel().