ioquake3 doxygen: C:/entry/dev/ioq3/code/game/bg_public.h File Reference
bg_public.h File Reference
Definitions shared by both the server game and client game modules.
Classes
struct pmove_t
struct animation_s
struct gitem_s
struct gitem_s.
Macros
#define GAME_VERSION BASEGAME "-1"
#define DEFAULT_GRAVITY 800
#define GIB_HEALTH -40
#define ARMOR_PROTECTION 0.66
#define MAX_ITEMS 256
#define RANK_TIED_FLAG 0x4000
#define DEFAULT_SHOTGUN_SPREAD 700
#define DEFAULT_SHOTGUN_COUNT 11
#define ITEM_RADIUS 15
#define LIGHTNING_RANGE 768
#define SCORE_NOT_PRESENT -9999
#define VOTE_TIME 30000
#define MINS_Z -24
#define DEFAULT_VIEWHEIGHT 26
#define CROUCH_VIEWHEIGHT 12
#define DEAD_VIEWHEIGHT -16
#define CS_MUSIC 2
#define CS_MESSAGE 3
from the map worldspawn's message field.
#define CS_MOTD 4
g_motd string for server message of the day.
#define CS_WARMUP 5
server time when the match will be restarted.
#define CS_SCORES1 6
#define CS_SCORES2 7
#define CS_VOTE_TIME 8
#define CS_VOTE_STRING 9
#define CS_VOTE_YES 10
#define CS_VOTE_NO 11
#define CS_TEAMVOTE_TIME 12
#define CS_TEAMVOTE_STRING 14
#define CS_TEAMVOTE_YES 16
#define CS_TEAMVOTE_NO 18
#define CS_GAME_VERSION 20
#define CS_LEVEL_START_TIME 21
so the timer only shows the current level
#define CS_INTERMISSION 22
when 1, fraglimit/timelimit has been hit and intermission will start in a second or two.
#define CS_FLAGSTATUS 23
string indicating flag status in CTF.
#define CS_SHADERSTATE 24
#define CS_BOTINFO 25
#define CS_ITEMS 27
string of 0's and 1's that tell which items are present.
#define CS_MODELS 32
#define CS_SOUNDS (CS_MODELS+MAX_MODELS)
#define CS_PLAYERS (CS_SOUNDS+MAX_SOUNDS)
#define CS_LOCATIONS (CS_PLAYERS+MAX_CLIENTS)
#define CS_PARTICLES (CS_LOCATIONS+MAX_LOCATIONS)
#define CS_MAX (CS_PARTICLES+MAX_LOCATIONS)
#define PMF_DUCKED 1
#define PMF_JUMP_HELD 2
#define PMF_BACKWARDS_JUMP 8
go into backwards land.
#define PMF_BACKWARDS_RUN 16
coast down to backwards run.
#define PMF_TIME_LAND 32
pm_time is time before rejump.
#define PMF_TIME_KNOCKBACK 64
pm_time is an air-accelerate only time.
#define PMF_TIME_WATERJUMP 256
pm_time is waterjump.
#define PMF_RESPAWNED 512
clear after attack and jump buttons come up.
#define PMF_USE_ITEM_HELD 1024
#define PMF_GRAPPLE_PULL 2048
pull towards grapple location.
#define PMF_FOLLOW 4096
spectate following another player.
#define PMF_SCOREBOARD 8192
spectate as a scoreboard.
#define PMF_INVULEXPAND 16384
invulnerability sphere set to full size.
#define PMF_ALL_TIMES (PMF_TIME_WATERJUMP|PMF_TIME_LAND|PMF_TIME_KNOCKBACK)
#define MAXTOUCH 32
#define EF_DEAD 0x00000001
#define EF_TELEPORT_BIT 0x00000004
#define EF_AWARD_EXCELLENT 0x00000008
#define EF_PLAYER_EVENT 0x00000010
#define EF_BOUNCE 0x00000010
#define EF_BOUNCE_HALF 0x00000020
#define EF_AWARD_GAUNTLET 0x00000040
#define EF_NODRAW 0x00000080
#define EF_FIRING 0x00000100
#define EF_KAMIKAZE 0x00000200
#define EF_MOVER_STOP 0x00000400
#define EF_AWARD_CAP 0x00000800
#define EF_TALK 0x00001000
#define EF_CONNECTION 0x00002000
#define EF_VOTED 0x00004000
#define EF_AWARD_IMPRESSIVE 0x00008000
#define EF_AWARD_DEFEND 0x00010000
#define EF_AWARD_ASSIST 0x00020000
#define EF_AWARD_DENIED 0x00040000
#define EF_TEAMVOTED 0x00080000
#define PLAYEREVENT_DENIEDREWARD 0x0001
#define PLAYEREVENT_GAUNTLETREWARD 0x0002
#define PLAYEREVENT_HOLYSHIT 0x0004
#define EV_EVENT_BIT1 0x00000100
#define EV_EVENT_BIT2 0x00000200
#define EV_EVENT_BITS (EV_EVENT_BIT1|EV_EVENT_BIT2)
#define EVENT_VALID_MSEC 300
#define ANIM_TOGGLEBIT 128
#define TEAM_LOCATION_UPDATE_TIME 1000
#define TEAM_MAXOVERLAY 32
#define MAX_ITEM_MODELS 4
#define ITEM_INDEX(x) ((x)-bg_itemlist)
#define DF_NO_FALLING 8
#define DF_FIXED_FOV 16
#define DF_NO_FOOTSTEPS 32
#define MASK_ALL (-1)
#define MASK_SOLID (CONTENTS_SOLID)
#define MASK_PLAYERSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_BODY)
#define MASK_DEADSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP)
#define MASK_WATER (CONTENTS_WATER|CONTENTS_LAVA|CONTENTS_SLIME)
#define MASK_OPAQUE (CONTENTS_SOLID|CONTENTS_SLIME|CONTENTS_LAVA)
#define MASK_SHOT (CONTENTS_SOLID|CONTENTS_BODY|CONTENTS_CORPSE)
#define ARENAS_PER_TIER 4
#define MAX_ARENAS 1024
#define MAX_ARENAS_TEXT 8192
#define MAX_BOTS 1024
#define MAX_BOTS_TEXT 8192
#define KAMI_SHOCKWAVE_STARTTIME 0
#define KAMI_SHOCKWAVEFADE_STARTTIME 1500
#define KAMI_SHOCKWAVE_ENDTIME 2000
#define KAMI_EXPLODE_STARTTIME 250
#define KAMI_IMPLODE_STARTTIME 2000
#define KAMI_IMPLODE_ENDTIME 2250
#define KAMI_SHOCKWAVE2_STARTTIME 2000
#define KAMI_SHOCKWAVE2FADE_STARTTIME 2500
#define KAMI_SHOCKWAVE2_ENDTIME 3000
#define KAMI_SHOCKWAVEMODEL_RADIUS 88
#define KAMI_BOOMSPHEREMODEL_RADIUS 72
#define KAMI_SHOCKWAVE_MAXRADIUS 1320
#define KAMI_BOOMSPHERE_MAXRADIUS 720
#define KAMI_SHOCKWAVE2_MAXRADIUS 704
Typedefs
typedef struct animation_s animation_t
typedef struct gitem_s gitem_t
struct gitem_s.
Enumerations
enum gametype_t {
GT_FFA, GT_TOURNAMENT, GT_SINGLE_PLAYER, GT_TEAM,
GT_CTF, GT_MAX_GAME_TYPE, GT_FFA, GT_TOURNAMENT,
GT_SINGLE_PLAYER, GT_TEAM, GT_CTF, GT_1FCTF,
GT_OBELISK, GT_HARVESTER, GT_MAX_GAME_TYPE
}
Game types.
enum gender_t { GENDER_MALE, GENDER_FEMALE, GENDER_NEUTER }
enum pmtype_t {
PM_NORMAL, PM_NOCLIP, PM_SPECTATOR, PM_DEAD,
PM_FREEZE, PM_INTERMISSION, PM_SPINTERMISSION
}
PMOVE MODULE, The pmove code takes a player_state_t and a usercmd_t and generates a new player_state_t and some other output data.
enum weaponstate_t { WEAPON_READY, WEAPON_RAISING, WEAPON_DROPPING, WEAPON_FIRING }
enum statIndex_t {
STAT_HEALTH, STAT_HOLDABLE_ITEM, STAT_WEAPONS, STAT_ARMOR,
STAT_DEAD_YAW, STAT_CLIENTS_READY, STAT_MAX_HEALTH
}
player_state->stats[] indexes.
enum persEnum_t {
PERS_SCORE, PERS_HITS, PERS_RANK, PERS_TEAM,
PERS_SPAWN_COUNT, PERS_PLAYEREVENTS, PERS_ATTACKER, PERS_ATTACKEE_ARMOR,
PERS_KILLED, PERS_IMPRESSIVE_COUNT, PERS_EXCELLENT_COUNT, PERS_DEFEND_COUNT,
PERS_ASSIST_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_CAPTURES
}
player_state->persistant[] indexes.
enum powerup_t {
PW_NONE, PW_QUAD, PW_BATTLESUIT, PW_HASTE,
PW_INVIS, PW_REGEN, PW_FLIGHT, PW_REDFLAG,
PW_BLUEFLAG, PW_NEUTRALFLAG, PW_SCOUT, PW_GUARD,
PW_DOUBLER, PW_AMMOREGEN, PW_INVULNERABILITY, PW_NUM_POWERUPS
}
enum holdable_t {
HI_NONE, HI_TELEPORTER, HI_MEDKIT, HI_KAMIKAZE,
HI_PORTAL, HI_INVULNERABILITY, HI_NUM_HOLDABLE
}
enum weapon_t {
WP_NONE, WP_GAUNTLET, WP_MACHINEGUN, WP_SHOTGUN,
WP_GRENADE_LAUNCHER, WP_ROCKET_LAUNCHER, WP_LIGHTNING, WP_RAILGUN,
WP_PLASMAGUN, WP_BFG, WP_GRAPPLING_HOOK, WP_NUM_WEAPONS
}
enum entity_event_t {
EV_NONE, EV_FOOTSTEP, EV_FOOTSTEP_METAL, EV_FOOTSPLASH,
EV_FOOTWADE, EV_SWIM, EV_STEP_4, EV_STEP_8,
EV_STEP_12, EV_STEP_16, EV_FALL_SHORT, EV_FALL_MEDIUM,
EV_FALL_FAR, EV_JUMP_PAD, EV_JUMP, EV_WATER_TOUCH,
EV_WATER_LEAVE, EV_WATER_UNDER, EV_WATER_CLEAR, EV_ITEM_PICKUP,
EV_GLOBAL_ITEM_PICKUP, EV_NOAMMO, EV_CHANGE_WEAPON, EV_FIRE_WEAPON,
EV_USE_ITEM0, EV_USE_ITEM1, EV_USE_ITEM2, EV_USE_ITEM3,
EV_USE_ITEM4, EV_USE_ITEM5, EV_USE_ITEM6, EV_USE_ITEM7,
EV_USE_ITEM8, EV_USE_ITEM9, EV_USE_ITEM10, EV_USE_ITEM11,
EV_USE_ITEM12, EV_USE_ITEM13, EV_USE_ITEM14, EV_USE_ITEM15,
EV_ITEM_RESPAWN, EV_ITEM_POP, EV_PLAYER_TELEPORT_IN, EV_PLAYER_TELEPORT_OUT,
EV_GRENADE_BOUNCE, EV_GENERAL_SOUND, EV_GLOBAL_SOUND, EV_GLOBAL_TEAM_SOUND,
EV_BULLET_HIT_FLESH, EV_BULLET_HIT_WALL, EV_MISSILE_HIT, EV_MISSILE_MISS,
EV_MISSILE_MISS_METAL, EV_RAILTRAIL, EV_SHOTGUN, EV_BULLET,
EV_PAIN, EV_DEATH1, EV_DEATH2, EV_DEATH3,
EV_OBITUARY, EV_POWERUP_QUAD, EV_POWERUP_BATTLESUIT, EV_POWERUP_REGEN,
EV_GIB_PLAYER, EV_SCOREPLUM, EV_PROXIMITY_MINE_STICK, EV_PROXIMITY_MINE_TRIGGER,
EV_KAMIKAZE, EV_OBELISKEXPLODE, EV_OBELISKPAIN, EV_INVUL_IMPACT,
EV_JUICED, EV_LIGHTNINGBOLT, EV_DEBUG_LINE, EV_STOPLOOPINGSOUND,
EV_TAUNT, EV_TAUNT_YES, EV_TAUNT_NO, EV_TAUNT_FOLLOWME,
EV_TAUNT_GETFLAG, EV_TAUNT_GUARDBASE, EV_TAUNT_PATROL
}
enum global_team_sound_t {
GTS_RED_CAPTURE, GTS_BLUE_CAPTURE, GTS_RED_RETURN, GTS_BLUE_RETURN,
GTS_RED_TAKEN, GTS_BLUE_TAKEN, GTS_REDOBELISK_ATTACKED, GTS_BLUEOBELISK_ATTACKED,
GTS_REDTEAM_SCORED, GTS_BLUETEAM_SCORED, GTS_REDTEAM_TOOK_LEAD, GTS_BLUETEAM_TOOK_LEAD,
GTS_TEAMS_ARE_TIED, GTS_KAMIKAZE
}
enum animNumber_t {
BOTH_DEATH1, BOTH_DEAD1, BOTH_DEATH2, BOTH_DEAD2,
BOTH_DEATH3, BOTH_DEAD3, TORSO_GESTURE, TORSO_ATTACK,
TORSO_ATTACK2, TORSO_DROP, TORSO_RAISE, TORSO_STAND,
TORSO_STAND2, LEGS_WALKCR, LEGS_WALK, LEGS_RUN,
LEGS_BACK, LEGS_SWIM, LEGS_JUMP, LEGS_LAND,
LEGS_JUMPB, LEGS_LANDB, LEGS_IDLE, LEGS_IDLECR,
LEGS_TURN, TORSO_GETFLAG, TORSO_GUARDBASE, TORSO_PATROL,
TORSO_FOLLOWME, TORSO_AFFIRMATIVE, TORSO_NEGATIVE, MAX_ANIMATIONS,
LEGS_BACKCR, LEGS_BACKWALK, FLAG_RUN, FLAG_STAND,
FLAG_STAND2RUN, MAX_TOTALANIMATIONS
}
enum team_t {
TEAM_FREE, TEAM_RED, TEAM_BLUE, TEAM_SPECTATOR,
TEAM_NUM_TEAMS
}
enum teamtask_t {
TEAMTASK_NONE, TEAMTASK_OFFENSE, TEAMTASK_DEFENSE, TEAMTASK_PATROL,
TEAMTASK_FOLLOW, TEAMTASK_RETRIEVE, TEAMTASK_ESCORT, TEAMTASK_CAMP
}
enum meansOfDeath_t {
MOD_UNKNOWN, MOD_SHOTGUN, MOD_GAUNTLET, MOD_MACHINEGUN,
MOD_GRENADE, MOD_GRENADE_SPLASH, MOD_ROCKET, MOD_ROCKET_SPLASH,
MOD_PLASMA, MOD_PLASMA_SPLASH, MOD_RAILGUN, MOD_LIGHTNING,
MOD_BFG, MOD_BFG_SPLASH, MOD_WATER, MOD_SLIME,
MOD_LAVA, MOD_CRUSH, MOD_TELEFRAG, MOD_FALLING,
MOD_SUICIDE, MOD_TARGET_LASER, MOD_TRIGGER_HURT, MOD_GRAPPLE
}
enum itemType_t {
IT_BAD, IT_WEAPON, IT_AMMO, IT_ARMOR,
IT_HEALTH, IT_POWERUP, IT_HOLDABLE, IT_PERSISTANT_POWERUP,
IT_TEAM
}
gitem_t->type.
enum entityType_t {
ET_GENERAL, ET_PLAYER, ET_ITEM, ET_MISSILE,
ET_MOVER, ET_BEAM, ET_PORTAL, ET_SPEAKER,
ET_PUSH_TRIGGER, ET_TELEPORT_TRIGGER, ET_INVISIBLE, ET_GRAPPLE,
ET_TEAM, ET_EVENTS
}
Functions
void PM_UpdateViewAngles (playerState_t *ps, const usercmd_t *cmd)
void Pmove (pmove_t *pmove)
Pmove Can be called by either the server or the client.
gitem_t * BG_FindItem (const char *pickupName)
gitem_t * BG_FindItemForWeapon (weapon_t weapon)
gitem_t * BG_FindItemForPowerup (powerup_t pw)
gitem_t * BG_FindItemForHoldable (holdable_t pw)
qboolean BG_CanItemBeGrabbed (int gametype, const entityState_t *ent, const playerState_t *ps)
void BG_EvaluateTrajectory (const trajectory_t *tr, int atTime, vec3_t result)
void BG_EvaluateTrajectoryDelta (const trajectory_t *tr, int atTime, vec3_t result)
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t *ps)
void BG_TouchJumpPad (playerState_t *ps, entityState_t *jumppad)
void BG_PlayerStateToEntityState (playerState_t *ps, entityState_t *s, qboolean snap)
void BG_PlayerStateToEntityStateExtraPolate (playerState_t *ps, entityState_t *s, int time, qboolean snap)
qboolean BG_PlayerTouchesItem (playerState_t *ps, entityState_t *item, int atTime)
Variables
gitem_t bg_itemlist []
int bg_numItems
Detailed Description
Definitions shared by both the server game and client game modules.
Because games can change separately from the main system version, we need a second version that must match between game and cgame.
Definition in file bg_public.h.
Macro Definition Documentation
ANIM_TOGGLEBIT
#define ANIM_TOGGLEBIT 128
Definition at line 549 of file bg_public.h.
ARENAS_PER_TIER
#define ARENAS_PER_TIER 4
Definition at line 720 of file bg_public.h.
ARMOR_PROTECTION
#define ARMOR_PROTECTION 0.66
Definition at line 35 of file bg_public.h.
CROUCH_VIEWHEIGHT
#define CROUCH_VIEWHEIGHT 12
Definition at line 54 of file bg_public.h.
CS_BOTINFO
#define CS_BOTINFO 25
Definition at line 84 of file bg_public.h.
CS_FLAGSTATUS
#define CS_FLAGSTATUS 23
string indicating flag status in CTF.
Definition at line 82 of file bg_public.h.
CS_GAME_VERSION
#define CS_GAME_VERSION 20
Definition at line 79 of file bg_public.h.
CS_INTERMISSION
#define CS_INTERMISSION 22
when 1, fraglimit/timelimit has been hit and intermission will start in a second or two.
Definition at line 81 of file bg_public.h.
CS_ITEMS
#define CS_ITEMS 27
string of 0's and 1's that tell which items are present.
Definition at line 86 of file bg_public.h.
CS_LEVEL_START_TIME
#define CS_LEVEL_START_TIME 21
so the timer only shows the current level
Definition at line 80 of file bg_public.h.
CS_LOCATIONS
#define CS_LOCATIONS (CS_PLAYERS+MAX_CLIENTS)
Definition at line 91 of file bg_public.h.
CS_MAX
#define CS_MAX (CS_PARTICLES+MAX_LOCATIONS)
Definition at line 94 of file bg_public.h.
CS_MESSAGE
#define CS_MESSAGE 3
from the map worldspawn's message field.
Definition at line 64 of file bg_public.h.
CS_MODELS
#define CS_MODELS 32
Definition at line 88 of file bg_public.h.
CS_MOTD
#define CS_MOTD 4
g_motd string for server message of the day.
Definition at line 65 of file bg_public.h.
CS_MUSIC
#define CS_MUSIC 2
Definition at line 63 of file bg_public.h.
CS_PARTICLES
#define CS_PARTICLES (CS_LOCATIONS+MAX_LOCATIONS)
Definition at line 92 of file bg_public.h.
CS_PLAYERS
#define CS_PLAYERS (CS_SOUNDS+MAX_SOUNDS)
Definition at line 90 of file bg_public.h.
CS_SCORES1
#define CS_SCORES1 6
Definition at line 67 of file bg_public.h.
CS_SCORES2
#define CS_SCORES2 7
Definition at line 68 of file bg_public.h.
CS_SHADERSTATE
#define CS_SHADERSTATE 24
Definition at line 83 of file bg_public.h.
CS_SOUNDS
#define CS_SOUNDS (CS_MODELS+MAX_MODELS)
Definition at line 89 of file bg_public.h.
CS_TEAMVOTE_NO
#define CS_TEAMVOTE_NO 18
Definition at line 77 of file bg_public.h.
CS_TEAMVOTE_STRING
#define CS_TEAMVOTE_STRING 14
Definition at line 75 of file bg_public.h.
CS_TEAMVOTE_TIME
#define CS_TEAMVOTE_TIME 12
Definition at line 74 of file bg_public.h.
CS_TEAMVOTE_YES
#define CS_TEAMVOTE_YES 16
Definition at line 76 of file bg_public.h.
CS_VOTE_NO
#define CS_VOTE_NO 11
Definition at line 72 of file bg_public.h.
CS_VOTE_STRING
#define CS_VOTE_STRING 9
Definition at line 70 of file bg_public.h.
CS_VOTE_TIME
#define CS_VOTE_TIME 8
Definition at line 69 of file bg_public.h.
CS_VOTE_YES
#define CS_VOTE_YES 10
Definition at line 71 of file bg_public.h.
CS_WARMUP
#define CS_WARMUP 5
server time when the match will be restarted.
Definition at line 66 of file bg_public.h.
DEAD_VIEWHEIGHT
#define DEAD_VIEWHEIGHT -16
Definition at line 55 of file bg_public.h.
DEFAULT_GRAVITY
#define DEFAULT_GRAVITY 800
Definition at line 33 of file bg_public.h.
DEFAULT_SHOTGUN_COUNT
#define DEFAULT_SHOTGUN_COUNT 11
Definition at line 42 of file bg_public.h.
DEFAULT_SHOTGUN_SPREAD
#define DEFAULT_SHOTGUN_SPREAD 700
Definition at line 41 of file bg_public.h.
DEFAULT_VIEWHEIGHT
#define DEFAULT_VIEWHEIGHT 26
Definition at line 53 of file bg_public.h.
DF_FIXED_FOV
#define DF_FIXED_FOV 16
Definition at line 669 of file bg_public.h.
DF_NO_FALLING
#define DF_NO_FALLING 8
Definition at line 668 of file bg_public.h.
DF_NO_FOOTSTEPS
#define DF_NO_FOOTSTEPS 32
Definition at line 670 of file bg_public.h.
EF_AWARD_ASSIST
#define EF_AWARD_ASSIST 0x00020000
Definition at line 270 of file bg_public.h.
EF_AWARD_CAP
#define EF_AWARD_CAP 0x00000800
Definition at line 264 of file bg_public.h.
EF_AWARD_DEFEND
#define EF_AWARD_DEFEND 0x00010000
Definition at line 269 of file bg_public.h.
EF_AWARD_DENIED
#define EF_AWARD_DENIED 0x00040000
Definition at line 271 of file bg_public.h.
EF_AWARD_EXCELLENT
#define EF_AWARD_EXCELLENT 0x00000008
Definition at line 255 of file bg_public.h.
EF_AWARD_GAUNTLET
#define EF_AWARD_GAUNTLET 0x00000040
Definition at line 259 of file bg_public.h.
EF_AWARD_IMPRESSIVE
#define EF_AWARD_IMPRESSIVE 0x00008000
Definition at line 268 of file bg_public.h.
EF_BOUNCE
#define EF_BOUNCE 0x00000010
Definition at line 257 of file bg_public.h.
EF_BOUNCE_HALF
#define EF_BOUNCE_HALF 0x00000020
Definition at line 258 of file bg_public.h.
EF_CONNECTION
#define EF_CONNECTION 0x00002000
Definition at line 266 of file bg_public.h.
EF_DEAD
#define EF_DEAD 0x00000001
Definition at line 250 of file bg_public.h.
EF_FIRING
#define EF_FIRING 0x00000100
Definition at line 261 of file bg_public.h.
EF_KAMIKAZE
#define EF_KAMIKAZE 0x00000200
Definition at line 262 of file bg_public.h.
EF_MOVER_STOP
#define EF_MOVER_STOP 0x00000400
Definition at line 263 of file bg_public.h.
EF_NODRAW
#define EF_NODRAW 0x00000080
Definition at line 260 of file bg_public.h.
EF_PLAYER_EVENT
#define EF_PLAYER_EVENT 0x00000010
Definition at line 256 of file bg_public.h.
EF_TALK
#define EF_TALK 0x00001000
Definition at line 265 of file bg_public.h.
EF_TEAMVOTED
#define EF_TEAMVOTED 0x00080000
Definition at line 272 of file bg_public.h.
EF_TELEPORT_BIT
#define EF_TELEPORT_BIT 0x00000004
Definition at line 254 of file bg_public.h.
EF_VOTED
#define EF_VOTED 0x00004000
Definition at line 267 of file bg_public.h.
EV_EVENT_BIT1
#define EV_EVENT_BIT1 0x00000100
Definition at line 349 of file bg_public.h.
EV_EVENT_BIT2
#define EV_EVENT_BIT2 0x00000200
Definition at line 350 of file bg_public.h.
EV_EVENT_BITS
#define EV_EVENT_BITS (EV_EVENT_BIT1|EV_EVENT_BIT2)
Definition at line 351 of file bg_public.h.
EVENT_VALID_MSEC
#define EVENT_VALID_MSEC 300
Definition at line 353 of file bg_public.h.
GAME_VERSION
#define GAME_VERSION BASEGAME "-1"
Definition at line 31 of file bg_public.h.
GIB_HEALTH
#define GIB_HEALTH -40
Definition at line 34 of file bg_public.h.
ITEM_INDEX
#define ITEM_INDEX (x) ((x)-bg_itemlist)
Definition at line 662 of file bg_public.h.
ITEM_RADIUS
#define ITEM_RADIUS 15
Definition at line 44 of file bg_public.h.
KAMI_BOOMSPHERE_MAXRADIUS
#define KAMI_BOOMSPHERE_MAXRADIUS 720
Definition at line 747 of file bg_public.h.
KAMI_BOOMSPHEREMODEL_RADIUS
#define KAMI_BOOMSPHEREMODEL_RADIUS 72
Definition at line 744 of file bg_public.h.
KAMI_EXPLODE_STARTTIME
#define KAMI_EXPLODE_STARTTIME 250
Definition at line 735 of file bg_public.h.
KAMI_IMPLODE_ENDTIME
#define KAMI_IMPLODE_ENDTIME 2250
Definition at line 737 of file bg_public.h.
KAMI_IMPLODE_STARTTIME
#define KAMI_IMPLODE_STARTTIME 2000
Definition at line 736 of file bg_public.h.
KAMI_SHOCKWAVE2_ENDTIME
#define KAMI_SHOCKWAVE2_ENDTIME 3000
Definition at line 741 of file bg_public.h.
KAMI_SHOCKWAVE2_MAXRADIUS
#define KAMI_SHOCKWAVE2_MAXRADIUS 704
Definition at line 748 of file bg_public.h.
KAMI_SHOCKWAVE2_STARTTIME
#define KAMI_SHOCKWAVE2_STARTTIME 2000
Definition at line 739 of file bg_public.h.
KAMI_SHOCKWAVE2FADE_STARTTIME
#define KAMI_SHOCKWAVE2FADE_STARTTIME 2500
Definition at line 740 of file bg_public.h.
KAMI_SHOCKWAVE_ENDTIME
#define KAMI_SHOCKWAVE_ENDTIME 2000
Definition at line 733 of file bg_public.h.
KAMI_SHOCKWAVE_MAXRADIUS
#define KAMI_SHOCKWAVE_MAXRADIUS 1320
Definition at line 746 of file bg_public.h.
KAMI_SHOCKWAVE_STARTTIME
#define KAMI_SHOCKWAVE_STARTTIME 0
Definition at line 731 of file bg_public.h.
KAMI_SHOCKWAVEFADE_STARTTIME
#define KAMI_SHOCKWAVEFADE_STARTTIME 1500
Definition at line 732 of file bg_public.h.
KAMI_SHOCKWAVEMODEL_RADIUS
#define KAMI_SHOCKWAVEMODEL_RADIUS 88
Definition at line 743 of file bg_public.h.
LIGHTNING_RANGE
#define LIGHTNING_RANGE 768
Definition at line 46 of file bg_public.h.
MASK_ALL
#define MASK_ALL (-1)
Definition at line 673 of file bg_public.h.
MASK_DEADSOLID
#define MASK_DEADSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP)
Definition at line 676 of file bg_public.h.
MASK_OPAQUE
#define MASK_OPAQUE (CONTENTS_SOLID|CONTENTS_SLIME|CONTENTS_LAVA)
Definition at line 678 of file bg_public.h.
MASK_PLAYERSOLID
#define MASK_PLAYERSOLID (CONTENTS_SOLID|CONTENTS_PLAYERCLIP|CONTENTS_BODY)
Definition at line 675 of file bg_public.h.
MASK_SHOT
#define MASK_SHOT (CONTENTS_SOLID|CONTENTS_BODY|CONTENTS_CORPSE)
Definition at line 679 of file bg_public.h.
MASK_SOLID
#define MASK_SOLID (CONTENTS_SOLID)
Definition at line 674 of file bg_public.h.
MASK_WATER
#define MASK_WATER (CONTENTS_WATER|CONTENTS_LAVA|CONTENTS_SLIME)
Definition at line 677 of file bg_public.h.
MAX_ARENAS
#define MAX_ARENAS 1024
Definition at line 721 of file bg_public.h.
MAX_ARENAS_TEXT
#define MAX_ARENAS_TEXT 8192
Definition at line 722 of file bg_public.h.
MAX_BOTS
#define MAX_BOTS 1024
Definition at line 724 of file bg_public.h.
MAX_BOTS_TEXT
#define MAX_BOTS_TEXT 8192
Definition at line 725 of file bg_public.h.
MAX_ITEM_MODELS
#define MAX_ITEM_MODELS 4
Definition at line 632 of file bg_public.h.
MAX_ITEMS
#define MAX_ITEMS 256
Definition at line 37 of file bg_public.h.
MAXTOUCH
#define MAXTOUCH 32
Definition at line 164 of file bg_public.h.
MINS_Z
#define MINS_Z -24
Definition at line 52 of file bg_public.h.
PLAYEREVENT_DENIEDREWARD
#define PLAYEREVENT_DENIEDREWARD 0x0001
Definition at line 336 of file bg_public.h.
PLAYEREVENT_GAUNTLETREWARD
#define PLAYEREVENT_GAUNTLETREWARD 0x0002
Definition at line 337 of file bg_public.h.
PLAYEREVENT_HOLYSHIT
#define PLAYEREVENT_HOLYSHIT 0x0004
Definition at line 338 of file bg_public.h.
PMF_ALL_TIMES
#define PMF_ALL_TIMES (PMF_TIME_WATERJUMP|PMF_TIME_LAND|PMF_TIME_KNOCKBACK)
Definition at line 162 of file bg_public.h.
PMF_BACKWARDS_JUMP
#define PMF_BACKWARDS_JUMP 8
go into backwards land.
Definition at line 150 of file bg_public.h.
PMF_BACKWARDS_RUN
#define PMF_BACKWARDS_RUN 16
coast down to backwards run.
Definition at line 151 of file bg_public.h.
PMF_DUCKED
#define PMF_DUCKED 1
Definition at line 148 of file bg_public.h.
PMF_FOLLOW
#define PMF_FOLLOW 4096
spectate following another player.
Definition at line 158 of file bg_public.h.
PMF_GRAPPLE_PULL
#define PMF_GRAPPLE_PULL 2048
pull towards grapple location.
Definition at line 157 of file bg_public.h.
PMF_INVULEXPAND
#define PMF_INVULEXPAND 16384
invulnerability sphere set to full size.
Definition at line 160 of file bg_public.h.
PMF_JUMP_HELD
#define PMF_JUMP_HELD 2
Definition at line 149 of file bg_public.h.
PMF_RESPAWNED
#define PMF_RESPAWNED 512
clear after attack and jump buttons come up.
Definition at line 155 of file bg_public.h.
PMF_SCOREBOARD
#define PMF_SCOREBOARD 8192
spectate as a scoreboard.
Definition at line 159 of file bg_public.h.
PMF_TIME_KNOCKBACK
#define PMF_TIME_KNOCKBACK 64
pm_time is an air-accelerate only time.
Definition at line 153 of file bg_public.h.
PMF_TIME_LAND
#define PMF_TIME_LAND 32
pm_time is time before rejump.
Definition at line 152 of file bg_public.h.
PMF_TIME_WATERJUMP
#define PMF_TIME_WATERJUMP 256
pm_time is waterjump.
Definition at line 154 of file bg_public.h.
PMF_USE_ITEM_HELD
#define PMF_USE_ITEM_HELD 1024
Definition at line 156 of file bg_public.h.
RANK_TIED_FLAG
#define RANK_TIED_FLAG 0x4000
Definition at line 39 of file bg_public.h.
SCORE_NOT_PRESENT
#define SCORE_NOT_PRESENT -9999
Definition at line 48 of file bg_public.h.
TEAM_LOCATION_UPDATE_TIME
#define TEAM_LOCATION_UPDATE_TIME 1000
Definition at line 561 of file bg_public.h.
TEAM_MAXOVERLAY
#define TEAM_MAXOVERLAY 32
Definition at line 564 of file bg_public.h.
VOTE_TIME
#define VOTE_TIME 30000
Definition at line 50 of file bg_public.h.
Typedef Documentation
animation_t
typedef struct animation_s animation_t
gitem_t
typedef struct gitem_s gitem_t
struct gitem_s.
Enumeration Type Documentation
animNumber_t
enum animNumber_t
Enumerator
BOTH_DEATH1
BOTH_DEAD1
BOTH_DEATH2
BOTH_DEAD2
BOTH_DEATH3
BOTH_DEAD3
TORSO_GESTURE
TORSO_ATTACK
TORSO_ATTACK2
TORSO_DROP
TORSO_RAISE
TORSO_STAND
TORSO_STAND2
LEGS_WALKCR
LEGS_WALK
LEGS_RUN
LEGS_BACK
LEGS_SWIM
LEGS_JUMP
LEGS_LAND
LEGS_JUMPB
LEGS_LANDB
LEGS_IDLE
LEGS_IDLECR
LEGS_TURN
TORSO_GETFLAG
TORSO_GUARDBASE
TORSO_PATROL
TORSO_FOLLOWME
TORSO_AFFIRMATIVE
TORSO_NEGATIVE
MAX_ANIMATIONS
LEGS_BACKCR
LEGS_BACKWALK
FLAG_RUN
FLAG_STAND
FLAG_STAND2RUN
MAX_TOTALANIMATIONS
Definition at line 481 of file bg_public.h.
              {
     BOTH_DEATH1,
     BOTH_DEAD1,
     BOTH_DEATH2,
     BOTH_DEAD2,
     BOTH_DEATH3,
     BOTH_DEAD3,
     TORSO_GESTURE,
     TORSO_ATTACK,
     TORSO_ATTACK2,
     TORSO_DROP,
     TORSO_RAISE,
     TORSO_STAND,
     TORSO_STAND2,
     LEGS_WALKCR,
     LEGS_WALK,
     LEGS_RUN,
     LEGS_BACK,
     LEGS_SWIM,
     LEGS_JUMP,
     LEGS_LAND,
     LEGS_JUMPB,
     LEGS_LANDB,
     LEGS_IDLE,
     LEGS_IDLECR,
     LEGS_TURN,
     TORSO_GETFLAG,
     TORSO_GUARDBASE,
     TORSO_PATROL,
     TORSO_FOLLOWME,
     TORSO_AFFIRMATIVE,
     TORSO_NEGATIVE,
     MAX_ANIMATIONS,
     LEGS_BACKCR,
     LEGS_BACKWALK,
     FLAG_RUN,
     FLAG_STAND,
     FLAG_STAND2RUN,
     MAX_TOTALANIMATIONS
 } animNumber_t;
entity_event_t
enum entity_event_t
Enumerator
EV_NONE
EV_FOOTSTEP
EV_FOOTSTEP_METAL
EV_FOOTSPLASH
EV_FOOTWADE
EV_SWIM
EV_STEP_4
EV_STEP_8
EV_STEP_12
EV_STEP_16
EV_FALL_SHORT
EV_FALL_MEDIUM
EV_FALL_FAR
EV_JUMP_PAD
EV_JUMP
EV_WATER_TOUCH
EV_WATER_LEAVE
EV_WATER_UNDER
EV_WATER_CLEAR
EV_ITEM_PICKUP
EV_GLOBAL_ITEM_PICKUP
EV_NOAMMO
EV_CHANGE_WEAPON
EV_FIRE_WEAPON
EV_USE_ITEM0
EV_USE_ITEM1
EV_USE_ITEM2
EV_USE_ITEM3
EV_USE_ITEM4
EV_USE_ITEM5
EV_USE_ITEM6
EV_USE_ITEM7
EV_USE_ITEM8
EV_USE_ITEM9
EV_USE_ITEM10
EV_USE_ITEM11
EV_USE_ITEM12
EV_USE_ITEM13
EV_USE_ITEM14
EV_USE_ITEM15
EV_ITEM_RESPAWN
EV_ITEM_POP
EV_PLAYER_TELEPORT_IN
EV_PLAYER_TELEPORT_OUT
EV_GRENADE_BOUNCE
EV_GENERAL_SOUND
EV_GLOBAL_SOUND
EV_GLOBAL_TEAM_SOUND
EV_BULLET_HIT_FLESH
EV_BULLET_HIT_WALL
EV_MISSILE_HIT
EV_MISSILE_MISS
EV_MISSILE_MISS_METAL
EV_RAILTRAIL
EV_SHOTGUN
EV_BULLET
EV_PAIN
EV_DEATH1
EV_DEATH2
EV_DEATH3
EV_OBITUARY
EV_POWERUP_QUAD
EV_POWERUP_BATTLESUIT
EV_POWERUP_REGEN
EV_GIB_PLAYER
EV_SCOREPLUM
EV_PROXIMITY_MINE_STICK
EV_PROXIMITY_MINE_TRIGGER
EV_KAMIKAZE
EV_OBELISKEXPLODE
EV_OBELISKPAIN
EV_INVUL_IMPACT
EV_JUICED
EV_LIGHTNINGBOLT
EV_DEBUG_LINE
EV_STOPLOOPINGSOUND
EV_TAUNT
EV_TAUNT_YES
EV_TAUNT_NO
EV_TAUNT_FOLLOWME
EV_TAUNT_GETFLAG
EV_TAUNT_GUARDBASE
EV_TAUNT_PATROL
Definition at line 355 of file bg_public.h.
              {
     EV_NONE,
     EV_FOOTSTEP,
     EV_FOOTSTEP_METAL,
     EV_FOOTSPLASH,
     EV_FOOTWADE,
     EV_SWIM,
     EV_STEP_4,
     EV_STEP_8,
     EV_STEP_12,
     EV_STEP_16,
     EV_FALL_SHORT,
     EV_FALL_MEDIUM,
     EV_FALL_FAR,
     EV_JUMP_PAD,            // boing sound at origin, jump sound on player
     EV_JUMP,
     EV_WATER_TOUCH,    // foot touches
     EV_WATER_LEAVE,    // foot leaves
     EV_WATER_UNDER,    // head touches
     EV_WATER_CLEAR,    // head leaves
     EV_ITEM_PICKUP,            // normal item pickups are predictable
     EV_GLOBAL_ITEM_PICKUP,    // powerup / team sounds are broadcast to everyone
     EV_NOAMMO,
     EV_CHANGE_WEAPON,
     EV_FIRE_WEAPON,
     EV_USE_ITEM0,
     EV_USE_ITEM1,
     EV_USE_ITEM2,
     EV_USE_ITEM3,
     EV_USE_ITEM4,
     EV_USE_ITEM5,
     EV_USE_ITEM6,
     EV_USE_ITEM7,
     EV_USE_ITEM8,
     EV_USE_ITEM9,
     EV_USE_ITEM10,
     EV_USE_ITEM11,
     EV_USE_ITEM12,
     EV_USE_ITEM13,
     EV_USE_ITEM14,
     EV_USE_ITEM15,
     EV_ITEM_RESPAWN,
     EV_ITEM_POP,
     EV_PLAYER_TELEPORT_IN,
     EV_PLAYER_TELEPORT_OUT,
     EV_GRENADE_BOUNCE,        // eventParm will be the soundindex
     EV_GENERAL_SOUND,
     EV_GLOBAL_SOUND,        // no attenuation
     EV_GLOBAL_TEAM_SOUND,
     EV_BULLET_HIT_FLESH,
     EV_BULLET_HIT_WALL,
     EV_MISSILE_HIT,
     EV_MISSILE_MISS,
     EV_MISSILE_MISS_METAL,
     EV_RAILTRAIL,
     EV_SHOTGUN,
     EV_BULLET,                // otherEntity is the shooter
     EV_PAIN,
     EV_DEATH1,
     EV_DEATH2,
     EV_DEATH3,
     EV_OBITUARY,
     EV_POWERUP_QUAD,
     EV_POWERUP_BATTLESUIT,
     EV_POWERUP_REGEN,
     EV_GIB_PLAYER,          // gib a previously living player
     EV_SCOREPLUM,           // score plum
     //#ifdef MISSIONPACK
     EV_PROXIMITY_MINE_STICK,
     EV_PROXIMITY_MINE_TRIGGER,
     EV_KAMIKAZE,            // kamikaze explodes
     EV_OBELISKEXPLODE,      // obelisk explodes
     EV_OBELISKPAIN,         // obelisk is in pain
     EV_INVUL_IMPACT,        // invulnerability sphere impact
     EV_JUICED,              // invulnerability juiced effect
     EV_LIGHTNINGBOLT,       // lightning bolt bounced of invulnerability sphere
     //#endif
     EV_DEBUG_LINE,
     EV_STOPLOOPINGSOUND,
     EV_TAUNT,
     EV_TAUNT_YES,
     EV_TAUNT_NO,
     EV_TAUNT_FOLLOWME,
     EV_TAUNT_GETFLAG,
     EV_TAUNT_GUARDBASE,
     EV_TAUNT_PATROL
 } entity_event_t;
entityType_t
enum entityType_t
Enumerator
ET_GENERAL
ET_PLAYER
ET_ITEM
ET_MISSILE
ET_MOVER
ET_BEAM
ET_PORTAL
ET_SPEAKER
ET_PUSH_TRIGGER
ET_TELEPORT_TRIGGER
ET_INVISIBLE
ET_GRAPPLE
ET_TEAM
ET_EVENTS
Definition at line 685 of file bg_public.h.
              {
     ET_GENERAL,
     ET_PLAYER,
     ET_ITEM,
     ET_MISSILE,
     ET_MOVER,
     ET_BEAM,
     ET_PORTAL,
     ET_SPEAKER,
     ET_PUSH_TRIGGER,
     ET_TELEPORT_TRIGGER,
     ET_INVISIBLE,
     ET_GRAPPLE,                // grapple hooked on wall
     ET_TEAM,
     ET_EVENTS                // any of the EV_* events can be added freestanding
                             // by setting eType to ET_EVENTS + eventNum
                             // this avoids having to set eFlags and eventNum
 } entityType_t;
gametype_t
enum gametype_t
Game types.
FIXME: these are game specific.
Enumerator
GT_FFA
free for all.
GT_TOURNAMENT
one on one tournament.
GT_SINGLE_PLAYER
single player tournament.
GT_TEAM
team deathmatch.
GT_CTF
capture the flag.
GT_MAX_GAME_TYPE
GT_FFA
free for all.
GT_TOURNAMENT
one on one tournament.
GT_SINGLE_PLAYER
single player tournament.
GT_TEAM
team deathmatch.
GT_CTF
capture the flag.
GT_1FCTF
GT_OBELISK
GT_HARVESTER
GT_MAX_GAME_TYPE
Definition at line 105 of file bg_public.h.
              {
     GT_FFA,
     GT_TOURNAMENT,
     GT_SINGLE_PLAYER,
     //-- team games go after this --
     GT_TEAM,
     GT_CTF,
 //#ifdef MISSIONPACK
     GT_1FCTF,
     GT_OBELISK,
     GT_HARVESTER,
 //#endif
     GT_MAX_GAME_TYPE
 } gametype_t;
gender_t
enum gender_t
Enumerator
GENDER_MALE
GENDER_FEMALE
GENDER_NEUTER
Definition at line 122 of file bg_public.h.
 { GENDER_MALE, GENDER_FEMALE, GENDER_NEUTER } gender_t;
global_team_sound_t
enum global_team_sound_t
Enumerator
GTS_RED_CAPTURE
GTS_BLUE_CAPTURE
GTS_RED_RETURN
GTS_BLUE_RETURN
GTS_RED_TAKEN
GTS_BLUE_TAKEN
GTS_REDOBELISK_ATTACKED
GTS_BLUEOBELISK_ATTACKED
GTS_REDTEAM_SCORED
GTS_BLUETEAM_SCORED
GTS_REDTEAM_TOOK_LEAD
GTS_BLUETEAM_TOOK_LEAD
GTS_TEAMS_ARE_TIED
GTS_KAMIKAZE
Definition at line 463 of file bg_public.h.
              {
     GTS_RED_CAPTURE,
     GTS_BLUE_CAPTURE,
     GTS_RED_RETURN,
     GTS_BLUE_RETURN,
     GTS_RED_TAKEN,
     GTS_BLUE_TAKEN,
     GTS_REDOBELISK_ATTACKED,
     GTS_BLUEOBELISK_ATTACKED,
     GTS_REDTEAM_SCORED,
     GTS_BLUETEAM_SCORED,
     GTS_REDTEAM_TOOK_LEAD,
     GTS_BLUETEAM_TOOK_LEAD,
     GTS_TEAMS_ARE_TIED,
     GTS_KAMIKAZE
 } global_team_sound_t;
holdable_t
enum holdable_t
Enumerator
HI_NONE
HI_TELEPORTER
HI_MEDKIT
HI_KAMIKAZE
HI_PORTAL
HI_INVULNERABILITY
HI_NUM_HOLDABLE
Definition at line 299 of file bg_public.h.
              {
     HI_NONE,
     HI_TELEPORTER,
     HI_MEDKIT,
     HI_KAMIKAZE,
     HI_PORTAL,
     HI_INVULNERABILITY,
     HI_NUM_HOLDABLE
 } holdable_t;
itemType_t
enum itemType_t
gitem_t->type.
Enumerator
IT_BAD
IT_WEAPON
EFX: rotate + upscale + minlight.
IT_AMMO
EFX: rotate.
IT_ARMOR
EFX: rotate + minlight.
IT_HEALTH
EFX: static external sphere + rotating internal.
IT_POWERUP
instant on, timer based.
IT_HOLDABLE
single use, holdable item.
IT_PERSISTANT_POWERUP
IT_TEAM
Definition at line 618 of file bg_public.h.
              {
     IT_BAD,
     IT_WEAPON,
     IT_AMMO,
     IT_ARMOR,
     IT_HEALTH,
     IT_POWERUP,
     // EFX: rotate + external ring that rotates.
     IT_HOLDABLE,
     // EFX: rotate + bob
     IT_PERSISTANT_POWERUP,
     IT_TEAM
 } itemType_t;
meansOfDeath_t
enum meansOfDeath_t
Enumerator
MOD_UNKNOWN
MOD_SHOTGUN
MOD_GAUNTLET
MOD_MACHINEGUN
MOD_GRENADE
MOD_GRENADE_SPLASH
MOD_ROCKET
MOD_ROCKET_SPLASH
MOD_PLASMA
MOD_PLASMA_SPLASH
MOD_RAILGUN
MOD_LIGHTNING
MOD_BFG
MOD_BFG_SPLASH
MOD_WATER
MOD_SLIME
MOD_LAVA
MOD_CRUSH
MOD_TELEFRAG
MOD_FALLING
MOD_SUICIDE
MOD_TARGET_LASER
MOD_TRIGGER_HURT
MOD_GRAPPLE
Definition at line 579 of file bg_public.h.
              {
     MOD_UNKNOWN,
     MOD_SHOTGUN,
     MOD_GAUNTLET,
     MOD_MACHINEGUN,
     MOD_GRENADE,
     MOD_GRENADE_SPLASH,
     MOD_ROCKET,
     MOD_ROCKET_SPLASH,
     MOD_PLASMA,
     MOD_PLASMA_SPLASH,
     MOD_RAILGUN,
     MOD_LIGHTNING,
     MOD_BFG,
     MOD_BFG_SPLASH,
     MOD_WATER,
     MOD_SLIME,
     MOD_LAVA,
     MOD_CRUSH,
     MOD_TELEFRAG,
     MOD_FALLING,
     MOD_SUICIDE,
     MOD_TARGET_LASER,
     MOD_TRIGGER_HURT,
 #ifdef MISSIONPACK
     MOD_NAIL,
     MOD_CHAINGUN,
     MOD_PROXIMITY_MINE,
     MOD_KAMIKAZE,
     MOD_JUICED,
 #endif
     MOD_GRAPPLE
 } meansOfDeath_t;
persEnum_t
enum persEnum_t
player_state->persistant[] indexes.
These fields of persistant[] are the only part of player_state that isn't cleared on respawn.
NOTE: may not have more than 16.
Enumerator
PERS_SCORE
!!! MUST NOT CHANGE, SERVER AND GAME BOTH REFERENCE !!!.
PERS_HITS
total points damage inflicted so damage beeps can sound on change.
PERS_RANK
player rank or team rank.
PERS_TEAM
player team.
PERS_SPAWN_COUNT
incremented every respawn.
PERS_PLAYEREVENTS
16 bits that can be flipped for events.
PERS_ATTACKER
clientnum of last damage inflicter.
PERS_ATTACKEE_ARMOR
health/armor of last person we attacked.
PERS_KILLED
count of the number of times you died.
PERS_IMPRESSIVE_COUNT
two railgun hits in a row.
PERS_EXCELLENT_COUNT
two successive kills in a short amount of time.
PERS_DEFEND_COUNT
defend awards.
PERS_ASSIST_COUNT
assist awards.
PERS_GAUNTLET_FRAG_COUNT
kills with the guantlet.
PERS_CAPTURES
captures.
Definition at line 228 of file bg_public.h.
              {
     PERS_SCORE,
     PERS_HITS,
     PERS_RANK,
     PERS_TEAM,
     PERS_SPAWN_COUNT,
     PERS_PLAYEREVENTS,
     PERS_ATTACKER,
     PERS_ATTACKEE_ARMOR,
     PERS_KILLED,
     /*player awards tracking*/
     PERS_IMPRESSIVE_COUNT,
     PERS_EXCELLENT_COUNT,
     PERS_DEFEND_COUNT,
     PERS_ASSIST_COUNT,
     PERS_GAUNTLET_FRAG_COUNT,
     PERS_CAPTURES
 } persEnum_t;
pmtype_t
enum pmtype_t
PMOVE MODULE, The pmove code takes a player_state_t and a usercmd_t and generates a new player_state_t and some other output data.
Used for local prediction on the client game and true movement on the server game.
Enumerator
PM_NORMAL
can accelerate and turn.
PM_NOCLIP
noclip movement.
PM_SPECTATOR
still run into walls.
PM_DEAD
no acceleration or turning, but free falling.
PM_FREEZE
stuck in place with no control.
PM_INTERMISSION
no movement or status bar.
PM_SPINTERMISSION
no movement or status bar.
Definition at line 130 of file bg_public.h.
              {
     PM_NORMAL,
     PM_NOCLIP,
     PM_SPECTATOR,
     PM_DEAD,
     PM_FREEZE,
     PM_INTERMISSION,
     PM_SPINTERMISSION
 } pmtype_t;
powerup_t
enum powerup_t
Enumerator
PW_NONE
PW_QUAD
PW_BATTLESUIT
PW_HASTE
PW_INVIS
PW_REGEN
PW_FLIGHT
PW_REDFLAG
PW_BLUEFLAG
PW_NEUTRALFLAG
PW_SCOUT
PW_GUARD
PW_DOUBLER
PW_AMMOREGEN
PW_INVULNERABILITY
PW_NUM_POWERUPS
Definition at line 275 of file bg_public.h.
              {
     PW_NONE,
     PW_QUAD,
     PW_BATTLESUIT,
     PW_HASTE,
     PW_INVIS,
     PW_REGEN,
     PW_FLIGHT,
     PW_REDFLAG,
     PW_BLUEFLAG,
     PW_NEUTRALFLAG,
     PW_SCOUT,
     PW_GUARD,
     PW_DOUBLER,
     PW_AMMOREGEN,
     PW_INVULNERABILITY,
     PW_NUM_POWERUPS
 } powerup_t;
statIndex_t
enum statIndex_t
player_state->stats[] indexes.
NOTE: may not have more than 16.
Enumerator
STAT_HEALTH
STAT_HOLDABLE_ITEM
STAT_WEAPONS
STAT_ARMOR
STAT_DEAD_YAW
STAT_CLIENTS_READY
STAT_MAX_HEALTH
Definition at line 209 of file bg_public.h.
              {
     STAT_HEALTH,
     STAT_HOLDABLE_ITEM,
 #ifdef MISSIONPACK
     STAT_PERSISTANT_POWERUP,
 #endif
     STAT_WEAPONS,               // 16 bit fields
     STAT_ARMOR,
     STAT_DEAD_YAW,              // look this direction when dead (FIXME: get rid of?)
     STAT_CLIENTS_READY,         // bit mask of clients wishing to exit the intermission (FIXME: configstring?)
     STAT_MAX_HEALTH             // health / armor limit, changeable by handicap
 } statIndex_t;
team_t
enum team_t
Enumerator
TEAM_FREE
TEAM_RED
TEAM_BLUE
TEAM_SPECTATOR
TEAM_NUM_TEAMS
Definition at line 551 of file bg_public.h.
              {
     TEAM_FREE,
     TEAM_RED,
     TEAM_BLUE,
     TEAM_SPECTATOR,
     TEAM_NUM_TEAMS
 } team_t;
teamtask_t
enum teamtask_t
Enumerator
TEAMTASK_NONE
TEAMTASK_OFFENSE
TEAMTASK_DEFENSE
TEAMTASK_PATROL
TEAMTASK_FOLLOW
TEAMTASK_RETRIEVE
TEAMTASK_ESCORT
TEAMTASK_CAMP
Definition at line 567 of file bg_public.h.
              {
     TEAMTASK_NONE,
     TEAMTASK_OFFENSE,
     TEAMTASK_DEFENSE,
     TEAMTASK_PATROL,
     TEAMTASK_FOLLOW,
     TEAMTASK_RETRIEVE,
     TEAMTASK_ESCORT,
     TEAMTASK_CAMP
 } teamtask_t;
weapon_t
enum weapon_t
Enumerator
WP_NONE
WP_GAUNTLET
WP_MACHINEGUN
WP_SHOTGUN
WP_GRENADE_LAUNCHER
WP_ROCKET_LAUNCHER
WP_LIGHTNING
WP_RAILGUN
WP_PLASMAGUN
WP_BFG
WP_GRAPPLING_HOOK
WP_NUM_WEAPONS
Definition at line 312 of file bg_public.h.
              {
     WP_NONE,
     WP_GAUNTLET,
     WP_MACHINEGUN,
     WP_SHOTGUN,
     WP_GRENADE_LAUNCHER,
     WP_ROCKET_LAUNCHER,
     WP_LIGHTNING,
     WP_RAILGUN,
     WP_PLASMAGUN,
     WP_BFG,
     WP_GRAPPLING_HOOK,
 #ifdef MISSIONPACK
     WP_NAILGUN,
     WP_PROX_LAUNCHER,
     WP_CHAINGUN,
 #endif
     WP_NUM_WEAPONS
 } weapon_t;
weaponstate_t
enum weaponstate_t
Enumerator
WEAPON_READY
WEAPON_RAISING
WEAPON_DROPPING
WEAPON_FIRING
Definition at line 140 of file bg_public.h.
              {
     WEAPON_READY,
     WEAPON_RAISING,
     WEAPON_DROPPING,
     WEAPON_FIRING
 } weaponstate_t;
Function Documentation
BG_AddPredictableEventToPlayerstate()
void BG_AddPredictableEventToPlayerstate (int newEvent, int eventParm, playerState_t * ps)
Definition at line 1414 of file bg_misc.c.
 {
 #ifdef _DEBUG
     {
         char buf[256];
         trap_Cvar_VariableStringBuffer("showevents", buf, sizeof(buf));
         if (atof(buf) != 0) {
 #ifdef QAGAME
             Com_Printf(" game event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #else
             Com_Printf("Cgame event svt %5d -> %5d: num = %20s parm %d\n", ps->pmove_framecount/*ps->commandTime*/, ps->eventSequence, eventnames[newEvent], eventParm);
 #endif
     }
 }
 #endif
     ps->events[ps->eventSequence & (MAX_PS_EVENTS - 1)] = newEvent;
     ps->eventParms[ps->eventSequence & (MAX_PS_EVENTS - 1)] = eventParm;
     ps->eventSequence++;
 }
Referenced by BG_TouchJumpPad(), CG_TouchItem(), G_AddPredictableEvent(), and PM_AddEvent().
BG_CanItemBeGrabbed()
qboolean BG_CanItemBeGrabbed (int gametype, const entityState_t * ent, const playerState_t * ps)
Definition at line 1056 of file bg_misc.c.
 {
     gitem_t* item;
 #ifdef MISSIONPACK
     int        upperBound;
 #endif
     if (ent->modelindex < 1 || ent->modelindex >= bg_numItems) {
         Com_Error(ERR_DROP, "BG_CanItemBeGrabbed: index out of range");
     }
     item = &bg_itemlist[ent->modelindex];
     switch (item->giType) {
     case IT_WEAPON:
         return qtrue;    // weapons are always picked up
     case IT_AMMO:
         if (ps->ammo[item->giTag] >= 200) {
             return qfalse;        // can't hold any more
         }
         return qtrue;
     case IT_ARMOR:
 #ifdef MISSIONPACK
         if (bg_itemlist[ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_SCOUT) {
             return qfalse;
         }
         // we also clamp armor to the maxhealth for handicapping
         if (bg_itemlist[ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_GUARD) {
             upperBound = ps->stats[STAT_MAX_HEALTH];
         } else {
             upperBound = ps->stats[STAT_MAX_HEALTH] * 2;
         }
         if (ps->stats[STAT_ARMOR] >= upperBound) {
             return qfalse;
     }
 #else
         if (ps->stats[STAT_ARMOR] >= ps->stats[STAT_MAX_HEALTH] * 2) {
             return qfalse;
         }
 #endif
         return qtrue;
     case IT_HEALTH:
         // small and mega healths will go over the max, otherwise
         // don't pick up if already at max
 #ifdef MISSIONPACK
         if (bg_itemlist[ps->stats[STAT_PERSISTANT_POWERUP]].giTag == PW_GUARD) {
         } else
 #endif
             if (item->quantity == 5 || item->quantity == 100) {
                 if (ps->stats[STAT_HEALTH] >= ps->stats[STAT_MAX_HEALTH] * 2) {
                     return qfalse;
                 }
                 return qtrue;
             }
         if (ps->stats[STAT_HEALTH] >= ps->stats[STAT_MAX_HEALTH]) {
             return qfalse;
         }
         return qtrue;
     case IT_POWERUP:
         return qtrue;    // powerups are always picked up
 #ifdef MISSIONPACK
     case IT_PERSISTANT_POWERUP:
         // can only hold one item at a time
         if (ps->stats[STAT_PERSISTANT_POWERUP]) {
             return qfalse;
         }
         // check team only
         if ((ent->generic1 & 2) && (ps->persistant[PERS_TEAM] != TEAM_RED)) {
             return qfalse;
         }
         if ((ent->generic1 & 4) && (ps->persistant[PERS_TEAM] != TEAM_BLUE)) {
             return qfalse;
         }
         return qtrue;
 #endif
     case IT_TEAM: // team items, such as flags
 #ifdef MISSIONPACK
         if (gametype == GT_1FCTF) {
             // neutral flag can always be picked up
             if (item->giTag == PW_NEUTRALFLAG) {
                 return qtrue;
             }
             if (ps->persistant[PERS_TEAM] == TEAM_RED) {
                 if (item->giTag == PW_BLUEFLAG && ps->powerups[PW_NEUTRALFLAG]) {
                     return qtrue;
                 }
             } else if (ps->persistant[PERS_TEAM] == TEAM_BLUE) {
                 if (item->giTag == PW_REDFLAG && ps->powerups[PW_NEUTRALFLAG]) {
                     return qtrue;
                 }
             }
         }
 #endif
         if (gametype == GT_CTF) {
             // ent->modelindex2 is non-zero on items if they are dropped
             // we need to know this because we can pick up our dropped flag (and return it)
             // but we can't pick up our flag at base
             if (ps->persistant[PERS_TEAM] == TEAM_RED) {
                 if (item->giTag == PW_BLUEFLAG ||
                     (item->giTag == PW_REDFLAG && ent->modelindex2) ||
                     (item->giTag == PW_REDFLAG && ps->powerups[PW_BLUEFLAG]))
                     return qtrue;
             } else if (ps->persistant[PERS_TEAM] == TEAM_BLUE) {
                 if (item->giTag == PW_REDFLAG ||
                     (item->giTag == PW_BLUEFLAG && ent->modelindex2) ||
                     (item->giTag == PW_BLUEFLAG && ps->powerups[PW_REDFLAG]))
                     return qtrue;
             }
         }
 #ifdef MISSIONPACK
         if (gametype == GT_HARVESTER) {
             return qtrue;
         }
 #endif
         return qfalse;
     case IT_HOLDABLE:
         // can only hold one item at a time
         if (ps->stats[STAT_HOLDABLE_ITEM]) {
             return qfalse;
         }
         return qtrue;
     case IT_BAD:
         Com_Error(ERR_DROP, "BG_CanItemBeGrabbed: IT_BAD");
     default:
 #ifndef Q3_VM
 #ifndef NDEBUG
         Com_Printf("BG_CanItemBeGrabbed: unknown enum %d\n", item->giType);
 #endif
 #endif
         break;
     }
     return qfalse;
 }
Referenced by CG_TouchItem(), and Touch_Item().
BG_EvaluateTrajectory()
void BG_EvaluateTrajectory (const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 1213 of file bg_misc.c.
 {
     float        deltaTime;
     float        phase;
     switch (tr->trType) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorCopy(tr->trBase, result);
         break;
     case TR_LINEAR:
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         VectorMA(tr->trBase, deltaTime, tr->trDelta, result);
         break;
     case TR_SINE:
         deltaTime = (atTime - tr->trTime) / (float)tr->trDuration;
         phase = sin(deltaTime * M_PI * 2);
         VectorMA(tr->trBase, phase, tr->trDelta, result);
         break;
     case TR_LINEAR_STOP:
         if (atTime > tr->trTime + tr->trDuration) {
             atTime = tr->trTime + tr->trDuration;
         }
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         if (deltaTime < 0) {
             deltaTime = 0;
         }
         VectorMA(tr->trBase, deltaTime, tr->trDelta, result);
         break;
     case TR_GRAVITY:
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         VectorMA(tr->trBase, deltaTime, tr->trDelta, result);
         result[2] -= 0.5 * DEFAULT_GRAVITY * deltaTime * deltaTime;        // FIXME: local gravity...
         break;
     default:
         Com_Error(ERR_DROP, "BG_EvaluateTrajectory: unknown trType: %i", tr->trType);
         break;
     }
 }
Referenced by BG_PlayerTouchesItem(), CG_AddFragment(), CG_AddMoveScaleFade(), CG_AdjustPositionForMover(), CG_BloodTrail(), CG_CalcEntityLerpPositions(), CG_CheckEvents(), CG_ClipMoveToEntities(), CG_GrappleTrail(), CG_InterpolateEntityPosition(), CG_PlasmaTrail(), CG_ResetPlayerEntity(), CG_RocketTrail(), G_ExplodeMissile(), G_MoverTeam(), G_RunItem(), G_RunMissile(), and SetMoverState().
BG_EvaluateTrajectoryDelta()
void BG_EvaluateTrajectoryDelta (const trajectory_t * tr, int atTime, vec3_t result)
Definition at line 1260 of file bg_misc.c.
 {
     float    deltaTime;
     float    phase;
     switch (tr->trType) {
     case TR_STATIONARY:
     case TR_INTERPOLATE:
         VectorClear(result);
         break;
     case TR_LINEAR:
         VectorCopy(tr->trDelta, result);
         break;
     case TR_SINE:
         deltaTime = (atTime - tr->trTime) / (float)tr->trDuration;
         phase = cos(deltaTime * M_PI * 2);    // derivative of sin = cos
         phase *= 0.5;
         VectorScale(tr->trDelta, phase, result);
         break;
     case TR_LINEAR_STOP:
         if (atTime > tr->trTime + tr->trDuration) {
             VectorClear(result);
             return;
         }
         VectorCopy(tr->trDelta, result);
         break;
     case TR_GRAVITY:
         deltaTime = (atTime - tr->trTime) * 0.001;    // milliseconds to seconds
         VectorCopy(tr->trDelta, result);
         result[2] -= DEFAULT_GRAVITY * deltaTime;        // FIXME: local gravity...
         break;
     default:
         Com_Error(ERR_DROP, "BG_EvaluateTrajectoryDelta: unknown trType: %i", tr->trType);
         break;
     }
 }
Referenced by CG_Missile(), CG_ReflectVelocity(), G_BounceItem(), G_BounceMissile(), and G_MissileImpact().
BG_FindItem()
gitem_t* BG_FindItem (const char * pickupName)
Definition at line 1007 of file bg_misc.c.
 {
     gitem_t* it;
     for (it = bg_itemlist + 1; it->classname; it++) {
         if (!Q_stricmp(it->pickup_name, pickupName))
             return it;
     }
     return NULL;
 }
Referenced by ClearRegisteredItems(), ClientEvents(), Cmd_Give_f(), and G_CheckTeamItems().
BG_FindItemForHoldable()
gitem_t* BG_FindItemForHoldable (holdable_t pw)
Definition at line 965 of file bg_misc.c.
 {
     int        i;
     for (i = 0; i < bg_numItems; i++) {
         if (bg_itemlist[i].giType == IT_HOLDABLE && bg_itemlist[i].giTag == pw) {
             return &bg_itemlist[i];
         }
     }
     Com_Error(ERR_DROP, "HoldableItem not found");
     return NULL;
 }
Referenced by CG_UseItem().
BG_FindItemForPowerup()
gitem_t* BG_FindItemForPowerup (powerup_t pw)
Definition at line 943 of file bg_misc.c.
 {
     int        i;
     for (i = 0; i < bg_numItems; i++) {
         if ((bg_itemlist[i].giType == IT_POWERUP ||
             bg_itemlist[i].giType == IT_TEAM ||
             bg_itemlist[i].giType == IT_PERSISTANT_POWERUP) &&
             bg_itemlist[i].giTag == pw) {
             return &bg_itemlist[i];
         }
     }
     return NULL;
 }
Referenced by CG_DrawAreaPowerUp(), CG_DrawBlueFlagStatus(), CG_DrawFlagModel(), CG_DrawNewTeamInfo(), CG_DrawPowerups(), CG_DrawRedFlagStatus(), CG_DrawScores(), CG_DrawSelectedPlayerPowerup(), CG_DrawTeamOverlay(), CG_OneFlagStatus(), ClientEvents(), and TossClientItems().
BG_FindItemForWeapon()
gitem_t* BG_FindItemForWeapon (weapon_t weapon)
Definition at line 987 of file bg_misc.c.
 {
     gitem_t* it;
     for (it = bg_itemlist + 1; it->classname; it++) {
         if (it->giType == IT_WEAPON && it->giTag == weapon) {
             return it;
         }
     }
     Com_Error(ERR_DROP, "Couldn't find item for weapon %i", weapon);
     return NULL;
 }
Referenced by ClearRegisteredItems(), InitShooter(), and TossClientItems().
BG_PlayerStateToEntityState()
void BG_PlayerStateToEntityState (playerState_t * ps, entityState_t * s, qboolean snap)
Definition at line 1484 of file bg_misc.c.
 {
     int        i;
     if (ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPECTATOR) {
         s->eType = ET_INVISIBLE;
     } else if (ps->stats[STAT_HEALTH] <= GIB_HEALTH) {
         s->eType = ET_INVISIBLE;
     } else {
         s->eType = ET_PLAYER;
     }
     s->number = ps->clientNum;
     s->pos.trType = TR_INTERPOLATE;
     VectorCopy(ps->origin, s->pos.trBase);
     if (snap) {
         SnapVector(s->pos.trBase);
     }
     // set the trDelta for flag direction
     VectorCopy(ps->velocity, s->pos.trDelta);
     s->apos.trType = TR_INTERPOLATE;
     VectorCopy(ps->viewangles, s->apos.trBase);
     if (snap) {
         SnapVector(s->apos.trBase);
     }
     s->angles2[YAW] = ps->movementDir;
     s->legsAnim = ps->legsAnim;
     s->torsoAnim = ps->torsoAnim;
     s->clientNum = ps->clientNum;        // ET_PLAYER looks here instead of at number
                                         // so corpses can also reference the proper config
     s->eFlags = ps->eFlags;
     if (ps->stats[STAT_HEALTH] <= 0) {
         s->eFlags |= EF_DEAD;
     } else {
         s->eFlags &= ~EF_DEAD;
     }
     if (ps->externalEvent) {
         s->event = ps->externalEvent;
         s->eventParm = ps->externalEventParm;
     } else if (ps->entityEventSequence < ps->eventSequence) {
         int        seq;
         if (ps->entityEventSequence < ps->eventSequence - MAX_PS_EVENTS) {
             ps->entityEventSequence = ps->eventSequence - MAX_PS_EVENTS;
         }
         seq = ps->entityEventSequence & (MAX_PS_EVENTS - 1);
         s->event = ps->events[seq] | ((ps->entityEventSequence & 3) << 8);
         s->eventParm = ps->eventParms[seq];
         ps->entityEventSequence++;
     }
     s->weapon = ps->weapon;
     s->groundEntityNum = ps->groundEntityNum;
     s->powerups = 0;
     for (i = 0; i < MAX_POWERUPS; i++) {
         if (ps->powerups[i]) {
             s->powerups |= 1 << i;
         }
     }
     s->loopSound = ps->loopSound;
     s->generic1 = ps->generic1;
 }
Referenced by CG_AddPacketEntities(), CG_SetInitialSnapshot(), CG_SetNextSnap(), CG_TransitionSnapshot(), ClientEndFrame(), ClientSpawn(), ClientThink_real(), SendPendingPredictableEvents(), and TeleportPlayer().
BG_PlayerStateToEntityStateExtraPolate()
void BG_PlayerStateToEntityStateExtraPolate (playerState_t * ps, entityState_t * s, int time, qboolean snap)
Definition at line 1561 of file bg_misc.c.
 {
     int        i;
     if (ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPECTATOR) {
         s->eType = ET_INVISIBLE;
     } else if (ps->stats[STAT_HEALTH] <= GIB_HEALTH) {
         s->eType = ET_INVISIBLE;
     } else {
         s->eType = ET_PLAYER;
     }
     s->number = ps->clientNum;
     s->pos.trType = TR_LINEAR_STOP;
     VectorCopy(ps->origin, s->pos.trBase);
     if (snap) {
         SnapVector(s->pos.trBase);
     }
     // set the trDelta for flag direction and linear prediction
     VectorCopy(ps->velocity, s->pos.trDelta);
     // set the time for linear prediction
     s->pos.trTime = time;
     // set maximum extra polation time
     s->pos.trDuration = 50; // 1000 / sv_fps (default = 20)
     s->apos.trType = TR_INTERPOLATE;
     VectorCopy(ps->viewangles, s->apos.trBase);
     if (snap) {
         SnapVector(s->apos.trBase);
     }
     s->angles2[YAW] = ps->movementDir;
     s->legsAnim = ps->legsAnim;
     s->torsoAnim = ps->torsoAnim;
     s->clientNum = ps->clientNum;        // ET_PLAYER looks here instead of at number
                                         // so corpses can also reference the proper config
     s->eFlags = ps->eFlags;
     if (ps->stats[STAT_HEALTH] <= 0) {
         s->eFlags |= EF_DEAD;
     } else {
         s->eFlags &= ~EF_DEAD;
     }
     if (ps->externalEvent) {
         s->event = ps->externalEvent;
         s->eventParm = ps->externalEventParm;
     } else if (ps->entityEventSequence < ps->eventSequence) {
         int        seq;
         if (ps->entityEventSequence < ps->eventSequence - MAX_PS_EVENTS) {
             ps->entityEventSequence = ps->eventSequence - MAX_PS_EVENTS;
         }
         seq = ps->entityEventSequence & (MAX_PS_EVENTS - 1);
         s->event = ps->events[seq] | ((ps->entityEventSequence & 3) << 8);
         s->eventParm = ps->eventParms[seq];
         ps->entityEventSequence++;
     }
     s->weapon = ps->weapon;
     s->groundEntityNum = ps->groundEntityNum;
     s->powerups = 0;
     for (i = 0; i < MAX_POWERUPS; i++) {
         if (ps->powerups[i]) {
             s->powerups |= 1 << i;
         }
     }
     s->loopSound = ps->loopSound;
     s->generic1 = ps->generic1;
 }
Referenced by ClientEndFrame(), and ClientThink_real().
BG_PlayerTouchesItem()
qboolean BG_PlayerTouchesItem (playerState_t * ps, entityState_t * item, int atTime)
Definition at line 1027 of file bg_misc.c.
 {
     vec3_t        origin;
     BG_EvaluateTrajectory(&item->pos, atTime, origin);
     // we are ignoring ducked differences here
     if (ps->origin[0] - origin[0] > 44
         || ps->origin[0] - origin[0] < -50
         || ps->origin[1] - origin[1] > 36
         || ps->origin[1] - origin[1] < -36
         || ps->origin[2] - origin[2] > 36
         || ps->origin[2] - origin[2] < -36) {
         return qfalse;
     }
     return qtrue;
 }
Referenced by CG_TouchItem(), and G_TouchTriggers().
BG_TouchJumpPad()
void BG_TouchJumpPad (playerState_t * ps, entityState_t * jumppad)
Definition at line 1440 of file bg_misc.c.
 {
     vec3_t    angles;
     float p;
     int effectNum;
     // spectators don't use jump pads
     if (ps->pm_type != PM_NORMAL) {
         return;
     }
     // flying characters don't hit bounce pads
     if (ps->powerups[PW_FLIGHT]) {
         return;
     }
     // if we didn't hit this same jumppad the previous frame
     // then don't play the event sound again if we are in a fat trigger
     if (ps->jumppad_ent != jumppad->number) {
         vectoangles(jumppad->origin2, angles);
         p = fabs(AngleNormalize180(angles[PITCH]));
         if (p < 45) {
             effectNum = 0;
         } else {
             effectNum = 1;
         }
         BG_AddPredictableEventToPlayerstate(EV_JUMP_PAD, effectNum, ps);
     }
     // remember hitting this jumppad this frame
     ps->jumppad_ent = jumppad->number;
     ps->jumppad_frame = ps->pmove_framecount;
     // give the player the velocity from the jumppad
     VectorCopy(jumppad->origin2, ps->velocity);
 }
Referenced by CG_TouchTriggerPrediction(), and trigger_push_touch().
PM_UpdateViewAngles()
void PM_UpdateViewAngles (playerState_t * ps, const usercmd_t * cmd)
Definition at line 1804 of file bg_pmove.c.
 {
     short        temp;
     int        i;
     if (ps->pm_type == PM_INTERMISSION || ps->pm_type == PM_SPINTERMISSION) {
         return;        // no view changes at all
     }
     if (ps->pm_type != PM_SPECTATOR && ps->stats[STAT_HEALTH] <= 0) {
         return;        // no view changes at all
     }
     // circularly clamp the angles with deltas
     for (i = 0; i < 3; i++) {
         temp = cmd->angles[i] + ps->delta_angles[i];
         if (i == PITCH) {
             // don't let the player look up or down more than 90 degrees
             if (temp > 16000) {
                 ps->delta_angles[i] = 16000 - cmd->angles[i];
                 temp = 16000;
             } else if (temp < -16000) {
                 ps->delta_angles[i] = -16000 - cmd->angles[i];
                 temp = -16000;
             }
         }
         ps->viewangles[i] = SHORT2ANGLE(temp);
     }
 }
Referenced by CG_InterpolatePlayerState(), CG_PredictPlayerState(), and PmoveSingle().
Pmove()
void Pmove (pmove_t * pmove)
Pmove Can be called by either the server or the client.
Definition at line 2023 of file bg_pmove.c.
 {
     int finalTime;
     finalTime = pmove->cmd.serverTime;
     if (finalTime < pmove->ps->commandTime)
         return; // should not happen
     if (finalTime > pmove->ps->commandTime + 1000)
         pmove->ps->commandTime = finalTime - 1000;
     pmove->ps->pmove_framecount = (pmove->ps->pmove_framecount + 1) & ((1 << PS_PMOVEFRAMECOUNTBITS) - 1);
     // chop the move up if it is too long, to prevent framerate
     // dependent behavior
     while (pmove->ps->commandTime != finalTime) {
         int msec;
         msec = finalTime - pmove->ps->commandTime;
         if (pmove->pmove_fixed) {
             if (msec > pmove->pmove_msec)
                 msec = pmove->pmove_msec;
         } else {
             if (msec > 66)
                 msec = 66;
         }
         pmove->cmd.serverTime = pmove->ps->commandTime + msec;
         PmoveSingle(pmove);
         if (pmove->ps->pm_flags & PMF_JUMP_HELD)
             pmove->cmd.upmove = 20;
     }
     //PM_CheckStuck();
 }
Referenced by CG_PredictPlayerState(), ClientThink_real(), and SpectatorThink().
Variable Documentation
bg_itemlist
gitem_t bg_itemlist[]
Definition at line 48 of file bg_misc.c.
Referenced by BG_CanItemBeGrabbed(), BG_FindItem(), BG_FindItemForHoldable(), BG_FindItemForPowerup(), BG_FindItemForWeapon(), CG_DrawPickupItem(), CG_EntityEvent(), CG_Item(), CG_ItemPickup(), CG_LoadingItem(), CG_RegisterItemSounds(), CG_RegisterItemVisuals(), CG_RegisterWeapon(), CG_TouchItem(), ClientEndFrame(), ClientThink_real(), ClientTimerActions(), Controls_InitWeapons(), FinishSpawningItem(), G_CallSpawn(), G_CheckTeamItems(), G_Damage(), LaunchItem(), Pickup_Armor(), Pickup_Health(), Pickup_Holdable(), PM_Weapon(), RegisterItem(), and UI_PlayerInfo_SetWeapon().
bg_numItems
int bg_numItems
Definition at line 935 of file bg_misc.c.
Referenced by BG_CanItemBeGrabbed(), BG_FindItemForHoldable(), BG_FindItemForPowerup(), CG_EntityEvent(), CG_Item(), CG_RegisterGraphics(), CG_RegisterItemVisuals(), CG_RegisterSounds(), and SaveRegisteredItems().