ioquake3 doxygen: C:/entry/dev/ioq3/code/renderergl2/tr_extramath.h File Reference
tr_extramath.h File Reference
Macros
#define VectorCopy2(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1])
#define VectorSet2(v, x, y) ((v)[0]=(x),(v)[1]=(y));
#define VectorCopy4(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
#define VectorSet4(v, x, y, z, w) ((v)[0]=(x),(v)[1]=(y),(v)[2]=(z),(v)[3]=(w))
#define DotProduct4(a, b) ((a)[0]*(b)[0] + (a)[1]*(b)[1] + (a)[2]*(b)[2] + (a)[3]*(b)[3])
#define VectorScale4(a, b, c) ((c)[0]=(a)[0]*(b),(c)[1]=(a)[1]*(b),(c)[2]=(a)[2]*(b),(c)[3]=(a)[3]*(b))
#define VectorCopy5(a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3],(b)[4]=(a)[4])
#define OffsetByteToFloat(a) ((float)(a) * 1.0f/127.5f - 1.0f)
#define FloatToOffsetByte(a) (byte)((a) * 127.5f + 128.0f)
#define ByteToFloat(a) ((float)(a) * 1.0f/255.0f)
#define FloatToByte(a) (byte)((a) * 255.0f)
#define SGN(x) (((x) >= 0) ? !!(x) : -1)
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#define CLAMP(a, b, c) MIN(MAX((a),(b)),(c))
Typedefs
typedef vec_t mat4_t[16]
typedef int ivec2_t[2]
typedef int ivec3_t[3]
typedef int ivec4_t[4]
Functions
void Mat4Zero (mat4_t out)
void Mat4Identity (mat4_t out)
void Mat4Copy (const mat4_t in, mat4_t out)
void Mat4Multiply (const mat4_t in1, const mat4_t in2, mat4_t out)
void Mat4Transform (const mat4_t in1, const vec4_t in2, vec4_t out)
qboolean Mat4Compare (const mat4_t a, const mat4_t b)
void Mat4Dump (const mat4_t in)
void Mat4Translation (vec3_t vec, mat4_t out)
void Mat4Ortho (float left, float right, float bottom, float top, float znear, float zfar, mat4_t out)
void Mat4View (vec3_t axes[3], vec3_t origin, mat4_t out)
void Mat4SimpleInverse (const mat4_t in, mat4_t out)
static ID_INLINE int VectorCompare4 (const vec4_t v1, const vec4_t v2)
static ID_INLINE int VectorCompare5 (const vec5_t v1, const vec5_t v2)
void VectorLerp (vec3_t a, vec3_t b, float lerp, vec3_t c)
qboolean SpheresIntersect (vec3_t origin1, float radius1, vec3_t origin2, float radius2)
void BoundingSphereOfSpheres (vec3_t origin1, float radius1, vec3_t origin2, float radius2, vec3_t origin3, float *radius3)
int NextPowerOfTwo (int in)
unsigned short FloatToHalf (float in)
float HalfToFloat (unsigned short in)
Macro Definition Documentation
ByteToFloat
#define ByteToFloat (a) ((float)(a) * 1.0f/255.0f)
Definition at line 56 of file tr_extramath.h.
CLAMP
#define CLAMP (a, b, c) MIN(MAX((a),(b)),(c))
Definition at line 96 of file tr_extramath.h.
DotProduct4
#define DotProduct4 (a, b) ((a)[0]*(b)[0] + (a)[1]*(b)[1] + (a)[2]*(b)[2] + (a)[3]*(b)[3])
Definition at line 49 of file tr_extramath.h.
FloatToByte
#define FloatToByte (a) (byte)((a) * 255.0f)
Definition at line 57 of file tr_extramath.h.
FloatToOffsetByte
#define FloatToOffsetByte (a) (byte)((a) * 127.5f + 128.0f)
Definition at line 55 of file tr_extramath.h.
MAX
#define MAX (a, b) ((a) > (b) ? (a) : (b))
Definition at line 88 of file tr_extramath.h.
MIN
#define MIN (a, b) ((a) < (b) ? (a) : (b))
Definition at line 92 of file tr_extramath.h.
OffsetByteToFloat
#define OffsetByteToFloat (a) ((float)(a) * 1.0f/127.5f - 1.0f)
Definition at line 54 of file tr_extramath.h.
SGN
#define SGN (x) (((x) >= 0) ? !!(x) : -1)
Definition at line 84 of file tr_extramath.h.
VectorCopy2
#define VectorCopy2 (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1])
Definition at line 44 of file tr_extramath.h.
VectorCopy4
#define VectorCopy4 (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3])
Definition at line 47 of file tr_extramath.h.
VectorCopy5
#define VectorCopy5 (a, b) ((b)[0]=(a)[0],(b)[1]=(a)[1],(b)[2]=(a)[2],(b)[3]=(a)[3],(b)[4]=(a)[4])
Definition at line 52 of file tr_extramath.h.
VectorScale4
#define VectorScale4 (a, b, c) ((c)[0]=(a)[0]*(b),(c)[1]=(a)[1]*(b),(c)[2]=(a)[2]*(b),(c)[3]=(a)[3]*(b))
Definition at line 50 of file tr_extramath.h.
VectorSet2
#define VectorSet2 (v, x, y) ((v)[0]=(x),(v)[1]=(y));
Definition at line 45 of file tr_extramath.h.
VectorSet4
#define VectorSet4 (v, x, y, z, w) ((v)[0]=(x),(v)[1]=(y),(v)[2]=(z),(v)[3]=(w))
Definition at line 48 of file tr_extramath.h.
Typedef Documentation
ivec2_t
typedef int ivec2_t[2]
Definition at line 28 of file tr_extramath.h.
ivec3_t
typedef int ivec3_t[3]
Definition at line 29 of file tr_extramath.h.
ivec4_t
typedef int ivec4_t[4]
Definition at line 30 of file tr_extramath.h.
mat4_t
typedef vec_t mat4_t[16]
Definition at line 27 of file tr_extramath.h.
Function Documentation
BoundingSphereOfSpheres()
void BoundingSphereOfSpheres (vec3_t origin1, float radius1, vec3_t origin2, float radius2, vec3_t origin3, float * radius3)
Definition at line 181 of file tr_extramath.c.
 {
     vec3_t diff;
     VectorScale(origin1, 0.5f, origin3);
     VectorMA(origin3, 0.5f, origin2, origin3);
     VectorSubtract(origin1, origin2, diff);
     *radius3 = VectorLength(diff) * 0.5f + MAX(radius1, radius2);
 }
Referenced by R_RenderPshadowMaps().
FloatToHalf()
unsigned short FloatToHalf (float in)
Definition at line 221 of file tr_extramath.c.
 {
     union f32_u f32;
     union f16_u f16;
     f32.f = in;
     f16.pack.exponent = CLAMP((int)(f32.pack.exponent) - 112, 0, 31);
     f16.pack.fraction = f32.pack.fraction >> 13;
     f16.pack.sign     = f32.pack.sign;
     return f16.ui;
 }
HalfToFloat()
float HalfToFloat (unsigned short in)
Mat4Compare()
qboolean Mat4Compare (const mat4_t a, const mat4_t b)
Definition at line 84 of file tr_extramath.c.
 {
     return !(a[ 0] != b[ 0] || a[ 4] != b[ 4] || a[ 8] != b[ 8] || a[12] != b[12] ||
              a[ 1] != b[ 1] || a[ 5] != b[ 5] || a[ 9] != b[ 9] || a[13] != b[13] ||
              a[ 2] != b[ 2] || a[ 6] != b[ 6] || a[10] != b[10] || a[14] != b[14] ||
              a[ 3] != b[ 3] || a[ 7] != b[ 7] || a[11] != b[11] || a[15] != b[15]);
 }
Referenced by GLSL_SetUniformMat4().
Mat4Copy()
void Mat4Copy (const mat4_t in, mat4_t out)
Definition at line 45 of file tr_extramath.c.
 {
     out[ 0] = in[ 0]; out[ 4] = in[ 4]; out[ 8] = in[ 8]; out[12] = in[12];
     out[ 1] = in[ 1]; out[ 5] = in[ 5]; out[ 9] = in[ 9]; out[13] = in[13];
     out[ 2] = in[ 2]; out[ 6] = in[ 6]; out[10] = in[10]; out[14] = in[14];
     out[ 3] = in[ 3]; out[ 7] = in[ 7]; out[11] = in[11]; out[15] = in[15];
 }
Referenced by GL_SetModelviewMatrix(), GL_SetProjectionMatrix(), GLSL_SetUniformMat4(), R_RotateForEntity(), RB_RenderFlares(), RB_StageIteratorSky(), and RE_RenderScene().
Mat4Dump()
void Mat4Dump (const mat4_t in)
Definition at line 92 of file tr_extramath.c.
 {
     ri.Printf(PRINT_ALL, "%3.5f %3.5f %3.5f %3.5f\n", in[ 0], in[ 4], in[ 8], in[12]);
     ri.Printf(PRINT_ALL, "%3.5f %3.5f %3.5f %3.5f\n", in[ 1], in[ 5], in[ 9], in[13]);
     ri.Printf(PRINT_ALL, "%3.5f %3.5f %3.5f %3.5f\n", in[ 2], in[ 6], in[10], in[14]);
     ri.Printf(PRINT_ALL, "%3.5f %3.5f %3.5f %3.5f\n", in[ 3], in[ 7], in[11], in[15]);
 }
Mat4Identity()
void Mat4Identity (mat4_t out)
Definition at line 37 of file tr_extramath.c.
 {
     out[ 0] = 1.0f; out[ 4] = 0.0f; out[ 8] = 0.0f; out[12] = 0.0f;
     out[ 1] = 0.0f; out[ 5] = 1.0f; out[ 9] = 0.0f; out[13] = 0.0f;
     out[ 2] = 0.0f; out[ 6] = 0.0f; out[10] = 1.0f; out[14] = 0.0f;
     out[ 3] = 0.0f; out[ 7] = 0.0f; out[11] = 0.0f; out[15] = 1.0f;
 }
Referenced by RB_RenderFlares(), and RB_SetGL2D().
Mat4Multiply()
void Mat4Multiply (const mat4_t in1, const mat4_t in2, mat4_t out)
Definition at line 53 of file tr_extramath.c.
 {
     out[ 0] = in1[ 0] * in2[ 0] + in1[ 4] * in2[ 1] + in1[ 8] * in2[ 2] + in1[12] * in2[ 3];
     out[ 1] = in1[ 1] * in2[ 0] + in1[ 5] * in2[ 1] + in1[ 9] * in2[ 2] + in1[13] * in2[ 3];
     out[ 2] = in1[ 2] * in2[ 0] + in1[ 6] * in2[ 1] + in1[10] * in2[ 2] + in1[14] * in2[ 3];
     out[ 3] = in1[ 3] * in2[ 0] + in1[ 7] * in2[ 1] + in1[11] * in2[ 2] + in1[15] * in2[ 3];
     out[ 4] = in1[ 0] * in2[ 4] + in1[ 4] * in2[ 5] + in1[ 8] * in2[ 6] + in1[12] * in2[ 7];
     out[ 5] = in1[ 1] * in2[ 4] + in1[ 5] * in2[ 5] + in1[ 9] * in2[ 6] + in1[13] * in2[ 7];
     out[ 6] = in1[ 2] * in2[ 4] + in1[ 6] * in2[ 5] + in1[10] * in2[ 6] + in1[14] * in2[ 7];
     out[ 7] = in1[ 3] * in2[ 4] + in1[ 7] * in2[ 5] + in1[11] * in2[ 6] + in1[15] * in2[ 7];
     out[ 8] = in1[ 0] * in2[ 8] + in1[ 4] * in2[ 9] + in1[ 8] * in2[10] + in1[12] * in2[11];
     out[ 9] = in1[ 1] * in2[ 8] + in1[ 5] * in2[ 9] + in1[ 9] * in2[10] + in1[13] * in2[11];
     out[10] = in1[ 2] * in2[ 8] + in1[ 6] * in2[ 9] + in1[10] * in2[10] + in1[14] * in2[11];
     out[11] = in1[ 3] * in2[ 8] + in1[ 7] * in2[ 9] + in1[11] * in2[10] + in1[15] * in2[11];
     out[12] = in1[ 0] * in2[12] + in1[ 4] * in2[13] + in1[ 8] * in2[14] + in1[12] * in2[15];
     out[13] = in1[ 1] * in2[12] + in1[ 5] * in2[13] + in1[ 9] * in2[14] + in1[13] * in2[15];
     out[14] = in1[ 2] * in2[12] + in1[ 6] * in2[13] + in1[10] * in2[14] + in1[14] * in2[15];
     out[15] = in1[ 3] * in2[12] + in1[ 7] * in2[13] + in1[11] * in2[14] + in1[15] * in2[15];
 }
Referenced by GL_SetModelviewMatrix(), GL_SetProjectionMatrix(), R_RenderSunShadowMaps(), RB_DrawSun(), RB_StageIteratorSky(), and RB_SunRays().
Mat4Ortho()
void Mat4Ortho (float left, float right, float bottom, float top, float znear, float zfar, mat4_t out)
Definition at line 108 of file tr_extramath.c.
 {
     out[ 0] = 2.0f / (right - left); out[ 4] = 0.0f;                  out[ 8] = 0.0f;                  out[12] = -(right + left) / (right - left);
     out[ 1] = 0.0f;                  out[ 5] = 2.0f / (top - bottom); out[ 9] = 0.0f;                  out[13] = -(top + bottom) / (top - bottom);
     out[ 2] = 0.0f;                  out[ 6] = 0.0f;                  out[10] = 2.0f / (zfar - znear); out[14] = -(zfar + znear) / (zfar - znear);
     out[ 3] = 0.0f;                  out[ 7] = 0.0f;                  out[11] = 0.0f;                  out[15] = 1.0f;
 }
Referenced by FBO_BlitFromTexture(), RB_RenderFlares(), and RB_SetGL2D().
Mat4SimpleInverse()
void Mat4SimpleInverse (const mat4_t in, mat4_t out)
Definition at line 139 of file tr_extramath.c.
 {
     vec3_t v;
     float invSqrLen;
     VectorCopy(in + 0, v);
     invSqrLen = 1.0f / DotProduct(v, v); VectorScale(v, invSqrLen, v);
     out[ 0] = v[0]; out[ 4] = v[1]; out[ 8] = v[2]; out[12] = -DotProduct(v, &in[12]);
     VectorCopy(in + 4, v);
     invSqrLen = 1.0f / DotProduct(v, v); VectorScale(v, invSqrLen, v);
     out[ 1] = v[0]; out[ 5] = v[1]; out[ 9] = v[2]; out[13] = -DotProduct(v, &in[12]);
     VectorCopy(in + 8, v);
     invSqrLen = 1.0f / DotProduct(v, v); VectorScale(v, invSqrLen, v);
     out[ 2] = v[0]; out[ 6] = v[1]; out[10] = v[2]; out[14] = -DotProduct(v, &in[12]);
     out[ 3] = 0.0f; out[ 7] = 0.0f; out[11] = 0.0f; out[15] = 1.0f;
 }
Mat4Transform()
void Mat4Transform (const mat4_t in1, const vec4_t in2, vec4_t out)
Definition at line 76 of file tr_extramath.c.
 {
     out[ 0] = in1[ 0] * in2[ 0] + in1[ 4] * in2[ 1] + in1[ 8] * in2[ 2] + in1[12] * in2[ 3];
     out[ 1] = in1[ 1] * in2[ 0] + in1[ 5] * in2[ 1] + in1[ 9] * in2[ 2] + in1[13] * in2[ 3];
     out[ 2] = in1[ 2] * in2[ 0] + in1[ 6] * in2[ 1] + in1[10] * in2[ 2] + in1[14] * in2[ 3];
     out[ 3] = in1[ 3] * in2[ 0] + in1[ 7] * in2[ 1] + in1[11] * in2[ 2] + in1[15] * in2[ 3];
 }
Referenced by R_RenderSunShadowMaps(), and RB_SunRays().
Mat4Translation()
void Mat4Translation (vec3_t vec, mat4_t out)
Definition at line 100 of file tr_extramath.c.
 {
     out[ 0] = 1.0f; out[ 4] = 0.0f; out[ 8] = 0.0f; out[12] = vec[0];
     out[ 1] = 0.0f; out[ 5] = 1.0f; out[ 9] = 0.0f; out[13] = vec[1];
     out[ 2] = 0.0f; out[ 6] = 0.0f; out[10] = 1.0f; out[14] = vec[2];
     out[ 3] = 0.0f; out[ 7] = 0.0f; out[11] = 0.0f; out[15] = 1.0f;
 }
Referenced by RB_DrawSun(), RB_StageIteratorSky(), and RB_SunRays().
Mat4View()
void Mat4View (vec3_t axes[3], vec3_t origin, mat4_t out)
Definition at line 116 of file tr_extramath.c.
 {
     out[0]  = axes[0][0];
     out[1]  = axes[1][0];
     out[2]  = axes[2][0];
     out[3]  = 0;
     out[4]  = axes[0][1];
     out[5]  = axes[1][1];
     out[6]  = axes[2][1];
     out[7]  = 0;
     out[8]  = axes[0][2];
     out[9]  = axes[1][2];
     out[10] = axes[2][2];
     out[11] = 0;
     out[12] = -DotProduct(origin, axes[0]);
     out[13] = -DotProduct(origin, axes[1]);
     out[14] = -DotProduct(origin, axes[2]);
     out[15] = 1;
 }
Referenced by R_RenderSunShadowMaps().
Mat4Zero()
void Mat4Zero (mat4_t out)
Definition at line 29 of file tr_extramath.c.
 {
     out[ 0] = 0.0f; out[ 4] = 0.0f; out[ 8] = 0.0f; out[12] = 0.0f;
     out[ 1] = 0.0f; out[ 5] = 0.0f; out[ 9] = 0.0f; out[13] = 0.0f;
     out[ 2] = 0.0f; out[ 6] = 0.0f; out[10] = 0.0f; out[14] = 0.0f;
     out[ 3] = 0.0f; out[ 7] = 0.0f; out[11] = 0.0f; out[15] = 0.0f;
 }
Referenced by RE_RenderScene().
NextPowerOfTwo()
int NextPowerOfTwo (int in)
Definition at line 192 of file tr_extramath.c.
 {
     int out;
     for (out = 1; out < in; out <<= 1)
         ;
     return out;
 }
Referenced by RawImage_ScaleToPower2().
SpheresIntersect()
qboolean SpheresIntersect (vec3_t origin1, float radius1, vec3_t origin2, float radius2)
Definition at line 166 of file tr_extramath.c.
 {
     float radiusSum = radius1 + radius2;
     vec3_t diff;
     VectorSubtract(origin1, origin2, diff);
     if (DotProduct(diff, diff) <= radiusSum * radiusSum)
     {
         return qtrue;
     }
     return qfalse;
 }
Referenced by R_DlightSurface(), R_PshadowSurface(), and R_RenderPshadowMaps().
VectorCompare4()
static ID_INLINE int VectorCompare4 (const vec4_t v1, const vec4_t v2) static
Definition at line 59 of file tr_extramath.h.
 {
     if(v1[0] != v2[0] || v1[1] != v2[1] || v1[2] != v2[2] || v1[3] != v2[3])
     {
         return 0;
     }
     return 1;
 }
Referenced by GLSL_SetUniformVec4().
VectorCompare5()
static ID_INLINE int VectorCompare5 (const vec5_t v1, const vec5_t v2) static
Definition at line 68 of file tr_extramath.h.
 {
     if(v1[0] != v2[0] || v1[1] != v2[1] || v1[2] != v2[2] || v1[3] != v2[3] || v1[4] != v2[4])
     {
         return 0;
     }
     return 1;
 }
Referenced by GLSL_SetUniformFloat5().
VectorLerp()
void VectorLerp (vec3_t a, vec3_t b, float lerp, vec3_t c)
Definition at line 159 of file tr_extramath.c.
 {
     c[0] = a[0] * (1.0f - lerp) + b[0] * lerp;
     c[1] = a[1] * (1.0f - lerp) + b[1] * lerp;
     c[2] = a[2] * (1.0f - lerp) + b[2] * lerp;
 }
Referenced by LerpMeshVertexes().