ioquake3 doxygen: C:/entry/dev/ioq3/code/qcommon/q_shared.c File Reference
q_shared.c File Reference
#include "q_shared.h"
Functions
qboolean Q_IsColorString (const char *p)
float Com_Clamp (float min, float max, float value)
char * COM_SkipPath (char *pathname)
const char * COM_GetExtension (const char *name)
void COM_StripExtension (const char *in, char *out, int destsize)
qboolean COM_CompareExtension (const char *in, const char *ext)
void COM_DefaultExtension (char *path, int maxSize, const char *extension)
void CopyShortSwap (void *dest, void *src)
void CopyLongSwap (void *dest, void *src)
short ShortSwap (short l)
short ShortNoSwap (short l)
int LongSwap (int l)
int LongNoSwap (int l)
qint64 Long64Swap (qint64 ll)
qint64 Long64NoSwap (qint64 ll)
float FloatSwap (const float *f)
float FloatNoSwap (const float *f)
void COM_BeginParseSession (const char *name)
int COM_GetCurrentParseLine (void)
char * COM_Parse (char **data_p)
void COM_ParseError (char *format,...)
void COM_ParseWarning (char *format,...)
static char * SkipWhitespace (char *data, qboolean *hasNewLines)
int COM_Compress (char *data_p)
char * COM_ParseExt (char **data_p, qboolean allowLineBreaks)
void COM_MatchToken (char **buf_p, char *match)
qboolean SkipBracedSection (char **program, int depth)
void SkipRestOfLine (char **data)
void Parse1DMatrix (char **buf_p, int x, float *m)
void Parse2DMatrix (char **buf_p, int y, int x, float *m)
void Parse3DMatrix (char **buf_p, int z, int y, int x, float *m)
int Com_HexStrToInt (const char *str)
int Q_isprint (int c)
int Q_islower (int c)
int Q_isupper (int c)
int Q_isalpha (int c)
qboolean Q_isanumber (const char *s)
qboolean Q_isintegral (float f)
int Q_vsnprintf (char *str, size_t size, const char *format, va_list ap)
void Q_strncpyz (char *dest, const char *src, int destsize)
int Q_stricmpn (const char *s1, const char *s2, int n)
int Q_strncmp (const char *s1, const char *s2, int n)
int Q_stricmp (const char *s1, const char *s2)
char * Q_strlwr (char *s1)
char * Q_strupr (char *s1)
void Q_strcat (char *dest, int size, const char *src)
const char * Q_stristr (const char *s, const char *find)
int Q_PrintStrlen (const char *string)
char * Q_CleanStr (char *string)
int Q_CountChar (const char *string, char tocount)
int QDECL Com_sprintf (char *dest, int size, const char *fmt,...)
char *QDECL va (char *format,...)
void Com_TruncateLongString (char *buffer, const char *s)
char * Info_ValueForKey (const char *s, const char *key)
void Info_NextPair (const char **head, char *key, char *value)
void Info_RemoveKey (char *s, const char *key)
void Info_RemoveKey_Big (char *s, const char *key)
qboolean Info_Validate (const char *s)
void Info_SetValueForKey (char *s, const char *key, const char *value)
void Info_SetValueForKey_Big (char *s, const char *key, const char *value)
static qboolean Com_CharIsOneOfCharset (char c, char *set)
char * Com_SkipCharset (char *s, char *sep)
char * Com_SkipTokens (char *s, int numTokens, char *sep)
Variables
static char com_token [MAX_TOKEN_CHARS]
static char com_parsename [MAX_TOKEN_CHARS]
static int com_lines
static int com_tokenline
Function Documentation
COM_BeginParseSession()
void COM_BeginParseSession (const char * name)
Definition at line 318 of file q_shared.c.
 {
     com_lines = 1;
     com_tokenline = 0;
     Com_sprintf(com_parsename, sizeof(com_parsename), "%s", name);
 }
Referenced by ScanAndLoadShaderFiles().
Com_CharIsOneOfCharset()
static qboolean Com_CharIsOneOfCharset (char c, char * set) static
Definition at line 1380 of file q_shared.c.
 {
     int i;
     for (i = 0; i < strlen(set); i++) {
         if (set[i] == c)
             return qtrue;
     }
     return qfalse;
 }
Referenced by Com_SkipCharset(), and Com_SkipTokens().
Com_Clamp()
float Com_Clamp (float min, float max, float value)
Definition at line 49 of file q_shared.c.
 {
     if (value < min) {
         return min;
     }
     if (value > max) {
         return max;
     }
     return value;
 }
Referenced by ArenaServers_MenuInit(), InitOpenGL(), PlayerSettings_SetMenuItems(), Preferences_SetMenuItems(), Punkbuster_ConfirmDisable(), Punkbuster_ConfirmEnable(), R_CreateImage2(), RB_GaussianBlur(), ServerOptions_MenuInit(), ServerOptions_SetMenuItems(), ServerOptions_Start(), Svcmd_AddBot_f(), UI_AddBotsMenu_Init(), UI_DrawHandicap(), UI_Handicap_HandleKey(), UI_OwnerDrawWidth(), UI_RunMenuScript(), and UI_SPSkillMenu_Init().
COM_CompareExtension()
qboolean COM_CompareExtension (const char * in, const char * ext)
Definition at line 119 of file q_shared.c.
 {
     int inlen, extlen;
     inlen = strlen(in);
     extlen = strlen(ext);
     if (extlen <= inlen) {
         in += inlen - extlen;
         if (!Q_stricmp(in, ext))
             return qtrue;
     }
     return qfalse;
 }
Referenced by Com_WriteConfig_f(), Con_Dump_f(), FS_CheckFilenameIsMutable(), and Sys_DllExtension().
COM_Compress()
int COM_Compress (char * data_p)
Definition at line 393 of file q_shared.c.
 {
     char* in, * out;
     int c;
     qboolean newline = qfalse, whitespace = qfalse;
     in = out = data_p;
     if (in) {
         while ((c = *in) != 0) {
             // skip double slash comments
             if (c == '/' && in[1] == '/') {
                 while (*in && *in != '\n') {
                     in++;
                 }
                 // skip /* */ comments
             } else if (c == '/' && in[1] == '*') {
                 while (*in && (*in != '*' || in[1] != '/'))
                     in++;
                 if (*in)
                     in += 2;
                 // record when we hit a newline
             } else if (c == '\n' || c == '\r') {
                 newline = qtrue;
                 in++;
                 // record when we hit whitespace
             } else if (c == ' ' || c == '\t') {
                 whitespace = qtrue;
                 in++;
                 // an actual token
             } else {
                 // if we have a pending newline, emit it (and it counts as whitespace)
                 if (newline) {
                     *out++ = '\n';
                     newline = qfalse;
                     whitespace = qfalse;
                 } if (whitespace) {
                     *out++ = ' ';
                     whitespace = qfalse;
                 }
                 // copy quoted strings unmolested
                 if (c == '"') {
                     *out++ = c;
                     in++;
                     while (1) {
                         c = *in;
                         if (c && c != '"') {
                             *out++ = c;
                             in++;
                         } else {
                             break;
                         }
                     }
                     if (c == '"') {
                         *out++ = c;
                         in++;
                     }
                 } else {
                     *out = c;
                     out++;
                     in++;
                 }
             }
         }
         *out = 0;
     }
     return out - data_p;
 }
Referenced by ScanAndLoadShaderFiles(), UI_LoadBotsFromFile(), and UI_ParseAnimationFile().
COM_DefaultExtension()
void COM_DefaultExtension (char * path, int maxSize, const char * extension)
Definition at line 144 of file q_shared.c.
 {
     const char* dot = strrchr(path, '.'), * slash;
     if (dot && (!(slash = strrchr(path, '/')) || slash < dot))
         return;
     else
         Q_strcat(path, maxSize, extension);
 }
Referenced by Cmd_Exec_f(), Com_WriteConfig_f(), and Con_Dump_f().
COM_GetCurrentParseLine()
int COM_GetCurrentParseLine (void)
Definition at line 325 of file q_shared.c.
 {
     if (com_tokenline) {
         return com_tokenline;
     }
     return com_lines;
 }
Referenced by COM_ParseError(), COM_ParseWarning(), and ScanAndLoadShaderFiles().
COM_GetExtension()
const char* COM_GetExtension (const char * name)
Definition at line 84 of file q_shared.c.
 {
     const char* dot = strrchr(name, '.'), * slash;
     if (dot && (!(slash = strrchr(name, '/')) || slash < dot))
         return dot + 1;
     else
         return "";
 }
Referenced by FS_CheckFilenameIsMutable(), R_LoadImage(), RE_RegisterModel(), and S_CodecGetSound().
Com_HexStrToInt()
int Com_HexStrToInt (const char * str)
Definition at line 672 of file q_shared.c.
 {
     if (!str)
         return -1;
     // check for hex code
     if (str[0] == '0' && str[1] == 'x' && str[2] != '\0') {
         int i, n = 0, len = strlen(str);
         for (i = 2; i < len; i++) {
             char digit;
             n *= 16;
             digit = tolower(str[i]);
             if (digit >= '0' && digit <= '9')
                 digit -= '0';
             else if (digit >= 'a' && digit <= 'f')
                 digit = digit - 'a' + 10;
             else
                 return -1;
             n += digit;
         }
         return n;
     }
     return -1;
 }
Referenced by Com_FieldStringToPlayerName(), and Key_StringToKeynum().
COM_MatchToken()
void COM_MatchToken (char ** buf_p, char * match)
Definition at line 562 of file q_shared.c.
 {
     char* token;
     token = COM_Parse(buf_p);
     if (strcmp(token, match)) {
         Com_Error(ERR_DROP, "MatchToken: %s != %s", token, match);
     }
 }
Referenced by Parse1DMatrix(), Parse2DMatrix(), and Parse3DMatrix().
COM_Parse()
char* COM_Parse (char ** data_p)
Definition at line 334 of file q_shared.c.
 {
     return COM_ParseExt(data_p, qtrue);
 }
Referenced by CG_NewParticleArea(), CG_ParseAnimationFile(), CG_StartMusic(), CL_LoadConsoleHistory(), COM_MatchToken(), G_ParseInfos(), Parse1DMatrix(), R_GetEntityToken(), SV_GameSystemCalls(), UI_ParseAnimationFile(), UI_ParseInfos(), and VM_LoadSymbols().
COM_ParseError()
void COM_ParseError (char * format, ...)
Definition at line 339 of file q_shared.c.
 {
     va_list argptr;
     static char string[4096];
     va_start(argptr, format);
     Q_vsnprintf(string, sizeof(string), format, argptr);
     va_end(argptr);
     Com_Printf("ERROR: %s, line %d: %s\n", com_parsename, COM_GetCurrentParseLine(), string);
 }
COM_ParseExt()
char* COM_ParseExt (char ** data_p, qboolean allowLineBreaks)
Definition at line 463 of file q_shared.c.
 {
     int c = 0, len;
     qboolean hasNewLines = qfalse;
     char* data;
     data = *data_p;
     len = 0;
     com_token[0] = 0;
     com_tokenline = 0;
     // make sure incoming data is valid
     if (!data) {
         *data_p = NULL;
         return com_token;
     }
     while (1) {
         // skip whitespace
         data = SkipWhitespace(data, &hasNewLines);
         if (!data) {
             *data_p = NULL;
             return com_token;
         }
         if (hasNewLines && !allowLineBreaks) {
             *data_p = data;
             return com_token;
         }
         c = *data;
         // skip double slash comments
         if (c == '/' && data[1] == '/') {
             data += 2;
             while (*data && *data != '\n') {
                 data++;
             }
         }
         // skip /* */ comments
         else if (c == '/' && data[1] == '*') {
             data += 2;
             while (*data && (*data != '*' || data[1] != '/')) {
                 if (*data == '\n') {
                     com_lines++;
                 }
                 data++;
             }
             if (*data) {
                 data += 2;
             }
         } else {
             break;
         }
     }
     // token starts on this line
     com_tokenline = com_lines;
     // handle quoted strings
     if (c == '\"') {
         data++;
         while (1) {
             c = *data++;
             if (c == '\"' || !c) {
                 com_token[len] = 0;
                 *data_p = (char*)data;
                 return com_token;
             }
             if (c == '\n') {
                 com_lines++;
             }
             if (len < MAX_TOKEN_CHARS - 1) {
                 com_token[len] = c;
                 len++;
             }
         }
     }
     // parse a regular word
     do {
         if (len < MAX_TOKEN_CHARS - 1) {
             com_token[len] = c;
             len++;
         }
         data++;
         c = *data;
     } while (c > 32);
     com_token[len] = 0;
     *data_p = (char*)data;
     return com_token;
 }
Referenced by Alias_Parse(), Character_Parse(), COM_Parse(), FindShaderInShaderText(), Float_Parse(), G_ParseInfos(), GameType_Parse(), GametypeBits(), Int_Parse(), MapList_Parse(), ParseDeform(), ParseShader(), ParseSkyParms(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseTexMod(), ParseVector(), ParseWaveForm(), R_LoadEntities(), ScanAndLoadShaderFiles(), SkipBracedSection(), String_Parse(), Team_Parse(), UI_ParseGameInfo(), UI_ParseInfos(), and UI_ParseTeamInfo().
COM_ParseWarning()
void COM_ParseWarning (char * format, ...)
Definition at line 351 of file q_shared.c.
 {
     va_list argptr;
     static char string[4096];
     va_start(argptr, format);
     Q_vsnprintf(string, sizeof(string), format, argptr);
     va_end(argptr);
     Com_Printf("WARNING: %s, line %d: %s\n", com_parsename, COM_GetCurrentParseLine(), string);
 }
Com_SkipCharset()
char* Com_SkipCharset (char * s, char * sep)
Definition at line 1397 of file q_shared.c.
 {
     char* p = s;
     while (p) {
         if (Com_CharIsOneOfCharset(*p, sep))
             p++;
         else
             break;
     }
     return p;
 }
Referenced by Field_CompleteCommand().
COM_SkipPath()
char* COM_SkipPath (char * pathname)
Definition at line 66 of file q_shared.c.
 {
     char* last;
     last = pathname;
     while (*pathname) {
         if (*pathname == '/')
             last = pathname + 1;
         pathname++;
     }
     return last;
 }
Referenced by CL_Frame(), and RE_LoadWorldMap().
Com_SkipTokens()
char* Com_SkipTokens (char * s, int numTokens, char * sep)
Definition at line 1416 of file q_shared.c.
 {
     int        sepCount = 0;
     char* p = s;
     while (sepCount < numTokens) {
         if (Com_CharIsOneOfCharset(*p++, sep)) {
             sepCount++;
             while (Com_CharIsOneOfCharset(*p, sep))
                 p++;
         } else if (*p == '\0')
             break;
     }
     if (sepCount == numTokens)
         return p;
     else
         return s;
 }
Referenced by CL_CompleteRcon(), Cvar_CompleteCvarName(), Key_CompleteBind(), and Key_CompleteUnbind().
Com_sprintf()
int QDECL Com_sprintf (char * dest, int size, const char * fmt, ...)
Definition at line 1000 of file q_shared.c.
 {
     int        len;
     va_list        argptr;
     va_start(argptr, fmt);
     len = Q_vsnprintf(dest, size, fmt, argptr);
     va_end(argptr);
     if (len >= size)
         Com_Printf("Com_sprintf: Output length %d too short, require %d bytes.\n", size, len + 1);
     return len;
 }
Referenced by AAS_LoadFiles(), AAS_ReadRouteCache(), AAS_WriteRouteCache(), ArenaServers_SetType(), ArenaServers_UpdateMenu(), ArenaServers_UpdatePicture(), BotGetActivateGoal(), BotInitLibrary(), BotMatch_CheckPoint(), BotPrintActivateGoalInfo(), BotRecordNodeSwitch(), BotReportStatus(), BotSayTeamOrderAlways(), BotSetInfoConfigString(), BuildShaderStateConfig(), CG_DrawAreaPowerUp(), CG_DrawBlueScore(), CG_DrawClientScore(), CG_DrawField(), CG_DrawPlayerAmmoValue(), CG_DrawPlayerArmorValue(), CG_DrawPlayerHealth(), CG_DrawPlayerScore(), CG_DrawRedScore(), CG_DrawReward(), CG_DrawSelectedPlayerArmor(), CG_DrawSelectedPlayerHealth(), CG_DrawTeamOverlay(), CG_FindClientHeadFile(), CG_FindClientModelFile(), CG_HarvesterSkulls(), CG_LoadingClient(), CG_ParseServerinfo(), CG_PlaceString(), CG_RegisterClientModelname(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_TellAttacker_f(), CG_TellTarget_f(), CIN_PlayCinematic(), CL_BeginDownload(), CL_CheckForResend(), CL_CompleteDemoName(), CL_DemoCompleted(), CL_DemoFilename(), CL_GetServerCommand(), CL_GlobalServers_f(), CL_InitCGame(), CL_InitRef(), CL_ParseBinding(), CL_PlayDemo_f(), CL_Record_f(), CL_RequestMotd(), CL_SendPureChecksums(), CL_ServerStatusResponse(), CL_Video_f(), CL_WalkDemoExt(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Com_AppendCDKey(), COM_BeginParseSession(), Com_ReadCDKey(), Com_WriteCDKey(), CON_Input(), Console_Key(), Cvar_SetValue(), Cvar_SetValueSafe(), Cvar_Validate(), Cvar_WriteVariables(), DeathmatchScoreboardMessage(), Demos_MenuInit(), FS_BuildOSPath(), FS_CheckPak0(), FS_ComparePaks(), FS_FindVM(), FS_GetModDescription(), G_ItemDisabled(), G_LogPrintf(), G_RemapTeamShaders(), G_Say(), GL_CheckErrs(), GLSL_LoadGPUShaderText(), GraphicsOptions_GetAspectRatios(), GraphicsOptions_GetResolutions(), Hunk_Log(), Hunk_SmallLog(), Info_SetValueForKey(), Info_SetValueForKey_Big(), Item_ApplyHacks(), LoadScriptFile(), Message_Key(), NET_AdrToString(), NET_AdrToStringwPort(), ParseSkyParms(), PlayerIcon(), PlayerModel_BuildList(), PS_SetBaseFolder(), R_LevelShot(), R_LoadCubemaps(), R_LoadEnvironmentJson(), R_LoadLightGrid(), R_LoadLightmaps(), R_LoadSubmodels(), R_LoadSurfaces(), R_RegisterMD3(), R_ScreenShot_f(), R_ScreenshotFilename(), R_ScreenshotFilenameJPEG(), R_ScreenShotJPEG_f(), RB_ExportCubemaps(), RE_RegisterFont(), RE_RegisterModel(), S_CodecGetSound(), ScanAndLoadShaderFiles(), ServerOptions_SetMenuItems(), ServerOptions_Start(), ServerPlayerIcon(), SP_target_speaker(), SpecifyServer_Event(), SpecifyServer_MenuInit(), StartServer_Cache(), StartServer_Update(), SV_ClientCommand(), SV_Map_f(), SV_RehashBans_f(), SV_WriteBans(), SV_WriteDownloadToClient(), SVC_Status(), Sys_AnsiColorPrint(), Sys_DefaultHomePath(), Sys_InitPIDFile(), Sys_ListFiles(), Sys_ListFilteredFiles(), Sys_LoadDll(), Team_GetLocationMsg(), TeamplayInfoMessage(), UI_BuildFindPlayerList(), UI_BuildQ3Model_List(), UI_CalcPostGameStats(), UI_CanShowTierVideo(), UI_DrawConnectScreen(), UI_FeederItemText(), UI_FindClientHeadFile(), UI_GetAwardLevel(), UI_GetBestScore(), UI_GetServerStatusInfo(), UI_hasSkinForBase(), UI_LoadBestScores(), UI_LoadDemos(), UI_LogAwardData(), UI_NetSource_HandleKey(), UI_PrintTime(), UI_ReadableSize(), UI_RegisterClientModelname(), UI_RegisterClientSkin(), UI_ResolutionToAspect(), UI_RunMenuScript(), UI_SetBestScore(), UI_ShowTierVideo(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetMenuArena(), UI_SPPostgameMenu_DrawAwardsMedals(), UI_SPUnlock_f(), UI_SPUnlockMedals_f(), UI_StartSkirmish(), UI_TeamOrdersMenu_ListEvent(), UpdateTournamentInfo(), VM_LoadQVM(), VM_LoadSymbols(), VM_ValueToSymbol(), vtos(), WriteFloat(), and Z_LogZoneHeap().
COM_StripExtension()
void COM_StripExtension (const char * in, char * out, int destsize)
Definition at line 99 of file q_shared.c.
 {
     const char* dot = strrchr(in, '.'), * slash;
     if (dot && (!(slash = strrchr(in, '/')) || slash < dot))
         destsize = (destsize < dot - in + 1 ? destsize : dot - in + 1);
     if (in == out && destsize > 1)
         out[destsize - 1] = '\0';
     else
         Q_strncpyz(out, in, destsize);
 }
Referenced by CG_RegisterWeapon(), CL_Frame(), CollapseStagesToLightall(), FS_FilenameCompletion(), PlayerModel_BuildList(), R_FindImageFile(), R_FindShader(), R_FindShaderByName(), R_LoadImage(), R_RemapShader(), RB_ExportCubemaps(), RE_LoadWorldMap(), RE_RegisterModel(), S_CodecGetSound(), UI_BuildQ3Model_List(), UI_PlayerInfo_SetWeapon(), UI_SaveConfigMenu_SaveEvent(), and VM_LoadSymbols().
Com_TruncateLongString()
void Com_TruncateLongString (char * buffer, const char * s)
Definition at line 1047 of file q_shared.c.
 {
     int length = strlen(s);
     if (length <= TRUNCATE_LENGTH)
         Q_strncpyz(buffer, s, TRUNCATE_LENGTH);
     else {
         Q_strncpyz(buffer, s, (TRUNCATE_LENGTH / 2) - 3);
         Q_strcat(buffer, TRUNCATE_LENGTH, " ... ");
         Q_strcat(buffer, TRUNCATE_LENGTH, s + length - (TRUNCATE_LENGTH / 2) + 3);
     }
 }
Referenced by PrintCvarMatches().
CopyLongSwap()
void CopyLongSwap (void * dest, void * src)
Definition at line 190 of file q_shared.c.
 {
     byte* to = dest, * from = src;
     to[0] = from[3];
     to[1] = from[2];
     to[2] = from[1];
     to[3] = from[0];
 }
CopyShortSwap()
void CopyShortSwap (void * dest, void * src)
Definition at line 182 of file q_shared.c.
 {
     byte* to = dest, * from = src;
     to[0] = from[1];
     to[1] = from[0];
 }
FloatNoSwap()
float FloatNoSwap (const float * f)
Definition at line 263 of file q_shared.c.
 {
     return *f;
 }
FloatSwap()
float FloatSwap (const float * f)
Definition at line 253 of file q_shared.c.
 {
     floatint_t out;
     out.f = *f;
     out.ui = LongSwap(out.ui);
     return out.f;
 }
Info_NextPair()
void Info_NextPair (const char ** head, char * key, char * value)
Definition at line 1132 of file q_shared.c.
 {
     char* o;
     const char* s;
     s = *head;
     if (*s == '\\') {
         s++;
     }
     key[0] = 0;
     value[0] = 0;
     o = key;
     while (*s != '\\') {
         if (!*s) {
             *o = 0;
             *head = s;
             return;
         }
         *o++ = *s++;
     }
     *o = 0;
     s++;
     o = value;
     while (*s != '\\' && *s) {
         *o++ = *s++;
     }
     *o = 0;
     *head = s;
 }
Referenced by CL_SystemInfoChanged(), ServerInfo_MenuDraw(), and UI_ServerInfoMenu().
Info_RemoveKey()
void Info_RemoveKey (char * s, const char * key)
Definition at line 1172 of file q_shared.c.
 {
     char* start;
     char    pkey[MAX_INFO_KEY];
     char    value[MAX_INFO_VALUE];
     char* o;
     if (strlen(s) >= MAX_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_RemoveKey: oversize infostring");
     }
     if (strchr(key, '\\')) {
         return;
     }
     while (1) {
         start = s;
         if (*s == '\\')
             s++;
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value;
         while (*s != '\\' && *s) {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp(key, pkey)) {
             memmove(start, s, strlen(s) + 1); // remove this part
             return;
         }
         if (!*s)
             return;
     }
 }
Referenced by Info_SetValueForKey().
Info_RemoveKey_Big()
void Info_RemoveKey_Big (char * s, const char * key)
Definition at line 1225 of file q_shared.c.
 {
     char* start;
     char    pkey[BIG_INFO_KEY];
     char    value[BIG_INFO_VALUE];
     char* o;
     if (strlen(s) >= BIG_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_RemoveKey_Big: oversize infostring");
     }
     if (strchr(key, '\\')) {
         return;
     }
     while (1) {
         start = s;
         if (*s == '\\')
             s++;
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value;
         while (*s != '\\' && *s) {
             if (!*s)
                 return;
             *o++ = *s++;
         }
         *o = 0;
         if (!strcmp(key, pkey)) {
             memmove(start, s, strlen(s) + 1); // remove this part
             return;
         }
         if (!*s)
             return;
     }
 }
Referenced by Info_SetValueForKey_Big().
Info_SetValueForKey()
void Info_SetValueForKey (char * s, const char * key, const char * value)
Definition at line 1301 of file q_shared.c.
 {
     char    newi[MAX_INFO_STRING];
     const char* blacklist = "\\;\"";
     if (strlen(s) >= MAX_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_SetValueForKey: oversize infostring");
     }
     for (; *blacklist; ++blacklist) {
         if (strchr(key, *blacklist) || strchr(value, *blacklist)) {
             Com_Printf(S_COLOR_YELLOW "Can't use keys or values with a '%c': %s = %s\n", *blacklist, key, value);
             return;
         }
     }
     Info_RemoveKey(s, key);
     if (!value || !strlen(value))
         return;
     Com_sprintf(newi, sizeof(newi), "\\%s\\%s", key, value);
     if (strlen(newi) + strlen(s) >= MAX_INFO_STRING) {
         Com_Printf("Info string length exceeded\n");
         return;
     }
     strcat(newi, s);
     strcpy(s, newi);
 }
Referenced by ArenaServers_DoRefresh(), BotDeathmatchAI(), BotSetUserInfo(), CL_CheckForResend(), CL_RequestMotd(), CL_ServerInfoPacket(), Cmd_TeamTask_f(), Cvar_InfoString(), G_AddBot(), G_LoadArenas(), G_ParseInfos(), LAN_GetServerInfo(), SV_DirectConnect(), SV_RankNewGameCBF(), SV_UserinfoChanged(), SVC_Info(), SVC_Status(), UI_LoadArenas(), UI_LogAwardData(), UI_ParseInfos(), UI_SetBestScore(), UI_ShowTierVideo(), UI_SPUnlock_f(), and UI_SPUnlockMedals_f().
Info_SetValueForKey_Big()
void Info_SetValueForKey_Big (char * s, const char * key, const char * value)
Definition at line 1340 of file q_shared.c.
 {
     char    newi[BIG_INFO_STRING];
     const char* blacklist = "\\;\"";
     if (strlen(s) >= BIG_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_SetValueForKey: oversize infostring");
     }
     for (; *blacklist; ++blacklist) {
         if (strchr(key, *blacklist) || strchr(value, *blacklist)) {
             Com_Printf(S_COLOR_YELLOW "Can't use keys or values with a '%c': %s = %s\n", *blacklist, key, value);
             return;
         }
     }
     Info_RemoveKey_Big(s, key);
     if (!value)
         return;
     Com_sprintf(newi, sizeof(newi), "\\%s\\%s", key, value);
     if (strlen(newi) + strlen(s) >= BIG_INFO_STRING) {
         Com_Printf("BIG Info string length exceeded\n");
         return;
     }
     strcat(s, newi);
 }
Referenced by Cvar_InfoString_Big().
Info_Validate()
qboolean Info_Validate (const char * s)
Definition at line 1283 of file q_shared.c.
 {
     if (strchr(s, '\"')) {
         return qfalse;
     }
     if (strchr(s, ';')) {
         return qfalse;
     }
     return qtrue;
 }
Referenced by ClientUserinfoChanged().
Info_ValueForKey()
char* Info_ValueForKey (const char * s, const char * key)
Definition at line 1077 of file q_shared.c.
 {
     char    pkey[BIG_INFO_KEY];
     static    char value[2][BIG_INFO_VALUE];    // use two buffers so compares
                                             // work without stomping on each other
     static    int    valueindex = 0;
     char* o;
     if (!s || !key) {
         return "";
     }
     if (strlen(s) >= BIG_INFO_STRING) {
         Com_Error(ERR_DROP, "Info_ValueForKey: oversize infostring");
     }
     valueindex ^= 1;
     if (*s == '\\')
         s++;
     while (1) {
         o = pkey;
         while (*s != '\\') {
             if (!*s)
                 return "";
             *o++ = *s++;
         }
         *o = 0;
         s++;
         o = value[valueindex];
         while (*s != '\\' && *s) {
             *o++ = *s++;
         }
         *o = 0;
         if (!Q_stricmp(key, pkey))
             return value[valueindex];
         if (!*s)
             break;
         s++;
     }
     return "";
 }
Referenced by ArenaServers_Insert(), BotFirstClientInRankings(), BotIsFirstInRankings(), BotIsLastInRankings(), BotIsObserver(), BotLastClientInRankings(), BotMapScripts(), BotMapTitle(), BotNumActivePlayers(), BotNumTeamMates(), BotRandomOpponentName(), BotSortTeamMatesByBaseTravelTime(), BotTeamOrders(), BotTeamplayReport(), BotUpdateInfoConfigStrings(), CG_DrawAttacker(), CG_DrawInformation(), CG_LoadingClient(), CG_NewClientInfo(), CG_Obituary(), CG_ParseServerinfo(), CL_CompletePlayerName(), CL_InitCGame(), CL_MotdPacket(), CL_ParseServerInfo(), CL_Sayto_f(), CL_ServerInfoPacket(), CL_SetServerInfo(), CL_SystemInfoChanged(), ClientConnect(), ClientFromName(), ClientName(), ClientOnSameTeamFromName(), ClientSkin(), ClientSpawn(), ClientUserinfoChanged(), G_AddBot(), G_BotConnect(), G_CheckBotSpawn(), G_GetArenaInfoByMap(), G_GetBotInfoByName(), G_InitBots(), G_InitSessionData(), G_SelectRandomBotInfo(), InGame_MenuInit(), Prepname(), ServerOptions_InitBotNames(), ServerOptions_SetMenuItems(), ServerOptions_Start(), StartServer_Cache(), StartServer_GametypeEvent(), StartServer_LevelshotDraw(), StartServer_Update(), SV_DirectConnect(), SV_SetUserinfo(), SV_UserinfoChanged(), Svcmd_BotList_f(), TeamMain_MenuInit(), UI_AddBotsMenu_Init(), UI_AddBotsMenu_SetBotNames(), UI_AddBotsMenu_SortCompare(), UI_BotSelectMenu_Default(), UI_BotSelectMenu_SortCompare(), UI_BotSelectMenu_UpdateGrid(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_BuildServerDisplayList(), UI_CalcPostGameStats(), UI_CanShowTierVideo(), UI_DrawConnectScreen(), UI_FeederItemText(), UI_FeederSelection(), UI_GetArenaInfoByMap(), UI_GetArenaInfoByNumber(), UI_GetAwardLevel(), UI_GetBestScore(), UI_GetBotInfoByName(), UI_GetBotNameByNumber(), UI_GetCurrentGame(), UI_GetSpecialArenaInfo(), UI_LoadArenas(), UI_LoadArenasIntoMapList(), UI_LogAwardData(), UI_RemoveBotsMenu_GetBots(), UI_RemoveBotsMenu_SetBotNames(), UI_RunMenuScript(), UI_SetBestScore(), UI_ShowTierVideo(), UI_SPArena_Start(), UI_SPLevelMenu(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetBots(), UI_SPLevelMenu_SetMenuArena(), UI_SPLevelMenu_SetMenuItems(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_TeamOrdersMenu_BuildBotList(), UI_TeamOrdersMenu_f(), and UI_TierCompleted().
Long64NoSwap()
qint64 Long64NoSwap (qint64 ll)
Definition at line 248 of file q_shared.c.
 {
     return ll;
 }
Long64Swap()
qint64 Long64Swap (qint64 ll)
Definition at line 232 of file q_shared.c.
 {
     qint64    result;
     result.b0 = ll.b7;
     result.b1 = ll.b6;
     result.b2 = ll.b5;
     result.b3 = ll.b4;
     result.b4 = ll.b3;
     result.b5 = ll.b2;
     result.b6 = ll.b1;
     result.b7 = ll.b0;
     return result;
 }
LongNoSwap()
int LongNoSwap (int l)
Definition at line 227 of file q_shared.c.
 {
     return l;
 }
LongSwap()
int LongSwap (int l)
Definition at line 215 of file q_shared.c.
 {
     byte    b1, b2, b3, b4;
     b1 = l & 255;
     b2 = (l >> 8) & 255;
     b3 = (l >> 16) & 255;
     b4 = (l >> 24) & 255;
     return ((int)b1 << 24) + ((int)b2 << 16) + ((int)b3 << 8) + b4;
 }
Referenced by FloatSwap().
Parse1DMatrix()
void Parse1DMatrix (char ** buf_p, int x, float * m)
Definition at line 626 of file q_shared.c.
 {
     char* token;
     int        i;
     COM_MatchToken(buf_p, "(");
     for (i = 0; i < x; i++) {
         token = COM_Parse(buf_p);
         m[i] = atof(token);
     }
     COM_MatchToken(buf_p, ")");
 }
Referenced by Parse2DMatrix().
Parse2DMatrix()
void Parse2DMatrix (char ** buf_p, int y, int x, float * m)
Definition at line 641 of file q_shared.c.
 {
     int        i;
     COM_MatchToken(buf_p, "(");
     for (i = 0; i < y; i++) {
         Parse1DMatrix(buf_p, x, m + i * x);
     }
     COM_MatchToken(buf_p, ")");
 }
Referenced by Parse3DMatrix().
Parse3DMatrix()
void Parse3DMatrix (char ** buf_p, int z, int y, int x, float * m)
Definition at line 654 of file q_shared.c.
 {
     int        i;
     COM_MatchToken(buf_p, "(");
     for (i = 0; i < z; i++) {
         Parse2DMatrix(buf_p, y, x, m + i * x * y);
     }
     COM_MatchToken(buf_p, ")");
 }
Q_CleanStr()
char* Q_CleanStr (char * string)
Definition at line 967 of file q_shared.c.
 {
     char* d;
     char* s;
     int        c;
     s = string;
     d = string;
     while ((c = *s) != 0) {
         if (Q_IsColorString(s)) {
             s++;
         } else if (c >= 0x20 && c <= 0x7E) {
             *d++ = c;
         }
         s++;
     }
     *d = '\0';
     return string;
 }
Referenced by ArenaServers_Insert(), CG_DrawInformation(), CG_LoadingClient(), CL_CompletePlayerName(), CL_Sayto_f(), ClientFromName(), ClientName(), ClientNumberFromString(), ClientOnSameTeamFromName(), Cmd_CallTeamVote_f(), Controls_MenuInit(), PlayerModel_SetMenuItems(), PlayerSettings_DrawName(), Prepname(), Rankings_DrawName(), ServerOptions_InitPlayerItems(), SV_CompletePlayerName(), SV_ConSayto_f(), SV_GetPlayerByHandle(), Sys_InitPIDFile(), UI_BotSelectMenu_UpdateGrid(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_RemoveBotsMenu_SetBotNames(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetBots(), UI_SPPostgameMenu_MenuDrawScoreLine(), and UI_TeamOrdersMenu_BuildBotList().
Q_CountChar()
int Q_CountChar (const char * string, char tocount)
Definition at line 988 of file q_shared.c.
 {
     int count;
     for (count = 0; *string; string++) {
         if (*string == tocount)
             count++;
     }
     return count;
 }
Referenced by NET_IP6Socket(), and NET_StringToAdr().
Q_isalpha()
int Q_isalpha (int c)
Definition at line 733 of file q_shared.c.
 {
     if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z'))
         return (1);
     return (0);
 }
Referenced by MenuField_Key(), Rankings_DrawName(), and Rankings_DrawPassword().
Q_isanumber()
qboolean Q_isanumber (const char * s)
Definition at line 740 of file q_shared.c.
 {
     char* p;
     double UNUSED_VAR d;
     if (*s == '\0')
         return qfalse;
     d = strtod(s, &p);
     return *p == '\0';
 }
Referenced by Cvar_Validate().
Q_IsColorString()
qboolean Q_IsColorString (const char * p)
Definition at line 27 of file q_shared.c.
 {
     if (!p)
         return qfalse;
     if (p[0] != Q_COLOR_ESCAPE)
         return qfalse;
     if (p[1] == 0)
         return qfalse;
     // isalnum expects a signed integer in the range -1 (EOF) to 255, or it might assert on undefined behaviour
     // a dereferenced char pointer has the range -128 to 127, so we just need to rangecheck the negative part
     if (p[1] < 0)
         return qfalse;
     if (isalnum(p[1]) == 0)
         return qfalse;
     return qtrue;
 }
Referenced by CG_AddToTeamChat(), CG_DrawStringExt(), CG_DrawStrlen(), CG_Text_Paint_Limit(), CL_ConsolePrint(), ClientCleanName(), CON_Show(), CON_WindowsColorPrint(), PlayerSettings_DrawName(), Q_CleanStr(), Q_PrintStrlen(), RemoveColorEscapeSequences(), SCR_DrawSmallStringExt(), SCR_DrawStringExt(), SCR_Strlen(), SV_Strlen(), Sys_AnsiColorPrint(), Text_Height(), Text_Paint(), Text_Paint_Limit(), Text_PaintWithCursor(), Text_Width(), and UI_DrawString2().
Q_isintegral()
qboolean Q_isintegral (float f)
Definition at line 753 of file q_shared.c.
 {
     return (int)f == f;
 }
Referenced by Cvar_SetValueSafe(), and Cvar_Validate().
Q_islower()
int Q_islower (int c)
Definition at line 719 of file q_shared.c.
 {
     if (c >= 'a' && c <= 'z')
         return (1);
     return (0);
 }
Referenced by MenuField_Key().
Q_isprint()
int Q_isprint (int c)
Definition at line 712 of file q_shared.c.
 {
     if (c >= 0x20 && c <= 0x7E)
         return (1);
     return (0);
 }
Referenced by ScrollList_Key().
Q_isupper()
int Q_isupper (int c)
Definition at line 726 of file q_shared.c.
 {
     if (c >= 'A' && c <= 'Z')
         return (1);
     return (0);
 }
Referenced by MenuField_Key(), and ScrollList_Key().
Q_PrintStrlen()
int Q_PrintStrlen (const char * string)
Definition at line 943 of file q_shared.c.
 {
     int            len;
     const char* p;
     if (!string) {
         return 0;
     }
     len = 0;
     p = string;
     while (*p) {
         if (Q_IsColorString(p)) {
             p += 2;
             continue;
         }
         p++;
         len++;
     }
     return len;
 }
Referenced by CG_DrawAttacker().
Q_strcat()
void Q_strcat (char * dest, int size, const char * src)
Definition at line 904 of file q_shared.c.
 {
     int        l1;
     l1 = strlen(dest);
     if (l1 >= size) {
         Com_Error(ERR_FATAL, "Q_strcat: already overflowed");
     }
     Q_strncpyz(dest + l1, src, size - l1);
 }
Referenced by BuildShaderStateConfig(), CG_BuildSpectatorString(), CG_RegisterWeapon(), CL_GlobalServers_f(), CL_Rcon_f(), CL_SaveConsoleHistory(), CL_ServerInfoPacket(), CollapseStagesToLightall(), COM_DefaultExtension(), Com_MD5File(), Com_Printf(), Com_TruncateLongString(), Con_Dump_f(), Field_Complete(), Field_CompletePlayerNameFinal(), FS_CheckPak0(), FS_ComparePaks(), FS_LoadedPakChecksums(), FS_LoadedPakNames(), FS_LoadedPakPureChecksums(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), FS_ReferencedPakPureChecksums(), GLSL_GetShaderHeader(), GLSL_InitGPUShaders(), Item_EnableShowViaCvar(), Item_RunScript(), main(), ParseStage(), PC_Directive_include(), PC_Script_Parse(), PlayerModel_SetMenuItems(), R_FindImageFile(), R_LoadImage(), RB_ExportCubemaps(), S_AL_Init(), ServerInfo_MenuDraw(), SVC_RemoteCommand(), Sys_DefaultHomePath(), Sys_SteamPath(), UI_PlayerInfo_SetWeapon(), UI_RunMenuScript(), and UpdateIPBans().
Q_stricmp()
int Q_stricmp (const char * s1, const char * s2)
Definition at line 872 of file q_shared.c.
 {
     return (s1 && s2) ? Q_stricmpn(s1, s2, 99999) : -1;
 }
Referenced by AddRemap(), Alias_Parse(), ArenaServers_Compare(), ArenaServers_DoRefresh(), ArenaServers_LoadFavorites(), ArenaServers_Remove(), Asset_Parse(), BG_FindItem(), BindingFromName(), BindingIDFromName(), BotAI(), BotAlreadySelected(), BotChooseInitialChatMessage(), BotFindWayPoint(), BotGetLevelItemGoal(), BotGetMapLocationGoal(), BotGetTeamMateTaskPreference(), BotLoadInitialChat(), BotMapScripts(), BotMatch_CTF(), BotMatch_StopTeamLeaderShip(), BotMatch_TaskPreference(), BotMatch_WhatIsMyCommand(), BotMatch_WhoIsTeamLeader(), BotNearestVisibleItem(), BotNumInitialChats(), BotReportStatus(), BotSetBrushModelTypes(), BotSetEntityNumForGoal(), BotSetEntityNumForGoalWithActivator(), BotSetInfoConfigString(), BotTeamAI(), BotVoiceChat_StopLeader(), BotVoiceChat_WhoIsLeader(), BotVoiceChatCommand(), CG_ClientNumFromName(), CG_ConsoleCommand(), CG_ParseAnimationFile(), CG_ParticleExplosion(), CG_ScanForExistingClientInfo(), CG_ServerCommand(), CG_SetDeferredClientInfo(), Character_Parse(), CheckCvars(), CL_BindUICommand(), CL_CDKeyValidate(), CL_ConnectionlessPacket(), CL_GlobalServers_f(), CL_MapLoading(), CL_OpenAVIForWriting(), CL_PlayCinematic_f(), CL_Sayto_f(), CL_SystemInfoChanged(), ClientCommand(), ClientConnect(), ClientForString(), ClientFromName(), ClientNumberFromString(), ClientOnSameTeamFromName(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_CompleteArgument(), Cmd_Exec_f(), Cmd_ExecuteString(), Cmd_FindCommand(), Cmd_Give_f(), Cmd_SetCommandCompletionFunc(), COM_CompareExtension(), Com_SafeMode(), ConsoleCommand(), Controls_GetKeyAssignment(), Cvar_FindVar(), Cvar_Print(), Cvar_WriteVariables(), ExitLevel(), Favorites_Add(), Field_CompletePlayerName(), FindClientByName(), FindEnemyByName(), FindShaderInShaderText(), FS_AddFileToList(), FS_AddGameDirectory(), FS_CheckPak0(), FS_FOpenFileReadDir(), FS_GetFileList(), FS_GetModList(), FS_IsExt(), FS_ListFilteredFiles(), FS_LoadZipFile(), FS_Restart(), FS_Startup(), FS_SV_FOpenFileRead(), G_AddBot(), G_CountBotPlayersByName(), G_Find(), G_GetArenaInfoByMap(), G_GetBotInfoByName(), G_InitBots(), G_ParseField(), G_SpawnString(), GameType_Parse(), GametypeBits(), GL_TextureMode(), GraphicsOptions_FindBuiltinResolution(), GraphicsOptions_FindDetectedResolution(), GraphicsOptions_GetAspectRatios(), GraphicsOptions_SetMenuItems(), Hunk_SmallLog(), Info_ValueForKey(), Item_ApplyHacks(), Item_EnableShowViaCvar(), Item_Multi_FindCvarByValue(), Item_Multi_Setting(), Item_RunScript(), Key_GetKey(), Key_StringToKeynum(), KeywordHash_Find(), LAN_CompareServers(), LibVarGet(), LoadConfig_MenuInit(), MapList_Parse(), Menu_FindItemByName(), Menu_GetMatchingItemByNumber(), Menu_ItemsMatchingGroup(), MenuParse_name(), Menus_ActivateByName(), Menus_FindByName(), NameToAFunc(), NameToDstBlendMode(), NameToGenFunc(), NameToSrcBlendMode(), ParseDeform(), ParseShader(), ParseSort(), ParseStage(), ParseSurfaceParm(), ParseTexMod(), PC_PushScript(), PC_Script_Parse(), PlayerIcon(), PlayerIntroSound(), PlayerModel_SetMenuItems(), R_FindShader(), R_FindShaderByName(), R_LoadCubemapEntities(), R_LoadEntities(), R_LoadImage(), R_RemapShader(), RE_BeginFrame(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterShaderFromImage(), RE_RegisterSkin(), S_AL_Init(), S_CodecGetSound(), S_FindName(), Script_SetColor(), Script_SetItemColor(), ServerPlayerIcon(), SetTeam(), SP_worldspawn(), SV_AuthorizeIpPacket(), SV_ConnectionlessPacket(), SV_ConSayto_f(), SV_GetPlayerByHandle(), SV_Kick_f(), SV_Map_f(), SV_MasterHeartbeat(), SV_UserinfoChanged(), SV_WriteDownloadToClient(), Sys_ListFiles(), Sys_ListFilteredFiles(), target_location_linkup(), Team_Parse(), UI_AddBotsMenu_SortCompare(), UI_AIFromName(), UI_AIIndex(), UI_AIIndexFromName(), UI_BotSelectMenu_Default(), UI_BotSelectMenu_SortCompare(), UI_BuildQ3Model_List(), UI_BuildServerDisplayList(), UI_ConsoleCommand(), UI_DrawConnectScreen(), UI_EnglishMapName(), UI_GetArenaInfoByMap(), UI_GetBotInfoByName(), UI_GetSpecialArenaInfo(), UI_HeadCountByTeam(), UI_LoadMenus(), UI_LoadMovies(), UI_OpponentLeaderModel(), UI_ParseAnimationFile(), UI_ParseGameInfo(), UI_ParseMenu(), UI_ParseTeamInfo(), UI_ResolutionToAspect(), UI_RunMenuScript(), UI_SortServerStatusInfo(), UI_SPArena_Start(), UI_SPLevelMenu_MenuDraw(), UI_TeamArenaExists(), UI_TeamIndexFromName(), UI_Update(), and VM_Create().
Q_stricmpn()
int Q_stricmpn (const char * s1, const char * s2, int n)
Definition at line 814 of file q_shared.c.
 {
     int        c1, c2;
     if (s1 == NULL) {
         if (s2 == NULL)
             return 0;
         else
             return -1;
     } else if (s2 == NULL)
         return 1;
     do {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--) {
             return 0;        // strings are equal until end point
         }
         if (c1 != c2) {
             if (c1 >= 'a' && c1 <= 'z') {
                 c1 -= ('a' - 'A');
             }
             if (c2 >= 'a' && c2 <= 'z') {
                 c2 -= ('a' - 'A');
             }
             if (c1 != c2) {
                 return c1 < c2 ? -1 : 1;
             }
         }
     } while (c1);
     return 0;        // strings are equal
 }
Referenced by CG_ServerCommand(), CL_PlayDemo_f(), Cmd_CallVote_f(), Com_AddStartupCommands(), FindMatches(), FS_CheckPak0(), FS_GetModList(), FS_IsDemoExt(), FS_ListFilteredFiles(), FS_ReferencedPakChecksums(), FS_ReferencedPakNames(), ParseDeform(), ParseShader(), PlayerModel_BuildList(), PrintCvarMatches(), PrintMatches(), Q_stricmp(), Q_stristr(), SV_Map_f(), and UI_BuildQ3Model_List().
Q_stristr()
const char* Q_stristr (const char * s, const char * find)
Definition at line 918 of file q_shared.c.
 {
     char c, sc;
     size_t len;
     if ((c = *find++) != 0) {
         if (c >= 'a' && c <= 'z') {
             c -= ('a' - 'A');
         }
         len = strlen(find);
         do {
             do {
                 if ((sc = *s++) == 0)
                     return NULL;
                 if (sc >= 'a' && sc <= 'z') {
                     sc -= ('a' - 'A');
                 }
             } while (sc != c);
         } while (Q_stricmpn(s, find, len) != 0);
         s--;
     }
     return s;
 }
Q_strlwr()
char* Q_strlwr (char * s1)
Definition at line 878 of file q_shared.c.
 {
     char* s;
     s = s1;
     while (*s) {
         *s = tolower(*s);
         s++;
     }
     return s1;
 }
Referenced by FS_LoadZipFile(), R_LoadIQM(), R_LoadMD3(), R_LoadMDR(), and RE_RegisterSkin().
Q_strncmp()
int Q_strncmp (const char * s1, const char * s2, int n)
Definition at line 852 of file q_shared.c.
 {
     int        c1, c2;
     do {
         c1 = *s1++;
         c2 = *s2++;
         if (!n--) {
             return 0;        // strings are equal until end point
         }
         if (c1 != c2) {
             return c1 < c2 ? -1 : 1;
         }
     } while (c1);
     return 0;        // strings are equal
 }
Referenced by CheckTeamVote(), CL_ConnectionlessPacket(), CL_ConsolePrint(), main(), R_LoadEntities(), R_LoadIQM(), S_FindRIFFChunk(), SpecifyLeague_Event(), and SV_ConnectionlessPacket().
Q_strncpyz()
void Q_strncpyz (char * dest, const char * src, int destsize)
Definition at line 798 of file q_shared.c.
 {
     if (!dest) {
         Com_Error(ERR_FATAL, "Q_strncpyz: NULL dest");
     }
     if (!src) {
         Com_Error(ERR_FATAL, "Q_strncpyz: NULL src");
     }
     if (destsize < 1) {
         Com_Error(ERR_FATAL, "Q_strncpyz: destsize < 1");
     }
     strncpy(dest, src, destsize - 1);
     dest[destsize - 1] = 0;
 }
Referenced by AAS_LoadFiles(), ArenaServers_Insert(), ArenaServers_LoadFavorites(), BotCreateWayPoint(), BotFindMatch(), BotGoalName(), BotLoadChatFile(), BotLoadInitialChat(), BotMatch_NewLeader(), BotNextConsoleMessage(), BotQueueConsoleMessage(), BotVoiceChatCommand(), CG_CenterPrint(), CG_ConfigStringModified(), CG_DrawInformation(), CG_LoadClientInfo(), CG_LoadingClient(), CG_LoadingString(), CG_NewClientInfo(), CG_Obituary(), CG_ParseServerinfo(), CG_RegisterGraphics(), CG_RegisterSounds(), CG_ServerCommand(), CG_StartMusic(), CG_TestModel_f(), CL_AddReliableCommand(), CL_BeginDownload(), CL_CheckForResend(), CL_CompletePlayerName(), CL_Connect_f(), CL_ConnectionlessPacket(), CL_Frame(), CL_GetClipboardData(), CL_GetPing(), CL_GetPingInfo(), CL_MapLoading(), CL_MotdPacket(), CL_NextDemo(), CL_OpenAVIForWriting(), CL_ParseBinding(), CL_ParseCommandString(), CL_ParseGamestate(), CL_ParseServerInfo(), CL_PlayDemo_f(), CL_Record_f(), CL_Sayto_f(), CL_ServerInfoPacket(), CL_ServerStatus(), CL_SetServerInfo(), ClientCleanName(), ClientNumberFromString(), ClientUserinfoChanged(), CM_LoadMap(), Cmd_ArgsBuffer(), Cmd_ArgvBuffer(), Cmd_CallTeamVote_f(), Cmd_Exec_f(), Cmd_TokenizeString2(), Com_AppendCDKey(), Com_FieldStringToPlayerName(), Com_MD5File(), Com_ReadCDKey(), COM_StripExtension(), Com_TruncateLongString(), Com_WriteCDKey(), Com_WriteConfig_f(), Con_Dump_f(), CON_HistAdd(), CON_HistNext(), CON_HistPrev(), CON_Input(), Console_Key(), CreateInternalShaders(), Cvar_InfoStringBuffer(), Cvar_Update(), Cvar_VariableStringBuffer(), FBO_Create(), Field_Complete(), Field_CompletePlayerNameFinal(), FindMatches(), FS_AddGameDirectory(), FS_CreatePath(), FS_FCreateOpenPipeFile(), FS_FilenameCompletion(), FS_FindVM(), FS_FOpenFileAppend(), FS_FOpenFileReadDir(), FS_FOpenFileWrite(), FS_GetModDescription(), FS_InitFilesystem(), FS_LoadZipFile(), FS_Restart(), FS_SV_FOpenFileRead(), FS_SV_FOpenFileWrite(), G_BotConnect(), G_InitBots(), G_ParseInfos(), G_ProcessIPBans(), G_Say(), G_SpawnBots(), GetClientState(), GetConfigString(), GLimp_InitExtraExtensions(), GLSL_InitGPUShader2(), GLSL_LoadGPUShaderText(), GLSL_PrintLog(), GraphicsOptions_ApplyChanges(), GraphicsOptions_GetAspectRatios(), InitShader(), Item_Multi_HandleKey(), Key_GetBindingBuf(), Key_KeynumToStringBuf(), LAN_AddServer(), LAN_GetServerAddressString(), LAN_GetServerInfo(), LoadItemConfig(), LoadScriptFile(), LoadScriptMemory(), LoadSourceFile(), LoadSourceMemory(), LoadWeaponConfig(), Log_Open(), MSG_WriteBigString(), MSG_WriteString(), NET_AddLocalAddress(), NET_StringToAdr(), PC_DefineFromString(), PC_Directive_include(), PC_SetIncludePath(), PlayerIcon(), PlayerIntroSound(), PlayerModel_PicEvent(), PlayerModel_SetMenuItems(), PlayerSettings_DrawName(), PlayerSettings_SetMenuItems(), Prepname(), PS_ReadPunctuation(), Q_strcat(), R_CreateVao(), R_CreateVao2(), R_GetEntityToken(), R_InitSkins(), R_LoadCubemapEntities(), R_LoadEntities(), R_LoadImage(), R_LoadIQM(), R_LoadMD3(), R_LoadMDR(), R_PrintLongString(), R_TakeScreenshot(), Rankings_DrawPassword(), RE_LoadWorldMap(), RE_RegisterFont(), RE_RegisterModel(), RE_RegisterSkin(), ReadWeightConfig(), S_Base_StartBackgroundTrack(), S_CodecGetSound(), ScanAndLoadShaderFiles(), ServerOptions_InitBotNames(), ServerOptions_LevelshotDraw(), ServerOptions_SetMenuItems(), ServerPlayerIcon(), SP_target_speaker(), SpecifyLeague_GetList(), SpecifyLeague_MenuInit(), StartServer_Cache(), StartServer_LevelshotDraw(), StartServer_Update(), SV_AddBanToList(), SV_AddServerCommand(), SV_BeginDownload_f(), SV_BotGetConsoleMessage(), SV_CompletePlayerName(), SV_ConSayto_f(), SV_DirectConnect(), SV_GameSystemCalls(), SV_GetConfigstring(), SV_GetPlayerByHandle(), SV_GetServerinfo(), SV_GetUserinfo(), SV_Map_f(), SV_MapRestart_f(), SV_Netchan_Transmit(), SV_RankUserValidate(), SV_SendConfigstring(), SV_SetUserinfo(), SV_SpawnServer(), SV_UpdateUserinfo_f(), SV_UserinfoChanged(), Svcmd_BotList_f(), Sys_Basename(), Sys_Dirname(), Sys_GetClipboardData(), Sys_SetBinaryPath(), Sys_SetDefaultInstallPath(), Sys_StripAppBundle(), Text_PaintCenter_AutoWrapped(), UI_AddBotsMenu_SetBotNames(), UI_BotSelectMenu_SelectEvent(), UI_BotSelectMenu_UpdateGrid(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_CalcPostGameStats(), UI_ConsoleCommand(), UI_DrawConnectScreen(), UI_DrawGLInfo(), UI_DrawOpponent(), UI_DrawPlayerModel(), UI_DrawProportionalString_AutoWrapped(), UI_DrawServerRefreshDate(), UI_DriverInfo_Menu(), UI_FeederSelection(), UI_GetServerStatusInfo(), UI_Load(), UI_Mods_ParseInfos(), UI_ParseInfos(), UI_RegisterClientModelname(), UI_RemoveBotsMenu_SetBotNames(), UI_ResolutionToAspect(), UI_RunMenuScript(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_SetBots(), UI_SPLevelMenu_SetMenuArena(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_TeamOrdersMenu_BuildBotList(), VM_Create(), VM_LoadSymbols(), and VM_Restart().
Q_strupr()
char* Q_strupr (char * s1)
Definition at line 890 of file q_shared.c.
 {
     char* s;
     s = s1;
     while (*s) {
         *s = toupper(*s);
         s++;
     }
     return s1;
 }
Referenced by ArenaServers_Insert(), BindingFromName(), Controls_DrawKeyBinding(), LoadConfig_MenuInit(), PlayerModel_PicEvent(), PlayerModel_SetMenuItems(), ServerOptions_SetMenuItems(), StartServer_Cache(), StartServer_LevelshotDraw(), StartServer_Update(), UI_LoadMovies(), UI_SPLevelMenu_MenuDraw(), and UI_SPLevelMenu_SetMenuArena().
Q_vsnprintf()
int Q_vsnprintf (char * str, size_t size, const char * format, va_list ap)
Definition at line 769 of file q_shared.c.
 {
     int retval;
     retval = _vsnprintf(str, size, format, ap);
     if (retval < 0 || retval == size) {
         // Microsoft doesn't adhere to the C99 standard of vsnprintf,
         // which states that the return value must be the number of
         // bytes written if the output string had sufficient length.
         //
         // Obviously we cannot determine that value from Microsoft's
         // implementation, so we have no choice but to return size.
         str[size - 1] = '\0';
         return size;
     }
     return retval;
 }
Referenced by __attribute__(), AAS_Error(), BotAI_Print(), CG_Error(), CG_Printf(), Com_DPrintf(), Com_Error(), COM_ParseError(), COM_ParseWarning(), Com_Printf(), Com_sprintf(), FS_Printf(), G_Error(), G_LogPrintf(), G_Printf(), NET_OutOfBandPrint(), ScriptError(), ScriptWarning(), SourceError(), SourceWarning(), SV_RankError(), SV_SendServerCommand(), Sys_Error(), and va().
ShortNoSwap()
short ShortNoSwap (short l)
Definition at line 210 of file q_shared.c.
 {
     return l;
 }
ShortSwap()
short ShortSwap (short l)
Definition at line 200 of file q_shared.c.
 {
     byte    b1, b2;
     b1 = l & 255;
     b2 = (l >> 8) & 255;
     return (b1 << 8) + b2;
 }
SkipBracedSection()
qboolean SkipBracedSection (char ** program, int depth)
Definition at line 582 of file q_shared.c.
 {
     char* token;
     do {
         token = COM_ParseExt(program, qtrue);
         if (token[1] == 0) {
             if (token[0] == '{') {
                 depth++;
             } else if (token[0] == '}') {
                 depth--;
             }
         }
     } while (depth && *program);
     return (depth == 0);
 }
Referenced by FindShaderInShaderText(), and ScanAndLoadShaderFiles().
SkipRestOfLine()
void SkipRestOfLine (char ** data)
Definition at line 605 of file q_shared.c.
 {
     char* p;
     int        c;
     p = *data;
     if (!*p)
         return;
     while ((c = *p++) != 0) {
         if (c == '\n') {
             com_lines++;
             break;
         }
     }
     *data = p;
 }
Referenced by ParseShader().
SkipWhitespace()
static char* SkipWhitespace (char * data, qboolean * hasNewLines) static
Definition at line 375 of file q_shared.c.
 {
     int c;
     while ((c = *data) <= ' ') {
         if (!c) {
             return NULL;
         }
         if (c == '\n') {
             com_lines++;
             *hasNewLines = qtrue;
         }
         data++;
     }
     return data;
 }
Referenced by COM_ParseExt().
va()
char* QDECL va (char * format, ...)
Definition at line 1023 of file q_shared.c.
 {
     va_list        argptr;
     static char string[2][32000]; // in case va is called by nested functions
     static int    index = 0;
     char* buf;
     buf = string[index & 1];
     index++;
     va_start(argptr, format);
     Q_vsnprintf(buf, sizeof(*string), format, argptr);
     va_end(argptr);
     return buf;
 }
Referenced by __attribute__(), _UI_Init(), ArenaServers_DoRefresh(), ArenaServers_Go(), ArenaServers_LoadFavorites(), ArenaServers_SaveChanges(), ArenaServers_StartRefresh(), AssetCache(), BotCTFSeekGoals(), BotEnterChat(), BotInterbreeding(), BotReadSessionData(), BotSetInfoConfigString(), BotSetTeamStatus(), BotVoiceChat(), BotVoiceChatOnly(), BotWriteSessionData(), BroadcastTeamChange(), CalculateRanks(), CG_BuildSpectatorString(), CG_CheckOrderPending(), CG_ClearParticles(), CG_Draw1stPlace(), CG_Draw2ndPlace(), CG_DrawActiveFrame(), CG_DrawCapFragLimit(), CG_DrawFPS(), CG_DrawInformation(), CG_DrawMedal(), CG_DrawOldScoreboard(), CG_DrawScores(), CG_DrawSnapshot(), CG_DrawTeamVote(), CG_DrawTimer(), CG_DrawTourneyScoreboard(), CG_DrawVote(), CG_DrawWarmup(), CG_EntityEvent(), CG_GetGameStatusText(), CG_GetKillerText(), CG_LoadClientInfo(), CG_LoadingClient(), CG_MapRestart(), CG_Obituary(), CG_ParseServerinfo(), CG_PlaceString(), CG_RegisterGraphics(), CG_SetSelectedPlayerName(), CG_ShowResponseHead(), CG_SizeDown_f(), CG_SizeUp_f(), CG_TargetCommand_f(), CG_UseItem(), Character_Parse(), CheckExitRules(), CheckTeamVote(), CheckTournament(), CheckVote(), CL_BeginDownload(), CL_CheckFileSize(), CL_CheckForResend(), CL_CheckUserinfo(), CL_CloseAVI(), CL_Frame(), CL_NextDownload(), CL_OpenAVIForWriting(), CL_ParseDownload(), CL_Reconnect_f(), CL_SaveConsoleHistory(), CL_Sayto_f(), CL_ServerInfoPacket(), ClientBegin(), ClientCommand(), ClientConnect(), ClientNumberFromString(), ClientUserinfoChanged(), Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_GameCommand_f(), Cmd_God_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_TeamTask_f(), Cmd_TeamVote_f(), Cmd_Vote_f(), Cmd_Vstr_f(), Cmd_Where_f(), Com_Error(), Com_Init(), Com_MD5File(), ConsoleCommand(), Cvar_Toggle_f(), DeathmatchScoreboardMessage(), Demos_MenuEvent(), DriverInfo_MenuDraw(), EA_DropInv(), EA_DropItem(), EA_Say(), EA_SayTeam(), EA_Tell(), EA_UseInv(), EA_UseItem(), Favorites_Add(), FBO_Bind(), FBO_Init(), FS_CheckPak0(), FS_ComparePaks(), FS_idPak(), FS_LoadedPakChecksums(), FS_LoadedPakPureChecksums(), FS_ReferencedPakChecksums(), FS_ReferencedPakPureChecksums(), G_AddBot(), G_AddRandomBot(), G_GetBotInfoByNumber(), G_LoadArenas(), G_LoadArenasFromFile(), G_LoadBots(), G_LoadBotsFromFile(), G_ParseInfos(), G_RankRunFrame(), G_ReadSessionData(), G_RemoveRandomBot(), G_SayTo(), G_SpawnBots(), G_TeamCommand(), G_UpdateCvars(), G_WriteClientSessionData(), G_WriteSessionData(), GetMenuBuffer(), GLSL_BindProgram(), GLSL_GetShaderHeader(), GLSL_InitGPUShaders(), Item_Multi_HandleKey(), Item_Slider_HandleKey(), Item_YesNo_HandleKey(), LAN_GetServerInfo(), LoadConfig_MenuEvent(), main(), MapList_Parse(), Menu_AddItem(), Menu_Draw(), Menu_PaintAll(), NET_GetCvars(), Netchan_Init(), PC_Script_Parse(), PlayerIntroSound(), PlayerModel_BuildList(), PlayerSettings_MenuEvent(), Preferences_Cache(), R_BindVao(), R_CreateBuiltinImages(), R_LoadImage(), R_LoadIQM(), R_LoadLightmaps(), R_LoadMD3(), R_Register(), R_RenderMissingCubemaps(), RB_StageIteratorGeneric(), RE_RegisterFont(), RoQShutdown(), Script_Exec(), Scroll_Slider_ThumbFunc(), ServerOptions_Start(), SetLeader(), SP_worldspawn(), SpecifyLeague_GetList(), SpecifyServer_Event(), SV_BoundMaxClients(), SV_Frame(), SV_Init(), SV_MapRestart_f(), SV_SpawnServer(), SVC_Info(), Svcmd_BotList_f(), Sys_ErrorDialog(), Sys_PIDFileName(), Sys_SetEnv(), Sys_SigHandler(), Team_Parse(), TeamplayInfoMessage(), UI_AddBotsMenu_FightEvent(), UI_BuildFindPlayerList(), UI_BuildPlayerList(), UI_BuildQ3Model_List(), UI_CinematicsMenu_Event(), UI_ClearScores(), UI_DisplayDownloadInfo(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawConnectScreen(), UI_DrawGLInfo(), UI_DrawMapCinematic(), UI_DrawMapTimeToBeat(), UI_DrawNetFilter(), UI_DrawNetSource(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawPreviewCinematic(), UI_DrawServerRefreshDate(), UI_DrawTeamMember(), UI_DrawTeamName(), UI_DrawTier(), UI_DrawTierMap(), UI_FeederSelection(), UI_GetArenaInfoByNumber(), UI_GetBestScore(), UI_GetBotInfoByNumber(), UI_LoadArenas(), UI_LoadArenasFromFile(), UI_LoadArenasIntoMapList(), UI_LoadBots(), UI_LoadBotsFromFile(), UI_LogAwardData(), UI_Mods_LoadMods(), UI_OwnerDrawWidth(), UI_ParseInfos(), UI_Refresh(), UI_RemoveBotsMenu_DeleteEvent(), UI_RunMenuScript(), UI_SaveConfigMenu_SaveEvent(), UI_SetBestScore(), UI_SetBestScores(), UI_SetCapFragLimits(), UI_SetLerpFrameAnimation(), UI_ShowTierVideo(), UI_SPArena_Start(), UI_SPLevelMenu_MenuDraw(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuDrawScoreLine(), UI_StartServerRefresh(), UI_StartSkirmish(), UI_TeamMember_HandleKey(), UI_TeamOrdersMenu_ListEvent(), UpdateIPBans(), and Use_Target_Print().
Variable Documentation
com_lines
int com_lines static
Definition at line 315 of file q_shared.c.
Referenced by COM_BeginParseSession(), COM_GetCurrentParseLine(), COM_ParseExt(), SkipRestOfLine(), and SkipWhitespace().
com_parsename
char com_parsename[MAX_TOKEN_CHARS] static
Definition at line 314 of file q_shared.c.
Referenced by COM_BeginParseSession(), COM_ParseError(), and COM_ParseWarning().
com_token
char com_token[MAX_TOKEN_CHARS] static
Definition at line 313 of file q_shared.c.
Referenced by COM_ParseExt(), CommaParse(), G_ParseSpawnVars(), and R_ParseSpawnVars().
com_tokenline
int com_tokenline static
Definition at line 316 of file q_shared.c.
Referenced by COM_BeginParseSession(), COM_GetCurrentParseLine(), and COM_ParseExt().