ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ai_char.h File Reference
be_ai_char.h File Reference
Functions
int BotLoadCharacter (char *charfile, float skill)
void BotFreeCharacter (int character)
float Characteristic_Float (int character, int index)
float Characteristic_BFloat (int character, int index, float min, float max)
int Characteristic_Integer (int character, int index)
int Characteristic_BInteger (int character, int index, int min, int max)
void Characteristic_String (int character, int index, char *buf, int size)
void BotShutdownCharacters (void)
Function Documentation
BotFreeCharacter()
void BotFreeCharacter (int character)
Definition at line 169 of file be_ai_char.c.
 {
     if (!LibVarGetValue("bot_reloadcharacters")) return;
     BotFreeCharacter2(handle);
 } //end of the function BotFreeCharacter
References BotFreeCharacter2(), and LibVarGetValue().
Referenced by Init_AI_Export().
BotLoadCharacter()
int BotLoadCharacter (char * charfile, float skill)
Definition at line 568 of file be_ai_char.c.
 {
     int firstskill, secondskill, handle;
     //make sure the skill is in the valid range
     if (skill < 1.0) skill = 1.0;
     else if (skill > 5.0) skill = 5.0;
     //skill 1, 4 and 5 should be available in the character files
     if (skill == 1.0 || skill == 4.0 || skill == 5.0)
     {
         return BotLoadCharacterSkill(charfile, skill);
     } //end if
     //check if there's a cached skill
     handle = BotFindCachedCharacter(charfile, skill);
     if (handle)
     {
         botimport.Print(PRT_MESSAGE, "loaded cached skill %f from %s\n", skill, charfile);
         return handle;
     } //end if
     if (skill < 4.0)
     {
         //load skill 1 and 4
         firstskill = BotLoadCharacterSkill(charfile, 1);
         if (!firstskill) return 0;
         secondskill = BotLoadCharacterSkill(charfile, 4);
         if (!secondskill) return firstskill;
     } //end if
     else
     {
         //load skill 4 and 5
         firstskill = BotLoadCharacterSkill(charfile, 4);
         if (!firstskill) return 0;
         secondskill = BotLoadCharacterSkill(charfile, 5);
         if (!secondskill) return firstskill;
     } //end else
     //interpolate between the two skills
     handle = BotInterpolateCharacters(firstskill, secondskill, skill);
     if (!handle) return 0;
     //write the character to the log file
     BotDumpCharacter(botcharacters[handle]);
     //
     return handle;
 } //end of the function BotLoadCharacter
References botcharacters, BotDumpCharacter(), BotFindCachedCharacter(), botimport, BotInterpolateCharacters(), BotLoadCharacterSkill(), and PRT_MESSAGE.
Referenced by Init_AI_Export().
BotShutdownCharacters()
void BotShutdownCharacters (void)
Definition at line 775 of file be_ai_char.c.
 {
     int handle;
     for (handle = 1; handle <= MAX_CLIENTS; handle++)
     {
         if (botcharacters[handle])
         {
             BotFreeCharacter2(handle);
         } //end if
     } //end for
 } //end of the function BotShutdownCharacters
References botcharacters, BotFreeCharacter2(), and MAX_CLIENTS.
Referenced by Export_BotLibShutdown().
Characteristic_BFloat()
float Characteristic_BFloat (int character, int index, float min, float max)
Definition at line 673 of file be_ai_char.c.
 {
     float value;
     bot_character_t *ch;
     ch = BotCharacterFromHandle(character);
     if (!ch) return 0;
     if (min > max)
     {
         botimport.Print(PRT_ERROR, "cannot bound characteristic %d between %f and %f\n", index, min, max);
         return 0;
     } //end if
     value = Characteristic_Float(character, index);
     if (value < min) return min;
     if (value > max) return max;
     return value;
 } //end of the function Characteristic_BFloat
References BotCharacterFromHandle(), botimport, Characteristic_Float(), and PRT_ERROR.
Referenced by Init_AI_Export().
Characteristic_BInteger()
int Characteristic_BInteger (int character, int index, int min, int max)
Definition at line 727 of file be_ai_char.c.
 {
     int value;
     bot_character_t *ch;
     ch = BotCharacterFromHandle(character);
     if (!ch) return 0;
     if (min > max)
     {
         botimport.Print(PRT_ERROR, "cannot bound characteristic %d between %d and %d\n", index, min, max);
         return 0;
     } //end if
     value = Characteristic_Integer(character, index);
     if (value < min) return min;
     if (value > max) return max;
     return value;
 } //end of the function Characteristic_BInteger
References BotCharacterFromHandle(), botimport, Characteristic_Integer(), and PRT_ERROR.
Referenced by Init_AI_Export().
Characteristic_Float()
float Characteristic_Float (int character, int index)
Definition at line 641 of file be_ai_char.c.
 {
     bot_character_t *ch;
     ch = BotCharacterFromHandle(character);
     if (!ch) return 0;
     //check if the index is in range
     if (!CheckCharacteristicIndex(character, index)) return 0;
     //an integer will be converted to a float
     if (ch->c[index].type == CT_INTEGER)
     {
         return (float) ch->c[index].value.integer;
     } //end if
     //floats are just returned
     else if (ch->c[index].type == CT_FLOAT)
     {
         return ch->c[index].value._float;
     } //end else if
     //cannot convert a string pointer to a float
     else
     {
         botimport.Print(PRT_ERROR, "characteristic %d is not a float\n", index);
         return 0;
     } //end else if
 //  return 0;
 } //end of the function Characteristic_Float
References cvalue::_float, BotCharacterFromHandle(), botimport, bot_character_s::c, CheckCharacteristicIndex(), CT_FLOAT, CT_INTEGER, cvalue::integer, PRT_ERROR, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by Characteristic_BFloat(), and Init_AI_Export().
Characteristic_Integer()
int Characteristic_Integer (int character, int index)
Definition at line 696 of file be_ai_char.c.
 {
     bot_character_t *ch;
     ch = BotCharacterFromHandle(character);
     if (!ch) return 0;
     //check if the index is in range
     if (!CheckCharacteristicIndex(character, index)) return 0;
     //an integer will just be returned
     if (ch->c[index].type == CT_INTEGER)
     {
         return ch->c[index].value.integer;
     } //end if
     //floats are casted to integers
     else if (ch->c[index].type == CT_FLOAT)
     {
         return (int) ch->c[index].value._float;
     } //end else if
     else
     {
         botimport.Print(PRT_ERROR, "characteristic %d is not an integer\n", index);
         return 0;
     } //end else if
 //  return 0;
 } //end of the function Characteristic_Integer
References cvalue::_float, BotCharacterFromHandle(), botimport, bot_character_s::c, CheckCharacteristicIndex(), CT_FLOAT, CT_INTEGER, cvalue::integer, PRT_ERROR, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by Characteristic_BInteger(), and Init_AI_Export().
Characteristic_String()
void Characteristic_String (int character, int index, char * buf, int size)
Definition at line 750 of file be_ai_char.c.
 {
     bot_character_t *ch;
     ch = BotCharacterFromHandle(character);
     if (!ch) return;
     //check if the index is in range
     if (!CheckCharacteristicIndex(character, index)) return;
     //an integer will be converted to a float
     if (ch->c[index].type == CT_STRING)
     {
         strncpy(buf, ch->c[index].value.string, size-1);
         buf[size-1] = '\0';
     } //end if
     else
     {
         botimport.Print(PRT_ERROR, "characteristic %d is not a string\n", index);
     } //end else if
 } //end of the function Characteristic_String
References BotCharacterFromHandle(), botimport, bot_character_s::c, CheckCharacteristicIndex(), CT_STRING, PRT_ERROR, cvalue::string, bot_characteristic_s::type, and bot_characteristic_s::value.
Referenced by Init_AI_Export().