ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_confirm.c File Reference
ui_confirm.c File Reference
#include "ui_local.h"
Classes
struct confirmMenu_t
Macros
#define ART_CONFIRM_FRAME "menu/art/cut_frame"
#define ID_CONFIRM_NO 10
#define ID_CONFIRM_YES 11
Functions
static void ConfirmMenu_Event (void *ptr, int event)
static sfxHandle_t ConfirmMenu_Key (int key)
static void MessageMenu_Draw (void)
static void ConfirmMenu_Draw (void)
void ConfirmMenu_Cache (void)
void UI_ConfirmMenu_Style (const char *question, int style, void(*draw)(void), void(*action)(qboolean result))
void UI_ConfirmMenu (const char *question, void(*draw)(void), void(*action)(qboolean result))
void UI_Message (const char **lines)
Variables
static confirmMenu_t s_confirm
Macro Definition Documentation
ART_CONFIRM_FRAME
#define ART_CONFIRM_FRAME "menu/art/cut_frame"
Definition at line 35 of file ui_confirm.c.
ID_CONFIRM_NO
#define ID_CONFIRM_NO 10
Definition at line 37 of file ui_confirm.c.
ID_CONFIRM_YES
#define ID_CONFIRM_YES 11
Definition at line 38 of file ui_confirm.c.
Function Documentation
ConfirmMenu_Cache()
void ConfirmMenu_Cache (void)
Definition at line 163 of file ui_confirm.c.
{
     trap_R_RegisterShaderNoMip( ART_CONFIRM_FRAME );
 }
References ART_CONFIRM_FRAME, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), UI_ConfirmMenu_Style(), and UI_Message().
ConfirmMenu_Draw()
static void ConfirmMenu_Draw (void) static
Definition at line 145 of file ui_confirm.c.
{
     UI_DrawNamedPic( 142, 118, 359, 256, ART_CONFIRM_FRAME );
     UI_DrawProportionalString( 320, 204, s_confirm.question, s_confirm.style, color_red );
     UI_DrawProportionalString( s_confirm.slashX, 265, "/", UI_LEFT|UI_INVERSE, color_red );
     Menu_Draw( &s_confirm.menu );
     if( s_confirm.draw ) {
         s_confirm.draw();
     }
 }
References ART_CONFIRM_FRAME, color_red, confirmMenu_t::draw, confirmMenu_t::menu, Menu_Draw(), confirmMenu_t::question, s_confirm, confirmMenu_t::slashX, confirmMenu_t::style, UI_DrawNamedPic(), UI_DrawProportionalString(), UI_INVERSE, and UI_LEFT.
Referenced by UI_ConfirmMenu_Style().
ConfirmMenu_Event()
static void ConfirmMenu_Event (void * ptr, int event) static
Definition at line 65 of file ui_confirm.c.
{
     qboolean    result;
     if( event != QM_ACTIVATED ) {
         return;
     }
     UI_PopMenu();
     if( ((menucommon_s*)ptr)->id == ID_CONFIRM_NO ) {
         result = qfalse;
     }
     else {
         result = qtrue;
     }
     if( s_confirm.action ) {
         s_confirm.action( result );
     }
 }
References confirmMenu_t::action, ID_CONFIRM_NO, qfalse, QM_ACTIVATED, qtrue, s_confirm, and UI_PopMenu().
Referenced by ConfirmMenu_Key(), UI_ConfirmMenu_Style(), and UI_Message().
ConfirmMenu_Key()
static sfxHandle_t ConfirmMenu_Key (int key) static
Definition at line 92 of file ui_confirm.c.
{
     switch ( key ) {
     case K_KP_LEFTARROW:
     case K_LEFTARROW:
     case K_KP_RIGHTARROW:
     case K_RIGHTARROW:
         key = K_TAB;
         break;
     case 'n':
     case 'N':
         ConfirmMenu_Event( &s_confirm.no, QM_ACTIVATED );
         break;
     case 'y':
     case 'Y':
         ConfirmMenu_Event( &s_confirm.yes, QM_ACTIVATED );
         break;
     }
     return Menu_DefaultKey( &s_confirm.menu, key );
 }
References ConfirmMenu_Event(), K_KP_LEFTARROW, K_KP_RIGHTARROW, K_LEFTARROW, K_RIGHTARROW, K_TAB, confirmMenu_t::menu, Menu_DefaultKey(), confirmMenu_t::no, QM_ACTIVATED, s_confirm, and confirmMenu_t::yes.
Referenced by UI_ConfirmMenu_Style(), and UI_Message().
MessageMenu_Draw()
static void MessageMenu_Draw (void) static
Definition at line 121 of file ui_confirm.c.
{
     int i,y;
     UI_DrawNamedPic( 142, 118, 359, 256, ART_CONFIRM_FRAME );
     y = 188;
     for(i=0; s_confirm.lines[i]; i++)
     {
         UI_DrawProportionalString( 320, y, s_confirm.lines[i], s_confirm.style, color_red );
         y += 18;
     }
     Menu_Draw( &s_confirm.menu );
     if( s_confirm.draw ) {
         s_confirm.draw();
     }
 }
References ART_CONFIRM_FRAME, color_red, confirmMenu_t::draw, confirmMenu_t::lines, confirmMenu_t::menu, Menu_Draw(), s_confirm, confirmMenu_t::style, UI_DrawNamedPic(), and UI_DrawProportionalString().
Referenced by UI_Message().
UI_ConfirmMenu()
void UI_ConfirmMenu (const char * question, void(*)(void) draw, void(*)(qboolean result) action)
Definition at line 241 of file ui_confirm.c.
{
     UI_ConfirmMenu_Style(question, UI_CENTER|UI_INVERSE, draw, action);
 }
References UI_CENTER, UI_ConfirmMenu_Style(), and UI_INVERSE.
Referenced by Controls_MenuEvent(), InGame_Event(), Main_MenuEvent(), UI_SetActiveMenu(), UI_SetupMenu_Event(), and UI_SPLevelMenu_ResetEvent().
UI_ConfirmMenu_Style()
void UI_ConfirmMenu_Style (const char * question, int style, void(*)(void) draw, void(*)(qboolean result) action)
Definition at line 173 of file ui_confirm.c.
{
     uiClientState_t cstate;
     int n1, n2, n3;
     int l1, l2, l3;
     // zero set all our globals
     memset( &s_confirm, 0, sizeof(s_confirm) );
     ConfirmMenu_Cache();
     n1 = UI_ProportionalStringWidth( "YES/NO" );
     n2 = UI_ProportionalStringWidth( "YES" ) + PROP_GAP_WIDTH;
     n3 = UI_ProportionalStringWidth( "/" )  + PROP_GAP_WIDTH;
     l1 = 320 - ( n1 / 2 );
     l2 = l1 + n2;
     l3 = l2 + n3;
     s_confirm.slashX = l2;
     s_confirm.question = question;
     s_confirm.draw = draw;
     s_confirm.action = action;
     s_confirm.style = style;
     s_confirm.menu.draw       = ConfirmMenu_Draw;
     s_confirm.menu.key        = ConfirmMenu_Key;
     s_confirm.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         s_confirm.menu.fullscreen = qfalse;
     }
     else {
         s_confirm.menu.fullscreen = qtrue;
     }
     s_confirm.yes.generic.type      = MTYPE_PTEXT;
     s_confirm.yes.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.yes.generic.callback  = ConfirmMenu_Event;
     s_confirm.yes.generic.id        = ID_CONFIRM_YES;
     s_confirm.yes.generic.x         = l1;
     s_confirm.yes.generic.y         = 264;
     s_confirm.yes.string            = "YES";
     s_confirm.yes.color             = color_red;
     s_confirm.yes.style             = UI_LEFT;
     s_confirm.no.generic.type       = MTYPE_PTEXT;
     s_confirm.no.generic.flags      = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.no.generic.callback   = ConfirmMenu_Event;
     s_confirm.no.generic.id         = ID_CONFIRM_NO;
     s_confirm.no.generic.x          = l3;
     s_confirm.no.generic.y          = 264;
     s_confirm.no.string             = "NO";
     s_confirm.no.color              = color_red;
     s_confirm.no.style              = UI_LEFT;
     Menu_AddItem( &s_confirm.menu,  &s_confirm.yes );
     Menu_AddItem( &s_confirm.menu,  &s_confirm.no );
     UI_PushMenu( &s_confirm.menu );
     Menu_SetCursorToItem( &s_confirm.menu, &s_confirm.no );
 }
References confirmMenu_t::action, CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_red, ConfirmMenu_Cache(), ConfirmMenu_Draw(), ConfirmMenu_Event(), ConfirmMenu_Key(), uiClientState_t::connState, confirmMenu_t::draw, _tag_menuframework::draw, menucommon_s::flags, _tag_menuframework::fullscreen, menutext_s::generic, menucommon_s::id, ID_CONFIRM_NO, ID_CONFIRM_YES, _tag_menuframework::key, confirmMenu_t::menu, Menu_AddItem(), Menu_SetCursorToItem(), MTYPE_PTEXT, confirmMenu_t::no, PROP_GAP_WIDTH, qfalse, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, confirmMenu_t::question, s_confirm, confirmMenu_t::slashX, menutext_s::string, confirmMenu_t::style, menutext_s::style, trap_GetClientState(), menucommon_s::type, UI_LEFT, UI_ProportionalStringWidth(), UI_PushMenu(), _tag_menuframework::wrapAround, menucommon_s::x, menucommon_s::y, and confirmMenu_t::yes.
Referenced by ArenaServers_Event(), and UI_ConfirmMenu().
UI_Message()
void UI_Message (const char ** lines)
Definition at line 251 of file ui_confirm.c.
{
     uiClientState_t cstate;
     int n1, l1;
     // zero set all our globals
     memset( &s_confirm, 0, sizeof(s_confirm) );
     ConfirmMenu_Cache();
     n1 = UI_ProportionalStringWidth( "OK" );
     l1 = 320 - ( n1 / 2 );
     s_confirm.lines = lines;
     s_confirm.style = UI_CENTER|UI_INVERSE|UI_SMALLFONT;
     s_confirm.menu.draw       = MessageMenu_Draw;
     s_confirm.menu.key        = ConfirmMenu_Key;
     s_confirm.menu.wrapAround = qtrue;
     trap_GetClientState( &cstate );
     if ( cstate.connState >= CA_CONNECTED ) {
         s_confirm.menu.fullscreen = qfalse;
     }
     else {
         s_confirm.menu.fullscreen = qtrue;
     }
     s_confirm.yes.generic.type      = MTYPE_PTEXT;
     s_confirm.yes.generic.flags     = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     s_confirm.yes.generic.callback  = ConfirmMenu_Event;
     s_confirm.yes.generic.id        = ID_CONFIRM_YES;
     s_confirm.yes.generic.x         = l1;
     s_confirm.yes.generic.y         = 280;
     s_confirm.yes.string            = "OK";
     s_confirm.yes.color             = color_red;
     s_confirm.yes.style             = UI_LEFT;
     Menu_AddItem( &s_confirm.menu,  &s_confirm.yes );
     UI_PushMenu( &s_confirm.menu );
     Menu_SetCursorToItem( &s_confirm.menu, &s_confirm.yes );
 }
References CA_CONNECTED, menucommon_s::callback, menutext_s::color, color_red, ConfirmMenu_Cache(), ConfirmMenu_Event(), ConfirmMenu_Key(), uiClientState_t::connState, _tag_menuframework::draw, menucommon_s::flags, _tag_menuframework::fullscreen, menutext_s::generic, menucommon_s::id, ID_CONFIRM_YES, _tag_menuframework::key, confirmMenu_t::lines, confirmMenu_t::menu, Menu_AddItem(), Menu_SetCursorToItem(), MessageMenu_Draw(), MTYPE_PTEXT, qfalse, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, s_confirm, menutext_s::string, confirmMenu_t::style, menutext_s::style, trap_GetClientState(), menucommon_s::type, UI_CENTER, UI_INVERSE, UI_LEFT, UI_ProportionalStringWidth(), UI_PushMenu(), UI_SMALLFONT, _tag_menuframework::wrapAround, menucommon_s::x, menucommon_s::y, and confirmMenu_t::yes.
Referenced by Punkbuster_ConfirmDisable().
Variable Documentation
s_confirm
confirmMenu_t s_confirm static
Definition at line 57 of file ui_confirm.c.
Referenced by ConfirmMenu_Draw(), ConfirmMenu_Event(), ConfirmMenu_Key(), MessageMenu_Draw(), UI_ConfirmMenu_Style(), and UI_Message().