ioquake3 doxygen: C:/entry/dev/ioquake3/code/botlib/be_aas_bspq3.c File Reference
be_aas_bspq3.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_aas_def.h"
Classes
struct rgb_s
struct bsp_epair_s
struct bsp_entity_s
struct bsp_s
Macros
#define ON_EPSILON 0.005
#define MAX_BSPENTITIES 2048
Typedefs
typedef struct rgb_s rgb_t
typedef struct bsp_epair_s bsp_epair_t
typedef struct bsp_entity_s bsp_entity_t
typedef struct bsp_s bsp_t
Functions
bsp_trace_t AAS_Trace (vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
int AAS_PointContents (vec3_t point)
qboolean AAS_EntityCollision (int entnum, vec3_t start, vec3_t boxmins, vec3_t boxmaxs, vec3_t end, int contentmask, bsp_trace_t *trace)
qboolean AAS_inPVS (vec3_t p1, vec3_t p2)
qboolean AAS_inPHS (vec3_t p1, vec3_t p2)
void AAS_BSPModelMinsMaxsOrigin (int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
void AAS_UnlinkFromBSPLeaves (bsp_link_t *leaves)
bsp_link_t * AAS_BSPLinkEntity (vec3_t absmins, vec3_t absmaxs, int entnum, int modelnum)
int AAS_BoxEntities (vec3_t absmins, vec3_t absmaxs, int *list, int maxcount)
int AAS_NextBSPEntity (int ent)
int AAS_BSPEntityInRange (int ent)
int AAS_ValueForBSPEpairKey (int ent, char *key, char *value, int size)
int AAS_VectorForBSPEpairKey (int ent, char *key, vec3_t v)
int AAS_FloatForBSPEpairKey (int ent, char *key, float *value)
int AAS_IntForBSPEpairKey (int ent, char *key, int *value)
void AAS_FreeBSPEntities (void)
void AAS_ParseBSPEntities (void)
int AAS_BSPTraceLight (vec3_t start, vec3_t end, vec3_t endpos, int *red, int *green, int *blue)
void AAS_DumpBSPData (void)
int AAS_LoadBSPFile (void)
Variables
botlib_import_t botimport
bsp_t bspworld
Macro Definition Documentation
MAX_BSPENTITIES
#define MAX_BSPENTITIES 2048
Definition at line 50 of file be_aas_bspq3.c.
ON_EPSILON
#define ON_EPSILON 0.005
Definition at line 47 of file be_aas_bspq3.c.
Typedef Documentation
bsp_entity_t
typedef struct bsp_entity_s bsp_entity_t
bsp_epair_t
typedef struct bsp_epair_s bsp_epair_t
bsp_t
typedef struct bsp_s bsp_t
rgb_t
typedef struct rgb_s rgb_t
Function Documentation
AAS_BoxEntities()
int AAS_BoxEntities (vec3_t absmins, vec3_t absmaxs, int * list, int maxcount)
Definition at line 242 of file be_aas_bspq3.c.
 {
     return 0;
 } //end of the function AAS_BoxEntities
AAS_BSPEntityInRange()
int AAS_BSPEntityInRange (int ent)
Definition at line 264 of file be_aas_bspq3.c.
 {
     if (ent <= 0 || ent >= bspworld.numentities)
     {
         botimport.Print(PRT_MESSAGE, "bsp entity out of range\n");
         return qfalse;
     } //end if
     return qtrue;
 } //end of the function AAS_BSPEntityInRange
Referenced by AAS_ValueForBSPEpairKey().
AAS_BSPLinkEntity()
bsp_link_t* AAS_BSPLinkEntity (vec3_t absmins, vec3_t absmaxs, int entnum, int modelnum)
Definition at line 232 of file be_aas_bspq3.c.
 {
     return NULL;
 } //end of the function AAS_BSPLinkEntity
Referenced by AAS_UpdateEntity().
AAS_BSPModelMinsMaxsOrigin()
void AAS_BSPModelMinsMaxsOrigin (int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
Definition at line 212 of file be_aas_bspq3.c.
 {
     botimport.BSPModelMinsMaxsOrigin(modelnum, angles, mins, maxs, origin);
 } //end of the function AAS_BSPModelMinsMaxs
Referenced by AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Teleport(), AAS_UpdateEntity(), BotFuncBobStartEnd(), BotOnMover(), MoverBottomCenter(), and MoverDown().
AAS_BSPTraceLight()
int AAS_BSPTraceLight (vec3_t start, vec3_t end, vec3_t endpos, int * red, int * green, int * blue)
Definition at line 450 of file be_aas_bspq3.c.
 {
     return 0;
 } //end of the function AAS_BSPTraceLight
AAS_DumpBSPData()
void AAS_DumpBSPData (void)
Definition at line 460 of file be_aas_bspq3.c.
 {
     AAS_FreeBSPEntities();
     if (bspworld.dentdata) FreeMemory(bspworld.dentdata);
     bspworld.dentdata = NULL;
     bspworld.entdatasize = 0;
     //
     bspworld.loaded = qfalse;
     Com_Memset( &bspworld, 0, sizeof(bspworld) );
 } //end of the function AAS_DumpBSPData
Referenced by AAS_LoadBSPFile(), and AAS_Shutdown().
AAS_EntityCollision()
qboolean AAS_EntityCollision (int entnum, vec3_t start, vec3_t boxmins, vec3_t boxmaxs, vec3_t end, int contentmask, bsp_trace_t * trace)
Definition at line 170 of file be_aas_bspq3.c.
 {
     bsp_trace_t enttrace;
     botimport.EntityTrace(&enttrace, start, boxmins, boxmaxs, end, entnum, contentmask);
     if (enttrace.fraction < trace->fraction)
     {
         Com_Memcpy(trace, &enttrace, sizeof(bsp_trace_t));
         return qtrue;
     } //end if
     return qfalse;
 } //end of the function AAS_EntityCollision
Referenced by AAS_AreaEntityCollision().
AAS_FloatForBSPEpairKey()
int AAS_FloatForBSPEpairKey (int ent, char * key, float * value)
Definition at line 323 of file be_aas_bspq3.c.
 {
     char buf[MAX_EPAIRKEY];
     *value = 0;
     if (!AAS_ValueForBSPEpairKey(ent, key, buf, MAX_EPAIRKEY)) return qfalse;
     *value = atof(buf);
     return qtrue;
 } //end of the function AAS_FloatForBSPEpairKey
Referenced by AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Teleport(), BotInitInfoEntities(), BotInitLevelItems(), and Init_AAS_Export().
AAS_FreeBSPEntities()
void AAS_FreeBSPEntities (void)
Definition at line 353 of file be_aas_bspq3.c.
 {
     int i;
     bsp_entity_t *ent;
     bsp_epair_t *epair, *nextepair;
     for (i = 1; i < bspworld.numentities; i++)
     {
         ent = &bspworld.entities[i];
         for (epair = ent->epairs; epair; epair = nextepair)
         {
             nextepair = epair->next;
             //
             if (epair->key) FreeMemory(epair->key);
             if (epair->value) FreeMemory(epair->value);
             FreeMemory(epair);
         } //end for
     } //end for
     bspworld.numentities = 0;
 } //end of the function AAS_FreeBSPEntities
Referenced by AAS_DumpBSPData(), and AAS_ParseBSPEntities().
AAS_inPHS()
qboolean AAS_inPHS (vec3_t p1, vec3_t p2)
Definition at line 202 of file be_aas_bspq3.c.
 {
     return qtrue;
 } //end of the function AAS_inPHS
AAS_inPVS()
qboolean AAS_inPVS (vec3_t p1, vec3_t p2)
Definition at line 191 of file be_aas_bspq3.c.
 {
     return botimport.inPVS(p1, p2);
 } //end of the function AAS_InPVS
AAS_IntForBSPEpairKey()
int AAS_IntForBSPEpairKey (int ent, char * key, int * value)
Definition at line 338 of file be_aas_bspq3.c.
 {
     char buf[MAX_EPAIRKEY];
     *value = 0;
     if (!AAS_ValueForBSPEpairKey(ent, key, buf, MAX_EPAIRKEY)) return qfalse;
     *value = atoi(buf);
     return qtrue;
 } //end of the function AAS_IntForBSPEpairKey
Referenced by AAS_Reachability_FuncBobbing(), AAS_SetWeaponJumpAreaFlags(), AAS_TravelFlagsForTeam(), BotInitLevelItems(), and Init_AAS_Export().
AAS_LoadBSPFile()
int AAS_LoadBSPFile (void)
Definition at line 478 of file be_aas_bspq3.c.
 {
     AAS_DumpBSPData();
     bspworld.entdatasize = strlen(botimport.BSPEntityData()) + 1;
     bspworld.dentdata = (char *) GetClearedHunkMemory(bspworld.entdatasize);
     Com_Memcpy(bspworld.dentdata, botimport.BSPEntityData(), bspworld.entdatasize);
     AAS_ParseBSPEntities();
     bspworld.loaded = qtrue;
     return BLERR_NOERROR;
 } //end of the function AAS_LoadBSPFile
Referenced by AAS_LoadFiles().
AAS_NextBSPEntity()
int AAS_NextBSPEntity (int ent)
Definition at line 252 of file be_aas_bspq3.c.
 {
     ent++;
     if (ent >= 1 && ent < bspworld.numentities) return ent;
     return 0;
 } //end of the function AAS_NextBSPEntity
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_JumpPad(), AAS_Reachability_Teleport(), AAS_SetWeaponJumpAreaFlags(), BotInitInfoEntities(), BotInitLevelItems(), BotSetBrushModelTypes(), and Init_AAS_Export().
AAS_ParseBSPEntities()
void AAS_ParseBSPEntities (void)
Definition at line 379 of file be_aas_bspq3.c.
 {
     script_t *script;
     token_t token;
     bsp_entity_t *ent;
     bsp_epair_t *epair;
     script = LoadScriptMemory(bspworld.dentdata, bspworld.entdatasize, "entdata");
     SetScriptFlags(script, SCFL_NOSTRINGWHITESPACES|SCFL_NOSTRINGESCAPECHARS);//SCFL_PRIMITIVE);
     bspworld.numentities = 1;
     while(PS_ReadToken(script, &token))
     {
         if (strcmp(token.string, "{"))
         {
             ScriptError(script, "invalid %s", token.string);
             AAS_FreeBSPEntities();
             FreeScript(script);
             return;
         } //end if
         if (bspworld.numentities >= MAX_BSPENTITIES)
         {
             botimport.Print(PRT_MESSAGE, "too many entities in BSP file\n");
             break;
         } //end if
         ent = &bspworld.entities[bspworld.numentities];
         bspworld.numentities++;
         ent->epairs = NULL;
         while(PS_ReadToken(script, &token))
         {
             if (!strcmp(token.string, "}")) break;
             epair = (bsp_epair_t *) GetClearedHunkMemory(sizeof(bsp_epair_t));
             epair->next = ent->epairs;
             ent->epairs = epair;
             if (token.type != TT_STRING)
             {
                 ScriptError(script, "invalid %s", token.string);
                 AAS_FreeBSPEntities();
                 FreeScript(script);
                 return;
             } //end if
             StripDoubleQuotes(token.string);
             epair->key = (char *) GetHunkMemory(strlen(token.string) + 1);
             strcpy(epair->key, token.string);
             if (!PS_ExpectTokenType(script, TT_STRING, 0, &token))
             {
                 AAS_FreeBSPEntities();
                 FreeScript(script);
                 return;
             } //end if
             StripDoubleQuotes(token.string);
             epair->value = (char *) GetHunkMemory(strlen(token.string) + 1);
             strcpy(epair->value, token.string);
         } //end while
         if (strcmp(token.string, "}"))
         {
             ScriptError(script, "missing }");
             AAS_FreeBSPEntities();
             FreeScript(script);
             return;
         } //end if
     } //end while
     FreeScript(script);
 } //end of the function AAS_ParseBSPEntities
Referenced by AAS_LoadBSPFile().
AAS_PointContents()
int AAS_PointContents (vec3_t point)
Definition at line 160 of file be_aas_bspq3.c.
 {
     return botimport.PointContents(point);
 } //end of the function AAS_PointContents
Referenced by AAS_ClientMovementPrediction(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Swim(), AAS_Swimming(), BotFinishTravel_WaterJump(), BotGapDistance(), BotInitLevelItems(), and Init_AAS_Export().
AAS_Trace()
bsp_trace_t AAS_Trace (vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
Definition at line 147 of file be_aas_bspq3.c.
 {
     bsp_trace_t bsptrace;
     botimport.Trace(&bsptrace, start, mins, maxs, end, passent, contentmask);
     return bsptrace;
 } //end of the function AAS_Trace
Referenced by AAS_DropToFloor(), AAS_Reachability_Grapple(), AAS_WeaponJumpZVelocity(), BotCheckBlocked(), BotExportTest(), BotInitLevelItems(), BotItemGoalInVisButNotVisible(), BotOnMover(), BotOnTopOfEntity(), BotReachabilityArea(), BotTravel_Grapple(), and BotVisible().
AAS_UnlinkFromBSPLeaves()
void AAS_UnlinkFromBSPLeaves (bsp_link_t * leaves)
Definition at line 223 of file be_aas_bspq3.c.
 {
 } //end of the function AAS_UnlinkFromBSPLeaves
Referenced by AAS_UnlinkInvalidEntities(), and AAS_UpdateEntity().
AAS_ValueForBSPEpairKey()
int AAS_ValueForBSPEpairKey (int ent, char * key, char * value, int size)
Definition at line 279 of file be_aas_bspq3.c.
 {
     bsp_epair_t *epair;
     value[0] = '\0';
     if (!AAS_BSPEntityInRange(ent)) return qfalse;
     for (epair = bspworld.entities[ent].epairs; epair; epair = epair->next)
     {
         if (!strcmp(epair->key, key))
         {
             strncpy(value, epair->value, size-1);
             value[size-1] = '\0';
             return qtrue;
         } //end if
     } //end for
     return qfalse;
 } //end of the function AAS_FindBSPEpair
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_FloatForBSPEpairKey(), AAS_GetJumpPadInfo(), AAS_IntForBSPEpairKey(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_JumpPad(), AAS_Reachability_Teleport(), AAS_SetWeaponJumpAreaFlags(), AAS_VectorForBSPEpairKey(), BotInitInfoEntities(), BotInitLevelItems(), BotSetBrushModelTypes(), and Init_AAS_Export().
AAS_VectorForBSPEpairKey()
int AAS_VectorForBSPEpairKey (int ent, char * key, vec3_t v)
Definition at line 302 of file be_aas_bspq3.c.
 {
     char buf[MAX_EPAIRKEY];
     double v1, v2, v3;
     VectorClear(v);
     if (!AAS_ValueForBSPEpairKey(ent, key, buf, MAX_EPAIRKEY)) return qfalse;
     //scanf into doubles, then assign, so it is vec_t size independent
     v1 = v2 = v3 = 0;
     sscanf(buf, "%lf %lf %lf", &v1, &v2, &v3);
     v[0] = v1;
     v[1] = v2;
     v[2] = v3;
     return qtrue;
 } //end of the function AAS_VectorForBSPEpairKey
Referenced by AAS_GetJumpPadInfo(), AAS_Reachability_Elevator(), AAS_Reachability_FuncBobbing(), AAS_Reachability_Teleport(), AAS_SetWeaponJumpAreaFlags(), BotInitInfoEntities(), BotInitLevelItems(), and Init_AAS_Export().
Variable Documentation
botimport
botlib_import_t botimport
Definition at line 59 of file be_interface.c.
Referenced by AAS_AASLinkEntity(), AAS_AllocAASLink(), AAS_AlternativeRouteGoals(), AAS_AreaCluster(), AAS_AreaInfo(), AAS_AreaPresenceType(), AAS_AreaRouteToGoalArea(), AAS_BSPEntityInRange(), AAS_BSPModelMinsMaxsOrigin(), AAS_CalculateAreaTravelTimes(), AAS_ClearShownDebugLines(), AAS_ClearShownPolygons(), AAS_ContinueInit(), AAS_CreateAllRoutingCache(), AAS_CreateReversedReachability(), AAS_DebugLine(), AAS_DrawPermanentCross(), AAS_DrawPlaneCross(), AAS_EnableRoutingArea(), AAS_EntityCollision(), AAS_EntityInfo(), AAS_EntityModelindex(), AAS_EntityModelNum(), AAS_EntityOrigin(), AAS_EntitySize(), AAS_EntityType(), AAS_Error(), AAS_inPVS(), AAS_InsideFace(), AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_LoadBSPFile(), AAS_LoadFiles(), AAS_NextAreaReachability(), AAS_Optimize(), AAS_ParseBSPEntities(), AAS_PermanentLine(), AAS_PointAreaNum(), AAS_PointContents(), AAS_PresenceTypeBoundingBox(), AAS_PrintTravelType(), AAS_ReadCache(), AAS_ReadRouteCache(), AAS_RoutingInfo(), AAS_SetInitialized(), AAS_ShowArea(), AAS_ShowAreaPolygons(), AAS_ShowBoundingBox(), AAS_ShowFace(), AAS_ShowFacePolygon(), AAS_ShowPolygon(), AAS_ShowReachableAreas(), AAS_Shutdown(), AAS_Trace(), AAS_TraceAreas(), AAS_TraceClientBBox(), AAS_UpdateEntity(), AAS_WriteAASFile(), AAS_WriteAASLump(), AAS_WriteRouteCache(), AllocLevelItem(), AvailableMemory(), BotCharacterFromHandle(), BotChatStateFromHandle(), BotCheckChatMessageIntegrety(), BotConstructChatMessage(), BotEnterChat(), BotExpandChatMessage(), BotFreeCharacter2(), BotFreeChatState(), BotFreeGoalState(), BotFreeMoveState(), BotFreeWeaponState(), BotFuncBobStartEnd(), BotGetReachabilityToGoal(), BotGoalStateFromHandle(), BotInitialChat(), BotInitInfoEntities(), BotInitLevelItems(), BotLoadCachedCharacter(), BotLoadCharacter(), BotLoadCharacterFromFile(), BotLoadChatFile(), BotLoadInitialChat(), BotLoadItemWeights(), BotLoadMatchTemplates(), BotLoadRandomStrings(), BotLoadReplyChat(), BotLoadSynonyms(), BotLoadWeaponWeights(), BotMatchVariable(), BotMoveStateFromHandle(), BotMoveToGoal(), BotNumInitialChats(), BotOnMover(), BotPrintReplyChatKeys(), BotPushGoal(), BotQueueConsoleMessage(), BotReachabilityTime(), BotReplyChat(), BotResetGrapple(), BotSetBrushModelTypes(), BotSetupChatAI(), BotSetupGoalAI(), BotSetupWeaponAI(), BotTravel_Elevator(), BotTravel_FuncBobbing(), BotTravel_Grapple(), BotValidWeaponNumber(), BotWeaponStateFromHandle(), Characteristic_BFloat(), Characteristic_BInteger(), Characteristic_Float(), Characteristic_Integer(), Characteristic_String(), CheckCharacteristicIndex(), EA_Command(), EA_DropInv(), EA_DropItem(), EA_Say(), EA_SayTeam(), EA_Tell(), EA_UseInv(), EA_UseItem(), FreeMemory(), GeneticParentsAndChildSelection(), GetHunkMemory(), GetMemory(), InterbreedFuzzySeperator_r(), InterbreedWeightConfigs(), LoadItemConfig(), LoadScriptFile(), LoadWeaponConfig(), Log_Close(), Log_Open(), MoverBottomCenter(), MoverDown(), PC_CheckOpenSourceHandles(), ReadWeightConfig(), ScriptError(), ScriptWarning(), SourceError(), and SourceWarning().
bspworld
bsp_t bspworld
Definition at line 87 of file be_aas_bspq3.c.
Referenced by AAS_BSPEntityInRange(), AAS_DumpBSPData(), AAS_FreeBSPEntities(), AAS_LoadBSPFile(), AAS_NextBSPEntity(), AAS_ParseBSPEntities(), and AAS_ValueForBSPEpairKey().