ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/l_struct.h File Reference
l_struct.h File Reference
Classes
struct fielddef_s
struct structdef_s
Macros
#define MAX_STRINGFIELD 80
#define FT_CHAR 1
#define FT_INT 2
#define FT_FLOAT 3
#define FT_STRING 4
#define FT_STRUCT 6
#define FT_TYPE 0x00FF
#define FT_ARRAY 0x0100
#define FT_BOUNDED 0x0200
#define FT_UNSIGNED 0x0400
Typedefs
typedef struct fielddef_s fielddef_t
typedef struct structdef_s structdef_t
Functions
int ReadStructure (source_t *source, structdef_t *def, char *structure)
int WriteStructure (FILE *fp, structdef_t *def, char *structure)
int WriteIndent (FILE *fp, int indent)
int WriteFloat (FILE *fp, float value)
Macro Definition Documentation
FT_ARRAY
#define FT_ARRAY 0x0100
Definition at line 43 of file l_struct.h.
FT_BOUNDED
#define FT_BOUNDED 0x0200
Definition at line 44 of file l_struct.h.
FT_CHAR
#define FT_CHAR 1
Definition at line 35 of file l_struct.h.
FT_FLOAT
#define FT_FLOAT 3
Definition at line 37 of file l_struct.h.
FT_INT
#define FT_INT 2
Definition at line 36 of file l_struct.h.
FT_STRING
#define FT_STRING 4
Definition at line 38 of file l_struct.h.
FT_STRUCT
#define FT_STRUCT 6
Definition at line 39 of file l_struct.h.
FT_TYPE
#define FT_TYPE 0x00FF
Definition at line 41 of file l_struct.h.
FT_UNSIGNED
#define FT_UNSIGNED 0x0400
Definition at line 45 of file l_struct.h.
MAX_STRINGFIELD
#define MAX_STRINGFIELD 80
Definition at line 33 of file l_struct.h.
Typedef Documentation
fielddef_t
typedef struct fielddef_s fielddef_t
structdef_t
typedef struct structdef_s structdef_t
Function Documentation
ReadStructure()
int ReadStructure (source_t * source, structdef_t * def, char * structure)
Definition at line 236 of file l_struct.c.
 {
     token_t token;
     fielddef_t *fd;
     void *p;
     int num;
     if (!PC_ExpectTokenString(source, "{")) return 0;
     while(1)
     {
         if (!PC_ExpectAnyToken(source, &token)) return qfalse;
         //if end of structure
         if (!strcmp(token.string, "}")) break;
         //find the field with the name
         fd = FindField(def->fields, token.string);
         if (!fd)
         {
             SourceError(source, "unknown structure field %s", token.string);
             return qfalse;
         } //end if
         if (fd->type & FT_ARRAY)
         {
             num = fd->maxarray;
             if (!PC_ExpectTokenString(source, "{")) return qfalse;
         } //end if
         else
         {
             num = 1;
         } //end else
         p = (void *)(structure + fd->offset);
         while (num-- > 0)
         {
             if (fd->type & FT_ARRAY)
             {
                 if (PC_CheckTokenString(source, "}")) break;
             } //end if
             switch(fd->type & FT_TYPE)
             {
                 case FT_CHAR:
                 {
                     if (!ReadChar(source, fd, p)) return qfalse;
                     p = (char *) p + sizeof(char);
                     break;
                 } //end case
                 case FT_INT:
                 {
                     if (!ReadNumber(source, fd, p)) return qfalse;
                     p = (char *) p + sizeof(int);
                     break;
                 } //end case
                 case FT_FLOAT:
                 {
                     if (!ReadNumber(source, fd, p)) return qfalse;
                     p = (char *) p + sizeof(float);
                     break;
                 } //end case
                 case FT_STRING:
                 {
                     if (!ReadString(source, fd, p)) return qfalse;
                     p = (char *) p + MAX_STRINGFIELD;
                     break;
                 } //end case
                 case FT_STRUCT:
                 {
                     if (!fd->substruct)
                     {
                         SourceError(source, "BUG: no sub structure defined");
                         return qfalse;
                     } //end if
                     ReadStructure(source, fd->substruct, (char *) p);
                     p = (char *) p + fd->substruct->size;
                     break;
                 } //end case
             } //end switch
             if (fd->type & FT_ARRAY)
             {
                 if (!PC_ExpectAnyToken(source, &token)) return qfalse;
                 if (!strcmp(token.string, "}")) break;
                 if (strcmp(token.string, ","))
                 {
                     SourceError(source, "expected a comma, found %s", token.string);
                     return qfalse;
                 } //end if
             } //end if
         } //end while
     } //end while
     return qtrue;
 } //end of the function ReadStructure
Referenced by LoadItemConfig(), LoadWeaponConfig(), and ReadStructure().
WriteFloat()
int WriteFloat (FILE * fp, float value)
Definition at line 344 of file l_struct.c.
 {
     char buf[128];
     int l;
     Com_sprintf(buf, sizeof(buf), "%f", value);
     l = strlen(buf);
     //strip any trailing zeros
     while(l-- > 1)
     {
         if (buf[l] != '0' && buf[l] != '.') break;
         if (buf[l] == '.')
         {
             buf[l] = 0;
             break;
         } //end if
         buf[l] = 0;
     } //end while
     //write the float to file
     if (fprintf(fp, "%s", buf) < 0) return 0;
     return 1;
 } //end of the function WriteFloat
Referenced by WriteStructWithIndent().
WriteIndent()
int WriteIndent (FILE * fp, int indent)
Definition at line 330 of file l_struct.c.
 {
     while(indent-- > 0)
     {
         if (fprintf(fp, "\t") < 0) return qfalse;
     } //end while
     return qtrue;
 } //end of the function WriteIndent
Referenced by WriteStructWithIndent().
WriteStructure()
int WriteStructure (FILE * fp, structdef_t * def, char * structure)
Definition at line 458 of file l_struct.c.
 {
     return WriteStructWithIndent(fp, def, structure, 0);
 } //end of the function WriteStructure