ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_entity.c File Reference
be_aas_entity.c File Reference
#include "../qcommon/q_shared.h"
#include "l_memory.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "l_utils.h"
#include "l_log.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_aas_def.h"
Macros
#define MASK_SOLID CONTENTS_PLAYERCLIP
Enumerations
enum {
ET_GENERAL, ET_PLAYER, ET_ITEM, ET_MISSILE,
ET_MOVER
}
Functions
int AAS_UpdateEntity (int entnum, bot_entitystate_t *state)
void AAS_EntityInfo (int entnum, aas_entityinfo_t *info)
void AAS_EntityOrigin (int entnum, vec3_t origin)
int AAS_EntityModelindex (int entnum)
int AAS_EntityType (int entnum)
int AAS_EntityModelNum (int entnum)
int AAS_OriginOfMoverWithModelNum (int modelnum, vec3_t origin)
void AAS_EntitySize (int entnum, vec3_t mins, vec3_t maxs)
void AAS_EntityBSPData (int entnum, bsp_entdata_t *entdata)
void AAS_ResetEntityLinks (void)
void AAS_InvalidateEntities (void)
void AAS_UnlinkInvalidEntities (void)
int AAS_NearestEntity (vec3_t origin, int modelindex)
int AAS_BestReachableEntityArea (int entnum)
int AAS_NextEntity (int entnum)
Macro Definition Documentation
MASK_SOLID
#define MASK_SOLID CONTENTS_PLAYERCLIP
Definition at line 46 of file be_aas_entity.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
ET_GENERAL
ET_PLAYER
ET_ITEM
ET_MISSILE
ET_MOVER
Definition at line 49 of file be_aas_entity.c.
      {
     ET_GENERAL,
     ET_PLAYER,
     ET_ITEM,
     ET_MISSILE,
     ET_MOVER
 };
Function Documentation
AAS_BestReachableEntityArea()
int AAS_BestReachableEntityArea (int entnum)
Definition at line 414 of file be_aas_entity.c.
 {
     aas_entity_t *ent;
     ent = &aasworld.entities[entnum];
     return AAS_BestReachableLinkArea(ent->areas);
 } //end of the function AAS_BestReachableEntityArea
References AAS_BestReachableLinkArea(), aasworld, aas_entity_s::areas, and aas_s::entities.
AAS_EntityBSPData()
void AAS_EntityBSPData (int entnum, bsp_entdata_t * entdata)
Definition at line 308 of file be_aas_entity.c.
 {
     aas_entity_t *ent;
     ent = &aasworld.entities[entnum];
     VectorCopy(ent->i.origin, entdata->origin);
     VectorCopy(ent->i.angles, entdata->angles);
     VectorAdd(ent->i.origin, ent->i.mins, entdata->absmins);
     VectorAdd(ent->i.origin, ent->i.maxs, entdata->absmaxs);
     entdata->solid = ent->i.solid;
     entdata->modelnum = ent->i.modelindex - 1;
 } //end of the function AAS_EntityBSPData
References aasworld, bsp_entdata_s::absmaxs, bsp_entdata_s::absmins, bsp_entdata_s::angles, aas_entityinfo_s::angles, aas_s::entities, aas_entity_s::i, aas_entityinfo_s::maxs, aas_entityinfo_s::mins, aas_entityinfo_s::modelindex, bsp_entdata_s::modelnum, bsp_entdata_s::origin, aas_entityinfo_s::origin, bsp_entdata_s::solid, aas_entityinfo_s::solid, VectorAdd, and VectorCopy.
AAS_EntityInfo()
void AAS_EntityInfo (int entnum, aas_entityinfo_t * info)
Definition at line 171 of file be_aas_entity.c.
 {
     if (!aasworld.initialized)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityInfo: aasworld not initialized\n");
         Com_Memset(info, 0, sizeof(aas_entityinfo_t));
         return;
     } //end if
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityInfo: entnum %d out of range\n", entnum);
         Com_Memset(info, 0, sizeof(aas_entityinfo_t));
         return;
     } //end if
     Com_Memcpy(info, &aasworld.entities[entnum].i, sizeof(aas_entityinfo_t));
 } //end of the function AAS_EntityInfo
References aasworld, botimport, Com_Memcpy, Com_Memset, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, and PRT_FATAL.
Referenced by BotFindEntityForLevelItem(), BotItemGoalInVisButNotVisible(), BotUpdateEntityItems(), GrappleState(), and Init_AAS_Export().
AAS_EntityModelindex()
int AAS_EntityModelindex (int entnum)
Definition at line 212 of file be_aas_entity.c.
 {
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityModelindex: entnum %d out of range\n", entnum);
         return 0;
     } //end if
     return aasworld.entities[entnum].i.modelindex;
 } //end of the function AAS_EntityModelindex
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::modelindex, and PRT_FATAL.
Referenced by BotFindEntityForLevelItem(), BotMoveToGoal(), BotReachabilityArea(), and BotUpdateEntityItems().
AAS_EntityModelNum()
int AAS_EntityModelNum (int entnum)
Definition at line 244 of file be_aas_entity.c.
 {
     if (!aasworld.initialized) return 0;
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityModelNum: entnum %d out of range\n", entnum);
         return 0;
     } //end if
     return aasworld.entities[entnum].i.modelindex;
 } //end of the function AAS_EntityModelNum
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, aas_entityinfo_s::modelindex, and PRT_FATAL.
Referenced by BotOnMover().
AAS_EntityOrigin()
void AAS_EntityOrigin (int entnum, vec3_t origin)
Definition at line 195 of file be_aas_entity.c.
 {
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityOrigin: entnum %d out of range\n", entnum);
         VectorClear(origin);
         return;
     } //end if
     VectorCopy(aasworld.entities[entnum].i.origin, origin);
 } //end of the function AAS_EntityOrigin
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::origin, PRT_FATAL, VectorClear, and VectorCopy.
AAS_EntitySize()
void AAS_EntitySize (int entnum, vec3_t mins, vec3_t maxs)
Definition at line 286 of file be_aas_entity.c.
 {
     aas_entity_t *ent;
     if (!aasworld.initialized) return;
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntitySize: entnum %d out of range\n", entnum);
         return;
     } //end if
     ent = &aasworld.entities[entnum];
     VectorCopy(ent->i.mins, mins);
     VectorCopy(ent->i.maxs, maxs);
 } //end of the function AAS_EntitySize
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, aas_entityinfo_s::maxs, aas_entityinfo_s::mins, PRT_FATAL, and VectorCopy.
AAS_EntityType()
int AAS_EntityType (int entnum)
Definition at line 227 of file be_aas_entity.c.
 {
     if (!aasworld.initialized) return 0;
     if (entnum < 0 || entnum >= aasworld.maxentities)
     {
         botimport.Print(PRT_FATAL, "AAS_EntityType: entnum %d out of range\n", entnum);
         return 0;
     } //end if
     return aasworld.entities[entnum].i.type;
 } //end of the AAS_EntityType
References aasworld, botimport, aas_s::entities, aas_entity_s::i, aas_s::initialized, aas_s::maxentities, PRT_FATAL, and aas_entityinfo_s::type.
Referenced by BotUpdateEntityItems(), and GrappleState().
AAS_InvalidateEntities()
void AAS_InvalidateEntities (void)
Definition at line 341 of file be_aas_entity.c.
 {
     int i;
     for (i = 0; i < aasworld.maxentities; i++)
     {
         aasworld.entities[i].i.valid = qfalse;
         aasworld.entities[i].i.number = i;
     } //end for
 } //end of the function AAS_InvalidateEntities
References aasworld, aas_s::entities, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::number, qfalse, and aas_entityinfo_s::valid.
Referenced by AAS_Setup(), and AAS_StartFrame().
AAS_NearestEntity()
int AAS_NearestEntity (vec3_t origin, int modelindex)
Definition at line 379 of file be_aas_entity.c.
 {
     int i, bestentnum;
     float dist, bestdist;
     aas_entity_t *ent;
     vec3_t dir;
     bestentnum = 0;
     bestdist = 99999;
     for (i = 0; i < aasworld.maxentities; i++)
     {
         ent = &aasworld.entities[i];
         if (ent->i.modelindex != modelindex) continue;
         VectorSubtract(ent->i.origin, origin, dir);
         if (fabsf(dir[0]) < 40)
         {
             if (fabsf(dir[1]) < 40)
             {
                 dist = VectorLength(dir);
                 if (dist < bestdist)
                 {
                     bestdist = dist;
                     bestentnum = i;
                 } //end if
             } //end if
         } //end if
     } //end for
     return bestentnum;
 } //end of the function AAS_NearestEntity
References aasworld, aas_s::entities, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::modelindex, aas_entityinfo_s::origin, VectorLength(), and VectorSubtract.
AAS_NextEntity()
int AAS_NextEntity (int entnum)
Definition at line 427 of file be_aas_entity.c.
 {
     if (!aasworld.loaded) return 0;
     if (entnum < 0) entnum = -1;
     while(++entnum < aasworld.maxentities)
     {
         if (aasworld.entities[entnum].i.valid) return entnum;
     } //end while
     return 0;
 } //end of the function AAS_NextEntity
References aasworld, aas_s::entities, aas_entity_s::i, aas_s::loaded, aas_s::maxentities, and aas_entityinfo_s::valid.
Referenced by BotFindEntityForLevelItem(), BotUpdateEntityItems(), and GrappleState().
AAS_OriginOfMoverWithModelNum()
int AAS_OriginOfMoverWithModelNum (int modelnum, vec3_t origin)
Definition at line 261 of file be_aas_entity.c.
 {
     int i;
     aas_entity_t *ent;
     for (i = 0; i < aasworld.maxentities; i++)
     {
         ent = &aasworld.entities[i];
         if (ent->i.type == ET_MOVER)
         {
             if (ent->i.modelindex == modelnum)
             {
                 VectorCopy(ent->i.origin, origin);
                 return qtrue;
             } //end if
         } //end if
     } //end for
     return qfalse;
 } //end of the function AAS_OriginOfMoverWithModelNum
References aasworld, aas_s::entities, ET_MOVER, aas_entity_s::i, aas_s::maxentities, aas_entityinfo_s::modelindex, aas_entityinfo_s::origin, qfalse, qtrue, aas_entityinfo_s::type, and VectorCopy.
Referenced by BotFuncBobStartEnd(), BotOnMover(), MoverBottomCenter(), and MoverDown().
AAS_ResetEntityLinks()
void AAS_ResetEntityLinks (void)
Definition at line 326 of file be_aas_entity.c.
 {
     int i;
     for (i = 0; i < aasworld.maxentities; i++)
     {
         aasworld.entities[i].areas = NULL;
         aasworld.entities[i].leaves = NULL;
     } //end for
 } //end of the function AAS_ResetEntityLinks
References aasworld, aas_entity_s::areas, aas_s::entities, aas_entity_s::leaves, aas_s::maxentities, and NULL.
Referenced by AAS_LoadFiles().
AAS_UnlinkInvalidEntities()
void AAS_UnlinkInvalidEntities (void)
Definition at line 356 of file be_aas_entity.c.
 {
     int i;
     aas_entity_t *ent;
     for (i = 0; i < aasworld.maxentities; i++)
     {
         ent = &aasworld.entities[i];
         if (!ent->i.valid)
         {
             AAS_UnlinkFromAreas( ent->areas );
             ent->areas = NULL;
             AAS_UnlinkFromBSPLeaves( ent->leaves );
             ent->leaves = NULL;
         } //end for
     } //end for
 } //end of the function AAS_UnlinkInvalidEntities
References AAS_UnlinkFromAreas(), AAS_UnlinkFromBSPLeaves(), aasworld, aas_entity_s::areas, aas_s::entities, aas_entity_s::i, aas_entity_s::leaves, aas_s::maxentities, NULL, and aas_entityinfo_s::valid.
Referenced by AAS_StartFrame().
AAS_UpdateEntity()
int AAS_UpdateEntity (int entnum, bot_entitystate_t * state)
Definition at line 63 of file be_aas_entity.c.
 {
     int relink;
     aas_entity_t *ent;
     vec3_t absmins, absmaxs;
     if (!aasworld.loaded)
     {
         botimport.Print(PRT_MESSAGE, "AAS_UpdateEntity: not loaded\n");
         return BLERR_NOAASFILE;
     } //end if
     ent = &aasworld.entities[entnum];
     if (!state) {
         //unlink the entity
         AAS_UnlinkFromAreas(ent->areas);
         //unlink the entity from the BSP leaves
         AAS_UnlinkFromBSPLeaves(ent->leaves);
         //
         ent->areas = NULL;
         //
         ent->leaves = NULL;
         return BLERR_NOERROR;
     }
     ent->i.update_time = AAS_Time() - ent->i.ltime;
     ent->i.type = state->type;
     ent->i.flags = state->flags;
     ent->i.ltime = AAS_Time();
     VectorCopy(ent->i.origin, ent->i.lastvisorigin);
     VectorCopy(state->old_origin, ent->i.old_origin);
     ent->i.solid = state->solid;
     ent->i.groundent = state->groundent;
     ent->i.modelindex = state->modelindex;
     ent->i.modelindex2 = state->modelindex2;
     ent->i.frame = state->frame;
     ent->i.event = state->event;
     ent->i.eventParm = state->eventParm;
     ent->i.powerups = state->powerups;
     ent->i.weapon = state->weapon;
     ent->i.legsAnim = state->legsAnim;
     ent->i.torsoAnim = state->torsoAnim;
     //number of the entity
     ent->i.number = entnum;
     //updated so set valid flag
     ent->i.valid = qtrue;
     //link everything the first frame
     if (aasworld.numframes == 1) relink = qtrue;
     else relink = qfalse;
     //
     if (ent->i.solid == SOLID_BSP)
     {
         //if the angles of the model changed
         if (!VectorCompare(state->angles, ent->i.angles))
         {
             VectorCopy(state->angles, ent->i.angles);
             relink = qtrue;
         } //end if
         //get the mins and maxs of the model
         //FIXME: rotate mins and maxs
         AAS_BSPModelMinsMaxsOrigin(ent->i.modelindex, ent->i.angles, ent->i.mins, ent->i.maxs, NULL);
     } //end if
     else if (ent->i.solid == SOLID_BBOX)
     {
         //if the bounding box size changed
         if (!VectorCompare(state->mins, ent->i.mins) ||
                 !VectorCompare(state->maxs, ent->i.maxs))
         {
             VectorCopy(state->mins, ent->i.mins);
             VectorCopy(state->maxs, ent->i.maxs);
             relink = qtrue;
         } //end if
         VectorCopy(state->angles, ent->i.angles);
     } //end if
     //if the origin changed
     if (!VectorCompare(state->origin, ent->i.origin))
     {
         VectorCopy(state->origin, ent->i.origin);
         relink = qtrue;
     } //end if
     //if the entity should be relinked
     if (relink)
     {
         //don't link the world model
         if (entnum != ENTITYNUM_WORLD)
         {
             //absolute mins and maxs
             VectorAdd(ent->i.mins, ent->i.origin, absmins);
             VectorAdd(ent->i.maxs, ent->i.origin, absmaxs);
             //unlink the entity
             AAS_UnlinkFromAreas(ent->areas);
             //relink the entity to the AAS areas (use the larges bbox)
             ent->areas = AAS_LinkEntityClientBBox(absmins, absmaxs, entnum, PRESENCE_NORMAL);
             //unlink the entity from the BSP leaves
             AAS_UnlinkFromBSPLeaves(ent->leaves);
             //link the entity to the world BSP tree
             ent->leaves = AAS_BSPLinkEntity(absmins, absmaxs, entnum, 0);
         } //end if
     } //end if
     return BLERR_NOERROR;
 } //end of the function AAS_UpdateEntity
References AAS_BSPLinkEntity(), AAS_BSPModelMinsMaxsOrigin(), AAS_LinkEntityClientBBox(), AAS_Time(), AAS_UnlinkFromAreas(), AAS_UnlinkFromBSPLeaves(), aasworld, aas_entityinfo_s::angles, aas_entity_s::areas, BLERR_NOAASFILE, BLERR_NOERROR, botimport, aas_s::entities, ENTITYNUM_WORLD, aas_entityinfo_s::event, aas_entityinfo_s::eventParm, aas_entityinfo_s::flags, aas_entityinfo_s::frame, aas_entityinfo_s::groundent, aas_entity_s::i, aas_entityinfo_s::lastvisorigin, aas_entity_s::leaves, aas_entityinfo_s::legsAnim, aas_s::loaded, aas_entityinfo_s::ltime, aas_entityinfo_s::maxs, aas_entityinfo_s::mins, aas_entityinfo_s::modelindex, aas_entityinfo_s::modelindex2, NULL, aas_entityinfo_s::number, aas_s::numframes, aas_entityinfo_s::old_origin, aas_entityinfo_s::origin, aas_entityinfo_s::powerups, PRESENCE_NORMAL, PRT_MESSAGE, qfalse, qtrue, aas_entityinfo_s::solid, SOLID_BBOX, SOLID_BSP, aas_entityinfo_s::torsoAnim, aas_entityinfo_s::type, aas_entityinfo_s::update_time, aas_entityinfo_s::valid, VectorAdd, VectorCompare(), VectorCopy, and aas_entityinfo_s::weapon.
Referenced by Export_BotLibUpdateEntity().