ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_cinematics.c File Reference
ui_cinematics.c File Reference
#include "ui_local.h"
Classes
struct cinematicsMenuInfo_t
Macros
#define ART_BACK0 "menu/art/back_0"
#define ART_BACK1 "menu/art/back_1"
#define ART_FRAMEL "menu/art/frame2_l"
#define ART_FRAMER "menu/art/frame1_r"
#define VERTICAL_SPACING 30
#define ID_BACK 10
#define ID_CIN_IDLOGO 11
#define ID_CIN_INTRO 12
#define ID_CIN_TIER1 13
#define ID_CIN_TIER2 14
#define ID_CIN_TIER3 15
#define ID_CIN_TIER4 16
#define ID_CIN_TIER5 17
#define ID_CIN_TIER6 18
#define ID_CIN_TIER7 19
#define ID_CIN_END 20
Functions
static void UI_CinematicsMenu_BackEvent (void *ptr, int event)
static void UI_CinematicsMenu_Event (void *ptr, int event)
static void UI_CinematicsMenu_Init (void)
void UI_CinematicsMenu_Cache (void)
void UI_CinematicsMenu (void)
void UI_CinematicsMenu_f (void)
Variables
static cinematicsMenuInfo_t cinematicsMenuInfo
static char * cinematics []
Macro Definition Documentation
ART_BACK0
#define ART_BACK0 "menu/art/back_0"
Definition at line 26 of file ui_cinematics.c.
ART_BACK1
#define ART_BACK1 "menu/art/back_1"
Definition at line 27 of file ui_cinematics.c.
ART_FRAMEL
#define ART_FRAMEL "menu/art/frame2_l"
Definition at line 28 of file ui_cinematics.c.
ART_FRAMER
#define ART_FRAMER "menu/art/frame1_r"
Definition at line 29 of file ui_cinematics.c.
ID_BACK
#define ID_BACK 10
Definition at line 33 of file ui_cinematics.c.
ID_CIN_END
#define ID_CIN_END 20
Definition at line 43 of file ui_cinematics.c.
ID_CIN_IDLOGO
#define ID_CIN_IDLOGO 11
Definition at line 34 of file ui_cinematics.c.
ID_CIN_INTRO
#define ID_CIN_INTRO 12
Definition at line 35 of file ui_cinematics.c.
ID_CIN_TIER1
#define ID_CIN_TIER1 13
Definition at line 36 of file ui_cinematics.c.
ID_CIN_TIER2
#define ID_CIN_TIER2 14
Definition at line 37 of file ui_cinematics.c.
ID_CIN_TIER3
#define ID_CIN_TIER3 15
Definition at line 38 of file ui_cinematics.c.
ID_CIN_TIER4
#define ID_CIN_TIER4 16
Definition at line 39 of file ui_cinematics.c.
ID_CIN_TIER5
#define ID_CIN_TIER5 17
Definition at line 40 of file ui_cinematics.c.
ID_CIN_TIER6
#define ID_CIN_TIER6 18
Definition at line 41 of file ui_cinematics.c.
ID_CIN_TIER7
#define ID_CIN_TIER7 19
Definition at line 42 of file ui_cinematics.c.
VERTICAL_SPACING
#define VERTICAL_SPACING 30
Definition at line 31 of file ui_cinematics.c.
Function Documentation
UI_CinematicsMenu()
void UI_CinematicsMenu (void)
Definition at line 333 of file ui_cinematics.c.
{
     UI_CinematicsMenu_Init();
     UI_PushMenu( &cinematicsMenuInfo.menu );
 }
References cinematicsMenuInfo, cinematicsMenuInfo_t::menu, UI_CinematicsMenu_Init(), and UI_PushMenu().
Referenced by Main_MenuEvent(), and UI_CinematicsMenu_f().
UI_CinematicsMenu_BackEvent()
static void UI_CinematicsMenu_BackEvent (void * ptr, int event) static
Definition at line 84 of file ui_cinematics.c.
{
     if( event != QM_ACTIVATED ) {
         return;
     }
     UI_PopMenu();
 }
References QM_ACTIVATED, and UI_PopMenu().
Referenced by UI_CinematicsMenu_Init().
UI_CinematicsMenu_Cache()
void UI_CinematicsMenu_Cache (void)
Definition at line 320 of file ui_cinematics.c.
{
     trap_R_RegisterShaderNoMip( ART_BACK0 );
     trap_R_RegisterShaderNoMip( ART_BACK1 );
     trap_R_RegisterShaderNoMip( ART_FRAMEL );
     trap_R_RegisterShaderNoMip( ART_FRAMER );
 }
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, and trap_R_RegisterShaderNoMip().
Referenced by UI_Cache_f(), and UI_CinematicsMenu_Init().
UI_CinematicsMenu_Event()
static void UI_CinematicsMenu_Event (void * ptr, int event) static
Definition at line 97 of file ui_cinematics.c.
{
     int     n;
     if (event != QM_ACTIVATED)
         return;
     n = ((menucommon_s*)ptr)->id - ID_CIN_IDLOGO;
     trap_Cvar_Set( "nextmap", va( "ui_cinematics %i", n ) );
     if( uis.demoversion && ((menucommon_s*)ptr)->id == ID_CIN_END ) {
         trap_Cmd_ExecuteText( EXEC_APPEND, "disconnect; cinematic demoEnd.RoQ 1\n" );
     }
     else {
         trap_Cmd_ExecuteText( EXEC_APPEND, va( "disconnect; cinematic %s.RoQ\n", cinematics[n] ) );
     }
 }
References cinematics, uiStatic_t::demoversion, EXEC_APPEND, ID_CIN_END, ID_CIN_IDLOGO, QM_ACTIVATED, trap_Cmd_ExecuteText(), trap_Cvar_Set(), uis, and va().
Referenced by UI_CinematicsMenu_Init().
UI_CinematicsMenu_f()
void UI_CinematicsMenu_f (void)
Definition at line 344 of file ui_cinematics.c.
{
     int     n;
     n = atoi( UI_Argv( 1 ) );
     UI_CinematicsMenu();
     Menu_SetCursorToItem( &cinematicsMenuInfo.menu, cinematicsMenuInfo.menu.items[n + 3] );
 }
References cinematicsMenuInfo, _tag_menuframework::items, cinematicsMenuInfo_t::menu, Menu_SetCursorToItem(), UI_Argv(), and UI_CinematicsMenu().
Referenced by UI_ConsoleCommand().
UI_CinematicsMenu_Init()
static void UI_CinematicsMenu_Init (void) static
Definition at line 119 of file ui_cinematics.c.
{
     int     y;
     UI_CinematicsMenu_Cache();
     memset( &cinematicsMenuInfo, 0, sizeof(cinematicsMenuInfo) );
     cinematicsMenuInfo.menu.fullscreen = qtrue;
     cinematicsMenuInfo.banner.generic.type      = MTYPE_BTEXT;
     cinematicsMenuInfo.banner.generic.x         = 320;
     cinematicsMenuInfo.banner.generic.y         = 16;
     cinematicsMenuInfo.banner.string            = "CINEMATICS";
     cinematicsMenuInfo.banner.color             = color_white;
     cinematicsMenuInfo.banner.style             = UI_CENTER;
     cinematicsMenuInfo.framel.generic.type      = MTYPE_BITMAP;
     cinematicsMenuInfo.framel.generic.name      = ART_FRAMEL;
     cinematicsMenuInfo.framel.generic.flags     = QMF_INACTIVE;
     cinematicsMenuInfo.framel.generic.x         = 0;
     cinematicsMenuInfo.framel.generic.y         = 78;
     cinematicsMenuInfo.framel.width             = 256;
     cinematicsMenuInfo.framel.height            = 329;
     cinematicsMenuInfo.framer.generic.type      = MTYPE_BITMAP;
     cinematicsMenuInfo.framer.generic.name      = ART_FRAMER;
     cinematicsMenuInfo.framer.generic.flags     = QMF_INACTIVE;
     cinematicsMenuInfo.framer.generic.x         = 376;
     cinematicsMenuInfo.framer.generic.y         = 76;
     cinematicsMenuInfo.framer.width             = 256;
     cinematicsMenuInfo.framer.height            = 334;
     y = 100;
     cinematicsMenuInfo.cin_idlogo.generic.type      = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_idlogo.generic.flags     = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_idlogo.generic.x         = 320;
     cinematicsMenuInfo.cin_idlogo.generic.y         = y;
     cinematicsMenuInfo.cin_idlogo.generic.id        = ID_CIN_IDLOGO;
     cinematicsMenuInfo.cin_idlogo.generic.callback  = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_idlogo.string            = "ID LOGO";
     cinematicsMenuInfo.cin_idlogo.color             = color_red;
     cinematicsMenuInfo.cin_idlogo.style             = UI_CENTER;
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_intro.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_intro.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_intro.generic.x          = 320;
     cinematicsMenuInfo.cin_intro.generic.y          = y;
     cinematicsMenuInfo.cin_intro.generic.id         = ID_CIN_INTRO;
     cinematicsMenuInfo.cin_intro.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_intro.string             = "INTRO";
     cinematicsMenuInfo.cin_intro.color              = color_red;
     cinematicsMenuInfo.cin_intro.style              = UI_CENTER;
     if( uis.demoversion ) {
         cinematicsMenuInfo.cin_intro.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_tier1.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_tier1.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_tier1.generic.x          = 320;
     cinematicsMenuInfo.cin_tier1.generic.y          = y;
     cinematicsMenuInfo.cin_tier1.generic.id         = ID_CIN_TIER1;
     cinematicsMenuInfo.cin_tier1.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_tier1.string             = "Tier 1";
     cinematicsMenuInfo.cin_tier1.color              = color_red;
     cinematicsMenuInfo.cin_tier1.style              = UI_CENTER;
     if( !UI_CanShowTierVideo( 1 ) ) {
         cinematicsMenuInfo.cin_tier1.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_tier2.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_tier2.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_tier2.generic.x          = 320;
     cinematicsMenuInfo.cin_tier2.generic.y          = y;
     cinematicsMenuInfo.cin_tier2.generic.id         = ID_CIN_TIER2;
     cinematicsMenuInfo.cin_tier2.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_tier2.string             = "Tier 2";
     cinematicsMenuInfo.cin_tier2.color              = color_red;
     cinematicsMenuInfo.cin_tier2.style              = UI_CENTER;
     if( !UI_CanShowTierVideo( 2 ) ) {
         cinematicsMenuInfo.cin_tier2.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_tier3.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_tier3.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_tier3.generic.x          = 320;
     cinematicsMenuInfo.cin_tier3.generic.y          = y;
     cinematicsMenuInfo.cin_tier3.generic.id         = ID_CIN_TIER3;
     cinematicsMenuInfo.cin_tier3.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_tier3.string             = "Tier 3";
     cinematicsMenuInfo.cin_tier3.color              = color_red;
     cinematicsMenuInfo.cin_tier3.style              = UI_CENTER;
     if( !UI_CanShowTierVideo( 3 ) ) {
         cinematicsMenuInfo.cin_tier3.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_tier4.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_tier4.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_tier4.generic.x          = 320;
     cinematicsMenuInfo.cin_tier4.generic.y          = y;
     cinematicsMenuInfo.cin_tier4.generic.id         = ID_CIN_TIER4;
     cinematicsMenuInfo.cin_tier4.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_tier4.string             = "Tier 4";
     cinematicsMenuInfo.cin_tier4.color              = color_red;
     cinematicsMenuInfo.cin_tier4.style              = UI_CENTER;
     if( !UI_CanShowTierVideo( 4 ) ) {
         cinematicsMenuInfo.cin_tier4.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_tier5.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_tier5.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_tier5.generic.x          = 320;
     cinematicsMenuInfo.cin_tier5.generic.y          = y;
     cinematicsMenuInfo.cin_tier5.generic.id         = ID_CIN_TIER5;
     cinematicsMenuInfo.cin_tier5.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_tier5.string             = "Tier 5";
     cinematicsMenuInfo.cin_tier5.color              = color_red;
     cinematicsMenuInfo.cin_tier5.style              = UI_CENTER;
     if( !UI_CanShowTierVideo( 5 ) ) {
         cinematicsMenuInfo.cin_tier5.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_tier6.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_tier6.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_tier6.generic.x          = 320;
     cinematicsMenuInfo.cin_tier6.generic.y          = y;
     cinematicsMenuInfo.cin_tier6.generic.id         = ID_CIN_TIER6;
     cinematicsMenuInfo.cin_tier6.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_tier6.string             = "Tier 6";
     cinematicsMenuInfo.cin_tier6.color              = color_red;
     cinematicsMenuInfo.cin_tier6.style              = UI_CENTER;
     if( !UI_CanShowTierVideo( 6 ) ) {
         cinematicsMenuInfo.cin_tier6.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_tier7.generic.type       = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_tier7.generic.flags      = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_tier7.generic.x          = 320;
     cinematicsMenuInfo.cin_tier7.generic.y          = y;
     cinematicsMenuInfo.cin_tier7.generic.id         = ID_CIN_TIER7;
     cinematicsMenuInfo.cin_tier7.generic.callback   = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_tier7.string             = "Tier 7";
     cinematicsMenuInfo.cin_tier7.color              = color_red;
     cinematicsMenuInfo.cin_tier7.style              = UI_CENTER;
     if( !UI_CanShowTierVideo( 7 ) ) {
         cinematicsMenuInfo.cin_tier7.generic.flags |= QMF_GRAYED;
     }
     y += VERTICAL_SPACING;
     cinematicsMenuInfo.cin_end.generic.type         = MTYPE_PTEXT;
     cinematicsMenuInfo.cin_end.generic.flags        = QMF_CENTER_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.cin_end.generic.x            = 320;
     cinematicsMenuInfo.cin_end.generic.y            = y;
     cinematicsMenuInfo.cin_end.generic.id           = ID_CIN_END;
     cinematicsMenuInfo.cin_end.generic.callback     = UI_CinematicsMenu_Event;
     cinematicsMenuInfo.cin_end.string               = "END";
     cinematicsMenuInfo.cin_end.color                = color_red;
     cinematicsMenuInfo.cin_end.style                = UI_CENTER;
     if( !UI_CanShowTierVideo( 8 ) ) {
         cinematicsMenuInfo.cin_end.generic.flags |= QMF_GRAYED;
     }
     cinematicsMenuInfo.back.generic.type        = MTYPE_BITMAP;
     cinematicsMenuInfo.back.generic.name        = ART_BACK0;
     cinematicsMenuInfo.back.generic.flags       = QMF_LEFT_JUSTIFY|QMF_PULSEIFFOCUS;
     cinematicsMenuInfo.back.generic.id          = ID_BACK;
     cinematicsMenuInfo.back.generic.callback    = UI_CinematicsMenu_BackEvent;
     cinematicsMenuInfo.back.generic.x           = 0;
     cinematicsMenuInfo.back.generic.y           = 480-64;
     cinematicsMenuInfo.back.width               = 128;
     cinematicsMenuInfo.back.height              = 64;
     cinematicsMenuInfo.back.focuspic            = ART_BACK1;
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.banner );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.framel );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.framer );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_idlogo );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_intro );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_tier1 );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_tier2 );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_tier3 );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_tier4 );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_tier5 );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_tier6 );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_tier7 );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.cin_end );
     Menu_AddItem( &cinematicsMenuInfo.menu, &cinematicsMenuInfo.back );
 }
References ART_BACK0, ART_BACK1, ART_FRAMEL, ART_FRAMER, cinematicsMenuInfo_t::back, cinematicsMenuInfo_t::banner, menucommon_s::callback, cinematicsMenuInfo_t::cin_end, cinematicsMenuInfo_t::cin_idlogo, cinematicsMenuInfo_t::cin_intro, cinematicsMenuInfo_t::cin_tier1, cinematicsMenuInfo_t::cin_tier2, cinematicsMenuInfo_t::cin_tier3, cinematicsMenuInfo_t::cin_tier4, cinematicsMenuInfo_t::cin_tier5, cinematicsMenuInfo_t::cin_tier6, cinematicsMenuInfo_t::cin_tier7, cinematicsMenuInfo, menutext_s::color, color_red, color_white, uiStatic_t::demoversion, menucommon_s::flags, menubitmap_s::focuspic, cinematicsMenuInfo_t::framel, cinematicsMenuInfo_t::framer, _tag_menuframework::fullscreen, menubitmap_s::generic, menutext_s::generic, menubitmap_s::height, menucommon_s::id, ID_BACK, ID_CIN_END, ID_CIN_IDLOGO, ID_CIN_INTRO, ID_CIN_TIER1, ID_CIN_TIER2, ID_CIN_TIER3, ID_CIN_TIER4, ID_CIN_TIER5, ID_CIN_TIER6, ID_CIN_TIER7, cinematicsMenuInfo_t::menu, Menu_AddItem(), MTYPE_BITMAP, MTYPE_BTEXT, MTYPE_PTEXT, menucommon_s::name, QMF_CENTER_JUSTIFY, QMF_GRAYED, QMF_INACTIVE, QMF_LEFT_JUSTIFY, QMF_PULSEIFFOCUS, qtrue, menutext_s::string, menutext_s::style, menucommon_s::type, UI_CanShowTierVideo(), UI_CENTER, UI_CinematicsMenu_BackEvent(), UI_CinematicsMenu_Cache(), UI_CinematicsMenu_Event(), uis, VERTICAL_SPACING, menubitmap_s::width, menucommon_s::x, and menucommon_s::y.
Referenced by UI_CinematicsMenu().
Variable Documentation
cinematics
char* cinematics[] static
Initial value:
= {
    "idlogo",
    "intro",
    "tier1",
    "tier2",
    "tier3",
    "tier4",
    "tier5",
    "tier6",
    "tier7",
    "end"
}
Definition at line 66 of file ui_cinematics.c.
Referenced by UI_CinematicsMenu_Event().
cinematicsMenuInfo
cinematicsMenuInfo_t cinematicsMenuInfo static
Definition at line 64 of file ui_cinematics.c.
Referenced by UI_CinematicsMenu(), UI_CinematicsMenu_f(), and UI_CinematicsMenu_Init().