ioquake3 doxygen: C:/entry/dev/ioq3/code/q3_ui/ui_atoms.c File Reference
ui_atoms.c File Reference
#include "ui_local.h"
Macros
#define PROPB_GAP_WIDTH 4
#define PROPB_SPACE_WIDTH 12
#define PROPB_HEIGHT 36
Functions
void QDECL Com_Error (int level, const char *error,...)
void QDECL Com_Printf (const char *msg,...)
float UI_ClampCvar (float min, float max, float value)
void UI_StartDemoLoop (void)
void UI_PushMenu (menuframework_s *menu)
void UI_PopMenu (void)
void UI_ForceMenuOff (void)
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
static void UI_DrawBannerString2 (int x, int y, const char *str, vec4_t color)
void UI_DrawBannerString (int x, int y, const char *str, int style, vec4_t color)
int UI_ProportionalStringWidth (const char *str)
static void UI_DrawProportionalString2 (int x, int y, const char *str, vec4_t color, float sizeScale, qhandle_t charset)
float UI_ProportionalSizeScale (int style)
void UI_DrawProportionalString (int x, int y, const char *str, int style, vec4_t color)
void UI_DrawProportionalString_AutoWrapped (int x, int y, int xmax, int ystep, const char *str, int style, vec4_t color)
static void UI_DrawString2 (int x, int y, const char *str, vec4_t color, int charw, int charh)
void UI_DrawString (int x, int y, const char *str, int style, vec4_t color)
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
qboolean UI_IsFullscreen (void)
static void NeedCDAction (qboolean result)
static void NeedCDKeyAction (qboolean result)
void UI_SetActiveMenu (uiMenuCommand_t menu)
void UI_KeyEvent (int key, int down)
void UI_MouseEvent (int dx, int dy)
char * UI_Argv (int arg)
char * UI_Cvar_VariableString (const char *var_name)
void UI_Cache_f (void)
qboolean UI_ConsoleCommand (int realTime)
void UI_Shutdown (void)
void UI_Init (void)
void UI_AdjustFrom640 (float *x, float *y, float *w, float *h)
void UI_DrawNamedPic (float x, float y, float width, float height, const char *picname)
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
void UI_FillRect (float x, float y, float width, float height, const float *color)
void UI_DrawRect (float x, float y, float width, float height, const float *color)
void UI_SetColor (const float *rgba)
void UI_UpdateScreen (void)
void UI_Refresh (int realtime)
void UI_DrawTextBox (int x, int y, int width, int lines)
qboolean UI_CursorInRect (int x, int y, int width, int height)
Variables
uiStatic_t uis
qboolean m_entersound
static int propMap [128][3]
static int propMapB [26][3]
Macro Definition Documentation
PROPB_GAP_WIDTH
#define PROPB_GAP_WIDTH 4
Definition at line 329 of file ui_atoms.c.
PROPB_HEIGHT
#define PROPB_HEIGHT 36
Definition at line 331 of file ui_atoms.c.
PROPB_SPACE_WIDTH
#define PROPB_SPACE_WIDTH 12
Definition at line 330 of file ui_atoms.c.
Function Documentation
Com_Error()
void QDECL Com_Error (int level, const char * error, ...)
Definition at line 33 of file ui_atoms.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, error);
     Q_vsnprintf (text, sizeof(text), error, argptr);
     va_end (argptr);
     trap_Error( text );
 }
References Q_vsnprintf(), and trap_Error().
Com_Printf()
void QDECL Com_Printf (const char * msg, ...)
Definition at line 44 of file ui_atoms.c.
{
     va_list     argptr;
     char        text[1024];
     va_start (argptr, msg);
     Q_vsnprintf (text, sizeof(text), msg, argptr);
     va_end (argptr);
     trap_Print( text );
 }
References Q_vsnprintf(), and trap_Print().
Referenced by UI_SetActiveMenu().
NeedCDAction()
static void NeedCDAction (qboolean result) static
Definition at line 796 of file ui_atoms.c.
{
     if ( !result ) {
         trap_Cmd_ExecuteText( EXEC_APPEND, "quit\n" );
     }
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
Referenced by UI_SetActiveMenu().
NeedCDKeyAction()
static void NeedCDKeyAction (qboolean result) static
Definition at line 802 of file ui_atoms.c.
{
     if ( !result ) {
         trap_Cmd_ExecuteText( EXEC_APPEND, "quit\n" );
     }
 }
References EXEC_APPEND, and trap_Cmd_ExecuteText().
Referenced by UI_SetActiveMenu().
UI_AdjustFrom640()
void UI_AdjustFrom640 (float * x, float * y, float * w, float * h)
Definition at line 1105 of file ui_atoms.c.
{
     // expect valid pointers
     *x = *x * uis.xscale + uis.bias;
     *y *= uis.yscale;
     *w *= uis.xscale;
     *h *= uis.yscale;
 }
Referenced by _UI_DrawSides(), _UI_DrawTopBottom(), Main_MenuDraw(), Text_PaintChar(), UI_DrawCinematic(), UI_DrawHandlePic(), UI_DrawNamedPic(), UI_DrawPlayer(), UI_DrawRect(), UI_DrawSides(), UI_DrawTopBottom(), and UI_FillRect().
UI_Argv()
char* UI_Argv (int arg)
Definition at line 939 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Argv( arg, buffer, sizeof( buffer ) );
     return buffer;
 }
Referenced by UI_CalcPostGameStats(), UI_CinematicsMenu_f(), UI_ConsoleCommand(), and UI_SPPostgameMenu_f().
UI_Cache_f()
void UI_Cache_f (void)
Definition at line 962 of file ui_atoms.c.
{
     MainMenu_Cache();
     InGame_Cache();
     ConfirmMenu_Cache();
     PlayerModel_Cache();
     PlayerSettings_Cache();
     Controls_Cache();
     Demos_Cache();
     UI_CinematicsMenu_Cache();
     Preferences_Cache();
     ServerInfo_Cache();
     SpecifyServer_Cache();
     ArenaServers_Cache();
     StartServer_Cache();
     ServerOptions_Cache();
     DriverInfo_Cache();
     GraphicsOptions_Cache();
     UI_DisplayOptionsMenu_Cache();
     UI_SoundOptionsMenu_Cache();
     UI_NetworkOptionsMenu_Cache();
     UI_SPLevelMenu_Cache();
     UI_SPSkillMenu_Cache();
     UI_SPPostgameMenu_Cache();
     TeamMain_Cache();
     UI_AddBots_Cache();
     UI_RemoveBots_Cache();
     UI_SetupMenu_Cache();
 //  UI_LoadConfig_Cache();
 //  UI_SaveConfigMenu_Cache();
     UI_BotSelectMenu_Cache();
     UI_CDKeyMenu_Cache();
     UI_ModsMenu_Cache();
 }
References ArenaServers_Cache(), ConfirmMenu_Cache(), Controls_Cache(), Demos_Cache(), DriverInfo_Cache(), GraphicsOptions_Cache(), InGame_Cache(), MainMenu_Cache(), PlayerModel_Cache(), PlayerSettings_Cache(), Preferences_Cache(), ServerInfo_Cache(), ServerOptions_Cache(), SpecifyServer_Cache(), StartServer_Cache(), TeamMain_Cache(), UI_AddBots_Cache(), UI_BotSelectMenu_Cache(), UI_CDKeyMenu_Cache(), UI_CinematicsMenu_Cache(), UI_DisplayOptionsMenu_Cache(), UI_ModsMenu_Cache(), UI_NetworkOptionsMenu_Cache(), UI_RemoveBots_Cache(), UI_SetupMenu_Cache(), UI_SoundOptionsMenu_Cache(), UI_SPLevelMenu_Cache(), UI_SPPostgameMenu_Cache(), and UI_SPSkillMenu_Cache().
Referenced by UI_ConsoleCommand().
UI_ClampCvar()
float UI_ClampCvar (float min, float max, float value)
Definition at line 60 of file ui_atoms.c.
 {
     if ( value < min ) return min;
     if ( value > max ) return max;
     return value;
 }
Referenced by Controls_GetConfig().
UI_ConsoleCommand()
qboolean UI_ConsoleCommand (int realTime)
Definition at line 1003 of file ui_atoms.c.
{
     char    *cmd;
     uis.frametime = realTime - uis.realtime;
     uis.realtime = realTime;
     cmd = UI_Argv( 0 );
     // ensure minimum menu data is available
     Menu_Cache();
     if ( Q_stricmp (cmd, "levelselect") == 0 ) {
         UI_SPLevelMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "postgame") == 0 ) {
         UI_SPPostgameMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cache") == 0 ) {
         UI_Cache_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cinematics") == 0 ) {
         UI_CinematicsMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_teamOrders") == 0 ) {
         UI_TeamOrdersMenu_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "iamacheater") == 0 ) {
         UI_SPUnlock_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "iamamonkey") == 0 ) {
         UI_SPUnlockMedals_f();
         return qtrue;
     }
     if ( Q_stricmp (cmd, "ui_cdkey") == 0 ) {
         UI_CDKeyMenu_f();
         return qtrue;
     }
     return qfalse;
 }
Referenced by vmMain().
UI_CursorInRect()
qboolean UI_CursorInRect (int x, int y, int width, int height)
Definition at line 1263 of file ui_atoms.c.
 {
     if (uis.cursorx < x ||
         uis.cursory < y ||
         uis.cursorx > x+width ||
         uis.cursory > y+height)
         return qfalse;
     return qtrue;
 }
Referenced by ScrollList_Key(), and UI_TeamOrdersMenu_Key().
UI_Cvar_VariableString()
char* UI_Cvar_VariableString (const char * var_name)
Definition at line 948 of file ui_atoms.c.
{
     static char buffer[MAX_STRING_CHARS];
     trap_Cvar_VariableStringBuffer( var_name, buffer, sizeof( buffer ) );
     return buffer;
 }
Referenced by _UI_Init(), Controls_InitModel(), GraphicsOptions_SetMenuItems(), PlayerSettings_SetMenuItems(), ServerOptions_SetMenuItems(), SpecifyLeague_MenuInit(), UI_CalcPostGameStats(), UI_ClanName_HandleKey(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawClanName(), UI_DrawOpponent(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawOpponentName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawPlayerModel(), UI_DrawSelectedPlayer(), UI_DrawServerRefreshDate(), UI_DrawTeamName(), UI_HeadCountByTeam(), UI_Load(), UI_LoadNonIngame(), UI_NextOpponent(), UI_OpponentLeaderName(), UI_OwnerDrawWidth(), UI_PriorOpponent(), UI_RunMenuScript(), UI_StartServerRefresh(), UI_StartSkirmish(), UI_StopCinematic(), UI_TeamName_HandleKey(), and UI_Update().
UI_DrawBannerString()
void UI_DrawBannerString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 381 of file ui_atoms.c.
{
     const char *    s;
     int             ch;
     int             width;
     vec4_t          drawcolor;
     // find the width of the drawn text
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s;
         if ( ch == ' ' ) {
             width += PROPB_SPACE_WIDTH;
         }
         else if ( ch >= 'A' && ch <= 'Z' ) {
             width += propMapB[ch - 'A'][2] + PROPB_GAP_WIDTH;
         }
         s++;
     }
     width -= PROPB_GAP_WIDTH;
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             x -= width / 2;
             break;
         case UI_RIGHT:
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawBannerString2( x+2, y+2, str, drawcolor );
     }
     UI_DrawBannerString2( x, y, str, color );
 }
References PROPB_GAP_WIDTH, PROPB_SPACE_WIDTH, propMapB, s, UI_CENTER, UI_DrawBannerString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_LEFT, and UI_RIGHT.
UI_DrawBannerString2()
static void UI_DrawBannerString2 (int x, int y, const char * str, vec4_t color) static
Definition at line 338 of file ui_atoms.c.
 {
     const char* s;
     unsigned char   ch;
     float   ax;
     float   ay;
     float   aw;
     float   ah;
     float   frow;
     float   fcol;
     float   fwidth;
     float   fheight;
     // draw the colored text
     trap_R_SetColor( color );
     ax = x * uis.xscale + uis.bias;
     ay = y * uis.yscale;
     s = str;
     while ( *s )
     {
         ch = *s & 127;
         if ( ch == ' ' ) {
             ax += ((float)PROPB_SPACE_WIDTH + (float)PROPB_GAP_WIDTH)* uis.xscale;
         }
         else if ( ch >= 'A' && ch <= 'Z' ) {
             ch -= 'A';
             fcol = (float)propMapB[ch][0] / 256.0f;
             frow = (float)propMapB[ch][1] / 256.0f;
             fwidth = (float)propMapB[ch][2] / 256.0f;
             fheight = (float)PROPB_HEIGHT / 256.0f;
             aw = (float)propMapB[ch][2] * uis.xscale;
             ah = (float)PROPB_HEIGHT * uis.yscale;
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol+fwidth, frow+fheight, uis.charsetPropB );
             ax += (aw + (float)PROPB_GAP_WIDTH * uis.xscale);
         }
         s++;
     }
     trap_R_SetColor( NULL );
 }
References uiStatic_t::bias, uiStatic_t::charsetPropB, NULL, PROPB_GAP_WIDTH, PROPB_HEIGHT, PROPB_SPACE_WIDTH, propMapB, s, trap_R_DrawStretchPic(), trap_R_SetColor(), uis, uiStatic_t::xscale, and uiStatic_t::yscale.
Referenced by UI_DrawBannerString().
UI_DrawChar()
void UI_DrawChar (int x, int y, int ch, int style, vec4_t color)
Definition at line 778 of file ui_atoms.c.
 {
     char    buff[2];
     buff[0] = ch;
     buff[1] = '\0';
     UI_DrawString( x, y, buff, style, color );
 }
References UI_DrawString().
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), MField_Draw(), PlayerName_Draw(), PlayerSettings_DrawName(), RadioButton_Draw(), Rankings_DrawText(), SpinControl_Draw(), and UI_CDKeyMenu_DrawKey().
UI_DrawHandlePic()
void UI_DrawHandlePic (float x, float y, float w, float h, qhandle_t hShader)
Definition at line 1121 of file ui_atoms.c.
{
     float   s0;
     float   s1;
     float   t0;
     float   t1;
     if( w < 0 ) {   // flip about vertical
         w  = -w;
         s0 = 1;
         s1 = 0;
     }
     else {
         s0 = 0;
         s1 = 1;
     }
     if( h < 0 ) {   // flip about horizontal
         h  = -h;
         t0 = 1;
         t1 = 0;
     }
     else {
         t0 = 0;
         t1 = 1;
     }
     UI_AdjustFrom640( &x, &y, &w, &h );
     trap_R_DrawStretchPic( x, y, w, h, s0, t0, s1, t1, hShader );
 }
Referenced by _UI_Init(), _UI_Refresh(), Bitmap_Draw(), Crosshair_Draw(), PlayerSettings_DrawEffects(), RadioButton_Draw(), Slider_Draw(), StartServer_LevelshotDraw(), UI_DrawCenteredPic(), UI_DrawClanCinematic(), UI_DrawClanLogo(), UI_DrawConnectScreen(), UI_DrawCrosshair(), UI_DrawEffects(), UI_DrawMapPreview(), UI_DrawNetMapPreview(), UI_DrawOpponentLogo(), UI_DrawOpponentLogoMetal(), UI_DrawOpponentLogoName(), UI_DrawPlayerLogo(), UI_DrawPlayerLogoMetal(), UI_DrawPlayerLogoName(), UI_DrawTierMap(), UI_Refresh(), and UI_SPLevelMenu_MenuDraw().
UI_DrawNamedPic()
void UI_DrawNamedPic (float x, float y, float width, float height, const char * picname)
Definition at line 1113 of file ui_atoms.c.
{
     qhandle_t   hShader;
     hShader = trap_R_RegisterShaderNoMip( picname );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 1, 1, hShader );
 }
Referenced by ConfirmMenu_Draw(), MessageMenu_Draw(), Reset_MenuDraw(), and UI_SPPostgameMenu_DrawAwardsMedals().
UI_DrawProportionalString()
void UI_DrawProportionalString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 510 of file ui_atoms.c.
{
     vec4_t  drawcolor;
     int     width;
     float   sizeScale;
     if( !str ) {
         return;
     }
     sizeScale = UI_ProportionalSizeScale( style );
     switch( style & UI_FORMATMASK ) {
         case UI_CENTER:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width / 2;
             break;
         case UI_RIGHT:
             width = UI_ProportionalStringWidth( str ) * sizeScale;
             x -= width;
             break;
         case UI_LEFT:
         default:
             break;
     }
     if ( style & UI_DROPSHADOW ) {
         drawcolor[0] = drawcolor[1] = drawcolor[2] = 0;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x+2, y+2, str, drawcolor, sizeScale, uis.charsetProp );
     }
     if ( style & UI_INVERSE ) {
         drawcolor[0] = color[0] * 0.7;
         drawcolor[1] = color[1] * 0.7;
         drawcolor[2] = color[2] * 0.7;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, uis.charsetProp );
         return;
     }
     if ( style & UI_PULSE ) {
         drawcolor[0] = color[0] * 0.7;
         drawcolor[1] = color[1] * 0.7;
         drawcolor[2] = color[2] * 0.7;
         drawcolor[3] = color[3];
         UI_DrawProportionalString2( x, y, str, color, sizeScale, uis.charsetProp );
         drawcolor[0] = color[0];
         drawcolor[1] = color[1];
         drawcolor[2] = color[2];
         drawcolor[3] = 0.5 + 0.5 * sin( uis.realtime / PULSE_DIVISOR );
         UI_DrawProportionalString2( x, y, str, drawcolor, sizeScale, uis.charsetPropGlow );
         return;
     }
     UI_DrawProportionalString2( x, y, str, color, sizeScale, uis.charsetProp );
 }
References cg, cgs, uiStatic_t::charsetProp, cgMedia_t::charsetProp, uiStatic_t::charsetPropGlow, cgMedia_t::charsetPropGlow, cgs_t::media, PULSE_DIVISOR, uiStatic_t::realtime, cg_t::time, UI_CENTER, UI_DrawProportionalString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_INVERSE, UI_LEFT, UI_ProportionalSizeScale(), UI_ProportionalStringWidth(), UI_PULSE, UI_RIGHT, and uis.
Referenced by UI_DrawProportionalString_AutoWrapped().
UI_DrawProportionalString2()
static void UI_DrawProportionalString2 (int x, int y, const char * str, vec4_t color, float sizeScale, qhandle_t charset) static
Definition at line 448 of file ui_atoms.c.
 {
     const char* s;
     unsigned char   ch;
     float   ax;
     float   ay;
     float   aw = 0;
     float   ah;
     float   frow;
     float   fcol;
     float   fwidth;
     float   fheight;
     // draw the colored text
     trap_R_SetColor( color );
     ax = x * uis.xscale + uis.bias;
     ay = y * uis.yscale;
     s = str;
     while ( *s )
     {
         ch = *s & 127;
         if ( ch == ' ' ) {
             aw = (float)PROP_SPACE_WIDTH * uis.xscale * sizeScale;
         }
         else if ( propMap[ch][2] != -1 ) {
             fcol = (float)propMap[ch][0] / 256.0f;
             frow = (float)propMap[ch][1] / 256.0f;
             fwidth = (float)propMap[ch][2] / 256.0f;
             fheight = (float)PROP_HEIGHT / 256.0f;
             aw = (float)propMap[ch][2] * uis.xscale * sizeScale;
             ah = (float)PROP_HEIGHT * uis.yscale * sizeScale;
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol+fwidth, frow+fheight, charset );
         }
         ax += (aw + (float)PROP_GAP_WIDTH * uis.xscale * sizeScale);
         s++;
     }
     trap_R_SetColor( NULL );
 }
References uiStatic_t::bias, NULL, PROP_GAP_WIDTH, PROP_HEIGHT, PROP_SPACE_WIDTH, propMap, s, trap_R_DrawStretchPic(), trap_R_SetColor(), uis, uiStatic_t::xscale, and uiStatic_t::yscale.
Referenced by UI_DrawProportionalString().
UI_DrawProportionalString_AutoWrapped()
void UI_DrawProportionalString_AutoWrapped (int x, int y, int xmax, int ystep, const char * str, int style, vec4_t color)
Definition at line 575 of file ui_atoms.c.
{
     int width;
     char *s1,*s2,*s3;
     char c_bcp;
     char buf[1024];
     float   sizeScale;
     if (!str || str[0]=='\0')
         return;
     sizeScale = UI_ProportionalSizeScale( style );
     Q_strncpyz(buf, str, sizeof(buf));
     s1 = s2 = s3 = buf;
     while (1) {
         do {
             s3++;
         } while (*s3!=' ' && *s3!='\0');
         c_bcp = *s3;
         *s3 = '\0';
         width = UI_ProportionalStringWidth(s1) * sizeScale;
         *s3 = c_bcp;
         if (width > xmax) {
             if (s1==s2)
             {
                 // fuck, don't have a clean cut, we'll overflow
                 s2 = s3;
             }
             *s2 = '\0';
             UI_DrawProportionalString(x, y, s1, style, color);
             y += ystep;
             if (c_bcp == '\0')
       {
         // that was the last word
         // we could start a new loop, but that wouldn't be much use
         // even if the word is too long, we would overflow it (see above)
         // so just print it now if needed
         s2++;
         if (*s2 != '\0') // if we are printing an overflowing line we have s2 == s3
           UI_DrawProportionalString(x, y, s2, style, color);
                 break;
       }
             s2++;
             s1 = s2;
             s3 = s2;
         }
         else
         {
             s2 = s3;
             if (c_bcp == '\0') // we reached the end
             {
                 UI_DrawProportionalString(x, y, s1, style, color);
                 break;
             }
         }
     }
 }
References Q_strncpyz(), UI_DrawProportionalString(), UI_ProportionalSizeScale(), and UI_ProportionalStringWidth().
Referenced by Main_MenuDraw(), and UI_DrawConnectScreen().
UI_DrawRect()
void UI_DrawRect (float x, float y, float width, float height, const float * color)
Definition at line 1174 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x, y + height - 1, width, 1, 0, 0, 0, 0, uis.whiteShader );
     trap_R_DrawStretchPic( x + width - 1, y, 1, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
Referenced by Menu_Draw(), and UI_DrawTextBox().
UI_DrawString()
void UI_DrawString (int x, int y, const char * str, int style, vec4_t color)
Definition at line 699 of file ui_atoms.c.
 {
     int     len;
     int     charw;
     int     charh;
     vec4_t  newcolor;
     vec4_t  lowlight;
     float   *drawcolor;
     vec4_t  dropcolor;
     if( !str ) {
         return;
     }
     if ((style & UI_BLINK) && ((uis.realtime/BLINK_DIVISOR) & 1))
         return;
     if (style & UI_SMALLFONT)
     {
         charw = SMALLCHAR_WIDTH;
         charh = SMALLCHAR_HEIGHT;
     }
     else if (style & UI_GIANTFONT)
     {
         charw = GIANTCHAR_WIDTH;
         charh = GIANTCHAR_HEIGHT;
     }
     else
     {
         charw = BIGCHAR_WIDTH;
         charh = BIGCHAR_HEIGHT;
     }
     if (style & UI_PULSE)
     {
         lowlight[0] = 0.8*color[0];
         lowlight[1] = 0.8*color[1];
         lowlight[2] = 0.8*color[2];
         lowlight[3] = 0.8*color[3];
         UI_LerpColor(color,lowlight,newcolor,0.5+0.5*sin(uis.realtime/PULSE_DIVISOR));
         drawcolor = newcolor;
     }
     else
         drawcolor = color;
     switch (style & UI_FORMATMASK)
     {
         case UI_CENTER:
             // center justify at x
             len = strlen(str);
             x   = x - len*charw/2;
             break;
         case UI_RIGHT:
             // right justify at x
             len = strlen(str);
             x   = x - len*charw;
             break;
         default:
             // left justify at x
             break;
     }
     if ( style & UI_DROPSHADOW )
     {
         dropcolor[0] = dropcolor[1] = dropcolor[2] = 0;
         dropcolor[3] = drawcolor[3];
         UI_DrawString2(x+2,y+2,str,dropcolor,charw,charh);
     }
     UI_DrawString2(x,y,str,drawcolor,charw,charh);
 }
References BIGCHAR_HEIGHT, BIGCHAR_WIDTH, BLINK_DIVISOR, GIANTCHAR_HEIGHT, GIANTCHAR_WIDTH, PULSE_DIVISOR, uiStatic_t::realtime, SMALLCHAR_HEIGHT, SMALLCHAR_WIDTH, UI_BLINK, UI_CENTER, UI_DrawString2(), UI_DROPSHADOW, UI_FORMATMASK, UI_GIANTFONT, UI_LerpColor(), UI_PULSE, UI_RIGHT, UI_SMALLFONT, and uis.
Referenced by Action_Draw(), Controls_DrawKeyBinding(), Controls_StatusBar(), Crosshair_Draw(), DriverInfo_MenuDraw(), Main_MenuDraw(), MenuField_Draw(), MField_Draw(), PlayerName_Draw(), RadioButton_Draw(), ScrollList_Draw(), ServerInfo_MenuDraw(), ServerOptions_LevelshotDraw(), ServerOptions_StatusBar(), Slider_Draw(), SpinControl_Draw(), StartServer_LevelshotDraw(), Text_Draw(), UI_CDKeyMenu_DrawKey(), UI_CreditMenu_Draw(), UI_CreditMenu_Draw_ioq3(), UI_DrawChar(), UI_Refresh(), UI_SPLevelMenu_MenuDraw(), UI_SPPostgameMenu_DrawAwardsMedals(), and UI_SPPostgameMenu_MenuDrawScoreLine().
UI_DrawString2()
static void UI_DrawString2 (int x, int y, const char * str, vec4_t color, int charw, int charh) static
Definition at line 639 of file ui_atoms.c.
 {
     const char* s;
     char    ch;
     int forceColor = qfalse; //APSFIXME;
     vec4_t  tempcolor;
     float   ax;
     float   ay;
     float   aw;
     float   ah;
     float   frow;
     float   fcol;
     if (y < -charh)
         // offscreen
         return;
     // draw the colored text
     trap_R_SetColor( color );
     ax = x * uis.xscale + uis.bias;
     ay = y * uis.yscale;
     aw = charw * uis.xscale;
     ah = charh * uis.yscale;
     s = str;
     while ( *s )
     {
         if ( Q_IsColorString( s ) )
         {
             if ( !forceColor )
             {
                 memcpy( tempcolor, g_color_table[ColorIndex(s[1])], sizeof( tempcolor ) );
                 tempcolor[3] = color[3];
                 trap_R_SetColor( tempcolor );
             }
             s += 2;
             continue;
         }
         ch = *s & 255;
         if (ch != ' ')
         {
             frow = (ch>>4)*0.0625;
             fcol = (ch&15)*0.0625;
             trap_R_DrawStretchPic( ax, ay, aw, ah, fcol, frow, fcol + 0.0625, frow + 0.0625, uis.charset );
         }
         ax += aw;
         s++;
     }
     trap_R_SetColor( NULL );
 }
References uiStatic_t::bias, uiStatic_t::charset, ColorIndex, g_color_table, NULL, Q_IsColorString(), qfalse, s, trap_R_DrawStretchPic(), trap_R_SetColor(), uis, uiStatic_t::xscale, and uiStatic_t::yscale.
Referenced by UI_DrawString().
UI_DrawTextBox()
void UI_DrawTextBox (int x, int y, int width, int lines)
Definition at line 1257 of file ui_atoms.c.
 {
     UI_FillRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorBlack );
     UI_DrawRect( x + BIGCHAR_WIDTH/2, y + BIGCHAR_HEIGHT/2, ( width + 1 ) * BIGCHAR_WIDTH, ( lines + 1 ) * BIGCHAR_HEIGHT, colorWhite );
 }
UI_FillRect()
void UI_FillRect (float x, float y, float width, float height, const float * color)
Definition at line 1158 of file ui_atoms.c.
{
     trap_R_SetColor( color );
     UI_AdjustFrom640( &x, &y, &width, &height );
     trap_R_DrawStretchPic( x, y, width, height, 0, 0, 0, 0, uis.whiteShader );
     trap_R_SetColor( NULL );
 }
Referenced by _UI_Init(), Controls_DrawKeyBinding(), Crosshair_Draw(), MenuField_Draw(), PlayerName_Draw(), RadioButton_Draw(), ScrollList_Draw(), ServerOptions_LevelshotDraw(), SpinControl_Draw(), StartServer_LevelshotDraw(), UI_CDKeyMenu_DrawKey(), UI_DrawTextBox(), UI_SaveConfigMenu_SavenameDraw(), and UI_SPLevelMenu_MenuDraw().
UI_ForceMenuOff()
void UI_ForceMenuOff (void)
Definition at line 152 of file ui_atoms.c.
 {
     uis.menusp     = 0;
     uis.activemenu = NULL;
     trap_Key_SetCatcher( trap_Key_GetCatcher() & ~KEYCATCH_UI );
     trap_Key_ClearStates();
     trap_Cvar_Set( "cl_paused", "0" );
 }
References uiStatic_t::activemenu, KEYCATCH_UI, uiStatic_t::menusp, NULL, trap_Cvar_Set(), trap_Key_ClearStates(), trap_Key_GetCatcher(), trap_Key_SetCatcher(), and uis.
Referenced by Demos_MenuEvent(), Login_MenuEvent(), Rankings_MenuEvent(), Signup_MenuEvent(), TeamMain_MenuEvent(), UI_PopMenu(), UI_RankStatusMenu(), UI_SetActiveMenu(), and UI_SoundOptionsMenu_Event().
UI_Init()
void UI_Init (void)
Definition at line 1070 of file ui_atoms.c.
                      {
     UI_RegisterCvars();
     UI_InitGameinfo();
     // cache redundant calulations
     trap_GetGlconfig( &uis.glconfig );
     // for 640x480 virtualized screen
     uis.xscale = uis.glconfig.vidWidth * (1.0/640.0);
     uis.yscale = uis.glconfig.vidHeight * (1.0/480.0);
     if ( uis.glconfig.vidWidth * 480 > uis.glconfig.vidHeight * 640 ) {
         // wide screen
         uis.bias = 0.5 * ( uis.glconfig.vidWidth - ( uis.glconfig.vidHeight * (640.0/480.0) ) );
         uis.xscale = uis.yscale;
     }
     else {
         // no wide screen
         uis.bias = 0;
     }
     // initialize the menu system
     Menu_Cache();
     uis.activemenu = NULL;
     uis.menusp     = 0;
 }
References uiStatic_t::activemenu, uiStatic_t::bias, uiStatic_t::glconfig, Menu_Cache(), uiStatic_t::menusp, NULL, trap_GetGlconfig(), UI_InitGameinfo(), UI_RegisterCvars(), uis, glconfig_t::vidHeight, glconfig_t::vidWidth, uiStatic_t::xscale, and uiStatic_t::yscale.
Referenced by vmMain().
UI_IsFullscreen()
qboolean UI_IsFullscreen (void)
Definition at line 788 of file ui_atoms.c.
{
     if ( uis.activemenu && ( trap_Key_GetCatcher() & KEYCATCH_UI ) ) {
         return uis.activemenu->fullscreen;
     }
     return qfalse;
 }
References uiStatic_t::activemenu, _tag_menuframework::fullscreen, KEYCATCH_UI, qfalse, trap_Key_GetCatcher(), and uis.
Referenced by vmMain().
UI_KeyEvent()
void UI_KeyEvent (int key, int down)
Definition at line 851 of file ui_atoms.c.
{
     sfxHandle_t     s;
     if (!uis.activemenu) {
         return;
     }
     if (!down) {
         return;
     }
     if (uis.activemenu->key)
         s = uis.activemenu->key( key );
     else
         s = Menu_DefaultKey( uis.activemenu, key );
     if ((s > 0) && (s != menu_null_sound))
         trap_S_StartLocalSound( s, CHAN_LOCAL_SOUND );
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, _tag_menuframework::key, Menu_DefaultKey(), menu_null_sound, s, trap_S_StartLocalSound(), and uis.
Referenced by vmMain().
UI_LerpColor()
void UI_LerpColor (vec4_t a, vec4_t b, vec4_t c, float t)
Definition at line 167 of file ui_atoms.c.
 {
     int i;
     // lerp and clamp each component
     for (i=0; i<4; i++)
     {
         c[i] = a[i] + t*(b[i]-a[i]);
         if (c[i] < 0)
             c[i] = 0;
         else if (c[i] > 1.0)
             c[i] = 1.0;
     }
 }
References a, and t.
Referenced by UI_DrawString().
UI_MouseEvent()
void UI_MouseEvent (int dx, int dy)
Definition at line 876 of file ui_atoms.c.
 {
     int             i;
     int             bias;
     menucommon_s*   m;
     if (!uis.activemenu)
         return;
     // convert X bias to 640 coords
     bias = uis.bias / uis.xscale;
     // update mouse screen position
     uis.cursorx += dx;
     if (uis.cursorx < -bias)
         uis.cursorx = -bias;
     else if (uis.cursorx > SCREEN_WIDTH+bias)
         uis.cursorx = SCREEN_WIDTH+bias;
     uis.cursory += dy;
     if (uis.cursory < 0)
         uis.cursory = 0;
     else if (uis.cursory > SCREEN_HEIGHT)
         uis.cursory = SCREEN_HEIGHT;
     // region test the active menu items
     for (i=0; i<uis.activemenu->nitems; i++)
     {
         m = (menucommon_s*)uis.activemenu->items[i];
         if (m->flags & (QMF_GRAYED|QMF_INACTIVE))
             continue;
         if ((uis.cursorx < m->left) ||
             (uis.cursorx > m->right) ||
             (uis.cursory < m->top) ||
             (uis.cursory > m->bottom))
         {
             // cursor out of item bounds
             continue;
         }
         // set focus to item at cursor
         if (uis.activemenu->cursor != i)
         {
             Menu_SetCursor( uis.activemenu, i );
             ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor_prev]))->flags &= ~QMF_HASMOUSEFOCUS;
             if ( !(((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags & QMF_SILENT ) ) {
                 trap_S_StartLocalSound( menu_move_sound, CHAN_LOCAL_SOUND );
             }
         }
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags |= QMF_HASMOUSEFOCUS;
         return;
     }
     if (uis.activemenu->nitems > 0) {
         // out of any region
         ((menucommon_s*)(uis.activemenu->items[uis.activemenu->cursor]))->flags &= ~QMF_HASMOUSEFOCUS;
     }
 }
References uiStatic_t::activemenu, uiStatic_t::bias, CHAN_LOCAL_SOUND, _tag_menuframework::cursor, _tag_menuframework::cursor_prev, uiStatic_t::cursorx, uiStatic_t::cursory, _tag_menuframework::items, m, menu_move_sound, Menu_SetCursor(), _tag_menuframework::nitems, QMF_GRAYED, QMF_HASMOUSEFOCUS, QMF_INACTIVE, QMF_SILENT, SCREEN_HEIGHT, SCREEN_WIDTH, trap_S_StartLocalSound(), uis, and uiStatic_t::xscale.
Referenced by UI_Refresh(), and vmMain().
UI_PopMenu()
void UI_PopMenu (void)
Definition at line 134 of file ui_atoms.c.
 {
     trap_S_StartLocalSound( menu_out_sound, CHAN_LOCAL_SOUND );
     uis.menusp--;
     if (uis.menusp < 0)
         trap_Error ("UI_PopMenu: menu stack underflow");
     if (uis.menusp) {
         uis.activemenu = uis.stack[uis.menusp-1];
         uis.firstdraw = qtrue;
     }
     else {
         UI_ForceMenuOff ();
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, uiStatic_t::firstdraw, menu_out_sound, uiStatic_t::menusp, qtrue, uiStatic_t::stack, trap_Error(), trap_S_StartLocalSound(), UI_ForceMenuOff(), and uis.
Referenced by ArenaServers_Event(), ConfirmMenu_Event(), Controls_MenuEvent(), Demos_MenuEvent(), DriverInfo_Event(), GraphicsOptions_Event(), InGame_Event(), InGame_QuitAction(), InGame_RestartAction(), LoadConfig_MenuEvent(), Login_MenuEvent(), MainMenu_ExitAction(), Menu_DefaultKey(), Options_Event(), PlayerModel_MenuEvent(), PlayerSettings_MenuEvent(), Preferences_Event(), RankStatus_MenuEvent(), Reset_MenuEvent(), ServerInfo_Event(), ServerOptions_Event(), Signup_MenuEvent(), SpecifyLeague_Event(), SpecifyServer_Event(), StartServer_MenuEvent(), UI_AddBotsMenu_BackEvent(), UI_BotSelectMenu_BackEvent(), UI_BotSelectMenu_SelectEvent(), UI_CDKeyMenu_Event(), UI_CinematicsMenu_BackEvent(), UI_DisplayOptionsMenu_Event(), UI_Mods_MenuEvent(), UI_NetworkOptionsMenu_Event(), UI_RemoveBotsMenu_BackEvent(), UI_SaveConfigMenu_BackEvent(), UI_SaveConfigMenu_SaveEvent(), UI_SetupMenu_Event(), UI_SoundOptionsMenu_Event(), UI_SPLevelMenu_BackEvent(), UI_SPLevelMenu_MenuDraw(), UI_SPLevelMenu_ResetAction(), UI_SPPostgameMenu_AgainEvent(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuEvent(), UI_SPPostgameMenu_NextEvent(), UI_SPSkillMenu_BackEvent(), UI_TeamOrdersMenu_BackEvent(), and UI_TeamOrdersMenu_ListEvent().
UI_ProportionalSizeScale()
float UI_ProportionalSizeScale (int style)
Definition at line 496 of file ui_atoms.c.
{
     if(  style & UI_SMALLFONT ) {
         return PROP_SMALL_SIZE_SCALE;
     }
     return 1.00;
 }
References PROP_SMALL_SIZE_SCALE, and UI_SMALLFONT.
Referenced by UI_DrawProportionalString(), and UI_DrawProportionalString_AutoWrapped().
UI_ProportionalStringWidth()
int UI_ProportionalStringWidth (const char * str)
Definition at line 426 of file ui_atoms.c.
{
     const char *    s;
     int             ch;
     int             charWidth;
     int             width;
     s = str;
     width = 0;
     while ( *s ) {
         ch = *s & 127;
         charWidth = propMap[ch][2];
         if ( charWidth != -1 ) {
             width += charWidth;
             width += PROP_GAP_WIDTH;
         }
         s++;
     }
     width -= PROP_GAP_WIDTH;
     return width;
 }
References PROP_GAP_WIDTH, propMap, and s.
Referenced by UI_DrawProportionalString(), and UI_DrawProportionalString_AutoWrapped().
UI_PushMenu()
void UI_PushMenu (menuframework_s * menu)
Definition at line 81 of file ui_atoms.c.
 {
     int             i;
     menucommon_s*   item;
     // avoid stacking menus invoked by hotkeys
     for (i=0 ; i<uis.menusp ; i++)
     {
         if (uis.stack[i] == menu)
         {
             uis.menusp = i;
             break;
         }
     }
     if (i == uis.menusp)
     {
         if (uis.menusp >= MAX_MENUDEPTH)
             trap_Error("UI_PushMenu: menu stack overflow");
         uis.stack[uis.menusp++] = menu;
     }
     uis.activemenu = menu;
     // default cursor position
     menu->cursor      = 0;
     menu->cursor_prev = 0;
     m_entersound = qtrue;
     trap_Key_SetCatcher( KEYCATCH_UI );
     // force first available item to have focus
     for (i=0; i<menu->nitems; i++)
     {
         item = (menucommon_s *)menu->items[i];
         if (!(item->flags & (QMF_GRAYED|QMF_MOUSEONLY|QMF_INACTIVE)))
         {
             menu->cursor_prev = -1;
             Menu_SetCursor( menu, i );
             break;
         }
     }
     uis.firstdraw = qtrue;
 }
References uiStatic_t::activemenu, _tag_menuframework::cursor, _tag_menuframework::cursor_prev, uiStatic_t::firstdraw, menucommon_s::flags, _tag_menuframework::items, KEYCATCH_UI, m_entersound, MAX_MENUDEPTH, Menu_SetCursor(), uiStatic_t::menusp, _tag_menuframework::nitems, QMF_GRAYED, QMF_INACTIVE, QMF_MOUSEONLY, qtrue, uiStatic_t::stack, trap_Error(), trap_Key_SetCatcher(), and uis.
Referenced by UI_AddBotsMenu(), UI_ArenaServersMenu(), UI_BotSelectMenu(), UI_CDKeyMenu(), UI_CinematicsMenu(), UI_ConfirmMenu_Style(), UI_ControlsMenu(), UI_CreditMenu(), UI_DemosMenu(), UI_DisplayOptionsMenu(), UI_DriverInfo_Menu(), UI_GraphicsOptionsMenu(), UI_InGameMenu(), UI_LoadConfigMenu(), UI_LoginMenu(), UI_MainMenu(), UI_Message(), UI_ModsMenu(), UI_NetworkOptionsMenu(), UI_PlayerModelMenu(), UI_PlayerSettingsMenu(), UI_PreferencesMenu(), UI_RankingsMenu(), UI_RankStatusMenu(), UI_RemoveBotsMenu(), UI_ResetMenu(), UI_SaveConfigMenu(), UI_ServerInfoMenu(), UI_ServerOptionsMenu(), UI_SetupMenu(), UI_SignupMenu(), UI_SoundOptionsMenu(), UI_SpecifyLeagueMenu(), UI_SpecifyServerMenu(), UI_SPLevelMenu(), UI_SPPostgameMenu_f(), UI_SPSkillMenu(), UI_StartServerMenu(), UI_SystemConfigMenu(), UI_TeamMainMenu(), and UI_TeamOrdersMenu().
UI_Refresh()
void UI_Refresh (int realtime)
Definition at line 1200 of file ui_atoms.c.
 {
     uis.frametime = realtime - uis.realtime;
     uis.realtime  = realtime;
     if ( !( trap_Key_GetCatcher() & KEYCATCH_UI ) ) {
         return;
     }
     UI_UpdateCvars();
     if ( uis.activemenu )
     {
         if (uis.activemenu->fullscreen)
         {
             // draw the background
             if( uis.activemenu->showlogo ) {
                 UI_DrawHandlePic( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, uis.menuBackShader );
             }
             else {
                 UI_DrawHandlePic( 0, 0, SCREEN_WIDTH, SCREEN_HEIGHT, uis.menuBackNoLogoShader );
             }
         }
         if (uis.activemenu->draw)
             uis.activemenu->draw();
         else
             Menu_Draw( uis.activemenu );
         if( uis.firstdraw ) {
             UI_MouseEvent( 0, 0 );
             uis.firstdraw = qfalse;
         }
     }
     // draw cursor
     UI_SetColor( NULL );
     UI_DrawHandlePic( uis.cursorx-16, uis.cursory-16, 32, 32, uis.cursor);
 #ifndef NDEBUG
     if (uis.debug)
     {
         // cursor coordinates
         UI_DrawString( 0, 0, va("(%d,%d)",uis.cursorx,uis.cursory), UI_LEFT|UI_SMALLFONT, colorRed );
     }
 #endif
     // delay playing the enter sound until after the
     // menu has been drawn, to avoid delay while
     // caching images
     if (m_entersound)
     {
         trap_S_StartLocalSound( menu_in_sound, CHAN_LOCAL_SOUND );
         m_entersound = qfalse;
     }
 }
References uiStatic_t::activemenu, CHAN_LOCAL_SOUND, colorRed, uiStatic_t::cursor, uiStatic_t::cursorx, uiStatic_t::cursory, uiStatic_t::debug, _tag_menuframework::draw, uiStatic_t::firstdraw, uiStatic_t::frametime, _tag_menuframework::fullscreen, KEYCATCH_UI, m_entersound, Menu_Draw(), menu_in_sound, uiStatic_t::menuBackNoLogoShader, uiStatic_t::menuBackShader, NULL, qfalse, uiStatic_t::realtime, SCREEN_HEIGHT, SCREEN_WIDTH, _tag_menuframework::showlogo, trap_Key_GetCatcher(), trap_S_StartLocalSound(), UI_DrawHandlePic(), UI_DrawString(), UI_LEFT, UI_MouseEvent(), UI_SetColor(), UI_SMALLFONT, UI_UpdateCvars(), uis, and va().
Referenced by vmMain().
UI_SetActiveMenu()
void UI_SetActiveMenu (uiMenuCommand_t menu)
Definition at line 808 of file ui_atoms.c.
{
     // this should be the ONLY way the menu system is brought up
     // ensure minimum menu data is cached
     Menu_Cache();
     switch ( menu ) {
     case UIMENU_NONE:
         UI_ForceMenuOff();
         return;
     case UIMENU_MAIN:
         UI_MainMenu();
         return;
     case UIMENU_NEED_CD:
         UI_ConfirmMenu( "Insert the CD", 0, NeedCDAction );
         return;
     case UIMENU_BAD_CD_KEY:
         UI_ConfirmMenu( "Bad CD Key", 0, NeedCDKeyAction );
         return;
     case UIMENU_INGAME:
         /*
         //GRank
         UI_RankingsMenu();
         return;
         */
         trap_Cvar_Set( "cl_paused", "1" );
         UI_InGameMenu();
         return;
     case UIMENU_TEAM:
     case UIMENU_POSTGAME:
     default:
 #ifndef NDEBUG
       Com_Printf("UI_SetActiveMenu: bad enum %d\n", menu );
 #endif
       break;
     }
 }
References Com_Printf(), Menu_Cache(), NeedCDAction(), NeedCDKeyAction(), trap_Cvar_Set(), UI_ConfirmMenu(), UI_ForceMenuOff(), UI_InGameMenu(), UI_MainMenu(), UIMENU_BAD_CD_KEY, UIMENU_INGAME, UIMENU_MAIN, UIMENU_NEED_CD, UIMENU_NONE, UIMENU_POSTGAME, and UIMENU_TEAM.
Referenced by vmMain().
UI_SetColor()
void UI_SetColor (const float * rgba)
Definition at line 1187 of file ui_atoms.c.
{
     trap_R_SetColor( rgba );
 }
Referenced by _UI_Init(), _UI_Refresh(), Slider_Draw(), UI_DisplayDownloadInfo(), UI_DrawConnectScreen(), and UI_Refresh().
UI_Shutdown()
void UI_Shutdown (void)
Definition at line 1062 of file ui_atoms.c.
{
 }
Referenced by vmMain().
UI_StartDemoLoop()
void UI_StartDemoLoop (void)
Definition at line 72 of file ui_atoms.c.
{
     trap_Cmd_ExecuteText( EXEC_APPEND, "d1\n" );
 }
UI_UpdateScreen()
void UI_UpdateScreen (void)
Definition at line 1191 of file ui_atoms.c.
{
     trap_UpdateScreen();
 }
Variable Documentation
m_entersound
qboolean m_entersound
Definition at line 31 of file ui_atoms.c.
Referenced by UI_PushMenu(), and UI_Refresh().
propMap
int propMap[128][3] static
Definition at line 187 of file ui_atoms.c.
Referenced by UI_DrawProportionalString2(), and UI_ProportionalStringWidth().
propMapB
int propMapB[26][3] static
Definition at line 297 of file ui_atoms.c.
Referenced by UI_DrawBannerString(), and UI_DrawBannerString2().
uis
uiStatic_t uis
Definition at line 30 of file ui_atoms.c.
Referenced by ArenaServers_DoRefresh(), ArenaServers_StartRefresh(), Bitmap_Draw(), Controls_DrawPlayer(), DriverInfo_MenuDraw(), GraphicsOptions_GetResolutions(), GraphicsOptions_MenuInit(), Main_MenuDraw(), Menu_Cache(), Menu_DefaultKey(), Menu_Draw(), PlayerModel_DrawPlayer(), PlayerSettings_DrawPlayer(), RadioButton_Draw(), ScrollList_Key(), Slider_Key(), UI_AdjustFrom640(), UI_CanShowTierVideo(), UI_CDKeyMenu_Init(), UI_CinematicsMenu_Event(), UI_CinematicsMenu_Init(), UI_ConsoleCommand(), UI_CursorInRect(), UI_DisplayDownloadInfo(), UI_DisplayOptionsMenu_Init(), UI_DrawBannerString2(), UI_DrawConnectScreen(), UI_DrawPlayer(), UI_DrawProportionalString(), UI_DrawProportionalString2(), UI_DrawRect(), UI_DrawString(), UI_DrawString2(), UI_DriverInfo_Menu(), UI_FillRect(), UI_ForceMenuOff(), UI_InGameMenu(), UI_Init(), UI_InitGameinfo(), UI_IsFullscreen(), UI_KeyEvent(), UI_MainMenu(), UI_MouseEvent(), UI_PlayerAnimation(), UI_PopMenu(), UI_PushMenu(), UI_Refresh(), UI_SPLevelMenu_f(), UI_SPLevelMenu_MenuDraw(), UI_SPPostgameMenu_f(), UI_SPPostgameMenu_Init(), UI_SPPostgameMenu_MenuDraw(), UI_SPPostgameMenu_MenuKey(), UI_SwingAngles(), and UI_TeamOrdersMenu_Key().