ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_cmds.c File Reference
g_cmds.c File Reference
#include "g_local.h"
Macros
#define EC "\x19"
Functions
void DeathmatchScoreboardMessage (gentity_t *ent)
void Cmd_Score_f (gentity_t *ent)
qboolean CheatsOk (gentity_t *ent)
char * ConcatArgs (int start)
qboolean StringIsInteger (const char *s)
int ClientNumberFromString (gentity_t *to, char *s, qboolean checkNums, qboolean checkNames)
void Cmd_Give_f (gentity_t *ent)
void Cmd_God_f (gentity_t *ent)
void Cmd_Notarget_f (gentity_t *ent)
void Cmd_Noclip_f (gentity_t *ent)
void Cmd_LevelShot_f (gentity_t *ent)
void Cmd_TeamTask_f (gentity_t *ent)
void Cmd_Kill_f (gentity_t *ent)
void BroadcastTeamChange (gclient_t *client, int oldTeam)
void SetTeam (gentity_t *ent, const char *s)
void StopFollowing (gentity_t *ent)
void Cmd_Team_f (gentity_t *ent)
void Cmd_Follow_f (gentity_t *ent)
void Cmd_FollowCycle_f (gentity_t *ent, int dir)
static void G_SayTo (gentity_t *ent, gentity_t *other, int mode, int color, const char *name, const char *message)
void G_Say (gentity_t *ent, gentity_t *target, int mode, const char *chatText)
static void SanitizeChatText (char *text)
static void Cmd_Say_f (gentity_t *ent, int mode, qboolean arg0)
static void Cmd_Tell_f (gentity_t *ent)
void Cmd_GameCommand_f (gentity_t *ent)
void Cmd_Where_f (gentity_t *ent)
void Cmd_CallVote_f (gentity_t *ent)
void Cmd_Vote_f (gentity_t *ent)
void Cmd_CallTeamVote_f (gentity_t *ent)
void Cmd_TeamVote_f (gentity_t *ent)
void Cmd_SetViewpos_f (gentity_t *ent)
void Cmd_Stats_f (gentity_t *ent)
void ClientCommand (int clientNum)
Variables
static char * gc_orders []
static const int numgc_orders = ARRAY_LEN(gc_orders)
static const char * gameNames []
Macro Definition Documentation
EC
#define EC "\x19"
Definition at line 878 of file g_cmds.c.
Function Documentation
BroadcastTeamChange()
void BroadcastTeamChange (gclient_t * client, int oldTeam)
Definition at line 496 of file g_cmds.c.
 {
     if (client->sess.sessionTeam == TEAM_RED) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the red team.\n\"",
             client->pers.netname));
     } else if (client->sess.sessionTeam == TEAM_BLUE) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the blue team.\n\"",
             client->pers.netname));
     } else if (client->sess.sessionTeam == TEAM_SPECTATOR && oldTeam != TEAM_SPECTATOR) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the spectators.\n\"",
             client->pers.netname));
     } else if (client->sess.sessionTeam == TEAM_FREE) {
         trap_SendServerCommand(-1, va("cp \"%s" S_COLOR_WHITE " joined the battle.\n\"",
             client->pers.netname));
     }
 }
References clientPersistant_t::netname, gclient_s::pers, S_COLOR_WHITE, gclient_s::sess, clientSession_t::sessionTeam, TEAM_BLUE, TEAM_FREE, TEAM_RED, TEAM_SPECTATOR, trap_SendServerCommand(), and va().
Referenced by ClientConnect(), and SetTeam().
CheatsOk()
qboolean CheatsOk (gentity_t * ent)
Definition at line 117 of file g_cmds.c.
 {
     if (!g_cheats.integer) {
         trap_SendServerCommand(ent - g_entities, "print \"Cheats are not enabled on this server.\n\"");
         return qfalse;
     }
     if (ent->health <= 0) {
         trap_SendServerCommand(ent - g_entities, "print \"You must be alive to use this command.\n\"");
         return qfalse;
     }
     return qtrue;
 }
References g_cheats, g_entities, gentity_s::health, vmCvar_t::integer, qfalse, qtrue, and trap_SendServerCommand().
Referenced by Cmd_Give_f(), Cmd_God_f(), Cmd_LevelShot_f(), Cmd_Noclip_f(), and Cmd_Notarget_f().
ClientCommand()
void ClientCommand (int clientNum)
Definition at line 1725 of file g_cmds.c.
 {
     gentity_t* ent;
     char       cmd[MAX_TOKEN_CHARS];
     ent = g_entities + clientNum;
     if (!ent->client || ent->client->pers.connected != CON_CONNECTED) {
         if (ent->client && ent->client->pers.localClient) {
             // Handle early team command sent by UI when starting a local
             // team play game.
             trap_Argv(0, cmd, sizeof(cmd));
             if (Q_stricmp(cmd, "team") == 0) {
                 Cmd_Team_f(ent);
             }
         }
         return; // not fully in game yet
     }
     trap_Argv(0, cmd, sizeof(cmd));
     if (Q_stricmp(cmd, "say") == 0) {
         Cmd_Say_f(ent, SAY_ALL, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "say_team") == 0) {
         Cmd_Say_f(ent, SAY_TEAM, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "tell") == 0) {
         Cmd_Tell_f(ent);
         return;
     }
 #ifdef MISSIONPACK
     if (Q_stricmp(cmd, "vsay") == 0) {
         Cmd_Voice_f(ent, SAY_ALL, qfalse, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "vsay_team") == 0) {
         Cmd_Voice_f(ent, SAY_TEAM, qfalse, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "vtell") == 0) {
         Cmd_VoiceTell_f(ent, qfalse);
         return;
     }
     if (Q_stricmp(cmd, "vosay") == 0) {
         Cmd_Voice_f(ent, SAY_ALL, qfalse, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "vosay_team") == 0) {
         Cmd_Voice_f(ent, SAY_TEAM, qfalse, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "votell") == 0) {
         Cmd_VoiceTell_f(ent, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "vtaunt") == 0) {
         Cmd_VoiceTaunt_f(ent);
         return;
     }
 #endif
     if (Q_stricmp(cmd, "score") == 0) {
         Cmd_Score_f(ent);
         return;
     }
     // ignore all other commands when at intermission
     if (level.intermissiontime) {
         Cmd_Say_f(ent, qfalse, qtrue);
         return;
     }
     if (Q_stricmp(cmd, "give") == 0)
         Cmd_Give_f(ent);
     else if (Q_stricmp(cmd, "god") == 0)
         Cmd_God_f(ent);
     else if (Q_stricmp(cmd, "notarget") == 0)
         Cmd_Notarget_f(ent);
     else if (Q_stricmp(cmd, "noclip") == 0)
         Cmd_Noclip_f(ent);
     else if (Q_stricmp(cmd, "kill") == 0)
         Cmd_Kill_f(ent);
     else if (Q_stricmp(cmd, "teamtask") == 0)
         Cmd_TeamTask_f(ent);
     else if (Q_stricmp(cmd, "levelshot") == 0)
         Cmd_LevelShot_f(ent);
     else if (Q_stricmp(cmd, "follow") == 0)
         Cmd_Follow_f(ent);
     else if (Q_stricmp(cmd, "follownext") == 0)
         Cmd_FollowCycle_f(ent, 1);
     else if (Q_stricmp(cmd, "followprev") == 0)
         Cmd_FollowCycle_f(ent, -1);
     else if (Q_stricmp(cmd, "team") == 0)
         Cmd_Team_f(ent);
     else if (Q_stricmp(cmd, "where") == 0)
         Cmd_Where_f(ent);
     else if (Q_stricmp(cmd, "callvote") == 0)
         Cmd_CallVote_f(ent);
     else if (Q_stricmp(cmd, "vote") == 0)
         Cmd_Vote_f(ent);
     else if (Q_stricmp(cmd, "callteamvote") == 0)
         Cmd_CallTeamVote_f(ent);
     else if (Q_stricmp(cmd, "teamvote") == 0)
         Cmd_TeamVote_f(ent);
     else if (Q_stricmp(cmd, "gc") == 0)
         Cmd_GameCommand_f(ent);
     else if (Q_stricmp(cmd, "setviewpos") == 0)
         Cmd_SetViewpos_f(ent);
     else if (Q_stricmp(cmd, "stats") == 0)
         Cmd_Stats_f(ent);
     else
         trap_SendServerCommand(clientNum, va("print \"unknown cmd %s\n\"", cmd));
 }
References gentity_s::client, Cmd_CallTeamVote_f(), Cmd_CallVote_f(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_GameCommand_f(), Cmd_Give_f(), Cmd_God_f(), Cmd_Kill_f(), Cmd_LevelShot_f(), Cmd_Noclip_f(), Cmd_Notarget_f(), Cmd_Say_f(), Cmd_Score_f(), Cmd_SetViewpos_f(), Cmd_Stats_f(), Cmd_Team_f(), Cmd_TeamTask_f(), Cmd_TeamVote_f(), Cmd_Tell_f(), Cmd_Vote_f(), Cmd_Where_f(), CON_CONNECTED, clientPersistant_t::connected, g_entities, level_locals_t::intermissiontime, level, clientPersistant_t::localClient, MAX_TOKEN_CHARS, gclient_s::pers, Q_stricmp(), qfalse, qtrue, SAY_ALL, SAY_TEAM, trap_Argv(), trap_SendServerCommand(), and va().
Referenced by vmMain().
ClientNumberFromString()
int ClientNumberFromString (gentity_t * to, char * s, qboolean checkNums, qboolean checkNames)
Definition at line 199 of file g_cmds.c.
 {
     gclient_t* cl;
     int            idnum;
     char        cleanName[MAX_STRING_CHARS];
     if (checkNums) {
         // numeric values could be slot numbers
         if (StringIsInteger(s)) {
             idnum = atoi(s);
             if (idnum >= 0 && idnum < level.maxclients) {
                 cl = &level.clients[idnum];
                 if (cl->pers.connected == CON_CONNECTED) {
                     return idnum;
                 }
             }
         }
     }
     if (checkNames) {
         // check for a name match
         for (idnum = 0, cl = level.clients; idnum < level.maxclients; idnum++, cl++) {
             if (cl->pers.connected != CON_CONNECTED) {
                 continue;
             }
             Q_strncpyz(cleanName, cl->pers.netname, sizeof(cleanName));
             Q_CleanStr(cleanName);
             if (!Q_stricmp(cleanName, s)) {
                 return idnum;
             }
         }
     }
     trap_SendServerCommand(to - g_entities, va("print \"User %s is not on the server\n\"", s));
     return -1;
 }
References cl, level_locals_t::clients, CON_CONNECTED, g_entities, level, MAX_STRING_CHARS, level_locals_t::maxclients, Q_CleanStr(), Q_stricmp(), Q_strncpyz(), s, StringIsInteger(), trap_SendServerCommand(), and va().
Referenced by Cmd_CallVote_f(), Cmd_Follow_f(), Cmd_GameCommand_f(), and Cmd_Tell_f().
Cmd_CallTeamVote_f()
void Cmd_CallTeamVote_f (gentity_t * ent)
Definition at line 1484 of file g_cmds.c.
 {
     char* c;
     int        i, team, cs_offset;
     char    arg1[MAX_STRING_TOKENS];
     char    arg2[MAX_STRING_TOKENS];
     team = ent->client->sess.sessionTeam;
     if (team == TEAM_RED)
         cs_offset = 0;
     else if (team == TEAM_BLUE)
         cs_offset = 1;
     else
         return;
     if (!g_allowVote.integer) {
         trap_SendServerCommand(ent - g_entities, "print \"Voting not allowed here.\n\"");
         return;
     }
     if (level.teamVoteTime[cs_offset]) {
         trap_SendServerCommand(ent - g_entities, "print \"A team vote is already in progress.\n\"");
         return;
     }
     if (ent->client->pers.teamVoteCount >= MAX_VOTE_COUNT) {
         trap_SendServerCommand(ent - g_entities, "print \"You have called the maximum number of team votes.\n\"");
         return;
     }
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         trap_SendServerCommand(ent - g_entities, "print \"Not allowed to call a vote as spectator.\n\"");
         return;
     }
     // make sure it is a valid command to vote on
     trap_Argv(1, arg1, sizeof(arg1));
     arg2[0] = '\0';
     for (i = 2; i < trap_Argc(); i++) {
         if (i > 2)
             strcat(arg2, " ");
         trap_Argv(i, &arg2[strlen(arg2)], sizeof(arg2) - strlen(arg2));
     }
     // check for command separators in arg2
     for (c = arg2; *c; ++c) {
         switch (*c) {
         case '\n':
         case '\r':
         case ';':
             trap_SendServerCommand(ent - g_entities, "print \"Invalid vote string.\n\"");
             return;
             break;
         }
     }
     if (!Q_stricmp(arg1, "leader")) {
         char netname[MAX_NETNAME], leader[MAX_NETNAME];
         if (!arg2[0]) {
             i = ent->client->ps.clientNum;
         } else {
             // numeric values are just slot numbers
             for (i = 0; i < 3; i++) {
                 if (!arg2[i] || arg2[i] < '0' || arg2[i] > '9')
                     break;
             }
             if (i >= 3 || !arg2[i]) {
                 i = atoi(arg2);
                 if (i < 0 || i >= level.maxclients) {
                     trap_SendServerCommand(ent - g_entities, va("print \"Bad client slot: %i\n\"", i));
                     return;
                 }
                 if (!g_entities[i].inuse) {
                     trap_SendServerCommand(ent - g_entities, va("print \"Client %i is not active\n\"", i));
                     return;
                 }
             } else {
                 Q_strncpyz(leader, arg2, sizeof(leader));
                 Q_CleanStr(leader);
                 for (i = 0; i < level.maxclients; i++) {
                     if (level.clients[i].pers.connected == CON_DISCONNECTED)
                         continue;
                     if (level.clients[i].sess.sessionTeam != team)
                         continue;
                     Q_strncpyz(netname, level.clients[i].pers.netname, sizeof(netname));
                     Q_CleanStr(netname);
                     if (!Q_stricmp(netname, leader)) {
                         break;
                     }
                 }
                 if (i >= level.maxclients) {
                     trap_SendServerCommand(ent - g_entities, va("print \"%s is not a valid player on your team.\n\"", arg2));
                     return;
                 }
             }
         }
         Com_sprintf(arg2, sizeof(arg2), "%d", i);
     } else {
         trap_SendServerCommand(ent - g_entities, "print \"Invalid vote string.\n\"");
         trap_SendServerCommand(ent - g_entities, "print \"Team vote commands are: leader <player>.\n\"");
         return;
     }
     Com_sprintf(level.teamVoteString[cs_offset], sizeof(level.teamVoteString[cs_offset]), "%s %s", arg1, arg2);
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].pers.connected == CON_DISCONNECTED)
             continue;
         if (level.clients[i].sess.sessionTeam == team)
             trap_SendServerCommand(i, va("print \"%s called a team vote.\n\"", ent->client->pers.netname));
     }
     // start the voting, the caller automatically votes yes
     level.teamVoteTime[cs_offset] = level.time;
     level.teamVoteYes[cs_offset] = 1;
     level.teamVoteNo[cs_offset] = 0;
     for (i = 0; i < level.maxclients; i++) {
         if (level.clients[i].sess.sessionTeam == team)
             level.clients[i].ps.eFlags &= ~EF_TEAMVOTED;
     }
     ent->client->ps.eFlags |= EF_TEAMVOTED;
     trap_SetConfigstring(CS_TEAMVOTE_TIME + cs_offset, va("%i", level.teamVoteTime[cs_offset]));
     trap_SetConfigstring(CS_TEAMVOTE_STRING + cs_offset, level.teamVoteString[cs_offset]);
     trap_SetConfigstring(CS_TEAMVOTE_YES + cs_offset, va("%i", level.teamVoteYes[cs_offset]));
     trap_SetConfigstring(CS_TEAMVOTE_NO + cs_offset, va("%i", level.teamVoteNo[cs_offset]));
 }
References gentity_s::client, playerState_s::clientNum, level_locals_t::clients, Com_sprintf(), CON_DISCONNECTED, clientPersistant_t::connected, CS_TEAMVOTE_NO, CS_TEAMVOTE_STRING, CS_TEAMVOTE_TIME, CS_TEAMVOTE_YES, EF_TEAMVOTED, playerState_s::eFlags, g_allowVote, g_entities, vmCvar_t::integer, level, MAX_NETNAME, MAX_STRING_TOKENS, MAX_VOTE_COUNT, level_locals_t::maxclients, clientPersistant_t::netname, gclient_s::pers, gclient_s::ps, Q_CleanStr(), Q_stricmp(), Q_strncpyz(), gclient_s::sess, clientSession_t::sessionTeam, TEAM_BLUE, TEAM_RED, TEAM_SPECTATOR, clientPersistant_t::teamVoteCount, level_locals_t::teamVoteNo, level_locals_t::teamVoteString, level_locals_t::teamVoteTime, level_locals_t::teamVoteYes, level_locals_t::time, trap_Argc(), trap_Argv(), trap_SendServerCommand(), trap_SetConfigstring(), and va().
Referenced by ClientCommand().
Cmd_CallVote_f()
void Cmd_CallVote_f (gentity_t * ent)
Definition at line 1302 of file g_cmds.c.
 {
     char* c;
     int        i;
     char    arg1[MAX_STRING_TOKENS];
     char    arg2[MAX_STRING_TOKENS];
     if (!g_allowVote.integer) {
         trap_SendServerCommand(ent - g_entities, "print \"Voting not allowed here.\n\"");
         return;
     }
     if (level.voteTime) {
         trap_SendServerCommand(ent - g_entities, "print \"A vote is already in progress.\n\"");
         return;
     }
     if (ent->client->pers.voteCount >= MAX_VOTE_COUNT) {
         trap_SendServerCommand(ent - g_entities, "print \"You have called the maximum number of votes.\n\"");
         return;
     }
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         trap_SendServerCommand(ent - g_entities, "print \"Not allowed to call a vote as spectator.\n\"");
         return;
     }
     // make sure it is a valid command to vote on
     trap_Argv(1, arg1, sizeof(arg1));
     trap_Argv(2, arg2, sizeof(arg2));
     // check for command separators in arg2
     for (c = arg2; *c; ++c) {
         switch (*c) {
         case '\n':
         case '\r':
         case ';':
             trap_SendServerCommand(ent - g_entities, "print \"Invalid vote string.\n\"");
             return;
             break;
         }
     }
     if (!Q_stricmp(arg1, "map_restart")) {
     } else if (!Q_stricmp(arg1, "nextmap")) {
     } else if (!Q_stricmp(arg1, "map")) {
     } else if (!Q_stricmp(arg1, "g_gametype")) {
     } else if (!Q_stricmp(arg1, "kick")) {
     } else if (!Q_stricmp(arg1, "clientkick")) {
     } else if (!Q_stricmp(arg1, "g_doWarmup")) {
     } else if (!Q_stricmp(arg1, "timelimit")) {
     } else if (!Q_stricmp(arg1, "fraglimit")) {
     } else {
         trap_SendServerCommand(ent - g_entities, "print \"Invalid vote string.\n\"");
         trap_SendServerCommand(ent - g_entities, "print \"Vote commands are: map_restart, nextmap, map <mapname>, g_gametype <n>, kick <player>, clientkick <clientnum>, g_doWarmup, timelimit <time>, fraglimit <frags>.\n\"");
         return;
     }
     // if there is still a vote to be executed
     if (level.voteExecuteTime) {
         // don't start a vote when map change or restart is in progress
         if (!Q_stricmpn(level.voteString, "map", 3)
             || !Q_stricmpn(level.voteString, "nextmap", 7)) {
             trap_SendServerCommand(ent - g_entities, "print \"Vote after map change.\n\"");
             return;
         }
         level.voteExecuteTime = 0;
         trap_SendConsoleCommand(EXEC_APPEND, va("%s\n", level.voteString));
     }
     // special case for g_gametype, check for bad values
     if (!Q_stricmp(arg1, "g_gametype")) {
         i = atoi(arg2);
         if (i == GT_SINGLE_PLAYER || i < GT_FFA || i >= GT_MAX_GAME_TYPE) {
             trap_SendServerCommand(ent - g_entities, "print \"Invalid gametype.\n\"");
             return;
         }
         Com_sprintf(level.voteString, sizeof(level.voteString), "%s %d", arg1, i);
         Com_sprintf(level.voteDisplayString, sizeof(level.voteDisplayString), "%s %s", arg1, gameNames[i]);
     } else if (!Q_stricmp(arg1, "map")) {
         // special case for map changes, we want to reset the nextmap setting
         // this allows a player to change maps, but not upset the map rotation
         char    s[MAX_STRING_CHARS];
         trap_Cvar_VariableStringBuffer("nextmap", s, sizeof(s));
         if (*s) {
             Com_sprintf(level.voteString, sizeof(level.voteString), "%s %s; set nextmap \"%s\"", arg1, arg2, s);
         } else {
             Com_sprintf(level.voteString, sizeof(level.voteString), "%s %s", arg1, arg2);
         }
         Com_sprintf(level.voteDisplayString, sizeof(level.voteDisplayString), "%s", level.voteString);
     } else if (!Q_stricmp(arg1, "nextmap")) {
         char    s[MAX_STRING_CHARS];
         trap_Cvar_VariableStringBuffer("nextmap", s, sizeof(s));
         if (!*s) {
             trap_SendServerCommand(ent - g_entities, "print \"nextmap not set.\n\"");
             return;
         }
         Com_sprintf(level.voteString, sizeof(level.voteString), "vstr nextmap");
         Com_sprintf(level.voteDisplayString, sizeof(level.voteDisplayString), "%s", level.voteString);
     } else if (!Q_stricmp(arg1, "clientkick") || !Q_stricmp(arg1, "kick")) {
         i = ClientNumberFromString(ent, arg2, !Q_stricmp(arg1, "clientkick"), !Q_stricmp(arg1, "kick"));
         if (i == -1) {
             return;
         }
         if (level.clients[i].pers.localClient) {
             trap_SendServerCommand(ent - g_entities, "print \"Cannot kick host player.\n\"");
             return;
         }
         Com_sprintf(level.voteString, sizeof(level.voteString), "clientkick %d", i);
         Com_sprintf(level.voteDisplayString, sizeof(level.voteDisplayString), "kick %s", level.clients[i].pers.netname);
     } else {
         Com_sprintf(level.voteString, sizeof(level.voteString), "%s \"%s\"", arg1, arg2);
         Com_sprintf(level.voteDisplayString, sizeof(level.voteDisplayString), "%s", level.voteString);
     }
     trap_SendServerCommand(-1, va("print \"%s called a vote.\n\"", ent->client->pers.netname));
     // start the voting, the caller automatically votes yes
     level.voteTime = level.time;
     level.voteYes = 1;
     level.voteNo = 0;
     for (i = 0; i < level.maxclients; i++) {
         level.clients[i].ps.eFlags &= ~EF_VOTED;
     }
     ent->client->ps.eFlags |= EF_VOTED;
     trap_SetConfigstring(CS_VOTE_TIME, va("%i", level.voteTime));
     trap_SetConfigstring(CS_VOTE_STRING, level.voteDisplayString);
     trap_SetConfigstring(CS_VOTE_YES, va("%i", level.voteYes));
     trap_SetConfigstring(CS_VOTE_NO, va("%i", level.voteNo));
 }
References gentity_s::client, ClientNumberFromString(), level_locals_t::clients, Com_sprintf(), CS_VOTE_NO, CS_VOTE_STRING, CS_VOTE_TIME, CS_VOTE_YES, EF_VOTED, playerState_s::eFlags, EXEC_APPEND, g_allowVote, g_entities, gameNames, GT_MAX_GAME_TYPE, GT_SINGLE_PLAYER, vmCvar_t::integer, level, clientPersistant_t::localClient, MAX_STRING_CHARS, MAX_STRING_TOKENS, MAX_VOTE_COUNT, level_locals_t::maxclients, clientPersistant_t::netname, gclient_s::pers, gclient_s::ps, Q_stricmp(), Q_stricmpn(), s, gclient_s::sess, clientSession_t::sessionTeam, TEAM_SPECTATOR, level_locals_t::time, trap_Argv(), trap_Cvar_VariableStringBuffer(), trap_SendConsoleCommand(), trap_SendServerCommand(), trap_SetConfigstring(), va(), clientPersistant_t::voteCount, level_locals_t::voteDisplayString, level_locals_t::voteExecuteTime, level_locals_t::voteNo, level_locals_t::voteString, level_locals_t::voteTime, and level_locals_t::voteYes.
Referenced by ClientCommand().
Cmd_Follow_f()
void Cmd_Follow_f (gentity_t * ent)
Definition at line 735 of file g_cmds.c.
 {
     int        i;
     char    arg[MAX_TOKEN_CHARS];
     if (trap_Argc() != 2) {
         if (ent->client->sess.spectatorState == SPECTATOR_FOLLOW) {
             StopFollowing(ent);
         }
         return;
     }
     trap_Argv(1, arg, sizeof(arg));
     i = ClientNumberFromString(ent, arg, qtrue, qtrue);
     if (i == -1) {
         return;
     }
     // can't follow self
     if (&level.clients[i] == ent->client) {
         return;
     }
     // can't follow another spectator
     if (level.clients[i].sess.sessionTeam == TEAM_SPECTATOR) {
         return;
     }
     // if they are playing a tournement game, count as a loss
     if ((g_gametype.integer == GT_TOURNAMENT)
         && ent->client->sess.sessionTeam == TEAM_FREE) {
         ent->client->sess.losses++;
     }
     // first set them to spectator
     if (ent->client->sess.sessionTeam != TEAM_SPECTATOR) {
         SetTeam(ent, "spectator");
     }
     ent->client->sess.spectatorState = SPECTATOR_FOLLOW;
     ent->client->sess.spectatorClient = i;
 }
References gentity_s::client, ClientNumberFromString(), level_locals_t::clients, g_gametype, GT_TOURNAMENT, level, clientSession_t::losses, MAX_TOKEN_CHARS, qtrue, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), SPECTATOR_FOLLOW, clientSession_t::spectatorClient, clientSession_t::spectatorState, StopFollowing(), TEAM_FREE, TEAM_SPECTATOR, trap_Argc(), and trap_Argv().
Referenced by ClientCommand().
Cmd_FollowCycle_f()
void Cmd_FollowCycle_f (gentity_t * ent, int dir)
Definition at line 783 of file g_cmds.c.
 {
     int        clientnum;
     int        original;
     // if they are playing a tournement game, count as a loss
     if ((g_gametype.integer == GT_TOURNAMENT)
         && ent->client->sess.sessionTeam == TEAM_FREE) {
         ent->client->sess.losses++;
     }
     // first set them to spectator
     if (ent->client->sess.spectatorState == SPECTATOR_NOT) {
         SetTeam(ent, "spectator");
     }
     if (dir != 1 && dir != -1) {
         G_Error("Cmd_FollowCycle_f: bad dir %i", dir);
     }
     // if dedicated follow client, just switch between the two auto clients
     if (ent->client->sess.spectatorClient < 0) {
         if (ent->client->sess.spectatorClient == -1) {
             ent->client->sess.spectatorClient = -2;
         } else if (ent->client->sess.spectatorClient == -2) {
             ent->client->sess.spectatorClient = -1;
         }
         return;
     }
     clientnum = ent->client->sess.spectatorClient;
     original = clientnum;
     do {
         clientnum += dir;
         if (clientnum >= level.maxclients) {
             clientnum = 0;
         }
         if (clientnum < 0) {
             clientnum = level.maxclients - 1;
         }
         // can only follow connected clients
         if (level.clients[clientnum].pers.connected != CON_CONNECTED) {
             continue;
         }
         // can't follow another spectator
         if (level.clients[clientnum].sess.sessionTeam == TEAM_SPECTATOR) {
             continue;
         }
         // this is good, we can use it
         ent->client->sess.spectatorClient = clientnum;
         ent->client->sess.spectatorState = SPECTATOR_FOLLOW;
         return;
     } while (clientnum != original);
     // leave it where it was
 }
References gentity_s::client, level_locals_t::clients, CON_CONNECTED, clientPersistant_t::connected, G_Error(), g_gametype, GT_TOURNAMENT, level, clientSession_t::losses, level_locals_t::maxclients, gclient_s::pers, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), SPECTATOR_FOLLOW, SPECTATOR_NOT, clientSession_t::spectatorClient, clientSession_t::spectatorState, TEAM_FREE, and TEAM_SPECTATOR.
Referenced by ClientCommand(), and SpectatorThink().
Cmd_GameCommand_f()
void Cmd_GameCommand_f (gentity_t * ent)
Definition at line 1236 of file g_cmds.c.
 {
     int            targetNum;
     gentity_t* target;
     int            order;
     char        arg[MAX_TOKEN_CHARS];
     if (trap_Argc() != 3) {
         trap_SendServerCommand(ent - g_entities, va("print \"Usage: gc <player id> <order 0-%d>\n\"", numgc_orders - 1));
         return;
     }
     trap_Argv(2, arg, sizeof(arg));
     order = atoi(arg);
     if (order < 0 || order >= numgc_orders) {
         trap_SendServerCommand(ent - g_entities, va("print \"Bad order: %i\n\"", order));
         return;
     }
     trap_Argv(1, arg, sizeof(arg));
     targetNum = ClientNumberFromString(ent, arg, qtrue, qtrue);
     if (targetNum == -1) {
         return;
     }
     target = &g_entities[targetNum];
     if (!target->inuse || !target->client) {
         return;
     }
     G_LogPrintf("tell: %s to %s: %s\n", ent->client->pers.netname, target->client->pers.netname, gc_orders[order]);
     G_Say(ent, target, SAY_TELL, gc_orders[order]);
     // don't tell to the player self if it was already directed to this player
     // also don't send the chat back to a bot
     if (ent != target && !(ent->r.svFlags & SVF_BOT)) {
         G_Say(ent, ent, SAY_TELL, gc_orders[order]);
     }
 }
References gentity_s::client, ClientNumberFromString(), g_entities, G_LogPrintf(), G_Say(), gc_orders, gentity_s::inuse, MAX_TOKEN_CHARS, clientPersistant_t::netname, numgc_orders, gclient_s::pers, qtrue, gentity_s::r, SAY_TELL, SVF_BOT, entityShared_t::svFlags, trap_Argc(), trap_Argv(), trap_SendServerCommand(), and va().
Referenced by ClientCommand().
Cmd_Give_f()
void Cmd_Give_f (gentity_t * ent)
Definition at line 243 of file g_cmds.c.
 {
     char* name;
     gitem_t* it;
     int            i;
     qboolean    give_all;
     gentity_t* it_ent;
     trace_t        trace;
     if (!CheatsOk(ent)) {
         return;
     }
     name = ConcatArgs(1);
     if (Q_stricmp(name, "all") == 0)
         give_all = qtrue;
     else
         give_all = qfalse;
     if (give_all || Q_stricmp(name, "health") == 0) {
         ent->health = ent->client->ps.stats[STAT_MAX_HEALTH];
         if (!give_all)
             return;
     }
     if (give_all || Q_stricmp(name, "weapons") == 0) {
         ent->client->ps.stats[STAT_WEAPONS] = (1 << WP_NUM_WEAPONS) - 1 -
             (1 << WP_GRAPPLING_HOOK) - (1 << WP_NONE);
         if (!give_all)
             return;
     }
     if (give_all || Q_stricmp(name, "ammo") == 0) {
         for (i = 0; i < MAX_WEAPONS; i++) {
             ent->client->ps.ammo[i] = 999;
         }
         if (!give_all)
             return;
     }
     if (give_all || Q_stricmp(name, "armor") == 0) {
         ent->client->ps.stats[STAT_ARMOR] = 200;
         if (!give_all)
             return;
     }
     if (Q_stricmp(name, "excellent") == 0) {
         ent->client->ps.persistant[PERS_EXCELLENT_COUNT]++;
         return;
     }
     if (Q_stricmp(name, "impressive") == 0) {
         ent->client->ps.persistant[PERS_IMPRESSIVE_COUNT]++;
         return;
     }
     if (Q_stricmp(name, "gauntletaward") == 0) {
         ent->client->ps.persistant[PERS_GAUNTLET_FRAG_COUNT]++;
         return;
     }
     if (Q_stricmp(name, "defend") == 0) {
         ent->client->ps.persistant[PERS_DEFEND_COUNT]++;
         return;
     }
     if (Q_stricmp(name, "assist") == 0) {
         ent->client->ps.persistant[PERS_ASSIST_COUNT]++;
         return;
     }
     // spawn a specific item right on the player
     if (!give_all) {
         it = BG_FindItem(name);
         if (!it) {
             return;
         }
         it_ent = G_Spawn();
         VectorCopy(ent->r.currentOrigin, it_ent->s.origin);
         it_ent->classname = it->classname;
         G_SpawnItem(it_ent, it);
         FinishSpawningItem(it_ent);
         memset(&trace, 0, sizeof(trace));
         Touch_Item(it_ent, ent, &trace);
         if (it_ent->inuse) {
             G_FreeEntity(it_ent);
         }
     }
 }
References playerState_s::ammo, BG_FindItem(), CheatsOk(), gentity_s::classname, gitem_s::classname, gentity_s::client, ConcatArgs(), entityShared_t::currentOrigin, FinishSpawningItem(), G_FreeEntity(), G_Spawn(), G_SpawnItem(), gentity_s::health, gentity_s::inuse, MAX_WEAPONS, entityState_s::origin, PERS_ASSIST_COUNT, PERS_DEFEND_COUNT, PERS_EXCELLENT_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_IMPRESSIVE_COUNT, playerState_s::persistant, gclient_s::ps, Q_stricmp(), qfalse, qtrue, gentity_s::r, gentity_s::s, STAT_ARMOR, STAT_MAX_HEALTH, STAT_WEAPONS, playerState_s::stats, Touch_Item(), VectorCopy, WP_GRAPPLING_HOOK, WP_NONE, and WP_NUM_WEAPONS.
Referenced by ClientCommand().
Cmd_God_f()
void Cmd_God_f (gentity_t * ent)
Definition at line 342 of file g_cmds.c.
 {
     char* msg;
     if (!CheatsOk(ent)) {
         return;
     }
     ent->flags ^= FL_GODMODE;
     if (!(ent->flags & FL_GODMODE))
         msg = "godmode OFF\n";
     else
         msg = "godmode ON\n";
     trap_SendServerCommand(ent - g_entities, va("print \"%s\"", msg));
 }
References CheatsOk(), FL_GODMODE, gentity_s::flags, g_entities, trap_SendServerCommand(), and va().
Referenced by ClientCommand().
Cmd_Kill_f()
void Cmd_Kill_f (gentity_t * ent)
Definition at line 476 of file g_cmds.c.
 {
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         return;
     }
     if (ent->health <= 0) {
         return;
     }
     ent->flags &= ~FL_GODMODE;
     ent->client->ps.stats[STAT_HEALTH] = ent->health = -999;
     player_die(ent, ent, ent, 100000, MOD_SUICIDE);
 }
References gentity_s::client, FL_GODMODE, gentity_s::flags, gentity_s::health, MOD_SUICIDE, player_die(), gclient_s::ps, gclient_s::sess, clientSession_t::sessionTeam, STAT_HEALTH, playerState_s::stats, and TEAM_SPECTATOR.
Referenced by ClientCommand().
Cmd_LevelShot_f()
void Cmd_LevelShot_f (gentity_t * ent)
Definition at line 423 of file g_cmds.c.
 {
     if (!ent->client->pers.localClient) {
         trap_SendServerCommand(ent - g_entities,
             "print \"The levelshot command must be executed by a local client\n\"");
         return;
     }
     if (!CheatsOk(ent))
         return;
     // doesn't work in single player
     if (g_gametype.integer == GT_SINGLE_PLAYER) {
         trap_SendServerCommand(ent - g_entities,
             "print \"Must not be in singleplayer mode for levelshot\n\"");
         return;
     }
     BeginIntermission();
     trap_SendServerCommand(ent - g_entities, "clientLevelShot");
 }
References BeginIntermission(), CheatsOk(), gentity_s::client, g_entities, g_gametype, GT_SINGLE_PLAYER, clientPersistant_t::localClient, gclient_s::pers, and trap_SendServerCommand().
Referenced by ClientCommand().
Cmd_Noclip_f()
void Cmd_Noclip_f (gentity_t * ent)
Definition at line 394 of file g_cmds.c.
 {
     char* msg;
     if (!CheatsOk(ent)) {
         return;
     }
     if (ent->client->noclip) {
         msg = "noclip OFF\n";
     } else {
         msg = "noclip ON\n";
     }
     ent->client->noclip = !ent->client->noclip;
     trap_SendServerCommand(ent - g_entities, va("print \"%s\"", msg));
 }
References CheatsOk(), gentity_s::client, g_entities, gclient_s::noclip, trap_SendServerCommand(), and va().
Referenced by ClientCommand().
Cmd_Notarget_f()
void Cmd_Notarget_f (gentity_t * ent)
Definition at line 369 of file g_cmds.c.
 {
     char* msg;
     if (!CheatsOk(ent)) {
         return;
     }
     ent->flags ^= FL_NOTARGET;
     if (!(ent->flags & FL_NOTARGET))
         msg = "notarget OFF\n";
     else
         msg = "notarget ON\n";
     trap_SendServerCommand(ent - g_entities, va("print \"%s\"", msg));
 }
References CheatsOk(), FL_NOTARGET, gentity_s::flags, g_entities, trap_SendServerCommand(), and va().
Referenced by ClientCommand().
Cmd_Say_f()
static void Cmd_Say_f (gentity_t * ent, int mode, qboolean arg0) static
Definition at line 958 of file g_cmds.c.
 {
     char* p;
     if (trap_Argc() < 2 && !arg0) {
         return;
     }
     if (arg0) {
         p = ConcatArgs(0);
     } else {
         p = ConcatArgs(1);
     }
     SanitizeChatText(p);
     G_Say(ent, NULL, mode, p);
 }
References ConcatArgs(), G_Say(), NULL, SanitizeChatText(), and trap_Argc().
Referenced by ClientCommand().
Cmd_Score_f()
void Cmd_Score_f (gentity_t * ent)
Definition at line 105 of file g_cmds.c.
 {
     DeathmatchScoreboardMessage(ent);
 }
References DeathmatchScoreboardMessage().
Referenced by ClientCommand(), and player_die().
Cmd_SetViewpos_f()
void Cmd_SetViewpos_f (gentity_t * ent)
Definition at line 1668 of file g_cmds.c.
 {
     vec3_t        origin, angles;
     char        buffer[MAX_TOKEN_CHARS];
     int            i;
     if (!g_cheats.integer) {
         trap_SendServerCommand(ent - g_entities, "print \"Cheats are not enabled on this server.\n\"");
         return;
     }
     if (trap_Argc() != 5) {
         trap_SendServerCommand(ent - g_entities, "print \"usage: setviewpos x y z yaw\n\"");
         return;
     }
     VectorClear(angles);
     for (i = 0; i < 3; i++) {
         trap_Argv(i + 1, buffer, sizeof(buffer));
         origin[i] = atof(buffer);
     }
     trap_Argv(4, buffer, sizeof(buffer));
     angles[YAW] = atof(buffer);
     TeleportPlayer(ent, origin, angles);
 }
References buffer, g_cheats, g_entities, vmCvar_t::integer, MAX_TOKEN_CHARS, TeleportPlayer(), trap_Argc(), trap_Argv(), trap_SendServerCommand(), VectorClear, and YAW.
Referenced by ClientCommand().
Cmd_Stats_f()
void Cmd_Stats_f (gentity_t * ent)
Definition at line 1702 of file g_cmds.c.
 {
     /*
         int max, n, i;
         max = trap_AAS_PointReachabilityAreaIndex( NULL );
         n = 0;
         for ( i = 0; i < max; i++ ) {
             if ( ent->client->areabits[i >> 3] & (1 << (i & 7)) )
                 n++;
         }
         //trap_SendServerCommand( ent-g_entities, va("print \"visited %d of %d areas\n\"", n, max));
         trap_SendServerCommand( ent-g_entities, va("print \"%d%% level coverage\n\"", n * 100 / max));
     */
 }
Referenced by ClientCommand().
Cmd_Team_f()
void Cmd_Team_f (gentity_t * ent)
Definition at line 687 of file g_cmds.c.
 {
     int            oldTeam;
     char        s[MAX_TOKEN_CHARS];
     if (trap_Argc() != 2) {
         oldTeam = ent->client->sess.sessionTeam;
         switch (oldTeam) {
         case TEAM_BLUE:
             trap_SendServerCommand(ent - g_entities, "print \"Blue team\n\"");
             break;
         case TEAM_RED:
             trap_SendServerCommand(ent - g_entities, "print \"Red team\n\"");
             break;
         case TEAM_FREE:
             trap_SendServerCommand(ent - g_entities, "print \"Free team\n\"");
             break;
         case TEAM_SPECTATOR:
             trap_SendServerCommand(ent - g_entities, "print \"Spectator team\n\"");
             break;
         }
         return;
     }
     if (ent->client->switchTeamTime > level.time) {
         trap_SendServerCommand(ent - g_entities, "print \"May not switch teams more than once per 5 seconds.\n\"");
         return;
     }
     // if they are playing a tournement game, count as a loss
     if ((g_gametype.integer == GT_TOURNAMENT)
         && ent->client->sess.sessionTeam == TEAM_FREE) {
         ent->client->sess.losses++;
     }
     trap_Argv(1, s, sizeof(s));
     SetTeam(ent, s);
     ent->client->switchTeamTime = level.time + 5000;
 }
References gentity_s::client, g_entities, g_gametype, GT_TOURNAMENT, level, clientSession_t::losses, MAX_TOKEN_CHARS, s, gclient_s::sess, clientSession_t::sessionTeam, SetTeam(), gclient_s::switchTeamTime, TEAM_BLUE, TEAM_FREE, TEAM_RED, TEAM_SPECTATOR, level_locals_t::time, trap_Argc(), trap_Argv(), and trap_SendServerCommand().
Referenced by ClientCommand().
Cmd_TeamTask_f()
void Cmd_TeamTask_f (gentity_t * ent)
Definition at line 451 of file g_cmds.c.
 {
     char userinfo[MAX_INFO_STRING];
     char        arg[MAX_TOKEN_CHARS];
     int task;
     int client = ent->client - level.clients;
     if (trap_Argc() != 2) {
         return;
     }
     trap_Argv(1, arg, sizeof(arg));
     task = atoi(arg);
     trap_GetUserinfo(client, userinfo, sizeof(userinfo));
     Info_SetValueForKey(userinfo, "teamtask", va("%d", task));
     trap_SetUserinfo(client, userinfo);
     ClientUserinfoChanged(client);
 }
References gentity_s::client, level_locals_t::clients, ClientUserinfoChanged(), Info_SetValueForKey(), level, MAX_INFO_STRING, MAX_TOKEN_CHARS, trap_Argc(), trap_Argv(), trap_GetUserinfo(), trap_SetUserinfo(), and va().
Referenced by ClientCommand().
Cmd_TeamVote_f()
void Cmd_TeamVote_f (gentity_t * ent)
Definition at line 1618 of file g_cmds.c.
 {
     int            team, cs_offset;
     char        msg[64];
     team = ent->client->sess.sessionTeam;
     if (team == TEAM_RED)
         cs_offset = 0;
     else if (team == TEAM_BLUE)
         cs_offset = 1;
     else
         return;
     if (!level.teamVoteTime[cs_offset]) {
         trap_SendServerCommand(ent - g_entities, "print \"No team vote in progress.\n\"");
         return;
     }
     if (ent->client->ps.eFlags & EF_TEAMVOTED) {
         trap_SendServerCommand(ent - g_entities, "print \"Team vote already cast.\n\"");
         return;
     }
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         trap_SendServerCommand(ent - g_entities, "print \"Not allowed to vote as spectator.\n\"");
         return;
     }
     trap_SendServerCommand(ent - g_entities, "print \"Team vote cast.\n\"");
     ent->client->ps.eFlags |= EF_TEAMVOTED;
     trap_Argv(1, msg, sizeof(msg));
     if (tolower(msg[0]) == 'y' || msg[0] == '1') {
         level.teamVoteYes[cs_offset]++;
         trap_SetConfigstring(CS_TEAMVOTE_YES + cs_offset, va("%i", level.teamVoteYes[cs_offset]));
     } else {
         level.teamVoteNo[cs_offset]++;
         trap_SetConfigstring(CS_TEAMVOTE_NO + cs_offset, va("%i", level.teamVoteNo[cs_offset]));
     }
     // a majority will be determined in TeamCheckVote, which will also account
     // for players entering or leaving
 }
References gentity_s::client, CS_TEAMVOTE_NO, CS_TEAMVOTE_YES, EF_TEAMVOTED, playerState_s::eFlags, g_entities, level, gclient_s::ps, gclient_s::sess, clientSession_t::sessionTeam, TEAM_BLUE, TEAM_RED, TEAM_SPECTATOR, level_locals_t::teamVoteNo, level_locals_t::teamVoteTime, level_locals_t::teamVoteYes, trap_Argv(), trap_SendServerCommand(), trap_SetConfigstring(), and va().
Referenced by ClientCommand().
Cmd_Tell_f()
static void Cmd_Tell_f (gentity_t * ent) static
Definition at line 982 of file g_cmds.c.
 {
     int            targetNum;
     gentity_t* target;
     char* p;
     char        arg[MAX_TOKEN_CHARS];
     if (trap_Argc() < 3) {
         trap_SendServerCommand(ent - g_entities, "print \"Usage: tell <player id> <message>\n\"");
         return;
     }
     trap_Argv(1, arg, sizeof(arg));
     targetNum = ClientNumberFromString(ent, arg, qtrue, qtrue);
     if (targetNum == -1) {
         return;
     }
     target = &g_entities[targetNum];
     if (!target->inuse || !target->client) {
         return;
     }
     p = ConcatArgs(2);
     SanitizeChatText(p);
     G_LogPrintf("tell: %s to %s: %s\n", ent->client->pers.netname, target->client->pers.netname, p);
     G_Say(ent, target, SAY_TELL, p);
     // don't tell to the player self if it was already directed to this player
     // also don't send the chat back to a bot
     if (ent != target && !(ent->r.svFlags & SVF_BOT)) {
         G_Say(ent, ent, SAY_TELL, p);
     }
 }
References gentity_s::client, ClientNumberFromString(), ConcatArgs(), g_entities, G_LogPrintf(), G_Say(), gentity_s::inuse, MAX_TOKEN_CHARS, clientPersistant_t::netname, gclient_s::pers, qtrue, gentity_s::r, SanitizeChatText(), SAY_TELL, SVF_BOT, entityShared_t::svFlags, trap_Argc(), trap_Argv(), and trap_SendServerCommand().
Referenced by ClientCommand().
Cmd_Vote_f()
void Cmd_Vote_f (gentity_t * ent)
Definition at line 1444 of file g_cmds.c.
 {
     char        msg[64];
     if (!level.voteTime) {
         trap_SendServerCommand(ent - g_entities, "print \"No vote in progress.\n\"");
         return;
     }
     if (ent->client->ps.eFlags & EF_VOTED) {
         trap_SendServerCommand(ent - g_entities, "print \"Vote already cast.\n\"");
         return;
     }
     if (ent->client->sess.sessionTeam == TEAM_SPECTATOR) {
         trap_SendServerCommand(ent - g_entities, "print \"Not allowed to vote as spectator.\n\"");
         return;
     }
     trap_SendServerCommand(ent - g_entities, "print \"Vote cast.\n\"");
     ent->client->ps.eFlags |= EF_VOTED;
     trap_Argv(1, msg, sizeof(msg));
     if (tolower(msg[0]) == 'y' || msg[0] == '1') {
         level.voteYes++;
         trap_SetConfigstring(CS_VOTE_YES, va("%i", level.voteYes));
     } else {
         level.voteNo++;
         trap_SetConfigstring(CS_VOTE_NO, va("%i", level.voteNo));
     }
     // a majority will be determined in CheckVote, which will also account
     // for players entering or leaving
 }
References gentity_s::client, CS_VOTE_NO, CS_VOTE_YES, EF_VOTED, playerState_s::eFlags, g_entities, level, gclient_s::ps, gclient_s::sess, clientSession_t::sessionTeam, TEAM_SPECTATOR, trap_Argv(), trap_SendServerCommand(), trap_SetConfigstring(), va(), level_locals_t::voteNo, level_locals_t::voteTime, and level_locals_t::voteYes.
Referenced by ClientCommand().
Cmd_Where_f()
void Cmd_Where_f (gentity_t * ent)
Definition at line 1281 of file g_cmds.c.
 {
     trap_SendServerCommand(ent - g_entities, va("print \"%s\n\"", vtos(ent->r.currentOrigin)));
 }
References entityShared_t::currentOrigin, g_entities, gentity_s::r, trap_SendServerCommand(), va(), and vtos().
Referenced by ClientCommand().
ConcatArgs()
char* ConcatArgs (int start)
Definition at line 136 of file g_cmds.c.
 {
     int        i, c, tlen;
     static char    line[MAX_STRING_CHARS];
     int        len;
     char    arg[MAX_STRING_CHARS];
     len = 0;
     c = trap_Argc();
     for (i = start; i < c; i++) {
         trap_Argv(i, arg, sizeof(arg));
         tlen = strlen(arg);
         if (len + tlen >= MAX_STRING_CHARS - 1) {
             break;
         }
         memcpy(line + len, arg, tlen);
         len += tlen;
         if (i != c - 1) {
             line[len] = ' ';
             len++;
         }
     }
     line[len] = 0;
     return line;
 }
References MAX_STRING_CHARS, trap_Argc(), and trap_Argv().
Referenced by Cmd_Give_f(), Cmd_Say_f(), Cmd_Tell_f(), and ConsoleCommand().
DeathmatchScoreboardMessage()
void DeathmatchScoreboardMessage (gentity_t * ent)
Definition at line 35 of file g_cmds.c.
 {
     char        entry[1024];
     char        string[1000];
     int            stringlength;
     int            i, j;
     gclient_t* cl;
     int            numSorted, scoreFlags, accuracy, perfect;
     // don't send scores to bots, they don't parse it
     if (ent->r.svFlags & SVF_BOT) {
         return;
     }
     // send the latest information on all clients
     string[0] = 0;
     stringlength = 0;
     scoreFlags = 0;
     numSorted = level.numConnectedClients;
     for (i = 0; i < numSorted; i++) {
         int        ping;
         cl = &level.clients[level.sortedClients[i]];
         if (cl->pers.connected == CON_CONNECTING) {
             ping = -1;
         } else {
             ping = cl->ps.ping < 999 ? cl->ps.ping : 999;
         }
         if (cl->accuracy_shots) {
             accuracy = cl->accuracy_hits * 100 / cl->accuracy_shots;
         } else {
             accuracy = 0;
         }
         perfect = (cl->ps.persistant[PERS_RANK] == 0 && cl->ps.persistant[PERS_KILLED] == 0) ? 1 : 0;
         Com_sprintf(entry, sizeof(entry),
             " %i %i %i %i %i %i %i %i %i %i %i %i %i %i", level.sortedClients[i],
             cl->ps.persistant[PERS_SCORE], ping, (level.time - cl->pers.enterTime) / 60000,
             scoreFlags, g_entities[level.sortedClients[i]].s.powerups, accuracy,
             cl->ps.persistant[PERS_IMPRESSIVE_COUNT],
             cl->ps.persistant[PERS_EXCELLENT_COUNT],
             cl->ps.persistant[PERS_GAUNTLET_FRAG_COUNT],
             cl->ps.persistant[PERS_DEFEND_COUNT],
             cl->ps.persistant[PERS_ASSIST_COUNT],
             perfect,
             cl->ps.persistant[PERS_CAPTURES]);
         j = strlen(entry);
         if (stringlength + j >= sizeof(string))
             break;
         strcpy(string + stringlength, entry);
         stringlength += j;
     }
     trap_SendServerCommand(ent - g_entities, va("scores %i %i %i%s", i,
         level.teamScores[TEAM_RED], level.teamScores[TEAM_BLUE],
         string));
 }
References cl, level_locals_t::clients, Com_sprintf(), CON_CONNECTING, g_entities, level, level_locals_t::numConnectedClients, PERS_ASSIST_COUNT, PERS_CAPTURES, PERS_DEFEND_COUNT, PERS_EXCELLENT_COUNT, PERS_GAUNTLET_FRAG_COUNT, PERS_IMPRESSIVE_COUNT, PERS_KILLED, PERS_RANK, PERS_SCORE, entityState_s::powerups, gentity_s::r, gentity_s::s, level_locals_t::sortedClients, SVF_BOT, entityShared_t::svFlags, TEAM_BLUE, TEAM_RED, level_locals_t::teamScores, level_locals_t::time, trap_SendServerCommand(), and va().
Referenced by Cmd_Score_f(), G_RankRunFrame(), and SendScoreboardMessageToAllClients().
G_Say()
void G_Say (gentity_t * ent, gentity_t * target, int mode, const char * chatText)
Definition at line 880 of file g_cmds.c.
 {
     int            j;
     gentity_t* other;
     int            color;
     char        name[64];
     // don't let text be too long for malicious reasons
     char        text[MAX_SAY_TEXT];
     char        location[64];
     if (g_gametype.integer < GT_TEAM && mode == SAY_TEAM) {
         mode = SAY_ALL;
     }
     switch (mode) {
     default:
     case SAY_ALL:
         G_LogPrintf("say: %s: %s\n", ent->client->pers.netname, chatText);
         Com_sprintf(name, sizeof(name), "%s%c%c"EC": ", ent->client->pers.netname, Q_COLOR_ESCAPE, COLOR_WHITE);
         color = COLOR_GREEN;
         break;
     case SAY_TEAM:
         G_LogPrintf("sayteam: %s: %s\n", ent->client->pers.netname, chatText);
         if (Team_GetLocationMsg(ent, location, sizeof(location)))
             Com_sprintf(name, sizeof(name), EC"(%s%c%c"EC") (%s)"EC": ",
                 ent->client->pers.netname, Q_COLOR_ESCAPE, COLOR_WHITE, location);
         else
             Com_sprintf(name, sizeof(name), EC"(%s%c%c"EC")"EC": ",
                 ent->client->pers.netname, Q_COLOR_ESCAPE, COLOR_WHITE);
         color = COLOR_CYAN;
         break;
     case SAY_TELL:
         if (target && target->inuse && target->client && g_gametype.integer >= GT_TEAM &&
             target->client->sess.sessionTeam == ent->client->sess.sessionTeam &&
             Team_GetLocationMsg(ent, location, sizeof(location)))
             Com_sprintf(name, sizeof(name), EC"[%s%c%c"EC"] (%s)"EC": ", ent->client->pers.netname, Q_COLOR_ESCAPE, COLOR_WHITE, location);
         else
             Com_sprintf(name, sizeof(name), EC"[%s%c%c"EC"]"EC": ", ent->client->pers.netname, Q_COLOR_ESCAPE, COLOR_WHITE);
         color = COLOR_MAGENTA;
         break;
     }
     Q_strncpyz(text, chatText, sizeof(text));
     if (target) {
         G_SayTo(ent, target, mode, color, name, text);
         return;
     }
     // echo the text to the console
     if (g_dedicated.integer) {
         G_Printf("%s%s\n", name, text);
     }
     // send it to all the appropriate clients
     for (j = 0; j < level.maxclients; j++) {
         other = &g_entities[j];
         G_SayTo(ent, other, mode, color, name, text);
     }
 }
References gentity_s::client, COLOR_CYAN, COLOR_GREEN, COLOR_MAGENTA, COLOR_WHITE, Com_sprintf(), EC, g_dedicated, g_entities, g_gametype, G_LogPrintf(), G_Printf(), G_SayTo(), GT_TEAM, vmCvar_t::integer, gentity_s::inuse, level, MAX_SAY_TEXT, level_locals_t::maxclients, clientPersistant_t::netname, gclient_s::pers, Q_COLOR_ESCAPE, Q_strncpyz(), SAY_ALL, SAY_TEAM, SAY_TELL, gclient_s::sess, clientSession_t::sessionTeam, and Team_GetLocationMsg().
Referenced by Cmd_GameCommand_f(), Cmd_Say_f(), and Cmd_Tell_f().
G_SayTo()
static void G_SayTo (gentity_t * ent, gentity_t * other, int mode, int color, const char * name, const char * message) static
Definition at line 849 of file g_cmds.c.
 {
     if (!other) {
         return;
     }
     if (!other->inuse) {
         return;
     }
     if (!other->client) {
         return;
     }
     if (other->client->pers.connected != CON_CONNECTED) {
         return;
     }
     if (mode == SAY_TEAM && !OnSameTeam(ent, other)) {
         return;
     }
     // no chatting to players in tournements
     if ((g_gametype.integer == GT_TOURNAMENT)
         && other->client->sess.sessionTeam == TEAM_FREE
         && ent->client->sess.sessionTeam != TEAM_FREE) {
         return;
     }
     trap_SendServerCommand(other - g_entities, va("%s \"%s%c%c%s\"",
         mode == SAY_TEAM ? "tchat" : "chat",
         name, Q_COLOR_ESCAPE, color, message));
 }
References gentity_s::client, CON_CONNECTED, clientPersistant_t::connected, g_entities, g_gametype, GT_TOURNAMENT, gentity_s::inuse, OnSameTeam(), gclient_s::pers, Q_COLOR_ESCAPE, SAY_TEAM, gclient_s::sess, clientSession_t::sessionTeam, TEAM_FREE, trap_SendServerCommand(), and va().
Referenced by G_Say().
SanitizeChatText()
static void SanitizeChatText (char * text) static
Definition at line 941 of file g_cmds.c.
 {
     int i;
     for (i = 0; text[i]; i++) {
         if (text[i] == '\n' || text[i] == '\r') {
             text[i] = ' ';
         }
     }
 }
Referenced by Cmd_Say_f(), and Cmd_Tell_f().
SetTeam()
void SetTeam (gentity_t * ent, const char * s)
Definition at line 518 of file g_cmds.c.
 {
     int                    team, oldTeam;
     gclient_t* client;
     int                    clientNum;
     spectatorState_t    specState;
     int                    specClient;
     int                    teamLeader;
     //
     // see what change is requested
     //
     client = ent->client;
     clientNum = client - level.clients;
     specClient = 0;
     specState = SPECTATOR_NOT;
     if (!Q_stricmp(s, "scoreboard") || !Q_stricmp(s, "score")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_SCOREBOARD;
     } else if (!Q_stricmp(s, "follow1")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FOLLOW;
         specClient = -1;
     } else if (!Q_stricmp(s, "follow2")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FOLLOW;
         specClient = -2;
     } else if (!Q_stricmp(s, "spectator") || !Q_stricmp(s, "s")) {
         team = TEAM_SPECTATOR;
         specState = SPECTATOR_FREE;
     } else if (g_gametype.integer >= GT_TEAM) {
         // if running a team game, assign player to one of the teams
         specState = SPECTATOR_NOT;
         if (!Q_stricmp(s, "red") || !Q_stricmp(s, "r")) {
             team = TEAM_RED;
         } else if (!Q_stricmp(s, "blue") || !Q_stricmp(s, "b")) {
             team = TEAM_BLUE;
         } else {
             // pick the team with the least number of players
             team = PickTeam(clientNum);
         }
         if (g_teamForceBalance.integer && !client->pers.localClient && !(ent->r.svFlags & SVF_BOT)) {
             int        counts[TEAM_NUM_TEAMS];
             counts[TEAM_BLUE] = TeamCount(clientNum, TEAM_BLUE);
             counts[TEAM_RED] = TeamCount(clientNum, TEAM_RED);
             // We allow a spread of two
             if (team == TEAM_RED && counts[TEAM_RED] - counts[TEAM_BLUE] > 1) {
                 trap_SendServerCommand(clientNum,
                     "cp \"Red team has too many players.\n\"");
                 return; // ignore the request
             }
             if (team == TEAM_BLUE && counts[TEAM_BLUE] - counts[TEAM_RED] > 1) {
                 trap_SendServerCommand(clientNum,
                     "cp \"Blue team has too many players.\n\"");
                 return; // ignore the request
             }
             // It's ok, the team we are switching to has less or same number of players
         }
     } else {
         // force them to spectators if there aren't any spots free
         team = TEAM_FREE;
     }
     // override decision if limiting the players
     if ((g_gametype.integer == GT_TOURNAMENT)
         && level.numNonSpectatorClients >= 2) {
         team = TEAM_SPECTATOR;
     } else if (g_maxGameClients.integer > 0 &&
         level.numNonSpectatorClients >= g_maxGameClients.integer) {
         team = TEAM_SPECTATOR;
     }
     //
     // decide if we will allow the change
     //
     oldTeam = client->sess.sessionTeam;
     if (team == oldTeam && team != TEAM_SPECTATOR) {
         return;
     }
     //
     // execute the team change
     //
     // if the player was dead leave the body, but only if they're actually in game
     if (client->ps.stats[STAT_HEALTH] <= 0 && client->pers.connected == CON_CONNECTED) {
         CopyToBodyQue(ent);
     }
     // he starts at 'base'
     client->pers.teamState.state = TEAM_BEGIN;
     if (oldTeam != TEAM_SPECTATOR) {
         // Kill him (makes sure he loses flags, etc)
         ent->flags &= ~FL_GODMODE;
         ent->client->ps.stats[STAT_HEALTH] = ent->health = 0;
         player_die(ent, ent, ent, 100000, MOD_SUICIDE);
     }
     // they go to the end of the line for tournements
     if (team == TEAM_SPECTATOR && oldTeam != team)
         AddTournamentQueue(client);
     client->sess.sessionTeam = team;
     client->sess.spectatorState = specState;
     client->sess.spectatorClient = specClient;
     client->sess.teamLeader = qfalse;
     if (team == TEAM_RED || team == TEAM_BLUE) {
         teamLeader = TeamLeader(team);
         // if there is no team leader or the team leader is a bot and this client is not a bot
         if (teamLeader == -1 || (!(g_entities[clientNum].r.svFlags & SVF_BOT) && (g_entities[teamLeader].r.svFlags & SVF_BOT))) {
             SetLeader(team, clientNum);
         }
     }
     // make sure there is a team leader on the team the player came from
     if (oldTeam == TEAM_RED || oldTeam == TEAM_BLUE) {
         CheckTeamLeader(oldTeam);
     }
     // get and distribute relevant parameters
     ClientUserinfoChanged(clientNum);
     // client hasn't spawned yet, they sent an early team command, teampref userinfo, or g_teamAutoJoin is enabled
     if (client->pers.connected != CON_CONNECTED) {
         return;
     }
     BroadcastTeamChange(client, oldTeam);
     ClientBegin(clientNum);
 }
References AddTournamentQueue(), BroadcastTeamChange(), CheckTeamLeader(), gentity_s::client, ClientBegin(), level_locals_t::clients, ClientUserinfoChanged(), CON_CONNECTED, clientPersistant_t::connected, CopyToBodyQue(), FL_GODMODE, gentity_s::flags, g_entities, g_gametype, g_maxGameClients, g_teamForceBalance, GT_TEAM, GT_TOURNAMENT, gentity_s::health, vmCvar_t::integer, level, clientPersistant_t::localClient, MOD_SUICIDE, level_locals_t::numNonSpectatorClients, gclient_s::pers, PickTeam(), player_die(), gclient_s::ps, Q_stricmp(), qfalse, gentity_s::r, s, gclient_s::sess, clientSession_t::sessionTeam, SetLeader(), SPECTATOR_FOLLOW, SPECTATOR_FREE, SPECTATOR_NOT, SPECTATOR_SCOREBOARD, clientSession_t::spectatorClient, clientSession_t::spectatorState, STAT_HEALTH, playerTeamState_t::state, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, TEAM_BEGIN, TEAM_BLUE, TEAM_FREE, TEAM_NUM_TEAMS, TEAM_RED, TEAM_SPECTATOR, TeamCount(), clientSession_t::teamLeader, TeamLeader(), clientPersistant_t::teamState, and trap_SendServerCommand().
Referenced by AddTournamentPlayer(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_Team_f(), G_InitSessionData(), G_RankRunFrame(), RemoveTournamentLoser(), RemoveTournamentWinner(), and Svcmd_ForceTeam_f().
StopFollowing()
void StopFollowing (gentity_t * ent)
Definition at line 665 of file g_cmds.c.
 {
     ent->client->ps.persistant[PERS_TEAM] = TEAM_SPECTATOR;
     ent->client->sess.sessionTeam = TEAM_SPECTATOR;
     ent->client->sess.spectatorState = SPECTATOR_FREE;
     ent->client->ps.pm_flags &= ~PMF_FOLLOW;
     ent->r.svFlags &= ~SVF_BOT;
     ent->client->ps.clientNum = ent - g_entities;
     SetClientViewAngle(ent, ent->client->ps.viewangles);
     // don't use dead view angles
     if (ent->client->ps.stats[STAT_HEALTH] <= 0) {
         ent->client->ps.stats[STAT_HEALTH] = 1;
     }
 }
References gentity_s::client, playerState_s::clientNum, g_entities, PERS_TEAM, playerState_s::persistant, playerState_s::pm_flags, PMF_FOLLOW, gclient_s::ps, gentity_s::r, gclient_s::sess, clientSession_t::sessionTeam, SetClientViewAngle(), SPECTATOR_FREE, clientSession_t::spectatorState, STAT_HEALTH, playerState_s::stats, SVF_BOT, entityShared_t::svFlags, TEAM_SPECTATOR, and playerState_s::viewangles.
Referenced by ClientDisconnect(), Cmd_Follow_f(), and MoveClientToIntermission().
StringIsInteger()
qboolean StringIsInteger (const char * s)
Definition at line 170 of file g_cmds.c.
 {
     int            i;
     int            len;
     qboolean    foundDigit;
     len = strlen(s);
     foundDigit = qfalse;
     for (i = 0; i < len; i++) {
         if (!isdigit(s[i])) {
             return qfalse;
         }
         foundDigit = qtrue;
     }
     return foundDigit;
 }
References qfalse, qtrue, and s.
Referenced by ClientNumberFromString().
Variable Documentation
gameNames
const char* gameNames[] static
Initial value:
= {
    "Free For All",
    "Tournament",
    "Single Player",
    "Team Deathmatch",
    "Capture the Flag",
    "One Flag CTF",
    "Overload",
    "Harvester"
}
Definition at line 1286 of file g_cmds.c.
Referenced by Cmd_CallVote_f().
gc_orders
char* gc_orders[] static
Initial value:
= {
    "hold your position",
    "hold this position",
    "come here",
    "cover me",
    "guard location",
    "search and destroy",
    "report"
}
Definition at line 1224 of file g_cmds.c.
Referenced by Cmd_GameCommand_f().
numgc_orders
const int numgc_orders = ARRAY_LEN(gc_orders) static
Definition at line 1234 of file g_cmds.c.
Referenced by Cmd_GameCommand_f().