ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_reach.h File Reference
be_aas_reach.h File Reference
Functions
int AAS_AreaReachability (int areanum)
int AAS_BestReachableArea (vec3_t origin, vec3_t mins, vec3_t maxs, vec3_t goalorigin)
int AAS_BestReachableFromJumpPadArea (vec3_t origin, vec3_t mins, vec3_t maxs)
int AAS_NextModelReachability (int num, int modelnum)
float AAS_AreaGroundFaceArea (int areanum)
int AAS_AreaCrouch (int areanum)
int AAS_AreaSwim (int areanum)
int AAS_AreaLiquid (int areanum)
int AAS_AreaLava (int areanum)
int AAS_AreaSlime (int areanum)
int AAS_AreaGrounded (int areanum)
int AAS_AreaLadder (int areanum)
int AAS_AreaJumpPad (int areanum)
int AAS_AreaDoNotEnter (int areanum)
Function Documentation
AAS_AreaCrouch()
int AAS_AreaCrouch (int areanum)
Definition at line 656 of file be_aas_reach.c.
 {
     if (!(aasworld.areasettings[areanum].presencetype & PRESENCE_NORMAL)) return qtrue;
     else return qfalse;
 } //end of the function AAS_AreaCrouch
References aasworld, aas_lreachability_s::areanum, aas_s::areasettings, PRESENCE_NORMAL, aas_areasettings_s::presencetype, qfalse, and qtrue.
Referenced by AAS_AreaTravelTime(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Jump(), and AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge().
AAS_AreaDoNotEnter()
int AAS_AreaDoNotEnter (int areanum)
Definition at line 763 of file be_aas_reach.c.
 {
     return (aasworld.areasettings[areanum].contents & AREACONTENTS_DONOTENTER);
 } //end of the function AAS_AreaDoNotEnter
References aasworld, AREACONTENTS_DONOTENTER, aas_lreachability_s::areanum, aas_s::areasettings, and aas_areasettings_s::contents.
Referenced by AAS_AreaRouteToGoalArea(), and BotGetReachabilityToGoal().
AAS_AreaGrounded()
int AAS_AreaGrounded (int areanum)
Definition at line 712 of file be_aas_reach.c.
 {
     return (aasworld.areasettings[areanum].areaflags & AREA_GROUNDED);
 } //end of the function AAS_AreaGround
References aasworld, AREA_GROUNDED, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, and aas_s::areasettings.
Referenced by AAS_BestReachableLinkArea(), AAS_NearbySolidOrGap(), AAS_Reachability_Elevator(), AAS_Reachability_EqualFloorHeight(), AAS_Reachability_Grapple(), AAS_Reachability_Jump(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_WalkOffLedge(), and AAS_Reachability_WeaponJump().
AAS_AreaGroundFaceArea()
float AAS_AreaGroundFaceArea (int areanum)
Definition at line 538 of file be_aas_reach.c.
 {
     int i;
     float total;
     aas_area_t *area;
     aas_face_t *face;
     total = 0;
     area = &aasworld.areas[areanum];
     for (i = 0; i < area->numfaces; i++)
     {
         face = &aasworld.faces[abs(aasworld.faceindex[area->firstface + i])];
         if (!(face->faceflags & FACE_GROUND)) continue;
         //
         total += AAS_FaceArea(face);
     } //end for
     return total;
 } //end of the function AAS_AreaGroundFaceArea
References AAS_FaceArea(), aasworld, aas_lreachability_s::areanum, aas_s::areas, FACE_GROUND, aas_face_s::faceflags, aas_s::faceindex, aas_s::faces, aas_area_s::firstface, and aas_area_s::numfaces.
Referenced by AAS_RandomGoalArea().
AAS_AreaJumpPad()
int AAS_AreaJumpPad (int areanum)
Definition at line 733 of file be_aas_reach.c.
 {
     return (aasworld.areasettings[areanum].contents & AREACONTENTS_JUMPPAD);
 } //end of the function AAS_AreaJumpPad
References aasworld, AREACONTENTS_JUMPPAD, aas_lreachability_s::areanum, aas_s::areasettings, and aas_areasettings_s::contents.
Referenced by AAS_BestReachableFromJumpPadArea(), AAS_Reachability_Jump(), AAS_Reachability_JumpPad(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Teleport(), AAS_Reachability_WalkOffLedge(), BotMoveToGoal(), and BotUpdateEntityItems().
AAS_AreaLadder()
int AAS_AreaLadder (int areanum)
Definition at line 723 of file be_aas_reach.c.
 {
     return (aasworld.areasettings[areanum].areaflags & AREA_LADDER);
 } //end of the function AAS_AreaLadder
References aasworld, AREA_LADDER, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, and aas_s::areasettings.
Referenced by AAS_Reachability_Ladder().
AAS_AreaLava()
int AAS_AreaLava (int areanum)
Definition at line 691 of file be_aas_reach.c.
 {
     return (aasworld.areasettings[areanum].contents & AREACONTENTS_LAVA);
 } //end of the function AAS_AreaLava
References aasworld, AREACONTENTS_LAVA, aas_lreachability_s::areanum, aas_s::areasettings, and aas_areasettings_s::contents.
AAS_AreaLiquid()
int AAS_AreaLiquid (int areanum)
Definition at line 680 of file be_aas_reach.c.
 {
     if (aasworld.areasettings[areanum].areaflags & AREA_LIQUID) return qtrue;
     else return qfalse;
 } //end of the function AAS_AreaLiquid
References aasworld, AREA_LIQUID, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, aas_s::areasettings, qfalse, and qtrue.
AAS_AreaReachability()
int AAS_AreaReachability (int areanum)
Definition at line 522 of file be_aas_reach.c.
 {
     if (areanum < 0 || areanum >= aasworld.numareas)
     {
         AAS_Error("AAS_AreaReachability: areanum %d out of range\n", areanum);
         return 0;
     } //end if
     return aasworld.areasettings[areanum].numreachableareas;
 } //end of the function AAS_AreaReachability
References AAS_Error(), aasworld, aas_lreachability_s::areanum, aas_s::areasettings, aas_s::numareas, and aas_areasettings_s::numreachableareas.
Referenced by AAS_AlternativeRouteGoals(), AAS_BestReachableLinkArea(), AAS_CreateAllRoutingCache(), AAS_NumberClusterAreas(), AAS_PointReachabilityAreaIndex(), AAS_RandomGoalArea(), BotCheckBlocked(), BotChooseLTGItem(), BotChooseNBGItem(), BotFuzzyPointReachabilityArea(), BotMoveToGoal(), BotReachabilityArea(), and Init_AAS_Export().
AAS_AreaSlime()
int AAS_AreaSlime (int areanum)
Definition at line 701 of file be_aas_reach.c.
 {
     return (aasworld.areasettings[areanum].contents & AREACONTENTS_SLIME);
 } //end of the function AAS_AreaSlime
References aasworld, AREACONTENTS_SLIME, aas_lreachability_s::areanum, aas_s::areasettings, and aas_areasettings_s::contents.
AAS_AreaSwim()
int AAS_AreaSwim (int areanum)
Definition at line 668 of file be_aas_reach.c.
 {
     if (aasworld.areasettings[areanum].areaflags & AREA_LIQUID) return qtrue;
     else return qfalse;
 } //end of the function AAS_AreaSwim
References aasworld, AREA_LIQUID, aas_areasettings_s::areaflags, aas_lreachability_s::areanum, aas_s::areasettings, qfalse, and qtrue.
Referenced by AAS_AreaTravelTime(), AAS_BestReachableLinkArea(), AAS_NearbySolidOrGap(), AAS_RandomGoalArea(), AAS_Reachability_Elevator(), AAS_Reachability_Grapple(), AAS_Reachability_Step_Barrier_WaterJump_WalkOffLedge(), AAS_Reachability_Swim(), AAS_Reachability_WalkOffLedge(), and AAS_Reachability_WeaponJump().
AAS_BestReachableArea()
int AAS_BestReachableArea (vec3_t origin, vec3_t mins, vec3_t maxs, vec3_t goalorigin)
Definition at line 359 of file be_aas_reach.c.
 {
     int areanum, i, j, k, l;
     aas_link_t *areas;
     vec3_t absmins, absmaxs;
     //vec3_t bbmins, bbmaxs;
     vec3_t start, end;
     aas_trace_t trace;
     if (!aasworld.loaded)
     {
         botimport.Print(PRT_ERROR, "AAS_BestReachableArea: aas not loaded\n");
         return 0;
     } //end if
     //find a point in an area
     VectorCopy(origin, start);
     areanum = AAS_PointAreaNum(start);
     //while no area found fudge around a little
     for (i = 0; i < 5 && !areanum; i++)
     {
         for (j = 0; j < 5 && !areanum; j++)
         {
             for (k = -1; k <= 1 && !areanum; k++)
             {
                 for (l = -1; l <= 1 && !areanum; l++)
                 {
                     VectorCopy(origin, start);
                     start[0] += (float) j * 4 * k;
                     start[1] += (float) j * 4 * l;
                     start[2] += (float) i * 4;
                     areanum = AAS_PointAreaNum(start);
                 } //end for
             } //end for
         } //end for
     } //end for
     //if an area was found
     if (areanum)
     {
         //drop client bbox down and try again
         VectorCopy(start, end);
         start[2] += 0.25;
         end[2] -= 50;
         trace = AAS_TraceClientBBox(start, end, PRESENCE_CROUCH, -1);
         if (!trace.startsolid)
         {
             areanum = AAS_PointAreaNum(trace.endpos);
             VectorCopy(trace.endpos, goalorigin);
             //FIXME: cannot enable next line right now because the reachability
             // does not have to be calculated when the level items are loaded
             //if the origin is in an area with reachability
             //if (AAS_AreaReachability(areanum)) return areanum;
             if (areanum) return areanum;
         } //end if
         else
         {
             //it can very well happen that the AAS_PointAreaNum function tells that
             //a point is in an area and that starting an AAS_TraceClientBBox from that
             //point will return trace.startsolid qtrue
 #if 0
             if (AAS_PointAreaNum(start))
             {
                 Log_Write("point %f %f %f in area %d but trace startsolid", start[0], start[1], start[2], areanum);
                 AAS_DrawPermanentCross(start, 4, LINECOLOR_RED);
             } //end if
             botimport.Print(PRT_MESSAGE, "AAS_BestReachableArea: start solid\n");
 #endif
             VectorCopy(start, goalorigin);
             return areanum;
         } //end else
     } //end if
     //
     //AAS_PresenceTypeBoundingBox(PRESENCE_CROUCH, bbmins, bbmaxs);
     //NOTE: the goal origin does not have to be in the goal area
     // because the bot will have to move towards the item origin anyway
     VectorCopy(origin, goalorigin);
     //
     VectorAdd(origin, mins, absmins);
     VectorAdd(origin, maxs, absmaxs);
     //add bounding box size
     //VectorSubtract(absmins, bbmaxs, absmins);
     //VectorSubtract(absmaxs, bbmins, absmaxs);
     //link an invalid (-1) entity
     areas = AAS_LinkEntityClientBBox(absmins, absmaxs, -1, PRESENCE_CROUCH);
     //get the reachable link area
     areanum = AAS_BestReachableLinkArea(areas);
     //unlink the invalid entity
     AAS_UnlinkFromAreas(areas);
     //
     return areanum;
 } //end of the function AAS_BestReachableArea
References AAS_BestReachableLinkArea(), AAS_DrawPermanentCross(), AAS_LinkEntityClientBBox(), AAS_PointAreaNum(), AAS_TraceClientBBox(), AAS_UnlinkFromAreas(), aasworld, aas_lreachability_s::areanum, botimport, aas_lreachability_s::end, aas_trace_s::endpos, LINECOLOR_RED, aas_s::loaded, Log_Write(), PRESENCE_CROUCH, PRT_ERROR, PRT_MESSAGE, aas_lreachability_s::start, aas_trace_s::startsolid, VectorAdd, and VectorCopy.
Referenced by AAS_SetWeaponJumpAreaFlags(), BotInitLevelItems(), and BotUpdateEntityItems().
AAS_BestReachableFromJumpPadArea()
int AAS_BestReachableFromJumpPadArea (vec3_t origin, vec3_t mins, vec3_t maxs)
Definition at line 290 of file be_aas_reach.c.
 {
     int ent, bot_visualizejumppads, bestareanum;
     float volume, bestareavolume;
     vec3_t areastart, cmdmove, bboxmins, bboxmaxs;
     vec3_t absmins, absmaxs, velocity;
     aas_clientmove_t move;
     aas_link_t *areas, *link;
     char classname[MAX_EPAIRKEY];
 #ifdef BSPC
     bot_visualizejumppads = 0;
 #else
     bot_visualizejumppads = LibVarValue("bot_visualizejumppads", "0");
 #endif
     VectorAdd(origin, mins, bboxmins);
     VectorAdd(origin, maxs, bboxmaxs);
     for (ent = AAS_NextBSPEntity(0); ent; ent = AAS_NextBSPEntity(ent))
     {
         if (!AAS_ValueForBSPEpairKey(ent, "classname", classname, MAX_EPAIRKEY)) continue;
         if (strcmp(classname, "trigger_push")) continue;
         //
         if (!AAS_GetJumpPadInfo(ent, areastart, absmins, absmaxs, velocity)) continue;
         //get the areas the jump pad brush is in
         areas = AAS_LinkEntityClientBBox(absmins, absmaxs, -1, PRESENCE_CROUCH);
         for (link = areas; link; link = link->next_area)
         {
             if (AAS_AreaJumpPad(link->areanum)) break;
         } //end for
         if (!link)
         {
             botimport.Print(PRT_MESSAGE, "trigger_push not in any jump pad area\n");
             AAS_UnlinkFromAreas(areas);
             continue;
         } //end if
         //
         //botimport.Print(PRT_MESSAGE, "found a trigger_push with velocity %f %f %f\n", velocity[0], velocity[1], velocity[2]);
         //
         VectorSet(cmdmove, 0, 0, 0);
         Com_Memset(&move, 0, sizeof(aas_clientmove_t));
         AAS_ClientMovementHitBBox(&move, -1, areastart, PRESENCE_NORMAL, qfalse,
                                 velocity, cmdmove, 0, 30, 0.1f, bboxmins, bboxmaxs, bot_visualizejumppads);
         if (move.frames < 30)
         {
             bestareanum = 0;
             bestareavolume = 0;
             for (link = areas; link; link = link->next_area)
             {
                 if (!AAS_AreaJumpPad(link->areanum)) continue;
                 volume = AAS_AreaVolume(link->areanum);
                 if (volume >= bestareavolume)
                 {
                     bestareanum = link->areanum;
                     bestareavolume = volume;
                 } //end if
             } //end if
             AAS_UnlinkFromAreas(areas);
             return bestareanum;
         } //end if
         AAS_UnlinkFromAreas(areas);
     } //end for
     return 0;
 } //end of the function AAS_BestReachableFromJumpPadArea
References AAS_AreaJumpPad(), AAS_AreaVolume(), AAS_ClientMovementHitBBox(), AAS_GetJumpPadInfo(), AAS_LinkEntityClientBBox(), AAS_NextBSPEntity(), AAS_UnlinkFromAreas(), AAS_ValueForBSPEpairKey(), aas_link_s::areanum, botimport, Com_Memset, aas_clientmove_s::frames, LibVarValue(), MAX_EPAIRKEY, aas_link_s::next_area, PRESENCE_CROUCH, PRESENCE_NORMAL, PRT_MESSAGE, qfalse, VectorAdd, and VectorSet.
Referenced by BotInitLevelItems().
AAS_NextModelReachability()
int AAS_NextModelReachability (int num, int modelnum)
Definition at line 1982 of file be_aas_route.c.
 {
     int i;
     if (num <= 0) num = 1;
     else if (num >= aasworld.reachabilitysize) return 0;
     else num++;
     //
     for (i = num; i < aasworld.reachabilitysize; i++)
     {
         if ((aasworld.reachability[i].traveltype & TRAVELTYPE_MASK) == TRAVEL_ELEVATOR)
         {
             if (aasworld.reachability[i].facenum == modelnum) return i;
         } //end if
         else if ((aasworld.reachability[i].traveltype & TRAVELTYPE_MASK) == TRAVEL_FUNCBOB)
         {
             if ((aasworld.reachability[i].facenum & 0x0000FFFF) == modelnum) return i;
         } //end if
     } //end for
     return 0;
 } //end of the function AAS_NextModelReachability
References aasworld, aas_reachability_s::facenum, aas_s::reachability, aas_s::reachabilitysize, TRAVEL_ELEVATOR, TRAVEL_FUNCBOB, aas_reachability_s::traveltype, and TRAVELTYPE_MASK.
Referenced by BotMoveToGoal(), and BotReachabilityArea().