ioquake3 doxygen: C:/entry/dev/ioq3/code/game/g_weapon.c File Reference
g_weapon.c File Reference
#include "g_local.h"
Macros
#define NUM_NAILSHOTS 15
#define MACHINEGUN_SPREAD 200
#define MACHINEGUN_DAMAGE 7
#define MACHINEGUN_TEAM_DAMAGE 5
#define DEFAULT_SHOTGUN_DAMAGE 10
#define MAX_RAIL_HITS 4
Functions
void G_BounceProjectile (vec3_t start, vec3_t impact, vec3_t dir, vec3_t endout)
void Weapon_Gauntlet (gentity_t *ent)
qboolean CheckGauntletAttack (gentity_t *ent)
void SnapVectorTowards (vec3_t v, vec3_t to)
void Bullet_Fire (gentity_t *ent, float spread, int damage, int mod)
void BFG_Fire (gentity_t *ent)
qboolean ShotgunPellet (vec3_t start, vec3_t end, gentity_t *ent)
ShotgunPellet calculates each unique bullet’s path.
void ShotgunPattern (vec3_t origin, vec3_t origin2, int seed, gentity_t *ent)
ShotgunPattern creates the effect of the random spread of bullets.
void weapon_supershotgun_fire (gentity_t *ent)
Fires the shotgun.
void weapon_grenadelauncher_fire (gentity_t *ent)
void Weapon_RocketLauncher_Fire (gentity_t *ent)
void Weapon_Plasmagun_Fire (gentity_t *ent)
void weapon_railgun_fire (gentity_t *ent)
void Weapon_GrapplingHook_Fire (gentity_t *ent)
void Weapon_HookFree (gentity_t *ent)
void Weapon_HookThink (gentity_t *ent)
void Weapon_LightningFire (gentity_t *ent)
Fire lightning gun.
qboolean LogAccuracyHit (gentity_t *target, gentity_t *attacker)
void CalcMuzzlePoint (gentity_t *ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
void CalcMuzzlePointOrigin (gentity_t *ent, vec3_t origin, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
void FireWeapon (gentity_t *ent)
Variables
static float s_quadFactor
static vec3_t forward
static vec3_t right
static vec3_t up
static vec3_t muzzle
Macro Definition Documentation
DEFAULT_SHOTGUN_DAMAGE
#define DEFAULT_SHOTGUN_DAMAGE 10
Definition at line 272 of file g_weapon.c.
MACHINEGUN_DAMAGE
#define MACHINEGUN_DAMAGE 7
Definition at line 165 of file g_weapon.c.
MACHINEGUN_SPREAD
#define MACHINEGUN_SPREAD 200
Definition at line 164 of file g_weapon.c.
MACHINEGUN_TEAM_DAMAGE
#define MACHINEGUN_TEAM_DAMAGE 5
Definition at line 166 of file g_weapon.c.
MAX_RAIL_HITS
#define MAX_RAIL_HITS 4
Definition at line 464 of file g_weapon.c.
NUM_NAILSHOTS
#define NUM_NAILSHOTS 15
Definition at line 32 of file g_weapon.c.
Function Documentation
BFG_Fire()
void BFG_Fire (gentity_t * ent)
Definition at line 250 of file g_weapon.c.
 {
     gentity_t* m;
     m = fire_bfg(ent, muzzle, forward);
     m->damage *= s_quadFactor;
     m->splashDamage *= s_quadFactor;
     //    VectorAdd( m->s.pos.trDelta, ent->client->ps.velocity, m->s.pos.trDelta );    // "real" physics
 }
References fire_bfg(), forward, m, muzzle, and s_quadFactor.
Referenced by FireWeapon().
Bullet_Fire()
void Bullet_Fire (gentity_t * ent, float spread, int damage, int mod)
Definition at line 168 of file g_weapon.c.
 {
     trace_t        tr;
     vec3_t        end;
 #ifdef MISSIONPACK
     vec3_t        impactpoint, bouncedir;
 #endif
     float        r;
     float        u;
     gentity_t* tent;
     gentity_t* traceEnt;
     int            i, passent;
     damage *= s_quadFactor;
     r = random() * M_PI * 2.0f;
     u = sin(r) * crandom() * spread * 16;
     r = cos(r) * crandom() * spread * 16;
     VectorMA(muzzle, 8192 * 16, forward, end);
     VectorMA(end, r, right, end);
     VectorMA(end, u, up, end);
     passent = ent->s.number;
     for (i = 0; i < 10; i++) {
         trap_Trace(&tr, muzzle, NULL, NULL, end, passent, MASK_SHOT);
         if (tr.surfaceFlags & SURF_NOIMPACT) {
             return;
         }
         traceEnt = &g_entities[tr.entityNum];
         // snap the endpos to integers, but nudged towards the line
         SnapVectorTowards(tr.endpos, muzzle);
         // send bullet impact
         if (traceEnt->takedamage && traceEnt->client) {
             tent = G_TempEntity(tr.endpos, EV_BULLET_HIT_FLESH);
             tent->s.eventParm = traceEnt->s.number;
             if (LogAccuracyHit(traceEnt, ent)) {
                 ent->client->accuracy_hits++;
             }
         } else {
             tent = G_TempEntity(tr.endpos, EV_BULLET_HIT_WALL);
             tent->s.eventParm = DirToByte(tr.plane.normal);
         }
         tent->s.otherEntityNum = ent->s.number;
         if (traceEnt->takedamage) {
 #ifdef MISSIONPACK
             if (traceEnt->client && traceEnt->client->invulnerabilityTime > level.time) {
                 if (G_InvulnerabilityEffect(traceEnt, forward, tr.endpos, impactpoint, bouncedir)) {
                     G_BounceProjectile(muzzle, impactpoint, bouncedir, end);
                     VectorCopy(impactpoint, muzzle);
                     // the player can hit him/herself with the bounced rail
                     passent = ENTITYNUM_NONE;
                 } else {
                     VectorCopy(tr.endpos, muzzle);
                     passent = traceEnt->s.number;
                 }
                 continue;
             } else {
 #endif
                 G_Damage(traceEnt, ent, ent, forward, tr.endpos,
                     damage, 0, mod);
 #ifdef MISSIONPACK
             }
 #endif
         }
         break;
     }
 }
References gclient_s::accuracy_hits, gentity_s::client, crandom, DirToByte(), ENTITYNUM_NONE, EV_BULLET_HIT_FLESH, EV_BULLET_HIT_WALL, entityState_s::eventParm, forward, G_BounceProjectile(), G_Damage(), g_entities, G_InvulnerabilityEffect(), G_TempEntity(), level, LogAccuracyHit(), M_PI, MASK_SHOT, muzzle, NULL, entityState_s::number, entityState_s::otherEntityNum, random, right, gentity_s::s, s_quadFactor, SnapVectorTowards(), SURF_NOIMPACT, gentity_s::takedamage, level_locals_t::time, tr, trap_Trace(), up, VectorCopy, and VectorMA.
Referenced by FireWeapon().
CalcMuzzlePoint()
void CalcMuzzlePoint (gentity_t * ent, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
Definition at line 799 of file g_weapon.c.
 {
     VectorCopy(ent->s.pos.trBase, muzzlePoint);
     muzzlePoint[2] += ent->client->ps.viewheight;
     VectorMA(muzzlePoint, 14, forward, muzzlePoint);
     // snap to integer coordinates for more efficient network bandwidth usage
     SnapVector(muzzlePoint);
 }
References gentity_s::client, forward, entityState_s::pos, gclient_s::ps, gentity_s::s, SnapVector, trajectory_t::trBase, VectorCopy, VectorMA, and playerState_s::viewheight.
Referenced by CheckGauntletAttack().
CalcMuzzlePointOrigin()
void CalcMuzzlePointOrigin (gentity_t * ent, vec3_t origin, vec3_t forward, vec3_t right, vec3_t up, vec3_t muzzlePoint)
Definition at line 815 of file g_weapon.c.
 {
     VectorCopy(ent->s.pos.trBase, muzzlePoint);
     muzzlePoint[2] += ent->client->ps.viewheight;
     VectorMA(muzzlePoint, 14, forward, muzzlePoint);
     // snap to integer coordinates for more efficient network bandwidth usage
     SnapVector(muzzlePoint);
 }
References gentity_s::client, forward, entityState_s::pos, gclient_s::ps, gentity_s::s, SnapVector, trajectory_t::trBase, VectorCopy, VectorMA, and playerState_s::viewheight.
Referenced by FireWeapon().
CheckGauntletAttack()
qboolean CheckGauntletAttack (gentity_t * ent)
Definition at line 71 of file g_weapon.c.
 {
     trace_t        tr;
     vec3_t        end;
     gentity_t* tent;
     gentity_t* traceEnt;
     int            damage;
     // set aiming directions
     AngleVectors(ent->client->ps.viewangles, forward, right, up);
     CalcMuzzlePoint(ent, forward, right, up, muzzle);
     VectorMA(muzzle, 32, forward, end);
     trap_Trace(&tr, muzzle, NULL, NULL, end, ent->s.number, MASK_SHOT);
     if (tr.surfaceFlags & SURF_NOIMPACT) {
         return qfalse;
     }
     if (ent->client->noclip) {
         return qfalse;
     }
     traceEnt = &g_entities[tr.entityNum];
     // send blood impact
     if (traceEnt->takedamage && traceEnt->client) {
         tent = G_TempEntity(tr.endpos, EV_MISSILE_HIT);
         tent->s.otherEntityNum = traceEnt->s.number;
         tent->s.eventParm = DirToByte(tr.plane.normal);
         tent->s.weapon = ent->s.weapon;
     }
     if (!traceEnt->takedamage) {
         return qfalse;
     }
     if (ent->client->ps.powerups[PW_QUAD]) {
         G_AddEvent(ent, EV_POWERUP_QUAD, 0);
         s_quadFactor = g_quadfactor.value;
     } else {
         s_quadFactor = 1;
     }
 #ifdef MISSIONPACK
     if (ent->client->persistantPowerup && ent->client->persistantPowerup->item && ent->client->persistantPowerup->item->giTag == PW_DOUBLER) {
         s_quadFactor *= 2;
     }
 #endif
     damage = 50 * s_quadFactor;
     G_Damage(traceEnt, ent, ent, forward, tr.endpos,
         damage, 0, MOD_GAUNTLET);
     return qtrue;
 }
References AngleVectors(), CalcMuzzlePoint(), gentity_s::client, DirToByte(), EV_MISSILE_HIT, EV_POWERUP_QUAD, entityState_s::eventParm, forward, G_AddEvent(), G_Damage(), g_entities, g_quadfactor, G_TempEntity(), MASK_SHOT, MOD_GAUNTLET, muzzle, gclient_s::noclip, NULL, entityState_s::number, entityState_s::otherEntityNum, playerState_s::powerups, gclient_s::ps, PW_DOUBLER, PW_QUAD, qfalse, qtrue, right, gentity_s::s, s_quadFactor, SURF_NOIMPACT, gentity_s::takedamage, tr, trap_Trace(), up, vmCvar_t::value, VectorMA, playerState_s::viewangles, and entityState_s::weapon.
Referenced by ClientThink_real().
FireWeapon()
void FireWeapon (gentity_t * ent)
Definition at line 831 of file g_weapon.c.
 {
     if (ent->client->ps.powerups[PW_QUAD]) {
         s_quadFactor = g_quadfactor.value;
     } else {
         s_quadFactor = 1;
     }
 #ifdef MISSIONPACK
     if (ent->client->persistantPowerup && ent->client->persistantPowerup->item && ent->client->persistantPowerup->item->giTag == PW_DOUBLER) {
         s_quadFactor *= 2;
     }
 #endif
     // track shots taken for accuracy tracking.  Grapple is not a weapon and gauntet is just not tracked
     if (ent->s.weapon != WP_GRAPPLING_HOOK && ent->s.weapon != WP_GAUNTLET) {
 #ifdef MISSIONPACK
         if (ent->s.weapon == WP_NAILGUN) {
             ent->client->accuracy_shots += NUM_NAILSHOTS;
         } else {
             ent->client->accuracy_shots++;
         }
 #else
         ent->client->accuracy_shots++;
 #endif
     }
     // set aiming directions
     AngleVectors(ent->client->ps.viewangles, forward, right, up);
     CalcMuzzlePointOrigin(ent, ent->client->oldOrigin, forward, right, up, muzzle);
     // fire the specific weapon
     switch (ent->s.weapon) {
     case WP_GAUNTLET:
         Weapon_Gauntlet(ent);
         break;
     case WP_LIGHTNING:
         Weapon_LightningFire(ent);
         break;
     case WP_SHOTGUN:
         weapon_supershotgun_fire(ent);
         break;
     case WP_MACHINEGUN:
         if (g_gametype.integer != GT_TEAM) {
             Bullet_Fire(ent, MACHINEGUN_SPREAD, MACHINEGUN_DAMAGE, MOD_MACHINEGUN);
         } else {
             Bullet_Fire(ent, MACHINEGUN_SPREAD, MACHINEGUN_TEAM_DAMAGE, MOD_MACHINEGUN);
         }
         break;
     case WP_GRENADE_LAUNCHER:
         weapon_grenadelauncher_fire(ent);
         break;
     case WP_ROCKET_LAUNCHER:
         Weapon_RocketLauncher_Fire(ent);
         break;
     case WP_PLASMAGUN:
         Weapon_Plasmagun_Fire(ent);
         break;
     case WP_RAILGUN:
         weapon_railgun_fire(ent);
         break;
     case WP_BFG:
         BFG_Fire(ent);
         break;
     case WP_GRAPPLING_HOOK:
         Weapon_GrapplingHook_Fire(ent);
         break;
 #ifdef MISSIONPACK
     case WP_NAILGUN:
         Weapon_Nailgun_Fire(ent);
         break;
     case WP_PROX_LAUNCHER:
         weapon_proxlauncher_fire(ent);
         break;
     case WP_CHAINGUN:
         Bullet_Fire(ent, CHAINGUN_SPREAD, CHAINGUN_DAMAGE, MOD_CHAINGUN);
         break;
 #endif
     default:
         // FIXME        G_Error( "Bad ent->s.weapon" );
         break;
     }
 }
References gclient_s::accuracy_shots, AngleVectors(), BFG_Fire(), Bullet_Fire(), CalcMuzzlePointOrigin(), gentity_s::client, forward, g_gametype, g_quadfactor, GT_TEAM, MACHINEGUN_DAMAGE, MACHINEGUN_SPREAD, MACHINEGUN_TEAM_DAMAGE, MOD_MACHINEGUN, muzzle, NUM_NAILSHOTS, gclient_s::oldOrigin, playerState_s::powerups, gclient_s::ps, PW_DOUBLER, PW_QUAD, right, gentity_s::s, s_quadFactor, up, vmCvar_t::value, playerState_s::viewangles, entityState_s::weapon, Weapon_Gauntlet(), Weapon_GrapplingHook_Fire(), weapon_grenadelauncher_fire(), Weapon_LightningFire(), Weapon_Plasmagun_Fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), weapon_supershotgun_fire(), WP_BFG, WP_GAUNTLET, WP_GRAPPLING_HOOK, WP_GRENADE_LAUNCHER, WP_LIGHTNING, WP_MACHINEGUN, WP_PLASMAGUN, WP_RAILGUN, WP_ROCKET_LAUNCHER, and WP_SHOTGUN.
Referenced by ClientEvents().
G_BounceProjectile()
void G_BounceProjectile (vec3_t start, vec3_t impact, vec3_t dir, vec3_t endout)
Definition at line 39 of file g_weapon.c.
 {
     vec3_t v, newv;
     float dot;
     VectorSubtract(impact, start, v);
     dot = DotProduct(v, dir);
     VectorMA(v, -2 * dot, dir, newv);
     VectorNormalize(newv);
     VectorMA(impact, 8192, newv, endout);
 }
References DotProduct, VectorMA, VectorNormalize(), and VectorSubtract.
Referenced by Bullet_Fire(), ShotgunPellet(), Weapon_LightningFire(), and weapon_railgun_fire().
LogAccuracyHit()
qboolean LogAccuracyHit (gentity_t * target, gentity_t * attacker)
Definition at line 762 of file g_weapon.c.
 {
     if (!target->takedamage) {
         return qfalse;
     }
     if (target == attacker) {
         return qfalse;
     }
     if (!target->client) {
         return qfalse;
     }
     if (!attacker->client) {
         return qfalse;
     }
     if (target->client->ps.stats[STAT_HEALTH] <= 0) {
         return qfalse;
     }
     if (OnSameTeam(target, attacker)) {
         return qfalse;
     }
     return qtrue;
 }
References gentity_s::client, OnSameTeam(), gclient_s::ps, qfalse, qtrue, STAT_HEALTH, playerState_s::stats, and gentity_s::takedamage.
Referenced by Bullet_Fire(), G_MissileImpact(), G_RadiusDamage(), ShotgunPellet(), Weapon_LightningFire(), and weapon_railgun_fire().
ShotgunPattern()
void ShotgunPattern (vec3_t origin, vec3_t origin2, int seed, gentity_t * ent)
ShotgunPattern creates the effect of the random spread of bullets.
ShotgunPattern should match CG_ShotgunPattern.
Parameters
origin
origin2
seed
ent
Definition at line 341 of file g_weapon.c.
 {
     int         i;
     float       r, u;
     vec3_t      end;
     vec3_t      forward, right, up;
     qboolean    hitClient = qfalse;
     // derive the right and up vectors from the forward vector, because
     // the client won't have any other information
     VectorNormalize2(origin2, forward);
     PerpendicularVector(right, forward);
     CrossProduct(forward, right, up);
     // generate the "random" spread pattern
     for (i = 0; i < DEFAULT_SHOTGUN_COUNT; i++) {
         r = Q_crandom(&seed) * DEFAULT_SHOTGUN_SPREAD * 16;
         u = Q_crandom(&seed) * DEFAULT_SHOTGUN_SPREAD * 16;
         VectorMA(origin, 8192 * 16, forward, end);
         VectorMA(end, r, right, end);
         VectorMA(end, u, up, end);
         if (ShotgunPellet(origin, end, ent) && !hitClient) {
             hitClient = qtrue;
             ent->client->accuracy_hits++;
         }
     }
 }
References gclient_s::accuracy_hits, gentity_s::client, CrossProduct(), DEFAULT_SHOTGUN_COUNT, DEFAULT_SHOTGUN_SPREAD, forward, PerpendicularVector(), Q_crandom(), qfalse, qtrue, right, ShotgunPellet(), up, VectorMA, and VectorNormalize2().
Referenced by weapon_supershotgun_fire().
ShotgunPellet()
qboolean ShotgunPellet (vec3_t start, vec3_t end, gentity_t * ent)
ShotgunPellet calculates each unique bullet’s path.
Parameters
start
end
ent
Returns
Definition at line 282 of file g_weapon.c.
 {
     trace_t     tr;
     int         damage, i, passent;
     gentity_t* traceEnt;
 #ifdef MISSIONPACK
     vec3_t      impactpoint, bouncedir;
 #endif
     vec3_t      tr_start, tr_end;
     qboolean    hitClient = qfalse;
     passent = ent->s.number;
     VectorCopy(start, tr_start);
     VectorCopy(end, tr_end);
     for (i = 0; i < 10; i++) {
         trap_Trace(&tr, tr_start, NULL, NULL, tr_end, passent, MASK_SHOT);
         traceEnt = &g_entities[tr.entityNum];
         // send bullet impact
         if (tr.surfaceFlags & SURF_NOIMPACT) {
             return qfalse;
         }
         if (traceEnt->takedamage) {
             damage = DEFAULT_SHOTGUN_DAMAGE * s_quadFactor;
 #ifdef MISSIONPACK
             if (traceEnt->client && traceEnt->client->invulnerabilityTime > level.time) {
                 if (G_InvulnerabilityEffect(traceEnt, forward, tr.endpos, impactpoint, bouncedir)) {
                     G_BounceProjectile(tr_start, impactpoint, bouncedir, tr_end);
                     VectorCopy(impactpoint, tr_start);
                     // the player can hit him/herself with the bounced rail
                     passent = ENTITYNUM_NONE;
                 } else {
                     VectorCopy(tr.endpos, tr_start);
                     passent = traceEnt->s.number;
                 }
                 continue;
             }
 #endif
             if (LogAccuracyHit(traceEnt, ent)) {
                 hitClient = qtrue;
             }
             G_Damage(traceEnt, ent, ent, forward, tr.endpos, damage, 0, MOD_SHOTGUN);
             return hitClient;
         }
         return qfalse;
     }
     return qfalse;
 }
References gentity_s::client, DEFAULT_SHOTGUN_DAMAGE, ENTITYNUM_NONE, forward, G_BounceProjectile(), G_Damage(), g_entities, G_InvulnerabilityEffect(), level, LogAccuracyHit(), MASK_SHOT, MOD_SHOTGUN, NULL, entityState_s::number, qfalse, qtrue, gentity_s::s, s_quadFactor, SURF_NOIMPACT, gentity_s::takedamage, level_locals_t::time, tr, trap_Trace(), and VectorCopy.
Referenced by ShotgunPattern().
SnapVectorTowards()
void SnapVectorTowards (vec3_t v, vec3_t to)
Definition at line 147 of file g_weapon.c.
 {
     int        i;
     for (i = 0; i < 3; i++) {
         if (to[i] <= v[i]) {
             v[i] = floor(v[i]);
         } else {
             v[i] = ceil(v[i]);
         }
     }
 }
Referenced by Bullet_Fire(), G_MissileImpact(), Weapon_HookThink(), and weapon_railgun_fire().
Weapon_Gauntlet()
void Weapon_Gauntlet (gentity_t * ent)
Definition at line 61 of file g_weapon.c.
 {
 }
Referenced by FireWeapon().
Weapon_GrapplingHook_Fire()
void Weapon_GrapplingHook_Fire (gentity_t * ent)
Definition at line 596 of file g_weapon.c.
 {
     if (!ent->client->fireHeld && !ent->client->hook)
         fire_grapple(ent, muzzle, forward);
     ent->client->fireHeld = qtrue;
 }
References gentity_s::client, fire_grapple(), gclient_s::fireHeld, forward, gclient_s::hook, muzzle, and qtrue.
Referenced by FireWeapon().
weapon_grenadelauncher_fire()
void weapon_grenadelauncher_fire (gentity_t * ent)
Definition at line 396 of file g_weapon.c.
 {
     gentity_t* m;
     // extra vertical velocity
     forward[2] += 0.2f;
     VectorNormalize(forward);
     m = fire_grenade(ent, muzzle, forward);
     m->damage *= s_quadFactor;
     m->splashDamage *= s_quadFactor;
     // VectorAdd( m->s.pos.trDelta, ent->client->ps.velocity, m->s.pos.trDelta );    // "real" physics
 }
References fire_grenade(), forward, m, muzzle, s_quadFactor, and VectorNormalize().
Referenced by FireWeapon().
Weapon_HookFree()
void Weapon_HookFree (gentity_t * ent)
Definition at line 604 of file g_weapon.c.
 {
     ent->parent->client->hook = NULL;
     ent->parent->client->ps.pm_flags &= ~PMF_GRAPPLE_PULL;
     G_FreeEntity(ent);
 }
References gentity_s::client, G_FreeEntity(), gclient_s::hook, NULL, gentity_s::parent, playerState_s::pm_flags, PMF_GRAPPLE_PULL, and gclient_s::ps.
Referenced by ClientThink_real(), fire_grapple(), and player_die().
Weapon_HookThink()
void Weapon_HookThink (gentity_t * ent)
Definition at line 611 of file g_weapon.c.
 {
     if (ent->enemy) {
         vec3_t v, oldorigin;
         VectorCopy(ent->r.currentOrigin, oldorigin);
         v[0] = ent->enemy->r.currentOrigin[0] + (ent->enemy->r.mins[0] + ent->enemy->r.maxs[0]) * 0.5;
         v[1] = ent->enemy->r.currentOrigin[1] + (ent->enemy->r.mins[1] + ent->enemy->r.maxs[1]) * 0.5;
         v[2] = ent->enemy->r.currentOrigin[2] + (ent->enemy->r.mins[2] + ent->enemy->r.maxs[2]) * 0.5;
         SnapVectorTowards(v, oldorigin);    // save net bandwidth
         G_SetOrigin(ent, v);
     }
     VectorCopy(ent->r.currentOrigin, ent->parent->client->ps.grapplePoint);
 }
References gentity_s::client, entityShared_t::currentOrigin, gentity_s::enemy, G_SetOrigin(), playerState_s::grapplePoint, entityShared_t::maxs, entityShared_t::mins, gentity_s::parent, gclient_s::ps, gentity_s::r, SnapVectorTowards(), and VectorCopy.
Referenced by G_MissileImpact().
Weapon_LightningFire()
void Weapon_LightningFire (gentity_t * ent)
Fire lightning gun.
Parameters
ent The attacker.
Definition at line 633 of file g_weapon.c.
 {
     trace_t     tr;
     vec3_t      end;
 #ifdef MISSIONPACK
     vec3_t impactpoint, bouncedir;
 #endif
     gentity_t*  traceEnt, * tent;
     int         damage, i, passent;
     damage = 8 * s_quadFactor;
     passent = ent->s.number;
     for (i = 0; i < 10; i++) {
         VectorMA(muzzle, LIGHTNING_RANGE, forward, end);
         trap_Trace(&tr, muzzle, NULL, NULL, end, passent, MASK_SHOT);
 #ifdef MISSIONPACK
         // if not the first trace (the lightning bounced of an invulnerability sphere)
         if (i) {
             // add bounced off lightning bolt temp entity
             // the first lightning bolt is a cgame only visual
             //
             tent = G_TempEntity(muzzle, EV_LIGHTNINGBOLT);
             VectorCopy(tr.endpos, end);
             SnapVector(end);
             VectorCopy(end, tent->s.origin2);
         }
 #endif
         if (tr.entityNum == ENTITYNUM_NONE)
             return;
         traceEnt = &g_entities[tr.entityNum];
         if (traceEnt->takedamage) {
 #ifdef MISSIONPACK
             if (traceEnt->client && traceEnt->client->invulnerabilityTime > level.time) {
                 if (G_InvulnerabilityEffect(traceEnt, forward, tr.endpos, impactpoint, bouncedir)) {
                     G_BounceProjectile(muzzle, impactpoint, bouncedir, end);
                     VectorCopy(impactpoint, muzzle);
                     VectorSubtract(end, impactpoint, forward);
                     VectorNormalize(forward);
                     // the player can hit him/herself with the bounced lightning
                     passent = ENTITYNUM_NONE;
                 } else {
                     VectorCopy(tr.endpos, muzzle);
                     passent = traceEnt->s.number;
                 }
                 continue;
             }
 #endif
             if (LogAccuracyHit(traceEnt, ent))
                 ent->client->accuracy_hits++;
             G_Damage(traceEnt, ent, ent, forward, tr.endpos, damage, 0, MOD_LIGHTNING);
         }
         if (traceEnt->takedamage && traceEnt->client) {
             tent = G_TempEntity(tr.endpos, EV_MISSILE_HIT);
             tent->s.otherEntityNum = traceEnt->s.number;
             tent->s.eventParm = DirToByte(tr.plane.normal);
             tent->s.weapon = ent->s.weapon;
         } else if (!(tr.surfaceFlags & SURF_NOIMPACT)) {
             tent = G_TempEntity(tr.endpos, EV_MISSILE_MISS);
             tent->s.eventParm = DirToByte(tr.plane.normal);
         }
         break;
     }
 }
References gclient_s::accuracy_hits, gentity_s::client, DirToByte(), ENTITYNUM_NONE, EV_LIGHTNINGBOLT, EV_MISSILE_HIT, EV_MISSILE_MISS, entityState_s::eventParm, forward, G_BounceProjectile(), G_Damage(), g_entities, G_InvulnerabilityEffect(), G_TempEntity(), level, LIGHTNING_RANGE, LogAccuracyHit(), MASK_SHOT, MOD_LIGHTNING, muzzle, NULL, entityState_s::number, entityState_s::origin2, entityState_s::otherEntityNum, gentity_s::s, s_quadFactor, SnapVector, SURF_NOIMPACT, gentity_s::takedamage, level_locals_t::time, tr, trap_Trace(), VectorCopy, VectorMA, VectorNormalize(), VectorSubtract, and entityState_s::weapon.
Referenced by FireWeapon().
Weapon_Plasmagun_Fire()
void Weapon_Plasmagun_Fire (gentity_t * ent)
Definition at line 439 of file g_weapon.c.
 {
     gentity_t* m;
     m = fire_plasma(ent, muzzle, forward);
     m->damage *= s_quadFactor;
     m->splashDamage *= s_quadFactor;
     //    VectorAdd( m->s.pos.trDelta, ent->client->ps.velocity, m->s.pos.trDelta );    // "real" physics
 }
References fire_plasma(), forward, m, muzzle, and s_quadFactor.
Referenced by FireWeapon().
weapon_railgun_fire()
void weapon_railgun_fire (gentity_t * ent)
Definition at line 465 of file g_weapon.c.
 {
     vec3_t        end;
 #ifdef MISSIONPACK
     vec3_t impactpoint, bouncedir;
 #endif
     trace_t        trace;
     gentity_t* tent;
     gentity_t* traceEnt;
     int            damage;
     int            i;
     int            hits;
     int            unlinked;
     int            passent;
     gentity_t* unlinkedEntities[MAX_RAIL_HITS];
     damage = 100 * s_quadFactor;
     VectorMA(muzzle, 8192, forward, end);
     // trace only against the solids, so the railgun will go through people
     unlinked = 0;
     hits = 0;
     passent = ent->s.number;
     do {
         trap_Trace(&trace, muzzle, NULL, NULL, end, passent, MASK_SHOT);
         if (trace.entityNum >= ENTITYNUM_MAX_NORMAL) {
             break;
         }
         traceEnt = &g_entities[trace.entityNum];
         if (traceEnt->takedamage) {
 #ifdef MISSIONPACK
             if (traceEnt->client && traceEnt->client->invulnerabilityTime > level.time) {
                 if (G_InvulnerabilityEffect(traceEnt, forward, trace.endpos, impactpoint, bouncedir)) {
                     G_BounceProjectile(muzzle, impactpoint, bouncedir, end);
                     // snap the endpos to integers to save net bandwidth, but nudged towards the line
                     SnapVectorTowards(trace.endpos, muzzle);
                     // send railgun beam effect
                     tent = G_TempEntity(trace.endpos, EV_RAILTRAIL);
                     // set player number for custom colors on the railtrail
                     tent->s.clientNum = ent->s.clientNum;
                     VectorCopy(muzzle, tent->s.origin2);
                     // move origin a bit to come closer to the drawn gun muzzle
                     VectorMA(tent->s.origin2, 4, right, tent->s.origin2);
                     VectorMA(tent->s.origin2, -1, up, tent->s.origin2);
                     tent->s.eventParm = 255;    // don't make the explosion at the end
                     //
                     VectorCopy(impactpoint, muzzle);
                     // the player can hit him/herself with the bounced rail
                     passent = ENTITYNUM_NONE;
                 }
             } else {
                 if (LogAccuracyHit(traceEnt, ent)) {
                     hits++;
                 }
                 G_Damage(traceEnt, ent, ent, forward, trace.endpos, damage, 0, MOD_RAILGUN);
             }
 #else
             if (LogAccuracyHit(traceEnt, ent)) {
                 hits++;
             }
             G_Damage(traceEnt, ent, ent, forward, trace.endpos, damage, 0, MOD_RAILGUN);
 #endif
         }
         if (trace.contents & CONTENTS_SOLID) {
             break;        // we hit something solid enough to stop the beam
         }
         // unlink this entity, so the next trace will go past it
         trap_UnlinkEntity(traceEnt);
         unlinkedEntities[unlinked] = traceEnt;
         unlinked++;
     } while (unlinked < MAX_RAIL_HITS);
     // link back in any entities we unlinked
     for (i = 0; i < unlinked; i++) {
         trap_LinkEntity(unlinkedEntities[i]);
     }
     // the final trace endpos will be the terminal point of the rail trail
     // snap the endpos to integers to save net bandwidth, but nudged towards the line
     SnapVectorTowards(trace.endpos, muzzle);
     // send railgun beam effect
     tent = G_TempEntity(trace.endpos, EV_RAILTRAIL);
     // set player number for custom colors on the railtrail
     tent->s.clientNum = ent->s.clientNum;
     VectorCopy(muzzle, tent->s.origin2);
     // move origin a bit to come closer to the drawn gun muzzle
     VectorMA(tent->s.origin2, 4, right, tent->s.origin2);
     VectorMA(tent->s.origin2, -1, up, tent->s.origin2);
     // no explosion at end if SURF_NOIMPACT, but still make the trail
     if (trace.surfaceFlags & SURF_NOIMPACT) {
         tent->s.eventParm = 255;    // don't make the explosion at the end
     } else {
         tent->s.eventParm = DirToByte(trace.plane.normal);
     }
     tent->s.clientNum = ent->s.clientNum;
     // give the shooter a reward sound if they have made two railgun hits in a row
     if (hits == 0) {
         // complete miss
         ent->client->accurateCount = 0;
     } else {
         // check for "impressive" reward sound
         ent->client->accurateCount += hits;
         if (ent->client->accurateCount >= 2) {
             ent->client->accurateCount -= 2;
             ent->client->ps.persistant[PERS_IMPRESSIVE_COUNT]++;
             // add the sprite over the player's head
             ent->client->ps.eFlags &= ~(EF_AWARD_IMPRESSIVE | EF_AWARD_EXCELLENT | EF_AWARD_GAUNTLET | EF_AWARD_ASSIST | EF_AWARD_DEFEND | EF_AWARD_CAP);
             ent->client->ps.eFlags |= EF_AWARD_IMPRESSIVE;
             ent->client->rewardTime = level.time + REWARD_SPRITE_TIME;
         }
         ent->client->accuracy_hits++;
     }
 }
References gclient_s::accuracy_hits, gclient_s::accurateCount, gentity_s::client, entityState_s::clientNum, trace_t::contents, CONTENTS_SOLID, DirToByte(), EF_AWARD_ASSIST, EF_AWARD_CAP, EF_AWARD_DEFEND, EF_AWARD_EXCELLENT, EF_AWARD_GAUNTLET, EF_AWARD_IMPRESSIVE, playerState_s::eFlags, trace_t::endpos, trace_t::entityNum, ENTITYNUM_MAX_NORMAL, ENTITYNUM_NONE, EV_RAILTRAIL, entityState_s::eventParm, forward, G_BounceProjectile(), G_Damage(), g_entities, G_InvulnerabilityEffect(), G_TempEntity(), level, LogAccuracyHit(), MASK_SHOT, MAX_RAIL_HITS, MOD_RAILGUN, muzzle, cplane_s::normal, NULL, entityState_s::number, entityState_s::origin2, PERS_IMPRESSIVE_COUNT, playerState_s::persistant, trace_t::plane, gclient_s::ps, REWARD_SPRITE_TIME, gclient_s::rewardTime, right, gentity_s::s, s_quadFactor, SnapVectorTowards(), SURF_NOIMPACT, trace_t::surfaceFlags, gentity_s::takedamage, level_locals_t::time, trap_LinkEntity(), trap_Trace(), trap_UnlinkEntity(), up, VectorCopy, and VectorMA.
Referenced by FireWeapon().
Weapon_RocketLauncher_Fire()
void Weapon_RocketLauncher_Fire (gentity_t * ent)
Definition at line 419 of file g_weapon.c.
 {
     gentity_t* m;
     m = fire_rocket(ent, muzzle, forward);
     m->damage *= s_quadFactor;
     m->splashDamage *= s_quadFactor;
     // VectorAdd( m->s.pos.trDelta, ent->client->ps.velocity, m->s.pos.trDelta );    // "real" physics
 }
References fire_rocket(), forward, m, muzzle, and s_quadFactor.
Referenced by FireWeapon().
weapon_supershotgun_fire()
void weapon_supershotgun_fire (gentity_t * ent)
Fires the shotgun.
Parameters
[in] ent Shotgun owner.
Definition at line 373 of file g_weapon.c.
 {
     gentity_t* tent;
     // send shotgun blast
     tent = G_TempEntity(muzzle, EV_SHOTGUN);
     VectorScale(forward, 4096, tent->s.origin2);
     SnapVector(tent->s.origin2);
     tent->s.eventParm = rand() & 255;       // seed for spread pattern
     tent->s.otherEntityNum = ent->s.number;
     ShotgunPattern(tent->s.pos.trBase, tent->s.origin2, tent->s.eventParm, ent);
 }
References EV_SHOTGUN, entityState_s::eventParm, forward, G_TempEntity(), muzzle, entityState_s::number, entityState_s::origin2, entityState_s::otherEntityNum, entityState_s::pos, gentity_s::s, ShotgunPattern(), SnapVector, trajectory_t::trBase, and VectorScale.
Referenced by FireWeapon().
Variable Documentation
forward
vec3_t forward static
Definition at line 29 of file g_weapon.c.
Referenced by AAS_GetJumpPadInfo(), AAS_WeaponJumpZVelocity(), AimAtTarget(), AngleVectors(), Autosprite2Deform(), BFG_Fire(), BotAttackMove(), BotCheckAttack(), BotExportTest(), BotInputToUserCommand(), Bullet_Fire(), CalcMuzzlePoint(), CalcMuzzlePointOrigin(), CG_CalcMuzzlePoint(), CG_GrappleTrail(), CG_LightningBolt(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_ParticleBloodCloud(), CG_ParticleDust(), CG_ShotgunPattern(), CG_Tracer(), CheckGauntletAttack(), CL_JoystickMove(), CL_KeyMove(), CM_TransformedPointContents(), FireWeapon(), G_MissileImpact(), G_TryPushingProxMine(), MakeNormalVectors(), Pickup_Powerup(), PM_DeadMove(), ShotgunPattern(), ShotgunPellet(), vectoangles(), Weapon_GrapplingHook_Fire(), weapon_grenadelauncher_fire(), Weapon_LightningFire(), Weapon_Plasmagun_Fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), and weapon_supershotgun_fire().
muzzle
vec3_t muzzle static
Definition at line 30 of file g_weapon.c.
Referenced by BFG_Fire(), Bullet_Fire(), CG_CalcMuzzlePoint(), CheckGauntletAttack(), FireWeapon(), Weapon_GrapplingHook_Fire(), weapon_grenadelauncher_fire(), Weapon_LightningFire(), Weapon_Plasmagun_Fire(), weapon_railgun_fire(), Weapon_RocketLauncher_Fire(), and weapon_supershotgun_fire().
right
vec3_t right static
Definition at line 29 of file g_weapon.c.
Referenced by AAS_WeaponJumpZVelocity(), AnglesToAxis(), AngleVectors(), BotCheckAttack(), BotExportTest(), BotInputToUserCommand(), Bullet_Fire(), CG_DrawTeamOverlay(), CG_OffsetThirdPersonView(), CG_ShotgunPattern(), CG_TileClear(), CG_Tracer(), CheckGauntletAttack(), CL_JoystickMove(), CM_TransformedPointContents(), DoRailDiscs(), FireWeapon(), G_TryPushingProxMine(), MakeNormalVectors(), Mat4Ortho(), RB_SurfaceLightningBolt(), RB_SurfaceRailCore(), RB_SurfaceRailRings(), S_AddLoopSounds(), S_TransferPaintBuffer(), ShotgunPattern(), Use_Shooter(), ValidBloodPool(), and weapon_railgun_fire().
s_quadFactor
float s_quadFactor static
Definition at line 28 of file g_weapon.c.
Referenced by BFG_Fire(), Bullet_Fire(), CheckGauntletAttack(), FireWeapon(), ShotgunPellet(), weapon_grenadelauncher_fire(), Weapon_LightningFire(), Weapon_Plasmagun_Fire(), weapon_railgun_fire(), and Weapon_RocketLauncher_Fire().
up
vec3_t up static
Definition at line 29 of file g_weapon.c.
Referenced by AAS_AreaGroundFace(), AAS_ClientMovementPrediction(), AAS_DrawArrow(), AAS_OnGround(), AAS_Reachability_Jump(), AAS_Reachability_Ladder(), AngleVectors(), AutospriteDeform(), BotAIBlocked(), BotAttackMove(), BotCheckBlocked(), BotImport_DebugLineShow(), BotOnTopOfEntity(), BotReachabilityArea(), Bullet_Fire(), CG_AddScorePlum(), CG_DamageFeedback(), CG_EntityEvent(), CG_GrappleTrail(), CG_OffsetFirstPersonView(), CG_OffsetThirdPersonView(), CG_RocketTrail(), CG_ShotgunFire(), CG_ShotgunPattern(), CheckGauntletAttack(), CL_JoystickMove(), CL_KeyMove(), CM_EdgePlaneNum(), CM_TransformedPointContents(), DebugLine(), DoRailCore(), DoRailDiscs(), FireWeapon(), G_TryPushingProxMine(), MakeNormalVectors(), PM_StepSlideMove(), R_RenderPshadowMaps(), RB_AddQuadStamp(), RB_AddQuadStampExt(), RB_SurfaceRailRings(), RB_SurfaceSprite(), ShotgunPattern(), Use_Shooter(), ValidBloodPool(), and weapon_railgun_fire().