ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_aas_optimize.h File Reference
be_aas_optimize.h File Reference
Functions
void AAS_Optimize (void)
Function Documentation
AAS_Optimize()
void AAS_Optimize (void)
Definition at line 280 of file be_aas_optimize.c.
 {
     int i, sign;
     optimized_t optimized;
     AAS_OptimizeAlloc(&optimized);
     for (i = 1; i < aasworld.numareas; i++)
     {
         AAS_OptimizeArea(&optimized, i);
     } //end for
     //reset the reachability face pointers
     for (i = 0; i < aasworld.reachabilitysize; i++)
     {
         //NOTE: for TRAVEL_ELEVATOR the facenum is the model number of
         //      the elevator
         if ((aasworld.reachability[i].traveltype & TRAVELTYPE_MASK) == TRAVEL_ELEVATOR) continue;
         //NOTE: for TRAVEL_JUMPPAD the facenum is the Z velocity and the edgenum is the hor velocity
         if ((aasworld.reachability[i].traveltype & TRAVELTYPE_MASK) == TRAVEL_JUMPPAD) continue;
         //NOTE: for TRAVEL_FUNCBOB the facenum and edgenum contain other coded information
         if ((aasworld.reachability[i].traveltype & TRAVELTYPE_MASK) == TRAVEL_FUNCBOB) continue;
         //
         sign = aasworld.reachability[i].facenum;
         aasworld.reachability[i].facenum = optimized.faceoptimizeindex[abs(aasworld.reachability[i].facenum)];
         if (sign < 0) aasworld.reachability[i].facenum = -aasworld.reachability[i].facenum;
         sign = aasworld.reachability[i].edgenum;
         aasworld.reachability[i].edgenum = optimized.edgeoptimizeindex[abs(aasworld.reachability[i].edgenum)];
         if (sign < 0) aasworld.reachability[i].edgenum = -aasworld.reachability[i].edgenum;
     } //end for
     //store the optimized AAS data into aasworld
     AAS_OptimizeStore(&optimized);
     //print some nice stuff :)
     botimport.Print(PRT_MESSAGE, "AAS data optimized.\n");
 } //end of the function AAS_Optimize
References AAS_OptimizeAlloc(), AAS_OptimizeArea(), AAS_OptimizeStore(), aasworld, botimport, aas_reachability_s::edgenum, optimized_s::edgeoptimizeindex, aas_reachability_s::facenum, optimized_s::faceoptimizeindex, aas_s::numareas, PRT_MESSAGE, aas_s::reachability, aas_s::reachabilitysize, TRAVEL_ELEVATOR, TRAVEL_FUNCBOB, TRAVEL_JUMPPAD, aas_reachability_s::traveltype, and TRAVELTYPE_MASK.
Referenced by AAS_ContinueInit().