ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ai_weap.h File Reference
be_ai_weap.h File Reference
Classes
struct projectileinfo_s
struct weaponinfo_s
Macros
#define PFL_WINDOWDAMAGE 1
#define PFL_RETURN 2
#define WFL_FIRERELEASED 1
#define DAMAGETYPE_IMPACT 1
#define DAMAGETYPE_RADIAL 2
#define DAMAGETYPE_VISIBLE 4
Typedefs
typedef struct projectileinfo_s projectileinfo_t
typedef struct weaponinfo_s weaponinfo_t
Functions
int BotSetupWeaponAI (void)
void BotShutdownWeaponAI (void)
int BotChooseBestFightWeapon (int weaponstate, int *inventory)
void BotGetWeaponInfo (int weaponstate, int weapon, weaponinfo_t *weaponinfo)
int BotLoadWeaponWeights (int weaponstate, char *filename)
int BotAllocWeaponState (void)
void BotFreeWeaponState (int weaponstate)
void BotResetWeaponState (int weaponstate)
Macro Definition Documentation
DAMAGETYPE_IMPACT
#define DAMAGETYPE_IMPACT 1
Definition at line 39 of file be_ai_weap.h.
DAMAGETYPE_RADIAL
#define DAMAGETYPE_RADIAL 2
Definition at line 40 of file be_ai_weap.h.
DAMAGETYPE_VISIBLE
#define DAMAGETYPE_VISIBLE 4
Definition at line 41 of file be_ai_weap.h.
PFL_RETURN
#define PFL_RETURN 2
Definition at line 35 of file be_ai_weap.h.
PFL_WINDOWDAMAGE
#define PFL_WINDOWDAMAGE 1
Definition at line 34 of file be_ai_weap.h.
WFL_FIRERELEASED
#define WFL_FIRERELEASED 1
Definition at line 37 of file be_ai_weap.h.
Typedef Documentation
projectileinfo_t
typedef struct projectileinfo_s projectileinfo_t
weaponinfo_t
typedef struct weaponinfo_s weaponinfo_t
Function Documentation
BotAllocWeaponState()
int BotAllocWeaponState (void)
Definition at line 450 of file be_ai_weap.c.
 {
     int i;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (!botweaponstates[i])
         {
             botweaponstates[i] = GetClearedMemory(sizeof(bot_weaponstate_t));
             return i;
         } //end if
     } //end for
     return 0;
 } //end of the function BotAllocWeaponState
Referenced by Init_AI_Export().
BotChooseBestFightWeapon()
int BotChooseBestFightWeapon (int weaponstate, int * inventory)
Definition at line 404 of file be_ai_weap.c.
 {
     int i, index, bestweapon;
     float weight, bestweight;
     weaponconfig_t *wc;
     bot_weaponstate_t *ws;
     ws = BotWeaponStateFromHandle(weaponstate);
     if (!ws) return 0;
     wc = weaponconfig;
     if (!weaponconfig) return 0;
     //if the bot has no weapon weight configuration
     if (!ws->weaponweightconfig) return 0;
     bestweight = 0;
     bestweapon = 0;
     for (i = 0; i < wc->numweapons; i++)
     {
         if (!wc->weaponinfo[i].valid) continue;
         index = ws->weaponweightindex[i];
         if (index < 0) continue;
         weight = FuzzyWeight(inventory, ws->weaponweightconfig, index);
         if (weight > bestweight)
         {
             bestweight = weight;
             bestweapon = i;
         } //end if
     } //end for
     return bestweapon;
 } //end of the function BotChooseBestFightWeapon
Referenced by Init_AI_Export().
BotFreeWeaponState()
void BotFreeWeaponState (int weaponstate)
Definition at line 470 of file be_ai_weap.c.
 {
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "weapon state handle %d out of range\n", handle);
         return;
     } //end if
     if (!botweaponstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid weapon state %d\n", handle);
         return;
     } //end if
     BotFreeWeaponWeights(handle);
     FreeMemory(botweaponstates[handle]);
     botweaponstates[handle] = NULL;
 } //end of the function BotFreeWeaponState
Referenced by BotShutdownWeaponAI(), and Init_AI_Export().
BotGetWeaponInfo()
void BotGetWeaponInfo (int weaponstate, int weapon, weaponinfo_t * weaponinfo)
Definition at line 388 of file be_ai_weap.c.
 {
     bot_weaponstate_t *ws;
     if (!BotValidWeaponNumber(weapon)) return;
     ws = BotWeaponStateFromHandle(weaponstate);
     if (!ws) return;
     if (!weaponconfig) return;
     Com_Memcpy(weaponinfo, &weaponconfig->weaponinfo[weapon], sizeof(weaponinfo_t));
 } //end of the function BotGetWeaponInfo
Referenced by Init_AI_Export().
BotLoadWeaponWeights()
int BotLoadWeaponWeights (int weaponstate, char * filename)
Definition at line 364 of file be_ai_weap.c.
 {
     bot_weaponstate_t *ws;
     ws = BotWeaponStateFromHandle(weaponstate);
     if (!ws) return BLERR_CANNOTLOADWEAPONWEIGHTS;
     BotFreeWeaponWeights(weaponstate);
     //
     ws->weaponweightconfig = ReadWeightConfig(filename);
     if (!ws->weaponweightconfig)
     {
         botimport.Print(PRT_FATAL, "couldn't load weapon config %s\n", filename);
         return BLERR_CANNOTLOADWEAPONWEIGHTS;
     } //end if
     if (!weaponconfig) return BLERR_CANNOTLOADWEAPONCONFIG;
     ws->weaponweightindex = WeaponWeightIndex(ws->weaponweightconfig, weaponconfig);
     return BLERR_NOERROR;
 } //end of the function BotLoadWeaponWeights
Referenced by Init_AI_Export().
BotResetWeaponState()
void BotResetWeaponState (int weaponstate)
Definition at line 441 of file be_ai_weap.c.
 {
 } //end of the function BotResetWeaponState
Referenced by Init_AI_Export().
BotSetupWeaponAI()
int BotSetupWeaponAI (void)
Definition at line 492 of file be_ai_weap.c.
 {
     char *file;
     file = LibVarString("weaponconfig", "weapons.c");
     weaponconfig = LoadWeaponConfig(file);
     if (!weaponconfig)
     {
         botimport.Print(PRT_FATAL, "couldn't load the weapon config\n");
         return BLERR_CANNOTLOADWEAPONCONFIG;
     } //end if
 #ifdef DEBUG_AI_WEAP
     DumpWeaponConfig(weaponconfig);
 #endif //DEBUG_AI_WEAP
     //
     return BLERR_NOERROR;
 } //end of the function BotSetupWeaponAI
Referenced by Export_BotLibSetup().
BotShutdownWeaponAI()
void BotShutdownWeaponAI (void)
Definition at line 516 of file be_ai_weap.c.
 {
     int i;
     if (weaponconfig) FreeMemory(weaponconfig);
     weaponconfig = NULL;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (botweaponstates[i])
         {
             BotFreeWeaponState(i);
         } //end if
     } //end for
 } //end of the function BotShutdownWeaponAI
Referenced by Export_BotLibShutdown().