ioquake3 doxygen: C:/entry/dev/ioq3/code/botlib/be_ai_goal.c File Reference
be_ai_goal.c File Reference
#include "../qcommon/q_shared.h"
#include "l_utils.h"
#include "l_libvar.h"
#include "l_memory.h"
#include "l_log.h"
#include "l_script.h"
#include "l_precomp.h"
#include "l_struct.h"
#include "aasfile.h"
#include "botlib.h"
#include "be_aas.h"
#include "be_aas_funcs.h"
#include "be_interface.h"
#include "be_ai_weight.h"
#include "be_ai_goal.h"
#include "be_ai_move.h"
Classes
struct maplocation_s
struct campspot_s
struct levelitem_s
struct iteminfo_s
struct itemconfig_s
struct bot_goalstate_s
Macros
#define UNDECIDEDFUZZY
#define DROPPEDWEIGHT
#define AVOID_MINIMUM_TIME 10
#define AVOID_DEFAULT_TIME 30
#define AVOID_DROPPED_TIME 10
#define TRAVELTIME_SCALE 0.01
#define IFL_NOTFREE 1
not in free for all.
#define IFL_NOTTEAM 2
not in team play.
#define IFL_NOTSINGLE 4
not in single player.
#define IFL_NOTBOT 8
bot should never go for this.
#define IFL_ROAM 16
bot roam goal.
#define ITEMINFO_OFS(x) (size_t)&(((iteminfo_t *)0)->x)
#define ET_ITEM 2
Typedefs
typedef struct maplocation_s maplocation_t
typedef struct campspot_s campspot_t
typedef struct levelitem_s levelitem_t
typedef struct iteminfo_s iteminfo_t
typedef struct itemconfig_s itemconfig_t
typedef struct bot_goalstate_s bot_goalstate_t
Enumerations
enum gametype_t {
GT_FFA, GT_TOURNAMENT, GT_SINGLE_PLAYER, GT_TEAM,
GT_CTF, GT_MAX_GAME_TYPE, GT_FFA, GT_TOURNAMENT,
GT_SINGLE_PLAYER, GT_TEAM, GT_CTF, GT_1FCTF,
GT_OBELISK, GT_HARVESTER, GT_MAX_GAME_TYPE
}
Game types.
Functions
bot_goalstate_t * BotGoalStateFromHandle (int handle)
void BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
void BotSaveGoalFuzzyLogic (int goalstate, char *filename)
void BotMutateGoalFuzzyLogic (int goalstate, float range)
itemconfig_t * LoadItemConfig (char *filename)
int * ItemWeightIndex (weightconfig_t *iwc, itemconfig_t *ic)
void InitLevelItemHeap (void)
levelitem_t * AllocLevelItem (void)
void FreeLevelItem (levelitem_t *li)
void AddLevelItemToList (levelitem_t *li)
void RemoveLevelItemFromList (levelitem_t *li)
void BotFreeInfoEntities (void)
void BotInitInfoEntities (void)
void BotInitLevelItems (void)
void BotGoalName (int number, char *name, int size)
void BotResetAvoidGoals (int goalstate)
void BotDumpAvoidGoals (int goalstate)
void BotAddToAvoidGoals (bot_goalstate_t *gs, int number, float avoidtime)
void BotRemoveFromAvoidGoals (int goalstate, int number)
float BotAvoidGoalTime (int goalstate, int number)
void BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
int BotGetLevelItemGoal (int index, char *name, bot_goal_t *goal)
int BotGetMapLocationGoal (char *name, bot_goal_t *goal)
int BotGetNextCampSpotGoal (int num, bot_goal_t *goal)
void BotFindEntityForLevelItem (levelitem_t *li)
void BotUpdateEntityItems (void)
void BotDumpGoalStack (int goalstate)
void BotPushGoal (int goalstate, bot_goal_t *goal)
void BotPopGoal (int goalstate)
void BotEmptyGoalStack (int goalstate)
int BotGetTopGoal (int goalstate, bot_goal_t *goal)
int BotGetSecondGoal (int goalstate, bot_goal_t *goal)
int BotChooseLTGItem (int goalstate, vec3_t origin, int *inventory, int travelflags)
int BotChooseNBGItem (int goalstate, vec3_t origin, int *inventory, int travelflags, bot_goal_t *ltg, float maxtime)
int BotTouchingGoal (vec3_t origin, bot_goal_t *goal)
int BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, bot_goal_t *goal)
void BotResetGoalState (int goalstate)
int BotLoadItemWeights (int goalstate, char *filename)
void BotFreeItemWeights (int goalstate)
int BotAllocGoalState (int client)
void BotFreeGoalState (int handle)
int BotSetupGoalAI (void)
void BotShutdownGoalAI (void)
Variables
fielddef_t iteminfo_fields []
structdef_t iteminfo_struct
bot_goalstate_t * botgoalstates [MAX_CLIENTS+1]
itemconfig_t * itemconfig = NULL
levelitem_t * levelitemheap = NULL
levelitem_t * freelevelitems = NULL
levelitem_t * levelitems = NULL
int numlevelitems = 0
maplocation_t * maplocations = NULL
campspot_t * campspots = NULL
int g_gametype = 0
libvar_t * droppedweight = NULL
Macro Definition Documentation
AVOID_DEFAULT_TIME
#define AVOID_DEFAULT_TIME 30
Definition at line 57 of file be_ai_goal.c.
AVOID_DROPPED_TIME
#define AVOID_DROPPED_TIME 10
Definition at line 59 of file be_ai_goal.c.
AVOID_MINIMUM_TIME
#define AVOID_MINIMUM_TIME 10
Definition at line 55 of file be_ai_goal.c.
DROPPEDWEIGHT
#define DROPPEDWEIGHT
Definition at line 53 of file be_ai_goal.c.
ET_ITEM
#define ET_ITEM 2
Definition at line 1018 of file be_ai_goal.c.
IFL_NOTBOT
#define IFL_NOTBOT 8
bot should never go for this.
Definition at line 66 of file be_ai_goal.c.
IFL_NOTFREE
#define IFL_NOTFREE 1
not in free for all.
Definition at line 63 of file be_ai_goal.c.
IFL_NOTSINGLE
#define IFL_NOTSINGLE 4
not in single player.
Definition at line 65 of file be_ai_goal.c.
IFL_NOTTEAM
#define IFL_NOTTEAM 2
not in team play.
Definition at line 64 of file be_ai_goal.c.
IFL_ROAM
#define IFL_ROAM 16
bot roam goal.
Definition at line 67 of file be_ai_goal.c.
ITEMINFO_OFS
#define ITEMINFO_OFS (x) (size_t)&(((iteminfo_t *)0)->x)
Definition at line 141 of file be_ai_goal.c.
TRAVELTIME_SCALE
#define TRAVELTIME_SCALE 0.01
Definition at line 61 of file be_ai_goal.c.
UNDECIDEDFUZZY
#define UNDECIDEDFUZZY
Definition at line 51 of file be_ai_goal.c.
Typedef Documentation
bot_goalstate_t
typedef struct bot_goalstate_s bot_goalstate_t
campspot_t
typedef struct campspot_s campspot_t
itemconfig_t
typedef struct itemconfig_s itemconfig_t
iteminfo_t
typedef struct iteminfo_s iteminfo_t
levelitem_t
typedef struct levelitem_s levelitem_t
maplocation_t
typedef struct maplocation_s maplocation_t
Enumeration Type Documentation
gametype_t
enum gametype_t
Game types.
FIXME: these are game specific.
Enumerator
GT_FFA
free for all.
GT_TOURNAMENT
one on one tournament.
GT_SINGLE_PLAYER
single player tournament.
GT_TEAM
team deathmatch.
GT_CTF
capture the flag.
GT_MAX_GAME_TYPE
GT_FFA
free for all.
GT_TOURNAMENT
one on one tournament.
GT_SINGLE_PLAYER
single player tournament.
GT_TEAM
team deathmatch.
GT_CTF
capture the flag.
GT_1FCTF
GT_OBELISK
GT_HARVESTER
GT_MAX_GAME_TYPE
Definition at line 96 of file be_ai_goal.c.
              {
     GT_FFA,
     GT_TOURNAMENT,
     GT_SINGLE_PLAYER,
     //-- team games go after this --
     GT_TEAM,
     GT_CTF,
 #ifdef MISSIONPACK
     GT_1FCTF,
     GT_OBELISK,
     GT_HARVESTER,
 #endif
     GT_MAX_GAME_TYPE
 } gametype_t;
Function Documentation
AddLevelItemToList()
void AddLevelItemToList (levelitem_t * li)
Definition at line 433 of file be_ai_goal.c.
 {
     if (levelitems) levelitems->prev = li;
     li->prev = NULL;
     li->next = levelitems;
     levelitems = li;
 } //end of the function AddLevelItemToList
References levelitems, levelitem_s::next, NULL, and levelitem_s::prev.
Referenced by BotInitLevelItems(), and BotUpdateEntityItems().
AllocLevelItem()
levelitem_t* AllocLevelItem (void)
Definition at line 401 of file be_ai_goal.c.
 {
     levelitem_t *li;
     li = freelevelitems;
     if (!li)
     {
         botimport.Print(PRT_FATAL, "out of level items\n");
         return NULL;
     } //end if
     //
     freelevelitems = freelevelitems->next;
     Com_Memset(li, 0, sizeof(levelitem_t));
     return li;
 } //end of the function AllocLevelItem
References botimport, Com_Memset, freelevelitems, levelitem_s::next, NULL, and PRT_FATAL.
Referenced by BotInitLevelItems(), and BotUpdateEntityItems().
BotAddToAvoidGoals()
void BotAddToAvoidGoals (bot_goalstate_t * gs, int number, float avoidtime)
Definition at line 746 of file be_ai_goal.c.
 {
     int i;
     for (i = 0; i < MAX_AVOIDGOALS; i++)
     {
         //if the avoid goal is already stored
         if (gs->avoidgoals[i] == number)
         {
             gs->avoidgoals[i] = number;
             gs->avoidgoaltimes[i] = AAS_Time() + avoidtime;
             return;
         } //end if
     } //end for
     for (i = 0; i < MAX_AVOIDGOALS; i++)
     {
         //if this avoid goal has expired
         if (gs->avoidgoaltimes[i] < AAS_Time())
         {
             gs->avoidgoals[i] = number;
             gs->avoidgoaltimes[i] = AAS_Time() + avoidtime;
             return;
         } //end if
     } //end for
 } //end of the function BotAddToAvoidGoals
References AAS_Time(), bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, and MAX_AVOIDGOALS.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), and BotSetAvoidGoalTime().
BotAllocGoalState()
int BotAllocGoalState (int client)
Definition at line 1742 of file be_ai_goal.c.
 {
     int i;
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (!botgoalstates[i])
         {
             botgoalstates[i] = GetClearedMemory(sizeof(bot_goalstate_t));
             botgoalstates[i]->client = client;
             return i;
         } //end if
     } //end for
     return 0;
 } //end of the function BotAllocGoalState
References botgoalstates, bot_goalstate_s::client, GetClearedMemory(), and MAX_CLIENTS.
Referenced by Init_AI_Export().
BotAvoidGoalTime()
float BotAvoidGoalTime (int goalstate, int number)
Definition at line 801 of file be_ai_goal.c.
 {
     int i;
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return 0;
     //don't use the goals the bot wants to avoid
     for (i = 0; i < MAX_AVOIDGOALS; i++)
     {
         if (gs->avoidgoals[i] == number && gs->avoidgoaltimes[i] >= AAS_Time())
         {
             return gs->avoidgoaltimes[i] - AAS_Time();
         } //end if
     } //end for
     return 0;
 } //end of the function BotAvoidGoalTime
References AAS_Time(), bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalStateFromHandle(), and MAX_AVOIDGOALS.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), and Init_AI_Export().
BotChooseLTGItem()
int BotChooseLTGItem (int goalstate, vec3_t origin, int * inventory, int travelflags)
Definition at line 1295 of file be_ai_goal.c.
 {
     int areanum, t, weightnum;
     float weight, bestweight, avoidtime;
     iteminfo_t *iteminfo;
     itemconfig_t *ic;
     levelitem_t *li, *bestitem;
     bot_goal_t goal;
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs)
         return qfalse;
     if (!gs->itemweightconfig)
         return qfalse;
     //get the area the bot is in
     areanum = BotReachabilityArea(origin, gs->client);
     //if the bot is in solid or if the area the bot is in has no reachability links
     if (!areanum || !AAS_AreaReachability(areanum))
     {
         //use the last valid area the bot was in
         areanum = gs->lastreachabilityarea;
     } //end if
     //remember the last area with reachabilities the bot was in
     gs->lastreachabilityarea = areanum;
     //if still in solid
     if (!areanum)
         return qfalse;
     //the item configuration
     ic = itemconfig;
     if (!itemconfig)
         return qfalse;
     //best weight and item so far
     bestweight = 0;
     bestitem = NULL;
     Com_Memset(&goal, 0, sizeof(bot_goal_t));
     //go through the items in the level
     for (li = levelitems; li; li = li->next)
     {
         if (g_gametype == GT_SINGLE_PLAYER) {
             if (li->flags & IFL_NOTSINGLE)
                 continue;
         }
         else if (g_gametype >= GT_TEAM) {
             if (li->flags & IFL_NOTTEAM)
                 continue;
         }
         else {
             if (li->flags & IFL_NOTFREE)
                 continue;
         }
         if (li->flags & IFL_NOTBOT)
             continue;
         //if the item is not in a possible goal area
         if (!li->goalareanum)
             continue;
         //FIXME: is this a good thing? added this for items that never spawned into the game (f.i. CTF flags in obelisk)
         if (!li->entitynum && !(li->flags & IFL_ROAM))
             continue;
         //get the fuzzy weight function for this item
         iteminfo = &ic->iteminfo[li->iteminfo];
         weightnum = gs->itemweightindex[iteminfo->number];
         if (weightnum < 0)
             continue;
 #ifdef UNDECIDEDFUZZY
         weight = FuzzyWeightUndecided(inventory, gs->itemweightconfig, weightnum);
 #else
         weight = FuzzyWeight(inventory, gs->itemweightconfig, weightnum);
 #endif //UNDECIDEDFUZZY
 #ifdef DROPPEDWEIGHT
         //HACK: to make dropped items more attractive
         if (li->timeout)
             weight += droppedweight->value;
 #endif //DROPPEDWEIGHT
         //use weight scale for item_botroam
         if (li->flags & IFL_ROAM) weight *= li->weight;
         //
         if (weight > 0)
         {
             //get the travel time towards the goal area
             t = AAS_AreaTravelTimeToGoalArea(areanum, origin, li->goalareanum, travelflags);
             //if the goal is reachable
             if (t > 0)
             {
                 //if this item won't respawn before we get there
                 avoidtime = BotAvoidGoalTime(goalstate, li->number);
                 if (avoidtime - t * 0.009 > 0)
                     continue;
                 //
                 weight /= (float) t * TRAVELTIME_SCALE;
                 //
                 if (weight > bestweight)
                 {
                     bestweight = weight;
                     bestitem = li;
                 } //end if
             } //end if
         } //end if
     } //end for
     //if no goal item found
     if (!bestitem)
     {
         /*
         //if not in lava or slime
         if (!AAS_AreaLava(areanum) && !AAS_AreaSlime(areanum))
         {
             if (AAS_RandomGoalArea(areanum, travelflags, &goal.areanum, goal.origin))
             {
                 VectorSet(goal.mins, -15, -15, -15);
                 VectorSet(goal.maxs, 15, 15, 15);
                 goal.entitynum = 0;
                 goal.number = 0;
                 goal.flags = GFL_ROAM;
                 goal.iteminfo = 0;
                 //push the goal on the stack
                 BotPushGoal(goalstate, &goal);
                 //
 #ifdef DEBUG
                 botimport.Print(PRT_MESSAGE, "chosen roam goal area %d\n", goal.areanum);
 #endif //DEBUG
                 return qtrue;
             } //end if
         } //end if
         */
         return qfalse;
     } //end if
     //create a bot goal for this item
     iteminfo = &ic->iteminfo[bestitem->iteminfo];
     VectorCopy(bestitem->goalorigin, goal.origin);
     VectorCopy(iteminfo->mins, goal.mins);
     VectorCopy(iteminfo->maxs, goal.maxs);
     goal.areanum = bestitem->goalareanum;
     goal.entitynum = bestitem->entitynum;
     goal.number = bestitem->number;
     goal.flags = GFL_ITEM;
     if (bestitem->timeout)
         goal.flags |= GFL_DROPPED;
     if (bestitem->flags & IFL_ROAM)
         goal.flags |= GFL_ROAM;
     goal.iteminfo = bestitem->iteminfo;
     //if it's a dropped item
     if (bestitem->timeout)
     {
         avoidtime = AVOID_DROPPED_TIME;
     } //end if
     else
     {
         avoidtime = iteminfo->respawntime;
         if (!avoidtime)
             avoidtime = AVOID_DEFAULT_TIME;
         if (avoidtime < AVOID_MINIMUM_TIME)
             avoidtime = AVOID_MINIMUM_TIME;
     } //end else
     //add the chosen goal to the goals to avoid for a while
     BotAddToAvoidGoals(gs, bestitem->number, avoidtime);
     //push the goal on the stack
     BotPushGoal(goalstate, &goal);
     //
     return qtrue;
 } //end of the function BotChooseLTGItem
References AAS_AreaReachability(), AAS_AreaTravelTimeToGoalArea(), bot_goal_s::areanum, AVOID_DEFAULT_TIME, AVOID_DROPPED_TIME, AVOID_MINIMUM_TIME, BotAddToAvoidGoals(), BotAvoidGoalTime(), BotGoalStateFromHandle(), BotPushGoal(), BotReachabilityArea(), bot_goalstate_s::client, Com_Memset, droppedweight, bot_goal_s::entitynum, levelitem_s::entitynum, bot_goal_s::flags, levelitem_s::flags, FuzzyWeight(), FuzzyWeightUndecided(), g_gametype, GFL_DROPPED, GFL_ITEM, GFL_ROAM, levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, IFL_ROAM, itemconfig, bot_goal_s::iteminfo, levelitem_s::iteminfo, itemconfig_s::iteminfo, bot_goalstate_s::itemweightconfig, bot_goalstate_s::itemweightindex, bot_goalstate_s::lastreachabilityarea, levelitems, bot_goal_s::maxs, iteminfo_s::maxs, bot_goal_s::mins, iteminfo_s::mins, levelitem_s::next, NULL, bot_goal_s::number, levelitem_s::number, iteminfo_s::number, bot_goal_s::origin, qfalse, qtrue, iteminfo_s::respawntime, t, levelitem_s::timeout, TRAVELTIME_SCALE, libvar_s::value, VectorCopy, and levelitem_s::weight.
Referenced by Init_AI_Export().
BotChooseNBGItem()
int BotChooseNBGItem (int goalstate, vec3_t origin, int * inventory, int travelflags, bot_goal_t * ltg, float maxtime)
Definition at line 1462 of file be_ai_goal.c.
 {
     int areanum, t, weightnum, ltg_time;
     float weight, bestweight, avoidtime;
     iteminfo_t *iteminfo;
     itemconfig_t *ic;
     levelitem_t *li, *bestitem;
     bot_goal_t goal;
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs)
         return qfalse;
     if (!gs->itemweightconfig)
         return qfalse;
     //get the area the bot is in
     areanum = BotReachabilityArea(origin, gs->client);
     //if the bot is in solid or if the area the bot is in has no reachability links
     if (!areanum || !AAS_AreaReachability(areanum))
     {
         //use the last valid area the bot was in
         areanum = gs->lastreachabilityarea;
     } //end if
     //remember the last area with reachabilities the bot was in
     gs->lastreachabilityarea = areanum;
     //if still in solid
     if (!areanum)
         return qfalse;
     //
     if (ltg) ltg_time = AAS_AreaTravelTimeToGoalArea(areanum, origin, ltg->areanum, travelflags);
     else ltg_time = 99999;
     //the item configuration
     ic = itemconfig;
     if (!itemconfig)
         return qfalse;
     //best weight and item so far
     bestweight = 0;
     bestitem = NULL;
     Com_Memset(&goal, 0, sizeof(bot_goal_t));
     //go through the items in the level
     for (li = levelitems; li; li = li->next)
     {
         if (g_gametype == GT_SINGLE_PLAYER) {
             if (li->flags & IFL_NOTSINGLE)
                 continue;
         }
         else if (g_gametype >= GT_TEAM) {
             if (li->flags & IFL_NOTTEAM)
                 continue;
         }
         else {
             if (li->flags & IFL_NOTFREE)
                 continue;
         }
         if (li->flags & IFL_NOTBOT)
             continue;
         //if the item is in a possible goal area
         if (!li->goalareanum)
             continue;
         //FIXME: is this a good thing? added this for items that never spawned into the game (f.i. CTF flags in obelisk)
         if (!li->entitynum && !(li->flags & IFL_ROAM))
             continue;
         //get the fuzzy weight function for this item
         iteminfo = &ic->iteminfo[li->iteminfo];
         weightnum = gs->itemweightindex[iteminfo->number];
         if (weightnum < 0)
             continue;
         //
 #ifdef UNDECIDEDFUZZY
         weight = FuzzyWeightUndecided(inventory, gs->itemweightconfig, weightnum);
 #else
         weight = FuzzyWeight(inventory, gs->itemweightconfig, weightnum);
 #endif //UNDECIDEDFUZZY
 #ifdef DROPPEDWEIGHT
         //HACK: to make dropped items more attractive
         if (li->timeout)
             weight += droppedweight->value;
 #endif //DROPPEDWEIGHT
         //use weight scale for item_botroam
         if (li->flags & IFL_ROAM) weight *= li->weight;
         //
         if (weight > 0)
         {
             //get the travel time towards the goal area
             t = AAS_AreaTravelTimeToGoalArea(areanum, origin, li->goalareanum, travelflags);
             //if the goal is reachable
             if (t > 0 && t < maxtime)
             {
                 //if this item won't respawn before we get there
                 avoidtime = BotAvoidGoalTime(goalstate, li->number);
                 if (avoidtime - t * 0.009 > 0)
                     continue;
                 //
                 weight /= (float) t * TRAVELTIME_SCALE;
                 //
                 if (weight > bestweight)
                 {
                     t = 0;
                     if (ltg && !li->timeout)
                     {
                         //get the travel time from the goal to the long term goal
                         t = AAS_AreaTravelTimeToGoalArea(li->goalareanum, li->goalorigin, ltg->areanum, travelflags);
                     } //end if
                     //if the travel back is possible and doesn't take too long
                     if (t <= ltg_time)
                     {
                         bestweight = weight;
                         bestitem = li;
                     } //end if
                 } //end if
             } //end if
         } //end if
     } //end for
     //if no goal item found
     if (!bestitem)
         return qfalse;
     //create a bot goal for this item
     iteminfo = &ic->iteminfo[bestitem->iteminfo];
     VectorCopy(bestitem->goalorigin, goal.origin);
     VectorCopy(iteminfo->mins, goal.mins);
     VectorCopy(iteminfo->maxs, goal.maxs);
     goal.areanum = bestitem->goalareanum;
     goal.entitynum = bestitem->entitynum;
     goal.number = bestitem->number;
     goal.flags = GFL_ITEM;
     if (bestitem->timeout)
         goal.flags |= GFL_DROPPED;
     if (bestitem->flags & IFL_ROAM)
         goal.flags |= GFL_ROAM;
     goal.iteminfo = bestitem->iteminfo;
     //if it's a dropped item
     if (bestitem->timeout)
     {
         avoidtime = AVOID_DROPPED_TIME;
     } //end if
     else
     {
         avoidtime = iteminfo->respawntime;
         if (!avoidtime)
             avoidtime = AVOID_DEFAULT_TIME;
         if (avoidtime < AVOID_MINIMUM_TIME)
             avoidtime = AVOID_MINIMUM_TIME;
     } //end else
     //add the chosen goal to the goals to avoid for a while
     BotAddToAvoidGoals(gs, bestitem->number, avoidtime);
     //push the goal on the stack
     BotPushGoal(goalstate, &goal);
     //
     return qtrue;
 } //end of the function BotChooseNBGItem
References AAS_AreaReachability(), AAS_AreaTravelTimeToGoalArea(), bot_goal_s::areanum, AVOID_DEFAULT_TIME, AVOID_DROPPED_TIME, AVOID_MINIMUM_TIME, BotAddToAvoidGoals(), BotAvoidGoalTime(), BotGoalStateFromHandle(), BotPushGoal(), BotReachabilityArea(), bot_goalstate_s::client, Com_Memset, droppedweight, bot_goal_s::entitynum, levelitem_s::entitynum, bot_goal_s::flags, levelitem_s::flags, FuzzyWeight(), FuzzyWeightUndecided(), g_gametype, GFL_DROPPED, GFL_ITEM, GFL_ROAM, levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, IFL_ROAM, itemconfig, bot_goal_s::iteminfo, levelitem_s::iteminfo, itemconfig_s::iteminfo, bot_goalstate_s::itemweightconfig, bot_goalstate_s::itemweightindex, bot_goalstate_s::lastreachabilityarea, levelitems, bot_goal_s::maxs, iteminfo_s::maxs, bot_goal_s::mins, iteminfo_s::mins, levelitem_s::next, NULL, bot_goal_s::number, levelitem_s::number, iteminfo_s::number, bot_goal_s::origin, qfalse, qtrue, iteminfo_s::respawntime, t, levelitem_s::timeout, TRAVELTIME_SCALE, libvar_s::value, VectorCopy, and levelitem_s::weight.
Referenced by Init_AI_Export().
BotDumpAvoidGoals()
void BotDumpAvoidGoals (int goalstate)
Definition at line 722 of file be_ai_goal.c.
 {
     int i;
     bot_goalstate_t *gs;
     char name[32];
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     for (i = 0; i < MAX_AVOIDGOALS; i++)
     {
         if (gs->avoidgoaltimes[i] >= AAS_Time())
         {
             BotGoalName(gs->avoidgoals[i], name, 32);
             Log_Write("avoid goal %s, number %d for %f seconds", name,
                 gs->avoidgoals[i], gs->avoidgoaltimes[i] - AAS_Time());
         } //end if
     } //end for
 } //end of the function BotDumpAvoidGoals
References AAS_Time(), bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalName(), BotGoalStateFromHandle(), Log_Write(), and MAX_AVOIDGOALS.
Referenced by Init_AI_Export().
BotDumpGoalStack()
void BotDumpGoalStack (int goalstate)
Definition at line 1193 of file be_ai_goal.c.
 {
     int i;
     bot_goalstate_t *gs;
     char name[32];
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     for (i = 1; i <= gs->goalstacktop; i++)
     {
         BotGoalName(gs->goalstack[i].number, name, 32);
         Log_Write("%d: %s", i, name);
     } //end for
 } //end of the function BotDumpGoalStack
References BotGoalName(), BotGoalStateFromHandle(), bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, Log_Write(), and bot_goal_s::number.
Referenced by BotPushGoal(), and Init_AI_Export().
BotEmptyGoalStack()
void BotEmptyGoalStack (int goalstate)
Definition at line 1248 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     gs->goalstacktop = 0;
 } //end of the function BotEmptyGoalStack
References BotGoalStateFromHandle(), and bot_goalstate_s::goalstacktop.
Referenced by Init_AI_Export().
BotFindEntityForLevelItem()
void BotFindEntityForLevelItem (levelitem_t * li)
Definition at line 976 of file be_ai_goal.c.
 {
     int ent, modelindex;
     itemconfig_t *ic;
     aas_entityinfo_t entinfo;
     vec3_t dir;
     ic = itemconfig;
     if (!itemconfig) return;
     for (ent = AAS_NextEntity(0); ent; ent = AAS_NextEntity(ent))
     {
         //get the model index of the entity
         modelindex = AAS_EntityModelindex(ent);
         //
         if (!modelindex) continue;
         //get info about the entity
         AAS_EntityInfo(ent, &entinfo);
         //if the entity is still moving
         if (entinfo.origin[0] != entinfo.lastvisorigin[0] ||
                 entinfo.origin[1] != entinfo.lastvisorigin[1] ||
                 entinfo.origin[2] != entinfo.lastvisorigin[2]) continue;
         //
         if (ic->iteminfo[li->iteminfo].modelindex == modelindex)
         {
             //check if the entity is very close
             VectorSubtract(li->origin, entinfo.origin, dir);
             if (VectorLength(dir) < 30)
             {
                 //found an entity for this level item
                 li->entitynum = ent;
             } //end if
         } //end if
     } //end for
 } //end of the function BotFindEntityForLevelItem
References AAS_EntityInfo(), AAS_EntityModelindex(), AAS_NextEntity(), levelitem_s::entitynum, itemconfig, levelitem_s::iteminfo, itemconfig_s::iteminfo, aas_entityinfo_s::lastvisorigin, iteminfo_s::modelindex, levelitem_s::origin, aas_entityinfo_s::origin, VectorLength(), and VectorSubtract.
BotFreeGoalState()
void BotFreeGoalState (int handle)
Definition at line 1763 of file be_ai_goal.c.
 {
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "goal state handle %d out of range\n", handle);
         return;
     } //end if
     if (!botgoalstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid goal state handle %d\n", handle);
         return;
     } //end if
     BotFreeItemWeights(handle);
     FreeMemory(botgoalstates[handle]);
     botgoalstates[handle] = NULL;
 } //end of the function BotFreeGoalState
References BotFreeItemWeights(), botgoalstates, botimport, FreeMemory(), MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotShutdownGoalAI(), and Init_AI_Export().
BotFreeInfoEntities()
void BotFreeInfoEntities (void)
Definition at line 458 of file be_ai_goal.c.
 {
     maplocation_t *ml, *nextml;
     campspot_t *cs, *nextcs;
     for (ml = maplocations; ml; ml = nextml)
     {
         nextml = ml->next;
         FreeMemory(ml);
     } //end for
     maplocations = NULL;
     for (cs = campspots; cs; cs = nextcs)
     {
         nextcs = cs->next;
         FreeMemory(cs);
     } //end for
     campspots = NULL;
 } //end of the function BotFreeInfoEntities
References campspots, FreeMemory(), maplocations, maplocation_s::next, campspot_s::next, and NULL.
Referenced by BotInitInfoEntities(), and BotShutdownGoalAI().
BotFreeItemWeights()
void BotFreeItemWeights (int goalstate)
Definition at line 1727 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     if (gs->itemweightconfig) FreeWeightConfig(gs->itemweightconfig);
     if (gs->itemweightindex) FreeMemory(gs->itemweightindex);
 } //end of the function BotFreeItemWeights
References BotGoalStateFromHandle(), FreeMemory(), FreeWeightConfig(), bot_goalstate_s::itemweightconfig, and bot_goalstate_s::itemweightindex.
Referenced by BotFreeGoalState(), and Init_AI_Export().
BotGetLevelItemGoal()
int BotGetLevelItemGoal (int index, char * name, bot_goal_t * goal)
Definition at line 863 of file be_ai_goal.c.
 {
     levelitem_t *li;
     if (!itemconfig) return -1;
     li = levelitems;
     if (index >= 0)
     {
         for (; li; li = li->next)
         {
             if (li->number == index)
             {
                 li = li->next;
                 break;
             } //end if
         } //end for
     } //end for
     for (; li; li = li->next)
     {
         //
         if (g_gametype == GT_SINGLE_PLAYER) {
             if (li->flags & IFL_NOTSINGLE) continue;
         }
         else if (g_gametype >= GT_TEAM) {
             if (li->flags & IFL_NOTTEAM) continue;
         }
         else {
             if (li->flags & IFL_NOTFREE) continue;
         }
         if (li->flags & IFL_NOTBOT) continue;
         //
         if (!Q_stricmp(name, itemconfig->iteminfo[li->iteminfo].name))
         {
             goal->areanum = li->goalareanum;
             VectorCopy(li->goalorigin, goal->origin);
             goal->entitynum = li->entitynum;
             VectorCopy(itemconfig->iteminfo[li->iteminfo].mins, goal->mins);
             VectorCopy(itemconfig->iteminfo[li->iteminfo].maxs, goal->maxs);
             goal->number = li->number;
             goal->flags = GFL_ITEM;
             if (li->timeout) goal->flags |= GFL_DROPPED;
             goal->iteminfo = li->iteminfo;
             //botimport.Print(PRT_MESSAGE, "found li %s\n", itemconfig->iteminfo[li->iteminfo].name);
             return li->number;
         } //end if
     } //end for
     return -1;
 } //end of the function BotGetLevelItemGoal
References bot_goal_s::areanum, bot_goal_s::entitynum, levelitem_s::entitynum, bot_goal_s::flags, levelitem_s::flags, g_gametype, GFL_DROPPED, GFL_ITEM, levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, itemconfig, bot_goal_s::iteminfo, levelitem_s::iteminfo, itemconfig_s::iteminfo, levelitems, bot_goal_s::maxs, iteminfo_s::maxs, bot_goal_s::mins, iteminfo_s::mins, iteminfo_s::name, levelitem_s::next, bot_goal_s::number, levelitem_s::number, bot_goal_s::origin, Q_stricmp(), levelitem_s::timeout, and VectorCopy.
Referenced by Init_AI_Export().
BotGetMapLocationGoal()
int BotGetMapLocationGoal (char * name, bot_goal_t * goal)
Definition at line 917 of file be_ai_goal.c.
 {
     maplocation_t *ml;
     vec3_t mins = {-8, -8, -8}, maxs = {8, 8, 8};
     for (ml = maplocations; ml; ml = ml->next)
     {
         if (!Q_stricmp(ml->name, name))
         {
             goal->areanum = ml->areanum;
             VectorCopy(ml->origin, goal->origin);
             goal->entitynum = 0;
             VectorCopy(mins, goal->mins);
             VectorCopy(maxs, goal->maxs);
             goal->number = 0;
             goal->flags = 0;
             goal->iteminfo = 0;
             return qtrue;
         } //end if
     } //end for
     return qfalse;
 } //end of the function BotGetMapLocationGoal
References bot_goal_s::areanum, maplocation_s::areanum, bot_goal_s::entitynum, bot_goal_s::flags, bot_goal_s::iteminfo, maplocations, bot_goal_s::maxs, bot_goal_s::mins, maplocation_s::name, maplocation_s::next, bot_goal_s::number, bot_goal_s::origin, maplocation_s::origin, Q_stricmp(), qfalse, qtrue, and VectorCopy.
Referenced by Init_AI_Export().
BotGetNextCampSpotGoal()
int BotGetNextCampSpotGoal (int num, bot_goal_t * goal)
Definition at line 945 of file be_ai_goal.c.
 {
     int i;
     campspot_t *cs;
     vec3_t mins = {-8, -8, -8}, maxs = {8, 8, 8};
     if (num < 0) num = 0;
     i = num;
     for (cs = campspots; cs; cs = cs->next)
     {
         if (--i < 0)
         {
             goal->areanum = cs->areanum;
             VectorCopy(cs->origin, goal->origin);
             goal->entitynum = 0;
             VectorCopy(mins, goal->mins);
             VectorCopy(maxs, goal->maxs);
             goal->number = 0;
             goal->flags = 0;
             goal->iteminfo = 0;
             return num+1;
         } //end if
     } //end for
     return 0;
 } //end of the function BotGetNextCampSpotGoal
References bot_goal_s::areanum, campspot_s::areanum, campspots, bot_goal_s::entitynum, bot_goal_s::flags, bot_goal_s::iteminfo, bot_goal_s::maxs, bot_goal_s::mins, campspot_s::next, bot_goal_s::number, bot_goal_s::origin, campspot_s::origin, and VectorCopy.
Referenced by Init_AI_Export().
BotGetSecondGoal()
int BotGetSecondGoal (int goalstate, bot_goal_t * goal)
Definition at line 1278 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return qfalse;
     if (gs->goalstacktop <= 1) return qfalse;
     Com_Memcpy(goal, &gs->goalstack[gs->goalstacktop-1], sizeof(bot_goal_t));
     return qtrue;
 } //end of the function BotGetSecondGoal
References BotGoalStateFromHandle(), Com_Memcpy, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, qfalse, and qtrue.
Referenced by Init_AI_Export().
BotGetTopGoal()
int BotGetTopGoal (int goalstate, bot_goal_t * goal)
Definition at line 1262 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return qfalse;
     if (!gs->goalstacktop) return qfalse;
     Com_Memcpy(goal, &gs->goalstack[gs->goalstacktop], sizeof(bot_goal_t));
     return qtrue;
 } //end of the function BotGetTopGoal
References BotGoalStateFromHandle(), Com_Memcpy, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, qfalse, and qtrue.
Referenced by Init_AI_Export().
BotGoalName()
void BotGoalName (int number, char * name, int size)
Definition at line 685 of file be_ai_goal.c.
 {
     levelitem_t *li;
     if (!itemconfig) return;
     //
     for (li = levelitems; li; li = li->next)
     {
         if (li->number == number)
         {
             Q_strncpyz(name, itemconfig->iteminfo[li->iteminfo].name, size);
             return;
         } //end for
     } //end for
     strcpy(name, "");
 } //end of the function BotGoalName
References itemconfig, levelitem_s::iteminfo, itemconfig_s::iteminfo, levelitems, iteminfo_s::name, levelitem_s::next, levelitem_s::number, and Q_strncpyz().
Referenced by BotDumpAvoidGoals(), BotDumpGoalStack(), and Init_AI_Export().
BotGoalStateFromHandle()
bot_goalstate_t* BotGoalStateFromHandle (int handle)
Definition at line 206 of file be_ai_goal.c.
 {
     if (handle <= 0 || handle > MAX_CLIENTS)
     {
         botimport.Print(PRT_FATAL, "goal state handle %d out of range\n", handle);
         return NULL;
     } //end if
     if (!botgoalstates[handle])
     {
         botimport.Print(PRT_FATAL, "invalid goal state %d\n", handle);
         return NULL;
     } //end if
     return botgoalstates[handle];
 } //end of the function BotGoalStateFromHandle
References botgoalstates, botimport, MAX_CLIENTS, NULL, and PRT_FATAL.
Referenced by BotAvoidGoalTime(), BotChooseLTGItem(), BotChooseNBGItem(), BotDumpAvoidGoals(), BotDumpGoalStack(), BotEmptyGoalStack(), BotFreeItemWeights(), BotGetSecondGoal(), BotGetTopGoal(), BotInterbreedGoalFuzzyLogic(), BotLoadItemWeights(), BotMutateGoalFuzzyLogic(), BotPopGoal(), BotPushGoal(), BotRemoveFromAvoidGoals(), BotResetAvoidGoals(), BotResetGoalState(), and BotSetAvoidGoalTime().
BotInitInfoEntities()
void BotInitInfoEntities (void)
Definition at line 482 of file be_ai_goal.c.
 {
     char classname[MAX_EPAIRKEY];
     maplocation_t *ml;
     campspot_t *cs;
     int ent, numlocations, numcampspots;
     BotFreeInfoEntities();
     //
     numlocations = 0;
     numcampspots = 0;
     for (ent = AAS_NextBSPEntity(0); ent; ent = AAS_NextBSPEntity(ent))
     {
         if (!AAS_ValueForBSPEpairKey(ent, "classname", classname, MAX_EPAIRKEY)) continue;
         //map locations
         if (!strcmp(classname, "target_location"))
         {
             ml = (maplocation_t *) GetClearedMemory(sizeof(maplocation_t));
             AAS_VectorForBSPEpairKey(ent, "origin", ml->origin);
             AAS_ValueForBSPEpairKey(ent, "message", ml->name, sizeof(ml->name));
             ml->areanum = AAS_PointAreaNum(ml->origin);
             ml->next = maplocations;
             maplocations = ml;
             numlocations++;
         } //end if
         //camp spots
         else if (!strcmp(classname, "info_camp"))
         {
             cs = (campspot_t *) GetClearedMemory(sizeof(campspot_t));
             AAS_VectorForBSPEpairKey(ent, "origin", cs->origin);
             //cs->origin[2] += 16;
             AAS_ValueForBSPEpairKey(ent, "message", cs->name, sizeof(cs->name));
             AAS_FloatForBSPEpairKey(ent, "range", &cs->range);
             AAS_FloatForBSPEpairKey(ent, "weight", &cs->weight);
             AAS_FloatForBSPEpairKey(ent, "wait", &cs->wait);
             AAS_FloatForBSPEpairKey(ent, "random", &cs->random);
             cs->areanum = AAS_PointAreaNum(cs->origin);
             if (!cs->areanum)
             {
                 botimport.Print(PRT_MESSAGE, "camp spot at %1.1f %1.1f %1.1f in solid\n", cs->origin[0], cs->origin[1], cs->origin[2]);
                 FreeMemory(cs);
                 continue;
             } //end if
             cs->next = campspots;
             campspots = cs;
             //AAS_DrawPermanentCross(cs->origin, 4, LINECOLOR_YELLOW);
             numcampspots++;
         } //end else if
     } //end for
     if (botDeveloper)
     {
         botimport.Print(PRT_MESSAGE, "%d map locations\n", numlocations);
         botimport.Print(PRT_MESSAGE, "%d camp spots\n", numcampspots);
     } //end if
 } //end of the function BotInitInfoEntities
References AAS_FloatForBSPEpairKey(), AAS_NextBSPEntity(), AAS_PointAreaNum(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), maplocation_s::areanum, campspot_s::areanum, botDeveloper, BotFreeInfoEntities(), botimport, campspots, FreeMemory(), GetClearedMemory(), maplocations, MAX_EPAIRKEY, maplocation_s::name, campspot_s::name, maplocation_s::next, campspot_s::next, maplocation_s::origin, campspot_s::origin, PRT_MESSAGE, campspot_s::random, campspot_s::range, campspot_s::wait, and campspot_s::weight.
Referenced by BotInitLevelItems().
BotInitLevelItems()
void BotInitLevelItems (void)
Definition at line 544 of file be_ai_goal.c.
 {
     int i, spawnflags, value;
     char classname[MAX_EPAIRKEY];
     vec3_t origin, end;
     int ent, goalareanum;
     itemconfig_t *ic;
     levelitem_t *li;
     bsp_trace_t trace;
     //initialize the map locations and camp spots
     BotInitInfoEntities();
     //initialize the level item heap
     InitLevelItemHeap();
     levelitems = NULL;
     numlevelitems = 0;
     //
     ic = itemconfig;
     if (!ic) return;
     //if there's no AAS file loaded
     if (!AAS_Loaded()) return;
     //validate the modelindexes of the item info
     for (i = 0; i < ic->numiteminfo; i++)
     {
         if (!ic->iteminfo[i].modelindex)
         {
             Log_Write("item %s has modelindex 0", ic->iteminfo[i].classname);
         } //end if
     } //end for
     for (ent = AAS_NextBSPEntity(0); ent; ent = AAS_NextBSPEntity(ent))
     {
         if (!AAS_ValueForBSPEpairKey(ent, "classname", classname, MAX_EPAIRKEY)) continue;
         //
         spawnflags = 0;
         AAS_IntForBSPEpairKey(ent, "spawnflags", &spawnflags);
         //
         for (i = 0; i < ic->numiteminfo; i++)
         {
             if (!strcmp(classname, ic->iteminfo[i].classname)) break;
         } //end for
         if (i >= ic->numiteminfo)
         {
             Log_Write("entity %s unknown item\r\n", classname);
             continue;
         } //end if
         //get the origin of the item
         if (!AAS_VectorForBSPEpairKey(ent, "origin", origin))
         {
             botimport.Print(PRT_ERROR, "item %s without origin\n", classname);
             continue;
         } //end else
         //
         goalareanum = 0;
         //if it is a floating item
         if (spawnflags & 1)
         {
             //if the item is not floating in water
             if (!(AAS_PointContents(origin) & CONTENTS_WATER))
             {
                 VectorCopy(origin, end);
                 end[2] -= 32;
                 trace = AAS_Trace(origin, ic->iteminfo[i].mins, ic->iteminfo[i].maxs, end, -1, CONTENTS_SOLID|CONTENTS_PLAYERCLIP);
                 //if the item not near the ground
                 if (trace.fraction >= 1)
                 {
                     //if the item is not reachable from a jumppad
                     goalareanum = AAS_BestReachableFromJumpPadArea(origin, ic->iteminfo[i].mins, ic->iteminfo[i].maxs);
                     Log_Write("item %s reachable from jumppad area %d\r\n", ic->iteminfo[i].classname, goalareanum);
                     //botimport.Print(PRT_MESSAGE, "item %s reachable from jumppad area %d\r\n", ic->iteminfo[i].classname, goalareanum);
                     if (!goalareanum) continue;
                 } //end if
             } //end if
         } //end if
         li = AllocLevelItem();
         if (!li) return;
         //
         li->number = ++numlevelitems;
         li->timeout = 0;
         li->entitynum = 0;
         //
         li->flags = 0;
         AAS_IntForBSPEpairKey(ent, "notfree", &value);
         if (value) li->flags |= IFL_NOTFREE;
         AAS_IntForBSPEpairKey(ent, "notteam", &value);
         if (value) li->flags |= IFL_NOTTEAM;
         AAS_IntForBSPEpairKey(ent, "notsingle", &value);
         if (value) li->flags |= IFL_NOTSINGLE;
         AAS_IntForBSPEpairKey(ent, "notbot", &value);
         if (value) li->flags |= IFL_NOTBOT;
         if (!strcmp(classname, "item_botroam"))
         {
             li->flags |= IFL_ROAM;
             AAS_FloatForBSPEpairKey(ent, "weight", &li->weight);
         } //end if
         //if not a stationary item
         if (!(spawnflags & 1))
         {
             if (!AAS_DropToFloor(origin, ic->iteminfo[i].mins, ic->iteminfo[i].maxs))
             {
                 botimport.Print(PRT_MESSAGE, "%s in solid at (%1.1f %1.1f %1.1f)\n",
                                                 classname, origin[0], origin[1], origin[2]);
             } //end if
         } //end if
         //item info of the level item
         li->iteminfo = i;
         //origin of the item
         VectorCopy(origin, li->origin);
         //
         if (goalareanum)
         {
             li->goalareanum = goalareanum;
             VectorCopy(origin, li->goalorigin);
         } //end if
         else
         {
             //get the item goal area and goal origin
             li->goalareanum = AAS_BestReachableArea(origin,
                             ic->iteminfo[i].mins, ic->iteminfo[i].maxs,
                             li->goalorigin);
             if (!li->goalareanum)
             {
                 botimport.Print(PRT_MESSAGE, "%s not reachable for bots at (%1.1f %1.1f %1.1f)\n",
                                                 classname, origin[0], origin[1], origin[2]);
             } //end if
         } //end else
         //
         AddLevelItemToList(li);
     } //end for
     botimport.Print(PRT_MESSAGE, "found %d level items\n", numlevelitems);
 } //end of the function BotInitLevelItems
References AAS_BestReachableArea(), AAS_BestReachableFromJumpPadArea(), AAS_DropToFloor(), AAS_FloatForBSPEpairKey(), AAS_IntForBSPEpairKey(), AAS_Loaded(), AAS_NextBSPEntity(), AAS_PointContents(), AAS_Trace(), AAS_ValueForBSPEpairKey(), AAS_VectorForBSPEpairKey(), AddLevelItemToList(), AllocLevelItem(), botimport, BotInitInfoEntities(), iteminfo_s::classname, CONTENTS_PLAYERCLIP, CONTENTS_SOLID, CONTENTS_WATER, levelitem_s::entitynum, levelitem_s::flags, bsp_trace_s::fraction, levelitem_s::goalareanum, levelitem_s::goalorigin, IFL_NOTBOT, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, IFL_ROAM, InitLevelItemHeap(), itemconfig, levelitem_s::iteminfo, itemconfig_s::iteminfo, levelitems, Log_Write(), MAX_EPAIRKEY, iteminfo_s::maxs, iteminfo_s::mins, iteminfo_s::modelindex, NULL, levelitem_s::number, itemconfig_s::numiteminfo, numlevelitems, levelitem_s::origin, PRT_ERROR, PRT_MESSAGE, levelitem_s::timeout, VectorCopy, and levelitem_s::weight.
Referenced by Export_BotLibLoadMap(), and Init_AI_Export().
BotInterbreedGoalFuzzyLogic()
void BotInterbreedGoalFuzzyLogic (int parent1, int parent2, int child)
Definition at line 226 of file be_ai_goal.c.
 {
     bot_goalstate_t *p1, *p2, *c;
     p1 = BotGoalStateFromHandle(parent1);
     p2 = BotGoalStateFromHandle(parent2);
     c = BotGoalStateFromHandle(child);
     if (!p1 || !p2 || !c)
         return;
     InterbreedWeightConfigs(p1->itemweightconfig, p2->itemweightconfig,
                                     c->itemweightconfig);
 } //end of the function BotInterbreedingGoalFuzzyLogic
References BotGoalStateFromHandle(), InterbreedWeightConfigs(), and bot_goalstate_s::itemweightconfig.
Referenced by Init_AI_Export().
BotItemGoalInVisButNotVisible()
int BotItemGoalInVisButNotVisible (int viewer, vec3_t eye, vec3_t viewangles, bot_goal_t * goal)
Definition at line 1648 of file be_ai_goal.c.
 {
     aas_entityinfo_t entinfo;
     bsp_trace_t trace;
     vec3_t middle;
     if (!(goal->flags & GFL_ITEM)) return qfalse;
     //
     VectorAdd(goal->mins, goal->mins, middle);
     VectorScale(middle, 0.5, middle);
     VectorAdd(goal->origin, middle, middle);
     //
     trace = AAS_Trace(eye, NULL, NULL, middle, viewer, CONTENTS_SOLID);
     //if the goal middle point is visible
     if (trace.fraction >= 1)
     {
         //the goal entity number doesn't have to be valid
         //just assume it's valid
         if (goal->entitynum <= 0)
             return qfalse;
         //
         //if the entity data isn't valid
         AAS_EntityInfo(goal->entitynum, &entinfo);
         //NOTE: for some wacko reason entities are sometimes
         // not updated
         //if (!entinfo.valid) return qtrue;
         if (entinfo.ltime < AAS_Time() - 0.5)
             return qtrue;
     } //end if
     return qfalse;
 } //end of the function BotItemGoalInVisButNotVisible
References AAS_EntityInfo(), AAS_Time(), AAS_Trace(), CONTENTS_SOLID, bot_goal_s::entitynum, bot_goal_s::flags, bsp_trace_s::fraction, GFL_ITEM, aas_entityinfo_s::ltime, bot_goal_s::mins, NULL, bot_goal_s::origin, qfalse, qtrue, VectorAdd, and VectorScale.
Referenced by Init_AI_Export().
BotLoadItemWeights()
int BotLoadItemWeights (int goalstate, char * filename)
Definition at line 1701 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return BLERR_CANNOTLOADITEMWEIGHTS;
     //load the weight configuration
     gs->itemweightconfig = ReadWeightConfig(filename);
     if (!gs->itemweightconfig)
     {
         botimport.Print(PRT_FATAL, "couldn't load weights\n");
         return BLERR_CANNOTLOADITEMWEIGHTS;
     } //end if
     //if there's no item configuration
     if (!itemconfig) return BLERR_CANNOTLOADITEMWEIGHTS;
     //create the item weight index
     gs->itemweightindex = ItemWeightIndex(gs->itemweightconfig, itemconfig);
     //everything went ok
     return BLERR_NOERROR;
 } //end of the function BotLoadItemWeights
References BLERR_CANNOTLOADITEMWEIGHTS, BLERR_NOERROR, BotGoalStateFromHandle(), botimport, itemconfig, bot_goalstate_s::itemweightconfig, bot_goalstate_s::itemweightindex, ItemWeightIndex(), PRT_FATAL, and ReadWeightConfig().
Referenced by Init_AI_Export().
BotMutateGoalFuzzyLogic()
void BotMutateGoalFuzzyLogic (int goalstate, float range)
Definition at line 260 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     EvolveWeightConfig(gs->itemweightconfig);
 } //end of the function BotMutateGoalFuzzyLogic
References BotGoalStateFromHandle(), EvolveWeightConfig(), and bot_goalstate_s::itemweightconfig.
Referenced by Init_AI_Export().
BotPopGoal()
void BotPopGoal (int goalstate)
Definition at line 1234 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     if (gs->goalstacktop > 0) gs->goalstacktop--;
 } //end of the function BotPopGoal
References BotGoalStateFromHandle(), and bot_goalstate_s::goalstacktop.
Referenced by Init_AI_Export().
BotPushGoal()
void BotPushGoal (int goalstate, bot_goal_t * goal)
Definition at line 1213 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     if (gs->goalstacktop >= MAX_GOALSTACK-1)
     {
         botimport.Print(PRT_ERROR, "goal heap overflow\n");
         BotDumpGoalStack(goalstate);
         return;
     } //end if
     gs->goalstacktop++;
     Com_Memcpy(&gs->goalstack[gs->goalstacktop], goal, sizeof(bot_goal_t));
 } //end of the function BotPushGoal
References BotDumpGoalStack(), BotGoalStateFromHandle(), botimport, Com_Memcpy, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, MAX_GOALSTACK, and PRT_ERROR.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), and Init_AI_Export().
BotRemoveFromAvoidGoals()
void BotRemoveFromAvoidGoals (int goalstate, int number)
Definition at line 778 of file be_ai_goal.c.
 {
     int i;
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     //don't use the goals the bot wants to avoid
     for (i = 0; i < MAX_AVOIDGOALS; i++)
     {
         if (gs->avoidgoals[i] == number && gs->avoidgoaltimes[i] >= AAS_Time())
         {
             gs->avoidgoaltimes[i] = 0;
             return;
         } //end if
     } //end for
 } //end of the function BotRemoveFromAvoidGoals
References AAS_Time(), bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalStateFromHandle(), and MAX_AVOIDGOALS.
Referenced by Init_AI_Export().
BotResetAvoidGoals()
void BotResetAvoidGoals (int goalstate)
Definition at line 707 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     Com_Memset(gs->avoidgoals, 0, MAX_AVOIDGOALS * sizeof(int));
     Com_Memset(gs->avoidgoaltimes, 0, MAX_AVOIDGOALS * sizeof(float));
 } //end of the function BotResetAvoidGoals
References bot_goalstate_s::avoidgoals, bot_goalstate_s::avoidgoaltimes, BotGoalStateFromHandle(), Com_Memset, and MAX_AVOIDGOALS.
Referenced by BotResetGoalState(), and Init_AI_Export().
BotResetGoalState()
void BotResetGoalState (int goalstate)
Definition at line 1685 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs) return;
     Com_Memset(gs->goalstack, 0, MAX_GOALSTACK * sizeof(bot_goal_t));
     gs->goalstacktop = 0;
     BotResetAvoidGoals(goalstate);
 } //end of the function BotResetGoalState
References BotGoalStateFromHandle(), BotResetAvoidGoals(), Com_Memset, bot_goalstate_s::goalstack, bot_goalstate_s::goalstacktop, and MAX_GOALSTACK.
Referenced by Init_AI_Export().
BotSaveGoalFuzzyLogic()
void BotSaveGoalFuzzyLogic (int goalstate, char * filename)
Definition at line 246 of file be_ai_goal.c.
 {
     //bot_goalstate_t *gs;
     //gs = BotGoalStateFromHandle(goalstate);
     //if (!gs) return;
     //WriteWeightConfig(filename, gs->itemweightconfig);
 } //end of the function BotSaveGoalFuzzyLogic
Referenced by Init_AI_Export().
BotSetAvoidGoalTime()
void BotSetAvoidGoalTime (int goalstate, int number, float avoidtime)
Definition at line 824 of file be_ai_goal.c.
 {
     bot_goalstate_t *gs;
     levelitem_t *li;
     gs = BotGoalStateFromHandle(goalstate);
     if (!gs)
         return;
     if (avoidtime < 0)
     {
         if (!itemconfig)
             return;
         //
         for (li = levelitems; li; li = li->next)
         {
             if (li->number == number)
             {
                 avoidtime = itemconfig->iteminfo[li->iteminfo].respawntime;
                 if (!avoidtime)
                     avoidtime = AVOID_DEFAULT_TIME;
                 if (avoidtime < AVOID_MINIMUM_TIME)
                     avoidtime = AVOID_MINIMUM_TIME;
                 BotAddToAvoidGoals(gs, number, avoidtime);
                 return;
             } //end for
         } //end for
         return;
     } //end if
     else
     {
         BotAddToAvoidGoals(gs, number, avoidtime);
     } //end else
 } //end of the function BotSetAvoidGoalTime
References AVOID_DEFAULT_TIME, AVOID_MINIMUM_TIME, BotAddToAvoidGoals(), BotGoalStateFromHandle(), itemconfig, levelitem_s::iteminfo, itemconfig_s::iteminfo, levelitems, levelitem_s::next, levelitem_s::number, and iteminfo_s::respawntime.
Referenced by Init_AI_Export().
BotSetupGoalAI()
int BotSetupGoalAI (void)
Definition at line 1785 of file be_ai_goal.c.
 {
     char *filename;
     //check if teamplay is on
     g_gametype = LibVarValue("g_gametype", "0");
     //item configuration file
     filename = LibVarString("itemconfig", "items.c");
     //load the item configuration
     itemconfig = LoadItemConfig(filename);
     if (!itemconfig)
     {
         botimport.Print(PRT_FATAL, "couldn't load item config\n");
         return BLERR_CANNOTLOADITEMCONFIG;
     } //end if
     //
     droppedweight = LibVar("droppedweight", "1000");
     //everything went ok
     return BLERR_NOERROR;
 } //end of the function BotSetupGoalAI
References BLERR_CANNOTLOADITEMCONFIG, BLERR_NOERROR, botimport, droppedweight, g_gametype, itemconfig, LibVar(), LibVarString(), LibVarValue(), LoadItemConfig(), and PRT_FATAL.
Referenced by Export_BotLibSetup().
BotShutdownGoalAI()
void BotShutdownGoalAI (void)
Definition at line 1811 of file be_ai_goal.c.
 {
     int i;
     if (itemconfig) FreeMemory(itemconfig);
     itemconfig = NULL;
     if (levelitemheap) FreeMemory(levelitemheap);
     levelitemheap = NULL;
     freelevelitems = NULL;
     levelitems = NULL;
     numlevelitems = 0;
     BotFreeInfoEntities();
     for (i = 1; i <= MAX_CLIENTS; i++)
     {
         if (botgoalstates[i])
         {
             BotFreeGoalState(i);
         } //end if
     } //end for
 } //end of the function BotShutdownGoalAI
References BotFreeGoalState(), BotFreeInfoEntities(), botgoalstates, freelevelitems, FreeMemory(), itemconfig, levelitemheap, levelitems, MAX_CLIENTS, NULL, and numlevelitems.
Referenced by Export_BotLibShutdown().
BotTouchingGoal()
int BotTouchingGoal (vec3_t origin, bot_goal_t * goal)
Definition at line 1619 of file be_ai_goal.c.
 {
     int i;
     vec3_t boxmins, boxmaxs;
     vec3_t absmins, absmaxs;
     vec3_t safety_maxs = {0, 0, 0}; //{4, 4, 10};
     vec3_t safety_mins = {0, 0, 0}; //{-4, -4, 0};
     AAS_PresenceTypeBoundingBox(PRESENCE_NORMAL, boxmins, boxmaxs);
     VectorSubtract(goal->mins, boxmaxs, absmins);
     VectorSubtract(goal->maxs, boxmins, absmaxs);
     VectorAdd(absmins, goal->origin, absmins);
     VectorAdd(absmaxs, goal->origin, absmaxs);
     //make the box a little smaller for safety
     VectorSubtract(absmaxs, safety_maxs, absmaxs);
     VectorSubtract(absmins, safety_mins, absmins);
     for (i = 0; i < 3; i++)
     {
         if (origin[i] < absmins[i] || origin[i] > absmaxs[i]) return qfalse;
     } //end for
     return qtrue;
 } //end of the function BotTouchingGoal
References AAS_PresenceTypeBoundingBox(), bot_goal_s::maxs, bot_goal_s::mins, bot_goal_s::origin, PRESENCE_NORMAL, qfalse, qtrue, VectorAdd, and VectorSubtract.
Referenced by Init_AI_Export().
BotUpdateEntityItems()
void BotUpdateEntityItems (void)
Definition at line 1020 of file be_ai_goal.c.
 {
     int ent, i, modelindex;
     vec3_t dir;
     levelitem_t *li, *nextli;
     aas_entityinfo_t entinfo;
     itemconfig_t *ic;
     //timeout current entity items if necessary
     for (li = levelitems; li; li = nextli)
     {
         nextli = li->next;
         //if it is an item that will time out
         if (li->timeout)
         {
             //timeout the item
             if (li->timeout < AAS_Time())
             {
                 RemoveLevelItemFromList(li);
                 FreeLevelItem(li);
             } //end if
         } //end if
     } //end for
     //find new entity items
     ic = itemconfig;
     if (!itemconfig) return;
     //
     for (ent = AAS_NextEntity(0); ent; ent = AAS_NextEntity(ent))
     {
         if (AAS_EntityType(ent) != ET_ITEM) continue;
         //get the model index of the entity
         modelindex = AAS_EntityModelindex(ent);
         //
         if (!modelindex) continue;
         //get info about the entity
         AAS_EntityInfo(ent, &entinfo);
         //FIXME: don't do this
         //skip all floating items for now
         //if (entinfo.groundent != ENTITYNUM_WORLD) continue;
         //if the entity is still moving
         if (entinfo.origin[0] != entinfo.lastvisorigin[0] ||
                 entinfo.origin[1] != entinfo.lastvisorigin[1] ||
                 entinfo.origin[2] != entinfo.lastvisorigin[2]) continue;
         //check if the entity is already stored as a level item
         for (li = levelitems; li; li = li->next)
         {
             //if the level item is linked to an entity
             if (li->entitynum && li->entitynum == ent)
             {
                 //the entity is re-used if the models are different
                 if (ic->iteminfo[li->iteminfo].modelindex != modelindex)
                 {
                     //remove this level item
                     RemoveLevelItemFromList(li);
                     FreeLevelItem(li);
                     li = NULL;
                     break;
                 } //end if
                 else
                 {
                     if (entinfo.origin[0] != li->origin[0] ||
                         entinfo.origin[1] != li->origin[1] ||
                         entinfo.origin[2] != li->origin[2])
                     {
                         VectorCopy(entinfo.origin, li->origin);
                         //also update the goal area number
                         li->goalareanum = AAS_BestReachableArea(li->origin,
                                         ic->iteminfo[li->iteminfo].mins, ic->iteminfo[li->iteminfo].maxs,
                                         li->goalorigin);
                     } //end if
                     break;
                 } //end else
             } //end if
         } //end for
         if (li) continue;
         //try to link the entity to a level item
         for (li = levelitems; li; li = li->next)
         {
             //if this level item is already linked
             if (li->entitynum) continue;
             //
             if (g_gametype == GT_SINGLE_PLAYER) {
                 if (li->flags & IFL_NOTSINGLE) continue;
             }
             else if (g_gametype >= GT_TEAM) {
                 if (li->flags & IFL_NOTTEAM) continue;
             }
             else {
                 if (li->flags & IFL_NOTFREE) continue;
             }
             //if the model of the level item and the entity are the same
             if (ic->iteminfo[li->iteminfo].modelindex == modelindex)
             {
                 //check if the entity is very close
                 VectorSubtract(li->origin, entinfo.origin, dir);
                 if (VectorLength(dir) < 30)
                 {
                     //found an entity for this level item
                     li->entitynum = ent;
                     //if the origin is different
                     if (entinfo.origin[0] != li->origin[0] ||
                         entinfo.origin[1] != li->origin[1] ||
                         entinfo.origin[2] != li->origin[2])
                     {
                         //update the level item origin
                         VectorCopy(entinfo.origin, li->origin);
                         //also update the goal area number
                         li->goalareanum = AAS_BestReachableArea(li->origin,
                                         ic->iteminfo[li->iteminfo].mins, ic->iteminfo[li->iteminfo].maxs,
                                         li->goalorigin);
                     } //end if
 #ifdef DEBUG
                     Log_Write("linked item %s to an entity", ic->iteminfo[li->iteminfo].classname);
 #endif //DEBUG
                     break;
                 } //end if
             } //end else
         } //end for
         if (li) continue;
         //check if the model is from a known item
         for (i = 0; i < ic->numiteminfo; i++)
         {
             if (ic->iteminfo[i].modelindex == modelindex)
             {
                 break;
             } //end if
         } //end for
         //if the model is not from a known item
         if (i >= ic->numiteminfo) continue;
         //allocate a new level item
         li = AllocLevelItem();
         //
         if (!li) continue;
         //entity number of the level item
         li->entitynum = ent;
         //number for the level item
         li->number = numlevelitems + ent;
         //set the item info index for the level item
         li->iteminfo = i;
         //origin of the item
         VectorCopy(entinfo.origin, li->origin);
         //get the item goal area and goal origin
         li->goalareanum = AAS_BestReachableArea(li->origin,
                                     ic->iteminfo[i].mins, ic->iteminfo[i].maxs,
                                     li->goalorigin);
         //never go for items dropped into jumppads
         if (AAS_AreaJumpPad(li->goalareanum))
         {
             FreeLevelItem(li);
             continue;
         } //end if
         //time this item out after 30 seconds
         //dropped items disappear after 30 seconds
         li->timeout = AAS_Time() + 30;
         //add the level item to the list
         AddLevelItemToList(li);
         //botimport.Print(PRT_MESSAGE, "found new level item %s\n", ic->iteminfo[i].classname);
     } //end for
     /*
     for (li = levelitems; li; li = li->next)
     {
         if (!li->entitynum)
         {
             BotFindEntityForLevelItem(li);
         } //end if
     } //end for*/
 } //end of the function BotUpdateEntityItems
References AAS_AreaJumpPad(), AAS_BestReachableArea(), AAS_EntityInfo(), AAS_EntityModelindex(), AAS_EntityType(), AAS_NextEntity(), AAS_Time(), AddLevelItemToList(), AllocLevelItem(), iteminfo_s::classname, levelitem_s::entitynum, ET_ITEM, levelitem_s::flags, FreeLevelItem(), g_gametype, levelitem_s::goalareanum, levelitem_s::goalorigin, GT_SINGLE_PLAYER, GT_TEAM, IFL_NOTFREE, IFL_NOTSINGLE, IFL_NOTTEAM, itemconfig, levelitem_s::iteminfo, itemconfig_s::iteminfo, aas_entityinfo_s::lastvisorigin, levelitems, Log_Write(), iteminfo_s::maxs, iteminfo_s::mins, iteminfo_s::modelindex, levelitem_s::next, NULL, levelitem_s::number, itemconfig_s::numiteminfo, numlevelitems, levelitem_s::origin, aas_entityinfo_s::origin, RemoveLevelItemFromList(), levelitem_s::timeout, VectorCopy, VectorLength(), and VectorSubtract.
Referenced by Init_AI_Export().
FreeLevelItem()
void FreeLevelItem (levelitem_t * li)
Definition at line 422 of file be_ai_goal.c.
 {
     li->next = freelevelitems;
     freelevelitems = li;
 } //end of the function FreeLevelItem
References freelevelitems, and levelitem_s::next.
Referenced by BotUpdateEntityItems().
InitLevelItemHeap()
void InitLevelItemHeap (void)
Definition at line 378 of file be_ai_goal.c.
 {
     int i, max_levelitems;
     if (levelitemheap) FreeMemory(levelitemheap);
     max_levelitems = (int) LibVarValue("max_levelitems", "256");
     levelitemheap = (levelitem_t *) GetClearedMemory(max_levelitems * sizeof(levelitem_t));
     for (i = 0; i < max_levelitems-1; i++)
     {
         levelitemheap[i].next = &levelitemheap[i + 1];
     } //end for
     levelitemheap[max_levelitems-1].next = NULL;
     //
     freelevelitems = levelitemheap;
 } //end of the function InitLevelItemHeap
References freelevelitems, FreeMemory(), GetClearedMemory(), int(), levelitemheap, LibVarValue(), levelitem_s::next, and NULL.
Referenced by BotInitLevelItems().
ItemWeightIndex()
int* ItemWeightIndex (weightconfig_t * iwc, itemconfig_t * ic)
Definition at line 355 of file be_ai_goal.c.
 {
     int *index, i;
     //initialize item weight index
     index = (int *) GetClearedMemory(sizeof(int) * ic->numiteminfo);
     for (i = 0; i < ic->numiteminfo; i++)
     {
         index[i] = FindFuzzyWeight(iwc, ic->iteminfo[i].classname);
         if (index[i] < 0)
         {
             Log_Write("item info %d \"%s\" has no fuzzy weight\r\n", i, ic->iteminfo[i].classname);
         } //end if
     } //end for
     return index;
 } //end of the function ItemWeightIndex
References iteminfo_s::classname, FindFuzzyWeight(), GetClearedMemory(), itemconfig_s::iteminfo, Log_Write(), and itemconfig_s::numiteminfo.
Referenced by BotLoadItemWeights().
LoadItemConfig()
itemconfig_t* LoadItemConfig (char * filename)
Definition at line 274 of file be_ai_goal.c.
 {
     int max_iteminfo;
     token_t token;
     char path[MAX_QPATH];
     source_t *source;
     itemconfig_t *ic;
     iteminfo_t *ii;
     max_iteminfo = (int) LibVarValue("max_iteminfo", "256");
     if (max_iteminfo < 0)
     {
         botimport.Print(PRT_ERROR, "max_iteminfo = %d\n", max_iteminfo);
         max_iteminfo = 256;
         LibVarSet( "max_iteminfo", "256" );
     }
     Q_strncpyz(path, filename, sizeof(path));
     PC_SetBaseFolder(BOTFILESBASEFOLDER);
     source = LoadSourceFile( path );
     if( !source ) {
         botimport.Print( PRT_ERROR, "counldn't load %s\n", path );
         return NULL;
     } //end if
     //initialize item config
     ic = (itemconfig_t *) GetClearedHunkMemory(sizeof(itemconfig_t) +
                                                         max_iteminfo * sizeof(iteminfo_t));
     ic->iteminfo = (iteminfo_t *) ((char *) ic + sizeof(itemconfig_t));
     ic->numiteminfo = 0;
     //parse the item config file
     while(PC_ReadToken(source, &token))
     {
         if (!strcmp(token.string, "iteminfo"))
         {
             if (ic->numiteminfo >= max_iteminfo)
             {
                 SourceError(source, "more than %d item info defined", max_iteminfo);
                 FreeMemory(ic);
                 FreeSource(source);
                 return NULL;
             } //end if
             ii = &ic->iteminfo[ic->numiteminfo];
             Com_Memset(ii, 0, sizeof(iteminfo_t));
             if (!PC_ExpectTokenType(source, TT_STRING, 0, &token))
             {
                 FreeMemory(ic);
                 FreeSource(source);
                 return NULL;
             } //end if
             StripDoubleQuotes(token.string);
             Q_strncpyz(ii->classname, token.string, sizeof(ii->classname));
             if (!ReadStructure(source, &iteminfo_struct, (char *) ii))
             {
                 FreeMemory(ic);
                 FreeSource(source);
                 return NULL;
             } //end if
             ii->number = ic->numiteminfo;
             ic->numiteminfo++;
         } //end if
         else
         {
             SourceError(source, "unknown definition %s", token.string);
             FreeMemory(ic);
             FreeSource(source);
             return NULL;
         } //end else
     } //end while
     FreeSource(source);
     //
     if (!ic->numiteminfo) botimport.Print(PRT_WARNING, "no item info loaded\n");
     botimport.Print(PRT_MESSAGE, "loaded %s\n", path);
     return ic;
 } //end of the function LoadItemConfig
References BOTFILESBASEFOLDER, botimport, iteminfo_s::classname, Com_Memset, FreeMemory(), FreeSource(), GetClearedHunkMemory(), int(), itemconfig_s::iteminfo, iteminfo_struct, LibVarSet(), LibVarValue(), LoadSourceFile(), MAX_QPATH, NULL, itemconfig_s::numiteminfo, PC_ExpectTokenType(), PC_ReadToken(), PC_SetBaseFolder(), PRT_ERROR, PRT_MESSAGE, PRT_WARNING, Q_strncpyz(), ReadStructure(), SourceError(), token_s::string, StripDoubleQuotes(), and TT_STRING.
Referenced by BotSetupGoalAI().
RemoveLevelItemFromList()
void RemoveLevelItemFromList (levelitem_t * li)
Definition at line 446 of file be_ai_goal.c.
 {
     if (li->prev) li->prev->next = li->next;
     else levelitems = li->next;
     if (li->next) li->next->prev = li->prev;
 } //end of the function RemoveLevelItemFromList
References levelitems, levelitem_s::next, and levelitem_s::prev.
Referenced by BotUpdateEntityItems().
Variable Documentation
botgoalstates
bot_goalstate_t* botgoalstates[MAX_CLIENTS+1]
Definition at line 183 of file be_ai_goal.c.
Referenced by BotAllocGoalState(), BotFreeGoalState(), BotGoalStateFromHandle(), and BotShutdownGoalAI().
campspots
campspot_t* campspots = NULL
Definition at line 194 of file be_ai_goal.c.
Referenced by BotFreeInfoEntities(), BotGetNextCampSpotGoal(), and BotInitInfoEntities().
droppedweight
libvar_t* droppedweight = NULL
Definition at line 198 of file be_ai_goal.c.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), and BotSetupGoalAI().
freelevelitems
levelitem_t* freelevelitems = NULL
Definition at line 188 of file be_ai_goal.c.
Referenced by AllocLevelItem(), BotShutdownGoalAI(), FreeLevelItem(), and InitLevelItemHeap().
g_gametype
int g_gametype = 0
Definition at line 196 of file be_ai_goal.c.
Referenced by AddScore(), BotChooseLTGItem(), BotChooseNBGItem(), BotGetLevelItemGoal(), BotSetupGoalAI(), BotUpdateEntityItems(), CheckAlmostCapture(), ClearRegisteredItems(), ClientBegin(), ClientConnect(), ClientDisconnect(), ClientEvents(), ClientSpawn(), ClientUserinfoChanged(), Cmd_Follow_f(), Cmd_FollowCycle_f(), Cmd_LevelShot_f(), Cmd_Team_f(), FireWeapon(), G_AddBot(), G_CheckBotSpawn(), G_CheckMinimumPlayers(), G_CheckTeamItems(), G_Damage(), G_InitBots(), G_InitSessionData(), G_InitWorldSession(), G_RankRunFrame(), G_Say(), G_SayTo(), G_SpawnGEntityFromSpawnVars(), G_WriteSessionData(), LaunchItem(), OnSameTeam(), Pickup_Powerup(), Pickup_Team(), Pickup_Weapon(), player_die(), SetTeam(), Svcmd_AbortPodium_f(), Team_CheckHurtCarrier(), Team_FragBonuses(), Team_InitGame(), Team_ResetFlags(), Team_SetFlagStatus(), Team_TouchEnemyFlag(), Team_TouchOurFlag(), TossClientItems(), Touch_Item(), and UpdateTournamentInfo().
itemconfig
itemconfig_t* itemconfig = NULL
Definition at line 185 of file be_ai_goal.c.
Referenced by BotChooseLTGItem(), BotChooseNBGItem(), BotFindEntityForLevelItem(), BotGetLevelItemGoal(), BotGoalName(), BotInitLevelItems(), BotLoadItemWeights(), BotSetAvoidGoalTime(), BotSetupGoalAI(), BotShutdownGoalAI(), and BotUpdateEntityItems().
iteminfo_fields
fielddef_t iteminfo_fields[]
Initial value:
=
{
{"name", ITEMINFO_OFS(name), FT_STRING},
{"model", ITEMINFO_OFS(model), FT_STRING},
{"modelindex", ITEMINFO_OFS(modelindex), FT_INT},
{"type", ITEMINFO_OFS(type), FT_INT},
{"index", ITEMINFO_OFS(index), FT_INT},
{"respawntime", ITEMINFO_OFS(respawntime), FT_FLOAT},
{"mins", ITEMINFO_OFS(mins), FT_FLOAT|FT_ARRAY, 3},
{"maxs", ITEMINFO_OFS(maxs), FT_FLOAT|FT_ARRAY, 3},
{NULL, 0, 0}
}
Definition at line 143 of file be_ai_goal.c.
iteminfo_struct
structdef_t iteminfo_struct
Initial value:
=
{
    sizeof(iteminfo_t), iteminfo_fields
}
Definition at line 156 of file be_ai_goal.c.
Referenced by LoadItemConfig().
levelitemheap
levelitem_t* levelitemheap = NULL
Definition at line 187 of file be_ai_goal.c.
Referenced by BotShutdownGoalAI(), and InitLevelItemHeap().
levelitems
levelitem_t* levelitems = NULL
Definition at line 189 of file be_ai_goal.c.
Referenced by AddLevelItemToList(), BotChooseLTGItem(), BotChooseNBGItem(), BotGetLevelItemGoal(), BotGoalName(), BotInitLevelItems(), BotSetAvoidGoalTime(), BotShutdownGoalAI(), BotUpdateEntityItems(), and RemoveLevelItemFromList().
maplocations
maplocation_t* maplocations = NULL
Definition at line 192 of file be_ai_goal.c.
Referenced by BotFreeInfoEntities(), BotGetMapLocationGoal(), and BotInitInfoEntities().
numlevelitems
int numlevelitems = 0
Definition at line 190 of file be_ai_goal.c.
Referenced by BotInitLevelItems(), BotShutdownGoalAI(), and BotUpdateEntityItems().