ioquake3 doxygen: botlib_import_s Struct Reference
botlib_import_s Struct Reference
#include <botlib.h>
Public Member Functions
void (QDECL *Print)(int type
char __attribute__ ((format(printf, 2, 3)))
Public Attributes
char * fmt
void(* Trace)(bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
void(* EntityTrace)(bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int entnum, int contentmask)
int(* PointContents)(vec3_t point)
int(* inPVS)(vec3_t p1, vec3_t p2)
char *(* BSPEntityData)(void)
void(* BSPModelMinsMaxsOrigin)(int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
void(* BotClientCommand)(int client, char *command)
void *(* GetMemory)(int size)
void(* FreeMemory)(void *ptr)
int(* AvailableMemory)(void)
void *(* HunkAlloc)(int size)
int(* FS_FOpenFile)(const char *qpath, fileHandle_t *file, fsMode_t mode)
int(* FS_Read)(void *buffer, int len, fileHandle_t f)
int(* FS_Write)(const void *buffer, int len, fileHandle_t f)
void(* FS_FCloseFile)(fileHandle_t f)
int(* FS_Seek)(fileHandle_t f, long offset, int origin)
int(* DebugLineCreate)(void)
void(* DebugLineDelete)(int line)
void(* DebugLineShow)(int line, vec3_t start, vec3_t end, int color)
int(* DebugPolygonCreate)(int color, int numPoints, vec3_t *points)
void(* DebugPolygonDelete)(int id)
Detailed Description
Definition at line 170 of file botlib.h.
Member Function Documentation
__attribute__()
char botlib_import_s::__attribute__ ((format(printf, 2, 3)))
void()
botlib_import_s::void (QDECL * Print)
Member Data Documentation
AvailableMemory
int(* botlib_import_s::AvailableMemory) (void)
Definition at line 191 of file botlib.h.
Referenced by AvailableMemory(), and SV_BotInitBotLib().
BotClientCommand
void(* botlib_import_s::BotClientCommand) (int client, char *command)
Definition at line 187 of file botlib.h.
Referenced by EA_Command(), EA_DropInv(), EA_DropItem(), EA_Say(), EA_SayTeam(), EA_Tell(), EA_UseInv(), EA_UseItem(), and SV_BotInitBotLib().
BSPEntityData
char*(* botlib_import_s::BSPEntityData) (void)
Definition at line 183 of file botlib.h.
Referenced by AAS_LoadBSPFile(), and SV_BotInitBotLib().
BSPModelMinsMaxsOrigin
void(* botlib_import_s::BSPModelMinsMaxsOrigin) (int modelnum, vec3_t angles, vec3_t mins, vec3_t maxs, vec3_t origin)
Definition at line 185 of file botlib.h.
Referenced by AAS_BSPModelMinsMaxsOrigin(), and SV_BotInitBotLib().
DebugLineCreate
int(* botlib_import_s::DebugLineCreate) (void)
Definition at line 200 of file botlib.h.
Referenced by AAS_DebugLine(), AAS_DrawPermanentCross(), AAS_DrawPlaneCross(), AAS_PermanentLine(), AAS_ShowArea(), AAS_ShowBoundingBox(), BotExportTest(), BotTravel_Grapple(), and SV_BotInitBotLib().
DebugLineDelete
void(* botlib_import_s::DebugLineDelete) (int line)
Definition at line 201 of file botlib.h.
Referenced by AAS_ClearShownDebugLines(), and SV_BotInitBotLib().
DebugLineShow
void(* botlib_import_s::DebugLineShow) (int line, vec3_t start, vec3_t end, int color)
Definition at line 202 of file botlib.h.
Referenced by AAS_DebugLine(), AAS_DrawPermanentCross(), AAS_DrawPlaneCross(), AAS_PermanentLine(), AAS_ShowArea(), AAS_ShowBoundingBox(), BotExportTest(), BotTravel_Grapple(), and SV_BotInitBotLib().
DebugPolygonCreate
int(* botlib_import_s::DebugPolygonCreate) (int color, int numPoints, vec3_t *points)
Definition at line 204 of file botlib.h.
Referenced by AAS_ShowPolygon(), and SV_BotInitBotLib().
DebugPolygonDelete
void(* botlib_import_s::DebugPolygonDelete) (int id)
Definition at line 205 of file botlib.h.
Referenced by AAS_ClearShownPolygons(), and SV_BotInitBotLib().
EntityTrace
void(* botlib_import_s::EntityTrace) (bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int entnum, int contentmask)
Definition at line 177 of file botlib.h.
Referenced by AAS_EntityCollision(), and SV_BotInitBotLib().
fmt
char* botlib_import_s::fmt
Definition at line 173 of file botlib.h.
FreeMemory
void(* botlib_import_s::FreeMemory) (void *ptr)
Definition at line 190 of file botlib.h.
Referenced by FreeMemory(), and SV_BotInitBotLib().
FS_FCloseFile
void(* botlib_import_s::FS_FCloseFile) (fileHandle_t f)
Definition at line 197 of file botlib.h.
Referenced by AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_ReadRouteCache(), AAS_WriteAASFile(), AAS_WriteRouteCache(), LoadScriptFile(), and SV_BotInitBotLib().
FS_FOpenFile
int(* botlib_import_s::FS_FOpenFile) (const char *qpath, fileHandle_t *file, fsMode_t mode)
Definition at line 194 of file botlib.h.
Referenced by AAS_LoadAASFile(), AAS_ReadRouteCache(), AAS_WriteAASFile(), AAS_WriteRouteCache(), LoadScriptFile(), and SV_BotInitBotLib().
FS_Read
int(* botlib_import_s::FS_Read) (void *buffer, int len, fileHandle_t f)
Definition at line 195 of file botlib.h.
Referenced by AAS_LoadAASFile(), AAS_LoadAASLump(), AAS_ReadCache(), AAS_ReadRouteCache(), LoadScriptFile(), and SV_BotInitBotLib().
FS_Seek
int(* botlib_import_s::FS_Seek) (fileHandle_t f, long offset, int origin)
Definition at line 198 of file botlib.h.
Referenced by AAS_LoadAASLump(), AAS_WriteAASFile(), and SV_BotInitBotLib().
FS_Write
int(* botlib_import_s::FS_Write) (const void *buffer, int len, fileHandle_t f)
Definition at line 196 of file botlib.h.
Referenced by AAS_WriteAASFile(), AAS_WriteAASLump(), AAS_WriteRouteCache(), and SV_BotInitBotLib().
GetMemory
void*(* botlib_import_s::GetMemory) (int size)
Definition at line 189 of file botlib.h.
Referenced by GetMemory(), and SV_BotInitBotLib().
HunkAlloc
void*(* botlib_import_s::HunkAlloc) (int size)
Definition at line 192 of file botlib.h.
Referenced by GetHunkMemory(), and SV_BotInitBotLib().
inPVS
int(* botlib_import_s::inPVS) (vec3_t p1, vec3_t p2)
Definition at line 181 of file botlib.h.
Referenced by AAS_inPVS(), and SV_BotInitBotLib().
PointContents
int(* botlib_import_s::PointContents) (vec3_t point)
Definition at line 179 of file botlib.h.
Referenced by AAS_PointContents(), and SV_BotInitBotLib().
Trace
void(* botlib_import_s::Trace) (bsp_trace_t *trace, vec3_t start, vec3_t mins, vec3_t maxs, vec3_t end, int passent, int contentmask)
Definition at line 175 of file botlib.h.
Referenced by AAS_Trace(), and SV_BotInitBotLib().