ioquake3 doxygen: C:/entry/dev/ioq3/code/ui/ui_gameinfo.c File Reference
ui_gameinfo.c File Reference
#include "ui_local.h"
Functions
int UI_ParseInfos (char *buf, int max, char *infos[])
static void UI_LoadArenasFromFile (char *filename)
void UI_LoadArenas (void)
void UI_LoadArenasIntoMapList (void)
static void UI_LoadBotsFromFile (char *filename)
void UI_LoadBots (void)
char * UI_GetBotInfoByNumber (int num)
char * UI_GetBotInfoByName (const char *name)
int UI_GetNumBots (void)
char * UI_GetBotNameByNumber (int num)
Variables
int ui_numBots
static char * ui_botInfos [MAX_BOTS]
static int ui_numArenas
static char * ui_arenaInfos [MAX_ARENAS]
static int ui_numSinglePlayerArenas
static int ui_numSpecialSinglePlayerArenas
Function Documentation
UI_GetBotInfoByName()
char* UI_GetBotInfoByName (const char * name)
Definition at line 309 of file ui_gameinfo.c.
{
     int     n;
     char    *value;
     for ( n = 0; n < ui_numBots ; n++ ) {
         value = Info_ValueForKey( ui_botInfos[n], "name" );
         if ( !Q_stricmp( value, name ) ) {
             return ui_botInfos[n];
         }
     }
     return NULL;
 }
References Info_ValueForKey(), NULL, Q_stricmp(), ui_botInfos, and ui_numBots.
UI_GetBotInfoByNumber()
char* UI_GetBotInfoByNumber (int num)
Definition at line 295 of file ui_gameinfo.c.
{
     if( num < 0 || num >= ui_numBots ) {
         trap_Print( va( S_COLOR_RED "Invalid bot number: %i\n", num ) );
         return NULL;
     }
     return ui_botInfos[num];
 }
References NULL, S_COLOR_RED, trap_Print(), ui_botInfos, ui_numBots, and va().
UI_GetBotNameByNumber()
char* UI_GetBotNameByNumber (int num)
Definition at line 328 of file ui_gameinfo.c.
{
     char *info = UI_GetBotInfoByNumber(num);
     if (info) {
         return Info_ValueForKey( info, "name" );
     }
     return "Sarge";
 }
References Info_ValueForKey(), and UI_GetBotInfoByNumber().
Referenced by UI_DrawBotName(), UI_DrawTeamMember(), and UI_RunMenuScript().
UI_GetNumBots()
int UI_GetNumBots (void)
Definition at line 323 of file ui_gameinfo.c.
{
     return ui_numBots;
 }
References ui_numBots.
UI_LoadArenas()
void UI_LoadArenas (void)
Definition at line 135 of file ui_gameinfo.c.
{
     int         numdirs;
     vmCvar_t    arenasFile;
     char        filename[128];
     char        dirlist[1024];
     char*       dirptr;
     int         i;
     int         dirlen;
     ui_numArenas = 0;
     trap_Cvar_Register( &arenasFile, "g_arenasFile", "", CVAR_INIT|CVAR_ROM );
     if( *arenasFile.string ) {
         UI_LoadArenasFromFile(arenasFile.string);
     }
     else {
         UI_LoadArenasFromFile("scripts/arenas.txt");
     }
     // get all arenas from .arena files
     numdirs = trap_FS_GetFileList("scripts", ".arena", dirlist, 1024 );
     dirptr  = dirlist;
     for (i = 0; i < numdirs; i++, dirptr += dirlen+1) {
         dirlen = strlen(dirptr);
         strcpy(filename, "scripts/");
         strcat(filename, dirptr);
         UI_LoadArenasFromFile(filename);
     }
     trap_Print( va( "%i arenas parsed\n", ui_numArenas ) );
     if (UI_OutOfMemory()) {
         trap_Print(S_COLOR_YELLOW"WARNING: not enough memory in pool to load all arenas\n");
     }
 }
References CVAR_INIT, CVAR_ROM, S_COLOR_YELLOW, vmCvar_t::string, trap_Cvar_Register(), trap_FS_GetFileList(), trap_Print(), UI_LoadArenasFromFile(), ui_numArenas, UI_OutOfMemory(), and va().
UI_LoadArenasFromFile()
static void UI_LoadArenasFromFile (char * filename) static
Definition at line 107 of file ui_gameinfo.c.
{
     int             len;
     fileHandle_t    f;
     char            buf[MAX_ARENAS_TEXT];
     len = trap_FS_FOpenFile( filename, &f, FS_READ );
     if ( !f ) {
         trap_Print( va( S_COLOR_RED "file not found: %s\n", filename ) );
         return;
     }
     if ( len >= MAX_ARENAS_TEXT ) {
         trap_Print( va( S_COLOR_RED "file too large: %s is %i, max allowed is %i\n", filename, len, MAX_ARENAS_TEXT ) );
         trap_FS_FCloseFile( f );
         return;
     }
     trap_FS_Read( buf, len, f );
     buf[len] = 0;
     trap_FS_FCloseFile( f );
     ui_numArenas += UI_ParseInfos( buf, MAX_ARENAS - ui_numArenas, &ui_arenaInfos[ui_numArenas] );
 }
References FS_READ, MAX_ARENAS, MAX_ARENAS_TEXT, S_COLOR_RED, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), ui_arenaInfos, ui_numArenas, UI_ParseInfos(), and va().
Referenced by UI_LoadArenas().
UI_LoadArenasIntoMapList()
void UI_LoadArenasIntoMapList (void)
Definition at line 174 of file ui_gameinfo.c.
{
     int         n;
     char        *type;
     uiInfo.mapCount = 0;
     for( n = 0; n < ui_numArenas; n++ ) {
         // determine type
         uiInfo.mapList[uiInfo.mapCount].cinematic = -1;
         uiInfo.mapList[uiInfo.mapCount].mapLoadName = String_Alloc(Info_ValueForKey(ui_arenaInfos[n], "map"));
         uiInfo.mapList[uiInfo.mapCount].mapName = String_Alloc(Info_ValueForKey(ui_arenaInfos[n], "longname"));
         uiInfo.mapList[uiInfo.mapCount].levelShot = -1;
         uiInfo.mapList[uiInfo.mapCount].imageName = String_Alloc(va("levelshots/%s", uiInfo.mapList[uiInfo.mapCount].mapLoadName));
         uiInfo.mapList[uiInfo.mapCount].typeBits = 0;
         type = Info_ValueForKey( ui_arenaInfos[n], "type" );
         // if no type specified, it will be treated as "ffa"
         if( *type ) {
             if( strstr( type, "ffa" ) ) {
                 uiInfo.mapList[uiInfo.mapCount].typeBits |= (1 << GT_FFA);
             }
             if( strstr( type, "tourney" ) ) {
                 uiInfo.mapList[uiInfo.mapCount].typeBits |= (1 << GT_TOURNAMENT);
             }
             if( strstr( type, "ctf" ) ) {
                 uiInfo.mapList[uiInfo.mapCount].typeBits |= (1 << GT_CTF);
             }
             if( strstr( type, "oneflag" ) ) {
                 uiInfo.mapList[uiInfo.mapCount].typeBits |= (1 << GT_1FCTF);
             }
             if( strstr( type, "overload" ) ) {
                 uiInfo.mapList[uiInfo.mapCount].typeBits |= (1 << GT_OBELISK);
             }
             if( strstr( type, "harvester" ) ) {
                 uiInfo.mapList[uiInfo.mapCount].typeBits |= (1 << GT_HARVESTER);
             }
         } else {
             uiInfo.mapList[uiInfo.mapCount].typeBits |= (1 << GT_FFA);
         }
         uiInfo.mapCount++;
         if (uiInfo.mapCount >= MAX_MAPS) {
             break;
         }
     }
 }
References mapInfo::cinematic, GT_1FCTF, GT_CTF, GT_FFA, GT_HARVESTER, GT_OBELISK, GT_TOURNAMENT, mapInfo::imageName, Info_ValueForKey(), mapInfo::levelShot, uiInfo_t::mapCount, uiInfo_t::mapList, mapInfo::mapLoadName, mapInfo::mapName, MAX_MAPS, String_Alloc(), mapInfo::typeBits, ui_arenaInfos, ui_numArenas, uiInfo, and va().
Referenced by UI_RunMenuScript().
UI_LoadBots()
void UI_LoadBots (void)
Definition at line 258 of file ui_gameinfo.c.
{
     vmCvar_t    botsFile;
     int         numdirs;
     char        filename[128];
     char        dirlist[1024];
     char*       dirptr;
     int         i;
     int         dirlen;
     ui_numBots = 0;
     trap_Cvar_Register( &botsFile, "g_botsFile", "", CVAR_INIT|CVAR_ROM );
     if( *botsFile.string ) {
         UI_LoadBotsFromFile(botsFile.string);
     }
     else {
         UI_LoadBotsFromFile("scripts/bots.txt");
     }
     // get all bots from .bot files
     numdirs = trap_FS_GetFileList("scripts", ".bot", dirlist, 1024 );
     dirptr  = dirlist;
     for (i = 0; i < numdirs; i++, dirptr += dirlen+1) {
         dirlen = strlen(dirptr);
         strcpy(filename, "scripts/");
         strcat(filename, dirptr);
         UI_LoadBotsFromFile(filename);
     }
     trap_Print( va( "%i bots parsed\n", ui_numBots ) );
 }
References CVAR_INIT, CVAR_ROM, vmCvar_t::string, trap_Cvar_Register(), trap_FS_GetFileList(), trap_Print(), UI_LoadBotsFromFile(), ui_numBots, and va().
UI_LoadBotsFromFile()
static void UI_LoadBotsFromFile (char * filename) static
Definition at line 228 of file ui_gameinfo.c.
{
     int             len;
     fileHandle_t    f;
     char            buf[MAX_BOTS_TEXT];
     len = trap_FS_FOpenFile( filename, &f, FS_READ );
     if ( !f ) {
         trap_Print( va( S_COLOR_RED "file not found: %s\n", filename ) );
         return;
     }
     if ( len >= MAX_BOTS_TEXT ) {
         trap_Print( va( S_COLOR_RED "file too large: %s is %i, max allowed is %i\n", filename, len, MAX_BOTS_TEXT ) );
         trap_FS_FCloseFile( f );
         return;
     }
     trap_FS_Read( buf, len, f );
     buf[len] = 0;
     trap_FS_FCloseFile( f );
     COM_Compress(buf);
     ui_numBots += UI_ParseInfos( buf, MAX_BOTS - ui_numBots, &ui_botInfos[ui_numBots] );
 }
References COM_Compress(), FS_READ, MAX_BOTS, MAX_BOTS_TEXT, S_COLOR_RED, trap_FS_FCloseFile(), trap_FS_FOpenFile(), trap_FS_Read(), trap_Print(), ui_botInfos, ui_numBots, UI_ParseInfos(), and va().
Referenced by UI_LoadBots().
UI_ParseInfos()
int UI_ParseInfos (char * buf, int max, char * infos[])
Definition at line 51 of file ui_gameinfo.c.
{
     char    *token;
     int     count;
     char    key[MAX_TOKEN_CHARS];
     char    info[MAX_INFO_STRING];
     count = 0;
     while ( 1 ) {
         token = COM_Parse( &buf );
         if ( !token[0] ) {
             break;
         }
         if ( strcmp( token, "{" ) ) {
             Com_Printf( "Missing { in info file\n" );
             break;
         }
         if ( count == max ) {
             Com_Printf( "Max infos exceeded\n" );
             break;
         }
         info[0] = '\0';
         while ( 1 ) {
             token = COM_ParseExt( &buf, qtrue );
             if ( !token[0] ) {
                 Com_Printf( "Unexpected end of info file\n" );
                 break;
             }
             if ( !strcmp( token, "}" ) ) {
                 break;
             }
             Q_strncpyz( key, token, sizeof( key ) );
             token = COM_ParseExt( &buf, qfalse );
             if ( !token[0] ) {
                 strcpy( token, "<NULL>" );
             }
             Info_SetValueForKey( info, key, token );
         }
         //NOTE: extra space for arena number
         infos[count] = UI_Alloc(strlen(info) + strlen("\\num\\") + strlen(va("%d", MAX_ARENAS)) + 1);
         if (infos[count]) {
             strcpy(infos[count], info);
             count++;
         }
     }
     return count;
 }
References COM_Parse(), COM_ParseExt(), Com_Printf(), count, Info_SetValueForKey(), MAX_ARENAS, MAX_INFO_STRING, MAX_TOKEN_CHARS, Q_strncpyz(), qfalse, qtrue, UI_Alloc(), and va().
Variable Documentation
ui_arenaInfos
char* ui_arenaInfos[MAX_ARENAS] static
Definition at line 39 of file ui_gameinfo.c.
Referenced by UI_LoadArenasFromFile(), and UI_LoadArenasIntoMapList().
ui_botInfos
char* ui_botInfos[MAX_BOTS] static
Definition at line 36 of file ui_gameinfo.c.
Referenced by UI_GetBotInfoByName(), UI_GetBotInfoByNumber(), and UI_LoadBotsFromFile().
ui_numArenas
int ui_numArenas static
Definition at line 38 of file ui_gameinfo.c.
Referenced by UI_LoadArenas(), UI_LoadArenasFromFile(), and UI_LoadArenasIntoMapList().
ui_numBots
int ui_numBots
Definition at line 35 of file ui_gameinfo.c.
ui_numSinglePlayerArenas
int ui_numSinglePlayerArenas static
Definition at line 42 of file ui_gameinfo.c.
ui_numSpecialSinglePlayerArenas
int ui_numSpecialSinglePlayerArenas static
Definition at line 43 of file ui_gameinfo.c.